### ISSUE TITLE
journalctl --machine --follow doesn’t work

### ISSUE THREAD

**Issue by lucaswerkmeister** [systemd/systemd#4094] opened 2016-09-03 17:39 UTC
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> systemd 231  
> +PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

> `journalctl --machine MACHINE --follow` should show the ten most recent log entries, then continue showing new ones as they are appended to the journal.
### In case of bug report: Unexpected behaviour you saw

> The ten most recent log entries are shown, then no further output happens. (`journalctl` does not terminate, it just behaves as if no further entries were being appended to the journal.)
### In case of bug report: Steps to reproduce the problem

> ``` sh
> mkosi -o /var/lib/machines/systemd-issue-4094.raw
> machinectl start systemd-issue-4094
> systemd-run --machine systemd-issue-4094 --unit speaking-clock.service /bin/sh -c 'while true; do date; sleep 1; done'
> journalctl --machine systemd-issue-4094 --follow --unit speaking-clock.service
> ```

Perhaps there’s some technical reason why this can’t work, but if that’s the case, `journalctl` should exit with an error, just like `--sync`, `--rotate` and `--flush` already do. (I suppose it would be useful if the ten most recent messages were still printed before this error.)

**Comment by evverx** [comment] 2016-09-04 20:23
Duplicate of https://github.com/systemd/systemd/issues/3927

**Closed as completed by evverx** 2016-09-04 20:23 UTC
Labels: journal, duplicate

**Comment by lucaswerkmeister** [comment] 2016-09-04 20:24
Oops, sorry about the inconvenience. Not sure why I couldn’t find that…
