### ISSUE TITLE
nspawn: network-interface doesn't work with -U

### ISSUE THREAD

**Issue by MorphBonehunter** [systemd/systemd#8649] opened 2018-04-04 07:09 UTC
### Submission type

 - Bug report
- Regression from #8427 / 649030e8cb00b2a9f1767cb8f77f7edb522b1dfb

### systemd version the issue has been seen with

> 238.51 (Arch Linux which means until c58ab03f64890e7db88745a843bd4520e307099b from systemd-stable)

### Used distribution

> Arch Linux (4.15.14)

### In case of bug report: Expected behaviour you didn't see

> Using system-nspawn with `network-interface` together with `-U` should put the mentioned interface in the netns

### In case of bug report: Unexpected behaviour you saw

> The interface isn't put into the namespace

### In case of bug report: Steps to reproduce the problem

```
pacstrap -i -c archtest/

systemd-nspawn -D archtest/ -U --network-interface=lan0
Spawning container archtest on /root/tmp/archtest.
Press ^] three times within 1s to kill container.
Selected user namespace base 35323904 and range 65536.
[root@archtest ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever

systemd-nspawn -D archtest/ --network-interface=lan0
Spawning container archtest on /root/tmp/archtest.
Press ^] three times within 1s to kill container.
[root@archtest ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: lan0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 00:90:f5:e7:aa:75 brd ff:ff:ff:ff:ff:ff
```

**Comment by filbranden** [comment] 2018-04-04 07:15
I believe this is the same as issue #8599.

**Comment by poettering** [comment] 2018-04-05 10:25
Let's close this as duplicate of #8599 then.

Duplicate of #8599

**Closed as completed by poettering** 2018-04-05 10:25 UTC
Labels: nspawn, duplicate
