### ISSUE TITLE
usr.mount unit failure after switching root

### ISSUE THREAD

**Issue by mischief** [systemd/systemd#2960] opened 2016-04-04 21:22 UTC
### Submission type
- [x] Bug report
### systemd version the issue has been seen with

v229
### Used distribution

CoreOS
### In case of bug report: Expected behaviour you didn't see

`usr.mount` should not be in the failed state
### In case of bug report: Unexpected behaviour you saw

a start/fail job for `usr.mount` is triggered by `retroactively_start_dependencies` by the backing device, in this case `dev-vda3.device`, however, usr.mount should not be in the inactive state.
### In case of bug report: Steps to reproduce the problem

boot CoreOS with systemd v229. i can provide images or build instructions if necessary.

here's the status after boot when the unit fails:

```
$ systemctl status usr.mount
? usr.mount - /usr
   Loaded: loaded
   Active: failed (Result: resources) since Mon 2016-04-04 21:10:09 UTC; 24s ago
    Where: /usr

Apr 04 21:10:09 localhost systemd[1]: usr.mount: Failed to load configuration: No such file or directory
Apr 04 21:10:10 localhost systemd[1]: usr.mount: Trying to enqueue job usr.mount/start/fail
Apr 04 21:10:10 localhost systemd[1]: usr.mount: Installed new job usr.mount/start as 345
Apr 04 21:10:10 localhost systemd[1]: usr.mount: Enqueued job usr.mount/start as 345
Apr 04 21:10:10 localhost systemd[1]: usr.mount: Directory /usr to mount over is not empty, mounting anyway.
Apr 04 21:10:10 localhost systemd[1]: usr.mount: Failed to run 'mount' task: No such file or directory
Apr 04 21:10:10 localhost systemd[1]: usr.mount: Changed dead -> failed
Apr 04 21:10:10 localhost systemd[1]: usr.mount: Job usr.mount/start finished, result=failed
Apr 04 21:10:10 localhost systemd[1]: Failed to mount /usr.
Apr 04 21:10:10 localhost systemd[1]: usr.mount: Unit entered failed state.
```

this issue only occurs on the first boot of a system, and is only reproducible some of the time. there's a few things that seem to take additional time during the first boot, such as tmpfiles, and building hwdb, but i have not figured out how to reproduce this issue after the first boot of the system.

the it appears that the codepath that puts `usr.mount` into the inactive state is the branch taken in `mount_dispatch_io` when `mount->is_mounted` is false. it's worth noting that usr.mount is set up by the initrd before the root pivot, and /dev/vda3 -> /usr is always present in /proc/self/mountinfo.

i eventually took a guess and came up with this diff, and it appears to solve the problem, but i don't think this is the right way to solve it.

``` diff
diff --git a/src/core/mount.c b/src/core/mount.c
index de1075d..f7d54db 100644
--- a/src/core/mount.c
+++ b/src/core/mount.c
@@ -325,7 +360,7 @@ static int mount_add_device_links(Mount *m) {
         if (path_equal(p->what, "/dev/root"))
                 return 0;

-        if (path_equal(m->where, "/"))
+        if (path_equal(m->where, "/") || path_equal(m->where, "/usr"))
                 return 0;

         if (mount_is_auto(p) && UNIT(m)->manager->running_as == MANAGER_SYSTEM)
```

i'm still investigating why exactly `usr.mount` transitions to the inactive state, but hopefully this is an actual systemd bug and upstream has some ideas about the problem.

**Comment by mischief** [comment] 2016-04-04 21:27
it's also worth noting the unit failure comes from `mount_enter_mounting`, due to `m->from_fragment` being somehow set to false. the whole state of the unit appears to be erased, e.g. `m->from_proc_self_mountinfo` is also false.

i was able to reproduce this with the log level set to debug, however i was not able to reproduce while sending the log to console/kmsg because it appears to be too slow. while sending logs to the journal, there appears to be a critical period where log messages are lost, since some of my debug prints never showed up, nor does the state transition to the `dead` mount.

**Comment by mischief** [comment] 2016-04-04 21:57
maybe related to #2206

**Comment by mischief** [comment] 2016-04-05 22:14
@zonque or @poettering any ideas or other information i could give about this?

**Comment by marineam** [comment] 2016-04-07 05:10
Turns out this was caused by https://github.com/systemd/systemd/pull/2978 which we've encountered before (https://github.com/coreos/bugs/issues/463) and the reason why our old solution (https://github.com/coreos/bootengine/pull/69) stopped working is because https://github.com/systemd/systemd/commit/104bc12fbc23c3ca852d9d389805c615cd590d01 broke the dependencies in our initrd https://github.com/coreos/bootengine/pull/86

**Comment by poettering** [comment] 2016-04-15 08:27
Given that this is caused by #2978 I figure we can close this bug.

**Closed as completed by poettering** 2016-04-15 08:27 UTC
Labels: pid1, not-our-bug
