### ISSUE TITLE
network: support routing table names in routes and routing policy rules

### ISSUE THREAD

**Issue by sbraz** [systemd/systemd#18122] opened 2021-01-02 23:07 UTC
Hello,

**Is your feature request related to a problem? Please describe.**
At the moment, only reserved routing table names (such as `main`) can be used in the configuration of `Route` and `RoutingPolicyRule` sections. I've discussed this with @bluca in #18121.

**Describe the solution you'd like**
It would be nice to allow routing table names as specified in `/etc/iproute2/rt_tables`. [This](https://github.com/shemminger/iproute2/blob/2953235e61eb672bbdd2de84eb5b91c388f9a9b5/lib/rt_names.c#L431) is how iproute2 does it.

**Describe alternatives you've considered**
Writing the numeric ID of the routing table works, it's just not as user-friendly.

**Comment by ssahani** [comment] 2021-01-04 13:03
Duplicate of https://github.com/systemd/systemd/issues/8418

**Closed as completed** 2021-01-04 13:08 UTC
Labels: RFE 🎁, network
