### ISSUE TITLE
Propagate reload requests from target units

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#999] opened 2015-08-20 21:21 UTC
Following up the discussion at http://lists.freedesktop.org/archives/systemd-devel/2015-July/033633.html

For certain use cases it would be useful if reloading a target propagates that reload request to all referenced units.
This would require explicit Configuration and the default behaviour of targets would be, to continue to return an error.

I'm not sure if the suggested PropagateReloadsTo=foo.service is the right or at least sufficient approach though.

In some cases you might want to propagate the reload request all services within a target without knowing beforehand which services are part of the target (think of instantiated template services).

**Comment by arvidjaar** [comment] 2015-08-21 03:48
> all services within a target

What exactly does it mean? Can you give formal definition?

**Comment by mbiebl** [comment] 2015-08-21 06:47
I think I'd like to see a boolean PropagateReload=yes instead or at least in addition to PropagateReloadTo=foo.service
This way services can declare themselves PartOf=foo.target, which can be useful for instanced services, where you don't know the name of the service beforehand.
I would basically use the same definition here that we use for  restart.

**Comment by poettering** [comment] 2015-08-28 00:42
Closing, duplicate of #710. Which was also filed by a certain @mbiebl... ;-)

**Closed as completed by poettering** 2015-08-28 00:42 UTC
Labels: RFE 🎁, pid1

**Comment by mbiebl** [comment] 2015-08-28 12:18
@poettering oops, sorry for the noise
