### ISSUE TITLE
LLMNR appears to be non-deterministic

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#942] opened 2015-08-13 10:10 UTC
```
xnox@xnox-nuc ~ $ /usr/lib/systemd/systemd-resolve-host 8e7f0ccfe29a
8e7f0ccfe29a: fe80::a865:68ff:fe9b:bbed%clrbr0

-- Information acquired via protocol LLMNR/IPv6 interface clrbr0.
xnox@xnox-nuc ~ $ /usr/lib/systemd/systemd-resolve-host 8e7f0ccfe29a
8e7f0ccfe29a: 10.0.0.34%clrbr0

-- Information acquired via protocol LLMNR/IPv4 interface clrbr0.
xnox@xnox-nuc ~ $ /usr/lib/systemd/systemd-resolve-host 8e7f0ccfe29a
8e7f0ccfe29a: fe80::a865:68ff:fe9b:bbed%clrbr0

-- Information acquired via protocol LLMNR/IPv6 interface clrbr0.
xnox@xnox-nuc ~ $ /usr/lib/systemd/systemd-resolve-host 8e7f0ccfe29a
8e7f0ccfe29a: fe80::a865:68ff:fe9b:bbed%clrbr0

-- Information acquired via protocol LLMNR/IPv6 interface clrbr0.
xnox@xnox-nuc ~ $ /usr/lib/systemd/systemd-resolve-host 8e7f0ccfe29a
8e7f0ccfe29a: fe80::a865:68ff:fe9b:bbed%clrbr0

-- Information acquired via protocol LLMNR/IPv6 interface clrbr0.
xnox@xnox-nuc ~ $ /usr/lib/systemd/systemd-resolve-host 8e7f0ccfe29a
8e7f0ccfe29a: 10.0.0.34%clrbr0

-- Information acquired via protocol LLMNR/IPv4 interface clrbr0.
```

This output is complete, ideally both ipv4 & ipv6 would be always displayed.

Furthermore, since resolvd is used, output of

```
getent ahosts 8e7f0ccfe29a
```

Is always incorrect, as that one should include both IPv4 & IPv6 addressing.

**Comment by poettering** [comment] 2015-08-14 17:03
Well, LLMNR is inherently non-deterministic (as is mDNS btw). Furthermore, resolved's zone-merging logic is non-deterministic either.

The issue is like this: resolved manages a number of different "scopes". A "scope" is basically a query "domain" (for lack of a better word, not to be confused with DNS domain names...) For each interface there's one IPv4 LLMNR scope (where queries are sent via IPv4 mcast sockets), and one IPv6 LLMNR scope (where the same is done via IPv6 mcast sockets). Then, for each interface there is one classic DNS scope defined (the af is derived from the DNS server address types configured, there's hence only one DNS scope for each interface, not two). Finally, there's one more DNS server scope for globally (non-per-interface) DNS servers, if there are any.

resolved generally follows the logic then, that all hostnames are attempted to be sent on all scopes that apply to it, simultaneously. As soon as we get one positive reply we return it, and that's the end of the story. Also, as soon as we only get negative replies we return that (or in short: "first positive wins, last negative wins"). Furthermore, for LLMNR resolved only sends A RR queries via IPv4 LLMNR and AAAA RR queries via IPv6 LLMNR. For single label names, only LLMNR applies, hence if you ask for "A or AAAA" for a name, the query is done simultaneously on all interfaces where LLMNR is possible (i.e. all interfaces that support multicasting), with one A query sent via IPv4 and one AAAA query sent via IPv6. The peer will receive these packets now, and reply to them, but it's up to the OS scheduler of the peer which one will be replied to first. And that's the one the sender will get first, that hence wins, and hence is returned to the caller. The indeterminism you see is hence the indeterminism of the process scheduler of the peer...

Could we fix this? Not really. The reason for the "first positive wins" + "last negative wins" is simply that on protocols such as LLMNR or mDNS (which are p2p, and unreliable) there's no message for "this host does not exist", because in that case the host will simply not answer, and the only way you detect that is via a longish timeout. If we hence would wait longer than just the first positive reply, and the peer is single-protocol (i.e. speaks only ipv4 xor ipv6), then we'd have to timeout, because the second reply will never come.

Hence, I am sorry, but this is not fixable. LLMNR doesn't allow what you are asking for, and if you want determinism, it cannot really deliver that...

Ultimately it shouldn't really matter though whether IPv4 or IPv6 is actually resolved first, as LLMNR is only about the local link, and on the local link both should work fine, given that there's no firewalling involved generally... and given that we only do A queries over IPv4 and AAAA queries over IPv6 the fact that a successful A response was recieved should be indication enough that the IPv4 connection will also work to that returned address, and similar for AAAA and Ipv6, if you follow what I mean.

I see nothing we can fix here, sorry! Closing.

**Closed as completed by poettering** 2015-08-14 17:03 UTC
Labels: resolve
