### ISSUE TITLE
docs: logind methods do not enforce inhibitiors of type "block" for sufficiently privileged clients

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#6644] opened 2017-08-19 11:02 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

systemd-233-6.fc26.x86_64

### Used distribution

Fedora 26

### In case of bug report: Expected behaviour you didn't see

According to the [documentation](https://www.freedesktop.org/wiki/Software/systemd/logind/), calling `org.freedesktop.login1.Manager.Suspend()` - which is how `systemctl suspend` works for unprivileged users - should "enforce" inhibition locks.

> PowerOff(), Reboot(), Suspend(), Hibernate(), HybridSleep() results in the system being powered off, rebooted, suspend, hibernated or hibernated+suspended. The only argument is the PolicyKit interactivity boolean (see above). The main purpose of these calls is that they enforce PolicyKit policy and hence allow powering off/rebooting/suspending/hibernating even by unprivileged users. _They also enforce inhibition locks._

The bug is that this is not correct.  logind does not enforce inhibition locks of type "block" when this method is called.  Instead, the implementation of `systemctl` (`logind_check_inhibitors()`) shows that inhibition locks of type "block" are enforced by the client.

### In case of bug report: Unexpected behaviour you saw

Sleep proceeds without being blocked.

### In case of bug report: Steps to reproduce the problem

```
$ systemd-inhibit --what=sleep sleep 60 &
$ systemctl suspend -i
```

**Comment by sourcejedi** [comment] 2017-08-21 07:57
Qualifier: If the client doesn't check for "block" inhibitors, the result does depend on whether the client has PolKit permission to override them or not.

The point is that most clients check for suspend inhibitors themselves (by default), but that would not make sense from reading the docs.

I think I want new versions of PowerOff() etc for #6479, so I'm planning to include IGNORE_OTHER_USERS and IGNORE_OTHER_BLOCKS as flags as well.   This should provide more hints to the documentation.

**Comment by poettering** [comment] 2017-08-30 11:04
yes, if you ask logind to execute an operation and you have enough privs to ignore inhibtors, then logind will do what you ask it for, and override the inhibitors. It's really up to the client to inform the user about inhibitors in a friendly way, logind won't and can't do that, it's not a UI tool.

**Comment by poettering** [comment] 2017-08-30 11:05
but yeah the documentation should really be updated on this, highlighting that for root inhibitors are without effect for the raw bus call

**Comment by jwrdegoede** [comment] 2017-11-15 15:15
I stumbled over this bug while looking at gnome's use of suspend inhibitors. Reading the code I found another interesting behavior which needs to be documented too.

The original reproducer works even as a regular user (non root) because the dbus method will ignore 
BlockInhibited inhibitors which were set by the same uid as the caller of the dbus method. That is iif I'm reading the code correct, see the manager_is_inhibited call in method_do_shutdown_or_sleep, which passes true for ignore_uid.

**Comment by sourcejedi** [comment] 2017-11-15 19:59
> The original reproducer works even as a regular user (non root) because the dbus method will ignore
BlockInhibited inhibitors which were set by the same uid as the caller of the dbus method.

That is what I understand now, yes.   To be explicit, the `$` prompt in the reproducer shows that I was running it as a regular user (non-root).  I had not noticed the behaviour between different UIDs.

To interpret your point: you're saying the revised docs need to not just say "sufficiently privileged".  "Privilege" sounds too much like `root`, or some `capabilities` flag which is equivalent to a subset of root.  Software like a desktop shell may assert that it never has privilege in that sense.

Instead the revised doc should mention that the client is expected to check for block inhibitors or other logged in users, if it intends to respect these, as the daemon may choose to allow the client to ignore them.

---

It interests me that you were surprised; I'd have thought this issue would be clearer when looking at the client-side code, like GNOME where the code checks for inhibitors & logged in users before shutting down...

...Now you mention it, I notice that gnome is happy to go ahead and suspend while there are logins by other users on other VTs.  Whereas `systemctl suspend` treats this as a blocker, at least after accounting for #7351.  If systemd had formalized the rules in an API (boolean parameter for overriding block inhibitors and logged in users), the rules would be more prominent, and it might have helped anticipate #7351.  
I do think it's confusing that the logind API refuses to offer an opinion.  I suspect it contributes to the "reference implementation" in systemctl being out of sync with gnome.

(I filed issues such as this here because I didn't think I could edit the wiki.  Looking now, apparently I would need be verifiable by gpg).

**Comment by jwrdegoede** [comment] 2017-11-16 09:42
Hi,

On 15-11-17 21:00, Alan Jenkins wrote:
> To interpret your point: you're saying the revised docs need to not just say "sufficiently privileged". Because privilege sounds too much like root, or some capability flag which is equivalent to a subset of root. Software like a desktop shell may assert that it never has privilege in that sense.

Right, I was expecting "sufficiently privileged" to mean root, or other processes allowed to do this through policykit.
I was sorta surprised while reading the code that if user hans sets a blocker and then user hans tries to suspend the
suspend will happily continue.

> Instead the revised doc should mention that the client is expected to check for block inhibitors or other logged in users, if it intends to respect these, as the daemon may choose to allow the client to ignore them.

I wouldn't write it that way, I would warn that the client should check and as reason explicitly spell out both causes why logind might ignore the blocker:
1) Special privileges (either run as root, or allowed to ignore inhibitors through polkit)
2) Blockers set by the same uid as the client will be ignored

> ...Now you mention it, I notice that gnome is happy to go ahead and suspend while there are logins by other users on other VTs. Whereas |systemctl suspend| treats this as a blocker

Suspend yes, but for shutdown gnome will show a dialog that other users are logged in and ask you to confirm
the shutdown. This is a policy decision by gnome, which makes a lot of sense because showing a dialog when
closing the laptop lid, which is how most users suspend, is not going to help a lot and may actually cause
the laptop to overheat when put in e.g. a backpack (been there, done that, didn't like it).

Regards,

Hans

**Comment by sourcejedi** [comment] 2017-11-16 11:40
FWIW, nowadays the lid close action is implemented in logind, not in a Gnome component.  So it's logind that ultimately holds policy about lid close.  https://unix.stackexchange.com/questions/307497/gnome-disable-sleep-on-lid-close/307498#307498  <del>I don't think Gnome requests any adjustments to it, outside of the Tweak Tool mentioned in the link</del>.  (logind has another bug regarding inhibitors on this, though it does not affect current Gnome).

Instead, I was triggering suspend through Gnome from the lock screen - there's a pause button where the gnome power button would be normally.  Or, by turning the power button into a pause button by holding down the Alt key.

**Comment by jwrdegoede** [comment] 2017-11-16 11:48
Hi,

On 16-11-17 12:40, Alan Jenkins wrote:
> FWIW, the lid close action is handled directly by logind nowadays not Gnome. So it's logind that ultimately holds policy about lid close. https://unix.stackexchange.com/questions/307497/gnome-disable-sleep-on-lid-close/307498#307498 (logind has another bug here, but it does not affect current Gnome).

Ah you're right, gnome-settings-daemon/plugins/power/gsd-power-manager.c does:

         params = g_variant_new ("(ssss)",
                                 "handle-lid-switch",
                                 g_get_user_name (),
                                 "Multiple displays attached",
                                 "block");
         g_dbus_proxy_call_with_unix_fd_list (manager->priv->logind_proxy,
                                              "Inhibit",
                                              params,
	...

But it only uses this to inhibit/uninhibit suspend on lid close when there
is an external monitor. I was expecting it to simply inhibit it once when
started and take over the handling, but it is not doing that.

Regards,

Hans

**Comment by icasdri** [comment] 2019-10-03 05:55
I also found this behavior *very* surprising given the documentation:

`They [Suspend() and friends] also enforce inhibition locks. UIs should expose these calls as primary mechanism to poweroff/reboot/suspend/hibernate/hybrid-sleep the machine.`

This says nothing about the fact that UIs should check inhibitors themselves (which is what `systemctl suspend` apparently does) before calling `Suspend()` and friends, and seems to suggest the contrary.

Steps to reproduce: (all run as a non-root locally logged-in user, with version `systemd 243`)

1. `systemd-inhibit --what=sleep --mode=block cat &`
2. `systemctl suspend` results in *Operation inhibited by "cat"* as desired (**expected behavior**)
3. `gdbus call --system -d org.freedesktop.login1 -o /org/freedesktop/login1 -m org.freedesktop.login1.Manager.Suspend true`  results in immediate system suspension  (**unexpected surprising behavior**) (note: `true` or `false` for `polkit_interactive` makes no difference here)

---
This problem is compounded by #2680, which together with this issue makes it very unintuitive to write something that e.g. does what `systemctl suspend` does but puts *Operation inhibited by ...* out via a libnotify notification:
* you can't just wrap `systemctl suspend` as calling that non-interactively (even without `-i`) will ignore and not honor inhibitors
* you can't use `org.freedesktop.login1.Manager.Suspend` which "enforces inhibitors" without checking `ListInhibitors` yourself (which the documentation does not lead you to do)

---
As @sourcejedi pointed out in an earlier comment comparing the behavior of `systemctl suspend` and GNOME, pushing the responsibility for checking inhibitors to clients may also have the unintended consequence of inconsistent system behavior in default use cases depending on which client a user is using to suspend their system, decreasing the perceived reliability and therefore usability of inhibitors.

I'm not sure how viable something like this would be but I think it would be much more intuitive to change or add a new interface such that instead of

```
Suspend(in  b  polkit_interactive)
```

we have the method take whether inhibitors should be honored or not and return the inhibitor that is blocking suspend (in e.g. the format of `ListInhibitors`) when suspend fails due to an inhibitor being honored (or something like this)

```
Suspend2(in  b  polkit_interactive,
         in  b  honor_inhibitors,
         out ssssuu  inhibitor_blocking_suspend)
```

At the very least, we should probably update/correct the documentation to reflect the current implementation in logind and clients.

**Comment by bluca** [comment] 2021-02-02 11:57
Fixed by https://github.com/systemd/systemd/pull/18316 - now the documentation is updated, and there's a new interface to always respect inhibitors even when privileged

**Closed as completed by bluca** 2021-02-02 11:57 UTC
Labels: login, documentation
