### ISSUE TITLE
Remove fd leak in pam_systemd

### ISSUE THREAD

**Issue by gwsas** [systemd/systemd#4507] opened 2016-10-27 22:16 UTC
### Submission type
- [ ] Bug report
- [X ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 219

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> RHEL 7.2

In systemd/src/login/pam_systemd.c, at line 546 there is this statement:

```
    /* Note that we are knowingly leaking the FIFO fd here. This
     * way, logind can watch us die. If we closed it here it would
     * not have any clue when that is completed. Given that one
     * cannot really have multiple PAM sessions open from the same
     * process this means we will leak one FD at max. */
```

However, take the example of a persistent authentication process used to authenticate users to a server application.  Because of this intentional leak in pam_systemd, a file descriptor is leaked for every user session, even though the auth process calls pam_session_close and pam_end when the user's session ends.  A process like I described will leak descriptors until we hit a limit and the system is unusable.

Of course, we can remove pam_systemd.so from the PAM service file for our application, but this isn't convenient since RHEL7 and RHEL7 derivatives ship with pam_systemd.so in the session chain in /etc/pam.d/password-auth.  

tail --lines=6 /etc/pam.d/password-auth

session     optional      pam_keyinit.so revoke
session     required      pam_limits.so
-session     optional      pam_systemd.so
session     [success=1 default=ignore] pam_succeed_if.so service in crond quiet use_uid
session     required      pam_unix.so

We are trying to keep it simple by referencing password-auth in our application's PAM service file.  Because of this leak, we have to instruct our users to make manual edits to the PAM service file or add automation in our installation process in order to include all the session directives from password-auth except for the one that invokes pam_systemd.so.

The goal of this request is to remove the fd leak from pam_systemd.

**Comment by poettering** [comment] 2016-11-01 13:41
We set O_CLOEXEC on the "leaked" fd, to ensure that it is closed in the PAM session's user process, as that it is only left around only in the parent and is closed by the PAM session end hook there.

There hence shouldn't be any real leak unless your program doesn't properly invoke execve() in the child process. Does it? (this is necessary not only for this case, but also many MACs require it to do the security transitions properly, for example pam_selinux).

Either way, I see no bug in logind here. Yupp, it would be better if we didn't have to do this, but the issue you are describing cannot be caused by it.

Also note that before pam_systemd there was pam_consolekit, and it used the very same mechanism. We just inherited the scheme from that. This behaviour has been in place hence since a long long time, already in RHEL6.

Hope this makes sense. Closing.

**Closed as completed by poettering** 2016-11-01 13:41 UTC
Labels: login, not-a-bug

**Comment by gwsas** [comment] 2016-11-01 15:36
We don’t know if this is the latest source and matches what you are looking at, but below, we see the O_CLOEXEC, and we see that the original session_fd that is dup’d seems to get closed, but in the parent process, where does the returned fd from the fcntl() call get closed? Where do you call pam_get_data() on the system.session-fd and close it in the parent? Sure – if you fork/exec the fd is closed in the child, but it still leaks in the parent.

The session_fd is dup’d and saved away in this section of code:

```
    if (session_fd >= 0) {
            session_fd = fcntl(session_fd, F_DUPFD_CLOEXEC, 3);
            if (session_fd < 0) {
                    pam_syslog(handle, LOG_ERR, "Failed to dup session fd: %m");
                    return PAM_SESSION_ERR;
            }

            r = pam_set_data(handle, "systemd.session-fd", FD_TO_PTR(session_fd), NULL);
            if (r != PAM_SUCCESS) {
                    pam_syslog(handle, LOG_ERR, "Failed to install session fd.");
                    safe_close(session_fd);
                    return r;
            }
    }
```

This fd is never closed.

**Comment by poettering** [comment] 2016-11-03 18:40
yeah, we don't actively close the fd in pam_sm_close_session(), see the comments about that there. The reason is that the process managing the PAM session should have time doing whatever further clean-up job it wants to do after invoking pam_sm_close_session(), before exiting. If we'd close the fd within the pam_sm_close_session() this would tell logind that the process managing the PAM session died, and logind would clean it up. After all seeing an EOF on that fd is indication to logind that the session died abnormally...

Note that you cannot create multiple PAM sessions within the same process, and you cannot reuse the process for much after the PAM session ended: you have to clean things up and exit. That's because PAM session modules will alter the credentials and settings of your process quite drastically, and you cannot properly undo that. Opening a PAM session basically means your process is from that point on nothing else but the managing process of that PAM session. And because it's that way it is safe to leak that fd even beyond the pam_sm_close_session(), since we know it will be followed shortly by an exit() where the kernel will clean this up correctly.

Hope that makes sense?
