### ISSUE TITLE
User mounts (FUSE) cannot be unmounted

### ISSUE THREAD

**Issue by 05storm26** [systemd/systemd#18431] opened 2021-02-01 17:13 UTC
**systemd version the issue has been seen with**
 ``` 
> /bin/init --version
systemd 247 (247.2-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

**Used distribution**
 > Arch

**Linux kernel version used** (`uname -a`)

 > `5.10.11-arch1-1`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > The user FUSE mounts can be started, stopped and restarted. During stopping `fusermount -u` is used instead of trying to use `unmount` which requires root.

**Unexpected behaviour you saw**
 > Systemd tries to use `umount` for FUSE mounts when stopping them. This doesn't work if the user is not root. 
```
Feb 01 18:06:51 hostname umount[137122]: umount: /home/username/mount/path: must be superuser to unmount.
Feb 01 18:06:51 hostname systemd[760]: home-username-mount-path.mount: Mount process exited, code=exited, status=32/n/a
```

**Steps to reproduce the problem**
 > Something like this:
```
> cat .config/systemd/user/home-username-mount-path.mount
    [Unit]
    Description=sshfs mount
    After=network-online.target
    After=NetworkManager.service

    [Mount]
    What=pi:/ssd/dir-to-mount
    Where=/home/username/mount/path
    Type=fuse.sshfs
    Options=noauto,user,_netdev

```
> In `.ssh/config` configure the a Host named *`pi`*

> `systemctl --user daemon-reload`

> `systemctl --user start home-username-mount-path.mount`

> Verify that the start was successfull and was successfully mounted.

> `systemctl --user stop home-username-mount-path.mount`

**Comment by poettering** [comment] 2021-02-01 17:18
Duplicate of #17788

**Closed as completed by poettering** 2021-02-01 17:18 UTC
Labels: duplicate
