### ISSUE TITLE
cgroup controllers are not activated for the user instance in the unified hierarchy

### ISSUE THREAD

**Issue by aroig** [systemd/systemd#3500] opened 2016-06-10 18:10 UTC
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> systemd 230
> kernel 4.6.2
### Used distribution

> arch linux
### In case of bug report: Expected behaviour you didn't see

> io, memory and pids controllers are not activated for the cgroups belonging to the systemd user instance.
### In case of bug report: Unexpected behaviour you saw

> The cgroup for `user@1000.service` has empty `cgroup.subtree_controller`, despite io memory and pids are marked as available in `cgroup.controllers`, and enabled in `/etc/systemd/user.conf`.
> 
> Also, attempting to add the controllers manually fails (nothing happens). After a quick look at the kernel sources, it seems they do not allow changing the controllers if the cgroup is already populated, except for the root cgroup.
### In case of bug report: Steps to reproduce the problem

> Enable controllers for the user instance and boot with the unified hierarchy.

**Comment by evverx** [comment] 2016-06-10 18:14
https://github.com/systemd/systemd/issues/3388#issuecomment-222595883

**Comment by aroig** [comment] 2016-06-10 18:41
@evverx what makes you think this is a duplicate? The problem I reported is different, and I see no obvious a priori reason why #3388 and this bug have the same cause.

**Comment by evverx** [comment] 2016-06-10 19:07
> what makes you think this is a duplicate?

Logs:

```
bash-4.3# journalctl -b --no-hostname -u user@1001.service 
-- Logs begin at Fri 2016-06-10 18:59:14 UTC, end at Fri 2016-06-10 19:06:31 UTC. --
Jun 10 19:00:34 systemd[1]: user@1001.service: Trying to enqueue job user@1001.service/start/replace
Jun 10 19:00:34 systemd[1]: user@1001.service: Installed new job user@1001.service/start as 226
Jun 10 19:00:34 systemd[1]: user@1001.service: Enqueued job user@1001.service/start as 226
Jun 10 19:00:34 systemd[161]: pam_unix(systemd-user:session): session opened for user vagrant by (uid=0)
Jun 10 19:00:34 systemd[1]: user@1001.service: Failed to set io.weight: No such file or directory
Jun 10 19:00:34 systemd[1]: user@1001.service: Failed to set memory.low: No such file or directory
Jun 10 19:00:34 systemd[1]: user@1001.service: Failed to set memory.high: No such file or directory
Jun 10 19:00:34 systemd[1]: user@1001.service: Failed to set memory.max: No such file or directory
Jun 10 19:00:34 systemd[1]: user@1001.service: Failed to set pids.max: No such file or directory
Jun 10 19:00:34 systemd[1]: user@1001.service: About to execute: /usr/lib/systemd/systemd --user
Jun 10 19:00:34 systemd[1]: user@1001.service: Forked /usr/lib/systemd/systemd as 161
Jun 10 19:00:34 systemd[1]: user@1001.service: Changed dead -> start
Jun 10 19:00:34 systemd[1]: Starting User Manager for UID 1001...
Jun 10 19:00:34 systemd[161]: user@1001.service: Executing: /usr/lib/systemd/systemd --user
Jun 10 19:00:34 systemd[161]: Failed to fully start up daemon: Permission denied
Jun 10 19:00:34 systemd[161]: Reached target Sockets.
Jun 10 19:00:34 systemd[161]: Reached target Paths.
Jun 10 19:00:34 systemd[161]: Reached target Timers.
Jun 10 19:00:34 systemd[161]: Reached target Basic System.
Jun 10 19:00:34 systemd[161]: Reached target Default.
Jun 10 19:00:34 systemd[161]: Startup finished in 206ms.
Jun 10 19:00:34 systemd[1]: user@1001.service: Got notification message from PID 161 (READY=1, STATUS=Startup finished in 206ms.)
Jun 10 19:00:34 systemd[1]: user@1001.service: Changed start -> running
Jun 10 19:00:34 systemd[1]: user@1001.service: Job user@1001.service/start finished, result=done
Jun 10 19:00:34 systemd[1]: Started User Manager for UID 1001.
```

And

```
Jun 10 19:00:34 systemd[1]: Failed to enable controller io for /user.slice/user-1001.slice (/sys/fs/cgroup/user.slice/user-1001.slice/cgroup.subtree_control): No such file or directory
Jun 10 19:00:34 systemd[1]: Failed to enable controller memory for /user.slice/user-1001.slice (/sys/fs/cgroup/user.slice/user-1001.slice/cgroup.subtree_control): No such file or directory
Jun 10 19:00:34 systemd[1]: Failed to enable controller pids for /user.slice/user-1001.slice (/sys/fs/cgroup/user.slice/user-1001.slice/cgroup.subtree_control): No such file or directory
```

**Comment by aroig** [comment] 2016-06-10 19:22
Ok, those logs do reflect the same problem I reported. But where do they come from? This is not the issue reported in #3388!

I mean, this is a duplicate of what? I'm just asking because I fail to see any other issue reporting this. I'm happy to close this and go there to follow the progress of this bug.

**Comment by evverx** [comment] 2016-06-10 19:44
> I mean, this is a duplicate of what?

By "duplicate" I mean "the same root cause". Maybe, this is the wrong word. Sorry.

**Comment by aroig** [comment] 2016-06-10 20:19
> By "duplicate" I mean "the same root cause". Maybe, this is the wrong word. Sorry.

Then no, I don't think they have the same root cause. Or not obviously. 

Ok, those are my logs for the user instance, which are slightly different than yours.

```
Jun 10 21:33:29 galois systemd[14746]: Failed to enable controller io for /user.slice/user-1000.slice/user@1000.service (/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/cgroup.subtree_control): Permission denied
Jun 10 21:33:29 galois systemd[14746]: Failed to enable controller memory for /user.slice/user-1000.slice/user@1000.service (/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/cgroup.subtree_control): Permission denied
Jun 10 21:33:29 galois systemd[14746]: Failed to enable controller pids for /user.slice/user-1000.slice/user@1000.service (/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/cgroup.subtree_control): Permission denied
Jun 10 21:33:29 galois systemd[14746]: Failed to set io.weight on /user.slice/user-1000.slice/user@1000.service: Permission denied
Jun 10 21:33:29 galois systemd[14746]: Failed to set memory.limit_in_bytes/memory.max on /user.slice/user-1000.slice/user@1000.service: Permission denied
Jun 10 21:33:29 galois systemd[14746]: Failed to set pids.max on /user.slice/user-1000.slice/user@1000.service: Permission denied
Jun 10 21:33:29 galois systemd[14746]: Failed to enable controller io for /user.slice/user-1000.slice/user@1000.service/daemons.slice (/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/daemons.slice/cgroup.subtree_control): No such file or directory
Jun 10 21:33:29 galois systemd[14746]: Failed to enable controller memory for /user.slice/user-1000.slice/user@1000.service/daemons.slice (/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/daemons.slice/cgroup.subtree_control): No such file or directory
Jun 10 21:33:29 galois systemd[14746]: Failed to enable controller pids for /user.slice/user-1000.slice/user@1000.service/daemons.slice (/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/daemons.slice/cgroup.subtree_control): No such file or directory
Jun 10 21:33:29 galois systemd[14746]: Failed to set io.weight on /user.slice/user-1000.slice/user@1000.service/daemons.slice: No such file or directory
Jun 10 21:33:29 galois systemd[14746]: Failed to set memory.limit_in_bytes/memory.max on /user.slice/user-1000.slice/user@1000.service/daemons.slice: No such file or directory
Jun 10 21:33:29 galois systemd[14746]: Failed to set pids.max on /user.slice/user-1000.slice/user@1000.service/daemons.slice: No such file or directory
```

Instead of "No such file or directory" I get "Permission denied", which makes more sense, since those files exist and are owned by root.

We are talking of about 4 different problems:
1. the systemd user instance tries to enable their own controllers, but `cgroup.subtree_control` is owned by root and it fails. This is the obvious part, and should be fixed by giving permissions to that file, or letting the system instance enable the controllers. Now I'm not sure this is the same issue as in your logs or not, since you get "file not found" instead of permission denied. 
2. Something happens to systemd-run in the unified hierarchy. This is #3388. It looks like a permission denied on `cgroup.progs`, but I cannot reproduce that bug. `systemd-run --user --scope bash -c 'sleep 10'` works as expected on my machine, in the unified hierarchy. In fact, `cgroup.progs` has user permissions on my machine, due to `Delegate=yes` in user@.service.
3. If after 1 above, you try to enable the controllers for the `user@1000.service` cgroup manually (i.e. `echo '+io' > cgroup.subtree_control`) as root, nothing happens, they do not get enabled. I suspect this has to do with the kernel not allowing to change the controllers once the cgroup is populated, but I don't really know. I'm not even sure if this would be a kernel bug or a systemd bug, although I'm pretty sure that if I'm right about the cause, systemd could make it work by doing things in a different order.
4. systemd does not kill user processes at logout under the unified hierarchy. This is #3483, and may or may not have the same root cause as the others. I cannot tell.

**Comment by evverx** [comment] 2016-06-10 22:37
> Now I'm not sure this is the same issue as in your logs or not, since you get "file not found" instead of permission denied.

This is the same

``` sh
-bash-4.3# pwd
/sys/fs/cgroup/user.slice/user-1001.slice/user@1001.service

-bash-4.3# id
uid=0(root) gid=0(root) groups=0(root)

-bash-4.3# ls -l
total 0
-r--r--r-- 1 root    root    0 Jun 10 21:56 cgroup.controllers
-r--r--r-- 1 root    root    0 Jun 10 21:56 cgroup.events
-rw-r--r-- 1 vagrant vagrant 0 Jun 10 21:51 cgroup.procs
-rw-r--r-- 1 root    root    0 Jun 10 21:56 cgroup.subtree_control
drwxr-xr-x 2 vagrant vagrant 0 Jun 10 21:51 init.scope

-bash-4.3# printf '+pids' >cgroup.subtree_control
-bash: printf: write error: No such file or directory

-bash-4.3# su vagrant
bash-4.3$ id
uid=1001(vagrant) gid=1001(vagrant) groups=1001(vagrant)

bash-4.3$ printf '+pids' >cgroup.subtree_control
bash: cgroup.subtree_control: Permission denied
```

So, could you reboot (start from the clean state) and provide the output of:

```
ls -lR /sys/fs/cgroup/user.slice/
cat /sys/fs/cgroup/user.slice/cgroup.controllers
cat /sys/fs/cgroup/user.slice/cgroup.subtree_control
cat /sys/fs/cgroup/user.slice/user-1000.slice/cgroup.controllers
cat /sys/fs/cgroup/user.slice/user-1000.slice/cgroup.subtree_control
and so on
```

?

**Comment by evverx** [comment] 2016-06-10 23:08
Anyway,

```
root@archlinux# uname -r
4.6.2-1-ARCH

root@archlinux# pacman -Q systemd
systemd 230-4

root@archlinux# pwd
/sys/fs/cgroup/user.slice/user-998.slice/user@998.service

root@archlinux# cat cgroup.controllers
io memory pids

root@archlinux# cat cgroup.subtree_control #nothing

root@archlinux# ls init.scope/ #there is no pids.current pids.max
cgroup.controllers  cgroup.events  cgroup.procs  cgroup.subtree_control

root@archlinux# printf +pids >cgroup.subtree_control

root@archlinux# cat cgroup.subtree_control
pids

root@archlinux# ls init.scope/ # note pids.current pids.max
cgroup.controllers  cgroup.events  cgroup.procs  cgroup.subtree_control  pids.current  pids.max
```

**Comment by aroig** [comment] 2016-06-11 00:47
Hi, answering your request:

```
$ ls -l /sys/fs/cgroup/user.slice/user-1000.slice/
total 0
-r--r--r--  1 root root 0 Jun 11 01:40 cgroup.controllers
-r--r--r--  1 root root 0 Jun 11 01:40 cgroup.events
-rw-r--r--  1 root root 0 Jun 11 01:40 cgroup.procs
-rw-r--r--  1 root root 0 Jun 11 01:40 cgroup.subtree_control
-rw-r--r--  1 root root 0 Jun 11 01:40 io.max
-r--r--r--  1 root root 0 Jun 11 01:40 io.stat
-rw-r--r--  1 root root 0 Jun 11 01:40 io.weight
-r--r--r--  1 root root 0 Jun 11 01:40 memory.current
-r--r--r--  1 root root 0 Jun 11 01:40 memory.events
-rw-r--r--  1 root root 0 Jun 11 01:40 memory.high
-rw-r--r--  1 root root 0 Jun 11 01:40 memory.low
-rw-r--r--  1 root root 0 Jun 11 01:40 memory.max
-r--r--r--  1 root root 0 Jun 11 01:40 memory.stat
-r--r--r--  1 root root 0 Jun 11 01:40 memory.swap.current
-rw-r--r--  1 root root 0 Jun 11 01:40 memory.swap.max
-r--r--r--  1 root root 0 Jun 11 01:40 pids.current
-rw-r--r--  1 root root 0 Jun 11 01:40 pids.max
drwxr-xr-x  2 root root 0 Jun 11 01:40 session-c1.scope/
drwxr-xr-x 20 abdo abdo 0 Jun 11 01:39 user@1000.service/

$ ls -l /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service
total 0
drwxr-xr-x 6 abdo abdo 0 Jun 11 01:49 apps.slice/
drwxr-xr-x 2 abdo abdo 0 Jun 11 01:49 boot.mount/
-r--r--r-- 1 root root 0 Jun 11 01:40 cgroup.controllers
-r--r--r-- 1 root root 0 Jun 11 01:40 cgroup.events
-rw-r--r-- 1 abdo abdo 0 Jun 11 01:39 cgroup.procs
-rw-r--r-- 1 root root 0 Jun 11 01:49 cgroup.subtree_control
drwxr-xr-x 4 abdo abdo 0 Jun 11 01:49 daemons.slice/
drwxr-xr-x 2 abdo abdo 0 Jun 11 01:49 data0.mount/
drwxr-xr-x 2 abdo abdo 0 Jun 11 01:49 data1.mount/
drwxr-xr-x 2 abdo abdo 0 Jun 11 01:49 dbus.service/
drwxr-xr-x 2 abdo abdo 0 Jun 11 01:49 dbus.socket/
drwxr-xr-x 2 abdo abdo 0 Jun 11 01:49 dev-hugepages.mount/
drwxr-xr-x 2 abdo abdo 0 Jun 11 01:49 dev-mqueue.mount/
drwxr-xr-x 2 abdo abdo 0 Jun 11 01:49 init.scope/
-rw-r--r-- 1 root root 0 Jun 11 01:40 io.max
-r--r--r-- 1 root root 0 Jun 11 01:40 io.stat
-rw-r--r-- 1 root root 0 Jun 11 01:40 io.weight
drwxr-xr-x 2 abdo abdo 0 Jun 11 01:49 media-quasar.mount/
-r--r--r-- 1 root root 0 Jun 11 01:40 memory.current
-r--r--r-- 1 root root 0 Jun 11 01:40 memory.events
-rw-r--r-- 1 root root 0 Jun 11 01:40 memory.high
-rw-r--r-- 1 root root 0 Jun 11 01:40 memory.low
-rw-r--r-- 1 root root 0 Jun 11 01:40 memory.max
-r--r--r-- 1 root root 0 Jun 11 01:40 memory.stat
-r--r--r-- 1 root root 0 Jun 11 01:40 memory.swap.current
-rw-r--r-- 1 root root 0 Jun 11 01:40 memory.swap.max
-r--r--r-- 1 root root 0 Jun 11 01:40 pids.current
-rw-r--r-- 1 root root 0 Jun 11 01:40 pids.max
drwxr-xr-x 2 abdo abdo 0 Jun 11 01:49 run-user-1000-gvfs.mount/
drwxr-xr-x 2 abdo abdo 0 Jun 11 01:49 sys-fs-fuse-connections.mount/
drwxr-xr-x 2 abdo abdo 0 Jun 11 01:49 sys-kernel-config.mount/
drwxr-xr-x 2 abdo abdo 0 Jun 11 01:49 sys-kernel-debug.mount/
drwxr-xr-x 2 abdo abdo 0 Jun 11 01:49 tmp.mount/
drwxr-xr-x 9 abdo abdo 0 Jun 11 01:49 wm.slice/
drwxr-xr-x 2 abdo abdo 0 Jun 11 01:49 xrandr-dual.service/

$ cat /sys/fs/cgroup/user.slice/cgroup.controllers 
io memory pids

$ cat /sys/fs/cgroup/user.slice/cgroup.subtree_control 
io memory pids

$ cat /sys/fs/cgroup/user.slice/user-1000.slice/cgroup.controllers     
io memory pids

$ cat /sys/fs/cgroup/user.slice/user-1000.slice/cgroup.subtree_control
io memory pids

$ cat /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/cgroup.controllers 
io memory pids

$ cat /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/cgroup.subtree_control
# empty

$ printf '+io' > /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/cgroup.subtree_control 
$ cat /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/cgroup.subtree_control 
io
```

So, it turns out this works as expected now, opposed to what I reported as problem 3 above. The issue remains that systemd --user has no permissions to write `cgroup.subtree_control` and the per-controller files.

 Right now, I was trying to reproduce what I did to trigger 3 above (I was playing with the cgroups and had chowned cgroup.subtree_control to my user and back to root...). I just managed to get it into a broken state again

```
$ printf -- '-io' > cgroup.subtree_control 
bash: printf: write error: Device or resource busy
$ cat cgroup.subtree_control 
io
$ printf '+pids' > cgroup.subtree_control 
$ cat cgroup.subtree_control 
io
```

But I can't reproduce it for a third time. I can't reproduce the "No such file or directory" from your vagrant logs either.

**Comment by evverx** [comment] 2016-06-18 03:04
https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html#Delegate=

>  Delegate=
> Turns on delegation of further resource control partitioning to processes of the unit. For unprivileged services (i.e. those using the User= setting), this allows processes to create a subhierarchy beneath its control group path. For privileged services and scopes, this ensures the processes will have all control group controllers enabled.

Seems like `user@.service` and `systemd --user` work as expected.

> systemd does not kill user processes at logout under the unified hierarchy.

See https://github.com/systemd/systemd/issues/3483#issuecomment-225438603

> Something happens to systemd-run in the unified hierarchy. 

Indeed. This is a bug. :
- `systemd-run --user --scope` runs a process `PID` inside the cgroup `/user.slice/user-M.slice/session-N.scope`
- `systemd --user` runs `mkdir /sys/fs/cgroup/user.slice/user-M.slice/user@M.service/run-PID.scope`
- `systemd --user` tries to write `PID` to `/sys/fs/cgroup/user.slice/user-M.slice/user@M.service/run-PID.scope/cgroup.procs`

This fails

> The writer must have write access to the "cgroup.procs" file of the
>   common ancestor of the source and destination cgroups.

https://github.com/torvalds/linux/blob/5518f66b5a64b76fd602a7baf60590cd838a2ca0/Documentation/cgroup-v2.txt#L331

(`systemd --user` doesn't have write access to the `/sys/fs/cgroup/user.slice/user-M.slice/cgroup.procs`)

> I can't reproduce the "No such file or directory"

``` sh
$ cat cgroup.controllers # emtpy
$ cat cgroup.subtree_control # empty
$ [ -w cgroup.subtree_control ] && printf +pids >cgroup.subtree_control
-bash: printf: write error: No such file or directory
```

**Comment by aroig** [comment] 2016-06-18 09:37
> $ cat cgroup.controllers # emtpy
> $ cat cgroup.subtree_control # empty
> $ [ -w cgroup.subtree_control ] && printf +pids >cgroup.subtree_control
> -bash: printf: write error: No such file or directory

This did not happen consistently to me. Sometimes it gave this error, sometimes it just didn't do anything, and sometimes it added the controller (when I had them activated and `cgroup.controllers` was populated, of course). I didn't find a consistent trigger for the wrong behaviour. It looked like a kernel issue to me.

Did you manage to enable the controllers for the user instance manually  this way at any point? In my case it worked, except for two times, the one that prompted me to open this issue, and a second one I managed to screw things up. The rest of the time I could enable controllers on the user instance manually as expected..

I gave up playing with the controllers for now.

Thanks for following up on this!

**Comment by poettering** [comment] 2018-05-24 11:07
So, I am pretty sure this works on current systemd versions. At least I verified it does on my system.

Note that by default we currently only delegate "memory" and "pids" to unpriv users, as the other stuff is not really cheap enough to enable it by default yet. You can enable that too my adding "Delegate=cpu io" for that into the relevant user's user@.service or as a drop-in for all of them.

I think we can close this hence.

**Closed as completed by poettering** 2018-05-24 11:07 UTC
Labels: cgroups, pid1
