### ISSUE TITLE
systemd-homed does not restart on failure

### ISSUE THREAD

**Issue by 0x647262** [systemd/systemd#22444] opened 2022-02-08 00:43 UTC
**systemd version the issue has been seen with**

```
systemctl --version
systemd 250 (250.3-2-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

**Used distribution**

Arch Linux

**Linux kernel version used** (`uname -a`)

```
uname -a
Linux amalgam 5.16.5-arch1-1 #1 SMP PREEMPT Tue, 01 Feb 2022 21:42:50 +0000 x86_64 GNU/Linux
```

**CPU architecture issue was seen on**

x86_64

**Expected behaviour you didn't see**

systemd-homed should restart on failure

**Unexpected behaviour you saw**

systemd-homed does not restart on failure

**Steps to reproduce the problem**

Until #22443 is fixed:

1. Start a tmux session (or any other terminal multiplexer that allows mirroring of keystrokes)
2. Create two or more terminal panes in the mulitplexer
3. Enable mirroring of keystokes across all terminals
4. Run any command with `sudo` (e.g.: `sudo systemctl --version`)
5. systemd-homed should crash and not restart

**Additional program output to the terminal or log subsystem illustrating the issue**

Journalctl output:

```
Feb 07 18:41:22 amalgam systemd[1]: Starting Home Area Manager...
Feb 07 18:41:22 amalgam systemd-homed[56238]: Successfully loaded private key pair.
Feb 07 18:41:22 amalgam systemd-homed[56238]: Watching /home.
Feb 07 18:41:22 amalgam systemd-homed[56238]: User record drb.identity is signed only by us, accepting.
Feb 07 18:41:22 amalgam systemd-homed[56238]: Added registered home for user drb.
Feb 07 18:41:22 amalgam systemd[1]: Started Home Area Manager.
Feb 07 18:41:48 amalgam systemd-homed[56238]: drb: changing state active → authenticating-for-acquire
Feb 07 18:41:48 amalgam systemd-homed[56238]: Assertion '!h->current_operation' failed at src/home/homed-home.c:2693, function home_dispatch_acquire(). Aborting.
Feb 07 18:41:48 amalgam systemd-homework[56299]: None of the supplied plaintext passwords unlock the user record's hashed passwords.
Feb 07 18:41:48 amalgam systemd[1]: systemd-homed.service: Main process exited, code=dumped, status=6/ABRT
Feb 07 18:41:48 amalgam systemd[1]: systemd-homed.service: Failed with result 'core-dump'.
```

**Comment by 0x647262** [comment] 2022-02-08 00:50
Assuming there's nothing blocking us from adding `Restart=on-failure` to the default `systemd-homed` unit file, I'll create a merge request for this issue. :smile:

**Comment by dtardon** [comment] 2023-06-05 08:56
A duplicate of #24036.

**Closed as completed by dtardon** 2023-06-05 08:56 UTC
Labels: duplicate, homed
