### ISSUE TITLE
RFE: systemd-boot: hiding of auto entries

### ISSUE THREAD

**Issue by grawity** [systemd/systemd#7662] opened 2017-12-15 17:36 UTC
### Submission type

 - Request for enhancement (RFE)

### In case of request for enhancement: Behavior you would like to see

Currently systemd-boot adds a few automatic entries – EFI shell, Windows, default loader, etc. For aesthetic purposes, I would like to hide some of those entries (efi-shell and efi-default); they're needed so rarely and I can reach them via my firmware boot menu anyway. There is however no option that I could find for that.

**Comment by poettering** [comment] 2017-12-15 17:41
Duplicate of #2895

**Closed as completed** 2017-12-15 17:41 UTC
Labels: sd-boot/sd-stub/bootctl, duplicate
