### ISSUE TITLE
Sometimes, not always, there is no usage consumption summary for a unit in the journal

### ISSUE THREAD

**Issue by e-Gyi-qO** [systemd/systemd#28524] opened 2023-07-26 11:23 UTC
### systemd version the issue has been seen with

253

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

When a unit terminated a run, always get in the journal a message like
```name.service: Consumed 1.204s CPU time.```

### Unexpected behaviour you saw

The other messages for the unit are as expected. Only the CPU consumption line is missing.

### Steps to reproduce the problem

Currently with version 253.7. The problem seen for a long time. I don’t remember since when.
The problem is that sometimes, the CPU consumption summary is not reported in the journal. I set a user service, and a user timer for bug reporting purposes.
```
# ~/.config/systemd/user/bugdemo.timer
[Unit]
Description=Attempting to demonstrate a bug with systemd CPU consumption messages
Documentation=man:systemd.timer(5)

[Timer]
OnCalendar=14:05
AccuracySec=2h
Persistent=true

[Install]
WantedBy=timers.target
```
```
# ~/.config/systemd/user/bugdemo.service
[Unit]
Environment=SYSTEMD_LOG_LEVEL=debug
Description=Attempting to demonstrate a bug with systemd CPU consumption messages
ConditionACPower=true

[Service]
Type=oneshot
WorkingDirectory=/home/e-Gyi-qO/
ExecStart=/home/e-Gyi-qO/.config/systemd/user/bugdemo.sh
Nice=19
IOSchedulingClass=best-effort
IOSchedulingPriority=7
Umask=0077
```
```
#! /bin/bash
# ~/.config/systemd/user/bugdemo.sh

# A bash script to demonstrate a bug in systemd consumption CPU summary.
# The script is run by a service, which is periodically activated by a 
# user timer.

for ((i = 0; i < 2; i++)); do
    ping -c 1 systemd.io
    sleep 10 
done
```
```
$ systemd-analyze verify --user ~/.config/systemd/user/bugdemo.service
$ 
$ systemd-analyze verify --user ~/.config/systemd/user/bugdemo.timer
$ 
```
There is no terminating CPU consumption line in the journal.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
$ journalctl --no-hostname –-user -u bugdemo –-since 2023-07-25 --until 2023-07-26
Jul 25 16:04:11 systemd[357]: Starting Attempting to demonstrate a bug with systemd CPU consumption messages...
Jul 25 16:04:11 bugdemo.sh[184456]: Failed to connect to /run/systemd/resolve/io.systemd.Resolve: No such file or directory
Jul 25 16:04:12 bugdemo.sh[184456]: Failed to connect to /run/systemd/resolve/io.systemd.Resolve: No such file or directory
Jul 25 16:04:14 bugdemo.sh[184456]: PING systemd.io (185.199.111.153) 56(84) bytes of data.
Jul 25 16:04:14 bugdemo.sh[184456]: 64 bytes from cdn-185-199-111-153.github.com (185.199.111.153): icmp_seq=1 ttl=53 time=82.2 ms
Jul 25 16:04:14 bugdemo.sh[184456]: --- systemd.io ping statistics ---
Jul 25 16:04:14 bugdemo.sh[184456]: 1 packets transmitted, 1 received, 0% packet loss, time 0ms
Jul 25 16:04:14 bugdemo.sh[184456]: rtt min/avg/max/mdev = 82.184/82.184/82.184/0.000 ms
Jul 25 16:04:24 bugdemo.sh[184471]: Failed to connect to /run/systemd/resolve/io.systemd.Resolve: No such file or directory
Jul 25 16:04:24 bugdemo.sh[184471]: Failed to connect to /run/systemd/resolve/io.systemd.Resolve: No such file or directory
Jul 25 16:04:25 bugdemo.sh[184471]: PING systemd.io (185.199.110.153) 56(84) bytes of data.
Jul 25 16:04:25 bugdemo.sh[184471]: 64 bytes from cdn-185-199-110-153.github.com (185.199.110.153): icmp_seq=1 ttl=52 time=120 ms
Jul 25 16:04:25 bugdemo.sh[184471]: --- systemd.io ping statistics ---
Jul 25 16:04:25 bugdemo.sh[184471]: 1 packets transmitted, 1 received, 0% packet loss, time 0ms
Jul 25 16:04:25 bugdemo.sh[184471]: rtt min/avg/max/mdev = 120.421/120.421/120.421/0.000 ms
Jul 25 16:04:35 systemd[357]: Finished Attempting to demonstrate a bug with systemd CPU consumption messages.
```

**Comment by Werkov** [comment] 2023-07-28 12:40
@e-Gyi-qO What log level do you use?
(The consumption message have debug level when consumption is below 1s, hence with the default settings, you may only see service runs that consume above 1s.)

**Comment by e-Gyi-qO** [comment] 2023-07-29 13:07
> @e-Gyi-qO What log level do you use?

I haven't configured a log level explicitly. There is a ``#MaxLevelSyslog=debug`` line at /etc/systemd/journald.conf. Does that answer your question? How can I find out which log level I am using?

> (The consumption message have debug level when consumption is below 1s, hence with the default settings, you may only see service runs that consume above 1s.)

I am totally confused by this part of your reply. Can you explain that is a much slower pace? Do you suggest to change ``bugdemo.sh`` to something like having a long running ``find`` command? Or some not short compilation process?

**Comment by Werkov** [comment] 2023-07-30 10:13
The logging level of systemd user instance is what's relevant in this case. You can check/modify it with:
```
systemd-analyze --user get-log-level
systemd-analyze --user set-log-level <level>
```

I mean that with the default logging, you will only see the CPU consumption message when the CPU time spent is more than 1 second (and higher logging level would emit the message unconditionally).
Hence, if you saw apparently random omission of the messages, it would be caused by CPU duration of the service being randomly below or above 1 second.

**Comment by mrc0mmand** [comment] 2023-07-30 12:00
> The logging level of systemd user instance is what's relevant in this case. You can check/modify it with:
> 
> ```
> systemd-analyze --user get-log-level
> systemd-analyze --user set-log-level <level>
> ```

Just a note here - the `[{get,set}-]log-level` verbs in `systemd-analyze` are deprecated since 26e1e97345, you should use `systemctl [--user] log-level [new-level]` instead.

**Comment by e-Gyi-qO** [comment] 2023-07-31 15:55
When the consumption is less than 1s, perhaps a ``CPU consumption was less than 1s`` message should appear in the journal?
```
$ systemctl --user log-level
info
```
I will replace ``bugdemo.sh`` from above with the following script, in a hope it is always have a greater than 1s CPU consumption. I will report back within 1 week, or so:
```
#! /bin/bash
# ~/.config/systemd/user/bugdemo.sh

# A bash script to demonstrate a possible bug in systemd consumption CPU summary.
# The script is run by a service, which is periodically activated by a 
# user timer.

# Hopefully, it will always consume CPU for more than 1s.
timeout 25s find / -type f -readable -execdir grep --quiet 2143658709badcfehgjilknmporqtsvuxwzy \{\} \;
```

**Comment by e-Gyi-qO** [comment] 2023-08-08 19:49
By using
> `timeout 5s sh -c "while true ; do true ; done"`

suggested above, it does look like the consumption summary lines were missing at my journal because there were instances where the units CPU consumption were less then 1sec.
I do think it worth rethinking if in those circumstances it is not worth adding an appropriate message to the journal, instead of full silence.
Should I close this issue, or wait for someone to announce here the outcome of such rethinking?

**Comment by Werkov** [comment] 2023-08-09 11:59
Thanks for checking.
I reckon this is no bug in accounting then and if you enable debug level logging, you see the message every time (not only >1s).

Originally, the [behavior was more chatty](https://github.com/systemd/systemd/pull/13206). So this would actually be re-re-thinking. To avoid being stuck in circles, I'll close the issue for you ;-)

**Closed as completed by Werkov** 2023-08-09 11:59 UTC
Labels: bug 🐛, needs-reporter-feedback ❓

**Comment by poettering** [comment] 2023-08-09 13:35
> instead of full silence.

it's not precisely "full silence". it's still logged, but ad debug level.

**Comment by e-Gyi-qO** [comment] 2023-08-10 17:31
What about documentation? At https://github.com/systemd/systemd/blob/main/man/systemd-system.conf.xml? At https://github.com/systemd/systemd/blob/main/man/systemd.resource-control.xml? Somewhere else? Not at all?

**Comment by Werkov** [comment] 2023-08-11 08:20
Feel free to extend the [catalog](https://github.com/systemd/systemd/blob/main/catalog/systemd.catalog.in).
But if you're in the need of the data, I'd suggest checking `systemctl show -p CPUUsageNSec $unit` instead of relying on a log message.
