### ISSUE TITLE
/etc configuration of journald doesn't override dropin in /usr/lib

### ISSUE THREAD

**Issue by utezduyar** [systemd/systemd#4940] opened 2016-12-21 13:50 UTC
### Submission type

  - [x] Bug report

### systemd version the issue has been seen with

> 231

### Used distribution

> Yocto

### In case of bug report: Expected behaviour you didn't see

Seems like the journal configuration in /etc doesn't override the drop-in created in /usr/lib.

```
root@axis-00408c186048:~# journalctl
No journal files were found.
-- No entries --
root@axis-00408c186048:~# cat /usr/lib/systemd/journald.conf.d/50-axis.conf 
[Journal]
Storage=none
RateLimitInterval=0
RateLimitBurst=0
ForwardToConsole=yes
MaxLevelConsole=warning
ForwardToSyslog=yes
root@axis-00408c186048:~# cat /etc/systemd/journald.conf 
[Journal]
Storage=auto
```

**Comment by fsateler** [comment] 2016-12-21 15:45
Dupe of #2121 , which was closed. However, I still think the current behavior is wrong.

**Comment by poettering** [comment] 2016-12-21 17:48
Yeah, this is by design, drop-in snippets always override the main configuration. drop-ins in /etc override drop-ins in /usr/lib however, hence mask the drop-in in /etc to disable its effect.

**Closed as completed by poettering** 2016-12-21 17:48 UTC
Labels: journal, not-a-bug

**Comment by arvidjaar** [comment] 2016-12-22 04:02
This means that administrator must hunt for all drop-ins to make sure they do not contain unwanted settings and if any package installs new drop-in it suddenly may change configuration, recorded in /etc.

For units we at least can see drop-ins with `systemctl status`. Any way to see it for journal?

**Comment by poettering** [comment] 2016-12-22 09:43
> This means that administrator must hunt for all drop-ins to make sure they do not contain unwanted settings and if any package installs new drop-in it suddenly may change configuration, recorded in /etc.

I think it would be a good idea for general purpose distros not to ship any drop-ins in /usr/lib, but instead just edit the journald.conf file shipped there directly.

> For units we at least can see drop-ins with systemctl status. Any way to see it for journal?

Nope, sorry.
