### ISSUE TITLE
[   ***] A stop job is running for Network Time Synchronization (6s / 1min 30s)

### ISSUE THREAD

**Issue by qqdxgg** [systemd/systemd#25511] opened 2022-11-24 08:56 UTC
**Hi friends:**
 I recently ran into a problem with my linux embedded development board. When I run the reboot command, it delays on stopping the timesync process about a minute.
`[   ***] A stop job is running for Network Time Synchronization (6s / 1min 30s)`
Please give me some advices, if you knows this issue. Thanks you.

Note:
1. My linux board can't connect to internet.
2.  Linux version is 5.15.76. Systemd version is 250.5+

**Comment by yuwata** [comment] 2022-11-24 11:51
Could you provide debugging log of shutdown or reboot process? Debugging logs can be generated by booting `systemd.log_level=debug`.

**Comment by qqdxgg** [comment] 2022-11-25 09:53
@yuwata Thank you. It.s has been fixed. This issue is caused by my board can't access to NTP server of internet.

**Comment by Werkov** [comment] 2022-11-25 23:37
FTR, I can't reproduce it (stop job timeout of `systemd-timesyncd.service`) with current (6042b60def) systemd in qemu with mkosi (Arch) image. (#16529 for possible context.)

Since reporter is happy, I'm closing this.

**Closed as completed by Werkov** 2022-11-25 23:37 UTC
Labels: pid1, timesync, needs-reporter-feedback ❓, shutdown

**Comment by Bartel-C8** [comment] 2025-03-10 14:20
Same problem here on a embedded system without internet connection:


A long timeout when rebooting. Also a manual stop has this issue: `systemctl stop systemd-timesyncd`

Log:
```
Jul 24 12:49:47 systemd[1]: Starting Network Time Synchronization...
Jul 24 12:49:47 systemd[1]: Started Network Time Synchronization.
Jul 24 12:49:48 systemd-timesyncd[945]: Network configuration changed, trying to establish connection.
Jul 24 12:49:49 systemd-timesyncd[945]: Network configuration changed, trying to establish connection.
Jul 24 12:49:50 systemd-timesyncd[945]: Network configuration changed, trying to establish connection.
Jul 24 12:49:54 systemd-timesyncd[945]: Network configuration changed, trying to establish connection.
Jul 24 12:49:54 systemd-timesyncd[945]: Network configuration changed, trying to establish connection.
Jul 24 12:50:01 systemd-timesyncd[945]: Network configuration changed, trying to establish connection.
Jul 24 12:59:25 systemd[1]: Stopping Network Time Synchronization...
Jul 24 13:00:55 systemd[1]: systemd-timesyncd.service: State 'stop-sigterm' timed out. Killing.
Jul 24 13:00:55 systemd[1]: systemd-timesyncd.service: Killing process 945 (systemd-timesyn) with signal SIGKILL.
Jul 24 13:00:55 systemd[1]: systemd-timesyncd.service: Killing process 947 (sd-resolve) with signal SIGKILL.
Jul 24 13:00:55 systemd[1]: systemd-timesyncd.service: Main process exited, code=killed, status=9/KILL
Jul 24 13:00:55 systemd[1]: systemd-timesyncd.service: Failed with result 'timeout'.
Jul 24 13:00:55 systemd[1]: Stopped Network Time Synchronization.
```
