### ISSUE TITLE
systemd-delta displays symlink target wrong

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#18845] opened 2021-03-02 14:18 UTC
**systemd version the issue has been seen with**
 > Recent git.

```console
$ systemd-delta
[EQUIVALENT] /etc/systemd/system/ctrl-alt-del.target → /usr/lib/systemd/system/ctrl-alt-del.target
[REDIRECTED] /etc/systemd/system/default.target → /usr/lib/systemd/system/default.target
$ ls -l /etc/systemd/system/ctrl-alt-del.target /etc/systemd/system/default.target
lrwxrwxrwx. 1 root root 37 Nov  7 18:40 /etc/systemd/system/ctrl-alt-del.target -> /usr/lib/systemd/system/reboot.target
lrwxrwxrwx. 1 root root 41 Jan 16 15:16 /etc/systemd/system/default.target -> /usr/lib/systemd/system/multi-user.target
```
It seems strange to show `/usr/lib/systemd/system/default.target`.

Also:
```console
[EXTENDED]   /usr/lib/systemd/system/systemd-hostnamed.service → /usr/lib/systemd/system/systemd-hostnamed.service.d/disable-privatedevices.conf
[EXTENDED]   /usr/lib/systemd/system/systemd-logind.service → /usr/lib/systemd/system/systemd-logind.service.d/10-grub2-logind-service.conf
[EXTENDED]   /usr/lib/systemd/system/systemd-udev-trigger.service → /usr/lib/systemd/system/systemd-udev-trigger.service.d/systemd-udev-trigger-no-reload.conf
```
I think we should use something different than "→" here. Maybe ":" ?

**Comment by dtardon** [comment] 2022-07-15 15:11
This is a duplicate of #6534, isn't it?

**Closed as not planned** 2023-03-03 09:39 UTC
Labels: bug 🐛, delta, duplicate
