### ISSUE TITLE
user@32.service: Failed at step PAM spawning /usr/lib/systemd/systemd: Operation not permitted

### ISSUE THREAD

**Issue by rafbee** [systemd/systemd#6038] opened 2017-05-26 12:57 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

233

### Used distribution

gentoo

$ uname -a
Linux ws2912 4.11.1-gentoo #3 SMP Wed May 17 10:13:46 CEST 2017 i686 Intel(R) Pentium(R) 4 CPU 3.40GHz GenuineIntel GNU/Linux

### In case of bug report: Expected behaviour you didn't see

Gnome Display Manager (gdm) starts at boot

### In case of bug report: Unexpected behaviour you saw
The display manager is not started. The User Manager for user gdm continuously starts and dies:

$ grep gdm /etc/passwd
`gdm:x:32:32:GDM:/var/lib/gdm:/bin/false`

$ systemctl status  user@32.service
● user@32.service - User Manager for UID 32
   Loaded: loaded (/usr/lib/systemd/system/user@.service; static; vendor preset: disabled)
   Active: failed (Result: protocol) since Fri 2017-05-26 08:17:25 CEST; 6h ago
  Process: 516 ExecStart=/usr/lib/systemd/systemd --user (code=exited, status=224/PAM)
 Main PID: 516 (code=exited, status=224/PAM)

May 26 08:17:25 ws2912 systemd[1]: Starting User Manager for UID 32...
May 26 08:17:25 ws2912 systemd[516]: user@32.service: Failed at step PAM spawning /usr/lib/systemd/systemd: Operation not permitted
May 26 08:17:25 ws2912 systemd[1]: Failed to start User Manager for UID 32.
May 26 08:17:25 ws2912 systemd[1]: user@32.service: Unit entered failed state.
May 26 08:17:25 ws2912 systemd[1]: user@32.service: Failed with result 'protocol'.

Already checked bug https://github.com/systemd/systemd/issues/4342, this system does not seem affected:

$ cat /etc/pam.d/systemd-user
account include system-auth
session include system-auth
session optional pam_keyinit.so force revoke
session optional pam_systemd.so

$ cat /etc/pam.d/system-auth 
auth		required	pam_env.so 
auth		required	pam_unix.so try_first_pass likeauth nullok 
auth		optional	pam_permit.so
account		required	pam_unix.so 
account		optional	pam_permit.so
...

### In case of bug report: Steps to reproduce the problem

$ systemctl enable gdm

**Comment by poettering** [comment] 2017-05-29 09:51
Well, PAM returns an error on your system for the gdm user. PAM is mostly a black box for systemd, you'd have to use PAM tools to figure out why exactly PAM refuses operation here. 

Do you use any weird security framework such as grsecurity, selinux, apparmor, or something like that?

I figure we can't help you much with this one, it's really between PAM and your distro's systemd packagers. I will close this hence here now. Please contact your distro's systemd and PAM packagers to figure out what might be going on, but this is really outside of systemd's scope, we take the interface PAM is as it is and do not introspect or trace it. Sorry!

**Closed as completed by poettering** 2017-05-29 09:51 UTC
Labels: not-our-bug

**Comment by basdebakker** [comment] 2017-09-04 12:09
I also ran into this issue and there is not much to find about it. I have no clue about the root cause, but for anyone finding this web page here's what resolved it for me:
1. Unmerge gdm.
2. Remove the gdm user, the gdm group and any files in /var/lib/gdm.
3. Merge gdm. This created a new gdm user with a different uid.

**Comment by rafbee** [comment] 2017-09-05 06:00
Wow, it works for me also! Thanks a lot.

**Comment by vjt** [comment] 2020-01-30 18:12
Well, in my case, that may be well different than yours but I got here at the second google result, was that my user was present in `/etc/passwd` but not in `/etc/shadow`, as I had created it manually. That was an inconsistency that was not inserting the user in the `passwd` authentication database, and `PAM` complained. Adding a row in `/etc/shadow` for the user fixed my issue. Cheers
