### ISSUE TITLE
Issue in services dependency using systemd.path

### ISSUE THREAD

**Issue by pcoves** [systemd/systemd#20737] opened 2021-09-14 15:40 UTC
**systemd version the issue has been seen with**
 
Both `249.4-1` and `241-7~deb10u8`

**Used distribution**

Both Arch and Debian Buster

**Linux kernel version used** (`uname -a`)

* `Linux talus 5.14.2-arch1-2 #1 SMP PREEMPT Thu, 09 Sep 2021 09:42:35 +0000 x86_64 GNU/Linux`
* `Linux ip-10-115-151-30 4.19.0-17-cloud-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 GNU/Linux`

**CPU architecture issue was seen on**

X86_64 on both

**(Un)Expected behaviour **

I have five files:

* `oneshot.service`
```
[Unit]
Description = Service A

[Service]
Type = oneshot
ExecStart = sh -c "echo 'Service A';sleep 5; echo 'Service A again'"
```

* `oneshot.path`
```
[Unit]
Description = Oneshot Path

[Path]
PathChanged = /tmp/path
MakeDirectory = true

[Install]
WantedBy = default.target
```

* `watcher.service`
```
[Unit]
Description = Watcher Service

[Service]
ExecStart = systemctl --user restart oneshot.service
```

* `watcher.path`
```
[Unit]
Description = Watcher Path

[Path]
PathChanged = /tmp/path
MakeDirectory = true

[Install]
WantedBy = default.target
```

* `simple.service`
```
[Unit]
Description = Simple service

Requires = oneshot.service
After    = oneshot.service
PartOf   = oneshot.service

[Service]
ExecStart = sh -c "while true; do echo 'Simple service' && sleep 1; done"

[Install]
WantedBy = oneshot.service
```

First step is to `systemctl start simple.service` that *Requires* and is *PartOf* `oneshot.service`.
At this point, `journalctl -feu simple.service` show a `Simple service` every second which is normal.

Second step: `systemctl start oneshot.service`.
At this point, `oneshot.service` starts and `simple.services` restarts as its *PartOf` `oneshot.service` which is normal.

Third point, `systemctl start watcher.path; echo whatever >> /tmp/path/foo`.
At this point, `watcher.service` is triggered which in turn restarts  `oneshot.service` which restarts `simple.service` which is normal as seen previously.

Last point: `systemctl stop watcher.path; systemctl start oneshot.path; echo whatever >> /tmp/path/foo`.
Here, only `oneshot.service` restarts but not `simple.service`.

As pointed out, using a *proxy* `watcher.{path,service}` does the trick but given the documentation I thought it'd be ok without this.
Also, adding `Unit = oneshot.service` in the `watcher.path` exposes the same behavior as in the last point.

**Comment by poettering** [comment] 2021-09-29 08:10
I am not sure I follow. What do you mean by "restart"? And actualy "restart" job? or just another "start" job? I cannot parse what the issue is supposed to be here?

**Comment by pcoves** [comment] 2021-09-29 08:28
In real life, I've a cascade of services that are restarted along with my `simple.service`.

As the `simple.service` is `PartOf` the `oneshot.service` I expected it (`simple.service`) to be *restarted* as in `systemctl restart simple.service` even if it's already *up and running*.

It's not the case unless I use the *watcher.{service,path}` proxy service to explicitly restart it.

**Comment by arvidjaar** [comment] 2021-10-02 07:34
> First step is to systemctl start simple.service that Requires and is PartOf oneshot.service.
> At this point, journalctl -feu simple.service show a Simple service every second which is normal.

Here simple.service remains active and oneshot.service has been started (due to Requires) and is now inactive as it does not have RemainAfterExit.

> Second step: systemctl start oneshot.service.
> At this point, oneshot.service starts and simple.services restarts as its *PartOf oneshot.service` which is normal.

`simple.service` is not restarted here nor do I see any reason why it should be restarted. 

Show `systemctl status` output for each service after each step.

**Comment by poettering** [comment] 2023-06-06 16:02
CLosing, since the equested data was never provided.

**Closed as completed by poettering** 2023-06-06 16:02 UTC
Labels: pid1, needs-reporter-feedback ❓
