### ISSUE TITLE
systemd support dns over https

### ISSUE THREAD

**Issue by olumolu** [systemd/systemd#32970] opened 2024-05-22 07:27 UTC
### Component

systemd-resolved

### Is your feature request related to a problem? Please describe

Systemd support for dns over tls but does not support for dns over https.
https://developers.google.com/speed/public-dns/docs/doh
This is a safe way of getting dns when port 53 is blocked.
And you need encrypted dns. The only way to have this is to use doh.

### Describe the solution you'd like

Dns over https implementation of doh in systemd-resolved.

### Describe alternatives you've considered

Nothing

**Comment by bluca** [comment] 2024-05-22 10:11
Duplicate of https://github.com/systemd/systemd/issues/8639

**Closed as not planned by bluca** 2024-05-22 10:11 UTC
Labels: resolve, duplicate
