### ISSUE TITLE
mkosi CIs get stuck in the Debian Testing and C9S jobs

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#24202] opened 2022-08-04 13:18 UTC
### systemd version the issue has been seen with

latest main

### Used distribution

Ubuntu Jammy

### Expected behaviour you didn't see

All mkosi CIs should pass.

### Unexpected behaviour you saw

Currently both Debian Testing and CentOS Stream 9 jobs get stuck for ~6 hours due to:

```
Run ./.github/workflows/run_mkosi.sh qemu
  ./.github/workflows/run_mkosi.sh qemu
  shell: /usr/bin/bash -e {0}
  env:
    KERNEL_CMDLINE: systemd.unit=mkosi-check-and-shutdown.service !quiet systemd.log_level=debug systemd.log_target=console udev.log_level=info systemd.default_standard_output=journal+console
‣ Running command:
‣ qemu-system-x86_64 -machine type=q35,accel=tcg,smm=on -smp 1 -m 2G -object rng-random,filename=/dev/urandom,id=rng0 -device virtio-rng-pci,rng=rng0,id=rng-device0 -cpu max -nographic -nodefaults -serial mon:stdio -nic tap,script=no,downscript=no,ifname=vt-image,model=virtio-net-pci -drive if=pflash,format=raw,readonly=on,file=/usr/share/OVMF/OVMF_CODE.secboot.fd -global ICH9-LPC.disable_s3=1 -global driver=cfi.pflash01,property=secure,value=on -drive file=/var/tmp/.mkosi-6ww9kyhs,if=pflash,format=raw -drive if=none,id=hd,file=/home/runner/work/systemd/systemd/image.raw,format=raw -device virtio-scsi-pci,id=scsi -device scsi-hd,drive=hd,bootindex=1

3hBdsDxe: loading Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x3,0x0)/Scsi(0x0,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x3,0x0)/Scsi(0x0,0x0)
systemd-boot@0x7D34B000,0x7D369000
!!!! X64 Exception Type - 0D(#GP - General Protection)  CPU Apic ID - 00000000 !!!!
ExceptionData - 0000000000000000
RIP  - 0000000072A7938C, CS  - 0000000000000038, RFLAGS - 0000000000000206
RAX  - 000A226DD40B8274, RCX - 0000000000000EB8, RDX - 0000000072A81180
RBX  - 000000007D369000, RSP - 000000007EFB4558, RBP - 000000007EFB46C0
RSI  - 0000000072A800A8, RDI - 0000000072A61000
R8   - 0000000000000018, R9  - 0000000000000000, R10 - 000000007DAD1098
R11  - 000000007DC1B65C, R12 - 0000000000000000, R13 - 000000007D3702B0
R14  - 000000007DCE47FC, R15 - 000000007EFCB440
DS   - 0000000000000030, ES  - 0000000000000030, FS  - 0000000000000030
GS   - 0000000000000030, SS  - 0000000000000030
CR0  - 0000000080010033, CR2 - 0000000000000000, CR3 - 000000007EC01000
CR4  - 0000000000000668, CR8 - 0000000000000000
DR0  - 0000000000000000, DR1 - 0000000000000000, DR2 - 0000000000000000
DR3  - 0000000000000000, DR6 - 00000000FFFF0FF0, DR7 - 0000000000000400
GDTR - 000000007E9E3000 0000000000000047, LDTR - 0000000000000000
IDTR - 000000007E4E3018 0000000000000FFF,   TR - 0000000000000000
FXSAVE_STATE - 000000007EFB41B0
!!!! Find image based on IP(0x72A7938C) (No PDB)  (ImageBase=0000000072A61000, EntryPoint=0000000072A66000) !!!!
Error: The operation was canceled.
```

Example jobs:
  * https://github.com/systemd/systemd/runs/7661904883?check_suite_focus=true
  * https://github.com/systemd/systemd/runs/7661962008?check_suite_focus=true
  * https://github.com/systemd/systemd/runs/7654347531?check_suite_focus=true

/cc @DaanDeMeyer

**Comment by mrc0mmand** [comment] 2022-08-04 21:56
Interesting. I played around a bit, went through the CI history & logs, and the issue seems to be introduced by e6b0cfa. After reverting it (and the follow-up commits from https://github.com/systemd/systemd/pull/24189) the CIs pass once again. I also tested the follow-up commits separately and the boot still fails even after reverting them, so the issue seems to be introduced directly by e6b0cfa.

Since the EFI stuff is still mostly a black magic to me, I'm not sure how to debug this further, but if the need arises, I can prepare a machine in the CI with a shell on it for further debugging.

I have a couple of tests still running, but everything points to e6b0cfa, at least so far.

/cc @medhefgo @vdagonneau-anssi @poettering

**Comment by mrc0mmand** [comment] 2022-08-04 22:09
Yup, with e6b0cfa reverted, everything boots normally:

```

Run ./.github/workflows/run_mkosi.sh qemu
  ./.github/workflows/run_mkosi.sh qemu
  shell: /usr/bin/bash -e {0}
  env:
    KERNEL_CMDLINE: systemd.unit=mkosi-check-and-shutdown.service !quiet systemd.log_level=debug systemd.log_target=console udev.log_level=info systemd.default_standard_output=journal+console
‣ Running command:
‣ qemu-system-x86_64 -machine type=q35,accel=tcg,smm=on -smp 1 -m 2G -object rng-random,filename=/dev/urandom,id=rng0 -device virtio-rng-pci,rng=rng0,id=rng-device0 -cpu max -nographic -nodefaults -serial mon:stdio -nic tap,script=no,downscript=no,ifname=vt-image,model=virtio-net-pci -drive if=pflash,format=raw,readonly=on,file=/usr/share/OVMF/OVMF_CODE.secboot.fd -global ICH9-LPC.disable_s3=1 -global driver=cfi.pflash01,property=secure,value=on -drive file=/var/tmp/.mkosi-7l1odlc1,if=pflash,format=raw -drive if=none,id=hd,file=/home/runner/work/systemd/systemd/image.raw,format=raw -device virtio-scsi-pci,id=scsi -device scsi-hd,drive=hd,bootindex=1
3hBdsDxe: loading Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x3,0x0)/Scsi(0x0,0x0)
BdsDxe: starting Boot0001 "UEFI QEMU QEMU HARDDISK " from PciRoot(0x0)/Pci(0x3,0x0)/Scsi(0x0,0x0)
systemd-boot@0x7D34D000,0x7D36B000
systemd-stub@0x729F9000,0x72A0D000
EFI stub: Loaded initrd from LINUX_EFI_INITRD_MEDIA_GUID device path
systemd 251 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Virtualization QEMU found in DMI (/sys/class/dmi/id/sys_vendor)
UML virtualization not found in /proc/cpuinfo.
Virtualization XEN not found, /proc/xen does not exist
Virtualization found, CPUID=TCGTCGTCGTCG
Found VM virtualization qemu
Detected virtualization qemu.
Detected architecture x86-64.
Running in initial RAM disk.
Kernel version 5.14.0-134.el9.x86_64, our baseline is 4.15
Welcome to CentOS Stream 9 dracut-057-10.git20220721.el9 (Initramfs)!
...
```

```
Run ./.github/workflows/run_mkosi.sh qemu
  ./.github/workflows/run_mkosi.sh qemu
  shell: /usr/bin/bash -e {0}
  env:
    KERNEL_CMDLINE: systemd.unit=mkosi-check-and-shutdown.service !quiet systemd.log_level=debug systemd.log_target=console udev.log_level=info systemd.default_standard_output=journal+console
‣ Running command:
‣ qemu-system-x86_64 -machine type=q35,accel=tcg,smm=on -smp 1 -m 2G -object rng-random,filename=/dev/urandom,id=rng0 -device virtio-rng-pci,rng=rng0,id=rng-device0 -cpu max -nographic -nodefaults -serial mon:stdio -nic tap,script=no,downscript=no,ifname=vt-image,model=virtio-net-pci -drive if=pflash,format=raw,readonly=on,file=/usr/share/OVMF/OVMF_CODE.secboot.fd -global ICH9-LPC.disable_s3=1 -global driver=cfi.pflash01,property=secure,value=on -drive file=/var/tmp/.mkosi-sogipuyd,if=pflash,format=raw -drive if=virtio,id=hd,file=/home/runner/work/systemd/systemd/image.raw,format=raw

3hBdsDxe: loading Boot0001 "UEFI Misc Device" from PciRoot(0x0)/Pci(0x3,0x0)
BdsDxe: starting Boot0001 "UEFI Misc Device" from PciRoot(0x0)/Pci(0x3,0x0)
systemd-boot@0x7D0F4000,0x7D112000
systemd-stub@0x76BAC000,0x76BC0000
EFI stub: Loaded initrd from LINUX_EFI_INITRD_MEDIA_GUID device path
systemd 251 running in system mode (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization qemu.
Detected architecture x86-64.
Running in initial RAM disk.
Kernel version 5.18.0-3-amd64, our baseline is 4.15

Welcome to Debian GNU/Linux bookworm/sid dracut-056-3 (Initramfs)!
...
```

**Comment by vdagonneau-anssi** [comment] 2022-08-04 22:09
Mmmh, usually this error means that Secure Boot is activated, has been locked down and there are no valid UEFI binaries to boot from.

I suspect something is wrong with the way OVMF_VARS are passed to the VM, e.g. the OVMF_VARS might get reused from a previous run. From my understanding of the qemu command line (`-drive file=/var/tmp/.mkosi-6ww9kyhs,if=pflash,format=raw`), the OVMF_VARS are copied in /tmp before getting used.

I also found this (closed) issue in mkosi (https://github.com/systemd/mkosi/pull/650), might be linked? From what I understand

**Comment by medhefgo** [comment] 2022-08-05 09:03
> Since the EFI stuff is still mostly a black magic to me, I'm not sure how to debug this further, but if the need arises, I can prepare a machine in the CI with a shell on it for further debugging.

You can join the club. I am the president. :joy_cat:

This is another case I encountered here: https://github.com/systemd/systemd/pull/23706#issuecomment-1173721470

Basically, code size blows up too much and breaks *something* (could be gnu-efi, ovmf, or just the way we assemble/build/create our efi binary). Our code still works perfectly fine (and correctly, as far as I can tell) and calls StatImage on the kernel. And then an the exception happens. Note in particular, that the `secure_boot_enroll_at` function doesn't even get called!

The nice thing (to me) it that this now happens without even having my printf implementation anywhere, so I can be sure it does nothing wrong. :D

Here is *one* minimized code that breaks for me. Remove the `clear_screen(COLOR_NORMAL);` and it works again!!
<details>

```
/* SPDX-License-Identifier: LGPL-2.1-or-later */

#include "sbat.h"
#include "secure-boot.h"
#include "console.h"
#include "util.h"

bool secure_boot_enabled(void) {
        return false;
}

SecureBootMode secure_boot_mode(void) {
        return SECURE_BOOT_UNSUPPORTED;
}

#ifdef SBAT_DISTRO
static const char sbat[] _used_ _section_(".sbat") = SBAT_SECTION_TEXT;
#endif

EFI_STATUS secure_boot_enroll_at(EFI_FILE *root_dir, const char16_t *path) {
        assert(root_dir);
        assert(path);

        EFI_STATUS err;

        clear_screen(COLOR_NORMAL);

        Print(L"Enrolling secure boot keys from directory: %s\n"
              L"Warning: Enrolling custom Secure Boot keys might soft-brick your machine!\n",
              path);

        unsigned timeout_sec = 15;
        for(;;) {
                /* Enrolling secure boot keys is safe to do in virtualized environments as there is nothing
                 * we can brick there. */
                if (in_hypervisor())
                        break;

                PrintAt(0, ST->ConOut->Mode->CursorRow, L"Enrolling in %2u s, press any key to abort.", timeout_sec);

                uint64_t key;
                err = console_key_read(&key, 1000 * 1000);
                if (err == EFI_NOT_READY)
                        continue;
                if (err == EFI_TIMEOUT) {
                        if (timeout_sec == 0) /* continue enrolling keys */
                                break;
                        timeout_sec--;
                        continue;
                }
                if (err != EFI_SUCCESS)
                        return log_error_status_stall(err, L"Error waiting for user input to enroll Secure Boot keys: %r", err);

                /* user aborted, returning EFI_SUCCESS here allows the user to go back to the menu */
                return EFI_SUCCESS;
        }

        _cleanup_(file_closep) EFI_FILE *dir = NULL;

        err = open_directory(root_dir, path, &dir);
        if (err != EFI_SUCCESS)
                return log_error_status_stall(err, L"Failed opening keys directory %s: %r", path, err);

        struct {
                const char16_t *name;
                const char16_t *filename;
                const EFI_GUID vendor;
                char *buffer;
                size_t size;
        } sb_vars[] = {
                { u"db",  u"db.auth",  EFI_IMAGE_SECURITY_DATABASE_VARIABLE, NULL, 0 },
                { u"KEK", u"KEK.auth", EFI_GLOBAL_VARIABLE, NULL, 0 },
                { u"PK",  u"PK.auth",  EFI_GLOBAL_VARIABLE, NULL, 0 },
        };

        /* Make sure all keys files exist before we start enrolling them by loading them from the disk first. */
        for (size_t i = 0; i < ELEMENTSOF(sb_vars); i++) {
                err = file_read(dir, sb_vars[i].filename, 0, 0, &sb_vars[i].buffer, &sb_vars[i].size);
                if (err != EFI_SUCCESS) {
                        log_error_stall(L"Failed reading file %s\\%s: %r", path, sb_vars[i].filename, err);
                        goto out_deallocate;
                }
        }

        for (size_t i = 0; i < ELEMENTSOF(sb_vars); i++) {
                uint32_t sb_vars_opts =
                        EFI_VARIABLE_NON_VOLATILE |
                        EFI_VARIABLE_BOOTSERVICE_ACCESS |
                        EFI_VARIABLE_RUNTIME_ACCESS |
                        EFI_VARIABLE_TIME_BASED_AUTHENTICATED_WRITE_ACCESS;

                err = efivar_set_raw(&sb_vars[i].vendor, sb_vars[i].name, sb_vars[i].buffer, sb_vars[i].size, sb_vars_opts);
                if (err != EFI_SUCCESS) {
                        log_error_stall(L"Failed to write %s secure boot variable: %r", sb_vars[i].name, err);
                        goto out_deallocate;
                }
        }

        /* The system should be in secure boot mode now and we could continue a regular boot. But at least
         * TPM PCR7 measurements should change on next boot. Reboot now so that any OS we load does not end
         * up relying on the old PCR state. */
        RT->ResetSystem(EfiResetCold, EFI_SUCCESS, 0, NULL);
        assert_not_reached();

out_deallocate:
        for (size_t i = 0; i < ELEMENTSOF(sb_vars); i++)
                FreePool(sb_vars[i].buffer);

        return err;
}
```

</details>

The simplest workaround (as I did in the linked PR) is to force at least `-O1` as that seems to condense code enough to unbreak things. Ultimately, I'd really like to get the printf thing merged so I can finish the removal of `libefi.a`, which also helps.

**Comment by medhefgo** [comment] 2022-08-05 09:05
Also, just like the linked PR, it would be really nice if we could get ovmf/qemu to exit with an error instead of just idling around. Or reduce the timeout and have that actually be considered an error instead of ignoring it.

**Closed as completed** 2022-08-06 14:42 UTC
Labels: bug 🐛, sd-boot/sd-stub/bootctl, mkosi, ci, ci-blocker 🚧

**Comment by medhefgo** [comment] 2022-09-03 16:41
I think I found the true reason for the breakage: the stub binary has become so big (in unoptimized debug builds) that the section VMA values that are used in objcopy are too low, causing code/data corruption.

Sections with no optimization:
```
Idx Name          Size      VMA               LMA               File off  Algn
  0 .text         00015640  0000000000003000  0000000000003000  00000400  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  1 .reloc        0000000c  0000000000019000  0000000000019000  00015c00  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  2 .data         00004b98  000000000001a000  000000000001a000  00015e00  2**4
                  CONTENTS, ALLOC, LOAD, DATA
  3 .dynamic      00000110  000000000001f000  000000000001f000  0001aa00  2**2
                  CONTENTS, ALLOC, LOAD, DATA
  4 .rela         00001038  0000000000020000  0000000000020000  0001ac00  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  5 .dynsym       00000018  0000000000022000  0000000000022000  0001be00  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  6 .sbat         000000df  0000000000024000  0000000000024000  0001c000  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  7 .sdmagic      00000036  00000000000240e0  00000000000240e0  0001c200  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
```

Sections with `-O1` build:
```
Idx Name          Size      VMA               LMA               File off  Algn
  0 .text         0000ecd0  0000000000003000  0000000000003000  00000400  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  1 .reloc        0000000c  0000000000012000  0000000000012000  0000f200  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  2 .data         00004698  0000000000013000  0000000000013000  0000f400  2**4
                  CONTENTS, ALLOC, LOAD, DATA
  3 .dynamic      00000110  0000000000018000  0000000000018000  00013c00  2**2
                  CONTENTS, ALLOC, LOAD, DATA
  4 .rela         00000f90  0000000000019000  0000000000019000  00013e00  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  5 .dynsym       00000018  000000000001a000  000000000001a000  00014e00  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  6 .sbat         000000df  000000000001c000  000000000001c000  00015000  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  7 .sdmagic      00000036  000000000001c0e0  000000000001c0e0  00015200  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
```

Note the VMA of the last section is `0x1c0e0` vs `0x240e0`. Now the problem is that our (and everyone else's) docs say to use `--change-section-vma .osrel=0x20000` (and the other values are similarly pulled out of nowhere), which may end up overriding something in the binary. I even checked this may setting .cmdline and .osrel to the same VMA and sure enough one overrode the other once it was put into memory by LoadImage.

Ultimately, this means that the stub assembling instructions need to be adjusted quite a bit to make sure people only use VMA values that don't overlap. This would really need to be communicated to initrd tools especially (urgh). I think it makes sense at this point to provide a helper tool that does this and make it the preferred (or only supported) method from then on (even if it still calls objcopy under the hood).

@poettering Your thoughts on this would be nice…

**Comment by poettering** [comment] 2022-09-09 19:48
Hmm, I think the only thing that really matters is that we don't have the stuff in certain low addresses. After that it could all be packed as much as we want. Somebody needs to sit down and figure out how to make objcopy do that...

It's a bit stupid we pick these offsets from thin air.

**Comment by medhefgo** [comment] 2022-09-09 20:05
> Hmm, I think the only thing that really matters is that we don't have the stuff in certain low addresses. After that it could all be packed as much as we want. Somebody needs to sit down and figure out how to make objcopy do that...
> 
> It's a bit stupid we pick these offsets from thin air.

You can't really do that. native clang efi builds can pick some really large numbers (though, it doesn't apply to our builds (yet)):
```
Sections:
Idx Name          Size      VMA               LMA               File off  Algn
  0 .text         000227dc  0000000140001000  0000000140001000  00000400  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  1 .rdata        000068ae  0000000140024000  0000000140024000  00022c00  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  2 .data         00000048  000000014002b000  000000014002b000  00029600  2**4
                  CONTENTS, ALLOC, LOAD, DATA
  3 .eh_fram      00000040  000000014002c000  000000014002c000  00029800  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  4 .reloc        00000414  000000014002d000  000000014002d000  00029a00  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
```

**Comment by medhefgo** [comment] 2022-09-09 20:31
Also, right now nobody flags the .linux section as code, which is kinda incorrect on x86 as we execute it in place.
