### ISSUE TITLE
System freezes when systemd-binfmt is run and strace is attached to pid 1

### ISSUE THREAD

**Issue by rfinnie** [systemd/systemd#32132] opened 2024-04-06 18:30 UTC
### systemd version the issue has been seen with

255.4-1

### Used distribution

Debian testing

### Linux kernel version used

6.6.15-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-binfmt

### Expected behaviour you didn't see

Normal execution/exit of systemd-binfmt

### Unexpected behaviour you saw

System freezes when systemd-binfmt is run

### Steps to reproduce the problem

Create /sbin/strace-init with:
```shell
#!/bin/sh

set -e
PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
strace -v -qq -yy -s 65535 -p $$ -f -e open,openat,execve -z -o /var/log/strace-init.trace &
sleep 3
exec /sbin/init
```

Boot system with `init=/sbin/strace-init`

Run `systemd-binfmt`

**Comment by rfinnie** [comment] 2024-04-06 18:30
Note that I have not been able to reproduce this when I manually run strace against pid 1, then run `systemd-binfmt`. I've only been able to see the freeze when a script is run as pid 1, runs strace against itself, then execs into `systemd`.

This is a regression -- in addition to seeing this in 255.4-1 (Debian 6.6.15-amd64), I've also seen it in 252.6-1 (6.1.0-6-amd64), but it worked previously with 250.3-2 (5.16.0-4-amd64).

Background here is I produce a LiveCD, and part of the release process is to arrange all the common boot files at the end of the ISO, for faster execution on a physical CD-ROM. This file list is gathered by doing a boot where strace is attached to pid 1. For now, I'm working around this by simply not having the boot process run `systemd-binfmt` on the gathering run. I'm also aware this very likely could be a kernel regression which manifests itself in `systemd-binfmt`.

**Comment by poettering** [comment] 2024-04-08 14:20
So, what precisely is it hanging on?

Why do you think systemd has anything to do with this?

Which binfmt.d/ drop-ins do you actually have in place? what if you delete them and readd them one by one?

The init replacement you put together is really weird, you fork off strace and then apparently sync on it with sleep? Yuck. strace has a -D switch for cases like this, i.e. just do `exec stace -D …` and you should be set.

**Comment by poettering** [comment] 2024-04-19 21:08
so, here's my edcuated guess: binfmt_misc is implemented via an autofs mount. your strace call analyzes all files that are opened. As side-effect it touches the autofs and hangs while blocking pid 1 from actually resolving it. After all, pid 1 actually is excluded from triggering the mount because its process group is marked for that when the autofs was set up. But since your strace runs before systemd initializes (which creates its own pgrp), it's not part of the same pgrp. hence deadlock where there is no deadlock without strace.

But anyway, this is not a systemd bug, nor a feature request, hence let's close this here.

If you can reproduce such a deadlock without strace it would be more interesting.

**Closed as completed by poettering** 2024-04-19 21:08 UTC
Labels: bug 🐛, needs-reporter-feedback ❓, binfmt
