### ISSUE TITLE
systemd-nspawn - connectivity to the external network (default networks)

### ISSUE THREAD

**Issue by LaKing** [systemd/systemd#4460] opened 2016-10-23 18:18 UTC
### Submission type
- [x] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

systemd 231
### Used distribution

Fedora 25 beta
### In case of bug report: Expected behaviour you didn't see

systemd-nspawn container created with --network-veth or --network-zone communicating to external networks, such as the internet or lan.
### In case of bug report: Unexpected behaviour you saw

State: degraded (configuring)
Destination Host Unreachable (or all packets lost)
### In case of bug report: Steps to reproduce the problem
- Install fedora 25 beta, add SSH key, Disable SELinux, install systemd-container
- Create .network file for the physical Ethernet device
- disable network, NetworkManager
- enable and start systemd-network
- create container rootfs

``` bash
dnf -y --releasever=25 --installroot=/b install dnf initscripts passwd rsyslog vim-minimal openssh-server openssh-clients dhclient chkconfig rootfiles policycoreutils fedora-repos fedora-release mc
```
- set root password for container
- enable systemd-networkd on the container

Here comes a step that appears to be necessary, as I was able to get a custom bridge config running after I figured out this step is necessary. As RFE, would be nice to mention this in the documentation "Masquerade on the firewall needs to be enabled". The IPForwarding option seems to have no effect.
- enable masquarade on firewalld

``` bash
firewall-cmd --add-masquerade
```
- start a container, login as root

``` bash
systemd-nspawn --boot -n -D /b
```
- ping something external, eg 8.8.8.8 .. 100% packet loss

``` bash
[root@b ~]# ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
From 169.254.252.51 icmp_seq=1 Destination Host Unreachable
From 169.254.252.51 icmp_seq=2 Destination Host Unreachable
From 169.254.252.51 icmp_seq=3 Destination Host Unreachable
```

Diagnostics on the container interface with networkctl

```
● 2: host0
       Link File: n/a
    Network File: /usr/lib/systemd/network/80-container-host0.network
            Type: ether
           State: degraded (configuring)
      HW Address: a2:ae:b2:6d:55:8d
         Address: 169.254.252.51
                  fe80::a0ae:b2ff:fe6d:558d
    Connected To: testbox on port ve-b

```

Diagnostics on the host interfaces

```
● 2: enp0s3
       Link File: /usr/lib/systemd/network/99-default.link
    Network File: /etc/systemd/network/10-lan.network
            Type: ether
           State: routable (configured)
            Path: pci-0000:00:03.0
          Driver: e1000
          Vendor: Intel Corporation
           Model: 82540EM Gigabit Ethernet Controller (PRO/1000 MT Desktop Adapter)
      HW Address: 08:00:27:cb:fb:71 (Cadmus Computer Systems)
         Address: 192.168.88.28
                  fe80::a00:27ff:fecb:fb71
         Gateway: 192.168.88.1 (Routerboard.com)
             DNS: 192.168.88.1

● 3: ve-b
       Link File: /usr/lib/systemd/network/99-default.link
    Network File: /usr/lib/systemd/network/80-container-ve.network
            Type: ether
           State: routable (configured)
          Driver: veth
      HW Address: a6:38:8f:f7:58:97
         Address: 10.0.0.1
                  10.0.0.17
                  169.254.188.19
                  fe80::a438:8fff:fef7:5897
    Connected To: b on port host0
```

A strange thing I see, is that the 169.254.0.0 network is not present when checking the route command.

```
[root@testbox lib]# ip route
default via 192.168.88.1 dev enp0s3  proto static 
default dev ve-b  proto static  scope link  metric 2048 
10.0.0.0/28 dev ve-b  proto kernel  scope link  src 10.0.0.1 
10.0.0.16/28 dev ve-b  proto kernel  scope link  src 10.0.0.17 
169.254.0.0/16 dev ve-b  proto kernel  scope link  src 169.254.188.19 
192.168.88.0/24 dev enp0s3  proto kernel  scope link  src 192.168.88.28 
[root@testbox lib]# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         gateway         0.0.0.0         UG    0      0        0 enp0s3
default         0.0.0.0         0.0.0.0         U     2048   0        0 ve-b
10.0.0.0        0.0.0.0         255.255.255.240 U     0      0        0 ve-b
10.0.0.16       0.0.0.0         255.255.255.240 U     0      0        0 ve-b
link-local      0.0.0.0         255.255.0.0     U     0      0        0 ve-b
192.168.88.0    0.0.0.0         255.255.255.0   U     0      0        0 enp0s3
```

Another test, with a network-zone. Ping has no response either.

```
systemd-nspawn --boot --network-zone=myzone -D /b
```

On the container

```
● 2: host0
       Link File: n/a
    Network File: /usr/lib/systemd/network/80-container-host0.network
            Type: ether
           State: degraded (configuring)
      HW Address: a2:ae:b2:6d:55:8d
         Address: 169.254.252.51
                  fe80::a0ae:b2ff:fe6d:558d
    Connected To: testbox on port vz-myzone

```

On the host

```
● 3: vb-b
       Link File: /usr/lib/systemd/network/99-default.link
    Network File: n/a
            Type: ether
           State: degraded (unmanaged)
          Driver: veth
      HW Address: a6:38:8f:f7:58:97
         Address: fe80::a438:8fff:fef7:5897

● 4: vz-myzone
       Link File: /usr/lib/systemd/network/99-default.link
    Network File: /usr/lib/systemd/network/80-container-vz.network
            Type: ether
           State: routable (configured)
          Driver: bridge
      HW Address: a6:38:8f:f7:58:97
         Address: 10.0.0.1
                  10.0.1.1
                  169.254.188.19
                  fe80::a438:8fff:fef7:5897
    Connected To: b on port host0

```

Not sure why, but vb-b got created - and is unmanaged?
Anyway, on the host:

```
[root@testbox ~]# ip route
default via 192.168.88.1 dev enp0s3  proto static 
default dev vz-myzone  proto static  scope link  metric 2048 
10.0.0.0/24 dev vz-myzone  proto kernel  scope link  src 10.0.0.1 
10.0.1.0/24 dev vz-myzone  proto kernel  scope link  src 10.0.1.1 
169.254.0.0/16 dev vz-myzone  proto kernel  scope link  src 169.254.188.19 
192.168.88.0/24 dev enp0s3  proto kernel  scope link  src 192.168.88.28 
[root@testbox ~]# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         gateway         0.0.0.0         UG    0      0        0 enp0s3
default         0.0.0.0         0.0.0.0         U     2048   0        0 vz-myzone
10.0.0.0        0.0.0.0         255.255.255.0   U     0      0        0 vz-myzone
10.0.1.0        0.0.0.0         255.255.255.0   U     0      0        0 vz-myzone
link-local      0.0.0.0         255.255.0.0     U     0      0        0 vz-myzone
192.168.88.0    0.0.0.0         255.255.255.0   U     0      0        0 enp0s3
```

I would assume this is normal behavior if the documentation wouldn't explicitly mention at both options, that "further connectivity to the external network" is granted. I didn't find a way to get external connectivity working, only with a custom bridge, and custom configs with static IPs for containers. The lan interface can be reached by the containers, but nothing further.

**Comment by poettering** [comment] 2016-10-24 10:29
My guess is that firewalld is the culprit here. Please consider disabling it.

If you use the zone mode, then you get a zone interface on the host side, plus a veth link towards the container, and that link is added to the bridge. You'll thus always see at least two interfaces there. IP will only be configured on the bridge iface however, the veth link will be up but not have IP configured (i.e. appear as "degraded" and "unmanaged").

**Comment by LaKing** [comment] 2016-10-24 13:37
It seems that systemd-nspawn does not create the 10.0.0.0 config that includes the gateway, if firewalld is running at the creation moment of the container. With firewalld stopped, the container gets created, and it has the 10.0.0.0 network as part of it.

```
● 2: host0
       Link File: n/a
    Network File: /usr/lib/systemd/network/80-container-host0.network
            Type: ether
           State: routable (configuring)
      HW Address: a2:ae:b2:6d:55:8d
         Address: 10.0.0.115
                  169.254.252.51
                  fe80::a0ae:b2ff:fe6d:558d
         Gateway: 10.0.0.1
             DNS: 192.168.88.1
       Time Zone: Europe/Budapest
    Connected To: testbox on port vz-myzone
```

It even sees the external router at the DNS. Once the container is created, firewalld can be started and if masquerade is added on firewalld, external communication works, as expected.

**Comment by poettering** [comment] 2016-10-24 15:02
I have no idea what firewalld is doing, but my recommendation would be not to use it... If you want to use it I can't really tell you what firewalld is doing there precisely, and what needs to be fixed to make it work. It's really not a bug we can help you with much upstream...

**Comment by keszybz** [comment] 2016-10-30 19:51
Yeah, firewall config is out of scope. If you reproduce this without firewalld being involved, we can reopen this.

**Closed as completed by keszybz** 2016-10-30 19:51 UTC
Labels: network, nspawn
