### ISSUE TITLE
default route for wireguard interface automatically set when allowedIPs contains ::/0 or 0.0.0.0/0 since v250

### ISSUE THREAD

**Issue by freswa** [systemd/systemd#21964] opened 2022-01-01 22:03 UTC
Last good version: `249.7`
First bad version: `250`

With `249.7` this file doesn't set a default route, with `250` it does.

`wg0.network` config file:
```
[Match]
Name=wg0

[Network]
Address = fd00:dead:beef::1/64
Address = 172.16.42.1/24
IPForward = yes

[Route]
Destination = 172.16.0.0/22
Gateway = 172.16.42.2

[Route]
Destination = 192.168.178.0/24
Gateway = 172.16.42.2

[Route]
Destination = 192.168.80.0/24
Gateway = 172.16.42.2

[Route]
Destination = 2a01:4f8:1c0c:80a0::/64
Gateway = fd00:dead:beef::2
```

**Comment by yuwata** [comment] 2022-01-02 05:08
Could you provide relevant .netdev file?

**Comment by yuwata** [comment] 2022-01-02 15:38
I guess, you have `AllowedIPs=0.0.0.0/0` or `AllowedIPs=::/0`. If so, please try to set `RouteTable=off` in [WireGuardPeer] or [WireGuard] section.

**Comment by freswa** [comment] 2022-01-02 20:09
netdev:
```
[NetDev]
Name = wg0
Kind = wireguard
MTUBytes = 1412

[WireGuard]
PrivateKey = yyy
ListenPort = 51820

[WireGuardPeer]
PublicKey = xxx
AllowedIPs = 0.0.0.0/0
AllowedIPs = ::/0
```

Indeed, `RouteTable = off` fixes the issue. Is this an intentional change in systemd 250?

**Comment by yuwata** [comment] 2022-01-02 20:29
Since v250, networkd creates routes to `AllowedIPs=` by default. But yeah, I think we should disable that for 0.0.0.0/0 or ::/0.

`wg-quick` does something more complicated and smart way to handle such case.

**Comment by yuwata** [comment] 2022-01-02 20:31
@zx2c4 Could you give me any suggestions?

**Comment by zx2c4** [comment] 2022-01-02 20:33
It might not be a bad idea to handle this the way `wg-quick` does. Either that, or handle it normally as is the case now, and expect people to set RouteTable=off who dont want it. Don't special case it to doing nothing, though.

**Comment by yuwata** [comment] 2022-01-02 21:35
@zx2c4 OK. Thanks.

**Comment by m29h** [comment] 2022-01-03 19:54
I think this is caused by pull #21553.
In my opinion the new behavior is terrible. I had also set AllowedIp=0.0.0.0/0 and this now created a default route to the wg interface (that had higher priority than my actual Ethernet default route that connects me to the internet). This made the wg network try to reach the wireguard peer through the default route that pointed back  to the wire guard netdev. This creates a black hole loop that brings the entire ipv4 network traffic to a stop. 

One of my arch linux headless machines lost network connectivity through this after a upgrade of systemd and reboot ☹️

At a bare minimum there should be a check made if the wire guard peers (public internet) ip address is itself in the created route to wg netdev to prevent making a black hole!

**Comment by zx2c4** [comment] 2022-01-03 23:14
Why is your allowedips 0.0.0.0/0? Are you sure a smaller subnet wouldn't be more appropriate? If you do need to allow everything, but don't want that to be reflected on the main routing table, use the RouteTable= option mentioned above.

**Comment by m29h** [comment] 2022-01-04 09:16
Setting "AllowedIps=0.0.0.0/0" is an example in the [Arch Linux wiki](https://wiki.archlinux.org/title/WireGuard) for the scenario: "systemd-networkd: routing all traffic over WireGuard / Peer B setup"

The upgrade to v250 introduces a breaking change to the behavior that leaves people with a setup derived from this above example with a "bricked" network config that has completely inoperative non-local ipv4 networking.
The reason is that for default routes one has to be (obviously) very careful to exclude the actual traffic going to the wireguard peer endpoint from the default route. In the above example this is done by setting a FirewallMark and having a seperate routing table 1000 for all the unmarked traffic that gets a default route to the wg0 netdev, while the remaining (i.e. wireguard packets to peer endpoint) go to the "main" table which default routes on the public internet. 

The problem is that the AllowedIPs=0.0.0.0/0 derived route "slammed" on top of the "main" routing table (and not the Table=1000). I agree that for "most users" the new behaviour is good, but not for the scenario above.

How about adding a check if the Wireguard Peer Endpoint IP address is contained in the AllowedIPs range and default RouteTable to off when that check triggers? One could additionally throw a warning on the systemd journal that RouteTable should be explicitly be set by the in the config.

**Comment by zx2c4** [comment] 2022-01-04 11:36
> by setting a FirewallMark and having a seperate routing table 1000

This is the wg-quick trick mentioned above.

> How about adding a check if the Wireguard Peer Endpoint IP address is contained in the AllowedIPs range and default RouteTable to

What you're suggesting isn't that default is "on" or "off" but a new state called "auto". I don't know whether the systemd-networkd designers want automagic in what's supposed to be an otherwise somewhat deterministic system, but in case they do want that, my suggestion would be to make "auto" mode set up wg-quick-style fwmarks in certain cases.

It's hard to do the right thing all the time though, so it may wind up being better off keeping the behavior as-is and updating the Arch wiki; people who want fancy policy routing can presumably do that on their own or using wg-quick.

**Comment by igo95862** [comment] 2022-01-04 15:38
I think new behavior is way worse. It automatically creates a black hole and kills your internet connection.

Old behavior at least did not nuke your connection. Routing all traffic was a bit tricky to setup but you could use `--interface` parameters of utilities like curl to check the connection.

**Comment by igo95862** [comment] 2022-01-04 15:48
> It's hard to do the right thing all the time though, so it may wind up being better off keeping the behavior as-is and updating the Arch wiki; people who want fancy policy routing can presumably do that on their own or using wg-quick.

I think the best option is not introducing connection breaking updates. Right now updating to 250 completely breaks existing setups which I don't think should be the case.

**Comment by zx2c4** [comment] 2022-01-04 15:49
As mentioned here already, @igo95862, you can set `RouteTable=off` to get the old behavior.

**Comment by igo95862** [comment] 2022-01-04 15:53
> As mentioned here already, @igo95862, you can set `RouteTable=off` to get the old behavior.

I saw that but it is still breaking non backward-compatible update that can take down servers and desktops down.

**Comment by igo95862** [comment] 2022-01-04 15:56
If you read the systemd 250 changelog there are not mentions that Wireguard configurations need to be updated or you will lose connection. I suspect a lot of people will unknowingly break their connection.

**Comment by zx2c4** [comment] 2022-01-04 15:57
> If you read the systemd 250 changelog there are not mentions

Sounds like you should update the changelog?

**Comment by zx2c4** [comment] 2022-01-04 15:58
FYI, there's a mailing list announcement here, in case you're interested: https://lists.zx2c4.com/pipermail/wireguard/2022-January/007403.html

**Comment by igo95862** [comment] 2022-01-04 18:36
I opened a reddit thread: https://www.reddit.com/r/archlinux/comments/rw1ak8/psa_if_you_used_systemdnetworkd_routing_all/?

**Comment by zx2c4** [comment] 2022-01-04 21:13
Good idea with Reddit. Stickied to /r/wireguard here: https://www.reddit.com/r/WireGuard/comments/rw4ufd/psa_systemdnetworkd_v250_adds_routes_from/

I think this should give us enough visibility that people can update their configs. This issue can probably be closed.

**Comment by cwegener** [comment] 2022-01-08 03:46
Lesson from the field:

I just found out that in order for the `RouteTable=off`  setting to take effect, a FULL restart of `systemd-networkd` is required!

I was pulling my hair out, doing continuous attempts of `networkctl reload && networkctl reconfigure wg0` ..... which has NO effect with regards to the `RouteTable=off` setting at all.

**Comment by igo95862** [comment] 2022-01-08 12:34
@yuwata I opened a pull request which should no longer add routes which have a CIDR mask of 0.

**Comment by igo95862** [comment] 2022-01-08 13:43
I propose adding a new value `auto` which will add all routes from `AllowedIPs` **except** unspecified ones. (i.e. ::/0 and 0.0.0.0/0) This value will be new default.

If someone wants to add the unspecified routes to main table they will be able to pass the current default `main`.

@zx2c4 What do you think?

**Comment by tomty89** [comment] 2022-01-08 13:47
Isn't this really about users should move all `[Route]` `Destination=` in the matched `.network` to `AllowedIPs=` in the corresponding `.netdev`?

**Comment by zx2c4** [comment] 2022-01-08 13:48
I'd be wary of anything that special cases routes. I mentioned this in https://github.com/systemd/systemd/issues/21964#issuecomment-1003771183.

It might be interesting to use wg-quick's fwmark trick if the endpoint falls within the routes or the like. But actually I think that for a system utility like systemd-networkd, which isn't really meant for interactive laptop usage, the existing behavior is fine and nothing further needs to be done.

Then we can say: if you want magic, use wg-quick; if you want a reliable deterministic network configuration system, use systemd-networkd. Seems straightforward enough.

Framed like that, RouteTable= is basically a syntactic shortcut more than anything fancy.

**Comment by zx2c4** [comment] 2022-01-08 13:54
> Isn't this really about users should move all `[Route]` `Destination=` in the matched `.network` to `AllowedIPs=` in the corresponding `.netdev`?

Actually, I'm not sure what happens when RouteTable!=off is combined with already existing .network routes. Probably we should warn in that case? @yuwata Do you know?

**Comment by igo95862** [comment] 2022-01-08 13:57
@zx2c4 Correct me if I am wrong but you don't think breaking users configurations is a regression that needs to be fixed?

**Comment by zx2c4** [comment] 2022-01-08 14:02
As far as I can recall, systemd has configuration-breaking releases from time to time, considered an unfortunate occasional necessity for progress.

But I might be wrong about that; I'm no policy expert. If I am wrong, then I'd think the way forward would be to just revert the whole feature and release a patch ASAP, and then we can go back to the drawing board to evaluate this, including why @yuwata thought we should have it.

However, I really do suspect that occasionally breaking configuration file behavior is one of those accepted systemd growing pains. (Leadership: feel free to shout me down if I'm wrong.)

**Comment by igo95862** [comment] 2022-01-08 14:19
@poettering @keszybz Would you mind making a statement on regression policy?

**Comment by DasSkelett** [comment] 2022-01-08 15:23
I for one don't care how `RouteTable` behaves when turned on, but I do care a lot about it being disabled by default.
This automatic route manipulation is unexpected _for networkd_, it does not follow the principle of least surprise.
systemd-networkd doesn't behave like this in other places, at least in my experience.

If I want routes to an interface, I configure those routes for the interface; the same way as for any other interface: in its .network file using `[Route]` blocks.

**Comment by zx2c4** [comment] 2022-01-08 15:30
That would be one outcome. I suspect, though, if this becomes a question about defaults, we should probably go back to the drawing board and reevaluate the whole feature, its intended semantics and use case, and who it's for. @yuwata sent the PR and then it got merged pretty soon after, without a whole lot of discussion. (And at the same time as that one, there was another somewhat related PR that I thought really, really needed more discussion, and felt like I had to make a small amount of noise in order to slow that process down.)

Anyway, I guess the question, when evaluating the feature at large (and by extension what the sensible defaults are related to the feature) are when one of the routing tables ever should _not_ contain the union of all AllowedIPs? What are the network configurations that make sense for that? If the answer is, "none of them" or "only very rare ones", then probably things are fine as-is and we don't need to change anything. If the answer is, "most of them", then there's probably no point in even having this feature. I'm pretty sure the answer is *not* "most of them," however.

**Comment by flokli** [comment] 2022-01-08 15:43
I use wireguard mostly in a "one server, multiple roadwarriors" setup. All peers have addresses in a /24, and only know the pubkey of the server. The server takes care of routing lateral traffic (and the /24 netmask takes care of configuring the route)

I still set AllowedIPs to 0.0.0.0/0, so that i can explicitly configure some more specific routes for some IPs on the internet on demand. Let's say redirecting 1.1.1.1 if my current connection does do funky things with DNS.

**Comment by zx2c4** [comment] 2022-01-08 15:45
In that case, wouldn't you be better off having your allowedips match your routing table? This way the server can't forward you packets you weren't expecting? Or do you _also_ configure things to have a (non-default) strong host model?

**Comment by flokli** [comment] 2022-01-08 16:03
Those routes are configured much more dynamically. Think of running a dynamic routing protocol through that link.

On top of that, there's a distinction between what source addresses can originate from a tunnel, and what is currently configured in the routing table.

Think of having multiple independent wireguard tunnels to different "upstream providers". You might still want to accept packets from the less optimal path, even though you don't have a route to it.

**Comment by tomty89** [comment] 2022-01-08 16:04
> I for one don't care how `RouteTable` behaves when turned on, but I do care a lot about it being disabled by default. This automatic route manipulation is unexpected _for networkd_, it does not follow the principle of least surprise. systemd-networkd doesn't behave like this in other places, at least in my experience.
> 
> If I want routes to an interface, I configure those routes for the interface; the same way as for any other interface: in its .network file using `[Route]` blocks.

Perhaps it should work the other way round: all `[Route]` `Destination=` are added to the internal list of allowed IPs without the need of manual specification, with `RouteTable=off` by default.

**Comment by zx2c4** [comment] 2022-01-08 16:08
@flokli 

> On top of that, there's a distinction between what source addresses can originate from a tunnel, and what is currently configured in the routing table.

Yes, I realize that what you've described is such a distinction, which is why I asked you _why_ you would want such a distinction. For most use cases you want these to be the same

> Think of having multiple independent wireguard tunnels to different "upstream providers". You might still want to accept packets from the less optimal path, even though you don't have a route to it.
> Those routes are configured much more dynamically. Think of running a dynamic routing protocol through that link.

Right, so the non-WG aware routing daemon use case is one place where certainly people are disabling allowedips and having one peer per interface (at least until @tohojo finishes adding support for allowedips to bird!).

It seems reasonable to assume that, "interoperating with non-WG-aware routing daemons" is one of those rare special cases why somebody would want `RoutingTable=off` for a configuration. Point taken there. But, as said, it also seems to be rare and special, right?

**Comment by zx2c4** [comment] 2022-01-08 16:09
> Perhaps it should work the other way round: all `[Route]` `Destination=` are added to the internal list of allowed IPs without the need of manual specification, with `RouteTable=off` by default.

Yikes, please no. AllowedIPs is a security concept. Don't infer data for security concepts from routing concepts. That directionality is sure to end in tears at some point.

**Comment by flokli** [comment] 2022-01-08 16:30
So we agree there's a distinction between routing and security concepts :-)

It might make sense to handle those very similarly for wg-quick, but having networkd flip defaults over night, and suddenly adding routing table entries for AllowedIP entries is a possibly breaking change.

There's some prior art on not breaking existing configs, how sandboxing features in systemd are handled. I need to dig out some links, but I'd assume this falls under the same "don't break existing configs" guarantee. We can have that as an opt-in, but flipping the default is wrong.

**Comment by tomty89** [comment] 2022-01-08 16:30
> > Perhaps it should work the other way round: all `[Route]` `Destination=` are added to the internal list of allowed IPs without the need of manual specification, with `RouteTable=off` by default.
> 
> Yikes, please no. AllowedIPs is a security concept. Don't infer data for security concepts from routing concepts. That directionality is sure to end in tears at some point.

Yes, conceptually-speaking, it might sound bad. But apparently in reality, when this "concept separation for security" is applied on networkd, it merely led (some of the) users (that are lazy, or ignorant, if I may say so) to simply abuse `AllowedIPs=0.0.0.0`...

I don't know if there's some black magic special case in which "not-allowed routes" could actually make sense, but at least if it centralize the configuration to `.network` and makes (the abuse of) `AllowedIPs=` optional, I'd say it has its security pros...

**Comment by zx2c4** [comment] 2022-01-08 16:48
> So we agree there's a distinction between routing and security concepts :-)

Yes, sure. WireGuard smushes them together with its "cryptokey routing" idea, realized by AllowedIPs. My point is that there's mostly a 1:1 relationship between the two, and the source of truth there should originate from AllowedIPs, since that's explicitly security related, whereas willynilly routing mentions are not. I have no interest at all in pursuing anything related to @tomty89's terrible suggestion to have AllowedIPs inferred by network routes. But for the purposes of our (@flokli and myself) discussion here, indeed the distinction also plays a part.

> It might make sense to handle those very similarly for wg-quick, but having networkd flip defaults over night, and suddenly adding routing table entries for AllowedIP entries is a possibly breaking change.
> 
> There's some prior art on not breaking existing configs, how sandboxing features in systemd are handled. I need to dig out some links, but I'd assume this falls under the same "don't break existing configs" guarantee. We can have that as an opt-in, but flipping the default is wrong.

This sounds like a fair argument to me, if the policy matter _truly_ is "don't break existing configs no matter what." Of course, all of the people on this bug report (except, perhaps, you) are complaining because their Arch-wiki recipe no longer works, without realizing that that Arch wiki recipe could become _simpler_ by using `RouteTable=secondarything`. Simplifying that sort of recipe seems like it'd be a win for those users, even if today they're complaining. And most server users, who have a few statically defined WG peers defined, may well benefit from this.

*BUT*, if indeed we really _can never ever break configurations, even unusual fwmark ones_, then I think the thing to do would be to revert the feature as a whole. There's already a way to explicitly opt-in to making various routes (.network files). Why add a second way? The appeal of `RouteTable=` is that it provides an automatic thing that's already on by default helping the use cases of _most users_, in particular server users, of systemd-networkd. Once it becomes non-default, then it's just another confusing knob that people will mix up.

----

A counterargument to what I wrote above regarding server use cases is actually the situation you described on your server side. That wasn't the point of your post -- you were focused on the client -- but it does seem like a relevant configuration to consider.  Specifically, the server has multiple peers, each WG peer owning a /32 in AllowedIPs, with the interface itself owning the routing table route of a /24. This makes sense, and is something you get with the standard boring .netdev/.network duality. With `RouteTable=`, all of the sudden, instead of a single /24 route, you might wind up with 253 /32 routes.  Is that really want any server users want?

So, understood _that way_, maybe this isn't actually very useful for server users either. wg-quick does not suffer from this problem, as it does a route inclusion check before adding automatic routes (`[[ -n $(ip $proto route show dev "$INTERFACE" match "$1" 2>/dev/null) ]] || cmd ip $proto route add "$1" dev "$INTERFACE"`), so if your `Address=` entry has a /24 in it, you won't get all those extra routes.

But that means that in order to make this feature useful for server use cases, we'll probably need some more magical logic in systemd-netword. And, as already mentioned above, in order to make this feature useful for the client use cases, we'll certainly need some more magical logic in systemd-networkd (fwmark magic for the 0.0.0.0/0 route and things like that). Sounds like a lot of magic is required for this to be useful.

So, as is, the feature fails to be useful for both the most common client use case and the most common server use case. In which case, maybe we should just revert this feature until it's more thought out and comes with a more compelling PR summary from @yuwata that isn't rushed through two weeks before a version is cut?

**Comment by tohojo** [comment] 2022-01-08 17:11
Right, so since I got tagged in this, I figured I'd weight in as well :)

I happen to also have been hit by this. I have multiple wg interfaces with ::/0 in allowedIps on my main router (and generally a fairly bespoke routing setup :)), and after updating systemd, my network broke. While I generally think "don't break users on upgrade" is a good ambition to have, my experience with systemd in the past has taught me that it is not one I can count on for this particular package. So I was prepared for things to break, and it was a fairly simple fix to disable the (useless, to me) feature after that; so from that PoV I think the main failing was that this wasn't mentioned in the release notes (which it definitely should have been!).

I didn't think much of the change, as I recognised it corresponding to wg-quick which I think makes sense; so in that respect I can understand why this should be a default. However if, as @zx2c4 points out above, the feature is in fact not useful at all, well, that's certainly another matter...

As for reverting, there does exist a stable repo, and I know at least Arch packaging pulls from there: https://github.com/systemd/systemd-stable - but I'm not sure if it makes sense at this point? I mean, it's already in a released version, so people will already have been hit by the breakage. If they just disabled the new feature (like I did) a revert in a point release is benign, but if someone adjusts their config to actually make use of the feature, a revert will just introduce another breakage. So from that PoV, the time to revert would have been before the release happened, and now all we can do is learn from the mistake, and maybe fix the feature to actualy be useful (with the "magic" mentioned above)?

**Comment by flokli** [comment] 2022-01-08 17:34
@zx2c4 @tohojo `systemd-stable` contains cherry-picks from the `master` branch and pushes `xxx.x` tags. So far, this were mostly bugfixes.

I did raise some concerns on properly designing this, taking network namespaces into account. That happened in https://github.com/systemd/systemd/issues/14176#issuecomment-748666657. Rushing this in shortly before the release was cut probably wasn't a good idea, and I would have really appreciated if some more opinions were collected (which might have revealed some of the shortsights in https://github.com/systemd/systemd/issues/21964#issuecomment-1008057529)

I'm not sure how to best fix this now, and whether pushing a revert in a patch release is the right way to do it or not.

As already mentioned, it already broke some setups (and people applied the "migitation" of disabling the feature), but considering not too many distros already upgraded to 250, and started making use of the feature, a revert might be possible. After all, "undoing" the config won't be too much work (the previous static `AllowedIP` lines would need to be re-added, if they were already removed consciously, and nothing would change for people not using that feature so far).

In any case, I still think a proper design phase, taking network namespaces into account is needed at some point.

**Comment by zx2c4** [comment] 2022-01-09 16:07
Alright, then, seems like consensus is clearly against this stuff until it receives more discussion. I submitted https://github.com/systemd/systemd/pull/22065 which hopefully can be backported to stable soon. I also noticed some other rushed stuff in there I wasn't even CC'd on that was snuck in there just before v250 was released. Leaves a sour taste.

**Comment by yuwata** [comment] 2022-01-11 06:07
Sorry for late response. I was AFK last few days. Now I am reading this thread.

**Comment by yuwata** [comment] 2022-01-11 06:52
https://github.com/systemd/systemd/issues/21964#issuecomment-1008001452
> As far as I can recall, systemd has configuration-breaking releases from time to time, considered an unfortunate occasional necessity for progress.

Yeah, unfortunately...

https://github.com/systemd/systemd/issues/21964#issuecomment-1008025927
>  (And at the same time as that one, there was another somewhat related PR that I thought really, really needed more discussion, and felt like I had to make a small amount of noise in order to slow that process down.)

Thank you for stopping the PR to be merged soon.

https://github.com/systemd/systemd/issues/21964#issuecomment-1008067422
> As for reverting, (snip) I'm not sure if it makes sense at this point? I mean, it's already in a released version, so people will already have been hit by the breakage. If they just disabled the new feature (like I did) a revert in a point release is benign, but if someone adjusts their config to actually make use of the feature, a revert will just introduce another breakage. So from that PoV, the time to revert would have been before the release happened, and now all we can do is learn from the mistake, and maybe fix the feature to actualy be useful (with the "magic" mentioned above)?

Right. Unfortunately, the feature is already released. We cannot simply revert it.

------------

Again, unfortunately backward incompatibility is broken sometimes, to introduce new features. Of course, it should not happen so frequently. And, because of that, we should not simply revert the feature.

Here, there are at least two issues (except for the default change).
1. as originally reported, we should not add route for 0.0.0.0/0 and ::/0.
2. if e.g. a /32 AllowedIP= is configured, and /24 route is already configured in a .network file, then we should skip to add /32 route.

These can be 'easily' fixed I think, and their fix can be backported to -stable repo. Are there any other issues we need to fix?

**Comment by zx2c4** [comment] 2022-01-11 08:59
> Are there any other issues we need to fix?

Yes. And I'm not really up for rushing into solutions AGAIN here. Just revert the mess made by rushing this in the first place. After that, we can take our time properly designing a nice feature. This is not a matter of some slapdash bug fixes.

The sooner you merge the revert, the sooner distros can backport it from 250.y stable. I might start sending the reverts downstream in the meantime too.

I'll wait for you to merge https://github.com/systemd/systemd/pull/22065 before engaging further, I don't think designing features from a broken and rushed position is an okay path forward.

**Comment by yuwata** [comment] 2022-01-11 09:09
> > Are there any other issues we need to fix?
> 
> Yes.

Could you list them? I read this thread, but maybe I missed some of them.

**Comment by yuwata** [comment] 2022-01-11 09:16
@zx2c4
> I don't think designing features from a broken and rushed position is an okay path forward.

Could you explain a 'proper design' you think? I understand current implementation has several issues, but I am not sure about this comes from the current 'design'.

**Comment by igo95862** [comment] 2022-01-11 11:08
IIRC systemd unit parser will ignore unknown fields and only emit warning so removing `RouteTable=` should not really break systems that had set it to `RouteTable=off`

**Comment by yuwata** [comment] 2022-01-11 11:09
> IIRC systemd unit parser will ignore unknown fields and only emit warning so removing `RouteTable=` should not really break systems that had set it to `RouteTable=off`

Right.

**Comment by yuwata** [comment] 2022-01-11 11:15
> @zx2c4
> 
> > I don't think designing features from a broken and rushed position is an okay path forward.
> 
> Could you explain a 'proper design' you think? I understand current implementation has several issues, but I am not sure about this comes from the current 'design'.

I mean, if the expected design you think is completely far from the current one, then it is OK to revert my PR. But, if it is not, then why not to fix the current issues? At least, I do not catch anything about failures in the current design, and the basic concept looks similar to what wg-quick does for me. If I just missed, then please let me know.

**Comment by zx2c4** [comment] 2022-01-12 15:25
@yuwata I'm still waiting for you to merge that revert. Then we can go back to the drawing board to figure out how this "feature" should work, if it's even something we want at all.

This is *not* a matter of a few slapdash bug fixes, as I mentioned earlier. And I don't appreciate the hostage taking with respect to pressuring the discussion on the matter to resolve *NOW* with a list of things sent to you *NOW*. That's not a way that we're going to arrive at a nicely designed feature.

Please merge the revert, and then we'll talk. You can submit your PR again, and I'm sure folks will chime in this time around, including myself. You'll simply have to be patient and not post it a week before v251 is released.

**Comment by bluca** [comment] 2022-01-12 15:49
@zx2c4 whether it's intentional or not, these last messages are coming off as unnecessarily aggressive - please knock it down a notch or two, this is all just some weird math running on a funny-looking pieces of sand and plastic

**Comment by zx2c4** [comment] 2022-01-12 17:29
- It's not clear whether this belongs in .netdev vs .network (push vs pull).
- It's not clear _who_ actually benefits from this feature at the moment and how common those users are.
- There are issues if you're a server with multiple peers.
- There are issues if you're a client with a default route.
- It's not clear exactly _how much of_ `wg-quick(8)`-style logic that systemd-networkd should inherit, and how much of that is much too magical and violates a principle of least surprise.
- There are lingering concerns with namespaces.
- Multiple people have raised conceptual issues and seemingly would like to be part of larger design discussions on how this is supposed to work.
- Configuration semantics in something like systemd-networkd greatly influence how people conceptualize wireguard and how it's deployed. That means we need to think carefully about each thing we add.
- It's not even clear whether this feature should exist in the first place.

None of this stuff is going to get done for your options (2) and (3). It's only through taking our time slowly, engaging with community members, and thinking this through thoroughly that we'll reach a good model. None of that is going to happen while we're still under the time pressure of _everyday people are running the broken code_. The revert needs to be applied yesterday, so that we can get this downstream, not have more breakage, and then be able to properly take our time doing this right. Your options (2) and (3) will likely result in more rushed decisions and half baked features.

And don't get me wrong: I entered this thread of the mind that the feature was basically fine and at most needed a tweak here or there. But after listening to folks voice their concerns and thinking through what practical use cases actually are, I've arrived at the conclusion that we're not going to simply bandaid over this quickly.

Every one of those bullet points requires careful discussion. And every day that we're discussing it, users with v250 are learning the wrong way of doing things and borking their configs. We don't have the _time_ to work things out _now_. Rather, we can revert. And once that's done, then we'll have all the time in the world to talk about these important matters.

And while @bluca considers this comment of mine aggressive:

> And I don't appreciate the hostage taking with respect to pressuring the discussion on the matter to resolve _NOW_ with a list of things sent to you _NOW_.

, I consider it really just a matter of practicality. We need to back out the changes of v250 before it's too late. By you insisting on re-designing or fixing the feature _before_ then, you force me to devote all of my time to systemd-networkd discussions _now_, rather than working on this gradually in accordance with how volunteer work usually goes. The only pressing thing is getting the revert out to users on v250. Nothing else is pressing and can be done gradually over time with good discussion.

**Comment by zotanmew** [comment] 2022-01-15 15:30
This just broke my entire routing setup as this breaks connectivity of every node using BGP over wireguard, which requires ::/0 allowedips. I like this behavior in general, but making it opt-out instead of opt-in is breaking systems to an unacceptable degree.

**Comment by zx2c4** [comment] 2022-01-15 15:31
Indeed my inbox is lit up with folks like you who have been hit by this. I don't know why @yuwata hasn't merged the revert yet. Every day this remains the problem gets worse.

**Closed as completed** 2022-01-16 14:04 UTC
Labels: network

**Comment by zx2c4** [comment] 2022-01-16 14:57
Looks like you didn't merge the revert. That's extremely disappointing, especially given how little you've engaged here and how much effort has been expended by myself and others into looking at this situation.

Needless to say, I won't be working further with @yuwata until this matter is rectified. You've burned a lot of goodwill.

**Comment by zx2c4** [comment] 2022-01-16 14:59
CC @poettering

**Comment by keszybz** [comment] 2022-01-18 09:33
> I really do suspect that occasionally breaking configuration file behavior is one of those accepted systemd growing pains.

This was briefly answered by Yu above, but I'll expand a bit: we avoid breaking existing setups. This is the general rule and we follow it almost always. Nevertheless, there *are* cases where we do this, and usually that's when we cannot figure out a way to change things without some breakage somewhere. A case like this is when we redefine/split/clarify semantics of some early boot targets: in those cases *any* change of the ordering is going to break somebody's bespoke setup, but we can't predict or avoid that. There are other such cases where we decide that fixing some existing behaviour to make things generally sane is worth the breakage for some use cases. If the negative impact is noticed, we'll describe this in NEWS and only do the change in before a -rc1 release.

> Looks like you didn't merge the revert.

As described above, once a feature has been released, we assume *some* people are making use of it and can't just rip it out. With the revert of the default in #22136, there is no harm in the feature and we can do follow-up changes without undue hurry. (Unless you think that there's still breakage to existing setups with #22136 merged. But I haven't seen any mention of this so far.)

I'll close #22065 now.

**Comment by keszybz** [comment] 2022-01-18 11:59
#22136 has been backported to v250.3 now in.

**Comment by yuwata** [comment] 2022-01-18 12:34
@zx2c4 Please do not get angry with our decision, and please understand our basic rule described in the above.
I feel sorry about that you feel your time is wasted. Actually, in a short time period, sometimes discussions and answering questions may look as a waste of time, especially for authorities. But it is not, especially for long time period. And unfortunately, your explanations are not sufficient for answering my questions in the above.

As mentioned in my follow-up PR #22136, there is an open room for fixing and improving the feature. Any suggestions are always welcome.

------

For all participants and audiences in this thread, I feel sorry that v250 was initially released with such an incomplete feature. As @keszybz commented in the above, now #22136 is backported to v250-stable repository, and I hope a point release with the backport will be distributed to your machine soon. And, I hope all previously worked .netdev files for WireGuard will work again without any modification. If it does not work for you, then please open a new issue page with debugging logs. Thank you.

**Comment by zx2c4** [comment] 2022-01-18 12:45
@yuwata The issue is that you did not engage or even discuss before moving ahead. It's insulting. Had you explained your rationale, engaged with the discussion here, and then made a decision, it'd be a different situation. Instead you just moved ahead with it on a Sunday, disregarding what I'd written. It doesn't send a nice message and leaves a _very_ sour taste in my mouth. Good luck.

**Comment by yuwata** [comment] 2022-01-18 14:14
@zx2c4 Please provide concrete logic for what we should do and join constructive discussion, rather than such strong words.

The main issue here is previous working .netdev files for WireGuard do not work with v250. And the issue can be fixed without reverting the whole feature, as I wrote several times here and also in #22136. This logic should be pretty simple and clear, no?

Again, any suggestions for redesigning or improving the feature are always welcome.

**Comment by zx2c4** [comment] 2022-01-18 14:27
The comment to have replied to before moving ahead without conversation was https://github.com/systemd/systemd/issues/21964#issuecomment-1011285491 . You ignored this and closed this issue. That slight is the problem. I've gone above and beyond in providing constructive conversation. Maybe you should re-read this thread. There's tons of analysis and discussion from multiple people. That you've just tried to reverse the matter in your last comment is striking to me, and just gives me more motivation to never attempt to work with you again.

**Comment by yuwata** [comment] 2022-01-18 14:54
@zx2c4 First of all, you may doubt about that, but I feel thankful about the whole discussion in this thread, and I've recognized there exists multiple issues in the new feature. Also, your help in other PRs are much appreciated. That's very true.

But in this thread, there exists a missing link between 'the feature is useless and harmful' and 'the feature should be reverted' in your comments. That is, why we need to revert it rather than fixing it, which is I repeatedly asked in the above. As we already said several times, we do not usually revert a feature which is already released. So, if you want to push that your opinion, then you need to provide a concrete logic for that.

**Comment by zx2c4** [comment] 2022-01-18 15:00
Please don't try to pretend retroactively like you were actually engaged in this discussion. You made the call that you did _without_ engaging. Here's a photo of the end sequence:

![image](https://user-images.githubusercontent.com/10643/149961632-d55eef46-35bd-4864-b25e-63787ca0273a.png)

> So, if you want to push that your opinion, then you need to provide a concrete logic for that.

I defer again to https://github.com/systemd/systemd/issues/21964#issuecomment-1011285491 which you still haven't replied to.

But it's clear that you're not arguing here in good faith, but just trying to save face. I'm not convinced systemd-networkd really has a promising future with you making decisions and running things how you are. I'll just move along. Good luck with your future endeavors here.

**Comment by bluca** [comment] 2022-01-18 15:19
This is quite enough - we can endure some level of condescending, but straight up toxicity is not welcome. One warning was given, now it's time to stop posting.
