### ISSUE TITLE
resolvectl query 10.111.113.2 now takes ~ 7 seconds

### ISSUE THREAD

**Issue by jelly** [systemd/systemd#26620] opened 2023-02-28 16:55 UTC
### systemd version the issue has been seen with

253

### Used distribution

Arch Linux

### Linux kernel version used

6.1.12-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

After upgrading systemd (252.5-1 -> 253-1) `cockpit-ssh` now takes 7 seconds to connect to another host. We managed to boil down the issue to `resolvectl query 10.111.113.2` taking 7 seconds. I bisected this issue to e31540196b8fb136a8f197c7a26d851bd0b93329

```
[root@archlinux ~]# time resolvectl query 10.111.113.2
10.111.113.2: resolve call failed: All attempts to contact name servers or networks failed

real    0m7.635s
user    0m0.007s
sys     0m0.008s
```

Full reference https://github.com/cockpit-project/bots/pull/4446#issuecomment-1447782375

### Steps to reproduce the problem

This can be rather tricky, we setup two virtual machines and manually set the interfaces to 10.111.113.1 and the other VM to 10.111.113.2 with both virtual machines having their "internet" disabled.

My coworker's further debugging conclusions of the issue https://github.com/cockpit-project/bots/pull/4446#issuecomment-1447782375

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
systemd-resolved debug logs

Registering bus object implementation for path=/org/freedesktop/resolve1/dnssd iface=org.freedesktop.resolve1.DnssdService
Registering bus object implementation for path=/org/freedesktop/LogControl1 iface=org.freedesktop.LogControl1
Creating stub listener using UDP/TCP.
Switching to system DNS server 127.0.0.1.
Bus bus-api-resolve: changing state AUTHENTICATING → HELLO
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RequestName cookie=2 reply_cookie=0 signature=su error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=3 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.170 path=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 signature=s error-name=n/a error-message=n/a
Bus bus-api-resolve: changing state HELLO → RUNNING
Got message type=signal sender=org.freedesktop.DBus.Local destination=n/a path=/org/freedesktop/DBus/Local interface=org.freedesktop.DBus.Local member=Connected cookie=4294967295 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Got message type=signal sender=org.freedesktop.DBus destination=:1.170 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired cookie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=signal sender=org.freedesktop.DBus destination=:1.170 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired cookie=3 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.170 path=n/a interface=n/a member=n/a cookie=4 reply_cookie=2 signature=u error-name=n/a error-message=n/a
Successfully acquired requested service name.
Got message type=method_call sender=:1.6 destination=:1.170 path=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=SetLinkDomains cookie=548 reply_cookie=0 signature=ia(sb) error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixUser cookie=4 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.170 path=n/a interface=n/a member=n/a cookie=6 reply_cookie=4 signature=u error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixProcessID cookie=5 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.170 path=n/a interface=n/a member=n/a cookie=7 reply_cookie=5 signature=u error-name=n/a error-message=n/a
D-Bus dns domains change request from client PID 309 (NetworkManager) with UID 0
Sent message type=method_return sender=n/a destination=:1.6 path=n/a interface=n/a member=n/a cookie=6 reply_cookie=548 signature=n/a error-name=n/a error-message=n/a
Got message type=method_call sender=:1.6 destination=:1.170 path=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=SetLinkDefaultRoute cookie=549 reply_cookie=0 signature=ib error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixUser cookie=7 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.170 path=n/a interface=n/a member=n/a cookie=8 reply_cookie=7 signature=u error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixProcessID cookie=8 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.170 path=n/a interface=n/a member=n/a cookie=9 reply_cookie=8 signature=u error-name=n/a error-message=n/a
D-Bus dns default route change request from client PID 309 (NetworkManager) with UID 0
Sent message type=method_return sender=n/a destination=:1.6 path=n/a interface=n/a member=n/a cookie=9 reply_cookie=549 signature=n/a error-name=n/a error-message=n/a
Got message type=method_call sender=:1.6 destination=:1.170 path=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=SetLinkMulticastDNS cookie=550 reply_cookie=0 signature=is error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixUser cookie=10 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.170 path=n/a interface=n/a member=n/a cookie=10 reply_cookie=10 signature=u error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixProcessID cookie=11 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.170 path=n/a interface=n/a member=n/a cookie=11 reply_cookie=11 signature=u error-name=n/a error-message=n/a
D-Bus mDNS change request from client PID 309 (NetworkManager) with UID 0
Sent message type=method_return sender=n/a destination=:1.6 path=n/a interface=n/a member=n/a cookie=12 reply_cookie=550 signature=n/a error-name=n/a error-message=n/a
Got message type=method_call sender=:1.6 destination=:1.170 path=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=SetLinkLLMNR cookie=551 reply_cookie=0 signature=is error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixUser cookie=13 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.170 path=n/a interface=n/a member=n/a cookie=12 reply_cookie=13 signature=u error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixProcessID cookie=14 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.170 path=n/a interface=n/a member=n/a cookie=13 reply_cookie=14 signature=u error-name=n/a error-message=n/a
D-Bus LLMNR change request from client PID 309 (NetworkManager) with UID 0
Sent message type=method_return sender=n/a destination=:1.6 path=n/a interface=n/a member=n/a cookie=15 reply_cookie=551 signature=n/a error-name=n/a error-message=n/a
Initial jitter phase for transaction 24681 elapsed.
Retrying transaction 24681.
Firing regular transaction 24681 for <archlinux IN ANY> scope llmnr on eth1/INET (validate=yes).
Sending query packet with id 24681 on interface 3/AF_INET of size 27.
Got message type=method_call sender=:1.6 destination=:1.170 path=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=SetLinkDNS cookie=552 reply_cookie=0 signature=ia(iay) error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixUser cookie=16 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.170 path=n/a interface=n/a member=n/a cookie=14 reply_cookie=16 signature=u error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixProcessID cookie=17 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.170 path=n/a interface=n/a member=n/a cookie=15 reply_cookie=17 signature=u error-name=n/a error-message=n/a
D-Bus DNS server change request from client PID 309 (NetworkManager) with UID 0
Sent message type=method_return sender=n/a destination=:1.6 path=n/a interface=n/a member=n/a cookie=18 reply_cookie=552 signature=n/a error-name=n/a error-message=n/a
Got message type=method_call sender=:1.6 destination=:1.170 path=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=SetLinkDNSOverTLS cookie=553 reply_cookie=0 signature=is error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixUser cookie=19 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.170 path=n/a interface=n/a member=n/a cookie=16 reply_cookie=19 signature=u error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixProcessID cookie=20 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.170 path=n/a interface=n/a member=n/a cookie=17 reply_cookie=20 signature=u error-name=n/a error-message=n/a
D-Bus D-o-T change request from client PID 309 (NetworkManager) with UID 0
Sent message type=method_return sender=n/a destination=:1.6 path=n/a interface=n/a member=n/a cookie=21 reply_cookie=553 signature=n/a error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.170 path=n/a interface=n/a member=n/a cookie=5 reply_cookie=3 signature=n/a error-name=n/a error-message=n/a
Match type='signal',sender='org.freedesktop.login1',path='/org/freedesktop/login1',interface='org.freedesktop.login1.Manager',member='PrepareForSleep' successfully installed.
Initial jitter phase for transaction 51910 elapsed.
Retrying transaction 51910.
Firing regular transaction 51910 for <archlinux.local IN ANY> scope mdns on eth1/INET (validate=yes).
Sending query packet with id 0 on interface 3/AF_INET of size 49.
Initial jitter phase for transaction 43768 elapsed.
Retrying transaction 43768.
Firing regular transaction 43768 for <archlinux IN ANY> scope llmnr on eth0/INET6 (validate=yes).
Sending query packet with id 43768 on interface 2/AF_INET6 of size 27.
Timeout reached on transaction 51910.
Retrying transaction 51910.
Firing regular transaction 51910 for <archlinux.local IN ANY> scope mdns on eth1/INET (validate=yes).
Sending query packet with id 0 on interface 3/AF_INET of size 49.
Initial jitter phase for transaction 37613 elapsed.
Retrying transaction 37613.
Firing regular transaction 37613 for <archlinux.local IN ANY> scope mdns on eth1/INET6 (validate=yes).
Sending query packet with id 0 on interface 3/AF_INET6 of size 61.
Timeout reached on transaction 24681.
Retrying transaction 24681.
Firing regular transaction 24681 for <archlinux IN ANY> scope llmnr on eth1/INET (validate=yes).
Sending query packet with id 24681 on interface 3/AF_INET of size 27.
Initial jitter phase for transaction 9007 elapsed.
Retrying transaction 9007.
Firing regular transaction 9007 for <archlinux IN ANY> scope llmnr on eth0/INET (validate=yes).
Sending query packet with id 9007 on interface 2/AF_INET of size 27.
Initial jitter phase for transaction 40595 elapsed.
Retrying transaction 40595.
Firing regular transaction 40595 for <archlinux IN ANY> scope llmnr on eth1/INET6 (validate=yes).
Sending query packet with id 40595 on interface 3/AF_INET6 of size 27.
Timeout reached on transaction 43768.
Retrying transaction 43768.
Firing regular transaction 43768 for <archlinux IN ANY> scope llmnr on eth0/INET6 (validate=yes).
Sending query packet with id 43768 on interface 2/AF_INET6 of size 27.
Timeout reached on transaction 24681.
Retrying transaction 24681.
Firing regular transaction 24681 for <archlinux IN ANY> scope llmnr on eth1/INET (validate=yes).
Sending query packet with id 24681 on interface 3/AF_INET of size 27.
Timeout reached on transaction 9007.
Retrying transaction 9007.
Firing regular transaction 9007 for <archlinux IN ANY> scope llmnr on eth0/INET (validate=yes).
Sending query packet with id 9007 on interface 2/AF_INET of size 27.
Timeout reached on transaction 40595.
Retrying transaction 40595.
Firing regular transaction 40595 for <archlinux IN ANY> scope llmnr on eth1/INET6 (validate=yes).
Sending query packet with id 40595 on interface 3/AF_INET6 of size 27.
Timeout reached on transaction 51910.
Retrying transaction 51910.
Firing regular transaction 51910 for <archlinux.local IN ANY> scope mdns on eth1/INET (validate=yes).
Sending query packet with id 0 on interface 3/AF_INET of size 49.
Timeout reached on transaction 37613.
Retrying transaction 37613.
Firing regular transaction 37613 for <archlinux.local IN ANY> scope mdns on eth1/INET6 (validate=yes).
Sending query packet with id 0 on interface 3/AF_INET6 of size 61.
Timeout reached on transaction 43768.
Retrying transaction 43768.
Firing regular transaction 43768 for <archlinux IN ANY> scope llmnr on eth0/INET6 (validate=yes).
Sending query packet with id 43768 on interface 2/AF_INET6 of size 27.
Timeout reached on transaction 40595.
Retrying transaction 40595.
Firing regular transaction 40595 for <archlinux IN ANY> scope llmnr on eth1/INET6 (validate=yes).
Sending query packet with id 40595 on interface 3/AF_INET6 of size 27.
Timeout reached on transaction 9007.
Retrying transaction 9007.
Firing regular transaction 9007 for <archlinux IN ANY> scope llmnr on eth0/INET (validate=yes).
Sending query packet with id 9007 on interface 2/AF_INET of size 27.
Timeout reached on transaction 51910.
Retrying transaction 51910.
Regular transaction 51910 for <archlinux.local IN ANY> on scope mdns on eth1/INET now complete with <attempts-max-reached> from none (unsigned; non-confidential).
Record archlinux.local IN A 10.111.113.1 successfully probed.
Sending response packet with id 0 on interface 3/AF_INET of size 82.
Freeing transaction 51910.
Timeout reached on transaction 24681.
Retrying transaction 24681.
Regular transaction 24681 for <archlinux IN ANY> on scope llmnr on eth1/INET now complete with <not-found> from none (unsigned; non-confidential).
Record archlinux IN A 10.111.113.1 successfully probed.
Freeing transaction 24681.
Timeout reached on transaction 37613.
Retrying transaction 37613.
Firing regular transaction 37613 for <archlinux.local IN ANY> scope mdns on eth1/INET6 (validate=yes).
Sending query packet with id 0 on interface 3/AF_INET6 of size 61.
Timeout reached on transaction 43768.
Retrying transaction 43768.
Regular transaction 43768 for <archlinux IN ANY> on scope llmnr on eth0/INET6 now complete with <not-found> from none (unsigned; non-confidential).
Record archlinux IN AAAA fe80::5054:ff:fe12:3456 successfully probed.
Record archlinux IN AAAA fec0::5054:ff:fe12:3456 successfully probed.
Freeing transaction 43768.
Timeout reached on transaction 9007.
Retrying transaction 9007.
Regular transaction 9007 for <archlinux IN ANY> on scope llmnr on eth0/INET now complete with <not-found> from none (unsigned; non-confidential).
Record archlinux IN A 172.27.0.15 successfully probed.
Freeing transaction 9007.
Timeout reached on transaction 40595.
Retrying transaction 40595.
Regular transaction 40595 for <archlinux IN ANY> on scope llmnr on eth1/INET6 now complete with <not-found> from none (unsigned; non-confidential).
Record archlinux IN AAAA fe80::f800:363d:eca:6444 successfully probed.
Freeing transaction 40595.
Timeout reached on transaction 37613.
Retrying transaction 37613.
Regular transaction 37613 for <archlinux.local IN ANY> on scope mdns on eth1/INET6 now complete with <attempts-max-reached> from none (unsigned; non-confidential).
Record archlinux.local IN AAAA fe80::f800:363d:eca:6444 successfully probed.
Sending response packet with id 0 on interface 3/AF_INET6 of size 141.
Freeing transaction 37613.
Got message type=method_call sender=:1.171 destination=org.freedesktop.resolve1 path=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=ResolveAddress cookie=2 reply_cookie=0 signature=iiayt error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixProcessID cookie=22 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.170 path=n/a interface=n/a member=n/a cookie=18 reply_cookie=22 signature=u error-name=n/a error-message=n/a
D-Bus address resolution request from client PID 1295 (resolvectl) with UID 0
Looking up RR for 2.113.111.10.in-addr.arpa IN PTR.
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=23 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetNameOwner cookie=24 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.170 path=n/a interface=n/a member=n/a cookie=20 reply_cookie=24 signature=s error-name=n/a error-message=n/a
eth0: Switching to DNS server fec0::3.
Cache miss for 2.113.111.10.in-addr.arpa IN PTR
Firing regular transaction 2241 for <2.113.111.10.in-addr.arpa IN PTR> scope llmnr on eth1/INET (validate=yes).
Delaying llmnr transaction 2241 for 63007us.
Cache miss for 2.113.111.10.in-addr.arpa IN PTR
Firing regular transaction 48847 for <2.113.111.10.in-addr.arpa IN PTR> scope mdns on eth1/INET (validate=yes).
Delaying mdns transaction 48847 for 0us.
Initial jitter phase for transaction 48847 elapsed.
Retrying transaction 48847.
Cache miss for 2.113.111.10.in-addr.arpa IN PTR
Firing regular transaction 48847 for <2.113.111.10.in-addr.arpa IN PTR> scope mdns on eth1/INET (validate=yes).
Sending query packet with id 0 on interface 3/AF_INET of size 43.
Got message type=method_return sender=org.freedesktop.DBus destination=:1.170 path=n/a interface=n/a member=n/a cookie=19 reply_cookie=23 signature=n/a error-name=n/a error-message=n/a
Match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0=':1.171' successfully installed.
Initial jitter phase for transaction 2241 elapsed.
Retrying transaction 2241.
Cache miss for 2.113.111.10.in-addr.arpa IN PTR
Firing regular transaction 2241 for <2.113.111.10.in-addr.arpa IN PTR> scope llmnr on eth1/INET (validate=yes).
Regular transaction 2241 for <2.113.111.10.in-addr.arpa IN PTR> on scope llmnr on eth1/INET now complete with <not-found> from none (unsigned; non-confidential).
Sending response packet with id 0 on interface 3/AF_INET6 of size 141.
Timeout reached on transaction 48847.
Retrying transaction 48847.
Cache miss for 2.113.111.10.in-addr.arpa IN PTR
Firing regular transaction 48847 for <2.113.111.10.in-addr.arpa IN PTR> scope mdns on eth1/INET (validate=yes).
Sending query packet with id 0 on interface 3/AF_INET of size 43.
Timeout reached on transaction 48847.
Retrying transaction 48847.
Cache miss for 2.113.111.10.in-addr.arpa IN PTR
Firing regular transaction 48847 for <2.113.111.10.in-addr.arpa IN PTR> scope mdns on eth1/INET (validate=yes).
Sending query packet with id 0 on interface 3/AF_INET of size 43.
Got message type=method_call sender=:1.6 destination=org.freedesktop.resolve1 path=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=ResolveHostname cookie=554 reply_cookie=0 signature=isit error-name=n/a error-message=n/a
idn2_lookup_u8: ping.archlinux.org → ping.archlinux.org
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixProcessID cookie=25 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.170 path=n/a interface=n/a member=n/a cookie=21 reply_cookie=25 signature=u error-name=n/a error-message=n/a
D-Bus hostname resolution request from client PID 309 (NetworkManager) with UID 0
Looking up RR for ping.archlinux.org IN AAAA.
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=26 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetNameOwner cookie=27 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.170 path=n/a interface=n/a member=n/a cookie=23 reply_cookie=27 signature=s error-name=n/a error-message=n/a
Cache miss for ping.archlinux.org IN AAAA
Firing regular transaction 18705 for <ping.archlinux.org IN AAAA> scope dns on */* (validate=yes).
Using feature level UDP+EDNS0+DO for transaction 18705.
Using DNS server 127.0.0.1 for transaction 18705.
Announcing packet size 65508 in egress EDNS(0) packet.
Emitting UDP, link MTU is 1500, socket MTU is 65535, minimal MTU is 40
Sending query packet with id 18705 of size 70.
Cache miss for ping.archlinux.org IN AAAA
Firing regular transaction 1718 for <ping.archlinux.org IN AAAA> scope dns on eth0/* (validate=yes).
Using feature level UDP+EDNS0+DO for transaction 1718.
Using DNS server fec0::3 for transaction 1718.
Announcing packet size 1452 in egress EDNS(0) packet.
Emitting UDP, link MTU is 1500, socket MTU is 0, minimal MTU is 60
Sending query packet with id 1718 of size 70.
Connection failure for DNS UDP packet: Connection refused
Regular transaction 18705 for <ping.archlinux.org IN AAAA> on scope dns on */* now complete with <ECONNREFUSED> from none (unsigned; non-confidential).
Got message type=method_return sender=org.freedesktop.DBus destination=:1.170 path=n/a interface=n/a member=n/a cookie=22 reply_cookie=26 signature=n/a error-name=n/a error-message=n/a
Match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0=':1.6' successfully installed.
Timeout reached on transaction 48847.
Retrying transaction 48847.
Regular transaction 48847 for <2.113.111.10.in-addr.arpa IN PTR> on scope mdns on eth1/INET now complete with <attempts-max-reached> from none (unsigned; non-confidential).
Freeing transaction 2241.
Sent message type=error sender=n/a destination=:1.171 path=n/a interface=n/a member=n/a cookie=28 reply_cookie=2 signature=s error-name=org.freedesktop.DBus.Error.Timeout error-message=All attempts to contact name servers or networks failed
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RemoveMatch cookie=29 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Freeing transaction 48847.
Got message type=signal sender=org.freedesktop.DBus destination=n/a path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameOwnerChanged cookie=24 reply_cookie=0 signature=sss error-name=n/a error-message=n/a
```
```

**Comment by poettering** [comment] 2023-02-28 20:43
this is on the local network? if so we'll try to resolve the name via mdns, and if the peer doesn't have mdns then it will time out.

turn off mdns if you don't want this?

**Comment by rpigott** [comment] 2023-03-01 00:09
Possible dupe of #14735 and #26594?

**Comment by jelly** [comment] 2023-03-01 09:56
@poettering Right, I guess that's how we are going to workaround this, I'm still not sure why `cockpit-ssh` ends up calling `resolvectl query $ip` but that's something for us to figure out. For now I can get our test setup working again by disabling MulticastDNS with a dropin file.

(Re-reading the commit message of e31540196b8fb136a8f197c7a26d851bd0b93329 made it kinda obvious why it broke)

@rpigott no it's not. This issue did not occur before in 252.

**Closed as completed** 2023-03-01 09:57 UTC
Labels: bug 🐛, resolve
