### ISSUE TITLE
systemd-bootd: booting last option when resuming from hibernate

### ISSUE THREAD

**Issue by smopucilowski** [systemd/systemd#31081] opened 2024-01-25 06:42 UTC
### Component

bootctl

### Is your feature request related to a problem? Please describe

I multiboot using `systemd-boot` making a choice from multiple entry definitions in `/boot/loader/entries`.

When I hibernate my machine, the bootloader isn't aware the system was hibernated and which boot option was the "last boot".

As such there is a risk when resuming that I can clobber the hibernated swap partition, and corrupt a file system that is mounted by a hibernated boot.

### Describe the solution you'd like

It would be nice if the bootloader was aware/cautioning we're resuming a hibernated boot, or hibernate tainted swap partition.

Perhaps `systemctl hibernate` can inform `bootctl` which entry to 1-time boot to on power-up.

### Describe alternatives you've considered

Potentially I can cludge a service targetting `hibernate.target` which sets a one-boot target.

**Comment by YHNdnzj** [comment] 2024-01-25 07:20
Duplicate of #29037

**Closed as completed** 2024-01-25 07:21 UTC
Labels: RFE 🎁, sd-boot/sd-stub/bootctl, duplicate
