### ISSUE TITLE
XDG-variables for user without password are not set anymore

### ISSUE THREAD

**Issue by nerdnils** [systemd/systemd#9525] opened 2018-07-07 16:43 UTC
**systemd version the issue has been seen with**
239.0, worked fine up to 238.133

**Used distribution**
Archlinux

**Expected behaviour you didn't see**
XDG-Variables set.
Being exactly:
$export|grep XDG_VTNR
declare -x XDG_VTNR="2"

**Unexpected behaviour you saw**
Nothing is returned even by "export|grep XDG"

**Steps to reproduce the problem**
passwd -l $user
autologin with the user like described here: https://wiki.archlinux.org/index.php/Getty#Automatic_login_to_virtual_console

Works again when the user is given a password and logs in with it. But I need this user not to be able to log in on his own.

**Comment by poettering** [comment] 2018-07-08 11:07
is pam_systemd included in the PAM stack of that autologin getty?

**Comment by nerdnils** [comment] 2018-07-08 12:47
How to include it and how to look if it is?

**Comment by boucman** [comment] 2018-07-08 13:38
please look in /etc/pam.d, there should be a file called gdm, check for a line containing pam_systemd.so

do note that this file might include more files, please follow thoses to make sure it's not included recursively

**Comment by nerdnils** [comment] 2018-07-08 15:43
I am NOT using gdm and the tty where this happens does not use any login manager at all. So no, I don't have any gdm in /etc/pam.d

**Comment by nerdnils** [comment] 2018-07-08 15:45
But I have pam_systemd.so:
19:-session   optional   pam_systemd.so
17:-session             optional pam_systemd.so

**Comment by poettering** [comment] 2018-07-13 16:42
@nerdnils is pam_systemd included in the pam stack for your autologin tool? it can be included either directly or possibly indirectly through some `include` stanza. 

If it isn't included in the PAM stack, then this explains the issue. Whether it is included or not is something up to the distributions. Please ping your distro for help on this, if the module is missing. And no, I can't tell you what the PAM snippet is for your autologin tool, please ping your community.

**Comment by nerdnils** [comment] 2018-07-17 04:59
So the community told me to remove the - from this line in /etc/pam-d/system-login:
-session   optional   pam_systemd.so
this did not work out so we added debug at the end.
journalctl after this and relogging on:
http://pasteall.org/1027892

Downgrade systemd to 239.0 and it works again, any newer version has those errors.

**Comment by poettering** [comment] 2018-07-17 08:46
`getty@tty2.service.d.service` – what's that supposed to be?

The appears to be something wrong with your unit file setup... something ending in ".service.d" is usually a drop-in *directory* for extending unit files, but then you also have ".service" at the end of it... What precisely are the files an directories you created for this in /etc/systemd/system?

**Comment by nerdnils** [comment] 2018-07-17 15:17
# cd /etc/systemd/system/getty\@tty2.service.d/
[root@cab getty@tty2.service.d]# ls
override.conf
# cat override.conf 
[Service]
ExecStart=
ExecStart=-/usr/bin/agetty --autologin cab --noclear %I $TERM


Exactly as described here https://wiki.archlinux.org/index.php/Getty#Automatic_login_to_virtual_console as I mentioned in the first post.

**Comment by nerdnils** [comment] 2018-07-17 19:55
Not as far as I know. Where should I look for them? What else could cause this?

**Comment by poettering** [comment] 2018-07-19 14:11
try `find /etc/systemd/system/ -type l`. What does that show?

**Comment by nerdnils** [comment] 2018-07-19 16:07
/etc/systemd/system/multi-user.target.wants/atd.service
/etc/systemd/system/multi-user.target.wants/systemd-networkd.service
/etc/systemd/system/multi-user.target.wants/wpa_supplicant@wlp4s5.service
/etc/systemd/system/multi-user.target.wants/lm_sensors.service
/etc/systemd/system/multi-user.target.wants/netcfgmeins.service
/etc/systemd/system/multi-user.target.wants/systemd-resolved.service
/etc/systemd/system/multi-user.target.wants/sshd.service
/etc/systemd/system/multi-user.target.wants/remote-fs.target
/etc/systemd/system/display-manager.service
/etc/systemd/system/getty.target.wants/getty@tty2.service.d.service
/etc/systemd/system/getty.target.wants/getty@tty2.service

Maybe I should add that display-manager.service runs on tty1 and is a simple kdm.

**Comment by nerdnils** [comment] 2018-07-26 15:03
I can not reboot this machine atm. I will report when I can.

**Comment by nerdnils** [comment] 2018-07-29 19:44
First: this did not solve the problem.

loginctl done as user cab on the problematic tty2: http://ix.io/1iHh
http://ix.io/1iHi

**Comment by poettering** [comment] 2018-07-30 11:39
This is interesting:

```
State: opening
```

This means the scope unit for the session is never successfully created.

Would be interesting to see a more complete set of root logs about this. It appears that something is wrong and maybe dbus communication between logind and PID 1 doesn't work.

**Comment by nerdnils** [comment] 2018-07-30 14:17
What logs exactly do you need?
I can not see anything related to this in journalctl -b 0

**Comment by nerdnils** [comment] 2018-08-02 14:31
What logs do you need poettering?

**Comment by poettering** [comment] 2018-08-02 15:03
The system logs up to where the problem occurs, and best would be with debug logging on (i.e. boot with systemd.log_level=debug on the kernel cmdline)

**Comment by nerdnils** [comment] 2018-08-02 17:30
here you are:

[systemdlog.txt](https://github.com/systemd/systemd/files/2254535/systemdlog.txt)

**Comment by poettering** [comment] 2018-08-02 18:09
Those are just the *user* logs. I asked for *system* logs. i.e. please provide the logs journalctl called as root user shows you, and include the time where your user logged in.

**Comment by nerdnils** [comment] 2018-08-02 18:17
19:28 at the end of the last log.
[journalroot.txt](https://github.com/systemd/systemd/files/2254672/journalroot.txt)

**Comment by poettering** [comment] 2018-08-02 18:32
You still have this weird `getty@tty2.service.d.service` thing in there. Can you fix that first? That service name makes no sense...

**Comment by nerdnils** [comment] 2018-08-02 18:53
Got rid of it:
# find /etc/systemd/system/ -type l
/etc/systemd/system/multi-user.target.wants/atd.service
/etc/systemd/system/multi-user.target.wants/systemd-networkd.service
/etc/systemd/system/multi-user.target.wants/wpa_supplicant@wlp4s5.service
/etc/systemd/system/multi-user.target.wants/lm_sensors.service
/etc/systemd/system/multi-user.target.wants/netcfgmeins.service
/etc/systemd/system/multi-user.target.wants/systemd-resolved.service
/etc/systemd/system/multi-user.target.wants/sshd.service
/etc/systemd/system/multi-user.target.wants/remote-fs.target
/etc/systemd/system/display-manager.service

New log:
[journalroot.txt](https://github.com/systemd/systemd/files/2254782/journalroot.txt)

User logged in:
Aug 02 20:49:48 cab systemd[524]: getty@tty2.service: Executing: /usr/bin/agetty --autologin cab --noclear tty2 linux

**Comment by poettering** [comment] 2018-08-02 18:54
Hmm, so looking at this it appears to be caused because the session you are creating is very short lived and this triggers a bug in logind. various jobs logind enqueues already get canceled while they are still pending, such as es xdg runtime dir unit @keszybz added.

**Comment by nerdnils** [comment] 2018-08-02 18:55
But why is the session short lived? I do not log out or anything.

**Comment by poettering** [comment] 2018-10-24 16:04
So I am pretty sure this has been fixed in current git already, specifically by #9824. I will close this now. Would be good if you could check with a git version newer than the merge of #9824. In the unlikely case you can reproduce the issue with that, please reopen.

**Closed as completed by poettering** 2018-10-24 16:04 UTC
Labels: bug 🐛, login
