### ISSUE TITLE
"timedatectl status" takes long (20 s) on the first run when you have many (thousand) bind-mount-Units

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#31139] opened 2024-01-31 08:40 UTC
### systemd version the issue has been seen with

249.11-0ubuntu3.7

### Used distribution

Ubuntu 22 server LTS

### Linux kernel version used

5.15.0-92-generic

### CPU architectures issue was seen on

x86_64

### Component

timedatectl

### Expected behaviour you didn't see

Fast (<2 s) output of command

`timedatectl status`

### Unexpected behaviour you saw

`timedatectl status` takes 21 s to display the status.

### Steps to reproduce the problem

On the Ubuntu 22 Server have a NFSv4 Mount /nfsimp/sftphome/

and underneath that NFS mount have 1400 Bind-Mount-Units to each a local folder, all of this type (where xxxx are 1400 different names (sftp users that have each their own log device on the local bind mount, for user specific log files)):
```
[Unit]
Description=Bind-Mount xxxx
# stop this unit when /nfsimp/sftphome/ is unmounted
# but just fail to start this unit if /nfsimp/sftphome/ is unmounted.
PartOf=nfsimp-sftphome.mount
After=nfsimp-sftphome.mount
AssertPathIsDirectory=/nfsimp/sftphome/xxxx/dev


[Mount]
# /var/data/dev/xxxx/ is a local folder
What=/var/data/dev/xxxx
Where=/nfsimp/sftphome/xxxx/dev
Options=bind,_netdev
# wait 10 s for mount, otherwise abort and stop.
TimeoutSec=10
# force an unmount (in case of an unreachable NFS system). Corresponds with umount's -f switch.
ForceUnmount=true


[Install]
# start this unit when /nfsimp/sftphome/ is mounted
WantedBy=nfsimp-sftphome.mount
```

When you have not issued `timedatectl status` for like 20 minutes, it it takes 20 s. But after that the following executions of that command happen at once as expected. When you wait 20 minutes again, the first execution is slow again. See here:

```
$ date +'Start %T' ; time timedatectl status ; sleep 10 ; date +'Start %T' ; time timedatectl status
Start 09:11:58
               Local time: Fri 2024-01-26 09:12:19 CET
           Universal time: Fri 2024-01-26 08:12:19 UTC
                 RTC time: Fri 2024-01-26 08:12:19
                Time zone: Europe/Berlin (CET, +0100)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no


real    0m21.075s
user    0m0.000s
sys     0m0.009s
Start 09:12:29
               Local time: Fri 2024-01-26 09:12:29 CET
           Universal time: Fri 2024-01-26 08:12:29 UTC
                 RTC time: Fri 2024-01-26 08:12:29
                Time zone: Europe/Berlin (CET, +0100)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no


real    0m0.015s
user    0m0.004s
sys     0m0.005s
```
Sometimes, it even takes longer than 25 s that leaves to error because of timeout:
`Failed to query server: Failed to activate service 'org.freedesktop.timedate1': timed out (service_start_timeout=25000ms)`

The same problem is with SSH sessions to the sshd service. First session establishment takes 20 s, following sessions are established normally fast.

What is the problem here that makes the system / systemd so slow?
Is there some sort of cache?
How can I debug this?
Might this be a dbus problem?
How to fix this?
Thank you.

(cross posting https://ubuntuforums.org/showthread.php?t=2494763)

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Failed to query server: Failed to activate service 'org.freedesktop.timedate1': timed out (service_start_timeout=25000ms)
```

**Comment by daku3649** [comment] 2024-01-31 15:11
P.S. Of course it is bad to have over thousand mount units (so I agree with @poettering's general concern in  https://github.com/systemd/systemd/issues/31137#issuecomment-1918642689).
The problem that led to those mounts can be read here:
https://unix.stackexchange.com/questions/666641/howto-log-multiple-sftpd-servers-activity-which-users-chrooted-home-is-on-shar
(answers with better solution welcome!)

Or here the long discussion about the problem on the OpenSSH maling list: [Howto log multiple sftpd instances with their chroot shared via NFS](https://groups.google.com/g/opensshunixdev/c/yU165Xl5Azc)

**Comment by dtardon** [comment] 2024-02-01 08:48
Duplicate of #31137.

**Closed as not planned by dtardon** 2024-02-01 08:48 UTC
Labels: bug 🐛, timedate, duplicate

**Comment by daku3649** [comment] 2024-02-02 13:20
Filed upstream (OpenSSH) enhancement request [Make logging of chrooted sftp sessions possible internally routed to local file, without /dev/log device](https://bugzilla.mindrot.org/show_bug.cgi?id=3662)
