### ISSUE TITLE
Allow ordering of system units after sd-homed login

### ISSUE THREAD

**Issue by ljrk0** [systemd/systemd#17246] opened 2020-10-04 15:28 UTC
**Is your feature request related to a problem? Please describe.**
I want to bind-mount a globally-shared directory (`/data`) into my users home directory (e.g., to `/home/leonard/.data-bind`).  However, my home is mounted by `home-leonard.mount` which is created ad-hoc by sd-homed. I had two ideas to implement that: First, I tried to create a `.mount` unit:
```
[Unit]
Description=Bind-mount /data to leonard home dir
After=home-leonard.mount
Wants=home-leonard.mount
RequiresMountsFor=/home/leonard

[Mount]
What=/data
Where=/home/leonard/.data-bind
Type=none
Options=bind

[Install]
WantedBy=multi-user.target
```
Unfortunately, neither ordering with `After=` nor `RequiresMountsFor=` works, likely, since when loaded by systemd, the `home-leonard.mount` unit isn't "there" yet. Hence, this unit executes before the `home-leonard.mount`.

The second idea was to not enable the `.mount` unit but to have a `.automount` unit trigger it when the path is accessed:
```
[Unit]
Description=Trigger automount of bind-mount from /data to leonard home dir

[Automount]
Where=/home/leonard/.data-bind

[Install]
WantedBy=multi-user.target
```
Unfortunately, this unit loads before `home-leonard.mount` and likely "listens" for "access" on a wrong inode or such like. When I restart this `.automount` unit _after login_, it works fine.

**Describe the solution you'd like**
I think the "right" way would be to be able to specify that a `.mount` and/or `.automount` unit is only to be executed after a specific login/sd-homed mount.

**Describe alternatives you've considered**
Alternatively, the `.automount` unit notices, that the path it watches changes and reloads its triggers.

**Rationale**
I want to use systemd-homed in combination with the [containers/toolbox](https://github.com/containers/toolbox) and access these "shared" files from within the container. While I can ask podman directly to also pass-through the `/data` volume, the same cannot be said(?) for podman, and it seems to me to be against its design anyway.  Ideally, I can mount "remote" additional volumes after login, be it my bind-mount use case or NFS etc.

**Comment by keszybz** [comment] 2020-10-05 05:58
I'd avoid this. This creates an ugly interdependence between system things and user things. Why can't you just leave the /data mount on /data and let users symlink ~/.data-bind to /data? Anything sane should just accept ~/.data-bind/ as the path to work on and follow the symlink.

**Comment by LeonardKoenig** [comment] 2020-10-05 08:09
@keszybz The symlink indeed gets carried over into the container but since `/data` isn't available in toolbox, it's effectively dead.  While my use case may indeed be a bit peculiar, I think being available to access networked filesystems under e.g., `/export` or other "dynamic" configurations. Of course this can be instead seen as a toolbox issue, I'm not sure either whether we want to solve this "here" or "there". I could imagine it being helpful though to trigger system units on login or sd-omed home activation.

Another alternative I thought of and that's currently effectively in place here: Have the `user` option in `/etc/fstab` for the bind mount and create "regular" user unit to execute `mount %h/.data-bind`. I unfortunately cannot do that with a mount unit since it requires the `What=` key, however user mounts (seem to) only work if just the target/source is given.

**Comment by poettering** [comment] 2020-10-05 13:57
This is problematic security wise: having privileged code mount/create dirs below unpriv dirs is always problematic, due to symlink attacks.

Not sure what "toolbox" is, but maybe that thing should be fixed instead? What you are doing is a simply a hack...

That all said, you should be able to pull in your mount unit from a home-leonard.wants/ symlink. 

In general: this sounds a lot like a user support question, not a bug report or feature request. Hence, please do not isue the github issue tracker, as we try to keep the noise level, and use it only for bug reports and feature requests. For support stuff, please use the mailing list or so.

Hope that makes sense, closing.

**Closed as completed by poettering** 2020-10-05 13:57 UTC
