### ISSUE TITLE
systemd-journald spams dmesg when it is unable to write to disk

### ISSUE THREAD

**Issue by Mayzie** [systemd/systemd#3034] opened 2016-04-14 05:35 UTC
### Submission type
- [x] Bug report

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> journalctl --version
> systemd 229
> +PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux x86_64
### In case of bug report: Expected behaviour you didn't see

> Shouldn't clog up dmesg with unable to write message.
### In case of bug report: Unexpected behaviour you saw

> Clogged up dmesg with "Failed to {rotate|write}" messages. (see attached "systemd-journald.txt" file for dmesg output).
### In case of bug report: Steps to reproduce the problem

> Have BTRFS fail. (see attached "dmesg.txt" for what happened in dmesg before systemd-journald started spamming it [this is the earliest I could get, I don't know how to go back and see older messages in dmesg]).
### Attachments (dmesg)

[systemd-journald.txt](https://github.com/systemd/systemd/files/218441/systemd-journald.txt)
[dmesg.txt](https://github.com/systemd/systemd/files/218440/dmesg.txt)

**Comment by evverx** [comment] 2016-04-14 10:16
Related: https://github.com/systemd/systemd/issues/2339

**Comment by poettering** [comment] 2016-04-14 13:03
Closing as duplicate of #2339

**Closed as completed by poettering** 2016-04-14 13:03 UTC
Labels: journal, duplicate
