### ISSUE TITLE
Issue w/ HandleLidSwitch Settings

### ISSUE THREAD

**Issue by ipb26** [systemd/systemd#15995] opened 2020-05-31 21:32 UTC
I've been having an issue running Elementary OS on a laptop for quite some time. Most of the time, my laptop is closed, plugged into a USB C hub which is connected to an external monitor.

When I lock the screen, 1 in 5 times or so, my system goes into suspend instead of taking me back to the greeter.

Ideally, I would have HandleLidSwitch=suspend and HandleLidSwitchDocked=ignore (the defaults) and it would work fine. What I'm trying to accomplish should work with these settings.

However, HandleLidSwitchDocked only takes effect most of the time. I know this is the issue because if I set HandleLidSwitchDocked=suspend, it suspends every time I lock, whereas if I set HandleLidSwitch=ignore, it never suspends when I lock. So apparently logind thinks I am not docked about 20% of the time, even though I am. Attaching systemd debug logs from the last time this happened (search for "Suspending" to see where it suspends).

[journalctl.txt](https://github.com/systemd/systemd/files/4708532/journalctl.txt)

uname -a: Linux sam 5.3.0-53-generic #47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by poettering** [comment] 2020-06-02 07:37
what desktop do you use? My educated guess is that this is  duplicate of #12001 maybe? Is that possible?

**Comment by sbarrow** [comment] 2020-06-02 14:03
I'm on Pantheon, Elementary OS. Not on Wayland.

**Comment by keszybz** [comment] 2020-10-10 08:11
What systemd version?

**Comment by poettering** [comment] 2021-02-12 17:12
Closing due to lack of response

**Closed as completed by poettering** 2021-02-12 17:12 UTC
Labels: login, needs-reporter-feedback ❓
