### ISSUE TITLE
systemctl cat nonexistent@ fails with assertion error

### ISSUE THREAD

**Issue by nicoonoclaste** [systemd/systemd#14739] opened 2020-02-02 23:58 UTC
**systemd version the issue has been seen with**
```
$ systemd --version                                                        :(
systemd 244 (244.1-2)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

**Used distribution**
Debian 11 (testing, “bullseye”)

**Expected behaviour you didn't see**
```
$ systemctl cat notexist@
No files found for notexist@.service.
```

**Unexpected behaviour you saw**
```
$ systemctl cat notexist@
Assertion 'name' failed at src/shared/dropin.c:143, function unit_file_find_dirs(). Aborting.
[1]    63986 abort      systemctl cat notexist@
```

**Steps to reproduce the problem**
See above

**Notes**
The issue seems to be limited to non-existent, templated units:
- non-existent, non-templated units work fine;
```
$ systemctl cat notexist
No files found for notexist.service.
```
- exiting, templated units work.
```
$ systemctl cat hostapd@
# /lib/systemd/system/hostapd@.service
[...]
```

This was initially reported as [Debian bug #950489](https://bugs.debian.org/950489).

**Comment by yuwata** [comment] 2020-02-03 01:00
I cannot reproduce this with the current git master (and v243).
```
$ systemctl cat hoge@
No files found for hoge@.service.
```
Could you test with the current git master?

**Comment by yuwata** [comment] 2020-02-03 01:03
Ah, this is already fixed by 7a670b1dd981c645064f69faf85b04620aadbafb.

**Comment by yuwata** [comment] 2020-02-03 01:05
@keszybz Could you backport the commit to the stable repository?

**Closed as completed by yuwata** 2020-02-03 01:05 UTC
Labels: bug 🐛, systemctl, already-fixed

**Comment by mbiebl** [comment] 2020-02-03 22:52
Thanks @yuwata . I've cherry-picked the fix in Debian for the time being.
