### ISSUE TITLE
Systemd hangs on LUKS

### ISSUE THREAD

**Issue by uzytkownik** [systemd/systemd#6611] opened 2017-08-14 18:03 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 234

### Used distribution

> Gentoo

### In case of bug report: Expected behaviour you didn't see

> System prompts for password

### In case of bug report: Unexpected behaviour you saw

Log rewritten from photo (kernel message about NIC and sound card startup edited out for bravery] 

```
     Starting cryptography setup for luks <LUKS UUID>...
[6.510858] dracut-initqueue[2285]: Warning systemd-cryptsetup@<LUKS UUID>.service changed on disk. Run 'systemctl ...
```

And than system hangs. This happens both with and without plymouth. 

### In case of bug report: Steps to reproduce the problem

Use systemd on LUKS on LVM?

**Comment by bl33pbl0p** [comment] 2017-08-15 14:28
This is more of a downstream issue, also, 234 got a few bug fixes including the LUKS timeout bug with -r3, try updating to it, meanwhile, you can pass rd.luks.options=timeout=15s (assuming this was a previously working setup broken due to an update). Otherwise, there's something wrong in the kernel parameters you're passing. It works here on Gentoo ~amd64 systemd-234-r3 with systemd in dracut used to decrypt the LUKS device.

**Comment by uzytkownik** [comment] 2017-08-16 02:54
@bl33pbl0p I did tried -r3. I'll try rd.luks.options

**Comment by bl33pbl0p** [comment] 2017-08-16 10:39
Then probably you're passing the wrong parameters, read man systemd-cryptsetup-generator, and also paste your logs after passing debug (in the unlikely case of this being a bug). (add base to dracut modules to drop to a working shell environment in the initramfs and retrieve the logs).
This still looks less of a bug as I had the same issue when passing the wrong UUID to rd.luks.uuid= (of the device mapper instead of the LUKS block device). only root= takes the UUID of the device mapper, rd.luks.uuid= and rd.luks.name= take UUID of the LUKS block device. Again, see `man systemd-cryptsetup-generator`

**Comment by uzytkownik** [comment] 2017-08-19 03:24
@bl33pbl0p Sorry for delay (I've got swamped by emails). I'm passing luks uuid i.e. thing I'm getting from `cryptsetup luksUUID /dev/<BLOCK DEVICE>`. It was working in 232 (233 was broken due to unrelated bug).

**Comment by uzytkownik** [comment] 2017-08-19 03:27
BTW I cannot past logs as system just... hangs. If I'm pressing any key nothing appears on screen.

**Comment by bl33pbl0p** [comment] 2017-08-19 16:08
As I said, can you paste the output of `blkid` (after you have opened the LUKS device, and your kernel command line? Also the modules you included in dracut? If every one of those is right, then probably there is something wrong in systemd, though I'm still not very convinced.

**Comment by uzytkownik** [comment] 2017-08-19 20:09
@bl33pbl0p Well, the systemd is the only variable so I don't think downgrading systemd and rebuilding initramfs from dracut would magically include more modules. Beside I have dmcrypt built in...

```
% sudo blkid
(...)
/dev/nvme0n1p2: UUID="76..." TYPE="crypto_LUKS" PARTLABEL="Linux filesystem" PARTUUID="30..."
(...)
/dev/mapper/luks-76...: UUID="u0..." TYPE="LVM2_member"
% cat /proc/cmdline
initrd=\03...\4.12.6-ck\initramfs.img rd.luks.uuid=luks-76... rd.luks.allow-discards=luks-76... rd.lvm.lv=... rd.lvm.lv=... root=/dev/mapper/... init=/usr/lib/systemd/systemd
% zcat /proc/config.gz | grep DM_CRYPT
CONFIG_DM_CRYPT=y
```

**Comment by bl33pbl0p** [comment] 2017-08-21 06:21
Well, I meant dracut modules.
You need dm and crypt to begin with, except the systemd ones.
> rd.luks.uuid=luks-76...

should be rd.luks.uuid=76...
You're passing the device mapper name that you see in blkid, not the uuid of the LUKS superblock.
Also, make sure your fstab uses the uuid of the unlocked device mapper. (u0...)

**Comment by uzytkownik** [comment] 2017-08-21 12:17
> Well, I meant dracut modules.
> You need dm and crypt to begin with, except the systemd ones.

I do. I mean how it would work on systemd-232.

>> rd.luks.uuid=luks-76...
> should be rd.luks.uuid=76...

To quote the dracut manpage:
```
           (...) Any
           "luks-" of the LUKS UUID is removed before comparing to <luks
           uuid>. The comparisons also matches, if <luks uuid> is only the
           beginning of the LUKS UUID, so you don’t have to specify the full
           UUID. This parameter can be specified multiple times.
```

Does systemd behaves differently? If yes it _probably_ should be documented more explicitly especially if this is recent change.

**Comment by uzytkownik** [comment] 2017-08-21 14:11
@bl33pbl0p I checked - it doesn't work without luks as well. I have no idea what fstab is suppose to do with it - especially that there is LVM on top of LUKS so it wouldn't directly include any names anyway. Beside if this was a problem why would `systemd-cryptsetup@<LUKS UUID>.service` be started at all?

PS. systemd+LUKS works for you, that's great. I've used systemd+LUKS on Gentoo for many years now (5? 6? 7? I don't remember) and set it up on several systems. I'm reasonably certain that if this is configuration issue then it is due to recent change of how systemd handles configuration.

**Comment by bl33pbl0p** [comment] 2017-08-21 16:27
> "luks-" of the LUKS UUID is removed before comparing to <luks uuid>. The comparisons also matches, if <luks uuid> is only the beginning of the LUKS UUID, so you don’t have to specify the full UUID. This parameter can be specified multiple times.

You're reading the wrong man page, that is for rd_LUKS_UUID which must be from dracut's crypt module. Anyway,
Are you not giving it the full UUID (if you're wondering, no, you need to give it the full UUID, idk if this is a recent change, but I've always given it full UUIDs, and that is how it has worked for some time now)? Please refer to systemd-cryptsetup-generator man page for reference (it is well documented) as this is what is used to generate units to unlock your device here.

The systemd-cryptsetup unit will always be generated with what you feed the generator, and systemd will always try to start it, ofcourse what you feed it needs to be correct to be able to boot.

Anyway, try to boot with debug on and somehow give us something to read (since you say you cannot grab logs because it hangs, try clicking a picture?).

**Comment by uzytkownik** [comment] 2017-08-23 02:17
I'll add picture soon.

In related news - that might be fun bug to debug - updating kernel 'fixed' the problem so in newer (4.12.8) kernel it boots correctly while in older (4.12.7) it hangs. `.config` is essentially identical (I added a few netfilter NAT modules). I checked that md5sum of systemd binaries in initramfs is identical. I guess I suspect timing?

**Comment by bl33pbl0p** [comment] 2017-08-23 05:58
Yes, even if it is fixed, please provide debug output. (Also, you didnt tell me if you were using the full UUIDs or not, it looks very much possible that you were not, from dracut's man page, which may have been a part of the problem atleast.)

**Comment by uzytkownik** [comment] 2017-08-23 15:41
> Also, you didnt tell me if you were using the full UUIDs or not, it looks very much possible that you were not, from dracut's man page, which may have been a part of the problem atleast.

I'm using full UUID (it was easier to copy'n' paste whole UUID. I didn't know partial work even)

> Yes, even if it is fixed

I'm not sure if it is fixed or just hidden due to timing etc.

```
Calling manager for StartUnit on systemd-cryptsetup@luks<UUID>.service, replace
Sent message type=method_call sender=n/a destination=org.freedesktop.systemd1 object=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=StartUnit cookie=1 reply_cookie=0 error=n/a
Got message type=method_return sender=n/a destination=n/a object=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 error=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.systemd1 object=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=GetUnit cookie=2 reply_cookie=2 error=n/a
Got message type=method_return sender=n/a destination=n/a object=n/a interface=n/a member=n/a cookie=5 reply_cookie=2 error=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.systemd1 object=/org/freedesktop/systemd1/unit/systemd_2dcryptsetup_40luks_5c<UUID>_2eservice interface=org.freedesktop.DBus.Properties member=Get cookie=3 reply_cookie=0 error=n/a
Got message type=method_return sender=n/a destination=n/a object=n/a interface=n/a member=n/a cookie=6 reply_cookie=3 error=n/a
Warning: systemd-cryptsetup@luks<UUID>.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Adding /org/freedesktop/systemd1/job/17 to the set
Got message type=signal sender=n/a destination=n/a object=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobNew cookie=2 reply_cookie=0 error=n/a
Got message type=signal sender=n/a destination=n/a object=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobRemoved cookie=3 reply_cookie=0 error=n/a
Got message type=signal sender=n/a destination=n/a object=/org/freedesktop/systemd1/job/17 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=4 reply_cookie=0 error=n/a
```

**Comment by poettering** [comment] 2017-08-30 09:34
Warning: systemd-cryptsetup@luks<UUID>.service changed on disk. Run 'systemctl daemon-reload' to reload units.

This is very strange. Something is writing this out and not reloading systemd. I am not sure what that is about. Can you ping your downstream initrd maintainers about this please?

**Comment by bemeurer** [comment] 2018-12-10 02:21
I have encountered this very same issue on Gentoo using dracut.

**Comment by fturco** [comment] 2019-02-11 19:44
I also get the "changed on disk" / "daemon-reload" message from dracut-initqueue on my Gentoo Linux system. This started happening today after my weekly system upgrade (168 packages were upgraded).

I can successfully decrypt my root partition and boot the system, but I'd still like to get rid of that warning message. Running `systemd daemon-reload` doesn't help, unfortunately.

Package versions:
* sys-apps/systemd-241_rc2
* sys-kernel/dracut-049-r1

```
$ blkid
/dev/mapper/luks-4dd95fa7-9546-4a20-9b05-0e46774c823f: UUID="6cba4f6d-699f-4c47-aa40-bd9703a5ebeb" TYPE="ext4"
/dev/sda3: UUID="4dd95fa7-9546-4a20-9b05-0e46774c823f" TYPE="crypto_LUKS" PARTLABEL="LUKS" PARTUUID="b15189cf-014e-4318-9491-1b5900192a67"
...
```

This is my GRUB configuration in `/boot/grub/grub.cfg`

```
set default=linux-libre
set timeout=10

menuentry 'Linux-libre 4.20.7' --id linux-libre {
  linux /vmlinuz-4.20.7-gnu root=UUID=6cba4f6d-699f-4c47-aa40-bd9703a5ebeb ro init=/lib/systemd/systemd quiet loglevel=3 rd.luks.uuid=4dd95fa7-9546-4a20-9b05-0e46774c823f rd.vconsole.keymap=it
  initrd /initramfs-4.20.7-gnu.img
}
```

```
# journalctl -b -u dracut-initqueue --no-pager
-- Logs begin at Tue 2017-09-12 19:10:23 CEST, end at Mon 2019-02-11 20:41:58 CET. --
Feb 11 20:26:41 desktop systemd[1]: Starting dracut initqueue hook...
Feb 11 20:26:42 desktop dracut-initqueue[260]: Warning: The unit file, source configuration file or drop-ins of systemd-cryptsetup@luks\x2d4dd95fa7\x2d9546\x2d4a20\x2d9b05\x2d0e46774c823f.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Feb 11 20:26:59 desktop systemd[1]: Started dracut initqueue hook.
Feb 11 20:26:59 desktop systemd[1]: dracut-initqueue.service: Succeeded.
Feb 11 20:26:59 desktop systemd[1]: Stopped dracut initqueue hook.
```

**Comment by fturco** [comment] 2019-02-11 20:02
It seems I had deleted my `/etc/crypttab` configuration file for some reasons. So I managed to fix my problem by running the following commands:

```
touch /etc/crypttab
dracut -f
```

**Comment by bemeurer** [comment] 2019-02-11 22:30
@fturco That fixed it for me! Thank you!!

**Comment by poettering** [comment] 2019-02-12 11:01
Hmm, so apparently /etc/crypttab being removed was triggering this for at least two users, and the original reporter hasn't reported back so far. Let's hence assume the issue is not caused upstream but by a removed /etc/crypttab, and let's close this. Hope this makes sense.

**Closed as completed by poettering** 2019-02-12 11:01 UTC
Labels: needs-reporter-feedback ❓, cryptsetup

**Comment by fturco** [comment] 2019-08-06 19:40
This bug reappeared on my Gentoo system after upgrading systemd from version 242-r6 to 243_rc1-r1. I still have dracut-049-r1. My previous solution of creating an empty `/etc/crypttab` file and running `dracut -f` doesn't work anymore. I had to switch back to systemd 242-r6...
