### ISSUE TITLE
logind: Add HandleLidSwitch option for when device is connected to AC power

### ISSUE THREAD

**Issue by akors** [systemd/systemd#6122] opened 2017-06-14 10:16 UTC
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> v233

### Used distribution

> Fedora 26

Currently, there is are two options for how to handle Lid switches: they are HandleLidSwitch, HandleLidSwitchDocked where the latter applies when a device is "Docked". What this currently means is that it is counted how many displays are attached.

Most lid switch actions such as "poweroff", "suspend", "hibernate" and so on are related to power management, and therefor naturally depend on the availability of system power. In more practical terms: When running on battery, I want my device to suspend - but when it's running off of AC power, nothing needs to happen.

Therefor, I would like to request **either**:

- A new option called `HandleLidSwitchAC` or similar, which applies when the device is connected to a power source.

**or**

- Modify the semantics of `HandleLidSwitchDocked` to apply when the device is connected to a power source, and not the number of external displays.

**Comment by cjustin88** [comment] 2017-08-18 20:27
Is there any progress or a timeline on this? It would be nice to implement this functionality into systemd instead of using a script like this: [https://nrocco.github.io/2014/06/05/suspend-prevent-systemd.html](https://nrocco.github.io/2014/06/05/suspend-prevent-systemd.html)

**Comment by akors** [comment] 2017-08-18 20:34
> Is there any progress or a timeline on this? It would be nice to implement this functionality into systemd instead of 

Judging by the RFE label and the lack of comments, I'd say the timeline is never ;)

> using a script like this: https://nrocco.github.io/2014/06/05/suspend-prevent-systemd.html

Thanks, i didn't know about that yet!

**Comment by amir-barkal** [comment] 2017-08-24 06:30
I'd like this option to be implemented also.
It's quite crucial when working with external monitors.

**Comment by cjustin88** [comment] 2017-08-27 20:35
@amir-barkal: with the default systemd settings (everything commented out in `/etc/systemd/logind.conf`), if I close the laptop lid while on AC and with an external monitor connected, my laptop does not sleep. Is this acceptable behaviour for you?

This behaviour is documented here [logind.conf](https://www.freedesktop.org/software/systemd/man/logind.conf.html):

> If the system is inserted in a docking station, or if more than one display is connected, the action specified by HandleLidSwitchDocked= occurs; otherwise the HandleLidSwitch= action occurs.

So the default options `HandleLidSwitchDocked=ignore` and `HandleLidSwitch=suspend` should give you this behaviour.

**Comment by amir-barkal** [comment] 2017-08-27 21:44
That is not the same behavior I'm having. When I close the lid while an external monitor is connected via hdmi + ac power cord connected, the external monitor will shutdown.

(Using Fedora 26 latest updates + gnome on x11/wayland)

**Comment by cjustin88** [comment] 2017-08-28 00:04
@amir-barkal Have you tried explicitly setting those options in `logind.conf`? Maybe systemd is not detecting your external displays at all (or not detecting them as external).

**Comment by poettering** [comment] 2017-08-29 16:49
> Is there any progress or a timeline on this? It would be nice to implement this functionality into systemd instead of using a script like this: https://nrocco.github.io/2014/06/05/suspend-prevent-systemd.html

Due to our limited manpower the best way to get something in is by contributing a mergable patch for any feature you want...

**Comment by poettering** [comment] 2017-09-14 10:38
Duplicate of #5184

**Closed as completed by poettering** 2017-09-14 10:38 UTC
Labels: RFE 🎁, login
