### ISSUE TITLE
getaddrinfo returns EAI_NONAME inappropriately with nss_resolve

### ISSUE THREAD

**Issue by wfurt** [systemd/systemd#15076] opened 2020-03-11 05:26 UTC
**systemd version the issue has been seen with**
> libnss-systemd/now 237-3ubuntu10.11 amd64
libsystemd0/now 237-3ubuntu10.11 amd64

**Used distribution**
 > Ubuntu 18.04

**Expected behaviour you didn't see**
>

**Unexpected behaviour you saw**
 > This is related to https://github.com/systemd/systemd/issues/15075 and https://github.com/dotnet/runtime/issues/33145. I have seen cases when lookup fails with EAI_NONAME  for reasons other than a wrong name. 

man page for getaddrinfo describes:
```
       EAI_ADDRFAMILY
              The specified network host does not have any network addresses in the requested address family.

       EAI_AGAIN
              The name server returned a temporary failure indication.  Try again later.

       EAI_BADFLAGS
              hints.ai_flags contains invalid flags; or, hints.ai_flags included AI_CANONNAME and name was NULL.

       EAI_FAIL
              The name server returned a permanent failure indication.

       EAI_FAMILY
              The requested address family is not supported.

       EAI_MEMORY
              Out of memory.

       EAI_NODATA
              The specified network host exists, but does not have any network addresses defined.

       EAI_NONAME
              The node or service is not known; or both node and service are NULL; or AI_NUMERICSERV was specified in hints.ai_flags and service was not a numeric port-number string.

       EAI_SERVICE
              The requested service is not available for the requested socket type.  It may be available through another socket type.  For example, this error could occur if service was "shell"  (a  service
              available  only  on  stream sockets), and either hints.ai_protocol was IPPROTO_UDP, or hints.ai_socktype was SOCK_DGRAM; or the error could occur if service was not NULL, and hints.ai_socktype
              was SOCK_RAW (a socket type that does not support the concept of services).

       EAI_SOCKTYPE
              The requested socket type is not supported.  This could occur, for example, if hints.ai_socktype and hints.ai_protocol are inconsistent (e.g., SOCK_DGRAM and IPPROTO_TCP, respectively).

       EAI_SYSTEM
              Other system error, check errno for details.
```

It would be more appropriate to return  EAI_SYSTEM in case of internal failure rather than claiming the host does not exist. That would give the caller the option to retry or react in other ways. Similarily I saw cases when errno is set to ETIMEDOUT but the result code is also set to EAI_NONAME. In such case, EAI_AGAIN would be more appropriate. 
Note that the use of errno is documented only for EAI_SYSTEM. I noticed them with debug statements and dbus-monitor. From caller prospective EAI_NONAME means host does not exit and blindly do any retry does not seems to make sense. 
   

**Steps to reproduce the problem**
So far, I can reproduce the EINVAL only while running our HTTP test suite. The rest of the behavior can be probably simulated by pointing to a slow or nonexistent DNS server and observing results codes from getaddrinfo().

cc: @tmds

**Comment by keszybz** [comment] 2020-03-11 08:28
The same as in #15075, this version is too old. There have been a bunch of fixes to this code in the meantime, in particular 8baaf650ef68a7def4f867e6ca3ff606783ea42f could be relevant. If you can reproduce the issue with systemd>=243, we can reopen.

**Comment by wfurt** [comment] 2020-03-11 18:04
ok. I'll try to rebuild systemd from current repro and I'll give it try. 

I was also able to finally catch that with debug logs on. I'm posting just for completeness. 
(it takes significantly more time to reproduce) 

```
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Positive cache hit for corefx-net-http2.azurewebsites.net IN A
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Transaction 48654 for <corefx-net-http2.azurewebsites.net IN A> on scope dns on */* now complete with <success> from cache (unsigned).
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Positive cache hit for corefx-net-http2.azurewebsites.net IN AAAA
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Transaction 52259 for <corefx-net-http2.azurewebsites.net IN AAAA> on scope dns on */* now complete with <success> from cache (unsigned).
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Freeing transaction 48654.
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Freeing transaction 52259.
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Following CNAME/DNAME corefx-net-http2.azurewebsites.net → waws-prod-bay-047.vip.azurewebsites.windows.net.
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.2006985 path=n/a interface=n/a member=n/a cookie=355308 reply_cookie=702932 signature=n/a error-name=n/a error-message=n/a
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0=':1.2182731' successfully installed.
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.2006985 path=n/a interface=n/a member=n/a cookie=355310 reply_cookie=702934 signature=n/a error-name=n/a error-message=n/a
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0=':1.2182732' successfully installed.
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Processing incoming packet on transaction 26251. (rcode=SUCCESS)
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Added positive unauthenticated cache entry for waws-prod-bay-047.vip.azurewebsites.windows.net IN CNAME 221s on */INET/10.50.50.50
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Added positive unauthenticated cache entry for waws-prod-bay-047.cloudapp.net IN A 48s on */INET/10.50.50.50
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Transaction 26251 for <waws-prod-bay-047.vip.azurewebsites.windows.net IN A> on scope dns on */* now complete with <success> from network (unsigned).
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Processing incoming packet on transaction 43019. (rcode=SUCCESS)
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Not caching zero TTL cache entry: waws-prod-bay-047.vip.azurewebsites.windows.net IN CNAME
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Transaction 43019 for <waws-prod-bay-047.vip.azurewebsites.windows.net IN AAAA> on scope dns on */* now complete with <success> from network (unsigned).
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Sent message type=error sender=n/a destination=:1.2182731 path=n/a interface=n/a member=n/a cookie=702936 reply_cookie=2 signature=s error-name=org.freedesktop.DBus.Error.InvalidArgs error-message=Lookup failed due to system error: Invalid argument
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RemoveMatch cookie=702937 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Freeing transaction 26251.
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Sent message type=error sender=n/a destination=:1.2182732 path=n/a interface=n/a member=n/a cookie=702938 reply_cookie=2 signature=s error-name=org.freedesktop.DBus.Error.InvalidArgs error-message=Lookup failed due to system error: Invalid argument
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RemoveMatch cookie=702939 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Mar 11 00:34:46 net-dale systemd-resolved[17568]: Freeing transaction 43019.
```

**Comment by tmds** [comment] 2020-03-11 21:40
> 8baaf65 could be relevant.

The error that shows up here `org.freedesktop.DBus.Error.InvalidArgs` is not in the `bus_error_shall_fallback` list.

The error-message is `error-message=Lookup failed due to system error: Invalid argument`, may be same issue as https://github.com/systemd/systemd/issues/9690.

**Comment by wfurt** [comment] 2020-03-12 15:44
Is three RH/Centos/Fedora version containing the fix @tmds?

**Comment by tmds** [comment] 2020-03-13 22:52
@wfurt Fedora 31 has systemd 243, which includes https://github.com/systemd/systemd/commit/8baaf650ef68a7def4f867e6ca3ff606783ea42f.
I think this commit will fix the case in https://github.com/dotnet/runtime/issues/33145 where you observe `org.freedesktop.DBus.Error.Timeout` (it is added in the commit).
It won't fix the case where you observe `org.freedesktop.DBus.Error.InvalidArgs`. That case is probably the same issue as https://github.com/systemd/systemd/issues/9690.

**Comment by poettering** [comment] 2020-11-11 15:25
So I am pretty sure this has been fixed by fd8a30170342cfe245ea6acac392c2b224f0ae1b. Please verify. If not, please reopen.

**Closed as completed by poettering** 2020-11-11 15:25 UTC
Labels: resolve

**Comment by wfurt** [comment] 2020-11-11 19:02
thanks for update @poettering. Do you know what RH derived distro have the fix @tmds?  (or possibly when?)

**Comment by tmds** [comment] 2020-11-12 12:56
@wfurt from the tags it looks like this will be part of the _next_ systemd release, which is v247.
