### ISSUE TITLE
networkd: multiple netdev drop-in files with [WireGuardPeer] sections overwrite each other instead of configuring multiple peers

### ISSUE THREAD

**Issue by scolby33** [systemd/systemd#18241] opened 2021-01-13 18:27 UTC
**systemd version the issue has been seen with**
 > systemd 241
(I am aware that this is an older version, but from a reading of the changelog I think this is still an issue. Please read on before closing.)

**Used distribution**
 > Debian 10

**Linux kernel version used** (`uname -a`)
 > `Linux hostname 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Multiple drop-in files in a netdev drop-in dir, each with a  `[WireGuardPeer]` section, should configure multiple peers
(I think, because in WireGuard peers are effectively identified by only their public keys, "conflicting" `[WireGuardPeer]` sections should overwrite each other in lexical order if they have matching keys, but should create new peers if the pubkeys do not match.)

**Unexpected behaviour you saw**
 > Only one peer is configured, with the public key and preshared key from the lexically last of the drop-in files and the union of the allowed IPs

**Steps to reproduce the problem**

(Note: I am using newly generated keys for the examples here, for ease of copy-pasting to reproduce. I am not revealing my actual in-use keys.)

1. create `/etc/systemd/network/99-wg0.netdev` with the contents
```
[NetDev]
Name=wg0
Kind=wireguard

[WireGuard]
ListenPort=51820
```
2. create `/etc/systemd/network/99-wg0.netdev.d/private_key.conf` with the contents
```
[WireGuard]
PrivateKey=QFKTUI6QyJl9DAEauZD7mJl1ontXCcUYxB3Kvz3qrmk=
```
3. create `/etc/systemd/network/99-wg0.netdev.d/peer1.conf` with the contents
```
[WireGuardPeer]
PublicKey=TTiCUpCxS7zDn/ax4p5W6Evg41r8hOrnWQw2Sq6Nh10=
PresharedKey=it7nd33chCT/tKT2ZZWfYyp43Zs+6oif72hexnSNMqA=

AllowedIPs=172.16.0.2
```
4. create `/etc/systemd/network/99-wg0.netdev.d/peer2.conf` with the contents
```
[WireGuardPeer]
PublicKey=9uioxkGzjvGjkse3V35I9AhorWfIjBcrf3UPMS0bw2c=
PresharedKey=6Fsg8XN0DE6aPQgAX4r2oazEYJOGqyHUz3QRH/jCB+I=

AllowedIPs=172.16.0.3
```
5. create `/etc/systemd/network/99-wg0.network` with the contents
```
[Match]
Name=wg0

[Network]
Address=172.16.0.1/24
```
6. restart systemd-networkd
7. observe the resulting wireguard configuration
```console
# wg
interface: wg0
  public key: 4cYBxtX61RHBRYUqohC+4T4jE0sFU68iw/IdlEgtZFQ=
  private key: (hidden)
  listening port: 51820

peer: 9uioxkGzjvGjkse3V35I9AhorWfIjBcrf3UPMS0bw2c=  # the public key from peer2.conf
  preshared key: (hidden)
  allowed ips: 172.16.0.2/32, 172.16.0.3/32
```

I think this is related to #5141. I tried the workaround from there, padding one of the `peer?.conf` files with leading newlines, but this did not change the observed results. I know this is an older version of systemd than is current, but given that the fix for #5141 was merged in 2017 and I am on a version from 2019, I think that fix doesn't solve this issue. Further, an examination of the NEWS file didn't reveal any related changes between version 241 and now.

**Comment by yuwata** [comment] 2021-02-22 07:59
Sorry for late. But I cannot reproduce this. See #18724.

> systemd 241
(I am aware that this is an older version, but from a reading of the changelog I think this is still an issue. Please read on before closing.)

Unfortunately, v241 is too old here. And the NEWS file only announces new feature or backward compatibility, but not any bug fixes. Please test recent release, or contact your downstream (in your case, Debian bug tracker) to find and backport relevant fixes. Sorry.

**Closed as completed** 2021-02-22 12:33 UTC
Labels: network, version-too-ancient, cant-reproduce

**Comment by scolby33** [comment] 2021-02-22 19:20
That's for letting me know! Since I was able to work around it by templating my netdev configs together, I didn't bother going further with installing a more-up-to-date version, which maybe I should have. I'm glad it's fixed!
