### ISSUE TITLE
journalctl -b -N shows logs from incorrect boot

### ISSUE THREAD

**Issue by jazik** [systemd/systemd#30123] opened 2023-11-21 15:14 UTC
### systemd version the issue has been seen with

254

### Used distribution

Fedora 39

### Linux kernel version used

6.5.2-301.fc39.x86_64

### CPU architectures issue was seen on

x86_64

### Component

journalctl

### Expected behaviour you didn't see

The `journalctl -b -1` should list logs from previous boot. With `-b -N` it should show N-th boot.

### Unexpected behaviour you saw

With v254 the `journalclt -b -1` either fails if only one reboot was executed or it displays logs from different older boot. The same behavior is with other `-b -N` values.

### Steps to reproduce the problem

1. Start Fedora 39, for example a qcow2 server image under qemu/kvm.
2. Reboot the vm with `reboot` command
3. Try to list logs of previous boot with `journalctl -b -1` following error will occur:

```
[root@waders ~]# journalctl -b -1
No journal boot entry found from the specified boot offset (-1).
```

The `--list-boots` lists expected boot:

```
[root@waders ~]# journalctl --list-boots
IDX BOOT ID                          FIRST ENTRY                 LAST ENTRY                 
 -1 a82fc6ae45504e278c35c85b9d9a0489 Tue 2023-11-21 16:52:52 EET Tue 2023-11-21 16:53:23 EET
  0 3f7b751115604a60932f59ff2f9d28dc Tue 2023-11-21 16:53:52 EET Tue 2023-11-21 16:58:13 EET
```

If more reboots are done then the `-b -N` shows older boots' logs, sometimes every other boot is skipped, sometimes not. The behavior is not completely consistent. For example after 5 reboots:

```
[root@waders ~]# journalctl --list-boots
IDX BOOT ID                          FIRST ENTRY                 LAST ENTRY                 
 -4 a82fc6ae45504e278c35c85b9d9a0489 Tue 2023-11-21 16:52:52 EET Tue 2023-11-21 16:53:23 EET
 -3 3f7b751115604a60932f59ff2f9d28dc Tue 2023-11-21 16:53:52 EET Tue 2023-11-21 16:59:49 EET
 -2 0f9410bcf14a4e8ead3a3b16acec0533 Tue 2023-11-21 17:00:19 EET Tue 2023-11-21 17:00:57 EET
 -1 f2a8abfba2894fffb81c568b9c1c9012 Tue 2023-11-21 17:01:26 EET Tue 2023-11-21 17:03:15 EET
  0 f8c480c94cc7463da561a7d3a5234b3b Tue 2023-11-21 17:03:45 EET Tue 2023-11-21 17:04:07 EET
```

The `-b -1` shows logs from boot -2, `-b -2` shows logs from boot -4 and `-b -3` fails:

```
[root@waders ~]# journalctl -b -1 | tail -n 1
Nov 21 17:00:57 waders.novalocal systemd-journald[571]: Journal stopped
[root@waders ~]# journalctl -b -2 | tail -n 1
Nov 21 16:53:23 waders.novalocal systemd-journald[570]: Journal stopped
[root@waders ~]# journalctl -b -3 | tail -n 1
No journal boot entry found from the specified boot offset (-3).
```

This works with systemd v253. I did try to debug this with gdb and the problem is somewhere in `sd_journal_previous()` which with single reboot returns end of journal with second iteration.

Looking for changes in `sd-journal.c` between v253 and v254 there were some modifications how `_BOOT_ID` is searched and compared. Such as 34af74946e8853411f18120007ebaca6549b2a52 and 262299dccbb09f36c8c830dabd6a104469d9852b and there were also changes related to boot id search in `journalctl` such as https://github.com/systemd/systemd/pull/27721.

I was not able to pinpoint what is really causing this, but I'll continue debugging and I'll try to bisect this problem. Reporting this ahead in case someone from maintainers will be faster to figure this out.

**Comment by YHNdnzj** [comment] 2023-11-21 15:17
Duplicate of https://github.com/systemd/systemd/issues/29275 (already fixed in the latest main)

**Comment by jazik** [comment] 2023-11-21 15:25
> Duplicate of #29275 (already fixed in the latest main)

Ah thanks! I did try to search for the issue by failed to find it.

**Comment by jazik** [comment] 2023-11-21 15:34
Seems there were rather many commits trying to fix this ... is there any simple way to get patchset for v254 somewhere?

**Closed as not planned** 2023-11-21 15:36 UTC
Labels: bug 🐛, journal, duplicate, already-fixed
