### ISSUE TITLE
resolvectl dns does not completely set per-interface DNS server address

### ISSUE THREAD

**Issue by elie-delorme** [systemd/systemd#22488] opened 2022-02-12 00:09 UTC
**systemd version the issue has been seen with**
 > systemd 248 (248.3-1ubuntu8.2)

**Used distribution**
 > Ubuntu 21.10 impish

**Linux kernel version used** (`uname -a`)

 > `Linux CH0013-P 5.13.0-28-generic #31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > "resolvectl dns" should replace dns server on the specified interface

**Unexpected behaviour you saw**
 > "resolvectl dns" only replaces one dns server if any already exist

**Steps to reproduce the problem**
>1. Have an interface with two dns servers (`192.168.2.1 207.164.234.129`)
>2. Replace dns servers with resolvectl (for example: `resolvectl dns 2 1.1.1.1 8.8.8.8`)
>3. There are now 3 dns servers instead of the two expected (`207.164.234.129 1.1.1.1 8.8.8.8`)

**Additional program output to the terminal or log subsystem illustrating the issue**

```journalctl -u systemd-resolved -f
-- Journal begins at Thu 2021-11-25 12:58:52 EST. --
Feb 11 19:01:43 CH0013-P systemd-resolved[60574]: enp11s0: Bus client set DNS server list to: 192.168.2.1, 207.164.234.129
Feb 11 19:01:43 CH0013-P systemd[1]: Stopping Network Name Resolution...
Feb 11 19:01:43 CH0013-P systemd[1]: systemd-resolved.service: Deactivated successfully.
Feb 11 19:01:43 CH0013-P systemd[1]: Stopped Network Name Resolution.
Feb 11 19:01:43 CH0013-P systemd[1]: Starting Network Name Resolution...
Feb 11 19:01:43 CH0013-P systemd-resolved[60584]: Positive Trust Anchors:
Feb 11 19:01:43 CH0013-P systemd-resolved[60584]: . IN DS 20326 8 2 e06d44b80b8f1d39a95c0b0d7c65d08458e880409bbc683457104237c7f8ec8d
Feb 11 19:01:43 CH0013-P systemd-resolved[60584]: Negative trust anchors: home.arpa 10.in-addr.arpa 16.172.in-addr.arpa 17.172.in-addr.arpa 18.172.in-addr.arpa 19.172.in-addr.arpa 20.172.in-addr.arpa 21.172.in-addr.arpa 22.172.in-addr.arpa 23.172.in-addr.arpa 24.172.in-addr.arpa 25.172.in-addr.arpa 26.172.in-addr.arpa 27.172.in-addr.arpa 28.172.in-addr.arpa 29.172.in-addr.arpa 30.172.in-addr.arpa 31.172.in-addr.arpa 168.192.in-addr.arpa d.f.ip6.arpa corp home internal intranet lan local private test
Feb 11 19:01:43 CH0013-P systemd-resolved[60584]: Using system hostname 'CH0013-P'.
Feb 11 19:01:43 CH0013-P systemd[1]: Started Network Name Resolution.
Feb 11 19:02:49 CH0013-P systemd-resolved[60584]: enp11s0: Bus client set DNS server list to: 1.1.1.1, 8.8.8.8
…
```
```
$ resolvectl dns
Global:
Link 2 (enp11s0): 192.168.2.1 207.164.234.129
$ sudo resolvectl dns 2 1.1.1.1 8.8.8.8
$ resolvectl dns
Global:
Link 2 (enp11s0): 207.164.234.129 1.1.1.1 8.8.8.8
…
```

**Comment by yuwata** [comment] 2022-02-13 13:54
Maybe duplicate of #19651, which is fixed by a77f9dfbaed2e49269b42222da0d1c8680057fa6 (v249)?

**Comment by elie-delorme** [comment] 2022-02-14 17:48
@yuwata I compile source from git tag ubuntu/248.3-1ubuntu8.2 with that commit added and it resolved the issue, thank you

**Comment by yuwata** [comment] 2022-02-14 18:08
Thank you for the confirmation! Closing.

**Closed as completed by yuwata** 2022-02-14 18:08 UTC
Labels: resolve, needs-reporter-feedback ❓, duplicate
