### ISSUE TITLE
udev 60-persistent-input.rules missing ID_INPUT_POINTINGSTICK class name

### ISSUE THREAD

**Issue by twshield** [systemd/systemd#18356] opened 2021-01-23 19:29 UTC
Using Fedora 33 with package systemd-udev-246.7-2.fc33.x86_64

/dev/input/by-path (and by-id, but that is not a udev problem*) entries are missing for my pvr-150 video capture card's IR remote input.

Dmesg output:

[    6.885262] rc rc0: Hauppauge WinTV PVR-150 as /devices/pci0000:00/0000:00:1c.6/0000:04:00.0/0000:05:00.0/i2c-9/9-0071/rc/rc0
[    6.888219] rc rc0: lirc_dev: driver ir_kbd_i2c registered at minor = 0, scancode receiver, raw IR transmitter
[    6.888276] input: Hauppauge WinTV PVR-150 as /devices/pci0000:00/0000:00:1c.6/0000:04:00.0/0000:05:00.0/i2c-9/9-0071/rc/rc0/input33

Running (without my addition in place)
udevadm test /sys/class/input/event27

gives:

DEVPATH=/devices/pci0000:00/0000:00:1c.6/0000:04:00.0/0000:05:00.0/i2c-9/9-0071/rc/rc0/input33/event27
DEVNAME=/dev/input/event27
MAJOR=13
MINOR=91
ACTION=add
SUBSYSTEM=input
ID_INPUT=1
ID_INPUT_POINTINGSTICK=1
ID_INPUT_KEY=1
ID_PATH=pci-0000:05:00.0
ID_PATH_TAG=pci-0000_05_00_0
.rc_sysdev=rc0
TAGS=:power-switch:
LIBINPUT_DEVICE_GROUP=18/0/0:i2c-9/9-0071
USEC_INITIALIZED=8015844
run: '/usr/bin/ir-keytable -a /etc/rc_maps.cfg -s rc0'
 
looking at /usr/lib/udev/rules.d/60-persistent-input.rules

The top of the file has 
\# determine class name for persistent symlinks
ENV{ID_INPUT_KEYBOARD}=="?*", ENV{.INPUT_CLASS}="kbd"
ENV{ID_INPUT_MOUSE}=="?*", ENV{.INPUT_CLASS}="mouse"
ENV{ID_INPUT_TOUCHPAD}=="?*", ENV{.INPUT_CLASS}="mouse"
ENV{ID_INPUT_TABLET}=="?*", ENV{.INPUT_CLASS}="mouse"
ENV{ID_INPUT_JOYSTICK}=="?*", ENV{.INPUT_CLASS}="joystick"

but no line for ID_INPUT_POINTINGSTICK (which is set for i2c devices in udev-builtin-input_id.c) .  So I added 

ENV{ID_INPUT_POINTINGSTICK}=="?*", ENV{.INPUT_CLASS}="ir"

after the ID_INPUT_JOYSTICK line and now I get a by-path entry:

lrwxrwxrwx 1 root root 10 Jan 23 13:05 pci-0000:05:00.0-event-ir -> ../event27

I made it "ir" class, but it could also be 'kbd" class.  I don't know what the criteria are for them, so I picked "ir"

\* driver lacks ID_SERIAL information needed by udev.

**Comment by poettering** [comment] 2021-01-25 17:24
"ir" is an implementation detail i guess, while these classifiers so far tried to express what kind of device it is we are seeing, not how it is connected. That said, I have no idea about IR hw, maybe we can't actually categorize things properly this way?

Either wa,y please submit patches as PR, not as issue, if you want them merged. Otherwise they will just linger here..

**Comment by Dewinsy** [comment] 2022-04-03 17:20
@twshield, I am an outreachy intern and while considering working on this issue, I noticed there was a pull request merged in Feb 2021. Here is a [link](https://github.com/twshield/systemd/pull/1/files) to the merged PR. I wonder if we should close the issue?

**Comment by poettering** [comment] 2022-04-04 09:43
@Dewinsy that's not a PR merged into our main systemd tree

**Comment by poettering** [comment] 2022-04-04 09:47
That said, the issue is apparently fixed, i.e. #18523 was posted and then this was found out:

https://github.com/systemd/systemd/pull/18523#issuecomment-785412335

Which was then implemented in #18808 which was then merged.

Hence I assume this has already been fixed now. Closing hence. (If not, @twshield please reopen, and explain)

**Closed as completed by poettering** 2022-04-04 09:47 UTC
Labels: udev, please-submit-as-pr

**Comment by twshield** [comment] 2022-04-04 14:23
Sorry for not getting back to you. The real issue is that the kernel driver
for remotes erroneously marks them all as having pointing sticks.

So closing it was ok.

Tom

Tom Shield
Vadnais Heights, MN
sent from my tablet, odd words due to auto confuse
