### ISSUE TITLE
At some point during boot, status messages are not shown on console

### ISSUE THREAD

**Issue by utezduyar** [systemd/systemd#5070] opened 2017-01-12 07:26 UTC
### Submission type

  - [x] Bug report

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

systemd 231
-PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK -SYSVINIT -UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS -ACL -XZ -LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Yocto

### In case of bug report: Expected behaviour you didn't see

I have set ShowStatus=yes (with kernel command line quiet). During boot, systemd decides to stop printing status messages on the console. But the messages can still be retrieved from journal. It is random when systemd decides to stop printing.
Our default.target is streaming.target which through a service files starts multi-user.target. Does this have anything to do with the bug?

I have following 2 screen shots (grep of Started messages) where I compare the console output (right) with journal (left). Systemd stops printing on console at different times on both screenshots. 
![screen shot 2016-12-21 at 1 16 12 pm](https://cloud.githubusercontent.com/assets/8062069/21880657/64afe0e0-d8a0-11e6-8135-0df9be38f5cb.png)
![screen shot 2016-12-21 at 1 31 08 pm](https://cloud.githubusercontent.com/assets/8062069/21880658/64b0ecce-d8a0-11e6-9804-b023478c6ec1.png)

This bug is a deviation of https://github.com/systemd/systemd/issues/4899.

**Comment by poettering** [comment] 2017-01-12 09:34
We only do console status output while we are booting up or shutting down. And that's defined by not having any jobs queued anymore/having the shutdown job queued. Now, depending on your unit types and ordering this means the point in time where we stop/start console output while well-defined might appear at different times as unit state changes might happen independendtly of the job queue running empty.

**Comment by poettering** [comment] 2017-01-12 09:40
Closing, because this is not a bug.

**Closed as completed by poettering** 2017-01-12 09:40 UTC
Labels: pid1, not-a-bug
