### ISSUE TITLE
systemd: «systemd-analyze plot» -  unknown return code 1.

### ISSUE THREAD

**Issue by locaIhost** [systemd/systemd#26766] opened 2023-03-12 03:41 UTC
### systemd version the issue has been seen with

249

### Used distribution

Ubuntu 22.04.1 LTS

### Linux kernel version used

5.15.0-46-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-analyze

### Expected behaviour you didn't see

Failed to launch systemd-analyze having the key a plot
`systemd-analyze plot`
using the `blame` key does not cause problems.

### Unexpected behaviour you saw

Failed to get timestamp properties: Launch helper exited with unknown return code 1.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
small part of output strace.
-
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/liblzma.so.5", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=170456, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 172296, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ff035d1d000
mmap(0x7ff035d20000, 110592, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7ff035d20000
mmap(0x7ff035d3b000, 45056, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1e000) = 0x7ff035d3b000
mmap(0x7ff035d46000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x28000) = 0x7ff035d46000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libpcre2-8.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=613064, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 615184, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ff035c86000
mmap(0x7ff035c88000, 438272, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7ff035c88000
mmap(0x7ff035cf3000, 163840, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x6d000) = 0x7ff035cf3000
mmap(0x7ff035d1b000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x94000) = 0x7ff035d1b000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libcap-ng.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=27072, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 28992, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ff035c7e000
mmap(0x7ff035c80000, 12288, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7ff035c80000
mmap(0x7ff035c83000, 4096, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x5000) = 0x7ff035c83000
mmap(0x7ff035c84000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x5000) = 0x7ff035c84000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libgpg-error.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=149760, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 151992, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7ff035c58000
mmap(0x7ff035c5c000, 90112, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4000) = 0x7ff035c5c000
mmap(0x7ff035c72000, 40960, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1a000) = 0x7ff035c72000
mmap(0x7ff035c7c000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x23000) = 0x7ff035c7c000
close(3)                                = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff035c56000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff035c54000
arch_prctl(ARCH_SET_FS, 0x7ff035c55400) = 0
set_tid_address(0x7ff035c556d0)         = 283492
set_robust_list(0x7ff035c556e0, 24)     = 0
rseq(0x7ff035c55da0, 0x20, 0, 0x53053053) = 0
mprotect(0x7ff03667c000, 16384, PROT_READ) = 0
mprotect(0x7ff035c7c000, 4096, PROT_READ) = 0
mprotect(0x7ff035c84000, 4096, PROT_READ) = 0
mprotect(0x7ff035d1b000, 4096, PROT_READ) = 0
mprotect(0x7ff035d46000, 4096, PROT_READ) = 0
mprotect(0x7ff035e15000, 4096, PROT_READ) = 0
mprotect(0x7ff0361fa000, 372736, PROT_READ) = 0
mprotect(0x7ff036279000, 4096, PROT_READ) = 0
mprotect(0x7ff036295000, 4096, PROT_READ) = 0
mprotect(0x7ff03629f000, 4096, PROT_READ) = 0
mprotect(0x7ff0363d5000, 12288, PROT_READ) = 0
mprotect(0x7ff03640f000, 4096, PROT_READ) = 0
mprotect(0x7ff036424000, 4096, PROT_READ) = 0
mprotect(0x7ff036457000, 20480, PROT_READ) = 0
mprotect(0x7ff036465000, 4096, PROT_READ) = 0
mprotect(0x7ff0366a2000, 4096, PROT_READ) = 0
mprotect(0x7ff0366c4000, 4096, PROT_READ) = 0
mprotect(0x7ff0366e4000, 4096, PROT_READ) = 0
mprotect(0x7ff036752000, 4096, PROT_READ) = 0
mprotect(0x7ff036728000, 4096, PROT_READ) = 0
mprotect(0x7ff036774000, 4096, PROT_READ) = 0
mprotect(0x7ff036a36000, 77824, PROT_READ) = 0
mprotect(0x561fafaed000, 335872, PROT_READ) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7ff035c52000
mprotect(0x7ff036a86000, 8192, PROT_READ) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
munmap(0x7ff036776000, 122823)          = 0
getrandom("\xdb\xc5\x66\xa6\xc4\x92\x7b\x1b", 8, GRND_NONBLOCK) = 8
brk(NULL)                               = 0x561fb0e62000
brk(0x561fb0e83000)                     = 0x561fb0e83000
prctl(PR_CAPBSET_READ, CAP_MAC_OVERRIDE) = 1
prctl(PR_CAPBSET_READ, 0x30 /* CAP_??? */) = -1 EINVAL (Invalid argument)
prctl(PR_CAPBSET_READ, CAP_CHECKPOINT_RESTORE) = 1
prctl(PR_CAPBSET_READ, 0x2c /* CAP_??? */) = -1 EINVAL (Invalid argument)
prctl(PR_CAPBSET_READ, 0x2a /* CAP_??? */) = -1 EINVAL (Invalid argument)
prctl(PR_CAPBSET_READ, 0x29 /* CAP_??? */) = -1 EINVAL (Invalid argument)
statfs("/sys/fs/selinux", 0x7ffc43d60f10) = -1 ENOENT (No such file or directory)
statfs("/selinux", 0x7ffc43d60f10)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/proc/filesystems", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0444, st_size=0, ...}, AT_EMPTY_PATH) = 0
read(3, "nodev\tsysfs\nnodev\ttmpfs\nnodev\tbd"..., 1024) = 438
read(3, "", 1024)                       = 0
close(3)                                = 0
access("/etc/selinux/config", F_OK)     = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/locale/locale-archive", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=14575936, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 14575936, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7ff034e6b000
close(3)                                = 0
getpid()                                = 283492
faccessat2(AT_FDCWD, "/run/systemd/system/", F_OK, AT_SYMLINK_NOFOLLOW) = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
getsockopt(3, SOL_SOCKET, SO_RCVBUF, [212992], [4]) = 0
setsockopt(3, SOL_SOCKET, SO_RCVBUF, [8388608], 4) = 0
getsockopt(3, SOL_SOCKET, SO_RCVBUF, [425984], [4]) = 0
setsockopt(3, SOL_SOCKET, SO_RCVBUFFORCE, [8388608], 4) = 0
getsockopt(3, SOL_SOCKET, SO_SNDBUF, [212992], [4]) = 0
setsockopt(3, SOL_SOCKET, SO_SNDBUF, [8388608], 4) = 0
getsockopt(3, SOL_SOCKET, SO_SNDBUF, [425984], [4]) = 0
setsockopt(3, SOL_SOCKET, SO_SNDBUFFORCE, [8388608], 4) = 0
connect(3, {sa_family=AF_UNIX, sun_path="/run/dbus/system_bus_socket"}, 30) = 0
getsockopt(3, SOL_SOCKET, SO_PEERCRED, {pid=213566, uid=0, gid=0}, [12]) = 0
getsockopt(3, SOL_SOCKET, SO_PEERSEC, "unconfined", [64 => 10]) = 0
getsockopt(3, SOL_SOCKET, SO_PEERGROUPS, [0], [256 => 4]) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=12323, tv_nsec=685288520}) = 0
newfstatat(3, "", {st_mode=S_IFSOCK|0777, st_size=0, ...}, AT_EMPTY_PATH) = 0
getsockopt(3, SOL_SOCKET, SO_ACCEPTCONN, [0], [4]) = 0
getsockname(3, {sa_family=AF_UNIX}, [128 => 2]) = 0
sendmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\0AUTH EXTERNAL\r\nDATA\r\n", iov_len=22}, {iov_base="NEGOTIATE_UNIX_FD\r\n", iov_len=19}, {iov_base="BEGIN\r\n", iov_len=7}], msg_iovlen=3, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 48
gettid()                                = 283492
getrandom("\xbb\xf3\xea\x2b\x40\x5f\x48\xa5\x30\x93\x50\xec\x81\xe7\xd4\xb2", 16, GRND_NONBLOCK|GRND_INSECURE) = 16
futex(0x7ff036a4a1d0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
gettid()                                = 283492
clock_gettime(CLOCK_MONOTONIC, {tv_sec=12323, tv_nsec=685928219}) = 0
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="DATA\r\nOK e40bd40f0f1342bd36a01ab"..., iov_len=256}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = 58
clock_gettime(CLOCK_MONOTONIC, {tv_sec=12323, tv_nsec=686064050}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=12323, tv_nsec=686120477}) = 0
sendmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\1\0\1\0\0\0\0\1\0\0\0m\0\0\0\1\1o\0\25\0\0\0/org/fre"..., iov_len=128}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 128
clock_gettime(CLOCK_MONOTONIC, {tv_sec=12323, tv_nsec=686249674}) = 0
recvmsg(3, {msg_namelen=0}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
clock_gettime(CLOCK_MONOTONIC, {tv_sec=12323, tv_nsec=686370072}) = 0
ppoll([{fd=3, events=POLLIN}], 1, {tv_sec=24, tv_nsec=999694000}, NULL, 8) = 1 ([{fd=3, revents=POLLIN}], left {tv_sec=24, tv_nsec=999662015})
clock_gettime(CLOCK_MONOTONIC, {tv_sec=12323, tv_nsec=686528320}) = 0
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\2\1\1\v\0\0\0\1\0\0\0=\0\0\0\6\1s\0\6\0\0\0", iov_len=24}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = 24
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base=":1.119\0\0\5\1u\0\1\0\0\0\10\1g\0\1s\0\0\7\1s\0\24\0\0\0"..., iov_len=67}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = 67
sendmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\1\0\1\5\0\0\0\2\0\0\0\217\0\0\0\1\1o\0\31\0\0\0/org/fre"..., iov_len=160}, {iov_base="\0\0\0\0\0", iov_len=5}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 165
clock_gettime(CLOCK_MONOTONIC, {tv_sec=12323, tv_nsec=686842164}) = 0
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\4\1\1\v\0\0\0\2\0\0\0\215\0\0\0\1\1o\0\25\0\0\0", iov_len=24}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = 24
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="/org/freedesktop/DBus\0\0\0\2\1s\0\24\0\0\0"..., iov_len=147}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = 147
recvmsg(3, {msg_namelen=0}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
clock_gettime(CLOCK_MONOTONIC, {tv_sec=12323, tv_nsec=687098742}) = 0
ppoll([{fd=3, events=POLLIN}], 1, {tv_sec=24, tv_nsec=999744000}, NULL, 8) = 1 ([{fd=3, revents=POLLIN}], left {tv_sec=24, tv_nsec=995762502})
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\3\1\0014\0\0\0\3\0\0\0u\0\0\0\6\1s\0\6\0\0\0", iov_len=24}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = 24
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base=":1.119\0\0\4\1s\0,\0\0\0org.freedesktop."..., iov_len=164}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = 164
ioctl(1, TCGETS, {B38400 opost isig icanon echo ...}) = 0
ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
writev(2, [{iov_base="\33[0;1;31m", iov_len=9}, {iov_base="Failed to get timestamp properti"..., iov_len=83}, {iov_base="\33[0m", iov_len=4}, {iov_base="\n", iov_len=1}], 4Failed to get timestamp properties: Launch helper exited with unknown return code 1
) = 97
close(3)                                = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```

**Comment by yuwata** [comment] 2023-03-12 05:40
Sorry, here is an upstream issue tracker, and v249 is too old here. Please contact to your downstream.

Or, please try to reproduce the issue with one of a recent release (v252 or v253), or the current git HEAD.
If you find that the issue is still reproducible in the recent release, then please provide the result of
```
SYSTEMD_LOG_LEVEL=debug systemd-analyze plot
```

Closing, at least tentatively. Feel free to request to reopen this page.

**Closed as completed by yuwata** 2023-03-12 05:40 UTC
Labels: bug 🐛, analyze, version-too-ancient
