### ISSUE TITLE
Feature request: Add ability to show logs directly with `systemctl start unit` 

### ISSUE THREAD

**Issue by phiresky** [systemd/systemd#16502] opened 2020-07-17 13:44 UTC
**Is your feature request related to a problem? Please describe.**

Currently, when a unit fails at startup, this is displayed:

```
Job for foobar.service failed because the control process exited with error code.
See "systemctl status foobar.service" and "journalctl -xe" for details.
```

It would be useful if it could just show the corresponding logs instead of referring to a different command - especially when editing unit files this quickly becomes tedious. The same goes if it succeeds - it is often still useful to see the output.

**Describe the solution you'd like**

* add an argument like `--status` or `--logs` or `--follow` to `start`, so that `systemctl start --logs foobar` is equivalent to `journalctl -f -u foobar & systemctl start foobar`, or maybe to `systemctl start foobar && systemctl status foobar`. Possibly distinguish between only showing the logs during startup and then exiting vs keeping it open "forever" like `--wait`.

* possibly outputting the error log by default if it fails instead of referring to `journalctl`.

**Describe alternatives you've considered**
Opening another terminal with `journalctl -f -u foobar` and watching that output. Or running `systemctl status foobar` afterwards.

**Comment by poettering** [comment] 2020-07-21 10:06
Duplicate of #1287

**Closed as completed** 2020-07-21 10:21 UTC
Labels: RFE 🎁, systemctl, duplicate
