### ISSUE TITLE
sysext refresh stopped because of a bad file

### ISSUE THREAD

**Issue by CorrectRoadH** [systemd/systemd#32965] opened 2024-05-22 02:46 UTC
### systemd version the issue has been seen with

systemd 252 (252.5-2ubuntu3.2)

### Used distribution

Ubuntu 23.04

### Linux kernel version used

6.2.0-39-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-sysext

### Expected behaviour you didn't see

Expected sysext ignore not incorrect extension files.
like in `/var/lib/extensions` have two files `a.raw` and `b.raw`. a is a valid extension file. but b.raw is a blank file.

execute `systemd-sysext refresh`. the a.raw be mount.

### Unexpected behaviour you saw

execute `systemd-sysext refresh`. throw error `Failed to read metadata for image b: Package not installed`. a is not be mounted.

### Steps to reproduce the problem

1. copy a correct files to /var/lib/extensions/
2. touch b.raw in ` /var/lib/extensions/`
3. chmod +x  b.raw
4. systemd-sysext refresh

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
😂I don't know the problem is a feature or a bug.
```

**Comment by yuwata** [comment] 2024-05-22 04:51
Fix is waiting in #32967.

**Comment by poettering** [comment] 2024-05-22 07:19
kinda a duplicate of #32762

**Comment by bluca** [comment] 2024-05-22 09:49
Duplicate of https://github.com/systemd/systemd/issues/32762

**Closed as not planned by bluca** 2024-05-22 09:49 UTC
Labels: duplicate, sysext
