### ISSUE TITLE
machinectl shell should default to the user configured shell instead of /bin/sh

### ISSUE THREAD

**Issue by Keruspe** [systemd/systemd#1410] opened 2015-09-30 07:00 UTC
```
keruspe@Lou ~ % machinectl shell                                                
Connected to the local host. Press ^] three times within 1s to exit session.
root@Lou ~ # echo $0
-bin/sh
root@Lou ~ # getent passwd root
root:x:0:0:root:/root:/bin/zsh
```

Currently /bin/sh is started instead of /bin/zsh

**Comment by poettering** [comment] 2015-09-30 09:37
Duplicate of #1395.

**Closed as completed by poettering** 2015-09-30 09:37 UTC
Labels: machine, duplicate
