### ISSUE TITLE
RoutingPolicyRule does not always apply - applies alternately?

### ISSUE THREAD

**Issue by amishmm** [systemd/systemd#11280] opened 2018-12-27 12:07 UTC
**systemd version the issue has been seen with**
> 239.303-1 (had noticed the issue in earlier versions too)

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > Routing rules should remain constantly on networkd restart

**Unexpected behaviour you saw**
 >  Routing rules appear / disappear alternately on networkd restart

**Steps to reproduce the problem**

**Note:** This is long description and seems complicated but if you are comfortable with ip rules then its not complicated. To easily understand please focus on RoutingPolicyRule sections and not Route sections.

I have following config with 1 LAN and 3 WAN connection. 1 of the WAN connection is PPPoE based, however that should not be relevant here.

**25-eth0.network (LAN connection)**
```
[Match]
MACAddress=aa:bb:cc:dd:ee:f1

[Network]
ConfigureWithoutCarrier=true
Address=192.168.0.250/24
```

**25-eth1.network (tata WAN - associated route table number 101)**
```
[Match]
MACAddress=aa:bb:cc:dd:ee:f2

[Network]
ConfigureWithoutCarrier=true
Address=1.1.1.58/30

[Route]
Gateway=1.1.1.57
Metric=20

[Route]
Gateway=1.1.1.57
Table=101
Metric=20

[Route]
Gateway=1.1.1.57
Destination=1.1.1.56/30
Table=101
Metric=20

[RoutingPolicyRule]
From=1.1.1.58
Table=101
Priority=29001

[RoutingPolicyRule]
To=1.1.1.56/30
Table=101
Priority=29002

[RoutingPolicyRule]
FirewallMark=0x101
Table=101
Priority=30001
```

**25-eth2.network (airtel - associated route table number 102)**
```
[Match]
MACAddress=aa:bb:cc:dd:ee:f3

[Network]
ConfigureWithoutCarrier=true
Address=192.168.1.2/24

[Route]
Gateway=192.168.1.1
Metric=20

[Route]
Gateway=192.168.1.1
Table=102
Metric=20

[Route]
Gateway=192.168.1.1
Destination=192.168.1.0/24
Table=102
Metric=20

[RoutingPolicyRule]
From=192.168.1.2
Table=102
Priority=29003

[RoutingPolicyRule]
To=192.168.1.0/24
Table=102
Priority=29004

[RoutingPolicyRule]
FirewallMark=0x102
Table=102
Priority=30002
```

**25-eth3.network (pppoe / pppoelan - associated route table numbers 103 / 104)**

```
[Match]
MACAddress=aa:bb:cc:dd:ee:f4

[Network]
ConfigureWithoutCarrier=true
Address=192.168.5.2/24

[Route]
Gateway=192.168.5.1
Metric=20

[Route]
Gateway=192.168.5.1
Table=104
Metric=20

[Route]
Gateway=192.168.5.1
Destination=192.168.5.0/24
Table=104
Metric=20

[RoutingPolicyRule]
From=192.168.5.2
Table=104
Priority=29005

[RoutingPolicyRule]
To=192.168.5.0/24
Table=104
Priority=29006

[RoutingPolicyRule]
FirewallMark=0x104
Table=104
Priority=30004

# pppd places routes in this table after connection
# is established over PPPoE
[RoutingPolicyRule]
FirewallMark=0x103
Table=103
Priority=30003
```

Now lets see what routing policy rules are created when systemd-networkd starts.

```
$ systemctl start systemd-networkd
$ ip ru l
0:      from all lookup local
28995:  from all to 10.10.10.10 lookup pppoe
28996:  from 11.11.11.11 lookup pppoe
28997:  from all to 192.168.0.0/24 lookup main
29001:  from 1.1.1.58 lookup tata
29002:  from all to 1.1.1.56/30 lookup tata
29003:  from 192.168.1.2 lookup airtel
29004:  from all to 192.168.1.0/24 lookup airtel
29005:  from 192.168.5.2 lookup pppoelan
29006:  from all to 192.168.5.0/24 lookup pppoelan
30001:  from all fwmark 0x101 lookup tata
30002:  from all fwmark 0x102 lookup airtel
30003:  from all fwmark 0x103 lookup pppoe
30004:  from all fwmark 0x104 lookup pppoelan
32766:  from all lookup main
32767:  from all lookup default
```

First three rules above are added by pppd (ip-up script) which you may please ignore. But rest are added by systemd-networkd.

**As we can see, all rules are above are as expected.**

Now lets restart systemd-networkd and check what happens:

```
$ systemctl restart systemd-networkd
$ ip ru l
0:      from all lookup local
28995:  from all to 10.10.10.10 lookup pppoe
28996:  from 11.11.11.11 lookup pppoe
28997:  from all to 192.168.0.0/24 lookup main
29005:  from 192.168.5.2 lookup pppoelan
29006:  from all to 192.168.5.0/24 lookup pppoelan
30001:  from all fwmark 0x101 lookup tata
30002:  from all fwmark 0x102 lookup airtel
30003:  from all fwmark 0x103 lookup pppoe
30004:  from all fwmark 0x104 lookup pppoelan
32766:  from all lookup main
32767:  from all lookup default
```

**Boom!** IP based rules of tata and airtel vanish!! (but fwmark based rules remain)

Lets restart systemd-networkd one more time and check what happens:

```
$ systemctl restart systemd-networkd
$ ip ru l
0:      from all lookup local
28995:  from all to 10.10.10.10 lookup pppoe
28996:  from 11.11.11.11 lookup pppoe
28997:  from all to 192.168.0.0/24 lookup main
29001:  from 1.1.1.58 lookup tata
29002:  from all to 1.1.1.56/30 lookup tata
29003:  from 192.168.1.2 lookup airtel
29004:  from all to 192.168.1.0/24 lookup airtel
29005:  from 192.168.5.2 lookup pppoelan
29006:  from all to 192.168.5.0/24 lookup pppoelan
30001:  from all fwmark 0x101 lookup tata
30002:  from all fwmark 0x102 lookup airtel
30003:  from all fwmark 0x103 lookup pppoe
30004:  from all fwmark 0x104 lookup pppoelan
32766:  from all lookup main
32767:  from all lookup default
```

**BINGO!! And the rules are back!!!**

This is consistent and alternate. One restart they disappear and 2nd restart they appear.

journalctl shows this: (with coredump)
```
$ journalctl --file /var/log/journal/XXXXXXX/system.journal -n 100  -u systemd-networkd.service
-- Logs begin at Mon 2018-12-24 10:10:51 IST, end at Thu 2018-12-27 16:43:05 IST. --
Dec 27 16:28:01 myfw systemd-networkd[31226]: eth0: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: lo: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: eth1: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: ppp1: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: eth0: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: lo: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: ppp1: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: eth0: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: lo: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: ppp1: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: lo: Link is not managed by us
Dec 27 16:28:01 myfw systemd-networkd[31226]: eth2: Could not drop routing policy rule: No such file or directory
Dec 27 16:28:01 myfw systemd-networkd[31226]: eth2: Could not drop routing policy rule: No such file or directory
Dec 27 16:28:02 myfw systemd-networkd[31226]: eth0: Configured
Dec 27 16:28:06 myfw systemd[1]: Stopping Network Service...
Dec 27 16:28:06 myfw systemd[1]: systemd-networkd.service: Main process exited, code=dumped, status=11/SEGV
Dec 27 16:28:06 myfw systemd[1]: systemd-networkd.service: Failed with result 'core-dump'.
Dec 27 16:28:06 myfw systemd[1]: Stopped Network Service.
Dec 27 16:28:06 myfw systemd[1]: Starting Network Service...
Dec 27 16:28:06 myfw systemd-networkd[31243]: eth3: Gained IPv6LL
Dec 27 16:28:06 myfw systemd-networkd[31243]: eth2: Gained IPv6LL
Dec 27 16:28:06 myfw systemd-networkd[31243]: eth1: Gained IPv6LL
Dec 27 16:28:06 myfw systemd-networkd[31243]: eth0: Gained IPv6LL
Dec 27 16:28:06 myfw systemd-networkd[31243]: Enumeration completed
Dec 27 16:28:06 myfw systemd[1]: Started Network Service.
Dec 27 16:28:06 myfw systemd-networkd[31243]: eth1: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: eth0: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: lo: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: ppp1: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: eth2: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: eth1: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: eth0: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: lo: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: ppp1: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: eth0: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: lo: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: ppp1: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: lo: Link is not managed by us
Dec 27 16:28:06 myfw systemd-networkd[31243]: ppp1: Link is not managed by us
Dec 27 16:28:07 myfw systemd-networkd[31243]: eth0: Configured
Dec 27 16:28:18 myfw systemd-networkd[31243]: eth3: Configured
Dec 27 16:28:18 myfw systemd-networkd[31243]: eth2: Configured
Dec 27 16:28:18 myfw systemd-networkd[31243]: eth1: Configured
Dec 27 16:29:04 myfw systemd[1]: Stopping Network Service...
Dec 27 16:29:05 myfw systemd[1]: systemd-networkd.service: Main process exited, code=dumped, status=11/SEGV
Dec 27 16:29:05 myfw systemd[1]: systemd-networkd.service: Failed with result 'core-dump'.
Dec 27 16:29:05 myfw systemd[1]: Stopped Network Service.
Dec 27 16:29:05 myfw systemd[1]: Starting Network Service...
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth3: Gained IPv6LL
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth2: Gained IPv6LL
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth1: Gained IPv6LL
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth0: Gained IPv6LL
Dec 27 16:29:05 myfw systemd-networkd[31303]: Enumeration completed
Dec 27 16:29:05 myfw systemd[1]: Started Network Service.
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth1: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth2: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: ppp1: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: lo: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth0: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth1: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: ppp1: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: lo: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth0: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: ppp1: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: lo: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth0: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: ppp1: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: lo: Link is not managed by us
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth2: Could not drop routing policy rule: No such file or directory
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth2: Could not drop routing policy rule: No such file or directory
Dec 27 16:29:05 myfw systemd-networkd[31303]: eth0: Configured
Dec 27 16:29:09 myfw systemd[1]: Stopping Network Service...
Dec 27 16:29:09 myfw systemd[1]: systemd-networkd.service: Main process exited, code=dumped, status=11/SEGV
Dec 27 16:29:09 myfw systemd[1]: systemd-networkd.service: Failed with result 'core-dump'.
Dec 27 16:29:09 myfw systemd[1]: Stopped Network Service.
Dec 27 16:29:09 myfw systemd[1]: Starting Network Service...
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth3: Gained IPv6LL
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth2: Gained IPv6LL
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth1: Gained IPv6LL
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth0: Gained IPv6LL
Dec 27 16:29:09 myfw systemd-networkd[31323]: Enumeration completed
Dec 27 16:29:09 myfw systemd[1]: Started Network Service.
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth0: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth2: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth1: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: lo: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: ppp1: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth0: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth1: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: lo: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: ppp1: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth0: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: lo: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: ppp1: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: lo: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: ppp1: Link is not managed by us
Dec 27 16:29:09 myfw systemd-networkd[31323]: eth0: Configured
Dec 27 16:29:21 myfw systemd-networkd[31323]: eth3: Configured
Dec 27 16:29:21 myfw systemd-networkd[31323]: eth2: Configured
Dec 27 16:29:21 myfw systemd-networkd[31323]: eth1: Configured
```

**Its a live system so it would be difficult for me to run gdb on it.**

But I hope that above information does provide some useful hints.

**Comment by CharlesMCruz** [comment] 2019-01-23 22:50
I'm also seeing the same bug in Ubuntu 18.04 with systemd 237. I believe this happens whenever an address for the interface is specified in the .network file. Here's an example:

```
# cat /etc/systemd/network/50-eni1.network
[Match]
Name=eni1
[Address]
Address=198.168.24.4/24
[RoutingPolicyRule]
From=198.168.24.4
Table=10
```

On a restart when it doesn't work, I see:
```
# sudo systemctl restart systemd-networkd
# ip rule
0:      from all lookup local
32766:  from all lookup main
32767:  from all lookup default
```

And on the next restart, I see:
```
# sudo systemctl restart systemd-networkd
# ip rule
0:      from all lookup local
0:      from 198.168.24.4 lookup eni1
32766:  from all lookup main
32767:  from all lookup default
```

And the same "works every other time" behavior as mentioned.

Looking at the logs with systemd-networkd debug set, I can see the routing policy rules are set after the addresses when it works. I don't see the routing policy rules being set/configured on the restarts that cause it to not work.
```
Jan 23 22:39:39 foo systemd-networkd[24209]: eni1: Configured
Jan 23 22:39:39 foo systemd-networkd[24209]: eni1: Routing policy rule configured
Jan 23 22:39:39 foo systemd-networkd[24209]: eni1: Setting routing policy rules
Jan 23 22:39:39 foo systemd-networkd[24209]: eni1: Addresses set
Jan 23 22:39:39 foo systemd-networkd[24209]: eni1: Adding address: 198.168.24.4/24 (valid forever)
Jan 23 22:39:39 foo systemd-networkd[24209]: eni1: Removing address: 198.168.24.4/24 (valid forever)
Jan 23 22:39:39 foo systemd-networkd[24209]: eni1: Setting addresses
```

**Comment by yuwata** [comment] 2019-01-24 02:34
I cannot reproduce this with the current git master (8499b2c26dc6811495e46c8c8a69d4d2656873ac). I guess that this is already fixed by 6aa5773bfff0a92d64da70426cae833df6f84daf.
@amishmm and @CharlesMCruz Could you test the current master?

@ssahani What do you think?

**Comment by amishmm** [comment] 2019-01-24 04:48
I am sorry but the system this happens is a production system. And I am not allowed to install "unreleased" version. Any other way I can test it?

PS: Currently I am adding IP rules via (foreign) script  so that they dont get deleted by systemd-network restart or crash.

**Comment by ssahani** [comment] 2019-02-07 20:23
@yuwata sorry for late reply. I can't reproduce with @CharlesMCruz's conf with latest git

**Comment by yuwata** [comment] 2019-02-07 20:34
OK. Let's close this.
@amishmm and @CharlesMCruz If you find the same issue with a recent version or snapshot (maybe newer then 6aa5773bfff0a92d64da70426cae833df6f84daf ?), then please provide the relevant logs and configs again. Thank you.

**Comment by amishmm** [comment] 2019-02-08 01:54
I havent been able to test it for above reasons. Will report as soon as new systemd release is out.

But I wonder if this issue will be resolved by https://github.com/systemd/systemd/commit/6aa5773bfff0a92d64da70426cae833df6f84daf . Because this issue is related to IP rules and not IP routes.

Kernel would refuse IP route addition if address is not ready. But kernel would not refuse IP rule addition even if address is not ready.

But lets see.

**Comment by amishmm** [comment] 2019-02-21 03:44
I upgraded to v241 and this bug still exists. Please re-open.

**Now only difference is that it fails randomly instead of alternately.**

This time I tried it on a different system.

As you can see below. It failed first time (rules vanished completely) then it did not vanish for 4-5 tries and then vanished again and then appeared again. So its no more alternate.

Strange behavior is that only rules related to IP address vanish and no rules related fwmark vanish.

> $ ip ru l
> 0:      from all lookup local 
> 28999:  from all to 192.169.25.0/24 lookup main 
> 29000:  from 1.2.3.254 lookup airtel 
> 29000:  from all to 1.2.3.252/30 lookup airtel 
> 29000:  from 4.5.6.18 lookup reliance 
> 29000:  from all to 4.5.6.16/28 lookup reliance 
> 30000:  from all fwmark 0x102 lookup airtel 
> 30000:  from all fwmark 0x101 lookup reliance 
> 32766:  from all lookup main 
> 32767:  from all lookup default 
> $ systemctl restart systemd-networkd
> $ ip ru l
> 0:      from all lookup local 
> 28999:  from all to 192.169.25.0/24 lookup main 
> 30000:  from all fwmark 0x102 lookup airtel 
> 30000:  from all fwmark 0x101 lookup reliance 
> 32766:  from all lookup main 
> 32767:  from all lookup default 
> $ systemctl restart systemd-networkd
> $ ip ru l
> 0:      from all lookup local 
> 28999:  from all to 192.169.25.0/24 lookup main 
> 29000:  from 1.2.3.254 lookup airtel 
> 29000:  from all to 1.2.3.252/30 lookup airtel 
> 29000:  from 4.5.6.18 lookup reliance 
> 29000:  from all to 4.5.6.16/28 lookup reliance 
> 30000:  from all fwmark 0x102 lookup airtel 
> 30000:  from all fwmark 0x101 lookup reliance 
> 32766:  from all lookup main 
> 32767:  from all lookup default 
> $ systemctl restart systemd-networkd
> $ ip ru l
> 0:      from all lookup local 
> 28999:  from all to 192.169.25.0/24 lookup main 
> 29000:  from 1.2.3.254 lookup airtel 
> 29000:  from all to 1.2.3.252/30 lookup airtel 
> 29000:  from 4.5.6.18 lookup reliance 
> 29000:  from all to 4.5.6.16/28 lookup reliance 
> 30000:  from all fwmark 0x102 lookup airtel 
> 30000:  from all fwmark 0x101 lookup reliance 
> 32766:  from all lookup main 
> 32767:  from all lookup default 
> $ systemctl restart systemd-networkd
> $ ip ru l
> 0:      from all lookup local 
> 28999:  from all to 192.169.25.0/24 lookup main 
> 29000:  from 1.2.3.254 lookup airtel 
> 29000:  from all to 1.2.3.252/30 lookup airtel 
> 29000:  from 4.5.6.18 lookup reliance 
> 29000:  from all to 4.5.6.16/28 lookup reliance 
> 30000:  from all fwmark 0x102 lookup airtel 
> 30000:  from all fwmark 0x101 lookup reliance 
> 32766:  from all lookup main 
> 32767:  from all lookup default 
> $ systemctl restart systemd-networkd
> $ ip ru l
> 0:      from all lookup local 
> 28999:  from all to 192.169.25.0/24 lookup main 
> 29000:  from 1.2.3.254 lookup airtel 
> 29000:  from all to 1.2.3.252/30 lookup airtel 
> 29000:  from 4.5.6.18 lookup reliance 
> 29000:  from all to 4.5.6.16/28 lookup reliance 
> 30000:  from all fwmark 0x102 lookup airtel 
> 30000:  from all fwmark 0x101 lookup reliance 
> 32766:  from all lookup main 
> 32767:  from all lookup default 
> $ systemctl restart systemd-networkd
> $ ip ru l
> 0:      from all lookup local 
> 28999:  from all to 192.169.25.0/24 lookup main 
> 29000:  from 1.2.3.254 lookup airtel 
> 29000:  from all to 1.2.3.252/30 lookup airtel 
> 29000:  from 4.5.6.18 lookup reliance 
> 29000:  from all to 4.5.6.16/28 lookup reliance 
> 30000:  from all fwmark 0x102 lookup airtel 
> 30000:  from all fwmark 0x101 lookup reliance 
> 32766:  from all lookup main 
> 32767:  from all lookup default 
> $ systemctl restart systemd-networkd
> $ ip ru l
> 0:      from all lookup local 
> 28999:  from all to 192.169.25.0/24 lookup main 
> 30000:  from all fwmark 0x102 lookup airtel 
> 30000:  from all fwmark 0x101 lookup reliance 
> 32766:  from all lookup main 
> 32767:  from all lookup default 
> $ systemctl restart systemd-networkd
> $ ip ru l
> 0:      from all lookup local 
> 28999:  from all to 192.169.25.0/24 lookup main 
> 29000:  from 1.2.3.254 lookup airtel 
> 29000:  from all to 1.2.3.252/30 lookup airtel 
> 29000:  from 4.5.6.18 lookup reliance 
> 29000:  from all to 4.5.6.16/28 lookup reliance 
> 30000:  from all fwmark 0x102 lookup airtel 
> 30000:  from all fwmark 0x101 lookup reliance 
> 32766:  from all lookup main 
> 32767:  from all lookup default

**Comment by amishmm** [comment] 2019-02-22 02:17
Today upgraded to v241.7 (Arch linux) and bug still exists. (for details see post above)

Infact after restarting networkd 7-8 times (or may be more) now I have lost access to the system. Will have to get someone check physically.

@yuwata @ssahani

**Comment by yuwata** [comment] 2019-02-22 02:24
Thank you for the report.
Is it possible to create a minimum reproducer?

**Comment by yuwata** [comment] 2019-02-22 03:27
Oh, ah, uh, finally I succeed to reproduce the issue... I will work on this issue. Please wait for a while.

**Comment by amishmm** [comment] 2019-02-22 04:08
Great. Thanks. In the mean while I managed to reproduce this on my personal laptop too.

And I managed to get a minimal config.

**Trick to reproduce this consistently is to WAIT 15 seconds between two restarts of systemd-networkd**.

Here is the situation:
1) I have LAN port - unplugged.
2) I have Wifi working connectivity

**Comment by amishmm** [comment] 2019-02-22 04:26
Great. Thanks. In the meantime I managed to reproduce this on my personal Laptop.

I also managed to create minimal reproducer.

**Trick is to reproduce this is to WAIT 15 seconds between two systemd-networkd restarts.**

Here is my settings:
1) Ethernet port - **Unplugged** - 192.168.0.5
2) Wifi - working - 192.168.1.5


1. Ethernet port config.
```
[Match]
MACAddress=00:11:22:33:44:55

[Network]
ConfigureWithoutCarrier=true
Address=192.168.0.5/24

[RoutingPolicyRule]
To=192.168.0.0/24
Table=200
Priority=29000
```

2. Wifi port config
```
[Match]
MACAddress=00:12:34:56:78:9a

[Network]
Address=192.168.1.5/24

[RoutingPolicyRule]
To=192.168.1.0/24
Table=201
Priority=29000
```

First stop systemd-networked and clear all existing rules using "ip rule del ...". So we have a clean slate.

Now run:

```
$ systemctl restart systemd-networkd
$ sleep 1
$ ip ru l
0:      from all lookup local 
29000:  from all to 192.168.1.0/24 lookup wifi 
29000:  from all to 192.168.0.0/24 lookup lan 
32766:  from all lookup main 
32767:  from all lookup default
```

All looks fine.

Now wait 15 seconds and restart systemd-networkd again.

```
$ sleep 15
$ systemctl restart systemd-networkd
$ sleep 1
$ ip ru l
0:      from all lookup local 
29000:  from all to 192.168.1.0/24 lookup wifi 
32766:  from all lookup main 
32767:  from all lookup default
```

Notice that rule related to "lan" (192.168.0.0/24) has vanished.

It re-appears on next restart.

Hope it helps in debugging.

Let me know if I can be of any other help.

Thank you

**Comment by yuwata** [comment] 2019-02-22 04:44
Fix is waiting in #11795.

@amishmm Thank you for the reproducer. I also use similar configs in the PR for testing the issue. Note that this issue only appears when multiple links request routing policy rules. I tried to reproduce this with single interface, so I did not notice this previously...

**Comment by amishmm** [comment] 2019-02-22 04:53
Thanks. You are always very quick! Amazing.

Yes earlier I was not able reproduce on my laptop for the same reason because I was trying to do it with one interface too.

I will try your PR on my laptop this weekend or so. And let you know.

**Closed as completed** 2019-02-27 17:43 UTC
Labels: bug 🐛, network

**Comment by iamtakingiteasy** [comment] 2025-01-06 11:26
Issue persists on `257 (257.1-1-arch)`

with
```
[Match]
Name=wgdev

[Network]
Address=10.32.46.5/24

[RoutingPolicyRule]
To=205.251.249.0/24
Table=1001

[RoutingPolicyRule]
To=205.251.252.0/23
Table=1001

[RoutingPolicyRule]
To=180.163.57.128/26
Table=1001

[RoutingPolicyRule]
To=111.13.171.128/26
Table=1001
```
I observe only three rules created after `systemctl restart systemd-networkd`:
```
32758:	from all to 205.251.252.0/23 lookup 1001 proto static
32764:	from all to 180.163.57.128/26 lookup 1001 proto static
32765:	from all to 205.251.249.0/24 lookup 1001 proto static
```

Interestingly, if you change Network.Address to 10.30.46.5/24, then all four rules are created, but on larger samples some still will be missing.
