### ISSUE TITLE
systemd-journald takes incredibly long to start

### ISSUE THREAD

**Issue by flippette** [systemd/systemd#33511] opened 2024-06-27 20:30 UTC
### systemd version the issue has been seen with

systemd-255.6

### Used distribution

NixOS 24.11 unstable

### Linux kernel version used

6.9.6-zen1

### CPU architectures issue was seen on

x86_64

### Component

systemd-journald

### Expected behaviour you didn't see

Fast system boot

### Unexpected behaviour you saw

`journald` takes upwards of 10 to 30 seconds to start

```
~ 
❯ systemd-analyze blame | head 
12.158s systemd-journald.service
  719ms home-manager-flippette.service
  221ms NetworkManager.service
  177ms nftables.service
  161ms dev-disk-by\x2dlabel-root.device
  110ms systemd-udev-trigger.service
  107ms user@1000.service
   66ms systemd-journal-flush.service
   57ms boot.mount
   52ms udisks2.service
```

edit: here's a bootup when it takes 25 seconds

```
~ 
❯ systemd-analyze blame | head
25.252s systemd-journald.service
  707ms home-manager-flippette.service
  225ms NetworkManager.service
  219ms nftables.service
  145ms dev-disk-by\x2dlabel-root.device
  105ms systemd-udev-trigger.service
  105ms user@1000.service
   59ms systemd-journal-flush.service
   51ms udisks2.service
   49ms suid-sgid-wrappers.service
```

here's the critical chain:

```
The time when unit became active or started is printed after the "@" character.
The time the unit took to start is printed after the "+" character.

multi-user.target @26.577s
└─getty.target @26.577s
  └─getty@tty1.service @26.577s
    └─plymouth-quit-wait.service @26.552s +23ms
      └─systemd-user-sessions.service @26.549s +2ms
        └─home-manager-flippette.service @25.823s +707ms
          └─basic.target @25.820s
            └─sockets.target @25.820s
              └─nix-daemon.socket @25.820s
                └─sysinit.target @25.820s
                  └─systemd-timesyncd.service @25.778s +41ms
                    └─systemd-tmpfiles-setup.service @25.766s +10ms
                      └─systemd-journal-flush.service @25.693s +59ms
                        └─systemd-journald.service @420ms +25.252s
                          └─systemd-journald.socket @413ms
                            └─-.mount @398ms
                              └─-.slice @398ms
```

**Comment by yuwata** [comment] 2024-08-02 06:51
I have never observe such slow down. Please provide the result of `systemd-analyze cat-config /usr/lib/systemd/journald.conf`.

**Comment by flippette** [comment] 2024-08-02 18:02
I managed to fix it on my machine by blacklisting Bluetooth-related kernel modules from loading, for some reason.

```
$ cat /etc/modprobe.d/disable-bluetooth.conf
blacklist bluetooth
blacklist btrtl
blacklist btmtk
blacklist btintel
blacklist btbcm
blacklist btusb
```

This is on a separate Arch install with the exact same issue, until I did this.

Blacklisting Bluetooth-related modules managed to bring `systemd-journald.service`'s startup time all the way from 25s down to just 9s, which I feel is still too long but it's better, I guess.

Here's the output of `systemd-analyze cat-config /usr/lib/systemd/journald.conf`, as requested:

```
# /etc/systemd/journald.conf
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it under the
#  terms of the GNU Lesser General Public License as published by the Free
#  Software Foundation; either version 2.1 of the License, or (at your option)
#  any later version.
#
# Entries in this file show the compile time defaults. Local configuration
# should be created by either modifying this file (or a copy of it placed in
# /etc/ if the original file is shipped in /usr/), or by creating "drop-ins" in
# the /etc/systemd/journald.conf.d/ directory. The latter is generally
# recommended. Defaults can be restored by simply deleting the main
# configuration file and all drop-ins located in /etc/.
#
# Use 'systemd-analyze cat-config systemd/journald.conf' to display the full config.
#
# See journald.conf(5) for details.

[Journal]
#Storage=auto
#Compress=yes
#Seal=yes
#SplitMode=uid
#SyncIntervalSec=5m
#RateLimitIntervalSec=30s
#RateLimitBurst=10000
#SystemMaxUse=
#SystemKeepFree=
#SystemMaxFileSize=
#SystemMaxFiles=100
#RuntimeMaxUse=
#RuntimeKeepFree=
#RuntimeMaxFileSize=
#RuntimeMaxFiles=100
#MaxRetentionSec=
#MaxFileSec=1month
#ForwardToSyslog=no
#ForwardToKMsg=no
#ForwardToConsole=no
#ForwardToWall=yes
#TTYPath=/dev/console
#MaxLevelStore=debug
#MaxLevelSyslog=debug
#MaxLevelKMsg=notice
#MaxLevelConsole=info
#MaxLevelWall=emerg
#MaxLevelSocket=debug
#LineMax=48K
#ReadKMsg=yes
#Audit=yes
```

**Comment by rarick** [comment] 2024-08-10 06:16
I'm also getting killed by this:

```
❯ sudo systemd-analyze blame
1min 1.046s systemd-journald.service
     4.314s systemd-networkd-wait-online.service
     1.145s reflector.service
     1.020s docker.service
      257ms dev-nvme1n1p2.device
      253ms syslog-ng@default.service
      171ms lvm2-monitor.service
      162ms systemd-udev-trigger.service
      110ms containerd.service
      102ms udisks2.service
      100ms blueman-mechanism.service
...
```

Output of `sudo systemd-analyze cat-config /usr/lib/systemd/journald.conf`:
```
# /etc/systemd/journald.conf
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it under the
#  terms of the GNU Lesser General Public License as published by the Free
#  Software Foundation; either version 2.1 of the License, or (at your option)
#  any later version.
#
# Entries in this file show the compile time defaults. Local configuration
# should be created by either modifying this file (or a copy of it placed in
# /etc/ if the original file is shipped in /usr/), or by creating "drop-ins" in
# the /etc/systemd/journald.conf.d/ directory. The latter is generally
# recommended. Defaults can be restored by simply deleting the main
# configuration file and all drop-ins located in /etc/.
#
# Use 'systemd-analyze cat-config systemd/journald.conf' to display the full config.
#
# See journald.conf(5) for details.

[Journal]
#Storage=auto
#Compress=yes
#Seal=yes
#SplitMode=uid
#SyncIntervalSec=5m
#RateLimitIntervalSec=30s
#RateLimitBurst=10000
#SystemMaxUse=
#SystemKeepFree=
#SystemMaxFileSize=
#SystemMaxFiles=100
#RuntimeMaxUse=
#RuntimeKeepFree=
#RuntimeMaxFileSize=
#RuntimeMaxFiles=100
#MaxRetentionSec=
#MaxFileSec=1month
#ForwardToSyslog=no
#ForwardToKMsg=no
#ForwardToConsole=no
#ForwardToWall=yes
#TTYPath=/dev/console
#MaxLevelStore=debug
#MaxLevelSyslog=debug
#MaxLevelKMsg=notice
#MaxLevelConsole=info
#MaxLevelWall=emerg
#MaxLevelSocket=debug
#LineMax=48K
#ReadKMsg=yes
#Audit=yes
```

Critical chain for journald:
```
❯ systemd-analyze critical-chain systemd-journald.service
The time when unit became active or started is printed after the "@" character.
The time the unit took to start is printed after the "+" character.

systemd-journald.service +1min 1.046s
└─systemd-journald.socket @267ms
  └─system.slice @213ms
    └─-.slice @213ms
```

I also heavily suspect it to be bluetooth device related. Here's why:
1. I don't see any bluetooth devices (ie my Asrock X670e Pro RS motherboard's bluetooth controller) showing up any more
2. When I boot into Arch's rescue mode, it takes a full minute on the `systemd-udev-trigger.service`. However, when I boot into my normal root, I see 162ms on that service.
3. I'm seeing error messages like these in `dmesg` (may or may not be related):

```
❯ sudo dmesg -w | grep -i usb | grep -i error
[    8.844027] usb 1-12: device descriptor read/64, error -110
[   24.417447] usb 1-12: device descriptor read/64, error -110
[   30.177187] usb 1-12: device descriptor read/64, error -110
[   45.750698] usb 1-12: device descriptor read/64, error -110
[   56.340593] usb 1-12: device not accepting address 4, error -71
[   66.750580] usb 1-12: device not accepting address 5, error -71
[  185.921759] xhci_hcd 0000:7d:00.0: xHC error in resume, USBSTS 0x401, Reinit
[  191.691480] usb 1-12: device descriptor read/64, error -110
[  207.259086] usb 1-12: device descriptor read/64, error -110
```

Let me know if you need any more info, very eager to get this problem solved.

**Comment by rarick** [comment] 2024-08-17 17:03
I found my issue, I had several coinciding things that seemed related but weren't.

I did a BIOS upgrade, which I had suspected had broken compatibility with my on-board Bluetooth/WiFi and was potentially blocking journald in some way on startup. This was not the case (though my BT/WiFi still aren't functional - could be my Linux 6.8.2 upgrade).

Fastboot had been re-enabled (BIOS update reset all settings) and was the root cause of the long journald times on my end. Disabling fast boot returned me to normal systemd start times.

**Comment by yuwata** [comment] 2024-08-17 18:21
> Fastboot had been re-enabled (BIOS update reset all settings) and was the root cause of the long journald times on my end. Disabling fast boot returned me to normal systemd start times.

Interesting. Why does the Fastboot feature trigger the issue??

If you'd like, please provide the results of `systemd-analyze plot > plot.svg` with/without the Fastboot.
Also, boot with `systemd.log_level=debug` kernel commandline option and provides journals by `journalctl -b --no-hostname > journal.txt` in both cases.

**Comment by flippette** [comment] 2024-08-17 19:34
I also did a BIOS update, and journald now only take ~60ms to start. Fast boot is/was not a configurable option between these 2 versions, so I can't definitively say if that has changed.

I use an MSI B650 MORTAR WIFI board, and updated from BIOS version 7D76vAH2 (July 18th, ComboPI 1.2.0.0a) to version 7D76vAH (August 14th, ComboPI 1.2.0.0a Patch A).

**Comment by vcaputo** [comment] 2024-08-17 19:39
Lack of entropy for the kernel's RNG to not block?  I don't recall if journald needs any "secure" random numbers @ startup... but this can be a source of inexplicable stalls during boot.

**Comment by poettering** [comment] 2024-10-18 13:14
OK, let's close this since this appears to be some mainboard/BIOS issue, not a systemd issue.

**Closed as completed by poettering** 2024-10-18 13:14 UTC
Labels: bug 🐛, udev, journal, pid1
