### ISSUE TITLE
fscrypt key appears to still be active after logout

### ISSUE THREAD

**Issue by dkg** [systemd/systemd#33138] opened 2024-06-01 02:05 UTC
### systemd version the issue has been seen with

256~rc3-6

### Used distribution

debian unstable

### Linux kernel version used

6.8.11-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-homed

### Expected behaviour you didn't see

following up from #32596, i'm experimenting with fscrypt-backed home directories created and maintained by `systemd-homed`.

It looks to me like the fscrypt key is not being correctly dropped.

according to `keyrings(7)`, `/proc/keys` is supposed to report different information depending on the permissions of the thread accessing it.

I don't really understand how to parse this file, but i tried to access it as user `moogly`, uid 60240.  I think i've run into some other bug with `sudo` here, because:

Enable fscrypt if needed and create a user:

```
# tune2fs -O encrypt /dev/device
# homectl create --storage=fscrypt moogly
```

```
0 root@unstable-amd64:~# sudo -u moogly -- id -u
[sudo] password for %p: 
60240
0 root@unstable-amd64:~# 
```

i just hit enter -- did not enter the password for `moogly` -- at the strange-looking prompt.

Anyway, to avoid any risk that `sudo` might try to tickle the PAM or NSS stacks, which in turn might tickle `systemd` and do something related to the fscrypt homedir, i figured i'd look at `/proc/keys` using `chpst` from [runit](https://smarden.org/runit/), version 2.1.2-59.  My understanding is that `chpst` is bare-bones.

Using that, it appears that `moogly`'s `fscrypt` key is still present after logout ☹.

### Unexpected behaviour you saw

As in #32596, ⛳ prefixes a one-line comment about the state of the system.

```
⛳ fresh boot
0 root@unstable-amd64:~# chpst -u :60240:60240 cat /proc/keys
00686174 I--Q---     4 perm 1f3f0000     0 65534 keyring   _uid.0: empty
2fc4b570 I--Q---     9 perm 3f030000     0     0 keyring   _ses: 1
⛳ moogly logs in
0 root@unstable-amd64:~# chpst -u :60240:60240 cat /proc/keys
00686174 I--Q---     4 perm 1f3f0000     0 65534 keyring   _uid.0: empty
1da94d1f I--Q---     1 perm 3d010000 60240 60240 logon     fscrypt:54c5eb495739a0b6: 72
25815ea1 I--Q---     4 perm 1f3f0000 60240 65534 keyring   _uid.60240: 1
2664d714 I--Q---     1 perm 1f3f0000 60240 65534 keyring   _uid_ses.60240: 1
2fc4b570 I--Q---     9 perm 3f030000     0     0 keyring   _ses: 1
31d695c6 I--Q---     5 perm 3f030000 60240 60240 keyring   _ses: 1
34548126 I--Q---     4 perm 3f030000 60240 60240 keyring   _ses: 1
⛳ moogly does "cat test.txt"
0 root@unstable-amd64:~# chpst -u :60240:60240 cat /proc/keys
00686174 I--Q---     4 perm 1f3f0000     0 65534 keyring   _uid.0: empty
1da94d1f I--Q---     1 perm 3d010000 60240 60240 logon     fscrypt:54c5eb495739a0b6: 72
25815ea1 I--Q---     4 perm 1f3f0000 60240 65534 keyring   _uid.60240: 1
2664d714 I--Q---     1 perm 1f3f0000 60240 65534 keyring   _uid_ses.60240: 1
2fc4b570 I--Q---     9 perm 3f030000     0     0 keyring   _ses: 1
31d695c6 I--Q---     5 perm 3f030000 60240 60240 keyring   _ses: 1
34548126 I--Q---     4 perm 3f030000 60240 60240 keyring   _ses: 1
⛳ moogly logs out, wait 5 seconds
0 root@unstable-amd64:~# chpst -u :60240:60240 cat /proc/keys
00686174 I--Q---     4 perm 1f3f0000     0 65534 keyring   _uid.0: empty
1da94d1f I--Q---     1 perm 3d010000 60240 60240 logon     fscrypt:54c5eb495739a0b6: 72
25815ea1 I--Q---     3 perm 1f3f0000 60240 65534 keyring   _uid.60240: 1
2664d714 I--Q---     1 perm 1f3f0000 60240 65534 keyring   _uid_ses.60240: 1
2fc4b570 I--Q---     9 perm 3f030000     0     0 keyring   _ses: 1
31d695c6 I--Q---     5 perm 3f030000 60240 60240 keyring   _ses: 1
⛳ wait another 10 minutes
0 root@unstable-amd64:~# chpst -u :60240:60240 cat /proc/keys
00686174 I--Q---     4 perm 1f3f0000     0 65534 keyring   _uid.0: empty
1da94d1f I--Q---     1 perm 3d010000 60240 60240 logon     fscrypt:54c5eb495739a0b6: 72
25815ea1 I--Q---     2 perm 1f3f0000 60240 65534 keyring   _uid.60240: 1
2664d714 I--Q---     1 perm 1f3f0000 60240 65534 keyring   _uid_ses.60240: 1
2fc4b570 I--Q---     9 perm 3f030000     0     0 keyring   _ses: 1
0 root@unstable-amd64:~# 
```

So yes, it appears that some keys are still held by user `60240`, including one with an `fscrypt:` prefix.

If you need me to debug further, please suggest what i should do.

### Steps to reproduce the problem

- following the same steps as #32596 to set up the system.
- `apt install --no-install-recommends runit`
- as `root`, examine the state of `/proc/keys` while `moogly` logs in and logs out.

**Comment by bluca** [comment] 2024-06-04 00:11
```
Jun 04 00:09:35 localhost systemd-homework[943]: Syncing completed.
Jun 04 00:09:35 localhost systemd-homework[943]: Umounting /run/systemd/user-home-mount...
Jun 04 00:09:35 localhost systemd-homework[943]: Unmounting completed.
Jun 04 00:09:35 localhost systemd-homework[943]: Failed to find kernel keyring entry for user, ignoring: Required key not available
Jun 04 00:09:35 localhost systemd-homework[943]: Dropped caches.
Jun 04 00:09:36 localhost kernel: systemd-homewor (943): drop_caches: 3
Jun 04 00:09:35 localhost systemd-homework[943]: Everything completed.
```

Looks like flushing the keyring fails as the key can't be found, for some reason

**Comment by bluca** [comment] 2024-06-04 00:59
Actually flushing the fscrypt key is not implemented at all, so this is not really a regression. It's a 'logon' keyring, which according to the kernel doc makes it unreadable from userspace so it's probably not too bad.

**Comment by poettering** [comment] 2024-06-04 12:07
So, my understanding is that the per-user keyring goes away anyway if the last process of the owning user goes away. Hence how come this is not cleaned up automatically for you?

do you have a process hidden somewhere that is owned by the user in question?

**Comment by bluca** [comment] 2024-06-04 12:10
> So, my understanding is that the per-user keyring goes away anyway if the last process of the owning user goes away. Hence how come this is not cleaned up automatically for you?
> 
> do you have a process hidden somewhere that is owned by the user in question?

No processes or sessions left. This is trivially reproducible with a mkosi mage built on latest main btw, just build it, add a user with `homectl create --storage=fscrypt test`, and then activate it with homectl, and deactivate it again - no need to even login. The fscrypt key will be in the user keyring.

**Comment by poettering** [comment] 2024-06-04 12:18
As per man page user-keyring(7):

> The user keyring is associated with the record that the kernel maintains for the UID.  It comes into existence upon the first attempt to access either the user keyring, the user-session-keyring(7), or the  session-keyring(7). The  keyring  remains  pinned  in  existence  so  long as there are processes running with that real UID or files opened by those processes remain open.  (The keyring can also be pinned indefinitely by linking it into another keyring.)

So, it relaly should be cleaned up automatically.

**Comment by bluca** [comment] 2024-06-04 12:19
> (The keyring can also be pinned indefinitely by linking it into another keyring.)

Are we linking it somewhere else maybe?

**Closed as completed** 2024-06-06 15:34 UTC
Labels: bug 🐛, homed

**Comment by dkg** [comment] 2024-06-13 18:51
Thanks for fixing this!  The `fscrypt` key is now purged, but something else is still holding a couple keys for the user even 10 minutes after they log out.  I've opened #33308 to track that remaining concern.
