### ISSUE TITLE
overriding of symlinked unit files is broken

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#4917] opened 2016-12-19 00:30 UTC
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

v232

### Used distribution

Debian unstable

### In case of bug report: Expected behaviour you didn't see

Trying to override a system provided unit file by copying it to /etc does not work for certain unit files.

### In case of bug report: Unexpected behaviour you saw

Overriding by copying to /etc works for *all* unit files.

### In case of bug report: Steps to reproduce the problem

systemctl edit --full rsyslog.service && systemctl restart rsyslog.service && systemctl status rsyslog.service
→ error: unit file from /usr/lib/ is used

systemctl edit --full crond.service && systemctl restart crond.service && systemctl status crond.service
→ unit file from /etc/ is used

So, this doesn't happen for all unit files. 
rsyslog.service has an syslog.service alias, maybe that's a hint.
I've also noticed, that template unit files can't be overridden, say systemctl edit --full getty@.service

**Comment by poettering** [comment] 2016-12-20 09:36
Yupp, there's currently a limitation in the loading scheme used by systemd: we'll follow symlinks when loading units, and if an overriden unit is not among the symlink chain we load something from we won't notice it. We should change that and make sure that for each symlink chain element we check all search paths before proceeding to the next.

**Comment by keszybz** [comment] 2018-12-06 14:32
Duplicate of #902

**Closed as completed by keszybz** 2018-12-06 14:32 UTC
Labels: pid1
