### ISSUE TITLE
systemd-boot doesn't parse menu entries most of the time

### ISSUE THREAD

**Issue by francoism90** [systemd/systemd#7194] opened 2017-10-27 13:09 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

>235.8-1

### Used distribution

>Arch Linux

### In case of bug report: Expected behaviour you didn't see

>Able to select different kernel at boot, dual boot (e.g. booting into Windows)

### In case of bug report: Unexpected behaviour you saw

>Directly boots into default section set in `loader.conf`

### In case of bug report: Steps to reproduce the problem

>The boot-menu doesn't show most times, the chance at the moment is 1/10 it will show correctly.
>Tried disabling `fastboot`, fsck on EFI-partition `/boot/efi` and updating/regenerating kernel(s).

**Comment by poettering** [comment] 2017-10-27 18:24
Consider increasing the menu timeout from 0. Either by pressing "+" while you have the menu. Or via the text file: 

https://wiki.archlinux.org/index.php/systemd-boot#Configuration

**Comment by poettering** [comment] 2017-10-27 18:26
Also note that if a keypress is already queued by the firmware when sd-boot initializes, the menu is shown.

Either way, this is not a bug, if you set the timeout to 0. Closing hence.

**Closed as completed by poettering** 2017-10-27 18:26 UTC
Labels: sd-boot/sd-stub/bootctl, not-a-bug

**Comment by francoism90** [comment] 2017-10-28 08:20
@poettering Thanks for your reply.

This is my `loader.conf`:
```
$ cat /boot/loader/loader.conf
timeout 5
default arch-ck
```

As you can see I use a timeout and I'm using linux-ck (arch-ck) as default boot entry.
Strange it doesn't show up the default kernel and Windows boot entries, but immediately boots into the default entry.

As already stated it does show the boot selection sometimes.
To be fair, I don't know if this is a issue with the latest Windows update or has something to do with systemd-boot.

Is it possible to get boot log or show debug info on systemd-boot?

**Comment by francoism90** [comment] 2018-03-06 20:09
For anyone struggling with this issue - turns out Windows 10 needs CSM enabled in BIOS.
It now works perfectly again, so no systemd bug.
