### ISSUE TITLE
Allow cache DNS responses from localhost resolvers

### ISSUE THREAD

**Issue by psapezhka** [systemd/systemd#17679] opened 2020-11-20 13:49 UTC
**Is your feature request related to a problem? Please describe.**
I've tried to use systemd-resolved as the main resolve solution and consul for my internal services. I want to cache responses using systemd-resolved (plus consul won't cache responses from recursors by design), but systemd-resolved won't do that because of https://github.com/systemd/systemd/blob/40ebe492596abbb525857034e28fdeee16d4e50b/src/resolve/resolved-dns-transaction.c#L685

**Describe the solution you'd like**
Implement an option to allow cache DNS responses from localhost resolvers.

**Describe alternatives you've considered**
As alternative, I found only using another DNS solution, like dnsmasq, or bind consul agent to non-localhost address.

I think I can implement that, but first I want to know is it a suitable solution?

**Comment by poettering** [comment] 2020-11-20 15:07
Duplicate of #4480

**Comment by poettering** [comment] 2020-11-20 15:07
Yes, making this configurable would be OK i guess, via some setting in `resolved.conf`. Happy to review/merge a patch for that.

**Closed as completed by poettering** 2020-11-20 15:07 UTC
Labels: resolve, duplicate
