### ISSUE TITLE
systemd.path - Implement PathModifiedGlob, glob on daemon-reload

### ISSUE THREAD

**Issue by SjonHortensius** [systemd/systemd#5344] opened 2017-02-14 14:14 UTC
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### Description of Enhancement

It would be nice if besides the existing `PathCreatedGlob`; `PathModifiedGlob` would also be supported. It could glob on daemon-reload; watching for modifications on the found paths

**Comment by poettering** [comment] 2017-02-14 14:26
Uh, automatic reloading when unit files are change cannot work. Your usecase is inherently flawed: unit file changes are quite often everything but atomic: for example a rename of a unit file might result in a reload at the wrong time where the unit file is possible seen under both names or under neither (depending when precisely systemd reads the relevant unit file dirs). 

Automatic reloading is only safe for daemons that have a single configuration file, which is always updated atomically. Most daemons are not like that, and systemd definitely isn't. Hence any such logic for automatic reloads is unsafe for these cases, and we won't support it in systemd, as it makes a promise we cannot keep.

**Comment by SjonHortensius** [comment] 2017-02-14 14:37
Thanks for your response. That's not what I meant; I'll need to explain it better. I meant the `glob` could be executed on daemon-reload; eg; when the service file is reloaded. So a unit could specify:

```
PathModifiedGlob=/etc/directory/*.conf
```

When this unit is enabled; or daemon-reload is executed; the glob is done and it finds 3 conf files. It sets up watches for modifications to `/etc/directory/a.conf`, `/etc/directory/b.conf` and `/etc/directory/c.conf`.

If `/etc/directory/d.conf` is added nothing happens. If `b.conf` is modified, the service is activated

**Comment by jcpunk** [comment] 2017-05-30 14:06
I'm also interested in this feature, but for different reasons.

systemd has most of the features I require to replace my use of `inotifywatch`.  I have a simple set of globs I'm watching.  

The addition of `PathChangedGlob` and `PathModifiedGlob` would be sufficient to cover my entire use case.  It would drop the complexity of my environment significantly.

Unlike the original RFE, I'm generating generating alerts, reports, and doing some limited audits.  I have no plans to use this as a trigger for service reloads.

**Comment by Zugschlus** [comment] 2017-07-31 10:54
While we're at it, PathChangedGlob would also be a good idea. And an PathExcludeGlob, for example:

PathExists=/foo
PathExcludeGlob=[#.]*

Many editors do create their work/scratch/swap files in the same directory as the file being edited, and just taking out a PathExists watch would mistrigger the Unit multiple times while the actual file is edited.

I am really excited about systemd.path, because it will allow to remove a mess of inoticron, incron, iwatch etc use cases in favor of a centralized and readily-available tool. But alas, not in the current state of development.

**Comment by elgow** [comment] 2019-04-05 19:30
Having PathExistsGlob as the only glob option makes systemd.path unable to watch anything except individual files with names fully known at the time the path unit is written. The PathExistsGlob mode will re-trigger for a file that exists for any length of time even w/o any change to the file. That is generally not desired. The PathModifiedGlob mode suggested here would be a great step forward as it would eliminate spurious re-triggering. 

Delivering context info about the file and event that caused the trigger  as environment variables would make systemd.path a viable replacement for incron, inotifyutils, etc. As things stand, the entire systemd.path feature is essentially unusable for almost any purpose.

**Comment by poettering** [comment] 2022-03-10 10:46
Closing this as duplicate of #14330

**Closed as completed by poettering** 2022-03-10 10:46 UTC
Labels: RFE 🎁, pid1
