### ISSUE TITLE
Allow journal query match api to allow exclusions

### ISSUE THREAD

**Issue by MrPippin66** [systemd/systemd#23052] opened 2022-04-11 17:14 UTC
**Is your feature request related to a problem? Please describe.**
When doing journal queries, I have situations where I have logs entries indicating a serious issue (log level 'critical'), but aren't actually serious issues. This results in me having to manually do exclusion filters outside the API, which I find counter-productive. This isn't scripting, but actually programs using the "add_match", etc. filter api.

**Describe the solution you'd like**
I would prefer if an exclusion extension was made to the existing API to allow match results to be excluded from the returned data.

This might be best served by adding an 'sd_journal_add_exclusion()' API.

**Describe alternatives you've considered**
The only alternative I'm aware of is to either not use the existing filter API altogether and write my own, or extend the existing filter to have my own exclusion rules.

**The systemd version you checked that didn't have the feature you are asking for**
I'm not aware of any existing systemd version having exclusion abilities in the journal query API. I'm using version 239.

**Comment by MrPippin66** [comment] 2023-05-08 19:20
Has this been evaluated? Request is over a year old at this point.

**Comment by dtardon** [comment] 2023-05-09 06:54
Duplicate of #2720.

**Closed as not planned by dtardon** 2023-05-09 06:54 UTC
Labels: RFE 🎁, journal, duplicate
