### ISSUE TITLE
Set old date to system time and then write it to hardware time will be lost after reboot

### ISSUE THREAD

**Issue by utt54321** [systemd/systemd#24302] opened 2022-08-13 14:43 UTC
### systemd version the issue has been seen with

247.3-7

### Used distribution

Debian11

### Linux kernel version used

5.10.0-14-amd64

### Expected behaviour you didn't see

In Debian11, disable Automatic time synchronization, then I use  timedatectl to set a old date like 
$ timedatectl set-time "2012-10-30 18:17:16"
(today is 2022/8/13)
And then I reboot the computer, checkout the system time
$ timedatectl status
Local time: Sat 2022-08-13 20:14:57 CST
Universal time: Sat 2022-08-13 12:14:57 UTC
RTC time: **Sat 2022-08-13 12:14:57 UTC**
Time zone: Asia/Beijing (CST, +0800)
System clock synchronized: no
NTP service: inactive
RTC in local TZ: no

### Unexpected behaviour you saw

In Debian11 or ubuntu, I disable Automatic time synchronization, then I use  timedatectl to set a old date like 
$ timedatectl set-time "2012-10-30 18:17:16"
(today is 2022/8/13)
And then I reboot the computer, checkout the system time
$ timedatectl status
Local time: Sat 2022-08-13 20:14:57 CST
Universal time: Sat 2022-08-13 12:14:57 UTC
RTC time: **Tue 2012-10-30 10:18:57**
Time zone: Asia/Beijing (CST, +0800)
System clock synchronized: no
NTP service: inactive
RTC in local TZ: no

### Steps to reproduce the problem

1.  disable Automatic time synchronization
2. use  timedatectl to set a old date like 
$ timedatectl set-time "2012-10-30 18:17:16"
(today is 2022/8/13)
3.reboot the computer, checkout the system time
$ timedatectl status
_Local time: Sat 2022-08-13 20:14:57 CST
Universal time: Sat 2022-08-13 12:14:57 UTC
RTC time: **Tue 2012-10-30 10:18:57**
Time zone: Asia/Beijing (CST, +0800)
System clock synchronized: no
NTP service: inactive
RTC in local TZ: no_

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Here is my question:
In Debian11 or ubuntu, I disable Automatic time synchronization, then I use  timedatectl to set a old date like 
$ timedatectl set-time "2012-10-30 18:17:16"
(today is 2022/8/13)
And then I reboot the computer, checkout the system time
$ timedatectl status
Local time: Sat 2022-08-13 20:14:57 CST
Universal time: Sat 2022-08-13 12:14:57 UTC
RTC time: Tue 2012-10-30 10:18:57
Time zone: Asia/Beijing (CST, +0800)
System clock synchronized: no
NTP service: inactive
RTC in local TZ: no
You can see the system time come back to the original date(2022/8/13), and the hardware time keeps the old date (2012/10/30) while I disable Automatic time synchronization.
I thought if I set the system time an old date, after reboot the system time should be the old date. 
And I have tested if I only change a few days with command "timedatectl set-time '2022-8-5 18:17:16'", after reboot the system time is  '2022-8-5 18:17:16'.
I also have tested using "date -s" and "hwclock -w" to set old date, the phenomenon still exits.
So I think it is systemd mechanism which leads to this situation (systemd sync the system time to the date 2022/8/13 while the RTC time keeps old date), but I cannot find any doc describe this situation. So I think it is a bug.
```

**Comment by yuwata** [comment] 2022-08-13 17:34
If the system time is set before the epoch time (usually, automatically determined on compile), then PID1 sets the system time to the epoch time.

I do not know why you want to set such old date, but if you really want to do that, please create `/usr/lib/clock-epoch` with its mtime older than the date you want to set.

This is not a bug, closing.

**Closed as not planned by yuwata** 2022-08-13 17:34 UTC
Labels: pid1, not-a-bug

**Comment by utt54321** [comment] 2022-08-13 19:22
@yuwata  Sir, what is PID1? Is it /sbin/init? 
Where can I find the epoch time( or build time )
And I followed the advice to create clock-epoch :
![image](https://user-images.githubusercontent.com/20319237/184507846-afb1972f-4d13-4ce9-bb72-0c8f53383308.png)
after reboot, the phenomenon still keeps:
![image](https://user-images.githubusercontent.com/20319237/184507900-e2496dc8-3351-4076-b013-a6a4c1989cbb.png)
Is the functionality of `/usr/lib/clock-epoch` OK?

**Comment by yuwata** [comment] 2022-08-13 20:34
> what is PID1? Is it /sbin/init?

PID1 is systemd service manager. Yeah, you can see that from the symlink /sbin/init.

> Where can I find the epoch time( or build time )

Hm, please find it in the build log of the systemd package.

--------
Several additional comments.
- First of all, please check that no NTP service running on the host.
- I guess you can find `"System time before build time, advancing clock."` in journal. Please try to find relevant logs in journal.
- If you want to use the epoch file, then the file must exist both on the host system and initrd. Please do not forget to append the epoch file to initrd image.

**Comment by utt54321** [comment] 2022-08-13 20:47
![image](https://user-images.githubusercontent.com/20319237/184510174-2bc0bc50-e958-4a7e-bdaf-74d188ec735c.png)
@yuwata sir,I was trying to find what you say, but there seems no NTP service and no log like "System time before build time, advancing clock."

And how  to append the epoch file to initrd image?

**Comment by yuwata** [comment] 2022-08-13 21:30
Then, please try to find what changes the system time.

> And how to append the epoch file to initrd image?

I do not know how to build/update initrd on Debian. Please google it.

**Comment by yuwata** [comment] 2022-08-13 21:32
BTW, here is not support forum. Please do not continue this thread unless you find a bug in systemd.
Also, as you can see in the template, v247 is too old here. Please contact to the Debian's support forum.

**Comment by utt54321** [comment] 2022-08-14 02:51
@yuwata sir, I have the last question: why you thought about to  append the epoch file to initrd image? How this idea comes up?
