### ISSUE TITLE
systemd-networkd does not bring up static interfaces at startup

### ISSUE THREAD

**Issue by LaKing** [systemd/systemd#7920] opened 2018-01-18 04:01 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

systemd 234

### Used distribution

Fedora 27

### In case of bug report: Expected behaviour you didn't see

Networking on the interface defined, eg.: /etc/systemd/network/eno1.network

```
[Match]
Name=eno1

[Network]
Address=195.123.124.125/28
Gateway=195.123.124.126
DNS=195.184.180.4
DNS=195.184.181.4
```

### In case of bug report: Unexpected behaviour you saw

No connectivity until systemd-networkd is restarted.

### In case of bug report: Steps to reproduce the problem

Case one: A single link with a static IPv4 configuration in the .network configuration file.
Case two: Multiple links, but only one static configuration  with IPv4, all others left on DHCP.

Boot the system, with systemd-networkd enabled.
In both cases, no network, no static IP address, .. however, restarting systemd-networkd instantly brings the configuration up, and communication on the desired IP address starts.

There are two workarounds, the first for the first case, an additional 'classic' /etc/sysconfig/network-scripts configuration file, and restarting systemd-networkd after boot.
Or, in the second case, connecting over the DHCP interface to restart systemd-networkd.

I assume systemd-networkd alone should be sufficient alone to bring the static configuration up automatically after boot, therefore this appears to be a bug to me.

(IP adderss and hostname are altered)

**Comment by ssahani** [comment] 2018-01-18 13:28
Cant' reproduce .
```

3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:40:aa:db brd ff:ff:ff:ff:ff:ff
    inet 192.168.225.25/24 brd 192.168.225.255 scope global enp0s8
       valid_lft forever preferred_lft forever
    inet6 2405:204:9422:2b4:a00:27ff:fe40:aadb/64 scope global mngtmpaddr noprefixroute 
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe40:aadb/64 scope link 
       valid_lft forever preferred_lft forever
[sus@A ~]$ cat /lib/systemd/network/
80-container-host0.network  80-container-vz.network     br0.network1                enp0s9.network~             tmp/                        
80-container-ve.network     99-default.link             enp0s9.network              m-mSz.tar.gz                
[sus@A ~]$ cat /lib/systemd/network/enp0s9.network
[Match]
Name=enp0s8

[Network]
Address=192.168.225.25/24
Gateway=192.168.225.1
DNS=192.168.225.1

```

**Comment by LaKing** [comment] 2018-01-18 21:19
@ssahani 
I'm wondering why you keep your .network definitions in /lib/systemd/network?
Plus there are files that don't belong there? ...

You appear to use a network behind a router. Are you sure that the router is not assigning a DHCP address? And you have no configs in /etc/sysconfig? ...

In both of my cases, the NIC's connect directly to the internet, so the static IP is not behind a router ,...

**Comment by LaKing** [comment] 2018-01-19 02:11
What log / debug info is needed? ....

**Comment by jkhsjdhjs** [comment] 2018-01-20 08:01
I'm having a similar issue on Gentoo with systemd 236 at the moment and it might have the same cause.
In my case it's caused by udev renaming the devices too late.

Debug mode log: http://dpaste.com/1Q85HDN
In Line 13 systemd-networkd is setting the flags for eth0, which gets renamed to eno2 later. But because networkd does not have a configuration file for eth0, it doesn't add IP adresses and doesn't set +UP.
In Line 36 eth0 gets renamed to eno2 by udev, but networkd does not check if it has .network files for eno2.

I solved this by disabling udev device renaming by placing an empty file named `80-net-name-slot.rules` in `/etc/udev/rules.d/`. My device would then be named eth0 instead of eno2, so I changed the name in my .network file too and it works.

If this doesn't solve your problem @LaKing our issues aren't related. It would be nice if you could try it.

**Comment by LaKing** [comment] 2018-01-21 05:00
@jkhsjdhjs 

I tried it but placing the 80-net-name-slot.rules file to udev rules.d did not disable eth renaming.
I was trying to examine dmesg and systemd-networkd logs, but the logs are not verbose enough.

**Comment by jkhsjdhjs** [comment] 2018-01-21 12:43
If you want more verbose logs you can run `systemctl edit systemd-networkd`, enter the following
```
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```
and then restart systemd-networkd.

If you then think that udev might be renaming the devices too late in your case, too, you can apparently also disable device renaming by adding `net.ifnames=0` and `biosdevname=0` as kernel parameters to your bootloader.

**Comment by LaKing** [comment] 2018-01-22 04:20
I enabled debug loglevel. After reboot:
```
[root@my-hostname ~]# journalctl --since today | grep eno1

jan 22 03:45:14 my-hostname kernel: bnx2 0000:01:00.0 eno1: renamed from eth0
jan 22 03:45:22 my-hostname systemd-networkd[827]: eno1: Flags change: +MULTICAST +BROADCAST
jan 22 03:45:22 my-hostname systemd-networkd[827]: eno1: Link 2 added
jan 22 03:45:22 my-hostname systemd-networkd[827]: eno1: udev initialized link
jan 22 03:45:22 my-hostname systemd-networkd[827]: eno1: Saved original MTU: 1500
jan 22 03:45:22 my-hostname kernel: bnx2 0000:01:00.0 eno1: using MSIX
jan 22 03:45:22 my-hostname kernel: IPv6: ADDRCONF(NETDEV_UP): eno1: link is not ready
jan 22 03:45:22 my-hostname kernel: IPv6: ADDRCONF(NETDEV_UP): eno1: link is not ready
jan 22 03:45:22 my-hostname systemd-networkd[827]: eno1: Link state is up-to-date
jan 22 03:45:22 my-hostname systemd-networkd[827]: eno1: found matching network '/etc/systemd/network/eno1.network'
jan 22 03:45:22 my-hostname systemd-networkd[827]: eno1: Bringing link up
jan 22 03:45:22 my-hostname systemd-networkd[827]: eno1: IPv6 successfully enabled
jan 22 03:45:22 my-hostname NetworkManager[826]: <info>  [1516589122.2943] manager: (eno1): new Ethernet device (/org/freedesktop/NetworkManager/Devices/2)
jan 22 03:45:22 my-hostname NetworkManager[826]: <info>  [1516589122.2975] settings: (eno1): created default wired connection 'Wired connection 1'
jan 22 03:45:22 my-hostname NetworkManager[826]: <info>  [1516589122.2986] device (eno1): state change: unmanaged -> unavailable (reason 'managed', internal state 'external')
jan 22 03:45:22 my-hostname systemd-networkd[827]: eno1: Flags change: +UP +RUNNING
jan 22 03:45:22 my-hostname systemd-networkd[827]: eno1: Started LLDP.
jan 22 03:45:23 my-hostname systemd-networkd[827]: eno1: Flags change: -RUNNING
jan 22 03:45:25 my-hostname systemd-networkd[827]: eno1: Flags change: +LOWER_UP +RUNNING
jan 22 03:45:25 my-hostname systemd-networkd[827]: eno1: Gained carrier
jan 22 03:45:25 my-hostname kernel: bnx2 0000:01:00.0 eno1: NIC Copper Link is Up, 1000 Mbps full duplex
jan 22 03:45:25 my-hostname kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eno1: link becomes ready
jan 22 03:45:25 my-hostname NetworkManager[826]: <info>  [1516589125.5236] device (eno1): link connected
jan 22 03:45:25 my-hostname systemd-networkd[827]: eno1: Setting addresses
jan 22 03:45:25 my-hostname systemd-networkd[827]: eno1: Updating address: 195.123.124.125/28 (valid forever)
jan 22 03:45:25 my-hostname NetworkManager[826]: <info>  [1516589125.5245] device (eno1): state change: unavailable -> disconnected (reason 'carrier-changed', internal state 'managed')
jan 22 03:45:25 my-hostname systemd-networkd[827]: eno1: Addresses set
jan 22 03:45:25 my-hostname systemd-networkd[827]: eno1: Setting routes
jan 22 03:45:25 my-hostname systemd-networkd[827]: eno1: Routes set
jan 22 03:45:25 my-hostname NetworkManager[826]: <info>  [1516589125.5274] ifcfg-rh: add connection in-memory (2b3d68b4-c2af-46ac-9f28-5fa07f2824ea,"eno1")
jan 22 03:45:25 my-hostname NetworkManager[826]: <info>  [1516589125.5290] device (eno1): Activation: starting connection 'eno1' (2b3d68b4-c2af-46ac-9f28-5fa07f2824ea)
jan 22 03:45:25 my-hostname NetworkManager[826]: <info>  [1516589125.5311] device (eno1): state change: disconnected -> prepare (reason 'none', internal state 'external')
jan 22 03:45:25 my-hostname NetworkManager[826]: <info>  [1516589125.5319] device (eno1): disconnecting for new activation request.
jan 22 03:45:25 my-hostname NetworkManager[826]: <info>  [1516589125.5319] device (eno1): state change: prepare -> deactivating (reason 'new-activation', internal state 'external')
jan 22 03:45:25 my-hostname NetworkManager[826]: <info>  [1516589125.5325] device (eno1): state change: deactivating -> disconnected (reason 'new-activation', internal state 'external')
jan 22 03:45:25 my-hostname systemd-networkd[827]: eno1: Removing address: 195.123.124.125/28 (valid forever)
jan 22 03:45:25 my-hostname NetworkManager[826]: <info>  [1516589125.5359] device (eno1): Activation: starting connection 'Wired connection 1' (b061a7d2-b434-3fc3-b3da-b9a3a86eb252)
jan 22 03:45:25 my-hostname NetworkManager[826]: <info>  [1516589125.5455] device (eno1): state change: disconnected -> prepare (reason 'none', internal state 'managed')
jan 22 03:45:25 my-hostname NetworkManager[826]: <info>  [1516589125.5465] device (eno1): state change: prepare -> config (reason 'none', internal state 'managed')
jan 22 03:45:26 my-hostname NetworkManager[826]: <info>  [1516589126.4990] device (eno1): state change: config -> ip-config (reason 'none', internal state 'managed')
jan 22 03:45:26 my-hostname NetworkManager[826]: <info>  [1516589126.5003] dhcp4 (eno1): activation: beginning transaction (timeout in 45 seconds)
jan 22 03:45:26 my-hostname NetworkManager[826]: <info>  [1516589126.5048] dhcp4 (eno1): dhclient started with pid 1700
jan 22 03:45:26 my-hostname dhclient[1700]: DHCPDISCOVER on eno1 to 255.255.255.255 port 67 interval 7 (xid=0xbd810a05)
jan 22 03:45:28 my-hostname systemd-networkd[827]: eno1: Adding address: fe80::24e2:bba1:8b4f:8067/64 (valid forever)
jan 22 03:45:28 my-hostname systemd-networkd[827]: eno1: Gained IPv6LL
jan 22 03:45:28 my-hostname systemd-networkd[827]: eno1: Discovering IPv6 routers
jan 22 03:45:28 my-hostname systemd-networkd[827]: eno1: Updating address: fe80::24e2:bba1:8b4f:8067/64 (valid forever)
jan 22 03:45:30 my-hostname ntpd[797]: Listen normally on 5 eno1 [fe80::24e2:bba1:8b4f:8067%2]:123
jan 22 03:45:33 my-hostname dhclient[1700]: DHCPDISCOVER on eno1 to 255.255.255.255 port 67 interval 15 (xid=0xbd810a05)
jan 22 03:45:40 my-hostname systemd-networkd[827]: eno1: Configured
jan 22 03:45:48 my-hostname dhclient[1700]: DHCPDISCOVER on eno1 to 255.255.255.255 port 67 interval 17 (xid=0xbd810a05)
jan 22 03:46:05 my-hostname dhclient[1700]: DHCPDISCOVER on eno1 to 255.255.255.255 port 67 interval 16 (xid=0xbd810a05)
jan 22 03:46:11 my-hostname NetworkManager[826]: <warn>  [1516589171.4353] dhcp4 (eno1): request timed out
jan 22 03:46:11 my-hostname NetworkManager[826]: <info>  [1516589171.4354] dhcp4 (eno1): state changed unknown -> timeout
jan 22 03:46:11 my-hostname NetworkManager[826]: <info>  [1516589171.4437] dhcp4 (eno1): canceled DHCP transaction, DHCP client pid 1700
jan 22 03:46:11 my-hostname NetworkManager[826]: <info>  [1516589171.4437] dhcp4 (eno1): state changed timeout -> done
jan 22 03:46:11 my-hostname NetworkManager[826]: <info>  [1516589171.4440] device (eno1): state change: ip-config -> failed (reason 'ip-config-unavailable', internal state 'managed')
jan 22 03:46:11 my-hostname NetworkManager[826]: <warn>  [1516589171.4452] device (eno1): Activation: failed for connection 'Wired connection 1'
jan 22 03:46:11 my-hostname NetworkManager[826]: <info>  [1516589171.4501] device (eno1): state change: failed -> disconnected (reason 'none', internal state 'managed')
jan 22 03:46:11 my-hostname systemd-networkd[827]: eno1: Removing address: fe80::24e2:bba1:8b4f:8067/64 (valid forever)
jan 22 03:46:11 my-hostname NetworkManager[826]: <info>  [1516589171.4544] device (eno1): Activation: starting connection 'Wired connection 1' (b061a7d2-b434-3fc3-b3da-b9a3a86eb252)
jan 22 03:46:11 my-hostname NetworkManager[826]: <info>  [1516589171.4547] device (eno1): state change: disconnected -> prepare (reason 'none', internal state 'managed')
jan 22 03:46:11 my-hostname NetworkManager[826]: <info>  [1516589171.4553] device (eno1): state change: prepare -> config (reason 'none', internal state 'managed')
jan 22 03:46:11 my-hostname NetworkManager[826]: <info>  [1516589171.4973] device (eno1): state change: config -> ip-config (reason 'none', internal state 'managed')
jan 22 03:46:11 my-hostname NetworkManager[826]: <info>  [1516589171.4979] dhcp4 (eno1): activation: beginning transaction (timeout in 45 seconds)
jan 22 03:46:11 my-hostname NetworkManager[826]: <info>  [1516589171.5005] dhcp4 (eno1): dhclient started with pid 17880
jan 22 03:46:11 my-hostname dhclient[17880]: DHCPDISCOVER on eno1 to 255.255.255.255 port 67 interval 5 (xid=0x5b47ae5c)
```
I have the feeling that NetworkManager is trying to apply a DHCP based default configuration even though the interface is already up and running. ... 

The strange thing is that Network Manager is not even enabled ...

```
[root@my-hostname ~]# systemctl is-enabled NetworkManager
disabled
[root@my-hostname ~]# systemctl status NetworkManager
● NetworkManager.service - Network Manager
   Loaded: loaded (/usr/lib/systemd/system/NetworkManager.service; disabled; vendor preset: enabled)
   Active: active (running) since Mon 2018-01-22 05:08:33 CET; 7min ago
     Docs: man:NetworkManager(8)
 Main PID: 824 (NetworkManager)
    Tasks: 4 (limit: 16384)
   CGroup: /system.slice/NetworkManager.service
           ├─ 824 /usr/sbin/NetworkManager --no-daemon
           └─1649 /sbin/dhclient -d -q -sf /usr/libexec/nm-dhcp-helper -pf /var/run/dhclient-eno2.pid -lf /var/lib/NetworkManager/dhclient-e5a924a1-0cf9-356f-a411-8b4829e5ae3a-eno2.lease -cf /var/lib/NetworkManager/dhclient-eno2.conf eno2
```

**Comment by poettering** [comment] 2018-01-22 10:20
@LaKing it appears you are running NM and networkd in parallel on your interface. Please disable NM on it properly, and retry. Does it work then?

**Comment by LaKing** [comment] 2018-01-24 00:24
Removed Network Manager with dnf from both configs, and it seems that resolved the issue.

**Comment by yuwata** [comment] 2018-01-24 00:58
Good. So, let's close this.

**Comment by surabujin** [comment] 2018-02-28 09:40
@yuwata wait... there is an real issue here. Not related to influence from networkmanager. @jkhsjdhjs tell about problem in systemd-236 - network interface stays in unmanaged state untill systemd-networkd have been restarted.

recently I have updated to systemd-236(-r5 gentoo) and faced same issue. I have an interface enp3s0. It stays in unmanaged state after system boot. But if I restart systemd-netowrkd it become "routabe"

```
# networkctl 
IDX LINK             TYPE               OPERATIONAL SETUP     
  1 lo               loopback           carrier     unmanaged 
  2 sit0             sit                off         unmanaged 
  3 enp3s0           ether              routable    configured
  4 bond0            ether              off         unmanaged 
  5 virbr0           ether              no-carrier  unmanaged 
  6 virbr0-nic       ether              off         unmanaged 
  7 docker0          ether              no-carrier  unmanaged 
```

```
[Match]
Name=enp3s0
;MACAddress=60:a4:4c:35:2a:bc

[Network]
DHCP=yes
IPForward=yes
```

Boot log (cut unrelated chunks)
```
...
Feb 28 10:51:56 dbogun-pc kernel: r8169 Gigabit Ethernet driver 2.3LK-NAPI loaded
Feb 28 10:51:56 dbogun-pc kernel: ehci-pci 0000:00:1a.0: EHCI Host Controller
Feb 28 10:51:56 dbogun-pc kernel: r8169 0000:03:00.0: can't disable ASPM; OS doesn't 
have ASPM control
Feb 28 10:51:56 dbogun-pc kernel: ehci-pci 0000:00:1a.0: new USB bus registered, assi
gned bus number 1
Feb 28 10:51:56 dbogun-pc kernel: ehci-pci 0000:00:1a.0: debug port 2
Feb 28 10:51:56 dbogun-pc kernel: r8169 0000:03:00.0 eth0: RTL8168f/8111f at 0x000000
0051a008c0, 60:a4:4c:35:2a:bc, XID 08000800 IRQ 27
Feb 28 10:51:56 dbogun-pc kernel: r8169 0000:03:00.0 eth0: jumbo features [frames: 92
00 bytes, tx checksumming: ko]
...
Feb 28 10:51:58 dbogun-pc kernel: r8169 0000:03:00.0 enp3s0: renamed from eth0
Feb 28 10:51:58 dbogun-pc systemd-networkd-wait-online[1675]: ignoring: lo
Feb 28 10:51:58 dbogun-pc systemd-networkd[1671]: eth0: Interface name change detected, eth0 has been renamed to enp3s0.
...
Feb 28 10:51:57 dbogun-pc systemd-networkd[1671]: Enumeration completed
Feb 28 10:51:57 dbogun-pc systemd[1]: Started Network Service.
Feb 28 10:51:57 dbogun-pc systemd[1]: Starting Wait for Network to be Configured...
Feb 28 10:51:57 dbogun-pc systemd[1]: Reached target Network.
Feb 28 10:51:57 dbogun-pc systemd-networkd-wait-online[1675]: ignoring: lo
...
Feb 28 10:53:58 dbogun-pc systemd-networkd-wait-online[1675]: Event loop failed: Connection timed out
Feb 28 10:53:58 dbogun-pc systemd[1]: systemd-networkd-wait-online.service: Main process exited, code=exited, status=1/FAILURE
Feb 28 10:53:58 dbogun-pc systemd[1]: systemd-networkd-wait-online.service: Failed with result 'exit-code'.
```

All logs for systemd-networkd
```
# journalctl --boot=0 --unit=systemd-networkd
-- Logs begin at Tue 2017-05-16 15:55:49 EEST, end at Wed 2018-02-28 11:26:13 EET. --
Feb 28 10:51:57 dbogun-pc systemd[1]: Starting Network Service...
Feb 28 10:51:57 dbogun-pc systemd-networkd[1671]: Enumeration completed
Feb 28 10:51:57 dbogun-pc systemd[1]: Started Network Service.
Feb 28 10:51:58 dbogun-pc systemd-networkd[1671]: eth0: Interface name change detected, eth0 has been renamed to enp3s0.
Feb 28 10:52:09 dbogun-pc systemd-networkd[1671]: virbr0-nic: Gained carrier
Feb 28 10:52:11 dbogun-pc systemd-networkd[1671]: virbr0-nic: Lost carrier
Feb 28 10:55:41 dbogun-pc systemd-networkd[1671]: enp3s0: Gained carrier
Feb 28 10:55:43 dbogun-pc systemd-networkd[1671]: enp3s0: Gained IPv6LL
Feb 28 10:56:12 dbogun-pc systemd[1]: Stopping Network Service...
Feb 28 10:56:12 dbogun-pc systemd[1]: Stopped Network Service.
Feb 28 10:56:12 dbogun-pc systemd[1]: Starting Network Service...
Feb 28 10:56:13 dbogun-pc systemd-networkd[2239]: enp3s0: Gained IPv6LL
Feb 28 10:56:13 dbogun-pc systemd-networkd[2239]: Enumeration completed
Feb 28 10:56:13 dbogun-pc systemd[1]: Started Network Service.
Feb 28 10:56:13 dbogun-pc systemd-networkd[2239]: enp3s0: DHCPv4 address 172.18.194.70/24 via 172.18.194.1
Feb 28 10:56:13 dbogun-pc systemd-networkd[2239]: enp3s0: Configured
```

Do you  need a debug log?

**Comment by LaKing** [comment] 2018-03-01 01:02
Not sure if it is related to this, or related to anything here, but now on one of my servers with two NIC's my second interface is carrier:off, unmanaged, even though the ethernet port is connected and blinking. Should be DHCP, and has no .network file ... not so important, I just find it strange that I can't get that interface up. ...

**Comment by jkhsjdhjs** [comment] 2018-03-01 01:17
@surabujin I solved it by disabling udev device renaming.
> I solved this by disabling udev device renaming by placing an empty file named `80-net-name-slot.rules` in `/etc/udev/rules.d/`. My device would then be named eth0 instead of eno2, so I changed the name in my .network file too and it works.

You should try that too. If that fixes your problem there might be a real bug here.

**Comment by surabujin** [comment] 2018-03-02 10:17
@jkhsjdhjs I have tried to boot system with disabled eth0 renaming. And in this case it boot properly and "manage" to use eth0 interface. 

To disable eth0 renaming I have created file /etc/systemd/netword/10-eth0.link:
```
[Match]
OriginalName=eth0

[Link]
NamePolicy=kernel
```

systemd-networkd logs for both boots (when eth0 rename enabled I have restarted systemd-networkd service by hands to "enable" enp3s0 interface)
https://gist.github.com/surabujin/00c5b53ba52461bc26375e8431ae0732

**Comment by jkhsjdhjs** [comment] 2018-03-03 04:12
@surabujin That seems to be the same problem as I have.
My logs: https://fpaste.cc/v/7aaecf4e/raw

@yuwata As there seems to be a real bug here, shall we open a new issue or should this one be re-opened?

**Comment by yuwata** [comment] 2018-03-03 09:28
Please provide a minimal reproducer.

**Comment by surabujin** [comment] 2018-03-05 09:41
@yuwata 
> Please provide a minimal reproducer.

can you be more specific?

**Comment by surabujin** [comment] 2018-04-23 11:25
@yuwata you are extremely proactive in detecting and fixing bugs in systemd

**Comment by jkhsjdhjs** [comment] 2018-04-23 11:32
I think he means:
"Provide a step by step manual on how to reproduce the bug."

Unfortunately I'm unable to reproduce it because I don't own the server where the problem occured anymore.

**Comment by yuwata** [comment] 2018-04-24 03:57
@surabujin and @jkhsjdhjs Sorry for late reply. I am not sure it is related to the issue which you are faced. But I file a similar issue in #8794 with a simple reproducer. I guess that on your systems `systemd-networkd.service` starts earlier than the udev interface renaming. So, #8794 inhibits the interface become managed.

**Comment by yuwata** [comment] 2018-04-24 06:13
Still I am not sure how to reproduce this. But I've posted PR #8795. If possible, please test it. Thank you.

**Closed as completed** 2018-04-26 19:05 UTC
Labels: network, needs-reporter-feedback ❓

**Comment by marcstreeter** [comment] 2018-10-20 16:04
I'm going to have to retract the statement I just made....because it sometimes happens and sometimes doesn't.  I was about to post my journalctl logs to better help anyone looking into it, however, I wanted to remove all the noise from what I had been trying earlier, so I cleared my logs and restarted the machine for fresh logs of the issue.  However, I was able to log in without problem: my static ip was accepted as it should be.  So I restarted again this time clearing the logs to see if by some weird logic journalctl logs were the issue.  This time the static ip didn't take. So I restarted multiple times without clearing any logs or doing anything, reattempting to ssh in after a minute or two of being at the login screen.  Some times the static rules would take and I could sign in, other times not.  This is with no changes to the system in between restarts.  ¯\_(ツ)_/¯   So I guess, anything I could give to you I'm willing to give, meh...

**Comment by tconrado** [comment] 2020-09-01 23:37
@marcstreeter I have similar problem, but on mine, it does not consistently assign the static IP for the bond. Everything else is ok.
So, tried about 10 restarts, and some times it does bring up the IP and sometimes it does not.
for me it points to a race condition too. Also a simple restart on systemd-networks always assign the IP as expected. I'm using Netplan, doing netplan apply, also solves the problem. Hence, I guess, that something is not available sometimes when systemd-network executes. (we are using Ubuntu 18.04.1 LTS)
