### ISSUE TITLE
Bluetooth can't connect to both keyboard and headphones

### ISSUE THREAD

**Issue by katkasoft** [systemd/systemd#30659] opened 2023-12-29 17:31 UTC
### systemd version the issue has been seen with

255

### Used distribution

Arch Linux

### Linux kernel version used

6.6.8-arch1-1 

### CPU architectures issue was seen on

amd64

### Component

bluetooth

### Expected behaviour you didn't see

I expected working both bluetooth devices

### Unexpected behaviour you saw

Bluetooth can't connect to both keyboard and headphones

**Comment by yuwata** [comment] 2023-12-29 17:58
No useful information. There is no hint that the issue is caused by systemd. Closing.

**Closed as not planned by yuwata** 2023-12-29 17:58 UTC
Labels: misfiled

**Comment by YHNdnzj** [comment] 2023-12-29 18:00
This report contains no valuable information. An how does bluetooth have anything to do with systemd?

Closing as misfiled.

**Comment by katkasoft** [comment] 2023-12-29 18:03
> This report contains no valuable information. And how does bluetooth have anything to do with systemd?
> 
> Closing as misfiled.

i thought bluetooth.service is built-in in systemd

**Comment by yuwata** [comment] 2023-12-29 18:13
> > This report contains no valuable information. And how does bluetooth have anything to do with systemd?
> > Closing as misfiled.
> 
> i thought bluetooth.service is built-in in systemd

No.
