### ISSUE TITLE
the udev event for the lid is considered as a keyboard event

### ISSUE THREAD

**Issue by bohanubis** [systemd/systemd#28942] opened 2023-08-23 22:54 UTC
### systemd version the issue has been seen with

254

### Used distribution

arch

### Linux kernel version used

6.4.11-arch2-1

### CPU architectures issue was seen on

aarch64

### Component

udev rule files

### Expected behaviour you didn't see

when I close the lid it actually suspends
pressing fn+f2/3 actually increases and decreases brightness
actually I guess the fn+f2/3 is out of the bound of this issue since for some reason pressing each of those two keys give the same scancode so a hp problem
the next stuff is just talking about the lid since its the main problem
anyway so what are the outputs of something like acpi_listen "button/wlan WLAN 00000080 00000000 K" so its thinking that its a keyboard button the one that toggles wifi moreover output from dmesg -W
"[ 1111.905107] atkbd serio0: Unknown key released (translated set 2, code 0xd8 on isa0060/serio0).
[ 1111.905120] atkbd serio0: Use 'setkeycodes e058 <keycode>' to make it known."
basically the lid is considered a part of the keyboard
and running evtest /dev/input/event0 and closing and reopening the lid confirms that hypothesis

"Event: time 1692830792.214459, type 4 (EV_MSC), code 4 (MSC_SCAN), value d7
Event: time 1692830792.214459, type 1 (EV_KEY), code 238 (KEY_WLAN), value 0"
the output since it will matter

and from the guides in the web I haven't found a guide to do something like this
MSC_ID_d7=SW_LID
its just remapping keyboard scancodes to keycodes and I guess I should tell udev that its not actually a key its the lid

I guess a solution is to tell me how to actually either remap between multiple devices or actually as I said maybe just tell it what is it actually
and what is even the device name I should put "Lid Switch" like with a space this makes no sense

### Steps to reproduce the problem

this is a hardware problem I guess

**Comment by beh-10257** [comment] 2023-08-23 23:07
I just have to clarify that if anything you feel like I was angry for some reason I wasn't
If anything I should be angry at hp for giving the same scan code to two different keys

**Comment by yuwata** [comment] 2023-08-24 01:32
Please try to edit hwdb.d/60-keyboard.hwdb, and submit the change as a PR. Thank you.

**Comment by beh-10257** [comment] 2023-08-24 09:48
well @yuwata I found this in 60-keyboard.hwdb
```
evdev:atkbd:dmi:bvn*:bvr*:svnHP*:pnHP*ProBook*640*G2*:*
 KEYBOARD_KEY_85=unknown                                # lid close; also reported via special evdev
 KEYBOARD_KEY_f8=unknown                                # rf kill; also reported via special evdev
```
basically I guesss I have to do the same thing but what do they even mean by creating a special evdev
. is there even a wiki or something to learn how to edit these udev rules
. there is no KEYBOARD_KEY_d7=lid
as far as I am aware so yeah what I should do should I put it as unknown
+ I am willing to fix this its just I have no idea what are even the things that can be put in KEYBOARD_KEY_XX=WHAT??

**Comment by yuwata** [comment] 2023-08-24 11:21
Not sure, but e.g. please try to add `KEYBOARD_KEY_d7=unknown` with matching modalias.
See also the comments in 60-keyboard.hwdb how to add custom entry and apply the change.

**Comment by beh-10257** [comment] 2023-08-24 20:09
@yuwata that basically stops the wlan thing and makes closing the lid meaningless
+ another update I after trying to see evtest /dev/input/event3 (keyboard) another time I noticed that there is another unknown button
```
Event: time 1692907126.684452, type 4 (EV_MSC), code 4 (MSC_SCAN), value d8
Event: time 1692907126.684452, -------------- SYN_REPORT ------------
```
and this button is basically the button that is supposed to tell udev that the lid is closed 
and the d7 one is the one saying that the lid have opened
so yeah my question is still how can I map this stuff to make it actually work with udev like show up when I run evtest /dev/input/event0 (the lid supposedly)
and the devastating thing is running `cat /proc/acpi/button/lid/LID0/state` actually returns the actual state of the lid so why is udev not getting it

**Comment by beh-10257** [comment] 2023-08-28 15:25
hello again @yuwata sorry for tagging you again so as I said is what I just said even possible
like to link KEYBOARD_KEY_d7 in /dev/input/event3 to opening the lid in /dev/input/event0
and KEYBOARD_KEY_d8 in /dev/input/event3 to closing the lid in /dev/input/event0
```
#   Event type 5 (EV_SW)
#     Event code 0 (SW_LID)
#        State 0
```
that was a part of the output from `evemu-describe /dev/input/event0`
so all I want I guess is to link those two keys to each state for this `SW_LID`
my question is that even possible
all I want is for my logind.conf to actually work and thanks

**Comment by beh-10257** [comment] 2023-09-05 19:43
update so after rechecking journalctl I noticed this line:
`ACPI: button: The lid device is not compliant to SW_LID.`
so I suppose this is a kernel issue I don't know to be honest

**Comment by yuwata** [comment] 2023-09-06 17:12
@whot Could you help ?

**Comment by whot** [comment] 2023-09-07 01:30
> so all I want I guess is to link those two keys to each state for this SW_LID
> my question is that even possible

nothing in userspace that I'm aware of can link those two to the sw state, so there's no hwdb/udev magic you can immediately use. There's a second problem in that even assuming we had a `KEY_LID_OPEN` and `KEY_LID_CLOSE` they'd eventually both end up as logically down and only send key repeat events for when the respective action happens (and key repeat events are filtered by virtually all consumers).

This really needs to be fixed in the kernel, maybe @jwrdegoede can point you in the right direction here.

**Comment by beh-10257** [comment] 2023-09-07 09:32
if the problem is in the kernel I guess since

> and the devastating thing is running cat /proc/acpi/button/lid/LID0/state actually returns the actual state of the lid

so the kernel is actually giving the actual state of the lid for /proc/acpi/button/lid/LID0/state but giving it as a keypress for udev
yeah that's all I have to say maybe that can help or something at least we are not starting from scratch

**Comment by jwrdegoede** [comment] 2023-09-16 21:23
If there is a working /proc/acpi/button/lid/LID0/state then there should really also be a "Lid Switch" evdev device.

Can you try running: "sudo evtest" and then see if there is a "Lid Switch" /dev/input/event# node and if yes select that and see if it sends SW_LID events when you open/close the lid ?

**Comment by beh-10257** [comment] 2023-09-17 14:36
https://github.com/systemd/systemd/assets/77834479/6ae620d3-d581-4100-a517-6f3076ea225b

hello @jwrdegoede I think that pretty much explains everything
I don't know how the kernel works
but at least what I can say is that I haven't messed up this system since putting fedora in a live usb and actually closing and reopening the lid doesn't
get detected as well same as here its always a keyboard key

**Comment by jwrdegoede** [comment] 2023-09-17 15:15
> hello @jwrdegoede I think that pretty much explains everything
I don't know how the kernel works

Ok, so for folks reading along, what the linked video shows is the output of "watch cat /proc/acpi/button/lid/LID0/state" (polling the ACPI _LID method) changes, while evtest on the "Lid Switch" shows no output.

This means that the ACPI object with the _LID method is not getting ACPI notify events when the change happens. Which can have various causes.

@beh-10257 in your original report you mention that you are on an aarch64 machine. Do you really have a laptop with a 64 bit ARM processor? Or do you mean that you are running the 64 bit x86 (x86_64) version of Arch Linux?  What is the output of `uname -a` ?

Can you run:

```
dmesg > dmesg.txt
sudo acpidump -o acpidump.txt
```

And attach both .txt files here please?  Also which model laptop do you exactly have ?

**Comment by beh-10257** [comment] 2023-09-17 15:53
hello again @jwrdegoede so the output for `uname -a` is `Linux behepc 6.5.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 13 Sep 2023 08:37:40 +0000 x86_64 GNU/Linux`
and I am using intel i5-10300H so its the 64 bit kernel that's just arch naming I guess
I guess this image may help
![nice](https://github.com/systemd/systemd/assets/77834479/91dba5fc-9d5c-411c-9aa5-60d3b428502c)

the dmesg.txt: [dmesg.txt](https://github.com/systemd/systemd/files/12643142/dmesg.txt)
the acpidump.txt:  [acpidump.txt](https://github.com/systemd/systemd/files/12643143/acpidump.txt)
+ my laptop is in `HP Pavilion Gaming Laptop 15-dk1000` series there are a lot of models I just chose the model where I have a gtx 1650ti and i5-10300H and 500gb ssd and 16gb of ram I don't really know what the exact model is

update and since its been a while since I checked on fedora I just tried it today with fedora 38
maybe this can help as well
[Screencast from 2023-09-17 11-13-01.webm](https://github.com/systemd/systemd/assets/77834479/fb6704e5-b06a-45f7-bbb9-558d789ef881)
![Screenshot from 2023-09-17 11-16-04](https://github.com/systemd/systemd/assets/77834479/7ca92d72-d268-49d2-b75b-1985f6180e35)

**Comment by jwrdegoede** [comment] 2023-09-17 17:08
Ok, so your LID device is described like this in the DSDT of your ACPI tables:

```
        Device (LID0)
        {
            Name (_HID, EisaId ("PNP0C0D") /* Lid Device */)  // _HID: Hardware ID
            Name (PLID, One)
            Method (_STA, 0, NotSerialized)  // _STA: Status
            {
                Return (0x0F)
            }

            Method (_LID, 0, NotSerialized)  // _LID: Lid Status
            {
                Local0 = ^^EC0.LIDF /* \_SB_.PCI0.LPCB.EC0_.LIDF */
                If (Local0)
                {
                    Return (Zero)
                }

                Return (One)
            }
        }
```

So nothing special and it gets notified about changes of the LIDF flag by an embedded-controller query:

            Method (_Q15, 0, NotSerialized)  // _Qxx: EC Query, xx=0x00-0xFF
            {
                Debug = "=====QUERY_15====="
                P80H = 0x15
                If (IGDS)
                {
                    Local0 = LIDF /* \_SB_.PCI0.LPCB.EC0_.LIDF */
                    Local0 = ~Local0
                    Local0 &= One
                    Local0 += 0x02
                    If (^^^GFX0.GLID (Local0))
                    {
                        ^^^GFX0.CLID |= 0x80000000 /* External reference */
                    }
                }

                Notify (LID0, 0x80) // Status Change
            }

Again nothing special.

I've also checked if the ACPI EC code is recognizing your EC properly and that all looks fine.

But for some reason the embedded-controller in your laptop is sending a PS/2 keypresses event (which gets mapped to KEY_WLAN, instead of sending a 0x15 query event to ACPI.

I suspect that the embedded controller needs to be poked in some way to make it send the 0x15 query instead of sending 0xd7 / 0xd8 PS/2 scancode events. That or somehow all query events from the EC are broken on your model and the scancodes are just extra events which can be ignored.

The problem with these kinda bugs is that the necessary poke is vendor (and model) specific and there really is no way for us (Linux devs) to know what kinda magic poke is necessary.

Are you on the latest BIOS? If not I would suggest updating your BIOS version, because this does look like it might be a BIOS bug.

**Comment by beh-10257** [comment] 2023-09-17 19:06
hello again @jwrdegoede so I just upgraded my bios to the latest version (it broke my grub installation for some reason)
arch-chroot saved me
anyway so there is basically no difference: the same exact issue
+ I want to point out that actually the airplane mode button just happen to not work in my system as well and that's ironic I would say

and so since I guess  the bios update haven't solved this issue

my question is "so since the hardware is specific to me should I just postpone the issue until I understand c enough to solve my own issue" or is it that a specif model solution is already out of the question for the Linux 
all of this is considering the fact that hp will not fix a 3 year old bios (I bet they will give out the usual linux is not supported response)

another note if embedded-controller is responsible for media key and those fancy fn+fX features if yes than other than
the stupid brightness up/down keys sending the same exact scancode there are no other issues

**Comment by jwrdegoede** [comment] 2023-09-18 14:43
If the patch which I attached to my previous comment helps please run:

```
grep . /sys/class/dmi/id/* 2> /dev/null
```

As *normal* user and then copy and paste the output into a comment here. Then I can turn my quick hack into a proper patch to add a quirk for your laptop for this.

**Comment by beh-10257** [comment] 2023-09-19 11:59
anyway hello again sorry I took a day to respond It was a busy day yesterday

anyway about that patch it basically solved every single problem
from the brightness keys
to the airplane mode key
and the lid obviously
so yeah with that patch we can say that this laptop model is supported by the linux kernel

so yeah thanks a lot @jwrdegoede for your help + when you go around to making a pull request can you link it here
so I will know when it will be merged
and this is that [command output](https://github.com/systemd/systemd/files/12659456/nice.txt)

**Comment by jwrdegoede** [comment] 2023-09-20 13:10
I have submitted the kernel patch upstream now:
https://lore.kernel.org/linux-acpi/20230920130506.8595-1-hdegoede@redhat.com/

Since this is a kernel issue and not a systemd issue, can you close this issue please?

**Closed as completed** 2023-09-20 15:35 UTC
Labels: hwdb, not-our-bug
