### ISSUE TITLE
Support CD (checking disabled) in request

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#8450] opened 2018-03-14 10:15 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 238

### Used distribution

> Linux From Scratch

### In case of bug report: Expected behaviour you didn't see

Debugging a problem with DNSSEC, a response should be returned when manually requesting to disable the checking.

```
$ dig +dnssec +cdflag @127.0.0.53 www.freedesktop.org

; <<>> DiG 9.9.6-P1 <<>> +dnssec +cdflag @127.0.0.53 www.freedesktop.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOTIMP, id: 57088
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 65494
;; QUESTION SECTION:
;www.freedesktop.org.		IN	A

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Mar 14 11:12:00 CET 2018
;; MSG SIZE  rcvd: 48
```

From the manual page:

>        +[no]cdflag
>            Set [do not set] the CD (checking disabled) bit in the query. This
>            requests the server to not perform DNSSEC validation of responses.

### In case of bug report: Unexpected behaviour you saw

> `status: NOTIMP` is returned.

### In case of bug report: Steps to reproduce the problem

> Run `dig +dnssec +cdflag @127.0.0.53 www.freedesktop.org`.

**Comment by poettering** [comment] 2018-03-20 17:51
Duplicate of #4621

**Closed as completed by poettering** 2018-03-20 17:51 UTC
Labels: RFE 🎁, resolve, duplicate
