### ISSUE TITLE
systemd hardcodes SYS_UID_MAX instead of parsing /etc/login.defs at runtime

### ISSUE THREAD

**Issue by nmiell** [systemd/systemd#4850] opened 2016-12-08 05:04 UTC
### Submission type
  - [x] Bug report

### systemd version the issue has been seen with
> 231

### Used distribution
> Fedora 25

### Unexpected behaviour you saw
> systemd parses the build machine's copy of /etc/login.defs for SYS_UID_MAX at compile time and uses the extracted hard-coded value instead of parsing /etc/login.defs on the install machine at runtime.

> This prevents coredumpctl from allowing users to see their own core dumps because journald doesn't log core dumps (or anything else) in a journal file that the user is allowed to read. 

### In case of bug report: Steps to reproduce the problem
> Crash something as an unprivileged user with a UID less than the value of SYS_UID_MAX that was extracted from /etc/login.defs on the build machine.

**Comment by poettering** [comment] 2016-12-08 09:48
Sorry, but I am strongly against reading SYS_UID_MAX during runtime. It's not really a user setting. It's not really up to admins to change this, this is baked into the distro, and can only be chosen realistically by the distro vendor. The login.defs setting doesn't really work, as the UID is replicated at tons of places (for example fedora ships an explicit check for "1000" in a good chunk of the PAM snippets).

Sorry, but this is not going to be added. It's a compile-time setting, not a runtime-setting. 

Duplicate of #3855.

**Closed as completed by poettering** 2016-12-08 09:48 UTC
Labels: duplicate
