### ISSUE TITLE
"systemd-nspawn  --directory=/install/netboot/sles12.1/ppc64le/compute/rootimg/" complains "Failed to install seccomp audit filter: Invalid argument  Container rootimg failed with error code 1."

### ISSUE THREAD

**Issue by immarvin** [systemd/systemd#3665] opened 2016-07-06 03:10 UTC
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> ```
> c910f03c05k27:/opt/xcat/share/xcat/netboot/sles # systemctl --version
> systemd 210
> +PAM +LIBWRAP +AUDIT +SELINUX -IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ +SECCOMP +APPARMOR
> c910f03c05k27:/opt/xcat/share/xcat/netboot/sles # systemd --version
> systemd 210
> +PAM +LIBWRAP +AUDIT +SELINUX -IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ +SECCOMP +APPARMOR
> ```
> 
> _NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> ```
> c910f03c05k27:/opt/xcat/share/xcat/netboot/sles # cat /etc/os-release 
> NAME="SLES"
> VERSION="12-SP1"
> VERSION_ID="12.1"
> PRETTY_NAME="SUSE Linux Enterprise Server 12 SP1"
> ID="sles"
> ANSI_COLOR="0;32"
> CPE_NAME="cpe:/o:suse:sles:12:sp1"
> ```
> ### In case of bug report: Expected behaviour you didn't see
> 
> ```
> c910f03c05k27:/opt/xcat/share/xcat/netboot/sles # cat /etc/os-release 
> NAME="SLES"
> VERSION="12-SP1"
> VERSION_ID="12.1"
> PRETTY_NAME="SUSE Linux Enterprise Server 12 SP1"
> ID="sles"
> ANSI_COLOR="0;32"
> CPE_NAME="cpe:/o:suse:sles:12:sp1"
> ```
### In case of bug report: Unexpected behaviour you saw

```
c910f03c05k27:/opt/xcat/share/xcat/netboot/sles # systemd-nspawn  --directory=/install/netboot/sles12.1/ppc64le/compute/rootimg/ 
Failed to install seccomp audit filter: Invalid argument
Container rootimg failed with error code 1.

```

**Comment by poettering** [comment] 2016-07-06 04:02
first of all, we only track bugs in the two most recently released upstream versions of system upstream, and the submission form really tries to make that clear. 210 is waaaay to old for this.

It appears you are on ppc64le, is that right? if so, this really smells as if libseccomp doesn't support that architecture correctly, as it is the library that returns EINVAL on that arch, when we try to install a seccomp filter for AF_NETLINK on the audit mcast group, it really shouldn't. Hence, please ask yout distro to fix that lib on that arch, or -- if they don't want that -- ask them to disable seccomp in their builds on ppc64le. Either way this is nothing we can fix in systemd.

Closing hence, since this is clearly too old a systemd version to track here and is not a bug in systemd anyway, but in libseccomp. Hope that makes sense.

**Closed as completed by poettering** 2016-07-06 04:02 UTC
Labels: not-our-bug, version-too-ancient
