### ISSUE TITLE
Activate arbitrary units with StartLimitAction

### ISSUE THREAD

**Issue by bradbishop** [systemd/systemd#6016] opened 2017-05-23 15:08 UTC
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

HEAD

### Used distribution

Yocto 2.2

The proposal here is to start units similar to OnFailure but after exceeding StartLimitInterval/Burst.  Put another way, enable something other than reboot incantations in StartLimitAction.

Before I start writing code, was looking for some general direction.  Would the project be interested in function like this?  Any suggestions on implementation specifics?

Some background on our use case....

We are using systemd in an embedded system with an ARM SOC with three watchdog IP blocks ( so three watchdog devices ).  One of the watchdogs serves in the usual sense, and we have systemd pinging it to protect against kernel and/or systemd hangs.

The other watchdogs are configured to do something other than reset the processor.  For example, we have one that when it trips, it wiggles a SOC gpio hooked up to a fan control chip (i2c device) input that instructs the chip to run the connected fans at full speed.

We have number of applications that work in concert to control the fans in our system.  We want to protect the system thermally (by running the fans at full speed) from failures in any of these applications.

Our implementation plan is to have an instance of the busybox watchdog applet pinging the watchdog connected to the fan control chip via the gpio.  The busybox service unit would conflict with a target unit.  When one of the control application units exceeds its StartLimitInterval/Burst, the target would be started (via the enhancements suggested here), stopping the watchdog unit, tripping the watchdog.

Thanks for reading - brad

**Comment by fsateler** [comment] 2017-05-23 15:27
This is a duplicate of https://github.com/systemd/systemd/issues/3613 , closing in favor of the older issue.

**Closed as completed by fsateler** 2017-05-23 15:28 UTC
Labels: duplicate
