### ISSUE TITLE
nspawn: containers with mounted /sys/fs/cgroup aren't registered by machined

### ISSUE THREAD

**Issue by nhlfr** [systemd/systemd#5301] opened 2017-02-10 11:23 UTC
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232
> in 231 and older versions this bug doesn't exist

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Fedora 25

### In case of bug report: Expected behaviour you didn't see

> I expect the containers running with --bind=/sys/fs/cgroup argument to be registered by machined.

### In case of bug report: Unexpected behaviour you saw

> After running the container with --bind=/sys/fs/cgroup **second time (and more)** it doesn't get registered by machined.

### In case of bug report: Steps to reproduce the problem

> First time

```
systemd-nspawn --bind=/sys/fs/cgroup rootfs
```
```
# machinectl list
MACHINE                          CLASS     SERVICE
rootfs                           container systemd-nspawn

1 machine listed.
```

> Second time, after terminating the container we just created above

```
systemd-nspawn --bind=/sys/fs/cgroup rootfs
```
```
# machinectl list
MACHINE                          CLASS     SERVICE

0 machines listed.
```

**Comment by poettering** [comment] 2017-02-10 13:40
not sure i follow... why would you even specify --bind=/sys/fs/cgroup? We set up /sys/fs/cgroup anyway for you...

Do you see anything in the logs about this? specifically machined logs?

**Comment by poettering** [comment] 2017-02-10 17:42
So, I looked into this now, as I managed to reproduce this locally, but I came to the conclusion that this is actually not a bug. Here's what happens: we use cgroup namespacing these days. By doing the bind mount you do you make the host hierarchy available to the container, which is supposed to only see its own little subhierarchy. This is highly problematic, as systemd inside of the container will no muck around in the host's cgroup tree, thinking it was its own private property. Moreover /proc/$PID/cgroup will not match with reality (as that still reflects the path in the subtree, not the whole tree). Basically, you are in deep trouble.

machined actually registers the machine properly, but quickly notices that the machine actually died on its own. It does that, because it realizes that the cgroup the machine is supposed to be in runs empty. But it does so, simply because the stuff is actually living in a different place now: in the host cgroup tree...

Hence, there isn't really a "bug" here... What you are doing is basically shooting yourself (or actually: systemd) in the foot. You are welcome to do so, but if systemd misbehaves if you shoot it in its foot, then that's hardly surprising.

Or in other words: what you are doing voids the warranty, please don't do it, or live with the consequences: a broken machined and systemd.

Closing this, I hope this makes sense.

**Closed as completed by poettering** 2017-02-10 17:42 UTC
Labels: nspawn, machine, not-a-bug
