### ISSUE TITLE
machinectl: GetMachineOSRelease dbus call error is not handled 

### ISSUE THREAD

**Issue by Stratold** [systemd/systemd#5162] opened 2017-01-26 17:18 UTC
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

```
# machinectl --version
systemd 232
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> machinectl returns list of running machines

### In case of bug report: Unexpected behaviour you saw

> If kvm VM launched via libvirt is running on the host, executing machinectl fails with exit code 1.
```
# strace -f -s 1200 machinectl --no-pager list
...
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\6\1s\0\6\0\0\0:1.157\0\0\10\1g\0\7a(ssso)\0\0\0\0\7\1s\0\6\0\0\0:1.146\0\0<\4\0\0\0\0\0\0\23\0\0\0qemu-1-win2012webex\0\2\0\0\0vm\0\0\f\0\0\0libvirt-qemu\0\0\0\0009\0\0\0/org/freedesktop/machine1/machine/qemu_2d1_2dwin2012webex\0\0\0\0\0\0\0 \0\0\0qemu-7-f90-dvr-node-2-controller\0\0\0\0\2\0\0\0vm\0\0\f\0\0\0libvirt-qemu\0\0\0\0N\0\0\0/org/freedesktop/machine1/machine/qemu_2d7_2df90_2ddvr_2dnode_2d2_2dcontroller\0\0 \0\0\0qemu-6-f90-dvr-node-4-controller\0\0\0\0\2\0\0\0vm\0\0\f\0\0\0libvirt-qemu\0\0\0\0N\0\0\0/org/freedesktop/machine1/machine/qemu_2d6_2df90_2ddvr_2dnode_2d4_2dcontroller\0\0\25\0\0\0qemu-2-f90-dvr-master\0\0\0\2\0\0\0vm\0\0\f\0\0\0libvirt-qemu\0\0\0\0?\0\0\0/org/freedesktop/machine1/machine/qemu_2d2_2df90_2ddvr_2dmaster\0\0\0\0\0\5\0\0\0.host\0\0\0\4\0\0\0host\0\0\0\0\0\0\0\0\0\0\0\0)\0\0\0/org/freedesktop/machine1/machine/_2ehost\0\0\0\37\0\0\0qemu-4-f90-dvr-node-1-ceph-comp\0\2\0\0\0vm\0\0\f\0\0\0libvirt-qemu\0\0\0\0O\0\0\0/org/freedesktop/machine1/machine/qemu_2d4_2df90_2ddvr_2dnode_2d1_2dceph_2dcomp\0\0\0\0\0 \0\0\0qemu-5-f90-dvr-node-3-controller\0\0\0\0\2\0\0\0vm\0\0\f\0\0\0libvirt-qemu\0\0\0\0N\0\0\0/org/freedesktop/machine1/machine/qemu_2d5_2df90_2ddvr_2dnode_2d3_2dcontroller\0\0\37\0\0\0qemu-3-f90-dvr-node-5-ceph-comp\0\2\0\0\0vm\0\0\f\0\0\0libvirt-qemu\0\0\0\0O\0\0\0/org/freedesktop/machine1/machine/qemu_2d3_2df90_2ddvr_2dnode_2d5_2dceph_2dcomp\0", iov_len=1140}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 1140
sendmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\1\4\1\30\0\0\0\3\0\0\0\247\0\0\0\1\1o\0\31\0\0\0/org/freedesktop/machine1\0\0\0\0\0\0\0\3\1s\0\23\0\0\0GetMachineOSRelease\0\0\0\0\0\2\1s\0 \0\0\0org.freedesktop.machine1.Manager\0\0\0\0\0\0\0\0\6\1s\0\30\0\0\0org.freedesktop.machine1\0\0\0\0\0\0\0\0\10\1g\0\1s\0\0", iov_len=184}, {iov_base="\23\0\0\0qemu-1-win2012webex\0", iov_len=24}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 208
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\3\1\1H\0\0\0/\0\0\0_\0\0\0\5\1u\0\3\0\0\0", iov_len=24}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 24
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\6\1s\0\6\0\0\0:1.157\0\0\4\1s\0'\0\0\0org.freedesktop.DBus.Error.NotSupported\0\10\1g\0\1s\0\0\7\1s\0\6\0\0\0:1.146\0\0C\0\0\0Requesting OS release data is only supported on container machines.\0", iov_len=160}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 160
close(3)                                = 0
exit_group(1)                           = ?
```

### In case of bug report: Steps to reproduce the problem

> Launch VM in libvirt and run machinectl

**Comment by fsateler** [comment] 2017-01-26 17:44
Duplicate of #4918 , fixed in #4972

**Closed as completed by fsateler** 2017-01-26 17:44 UTC
Labels: bug 🐛, machine, duplicate
