### ISSUE TITLE
Predictable interface naming is flawed

### ISSUE THREAD

**Issue by zrm** [systemd/systemd#3715] opened 2016-07-13 15:17 UTC
### Submission type
- [X] Bug report
- [X] Request for enhancement (RFE)
### Used distribution

> Debian/Ubuntu
### Predictable interface naming is flawed

This bug describes a design flaw. It can be summarized as "network interface names should be names, not addresses."

Naming interfaces with physical addresses causes trouble.

It makes the simple case complicated. A majority of machines previously had eth0, maybe also wlan0, and no other physical interface. Now they have enp3s5 or enp4s0 or enxbadbadbadbad, all different names. But the admin needs the interface name when configuring services and firewall rules. It was a lot easier to remember and type eth0 than, and I swear this is the actual name it gave, enP2p32s15f0.

Existing scripts and documentation reference the default names. They have to be adjusted if your specific machine has any other interface name, only now a different name is the rule rather than the exception.

People often suggest manually renaming the interfaces back to something sensible. This has always been a common practice for firewalls and routers, where historically you had an entry in /etc/udev/rules.d/70-persistent-net.rules and could just change the 'NAME=' entry from "eth1" to "outside0" to have meaningful names. But that file is not generated by default anymore, so the user has to create an equivalent file from scratch, read more documentation, find the interface hardware address, debug more typos and formatting errors and so on. Setting interface names manually is effectively turning off the "feature" though, and that is now harder than before.

It also gets the less simple cases wrong.

Suppose I have used the builtin network interface for a while and now upgrade by adding a faster one. If the old name was eth0 then I give the new interface the old name and I'm done. But if the old name was enp2s0 then I have an ugly choice. Either I update firewall rules and daemon configs and every other reference on the system from enp2s0 to enp4s0 and hope I don't miss anything, or now I disable "predictable naming" and confuse everything by renaming enp4s0 to enp2s0 even though that name would both indicate the wrong device and imply the device is using "predictable naming" when it isn't. 

Using topology as part of an interface name also makes the names less consistent. Put a laptop in a dock, plug in a thunderbolt PCIe cage, remove a GPU https://github.com/systemd/systemd/issues/2811, change a BIOS setting https://github.com/systemd/systemd/issues/563 and you can change the PCI topology and thus the name of all or none or some of your interfaces. When udev was using hardware MAC, non-network interface changes would rarely change network interface names and could rarely if ever silently cause an interface to use the name previously held by a different interface.

Anything that could unexpectedly change the name of a firewall outside interface to that of a firewall inside interface is problematic.

So here is a suggested alternative (not altogether unlike the old way).

After all network interfaces present at boot are discovered, consult the filesystem for the names of known interfaces and assign them. If a known interface is not found but an interface with the same MAC and a different slot exists, keep the name and update the slot. If there is no interface with that MAC but there is a new interface in the same slot, keep the name and update the MAC. Then deterministically order all the unmatched physical interfaces using the firmware index or PCI bus location, name them in order ethN, ethN+1, ..., wlanN, wlanN+1 and so on and write the new interfaces to the filesystem. An interface added after boot becomes ethN+2 etc.

With deterministic reordering after detection, machines that cannot write rules to the filesystem still use deterministic names for everything present at boot. But writing the interfaces to file when possible ensures that previously seen devices always get the same names even if PCI topology changes. And makes it easier for the user to set names by updating the name in a file that already exists and describes every existing interface. Matching known interfaces first by MAC then by slot means that an interface will keep its name when moved to a different slot or when PCI is renumbered, but if a NIC is altogether removed and another is put in the same slot (i.e. replacing a bad NIC or in a VM that randomly generates the MAC) then that works too. Then the user setting a custom interface name doesn't break the system's ability to update it in those cases.

And every device with only one ethernet/wifi interface will still default to eth0/wlan0.

This doesn't guarantee consistent names on a device without a writable filesystem after interfaces are added or removed, but neither does the current method. Firmware will commonly change PCI enumeration order based on which devices are present at POST. At least this way interface names are only based on the order of network interfaces relative to each other and not the entire universe of things that could cause any PCI renumbering.

A possible variant on this is to use different names than the kernel uses to avoid the rename race. So the kernel will set interface names eth0, eth1 and we rename them to enet0, enet1. In which case the default interface becomes enet0. Or do it the other way around and have the kernel assign enetN and then rename to the traditional ethN.

**Comment by mbiebl** [comment] 2016-07-13 15:38
2016-07-13 17:17 GMT+02:00 zrm notifications@github.com:

> And every device with only one ethernet/wifi interface will still default
> to eth0/wlan0.

How do you determine that there will always be only one interface? What
happens if someone plugs in an USB ethernet or wlan adapter?

## 

Why is it that all of the instruments seeking intelligent life in the
universe are pointed away from Earth?

**Comment by zrm** [comment] 2016-07-13 15:42
> How do you determine that there will always be only one interface? What happens if someone plugs in an USB ethernet or wlan adapter?

There won't always be one interface. But if there is only one interface then it will be eth0 or wlan0 instead of an effectively random name derived from the PCI topology.

**Comment by mbiebl** [comment] 2016-07-13 15:44
That doesn't answer my question

**Comment by mbiebl** [comment] 2016-07-13 15:50
Heck, I do think the new names are ugly as well, but all alternatives that have been proposed so far don't work. The old scheme didn't and yours doesn't either.

**Comment by zrm** [comment] 2016-07-13 16:04
Can you be more specific than "doesn't work"?

If you add an interface after boot it has the same effect as adding it during the next boot. The existing interface is eth0 and the new one is eth1. That gets written to the filesystem so that those names persist.

The problematic scenario is when you can't write to the filesystem and you want names to be persistent against hardware changes. But for that to work you need names derived from the MAC because hardware changes can also change the PCI ordering. It would be silly to subject everyone to MAC-derived names by default instead of only using them where they're needed.

**Comment by gdamjan** [comment] 2016-07-13 16:18
kernel or driver updates will/can change the eth0/eth1 names - those names are highly unreliable.
OTOH, I've never seen the topology changed, are you sure that ever happens?

**Comment by zrm** [comment] 2016-07-13 17:00
The kernel-assigned names are non-deterministic and therefore not useful. The question isn't whether to rename them, it's how to rename them.

I linked two bugs of people complaining of PCI topology changes above. The common thread seems to be that some piece of hardware (IDE controller, GPU) has its own PCI bus and if you remove or disable it then the rest of the buses get renumbered. I have also seen old hardware with a BIOS setting to reverse the enumeration order of the PCI slots and servers that you can physically add more PCI slots to, e.g. SUN 501-4926.

**Comment by msoltyspl** [comment] 2016-07-14 19:03
Why not just use systemd.link and set the names precisely as one wants ?

**Comment by zrm** [comment] 2016-07-15 05:22
Using systemd.link is a solid suggestion, but it's kind of an indictment of predictable naming if the good solution to its problems is to turn it off. And systemd.link has its own problems here:

You're often naming an interface on a machine with no network configuration, so creating the systemd.link file can mean typing the MAC or PCI path into the console with your human fingers. Clearly not insurmountable, but a usability fail and a regression from when udev would populate it for you and all you had to change was the interface name.

Then if you match based on slot and you move the card or the PCI enumeration changes it breaks. If you match based on MAC and you replace the NIC even if it's in the same slot it breaks. Preferably it would be possible to match the MAC and if no interface has that MAC then match the slot (and then update the non-matching parameters), but so far as I'm aware that isn't yet supported.

And that behavior would also be a better default for people who haven't set interface names, except that it's inconsistent with the original name being chosen based on the topology or MAC since then you could end up with names that no longer correspond to what they were derived from.

Which is the main problem with address-derived names as the default. By the time you encounter the trouble, using systemd.link can't save you after the fact. Once you have enp2s0 in all your rules and config files, if the interface you need to use then for any reason becomes the one at enp4s0, you can in theory change its name to enp2s0 but that would sow confusion.

**Comment by arvidjaar** [comment] 2016-07-15 05:31
@zrm so you just concluded yourself that whatever scheme is selected, it will fail under some conditions. So could you please finally give concise summary of what you really suggest (not buried in thousand pages of musings).

**Comment by poettering** [comment] 2016-07-15 17:10
I mean, all possible schemes are awful in a number of cases, and a bit less awful in others. I think the currently implemented scheme is better than all other possible options however. It provides stability of interface names in most cases (yes, some BIOSes export crappy topology info that isn't as stable as it should be, but most are pretty good) and makes systems with multiple interfaces work at all (because: if you do not have this, then interface eth7 might be one hw port this boot but a completely different one on the next). It's not as nice for other cases, for example systems which only ever have a single interface, where it admittedly is handy if it would always be called eth0. But I think that such cases are not as typical as people assume that they are. Consider this:  your laptop normally has eth0 and wlan0. But now you plug your phone into your laptop in tethering mode, a pretty typical android feature. And suddenly you got two ethernet links and one wlan link, and it's not clear anymore how things are called. And what happens if your colleague also wants to charge his phone with your laptop and plugs his device in, and now gets one more ethernet link? so you have eth0 and eth1 and eth2, and you only know which one the phsyical ethernet one is because the phones weren't plugged in at boot and hence can't be eth0. But now you suspend your machine, or reboot it, leaving the phones pluged in. This causes a device reprobing and when the system is back up again there's no guarantee that it's again the builtin physical ethernet card that got eth0... Now it could be your phone that became eth0, and your physical card is eth2...

So, we live in a world where devices are hotplugged and network links come and go any time and are components of hardware you don#t even think about anymore. As such we should try our best to hand out somewhat stable names, even if we can't cover everything, and even if some very specific cases don#t need this feature. 

So, I am not sure what better proposal you could make than the current scheme. Moreover we provide very easy ways to turn off this functionality, via kernel cmdline via config file. And we suggest that people pick their own names anyway, or their own policy, and make that easy, because we know that this option is not for everyone. However, I am still very sure that it's the best we can do.

Anyway, closing this now, as I don't see anything we could improvere here. If you have a concise, explicit proposal what to improve pleas comment here and we can reopen this.

**Closed as completed by poettering** 2016-07-15 17:10 UTC
Labels: udev

**Comment by zrm** [comment] 2016-07-15 18:22
So there are two pieces:

1) Storing state when possible is useful, because it allows the system to maintain the interface name when any one property of the interface changes, regardless of which one.

2) Using topology or MAC directly as the interface name is problematic since either can change without changing the purpose of the interface.

Fix for # 1 might write files like this:

[Match prio=5]
MACAddress=00:a0:df:63:7a:e6
[Match prio=10]
Path=pci-0000:00:1a.0-*
[Link]
Name=eth2

Then at boot check all priority 1 matches before renaming any prio 2 matches etc. And (if writable) update the file's other match lines to be consistent with the matched interface by default.

New proposal for # 2. Name unmatched interfaces enhHHH where HHH is a short hash of what is currently used. Then you don't get enP2p32s15f0 or the full MAC and there is less dissonance if the system retains the name when the interface with that MAC is in a different slot or vice versa or the user pins the name to a different interface.

It also encourages things to handle possible collisions instead of not anticipating them and then someone has renamed enp4s0 to enp2s0 before another interface appears there.

**Comment by martinpitt** [comment] 2016-07-16 08:34
> 1) Storing state when possible is useful

I disagree; this was one of the biggest issues with the old 75-persistent-net generator. This breaks important use cases like building an image which then gets deployed to a lot of boards, read-only root, race conditions, you have to remember to copy it to the initrd, etc.

> because it allows the system to maintain the interface name when any one property of the interface changes, regardless of which one.

And how would you programmatically determine that? If it was a "decisive" property and it changes, then this is to be considered a new interface. And if it was an "unimportant" property then you shouldn't match on it in the first place.

This really needs taking a step back and first defining how you define the meaning of "same" for network interfaces. You will find that the main difficulties are actually on that conceptual level, and before pinning these down it makes no sense to discuss the technical implementation or how to shave off two more characters from an interface name.

There are two fundamental meanings of "same network interface":
- by identity: This means a network interfaces is the "same" as a previously seen one if a hardware-intrinsic property matches, such as MAC address or a serial number. (Note that a lot of devices don't have stable MAC addresses, but use Locally Administered Addresses; most popular example is tethering an Android phone)
- by topology: This means a network interfaces is the "same" as a previously seen one if it is connected to the same port.

The problems is that none of these is unanimously better -- Reality has proven that in the majority of use cases the topology definition is more natural, intuitive, and practical. But e. g. for connecting USB NICs on a desktop the "by identity" approach is still better.

So for any given _concrete_ use case you usually have additional information/requirements of the user/an oracle like extra bios information or cloud-init configs where you can tune the naming, and builders of images for RasPis or similar are encouraged to do so. But we still need a default naming schema which is robust, reliable, predictable, and maximizes the cases where it DTRT. The price for that is "ugly" interface names and people keep grumbling about it, but so far it's the best that we have.

**Comment by zrm** [comment] 2016-07-16 19:56
> I disagree; this was one of the biggest issues with the old 75-persistent-net generator. This breaks important use cases like building an image which then gets deployed to a lot of boards, read-only root, race conditions, you have to remember to copy it to the initrd, etc.

It's possible to use state when available and still do something reasonable when it isn't.

And the race with the kernel can be solved by using any different name prefix than the kernel does.

> And how would you programmatically determine that? If it was a "decisive" property and it changes, then this is to be considered a new interface. And if it was an "unimportant" property then you shouldn't match on it in the first place.

You've listed the main important properties. The MAC and the topology.

> The problems is that none of these is unanimously better

And if you keep state then you know both.

The problem with using only the MAC is the case where it changes, but in that case there will be no interface with that MAC. So if there _is_ an interface with that MAC, it's "that" interface regardless of port.

Then after you match every name you can on MAC, match the remaining names on port. (Though MAC-only for USB may still be right.)

Which will even DTRT when the state is "wrong" like an image deployed to a different board of the same model, because the MAC won't match but the port will.

And am I missing a specific problem with the read-only root case? If the image expects any particular interface to exist then it can be in the state file even if the file can't be modified anymore, but if it doesn't then what does it matter if hardware changes could change the interface names when nothing references them?

**Comment by poettering** [comment] 2016-07-18 10:44
> 1) Storing state when possible is useful, because it allows the system to maintain the interface name when any one property of the interface changes, regardless of which one.

Nope, this is a really broken concept. First of all, this doesn't really fix anything: you still need to identify netfis by something in order to find the name for the netifs on disks. Hence, to find the name X of an interface, you first need to generate a key Y to lookup in the persistent database on disk. But if that key Y is suitable for identifying the name on disk, then why not just use it directly as name for the netif instead of X? And that's precisely what we are doing now. Secondly: this scheme is inherently incompatible with how Linux systems work: network devices typically appear in early boot, but writable storage is only available during late boot, or might not exist at all on stateless systems. Since network interfaces may not be renamed while they are up a scheme like this can only work in some exotic cases or requires downing/upping interfaces in the middle of the boot operation... 

Saving interface names to disk is not going to come back, sorry.

(Or, to be more precise: it's not going to come back to systemd/udev. You can of course hack this up yourself and maintain it as an addon. But we are not going to support anything like this for you, because it#s just broken. Sorry)

**Comment by poettering** [comment] 2016-07-18 10:45
> Name unmatched interfaces enhHHH where HHH is a short hash of what is currently used. Then you don't get enP2p32s15f0 or the full MAC and there is less dissonance if the system retains the name when the interface with that MAC is in a different slot or vice versa or the user pins the name to a different interface.

This cannot work. If the hash is too short, collisions are too likely. If you pick a large hash then the resulting name won't be any shorter than the hw bus based names, or the MAC-based names anyway, hence why not just use those?

**Comment by zrm** [comment] 2016-07-19 16:38
The problem is clearly one of "naming things and cache invalidation", so people can argue at length, and have done before this, and people are understandably wary of reopening the can of worms. If anyone is interested in continuing to argue about it then I probably will because I am a stubborn pedant, but if there is no hope of changing it then by all means commence ignoring me.

> But if that key Y is suitable for identifying the name on disk, then why not just use it directly as name for the netif instead of X?

For the same reason we use names instead of IP addresses. Which is not just because addresses are ugly. The name gets smeared all over rules and config files. Previously when the address changed you could point the name at the new address. But if the name is the address then when the address changes you have to change everything else.

Storing both MAC and topology for the name could also allow the system to keep the name without manual intervention unless they both change at once.

> Secondly: this scheme is inherently incompatible with how Linux systems work: network devices typically appear in early boot, but writable storage is only available during late boot, or might not exist at all on stateless systems. Since network interfaces may not be renamed while they are up a scheme like this can only work in some exotic cases or requires downing/upping interfaces in the middle of the boot operation... 

So rename them early and write state later as soon as the filesystem is rw.

If new names are deterministic (even "sort by topology and name sequentially") then the problem case is the subset of stateless systems that need not only determinism but persistence against hardware changes _and_ can't be satisfied with a read-only state file.

Which isn't to say it can't happen, but why not reserve the address-names for that edge case instead of making them the default?

**Comment by zrm** [comment] 2016-07-19 16:45
> This cannot work. If the hash is too short, collisions are too likely. If you pick a large hash then the resulting name won't be any shorter than the hw bus based names, or the MAC-based names anyway, hence why not just use those?

It was admittedly a lame idea. In theory it works pretty well if you keep state (since then collisions are less problematic) but if you keep state then even simpler deterministic naming algorithms are just as good and give better names.

**Comment by poettering** [comment] 2016-07-21 11:53
> For the same reason we use names instead of IP addresses. Which is not just because addresses are ugly. The name gets smeared all over rules and config files. Previously when the address changed you could point the name at the new address. But if the name is the address then when the address changes you have to change everything else.

That all is certainly true, but our suggestion is to pick your own names if you want _friendly_ AND _stable_. And we do make this easy.

**Comment by KeithMyers** [comment] 2017-11-20 05:28
This issue is driving me crazy.  Why does the network interface name change EVERY time I update the system BIOS?  There is only one wired network interface on the motherboard.  The MAC address is the same and has never changed.  The network interface original name was enp38s0.  Then I updated the BIOS and the name then changed to enp34s0.  I update the BIOS again and now the name is enp4s0.  I DON'T have biosdevname installed.  I have to change the interface name in /etc/network/interfaces and /etc/samba/smb.conf every time I update the system BIOS.  What is the solution?

**Comment by zrm** [comment] 2017-11-20 06:52
The solution is to create a systemd.link file, typically in /etc/systemd/network/, to name the interface explicitly. For example, /etc/systemd/network/20-lan0.link:
`[Match]`
`MACAddress=00:01:02:03:04:05`
`[Link]`
`Name=lan0`

See the systemd.link man page for details.

On many distributions that use initramfs it is then necessary to update the initramfs image so that it contains the systemd.link file, e.g.:
`# update-initramfs -u`

(That last bit should probably be added to the man page.)

**Comment by KeithMyers** [comment] 2017-11-21 00:02
Thanks for the tip.  I guess I will find out the next BIOS update whether this works or not.

Can you explain now why my  "Ethernet Network" is greyed out in the taskbar applet and now replaced with ifupdown(lan0)?

**Comment by boucman** [comment] 2017-11-22 11:29
your taskbar is probably handled by NetworkManager and NetworkManager has detected that another network management-daemon has configured the interface before. It refuses to touch an interface that is already configured and greys it out

My guess is that the renaming you just did worked correctly, your interface is now correctly named lan0 and some lines in /etc/network/interfaces have started working. the inteface is configured by ifupdown, and network manager has stoped handling it.

**Comment by KeithMyers** [comment] 2017-11-22 15:50
Thanks, the problem with being greyed out was caused by having the interface named in /etc/network/interfaces.  I had to do that before because of the constant naming change.  I removed the interface name in the file and just left the original lo and the interface name in the Taskbar changed to the conventional "Wired Networking 1"  Thanks for all the help.

**Comment by chefarov** [comment] 2018-04-11 12:32
Using a systemd.link to rename a network interface isn't a solid solution inmo, because various applications (e.g gnome's network-manager) tend to change MAC addresses in various circumstances, and in order to keep a stable mac address you need to use a network interface name as an identifier. Thus we have a chicken/egg situation here.

**Comment by jccleaver** [comment] 2018-10-10 23:39
The original report is that "predictable interface naming" was flawed because it was adapted for the hard cases, not the simple cases. That remains a problem to this day.
