### ISSUE TITLE
"Bad user or group name" warning is inappropriate

### ISSUE THREAD

**Issue by yrro** [systemd/systemd#15154] opened 2020-03-18 12:41 UTC
**systemd version the issue has been seen with**
245

**Used distribution**
 Debian

**Unexpected behaviour you saw**
The following warnings are emitted whenever I run sudo:
```
Bad user or group name "user.name@domain.example", accepting for compatibility.
Bad user or group name "global.dept.allstaff@domain.example", accepting for compatibility.
Bad user or group name "global.ou.dept.db.read@domain.example", accepting for compatibility.
Bad user or group name "global.ou.dept.db.utility@domain.example", accepting for compatibility.
Bad user or group name "legacy.prior.ou.dept.wonshare.modify@domain.example", accepting for compatibility.
Bad user or group name "global.30670.severn.orgnet.allowed@domain.example", accepting for compatibility.
Bad user or group name "global.ou.dept.groupmembership.updaterequestors@domain.example", accepting for compatibility.
Bad user or group name "global.odir.saw.sw.project_siterelocationpsg@domain.example", accepting for compatibility.
Bad user or group name "global.ou.dept.windows10.authorization@domain.example", accepting for compatibility.
Bad user or group name "global.ou.dept.arbitrarysystemgroup.requestors@domain.example", accepting for compatibility.
Bad user or group name "global.vendor.software.license.somesaas.level_default@domain.example", accepting for compatibility.
Bad user or group name "global.vendor.software.license.somesaas.prodnine.level@domain.example", accepting for compatibility.
Bad user or group name "sccm.ds.prod.avendor.aproduct.0.9@domain.example", accepting for compatibility.
Bad user or group name "global.somesaas.allowsomething@domain.example", accepting for compatibility.
```

I'm in a mere 30 groups in our organization. There are other people who are in 50 or more groups. These warnings will make their systems unpleasant to use. In addition these warnings are simply not actionable. I don't choose the names of users or groups around here, my systems simply have to consume what they are given by Active Directory.

It looks like the exact warning is being emitted via `getgrgid(3)`:

```
$ python3 -c 'import grp; grp.getgrgid(556376691)'
Bad user or group name "global.vendor.software.license.somesaas.level_default@domain.example", accepting for compatibility.
```

**Steps to reproduce the problem**
1. Have a FreeIPA realm with a cross-forest trust to an Active Directory domain
1. Install freeipa-client and join the system to the FreeIPA realm
1. Upgrade to 245
1. Log in as an Active Directory user `user.name@domain.example`
1. Run `sudo -l`

**Comment by yuwata** [comment] 2020-03-18 12:43
I think this is a duplicate of #15149.

**Comment by yrro** [comment] 2020-03-18 12:51
Could be. This is more about the warning rather than not being able to log in, but the same fix may apply to both.

**Comment by yuwata** [comment] 2020-03-18 13:11
OK. Let's close this and discuss in #15149.

**Closed as completed by yuwata** 2020-03-18 13:11 UTC
Labels: bug 🐛, duplicate, userdb
