### ISSUE TITLE
Local user sessions should not wait for network.target

### ISSUE THREAD

**Issue by gloaming** [systemd/systemd#12853] opened 2019-06-20 23:55 UTC
**systemd version the issue has been seen with**
> 242

**Used distribution**
 > NixOS

**Expected behaviour you didn't see**
 > Local login should become available as soon as X11 has booted

**Unexpected behaviour you saw**
 > Login window waits for systemd-user-sessions.service, which waits for network.target

---
This behaviour was introduced in https://github.com/systemd/systemd/commit/8c856804780681e135d98ca94d08afe247557770 to fix https://github.com/systemd/systemd/issues/2390, i.e. it makes _remote_ sessions close _before_ `network.target` at shutdown. However, this introduces the undesirable behaviour of having _local_ sessions wait until _after_ `network.target` at boot!

This was actually reported before at https://github.com/systemd/systemd/issues/4010, but that issue was closed as the greater part of the problem is that `dhcpcd.service` should be ordered before `network-online.target`, not `network.target`.

However, the current behaviour still doesn't really seem correct;  It seems like it would be better, in principle at least, to decouple `systemd-user-sessions.service` from any network targets and to find a better way to ensure that SSH sessions are properly terminated, i.e. by ensuring that the scopes of SSH child sessions are set `After=network-online.target`. Is that possible?

**Comment by poettering** [comment] 2019-06-22 18:00
But why? s-u-s.s is used as a barrier here, so that we don't have to order all scopes individually.

Are you trying to fix an actual bug you ran into? Or are your concerns more out of principle?

**Comment by flokli** [comment] 2019-06-25 11:50
If I understood correctly, the observed behaviour was user sessions taking a long time to set up (sddm/gdm to start), when networking is not configured via systemd-networkd, but relying on it being setup via `dhcpcd.service` (still the default on  NixOS).

This might be the same issue as https://github.com/systemd/systemd/issues/4010#issuecomment-241256725, also see my ramblings [here](https://github.com/NixOS/nixpkgs/pull/61098#pullrequestreview-235005407)

I suggested to open an issue here mainly because of the last paragraph in https://github.com/NixOS/nixpkgs/pull/61098#issuecomment-490583917.

**Comment by gloaming** [comment] 2019-06-28 15:54
> I suggested to open an issue here mainly because of the last paragraph in [NixOS/nixpkgs#61098 (comment)](https://github.com/NixOS/nixpkgs/pull/61098#issuecomment-490583917).

Oh, yes, I got a bit enthusiastic there :)

> Are you trying to fix an actual bug you ran into?

@poettering My interest in this originally came from that same issue with `dhcpcd`, since NixOS still has the wrong configuration there, but as above, I feel it should be fixed in both places. It seems odd to think that boot could be delayed if e.g. `wpa_supplicant` crashes or something like that.

**Comment by flokli** [comment] 2019-07-10 23:43
`wpa_supplicant` on NixOS only has `Before/Wants=network.target`, and itself isn't part of `network.target`, so doesn't block `systemd-user-sessions.service`. I wonder how much actually IS part of `network.target`.

The fix for dhcpcd would be to move it from `network.target` to `network-online.target`, like suggested in https://github.com/NixOS/nixpkgs/pull/61098#issuecomment-509833282.

After that, dhcpcd shouldn't block user sessions anymore.

**Comment by gloaming** [comment] 2019-07-11 11:28
> `wpa_supplicant` on NixOS only has `Before/Wants=network.target`, and itself isn't part of `network.target`, so doesn't block `systemd-user-sessions.service`. 

?? I think you are confused. The ordering requirement is what produces the blocking. 
That `network.target` does not `Wants=` `someUnit` is irrelevant; you don't boot your system to only `network.target`.

That said, `wpa_supplicant.service` specifically has `Type=simple`, so I don't think it can block anything. So this is currently only a theoretical concern; perhaps @poettering would like to close.

> The fix for dhcpcd would be...

Yes, we already discussed that. This thread is not about `dhcpcd`.

**Comment by poettering** [comment] 2019-07-11 15:49
this is not just about ssh, it's about all kind of network stuff the user might use, i.e. home on NFS and so on. network.target really should only be used for ordering things at shutdown.

it appears to me that dhcpcd in your case is simply wrong and shouldn't delay network.target for the DHCP lease. it should delay network-online.target, but not network.target.

I think the rule of shutting down user sessions before the network goes down is a good one, and should stay, and that's what network.target is really about.

Or am I not getting what you are trying to do?

**Comment by flokli** [comment] 2019-07-17 23:50
dhcpcd was fixed in https://github.com/NixOS/nixpkgs/pull/64621 - there shouldn't be much left in `network.target` on NixOS that could cause local user session startup to be delayed.

If the intended use of `network.target` is really only about ordering on shutdown, is this really a bug? @gloaming, could you elaborate?

**Comment by poettering** [comment] 2019-07-23 08:38
Let's close this, I think this is not a bug, but documented logic: network.target is about shutting down, that's all.

**Closed as completed by poettering** 2019-07-23 08:38 UTC
Labels: login, needs-reporter-feedback ❓
