### ISSUE TITLE
document that sd_bus_track references are considered dropped if a name disappears even if it later reappears

### ISSUE THREAD

**Issue by utezduyar** [systemd/systemd#592] opened 2015-07-15 08:35 UTC
If the subscribed name disappears and appears again in between https://github.com/systemd/systemd/blob/8a2abb30b8a4ef97eb69ecdabd31da996abc3df0/src/libsystemd/sd-bus/bus-track.c#L192 and https://github.com/systemd/systemd/blob/8a2abb30b8a4ef97eb69ecdabd31da996abc3df0/src/libsystemd/sd-bus/bus-track.c#L180 sd-track considers the connection as offline but it is actually online. 

sd_bus_add_match (NAME)
... NAME disappears
... NAME appears
sd_bus_get_name_creds (NAME) -> This will tell us that NAME is on the bus but we will inform sd-track user saying NAME is offline but actually it is online.

**Comment by dvdhrm** [comment] 2015-07-15 09:40
In your case, at the time you call `sd_bus_track_add_name()`, the name is online and disappears before this call returns. Therefore, it is reasonable to tell the caller that the name disappeared, even though it re-appeared afterwards.

Furthermore, if the name re-appears before the function returns, it is also reasonable to tell the caller that the name is online. The caller has no right to assume the re-appearance happens after or before that function performs its name-tracking.

This situation is a normal 'expected' race. If you track something that changes at the time you start tracking it, you must not place any assumptions on the order in which both events happen.

**Comment by poettering** [comment] 2015-07-24 01:36
Yes, this is really intended behaviour of sd_bus_track: as soon as a name disappaered once we assume invalidation of the object. If it returns later, it doesn't matter: the reference was dropped once.

This appears like something to document, as soon as we get sd_bus_track correctly documented.

**Comment by dvdhrm** [comment] 2015-09-05 19:02
TBH, sd_bus_track should not be used for anything but unique names. And in the case of unique names, this race cannot happen. I'm closing this now, as there's another open issue for lacking documentation of sd-bus. If anyone writes up docs for sd_bus_track, it will very likely include detailed information on what it is supposed to do.

**Closed as completed by dvdhrm** 2015-09-05 19:02 UTC
Labels: documentation, sd-bus
