### ISSUE TITLE
Systemd-udevd trying to apply unsuitable .link file

### ISSUE THREAD

**Issue by aleksander** [systemd/systemd#10336] opened 2018-10-09 14:39 UTC
**systemd version the issue has been seen with**
> 239.2

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > New network interface left untouched by systemd-udevd, because no matching .link file.

**Unexpected behaviour you saw**
 > Systemd-udevd tried to rename new network interface from kernel name to one specified in unsuitable .link file.

**Steps to reproduce the problem**
Create network interface without MAC address.

**Description**
There is a driver which creates a new network interface named `test0` without MAC address (ARPHRD_NONE). When I insmod this driver interface `test0` appears:

> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
3: internet: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 94:df:80:76:86:af brd ff:ff:ff:ff:ff:ff
14: test0: <BROADCAST,MULTICAST,NOARP> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 100
    link/none 

And systemd-udevd is trying to rename `test0` to `internet`:

> systemd-udevd[26003]: Error changing net interface name 'test0' to 'internet': File exists
> systemd-udevd[26003]: could not rename interface '14' from 'test0' to 'internet': File exists

File `00-internet.link` looks like this:

> [Match]
> MACAddress=94:df:80:76:86:af
> [Link]
> Name=internet

`Match` section doesn't match to the test0 interface.
Why systemd-udevd is trying to apply this .link?

**Comment by yuwata** [comment] 2018-10-09 14:50
Duplicate of #9522 and already fixed by 25ea58d37385af27301b7ad25e985eb15f421614 (#9523).

**Closed as completed by yuwata** 2018-10-09 14:50 UTC
Labels: udev, network, duplicate
