### ISSUE TITLE
systemd v242 and later cause amdgpu firmware load failure for Radeon RX Vega M

### ISSUE THREAD

**Issue by akien-mga** [systemd/systemd#15386] opened 2020-04-09 22:20 UTC
**systemd version the issue has been seen with**
systemd v242 to v245.4.
v241 and earlier worked without issue.

**Used distribution**
Mageia Cauldron (development version for Mageia 8)

**Expected behaviour you didn't see**
When booting the system, amdgpu should load the installed firmware for my Radeon RX Vega M discrete GPU. This works fine with an initramfs that includes systemd v241 or earlier.

**Unexpected behaviour you saw**
After upgrading from Mageia 7 (systemd v241) to Mageia Cauldron (systemd v245), my Radeon RX Vega M stopped working, raising this kind of errors on boot:
```
[    2.861298] amdgpu 0000:01:00.0: Direct firmware load for
amdgpu/vegam_pfp.bin failed with error -2
[    2.861300] amdgpu 0000:01:00.0: gfx8: Failed to load firmware
"amdgpu/vegam_pfp.bin"
[    2.861466] [drm:gfx_v8_0_sw_init [amdgpu]] *ERROR* Failed to load
gfx firmware!
[    2.861648] [drm:amdgpu_device_init.cold.33 [amdgpu]] *ERROR*
sw_init of IP block <gfx_v8_0> failed -2
[    2.861696] amdgpu 0000:01:00.0: amdgpu_device_ip_init failed
[    2.861724] amdgpu 0000:01:00.0: Fatal error during GPU init
```

I didn't see the connection with systemd right away, but after spending several days debugging this issue I got the following findings:
- The boot initramfs generated on mga7 does not reproduce the bug when used on mga8 (generated by dracut), while any initramfs generated on mga8 triggers the bug (even when recreating a working mga7 initramfs on mga8).
- I downgraded all components I could find that are involved in initramfs generation. Eventually, I found that systemd is the one that causes the issue.

I rebuilt Mageia's systemd package with intermediate versions between v241 (mga7) and v245 (mga8), also with Mageia patches disabled to test vanilla systemd.

v241 works fine, v242, v243 and v245 all reproduce the issue.

**Steps to reproduce the problem**
- Install Mageia Cauldron on a system with Radeon RX Vega M (here I have a HP Spectre x360)
- Notice the errors in `dmesg` and that `DRI_PRIME=1 glxinfo` does not work (reports Intel as OpenGL vendor, so it's using the integrated Intel HD Graphics 630).
- Downgrade the systemd packages (systemd, systemd-units, lib64systemd0) to their Mageia 7 version, rebuilt the initramfs with `dracut -f` and reboot: the Vega M now works fine.

----

Downstream report:

I debugged this directly on the Mageia developers mailing list with our kernel maintainer and others:
- Thread start (continues in April): https://ml.mageia.org/l/arc/dev/2020-03/msg00233.html
- Findings about systemd causing the issue: https://ml.mageia.org/l/arc/dev/2020-04/msg00110.html

System info:
(Note that this is when using a functional initramfs built with systemd v241)

```
$ inxi -CSG
System:    Host: cauldron Kernel: 5.5.15-desktop-3.mga8 x86_64 bits: 64 Desktop: KDE Plasma 5.18.3 Distro: Mageia 8 mga8 
CPU:       Topology: Quad Core model: Intel Core i7-8705G bits: 64 type: MT MCP L2 cache: 8192 KiB 
           Speed: 2923 MHz min/max: 800/4100 MHz Core speeds (MHz): 1: 2923 2: 2247 3: 1330 4: 1700 5: 1334 6: 1360 7: 2774 
           8: 2725 
Graphics:  Device-1: Intel HD Graphics 630 driver: i915 v: kernel 
           Device-2: Advanced Micro Devices [AMD/ATI] Polaris 22 XL [Radeon RX Vega M GL] driver: amdgpu v: kernel 
           Display: x11 server: Mageia X.org 1.20.8 driver: intel,v4l resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa Intel HD Graphics 630 (KBL GT2) v: 4.6 Mesa 20.0.4
```

**Comment by poettering** [comment] 2020-04-10 12:15
the kernel loads firmware on its own these days, udev/systemd is no longer involved. Maybe when you rebuilt your initrd for the newer systemd the generator forgot to include the firmware file?

**Comment by poettering** [comment] 2020-04-10 12:16
> [    2.861298] amdgpu 0000:01:00.0: Direct firmware load for
amdgpu/vegam_pfp.bin failed with error -2

error 2 is ENOENT btw. This smells a lot like the firmware file is simply missing in your initrd.

**Comment by akien-mga** [comment] 2020-04-10 12:30
> error 2 is ENOENT btw. This smells a lot like the firmware file is simply missing in your initrd.

That's also what I investigated first, and I did find some fishy output in `lsinitrd` initially: https://ml.mageia.org/l/arc/dev/2020-04/msg00081.html

The `vegam` files *are* present, but some seem to have 4 or 5 hardlinks. I'm not very knowledgeable about what hardlinks represent but my understanding was that it would be directories that would contain 3 or more hardlinks. The same files on the installed filesystem have 1 hardlink.

> the kernel loads firmware on its own these days, udev/systemd is no longer involved. Maybe when you rebuilt your initrd for the newer systemd the generator forgot to include the firmware file?

I've been rebuilding the initrd several times with the systemd version as the only difference on the filesystem, and lsinitrd output doesn't change significantly apart from the systemd version.

Here's the output from `lsinitrd` from kernel 5.5.15-desktop-3.mga8 with dracut 050, before and after upgrading systemd:
```
sudo lsinitrd > lsinitrd-$(uname -r)-systemd-v241.log
sudo urpmi {systemd,systemd-devel,lib64systemd0,systemd-units}
sudo dracut -f
sudo lsinitrd > lsinitrd-$(uname -r)-systemd-v245.log
```

[lsinitrd-5.5.15-desktop-3.mga8-systemd-v241.log](https://github.com/systemd/systemd/files/4461497/lsinitrd-5.5.15-desktop-3.mga8-systemd-v241.log)
[lsinitrd-5.5.15-desktop-3.mga8-systemd-v245.log](https://github.com/systemd/systemd/files/4461498/lsinitrd-5.5.15-desktop-3.mga8-systemd-v245.log)

And here's the diff between the two files (after removing the timestamps to be able to compare line by line):
```diff
--- systemd-v241_awk.log        2020-04-10 14:27:05.576506852 +0200
+++ systemd-v245_awk.log        2020-04-10 14:27:11.065513888 +0200
@@ -1,4 +1,4 @@
-initrd in UEFI: : 25M           
+initrd in UEFI: : 26M           
 ========================================================================                
 Early CPIO image                
 ========================================================================                
@@ -31,11 +31,11 @@
 shutdown                
 ========================================================================                
 drwxr-xr-x 12 root root 0                       .
-crw-r--r-- 1 root root 5,                       23:57 dev/console
-crw-r--r-- 1 root root 1,                       23:57 dev/kmsg
-crw-r--r-- 1 root root 1,                       23:57 dev/null
-crw-r--r-- 1 root root 1,                       23:57 dev/random
-crw-r--r-- 1 root root 1,                       23:57 dev/urandom
+crw-r--r-- 1 root root 5,                       14:26 dev/console
+crw-r--r-- 1 root root 1,                       14:26 dev/kmsg
+crw-r--r-- 1 root root 1,                       14:26 dev/null
+crw-r--r-- 1 root root 1,                       14:26 dev/random
+crw-r--r-- 1 root root 1,                       14:26 dev/urandom
 lrwxrwxrwx 1 root root 7                        bin -> usr/bin
 drwxr-xr-x 2 root root 0                        dev
 drwxr-xr-x 11 root root 0                       etc
@@ -51,7 +51,7 @@
 -rw-r--r-- 1 root root 0                        etc/fstab.empty
 -rw-r--r-- 1 root root 153                      etc/group
 lrwxrwxrwx 1 root root 25                       etc/initrd-release -> ../usr/lib/initrd-release
--rw-r--r-- 1 root root 5002                     etc/ld.so.cache
+-rw-r--r-- 1 root root 5960                     etc/ld.so.cache
 -rw-r--r-- 1 root root 33                       etc/ld.so.conf
 drwxr-xr-x 3 root root 0                        etc/ld.so.conf.d
 -rw-r--r-- 1 root root 21                       etc/ld.so.conf.d/darktable-x86_64.conf
@@ -112,6 +112,7 @@
 -rwxr-xr-x 1 root root 75056                    usr/bin/dmesg
 -rwxr-xr-x 1 root root 63776                    usr/bin/findmnt
 -rwxr-xr-x 1 root root 32872                    usr/bin/flock
+-rwxr-xr-x 1 root root 159152                   usr/bin/grep
 lrwxrwxrwx 1 root root 16                       usr/bin/halt -> ../bin/systemctl
 -rwxr-xr-x 1 root root 15584                    usr/bin/kbd_mode
 -rwxr-xr-x 1 root root 159080                   usr/bin/kmod
@@ -137,9 +138,9 @@
 -rwxr-xr-x 1 root root 41312                    usr/bin/sleep
 -rwxr-xr-x 1 root root 87384                    usr/bin/stat
 -rwxr-xr-x 1 root root 78512                    usr/bin/stty
--rwxr-xr-x 1 root root 184520                   usr/bin/systemctl
+-rwxr-xr-x 1 root root 209400                   usr/bin/systemctl
 -rwxr-xr-x 1 root root 53832                    usr/bin/tr
--rwxr-xr-x 1 root root 357288                   usr/bin/udevadm
+-rwxr-xr-x 1 root root 381880                   usr/bin/udevadm
 -rwsr-xr-x 1 root root 37056                    usr/bin/umount
 -rwxr-xr-x 1 root root 37176                    usr/bin/uname
 drwxr-xr-x 9 root root 0                        usr/lib
@@ -151,10 +152,16 @@
 lrwxrwxrwx 1 root root 30                       usr/lib64/libacl.so -> ../../lib64/libacl.so.1.1.2253
 -rwxr-xr-x 1 root root 28168                    usr/lib64/libattr.so.1.1.2448
 lrwxrwxrwx 1 root root 31                       usr/lib64/libattr.so.1 -> ../../lib64/libattr.so.1.1.2448
+-rwxr-xr-x 1 root root 118944                   usr/lib64/libaudit.so.1.0.0
+lrwxrwxrwx 1 root root 29                       usr/lib64/libaudit.so.1 -> ../../lib64/libaudit.so.1.0.0
+lrwxrwxrwx 1 root root 29                       usr/lib64/libaudit.so -> ../../lib64/libaudit.so.1.0.0
 -rwxr-xr-x 1 root root 320528                   usr/lib64/libblkid.so.1.1.0
 lrwxrwxrwx 1 root root 29                       usr/lib64/libblkid.so.1 -> ../../lib64/libblkid.so.1.1.0
 lrwxrwxrwx 1 root root 29                       usr/lib64/libblkid.so -> ../../lib64/libblkid.so.1.1.0
 -rwxr-xr-x 1 root root 2161064                          usr/lib64/libc-2.31.so
+-rwxr-xr-x 1 root root 28080                    usr/lib64/libcap-ng.so.0.0.0
+lrwxrwxrwx 1 root root 30                       usr/lib64/libcap-ng.so.0 -> ../../lib64/libcap-ng.so.0.0.0
+lrwxrwxrwx 1 root root 42                       usr/lib64/libcap-ng.so -> ../../lib64/../../lib64/libcap-ng.so.0.0.0
 -rw-r--r-- 1 root root 85312                    usr/lib64/libcap.so.2.27
 lrwxrwxrwx 1 root root 26                       usr/lib64/libcap.so.2 -> ../../lib64/libcap.so.2.27
 lrwxrwxrwx 1 root root 23                       usr/lib64/libcap.so -> ../../lib64/libcap.so.2
@@ -166,6 +173,9 @@
 -rwxr-xr-x 1 root root 498368                   usr/lib64/libcryptsetup.so.12.6.0
 lrwxrwxrwx 1 root root 35                       usr/lib64/libcryptsetup.so.12 -> ../../lib64/libcryptsetup.so.12.6.0
 lrwxrwxrwx 1 root root 35                       usr/lib64/libcryptsetup.so -> ../../lib64/libcryptsetup.so.12.6.0
+-rwxr-xr-x 1 root root 205416                   usr/lib64/libcrypt.so.1.1.0
+lrwxrwxrwx 1 root root 29                       usr/lib64/libcrypt.so.1 -> ../../lib64/libcrypt.so.1.1.0
+lrwxrwxrwx 1 root root 29                       usr/lib64/libcrypt.so -> ../../lib64/libcrypt.so.1.1.0
 -rw-r--r-- 1 root root 253                      usr/lib64/libc.so
 lrwxrwxrwx 1 root root 12                       usr/lib64/libc.so.6 -> libc-2.31.so
 -rwxr-xr-x 1 root root 363776                   usr/lib64/libdevmapper.so.1.02
@@ -182,6 +192,9 @@
 -rwxr-xr-x 1 root root 423048                   usr/lib64/libext2fs.so.2.4
 lrwxrwxrwx 1 root root 28                       usr/lib64/libext2fs.so.2 -> ../../lib64/libext2fs.so.2.4
 lrwxrwxrwx 1 root root 38                       usr/lib64/libext2fs.so -> ../../lib64/../../lib64/libext2fs.so.2
+-rwxr-xr-x 1 root root 36568                    usr/lib64/libffi.so.6.0.4
+lrwxrwxrwx 1 root root 27                       usr/lib64/libffi.so.6 -> ../../lib64/libffi.so.6.0.4
+lrwxrwxrwx 1 root root 27                       usr/lib64/libffi.so -> ../../lib64/libffi.so.6.0.4
 -rwxr-xr-x 1 root root 103656                   usr/lib64/libgcc_s-9.so.1
 lrwxrwxrwx 1 root root 27                       usr/lib64/libgcc_s.so.1 -> ../../lib64/libgcc_s-9.so.1
 -rwxr-xr-x 1 root root 1186064                          usr/lib64/libgcrypt.so.20.2.5
@@ -217,6 +230,15 @@
 -rwxr-xr-x 1 root root 52928                    usr/lib64/libnss_files-2.31.so
 lrwxrwxrwx 1 root root 44                       usr/lib64/libnss_files.so.2 -> ../../lib64/../../lib64/libnss_files-2.31.so
 lrwxrwxrwx 1 root root 41                       usr/lib64/libnss_files.so -> ../../lib64/../../lib64/libnss_files.so.2
+-rwxr-xr-x 1 root root 1220392                          usr/lib64/libp11-kit.so.0.3.0
+lrwxrwxrwx 1 root root 31                       usr/lib64/libp11-kit.so.0 -> ../../lib64/libp11-kit.so.0.3.0
+lrwxrwxrwx 1 root root 27                       usr/lib64/libp11-kit.so -> ../../lib64/libp11-kit.so.0
+-rwxr-xr-x 1 root root 65872                    usr/lib64/libpam.so.0.84.2
+lrwxrwxrwx 1 root root 28                       usr/lib64/libpam.so.0 -> ../../lib64/libpam.so.0.84.2
+lrwxrwxrwx 1 root root 28                       usr/lib64/libpam.so -> ../../lib64/libpam.so.0.84.2
+-rwxr-xr-x 1 root root 463904                   usr/lib64/libpcre.so.1.2.12
+lrwxrwxrwx 1 root root 29                       usr/lib64/libpcre.so.1 -> ../../lib64/libpcre.so.1.2.12
+lrwxrwxrwx 1 root root 29                       usr/lib64/libpcre.so -> ../../lib64/libpcre.so.1.2.12
 -rwxr-xr-x 1 root root 103624                   usr/lib64/libply.so.4.0.0
 lrwxrwxrwx 1 root root 15                       usr/lib64/libply.so.4 -> libply.so.4.0.0
 -rwxr-xr-x 1 root root 107456                   usr/lib64/libply-splash-core.so.4.0.0
@@ -1035,9 +1057,9 @@
 -rw-r--r-- 1 root root 111481                   usr/lib/modules/5.5.15-desktop-3.mga8/modules.symbols.bin
 lrwxrwxrwx 1 root root 14                       usr/lib/os-release -> initrd-release
 drwxr-xr-x 3 root root 0                        usr/lib/systemd
--rwxr-xr-x 1 root root 2609776                          usr/lib/systemd/libsystemd-shared-241.so
+-rwxr-xr-x 1 root root 2494248                          usr/lib/systemd/libsystemd-shared-245.so
 drwxr-xr-x 9 root root 0                        usr/lib/systemd/system
--rwxr-xr-x 1 root root 361432                   usr/lib/systemd/systemd-udevd
+-rwxr-xr-x 1 root root 377856                   usr/lib/systemd/systemd-udevd
 drwxr-xr-x 2 root root 0                        usr/lib/systemd/system/halt.target.wants
 lrwxrwxrwx 1 root root 24                       usr/lib/systemd/system/halt.target.wants/plymouth-halt.service -> ../plymouth-halt.service
 drwxr-xr-x 2 root root 0                        usr/lib/systemd/system/initrd-switch-root.target.wants
@@ -1065,26 +1087,27 @@
 -rw-r--r-- 1 root root 419                      usr/lib/systemd/system/systemd-ask-password-plymouth.path
 -rw-r--r-- 1 root root 435                      usr/lib/systemd/system/systemd-ask-password-plymouth.service
 drwxr-xr-x 3 root root 0                        usr/lib/udev
--rwxr-xr-x 1 root root 19248                    usr/lib/udev/ata_id
--rwxr-xr-x 1 root root 35696                    usr/lib/udev/cdrom_id
+-rwxr-xr-x 1 root root 19256                    usr/lib/udev/ata_id
+-rwxr-xr-x 1 root root 31608                    usr/lib/udev/cdrom_id
 -rwxr-xr-x 1 root root 1610                     usr/lib/udev/console_init
 -rwxr-xr-x 1 root root 15736                    usr/lib/udev/pcmcia-check-broken-cis
 -rwxr-xr-x 1 root root 28320                    usr/lib/udev/pcmcia-socket-startup
 drwxr-xr-x 2 root root 0                        usr/lib/udev/rules.d
--rw-r--r-- 1 root root 3679                     usr/lib/udev/rules.d/50-udev-default.rules
--rw-r--r-- 1 root root 626                      usr/lib/udev/rules.d/60-block.rules
+-rw-r--r-- 1 root root 3860                     usr/lib/udev/rules.d/50-udev-default.rules
+-rw-r--r-- 1 root root 703                      usr/lib/udev/rules.d/60-block.rules
 -rw-r--r-- 1 root root 1060                     usr/lib/udev/rules.d/60-pcmcia.rules
--rw-r--r-- 1 root root 6891                     usr/lib/udev/rules.d/60-persistent-storage.rules
+-rw-r--r-- 1 root root 7642                     usr/lib/udev/rules.d/60-persistent-storage.rules
 -rw-r--r-- 1 root root 2671                     usr/lib/udev/rules.d/70-uaccess.rules
--rw-r--r-- 1 root root 2735                     usr/lib/udev/rules.d/71-seat.rules
+-rw-r--r-- 1 root root 3901                     usr/lib/udev/rules.d/71-seat.rules
 -rw-r--r-- 1 root root 636                      usr/lib/udev/rules.d/73-seat-late.rules
 -rw-r--r-- 1 root root 452                      usr/lib/udev/rules.d/75-net-description.rules
--rw-r--r-- 1 root root 615                      usr/lib/udev/rules.d/80-drivers.rules
+-rw-r--r-- 1 root root 1248                     usr/lib/udev/rules.d/80-drivers.rules
 -rw-r--r-- 1 root root 292                      usr/lib/udev/rules.d/80-net-setup-link.rules
--rwxr-xr-x 1 root root 32304                    usr/lib/udev/scsi_id
+-rwxr-xr-x 1 root root 36400                    usr/lib/udev/scsi_id
 drwxr-xr-x 2 root root 0                        usr/sbin
 -rwxr-xr-x 1 root root 109848                   usr/sbin/blkid
 -rwxr-xr-x 1 root root 45584                    usr/sbin/chroot
+-rwxr-xr-x 1 root root 13656                    usr/sbin/display_driver_helper
 -rwxr-xr-x 1 root root 313144                   usr/sbin/e2fsck
 -rwxr-xr-x 1 root root 54192                    usr/sbin/fsck
 lrwxrwxrwx 1 root root 6                        usr/sbin/fsck.ext4 -> e2fsck
```

**Comment by poettering** [comment] 2020-04-10 12:41
this really looks like an initrd/distro issue, we cannot really help you on this, please contact your distro/initrd maintainers, maybe they can help you

**Comment by akien-mga** [comment] 2020-04-10 13:16
Well I did contact my distro maintainers first, and with their help narrowed down the issue to a regression that happens when going from systemd v241 (works) to v242 or later.

Is there any change in v242 that could relate to this? I'm happy to debug this further at the distro level but we need insights into why a systemd upgrade would trigger this issue.

As a reminder, I did build both v241 and v242 without any downstream patches to make sure that it's not due to the distro packaging.

**Comment by poettering** [comment] 2020-04-10 13:19
again, we are not involved in firmware loading anymore, systemd doesn't do anything in the area of firmware loading at all anymore

**Comment by akien-mga** [comment] 2020-04-10 13:21
I trust you, but the systemd version (and the effect of its udev rules) is the only difference between my working and broken initrds generated on the exact same system.

But I'll keep poking at it and see if I figure it out. Maybe bisecting between `v241` and `v242`.

**Comment by mbiebl** [comment] 2020-04-10 13:31
@akien-mga if you can reliably trigger the issue, running `git bisect` might indeed be very helpful.

**Comment by akien-mga** [comment] 2020-04-10 17:20
I ran a bisect between `v241` and `v242`, here's the result:
```
204e9c3e29c08386f8dfd58c0133e3cc73774365 is the first bad commit
commit 204e9c3e29c08386f8dfd58c0133e3cc73774365
Author: Yu Watanabe <watanabe.yu+github@gmail.com>
Date:   Sat Jan 26 00:13:16 2019 +0900

    udev: drop unused Manager::uevent_event

 src/udev/udevd.c | 3 ---
 1 file changed, 3 deletions(-)
```

So 204e9c3e29c08386f8dfd58c0133e3cc73774365 causes the bug I'm experiencing.

```
git bisect start
# good: [e62a7fea757f259eb330da5b6d3ab4ede46400a2] Merge pull request #11714 from poettering/final-news-241
git bisect good e62a7fea757f259eb330da5b6d3ab4ede46400a2
# bad: [1e5d2d656420d0e755dbcf72aeba3c3aba54e956] NEWS: update contributors and date
git bisect bad 1e5d2d656420d0e755dbcf72aeba3c3aba54e956
# bad: [7bbead1d0b8339d9878f8c9debf4d0966f442b9e] execute: simplify paths we set as HOME/SHELL for invoked programs
git bisect bad 7bbead1d0b8339d9878f8c9debf4d0966f442b9e
# bad: [6227fc14c48c4c17daed4b91f61cdd4aa375790a] selinux: don't log SELINUX_INFO and SELINUX_WARNING messages to audit
git bisect bad 6227fc14c48c4c17daed4b91f61cdd4aa375790a
# good: [149b0ab25d60fff638c1f7bc35898b9ae10a9451] Merge pull request #11763 from yuwata/disable-test-dropin-driver
git bisect good 149b0ab25d60fff638c1f7bc35898b9ae10a9451
# bad: [9fa326b18aef0c1e5c80e23a5b41de02155e6f7e] Merge pull request #11608 from taro-yamada/add_persistent_randmized_delay
git bisect bad 9fa326b18aef0c1e5c80e23a5b41de02155e6f7e
# bad: [41d3c9c2e9a0f7c5dca741cab3723571a2372197] Merge pull request #11725 from poettering/temp-dir
git bisect bad 41d3c9c2e9a0f7c5dca741cab3723571a2372197
# bad: [204e9c3e29c08386f8dfd58c0133e3cc73774365] udev: drop unused Manager::uevent_event
git bisect bad 204e9c3e29c08386f8dfd58c0133e3cc73774365
# good: [0cc972aac365df084b5c306f32936b0e4a6031e9] test-network: add tests for meaningless settings which should be ignored by networkd
git bisect good 0cc972aac365df084b5c306f32936b0e4a6031e9
# good: [71064bd5ac393a6e7725cb58d6c07bb1f22c2735] Merge pull request #11759 from yuwata/fix-test-dropin
git bisect good 71064bd5ac393a6e7725cb58d6c07bb1f22c2735
# good: [ebf963c551e1077abaa5e0fa0f330e6d1c23565e] util: make base64_append() add a whitespace before appending data
git bisect good ebf963c551e1077abaa5e0fa0f330e6d1c23565e
# good: [53bba2fb1da3ca26b1cf96c461598d53df2040cc] udev-ctrl: refactor udev_ctrl_enable_receiving()
git bisect good 53bba2fb1da3ca26b1cf96c461598d53df2040cc
# first bad commit: [204e9c3e29c08386f8dfd58c0133e3cc73774365] udev: drop unused Manager::uevent_event
```

**Comment by akien-mga** [comment] 2020-04-10 21:44
> _Edit 2:_ Confirmed, I re-ran a test with a build from [204e9c3](https://github.com/systemd/systemd/commit/204e9c3e29c08386f8dfd58c0133e3cc73774365) and this time it's a `good` result, so I must have missed a step earlier. I'll re-bisect between [41d3c9c](https://github.com/systemd/systemd/commit/41d3c9c2e9a0f7c5dca741cab3723571a2372197) (`bad`) and [204e9c3](https://github.com/systemd/systemd/commit/204e9c3e29c08386f8dfd58c0133e3cc73774365) (apparently `good`) tomorrow.

So I re-ran a bisect with extra care to each step, between the two commits mentioned (after checking that they are indeed respectively `bad` and `good`).

I did have an off-by-one error, the new results are that the first bad commit would be:
d02c6f546167d5f076a8940470db3a75ff12e814

```
d02c6f546167d5f076a8940470db3a75ff12e814 is the first bad commit
commit d02c6f546167d5f076a8940470db3a75ff12e814
Author: Yu Watanabe <watanabe.yu+github@gmail.com>
Date:   Sat Jan 26 00:27:26 2019 +0900

    udev-ctrl: use sd_event and introduce udev_ctrl_start()
    
    Now the new callback function get enum udev_ctrl_msg_type.
    So, this commit also drops udev_ctrl_connection and udev_ctrl_msg.

 src/udev/udev-ctrl.c | 380 +++++++++++++++++++++++----------------------------
 src/udev/udev-ctrl.h |  47 ++++---
 src/udev/udevd.c     | 101 ++++++--------
 3 files changed, 241 insertions(+), 287 deletions(-)
```

```
git bisect start
# good: [204e9c3e29c08386f8dfd58c0133e3cc73774365] udev: drop unused Manager::uevent_event
git bisect good 204e9c3e29c08386f8dfd58c0133e3cc73774365
# bad: [41d3c9c2e9a0f7c5dca741cab3723571a2372197] Merge pull request #11725 from poettering/temp-dir
git bisect bad 41d3c9c2e9a0f7c5dca741cab3723571a2372197
# bad: [7ca69792e57f09cafa77aec1312f356382715c8c] core: add ':' prefix to ExecXYZ= skip env var substitution
git bisect bad 7ca69792e57f09cafa77aec1312f356382715c8c
# bad: [6371db935851cde55a21ddcfb47c48de261d008d] man: udevadm: mention that no control command can be specified after --exit
git bisect bad 6371db935851cde55a21ddcfb47c48de261d008d
# bad: [a0b60b8a1b16217d9167d03c1c0ee7e4a362514f] udevadm: print error if the commands fail
git bisect bad a0b60b8a1b16217d9167d03c1c0ee7e4a362514f
# bad: [d02c6f546167d5f076a8940470db3a75ff12e814] udev-ctrl: use sd_event and introduce udev_ctrl_start()
git bisect bad d02c6f546167d5f076a8940470db3a75ff12e814
# first bad commit: [d02c6f546167d5f076a8940470db3a75ff12e814] udev-ctrl: use sd_event and introduce udev_ctrl_start()
```

**Comment by vcaputo** [comment] 2020-04-10 23:11
I doubt this is the cause of this specific issue, but just looking at the bisected commit I noticed a functional difference that may have been unintended:
```
+        case UDEV_CTRL_SET_CHILDREN_MAX:
+                if (value->intval <= 0) {
+                        log_debug("Received invalid udev control message (SET_MAX_CHILDREN, %i), ignoring.", value->intval);
+                        return 0;
+                }
 
-        i = udev_ctrl_get_set_children_max(ctrl_msg);
-        if (i >= 0) {
-                log_debug("Receivd udev control message (SET_MAX_CHILDREN), setting children_max=%i", i);
-                arg_children_max = i;
+                log_debug("Received udev control message (SET_MAX_CHILDREN), setting children_max=%i", value->intval);
+                arg_children_max = value->intval;
 
                 (void) sd_notifyf(false,
                                   "READY=1\n"
                                   "STATUS=Processing with %u children at max", arg_children_max);
-        }
-
-        if (udev_ctrl_get_ping(ctrl_msg) > 0)
+                break;
```

What used to be 'i >= 0' -> valid became 'value->intval <= 0' invalid, admittedly without spending enough time tofully grok this code, that seems mistaken as the inversion of >= 0 would be < 0.  As-written the 0 value went from valid to invalid.

Hence I suspect https://github.com/systemd/systemd/blob/v245/src/udev/udevd.c#L1060 should be changed to `value->intval < 0` if the previous code was correct.

But I didn't see anything else that stood out from skimming the commit.

/cc @yuwata

**Comment by poettering** [comment] 2020-04-23 12:05
still curious, does your kernel have userspace firmware loading still enabled? i.e. CONFIG_FW_LOADER_USER_HELPER still on?

**Comment by akien-mga** [comment] 2020-04-24 20:02
> still curious, does your kernel have userspace firmware loading still enabled? i.e. CONFIG_FW_LOADER_USER_HELPER still on?

It did, but our kernel maintainer just pushed a build disabling it but that doesn't seem to make a difference for this bug (installed the new kernel, systemd 245.5 and rebuilt the initramfs).
http://svnweb.mageia.org/packages/cauldron/kernel/current/SOURCES/defconfig-x86_64-desktop?r1=1571612&r2=1571611&pathrev=1571612

I attempted a local revert of d02c6f546167d5f076a8940470db3a75ff12e814 on the current master branch but that's not trivial, and I'm not familiar enough with the codebase not to mess things up resolving the merge conflicts.

**Comment by poettering** [comment] 2020-08-31 20:51
Is this still relevant?

/cc @yuwata

**Comment by yuwata** [comment] 2020-09-01 07:22
@vcaputo Setting 0 for `UDEV_CTRL_SET_CHILDREN_MAX` should be invalid. If it is accepted, then udevd cannot spawn any workers.

If I remember correctly, since 78467aeb9578bee56211a64190b3293616647aee, combining udevd earlier than v242 and udevadm order than v242 (or it might be inverted, I cannot remember) causes an issue that `udevadm control` will be stuck. @akien-mga Are the version of udevd and udevadm equivalent? (Though, I think the issue does not relevant to this firmware loading issue...)

**Comment by yuwata** [comment] 2020-09-01 07:56
> I notice the change in usr/lib/udev/rules.d/80-drivers.rules and the addition of usr/sbin/display_driver_helper which is used by the former, this might be involved?

We have not touch 80-drivers.rules for a while. Maybe, mageia modifies the rule?

**Comment by akien-mga** [comment] 2020-09-01 07:58
> Is this still relevant?

Since my last comment, we found a workaround for this issue with Mageia's kernel maintainer:

> On Sun, 26 Apr 2020 at 21:09, Thomas Backlund <tmb@mageia.org> wrote:
>>
>> Den 26-04-2020 kl. 21:25, skrev Rémi Verschelde:
>>> On Sun, 26 Apr 2020 at 17:22, Thomas Backlund <tmb@mageia.org> wrote:
>>>>
>>>> also if you reboot to runlevel 3, unload the amdgpu module and reload
>>>> it, does it then get the init / firmware loading done properly ?
>>>
>>> I tried that, and that does fix loading the firmware, the Vega M then
>>> works fine.
>>>
>>
>> Oh...
>>
>> Then maybe this can work as a hack for now:
>>
>> echo 'omit_drivers+=" amdgpu "' >/etc/dracut.conf.d/amdgpu-hack.conf
>> dracut -f
>> reboot
> 
> That works!

So I've been using this workaround since then with no problem.

On your prompt today I tried removing the hack, and after a `dracut -f` and reboot it seems that the bug is no longer reproducible with systemd-246.2-1.mga8.

So... this became a WORKSFORME I guess? I'll defer the decision of closing it or not to you, and I'll report back after some days of usage without the hack and after maybe a kernel or systemd update to confirm that everything works fine.

>  @akien-mga Are the version of udevd and udevadm equivalent?

Yes, both are provided by systemd-246.2-1.mga8.

**Comment by yuwata** [comment] 2020-09-01 08:08
OK. Let's close this then.

**Closed as completed by yuwata** 2020-09-01 08:08 UTC
Labels: needs-reporter-feedback ❓
