### ISSUE TITLE
systemd-resolved: allow marking a DNS server as "always-up"

### ISSUE THREAD

**Issue by alkisg** [systemd/systemd#31217] opened 2024-02-06 09:15 UTC
### Component

systemd-resolved

### Is your feature request related to a problem? Please describe

My netbooted workstations, running systemd-resolved 249.11-0ubuntu3.11, use only the boot server as DNS.
When temporary network issues occur (packet loss, corrupted packets etc), systemd-resolved marks that DNS server as failed.
This means that all further DNS requests will fail, even though the temporary network issue only lasted e.g. for a second.

### Describe the solution you'd like

Please provide:

1) A method to check if systemd-resolved has marked a certain server as failed.
2) An option to force a certain server to always be considered as working, e.g. in the case it's the only DNS server

### Describe alternatives you've considered

For (1), I tried to enable debug output but I couldn't pinpoint when systemd-resolved marks a server as failed.
For (2) I found no workaround, other than not using systemd-resolved.

### The systemd version you checked that didn't have the feature you are asking for

249.11-0ubuntu3.11

**Comment by poettering** [comment] 2024-02-06 10:12
We don't even have a concept of a "failed" DNS server. All we do if we encounter issues with a DNS server is lower the protocol level and eventually switch to a different DNS server that you configured. But that's round robin, so we'll eventually come back to the original one.

Hence, if DNS completely fails after this, it suggests you might have secondary DNS servers cnfigured that don#t work at all?

**Comment by alkisg** [comment] 2024-02-06 10:25
Thank you for your feedback and sorry for my misunderstanding.
Here are the facts:

1) There's only one DNS server (specifically it's dnsmasq):
```
root@g00pc02:~# grep DNS /etc/systemd/resolved.conf.d/ltsp.conf
DNS=10.16.3.10

root@g00pc02:~# resolvectl status
Global
         Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
  resolv.conf mode: stub
Current DNS Server: 10.16.3.10
       DNS Servers: 10.16.3.10
        DNS Domain: example.com

Link 2 (ens18)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```
2) When the issue happens, running `host somedomain` hangs for several seconds
3) But at the same time `host somedomain 10.16.3.10` works immediately
4) Running `systemctl restart systemd-networkd` restores DNS, e.g. `host somedomain` then also works immediately

A question, what happens if e.g. networking fails for 2 seconds (e.g. spanning tree delays), and some DNS requests pile up?
Does systemd-resolved block when e.g. 4 DNS requests are pending?
Maybe knowning the related timeouts will allow me to pinpoint if systemd is waiting for something. Unfortunately the issue happens e.g. every half an hour so troubleshooting it is hard...

Also, if systemd thinks that UDP has failed, and switches to TCP of the same DNS server, and TCP also fails, will it then switch back to UDP immediately, or will it have some delay before retrying?

**Comment by poettering** [comment] 2024-02-06 12:22
issue "systemctl service-log-level systemd-resolved debug". That will turn on debug logging in resolved.

Then reproduce the issue. This should reveal a lot of debug info on what precisely systemd is doing, and why it might time-out. Once you hit this, please paste the debug log of systemd-resolved somewhere (only the logs around the issue)

**Comment by poettering** [comment] 2024-02-06 12:25
> 5\. 
> 
> 
> A question, what happens if e.g. networking fails for 2 seconds (e.g. spanning tree delays), and some DNS requests pile up? Does systemd-resolved block when e.g. 4 DNS requests are pending? Maybe knowning the related timeouts will allow me to pinpoint if systemd is waiting for something. Unfortunately the issue happens e.g. every half an hour so troubleshooting it is hard...

All transactions are dispatched in parallel, they do not "pile up".

> Also, if systemd thinks that UDP has failed, and switches to TCP of the same DNS server, and TCP also fails, will it then switch back to UDP immediately, or will it have some delay before retrying?

In most cases UDP failures are detected as timeouts only, there's no ICMP error message seen, hence we typically have to wait for the time-out to reach before we take another action. Generally the logic in resolved is to start communication at the highest feature level. We then downgrade bit by bit. Once we hit simple 1980s UDP DNS, and that fails too, we'll switch to TCP, and if that fails we switch back to UDP DNS, and so on, until an overall timeout is reached.

**Comment by poettering** [comment] 2024-09-03 09:33
Let's close this, since the request doesn't really match resolved's logic, and this is probably just a downgrading issue.

**Closed as completed by poettering** 2024-09-03 09:33 UTC
Labels: RFE 🎁, resolve, needs-reporter-feedback ❓
