### ISSUE TITLE
Waking up from Suspend/sleep fails to configure eth link

### ISSUE THREAD

**Issue by nolange** [systemd/systemd#16902] opened 2020-08-29 15:52 UTC
**systemd version the issue has been seen with**
> systemd 246 (246.2-1)
   +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS 
   +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Debian Bullseye

**Expected behaviour you didn't see**
 > Network working after leaving sleep

**Unexpected behaviour you saw**

What happens is that my main eth link is not configured again,
instead a failure "No static address is stored." is logged.
Seems to be a regression in 246, did not have the issue before.

(restarting systemd-networkd fixes everything)

Configuration is:

```ini
[Match]
Name=eno1

[Network]
Address=192.168.0.11/24
Gateway=192.168.0.1
LinkLocalAddressing=no
IPv6AcceptRA=no

DNS=8.8.8.8
DNS=8.8.4.4
```

Log is:

```
Aug 29 17:38:23 debian-noppl systemd[1]: Finished Suspend.
Aug 29 17:38:23 debian-noppl systemd[1]: Stopped target Sleep.
Aug 29 17:38:23 debian-noppl systemd[1]: Reached target Suspend.
Aug 29 17:38:23 debian-noppl systemd[1]: Stopped target Suspend.
Aug 29 17:38:23 debian-noppl systemd-logind[712]: Operation 'sleep' finished.
Aug 29 17:38:23 debian-noppl systemd-networkd[330]: lo: Reset carrier
Aug 29 17:38:23 debian-noppl systemd-networkd[330]: eno1: Reset carrier
Aug 29 17:38:23 debian-noppl systemd-timesyncd[692]: No network connectivity, watching for changes.
Aug 29 17:38:23 debian-noppl systemd-timesyncd[692]: Network configuration changed, trying to establish connection.
Aug 29 17:38:23 debian-noppl systemd-networkd[330]: eno1: No static address is stored.
Aug 29 17:38:23 debian-noppl systemd-networkd[330]: eno1: Failed
Aug 29 17:38:23 debian-noppl rtkit-daemon[921]: Supervising 4 threads of 1 processes of 1 users.
Aug 29 17:38:23 debian-noppl rtkit-daemon[921]: Successfully made thread 7160 of process 1243 owned by '1000' RT at priority 5.
Aug 29 17:38:23 debian-noppl rtkit-daemon[921]: Supervising 5 threads of 1 processes of 1 users.
Aug 29 17:38:26 debian-noppl kernel: ata3: link is slow to respond, please be patient (ready=0)
Aug 29 17:38:27 debian-noppl kernel: e1000e 0000:00:19.0 eno1: NIC Link is Up 1000 Mbps Full Duplex, Flow Control: Rx/Tx

```

**Steps to reproduce the problem**

**Comment by mbiebl** [comment] 2020-08-29 15:57
Duplicate of #16696 ?

**Comment by mbiebl** [comment] 2020-08-29 16:05
I'll upload 246.3 to unstable later today, fwiw

**Comment by poettering** [comment] 2020-08-31 13:58
Closing as duplicate of #16696.

**Closed as completed by poettering** 2020-08-31 13:58 UTC
Labels: network, duplicate
