### ISSUE TITLE
RFE: declare a primary group with sysusers

### ISSUE THREAD

**Issue by dm0-** [systemd/systemd#14340] opened 2019-12-13 21:46 UTC
**Is your feature request related to a problem? Please describe.**
Gentoo now supports using packages to represent system users and groups in dependencies.  I experimented using these packages to configure sysusers which seems viable, but the implicit creation of primary groups is a point of incompatibility with this scheme.  See https://bugs.gentoo.org/702624#c7.

**Describe the solution you'd like**
I would like to be able to specify a user definition that declares its primary group.  Perhaps an optional field can be appended to the `u` line syntax?  I don't have a preference about specifics like whether it requires an preexisting group, or if it would take both name and GID to create it.

**Describe alternatives you've considered**
The alternative is to continue not using sysusers for Gentoo system accounts.

**Comment by poettering** [comment] 2019-12-16 08:38
hmm, you want sysusers.d/ to create user/group pairs that do not match in name? What#s the usecase for that? Can you provide a case where such an asymmetric user/group pair makes sense?

**Comment by dm0-** [comment] 2019-12-16 16:01
The example from the linked Gentoo bug is the [cmd5checkpw](https://github.com/gentoo/gentoo/blob/master/acct-user/cmd5checkpw/cmd5checkpw-0.ebuild) user which uses the `nofiles` group.

I personally don't use any accounts with non-matching primary groups, so I'm not sure how much of a hard requirement they have.  This request was to add compatibility with Gentoo's user/group packaging in general so it can be implemented with sysusers and still behave as expected.

**Comment by yuwata** [comment] 2019-12-16 16:07
Maybe, duplicate of #8046.

**Comment by dm0-** [comment] 2019-12-16 16:20
@yuwata Yes, sorry, I don't know how I missed that when I searched earlier.  It looks like if parts 2 and 3 of your RFE are implemented, that will give the flexibility needed to be compatible with Gentoo.

**Closed as completed** 2020-02-02 15:53 UTC
Labels: RFE 🎁, sysusers
