### ISSUE TITLE
networkd: fail to set jumbo MTU from DHCP

### ISSUE THREAD

**Issue by lucab** [systemd/systemd#9102] opened 2018-05-28 08:29 UTC
**systemd version**
 
systemd: `v238` (i.e. latest)
kernel: `4.14.42-coreos` (confirmed on a more recent `4.16.10-coreos` too)

*NOTE*: ~~setting the MTU works with systemd `237` and kernel `4.15.10-coreos`, thus I believe this is a regression introduced by latest systemd.~~ It may be kernel dependent, see updates in comments.

**Used distribution**

CoreOS Container Linux stable `1745.4.0` (confirmed on latest alpha `1786.1.0` too).

Original report at https://github.com/coreos/bugs/issues/2443.

**Unexpected behaviour you saw**

From networkd debug log at boot:
```
systemd-networkd[569]: eth0: Bringing link up
systemd-networkd[569]: eth0: IPv6 successfully enabled
systemd-networkd[569]: eth0: Flags change: +UP +LOWER_UP +RUNNING
systemd-networkd[569]: LLDP: Started LLDP client
systemd-networkd[569]: eth0: Started LLDP.
systemd-networkd[569]: eth0: Gained carrier
systemd-networkd[569]: eth0: Acquiring DHCPv4 lease
systemd-networkd[569]: DHCP CLIENT (0x5c75aa95): STARTED on ifindex 2
systemd-networkd[569]: DHCP CLIENT (0x5c75aa95): DISCOVER
systemd-networkd[569]: DHCP CLIENT (0x5c75aa95): OFFER
systemd-networkd[569]: DHCP CLIENT (0x5c75aa95): REQUEST (requesting)
systemd-networkd[569]: DHCP CLIENT (0x5c75aa95): ACK
systemd-networkd[569]: DHCP CLIENT (0x5c75aa95): lease expires in 59min 58s
systemd-networkd[569]: DHCP CLIENT (0x5c75aa95): T2 expires in 52min 28s
systemd-networkd[569]: DHCP CLIENT (0x5c75aa95): T1 expires in 30min
systemd-networkd[569]: eth0: DHCPv4 address 172.31.38.34/20 via 172.31.32.1
systemd-networkd[569]: eth0: Setting MTU: 9001
systemd-networkd[569]: Setting transient hostname: 'ip-172-31-38-34'
systemd-networkd[569]: Not connected to system bus, not setting hostname.
systemd-networkd[569]: eth0: Could not set MTU: Invalid argument
systemd-networkd[569]: eth0: Updating address: 172.31.38.34/20 (valid for 1h)
systemd-networkd[569]: eth0: DHCP error: could not get routes: No data available

```

**Steps to reproduce the problem**

This can be reproduced on any AWS instance which support [jumbo frames](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/network_mtu.html). Supported MTU is 9001, and it is advertised via DHCP:

```
07:36:10.895346 IP (tos 0x10, ttl 16, id 0, offset 0, flags [none], proto UDP (17), length 354)
    172.31.32.1.67 > 172.31.38.34.68: [udp sum ok] BOOTP/DHCP, Reply, length 326, xid 0x7c68ae9f, secs 1, Flags [none] (0x0000)
          Your-IP 172.31.38.34
          Client-Ethernet-Address 06:7c:8d:87:b8:3c
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message Option 53, length 1: ACK
            Server-ID Option 54, length 4: 172.31.32.1
            Lease-Time Option 51, length 4: 3600
            Subnet-Mask Option 1, length 4: 255.255.240.0
            Default-Gateway Option 3, length 4: 172.31.32.1
            Hostname Option 12, length 15: "ip-172-31-38-34"
            Domain-Name Option 15, length 29: "eu-central-1.compute.internal"
            Domain-Name-Server Option 6, length 4: 172.31.0.2
            MTU Option 26, length 2: 9001
```

The default link DHCP configuration applied on AWS is:
```
[DHCP]
UseMTU=true
UseDomains=true
```

**Comment by lucab** [comment] 2018-05-28 08:36
/cc @ssahani @poettering 

This regressed in systemd-v238, unrelated to kernel version in use. I suppose it may be related to your MTU rework, but I haven't see anything clearly wrong  in the new MTU parsing code (and logs seem to confirm it is ok).
I tried to strace systemd and networkd to double-check what was actually going through the netlink, but I failed to locate/decode such information.

I don't have debug symbols on CL and I'm not familiar with this netlink code, can you please have a look at this?

**Comment by ssahani** [comment] 2018-05-30 10:20
Ok i tried to recreate your  case using  veth and dnsmasq

dnsmasq.conf
~~~
dhcp-option=26,9001 
~~~

I can see that interface MTU is sent by dnsmasq is 9001
```

```        Rebinding Time Value: (3150s) 52 minutes, 30 seconds                                                                                                                                                        
    Option: (1) Subnet Mask                                                                                                                                                                                         
        Length: 4                                                                                                                                                                                                   
        Subnet Mask: 255.255.255.0                                                                                                                                                                                  
    Option: (28) Broadcast Address                                                                                                                                                                                  
        Length: 4                                                                                                                                                                                                   
        Broadcast Address: 192.168.111.255                                                                                                                                                                          
    Option: (15) Domain Name                                                                                                                                                                                        
        Length: 16                                                                                                                                                                                                  
        Domain Name: example-test.com                                                                                                                                                                               
    Option: (26) Interface MTU                                                                                                                                                                                      
        Length: 2                                                                                                                                                                                                   
        Interface MTU: 9001                   <===================here                                                                                                                                                                      
    Option: (6) Domain Name Server                                                                                                                                                                                  
        Length: 8                                                                                                                                                                                                   
        Domain Name Server: 8.8.8.8                                                                                                                                                                                 
        Domain Name Server: 8.8.4.4                                                                                                                                                                                 
    Option: (3) Router                                                                                                                                                                                              
        Length: 4                    
~~~

networkd logs
```o: Unmanaged
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_31 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=28 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
veth-test: Removing address: 192.168.111.58/24 (valid for 59min 51s)
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_37 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=29 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
DHCP CLIENT (0x6e6d32ec): ACK
DHCP CLIENT (0x6e6d32ec): lease expires in 59min 57s
DHCP CLIENT (0x6e6d32ec): T2 expires in 52min 27s
DHCP CLIENT (0x6e6d32ec): T1 expires in 29min 58s
veth-test: DHCPv4 address 192.168.111.58/24 via 192.168.1.1
veth-test: Setting MTU: 9001 <===================================HERE
Setting transient hostname: 'Zeus'
Sent message type=method_call sender=n/a destination=org.freedesktop.hostname1 path=/org/freedesktop/hostname1 interface=org.freedesktop.hostname1 member=SetHostname cookie=30 reply_cookie=0 signature=sb error-name=n/a error-message=n/a
Got message type=method_return sender=:1.167 destination=:1.168 path=n/a interface=n/a member=n/a cookie=5 reply_cookie=30 signature=n/a error-name=n/a error-message=n/a
veth-test: Updating address: 192.168.111.58/24 (valid for 1h)
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_37 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=31 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
veth-test: DHCP error: could not get routes: No data available
```

ip addr show dev veth-test
```
7: veth-test@veth-peer: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc noqueue state UP group default qlen 1000
    link/ether 7e:da:3f:d6:af:03 brd ff:ff:ff:ff:ff:ff
    inet 192.168.111.58/24 brd 192.168.111.255 scope global dynamic veth-test
       valid_lft 3581sec preferred_lft 3581sec
    inet6 fe80::7cda:3fff:fed6:af03/64 scope link 
       valid_lft forever preferred_lft forever
```

So basically I am not able to reproduce it . So kernel is not setting it that leads to the interface is not allowing ?

I did a code search to kernel networking which leads me to something called '''JUMBO_MTU""

```
0 acenic.c               353 #define ACE_JUMBO_BUFSIZE (ACE_JUMBO_MTU + ETH_HLEN + 4)
1 acenic.c               480 dev->max_mtu = ACE_JUMBO_MTU;
2 acenic.h               170 #define ACE_JUMBO_MTU 9000
3 bnx2x.h                621 #define BNX2X_FCOE_MINI_JUMBO_MTU 2500
4 bnx2x_cmn.c           2017 mtu = BNX2X_FCOE_MINI_JUMBO_MTU;
5 bnx2x_main.c          3171 gen_init->mtu = BNX2X_FCOE_MINI_JUMBO_MTU;
6 bnad.c                3463 netdev->max_mtu = BNAD_JUMBO_MTU;
7 bnad.h                  91 #define BNAD_JUMBO_MTU   9000
8 skge.c                  63 #define ETH_JUMBO_MTU  9000
9 skge.c                3868 dev->max_mtu = ETH_JUMBO_MTU;
a sky2.c                4817 dev->max_mtu = ETH_JUMBO_MTU;
b sky2.h                   8 #define ETH_JUMBO_MTU  9000 /* Maximum MTU supported */
c sky2.h                2204 dma_addr_t frag_addr[ETH_JUMBO_MTU >> PAGE_SHIFT];
d nixge.c                102 #define NIXGE_JUMBO_MTU  9000 /* Max MTU of a jumbo Eth. frame */
e nixge.c                106 (NIXGE_JUMBO_MTU + NIXGE_HDR_SIZE + NIXGE_TRL_SIZE)
f nixge.c               1202 ndev->max_mtu = NIXGE_JUMBO_MTU;
g qla3xxx.c             2848 } else if (qdev->ndev->mtu == JUMBO_MTU_SIZE) {
h qla3xxx.c             2853 qdev->lrg_buffer_len = JUMBO_MTU_SIZE;
i qla3xxx.c             2856 qdev->ndev->mtu, NORMAL_MTU_SIZE, JUMBO_MTU_SIZE);
j qla3xxx.h              935 #define JUMBO_MTU_SIZE    9000
k ll_temac.h              18 #define XTE_JUMBO_MTU   9000
l ll_temac.h              19 #define XTE_MAX_JUMBO_FRAME_SIZE (XTE_JUMBO_MTU + XTE_HDR_SIZE + XTE_TRL_SIZE)
m xilinx_axienet.h        21 #define XAE_JUMBO_MTU        9000 /* Max MTU of a jumbo Eth. frame */
n xilinx_axienet.h        25 #define XAE_MAX_JUMBO_FRAME_SIZE (XAE_JUMBO_MTU + XAE_HDR_SIZE + XAE_TRL_SIZE)
o xilinx_axienet_main.c  480 (ndev->mtu <= XAE_JUMBO_MTU)) {
p xilinx_axienet_main.c 1472 ndev->max_mtu = XAE_JUMBO_MTU;
q bnx2fc.h                99 #define BNX2FC_MINI_JUMBO_MTU  2500
r bnx2fc_hwi.c            92 fcoe_init1.mtu = BNX2FC_MINI_JUMBO_MTU;
s qedi_iscsi.c          1251 if (path_data->pmtu > JUMBO_MTU) {
t qedi_iscsi.h            35 #define JUMBO_MTU  9000

```

Does your driver supports this ?

**Comment by lucab** [comment] 2018-05-30 12:45
> Does your driver supports this?

Yes, it does. For reference, the driver is `xen_netfront` and the cloud environment is AWS. Setting a 9001 MTU used to work up to a couple of months ago, and only recently regressed.

But you are right that this may be a driver-specific weird interaction between networkd and the kernel.
I did a couple more tests with systemd-v238 and various kernels on AWS, and this is the recap:
 * `4.16.10-coreos`: not working
 * `4.16.3-coreos`: not working
 * `4.15.15-coreos`: working
 * `4.14.42-coreos`: not working
 * `4.14.35-coreos`: working

Thus systemd-v238 seems to work sometimes on some older kernels, which points to either an environmental race or some kernel changes backported to the 4.14.x stable tree.
So I started looking into any potentially related changes in kernels between (`4.15.15`, `4.16.3`) and (`4.14.35`, `4.14.42`), and found this one which seems interesting: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/commit/?id=f599c64fdf7d9c108e8717fb04bc41c680120da4

**Comment by bgilbert** [comment] 2018-05-31 01:41
Reverting coreos/linux@f599c64fdf7d9c108e8717fb04bc41c680120da4 did indeed fix the problem.

**Comment by ssahani** [comment] 2018-05-31 09:11
So we can close this ?

**Comment by ajeddeloh** [comment] 2018-05-31 23:58
Yes.

**Closed as completed** 2018-06-01 01:04 UTC
Labels: network, not-our-bug, dhcp
