### ISSUE TITLE
Group permissions for credentials when setting User or DynamicUser=1

### ISSUE THREAD

**Issue by thrasibule** [systemd/systemd#29096] opened 2023-09-05 21:30 UTC
### systemd version the issue has been seen with

254.1-1

### Used distribution

Arch

### Linux kernel version used

6.4.12-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Credential files used to have 600 permission, which is still the case if I don't specify a uid/gid. 

### Unexpected behaviour you saw

However if run with DynamicUser=1, or specify a user they're also group readable.

### Steps to reproduce the problem

I have a pgpass password file for postgres that I store in /etc/credstore. That file needs to have 600 permission for libpq to accept to read it.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
sudo systemd-run -t --property LoadCredential=key:/etc/credstore/pgpass sh -c 'ls -l "${CREDENTIALS_DIRECTORY}/key"'
Running as unit: run-u90.service
Press ^] three times within 1s to disconnect TTY.
-r-------- 1 root root 244 Sep  5 17:24 /run/credentials/run-u90.service/key

sudo systemd-run -t --property DynamicUser=1 --property LoadCredential=key:/etc/credstore/pgpass sh -c 'ls -l "${CREDENTIALS_DIRECTORY}/key"'
Press ^] three times within 1s to disconnect TTY.
-r--r-----+ 1 root root 244 Sep  5 17:25 /run/credentials/run-u93.service/key
```

**Comment by YHNdnzj** [comment] 2023-10-13 23:06
#29435 is a duplicate of this issue, but it contains more details. So closing this one instead.

**Closed as completed by YHNdnzj** 2023-10-13 23:06 UTC
Labels: bug 🐛, pid1
