### ISSUE TITLE
Starting/Started/Stopping/Stopped log messages only include description, which is imprecise on templated services

### ISSUE THREAD

**Issue by grooverdan** [systemd/systemd#8655] opened 2018-04-04 23:03 UTC
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

systemd 219
(however appears unchanged looking at `unit_status_printf`/`unit_get_status_message_format` functions)

### Used distribution

Centos7

### In case of bug report: Expected behaviour you didn't see

<pre>
systemd[1]: Started MariaDB @VERSION@ database server (multi-instance). (mariadb1@1.service)
</pre>

### In case of bug report: Unexpected behaviour you saw

<pre>
systemd[1]: Started MariaDB @VERSION@ database server (multi-instance).
</pre>

### In case of bug report: Steps to reproduce the problem

Start/Stop a templated service and look at logs to see which instance it is.

A failed service includes as followed but for non-failure cases its too brief.
<pre>
systemd[1]: mariadb1@1.service start-pre operation timed out. Terminating.
systemd[1]: Failed to start MariaDB @VERSION@ database server (multi-instance).
systemd[1]: Unit mariadb1@1.service entered failed state.
systemd[1]: mariadb1@1.service failed.
</pre>

**Comment by grooverdan** [comment] 2018-04-04 23:42
A work around exists - putting '%n' in the description.

**Comment by filbranden** [comment] 2018-04-04 23:50
The journal is actually rich and has more fields...

If you use `journalctl -o verbose` you should see something like:

```
Sat 2018-03-31 12:34:56.123456 UTC [s=abcdef123456abcdef123456;i=1234;b=abcdef123456abcdef123456;m=a1b2c3d4e5f6;t=a1b2c3d4e5f6;x=a1b2c3d4e5f6]
    UNIT=mariadb1@1.service
    MESSAGE=Failed to start MariaDB @VERSION@ database server (multi-instance).
    ... (many other fields)
```

I understand that maybe that's *too* verbose for your needs though... But the data is there, somewhere...

**Comment by grooverdan** [comment] 2018-04-05 00:02
yeh, that's probably good enough.

**Comment by filbranden** [comment] 2018-04-07 15:30
Well, there's `journalctl -o verbose` and `journalctl -o export` and you can filter these to only include the entries that are relevant to you...

But I do take the point, sometimes you care about only one additional variable, maybe we should have a shortcut to include only one of them (other than the syslog-like formatted contents including MESSAGE and the usual time/host/tag/pid fields...)

**Comment by arvidjaar** [comment] 2018-04-07 19:43
> But I do take the point

To make the point clear - logs should contain useful information by default and users should not jump through the hoops to get them. 

Do not assume everyone will have access to journal. Many people still forward journal to syslog and use it. Default message must be useful without any extra steps.

**Comment by grooverdan** [comment] 2018-04-08 22:25
reopening as its more than just me thinking it could be better (and its a pretty easy fix).

**Comment by poettering** [comment] 2018-04-09 08:59
@grooverdan wozuldn't it be nicer if your service would just use %i/%I in the Description field, so that you actually get a pretty instance name shown?

**Comment by poettering** [comment] 2018-04-09 09:00
(i mean, the idea is that the Description= field contains a pretty, helpful, sufficiently comprehensive description of the service. If that description is crappy then that's sounds like something to fix in the unit file)

**Comment by boucman** [comment] 2018-04-09 09:09
Having regularly to debu other people's logs on systems I don't know... I kinda agree that having the "real" name would be more usefull... 

It's more usefull to have the real name and then use "systemctl cat" to have the description then having a description and figuring out what the actual service is.

Even well formed Description are usually not sufficient to match the service name right away, because most of them don't contain the daemon name... moreover for complex daemons made of multiple units, it's hard to figure which of the slightly differently named units is the guilty party...

Documenting that the Description= field should use %i and doing it in systemd-provided services could be a good first step... but at this point you might as well hard code it in the code.

**Comment by poettering** [comment] 2019-03-11 13:16
Duplicate of #5356

**Closed as completed by poettering** 2019-03-11 13:16 UTC
Labels: RFE 🎁, pid1, duplicate
