### ISSUE TITLE
systemd.mount trying to mount unavailable smb share freezes the desktop momentarily

### ISSUE THREAD

**Issue by cyberpunkrocker-zero** [systemd/systemd#34798] opened 2024-10-16 17:17 UTC
### systemd version the issue has been seen with

256.7

### Used distribution

Arch Linux

### Linux kernel version used

6.6.56-native_amd-xanmod1-1-lts

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Systemd working in the background without bothering the desktop.

### Unexpected behaviour you saw

I have a separate server hosting a Samba service, which server is currently down for hardware reasons. Systemd is periodically, in every 10 minutes or so, trying to mount the unavailable smb share. Whenever that happens, _EVERY_ time,  _the whole desktop freezes for a few seconds!!!_

I was running `journalctl -f` on a terminal to verify the simultaneousity of the mount/freeze events. This kind of thing shouldn't be happening, ever!

The process 1942 (awesome) mentioned in the log excerpt is my window manager's (Awesome WM on X) process. I don't understand why it would be the triggering process, and why systemd is allowed to freeze it?

I had to temporarily comment out the smb share entry in /etc/fstab to make desktop to run smoothly again.

### Steps to reproduce the problem

1. Have a network mount down
2. Wait for a few minutes 
3. Watch in dismay as the desktop freezes for a few seconds periodically when systemd tries to mount the unavailable share 

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
loka 14 20:43:06 neverwinter systemd[1]: mnt-smbshare.automount: Got automount request for /mnt/smbshare, triggered by 1942 (awesome)
loka 14 20:43:06 neverwinter systemd[1]: Mounting /mnt/smbshare...
loka 14 20:43:06 neverwinter kernel: CIFS: enabling forceuid mount option implicitly because uid= option is specified
loka 14 20:43:06 neverwinter kernel: CIFS: enabling forcegid mount option implicitly because gid= option is specified
loka 14 20:43:06 neverwinter kernel: CIFS: Attempting to mount //192.168.1.10/share
loka 14 20:43:12 neverwinter mount[61982]: mount error(113): could not connect to 192.168.1.10Unable to find suitable address.
loka 14 20:43:12 neverwinter systemd[1]: mnt-smbshare.mount: Mount process exited, code=exited, status=32/n/a
loka 14 20:43:12 neverwinter systemd[1]: mnt-smbshare.mount: Failed with result 'exit-code'.
loka 14 20:43:12 neverwinter systemd[1]: Failed to mount /mnt/smbshare.
loka 14 20:43:12 neverwinter kernel: CIFS: VFS: Error connecting to socket. Aborting operation.
loka 14 20:43:12 neverwinter kernel: CIFS: VFS: cifs_mount failed w/return code = -113
```

**Comment by yuwata** [comment] 2024-10-16 17:49
Should be a bug in the kernel. Please try to manually mount the unavailable smb share, then I guess you can reproduce the few seconds freeze.

**Comment by cyberpunkrocker-zero** [comment] 2024-10-16 18:26
No, I cannot reproduce the delay manually, neither before nor after rebooting. And if it is a kernel bug, then the bug is in several kernel versions; originally tried in addition to xanmod kernel, the plain linux-lts-6.6.56 and 6.11.2.

Also noticed that the mount-try adds a noticeable delay in starting the X server (using just startx)

**Comment by YHNdnzj** [comment] 2024-10-16 19:04
> Systemd is periodically, in every 10 minutes or so, trying to mount the unavailable smb share. Whenever that happens, EVERY time, the whole desktop freezes for a few seconds!!!

Combining that with the logged triggering process below, it seems pretty obvious that your window manager synchronously waits for the mount to be established? Everything works as expected from systemd's PoV? The reason why `awesome` triggers automount is out of the scope of systemd's bug tracker.

**Comment by YHNdnzj** [comment] 2024-10-16 19:11
> No, I cannot reproduce the delay manually

Well, that's because it doesn't involve any automount mechanism. It's NOT the _mount_ that hangs your desktop, it's your window manager's access to that autofs mountpoint. IOW, figure out why your window manager tries to access that dir.

**Comment by poettering** [comment] 2024-10-17 06:09
Yeah, this is your window managar triggering the mount, because it wants to access that fs. We cannot tell you why it does it, but it does it, and systemd will log about this fact, that the kernel reports to it. 

There's nothing actionable for us here. Please find out why your window manager accesses the fs, but this is not the right place to track that. closing hence.

**Closed as completed by poettering** 2024-10-17 06:09 UTC
Labels: pid1, not-our-bug
