### ISSUE TITLE
systemd-networkd has wrong network config match for veth interfaces

### ISSUE THREAD

**Issue by alexandrem** [systemd/systemd#14399] opened 2019-12-19 18:33 UTC
**systemd version the issue has been seen with**
v241

**Used distribution**
 CoreOS 2303.3.0

**Expected behaviour you didn't see**
All veth devices are properly matched with the file in `/run/systemd/network/` directory that has a matching rule for veth driver, such as:

```
# cat /run/systemd/network/90-docker-veth.network
[Match]
Driver=veth

[Link]
Unmanaged=yes
```

That would make the veth interfaces unmanaged.

**Unexpected behaviour you saw**
 Some veth devices aren't matched to the proper network config file, but rather with:

```
# cat /usr/lib64/systemd/network/zz-default.network
[Network]
DHCP=yes

[DHCP]
UseMTU=true
UseDomains=true
```

systemd debug logs show that the first few interfaces are correctly matched, then the rest aren't, e.g
```
Dec 18 23:26:26 worker1 systemd-networkd[11630]: cali730edf540cf: Link state is up-to-date
Dec 18 23:26:26 worker1 systemd-networkd[11630]: cali730edf540cf: found matching network '/run/systemd/network/90-docker-veth.network'
Dec 18 23:26:26 worker1 systemd-networkd[11630]: cali730edf540cf: Unmanaged
Dec 18 23:26:26 worker1 systemd-networkd[11630]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_3976489 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=31 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Dec 18 23:26:26 worker1 systemd-networkd[11630]: cali610c810832d: Link state is up-to-date
Dec 18 23:26:26 worker1 systemd-networkd[11630]: cali610c810832d: found matching network '/run/systemd/network/90-docker-veth.network'
Dec 18 23:26:26 worker1 systemd-networkd[11630]: cali610c810832d: Unmanaged
Dec 18 23:26:26 worker1 systemd-networkd[11630]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_3976488 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=32 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Dec 18 23:26:26 worker1 systemd-networkd[11630]: cali4d867c9a59c: Link state is up-to-date
Dec 18 23:26:26 worker1 systemd-networkd[11630]: cali4d867c9a59c: found matching network '/run/systemd/network/90-docker-veth.network'
Dec 18 23:26:26 worker1 systemd-networkd[11630]: cali4d867c9a59c: Unmanaged
Dec 18 23:26:26 worker1 systemd-networkd[11630]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_3976487 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=33 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Dec 18 23:26:26 worker1 systemd-networkd[11630]: caliba90aa1e746: Link state is up-to-date
Dec 18 23:26:26 worker1 systemd-networkd[11630]: caliba90aa1e746: found matching network '/usr/lib64/systemd/network/zz-default.network'
Dec 18 23:26:26 worker1 systemd-networkd[11630]: LLDP: Started LLDP client
Dec 18 23:26:26 worker1 systemd-networkd[11630]: caliba90aa1e746: Started LLDP.
Dec 18 23:26:26 worker1 systemd-networkd[11630]: caliba90aa1e746: Setting address genmode for link
Dec 18 23:26:26 worker1 systemd-networkd[11630]: caliba90aa1e746: Acquiring DHCPv4 lease
Dec 18 23:26:26 worker1 systemd-networkd[11630]: DHCP CLIENT (0xec12b347): STARTED on ifindex 976486
```
**Steps to reproduce the problem**

This is on a Kubernetes cluster using the [canal](https://docs.projectcalico.org/v3.10/getting-started/kubernetes/installation/flannel) CNI plugin.

This is using the latest CoreOS stable release available [2303.3.0](https://coreos.com/releases/#2303.3.0).

```
# cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2303.3.0
VERSION_ID=2303.3.0
BUILD_ID=2019-12-02-2049
PRETTY_NAME="Container Linux by CoreOS 2303.3.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"
```
Restarting the `systemd-networkd` service will show that some calico interfaces (prefixed by `cali`) have their network config for the veth driver ignored and the default system one is used instead.

Expected:  /run/systemd/network/90-docker-veth.network
Actual: /usr/lib64/systemd/network/zz-default.network

All interfaces are veth:

```
# ethtool -i caliba90aa1e746
driver: veth
version: 1.0
firmware-version:
expansion-rom-version:
bus-info:
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no
```

As a workaround, adding this network config that matches on the interface name solves the issue and will interpret all `cali*` interfaces as unmanaged.

```
# cat /etc/systemd/network/cali.network
[Match]
Name=cali*

[Link]
Unmanaged=yes
```

Full systemd-networkd service log in debug during restart are available at: https://gist.github.com/alexandrem/b402ed23a42417933758c8d8b9289c62

**Comment by yuwata** [comment] 2019-12-20 11:53
Are there any chance to test v244?

**Comment by alexandrem** [comment] 2019-12-20 16:37
I just tested on Ubuntu 20.04 which has v243.

I'm not able to reproduce the bug on that version. I have approximately the same number of calico veth interfaces (18) and having same networkd config layout than my other problematic node.

It correctly selects the file `/run/systemd/network/90-docker-veth.network` for all interfaces.

**Comment by yuwata** [comment] 2019-12-26 06:35
So, the issue is apparently fixed within v243 or v242. I cannot remember which fixes the issue. If you want, please bisect and report which commit fixes the issue to your distro. Thank you. Closing.

**Closed as completed by yuwata** 2019-12-26 06:35 UTC
Labels: network
