### ISSUE TITLE
Wake up from suspend-then-hibernate not completing

### ISSUE THREAD

**Issue by Wallaby111** [systemd/systemd#25365] opened 2022-11-12 20:10 UTC
### systemd version the issue has been seen with

252.1.1

### Used distribution

Arch

### Linux kernel version used

6.0.8-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-logind

### Expected behaviour you didn't see

When waking from suspend-then-hibernate to have full control over desktop and windows.

### Unexpected behaviour you saw

When waking from suspend-then-hibernate, screen comes back on and windows appear but are not interactive. I cannot type in them or move them. I am using Qtile as a window manager and all the elements on the bar are also unresponsive and do not change. Both hibernate and suspend used separately work as expected. Rolling back to version 251.7 fixes all issues.

### Steps to reproduce the problem

Use `systemctl suspend-then-hibernate` or close laptop lid (when set to suspend-then-hibernate in /etc/systemd/logind.conf). Then press any key to send a wake command or open laptop lid.

**Comment by yuwata** [comment] 2022-11-13 03:55
This seems to be a duplicate of #25356.

**Closed as completed by yuwata** 2022-11-13 03:55 UTC
Labels: bug 🐛, login, duplicate, sleep
