### ISSUE TITLE
Leak of virtual net device unit

### ISSUE THREAD

**Issue by cynron** [systemd/systemd#17852] opened 2020-12-04 08:09 UTC
**systemd version: 246**
 
**Used distribution**
 
Debian 10 (buster) 

**Linux kernel version used** 

Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux

**CPU architecture issue was seen on**

 amd64

**Steps to reproduce the problem**
 
```
# ip link add vetha type veth peer vethb
# ip link set vetha name vetha
# ip link set vetha name vethaa
# ip link del vethaa
# systemctl list-units --all | grep vetha
  sys-devices-virtual-net-vetha.device                                                        loaded    active   plugge
d   /sys/devices/virtual/net/vetha                                    
  sys-subsystem-net-devices-vetha.device                                                      loaded    active   plugge
d   /sys/subsystem/net/devices/vetha    
```
**Expected behaviour you didn't see**
 
After deleting `vethaa`, the related device units should be deleted too.

**Unexpected behaviour you saw**

After deleting `vethaa`, the related device units is leaky.

We have observed  thousands of this leak from some of our kubernetes worker nodes.

`systemctl daemon-reload` would be of help to release the leaky device unit.

I can reproduce the problem on Debian 10 & Centos 8. 

on Debian 10, I have tested systemd version **241** and latest **246.6-2~bpo10+1**
on Centos 8, systemd version is **239**.

Besides, https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1742250 this bug report may be related.

**Comment by yuwata** [comment] 2020-12-04 08:17
Duplicate of #16967.
Already fixed by #16968.

**Closed as completed by yuwata** 2020-12-04 08:17 UTC
Labels: duplicate, already-fixed
