### ISSUE TITLE
Mount option 'nofail' not usable with fuse.bindfs based filesystems

### ISSUE THREAD

**Issue by vicinus** [systemd/systemd#5032] opened 2017-01-06 07:50 UTC
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> debian unstable

### In case of bug report: Expected behaviour you didn't see

> I want to use the _nofail_ option in /etc/fstab to ensure that the boot up process is finished and no emergency mode is entered on trying to mount some fuse.bindfs mounts during boot up.
>
> It should be possible to use the _nofail_ option in /etc/fstab with all types of filesystems.

### In case of bug report: Unexpected behaviour you saw

> The Problem is, that the _nofail_ option is passed by the mount command line tool to the mount tool specific to the filesystem type and fuse.bindfs based filesystems do not support the nofail option and therefore fail, which is rater ironically...
>
> One possible solution would be to add _x-systemd.nofail_ and _x-systemd.fail_ with the behaviour to override an eventually existing _nofail_ and _fail_ option. As the new options are systemd specific they will not be passed to filesystem type specific mount tool and can therefore be safely used filesystem type specific mount tool does not support _nofail_.

### In case of bug report: Steps to reproduce the problem

> Install bindfs and add a line like:
>
> `/usr            /mnt            fuse.bindfs  defaults,nofail   0       0`
>
> Try to mount it and the error message is:
>
> `fuse: unknown option 'nofail'`
>
> Without the option _nofail_ the mount works fine.

**Comment by poettering** [comment] 2017-01-06 09:20
"nofail" is an option that has been around since a long time and is handled by /bin/mount itself, systemd just honours it too. If fuse.bindfs has issues with it, then this needs to be fixed in fuse.bindfs, we won't work around it in systemd.

See the fstab(5) man page for details, the tool should at least drop all generic options listed there, of which "nofail" is one.

Closing hence, as this is not a bug in systemd.

**Closed as completed by poettering** 2017-01-06 09:20 UTC
Labels: not-our-bug, fstab-generator

**Comment by vicinus** [comment] 2017-01-06 13:17
According to fstab(5) man page the meaning of the original "nofail" option is:

> Do not report errors for this device if it does not exist.

But according to systemd.mount(5) the meaning of the "nofail" option is:

> With nofail, this mount will be only wanted, not required, by local-fs.target or remote-fs.target. This means that the boot will continue even if this mount point is not mounted successfully.

So at the moment it is not possible to configure systemd to use nofail to continue boot and to configure the filesystem mount to report an error on a missing device, because you changed the meaning of the "nofail" option...

**Comment by RenatoXSR** [comment] 2018-10-20 16:13
*(Sorry for being 1 year late on the issue)*

Actually, I believe the problem is trying to use fstab to implement a systemd mountpoint. @vicinus should use a systemd.mount file, and not an `/etc/fstab` entry, to accomplish the `nofail` behaviour wanted.

See [`man systemd.mount`](https://www.freedesktop.org/software/systemd/man/systemd.mount.html#nofail) for details. Look for the `nofail` option or try a different approach by making the mount unit Want or Require some required unit (such as an specific device or connection).

Hope this help in future web searches.

-- 
Renato.

**Comment by Reiner030** [comment] 2018-10-22 11:04
Systemd works fine with nofail option but saltstack recognize this warning as failure.
So Saltstack recognizes mount as failed and finally didn't mount / do the fstab entry **which is the wrong behavior** .

For this case this issue was surely initally setup.

**Comment by avliet** [comment] 2019-06-06 00:02
OK, I'm running into this issue on a regular basis now.  Kind of annoying.  No; definitely annoying.  Has there been any movement, or are fuse and systemd just flipping the bird at each other while throwing the hot potato back over the fence - and simultaneously continuing to ignore admins and users encountering the issue..?

**Comment by Reiner030** [comment] 2019-06-06 12:43
In my case I setup doubled states where first state has same setup except nofail option and is run only if mountpoint is not already mounted.
