### ISSUE TITLE
systemd-resolved wrongly assumes enabled DNSSEC when DNSKEY record is a CNAME

### ISSUE THREAD

**Issue by rouven0** [systemd/systemd#31699] opened 2024-03-10 11:50 UTC
### systemd version the issue has been seen with

255

### Used distribution

nixos-unstable

### Linux kernel version used

6.7.7

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

When querying a domain that has a CNAME record at the Domain level, systemd-resolved wrongly assumes that this domain has enabled DNSSEC.
`terranix.org` for example is such a domain. (Not operated by me, just using it for demonstration purposes).
The expected behaviour is that systemd-resolved discards that CNAME record as invalid DNSKEY and treats the domain as a domain without enabled DNSSEC.

### Unexpected behaviour you saw

Systemd-resolved wrongly thinks this Domain has DNSSEC enabled. As a result every query fails with the status code `no-signature`.

```
$ resolvectl query terranix.org
terranix.org: resolve call failed: DNSSEC validation failed: no-signature
```

### Steps to reproduce the problem

- Have a domain that only has a CNAME record at domain-level.
- Query it with systemd-resolved and DNSSEC enabled.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
$ dig DNSKEY terranix.org 

; <<>> DiG 9.18.24 <<>> DNSKEY terranix.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62229
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;terranix.org.			IN	DNSKEY

;; ANSWER SECTION:
terranix.org.		1310	IN	CNAME	terranix.github.io.
```

**Comment by rouven0** [comment] 2024-03-10 11:53
Debug logs of the query: https://gist.github.com/rouven0/8ce8b6d371c48f9da58ef31fcc23753e

**Comment by rpigott** [comment] 2024-03-11 09:13
This is expected behavior — the dns answer is bogus. If you disable dnssec validation we probably won't notice the error though.

Duplicate of #31484

**Closed as not planned** 2024-03-11 10:38 UTC
Labels: bug 🐛, resolve
