### ISSUE TITLE
Question: is systemd supposed to retry failed units at login?

### ISSUE THREAD

**Issue by nolange** [systemd/systemd#15242] opened 2020-03-27 12:05 UTC
**systemd version the issue has been seen with**
> systemd 245 (245)
> -PAM -AUDIT -SELINUX -IMA -APPARMOR -SMACK -SYSVINIT -UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS -ACL -XZ +LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN -PCRE2 default-hierarchy=unified

I dont get what logic is system applying to failed units, it seems that aslong as a single failed unit is in a target (eg. sysinit.target or multiuser.target) then after every new login:

- Failed units are restarted (unless their StartLimitIntervalSec in not expired? )
- Conditional units are reevaluated

Search for login in the text below to see that after this a row of services will be restarted/reevaluated.

Main culprits seem to be systemd-time-wait-sync.service and create-config.service, both wanted by sysinit.target.

```
Mar 06 15:31:58 buildroot systemd[1]: Condition check resulted in Journal Audit Socket being skipped.
Mar 06 15:31:58 buildroot systemd[1]: Listening on Journal Socket (/dev/log).
Mar 06 15:31:58 buildroot systemd[1]: Listening on Journal Socket.
Mar 06 15:31:58 buildroot systemd[1]: Listening on Network Service Netlink Socket.
Mar 06 15:31:58 buildroot systemd[1]: Listening on udev Control Socket.
Mar 06 15:31:58 buildroot systemd[1]: Listening on udev Kernel Socket.
Mar 06 15:31:58 buildroot systemd[1]: Mounting Huge Pages File System...
Mar 06 15:31:58 buildroot systemd[1]: Mounting POSIX Message Queue File System...
Mar 06 15:31:58 buildroot systemd[1]: Mounting Kernel Debug File System...
Mar 06 15:31:58 buildroot systemd[1]: Mounting Kernel Trace File System...
Mar 06 15:31:58 buildroot systemd[1]: Mounting Temporary Directory (/tmp)...
Mar 06 15:31:58 buildroot systemd[1]: Mounting Large Temporary Directory (/var/tmp)...
Mar 06 15:31:58 buildroot systemd[1]: Condition check resulted in Entropy Harvesting Daemon being skipped.
Mar 06 15:31:58 buildroot systemd[1]: Condition check resulted in Create list of static device nodes for the current kernel being skipped.
Mar 06 15:31:58 buildroot systemd[1]: Starting File System Check on Root Device...
Mar 06 15:31:58 buildroot systemd[1]: Starting Journal Service...
Mar 06 15:31:58 buildroot systemd[1]: Condition check resulted in Load Kernel Modules being skipped.
Mar 06 15:31:58 buildroot systemd[1]: Mounting FUSE Control File System...
Mar 06 15:31:58 buildroot systemd[1]: Mounting Kernel Configuration File System...
Mar 06 15:31:58 buildroot systemd[1]: Starting Generate network units from Kernel command line...
Mar 06 15:31:58 buildroot systemd[1]: Starting Apply Kernel Variables...
Mar 06 15:31:58 buildroot systemd[1]: Starting Wait Until Kernel Time Synchronized...
Mar 06 15:31:58 buildroot systemd-journald[561]: Journal started
Mar 06 15:31:58 buildroot systemd-journald[561]: Runtime Journal (/run/log/journal/fdd0189472c24ef8a81c5b63f2d53006) is 8.0M, max 188.9M, 180.9M free.
Mar 06 15:31:58 buildroot systemd-sysctl[566]: Not setting net/ipv4/conf/all/rp_filter (explicit setting exists).
Mar 06 15:31:58 buildroot systemd-sysctl[566]: Not setting net/ipv4/conf/default/rp_filter (explicit setting exists).
Mar 06 15:31:58 buildroot systemd-sysctl[566]: Not setting net/ipv4/conf/all/accept_source_route (explicit setting exists).
Mar 06 15:31:58 buildroot systemd-sysctl[566]: Not setting net/ipv4/conf/default/accept_source_route (explicit setting exists).
Mar 06 15:31:58 buildroot systemd-sysctl[566]: Not setting net/ipv4/conf/all/promote_secondaries (explicit setting exists).
Mar 06 15:31:58 buildroot systemd-sysctl[566]: Not setting net/ipv4/conf/default/promote_secondaries (explicit setting exists).
Mar 06 15:31:58 buildroot systemd-sysctl[566]: Couldn't write 'fq_codel' to 'net/core/default_qdisc', ignoring: No such file or directory
Mar 06 15:31:58 buildroot systemd-fsck[562]: /dev/mmcblk0p3: clean, 4586/229376 files, 139033/917504 blocks
Mar 06 15:31:58 buildroot systemd-time-wait-sync[567]: adjtime state 5 status 40 time Fri 2020-03-06 15:31:58.889228 UTC
Mar 06 15:31:58 buildroot systemd[1]: Starting Create Static Device Nodes in /dev...
Mar 06 15:31:58 buildroot systemd[1]: Starting udev Coldplug all Devices...
Mar 06 15:31:58 buildroot systemd[1]: Started Journal Service.
Mar 06 15:31:59 buildroot systemd[1]: Mounted Huge Pages File System.
Mar 06 15:31:59 buildroot systemd[1]: Mounted POSIX Message Queue File System.
Mar 06 15:31:59 buildroot systemd[1]: Mounted Kernel Debug File System.
Mar 06 15:31:59 buildroot systemd[1]: Mounted Kernel Trace File System.
Mar 06 15:31:59 buildroot systemd[1]: Mounted Temporary Directory (/tmp).
Mar 06 15:31:59 buildroot systemd[1]: Mounted Large Temporary Directory (/var/tmp).
Mar 06 15:31:59 buildroot systemd[1]: Finished File System Check on Root Device.
Mar 06 15:31:59 buildroot systemd[1]: Mounted FUSE Control File System.
Mar 06 15:31:59 buildroot systemd[1]: Mounted Kernel Configuration File System.
Mar 06 15:31:59 buildroot systemd[1]: Finished Generate network units from Kernel command line.
Mar 06 15:31:59 buildroot systemd[1]: Finished Apply Kernel Variables.
Mar 06 15:31:59 buildroot systemd[1]: Finished Create Static Device Nodes in /dev.
Mar 06 15:31:59 buildroot systemd[1]: Starting Remount Root and Kernel File Systems...
Mar 06 15:31:59 buildroot kernel: EXT4-fs (mmcblk0p3): re-mounted. Opts: (null)
Mar 06 15:31:59 buildroot systemd[1]: Starting udev Kernel Device Manager...
Mar 06 15:31:59 buildroot systemd[1]: Finished Remount Root and Kernel File Systems.
Mar 06 15:31:59 buildroot systemd[1]: Started udev Kernel Device Manager.
Mar 06 15:31:59 buildroot systemd[1]: Reached target Local File Systems (Pre).
Mar 06 15:31:59 buildroot systemd[1]: Reached target Local File Systems.
Mar 06 15:31:59 buildroot systemd[1]: Starting Flush Journal to Persistent Storage...
Mar 06 15:31:59 buildroot systemd[1]: Condition check resulted in Commit a transient machine-id on disk being skipped.
Mar 06 15:31:59 buildroot systemd[1]: Condition check resulted in Platform Persistent Storage Archival being skipped.
Mar 06 15:31:59 buildroot systemd[1]: Condition check resulted in Update is Completed being skipped.
Mar 06 15:31:59 buildroot systemd-journald[561]: Time spent on flushing to /var/log/journal/fdd0189472c24ef8a81c5b63f2d53006 is 85.233ms for 653 entries.
Mar 06 15:31:59 buildroot systemd-journald[561]: System Journal (/var/log/journal/fdd0189472c24ef8a81c5b63f2d53006) is 96.0M, max 346.3M, 250.3M free.
Mar 06 15:31:59 buildroot systemd[1]: Finished udev Coldplug all Devices.
Mar 06 15:31:59 buildroot systemd[1]: Finished Flush Journal to Persistent Storage.
Mar 06 15:31:59 buildroot systemd-udevd[583]: Using default interface naming scheme 'v245'.
Mar 06 15:31:59 buildroot systemd-udevd[583]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Mar 06 15:31:59 buildroot systemd-udevd[580]: Using default interface naming scheme 'v245'.
Mar 06 15:31:59 buildroot systemd-udevd[580]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Mar 06 15:31:59 buildroot systemd-udevd[578]: Using default interface naming scheme 'v245'.
Mar 06 15:31:59 buildroot systemd-udevd[578]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Mar 06 15:31:59 buildroot systemd-udevd[579]: Using default interface naming scheme 'v245'.
Mar 06 15:31:59 buildroot systemd-udevd[579]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Mar 06 15:31:59 buildroot systemd[1]: Starting Create Volatile Files and Directories...
Mar 06 15:31:59 buildroot systemd[1]: Finished Create Volatile Files and Directories.
Mar 06 15:31:59 buildroot kernel: plusb 1-5:1.0 usb0: register 'plusb' at usb-0000:00:15.0-5, Prolific PL-2301/PL-2302/PL-25A1/PL-27A1, c6:21:51:0a:70:b1
Mar 06 15:31:59 buildroot systemd[1]: Starting Create basic system information...
Mar 06 15:31:59 buildroot create_boardconfig.sh[599]: Runtime directory is /run/Some
Mar 06 15:31:59 buildroot create_boardconfig.sh[599]: Write periphconfig.ini
Mar 06 15:31:59 buildroot systemd[1]: Starting Network Time Synchronization...
Mar 06 15:31:59 buildroot create_boardconfig.sh[599]: Write networkd config
Mar 06 15:31:59 buildroot create_boardconfig.sh[599]: Read boardconfig from T-CPU
Mar 06 15:32:00 buildroot kernel: sdhci-pci 0000:00:1b.0: SDHCI controller found [8086:5aca] (rev d)
Mar 06 15:32:00 buildroot kernel: usbcore: registered new interface driver plusb
Mar 06 15:32:00 buildroot systemd[1]: Found device /dev/ttyS0.
Mar 06 15:32:00 buildroot systemd[1]: Started Network Time Synchronization.
Mar 06 15:32:00 buildroot systemd-udevd[578]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Mar 06 15:32:00 buildroot systemd[1]: Reached target System Initialization.
Mar 06 15:32:00 buildroot systemd-udevd[583]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Mar 06 15:32:00 buildroot kernel: plusb 1-5:1.0 enp0s21f0u5: renamed from usb0
Mar 06 15:32:00 buildroot systemd[1]: Started Wait Until Device Time Synchronized.
Mar 06 15:32:00 buildroot systemd[1]: Started Daily Cleanup of Temporary Directories.
Mar 06 15:32:00 buildroot systemd[1]: Reached target Paths.
Mar 06 15:32:00 buildroot systemd[1]: Reached target System Time Set.
Mar 06 15:32:00 buildroot systemd[1]: Reached target Timers.
Mar 06 15:32:00 buildroot systemd[1]: Listening on OpenBSD Secure Shell server socket.
Mar 06 15:32:00 buildroot systemd[1]: Listening on Journal Varlink Socket for Namespace acpu.
Mar 06 15:32:00 buildroot systemd[1]: Listening on Journal Socket for Namespace acpu.
Mar 06 15:32:00 buildroot systemd[1]: Listening on Component Tftp Server Activation Socket.
Mar 06 15:32:00 buildroot systemd[1]: Reached target Sockets.
Mar 06 15:32:00 buildroot systemd[1]: Reached target Basic System.
Mar 06 15:32:00 buildroot systemd[1]: Started Serial Getty on ttyS0.
Mar 06 15:32:00 buildroot systemd[1]: Reached target Login Prompts.
Mar 06 15:32:00 buildroot systemd[1]: Condition check resulted in SSH Key Generation being skipped.
Mar 06 15:32:01 buildroot systemd[1]: create-config.service: start operation timed out. Terminating.
Mar 06 15:32:01 buildroot create_boardconfig.sh[599]: Terminated
Mar 06 15:32:01 buildroot create_boardconfig.sh[633]: Read baseboard idchip from T-CPU
Mar 06 15:32:02 buildroot systemd[1]: create-config.service: State 'stop-sigterm' timed out. Killing.
Mar 06 15:32:02 buildroot systemd[1]: create-config.service: Killing process 599 (create_boardcon) with signal SIGKILL.
Mar 06 15:32:02 buildroot systemd[1]: create-config.service: Killing process 633 (create_boardcon) with signal SIGKILL.
Mar 06 15:32:02 buildroot systemd[1]: create-config.service: Killing process 634 (read_tcpu) with signal SIGKILL.
Mar 06 15:32:02 buildroot systemd[1]: create-config.service: Main process exited, code=killed, status=9/KILL
Mar 06 15:32:02 buildroot systemd[1]: create-config.service: Failed with result 'timeout'.
Mar 06 15:32:02 buildroot systemd[1]: Failed to start Create basic system information.
Mar 06 15:32:02 buildroot systemd[1]: Dependency failed for Some Realtime Interface.
Mar 06 15:32:02 buildroot systemd[1]: Dependency failed for Some Realtime Gateway.
Mar 06 15:32:02 buildroot systemd[1]: Dependency failed for Some Realtime Service.
Mar 06 15:32:02 buildroot systemd[1]: acpu.service: Job acpu.service/start failed with result 'dependency'.
Mar 06 15:32:02 buildroot systemd[1]: rtgate.service: Job rtgate.service/start failed with result 'dependency'.
Mar 06 15:32:02 buildroot systemd[1]: rtnet.service: Job rtnet.service/start failed with result 'dependency'.
Mar 06 15:32:02 buildroot systemd[1]: Reached target Network (Pre).
Mar 06 15:32:02 buildroot systemd[1]: Starting Network Service...
Mar 06 15:32:02 buildroot systemd-networkd[635]: Enumeration completed
Mar 06 15:32:02 buildroot systemd[1]: Started Network Service.
Mar 06 15:32:02 buildroot systemd[1]: Reached target Network.
Mar 06 15:32:02 buildroot systemd[1]: Started Target Communication Framework Agent.
Mar 06 15:32:02 buildroot systemd[1]: Reached target Multi-User System.
Mar 06 15:32:02 buildroot systemd-networkd[635]: enp0s21f0u5: Interface name change detected, enp0s21f0u5 has been renamed to usb0.
Mar 06 15:32:02 buildroot systemd-networkd[635]: usb0: Interface name change detected, usb0 has been renamed to enp0s21f0u5.
Mar 06 15:32:02 buildroot systemd[1]: create-config.service: Scheduled restart job, restart counter is at 1.
Mar 06 15:32:02 buildroot systemd[1]: Stopped Create basic system information.
Mar 06 15:32:02 buildroot systemd[1]: Starting Create basic system information...
Mar 06 15:32:02 buildroot create_boardconfig.sh[641]: Runtime directory is /run/Some
Mar 06 15:32:02 buildroot create_boardconfig.sh[641]: Write periphconfig.ini
Mar 06 15:32:02 buildroot create_boardconfig.sh[641]: Write networkd config
Mar 06 15:32:02 buildroot create_boardconfig.sh[641]: Read boardconfig from T-CPU
Mar 06 15:32:03 buildroot systemd[1]: create-config.service: start operation timed out. Terminating.
Mar 06 15:32:03 buildroot create_boardconfig.sh[641]: Terminated
Mar 06 15:32:03 buildroot create_boardconfig.sh[669]: Read baseboard idchip from T-CPU
Mar 06 15:32:04 buildroot kernel: igb 0000:01:00.0 enp1s0: igb: enp1s0 NIC Link is Up 100 Mbps Half Duplex, Flow Control: None
Mar 06 15:32:04 buildroot kernel: igb 0000:01:00.0: EEE Disabled: unsupported at half duplex. Re-enable using ethtool when at full duplex.
Mar 06 15:32:04 buildroot systemd[1]: create-config.service: State 'stop-sigterm' timed out. Killing.
Mar 06 15:32:04 buildroot systemd[1]: create-config.service: Killing process 641 (create_boardcon) with signal SIGKILL.
Mar 06 15:32:04 buildroot systemd[1]: create-config.service: Killing process 669 (create_boardcon) with signal SIGKILL.
Mar 06 15:32:04 buildroot systemd[1]: create-config.service: Killing process 670 (read_tcpu) with signal SIGKILL.
Mar 06 15:32:04 buildroot systemd[1]: create-config.service: Main process exited, code=killed, status=9/KILL
Mar 06 15:32:04 buildroot systemd[1]: create-config.service: Failed with result 'timeout'.
Mar 06 15:32:04 buildroot systemd[1]: Failed to start Create basic system information.
Mar 06 15:32:05 buildroot systemd[1]: create-config.service: Scheduled restart job, restart counter is at 2.
Mar 06 15:32:05 buildroot systemd[1]: Stopped Create basic system information.
Mar 06 15:32:05 buildroot systemd[1]: create-config.service: Start request repeated too quickly.
Mar 06 15:32:05 buildroot systemd[1]: create-config.service: Failed with result 'timeout'.
Mar 06 15:32:05 buildroot systemd[1]: Failed to start Create basic system information.
Mar 06 15:32:05 buildroot kernel: igb 0000:03:00.0 enp3s0: igb: enp3s0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX/TX
Mar 06 15:32:05 buildroot kernel: igb 0000:04:00.0 enp4s0: igb: enp4s0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX/TX
Mar 06 15:32:07 buildroot systemd-networkd[635]: enp4s0: Link UP
Mar 06 15:32:07 buildroot systemd-networkd[635]: enp3s0: Link UP
Mar 06 15:32:07 buildroot systemd-networkd[635]: enp2s0: Link UP
Mar 06 15:32:07 buildroot systemd-networkd[635]: enp1s0: Link UP
Mar 06 15:32:07 buildroot systemd-networkd[635]: enp0s21f0u5: Link UP
Mar 06 15:32:07 buildroot systemd-networkd[635]: enp0s21f0u5: Gained carrier
Mar 06 15:32:07 buildroot systemd-networkd[635]: enp1s0: Gained carrier
Mar 06 15:32:07 buildroot systemd-networkd[635]: enp3s0: Gained carrier
Mar 06 15:32:07 buildroot systemd-networkd[635]: enp4s0: Gained carrier
Mar 06 15:32:07 buildroot systemd-timesyncd[614]: Network configuration changed, trying to establish connection.
Mar 06 15:32:07 buildroot systemd-timesyncd[614]: Network configuration changed, trying to establish connection.
Mar 06 15:32:07 buildroot systemd-timesyncd[614]: Network configuration changed, trying to establish connection.
Mar 06 15:32:07 buildroot systemd-timesyncd[614]: Network configuration changed, trying to establish connection.
Mar 06 15:32:07 buildroot systemd-timesyncd[614]: Network configuration changed, trying to establish connection.
Mar 06 15:32:07 buildroot systemd-timesyncd[614]: Network configuration changed, trying to establish connection.
Mar 06 15:32:18 buildroot login[630]: root login on 'ttyS0'
Mar 06 15:32:48 buildroot systemd-timesyncd[614]: Timed out waiting for reply from 0.0.0.6:123 (0.0.0.6).
Mar 06 15:33:29 buildroot systemd[1]: Created slice system-sshd.slice.
Mar 06 15:33:29 buildroot systemd[1]: Condition check resulted in Journal Audit Socket being skipped.
Mar 06 15:33:29 buildroot systemd[1]: Condition check resulted in Entropy Harvesting Daemon being skipped.
Mar 06 15:33:29 buildroot systemd[1]: Starting Create basic system information...
Mar 06 15:33:29 buildroot systemd[1]: Condition check resulted in Create list of static device nodes for the current kernel being skipped.
Mar 06 15:33:29 buildroot systemd[1]: Condition check resulted in Commit a transient machine-id on disk being skipped.
Mar 06 15:33:29 buildroot systemd[1]: Condition check resulted in Load Kernel Modules being skipped.
Mar 06 15:33:29 buildroot systemd[1]: Condition check resulted in Platform Persistent Storage Archival being skipped.
Mar 06 15:33:29 buildroot systemd[1]: Condition check resulted in Update is Completed being skipped.
Mar 06 15:33:29 buildroot systemd[1]: Started OpenBSD Secure Shell server per-connection daemon (10.99.10.1:41520).
Mar 06 15:33:29 buildroot create_boardconfig.sh[695]: Runtime directory is /run/Some
Mar 06 15:33:29 buildroot create_boardconfig.sh[695]: Write periphconfig.ini
Mar 06 15:33:30 buildroot create_boardconfig.sh[695]: Write networkd config
Mar 06 15:33:30 buildroot create_boardconfig.sh[695]: Read boardconfig from T-CPU
Mar 06 15:33:30 buildroot sshd[696]: Accepted publickey for root from 10.99.10.1 port 41520 ssh2: ED25519 SHA256:xLLfWUDp09bYPzYOx2H277FcrAlvRYCKnXr3zw7nOfA
Mar 06 15:33:30 buildroot systemd-timesyncd[614]: Timed out waiting for reply from 0.0.0.6:123 (0.0.0.6).
Mar 06 15:33:31 buildroot systemd[1]: create-config.service: start operation timed out. Terminating.
Mar 06 15:33:31 buildroot create_boardconfig.sh[695]: Terminated
Mar 06 15:33:31 buildroot create_boardconfig.sh[737]: Read baseboard idchip from T-CPU
Mar 06 15:33:32 buildroot systemd[1]: create-config.service: State 'stop-sigterm' timed out. Killing.
Mar 06 15:33:32 buildroot systemd[1]: create-config.service: Killing process 695 (create_boardcon) with signal SIGKILL.
Mar 06 15:33:32 buildroot systemd[1]: create-config.service: Killing process 737 (create_boardcon) with signal SIGKILL.
Mar 06 15:33:32 buildroot systemd[1]: create-config.service: Killing process 738 (read_tcpu) with signal SIGKILL.
Mar 06 15:33:32 buildroot systemd[1]: create-config.service: Main process exited, code=killed, status=9/KILL
Mar 06 15:33:32 buildroot systemd[1]: create-config.service: Failed with result 'timeout'.
Mar 06 15:33:32 buildroot systemd[1]: Failed to start Create basic system information.
Mar 06 15:33:32 buildroot systemd[1]: Dependency failed for Some Realtime Interface.
Mar 06 15:33:32 buildroot systemd[1]: Dependency failed for Some Realtime Gateway.
Mar 06 15:33:32 buildroot systemd[1]: rtgate.service: Job rtgate.service/start failed with result 'dependency'.
Mar 06 15:33:32 buildroot systemd[1]: rtnet.service: Job rtnet.service/start failed with result 'dependency'.
Mar 06 15:33:32 buildroot systemd[1]: create-config.service: Scheduled restart job, restart counter is at 1.
Mar 06 15:33:32 buildroot systemd[1]: Stopped Create basic system information.
Mar 06 15:33:32 buildroot systemd[1]: Starting Create basic system information...
Mar 06 15:33:32 buildroot create_boardconfig.sh[739]: Runtime directory is /run/Some
Mar 06 15:33:32 buildroot create_boardconfig.sh[739]: Write periphconfig.ini
Mar 06 15:33:32 buildroot create_boardconfig.sh[739]: Write networkd config
Mar 06 15:33:32 buildroot create_boardconfig.sh[739]: Read boardconfig from T-CPU
Mar 06 15:33:33 buildroot systemd[1]: create-config.service: start operation timed out. Terminating.
Mar 06 15:33:33 buildroot create_boardconfig.sh[739]: Terminated
Mar 06 15:33:33 buildroot create_boardconfig.sh[767]: Read baseboard idchip from T-CPU
Mar 06 15:33:34 buildroot systemd[1]: create-config.service: State 'stop-sigterm' timed out. Killing.
Mar 06 15:33:34 buildroot systemd[1]: create-config.service: Killing process 739 (create_boardcon) with signal SIGKILL.
Mar 06 15:33:34 buildroot systemd[1]: create-config.service: Killing process 767 (create_boardcon) with signal SIGKILL.
Mar 06 15:33:34 buildroot systemd[1]: create-config.service: Killing process 768 (read_tcpu) with signal SIGKILL.
Mar 06 15:33:34 buildroot systemd[1]: create-config.service: Main process exited, code=killed, status=9/KILL
Mar 06 15:33:34 buildroot systemd[1]: create-config.service: Failed with result 'timeout'.
Mar 06 15:33:34 buildroot systemd[1]: Failed to start Create basic system information.
Mar 06 15:33:35 buildroot systemd[1]: create-config.service: Scheduled restart job, restart counter is at 2.
Mar 06 15:33:35 buildroot systemd[1]: Stopped Create basic system information.
Mar 06 15:33:35 buildroot systemd[1]: create-config.service: Start request repeated too quickly.
Mar 06 15:33:35 buildroot systemd[1]: create-config.service: Failed with result 'timeout'.
Mar 06 15:33:35 buildroot systemd[1]: Failed to start Create basic system information.
Mar 06 15:34:43 buildroot sshd[696]: syslogin_perform_logout: logout() returned an error
Mar 06 15:34:43 buildroot sshd[696]: Received disconnect from 10.99.10.1 port 41520:11: disconnected by user
Mar 06 15:34:43 buildroot systemd[1]: sshd@0-10.99.37.44:22-10.99.10.1:41520.service: Succeeded.
Mar 06 15:34:43 buildroot sshd[696]: Disconnected from user root 10.99.10.1 port 41520
Mar 06 15:34:45 buildroot systemd-timesyncd[614]: Timed out waiting for reply from 0.0.0.6:123 (0.0.0.6).
Mar 06 15:34:45 buildroot systemd[1]: Condition check resulted in Journal Audit Socket being skipped.
Mar 06 15:34:45 buildroot systemd[1]: Condition check resulted in Entropy Harvesting Daemon being skipped.
Mar 06 15:34:45 buildroot systemd[1]: Starting Create basic system information...
Mar 06 15:34:45 buildroot systemd[1]: Condition check resulted in Create list of static device nodes for the current kernel being skipped.
Mar 06 15:34:45 buildroot systemd[1]: Condition check resulted in Commit a transient machine-id on disk being skipped.
Mar 06 15:34:45 buildroot systemd[1]: Condition check resulted in Load Kernel Modules being skipped.
Mar 06 15:34:45 buildroot systemd[1]: Condition check resulted in Platform Persistent Storage Archival being skipped.
Mar 06 15:34:45 buildroot systemd[1]: Condition check resulted in Update is Completed being skipped.
Mar 06 15:34:45 buildroot systemd[1]: Started OpenBSD Secure Shell server per-connection daemon (10.99.10.1:41522).
Mar 06 15:34:45 buildroot create_boardconfig.sh[779]: Runtime directory is /run/Some
Mar 06 15:34:45 buildroot create_boardconfig.sh[779]: Write periphconfig.ini
Mar 06 15:34:45 buildroot create_boardconfig.sh[779]: Write networkd config
Mar 06 15:34:45 buildroot create_boardconfig.sh[779]: Read boardconfig from T-CPU
Mar 06 15:34:45 buildroot sshd[780]: Accepted publickey for root from 10.99.10.1 port 41522 ssh2: ED25519 SHA256:xLLfWUDp09bYPzYOx2H277FcrAlvRYCKnXr3zw7nOfA
Mar 06 15:34:46 buildroot systemd[1]: create-config.service: start operation timed out. Terminating.
Mar 06 15:34:46 buildroot create_boardconfig.sh[779]: Terminated
Mar 06 15:34:46 buildroot create_boardconfig.sh[821]: Read baseboard idchip from T-CPU
Mar 06 15:34:48 buildroot systemd[1]: create-config.service: State 'stop-sigterm' timed out. Killing.
Mar 06 15:34:48 buildroot systemd[1]: create-config.service: Killing process 779 (create_boardcon) with signal SIGKILL.
Mar 06 15:34:48 buildroot systemd[1]: create-config.service: Killing process 821 (create_boardcon) with signal SIGKILL.
Mar 06 15:34:48 buildroot systemd[1]: create-config.service: Killing process 822 (read_tcpu) with signal SIGKILL.
Mar 06 15:34:48 buildroot systemd[1]: create-config.service: Main process exited, code=killed, status=9/KILL
Mar 06 15:34:48 buildroot systemd[1]: create-config.service: Failed with result 'timeout'.
Mar 06 15:34:48 buildroot systemd[1]: Failed to start Create basic system information.
Mar 06 15:34:48 buildroot systemd[1]: Dependency failed for Some Realtime Interface.
Mar 06 15:34:48 buildroot systemd[1]: Dependency failed for Some Realtime Gateway.
Mar 06 15:34:48 buildroot systemd[1]: rtgate.service: Job rtgate.service/start failed with result 'dependency'.
Mar 06 15:34:48 buildroot systemd[1]: rtnet.service: Job rtnet.service/start failed with result 'dependency'.
Mar 06 15:34:48 buildroot systemd[1]: create-config.service: Scheduled restart job, restart counter is at 1.
Mar 06 15:34:48 buildroot systemd[1]: Stopped Create basic system information.
Mar 06 15:34:48 buildroot systemd[1]: Starting Create basic system information...
Mar 06 15:34:48 buildroot create_boardconfig.sh[823]: Runtime directory is /run/Some
Mar 06 15:34:48 buildroot create_boardconfig.sh[823]: Write periphconfig.ini
Mar 06 15:34:48 buildroot create_boardconfig.sh[823]: Write networkd config
Mar 06 15:34:48 buildroot create_boardconfig.sh[823]: Read boardconfig from T-CPU
Mar 06 15:34:49 buildroot systemd[1]: create-config.service: start operation timed out. Terminating.
Mar 06 15:34:49 buildroot create_boardconfig.sh[823]: Terminated
Mar 06 15:34:49 buildroot create_boardconfig.sh[851]: Read baseboard idchip from T-CPU
Mar 06 15:34:50 buildroot systemd[1]: create-config.service: State 'stop-sigterm' timed out. Killing.
Mar 06 15:34:50 buildroot systemd[1]: create-config.service: Killing process 823 (create_boardcon) with signal SIGKILL.
Mar 06 15:34:50 buildroot systemd[1]: create-config.service: Killing process 851 (create_boardcon) with signal SIGKILL.
Mar 06 15:34:50 buildroot systemd[1]: create-config.service: Killing process 852 (read_tcpu) with signal SIGKILL.
Mar 06 15:34:50 buildroot systemd[1]: create-config.service: Main process exited, code=killed, status=9/KILL
Mar 06 15:34:50 buildroot systemd[1]: create-config.service: Failed with result 'timeout'.
Mar 06 15:34:50 buildroot systemd[1]: Failed to start Create basic system information.
Mar 06 15:34:51 buildroot systemd[1]: create-config.service: Scheduled restart job, restart counter is at 2.
Mar 06 15:34:51 buildroot systemd[1]: Stopped Create basic system information.
Mar 06 15:34:51 buildroot systemd[1]: create-config.service: Start request repeated too quickly.
Mar 06 15:34:51 buildroot systemd[1]: create-config.service: Failed with result 'timeout'.
Mar 06 15:34:51 buildroot systemd[1]: Failed to start Create basic system information.
Mar 06 15:35:28 buildroot sshd[780]: syslogin_perform_logout: logout() returned an error
Mar 06 15:35:28 buildroot sshd[780]: Received disconnect from 10.99.10.1 port 41522:11: disconnected by user
Mar 06 15:35:28 buildroot systemd[1]: sshd@1-10.99.37.44:22-10.99.10.1:41522.service: Succeeded.
Mar 06 15:35:28 buildroot sshd[780]: Disconnected from user root 10.99.10.1 port 41522
Mar 06 15:35:46 buildroot systemd[1]: Condition check resulted in Journal Audit Socket being skipped.
Mar 06 15:35:46 buildroot systemd[1]: Condition check resulted in Entropy Harvesting Daemon being skipped.
Mar 06 15:35:46 buildroot systemd[1]: Starting Create basic system information...
Mar 06 15:35:46 buildroot systemd[1]: Condition check resulted in Create list of static device nodes for the current kernel being skipped.
Mar 06 15:35:46 buildroot systemd[1]: Condition check resulted in Commit a transient machine-id on disk being skipped.
Mar 06 15:35:46 buildroot systemd[1]: Condition check resulted in Load Kernel Modules being skipped.
Mar 06 15:35:46 buildroot systemd[1]: Condition check resulted in Platform Persistent Storage Archival being skipped.
Mar 06 15:35:46 buildroot systemd[1]: Condition check resulted in Update is Completed being skipped.
Mar 06 15:35:46 buildroot systemd[1]: Started OpenBSD Secure Shell server per-connection daemon (10.99.10.1:41526).
Mar 06 15:35:46 buildroot create_boardconfig.sh[859]: Runtime directory is /run/Some
Mar 06 15:35:46 buildroot create_boardconfig.sh[859]: Write periphconfig.ini
Mar 06 15:35:46 buildroot create_boardconfig.sh[859]: Write networkd config
```

**Comment by mbiebl** [comment] 2020-03-27 13:37
I think this is a duplicate of #15188 and I suspect the underlying issue is #15091

**Comment by nolange** [comment] 2020-03-27 14:26
I dont have plymouth, or graphical.target. And it goes away if I remove/fix the above services.

**Comment by mbiebl** [comment] 2020-03-28 00:08
> I dont have plymouth, or graphical.target. And it goes away if I remove/fix the above services.

plymouth being (re)started is just another symptom of the same underlying issue caused by https://github.com/systemd/systemd/pull/14086

**Comment by nolange** [comment] 2020-03-28 00:21
Yes, you are right. I answered before digging through the thread.
The current behavior is completely inconsistent at. Manually stop a service, try to remote debug with ssh/gdb and socket activation for ssh will mess with the state of your units.

Based on such external events your units might fail and stay dead or be retried.

Cant tell if it's an regression however, the service in question just sometimes fails. Means I just might not have realized it earlier

**Comment by poettering** [comment] 2020-08-28 15:39
I guess we can close this given that #16149 was merged.

**Closed as completed by poettering** 2020-08-28 15:39 UTC
