### ISSUE TITLE
IPv4 DHCP address preliminary expired

### ISSUE THREAD

**Issue by avakhit** [systemd/systemd#12676] opened 2019-05-27 17:07 UTC
systemd 242.19-1

arch Linux 5.0.10-arch1-1-ARCH

**Expected behaviour you didn't see**
 > IPv4 address received via DHCP should stay assigned to interface during lease renewal.

**Unexpected behaviour you saw**
 > On renewal process start address gets immediately removed from the interface. After renewal same address gets reassigned. IPv4 Communication breaks inbetween. Following log illustrates the problem:
```
Mai 27 18:39:35 xenhost systemd-networkd[21412]: DHCP CLIENT (0x8aa58d0c): REQUEST (renewing)
Mai 27 18:39:35 xenhost systemd-networkd[21412]: DHCP CLIENT (0x8aa58d0c): ACK
Mai 27 18:39:35 xenhost dbus-daemon[509]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.7425' (uid=193 pid>
Mai 27 18:39:35 xenhost systemd-networkd[21412]: DHCP CLIENT (0x8aa58d0c): lease expires in 59min 57s
Mai 27 18:39:35 xenhost systemd-networkd[21412]: DHCP CLIENT (0x8aa58d0c): T2 expires in 50min 34s
Mai 27 18:39:35 xenhost systemd-networkd[21412]: DHCP CLIENT (0x8aa58d0c): T1 expires in 28min 4s
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: DHCP lease lost
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing address 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: Setting transient hostname: 'n/a'
Mai 27 18:39:35 xenhost systemd-networkd[21412]: Sent message type=method_call sender=n/a destination=org.freedesktop.hostname1 path=/org/freedesktop/hostname1 interface=org.freedesktop.hostname1 m>
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: DHCPv4 address 192.168.33.5/24 via 192.168.33.2
Mai 27 18:39:35 xenhost systemd-networkd[21412]: Setting transient hostname: 'xenhost'
Mai 27 18:39:35 xenhost systemd-networkd[21412]: Sent message type=method_call sender=n/a destination=org.freedesktop.hostname1 path=/org/freedesktop/hostname1 interface=org.freedesktop.hostname1 m>
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing route: dst: 192.168.33.2/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing route: dst: n/a, src: n/a, gw: 192.168.33.2, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing address: 192.168.33.5/24 (valid for 32min 8s)
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing route: dst: 192.168.33.0/24, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing route: dst: 192.168.33.255/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing route: dst: 192.168.33.0/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Removing route: dst: 192.168.33.5/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Adding address: 192.168.33.5/24 (valid for 1h)
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Adding route: dst: 192.168.33.5/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Adding route: dst: 192.168.33.255/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Adding route: dst: 192.168.33.0/24, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Adding route: dst: 192.168.33.0/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: DHCP: No routes received from DHCP server: No data available
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Configuring route: dst: 192.168.33.2/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Configuring route: dst: n/a, src: n/a, gw: 192.168.33.2, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Updating route: dst: 192.168.33.2/32, src: n/a, gw: n/a, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: Updating route: dst: n/a, src: n/a, gw: 192.168.33.2, prefsrc: 192.168.33.5
Mai 27 18:39:35 xenhost systemd[1]: Starting Hostname Service...
Mai 27 18:39:36 xenhost dbus-daemon[509]: [system] Successfully activated service 'org.freedesktop.hostname1'
Mai 27 18:39:36 xenhost systemd[1]: Started Hostname Service.
Mai 27 18:39:36 xenhost systemd-networkd[21412]: Got message type=method_return sender=:1.7441 destination=:1.7425 path=n/a interface=n/a member=n/a cookie=3 reply_cookie=57 signature=n/a error-nam>
Mai 27 18:39:36 xenhost systemd-networkd[21412]: Got message type=method_return sender=:1.7441 destination=:1.7425 path=n/a interface=n/a member=n/a cookie=4 reply_cookie=58 signature=n/a error-nam>
Mai 27 18:39:36 xenhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res>
Mai 27 18:39:36 xenhost kernel: audit: type=1130 audit(1558975176.469:5311): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hos>
Mai 27 18:40:06 xenhost systemd[1]: systemd-hostnamed.service: Succeeded.
Mai 27 18:40:06 xenhost audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=>
```
**Steps to reproduce the problem**
No idea if it's matters, but I'm using a bonding device. There is an additional static IPv4 address assigned and IPv6 is active as well.
```
[root@xenhost ~]# ip a s dev lanbond
7: lanbond: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 82:28:70:ae:1a:60 brd ff:ff:ff:ff:ff:ff
    inet 192.168.33.105/32 scope global lanbond
       valid_lft forever preferred_lft forever
    inet 192.168.33.5/24 brd 192.168.33.255 scope global dynamic lanbond
       valid_lft 2325sec preferred_lft 2325sec
    inet6 2001:16b8:2233:f6f8:8028:70ff:feae:1a60/64 scope global dynamic mngtmpaddr noprefixroute
       valid_lft 3244sec preferred_lft 2902sec
    inet6 fe80::8028:70ff:feae:1a60/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by yuwata** [comment] 2019-05-27 21:58
Fix is waiting in #12573.

**Comment by avakhit** [comment] 2019-05-28 09:51
Thank you for incredible fast reaction. I've not tested your potential fix yet, but I'd like to point to an aspect that is not covered in the thread/issues you have linked above. Take a look on following part of the log:

Mai 27 18:39:35 xenhost systemd-networkd[21412]: DHCP CLIENT (0x8aa58d0c): lease expires in 59min 57s
Mai 27 18:39:35 xenhost systemd-networkd[21412]: DHCP CLIENT (0x8aa58d0c): T2 expires in 50min 34s
Mai 27 18:39:35 xenhost systemd-networkd[21412]: DHCP CLIENT (0x8aa58d0c): T1 expires in 28min 4s
Mai 27 18:39:35 xenhost systemd-networkd[21412]: lanbond: DHCP lease lost

All timers shows a lot of time until the expiration. Nevertheless it considers the lease as lost. Why? For me it appears to be a core of the problem. Am I wrong?
What do you mean, yuwata, about it?

**Comment by ssahani** [comment] 2019-05-28 12:16
>On renewal process start address gets immediately removed from the interface. After renewal same address gets reassigned. IPv4 Communication breaks inbetween. Following log illustrates the problem:

What is the guarantee that you will get the same address ? What if your client not able to connect to the DHCP server after lease expired. Are you going to use the expired addresses ? 

To retain addresses use ```CriticalConnection=```.

**Comment by avakhit** [comment] 2019-05-28 13:35
@ssahani: you are totaly right in case of lease expiration. But in my case lease should not expire yet. T1 timer shows 28min until expiration! It's clear that renewal process starts at ca. 50% of expiration time to have enough time for renewal if first try fails. But the start of renewal process absolutely doesn't meat that the address isn't valid anymore, there is no reason to remove it.

**Comment by ssahani** [comment] 2019-05-28 14:34
The client may initiate lease renewal prior to T1 timer expiration if it desires.

**Comment by avakhit** [comment] 2019-05-28 14:47
@ssahani: agree, but if client desires to renew before expiration there is no reason to immediately remove still valid old address leaving the link unconfigured, isn't it?

**Comment by ssahani** [comment] 2019-05-28 14:57
yeah you have a valid case. I agree. We should verify until t2 expires we should not remove the address.  So we should do something like RFC says

If the client receives no reply from the server, it will remain in the RENEWING state, and will regularly retransmit the unicast DHCPREQUEST to the server. During this period of time, the client is still operating normally, from the perspective of its user. If no response from the server is received, eventually the rebinding timer (T2) expires. This will cause the client to transition to the REBINDING state. Recall that by default, the T2 timer is set to 87.5% (7/8ths) of the length of the lease.

**Comment by ssahani** [comment] 2019-05-28 15:01
But This does not change the behaviour . This can happen after t2 expired too. What you think ?

**Comment by avakhit** [comment] 2019-05-28 15:11
@ssahani: IMHO you are correct: if lease expires and renew/rebind retries failing, address gets lost and the link becomes "unusable". But first after the expiration. Currenly I've perfectly responsive DHCP server doing the job properly and the client continiously (twice per; hour because DHCP lease time is set to 1 hout) loosing connections…
Thank you for you patience and support!

**Comment by yuwata** [comment] 2019-05-28 15:14
I may not catch the discussion, but the PR now
- just drop address and routes when no new lease is obtained. This behavior is not changed.
- when new lease is obtained, then assign new address and then remove old one. Previously, we first drop the old one, and assign new one, even if new one is the same as the old one.

I think T1 or T2 are not relevant here, at least to @avakhit's original issue.

**Comment by yuwata** [comment] 2019-05-28 15:17
Note that in the PR, `networkd` checks whether the new address is equivalent to the old one or not. So, when we obtain the same address, then the foregoing removing process does nothing.

**Comment by avakhit** [comment] 2019-05-28 15:24
sounds reasonable. Now I've to wait at least until you changes will be merged in order to build arch package by myself.

**Comment by ssahani** [comment] 2019-05-28 15:31
@yuwata 
> I think T1 or T2 are not relevant here, at least to @avakhit's original issue.

No they play a vital role here. We need to maintain the RFC standard.

>Note that in the PR, networkd checks whether the new address is equivalent to the old one or not. So, when we obtain the same address, then the foregoing removing process does nothing.

That is in a good case. What if it does not get a address at all. That is precise my point .

@avakhit 
>sounds reasonable. Now I've to wait at least until you changes will be merged in order to build arch package by myself.

You can use ```CriticalConnection``` or configure  mac to ip at DHCP server to be sure your IP is not acquire by somebody else.

**Comment by yuwata** [comment] 2019-05-28 15:36
> @yuwata
> 
> > I think T1 or T2 are not relevant here, at least to @avakhit's original issue.
> 
> No they play a vital role here. We need to maintain the RFC standard.

Which part of RFC is relevant to this issue or discussion? Could you give us a reference?

> > Note that in the PR, networkd checks whether the new address is equivalent to the old one or not. So, when we obtain the same address, then the foregoing removing process does nothing.
> 
> That is in a good case. What if it does not get a address at all. That is precise my point .

Yeah, as I already wrote, in that case, the already assigned address and routes are simply dropped.

**Comment by avakhit** [comment] 2019-05-28 15:50
@ssahani fixed IP/MAC mapping is already configured in DHCP server, so I always would get the same IP for this host. My problem is that the host means that it is loosing ip. I'll try to work around it with CriticalConnection until I get the fix.

**Comment by ssahani** [comment] 2019-05-28 16:16
Could you please see http://www.tcpipguide.com/free/t_DHCPLeaseRenewalandRebindingProcesses-2.htm
https://community.cisco.com/t5/collaboration-voice-and-video/what-is-the-significance-of-quot-renewal-t1-time-sec-quot-and/ta-p/3132484

https://www.netmanias.com/en/post/techdocs/5999/dhcp-network-protocol/understanding-the-detailed-operations-of-dhcp

https://www.juniper.net/documentation/en_US/junos/topics/topic-map/dhcp-lease-times.html

>Yeah, as I already wrote, in that case, the already assigned address and routes are simply dropped.

When and how ? It's not just about deleting but how the behaviour that does matter.

**Comment by ssahani** [comment] 2019-05-28 16:17
> @ssahani fixed IP/MAC mapping is already configured in DHCP server, so I always would get the same IP for this host. My problem is that the host means that it is loosing ip. I'll try to work around it with CriticalConnection until I get the fix.

Ok But what kind of fix you expecting ?

**Comment by avakhit** [comment] 2019-05-28 16:25
@yuwata mentioned: 
> when new lease is obtained, then assign new address and then remove old one. Previously, we first drop the old one, and assign new one, even if new one is the same as the old one
It sounds like a fix addressing my issue. under "fix" I mentioned this change

**Comment by ssahani** [comment] 2019-05-28 16:27
I am talking about the bad case. If you don't get a lease at all then ? That will works fine if network is OK and we really can't guarantee anything with the network.

**Comment by avakhit** [comment] 2019-05-28 16:29
I don’t expect any change in this case

--
Mit freundlichen Grüßen,
Andrey Vakhitov
 
E-Mail:  andrey@vakhitov.net            Stuttgart, Germany

**Comment by ssahani** [comment] 2019-05-29 01:46
@yuwata could you please reopen this issue. I don't understand why this is closed and merged?

**Comment by yuwata** [comment] 2019-05-29 02:29
@ssahani Thank you for the references. I guess 'the bad case' you mean is e.g. [Fig 265 in a reference](http://www.tcpipguide.com/free/t_DHCPLeaseRenewalandRebindingProcesses-2.htm).

I think the fix #12685 and the original issue here is not related to such situation. The issue here is 'good case', that is, server is alive and provide addresses.

I am not sure now but if there exists an issue in 'bad case', then it is another issue, and not relevant to this. And, regardless the PR, we need to fix such a situation. But, in another later PR.

**Comment by yuwata** [comment] 2019-05-29 02:32
So, I suggest to split the topic here.
1. original issue reported by @avakhit in 'good case'.
2. potential issue in 'bad case'.

And this thread is for topic 1. @ssahani WDYT?

**Comment by ssahani** [comment] 2019-05-29 03:01
>I think the fix #12685 and the original issue here is not related to such situation. The issue here is 'good case', that is, server is alive and provide addresses.

hmm how can we consider that server is always available ?

>I am not sure now but if there exists an issue in 'bad case', then it is another issue, and not relevant to this. And, regardless the PR, we need to fix such a situation. But, in another later PR.

 Now a bug is introduced that leads to one IP could be offered to two machines . Situation is very narrow but it's still there and will cause disruption in the network .

**Comment by yuwata** [comment] 2019-05-29 03:17
> hmm how can we consider that server is always available ?

Not sure, but maybe `sd_dhcp_client_get_lease()` succeeds or not? But anyway, it is a 'bad case'...

> Now a bug is introduced that leads to one IP could be offered to two machines.

From where you found so? I just found that an address is removed and then a new one is assigned.

**Comment by ssahani** [comment] 2019-05-29 03:34
>Not sure, but maybe sd_dhcp_client_get_lease() succeeds or not? But anyway, it is a 'bad case'
 
 Bad case is when the client fails to contact to the server that is failing to renew the address and lease expired.

>From where you found so? I just found that an address is removed and then the same address is re-assigned.

Let me explain this . When the client fails to communicate with the server and lease expired it now keeping the IP until there is a response from the server. But server point of view since the lease expired  it does not know that client is not able to communicate. It will assume lease is expired and put that in to the free pool of addresses. When another client will request it will assign that to other client. How ever if MAC to IP mapping is not there DHCP server is free to do so.

**Comment by avakhit** [comment] 2019-05-29 06:23
@yuwata I can follow you argumentation and agree with it
@ssahani The issue I described happened in the "good case". I expect uninterrupted network connectivity solong communication between DHCP client and DHCP server stays intact.
I agree with you, @ssahani , that in case of disturbed communication and unability to renew DHCP lease things become more complicated and leased address must be removed after the expiration but I'm not familiar enougth with DHCP to participate in detailed discussion about exact moment of lease expiration. IHMO a successfully renewed address must stay available on the interface exactly for the lease time (in my case 1 hour) after renewal even if any subsequent communication between DHCP client and server is broken. But again, it's just an opinion without RFC ref.

**Comment by ssahani** [comment] 2019-05-29 17:13
@avakhit when you addressing a issue we need to look at the corner cases. I dont understand without a review why @yuwata merged it and the issue is still under discussion. I dont ack for that patch and that need to be revered for sure without a review.

**Comment by yuwata** [comment] 2019-05-29 23:27
Hmm? I moved the patch to another PR #12685, and is not merged yet.

**Comment by ssahani** [comment] 2019-05-30 05:38
ohh I am sorry. I was under the impression that you merged it.

**Closed as completed** 2019-06-11 07:52 UTC
Labels: bug 🐛, network, dhcp
