### ISSUE TITLE
udev fails to trigger loading of modules

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#11314] opened 2019-01-02 20:11 UTC
**systemd version the issue has been seen with**

v240

**Used distribution**
 
Debian sid

Since the update of systemd from v239 to v240, we had several downstream bug reports, where udev fails to trigger loading of kernel modules.
I think the following bug reports are basically all about the same underlying issue:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917185
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917247
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917607

So far, all reports are either from users using udev with sysvinit or with udev in the initramfs (which doesn't use systemd in Debian). I wonder if there is a race condition in udev which is more likely to trigger with sysvinit or in the initramfs.
I wasn't able to reproduce the issue myself so far.

The udev SysV init script can be found at 
https://salsa.debian.org/systemd-team/systemd/blob/master/debian/udev.init
The initramfs hooks to start udevd are at
https://salsa.debian.org/systemd-team/systemd/blob/master/debian/extra/initramfs-tools/scripts/init-top/udev
https://salsa.debian.org/systemd-team/systemd/blob/master/debian/extra/initramfs-tools/scripts/init-bottom/udev

Any hints on how to further debug this would be greatly appreciated.

**Comment by yuwata** [comment] 2019-01-02 20:46
Does PR #11270 fix these issue?

**Comment by yuwata** [comment] 2019-01-02 20:48
From https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917185
> I've just updated from 239-15 to 240-2; but, unfortunately, none of the problems were solved.

Hmm... The reporter rebuild initramfs?

**Comment by yuwata** [comment] 2019-01-02 21:05
Are there any chance to start `udevd` with debug logging?

**Comment by yuwata** [comment] 2019-01-02 21:35
> @yuwata does https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917247#45 help?

Unfortunately, no... I guess the reporter just paste only lines which contain 'systemd-udevd'. Currently, udev workers do not append 'systemd-udevd' at the beginning of the journal log. So, the reporter log does not contain any udev worker's log. Relevant fix is waiting in #11244.

**Comment by gregoa** [comment] 2019-01-03 00:12
I tried again, new logs attached to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917247#74

**Comment by yuwata** [comment] 2019-01-03 00:35
Ah, @mbiebl Debian or Ubuntu do not apply all patches in #11244 but only one commit which fixes segafault. So, still bind/unbind actions are dropped. I guess that causes so many issues, e.g. #11277 and #11299.

Please try to apply all patches, at least, b261494128e60dd3168e0ea961606ec4f39c5739.

**Comment by mbiebl** [comment] 2019-01-03 00:44
@gregoa can you try with that patch applied? I can provide deb packages if it's too much hassle for you.

@yuwata regarding this particular patch, I wasn't certain whether it's safe to pull, especially since that PR hasn't been merged yet. With all the back and forth regarding that bind/unbind problem, it wasn't immediately obvious if this revert is the right thing to do or not

**Comment by gregoa** [comment] 2019-01-03 00:46
@mbiebl sure, I'll give it a try (tomorrow).

**Comment by yuwata** [comment] 2019-01-03 02:38
@mbiebl My previous comment does not intend to backport the patch right now, sorry. Yeah, let's wait reviews.

**Comment by yuwata** [comment] 2019-01-03 15:32
#11244 was merged. Let's close this, at least tentatively. If problem still exists, please reopen this.

**Comment by gregoa** [comment] 2019-01-03 15:47
Adding b261494 on top of debian's 240-2 doesn't help, still the same failures. Logs at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917247#79

**Comment by yuwata** [comment] 2019-01-03 16:32
@gregoa Thank you for the logs.
The module list of v240 in your first [post](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917247#5) does not contain 'evdev', but, the logs in the post#79, I found the following:
```
[   27.329014] [1106]: Inserted module 'evdev'
[   27.359598] [1105]: Module 'evdev' is already loaded
```
So, at least now evdev is correctly loaded?

**Comment by keszybz** [comment] 2019-01-03 16:37
Hmm, there were also my changes in ebcc52fad68daf4bb3198685c7ab730813606fff and related commits. Maybe they are the issue.

**Comment by yuwata** [comment] 2019-01-03 16:41
BTW, the log does not contain, e.g., udevd processing 'acpi'. The first device processed by udevd is 'vcs2'. It seems quite strange for me. I am not sure whether it depends on the implementation of initramfs or not, but in my case, with dracut and plain systemd provided udev units, the first device is 'acpi'.

**Comment by gregoa** [comment] 2019-01-03 16:42
@yuwata Please note that message 5 in the Debian bug report is not from me; I think in my prior logs (messages 45 and and 74), evdev was always present.

**Comment by yuwata** [comment] 2019-01-03 16:43
@gregoa Ah, sorry for that...

**Comment by yuwata** [comment] 2019-01-03 16:49
I am not familiar with the sysv init script, but it seems strange that it [triggers only devices but not subsystems](https://salsa.debian.org/systemd-team/systemd/blob/master/debian/udev.init#L181).

But [init-top/udev](https://salsa.debian.org/systemd-team/systemd/blob/master/debian/extra/initramfs-tools/scripts/init-top/udev) triggers both. Is it intended?

**Comment by yuwata** [comment] 2019-01-03 16:56
@gregoa Does adding `udevadm trigger --type=subsystems --action=add` in the udev.init help this issue?

**Comment by gregoa** [comment] 2019-01-03 19:53
Wow. Looks like it just works; i.e. I have all modules back (and also no lvm warnings/timeouts). Thank you!
Quick diff for the debian init script and logs (just in case anyone is interested) at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917247#84

**Comment by mbiebl** [comment] 2019-01-03 19:57
Fwiw, this part of the sysv init script has basically been unchanged for years (it was actually written before I started (co) maintaining systemd).
I'm still worried that we haven't actually found the root cause yet, as we have other user reports, where udev in the initramfs fails to load the modules as well (and initramfs-tools *does* use udevadm trigger --type=subsystems --action=add)

**Comment by gregoa** [comment] 2019-01-03 20:02
Ack, adding the trigger just works around some change in the back …

**Comment by yuwata** [comment] 2019-01-03 20:40
> I'm still worried that we haven't actually found the root cause yet

Yeah, still I have no idea why subsystems are not initialized with v240. I will take a look ebcc52fad68daf4bb3198685c7ab730813606fff (#11144) @keszybz commented.

But, I am surprised that v239 works without triggering subsystems. And adding the trigger command to udev.init seems reasonable.

Anyway, at least we found a workaround. That's a good news.

**Comment by mbiebl** [comment] 2019-01-03 20:49
> Anyway, at least we found a workaround. That's a good news.

I don't think it will help for the initramfs case, i.e. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917607

For the sysv init script: @rfc1036 do you know the history of that particular bit of the sysv init script and why it only triggers for devices but not subsystems?

**Comment by yuwata** [comment] 2019-01-03 20:58
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917607

I'd like to know the issue can be fixed by #11244 or not.

**Comment by mbiebl** [comment] 2019-01-03 23:49
Fwiw, I just reproduced the problem in a kvm/qemu VM using sysvinit three times in a row.
The important difference to previous attempts was that the system was under heavy load (compiling stuff).
I stopped the compile jobs, rebooted the VM and voila, it successfully boots again.
I'm not pretty much convinced we have a race condition somewhere in udev.
I suspect the additional `udevadm trigger --type=subsystems --action=add` just slowed down udev enough for @gregoa  to not this this race condition.

That said, that change looked reasonable on its own, so I applied it as
https://salsa.debian.org/systemd-team/systemd/commit/0b2292a999f34fe47dd3e9f204021bb7dafa9cdf

But I fear we haven't found the root cause yet.

**Comment by mbiebl** [comment] 2019-01-04 00:03
I think the root cause with the sysv init script is actually
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908796
now that I think of it. Sorry for not remembering this earlier.

I'm still at a loss though regarding https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917607

**Comment by mbiebl** [comment] 2019-01-04 00:09
For clarification: the SysV init issue is a Debian specific problem. The init script was switched from
`systemd-udevd --daemon` to `start-stop-daemon` running udev in foreground mode.

This is racy, as systemd-udevd might not have been properly initialized yet when `udevadm trigger` is called.

**Comment by mbiebl** [comment] 2019-01-04 00:11
@gregoa the problematic commit is https://salsa.debian.org/systemd-team/systemd/commit/e803efca59978aa5bb1d8806247f986d0c0f7e67

I'm pretty sure, if you reverted that commit, the problem would be gone

**Comment by yuwata** [comment] 2019-01-04 08:16
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=917607

- Please test with #11244.
- And enable debug logging for udevd. It may be necessary to modify init-top/udev:
https://salsa.debian.org/systemd-team/systemd/blob/master/debian/extra/initramfs-tools/scripts/init-top/udev#L18
- Then, please provide any relevant logs.

**Comment by mbiebl** [comment] 2019-01-04 10:30
> * And enable debug logging for udevd. It may be necessary to modify init-top/udev:
>   https://salsa.debian.org/systemd-team/systemd/blob/master/debian/extra/initramfs-tools/scripts/init-top/udev#L18

Modifying init-top/udev to use `SYSTEMD_LOG_LEVEL=debug` will produce a verbose debug log which goes to the console it seems. This makes it hard to gather the information in a file unless you can redirect the console somehow. I tried setting `SYSTEMD_LOG_TARGET=kmsg`, hoping that the udev log messages could be retrieved via `dmesg`, but I couldn't get that to work. 
@yuwata any idea how the information can be gathered from udev?

**Comment by mbiebl** [comment] 2019-01-06 17:44
@poettering I still have problems getting *any* log messages from udev in the initramfs via dmesg if I use
`SYSTEMD_LOG_LEVEL=debug SYSTEMD_LOG_TARGET=kmsg /lib/systemd/systemd-udevd --daemon`

Seems I'm doing something wrong...

**Comment by keszybz** [comment] 2019-01-06 17:51
Try setting udev_log= in the configuration file. This works best.

**Comment by mbiebl** [comment] 2019-01-06 17:52
@keszybz not sure how this will help
I need to be able to actually retrieve the log messages. If they are printed to the console, it's not too helpful

**Comment by mbiebl** [comment] 2019-01-06 18:13
@yuwata fwiw, I asked one of the bug submitters to try with #11244 applied. Unfortunately it didn't help.
Gathering a debug log from such a situation is still an ongoing problem. Haven't found a solution yet how this can be done...

**Comment by yuwata** [comment] 2019-01-07 16:09
> @yuwata fwiw, I asked one of the bug submitters to try with #11244 applied. Unfortunately it didn't help.
> Gathering a debug log from such a situation is still an ongoing problem. Haven't found a solution yet how this can be done...

Sad, but without logs, I can do almost nothing... @keszybz Do you have any idea?

**Comment by yuwata** [comment] 2019-01-07 16:12
@mbiebl BTW, about the possible race in the initscript, what do you think about adding `udevadm control --ping` or something. udev-ctrl.c has `udev_ctrl_send_ping()` but it is not exposed by `udevadm control` now.

**Comment by mbiebl** [comment] 2019-01-07 22:23
@yuwata a ping command in udevadm seems useful. This was actually suggested in 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908796#25

The alternative is to teach start-stop-daemon about the sd_notify API. See
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910707#116

I'd say, doing both makes sense

**Comment by mbiebl** [comment] 2019-01-08 12:04
@yuwata I think we need to disentangle the sysvinit case (which uses start-stop-daemon and udev in non-forking mode. Here  the `udevadm --ping` command can help) and the initramfs-tools case (which uses `systemd-udevd --daemon`, where I think `udevadm --ping` won't help).

In hindsight, it wasn't a good idea to intermingle these two cases.

Let's focus on the initramfs case in this bug report.

I have additional information from users that so far this seems to happen on X99 chipsets only where the `ahci` kernel module is not loaded.

**Comment by yuwata** [comment] 2019-01-08 13:16
> Let's focus on the initramfs case in this bug report.

OK :+1: 

> initramfs-tools case (which uses systemd-udevd --daemon, where I think udevadm --ping won't help)

Also, in this case, it may be possible that similar race condition hits the system. As I mentioned at the last commit of #11349, https://github.com/systemd/systemd/pull/11349/commits/56126e5aa4acf9ec1f9545cff859a9e503155405, when `--daemon` is set, then the parent process exit immediately after the daemon process is forked, and at that time, the daemon process may not be initialized yet. So, using `ping` command or applying [the commit](https://github.com/systemd/systemd/pull/11349/commits/56126e5aa4acf9ec1f9545cff859a9e503155405) may help the situation, at least theoretically I think.

**Comment by mbiebl** [comment] 2019-01-08 13:50
@yuwata the reason why I don't think the `ping` command helps in the initramfs case is https://github.com/systemd/systemd/issues/11314#issuecomment-452103909

At the point the user executed those commands, he was already dropped into the initramfs recovery shell and the udev process had been started a long time ago.

**Comment by keszybz** [comment] 2019-01-08 15:15
@mbiebl It's been a few weeks and we're not really making progress at this point. You said somewhere that you can reproduce the issue. Can you bisect it? I'm now doing a v239..master bisect for different Fedora issue, and while it's a lot of work, at least it is a mostly deterministic procedure that can be finished in a few hours.

**Comment by yuwata** [comment] 2019-01-08 16:21
@mbiebl From https://github.com/systemd/systemd/commit/56126e5aa4acf9ec1f9545cff859a9e503155405#commitcomment-31871062
> Is this a regression caused by the sd-device rewrite?
Up until now ```systemd-udevd --daemon``` seems to have  DTRT, i.e. we never had any bug reports that udevd was not fully initialized when the `udevadm trigger` calls were made

You mean the commit ebcc52fad68daf4bb3198685c7ab730813606fff or #11144? I have no idea. I cannot reproduce the issue, so I cannot bisect the commits...

**Comment by mbiebl** [comment] 2019-01-08 16:30
@yuwata I asked one of the bug submitters to drop the `-v` again from the `udevadm trigger` command and instead add a `sleep 1` after the start of `systemd-udevd` and before `udevadm trigger`. This apparently did *not* help.
This doesn't sound like there is a race in the startup of systemd-udevd but an issue in udevadm itself.
Call me equally puzzled as yourself.

**Comment by ewhac** [comment] 2019-01-08 20:06
> I have additional information from users that so far this seems to happen on X99 chipsets where the `ahci` kernel module is not loaded.

Count me as well.  I'm the reporter of 917607, and my system is X99-based.  I get dropped to the initramfs prompt with no kernel modules loaded.

**Comment by keszybz** [comment] 2019-01-08 20:41
It's very unlikely that this is related to hardware specifics. Probably only in the sense that certain types of hardware are more likely to tickle the race condition, but nothing more.

**Comment by mbiebl** [comment] 2019-01-08 20:50
so, as I wrote earlier, I was able to reproduce the issue with the sysv init script but not the initramfs scripts.
I decided to switch the udev init script back to use `systemd-udevd --daemon` and it turned out, that `--daemon` is indeed broken in v240. Running a git bisect points at
```
commit c4b69e990f962128cc6975e36e91e9ad838fa2c4
Author: Yu Watanabe <watanabe.yu+github@gmail.com>
Date:   Thu Oct 25 17:41:17 2018 +0900

    udev: drop redundant initializations for file descriptors
    
    As udev_ctrl_new_from_fd() or udev_monitor_new_from_netlink_fd()
    creates fd if negative fd is passed.
```

Seems like adeb26c1affd09138bb96a9e25b795d146e64c97 didn't fix this regression properly.

**Comment by mbiebl** [comment] 2019-01-08 20:53
I have to add, that I'm not entirely sure if it's the same issue as reported by e.g. @ewhac.
He reported that no modules were loaded at all, whereas I could only observe that fewer modules were loaded.

**Comment by mbiebl** [comment] 2019-01-08 20:56
Uploading v240 to Debian was probably not a good idea it seems, I received quite a few angry user emails so far.
That said, not sure what more I can do :-/

**Comment by mbiebl** [comment] 2019-01-08 20:59
I'm still grasping at straws here and I'm not sure if the various user reports are about the same underlying issue or not, which makes it hard for me to provide a coherent bug report. I'm sorry that this turned into such a mess.

**Comment by ewhac** [comment] 2019-01-08 21:12
What kind of additional data would help you?  My PS/2 keyboard is pretty much always handy now, so I could poke at a few things, mount filesystems by hand and save the results...

**Comment by ewhac** [comment] 2019-01-09 10:34
> ```
> I am having this very same issue. If I run
> 
> udevadm trigger --type=subsystems --action=add
> udevadm trigger --type=devices --action=add
> 
> in the initramdfs shell, it does nothing at all. However, if I run
> 
> udevadm trigger --type=subsystems --action=add -v
> udevadm trigger --type=devices --action=add -v
> 
> it loads the necessary modules. Adding the extra `-v` to the
> initramfs-tools script seems to work, but makes the boot quite bloated
> of text :-)
> ```

Confirmed; this happens for me, too.

On my system, `--type=subsystems` does nothing in either case.

If I invoke it as:

    SYSTEMD_LOG_LEVEL=debug udevadm trigger --type=devices --action=add

Then I get the output:

    sd-device-enumerator: Scan all dirs
    sd-device-enumerator: Scan /sys/bus
    sd-device-enumerator: Scan /sys/class

But no modules are loaded.

Now it gets very weird.  I got the Clever Idea to redirect `udevadm` verbose output to a file in /tmp so I could see what it was scanning, and maybe copy it off to disk:

    SYSTEMD_LOG_LEVEL=debug udevadm trigger --type=devices --action=add -v > /tmp/out

But *this also doesn't work!*  If I keep the `-v` but chop off the redirect, then the trigger works, kernel modules get loaded, and the boot can proceed.  (Also, the USB bus enumerates.)

**Comment by cankoluman** [comment] 2019-01-09 20:52
On Debian Buster, systemd & udev 240-2, with a Gigabyte X-99 SLI (Intel X99 Express) MB, I have the same issues, i.e. initramfs does not recognise the rootfs, usb keyboard does not work.

I can confirm that ewhac's approach of using
`  udevadm trigger --type=devices --action=add -v `
is a sufficient workaround.

I have also found that, starting with a 240-2 generated initramfs, (without any changes to init-top/udev) just replacing with the Debian 239-12~bpo9+1
` /usr/lib/systemd/systemd-udevd `
also works.

It looks like on Debian at least, something seems to have broken between the 239-12~bpo9+1 and 240-2 versions of udev (and/or systemd?). Unfortunately I do not have a ps2 keyboard ...

Finally I compiled the git (stock) ` systemd-stable at tag v240 `. Using ` ldd systemd-udevd` to get the missing libraries between the stock (git) and Debian versions, I added to the Debian 240-2 generated initramfs (1) the missing shared libraries, (2) the stock ` systemd-udevd ` , and (3) ewhac's work-around. The resulting initramfs also booted my Debian system.

I did not test keszybz's version as this was for v239, which already seems to work fine on my Debian system. 

I hope this is helpful.

**Comment by ewhac** [comment] 2019-01-10 09:56
Five bucks says this gets re-opened.

If you read above posts, you'll see that:

    SYSTEMD_LOG_LEVEL=debug udevadm trigger --type=devices --action=add

is invoked ***by hand*** at the initramfs prompt.  The ports are open; `systemd-udevd` was launched long ago and is running.  It just doesn't seem to be doing anything.

To recap:

```
# Does not work:
udevadm trigger --type=devices --action=add

# Works:
udevadm trigger --type=devices --action=add -v

# Does not work:
udevadm trigger --type=devices --action=add -v > /tmp/file
```

Perhaps the voodoo here is extremely deep, but I can't see how the above behavior is explained by an improper initialization sequence in `udevd`.

**Comment by mbiebl** [comment] 2019-01-10 11:49
@ewhac I think so as well, see my comments at https://github.com/systemd/systemd/issues/11314#issuecomment-452362590
https://github.com/systemd/systemd/issues/11314#issuecomment-452304699

I think we have multiple issues here, one is indeed a race in the `--daemon` startup but I think this particular failure is either a race inside udevadm itself (which is slowed down by `-v` just enough so it's no hit) or a race in the interaction between `udevadm` and `udevd`

**Comment by mbiebl** [comment] 2019-01-10 12:20
@ewhac that said, could you give #11376 a try?

**Comment by cankoluman** [comment] 2019-01-10 15:00
Checked out and compiled [b5af8c8](https://github.com/systemd/systemd/commit/b5af8c8cdf5fc7cc5d4108460270728375eb7fc4). On the basis of ` systemd-udevd ` replacement, unfortunately as @ewhac and @mbiebl have suspected, the issue persists and can be resolved by adding ` -v `.

I also compiled [a1b939d](https://github.com/systemd/systemd/commit/a1b939dfc74f1f6ac8e8ad41912ac322b5e2438c) from #11376, again with just ` systemd-udevd ` replacement, the results were as above.

**Comment by mbiebl** [comment] 2019-01-10 15:09
Thanks for testing @cankoluman , very much appreciate.
Re-opening based on your feedback.

**Comment by mbiebl** [comment] 2019-01-10 15:14
@cankoluman could you embed strace in your initramfs and try running `udevadm trigger` using `strace -s500 -f`. To embed strace, edit /usr/share/initramfs-tools/hooks/udev and add a `copy_exec /usr/bin/strace /bin`, then run `update-initramfs -u`

**Comment by mbiebl** [comment] 2019-01-10 15:15
You can store the output of strace in `/run`, that directory is preserved when you continue booting into the real system by exiting the initramfs shell.

**Comment by cankoluman** [comment] 2019-01-10 15:19
@mbiebl glad to help out. Where do I issue the ` strace -s500 -f` is there acertain ordering of items for the 'udev' file?

**Comment by mbiebl** [comment] 2019-01-10 15:22
in the initramfs shell, run `strace -s500 -f udevadm trigger --type=devices --action=add` and redirect the output to file in `/run`. I do have the suspicion though, that stracing the process might actually be sufficient to not trigger this issue. But we'll see...

**Comment by cankoluman** [comment] 2019-01-10 16:11
OK I ran [a1b939d](https://github.com/systemd/systemd/commit/a1b939dfc74f1f6ac8e8ad41912ac322b5e2438c)  with ` strace `. As you suspected, just running with strace produced enough delay for the boot to go ahead. I attach the strace log, in case it is of some help.
[strace-out.log.gz](https://github.com/systemd/systemd/files/2746152/strace-out.log.gz)

**Comment by sprokets101** [comment] 2019-01-10 21:09
How can I run the strace command in an initramfs shell? Do I need to use an arch linux live cd?

I updated arch linux and today upon booting into the system I'm confronted with the same error as everyone else.

**Comment by bikefrivolously** [comment] 2019-01-10 21:40
I've been watching this issue as we have quite a few affected users on Arch. It seems mostly to be X99 based systems and VMWare VMs.
Our ticket is https://bugs.archlinux.org/task/61317

@sprokets101 If you have the time and can come by #archlinux on irc.freenode.net and we can work on getting strace into the initramfs. My username on there is dmartins.
Alternatively, if you just need to get back up and running, see https://bbs.archlinux.org/viewtopic.php?pid=1825885

**Comment by yuwata** [comment] 2019-01-10 21:46
Still I cannot reproduce this...
@mbiebl Are there any chance to add a test which reproduces the issue?

> I think we have multiple issues here, one is indeed a race in the `--daemon` startup but I think this particular failure is either a race inside udevadm itself (which is slowed down by `-v` just enough so it's no hit) or a race in the interaction between `udevadm` and `udevd`

If `udevadm trigger` is too fast, then I expect the issue also hits systems using dracut with systemd.
Are there any report which does not use sysv init?

**Comment by mbiebl** [comment] 2019-01-10 21:49
> @mbiebl Are there any chance to add a test which reproduces the issue?

Unfortunately I haven't found a reproducer yet :-/

**Comment by mbiebl** [comment] 2019-01-10 21:51
> If `udevadm trigger` is too fast, then I expect the issue also hits systems using dracut with systemd.
> Are there any report which does not use sysv init?

Not sure. As mentioned earlier, the Debian initramfs is not using systemd.
I was under the impression though that Arch's initramfs *does* use systemd.
@bikefrivolously can probably answer that.

**Comment by mbiebl** [comment] 2019-01-10 21:56
@bikefrivolously if it's reproducible with VMware, could you please share the exact hardware config you are using for such a VM

**Comment by ssolidus** [comment] 2019-01-10 22:21
@mbiebl this bug has occurred on both my Linux VMs. What information do you need?

**Comment by ssolidus** [comment] 2019-01-10 22:23
Also, @mbiebl please answer asap as I plan to downgrade to a working version asap as it is preventing me from working.

**Comment by bikefrivolously** [comment] 2019-01-10 22:41
@mbiebl I'll see if I can get a few example VMWare configs from affected users.

Arch doesn't use systemd in it's initramfs by default. It has it's own minimal init with a number of optional hooks. We have found that switching to a systemd based initramfs works around this problem, but this is far less tested.

In the non-systemd setup there are , two calls to udevadm are made:
    udevadm trigger --action=add --type=subsystems
    udevadm trigger --action=add --type=devices

As suggested earlier, adding the verbose option to these commands also works around the issue.

**Comment by lnussbaum** [comment] 2019-01-10 23:00
Hi,
I'm running in the same issue: in my case, on several identical machines, in the initramfs case (not the sysvinit one), on bare metal. My disk setup is trivial (no LVM, no RAID). the OS is Debian "testing".

I tried to strace udevadm, but then the system booted fine, probably due to the heisenbug effect mentioned above. I can provide the strace output, but I doubt it will be useful.

However, I could bisect the issue, and the first bad commit is e39b4d254de7c12be99a17cc54026695b0bd9c27

If someone needs access to machines where the problem can be reproduced, please let me know (they are part of the CS testbed, so I can provide access, including to the bare metal provisioning)

**Comment by lnussbaum** [comment] 2019-01-10 23:06
I can also confirm that it's still broken in master (that's commit 0192cbdb2c19ed2abbf6662090f45ab3bf4caf56)

**Comment by ssolidus** [comment] 2019-01-10 23:13
> @ssolidus I'd be interested in what that of virtualization you are using and the exact hardware config of the VM

@mbiebl I am using VMware 15.0.2-10952284:
![image](https://user-images.githubusercontent.com/14216632/51002299-f57e3200-1586-11e9-9877-0a385d29e972.png)

Hardware:
![image](https://user-images.githubusercontent.com/14216632/51003024-42630800-1589-11e9-8908-456e05f4bbee.png)

Options:
![image](https://user-images.githubusercontent.com/14216632/51003030-4db63380-1589-11e9-8576-da285a40f96e.png)

And my `.vmx` file is here:
https://gist.github.com/ssolidus/e691a93f3b39717b9e50d2692fe1258b

Do you need anything else?

**Comment by sprokets101** [comment] 2019-01-10 23:32
Hi, @bikefrivolously and thanks for the link. I'm using Arch in a VM as well. If you want I can try to get on IRC and share my config with you so that the root of the problem can be found. 

I'm afraid I'm very much a novice to Linux but I can set up an Arch build, I just don't really know any of the inner workings of Linux.

I updated my system today using Pacman, shutdown and then a few hours later when I logged on again it inexplicably ceased working.

**Comment by bikefrivolously** [comment] 2019-01-10 23:52
@ssolidus thanks. I can reproduce it on the same version with Arch as the host and and a minimal VM (1 CPU, 768MB RAM, 8GB monolithic disk, BIOS boot). I used the default settings for the most part - just picked "Other Linux 4.x ... 64-bit".

My disk is is GPT with a 1MB BIOS boot partition and a second partition filling the rest, formatted as ext4.
It is a bare minimum Arch install.
Adding MODULES=(serio i8042 atkbd) to /etc/mkinitcpio.conf lets the keyboard work in the emergency shell.

@mbiebl any advice on next steps?

@sprokets101 thanks, but for now it looks like I have a reproducible setup

**Comment by bikefrivolously** [comment] 2019-01-11 04:15
I did a bisect between v239 and v240 on systemd-stable
git bisect bad 1742aae2aa8cd33897250d6fcfbe10928e43eb2f <-- v240
git bisect good de7436b02badc82200dc127ff190b8155769b8e7 <-- v239

And came up with "e39b4d254de7c12be99a17cc54026695b0bd9c27 is the first bad commit".

I hope this helps narrow it down.

**Comment by bikefrivolously** [comment] 2019-01-11 04:17
And now I see that @lnussbaum already came to this conclusion.. welp, at least I learned something.

**Comment by yuwata** [comment] 2019-01-11 06:22
@bikefrivolously and @lnussbaum Thank you for bisecting.

> And came up with "e39b4d254de7c12be99a17cc54026695b0bd9c27 is the first bad commit".

I've posted #11389. Could you tested the PR?

**Comment by lnussbaum** [comment] 2019-01-11 08:12
I can confirm that https://github.com/systemd/systemd/pull/11389 fixes the problem.

**Comment by lnussbaum** [comment] 2019-01-11 08:19
I can also confirm that commit f90169d7ec85db1f474d16a8d86bddd9381d43e9 is enough to fix the problem

**Comment by yuwata** [comment] 2019-01-11 09:19
Wow, thanks a lot! Which commit does fix this issue?

**Comment by yuwata** [comment] 2019-01-11 09:21
Ah, I missed the previous comment. Thanks.

**Comment by ssolidus** [comment] 2019-01-11 10:03
@yuwata I can confirm that https://github.com/systemd/systemd/pull/11389 fixes the issue! My arch VM is booting fine from it. Thank you!

**Comment by yuwata** [comment] 2019-01-11 10:11
@ssolidus Thank you for testing the PR. If possible, please also test with only f90169d?

**Comment by cankoluman** [comment] 2019-01-11 10:50
@yuwata  Thanks. I can also confirm that #11389 / commit [f90169d](https://github.com/systemd/systemd/commit/f90169d7ec85db1f474d16a8d86bddd9381d43e9) fixes boot on Debian-Buster with a Gigabyte X-99 SLI (X99 Express Chipset)   

Many thanks to all  :+1:

**Comment by ssolidus** [comment] 2019-01-11 10:57
@yuwata I confirm that https://github.com/systemd/systemd/commit/f90169d7ec85db1f474d16a8d86bddd9381d43e9 fixes the boot still :)

**Comment by yuwata** [comment] 2019-01-11 20:46
Finally I found the root of the issue. Please test the revised version (98aed1d68e13ef44bd844e6347e05faf9385a2ff).

**Comment by keszybz** [comment] 2019-01-11 20:52
Fixed by #11389.

**Closed as completed** 2019-01-11 20:52 UTC
Labels: udev, regression ⚠️

**Comment by cankoluman** [comment] 2019-01-12 11:41
@yuwata & @keszybz, thanks again for the updates. I tested both [98aed1d](https://github.com/systemd/systemd/commit/98aed1d68e13ef44bd844e6347e05faf9385a2ff) and [ee0b9e7](https://github.com/systemd/systemd/commit/ee0b9e721a368742ac6fa9c3d9a33e45dc3203a2) via ` systemd-udevd` substitution  - (on Debian-Buster X99 Chipset).

initramfs boots fine in both cases

**Comment by yuwata** [comment] 2019-01-12 14:57
Thank you for your help.

**Comment by ssolidus** [comment] 2019-01-12 16:10
@yuwata I also tested https://github.com/systemd/systemd/commit/98aed1d68e13ef44bd844e6347e05faf9385a2ff and confirm its working :)

**Comment by msg7086** [comment] 2019-01-15 19:17
Tested on Debian Buster VMware ESXi 6.7, and the patch seems to be working. I had to pull both `systemd` and `udev` 240-4 from sid, and since then I haven't seen any booting failures.

**Comment by yuwata** [comment] 2019-01-18 06:42
@ewhac Thank you for your help.
