### ISSUE TITLE
systemd-nspawn: no login after booting ARM64 container

### ISSUE THREAD

**Issue by dimitry-ishenko** [systemd/systemd#34809] opened 2024-10-17 22:38 UTC
### systemd version the issue has been seen with

255.4

### Used distribution

Ubuntu 24.04

### Linux kernel version used

6.8.0-47-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-nspawn

### Expected behaviour you didn't see

After creating ARM64 container with:
```
sudo debootstrap --include=systemd-container --cache-dir=/var/cache/apt/archives --arch=arm64 noble ./root
```
and booting into it with:
```
sudo systemd-nspawn --boot -D ./root
```
I was expecting to see a login screen.

Same commands work well if I change `--arch=arm64` to my native arch, which is `amd64`.

### Unexpected behaviour you saw

After the container boots with multiple errors (see full boot log below), I get the following:
```
Spawning container root on /home/dimitry/install/root.
Press Ctrl-] three times within 1s to kill container.
systemd 255.4-1ubuntu8 running in system mode (+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization systemd-nspawn.
Detected architecture arm64.

Welcome to Ubuntu 24.04 LTS!

Hostname set to <laptop>.
Queued start job for default target graphical.target.
[  OK  ] Created slice system-modprobe.slice - Slice /system/modprobe.
[  OK  ] Created slice user.slice - User and Session Slice.
...
         Starting systemd-update-utmp-runlevel.service - Record Runlevel Change in UTMP...
[  OK  ] Finished systemd-update-utmp-runlevel.service - Record Runlevel Change in UTMP.

``` 

When booting **amd64** container _do_ get a login screen:
```
Spawning container root on /home/dimitry/install/root.
Press Ctrl-] three times within 1s to kill container.
systemd 255.4-1ubuntu8 running in system mode (+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization systemd-nspawn.
Detected architecture x86-64.

Welcome to Ubuntu 24.04 LTS!

Hostname set to <laptop>.
Queued start job for default target graphical.target.
[  OK  ] Created slice system-modprobe.slice - Slice /system/modprobe.
[  OK  ] Created slice user.slice - User and Session Slice.
...
         Starting systemd-update-utmp-runlevel.service - Record Runlevel Change in UTMP...
[  OK  ] Finished systemd-update-utmp-runlevel.service - Record Runlevel Change in UTMP.

Ubuntu 24.04 LTS laptop pts/0

laptop login: 
```

### Steps to reproduce the problem

```shell
sudo debootstrap --include=systemd-container --cache-dir=/var/cache/apt/archives --arch=arm64 noble ./root
sudo systemd-nspawn --boot -D ./root
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Spawning container root on /home/dimitry/install/root.
Press Ctrl-] three times within 1s to kill container.
systemd 255.4-1ubuntu8 running in system mode (+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization systemd-nspawn.
Detected architecture arm64.

Welcome to Ubuntu 24.04 LTS!

Hostname set to <laptop>.
Queued start job for default target graphical.target.
[  OK  ] Created slice system-modprobe.slice - Slice /system/modprobe.
[  OK  ] Created slice user.slice - User and Session Slice.
[  OK  ] Started systemd-ask-password-console.path - Dispatch Password Requests to Console Directory Watch.
[  OK  ] Started systemd-ask-password-wall.path - Forward Password Requests to Wall Directory Watch.
[  OK  ] Reached target cryptsetup.target - Local Encrypted Volumes.
[  OK  ] Reached target integritysetup.target - Local Integrity Protected Volumes.
[  OK  ] Reached target paths.target - Path Units.
[  OK  ] Reached target remote-fs.target - Remote File Systems.
[  OK  ] Reached target slices.target - Slice Units.
[  OK  ] Reached target swap.target - Swaps.
[  OK  ] Reached target veritysetup.target - Local Verity Protected Volumes.
[  OK  ] Listening on syslog.socket - Syslog Socket.
[  OK  ] Listening on systemd-initctl.socket - initctl Compatibility Named Pipe.
[  OK  ] Listening on systemd-journald-dev-log.socket - Journal Socket (/dev/log).
[  OK  ] Listening on systemd-journald.socket - Journal Socket.
         Mounting dev-hugepages.mount - Huge Pages File System...
         Starting keyboard-setup.service - Set the console keyboard layout...
         Mounting sys-fs-fuse-connections.mount - FUSE Control File System...
systemd-journald.service: unit configures an IP firewall, but the local system does not support BPF/cgroup firewalling.
systemd-journald.service: (This warning is only shown for the first unit using IP firewalling.)
         Starting systemd-journald.service - Journal Service...
         Starting systemd-remount-fs.service - Remount Root and Kernel File Systems...
         Starting systemd-tmpfiles-setup-dev-early.service - Create Static Device Nodes in /dev gracefully...
[  OK  ] Mounted dev-hugepages.mount - Huge Pages File System.
[  OK  ] Mounted sys-fs-fuse-connections.mount - FUSE Control File System.
systemd-tmpfiles-setup-dev-early.service: Failed to set up credentials: Invalid argument
[  OK  ] Finished systemd-remount-fs.service - Remount Root and Kernel File Systems.
systemd-tmpfiles-setup-dev-early.service: Main process exited, code=exited, status=243/CREDENTIALS
systemd-tmpfiles-setup-dev-early.service: Failed with result 'exit-code'.
[FAILED] Failed to start systemd-tmpfiles-setup-dev-early.service - Create Static Device Nodes in /dev gracefully.
See 'systemctl status systemd-tmpfiles-setup-dev-early.service' for details.
         Starting systemd-sysusers.service - Create System Users...
systemd-sysusers.service: Failed to set up credentials: Invalid argument
systemd-sysusers.service: Main process exited, code=exited, status=243/CREDENTIALS
systemd-sysusers.service: Failed with result 'exit-code'.
[FAILED] Failed to start systemd-sysusers.service - Create System Users.
See 'systemctl status systemd-sysusers.service' for details.
         Starting systemd-tmpfiles-setup-dev.service - Create Static Device Nodes in /dev...
systemd-tmpfiles-setup-dev.service: Failed to set up credentials: Invalid argument
[  OK  ] Started systemd-journald.service - Journal Service.
[FAILED] Failed to start systemd-tmpfiles-setup-dev.service - Create Static Device Nodes in /dev.
See 'systemctl status systemd-tmpfiles-setup-dev.service' for details.
         Starting systemd-journal-flush.service - Flush Journal to Persistent Storage...
[  OK  ] Finished systemd-journal-flush.service - Flush Journal to Persistent Storage.
[  OK  ] Finished keyboard-setup.service - Set the console keyboard layout.
[  OK  ] Reached target local-fs-pre.target - Preparation for Local File Systems.
[  OK  ] Reached target local-fs.target - Local File Systems.
[  OK  ] Reached target machines.target - Containers.
[  OK  ] Listening on systemd-sysext.socket - System Extension Image Management (Varlink).
[  OK  ] Reached target sockets.target - Socket Units.
         Starting console-setup.service - Set console font and keymap...
         Starting ldconfig.service - Rebuild Dynamic Linker Cache...
         Starting systemd-tmpfiles-setup.service - Create Volatile Files and Directories...
[FAILED] Failed to start systemd-tmpfiles-setup.service - Create Volatile Files and Directories.
See 'systemctl status systemd-tmpfiles-setup.service' for details.
         Starting systemd-journal-catalog-update.service - Rebuild Journal Catalog...
         Starting systemd-resolved.service - Network Name Resolution...
[  OK  ] Reached target time-set.target - System Time Set.
         Starting systemd-update-utmp.service - Record System Boot/Shutdown in UTMP...
[  OK  ] Finished console-setup.service - Set console font and keymap.
[  OK  ] Finished ldconfig.service - Rebuild Dynamic Linker Cache.
[  OK  ] Finished systemd-update-utmp.service - Record System Boot/Shutdown in UTMP.
[FAILED] Failed to start systemd-resolved.service - Network Name Resolution.
See 'systemctl status systemd-resolved.service' for details.
         Starting systemd-resolved.service - Network Name Resolution...
[FAILED] Failed to start systemd-resolved.service - Network Name Resolution.
See 'systemctl status systemd-resolved.service' for details.
         Starting systemd-resolved.service - Network Name Resolution...
[FAILED] Failed to start systemd-resolved.service - Network Name Resolution.
See 'systemctl status systemd-resolved.service' for details.
         Starting systemd-resolved.service - Network Name Resolution...
[  OK  ] Finished systemd-journal-catalog-update.service - Rebuild Journal Catalog.
         Starting systemd-update-done.service - Update is Completed...
[  OK  ] Finished systemd-update-done.service - Update is Completed.
[FAILED] Failed to start systemd-resolved.service - Network Name Resolution.
See 'systemctl status systemd-resolved.service' for details.
         Starting systemd-resolved.service - Network Name Resolution...
[FAILED] Failed to start systemd-resolved.service - Network Name Resolution.
See 'systemctl status systemd-resolved.service' for details.
[FAILED] Failed to start systemd-resolved.service - Network Name Resolution.
See 'systemctl status systemd-resolved.service' for details.
[  OK  ] Reached target nss-lookup.target - Host and Network Name Lookups.
[  OK  ] Reached target sysinit.target - System Initialization.
[  OK  ] Started apt-daily.timer - Daily apt download activities.
[  OK  ] Started apt-daily-upgrade.timer - Daily apt upgrade and clean activities.
[  OK  ] Started dpkg-db-backup.timer - Daily dpkg database backup timer.
[  OK  ] Started e2scrub_all.timer - Periodic ext4 Online Metadata Check for All Filesystems.
[  OK  ] Started logrotate.timer - Daily rotation of log files.
[  OK  ] Started motd-news.timer - Message of the Day.
[  OK  ] Started systemd-tmpfiles-clean.timer - Daily Cleanup of Temporary Directories.
[  OK  ] Reached target timers.target - Timer Units.
[  OK  ] Listening on dbus.socket - D-Bus System Message Bus Socket.
[  OK  ] Reached target basic.target - Basic System.
         Starting systemd-logind.service - User Login Management...
[  OK  ] Started cron.service - Regular background program processing daemon.
         Starting dbus.service - D-Bus System Message Bus...
[  OK  ] Started dmesg.service - Save initial kernel messages after boot.
         Starting rsyslog.service - System Logging Service...
         Starting systemd-user-sessions.service - Permit User Sessions...
[  OK  ] Finished systemd-user-sessions.service - Permit User Sessions.
[  OK  ] Started console-getty.service - Console Getty.
[  OK  ] Created slice system-getty.slice - Slice /system/getty.
[  OK  ] Reached target getty.target - Login Prompts.
[  OK  ] Started dbus.service - D-Bus System Message Bus.
[  OK  ] Started rsyslog.service - System Logging Service.
[  OK  ] Started systemd-logind.service - User Login Management.
[  OK  ] Reached target multi-user.target - Multi-User System.
[  OK  ] Reached target graphical.target - Graphical Interface.
         Starting systemd-update-utmp-runlevel.service - Record Runlevel Change in UTMP...
[  OK  ] Finished systemd-update-utmp-runlevel.service - Record Runlevel Change in UTMP.
```

**Comment by poettering** [comment] 2024-10-18 07:10
is this via qemu-static? that's highly limited, it's not good enough to boot up a full system, but that's not systemd's fault really, but current limitations of qemu-static

**Comment by poettering** [comment] 2024-10-18 12:01
Duplicate of #31219

**Closed as completed by poettering** 2024-10-18 12:01 UTC
Labels: bug 🐛, nspawn
