### ISSUE TITLE
A pid without using systemd unit which it's cgroup path migrate silently

### ISSUE THREAD

**Issue by suxiaobei1024** [systemd/systemd#11584] opened 2019-01-29 03:08 UTC
**systemd version the issue has been seen with**
> ...

I am not sure, cause I cann't build upstream version, I want to ask a favour of somebody else help me to reproduce

**Used distribution**
 > …

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > …

As bellow,  we realize that, when we manage a pid without using systemd unit(we cann't guarantee all process must wrapper in systemd unit at all scene),
For example: I reset the target pid'd cgroup path: "/sys/fs/cgroup/memory/jiangyi/", After we execute "systemctl daemon-reload and restart prarent pid(sometimes the parent always is sshd.service, sshd need upgrade)"
the target pid will be migrated to "/system.slice/sshd.service/" silently. (I would say maybe it's a dangerous behavior.)

So, I would wonder say that is this a bug?

**Steps to reproduce the problem**

```

[root@localhost /home/bill]
#sh  /tmp/aa.sh  &               <<<==== This is a common process which is not wrapper with systemd
[1] 33577

[root@localhost /home/bill]
#cat /proc/33577/cgroup
10:net_cls:/
9:freezer:/
8:blkio:/
7:memory:/system.slice/sshd.service      <<<<===== When use sshd start this process, then pid will be placed at default cgroup path (sshd.service)
6:perf_event:/
5:pids:/
4:hugetlb:/
3:devices:/system.slice/sshd.service
2:cpuset,cpu,cpuacct:/
1:name=systemd:/system.slice/sshd.service

[root@localhost /home/bill]
#echo 33577 > /sys/fs/cgroup/memory/jiangyi/tasks   <<<=== Infact, we want to manage this pid's cgroup path at a suitable place.

[root@localhost /home/bill]
#cat /proc/33577/cgroup
10:net_cls:/
9:freezer:/
8:blkio:/
7:memory:/jiangyi    <<<=== This is what we want
6:perf_event:/
5:pids:/
4:hugetlb:/
3:devices:/system.slice/sshd.service
2:cpuset,cpu,cpuacct:/
1:name=systemd:/system.slice/sshd.service

[root@localhost /home/bill]
#systemctl daemon-reload        <<<=== There we do daemon-reload (someties sshd need upgrade configure file)and  restart sshd.service

[root@localhost /home/bill]
#systemctl restart sshd

[root@localhost /home/bill]
#cat /proc/33577/cgroup
10:net_cls:/
9:freezer:/
8:blkio:/
7:memory:/system.slice/sshd.service    <<<== There systemd automatically revert target pid's cgroup to default cgroup path
6:perf_event:/
5:pids:/
4:hugetlb:/
3:devices:/system.slice/sshd.service
2:cpuset,cpu,cpuacct:/
1:name=systemd:/system.slice/sshd.service
```

**Comment by vcaputo** [comment] 2019-01-29 03:32
You can probably avoid all this by using `systemd-run` for executing `/tmp/aa.sh`.

**Comment by muahao** [comment] 2019-01-29 05:13
> You can probably avoid all this by using `systemd-run` for executing `/tmp/aa.sh`.

Thanks for your reply, I thinks it can reproduce identical ...


```
[root@localhost /home/bill/systemd]
#systemd-run  sh /tmp/aa.sh
Running as unit run-113575.service.

[root@localhost /home/bill/systemd]
#cat /proc/113577/cgroup
10:net_cls:/
9:freezer:/
8:blkio:/
7:memory:/system.slice/run-113575.service
6:perf_event:/
5:pids:/
4:hugetlb:/
3:devices:/system.slice/run-113575.service
2:cpuset,cpu,cpuacct:/
1:name=systemd:/system.slice/run-113575.service

[root@localhost /home/bill/systemd]
#echo 113577 > /sys/fs/cgroup/memory/jiangyi/tasks

[root@localhost /home/bill/systemd]
#cat /proc/113577/cgroup
10:net_cls:/
9:freezer:/
8:blkio:/
7:memory:/jiangyi
6:perf_event:/
5:pids:/
4:hugetlb:/
3:devices:/system.slice/run-113575.service
2:cpuset,cpu,cpuacct:/
1:name=systemd:/system.slice/run-113575.service

[root@localhost /home/bill/systemd]
#systemctl daemon-reload

[root@localhost /home/bill/systemd]
#systemctl restart sshd

[root@localhost /home/bill/systemd]
#cat /proc/113577/cgroup
10:net_cls:/
9:freezer:/
8:blkio:/
7:memory:/system.slice/run-113575.service
6:perf_event:/
5:pids:/
4:hugetlb:/
3:devices:/system.slice/run-113575.service
2:cpuset,cpu,cpuacct:/
1:name=systemd:/system.slice/run-113575.service

```

**Comment by poettering** [comment] 2019-01-29 08:58
systemd takes exclusive ownership of all cgroup hierarchies you tell it to use, but allows delegation points.

Hence, if you want to make your own changes directly to cgroupfs, then you have two options:

1. configure systemd to not use the controller at all. i.e. make sure none of your units uses the accounting options MemoryAccounting=yes, CPUAccounting=yes, … (and their global counterparts in system.conf) nor the resource mgmt options CPUShares=, MemoryLimit= or so. As soon as at least one unit makes use of it, systemd takes possessoin of the controller in full though.

2. use cgroup delegation to take your own private subtree of the cgroup tree where systemd won't interfere anymore, using the Delegate= option.

if you are doing neither of the above, then yes, you will trample all over what systemd does, and systemd will trample all over your changes, and this is really by design. cgroup doesn#t really allow for the same set of groups being managed by multiple managers. 

Anyway, closing hence, since this is not a bug.

**Closed as completed by poettering** 2019-01-29 08:58 UTC

**Comment by poettering** [comment] 2019-01-29 09:00
> As bellow, we realize that, when we manage a pid without using systemd unit(we cann't guarantee all process must wrapper in systemd unit at all scene),

all userspace processes are part of a systemd unit btw. the entire userspace is partitioned into untis, and there's no way to escape that. when you fork of a process off an ssh session then it's part of the sshd unit or of the scope unit of the session (the latter if you use logind to manage sessions)

**Comment by muahao** [comment] 2019-01-29 12:56
> > As bellow, we realize that, when we manage a pid without using systemd unit(we cann't guarantee all process must wrapper in systemd unit at all scene),
> 
> all userspace processes are part of a systemd unit btw. the entire userspace is partitioned into untis, and there's no way to escape that. when you fork of a process off an ssh session then it's part of the sshd unit or of the scope unit of the session (the latter if you use logind to manage sessions)



Thanks for your reply, with your friendly direction, I adapt "Delegate=yes"  in sshd.service unit file, It  can solve my trouble.

**Comment by DanielQujun** [comment] 2019-11-08 04:01
@muahao Hi, could you  please explain ` When use sshd start this process`,  when I login by ssh , any process I executed was place under /user.slice . but i do seen process under sshd.service , and it got oom killed cause I set a small value in system.slice/memory.limit_in_bytes .

I googled this link https://serverfault.com/questions/968717/how-does-systemd-put-sshd-processes-in-slices, but did not find answer , could you pls give any hint?
