### ISSUE TITLE
resource control does not apply automatically with user instance

### ISSUE THREAD

**Issue by LockRing** [systemd/systemd#9887] opened 2018-08-20 11:53 UTC
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > Resource control (In the example below, memory limitation) apply to user instance automatically.

**Unexpected behaviour you saw**
 > Resource control does not apply to user instance.

**Steps to reproduce the problem**
Boot system with systemd.unified_cgroup_hierarchy=1 kernel parameter.
Make a .slice unit for limit memory usage.
>[Unit]
>Description=limit slice
>
>[Slice]
>MemoryAccounting=true
>MemoryMax=40M
>MemoryLimit=40M
>MemoryHigh=10M
>
>[Install]
>WantedBy=default.target

I named `limit.slice` this file.
Put this file into `/home/example/.config/systemd/user/`.
Run `systemctl --user enable limit.slice` and `systemctl --user start limit.slice`.
You can see memory limitation is not applied when run `systemctl --user status limit.slice`.
>● limit.slice - limit slice
   Loaded: loaded (/home/example/.config/systemd/user/limit.slice; enabled; vendor preset: enabled)
   Active: active since Mon 2018-08-20 10:06:26 UTC; 42s ago
   CGroup: /user.slice/user-1001.slice/user@1001.service/limit.slice

Additionally, parent CGroup units information.
user.slice: 
>● user.slice - User and Session Slice
   Loaded: loaded (/usr/lib/systemd/system/user.slice; static; vendor preset: disabled)
   Active: active since Mon 2018-08-20 10:06:14 UTC; 1min 37s ago
     Docs: man:systemd.special(7)
    Tasks: 5
   Memory: 7.6M
   CGroup: /user.slice
           └─user-1001.slice
             ├─session-1.scope
             │ ├─343 login -- example
             │ ├─368 -bash
             │ └─385 systemctl status user.slice
             └─user@1001.service
              └─init.scope
                 ├─362 /usr/lib/systemd/systemd --user
                 └─363 (sd-pam)

user-1001.slice:
>● user-1001.slice - User Slice of UID 1001
   Loaded: loaded
  Drop-In: /usr/lib/systemd/system/user-.slice.d
           └─10-defaults.conf
   Active: active since Mon 2018-08-20 10:06:26 UTC; 2min 8s ago
   CGroup: /user.slice/user-1001.slice
           ├─session-1.scope
           │ ├─343 login -- example
           │ ├─368 -bash
           │ └─387 systemctl status user-1001.slice
           └─user@1001.service
             └─init.scope
               ├─362 /usr/lib/systemd/systemd --user
               └─363 (sd-pam)

user.slice looks like `MemoryAccounting` is enabled, but the other is not.

Suprisingly, I found a weird way to enable memory limitation on `limit.slice`.
>sudo systemctl --runtime set-property user-1001.slice CPUAccounting=true
sudo systemctl daemon-reload
systemctl --user daemon-reload

Run these codes, memory limitation is applied.
>● limit.slice - limit slice
   Loaded: loaded (/home/example/.config/systemd/user/limit.slice; enabled; vendor preset: enabled)
   Active: active since Mon 2018-08-20 10:06:26 UTC; 7min ago
    Tasks: 0
   Memory: 0B (high: 10.0M max: 40.0M limit: 40.0M)
   CGroup: /user.slice/user-1001.slice/user@1001.service/limit.slice

`CPUAccounting` is false in default, so I think that triggered something inner systemd.

**Comment by poettering** [comment] 2018-09-11 18:38
This only works post acc8059129b38d60c1b923670863137f8ec8f91a. Do you have that in your version?

Basically, user instances can only make use of cgroup controllers delegated to them. Starting with that commit "tasks" and "memory" are delegated to regular users by default. Before that "memory" wasn't, hence the user instance had no chance to manage memory limits or accounting.

**Comment by LockRing** [comment] 2018-09-12 04:43
Yes I have it.
Slice of /usr/lib/systemd/system/user@.service:
>[Service]
>User=%i
>PAMName=systemd-user
>Type=notify
>ExecStart=-/usr/lib/systemd/systemd --user
>Slice=user-%i.slice
>KillMode=mixed
>Delegate=pids memory
>TasksMax=infinity
>TimeoutStopSec=120s

But the delegation does not seem to work properly...
`ls -1 /sys/fs/cgroup/user.slice` :
>cgroup.controllers
cgroup.events
cgroup.max.depth
cgroup.max.descendants
cgroup.procs
cgroup.stat
cgroup.subtree_control
cgroup.threads
cgroup.type
cpu.stat
memory.current
memory.events
memory.high
memory.low
memory.max
memory.min
memory.stat
memory.swap.current
memory.swap.events
memory.swap.max
pids.current
pids.events
pids.max
user-1000.slice

`ls -1 /sys/fs/cgroup/user.slice/user-1000.slice`:
>cgroup.controllers
cgroup.events
cgroup.max.depth
cgroup.max.descendants
cgroup.procs
cgroup.stat
cgroup.subtree_control
cgroup.threads
cgroup.type
cpu.stat
session-4.scope
user@1000.service

`ls -1 /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service`:
>cgroup.controllers
cgroup.events
cgroup.max.depth
cgroup.max.descendants
cgroup.procs
cgroup.stat
cgroup.subtree_control
cgroup.threads
cgroup.type
cpu.stat
dbus.service
dbus.socket
init.scope
limit.slice
pulseaudio.service

The memory controller has disappeared from user-@.slice.

**Comment by Xuanwo** [comment] 2018-10-09 02:40
This can be reproduced by following steps:

1. `systemd-run --user -t vim`, and we can get a running service like `run-u56.service`
2. Set a MemoryMax for it: `systemctl --user set-property run-u56.service  MemoryMax=1K`

A vim will use up to 4M, with MemoryMax=1K, vim should be kill now, however:

- Vim keeps running
- The accounting for memory in `systemctl --user status run-u56.service`not found
- `memory.max` under `/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/run-u56.service` not found

If we use `systemd-run -t vim` and `systemctl set-property run-u56.service  MemoryMax=1K`, everything works as expected.

**Comment by Xuanwo** [comment] 2018-10-10 02:43
ping @poettering in case of you are missing this issue.

**Comment by poettering** [comment] 2018-11-23 11:29
Duplicate of #9512

**Closed as completed by poettering** 2018-11-23 11:29 UTC
Labels: cgroups, pid1, duplicate
