### ISSUE TITLE
networkd: wrong IP address configuration after switching from DHCP to static

### ISSUE THREAD

**Issue by okashany** [systemd/systemd#25751] opened 2022-12-15 09:35 UTC
### systemd version the issue has been seen with

251.2+

### Linux kernel version used

5.10.36-6a21033-dirty-6bc3dae

### CPU architectures issue was seen on

arm

### Component

systemd-networkd

### Unexpected behaviour you saw

When switching from DHCP to static, it takes the IP address that was given earlyer by the DHCP and displays it as an additional static address. Although the file seems to be correct (only one address, which was configured by me).

![11](https://user-images.githubusercontent.com/118159036/207821857-f3ee0732-7c27-4c92-a105-88ab35414c86.png)
![22](https://user-images.githubusercontent.com/118159036/207821882-08afe7ba-b920-433d-8b67-fbc80a4d315a.png)
![33](https://user-images.githubusercontent.com/118159036/207823281-bef1f984-8527-442f-99f3-d95048e955cc.png)

**Comment by yuwata** [comment] 2022-12-15 09:40
I guess the address is generated from RA. Please try to disable `IPv6AcceptRA=no` if you wan to disable it.

Looks not a bug. Closing.

**Closed as completed by yuwata** 2022-12-15 09:40 UTC
Labels: network, not-a-bug

**Comment by okashany** [comment] 2022-12-15 09:46
Thank you for your response.
We call "    stream << std::boolalpha
           << "IPv6AcceptRA=" << EthernetInterfaceIntf::ipv6AcceptRA() << "\n";"
 Isn't is supposed to return "no" ?

**Comment by yuwata** [comment] 2022-12-15 10:54
I have no idea about the code. Such programming interface is not provided by us. Please show relevant .network file, result of networkctl, and journal. Otherwise, there is almost nothing we can say.
