### ISSUE TITLE
Systemd fails to mount BTRFS subvolumes if the filesystem was mounted without udevd running

### ISSUE THREAD

**Issue by desultory** [systemd/systemd#33948] opened 2024-08-05 23:47 UTC
### systemd version the issue has been seen with

255.7

### Used distribution

Gentoo

### Linux kernel version used

6.6.32

### CPU architectures issue was seen on

x86_64

### Component

systemd, systemd-udevd

### Expected behaviour you didn't see

subvols defined in the fstab are mounted.

### Unexpected behaviour you saw

systemd times out looking for the udev device node for the root filesystem device, and times out because it was mounted without udev running.

### Steps to reproduce the problem

Use an initramfs without udev, switch_root into a systemd system, watch as it times out looking for the rootfs device it's currently using.

I used UGRD to test this: https://github.com/desultory/ugrd

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
/dev/mapper/root    /        auto   defaults,subvol=/gentoo_systemd
/dev/mapper/root    /test    auto   defaults,subvol=/gentoo_systemd/testsubvol
```

**Comment by poettering** [comment] 2024-08-19 09:09
Is this lvm? sorry, that's something you have to ping the lvm folks about, and your initrd implementation. lvm stuff is its own thing, not maintained by us.

**Comment by poettering** [comment] 2024-08-19 09:10
or actually, let's close this. I DM/LVM stuff (in particular in conjunction with something that isn't using systemd in the initrd) is really out of scope with us. Please ping your distro for help.

**Closed as completed by poettering** 2024-08-19 09:10 UTC
Labels: udev, pid1, not-our-bug

**Comment by desultory** [comment] 2024-08-19 15:15
> Is this lvm? sorry, that's something you have to ping the lvm folks about, and your initrd implementation. lvm stuff is its own thing, not maintained by us.

LVM is not used here at all. The rootfs is on a LUKS volume which is mounted properly.

The rootfs is mounted successfully. If there is more I need to do to make systemd see it, I'm interested to know what steps I need to take.

**Comment by desultory** [comment] 2024-08-19 15:21
> or actually, let's close this. I DM/LVM stuff (in particular in conjunction with something that isn't using systemd in the initrd) is really out of scope with us. Please ping your distro for help.

https://systemd.io/INITRD_INTERFACE/

This says systemd is not a requirement? Same with a "storage daemon"

So is systemd a requirement in the initramfs now?

**Comment by desultory** [comment] 2024-08-19 16:39
> IIUC, using LUKS means dm-X will be generated. So, in that case, as same as the LVM case in your other issue, some state about the dm device need to be saved into a udev database. Otherwise `SYMLINK=` will not be processed for the device, and even if the symlink exists, PID1 (systemd) after switching root cannot detect the device is ready.
> 
> So, the root cause is exactly the same, and the 'issue' is not by systemd. It should be 'fixed' by a device-mapper.

Why does this issue only affect systemd then? I can't replicate this on any other init system.

I just ran a test where I created the /dev/disk/by-uuid symlink manually.

Is there any way to make systemd not stall looking for mounts that are already present besides just using udev? There must be some simple requirement that can be met here.

**Comment by yuwata** [comment] 2024-08-19 16:56
> > IIUC, using LUKS means dm-X will be generated. So, in that case, as same as the LVM case in your other issue, some state about the dm device need to be saved into a udev database. Otherwise `SYMLINK=` will not be processed for the device, and even if the symlink exists, PID1 (systemd) after switching root cannot detect the device is ready.
> > So, the root cause is exactly the same, and the 'issue' is not by systemd. It should be 'fixed' by a device-mapper.
> 
> Why does this issue only affect systemd then? I can't replicate this on any other init system.

systemd requires uevent notification sent from udevd, and configured symlink needs to be announced through the notification. Otherwise, we can not judge if the symlink and the device that the symlink points to are ready.

> This is not LVM related, so where do I open a bug? I'm not sure who maintains the udev rules related to this.

Related rules come from 10-dm.rules, and it is maintained by LVM.
https://github.com/lvmteam/lvm2/blob/main/udev/10-dm.rules.in

> I just ran a test where I created the /dev/disk/by-uuid symlink manually. That did not work, it still stalled even though the path mentioned was a valid symlink.

As described in the above, the existence of the symlink is not enough. systemd waits for announce about the symlink in uevent notification.

> Is there any way to make systemd not stall looking for mounts that are already present besides just using udev? There must be some simple requirement that can be met here.

I have no idea. Why not to simply install systemd and systemd-udevd in your initrd?
Potentially, there may be a workaround, but we cannot support that, and that may be easily broken in a future release of systemd or LVM.

**Comment by desultory** [comment] 2024-08-19 17:02
> > > IIUC, using LUKS means dm-X will be generated. So, in that case, as same as the LVM case in your other issue, some state about the dm device need to be saved into a udev database. Otherwise `SYMLINK=` will not be processed for the device, and even if the symlink exists, PID1 (systemd) after switching root cannot detect the device is ready.
> > > So, the root cause is exactly the same, and the 'issue' is not by systemd. It should be 'fixed' by a device-mapper.
> > 
> > 
> > Why does this issue only affect systemd then? I can't replicate this on any other init system.
> 
> systemd requires uevent notification sent from udevd, and configured symlink needs to be announced through the notification. Otherwise, we can not judge if the symlink and the device that the symlink points to are ready.
> 

How do I accomplish this? I don't understand how this signal could be passed in any way other than args passed to systemd when the initramfs runs switch_root. (the final command)

> > This is not LVM related, so where do I open a bug? I'm not sure who maintains the udev rules related to this.
> 
> Related rules come from 10-dm.rules, and it is maintained by LVM. https://github.com/lvmteam/lvm2/blob/main/udev/10-dm.rules.in
> 
> > I just ran a test where I created the /dev/disk/by-uuid symlink manually. That did not work, it still stalled even though the path mentioned was a valid symlink.
> 
> As described in the above, the existence of the symlink is not enough. systemd waits for announce about the symlink in uevent notification.
> 

What particular notification must be sent? is there any way to do this besides using udev.

> > Is there any way to make systemd not stall looking for mounts that are already present besides just using udev? There must be some simple requirement that can be met here.
> 
> I have no idea. Why not to simply install systemd and systemd-udevd in your initrd? Potentially, there may be a workaround, but we cannot support that, and that may be easily broken in a future release of systemd or LVM.

For the simple reason that I do not understand it, and for most use cases I do not need it. My system generates initeramfs images that are about 10mb uncompressed by default. That is smaller than the average udev install, and anyone who knows basic bash can verify the entirety of the generated script in a few minutes.

For my system to work, it does not need udev. My system does no more than mount the rootfs, and hand things off to whatever init system happens to be on the target root filesystem. It does not need to do more, so why make it do more?

This only seems to be a requirement to boot systemd, and to me, seems like a systemd issue for that reason. Dinit doesn't need this, openrc doesn't need this, i can even use bash as an init and it doesn't need this. If everything else works, it seems the issue is with systemd. At the very least, maybe systemd need some arg you can pass it saying "hey you're starting at stage2" or something. The fact that it simply breaks when the mount is very clearly present seems like deficiency with systemd. If systemd requires systemd/systemd tools (udevd) to be running before it runs, isn't that a bit circular and unreliable?

**Comment by yuwata** [comment] 2024-08-19 17:37
> For my system to work, it does not need udev.

It _does_ need udev, when you want to initialize dm devices in initrd and use them after switching root with systemd.
You just want to kill udev in initrd, rather than it is not necessary. Please do not mix them.
And the restriction is come from 10-dm.rules, which is managed by LVM people.

Here is not a support forum, and your initrd script cannot be consulted here. Sorry.

**Comment by desultory** [comment] 2024-08-19 17:41
> > For my system to work, it does not need udev.
> 
> It _does_ need udev, when you want to initialize dm devices in initrd and use them after switching root with systemd. You just want to kill udev in initrd, rather than it is not necessary. Please do not mix them. And the restriction is come from 10-dm.rules, which is managed by LVM people.
> 

For my initrd to mount the rootfs and switch_root to it, it does not need udev.

For systemd to detect the mount was mounted (even though it's the root mount and this should be implied), it requires that the initrd was using udevd.

Is there any other way that systemd can be told that the rootfs was mounted.

To be clear: udevd is not _needed_ to mount the rootfs, it's only "needed" to tell systemd that something was mounted, which again, should be implied since systemd lives in the root partition (or /usr which my system would also handle mounting) 

> Here is not a support forum, and your initrd script cannot be consulted here. Sorry.

My script does not need adjustment to function and do what it was designed to do. It needs adjustment because it doesn't send some bespoke signal to systemd. Where am I supposed to learn what signal systemd expects or how to interface with it? Surely I don't need all of udev to send the signal that a mount was mounted?

**Comment by desultory** [comment] 2024-08-19 17:51
Lets use an analogy: 

Systemd is like a fast food restaurant, it's something very common and meant to serve the user.
Fast food restaurants tend to have drive-thru lanes, making it easier for users to be served on the go.
The drive-thru becomes the typical way to serve users, as it's convenient, and users who dine-in even tend to drive there.
One day, I walk in and order food and get told "sorry we can't serve you because you didn't drive here", even though you walked to the register, where you place orders.

Does that make sense?

**Comment by yuwata** [comment] 2024-08-19 20:56
If looking at only initrd stage, then udev may not be necessary. But that does not mean your initrd is perfect. Actually lack of udevd causes the issue after switching root. And, as already commented in https://github.com/lvmteam/lvm2/issues/153, currently device-mapper does not support such setup.
Sorry, that's simply unsupported.

If you learn about block device handling in systemd and udevd, the first steps are
- enable debugging logs to see what they do
```
systemclt log-level debug
udevadm control --log-level=debug
```
- monitor uevents: opening two terminal and run `udevadm monitor` and `udevadm trigger --action=add /sys/class/block/DEVICE`.

Again, this is not a support forum. Please use our matrix channel or so for learning about systemd further.

**Comment by desultory** [comment] 2024-08-19 21:15
> If looking at only initrd stage, then udev may not be necessary. But that does not mean your initrd is perfect. Actually lack of udevd causes the issue after switching root. And, as already commented in [lvmteam/lvm2#153](https://github.com/lvmteam/lvm2/issues/153), currently device-mapper does not support such setup. Sorry, that's simply unsupported.

I'll accept this, but I think there should be a doc change. If this is the case, maybe there should be an update to this page: https://systemd.io/INITRD_INTERFACE/

saying something along the lines of "udev must be running in the initramfs or systemd will be unable to handle submounts". I think currently, it suggests that udev/any "storage daemon" is totally optional. It also suggests that systemd being in the initramfs is optional as well. If not using systemd/udevd in the initramfs is unsupported, I think that should be clearly stated.

> 
> If you learn about block device handling in systemd and udevd, the first steps are
> 
>     * enable debugging logs to see what they do
> 
> 
> ```
> systemclt log-level debug
> udevadm control --log-level=debug
> ```
> 
>     * monitor uevents: opening two terminal and run `udevadm monitor` and `udevadm trigger --action=add /sys/class/block/DEVICE`.
> 

Do this in the initramfs or after?

> 
> Again, this is not a support forum. Please use our matrix channel or so for learning about systemd further.

I've been asking about this in the libera systemd channel about once a week for months and have not been able to figure anything out.

**Comment by yuwata** [comment] 2024-08-19 21:39
> > If looking at only initrd stage, then udev may not be necessary. But that does not mean your initrd is perfect. Actually lack of udevd causes the issue after switching root. And, as already commented in [lvmteam/lvm2#153](https://github.com/lvmteam/lvm2/issues/153), currently device-mapper does not support such setup. Sorry, that's simply unsupported.
> 
> I'll accept this, but I think there should be a doc change. If this is the case, maybe there should be an update to this page: https://systemd.io/INITRD_INTERFACE/
> 
> saying something along the lines of "udev must be running in the initramfs or systemd will be unable to handle submounts". I think currently, it suggests that udev/any "storage daemon" is totally optional. It also suggests that systemd being in the initramfs is optional as well. If not using systemd/udevd in the initramfs is unsupported, I think that should be clearly stated.

Strictly speaking, systemd does not request that. But device-mapper requires that. So, if you want to improve documentation, that should be mentioned in the document of device-mapper.
Note, subvolume mounts of btrfs should work even with initrd-less initrd when the btrfs is on a simple block device, e.g. sda1 or nvme0n1. In your case, LUKS is used. So, device-mapper is required. Btrfs should not be the root cause.

> Do this in the initramfs or after?

Anytime, anywhere, when you'd like. I recommend to start normal simple setup of a distro, rather than complicated storage setup.

> > Again, this is not a support forum. Please use our matrix channel or so for learning about systemd further.
> 
> I've been asking about this in the libera systemd channel about once a week for months and have not been able to figure anything out.

The libera or matrix channels are chatting rooms. You cannot expect any response.

**Comment by desultory** [comment] 2024-08-23 18:38
> > > If looking at only initrd stage, then udev may not be necessary. But that does not mean your initrd is perfect. Actually lack of udevd causes the issue after switching root. And, as already commented in [lvmteam/lvm2#153](https://github.com/lvmteam/lvm2/issues/153), currently device-mapper does not support such setup. Sorry, that's simply unsupported.
> > 
> > 
> > I'll accept this, but I think there should be a doc change. If this is the case, maybe there should be an update to this page: https://systemd.io/INITRD_INTERFACE/
> > saying something along the lines of "udev must be running in the initramfs or systemd will be unable to handle submounts". I think currently, it suggests that udev/any "storage daemon" is totally optional. It also suggests that systemd being in the initramfs is optional as well. If not using systemd/udevd in the initramfs is unsupported, I think that should be clearly stated.
> 
> Strictly speaking, systemd does not request that. But device-mapper requires that. So, if you want to improve documentation, that should be mentioned in the document of device-mapper. Note, subvolume mounts of btrfs should work even with initrd-less initrd when the btrfs is on a simple block device, e.g. sda1 or nvme0n1. In your case, LUKS is used. So, device-mapper is required. Btrfs should not be the root cause.
> 
> > Do this in the initramfs or after?
> 
> Anytime, anywhere, when you'd like. I recommend to start normal simple setup of a distro, rather than complicated storage setup.
> 

I found this, is this what is required to signal to systemd that a deviece is online? Can i simply write to this file? does it need the symlink made too? I simply want to hotwire things so they are aware that the device is online.

https://github.com/anatol/booster/blob/master/init/udev.go#L251C40-L251C67

> > > Again, this is not a support forum. Please use our matrix channel or so for learning about systemd further.
> > 
> > 
> > I've been asking about this in the libera systemd channel about once a week for months and have not been able to figure anything out.
> 
> The libera or matrix channels are chatting rooms. You cannot expect any response.

I can't find any systemd matrix channel.

**Comment by yuwata** [comment] 2024-08-24 00:00
> I found this, is this what is required to signal to systemd that a deviece is online? Can i simply write to this file? does it need the symlink made too? I simply want to hotwire things so they are aware that the device is online.
> 
> https://github.com/anatol/booster/blob/master/init/udev.go#L251C40-L251C67

Theoretically, you can manually write udev database under /run/udev to mimic what udev does. But, that's super fragile and we (and other projects like LVM and so on) cannot support that.

Why not to simply run udevd in your initrd? Your initrd already has many binaries for lvm, device mapper, and encrypted block device. I do not think systemd-udevd and .rules files are not so huge.

Without systemd, but with systemd-udevd, you can do something like the following. That should not be annoying.
```sh
# start udevd and wait for udevd being actually listening events
systemd-udevd --daemon
udevadm control --ping

# activate and decrypt block device or so, I guess what you already do in your script.

# wait for the block device being processed by udevd, (--settle option may be necessary. Not sure. Depends on the setup.)
udevadm wait /dev/mapper/SYMBOLIC_LINK_YOU_WANT

# kill udevd and cleanup unnecessary database
udevadm control --exit
udevadm info --cleanup-db
```
So, only few lines you need to add, hopefully.

Note, we have a build option for statically linking systemd-udevd with libsystemd-shared.so, and systemd-udevd itself is a symbolic link to udevadm.
So, installing systemd-udevd, udevadm, and .rules files should be not so complicated.

> I can't find any systemd matrix channel.

There are several links in our README.md.

> If you are looking for support, please contact our [mailing list](https://lists.freedesktop.org/mailman/listinfo/systemd-devel), join our [IRC channel #systemd on libera.chat](https://web.libera.chat/#systemd) or [Matrix channel](https://matrix.to/#/#systemd-project:matrix.org)

**Comment by desultory** [comment] 2024-08-24 00:03
> > I found this, is this what is required to signal to systemd that a deviece is online? Can i simply write to this file? does it need the symlink made too? I simply want to hotwire things so they are aware that the device is online.
> > https://github.com/anatol/booster/blob/master/init/udev.go#L251C40-L251C67
> 
> Theoretically, you can manually write udev database under /run/udev to mimic what udev does. But, that's super fragile and we (and other projects like LVM and so on) cannot support that.
> 

I think booster does this? 

> Why not to simply run udevd in your initrd? Your initrd already has many binaries for lvm, device mapper, and encrypted block device. I do not think systemd-udevd and .rules files are not so huge.
> 

I want to avoid this and im not even sure how I'd go about doing this. I think the effort required to properly include/run udev is greater than the effort required to make a few udev db entries. It would only need to make one saying the device is available, right?

> Without systemd, but with systemd-udevd, you can do something like the following. That should not be annoying.
> 
> ```shell
> # start udevd and wait for udevd being actually listening events
> systemd-udevd --daemon
> udevadm control --ping
> 
> # activate and decrypt block device or so, I guess what you already do in your script.
> 
> # wait for the block device being processed by udevd, (--settle option may be necessary. Not sure. Depends on the setup.)
> udevadm wait /dev/mapper/SYMBOLIC_LINK_YOU_WANT
> 
> # kill udevd and cleanup unnecessary database
> udevadm control --exit
> udevadm info --cleanup-db
> ```
> 
> So, only few lines you need to add, hopefully.
> 

Yes but i need to add a mechanism for properly pulling all udev dependencies, directories, etc, then run it correctly. It's using plain bash and i think it doesn't have job control im not sure what needs to be considered to run a proper "daemon"

> Note, we have a build option for statically linking systemd-udevd with libsystemd-shared.so, and systemd-udevd itself is a symbolic link to udevadm. So, installing systemd-udevd, udevadm, and .rules files should be not so complicated.
> 
> > I can't find any systemd matrix channel.
> 
> There are several links in our README.md.
> 
> > If you are looking for support, please contact our [mailing list](https://lists.freedesktop.org/mailman/listinfo/systemd-devel), join our [IRC channel #systemd on libera.chat](https://web.libera.chat/#systemd) or [Matrix channel](https://matrix.to/#/#systemd-project:matrix.org)

I'm in the libera and have been asking about this pretty often. I'm not _expecting_ help but it would be very nice, and I think i've been pretty persistent about trying to solve this and get info that could be used to help.

**Comment by desultory** [comment] 2024-08-24 00:04
WRT support, I think this deficiency has existed in the dm udev rules for more than a decade, or I think this is related at the least: https://bugs.gentoo.org/330651
