### ISSUE TITLE
ForwardToConsole doesn't seem to show kernel messages

### ISSUE THREAD

**Issue by yacoob** [systemd/systemd#5129] opened 2017-01-22 22:16 UTC
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

> Arch linux, installed with 2017.01.01, up to date as of 2017/01/22

### Steps to reproduce the problem

> add the following to `/etc/systemd/journald.conf.d/fwtty12.conf`:
> ```
> [Journal]
> MaxLevelConsole=debug
> TTYPath=/dev/tty12
> ForwardToConsole=yes
> ```

> restart journald to have it pick up new config

> press `alt-sysrq-h`

### Expected behaviour you didn't see

> a help message for magic sysrq should show up in the logs forwarded by journald to `tty12`

### Unexpected behaviour you saw

> no magic sysrq help message on `tty12`

The help message reaches journald, as it's visible when you do `journalctl -k` or `journalctl -a`. I don't really see any other console-related config options in `man journald.conf`.

**Comment by poettering** [comment] 2017-01-23 13:32
Yeah, we only forward syslog + native journal + stdout/stderr stuff to the console. After all the kernel forwards audit to kmsg internally anyway, and kmsg to to the console too. If we'd blindly copy that stuff to the console too, then the console would get all that stuff multiple times...

I am not sure we should change that, and probably should refer people to the printk level configuration instead, so that they can make sure sysreq stuff is printed to the console directly, without the detour through userspace.

**Comment by poettering** [comment] 2017-01-23 13:33
I made this now a documentation issue, as I don't think journald should change behaviour here, we should simply document this better.

**Comment by yacoob** [comment] 2017-01-23 21:07
Looks like it's a matter of expectations - I've assumed I'd get the same output as with normal `journalctl -f`. By default kernel logs end up on `/dev/console` which is the "current" console - so duplicates would only occur if your log level is set high enough *and* you're currently watching the target console. I think it's not unreasonable to forward everything.

**Comment by poettering** [comment] 2017-02-01 19:25
Duplicate of #2866 btw...

**Closed as completed by poettering** 2017-02-01 19:25 UTC
Labels: journal, documentation, duplicate
