### ISSUE TITLE
Avoid term "holdoff time", since it's source is unknown at first sight

### ISSUE THREAD

**Issue by guettli** [systemd/systemd#5473] opened 2017-02-27 15:31 UTC
### Submission type

  - [ X] Request for enhancement (RFE)

### systemd version the issue has been seen with

> systemd 229

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

>Ubuntu

There are at least two question like "What is the meaning of holdoff time over in systemd services?" on ServerFault.

Why do you use "holdoff time"?

Why not use "RestartSec"?

**Comment by sztanpet** [comment] 2017-02-27 15:37
duplicate of #5472

**Comment by poettering** [comment] 2017-02-27 19:46
Closing as duplicate of #5472

**Closed as completed by poettering** 2017-02-27 19:46 UTC
Labels: documentation, duplicate
