### ISSUE TITLE
"MACAddress=" has no effect in .network, and .network has no effect when .link exists.

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#1032] opened 2015-08-25 16:21 UTC
systemd 224
linux 4.1.6

Running the "forcedeth" driver for an NVIDIA  MCP67 Ethernet device, the journal has

Invalid MAC address detected: 00:00:00:00:00:00
Using random MAC address: 9a:04:45:58:75:7a

So, am trying to use "MACAddress=" in a .network file for the device, but to no effect.  As reported by "ip addr", there is either the "random" address, or the "persistent" address, but never the "MACAddress=" address with only a .network file.  Adding a .link file applies "MACAddress=", but then the .network file is ignored, and the network interface is not configured.

systemd.network(5) says only:

<pre>
[LINK] SECTION OPTIONS
MACAddress=
           The hardware address.
</pre>

systemd.link(5) is slightly more forthcoming:

<pre>
[LINK] SECTION OPTIONS
 MACAddress=
           The MAC address to use, if no "MACAddressPolicy=" is specified.
</pre>

It is unclear whether the .network file or the .link file has priority if there is a conflict in "MACAddress=".
Which file has priority for conflicting "MACAddress="?

Reading

<pre>Note that a default file 99-default.link is shipped by the system, any user-supplied
 .link should hence have a lexically earlier name to be considered at all.
</pre>

 and then reading

<pre> 
MACAddressPolicy=
    The policy by which the MAC address should be set. The available policies are:
"persistent"
...  Otherwise, a new MAC address is generated which is guaranteed to be the same on
 every boot for the given machine and the given device, but which is otherwise random.
...
"random"
...
</pre>

"random" seems to leave in place the kernel-assigned random MAC address.

"persistent" seems to apply a persistent but random MAC address, just as the documentation says, but then, what is the point of having a "MACAddress=" setting that has no effect?  And then, how can the MAC address be set?

Creating a .link file, in addition to the .network file, results in "MACAddress=" taking effect, but then with no effect from the .network file, and no network configuration!

And, incidentally, the source of this "persistent" MAC address is an apparent mystery and seems to be undocumented.

Something is not right here, but I cannot say what the original intent might be.  How is this suppose to work?

It seems that both the .link file configuration and the .network file configuration should be applied, so that a working network interface is configured.  It also seems that the .network "MACAddress=" setting should over-ride the .link "MACAddressPolicy=" setting.  It also seems that there should not be two, possibly conflicting, ways to set "MACAddress=", in both the .network file and the .link file.  Alternatively, the .network file should over-ride the .link file, when the settings conflict.

Currently, it seems not possible to automatically configure a working network interface with a user-defined MAC address using systemd, without resorting to the "ip" commands.

**Comment by poettering** [comment] 2015-08-25 16:25
@teg is probably the one to look into this one!

**Comment by krogon-intel** [comment] 2015-11-25 15:52
@teg any comment regarding that?

**Comment by poettering** [comment] 2019-02-26 15:24
let's close this as duplicate of #6696, since it appears to be the same issue (yeah, the other one is newer, but it has a more descriptive title, so let's keep that one.)

Duplicate of #6696

**Closed as completed by poettering** 2019-02-26 15:24 UTC
Labels: network, duplicate
