### ISSUE TITLE
wiki: please update D-Bus related wiki page

### ISSUE THREAD

**Issue by kayrus** [systemd/systemd#2562] opened 2016-02-09 11:40 UTC
[This wiki](http://www.freedesktop.org/wiki/Software/systemd/dbus/) page contains info:

```
Read access is generally granted to all clients, but changes may only be made by privileged clients. PolicyKit is not used by this service, and access controlled exclusively via the D-Bus policy enforcement.
```

As I know D-Bus already uses polkit. Can someone update this text?

/cc @poettering

**Comment by poettering** [comment] 2016-02-10 20:49
Duplicate of #1042

**Comment by keszybz** [comment] 2020-04-12 16:47
I reopened this because it is a specific thing to fix.

**Closed as completed** 2020-04-17 21:40 UTC
Labels: documentation
