### ISSUE TITLE
Resolved queries fail with no address and IPv6 DHCP-PD

### ISSUE THREAD

**Issue by andrewbaxter** [systemd/systemd#33665] opened 2024-07-08 15:53 UTC
### systemd version the issue has been seen with

255.6

### Used distribution

NixOS

### Linux kernel version used

6.6.33

### CPU architectures issue was seen on

ia64

### Component

systemd-networkd, systemd-resolved

### Expected behaviour you didn't see

`resolvectl query google.com` should return IP addresses.

### Unexpected behaviour you saw

`resolvectl` errors with message "No appropriate name servers or networks for name found"

### Steps to reproduce the problem

My network is as follows: `eth0` is WAN-side, with `DHCP=ipv6`. LAN-side is a bridge with `eth1` attached for my local network and `br0` has `DHCPPrefixDelegation=yes`.

Prefix delegation completes and `br0` is assigned an address, routes are set up, etc.  The prefix delegation DHCP response provided two DNS servers - these are shown for `eth0` in `resolvectl` as well as `networkctl status --json pretty eth0`.  `br0` has no DNS servers per `resolvectl` and `networkctl status`.

WAN-side, the ISP (Biglobe)'s RA has no PIO and the DHCP server doesn't respond to IA_NA so `eth0` doesn't have an address.  I set `UseAddress=no` on `eth0` and now it at least shows as `configured` but it's still `degraded`.

I'm afraid I might be confused about how some things work, but my guess at this point is that `resolvectl` is trying to send the query via `eth0` but `eth0` doesn't have a routable ip address so that fails (eth0 is "not appropriate" using above language?). `br0` has a routable ip address but no DNS servers configured so `resolvectl` doesn't consider it.

I guess my expectation would be that `br0` would get DNS servers from the DHCP-PD messages.  But either
1. The documentation for `DHCPPrefixDelegation` says that the interface will be assigned an address from the prefix but mentions nothing about DNS servers, so the fact that that `br0` doesn't get DNS servers is by design or
2. The interface _should_ get DNS servers assigned, but isn't, maybe related to https://github.com/systemd/systemd/issues/30945

I'm guessing 1 is correct though, because on a system where `eth0` gets a routable address just sending the DNS queries out `eth0` would be simplest.

**Comment by yuwata** [comment] 2024-07-31 01:15
Yeah, we should definitely announce DNS servers to downstream. Unfortunately, that's not currently supported. Switching to RFE label.

**Comment by yuwata** [comment] 2024-07-31 01:57
duplicate of #30945.

**Closed as completed by yuwata** 2024-07-31 01:57 UTC
Labels: RFE 🎁, network, resolve, dhcp, duplicate
