### ISSUE TITLE
Disable service activation from dbus-broker while dbus-broker.service is deactivating

### ISSUE THREAD

**Issue by lclgo** [systemd/systemd#26799] opened 2023-03-14 02:46 UTC
### Component

systemd

### Is your feature request related to a problem? Please describe

I'm using `systemctl isolate reboot.target` to reboot the system. But since I changed the default D-Bus daemon from dbus-daemon to dbus-broker, the reboot process is always terminated. This is because NetworkManager.service will activate NetworkManager-dispatcher.service when it is stopped, and this `start` job makes many `stop` jobs canceled.

I'm curious why this `NetworkManager-dispatcher.service start` job was not generated when I use dbus-daemon, and find systemd will refuse this job when `dbus-daemon` is shutting down in `signal_activation_request()`. But this doesn't work on dbus-broker, because dbus-broker uses `StartUnit` methon_call directly instead of `ActivationRequest` signal. See <https://github.com/bus1/dbus-broker/blame/main/NEWS.md#L693>. systemd seems doesn't have similar code for dbus-broker.

### Describe the solution you'd like

I want systemd to refuse the service activation while dbus-broker.service is deactivating.

### Describe alternatives you've considered

I have considered 2 alternatives:

1. Broadcasting signal `DBusDeactivating` so dbus-broker knows it will be stopped, and dbus-broker can refuse the `StartUnit` message.

2. Check the state of dbus-broker and the the type of service waitting to be activated, if dbus-broker is deactivating, systemd refuses to activate `Type=dbus` services.

**Comment by poettering** [comment] 2023-03-15 10:35
> This is because NetworkManager.service will activate NetworkManager-dispatcher.service when it is stopped, and this `start` job makes many `stop` jobs canceled.

Hmm? it does what? it starts new services during shutdown? it really shouldn't do that. This is what should be fixed.

**Comment by poettering** [comment] 2023-03-15 10:36
> 2\. Check the state of dbus-broker and the the type of service waitting to be activated, if dbus-broker is deactivating, systemd refuses to activate `Type=dbus` services.

this sounds better to me actually. but yuck, nm shouldn't do what it is doing. starting up a lot of infra when shutting down, reversing the shutdown transaction is just a bad idea.

**Closed as completed** 2023-05-08 21:09 UTC
Labels: RFE 🎁, pid1

**Comment by ihuguet** [comment] 2025-01-17 09:30
Hi. NetworkManager developer here.

First, I would like to know what was actually the problem before this change. What stop jobs were cancelled and what problems did that cause exactly?

Second, I'd like to say that activating services during shutdown does have legitimate use cases. D-Bus activation is meant, among other purposes, to allow daemons with low activity to sleep until they are needed for something. In the case of NetworkManager-dispatcher, it is used to allow users to react to certain events like interface up or down with custom scripts. Users might need it to do "cleanup" actions.

I understand that systemd needs to do something to enforce a gradual shutdown of the running services. However, this limitation causes that D-Bus activated services cannot be used reliably any more. It is almost impossible for applications that depends on external services much to guarantee that they are not going to need any communication with any of those services during shutdown.

If applications cannot rely on that, the only alternative is not to depend on D-Bus activated services at all, and that's not always possible because the other services configuration might be maintained by completely different people, maybe even on how different distributions choose to configure their unit files.

What the solution can be?

See:
- https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/1643
- https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/1264

**Comment by Geass-LL** [comment] 2025-01-18 03:05
> Hi. NetworkManager developer here.
> 
> First, I would like to know what was actually the problem before this change. What stop jobs were cancelled and what problems did that cause exactly?
> 
> Second, I'd like to say that activating services during shutdown does have legitimate use cases. D-Bus activation is meant, among other purposes, to allow daemons with low activity to sleep until they are needed for something. In the case of NetworkManager-dispatcher, it is used to allow users to react to certain events like interface up or down with custom scripts. Users might need it to do "cleanup" actions.
> 
> I understand that systemd needs to do something to enforce a gradual shutdown of the running services. However, this limitation causes that D-Bus activated services cannot be used reliably any more. It is almost impossible for applications that depends on external services much to guarantee that they are not going to need any communication with any of those services during shutdown.
> 
> If applications cannot rely on that, the only alternative is not to depend on D-Bus activated services at all, and that's not always possible because the other services configuration might be maintained by completely different people, maybe even on how different distributions choose to configure their unit files.
> 
> What the solution can be?
> 
> See:
> 
> * https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/1643
> * https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/1264

Hello, the issue happened quite some time ago, so my memory might be a bit unclear.

1. When executing the reboot command, the stop job will not be canceled. To reproduce this issue, you need to run `systemctl isolate reboot.target`, because systemd uses different job types for these two commands.
2. Because NetworkManager-dispatcher.service depends on dbus-broker.service, when starting NetworkManager-dispatcher.service, systemd needs to start dbus-broker.service. This start operation cancels the stop process of the services that dbus-broker.service depends on, ultimately resulting in `systemctl isolate reboot.target` being unable to reboot the system.
3. I think if NetworkManager-dispatcher.service indeed needs to be activated during shutdown, dependencies should be added to ensure that NetworkManager-dispatcher.service starts and completes its tasks, then shuts down together with NetworkManager.service, before finally ensuring that dbus.service can be shut down properly.
