### ISSUE TITLE
coredumpctl loses coredumps that are on disk

### ISSUE THREAD

**Issue by jaymzh** [systemd/systemd#17910] opened 2020-12-08 23:54 UTC
**systemd version the issue has been seen with**
> 246 and 237

I'm currently using 237 but the very kind @davide125 reproduced this on the bleeding edge 246.

**Used distribution**
 > Ubuntu 20.18 (237) and CentOS8 (246, though it's not the distro systemd it's backported 246, obv)

**Linux kernel version used** (`uname -a`)
 > 5.0.0 (237) 4.16.18 (246)

**CPU architecture issue was seen on**
> x86_64

**Expected behaviour you didn't see**

Given a config like:

```
[Coredump]
ExternalSizeMax = 128G
Storage=External
```
Cores quite-rightly end up in `/var/lib/systemd/coredump`:
```
root@vcrs-r5009:/var/lib/systemd/coredump# ls
core.python.1000.aa7cdf86c0fb451ba0e5189acc31d4e0.11125.1607454190000000.lz4
core.python.1000.aa7cdf86c0fb451ba0e5189acc31d4e0.16528.1607451235000000.lz4
core.python.1000.aa7cdf86c0fb451ba0e5189acc31d4e0.17743.1607451261000000.lz4
core.python.1000.aa7cdf86c0fb451ba0e5189acc31d4e0.33469.1607453813000000.lz4
core.python.1000.aa7cdf86c0fb451ba0e5189acc31d4e0.37219.1607454033000000.lz4
core.python.1000.aa7cdf86c0fb451ba0e5189acc31d4e0.4710.1607454104000000.lz4
core.python.1000.aa7cdf86c0fb451ba0e5189acc31d4e0.7873.1607464785000000.lz4
core.python.1000.aa7cdf86c0fb451ba0e5189acc31d4e0.8908.1607454154000000.lz4
core.roslaunch.1000.aa7cdf86c0fb451ba0e5189acc31d4e0.20893.1607464795000000.lz4
core.sleep.0.aa7cdf86c0fb451ba0e5189acc31d4e0.30818.1607466109000000.lz4
core.sleep.0.aa7cdf86c0fb451ba0e5189acc31d4e0.40379.1607469127000000.lz4
core.sleep.0.aa7cdf86c0fb451ba0e5189acc31d4e0.9214.1607468390000000.lz4
core.sleep.1000.aa7cdf86c0fb451ba0e5189acc31d4e0.32547.1607466146000000.lz4
core.sleep.8012.aa7cdf86c0fb451ba0e5189acc31d4e0.31677.1607466126000000.lz4
```
But 
`coredumpctl list` doesn't seem most of these:
```
root@vcrs-r5009:/var/lib/systemd/coredump# coredumpctl list
TIME                            PID   UID   GID SIG COREFILE  EXE
Tue 2020-12-08 15:12:07 PST   40379     0     0   3 present   /bin/sleep
```

It seems like this is because the metadata for the cores are actually stored in the journal. For those of use who forward journal entries to syslog, we keep a very small volatile journal, so as soon as the metadata is pushed out of the journal (which can be just a few minutes).

It seems like:
1. When coredumps are being stored on disk, so should the metadata
2. If for some reason that cannot be done, then this behavior should be documented (it was not clear to me from many reads of coredumpctl coredump.conf and systemd-coredump man pages).

**Steps to reproduce the problem**

Set your journal to something very small like 10M:

```
[Journal]
ForwardToSyslog = true
RuntimeMaxUse = 10M
Storage = volatile
```
Set your coredump.conf to store things on disk:

```
[Coredump]
ExternalSizeMax = 128G
```

make a core:
```
sleep 100
^\
```

run `coredumpctl list` - see the core.
Wait 10 minutes, run `coredumpctl list` again, don't see core.

**Comment by poettering** [comment] 2020-12-09 11:15
Hmm? So you pick a configuration that loses data early, and then you are not happy with that it does it? 

It it's a local configuration issue. Allow the journal to keep its logs for longer and it can report coredumps for longer.

I am inclined to close this as local configuration issue.

**Comment by bluca** [comment] 2020-12-09 11:52
> Hmm? So you pick a configuration that loses data early, and then you are not happy with that it does it?
> 
> It it's a local configuration issue. Allow the journal to keep its logs for longer and it can report coredumps for longer.
> 
> I am inclined to close this as local configuration issue.

I concur, it is working as designed. A PR to improve the systemd-coredump manpage to specify that metadata is stored in the journal even if cores are stored on disk would be a welcome improvement. There are many references to the journal already, but it is not spelled out explicitly as far as I can see.

**Comment by jaymzh** [comment] 2020-12-09 17:39
Come on Lennart, if two *contributors* to systemd both read all the docs and *still* didn't understand the behavior, something is wrong. If you would like to say the bug is in the docs, that's fine. However, one would argue that changing `Storage=journal` to `Storage=persistent` implies, ya know, that core information is... _**persistent**_. And the reality of it is, if I have _literally any_ limits on my journal, then `Storage=persistent` is misleading. Turns out that coredumpctl will just forget about things on disk over time, even though they are still there.

It's pretty reasonable for one to want to rotate logs and corefiles at different levels and in different ways, and the fact that when my logs get rotated, coredumpctl just simply forgets about things on disk is super intuitive.

I would argue that `Storage=persistent` should mean that systemd-coredump stores everything on disk, outside of the journal. If not, there should at least be a `Metadata=persistent` option. And barring that, there should be a massive warning in the man page that says `Setting Storage=persistent does not store metadata on disk, that remains in the journal and as those journal entries are rotated coredumpctl will report there are no cores on disk. However, you can recover them manually in /var/lib/systemd/coredump`.

And @bluca the *only* references to the journal in coredump.conf are under `Storage=` where it implies you're moving the storage out of the journal.

**Comment by bluca** [comment] 2020-12-09 17:52
> And @bluca the only references to the journal in coredump.conf are under Storage= where it implies you're moving the storage out of the journal.

Well, for example coredumpctl's manpage says:

>            It's worth noting that different restrictions apply to data saved in the journal and core dump files
>            saved in /var/lib/systemd/coredump, see overview in systemd-coredump(8). Thus it may very well happen
>            that a particular core dump is still listed in the journal while its corresponding core dump file has
>            already been removed.

If having metadata without cores is possible, it follows that having cores without metadata is also possible. But having said that, improvements to the documentation to make it more intuitive and readable and accurate are always welcome: please send a PR and we'll review it and merge it. It's entirely possible that the manpages are incomplete or structured in a way that is confusing to some users. Documentation is hard.

Regarding storing metadata outside the journal, that's just not possible with the current implementation - there's no facility to do that. And I'm not so sure we'd want to invent a new metadata storage format, with all that entails, just for this corner case. If you feel strongly about that, please feel free to open an RFE indicating how you'd implement it and so on.

**Comment by jaymzh** [comment] 2020-12-09 18:07
>       It's worth noting that different restrictions apply to data saved in the journal and core dump files
>       saved in /var/lib/systemd/coredump, see overview in systemd-coredump(8). Thus it may very well happen
>       that a particular core dump is still listed in the journal while its corresponding core dump file has
>       already been removed.

The difference there is that `coredumpctl` tells you "hey I don't have that corefile" when you try to access it. You get an error that makes sense. As opposed to "I JUST had a coredump, why is it gone" and then quite a while later, realizing it's not gone.

Perhaps an option here is just having `coredumpctl` do a `readdir()` on `/var/lib/systemd/coredump` and list those as available even if it has less info about them?

**Comment by bluca** [comment] 2020-12-09 18:54
That sounds fine in principle. I'd suggest to start with the documentation as the first thing, since that should be straightforward.

**Closed as completed** 2021-03-01 14:14 UTC
Labels: documentation, coredump, not-a-bug
