### ISSUE TITLE
systemd-networkd fails with large route table

### ISSUE THREAD

**Issue by timbuchwaldt** [systemd/systemd#11575] opened 2019-01-27 12:50 UTC
**systemd version the issue has been seen with**
237-3ubuntu10.11

**Used distribution**
 Ubuntu 18.04

**Expected behaviour you didn't see**
`service systemd-networkd restart` successfully restarting the network 

**Unexpected behaviour you saw**
 `Could not drop route: Connection timed out` / `Could not join netdev: Connection timed out`

**Steps to reproduce the problem**
Load a full BGP table / have bird running synching multiple full tables and execute `systemctl restart systemd-networkd` with an unrelated / no change.

We consistently saw systemd-networkd restart again and again, never successfully bringing up the network after the initial fault. 
Stopping both `bird` and `bird6`, then restarting seems to work but is highly undesirable as this always introduces huge routing changes internally and externally.

**Comment by yuwata** [comment] 2019-01-27 12:58
Could you provide .network and .netdev files?

**Comment by timbuchwaldt** [comment] 2019-01-27 13:03
Sure, here you go:  https://dsh.re/edecc

Please note they are slightly redacted as they would leak internal company stuff, and wireguard interfaces of course also have keys :D

**Comment by yuwata** [comment] 2019-01-27 15:01
@timbuchwaldt Hmm, I cannot reproduce the error with the provided files and current git master... Do you reproduce the issue with the redacted files?

**Comment by timbuchwaldt** [comment] 2019-01-27 15:05
@yuwata did you load ~1M routes? I haven't worked on reproducing yet, I hope to start that tomorrow.

I have a general hunch of what might be going on: We have ~1.000.000 routes distributed across two interfaces, with a next hop reachable via a device route. In case `systemd-networkd` tries to deactivate this device route all of those 1M routes have to be discarded. If this happens bird would probably add alternate routes in case it has some and make the problem even worse.

**Comment by yuwata** [comment] 2019-01-27 15:06
Ah, I missed the explanation about `bird` and `bird6` in the first comment...

**Comment by yuwata** [comment] 2019-01-27 18:03
Please also debug logs of `systemd-networkd`.

**Comment by timbuchwaldt** [comment] 2019-01-27 18:21
Here you go: https://tim.chaos.cloud/4Er9m2RV/networkdlog.

**Comment by yuwata** [comment] 2019-01-27 18:31
> Here you go: https://tim.chaos.cloud/4Er9m2RV/networkdlog.

404...

**Comment by timbuchwaldt** [comment] 2019-01-27 18:32
Haha... the `.` at the end is part of the URL, thx GitHub. https://dsh.re/c1c18

**Comment by yuwata** [comment] 2019-01-27 18:39
As a workaround, please try to specify the following in the corresponding .network files:
```
[DHCP]
CriticalConnection=true
```
Then, routes are not dropped during the startup.

**Comment by timbuchwaldt** [comment] 2019-01-27 21:34
@ssahani I can't see activity in the kernel logs around 18:29 - can you point me to where you can see code 110?


What I can see in the kernel that looks slightly related is the following, although on another machine (same setup and issue though, just missing the eno7 10Gbit NIC + config):
```
Jan 26 18:22:58 hostname kernel: netlink: 'systemd-network': attribute type 5 has an invalid length.
Jan 26 18:22:58 hostname kernel: netlink: 'systemd-network': attribute type 5 has an invalid length.
Jan 26 18:22:58 hostname kernel: netlink: 'systemd-network': attribute type 5 has an invalid length.
Jan 26 18:22:58 hostname kernel: netlink: 'systemd-network': attribute type 5 has an invalid length.
Jan 26 18:22:58 hostname kernel: netlink: 'systemd-network': attribute type 5 has an invalid length.
```

**Comment by yuwata** [comment] 2019-01-27 21:36
The error log is fixed by 7d0b26a027118ca063780421cb31c74e9d2664ee.

**Comment by timbuchwaldt** [comment] 2019-01-27 22:42
> > The error log is fixed by [7d0b26a](https://github.com/systemd/systemd/commit/7d0b26a027118ca063780421cb31c74e9d2664ee).
> > 110 means ETIMEDOUT.
> 
> yes right. But why his logs have full of those ?
> 
I'm running a version that is older than the fix and I have wireguard in my configuration, so this adds up and smells an awful lot like a red herring.

> > Jan 26 18:22:58 hostname kernel: netlink: 'systemd-network': attribute type 5 has an invalid length.
> 
> Can you come up with a miniman reproducer that networkd is doing this . Rather than making wild guesses. Totally looks to me a type error ie a attribute do not have right length,

I will reproduce my setup in a VM ASAP, I hope tomorrow. It should be trivial to simulate `bird` adding routes to the kernel on a single host and have have some virtual NICs to play with.

**Comment by timbuchwaldt** [comment] 2019-03-12 10:53
I finally found time to reproduce this issue in our network.
Adding `CriticalConnection=true` indeed fixes the issue when applied to the connections that carry BGP. The CPU usage of systemd-networkd while restarting our routeserver is still is a little high, but at least our system is not unresponsive anymore after reloading our config.

**Closed as completed** 2019-06-06 23:59 UTC
Labels: network, needs-reporter-feedback ❓

**Comment by rfc1036** [comment] 2021-05-03 09:07
I am experiencing this with 30509 IPv6 routes and 81022 IPv4 routes, Debian systemd 247.3-5 and KeepConfiguration=static configured on all interfaces.

**Comment by OtherSystems** [comment] 2021-08-30 17:46
Experiencing this with a full IPv4 routing table (840544 entries) on debian buster aswell

**Comment by tedb** [comment] 2022-02-28 17:17
For me, on a system with a large route table, the systemd-networkd high memory usage was fixed by https://github.com/systemd/systemd/pull/14858.  In `/etc/systemd/networkd.conf`, under `[Network]`, I set `ManageForeignRoutes=n`.
