### ISSUE TITLE
Network Routes order changes after reloading config change of eth0

### ISSUE THREAD

**Issue by raviteja-b** [systemd/systemd#32253] opened 2024-04-12 17:41 UTC
### systemd version the issue has been seen with

255

### Used distribution

GNU/Linux

### Linux kernel version used

6.5.4-713e4ea-00113-g713e4ea49106

### CPU architectures issue was seen on

arm

### Component

systemd-networkd

### Expected behaviour you didn't see

Expected behaviour with two ethernet interfaces registered with systemd-networkd with configuration files is changing eth0 or eth1 configurations should not change routes order of eth0& eth1 interfaces.

### Unexpected behaviour you saw

there are two ethernet interfaces registered with systemd-networkd with configuration files.
while reloading after only eth0 interface configuration, changes  routes order of eth0 & eth1 interfaces 
Which makes eth0 interface route not reachable while eth1 private default route is on top routing table
seeing this behaviour consistently

### Steps to reproduce the problem

```
1. configure two ethernet interfaces with  one private(eth1) and one public(eth0) subnet ip addresses.
2. observe routes order using route command (eth0 route will be on top and eth1 route will be 2nd in table)
2. change other network configuration on eth0, like dns, ntp configuration and reload systemd networkd.
    since only eth0 config file updated, only eth0 interface configuration will be reloaded by systemd.
3. observe routing table again. routes order changes 
5. eth1 route will be on top of routing table and eth0 IP address is no longer reachable.
```

Here routing table before changing configuration & both IP addresses reachable.

route
Kernel IP routing table
Destination  Gateway         Genmask         Flags Metric Ref    Use Iface

default         10.x.y.1      0.0.0.0         UG    1024   0        0 eth0
default         192.x.1.1     0.0.0.0         UG    1024   0        0 eth1

Here is routes order after reloading systemd-network after changing eth0 configuration 
route
Kernel IP routing table
Destination     Gateway         Genmask   Flags Metric Ref    Use Iface

default         192.x.1.1     0.0.0.0      UG    1024   0        0 eth1
default         10.x.y.1        0.0.0.0      UG    1024   0        0 eth0

### Additional program output to the terminal or log subsystem illustrating the issue
since only eth0 configuration changed, only eth0 configuration is getting reloaded by systemd-networkd and route changes 

Apr 12 07:38:36  systemd-networkd[218]: eth0: Reconfiguring with /etc/systemd/network/eth0.network.
Apr 12 07:38:36  systemd-timesyncd[262]: Network configuration changed, trying to establish connection.
Apr 12 07:38:42 systemd-timesyncd[262]: Network configuration changed, trying to establish connection.

**Comment by yuwata** [comment] 2024-04-12 19:26
First of all, please use `ip route` command rather than old mostly deprecated `route` command.

Why you configure the default route for the private network (eth1)? That sounds not necessary I guess.
If you configure it manually, then just drop it.
If the default route is configured automatically with DHCP, then set `UseGateway=no`.

The issue should be misconfiguration, and predictable ordering of routes with the same destination is not supported. Closing.

**Closed as not planned by yuwata** 2024-04-12 19:26 UTC
Labels: network, not-a-bug

**Comment by raviteja-b** [comment] 2024-04-13 01:52
Basically when both ethernet interfaces configured with different subnet IP addresses and gateways
does each ethernet interfaces is expected to be reachable with IP address right?
it works initially but whenever there is reload of configuration then noticed route orders and it one of interface is not reachable.

Systemd support configuring Default gateway on each interface, order of Default gateway matters and it does impact network configuration if order changes.
is there anyway for systemd to reload configuration of both interfaces everytime there is a configuration change?

**Comment by yuwata** [comment] 2024-04-13 02:13
> Basically when both ethernet interfaces configured with different subnet IP addresses and gateways
> does each ethernet interfaces is expected to be reachable with configured IP address right?

Cannot follow. What's the configuration of your network? You said eth1 is for private network. Then I think the default gateway for the private network is not necessary. Why you think it's necessary? Have you tried to disable the default gateway on eth1?

**Comment by raviteja-b** [comment] 2024-04-13 03:02
eth1 being on private network is one case, I believe gateway needs to be configured for private network.
without gateway configuration private network IP address is not reachable.

I have noticed  this issue of routes order change with both interfaces configured with different subnet static public IP addresses and corresponding gateway.

**Comment by yuwata** [comment] 2024-04-13 03:07
> eth1 being on private network is one case, I believe gateway needs to be configured for private network because without gateway configuration private network IP address is not reachable.

Why? Have you tested? Please try, anyway...

**Comment by raviteja-b** [comment] 2024-04-13 03:15
> > eth1 being on private network is one case, I believe gateway needs to be configured for private network because without gateway configuration private network IP address is not reachable.
> 
> Why? Have you tested? Please try, anyway...

yes private network configuration I have tried many times, without gateway configuration its not working

**Comment by yuwata** [comment] 2024-04-13 03:52
Now eth1 has default gateway, and eth0 does not... It seems you edited a wrong .network file?

Anyway, this is definitely not a bug in systemd-networkd. But your misconfiguration or misdesign of network.

**Comment by raviteja-b** [comment] 2024-04-13 04:13
in the configuration I have shared above, eth0 on private network and eth1 on public network.
so eth1 has default gateway and I skipped gateway configuration for eth0 as you mentioned. 
do you mean say that network application needs to add check if configured IP is private network or public network and based on that it needs to configure gateway in the .network file?

**Comment by yuwata** [comment] 2024-04-13 04:28
You have not answered my question: what's the entire network configuration? I cannot understand what you want to achieve.

**Comment by raviteja-b** [comment] 2024-04-13 04:53
This system  is connected to a another Management system over DHCP network on eth1 and eth0 configured is in static network to provide access to the system in the given network

**Comment by yuwata** [comment] 2024-04-13 06:03
> This system is connected to a another management system over DHCP network on eth1. eth0 configured is in static network IP to have access to the system in the given network.

Which one is private? In what sense, the network is private (or public) ??

I guess something like the following, no?
```
Internet ) --- ( router ) --- 192.168.1.0/24 --- ( The host ) --- 10.5.5.0/24 --- ( other hosts in 'private' network )
```
Unless first you clarify such info, I cannot answer anything...


> I wanted to understand few points
> 
>     1. why network routes orders change while reloading eth0 configuration? is there any way to follow same route order for default gateways, each interfaces has it owns default gateway.

That's simply not supported. Controlling network routing with multiple default gateway by their ordering stored in the kernel is simply broken and bad idea. That does not work anyway, even if you use any other networking daemon.

>     2. how does private IP address works without gateway configured?

There is a prefix route (as you can see `10.5.5.0/24 dev eth0 scope link  src 10.5.5.x`). That should be enough for accessing nodes in the private network. Of course, that's based on my guess about your network configuration in the above. If that's incorrect, the prefix route may not be enough. So, anyway, please please provide detailed information, if you want to get clear answer.

Also, please do not hide or cut the result of `ip route`, except for the global address. You chop, e.g. `proto`, `metric`, and so on, right? These are important to understand your situation. Please do not.

**Comment by raviteja-b** [comment] 2024-04-15 07:48
@yuwata I did not chop any information, I just put x,y in IP address info, that's all.
anyways the major I am facing is with two interfaces configured with static addresses on different subnet and each interface has got default gateway configured.

**Comment by raviteja-b** [comment] 2024-04-15 08:10
Here is details of configuration where both interfaces has static IP addresses configured on different subnet.

1. Configured IP address on eth0 interface first then configured IP address on eth1 interface later

```
cat /etc/systemd/network/00-system-eth0.network 
[DHCPv4]
SendHostname=true
UseHostname=true
UseDomains=true
UseDNS=true
UseNTP=true
ClientIdentifier=mac
[IPv6AcceptRA]
DHCPv6Client=false
[DHCPv6]
UseHostname=true
UseNTP=true
UseDomains=true
UseDNS=true
[Network]
Gateway=9.3.x.1
Address=9.3.x.122/24
NTP=time.google.com
DHCP=false
IPv6AcceptRA=false
DNS=9.3.x.200
LinkLocalAddressing=yes
[Link]
MACAddress=08:xx:ef:xx:00:yy
[Match]
Name=Eth0

cat  /etc/systemd/network/00-bmc-eth1.network 
[DHCPv4]
SendHostname=true
UseHostname=true
UseDomains=true
UseDNS=true
UseNTP=true
ClientIdentifier=mac
[IPv6AcceptRA]
DHCPv6Client=true
[DHCPv6]
UseHostname=true
UseNTP=true
UseDomains=true
UseDNS=true
[Network]
Gateway=10.5.x.1
Address=10.5.x.11/24
NTP=time.google.com
DHCP=ipv6
IPv6AcceptRA=true
LinkLocalAddressing=ipv6
[Link]
MACAddress=08:xx:xx:xx:00:y
[Match]
Name=Eth1
```

```
ip route
default via 9.3.x.1 dev eth0 
default via 10.5.5.1 dev eth1 
9.3.x.0/24 dev eth0 scope link  src 9.3.x.122 
10.5.5.0/24 dev eth1 scope link  src 10.5.5.11 
169.254.0.0/16 dev eth0 scope link  src 169.254.85.38  metric 2048 
```

2. Modify network configuration on eth0 interface, Enable DHCPv6 on eth0 interface

route order changes immediately after reloading eth0 interface configuration with enabling DHCPv6
IP route order changes after enabling DHCP v6 on eth0 interface.

```
ip route
default via 10.5.5.1 dev eth1 
default via 9.3.x.1 dev eth0 
9.3.x.0/24 dev eth0 scope link  src 9.3.x.122 
10.5.5.0/24 dev eth1 scope link  src 10.5.5.11 
169.254.0.0/16 dev eth0 scope link  src 169.254.85.38  metric 2048 
```

I see IP address 9.3.x.122  on eth0 interface is not reachable and eth1 interfaces IP address on eth1 reachable 10.5.5.11

**Comment by yuwata** [comment] 2024-04-15 08:53
Please provide the entire network configuration something like the following:
> ```
> Internet ) --- ( router ) --- 192.168.1.0/24 --- ( The host ) --- 10.5.5.0/24 --- ( other hosts in 'private' network )
> ```

Otherwise, I cannot understand why the two default gateways are necessary...

**Comment by raviteja-b** [comment] 2024-04-22 13:28
@yuwata here is how networks connected hosts
     -----------------------------
     |    Lab network  with routers  |   - connected to lab network via switch  to  -------eth0-------> [HOST]
     -----------------------------           [192.168.1.0]
     
     ---------------------------------  ---    direct point to point link to eth1
     | LAN network with connected to eth1 |. ---------------------------------> eth1 -----> [HOST]
     ---------------------------------  ---                10.5.5.1

**Comment by raviteja-b** [comment] 2024-04-23 11:37
Route order keeps changing after reloading systemd-networkd configuration which has impact on eth0/eth1 network since routes work based route order.

this issue can be simply recreate by configuring two interfaces on any system with 
eth0 on one network IP and eth1 on another IP with different subnet.
only route which on top of routing table picks up and while reloading systemd-networkd again route order change which impacts network interfaces 
I think systemd should provide some solutions to this issue.

**Comment by yuwata** [comment] 2024-04-24 04:21
> @yuwata here is how networks connected hosts
> 
> ```
>      ---------------------------
>    |    Lab network  with routers  |  --Connected to lab network via switch  to  --eth0--> [HOST]
>    -----------------------------                        [192.168.1.0]
>    
>    -------------------------------       connected LAN network to eth1
>    | LAN network connected to eth1 |. ---------------------------------> eth1 ----> [HOST]
>    ------------------------------                      [10.5.5.1] 
> ```

Which network has the global internet connection?

BTW, this is not a right place to support your case like that.
As I said, this is a misconfiguration of .network file or misdesign of entire networking.
Please use our matrix channel https://matrix.to/#/#systemd-project:matrix.org .

**Comment by raviteja-b** [comment] 2024-04-24 06:01
> > @yuwata here is how networks connected hosts
> > ```
> >      ---------------------------
> >    |    Lab network  with routers  |  --Connected to lab network via switch  to  --eth0--> [HOST]
> >    -----------------------------                        [192.168.1.0]
> >    
> >    -------------------------------       connected LAN network to eth1
> >    | LAN network connected to eth1 |. ---------------------------------> eth1 ----> [HOST]
> >    ------------------------------                      [10.5.5.1] 
> > ```
> 
> Which network has the global internet connection?
> 
> BTW, this is not a right place to support your case like that. As I said, this is a misconfiguration of .network file or misdesign of entire networking. Please use our matrix channel https://matrix.to/#/#systemd-project:matrix.org .

none of network has global internet connection, this is our global lab network

**Comment by yuwata** [comment] 2024-04-24 09:22
> this is our global lab network

What does the 'global' mean here??

If both two networks does not have internet connection, then typically not necessary to set default gateway.

As I already commented in the above, multiple default gateways in a host is anyway spurious in general, unless you really know what happens in such case and you carefully configure other settings.

Anyway, as commented in the previous comment. This is not a right place to support such case. This is the last comment from me in this page. Please go to the matrix channel.

**Comment by raviteja-b** [comment] 2024-04-24 09:32
> > this is our global lab network
> 
> What does the 'global' mean here??
> 
> If both two networks does not have internet connection, then typically not necessary to set default gateway.
> 
> As I already commented in the above, multiple default gateways in a host is anyway spurious in general, unless you really know what happens in such case and you carefully configure other settings.
> 
> Anyway, as commented in the previous comment. This is not a right place to support such case. This is the last comment from me in this page. Please go to the matrix channel.

global means lab network across countries. without adding default gateway its not working.
one last question, does systemd-network supports any option which differentiates 
default gateway vs gateway?
