### ISSUE TITLE
systemd-nspawn:  container networking broken with systemd 238 and linux 4.14

### ISSUE THREAD

**Issue by xeji** [systemd/systemd#8646] opened 2018-04-03 21:10 UTC
### Submission type

 Bug report

### systemd version the issue has been seen with

238

### Used distribution

NixOS

### In case of bug report: Expected behaviour you didn't see

Container networks created by `systemd-nspawn` options work as documented in systemd-nspawn(1).

### In case of bug report: Unexpected behaviour you saw

`systemd-nspawn` containers started with `-n` (or similar options implying private-network) only see a loopback interface, the desired interface to the host is missing. Problem occurs with kernel 4.14 and systemd 238. 

Works fine with kernel 4.9 (and reportedly 4.15 as well, but I did not test this myself).
Also works fine with systemd 237 and kernel 4.14.

### In case of bug report: Steps to reproduce the problem

Start a container with `systemd-nspawn -n`, log into container, `ip l`.

**Comment by jiri-one** [comment] 2018-04-04 06:13
I confirm @xeji report. I tested systemd 238 with kernel 4.14 (LTS) and 4.15. With 4.15 networking works inside nspawn virtual hosts, but with kernel 4.14 no. My distribution is Arch Linux.

**Comment by filbranden** [comment] 2018-04-04 07:14
I believe this is the same as issue #8599.

**Comment by xeji** [comment] 2018-04-04 07:30
Maybe, but why does this only happen with kernel 4.14 ?

**Comment by filbranden** [comment] 2018-04-04 07:39
> Maybe, but why does this only happen with kernel 4.14 ?

It's a race condition... ?

**Comment by xeji** [comment] 2018-04-04 09:37
I tested #8633 and it seems to fix this on NixOS.

**Comment by poettering** [comment] 2018-04-05 10:26
Let's close this as duplicate of #8633 then.

Duplicate of #8599

**Closed as completed by poettering** 2018-04-05 10:26 UTC
Labels: nspawn, duplicate
