### ISSUE TITLE
RFE userdb/homed: user entries should provide avatar/face field

### ISSUE THREAD

**Issue by RMTT** [systemd/systemd#18323] opened 2021-01-20 09:51 UTC
**systemd version the issue has been seen with**
 > 247

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `5.10.8-zen1-1-zen`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > sddm show avatar which locate at ~/.face.icon

**Unexpected behaviour you saw**
 > sddm cannot show avatar

**Steps to reproduce the problem**
 >  Follow the [Arch Wiki](https://wiki.archlinux.org/index.php/SDDM#User_icon_(avatar)), but no avatar shown, here is the permissions about the `.face.icon`:
```shell
for ~:
# file: home/mt
# owner: mt
# group: mt
user::rwx
user:sddm:--x
group::---
mask::--x
other::---

for ~/.face.icon:
# file: home/mt/.face.icon
# owner: mt
# group: mt
user::rw-
user:sddm:r--
group::r--
mask::r--
other::r--
```

**Comment by poettering** [comment] 2021-01-20 14:10
THis is by design. homed uses the user's password to decrypt te user's home directory. Thus, unless you already logged in (and provided a password) te home directory is impossible to access, and sddm can't either then. The security model of homed is simply much stricter than what came before.

We probably should add am avatar/face field to userdb, and sddm could pick it up there. if so it would be available as part of the user database, and this regardless if the user is logged in or not.

**Comment by poettering** [comment] 2021-01-20 14:14
will convert this into a homed RFE now, asking for such an avatar field to be added. But note that even if we add this it won't fix your issue unless sddm eventually actually looks there.

**Comment by RMTT** [comment] 2021-01-21 07:12
> We probably should add am avatar/face field to userdb, and sddm could pick it up there. if so it would be available as part of the user database, and this regardless if the user is logged in or not.

I think so : )
Hope this work will be completed!

**Closed as completed** 2024-02-19 13:39 UTC
Labels: RFE 🎁, homed
