### ISSUE TITLE
systemd ignores service from overlayFS

### ISSUE THREAD

**Issue by krutzio** [systemd/systemd#8732] opened 2018-04-16 14:34 UTC
### Submission type
 - Bug report

### systemd version the issue has been seen with
> v237

### Used distribution
> Poky (Yocto Project Reference Distro) 2.4+snapshot-20180416
> Kernel 4.9.21

### In case of bug report: Expected behaviour you didn't see
> The application in the app filesystem is starting at boot time.

### In case of bug report: Unexpected behaviour you saw
> The application in the mounted app filesystem is not starting at boot time although it is enabled and can be started manually.

### In case of bug report: Steps to reproduce the problem
I want to build a system with applications on another partition, an app-filessystem. All binaries, configs and service files which belong to the application should be in the app-fs.
The app-partition is mounted at /opt, this includes following files:
> /opt/usr/bin/app-binary  
> /opt/etc/systemd/system/multiuser.target/link_2_app.service  
> /opt/lib/systemd/system/app.service

To synchronize the files with rootfilesystem I created 2 overlays, this is the output of mount:
> /dev/app_partition on /opt type ext4 (rw,relatime,data=ordered)
> overlay on /etc type overlay (rw,relatime,lowerdir=/opt/etc:/etc,upperdir=/config/etc,workdir=/config/work)
> overlay on /lib/systemd/system type overlay (rw,relatime,lowerdir=/lib/systemd/system,upperdir=/opt/lib/systemd/system,workdir=/opt/work)

These mounts are handled before local-fs.target is reached.

Result:
I can start the app successfully with "systemctl start app.service" but manually only. The status with "systemctl status app.service" says it is enabled. But the app is not starting at boot time. Systemd does not give a message about trying to start the app.

Questions:
I want to understand what systemd is doing at boot time. Can you give me some hints?
When (at boot time) does systemd check the service files?
Is there a way to trigger it again?
Is there a way to debug the behaviour?

**Comment by boucman** [comment] 2018-04-16 15:15
systemd assumes that services (except generated ones) are available when it is started. To get this to work you need to mount your overlays before systemd is started... 

this is the sort of cases where an initrd is needed. Could you try doing that ?

**Comment by poettering** [comment] 2018-04-17 18:03
Anyway, closing this, as this is intended behaviour really.

**Closed as completed by poettering** 2018-04-17 18:03 UTC
Labels: pid1, not-a-bug

**Comment by krutzio** [comment] 2018-04-20 15:16
Thanks for the quick and detailed reply.

**Comment by krutzio** [comment] 2018-05-03 10:43
Why not using this?

Reload systemd, scanning for new or changed units:
# systemctl daemon-reload
