### ISSUE TITLE
fstab entires not mounted at boot with systemd 251-1

### ISSUE THREAD

**Issue by bkrochta** [systemd/systemd#23498] opened 2022-05-24 15:35 UTC
**systemd version the issue has been seen with**

 > systemd 251-1

**Used distribution**

 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux XPS15 5.15.41-1-lts #1 SMP Wed, 18 May 2022 13:37:06 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > fstab entries automatically mount at boot

Example mount unit:
```
systemctl status var-cache.mount 
```
```
● var-cache.mount - /var/cache
     Loaded: loaded (/etc/fstab; generated)
     Active: active (mounted) since Tue 2022-05-24 11:04:55 EDT; 1min 5s ago
      Until: Tue 2022-05-24 11:04:55 EDT; 1min 5s ago
      Where: /var/cache
       What: /dev/mapper/cryptroot
       Docs: man:fstab(5)
             man:systemd-fstab-generator(8)
      Tasks: 0 (limit: 18806)
     Memory: 56.0K
        CPU: 1ms
     CGroup: /system.slice/var-cache.mount

May 24 11:04:55 XPS15 systemd[1]: Mounting /var/cache...
May 24 11:04:55 XPS15 systemd[1]: Mounted /var/cache.
```

```
lsblk
```
```
NAME          MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
nvme0n1       259:0    0 238.5G  0 disk  
├─nvme0n1p1   259:1    0   512M  0 part  /efi
└─nvme0n1p2   259:2    0   238G  0 part  
  └─cryptroot 254:0    0   238G  0 crypt /var/log
                                         /var/tmp
                                         /home
                                         /var/lib/libvirt/images
                                         /.swap
                                         /var/cache
                                         /.snapshots
                                         /
```

**Unexpected behaviour you saw**
 > only `/`, `/home`, and `/var/tmp` were mounted

```
systemctl status var-cache.mount  
```
```
○ var-cache.mount - /var/cache
     Loaded: loaded (/etc/fstab; generated)
     Active: inactive (dead)
      Where: /var/cache
       What: /dev/mapper/cryptroot
       Docs: man:fstab(5)
             man:systemd-fstab-generator(8)
```
```
lsblk
```
```
NAME          MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
nvme0n1       259:0    0 238.5G  0 disk  
├─nvme0n1p1   259:1    0   512M  0 part  /efi
└─nvme0n1p2   259:2    0   238G  0 part  
  └─cryptroot 254:0    0   238G  0 crypt /home
                                         /var/tmp
                                         /
```

**Steps to reproduce the problem**
 > update systemd from `systemd 250.5-1` to `systemd 251-1` and reboot.

I am mounting btrfs subvolumes from an encrypted LUKS partition.

**Comment by yuwata** [comment] 2022-05-24 18:40
Should be duplicate of https://github.com/systemd/systemd/issues/23429#issuecomment-1133876263, and fixed by https://github.com/systemd/systemd-stable/commit/011161de615c125e91a27d10decf4b5a3c5fbb99. Closing.

**Closed as completed by yuwata** 2022-05-24 18:40 UTC
Labels: pid1, duplicate
