### ISSUE TITLE
systemd high CPU on some kubernetes nodes

### ISSUE THREAD

**Issue by fasaxc** [systemd/systemd#16728] opened 2020-08-14 14:14 UTC
**systemd version the issue has been seen with**
> $ systemd --version
> systemd 245 (245.4-4ubuntu3.2)
> +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS + ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Ubuntu 20.04 (running on AWS)

**Expected behaviour you didn't see**
 > low CPU from systemd on all nodes

**Unexpected behaviour you saw**
 > Both PID 1 and per-user systemd instances using almost a core each

**Steps to reproduce the problem**

We saw the problem after doing churn testing on a kubernetes cluster, creating and deleting pods over and over.  Some nodes are OK (systemd occasionally showing up in top) but, on some nodes, systemd seems to be stuck at 80+% CPU (both instances of systemd)

I straced systemd and attached the output.  It seems to repeatedly go through this pattern: 
```
readlinkat(AT_FDCWD, "/sys/devices/vbd-768/block/xvda/xvda1/subsystem", "../../../../../class/block", 4096) = 26
openat(AT_FDCWD, "/run/udev/data/b202:1", O_RDONLY|O_CLOEXEC) = 16
fstat(16, {st_mode=S_IFREG|0644, st_size=662, ...}) = 0
fstat(16, {st_mode=S_IFREG|0644, st_size=662, ...}) = 0
read(16, "S:disk/by-uuid/ce780dbf-6f70-412"..., 4096) = 662
read(16, "", 4096)                      = 0
close(16)                               = 0
stat("/dev/xvda1", {st_mode=S_IFBLK|0660, st_rdev=makedev(0xca, 0x1), ...}) = 0
openat(AT_FDCWD, "/", O_RDONLY|O_CLOEXEC|O_PATH|O_DIRECTORY) = 16
openat(16, "sys", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = 17
fstat(17, {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
close(16)                               = 0
openat(17, "dev", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = 16
fstat(16, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
close(17)                               = 0
openat(16, "block", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = 17
fstat(17, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
close(16)                               = 0
openat(17, "202:1", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = 16
fstat(16, {st_mode=S_IFLNK|0777, st_size=0, ...}) = 0
readlinkat(17, "202:1", "../../devices/vbd-768/block/xvda"..., 4096) = 38
close(16)                               = 0
openat(17, "..", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = 16
close(17)                               = 0
openat(16, "..", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = 17
close(16)                               = 0
openat(17, "devices", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = 16
fstat(16, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
close(17)                               = 0
openat(16, "vbd-768", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = 17
fstat(17, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
close(16)                               = 0
openat(17, "block", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = 16
fstat(16, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
close(17)                               = 0
openat(16, "xvda", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = 17
fstat(17, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
close(16)                               = 0
openat(17, "xvda1", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_PATH) = 16
fstat(16, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
close(17)                               = 0
close(16)                               = 0
access("/sys/devices/vbd-768/block/xvda/xvda1/uevent", F_OK) = 0
openat(AT_FDCWD, "/sys/devices/vbd-768/block/xvda/xvda1/uevent", O_RDONLY|O_CLOEXEC) = 16
fstat(16, {st_mode=S_IFREG|0644, st_size=4096, ...}) = 0
fstat(16, {st_mode=S_IFREG|0644, st_size=4096, ...}) = 0
read(16, "MAJOR=202\nMINOR=1\nDEVNAME=xvda1\n"..., 4096) = 58
read(16, "", 4096)                      = 0
close(16)                               = 0
```

[systemd.strace.gz](https://github.com/systemd/systemd/files/5075020/systemd.strace.gz)

**Comment by fasaxc** [comment] 2020-08-14 14:29
After draining an affected node, systemd went back to normal.

**Comment by fasaxc** [comment] 2020-08-14 14:33
There are lots of mounts like this on this node, even after draining it of pods: 
```
/dev/xvda1 on /run/docker/runtime-runc/moby/94c3c718f9622ae3e1fc9da508eab7440b712c65a262c531fb506b8824d648d4/runc.0YLowE type ext4 (ro,relatime,discard)
/dev/xvda1 on /run/docker/runtime-runc/moby/c0372f87d4d30b9b5f1a0e1daf2c8fb9c7c87ca66a34240241c3172377ee3379/runc.jIyB2a type ext4 (ro,relatime,discard)
/dev/xvda1 on /run/docker/runtime-runc/moby/9ceb55e914730db8542d302cc07d99cb67facd34c329ca98b107082e27e433c0/runc.vemT5M type ext4 (ro,relatime,discard)
/dev/xvda1 on /run/docker/runtime-runc/moby/62872bd6593ed616516a9fd8c95adf9e55c04f59cdabdf6056cc93d7ef24abe8/runc.wdeMRI type ext4 (ro,relatime,discard)
/dev/xvda1 on /run/docker/runtime-runc/moby/d8e53e8096b8ca1d8ba3e669bfff48c2b39881fc2cc2bdf75a8a973a494f9e40/runc.dtJD9t type ext4 (ro,relatime,discard)
/dev/xvda1 on /run/docker/runtime-runc/moby/4797a912a3ce6f3dff3e157d360c34e14f216b0361ea6b15f3d909819d3bdd3a/runc.BVuLdj type ext4 (ro,relatime,discard)
```

**Comment by fasaxc** [comment] 2020-08-14 15:28
Found this issue about parsing mountinfo that sounded similar in use case: https://github.com/systemd/systemd/issues/15464

One affected node had 1800 entries in /proc/1/mountinfo but I found an unaffected node with 1750 entries and an affected node with 1100.

**Comment by poettering** [comment] 2020-08-14 18:10
The kernel API is notoriously inefficient to get notified about mounts: we poll() on /proc/self/mountinfo and get a POLLPRI event whenever it changes. We then go and compare the new file with what we read before. This is expensive, since any mount event might trigger O(n) work for us. There has been working on creating a better kernel interface for this that tells us exactly what changed (this stuff: https://lore.kernel.org/lkml/1449543.1585579014@warthog.procyon.org.uk/ and #16671)

There also has been work on improving things in systemd a bit, i.e. backing off when we notice we spend too much time processing mount notification events. See #16537.

**Comment by poettering** [comment] 2020-08-14 18:13
That all said: kubernetes/moby/docker/run or whatever you use there is pretty broken if it inserts all these mounts into the host mount table anyway. It simply shouldn#t to that. mount namespaces exists so that such mounts should be private to the container, and leaving them around in the host is frickin ugly. They really should fix that if they intend to deploy many containers since regardless how efficient systemd can handle this, the underlying kernel API misdesign will take a long time to be fixed, and even then it's pretty admin unfriendly to have an effectively unbounded number of mounts in the mount table when the admin types "mount".

Anyway, let's close this as duplicate of #15464.

**Closed as completed by poettering** 2020-08-14 18:13 UTC

**Comment by fasaxc** [comment] 2020-08-15 18:33
Yep, looks like the root cause was a docker issue, leaking mounts.  Closing this since it's a dupe.
