### ISSUE TITLE
systemd-resolved: maybe add concept of "negative routing domains"

### ISSUE THREAD

**Issue by lretq** [systemd/systemd#29415] opened 2023-10-02 20:15 UTC
### Component

systemd-resolved

### Is your feature request related to a problem? Please describe

I am currently using hashicorp consul, which provides a DNS API (=> query nodes, services and so on registered with consul).
 I added this DNS API server as a resolved.conf entry like this:
```
[Resolve]
DNS=127.0.0.1:8006
Domains=~consul
DNSSEC=false
```
as per the consul dcumentation.

The problem with this is, that when reverse looking up an IP it resolves it via the consul DNS server and not my actual DNS server. This leads to wrong name resolutions. For example, instead of xxxx.example.com, I get xxxx.node.consul (Which is correct behaviour from consul).

### Describe the solution you'd like

A toggle to disable reverse lookups on a DNS server.

### Describe alternatives you've considered

I have used dnsmasq in between systemd-resolved and consul, which "fixes" it.

### The systemd version you checked that didn't have the feature you are asking for

252

**Comment by rpigott** [comment] 2023-10-18 16:55
Just add the reverse mapping domains as route-only domains (~in-addr.arpa ~in6.arpa) to your non-vpn interface?

**Comment by poettering** [comment] 2024-03-05 10:37
Yes, i agree, just specify the routing domains on the interfaces that shall get the reverse lookups and the problem should be solved?

that said I am not totally opposed to adding "negative routing", i.e. a way how you can say that specific lookups should never be routed onto some specific interface. Would be useful mostly for controlling reverse lookups i guess.

**Comment by poettering** [comment] 2024-03-05 13:32
Duplicate of #21260. Closing.

**Closed as completed by poettering** 2024-03-05 13:32 UTC
Labels: RFE 🎁, resolve, duplicate
