### ISSUE TITLE
239 - StandardOutput=file does not truncate target leading to garbled output

### ISSUE THREAD

**Issue by SjonHortensius** [systemd/systemd#9566] opened 2018-07-11 08:26 UTC
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Archlinux

**Expected behaviour you didn't see**
 > When StandardOutput is a file, that file should be truncated before writing, or its length adjusted after completion

**Steps to reproduce the problem**
```
[Unit]
Description=TEST StandardOutput not truncating target file - %i

[Service]
StandardOutput=file:/tmp/test.log
ExecStart=/bin/seq 1 %i

[Install]
WantedBy=multi-user.target
```

run `systemctl start seq@20` and `systemctl start seq@10`. You'd expect /tmp/test.log to only contain the last sequence (up to 10) but previous run is also there (making the file contain 20 lines)

**Comment by keszybz** [comment] 2018-07-11 08:48
Duplicate of #8983.

**Closed as completed by keszybz** 2018-07-11 08:48 UTC
Labels: duplicate
