### ISSUE TITLE
systemd-time-wait-sync does not detect synchronization and "hangs"

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#8683] opened 2018-04-07 18:19 UTC
systemd-time-wait-sync.service was "waiting" for synchronization for a few days on my machine. Logs indicate that systemd-time-wait-sync.service is started before systemd-timesyncd.service, and after systemd-timesyncd.service reaches synchronized state, systemd-time-wait-sync does not detect this properly.

Logs from example boot:
```console
$ journalctl -b-1 --no-hostname -o short-monotonic -u systemd-time-wait-sync.service -u systemd-timesyncd.service 
-- Logs begin at Tue 2017-11-14 17:13:20 CET, end at Sat 2018-04-07 20:12:58 CEST. --
[   16.972377] systemd-time-wait-sync[763]: adjtime state 5 status 40 time Tue 2018-04-03 05:38:04.833941 UTC
[   20.941366] systemd[1]: Starting Network Time Synchronization...
[   21.051842] systemd[1]: Started Network Time Synchronization.
[   30.074710] systemd-timesyncd[994]: Network configuration changed, trying to establish connection.
[   60.393954] systemd-timesyncd[994]: Synchronized to time server 216.239.35.8:123 (time3.google.com).
[39243.008619] systemd-timesyncd[994]: Network configuration changed, trying to establish connection.
...
[46444.649717] systemd-timesyncd[994]: No network connectivity, watching for changes.
[46459.826208] systemd-timesyncd[994]: Network configuration changed, trying to establish connection.
[46470.034082] systemd-timesyncd[994]: Timed out waiting for reply from 216.239.35.8:123 (time3.google.com).
[46480.284187] systemd-timesyncd[994]: Timed out waiting for reply from 216.239.35.12:123 (time4.google.com).
[48528.646637] systemd-timesyncd[994]: Synchronized to time server 216.239.35.0:123 (time1.google.com).
** date -s here **
[388164.347331] systemd-time-wait-sync[763]: adjtime state 5 status 40 time Sat 2018-04-07 17:26:56.000433 UTC
[388164.347331] systemd-time-wait-sync[763]: adjtime state 0 status 2000 time Sat 2018-04-07 17:27:12.151764 UTC
[388164.349027] systemd[1]: Started Wait Until Kernel Time Synchronized.
[389160.684445] systemd-timesyncd[994]: Network configuration changed, trying to establish connection.
[389160.684932] systemd-timesyncd[994]: Synchronized to time server 216.239.35.8:123 (time3.google.com).
```
At some point I forced the clocked to jump by setting it with `date`. Only at that point did systemd-time-wait-sync terminate.

Comments in systemd-time-wait-sync.c indicate that the wake-up mechanism might not work if the time does not jump. I guess that my RTC is synchronized well with the system clock, and after a reboot the adjustment from NTP is very small.

@pabigot, any ideas how to handle this? It seems fairly repeatable, I get the same result after every reboot.

**Comment by pabigot** [comment] 2018-04-07 20:11
Does your RTC store local time or UTC?  It appears that if the RTC uses the local time zone then timesyncd will always set STA_UNSYNC which keeps the kernel from recognizing that it's synchronized to NTP.  In that case I suspect the only solution is to disable time-wait-sync, so time-sync.target will be released as soon as timesyncd finishes.

Alternatively it could well be that the initial time is close enough that the kernel knows the clock is synchronized, but gets into that state without actually "setting the clock".  That can be confirmed by manually running systemd-time-sync-wait after the system boots:

    # /lib/systemd/systemd-time-wait-sync                                             
    adjtime state 0 status 2001 time Sat 2018-04-07 20:04:28.230225 UTC 

If `state` is zero the time is synchronized, but if time-wait-sync is still blocked then it didn't notice because there wasn't a clock set event.  In that case we need a way to wake it up.  Or, again, just disable the service.

What hardware provides the RTC?  There may also be another way to detect that the clock is "good enough".

**Comment by pabigot** [comment] 2018-04-07 20:36
I have a patch that will make time-wait-sync exit immediately if the clock is in the local timezone.  I'll add a PR for that once it's clear there aren't any other changes necessary.

**Comment by poettering** [comment] 2018-04-09 09:47
The other option is to rework this tool to simply communicate with a watch file with timesyncd: a file that in /run is created whenever timesyncd synced for the first time. and this wait tool just waits for it to appear using inotify...

This of course means the tool becomes specific to timesyncd, but quite frankly I take reliability any day over maintaining compatibility with other NTP implementations...

That said, combinations of both approaches could be acceptable, too. i.e. when the touch file exists *or* adjtimex reports synchronization waiting could be considered done

**Comment by pabigot** [comment] 2018-04-09 10:37
I can add a watch file to timesyncd.  If that approach is taken, then perhaps it covers the case of a hwclock in the local timezone, though that would technically violate the promise of the service which is that the kernel considers time to be synchronized.  I need to play with this on a system that has a hardware clock....

**Comment by keszybz** [comment] 2018-04-09 11:12
> Does your RTC store local time or UTC?

UTC.

> Alternatively it could well be that the initial time is close enough that the kernel knows the clock is synchronized, but gets into that state without actually "setting the clock".

I believe this to be the case. In my initial report, systemd-timesyncd reports synchronization multiple times, but systemd-time-sync-wait is blocked.

```console
$ /usr/lib/systemd/systemd-time-wait-sync 
adjtime state 0 status 0 time Mon 2018-04-09 11:04:04.285050 UTC
```
> The other option is to rework this tool to simply communicate with a watch file with timesyncd: a file that in /run is created whenever timesyncd synced for the first time
> This of course means the tool becomes specific to timesyncd

I like this approach. This has the advantage that it'd work for both the RTC-in-UTC and RTC-in-local cases. But I'd prefer to make this file non-timesyncd-specific, something like /run/system-clock-synchronized, and then we could trivially allow any ntp implementation to touch this file whenever synchronization is successful.

**Comment by pabigot** [comment] 2018-04-09 11:28
My concern was that systemd-timesyncd reported synchronization and updated the kernel but kept the flag that told the kernel it was not synchronized; thanks for the output  that shows that isn't what happened.

`/run/systemd/time-wait-synchronized`? So it's clear it pairs with systemd-time-wait-sync.

I propose the default semantics will be that if that file appears time-wait-sync exits even if adjtimex() disagrees, but have not yet fully abandone an option to also requires kernel-level synchronization.  I need to play with some alternatives but will get a PR in soon.

**Comment by keszybz** [comment] 2018-04-09 12:52
My point was to **not** make this systemd-specific, i.e. not under `/run/systemd/`, but one level up. The reason is that if we want to (later on) e.g. patch nptd and chronyd to do the same thing, it'll be easier if the path is not systemd specific.

**Comment by pabigot** [comment] 2018-04-09 13:14
But the only thing that looks for the watchfile is a systemd service (time-wait-sync).  I see limited precedent for systemd services looking for files that are in `/run` but not under `/run/systemd`, and those appear to be cases where some higher authority specified the path and behavior.

IMO systemd should not define a path outside its domain for use by and for other systems unless it's coordinated with those systems.  But my judgment here is somewhat hampered in that I don't know how difficult it would be for ntpd or chrony to create a file under `/run/systemd`, or if there's some other IPC mechanism that would be better in that situation.

In any case, I'll work on the infrastructure; if @poettering would be so kind as to supply guidance I'll use whatever watchfile path is agreed on.

**Comment by keszybz** [comment] 2018-04-09 13:25
Exactly.

Also note that there's no "higher authority". Nowadays it's systemd that most often decides the location of things.

**Comment by pabigot** [comment] 2018-04-09 13:33
OK, thanks to everyone for clarifying.  I'll use the suggested ` /run/system-clock-synchronized` with the interpretation that its presence supersedes the kernel's perception whether the clock is synchronized per adjtimex().

**Comment by poettering** [comment] 2018-04-09 15:17
IIRC the FHS suggests not to place stuff anymore directly in /run, but one subdir down. And I am pretty sure that's a good idea really. In fact everytime I look into /run and see all those crap files allover the place I die a little inside ;-)...

Hence, I am fine with using some generic path for that timestamp file, but I think it should be /run/clock/synchronized or so instead.

**Comment by keszybz** [comment] 2018-04-09 15:39
I think `/run/clock/synchronized` is worse: it increases the chance of conflict, since `clock` is such a short and attractive name.  Then whatever "clock" is used for, might be happy with another file called "synchronized", but it might not. "system-clock-synchronized" is not very likely to conflict, "clock" unfortunately is.

**Comment by pabigot** [comment] 2018-04-09 15:46
timesyncd-manager already touches `/var/lib/systemd/timesync/clock` whenever it sets the clock.  Maybe should just use that, even if it only works for systemd.

**Comment by pabigot** [comment] 2018-04-09 16:45
Clearly `/var/lib/systemd/timesync/clock` won't work since it's usually there.  Unless path_spec_watch can be used I don't see a sane way to watch for creation of a file in a subdirectory of run that might not exist.  I'm going with `/run/system-clock-synchronized` for the initial PR.

**Comment by keszybz** [comment] 2018-04-09 20:19
You could watch recursively all the directories, but actually you don't want to, because even if you watch all those directories, that file cannot be created until /var is mounted. It seems much nicer to use a second file in /run, because /run is always available.

**Comment by pabigot** [comment] 2018-04-09 21:40
I ended up going with `/run/clock/synchronized` because of reasons not worth documenting.  Pretty trivial to switch back to `/run/system-clock-synchronized` if the consensus is that's preferred.

**Comment by poettering** [comment] 2018-04-10 15:26
Also, @keszybz did you explicitly enable that service? This really shouldn't be enabled by default. Making the boot depend on external conditions is something that must be opt-in not opt-out...

**Comment by poettering** [comment] 2018-04-10 15:27
(oh, and a file for this in /var is not right anyway...We should minimize unnecessary requirements on a writable /var)

**Comment by pabigot** [comment] 2018-04-10 15:46
The only reference to `/var` was when I was confused and thought the clock file could be used as the watchfile.  I'm fairly sure the initial watchfile's going to be `/run/clock/synchronized`, if my changes to notify work.  By the time the file needs to be created timesyncd doesn't have permissions to create `/run/system-clock-synchronized`.

systemd-time-wait-sync was always automatically enabled because that's what timesyncd did.  I think I see how to make it default disabled, which I'll add to the PR.

**Closed as completed** 2018-04-18 11:21 UTC
Labels: bug 🐛, timesync

**Comment by gourvy** [comment] 2020-05-26 15:22
While testing systemd v244.3 I encountered a similar problem (though not systematic). But this time, /run/systemd/timesync/synchronized exists. Restarting systemd-time-wait-sync allows the service to notice that /run/systemd/timesync/synchronized exists and everything works fine after that. So, it seems that systemd-time-wait-sync has some problems during the boot only.
This problem is still there in v245.5. But in version 241 I didn't encounter any problem (the kernel notify systemd-time-wait-sync that /run/systemd/timesync/synchronized exists and the service exit properly).

A simple test to check if the feature works is to mask the ntp client service, reboot, create the file "synchronized" and check the status of  systemd-time-wait-sync.
`systemctl mask systemd-timesyncd; reboot`
`mkdir /run/systemd/timesync; touch  systemctl status systemd-time-wait-sync; systemctl status systemd-time-wait-sync`
If systemd-time-wait-sync is still running, the problem is there. If it's exited, there's no problem.
Can someone validate/invalidate that there's a regression?
If there's no regression I'll open a different ticket
