### ISSUE TITLE
Failed to start reboot.target: Connection timed out

### ISSUE THREAD

**Issue by stamster** [systemd/systemd#6843] opened 2017-09-15 17:11 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

> systemd 229
> +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

### Used distribution

> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04.3 LTS
> Release:	16.04
> Codename:	xenial

### In case of bug report: Expected behaviour you didn't see

> myserver # reboot
> No errors printed on screen, task completed in the background (server rebooted)

### In case of bug report: Unexpected behaviour you saw

> myserver # reboot
>
> Failed to start reboot.target: Connection timed out
> See system logs and 'systemctl status reboot.target' for details.

(server actually rebooted after this, so I wasn't able to see status report)

### In case of bug report: Steps to reproduce the problem

> simply try to`reboot` while server is under high load (~50 or so)

**Comment by bl33pbl0p** [comment] 2017-09-15 17:36
Please try reproducing this with v233 or v234. On the issue tracker, only the two most recent systemd versions are supported. Your version is very old by now. You _can_ ping your downstream maintainers about this. Also, if you need support, please attach the relevant logs.

**Comment by poettering** [comment] 2017-09-18 09:12
As @bl33pbl0p points out, this is systemd version is a bit too old to be be tracked upstream. We only focus on the two most recently systemd versions here, which are 233 and 234 at the moment. Please ping your downstream distro about this. Or update to 234 and try to reproduce the issue. In either case, make sure to include the logs generated by the command, ideally even after booting with "systemd.log_level=debug" on the kernel command line, so that the maintainers have enough information to track this down.

Closing this here now. Thank you for understanding.

**Closed as completed by poettering** 2017-09-18 09:12 UTC
Labels: version-too-ancient

**Comment by stamster** [comment] 2017-09-18 09:21
Well, that's simply not a solution as many LTS distros out there rely on such (older) versions.

Pinging downstream (distro) maintainers would not make a difference on this, due to strict LTS policy, and really this bug is not that critical I guess.

Thanks @poettering @bl33pbl0p

**Comment by dkebler** [comment] 2017-10-20 15:48
I have similar issue with 232 on 17.04.  235 is out and  I would like to try the current but the only  ppa i can find is lagging  at 233.  https://launchpad.net/~pitti/+archive/ubuntu/systemd?field.series_filter=zesty
I'm not prepared to compile my own so any suggestions of how to keep current?

**Comment by baiyz** [comment] 2017-12-14 23:47
Also reproduced this issue on Ubuntu 16.04.3 with arm64 system, systemd version 229-4ubuntu21

The following command works:
systemctl --force --force reboot

**Comment by noizo** [comment] 2017-12-15 02:11
i've just encountered that issue, thanks @baiyz for the solution.
i wonder why this issue is closed, since bug is out there?

**Comment by alternico** [comment] 2018-01-19 14:39
Same here...

ii  systemd                             229-4ubuntu21                              amd64        system and service manager

Ubuntu 16.04.3
