### ISSUE TITLE
Hard system crash when running journalctl

### ISSUE THREAD

**Issue by jarlethorsen** [systemd/systemd#18087] opened 2020-12-26 17:45 UTC
**systemd version the issue has been seen with**
 > 247

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > Linux maskin 5.9.14-arch1-1 #1 SMP PREEMPT Sat, 12 Dec 2020 14:37:12 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Text output

**Unexpected behaviour you saw**
 > Hard system crash, reboot

**Steps to reproduce the problem**
 > Running the command "journalctl --list-boots" will result in a hard crash and reboot 100% of the time.

I would be happy to provide more debug info, however I'm currently not sure how to get more info as the whole system crashes when I run this command.

I have had irregular crashes for a while, which I suspect may be related to having "journalctl -F" running.

Both RAM and CPU have been tested for days without problem.

Maybe this is caused by some corrupt data in the logs?

**Comment by bluca** [comment] 2020-12-27 13:51
Can you share the journal files that cause this issue?

**Comment by bluca** [comment] 2020-12-27 13:51
Also when did the behaviour start appearing? Was it after an update? If so, what was updated?

**Comment by jarlethorsen** [comment] 2020-12-27 14:59
Not sure how to figure out which journal files is causing this issue, I have more than 2 GB of journal files on this system?

I would say the problem probably started a couple of months ago. This is a system that is running 24/7 and I probably did not notice the reboots happening every couple of days at first.

I have spent a couple of weeks trying to figure this out, first by ruling out any hardware issue.

It was first when I ran "journalctl --list-boots" to try and pinpoint when these random reboots started happening I actually found the real culprit. If I could just get it to not crash... :)

**Comment by bluca** [comment] 2020-12-27 15:01
The journal files will be split - just bisect them by moving half of them out of the directory and see if the problem occurs. Nobody else has observed this so far, so the most reasonable assumption is that there's something in the files themselves.

Also the backtrace/kernel oops is needed.

**Comment by poettering** [comment] 2020-12-27 20:32
I am sorry, but if userspace manages to make your system crash, then that's a bug in the kernel or in the hw. Userspace runs with limited privileges only, and should not be able to do something like that.

Given that journalctl is the trigger at best, but not the cause, please work with your distro on this first, i.e. report this to your donwtsream distro. There's probably something wrong between your kernel and your hw, but journalctl is certainly not rebooting your system, and if it can do that your kernel must be fixed.

Closing.

**Closed as completed by poettering** 2020-12-27 20:32 UTC
Labels: journal, not-our-bug, needs-reporter-feedback ❓

**Comment by vcaputo** [comment] 2020-12-28 06:26
Considering `journalctl` is often run as root, particularly for operations like `--list-boots`, I'm not sure it's fair to take such a firm stance of "we're in userspace, we can't break the system".  Userspace processes running as root have significant potential to break things and/or violate things like resource limits.

@jarlethorsen Out of curiosity have you tried reproducing this running as a regular user?  You can copy the journals to a temporary directory owned by your regular user and supply its path to `journalctl` with `--directory /path/to/journals/`.

It's worth noting that basically all journalctl does is mmap() regions of the journal files.  It accumulates these mappings in its address space only reclaiming them until OOM occurs.  With enough journal files, it can add up to quite a large amount of address space and may be exercising your kernel and its memory management subsystem more than anything else you execute.  I agree with @poettering in that this shouldn't result in crashing the system, but I'd verify it does the same crash running as a regular user.  If it only crashes as root with the same journals, that's an interesting data point hinting at perhaps something wrong in journalctl doing something inadvertently that being root allows to proceed and break things.

**Comment by jarlethorsen** [comment] 2020-12-28 16:28
@vcaputo I'm running ```journalctl --list-boots``` as a normal user, so I was actually quite suerprised myself when I saw that it triggered such a hard crash...

Moving most of the logfiles away to another directory lets the command run without crashing the system. I have yet to locate the specific logfile that is triggering the crash. I'll see what I can figure out.
