### ISSUE TITLE
systemd-nspawn --private-users: Failed unmounting /run/systemd/nspawn/incoming.

### ISSUE THREAD

**Issue by amessina** [systemd/systemd#15721] opened 2020-05-06 02:07 UTC
**systemd version the issue has been seen with**
> systemd 245 (v245.4-1.fc32)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified

**Used distribution**
 > Fedora 32 x86-64

**Expected behaviour you didn't see**
 > [OK] Unmounted /run/systemd/nspawn/incoming.

**Unexpected behaviour you saw**
 > [FAILED] Failed unmounting /run/systemd/nspawn/incoming.

**Steps to reproduce the problem**
1. Run systemd/init inside a systemd-nspawn container with -U/--private-users
2. Poweroff the container
3. Observe that files mounted in from the host system fail to unmount.  This affects bind-mounted `/etc/localtime`, `/etc/resolv.conf`, ` /run/systemd/nspawn/incoming` and other --bind mounts.

Issue seems similar to https://github.com/systemd/systemd/pull/4340.  I've included the strace for unmounting `/run/systemd/nspawn/incoming`.  It errors with "not mounted", just like in https://github.com/systemd/systemd/pull/4340.
[strace.txt.291636.txt](https://github.com/systemd/systemd/files/4584558/strace.txt.291636.txt)

**Comment by poettering** [comment] 2021-02-12 16:50
This is more or less a duplicate of #3774

**Closed as completed by poettering** 2021-02-12 16:50 UTC
Labels: nspawn, pid1, duplicate
