### ISSUE TITLE
systemd-networkd: Add support for not enslaved gretap tunnels

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#6694] opened 2017-08-30 08:34 UTC
It seems to be necessary to create some kind of network (e.g. eth0.network) to create tunnel interfaces. The eth0.network then has to contain Tunnel= entries. And as I found out in #6693, will remove the IP addresses from eth0.

As we already know, this requirement ended rather bad for me. It would therefore be good to be able to create unenslaved gretap interface

**Comment by poettering** [comment] 2017-08-30 09:03
Duplicate of #6695

**Closed as completed by poettering** 2017-08-30 09:03 UTC
Labels: network, duplicate
