### ISSUE TITLE
rootprefix not handled correctly

### ISSUE THREAD

**Issue by maxim-belkin** [systemd/systemd#12930] opened 2019-07-02 15:57 UTC
**systemd version the issue has been seen with**
> 242

**Used distribution**
 > Docker image of Ubuntu 16.04.4 LTS

**Expected behaviour you didn't see**
 > Using `-Drootprefix=/some/directory` installs (all) files under `/some/directory`

**Unexpected behaviour you saw**
 > (some) files are installed under `/some/directory/some/directory`

This problem was probably not caught before because `//` (double `rootprefix` when `rootprefix` == `/`) is identical to `/`, whereas `/some/directory/some/directory` is not.

**Steps to reproduce the problem**

https://github.com/maxim-belkin/linuxbrew-core/blob/systemd-242/Formula/systemd.rb#L37-L51

```
mkdir build && cd build
meson -Drootprefix=/some/directory ..
ninja
DESTDIR=/some/directory ninja install
```

**Prose**

I explained what happens in detail here: https://github.com/Homebrew/linuxbrew-core/pull/14039#issuecomment-507453038

**Comment by mbiebl** [comment] 2019-07-02 16:47
What you see is pretty much expected behaviour.

**Comment by maxim-belkin** [comment] 2019-07-03 00:09
In `src/journal/meson.build` there is `mkdir_p.format('/var/log/journal'))`

**Comment by maxim-belkin** [comment] 2019-07-03 01:13
In order to install `systemd` in `/some/directory` without using `DESTDIR`, I had to:

1. In `src/journal/meson.build` change
`mkdir_p.format('/var/log/journal'))`
to 
`mkdir_p.format(join_paths(prefixdir,'var/log/journal')))`

2. In `src/journal-remote/meson.build` change
`mkdir_p.format('/var/log/journal/remote'))`
to
`mkdir_p.format(join_paths(prefixdir,'var/log/journal/remote')))`

3. In `hwdb/meson.build` change
`systemd-hwdb update`
to
`systemd-hwdb -r /some/directory update`

and then also set 
```
-Dsysconfdir=/some/directory/etc
-Dlocalstatedir=/some/directory/var
-Dsysvinit-path=/some/directory/etc/init.d
-Dsysvrcnd-path=/some/directory/etc/rc.d
-Drc-local=/some/directory/etc/rc.local
-Dhalt-local=/some/directory/sbin/halt.local
```


which I didn't have to set when using `DESTDIR`

**Comment by floppym** [comment] 2019-07-03 02:52
It is not clear from your description exactly what you think is wrong here.

**Comment by maxim-belkin** [comment] 2019-07-03 03:55
> It is not clear from your description exactly what you think is wrong here.

A number of packages in Homebrew on Linux depend on `systemd`. As anything in Homebrew, we install things into some directory. Building packages into custom directories is usually achieved with a mere `--prefix=/somewhere`, maybe a few other options. With `systemd` 242 one has to [go to great lengths](https://github.com/systemd/systemd/issues/12930#issuecomment-507899581) or do something [weird](https://github.com/Homebrew/linuxbrew-core/pull/14039#issuecomment-507453038) to do that. Basically, I am wondering if someone could note a mistake in the set of flags that I'm using and let me know about it.

I also think that there is a problem with logic with the way `/var/log/...` directories are treated.

And a side note: parameters such as `sysconfdir` and `localstatedir` are usually inferred from `prefix`: any `./configure --help` says:
```
  Fine tuning of the installation directories:
    --bindir=DIR            user executables [EPREFIX/bin]
    --sbindir=DIR           system admin executables [EPREFIX/sbin]
    --libexecdir=DIR        program executables [EPREFIX/libexec]
    --sysconfdir=DIR        read-only single-machine data [PREFIX/etc]
    --sharedstatedir=DIR    modifiable architecture-independent data [PREFIX/com]
    --localstatedir=DIR     modifiable single-machine data [PREFIX/var]
    --libdir=DIR            object code libraries [EPREFIX/lib]
    --includedir=DIR        C header files [PREFIX/include]
  ```
This is not so in `meson_options.txt`
I'm also not sure about the meaning of `rootprefix` -- it says 'override the root prefix' but it doesn't help.
Finally, it seems to be not possible to provide custom locations for such libraries as `libcap`, libblkid`, etc. as `dependency()`in meson, unlike `find_library` does not accept `dirs` keyword.

**Comment by keszybz** [comment] 2019-07-03 09:09
> In `src/journal/meson.build` there is `mkdir_p.format('/var/log/journal'))` and
> `mkdir_p = 'mkdir -p $DESTDIR/@0@'` (in main meson.build), so without `DESTDIR` this `mkdir` will attempt to create a directory in `/` which fails in unprivileged build.

Sounds like a bug. Please submit any such cases as PR.
(We don't see this, because we're always building systemd on a machine which already has `/var/log/journal` and similar dirs, so this simply does nothing).

`--rootprefix` is about the obsolete split between `/` and `/usr`.  It's impossible to explain succinctly, since it doesn't make much sense. If you think you have a better description that fits in the same width, please include it in the PR too ;).

**Comment by floppym** [comment] 2019-07-03 14:12
Are you attempting to run systemd from `/somewhere`? Please note that systemd doesn't really support that.

**Comment by floppym** [comment] 2019-07-03 14:18
For example, the path `/var/log/journal` is hard-coded in several places in the systemd source code, so hard-coding the equivalent of `mkdir -p /var/log/journal` in the build files is arguably the right thing to do.

The alternative would be to convert this path into a build parameter, and reference the parameter in the source code.

**Comment by keszybz** [comment] 2019-07-03 14:40
We only support *running* with `/var/log/journal`. But installation with `$DESTDIR` should only touch `$DESTDIR/var/log/journal/`. So it's OK to hardcode the path in the sources, but not in build scripts.

**Comment by floppym** [comment] 2019-07-03 14:48
> But installation with $DESTDIR should only touch $DESTDIR/var/log/journal/.

It already does that.
```
mkdir_p = 'mkdir -p $DESTDIR/@0@'
...
meson.add_install_script(
        'sh', '-c',
        mkdir_p.format('/var/log/journal'))
```

> So it's OK to hardcode the path in the sources, but not in build scripts.

The path is technically still hard-coded in the build scripts, in that it doesn't respect prefix or rootprefix, or localstatedir. DESTDIR is another matter entirely. That's all I was getting at.

**Comment by keszybz** [comment] 2019-07-03 16:06
Oh, right. I read the code wrong.So I think it's mostly OK. We generally don't support configuring a different location for the logs.

**Comment by maxim-belkin** [comment] 2019-07-03 20:28
> Are you attempting to run systemd from `/somewhere`?

No. Some packages link against `libudev.so.1` provided by `systemd`. 

> We generally don't support configuring a different location for the logs.

I'm not sure I understand this point: the entire `systemd` package can be installed to `/some/directory` (with all the "gotchas") but location of logs has to be hard-coded? Aren't logs supposed to be stored in a location relative to `prefix`? At a first glance, it doesn't look like it would require a lot of support.

> The alternative would be to convert this path into a build parameter, and reference the parameter in the source code.

I think there is no need for an additional parameter (at least, for now). I think the right solution is to make logs live under `prefix` (or `rootprefix` but I still don't get it 🙃)

> DESTDIR is another matter entirely.

I'm all ears if you've got some time to explain the difference between `DESTDIR` and `prefix`. Why is it not equal to `prefix`?

**Comment by floppym** [comment] 2019-07-04 06:30
> No. Some packages link against libudev.so.1 provided by systemd.

If you just want a library to link against, configure with `--prefix=/usr` and install to some temporary location using `DESTDIR`. You can then copy libudev.so wherever you want manually.

> I'm not sure I understand this point: the entire systemd package can be installed to /some/directory (with all the "gotchas") but location of logs has to be hard-coded? Aren't logs supposed to be stored in a location relative to prefix? At a first glance, it doesn't look like it would require a lot of support.

The systemd build system assumes that you will configure with `prefix=/usr` and `rootprefix=/usr` or `rootprefix=/`. Although meson allows you to pass other values, the systemd developers do not really support it.

> I'm all ears if you've got some time to explain the difference between DESTDIR and prefix. Why is it not equal to prefix?

Speaking generally (not specific to systemd):

`prefix` is the final location to which the files will be installed.

`DESTDIR` allows the files to be staged in a separate location, under which the files will be installed in `prefix`. This is mostly used by package building tools (rpm, dpkg, etc). The package management tool is responsible for copying the files to `/${prefix}` when you install the package.

For example, if you configure the project with `--prefix=/foo` and run `DESTDIR=/bar ninja install`, your files will end up in `/bar/foo`. This is the expected and correct behavior. If you are not building a package, it is then your responsibility to copy the files from `/bar/foo` to `/foo` before attempting to run the software.

**Comment by keszybz** [comment] 2019-07-04 07:30
So... I think there's no bug here. We simply don't support remapping into arbitrary directories, a number of locations are fixed. This includes, `/var/log/journal`, `/run`, `/var/lib/systemd`, `/etc/fstab`, `/etc/systemd/system`, various api filesystems, and many others. I was confused and thought that we ignore `$DESTDIR`, but @floppym cleared that up. Sorry, but the use case of pushing systemd into some arbitrary subdirectory using `-Dprefix` is not supported.

(BTW, setting `-Dprefix` and `$DESTDIR` to the same path makes no sense. The first specifies the location in the installation root and on the final system, the second specifies the location of a temporary installation root.)

**Closed as completed by keszybz** 2019-07-04 07:30 UTC
Labels: not-supported, meson

**Comment by keszybz** [comment] 2019-07-04 07:52
That said ... I think we should allow skipping the creation of `/var/log/journal`. Not everybody wants that. I'll submit a PR.

**Comment by maxim-belkin** [comment] 2019-07-05 20:24
Thank you both, @keszybz and @floppym! I really appreciate your thorough explanations! In fact, I now understand the purpose of `rootprefix` (`if /bin !=  /usr/bin then rootprefix = /usr else rootprefix = /`)  and `DESTDIR` (for packaging tools). I think that in case of Homebrew on Linux it makes sense to do as @floppym suggests above: install `systemd` using `--prefix` (`-Dprefix`) and some `DESTDIR` and then "install" just the library.
