### ISSUE TITLE
systemd-network: IPv6Token/RFE: Multiple Definitions, Named Auto-Generation Types, Per-Prefix Definition, Anycast/NoDAD

### ISSUE THREAD

**Issue by maddes-b** [systemd/systemd#6889] opened 2017-09-22 14:19 UTC
Submission type: Request for enhancement (RFE)
systemd version: any
Used distribution: Debian 9.1 with systemd v232

1. Allow to specify multiple IPv6Token for SLAAC
Useful when multiple addresses are needed for application binding on a single interface or due to limitations/problems with some other nodes (e.g. port forwarding of AVM FRITZ!Box falls back to EUI-64 as soon as an IPv6 address is not reachable).
2. Provide names to choose between different auto-generation types:
2.1 "eui64" for EUI-64 of RFC 4291
2.2 "prefixstable" for RFC 7217
3. Allow to specify a prefix range an IPv6Token is valid for.
4. Allow to specify a preferred and validity lifetime.
5. Allow to specify token as an anycast address (RFC 4291, no DAD)

Example:
```
### IPv6Token=<token>[,[<prefix range>][,[<validty lifetime>][,[<preferred lifetime>][,anycast]]]]
### Hardware-based EUI-64 Interface ID for all subnets/prefixes, default validity, not preferred
IPv6Token=eui64,,,0
### 2 additional fix Interface IDs for ULA, infinite lifetime, forever preferred, first one as anycast address
IPv6Token=::1,fc00::/7,forever,forever,anycast
IPv6Token=::2,fc00::/7,infinity,infinity
### Additional prefix-stable Interface IDs for GUA, default lifetimes
IPv6Token=prefixstable,2000::/3
``` 

Of course IPv6Token could also become a section similar as Address.
```
[Network]
### Prefix-stable Interface IDs for all subnets
IPv6Token=prefixstable

[IPv6Token]
### Hardware-based EUI-64 Interface ID for all subnets/prefixes, default validity, not preferred
IPv6Token=eui64
PreferredLifetime=0

[IPv6Token]
### Additional fix Interface ID for ULA, infinite lifetime, forever preferred, as Anycast address
IPv6Token=::1
PrefixMatch=fc00::/7
ValidityLifetime=infinity
PreferredLifetime=forever
Anycast=true
```

**Comment by poettering** [comment] 2017-09-22 16:42
we usually try to normalize settings instead of cramming them all into one line. (i.e. the second approach appears better to me)

@ssahani something for you?

**Comment by ssahani** [comment] 2017-09-26 16:26
Could you please give a example how we do this with ip command
```
ip token set ::1a:2b:3c:4d/64 dev eth4
```
that is same 

```
IPv6Token=
An IPv6 address with the top 64 bits unset. When set, indicates the 64-bit interface part of SLAAC IPv6 addresses for this link. Note that the token is only ever used for SLAAC, and not for DHCPv6 addresses, even in the case DHCP is requested by router advertisement. By default, the token is autogenerated.
```

**Comment by maddes-b** [comment] 2017-09-27 21:15
The ip command has no token support, only systemd-networkd has token support as it is a reaction to a received RA with A-flag set (=SLAAC allowed).
systemd-networkd receives a prefix and uses the token as the interface id to build the SLAAC address.
If the token is not set or empty, then an EUI-64 interface ID is generated and used instead.

My feature request is to extend this support in systemd-networkd with more flexibility by using existing functionalities (separate section, multiple definitions, lifetimes) and new features (prefix matching, named auto-generation types, "prefixstable" RFC 7217, Anycast).

**Comment by ssahani** [comment] 2017-09-28 08:17
@maddes-b thanks I got it now.

**Comment by maddes-b** [comment] 2017-09-28 13:40
Short hint: [dhcpcd](https://roy.marples.name/projects/dhcpcd) has "prefixstable" RFC 7217 already implemented, just if converting RFC description to code gets tricky and you need a start.

**Comment by maddes-b** [comment] 2018-04-03 21:32
Is there any progress on this? Maybe even a beta I can test?

**Comment by kpfleming** [comment] 2019-01-05 13:52
The IPv6Token value is not handled by systemd-networkd, it is passed to the kernel when the link is brought up. Since the kernel's IPv6 stack only supports a single token per interface at this time, there is no value in supporting multiple token values in systemd-networkd. I too wish this was possible, but the kernel will have to be enhanced first before systemd can provide this feature.

**Comment by kpfleming** [comment] 2019-01-05 13:53
Kernel support is probably also an issue for some other aspects of this request (prefix filtering and lifetimes).

**Comment by JpegXguy** [comment] 2019-08-23 10:18
So there's no way for my non-temporary address to use RFC 7217? NetworkManager does it nicely

**Comment by ssahani** [comment] 2019-09-29 19:08
@maddes-b I am sorry finally I got time to work on this 

According to https://tools.ietf.org/html/rfc7217
RID = F(Prefix, Net_Iface, Network_ID, DAD_Counter, secret_key)

Just not sure about the secret_key ? who suppose to supply this ?

**Comment by JpegXguy** [comment] 2019-09-29 20:12
IIRC NetworkManager uses a hash that the connection uuid is part of. There's also a kernel setting net.ipv6.conf.all.stable_secret, google will help more than my limited knowledge

**Comment by JpegXguy** [comment] 2019-09-29 22:50
See this post as well: https://unix.stackexchange.com/a/255955

**Comment by kenyon** [comment] 2019-10-10 09:13
Possibly a duplicate of #4625.

**Comment by maddes-b** [comment] 2019-11-19 23:09
@kenyon Only partly.

**Closed as completed** 2020-02-05 16:05 UTC
Labels: RFE 🎁, network

**Comment by kpfleming** [comment] 2020-02-05 16:36
This issue was closed by that PR merge, but that PR only addresses items 1 and 2 from the list in the RFE. Are the other items impossible to implement, or should they be moved into another RFE issue?

**Comment by kpfleming** [comment] 2020-02-05 16:37
Also, thank you for implementing item 1 :-) It's why I came here, my network has both GUAs and ULAs and I'd like to be able to use the same token for both.

**Comment by keszybz** [comment] 2020-02-07 16:03
If something is still missing, please open a new issue. With so many PRs in flight it's hard to keep track of partially solved issues.
