### ISSUE TITLE
systemd-sysctl and procps' sysctl tool  have slightly different feature set, in regards to wildcard syntax

### ISSUE THREAD

**Issue by woodrow-shen** [systemd/systemd#17156] opened 2020-09-24 15:21 UTC
**systemd version the issue has been seen with**
246.4-1ubuntu1

**Used distribution**
Ubuntu groovy (20.10)

**Expected behaviour you didn't see**
The sysctl should not output "sysctl: setting key "net.ipv4.conf.all.promote_secondaries": Invalid argument"

**Unexpected behaviour you saw**
The command `sysctl --system` sysctl: setting key "net.ipv4.conf.all.promote_secondaries": Invalid argument

**Steps to reproduce the problem**

1. just executing sudo sysctl --system, and then the output is dumped as below:
```
* Applying /etc/sysctl.d/10-console-messages.conf ...
kernel.printk = 4 4 1 7
* Applying /etc/sysctl.d/10-ipv6-privacy.conf ...
net.ipv6.conf.all.use_tempaddr = 2
net.ipv6.conf.default.use_tempaddr = 2
* Applying /etc/sysctl.d/10-kernel-hardening.conf ...
kernel.kptr_restrict = 1
* Applying /etc/sysctl.d/10-magic-sysrq.conf ...
kernel.sysrq = 176
* Applying /etc/sysctl.d/10-network-security.conf ...
net.ipv4.conf.default.rp_filter = 2
net.ipv4.conf.all.rp_filter = 2
* Applying /etc/sysctl.d/10-ptrace.conf ...
kernel.yama.ptrace_scope = 1
* Applying /etc/sysctl.d/10-zeropage.conf ...
vm.mmap_min_addr = 65536
* Applying /usr/lib/sysctl.d/30-tracker.conf ...
fs.inotify.max_user_watches = 65536
* Applying /usr/lib/sysctl.d/50-default.conf ...
net.ipv4.conf.default.promote_secondaries = 1
sysctl: setting key "net.ipv4.conf.all.promote_secondaries": Invalid argument
net.ipv4.ping_group_range = 0 2147483647
...
```

Obviously that key came from /usr/lib/sysctl.d/50-default.conf, and maybe there are some reasons to the extent that we meet this, so I'm trying to post the issue here for clarification. 

Thanks.

**Comment by poettering** [comment] 2020-09-25 07:28
This was introduced in ad8bc9ea508740074cead005aa3cfd1ba10a5dac

@michaelolbrich any idea what might be going on here?

@woodrow-shen what happens if you issue `SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/systemd-sysctl to apply those files?

/cc @keszybz 

I must say I don#t grok these lines myself, i.e. since 5d4fc0e665a3639f92ac880896c56f9533441307 we appear to set the default sysctl twice, because there's now both: `net.ipv4.conf.default.promote_secondaries` and `net.ipv4.conf.*.promote_secondaries`, and the latter should cover the former anyway...

Not sure why the kernel returns EINVAL on these though

**Comment by michaelolbrich** [comment] 2020-09-25 09:40
> @michaelolbrich any idea what might be going on here?

I'm not an expert sysctl but I think this is caused by mixing `sysctl` and `systemd-sysctl`. The config file syntax is different.

If I pass the `promote_secondaries` lines from `50-default.conf` to `systemd-sysctl` then `net.ipv4.conf.all.promote_secondaries` is not touched at all. However `sysctl` tries to write "=" to the file. This obviously fails.

Note: I tried this on Debian.

> I must say I don#t grok these lines myself, i.e. since [5d4fc0e](https://github.com/systemd/systemd/commit/5d4fc0e665a3639f92ac880896c56f9533441307) we appear to set the default sysctl twice, because there's now both: `net.ipv4.conf.default.promote_secondaries` and `net.ipv4.conf.*.promote_secondaries`, and the latter should cover the former anyway...

This is important to avoid race conditions: `default` must be set first to ensure that new interfaces that show up while changing this, get the correct value.

> Not sure why the kernel returns EINVAL on these though

**Comment by poettering** [comment] 2020-09-28 15:16
> This is important to avoid race conditions: `default` must be set first to ensure that new interfaces that show up while changing this, get the correct value.

Makes sense

**Comment by poettering** [comment] 2020-09-28 15:17
So the glob syntax was introduced in e0f424790d3dbde136a29a7fa4c2777c2e3fd695.

**Comment by poettering** [comment] 2020-09-28 15:19
So I guess we extended the syntax of the drop-ins here without letting procps people know. Or were they notified? @keszybz?

**Comment by woodrow-shen** [comment] 2020-10-09 03:29
@poettering 

Hi sorry for late reply...
Here's the output of `SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/systemd-sysctl`
```
$ sudo SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/systemd-sysctl /usr/lib/sysctl.d/50-default.conf
Parsing /usr/lib/sysctl.d/50-default.conf
Setting 'net/ipv4/conf/default/promote_secondaries' to '1'.
Not setting net/ipv4/conf/all/promote_secondaries (explicit setting exists).
Not setting net/ipv4/conf/default/promote_secondaries (explicit setting exists).
Setting 'net/ipv4/conf/docker0/promote_secondaries' to '1'.
Setting 'net/ipv4/conf/eno1/promote_secondaries' to '1'.
Setting 'net/ipv4/conf/flannel.1/promote_secondaries' to '1'.
Setting 'net/ipv4/conf/lo/promote_secondaries' to '1'.
Setting 'net/ipv4/conf/wlp58s0/promote_secondaries' to '1'.
Setting 'net/ipv4/ping_group_range' to '0 2147483647'.
Setting 'net/core/default_qdisc' to 'fq_codel'.
Setting 'fs/protected_regular' to '1'.
Setting 'fs/protected_fifos' to '1'.
```

**Comment by pmmalinov01** [comment] 2021-01-07 06:57
I am getting this with:

```
root@k8spavelubuntu1:~# sysctl --system | grep net.bridge
sysctl: setting key "net.ipv4.conf.all.promote_secondaries": Invalid argument
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
```

Also running on 
```
root@k8spavelubuntu1:~# lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
5.4.0-52-generic
```

**Comment by ratulb** [comment] 2021-01-21 23:13
sysctl: setting key "net.ipv4.conf.all.promote_secondaries": Invalid argument 
Facing the same issue - kuberenetes install on containerd.

Have we found what the issue is?

**Comment by ratulb** [comment] 2021-01-21 23:13
I am facing this on ubuntu 18.04.

**Comment by johnnyutahh** [comment] 2021-01-30 02:14
1. Any updates on better-understanding the root cause and/or delivering a potential fix?
2. Is this symptom benign or can it cause any significant problems?

I too am seeing same behavior on Ubuntu 20.04.1 LTS.

( @poettering @keszybz @michaelolbrich )

**Comment by oldthreefeng** [comment] 2021-02-02 07:36
> Facing the same issue - kuberenetes install on containerd.

whats the main problem you are facing on?  cannot communicate with other nodes?

**Comment by michaelolbrich** [comment] 2021-02-07 12:22
My understanding is that `sysctl` and `systemd-sysctl` are two tools that basically have the same job (is this correct @poettering?).

However, as I noted above, they do not understand exactly the same syntax. So what happens here is that `sysctl` tries to read config files for `systemd-sysctl` and fails. So I guess that this is a distro/packaging issue? I'm not sure how the two should interact.

**Comment by poettering** [comment] 2021-02-12 23:50
@michaelolbrich that's mostly correct.

So initially the sysctl.d/ thing was a systemd thing, but since has been added to procps' sysctl too. 

They nowadays understand mostly the same syntax. The `*` syntax is unique to systemd though, and when this was added to systemd we didn't ask them to support it to. We should probably do that now.

**Comment by poettering** [comment] 2021-02-12 23:51
@keszybz or did I miss anything? when the wildcard syntax was added, was anyone from procps informed?

**Comment by keszybz** [comment] 2021-02-13 09:37
> So I guess we extended the syntax of the drop-ins here without letting procps people know. Or were they notified? @keszybz?

No, afaik. I opened https://gitlab.com/procps-ng/procps/-/issues/191 now.

> I'm not an expert sysctl but I think this is caused by mixing `sysctl` and `systemd-sysctl`. The config file syntax is different.

Yeah. It is rather strange to use sysctl when you have systemd-sysctl installed on the same system.

Let's close this here.

**Closed as completed by keszybz** 2021-02-13 09:37 UTC
Labels: sysctl

**Comment by poettering** [comment] 2021-02-14 14:45
@keszybz thanks for filing the issue (thankfully, last time — https://gitlab.com/procps-ng/procps/-/issues/138 — the procps-ng maintainer quickly reacted to our issue, let's hope this time, too!)
