### ISSUE TITLE
Support for multiple FIDO2 keys

### ISSUE THREAD

**Issue by Diaoul** [systemd/systemd#20822] opened 2021-09-23 20:02 UTC
**Is your feature request related to a problem? Please describe.**
At boot, when multiple FIDO2 keys are enrolled, they are all ignored and skipped, falling back to password without notification of error. Running manual attach reveals the issue:
```bash
$ sudo /usr/lib/systemd/systemd-cryptsetup attach mytest /dev/sda1 - fido2-device=auto
Set cipher aes, mode xts-plain64, key size 512 bits for device /dev/sda1.
Multiple FIDO2 tokens enrolled, cannot automatically determine token.
```

**Describe the solution you'd like**
- Support for multiple keys
- Documentation about this limitation. It is common practice to enroll multiple keys in case one is lost or stolen, which is impossible here.
- Combined with #19872 this means, currently, a single key is supported an no fallback to password possible.

**Describe alternatives you've considered**
Create another bootloader entry, disabling the `fido2-device=auto` option to at least have the ability to boot with a password.

**The systemd version you checked that didn't have the feature you are asking for**
249

Note that crypttab has some `fido2-cid` option that may come to the rescue here, maybe there is a way to use that but I have not find the documentation about how to get this base64 Client ID from enrolled keys

**Comment by poettering** [comment] 2021-09-24 07:24
So this is harder to implement than it sounds. The thing is that fido2 devices do not have an identification of any kind. We know they are fido2 devices, but we don't know which one. This means we can attempt to authenticate them, which means asking them a question they can only answer if they are the right one. But that question typically also involves interactivity, i.e. the user has to touch the token for the answer to be returned to the OS. This means if you enroll multiple tokens and you plug one of them in, then we have to ask it a question that might or might not be the right one for it. If it's the wrong one, we have to check if it's the next enrolled token, and so on. But that means the user each time has to touch the token. That#s just very user unfriendly.

**Comment by Diaoul** [comment] 2021-09-24 07:35
That's indeed not something I would want to use. Given that FIDO2 devices aren't just usually FIDO2, can we rely on some other interface to provide key identification and pair that with a particular FIDO2 key-slot?
I know my computer can identify I've inserted the wrong Yubikey by using its serial number without me touching the device, probably there is a way to get that information. Is there such an interface that could be used with a large number of FIDO2-compatible devices?

Even if not user friendly, we can imagine having a primary key that is always expected and when that fails, try the backup key. It's not very user friendly but given one has just lost his key, this is a fine fallback. I think would cover most of the use cases out there, very few people use 2 keys interchangeably IMO.

**Comment by poettering** [comment] 2021-09-24 07:55
pkcs#11 devices have a serial, fido2 devices not. at least i am not aware of any property like that.

**Comment by poettering** [comment] 2021-09-24 07:56
Duplicate of #19208

**Closed as completed by poettering** 2021-09-24 07:56 UTC
Labels: cryptsetup, fido2
