### ISSUE TITLE
journalctl -f as a user does not follow the journal

### ISSUE THREAD

**Issue by samueltardieu** [systemd/systemd#2321] opened 2016-01-14 09:42 UTC
Hi.

I have a timer-run (every 6 hours) program `episodes.py` and since I'd like to check its activitiy I happened to run

```
% journalctl -t episodes.py -f -q
```

However, while I properly see the initial log, I cannot see new traces unless I interrupt then re-run this command. `-f` as a user seems to block (`journalctl` does not return spontaneously) but not to follow the journal.

For info:

```
% systemctl --version
systemd 228
+PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP -LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL -XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN
```

**Comment by moviuro** [comment] 2016-01-18 07:36
I have a similar issue.

``` sh
$ journalctl -f
```

This opens the latest entries of the journal, then seems to block, and then spats out the entirety (?) of the journal before stopping at an other date (Oct 18 in my case) and not following anymore.

``` sh
systemd 228
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
```

**Comment by poettering** [comment] 2016-01-27 01:35
Hmm, could you please run journalctl lke this in strace until it settles, then generate a new log message with a tool like "logger" from a different terminal, and check the precise syscalls that this logger call results in. Then, please attach the generate strace excerpt generated by the logger call here.

**Comment by samueltardieu** [comment] 2016-01-28 21:41
It has been running for more than 24 hours now and I cannot reproduce the problem. I'll try again, and propose and close the issue in a few days if I (or @moviuro) can't reproduce it.

**Comment by moviuro** [comment] 2016-01-29 14:08
@samueltardieu I'm not on my computer ATM, I'll provide feedback on Jan, 30th around 10am UTC

**Comment by moviuro** [comment] 2016-01-30 16:52
See https://github.com/moviuro/systemd-issue

**Comment by poettering** [comment] 2016-08-31 11:55
Closing as the issue supposedly wasn't reproducible.

**Closed as completed by poettering** 2016-08-31 11:55 UTC
Labels: journal, needs-reporter-feedback ❓

**Comment by joonas-fi** [comment] 2022-02-05 08:44
I have this issue: `-f` isn't seeing new entries. Running it again I see the new entries that `-f` didn't produce.

It is worth noting that I think I'm running short of inotify watches due to Sublime Text (follows symlinks on project dir and tries to set up inotify for basically my whole computer). I see a log entry in my service:

```
systemd[32505]: notifymerge.service: Failed to add control inotify watch descriptor for control group /user.slice/user-1000.slice/user@1000.service/notifymerge.service: No space left on device
```

The control group filesystem has space (but like I said above, the inotify watches themselves have run out due to Sublime Text):

```console
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
tmpfs            15G     0   15G   0% /sys/fs/cgroup
```

systemd version:

```
systemd 245 (245.4-4ubuntu3.13)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

**Comment by poettering** [comment] 2022-02-07 09:54
@joonas-fi yeah, if your editor eats up all inotify watches nothing else can use it. It's a bug in your editor.

**Comment by joonas-fi** [comment] 2022-02-07 17:28
I agree, it's a bug in the editor that all available inotify watches were consumed.

But let's switch to systemd perspective. As a user I didn't know `$ journalctl -f -u ...` needs inotify under the covers.

I legitimately thought it's a bug in systemd, follow not working.

I know there's nothing systemd can do to fix the fact that inotify watches have ran out.

BUT could we add a warning, when the user tries to run the above command, that it's not going to work due to insufficient inotify watches? Something like if follow flag is defined and inotify watches not available => warn the user and explain the situation.

**Comment by poettering** [comment] 2022-02-08 10:02
There's a warning in less ancient versions systemd.
