### ISSUE TITLE
don't invoke a shell for sulogin services

### ISSUE THREAD

**Issue by poettering** [systemd/systemd#5674] opened 2017-03-30 14:54 UTC
#5623 introduces a boot-time shell script to systemd. I am not sure I like that. I'd prefer if we could find a different way to clean this up. For example, if we make sure that if if "-" is used in ExecStart=, and the specified binary doesn't exist, we log this at LOG_DEBUG level only and skip it, then we'd also have much of the ugliness removed.

**Comment by mbiebl** [comment] 2017-03-30 15:05
What you proposed is a duplicate of #5621

As for the remaining ugliness, any idea how to make

```
ExecStartPre=-/bin/echo -e 'You are in emergency mode. After logging in, type "journalctl -xb" to view\\nsystem logs, "systemctl reboot" to reboot, "systemctl default" or ^D to\\ntry again to boot into default mode.'
```
more readable?

What are we going to do about
```
ExecStart=-/bin/sh -c "@SULOGIN@; @SYSTEMCTL@ --job-mode=fail --no-block default"
```

If you don't like shell, the only way I see is to implement that in C

**Comment by poettering** [comment] 2017-03-30 15:10
> If you don't like shell, the only way I see is to implement that in C

I think that'd be an option too... We have C wrappers around fsck and quotaon too, so having one around sulogin doesn't sound totally off either... And the code would be trivial...

**Comment by mbiebl** [comment] 2017-05-30 16:45
@poettering I was just pointed at the fact that the usage of heredocs in systemd-sulogin-shell is problematic, as bash will uses temporary files for heredocs (dash doesn't apparently).
If your /tmp directory is not writable, this will lead to the following error message:
```
/usr/lib/systemd/systemd-sulogin-shell: line 7: cannot create temp file for here-document: Read-only file system
```
A quick fix is to use echo, but then again, if you want to drop systemd-sulogin-shell anyway, this might be a pointless change. I see that @keszybz postponed this to v235, so, should this be fixed for v234?
What's your opinion on this?

**Comment by keszybz** [comment] 2017-05-30 16:49
Yeah, we should change that to use echo, as a short term fix for v234. Moving back.

**Comment by keszybz** [comment] 2017-05-30 16:50
Or actually nvm, sorry for the noise, let's add a new issue to track this.

**Comment by marcosfrm** [comment] 2017-06-04 21:39
My systems have root account locked. In 232, I edit locally `rescue.service` and `emergency.service` (`systemctl edit --full`) and add `--force` to `sulogin` invocation. Maybe this use case is relevant?

Related Debian bug report:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=806852

**Comment by keszybz** [comment] 2017-06-06 15:48
A short status update:
- with #6052 we don't use heredocs so read-only /tmp is supported again
- with #5621 we could use `ExecStart=-/usr/bin/plymouth` again, but we still don't have a solution for other shell logic.

**Closed as completed** 2017-09-08 16:21 UTC
Labels: units

**Comment by mbiebl** [comment] 2017-09-08 16:38
> My systems have root account locked. In 232, I edit locally rescue.service and emergency.service (systemctl edit --full) and add --force to sulogin invocation. Maybe this use case is relevant?
> 

This is still supported. You can override ExecStart of rescue.service and emergency.service and use the sulogin parameters you want. I.e. you'd replace 
```
ExecStart=-/lib/systemd/system/systemd-sulogin-shell emergency
```
with something to your liking, possibly to what was used before, like:
```
ExecStartPre=-/bin/echo -e 'You are in emergency mode. After logging in, type "journalctl -xb" to view\\nsystem logs, "systemctl reboot" to reboot, "systemctl default" or ^D to\\ntry again to boot into default mode.'
ExecStart=-/bin/sh -c "/sbin/sulogin --force; /bin/systemctl --job-mode=fail --no-block default"
```
