### ISSUE TITLE
networkd: IPv6 address is lost after router reconnects to ISP

### ISSUE THREAD

**Issue by jaystrictor** [systemd/systemd#3879] opened 2016-08-03 11:20 UTC
### Submission type
- [x] Bug report
### systemd version the issue has been seen with

> systemd 231
### Used distribution

> ArchLinux ARM on a RaspberryPi2
### In case of bug report: Expected behaviour you didn't see

When the router of my local network reconnects to the ISP (and thus changes the IPv6 prefix), I want the device to obtain a new IPv6 address via DHCPv6 or RA.
### In case of bug report: Unexpected behaviour you saw

When the router reconnects, the device loses the IPv6 addresses for Global Unicast and for Unique Local Unicast after some time. (The IPv6 address for Link Local and the IPv4 address remain.)
In the logs, it shows

```
wlan0: Could not set NDisc route or address: Invalid argument
wlan0: Failed
```

I can fix this by running `systemctl restart systemd-networkd.service`: new IPv6 addresses are obtained.
### In case of bug report: Steps to reproduce the problem

Configure systemd-networkd with 

```
[Match]
Name=wl*

[Network]
DHCP=yes

[DHCP]
RouteMetric=20
```

and buy a FritzBox 7360 router. Wait for the nightly disconnect to happen.

Attached:
- [log of the router](https://github.com/systemd/systemd/files/399304/fritz.log.txt)
- [log of the device with networkd LOG_LEVEL=debug](https://github.com/systemd/systemd/files/399303/journal.log.txt)

**Comment by vindicatorr** [comment] 2016-08-03 11:35
That's an old (still open issue): https://github.com/systemd/systemd/issues/2365

**Comment by jaystrictor** [comment] 2016-08-03 14:13
@vindicatorr: I read #2365, but there it says that the problem occurs when restarting networkd. My issue can be fixed temporarily by restarting networkd.

**Comment by vcaputo** [comment] 2016-09-08 00:28
@poettering @teg it seems to me we really need to improve the debugging instrumentation in `systemd-networkd`.  There's no trivial way for a user to get logs of what route and/or address configuration was attempted when `ndisc_netlink_handler()` encounters an error.  To further complicate troubleshooting, multiple code-paths supply this handler, and when errno is EINVAL for example the user really should be shown what was attempted that is invalid.

Do you guys have a preferred approach for adding such context to the logged error output without creating a bunch of different flavors of `ndisc_netlink_handler()`?

**Comment by teg** [comment] 2016-09-08 08:56
Hmm, not sure what a nice way would be.

**Comment by florianjacob** [comment] 2016-12-02 13:48
I can confirm this specific problem still exists, using systemd 232.

I'm running a server that is connected to a fritzbox as well, but via ethernet.

**Comment by heftig** [comment] 2016-12-02 14:09
Ditto; this is rather annoying and the reason I'm using NM instead of networkd for my NAS.

**Comment by lloesche** [comment] 2017-01-20 22:58
Yup can confirm, whenever my ISP assigns a new v6 prefix (once or twice a day) the interface loses its IP address. Interestingly it also loses its fdxx address which isn't assigned by the ISP of course but the router itself.

I.e. upon boot the box will have v4 and v6 connectivity then after ISP reconnect it'll lose both v6 addresses that were originally assigned by the router (AVM Fritzbox), one of which is from the ISP assigned prefix and the other from an internal fd00 prefix. When I restart networkd it'll have routed addresses again until the next prefix update from the ISP.
The address is assigned via SLAAC the DNS via DHCPv6.
```
[root@blackhole ~]# ip -6 -br a s br0
br0              UP             fe80::f460:b9ff:fee6:1978/64
[root@blackhole ~]# systemctl restart systemd-networkd
[root@blackhole ~]# ip -6 -br a s br0
br0              UP             fd00::f460:b9ff:fee6:1978/64 2a02:2028:73a:f301:f460:b9ff:fee6:1978/64 fe80::f460:b9ff:fee6:1978/64
```

The interface's config is pretty barebones
```
[Match]
Name=br0

[Network]
IPv6AcceptRA=true
IPv6PrivacyExtensions=no
```

This is on systemd-231-10.fc25.x86_64

**Comment by 9er** [comment] 2017-01-23 07:54
What the? I just lost some IPv6-only servers out there on the internet, because of this bug. They run systemd-232 on ARM.

I still don't understand completely why this happens. Is there any workaround, until this is resolved?

**Comment by TheAifam5** [comment] 2017-02-07 01:41
Nope. But @systemd team "REPAIRED" that bug already :D : https://github.com/systemd/systemd/issues/2228

Workaround: Disable IPv6 temporary.

**Comment by 9er** [comment] 2017-02-07 10:44
I only have IPv6.

My workaround is a cronjob that calls `systemctl restart networkd` every minute. It's incredibly stupid, but it works...

**Comment by florianjacob** [comment] 2017-02-07 11:41
@9er A workaround is a workaround. 😆 I'm adding a timer now as well.

**Comment by jwwalton** [comment] 2017-02-09 09:47
There are probably 10-20 million+ devices of this vendor in Germany alone. It seems kinda weird that this is still broken? Of course complaining doesn't help either..

**Comment by heftig** [comment] 2017-02-09 09:51
@jwwalton Doesn't seem all that surprising to me; No distribution (to my knowledge) uses systemd-networkd as the default network handler outside of certain container setups, where either IPv6 is unused or the router is not doing whatever the Fritz!Boxes do.

FWIW, NetworkManager with the internal systemd-dhcp seems not to be affected by this.

**Comment by hendrikw01** [comment] 2017-03-25 12:24
If have analysed the Router Advertisement on a reconnect:
[changed.txt](https://github.com/systemd/systemd/files/869993/changed.txt)

The router sends the old prefix with a lifetime of 0 to state that this prefix should not be used anymore. This breaks ndisc.

My pull request simply removes the old address attached with the old prefix. This should be no problem because all connections with this address are closed by the router anyways.

**Closed as completed** 2017-03-31 13:11 UTC
Labels: network
