### ISSUE TITLE
hwdb commit to swap buttons for the Logitech Lift also swaps buttons for the MX Master 3s

### ISSUE THREAD

**Issue by zoku88** [systemd/systemd#26671] opened 2023-03-04 20:13 UTC
### systemd version the issue has been seen with

systemd 253.1-1 [core] (x86_64)

### Used distribution

Arch Linux

### Linux kernel version used

6.2.2-zen1-1-zen

### CPU architectures issue was seen on

x86_64

### Component

systemd-hwdb

### Expected behaviour you didn't see

For the left and right mouse button to work as intended.

### Unexpected behaviour you saw

Logitech Bolt Receiver id that I got with the MX Master 3S matches the usb ID's of the Logitech Lift, causing the buttons to be swapped.

lsusb:
Bus 001 Device 008: ID 046d:c548 Logitech, Inc. Logi Bolt Receiver
```
/usr/lib/udev/hwdb.d/60-keyboard.hwdb 
# Logitech USB Receiver Mouse (Lift for Business, left-handed)
# This left-handed ergonomic mouse swaps the left/right buttons
evdev:input:b0003v046DpC548e0111*
 KEYBOARD_KEY_90001=btn_right
 KEYBOARD_KEY_90002=btn_left
```
Introduced by commit:
https://github.com/systemd/systemd/commit/81cfea95e51c72da6765b517e7038b3e7e3dec9f

### Steps to reproduce the problem

Buttons will be swapped when default rules are loaded.

### Additional program output to the terminal or log subsystem illustrating the issue

Not sure if anything in the below udevadm output can be used to differentiate this from the Lift.
```
udevadm info /dev/input/mouse0

P: /devices/pci0000:00/0000:00:01.1/0000:01:00.0/usb1/1-12/1-12:1.1/0003:046D:C548.001A/input/input45/mouse0
M: mouse0
R: 0
U: input
D: c 13:32
N: input/mouse0
L: 0
S: input/by-path/pci-0000:01:00.0-usb-0:12:1.1-mouse
S: input/by-id/usb-Logitech_USB_Receiver-if01-mouse
E: DEVPATH=/devices/pci0000:00/0000:00:01.1/0000:01:00.0/usb1/1-12/1-12:1.1/0003:046D:C548.001A/input/input45/mouse0
E: DEVNAME=/dev/input/mouse0
E: MAJOR=13
E: MINOR=32
E: SUBSYSTEM=input
E: USEC_INITIALIZED=1071058860
E: ID_INPUT=1
E: ID_INPUT_MOUSE=1
E: ID_BUS=usb
E: ID_MODEL=USB_Receiver
E: ID_MODEL_ENC=USB\x20Receiver
E: ID_MODEL_ID=c548
E: ID_SERIAL=Logitech_USB_Receiver
E: ID_VENDOR=Logitech
E: ID_VENDOR_ENC=Logitech
E: ID_VENDOR_ID=046d
E: ID_REVISION=0501
E: ID_TYPE=hid
E: ID_USB_MODEL=USB_Receiver
E: ID_USB_MODEL_ENC=USB\x20Receiver
E: ID_USB_MODEL_ID=c548
E: ID_USB_SERIAL=Logitech_USB_Receiver
E: ID_USB_VENDOR=Logitech
E: ID_USB_VENDOR_ENC=Logitech
E: ID_USB_VENDOR_ID=046d
E: ID_USB_REVISION=0501
E: ID_USB_TYPE=hid
E: ID_USB_INTERFACES=:030101:030102:030000:
E: ID_USB_INTERFACE_NUM=01
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:01:00.0-usb-0:12:1.1
E: ID_PATH_TAG=pci-0000_01_00_0-usb-0_12_1_1
E: DEVLINKS=/dev/input/by-path/pci-0000:01:00.0-usb-0:12:1.1-mouse /dev/input/by-id/usb-Logitech_USB_Receiver-if01-mouse
```

**Comment by yuwata** [comment] 2023-03-05 04:09
Fix is waiting in #26677.

**Comment by yuwata** [comment] 2023-03-05 04:12
@zoku88 and @encombhat Could you show `/sys/class/input/eventXX/device/modalias`? That may help @vit-zikmund to update the hwdb entry.

**Comment by zoku88** [comment] 2023-03-05 04:21
Mine looks like this:
`input:b0003v046DpC548e0111-e0,1,4,11,14,k74,75,77,7A,7B,7C,7D,7E,7F,B7,B8,B9,BA,BB,BC,BD,BE,BF,C0,C1,C2,ram4,l0,1,2,3,4,sfw
`

**Comment by JordanP-Dev** [comment] 2023-03-05 04:37
Mine is identical to the modalias @vit-zikmund has for the Lift mouse:
`input:b0003v046DpC548e0111-e0,1,2,4,k110,111,112,113,114,115,116,117,118,119,11A,11B,11C,11D,11E,11F,r0,1,6,8,B,C,am4,lsfw`

**Comment by zoku88** [comment] 2023-03-05 04:42
Apologies, I grabbed the wrong receiver event (kbd).

The modalias  for the mouse is:
`input:b0003v046DpC548e0111-e0,1,2,4,k110,111,112,113,114,115,116,117,118,119,11A,11B,11C,11D,11E,11F,r0,1,6,8,B,C,am4,lsfw
`

**Comment by encombhat** [comment] 2023-03-05 07:45
Same here.
```sh
$ cat /sys/class/input/event4/device/modalias
input:b0003v046DpC548e0111-e0,1,2,4,k110,111,112,113,114,115,116,117,118,119,11A,11B,11C,11D,11E,11F,r0,1,6,8,B,C,am4,lsfw
```

**Comment by amezin** [comment] 2023-03-05 08:16
@yuwata @vit-zikmund The same receiver device can be paired with Lift or MX Master (maybe even with both simultaneously).

Probably swapping mouse buttons based on the receiver modalias is not the correct approach here.

Also, are you sure the behavior you tried to fix wasn't intentional?

**Comment by 0atman** [comment] 2023-03-05 12:13
MX Master 3s user here, my life just got twist-turned upside down by this bug too!

No reboot needed, happened right after my morning upgrade.

```
$ cat /sys/class/input/event4/device/modalias
input:b0003v046DpC548e0111-e0,1,4,11,14,k74,75,77,7A,7B,7C,7D,7E,7F,B7,B8,B9,BA,BB,BC,BD,BE,BF,C0,C1,C2,ram4,l0,1,2,3,4,sfw
```

Thanks to those working on this :heart:

**Comment by vit-zikmund** [comment] 2023-03-05 16:11
Sincere apologies everyone!
Please would anyone else post the `udevadm info /dev/input/mouseX` so I could try to find some differences to make the patch better targeted (if possible at all)?
I had no clue the modalias belongs to the bolt receiver, since it's flagged as a pointer device... This is rather disappointing, but hopefully there's a way out.

@amezin I believe the change is really intentional, as it works the same even in windows and the vendor software. As both Linux and Win seem to have only a single global setting about the left/right mouse button priority, even the Logitech's internal toggle moves the global one, I don't know who was hallucinating about making this vice-versa just for this lefthander model. I'm occasionally using a touchpad, too, where I'm not having the buttons swapped, using it with this mouse makes me twitch. I assume if I'd want the buttons swapped, I'd just use the OS settings and not rely on a single device that does so on its own *facepalm*.

**Comment by mb1986** [comment] 2023-03-05 18:32
```
P: /devices/pci0000:00/0000:00:14.0/usb3/3-3/3-3.3/3-3.3:1.1/0003:046D:C548.0002/input/input10/mouse0
M: mouse0
R: 0
U: input
D: c 13:32
N: input/mouse0
L: 0
S: input/by-id/usb-Logitech_USB_Receiver-if01-mouse
S: input/by-path/pci-0000:00:14.0-usb-0:3.3:1.1-mouse
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb3/3-3/3-3.3/3-3.3:1.1/0003:046D:C548.0002/input/input10/mouse0
E: DEVNAME=/dev/input/mouse0
E: MAJOR=13
E: MINOR=32
E: SUBSYSTEM=input
E: USEC_INITIALIZED=7466716
E: ID_INPUT=1
E: ID_INPUT_MOUSE=1
E: ID_BUS=usb
E: ID_MODEL=USB_Receiver
E: ID_MODEL_ENC=USB\x20Receiver
E: ID_MODEL_ID=c548
E: ID_SERIAL=Logitech_USB_Receiver
E: ID_VENDOR=Logitech
E: ID_VENDOR_ENC=Logitech
E: ID_VENDOR_ID=046d
E: ID_REVISION=0501
E: ID_TYPE=hid
E: ID_USB_MODEL=USB_Receiver
E: ID_USB_MODEL_ENC=USB\x20Receiver
E: ID_USB_MODEL_ID=c548
E: ID_USB_SERIAL=Logitech_USB_Receiver
E: ID_USB_VENDOR=Logitech
E: ID_USB_VENDOR_ENC=Logitech
E: ID_USB_VENDOR_ID=046d
E: ID_USB_REVISION=0501
E: ID_USB_TYPE=hid
E: ID_USB_INTERFACES=:030101:030102:030000:
E: ID_USB_INTERFACE_NUM=01
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:00:14.0-usb-0:3.3:1.1
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_3_3_1_1
E: DEVLINKS=/dev/input/by-id/usb-Logitech_USB_Receiver-if01-mouse /dev/input/by-path/pci-0000:00:14.0-usb-0:3.3:1.1-mouse
```

**Comment by geloczigeri** [comment] 2023-03-05 19:28
Hi Everyone, 

My Logitech MX Master 3S also swapped buttons:

```
P: /devices/pci0000:00/0000:00:08.1/0000:0c:00.3/usb3/3-2/3-2.2/3-2.2:1.1/0003:046D:C548.0005/input/input7/mouse0
M: mouse0
R: 0
U: input
D: c 13:32
N: input/mouse0
L: 0
S: input/by-path/pci-0000:0c:00.3-usb-0:2.2:1.1-mouse
S: input/by-id/usb-Logitech_USB_Receiver-if01-mouse
E: DEVPATH=/devices/pci0000:00/0000:00:08.1/0000:0c:00.3/usb3/3-2/3-2.2/3-2.2:1.1/0003:046D:C548.0005/input/input7/mouse0
E: DEVNAME=/dev/input/mouse0
E: MAJOR=13
E: MINOR=32
E: SUBSYSTEM=input
E: USEC_INITIALIZED=9459595
E: ID_INPUT=1
E: ID_INPUT_MOUSE=1
E: ID_BUS=usb
E: ID_MODEL=USB_Receiver
E: ID_MODEL_ENC=USB\x20Receiver
E: ID_MODEL_ID=c548
E: ID_SERIAL=Logitech_USB_Receiver
E: ID_VENDOR=Logitech
E: ID_VENDOR_ENC=Logitech
E: ID_VENDOR_ID=046d
E: ID_REVISION=0501
E: ID_TYPE=hid
E: ID_USB_MODEL=USB_Receiver
E: ID_USB_MODEL_ENC=USB\x20Receiver
E: ID_USB_MODEL_ID=c548
E: ID_USB_SERIAL=Logitech_USB_Receiver
E: ID_USB_VENDOR=Logitech
E: ID_USB_VENDOR_ENC=Logitech
E: ID_USB_VENDOR_ID=046d
E: ID_USB_REVISION=0501
E: ID_USB_TYPE=hid
E: ID_USB_INTERFACES=:030101:030102:030000:
E: ID_USB_INTERFACE_NUM=01
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:0c:00.3-usb-0:2.2:1.1
E: ID_PATH_TAG=pci-0000_0c_00_3-usb-0_2_2_1_1
E: DEVLINKS=/dev/input/by-path/pci-0000:0c:00.3-usb-0:2.2:1.1-mouse /dev/input/by-id/usb-Logitech_USB_Receiver-if01-mouse

```

**Comment by korteland** [comment] 2023-03-06 12:06
My MX Master 3S with swapped buttons:

```
P: /devices/pci0000:00/0000:00:02.1/0000:05:00.0/0000:06:0c.0/0000:11:00.0/usb2/2-3/2-3:1.1/0003:046D:C548.000A/input/input30/mouse2
M: mouse2
R: 2
U: input
D: c 13:34
N: input/mouse2
L: 0
S: input/by-id/usb-Logitech_USB_Receiver-if01-mouse
S: input/by-path/pci-0000:11:00.0-usb-0:3:1.1-mouse
E: DEVPATH=/devices/pci0000:00/0000:00:02.1/0000:05:00.0/0000:06:0c.0/0000:11:00.0/usb2/2-3/2-3:1.1/0003:046D:C548.000A/input/input30/mouse2
E: DEVNAME=/dev/input/mouse2
E: MAJOR=13
E: MINOR=34
E: SUBSYSTEM=input
E: USEC_INITIALIZED=1826319189
E: ID_INPUT=1
E: ID_INPUT_MOUSE=1
E: ID_BUS=usb
E: ID_MODEL=USB_Receiver
E: ID_MODEL_ENC=USB\x20Receiver
E: ID_MODEL_ID=c548
E: ID_SERIAL=Logitech_USB_Receiver
E: ID_VENDOR=Logitech
E: ID_VENDOR_ENC=Logitech
E: ID_VENDOR_ID=046d
E: ID_REVISION=0501
E: ID_TYPE=hid
E: ID_USB_MODEL=USB_Receiver
E: ID_USB_MODEL_ENC=USB\x20Receiver
E: ID_USB_MODEL_ID=c548
E: ID_USB_SERIAL=Logitech_USB_Receiver
E: ID_USB_VENDOR=Logitech
E: ID_USB_VENDOR_ENC=Logitech
E: ID_USB_VENDOR_ID=046d
E: ID_USB_REVISION=0501
E: ID_USB_TYPE=hid
E: ID_USB_INTERFACES=:030101:030102:030000:
E: ID_USB_INTERFACE_NUM=01
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:11:00.0-usb-0:3:1.1
E: ID_PATH_TAG=pci-0000_11_00_0-usb-0_3_1_1
E: DEVLINKS=/dev/input/by-id/usb-Logitech_USB_Receiver-if01-mouse /dev/input/by-path/pci-0000:11:00.0-usb-0:3:1.1-mouse
```

Thanks to everyone working on this - sounds like Logitech isn't making it easy for you.

**Comment by vit-zikmund** [comment] 2023-03-06 15:39
Thank you everyone for your contributions, but I must say I haven't find any native systemd/udev way to detect a particular mouse attached to the universal Logitech wireless receiver - which is the thing we're actually addressing here.

<details><summary>FWIW here's my receiver <code>udevadm info</code>, but there seems to be nothing interesting:</summary>

```
P: /devices/pci0000:00/0000:00:1c.4/0000:02:00.0/0000:03:01.0/0000:05:00.0/0000:06:02.0/0000:07:00.0/usb5/5-2/5-2.1/5-2.1.3/5-2.1.3.2/5-2.1.3.2:1.1/0003:046D:C548.001C/input/input61/mouse3
M: mouse3
R: 3
U: input
D: c 13:35
N: input/mouse3
L: 0
S: input/by-path/pci-0000:07:00.0-usb-0:2.1.3.2:1.1-mouse
S: input/by-id/usb-Logitech_USB_Receiver-if01-mouse
E: DEVPATH=/devices/pci0000:00/0000:00:1c.4/0000:02:00.0/0000:03:01.0/0000:05:00.0/0000:06:02.0/0000:07:00.0/usb5/5-2/5-2.1/5-2.1.3/5-2.1.3.2/5-2.1.3.2:1.1/0003:046D:C548.001C/input/input61/mouse3
E: DEVNAME=/dev/input/mouse3
E: MAJOR=13
E: MINOR=35
E: SUBSYSTEM=input
E: USEC_INITIALIZED=374722250833
E: ID_INPUT=1
E: ID_INPUT_MOUSE=1
E: ID_BUS=usb
E: ID_MODEL=USB_Receiver
E: ID_MODEL_ENC=USB\x20Receiver
E: ID_MODEL_ID=c548
E: ID_SERIAL=Logitech_USB_Receiver
E: ID_VENDOR=Logitech
E: ID_VENDOR_ENC=Logitech
E: ID_VENDOR_ID=046d
E: ID_REVISION=0501
E: ID_TYPE=hid
E: ID_USB_MODEL=USB_Receiver
E: ID_USB_MODEL_ENC=USB\x20Receiver
E: ID_USB_MODEL_ID=c548
E: ID_USB_SERIAL=Logitech_USB_Receiver
E: ID_USB_VENDOR=Logitech
E: ID_USB_VENDOR_ENC=Logitech
E: ID_USB_VENDOR_ID=046d
E: ID_USB_REVISION=0501
E: ID_USB_TYPE=hid
E: ID_USB_INTERFACES=:030101:030102:030000:
E: ID_USB_INTERFACE_NUM=01
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:07:00.0-usb-0:2.1.3.2:1.1
E: ID_PATH_TAG=pci-0000_07_00_0-usb-0_2_1_3_2_1_1
E: DEVLINKS=/dev/input/by-path/pci-0000:07:00.0-usb-0:2.1.3.2:1.1-mouse /dev/input/by-id/usb-Logitech_USB_Receiver-if01-mouse
```
</details>

I'm afraid the unlucky owners of Logitech Lift Left will either need to use the rule locally or figure out a different way, perhaps with the help of Solaar ([just asked there](https://github.com/pwr-Solaar/Solaar/issues/2012)).

**Comment by NTMan** [comment] 2023-03-06 16:46
My MX Master 3S swapped buttons too.

<details>
<summary>udevadm info</summary>

```
❯ udevadm info /dev/input/mouse0
P: /devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:07:00.1/usb2/2-3/2-3.3/2-3.3.2/2-3.3.2:1.1/0003:046D:C548.0004/input/input4/mouse0
M: mouse0
R: 0
U: input
D: c 13:32
N: input/mouse0
L: 0
S: input/by-id/usb-Logitech_USB_Receiver-if01-mouse
S: input/by-path/pci-0000:07:00.1-usb-0:3.3.2:1.1-mouse
E: DEVPATH=/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:07:00.1/usb2/2-3/2-3.3/2-3.3.2/2-3.3.2:1.1/0003:046D:C548.0004/input/input4/mouse0
E: DEVNAME=/dev/input/mouse0
E: MAJOR=13
E: MINOR=32
E: SUBSYSTEM=input
E: USEC_INITIALIZED=11543569
E: ID_INPUT=1
E: ID_INPUT_MOUSE=1
E: ID_BUS=usb
E: ID_MODEL=USB_Receiver
E: ID_MODEL_ENC=USB\x20Receiver
E: ID_MODEL_ID=c548
E: ID_SERIAL=Logitech_USB_Receiver
E: ID_VENDOR=Logitech
E: ID_VENDOR_ENC=Logitech
E: ID_VENDOR_ID=046d
E: ID_REVISION=0501
E: ID_TYPE=hid
E: ID_USB_MODEL=USB_Receiver
E: ID_USB_MODEL_ENC=USB\x20Receiver
E: ID_USB_MODEL_ID=c548
E: ID_USB_SERIAL=Logitech_USB_Receiver
E: ID_USB_VENDOR=Logitech
E: ID_USB_VENDOR_ENC=Logitech
E: ID_USB_VENDOR_ID=046d
E: ID_USB_REVISION=0501
E: ID_USB_TYPE=hid
E: ID_USB_INTERFACES=:030101:030102:030000:
E: ID_USB_INTERFACE_NUM=01
E: ID_USB_DRIVER=usbhid
E: ID_PATH=pci-0000:07:00.1-usb-0:3.3.2:1.1
E: ID_PATH_TAG=pci-0000_07_00_1-usb-0_3_3_2_1_1
E: DEVLINKS=/dev/input/by-id/usb-Logitech_USB_Receiver-if01-mouse /dev/input/by-path/pci-0000:07:00.1-usb-0:3.3.2:1.1-mouse
```

</details>

**Comment by stickyburn** [comment] 2023-03-14 19:04
Just fyi, i'm on an artix s6 system and facing the same issue. Not sure if there are other systemd dependencies that are still common. One similarity I see in the report is using zen-kernel.

**Comment by stickyburn** [comment] 2023-03-18 18:46
Any progress here..?

**Comment by jwrdegoede** [comment] 2023-03-20 21:10
About the original now reverted hwdb entry. I see that this is for a special left-handed device.

The left/right buttons being swapped there ootb is actually expected behavior so I don't think we should add a hwdb entry to swap them back at all.

The reason why most desktop-environments have an option to swap the left/right buttons is for left-handed users (of symmetric mice). You see the left / right button naming really is the wrong naming.

The buttons should be called / thought of as index-finger and ring-finger buttons. And the idea is that the index-finger button executes what we typically call the left-click action and for a left handed user to index-finger rests on the right button!

So I believe that this special "left-handed ergonomic mouse" swapping left/right itself is very much intentional and intended to make the mouse work as a left-handed mouse ootb without requiring special configuration in the OS to swap the buttons.  And since this swapping left/right  is intentionally done by the hw I don't believe we should swap them back again in hwdb,

So I believe that the revert is the right thing to do independent of the issue of it applying to a receiver rather then to a specific device behind the receiver.

**Comment by matterhorn103** [comment] 2023-03-20 21:17
This also happens to me with a Logitech M650 mouse - not a "left" model

**Comment by jwrdegoede** [comment] 2023-03-20 21:23
> This also happens to me with a Logitech M650 mouse - not a "left" model

I was talking about the original hwdb change which introduced the problematic behavior of swapping the buttons for *all* mice using the `046D:C548` receiver, that change was done for a "left" model, see commit 81cfea95e51c72da6765b517e7038b3e7e3dec9f.

That specific change has been removed from hwdb now, so once you get a hwdb update through your distro the swapping should be fixed.

**Comment by vit-zikmund** [comment] 2023-03-31 13:22
FYI, just ended my round with Logitech support, where I got the ultimate answer:
- it's a feature (not a bug, should you be worried :smile:)
- all there is one can do is really use the OS global button switch (and swap other devices on the way)
- not even Logitech's own software (Logi Options+) for Windows allows you to control the button priority just for this mouse - it offers a toggle, but that also controls the OS' global one (so in the end, the unsupported Linux world is better suited to cope with the problem :+1:)

Till the device is enumerable, there's not much else we can do to take this further. And even then, it's questionable this should be really done globally, as it would make the mouse behave inconsistently across different platforms not having this patch. A local `/etc/udev/hwdb.d/` rule should be enough for anyone in need of the swap.

Thank you all who patiently suffered through all this!

**Comment by keszybz** [comment] 2023-03-31 17:58
Thanks @jwrdegoede and @vit-zikmund. Let's close this then.

**Closed as completed by keszybz** 2023-03-31 17:58 UTC
Labels: bug 🐛, hwdb, regression ⚠️
