### ISSUE TITLE
several vlans stuck in pending

### ISSUE THREAD

**Issue by DarkPhily** [systemd/systemd#16865] opened 2020-08-27 07:36 UTC
**systemd version the issue has been seen with**

> systemd 245 (245.4-4ubuntu3.2)
> +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**

> Ubuntu 20.04 LTS

**Expected behaviour you didn't see**

> Configured vlans

**Steps to reproduce the problem**

> Use the provided netplan. `systemctl enable systemd-networkd.socket`

**netplan**

[01-netcfg.txt](https://github.com/systemd/systemd/files/5134516/01-netcfg.txt)

**journalctl -b with debug on**

[debug.log](https://github.com/systemd/systemd/files/5134620/debug.log)

**networkctl status -a**

[network.log](https://github.com/systemd/systemd/files/5134643/network.log)

> The bug appiers at Line 19189, every interface before is configured

**dmesg**

[dmesg.log](https://github.com/systemd/systemd/files/5134674/dmesg.log)

**Comment by yuwata** [comment] 2020-08-27 07:49
Duplicate of #12308? E.g. vlan1122 does not get `ADD` uevent. Could you enable debug logging for `systemd-udevd`?

**Comment by DarkPhily** [comment] 2020-08-27 08:00
**new journalctl -b with debugging of udevd  and networkd enabled**

[debug-udevd.log](https://github.com/systemd/systemd/files/5134900/debug-udevd.log)

**Comment by yuwata** [comment] 2020-09-08 08:10
Hmm, so strange. At least, there exist four (3 failures + 1 success) patterns.
- success path
```
Aug 27 09:56:27 dhcp-injector-DC5 systemd-udevd[443]: vlan921: Device (SEQNUM=5488, ACTION=add) is queued
Aug 27 09:56:27 dhcp-injector-DC5 systemd-udevd[467]: vlan921: Processing device (SEQNUM=5488, ACTION=add)
Aug 27 09:56:27 dhcp-injector-DC5 systemd-udevd[467]: vlan921: /usr/lib/udev/rules.d/75-net-description.rules:6 Importing properties from results of builtin command 'net_id'
Aug 27 09:56:27 dhcp-injector-DC5 systemd-udevd[467]: vlan921: /usr/lib/udev/rules.d/80-net-setup-link.rules:5 Importing properties from results of builtin command 'path_id'
Aug 27 09:56:27 dhcp-injector-DC5 systemd-udevd[467]: vlan921: /usr/lib/udev/rules.d/80-net-setup-link.rules:5 Failed to run builtin 'path_id': No such file or directory
Aug 27 09:56:27 dhcp-injector-DC5 systemd-udevd[467]: vlan921: /usr/lib/udev/rules.d/80-net-setup-link.rules:9 Importing properties from results of builtin command 'net_setup_link'
Aug 27 09:56:27 dhcp-injector-DC5 systemd-udevd[467]: vlan921: Config file /usr/lib/systemd/network/99-default.link is applied
Aug 27 09:56:27 dhcp-injector-DC5 systemd-udevd[467]: vlan921: Device has name_assign_type=3
Aug 27 09:56:27 dhcp-injector-DC5 systemd-udevd[467]: vlan921: Policies didn't yield a name and Name= is not given, not renaming.
Aug 27 09:56:27 dhcp-injector-DC5 systemd-udevd[467]: vlan921: Device has addr_assign_type=2
Aug 27 09:56:27 dhcp-injector-DC5 systemd-udevd[467]: vlan921: MAC on the device already set based on another device
Aug 27 09:56:27 dhcp-injector-DC5 systemd-udevd[467]: vlan921: /usr/lib/udev/rules.d/99-systemd.rules:62 RUN '/lib/systemd/systemd-sysctl --prefix=/net/ipv4/conf/$name --prefix=/net/ipv4/neigh/$name --prefix=/net/ipv6/conf/$name --prefix=/net/ipv6/neigh/$name'
Aug 27 09:56:27 dhcp-injector-DC5 systemd-udevd[467]: vlan921: sd-device: Created db file '/run/udev/data/n301' for '/devices/virtual/net/vlan921'
Aug 27 09:56:27 dhcp-injector-DC5 systemd-udevd[467]: vlan921: Running command "/lib/systemd/systemd-sysctl --prefix=/net/ipv4/conf/vlan921 --prefix=/net/ipv4/neigh/vlan921 --prefix=/net/ipv6/conf/vlan921 --prefix=/net/ipv6/neigh/vlan921"
Aug 27 09:56:27 dhcp-injector-DC5 systemd-udevd[467]: vlan921: Starting '/lib/systemd/systemd-sysctl --prefix=/net/ipv4/conf/vlan921 --prefix=/net/ipv4/neigh/vlan921 --prefix=/net/ipv6/conf/vlan921 --prefix=/net/ipv6/neigh/vlan921'
Aug 27 09:56:27 dhcp-injector-DC5 systemd-udevd[443]: vlan921: sd-device-monitor: Passed 183 byte to netlink monitor
Aug 27 09:56:27 dhcp-injector-DC5 systemd-udevd[467]: vlan921: Process '/lib/systemd/systemd-sysctl --prefix=/net/ipv4/conf/vlan921 --prefix=/net/ipv4/neigh/vlan921 --prefix=/net/ipv6/conf/vlan921 --prefix=/net/ipv6/neigh/vlan921' succeeded.
Aug 27 09:56:27 dhcp-injector-DC5 systemd-udevd[467]: vlan921: Device (SEQNUM=5488, ACTION=add) processed
Aug 27 09:56:27 dhcp-injector-DC5 systemd-udevd[467]: vlan921: sd-device-monitor: Passed 339 byte to netlink monitor
Aug 27 09:56:30 dhcp-injector-DC5 systemd-networkd[450]: vlan921: udev initialized link
```
- device is queued, and worker try to process the event, but not finished. It seems worker fails to process the device, but no log message about the failure. 
```
Aug 27 09:56:28 dhcp-injector-DC5 systemd-udevd[443]: vlan3922: Device (SEQNUM=6164, ACTION=add) is queued
Aug 27 09:56:28 dhcp-injector-DC5 systemd-udevd[475]: vlan3922: Processing device (SEQNUM=6164, ACTION=add)
Aug 27 09:56:28 dhcp-injector-DC5 systemd-udevd[475]: vlan3922: /usr/lib/udev/rules.d/75-net-description.rules:6 Importing properties from results of builtin command 'net_id'
Aug 27 09:56:28 dhcp-injector-DC5 systemd-udevd[475]: vlan3922: /usr/lib/udev/rules.d/80-net-setup-link.rules:5 Importing properties from results of builtin command 'path_id'
Aug 27 09:56:28 dhcp-injector-DC5 systemd-udevd[475]: vlan3922: /usr/lib/udev/rules.d/80-net-setup-link.rules:5 Failed to run builtin 'path_id': No such file or directory
Aug 27 09:56:28 dhcp-injector-DC5 systemd-udevd[475]: vlan3922: /usr/lib/udev/rules.d/80-net-setup-link.rules:9 Importing properties from results of builtin command 'net_setup_link'
Aug 27 09:56:28 dhcp-injector-DC5 systemd-udevd[475]: vlan3922: Config file /usr/lib/systemd/network/99-default.link is applied
Aug 27 09:56:28 dhcp-injector-DC5 systemd-udevd[475]: vlan3922: Device has name_assign_type=3
Aug 27 09:56:28 dhcp-injector-DC5 systemd-udevd[475]: vlan3922: Policies didn't yield a name and Name= is not given, not renaming.
Aug 27 09:56:28 dhcp-injector-DC5 systemd-udevd[475]: vlan3922: Device has addr_assign_type=2
Aug 27 09:56:28 dhcp-injector-DC5 systemd-udevd[475]: vlan3922: MAC on the device already set based on another device
Aug 27 09:56:28 dhcp-injector-DC5 systemd-udevd[475]: vlan3922: /usr/lib/udev/rules.d/99-systemd.rules:62 RUN '/lib/systemd/systemd-sysctl --prefix=/net/ipv4/conf/$name --prefix=/net/ipv4/neigh/$name --prefix=/net/ipv6/conf/$name --prefix=/net/ipv6/neigh/$name'
Aug 27 09:56:28 dhcp-injector-DC5 systemd-udevd[475]: vlan3922: sd-device: Created db file '/run/udev/data/n526' for '/devices/virtual/net/vlan3922'
Aug 27 09:56:28 dhcp-injector-DC5 systemd-udevd[475]: vlan3922: Running command "/lib/systemd/systemd-sysctl --prefix=/net/ipv4/conf/vlan3922 --prefix=/net/ipv4/neigh/vlan3922 --prefix=/net/ipv6/conf/vlan3922 --prefix=/net/ipv6/neigh/vlan3922"
Aug 27 09:56:28 dhcp-injector-DC5 systemd-udevd[475]: vlan3922: Starting '/lib/systemd/systemd-sysctl --prefix=/net/ipv4/conf/vlan3922 --prefix=/net/ipv4/neigh/vlan3922 --prefix=/net/ipv6/conf/vlan3922 --prefix=/net/ipv6/neigh/vlan3922'
Aug 27 09:56:28 dhcp-injector-DC5 systemd-udevd[443]: vlan3922: sd-device-monitor: Passed 185 byte to netlink monitor
```
- device is queued, but not processed any workers, and send to udev event listeners without any error message. I cannot find this path in udevd.c...
```
Aug 27 09:56:28 dhcp-injector-DC5 systemd-udevd[443]: vlan816: Device (SEQNUM=6209, ACTION=add) is queued
Aug 27 09:56:28 dhcp-injector-DC5 systemd-udevd[443]: vlan816: sd-device-monitor: Passed 183 byte to netlink monitor
```
- No uevent received by udevd.
```
$ grep 'vlan1002' debug-udevd.log 
Aug 27 09:56:21 dhcp-injector-DC5 systemd-networkd[450]: vlan1002: loaded vlan
Aug 27 09:56:25 dhcp-injector-DC5 systemd-networkd[450]: eth0: Enslaving by 'vlan1002'
Aug 27 09:56:25 dhcp-injector-DC5 systemd-networkd[450]: vlan1002: Creating
Aug 27 09:56:26 dhcp-injector-DC5 systemd-networkd[450]: vlan1002: New device has no master, continuing without
Aug 27 09:56:26 dhcp-injector-DC5 systemd-networkd[450]: vlan1002: Flags change: +MULTICAST +BROADCAST
Aug 27 09:56:26 dhcp-injector-DC5 systemd-networkd[450]: vlan1002: Link 876 added
Aug 27 09:56:26 dhcp-injector-DC5 systemd-networkd[450]: vlan1002: link pending udev initialization...
Aug 27 09:56:26 dhcp-injector-DC5 systemd-networkd[450]: vlan1002: netdev has index 876
Aug 27 09:56:26 dhcp-injector-DC5 systemd-networkd[450]: vlan1002: netdev ready
Aug 27 09:56:26 dhcp-injector-DC5 systemd-networkd[450]: vlan1002: Saved original MTU: 1500
Aug 27 09:56:26 dhcp-injector-DC5 systemd-networkd[450]: vlan1002: Flags change: +UP +LOWER_UP +RUNNING
Aug 27 09:56:26 dhcp-injector-DC5 systemd-networkd[450]: vlan1002: Link UP
Aug 27 09:56:26 dhcp-injector-DC5 systemd-networkd[450]: vlan1002: Gained carrier
Aug 27 09:56:26 dhcp-injector-DC5 systemd-networkd[450]: vlan1002: Remembering route: dst: ff00::/8, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: boot, type: unicast
Aug 27 09:56:26 dhcp-injector-DC5 systemd-networkd[450]: vlan1002: Remembering route: dst: fe80::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast
Aug 27 09:56:27 dhcp-injector-DC5 systemd-networkd[450]: vlan1002: Remembering foreign address: fe80::d63d:7eff:feed:dd1/64 (valid forever)
Aug 27 09:56:27 dhcp-injector-DC5 systemd-networkd[450]: vlan1002: Gained IPv6LL
Aug 27 09:56:27 dhcp-injector-DC5 systemd-networkd[450]: vlan1002: Remembering route: dst: fe80::d63d:7eff:feed:dd1/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
Aug 27 09:56:37 dhcp-injector-DC5 systemd-networkd[450]: vlan1002: Flags change: -LOWER_UP -RUNNING
Aug 27 09:56:37 dhcp-injector-DC5 systemd-networkd[450]: vlan1002: Lost carrier
Aug 27 09:56:38 dhcp-injector-DC5 systemd-networkd[450]: vlan1002: Flags change: +LOWER_UP +RUNNING
Aug 27 09:56:38 dhcp-injector-DC5 systemd-networkd[450]: vlan1002: Gained carrier
```

**Comment by yuwata** [comment] 2020-09-08 08:15
Ah, it seems that the log message is incomplete:
```
Aug 27 09:56:56 dhcp-injector-DC5 systemd-journald[402]: Suppressed 163207 messages from systemd-udevd.service
```

**Comment by yuwata** [comment] 2020-09-08 08:31
@DarkPhily Could you set `RateLimitIntervalSec=0` in `/etc/systemd/journald.conf`, and generate full debug log of udevd and networkd?

**Comment by ssahani** [comment] 2020-09-08 09:27
```
Aug 26 14:12:09 dhcp-injector-DC5 systemd-networkd[461]: sd-device-monitor: Failed to receive message: No buffer space available
```

```src/libsystemd/sd-device/device-monitor.c```

```
int device_monitor_receive_device(sd_device_monitor *m, sd_device **ret) {
          _cleanup_(sd_device_unrefp) sd_device *device = NULL;
          union {
                  monitor_netlink_header nlh;
                  char raw[8192]; <========================= this needs to be increased @yuwata ?
          } buf;
          struct iovec iov = {
                  .iov_base = &buf,
                  .iov_len = sizeof(buf)
          };
          CMSG_BUFFER_TYPE(CMSG_SPACE(sizeof(struct ucred))) control;
          union sockaddr_union snl;
          struct msghdr smsg = {
                  .msg_iov = &iov,
                  .msg_iovlen = 1,
                  .msg_control = &control,
                  .msg_controllen = sizeof(control),
                  .msg_name = &snl,
                  .msg_namelen = sizeof(snl),
          };

```

**Comment by yuwata** [comment] 2020-09-08 09:34
@ssahani Nice catch! I will take a look.

**Comment by ssahani** [comment] 2020-09-08 09:37
Then have tons of vlan, hence buffer is short. We need to increase it.

**Comment by DarkPhily** [comment] 2020-09-08 11:05
These are the new logs:

[2020-09-08.debug-udevd.log](https://github.com/systemd/systemd/files/5187866/2020-09-08.debug-udevd.log)
[2020-09-08.debug-networkd.log](https://github.com/systemd/systemd/files/5187867/2020-09-08.debug-networkd.log)

For some reasons we don't see the issue anymore.
How is changing `RateLimitIntervalSec=0` and uncommenting the parameter related to the vlans stuck in pending?
I don't see how this fixed the issue.

**Comment by yuwata** [comment] 2020-09-08 14:12
@DarkPhily Interesting. I guess that setting `RateLimitIntervalSec=0` makes `udevd` slower, and then the buffer shortage in `networkd` may be resolved.

**Closed as completed** 2020-09-09 14:28 UTC
Labels: udev, network
