### ISSUE TITLE
Systemd loses log messages due to race condition

### ISSUE THREAD

**Issue by duijf** [systemd/systemd#6565] opened 2017-08-08 09:05 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

```
systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN
```

### Used distribution

Ubuntu 16.04.2 LTS

### In case of bug report: Expected behaviour you didn't see

Every line logged to `stdout` by a process started by systemd ends up in the journal

### In case of bug report: Unexpected behaviour you saw

When a service is short lived, log messages can be lost.

### In case of bug report: Steps to reproduce the problem

I'm running the following script, saved under `/usr/local/bin/test.sh`:

```bash
#!/bin/bash
set -e
echo "Hello world"
```

With the following unit file, saved as `/etc/systemd/system/test.service`:

```
[Unit]
Description=test

[Service]
Type=simple
User=test
Group=test
PrivateTmp=true
ExecStart=/usr/local/bin/test.sh
```

The `test` user has been created with:

```
$ sudo adduser --shell /bin/bash test
```

After doing a `systemctl daemon-reload`, running:

```
$ sudo systemctl start test
```

Will not always have the `Hello World` message show up in the output of `sudo journalctl -u test`:

```
Aug 08 08:49:50 web1 systemd[1]: Started test.
Aug 08 08:49:52 web1 systemd[1]: Started test.
Aug 08 08:49:53 web1 systemd[1]: Started test.
Aug 08 08:49:54 web1 systemd[1]: Started test.
```

But changing the script to sleep for 1 second after the `echo` command will ensure it is always there. New script:

```bash
#!/bin/bash
set -e
echo "Hello world"
sleep 1
```

Output of `sudo journalctl -u test`:

```
Aug 08 08:49:59 web1 systemd[1]: Started test.
Aug 08 08:49:59 web1 test.sh[32117]: Hello world
Aug 08 08:50:02 web1 systemd[1]: Started test.
Aug 08 08:50:02 web1 test.sh[32148]: Hello world
```

**Comment by killermoehre** [comment] 2017-08-08 09:08
That's actually known behavior. Due to the race the messages can't be tagged properly. They are still in the journal, but not tagged with the unit name. You can see them with a plain `journalctl`.

**Comment by duijf** [comment] 2017-08-08 09:15
Thanks for the response! Could you explain to me how this race follows from the implementation used? How does the race condition work?

**Comment by killermoehre** [comment] 2017-08-08 09:33
I'm don't know the code, but the explanation is that that in the moment the journal wants to annotate the message with the metadata, the process which generated the message already exited, which means the unit doesn't have any running processes anymore and quits. So there is no connection between the PID which generated the message and the unit the process was running it.
I hope I explained this right.

**Comment by duijf** [comment] 2017-08-08 09:59
Makes sense; thanks for explaining.

Feel free to close this issue if there is no intention of fixing this behavior.

**Comment by fsateler** [comment] 2017-08-08 13:34
This is a duplicate of https://github.com/systemd/systemd/issues/2913 , there are more details there. I'm going to close this bug in preference of the older one.

**Comment by fsateler** [comment] 2017-08-08 13:35
BTW, note that messages are not lost, they are just not attributed to the `test.service` service. You can still see them if you remove the `-u` flag.

**Closed as completed by fsateler** 2017-08-08 13:34 UTC
Labels: journal, duplicate
