### ISSUE TITLE
regression: Onlink not set for dhcp routes

### ISSUE THREAD

**Issue by rossmeier** [systemd/systemd#17905] opened 2020-12-08 16:40 UTC
**systemd version the issue has been seen with**
 > definitley works with 246, doesn't work with 247

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > 5.9.10-arch1-1

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > routes received from dhcp server are added as routes no matter whether they can be directly reached over the interface or not

**Unexpected behaviour you saw**
 > dhcp routes that aren't in a configured network get silently ignored. Adding them manually using `ip route add default via x.y.z.a device eth0 onlink` works
 > `[Route] Gateway=x.y.z.a GatewayOnLink=yes` works
 > `[Route] Gateway=_dhcp4 GatewayOnLink=yes` doesn't

**Steps to reproduce the problem**
 > Set up a DHCP server that pushes a route that is not reachable directly by a configured interface address
 > restart `systemd-networkd`
 > Route will not show in `ip route`

During my investigation I found the test `test_dhcp_client_gateway_onlink_implicit` which probably should fail with build 247?

**Comment by veecue** [comment] 2020-12-08 17:45
So I started some further investigation and interesting enought, my specific error case does not occur anymore starting from commit df8aa086420e6ce61e32898b2bb7c88b87fd1c43. This is very confusing for me.

**Comment by yuwata** [comment] 2020-12-08 17:48
Ah, I guess this is a duplicate of #17803. Maybe, your DHCP server provides /32 address. Closing.

**Closed as completed by yuwata** 2020-12-08 17:48 UTC
Labels: network, duplicate, already-fixed
