### ISSUE TITLE
Fails to build with gperf 3.1

### ISSUE THREAD

**Issue by AdamWill** [systemd/systemd#5171] opened 2017-01-27 17:24 UTC
The new gperf 3.1 has a [significant change](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/UBLBIDF2WUQRZ2ZRPLYJ7AOZ7W5RQ5RK/). Quoting from that mail:

"This changes the type of one of the parameters of the generated
perfect hash function:

    -char *in_word_set (register const char *str, register unsigned int len);
    +char *in_word_set (register const char *str, register size_t len);

If you have the function prototyped in another file, then you have to
be careful that the prototype exactly matches the new type.  Otherwise
on 64 bit architectures you'll end up passing an incorrectly sized
'len' argument (unsigned int == 32 bits vs size_t == 64 bits) which
will subtly break in certain circumstances (but on little endian it'll
still work most of the time, making this bug rather insidious).

Using the functions (third) section of the gperf file can avoid
needing to prototype the function elsewhere, since you can drop a
wrapper of your own choosing into the functions section."

systemd falls foul of this in several places: `src/basic/cap-list.c` , `src/basic/errno-list.c` , `src/basic/arphrd-list.c` , `src/basic/af-list.c` and `src/resolve/dns-type.c` .

**Comment by evverx** [comment] 2017-01-27 17:30
Duplicate of https://github.com/systemd/systemd/issues/5039

**Closed as completed by evverx** 2017-01-27 17:30 UTC
Labels: build-system, duplicate
