### ISSUE TITLE
[systemd-shutdown] Add /etc/systemd/system-shutdown/

### ISSUE THREAD

**Issue by djgera** [systemd/systemd#17045] opened 2020-09-14 01:27 UTC
If you want to customize last-shutdown-scripts or add new one, you should touch /usr. Will be great if a directory /etc/systemd/system-shutdown/ takes precedence over /usr/lib/systemd/system-shutdown/. This logic looks like as in other parts of systemd directories.

systemd-246.4

**Comment by poettering** [comment] 2020-09-14 08:23
Placing binaries in /etc is simply wrong.

This stuff is not really for customization, it's very low-level stuff that runs here, at a time where almost everything else is already shut down and unmounted. It's inherently low-level OS vendor stuff that runs in this contexts, and not user software. hence I don't really think we should make this configurable more, because it's so low-level.

Package should be able to extend this easily, but if users want to interfere with it then they become their own OS vendor if you so will, at which point it should be OK for the to drop stuff into /usr themselves too.

**Comment by mbiebl** [comment] 2020-09-14 11:02
Seems related to #4927

**Comment by poettering** [comment] 2020-09-14 11:07
Yeah, let's close this as duplicate of #4927. It's close enough.

**Closed as completed by poettering** 2020-09-14 11:07 UTC
Labels: RFE 🎁, needs-discussion 🤔, pid1, duplicate

**Comment by djgera** [comment] 2020-09-14 15:31
I agree with no blobs in /etc. But I talk about scripts. Like the common practice (not officialy supported?) of put script related to local services in /etc/systemd/scripts.
