### ISSUE TITLE
Race between systemd-networkd.service and dbus.socket

### ISSUE THREAD

**Issue by floppym** [systemd/systemd#6618] opened 2017-08-15 15:04 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

234

### Used distribution

Gentoo

### In case of bug report: Expected behaviour you didn't see

systemd-networkd should start on boot without any errors.

### In case of bug report: Unexpected behaviour you saw

systemd-networkd[132]: Could not connect to bus: Connection refused

### In case of bug report: Steps to reproduce the problem

Not sure on exactly how to reproduce this, but after reviewing the units involved it looks like there is nothing preventing systemd-networkd from starting before the dbus socket has been created. I assume this is what causes the error above.

See also: https://bugs.gentoo.org/show_bug.cgi?id=626146

**Comment by yuwata** [comment] 2017-08-22 08:07
As I commented at https://github.com/systemd/systemd/issues/6435#issuecomment-323919989, I cannot reproduce the problem with the latest git snapshot. Even if I add `Before=dbus.service dbus.socket`, networkd works fine.

**Comment by yuwata** [comment] 2017-08-22 09:36
~~I guess the problem is already fixed by a132bef0239e6c3f04096eee3a00c7ecf24a4f5c (#6465).~~

**Comment by yuwata** [comment] 2017-08-22 09:45
Is it possible to test with the latest snapshot?

**Comment by yuwata** [comment] 2017-08-22 10:50
The important point in a132bef0239e6c3f04096eee3a00c7ecf24a4f5c for this bug is the last line of `bus_start_address()`. By the commit the line is changed from 
```
return b->last_connect_error ? -b->last_connect_error : -ECONNREFUSED;
```
to
```
return b->last_connect_error > 0 ? -b->last_connect_error : -ECONNREFUSED;
```
Thus, now `sd_bus_default_system()` does not returns `ECONNREFUSED`.

**Comment by yuwata** [comment] 2017-08-23 03:46
My previous comments may be completely wrong. Please ignore them.
I create PR #6659. If possible, please check it.

**Comment by floppym** [comment] 2017-08-23 16:03
I have asked for someone to test it on the Gentoo bug report.

**Closed as completed** 2017-08-30 10:17 UTC
Labels: network

**Comment by berndf** [comment] 2017-08-31 17:19
Sorry for the delay due to vacancies! I see the patch was just pulled.

I can confirm that the fix works (lets systemd-networkd start rather than fail on my systems).

As I see, the fix extends an internal retry loop to also include the error occurring when dbus is not yet up. I cannot imagine that this solution is really what the systemd authors intend, as it hides the information on the condition for which a service is waiting from the system. As I understand it, it would be cleaner to add dbus.socket as a dependency. Then this dependency is explicit and systemd-networkd may simply fail if it isn't met, just as before.

**Comment by yuwata** [comment] 2017-09-01 05:10
I guess (not confirmed) this bug is caused when networkd tries to connect dbus while dbus is starting. If dbus does not begin to start, then `sd_bus_default_system()` returns `-ENOENT`. However, during the starting process of the dbus, (I stress that it is not confirmed) there exists a short time delay such that the socket is created but not listened yet. If networkd calls `sd_bus_default_system()` in that period, it may returns `-ECONNREFUSED`. But still in that case, waiting for a while and trying to connect again is a good solution. I cannot say that `-ENOENT` and `-ECONNREFUSED` are only error values we should 'hide the information'. So, I decided to change the line as `if (r < 0)`.

As I said before, networkd correctly work even if we add `Before=dbus.service`. So, adding `After=dbus.service` is not necessary and is an overkill dependency.

**Comment by poettering** [comment] 2017-09-01 07:44
> As I understand it, it would be cleaner to add dbus.socket as a dependency.

It would be cleaner, but it would also mean we'd have to move networkd to late boot, as dbus-daemon isn#t fit to run in early boot and only is started in later boot hence... The retry loop exists in networkd do deal with this mess: permit networkd to start early, but connect to dbus later on.

**Comment by berndf** [comment] 2017-09-01 11:11
Thanks for the explanations, this makes the tradeoff clear. Thanks to Yu for the fix!
