### ISSUE TITLE
Units with BindsTo=<device> are being killed on upgrade from v246 to v247

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#17605] opened 2020-11-13 23:07 UTC
I just did a test-upgrade of a system from 246.6 to 247-rc2.

Once `systemctl daemon-reexec` is run a lot of units/services were killed. 
My preliminary findings so far is, that they all had a BindsTo=<device> and I guess this dependency was invalidated by the update.

In my particular case, this also caused my X / login session to be terminated.
I suppose this is a result of the new udev related changes in v247.

**Comment by poettering** [comment] 2020-11-14 10:57
Please provide log output when this happens. With debug logging turned on.

**Comment by mbiebl** [comment] 2020-11-14 12:52
And the first bug reports start rolling in:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=974730

**Comment by EricV** [comment] 2020-11-14 15:59
I confirm. If almost killed two machines. The services are killed during the upgrade before the apt command finishes and can let the system in unrecoverable state depending on when it happens and what is committed before the crash. On one I was lucky to have all systemd packages version still in /var/cache/apt/archives or I would have resorted o do a boot from iso/usb to restore (X does not work on my machine as I need very special amdgpu setting).

**Comment by mbiebl** [comment] 2020-11-15 17:44
Hi @poettering 
I ran the tests in a minimal VM, so the results are less severe.
Attached is a udevadm info dump from before and after, a systemd-analyze from before and after and a journalctl dump after the `daemon-reexec`


[journalctl.dump.txt](https://github.com/systemd/systemd/files/5542829/journalctl.dump.txt)
[systemd-analyze.after.txt](https://github.com/systemd/systemd/files/5542830/systemd-analyze.after.txt)
[systemd-analyze.before.txt](https://github.com/systemd/systemd/files/5542831/systemd-analyze.before.txt)
[udev.after.txt](https://github.com/systemd/systemd/files/5542832/udev.after.txt)
[udev.before.txt](https://github.com/systemd/systemd/files/5542833/udev.before.txt)

**Comment by mbiebl** [comment] 2020-11-15 17:49
The  ifup@enp1s0.service service that was killed during the upgrade 
is from https://salsa.debian.org/debian/ifupdown/-/blob/master/debian/ifup@.service
```
[Unit]
Description=ifup for %I
After=local-fs.target network-pre.target apparmor.service systemd-sysctl.service
Before=network.target shutdown.target network-online.target
Conflicts=shutdown.target
BindsTo=sys-subsystem-net-devices-%i.device
After=sys-subsystem-net-devices-%i.device
DefaultDependencies=no
IgnoreOnIsolate=yes

[Service]
# avoid stopping on shutdown via stopping system-ifup.slice
Slice=system.slice
ExecStart=/bin/sh -ec 'ifup --allow=hotplug %I; ifquery --state %I'
ExecStop=/sbin/ifdown %I
RemainAfterExit=true
TimeoutStartSec=5min
```

**Comment by arvidjaar** [comment] 2020-11-15 19:52
> journalctl.dump.txt

```
Nov 15 18:37:00 debian systemd[1]: Invoking unit coldplug() handlers…
Nov 15 18:37:00 debian systemd[1]: dev-vda1.device: Changed dead -> plugged
...
Nov 15 18:37:00 debian systemd[1]: Invoking unit catchup() handlers…
Nov 15 18:37:00 debian systemd[1]: dev-vda1.device: Changed plugged -> dead
```

`catchup()` handler for device calls `device_update_found_one(d, d->enumerated_found, DEVICE_FOUND_MASK);` but I do not see any place where `d->enumerated_found` is set after desrialization. So in `device_update_found_one()`:

```
                n = (d->found & ~mask) | (found & mask);
                previous = d->found;
                d->found = n;

                device_found_changed(d, previous, n);
```

where `found` == `d->enumerated_found` which is presumed to be 0 at this point. I.e. `d->found` is set to 0 and `previous` is set from serialized state and is likely equal to (or includes) `DEVICE_FOUND_UDEV` so we hit the last branch in `device_found_changed()`:

```
                /* If nobody sees the device, or if the device was previously seen by udev and now is only referenced
                 * from the kernel, then we consider the device is gone, the kernel just hasn't noticed it yet. */
                device_set_state(d, DEVICE_DEAD);
```

**Comment by mbiebl** [comment] 2020-11-15 21:44
From the test VM
```
# systemd-analyze dump | grep BindsTo
	BindsTo: dev-vdb1.device (origin-mountinfo-implicit)
	BindsTo: dev-disk-by\x2dlabel-data1.device (origin-file)
	BindsTo: dev-disk-by\x2dlabel-data2.device (origin-file)
	BindsTo: dev-vdb2.device (origin-mountinfo-implicit)
	BindsTo: sys-devices-virtual-misc-rfkill.device (origin-file)
	BindsTo: sys-devices-virtual-misc-rfkill.device (origin-file)
	BindsTo: sys-subsystem-net-devices-enp1s0.device (origin-file)
```

After upgrading the package (involving a udev restart)
```
# systemd-analyze dump | grep BindsTo
	BindsTo: dev-vdb1.device (origin-mountinfo-implicit)
	BindsTo: dev-vdb2.device (origin-mountinfo-implicit)
	BindsTo: sys-devices-virtual-misc-rfkill.device (origin-file)
	BindsTo: sys-devices-virtual-misc-rfkill.device (origin-file)
	BindsTo: sys-subsystem-net-devices-enp1s0.device (origin-file)
```
After `daemon-reexec`
```
# systemd-analyze dump | grep BindsTo
<empty>
```

**Comment by yuwata** [comment] 2020-11-16 09:55
I have not confirmed that, but it seems that the issue is caused by 242c1c075aa284c8a8657c5aca36147f528146ba.
The old udev database does not have the current tag entry. Thus, with the old udev database, `device_is_active()` always returns `false`.

**Comment by yuwata** [comment] 2020-11-16 11:12
I've created PR #17622, though I've not tested it. I will test it, but if you are interested in the PR, please also test it. Thanks.

**Comment by mbiebl** [comment] 2020-11-16 13:01
@yuwata thanks for having a look at this.
I gave this PR a go and the initial results look promising:
```
# journalctl -r
-- Journal begins at Fri 2020-11-13 23:22:54 CET, ends at Mon 2020-11-16 13:58:11 CET. --
Nov 16 13:58:11 debian systemd[1]: /lib/systemd/system/plymouth-start.service:16: Unit configured to use KillMo>
Nov 16 13:58:11 debian systemd[1]: Detected architecture x86-64.
Nov 16 13:58:11 debian systemd[1]: Detected virtualization kvm.
Nov 16 13:58:11 debian systemd[1]: systemd 247~rc2-3~test0 running in system mode. (+PAM +AUDIT +SELINUX +IMA +>
Nov 16 13:58:11 debian systemd[1]: Reexecuting.
```

before:
```
# systemd-analyze dump | grep BindsTo
	BindsTo: dev-vdb1.device (origin-mountinfo-implicit)
	BindsTo: dev-disk-by\x2dlabel-data1.device (origin-file)
	BindsTo: dev-disk-by\x2dlabel-data2.device (origin-file)
	BindsTo: dev-vdb2.device (origin-mountinfo-implicit)
	BindsTo: sys-subsystem-net-devices-enp1s0.device (origin-file)
	BindsTo: sys-devices-virtual-misc-rfkill.device (origin-file)
	BindsTo: sys-devices-virtual-misc-rfkill.device (origin-file)
```
after:
```
# systemd-analyze dump | grep BindsTo
	BindsTo: sys-devices-virtual-misc-rfkill.device (origin-file)
	BindsTo: sys-subsystem-net-devices-enp1s0.device (origin-file)
	BindsTo: dev-vdb2.device (origin-mountinfo-implicit)
	BindsTo: dev-vdb1.device (origin-mountinfo-implicit)
	BindsTo: sys-devices-virtual-misc-rfkill.device (origin-file)
```

**Closed as completed** 2020-11-26 11:48 UTC
Labels: bug 🐛, udev, pid1, sd-device
