### ISSUE TITLE
[resolved] explicitly allow caching for local dns resolvers

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#4480] opened 2016-10-25 09:53 UTC
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux

Hello,
It would be nice to have a third option in `/etc/systemd/resolved.conf` to allow caching of local dns-resolvers that doesn't come with a caching mechanism. For example `dnscrypt-proxy`. My current solution is a dirty hack with adding a private IP address to the loopback device.

**Comment by ott** [comment] 2018-08-31 23:59
@poettering It seems that this issue can be closed as it is a duplicated of #8346 and you closed that issue.

**Comment by shibumi** [comment] 2018-09-01 00:41
@ott he closed that issue because it's a duplicate of this issue.. this was the only reason for closing issue #8346

**Comment by ott** [comment] 2018-09-01 00:53
@shibumi I see. I was stupid. Sorry for the unnecessary effort.

**Comment by ott** [comment] 2018-09-01 00:58
@shibumi Isn't this also a duplicate of #6945? I'm assuming that the "local dns-resolvers that doesn't come with a caching mechanism" return RRs with TTL of 0.

**Comment by shibumi** [comment] 2018-09-01 01:10
@ott first of all #6945 would be a duplicate of this one, because this issue here is older. I am not that much into DNS internals.. so no idea if both issues are connected.

**Comment by ott** [comment] 2018-09-02 19:47
@shibumi Again you are of course right. What I wrote is illogical.

Can you describe what version of dnscrypt-proxy you used and how you configured it, so that I can reproduce the problem that you encountered?

**Comment by ott** [comment] 2018-09-02 20:29
@shibumi Perhaps we can close this issue then? We can't reproduce the issue and if `dnscrypt-proxy` used a TTL of 0, systemd-resolved behaved correctly.

**Comment by shibumi** [comment] 2018-09-03 00:42
@ott the issue got 3 votes and it's reproducible. Just install dnscrypt-proxy, set it up that it will run on an IP address different to the ones that are reserved from `systemd-resolved` and let systemd-resolved get the dns responses via this proxy.

**Comment by ott** [comment] 2019-03-10 15:50
@shibumi Can you post your dnscrypt-proxy version number and configuration file. The TTL of dnscrypt-proxy is adustable and, therefore, it might not be able to reproduce the issue.

**Comment by shibumi** [comment] 2019-03-10 16:13
@ott I lost interest in this setup, due to the fact that `systemd-resolved` supports `dns-over-tls` since a few versions.

**Comment by v-fox** [comment] 2019-09-01 05:18
@ott Well, I'm trying to use resolved with 6 parallel dnscrypt-proxy-1.9.5 tunnels (for redundancy) as 127.1.0.[1-6] (due to resolved's inability to swallow custom port numbers for 127.0.0.1, as unbound does) and it does not seem to be wanting to cache their answers. The only "adjustable" cache settings in dnscrypt is 'LocalCache: on/off'. So, are you saying that resolved is supposed to somehow detect when LocalCache:off in a dnscrypt instance and start to actually cache ?

And if you're referring to newer Go-rewrite of dnscrypt-proxy then there is little-to-no chance of it getting into my distro, openSUSE.

**Comment by shibumi** [comment] 2019-09-01 20:24
I don't understand why somebody should use dnscrypt with systemd-resolved nowadays. systemd-resolved has dns over tls support. I just wish people would actually invest some time in further dns over tls development in systemd-resolved. Then we could finally ditch dnscrypt.

**Comment by v-fox** [comment] 2019-09-01 21:39
@shibumi It would be nice not to have to manually set up tunnels just to make sure that ISP does not falsify/snoop DNS requests to censor/surveil traffic by orders from fascist politicians, especially now that proper dnscrypt implementation has been abandoned and the rewrite has little change of getting into popular distros, let alone be enabled by default anywhere, which would require auto-selection of tunnel endpoints (actual DNS servers) by some kind of startup RTT check or limiting to use only globally ubiquitous 'anycast' servers, yeah.

unbound doesn't seem to be able to do opportunistic DNS-over-TLS but resolved behaves weirdly, jumps around servers, has no way to see its current "interpretation" of their abilities and per-servers stats, doesn't seem to want to use avahi & lldpd or reimplement them fully. Does it spread queries or uses them sequentially ? Anyway, I've returned to unbound as my primary resolver and have put resolved as "failover" for now.

The more I try to make it work, the more I lose hope that any feature, including DNS-over-TLS, ever will be fully functional. Especially, if it even can't get simple caching right. And don't get me started on [DNSSEC "sabotage"](https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1682499), as one Ubuntu user have put it. Had to give up and disable it too but, to be fair, unbound isn't much better at it either.

**Comment by poettering** [comment] 2020-12-02 16:38
Fixed by #17710

**Closed as completed by poettering** 2020-12-02 16:38 UTC
Labels: RFE 🎁, resolve
