### ISSUE TITLE
nss_resolve makes getaddrinfo(3) fail resolution of ipv4 only hostnames if also connected via ipv6

### ISSUE THREAD

**Issue by Gamberoni** [systemd/systemd#8017] opened 2018-01-26 23:26 UTC
### Submission type
 - Bug report

### systemd version the issue has been seen with
systemd         234-2ubuntu1

### Used distribution
kubuntu.
Local modifications: using only systemd-nertworkd and systemd-resolved.
I removed both dnsmasq and network-manager last year.

### Bug description
I am experimenting with IPv6, and have a working dual IP stack: connection can go both through IPv4 and IPv6.
IPv6 is through a 6in4 tunnel with he.net, the local endpoint of the tunnel is on the same machine where nss_resolve in argument is failing.
```
$ cat /etc/systemd/network/he-tunnel.netdev
        [Match]
        
        [NetDev]
        Name=he-ipv6
        Kind=sit
        MTUBytes=1480
        
        [Tunnel]
        Local=192.168.xx.xx
        Remote=216.66.xx.xx
        TTL=255
        
$ cat /etc/systemd/network/he-tunnel.network
        [Match]
        Name=he-ipv6
        
        [Network]
        Address=2001:470:xxxx:xxxx::2/64
        Gateway=2001:470:xxxx:xxxx::1
        DNS=2001:470:20::2
        DNS=74.82.42.42
```
When the machine has this in /etc/nsswitch.conf:
```
# /etc/nsswitch.conf
...
hosts:          files resolve [!UNAVAIL=return] dns
... 
```
and in WHEN THE TUNNEL IS UP, that is when both IPv4 and IPv6 connection are available, nss_resolve returns nothing if the name to resolve has **only A records in the DNS** and resolution is invoked through **`getaddrinfo(3)`**. It works if invoked through `gethostbyname2(3)`.
serverfault.com is just one of such hosts today; an innocent involved because happened to be the first whose name resolution failed on me.
The difference between hosts and ahosts in getent, from getent(1) man page: ahosts uses getaddrinfo(3), hosts uses gethostbyname2(3).

### In case of bug report: Unexpected behaviour you saw,  exhibited from libnss_resolve
```
$ getent ahosts serverfault.com
        # No results!
$ getent hosts serverfault.com
        151.101.193.69  serverfault.com
        151.101.129.69  serverfault.com
        151.101.65.69   serverfault.com
        151.101.1.69    serverfault.com
```
### In case of bug report: Expected behaviour, exhibited from libnss_dns
To get correct behavior, removed nss_resolve from /etc/nsswitch.conf
```
# /etc/nsswitch.conf
...
hosts:          files dns
... 
```
and now name resolution works as expected:
```
$ getent ahosts serverfault.com
        151.101.193.69  STREAM serverfault.com
        151.101.193.69  DGRAM  
        151.101.193.69  RAW    
        151.101.129.69  STREAM 
        151.101.129.69  DGRAM  
        151.101.129.69  RAW    
        151.101.65.69   STREAM 
        151.101.65.69   DGRAM  
        151.101.65.69   RAW    
        151.101.1.69    STREAM 
        151.101.1.69    DGRAM  
        151.101.1.69    RAW   
$ getent hosts serverfault.com 
        151.101.193.69  serverfault.com
        151.101.129.69  serverfault.com
        151.101.65.69   serverfault.com
        151.101.1.69    serverfault.com
```
libnss_dns is using the stub resolver provided by systemd-resolved on 127.0.0.53, and returns the A records also to getaddrinfo(3).

**Comment by poettering** [comment] 2018-01-28 09:51
resolved generally suppresses ipv4 addresses when you don#t have a local ipv4 address, unless you query explicitly for it, similar for ipv6 addresses when you don't have a local ipv6 address. Now if I grok this correctly you actually do have both a local ipv4 and a local ipv6 address, right? So there's something not right there. How does your "ip addr" output look like if you run this?

**Comment by Gamberoni** [comment] 2018-01-28 19:29
Output, unabridged:
```
marco@p3:~$ ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether 00:24:54:c9:28:5c brd ff:ff:ff:ff:ff:ff
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether e8:39:df:9e:31:20 brd ff:ff:ff:ff:ff:ff
    inet 192.168.139.32/24 brd 192.168.139.255 scope global dynamic wlan0
       valid_lft 2925sec preferred_lft 2925sec
    inet6 fe80::ea39:dfff:fe9e:3120/64 scope link 
       valid_lft forever preferred_lft forever
4: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
6: he-ipv6@wlan0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN group default qlen 1000
    link/sit 192.168.139.32 peer 216.66.80.98
    inet6 2001:470:25:18d::2/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::c0a8:8b20/64 scope link 
       valid_lft forever preferred_lft forever
7: vboxnet0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 0a:00:27:00:00:00 brd ff:ff:ff:ff:ff:ff
```
This setup earns 20/20 at [http://ipv6-test.com/](http://ipv6-test.com/), it should be representative of a general case of a dual stack IPv4+IPv6 host. I said, I am experimenting with IPv6.

BTW, I have not understood the limits of resolved problem space.
I see  from [systemd/src/resolve/RFCs](https://github.com/systemd/systemd/blob/v234/src/resolve/RFCs) (linking the v234 version I have from the distribution) that RFC6724 "Default Address Selection for Internet Protocol Version 6 (IPv6)" is not in the list. And, OTOH, getaddrinfo(3) from GNU libc implements RFC6724, so do not think resolved should reimplement it.
Here, /etc/gai.conf is at default: only comments, the compiled in libc defaults are used.
Note also that, despite the title, RFC6724 applies to IPv4 too. IPv4 addresses are handled as IPv6 mapped, see comments in /etc/gai.conf.
So when you say 
> resolved generally suppresses ipv4 addresses when you don#t have a local ipv4 address

I would presume you were referring to behavior that is implemented in libc, were it not your source.

**Comment by liskin** [comment] 2019-06-02 22:57
Is this a duplicate of https://github.com/systemd/systemd/issues/5782, too?

**Comment by flokli** [comment] 2019-06-03 10:21
yes, this is a duplicate of #5782.

**Closed as completed** 2020-05-26 17:30 UTC
Labels: resolve
