### ISSUE TITLE
systemd-nspawn can not start nixos-on-nixos

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [systemd/systemd#8971] opened 2018-05-11 16:03 UTC
happens on both v237 and v238. 
looks like related to symlinks, again
original report: https://github.com/NixOS/nixpkgs/issues/40367

## Issue description

attempt to start nixos-on-nixos 
via [systemd-nspawn](https://www.freedesktop.org/software/systemd/man/systemd-nspawn.html)
fails with error in [nspawn.c](https://github.com/systemd/systemd/blob/master/src/nspawn/nspawn.c#L3924):
```
Directory /nix/store/xc7npmnz5ncvw795p9z1xsy4bk3m7spl-nixos-system-nixos-18.03.132304.45cd6090d9a doesn't look like an OS root directory (os-release file is missing). Refusing.
```

despite `os-release` apparently present, although as symlink:
```
ls -las /root/tester/etc/os-release 
0 lrwxrwxrwx 1 root root 58 Jan  1  1970 /root/tester/etc/os-release -> /nix/store/f5nj4avyxmrc4cf36aab17a474vdb36r-etc-os-release
```

### Steps to reproduce

1. given basic `/root/config.nix`:
```
{ config, pkgs, ... }:
{
  imports =
    [ # Include the results of the hardware scan.
    #      ./hardware-configuration.nix
    ];
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  fileSystems."/".device = "/dev/invalid" ;
  system.stateVersion = "18.09";
}
```

2. produce system image:
```
nix build -f '<nixpkgs/nixos>' system -I nixos-config=/root/config.nix -o /root/tester
```

3. now try to instantiate:
```
systemd-nspawn --boot --directory=/root/tester
```

## Technical details

nixos:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.32, NixOS, 18.03.131792.becbe4dbe16 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixos-18.03"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```
systemd:
```
systemd 237
+PAM +AUDIT -SELINUX +IMA +APPARMOR +SMACK -SYSVINIT +UTMP -LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD +IDN2 -IDN -PCRE2 default-hierarchy=hybrid
```

**Comment by kirbyfan64** [comment] 2018-05-11 16:16
Just to be clear, `/nix/store/f5nj4avyxmrc4cf36aab17a474vdb36r-etc-os-release` exists *inside* the tree, not outside, right?

**Comment by Andrei-Pozolotin** [comment] 2018-05-11 16:25
1. no, nixos creates huge *symlink* forest. files/folders only *appear* in right places
there is no nesting relations after symlinks are resolved

2. making total hard link copy for nspawn `--directory` makes the issue go away:
```
cp -a -l -L /root/tester /root/tester-hardlink
systemd-nspawn --boot --directory=/root/tester-hardlink
```
http://man7.org/linux/man-pages/man1/cp.1.html
```
-a, --archive
              same as -dR --preserve=all
-l, --link
              hard link files instead of copying
-L, --dereference
              always follow symbolic links in SOURCE
```

**Comment by kirbyfan64** [comment] 2018-05-11 17:04
No, I'm asking if `/root/tester/nix/store/f5nj4avyxmrc4cf36aab17a474vdb36r-etc-os-release` exists... Based on the fact the hardlink copy succeeded to begin with, I don't think the file pointed to by the symlink exists *inside* the os tree.

**Comment by Andrei-Pozolotin** [comment] 2018-05-11 19:26
ok, I see. I tried both when `/root/tester/nix/store/...` is present (via symlink) and missing, it still produces same error
```
Directory /nix/store/xc7npmnz5ncvw795p9z1xsy4bk3m7spl-nixos-system-nixos-18.03.132304.45cd6090d9a doesn't look like an OS root directory (os-release file is missing). Refusing.
```

**Comment by boucman** [comment] 2018-05-12 08:40
what @kirbyfan64 is asking is "what is os-relese pointing to" 

symlink inside a chroot must point to files inside the chroot... justmaking sure that this is the case here...

**Comment by Andrei-Pozolotin** [comment] 2018-05-12 23:04
@boucman 
yes, when `symlink inside a chroot point to files inside the chroot` it still produces error

**Comment by poettering** [comment] 2018-05-17 16:40
the os-release symlink is pointing to an absolute path, right? if you make it a relative one, does it work then?

**Comment by samliddicott** [comment] 2018-08-22 10:36
What do you get for these commands?

    # chroot /root/tester ls -l /etc/os-release

    # chroot /root/tester cat /etc/os-release

If the symlinks fail inside this chroot, they will fail for systemd-nspawn.

**Comment by poettering** [comment] 2018-11-16 23:09
Lets close this due to lack of reasponse

**Closed as completed by poettering** 2018-11-16 23:09 UTC
Labels: nspawn, needs-reporter-feedback ❓

**Comment by tekeri** [comment] 2019-10-30 07:11
Hi, I have same issue.
/nix/store in the container is available via bind mount of the host /nix/store.
So, os-release is read by following flow:
- <container>/etc/os-release -> symlink
- <container>/etc/static/os-release -> symlink
- <container>/nix/store/13jyj0yzs9h2c1n2y7v71xq2lxp6n0kh-etc-os-release -> bind mount
- (host) /nix/store/13jyj0yzs9h2c1n2y7v71xq2lxp6n0kh-etc-os-release (regular file)

Could you consider reopen this? @refi64 @boucman @poettering

**Comment by tekeri** [comment] 2019-11-01 10:39
Note that it was not reproduced with 239 and 242, but reproducible with 243.
