### ISSUE TITLE
Ubuntu CI: TEST-17-UDEV-WANTS hang calling 'udevadm control --reload'

### ISSUE THREAD

**Issue by ddstreet** [systemd/systemd#13812] opened 2019-10-21 14:11 UTC
**systemd version the issue has been seen with**
> v243

**Used distribution**
 > Ubuntu CI

**Expected behaviour you didn't see**
 > test pass

**Unexpected behaviour you saw**
 > test fail due to: 'udevadm control --reload' blocking/hanging

**Steps to reproduce the problem**
I've seen one failure from #13803 which appears unrelated to that PR.

Ubuntu CI log is: https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-upstream-systemd-ci-systemd-ci/bionic/amd64/s/systemd-upstream/20191019_151707_866cc@/log.gz

**Comment by ddstreet** [comment] 2019-10-21 14:28
journal from failed test:
https://people.canonical.com/~ddstreet/systemd-upstream/pr/13803/TEST-17-UDEV-WANTS-d0f1cfc95563476dab2d6b053d65a227/system.journal

It seems like the command is run:

> Oct 19 09:32:58 systemd-testsuite bash[246]: + udevadm control --reload


then systemd-udevd is reloaded ok:

> Oct 19 09:33:00 systemd-testsuite systemd[1]: systemd-udevd.service: Got notification message from PID 229 (RELOADING=1, STATUS=Flushing configuration...)
> Oct 19 09:33:00 systemd-testsuite systemd[1]: systemd-udevd.service: Changed running -> reload
> Oct 19 09:33:00 systemd-testsuite systemd[1]: Added job systemd-udevd.service/nop to transaction.
> Oct 19 09:33:00 systemd-testsuite systemd[1]: systemd-udevd.service: Installed new job systemd-udevd.service/nop as 70
> Oct 19 09:33:00 systemd-testsuite systemd[1]: systemd-udevd.service: Job 70 systemd-udevd.service/nop finished, result=done
> Oct 19 09:33:00 systemd-testsuite systemd[1]: systemd-udevd.service: Got notification message from PID 229 (READY=1, STATUS=Processing with 10 children at max)
> Oct 19 09:33:00 systemd-testsuite systemd[1]: systemd-udevd.service: Changed reload -> running
> 

but the call to udevadm never finishes, and times out 60 seconds after being called:

> Oct 19 09:33:58 systemd-testsuite bash[246]: Failed to wait for daemon to reply: Connection timed out
> Oct 19 09:33:58 systemd-testsuite systemd[1]: Received SIGCHLD from PID 246 (bash).
> Oct 19 09:33:58 systemd-testsuite systemd[1]: Child 246 (bash) died (code=exited, status=1/FAILURE)
> 

I do notice that dbus isn't started until *after* the call to udevadm and its reload; is dbus responsible for relaying the finished-reload back to udevadm?

> Oct 19 09:33:40 systemd-testsuite systemd[1]: dbus.socket: Incoming traffic
> Oct 19 09:33:40 systemd-testsuite systemd[1]: dbus.service: Trying to enqueue job dbus.service/start/replace
> Oct 19 09:33:41 systemd-testsuite kernel: audit: type=1130 audit(1571492021.466:10): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=dbus comm="systemd" exe="/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
> Oct 19 09:33:41 systemd-testsuite audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=dbus comm="systemd" exe="/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
> Oct 19 09:33:40 systemd-testsuite systemd[1]: dbus.service: Installed new job dbus.service/start as 71
> Oct 19 09:33:40 systemd-testsuite systemd[1]: dbus.service: Enqueued job dbus.service/start as 71
> Oct 19 09:33:40 systemd-testsuite systemd[1]: dbus.socket: Changed listening -> running
> Oct 19 09:33:40 systemd-testsuite systemd[1]: dbus.service: Failed to set 'memory.min' attribute on '/system.slice/dbus.service' to '0': No such file or directory
> Oct 19 09:33:40 systemd-testsuite systemd[1]: dbus.service: Failed to set 'memory.swap.max' attribute on '/system.slice/dbus.service' to 'max': No such file or directory
> Oct 19 09:33:40 systemd-testsuite systemd[1]: dbus.service: Failed to set 'memory.oom.group' attribute on '/system.slice/dbus.service' to '0': No such file or directory
> Oct 19 09:33:40 systemd-testsuite systemd[1]: dbus.service: Passing 1 fds to service
> Oct 19 09:33:40 systemd-testsuite systemd[1]: dbus.service: About to execute: /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
> Oct 19 09:33:40 systemd-testsuite systemd[1]: dbus.service: Forked /usr/bin/dbus-daemon as 265
> Oct 19 09:33:40 systemd-testsuite systemd[1]: dbus.service: Changed dead -> running
> Oct 19 09:33:42 systemd-testsuite dbus-daemon[265]: dbus[265]: Unknown group "power" in message bus configuration file
> Oct 19 09:33:40 systemd-testsuite systemd[1]: dbus.service: Job 71 dbus.service/start finished, result=done
> Oct 19 09:33:40 systemd-testsuite systemd[1]: Started D-Bus System Message Bus.
> Oct 19 09:33:40 systemd-testsuite systemd[265]: dbus.service: Executing: /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
>

**Comment by exFalso** [comment] 2022-01-05 20:29
We're seeing this reproducibly in a production setup, systemd hangs for 1 minute after certain operations. I straced it down to a wait on `/sbin/udevadm control --reload`, the strace from there is not very helpful:
```
$ sudo strace -p 2502955
strace: Process 2502955 attached
restart_syscall(<... resuming interrupted poll ...>) = 0
close(3)                                = 0
exit_group(2)                           = ?
+++ exited with 2 +++
```
It's a bit difficult to debug as e.g. `ps aux` and a bunch of other commands also hang in these situations. Any tips on how to debug further?

**Comment by dimara** [comment] 2022-01-11 15:42
> hangs for 1 minute after certain operations

We bumped into this when using `udevadm` from inside a container that has `/run/udev/` bind mounted. Our container runs debian/stretch, i.e., systemd/udev 232. This was working until we tried a host running Ubuntu Focal, i.e., systemd/udev 245.

> Any tips on how to debug further?

We ran strace both on `udevadm` inside the container and `systemd-udevd` inside the host.

`udevadm` that hangs send a message and waits for the response for 60sec:
```
connect(3, {sa_family=AF_UNIX, sun_path="/run/udev/control"}, 19) = 0

sendto(3, "udev-232\0\0\0\0 ... ) = 280

poll([{fd=3, events=POLLIN}], 1, 60000) = 0 (Timeout)
close(3)                                = 0
getpid()                                = 890
exit_group(2)                           = ?
+++ exited with 2 +++
```

`systemd-udevd` consumes the message but waits for another until the client (udevadm) timeouts:
```
36149 accept4(4, NULL, NULL, SOCK_CLOEXEC|SOCK_NONBLOCK) = 14
36149 recvfrom(14, NULL, 0, MSG_PEEK|MSG_TRUNC, NULL, NULL) = 280
36149 recvfrom(14, NULL, 0, MSG_PEEK|MSG_TRUNC, NULL, NULL) = 0
```

We straced `udevadm control --ping` directly on the host and saw that it was sending two messages:
```
connect(3, {sa_family=AF_UNIX, sun_path="/run/udev/control"}, 20) = 0
sendto(3, "udev-245\0\0\0\0\0\0\0 ... = 280
sendto(3, "udev-245\0\0\0\0\0\0\0\0\352\35\255\336\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0 ... = 280
```
and `systemd-udevd` received both messages:
```
36149 accept4(4, NULL, NULL, SOCK_CLOEXEC|SOCK_NONBLOCK) = 14
36149 recvfrom(14, NULL, 0, MSG_PEEK|MSG_TRUNC, NULL, NULL) = 280
36149 recvfrom(14, NULL, 0, MSG_PEEK|MSG_TRUNC, NULL, NULL) = 280
```

Using udev 241 inside the container failed as well. So we took a look at the code changes between 241 and 245 and seems that https://github.com/systemd/systemd/commit/78467aeb9578bee56211a64190b3293616647aee is related that is included in 242. We noticed that the command that fails sends:
```
udev-241\0\0\0\0\0\0\0\0\352\35\255\336\7\0
```
while the command that works sends:
```
udev-245\0\0\0\0\0\0\0\0\352\35\255\336\7\0
udev-245\0\0\0\0\0\0\0\0\352\35\255\336\0\0
```
The commit above supported multiple commands on the same connection. The first message is a UDEV_CTRL_PING. We understand that udevd is waiting for an explicit _UDEV_CTRL_END_MESSAGES before serving the request. Is this the case?

If so this means that udev is not compatible across versions. Is this intended?

**Comment by yuwata** [comment] 2022-01-11 17:18
> The commit above supported multiple commands on the same connection. The first message is a UDEV_CTRL_PING. We understand that udevd is waiting for an explicit _UDEV_CTRL_END_MESSAGES before serving the request. Is this the case?
> If so this means that udev is not compatible across versions. Is this intended?

Unfortunately, yes. The commit breaks compatibility, so we cannot use different version of udevd and udevadm simultaneously.

**Comment by yuwata** [comment] 2022-06-28 07:50
This will not be fixed, and I do not think it is necessary to fix. Closing.

**Closed as completed by yuwata** 2022-06-28 07:50 UTC
Labels: udev, tests, cant-fix, ci-blocker 🚧
