### ISSUE TITLE
Swap mount does not obey conditional

### ISSUE THREAD

**Issue by Thinstation** [systemd/systemd#10271] opened 2018-10-04 15:59 UTC
After creating a swap mount unit, and setting a conditionalpathexist, the system will fail the unit startup and slow down init if the path doesn’t exist. 

Desired behavior is for the unit to be ignored, like a regular mount unit with path conditional would be.

**Comment by poettering** [comment] 2018-10-05 16:19
what is a "swap mount unit"? Do you mean .swap units? or .mount units? Those are two seperate concepts!

Please provide the exact unit file you are using and how it has been enabled, also please provide log out of the boot process.

Also, first of all, which systemd version are you using, which distribution? Note that the issue submission form has fields for all that information, and the idea is that this information is supplied when the issue is filed...

We need more information to figure out what you are saying and what the problem is you are running into.

**Comment by Thinstation** [comment] 2018-10-05 20:46
Using the ThinStation linux distro. Working through all the issues of integrating systemd into LiveCD/Transient operating systems with dynamic configuration.

The unit is generated by systemd from fstab with the systemd-fstab-generator.
It's activated by a symlink in /etc/systemd/system/swap.target.wants

.txt added to unit file post to get around github filter for file attachment.

[thinstation.boot.log](https://github.com/systemd/systemd/files/2452197/thinstation.boot.log)
[dev-disk-by@%x2dlabel-swap.swap.txt](https://github.com/systemd/systemd/files/2452200/dev-disk-by.x2dlabel-swap.swap.txt)

**Comment by arvidjaar** [comment] 2018-10-06 05:02
> `Oct 05 13:35:45 thinstation-linux systemd[1]: dev-disk-by\x2dlabel-swap.device: Job dev-disk-by\x2dlabel-swap.device/start timed out.`
> `Oct 05 13:35:45 thinstation-linux systemd[1]: Dependency failed for /dev/disk/by-label/swap.`

As explained recently in similar question, conditions are evaluated when unit is going to be activated. In your case unit never gets as far - swap unit has implicit dependency on device unit and it times out before activation can even be attempted.

**Comment by Thinstation** [comment] 2018-10-06 13:43
At this point, there is no swap device. It’s not in physical existence. There is nothing in swap.target.wants linking to a device unit. A file system mount doesn’t have this limitation, why does swap?

**Comment by arvidjaar** [comment] 2018-10-06 14:49
This has nothing to do with obeying or not conditionals. If you believe unit is attempted to be actvated improperly, collect full log at debug level (the one you provided is truncated) and post question to mailing list or better ask your distribution support channel.

**Comment by Thinstation** [comment] 2018-10-07 02:05
I do not think we are understanding each other. When I allow the fstab generator to generate some unit files for filesystem partitions and swap partitions, and then move those units from *. requires to *.wants. Update them to include ConditionalPathExist=<the path>, filesystem units conform to expectations and act conditionally, the swap does not.

**Comment by poettering** [comment] 2018-10-08 07:33
This is a misunderstanding how ConditionXYZ= in systemd works. These concepts do *not* have an effect on the jobs queued (and thus waited for) but only an effect on the actual operation of the unit itself (in case of .swap units that means the mkswap invocation). They are checked immediately before the actual operation would be executed, and not at the time the job for the unit is enqueued.

Hence, if you add a .swap unit into the initial transaction, and will still pull in the matching .device unit, and if you have an ordering dep on swap.target (or any other target that is pulled in the initial transaction), then you will still have to wait for it.

This behaviour is documented btw... see systemd.unit(5)

I am not sure what you are trying to do, but if you are looking for a way to define a swap unit that is skipped when its backing device is not around, then add a udev rules files that matches the swap device you want to activate and set ENV{SYSTEMD_WANTS}= on your .swap unit, so that the .swap unit (and any deps it might have) are only pulled in when the device showed up.

Closing, as this is documented and expected behaviour

**Closed as completed by poettering** 2018-10-08 07:33 UTC
Labels: needs-reporter-feedback ❓
