### ISSUE TITLE
test-watchdog causes system reboot

### ISSUE THREAD

**Issue by floppym** [systemd/systemd#22001] opened 2022-01-04 22:08 UTC
**systemd version the issue has been seen with**
948d085e899273f3a34376665414d1ecd1858978

**Used distribution**
Gentoo

**Linux kernel version used** (`uname -a`)
 `Linux naomi 5.15.12-dist #1 SMP Fri Dec 31 12:43:34 EST 2021 x86_64 AMD Phenom(tm) II X6 1055T Processor AuthenticAMD GNU/Linux`

**CPU architecture issue was seen on**
x86_64

**Expected behaviour you didn't see**
Successful test run.

**Unexpected behaviour you saw**
System immediately reboots.

**Steps to reproduce the problem**
Run `test-watchdog` as root.

**Comment by floppym** [comment] 2022-01-04 22:32
Note that `test-watchdog` is run automatically by `meson test`, which might not be a great idea.

**Comment by bluca** [comment] 2022-01-04 23:33
That's weird - what's in the log, with debug level? Sounds like watchdog pinging is not working

**Comment by floppym** [comment] 2022-01-05 04:20
> what's in the log, with debug level?

The kernel reboots the system before any logs can be stored.
In a terminal, I see `Pinging...` appear twice before the reboot happens.

**Comment by floppym** [comment] 2022-01-05 04:32
When I set SYSTEMD_SLOW_TESTS=true, the test works fine.

Maybe the watchdog device on this system can't handle the 1 second timeout that the test uses by default.
```
# SYSTEMD_SLOW_TESTS=true ./test-watchdog
Using hardware watchdog 'SP5100 TCO timer', version 0, device /dev/watchdog0
Watchdog running with a timeout of 10s.
Pinging...
Pinging...
Pinging...
Pinging...
Pinging...
```

**Comment by evverx** [comment] 2022-01-05 05:35
@floppym I wonder if the test passes with v249 without SYSTEMD_SLOW_TESTS=true? If it does it's probably a regression caused by https://github.com/systemd/systemd/pull/20650.

**Comment by floppym** [comment] 2022-01-05 05:38
I can give it a try with v249 tomorrow.

**Comment by evverx** [comment] 2022-01-05 06:37
On the other hand, considering that the test seems to have printed "Pinging..." without "Failed to ping watchdog" it could be that the test itself can't handle scenarios where 1s isn't supported because if the timeout is actually set to something else the following loop
```c
        for (i = 0; i < count; i++) {
                log_info("Pinging...");
                r = watchdog_ping();
                if (r < 0)
                        log_warning_errno(r, "Failed to ping watchdog: %m");

                usleep(t/2);
```
seems to be wrong.

**Comment by evverx** [comment] 2022-01-05 07:09
Anyway, I'm pretty sure it has something to do with https://github.com/systemd/systemd/pull/20650/commits/2628b98f0ca511a0d454940399aeaae156d16eeb (where `watchdog_set_timeout` replacing `t` with the actual timeout was replaced `watchdog_set_timeout` receiving the value of `t` without changing it later)

**Comment by evverx** [comment] 2022-01-05 07:24
And it's a bug in pid1 because at least 
```
if (asprintf(&e, "WATCHDOG_USEC="USEC_FMT, watchdog_timer) > 0)
```
seems to be bogus now

**Comment by mrc0mmand** [comment] 2022-01-05 10:09
I suspect it's the same issue I've had to deal with in CentOS CI - tl;dr it's a kernel bug in the iTCO_wdt module.

*My whole story:* https://pagure.io/centos-infra/issue/505
Kernel BZ: https://bugzilla.kernel.org/show_bug.cgi?id=213809
Fix: https://patchwork.kernel.org/project/linux-watchdog/patch/20211008003302.1461733-1-linux@roeck-us.net/

@floppym could this be the root cause?

**Comment by floppym** [comment] 2022-01-05 14:42
I tested with v249.7, and saw the same reboot behavior without `SYSTEMD_SLOW_TESTS` enabled.

I took a video and the following text appears in the terminal just before the reboot:
```
Using hardware watchdog 'SP5100 TCO timer', version 0, device /dev/watchdog
Set hardware watchdog to 1s.
Pinging...
Pinging...
```

**Comment by floppym** [comment] 2022-01-05 15:04
> I suspect it's the same issue I've had to deal with in CentOS CI - tl;dr it's a kernel bug in the iTCO_wdt module.
> Fix: https://patchwork.kernel.org/project/linux-watchdog/patch/20211008003302.1461733-1-linux@roeck-us.net/

I am running Linux 5.15.2. The patch you linked was merged before 5.15 was released.

**Comment by evverx** [comment] 2022-01-05 16:51
Having said that, @fbuihuu looks like https://github.com/systemd/systemd/commit/2628b98f0ca511a0d454940399aeaae156d16eeb kind of broke the test in the sense that it relied on `t` being set to the actual timeout. And `systemd` itself seems to have started printing bogus timeouts like `WATCHDOG_USEC` after calling `watchdog_set_timeout`.

**Comment by yuwata** [comment] 2022-01-05 17:10
@evverx Could you show the difference of `WATCHDOG_USEC` before and after the commit?

**Comment by evverx** [comment] 2022-01-05 17:21
@yuwata I'm not sure I can reproduce a scenario where they can be different with my watchdog but they can because systemd actually uses the closest values supported by drivers:
```
        /* Initialize the watchdog timeout with the caller value. This value is
         * going to be updated by update_timeout() with the closest value
         * supported by the driver */
```

**Comment by fbuihuu** [comment] 2022-01-06 17:07
> Anyway, I'm pretty sure it has something to do with [2628b98](https://github.com/systemd/systemd/commit/2628b98f0ca511a0d454940399aeaae156d16eeb) (where `watchdog_set_timeout` replacing `t` with the actual timeout was replaced with `watchdog_set_timeout` receiving the value of `t` without changing it later)

I think you're right `t` needs to be updated with the real timeout value used by the driver.

However there's no API to retrieve the real timeout value because there's no need to do that as `watchdog_runtime_wait()` are supposed to be used to wait until the next ping.

So I think we should replace `usleep(t/2)` with `watchdog_runtime_wait()`.

**Comment by fbuihuu** [comment] 2022-01-06 17:08
> And it's a bug in pid1 because at least
> 
> ```
> if (asprintf(&e, "WATCHDOG_USEC="USEC_FMT, watchdog_timer) > 0)
> ```
> 
> seems to be bogus now

I'm not seeing why, could you explain ?

**Comment by evverx** [comment] 2022-01-06 18:24
@fbuihuu as far as I understand that patch was based on the assumption that actual timeouts weren't used anywhere so I just looked for places where they were used and where that patch could change anything. I said it was a bug because I'd expect systemd to show real timeouts by analogy with what it had been doing until that patch was merged. I don't think it's critical or anything like that but it's a change and I'm not sure whether it's expected or not.

**Comment by floppym** [comment] 2022-01-06 19:03
It looks like this test works on my hardware with a timeout value as low as 2 seconds. It's just the 1 second timeout that leads to a reboot.

**Comment by bluca** [comment] 2022-01-06 19:10
weird, but I guess we can set it at 2s in the test, shouldn't hurt

**Closed as completed** 2022-01-07 03:28 UTC
Labels: bug 🐛, tests

**Comment by fbuihuu** [comment] 2022-01-07 08:24
> @fbuihuu as far as I understand that patch was based on the assumption that actual timeouts weren't used anywhere so I just looked for places where they were used and where that patch could change anything. I said it was a bug because I'd expect systemd to show real timeouts by analogy with what it had been doing until that patch was merged. 

PID1 still show the real timeout, see `update_timeout()`.

The user can't retrieve it easily because there's no API for that but I think it was the same before 2628b98f0ca511a0d454940399aeaae156d16eeb.

> I don't think it's critical or anything like that but it's a change and I'm not sure whether it's expected or not.

It is. We need to store the target timeout value (the one passed by the user) because the actual timeout used by the driver might have been approximated due to the HW limitation and we don't want to reuse this approximated value if the user decide to use another watchdog device for example.
