### ISSUE TITLE
systemd-nspawn --bind does not bind recursively

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#4848] opened 2016-12-07 17:05 UTC
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> systemd 232 +PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Arch Linux

### Bugreport

I have a container with the following settings:
```
/usr/bin/systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest --settings=override --machine=%I --capability=CAP_NET_ADMIN --network-veth --bind=/tmp/.X11-unix:/tmp/.X11-unix --setenv="DISPLAY=:0" 
```

I bind `/tmp/.X11-unix` to access my X11-Socket from my host. This way I can spawn a graphical application for example firefox in the container. This doesn't work anymore since systemd version 232.

I have set `xhost +local:` on my host, but the directory /tmp/.X11-unix on my guest-container is empty.

**Comment by poettering** [comment] 2016-12-07 18:22
Hmm, this actually sounds like a duplicate of #4789. Closing hence.

**Closed as completed by poettering** 2016-12-07 18:22 UTC
Labels: nspawn, duplicate
