### ISSUE TITLE
networkd: allow DUID configuration for DHCPv6 and DHCPv4

### ISSUE THREAD

**Issue by j16sdiz** [systemd/systemd#394] opened 2015-06-28 10:52 UTC
The backend code seems to be implemented in 66eac1201a9c1596f5901f8dbbf24bda7e350878, but there is no where to configure.

RFC4361 reads <q>Any DHCPv6 client ... SHOULD ... provide a means by which the operator can configure the DUID</q>. It would be nice if systemd can support that in the unit file.

My ISP relies on DUID to do prefix delegation. All 3 major DHCPv6 implementations support that already, so my ISP is very unlikely to change.

**Comment by j16sdiz** [comment] 2015-06-28 10:59
Related to #345 ?
As far as I can tell, all major DHCP implementation persistent the client id on disk. 
This allow the admin to change that and prevent unexpected changes like #345

**Comment by poettering** [comment] 2015-07-23 19:29
Yeah, what #345 appears to discuss for IPv4, this discusses for IPv6. Let's close #345, and make this issue about both.

@teg, any opinion on this? Should the DUID be configurable in the unit files?

**Comment by teg** [comment] 2015-07-23 20:08
I'm not opposed to making the DUID (and possible the IAID?) statically (or partially statically) configurable.

I prefer if we don't just dump binary data though, how about something like introducing:
DUIDType=, DUIDEnterpriseNumber=, DUIDHardwareType=, DUIDTime=, DUIDHardwareAddress=, DUIDIdentifier=, DUIDUUID=. Where DUIDType determines which of the other keys are valid, and each of the other keys can be formatted in their usual way, with DUIDIdentifier (used by DUID-EN) the only one that is just arbitrary data (probably represented in hex).

We should allow keys to be omitted where that makes sense, so HardwareAddress, HardwareType can be deduced, EnterpriseNumber we can fallback to our own one, and UUID we can fall back to one generated from a hash of our machine-id, and Identifier we can fall back to the algorithm we currently use. I guess it does not make sense to have a fallback for Time though, so that would have to be specified if DUID-LLT is used.

Note that this still assumes we use RFC4361-style client identifiers for DHCPv4 (though their contents will obviously be as specified above), if we want to also allow statically setting the legacy-style DHCPv4 client identifiers we should consider introducing a ClientIdentifier=Legacy|NodeSpecific (the latter being the default). In case of Legacy we use DUIDHardwareType and DIDHardwareAddress= to generate the ClientIdentifier (using the same logic as above). This still leaves out completely arbitrary ClientIdentifiers as some other clients support, but I don't think that is something we should do (as it is contrary to the RFC and I have read reports of problems caused by this).

**Comment by teg** [comment] 2015-07-23 20:11
@j16sdiz out of interest, what are the DUID requirements of your ISP? Would the above scheme suit you?

**Comment by teg** [comment] 2015-07-23 20:12
Probably we should also support ClientIdentifier=None for the DHCPv4 case, as I have seen requests for that.

**Comment by teg** [comment] 2015-07-23 20:17
Seems my memory of what we have merged is not the best. We already support ClientIdentifier=mac|duid, so all we would have to do is to hook up the DUID (and possibly add ClientIdentifier=none if anyone wants that still).

**Comment by poettering** [comment] 2015-07-23 20:22
urks, having so many DUID options is ugly, but I figure it's the cleanest way. One recommendation though: i'd add a logic so that DUIDType= is determined automatically if not explicitly specified by what is set otherwise. i.e. so that if DUIDEnterpreiseNr= is set, but nothing else, DUIDType=en is implied... But that's just the cherry on top, and of course has to deal with ambigiuities...

**Comment by teg** [comment] 2015-07-23 20:25
Yeah, that makes sense. I agree about the ugliness though (which is why I didn't do this from the get-go). Patches welcome (but I'll add to TODO regardless)!

**Comment by j16sdiz** [comment] 2015-07-28 07:03
@teg My ISP give me a `duid-ll`. 
You can see how others do that in `dhclient`: https://forum.online.net/index.php?/topic/4729-howto-ipv6-using-dhclient-for-ubuntu/

**Comment by samueltardieu** [comment] 2015-12-19 09:04
Has there been a progress on this front, or a workaround? I switched one of my servers to `systemd` and cannot use IPv6 since I have to pass a client-identifier to the DHCPv6 server.

_Edit:_ in the meantime, running `dibbler` as a workaround works fine

**Comment by ppira** [comment] 2016-01-07 07:49
A use case for  "ClientIdentifier=none"; when pxebooting (nfsroot) the pxe stack and the Linux kernel requests a lease with no uid. When systemd-networkd requests a DHCP lease an uid is always sent with either duid or mac. ISC dhcpd treats the lease with uid and lease without uid as separate leases and I end up with two ipv4 addresses on my interface. One workaround is to upgrade the DHCP servers to ISC dhcpd 4.3.3 which has the option "ignore-client-uids". This is a bit impractical on "enterprise" dists like RHEL/CentOS and the likes.

**Comment by vinaykul** [comment] 2016-02-18 01:08
Hi,

I work on the VMware Photon OS team. We also have a use-case where we need the ability to configure DUID and IAID in networkd. 

When we upgrade a VM from an OS that uses dhclient (or similar) to Photon OS that uses systemd-networkd, configuring DUID and IAID values extracted from the VM being upgraded allows the new VM to acquire the same IPv6 addresses as VM that got upgraded. I'm investigating a solution / systemd patch to allow DUID and IAID configuration. 

My initial thoughts are to keep things simple and allow for system-wide DUID value to be configured raw in a manner similar to dhclient option dhcp.client-identifier or dhcp6.client-id  (per example suggested by @j16sdiz ). The idea is to have systemd look for /etc/systemd/network/dhcp-duid file that contains user configured DUID e.g. DUIDValue=XX:XX:XX:XX. If this file is not present, systemd falls back to using machine-id (current algorithm). My reasoning: If this ever needs to be user-configured, e.g. ISP provided value or our above use-case, the consumer will likely get a readable string (similar to MACaddress) and will just plug that in. This way we don't need  the added code/testing complexity of breaking it down into DUID type, hardware type etc... not sure what it buys us in the first place.

On initial code walk-through, I think the [Link] section is the best place to plug in the interface specifid IAIDValue. Thoughts?  If we work on such a solution, would you take the patch? 

Thanks,
Vinay

**Comment by j16sdiz** [comment] 2016-02-18 08:17
I prefer raw DUID as well. This make migrating from existing dhcp client easier.

**Comment by poettering** [comment] 2016-02-18 16:50
My recommendation would be to provide a good patch that adds this, that's usually the most convincing argument.

**Comment by vinaykul** [comment] 2016-02-29 02:26
I've requested PR https://github.com/systemd/systemd/pull/2761 . Please review. 
Thanks,
Vinay

**Closed as completed** 2016-05-23 00:22 UTC
Labels: RFE 🎁, network
