### ISSUE TITLE
error: argument to ‘-O’ should be a non-negative integer, ‘g’, ‘s’, ‘z’ or ‘fast’

### ISSUE THREAD

**Issue by xiacunshun** [systemd/systemd#25677] opened 2022-12-08 12:48 UTC
### systemd version the issue has been seen with

251

### Used distribution

OpenCloudOS

### Linux kernel version used

5.4.119-1-tlinux4-0008

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

build success

### Unexpected behaviour you saw

/usr/bin/gcc -c ../src/fundamental/bootspec-fundamental.c -o src/boot/efi/bootspec-fundamental.c.o -Wno-format-signedness -Wno-missing-field-initializers -Wno-unused-parameter -Wdate-time -Wendif-labels -Werror=format=2 -Werror=implicit-function-declaration -Werror=incompatible-pointer-types -Werror=int-conversion -Werror=overflow -Werror=override-init -Werror=return-type -Werror=shift-count-overflow -Werror=shift-overflow=2 -Werror=undef -Wfloat-equal -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-include-dirs -Wmissing-noreturn -Wnested-externs -Wold-style-definition -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-aliasing=2 -Wstrict-prototypes -Wsuggest-attribute=noreturn -Wunused-function -Wwrite-strings -Wno-maybe-uninitialized -Wno-unused-result -fno-stack-protector -fno-strict-aliasing -fpic -fwide-exec-charset=UCS2 -Wall -Wextra -Wsign-compare -nostdlib -std=gnu11 -ffreestanding -fshort-wchar -fvisibility=hidden -isystem /usr/include/efi -isystem /usr/include/efi/x86_64 -I /builddir/build/BUILD/systemd-251/src/fundamental -DSD_BOOT -DGNU_EFI_USE_MS_ABI -include src/boot/efi/efi_config.h -include version.h -mno-red-zone -mno-sse -mno-mmx -Oplain -flto -O2 -flto=auto
cc1: error: argument to ‘-O’ should be a non-negative integer, ‘g’, ‘s’, ‘z’ or ‘fast’

### Steps to reproduce the problem

package version:
 gcc-12.2.0
 meson-0.64.0

then rpmbuild systemd.

I tried  meson-0.60.3 and it passed.
But meson-0.64.1 failed.

Is there any compatible problems between meson and systemd (at least between the versions above)?

**Comment by xiacunshun** [comment] 2022-12-08 12:52
Having compared the build.log, I think it's "-Oplain" that results in the fault.

**Comment by mrc0mmand** [comment] 2022-12-08 13:10
This is most likely caused by this backward-incompatible change in meson 0.64:  https://github.com/mesonbuild/meson/pull/10593

Snippet from the changelog:

> Add optimization plain option
>
> The optimization built-in option now accepts plain value, which will not set any optimization flags. This is now the default value of the flag for buildtype=plain, which is useful for distros, that set the optimization and hardening flags by other means.
>
> If you are using the value of get_option('optimization') in your Meson scripts, make sure you are not making assumptions about it, such as that the value can be passed to a compiler in -O flag.

**Comment by mrc0mmand** [comment] 2022-12-08 13:14
Ah, nevermind, this is already addressed in 7aa4762ce274a1c9a59902b972fa4fdee1b22715, so you need to backport at least this change.

**Closed as completed by mrc0mmand** 2022-12-08 13:14 UTC
Labels: build-system, already-fixed
