### ISSUE TITLE
Allow to enable split mode on volatile storage

### ISSUE THREAD

**Issue by glandium** [systemd/systemd#3281] opened 2016-05-18 01:01 UTC
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 229

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Debian unstable (229-6)
### In case of bug report: Expected behaviour you didn't see

As a user, `journalctl --user`, `journalctl -t firefox.desktop`, etc. says:

```
Hint: You are currently not seeing messages from other users and the system.
      Users in the 'systemd-journal' group can see all messages. Pass -q to
      turn off this notice.
No journal files were opened due to insufficient permissions.
```

One would normally expect to be able to see the logs of the applications they are running. But a common combination of defaults and file existence leads to it not being possible. Specifically:
- `Storage` defaults to `auto` and `/var/log/journal` will, in many cases, not already exist, so in practice, that means `volatile`.
- `SplitMode` defaults to `uid`, but the documentation says:
  > If journals are stored on volatile storage (see above), only a single journal file for all user IDs is kept.

So, in practice, in many cases, users ends up with volatile storage with a single journal file, and can't have access to the logs of their running applications.

However, there is no indication in the documentation as to why volatile storage can't have split journal. One hypothesis is that it's because of the reliance on ACLs, but TMPFS has had ACL support since kernel 3.0 (CONFIG_TMPFS_POSIX_ACL).

If this is indeed the case, I'd argue volatile storage should add support for split journal when possible.

**Comment by glandium** [comment] 2016-05-18 01:06
The code in `journal-server.c`:`find_journal` doesn't give a reason why user logs are not split in /run.

**Comment by glandium** [comment] 2016-05-18 01:11
f4b4781191e8edfb5690e4447166e3ba7bcb48f5 is where volatile storage was added, and there is no rationale given why not supporting split logs there.

**Comment by glandium** [comment] 2016-05-18 01:13
> TMPFS has had ACL support since kernel 3.0 (CONFIG_TMPFS_POSIX_ACL).

Actually, 2.6.19. 3.0 added support for xattr. (CONFIG_TMPFS_XATTR)

**Comment by fsateler** [comment] 2016-05-19 15:01
This was requested before: #2744, the problem is quotas, not acl.

**Comment by glandium** [comment] 2016-05-19 22:25
User applications are filling the system log in /run/log/journal, what would quotas prevent?

**Comment by mbiebl** [comment] 2016-05-19 22:37
I don't quite buy the user-DOS argument / quota argument. How is a regular user supposed to DOS the system? Those log messages are guarded by journald after all which can apply any configured limits.

**Comment by mbiebl** [comment] 2016-05-19 22:47
s/buy/understand/, the journal found in /var/log/journal are ro by the user (via ACLs). If we apply the same logic to /run/log/journal, how can a user DOS the system? She can certainly run logger foo in a loop, but that would all go through journald which can apply any limits as configured.

**Comment by poettering** [comment] 2016-05-20 13:49
I figure the quota argument is bogus. I reopened #2744 now, let's make this a duplicate of it.

**Closed as completed by poettering** 2016-05-20 13:49 UTC
Labels: RFE 🎁, journal, duplicate
