### ISSUE TITLE
systemd-analyze blame prints wrong output

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#15093] opened 2020-03-12 02:27 UTC
**systemd version the issue has been seen with**
> 245

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**

`systemd-analyze blame` should generate the right output

**Unexpected behaviour you saw**
`systemd-analyze blame` prints the following:

```
2month 1w 3d 5h 2min 40.101s dev-hugepages.mount                                
2month 1w 3d 5h 2min 40.100s systemd-journald.service                           
2month 1w 3d 5h 2min 40.100s updatedb.service                                   
2month 1w 3d 5h 2min 40.100s dev-mqueue.mount                                   
2month 1w 3d 5h 2min 40.100s boot.mount                                         
2month 1w 3d 5h 2min 40.099s systemd-journal-catalog-update.service             
2month 1w 3d 5h 2min 40.099s systemd-backlight@backlight:intel_backlight.service
2month 1w 3d 5h 2min 40.099s polkit.service                                     
2month 1w 3d 5h 2min 40.098s lvm2-monitor.service                               
2month 1w 3d 5h 2min 40.098s initrd-parse-etc.service                           
2month 1w 3d 5h 2min 40.098s tmp.mount                                          
2month 1w 3d 5h 2min 40.098s systemd-hwdb-update.service                        
2month 1w 3d 5h 2min 40.098s systemd-udevd.service                              
2month 1w 3d 5h 2min 40.098s systemd-fsck@dev-sda1.service                      
2month 1w 3d 5h 2min 40.098s systemd-binfmt.service             
...
```

is this supposed to look like this? The man page is showing something else.
If it's supposed to look like this, somebody should update the man page accordingly.

**Steps to reproduce the problem**

execute `systemd-analyze blame`

**Comment by mbiebl** [comment] 2020-03-12 02:51
duplicate of #14830

**Closed as completed by mbiebl** 2020-03-12 02:51 UTC
Labels: duplicate
