### ISSUE TITLE
v.243 ignores After condition in service file (cryptsetup)

### ISSUE THREAD

**Issue by lourdas** [systemd/systemd#13977] opened 2019-11-08 15:19 UTC
**systemd version the issue has been seen with**
243-r2 (Gentoo package)

**Used distribution**
Gentoo

**Expected behaviour you didn't see**
systemd-cryptsetup mounts the dm volume after asking for the password during boot.

**Unexpected behaviour you saw**
systemd-cryptsetup fails to mount the dm volume and drops to maintenance.

**Steps to reproduce the problem**
My /home partition is a LUKS partition on top of a dmraid 1 mirror. systemd-cryptsetup fails because at the time it tries to encrypt the volume, the dm device from the raid 1 mirror has not yeat appeared. It drops me into maintenance mode where I can start systemd-cryptsetup@home.service manually (it asks for password) and I can continue to the default target.

Running /lib/systemd/system-generators/systemd-cryptsetup-generator exports the systemd-cryptsetup@home.service file inside /tmp:

    # Automatically generated by systemd-cryptsetup-generator

    [Unit]
    Description=Cryptography Setup for %I
    Documentation=man:crypttab(5) man:systemd-cryptsetup-generator(8) man:systemd-cryptsetup@.service(8)
    SourcePath=/etc/crypttab
    DefaultDependencies=no
    Conflicts=umount.target
    IgnoreOnIsolate=true
    After=cryptsetup-pre.target
    Before=cryptsetup.target
    BindsTo=dev-md-sysresccd:HOME_ARRAY.device
    After=dev-md-sysresccd:HOME_ARRAY.device
    Before=umount.target

    [Service]
    Type=oneshot
    RemainAfterExit=yes
    TimeoutSec=0
    KeyringMode=shared
    OOMScoreAdjust=500
    ExecStart=/lib/systemd/systemd-cryptsetup attach 'home' '/dev/md/sysresccd:HOME_ARRAY' 'none' 'timeout=300'
    ExecStop=/lib/systemd/systemd-cryptsetup detach 'home'

It seems that the line `After=dev-md-sysresccd:HOME_ARRAY.device` is ignored. As a temporary workaround, I added `ExecStartPre=/bin/sleep 0.3` and copied the file inside `/etc/systemd/system` which waits 300ms for the dm device to appear and seems to work.

**Comment by lourdas** [comment] 2019-11-08 15:26
Downgrading systemd to v.242 (Gentoo package 242-r7) and removing `systemd-cryptsetup@home.service` `from /etc/systemd/system/` works too, so this must be a v.243 regression.

**Comment by poettering** [comment] 2019-11-15 12:10
please provide logs of this. Otherwise this is not actionable. i.e. boot with "systemd.log_level=target=debug" on the kernel cmdline, and reproduce the issue, then attach the result here

**Comment by lourdas** [comment] 2019-11-15 14:32
Here's the debug log with systemd-243. This is not always reproducible, I had to reboot 5-6 times to recreate the problem.
[debug.txt.gz](https://github.com/systemd/systemd/files/3851902/debug.txt.gz)

**Comment by poettering** [comment] 2019-11-15 15:19
The logs show the device showed up before cryptsetup was started:

```
Νοε 15 16:21:14 helios systemd[1]: dev-md-sysresccd:HOME_ARRAY.device: Changed dead -> plugged
Νοε 15 16:21:14 helios systemd[1]: dev-md-sysresccd:HOME_ARRAY.device: Job 34 dev-md-sysresccd:HOME_ARRAY.device/start finished, result=done
Νοε 15 16:21:14 helios systemd[1]: Found device /dev/md/sysresccd:HOME_ARRAY.
```

And the cryptsetup logs also look like it can open the device, but the reads afterwards fail:

```
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Allocating context for crypt device /dev/md/sysresccd:HOME_ARRAY.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Trying to open and read device /dev/md/sysresccd:HOME_ARRAY with direct-io.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Trying to open device /dev/md/sysresccd:HOME_ARRAY without direct-io.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Initialising device-mapper backend library.
…
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: dm version   [ opencount flush ]   [16384] (*1)
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: dm versions   [ opencount flush ]   [16384] (*1)
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Detected dm-ioctl version 4.40.0.
…
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Detected dm-crypt version 1.19.0.
…
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Device-mapper backend running with UDEV support enabled.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: dm status home  [ opencount noflush ]   [16384] (*1)
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Trying to load any crypt type from device /dev/md/sysresccd:HOME_ARRAY.
…
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Crypto backend (gcrypt 1.8.5) initialized in cryptsetup library version 2.2.1.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Detected kernel Linux 5.3.11-gentoo x86_64.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Loading LUKS2 header (repair disabled).
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Acquiring read lock for device /dev/md/sysresccd:HOME_ARRAY.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: WARNING: Locking directory /run/cryptsetup is missing!
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Opening lock resource file /run/cryptsetup/L_9:127
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Verifying lock handle for /dev/md/sysresccd:HOME_ARRAY.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Device /dev/md/sysresccd:HOME_ARRAY READ lock taken.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Trying to read primary LUKS2 header at offset 0x0.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Opening locked device /dev/md/sysresccd:HOME_ARRAY
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Veryfing locked device handle (bdev)
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Trying to read secondary LUKS2 header at offset 0x4000.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Reusing open ro fd on device /dev/md/sysresccd:HOME_ARRAY
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Trying to read secondary LUKS2 header at offset 0x8000.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Reusing open ro fd on device /dev/md/sysresccd:HOME_ARRAY
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Trying to read secondary LUKS2 header at offset 0x10000.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Reusing open ro fd on device /dev/md/sysresccd:HOME_ARRAY
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Trying to read secondary LUKS2 header at offset 0x20000.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Reusing open ro fd on device /dev/md/sysresccd:HOME_ARRAY
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Trying to read secondary LUKS2 header at offset 0x40000.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Reusing open ro fd on device /dev/md/sysresccd:HOME_ARRAY
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Trying to read secondary LUKS2 header at offset 0x80000.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Reusing open ro fd on device /dev/md/sysresccd:HOME_ARRAY
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Trying to read secondary LUKS2 header at offset 0x100000.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Reusing open ro fd on device /dev/md/sysresccd:HOME_ARRAY
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Trying to read secondary LUKS2 header at offset 0x200000.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Reusing open ro fd on device /dev/md/sysresccd:HOME_ARRAY
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Trying to read secondary LUKS2 header at offset 0x400000.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Reusing open ro fd on device /dev/md/sysresccd:HOME_ARRAY
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: LUKS2 header read failed (-5).
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Device /dev/md/sysresccd:HOME_ARRAY READ lock released.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Failed to load LUKS superblock on device /dev/md/sysresccd:HOME_ARRAY: Input/output error
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Releasing crypt device /dev/md/sysresccd:HOME_ARRAY context.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Releasing device-mapper backend.
Νοε 15 16:21:14 helios systemd-cryptsetup[357]: Closing read only fd for /dev/md/sysresccd:HOME_ARRAY.
```

So it appears the device pops up, and can even be opened read-only, but then nothing read from it?

Either way, this looks like an raid problem hence, systemd synchronizes everything properly. Let's close this here hence. Please talk to the dmraid people... we generally don't know these storage packages here, you need to ping them for further help.

Closing.

**Closed as completed by poettering** 2019-11-15 15:19 UTC
Labels: pid1, needs-reporter-feedback ❓, cryptsetup

**Comment by lourdas** [comment] 2019-11-15 16:01
This issue started appearing in systemd v.243. Version 242 and previous than that worked fine. If I add a few hundreds milliseconds before systemd-cryptsetup runs, it works, as I described in my first comment.

**Comment by lourdas** [comment] 2019-11-15 16:27
I have attached the debug log for version 242.
[debug242.txt.gz](https://github.com/systemd/systemd/files/3852333/debug242.txt.gz)

**Comment by lourdas** [comment] 2019-11-15 16:36
A few things I noticed from comparing the events in the 2 log files:

Version 242 | Line in debug file | Version 243
--------------- | --------------------- | ---------------
line 2913 | Executing: /lib/systemd/systemd-cryptsetup attach home /dev/md/sysresccd:HOME_ARRAY none timeout=300 | line 1984
line 1894 | kernel: md127: detected capacity change from 0 to 139452219392 | line 2280

So, systemd-cryptsetup should run after the kernel finalizes detection of the raid1 (message `kernel: md127: detected capacity change from 0 to 139452219392`). From my point of view, this is the reason systemd-cryptsetup fails. Version 242 works fine, 243 sometimes fails.

**Comment by lourdas** [comment] 2019-11-16 11:34
@poettering Lennart, any comment on my previous remarks?

**Comment by arvidjaar** [comment] 2019-11-17 16:23
It does not look like problem is caused by systemd. In both logs the very first kernel message related to md127 is

```
Νοε 15 16:21:14 helios kernel: md/raid1:md127: active with 2 out of 2 mirrors
```

repsectively

```
Νοε 15 18:13:58 helios kernel: md/raid1:md127: active with 2 out of 2 mirrors
```

Kernel claims md127 is active so systemd is absolutely right to assume device is available and it can proceed. Different behavior may be result of some code restructuring so that now systemd is faster starting dependent units.

Kernel should not claim array is active if array cannot be accessed yet. You should really discuss it with kernel guys.
