### ISSUE TITLE
Auto-Restart mode not entered in cases with socket-activation + ExecStopPost enabled

### ISSUE THREAD

**Issue by tonobo** [systemd/systemd#20181] opened 2021-07-09 10:20 UTC
**systemd version the issue has been seen with**
```
 systemd 245 (245.4-4ubuntu3.7)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

AND

```
systemd 248 (248.3-2-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

**Used distribution**
```
Ubuntu 20.04.2 LTS
```

AND

```
Arch Linux
```

**Linux kernel version used** (`uname -a`)
```
Linux host 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

AND

```
Linux host 5.12.15-arch1-1 #1 SMP PREEMPT Wed, 07 Jul 2021 23:35:29 +0000 x86_64 GNU/Linux
```

**CPU architecture issue was seen on**
```
amd64
```

**Expected behaviour you didn't see**
Service should have entered auto-restart mode.

**Steps to reproduce the problem**
Create socket file:
```
# moo.socket
[Unit]
Description=Moo service
BindsTo=moo.service

[Socket]
ListenStream=/run/moo.sock
RemoveOnStop=yes
FileDescriptorName=moo.socket
```
Add related service:
```
[Unit]
Description=Moo Socket
After=moo.socket
BindsTo=moo.socket

[Service]
ExecStart=/bin/bash -c "sleep 3 && false"
#ExecStopPost=/bin/true

Restart=always
RestartSec=10
```

Start service, wait a bit -> `Active: activating (auto-restart)`
```
root@host /etc/systemd/system # systemctl start moo.service
root@host /etc/systemd/system # systemctl status moo.service --no-pager -l
● moo.service - Moo Service
     Loaded: loaded (/etc/systemd/system/moo.service; static; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Fri 2021-07-09 12:14:13 CEST; 1s ago
TriggeredBy: ● moo.socket
    Process: 1193599 ExecStart=/bin/bash -c sleep 3 && false (code=exited, status=1/FAILURE)
   Main PID: 1193599 (code=exited, status=1/FAILURE)
```

Uncomment the `ExecStopPost=` line:
```diff
9c9
< #ExecStopPost=/bin/true
---
> ExecStopPost=/bin/true
```

Reload daemon and restart service -> `Active: failed (Result: exit-code)`:
```
root@host /etc/systemd/system # systemctl restart moo
root@host /etc/systemd/system # systemctl status moo.service --no-pager -l
● moo.service - Moo Service
     Loaded: loaded (/etc/systemd/system/moo.service; static; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2021-07-09 12:15:51 CEST; 436ms ago
TriggeredBy: ● moo.socket
    Process: 1197572 ExecStart=/bin/bash -c sleep 3 && false (code=exited, status=1/FAILURE)
    Process: 1197675 ExecStopPost=/bin/true (code=exited, status=0/SUCCESS)
   Main PID: 1197572 (code=exited, status=1/FAILURE)

Jul 09 12:15:48 host systemd[1]: Started Moo Service.
Jul 09 12:15:51 host systemd[1]: moo.service: Main process exited, code=exited, status=1/FAILURE
Jul 09 12:15:51 host systemd[1]: moo.service: Failed with result 'exit-code'.
Jul 09 12:15:51 host systemd[1]: Stopped Moo Service.
```

**Comment by tonobo** [comment] 2021-11-01 09:32
howdy again, triggered similar behavior in combination with sd_notify and dependend socket units. Service won't enter restart mode, unit will end up in failed mode because for watchdog failure. By removing the socket unit relation it behaves as expected.

**Comment by dtardon** [comment] 2023-03-01 15:14
This seems to be a duplicate of #11456.

**Closed as not planned** 2023-03-01 15:14 UTC
Labels: bug 🐛, pid1, duplicate
