### ISSUE TITLE
Assertion failure in dns_query_complete()

### ISSUE THREAD

**Issue by jdz** [systemd/systemd#18231] opened 2021-01-13 12:29 UTC
**systemd version the issue has been seen with**
 > 247.2

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > Linux kuro 5.10.6-arch1-1 #1 SMP PREEMPT Sat, 09 Jan 2021 18:22:35 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > No coredumps.

**Unexpected behaviour you saw**
 > Coredump.

**Steps to reproduce the problem**
 > Have no clue.

Relevant messages from journal:

```
Jan 13 14:06:55.112194 kuro systemd-resolved[490]: Assertion 'DNS_TRANSACTION_IS_LIVE(q->state)' failed at src/resolve/resolved-dns-query.c:485, function dns_query_complete(). Aborting.
Jan 13 14:06:55.122317 kuro systemd[1]: Created slice system-systemd\x2dcoredump.slice.
Jan 13 14:06:55.123528 kuro systemd[1]: Started Process Core Dump (PID 9717/UID 0).
Jan 13 14:06:55.201253 kuro systemd-coredump[9718]: [🡕] Process 490 (systemd-resolve) of user 980 dumped core.

                                                    Stack trace of thread 490:
                                                    #0  0x00007fd5ad9d6615 raise (libc.so.6 + 0x3d615)
                                                    #1  0x00007fd5ad9bf862 abort (libc.so.6 + 0x26862)
                                                    #2  0x00007fd5ae1fa07f n/a (libsystemd-shared-247.so + 0x5607f)
                                                    #3  0x0000556778be961a n/a (systemd-resolved + 0x1361a)
                                                    #4  0x0000556778be972b n/a (systemd-resolved + 0x1372b)
                                                    #5  0x00007fd5ae3595e6 n/a (libsystemd-shared-247.so + 0x1b55e6)
                                                    #6  0x00007fd5ae35997b sd_event_dispatch (libsystemd-shared-247.so + 0x1b597b)
                                                    #7  0x00007fd5ae35ad31 sd_event_run (libsystemd-shared-247.so + 0x1b6d31)
                                                    #8  0x00007fd5ae35af70 sd_event_loop (libsystemd-shared-247.so + 0x1b6f70)
                                                    #9  0x0000556778c0e369 n/a (systemd-resolved + 0x38369)
                                                    #10 0x0000556778be1126 n/a (systemd-resolved + 0xb126)
                                                    #11 0x00007fd5ad9c1152 __libc_start_main (libc.so.6 + 0x28152)
                                                    #12 0x0000556778be11ce n/a (systemd-resolved + 0xb1ce)
Jan 13 14:06:55.202691 kuro systemd[1]: systemd-coredump@0-9717-0.service: Succeeded.
Jan 13 14:06:55.203531 kuro systemd[1]: systemd-resolved.service: Main process exited, code=dumped, status=6/ABRT
Jan 13 14:06:55.203593 kuro systemd[1]: systemd-resolved.service: Failed with result 'core-dump'.
```

Excerpt from `journalctl -o short-precise -u systemd-resolved.service`:

```
Jan 13 11:10:38.780890 kuro systemd[1]: Started Network Name Resolution.
Jan 13 14:05:02.947664 kuro systemd-resolved[490]: Using degraded feature set UDP instead of UDP+EDNS0 for DNS server 9.9.9.9.
Jan 13 14:05:12.951069 kuro systemd-resolved[490]: Using degraded feature set TCP instead of UDP for DNS server 9.9.9.9.
Jan 13 14:05:33.112299 kuro systemd-resolved[490]: Using degraded feature set UDP instead of TCP for DNS server 9.9.9.9.
Jan 13 14:06:55.112194 kuro systemd-resolved[490]: Assertion 'DNS_TRANSACTION_IS_LIVE(q->state)' failed at src/resolve/resolved-dns-query.c:485, function dns_query_complete(). Aborting.
Jan 13 14:06:55.203531 kuro systemd[1]: systemd-resolved.service: Main process exited, code=dumped, status=6/ABRT
Jan 13 14:06:55.203593 kuro systemd[1]: systemd-resolved.service: Failed with result 'core-dump'.
```

**Comment by yuwata** [comment] 2021-01-13 15:31
Duplicate of #18232.

**Closed as completed by yuwata** 2021-01-13 15:31 UTC
Labels: resolve, duplicate
