### ISSUE TITLE
"systemctl reboot" fails to send wall message

### ISSUE THREAD

**Issue by chowbok** [systemd/systemd#8424] opened 2018-03-11 15:10 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

237

### Used distribution

Arch Linux

### In case of bug report: Expected behaviour you didn't see

According to the documentation, "systemctl reboot" is supposed to send a wall message. I have never seen this behavior in any version of systemd. It doesn't send it to xterms, ssh terminals, or even to the console.

**Comment by chowbok** [comment] 2018-03-11 15:24
I should also add that "wall foo" sends a message, at least to console and ssh terminals.

**Comment by sourcejedi** [comment] 2018-03-11 21:42
It's not just you or your setup :).  I noticed it when looking at the code.  You only get wall messages with `shutdown`.

My suggestion would be to just fix the docs.  Historically I don't think `reboot` / `halt` on Linux sent wall messages.  http://git.savannah.nongnu.org/cgit/sysvinit.git/tree/src/halt.c?id=3f98f493ff9331bf41ddf5d734729f9d5a89d73a  And the old standby, no-one actually complained about it :).  Do you have an alternative suggestion or explanation why you'd find the documented behaviour useful?

AIUI `shutdown` is the thing that was standardized for shutting down a multi-user system after a delay, warning users in advance, stopping new users from logging in in the last five minutes etc.

**Comment by chowbok** [comment] 2018-03-12 14:59
I appreciate the response. Some thoughts in reply:

1. None of this really matters on a desktop, but it _is_ an issue on multi-user systems.
1. `reboot` in sysvinit will reboot the system immediately, but `shutdown -r` will reboot the system with a wall message, and therefore that's what a sysadmin will use on a system that others might be logged in to. There's no real equivalent to `shutdown -r` in systemd, if I'm not mistaken. That might actually be the initial source of this problem, come to think of it.
1. Most systems with multiple-users nowadays will be in business environments. If my experience is at all typical, businesses only just now are really starting to use RHEL 7. Most are still on RHEL 6, which is sysvinit. So I think the fact that you haven't gotten many complaints yet is just because it has yet to hit the systems that it's relevant to.
1. And it _is_ relevant. Users on a system need to know if they've been disconnected because the network just went out, because the system crashed, or because it was a planned shutdown, and they also need to know if it's just a reboot and they'll be able to log right back in, or if it's actually a shutdown and they'll have to wait a while. (Not to mention we've lost the ability to automatically send periodic reminders before shutdown so that they can save their work, but that's another bug.)
1. By the way, if you run `systemctl reboot` as a non-root user, it prompts for your password twice; the first time is for sending the wall message.
1. Finally, you don't even get wall messages in `shutdown`. ssh sessions are disconnected before the message even comes through. I guess you'd get the message on a console, but it's far more unusual that you'd be on console and someone else shuts the machine down from an SSH session than vice versa. (And besides, even on console the wall message would be drowned out by the systemd services stopping, although I imagine there's not really much that can be done about that).

So yes, I think this should actually be made to behave the way it says in the documentation rather than just dropping the relevant docs.

**Comment by sourcejedi** [comment] 2018-03-12 15:47
We provide `shutdown` including `shutdown -r`, complete with man page.  So that should work in the familiar unix way and be adequate for your concerns, no?  It's supposed to send periodic messages.  A user blogged some details including the timings of the messages [here](https://utcc.utoronto.ca/~cks/space/blog/linux/SystemdVersionOfShutdown) :).

I admit I made the assumption myself, that `shutdown` would be deprecated by systemd.  But it is not.  The true position is implicit in the exact text of various man pages.  I really hope no-one who needs the `shutdown` feature of scheduled shutdown, would be scared away by the really mild deprecation markings in _other_ man pages.

Given that we built out all this documentation in `systemctl reboot`, and it's also in the `reboot` compat, I expect you're right and the friendliest thing is to fix the behaviour of `systemctl reboot`.  I think we should also add a REFERENCES entry at the end of `man systemctl` to point to `shutdown`.  Thank you for your discussion.

> By the way, if you run systemctl reboot as a non-root user, it prompts for your password twice; the first time is for sending the wall message.

Well spotted.  IIRC the code sets the wall message in logind, but logind only does anything with the wall message for the API used by `shutdown`, not by `systemctl`.  It's a dumb bug, at least when we decide whether or not we're really sending wall messages, we can make the code consistent at the same time.  I don't know much about PolKit, whether there's an easy way to fix the double prompt.  It will still be relevant because `shutdown` should have the same issue.  I guess if we care enough we could make the bus API used by `shutdown` take both the message and the shutdown schedule in a single call.

I'm not sure what you're saying with point 6.  The wall message should be going out just before shutdown starts for real.  If our `shutdown` doesn't work how you want it to, maybe you can open a separate bug for that showing what you need and why we're not fulfilling it.

**Comment by chowbok** [comment] 2018-03-12 16:25
Ah. Okay, part if the issue here, at least for me, is that Arch puts the `shutdown` link in a package called "systemd-sysvcompat", which makes it sound like it's deprecated. I figured I should learn to get by without that since it would go away someday, but I guess it provides functionality that systemd by itself does not. So I guess as long that stays around, we're fine. (Seems strange to me to have functionality only available via a symlink, though.)

So I guess this is just a documentation bug, then. One other small thing I noticed, which might be worth pointing out, is that `shutdown` in sysvinit sends the wall message to all terminals including the invoking terminal, whereas systemd's `shutdown` only sends it to the other terminals. I think systemd's behavior actually makes more sense, but it may confuse people.

**Comment by sourcejedi** [comment] 2018-03-12 18:13
If you'd like to report a bug to Arch, that would be great.  (Perhaps pointing to this comment; that `shutdown -h +10` cannot be re-phrased using `systemctl` or any other command, `man shutdown` does *not* say "These are legacy commands available for compatibility only.", and `shutdown` is still provided when built without SYSV_COMPAT.)

Let us know if you have more detailed ideas about how our documentation could have dispelled this confusion :).

---

My opinion was the wall message should be changed to all terminals.  The sysvinit behaviour is simpler and I don't think the special case is justified.  Excluding the PTY the shutdown was scheduled from, doesn't work well if you log out that particular session and someone else grabs your PTY.

**Comment by poettering** [comment] 2018-03-20 17:03
I figure we should really generate the wall message in all cases, as long as it's a "clean" shutdown operation that is requested. Happy to take a patch that fixes this. 

Closing as duplicate of #3700.

Also see #5917.

**Closed as completed by poettering** 2018-03-20 17:03 UTC
Labels: systemctl, duplicate

**Comment by Swatigupta1997** [comment] 2020-07-10 05:40
Was this problem not fixed for reboots?

I am still not seeing the wall message when issuing `systemctl reboot`. According to the documentation, "systemctl reboot" is supposed to send a wall message. There is even a --no-wall option to suppress the broadcast message! But it is not coming at all.

root@abc:~# systemctl reboot
Connection to jdm closed by remote host.
Connection to jdm closed.

root@abc:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

root@abc:~# systemd --version
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
root@bng-ix-svr5-jdm:~#

**Comment by Swatigupta1997** [comment] 2020-07-10 05:44
Was this problem not fixed for reboots?

I am still not seeing the wall message when issuing systemctl reboot. According to the documentation, "systemctl reboot" is supposed to send a wall message (There is even a --no-wall option to suppress the broadcast message!). But the message is not coming at all.

root@abc:~# systemctl reboot
Connection to abc closed by remote host.
Connection to abc closed.

root@abc:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

root@abc:~# systemd --version
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Comment by khm** [comment] 2021-10-11 20:01
@sourcejedi For the record, we have not been complaining about this because we're still waiting for #3700 to be fixed.  Is there a preferred way to register interest in this bug?
