### ISSUE TITLE
Obnoxious error message due to `not-found` units during shell completion.

### ISSUE THREAD

**Issue by chaoren** [systemd/systemd#3972] opened 2016-08-16 18:33 UTC
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> systemd 231
> +PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux
### In case of bug report: Unexpected behaviour you saw

> Obnoxious error message due to `not-found` units during shell completion.
> See https://github.com/systemd/systemd/pull/3967#issuecomment-240187837 and https://github.com/systemd/systemd/issues/3856#issuecomment-236986927.
### In case of bug report: Steps to reproduce the problem

> ```
> systemctl start <TAB>
> Unit auditd.service could not be found.
> ```

**Comment by arvidjaar** [comment] 2016-08-16 20:31
Duplicate of #3856

**Comment by poettering** [comment] 2016-08-17 18:14
Closing as duplicate.

**Closed as completed by poettering** 2016-08-17 18:14 UTC
Labels: systemctl, duplicate
