### ISSUE TITLE
directories defined in systemd.pc are hardcoded

### ISSUE THREAD

**Issue by iainlane** [systemd/systemd#9595] opened 2018-07-16 09:39 UTC
**Is your feature request related to a problem? Please describe.**
On my Ubuntu bionic system with systemd 237, the directories defined in the .pc file are hardcoded to absolute locations, for example `systemduserunitdir=/usr/lib/systemd/user`.

This means that it's not possible to use these variables from consuming projects without potentially installing out of their prefix. In something like jhbuild this doesn't work.

**Describe the solution you'd like**
What [Emannuele Bassi posted on his blog a few months ago](https://www.bassi.io/articles/2018/03/15/pkg-config-and-paths/). The variables in the `.pc` file should be expressed relative to `${prefix}` (and `${rootprefix}`) rather than substituting it directly.

**Describe alternatives you've considered**
If you pick a different prefix to the one systemd was configured with then things probably won't be found anyway. Consumers could somehow detect this situation and not install the units. That's probably going to irritate some people though.

Otherwise, and this is probably what I'm going to propose we do downstream in the meantime, you can ignore where systemd is telling you to install to and install to `${prefix}/lib/systemd/user` or whatever directly.

**Comment by poettering** [comment] 2018-07-16 09:52
Hmm, not sure I follow. I mean, we don't really look in other dirs, and as documented in README we only support prefix=/usr for systemd...

**Comment by iainlane** [comment] 2018-07-16 10:00
Right, if you configure with a different prefix to the systemd installed on your system then it's your own problem, this is mainly to help the JHBuilders (& friends) of the world.

**Comment by poettering** [comment] 2018-07-16 10:36
ok, fair enough. send a PR, plz.

**Comment by filbranden** [comment] 2018-07-16 20:46
@iainlane Shouldn't this be handled by having JHBuilders and friends exporting PKG_CONFIG_SYSROOT_DIR instead?

```
$ PKG_CONFIG_SYSROOT_DIR=/home/laney/my-cool-project pkg-config --variable=systemduserunitdir systemd
/home/laney/my-cool-project/usr/lib/systemd/user
```

**Comment by poettering** [comment] 2018-11-17 00:12
Duplicate of #4549

**Closed as completed by poettering** 2018-11-17 00:12 UTC
Labels: RFE 🎁, needs-patch
