### ISSUE TITLE
systemd-boot default entry selection not working

### ISSUE THREAD

**Issue by lnicola** [systemd/systemd#15144] opened 2020-03-17 15:49 UTC
**systemd version the issue has been seen with**
> `245-3`

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > `default` setting is not respected

**Steps to reproduce the problem**

```
$ find /boot/loader
/boot/loader
/boot/loader/entries
/boot/loader/entries/arch-sd.conf
/boot/loader/entries/arch-fallback.conf
/boot/loader/entries/arch.conf
/boot/loader/entries/memtest86-efi.conf
/boot/loader/loader.conf
/boot/loader/random-seed

$ cat /boot/loader/loader.conf
timeout 0
default arch
#default arch-sd
```

Instead of the Arch entry, `systemd-boot` selects MemTest86 by default. I can pick Arch from the boot menu and it boots fine. This used to work before 245.

**Comment by anitazha** [comment] 2020-03-17 17:58
Duplicate of https://github.com/systemd/systemd/issues/15068

**Closed as completed by anitazha** 2020-03-17 17:58 UTC
Labels: duplicate
