### ISSUE TITLE
Restart of systemd-logind does not work

### ISSUE THREAD

**Issue by bitstreamout** [systemd/systemd#1716] opened 2015-10-29 14:20 UTC
after updating main libraries also used by systemd-logind the user is normally instructed to restart the affected processes and daemon.  This is currently not doable for systemd-logind. Otherwise e.g. X sessions will be terminated and other nasty side effects do happen!

IMHO a re-execute feature is missed for systemd-logind similar as available for systemd it self by using the command `systemctl daemon-rexec`

**Comment by mbiebl** [comment] 2015-10-29 22:07
This bug report is basically a duplicate of https://github.com/systemd/systemd/issues/1163

**Comment by mbiebl** [comment] 2015-10-29 22:08
Closing the bug report as duplicate

**Closed as completed by mbiebl** 2015-10-29 22:08 UTC
