### ISSUE TITLE
DHCPV6  client is not sending the mac address

### ISSUE THREAD

**Issue by ratagupt** [systemd/systemd#21442] opened 2021-11-19 09:47 UTC
In systemd-networkd we have an option clientIdentifier which can have value like "mac,duid,duid-only".
When  I set the clientIdentifier as mac, I was expecting that the dhcpv6 client should send the mac address to the DHCP server?

I understand that DHCPv6 client will send the mac address if I explicitly set the DUIDType to "link-layer" or "link-layer-time" but that should only be usable when somebody sets the  clientIdentifier as duid.

What is happening now if I set the clientIdentifier as mac , DHCPv6 client sends the DUIDType as vendor and it doesn't send the mac address of the interface in the solicit request, I am confused why the clientIdentifer=mac exist?

systemd 244 (244.3+) : I understand that I am using the older version of systemd but my query is what should I expect in the solicit request if I set the clientIdentifier as mac(wrt DHCPv6 )

My network conf is like below
===================
[Match]
Name=eth0
[Network]
DHCP=true
LinkLocalAddressing=yes
IPv6AcceptRA=true
[DHCP]
ClientIdentifier=mac

@yuwata @ssahani ???

**Comment by ratagupt** [comment] 2021-11-22 11:15
@yuwata @ssahani  any quick comments on this would be appreciable.

**Comment by yuwata** [comment] 2021-11-30 01:20
Duplicate of #21311?

Sorry, v244 is too old here. Please test with the recent release or the current git HEAD, or contact to your distro. Closing.

Feel free to request to reopen the issue, when you confirm that the recent release still has the issue.

**Closed as completed by yuwata** 2021-11-30 01:20 UTC
Labels: network, dhcp, duplicate, version-too-ancient
