### ISSUE TITLE
TEST-70-TPM2 is unstable

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#27716] opened 2023-05-20 06:03 UTC
### systemd version the issue has been seen with

HEAD

### CPU architectures issue was seen on

None

### Unexpected behaviour you saw

I thought it is unstable only on Ubuntu CI (ppc64el), but also failed on CentOS CI.
See https://jenkins-systemd.apps.ocp.cloud.ci.centos.org/job/upstream-vagrant-archlinux/2447/artifact/systemd-centos-ci/index.html

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[   70.942519] testsuite-70.sh[368]: + PASSWORD=
[   70.943226] testsuite-70.sh[368]: + NEWPIN=123456
[   70.943926] testsuite-70.sh[368]: + systemd-cryptenroll --tpm2-device=auto --tpm2-with-pin=true /tmp/cryptenroll.img
[   70.944707] testsuite-70.sh[4385]: Allocating context for crypt device /tmp/cryptenroll.img.
[   70.945255] testsuite-70.sh[4385]: Trying to open and read device /tmp/cryptenroll.img with direct-io.
[   70.945997] testsuite-70.sh[4385]: Trying to open device /tmp/cryptenroll.img without direct-io.
[   70.946643] testsuite-70.sh[4385]: Initialising device-mapper backend library.
[   70.947338] testsuite-70.sh[4385]: Trying to load LUKS2 crypt type from device /tmp/cryptenroll.img.
[   70.948004] testsuite-70.sh[4385]: Crypto backend (OpenSSL 3.0.8 7 Feb 2023 [default][legacy]) initialized in cryptsetup library version 2.6.1.
[   70.948716] testsuite-70.sh[4385]: Detected kernel Linux 6.3.2-arch1-1 x86_64.
[   70.949409] testsuite-70.sh[4385]: Loading LUKS2 header (repair disabled).
[   70.950110] testsuite-70.sh[4385]: Acquiring read lock for device /tmp/cryptenroll.img.
[   70.950790] testsuite-70.sh[4385]: Verifying lock handle for /tmp/cryptenroll.img.
[   70.951492] testsuite-70.sh[4385]: Device /tmp/cryptenroll.img READ lock taken.
[   70.952192] testsuite-70.sh[4385]: Trying to read primary LUKS2 header at offset 0x0.
[   70.952908] testsuite-70.sh[4385]: Opening locked device /tmp/cryptenroll.img
[   70.953613] testsuite-70.sh[4385]: Verifying locked device handle (regular file)
[   70.954276] testsuite-70.sh[4385]: LUKS2 header version 2 of size 16384 bytes, checksum sha256.
[   70.954988] testsuite-70.sh[4385]: Checksum:3aafd23639665a30ed3cc5fdea2408d340cbaa8ee925e1998f4e1ada590329bf (on-disk)
[   70.955677] testsuite-70.sh[4385]: Checksum:3aafd23639665a30ed3cc5fdea2408d340cbaa8ee925e1998f4e1ada590329bf (in-memory)
[   70.956385] testsuite-70.sh[4385]: Trying to read secondary LUKS2 header at offset 0x4000.
[   70.957086] testsuite-70.sh[4385]: Reusing open ro fd on device /tmp/cryptenroll.img
[   71.124556] testsuite-70.sh[4385]: LUKS2 header version 2 of size 16384 bytes, checksum sha256.
[   71.125132] testsuite-70.sh[4385]: Checksum:8b78b36104d268dff3bfc11448f21bdb31379c70a6c406bf3c6711b28a6d0913 (on-disk)
[   71.125835] testsuite-70.sh[4385]: Checksum:8b78b36104d268dff3bfc11448f21bdb31379c70a6c406bf3c6711b28a6d0913 (in-memory)
[   71.126507] testsuite-70.sh[4385]: Device size 20971520, offset 16777216.
[   71.127202] testsuite-70.sh[4385]: Device /tmp/cryptenroll.img READ lock released.
[   71.127863] testsuite-70.sh[4385]: Not enough physical memory detected, PBKDF max memory decreased from 1048576kB to 362658kB.
[   71.128598] testsuite-70.sh[4385]: PBKDF argon2id, time_ms 2000 (iterations 0), max_memory_kb 362658, parallel_threads 4.
[   71.129330] testsuite-70.sh[4385]: Requesting JSON for token 0.
[   71.129971] testsuite-70.sh[4385]: Requesting JSON for token 1.
[   71.130672] testsuite-70.sh[4385]: Requesting JSON for token 2.
[   71.131335] testsuite-70.sh[4385]: Requesting JSON for token 3.
[   71.132047] testsuite-70.sh[4385]: Requesting JSON for token 4.
[   71.132767] testsuite-70.sh[4385]: Requesting JSON for token 5.
[   71.133459] testsuite-70.sh[4385]: Requesting JSON for token 6.
[   71.134136] testsuite-70.sh[4385]: Requesting JSON for token 7.
[   71.134797] testsuite-70.sh[4385]: Requesting JSON for token 8.
[   71.135519] testsuite-70.sh[4385]: Requesting JSON for token 9.
[   71.136222] testsuite-70.sh[4385]: Requesting JSON for token 10.
[   71.136915] testsuite-70.sh[4385]: Requesting JSON for token 11.
[   71.137571] testsuite-70.sh[4385]: Requesting JSON for token 12.
[   71.138274] testsuite-70.sh[4385]: Requesting JSON for token 13.
[   71.138947] testsuite-70.sh[4385]: Requesting JSON for token 14.
[   71.139747] testsuite-70.sh[4385]: Requesting JSON for token 15.
[   71.140356] testsuite-70.sh[4385]: Requesting JSON for token 16.
[   71.141022] testsuite-70.sh[4385]: Requesting JSON for token 17.
[   71.141712] testsuite-70.sh[4385]: Requesting JSON for token 18.
[   71.142388] testsuite-70.sh[4385]: Requesting JSON for token 19.
[   71.143108] testsuite-70.sh[4385]: Requesting JSON for token 20.
[   71.144507] testsuite-70.sh[4385]: Requesting JSON for token 21.
[   71.145186] testsuite-70.sh[4385]: Requesting JSON for token 22.
[   71.145865] testsuite-70.sh[4385]: Requesting JSON for token 23.
[   71.146560] testsuite-70.sh[4385]: Requesting JSON for token 24.
[   71.147925] testsuite-70.sh[4385]: Requesting JSON for token 25.
[   71.148644] testsuite-70.sh[4385]: Requesting JSON for token 26.
[   71.149992] testsuite-70.sh[4385]: Requesting JSON for token 27.
[   71.150658] testsuite-70.sh[4385]: Requesting JSON for token 28.
[   71.151350] testsuite-70.sh[4385]: Requesting JSON for token 29.
[   71.152073] testsuite-70.sh[4385]: Requesting JSON for token 30.
[   71.152780] testsuite-70.sh[4385]: Requesting JSON for token 31.
[   71.154132] testsuite-70.sh[4385]: Keyslot 0 priority 1 != 2 (required), skipped.
[   71.154828] testsuite-70.sh[4385]: Keyslot 1 priority 1 != 2 (required), skipped.
[   71.155517] testsuite-70.sh[4385]: Keyslot 2 priority 1 != 2 (required), skipped.
[   71.156224] testsuite-70.sh[4385]: Keyslot 3 priority 1 != 2 (required), skipped.
[   71.156918] testsuite-70.sh[4385]: Keyslot 4 priority 1 != 2 (required), skipped.
[   71.157584] testsuite-70.sh[4385]: Keyslot 5 priority 1 != 2 (required), skipped.
[   71.158272] testsuite-70.sh[4385]: Keyslot 6 priority 1 != 2 (required), skipped.
[   71.158980] testsuite-70.sh[4385]: Keyslot 7 priority 1 != 2 (required), skipped.
[   71.159705] testsuite-70.sh[4385]: Keyslot 8 priority 1 != 2 (required), skipped.
[   71.160398] testsuite-70.sh[4385]: Keyslot 9 priority 1 != 2 (required), skipped.
[   71.161085] testsuite-70.sh[4385]: Keyslot 10 priority 1 != 2 (required), skipped.
[   71.161760] testsuite-70.sh[4385]: Keyslot 11 priority 1 != 2 (required), skipped.
[   71.162436] testsuite-70.sh[4385]: Keyslot 12 priority 1 != 2 (required), skipped.
[   71.163160] testsuite-70.sh[4385]: Keyslot 13 priority 1 != 2 (required), skipped.
[   71.163866] testsuite-70.sh[4385]: Trying to open LUKS2 keyslot 0.
[   71.164529] testsuite-70.sh[4385]: Running keyslot key derivation.
[   71.165236] testsuite-70.sh[4385]: Reading keyslot area [0x8000].
[   71.165979] testsuite-70.sh[4385]: Acquiring read lock for device /tmp/cryptenroll.img.
[   71.166646] testsuite-70.sh[4385]: Verifying lock handle for /tmp/cryptenroll.img.
[   71.167343] testsuite-70.sh[4385]: Device /tmp/cryptenroll.img READ lock taken.
[   71.168007] testsuite-70.sh[4385]: Reusing open ro fd on device /tmp/cryptenroll.img
[   71.168691] testsuite-70.sh[4385]: Device /tmp/cryptenroll.img READ lock released.
[   71.169413] testsuite-70.sh[4385]: Verifying key from keyslot 0, digest 0.
[   71.339118] testsuite-70.sh[4385]: Digest 0 (pbkdf2) verify failed with -1.
[   71.339767] testsuite-70.sh[4385]: Trying to open LUKS2 keyslot 1.
[   71.340487] testsuite-70.sh[4385]: Running keyslot key derivation.
[   71.341163] testsuite-70.sh[4385]: Reading keyslot area [0x47000].
[   71.341885] testsuite-70.sh[4385]: Acquiring read lock for device /tmp/cryptenroll.img.
[   71.343297] testsuite-70.sh[4385]: Verifying lock handle for /tmp/cryptenroll.img.
[   71.344711] testsuite-70.sh[4385]: Device /tmp/cryptenroll.img READ lock taken.
[   71.345394] testsuite-70.sh[4385]: Reusing open ro fd on device /tmp/cryptenroll.img
[   71.346119] testsuite-70.sh[4385]: Device /tmp/cryptenroll.img READ lock released.
[   71.346826] testsuite-70.sh[4385]: Verifying key from keyslot 1, digest 0.
[   71.347517] testsuite-70.sh[4385]: Digest 0 (pbkdf2) verify failed with -1.
[   71.348199] testsuite-70.sh[4385]: Trying to open LUKS2 keyslot 2.
[   71.349034] testsuite-70.sh[4385]: Running keyslot key derivation.
[   71.349606] testsuite-70.sh[4385]: Reading keyslot area [0x86000].
[   71.350307] testsuite-70.sh[4385]: Acquiring read lock for device /tmp/cryptenroll.img.
[   71.350981] testsuite-70.sh[4385]: Verifying lock handle for /tmp/cryptenroll.img.
[   71.351711] testsuite-70.sh[4385]: Device /tmp/cryptenroll.img READ lock taken.
[   71.352370] testsuite-70.sh[4385]: Reusing open ro fd on device /tmp/cryptenroll.img
[   71.353106] testsuite-70.sh[4385]: Device /tmp/cryptenroll.img READ lock released.
[   71.353828] testsuite-70.sh[4385]: Verifying key from keyslot 2, digest 0.
[   71.354529] testsuite-70.sh[4385]: Failed to find TPM PCR public key file 'tpm2-pcr-public-key.pem': No such file or directory
[   71.355256] testsuite-70.sh[4385]: Failed to read TPM2 PCR public key, proceeding without: No such file or directory
[   71.355983] testsuite-70.sh[4385]: Using TPM2 TCTI driver 'device' with device '/dev/tpmrm0'.
[   71.356648] testsuite-70.sh[4385]: Loaded TCTI module 'tcti-device' (TCTI module for communication with Linux kernel interface.) [Version 2]
[   71.358001] testsuite-70.sh[4385]: TPM successfully started up.
[   71.358752] testsuite-70.sh[4385]: Reading PCR selection: [sha1(7)]
[   71.359436] testsuite-70.sh[4385]: [sha1(7)]: 3a3f780f11a4b49969fcaa80cd6e3957c33b2275
[   71.360140] testsuite-70.sh[4385]: Reading PCR selection: [sha256(7)]
[   71.360888] testsuite-70.sh[4385]: [sha256(7)]: a58606a00cf970a353d116d6efeec33b2bd076641f3bda7c39a7483041b53601
[   71.360921] testsuite-70.sh[4385]: TPM2 device supports SHA256 PCR bank and SHA256 PCRs are valid, yay!
[   71.361736] testsuite-70.sh[4385]: Creating SRK on TPM.
[   71.362826] testsuite-70.sh[4385]: Found SRK on TPM.
[   71.363701] testsuite-70.sh[4385]: Discovered existing SRK
[   71.364742] testsuite-70.sh[4385]: Starting HMAC encryption session.
[   71.365795] testsuite-70.sh[4385]: Starting policy session.
[   71.367592] testsuite-70.sh[4385]: Building sealing policy.
[   71.368308] testsuite-70.sh[4385]: Reading PCR selection: [sha256(7)]
[   71.369018] testsuite-70.sh[4385]: [sha256(7)]: a58606a00cf970a353d116d6efeec33b2bd076641f3bda7c39a7483041b53601
[   71.369799] testsuite-70.sh[4385]: Configuring hash-based PCR policy.
[   71.371165] testsuite-70.sh[4385]: Configuring PIN policy.
[   71.371873] testsuite-70.sh[4385]: Acquiring policy digest.
[   71.372568] testsuite-70.sh[4385]: Session policy digest: 289ebcf9cbc08ed0f28af3aa4c2e96cdd493b389c2644d9fec76649ee7a0f063
[   71.373368] testsuite-70.sh[4385]: Not adding TPM2 entropy to the kernel random pool again.
[   71.374032] testsuite-70.sh[4385]: Generating secret key data.
[   71.374698] testsuite-70.sh[4385]: Creating HMAC key.
[   71.375416] testsuite-70.sh[4385]: Marshalling private and public part of HMAC key.
[   71.376189] testsuite-70.sh[4385]: Serializing SRK ESYS_TR reference
[   71.376903] testsuite-70.sh[4385]: Completed TPM2 key sealing in 600.168ms.
[   71.377559] testsuite-70.sh[4385]: WARNING:esys:src/tss2-esys/api/Esys_FlushContext.c:234:Esys_FlushContext_Finish() Received TPM Error
[   71.378271] testsuite-70.sh[4385]: ERROR:esys:src/tss2-esys/api/Esys_FlushContext.c:89:Esys_FlushContext() Esys Finish ErrorCode (0x000001c4)
[   71.378945] testsuite-70.sh[4385]: Failed to flush TPM handle, ignoring: tpm:parameter(1):value is out of range or is not correct for the context
[   71.379732] testsuite-70.sh[4385]: Requesting JSON for token 0.
[   71.380423] testsuite-70.sh[4385]: Requesting JSON for token 1.
[   71.381088] testsuite-70.sh[4385]: Requesting JSON for token 2.
[   71.381837] testsuite-70.sh[4385]: Requesting JSON for token 3.
[   71.382466] testsuite-70.sh[4385]: Requesting JSON for token 4.
[   71.553242] testsuite-70.sh[4385]: Requesting JSON for token 5.
[   71.554518] testsuite-70.sh[4385]: Requesting JSON for token 6.
[   71.555208] testsuite-70.sh[4385]: Requesting JSON for token 7.
[   71.556013] testsuite-70.sh[4385]: Requesting JSON for token 8.
[   71.556648] testsuite-70.sh[4385]: Requesting JSON for token 9.
[   71.557359] testsuite-70.sh[4385]: Requesting JSON for token 10.
[   71.558047] testsuite-70.sh[4385]: Requesting JSON for token 11.
[   71.558779] testsuite-70.sh[4385]: Requesting JSON for token 12.
[   71.559487] testsuite-70.sh[4385]: Requesting JSON for token 13.
[   71.560194] testsuite-70.sh[4385]: Requesting JSON for token 14.
[   71.561048] testsuite-70.sh[4385]: Requesting JSON for token 15.
[   71.561633] testsuite-70.sh[4385]: Requesting JSON for token 16.
[   71.562435] testsuite-70.sh[4385]: Requesting JSON for token 17.
[   71.563191] testsuite-70.sh[4385]: Requesting JSON for token 18.
[   71.563932] testsuite-70.sh[4385]: Requesting JSON for token 19.
[   71.564668] testsuite-70.sh[4385]: Requesting JSON for token 20.
[   71.565374] testsuite-70.sh[4385]: Requesting JSON for token 21.
[   71.566073] testsuite-70.sh[4385]: Requesting JSON for token 22.
[   71.567453] testsuite-70.sh[4385]: Requesting JSON for token 23.
[   71.568197] testsuite-70.sh[4385]: Requesting JSON for token 24.
[   71.568862] testsuite-70.sh[4385]: Requesting JSON for token 25.
[   71.569562] testsuite-70.sh[4385]: Requesting JSON for token 26.
[   71.570276] testsuite-70.sh[4385]: Requesting JSON for token 27.
[   71.570960] testsuite-70.sh[4385]: Requesting JSON for token 28.
[   71.571680] testsuite-70.sh[4385]: Requesting JSON for token 29.
[   71.572361] testsuite-70.sh[4385]: Requesting JSON for token 30.
[   71.573076] testsuite-70.sh[4385]: Requesting JSON for token 31.
[   71.573783] testsuite-70.sh[4385]: PCR policy hash not yet enrolled, enrolling now.
[   71.574480] testsuite-70.sh[4385]: Unsealing for verification...
[   71.575162] testsuite-70.sh[4385]: Unmarshalling private part of HMAC key.
[   71.575890] testsuite-70.sh[4385]: Unmarshalling public part of HMAC key.
[   71.576593] testsuite-70.sh[4385]: Using TPM2 TCTI driver 'device' with device '/dev/tpmrm0'.
[   71.577302] testsuite-70.sh[4385]: Loaded TCTI module 'tcti-device' (TCTI module for communication with Linux kernel interface.) [Version 2]
[   71.577987] testsuite-70.sh[4385]: TPM successfully started up.
[   71.578668] testsuite-70.sh[4385]: Found existing SRK key to use, deserializing ESYS_TR
[   71.579413] testsuite-70.sh[4385]: Loading HMAC key into TPM.
[   71.580120] testsuite-70.sh[4385]: Starting HMAC encryption session.
[   71.580784] testsuite-70.sh[4385]: Starting policy session.
[   71.581486] testsuite-70.sh[4385]: WARNING:esys:src/tss2-esys/api/Esys_StartAuthSession.c:391:Esys_StartAuthSession_Finish() Received TPM Error
[   71.582210] testsuite-70.sh[4385]: ERROR:esys:src/tss2-esys/api/Esys_StartAuthSession.c:136:Esys_StartAuthSession() Esys Finish ErrorCode (0x0000098e)
[   71.582959] testsuite-70.sh[4385]: Failed to open session in TPM: tpm:session(1):the authorization HMAC check failed and DA counter incremented
[   71.583675] testsuite-70.sh[4385]: Releasing crypt device /tmp/cryptenroll.img context.
[   71.584347] testsuite-70.sh[4385]: Releasing device-mapper backend.
[   71.585060] testsuite-70.sh[4385]: Closing read only fd for /tmp/cryptenroll.img.
```

**Comment by ddstreet** [comment] 2023-05-22 16:01
I'm pretty sure the new SRK generation code is wrong, as when it needs to create a SRK, it still returns the transient handle instead of the persistent SRK handle, so unsealing will be trying to use the transient handle. Not really sure if that's what is causing the failure here though. This is (incidentially) fixed by replacing tpm2_make_primary() in #27713

**Comment by ddstreet** [comment] 2023-06-27 11:35
I think this is only happening on ppc64el.

**Comment by bluca** [comment] 2023-06-27 11:40
Yes we've never seen it on another architecture (however note that the test only runs on amd64 and ppc64el on Ubuntu, s390x and arm64 only run container-based tests)

**Comment by bluca** [comment] 2023-07-07 09:12
@ddstreet we are also seeing occasional issues on x86_64:

```
08:24:32 [   11.958254] testsuite-70.sh[408]: PCR policy hash not yet enrolled, enrolling now.
08:24:32 [   11.959136] testsuite-70.sh[408]: Unsealing for verification...
08:24:32 [   11.960070] testsuite-70.sh[408]: Unmarshalling private part of HMAC key.
08:24:32 [   11.960927] testsuite-70.sh[408]: Unmarshalling public part of HMAC key.
08:24:32 [   11.961821] testsuite-70.sh[408]: Using TPM2 TCTI driver 'device' with device '/dev/tpmrm0'.
08:24:32 [   11.962718] testsuite-70.sh[408]: Loaded TCTI module 'tcti-device' (TCTI module for communication with Linux kernel interface.) [Version 2]
08:24:32 [   11.964469] testsuite-70.sh[408]: TPM successfully started up.
08:24:32 [   11.965347] testsuite-70.sh[408]: Getting TPM2 capability 0x0000 property 0x0001 count 127.
08:24:32 [   11.965379] testsuite-70.sh[408]: Getting TPM2 capability 0x0002 property 0x011f count 256.
08:24:32 [   11.966272] testsuite-70.sh[408]: Getting TPM2 capability 0x0005 property 0x0000 count 1.
08:24:32 [   11.967421] testsuite-70.sh[408]: Found existing SRK key to use, deserializing ESYS_TR
08:24:32 [   11.968299] testsuite-70.sh[408]: Loading HMAC key into TPM.
08:24:32 [   11.969185] testsuite-70.sh[408]: Loading object into TPM.
08:24:32 [   11.971017] testsuite-70.sh[408]: Starting HMAC encryption session.
08:24:32 [   11.971888] testsuite-70.sh[408]: Starting policy session.
08:24:32 [   11.972821] testsuite-70.sh[408]: WARNING:esys:src/tss2-esys/api/Esys_StartAuthSession.c:391:Esys_StartAuthSession_Finish() Received TPM Error
08:24:32 [   11.973848] testsuite-70.sh[408]: ERROR:esys:src/tss2-esys/api/Esys_StartAuthSession.c:136:Esys_StartAuthSession() Esys Finish ErrorCode (0x0000098e)
08:24:32 [   11.974613] testsuite-70.sh[408]: Failed to open session in TPM: tpm:session(1):the authorization HMAC check failed and DA counter incremented
08:24:32 [   11.975504] testsuite-70.sh[408]: Releasing crypt device /tmp/test.img context.
08:24:32 [   11.976402] testsuite-70.sh[408]: Releasing device-mapper backend.
08:24:32 [   11.977303] testsuite-70.sh[408]: Closing read only fd for /tmp/test.img.
```

Could you please look into this? We are preparing the release and we should have these things sorted out before it can go out of the door - thanks

**Comment by bluca** [comment] 2023-07-07 09:13
e.g.: https://jenkins-systemd.apps.ocp.cloud.ci.centos.org/job/upstream-vagrant-archlinux/3928/console

**Comment by bluca** [comment] 2023-07-14 16:44
@ddstreet any luck with this one?

**Comment by ddstreet** [comment] 2023-07-15 12:17
This is an interesting one, caused by the addition of the pin salting (but the pin salting isn't doing anything wrong).

The pin value is always hashed before passing it to the tpm, so from the perspective of our code (and tpm2-tss) it's always been a 32-byte value of data, and our code has never done anything special with it. However, the tpm spec allows for the pin to be a "...password or passphrase..." as long as it's <= the hash digest size, but - critically - the spec states "Trailing octets of zero are to be removed from any string before it is used as an authValue." Unfortunately, there is no good way to tell if something is a "string" or "hash", so this requirement to remove trailing 0's means that any hash digest that happens to end in "0" needs special handling in our code (or, in tpm2-tss), because the tpm is going to remove that trailing 0 before using it.

The reason this is happening now is because before the pin salting was added, the "pin" that we hashed was always the plain string (in our test's case, 123456) so the resulting digest was always the same, and happened to not end in 0. When the pin salting was added, it introduced a random number (the salt) which resulted in our hash of the salted pin always being random, so there is roughly a 1/256 chance for our hash to end in 0, which causes the problem.

This should be easily fixable by adding a special function to generate the pin hash that also checks the last byte to make sure it's not 0.

**Comment by bluca** [comment] 2023-07-15 12:20
now that I picked up my jaw from the floor, any idea why this only affects ppc64 on ubuntu and nowhere else?

**Comment by ddstreet** [comment] 2023-07-15 12:38
> now that I picked up my jaw from the floor, any idea why this only affects ppc64 on ubuntu and nowhere else?

well we do see this on x64 too, as you noted in an earlier comment; but it did seem like this was much more common on ppc64. i'm not sure why that would be. it's possible the ppc64 failure is something different; I seem to remember those ppc64 failures complaining about being unable to unlock the luks drive using a password (not the tpm).

**Comment by ddstreet** [comment] 2023-07-15 12:47
Re: ppc64 failures, I do think that's something different, for example here: https://autopkgtest.ubuntu.com/results/autopkgtest-jammy-upstream-systemd-ci-systemd-ci/jammy/ppc64el/s/systemd-upstream/20230715_031818_58648@/log.gz

The failure is 

> 10737s [  142.389922] testsuite-70.sh[1662]: Password from environment variable $PASSWORD did not work: Operation not permitted

so that seems unrelated to the tpm.

**Comment by ddstreet** [comment] 2023-07-15 12:48
I marked #28414 as fixing this, but maybe we should open a separate issue for this test's failure specifically on ppc64el?

**Comment by bluca** [comment] 2023-07-15 13:04
we can just reopen this, no need to duplicate all the info

**Comment by ddstreet** [comment] 2023-07-17 16:34
For the failure on ppc64el systems, I'm able to reproduce this using only the 'cryptsetup' command, with no systemd code involved, so this is definitely a problem in libcryptsetup (or lower). This is the loop I used:

```
#!/bin/bash

if test -z $1; then
    echo "Usage: $0 <testimg> [size]"
    exit 1
fi

IMG=$1
SIZE=$2
test -z $SIZE && SIZE=20M

PW=/tmp/password.$$
FOO=/tmp/foo.$$
BAR=/tmp/bar.$$
echo password > $PW
echo foo > $FOO
echo bar > $BAR

set -ex

while true; do
    rm -rf $IMG
    truncate -s $SIZE $IMG
    cat $PW
    cryptsetup --verbose luksFormat -q $IMG $PW
    cat $PW
    cat $FOO
    cryptsetup --verbose luksAddKey $IMG --key-file $PW $FOO
    cat $FOO
    cat $BAR
    cryptsetup --verbose luksAddKey $IMG --key-file $FOO $BAR
done

```

it's quite easy to reproduce:

```
$ ./run-test.sh test1.img
+ true
+ rm -rf test1.img
+ truncate -s 20M test1.img
+ cat /tmp/password.869194
password
+ cryptsetup --verbose luksFormat -q test1.img /tmp/password.869194
Key slot 0 created.
Command successful.
+ cat /tmp/password.869194
password
+ cat /tmp/foo.869194
foo
+ cryptsetup --verbose luksAddKey test1.img --key-file /tmp/password.869194 /tmp/foo.869194
Key slot 1 created.
Command successful.
+ cat /tmp/foo.869194
foo
+ cat /tmp/bar.869194
bar
+ cryptsetup --verbose luksAddKey test1.img --key-file /tmp/foo.869194 /tmp/bar.869194
No key available with this passphrase.
Command failed with code -2 (no permission or bad passphrase).

```

though sometimes it goes longer before failing:

```
$ ./run-test.sh test3.img                                           
+ true                                
+ rm -rf test3.img                                                                             
+ truncate -s 20M test3.img
+ cryptsetup --verbose luksFormat -q test3.img /tmp/password.860441                            
Key slot 0 created.
Command successful.
+ cryptsetup --verbose luksAddKey test3.img --key-file /tmp/password.860441 /tmp/foo.860441    
Key slot 1 created.
Command successful.
+ cryptsetup --verbose luksAddKey test3.img --key-file /tmp/foo.860441 /tmp/bar.860441         
Key slot 2 created.
Command successful.
+ true             
+ rm -rf test3.img                    
+ truncate -s 20M test3.img                                                                    
+ cryptsetup --verbose luksFormat -q test3.img /tmp/password.860441                                                                                                                           
Key slot 0 created.                                                                                                                                                                           
Command successful.
+ cryptsetup --verbose luksAddKey test3.img --key-file /tmp/password.860441 /tmp/foo.860441    
Key slot 1 created.
Command successful.
+ cryptsetup --verbose luksAddKey test3.img --key-file /tmp/foo.860441 /tmp/bar.860441         
Key slot 2 created.
Command successful.
+ true             
+ rm -rf test3.img 
+ truncate -s 20M test3.img           
+ cryptsetup --verbose luksFormat -q test3.img /tmp/password.860441
Key slot 0 created.                      
Command successful.
+ cryptsetup --verbose luksAddKey test3.img --key-file /tmp/password.860441 /tmp/foo.860441    
Key slot 1 created.
Command successful.                  
+ cryptsetup --verbose luksAddKey test3.img --key-file /tmp/foo.860441 /tmp/bar.860441         
Key slot 2 created.
Command successful.                            
+ true
+ rm -rf test3.img
+ truncate -s 20M test3.img
+ cryptsetup --verbose luksFormat -q test3.img /tmp/password.860441                            
Key slot 0 created.          
Command successful.
+ cryptsetup --verbose luksAddKey test3.img --key-file /tmp/password.860441 /tmp/foo.860441    
Key slot 1 created.                            
Command successful.
+ cryptsetup --verbose luksAddKey test3.img --key-file /tmp/foo.860441 /tmp/bar.860441         
Key slot 2 created.
Command successful.
+ true                    
+ rm -rf test3.img                                                                             
+ truncate -s 20M test3.img                                                                    
+ cryptsetup --verbose luksFormat -q test3.img /tmp/password.860441  
Key slot 0 created.
Command successful.                        
+ cryptsetup --verbose luksAddKey test3.img --key-file /tmp/password.860441 /tmp/foo.860441
No key available with this passphrase.
Command failed with code -2 (no permission or bad passphrase).                                 

```

**Comment by bluca** [comment] 2023-07-17 16:36
Thanks - the issue here is that this used to work in v253, it's a new regression, so something must have changed on our side that trigger this bug?

**Comment by ddstreet** [comment] 2023-07-17 16:44
> Thanks - the issue here is that this used to work in v253, it's a new regression, so something must have changed on our side that trigger this bug?

@mrc0mmand updated TEST-70 in commit a9fe7f66e8c (and b0582f6b635) to add the part that is actually failing, specifically the part that uses the 'foo' password. Before that, TEST-70 wasn't actually testing if an enrolled password could be used (besides the initial password used during luks creation). I think that's why this issue wasn't seen in v253 or earlier.

**Comment by keszybz** [comment] 2023-07-17 17:14
Let's keep this open, but we shouldn't block the release, since it seems that it's not caused by us.

**Comment by bluca** [comment] 2023-07-17 17:17
I plan to send a fix that will simply skip the check on ppc64el, that should be in the release or it will trip testers

**Comment by keszybz** [comment] 2023-07-17 17:21
I'm running the reproducer on amd64 (VM on my laptop, Fedora 38) and ppc64el (VM with Fedora 37) and in both cases the issue doesn't trigger. (I'll let it run for a bit, but it's been 10 minutes already.)

**Closed as completed** 2023-07-17 21:47 UTC
Labels: bug 🐛, tests, not-our-bug, tpm2

**Comment by ddstreet** [comment] 2023-07-18 15:29
> I'm running the reproducer on amd64 (VM on my laptop, Fedora 38) and ppc64el (VM with Fedora 37) and in both cases the issue doesn't trigger. (I'll let it run for a bit, but it's been 10 minutes already.)

I'm seeing the same results, no failure on Fedora. I also tested on Debian and there's no failure there either. I tested Ubuntu versions Jammy and Lunar, and both fail, so this seems to be specific to only Ubuntu. I opened this Ubuntu bug:
https://bugs.launchpad.net/ubuntu/+source/cryptsetup/+bug/2028072
