### ISSUE TITLE
nspawn: machine leak with --keep-unit, RemainAfterExit and systemctl kill

### ISSUE THREAD

**Issue by iaguis** [systemd/systemd#2770] opened 2016-02-29 17:27 UTC
### Submission type
- [x] Bug report
### systemd version the issue has been seen with

229
### Used distribution

Arch Linux
### In case of bug report: Expected behaviour you didn't see

If I start a service that runs a container with `systemd-nspawn --keep-unit` and `RemainAfterExit=true`,  the machine gets deregistered after killing the service with `systemctl kill`.
### In case of bug report: Unexpected behaviour you saw

If I run `machinectl` I can still see the machine even though all the processes are gone.
### In case of bug report: Steps to reproduce the problem

Create a service file like this one:

```
# /run/systemd/system/test-machine-leak.service
[Service]
RemainAfterExit=true
ExecStart=/usr/bin/systemd-nspawn --keep-unit -bD /home/iaguis/distro-trees/arch
KillMode=mixed
```

Start it, kill it, and check that the machine is still present:

```
$ sudo systemctl start test-machine-leak
$ machinectl
MACHINE CLASS     SERVICE       
arch    container systemd-nspawn

1 machines listed.
$ sudo systemctl kill test-machine-leak
$ echo $?
0
$ machinectl
MACHINE CLASS     SERVICE       
arch    container systemd-nspawn

1 machines listed.
$ sudo systemctl status test-machine-leak
● test-machine-leak.service
   Loaded: loaded (/run/systemd/system/test-machine-leak.service; static; vendor preset: disabled)
   Active: active (exited) since Mon 2016-02-29 18:14:04 CET; 1min 54s ago
  Process: 5752 ExecStart=/usr/bin/systemd-nspawn --keep-unit -bD /home/iaguis/distro-trees/arch (code=exited, sta
 Main PID: 5752 (code=exited, status=0/SUCCESS)

Feb 29 18:14:42 locke-xps13 systemd-nspawn[5752]:          Starting Flush Journal to Persistent Storage...
Feb 29 18:14:42 locke-xps13 systemd-nspawn[5752]: [  OK  ] Started Flush Journal to Persistent Storage.
Feb 29 18:14:42 locke-xps13 systemd-nspawn[5752]: [  OK  ] Unmounted Temporary Directory.
Feb 29 18:14:42 locke-xps13 systemd-nspawn[5752]: [  OK  ] Reached target Unmount All Filesystems.
Feb 29 18:14:42 locke-xps13 systemd-nspawn[5752]: [  OK  ] Started Generate shutdown-ramfs.
Feb 29 18:14:42 locke-xps13 systemd-nspawn[5752]: [  OK  ] Reached target Shutdown.
Feb 29 18:14:42 locke-xps13 systemd-nspawn[5752]: Sending SIGTERM to remaining processes...
Feb 29 18:14:42 locke-xps13 systemd-nspawn[5752]: Sending SIGKILL to remaining processes...
Feb 29 18:14:42 locke-xps13 systemd-nspawn[5752]: Halting system.
Feb 29 18:14:42 locke-xps13 systemd-nspawn[5752]: Container arch has been shut down.
```

Try with `stop` and see that it deregisters correctly:

```
$ sudo systemctl stop test-machine-leak
$ machinectl 
MACHINE CLASS SERVICE

0 machines listed.
```

This doesn't happen with `RemainAfterExit=false`
### References

First reported on https://github.com/coreos/rkt/issues/2237

**Comment by poettering** [comment] 2016-04-15 18:53
This isn't a bug, this is expected behaviour. machined will not release the machine name until the machine's unit is gone. We explicitly check for that in machined, and watch the unit's state in PID 1 for that.

Or in other words, by using RemainAfterExit=true you explicitly configure PID1 to keep around the scope forever, which means machined will ask the container to shutdown, and then waits for its unit to go away, but it never will, because you explicitly configured that.

This is not a bug hence, but expected behaviour. Hope this make sense. Closing.

(Why would you set RemainAfterExit=true for nspawn even?)

**Closed as completed by poettering** 2016-04-15 18:53 UTC
Labels: nspawn, not-a-bug

**Comment by iaguis** [comment] 2016-04-18 09:14
Right, that makes sense.

> Why would you set RemainAfterExit=true for nspawn even?

It was because we were using `systemctl list-units` to get the rkt containers the machine ran. Thankfully, we don't do that anymore :)

Thanks for the explanation!
