### ISSUE TITLE
Component or interdependent unit stays running when the service it Requires or is PartOf exits

### ISSUE THREAD

**Issue by mvduin** [systemd/systemd#8631] opened 2018-03-31 08:18 UTC
### Submission type

Bug report

### systemd version the issue has been seen with

237 and 238

### Used distribution

debian stretch and debian buster

### Expected behaviour you didn't see

Scenario:
 * main.service Requires component.unit
 * component.unit either Requires or is PartOf main.service
 * main.service either fails to start, or exits (successful or not)

I all these cases I expect component.unit to be stopped by systemd.

### Unexpected behaviour you saw

component.unit remains running after main.service has stopped.

### Steps to reproduce the problem

Create main.service:
```ini
[Unit]
Requires=component.service
[Service]
ExecStart=/bin/false   # or ExecStart=/bin/true
```
and component.service:
```ini
[Unit]
PartOf=main.service   # or Requires=main.service
[Service]
ExecStart=/bin/sleep 600
```
and then run:
```
systemctl start main.service
systemctl status main.service component.service
```

**Comment by boucman** [comment] 2018-03-31 09:55
This all seems to "work as expected" to me, but I know it took me quite some time to integrate the fine details of the dependency logic...

A Requires B means to things :
* If an order to start A is queued, an order to start B will be queued too.
* If B has failed when we are starting A, A will not be started
note that nothing guarentees that B will be started before A

moreover, Requires implies nothing once service B is done starting. if B fails after its initialization phase, A won't be notified. In your case, main.service is (implicitely) of Type=simple, so it's considered correctly started right away, and the exit code of /bin/false arrives after B has checked the status of A.

this is as designed, you probably want Type=oneshot in your example, and After=component.service

as for PartOf, i'm less clear on what it does, but my reading of the manual is it only takes effect when systemd stops main.service (i.e jobs are queued together) and not when the unit stops by itself. but again, i'm not very clear on that one

My guess is that you are in a case where you want BindsTo... but i'm not completely clear on your use-case

**Comment by mvduin** [comment] 2018-03-31 10:51
Okay I really thought I had checked that if A requires B (and no other deps exist) and B exits that A is also stopped... but now I tested again and indeed it doesn't. I probably accidently just tested the case where B fails during startup.

Okay this is... not what I expected from a unit dependency relationship. Hum.

And you're right, it looks like BindTo does what I need.

In the actual use case, the main.service has a RootDirectory pointing to a mountpoint and the component unit is the mount unit for the squashfs image that's mounted there (containing the service and whatever libs/files it needs to run in a chroot like that). If the service stops, the image should be unmounted.

More generally though, when you have units that are mere components of another service, you really don't want them to outlive that service. That's why I really expected PartOf to stop the unit when the service it's part of stops for any reason, and not just propagate explicit stop/restart jobs from the service to the component unit.

**Comment by mvduin** [comment] 2018-03-31 10:53
(oh, before you say "then use RootImage instead of this construction, that's what it's for". I'd love to, but it doesn't work. I still need to file a bug report on that.)

**Comment by poettering** [comment] 2018-04-17 18:07
So yeah, this looks like a job for BindsTo=. Also some ordering deps appear to be missing. Please have a look on the docs for this!

Anyway, closing this, as I think @boucman's explanation explains exactly what is going here and that this is intended behaviour and how to fix this properly.

**Closed as completed by poettering** 2018-04-17 18:07 UTC
