### ISSUE TITLE
Units might be incorrectly activated even if they require a unit whose job that couldn't be enqueued

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#16909] opened 2020-08-31 08:11 UTC
Consider the following units:

```
# cat top-fail.target 
[Unit]
Wants=fail.target
After=fail.target`

# cat fail.target 
[Unit]
Requires=masked.service
After=fail.service
OnFailure=on-failure.service

# cat on-failure.service 
[Service]
ExecStart=/bin/true
RemainAfterExit=yes
```
`fail.target` requires a masked unit, which is considered as an error:

```
# systemctl start fail.target
Failed to start fail.target: Unit fail.service is masked.

# systemctl status fail.target
● fail.target
     Loaded: loaded (/etc/systemd/system/fail.target; static; vendor preset: disabled)
     Active: inactive (dead)
```

However on thing that is worth noting is that even if the target failed to start, `on-failure.service` wasn't started at all:

```
# systemctl status on-failure.service 
● on-failure.service
     Loaded: loaded (/etc/systemd/system/on-failure.service; static; vendor preset: disabled)
     Active: inactive (dead)
```
Now let's see if we start `top-fail.target` which has only a weak dep of type `Wants` on `fail.target`:

```
# systemct start top-fail.target

# systemctl status top-fail.target fail.target on-failure.target
systemctl status top-fail.target fail.target on-failure.service
● top-fail.target
     Loaded: loaded (/etc/systemd/system/top-fail.target; static; vendor preset: disabled)
     Active: active since Mon 2020-08-31 09:21:40 CEST; 9s ago

Aug 31 09:21:40 localhost systemd[1]: Reached target top-fail.target.

● fail.target
     Loaded: loaded (/etc/systemd/system/fail.target; static; vendor preset: disabled)
     Active: active since Mon 2020-08-31 09:21:40 CEST; 9s ago

Aug 31 09:21:40 localhost systemd[1]: Reached target fail.target.

● on-failure.service
     Loaded: loaded (/etc/systemd/system/on-failure.service; static; vendor preset: disabled)
     Active: inactive (dead)
```

Here we can see that pid1 happily started `fail.target` even though it (still) requires a masked unit and `on-failure.target` wasn't still started.

The problem here is due to the fact that we don't enqueue any job when we fail at validating a unit (see call of `bus_unit_validate_load_state()`) during the build of a transaction. We simply abort the job enqueuing. But if the unit we attempt to start was pulled in by a weak dep then the transaction is still processed. This explains why `fail.target` was still activated - no start job was enqueued for `masked.service` - and also why `OnFailure=` didn't work as expected.

Another incorrect behavior not showed in the previous example is that if `fail.target` was pulling several other units in then jobs for those units could have been enqueued if job for `masked.service` was processed after the jobs for the other units. This means that `fail.target` could have been activated while only a part of its strong deps was started (the ones specified by `Requires=`).

**Comment by fbuihuu** [comment] 2020-08-31 08:14
BTW in case you wonder, this happens when /tmp is defined in fstab. In this case `sysvinit.target` is equivalent to `top-fail.target`, `local-fs.target` is equivalent to `fail.target` and `tmp.mount` is `masked.service` assuming that `tmp.mount` was masked by the user.

**Comment by kkdwivedi** [comment] 2020-09-02 16:26
This has been reported before in #11338 and #4937.

**Comment by msekletar** [comment] 2020-09-07 10:29
Duplicate of #11338

**Closed as completed by msekletar** 2020-09-07 10:29 UTC
Labels: pid1
