### ISSUE TITLE
nspawn: Can't use symlink for TTY communication inside container

### ISSUE THREAD

**Issue by Spaceless007** [systemd/systemd#16446] opened 2020-07-13 18:18 UTC
**systemd version the issue has been seen with**
The version that is used is `systemd 245.6-2`

**Used distribution**
I'm using the most recent unstable debian image, obtained with this command: `debootstrap --include=systemd-container unstable /var/lib/machines/debian-unstable` 

**Expected behaviour you didn't see**
I'm trying to communicate with a systemd-nspawn container via `socat`. Since `socat` opens random ports, and I want to always open the same port, then I'm creating symlink with `link=` option. Here is the command that I'm executing:
```bash
socat -d -d pty,raw,echo=0,link=fakepts/10 pty,raw,echo=0,link=fakepts/11
```

Then I want to do something like this:
```bash
# Open first terminal
nbeaudoi@melpomenia:~$ sudo systemd-nspawn -bD /var/lib/machines/debian-unstable --machine debian-unstable

# Open second terminal
nbeaudoi@melpomenia:~$ sudo machinectl bind --mkdir debian-unstable ${PWD}/fakepts/ /dev/fakepts

# Return to first terminal inside container
root@melpomenia:~$ cat < /dev/fakepts/10
Test # test is printed via cat < /dev/fakepts/10 command

# Return to second terminal
nbeaudoi@melpomenia:~$ echo "Test" > ${PWD}/fakepts/11

# Return to first terminal inside container
Test # test is printed via cat < /dev/fakepts/10 command
```

**Unexpected behaviour you saw**
The thing is, it doesn't work. When I `cat < /dev/fakepts/10` inside the container. it says: `-bash: /dev/fakepts/10: No such file or directory`. And I can verify that it is there by doing: 
```bash
root@melpomenia:~$ ls -ln /dev/fakepts/10
lrwxrwxrwx 1 1001 1001 10 Jul 13 12:34 /dev/fakepts/10 -> /dev/pts/3
```

I checked online, and I found someone that was saying this kind of problem happens when the symlink becomes broken. But, I can make it work without symlinks by doing this: 

```bash
# Open first terminal
nbeaudoi@melpomenia:~$ socat -d -d pty,raw,echo=0 pty,raw,echo=0 
2020/07/13 12:32:10 socat[17533] N PTY is /dev/pts/3
2020/07/13 12:32:10 socat[17533] N PTY is /dev/pts/4
2020/07/13 12:32:10 socat[17533] N starting data transfer loop with FDs [5,5] and [7,7]

# Open second terminal
nbeaudoi@melpomenia:~$ sudo systemd-nspawn -bD /var/lib/machines/debian-unstable --machine debian-unstable

# Open third terminal
nbeaudoi@melpomenia:~$ sudo machinectl bind --mkdir debian-unstable /dev/pts /dev/fakepts

# Return to second terminal inside container
root@melpomenia:~$ cat < /dev/fakepts/10

# Return to third container 
nbeaudoi@melpomenia:~$ echo "Test" > ${PWD}/fakepts/4

# Return to second terminal inside container
# root@melpomenia:~$ cat < /dev/fakepts/3
Test # test is printed via cat < /dev/fakepts/3 command
```

So this solution works great, which is why I didnt understand why the first solution doesnt work (when I have symlinks). 

**Steps to reproduce the problem**

```bash
# Open first terminal
nbeaudoi@melpomenia:~$ mkdir fakepts
nbeaudoi@melpomenia:~$ touch fakepts/10
nbeaudoi@melpomenia:~$ touch fakepts/11
nbeaudoi@melpomenia:~$ socat -d -d pty,raw,echo=0,link=fakepts/10 pty,raw,echo=0,link=fakepts/11

# Open second terminal
nbeaudoi@melpomenia:~$ sudo debootstrap --include=systemd-container unstable /var/lib/machines/debian-unstable
nbeaudoi@melpomenia:~$ sudo systemd-nspawn -bD /var/lib/machines/debian-unstable --machine debian-unstable

# Open third terminal
nbeaudoi@melpomenia:~$ sudo machinectl bind --mkdir debian-unstable /fakepts /dev/fakepts

# Return to second terminal inside container
root@melpomenia:~$ cat < /dev/fakepts/10
-bash: /dev/fakepts/10: No such file or directory
```

**Comment by poettering** [comment] 2020-07-14 07:03
symlinks are resolved in the context they are accessed, i.e. if you bind mount a directory with symlinks from host into container, and then access them in the container, they will be resolved relative to the container, and not the host, i.e. point to the container's pts devices in your cases and not the hosts. However, since you haven't allocated pts device in the container they won't point to working pts devices.

The set of pts devices defined in the container and defined on the host is entirely distinct. If you want to make a pts device from the host available in the container, then you must mount the device node itself into the container, it's not sufficient to mount the directory it is in. (Yes, you can mount files and device nodes, too, on Linux, not just dirs)

Closing, since this is not a bug, but simply how Linux works.

**Closed as completed by poettering** 2020-07-14 07:03 UTC
Labels: nspawn, not-a-bug
