### ISSUE TITLE
RestrictAddressFamilies= broken on 32-bit

### ISSUE THREAD

**Issue by falconindy** [systemd/systemd#4575] opened 2016-11-04 18:07 UTC
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

v232

### Used distribution

Arch Linux

### In case of bug report: Expected behaviour you didn't see

Expected the machine to boot

### In case of bug report: Unexpected behaviour you saw

Many daemons fail to start. Notably, those with RestrictAddressFamilies= all fail to start. The journal is the most vocal about this:

```
[    1.596056] systemd-journald[151]: Failed to create notify socket: Protocol not supported
```

Commenting out RestrictAddressFamilies= in systemd-journald.service makes that error go away, but other services (systemd-udevd for example) never show up, devices aren't found... the system never completes booting.

### In case of bug report: Steps to reproduce the problem

Boot a 32bit system with v232.

**Comment by FredBezies** [comment] 2016-11-04 18:28
I am the bug reporter on archlinux bugtracker. The only fix ? Downgrading to systemd 231 :(

**Comment by falconindy** [comment] 2016-11-04 18:29
As I pointed out, you can just disable RestrictAddressFamilies= in the relevant units rather than downgrade...

**Comment by FredBezies** [comment] 2016-11-04 18:35
It was simpler for me to downgrade. I did not want to tweak every single unit needed.

**Comment by martinpitt** [comment] 2016-11-04 19:38
In Debian (https://bugs.debian.org/843160) this only happens on 32 bit userspace running on a 64 bit kernel. Our CI runs a 32 bit kernel (for the i386 test) and thus didn't notice that. Can you confirm that you are running a 64 bit kernel as well?

**Comment by falconindy** [comment] 2016-11-04 19:42
No, this is a 32 bit kernel.

**Comment by poettering** [comment] 2016-11-04 19:56
this smells like libseccomp rather than systemd borkage to me, but I might be mistaken...

**Comment by poettering** [comment] 2016-11-04 20:06
(the weird thing here is that the filter we pass to libseccomp for this on i386 should actually become a NOP. That's because on i386 all socket syscalls are multiplexed over a single "socketcall()" super-syscall, and it takes the actual command to execute as indirect parameter, meaning that seccomp cannot match against it. If it suddenly ends up masking all socket() syscalls, then this indicates that something is really off here...

**Comment by falconindy** [comment] 2016-11-05 02:23
Yep, it does seem to be masking all socket calls. I lifted the logic out of src/core/execute.c and wrote a test program. Blocking _any_ address family seems to result in all socket calls returning EPROTONOTSUPPORT. Maybe this is fixed by https://github.com/seccomp/libseccomp/commit/73d83e45efbe8c31067c97155162f17ca51b7435

edit: scratch that, there's a tag missing from the libseccomp repo which lead me to believe that the above commit was not yet released...

**Comment by nilsholland** [comment] 2016-11-05 12:56
@martinpitt: Just to chime in here, I can also confirm that it happens with a 32 bit kernel (and, obviously, 32 bit userspace) on my Gentoo system. So it indeed doesn't seem to be a 64 bit kernel / 32 bit userspace problem only.

**Comment by mbiebl** [comment] 2016-11-05 13:30
I've just tried this in a 32bit VM and can easily reproduce the issue.
What makes this even more severe is, that I'm not dropped into the rescue shell. systemd just tries over and over to start systemd-udevd after it times out. I guess this can be considered a bug on its own.
No rescue shell means not possibility to fix the system.

**Comment by daavve** [comment] 2016-11-05 19:00
On my 32-bit Arch laptop it drops to the rescue shell.  Also RestrictAddressFamilies= is not present in any of my config files.

If you need any logs please let me know.

-Dave

**Comment by falconindy** [comment] 2016-11-05 19:14
RestrictAddressFamilies= is present in units shipped with v232.

**Comment by daavve** [comment] 2016-11-05 20:37
My Bad,

I see that RestrictAddressFamilies is present in core/dbus-execute.c, 
and in core/execute.

How do I go about disabling this?

Thanks,

-Dave

**Comment by nilsholland** [comment] 2016-11-05 22:38
@daavve: You don't have to edit any source files, just check the unit files in /usr/lib/systemd/system and comment out the RestrictAddressFamilies= lines. It were about four files or so that I had to change there in order to make my system bootable again ... systemd-udevd.service and systemd-journald.service are the ones I remeber, I think the other ones were the logind and timesyncd unit files or something like that.

Of course, making these changes in those files is only a workaround and doesn't fix the root issue.

**Comment by daavve** [comment] 2016-11-06 03:24
Thanks nilsholland,

I ended up having to edit the localed, udev, journal-gatewayd, tiesyncd, 
iportd, timedated, journal-remote, hostnamed, journal-upload, networkd, 
resolved, journald, logind, and machined .service files.

My laptop works again.  I fear uncovering the root if this issue may 
exceed my programming skills.  Good luck!

-Dave

**Comment by martinpitt** [comment] 2016-11-08 15:05
For the record, this also affects s390x (IBM z-series) which is 64 bit and big-endian (see PR #4611).

**Comment by heftig** [comment] 2016-11-09 10:04
i386 Linux 4.3 gained individual syscalls so seccomp can filter them, and if you do that then it makes sense the old `socketcall` interface is disabled completely. At least unless `socketcall` is somehow adjusted to fake the other syscalls to seccomp, if that's even possible.

Looks like this can be fixed by updating libc to use the new syscalls, at least for i386. https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1576066 suggests Ubuntu has already done so.

**Comment by poettering** [comment] 2016-11-10 20:04
> i386 Linux 4.3 gained individual syscalls so seccomp can filter them,

This doesn't help much, as the old socketcall()-based API of course stays around, and thus blocking the new API won't suffice to make the functionality unavailable.

**Comment by heftig** [comment] 2016-11-10 20:06
No, I think that's exactly what happens. If you filter on any of the new syscalls, `socketcall` becomes completely unavailable.

**Comment by poettering** [comment] 2016-11-11 13:09
@heftig but that'd be a major bug in libseccomp. It shouldn't block more than it is told to block when blacklisting stuff... Did anyone contact the libseccomp folks about all of this yet?

**Comment by mbiebl** [comment] 2016-11-11 14:06
I don't think there has been a bug filed yet against libseccomp. 
@pcmoore your input would be very much appreciated. Maybe you can chime in here.

**Comment by pcmoore** [comment] 2016-11-11 14:55
Can somebody point me to the systemd code which is calling libseccomp in response to the RestrictAddressFamilies option?  I want to try to better understand what systemd is doing before I comment.

**Comment by poettering** [comment] 2016-11-11 14:58
The relevant bits are here:

https://github.com/systemd/systemd/blob/master/src/core/execute.c#L1252

and here:

https://github.com/systemd/systemd/blob/master/src/shared/seccomp-util.c#L125 (and environs)

**Comment by heftig** [comment] 2016-11-11 15:26
There seems to be some code dealing with generating rules to filter `socketcall` when you match on the new syscalls here:

https://github.com/seccomp/libseccomp/blob/937e774d8ccfd063a601f49ef46769de3926b62d/src/arch-x86.c#L223

Now I don't know the seccomp code at all, but to me that looks like they're _replacing_ the first argument compare with one that matches on the pseudo-syscall number instead of _adding_ a compare and shifting the indices for the other arguments.

**Comment by pcmoore** [comment] 2016-11-11 15:50
```
Now I don't know the seccomp code at all, but to me that looks like they're replacing the
first argument compare with one that matches on the pseudo-syscall number instead of
adding a compare and shifting the indices for the other arguments.
```

Unfortunately the multiplexed 32-bit x86 socket syscalls don't work that way; the syscall is called such that the multiplexed syscall number is the first argument to socketcall(2) and all of the remaining arguments are packaged up in a structure which is passed as the second argument.  See the manpage below:
- http://man7.org/linux/man-pages/man2/socketcall.2.html

I'll try to run some tests to verify that libseccomp is doing the right thing here (believe it or not, there are a lot of corner cases on this, I may have missed one), but I suspect the issue is that systemd is calling seccomp_rule_add(3) which will do some best effort rule mangling to add the rule in cases where the underlying arch/ABI does not fully support the rule as written.  In this particular case (attempting to filter on syscall arguments passed to socket(3) on 32-bit x86), libseccomp is limited to filtering on the syscall, independent of the arguments, due to limits with the kernel's ABI.  Possible solutions include changing to seccomp_rule_add_exact(3) which will do no such mangling, it will just fail if given rules which aren't valid for the ABI, or convert your libraries/applications to use the direct wired socket syscalls introduced in Linux v4.3 (yes, I realize this is very non-trivial); the latest versions of libseccomp _should_ correctly generate seccomp filters for both the multiplexed and direct wired socket syscalls.
- http://man7.org/linux/man-pages/man3/seccomp_rule_add.3.html

**Comment by poettering** [comment] 2016-11-11 17:37
@pcmoore Oh... I assumed that seccomp_rule_add() would become a NOP if the arch doesn't permit the precise match. i.e. i assumed if I use it to block some syscall, and the precise syscall cannot be matched due to the socketcall() weirdness, then it would rather not block it all all, than block too much. Are you saying that it actually prefers blocking too much?

The docs are very vague about this. Quoting the man page: 

```
   The seccomp_rule_add() and seccomp_rule_add_array() functions will
   make a "best effort" to add the rule as specified, but may alter the
   rule slightly due to architecture specifics, e.g. socket and ipc
   functions on x86.  The seccomp_rule_add_exact() and
   seccomp_rule_add_exact_array() functions will attempt to add the rule
   exactly as specified so it may behave differently on different
   architectures.  While it does not guarantee a exact filter ruleset,
   seccomp_rule_add() and seccomp_rule_add_array() do guarantee the same
   behavior regardless of the architecture.
```

Can you elaborate what this is supposed to mean?

**Comment by pcmoore** [comment] 2016-11-11 18:34
The documentation is intentionally vague at this point as there are still some ABIs and syscalls that we don't have supported as well as I would like; as we continue to develop libseccomp I expect that we will be able to flesh this out further.  Yes, it isn't perfect, but it is what we've got at the moment.

FWIW, I don't expect the behavior to change to change with respect to 32-bit x86 and the socket related syscalls, so the behavior you are seeing now is likely to continue to be that behavior.  I suspect we will end up doing very similar things with the other ABIs/syscalls for the sake of consistency/sanity, but I can't promise that at this moment.  Perhaps someday I might add some flexibility to allow callers to specify to fail permissive (the NOP as you describe) or to fail restrictive (the current behavior), but that doesn't solve the issue you are having today.

Based on the conversation in this thread, if you don't want to add ABI specific checks (I wouldn't), it seems like perhaps the best option for systemd at the moment is to attempt to add the rule using seccomp_rule_add_exact(3) and simply keep going (perhaps issue a warning about an impossible config?).

**Comment by pcmoore** [comment] 2016-11-11 18:38
```
Perhaps someday I might add some flexibility to allow callers to specify to fail permissive
(the NOP as you describe) or to fail restrictive (the current behavior), but that doesn't
solve the issue you are having today.
```

Just in case anyone is curious or wants to comment, I created a libseccomp issue to track the fail permissive/restrictive toggle:
- https://github.com/seccomp/libseccomp/issues/54

**Comment by poettering** [comment] 2016-11-11 18:46
> the best option for systemd at the moment is to attempt to add the rule using seccomp_rule_add_exact(3) and simply keep going

OK, I figure we can do this. Any chance you can document the precise error code that is returned for this specific case? I'd like to handling this specific case explicitly, so that other errors can be fatal, but this one doesn't have to be...

**Comment by pcmoore** [comment] 2016-11-11 20:46
Looking quickly at the code, it looks like it will return -EINVAL in this particular case; far from ideal.  I might be a good idea for someone to verify that return value just to make sure I didn't miss something (I would, but I lost my 32-bit x86 VM when my laptop drive died last week and haven't replaced it yet).

See my comments above about being vague, I may want to change this error code in the future to make it a bit more obvious that the error was due to a ABI conflict.

**Comment by poettering** [comment] 2016-11-14 19:03
@pcmoore hmm, OK, for now we'll just consider all errors here as "local arch doesn't permit this check". it would be nice if you could change libseccomp though to add a proper, distinct error number for this case, that we can check for. If you add this, please let us know the error number you picked, and we'll adapt systemd accordingly, and add a versioned dep for this.

Hmm, one more question: how does this all relate to secondary archs? If I use `seccomp_rule_add_exact()` and then rule works fine on the primary arch, but doesn't on secondary archs I added (which is typically the case on x86_64), then will the call fail or what will it do? If it fails, is there any chance I can distinguish failure due to the primary arch from failure due to any secondary arch?

**Comment by pcmoore** [comment] 2016-12-15 20:19
Sorry for the delay, this got lost in my inbox while on vacation and I just saw it now, let me try to answer your questions.

    How does this all relate to secondary archs? If I use seccomp_rule_add_exact() and
    then rule works fine on the primary arch, but doesn't on secondary archs I added
    (which is typically the case on x86_64), then will the call fail or what will it do?

In this particular case libseccomp will attempt to add the rule to each architecture which is part of the filter.  If any of the architectures fail to add the rule then an error code will be returned; in the case of multiple failures the first error code encountered will be returned.

    If it fails, is there any chance I can distinguish failure due to the primary arch from
    failure due to any secondary arch?

Not presently no.  There is no real concept of architecture priority, e.g. primary/secondary, within libseccomp; the architecture is either part of the filter or it is not.

**Comment by poettering** [comment] 2016-12-27 17:17
Fix waiting in #4991. I reworked this quite a bit now. We don't rely on libseccomp's own support for dealing with multiple syscall archs, and we do not rely on libseccomp's support for "inexact" rules. The behaviour of both is not properly defined apparently, and hence to get clear, well-defined behaviour we'll avoid it and handle them in our code.

I would prefer if all of this would be hidden in libseccomp I must say, as I think this really makes it hard to use in real-life applications, as the glue code you need around it becomes non-trivial...

**Closed as completed** 2017-01-18 06:08 UTC
Labels: pid1

**Comment by pcmoore** [comment] 2017-01-18 19:19
One possible workaround to get you more control over filter creation would be to create multiple filters, one for each arch/ABI, and then merge them at the end using seccomp_merge(3).  This would allow you better control and error reporting.

**Comment by AdamWill** [comment] 2017-01-21 02:21
This issue also affects Fedora Rawhide, and backporting the fix to v232 isn't trivial: https://bugzilla.redhat.com/show_bug.cgi?id=1415358 . Could a Fedora maintainer please get this fixed in Fedora somehow? Thanks.

**Comment by mbiebl** [comment] 2017-01-21 03:43
@AdamWill  @martinpitt did the backport for Debian, just in case you want to have a look:
https://anonscm.debian.org/cgit/pkg-systemd/systemd.git/commit/?id=c31b5ee9b9c79c9d2ac491920b23a8084a4ccc46

You will want to cherry-pick 51b9bb4f8e88d420ae557c3ecf1922dd9ac95fcc as well
in case seccomp support is not enabled on all architecutures
