### ISSUE TITLE
systemd-journald   Argument list too long

### ISSUE THREAD

**Issue by rthorntn** [systemd/systemd#7119] opened 2017-10-18 02:15 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 234

### Used distribution

> Clear Linux

### In case of bug report: Expected behaviour you didn't see

> N/A - everything seems to be working normally

### In case of bug report: Unexpected behaviour you saw

> error: systemd-journald[246]: Failed to write entry (24 items, 5112466 bytes) despite vacuuming, ignoring: Argument list too long

### In case of bug report: Steps to reproduce the problem

> reboot, it happens just before the login prompt, just in case it's important I moved this NVMe drive from a NUC to a desktop PC.

**Comment by poettering** [comment] 2017-10-20 09:22
what arch is this?

did you configure any specific values in journald.conf (such as the file metrics and such), or are they the upstream defaults? is the /var partition full or close to being full when this happens?

**Comment by rthorntn** [comment] 2017-10-24 01:09
Hi Lennart,

Thanks, it's Intel Clear Linux, on a rolling release, it's stateless and so doesn't have a /etc/systemd directory or journald.conf but I'm going to be adding one for mounting & service startup at boot.  Happy to add journald.conf if I should have one?

/var doesn't have it's own partition, so it has 1.8T as part of /.

Thanks.

Richard

**Comment by renich** [comment] 2019-06-12 14:59
Hello!

I had this same problem in CentOS 7.6. I think this happens when the list of journal files gets too big.

**Comment by vcaputo** [comment] 2019-06-22 15:20
I just had my Debian 9 (v232) laptop fail to boot because /var is full, with the boot coming to a halt at `systemd-journald` failing an `assert(f)` somewhere in `journal-file.c`.

The error printed was `Argument list too long` (`E2BIG`) which was *very* confusing.  At the least there seems to be an error return path in journal-file.c returning `-E2BIG` where it should be `-ENOSPC`.

In my case I had left a very large `SystemMaxFileSize` in `journald.conf` from testing something in the past, so it was my doing.  But it wouldn't surprise me if the misleading error message is partly to blame for what's being reported in this issue.

**Comment by mrc0mmand** [comment] 2023-12-08 22:26
Closing, since the issue is very old and there were many fixes in the mentioned area since then. Please feel free to reopen, if the issue still occurs.

**Closed as not planned by mrc0mmand** 2023-12-08 22:26 UTC
Labels: journal
