### ISSUE TITLE
API/options for joining units to a particular user session

### ISSUE THREAD

**Issue by izh1979** [systemd/systemd#18652] opened 2021-02-17 10:18 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes you may need to start user session units as a part of particular user session (e.g. the graphical session on the seat0). There are two use cases for that. First, it could be convenient to launch graphical applications with simple `systemctl` call.
The second case is the application startup boosters. I.e. you have a forked spare process that has loaded almost all necessary shared libraries, then simply dlopen()s the target application binary and jumps to main(). This can considerably reduce the launch time in some cases.
In all these cases you can't start necessary services and then join the needed user session because of lack of the proper API/options. Currently it is required that all user session processes must be children of the login process of that session.

**Describe the solution you'd like**
It could be implemented in a form of instantiating some user service at particular user session. Like `systemctl start gimp@seat0`.

**Comment by izh1979** [comment] 2021-02-17 10:19
By threating applications as a separate services it would be possible to apply e.g. cgroups CPU and memory limits on a particular application.

**Comment by poettering** [comment] 2021-02-17 22:34
> Sometimes you may need to start user session units as a part of particular user session

Not sure I grok this?

systemd has no "per-session" instance, only a *per-user" instance?

we nowadays synthesize unit files for all XDG desktop files via a generator, hence such executables are already startable via "systemctl start"?

systemd enforces a myriad of sandboxing options and other options it can only do when it forks off the processes themseves. kdserver style stuff doesn't really work in a systemd world anymore. We need the security boundary that the execve() provides, there's no way around it.

You can already have systemd manage process your fork off some other processes as a unit, via the "scope" logic. See `systemd-run --scope` for example.

I don't grok the request though I must say. It seems there are some misunderstanding but also that most of what you are asking for already exists?

**Comment by izh1979** [comment] 2021-02-18 14:48
May be it is already existing.

In Sailfish OS we have 2 systemd's running: one for the system services (PID1) and the another one is for the currently logged user (with autologin). So the user session "c1" is started automatically when the device boots.

But not all of the processes that are started via /usr/lib/systemd/user/ units are belonging to the "c1" session, but only those that are children of a particular service.

So if we will try to start some application as s user service, it will not belong to "c1" session. And that creates trouble with the Polkit which checks whether the requesting process belongs to the session.

That's why I asked whether it is possible to move processes that are started as the user units to the "c1" session.

**Comment by poettering** [comment] 2021-02-22 16:01
uh, oh, nah, this needs to be fixed in polkit (and I think it already was). i.e. the logic in PK needs to be: "does the user of process X have a session on the console" instead of "is the session of the process X on the console".

To my knowledge this has been addressed a long time ago in PK, but I don't remember. Given this isn't an issue in Fedora which uses per-user services heavily and also PK heavily I assume this is all addressed long time ago.

Maybe ask the PK people for help on this?

does your distro run a current PK version?

**Comment by izh1979** [comment] 2021-02-22 17:11
Thanks for the suggestion. I will check the version.

Currently, I guess, it works exactly like this: the PK tries to find to what session the process belongs. So if it is on the graphical session, it will show the graphical confirmation UI. But if you are using ssh connection (in the developer mode), it will show the prompt on the console.

So when we are trying to start the graphical apps via system --user, and they don't belong to the "c1" session from the PK's point of view, the PK is refusing to authorize the requests.

**Comment by izh1979** [comment] 2021-02-26 08:37
I've checked it. It is 0.105, while the latest version is 0.118. Will check whether that logic  was changed between the two releases.

**Comment by dev-harsh1998** [comment] 2021-03-06 14:40
> Thanks for the suggestion. I will check the version.
> 
> Currently, I guess, it works exactly like this: the PK tries to find to what session the process belongs. So if it is on the graphical session, it will show the graphical confirmation UI. But if you are using ssh connection (in the developer mode), it will show the prompt on the console.
> 
> So when we are trying to start the graphical apps via system --user, and they don't belong to the "c1" session from the PK's point of view, the PK is refusing to authorize the requests.


Can confirm this

**Comment by izh1979** [comment] 2021-03-10 14:45
Thanks. We will check the new PK.

@poettering If you think that it is not very useful to be able to launch units on a specific user session, I have no objections on closing this issue.

**Comment by poettering** [comment] 2023-06-06 08:00
OK, closing then. I am pretty sure this is just a PK issue, i.e. update your PK and the issue is gone.

**Closed as completed by poettering** 2023-06-06 08:00 UTC
Labels: needs-discussion 🤔, not-our-bug, needs-reporter-feedback ❓
