### ISSUE TITLE
systemd-resolved: Failback to 'primary' DNS server when it's available

### ISSUE THREAD

**Issue by rafajot1** [systemd/systemd#29614] opened 2023-10-19 08:09 UTC
### Component

resolvectl

### Is your feature request related to a problem? Please describe

With traditional /etc/resolv.conf having configured external nameservers, they are queried in order (unless rotate option is used)
Windows also seems to prefer the first nameserver on the list: https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/dd197552(v=ws.10)

Based on that many network admins assumed DNS responses will mostly come from the first nameserver on the list and 'secondary' or 'tertiary' would be used only in case former nameservers are not reachable.
Therefore, we may end up in a situation where systemd-resolved permanently queries slower nameserver even though 'primary' nameserver is available again.

Moreover, nameservers might be in different geo regions and resolve differently some names such as proxy server IP address specific to their geo region. This situation may lead to even worse overall Internet performance.

### Describe the solution you'd like

I understand that not trying the first server on the list in every DNS query in the situation where it was not available recently is a significant performance improvement.
Anyway, it would be great to probe at least the first nameserver and have an option to fail back.
The frequency of such probing could be either hardcoded or configurable with some reasonable default value (5 minutes?)

### The systemd version you checked that didn't have the feature you are asking for

systemd 249 (249.11-0ubuntu3.9)

**Comment by poettering** [comment] 2023-10-23 08:11
Sorry, but this is a really bad idea. we generally stick to the DNS server that works. That is initially the first one, until we see some error, when we switch to the next, and then we stick with that.

In todays world where DNS servers need to be probed for feature set it's simply not a good idea to always flush everything out and start from the top.

**Comment by rafajot1** [comment] 2023-10-23 12:15
Fair enough, thank you for your response.

**Comment by jonesmz** [comment] 2023-11-07 05:20
This may be a duplicate of: https://github.com/systemd/systemd/issues/5755

**Comment by poettering** [comment] 2023-11-07 08:34
Yeah, let's close it as duplicate.

**Closed as completed by poettering** 2023-11-07 08:34 UTC
Labels: RFE 🎁, resolve, duplicate
