### ISSUE TITLE
Ability to hide systemd processes from users (like hidepid=2 for /proc)

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#13333] opened 2019-08-16 19:01 UTC
Hi Poettering and all,

I already run my systems with /proc mounted with hidepid=2 so that any intentional or accidental passwords on the command line don't show up in the process table, among other reasons. Each user can only see their own process table which makes sense.

Now, I'd like to get [rqlited](https://github.com/rqlite/rqlite/blob/master/DOC/SECURITY.md#secure-cluster-example) going with authentication while running under systemd. It's partly in vain if every user on the system can see the password through `systemd status`.

This is largely related to: "Configuration file %s is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway."
https://github.com/systemd/systemd/blob/6fd79cca68a170c88e87b5d95cd7a44953df94e2/src/basic/fs-util.c#L319

It seems like this is because of how /sys/fs/cgroup/systemd is mounted. If it was mounted with mode=0700, only root would be able to see it.

Is it possible to adjust that? That and to set my service files to 0600 so users can't read them?

Even if I made a script that then executes a command requiring a password on the command line, that still shows up in `systemd service`. But being able to have 0600 .service files without warnings and /sys/fs/cgroupd/systemd mounted 0700 would be nice. I guess it might impact systemd user services? In my case not immediately a big deal.

If this isn't a good solution, could you give me another recommendation?

This seems related: https://github.com/systemd/systemd/issues/12955

Here @poettering is saying that hidepid=2 doesn't work with systemd. Obviously that isn't true in every case (at least with the version on Debian 9) as I've been using it with hidepid=2 for ages.

Also related: https://github.com/systemd/systemd/pull/11670

What is PrivatePIDS? I can't find information about it.

Thank you for your time.

-Teran

**Comment by topimiettinen** [comment] 2019-08-17 07:58
Using command line for secrets has been a bad idea forever. But I think rqlite does not require or promote that. In the example the password is in  `/etc/rqlited/config.json`, which should not be world readable. There's no need to restrict the permissions of other files.

I proposed PrivatePIDS as a new feature in #11670, based on PID namespaces. However, the preferred approach is to wait for @tixxdz's `/proc` patches for kernel to be finalized (@legionus?), which allows `/proc` mount options (like hidepid=2) to be changed per task.

I think this issue is a duplicate of #12955, closing.

**Closed as completed by topimiettinen** 2019-08-17 07:58 UTC
Labels: not-supported, duplicate
