### ISSUE TITLE
"session-1.scope: Failed with result 'timeout'."

### ISSUE THREAD

**Issue by DUOLabs333** [systemd/systemd#23501] opened 2022-05-24 17:31 UTC
**systemd version the issue has been seen with**
 > 250.5-1

**Used distribution**
 > Arch Linux 

**Linux kernel version used** (`uname -a`)

 > `5.17.1-1`

**CPU architecture issue was seen on**
 > ARM64

**Expected behaviour you didn't see**
 > When shutting down, it should stop almost instantly.

**Unexpected behaviour you saw**
 > Takes 90 seconds to time out and shut down.

**Steps to reproduce the problem**
 > I'm not sure what causes it (this happened when I updated to Linux 5.17, though it could also be coincidental with an update to systemd).

**Additional program output to the terminal or log subsystem illustrating the issue**

```
May 24 10:15:56 system systemd[1]: session-1.scope: Stopping timed out. Killing.
May 24 10:15:56 system systemd[1]: session-1.scope: Failed with result 'timeout'.
May 24 10:15:56 system systemd[1]: Stopped Session 1 of User system.
```

This might be similar to #1615

**Comment by DUOLabs333** [comment] 2022-05-24 17:52
With `261`, I now also get
```
May 24 13:48:10 system plasma_waitforname[6458]: org.kde.knotifications: WaitForName: Service was not registered within timeout
May 24 13:48:10 system dbus-daemon[389]: [session uid=1001 pid=389] Activated service 'org.freedesktop.Notifications' failed: Process org.freedesktop.Notifications exited with status 1
```

**Comment by DUOLabs333** [comment] 2022-05-24 18:15
Some debug logging:
```
May 24 14:09:18 system systemd[1]: systemd-logind.service: Got notification message from PID 313 (WATCHDOG=1)
May 24 14:09:18 system systemd[1]: systemd-networkd.service: Got notification message from PID 314 (WATCHDOG=1)
May 24 14:09:18 system systemd-networkd[314]: enp0s2: NDISC: Sent Router Solicitation, next solicitation in 58s
May 24 14:10:17 system systemd[1]: systemd-networkd.service: Got notification message from PID 314 (WATCHDOG=1)
May 24 14:10:17 system systemd-journald[272]: Sent WATCHDOG=1 notification.
May 24 14:10:17 system systemd-networkd[314]: enp0s2: NDISC: Sent Router Solicitation, next solicitation in 1min 57s
May 24 14:10:17 system systemd[1]: systemd-journald.service: Got notification message from PID 272 (WATCHDOG=1)
May 24 14:10:18 system systemd[1]: session-1.scope: Stopping timed out. Killing.
May 24 14:10:18 system systemd[1]: session-1.scope: Failed with result 'timeout'.
May 24 14:10:18 system systemd[1]: session-1.scope changed stop-sigterm -> failed
May 24 14:10:18 system systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=4566 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 24 14:10:18 system systemd[1]: session-1.scope: Job 739 session-1.scope/stop finished, result=done
May 24 14:10:18 system systemd[1]: Stopped Session 1 of User system.
May 24 14:10:18 system systemd-logind[313]: Got message type=signal sender=:1.2 destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=4566 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
```

**Comment by Werkov** [comment] 2022-06-07 17:25
Given the distribution and systemd version, I assume you run the systemd with the unified cgroup mode. (`grep cgroup2 /proc/mounts` should show `/sys/fs/cgroup`.)

It looks like some processes in `session-1.scope` won't terminate upon `SIGTERM` and hence they have to be stopped forcefully after timeout.

I'd suggest the [generic shutdown troubleshooting](https://freedesktop.org/wiki/Software/systemd/Debugging/#diagnosingshutdownproblems) and additionally something like

```
cat >/etc/systemd/system/session-.scope.d/99-debug.conf <<EOD
[Unit]
OnFailure=dump-procs@%n.service
EOD

cat >/etc/systemd/system/dump-procs@.service <<EOD
[Service]
Type=oneshot
ExecStart=/usr/bin/cat /sys/fs/cgroup/user.slice/user-<YOUR_UID>.slice/%I/cgroup.procs
EOD
```
(Replace YOUR_UID and test by `systemctl start dump-procs@session-<ID>` (figure ID of a session e.g. with `loginctl`). I did not test this.)

**Comment by DUOLabs333** [comment] 2022-06-07 17:41
I got `/sys/fs/cgroup/user.slice/user-1001.slice/session/1/cgroup.procs: No such file or directory`

**Comment by DUOLabs333** [comment] 2022-06-07 17:47
Anyways, fixed it. What should I do with this information.

**Comment by Werkov** [comment] 2022-06-08 09:59
From systemd-shutdown(8):
> systemd-shutdown will run all **executables** in /usr/lib/systemd/system-shutdown/

(Highlight mine, i.e. is your script executable?)

**Comment by DUOLabs333** [comment] 2022-06-08 13:29
What script?

**Comment by Werkov** [comment] 2022-06-08 13:34
I was referring to `debug.sh` from the [troubleshooting](https://freedesktop.org/wiki/Software/systemd/Debugging/#diagnosingshutdownproblems) manual.

I see you're asking about `debug.conf`, sorry. One plain `systemctl daemon-reload` should make it (`sysctemctl cat session-<ID>.scope` to check it).

**Comment by Werkov** [comment] 2022-06-08 13:58
And the session's timeout occurred?
(I'm not 100% sure `OnFailure=` triggers on stop timeout (it was just a quick suggestion) but I'm positive it won't trigger when there's no failure.)

**Comment by DUOLabs333** [comment] 2022-06-08 13:59
Yes, the timeout occurs.

**Comment by DUOLabs333** [comment] 2022-06-08 14:09
Figured it out --- it's because of postgres. It doesn't shutdown promptly to `SIGTERM`. Killing it before shutting it down is quite prompt.

**Comment by DUOLabs333** [comment] 2022-06-08 14:57
Is there a way to tell systemd to run some commands before just `SIGTERM`ing everything? I have some scripts that monitor for `SIGTERM` then shuts down `postgresql` with `SIGINT`.

**Comment by Werkov** [comment] 2022-06-08 15:07
You may redefine `KillSignal=` for a scope, or define `ExecStop=` if it were a service. (Or prolong `TimeoutStopSec=` if the DB needs longer time to cleanup.)

**Comment by DUOLabs333** [comment] 2022-06-08 15:45
So there's no `ExecStop` for a scope?

**Comment by Werkov** [comment] 2022-06-08 15:56
Nope, see also 2d4a39e759c4ab846ad8a546abeddd40bc8d736e.

**Comment by DUOLabs333** [comment] 2022-06-08 17:02
Well, I don't have a controller for all processes, only a few. Is there a corresponding service for `session-*.scope`?

**Comment by Werkov** [comment] 2022-06-08 17:16
That'd be the docker daemon in the ideal world (in the even more ideal world, it'd use [`org.freedesktop.machine1.Manager`](https://www.freedesktop.org/software/systemd/man/org.freedesktop.machine1.html) API to register the container's scope (cf libvirt and VM scopes)).
But the name of `session-<ID>.scope` suggests this is a logind's scope, i.e. likely result of call into `pam_systemd` somewhere on your container starting path. Or if it's your regular user session, the postgres process was left behind in a wrong cgroup. So I'd suggest reviewing how the container is started.

**Comment by DUOLabs333** [comment] 2022-06-08 17:58
Ok, I figured out that the problem is not with postgres directly, but rather (at least) one of my containers (killing postgres before shutting down still causes a timeout, but killing all my containers before shutting down doesn't). Is there a service that runs before the shutdown of session-1.scope. I'll have to look into whether it's the containers themselves that cause the problem or one of them in particular.

**Comment by DUOLabs333** [comment] 2022-06-08 18:51
Figured out the issue after a lot of trial and error: this happens if you have `/sys` bind-mounted on top of the mountpoint of a unionfs mount.

**Comment by Werkov** [comment] 2022-06-09 14:57
What systemd unit does the unionfs-fuse process belong to? (And in what cgroup it resides?)

**Comment by DUOLabs333** [comment] 2022-06-09 14:58
It doesn't have a unit, just one process in `session-1.scope`.

**Comment by DUOLabs333** [comment] 2022-06-09 15:10
I use `SIGTERM`. It shouldn't matter which one is killed first.

**Comment by Werkov** [comment] 2022-06-10 08:58
The `session-1.scope` termination by systemd should do the same.

At this stage, I can recommend to try obtaining list of processes in the cgroup (if `OnFailure=` above didn't work, then it appears a periodic sampling may come to help). I.e. this should tell us whether systemd mishandles emptiness notification (and thus times out), or there are still some processes surviving after `SIGTERM`.

**Comment by DUOLabs333** [comment] 2022-06-13 14:35
I added `/etc/systemd/system/session-1.scope.d/99-debug.conf`
with
```
[Unit]
KillSignal=SIGKILL
```
but it doesn't work --- there is still a timeout.

**Comment by Werkov** [comment] 2022-06-13 14:39
`KillSignal=` belongs to `[Scope]` section, it's nop in `[Unit]`.

**Comment by DUOLabs333** [comment] 2022-06-13 14:42
It works! Of course, this is just a bandage over the problem.

**Comment by Werkov** [comment] 2022-06-13 14:56
So, there's a process in your scope that doesn't respond to `SIGTERM` sent by PID 1 but only (unsurprisingly) `SIGKILL`. (And also to `SIGTERM` [sent manually](https://github.com/systemd/systemd/issues/23501#issuecomment-1151249314).) Correct?

How do you find out the PID to kill manually? If you list `/sys/fs/cgroup/user.slice/user-$UID.slice/session-$SID.scope/cgroup.procs`, is the same PID visible there?

**Comment by Werkov** [comment] 2022-06-13 15:06
I'm confused, I was referring to your previous comments where you said the manual killing of process(es) within the scope prevented the timeout. So [my questions](https://github.com/systemd/systemd/issues/23501#issuecomment-1154029462) referred to that situation.
(That's currently the only idea I have now how to relate this to a bug within systemd. Otherwise, I'd claim that it's the problem with the process not responding to SIGTERM or insufficient timeout.)

**Comment by DUOLabs333** [comment] 2022-06-13 15:12
Ok, so I figured out that the problem was from my containers. I stopped all of them and tried to narrow down what does my containers do that causes the timeout. I figured out that having `/sys` mounted on top of unionfs-fuse (which is what all my containers do) causes a timeout. I didn't actually go through all the PIDs, but it was trial-and-error (with a lot of restarting).

**Comment by DUOLabs333** [comment] 2022-06-13 19:42
Actually, it seems that `SIGKILL` doesn't work either.

**Comment by DUOLabs333** [comment] 2022-07-01 02:14
I'm not sure why systemd does this, or if there's a setting to turn it off.

**Comment by poettering** [comment] 2022-07-04 20:40
my educated guess: the processing backing that fuse mount is killed too early or so, hence when accessing cgroupfs (i.e. `/sys/fs/cgroup/…`) in order to enumerate the processes to kill we'll hang, because that pass after all must be resolved left to right, i.e. from the root fs down. And if accesses to the root fs hang then everything hangs...

**Comment by poettering** [comment] 2022-07-04 20:42
either way, i think we can close this, this appears unlikely to have anything to do with systemd, but is caused by icky fuse stuff.

**Closed as completed by poettering** 2022-07-04 20:42 UTC
Labels: cgroups, pid1
