### ISSUE TITLE
systemd-cryptenroll: add cryptsetup like --key-file option to specify a key-file instead of password

### ISSUE THREAD

**Issue by crestfalln** [systemd/systemd#23295] opened 2022-05-07 09:19 UTC
**Is your feature request related to a problem? Please describe.**
Right now it is not possible to use key-files for decryption purposes, I have been using the PASSWORD env variable but that's a subpar solution.

**Describe the solution you'd like**
A --key-file option like that in cryptsetup would be great.

**The systemd version you checked that didn't have the feature you are asking for**
250

**Comment by josephlr** [comment] 2022-05-08 01:38
I would also be interested in this feature, as it would allow for easier and more secure automated disk encryption setup.

Ideally, you would be able to do `cryptsetup luksFormat` using a random keyfile, and then use `systemd-cryptenroll` to enroll recovery / TPM2 / password credentials, without the user needing to type their password in multiple times. It could look something like:
```bash
# The keyfile already has high entropy, so set minimum PBKDF settings
cryptsetup luksFormat --key-file=/path/to//keyfile /dev/sda5
# Enroll a human-readable Recovery Key
systemd-cryptenroll --key-file=/path/to//keyfile --recovery-key /dev/sda5
# Enroll a TPM2-based protector
systemd-cryptenroll --key-file=/path/to//keyfile --tpm2-device=auto --tpm2-pcrs=7 /dev/sda5
# Only now, enroll as password and require user input.
# This might be later in the install process (during account creation). 
systemd-cryptenroll --key-file=/path/to//keyfile --password /dev/sda5
````
where `/path/to//keyfile` might be on a tmpfs or similar.

**Comment by crestfalln** [comment] 2022-05-09 17:05
@poettering I am asking for the ability to use a key-file(binary or human-readable) to enroll other tokens/keys, one way of doing this would be via a `--key-file` option. 
Right now I am reading the key-file to the `PASSWORD` env variable to achieve this, but the discussion in issue #20955 discourages such use.
I also tried passing the key-file via stdin but it doesn't seem to work.
This doesn't work for me. 
```sh
systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=0+1+7 /dev/sda1 < path-to-keyfile
``` 
The above command just hangs without doing or printing anything and must be killed with C-c. Is this the intended functionality?

**Comment by josephlr** [comment] 2022-05-09 19:43
Should this be merged with https://github.com/systemd/systemd/issues/20961 ?

**Comment by josephlr** [comment] 2022-05-09 19:56
It might be reasonable to use `--unlock-file` (or similar) for passing in non-interactive secret data to _unlock_ the drive. Then we could reserve `--key-file` for a future use case of _enrolling_ a binary cryptographic key.

I think this makes the intent clearer to the user. It avoids confusing key _enrollment_ with just using a key to unlock a drive.

 An alternative approach could be having an option to directly read the unlock material from stdin, something like `--unlock-stdin`. But I think the approach of specifying an unlock file is more idiomatic and easier for users to understand.

**Comment by poettering** [comment] 2022-05-10 08:58
Ah, yeah, so this sounds like the same usecase then, and it does make sense to me. and yeah, an --unlock-file= or so thing does make sense to me

**Comment by poettering** [comment] 2022-05-10 09:01
And yes, let's close this as duplicate of #20961

**Closed as completed by poettering** 2022-05-10 09:01 UTC
Labels: RFE 🎁, cryptsetup, duplicate
