### ISSUE TITLE
weekly persistent timer seem to hang

### ISSUE THREAD

**Issue by asavah** [systemd/systemd#8637] opened 2018-04-02 00:05 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with
master @ 34bfb98

### Used distribution

custom, arm

### In case of bug report: Expected behaviour you didn't see

Weekly persistent timers work.

### In case of bug report: Unexpected behaviour you saw
Example timer, service and explanation below.
```
systemctl --type timer
UNIT                         LOAD   ACTIVE   SUB     JOB   DESCRIPTION
fstest.timer                 loaded inactive dead    start timer test
systemd-tmpfiles-clean.timer loaded active   waiting       Daily Cleanup of Temporary Directories
```
```
systemctl list-timers --all
NEXT LEFT LAST                          PASSED    UNIT                         ACTIVATES
n/a  n/a  n/a                           n/a       fstest.timer                 fstest.service
n/a  n/a  Mon 2018-04-02 02:49:39 EEST  26min ago systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service
```
```
systemctl status fstest.timer
● fstest.timer - timer test
   Loaded: loaded (/usr/lib/systemd/system/fstest.timer; enabled; vendor preset: disabled)
   Active: inactive (dead)
  Trigger: n/a
```
### In case of bug report: Steps to reproduce the problem
Actually stumbled into this while investigating why fstrim.service from util-linux did not work.
https://github.com/karelzak/util-linux/blob/master/sys-utils/fstrim.timer
https://github.com/karelzak/util-linux/blob/master/sys-utils/fstrim.service.in

Example fstest.timer:
```
[Unit]
Description=timer test

[Timer]
OnCalendar=weekly
AccuracySec=1h
Persistent=true

[Install]
WantedBy=timers.target
```
Corresponding fstest.service unit:
```
[Unit]
Description=timer test service

[Service]
Type=oneshot
ExecStart=/bin/echo "me workZ"
```

Additional symptoms:
`systemctl enable --now fstest.timer` hangs indefinitely, ctrl-c is needed ...
If I try `systemctl start fstest.service` while the timer is enabled it hangs too.
`systemctl disable fstest.timer` does not help, it's still shown as `fstest.timer                 loaded inactive dead    start timer test` , systemctl still hangs if I try starting it.
Only disabling the timer and rebooting the systems allow the static test.service unit to be started,
daemon-reload, stop timer and etc do not help, only reboot does.

/var/lib/systemd/timers/stamp-*blah is not created.

Adding RemainAfterExit=no to the service does not help (it's the default anyway).

I have a system with an older build @ a6d09d9 and it works fine.

**Comment by poettering** [comment] 2018-04-10 12:47
If "systemctl start fstest.timer" hangs for you, then this suggests that some dependency of the timer (which includes any mount units necessary for /var/lib/systemd/timers/) is enqueued and not immediately available.

Please run "systemctl list-jobs" in another terminal, and have a look at what is in job queue when this hangs. my educated guess is that something is wrong with your /etc/fstab, i.e. a mount for /var/lib/systemd/timers cannot be established...

**Comment by asavah** [comment] 2018-04-10 14:16
AFAIK nothing is wrong with fstab.

```
# fstab automatically generated for rpi3
#<dev>	<mount point>	<type>	<options>	<dump>	<pass>
/dev/mmcblk0p1	/boot	vfat	ro,defaults	0	0
/dev/mmcblk0p2	/	ext4	defaults,noatime	0	0
/dev/mmcblk0p3	/home	ext4	defaults,noatime	0	0
nas2:/media/nas	/media/nas	nfs4	auto,x-systemd.automount,timeo=14,async,noatime,nodiratime,nocto,hard,retry=30,rsize=32768,wsize=32768	0	0
```

```
 mount
/dev/mmcblk0p2 on / type ext4 (rw,noatime,data=ordered)
devtmpfs on /dev type devtmpfs (rw,relatime,size=344752k,nr_inodes=86188,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
systemd-1 on /media/nas type autofs (rw,relatime,fd=32,pgrp=1,timeout=0,minproto=5,maxproto=5,direct)
mqueue on /dev/mqueue type mqueue (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
configfs on /sys/kernel/config type configfs (rw,relatime)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev)
/dev/mmcblk0p1 on /boot type vfat (ro,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro)
/dev/mmcblk0p3 on /home type ext4 (rw,noatime,data=ordered)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,size=69972k,mode=700)
nas2:/media/nas on /media/nas type nfs4 (rw,noatime,nodiratime,vers=4.2,rsize=32768,wsize=32768,namlen=255,hard,nocto,proto=tcp,timeo=14,retrans=2,sec=sys,clientaddr=SNIP,local_lock=none,addr=SNIP)
```

```
systemctl enable --now fstrim.timer
Created symlink /etc/systemd/system/timers.target.wants/fstrim.timer → /usr/lib/systemd/system/fstrim.timer.
#"hangs" here
```

```
systemctl list-jobs
JOB UNIT                           TYPE  STATE  
474 systemd-tmpfiles-clean.service start waiting
 50 systemd-time-wait-sync.service start running
483 fstrim.timer                   start waiting
 48 time-sync.target               start waiting

4 jobs listed.
```

```
strace -v -p 3445
strace: Process 3445 attached
ppoll([{fd=3, events=POLLIN}], 1, NULL, NULL, 8
```

"hung" systemctl seems to be polling dbus socket, like waiting for a message or something

**Comment by poettering** [comment] 2018-04-10 15:25
The relevant line is this:

```
 50 systemd-time-wait-sync.service start running
```

Appears to be a duplicate of #8683

**Closed as completed by poettering** 2018-04-10 15:25 UTC
Labels: pid1, duplicate
