### ISSUE TITLE
Feature Request: Release package signing

### ISSUE THREAD

**Issue by g4jc** [systemd/systemd#4586] opened 2016-11-05 16:35 UTC
### Submission type

  - [ ] Bug report
  - [*] Request for enhancement (RFE)

----

Hello,
There is currently no way to verify the complete integrity of the source tarball releases. Please consider signing your release packages so that downstream maintainers can verify the sources prior to packaging.

See here for how-to and complete details:
https://wiki.debian.org/Creating%20signed%20GitHub%20releases

Thank you

**Comment by mbiebl** [comment] 2016-11-05 16:36
Duplicate of
https://github.com/systemd/systemd/issues/2926

**Closed as completed by mbiebl** 2016-11-05 16:36 UTC
Labels: duplicate
