### ISSUE TITLE
Document intersection of nss-myhostname and nss-resolve

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#1605] opened 2015-10-18 21:14 UTC
While testing out nss-resolve, I discovered that after enabling it, myhostname becomes useless:
- *.localhost maps to 127.0.0.1 and ::1
- The local hostname resolves to the public addresses of the host
- gateway resolves to the routing gateway address

All three tested with `getent ahosts $1`, having disabled myhostname. Has nss-myhostname become superfluous when nss-resolve is installed? Or is this result only sometimes applicable? The documentation doesn't say, and in particular `nss-resolve(8)` does not mention that one should expect this behavior.

systemd 227-2 from debian (plus enabling nss-resolve).

**Comment by poettering** [comment] 2015-10-19 18:34
My intention is to eventually remove nss-myhostname I guess. 

Right now nss-myhostname has some benefit over nss-resolve however, as it is available before resolved is started up. But I am not sure this actually matters much, as I think it's not really expected that these names are resolvable that early.

That said, I figure we should drop nss-myhostname only when resolved does DNSSEC so that we can clearly tell people that resolved is the way to go.

**Comment by poettering** [comment] 2016-06-16 12:29
#1280 was a duplicate of this one, and has some more discussion about this.

**Closed as completed** 2017-07-03 14:11 UTC
Labels: resolve, documentation, nss

**Comment by flokli** [comment] 2020-05-23 13:04
> My intention is to eventually remove nss-myhostname I guess.
> 
> Right now nss-myhostname has some benefit over nss-resolve however, as it is available before resolved is started up. But I am not sure this actually matters much, as I think it's not really expected that these names are resolvable that early.
> 
> That said, I figure we should drop nss-myhostname only when resolved does DNSSEC so that we can clearly tell people that resolved is the way to go.

IMHO, there's valid reasons to keep `nss-myhostname`. Resolving the local hostname, without having to bake it into `/etc/hosts` should still work, even when people don't use resolved, or resolved is down

For example, people could run applications in a separate network namespace, where everything goes via a VPN, and don't want to have their DNS requests leak via `nss-resolved`. In these situations, people might want to just use the `dns` nss module (which reads `/etc/resolv.conf`, pointing to another resolver), but local hostname and fqdn resolution could still be handled by `nss-myhostname`.
