### ISSUE TITLE
DNSSEC started failing after a while

### ISSUE THREAD

**Issue by Stebalien** [systemd/systemd#5639] opened 2017-03-26 04:26 UTC
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> systemd 233
+PAM -AUDIT -SELINUX -IMA -APPARMOR -SMACK -SYSVINIT -UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN default-hierarchy=hybrid
 
### Used distribution

Arch Linux (custom systemd build but no additional patches)

### Description

After coming back to my computer today after some time away, I was unable to perform any DNS lookups. Looking through my logs, I saw the following:

1. A bunch of mDNS messages.

```
Mar 25 14:44:29 bistromath systemd-resolved[322]: Got mDNS UDP packet on unknown scope. Ignoring.
...
Mar 25 16:16:26 bistromath systemd-resolved[322]: Got mDNS UDP packet on unknown scope. Ignoring.
````

2. A single degraded feature set message towards the end of the mDNS messages. Given that this is Google's server and it has been working for a while at this point, I think the degraded feature set detection feature is being overzealous.

```
Mar 25 15:27:48 bistromath systemd-resolved[322]: Using degraded feature set (UDP+EDNS0+DO) for DNS server 8.8.8.8.
```

3. And then a *ton* of DNSSEC failures (4101 to be exact). Note, these started 40 minutes *after* the degraded feature set message so they may not be related. However, I'm not actually at my computer at this point so it may have taken 40 minutes for the DNS cache entries of the domains my computer polls in the background to expire.

```
Mar 25 16:17:16 bistromath systemd-resolved[322]: DNSSEC validation failed for question  [omitted domain] IN SOA: incompatible-server
Mar 25 16:17:16 bistromath systemd-resolved[322]: DNSSEC validation failed for question  [omitted domain] IN A: incompatible-server
...
Mar 25 20:50:12 bistromath systemd-resolved[322]: DNSSEC validation failed for question  [omitted domain] IN A: incompatible-server
```

(with the occasional mDNS message mixed in).

This went away as soon as I restarted systemd-resolved.

#### Full Log

https://gist.github.com/95f5470f1e7a0bdae37ebd9382927174

#### Status

(After restart; sorry, I didn't think to run this or statistics before restarting)

```
Global
         DNS Servers: 8.8.8.8
          DNSSEC NTA: 10.in-addr.arpa
                      16.172.in-addr.arpa
                      168.192.in-addr.arpa
                      17.172.in-addr.arpa
                      18.172.in-addr.arpa
                      19.172.in-addr.arpa
                      20.172.in-addr.arpa
                      21.172.in-addr.arpa
                      22.172.in-addr.arpa
                      23.172.in-addr.arpa
                      24.172.in-addr.arpa
                      25.172.in-addr.arpa
                      26.172.in-addr.arpa
                      27.172.in-addr.arpa
                      28.172.in-addr.arpa
                      29.172.in-addr.arpa
                      30.172.in-addr.arpa
                      31.172.in-addr.arpa
                      corp
                      d.f.ip6.arpa
                      home
                      internal
                      intranet
                      lan
                      local
                      private
                      test

Link 3 (wlan0)
      Current Scopes: none
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: yes
    DNSSEC supported: yes

Link 2 (eth0)
      Current Scopes: none
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: yes
    DNSSEC supported: yes
```

#### Resolved Config

```
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.
#
# Entries in this file show the compile time defaults.
# You can change settings by editing this file.
# Defaults can be restored by simply deleting this file.
#
# See resolved.conf(5) for details

[Resolve]
DNS=8.8.8.8
FallbackDNS=8.8.8.8 8.8.4.4 2001:4860:4860::8888 2001:4860:4860::8844
LLMNR=no
DNSSEC=yes
Cache=yes
#DNSStubListener=udp
```

**NOTE: ** I've commented on the LLMNR discrepancy in #4022 but I don't think it's related.

#### Other

* I'm *not* using systemd-network (the service is disabled and stopped). Instead, I'm using Network Manager. However, I've configured Network Manager to *not* manage my DNS.

* As far as I can tell, there are no other relevant drop-in configs.

**Comment by Stebalien** [comment] 2017-03-26 05:17
Small update: Even after restarting systemd-resolved, I'm still seeing lots of "Got mDNS UDP packet on unknown scope" messages.

Edit: Probably just #5530.

**Comment by poettering** [comment] 2017-03-29 14:44
(ignore the mdns thing, it doesn't matter much, and it's probably caused because you run avahi together with resolved's mdns code?)

**Comment by poettering** [comment] 2017-03-29 14:46
most likely you experienced some heavier traffic loss while resolved tried to resolve something. It thus downgraded to lower dnssec modes, until the point where dnssec is not available anymore, but you configure dnssec mode to strict, hence the problem.

Any chance you can run resolved with "SYSTEMD_LOG_LEVEL=debug" set, and then reproduce the issue and provide me with a log? If you don't want to paste the full logs here, feel free to send them to me personally.

**Comment by Stebalien** [comment] 2017-03-29 15:24
> (ignore the mdns thing, it doesn't matter much, and it's probably caused because you run avahi together with resolved's mdns code?)

Yes.

> most likely you experienced some heavier traffic loss while resolved tried to resolve something

Given my internet service (AT&T ADSL), that's not surprising.

> It thus downgraded to lower dnssec modes

Unless I'm mistaken, the actionable items are:

1. Don't downgrade after establishing what the server supports (unless feature detection can have false positives?).
2. Never downgrade DNSSEC if required.
3. Possibly cache repeated DNSSEC failures to avoid accidentally DOSing a DNS server.

> Any chance you can run resolved with "SYSTEMD_LOG_LEVEL=debug" set, and then reproduce the issue and provide me with a log? If you don't want to paste the full logs here, feel free to send them to me personally.

Sure. However, this doesn't happen vary often (I've now seen it happen twice) so it may be a while.

**Comment by Stebalien** [comment] 2017-03-30 06:57
Statistics (because I didn't get them last time):

```
DNSSEC supported by current servers: yes

Transactions
Current Transactions: 0
  Total Transactions: 1766

Cache
  Current Cache Size: 194
          Cache Hits: 784
        Cache Misses: 1095

DNSSEC Verdicts
              Secure: 387
            Insecure: 1254
               Bogus: 1
       Indeterminate: 0
```

```
Mar 29 22:57:37 bistromath systemd-resolved[18608]: Using degraded feature set (UDP+EDNS0+DO) for DNS server 8.8.8.8.
Mar 29 23:05:28 bistromath systemd-resolved[18608]: DNSSEC validation failed for question lambda-the-ultimate.org IN DS: no-signature
Mar 29 23:05:28 bistromath systemd-resolved[18608]: DNSSEC validation failed for question lambda-the-ultimate.org IN SOA: no-signature
Mar 29 23:05:28 bistromath systemd-resolved[18608]: DNSSEC validation failed for question lambda-the-ultimate.org IN A: no-signature
Mar 29 23:44:10 bistromath systemd-resolved[18608]: DNSSEC validation failed for question t.co IN DS: failed-auxiliary
Mar 29 23:44:10 bistromath systemd-resolved[18608]: DNSSEC validation failed for question t.co IN SOA: failed-auxiliary
Mar 29 23:44:10 bistromath systemd-resolved[18608]: DNSSEC validation failed for question t.co IN A: failed-auxiliary
Mar 29 23:44:11 bistromath systemd-resolved[18608]: DNSSEC validation failed for question t.co IN DS: failed-auxiliary
Mar 29 23:44:11 bistromath systemd-resolved[18608]: DNSSEC validation failed for question t.co IN SOA: failed-auxiliary
Mar 29 23:44:11 bistromath systemd-resolved[18608]: DNSSEC validation failed for question t.co IN A: failed-auxiliary
Mar 29 23:44:27 bistromath systemd-resolved[18608]: DNSSEC validation failed for question t.co IN DS: failed-auxiliary
Mar 29 23:44:27 bistromath systemd-resolved[18608]: DNSSEC validation failed for question t.co IN SOA: failed-auxiliary
Mar 29 23:44:27 bistromath systemd-resolved[18608]: DNSSEC validation failed for question t.co IN A: failed-auxiliary
Mar 29 23:44:28 bistromath systemd-resolved[18608]: DNSSEC validation failed for question t.co IN DS: failed-auxiliary
Mar 29 23:44:28 bistromath systemd-resolved[18608]: DNSSEC validation failed for question t.co IN SOA: failed-auxiliary
Mar 29 23:44:28 bistromath systemd-resolved[18608]: DNSSEC validation failed for question t.co IN A: failed-auxiliary
```

**Comment by poettering** [comment] 2017-03-30 08:16
> Never downgrade DNSSEC if required.

Hmm, since 233 we don't actually downgrade below DNSSEC mode on packet loss anymore if strict DNSSEC mode is selected. Which suggests we downgraded for another reason (for example, because the server indicated to us that it doesn't do DNSSEC). To figure out the reason for the downgrade we'd need the requested logs.

**Comment by poettering** [comment] 2017-03-30 08:21
> Don't downgrade after establishing what the server supports (unless feature detection can have false positives?).

Well, there's no concept of "establishing what the server supports". All we can do is issue queries as we go, analyze the responses, and downgrade whenever we have reason to. On many servers specific lookups might work, while others might not, and if the ones working are issued first we'll downgrade step-by-step over time. Cases where some lookups work but others don't are those where the server enforces unannounced size limits, or where it acts as DNS proxy for some domains but implements DNS natively for others (many home routers do that, to provide access to the router's config page).

**Comment by Stebalien** [comment] 2017-03-30 17:57
> To figure out the reason for the downgrade we'd need the requested logs.

Those are all the logs I have (`SYSTEMD_LOG_LEVEL=debug` enabled). Is there something else I need to do to get debugging information?

> Well, there's no concept of "establishing what the server supports".

I see. For DNSSEC, I'm guessing that the reasoning here is: if a server can't provide DNSSEC records for *all* queries, we might as well disable DNSSEC.

> Which suggests we downgraded for another reason (for example, because the server indicated to us that it doesn't do DNSSEC). 

Or my ISP is MITMing my DNS traffic; this may have been what happened the first time as I was at a coffee shop and captive portals tend to be pretty invasive. If configured to require DNSSEC, resolved should probably avoid downgrading *regardless* of what the server says as it can't operate otherwise.

**Comment by Stebalien** [comment] 2017-03-30 18:30
(of course, setting `MaxLogStore=notice` in `journald.conf` might be an issue...)

**Comment by poettering** [comment] 2017-03-31 13:33
any chance you can set MaxLogStore=debug and get the debug logs? otherwise i am not sure what we can do about this

**Comment by Stebalien** [comment] 2017-03-31 14:30
I have now but it may take a while to reproduce.

**Comment by poettering** [comment] 2019-07-10 14:26
Let's close this, since the lack of response.

**Closed as completed by poettering** 2019-07-10 14:26 UTC
Labels: resolve, needs-reporter-feedback ❓

**Comment by Stebalien** [comment] 2019-07-10 15:59
Sorry about that. I haven't seen this in years so yeah, it's probably no longer an issue.
