### ISSUE TITLE
documented `systemd-umount WHERE` does not work

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#6758] opened 2017-09-06 15:17 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

systemd-233-6.fc26.x86_64

### Used distribution

Fedora 26

### In case of bug report: Expected behaviour you didn't see

`man systemd-umount` says I can do `systemd-umount [OPTIONS...] WHERE...`.  But I can't.

I expected it to be equivalent to `systemctl stop $(systemd-escape -p / -suffix=.mount)`  E.g. (I denied permission):

```
$ systemctl stop -- $(systemd-escape -p / --suffix=mount)
Failed to stop -.mount: Access denied
See system logs and 'systemctl status -- -.mount' for details.
```

### In case of bug report: Unexpected behaviour you saw

`Discovery only supported for block devices, don't know what to do.`

(This is referring to `--discover`.  Note it's documented as being implied for `systemd-mount`, when only one argument (WHAT) is given.)

### In case of bug report: Steps to reproduce the problem

`systemd-umount /`

**Comment by poettering** [comment] 2017-09-06 15:37
duplicate of #6756

**Closed as completed by poettering** 2017-09-06 15:37 UTC
Labels: duplicate, mount
