### ISSUE TITLE
Host resolution fails from time to time

### ISSUE THREAD

**Issue by brecht-yperman-tb** [systemd/systemd#20548] opened 2021-08-26 13:38 UTC
**systemd version the issue has been seen with**
 > 248.7

**Used distribution**
 > Fedora 34

**Linux kernel version used** (`uname -a`)

 > `5.13.12-200.fc34.x86_64`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Host resolution keeps working

**Unexpected behaviour you saw**
 > From time to time, host resolution stops working. It seems to remove the entries from the cache, but makes no effort to retrieve new values.

**Steps to reproduce the problem**
 > I have no idea what's causing it and cannot find any scenario to consistently reproduce this.  Our TTL was set fairly low (60s, but changing to 84600 did not fix it). We recently switched from using OpenFortiVPN on a guest network (no issues there, but this resulted in a different Link with a DNS Domain set) to a secured members network with a VPN tunnel on the VLAN (I'm unsure about how it's actually set up). I see `Using degraded feature set UDP instead of UDP+EDNS0 for DNS server 10.0.50.1.` in the logs, but that also shows up using OpenFortiVPN (where the errors don't happen).

**Additional program output to the terminal or log subsystem illustrating the issue**

Here is the status
```text
Global
       Protocols: LLMNR=resolve -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (wlp59s0)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 10.0.50.1
       DNS Servers: 10.0.50.1 1.1.1.1

Link 3 (virbr0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```

First there's a successful call
```text
Got message type=method_call sender=:1.207 destination=org.freedesktop.resolve1 path=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=ResolveHostname cookie=2 reply_cookie=0 signature=isit error-name=n/a error-message=n/a
idn2_lookup_u8: jenkins.trustbuilder.io → jenkins.trustbuilder.io
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixProcessID cookie=19 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.206 path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=19 signature=u error-name=n/a error-message=n/a
D-Bus hostname resolution request from client PID 7628 (resolvectl) with UID 1000
Looking up RR for jenkins.trustbuilder.io IN A.
Looking up RR for jenkins.trustbuilder.io IN AAAA.
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=20 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetNameOwner cookie=21 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.206 path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=21 signature=s error-name=n/a error-message=n/a
Switching to DNS server 10.0.50.1 for interface wlp59s0.
Cache miss for jenkins.trustbuilder.io IN AAAA
Firing regular transaction 44788 for <jenkins.trustbuilder.io IN AAAA> scope dns on wlp59s0/* (validate=yes).
Using feature level UDP+EDNS0 for transaction 44788.
Using DNS server 10.0.50.1 for transaction 44788.
Announcing packet size 512 in egress EDNS(0) packet.
Emitting UDP, link MTU is 1500, socket MTU is 0, minimal MTU is 40
Sending query packet with id 44788 of size 52.
Cache miss for jenkins.trustbuilder.io IN A
Firing regular transaction 65188 for <jenkins.trustbuilder.io IN A> scope dns on wlp59s0/* (validate=yes).
Using feature level UDP+EDNS0 for transaction 65188.
Using DNS server 10.0.50.1 for transaction 65188.
Announcing packet size 512 in egress EDNS(0) packet.
Emitting UDP, link MTU is 1500, socket MTU is 0, minimal MTU is 40
Sending query packet with id 65188 of size 52.
Got message type=method_return sender=org.freedesktop.DBus destination=:1.206 path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=20 signature= error-name=n/a error-message=n/a
Match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0=':1.207' successfully installed.
Received dns UDP packet of size 57, ifindex=2, ttl=0, fragsize=0
Processing incoming packet of size 57 on transaction 65188 (rcode=SUCCESS).
Verified we get a response at feature level UDP from DNS server 10.0.50.1.
Server doesn't support EDNS(0) properly, downgrading feature level...
Using degraded feature set UDP instead of UDP+EDNS0 for DNS server 10.0.50.1.
Server feature level is now lower than when we began our transaction. Restarting with new ID.
Transaction 65188 is now 26000.
Cache miss for jenkins.trustbuilder.io IN A
Firing regular transaction 26000 for <jenkins.trustbuilder.io IN A> scope dns on wlp59s0/* (validate=yes).
Using feature level UDP for transaction 26000.
Emitting UDP, link MTU is 1500, socket MTU is 1500, minimal MTU is 40
Sending query packet with id 26000 of size 41.
Received dns UDP packet of size 145, ifindex=2, ttl=0, fragsize=0
Processing incoming packet of size 145 on transaction 44788 (rcode=NXDOMAIN).
Server returned error NXDOMAIN in EDNS0 mode, retrying transaction with reduced feature level UDP (DVE-2018-0001 mitigation)
Retrying transaction 44788.
Cache miss for jenkins.trustbuilder.io IN AAAA
Firing regular transaction 44788 for <jenkins.trustbuilder.io IN AAAA> scope dns on wlp59s0/* (validate=yes).
Using feature level UDP for transaction 44788.
Emitting UDP, link MTU is 1500, socket MTU is 1500, minimal MTU is 40
Sending query packet with id 44788 of size 41.
Received dns UDP packet of size 57, ifindex=2, ttl=0, fragsize=0
Processing incoming packet of size 57 on transaction 26000 (rcode=SUCCESS).
Added positive unauthenticated non-confidential cache entry for jenkins.trustbuilder.io IN A 60s on wlp59s0/INET/10.0.50.1
Regular transaction 26000 for <jenkins.trustbuilder.io IN A> on scope dns on wlp59s0/* now complete with <success> from network (unsigned; non-confidential).
Received dns UDP packet of size 134, ifindex=2, ttl=0, fragsize=0
Processing incoming packet of size 134 on transaction 44788 (rcode=NXDOMAIN).
Added NXDOMAIN cache entry for jenkins.trustbuilder.io IN ANY 208s
Regular transaction 44788 for <jenkins.trustbuilder.io IN AAAA> on scope dns on wlp59s0/* now complete with <rcode-failure> from network (unsigned; non-confidential).
Freeing transaction 26000.
Sent message type=method_return sender=n/a destination=:1.207 path=n/a interface=n/a member=n/a cookie=22 reply_cookie=2 signature=a(iiay)st error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RemoveMatch cookie=23 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Freeing transaction 44788.
```
A later failing call
```text
Got message type=method_call sender=:1.211 destination=org.freedesktop.resolve1 path=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=ResolveHostname cookie=2 reply_cookie=0 signature=isit error-name=n/a error-message=n/a
idn2_lookup_u8: jenkins.trustbuilder.io → jenkins.trustbuilder.io
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixProcessID cookie=34 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.206 path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=34 signature=u error-name=n/a error-message=n/a
D-Bus hostname resolution request from client PID 7798 (resolvectl) with UID 1000
Looking up RR for jenkins.trustbuilder.io IN A.
Looking up RR for jenkins.trustbuilder.io IN AAAA.
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=35 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetNameOwner cookie=36 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.206 path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=36 signature=s error-name=n/a error-message=n/a
Removing cache entry for github-cloud.s3.amazonaws.com IN CNAME (expired 17s ago)
Removing cache entry for s3-w.us-east-1.amazonaws.com IN A (expired 17s ago)
Removing cache entry for locprod2-elb-us-west-2.prod.mozaws.net IN A (expired 16s ago)
Removing cache entry for location.services.mozilla.com IN CNAME (expired 16s ago)
Removing cache entry for jenkins.trustbuilder.io IN A (expired 11s ago)
Removing cache entry for analytics-collector-28944298.us-east-1.elb.amazonaws.com IN AAAA (expired 2s ago)
NXDOMAIN cache hit for jenkins.trustbuilder.io IN AAAA
Regular transaction 9036 for <jenkins.trustbuilder.io IN AAAA> on scope dns on wlp59s0/* now complete with <rcode-failure> from cache (unsigned; non-confidential).
NXDOMAIN cache hit for jenkins.trustbuilder.io IN A
Regular transaction 5301 for <jenkins.trustbuilder.io IN A> on scope dns on wlp59s0/* now complete with <rcode-failure> from cache (unsigned; non-confidential).
Freeing transaction 9036.
Freeing transaction 5301.
Sent message type=error sender=n/a destination=:1.211 path=n/a interface=n/a member=n/a cookie=37 reply_cookie=2 signature=s error-name=org.freedesktop.resolve1.DnsError.NXDOMAIN error-message='jenkins.trustbuilder.io' not found
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RemoveMatch cookie=38 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.206 path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=35 signature= error-name=n/a error-message=n/a
```

The following commands were issued at a later stage, but show it resolving properly first, and then all of a sudden no longer.

```
[brechtyperman@localhost ~]$ resolvectl query jenkins.trustbuilder.io
jenkins.trustbuilder.io: 10.0.50.163           -- link: wlp59s0

-- Information acquired via protocol DNS in 1.5ms.
-- Data is authenticated: no; Data was acquired via local or encrypted transport: no
-- Data from: cache
```

```
[brechtyperman@localhost ~]$ dig jenkins.trustbuilder.io

; <<>> DiG 9.16.20-RH <<>> jenkins.trustbuilder.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8670
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;jenkins.trustbuilder.io.	IN	A

;; ANSWER SECTION:
jenkins.trustbuilder.io. 6243	IN	A	10.0.50.163

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Thu Aug 26 16:14:06 CEST 2021
;; MSG SIZE  rcvd: 68
```

```
[brechtyperman@localhost ~]$ dig jenkins.trustbuilder.io

; <<>> DiG 9.16.20-RH <<>> jenkins.trustbuilder.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 35163
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;jenkins.trustbuilder.io.	IN	A

;; AUTHORITY SECTION:
trustbuilder.io.	297	IN	SOA	ns-cloud-e1.googledomains.com. cloud-dns-hostmaster.google.com. 2 21600 3600 259200 300

;; Query time: 53 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Thu Aug 26 16:14:14 CEST 2021
;; MSG SIZE  rcvd: 145
```

```
[brechtyperman@localhost ~]$ resolvectl query jenkins.trustbuilder.io
jenkins.trustbuilder.io: resolve call failed: 'jenkins.trustbuilder.io' not found
```

**Comment by poettering** [comment] 2024-03-05 13:58
Your DNS server is simply broken. it returns NXDOMAIN for aaaa queries, while returning a successfully for A queries on the same name. That makes no sense.

**Comment by poettering** [comment] 2024-03-05 13:59
Duplicate of #22575

**Closed as completed by poettering** 2024-03-05 13:59 UTC
Labels: resolve
