### ISSUE TITLE
Support tmpfiles.d in user instances

### ISSUE THREAD

**Issue by Stebalien** [systemd/systemd#2208] opened 2015-12-21 18:09 UTC
This would be really useful for deleting old files from the trash, clearing the cache, clearing old downloads, recreating XDG directories, etc.

**Comment by killermoehre** [comment] 2016-09-26 10:49
I plus one this.
In my use case, I want to add a directory into $XDG_RUNTIME_DIR to hold sockets for ssh multiplexing. Since ssh can't create the directory by itself, I thought of systemd-tmpfiles could generate it.

**Comment by ayekat** [comment] 2017-10-05 17:58
I have made [a change][commit] that makes systemd-tmpfiles recognise `%U`, `%u` and `%h` as well, so this will allow using it in a user context a bit more easily.

That being said, tmpfiles still doesn't support environment variables like e.g. the `XDG_...` variables, so this doesn't entirely solve this problem yet (I'll wait with opening a pull request).


[commit]: https://github.com/ayekat/systemd/commit/4b23d4b97866611d89a0541a0df1c95341397f1b

**Comment by poettering** [comment] 2017-10-27 18:12
Duplicate of this: https://bugs.freedesktop.org/show_bug.cgi?id=88873

**Closed as completed** 2017-12-06 18:50 UTC
Labels: RFE 🎁, tmpfiles
