### ISSUE TITLE
[systemd-homed]: portable user avatar

### ISSUE THREAD

**Issue by malformed-c** [systemd/systemd#21644] opened 2021-12-06 18:37 UTC
**Is your feature request related to a problem? Please describe.**
Portable user's avatar to more clearly distinguish users

**Describe the solution you'd like**
New user property or support to everywhere used `~/.icon.face`

**Describe alternatives you've considered**
Placed my avatar in `/var/lib/AccountsService/icons/`

**The systemd version you checked that didn't have the feature you are asking for**
`systemd 249 (249.7-2-arch)
`

**Comment by AdrianVovk** [comment] 2021-12-06 19:31
Putting files _in_ the home dir (i.e. `~/.icon.face`) is impossible because all those files are encrypted. Creating arbitrary properties should already be supported, but I'm not sure if there's a good way to actually change these just yet

That said, creating a standard way to define a user's profile picture would be handy

**Comment by poettering** [comment] 2021-12-07 13:33
This definitely makes sense to have, and has been on the TODO list for a while, but it's not entirely trivial to do, it needs some thinking: i.e. we cant just allow user records to include megabytes of user jpegs, that we then provide everywhere.

One approach might be to extend the user record JSON stuff with another "section", which we could call "bulk" or so, which can contain "bulk" data like this, and that is only returned on explicit request, but never during regular enumeration. That way the user icon/avatar/image would be part of the user record, but clearly separated from the rest, so that we can strip it usually but pass it along when needed.

**Comment by shalzz** [comment] 2022-01-14 13:37
I have the home user record property `icon-name` set for a user as `coffee2`.
I expected gnome-shell/gdm to automatically set that as a user avatar reading the file from a standard location (For gnome it can be found here: `/usr/share/pixmaps/faces/coffee2.jpg`).
However that didn't happen.

**Comment by Tachi107** [comment] 2022-03-18 16:23
Is this a duplicate of #18323?

**Comment by poettering** [comment] 2024-01-30 16:15
Duplicate of #18323

**Closed as completed by poettering** 2024-01-30 16:15 UTC
Labels: RFE 🎁, homed
