### ISSUE TITLE
[RoutingPolicyRule] in its own .network file crashes systemd-networkd

### ISSUE THREAD

**Issue by amishmm** [systemd/systemd#9994] opened 2018-09-03 05:18 UTC
**systemd version the issue has been seen with**
> 239.0-2

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > I wanted to add a simple routing rule so I created 25-iprules.network file with a [RoutingPolicyRule] section.

> I took a modular approach where ip rules are in different file / network address configuration in other.

File: 25-iprules.network
> [RoutingPolicyRule]
> FirewallMark=0x103
> Table=103
> Priority=30000

File: 25-myeth0.network
> [Match]
> MACAddress=00:e0:4a:0a:1e:1f
> 
> [Network]
> ConfigureWithoutCarrier=true
> Address=192.168.0.2/24

**Unexpected behaviour you saw**
> It added the fwmark rule but did not configure the interface and system was without network. And systemd-networkd also crashed.

> \# ip ru l
> 0:      from all lookup local 
> 30000:  from all fwmark 0x103 lookup 103
> 32766:  from all lookup main 
> 32767:  from all lookup default

> \# ifconfig
> eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
>       inet6 fe80::2e1:4aff:fe0a:1e1f  prefixlen 64  scopeid 0x20<link>
>        ether 00:e0:4a:0a:1e:1f  txqueuelen 1000  (Ethernet)
>        RX packets 9002  bytes 677172 (661.3 KiB)
>        RX errors 0  dropped 45  overruns 0  frame 0
>        TX packets 518  bytes 48678 (47.5 KiB)
>        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

> \# journalctl logs
> Sep 03 08:50:10 amish systemd-networkd[4994]: Assertion 'IN_SET(link->state, LINK_STATE_SETTING_ADDRESSES, LINK_STATE_SETTING_ROUTES, LINK_STATE_FAILED, LINK_STATE_LINGER)' failed at .. /systemd-stable/src/network/networkd-link.c:812, function route_handler(). Aborting.
> Sep 03 08:50:11 amish systemd[1]: systemd-networkd.service: Main process exited, code=dumped, status=6/ABRT
> Sep 03 08:50:11 amish systemd[1]: systemd-networkd.service: Failed with result 'core-dump'.

**Steps to reproduce the problem**
> See above - simply add [RoutingPolicyRule] in its own file and restart systemd-networkd.

**Comment by amishxda** [comment] 2018-09-03 05:32
To be honest - this happened in my main server (where I can not do anymore testing because there was already downtime of more than 2 hours because of this issue and I do not want people shouting again!!).

But on my desktop I am not able to reproduce this.

But main server has 4 network cards and all cards were without IP addresses after I added 25-iprules.network and restarted systemd-networkd (i.e. systemd-networkd did not re-configure any card). Even rebooting did not resolve the issue.

No sooner I removed 25-iprules.network file - systemd-networkd started functioning properly.

**Comment by yuwata** [comment] 2018-09-03 05:41
The config file 25-iprules.network does not have `[Match]` (and `[Network]`) section... Is it intended?

**Comment by amishxda** [comment] 2018-09-03 05:49
Yes as I said .. i wanted that file just for setting IP RULE. I wanted to keep it separate from IP addresses network file.

Now I have added it to 25-eth0.network and its working.

But isnt it a bug somewhere where systemd-networkd crashes?

Is it compulsory to have [Match] and / or [Network] section to add a [RoutingPolicyRule]?

**Comment by yuwata** [comment] 2018-09-03 05:59
> But isnt it a bug somewhere where systemd-networkd crashes?

Yeah, at least, networkd should not crash event if .network file does not contain `[Match]` or other sections.

**Comment by yuwata** [comment] 2018-09-03 06:00
But as you already faced, I cannot reproduce the crash...

**Comment by amishxda** [comment] 2018-09-03 06:10
Ok I found a reason. (although still not aware of the cause of crash)

On my server the file 25-eth0.network is actually named 25-myeth0.network. (i know weird name)

So 25-iprules.network had higher priority (lexically).

And since it had no [Match] section it matched for all the nework interfaces.

And files 25-myeth0.network, 25-myeth1.network, etc. never got processed. And hence IP addresses were also never set on any interface.

But I am still not aware why Assertion failed

If developers can figure out from journalctl log above then it would be good. Otherwise its going to be difficult for me to test all settings again. (but I will try my best if I can)

**Comment by amishxda** [comment] 2018-09-04 16:31
After looking at the code a little bit. I believe two unrelated things have happened together. Making it look like one single issue / bug.

I have some routes set up by systemd-networkd (which systemd calls as local config - inside [Route] section of .network files) and some routes set up by some process (which systemd calls as foreign config).

I was also adding / deleting routes manually. (which is also considered as foreign config by systemd)

It seems that something triggered ASSERT failure but it was NOT related to 25-iprules.network file.

So we can try to find out what combination of local config and foreign config caused ASSERT failure. (but its going to be a huge trial and error)

**Coming back to this ISSUE**.

If you want a file with only [RoutingPolicyRule] section (and no [Match] or [Network] sections), then make it lowest priority file.

i.e. instead of 25-iprules.network, name it say 99-iprules.network.

This way files with [Match] and [Network] will be processed first and then the files without them will be processed.

Hence I am closing the issue.

**Closed as completed by amishxda** 2018-09-04 16:31 UTC
Labels: bug 🐛, network, cant-reproduce
