### ISSUE TITLE
Missing implementation for documented support for "file:/path/to/README.md" Documentation URIs

### ISSUE THREAD

**Issue by sten0** [systemd/systemd#21369] opened 2021-11-14 23:31 UTC
Freedesktop.org asserts the following:

* Documentation=
     - A space-separated list of URIs referencing documentation for this unit or its configuration. Accepted are only URIs of the types "http://", "https://", "file:", "info:", "man:". For more information about the syntax of these URIs, see uri(7). The URIs should be listed in order of relevance, starting with the most relevant. It is a good idea to first reference documentation that explains what the unit's purpose is, followed by how it is configured, followed by any other related documentation. This option may be specified more than once, in which case the specified list of URIs is merged. If the empty string is assigned to this option, the list is reset and all prior assignments will have no effect. ( https://www.freedesktop.org/software/systemd/man/systemd.unit.html )

however, support for this does not appear to exist
https://github.com/systemd/systemd/blob/095eaf7130f27b638e19f24363a01fca95fc5297/src/systemctl/systemctl-show.c#L768

If supporting README.md files as a valid documentation for `systemctl help foo` is undesirable, for example because it requires a pager supporting gz compression (Debian, and derivatives, systems), then please fix the misleading freedesktop.org documentation.

Regards,
Nicholas

P.S. The Debian bug associated with this issue is https://bugs.debian.org/999637

**Comment by poettering** [comment] 2021-11-15 08:46
"systemctl help" only displays man pages, nothing else. it's documented that way, did you check the man page?

The other URL types can be specified too, but are not processed by "systemctl help". instead, they are shown as clickable links in your terminal (if your terminal is new enough to support that), so that you can just click on them.

Typically HTML rendering is not fun in the terminal, you want to hand this off to a graphical browser, hence we don't initiate that from "systemctl help".

Hence, closing, this works as intended and is documented.

**Closed as completed by poettering** 2021-11-15 08:46 UTC
Labels: systemctl, not-a-bug

**Comment by mbiebl** [comment] 2021-11-15 14:58
I think the documentation as-is is pretty clear, that `systemctl help` only supports man pages.
I told @sten0 this in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=999637#10 where I quoted the relevant part of the man page.
man systemd.unit does list `file:/` as a valid option for `Documentation=`, but it doesn't say anything about its support in `systemctl help`.
So I think the documentation is consistent and properly reflects the current behaviour.
Which is why I closed the downstream bug report.

I asked @sten0 to file an upstream RFE issue, if he's convinced that `systemctl help` should handle anything besides man:

I'm not sure if it's doable in a sensible way. Maybe it could just call xdg-open. Dunno

**Comment by poettering** [comment] 2021-11-16 09:15
user experience of xdg-open is not that great I would say, since we can't sync on it, i.e. make sure we show one entry after the other. 

I think providing clickable links for non-man page URLs is th ebest approach, like we currently do: doing clickable links is absolutely the right choice for stuff that typically is hypertext anyway.

**Comment by mbiebl** [comment] 2021-11-16 12:26
Nod, I guess opening arbitrary files is simply not sensibly doable.

That said, could we improve the error message a bit?
```
"Can't show: file:/usr/share/doc/foo/README.md".
```
This reads a bit like `systemctl help` tried to open the file but failed for an unspecified reason.
Maybe explicitly say, that it is unsupported and only man pages can work?
