### ISSUE TITLE
Delay in wwn symmlink initialization for native NVMe devices 

### ISSUE THREAD

**Issue by aayushSID** [systemd/systemd#33054] opened 2024-05-28 06:12 UTC
### systemd version the issue has been seen with

249

### Used distribution

SLES15 SP4

### Linux kernel version used

5.14.21-150400.24.100-default

### CPU architectures issue was seen on

x86_64

### Component

systemd-udevd

### Expected behaviour you didn't see

We have a host running with SLES15 SP4 which has approx. 1000 devices mapped to it. Node has 10 dedicated cores. 

As the number of devices mapped to the node is increased, we are observing significant delays in the wwn symmlink initialization for the newly added namespaces. 

Eg: After mapping 1000 devices to the node, each new device add takes about 40-50s to initialize the wwn symmlinks. 

Observation:
 
1) When we add device, nvme immediately gets the notification and scans the controller .. below messages appear in dmesg

  [102806.727071] nvme nvme1: rescanning namespaces.

2) But udev messages appear after about 55s

    KERNEL[102867.660536] add      /devices/virtual/bdi/259:7282 (bdi)
    KERNEL[102867.661961] add      /devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1364 (block)
    KERNEL[102867.662075] add      /devices/virtual/nvme-subsystem/nvme-subsys0/ng0n1364 (nvme-generic)
    UDEV  [102867.662491] add      /devices/virtual/bdi/259:7282 (bdi)
    UDEV  [102867.663429] add      /devices/virtual/nvme-subsystem/nvme-subsys0/ng0n1364 (nvme-generic)
    UDEV  [102867.674183] add      /devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1364 (block)

3) After udev processing, the new device gets added to the /dev namespace

Issue is observed even when system is idle state ie all CPUs idle and udev queue empty. 

### Unexpected behaviour you saw

Observing delays of approx. 35-50s for each namespace addition after mapping more than 1000 devices to the node.  

### Steps to reproduce the problem

Create and Map more than 1000 volumes to a node. 
Observe significant delay in wwn symmlink creation for subsequent device namespace addition.

**Comment by yuwata** [comment] 2024-05-28 06:17
Sorry, v249 is too old here. Please contact to your downstream. And I guess the issue is already fixed in upstream. Closing.

**Closed as completed by yuwata** 2024-05-28 06:17 UTC
Labels: udev, version-too-ancient, already-fixed

**Comment by aayushSID** [comment] 2024-05-28 06:19
@yuwata thanks for the feedback. Do you have any earlier bugs for reference? 
We will try upgrading to the latest systemd v

**Comment by yuwata** [comment] 2024-05-28 06:52
The most important fix is #23043 (v252).
Further improvement was done in #26048 (v254), and its follow-up #29691 (v255, backported to v254).

History.
30f6dce62cb3a738b20253f2192270607c31b55b (v247) and 996c83903da5bf8b371314b4207ff97afeef65a4introduced (v248) introduced retry-loop with delay. That causes significant slow down when a system has many disks.

Unfortunately, I cannot find explicit issue page, but we discussed about the race in creating symlink and performance at random places.

**Comment by yuwata** [comment] 2024-05-28 06:54
So, I hope, v252 or newer should fix your issue. If you can still find the slow down in recent releases (v255 or newer), then feel free to request to reopen this page.
