### ISSUE TITLE
TEST-30-ONCLOCKCHANGE is very flakey

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#12268] opened 2019-04-10 13:57 UTC
It failed on maybe half of PRs recently, e.g.
https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-upstream-systemd-ci-systemd-ci/bionic/amd64/s/systemd-upstream/20190410_134709_9d4d9@/log.gz

**Comment by mrc0mmand** [comment] 2019-04-10 14:12
Looks like a timing issue

```
systemd-timedated.service: Executing: /lib/systemd/systemd-timedated
systemd-timedated.service: Got notification message from PID 273 (WATCHDOG=1)


systemd-testsuite login: Got message type=signal sender=org.freedesktop.DBus destination=n/a path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameOwnerChanged cookie=13 reply_cookie=0 signature=sss error-name=n/a error-message=n/a
systemd-timedated.service: D-Bus name org.freedesktop.timedate1 now registered by :1.3Failed to set time zone: Connection timed out

systemd-timedated.service: Changed start -> running
systemd-timedated.service: Job 122 systemd-timedated.service/start finished, result=done
```

or "just another timeout" like in https://github.com/systemd/systemd/pull/12218#issuecomment-481663143

**Comment by poettering** [comment] 2019-04-11 09:40
> Failed to set time zone: Connection timed out

Hmm, how could that fail? that's strange

**Comment by mrc0mmand** [comment] 2019-04-11 09:50
It looks like the timezone was changed moments after the timeout:

```
systemd-timedated.service: D-Bus name org.freedesktop.timedate1 now registered by :1.3Failed to set time zone: Connection timed out

systemd-timedated.service: Changed start -> running
systemd-timedated.service: Job 122 systemd-timedated.service/start finished, result=done
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2dtimedated_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=157 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2dtimedated_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=158 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobRemoved cookie=159 reply_cookie=0 signature=uoss error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2dtimedated_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=160 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2dtimedated_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=161 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Received SIGCHLD from PID 242 (testsuite.sh).
Child 242 (testsuite.sh) died (code=exited, status=1/FAILURE)
testsuite.service: Child 242 belongs to testsuite.service.
testsuite.service: Main process exited, code=exited, status=1/FAILURE
testsuite.service: Failed with result 'exit-code'.
testsuite.service: Changed start -> failed
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=162 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
testsuite.service: Job 67 testsuite.service/start finished, result=failed
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/testsuite_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=163 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/testsuite_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=164 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1 interface=org.freedesktop.systemd1.Manager member=JobRemoved cookie=165 reply_cookie=0 signature=uoss error-name=n/a error-message=n/a
testsuite.service: Unit entered failed state.
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/testsuite_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=166 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/testsuite_2eservice interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=167 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
inotify event for /etc/localtime
Timezone has been changed (now: CEST).
systemd-tmpfiles-clean.timer: Timezone change, recalculating next elapse.
systemd-tmpfiles-clean.timer: Monotonic timer elapses in 13min 25.674731s.
```

So it apparently *just* timeouted while waiting for the response?

**Comment by poettering** [comment] 2019-04-11 14:23
this is with a dbus-daemon system I presume? dbus-broker is not in the mix?

For some reason the bus call for setting the timezone seems to time out. Since the timezone was changed it appears the response doesn't come back, or that the dbus client doesn't wait long enough for some reason...

**Comment by mrc0mmand** [comment] 2019-04-11 14:35
> this is with a dbus-daemon system I presume? dbus-broker is not in the mix?

Yes, dbus 1.12.2

**Comment by evverx** [comment] 2019-06-29 12:31
Judging by https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-upstream-systemd-ci-systemd-ci/bionic/amd64/s/systemd-upstream/20190629_005149_3874a@/log.gz (from https://github.com/systemd/systemd/pull/12909) and https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-upstream-systemd-ci-systemd-ci/bionic/amd64/s/systemd-upstream/20190628_211246_118dc@/log.gz (from https://github.com/systemd/systemd/pull/12908) the test keeps failing on Ubuntu CI. @ddstreet could you add it to the blacklist discussed in https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1829829.

**Comment by ddstreet** [comment] 2019-07-01 20:24
I made a note https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1829829/comments/25

Unless I see a easy way to get it passing in the 25 second service start timeout, I'll open a debian merge request to add it to the blacklist.

**Comment by mrc0mmand** [comment] 2019-07-01 21:15
I'm actually quite curious what causes the systemd-timedated service to timeout:

```
Failed to set time zone: Failed to activate service 'org.freedesktop.timedate1': timed out (service_start_timeout=25000ms)
```

as I can't reproduce it locally even in a VM without KVM and with SMP=1.

**Comment by ddstreet** [comment] 2019-07-09 01:09
opened debian MR to blacklist this test, for now:
https://salsa.debian.org/systemd-team/systemd/merge_requests/36

**Comment by yuwata** [comment] 2022-09-11 17:23
The test is still blacklisted on ubuntu i386 (though we do not have i386 CI anymore), but passes on other environment. Closing.

**Closed as completed by yuwata** 2022-09-11 17:23 UTC
Labels: tests
