### ISSUE TITLE
systemd-cryptsetup: failure when TPM2 libs are not found

### ISSUE THREAD

**Issue by xdbob** [systemd/systemd#19826] opened 2021-06-05 10:13 UTC
**systemd version the issue has been seen with**
 > systemd 248 (v248.3-1.fc34)

**Used distribution**
 > Fedora 34

**Linux kernel version used** (`uname -a`)

 > `Linux tartarus 5.12.8-300.fc34.x86_64 #1 SMP Fri May 28 15:20:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > `systemd-cryptsetup` should have asked for my passphrase

**Unexpected behaviour you saw**
 > `systemd-cryptsetup` failed leaving my system stuck at boot

**Steps to reproduce the problem**
 > `systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=1,2,3,5,7 /dev/nvme0n1p3 && reboot`

**Additional program output to the terminal or log subsystem illustrating the issue**

![IMG_20210604_214754](https://user-images.githubusercontent.com/950419/120888100-d6204d80-c5f6-11eb-9eb8-2a840b13d411.jpg)

**Comment by poettering** [comment] 2021-06-07 08:24
Duplicate of #19177

**Closed as completed by poettering** 2021-06-07 08:24 UTC
Labels: cryptsetup, duplicate, tpm2
