### ISSUE TITLE
Building udev/cdrom_id fails on bionic-s390x if dynamic linking to libselinux is added

### ISSUE THREAD

**Issue by bluca** [systemd/systemd#18165] opened 2021-01-08 11:49 UTC
If src/udev/cdrom_id is switched to use the ```DEFINE_MAIN_FUNCTION``` helper, which has an implicit call into a libselinux API, the linker will no longer prune -lselinux (-Wl,--as-needed). This causes a build error on bionic-s390x, which is not reproducible on developers environment, including native s390x machines with the same Ubuntu version, but it is 100% reproducible in the bionic-s390x CI environment:

> cc -o src/udev/cdrom_id 'src/udev/3eb56e7@@cdrom_id@exe/cdrom_id_cdrom_id.c.o' -flto -Wl,--as-needed -Wl,--no-undefined -pie -Wl,-z,relro -Wl,-z,now -fstack-protector -Wl,--gc-sections -g -O2 -fdebug-prefix-map=/tmp/autopkgtest.SgH9rI/build.5OR/systemd=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,--start-group src/shared/libsystemd-shared-247.a src/libsystemd/libsystemd_static.a src/basic/libbasic.a -pthread -lacl /usr/lib/s390x-linux-gnu/libblkid.so /usr/lib/s390x-linux-gnu/libcap.so -lcrypt -lgcrypt /usr/lib/s390x-linux-gnu/libip4tc.so /usr/lib/s390x-linux-gnu/libip6tc.so /usr/lib/s390x-linux-gnu/libkmod.so /usr/lib/gcc/s390x-linux-gnu/7/../../../s390x-linux-gnu/liblz4.so /usr/lib/s390x-linux-gnu/libmount.so -lpam -lrt /usr/lib/s390x-linux-gnu/libseccomp.so /usr/lib/s390x-linux-gnu/libselinux.so /usr/lib/gcc/s390x-linux-gnu/7/../../../s390x-linux-gnu/libzstd.so /usr/lib/s390x-linux-gnu/liblzma.so -lm -ldl -Wl,--end-group '-Wl,-rpath,$ORIGIN/../shared:$ORIGIN/../libsystemd:$ORIGIN/../basic' -Wl,-rpath-link,/tmp/autopkgtest.SgH9rI/build.5OR/systemd/build-deb/src/shared -Wl,-rpath-link,/tmp/autopkgtest.SgH9rI/build.5OR/systemd/build-deb/src/libsystemd -Wl,-rpath-link,/tmp/autopkgtest.SgH9rI/build.5OR/systemd/build-deb/src/basic
> 
> /usr/lib/s390x-linux-gnu/libselinux.so: undefined reference to `pthread_once'

-pthread is passed, so the lack of reference is strange, but @cpaelzer suspected that the linker flags order is the culprit here.

Discussion and PR:

https://github.com/systemd/systemd/pull/18095#discussion_r551474699

The PR did not change any build flags.

We are using a workaround which removes the SELinux call and thus the dependency is pruned, but at some point this might become a problem again.

Even more weirdly, the fido_id binary in the same directory (thus using the exact same build flags etc) can use ```DEFINE_MAIN_FUNCTION``` just fine. One would expect a build failure for it too, but it never happened.

/cc @martinpitt @cpaelzer @ddstreet for Canonical/Ubuntu/s390x expertise... and perhaps we need an exorcist too?

**Comment by ddstreet** [comment] 2021-01-15 21:45
I can't reproduce this myself, but my guess would be it's some bug in gcc ld that has to do with using both -flto and as-needed, which I think is what @cpaelzer was guessing also.

Is the only thing needed to repro the problem is replacing the cdrom_id main() function with DEFINE_MAIN_FUNCTION(run) ?

**Comment by bluca** [comment] 2021-01-15 22:31
Yes, it then becomes 100% reproducible in the bionic-s390x ci

**Comment by ddstreet** [comment] 2021-01-19 23:17
Ok, I verified this is a bug in the binutils version that's included in bionic; adding the focal version of binutils to the ppa allows the build to succeed. I've copied the focal-version binutils over to the upstream-system-ci ppa that's used for ubuntu ci tests, so a PR to switch cdrom_id back to DEFINE_MAIN_FUNCTION should pass on s390x again.

**Comment by bluca** [comment] 2021-01-19 23:21
Thanks for tracking this down! But if we do the change, won't it mean that anybody building systemd on Ubuntu 18.04 will start seeing build failures that they can't do anything about? Is there a plan to do backport a patch to binutils in Focal?

**Comment by ddstreet** [comment] 2021-01-19 23:23
@keszybz just FYI re: ubuntu ci, I think we should move up to testing with focal instead of bionic, as bionic is getting really old, and I think there will be more and more problems like this one that are due to old code being used during tests...the only thing I know of currently holding up a move to focal is this kernel bug:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1895132

That should be fixed in the next kernel release for focal, scheduled for sometime in Feb...once that's done, should I email the mailing list asking to move the ubuntu ci tests to focal, or open a github issue, or something else?

**Comment by bluca** [comment] 2021-01-19 23:25
Moving the CI to Focal sounds great to me!

**Comment by ddstreet** [comment] 2021-01-19 23:28
> Thanks for tracking this down! But if we do the change, won't it mean that anybody building systemd on Ubuntu 18.04 will start seeing build failures that they can't do anything about? Is there a plan to do backport a patch to binutils in Focal?

Well, for this *specific* bug, it seems to only affect s390x builds (I have no idea why), so that would at least limit who actually sees build failures.

However in general, yeah, anyone who is running bionic but also trying to build the latest upstream systemd will probably encounter problems. I really don't see any way around that though, and I don't think upstream systemd should limit itself to only working with the (quite old) package versions included in the oldest still-supported Ubuntu release. Already, the ubuntu ci uses a dedicated PPA with quite a few backported packages, because the version of those packages included in bionic is too old:
https://launchpad.net/~upstream-systemd-ci/+archive/ubuntu/systemd-ci/+packages?field.name_filter=&field.status_filter=published&field.series_filter=bionic

**Closed as completed** 2021-01-20 08:31 UTC
Labels: build-system, ci

**Comment by bluca** [comment] 2021-01-20 08:34
> > Thanks for tracking this down! But if we do the change, won't it mean that anybody building systemd on Ubuntu 18.04 will start seeing build failures that they can't do anything about? Is there a plan to do backport a patch to binutils in Focal?
> 
> Well, for this _specific_ bug, it seems to only affect s390x builds (I have no idea why), so that would at least limit who actually sees build failures.
> 
> However in general, yeah, anyone who is running bionic but also trying to build the latest upstream systemd will probably encounter problems. I really don't see any way around that though, and I don't think upstream systemd should limit itself to only working with the (quite old) package versions included in the oldest still-supported Ubuntu release. Already, the ubuntu ci uses a dedicated PPA with quite a few backported packages, because the version of those packages included in bionic is too old:
> https://launchpad.net/~upstream-systemd-ci/+archive/ubuntu/systemd-ci/+packages?field.name_filter=&field.status_filter=published&field.series_filter=bionic

Yes I agree, we shouldn't be limited by such a low common denominator. I was just wondering if it was possible to patch binutils in bionic itself, given it's definitely a bug and it still has quite a few years of support left.

**Comment by ddstreet** [comment] 2021-01-20 12:45
> I was just wondering if it was possible to patch binutils in bionic itself, given it's definitely a bug and it still has quite a few years of support left.

That's true, I'll scan through the changes between the versions, though it may not be obvious which commit(s) fix it.
