### ISSUE TITLE
No asking for clientPin for FIDO2

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#19491] opened 2021-05-02 06:00 UTC
**systemd version the issue has been seen with**
 > systemd 248 (v248-2.fc34)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified

**Used distribution**
 > Fedora Workstation 34

**Linux kernel version used** (`uname -a`)
 > `Linux hostname 5.11.16-300.fc34.x86_64 #1 SMP Wed Apr 21 13:18:33 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > `systemd-cryptsetup` asks for a clientPin when unlocking the LUKS2 via fido2 (Yubikey 5)

**Unexpected behaviour you saw**
 > `systemd-cryptstup` did not ask for a clientPin

**Steps to reproduce the problem**
 > 1. Configure YubiKey' FIDO2 application with a pin
 > 2. Add a key slot to LUKS using `systemd-cryptenroll --fido2-device=auto /dev/devname`
 > 3. Modify an entry in /etc/crypttab (add a 'fido2-device=auto' as a parameter)
 > 4. Attach a YubiKey to USB port
 > 5. Try to unlock the device via `systemd-cryptsetup attach mytest /dev/devname - fido2-device=auto`

**Additional program output to the terminal or log subsystem illustrating the issue**

```Set cipher ***, mode ***, key size *** bits for device /dev/devname.
Automatically discovered security FIDO2 token unlocks volume.
Asking FIDO2 token for authentication.
Security token requires user presence. <-- Here it waits for press on YubiKey, but no asking for pin was made
Failed to activate with FIDO2 decrypted key. (Key incorrect?)
🔐 Please enter passphrase for disk DISKNAME (mytest): (press TAB for no echo) 
```

I've also tried to make more verbose logs (I see there's a code which should ask for a clientPin and there're some debug logs in https://github.com/systemd/systemd/blob/main/src/shared/libfido2-util.c#L192) via `export SYSTEMD_LOG_LEVEL=debug`, but with no luck - no addition logs were made

**Comment by grassygrass** [comment] 2021-05-02 17:14
Sorry, seems to be a duplicate of https://github.com/systemd/systemd/issues/19246 and https://github.com/systemd/systemd/issues/19252. Will close for now

**Closed as completed by grassygrass** 2021-05-02 17:14 UTC
