### ISSUE TITLE
Drop-ins overriding Slice= don't consistently work

### ISSUE THREAD

**Issue by anitazha** [systemd/systemd#21058] opened 2021-10-20 00:25 UTC
**systemd version the issue has been seen with**
 > main (b00756030b3da2913a7d7ac332075aee25fed779). discovered in 249.

**Expected behaviour you didn't see**
 > Slice= set in a drop-in for a service will take precedence over the Slice= set in the main unit file.

**Unexpected behaviour you saw**
 > Service will sometimes be put in the cgroup specified by the main Slice= setting, and sometimes end up in the drop-in Slice= cgroup.

**Steps to reproduce the problem**
 Using mkosi and nspawn:
```
[root@image ~]# cat /etc/systemd/system/test.service
[Service]
Slice=caps.slice
ExecStart=sleep infinity

[root@image ~]# cat /etc/systemd/system/test.service.d/override.conf
[Service]
Slice=hostcrit.slice

[root@image ~]# systemctl show -p Slice test
Slice=caps.slice
[root@image ~]# systemctl daemon-reload
[root@image ~]# systemctl show -p Slice test
Slice=caps.slice
[root@image ~]# systemctl daemon-reexec
[root@image ~]# systemctl show -p Slice test
Slice=hostcrit.slice
[root@image ~]# systemctl daemon-reload
[root@image ~]# systemctl start test
[root@image ~]# systemctl show -p Slice test
Slice=caps.slice
```

Worked fine on 248. Blames to d219a2b07cc5dc8ffd5010f08561fab2780d8616. I think because it makes it possible to store multiple slices as dependencies instead of just one? cc @poettering

**Comment by dtardon** [comment] 2021-10-20 07:42
This is a duplicate of #20182.

**Closed as completed** 2021-10-20 07:46 UTC
Labels: pid1, regression ⚠️, duplicate
