### ISSUE TITLE
journald crash after suspend/resume

### ISSUE THREAD

**Issue by wavexx** [systemd/systemd#9538] opened 2018-07-08 21:02 UTC
**systemd version the issue has been seen with**
systemd 239

**Used distribution**
debian unstable

**Unexpected behaviour you saw**
I have several core dumps of journald on this system, which I only noticed late since the journal is lost during the crash, and while coredumpctl salvages the core, it obviously loses track of the crash.

Here's one:

[11810.001726] systemd-coredump[13637]: MESSAGE=Process 429 (systemd-journal) of user 0 dumped core.
[11810.001733] systemd-coredump[13637]: Coredump diverted to /var/lib/systemd/coredump/core.systemd-journal.0.0d437b0f1af84391b33134ef0909fcd9.429.1531082086000000.lz4
[11810.001736] systemd-coredump[13637]: Stack trace of thread 429:
[11810.001738] systemd-coredump[13637]: #0  0x00007f2ed6782234 __GI___libc_read (libc.so.6)
[11810.001740] systemd-coredump[13637]: #1  0x00007f2ed6714838 _IO_new_file_underflow (libc.so.6)
[11810.001743] systemd-coredump[13637]: #2  0x00007f2ed67138f8 __GI__IO_file_xsgetn (libc.so.6)
[11810.001745] systemd-coredump[13637]: #3  0x00007f2ed6708141 __GI__IO_fread (libc.so.6)
[11810.001747] systemd-coredump[13637]: #4  0x00007f2ed64886a8 fread (libsystemd-shared-239.so)
[11810.001749] systemd-coredump[13637]: #5  0x00007f2ed6488d47 read_full_file (libsystemd-shared-239.so)
[11810.001751] systemd-coredump[13637]: #6  0x00007f2ed6568b2d device_read_db_aux (libsystemd-shared-239.so)

another:

[ 6840.048179] systemd-coredump[7546]: MESSAGE=Process 418 (systemd-journal) of user 0 dumped core.
[ 6840.048185] systemd-coredump[7546]: Coredump diverted to /var/lib/systemd/coredump/core.systemd-journal.0.e13febf27eb6481eb4b017aeba831de4.418.1530998547000000.lz4
[ 6840.048188] systemd-coredump[7546]: Stack trace of thread 418:
[ 6840.048190] systemd-coredump[7546]: #0  0x00007f1e5b58a420 n/a (libsystemd-shared-239.so)
[ 6840.048193] systemd-coredump[7546]: #1  0x00007f1e5b58bb42 internal_hashmap_iterate (libsystemd-shared-239.so)
[ 6840.048195] systemd-coredump[7546]: #2  0x0000558f32563812 n/a (systemd-journald)
[ 6840.048197] systemd-coredump[7546]: #3  0x00007f1e5b74aa87 __libc_start_main (libc.so.6)
[ 6840.048199] systemd-coredump[7546]: #4  0x0000558f32565a7a n/a (systemd-journald)`

The crash location seems to vary, however after a couple of days I noticed these happen always after resuming from sleep, which make me suspect it's related to the watchdog and one of the earlier bug reports about it I've seen here.

Just to clarify, I'm running on kernel 4.17.3-1, on a i5-8250U. There is no disk pressure or anything special happening, however the system needs to wake from sleep after several minutes in order to reproduce the problem.

I'm running with a persistent journal if that would make any difference:

[Journal]
Storage=persistent
MaxRetentionSec=3month
MaxFileSec=1week

**Comment by wavexx** [comment] 2018-07-08 21:07
Further info: this is on a Lenovo Yoga X1 laptop.

**Comment by sourcejedi** [comment] 2018-07-09 14:03
AFAICT, the systemd watchdog uses signal ABRT.

Maybe `gdb` confirms this if you run it on the core dumps.

Or you could try looking at `journalctl --since=-2days | grep systemd-journal.service`.  Hopefully there should be some message from systemd about the crash, in a similar format to:

```
systemd[1]: plymouth-start.service: Control process exited, code=exited status=1
systemd[1]: plymouth-start.service: Failed with result 'exit-code'.
```

**Comment by wavexx** [comment] 2018-07-09 14:37
Yes, both cores are generated by SIGABRT by checking it on the core dump, forgot to mention.

**Comment by wavexx** [comment] 2018-07-09 15:45
From the journal:

````
Jul 08 22:34:46  kernel: Restarting tasks ... done.
Jul 08 22:34:46  systemd-journald[429]: /dev/kmsg buffer overrun, some messages lost.
Jul 08 22:34:46  systemd[1]: systemd-journald.service: Main process exited, code=dumped, status=6/ABRT
Jul 08 22:34:46  systemd[1]: systemd-journald.service: Failed with result 'watchdog'.
````

**Comment by wavexx** [comment] 2018-07-10 13:31
Issue #9079 seems vaguely related to me. With the exception that the stack traces shown are shown to be I/O-related.

In my case, the locations of the crashes are seemingly random (although this could be due to the latency added during the signal delivery).

According to https://github.com/systemd/systemd/issues/9079#issuecomment-392311933 there's no shift in CLOCK_MONOTONIC anymore. Still, the watchdog is trigger only after the system is woken up.

**Comment by poettering** [comment] 2018-07-13 16:37
What kernel is this? Is that perhaps one of those pre-release kernels that changed CLOCK_MONOTONIC semantics?

Does journald get killed instantly on resume, or is this delayed a bit?

Any chance you can acquire these backtraces with full debug symbols installed?

Is there anything else in the logs, can you paste a more complete exceprt?

**Comment by wavexx** [comment] 2018-07-13 21:51
On Fri, Jul 13 2018, Lennart Poettering wrote:
> What kernel is this? Is that perhaps one of those pre-release kernels that changed CLOCK_MONOTONIC semantics?

No. I wrote earlier it's 4.17.3 from Debian unstable.
I got another crash right now on 4.17.6.

> Does journald get killed instantly on resume, or is this delayed a bit?

Seems to be killed instantly.

> Any chance you can acquire these backtraces with full debug symbols installed?

Yes. I saved the journal, journald binary and separate debug symbols for
this purpose. But like I said, looking at various backtraces, the crash
location seems to be arbitrary.

Can I send those to you privately?

> Is there anything else in the logs, can you paste a more complete exceprt?

Nothing relevant that I can see. The particular kernel (4.17.6) seems to
sometimes juggle with thunderbolt during resume, failing to bring up the
display for a few seconds sometimes. This doesn't seem connected, as I
get journald to crash reliably after *each* suspend which was long
enough irregardless, and with the previous 4.17.3 kernel too which
didn't have this issue.

I could try with 4.18-rc4 if you think this would have any effect.

**Comment by wavexx** [comment] 2018-07-15 15:50
FIY I tried with 4.18-rc4, and the same problem persists. I did a few tests  using a stop watch: the stopwatch kills journald if I sleep more than 3 minutes. It's that simple.

**Comment by poettering** [comment] 2018-07-16 15:10
does this work on 4.16?

if you look at your CLOCK_BOOTTIME before and after a 1min suspend cycle, did it increase by 1min or just a few secs?

i.e. check what `python3 -c "import time; print(time.monotonic())` reports before and after such a 1min suspend cycle.

**Comment by wavexx** [comment] 2018-07-16 20:22
On Mon, Jul 16 2018, Lennart Poettering wrote:
> does this work on 4.16?
>
> if you look at your CLOCK_BOOTTIME before and after a 1min suspend
> cycle, did it increase by 1min or just a few secs?
>
> i.e. check what python3 -c "import time; print(time.monotonic())
> reports before and after such a 1min suspend cycle.

It increases by the slept time (1min + some seconds required to
suspend/wakeup).

I tested kernels 4.16.16 and 4.17.6 (both from debian unstable).
They have the exact same behavior on this machine for time.monotonic().

**Comment by poettering** [comment] 2018-07-17 13:53
> It increases by the slept time (1min + some seconds required to suspend/wakeup).

Well, it's really not supposed to. The monotonic clock (CLOCK_MONOTONIC) is supposed to pause while the system is suspended. If it continues running then what you are seeing is kinda expected, because nothing will be scheduled while the system is suspended.

The python test I gave you is entirely independent from systemd, this means this is a bug within your kernel, and your kernel only. Please report this to your distro's kernel packaging team, there's nothing we can do about this. CLOCK_MONOTONIC is supposed to pause during suspend (and CLOCK_BOOTTIME is supposed to continue), and if this doesn't work then this is something that has to be fixed in the kernel.

(Some re-release kernels carried some patches that broke CLOCK_MONOTONIC and made it work like CLOCK_BOOTTIME. They got reverted later on, and shouldn't have reached anybody's systems. Otherwise what you are seeing does smell a lot like those patches.)

Anyway, closing this here, as there's nothing we can do about this in systemd, and the bug is in your kernel.

**Comment by poettering** [comment] 2018-07-17 13:54
cc @bwhacks (debian kernel maintainer)

**Closed as completed by poettering** 2018-07-17 13:54 UTC
Labels: journal, not-our-bug

**Comment by wavexx** [comment] 2018-07-17 14:15
On Tue, Jul 17 2018, Lennart Poettering wrote:
> (Some re-release kernels carried some patches that broke
> CLOCK_MONOTONIC and made it work like CLOCK_BOOTTIME. They got
> reverted later on, and shouldn't have reached anybody's systems.
> Otherwise what you are seeing does smell a lot like those patches.)

So, @bwhacks, are you aware if this is the case?

I was able to reproduce this from 4.16.* all the way up to 4.18-rc4 in
debian.

It could also have started earlier, but I didn't notice until recently.

**Comment by bwhacks** [comment] 2018-07-17 17:07
We haven't cherry-picked any changed relating to CLOCK_MONOTONIC.

**Comment by bwhacks** [comment] 2018-07-17 17:10
I can't reproduce this when suspending my own laptop running Debian's version 4.17.3-1. It sounds as if @wavexx's system isn't properly suspending for some reason.

**Comment by wavexx** [comment] 2018-07-17 20:29
On Tue, Jul 17 2018, Ben Hutchings wrote:
> I can't reproduce this when suspending my own laptop running Debian's
> version 4.17.3-1. It sounds as if @wavexx's system isn't properly
> suspending for some reason.

This rang a bell. After searching a bit, looks like the Lenovo Carbon
6th gen and the X1 Yoga 3rd gen (this laptop) enter s2idle.

The most detailed post I found (which includes links to discussion with
Lenovo support) is this:

  https://bbs.archlinux.org/viewtopic.php?pid=1771210

@poettering: I guess things are a bit different in this sleep mode.
Should the assumption about CLOCK_MONOTONIC still holds in this mode?
I suspect not.

**Comment by poettering** [comment] 2018-07-18 06:49
> @poettering: I guess things are a bit different in this sleep mode. Should the assumption about CLOCK_MONOTONIC still holds in this mode? I suspect not.

Which underlying sleep mode is used by the kernel shouldn't matter to userspace, it's ultimately an implementation detail between kernel, firmware and hardware, but it shouldn't matter to userspace. CLOCK_MONOTONIC, CLOCK_REALTIME, CLOCK_BOOTTIME should all expose the same behaviour regardless which sleep mode is used.

Really, this is a kernel issue. Please report this to the kernel community, there's nothing we can do from userspace around this.

**Comment by wavexx** [comment] 2018-07-18 10:02
On Wed, Jul 18 2018, Lennart Poettering wrote:
> Which underlying sleep mode is used by the kernel shouldn't matter to
> userspace, it's ultimately an implementation detail between kernel,
> firmware and hardware, but it shouldn't matter to userspace.
> CLOCK_MONOTONIC, CLOCK_REALTIME, CLOCK_BOOTTIME should all expose the
> same behaviour regardless which sleep mode is used.

s2idle S0i3 sleep modes are different as far as I understood.

The userspace is suspended, as well as most devices, but the kernel is
alive and thus is makes perfect sense that CLOCK_MONOTONIC is advancing
as the kernel probably needs it.

**Comment by poettering** [comment] 2018-07-18 11:37
> The userspace is suspended, as well as most devices, but the kernel is alive and thus is makes perfect sense that CLOCK_MONOTONIC is advancing as the kernel probably needs it.

Well, it regardless what the kernel doe internally, this shouldn't be visible to userspace, either way.

I am sorry, but CLOCK_MONOTONIC is documented to work the way it works, and CLOCK_BOOTTIME exists precisely to have a clock that continues running during suspend. 

See the man page:

http://man7.org/linux/man-pages/man2/clock_gettime.2.html

Specifically the part of CLOCK_BOOTTIME, which makes it clear that unlike CLOCK_MONOTONIC it "also includes any time that the system is suspended".

This is a kernel issue, and it's not just going to break just systemd, but pretty much anything else that uses CLOCK_MONOTONIC and relies on the documented behaviour.

**Comment by glasserc** [comment] 2018-08-27 19:46
Thanks for the explanation. It looks like @wavexx also raised this issue on LKML without a response: https://lkml.org/lkml/2018/7/18/552.

**Comment by wavexx** [comment] 2018-08-27 21:12
On Mon, Aug 27 2018, Ethan Glasser-Camp wrote:
> Thanks for the explanation. It looks like @wavexx also raised this issue on LKML
> without a response: https://lkml.org/lkml/2018/7/18/552.

This was also reported here:

  https://bugzilla.kernel.org/show_bug.cgi?id=200595

**Comment by vojtechkral** [comment] 2019-07-11 15:16
@wavexx Hi. How did you end up solving this issue? I've just ran into a very similarly looking problem. My guess so far is that some other hardware is preventing a proper suspend, my top suspect is the nvidia GPU, followed by sound card, but this isn't confirmed so far...

**Comment by wavexx** [comment] 2019-07-11 15:48
On Thu, Jul 11 2019, Vojtech Kral wrote:
> @wavexx Hi. How did you end up solving this issue? I've just ran into
> a very similarly looking problem. My guess so far is that some other
> hardware is preventing a proper suspend, my top suspect is the nvidia
> GPU, followed by sound card, but this isn't confirmed so far...

I force S3 sleep by patching the ACPI tables. There are several guides
for lenovo laptops.

% cat /sys/power/mem_sleep
s2idle [deep]

s2idle is completely useless and represents a regression for me.
I found several other issues with it, including the laptop overheating
and shutting down for thermal reasons when being in a bag....

**Comment by vojtechkral** [comment] 2019-07-11 16:32
@wavexx Ah yes, I have a HP laptop, but the issue is probably the same - it uses s2idle. I'll look up how to force S3. Thank you! If this works I'll solve a Slicer issue foru you :-)

**Comment by wavexx** [comment] 2019-07-11 18:58
Are you using a kernel more recent than 4.18? If so, it would be great to update the report on https://bugzilla.kernel.org/show_bug.cgi?id=200595 the issue is still present.
Heck, I'll do that for you if you confirm that you're using 4.19+, just say which HP laptop are you using.

I was a bit lazy there, as they were asking to retest but I never did..

**Comment by vojtechkral** [comment] 2019-07-11 20:23
@wavexx I am using kernel 5.2 and the model is `HP Envy x360 15-dr0005nc`. However, the issue might be distinct from the Yoga issue. On this laptop apparently S3 doesn't work at all and the problem with s2idle is [caused by SK hynix nvme](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1801875). If some device is preventing the kernel to go to sleep, this might explain the watchdog firing up. I'll try a 
 [patched kernel](https://aur.archlinux.org/packages/linux-hynix/ (once it builds), maybe if the hynix problem is fixed this could also fix the journald crashing problem. I suggest we don't update the bugreport until I have more info as to whether the watchdog problem is actuall a distinct issue or not.

**Comment by marcan** [comment] 2023-01-27 05:53
I believe this is still a bug in systemd. While `CLOCK_MONOTONIC` is indeed documented to skip time in suspend (much to the dismay of the kernel folks - that is not POSIX compliant and they tried to unify it with `CLOCK_BOOTTIME`, but were unable to due to userspace issues such as this one), it does *not* and never has skipped *all* time in suspend (and it can't). In other words, there is a generally short but arbitrary time interval during a suspend cycle that *is* accounted for in `CLOCK_MONOTONIC` but during which userspace is frozen, since those events are not coincident.

In extreme cases, that discrepancy could be arbitrarily long. Consider that in s2idle states, timekeeping has to resume during IRQ processing, even if that processing does not result in a wakeup. An instance of many such interrupts arriving without a wakeup could make `CLOCK_MONOTONIC` tick arbitrarily long forward before the resume cycle.

So the correct interpretation of the behavior is that `CLOCK_BOOTTIME` never stops, while `CLOCK_MONOTONIC` skips *most* of the time in suspend, but not all of it, and there is no upper bound on how much it can tick forward between userspace freeze and thaw during a suspend cycle. I don't think systemd should rely on `CLOCK_MONOTONIC` not ticking during suspend. It should detect the suspend/resume and reset its watchdogs instead.

**Comment by poettering** [comment] 2023-01-27 08:57
> I believe this is still a bug in systemd. While `CLOCK_MONOTONIC` is indeed documented to skip time in suspend (much to the dismay of the kernel folks - that is not POSIX compliant and they tried to unify it with `CLOCK_BOOTTIME`, but were unable to due to userspace issues such as this one), it does _not_ and never has skipped _all_ time in suspend (and it can't). In other words, there is a generally short but arbitrary time interval during a suspend cycle that _is_ accounted for in `CLOCK_MONOTONIC` but during which userspace is frozen, since those events are not coincident.

But that's generally fine. As long as it is short. We are in an asynchronous system, scheduling latencies applies. I don't think anyone is surprised that scheduling latencies are bigger around a suspend/resume event.

Not that because scheduling latencies are really bad on general desktop in many cases (closed source nvidia drivers for example make things really bad), most desktop distros now default to turning off the watchdog logic in systemd services (you can, at build time). Moreover, the default watchdog timeout is 90s, and I don't think CLOCK_MONOTONIC is going to progress for thaaaaaat long during a suspend/resume event, is it?

Also, what I don't grok: the CLOCK_MONOTONIC clock exposed to userspace doesn't have to be synchronous to the one internally used by the kernel. it wouldn#t be too hard to stop the one exposed to userspace for a bit longer than the one used in the kernel.

> In extreme cases, that discrepancy could be arbitrarily long. Consider that in s2idle states, timekeeping has to resume during IRQ processing, even if that processing does not result in a wakeup. An instance of many such interrupts arriving without a wakeup could make `CLOCK_MONOTONIC` tick arbitrarily long forward before the resume cycle.

But that's just because the kernel people decided to expose their internal time-keeping 1:1 to userspace. stopping CLOCK_MONOTONIC until userspace is actually unfrozen would not be that hard.

There's also the simple fact that documentation simply says "This clock does not count time that the system is  suspended." This is what *everyone* relies on, because it's documented, sensible behaviour. if kernel people decided that docs are wrong, and don't even bother to provide an alternative then that's just careless and ignorant how this stuff is used and deployed in bazillions of systems, in systemd and about every other non-trivial Linux userspace software.

> So the correct interpretation of the behavior is that `CLOCK_BOOTTIME` never stops, while `CLOCK_MONOTONIC` skips _most_ of the time in suspend, but not all of it, and there is no upper bound on how much it can tick forward between userspace freeze and thaw during a suspend cycle. I don't think systemd should rely on `CLOCK_MONOTONIC` not ticking during suspend. It should detect the suspend/resume and reset its watchdogs instead.

This interepretation contradicts documentation and general use in Linux userpace. It might be a comfortable definition from kernel PoV, but it's inherently unfriendly to userspace where a clock that stops during suspend is highly desirable.

I am also not particularly impressed by the claims around s2idle. CLOCK_MONOTONIC with its documented semantics came long before that. Retroactively redifining what CLOCK_MONOTONIC means just to support s2idle is just wrong.

**Comment by zoechi** [comment] 2024-09-03 09:52
Is there any conclusion?

In a QEMU VM I run frequently into issues when watchdog kills systemd-journald, systemd-logind, udevadm, after resuming the host machine from sleep. 
systemd-logind is the main issue for me. It seems to break SDDM. Afterwards I can't login anymore (it only cycles back to the login screen).

```
Linux recherche 6.6.48 #1-NixOS SMP PREEMPT_DYNAMIC Thu Aug 29 15:33:59 UTC 2024 x86_64 GNU/Linux
```

I'm looking for months now and this seems to be the closest I got so far without any solution or workaround.

I found a few related issues like 
- https://access.redhat.com/solutions/5118401
- https://unix.stackexchange.com/questions/443601/systemd-watchdog-kills-services-after-changing-system-time-manually
- https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1433320
- https://bugzilla.redhat.com/show_bug.cgi?id=1524412
