### ISSUE TITLE
https://l10n.gnome.org/module/systemd/ is outdated

### ISSUE THREAD

**Issue by filmsi** [systemd/systemd#34028] opened 2024-08-18 14:08 UTC
### Component

systemd

### Is your feature request related to a problem? Please describe

Slovenian translation of systemd is finished at translate.fedoraproject.org, but here in github the unfinished po file is used.

### Describe the solution you'd like

Slovenian translation of systemd has been updated and completed by the Slovenian GNOME l10n Team.
Please merge the updated po file from translate.fedoraproject.org:
https://translate.fedoraproject.org/projects/systemd/main/sl/

Thank you.

**Comment by filmsi** [comment] 2024-08-18 14:10
Following the comment from @yuwata this is a properly stated issue
https://github.com/systemd/systemd/issues/34027

**Comment by yuwata** [comment] 2024-08-18 19:26
It seems all updates are already merged, e.g. be2ad93af3b6af6a939cf347754f5cc50ed1ac17.

**Comment by filmsi** [comment] 2024-08-18 19:29
That seems strange, Damned Lies reports of 2 untranslated strings (for all languages):
https://l10n.gnome.org/module/systemd/

**Comment by yuwata** [comment] 2024-08-18 19:46
IIRC, l10n.gnome is outdated, and we switched to weblate.
@mrc0mmand Please comment.

**Comment by filmsi** [comment] 2024-08-18 19:56
I understand that l10n.gnome.org is not the site to translate, but it shows the current state of all internal and external projects that are part of GNOME. For all external projects it seems quite accurate, changes that happen in external gits are usually updated in their stats in a day.
We just want all these projects 100% localized into Slovenian.

**Comment by yuwata** [comment] 2024-08-18 20:02
I do not have an account for the site. @mrc0mmand Could you take a look?

**Comment by mrc0mmand** [comment] 2024-08-23 13:46
The last time this happened it was caused by an outdated POT file, and after inspecting the Slovenian PO file it indeed shows a couple of newly introduced strings that are missing from our POT file (along with several updated strings, causing fuzzy translations). I opened https://github.com/systemd/systemd/pull/34108 which, once merged, should make Weblate complain and _demand_ new/updated translations. Once these are resolved and merged, Damned Lies should be happy as well.

**Closed as completed** 2024-08-24 22:53 UTC
Labels: l10n 🌍
