### ISSUE TITLE
limit journal size by systemd service

### ISSUE THREAD

**Issue by hosiet** [systemd/systemd#3341] opened 2016-05-25 03:37 UTC
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)

For systemd-journald, we can limit the maximum size of total journal file on the disk. So is it possible to limit the journal size of certain systemd service? For example, the size of the journal of bind9.service has to be less than 64M; any further journaling will cause old journal of this certain service to be rotated.

**Comment by evverx** [comment] 2016-05-25 05:17
Duplicate of #3045

**Closed as completed by evverx** 2016-05-25 05:17 UTC
Labels: RFE 🎁, journal, duplicate
