### ISSUE TITLE
homed: Fails to create LUKS2 home with BTRFS filesystem

### ISSUE THREAD

**Issue by yellowsquid** [systemd/systemd#16829] opened 2020-08-24 21:01 UTC
**systemd version**
```
systemd 246 (246.2-2-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default hierarchy=hybrid
```

**Used distribution**
 Arch Linux

**Expected behaviour you didn't see**
The following command to create a home directory:

```
homectl create newuser --storage=luks --fs-type=btrfs --image-path=/dev/disk/by-id/...
```

**Unexpected behaviour you saw**
 This error:

```
Operation on home newuser failed: Failed to execute operation: File exists
```

**Steps to reproduce the problem**
1) Insert a removable storage device.
2) Run the command listed above, with a correct device ID.
3) See the error.

The error does _not_ occur when using `--fs-type=ext4`, or when using the default image path.

 I am guessing that whatever formats the removable storage also creates a directory immediately. Later it tries to make a subvolume and fails. I might have the operation order backwards. I am unsure how to get more verbose output.

I am certain this is a regression from 245, because I was able to create a btrfs filesystem on removable storage (but not in a subvolume).

**Comment by yellowsquid** [comment] 2020-08-27 15:57
I can no longer replicate this issue. Same systemd version. I honestly have no clue why.

**Comment by poettering** [comment] 2020-09-18 17:45
I tried to replicate the issue in various ways, but I couldn't, it always worked here. Since it went away for you too, let's close this.

if you managed to reproduce it after all one day, please post the `journalctl -b -u systemd-homed.service` logs here, it should give us some hints where things went wrong.

**Closed as completed by poettering** 2020-09-18 17:45 UTC
Labels: homed

**Comment by alexandr-kara** [comment] 2024-12-02 17:09
I am having the same issue on Fedora 41:
```
homectl authenticate <username>
```
returns:
```
Operation on home <username> failed: Home <username> is currently being used, or an operation on home <username> is currently being executed.
```

If I do:
```
homectl activate <username>
```
I get instead
```
Operation on home <username> failed: failed to execute operation: File exists
```

When running it under `strace`, it fails on:
```
sendmsg(3, {msg_name=NULL, msg_namelen=0, ...) = 195
recvmsg(3, ...) = -1 EAGAIN (Resource temporarily unavailable)
```

Previously, file descriptor 3 seems to be connecting to AF_UNIX socket at /run/dbus/system_bus_socket. There are no SELinux failures, dmesg doesn't show anything interesting.

**Comment by alexandr-kara** [comment] 2024-12-02 17:25
Hm, the loopback was mounted in /var/media/root (I was logged in as root). It does work when in single-user setup.
