### ISSUE TITLE
RFE: Give alternatives when reboot command cannot connect to init daemon

### ISSUE THREAD

**Issue by ovitters** [systemd/systemd#4279] opened 2016-10-04 09:20 UTC
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Mageia
### In case of bug report: Expected behaviour you didn't see

> reboot
> Failed to talk to init daemon
> To force a reboot, run: systemctl --force --force reboot

Meaning: to add a hint what you could do in case reboot command doesn't work.
### In case of bug report: Unexpected behaviour you saw

> reboot
> Failed to talk to init daemon

This isn't helpful enough.
### In case of bug report: Steps to reproduce the problem

> Force a problem to talk to the init daemon.
> Run reboot command

**Comment by evverx** [comment] 2016-10-04 11:58
Duplicate of #3282

**Closed as completed by evverx** 2016-10-04 11:58 UTC
Labels: systemctl, duplicate
