### ISSUE TITLE
Nspawn containers fail to create payload subcgroup

### ISSUE THREAD

**Issue by LaKing** [systemd/systemd#14247] opened 2019-12-05 00:08 UTC
**systemd version the issue has been seen with**

systemd 243 (v243.4-1.fc31)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified

**Used distribution**
NAME=Fedora
VERSION="31 (Server Edition)"

**Expected behaviour you didn't see**
All Containers starting normally.

**Unexpected behaviour you saw**
About half of all containers fail to start.

```
Failed to create /machine.slice/[nspawn container].service/payload subcgroup: Operation not supported
Parent died too early
Main process exited, code=exited, status=1/FAILURE
Failed with result 'exit-code'.
```

**Steps to reproduce the problem**
Start ~100 containers at once, with Privateusers option. The first ~10-20 containers start fine, then some won't start and at the end of the sequence of starting containers only a few start.
Restarting containers one by one appears to be ok, but starting them in a sequence wont work on the first attempt. Starting a previously failed container works just fine, but now each container needs to be restarted one by one manually.

**Comment by poettering** [comment] 2019-12-05 10:44
hmm, weird... Is this with selinux on? if you turn it off, does it work then?

is this on unified hierarchy? hybrid? legacy? If you switch hierarchy, does it work then?

**Comment by LaKing** [comment] 2019-12-06 12:49
SELinux is diasbled on all containers and on the host.

Not sure how to check hierarchy, I don't think it has anything legacy. At least nothing is set manually on cgroups, they are all managed by systemd. 

```
[root@bp ~]# mount | grep cgroup
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
```

```
[root@bp ~]# cat /proc/mounts | grep cgroup
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0

```
systemd-cgls gives a really long list of everything started. ...

**Comment by poettering** [comment] 2019-12-12 18:22
if you switch to the legacy hierarachy (i.e. boot with systemd.unified_cgroup_hierarchy=0), does it work then?

**Comment by LaKing** [comment] 2019-12-29 04:45
I don't really reboot this machine that often, and have no remote access in the boot process, ... it is used as a dev server. However, I tried an update, and after the update only a couple containers failed to start, with a slightly different error:
```
systemd-nspawn[13006]: Failed to register machine: Connection timed out
systemd-nspawn[13006]: Failed to register machine: Connection timed out
```

**Comment by poettering** [comment] 2023-03-20 10:40
```
systemd-nspawn[13006]: Failed to register machine: Connection timed out
```

this sounds like a dbus issue/machined issue. 

Anyway, so much time passed since this was reported. Let's close this for now. if preproducible on current systemd, by all means, open a new issue.

**Closed as completed by poettering** 2023-03-20 10:40 UTC
Labels: bug 🐛, nspawn, needs-reporter-feedback ❓
