### ISSUE TITLE
RFE: systemd should support custom actions

### ISSUE THREAD

**Issue by Civil** [systemd/systemd#6690] opened 2017-08-29 14:23 UTC
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> All

### Used distribution

> All

Sometimes software need to have custom reload/restart/whatever actions. For example you have a daemon that can do:
1. Restart
2. Graceful restart
3. Upgrade
4. Reload config
5. Reopen logs

You might want to trigger any of them, but not other ones. Currently it seems impossible to define custom actions in systemd and you need to redefine either Start+Stop or Reload action.

If you think that that's something that should be done, I can even try to create a PR that will implement that functionality.

**Comment by poettering** [comment] 2017-08-29 16:14
This has been requested before, and we said no for it before. I don't think we should abstract what is inherently not abstractable, as these verbs are highly service-specific, and we couldn't generalize anything for them, since we don't know what they mean...

Also see the brief comment on the incompaitiblities list here:

https://www.freedesktop.org/wiki/Software/systemd/Incompatibilities/

> Additional verbs for init scripts are not supported. If your init script traditionally supported additional verbs for your init script simply move them to an auxiliary script. 

Moreover, this would potentially create naming conflicts as "systemctl" verbs and these per-service names would live in the same namespace.

Moreover, it's actually by design and on purpose that you cannot redefine what "systemctl restart" means, in order to expose a well-defined meaning to the user (as it strictly means: a stop followed by a start of the same service), and guarantee that after the restart the entire execution context of the service is clean, and fresh and properly reset.

So, yes, SysV supported that, but I don't think this scheme fits well with systemd, due to the conflicts, the inherent non-abstractability and so on. We have so far recommended everybody to simply move those verbs to some auxiliary service-specific tool, as they are inherently service-specific, and when they are in their own tool, they do not conflict with systemd's own verb naming, and can deviate from the unified behaviour systemd exposes for the usual verbs.

I hope that makes some sense?

Closing, sorry!

**Closed as completed by poettering** 2017-08-29 16:14 UTC
Labels: RFE 🎁, pid1, systemctl

**Comment by Civil** [comment] 2017-08-29 16:43
> I hope that makes some sense?

Nope, it doesn't. There is already such service-specific abstraction called "reload". Because it exists, it seems that there is no reason NOT to add a "logrotate", "graceful-restart" (or an option --graceful to restart command) and so on and so on. Maybe not arbitrary command, but at least extend current command set with some other common things.

**Comment by poettering** [comment] 2017-08-29 16:46
Nope, it doesn't. There is already such service-specific abstraction called "reload". Because it exists, it seems that there is no reason NOT to add a "logrotate", "graceful-restart" (or an option --graceful to restart command) and so on and so on. Maybe not arbitrary command, but at least extend current command set with some other common things.

"reload" has very clearly defined semantics, and it is tightly integrated with systemd's execution queue management. (For example, as systemd has an idea what "reload" means, if you enqueue a restart and a reload at the same time it will drop the reload knowing that a restart makes it unnecessary, as it is the much weaker operation).

Regarding graceful restarts: I think it would be a good idea if all restarts would be graceful, actually, it shouldn't be an option you have to explicitly request...

**Comment by poettering** [comment] 2017-08-29 16:47
And regarding "logrotate" and other verbs: if there's no strong case why systemd should know about these specific ones (which could be that it could manage the service state better then, or integarte the operation into its execution queue) I don't think it should be in systemd. 

Or to say this differently: there needs to be a good reason to abstract it in systemd, not a good reason not to have it...

**Comment by Civil** [comment] 2017-08-29 17:00
> Or to say this differently: there needs to be a good reason to abstract it in systemd, not a good reason not to have it...

Systemd as an init-service is the **only** source of truth for a PID<->Service mapping. That's the reason to do all that stuff in systemd.

**Comment by ikruglov** [comment] 2017-08-30 08:35
let me jump into this conversation.

The issue which we (@civil and I) have at $work is that we've bumped to the same issue multiple time where a service has:
- restart i.e. start + stop
- reload - configuration reload
- graceful restart - restart without dropping connections
- logrotate - reopen log files
with systemd we are able to accommodate two out of these 4 cases. Example of such service is nginx. The latest case is envoy.

So, I think what I would like to see is not the ability to have custom action as initially phrased, but rather two additional action which would cover described common case: logrotate, graceful restart.

Regarding to what you said before:
> Regarding graceful restarts: I think it would be a good idea if all restarts would be graceful, actually, it shouldn't be an option you have to explicitly request...

How does this coexists with?
> Moreover, it's actually by design and on purpose that you cannot redefine what "systemctl restart" means, in order to expose a well-defined meaning to the user (**as it strictly means: a stop followed by a start of the same service**), and guarantee that after the restart the entire execution context of the service is clean, and fresh and properly reset.

**Comment by bl33pbl0p** [comment] 2017-08-31 10:02
I also ran into this issue with one of my programs, but I created another service to do custom actions. I do agree that adding them as generic options is not really a good idea (because services needing `logrotate` and even `graceful-restart` are little in number), but maybe something along the lines of `systemctl action=logrotate foobar.service` (actually, the `action` could lie after the service name so the bash/zsh completion script could parse the unit and provide suggestions), and something like `Name=` and then `Exec=...`. (and maybe still have the `ExecPre=...` and `ExecPost=...` options for the `Exec=` action) in the service files, with these custom commands in their own context block, like [Action] to be able to depend on the generic `ExecStart=`, `ExecStop=`, `ExecReload=` commands, because then the reopening of log files can be subjected with a restart or reload or w/e. (When forming dependencies with a certain action, that action itself can have a parameter `action` to call the custom command.) The order of execution will be defined by the `Before=` or `After=` dependency of the command on the generic action.

Example for doing a job:
```ini
[Unit]
...

[Service]
...
ExecStart=...
ExecStop=...
ExecReload=...
...

[Action]
Name=logrotate
# queue it before ExecStartPre or ExecStartPost, or After
Before=ExecStart
ExecPre=...
Exec=...
ExecPost=..
```
and then, 
`systemctl action=logrotate foobar.service`
or 
`systemctl start action=logrotate foobar.service` # would mean the same thing

support could also be added to queue them as dependencies when being invoked from the command line when a dependency isn't specified in the unit or cannot be.
`systemctl restart before-action=logrotate foobar.service`
or 
`systemctl restart after-action=logrotate foobar.service`

This though does have some use cases, there are times when the custom action doesn't have to be queued before a generic action, and therefore it could be something like this

```ini
[Unit]
...

[Service]
...

[Action]
Name=jobfoo
Exec=...
...
```
and then,
`systemctl action=jobfoo foobar.service`

The Exec= thing being synchronous or asynchronous can be handled by the command/script/binary being invoked.


As everyone must have noticed, this is something more complex to fit into the current Unit specification scheme, but it is possible to fit in quite well, and would really make the simple .ini model of the service files to be more powerful. The proposal probably is not a very suitable scheme of integrating custom commands into the unit, and may have a lot of deficiencies, suggestions welcome. This really needs to be thought out well and be consistent with the current unit file specification.

Also, right, the user should really not be able to redefine what restart (i.e. start + stop) does, the behavior is correct.

All in all, custom commands do have a very strong use case, but they mustn't lie in the generic namespace, instead be invoked with a parameter to an argument instead. The issue can still be solved by making separate units for custom actions, but, adding support to define custom service actions will really be a plus and will be clean. Again, as proposed earlier, you could divide the naming namespaces into two sections, the generic namespace and unit specific namespace (which can be invoked with something like action). Although trivial, there could be a file to define custom global actions that can be used in all unit files created by the admin.

/cc @poettering @Civil @ikruglov

**Comment by ikruglov** [comment] 2017-08-31 12:01
Hi @bl33pbl0p. Thanks for your proposal. I would be fine with such approach. Let's see what @poettering thinks about it.

**Comment by Civil** [comment] 2017-08-31 12:03
And I'll also be ok with that and even will be willing to spend my time to try to create a PR for that, if @poettering will be ok with that.

**Comment by fsateler** [comment] 2017-08-31 13:30
@ikruglov 

> Regarding to what you said before:
>
> >Regarding graceful restarts: I think it would be a good idea if all restarts would be graceful, actually, it shouldn't be an option you have to explicitly request...
>
>How does this coexists with?
>
>>Moreover, it's actually by design and on purpose that you cannot redefine what "systemctl restart" means, in order to expose a well-defined meaning to the user (as it strictly means: a stop followed by a start of the same service), and guarantee that after the restart the entire execution context of the service is clean, and fresh and properly reset.

There are two mechanisms that help implement this:

1. Socket activation: With socket activation, your server does not open the listening socket, it receives it opened from systemd. If the service does not close the socket, systemd will keep it open, and new connections will simply buffer in the kernel while the new instance is started.
2. The FD store. If you need to keep more sockets or file descriptors open, you can pass them over to systemd using `sd_notify_with_fds`. Please see the [sd_notify man page](https://www.freedesktop.org/software/systemd/man/sd_notify.html) for more details.


This is how eg the journal can be restarted without losing logs.

**Comment by ikruglov** [comment] 2017-08-31 13:38
@fsateler thanks for clarification. Can you point me to a case where one of these mechanisms is used?

**Comment by Civil** [comment] 2017-08-31 13:38
@fsateler this is hard to impossible to implement for cross-platform software (I just want to remind that systemd is de-facto linux-specific, plus there are a lot of distributions that are still supported but doesn't have systemd, e.x. rhel6). And as far as I remember that's one of the main reasons why there is no sd_notify_with_fds for nginx for example.

**Comment by fsateler** [comment] 2017-08-31 14:03
@ikruglov 

> @fsateler thanks for clarification. Can you point me to a case where one of these mechanisms is used?

Socket activation is used in several daemons. I found a relatively simple one in onak. Here is the commit that introduced socket activation:  http://the.earth.li/gitweb/?p=onak.git;a=commitdiff;h=5c137b7d6af54fb54dfe13b65c933b5b6a4c764c . Notice how when the socket was passed by systemd onak avoids closing it on exit.
This already allows graceful restarts for stateless daemons (which is probably most of them). Current requests will finish processing, and new requests will queue up in the kernel while we restart.

I have not seen sd_pid_notify_with_fds used outside systemd yet.

@Civil 
> @fsateler this is hard to impossible to implement for cross-platform software (I just want to remind that systemd is de-facto linux-specific, plus there are a lot of distributions that are still supported but doesn't have systemd, e.x. rhel6). And as far as I remember that's one of the main reasons why there is no sd_notify_with_fds for nginx for example.

I think sd_notify_with_fds is not used in nginx because it does not need to: I don't think nginx keeps any sockets open other than the listening socket across restarts (and I don't know why it would want to, this function would be useful only for daemons that keep persistent connections). But I don't know for sure, I'm not very familiar with nginx. 

This subthread is becoming off-topic for an issue tracker. Please move this discussion to the mailing list if you want to continue it further.

**Comment by bl33pbl0p** [comment] 2017-08-31 19:26
Further discussion/thoughts and requests, please use the ML. I've made the mail. Thanks!
https://lists.freedesktop.org/archives/systemd-devel/2017-August/039473.html
/cc @ikruglov @Civil
Also, this document describes the log rotation and upgrade in place procedure, the graceful-restart.
http://nginx.org/en/docs/control.html

**Comment by poettering** [comment] 2017-09-14 10:07
BTW this is also a duplicate of #3656.
