### ISSUE TITLE
systemd-logind automatically suspends because surface laptop driver claims the lid is closed whenever it doesn't know the current lid state

### ISSUE THREAD

**Issue by chenyu105** [systemd/systemd#2807] opened 2016-03-07 15:06 UTC
Currently there are two lid issues on Surface Pro 1 and Surface 3 respectively:
https://bugzilla.kernel.org/show_bug.cgi?id=106941
https://bugzilla.kernel.org/show_bug.cgi?id=89211
The problems are lid status does not coincide with systemd properly.

The first one has been filed at:
https://github.com/systemd/systemd/issues/1874
and it is because lid status has been initialized as 'closed' during bootup, 
thus the button driver sends a 'close' event to systemd, which caused the auto-suspend.

The second one is more interesting and I'd like to describe it a little more.
On Surface Pro 1, there is no lid open event due to hardware design,
so we can not wake the system up be openning the lid, but have to
press a power button. So during resume the button driver would
not send any lid status to systemd (or send the wrong lid status),
as a result, the systemd suspend the system for the second time about
10~15 sec later after resumed.

I wonder if systemd-sleep is using a timeout mechanism, if it does not receive any
open lid event/netlink from button driver, it regards current state as still suspended,
thus launch another suspend operation? Why does systemd-sleep behave like this, I thought
systemd daemon should be driven only by lid close event, and should not care the lid
open event, as this is what Windows do for most platforms.

**Comment by hadess** [comment] 2016-03-07 16:06
> Why does systemd-sleep behave like this, I thought
> systemd daemon should be driven only by lid close event, and should not care the lid
> open event, as this is what Windows do for most platforms.

As I said on the mailing-list, you're conflating 2 things: the way Windows behaves, and the way the Linux API eventually got implemented.

systemd is behaving correctly given the interface the kernel provides. If, on the machine which cause problems, we had another interface, which didn't make it possible for user-space to read the Lid status, then systemd would probably be implement this feature differently.

As it is, the expectation is that user-space will be able to read the status of the lid, and that it will be correct.

The options are:
- the kernel changes its API so that the Lid status cannot be read or relied upon, breaking every user-space application that relies on it (UPower exports the lid status to a number of desktop environments)
- the kernel adds a new API for devices like the Surfaces mentioned above, and systemd/UPower change their API usage to reflect that.

systemd (and UPower) are using the API correctly. The problem is that this API worked on 99% of machines up until now, and didn't match the expectations that Windows set.

If we don't have a way to read the current lid status on those machines, then so be it, but user-space needs a way to figure that out, either because it's a different and separate API, or because the API is amended/extended to export this fact.

**Comment by poettering** [comment] 2016-04-15 17:04
@chenyu105 so it appears to me that if the lid state is not known, then the driver should return it as opened, not as closed. i.e. when booting or coming back from suspend it should really claim the lid is opened until it learns otherwise. It sounds completely backwards that this got implemented the other way, and defaults to "lid closed"... 

logind will suspend the machine if the lid is closed, and that's level-triggered, not edge triggered...

**Comment by poettering** [comment] 2016-04-15 18:14
(note that the logic of assuming that the lid is open when there is no lid switch detected is also what logind internally implements. Thus, if the surface laptop driver would do the same when it doesn't know this would nicely mimic the logic here...)

An alternative for the laptop driver would be to make the input device that exposes the SW_LID switch to userspace disappear when the switch state isn't known. i.e. as soon as the lid switch is known, create the input device via hotplug, and make it disappear again on suspend when the state is no longer known. logind would do the right thing then.

Hope that makes sense.

Either way, these are all driver issues that need be fixed in the kernel. Closing this issue hence.

**Closed as completed by poettering** 2016-04-15 18:14 UTC
Labels: login, not-our-bug
