### ISSUE TITLE
BindsTo=*.device in user service breaks login/session (when device does not exist)

### ISSUE THREAD

**Issue by tomty89** [systemd/systemd#5950] opened 2017-05-12 14:08 UTC
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

user service fails when device it binds to does not exist, without breaking login/session

### In case of bug report: Unexpected behaviour you saw

pan_systemd got connetion timeout when attempted to create session; it appears that the start job of the bound device blocks it somehow, since more errors show up after that timed out

btw the timeout is not affected by JobTimeoutSec= set in the service, not sure if that is expected/relevant either

one re-login is not enough for things to restart/recover, a cgroup error shows up on the first re-login, then after a second re-login things seem to start/work normally as usual again

### In case of bug report: Steps to reproduce the problem

I have the following udev rule (which is not really relevant to this I think, but I am gonna just show my full configuration anyway):

`SUBSYSTEM=="sound", KERNEL=="card*", TAG+="systemd", ENV{SYSTEMD_ALIAS}+="/sys/subsystem/sound/devices/$attr{id}"`

And the following user service _enabled_:
```
[Unit]
BindsTo=sys-subsystem-sound-devices-%i.device
After=sys-subsystem-sound-devices-%i.device
JobTimeoutSec=3

[Service]
ExecStart=/usr/bin/jackd -d alsa -d hw:%I -P -r 44100
KillSignal=SIGKILL

[Install]
WantedBy=sys-subsystem-sound-devices-%i.device default.target
```

Here are the logs. The test is done after a fresh reboot:
```
May 12 21:21:37 localhost login[367]: pam_unix(login:session): session opened for user tom by LOGIN(uid=0)
May 12 21:21:37 localhost systemd[1]: Created slice User Slice of tom.
May 12 21:21:37 localhost systemd[1]: Starting User Manager for UID 1000...
May 12 21:21:37 localhost systemd-logind[357]: New session c1 of user tom.
May 12 21:21:37 localhost systemd[1]: Started Session c1 of user tom.
May 12 21:21:37 localhost systemd[369]: pam_unix(systemd-user:session): session opened for user tom by (uid=0)
May 12 21:21:37 localhost systemd[369]: Reached target Paths.
May 12 21:21:37 localhost systemd[369]: Reached target Timers.
May 12 21:21:37 localhost systemd[369]: Created slice jackd.slice.
May 12 21:21:37 localhost systemd[369]: Starting D-Bus User Message Bus Socket.
May 12 21:21:37 localhost systemd[369]: Listening on D-Bus User Message Bus Socket.
May 12 21:21:37 localhost systemd[369]: Reached target Sockets.
May 12 21:21:37 localhost systemd[369]: Reached target Basic System.
May 12 21:21:40 localhost systemd[369]: jackd@Audio.service: Job jackd@Audio.service/start timed out.
May 12 21:21:40 localhost systemd[369]: Timed out starting jackd@Audio.service.
May 12 21:21:40 localhost systemd[369]: jackd@Audio.service: Job jackd@Audio.service/start failed with result 'timeout'.
May 12 21:21:40 localhost systemd[369]: Reached target Default.
May 12 21:22:02 localhost login[367]: pam_systemd(login:session): Failed to create session: Connection timed out
May 12 21:22:02 localhost login[367]: LOGIN ON tty1 BY tom
May 12 21:23:07 localhost systemd[369]: sys-subsystem-sound-devices-Audio.device: Job sys-subsystem-sound-devices-Audio.device/start timed out.
May 12 21:23:07 localhost systemd[369]: Timed out waiting for device sys-subsystem-sound-devices-Audio.device.
May 12 21:23:07 localhost systemd[369]: sys-subsystem-sound-devices-Audio.device: Job sys-subsystem-sound-devices-Audio.device/start failed with result 'timeout'.
May 12 21:23:07 localhost systemd[1]: user@1000.service: Start operation timed out. Terminating.
May 12 21:23:07 localhost systemd[369]: Startup finished in 1min 30.086s.
May 12 21:23:07 localhost systemd[369]: Removed slice jackd.slice.
May 12 21:23:07 localhost systemd[369]: Stopped target Default.
May 12 21:23:07 localhost systemd[369]: Stopped target Basic System.
May 12 21:23:07 localhost systemd[369]: Stopped target Timers.
May 12 21:23:07 localhost systemd[369]: Stopped target Paths.
May 12 21:23:07 localhost systemd[369]: Stopped target Sockets.
May 12 21:23:07 localhost systemd[369]: Closed D-Bus User Message Bus Socket.
May 12 21:23:07 localhost systemd[369]: Reached target Shutdown.
May 12 21:23:07 localhost systemd[369]: Starting Exit the Session...
May 12 21:23:07 localhost systemd[369]: Received SIGRTMIN+24 from PID 381 (kill).
May 12 21:23:07 localhost systemd[371]: pam_unix(systemd-user:session): session closed for user tom
May 12 21:23:07 localhost systemd[1]: Failed to start User Manager for UID 1000.
May 12 21:23:07 localhost systemd[1]: user@1000.service: Unit entered failed state.
May 12 21:23:07 localhost systemd[1]: user@1000.service: Failed with result 'timeout'.

--- disable the service (manually with rm, since systemctl --user is broken); log out ---

May 12 21:23:47 localhost login[367]: pam_unix(login:session): session closed for user tom
May 12 21:23:47 localhost systemd[1]: getty@tty1.service: Service has no hold-off time, scheduling restart.
May 12 21:23:47 localhost systemd[1]: Stopped Getty on tty1.
May 12 21:23:47 localhost systemd[1]: Started Getty on tty1.
May 12 21:23:47 localhost systemd-logind[357]: Removed session c1.
May 12 21:23:47 localhost systemd[1]: Removed slice User Slice of tom.

--- log in ---

May 12 21:23:51 localhost login[387]: pam_unix(login:session): session opened for user tom by LOGIN(uid=0)
May 12 21:23:51 localhost systemd[1]: Created slice User Slice of tom.
May 12 21:23:51 localhost systemd[1]: Starting User Manager for UID 1000...
May 12 21:23:51 localhost systemd-logind[357]: New session c2 of user tom.
May 12 21:23:51 localhost systemd[393]: user@1000.service: Failed at step CGROUP spawning /usr/lib/systemd/systemd: No such file or directory
May 12 21:23:51 localhost systemd[1]: Started Session c2 of user tom.
May 12 21:23:51 localhost systemd[1]: Started User Manager for UID 1000.
May 12 21:23:51 localhost login[387]: LOGIN ON tty1 BY tom

--- log out ---

May 12 21:24:04 localhost login[387]: pam_unix(login:session): session closed for user tom
May 12 21:24:04 localhost systemd[1]: getty@tty1.service: Service has no hold-off time, scheduling restart.
May 12 21:24:04 localhost systemd[1]: Stopped Getty on tty1.
May 12 21:24:04 localhost systemd[1]: Started Getty on tty1.
May 12 21:24:04 localhost systemd-logind[357]: Removed session c2.
May 12 21:24:04 localhost systemd[1]: Removed slice User Slice of tom.

--- log in ---

May 12 21:24:08 localhost login[404]: pam_unix(login:session): session opened for user tom by LOGIN(uid=0)
May 12 21:24:08 localhost systemd[1]: Created slice User Slice of tom.
May 12 21:24:08 localhost systemd[1]: Starting User Manager for UID 1000...
May 12 21:24:08 localhost systemd-logind[357]: New session c3 of user tom.
May 12 21:24:08 localhost systemd[1]: Started Session c3 of user tom.
May 12 21:24:08 localhost systemd[406]: pam_unix(systemd-user:session): session opened for user tom by (uid=0)
May 12 21:24:08 localhost systemd[406]: Reached target Paths.
May 12 21:24:08 localhost systemd[406]: Starting D-Bus User Message Bus Socket.
May 12 21:24:08 localhost systemd[406]: Reached target Timers.
May 12 21:24:08 localhost login[404]: LOGIN ON tty1 BY tom
May 12 21:24:08 localhost systemd[406]: Listening on D-Bus User Message Bus Socket.
May 12 21:24:08 localhost systemd[406]: Reached target Sockets.
May 12 21:24:08 localhost systemd[406]: Reached target Basic System.
May 12 21:24:08 localhost systemd[406]: Reached target Default.
May 12 21:24:08 localhost systemd[406]: Startup finished in 6ms.
May 12 21:24:08 localhost systemd[1]: Started User Manager for UID 1000.

--- enable the service again (with systemctl --user; it works again) ---

May 12 21:24:36 localhost systemd[406]: Reloading.

--- log out ---

May 12 21:24:42 localhost login[404]: pam_unix(login:session): session closed for user tom
May 12 21:24:42 localhost systemd[1]: getty@tty1.service: Service has no hold-off time, scheduling restart.
May 12 21:24:42 localhost systemd[1]: Stopped Getty on tty1.
May 12 21:24:42 localhost systemd[1]: Started Getty on tty1.
May 12 21:24:42 localhost systemd-logind[357]: Removed session c3.
May 12 21:24:42 localhost systemd[1]: Stopping User Manager for UID 1000...
May 12 21:24:42 localhost systemd[406]: Stopped target Default.
May 12 21:24:42 localhost systemd[406]: Stopped target Basic System.
May 12 21:24:42 localhost systemd[406]: Stopped target Sockets.
May 12 21:24:42 localhost systemd[406]: Closed D-Bus User Message Bus Socket.
May 12 21:24:42 localhost systemd[406]: Reached target Shutdown.
May 12 21:24:42 localhost systemd[406]: Starting Exit the Session...
May 12 21:24:42 localhost systemd[408]: pam_unix(systemd-user:session): session closed for user tom
May 12 21:24:42 localhost systemd[406]: Stopped target Paths.
May 12 21:24:42 localhost systemd[406]: Stopped target Timers.
May 12 21:24:42 localhost systemd[406]: Received SIGRTMIN+24 from PID 424 (kill).
May 12 21:24:42 localhost systemd[1]: Stopped User Manager for UID 1000.
May 12 21:24:42 localhost systemd[1]: Removed slice User Slice of tom.

--- insert the device (USB sound card with id "Audio") ---

May 12 21:24:55 localhost kernel: usb 1-3: new high-speed USB device number 5 using xhci_hcd
May 12 21:24:55 localhost kernel: input: Generic USB Audio as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.3/0003:0BDA:4835.0005/input/input12
May 12 21:24:55 localhost kernel: hid-generic 0003:0BDA:4835.0005: input,hiddev0,hidraw4: USB HID v1.11 Device [Generic USB Audio] on usb-0000:00:14.0-3/input3
May 12 21:24:57 localhost kernel: usbcore: registered new interface driver snd-usb-audio
May 12 21:24:57 localhost systemd[1]: Reached target Sound Card.

--- log in ---

May 12 21:25:02 localhost login[423]: pam_unix(login:session): session opened for user tom by LOGIN(uid=0)
May 12 21:25:02 localhost systemd[1]: Created slice User Slice of tom.
May 12 21:25:02 localhost systemd[1]: Starting User Manager for UID 1000...
May 12 21:25:02 localhost systemd-logind[357]: New session c4 of user tom.
May 12 21:25:02 localhost systemd[1]: Started Session c4 of user tom.
May 12 21:25:02 localhost systemd[436]: pam_unix(systemd-user:session): session opened for user tom by (uid=0)
May 12 21:25:02 localhost systemd[436]: Reached target Timers.
May 12 21:25:02 localhost systemd[436]: Reached target Paths.
May 12 21:25:02 localhost systemd[436]: Starting D-Bus User Message Bus Socket.
May 12 21:25:02 localhost systemd[436]: Created slice jackd.slice.
May 12 21:25:02 localhost systemd[436]: Listening on D-Bus User Message Bus Socket.
May 12 21:25:02 localhost systemd[436]: Reached target Sockets.
May 12 21:25:02 localhost systemd[436]: Reached target Basic System.
May 12 21:25:02 localhost systemd[436]: Started jackd@Audio.service.
May 12 21:25:02 localhost login[423]: LOGIN ON tty1 BY tom
May 12 21:25:02 localhost systemd[436]: Reached target Default.
May 12 21:25:03 localhost jackd[442]: jackd 0.125.0
May 12 21:25:03 localhost jackd[442]: Copyright 2001-2009 Paul Davis, Stephane Letz, Jack O'Quinn, Torben Hohn and others.
May 12 21:25:03 localhost jackd[442]: jackd comes with ABSOLUTELY NO WARRANTY
May 12 21:25:03 localhost jackd[442]: This is free software, and you are welcome to redistribute it
May 12 21:25:03 localhost jackd[442]: under certain conditions; see the file COPYING for details
May 12 21:25:02 localhost systemd[436]: Startup finished in 6ms.
May 12 21:25:02 localhost systemd[1]: Started User Manager for UID 1000.
May 12 21:25:03 localhost jackd[442]: JACK compiled with System V SHM support.
May 12 21:25:04 localhost jackd[442]: loading driver ..
May 12 21:25:04 localhost jackd[442]: apparent rate = 44100
May 12 21:25:04 localhost jackd[442]: creating alsa driver ... hw:Audio|-|1024|2|44100|0|0|nomon|swmeter|-|32bit
May 12 21:25:04 localhost jackd[442]: configuring for 44100Hz, period = 1024 frames (23.2 ms), buffer = 2 periods
May 12 21:25:04 localhost jackd[442]: ALSA: final selected sample format for playback: 24bit little-endian in 3bytes format
May 12 21:25:04 localhost jackd[442]: ALSA: use 2 periods for playback
```

**Comment by poettering** [comment] 2017-05-29 15:55
I figure this is kinda a duplicate of #5966, no?

**Closed as completed** 2017-11-09 07:32 UTC
