### ISSUE TITLE
RFE: "systemctl disable" on a disabled unit should probably print a quick message about that, instead of showing nothing

### ISSUE THREAD

**Issue by ewtoombs** [systemd/systemd#5750] opened 2017-04-18 15:21 UTC
### Submission type

  - [* ] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232-8

### Used distribution

> archlinux

### In case of bug report: Expected behaviour you didn't see

> deliver error, suggest correct command (mask)
```
% systemctl --user disable pulseaudio.socket
No symlinks were deleted. No change has been made to the configuration.
Did you mean to use systemctl --user mask?
%
```

### In case of bug report: Unexpected behaviour you saw

> no errors, even though operation failed.

### In case of bug report: Steps to reproduce the problem

```
% systemctl --user disable pulseaudio.socket
%
```

**Comment by poettering** [comment] 2017-04-24 13:09
I am very strongly against the suggestion to use "systemctl mask", as masking is a last resort thing, the big hammer that you only use if you really really know what you do and are capable of handling such a big hammer. It's not something we should point people to, as it should not be part of normal workflow.

That said, it might make sense to log a quick message if a unit is asked to be disabled, but there's nothing to disable because it already is disabled.

**Comment by ewtoombs** [comment] 2017-04-27 23:34
Well, if I want to disable a globally enabled user service like pulseaudio on startup but only for my user, how else would I do it? For system services, it is kind of nonsense, but for user services, it seems pretty natural and common to me. You'd only deliver the hint when it's a user service that somebody is trying to disable. Anyway, just the error message is still a huge improvement. Thanks for considering that.

**Comment by poettering** [comment] 2017-04-30 11:42
There were discussions to permit "systemctl disable" on a system service carrying [Install] data which was enabled via symlinks in /usr, by creating /dev/null symlinks in /etc. This wasn't implemented so far, but it would deliver what you are asking for in the user case.

**Comment by ewtoombs** [comment] 2017-05-06 22:57
Well, that would be cool. Is there an open issue for this? I'd like to follow it.

**Comment by poettering** [comment] 2020-05-19 16:21
This is actually a duplicate of #4012.

**Closed as completed by poettering** 2020-05-19 16:21 UTC
Labels: RFE 🎁, systemctl, duplicate
