### ISSUE TITLE
GetUnitProcesses should only show info for the current user's unit when /proc access is restricted

### ISSUE THREAD

**Issue by nixbitcoin** [systemd/systemd#16825] opened 2020-08-24 10:47 UTC
**systemd version the issue has been seen with**
> systemd 243

**Used distribution**
 > NixOS 20.03

**Expected behaviour you didn't see**
 > `systemctl status <service name>` should only show `CGroup` information for the current user's unit when `/proc` access is restricted

**Unexpected behaviour you saw**
 > When run from a less-privileged user  `systemctl status <service name>` shows `CGroup` information for other less-privileged user's units.

**Steps to reproduce the problem**
1. Set `hidepid=2`
2. Run a unit that places secrets in command line arguments like [c-lightning](https://github.com/elementsproject/lightning)
3. In the first few seconds of start up run `systemctl status clightning` and see how it leaks bitcoind rpc passwords while connecting to bitcoind

Of course, this should also be fixed upstream but I think it would be a general security improvement to restrict current user's access to process information when `/proc` access is restricted.

**Comment by poettering** [comment] 2020-08-24 16:21
We do not support hidepid= on the host `/proc`, sorry. This cannot work. Please see #16681 for a per-service hookup for this.

Duplicate of #12955 with further info why this is not supportable for the main host `/proc/`

**Closed as completed by poettering** 2020-08-24 16:21 UTC
Labels: pid1, not-supported

**Comment by poettering** [comment] 2021-08-12 12:00
well, ProtectProc= makes the whole of /proc unavailable for unrelated process, i.e. all the APIs it provides both for introspection and for control. Whether there are other APIs to get the parts of the same info is not really an issue of ProtectProc= and people shouldn't believe it was. 

If you don't want to open up the systemctl status process tree up for processes in your service, then disallow access to the bus api for example, or the GetProcesses() api. But even if not, it's still a *much* smaller surface, as it only shows pids and names, nothing else. not even uid info or so
