### ISSUE TITLE
90 seconds delay during boot, trying to rename 2 interfaces to eno1.

### ISSUE THREAD

**Issue by kroeckx** [systemd/systemd#14886] opened 2020-02-15 15:59 UTC
I get a 90 seconds delay during boot. It seems that hanging trying to rename an interface. dmesg shows:
```
[    2.524990] igb 0000:01:00.0: added PHC on eth0
[    2.524996] igb 0000:01:00.0: Intel(R) Gigabit Ethernet Network Connection
[    2.525002] igb 0000:01:00.0: eth0: (PCIe:2.5Gb/s:Width x1) XX:XX:XX:XX:XX:43
[    2.525067] igb 0000:01:00.0: eth0: PBA No: 000300-000
[    2.525072] igb 0000:01:00.0: Using MSI-X interrupts. 4 rx queue(s), 4 tx queue(s)
[...]
[    2.554624] igb 0000:02:00.0: added PHC on eth1
[    2.554630] igb 0000:02:00.0: Intel(R) Gigabit Ethernet Network Connection
[    2.554636] igb 0000:02:00.0: eth1: (PCIe:2.5Gb/s:Width x1) XX:XX:XX:XX:XX:44
[    2.554702] igb 0000:02:00.0: eth1: PBA No: 000300-000
[    2.554707] igb 0000:02:00.0: Using MSI-X interrupts. 4 rx queue(s), 4 tx queue(s)
[    2.566821] igb 0000:01:00.0 eno1: renamed from eth0
[...]
[    2.606909] igb 0000:02:00.0 rename3: renamed from eth1
[...]
[    3.249856] sd 1:0:0:0: [sda] Attached SCSI disk
[   63.258688] systemd-udevd[101]: eth1: Worker [128] processing SEQNUM=1438 is taking a long time
[   93.193528] systemd-udevd[128]: eth1: Failed to rename network interface 3 from 'eth1' to 'eno1': File exists
[   93.205214] systemd-udevd[127]: Using default interface naming scheme 'v240'.
[...]
[  110.007404] IPv6: ADDRCONF(NETDEV_UP): eno1: link is not ready
[  111.113963] NFSD: starting 90-second grace period (net f0000098)
[  112.994184] igb 0000:01:00.0 eno1: igb: eno1 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX/TX
[  112.994513] IPv6: ADDRCONF(NETDEV_CHANGE): eno1: link becomes ready
```

For some reason it's trying to rename both eth0 and eth1 to eno1. It seems to try to do:
eth0 -> eno1
eth1 -> rename3
eth1 -> eno1

I don't seem to have a file that gives the devices a persistent name.

ip addr shows:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether XX:XX:XX:XX:XX:43 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.7/24 brd 192.168.0.255 scope global eno1
       valid_lft forever preferred_lft forever
    inet6 XXXX/64 scope global dynamic mngtmpaddr 
       valid_lft 239811sec preferred_lft 67011sec
    inet6 fe80::XXXX/64 scope link 
       valid_lft forever preferred_lft forever
3: rename3: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether XX:XX:XX:XX:XX:44 brd ff:ff:ff:ff:ff:ff
```

I'm using Debian buster, version 241-7~deb10u3

**Comment by yuwata** [comment] 2020-02-15 16:12
How do you rename the interface? By using .link file?

**Comment by kroeckx** [comment] 2020-02-15 16:18
I assume this is what systemd does by default. I can't find any
file saying it should be named like that.

**Comment by yuwata** [comment] 2020-02-15 16:37
The name 'rename3' is not in systemd's default naming scheme. Please find which try to rename the interface to 'rename3'.

**Comment by mbiebl** [comment] 2020-02-15 17:12
@yuwata That is likely https://salsa.debian.org/systemd-team/systemd/blob/debian/buster/debian/patches/debian/Revert-udev-network-device-renaming-immediately-give.patch

**Comment by mbiebl** [comment] 2020-02-15 17:15
Afaics the problem is that both eth0 and eth1 are attempted to be renamed to eno1

**Comment by kroeckx** [comment] 2020-02-15 17:17
I do not find any file in /etc, /var, or even /usr that mentions
rename3, except for /var/log/

There is a file /run/udev/data/n3 that has the following in it:
I:93196561
E:ID_NET_NAMING_SCHEME=v240
E:ID_NET_NAME_MAC=enxXXXXXXXXXX44
E:ID_OUI_FROM_DATABASE=Thecus Technology Corp.
E:ID_NET_NAME_ONBOARD=eno1
E:ID_NET_LABEL_ONBOARD=en Onboard LAN
E:ID_NET_NAME_PATH=enp2s0
E:ID_BUS=pci
E:ID_VENDOR_ID=0x8086
E:ID_MODEL_ID=0x1533
E:ID_PCI_CLASS_FROM_DATABASE=Network controller
E:ID_PCI_SUBCLASS_FROM_DATABASE=Ethernet controller
E:ID_VENDOR_FROM_DATABASE=Intel Corporation
E:ID_MODEL_FROM_DATABASE=I210 Gigabit Network Connection
E:ID_PATH=pci-0000:02:00.0
E:ID_PATH_TAG=pci-0000_02_00_0
E:ID_NET_DRIVER=igb
E:ID_NET_LINK_FILE=/usr/lib/systemd/network/99-default.link
E:SYSTEMD_ALIAS=/sys/subsystem/net/devices/rename3
G:systemd

While n2 contains:
I:2608899
E:ID_NET_NAMING_SCHEME=v240
E:ID_NET_NAME_MAC=enxXXXXXXXXXX43
E:ID_OUI_FROM_DATABASE=Thecus Technology Corp.
E:ID_NET_NAME_ONBOARD=eno1
E:ID_NET_LABEL_ONBOARD=en Onboard LAN
E:ID_NET_NAME_PATH=enp1s0
E:ID_BUS=pci
E:ID_VENDOR_ID=0x8086
E:ID_MODEL_ID=0x1533
E:ID_PCI_CLASS_FROM_DATABASE=Network controller
E:ID_PCI_SUBCLASS_FROM_DATABASE=Ethernet controller
E:ID_VENDOR_FROM_DATABASE=Intel Corporation
E:ID_MODEL_FROM_DATABASE=I210 Gigabit Network Connection
E:ID_PATH=pci-0000:01:00.0
E:ID_PATH_TAG=pci-0000_01_00_0
E:ID_NET_DRIVER=igb
E:ID_NET_LINK_FILE=/usr/lib/systemd/network/99-default.link
E:SYSTEMD_ALIAS=/sys/subsystem/net/devices/eno1
G:systemd

**Comment by yuwata** [comment] 2020-02-15 17:24
It seems a firmware's bug. Please try to use the naming scheme based on the path, e.g., create the following file:
```
# /etc/systemd/network/99-default.link.d/override.conf
[Link]
NamePolicy=keep kernel database slot path
```

**Comment by kroeckx** [comment] 2020-02-15 20:57
Will that rename my device to eth0, and so not come up?

Can you explain on which information from the firmware this is
based?

**Comment by poettering** [comment] 2020-04-02 07:49
So the trigger is a firmware issue, there's nothing we can do about this, it reports the same id for two different network interfaces. it might make sense for the kernel to suppress this info, since it is easily detect, but doing so from userspace is much harder, since the info appears asynchronously, thus when the first device appears we cannot possibly detect the conflict, and when the second device appears we could detect the conflict but then it is too late for the first device.

Anyway, I'd really suggest the kernel to suppress this info from sysfs if it is not fond to be consistent with itself. But not sure the kernel peeps can be convinced of that.

Ideally of course a firmware upgrade can fix this for you.

Alternatively you can follow @yuwata's idea to change the policy.

The delay is caused by a DEbian specific patch that is something we dropped many years ago upstream because of issues like this. I really think debian should drop that too. Without the patch we'd just give up, i.e. one device wuld not be renamed, and it wouldn't be deterministic which one, but at least we wouldn't totally fail.

The data comes from ACPI _DSM and is what is exposed by the kernel in the `acpi_index` sysfs attribute file of PCI devices. (see PCI spec). your firmware is clearly in violation of the spec, first paragraph makes clear the index is supposed to be uniquely assigned but it isn't on your system.

I am inclined to closing this issue here, since it is triggered by firmware issue, we can't really fix it in userspace and the 90s are a debian specific failure that does not exist upstream

**Comment by mbiebl** [comment] 2020-04-02 08:02
> The delay is caused by a DEbian specific patch that is something we dropped many years ago upstream because of issues like this. I really think debian should drop that too.

Debian buster was the last release shipping that patch. It was dropped in the mean time and is not part of sid or the upcoming bullseye release anymore.

**Comment by poettering** [comment] 2020-04-23 12:21
ok, let's close, for the reasons outlined above

**Closed as completed by poettering** 2020-04-23 12:21 UTC
Labels: udev, needs-reporter-feedback ❓
