### ISSUE TITLE
Regression after upgrading resolved from 252.5 to 253: slow reverse DNS lookups

### ISSUE THREAD

**Issue by gentoo-root** [systemd/systemd#26594] opened 2023-02-26 13:11 UTC
### systemd version the issue has been seen with

253

### Used distribution

Arch linux

### Linux kernel version used

6.1.12-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

Reverse DNS lookup should be fast if the upstream DNS server returns NXDOMAIN:

```
$ time nslookup 128.1.1.1
** server can't find 1.1.1.128.in-addr.arpa: NXDOMAIN


________________________________________________________
Executed in  150.51 millis    fish           external
   usr time    7.39 millis  553.00 micros    6.83 millis
   sys time    6.77 millis    0.00 micros    6.77 millis

exit code: 1
```

This is a sample output from systemd-252.5.

### Unexpected behaviour you saw

After upgrading systemd to 253, the above test takes 15 seconds before failing:

```
$ time nslookup 128.1.1.1
;; communications error to 127.0.0.53#53: timed out
;; communications error to 127.0.0.53#53: timed out
;; communications error to 127.0.0.53#53: timed out
;; no servers could be reached



________________________________________________________
Executed in   15.03 secs      fish           external
   usr time   19.56 millis   11.18 millis    8.38 millis
   sys time    4.33 millis    0.15 millis    4.17 millis

exit code: 1
```

Also, instead of NXDOMAIN, it returns an I/O error with resolved itself, which suggests a bug in resolved.

### Steps to reproduce the problem

1. Upgrade systemd from 252.5 to 253, `systemctl restart systemd-resolved.service`.
2. Run `time nslookup 128.1.1.1` and measure time it takes to complete.
3. With systemd 253 it completes in 15 seconds and returns a "communications error to 127.0.0.53#53: timed out", and with systemd 252.5 it completes in less than a second and returns NXDOMAIN, as it should.

Instead of 128.1.1.1, you can use any other valid and routable IPv4 or IPv6 that doesn't have a PTR record. 128.1.1.1 is an arbitrary address used for an example purpose.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
$ grep '^hosts:' /etc/nsswitch.conf
hosts: mymachines resolve [!UNAVAIL=return] files myhostname dns
```

**Comment by rpigott** [comment] 2023-02-27 01:42
Possible dupe of #14735? Can you capture systemd-resolved log using SYSTEMD_LOG_LEVEL=debug?

**Comment by yuwata** [comment] 2023-03-04 12:33
Please try to disable MulticastDNS.

**Comment by YHNdnzj** [comment] 2023-03-04 13:04
But the default value of it is changed:
https://github.com/systemd/systemd/blob/v253/NEWS#L88

Disabling MulticastDNS worked around the issue, but I see it's not a new

**Comment by yuwata** [comment] 2023-03-04 13:10
> Disabling MulticastDNS worked around the issue, but I see it's not a new option in 253, and older versions didn't suffer from this issue, even with MulticastDNS enabled.

Yeah, (unfortunately?) the default value for `MulticastDNS=` was changed in v253. See e31540196b8fb136a8f197c7a26d851bd0b93329, the relevant discussion, and the relevant news entry.

Though, I am not familiar with the difference between mDNS and LLMNR, but LLMNR was enabled by default previously. Why LLMNR did not slow down querying DNS lookup??

**Comment by yuwata** [comment] 2023-03-04 14:20
The commit e31540196b8fb136a8f197c7a26d851bd0b93329 changes the per-link default for mDNS, not the global default.

**Comment by rulatir** [comment] 2023-04-27 15:03
> Disabling MulticastDNS worked around the issue

Can I have a complete instruction on how to apply this workaround on my system? I know nothing about systemd resolver functionality beyond vaguely sensing that it is insanely complex, and I am bitten by this issue - not just because I see the "communications error... timed out" message in nslookup output, but also because renewing certificates with certbot fails due to a DNS timeout, and I strongly suspect this is the same issue.

**Comment by rpigott** [comment] 2023-06-22 08:29
> Though, I am not familiar with the difference between mDNS and LLMNR, but LLMNR was enabled by default previously. Why LLMNR did not slow down querying DNS lookup??

@yuwata It's the reverse lookup. We have  NXDOMAIN response from dns but wait for mdns. All addresses are currently considered in scope for mdns, and it usually has no mechanism but a timeout to indicate a negative response. The discussion in #27001 is probably relevant.

It is not generally true that domains always have a PTR record. Here is an example I recorded just now using "example.com":

```
$ dig @1.1.1.1 +noall +ans A example.com
example.com.		69806	IN	A	93.184.216.34
$ dig @1.1.1.1 -x 93.184.216.34 | grep status             
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 3598
$ time resolvectl query 93.184.216.34             
93.184.216.34: resolve call failed: All attempts to contact name servers or networks failed
resolvectl query 93.184.216.34  0.01s user 0.00s system 0% cpu 7.550 total
```

<details><summary>associated systemd-resolved log</summary>

```
Jun 22 01:08:22 rdtw systemd-resolved[659]: Setting log level to debug.
Jun 22 01:08:22 rdtw systemd-resolved[659]: Sent message type=method_return sender=n/a destination=:1.345 path=n/a interface=n/a member=n/a cookie=182 reply_cookie=3 signature=n/a error-name=n/a error-message=n/a
Jun 22 01:08:26 rdtw systemd-resolved[659]: Got message type=method_call sender=:1.346 destination=org.freedesktop.resolve1 path=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=ResolveAddress  cookie=2 reply_cookie=0 signature=iiayt error-name=n/a error-message=n/a
Jun 22 01:08:26 rdtw systemd-resolved[659]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixProcessID cookie=183 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Jun 22 01:08:26 rdtw systemd-resolved[659]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.2 path=n/a interface=n/a member=n/a  cookie=83 reply_cookie=183 signature=u error-name=n/a error-message=n/a
Jun 22 01:08:26 rdtw systemd-resolved[659]: D-Bus address resolution request from client PID 35225 (resolvectl) with UID 1000
Jun 22 01:08:26 rdtw systemd-resolved[659]: Looking up RR for 34.216.184.93.in-addr.arpa IN PTR.
Jun 22 01:08:26 rdtw systemd-resolved[659]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=184 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Jun 22 01:08:26 rdtw systemd-resolved[659]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetNameOwner cookie=185 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Jun 22 01:08:26 rdtw systemd-resolved[659]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.2 path=n/a interface=n/a member=n/a  cookie=85 reply_cookie=185 signature=s error-name=n/a error-message=n/a
Jun 22 01:08:26 rdtw systemd-resolved[659]: Cache miss for 34.216.184.93.in-addr.arpa IN PTR
Jun 22 01:08:26 rdtw systemd-resolved[659]: Firing regular transaction 39880 for <34.216.184.93.in-addr.arpa IN PTR> scope dns on enp4s0/* (validate=yes).
Jun 22 01:08:26 rdtw systemd-resolved[659]: Using feature level UDP+EDNS0 for transaction 39880.
Jun 22 01:08:26 rdtw systemd-resolved[659]: Using DNS server 10.3.0.254 for transaction 39880.
Jun 22 01:08:26 rdtw systemd-resolved[659]: Announcing packet size 1472 in egress EDNS(0) packet.
Jun 22 01:08:26 rdtw systemd-resolved[659]: Emitting UDP, link MTU is 1500, socket MTU is 0, minimal MTU is 40
Jun 22 01:08:26 rdtw systemd-resolved[659]: Sending query packet with id 39880 of size 55.
Jun 22 01:08:26 rdtw systemd-resolved[659]: Cache miss for 34.216.184.93.in-addr.arpa IN PTR
Jun 22 01:08:26 rdtw systemd-resolved[659]: Firing regular transaction 3305 for <34.216.184.93.in-addr.arpa IN PTR> scope mdns on enp4s0/INET (validate=yes).
Jun 22 01:08:26 rdtw systemd-resolved[659]: Delaying mdns transaction 3305 for 0us.
Jun 22 01:08:26 rdtw systemd-resolved[659]: Initial jitter phase for transaction 3305 elapsed.
Jun 22 01:08:26 rdtw systemd-resolved[659]: Retrying transaction 3305.
Jun 22 01:08:26 rdtw systemd-resolved[659]: Cache miss for 34.216.184.93.in-addr.arpa IN PTR
Jun 22 01:08:26 rdtw systemd-resolved[659]: Firing regular transaction 3305 for <34.216.184.93.in-addr.arpa IN PTR> scope mdns on enp4s0/INET (validate=yes).
Jun 22 01:08:26 rdtw systemd-resolved[659]: Sending query packet with id 0 on interface 2/AF_INET of size 44.
Jun 22 01:08:26 rdtw systemd-resolved[659]: Received mdns UDP packet of size 44, ifindex=2, ttl=255, fragsize=0, sender=10.3.0.5, destination=224.0.0.251
Jun 22 01:08:26 rdtw systemd-resolved[659]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.2 path=n/a interface=n/a member=n/a  cookie=84 reply_cookie=184 signature=n/a error-name=n/a error-message=n/a
Jun 22 01:08:26 rdtw systemd-resolved[659]: Match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0=':1.346' successfully installed.
Jun 22 01:08:26 rdtw systemd-resolved[659]: Received dns UDP packet of size 55, ifindex=2, ttl=0, fragsize=0, sender=10.3.0.254, destination=10.3.0.5
Jun 22 01:08:26 rdtw systemd-resolved[659]: Processing incoming packet of size 55 on transaction 39880 (rcode=NXDOMAIN).
Jun 22 01:08:26 rdtw systemd-resolved[659]: Server returned error NXDOMAIN in EDNS0 mode, retrying transaction with reduced feature level UDP (DVE-2018-0001 mitigation)
Jun 22 01:08:26 rdtw systemd-resolved[659]: Retrying transaction 39880.
Jun 22 01:08:26 rdtw systemd-resolved[659]: Cache miss for 34.216.184.93.in-addr.arpa IN PTR
Jun 22 01:08:26 rdtw systemd-resolved[659]: Firing regular transaction 39880 for <34.216.184.93.in-addr.arpa IN PTR> scope dns on enp4s0/* (validate=yes).
Jun 22 01:08:26 rdtw systemd-resolved[659]: Using feature level UDP for transaction 39880.
Jun 22 01:08:26 rdtw systemd-resolved[659]: Emitting UDP, link MTU is 1500, socket MTU is 1500, minimal MTU is 40
Jun 22 01:08:26 rdtw systemd-resolved[659]: Sending query packet with id 39880 of size 44.
Jun 22 01:08:26 rdtw systemd-resolved[659]: Received dns UDP packet of size 44, ifindex=2, ttl=0, fragsize=0, sender=10.3.0.254, destination=10.3.0.5
Jun 22 01:08:26 rdtw systemd-resolved[659]: Processing incoming packet of size 44 on transaction 39880 (rcode=NXDOMAIN).
Jun 22 01:08:26 rdtw systemd-resolved[659]: Not caching negative entry without a SOA record: 34.216.184.93.in-addr.arpa IN PTR
Jun 22 01:08:26 rdtw systemd-resolved[659]: Regular transaction 39880 for <34.216.184.93.in-addr.arpa IN PTR> on scope dns on enp4s0/* now complete with <rcode-failure> from network (unsigned; non-confidential).
Jun 22 01:08:27 rdtw systemd-resolved[659]: Timeout reached on transaction 3305.
Jun 22 01:08:27 rdtw systemd-resolved[659]: Retrying transaction 3305.
Jun 22 01:08:27 rdtw systemd-resolved[659]: Cache miss for 34.216.184.93.in-addr.arpa IN PTR
Jun 22 01:08:27 rdtw systemd-resolved[659]: Firing regular transaction 3305 for <34.216.184.93.in-addr.arpa IN PTR> scope mdns on enp4s0/INET (validate=yes).
Jun 22 01:08:27 rdtw systemd-resolved[659]: Sending query packet with id 0 on interface 2/AF_INET of size 44.
Jun 22 01:08:27 rdtw systemd-resolved[659]: Received mdns UDP packet of size 44, ifindex=2, ttl=255, fragsize=0, sender=10.3.0.5, destination=224.0.0.251
Jun 22 01:08:29 rdtw systemd-resolved[659]: Timeout reached on transaction 3305.
Jun 22 01:08:29 rdtw systemd-resolved[659]: Retrying transaction 3305.
Jun 22 01:08:29 rdtw systemd-resolved[659]: Cache miss for 34.216.184.93.in-addr.arpa IN PTR
Jun 22 01:08:29 rdtw systemd-resolved[659]: Firing regular transaction 3305 for <34.216.184.93.in-addr.arpa IN PTR> scope mdns on enp4s0/INET (validate=yes).
Jun 22 01:08:29 rdtw systemd-resolved[659]: Sending query packet with id 0 on interface 2/AF_INET of size 44.
Jun 22 01:08:29 rdtw systemd-resolved[659]: Received mdns UDP packet of size 44, ifindex=2, ttl=255, fragsize=0, sender=10.3.0.5, destination=224.0.0.251
Jun 22 01:08:33 rdtw systemd-resolved[659]: Timeout reached on transaction 3305.
Jun 22 01:08:33 rdtw systemd-resolved[659]: Retrying transaction 3305.
Jun 22 01:08:33 rdtw systemd-resolved[659]: Regular transaction 3305 for <34.216.184.93.in-addr.arpa IN PTR> on scope mdns on enp4s0/INET now complete with <attempts-max-reached> from none (unsigned; non-confidential).
Jun 22 01:08:33 rdtw systemd-resolved[659]: Freeing transaction 39880.
Jun 22 01:08:33 rdtw systemd-resolved[659]: Sent message type=error sender=n/a destination=:1.346 path=n/a interface=n/a member=n/a cookie=186 reply_cookie=2 signature=s error-name=org.freedesktop.DBus.Error.Timeout error-message=All attempts to contact name servers or networks failed
Jun 22 01:08:33 rdtw systemd-resolved[659]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RemoveMatch cookie=187 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Jun 22 01:08:33 rdtw systemd-resolved[659]: Freeing transaction 3305.
Jun 22 01:08:36 rdtw systemd-resolved[659]: Got message type=method_call sender=:1.347 destination=org.freedesktop.resolve1 path=/org/freedesktop/LogControl1 interface=org.freedesktop.DBus.Properties member=Set  cookie=3 reply_cookie=0 signature=ssv error-name=n/a error-message=n/a
Jun 22 01:08:36 rdtw systemd-resolved[659]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixUser cookie=188 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Jun 22 01:08:36 rdtw systemd-resolved[659]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.2 path=n/a interface=n/a member=n/a  cookie=86 reply_cookie=188 signature=u error-name=n/a error-message=n/a
Jun 22 01:08:36 rdtw systemd-resolved[659]: Setting log level to info.
```
</details>

In these cases we are currently required to wait for the timeout.

**Comment by FranklinYu** [comment] 2023-10-22 05:57
How was it implemented in other mDNS clients? Do they simply break the protocol?

**Comment by lollipopman** [comment] 2024-01-12 18:52
The spec only mentions reverse lookups on the assigned mDNS domains:

> Unlike conventional DNS names, names that end in ".local." have only
> local significance.  The same is true of names within the IPv4 link-
> local reverse mapping domain "254.169.in-addr.arpa." and the IPv6
> link-local reverse mapping domains "8.e.f.ip6.arpa.",
> "9.e.f.ip6.arpa.", "a.e.f.ip6.arpa.", and "b.e.f.ip6.arpa.".

Are we sure all other reverse lookups should go to mDNS?

* https://datatracker.ietf.org/doc/html/rfc6762#section-4
* https://datatracker.ietf.org/doc/html/rfc6762#section-12

I also am experiencing timeouts with mdns enabled, rather than an NXDOMAIN, as expected.

**Comment by rpigott** [comment] 2024-01-12 19:13
I tried to make the argument in #28166 and #27001 that they should not. Feel free to bolster it, if you can.

**Comment by poettering** [comment] 2024-04-15 11:24
CLosing because #31645 was merged.

**Closed as completed by poettering** 2024-04-15 11:24 UTC
Labels: bug 🐛, resolve, regression ⚠️
