### ISSUE TITLE
systemd-nspawn: machinectl reboot shuts the container down instead of rebooting it

### ISSUE THREAD

**Issue by kakra** [systemd/systemd#10091] opened 2018-09-14 21:47 UTC
**systemd version the issue has been seen with**
> 239 (and as long as I can remember)

**Used distribution**
 > Gentoo Linux

**Expected behaviour you didn't see**
 > Log into the machine, run `reboot` OR use `machinectl reboot machine_name` didn't reboot the machine as expected, instead it stayed in shutdown state.

**Unexpected behaviour you saw**
 > When rebooting a general Linux container, no matter which way you do it, results in a lost connection. The machine is down and stays there forever.

**Steps to reproduce the problem**
See above: Use any of both ways to reboot an nspawn container machine. This is a long-standing bug as far as I can tell.

**Comment by yuwata** [comment] 2018-09-15 08:35
I think this is a duplicate of #2809.

> This is a long-standing bug as far as I can tell.

Yeah...

**Closed as completed by yuwata** 2018-09-15 08:35 UTC
Labels: machine, duplicate
