### ISSUE TITLE
systemd-resolved: Implement RFC 8767 for local cache

### ISSUE THREAD

**Issue by nexoscp** [systemd/systemd#21861] opened 2021-12-22 14:51 UTC
[RFC 8767](https://www.rfc-editor.org/rfc/rfc8767):

> This document defines a method (serve-stale) for recursive resolvers to use stale DNS data to avoid outages when authoritative nameservers cannot be reached to refresh expired data. One of the motivations for serve-stale is to make the DNS more resilient to DoS attacks and thereby make them less attractive as an attack vector.

**Comment by nexoscp** [comment] 2021-12-22 15:35
May be a duplicate of [Issue 21815](https://github.com/systemd/systemd/issues/21815)

**Comment by bluca** [comment] 2021-12-22 16:43
duplicate of https://github.com/systemd/systemd/issues/21815

**Closed as completed by bluca** 2021-12-22 16:43 UTC
Labels: resolve, duplicate
