### ISSUE TITLE
Old transient host-name not replaced by new one

### ISSUE THREAD

**Issue by Ricky-Tigg** [systemd/systemd#21446] opened 2021-11-19 13:26 UTC
**systemd version the issue has been seen with**
 > 249.7

**Used distribution**
 > Fedora

**Linux kernel version used** (`uname -a`)
 > `Linux DESKTOP-JAQA2JI 5.14.17-301.fc35.x86_64 #1 SMP Mon Nov 8 13:57:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > see `uname -a`

**Expected behaviour you didn't see**
 > Newly set transient host-name is not persistently replacing the old one

**Unexpected behaviour you saw**
 > While there has been no Shell session active for a random duration, is the old transient host-name always applied back by the system itself. 

**Steps to reproduce the problem**
 > _Tested in:_ `gnome-terminal`.

**Additional program output to the terminal**
```
[yk@DESKTOP-JAQA2JI ~]$ hostnamectl status | sed -n '1p;3p'
   Static hostname: n/a
Transient hostname: DESKTOP-JAQA2JI
[yk@DESKTOP-JAQA2JI ~]$ sudo hostnamectl --transient set-hostname linux
[yk@DESKTOP-JAQA2JI ~]$ sudo systemctl restart systemd-hostnamed.service
[yk@DESKTOP-JAQA2JI ~]$ hostnamectl --transient status
linux
[yk@DESKTOP-JAQA2JI ~]$ exit
```
If you decide to reopen a Shell session immediately, and otherwise with a few seconds brake between the openings of sessions, then the new transient host-name, seen in prompt as `[yk@linux~]$`, shall remain applied for several sessions. In any case, after a while, the old transient host-name shall be invariably applied back.

**Comment by poettering** [comment] 2021-11-22 09:06
I am not sure I follow what you are saying, but it sure appears as if your network management service is resetting the transient hostname for you? 

That's hardly something we can do anything about: we just do what clients tell us to do...

**Comment by Ricky-Tigg** [comment] 2021-11-22 12:02
How have you managed to misinterpret something? Cannot even guess. So we have '_network management_', as unique concrete though and unectedly suggested as guilty component. That is then _NetworkManager_ – version 1.32.12. "_we just do what clients tell us to do_": that's fine with me, so according to you, what is that thing that my commands could have had to say so that it goes wrong?

**Comment by Ricky-Tigg** [comment] 2021-11-22 12:05
How have you managed to misinterpret something then? Cannot even guess. So we have '_network management_', as unique concrete though and unexpectedly suggested as guilty component. That is then _NetworkManager_ – version 1.32.12. "_we just do what clients tell us to do_": that's fine with me, so according to you, what is that thing that my commands could have had to say so that it goes wrong?

**Comment by poettering** [comment] 2021-11-22 12:08
I don't grok what you are saying? What#s the supposed bug here?

You are using NM and it changes your transient hostname, but you don't want that it does that? Then tell NM not to do so? But what are we supposed to do in systemd about it?

Totally not following what the issue is supposed to be here?

**Comment by Ricky-Tigg** [comment] 2021-11-22 13:33
A least for any user having posted a similar relevant and self explicit report, the whole meaning of your capacity as a developer to not understand is obvious enough not to be misunderstood. Try, if you can, to understand how big is the part of the **issues** present on this platform that are due to that rare talent. And all of this is public! Do that _member_ a favour and close. Well done then, you have not only wasted your colleges' time but my own.

**Comment by mrc0mmand** [comment] 2021-11-22 16:48
Honestly, I don't know what's the issue either. In your case, you have no static hostname set, and the transient hostname is being set by your network configuration (as described in the `hostnamectl` man page).

For example, if you use NetworkManager, you should take a look at `hostname-mode` option, which affects transient hostname (https://developer-old.gnome.org/NetworkManager/stable/NetworkManager.conf.html). Other dhcp client have similar options.

**Comment by poettering** [comment] 2021-11-22 17:16
OK, let's close, I don't see what systemd is supposed to do any different here, and quite frankly I don't appreciate such comments as those last one of the original reporter. Nonetheless, @mrc0mmand has been overly nice with his response hence I presume this all addressed.

Closing. (And for the future, please vent your frustration elsewhere, this is not the forum, and will eventually just get you banned here)

**Closed as completed by poettering** 2021-11-22 17:16 UTC
Labels: hostname
