### ISSUE TITLE
systemd-homed "Activation failed", "incomplete mode", need to `daemon-reload`

### ISSUE THREAD

**Issue by dchinmay2** [systemd/systemd#33541] opened 2024-06-29 04:58 UTC
### systemd version the issue has been seen with

256

### Used distribution

Arch Linux

### Linux kernel version used

6.9.6-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

homectl

### Expected behaviour you didn't see

Log in, all of my user services start

### Unexpected behaviour you saw

My user services don't start after logging in. Restarting them manually doesn't work, I need to `systemctl --user daemon-reload` first.

Full journalctl log of this boot is here: https://paste.sr.ht/~p00f/1b92a9579a7679bc2d89442efd50a115d0463d90, I've pasted what I found interesting below.

`journalctl --user` log is here: https://paste.sr.ht/~p00f/0593b61e7ac9b5371b26ec72d4ae89942c24796e

### Steps to reproduce the problem

Log in

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Jun 29 10:07:13 ganymede systemd-homework[614]: None of the supplied plaintext passwords unlock the user record's hashed passwords.
Jun 29 10:07:13 ganymede systemd-homed[468]: Activation failed: Password for home chinmay is incorrect or not sufficient for authentication.
Jun 29 10:07:13 ganymede systemd-homed[468]: chinmay: changing state activating-for-acquire → inactive
Jun 29 10:07:13 ganymede systemd-homed[468]: Got notification that all sessions of user chinmay ended, deactivating automatically.
Jun 29 10:07:13 ganymede systemd-homed[468]: Home chinmay already deactivated, no automatic deactivation needed.
Jun 29 10:07:13 ganymede (systemd)[597]: pam_warn(systemd-user:setcred): function=[pam_sm_setcred] flags=0x8002 service=[systemd-user] terminal=[] user=[chinmay] ruser=[<unknown>] rhost=[<unknown>]
Jun 29 10:07:13 ganymede systemd[1]: Finished User Runtime Directory /run/user/971.
Jun 29 10:07:13 ganymede systemd[1]: Starting User Manager for UID 971...
Jun 29 10:07:13 ganymede systemd-homed[468]: chinmay: changing state inactive → activating-for-acquire
Jun 29 10:07:13 ganymede systemd-homework[619]: None of the supplied plaintext passwords unlock the user record's hashed passwords.
Jun 29 10:07:13 ganymede (systemd)[618]: pam_warn(systemd-user:setcred): function=[pam_sm_setcred] flags=0x8002 service=[systemd-user] terminal=[] user=[greeter] ruser=[<unknown>] rhost=[<unknown>]
Jun 29 10:07:13 ganymede (systemd)[618]: pam_unix(systemd-user:session): session opened for user greeter(uid=971) by greeter(uid=0)
Jun 29 10:07:13 ganymede systemd-homed[468]: Activation failed: Password for home chinmay is incorrect or not sufficient for authentication.
Jun 29 10:07:13 ganymede systemd-homed[468]: chinmay: changing state activating-for-acquire → inactive
Jun 29 10:07:13 ganymede systemd-homed[468]: Got notification that all sessions of user chinmay ended, deactivating automatically.
Jun 29 10:07:13 ganymede (systemd)[597]: pam_systemd_home(systemd-user:session): Home for user chinmay acquired in incomplete mode, requires later activation.
Jun 29 10:07:13 ganymede (systemd)[597]: pam_unix(systemd-user:session): session opened for user chinmay(uid=60254) by chinmay(uid=0)
Jun 29 10:07:13 ganymede systemd-logind[469]: New session 3 of user greeter.
Jun 29 10:07:13 ganymede (systemd)[597]: pam_systemd(systemd-user:session): PAM session of class 'manager' is incomplete, which is not supported, ignoring.
```

**Comment by p00f** [comment] 2024-06-29 05:06
> `Jun 29 10:07:13 ganymede systemd-homework[614]: None of the supplied plaintext passwords unlock the user record's hashed passwords.`

But I typed the password correctly in the first try, and was able to log in

**Comment by p00f** [comment] 2024-07-07 06:04
Also, this happens when I start emacs as a service and try to compile an org file into pdf (`M-x org-latex-export-to-pdf RET`):
`Failed to upgrade session: Unknown object '/org/freedesktop/login1/session/self'.`

**Comment by p00f** [comment] 2024-07-08 17:23
There's also this in the log:
```
Jul 08 22:45:28 ganymede xdg-user-dirs-update[649]: Can't create dir //Desktop
Jul 08 22:45:28 ganymede xdg-user-dirs-update[649]: Can't create dir //Downloads
Jul 08 22:45:28 ganymede xdg-user-dirs-update[649]: Can't create dir //Templates
Jul 08 22:45:28 ganymede xdg-user-dirs-update[649]: Can't create dir //Public
Jul 08 22:45:28 ganymede xdg-user-dirs-update[649]: Can't create dir //Documents
Jul 08 22:45:28 ganymede xdg-user-dirs-update[649]: Can't create dir //Music
Jul 08 22:45:28 ganymede xdg-user-dirs-update[649]: Can't create dir //Pictures
Jul 08 22:45:28 ganymede xdg-user-dirs-update[649]: Can't create dir //Videos
```

**Comment by AdrianVovk** [comment] 2024-07-12 04:20
Oh dear...

Have you changed your password recently? Does/did this user (i.e. a user with the same name?) ever exist outside of homed?

What started triggering this? After a system update? After a password change? Have you ever touched PAM? Is this your first time trying to use homed?

If I had to guess, it looks like something along the following lines happened:
- Your system's PAM stack is misconfigured, and doesn't properly consider homed
- You started out with a traditional UNIX user (via /etc/passwd and /etc/shadow)
- You converted that user into homed. State defining the user in /etc/passwd and /etc/shadow got left over (or not and you PAM stack is just _really_ misconfigured)
- You tried to change the user's password at some point. Due to PAM stack misconfiguration it didn't fully pass that through to homed
- You try to log into the user. Due to PAM stack misconfiguration it ignores the fact that homed couldn't decrypt your home dir, and "logs you in" anyways. You're now logged into a user with a non-existent home directory.
- The home directory doesn't exist, so PAM falls back to HOME=/
- Chaos ensues

**Comment by p00f** [comment] 2024-07-12 05:30
This installation of Arch Linux started with only this homed user.

I corrupted the loopback file at some point trying to resize it, but fixed it using homectl's fsck I think - anyway, this was a long time ago, and I had no problems then

I did not touch PAM recently, nor did I change the password

Arch Linux has had homed for quite a while, so the PAM being misconfigured is unlikely

I think it's a system update

**Comment by p00f** [comment] 2024-07-12 05:33
Last pam update was on 11 April so that is unlikely too https://archlinux.org/packages/core/x86_64/pam/

**Comment by NekkoDroid** [comment] 2024-07-12 09:35
The only issue I can think of related to PAM is this issue that was brought up https://gitlab.archlinux.org/archlinux/packaging/packages/systemd/-/issues/31. Basically was that the new `/usr/bin/systemd-home-fallback-shell` wasn't added to the `/etc/shells` file causing `pam_shell.so` to fail.

**Comment by p00f** [comment] 2024-07-12 11:15
`/usr/bin/systemd-home-fallback-shell` is in my `/etc/shells`

**Comment by p00f** [comment] 2024-07-12 11:26
I also tried changing the password (to the same password)

**Comment by p00f** [comment] 2024-07-12 14:10
@AdrianVovk 
> The home directory doesn't exist, so PAM falls back to HOME=/

No, all my files are there when I log in. My user services are there too, except systemd doesn't see them until I daemon-reload

**Comment by AdrianVovk** [comment] 2024-07-12 14:18
Can you please log out, make sure the user is completely deactivated according to homectl, then use systemctl to set the log level of homed to debug, then log in again, and send the logs?

To make life easier, if possible please log in on a TTY so it doesn't start as many services.

**Comment by p00f** [comment] 2024-07-12 15:42
> Can you please log out, make sure the user is completely deactivated according to homectl, then use systemctl to set the log level of homed to debug, then log in again, and send the logs?
> 
> To make life easier, if possible please log in on a TTY so it doesn't start as many services.

Is  "inactive" completely deactivated?
![2024-07-12-21-12-20-011.jpg](https://github.com/user-attachments/assets/83f73680-4fc8-4b26-bd74-f19c8189dc7b)

**Comment by p00f** [comment] 2024-07-12 15:51
@AdrianVovk `--user` log: https://paste.sr.ht/~p00f/f0f8b8c4f70e299227b88758cb79197a401055a3

system log: https://paste.sr.ht/~p00f/c6bf288e5f7ed74fa4f6762f055cd58f159363b4

**Comment by AdrianVovk** [comment] 2024-07-15 21:23
Can you reproduce this w/ GDM?

**Comment by p00f** [comment] 2024-07-16 02:18
Yes

**Comment by AdrianVovk** [comment] 2024-08-27 18:35
We have continued debugging this w/ @p00f in the background, and have finally figured out what's going on! :tada: 

- loginctl had linger enabled for user `chinmay`
- At boot, loginctl would immediately try to start `user@<UID of chinmay>.service` 
- This starts a `systemd-user` PAM stack, which ultimately tries to authenticate homed.
- One of two things happens:
  - Authentication fails outright. Home directory is not mounted.
  - Authentication fails, but homed launches the user in incomplete fallback mode for some reason. HOME=/ is explicitly set as the fallback home directory
- Either way, the home directory is not present and homed's failure to authenticate doesn't stop `user@<uid>.service` from starting
- The user manager starts. Somehow HOME=/ is set in its environment (or it's just outright unset, not sure which), and it has no access to the home directory. All services it spawns will have HOME= set incorrectly, and will be unable to access the home directory anyways. Which will break the services.
- (Later) the graphical login screen starts. User logs in
- IF homed was in an incomplete mode at this point, then it was just completed. This has the strange side effect of un-setting the fallback shell, which means the fallback shell never got to run in the other session and that session is left broken. I don't think this is actually an issue, since `user@<uid>` is just not supposed to be running while useFallback=true...
- A new user session is set up, desktop environment is started, etc. The user manager was already running from before
- User manager still has HOME= set up wrong (either set to /, or unset completely). The home directory is accessible but session services don't know about it
- Session services break because they can't find the home directory.

I think this boils down into a couple of independent issues, which I'll follow up with.

**Comment by AdrianVovk** [comment] 2024-08-27 18:36
First issue exposed here: logind lingering outright _cannot_ work with systemd-homed users. At least currently. Maybe eventually we'll have TPM based authentication methods for homed users, and will be able to use the TPM to unlock a home dir for lingering. But even then, that configuration will need to come from homed, not from logind. `loginctl enable-linger <some-homed-user>` can never work. Maybe we should just outright refuse to turn on linger for homed users via the command line, and ignore any homed users that might have previously been configured in /var/lib/systemd/linger.

logind should also log that it's activating a user w/ linger... I suspect there won't ever be enough lingering users on a system fro a long message about it to be too noisy. We spent a long time trying to figure out what, exactly, is trying to activate the `user@<uid>.service` at boot!

**Comment by AdrianVovk** [comment] 2024-08-27 18:39
Second issue exposed here: logind continued starting `user@<uid>.service` even though homed has failed to mount the home directory. Perhaps we should re-evaluate the recommended PAM configs (and the behavior of our PAM modules?) so that a failure from homed prevents the session manager unit (or any unit for that matter) from starting. This is not a distro config issue either - looks like Arch uses the upstream `systemd-user` PAM config.

**Comment by AdrianVovk** [comment] 2024-08-27 18:41
I'll close this in favor of the other two bugs

**Closed as completed by AdrianVovk** 2024-08-27 18:41 UTC
Labels: bug 🐛, homed

**Comment by NekkoDroid** [comment] 2024-08-27 19:50
> This is not a distro config issue either - looks like Arch uses the upstream systemd-user PAM config.

@AdrianVovk To my knowledge this isn't the case. It ships the upstream one in `/usr/lib/pam.d/`, but it provides its own in `/etc/pam.d/` https://gitlab.archlinux.org/archlinux/packaging/packages/systemd/-/blob/main/systemd-user.pam

**Comment by AdrianVovk** [comment] 2024-08-27 19:53
> It ships the upstream one in /usr/lib/pam.d/, but it provides its own in /etc/pam.d/

Distro PAM config was one of the first things I blamed. So when we were investigating the issue I had @p00f replace their /etc file with the upstream version (which later turned out to be identical to the file in /usr/lib/pam.d). The bug still occured. So despite the differences in the config file, that didn't cause the issue.

**Comment by MinaMatta98** [comment] 2024-10-02 13:16
Ahh, let me tell you the story of a fool who had this problem, and how he managed to fix it after several days of trying.

I didn't originally have a systemd-homed home, but I wanted to opt into encryption and decryption. Lo and behold, systemd-homed automated this with lukscrypt (I didn't want too much of a headache), so I created a systemd home.

Now, a year ago, I got an itch to play around with /etc/passwd and /etc/shadow. Don't ask why, because I don't remember. I deleted my user from both and restarted, but forgot about it.

The strange thing is that I would actually require two logins. The first login would still startx and lead to my WM Environment, but there would be clear corruption from an inability to access /home/$user.home. I would then log out and log in. Perfectly normal behavior would be observed at this point.

I have no idea why this was the case, but I suspect it's because I set a systemd-homed password which is _stored_ for later activation as per the systemd-homed notification.

### The solution:
Create an entry in /etc/passwd with the following form:

```
$username:x:$uid:$uid::$HOME:$terminal
```
where:
```
$username -> your username,
x -> just keep it in there,
$uid -> the output of  echo $UID in your terminal
$HOME -> your home directory location (generally /home/username)
$terminal -> the default is /bin/bash but this could be something else like /bin/zsh
```

Run the following in your terminal of choice:

```bash
sudo pwck
```

This will ask you to regenerate your /etc/shadow entry. Confirm with `yes`.

Now you are left with a systemd-home password that isn't represented in your `/etc/shadow`. So you have to do the following:

```bash
echo `username:password` | sudo chpasswd -c YESCRYPT
```

This will update your password in `/etc/shadow`

**Comment by 4lex11s** [comment] 2024-12-06 19:24
FYI
For  me, I think it's after activating the "lingering" for my user.

**konsole wouldn't open anymore.**

I was able to see what it said before it died by running `konsole --noclose` in startup menu:
In red : `Failed to upgrade session: Unknown object /org/freedesktop/login1/session/self`

I solved my problem by (disable linger is not sufficient):

 - loginctl disable-linger $user 
- from a user session (not possible from root, loop bug)
 - `homectl passwd $user`
    - and just `passwd` does'nt work

Before and after, my user is not in /etc/shadow, it's a full homed acount.

**Comment by AdrianVovk** [comment] 2024-12-12 19:25
I suspect that disabling linger on its own would solve the problem after a reboot.

But anyways, yes this bug is caused due to linger. Lingering breaks homed. This is tracked in https://github.com/systemd/systemd/issues/34151
