### ISSUE TITLE
Do not use struct timezone with settimeofday

### ISSUE THREAD

**Issue by fweimer** [systemd/systemd#13305] opened 2019-08-12 08:21 UTC
Linux is removing support for the system call `settimeofday` from new architectures. The `clock_settime` system call does not support the `struct timezone *` argument.  As a result, the glibc implementation of `settimeofday` will fail if a non-zero time zone offset is specified. For consistency, this change will likely be applied across all architectures (with a compatibility symbol to preserve the semantics for existing binaries).

systemd should not call `settimeofday` to set the time zone because the kernel is removing this feature.

An alternative would be convince the kernel developers to add back the `settimeofday` system call for new architectures.

**Comment by poettering** [comment] 2019-08-12 10:03
Hmm. So how is the "warp time" thing done without settimeofday? Its the one api to ensure the rtc offset can be applied. Is there any other? If this is removed without replacement then this would be a major api break and leave all windows dual boot folks in the cold.

**Comment by fweimer** [comment] 2019-08-12 10:43
This was asked before here, without receiving an answer:

* https://lore.kernel.org/lkml/CAK8P3a0OBBEwU044jbe-YK2CmCnpNpUSiCA9uRo-8EwtcUva6g@mail.gmail.com/T/

The [upstream submission](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=d33c577cccd0b3e5bb2425f85037f26714a59363) only mentions `stime` (which lacks the timezone argument), but not `settimeofday`.

The consensus so far is that this feature has been removed deliberately, but I don't know if this is really the case.

**Comment by poettering** [comment] 2019-08-12 11:18
@arndb, it appears you are pushing for the deprecation of settimeofday(), what's the story on this regarding the early-boot timewarp?

i.e. how are we supposed to implement this code:

https://github.com/systemd/systemd/blob/master/src/shared/clock-util.c#L99

It is invoked early on during boot to ensure the RTC offset that dual-booting Windows requires is passed to the kernel. Sure, it's ugly, and somewhat broken, but it's what users apparently want.

**Comment by arndb** [comment] 2019-08-12 15:03
I originally made the decision to only add clock_gettime64 and clock_settime64 but not gettimeofday_time64/settimeofday_time64 for the 64-bit time system calls, but did not expect that to cause problems. The issue has never been discussed with the kernel timekeeping maintainers so far.

When it came up in https://patchwork.ozlabs.org/patch/1121610/, I suggested we could add a new kernel interface to set the kernel time zone, but Paul Eggert said it would be better to leave it out because of general objections against the timezone interfaces.

The kernel generally only cares about the timezone in a few places:

1. the rtc time warp for windows compatibility on x86 machines
2. the timezone offset for file systems that require storing timestamps in local time (fat, udf, hpfs, hfs). These typically allow a 'time_offset' and/or 'timezone' mount option as an alternative.
3. some drivers that save timestamps as local time in hardware buffers, typically scsi adapters. One can argue that these are just wrong, and we should not be doing it that way, as other drivers do the same thing using UTC.

If all that's left is the need for boot time RTC time warp and we still don't want to add settimeofday_time64(), the most logical place for a new interface to be added would be an ioctl on /dev/rtc/, but that still leaves a problem for systemd built against a new glibc but running on an old kernel.

**Comment by poettering** [comment] 2019-08-12 15:20
i mean, from my side I'd be happy if we call a better API from systemd for the windows rtc compat thing. The old api with making the first call to settimeofday magic is just weird.

Note that systemd calls settimeofday with the first arg NULL for this purpose...

If glibc wants to retain compat on this it could just check if the first arg is NULL, and then redirect the second arg to some rtc ioctl (or sysfs file?). The code for that would probably not be totally ugly, but i guess that's for the glibc folks to decide.

anyway, from the systemd side we can call any API, we have no particular love for settimeofday(), just let us know which one shall replace settimeofday() with. whether kernel/glibc want to break compat on this is up to them...

**Comment by arndb** [comment] 2019-08-12 15:50
I don't think glibc can implement this since they would not know whether the settimeofday() call is the first one or not, so it would end up warping the timezone (i.e. setting the persistent_clock_is_local flag) instead of just setting it.

What I meant is that systemd could use a new kernel interface such as the /dev/rtc ioctl in its initialize_clock() when it is unable to set warp the timezone through settimeofday().

If we instead want to keep a way to set the timezone at runtime, we need the settimeofday_time64()/gettimeofday_time64() system calls.

**Comment by poettering** [comment] 2019-08-12 16:39
Anyway, I figure the glibc/kernel folks need to figure out what they want to do here. Until then, this issue is hardly actionable for us. I guess we are fine with anything. The old API is stupid, so pretty much anything is better. 

my suggestion: add an explicit sysctl to allow manipulation of the default rtc/fat/udf/… delta. This would be great so that people can even change it afterwards if they like. Changing this value should not have any direct effect on the system clock however. Then add an ioctl to /dev/rtc which takes no arguments, but makes CLOCK_REALTIME jump according to the value configured with the sysctl, turns off 11min mode, and then seals this all off. (Since this operation doesn't involve any RTC hw it might make sense to move this operation elsewhere though, not sure where though)

**Comment by zackw** [comment] 2019-08-13 01:10
I'm a glibc maintainer.  What would you think of a pair of new functions, named `get_hw_timezone` and `set_hw_timezone`, declared probably in `sys/timex.h` (which is already a dumping ground for rarely-used time-related extension APIs) that are dedicated for manipulating the "default rtc/fat/utf/... delta" ?  On current kernels these would call gettimeofday/settimeofday, but after the kernel people add some kind of dedicated API for this, we'd use that in preference.

In case you're curious, this comes up now because we're trying to nail down glibc support for 64-bit time_t on 32-bit architectures, and we were very surprised to find a genuine non-bug use of settimeofday with non-null timezone argument. We thought we were going to be safe making settimeofday forward to clock_settime.

**Comment by poettering** [comment] 2019-08-13 07:34
@zackw quite frankly, the "setting the rtc/fat/utf/… delta" thing is an operation that is required only by very few users (i.e. pretty much only pid1 once during early boot — or /usr/sbin/hwclock for the same purpose on non-systemd systems), and that is pretty borked (since time zones are not just fixed offsets, and winter/summer time is not modelled at all). If I were you I wouldn't bless this concept with a glibc API of its own. It's too specialist and too broken for that. It sounds like something an obscure sysctl might be good enough for, and that systemd can then deal with without any explicit glibc knobs.

hmm, another idea: so in glibc, why not just fallback to the classic settimeofday() syscall exactly in the case when settimeofday() is called with the first argument being NULL and the second being non-NULL? because in such an invocation you have no 64bit problem, and it's not that x86-64 could get rid of the syscall anyway, right?

i.e.:

```c
int settimeofday(const struct timeval *tv, const struct timezone *tz) {
        struct timespec ts;
        if (tz) {
#ifdef __NR_settimeofday
                if (!tv)
                        return syscall(__NR_settimeofday, NULL, tz);
#endif
                errno = ENOSYS;
                return -1;
        }
        return clock_gettime(CLOCK_REALTIME, &timeval_to_timespec(&ts, &tv));
}
```

if you get what I am saying. With such an implementation you have no 64bit problem, and you retain compatibility for everything systemd needs.

**Comment by fweimer** [comment] 2019-08-13 08:01
Such fallback is not possible for new architectures because they do not have a `settimeofday` system call at all.

**Comment by poettering** [comment] 2019-08-13 08:10
@fweimer well, sure, but maybe people should give up on the RTC offset anyway for them? i mean, it's a windows compat thing, and on new archs you probably won't need that.

And for the fat/hpfs/… time delta case I figure a good approach would be to add the suggested sysctl to change the offset anytime without the time warp thing

**Comment by arndb** [comment] 2019-08-13 09:32
I tried to summarize the state of the discussion and sent a follow-up mail to lkml, see https://lore.kernel.org/lkml/CAK8P3a0VxM1BkjY1D2FfHi6L-ho_NH3v3+gBu45EfpjLF5NU5w@mail.gmail.com/t/

**Comment by poettering** [comment] 2019-11-04 12:54
Any updates on this? @arndb? @fweimer?

**Comment by poettering** [comment] 2019-12-17 11:19
ping? @arndb @fweimer?

**Comment by karelzak** [comment] 2020-02-18 09:55
Do we really need to Glibc maintain extra API for just two programs (systemd and hwclock)? It sounds like pretty overkill.  IMHO it would be better to resolve this by /dev/rtc ioctl and keep Glibc out of this game. 

I guess backward compatibility is not a big issue as we can use some #ifdefs or direct system calls in our code (systemd and hwclock).

**Comment by poettering** [comment] 2021-02-10 10:59
I guess changing this kernel API was abandoned, right? I guess we can close this now?

**Comment by nullr0ute** [comment] 2021-02-10 11:06
No, it landed in 5.10 and I'm seeing issues on some devices:
Assertion 'clock_gettime(map_clock_id(clock_id), &ts) == 0' failed at src/basic/time-util.c:53, function

**Comment by poettering** [comment] 2021-02-10 11:12
@nullr0ute looks unrelated. that's not an invocation of settimeofday(), which this issue is about.

Please file a new issue about that, provide a backtrace, and explain how this is reproducible. Which arch, yadda, yadda.

**Comment by poettering** [comment] 2021-02-10 13:06
I understand that since glibc commit c3f9aef063cd9d5911e20d4f2b919ff2914c7965 it actually implements what I suggested above in https://github.com/systemd/systemd/issues/13305#issuecomment-520724016

I am happy to switch over systemd to using a newer API for setting that timezone offset of the kernel. But that requires that new kernel API to materialize first. I figure we don't have to keep this issue open.

Once  a new API for this materializes (maybe a sysctl, or a sysfs file, or an ioctl to rtc device, or something else), we can happily port things over, but until then there's nothing actionable for us here, hence let's close.

**Closed as completed by poettering** 2021-02-10 13:06 UTC
Labels: RFE 🎁, needs-discussion 🤔, pid1

**Comment by zackw** [comment] 2021-02-10 15:17
I guess we forgot to tell you when c3f9aef063cd9d5911e20d4f2b919ff2914c7965 landed in glibc.  My bad -- I wrote the first iteration of that patch, in response to your suggestion, and then someone else took it over and I stopped paying attention.

As long as systemd is prepared for `settimeofday(0, &tz)` to fail with ENOSYS on architectures where there isn't a settimeofday system call, yeah, I think there's no action needed from your end unless/until the new API materializes.
