### ISSUE TITLE
sysusers depends on systemd

### ISSUE THREAD

**Issue by LorbusChris** [systemd/systemd#13653] opened 2019-09-25 19:51 UTC
**Is your feature request related to a problem? Please describe.**
In Fedora containers, we would like to use sysusers as a standalone tool, without having it pull in the entirety of systemd. 

Quoting Troy Dawson from the fedora-devel Mailing List thread[1]
>One of the comments in the ticket was to try pulling out
systemd-sysusers into it's own sub-package.
systemd-sysusers requires libsystemd-shared
Pulling libsystemd-shared into it's own sub-package shows that it
requires cryptsetup-libs which sets up a circular dependency back to
systemd.
After many attempts, just using rpm packaging techniques, I have been
unsuccessful in breaking the circular dependency.
The only way I can see to do it is either remove some functionality,
or do some type of re-writting of code in systemd and/or one of the
packages in the circular dependency.

See [2], [3] and [4] for more context

**Describe the solution you'd like**
systemd-sysusers is packageable with minimal or no dependencies.

[1] https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/6YX6CEFBPU3XVZZEHTN6CBH2F7JDF35N/
[2] https://pagure.io/minimization/issue/13
[3] https://pagure.io/ContainerSIG/container-sig/issue/38
[4] https://pagure.io/packaging-committee/issue/442

**Comment by keszybz** [comment] 2019-10-03 12:04
I see two possibilities: 1. The container is immutable, and new versions of the container are created offline. In this case, the container should only have stuff that is needed for operation, so systemd-sysusers and similar tools should not be installed at all. 2. The container is mutable, and supports updates, logging into the container, etc. In this case, systemd should be present, and at least systemd-libs would very likely be pulled in by other components. In case 1., sysusers is not installed, in case 2. sysusers is installed but doesn't matter.

The use case where dependencies of sysusers would matter would be a minimalistic container that nevertheless has the stack required for installation of packages, in particular dnf and rpm in case of Fedora containers. Is this setup useful at all?

**Comment by LorbusChris** [comment] 2019-10-08 17:17
I am aiming for the 1. case, immutable containers. The problem, though, is that some Fedora RPMs have a `Requires` on systemd in order to create the users with sysusers. Ideally, one could use `dnf install --installroot ...` to create a root dir for a container. In the case of an RPM that uses sysusers to create users, though, systemd is also installed into that root dir, because the RPM has declared it as a dep.

In rpm-ostree, which creates immutable dir and file structures, sysusers and tmpfiles are _intercepted_ and created at image compose time. (Although this is probably not how it really works rn, calling on @cgwalters to correct me here :)

I am also wondering whether we could use rpm-ostree to compose fs structures for containers? (no dnf would be needed then)

**Comment by poettering** [comment] 2019-11-03 18:35
I am not entirely sure this is the ideal place to discuss this, after all it has nothing to do with upstream, does it?

Ideally we had "systemd-sysusers --root=" but we can't really offer that easily, since glibc's user APIs are not built like that: they do not allow operation relative to some root directory, and it's hard to image how they could be made supporting that, given how NSS (which requires dlopen() which requires living inside the disk image) works.

I have the suspicion this is something to fix in your image builder: build the image once with a larger set of tools, and once with a more reduced one. and just copy in the files the first itration generated. I mean, it's not that you need tools like "ldconfig" and so on in your container either. systemd-sysusers is not that special really I would argue: there are a number of deps only needed for RPM scriplet execution but not during runtime.

Anyway, a quick fix would be to split systemd-sysusers into its own package (maybe together with systemd-tmpfiles, which is a very similar case).

These two approaches have nothing to do with systemd upstream though, and are probably better tracked in RH bugzilla (or whatever issue tracker you use for your image builder). So maybe let's close this here?

**Comment by keszybz** [comment] 2019-11-04 07:55
> Ideally we had "systemd-sysusers --root="

We have that already ;)

> Anyway, a quick fix would be to split systemd-sysusers into its own package

Part of the problem is that systemd-sysusers needs libsystemd-shared.so, which is around half of the systemd package, and pulls in most of the dependencies already. This means that while we *can* split out a subpackage with systemd-sysusers and systemd-tmpfiles, the saving would not be very big. I think some more radical solution that allows those programs to be completely uninstalled from the system is the only thing worth targeting.

I agree that we shouldn't be discussing this here, since it's not an upstream issue. Let's close.

**Closed as completed by keszybz** 2019-11-04 07:55 UTC
Labels: sysusers

**Comment by mbiebl** [comment] 2019-11-04 11:29
We could allow those tools to be linked statically against libsystemd-shared (same as we do for systemctl).
We chose to link systemctl to be linked statically in Debian mainly for robustness reasons (to make it less likely to fail during a dist upgrade when system libraries are upgraded).

**Comment by mbiebl** [comment] 2019-11-04 11:33
Btw, there are people in Debian who would like to use systemd-tmpfiles/systemd-sysusers irregardless if systemd is the active init or not (so it's similar to the docker use case).
Splitting out those binaries is currently not really feasible because of the libsystemd-shared dependency.

**Comment by poettering** [comment] 2019-11-04 14:28
it appears to me the best would be to make libsystemd-shared.so less dependency-hungry somehow. I mean, statically compiling it into three binaries should be worse than having it once dynamically...

**Comment by mbiebl** [comment] 2019-11-04 14:51
I'm not sure if that would really help. Imagine this use case:
Say you keep systemd-tmpfiles/systemd-sysusers linked against libsystemd-shared and you want to make those tools available in a non-systemd context, so you split those binaries (along with libsystemd-shared) into a separate package, let's call it systemd-core.
Now you run into the interesting problem, that the real systemd package will have to depend on the new systemd-core package and on package upgrades you will have a time window where the new systemd-core package (with the new libsystemd-shared with potentially bumped soname) is unpacked but the new systemd package is not yet. If you now call any of the systemd binaries from the systemd package, they will segfault. If we want to provide the abilitiy to split off systemd-sysusers/systemd-tmpfiles, they need to be independet from the rest.

**Comment by poettering** [comment] 2019-11-04 15:14
hmm? why would you remove the old libsystemd-shared.so before the update is complete? install the new versions of everything and then remove the old stuff. That's how most package managers work, no?

**Comment by mbiebl** [comment] 2019-11-04 15:15
if systemd and systemd-core are split, you can't unpack them simultaneously.

**Comment by poettering** [comment] 2019-11-04 15:17
hmm? you unpack the new systemd-core, then unpack the new systemd, then remove the files no longer listed in systemd-core and systemd. And all is good.

We bump the name of libsystemd-shared on each release, which should make this seamless.

**Comment by mbiebl** [comment] 2019-11-04 15:18
That's not how dpkg works. If it was done this way, this would potentially double the size you need to upgrade a system.

**Comment by mbiebl** [comment] 2019-11-04 15:19
I might be mistaken, but I haven't seen rpm doing this either, i.e. keeping copies of the old files around until the "complete" upgrade is done.

**Comment by poettering** [comment] 2019-11-04 15:28
they have a cleanup stage where they remove old files. and it's called after all new stuff is unpacked.

**Comment by arvidjaar** [comment] 2019-11-05 09:37
> you will have a time window where the new systemd-core package (with the new libsystemd-shared with potentially bumped soname) is unpacked but the new systemd package is not yet

It is not really different from the case when library and binary are part of the same package. It's not possible to atomically unpack and switch to new versions of all files in a package; as long as you perform update in live system you always have time window with some files from old package and some files from new package. To avoid it you need to apply updates to inactive root and reboot into it.

With proper dependencies both packages must be updated together which is practically the same as  having single package.

**Comment by mbiebl** [comment] 2019-11-05 10:32
> With proper dependencies both packages must be updated together which is practically the same as having single package.

Well, no, it's not the same. Anyway, my point is that libsystemd-shared with a just few dependencies less is not a solution that would work for Debian.

**Comment by LorbusChris** [comment] 2020-01-28 01:38
What is the status on this? It does not look like this was ever resolved...would the right place to fix this be in downstream packaging? e.g the Fedora RPM? Or should this be discussed further here?
