### ISSUE TITLE
link Name is not applied if created after the initial type-based naming is applied

### ISSUE THREAD

**Issue by joejulian** [systemd/systemd#2846] opened 2016-03-15 21:44 UTC
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229
### Used distribution

> Arch
### In case of bug report: Expected behaviour you didn't see

> Network device is renamed
### In case of bug report: Unexpected behaviour you saw

> Network device retained predictable name
### In case of bug report: Steps to reproduce the problem

> - Boot a machine
> - Create a link file
> 
> /etc/systemd/network/10-mgmt.link
> 
> ```
> [Match]
> MACAddress=52:54:00:6c:cf:17
> 
> [Link]
> Name=mgmt
> ```
> 
> udevadm trigger -c add -s net
> (or even change should do it, imho, since that file didn't exist before)

**Comment by poettering** [comment] 2016-04-15 09:20
Looks like a bug, @teg?

**Comment by flokli** [comment] 2017-07-04 13:11
Seems like I'm also affected by this. It looks like no renaming is tried, and journalctl doesn't show anything.

60-rename-1B.link:
```
[Match]
Path=pci-0000:0a:00.1

[Link]
Name=1A
```

udevadm test /sys/class/net/enp10s0f1:
```
calling: test
version 232
=== trie on-disk ===
tool version:          232
file size:         8441068 bytes
header size             80 bytes
strings            1846908 bytes
nodes              6594080 bytes
Load module index
Found container virtualization none
timestamp of '/etc/systemd/network' changed
Parsed configuration file /lib/systemd/network/99-default.link
Parsed configuration file /etc/systemd/network/60-rename-1B.link
Parsed configuration file /etc/systemd/network/60-rename-1A.link
Created link configuration context.
timestamp of '/etc/udev/rules.d' changed
timestamp of '/lib/udev/rules.d' changed
Reading rules file: /lib/udev/rules.d/50-firmware.rules
Reading rules file: /lib/udev/rules.d/50-udev-default.rules
Reading rules file: /lib/udev/rules.d/55-dm.rules
Reading rules file: /lib/udev/rules.d/60-block.rules
Reading rules file: /lib/udev/rules.d/60-bridge-network-interface.rules
Reading rules file: /lib/udev/rules.d/60-cdrom_id.rules
Reading rules file: /lib/udev/rules.d/60-drm.rules
Reading rules file: /lib/udev/rules.d/60-evdev.rules
Reading rules file: /lib/udev/rules.d/60-persistent-alsa.rules
Reading rules file: /lib/udev/rules.d/60-persistent-input.rules
Reading rules file: /lib/udev/rules.d/60-persistent-storage-dm.rules
Reading rules file: /lib/udev/rules.d/60-persistent-storage-tape.rules
Reading rules file: /lib/udev/rules.d/60-persistent-storage.rules
Reading rules file: /lib/udev/rules.d/60-persistent-v4l.rules
Reading rules file: /lib/udev/rules.d/60-serial.rules
Reading rules file: /lib/udev/rules.d/63-md-raid-arrays.rules
Reading rules file: /lib/udev/rules.d/64-btrfs.rules
Reading rules file: /lib/udev/rules.d/64-md-raid-assembly.rules
Reading rules file: /lib/udev/rules.d/70-debian-uaccess.rules
Reading rules file: /lib/udev/rules.d/70-mouse.rules
Reading rules file: /lib/udev/rules.d/70-power-switch.rules
Reading rules file: /lib/udev/rules.d/70-touchpad.rules
Reading rules file: /lib/udev/rules.d/70-uaccess.rules
Reading rules file: /lib/udev/rules.d/71-seat.rules
Reading rules file: /lib/udev/rules.d/73-seat-late.rules
Reading rules file: /lib/udev/rules.d/73-special-net-names.rules
Reading rules file: /lib/udev/rules.d/73-usb-net-by-mac.rules
Reading rules file: /lib/udev/rules.d/75-net-description.rules
Reading rules file: /lib/udev/rules.d/75-probe_mtd.rules
Reading rules file: /lib/udev/rules.d/78-sound-card.rules
Reading rules file: /lib/udev/rules.d/80-debian-compat.rules
Reading rules file: /lib/udev/rules.d/80-drivers.rules
Reading rules file: /lib/udev/rules.d/80-ifupdown.rules
Reading rules file: /lib/udev/rules.d/80-net-setup-link.rules
Reading rules file: /lib/udev/rules.d/85-hwclock.rules
Reading rules file: /lib/udev/rules.d/90-console-setup.rules
Reading rules file: /lib/udev/rules.d/99-systemd.rules
rules contain 24576 bytes tokens (2048 * 12 bytes), 12221 bytes strings
1729 strings (21632 bytes), 1117 de-duplicated (10024 bytes), 613 trie nodes used
RUN 'bridge-network-interface' /lib/udev/rules.d/60-bridge-network-interface.rules:1
IMPORT builtin 'net_id' /lib/udev/rules.d/75-net-description.rules:6
IMPORT builtin 'hwdb' /lib/udev/rules.d/75-net-description.rules:12
RUN 'ifupdown-hotplug' /lib/udev/rules.d/80-ifupdown.rules:5
IMPORT builtin 'path_id' /lib/udev/rules.d/80-net-setup-link.rules:5
IMPORT builtin 'net_setup_link' /lib/udev/rules.d/80-net-setup-link.rules:9
Config file /etc/systemd/network/60-rename-1B.link applies to device enp10s0f1
RUN '/lib/systemd/systemd-sysctl --prefix=/net/ipv4/conf/$name --prefix=/net/ipv4/neigh/$name --prefix=/net/ipv6/conf/$name --prefix=/net/ipv6/neigh/$name' /lib/udev/rules.d/99-systemd.rules:56
created db file '/run/udev/data/n5' for '/devices/pci0000:00/0000:00:04.0/0000:0a:00.1/net/enp10s0f1'
Unload module index
Unloaded link configuration context.
This program is for debugging only, it does not run any programspecified by a RUN key. It may show incorrect results, because
some values may be different, or not available at a simulation run.

ACTION=add
DEVPATH=/devices/pci0000:00/0000:00:04.0/0000:0a:00.1/net/enp10s0f1
ID_BUS=pci
ID_MODEL_FROM_DATABASE=Ethernet Controller X710 for 10GbE SFP+ (Ethernet Converged Network Adapter X710)
ID_MODEL_ID=0x1572
ID_NET_DRIVER=i40e
ID_NET_LINK_FILE=/etc/systemd/network/60-rename-1B.link
ID_NET_NAME_MAC=enx3cfdfeaa429d
ID_NET_NAME_PATH=enp10s0f1
ID_OUI_FROM_DATABASE=Intel Corporate
ID_PATH=pci-0000:0a:00.1
ID_PATH_TAG=pci-0000_0a_00_1
ID_PCI_CLASS_FROM_DATABASE=Network controller
ID_PCI_SUBCLASS_FROM_DATABASE=Ethernet controller
ID_VENDOR_FROM_DATABASE=Intel Corporation
ID_VENDOR_ID=0x8086
IFINDEX=5
INTERFACE=enp10s0f1
SUBSYSTEM=net
SYSTEMD_ALIAS=/sys/subsystem/net/devices/enp10s0f1
TAGS=:systemd:
USEC_INITIALIZED=6084111
run: 'bridge-network-interface'
run: 'ifupdown-hotplug'
run: '/lib/systemd/systemd-sysctl --prefix=/net/ipv4/conf/enp10s0f1 --prefix=/net/ipv4/neigh/enp10s0f1 --prefix=/net/ipv6/conf/enp10s0f1 --prefix=/net/ipv6/neigh/enp10s0f1'
```

udevadm test-builtin net_setup_link /sys/class/net/enp10s0f1:
```
calling: test-builtin
=== trie on-disk ===
tool version:          232
file size:         8441068 bytes
header size             80 bytes
strings            1846908 bytes
nodes              6594080 bytes
Load module index
Found container virtualization none
timestamp of '/etc/systemd/network' changed
Parsed configuration file /lib/systemd/network/99-default.link
Parsed configuration file /etc/systemd/network/60-rename-1B.link
Parsed configuration file /etc/systemd/network/60-rename-1A.link
Created link configuration context.
ID_NET_DRIVER=i40e
Config file /etc/systemd/network/60-rename-1B.link applies to device enp10s0f1
ID_NET_LINK_FILE=/etc/systemd/network/60-rename-1B.link
Unload module index
Unloaded link configuration context.
```

**Comment by yuwata** [comment] 2019-01-16 22:07
From systemd.link(5)
>  The interface name to use in case all the policies specified in NamePolicy= fail, or in case NamePolicy= is missing or disabled.

The .link file provided in the above comments does not contain `NamePolicy=`. So, this is caused by the misconfiguration.

Let's close this. Even if `NamePolicy=` does not help, please reopen this.

**Closed as completed by yuwata** 2019-01-16 22:07 UTC
Labels: udev, not-a-bug
