### ISSUE TITLE
prefix '-' does not work in override.conf files

### ISSUE THREAD

**Issue by tiiiecherle** [systemd/systemd#9588] opened 2018-07-15 15:15 UTC
**systemd version the issue has been seen with**
239.0-2

**Used distribution**
archlinux

**Expected behaviour you didn't see**
prefix '-' in override.conf should have the same effect than in "regular" service file

**Unexpected behaviour you saw**
prefix '-' in override.conf was ignored

**Steps to reproduce the problem**
```
systemctl edit ipset.service
# creates /etc/systemd/system/ipset.service.d/override.conf
[Service]
ExecStop=
ExecStop=-/usr/bin/ipset destroy

systemctl start iptables
# starting iptables makes ipset exit unsecessfull without the modification
systemctl daemon-reload
systemctl restart ipset
sleep 5
systemctl status ipset.service --no-pager
# service restarts with failure, the "-" before /usr/bin/ipset is ignored
```
as a workaround this works (putting "" around the command)
```
systemctl edit ipset.service
# creates /etc/systemd/system/ipset.service.d/override.conf
[Service]
ExecStop=
ExecStop="-/usr/bin/ipset destroy"

systemctl start iptables
# starting iptables makes ipset exit unsecessfull without the modification
systemctl daemon-reload
systemctl restart ipset
sleep 5
systemctl status ipset.service --no-pager
# service restarts sucessfully
```
I do not know if this is the expected behavior, but I wouldn`t have expected that.

Thanks for looking into it and for all the hard work put into this project.

**Comment by poettering** [comment] 2018-07-16 09:56
We use the same parser fro drop-ins as for the main unit file... there is no real difference...

What do you mean by "service restarts with failure, the "-" before /usr/bin/ipset is ignored" and with "service restarts sucessfully"? What do the logs say precisely?

**Comment by poettering** [comment] 2018-07-16 10:38
again, what do the logs say precisely about this?

**Comment by poettering** [comment] 2018-07-16 12:02
> Which log (exact command) would you like to have?
just the output of "journalctl" called shortly after the failure, showing the logs created around the time you reproduce the issue

**Comment by tiiiecherle** [comment] 2018-07-16 12:23
ok, I set /etc/systemd/system/ipset.service.d/override.conf to
```
[Service]
ExecStop=
ExecStop=-/usr/bin/ipset destroy
```
and ran
```
systemctl daemon-reload
systemctl restart ipset
```
the journalctl log is:
```
-- Logs begin at Mon 2018-02-05 19:56:04 CET, end at Mon 2018-07-16 14:14:36 CEST. --
Jul 16 14:14:34 archvbox systemd[1]: Reloading.
Jul 16 14:14:35 archvbox systemd[1]: Stopping Fail2Ban Service...
Jul 16 14:14:35 archvbox fail2ban-client[9999]: Shutdown successful
Jul 16 14:14:35 archvbox systemd[1]: Stopped Fail2Ban Service.
Jul 16 14:14:35 archvbox systemd[1]: Stopping Loading IP Sets...
Jul 16 14:14:35 archvbox ipset[10035]: ipset v6.38: Set cannot be destroyed: it is in use by a kernel component
Jul 16 14:14:35 archvbox systemd[1]: Stopped Loading IP Sets.
Jul 16 14:14:35 archvbox systemd[1]: Starting Loading IP Sets...
Jul 16 14:14:35 archvbox systemd[1]: Started Loading IP Sets.
Jul 16 14:14:35 archvbox systemd[1]: Starting Fail2Ban Service...
Jul 16 14:14:35 archvbox systemd[1]: Started Fail2Ban Service.
Jul 16 14:14:36 archvbox fail2ban-server[10038]: Server ready
```

and the output of 
`systemctl status ipset.service --no-pager `
is
```
● ipset.service - Loading IP Sets
   Loaded: loaded (/etc/systemd/system/ipset.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/ipset.service.d
           └─override.conf
   Active: active (exited) since Mon 2018-07-16 14:14:35 CEST; 2min 44s ago
  Process: 10035 ExecStop=/usr/bin/ipset destroy (code=exited, status=1/FAILURE)
  Process: 10036 ExecStart=/usr/bin/ipset -f /etc/ipset.conf restore (code=exited, status=0/SUCCESS)
 Main PID: 10036 (code=exited, status=0/SUCCESS)

Jul 16 14:14:35 archvbox systemd[1]: Starting Loading IP Sets...
Jul 16 14:14:35 archvbox systemd[1]: Started Loading IP Sets.
```
ExecStop is supposed to exit with status SUCCESS in this config.

**Comment by poettering** [comment] 2018-07-16 12:35
Ah, I see where the confusion is.

So, systemd won't lie about exit codes, and will always remember them exactly how they happened. The "-" hence won't make the exit code of the ExecStop= to be flushed out entirely. All it does is that the propagated *effect* of a non-zero exit code is suppressed. Or in other words: the fact that the command failed is recorded for the command itself, but it won't affect the unit as a whole.

And I think this makes a ton of sense.

I will update the docs to clarify this a bit.

**Comment by tiiiecherle** [comment] 2018-07-16 13:04
Just to avoid any confusion. I get what you are saying, but the issue seems to be somewhere else.

If I do
`systemctl revert ipset`
and edit 
`/usr/lib/systemd/system/ipset.service `
directly by adding the "-" to the line and run 
```
systemctl daemon-reload
systemctl restart ipset
```
then
`systemctl status ipset.service --no-pager`
shows (as expected)
```
● ipset.service - Loading IP Sets
   Loaded: loaded (/usr/lib/systemd/system/ipset.service; disabled; vendor preset: disabled)
   Active: active (exited) since Mon 2018-07-16 15:00:58 CEST; 1min 36s ago
 Main PID: 4897 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 4708)
   Memory: 0B
   CGroup: /system.slice/ipset.service

Jul 16 15:00:58 archvbox systemd[1]: Starting Loading IP Sets...
Jul 16 15:00:58 archvbox systemd[1]: Started Loading IP Sets.
```

I expect override.conf to achieve the same result.

And it does if I use this in override.conf
`ExecStop="-/usr/bin/ipset destroy"`

**Comment by poettering** [comment] 2018-10-29 20:13
> And it does if I use this in override.conf
> `ExecStop="-/usr/bin/ipset destroy"`
> and this is the output.

Oh, this is not actually overriding anything, but extending things.

There may be multiple ExecStop= lines defined for a unit, and hence just declaring what you do means adding one more. If you want to replace the commands currently defined, assign ExecStop= the empty string first, and then add the new item.

```
…
ExecStop=
ExecStop=-/usr/bin/ipset destroy
…
```

**Comment by poettering** [comment] 2018-10-29 20:14
Since 6a1d4d9fa6b9df1069b15f00447b3a8f9b9a3266 has been merged, let's close this.

**Closed as completed by poettering** 2018-10-29 20:14 UTC
Labels: documentation, pid1
