### ISSUE TITLE
journalctl assection failed sd_id128_is_null

### ISSUE THREAD

**Issue by Kamilcuk** [systemd/systemd#29172] opened 2023-09-12 16:51 UTC
### systemd version the issue has been seen with

254

### Used distribution

Archlinux

### Linux kernel version used

Linux leonidas 6.5.2-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 06 Sep 2023 21:00:40 +0000 x86_64 GNU/Linux

### CPU architectures issue was seen on

x86_64

### Component

journalctl

### Expected behaviour you didn't see

Tell me "boot id does not exists" or similar.

### Unexpected behaviour you saw

```
$ sudo journalctl -b -178
Assertion '!sd_id128_is_null(id)' failed at src/shared/logs-show.c:1742, function add_match_boot_id(). Aborting.
Aborted
```

### Steps to reproduce the problem

run `journalctl` with `-b` with big enough negative number.

**Comment by medhefgo** [comment] 2023-09-12 18:57
Duplicate of #29167

**Closed as completed by medhefgo** 2023-09-12 18:57 UTC
Labels: bug 🐛, journal
