### ISSUE TITLE
run0 died in the middle of running a command (caused by systemctl daemon-reexec)

### ISSUE THREAD

**Issue by hiredman** [systemd/systemd#32906] opened 2024-05-17 20:26 UTC
### systemd version the issue has been seen with

256~rc1^20240509git1781de1

### Used distribution

Fedora Rawhide

### Linux kernel version used

6.9.0-0.rc3.20240411gite8c39d0f57f3.33.fc41.x86_64

### CPU architectures issue was seen on

x86_64

### Component

other

### Unexpected behaviour you saw

I was ran ` run0 dnf update --best --allowerasing  -x keybase\* -x emacs\*` to update packages and the final bit is 
```
>>> Running post-uninstall scriptlet: systemd-udev-0:256~rc1^20240509git1781de1-2.fc41.x86_64
>>> Stop post-uninstall scriptlet: systemd-udev-0:256~rc1^20240509git1781de1-2.fc41.x86_64
>>> Running trigger-uninstall scriptlet: systemd-0:256~rc1^20240509git1781de1-2.fc41.x86_64
>>> Stop trigger-uninstall scriptlet: systemd-0:256~rc1^20240509git1781de1-2.fc41.x86_64
>>> Running trigger-uninstall scriptlet: systemd-0:256~rc1^20240509git1781de1-2.fc41.x86_64Failed to query unit state: Remote peer disconnected
```

everything up to the beginning of "Failed" is on a red background. maybe a weird edge case is using run0 when updating systemd itself? dunno

it is not clear to me what happend. Running dnf again I just get a "Nothing to do.", maybe it completed, or it was killed and things it completed and didn't? dunno.

**Comment by YHNdnzj** [comment] 2024-05-17 21:01
Should be a duplicate of https://github.com/systemd/systemd/issues/27204.

**Closed as completed** 2024-10-25 17:50 UTC
Labels: bug 🐛, run, duplicate
