### ISSUE TITLE
Socket activation: service start is delayed and assertion error on shutdown

### ISSUE THREAD

**Issue by mphilipps** [systemd/systemd#7175] opened 2017-10-24 12:52 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

> Systemd 232 (debian stretch)

### Used distribution

> Debian Jessie (4.6 kernel) running a  Debian Stretch nspawn container that is starting another Debian stretch container.

### In case of bug report: Expected behaviour you didn't see

> I expect that the .service associated with a .socket file is started immediately. I Also expect systemd-nspawn to exit without assertion error.

### In case of bug report: Unexpected behaviour you saw
>  I have a constantly running Debian stretch container that is supposed to start another one through socket activation. I am using the following unit files for that:
https://gist.github.com/mphilipps/3f818af51826d818d56d4e411fe49149

About 90% of the time 15 seconds pass between me starting the ssh connection and the ExecStartPre logging the the time and the actual boot of the container starting. If I shutdown the container afterwards I always get the following assertion error:

Assertion 'fd >= 0' failed at ../src/basic/fd-util.c:38, function close_nointr(). Aborting.

**Comment by poettering** [comment] 2017-10-24 13:31
Hmm, any chance you can try to reproduce this on current systemd? (ie. 235 or 234) THere's a very good chance bugs in older versions are already fixed in current versions. Moreover, any chance you can get us the backtrace for the abort you are seeing? (normally, coredumpctl should have collected it)

Also, please provide logs when this happens.

**Comment by mbiebl** [comment] 2017-10-24 18:52
@mphilipps there is a backport of v234 available for stretch fwiw

**Comment by mphilipps** [comment] 2017-10-25 08:08
@mbiebl thank you, I have now installed systemd v234.
Unfortunately it doesn't appear to have helped. The first test was fast, but next one already had the 15 second delay again. However the assertion error on shutdown appears to be gone.  

It appears the two are not as related as I thought they were. My assumption was that it might be the fd for the socket activation that is causing the issue.

@poettering Is there anyway I can coax systemd into telling me more about what it is doing in the 15 seconds between triggering the socket activation and starting the service?

There are two other oddities I have discovered while trying to figure out this issue:
- The output of 'systemd-analyze plot' from within a container is several gigabyte in size, but not obviously malformed/corrupted.
- Sometimes on shutdown when nspawn removes the interface my ssh connection to the host container would freeze. Although I haven't seen that with 234 yet.

**Comment by poettering** [comment] 2017-10-27 18:30
> @poettering Is there anyway I can coax systemd into telling me more about what it is doing in the 15 seconds between triggering the socket activation and starting the service?

Yes, there's debug logging. Turn it on before with "systemd-analyze set-log-level debug"

**Comment by poettering** [comment] 2018-05-24 11:46
OK, let's close this for now, due to lack of response. We reall yneed those logs otherwise there's little we can do

**Closed as completed by poettering** 2018-05-24 11:46 UTC
Labels: needs-reporter-feedback ❓
