### ISSUE TITLE
Allow for alternative/multiple command lines in sd-boot

### ISSUE THREAD

**Issue by evelikov** [systemd/systemd#29445] opened 2023-10-04 13:59 UTC
### Component

systemd-boot

### Is your feature request related to a problem? Please describe

Currently systemd-boot allows for a single command line to be passed to the kernel at boot.

As mentioned in the end of @smoser's talk ` Kernel command line and UKI; systemd-stub and the ‘stubby’ alternative`,  there was the idea of having alternative/multiple kernel command lines. In turn sd-boot would potentially generate an entry for each one. With some ideas/input provided by @lucab and @poettering.

I couldn't find an existing issue about this so here it goes. Feel free to close this if I missed it ;-)

### Describe the solution you'd like

Having sd-boot generate extra entries or pick alternative command line based on some heuristics would be appreciated. Obviously there should be a way to deterministically selecting any of these alternatives - be that `LoaderEntryDefault` or otherwise.

### Describe alternatives you've considered

:shru

### The systemd version you checked that didn't have the feature you are asking for

254

**Comment by poettering** [comment] 2023-10-30 22:15
So i think it might make sense to allow embedding a subset of the type 1 boot loader spec syntax also in some PE section.

i.e. if you want a UKI to synthesize additional menu entries you'd add a PE section maybe called .bootmenu, with contents like the following:

```
title Boot into Recovery Mode
options recovery=1\0
title Boot in Storage Target Mode
options ip=ll rd.systemd.unit=storage-target-mode.target
```

You get the idea. We'd use a NUL byte as separator.

Of course any of the type1 stanzas that reference external resources would not be supported, i.e. initrd, linux, devicetree, efi. But we'd support title, options, sort-key, version at least.

**Comment by poettering** [comment] 2023-10-30 22:16
maybe using ^D (i.e. ASCII code 4) as separator, as on UNIX that indicates end of file, which this pretty much is.

**Comment by poettering** [comment] 2023-11-06 09:03
Duplicate of #24539

**Closed as completed by poettering** 2023-11-06 09:03 UTC
Labels: RFE 🎁, sd-boot/sd-stub/bootctl, duplicate
