### ISSUE TITLE
systemd-journald writes zero sizes for persistent journal sizes into journal

### ISSUE THREAD

**Issue by hese10** [systemd/systemd#5342] opened 2017-02-14 13:53 UTC
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

232

### Used distribution

fedora 25

### In case of bug report: Expected behaviour you didn't see

when checking journal logs with journalctl, valid disk file sizes shuold have been written by systemd-journal:
Feb 13 15:59:57 XYZ-0 systemd-journald[113]: System journal (/var/log/journal/102655a5f9c845e1b370c30f23b407ef) is 56MB, max 180MB, 124MB free.

### In case of bug report: Unexpected behaviour you saw

when checking journal logs with journalctl, it is seen that systemd-journal writes zero sizes for journal log sizes:
Feb 13 15:59:57 XYZ-0 systemd-journald[113]: System journal (/var/log/journal/102655a5f9c845e1b370c30f23b407ef) is 0B, max 0B, 0B free.

### In case of bug report: Steps to reproduce the problem
persistent storage for journal set in /etc/systemd/journald.conf:
Storage=persistent

Just boot system with systemd 232 installed.

here is journalctl binary files also:
[journal_bin_files.zip](https://github.com/systemd/systemd/files/774211/journal_bin_files.zip)
However, there seems to be showing that systemd 231 version in startup:
Feb 14 15:27:34 localhost.localdomain systemd[1]: systemd 231 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
, but newer systemd 232 is really installed:
systemd 232
-PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS -ACL +XZ +LZ4 -SECCOMP +BLKID -ELFUTILS -KMOD -IDN

Anyway this bug also occurs in other installations that are pure systemd 232 installation, but I cannot share those journal logs.

**Comment by evverx** [comment] 2017-02-14 15:38
Duplicate of https://github.com/systemd/systemd/issues/4790

**Closed as completed by evverx** 2017-02-14 15:38 UTC
Labels: journal, duplicate
