### ISSUE TITLE
man: sd_bus_send(3) does not exist

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#6655] opened 2017-08-22 08:22 UTC
The man page sd_bus_send(3) is referenced by sd_bus_default(3) and sd-bus(3), but it does not exist.

**Comment by yuwata** [comment] 2017-08-22 08:31
Neither, sd_bus_start(3) does not exist.

**Comment by poettering** [comment] 2017-08-30 09:08
Duplicate of #235 

Closing.

**Closed as completed by poettering** 2017-08-30 09:08 UTC
Labels: RFE 🎁, documentation, duplicate
