### ISSUE TITLE
systemd unit isolation different after libseccomp upgrade (2.5.0 -> 2.5.1)

### ISSUE THREAD

**Issue by andir** [systemd/systemd#18089] opened 2020-12-27 02:03 UTC
**systemd version the issue has been seen with**
 > 246

**Used distribution**
 > NixOS

**Linux kernel version used** (`uname -a`)
 > 5.9.11

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > Successful service startup.

**Unexpected behaviour you saw**
 > Service failed to start.

**Steps to reproduce the problem**
On a host with libseccomp 2.5.0 & babeld (or likely other services) create a service with the following configuration file:

```
[Unit]
After=network.target
Description=Babel routing daemon

[Service]
CapabilityBoundingSet=CAP_NET_ADMIN
ExecStart=/somewhere/bin/babeld -c /somewhere/babeld.conf -I /run/babeld/babeld.pid -S /var/lib/babeld/state
IPAddressAllow=fe80::/64
IPAddressAllow=ff00::/8
IPAddressAllow=::1/128
IPAddressAllow=127.0.0.0/8
IPAddressDeny=any
LockPersonality=true
MemoryDenyWriteExecute=true
NoNewPrivileges=true
PrivateDevices=true
PrivateMounts=true
PrivateTmp=true
PrivateUsers=false
ProtectClock=true
ProtectControlGroups=true
ProtectHome=true
ProtectHostname=true
ProtectKernelLogs=true
ProtectKernelModules=true
ProtectKernelTunables=false
ProtectSystem=strict
RemoveIPC=true
RestrictAddressFamilies=AF_NETLINK
RestrictAddressFamilies=AF_INET6
RestrictNamespaces=true
RestrictRealtime=true
RestrictSUIDSGID=true
RuntimeDirectory=babeld
StateDirectory=babeld
SystemCallArchitectures=native
SystemCallFilter=@system-service
UMask=0177
```

The service should *successfully* start up.

Now upgrade your system to seccomp 2.5.1 (or just recompile systemd with it) and start the same service again. This time the service startup should *fail* within some startup socket code:
```
babeld[872]: kernel_setup failed.
```

Starting the service again (and slightly modifying the system call filter to allow strace) yields the following output on the newer seccomp version:
```
strace[812]: socket(AF_INET, SOCK_DGRAM, IPPROTO_IP) = -1 EAFNOSUPPORT (Address family not supported by protocol)
```

Adding `AF_INET` to `RestrictAddressFamilies` fixes the problem with libseccomp 2.5.1.

This seems like either a wrong usage of seccomp in systemd - that only surfaced after the upgrade  - or a regression within libseccomp.

I did run a bisect on libseccomp and ended up at : https://github.com/seccomp/libseccomp/commit/8147801fbc73016491d9caaab0fc740dbdbc989d

Looking at the changed manpage entry for `seccomp_reset` (https://github.com/seccomp/libseccomp/commit/8147801fbc73016491d9caaab0fc740dbdbc989d#diff-24bcffd000ff0743112b80f6844dec4eb9d7fc3e3f132c7cf599bb03c773ad38R42-R47) it begs the question if systemd should perhaps call the function after forking for the new child process?

I am aware that this might as well be an upstream issue and not an systemd bug but since this happens on two released versions and systemd is likely more prominent (since less low-level) it might be worth starting here first.

**Comment by bluca** [comment] 2020-12-27 16:14
Uhm sorry I'm not sure I follow: babeld _is_ opening an AF_INET socket in that ```kernel_setup``` function, so it seems right that without AF_INET in the RestrictAddressFamilies field it gets blocked? What am I missing?

https://sources.debian.org/src/babeld/1.9.1-1/kernel_netlink.c/?hl=533#L545

```
        dgram_socket = socket(PF_INET, SOCK_DGRAM, 0);
        if(dgram_socket < 0)
            return -1;
```

**Comment by andir** [comment] 2020-12-27 16:40
@bluca that is correct. The concering part is that this used to work (while it really shouldn't have) with the older libseccomp. It might be that on older versions the enforcement wasn't as tight as it is now and thus lettings things slip through?
I am concerned this might just one of a whole class of issues with libseccomp in systemd.

**Comment by bluca** [comment] 2020-12-27 16:55
Well, a quick review of our usage of the API seems fine, although I'm not a super expert on the subject. Have you reported this upstream?

**Comment by andir** [comment] 2020-12-27 17:03
I haven't done that yet as the API changed (see linkk in the original post) and systemd isn't making any use of it despite forking. I can create an upstream ticket and cross-reference it with this issue.

**Comment by bluca** [comment] 2020-12-27 17:10
I did a quick test calling _reset before setting all the filters in the forked process, but there's no difference as far as I can see

**Comment by andir** [comment] 2020-12-27 17:23
Mind sharing that changes you did? I'd like to run my tests with those changes against both version of libseccomp.

**Comment by bluca** [comment] 2020-12-27 18:26
Just added a reset before the filters get applied in core/execute.c

**Comment by poettering** [comment] 2020-12-28 08:59
libseccomp 2.5.0 was borked. See: https://github.com/systemd/systemd/pull/16667

The filters should work correctly before and after 2.5.0, but not with 2.5.0 itself. 

Let's close this here. if you can reproduce any issue with older or newer versions than 2.5.0 please report back and we can reopen things, but any issues reported against 2.5.0 are not interesting, since the release was faulty.

**Closed as completed by poettering** 2020-12-28 08:59 UTC
Labels: not-our-bug, seccomp

**Comment by bluca** [comment] 2020-12-28 09:43
Oops my bad, I skimmed through the libseccomp PR and was left with the impression we carried a workaround for that issue, but I see now that we do not.
