### ISSUE TITLE
systemd-252.4 breaks hibernation 

### ISSUE THREAD

**Issue by AxelG-DE** [systemd/systemd#26296] opened 2023-02-01 20:20 UTC
### systemd version the issue has been seen with

252

### Used distribution

gentoo

### Linux kernel version used

6.1.8-gentoo

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

Hibernation worked well for years on that Lenovo T450s
Hibernation still works when triggered manually (e.g. command line, such like but not limited to 'systemctl hibernate')
Hibernation does not get triggered by /etc/systemd/sleep.conf HibernateDelaySec=
--> laptop remains in S3 sleep mode as long battery allows

Nothing helpful in logs or journalctl (just like HibernateDelaySec would not exist)

Downgrade to 251 and hibernation works again as expected.

Related downstream bug: https://bugs.gentoo.org/892846

### Additional program output to the terminal or log subsystem illustrating the issue

Nothing helpful in logs or journalctl (just like HibernateDelaySec would not exist)

**Comment by YHNdnzj** [comment] 2023-02-01 20:28
Should be fixed by
https://github.com/systemd/systemd/pull/25374. It’s not backported (yet)
though.

**Comment by yuwata** [comment] 2023-02-01 20:58
Duplicate of #25269.

**Closed as completed by yuwata** 2023-02-01 20:58 UTC
Labels: bug 🐛, duplicate, sleep
