### ISSUE TITLE
nspawn: document that /usr/lib/machines gets picked up in addition to /var/lib/machines

### ISSUE THREAD

**Issue by kaihendry** [systemd/systemd#851] opened 2015-08-04 05:18 UTC
I made a stupid mistake of putting my container in `/usr/lib/machines/` instead of `/var/lib/machines`.

https://youtu.be/sP-8uo7DkWo?t=534

This caused me great confusion at https://youtu.be/sP-8uo7DkWo?t=848, since systemd-nspawn@vpn starting still worked and the status didn't tell me where the rootfs was!

**Comment by richardmaw-codethink** [comment] 2015-08-04 12:21
There's a search path defined, so you could ship an OS image that contains containers baked-in to be used read-only.
`/var/lib/machines` is used for anything you import, and if you use `--template` then you can have a container image in `/usr/lib/machines` be copied into `/var/lib/machines` on first use.

**Comment by kaihendry** [comment] 2015-08-04 14:02
Ah, I remember seeing a RO flag with my misplaced container. This makes sense, but tbh I'd rather it be called `/var/lib/machine-templates` or something. `/usr/lib/machines` is just ripe for confusion.

**Comment by richardmaw-codethink** [comment] 2015-08-04 14:59
I don't see what's confusing about `/usr/lib/machines`, perhaps you could explain why you find it confusing.

If we were to have a directory specifically for templates, `/var/lib/machine-templates` would be for templates downloaded at run-time, while `/usr/lib/machine-templates` would be for those provided by your distribution.

However, there's little difference between a template used `--read-only`, one used with `--template` and `--directory=/var/lib/machines/foo` or `--machine=foo`, and one used with `--ephemeral`, so there's not much use in a split between `/usr/lib/machine` and `/usr/lib/machine-templates`, and even less in `/var/lib/machine` vs `/var/lib/machine-templates`, since you don't even need to use `--read-only` to make use of them.

**Comment by kaihendry** [comment] 2015-08-04 15:06
I got confused between **usr** and **var**. Both 3 characters and the first and last character are quite similar. ;)

I don't quite expect my distro to provide templates. Oh well.

**Comment by poettering** [comment] 2015-08-04 21:02
We do implement a search path logic, like we do for pretty much any other resource. That means we look for read-only, OS-vendor-supplied images in /usr/lib/containers, as well as the normal, writable user-supplied images in /var/lib/containers. That's intended behaviour.

The "machinectl status" command will show you the root dir of a container, to make this easy to grok.

As it turns out this logic is currently not documented in the man page. We should fix that. Hence renaming this bug to track that this behaviour needs documenting.

**Comment by richardmaw-codethink** [comment] 2015-08-05 08:52
It's described in http://www.freedesktop.org/software/systemd/man/machinectl.html#Files%20and%20Directories, but the `--machine` option's documentation just says `/var/lib/machines`, so I guess it should point to where it's described in more detail.

**Comment by poettering** [comment] 2015-08-05 12:18
I figure we can close this now that #874 is merged.

**Closed as completed by poettering** 2015-08-05 12:18 UTC
Labels: nspawn, documentation
