### ISSUE TITLE
/usr/bin/ld.bfd: warning: src/boot/efi/systemd-bootaa64.elf has a LOAD segment with RWX permissions

### ISSUE THREAD

**Issue by enr0n** [systemd/systemd#23789] opened 2022-06-20 17:07 UTC
Building systemd for arm64 with a recent version of binutils (2.38.50.20220615-4ubuntu1) fails as a result of the following warning:

```
[67/2388] /usr/bin/cc -o src/boot/efi/systemd-bootaa64.elf -Wno-format-signedness -Wno-missing-field-initializers -Wno-unused-parameter -Wdate-time -Wendif-labels -Werror=format=2 -Werror=implicit-function-declaration -Werror=incompatible-pointer-types -Werror=int-conversion -Werror=overflow -Werror=override-init -Werror=return-type -Werror=shift-count-overflow -Werror=shift-overflow=2 -Werror=undef -Wfloat-equal -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-include-dirs -Wmissing-noreturn -Wnested-externs -Wold-style-definition -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-aliasing=2 -Wstrict-prototypes -Wsuggest-attribute=noreturn -Wunused-function -Wwrite-strings -Wno-unused-result -fno-stack-protector -fno-strict-aliasing -fpic -fwide-exec-charset=UCS2 -Wall -Wextra -Wsign-compare -nostdlib -std=gnu11 -ffreestanding -fshort-wchar -fvisibility=hidden -isystem /usr/include/efi -isystem /usr/include/efi/aarch64 -I /<<PKGBUILDDIR>>/src/fundamental -DSD_BOOT -DGNU_EFI_USE_MS_ABI -include src/boot/efi/efi_config.h -include version.h -flto -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -flto=auto -flto=auto -fuse-ld=bfd -L /usr/lib -nostdlib -T /usr/lib/elf_aarch64_efi.lds -Wl,--build-id=sha1 -Wl,--fatal-warnings -Wl,--no-undefined -Wl,--warn-common -Wl,-Bsymbolic -z nocombreloc /usr/lib/crt0-efi-aarch64.o -shared -Wl,--defsym=EFI_SUBSYSTEM=0xa src/boot/efi/bootspec-fundamental.c.o src/boot/efi/efivars-fundamental.c.o src/boot/efi/sha256.c.o src/boot/efi/string-util-fundamental.c.o src/boot/efi/assert.c.o src/boot/efi/devicetree.c.o src/boot/efi/disk.c.o src/boot/efi/graphics.c.o src/boot/efi/measure.c.o src/boot/efi/pe.c.o src/boot/efi/secure-boot.c.o src/boot/efi/ticks.c.o src/boot/efi/util.c.o src/boot/efi/boot.c.o src/boot/efi/console.c.o src/boot/efi/drivers.c.o src/boot/efi/random-seed.c.o src/boot/efi/shim.c.o src/boot/efi/xbootldr.c.o src/boot/efi/bcd.c.o -lefi -lgnuefi -lgcc
FAILED: src/boot/efi/systemd-bootaa64.elf 
/usr/bin/cc -o src/boot/efi/systemd-bootaa64.elf -Wno-format-signedness -Wno-missing-field-initializers -Wno-unused-parameter -Wdate-time -Wendif-labels -Werror=format=2 -Werror=implicit-function-declaration -Werror=incompatible-pointer-types -Werror=int-conversion -Werror=overflow -Werror=override-init -Werror=return-type -Werror=shift-count-overflow -Werror=shift-overflow=2 -Werror=undef -Wfloat-equal -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-include-dirs -Wmissing-noreturn -Wnested-externs -Wold-style-definition -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-aliasing=2 -Wstrict-prototypes -Wsuggest-attribute=noreturn -Wunused-function -Wwrite-strings -Wno-unused-result -fno-stack-protector -fno-strict-aliasing -fpic -fwide-exec-charset=UCS2 -Wall -Wextra -Wsign-compare -nostdlib -std=gnu11 -ffreestanding -fshort-wchar -fvisibility=hidden -isystem /usr/include/efi -isystem /usr/include/efi/aarch64 -I /<<PKGBUILDDIR>>/src/fundamental -DSD_BOOT -DGNU_EFI_USE_MS_ABI -include src/boot/efi/efi_config.h -include version.h -flto -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -flto=auto -flto=auto -fuse-ld=bfd -L /usr/lib -nostdlib -T /usr/lib/elf_aarch64_efi.lds -Wl,--build-id=sha1 -Wl,--fatal-warnings -Wl,--no-undefined -Wl,--warn-common -Wl,-Bsymbolic -z nocombreloc /usr/lib/crt0-efi-aarch64.o -shared -Wl,--defsym=EFI_SUBSYSTEM=0xa src/boot/efi/bootspec-fundamental.c.o src/boot/efi/efivars-fundamental.c.o src/boot/efi/sha256.c.o src/boot/efi/string-util-fundamental.c.o src/boot/efi/assert.c.o src/boot/efi/devicetree.c.o src/boot/efi/disk.c.o src/boot/efi/graphics.c.o src/boot/efi/measure.c.o src/boot/efi/pe.c.o src/boot/efi/secure-boot.c.o src/boot/efi/ticks.c.o src/boot/efi/util.c.o src/boot/efi/boot.c.o src/boot/efi/console.c.o src/boot/efi/drivers.c.o src/boot/efi/random-seed.c.o src/boot/efi/shim.c.o src/boot/efi/xbootldr.c.o src/boot/efi/bcd.c.o -lefi -lgnuefi -lgcc
/usr/bin/ld.bfd: warning: src/boot/efi/systemd-bootaa64.elf has a LOAD segment with RWX permissions
collect2: error: ld returned 1 exit status
```

This is a new linker warning, added in https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=ba951afb99912da01a6e8434126b8fac7aa75107.

**Comment by mbiebl** [comment] 2022-06-20 18:51
I'm seeing a similar issue in Debian sid
```
$ apt-cache policy binutils
binutils:
  Installiert:           2.38.50.20220615-4
  Installationskandidat: 2.38.50.20220615-4
  Versionstabelle:
 *** 2.38.50.20220615-4 500
        500 http://ftp.debian.org/debian sid/main amd64 Packages
        100 /var/lib/dpkg/status
```
```
$ ninja -C build/                                                 
ninja: Entering directory `build/'
[72/2108] Generating src/boot/efi/linuxx64.elf.stub with a custom command
FAILED: src/boot/efi/linuxx64.elf.stub 
/usr/bin/cc -o src/boot/efi/linuxx64.elf.stub -DGNU_EFI_USE_MS_ABI -DSD_BOOT -ffreestanding -fshort-wchar -fvisibility=hidden -I /home/michael/git/systemd/src/fundamental -I /home/michael/git/systemd/src/boot/efi -include src/boot/efi/efi_config.h -include version.h -isystem /usr/include/efi/x86_64 -isystem /usr/include/efi -std=gnu11 -Wall -Wextra -Wno-format-signedness -Wno-missing-field-initializers -Wno-unused-parameter -Wdate-time -Wendif-labels -Werror=format=2 -Werror=implicit-function-declaration -Werror=incompatible-pointer-types -Werror=int-conversion -Werror=overflow -Werror=override-init -Werror=return-type -Werror=shift-count-overflow -Werror=shift-overflow=2 -Werror=undef -Wfloat-equal -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-include-dirs -Wmissing-noreturn -Wnested-externs -Wold-style-definition -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-aliasing=2 -Wstrict-prototypes -Wsuggest-attribute=noreturn -Wunused-function -Wwrite-strings -Wno-unused-result -fno-stack-protector -fno-strict-aliasing -fpic -fwide-exec-charset=UCS2 -mno-red-zone -mno-sse -mno-mmx -ggdb -DEFI_DEBUG -fuse-ld=bfd -L /usr/lib -nostdlib -T /usr/lib/elf_x86_64_efi.lds -Wl,--build-id=sha1 -Wl,--fatal-warnings -Wl,--no-undefined -Wl,--warn-common -Wl,-Bsymbolic -z nocombreloc /usr/lib/crt0-efi-x86_64.o -pie -Wl,--no-dynamic-linker src/boot/efi/bootspec-fundamental.c.o src/boot/efi/efivars-fundamental.c.o src/boot/efi/sha256.c.o src/boot/efi/string-util-fundamental.c.o src/boot/efi/assert.c.o src/boot/efi/devicetree.c.o src/boot/efi/disk.c.o src/boot/efi/efi-string.c.o src/boot/efi/graphics.c.o src/boot/efi/initrd.c.o src/boot/efi/measure.c.o src/boot/efi/pe.c.o src/boot/efi/secure-boot.c.o src/boot/efi/ticks.c.o src/boot/efi/util.c.o src/boot/efi/cpio.c.o src/boot/efi/splash.c.o src/boot/efi/stub.c.o src/boot/efi/linux_x86.c.o -lefi -lgnuefi -lgcc
/usr/bin/ld.bfd: warning: /usr/lib/crt0-efi-x86_64.o: missing .note.GNU-stack section implies executable stack
/usr/bin/ld.bfd: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
collect2: error: ld returned 1 exit status
[77/2108] Generating catalog/systemd.ru.catalog with a custom command (wrapped by meson to capture output)
ninja: build stopped: subcommand failed.
```

**Comment by mbiebl** [comment] 2022-06-20 18:52
Is that a regression in binutils or something that should be addressed on the systemd side?

**Comment by mbiebl** [comment] 2022-06-20 18:57
https://sourceware.org/bugzilla/show_bug.cgi?id=29072

**Comment by enr0n** [comment] 2022-06-20 19:25
> I'm seeing a similar issue in Debian sid
> 
> ```
> $ apt-cache policy binutils
> binutils:
>   Installiert:           2.38.50.20220615-4
>   Installationskandidat: 2.38.50.20220615-4
>   Versionstabelle:
>  *** 2.38.50.20220615-4 500
>         500 http://ftp.debian.org/debian sid/main amd64 Packages
>         100 /var/lib/dpkg/status
> ```
> 
> ```
> $ ninja -C build/                                                 
> ninja: Entering directory `build/'
> [72/2108] Generating src/boot/efi/linuxx64.elf.stub with a custom command
> FAILED: src/boot/efi/linuxx64.elf.stub 
> /usr/bin/cc -o src/boot/efi/linuxx64.elf.stub -DGNU_EFI_USE_MS_ABI -DSD_BOOT -ffreestanding -fshort-wchar -fvisibility=hidden -I /home/michael/git/systemd/src/fundamental -I /home/michael/git/systemd/src/boot/efi -include src/boot/efi/efi_config.h -include version.h -isystem /usr/include/efi/x86_64 -isystem /usr/include/efi -std=gnu11 -Wall -Wextra -Wno-format-signedness -Wno-missing-field-initializers -Wno-unused-parameter -Wdate-time -Wendif-labels -Werror=format=2 -Werror=implicit-function-declaration -Werror=incompatible-pointer-types -Werror=int-conversion -Werror=overflow -Werror=override-init -Werror=return-type -Werror=shift-count-overflow -Werror=shift-overflow=2 -Werror=undef -Wfloat-equal -Wimplicit-fallthrough=5 -Winit-self -Wlogical-op -Wmissing-include-dirs -Wmissing-noreturn -Wnested-externs -Wold-style-definition -Wpointer-arith -Wredundant-decls -Wshadow -Wstrict-aliasing=2 -Wstrict-prototypes -Wsuggest-attribute=noreturn -Wunused-function -Wwrite-strings -Wno-unused-result -fno-stack-protector -fno-strict-aliasing -fpic -fwide-exec-charset=UCS2 -mno-red-zone -mno-sse -mno-mmx -ggdb -DEFI_DEBUG -fuse-ld=bfd -L /usr/lib -nostdlib -T /usr/lib/elf_x86_64_efi.lds -Wl,--build-id=sha1 -Wl,--fatal-warnings -Wl,--no-undefined -Wl,--warn-common -Wl,-Bsymbolic -z nocombreloc /usr/lib/crt0-efi-x86_64.o -pie -Wl,--no-dynamic-linker src/boot/efi/bootspec-fundamental.c.o src/boot/efi/efivars-fundamental.c.o src/boot/efi/sha256.c.o src/boot/efi/string-util-fundamental.c.o src/boot/efi/assert.c.o src/boot/efi/devicetree.c.o src/boot/efi/disk.c.o src/boot/efi/efi-string.c.o src/boot/efi/graphics.c.o src/boot/efi/initrd.c.o src/boot/efi/measure.c.o src/boot/efi/pe.c.o src/boot/efi/secure-boot.c.o src/boot/efi/ticks.c.o src/boot/efi/util.c.o src/boot/efi/cpio.c.o src/boot/efi/splash.c.o src/boot/efi/stub.c.o src/boot/efi/linux_x86.c.o -lefi -lgnuefi -lgcc
> /usr/bin/ld.bfd: warning: /usr/lib/crt0-efi-x86_64.o: missing .note.GNU-stack section implies executable stack
> /usr/bin/ld.bfd: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
> collect2: error: ld returned 1 exit status
> [77/2108] Generating catalog/systemd.ru.catalog with a custom command (wrapped by meson to capture output)
> ninja: build stopped: subcommand failed.
> ```

I believe that specific warning (`/usr/bin/ld.bfd: warning: /usr/lib/crt0-efi-x86_64.o: missing .note.GNU-stack section implies executable stack`) actually needs to be fixed in gnu-efi. See https://github.com/systemd/systemd/issues/23149 and also https://sourceforge.net/p/gnu-efi/bugs/28/.

So that is different than what I am seeing on arm64, but is also because of a new linker warning in binutils.

**Comment by enr0n** [comment] 2022-06-20 19:27
For now I am silencing the warning with `--no-warn-rwx-segments`, but I don't know if that's the desired fix.

**Comment by yuwata** [comment] 2022-07-13 16:54
Should be fixed (at least, hidden) by #23996. Closing.

**Comment by FantasqueX** [comment] 2022-10-11 10:32
Hi, I recently solved a similar problem "a LOAD segment with RWX permissions" on riscv64 gnu-efi. I think solutions may be the same. I tried to comment code which adds mitigation flags and rebuilt; however, I could build successfully. I also tried to check the commit just before #23996, it also builds successfully.

FYI, I use ArchLinux with gcc 12.1.0 and binutils 2.39. Build options are `-Dgnu-efi=true`.

Any hint about how to trigger build failures?

**Comment by medhefgo** [comment] 2022-10-12 11:39
Latest gnu-efi was fixed to emit the proper flags to the binaries it creates. Try downgrading.

**Comment by FantasqueX** [comment] 2022-10-13 17:35
As far as I know, gnu-efi solved this problem only in x86_64  and riscv64. All other architectures have this kind of problem. These flags are necessary currently.

Thanks for your explanation!

**Comment by ozbenh** [comment] 2022-12-21 02:04
The remaining  problem on aarch64 is that ld now assumes a 64K page size and the .lds provided by gnu-efi only provides 4k alignment. Passing `-z maz-page-size=4064` to the linker might help here (UEFI mandates a 4k page size anyways). I haven't tried (I have other patches messing this around), it's possible that there's a remaining issue with .dynamic not being aligned either in that .lds

**Comment by ozbenh** [comment] 2022-12-21 02:45
This PR https://github.com/rhboot/gnu-efi/pull/6 (Fedora's gnu-efi 'fork') addresses the issues in gnu-efi. I've also sent patches to the gnu-efi-discuss mailing list on sourceforge against upstream gnu-efi.

systemd should also add `-z max-page-size=4096` for the fix to be complete. You can keep the mitigation for now until gnu-efi has been more generally fixed

**Comment by ozbenh** [comment] 2022-12-21 02:45
(opening a new issue... easier that way, this one is closed)

**Comment by poettering** [comment] 2022-12-21 19:43
Reopening, since there's apparently still something to do for us.

**Comment by keszybz** [comment] 2023-01-24 07:05
@medhefgo You're the most likely to know what to do here… Does #26110 affect this?

**Comment by medhefgo** [comment] 2023-01-24 08:57
#26110 only removes the gnu-efi helper library. We still use the linker script and the pe stub.

**Comment by ozbenh** [comment] 2023-01-25 01:08
The discussion on the `gnu-efi` (and IRC) list hasn't quite reached a conclusion ... Adding -z maz-page-size and fixing up the .lds to properly move .dynamic out of .text (tack it at the end of .data) would work though, but I suspect systemd doesn't want to carry its own lds. I'm still hoping Robbie or Peter will look at my Fedora PR and comment (or apply)

**Closed as completed** 2023-02-09 12:38 UTC
Labels: sd-boot/sd-stub/bootctl
