### ISSUE TITLE
dramatic increase in CPU usage if DNS traffic is blocked via REJECT action instead of DROP

### ISSUE THREAD

**Issue by dog-barks** [systemd/systemd#33862] opened 2024-07-29 14:26 UTC
### systemd version the issue has been seen with

255

### Used distribution

Fedora 40

### Linux kernel version used

6.9.7-200.fc40.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

If we have firewall rules (e.g., via iptables/nftables) on the local system with a `REJECT` action (`-j REJECT`), then `resolvectl query DOMAIN_NAME` causes very high CPU usage in the `systemd-resolved` process. However, if we use `-j DROP` as the action in iptables, this does NOT occur.

It seems understandable that there would be a difference, but a busy loop consuming lots of CPU time seems undesirable. After all, the high CPU usage symptom **does NOT occur on systems without systemd-resolved**.

To reproduce the issue, one can use this fw rule: `iptables -I OUTPUT -p udp --dport 53 -j REJECT`

### Unexpected behaviour you saw

Observe very high CPU usage in systemd-resolved (like 70% or 95%).

### Steps to reproduce the problem

```
iptables -I OUTPUT -p udp --dport 53 -j REJECT
resolvectl query wikipedia.org
```

**Comment by Werkov** [comment] 2024-07-31 15:42
Looks like a dupe of #33719.

**Closed as not planned** 2024-08-01 13:15 UTC
Labels: resolve, duplicate
