### ISSUE TITLE
Systemd crashes on startup after update to 229

### ISSUE THREAD

**Issue by lukewink** [systemd/systemd#3747] opened 2016-07-18 00:19 UTC
### Submission type
- [x ] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

229
### Used distribution

Arch
### In case of bug report: Expected behaviour you didn't see

System boots
### In case of bug report: Unexpected behaviour you saw

> systemd[1]: Assertion 'i' failed at src/basic/unit-name.c:463, function unit_name_replace_instance().  Aborting.
> systemd[1]: Caught <ABRT>, dumped core as pid 165.
> systemd[1]: Freezing execution
### In case of bug report: Steps to reproduce the problem

Not sure, I did a regular pacman update which upgraded systemd from 228 to 229.  After the update, I noticed that every systemctl command ended with a "Connected timed out" error.  I thought a reboot might fix the problem, but then I got the error listed up above.

The error states that there is a core dump, but I can't find it anywhere.  The /var/lib/systemd/coredump directory is empty.

**Comment by evverx** [comment] 2016-07-18 00:59
> systemd version the issue has been seen with
> 229

Does your package contain 7aad67e7f2b3dfbc3b5a884471bd551e4bf997cc ?

> systemd[1]: Assertion 'i' failed at src/basic/unit-name.c:463, function unit_name_replace_instance(). Aborting.

Seems like https://github.com/systemd/systemd/issues/3438#issuecomment-223834037
Try https://github.com/systemd/systemd/pull/3451

> The error states that there is a core dump, but I can't find it anywhere

Maybe https://github.com/systemd/systemd/issues/3285

**Comment by falconindy** [comment] 2016-07-18 02:34
Arch is shipping v230, not v229. Could you please upgrade and ensure that you can still reproduce this bug?

**Comment by lukewink** [comment] 2016-07-18 07:11
Sorry for the confusion.  I was running Arch version 230-5 which is the latest.  I thought it was 229 because on boot it says "Starting version 229".  For now I have downgraded back to  229-3 and the problem has gone away.

> Does your package contain 7aad67e ?
> I don't know how I would verify if the Arch package contains this commit or not.  I would need to open a ticket with the Arch maintainer.

**Comment by evverx** [comment] 2016-07-18 07:27
According to the [PKGBUILD](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/systemd&id=676fc46abc76cd008601b3f4fcd9b74c5fc556e4) the `230-5` contains  7aad67e and doesn't contain 85407be7a8db4

So, I think this is a duplicate of #3438

**Comment by falconindy** [comment] 2016-07-18 12:09
This is now backported in Arch's systemd package, 230-7.

If you still see "229" on bootup, then you haven't rebuilt your initramfs since upgrading to v230. As such, it contains an older udev/systemd.

**Comment by poettering** [comment] 2016-07-19 11:16
OK, as #3438 is fixed, let's close this one too.

**Closed as completed by poettering** 2016-07-19 11:16 UTC
Labels: duplicate
