### ISSUE TITLE
*.mail.protection.outlook.com not correctly resolved when DNSSEC is enabled.

### ISSUE THREAD

**Issue by HLFH** [systemd/systemd#28526] opened 2023-07-26 12:02 UTC
### systemd version the issue has been seen with

253

### Used distribution

Arch Linux

### Linux kernel version used

6.3.9-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

A and/or AAAA records for *.mail.protection.outlook.com are not correctly resolved.

Related to: https://serverfault.com/questions/1075903/postfix-not-resolving-outlook-domain-names-length

### Unexpected behaviour you saw

Mail with Postfix is deferred with message:

> Host or domain name not found. Name service error for name=example.mail.protection.outlook.com type=A: Host not found, try again)

### Steps to reproduce the problem

Enable DNSSEC in systemd-resolved
Send an email to someone using *mail.protection.outlook.com.
Email gets deferred because with DNSSEC enabled, even if the A record is present, it is not correctly resolved by systemd-resolved.

**Comment by svillemot** [comment] 2023-11-13 17:23
Looks like a duplicate of #24747

**Closed as completed** 2023-11-13 17:29 UTC
Labels: bug 🐛, resolve, duplicate, dnssec

**Comment by pemensik** [comment] 2024-07-26 10:44
Btw this issue has old entry at DNS violations: https://github.com/dns-violations/dns-violations/blob/master/2020/DVE-2020-0003.md
