### ISSUE TITLE
Consider joining "DNS Flag Day" - drop support for broken DNS servers

### ISSUE THREAD

**Issue by srd424** [systemd/systemd#9799] opened 2018-08-05 16:10 UTC
Multiple resolver vendors are intending to drop work arounds for DNS servers that drop queries with EDNS OPT RRs:

https://dnsflagday.net/
https://en.blog.nic.cz/2018/03/14/together-for-better-stability-speed-and-further-extensibility-of-the-dns-ecosystem/
https://datatracker.ietf.org/doc/draft-spacek-edns-camel-diet/

systemd-resolved authors may want to consider whether it is worth joining them, at the risk of (temporarily?) impairing end-user experience..

**Comment by ott** [comment] 2018-08-31 22:59
I think it is necessary to know how much broken CPE would be affected by this change. DNS resolvers like Unbound or Knot Resolver mostly query authoritative DNS servers or more standards-compliant upstream resolvers. The situation in home networks might be different, in particular in poorer parts of the world that don't change hardware so often.

For example, a quick search about some Fritz!Box and Speedport CPE, which are both popular in Germany and provided to subscribers by major ISPs, seem to not support EDNS0. Unfortunately, I don't have both devices and can't check whether the claims are true. I remember from RIPE Atlas measurements that Fritz!Box CPE do not support DNS over TCP or DNSSEC and have a very basic DNS resolver.

Perhaps we could measure it with the help of the RIPE Atlas. We would just have to make a query that has an answer that is longer than 512 bytes, set some EDNS0 options in the query and then check whether it can be resolved. However, I don't know how representative this is.

**Comment by ott** [comment] 2018-09-01 00:17
I also think that most of the inefficiencies that are mentioned disappear when systemd-resolved's feature set detection is improvied. See  #9384.

Another important consideration is that systemd-resolved queries just a few upstream resolvers while proper recursive DNS servers query many other servers and have to wait for EDN0 timeouts. So I'm not sure that the problem really applies for systemd-resolved.

**Comment by srd424** [comment] 2018-09-02 13:55
Both very good points - I also have a feeling I'm not done chasing down
dnsmasq quirks around EDNS0, and that will be a very common resolver found
in consumer grade routers etc. So perhaps the answer to my original
question is a definite "no, not appropriate" on this one..

**Comment by ott** [comment] 2018-09-02 19:29
Perhaps we can close this issue then and reopen it when the situation changes.

If you find out more about dnsmasq EDNS0 problems, it would be good if you could report them. I also run dnsmasq and systemd-resolved together and would be happy to help if the problem is in systemd-resolved.

**Closed as completed** 2018-09-02 20:07 UTC
Labels: resolve
