### ISSUE TITLE
timesyncd tries to set time forever when it can't set the system's time

### ISSUE THREAD

**Issue by StyXman** [systemd/systemd#20608] opened 2021-09-01 08:16 UTC
I think in this situation, `timesyncd` should stop retrying:

```
09:38 $ /lib/systemd/systemd-timesyncd 
Directory "/var/lib/systemd/timesync" already exists, but is owned by 100:102 (1001:1001 was requested), refusing.
Failed to call clock_adjtime(): Operation not permitted
Initial synchronization to time server 91.189.91.157:123 (ntp.ubuntu.com).
Failed to call clock_adjtime(): Operation not permitted
[...]
```

and it just keeps on going forever (or at least once per minute for more than 30m :).

**Comment by poettering** [comment] 2021-09-01 15:06
Hmm, should we really change this? I mean, it's a really broken setup, if we can't set the time. it's definitely a configuration error if this happens. As long as we don't crash or busy-loop we are fine. But if this is just once per minute I think we are OK. I mean we could also exit in this case, i.e. make the failure fatal. But I think that'd be pointless. First of all we have set Restart=always for the service, so as it stands now timesyncd would just be restarted again, which hence would require more work, to distinguish the error causes here. But more importantly: the error might very well be transient, i.e. people fix their MAC policy and reload it, hence there's a chance we can recover.

Also, note that timesyncd touches a touch file on disk on each NTP sync, which helps ensuring time progresses monotonically, and we still do that if clock_adjtime() fails, and hence it still serves a purpose.

Hence, I think we should just close this: it's a configuration error we handle pretty gracefully, but that's not really a bad thing, but a good one.

**Comment by StyXman** [comment] 2021-09-02 08:04
> it's a really broken setup, if we can't set the time. it's definitely a configuration error if this happens

isn't the issue that the command is being run as a user that does not have enough permissions?

**Comment by poettering** [comment] 2021-09-02 08:10
systemd-timesyncd as shipped with systemd runs with CAP_SYS_TIME capabilities, so out of the box everything works as it should.

if for some reason in your case the privs are gone, this is caused by some local security fuckup? maybe some LSM/MAC that is misconfigured?

**Comment by StyXman** [comment] 2021-09-02 17:05
> some local security fuckup

I don't appreciate the language here. 'local misconfiguration' would have been enough here.

I also have to deduce from your lack of explanation that the command I execute has nothing to do with the error displayed, but it comes from the daemon that's in charge of updating the time, and the command just tells it to do the update. None of that is mentioned in the manpage, or the fact that it will try indefinitely. I don't even know what LSM or MAC are in this context.

If that's the case, I still think the command should fail and the daemon should stop trying doing the update without exiting.

**Comment by floppym** [comment] 2021-09-02 19:01
Oh, you're actually executing systemd-timesyncd directly from a shell.

Don't do that -- it is meant to be run via the system service (systemd-timesyncd.service).

**Comment by floppym** [comment] 2021-09-02 19:03
In other words, run `systemctl start systemd-timesyncd.service` to start it immediately, and `systemctl enable systemd-timesyncd.service` to start it on boot.

**Comment by poettering** [comment] 2021-09-02 20:29
oh, indeed. don't run this from the command line, as unpriv users, that' cannot work.

It's tucked away in /usr/lib/ for a reason: since its not meant to be started by hand, but as a system service via a service unit file.

Closing.

**Closed as completed by poettering** 2021-09-02 20:29 UTC
Labels: needs-discussion 🤔, timesync
