### ISSUE TITLE
run0 invoked at cli can not open display

### ISSUE THREAD

**Issue by zeekisthename** [systemd/systemd#32874] opened 2024-05-16 18:56 UTC
### systemd version the issue has been seen with

256

### Used distribution

Fedora 41

### Linux kernel version used

kernel 6.9.0-rc4

### CPU architectures issue was seen on

x86_64

### Component

systemd-run

### Expected behaviour you didn't see

If run0 is supposed to inherit shell characteristics that function similar to sudo, running cli:

run0 caja  ....failure to open display/launch file manager caja

### Unexpected behaviour you saw

run0 caja  ...can not open display

### Steps to reproduce the problem

run0 caja using cli

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
systemd 256 installed

run0 caja (mate desktop file manager)

Cannot open display:

xhost + did not resolve the issue.

echo $DISPLAY shows :0.0

.bashrc specifies:

export DISPLAY=:0.0

From what I read run0 is supposed to have execution characteristics similar to using sudo.  However sudo works fine with existing parameters when file manager and other programs are initiated via cli, opening X/display window.

Is there a parameter that needs to be specified for .bashrc or .profile or environment, in order for run0 to connect to X?

Please give an example of command line syntax and any cofig file parameters necessary for run0 to execute an application requiring X/display.

Thank you.
```

**Comment by YHNdnzj** [comment] 2024-05-16 19:42
Sorry, but `run0` doesn't inherit envvars such as `$DISPLAY` by default, and I'm pretty sure it shouldn't. Running GUI applications as root is a terrible idea TBH. If you want to do that anyway, please specify `--setenv=DISPLAY=$DISPLAY`.

Not a bug, closing.

**Closed as completed** 2024-05-16 19:43 UTC
Labels: run, not-supported, not-a-bug
