### ISSUE TITLE
Valid link config not completely applied at boot

### ISSUE THREAD

**Issue by aurelien-enchanted-tools** [systemd/systemd#30539] opened 2023-12-20 11:38 UTC
### systemd version the issue has been seen with

v253-stable 6c327d74aa0d350482e82a247d7018559699798d

### Used distribution

Yocto poky mickledore

### Linux kernel version used

5.10.120-l4t-r35.4.ga+g76678311c10b

### CPU architectures issue was seen on

aarch64

### Component

systemd-networkd

### Expected behaviour you didn't see

2 boards with the same config, both connected together directly and booted together. The connection is working, but at boot time, it is not set to 100Mbps automatically.

```bash
sudo tee /etc/systemd/network/10-interboards.link << "EOF"
[Match]
Driver=lan743x
[Link]
Name=interboards
AutoNegotiation=no
Duplex=full
BitsPerSecond=100M
EOF
```

after boot:
```
networkctl status interboards --no-pager -l
[…]
              Auto negotiation: no
                         Speed: 100Mbps
                        Duplex: full
[…]
```

### Unexpected behaviour you saw

after boot:
```
networkctl status interboards --no-pager -l
● 4: interboards                                                                            
                     Link File: /etc/systemd/network/95-interboards.link
                  Network File: /usr/lib/systemd/network/80-wired.network
                         State: degraded (configuring)
                  Online state: online 
                          Type: ether
                          Path: platform-14160000.pcie-pci-0004:01:00.0
                        Driver: lan743x
                        Vendor: Microchip Technology / SMSC
                         Model: LAN7430
              Hardware Address: 46:65:01:93:23:22
                           MTU: 1500 (min: 68, max: 9216)
                         QDisc: pfifo_fast
  IPv6 Address Generation Mode: eui64
      Number of Queues (Tx/Rx): 1/1
              Auto negotiation: yes
                         Speed: 1Gbps
                        Duplex: full
                          Port: mii
                       Address: 192.168.0.141
                                fe80::4465:1ff:fe93:2322
             Activation Policy: up
           Required For Online: yes
             DHCP6 Client DUID: DUID-LL:00014665019323220000

Mar 03 09:49:20 custom-hostname (udev-worker)[284]: interboards: Could not disable auto negotiation, ignoring: No such device
Mar 03 09:49:20 custom-hostname (udev-worker)[284]: interboards: Could not set speed to 100Mbps, ignoring: No such device
Mar 03 09:49:20 custom-hostname (udev-worker)[284]: interboards: Could not set duplex to full, ignoring: No such device
Dec 20 11:04:17 custom-hostname systemd-networkd[420]: interboards: Configuring with /usr/lib/systemd/network/80-wired.network.
Dec 20 11:04:17 custom-hostname systemd-networkd[420]: interboards: Link UP
Dec 20 11:04:19 custom-hostname systemd-networkd[420]: interboards: Gained carrier
Dec 20 11:04:20 custom-hostname systemd-networkd[420]: interboards: Gained IPv6LL
[…]
```
The name is applied on the network interface, but other configs in the link file are not applied.
```
sudo SYSTEMD_LOG_LEVEL=debug udevadm test-builtin net_setup_link /sys/class/net/interboards
Trying to open "/etc/systemd/hwdb/hwdb.bin"...
Trying to open "/etc/udev/hwdb.bin"...
Trying to open "/usr/lib/systemd/hwdb/hwdb.bin"...
Trying to open "/usr/lib/udev/hwdb.bin"...
=== trie on-disk ===
tool version:          253
file size:        10091891 bytes
header size             80 bytes
strings            2500083 bytes
nodes              7591728 bytes
Loading kernel module index.
Found cgroup2 on /sys/fs/cgroup/unified, unified hierarchy for systemd controller
Found container virtualization none.
Using default interface naming scheme 'v253'.
Skipping overridden file '/usr/lib/systemd/network/99-default.link'.
Skipping empty file: /etc/systemd/network/99-default.link
Parsed configuration file "/etc/systemd/network/95-interboards.link"
Created link configuration context.
interboards: Device has name_assign_type=4
interboards: Device has addr_assign_type=0
ID_NET_DRIVER=lan743x
interboards: Config file /etc/systemd/network/95-interboards.link is applied
ethtool: setting speed, duplex, or port, disabling autonegotiation.
interboards: Using static MAC address.
interboards: Policies didn't yield a name, using specified Name=interboards.
ID_NET_LINK_FILE=/etc/systemd/network/95-interboards.link
ID_NET_NAME=interboards
ID_NET_LINK_FILE_DROPINS=
Unload kernel module index.
Unloaded link configuration context.
```
After the previous `sudo SYSTEMD_LOG_LEVEL=debug udevadm test-builtin net_setup_link /sys/class/net/interboards`
```
networkctl status interboards --no-pager -l
● 4: interboards                                                                            
                     Link File: /etc/systemd/network/95-interboards.link
                  Network File: /usr/lib/systemd/network/80-wired.network
                         State: degraded (configuring)
                  Online state: online                                                      
                          Type: ether
                          Path: platform-14160000.pcie-pci-0004:01:00.0
                        Driver: lan743x
                        Vendor: Microchip Technology / SMSC
                         Model: LAN7430
              Hardware Address: 46:65:01:93:23:22
                           MTU: 1500 (min: 68, max: 9216)
                         QDisc: pfifo_fast
  IPv6 Address Generation Mode: eui64
      Number of Queues (Tx/Rx): 1/1
              Auto negotiation: no
                         Speed: 100Mbps
                        Duplex: full
                          Port: mii
                       Address: 192.168.0.141
                                fe80::4465:1ff:fe93:2322
             Activation Policy: up
           Required For Online: yes
             DHCP6 Client DUID: DUID-LL:00014665019323220000

Mar 03 09:49:20 custom-hostname (udev-worker)[284]: interboards: Could not disable auto negotiation, ignoring: No such device
Mar 03 09:49:20 custom-hostname (udev-worker)[284]: interboards: Could not set speed to 100Mbps, ignoring: No such device
Mar 03 09:49:20 custom-hostname (udev-worker)[284]: interboards: Could not set duplex to full, ignoring: No such device
Dec 20 11:04:17 custom-hostname systemd-networkd[420]: interboards: Configuring with /usr/lib/systemd/network/80-wired.network.
Dec 20 11:04:17 custom-hostname systemd-networkd[420]: interboards: Link UP
Dec 20 11:04:19 custom-hostname systemd-networkd[420]: interboards: Gained carrier
Dec 20 11:04:20 custom-hostname systemd-networkd[420]: interboards: Gained IPv6LL
Dec 20 11:15:21 custom-hostname systemd-networkd[420]: interboards: Lost carrier
Dec 20 11:15:21 custom-hostname systemd-networkd[420]: interboards: DHCPv6 lease lost
Dec 20 11:15:24 custom-hostname systemd-networkd[420]: interboards: Gained carrier
```

**Comment by yuwata** [comment] 2023-12-20 11:55
I guess the driver does not support to configure such setting when the interface is down?

Could you try the following steps?
1. stop systemd-networkd
2. manually down the interface (`ip link set interboards down`),
3. manually configure the interface speed with ethtool.

**Comment by aurelien-enchanted-tools** [comment] 2023-12-20 12:58
```
sudo systemctl stop systemd-networkd
sudo ip link set interboards down
[ 6691.862897] lan743x 0004:01:00.0 interboards: ptp clock unregister
[ 6691.863100] lan743x 0004:01:00.0 interboards: Link is Down
sudo ethtool -s interboards speed 100 duplex full autoneg off
netlink error: failed to retrieve link settings
netlink error: No such device
```

**Comment by yuwata** [comment] 2023-12-20 13:56
Thank you for the confirmation. So, this is a duplicate of #16445.

**Closed as completed by yuwata** 2023-12-20 13:56 UTC
Labels: bug 🐛, udev, duplicate
