### ISSUE TITLE
Multiple daemons hang waiting to log messages to journald

### ISSUE THREAD

**Issue by pevogam** [systemd/systemd#16456] opened 2020-07-14 11:53 UTC
**systemd version the issue has been seen with**
> systemd 245 (v245.6-2.fc32)

**Used distribution**
 > Fedora 32

**Unexpected behaviour you saw**
 > Multiple daemons like `sshd` and `dnsmasq` get stuck sporadically with a frequency of about once every few hours.

Stracing both in the respective order brought me to these outputs:
```
openat(AT_FDCWD, "/etc/localtime", O_RDONLY|O_CLOEXEC) = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=2104, ...}) = 0
fstat(4, {st_mode=S_IFREG|0644, st_size=2104, ...}) = 0
read(4, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\t\0\0\0\t\0\0\0\0"..., 4096) = 2104
lseek(4, -1340, SEEK_CUR)               = 764
read(4, "TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\v\0\0\0\v\0\0\0\0"..., 4096) = 1340
close(4)                                = 0
socket(AF_UNIX, SOCK_DGRAM|SOCK_CLOEXEC, 0) = 4
connect(4, {sa_family=AF_UNIX, sun_path="/dev/log"}, 110) = 0
sendto(4, "<86>Jul 13 22:48:16 sshd: pam_un"..., 89, MSG_NOSIGNAL, NULL, 0
```
and
```
# strace -p 2481
strace: Process 2481 attached
write(12, "<30>Jul 13 23:59:36 dnsmasq[2481"..., 67^Cstrace: Process 2481 detached
 <detached ...>
```
Following up on this, I could quickly reproduce the hanging with command like `journalctl --flush` which when straced ends up here
```
prlimit64(0, RLIMIT_NOFILE, {rlim_cur=512*1024, rlim_max=512*1024}, NULL) = 0
rt_sigaction(SIGWINCH, {sa_handler=0x7f4e9ce82860, sa_mask=[WINCH], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f4e9d015ab0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
rt_sigaction(SIGBUS, {sa_handler=0x7f4e9ce797b0, sa_mask=[], sa_flags=SA_RESTORER|SA_SIGINFO, sa_restorer=0x7f4e9d015ab0}, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=0}, 8) = 0
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
connect(3, {sa_family=AF_UNIX, sun_path="/run/systemd/journal/io.systemd.journal"}, 42) = 0
sendto(3, "{\"method\":\"io.systemd.Journal.Fl"..., 59, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 59
mmap(NULL, 135168, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f4e8e86d000
mremap(0x7f4e8e86d000, 135168, 139264, MREMAP_MAYMOVE) = 0x7f4e8e84b000
recvfrom(3, 0x7f4e8e84b010, 135152, MSG_DONTWAIT, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
ppoll([{fd=3, events=POLLIN}], 1, NULL, NULL, 8
```
Thus, the flushing too is waiting to read some data on fd 3 and journald which should be writing on the other side of the noblocking `/run/systemd/journal/io.systemd.journal` socket is not responding resulting in this EAGAIN outcome for `recvfrom` while ppoll already blocks waiting for the missing data.

Going all the way and resetting the entire `systemd-journald` service fixes the problem until the next time it happens.

**Steps to reproduce the problem**
As of yet this is not fully reproducible and as you can see a sporadic problem but any help debugging the issue would be highly appreciated.

**Comment by poettering** [comment] 2020-07-14 12:47
So, what is journald doing when you see those hangs? Apparently journald is not processing client requests and thus the clients stall. Question is what journald itself is doing, i.e. try to acquire a backtrace with gdb, or at least strace. Or maybe kill journald with SIGABRT so that it coredumps and you get a backtrace via coredumpctl

**Comment by pevogam** [comment] 2020-07-14 14:18
Stracing the currently stuck `journald` shows it is looping:
```
...
epoll_wait(7, [{EPOLLIN|EPOLLERR|EPOLLHUP, {u32=28542720, u64=94583798335232}}, {EPOLLIN, {u32=28541904, u64=94583798334416}}, {EPOLLIN, {u32=28542448, u64=94583798334960}}, {EPOLLIN, {u32=28542176, u64=94583798334688}}, {EPOLLIN, {u32=28543200, u64=94583798335712}}], 21, 0) = 5
writev(2, [{iov_base="/dev/kmsg buffer overrun, some m"..., iov_len=45}, {iov_base="\n", iov_len=1}], 2) = 46
read(8, "", 8192)                       = 0
gettid()                                = 52
epoll_wait(7, [{EPOLLIN|EPOLLERR|EPOLLHUP, {u32=28542720, u64=94583798335232}}, {EPOLLIN, {u32=28541904, u64=94583798334416}}, {EPOLLIN, {u32=28542448, u64=94583798334960}}, {EPOLLIN, {u32=28542176, u64=94583798334688}}, {EPOLLIN, {u32=28543200, u64=94583798335712}}], 21, 0) = 5
writev(2, [{iov_base="/dev/kmsg buffer overrun, some m"..., iov_len=45}, {iov_base="\n", iov_len=1}], 2) = 46
read(8, "", 8192)                       = 0
gettid()                                = 52
...
epoll_wait(7, [{EPOLLIN|EPOLLERR|EPOLLHUP, {u32=28542720, u64=94583798335232}}, {EPOLLIN, {u32=28541904, u64=94583798334416}}, {EPOLLIN, {u32=28542448, u64=94583798334960}}, {EPOLLIN, {u32=28542176, u64=94583798334688}}, {EPOLLIN, {u32=28543200, u64=94583798335712}}], 21, 0) = 5^C
strace: Process 52 detached
```

So I guess the key takeaway here is `/dev/kmsg buffer overrun`.

I could also go the `coredumpctl` path if this is not sufficient but will keep the currently stuck process for now in order to be able to debug further.

**Comment by poettering** [comment] 2020-07-14 15:25
hmm, so we apparently get EPOLLERR from /dev/kmsg (which is supposed to indicate a kmsg overrun), and then we read from it and get no bytes back, and this doesn't reset the EPOLERR condition, like it's supposed to.

Smells like a kernel regression to me, I figure it changed behaviour there?

**Comment by poettering** [comment] 2020-07-14 15:27
does this go away if you switch to an older kernel version?

**Comment by pevogam** [comment] 2020-07-14 15:38
The kernel situation is a bit more complicated. Let me explain:

We encounter this error on a Fedora 32 linux container which runs on CentOS 7 kernel:

```
# uname -a
Linux c24 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

For what it is worth the kernel didn't change for a long time but we get this issue once we move from Fedora 31 to Fedora 32. I haven't detected any such problems with a Fedora 31 container. By some time tomorrow we could finish some testing with the Fedora 32 container on top a Fedora 32 kernel (physical host) and I will report back if the issue occurs there too.

**Comment by poettering** [comment] 2020-07-14 16:45
What kind of container? Nspawn? Podman? Docker? Looks like a bug in that container manager. It provides a borked /dev/kmsg

**Comment by poettering** [comment] 2020-07-14 17:46
Also, it note that current systemd versions require kernel 3.13 as minimum, see README. What you are doing is not supported.

Please start your bug reports with indicating you use such an old kernel from a different distro instead of claiming it was Fedora 32. Because it's not. Also, mention that you use a container manager and which. Whether things run in a container manager or not make a major difference.

Anyway, closing, since this is not supported anyway, and the specific issue almost certainly an issue with your container manager. It probably provides some fucked up FIFO or so in place of /dev/kmsg, and then closes it or so? It really shouldn't do that. Closing.

**Closed as completed by poettering** 2020-07-14 17:46 UTC
Labels: journal, not-our-bug, needs-reporter-feedback ❓

**Comment by pevogam** [comment] 2020-07-14 20:42
> What kind of container? Nspawn? Podman? Docker? Looks like a bug in that container manager. It provides a borked /dev/kmsg

It is a linux container (LXC) as I already mentioned above.

> Anyway, closing, since this is not supported anyway, and the specific issue almost certainly an issue with your container manager. It probably provides some fucked up FIFO or so in place of /dev/kmsg, and then closes it or so? It really shouldn't do that. Closing.

It would have been better if we could follow my original post that states we are also currently testing this with Fedora 32 host machines and that I will confirm tomorrow some time if we encounter it there as well but I guess this issue couldn't wait for some reason. Also note that I the last systemd release in Fedora 31 worked just fine. Anyway, thanks for the valuable feedback!

**Comment by pevogam** [comment] 2020-07-15 16:46
The Fedora 32 host worked out fine with some minor DNS issues.

I guess it no longer makes sense to share this since the issue was prematurely closed but I get your pain with container providers and their underdeveloped /dev/kmsg FIFO implementations. Perhaps `journald` could handle such corrupted devices without hanging and the follow-up chain of effects but let's hope their own implementations will improve more in the future.

**Comment by poettering** [comment] 2020-07-15 16:55
> > What kind of container? Nspawn? Podman? Docker? Looks like a bug in that container manager. It provides a borked /dev/kmsg
> 
> It is a linux container (LXC) as I already mentioned above.

Hmm, you didn't mention LXC before, that's why I was asking.

> I guess it no longer makes sense to share this since the issue was prematurely closed but I get your pain with container providers and their underdeveloped /dev/kmsg FIFO implementations. Perhaps `journald` could handle such corrupted devices without hanging and the follow-up chain of effects but let's hope their own implementations will improve more in the future.

I am sorry, but we don't work around broken container managers. We document clearly what we expect from container managers so that things just work:

https://systemd.io/CONTAINER_INTERFACE

This list isn't crazy stuff, but just simple things. If container managers can't follow that list I am sorry, but we are not responsible, and we won't work around their borked stuff. /dev/kmsg is a kernel device with very specific semantics, and symlinking random crap to it is a call for trouble. I am not sure why they thought this ever made sense, but systemd is not the place to work around that.

Anyway, please raise this with LXC upstream if you want this to work. It's a bug in their code, not ours.

**Comment by pevogam** [comment] 2020-07-15 20:07
> > > What kind of container? Nspawn? Podman? Docker? Looks like a bug in that container manager. It provides a borked /dev/kmsg
> > 
> > 
> > It is a linux container (LXC) as I already mentioned above.
> 
> Hmm, you didn't mention LXC before, that's why I was asking.

LXC is abbreviated from linux containers but that's not important.

> I am sorry, but we don't work around broken container managers. We document clearly what we expect from container managers so that things just work:
> 
> https://systemd.io/CONTAINER_INTERFACE
> 
> This list isn't crazy stuff, but just simple things. If container managers can't follow that list I am sorry, but we are not responsible, and we won't work around their borked stuff. /dev/kmsg is a kernel device with very specific semantics, and symlinking random crap to it is a call for trouble. I am not sure why they thought this ever made sense, but systemd is not the place to work around that.

I only meant this as a potential remedy to reduce the need of extra debugging from journald hanging instead of it for instance bailing out with "something is wrong with your /dev/kmsg". Some developers that have to deal with problematic software would sometimes build additional validating fences like this in order to keep their dependencies in check. But I understand your viewpoint about better integrated systems with clearly documented requirements where everyone abides by the these. Since this is harder in practice though, I guess you don't mind adding more `not-our-bug` flags in time to compensate for it.

> Anyway, please raise this with LXC upstream if you want this to work. It's a bug in their code, not ours.

Sure sure, I would close this issue now but it is already closed so let's keep it that way.

**Comment by poettering** [comment] 2020-07-16 07:21
The problem is that POLLERR on /dev/kmsg has a meaning: that the kmsg log buffer has overrun and we missed some messages. And after a read() the POLLERR is reset according to kernel semantics. The way LXC sets this up also triggers POLLERR but it doesn't reset POLLERR on read(). That's a major incompatibility that is hard to detect. We see the event, react to it like kmsg API suggests, but on LXC when the event is seen something very different happened and would require something very different to react...
