### ISSUE TITLE
udev 240 prevented Electron-based app from working on WSL systems

### ISSUE THREAD

**Issue by tommyvct** [systemd/systemd#11385] opened 2019-01-10 17:25 UTC
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > WLinux, Kali Linux 2018.4 WSL

**Expected behaviour you didn't see**
 > Electron-based apps running perfectly with GUI comes up
 > Examples are but not limited to VSCode and Atom

**Unexpected behaviour you saw**
 > Electron-based apps hang and GUI never show up, left a dead process occupying 15MB of RAM,

**Steps to reproduce the problem**
1. Install Kali WSL on Windows 10
2. Follow [this](https://token2shell.com/howto/x410/running-xfce-desktop-on-kali-linux-wsl/) link to install xfce desktop. You can use others if you want.
3. upgrade your system, make sure you have systemd version of 240.
Version 239 works fine hence cannot reproduce the problem
4. Start your XServer and launch your xfce desktop.
5. Install VSCode. Try to launch it, and you will find nothing comes up.
if you 'top' or open Task Manager in Windows, you will see one or bunch of 'code' processes that each of these processes takes only around 15MB of RAM, depending how many times you tried to launch it.

Huge thanks to @khuongduybui , he find out that udev 240 is the problem,
https://github.com/WhitewaterFoundry/WLinux/issues/285

**Comment by mbiebl** [comment] 2019-01-10 18:34
probably a duplicate of https://github.com/systemd/systemd/issues/11293

**Comment by tommyvct** [comment] 2019-01-10 18:47
> probably a duplicate of #11293

Sorry for asking, but this is kind of too hardcore for a beginner like me, could you briefly explain why it is a duplicate?
I know Electron apps' frontend is powered by Chromium, and I do see 'Chromium sets DBUS_SESSION_BUS_ADDRESS to disabled', is that the problem?

**Comment by ssolidus** [comment] 2019-01-10 22:31
@tommyvct you should read the systemd 240 changelog. They modified the way systemd  handles dbus, which you should look up if you don't know what it is. Almost all modern apps use dbus, so many apps have broken as a result

**Comment by kirbyfan64** [comment] 2019-01-11 01:52
FWIW they've fixed it in master, so this can probably be closed?

**Comment by ssolidus** [comment] 2019-01-11 02:08
> 
> 
> FWIW they've fixed it in master, so this can probably be closed?

You should wait for the user to verify it is fixed for them.

**Comment by poettering** [comment] 2019-01-14 16:12
I am sorry, but this is not actionable for us. Please provide a precise description of the problem, with a proposed fix, otherwise there's little we can do. systemd is written with Linux in mind, not with Windows, and if you run systemd on it anyway, then it's really on the WSL people and you to provide bugfixes, as we upstream don't do Windows.

I'll close this now. I hope the above makes sense. if you can provide a precise bugfix, and explanation what you think systemd is doing wrong, by all means reopen and include this here, but otherwise there's no point in tracking this here, since it's clearly out of focus for us upstream to work on.

Sorry!

**Closed as completed by poettering** 2019-01-14 16:12 UTC
Labels: needs-reporter-feedback ❓

**Comment by tommyvct** [comment] 2019-01-17 15:14
I'm on Ubuntu 1810, and I cannot test whether the problem is solved if version 240 is not up on their source.
