### ISSUE TITLE
[dm-crypt with LUKS] error when unmounting on shutdown

### ISSUE THREAD

**Issue by vessd** [systemd/systemd#2351] opened 2016-01-18 07:08 UTC
Hello.
If I define my encrypted home partition by UUID in /etc/fstab then I get an error on shutdown.
If I login as root and unmount it manually, it will exit successful.
If I define it by /dev/mapper/_name_ it will unmount successful.

system: Archlinux current
systemd version: 228
/etc/crypttab:
`crypthome  UUID=952c4ccc-4225-434e-82fc-7d527e51f5e0  /etc/home.key  luks,timeout=180`
/etc/fstab:
`UUID=9d8ebe66-f799-4770-b387-d75b09e3aac2   /home  ext4 rw,relatime,data=ordered  0 2`
error:
`Arch systemd[1]: Stopped (with error) /dev/mapper/crypthome.`
boot log: http://pastebin.com/x0RGnitm
erros: http://pastebin.com/X1mp8iNb
Archlinux forum: [link](https://bbs.archlinux.org/viewtopic.php?pid=1596042#p1596042), [link](https://bbs.archlinux.org/viewtopic.php?id=205275)

**Comment by rumpelsepp** [comment] 2016-01-18 08:56
#1620

**Comment by kernelOfTruth** [comment] 2016-01-26 16:19
[not entirely sure if I experience the same issue]

@D101101 interesting find !

I also have the partitions added by UUID, albeit in /etc/crypttab

and the /dev/dm\* or /dev/mapper/\* entries time out during shutdown but it hangs there

it used to work in some cases under 4.3\* (or 4.2*) kernel, but currently with 4.4.0 it seemingly isn't able to shutdown on its own - using Magic SYSRQ only during off the harddrives and the PC has to be turned off via the power button (a regression ?)

Anyway, I'll try out to add it by partition name instead of UUID and see whether that makes a difference

Thanks

@rumpelsepp thanks for the reference,

will monitor that issue entry closely

**edit**:

referencing https://bugzilla.redhat.com/show_bug.cgi?id=1293184

it would be nice to have an option to let systemd ignore the timeout of the device-mapper/dm entries during shutdown

not sure what the problem is here since with openrc there was never such an issue

**Comment by poettering** [comment] 2016-04-18 17:02
As @rumpelsepp suggested this indeed appears to be a duplicate of #1620. Closing this one in favour of that.

**Closed as completed by poettering** 2016-04-18 17:02 UTC
Labels: cryptsetup, duplicate
