### ISSUE TITLE
loginctl enable linger breaks systemctl --user

### ISSUE THREAD

**Issue by uzytkownik** [systemd/systemd#4229] opened 2016-09-28 00:12 UTC
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 231
### Used distribution

> Gentoo
### In case of bug report: Expected behaviour you didn't see

> `systemctl --user` work and have `systemd --user` enable after boot
### In case of bug report: Unexpected behaviour you saw

> `systemd --user` refused to start at all because it tried to remove `init.scope`. It breaks dbus and `systemctl --user`
### In case of bug report: Steps to reproduce the problem

> ```
> loginctl enable-linger user
> systemctl reboot
> systemctl --user
> ```

**Comment by poettering** [comment] 2016-10-07 13:34
> systemd --user refused to start at all because it tried to remove init.scope.

What's that supposed to mean? Can you elaborate on this?

Can you provide the logs/error messages related to this condition? Thanks!

**Comment by uzytkownik** [comment] 2016-10-07 16:30
There weren't really any error messages other then `systemctl --user` failing to connect to dbus (I was watching by `journalctl -f` when logging in to see PAM errors). Even running `systemd` by hand didn't produce any log.

I needed to run `strace` and see that it tries to remove `init.scope` cgroup which was owned by root (I am unfamiliar with cgroup subsystem but even root could not remove it). I'm not sure if that was a cause of failure but it was last failing syscall.

**Comment by poettering** [comment] 2016-10-07 16:32
well, do you see dbus-daemon running for the user?

**Comment by uzytkownik** [comment] 2016-10-07 19:21
No, dbus-daemon is not running in both cases other then system instance:

```
% ps `pgrep dbus`
  PID TTY      STAT   TIME COMMAND
  795 ?        Ss     0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
```

**Comment by akostadinov** [comment] 2018-01-06 13:57
I can't reproduce on fedora 27. 
```
$ systemctl --version
systemd 234
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid
```

**Comment by techtonik** [comment] 2018-11-27 19:19
To repeat this report, this needs original `.service` file to read its `[Install]` section, then the `systemctl` command used to install it and enable, as well as location where the file is present and where symlinks are created.

The bug with missing XDG_RUNTIME_DIR needs a separate issue. `loginctl` can not break it, because it is already broken before `loginctl`.

**Comment by poettering** [comment] 2018-11-27 19:22
the xdg-runtime-dir thing has been fixed by a9f0f5e50104fc5cc511aa10007f7f8b8366fed8. Closing hence.

**Closed as completed by poettering** 2018-11-27 19:22 UTC
Labels: needs-reporter-feedback ❓

**Comment by techtonik** [comment] 2018-11-28 07:04
Any hints how to get this backported to Ubuntu 16.04?

**Comment by kirk86** [comment] 2024-03-29 11:05
Is there any updates on this? I'm having similar issues on debian 11 with systemd 247.
Basically after enabling lingering with `loginctl enable-linger $USER`.
Upon inspection there's a file created at `ls /var/lib/systemd/linger` with the `username`.
Now after rebooting whenever I try to issue `systemctl --user status` I get the following error
```
Failed to read server status: Process org.freedesktop.systemd1 exited with status 1
```
Executing `systemctl status` I can see that the the `State: degraded` and `Failed: 2 units`

Running `loginctl disable-linger $USER` results in the following error `Could not enable linger: Resource temporarily unavailable`

How to get out of this mess? 

I can't delete the file in `/var/lib/systemd/linger/username` cause I don't have admin rights on the system only regular user rights, hence no sudo available?
