### ISSUE TITLE
Allow scheduling timer units for when the system is idle

### ISSUE THREAD

**Issue by strugee** [systemd/systemd#21569] opened 2021-11-30 00:26 UTC
**Is your feature request related to a problem? Please describe.**

I'd like to run certain jobs when the computer is expected to be idle. For example, on ostree systems, it might be a good idea to run `ostree fsck` on a regular basis, or I might want to configure my APT system to automatically download updates. Neither of these things should be done automatically while I'm using the computer, though, because I don't want them taking up CPU time or disk I/O when I'm interacting with the machine.

**Describe the solution you'd like**

A notion of system idle time, and accompanying timer directive to specify running timers during idle time.

Specifically, for "system idle time", I'm proposing a directive in `/etc/systemd/system.conf` that controls the "idle mode". I'm imagining that this would be one of `fixed` (define a range of time where the system is idle), `historical` (systemd records over time the times where the system tends to have low activity), or `runtime` (watch at runtime for system load to become low and run things then). Feel free to bikeshed the names, they're not the greatest :P

The timer directive would then basically be a way to hook into this notion of idle time. `OnIdle=` or something like that.

It's unclear to me if idle mode should take into account when the computer is sleeping. Maybe `historical` would prefer times where the computer tended to be asleep?

**Describe alternatives you've considered**

You could simply set this kind of job to run sometime during the night, but now you're guessing when the user isn't using the computer - this may not be true for people who work during the night and it also might not be true for people whose timezones aren't set correctly.

**The systemd version you checked that didn't have the feature you are asking for**

249 (Fedora Silverblue)

**Comment by bluca** [comment] 2021-11-30 01:14
Duplicate of https://github.com/systemd/systemd/issues/20139

**Closed as completed by bluca** 2021-11-30 01:14 UTC
Labels: duplicate
