### ISSUE TITLE
user@.service: Trying to run as user instance, but $XDG_RUNTIME_DIR is not set.

### ISSUE THREAD

**Issue by gclawes** [systemd/systemd#10574] opened 2018-10-30 12:33 UTC
**systemd version the issue has been seen with**
> 239-r2

**Used distribution**
 > gentoo

**Expected behaviour you didn't see**
 > user@UID.service started at user login

**Unexpected behaviour you saw**
 > Error reported in log: `Oct 29 17:49:41 enterprise.lan systemd[17543]: Trying to run as user instance, but $XDG_RUNTIME_DIR is not set.`

Similar to issue https://github.com/systemd/systemd/issues/232

Full log output:
```
Oct 29 17:49:41 enterprise.lan systemd[1]: Created slice User Slice of UID 1000.
-- Subject: Unit user-1000.slice has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit user-1000.slice has finished starting up.
--
-- The start-up result is RESULT.
Oct 29 17:49:41 enterprise.lan systemd[1]: Created slice system-user\x2druntime\x2ddir.slice.
-- Subject: Unit system-user\x2druntime\x2ddir.slice has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit system-user\x2druntime\x2ddir.slice has finished starting up.
--
-- The start-up result is RESULT.
Oct 29 17:49:41 enterprise.lan systemd[1]: Started /run/user/1000 mount wrapper.
-- Subject: Unit user-runtime-dir@1000.service has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit user-runtime-dir@1000.service has finished starting up.
--
-- The start-up result is RESULT.
Oct 29 17:49:41 enterprise.lan systemd[1]: Starting User Manager for UID 1000...
-- Subject: Unit user@1000.service has begun start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit user@1000.service has begun starting up.
Oct 29 17:49:41 enterprise.lan systemd[17543]: pam_unix(systemd-user:session): session opened for user gclawes by (uid=0)
Oct 29 17:49:41 enterprise.lan systemd[17543]: Trying to run as user instance, but $XDG_RUNTIME_DIR is not set.
Oct 29 17:49:41 enterprise.lan systemd[1]: user@1000.service: Failed with result 'protocol'.
Oct 29 17:49:41 enterprise.lan systemd[1]: Failed to start User Manager for UID 1000.
-- Subject: Unit user@1000.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit user@1000.service has failed.
--
-- The result is RESULT.
Oct 29 17:49:41 enterprise.lan systemd[1]: user-runtime-dir@1000.service: Unit not needed anymore. Stopping.
Oct 29 17:49:41 enterprise.lan systemd[1]: Stopping /run/user/1000 mount wrapper...
-- Subject: Unit user-runtime-dir@1000.service has begun shutting down
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit user-runtime-dir@1000.service has begun shutting down.
Oct 29 17:49:41 enterprise.lan systemd[1]: Stopped /run/user/1000 mount wrapper.
-- Subject: Unit user-runtime-dir@1000.service has finished shutting down
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit user-runtime-dir@1000.service has finished shutting down.
```

With `ExecStartPre=/bin/cat /run/systemd/users/%i` added to `user@.service`:

```
-- Unit user@1000.service has begun starting up.
Oct 29 18:16:48 enterprise.lan systemd[1]: Started /run/user/1000 mount wrapper.
Oct 29 18:16:48 enterprise.lan systemd[12809]: pam_unix(systemd-user:session): session opened for user gclawes by (uid=0)
Oct 29 18:16:48 enterprise.lan cat[12809]: /bin/cat: /run/systemd/users/1000: No such file or directory
Oct 29 18:16:48 enterprise.lan systemd[12810]: pam_unix(systemd-user:session): session closed for user gclawes
Oct 29 18:16:48 enterprise.lan systemd[1]: user@1000.service: Control process exited, code=exited status=1
Oct 29 18:16:48 enterprise.lan systemd[1]: user@1000.service: Failed with result 'exit-code'.
Oct 29 18:16:48 enterprise.lan systemd[1]: Failed to start User Manager for UID 1000.
-- Subject: Unit user@1000.service has failed
```

**Steps to reproduce the problem**
`systemctl start user@UID && journalctl -xe`

**Comment by poettering** [comment] 2018-10-30 13:57
Is pam_systemd correctly part of your PAM stacks?

**Comment by gclawes** [comment] 2018-10-30 14:03
Yes:

```
enterprise ~ # cat /etc/pam.d/systemd-user
# This file is part of systemd.
#
# Used by systemd --user instances.

account include system-auth
session include system-auth
session optional pam_keyinit.so force revoke
session optional pam_systemd.so
```
```
enterprise ~ # cat /etc/pam.d/system-auth
auth            required        pam_env.so
auth            required        pam_unix.so try_first_pass likeauth
auth            optional        pam_permit.so
account         required        pam_unix.so
account         optional        pam_permit.so
password        required        pam_cracklib.so difok=2 minlen=8 dcredit=2 ocredit=2 retry=3
password        required        pam_unix.so try_first_pass use_authtok  sha512 shadow
password        optional        pam_permit.so
session         required        pam_limits.so
session         required        pam_env.so
session         required        pam_unix.so
session         optional        pam_permit.so
-session        optional        pam_systemd.so
```

**Comment by poettering** [comment] 2018-10-30 14:20
hmm, with the above you'd actually have pam_systemd twice in your stack though?

if you log in on a getty or so, do you get $XDG_RUNTIME_DIR properly set?

**Comment by floppym** [comment] 2018-10-30 14:42
In case it is helpful, Gentoo's systemd-239-r2 corresponds to this branch.

https://github.com/gentoo/systemd/commits/gentoo-239

**Comment by floppym** [comment] 2018-10-30 14:55
Also, I am unable to reproduce the problem.

**Comment by gclawes** [comment] 2018-10-31 03:20
`$XDG_RUNTIME_DIR` isn't present in the environment both in SSH and getty:
```
$ ssh enterprise
gclawes@enterprise ~ $ env | grep XDG_RUNTIME_DIR
gclawes@enterprise ~ $
Connection to enterprise closed.
```

![img_20181030_231732](https://user-images.githubusercontent.com/172517/47764158-5b526180-dc9a-11e8-9843-14dc5fb91c24.jpg)

**Comment by poettering** [comment] 2018-10-31 09:00
this suggests you don't have pam_systemd or logind installed and enabled. At this point, this really feels like a local issue with your installation/distro, and that pam_systemd is not properly hooked into the pam stacks of your various pam services, including getty.

the pam_systemd session hook should appear exactly once in each 'session' stack for the relevant services. Consider adding "debug" as argument to the pam_systemd item in the stack. If you do then pam_systemd will log a bit about when it initializes and so on.

@floppym btw, if the pam snippets @gclawes pasted are correct and the default ones gentoo ships then there's definitely something wrong with them as that means the module is pulled in twice for "systemd-user", and it really shouldn't be.

**Comment by gclawes** [comment] 2018-10-31 11:54
I commented out `-sesssion` line (not sure why the `-` is there) in `/etc/pam.d/system-auth`, which just left the `pam_systemd.so` entry in `systemd-user`, and this was the result:

```
-- Unit user@1000.service has begun starting up.
Oct 31 07:50:25 enterprise.lan systemd[7416]: PAM unable to dlopen(/usr/lib64/security/pam_systemd.so): /usr/lib64/security/pam_systemd.so: cannot open shared object file: No such file or directory
Oct 31 07:50:25 enterprise.lan systemd[7416]: PAM adding faulty module: /usr/lib64/security/pam_systemd.so
Oct 31 07:50:25 enterprise.lan systemd[7416]: pam_unix(systemd-user:session): session opened for user gclawes by (uid=0)
Oct 31 07:50:25 enterprise.lan systemd[7416]: Trying to run as user instance, but $XDG_RUNTIME_DIR is not set.
Oct 31 07:50:25 enterprise.lan systemd[7417]: pam_unix(systemd-user:session): session closed for user gclawes
Oct 31 07:50:25 enterprise.lan systemd[1]: user@1000.service: Failed with result 'protocol'.
Oct 31 07:50:25 enterprise.lan systemd[1]: Failed to start User Manager for UID 1000.
-- Subject: Unit user@1000.service has failed
```

`pam_systemd.so` is present in `/lib64/security/pam_systemd.so`, not `/usr/lib64/security/pam_systemd.so`.

I get the same result changing `-session` to `session` in `/etc/pam.d/system-auth` as well.  In both cases, copying `pam_systemd.so` to `/usr/lib64/security/pam_systemd.so` allows the `user@.service` to start manually correctly via `systemctl`.

**Comment by poettering** [comment] 2018-10-31 12:15
Ok, appears to be a gentoo packaging issue, let's close this here then.

**Closed as completed by poettering** 2018-10-31 12:15 UTC
Labels: not-our-bug

**Comment by floppym** [comment] 2018-10-31 14:08
@gclawes PAM modules are supposed to be loaded from `/lib64/security` on Gentoo. Something is wrong with PAM on your system.

**Comment by gclawes** [comment] 2018-10-31 14:53
I uninstalled/reinstalled `sys-libs/pam` and ran `systemctl daemon-reexec`, that seems to have cleared it up.  If I can figure out how pam got into that state I'll submit a bug to gentoo.  Thanks for the time and attention on this.

**Comment by gclawes** [comment] 2018-10-31 16:18
Ah, yeah, I think that's it.  Thanks!

**Comment by KayARS** [comment] 2023-08-25 10:35
I've noticed the same error on my side, and it seems like I have pam-1.3.1-4.el8.i686 and there seems to be no newer version of this.
Is a reinstall needed? Together with reexec?
Or is this a new problem?
