### ISSUE TITLE
systemd-boot hangs if YubiKey is present

### ISSUE THREAD

**Issue by nmaggioni** [systemd/systemd#15847] opened 2020-05-19 14:03 UTC
**systemd version the issue has been seen with**
> systemd 245 (245.5-2-manjaro)

**Used distribution**
 > Manjaro 20.0.1

**Expected behaviour you didn't see**
 > Boot screen interactivity and regular progress.

**Unexpected behaviour you saw**

 If a YubiKey is (already) connected at boot time, systemd-boot hangs. If a timeout is set, the menu is shown but the counter immediately freezes; if a timeout isn't set, the screen stays blank. In both cases the system can't be interacted with apart from forcibly powering it off.

**Steps to reproduce the problem**

1. Boot with a YubiKey in an USB port.
2. The system hangs at systemd-boot's menu.

I can reproduce this behavior with both a YK 4 Nano (`1050:0407`) and a YK Neo (`1050:0116`). Different ports and/or hubs do not seem to be affecting the result; I don't have other devices causing this issue at hand.

---

<details><summary>/boot/loader/loader.conf</summary>

```
timeout 3
console-mode keep
default manjarolinux5.6
```
</details>

<details><summary>/etc/fstab</summary>

```
# /dev/mapper/cryptroot
UUID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx	/         	ext4      	rw,noatime	0 0
# /dev/nvme0n1p1
UUID=xxxx-xxxx      	/boot     	vfat      	rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro	0 0
/swapfile       	none      	swap      	defaults,pri=-2	0 0
```
</details>

<details><summary>Hardware</summary>

```
$ inxi -M
Machine:   Type: Convertible System: HP product: HP Spectre x360 Convertible 13-aw0xxx v: N/A serial: <filter> 
           Mobo: HP model: 86FA v: 87.46 serial: <filter> UEFI: AMI v: F.13 date: 03/02/2020

$ dmidecode
// ...
Handle 0x0000, DMI type 0, 26 bytes
BIOS Information
        Vendor: AMI
        Version: F.13
        Release Date: 03/02/2020
        Address: 0xF0000
        Runtime Size: 64 kB
        ROM Size: 12288 kB
        Characteristics:
                PCI is supported
                BIOS is upgradeable
                BIOS shadowing is allowed
                Boot from CD is supported
                Selectable boot is supported
                EDD is supported
                5.25"/1.2 MB floppy services are supported (int 13h)
                3.5"/720 kB floppy services are supported (int 13h)
                3.5"/2.88 MB floppy services are supported (int 13h)
                Print screen service is supported (int 5h)
                8042 keyboard services are supported (int 9h)
                Serial services are supported (int 14h)
                Printer services are supported (int 17h)
                ACPI is supported
                USB legacy is supported
                Smart battery is supported
                BIOS boot specification is supported
                Function key-initiated network boot is supported
                Targeted content distribution is supported
                UEFI is supported
        BIOS Revision: 15.13
        Firmware Revision: 87.46
// ...
```
</details>

**Comment by poettering** [comment] 2020-05-19 14:15
hmm, so i doubt there#s anything we can do about that. usb drivers for keyboards and stuff are handled inside the firmware. Is this reproducible on other systems? Have you tried updating your firmware?

**Comment by nmaggioni** [comment] 2020-05-19 14:38
Unfortunately I don't have any other system that I can equip with the same sw stack, and I've already updated my BIOS to the most recent version publicly available. Live mediums using GRUB seem to be booting fine though.

**Comment by avargaskun** [comment] 2021-05-28 02:49
FYI - I have the same problem with `systemd 245 (245.4-4ubuntu3.6)` on an HP Spectre 14-ea0023dx

**Comment by mschubert** [comment] 2021-07-20 09:36
Same issue with `systemd 249-3` on an HP Spectre 15-df0xxx (Arch) with an external keyboard connected

**Comment by nmaggioni** [comment] 2021-07-20 10:19
Something is definitely off in the way HP's firmware handles USB devices but their customer support hasn't been willing to acknowledge that so far.

**Comment by medhefgo** [comment] 2021-07-22 13:14
Does this branch fix this?
https://github.com/medhefgo/systemd/tree/boot

**Comment by eliadevito** [comment] 2021-07-22 18:26
> Does this branch fix this?
> https://github.com/medhefgo/systemd/tree/boot

Hi, I have tested this patch and it doesn't fix the problem.

this https://github.com/eliadevito/systemd/commit/0e3aafc5b9c2f64ae37db4c1615ef1370ec54251 has fixed the probnlem on my HP Spectre 15-df0xxx
from what I understand it looks like sd-boot freeze on this line 

`err  = uefi_call_wrapper(ST->ConIn->ReadKeyStroke, 2, ST->ConIn, &k);`

removing it fix the freeze but the arrow keys doesn't work correctly.

The solution should instead be here:

on boot.c insdie efi_main() function we have this 
```

err = console_key_read(&key, FALSE);

if (err == EFI_NOT_READY) {
        uefi_call_wrapper(BS->Stall, 1, 100 * 1000);
        err = console_key_read(&key, FALSE);
}
```
 
IMO the uefi_call_wrapper(ST->ConIn->ReadKeyStroke, 2, ST->ConIn, &k) call should be return EFI_NOT_READY 
until firmware not ready instead it causes the system to freeze, differently the uefi_call_wrapper(TextInputEx->ReadKeyStrokeEx, 2, TextInputEx, &keydata) call seem to return it (I suppose) in fact by adding the return in case of error sd-boot don't freeze anymore and work very well with or without an external keyboard connected.

The only thing is that only the notebook's built-in keyboard works and not the external one but it shouldn't be such a big problem.

I have tested this on Fedora 34, if someone want to test it I have created a copr repository with patched systemd
https://copr.fedorainfracloud.org/coprs/scorpionit/systemd_HP/

**Comment by medhefgo** [comment] 2021-07-23 10:46
I've reworked my branch. Does it work for you with that?

**Comment by eliadevito** [comment] 2021-07-23 14:41
> I've reworked my branch. Does it work for you with that?

I have tested your reworked branch and unfortunately  it doesn't work,

`if (TextInputEx && !EFI_ERROR(uefi_call_wrapper(BS->CheckEvent, 1, TextInputEx->WaitForKeyEx))) {`

this conditions is always false when you call console key_read with wait variable setted to false and don't press any key causing the fallback code to execute witch consequently firmware hang

**Comment by medhefgo** [comment] 2021-07-23 15:29
Am I getting this right: with wait set to true this code works?

**Comment by eliadevito** [comment] 2021-07-23 16:09
> Am I getting this right: with wait set to true this code works?

Yes, if I force wait variable to true it works

**Comment by medhefgo** [comment] 2021-07-23 16:14
Perfect! I've updated my branch which sidesteps the whole issue. It *should* work.

**Comment by medhefgo** [comment] 2021-07-23 16:21
Also, if you force wait to true and force using ConIn instead of TextInputEx, does that also work?

**Comment by eliadevito** [comment] 2021-07-23 17:20
> Perfect! I've updated my branch which sidesteps the whole issue. It _should_ work.

With these latest changes, no hang at all.
The only remain bug is for print_status(SHIFT+P) that don't wait to press a key to continue, but this should be solved by disabling the timer when the wait variable is true (I assume).

> Also, if you force wait to true and force using ConIn instead of TextInputEx, does that also work?

No, the ConnIn cause hang in all case

Can you please add a fix for print_status() an submit this as PR?

Thanks a lot for you work, good job.

**Comment by medhefgo** [comment] 2021-07-23 17:24
I'll make a PR with a ton of other sd-boot goodies containing a fix for this in the next week or two.

**Comment by medhefgo** [comment] 2021-07-30 14:24
Please double check that it works with my PR.

**Closed as completed** 2021-08-13 07:22 UTC
Labels: sd-boot/sd-stub/bootctl

**Comment by medhefgo** [comment] 2021-08-30 16:05
One last thing: could you slap this line at the top of console_key_read() of the latest git main and tell me if any of them say no at runtime? I feel like your firmware might be giving us null pointers here.

`log_error_stall(L"ConIn: %s\nConInHandle: %s\nReadKeyStroke: %s\nWaitForKey: %s", yes_no(!!ST->ConIn), yes_no(!!ST->ConsoleInHandle), yes_no(!!ST->ConIn && !!ST->ConIn->ReadKeyStroke), yes_no(!!ST->ConIn && !!ST->ConIn->WaitForKey));`
