### ISSUE TITLE
systemd.network Name=enp* matches eno*

### ISSUE THREAD

**Issue by drws** [systemd/systemd#32629] opened 2024-05-02 13:24 UTC
### systemd version the issue has been seen with

255.5

### Used distribution

Arch

### Linux kernel version used

6.8.8-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

The system has two ordinary Ethernet interfaces `eno1` and `enp2s0`. The following `.network` file should match `enp2s0`, but not `eno1`.

```
[Match]
Type=ether
Name=enp*
```

### Unexpected behaviour you saw

In practice _both_ interfaces are matched, but this seems to work:

```
[Match]
Type=ether
Name=enp2*
```

**Comment by poettering** [comment] 2024-05-06 11:05
This is not reproducible here. Are you sure you actually reloaded netwokrd properly, after editing those files? What does "networkctl status" actually show on the relevant file?

**Comment by drws** [comment] 2024-05-06 16:26
There were definitely 2 or 3 reboots inbetween testing, besides `daemon-reload`-ing and networkd service too, so it should be good. But the `networkctl status` reveals the interface has an _alternative name_ in the enp0* range so there's that. Reading systemd.network manpage now even more carefully it is mentioned that `Name` matches alternative names as well. But the `networkctl` manpage seems to not offer any additional explanation about alternative names it is displaying. And the system in-question doesn't have any special configuration regarding interface (re)naming.

So the questions seem to be which of the two names is alias, where is it created and can eno* even be matched exclusively with current `Name` directive behavior?

**Comment by yuwata** [comment] 2024-05-06 18:09
Alternative names are configured based on .link file, typically 99-default.link. And as the man page stated, both the main and alternative names can match the Name= in .network file.

This is not a bug, and well documented. Closing.

**Closed as not planned by yuwata** 2024-05-06 18:09 UTC
Labels: network, not-a-bug

**Comment by yuwata** [comment] 2024-05-06 18:12
Of course, suggestion about further document improvement is always welcome.
But the behavior itself is expected.
