### ISSUE TITLE
systemd-networkd replaced my firewall?

### ISSUE THREAD

**Issue by pomac303** [systemd/systemd#30257] opened 2023-11-29 21:27 UTC
### systemd version the issue has been seen with

254.5

### Used distribution

Gentoo

### Linux kernel version used

6.6.3

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

My machine booting up as normal, using my firewall config

### Unexpected behaviour you saw

My firewall being replaced with:
```
$ nft list tables
table ip io.systemd.nat
table ip6 io.systemd.nat

$ nft list table ip io.systemd.nat
table ip io.systemd.nat {
	set masq_saddr {
		type ipv4_addr
		flags interval
		elements = { 10.0.0.0/24 }
	}

	map map_port_ipport {
		type inet_proto . inet_service : ipv4_addr . inet_service
	}

	chain prerouting {
		type nat hook prerouting priority dstnat + 1; policy accept;
		fib daddr type local dnat ip to meta l4proto . th dport map @map_port_ipport
	}

	chain output {
		type nat hook output priority dstnat + 1; policy accept;
		ip daddr != 127.0.0.0/8 oif "lo" dnat ip to meta l4proto . th dport map @map_port_ipport
	}

	chain postrouting {
		type nat hook postrouting priority srcnat + 1; policy accept;
		ip saddr @masq_saddr masquerade
	}
}
```
And instead of my:
```
$ nft list tables
table inet filter
table ip nat
```
Also, why separate ipv4 and ipv6 when inet should be enough?

**Comment by pomac303** [comment] 2023-11-29 21:28
Forgot, I have been looking for a way of disabling it and not found anything...

**Comment by yuwata** [comment] 2023-11-30 00:00
cc @fbuihuu

**Comment by mrc0mmand** [comment] 2023-12-04 12:45
Also cc @fw-strlen as the author of 715a70e7218710d6a6c033e9157bf97fdf5d8ede.

**Comment by topimiettinen** [comment] 2023-12-04 19:45
I think the problem is that `fw_ctx_new()` [here](https://github.com/systemd/systemd/blob/26522a66a312b5b8cb6c4ad123569ae22731762b/src/network/networkd-address.c#L648) adds the firewall rules. I'll prepare a PR to change that to `fw_ctx_new_full(, false)` after a few tests.

> cc @topimiettinen

I don't think I got a notification of the edited comment (or I missed it), only when @mrc0mmand added a new message.

**Comment by yuwata** [comment] 2023-12-06 07:21
Hm, I tried to add test case for #30318, but I cannot reproduce the issue.
networkd adds unexpected table (that should be solved by #30318), but rules added by firewalld do not removed/replaced.

```
$ sudo nft list tables
table ip io.systemd.nat
table ip6 io.systemd.nat
table inet firewalld

$ sudo nft list table ip io.systemd.nat
table ip io.systemd.nat {
	set masq_saddr {
		type ipv4_addr
		flags interval
	}

	map map_port_ipport {
		type inet_proto . inet_service : ipv4_addr . inet_service
	}

	chain prerouting {
		type nat hook prerouting priority dstnat + 1; policy accept;
		fib daddr type local dnat ip to meta l4proto . th dport map @map_port_ipport
	}

	chain output {
		type nat hook output priority -99; policy accept;
		ip daddr != 127.0.0.0/8 oif "lo" dnat ip to meta l4proto . th dport map @map_port_ipport
	}

	chain postrouting {
		type nat hook postrouting priority srcnat + 1; policy accept;
		ip saddr @masq_saddr masquerade
	}
}

$ sudo nft list table ip6 io.systemd.nat
table ip6 io.systemd.nat {
	set masq_saddr {
		type ipv6_addr
		flags interval
	}

	map map_port_ipport {
		type inet_proto . inet_service : ipv6_addr . inet_service
	}

	chain prerouting {
		type nat hook prerouting priority dstnat + 1; policy accept;
		fib daddr type local dnat ip6 to meta l4proto . th dport map @map_port_ipport
	}

	chain output {
		type nat hook output priority -99; policy accept;
		ip6 daddr != ::1 oif "lo" dnat ip6 to meta l4proto . th dport map @map_port_ipport
	}

	chain postrouting {
		type nat hook postrouting priority srcnat + 1; policy accept;
		ip6 saddr @masq_saddr masquerade
	}
}

$ sudo nft list table inet firewalld
table inet firewalld {
	chain mangle_PREROUTING {
		type filter hook prerouting priority mangle + 10; policy accept;
		jump mangle_PREROUTING_ZONES
	}
(snip)
}

$ sudo systemctl restart systemd-networkd.service

$ sudo nft list tables
table ip io.systemd.nat
table ip6 io.systemd.nat
table inet firewalld

$ sudo nft list table inet firewalld
table inet firewalld {
	chain mangle_PREROUTING {
		type filter hook prerouting priority mangle + 10; policy accept;
		jump mangle_PREROUTING_ZONES
	}
(snip)
}
```

@pomac303 Could you provide more explicit reproducer for the issue?

**Comment by pomac303** [comment] 2023-12-06 11:36
I noticed that the rc.local script i use stopped once (ie, didn't actually return), i haven't been able to reproduce it though... 

It might be that you've fixed the whole bug, and the rest was a side effect of something going wonky with ethtool or so

**Comment by yuwata** [comment] 2023-12-06 11:42
> the rest was a side effect of something going wonky with ethtool or so

Cannot follow. But, I guess that's unrelated to this. Closing.

Feel free to open a new issue if you have a trouble.

**Closed as completed by yuwata** 2023-12-06 11:42 UTC
Labels: bug 🐛, network, regression ⚠️

**Comment by HanabishiRecca** [comment] 2023-12-10 12:01
I guess there is no way to tell systemd to not touch the firewall whatsoever?

**Comment by yuwata** [comment] 2023-12-10 12:09
With #30318, networkd should not touch nftables unless requested.

**Comment by HanabishiRecca** [comment] 2023-12-10 12:23
I see, but I double checked network interfaces, no forwarding or masquerading is configured anywhere.

Setting
```service
IPForward=no
IPMasquerade=no
```
does not help either. (Fairly expected though, those options are disabled by default.)

Do you know any other places where it can be "requested"?

**Comment by YHNdnzj** [comment] 2023-12-10 12:27
@HanabishiRecca The commit is not in stable release (yet).

**Comment by HanabishiRecca** [comment] 2023-12-10 12:30
Oh, I didn't noticed v256 milestone. Thank you.

**Comment by yuwata** [comment] 2023-12-10 12:31
@HanabishiRecca If you observe the issue with the mentioned PR, please open a new issue.

**Comment by HanabishiRecca** [comment] 2023-12-10 12:52
Already tested it and this PR solves the issue. Sorry again for me beind blind.

I will suggest to backport this commit for downstream Arch Linux package.
