### ISSUE TITLE
localed can easily be fooled if vconsole.conf was edited manually

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#5221] opened 2017-02-03 16:09 UTC
Hi,

localed can be fooled with:

```
> $ localectl set-keymap fr
> $ sleep 30 # wait for the exit-on-idle timeout
> $ echo "KEYMAP=us" >/etc/vconsole.conf
> $ localectl set-keymap us
```

During the last call to localectl, localed thinks that the keymap is already 'us' (it reads it from vconsole.conf) and doesn't update the keymap for the console nor update /etc/X11/xorg.conf.d/00-keyboard.conf.

Relying on the content of vconsole.conf doesnt seem to be a good idea: it also can be fooled by running 'loadkeys' directly.

Is it a valid use case as vconsole.conf man page doesn't forbid to edit the config file manually ?

**Comment by poettering** [comment] 2017-02-03 16:59
well, if you make your changes yourself, you have to live with that, you don't get the bells and whistles... 

It's totally fine to edit the file yourself, but of course, you won't get the nice automatic behaviour then, but that's really what you asked for.

This is intended behaviour really: the service is little more than a frontend that does a few things for you at once, that you otherwise have to do manually. If you choose not to use it, great, but then of course you need to do them manually.

Closing hence, as this bheaviour is perfeclty in line with what this is supposed to be. I hope that makes sense...

**Closed as completed by poettering** 2017-02-03 16:59 UTC
Labels: not-a-bug, vconsole
