### ISSUE TITLE
ethtool invocation in udev for RxBufferSize= runs too early(?) for some cards

### ISSUE THREAD

**Issue by nabijaczleweli** [systemd/systemd#28696] opened 2023-08-06 14:55 UTC
### systemd version the issue has been seen with

254~rc3-3

### Used distribution

debian sid

### Linux kernel version used

6.3.0-2-amd64

### CPU architectures issue was seen on

x32

### Component

systemd-networkd

### Expected behaviour you didn't see

`RxBufferSize=` is honoured like when running ethtool manually

### Unexpected behaviour you saw

isn't

### Steps to reproduce the problem

1. have a tg3 Tigon3 [partno(BCM95720) rev 5720000] card
2. set `RxBufferSize=1023` in the .link file

### Additional program output to the terminal or log subsystem illustrating the issue

Full config:

```
==> 00-onboard1.link <==
[Match]
MACAddress=78:e3:12:34:56:fd

[Link]
Name=onboard1
RxBufferSize=511
TxBufferSize=511

==> 01-onboard1-just-up.network <==
[Match]
Name=onboard1

[Link]
Unmanaged=yes

==> 10-bond1-local.netdev <==
[NetDev]
Name=bond1
Kind=bond
MACAddress=00:0a:12:34:56:12

[Bond]
Mode=balance-alb
TransmitHashPolicy=layer3+4
MIIMonitorSec=1s
# LACPTransmitRate=fast

==> 11-bond1-local.network <==
[Match]
Name=bond1

[Link]
MTUBytes=9000

[Network]
Address=192.168.1.1/24
#Gateway=192.168.1.1
DNS=127.0.0.1
DNS=192.168.1.250
NTP=192.168.1.250

#[Address]
#Address=10.0.0.1/24

==> 20-card1.link <==
[Match]
MACAddress=00:0a:12:34:56:10

[Link]
Name=card1
RxBufferSize=2047
RxJumboBufferSize=1023
TxBufferSize=511

==> 21-card2.link <==
[Match]
MACAddress=00:0a:12:34:56:11

[Link]
Name=card2
RxBufferSize=2047
RxJumboBufferSize=1023
TxBufferSize=511

==> 22-card*-bond1-local.network <==
[Match]
Name=card*

[Link]
RequiredForOnline=false
MTUBytes=9000

[Network]
Bond=bond1
```

journal:
```
$ journalctl -b | grep 'card[12]'
Aug 06 14:49:35 szarotka kernel: tg3 0000:20:00.1 card2: renamed from eth1
Aug 06 14:49:35 szarotka kernel: tg3 0000:20:00.0 card1: renamed from eth0
Aug 06 14:49:35 szarotka kernel: bond1: (slave card1): Enslaving as an active interface with a down link
Aug 06 14:49:35 szarotka kernel: bond1: (slave card2): Enslaving as an active interface with a down link
Aug 06 14:49:35 szarotka kernel: tg3 0000:20:00.0 card1: Link is up at 1000 Mbps, full duplex
Aug 06 14:49:35 szarotka kernel: tg3 0000:20:00.0 card1: Flow control is on for TX and on for RX
Aug 06 14:49:35 szarotka kernel: tg3 0000:20:00.0 card1: EEE is enabled
Aug 06 14:49:35 szarotka kernel: tg3 0000:20:00.1 card2: Link is up at 1000 Mbps, full duplex
Aug 06 14:49:35 szarotka kernel: tg3 0000:20:00.1 card2: Flow control is on for TX and on for RX
Aug 06 14:49:35 szarotka kernel: tg3 0000:20:00.1 card2: EEE is enabled
Aug 06 14:49:35 szarotka kernel: bond1: (slave card1): link status definitely up, 1000 Mbps full duplex
Aug 06 14:49:35 szarotka kernel: bond1: (slave card2): link status definitely up, 1000 Mbps full duplex
Aug 06 14:49:35 szarotka kernel: bond1: (slave card1): making interface the new active one
Aug 06 14:49:24 szarotka (udev-worker)[403]: card1: Process '/sbin/ethtool -G card1 rx-jumbo 1023' failed with exit code 81.
Aug 06 14:49:24 szarotka (udev-worker)[417]: card2: Process '/sbin/ethtool -G card2 rx-jumbo 1023' failed with exit code 81.
Aug 06 14:49:24 szarotka (udev-worker)[401]: card2: Process '/sbin/ethtool -G card2 rx-jumbo 1023' failed with exit code 81.
Aug 06 14:49:24 szarotka (udev-worker)[397]: card1: Process '/sbin/ethtool -G card1 rx-jumbo 1023' failed with exit code 81.
Aug 06 14:49:28 szarotka systemd-networkd[429]: card1: Configuring with /etc/systemd/network/22-card*-bond1-local.network.
Aug 06 14:49:29 szarotka systemd-networkd[429]: card2: Configuring with /etc/systemd/network/22-card*-bond1-local.network.
Aug 06 14:49:29 szarotka systemd-networkd[429]: card1: Link UP
Aug 06 14:49:29 szarotka systemd-networkd[429]: card2: Link UP
Aug 06 14:49:32 szarotka systemd-networkd[429]: card1: Gained carrier
Aug 06 14:49:33 szarotka systemd-networkd[429]: card2: Gained carrier
```

These correspond to
```
Aug 06 14:49:35 szarotka kernel: tg3 0000:20:00.0 eth0: Tigon3 [partno(BCM95720) rev 5720000] (PCI Express) MAC address 00:0a:12:34:56:10
Aug 06 14:49:35 szarotka kernel: tg3 0000:20:00.0 eth0: attached PHY is 5720C (10/100/1000Base-T Ethernet) (WireSpeed[1], EEE[1])
Aug 06 14:49:35 szarotka kernel: tg3 0000:20:00.0 eth0: RXcsums[1] LinkChgREG[0] MIirq[0] ASF[1] TSOcap[1]
Aug 06 14:49:35 szarotka kernel: tg3 0000:20:00.0 eth0: dma_rwctrl[00000001] dma_mask[64-bit]
Aug 06 14:49:35 szarotka kernel: tg3 0000:20:00.1 eth1: Tigon3 [partno(BCM95720) rev 5720000] (PCI Express) MAC address 00:0a:12:34:56:11
Aug 06 14:49:35 szarotka kernel: tg3 0000:20:00.1 eth1: attached PHY is 5720C (10/100/1000Base-T Ethernet) (WireSpeed[1], EEE[1])
Aug 06 14:49:35 szarotka kernel: tg3 0000:20:00.1 eth1: RXcsums[1] LinkChgREG[0] MIirq[0] ASF[1] TSOcap[1]
Aug 06 14:49:35 szarotka kernel: tg3 0000:20:00.1 eth1: dma_rwctrl[00000001] dma_mask[64-bit]

Aug 06 14:49:35 szarotka kernel: tg3 0000:3f:00.0 eth2: Tigon3 [partno(BCM95755) rev a002] (PCI Express) MAC address 78:e3:12:34:56:fd
Aug 06 14:49:35 szarotka kernel: tg3 0000:3f:00.0 eth2: attached PHY is 5755 (10/100/1000Base-T Ethernet) (WireSpeed[1], EEE[0])
Aug 06 14:49:35 szarotka kernel: tg3 0000:3f:00.0 eth2: RXcsums[1] LinkChgREG[0] MIirq[0] ASF[0] TSOcap[1]
Aug 06 14:49:35 szarotka kernel: tg3 0000:3f:00.0 eth2: dma_rwctrl[76180000] dma_mask[64-bit]
```

This works on the BCM95755 (onboard1, eth2).

Running `/sbin/ethtool -G card2 rx-jumbo 1023` manually after the system is booted works:
```
$ ethtool -g onboard1
Ring parameters for onboard1:
Pre-set maximums:
RX:                     511
RX Mini:                n/a
RX Jumbo:               n/a
TX:                     511
TX push buff len:       n/a
Current hardware settings:
RX:                     511
RX Mini:                n/a
RX Jumbo:               n/a
TX:                     511
RX Buf Len:             n/a
CQE Size:               n/a
TX Push:                off
RX Push:                off
TX push buff len:       n/a
TCP data split:         n/a
$ ethtool -g card1
Ring parameters for card1:
Pre-set maximums:
RX:                     2047
RX Mini:                n/a
RX Jumbo:               1023
TX:                     511
TX push buff len:       n/a
Current hardware settings:
RX:                     2047
RX Mini:                n/a
RX Jumbo:               1023
TX:                     511
RX Buf Len:             n/a
CQE Size:               n/a
TX Push:                off
RX Push:                off
TX push buff len:       n/a
TCP data split:         n/a
$ ethtool -g card2
Ring parameters for card2:
Pre-set maximums:
RX:                     2047
RX Mini:                n/a
RX Jumbo:               1023
TX:                     511
TX push buff len:       n/a
Current hardware settings:
RX:                     2047
RX Mini:                n/a
RX Jumbo:               1023
TX:                     511
RX Buf Len:             n/a
CQE Size:               n/a
TX Push:                off
RX Push:                off
TX push buff len:       n/a
TCP data split:         n/a
```

Exit 81 appears to just be "syscall failed": https://salsa.debian.org/kernel-team/ethtool/-/blob/d0578651310379629399dde060577d4b9b0bcab1/ethtool.c#L1988

**Comment by poettering** [comment] 2023-08-07 16:51
> Aug 06 14:49:24 szarotka (udev-worker)[403]: card1: Process '/sbin/ethtool -G card1 rx-jumbo 1023' failed with exit code 81.
> Aug 06 14:49:24 szarotka (udev-worker)[417]: card2: Process '/sbin/ethtool -G card2 rx-jumbo 1023' failed with exit code 81.
> Aug 06 14:49:24 szarotka (udev-worker)[401]: card2: Process '/sbin/ethtool -G card2 rx-jumbo 1023' failed with exit code 81.
> Aug 06 14:49:24 szarotka (udev-worker)[397]: card1: Process '/sbin/ethtool -G card1 rx-jumbo 1023' failed with exit co

I am not sure I follow? You are invoking ethtool from a udev worker? Or are you setthing the fields via .link? What is it now? one or the other?

**Comment by nabijaczleweli** [comment] 2023-08-07 17:16
Sorry, I'd completely forgotten I've added this to my udev rules (indeed,
```
/etc/udev$ l rules.d/xx-card\*.rules
-rw-r--r-- 1 root root 118 2020-04-29  'rules.d/xx-card*.rules'
```
) so I thought that's just how systemd sets it for some reason.

I *do* set it in `20-card1.link` and `21-card2.link`, as you can see above. I removed the udev rules with no change:
```
$ ethtool -g card2
Ring parameters for card2:
Pre-set maximums:
RX:                     2047
RX Mini:                n/a
RX Jumbo:               1023
TX:                     511
TX push buff len:       n/a
Current hardware settings:
RX:                     2047
RX Mini:                n/a
RX Jumbo:               100
TX:                     511
RX Buf Len:             n/a
CQE Size:               n/a
TX Push:                off
RX Push:                off
TX push buff len:       n/a
TCP data split:         n/a
$ journalctl -b | grep tg3
Aug 07 19:11:34 szarotka kernel: tg3 0000:20:00.0 eth0: Tigon3 [partno(BCM95720) rev 5720000] (PCI Express) MAC address 00:0a:12:34:56:10
Aug 07 19:11:34 szarotka kernel: tg3 0000:20:00.0 eth0: attached PHY is 5720C (10/100/1000Base-T Ethernet) (WireSpeed[1],
EEE[1])
Aug 07 19:11:34 szarotka kernel: tg3 0000:20:00.0 eth0: RXcsums[1] LinkChgREG[0] MIirq[0] ASF[1] TSOcap[1]
Aug 07 19:11:34 szarotka kernel: tg3 0000:20:00.0 eth0: dma_rwctrl[00000001] dma_mask[64-bit]
Aug 07 19:11:34 szarotka kernel: tg3 0000:20:00.1 eth1: Tigon3 [partno(BCM95720) rev 5720000] (PCI Express) MAC address 00:0a:12:34:56:11
Aug 07 19:11:34 szarotka kernel: tg3 0000:20:00.1 eth1: attached PHY is 5720C (10/100/1000Base-T Ethernet) (WireSpeed[1],
EEE[1])
Aug 07 19:11:34 szarotka kernel: tg3 0000:20:00.1 eth1: RXcsums[1] LinkChgREG[0] MIirq[0] ASF[1] TSOcap[1]
Aug 07 19:11:34 szarotka kernel: tg3 0000:20:00.1 eth1: dma_rwctrl[00000001] dma_mask[64-bit]
Aug 07 19:11:34 szarotka kernel: tg3 0000:3f:00.0 eth2: Tigon3 [partno(BCM95755) rev a002] (PCI Express) MAC address 78:e3:12:34:56:fd
Aug 07 19:11:34 szarotka kernel: tg3 0000:3f:00.0 eth2: attached PHY is 5755 (10/100/1000Base-T Ethernet) (WireSpeed[1], EEE[0])
Aug 07 19:11:34 szarotka kernel: tg3 0000:3f:00.0 eth2: RXcsums[1] LinkChgREG[0] MIirq[0] ASF[0] TSOcap[1]
Aug 07 19:11:34 szarotka kernel: tg3 0000:3f:00.0 eth2: dma_rwctrl[76180000] dma_mask[64-bit]
Aug 07 19:11:34 szarotka kernel: tg3 0000:3f:00.0 onboard1: renamed from eth2
Aug 07 19:11:34 szarotka kernel: tg3 0000:20:00.1 card2: renamed from eth1
Aug 07 19:11:34 szarotka kernel: tg3 0000:20:00.0 card1: renamed from eth0
Aug 07 19:11:34 szarotka kernel: tg3 0000:20:00.0 card1: Link is up at 1000 Mbps, full duplex
Aug 07 19:11:34 szarotka kernel: tg3 0000:20:00.0 card1: Flow control is on for TX and on for RX
Aug 07 19:11:34 szarotka kernel: tg3 0000:20:00.0 card1: EEE is enabled
Aug 07 19:11:34 szarotka kernel: tg3 0000:20:00.1 card2: Link is up at 1000 Mbps, full duplex
Aug 07 19:11:34 szarotka kernel: tg3 0000:20:00.1 card2: Flow control is on for TX and on for RX
Aug 07 19:11:34 szarotka kernel: tg3 0000:20:00.1 card2: EEE is enabled
Aug 07 19:11:34 szarotka kernel: tg3 0000:3f:00.0 onboard1: Link is up at 1000 Mbps, full duplex
Aug 07 19:11:34 szarotka kernel: tg3 0000:3f:00.0 onboard1: Flow control is off for TX and off for RX
```

**Comment by yuwata** [comment] 2023-08-07 17:23
Should be a duplicate of #16445.

**Comment by nabijaczleweli** [comment] 2023-08-07 19:35
Doubt it. Upness and downness doesn't really matter here:
```
# ethtool -G card1 rx-jumbo 100
$ ethtool -g card1
Ring parameters for card1:
Pre-set maximums:
RX:                     2047
RX Mini:                n/a
RX Jumbo:               1023
TX:                     511
TX push buff len:       n/a
Current hardware settings:
RX:                     2047
RX Mini:                n/a
RX Jumbo:               100
TX:                     511
RX Buf Len:             n/a
CQE Size:               n/a
TX Push:                off
RX Push:                off
TX push buff len:       n/a
TCP data split:         n/a
# ip l set card1 down
# udevadm trigger --action=add /sys/class/net/card1
$ ethtool -g card1
Ring parameters for card1:
Pre-set maximums:
RX:                     2047
RX Mini:                n/a
RX Jumbo:               1023
TX:                     511
TX push buff len:       n/a
Current hardware settings:
RX:                     2047
RX Mini:                n/a
RX Jumbo:               1023
TX:                     511
RX Buf Len:             n/a
CQE Size:               n/a
TX Push:                off
RX Push:                off
TX push buff len:       n/a
TCP data split:         n/a
# ip l set card1 up
$ ethtool -g card1
Ring parameters for card1:
Pre-set maximums:
RX:                     2047
RX Mini:                n/a
RX Jumbo:               1023
TX:                     511
TX push buff len:       n/a
Current hardware settings:
RX:                     2047
RX Mini:                n/a
RX Jumbo:               1023
TX:                     511
RX Buf Len:             n/a
CQE Size:               n/a
TX Push:                off
RX Push:                off
TX push buff len:       n/a
TCP data split:         n/a
```

**Comment by nabijaczleweli** [comment] 2023-08-07 19:38
Indeed, you *should* set this before you bring them up because they go through a full reset sequence when these parameters are changed and the interface is up:
```
# ethtool -G card1 rx-jumbo 100
Aug 07 21:37:02 szarotka sudo[28617]: nabijaczleweli : TTY=pts/0 ; PWD=/home/nabijaczleweli ; USER=root ; COMMAND=/sbin/ethtool -G card1 rx-jumbo 100
Aug 07 21:37:02 szarotka sudo[28617]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
Aug 07 21:37:02 szarotka kernel: tg3 0000:20:00.0 card1: Link is down
Aug 07 21:37:02 szarotka systemd-networkd[427]: card1: Lost carrier
Aug 07 21:37:02 szarotka sudo[28617]: pam_unix(sudo:session): session closed for user root
Aug 07 21:37:02 szarotka kernel: bond1: (slave card1): link status definitely down, disabling slave
Aug 07 21:37:02 szarotka kernel: tg3 0000:20:00.1 card2: entered promiscuous mode
Aug 07 21:37:05 szarotka kernel: tg3 0000:20:00.0 card1: Link is up at 1000 Mbps, full duplex
Aug 07 21:37:05 szarotka kernel: tg3 0000:20:00.0 card1: Flow control is on for TX and on for RX
Aug 07 21:37:05 szarotka kernel: tg3 0000:20:00.0 card1: EEE is enabled
Aug 07 21:37:05 szarotka systemd-networkd[427]: card1: Gained carrier
Aug 07 21:37:06 szarotka kernel: bond1: (slave card1): link status definitely up, 1000 Mbps full duplex
```

**Comment by yuwata** [comment] 2023-08-08 02:37
Thank you for the confirmation. Let's close this, and continue discussion if necessary in #16445.

**Closed as completed by yuwata** 2023-08-08 02:37 UTC
Labels: RFE 🎁, udev, network, duplicate
