### ISSUE TITLE
sys-fs-fuse-connections.mount doesn't always succeed

### ISSUE THREAD

**Issue by terencode** [systemd/systemd#12450] opened 2019-05-01 04:34 UTC
**systemd version the issue has been seen with**
> 242.19

**Used distribution**
 > ArchLinux

**Expected behaviour you didn't see**
 > `sys-fs-fuse-connections.mount` runs correctly at each boot.

**Unexpected behaviour you saw**
 >  `sys-fs-fuse-connections.mount` sometimes fails:
```
● sys-fs-fuse-connections.mount - FUSE Control File System
   Loaded: loaded (/usr/lib/systemd/system/sys-fs-fuse-connections.mount; static; vendor preset: disabled)
   Active: failed (Result: start-limit-hit)
    Where: /sys/fs/fuse/connections
     What: fusectl
     Docs: https://www.kernel.org/doc/Documentation/filesystems/fuse.txt
           https://www.freedesktop.org/wiki/Software/systemd/APIFileSystems

mai 01 05:51:28 terence-arch systemd[1]: Condition check resulted in FUSE Control File System being skipped.
mai 01 05:51:28 terence-arch systemd[1]: Condition check resulted in FUSE Control File System being skipped.
mai 01 05:51:28 terence-arch systemd[1]: Condition check resulted in FUSE Control File System being skipped.
mai 01 05:51:28 terence-arch systemd[1]: Condition check resulted in FUSE Control File System being skipped.
mai 01 05:51:31 terence-arch systemd[1]: sys-fs-fuse-connections.mount: Start request repeated too quickly.
mai 01 05:51:31 terence-arch systemd[1]: sys-fs-fuse-connections.mount: Failed with result 'start-limit-hit'.
mai 01 05:51:31 terence-arch systemd[1]: Failed to mount FUSE Control File System.
```

**Steps to reproduce the problem**
No consistent way to reproduce, only way is to reboot until problem occurs (race condition?).

**Comment by psemiletov** [comment] 2019-05-19 12:05
On Manjaro I have the same issue with systemd  242.29-1

**Comment by mbiebl** [comment] 2019-05-19 12:24
sys-fs-fuse-connections.mount has the following conditions:
```
ConditionPathExists=/sys/fs/fuse/connections
ConditionCapability=CAP_SYS_ADMIN
ConditionVirtualization=!private-users
```
I suspect it is `ConditionPathExists=/sys/fs/fuse/connections` which fails, but could you comment out that line just to confirm this?

**Comment by terencode** [comment] 2019-05-19 17:51
Sure, the problem is I can't reproduce any more with systemd 242.27. Maybe @psemiletov can help then.

**Comment by psemiletov** [comment] 2019-05-20 18:43
It happen from time to time, I don't know why. After that error message, all ntfs partitions are mounted ok.

**Comment by dtardon** [comment] 2019-05-21 06:33
This looks like a dupe of #4574.

**Comment by furgerf** [comment] 2019-05-23 13:03
I seem to have the same issue, very reliably on every boot. Starting sys-fs-fuse-connections.mount manually once booted works fine.

I've also tried the [hack](https://github.com/systemd/systemd/issues/4574#issuecomment-259833979) suggested by @mbiebl but that didn't help.

```
$ uname -a
Linux thinkpad 5.1.4-arch1-1-ARCH #1 SMP PREEMPT Wed May 22 08:06:56 UTC 2019 x86_64 GNU/Linux
$ systemctl --version
systemd 242 (242.29-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

**Comment by chrisco23** [comment] 2019-05-27 18:17
Yesterday I went to do a rare reboot and hit a bunch of systemd fails with 242.29-1-arch, sounding much like this (hence my arrival here).  I've been reading forums all morning and made some progress but it's still reliably getting one of these failures at every boot..

I did a few things and I can't say exactly what helped but at least I can boot now without getting dumped into emergency mode.  [knock]

I normally mount 2 USB ntfs drives and 1 USB externalized ext4 as such:

```
$ cat /etc/fstab
# 
# /etc/fstab: static file system information
#
# <file system> <dir>   <type>  <options>       <dump>  <pass>
UUID=8a55c7b6-4da8-4bb8-8061-b847aeb17136       /               ext4            rw,relatime,data=ordered        0 1
UUID=8dcfcdec-ae43-4991-ad64-14a4b6eae3f1       /mnt/downloads  ext4    rw,noexec,auto,user,async       0       0
UUID=8A38BB7838BB61BD   /mnt/mypassport ntfs defaults
UUID=64D4EAFED4EAD0FA   /mnt/mybook     ntfs defaults
```

Previously my ntfs were listed as ntfs-3g with more complicated params so I simplified per one of the threads I found.

I don't know if it's related but I also took a 4-port USB hub and 3 USB devices out of the equation (all of these had no real reason to be plugged into the computer anyway, and are now just plugged into a power strip).

Now I can boot and mount all my drives on boot, and only get the one Fail, so I'm mainly curious to find out what the problem has been and when it is resolved.

**Comment by poettering** [comment] 2019-06-18 14:13
This indeed looks like a duplicate of #4574, I agree with @dtardon. It's a kernel bug and remains unfixed. 

let's close this here. we can't sensibly work around this. Please print the issue up to the kernel folks!

**Closed as completed by poettering** 2019-06-18 14:13 UTC
Labels: not-our-bug, duplicate

**Comment by terencode** [comment] 2019-06-18 14:38
@dtardon where do you report such bugs?

**Comment by mbiebl** [comment] 2019-06-18 14:39
@terencode There is already https://bugzilla.kernel.org/show_bug.cgi?id=187421 with zero response since almost 3 years. Not sure who should be poked to get some attention to this issue.

**Comment by poettering** [comment] 2019-06-18 14:41
i don't think kernel bugzilla has the acceptance in the kernel community it ought to have. it's probably best to ping the maintainer of fuse.ko about this directly by email

**Comment by szmi** [comment] 2019-06-24 07:48
Can someone please report this on the relevant persons/mailing list?  Since fuse is involved in the creation of "sys/fs/connections" only as far as calling sysfs_create_mount_point(), I suspect the issue is in sysfs/kernfs.
