### ISSUE TITLE
systemd 246 regression for lingering user sessions and RuntimeDirectoryInodesMax

### ISSUE THREAD

**Issue by zyga** [systemd/systemd#16685] opened 2020-08-06 17:16 UTC
**systemd version the issue has been seen with**
> 246

**Used distribution**
 > Debian (sid) x86-64

**Expected behaviour you didn't see**
 > systemctl enable-linger foo works normally (before 246 upgrade)

**Unexpected behaviour you saw**
 > systemctl enable-linger foo fails as described below

**Steps to reproduce the problem**
- Boot and upgrade Debian sid
- Create a user, e.g. `test` or otherwise
- invoke as root: `systemctl enable-linger test`

What happens: 
```
google:debian-sid-64 ...# systemctl status user-runtime-dir@1000.service
● user-runtime-dir@1000.service - User Runtime Directory /run/user/1000
     Loaded: loaded (/lib/systemd/system/user-runtime-dir@.service; static)
     Active: failed (Result: exit-code) since Thu 2020-08-06 17:08:06 UTC; 4min 1s ago
       Docs: man:user@.service(5)
    Process: 28557 ExecStart=/lib/systemd/systemd-user-runtime-dir start 1000 (code=exited, status=1/FAILURE)
   Main PID: 28557 (code=exited, status=1/FAILURE)

Aug 06 17:08:06 aug061652-827018 systemd[1]: Starting User Runtime Directory /run/user/1000...
Aug 06 17:08:06 aug061652-827018 systemd-user-runtime-dir[28557]: Failed to acquire number of inodes for runtime directory: Unknown interface org.freedesktop.login1.Manager or property RuntimeDirectoryInodesMax.
Aug 06 17:08:06 aug061652-827018 systemd[1]: user-runtime-dir@1000.service: Main process exited, code=exited, status=1/FAILURE
Aug 06 17:08:06 aug061652-827018 systemd[1]: user-runtime-dir@1000.service: Failed with result 'exit-code'.
Aug 06 17:08:06 aug061652-827018 systemd[1]: Failed to start User Runtime Directory /run/user/1000.
```

It seems that the problem is with `RuntimeDirectoryInodesMax`.

Looking deeper it does not show up in introspection data
```
google:debian-sid-64 ...# busctl introspect org.freedesktop.login1 /org/freedesktop/login1
NAME                                TYPE      SIGNATURE          RESULT/VALUE         FLAGS
org.freedesktop.DBus.Introspectable interface -                  -                    -
.Introspect                         method    -                  s                    -
org.freedesktop.DBus.Peer           interface -                  -                    -
.GetMachineId                       method    -                  s                    -
.Ping                               method    -                  -                    -
org.freedesktop.DBus.Properties     interface -                  -                    -
.Get                                method    ss                 v                    -
.GetAll                             method    s                  a{sv}                -
.Set                                method    ssv                -                    -
.PropertiesChanged                  signal    sa{sv}as           -                    -
org.freedesktop.login1.Manager      interface -                  -                    -
.ActivateSession                    method    s                  -                    -
.ActivateSessionOnSeat              method    ss                 -                    -
.AttachDevice                       method    ssb                -                    -
.CanHalt                            method    -                  s                    -
.CanHibernate                       method    -                  s                    -
.CanHybridSleep                     method    -                  s                    -
.CanPowerOff                        method    -                  s                    -
.CanReboot                          method    -                  s                    -
.CanRebootParameter                 method    -                  s                    -
.CanRebootToBootLoaderEntry         method    -                  s                    -
.CanRebootToBootLoaderMenu          method    -                  s                    -
.CanRebootToFirmwareSetup           method    -                  s                    -
.CanSuspend                         method    -                  s                    -
.CanSuspendThenHibernate            method    -                  s                    -
.CancelScheduledShutdown            method    -                  b                    -
.CreateSession                      method    uusssssussbssa(sv) soshusub             -
.FlushDevices                       method    b                  -                    -
.GetSeat                            method    s                  o                    -
.GetSession                         method    s                  o                    -
.GetSessionByPID                    method    u                  o                    -
.GetUser                            method    u                  o                    -
.GetUserByPID                       method    u                  o                    -
.Halt                               method    b                  -                    -
.Hibernate                          method    b                  -                    -
.HybridSleep                        method    b                  -                    -
.Inhibit                            method    ssss               h                    -
.KillSession                        method    ssi                -                    -
.KillUser                           method    ui                 -                    -
.ListInhibitors                     method    -                  a(ssssuu)            -
.ListSeats                          method    -                  a(so)                -
.ListSessions                       method    -                  a(susso)             -
.ListUsers                          method    -                  a(uso)               -
.LockSession                        method    s                  -                    -
.LockSessions                       method    -                  -                    -
.PowerOff                           method    b                  -                    -
.Reboot                             method    b                  -                    -
.ReleaseSession                     method    s                  -                    -
.ScheduleShutdown                   method    st                 -                    -
.SetRebootParameter                 method    s                  -                    -
.SetRebootToBootLoaderEntry         method    s                  -                    -
.SetRebootToBootLoaderMenu          method    t                  -                    -
.SetRebootToFirmwareSetup           method    b                  -                    -
.SetUserLinger                      method    ubb                -                    -
.SetWallMessage                     method    sb                 -                    -
.Suspend                            method    b                  -                    -
.SuspendThenHibernate               method    b                  -                    -
.TerminateSeat                      method    s                  -                    -
.TerminateSession                   method    s                  -                    -
.TerminateUser                      method    u                  -                    -
.UnlockSession                      method    s                  -                    -
.UnlockSessions                     method    -                  -                    -
.BlockInhibited                     property  s                  ""                   emits-change
.BootLoaderEntries                  property  as                 0                    const
.DelayInhibited                     property  s                  ""                   emits-change
.Docked                             property  b                  false                -
.EnableWallMessages                 property  b                  false                writable
.HandleHibernateKey                 property  s                  "hibernate"          const
.HandleLidSwitch                    property  s                  "suspend"            const
.HandleLidSwitchDocked              property  s                  "ignore"             const
.HandleLidSwitchExternalPower       property  s                  ""                   const
.HandlePowerKey                     property  s                  "poweroff"           const
.HandleSuspendKey                   property  s                  "suspend"            const
.HoldoffTimeoutUSec                 property  t                  30000000             const
.IdleAction                         property  s                  "ignore"             const
.IdleActionUSec                     property  t                  1800000000           const
.IdleHint                           property  b                  false                emits-change
.IdleSinceHint                      property  t                  0                    emits-change
.IdleSinceHintMonotonic             property  t                  0                    emits-change
.InhibitDelayMaxUSec                property  t                  5000000              const
.InhibitorsMax                      property  t                  8192                 const
.KillExcludeUsers                   property  as                 0                    const
.KillOnlyUsers                      property  as                 0                    const
.KillUserProcesses                  property  b                  false                const
.LidClosed                          property  b                  false                -
.NAutoVTs                           property  u                  6                    const
.NCurrentInhibitors                 property  t                  0                    -
.NCurrentSessions                   property  t                  1                    -
.OnExternalPower                    property  b                  true                 -
.PreparingForShutdown               property  b                  false                -
.PreparingForSleep                  property  b                  false                -
.RebootParameter                    property  s                  ""                   -
.RebootToBootLoaderEntry            property  s                  ""                   -
.RebootToBootLoaderMenu             property  t                  18446744073709551615 -
.RebootToFirmwareSetup              property  b                  false                -
.RemoveIPC                          property  b                  true                 const
.RuntimeDirectorySize               property  t                  386756608            const
.ScheduledShutdown                  property  (st)               "" 0                 -
.SessionsMax                        property  t                  8192                 const
.UserStopDelayUSec                  property  t                  10000000             const
.WallMessage                        property  s                  ""                   writable
.PrepareForShutdown                 signal    b                  -                    -
.PrepareForSleep                    signal    b                  -                    -
.SeatNew                            signal    so                 -                    -
.SeatRemoved                        signal    so                 -                    -
.SessionNew                         signal    so                 -                    -
.SessionRemoved                     signal    so                 -                    -
.UserNew                            signal    uo                 -                    -
.UserRemoved                        signal    uo                 -                    -
/q
busctl introspect org.freedesktop.login1 /org/freedesktop/login1 | cat
NAME                                TYPE      SIGNATURE          RESULT/VALUE         FLAGS
org.freedesktop.DBus.Introspectable interface -                  -                    -
.Introspect                         method    -                  s                    -
org.freedesktop.DBus.Peer           interface -                  -                    -
.GetMachineId                       method    -                  s                    -
.Ping                               method    -                  -                    -
org.freedesktop.DBus.Properties     interface -                  -                    -
.Get                                method    ss                 v                    -
.GetAll                             method    s                  a{sv}                -
.Set                                method    ssv                -                    -
.PropertiesChanged                  signal    sa{sv}as           -                    -
org.freedesktop.login1.Manager      interface -                  -                    -
.ActivateSession                    method    s                  -                    -
.ActivateSessionOnSeat              method    ss                 -                    -
.AttachDevice                       method    ssb                -                    -
.CanHalt                            method    -                  s                    -
.CanHibernate                       method    -                  s                    -
.CanHybridSleep                     method    -                  s                    -
.CanPowerOff                        method    -                  s                    -
.CanReboot                          method    -                  s                    -
.CanRebootParameter                 method    -                  s                    -
.CanRebootToBootLoaderEntry         method    -                  s                    -
.CanRebootToBootLoaderMenu          method    -                  s                    -
.CanRebootToFirmwareSetup           method    -                  s                    -
.CanSuspend                         method    -                  s                    -
.CanSuspendThenHibernate            method    -                  s                    -
.CancelScheduledShutdown            method    -                  b                    -
.CreateSession                      method    uusssssussbssa(sv) soshusub             -
.FlushDevices                       method    b                  -                    -
.GetSeat                            method    s                  o                    -
.GetSession                         method    s                  o                    -
.GetSessionByPID                    method    u                  o                    -
.GetUser                            method    u                  o                    -
.GetUserByPID                       method    u                  o                    -
.Halt                               method    b                  -                    -
.Hibernate                          method    b                  -                    -
.HybridSleep                        method    b                  -                    -
.Inhibit                            method    ssss               h                    -
.KillSession                        method    ssi                -                    -
.KillUser                           method    ui                 -                    -
.ListInhibitors                     method    -                  a(ssssuu)            -
.ListSeats                          method    -                  a(so)                -
.ListSessions                       method    -                  a(susso)             -
.ListUsers                          method    -                  a(uso)               -
.LockSession                        method    s                  -                    -
.LockSessions                       method    -                  -                    -
.PowerOff                           method    b                  -                    -
.Reboot                             method    b                  -                    -
.ReleaseSession                     method    s                  -                    -
.ScheduleShutdown                   method    st                 -                    -
.SetRebootParameter                 method    s                  -                    -
.SetRebootToBootLoaderEntry         method    s                  -                    -
.SetRebootToBootLoaderMenu          method    t                  -                    -
.SetRebootToFirmwareSetup           method    b                  -                    -
.SetUserLinger                      method    ubb                -                    -
.SetWallMessage                     method    sb                 -                    -
.Suspend                            method    b                  -                    -
.SuspendThenHibernate               method    b                  -                    -
.TerminateSeat                      method    s                  -                    -
.TerminateSession                   method    s                  -                    -
.TerminateUser                      method    u                  -                    -
.UnlockSession                      method    s                  -                    -
.UnlockSessions                     method    -                  -                    -
.BlockInhibited                     property  s                  ""                   emits-change
.BootLoaderEntries                  property  as                 0                    const
.DelayInhibited                     property  s                  ""                   emits-change
.Docked                             property  b                  false                -
.EnableWallMessages                 property  b                  false                writable
.HandleHibernateKey                 property  s                  "hibernate"          const
.HandleLidSwitch                    property  s                  "suspend"            const
.HandleLidSwitchDocked              property  s                  "ignore"             const
.HandleLidSwitchExternalPower       property  s                  ""                   const
.HandlePowerKey                     property  s                  "poweroff"           const
.HandleSuspendKey                   property  s                  "suspend"            const
.HoldoffTimeoutUSec                 property  t                  30000000             const
.IdleAction                         property  s                  "ignore"             const
.IdleActionUSec                     property  t                  1800000000           const
.IdleHint                           property  b                  false                emits-change
.IdleSinceHint                      property  t                  0                    emits-change
.IdleSinceHintMonotonic             property  t                  0                    emits-change
.InhibitDelayMaxUSec                property  t                  5000000              const
.InhibitorsMax                      property  t                  8192                 const
.KillExcludeUsers                   property  as                 0                    const
.KillOnlyUsers                      property  as                 0                    const
.KillUserProcesses                  property  b                  false                const
.LidClosed                          property  b                  false                -
.NAutoVTs                           property  u                  6                    const
.NCurrentInhibitors                 property  t                  0                    -
.NCurrentSessions                   property  t                  1                    -
.OnExternalPower                    property  b                  true                 -
.PreparingForShutdown               property  b                  false                -
.PreparingForSleep                  property  b                  false                -
.RebootParameter                    property  s                  ""                   -
.RebootToBootLoaderEntry            property  s                  ""                   -
.RebootToBootLoaderMenu             property  t                  18446744073709551615 -
.RebootToFirmwareSetup              property  b                  false                -
.RemoveIPC                          property  b                  true                 const
.RuntimeDirectorySize               property  t                  386756608            const
.ScheduledShutdown                  property  (st)               "" 0                 -
.SessionsMax                        property  t                  8192                 const
.UserStopDelayUSec                  property  t                  10000000             const
.WallMessage                        property  s                  ""                   writable
.PrepareForShutdown                 signal    b                  -                    -
.PrepareForSleep                    signal    b                  -                    -
.SeatNew                            signal    so                 -                    -
.SeatRemoved                        signal    so                 -                    -
.SessionNew                         signal    so                 -                    -
.SessionRemoved                     signal    so                 -                    -
.UserNew                            signal    uo                 -                    -
.UserRemoved                        signal    uo                 -                    -
```

But is present in the source.

EDIT: I just realized that Debian maintainer script does not restart `systemd-logind.service` doing that is sufficient to fix the problem. Feel free to close though I will report a Debian bug and reference this one for tracking.

**Comment by zyga** [comment] 2020-08-06 17:19
While looking deeper I see this in the Debian postinst script:

```
if [ -n "$2" ]; then
    _systemctl daemon-reexec || true
    # don't restart logind; this can be done again once this gets implemented:
    # https://github.com/systemd/systemd/issues/1163
    _systemctl try-restart systemd-networkd.service || true
    _systemctl try-restart systemd-resolved.service || true
    _systemctl try-restart systemd-journald.service || true
fi

```

The referenced bug has been closed (fixed) so this is a clear bug in packaging.

**Comment by zyga** [comment] 2020-08-06 17:36
This is now a Debian bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=968014

**Comment by zyga** [comment] 2020-08-06 17:53
It seems this is a deeper problem, as restarting logind is still not allowed due to the interaction with graphical login sessions. In this case, could the systemd upstream bug (this one) be expanded to improve compatibility of a skew of systemd-logind.service? At least the error condition could be detected and handled better.

**Comment by poettering** [comment] 2020-08-06 20:07
hmm, logind should be restartable these days again without losing state.

I figure this is caused by a version mismatch, the running logind is still old, doesn't expose the props needed by the new user-runtime-dir@.service.

I guess we should make user-runtime-dir@.service handle this more graceful, i.e. come up with some default value if we can't query the prop. But then again, by the time this hit the distro repos it's probably already too late to fix anything for anyone.

/cc @topimiettinen

**Comment by zyga** [comment] 2020-08-10 08:55
@poettering my bug regarding systemd-logind.service not being restarted in Debian postinst script was closed as duplicate and the maintainer replied that there are still issues with Wayland and X and that unless those are taken care of, packaging cannot change. I asked for references to specific bugs as the one mentioned in packaging was already fixed.

**Comment by zyga** [comment] 2020-08-10 08:58
While trying to work around this on our end I think I found a bug in logind itself, but in v245. It does seem to forget state across restart:

This was executed on up-to-date Fedora 32 x86_64:
```
    loginctl list-sessions >/root/sessions-before-restart.txt
    systemctl restart systemd-logind.service || true
    loginctl list-sessions >/root/sessions-after-restart.txt
    diff -u /root/sessions-before-restart.txt /root/sessions-after-restart.txt
```

The result is:
```
+ loginctl list-sessions
+ systemctl restart systemd-logind.service
+ loginctl list-sessions
+ diff -u /root/sessions-before-restart.txt /root/sessions-after-restart.txt
--- /root/sessions-before-restart.txt	2020-08-10 08:56:16.171431721 +0000
+++ /root/sessions-after-restart.txt	2020-08-10 08:56:16.520486961 +0000
@@ -1,4 +1 @@
-SESSION UID USER SEAT TTY
-      1   0 root         
-
-1 sessions listed.
+No sessions.
-----
.
2020-08-10 10:56:16 Starting shell to debug...
google:fedora-32-64 ...# systemctl --version
systemd 245 (v245.4-1.fc32)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
```

**Comment by poettering** [comment] 2020-08-10 13:50
The logind reload issue was fixed in v246

**Closed as completed** 2020-08-20 11:12 UTC
Labels: login
