### ISSUE TITLE
systemd unable to use ipmi_watchdog

### ISSUE THREAD

**Issue by glance-** [systemd/systemd#26083] opened 2023-01-17 10:57 UTC
### systemd version the issue has been seen with

251.3

### Used distribution

Debian 11

### Linux kernel version used

5.15.81

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

Systemd opening the configured watchdog , /dev/watchdog

### Unexpected behaviour you saw

Systemd trying to open the non-existing watchdog /dev/watchdog0

### Steps to reproduce the problem

Run systemd on a machine with a ipmi BMC, or in qemu with one emulated with something like: -device ipmi-bmc-sim,id=bmc0 -device isa-ipmi-kcs,bmc=bmc0

Load the ipmi_watchdog driver.

Try to get systemd to use the /dev/watchdog device as system watchdog.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
The ipmi_watchdog is a old style watchdog driver, and doesn't produce a numbered watchdog device. Thus, with this watchdog driver, there's only a /dev/watchdog device, and no  /dev/watchdog0 device.

As the code reads in src/shared/watchdog.c:open_watchdog systemd translates /dev/watchdog into /dev/watchdog0 which can't be done for watchdog devices provided by the ipmi_watchdog driver.

After reconfiguring systemd to WatchdogDevice=/dev/ipmi_watchdog and adding a symlink ln -s watchdog ipmi_watchdog , systemd manage to use the ipmi_watchdog device as expected:
Using hardware watchdog 'IPMI', version 1, device /dev/ipmi_watchdog
```

**Comment by bluca** [comment] 2023-01-17 11:17
Duplicate of https://github.com/systemd/systemd/issues/24661

**Closed as not planned by bluca** 2023-01-17 11:17 UTC
Labels: pid1, duplicate
