### ISSUE TITLE
e307bebc0358a00ba6d945e411bd764cd39c5462 broke git

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#31773] opened 2024-03-14 09:03 UTC
### systemd version the issue has been seen with

git main 

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

```console
$ git diff
fatal: not a git repository: pkg/fedora/../../../../home/zbyszek/src/systemd/.git/worktrees/systemd-work/modules/pkg/fedora
```
I think this might be caused by some relative path confusion. `pkg/fedora/../../../../` points to my home directory, i.e. the path would need to be `pkg/fedora/../../../../../../home/zbyszek/src/systemd/.git/worktrees/systemd-work/modules/pkg/fedora` to actually work.

**Comment by keszybz** [comment] 2024-03-14 09:14
So I did a bunch of `rm -rf ` and `git restore` and now it works.
```
$ cat pkg/fedora/.git
gitdir: ../../../systemd/.git/worktrees/systemd-work/modules/pkg/fedora
```

I suspect this might be something related to calling git from the `build` directory, one level down.

**Comment by DaanDeMeyer** [comment] 2024-03-14 09:20
Let me know if you find a way to reproduce, happy to try and find a solution.

**Comment by evverx** [comment] 2024-03-16 16:27
Looks like it also broke the "pages build and deployment" action.

https://github.com/systemd/systemd/actions/runs/8307892277/job/22737563636
```
2024-03-16T12:52:20.1511024Z ##[group]Fetching submodules
2024-03-16T12:52:20.1517315Z [command]/usr/bin/git submodule sync --recursive
2024-03-16T12:52:20.1762337Z [command]/usr/bin/git -c protocol.version=2 submodule update --init --force --depth=1 --recursive
2024-03-16T12:52:20.1989682Z Submodule 'pkg/arch' (https://gitlab.archlinux.org/daandemeyer/systemd) registered for path 'pkg/arch'
2024-03-16T12:52:20.1994804Z Submodule 'pkg/centos' (https://git.centos.org/rpms/systemd) registered for path 'pkg/centos'
2024-03-16T12:52:20.1999675Z Submodule 'pkg/debian' (https://salsa.debian.org/systemd-team/systemd) registered for path 'pkg/debian'
2024-03-16T12:52:20.2003611Z Submodule 'pkg/fedora' (https://src.fedoraproject.org/rpms/systemd) registered for path 'pkg/fedora'
2024-03-16T12:52:20.2008139Z Submodule 'pkg/opensuse' (https://code.opensuse.org/package/systemd) registered for path 'pkg/opensuse'
2024-03-16T12:52:20.2036043Z Cloning into '/home/runner/work/systemd/systemd/pkg/arch'...
2024-03-16T12:52:21.0169144Z warning: redirecting to https://gitlab.archlinux.org/daandemeyer/systemd.git/
2024-03-16T12:52:21.6070041Z Cloning into '/home/runner/work/systemd/systemd/pkg/centos'...
2024-03-16T12:52:22.5696206Z Cloning into '/home/runner/work/systemd/systemd/pkg/debian'...
2024-03-16T12:52:23.0418816Z warning: redirecting to https://salsa.debian.org/systemd-team/systemd.git/
2024-03-16T12:52:26.4189059Z Cloning into '/home/runner/work/systemd/systemd/pkg/fedora'...
2024-03-16T12:52:27.2060419Z Cloning into '/home/runner/work/systemd/systemd/pkg/opensuse'...
2024-03-16T12:52:29.8550001Z warning: redirecting to https://gitlab.archlinux.org/daandemeyer/systemd.git/
2024-03-16T12:52:31.0352949Z warning: redirecting to https://gitlab.archlinux.org/daandemeyer/systemd.git/
2024-03-16T12:52:31.5947074Z From https://gitlab.archlinux.org/daandemeyer/systemd
2024-03-16T12:52:31.5948193Z  * branch            733045c8f6b0acf2f0cfaac207500483a678f4d2 -> FETCH_HEAD
2024-03-16T12:52:31.6020367Z Submodule path 'pkg/arch': checked out '733045c8f6b0acf2f0cfaac207500483a678f4d2'
2024-03-16T12:52:32.7666134Z From https://git.centos.org/rpms/systemd
2024-03-16T12:52:32.7667106Z  * branch            3cf45106c8bc5a050901851be6b2ac85b6f5c571 -> FETCH_HEAD
2024-03-16T12:52:32.7768256Z Submodule path 'pkg/centos': checked out '3cf45106c8bc5a050901851be6b2ac85b6f5c571'
2024-03-16T12:52:33.2675715Z Submodule path 'pkg/debian': checked out '5451923e3e7f5d6cc54f78a8b1d08317a42b4109'
2024-03-16T12:52:33.2810104Z Submodule path 'pkg/fedora': checked out '2822a03dded26b9453bddbba7c6a152de8204aec'
2024-03-16T12:52:34.6953387Z ##[error]error: Server does not allow request for unadvertised object 37aca188c2ef606319217b30ff8b0c66df6c60f1
2024-03-16T12:52:34.6964195Z ##[error]fatal: Fetched in submodule path 'pkg/opensuse', but it did not contain 37aca188c2ef606319217b30ff8b0c66df6c60f1. Direct fetching of that commit failed.
2024-03-16T12:52:34.7013724Z ##[error]The process '/usr/bin/git' failed with exit code 128
2024-03-16T12:52:34.7252330Z Post job cleanup.
2024-03-16T12:52:34.7956068Z [command]/usr/bin/git version
```

**Comment by keszybz** [comment] 2024-03-17 10:51
We don't need the submodules to build pages, so the best solution would be to skip the sync altogether.

**Comment by evverx** [comment] 2024-03-17 10:57
As far as I understand that particular action is run by default and can't be changed. Publishing with a custom GitHub Actions workflow is in beta: https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow

**Comment by evverx** [comment] 2024-03-17 13:27
By the way that action fails every time PRs get merged into the main branch: https://github.com/systemd/systemd/actions/workflows/pages/pages-build-deployment and the authors of the commits where the action is triggered probably receive notifications about that. As long as it's broken it would probably make sense to turn it off.

**Comment by DaanDeMeyer** [comment] 2024-03-17 14:29
This action seems quite broken, it passes `--depth=1` when cloning submodules, which seems like it expects all submodules to always be at the latest version?

**Comment by DaanDeMeyer** [comment] 2024-03-17 14:46
Reported the bug: https://github.com/orgs/community/discussions/112984

**Comment by DaanDeMeyer** [comment] 2024-03-17 14:50
https://github.com/systemd/systemd/pull/31831 should fix the issue for now

**Comment by evverx** [comment] 2024-03-30 11:38
Looks like GH Pages started failing again: https://github.com/systemd/systemd/actions/runs/8486811342/job/23253772460
```sh
2024-03-30T00:08:46.4477288Z Submodule path 'pkg/arch': checked out '3b86b9146b84d499789ba924a9dd4ac643d796ab'
2024-03-30T00:08:47.2347738Z ##[error]error: Server does not allow request for unadvertised object 3cf45106c8bc5a050901851be6b2ac85b6f5c571
2024-03-30T00:08:47.2360112Z ##[error]fatal: Fetched in submodule path 'pkg/centos', but it did not contain 3cf45106c8bc5a050901851be6b2ac85b6f5c571. Direct fetching of that commit failed.
2024-03-30T00:08:47.2423345Z ##[error]The process '/usr/bin/git' failed with exit code 128
2024-03-30T00:08:47.2654614Z Post job cleanup.
```
Dependabot broke too. In https://github.com/evverx/systemd/pull/204 it complained that it couldn't access the repository:
```sh
updater | Submodule path 'pkg/arch': checked out '3b86b9146b84d499789ba924a9dd4ac643d796ab'
updater | error: Server does not allow request for unadvertised object 3cf45106c8bc5a050901851be6b2ac85b6f5c571
updater | fatal: Fetched in submodule path 'pkg/centos', but it did not contain 3cf45106c8bc5a050901851be6b2ac85b6f5c571. Direct fetching of that commit failed.
updater | fatal:
updater | 2024/03/30 11:20:28 INFO <job_807505958> Finished job processing
updater | 2024/03/30 11:20:28 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +--------------------+
updater | |       Errors       |
updater | +--------------------+
updater | | job_repo_not_found |
updater | +--------------------+
```

**Comment by DaanDeMeyer** [comment] 2024-03-30 22:05
I reported https://pagure.io/pagure/issue/5453 for pagure. I can also report a bug for dependabot. On the report for GH pages I got told to use the custom workflow thingy.

**Comment by evverx** [comment] 2024-03-31 12:53
As far as I can remember it took several years for a Dependabot bug I cared about to get fixed so in terms of getting the Dependabot failures fixed it would probably be better if all the modules could be extracted using the flags Dependabot passes.

The custom GH Pages workflow would probably complicate things too.

**Comment by DaanDeMeyer** [comment] 2024-03-31 14:14
> As far as I can remember it took several years for a Dependabot bug I cared about to get fixed so in terms of getting the Dependabot failures fixed it would probably be better if all the modules could be extracted using the flags Dependabot passes.
> 
> The custom GH Pages workflow would probably complicate things too.

The pagure folks seem amicable to my proposal to add the necessary config to make this work on their side. I agree that dependabot isn't likely to look at the issue at all given the state of their bug tracker. I'll keep updating the submodules manually for now until we get some more insight on when pagure could be fixed.

**Comment by poettering** [comment] 2024-10-18 12:10
i guess this can be closed given that git submodule use was dropped in ba592dc715eed67b0c939ded94b4c31bc5ba1070

**Closed as completed by poettering** 2024-10-18 12:10 UTC
Labels: bug 🐛
