### ISSUE TITLE
systemctl link ./*.container  is not a valid unit name (podman)

### ISSUE THREAD

**Issue by gnat** [systemd/systemd#32543] opened 2024-04-29 04:50 UTC
### systemd version the issue has been seen with

255

### Used distribution

Ubuntu 24.04

### Linux kernel version used

6.8.0

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

```
gnat@gnat:~/Projects/systemd$ systemctl --user link ./*.container
Created symlink /home/gnat/.config/containers/systemd/user/memcached.container → /home/gnat/Projects/systemd/memcached.container.
```

### Unexpected behaviour you saw

```
gnat@gnat:~/Projects/systemd$ systemctl --user link ./*.container
Failed to link unit: "/home/gnat/Projects/systemd/memcached.container" is not a valid unit name.
```

### Steps to reproduce the problem

`sudo apt install podman` then try to `systemctl --user link` any `.container` unit

### Additional program output to the terminal or log subsystem illustrating the issue

`systemctl link` needs to be updated to handle `.container` files.

This only breaks if using `systemctl link` ... `.container` units work fine if you place it inside of a pre-determined directory (such as `~/.config/containers/systemd`)

**Comment by gnat** [comment] 2024-04-29 05:18
Note for readers, temporary workaround: Create the symbolic link manually...

`ln -s ~/Projects/systemd/memcached.container ~/.config/containers/systemd/`

This works, but sucks because you can't use `systemctl link ./*` to hook everything up automatically.

**Comment by YHNdnzj** [comment] 2024-04-29 05:19
Sorry, but `.container` is a podman thing. Such podman configs are turned into valid systemd units through a systemd generator provided by podman. They by themselves aren't valid systemd units.

Not a bug, closing.

**Closed as not planned** 2024-04-29 05:19 UTC
Labels: systemctl, not-a-bug
