### ISSUE TITLE
Limiting journald memory usage when storage=volatile 

### ISSUE THREAD

**Issue by dataselfservice** [systemd/systemd#18177] opened 2021-01-09 10:12 UTC
# Problem
Excess log might result in system out of memory (unusable). Info on bottom. Note: this refers to version 240, but I could not find any solutions on newer versions either. 

# Desired feature
Is is there way to limit RAM (rss especially) usage while in journald `volatile` mode?

# Details
## System details: 
```
# uname -rsm ; cat /etc/os-release ; cat /proc/meminfo | head -1 ; systemctl --version
Linux 4.19.94 armv5tejl
NAME=Buildroot
VERSION=2019.02.9
ID=buildroot
VERSION_ID=2019.02.9
PRETTY_NAME="Buildroot 2019.02.9"
MemTotal:         253420 kB
systemd 240
-PAM -AUDIT -SELINUX -IMA -APPARMOR -SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP -GCRYPT -GNUTLS -ACL -XZ -LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN -PCRE2 default-hierarchy=hybrid
# cat /etc/systemd/journald.conf 
[Journal]
Storage=volatile
```

## Issue details 
```
# systemctl restart systemd-journald && ps -o rss,vsz,comm|grep systemd-j
4924  14m systemd-journal
```
after some time feeding excess log: 
```
# ps -o rss,vsz,comm|grep systemd-j
50m  73m systemd-journal
```
and the system becomes unusable.

**Comment by poettering** [comment] 2021-01-18 16:45
journald mmaps a lot of stuff, i.e. the journal files. It doesn't actually "use" that much memory. RSS is just the stuff that is actually swapped in from that, but in case of memory pressure it's easily swapped out again, since file backed anyway.

RSS is simply a useless indicator for processes that use mmaping a lot. Please use some better metric.

Moreover Storage=volatile has no effect on RSS, because that just says that the backing files are to be stored in /run rathre than /var. /run is backed by tmpfs, and that won't affect RSS whatsoever. You can put limits on the disk space use in journald.conf, i.e. RuntimeMaxUse= and so on.

Anyway, closing this, since this whole issue appears to be a misunderstanding, and is not a bug report, but a support request anyway, for which this bug tracker is really wrong.

**Closed as completed by poettering** 2021-01-18 16:45 UTC
Labels: journal, misfiled, use-mailing-list-instead
