### ISSUE TITLE
Changing OnCalendar directive starts the unit it runs, despite not needing to.

### ISSUE THREAD

**Issue by BoyanHH** [systemd/systemd#14899] opened 2020-02-18 11:15 UTC
> systemd version the issue has been seen with

    241
> Used distribution

    Debian 10

> Expected behaviour you didn't see

I have a systemd timer setup with the following OnCalendar value:` OnCalendar=*-*-* 05:35:00`
Upon changing it to  `OnCalendar=*-*-* 06:35:00`

And running `systemctl daemon-reload` to reload the configuration the .service unit file ran by the timer activated(the script started). The .service file before running daemon-reload:

`Active: inactive (dead) since Tue 2020-02-18 05:35:08 EET; 5h 1min ago`

The .service file after running daemon-reload

`Active: inactive (dead) since Tue 2020-02-18 10:37:10 EET; 4s ago`

The .timer unit before running daemon-reload

`Trigger: Wed 2020-02-19 05:35:00 EET; 18h left`

After:

`Trigger: Wed 2020-02-19 06:35:00 EET; 19h left`

The .service file should not have activated after running daemon-reload. 

> Unexpected behaviour you saw

The timer trigger has the correct timestamp on when it should run next but the service unit started when i ran daemon-reload.  Despite it being ran already for that day and me moving the time 1 hour in the future for the next run.

> Steps to reproduce the problem

Change the OnCalendar value of a timer unit to the future. The .service unit controlled by it will start as soon as configuration is reloaded.

**Comment by BoyanHH** [comment] 2020-02-21 16:06
It seems that  the service only starts prematurely when you increase the OnCalendar value.
Example:
Changing it from   ` OnCalendar=*-*-* 05:36:00` to ` OnCalendar=*-*-* 05:37:00`
Will start the unit , but it won't start if you change it to `OnCalendar=*-*-* 05:34:00`

**Comment by Fanatique1337** [comment] 2020-06-01 09:29
Any news on this? I experience the same unexpected behavior and sometimes it is really frustrating that systemd runs a timed service twice in a day because of a reload. And it's hard to remember that we shouldn't change the designated time of the timer to a time in the future. Sometimes not doing that is not even an option, but we still don't want the service running twice a day because of it, since it creates problems in production for us.

**Comment by dtardon** [comment] 2023-06-08 08:28
Duplicate of #16732.

**Closed as not planned by dtardon** 2023-06-08 08:28 UTC
Labels: pid1, duplicate
