### ISSUE TITLE
%t don't follow $XDG_RUNTIME_DIR when using User= stanza

### ISSUE THREAD

**Issue by quentin9696** [systemd/systemd#32699] opened 2024-05-07 19:36 UTC
### systemd version the issue has been seen with

systemd 255 (255.5-4-arch)

### Used distribution

Archlinux

### Linux kernel version used

6.8.9-hardened1-1-hardened

### CPU architectures issue was seen on

x86_64

### Component

systemd-run

### Expected behaviour you didn't see

When using `User=` stanza in service unit, `%t` specifier should get the value of `$XDG_RUNTIME_DIR` as specified in the documentation. 
Actually, it get the value of the root user `/run` instead of `/run/user/<uid>`

### Unexpected behaviour you saw

When using `User=` stanza, `%t` is replace by the root value, instead of `$XDG_RUNTIME_DIR`

### Steps to reproduce the problem

1. Create a unit in `/etc/systemd/system` with the following content
```
[Service]
RemainAfterExit=yes
User=<my-user>
ExecStart=mkdir %t/foo
```
2. `systemctl daemon-reload`
3. `sudo systemctl start <my-unit.service>`
4. Get the issue (you should have a permission denied)

This works well with `--user` units. 

I also test it and repoduce it using Fedora CoreOs

**Comment by YHNdnzj** [comment] 2024-05-08 03:28
The specifier resolution happens at unit load time. Therefore they cannot be influenced by other settings, such as `User=`. `systemd.unit(5)` documents:

> This is either /run/ (for the system manager) or the path "$XDG_RUNTIME_DIR" resolves to (for user managers).

So the value is solely decided by the scope of the service manager.

See also: https://github.com/systemd/systemd/issues/30782

Not a bug, closing.

**Closed as completed** 2024-05-08 03:29 UTC
Labels: pid1, not-a-bug
