### ISSUE TITLE
OnFailure is triggered only when StartLimitBurst is reached on V249 but every time in V255. This is a bug or not documented.

### ISSUE THREAD

**Issue by amaddio** [systemd/systemd#33710] opened 2024-07-12 09:48 UTC
### systemd version the issue has been seen with

255 and 249

### Used distribution

Ubuntu 20.04 and Ubuntu 24.04

### Linux kernel version used

5.15.0-113-generic (Ubuntu 20.04) and 6.8.0-36-generic (Ubuntu 24.04)

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

`OnFailure` is triggered when `StartLimitBurst` is reached. As documented:

> "A space-separated list of one or more units that are activated when this unit enters the "failed" state."

### Unexpected behaviour you saw

`OnFailure` is triggered now every time the service is restarted (V255) . Before it was restarted as documented when the `StartLimitBurst` was reached (V249)

### Steps to reproduce the problem

Service file:

```sh
[Unit]
Description=Test service that reports error after 10 attempts in 100s
After=network.target
StartLimitIntervalSec=100s
StartLimitBurst=10
OnFailure=test-failure-handler@%N.service

[Service]
ExecStart=/bin/zsh -c "sleep 1 && echo 'Greetings from %H' && exit 1"
Restart=always
RestartSec=5
```

test-failure-handler@.service:

```sh
[Unit]
Description=Failure handler for %i

[Service]
Type=oneshot
# Perform some special action for when %i exits unexpectedly.
ExecStart=/usr/bin/systemctl reset-failed %i
ExecStart=/usr/bin/my_custom_handler.zsh %i
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
## Output on 249 (expected)

Jul 12 09:17:44 mega-apply-ai-web-01 systemd[1]: Started Test service that reports error after 10 attempts in 100s
Jul 12 09:17:45 mega-apply-ai-web-01 zsh[1024709]: Greetings from mega-apply-ai-web-01
Jul 12 09:17:45 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 09:17:45 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:17:50 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Scheduled restart job, restart counter is at 1.
Jul 12 09:17:50 mega-apply-ai-web-01 systemd[1]: Stopped Test service that reports error after 10 attempts in 100s
Jul 12 09:17:50 mega-apply-ai-web-01 systemd[1]: Started Test service that reports error after 10 attempts in 100s
Jul 12 09:17:51 mega-apply-ai-web-01 zsh[1024719]: Greetings from mega-apply-ai-web-01
Jul 12 09:17:51 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 09:17:51 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:17:56 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Scheduled restart job, restart counter is at 2.
Jul 12 09:17:56 mega-apply-ai-web-01 systemd[1]: Stopped Test service that reports error after 10 attempts in 100s
Jul 12 09:17:56 mega-apply-ai-web-01 systemd[1]: Started Test service that reports error after 10 attempts in 100s
Jul 12 09:17:57 mega-apply-ai-web-01 zsh[1024721]: Greetings from mega-apply-ai-web-01
Jul 12 09:17:57 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 09:17:57 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:18:03 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Scheduled restart job, restart counter is at 3.
Jul 12 09:18:03 mega-apply-ai-web-01 systemd[1]: Stopped Test service that reports error after 10 attempts in 100s
Jul 12 09:18:03 mega-apply-ai-web-01 systemd[1]: Started Test service that reports error after 10 attempts in 100s
Jul 12 09:18:04 mega-apply-ai-web-01 zsh[1024793]: Greetings from mega-apply-ai-web-01
Jul 12 09:18:04 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 09:18:04 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:18:09 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Scheduled restart job, restart counter is at 4.
Jul 12 09:18:09 mega-apply-ai-web-01 systemd[1]: Stopped Test service that reports error after 10 attempts in 100s
Jul 12 09:18:09 mega-apply-ai-web-01 systemd[1]: Started Test service that reports error after 10 attempts in 100s
Jul 12 09:18:10 mega-apply-ai-web-01 zsh[1024796]: Greetings from mega-apply-ai-web-01
Jul 12 09:18:10 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 09:18:10 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:18:15 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Scheduled restart job, restart counter is at 5.
Jul 12 09:18:15 mega-apply-ai-web-01 systemd[1]: Stopped Test service that reports error after 10 attempts in 100s
Jul 12 09:18:15 mega-apply-ai-web-01 systemd[1]: Started Test service that reports error after 10 attempts in 100s
Jul 12 09:18:16 mega-apply-ai-web-01 zsh[1024798]: Greetings from mega-apply-ai-web-01
Jul 12 09:18:16 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 09:18:16 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:18:21 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Scheduled restart job, restart counter is at 6.
Jul 12 09:18:21 mega-apply-ai-web-01 systemd[1]: Stopped Test service that reports error after 10 attempts in 100s
Jul 12 09:18:21 mega-apply-ai-web-01 systemd[1]: Started Test service that reports error after 10 attempts in 100s
Jul 12 09:18:22 mega-apply-ai-web-01 zsh[1024800]: Greetings from mega-apply-ai-web-01
Jul 12 09:18:22 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 09:18:22 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:18:28 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Scheduled restart job, restart counter is at 7.
Jul 12 09:18:28 mega-apply-ai-web-01 systemd[1]: Stopped Test service that reports error after 10 attempts in 100s
Jul 12 09:18:28 mega-apply-ai-web-01 systemd[1]: Started Test service that reports error after 10 attempts in 100s
Jul 12 09:18:29 mega-apply-ai-web-01 zsh[1024802]: Greetings from mega-apply-ai-web-01
Jul 12 09:18:29 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 09:18:29 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:18:34 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Scheduled restart job, restart counter is at 8.
Jul 12 09:18:34 mega-apply-ai-web-01 systemd[1]: Stopped Test service that reports error after 10 attempts in 100s
Jul 12 09:18:34 mega-apply-ai-web-01 systemd[1]: Started Test service that reports error after 10 attempts in 100s
Jul 12 09:18:35 mega-apply-ai-web-01 zsh[1024805]: Greetings from mega-apply-ai-web-01
Jul 12 09:18:35 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 09:18:35 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:18:40 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Scheduled restart job, restart counter is at 9.
Jul 12 09:18:40 mega-apply-ai-web-01 systemd[1]: Stopped Test service that reports error after 10 attempts in 100s
Jul 12 09:18:40 mega-apply-ai-web-01 systemd[1]: Started Test service that reports error after 10 attempts in 100s
Jul 12 09:18:41 mega-apply-ai-web-01 zsh[1024807]: Greetings from mega-apply-ai-web-01
Jul 12 09:18:41 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 09:18:41 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:18:46 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Scheduled restart job, restart counter is at 10.
Jul 12 09:18:46 mega-apply-ai-web-01 systemd[1]: Stopped Test service that reports error after 10 attempts in 100s
Jul 12 09:18:46 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Start request repeated too quickly.
Jul 12 09:18:46 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:18:46 mega-apply-ai-web-01 systemd[1]: Failed to start Test service that reports error after 10 attempts in 100s
Jul 12 09:18:46 mega-apply-ai-web-01 systemd[1]: test-slack-reporting.service: Triggering OnFailure= dependencies.



## Output on 255 (unexpected)

Jul 12 09:03:13 mega-apply-ai-preprocessor-03-2404 systemd[1]: Started test-slack-reporting.service - Test Slack error reporting service.
Jul 12 09:03:14 mega-apply-ai-preprocessor-03-2404 zsh[884165]: Greetings from mega-apply-ai-preprocessor-03-2404
Jul 12 09:03:14 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 09:03:14 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:03:14 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Triggering OnFailure= dependencies.
Jul 12 09:03:19 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Scheduled restart job, restart counter is at 1.
Jul 12 09:03:19 mega-apply-ai-preprocessor-03-2404 systemd[1]: Started test-slack-reporting.service - Test Slack error reporting service.
Jul 12 09:03:20 mega-apply-ai-preprocessor-03-2404 zsh[884179]: Greetings from mega-apply-ai-preprocessor-03-2404
Jul 12 09:03:20 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 09:03:20 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:03:20 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Triggering OnFailure= dependencies.
Jul 12 09:03:25 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Scheduled restart job, restart counter is at 2.
Jul 12 09:03:25 mega-apply-ai-preprocessor-03-2404 systemd[1]: Started test-slack-reporting.service - Test Slack error reporting service.
Jul 12 09:03:26 mega-apply-ai-preprocessor-03-2404 zsh[884185]: Greetings from mega-apply-ai-preprocessor-03-2404
Jul 12 09:03:26 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 09:03:26 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:03:26 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Triggering OnFailure= dependencies.
Jul 12 09:03:32 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Scheduled restart job, restart counter is at 3.
Jul 12 09:03:32 mega-apply-ai-preprocessor-03-2404 systemd[1]: Started test-slack-reporting.service - Test Slack error reporting service.
Jul 12 09:03:33 mega-apply-ai-preprocessor-03-2404 zsh[884190]: Greetings from mega-apply-ai-preprocessor-03-2404
Jul 12 09:03:33 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 09:03:33 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:03:33 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Triggering OnFailure= dependencies.
Jul 12 09:03:38 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Scheduled restart job, restart counter is at 4.
Jul 12 09:03:38 mega-apply-ai-preprocessor-03-2404 systemd[1]: Started test-slack-reporting.service - Test Slack error reporting service.
Jul 12 09:03:39 mega-apply-ai-preprocessor-03-2404 zsh[884195]: Greetings from mega-apply-ai-preprocessor-03-2404
Jul 12 09:03:39 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 09:03:39 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:03:39 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Triggering OnFailure= dependencies.
Jul 12 09:03:44 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Scheduled restart job, restart counter is at 5.
Jul 12 09:03:44 mega-apply-ai-preprocessor-03-2404 systemd[1]: Started test-slack-reporting.service - Test Slack error reporting service.
Jul 12 09:03:45 mega-apply-ai-preprocessor-03-2404 zsh[884200]: Greetings from mega-apply-ai-preprocessor-03-2404
Jul 12 09:03:45 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 09:03:45 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:03:45 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Triggering OnFailure= dependencies.
Jul 12 09:03:50 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Scheduled restart job, restart counter is at 6.
Jul 12 09:03:50 mega-apply-ai-preprocessor-03-2404 systemd[1]: Started test-slack-reporting.service - Test Slack error reporting service.
Jul 12 09:03:51 mega-apply-ai-preprocessor-03-2404 zsh[884206]: Greetings from mega-apply-ai-preprocessor-03-2404
Jul 12 09:03:51 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 09:03:51 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:03:51 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Triggering OnFailure= dependencies.
Jul 12 09:03:57 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Scheduled restart job, restart counter is at 7.
Jul 12 09:03:57 mega-apply-ai-preprocessor-03-2404 systemd[1]: Started test-slack-reporting.service - Test Slack error reporting service.
Jul 12 09:03:58 mega-apply-ai-preprocessor-03-2404 zsh[884211]: Greetings from mega-apply-ai-preprocessor-03-2404
Jul 12 09:03:58 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 09:03:58 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:03:58 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Triggering OnFailure= dependencies.
Jul 12 09:04:03 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Scheduled restart job, restart counter is at 8.
Jul 12 09:04:03 mega-apply-ai-preprocessor-03-2404 systemd[1]: Started test-slack-reporting.service - Test Slack error reporting service.
Jul 12 09:04:04 mega-apply-ai-preprocessor-03-2404 zsh[884262]: Greetings from mega-apply-ai-preprocessor-03-2404
Jul 12 09:04:04 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 09:04:04 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:04:04 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Triggering OnFailure= dependencies.
Jul 12 09:04:09 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Scheduled restart job, restart counter is at 9.
Jul 12 09:04:09 mega-apply-ai-preprocessor-03-2404 systemd[1]: Started test-slack-reporting.service - Test Slack error reporting service.
Jul 12 09:04:10 mega-apply-ai-preprocessor-03-2404 zsh[884269]: Greetings from mega-apply-ai-preprocessor-03-2404
Jul 12 09:04:10 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Main process exited, code=exited, status=1/FAILURE
Jul 12 09:04:10 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:04:10 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Triggering OnFailure= dependencies.
Jul 12 09:04:15 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Scheduled restart job, restart counter is at 10.
Jul 12 09:04:15 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Start request repeated too quickly.
Jul 12 09:04:15 mega-apply-ai-preprocessor-03-2404 systemd[1]: test-slack-reporting.service: Failed with result 'exit-code'.
Jul 12 09:04:15 mega-apply-ai-preprocessor-03-2404 systemd[1]: Failed to start test-slack-reporting.service - Test Slack error reporting service.
```

**Comment by YHNdnzj** [comment] 2024-07-12 09:56
> "A space-separated list of one or more units that are activated when this unit enters the "failed" state."

Before restarting, the service does enter `failed` state. The previous behavior is a bug.  You can use `RestartMode=direct` to restore the previous behavior.

Not a bug, closing.

**Closed as completed** 2024-07-12 09:56 UTC
Labels: pid1, not-a-bug
