### ISSUE TITLE
systemd kills process that migrated to some other unit on actions like Stop

### ISSUE THREAD

**Issue by bl33pbl0p** [systemd/systemd#10761] opened 2018-11-13 14:36 UTC
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Debian GNU/Linux buster/sid

**Expected behaviour you didn't see**
 > systemd stopping the unit but not killing the PID that resided in that unit earlier.

**Unexpected behaviour you saw**
 > systemd kills the process that migrated to some other unit despite the current unit being empty.

**Steps to reproduce the problem**
Perhaps this is something that confuses PID1, but the behavior still looks wrong to me.

Have a script like this:
```bash
systemd-run -p User=root -p CollectMode=inactive-or-failed -q -t --unit=root-session.service su -l root
```

su goes through the pam stack where pam_systemd then puts the process in its own session scope (and then you get a pristine login shell);

https://i.imgur.com/1kuwuO4.png

Notice PID 5648 (su -l root), Tasks: 0 in the original root-session unit, and the su process in the session scope now.

On stopping root-session.service, I would expect it to do nothing as the process does not belong to that unit anymore, but since systemd knows the PID from its bookkeeping, it kills that PID which tears down the session.

**Comment by poettering** [comment] 2018-11-15 08:43
This is by design. When it comes to enumerating processes for display and killing, systemd will consider 

1. all processes in the unit's cgroup
2. the "main" process if there is one (in case it's not already covered by the cgroup)
3. the "control" process if there is one (similar)

When you do "systemctl status" on a service whose main or control process migrated elsewhere and look at the cgroup process tree part of the output, you'll find the process listed there, prefixed with "‣" instead of the usual tree structure, since they are somewhat apart from the regular processes, as they are not part of the cgroup, but still are tracked for the service.

And we really have to do it this way, as for services the main and control processes define the lifecycle of the service, and if we want to influence the lifecycle of the service we do so by requesting operations on the main process (through the control processes if defined).

Note that if you migrate any other process out of a service, i.e. one that is neither control nor main process, then it will actually disappear from the tracking that systemd does, and systemd won't notice nor care for it.

Note that this has interesting effects: a process might show up as a member of two different units, once in the original where systemd forked it off, and once in another one it joined by migrating to its cgroup.

Anyway, this is really by design, and in order to correctly track things for lifecycle purposes I see no other way we could do this. Hence, closing. I hope that makes some sense.

**Closed as completed by poettering** 2018-11-15 08:43 UTC
Labels: pid1, not-a-bug

**Comment by bl33pbl0p** [comment] 2018-11-15 09:57
@poettering

It does make sense. Thank you for the explanation. I figure that also means the main process that migrated elsewhere changes its state will also affect the original unit and cause it to change state when it dies trigger other things.

How does this interact with settings the other "Unit" has wrt sd_notify, does migration only affect cgroup specific properties of the process or does it affect anything else that was defined in the original service?

Though I feel things like resource limits by cgroup might (and set-property and friends) break when the main process migrates elsewhere, because changing them for that service no longer applies to the process.
