### ISSUE TITLE
strange output systemd-analyze blame

### ISSUE THREAD

**Issue by jamestho** [systemd/systemd#15074] opened 2020-03-10 22:20 UTC
**systemd version the issue has been seen with**
systemd 245 (245-1 and 245-2-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > A list of start-up times by service

**Unexpected behaviour you saw**
```
[james@alisaie ~]$ systemd-analyze blame
2y 11month 3w 5d 4h 54min 31.222s upower.service                                                                           
2y 11month 3w 5d 4h 54min 31.222s lm_sensors.service                                                                       
2y 11month 3w 5d 4h 54min 31.222s ufw.service                                                                              
2y 11month 3w 5d 4h 54min 31.221s udisks2.service                                                                          
2y 11month 3w 5d 4h 54min 31.221s systemd-networkd.service                                                                 
2y 11month 3w 5d 4h 54min 31.221s modprobe@drm.service                                                                     
2y 11month 3w 5d 4h 54min 31.221s systemd-update-utmp.service                                                              
2y 11month 3w 5d 4h 54min 31.221s netctl-auto@wlan0.service                                                                
2y 11month 3w 5d 4h 54min 31.221s systemd-userdbd.service                                                                  
2y 11month 3w 5d 4h 54min 31.220s systemd-fsck@dev-disk-by\x2duuid-bf6271e9\x2d5118\x2d4e2d\x2d9eb6\x2d6f57098d9c5b.service
2y 11month 3w 5d 4h 54min 31.220s sys-kernel-config.mount                                                                  
2y 11month 3w 5d 4h 54min 31.220s systemd-remount-fs.service                                                               
2y 11month 3w 5d 4h 54min 31.220s home.mount                                                                               
2y 11month 3w 5d 4h 54min 31.220s systemd-journald.service                                                                 
2y 11month 3w 5d 4h 54min 31.219s systemd-udev-trigger.service                                                             
2y 11month 3w 5d 4h 54min 31.219s powertop.service                                                                         
2y 11month 3w 5d 4h 54min 31.219s systemd-journal-catalog-update.service                                                   
2y 11month 3w 5d 4h 54min 31.219s ldconfig.service                                                                         
2y 11month 3w 5d 4h 54min 31.219s tmp.mount                                                                                
2y 11month 3w 5d 4h 54min 31.219s org.cups.cupsd.service                                                                   
2y 11month 3w 5d 4h 54min 31.218s systemd-modules-load.service                                                             
2y 11month 3w 5d 4h 54min 31.218s kmod-static-nodes.service                                                                
2y 11month 3w 5d 4h 54min 31.218s dev-mqueue.mount                                                                         
2y 11month 3w 5d 4h 54min 31.218s systemd-logind.service                                                                   
2y 11month 3w 5d 4h 54min 31.218s systemd-tmpfiles-setup-dev.service                                                       
2y 11month 3w 5d 4h 54min 31.217s systemd-udevd.service                                                                    
2y 11month 3w 5d 4h 54min 31.216s systemd-random-seed.service                                                              
2y 11month 3w 5d 4h 54min 31.216s tlp.service                                                                              
2y 11month 3w 5d 4h 54min 31.216s user@1000.service                                                                        
2y 11month 3w 5d 4h 54min 31.216s systemd-user-sessions.service                                                            
2y 11month 3w 5d 4h 54min 31.216s systemd-backlight@backlight:intel_backlight.service                                      
2y 11month 3w 5d 4h 54min 31.216s boot.mount                                                                               
2y 11month 3w 5d 4h 54min 31.215s wpa_supplicant.service                                                                   
2y 11month 3w 5d 4h 54min 31.215s systemd-fsck@dev-disk-by\x2duuid-7F82\x2d0969.service                                    
2y 11month 3w 5d 4h 54min 31.215s systemd-rfkill.service                                                                   
2y 11month 3w 5d 4h 54min 31.215s systemd-repart.service                                                                   
2y 11month 3w 5d 4h 54min 31.215s colord.service                                                                           
2y 11month 3w 5d 4h 54min 31.215s systemd-tmpfiles-setup.service                                                           
2y 11month 3w 5d 4h 54min 31.214s lvm2-monitor.service                                                                     
2y 11month 3w 5d 4h 54min 31.214s dev-hugepages.mount                                                                      
2y 11month 3w 5d 4h 54min 31.214s systemd-homed.service                                                                    
2y 11month 3w 5d 4h 54min 31.214s systemd-sysusers.service                                                                 
2y 11month 3w 5d 4h 54min 31.214s rtkit-daemon.service                                                                     
2y 11month 3w 5d 4h 54min 31.214s sys-kernel-debug.mount                                                                   
2y 11month 3w 5d 4h 54min 31.214s systemd-sysctl.service                                                                   
2y 11month 3w 5d 4h 54min 31.213s dev-sda2.device                                                                          
2y 11month 3w 5d 4h 54min 31.213s systemd-timesyncd.service                                                                
2y 11month 3w 5d 4h 54min 31.213s smtpd.service                                                                            
2y 11month 3w 5d 4h 54min 31.213s systemd-update-done.service                                                              
2y 11month 3w 5d 4h 54min 31.213s sys-kernel-tracing.mount                                                                 
2y 11month 3w 5d 4h 54min 31.213s dev-disk-by\x2duuid-b10ebcb8\x2d14d8\x2d4d8b\x2d928a\x2d53bd21007c10.swap                
2y 11month 3w 5d 4h 54min 31.213s polkit.service                                                                           
2y 11month 3w 5d 4h 54min 31.213s user-runtime-dir@1000.service                                                            
2y 11month 3w 5d 4h 54min 31.212s packagekit.service                                                                       
2y 11month 3w 5d 4h 54min 31.212s systemd-resolved.service                                                                 
2y 11month 3w 5d 4h 54min 31.212s systemd-journal-flush.service 
```
**Steps to reproduce the problem**
type `systemd-analyze blame`at the CLI

**Comment by mbiebl** [comment] 2020-03-10 22:26
another duplicate of #14830

**Closed as completed by mbiebl** 2020-03-10 22:26 UTC
Labels: duplicate
