### ISSUE TITLE
systemd-networkd:Usually within a week I lose my IP address.

### ISSUE THREAD

**Issue by daiaji** [systemd/systemd#23642] opened 2022-06-06 12:47 UTC
**systemd version the issue has been seen with**
 > systemd 251

**Used distribution**
 > manjaro

**Linux kernel version used** (`uname -a`)

 > `Linux AIO 5.17.11-1-ACS-MANJARO #1 SMP PREEMPT Sat May 28 22:15:43 CST 2022 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > so that my IP address is no longer lost.

**Unexpected behaviour you saw**
 > The IP address was accidentally lost.

**Steps to reproduce the problem**
 > Use systemd-networkd for a long time.

**Additional program output to the terminal or log subsystem illustrating the issue**

https://gist.github.com/daiaji/058f96245555ad45a2c83cceae1c82dc

**Comment by daiaji** [comment] 2022-06-09 10:06
https://github.com/systemd/systemd/issues/23625
Looks like a similar glitch.

**Comment by yuwata** [comment] 2022-06-27 03:51
Yeah, duplicate of #23642. Closing.

**Closed as completed by yuwata** 2022-06-27 03:51 UTC
Labels: bug 🐛, network, duplicate
