### ISSUE TITLE
resolvectl query sometimes fails for Microsoft DNS server when TTL becomes 0

### ISSUE THREAD

**Issue by net147** [systemd/systemd#20617] opened 2021-09-02 06:30 UTC
**systemd version the issue has been seen with**
 > v249.4, fad45198b6a640ca39dd37d38c0d9c209b748758

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)

 > `Linux client 5.13.13-zen1-1-zen #1 ZEN SMP PREEMPT Thu, 26 Aug 2021 19:14:35 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > $ resolvectl query server-cname.addomain
 > server-cname.addomain: 192.168.0.2     -- link: eth0 
 >                                 (server.addomain) 
 > 
 > -- Information acquired via protocol DNS in 1.2ms. 
 > -- Data is authenticated: no; Data was acquired via local or encrypted transport: no 
 > -- Data from: cache 

**Unexpected behaviour you saw**
 > $ resolvectl query server-cname.addomain
 > server-cname.addomain: resolve call failed: Lookup failed due to system error: Invalid argument

**Steps to reproduce the problem**
 > $ while true; do resolvectl query server-cname.addomain; sleep 0.1; done

server-cname.addomain is a CNAME record (TTL 1) to server.addomain A record (TTL 3600). The DNS server is Windows Server 2019.
It seems the TTL returned from Windows Server counts down to 0 before wrapping around. This is different from dnsmasq which counts down to 1 before wrapping around.

The issue seems to be in https://github.com/systemd/systemd/blob/9fffe0a912d566f433483f1505caf7f8f59767a5/src/resolve/resolved-dns-answer.c#L164-L168 when rr->ttl is 1 and exist->rr->ttl is 0 so the dns_answer_add function returns -EINVAL and the resolvectl DNS query fails.

**Additional program output to the terminal or log subsystem illustrating the issue**

 > Sep 02 14:26:03 client systemd-resolved[642]: Sent message type=error sender=n/a destination=:1.270 path=n/a interface=n/a member=n/a cookie=685 reply_cookie=2 signature=s error-name=org.freedesktop.DBus.Error.InvalidArgs error-message=Lookup failed due to system error: Invalid argument

**Comment by smurfix** [comment] 2021-09-22 08:13
Looks like this test should simply be removed.

**Comment by clem4962** [comment] 2021-09-29 11:08
I have had a similar issue on Linux, where I have both ipv4 and ipv6 enabled; resolved sends two parallel A and AAAA queries, which occasionally return CNAME responses with different TTLs - both queries are successful but the query fails in the TTL check highlighted above.

In this particular case, I have a script running every 12 minutes and it fails intermittently, several times a day.

tcpdump:

```
2021-09-29 11:03:02.725349 ens5  Out IP (tos 0x0, ttl 64, id 23910, offset 0, flags [none], proto UDP (17), length 80)
    xxxxxx.com.47243 > 172.30.0.2.domain: [bad udp cksum 0x59c5 -> 0x4aee!] 40092+% [1au] AAAA? ticketing.almeida.co.uk. ar: . OPT UDPsize=512 (52)
2021-09-29 11:03:02.725466 ens5  Out IP (tos 0x0, ttl 64, id 23911, offset 0, flags [none], proto UDP (17), length 80)
    xxxxxx.com.59153 > 172.30.0.2.domain: [bad udp cksum 0x59c5 -> 0xcc05!] 2047+% [1au] A? ticketing.almeida.co.uk. ar: . OPT UDPsize=512 (52)
2021-09-29 11:03:02.747408 ens5  In  IP (tos 0x0, ttl 255, id 0, offset 0, flags [DF], proto UDP (17), length 171)
    172.30.0.2.domain > xxxxxx.com.59153: [udp sum ok] 2047 q: A? ticketing.almeida.co.uk. 3/0/1 ticketing.almeida.co.uk. [0s] CNAME alme-tnew-prod.tnhs.cloud., alme-tnew-prod.tnhs.cloud. [48m] CNAME 9whh7ex.x.incapdns.net., 9whh7ex.x.incapdns.net. [30s] A 45.60.123.73 ar: . OPT UDPsize=4096 (143)
2021-09-29 11:03:02.750305 ens5  In  IP (tos 0x0, ttl 255, id 0, offset 0, flags [DF], proto UDP (17), length 232)
    172.30.0.2.domain > xxxxxx.com.47243: [udp sum ok] 40092 q: AAAA? ticketing.almeida.co.uk. 2/1/1 ticketing.almeida.co.uk. [36m] CNAME alme-tnew-prod.tnhs.cloud., alme-tnew-prod.tnhs.cloud. [48m] CNAME 9whh7ex.x.incapdns.net. ns: incapdns.net. [21s] SOA ns1.incapdns.net.incapdns.net. hostmaster.incapsula.com. 1001 3600 600 604800 300 ar: . OPT UDPsize=4096 (204)
```

debug:


```
Sep 29 11:03:02.724900 xxxxxx.com systemd-resolved[267376]: varlink: New incoming connection.
Sep 29 11:03:02.724934 xxxxxx.com systemd-resolved[267376]: varlink: Connections of user 1512: 0 (of 576 max)
Sep 29 11:03:02.724943 xxxxxx.com systemd-resolved[267376]: varlink-21: Setting state idle-server
Sep 29 11:03:02.724988 xxxxxx.com systemd-resolved[267376]: varlink-21: New incoming message: {"method":"io.systemd.Resolve.ResolveHostname","parameters":{"name":"ticketing.almeida.co.uk","flags":0}}
Sep 29 11:03:02.725016 xxxxxx.com systemd-resolved[267376]: varlink-21: Changing state idle-server → processing-method
Sep 29 11:03:02.725062 xxxxxx.com systemd-resolved[267376]: idn2_lookup_u8: ticketing.almeida.co.uk → ticketing.almeida.co.uk
Sep 29 11:03:02.725083 xxxxxx.com systemd-resolved[267376]: Looking up RR for ticketing.almeida.co.uk IN A.
Sep 29 11:03:02.725088 xxxxxx.com systemd-resolved[267376]: Looking up RR for ticketing.almeida.co.uk IN AAAA.
Sep 29 11:03:02.725192 xxxxxx.com systemd-resolved[267376]: Cache miss for ticketing.almeida.co.uk IN AAAA
Sep 29 11:03:02.725200 xxxxxx.com systemd-resolved[267376]: Regular transaction 40092 for <ticketing.almeida.co.uk IN AAAA> scope dns on ens5/* (validate=yes).
Sep 29 11:03:02.725223 xxxxxx.com systemd-resolved[267376]: Using feature level UDP+EDNS0 for transaction 40092.
Sep 29 11:03:02.725231 xxxxxx.com systemd-resolved[267376]: Using DNS server 172.30.0.2 for transaction 40092.
Sep 29 11:03:02.725296 xxxxxx.com systemd-resolved[267376]: Announcing packet size 512 in egress EDNS(0) packet.
Sep 29 11:03:02.725306 xxxxxx.com systemd-resolved[267376]: Emitting UDP, link MTU is 9001, socket MTU is 0, minimal MTU is 40
Sep 29 11:03:02.725312 xxxxxx.com systemd-resolved[267376]: Sending query packet with id 40092 of size 52.
Sep 29 11:03:02.725385 xxxxxx.com systemd-resolved[267376]: Cache miss for ticketing.almeida.co.uk IN A
Sep 29 11:03:02.725392 xxxxxx.com systemd-resolved[267376]: Regular transaction 65287 for <ticketing.almeida.co.uk IN A> scope dns on ens5/* (validate=yes).
Sep 29 11:03:02.725408 xxxxxx.com systemd-resolved[267376]: Using feature level UDP+EDNS0 for transaction 65287.
Sep 29 11:03:02.725413 xxxxxx.com systemd-resolved[267376]: Using DNS server 172.30.0.2 for transaction 65287.
Sep 29 11:03:02.725443 xxxxxx.com systemd-resolved[267376]: Announcing packet size 512 in egress EDNS(0) packet.
Sep 29 11:03:02.725451 xxxxxx.com systemd-resolved[267376]: Emitting UDP, link MTU is 9001, socket MTU is 0, minimal MTU is 40
Sep 29 11:03:02.725456 xxxxxx.com systemd-resolved[267376]: Sending query packet with id 65287 of size 52.
Sep 29 11:03:02.747884 xxxxxx.com systemd-resolved[267376]: Received dns UDP packet of size 143, ifindex=2, ttl=0, fragsize=0
Sep 29 11:03:02.747892 xxxxxx.com systemd-resolved[267376]: Processing incoming packet of size 143 on transaction 65287 (rcode=SUCCESS).
Sep 29 11:03:02.747970 xxxxxx.com systemd-resolved[267376]: Not validating response for 65287, used server feature level does not support DNSSEC.
Sep 29 11:03:02.747991 xxxxxx.com systemd-resolved[267376]: Not caching zero TTL cache entry: ticketing.almeida.co.uk IN CNAME
Sep 29 11:03:02.748043 xxxxxx.com systemd-resolved[267376]: Added positive unauthenticated non-confidential cache entry for alme-tnew-prod.tnhs.cloud IN CNAME 2880s on ens5/INET/172.30.0.2
Sep 29 11:03:02.748066 xxxxxx.com systemd-resolved[267376]: Added positive unauthenticated non-confidential cache entry for 9whh7ex.x.incapdns.net IN A 30s on ens5/INET/172.30.0.2
Sep 29 11:03:02.748076 xxxxxx.com systemd-resolved[267376]: Regular transaction 65287 for <ticketing.almeida.co.uk IN A> on scope dns on ens5/* now complete with <success> from network (unsigned; non-confidential).
Sep 29 11:03:02.750393 xxxxxx.com systemd-resolved[267376]: Received dns UDP packet of size 204, ifindex=2, ttl=0, fragsize=0
Sep 29 11:03:02.750401 xxxxxx.com systemd-resolved[267376]: Processing incoming packet of size 204 on transaction 40092 (rcode=SUCCESS).
Sep 29 11:03:02.750478 xxxxxx.com systemd-resolved[267376]: Not validating response for 40092, used server feature level does not support DNSSEC.
Sep 29 11:03:02.750542 xxxxxx.com systemd-resolved[267376]: Added positive unauthenticated non-confidential cache entry for ticketing.almeida.co.uk IN CNAME 21s on ens5/INET/172.30.0.2
Sep 29 11:03:02.750564 xxxxxx.com systemd-resolved[267376]: Added positive unauthenticated non-confidential cache entry for alme-tnew-prod.tnhs.cloud IN CNAME 2880s on ens5/INET/172.30.0.2
Sep 29 11:03:02.750574 xxxxxx.com systemd-resolved[267376]: Regular transaction 40092 for <ticketing.almeida.co.uk IN AAAA> on scope dns on ens5/* now complete with <success> from network (unsigned; non-confidential).
Sep 29 11:03:02.751095 xxxxxx.com systemd-resolved[267376]: Freeing transaction 65287.
Sep 29 11:03:02.751151 xxxxxx.com systemd-resolved[267376]: varlink-21: Sending message: {"error":"io.systemd.System","parameters":{"errno":22}}
Sep 29 11:03:02.751158 xxxxxx.com systemd-resolved[267376]: varlink-21: Changing state pending-method → idle-server
Sep 29 11:03:02.751168 xxxxxx.com systemd-resolved[267376]: Freeing transaction 40092.
Sep 29 11:03:02.752921 xxxxxx.com systemd-resolved[267376]: varlink-21: Got POLLHUP from socket.
Sep 29 11:03:02.752944 xxxxxx.com systemd-resolved[267376]: varlink-21: Changing state idle-server → pending-disconnect
Sep 29 11:03:02.752957 xxxxxx.com systemd-resolved[267376]: varlink-21: Changing state pending-disconnect → processing-disconnect
Sep 29 11:03:02.752963 xxxxxx.com systemd-resolved[267376]: varlink-21: Changing state processing-disconnect → disconnected
```

**Comment by eworm-de** [comment] 2022-02-04 12:37
I see this with MikroTik DNS server where TTL for one response is zero...
Dumped an example with [query and response for "ftp.mozilla.org"](https://github.com/systemd/systemd/files/8003012/cname.pcap.gz)...

**Comment by polaris64** [comment] 2022-02-04 13:10
As this check was [originally added 6 years ago](https://github.com/systemd/systemd/commit/7feea00bb06bca94545d5682930c11a6dee9c642), I wonder if it's due to a DNS server which has started misbehaving. Perhaps others could report which DNS servers they are using here and maybe there'll be a correlation?

For me it is: -

```
$ resolvectl status
[...]
Link 4 (wlp10s0f3u3)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 1.1.1.1
       DNS Servers: 1.1.1.1 1.0.0.1
        DNS Domain: Home
[...]
```

**Comment by eworm-de** [comment] 2022-02-04 13:18
Well, the MikroTik Router is configured to use 1.1.1.1 as well...

**Comment by polaris64** [comment] 2022-02-04 13:33
@eworm-de, I've just taken a look at your pcap. I see two responses for the queries for `ftp.mozilla.org`, one in response to an `A` query and one for `AAAA`. Both responses contain a `CNAME` record with `d34chcsvb7ug62.cloudfront.net` as a value, however one has a TTL of 0 and one has a TTL of 30.

Looking at the code linked above, I'm wondering if these two answers are considered to be in the same RR set and therefore are triggering this error?

**Comment by polaris64** [comment] 2022-02-04 13:34
Ah, just realised you mentioned that too in your comment above, so it looks like we both reached the same conclusion :)

**Comment by eworm-de** [comment] 2022-02-04 13:35
Yes, we did. 😜

And I guess this is an issue with Cloudflare DNS... Just changed my upstream servers.

**Comment by polaris64** [comment] 2022-02-04 13:38
OK, let us know if you encounter the same issues with different upstream servers too!

**Comment by eworm-de** [comment] 2022-02-04 13:41
Guess I will not. It's easy to query cloudflare dns and get a response where TTL is zero:

```
eworm@leda ~ % dig AAAA ftp.mozilla.org @1.1.1.1 

; <<>> DiG 9.16.25 <<>> AAAA ftp.mozilla.org @1.1.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33052
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;ftp.mozilla.org.		IN	AAAA

;; ANSWER SECTION:
ftp.mozilla.org.	0	IN	CNAME	d34chcsvb7ug62.cloudfront.net.

;; AUTHORITY SECTION:
d34chcsvb7ug62.cloudfront.net. 16 IN	SOA	ns-1609.awsdns-09.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 36 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Fri Feb 04 14:39:58 CET 2022
;; MSG SIZE  rcvd: 174
```

Could not reproduce this with other upstream servers.

**Comment by eworm-de** [comment] 2022-02-04 13:47
Though I think the original issue may be caused by something else...

I started to see this earlier this year, but not in September last year. 
For sure #22177 and #22348 describe the Cloudflare issue.

**Comment by polaris64** [comment] 2022-02-08 14:08
@eworm-de, I saw your post on the Cloudflare community forum, so I've just [contacted Cloudflare via Twitter](https://twitter.com/polaris64/status/1491038384667590660) to let them know about it.

**Comment by eworm-de** [comment] 2022-02-08 14:13
Good idea, thanks!
I had hoped they take care of it in the community forum... No idea if they do.

**Comment by eworm-de** [comment] 2022-02-09 10:54
Until the issue is fixed by Cloudflare I use Quad9. The situation is a lot better there, but I still see the issue in very rare cases.

Wondering if the check should be dropped... Would it cause any harm?

**Comment by kiancross** [comment] 2023-08-14 17:22
Does anybody know is this has been resolved? I've suddenly started experiencing it.

**Comment by dacioromero** [comment] 2023-09-14 00:57
I subscribed to this issue but never gave my experience. I ran into this issue when using Unbound  with a Redis cache and `serve-expired-reply-ttl` set (among other settings) for my network's DNS. I observed the following warning from Unbound:

> warning: cachedb: serve-expired-reply-ttl is set but not working for data originating from the external cache; 0 TLL is used for those.

This means that systemd-resolved would receive a 0 TTL and have the same issue others have observed.

**Closed as completed** 2023-10-02 14:47 UTC
Labels: resolve
