### ISSUE TITLE
systemctl daemon-reload

### ISSUE THREAD

**Issue by tanmaymanolkar1** [systemd/systemd#30354] opened 2023-12-06 22:13 UTC
### systemd version the issue has been seen with

252-13.el9_2

### Used distribution

RHEL 9.2

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

Expecting the daemon-reload to occur after the rpm package upgrade, any suggestions are appreciated

### Unexpected behaviour you saw

I have to manually run 
systemctl --system daemon-reload
systemctl --system try-restart <a_system>.service
systemctl --userdaemon-reload
systemctl --usertry-restart <a_user>.service

OR

If I logout and log back in the upgrade works as expected (I am trying to avoid this and do it programatically)

### Steps to reproduce the problem

Attaching my install scripts

%post:
systemd-sysusers /usr/lib/sysusers.d/a.conf
systemctl reload dbus
%systemd_post <a_system>.service
%systemd_user_post <a_user>.service

%preun
%systemd_preun <a_system>.service
%systemd_user_preun <a_user>.service

%postUn
systemctl --user daemon-reload
systemctl --system daemon-reload
(restarting the services)
%systemd_postun_with_restart <a_system>.service
%systemd_user_postun_with_restart <a_user>.service
rm -rf <file_cleanup>

**Comment by Werkov** [comment] 2023-12-07 15:10
> 252-13.el9_2

Not that upstream tracker is only for the last two releases (v253 would be the oldest if I don't count v255 that is out since today).

Also, it seems to be better suited to be filed for distro's RPM macros.

Can you reproduce on something closer to upstream?

**Comment by poettering** [comment] 2024-04-19 15:04
Closing since misfiled and not really a systemd upstream thing anyway.

**Closed as completed by poettering** 2024-04-19 15:04 UTC
Labels: needs-reporter-feedback ❓, misfiled, rpm
