### ISSUE TITLE
Tunnel interfaces don't get configured

### ISSUE THREAD

**Issue by smurfix** [systemd/systemd#7315] opened 2017-11-13 17:25 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 235

### Used distribution

> Debian

### In case of bug report: Expected behaviour you didn't see

> GRE tunnel interfaces get addresses assigned and routes added to, as per "their" .network file when they come up.

### In case of bug report: Unexpected behaviour you saw

> Tunnel interface stays in state UNKNOWN and there are no routes.

The problem might be related to the fact that networkd is waiting for the link's state to come UP. However, an ip-GRE tunnel doesn't have a connection behind it, thus the kernel reports UNKNOWN.

In any case I can manually add the address+route to the tunnel and voilà it's up and running.

#### networkctl 
```
IDX LINK             TYPE               OPERATIONAL SETUP     
  1 lo               loopback           carrier     configured
  2 en1              ether              routable    configuring
  3 en0              ether              routable    configuring
  5 gre0             ipgre              carrier     configuring
  6 gretap0          ether              off         configuring
  9 router-3         ipgre              off         configuring
```
#### cat 20-en1.network 
```
[Match]
Name=en1

[Network]
DHCP=no
LinkLocalAddressing=no

Tunnel=router-3

[Address]
Address=10.107.11.1/24
```
#### cat 20-router-3.netdev 
```
[NetDev]
Name=router-3
Kind=gre

[Tunnel]
Local=10.107.11.1
Remote=10.107.11.3
DiscoverPathMTU=yes
```
#### cat 20-router-3.network 
```
[Match]
Name=router-3

[Network]
DHCP=no
LinkLocalAddressing=no

[Address]
Address=10.107.8.130/32

[Route]
Destination=10.107.6.0/24
Source=10.107.8.130
```
#### ip addr ls dev router-3
```
9: router-3@netz: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1396 qdisc noqueue state UNKNOWN group default qlen 1
    link/gre 10.107.11.1 peer 10.107.11.3
    inet6 fe80::5efe:a6b:b01/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by ssahani** [comment] 2017-11-14 08:39
Missing 21-router-3.network

For example:

```
[Match]                                                                                                                                                                                  
Name=router-3                                                                                                                                                                            
                                                                                                                                                                                         
[Network]                                                                                                                                                                                
DHCP=no                                                                                                                                                                                  
LinkLocalAddressing=no                                                                                                                                                                   
                                                                                                                                                          
[Address]                                                                                                                                                                                
Address=10.107.11.2/24                                                                                                                                                                   
 ```
networkctl 
```
IDX LINK             TYPE               OPERATIONAL SETUP     
  1 lo               loopback           carrier     unmanaged 
 14 router-3         ipgre              routable    configured
```

**Comment by smurfix** [comment] 2017-11-14 09:28
Umm, why?
(a) there already is a 20-router-3.network.
(b) I fail to see why a Tunnel=NAME in the file that's responsible for NAME should be necessary, or even make sense.

**Comment by smurfix** [comment] 2017-11-14 09:30
In any case, is there a way to figure out why an interface is stuck in `configuring` which I was too dumb to find, or is that an issue that really should be addressed?

**Comment by ssahani** [comment] 2017-11-14 10:39
Umm, why?
>(a) there already is a 20-router-3.network.
(b) I fail to see why a Tunnel=NAME in the file that's responsible for NAME should be necessary, or even make sense.

To configure a link we need to `[Match]` the interface name even if to make it up  . Tunnel=name just supplies the index number to create the netdev.

**Comment by smurfix** [comment] 2017-11-14 11:35
Sure, but there already is a
```
[Match]
Name=router-3
```
section in `20-router-3.network`! Why would I need to duplicate that in `21-router-3.network`?

**Comment by ssahani** [comment] 2017-11-14 11:38
that just a example I gave you . no need to duplicate that .

**Comment by smurfix** [comment] 2017-11-14 11:59
Umm … so, to summarize, you told me that there's something missing, but then supplied a file with essentially the same content as the one I already have. So you actually missed the file I provided?

Given that my example gets stuck in `configuring` state and your test environment apparently doesn't, something else must be wrong.

So how can I figure out the reason for this? It seems that systemd-networkd needs some more detailed introspective capabilities here …?

**Comment by ssahani** [comment] 2017-11-14 12:16
Oops sorry I missed the third file kind of overlooked. But I can't reproduce . works for me . using your config. Only thing I changed is the interface name

**Comment by ssahani** [comment] 2017-11-14 12:24
sudo ./systemd-networkd
```
router-3: netdev ready
router-3: IPv6 successfully disabled
router-3: Gained carrier
router-3: Configured
```

20-en1.network
```
[Match]                                                                                                                                                                                                             
Name=enp0s25                                                                                                                                                                                                        
                                                                                                                                                                                                                    
[Network]                                                                                                                                                                                                           
DHCP=no                                                                                                                                                                                                             
LinkLocalAddressing=no                                                                                                                                                                                              
Tunnel=router-3                                                                                                                                                                                                     
                                                                                                                                                                                                                    
[Address]                                                                                                                                                                                                           
Address=10.107.11.1/24
```
20-router-3.netdev
```
[NetDev]                                                                                                                                                                                                            
Name=router-3                                                                                                                                                                                                       
Kind=gre                                                                                                                                                                                                            
                                                                                                                                                                                                                    
[Tunnel]                                                                                                                                                                                                            
Local=10.107.11.1                                                                                                                                                                                                   
Remote=10.107.11.3                                                                                                                                                                                                  
DiscoverPathMTU=yes
```
20-router-3.network
```
Match]                                                                                                                                                                                                             
Name=router-3                                                                                                                                                                                                       
                                                                                                                                                                                                                    
[Network]                                                                                                                                                                                                           
DHCP=no                                                                                                                                                                                                             
LinkLocalAddressing=no                                                                                                                                                                                              
                                                                                                                                                                                                                    
[Address]                                                                                                                                                                                                           
Address=10.107.8.130/32                                                                                                                                                                                             
                                                                                                                                                                                                                    
[Route]                                                                                                                                                                                                             
Destination=10.107.6.0/24                                                                                                                                                                                           
Source=10.107.8.130                                                                                                                                                                                                 
                   
```
# ll
```
total 16
-rw-r--r-- 1 root root  113 Nov 14 17:49 20-en1.network
-rw-r--r-- 1 root root   99 Nov 14 17:49 20-router-3.netdev
-rw-r--r-- 1 root root  154 Nov 14 17:49 20-router-3.network
```

networkctl 
```
IDX LINK             TYPE               OPERATIONAL SETUP     
  1 lo               loopback           carrier     unmanaged 
  2 enp0s25          ether              no-carrier  configuring
  3 wlan0            wlan               routable    unmanaged 
  4 virbr2           ether              no-carrier  unmanaged 
  5 virbr2-nic       ether              off         unmanaged 
  6 virbr0           ether              no-carrier  unmanaged 
  7 virbr0-nic       ether              off         unmanaged 
  8 gre0             ipgre              off         unmanaged 
  9 gretap0          ether              off         unmanaged 
 13 router-3         ipgre              routable    configured <================here
```

Or I miss something ?

**Comment by ssahani** [comment] 2018-11-30 14:42
@smurfix should we close this ?

**Closed as completed** 2018-11-30 15:21 UTC
Labels: bug 🐛, network
