### ISSUE TITLE
journalctl: add option to add match for latest invocation ID of a unit

### ISSUE THREAD

**Issue by lucaswerkmeister** [systemd/systemd#5317] opened 2017-02-11 22:01 UTC
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232 / master

### Used distribution

> Arch Linux

I think a `journalctl` option to show only messages for the latest invocation of a unit would be useful. I imagine `journalctl` would look for the latest message of a unit, get its `_SYSTEMD_INVOCATION_ID`, and then add a match for that.

`systemctl status` could then use that functionality to only show messages pertaining to the current run of a unit, as @poettering suggested in #4067. (Though I suspect that’s not quite what he had in mind – the service manager knows the invocation ID already, it doesn’t have to look for it in the journal.)

I’m not yet sure what the CLI interface should be, though. I see two possibilities:

- It’s an additional option that applies to all units selected with `-u`. `journalctl -u sshd --latest-invocation`.
- It takes a unit name as argument, and can be specified several times. `journalctl --latest-invocation sshd`.

The first version seems to make more sense to me, but it’s weird that the option is illegal without `-u`, so perhaps the second one is better?

**Comment by evverx** [comment] 2017-02-11 22:21
`journald` doesn't know `_SYSTEMD_INVOCATION_ID` sometimes (https://github.com/systemd/systemd/issues/4441, https://github.com/systemd/systemd/issues/5236).
`journalctl --latest-invocation` should handle this somehow

**Comment by lucaswerkmeister** [comment] 2017-02-11 22:24
I’ve also noticed that the “Starting …”, “Started.” etc. messages by systemd itself don’t have the invocation ID attached (unless that’s a bug that’s already fixed on master?), so that’s another case where the latest message with `_SYSTEMD_UNIT=whatever` doesn’t provide an invocation ID for us.

**Comment by evverx** [comment] 2017-02-11 22:33
Hm, indeed
```
bash-4.3# journalctl _SYSTEMD_INVOCATION_ID=fd9e11aa6cc346799eafb7565ddae104 --no-pager
-- Logs begin at Thu 2017-02-09 05:44:31 UTC, end at Thu 2017-02-09 05:47:25 UTC. --
Feb 09 05:46:12 systemd-testsuite sh[198]: + echo Sleeping
Feb 09 05:46:12 systemd-testsuite sh[198]: Sleeping
Feb 09 05:46:12 systemd-testsuite sh[198]: + sleep 1000
Feb 09 05:46:12 systemd-testsuite systemd[198]: a.service: Executing: /bin/sh -x -c 'echo Sleeping; sleep 1000'
```
```
bash-4.3# journalctl -u a --no-pager
-- Logs begin at Thu 2017-02-09 05:44:31 UTC, end at Thu 2017-02-09 05:46:13 UTC. --
Feb 09 05:46:12 systemd-testsuite systemd[1]: a.service: Trying to enqueue job a.service/start/replace
Feb 09 05:46:12 systemd-testsuite systemd[1]: a.service: Installed new job a.service/start as 59
Feb 09 05:46:12 systemd-testsuite systemd[1]: a.service: Enqueued job a.service/start as 59
Feb 09 05:46:12 systemd-testsuite systemd[1]: a.service: Passing 0 fds to service
Feb 09 05:46:12 systemd-testsuite systemd[1]: a.service: About to execute: /bin/sh -x -c 'echo Sleeping; sleep 1000'
Feb 09 05:46:12 systemd-testsuite systemd[1]: a.service: Forked /bin/sh as 198
Feb 09 05:46:12 systemd-testsuite systemd[1]: a.service: Changed dead -> running
Feb 09 05:46:12 systemd-testsuite systemd[1]: a.service: Job a.service/start finished, result=done
Feb 09 05:46:12 systemd-testsuite systemd[1]: Started a.service.
Feb 09 05:46:12 systemd-testsuite sh[198]: + echo Sleeping
Feb 09 05:46:12 systemd-testsuite sh[198]: Sleeping
Feb 09 05:46:12 systemd-testsuite sh[198]: + sleep 1000
Feb 09 05:46:12 systemd-testsuite systemd[198]: a.service: Executing: /bin/sh -x -c 'echo Sleeping; sleep 1000'
```
I think this is a bug

**Comment by lucaswerkmeister** [comment] 2017-02-12 18:39
I’ve reported that bug as #5323.

**Comment by garyvdm** [comment] 2022-01-25 05:46
Duplicate of #1942 ?

**Closed as completed** 2024-08-01 02:33 UTC
Labels: RFE 🎁, journal
