### ISSUE TITLE
System hangs at reboot/shutdown, GH issues says its resolved but how?

### ISSUE THREAD

**Issue by JackDinn** [systemd/systemd#23776] opened 2022-06-17 17:22 UTC
Had this problem for ages and ages.  dont reboot much so it only bothers me a little but its about time i figure out how to fix this. In the thread below the same problem is "resolved" and the thread is closed, but how is it resolved?

https://github.com/systemd/systemd/issues/1615

You can see where my shutdown/reboot hangs for 90 ish seconds here, i just dont know why.
```
Jun 17 17:44:02 greg-inspiron5767 systemd[1]: Stopped Simple Desktop Display Manager.
Jun 17 17:44:02 greg-inspiron5767 systemd[1]: sddm.service: Consumed 32.280s CPU time.
Jun 17 17:45:31 greg-inspiron5767 systemd[1]: session-1.scope: Stopping timed out. Killing.
Jun 17 17:45:31 greg-inspiron5767 systemd[1]: session-1.scope: Killing process 989 (kwin_x11) with signal SIGKILL.
Jun 17 17:45:31 greg-inspiron5767 systemd[1]: session-1.scope: Killing process 1012 (kwin_x11:sh2) with signal SIGKILL.
Jun 17 17:45:31 greg-inspiron5767 systemd[1]: session-1.scope: Killing process 1013 (kwin_x11:gdrv0) with signal SIGKILL.
Jun 17 17:45:31 greg-inspiron5767 systemd[1]: session-1.scope: Killing process 1033 (n/a) with signal SIGKILL.
Jun 17 17:45:31 greg-inspiron5767 systemd[1]: session-1.scope: Killing process 1036 (n/a) with signal SIGKILL.
Jun 17 17:45:31 greg-inspiron5767 systemd[1]: session-1.scope: Killing process 1037 (n/a) with signal SIGKILL.
Jun 17 17:45:31 greg-inspiron5767 systemd[1]: session-1.scope: Killing process 1038 (n/a) with signal SIGKILL.
Jun 17 17:45:31 greg-inspiron5767 systemd[1]: session-1.scope: Killing process 1039 (n/a) with signal SIGKILL.
Jun 17 17:45:31 greg-inspiron5767 systemd[1]: session-1.scope: Killing process 1040 (kwin_x11:sh2) with signal SIGKILL.
Jun 17 17:45:31 greg-inspiron5767 systemd[1]: session-1.scope: Killing process 1045 (n/a) with signal SIGKILL.
Jun 17 17:45:31 greg-inspiron5767 systemd[1]: session-1.scope: Killing process 1046 (n/a) with signal SIGKILL.
Jun 17 17:45:31 greg-inspiron5767 systemd[1]: session-1.scope: Failed with result 'timeout'.
Jun 17 17:45:31 greg-inspiron5767 systemd[1]: Stopped Session 1 of User greg.
Jun 17 17:45:31 greg-inspiron5767 systemd[1]: session-1.scope: Consumed 1min 48.068s CPU time.
Jun 17 17:45:31 greg-inspiron5767 systemd[1]: Stopping User Login Management...
Jun 17 17:45:31 greg-inspiron5767 systemd[1]: Stopping User Manager for UID 1000...
```

```
System:
  Host: greg-inspiron5767 Kernel: 5.15.48-1-MANJARO arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.24.5 Distro: Manjaro Linux
Machine:
  Type: Laptop System: Dell product: Inspiron 5767 v: N/A
    serial: <superuser required>
  Mobo: Dell model: 03XWWJ v: A00 serial: <superuser required>
    UEFI-[Legacy]: Dell v: 1.4.1 date: 12/24/2020
```

**Comment by yuwata** [comment] 2022-06-27 15:48
Closing. Please feel free to request to reopen this is not a bug in KDE.

**Closed as completed by yuwata** 2022-06-27 15:48 UTC
Labels: pid1, not-our-bug, shutdown

**Comment by JackDinn** [comment] 2022-06-27 17:20
Ok thank you.
