### ISSUE TITLE
homed crash after event_inotify_data_drop()

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#18594] opened 2021-02-15 09:09 UTC
Filing this here so it doesn't get forgotten. Forwarded from https://bugzilla.redhat.com/show_bug.cgi?id=1899264.

**systemd version the issue has been seen with**
 > systemd-246.6-3.fc33

Truncated backtrace:
```
Thread no. 1 (7 frames)
 #2 log_assert_failed_realm at ../src/basic/log.c:844
 #3 event_inotify_data_drop at ../src/libsystemd/sd-event/sd-event.c:3035
 #4 source_dispatch at ../src/libsystemd/sd-event/sd-event.c:3250
 #5 sd_event_dispatch at ../src/libsystemd/sd-event/sd-event.c:3631
 #6 sd_event_run at ../src/libsystemd/sd-event/sd-event.c:3689
 #7 sd_event_loop at ../src/libsystemd/sd-event/sd-event.c:3711
 #8 run at ../src/home/homed.c:47
```

<details>

```
Core was generated by `/usr/lib/systemd/systemd-homed'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:49
49	  return ret;

Thread 1 (Thread 0x7efe60438b80 (LWP 1340)):
#0  __GI_raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:49
        set = {__val = {81922, 0, 0, 272, 0, 0, 32832, 139631015844352, 18446744073709551615, 0, 139631021524478, 94816921956336, 4294967295, 139631014564438, 2050, 139631015850016}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007efe60ff68a4 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x8, sa_sigaction = 0x8}, sa_mask = {__val = {31092, 1, 2474545584092771072, 0, 139631021707552, 2, 139631021704163, 3035, 139631021707552, 94816921819552, 139631020637010, 0, 0, 0, 139631022181888, 0}}, sa_flags = 0, sa_restorer = 0x7efe616e8d53}
        sigs = {__val = {32, 140734279600696, 140734279600480, 2474545584092771072, 483511169, 0, 139631021428051, 2474545584092771072, 3035, 139631021428051, 139631021428051, 139631020652401, 94816921956352, 140734279606189, 8, 31092}}
#2  0x00007efe6155f549 in log_assert_failed_realm (realm=<optimized out>, text=0x7efe616e8d53 "*_head == _item", file=0x7efe6172c3e3 "src/libsystemd/sd-event/sd-event.c", line=3035, func=0x7efe6172d120 <__PRETTY_FUNCTION__.20> "event_inotify_data_drop") at ../src/basic/log.c:844
No locals.
#3  0x00007efe616b2d87 in event_inotify_data_drop (e=e@entry=0x563c48f199a0, d=d@entry=0x563c48f1e7d0, sz=sz@entry=16) at ../src/libsystemd/sd-event/sd-event.c:3035
        _head = 0x563c48f19ad0
        _item = 0x563c48f1e7d0
        __PRETTY_FUNCTION__ = "event_inotify_data_drop"
#4  0x00007efe616badd2 in source_dispatch (s=s@entry=0x563c48f1e6c0) at ../src/libsystemd/sd-event/sd-event.c:3250
        e = 0x563c48f199a0
        d = 0x563c48f1e7d0
        sz = 16
        saved_type = SOURCE_INOTIFY
        r = 0
        __PRETTY_FUNCTION__ = "source_dispatch"
        __func__ = "source_dispatch"
#5  0x00007efe616bb0cd in sd_event_dispatch (e=0x563c48f199a0) at ../src/libsystemd/sd-event/sd-event.c:3631
        ref = 0x563c48f199a0
        p = 0x563c48f1e6c0
        r = <optimized out>
        __PRETTY_FUNCTION__ = "sd_event_dispatch"
#6  0x00007efe616bc398 in sd_event_run (e=e@entry=0x563c48f199a0, timeout=timeout@entry=18446744073709551615) at ../src/libsystemd/sd-event/sd-event.c:3689
        r = 1
        __PRETTY_FUNCTION__ = "sd_event_run"
#7  0x00007efe616bc5b7 in sd_event_loop (e=0x563c48f199a0) at ../src/libsystemd/sd-event/sd-event.c:3711
        ref = <optimized out>
        r = <optimized out>
        __PRETTY_FUNCTION__ = "sd_event_loop"
#8  0x0000563c4894f30e in run (argv=<optimized out>, argc=<optimized out>) at ../src/home/homed.c:47
        m = <optimized out>
        notify_stop = 0x563c4896b8e8 "STOPPING=1\nSTATUS=Shutting down..."
        r = 0
        m = <optimized out>
        notify_stop = <optimized out>
        r = <optimized out>
        __func__ = <optimized out>
        __PRETTY_FUNCTION__ = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _realm = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _realm = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _realm = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _realm = <optimized out>
#9  main (argc=<optimized out>, argv=<optimized out>) at ../src/home/homed.c:54
        r = <optimized out>
```
</details>

/cc @poettering

**Comment by poettering** [comment] 2021-02-15 16:33
This is a duplicate of #17824, but given this newer issue contains more info, let's close the other one

**Comment by keszybz** [comment] 2021-02-15 20:15
Thanks, I should have found the other issue.

**Closed as completed** 2021-03-08 14:12 UTC
Labels: bug 🐛, downstream/fedora, homed
