### ISSUE TITLE
tcp_ecn causes my network downloads to fail or become _very_slow

### ISSUE THREAD

**Issue by tYYGH** [systemd/systemd#9748] opened 2018-07-29 10:43 UTC
**systemd version the issue has been seen with**
> 239.0

**Used distribution**
> Archlinux

**Expected behaviour you didn't see**
> working downloads

**Unexpected behaviour you saw**
> very slow, or non-working downloads (curl, wget, firefox, git clone/fetch…)

**Steps to reproduce the problem**
Install systemd 239.0
See here: https://bugs.archlinux.org/task/59473

**Steps to _fix_ the problem**
`sysctl net.ipv4.tcp_ecn=0`

**Comment by phomes** [comment] 2018-07-29 20:16
[The man page for tcp](https://manpages.debian.org/stretch/manpages/tcp.7.en.html) says
> 
When enabled, connectivity to some destinations could be affected due to older, misbehaving middle boxes along the path, causing connections to be dropped. However, to facilitate and encourage deployment with option 1, and to work around such buggy equipment, the tcp_ecn_fallback option has been introduced.

And it seems that you might be affected by that. Can you share some details about your network equipment and perhaps even check if there is an updated firmware for it?

To work around the problem I would suggest to use `sysctl net.ipv4.tcp_ecn=1` instead of 0, as that is was the default in use before the change in #9143 

@SimonIremonger

**Comment by SimonIremonger** [comment] 2018-07-29 20:57
Correction to above:  sysctl net.ipv4.tcp_ecn=2  [negotiate ECN only on incoming connections] used to be the default, I think.
I any case, I agree tYYGH should sort-out what router / further network equipment in use and its' firmware...  Could easily be an issue there!.

**Comment by poettering** [comment] 2018-07-30 10:44
I wonder if we should revert #9143. We shouldn't really turn something on if it breaks people's connectivity. If routers are fucked, then this might very well be out of control of the person who uses the system, and issues like this are really not easy to debug and fix.

**Comment by poettering** [comment] 2018-07-30 10:45
@SimonIremonger @enihcam @michich opinions on reverting?

**Comment by tYYGH** [comment] 2018-07-30 11:10
I can confirm the “not easy to debug” part! I literally spent _days_ on Freenode##Networking, where I got great help, and no one came anywhere close to the real cause for this issue. We ran many tests (ping, traceroute, mtr, tcpdump…), and always we were disturbed by the fact that _some_ things worked, and _some_ not…

I had this issue on 2 machines (out of 2!) where I upgraded to latest systemd. I will report on these machines’ specifics (a regular self-assembled PC, and an Udoo X86) as soon as I get home.

Thanks a lot for systemd, by the way! It’s so much better than what we had before :-)

**Comment by SimonIremonger** [comment] 2018-07-30 11:18
I would strongly suggest a 3-prong'ed approach:-

Definitely encourage those who HAVE found STILL faulty network equipment to raise the issue (this NEEDS to happen somewhere!!).  Is there a new wiki/location for ECN-hall-of-shame?

Advising linux-net and bufferbloat communities of the issue still persisting in some areas, and asking if a more aggressive ECN-fallback option can be implemented (like apple have been doing sucessfully).

Gauge the actual scale of the issue, It may be reverting for the next systemd revision is worthwhile, but this still "needs raising" somewhere.  I would have expected this issue to appear in a FEW places but I really do get the impression its' increasingly-rare.  Many of us have had tcp_ecn=1 for a decade now.   These few, initial, complaints might suggest the problem is now more likely in "consumer routers" rather than in "public services" (latter appears to be much of a non-issue now)...
If the latter-point is true, a better adaptive-fallback in kernel would likely alleviate/workaround the slow connection establishment, at least.

**Comment by SimonIremonger** [comment] 2018-07-30 11:23
@tYYGH -- we don't need the machines' specifics as much as  Router/firmware-on-router that you are connecting through, which is much more likely where the incompatibility lies.

**Comment by tYYGH** [comment] 2018-07-30 15:58
Here is absolutely all I can tell about this ISP-provided router:

```
[root@sedentaire ~]# nmap -A 192.168.1.1
Starting Nmap 7.70 ( https://nmap.org ) at 2018-07-30 17:49 CEST
Nmap scan report for bbox.lan (192.168.1.1)
Host is up (0.00045s latency).
Not shown: 997 closed ports
PORT    STATE SERVICE  VERSION
53/tcp  open  domain   dnsmasq 2.75
| dns-nsid: 
|_  bind.version: dnsmasq-2.75
80/tcp  open  http     lighttpd
|_http-server-header: Lighttpd
443/tcp open  ssl/http lighttpd
| ssl-cert: Subject: commonName=Bbox/organizationName=Bouygues Telecom/stateOrProvinceName=France/countryName=FR
| Not valid before: 2013-05-27T08:50:31
|_Not valid after:  2023-05-25T08:50:31
|_ssl-date: TLS randomness does not represent time
MAC Address: D0:84:B0:18:55:FC (Sagemcom Broadband SAS)
Device type: general purpose
Running: Linux 2.6.X
OS CPE: cpe:/o:linux:linux_kernel:2.6
OS details: Linux 2.6.9 - 2.6.27
Network Distance: 1 hop
```

Apparently, this would be the one:
https://www.bbox-mag.fr/box/fixe/37-presentation-video-de-la-bbox-sensation-ng-sagem-5330b/

**Comment by tYYGH** [comment] 2018-07-30 16:38
In your opinion, is this an _important_ bug in this loaned router, that would justify, that Bouygues (my ISP) replaces it with a bug-free model? Or is this just a sadly-acceptable nuisance?

**Comment by phomes** [comment] 2018-07-30 17:06
I am a bit surprised that an ISP would not have this fixed. All iOS 11 devices have ECN enabled and 50% randomly selected OS X computers do. So I would expect an ISP to drown in complaints over the router. But maybe our fallback solution is just not good as Apples as @SimonIremonger wrote.

Just to be sure. `net.ipv4.tcp_ecn_fallback` is set to 1, right?

**Comment by SimonIremonger** [comment] 2018-07-30 17:35
FWIW conservative ECN fallback mechanism heuristics described here:-
https://www.ietf.org/proceedings/98/slides/slides-98-maprg-tcp-ecn-experience-with-enabling-ecn-on-the-internet-padma-bhooma-00.pdf

**Comment by tYYGH** [comment] 2018-07-31 16:11
Interesting read!
I believe I had at least the packet-reordering problem:
https://ptpb.pw/fXg1
This is curl trying to download the Tor-Browser using the URL from the project’s web site.

**Comment by SimonIremonger** [comment] 2018-07-31 16:51
@tYYGH 
Do find what you can about alternate-router / ISP tech support...  Post onto phomes's query:-
https://www.reddit.com/r/linux/comments/933vys/is_tcp_ecn_still_a_problem_today/
If problem-routers quoted there I'll put notes in bufferbloat wiki.

**Comment by dtaht** [comment] 2018-08-03 01:51
a packet cap of the failing connection with ecn on would be revealing.

for the record, I have deeply conflicting feelings about the wide use of ecn. In my mind it is a good idea at very short rtts(sub 2ms), and very long ones(>50ms), and for doing things like protecting video iframes from loss. *I* use it to protect routing babel protocol packets from being dropped. Etc.

Others (in the bbr, l4s, dctcp communities) want to change the definition of ecn to mean a multi-bit rate reduction and obsolete rfc3168, where a loss is equivalent to a mark. fq_codel, pie, red, and all other deployed ecn capable aqm systems essentially implement rfc3168 behavior and it's what apple's tcp - and linux cubic deployment expects. I had hoped with wider deployment of aqms that dealt with ecn properly that we'd see more tcp's also enabling it... and we'd see tcps evolve to treat aqms doing ecn marks per rfc3168 more sanely than they do today as it is a stronger signal of congestion than loss, as well as 

Instead... well, see bbr, which currently more or less ignores  packet loss on it's quest to own the link, and currently has no ecn response. There's a thread on the bbr list that talks about how they are leaning towards not respecting that rfc. The l4s folk vehemently defend the idea that some form of dctcp can run outside the datacenter, based on bigbuckbunny based demos, combined with a custom and patented aqm, never tested against wifi or 3g, who create a lot of noise in the ietf, and little else.

Nearly every time I've quit smoking, an aqm debate started me up again, and instead of continuing to deal with it, I left the ietf, leaving the folk there to plot amongst themselves with no actual deployment to deal with. I'm so frustrated with the "go fast at any cost" people that periodically I fiddle with something called tcp-fu (for users), that has an adjustable response curve to fq_codel's ecn marks from background (torrent-like) to "gentle". 

I certainly support systemd folk trying to move the state of the art forward and am eternally grateful for their adoption of fq_codel, which now covers the world, and has ecn enabled by default. If, in all the world, enabling ecn for cubic tcp only breaks one box, well, fix that box.

Turning on ecn universally in systemd seems to be an idea that could be a *major* forcing, political and technical function, towards aiding deployment (fixing busted routers) and keeping the simplicity of an rfc3168-style ecn enabled aqm alive instead of crazed ietf alternatives like l4s + "dualQ". Of course those proponents would point to their lowered tcp delay (in the datacenter) as a forever lost opportunity and split the universe apart.

I *used* to take great glee in how fq techniques generally beat dctcp's, even in the datacenter...

But...

As the accidental co-author of what is now the largest edge-user ecn-enabled aqm deployment in "fq_codel everywhere", + the implementation in the ath9k and athk  wifi code... (does anyone have any idea how many users of systemd + fq_codel are?) I lose sleep over it. I have a ton of data on it.

What I see with lots of tcp-ecn traffic on a link is that other valuable packets are delayed (slightly) or lost and am always saying "ECN has mass" to anyone that will listen. This is made up for by nearly eliminating retransmits, mostly. I think. It's a huge win for interactive tcp traffic, which is why apple adopted it. I worry about lockout at low speeds and that one day we'd have to mark all packets of all types of flows (including voip and dns) as ecn capable, *unless tcps evolve appropriately towards an agreed upon response curve*.

One *really* interesting side-effect of ecn on is that fq_codel, running locally on the server, can self congest and start marking packets locally, thus regulating the behavior of the server better after a rtt, IMHO.(try 128 flows coming out of a short path at a gbit). Others might view that as a problem and prefer that that server serve 100s more flows at ever increasing local delay (I know this is not a good description of this issue, this is a bug note not a paper).

I do wish we'd come up with a more robust response to overload in fq_codel for it, as currently a malicious ecn sender can push fq_codel to its memory limit before being dropped robustly. (pie drops ecn at overload). fq_codel can continue to evolve as can everything else of course!

ECN is the wet paint of the congestion control universe. I hope the systemd deployment goes well and if it does, I'll sleep better, and if it doesn't, and gets reverted with all the reasons why well understood, I'll also sleep better. thx for pushing the limits

**Comment by dtaht** [comment] 2018-08-03 05:07
@tYYGH  - looking at that packet cap is not helpful without the actual .cap file as it lacks IP headers. Secondly iy appears to be using tor. It would not surprise me if some tor's clients/servers encapsulation of ip packets was wrong (in perpetual draft is this: https://tools.ietf.org/html/draft-ietf-tsvwg-ecn-encap-guidelines-10) 

I'm currently not inclined to "blame the router" but the server you are connecting to. This server has ecn enabled. Try downloading this file both "straight" and through tor, with ecn on and off, with wget or curl: http://flent-fremont.bufferbloat.net/~d/losangeles_and_wish_you_were_here.mp3

(for the record, it's me and a friend playing those two songs and is 12MB in size, enjoy)

(If you can setup a time I can tcpdump from my side).

@SimonIremonger - if you can't tell, my position on ecn is nuanced. Also, apple's enormous test tested their clients against their servers primarily, and not things like torrent or tor. I would not surprise me at all if ecn failure modes were higher against many other peoples severs, nor if linux's ecn response was insufficiently robust.

**Comment by tYYGH** [comment] 2018-08-05 10:34
@dtaht - There is no TOR involved in the tcpdump output I posted. This is a plain curl download _of_ the Tor Browser, **not** _through_ the Tor Browser.

I wouldn’t blame the server, too (or at least not only this one), since this issue also prevented me from running any `git fetch` for example; and for instance, downloading https://f-droid.org/FDroid.apk failed the same way as downloading the Tor Browser did.

As for the usefulness of the capture I posted, I am sorry if it is useless; it is only what I had available at the time. I ran this capture at the direction of someone who understands these things better than I do. I do not know how to use tcpdump, and I do not understand its output, and your long post above is gibberish to me, sadly.

However, I am willing to learn, and to help, and if I can produce any output that is more helpful, please ask! I will do my best to do post the information you need.

**Comment by dtaht** [comment] 2018-08-06 20:39
ok, that much info points more at your router. 

tcpdump -i yourinterface -w acapture.cap 

captures the binary info needed to look that deeply into what was going on at the tcp level.

**Comment by jonathonf** [comment] 2018-08-12 11:48
Just to weigh in here. Silently "breaking" end-users' network connections isn't a great approach to fixing middleware. You also need to remember that large parts of the world don't have the same level of networking infrastructure so some users won't be able to do anything about this even if they knew the reason behind their issue.

As things stand, there are numerous reports of network connections suddenly becoming "slow" after an update to 239 on rolling release distros. This leads those users to test a different (frozen-pool) distro, find it works as expected (as it has an older systemd version), and then simply move to that distro. Of course, the issue will reappear a few months/years down the line when they upgrade _that_ distro, but as far as they're concerned the original distro was broken.

Now - if I I have read https://github.com/systemd/systemd/issues/9748#issuecomment-410119854 correctly, it appears that ECM isn't a "magic bullet" that should be blanket-enabled, but is instead a "tweak" or "optimisation" which should be applied by network admins who know what it does and can check its effects. A "successful" test on iOS isn't representative for anything other than for iOS devices being used in areas where people can afford iOS devices - Linux isn't only run on high-end/pro-sumer hardware.

I don't know how new features can be rolled out without this sort of friction ("you can't please all the people all the time") but if ECM isn't "perfect" perhaps this change should be reverted? At least until it can be better/more widely tested?

**Comment by dtaht** [comment] 2018-08-13 19:30
If the ecn change is causing trouble outside this bug report, I totally agree with reverting it in systemd.

**Comment by keszybz** [comment] 2018-08-20 07:38
Since #9880 is merged, let's close this. We can probably try again when the kernel gets better fallback mode.

**Closed as completed by keszybz** 2018-08-20 07:38 UTC
Labels: sysctl

**Comment by MayeulC** [comment] 2018-10-05 09:39
For what it's worth, I experienced this issue, with exactly the same ISP-provided router as @tYYGH, A Bouygues Telecom ADSL box (I'll provide the exact model later). Symptoms include Internet working on Wi-Fi but not Ethernet, everything working fine on an older distribution. The internet connection is very slow and unreliable, TCP connections start to drop after a while, downloads stalling after a handful bytes, with some websites working, and others not. Symptoms are similar to (and this router might exhibit this problem as well) a window scaling issue.
The fact that connections work over Wi-Fi indicates that it's probably a home router configuration issue, and not somewhere else on the link.
I will contact the ISP a bit later, I hope to be able to sort trough the phone support maze. Suggestions are welcome.

**Comment by tYYGH** [comment] 2018-10-05 14:54
Interesting feedback, @MayeulC! I once had a _competent_ _technical_ person on the phone (can you believe it?); unfortunately I had to leave home at that time, and couldn’t investigate things with him :cry:

In case that helps you, the way I did, is that I went to a real brick&mortar BBox agency at the mall, and told the people there, that I had a technical problem, and that I had already done some investigation with network experts from the Internet, and that the problem was definitely on Bouygues’ side, and that I wished to be called home by a technician. And call he did!

**Comment by rickco** [comment] 2018-10-16 20:33
Like @MayeulC  @tYYGH , I had my archlinux having unreliable internet connection through my ISP Bouygues Telecom (more precisely box Miami) after an upgrade.
The issue is not easy to detect as the internet is kind of working. Even a linux confirmed user like me would never suspect anything wrong. Until I was really upset of download failing that i started to look more precisely and found out on a Bouygues forum that is was due to my archlinux latest defaut config. Nothing in the issue makes you think is can come from systemd, so i would advocate for a default config that works everywhere.
setting net.ipv4.tcpp_ecn=2 solved the issue in my case

**Comment by MayeulC** [comment] 2018-10-27 15:36
I just had a phone call with a "Bouygues Telecom technical service" employee (who was actually quite knowledgeable, which surprised me as I missed the phone call we planned at the BBox store and had to call back like any customer).

I was told they would investigate and keep me updated. Meanwhile, that person suggested me to post in the self-support forums, so that other people could chime in and report that they were affected as well. @tYYGH , @rickco, could you add a few words to [this](https://forum.bouyguestelecom.fr/questions/1793649-gestion-explicite-congestion-perturbe-fonctionnement-reseau-ethernet-possible-corriger) thread, please (I wrote the post in French, though)?
I hope they will patch their routers and leave us one step closer to enabling this everywhere. I'm not holding up my hopes too high, though, and this won't replace a better in-kernel fallback mechanism.

**Comment by rickco** [comment] 2018-10-27 15:48
thanks MayeulC for the post on Bouygues forum, just replied

**Comment by dtaht** [comment] 2018-10-27 16:37
Mayeul Cantan <notifications@github.com> writes:

> I just had a phone call with a "Bouygues Telecom technical service"
> employee (who was actually quite knowledgeable, which surprised me as
> I missed the phone call we planned at the BBox store and had to call
> back like any customer).
>
> I was told they would investigate and keep me updated. Meanwhile, that
> person suggested me to post in the self-support forums, so that other
> people could chime in and report that they were affected as well.
> @tYYGH , @rickco, could you add a few words to this thread, please (I
> wrote the post in French, though)?
> I hope they will patch their routers and leave us one step closer to
> enabling this everywhere. I'm not holding up my hopes too high,
> though, and this won't replace a better in-kernel fallback mechanism.

Well, odds are iphones are acting up also.

**Comment by MayeulC** [comment] 2018-10-28 13:10
@dtaht It seems that their router doesn't exhibit this problem when using the Wi-Fi connection (I think they likely fixed that specifically for iOS devices).

**Comment by KenSharp** [comment] 2019-11-10 19:22
I don't know if you're collecting data elsewhere but:

    $ sudo sysctl -w net.ipv4.tcp_ecn=1
    net.ipv4.tcp_ecn = 1
    $ curl http://flent-fremont.bufferbloat.net/~d/losangeles_and_wish_you_were_here.mp3 > /dev/null
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 11.9M  100 11.9M    0     0   307k      0  0:00:39  0:00:39 --:--:--  313k

    $ sudo sysctl -w net.ipv4.tcp_ecn=2
    net.ipv4.tcp_ecn = 2
    $ curl http://flent-fremont.bufferbloat.net/~d/losangeles_and_wish_you_were_here.mp3 > /dev/null
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 11.9M  100 11.9M    0     0   860k      0  0:00:14  0:00:14 --:--:-- 1250k

    $ uname -a
    Linux 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Running Ubuntu 18.04. My router is a [Now TV Hub 2](https://community.nowtv.com/t5/Setup-Performance/What-is-new-with-the-NOW-TV-Hub-Two/td-p/450779) which is a Linux box, but the exact detail I do not know.

`speedtest-cli` utilizes the connection 100%. I'm guessing the test server doesn't use ECN. I can find out more if it's desirable.

**Comment by dtaht** [comment] 2019-11-10 20:45
Ken Sharp <notifications@github.com> writes:

> I don't know if you're collecting data elsewhere but:
>
> $ sudo sysctl -w net.ipv4.tcp_ecn=1
> net.ipv4.tcp_ecn = 1
> $ curl http://flent-fremont.bufferbloat.net/~d/losangeles_and_wish_you_were_here.mp3 > /dev/null
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 11.9M  100 11.9M    0     0   307k      0  0:00:39  0:00:39 --:--:--  313k
>
> $ sudo sysctl -w net.ipv4.tcp_ecn=2
> net.ipv4.tcp_ecn = 2
> $ curl http://flent-fremont.bufferbloat.net/~d/losangeles_and_wish_you_were_here.mp3 > /dev/null
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 11.9M  100 11.9M    0     0   860k      0  0:00:14  0:00:14 --:--:-- 1250k

I'd run this twice to eliminate caching effects. Still, that is a
puzzling difference. 

>
> $ uname -a
> Linux 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
>
> Running Ubuntu 18.04. My router is a Now TV Hub 2 which is a Linux
> box, but the exact detail I do not know.

(it would be cool if that box had a fq_codel or cake based qos system?)

The core stuff we use for good network measurements is the "flent" tool,
which can gather all sorts of interesting stats along the way, and it is
(along with irtt) mostly in apt. You might need to compile netperf
separately with --enable-demo 

Example of use:

sysctl -w net.ipv4.tcp_ecn=1
flent -H flent-newark.bufferbloat.net -t 'now tv hub ecn'
--te=download_streams=1 --socket-stats tcp_ndown # try 1,4,16 and
sysctl -w net.ipv4.tcp_ecn=2
flent -H flent-newark.bufferbloat.net -t 'now tv hub noecn'
--te=download_streams=1 --socket-stats tcp_ndown # try 1,4,16 and

you can then use flent-gui *.flent.gz to generate a variety of plots, especially
comparison plots.

You will find flent-derived graphs of network performance all over the
web nowadays. If you are really far away, we do have flent servers all
over the world - india, london, germany - it happens to be a good idea
to try multiple rtts (there are tests for that too in the flent suite - rtt_fair_*)

I would really like to see more ecn testing out there. There are folk
in the ietf hot and heavy about deploying it widely, while I remain
quite skeptical.

> speedtest-cli utilizes the connection 100%. I'm guessing the test
> server doesn't use ECN. I can find out more if it's desirable.

They don't. last I looked.

**Comment by KenSharp** [comment] 2019-11-10 22:03
> I'd run this twice to eliminate caching effects.

Sorry, I did mean to say that I run them multiple times. These are typical results in both cases.

> (it would be cool if that box had a fq_codel or cake based qos system?)

I honestly have no idea. The box is, sadly, pretty locked down, and it looks like they haven't updated their downloads for a while:
http://sky.com/opensourcesoftware/NowTvHub/NowTv_hub_downloads.html

I get the impression that they employ some sort of QoS, as they're a quadruple-play company, but it's not user-configurable.

I've spoken with their second-line support a few times regarding a bug (which they fixed) and they seem quite helpful. I'm not sure how many "secrets" they'd be willing to give up though.

> The core stuff we use for good network measurements is the "flent" tool

This, I shall have a look at!

**Comment by dtaht** [comment] 2019-11-14 23:07
I'm a big fan of merely asking if they are including fq_codel, cake and sqm support to fix their bufferbloat. And you could steer them at your question, here.

I hope you enjoy flent. It is currently being used big-time to prove out the relative merits of the L4S and SCE proposals in the ietf. https://github.com/heistp/sce-l4s-bakeoff

**Comment by dtaht** [comment] 2019-11-14 23:49
Wow, sky is shipping linux 3.4rt in their  SKY-NR801 release. This is a more than a few kernel versions prior to where I would have considered fq_codel & htb stable (3.12). In fact, this was probably the most bufferbloated linux kernel of them all, with bufferbloat at every layer in the stack - pre-bql for starters. I can't imagine the sheer number of cves this build must have!? If at all possible I'd run screaming away from this hardware in search of something with reasonable security.

4.14 is the last decent -rt kernel....

**Comment by SimonIremonger** [comment] 2022-05-28 19:18
> Also, apple's enormous test tested their clients against their servers primarily, and not things like torrent or tor. I would not surprise me at all if ecn failure modes were higher against many other peoples severs, nor if linux's ecn response was insufficiently robust.

Howso could "Linux's ECN response" be insufficiently-robust?  Are you talking about tcp_ecn_fallback which ought to be able to be more-intelligent, etc...?.

**Comment by dtaht** [comment] 2022-06-01 03:48
this is an extremely old thread. there have been so many bugs in the linux tcp stack, and only a couple in the ecn side.

**Comment by SimonIremonger** [comment] 2022-09-28 18:33
> this is an extremely old thread. there have been so many bugs in the linux tcp stack, and only a couple in the ecn side.
So, nonetheless, what now needs doing to make TCP_ECN widely deployable ??  What extra ECN fallback heuristics could be used for increased robustness to broken routers ?

**Comment by dtaht** [comment] 2022-09-28 19:09
There was a paper that went by a few weeks back analyzing the bleaching problem: https://arxiv.org/pdf/2208.14523.pdf
 The source data only had one major perspective to measure from, but claimed that ECN capability was up to 69% or so on the web servers tested. 

I have been observing a pretty high mark rate at a libreqos.io using ISP. Over 50% of customers have one or more CE marks per day. Now, is that working effectively? Is that marking real traffic? I don't know. The biggest fault in the current ECN deployment is that BBRv1 using servers WILL negotiate ecn capability, and then *ignore* the marks. 

To complicate matters further, the IETF just approved L4S (after a bitter fight over the SCE idea, and other problems L4S had), which does require quite a few changes still out of everyone's trees to negotiate properly and multiple incompatabilities with RFC3168 compliant AQMs.

My answer to the ECN situation remains - turn it on - see if it works - don't inflict your decision on others.
