### ISSUE TITLE
Stopping dbus ruined my day

### ISSUE THREAD

**Issue by zsugabubus** [systemd/systemd#14921] opened 2020-02-22 16:45 UTC
**Is your feature request related to a problem? Please describe.**
I wanted to get rid of unused services/processes to clean up a bit my system. I wasn’t really aware that dbus is a so crucial component, so I happily said `systemctl disable --now dbus`. Enter. F****. My disappointment was immeasurable. The only thing I could to is to switch to another TTY and press CAD.

**Describe the solution you'd like**
I surely don’t want to be able to stop core services (or anything) like this.

**Describe alternatives you've considered**
`RefuseManualStop=true` maybe? (For dumb users like me.)

**Comment by doverride** [comment] 2020-02-22 18:47
Youre late. We should probably dump dbus, instead look for ways to enhance unix stream sockets and maybe leverage varlink more.

**Comment by mbiebl** [comment] 2020-02-23 01:04
I don't see this as as useful or actionable bug report, so closing. Especially since this is related to dbus and not systemd.

**Closed as completed** 2020-02-23 01:05 UTC

**Comment by zsugabubus** [comment] 2020-02-23 01:18
Great. But I don’t understand why it has nothing to do with systemd.

**Comment by mrc0mmand** [comment] 2020-02-23 09:38
@zsugabubus systemd has no concept of *core services*, and even if it has, it would be infeasible to maintain it, since the definition of a *core service* differs from environment to environment. Also, it would be pretty dumb if systemd prevented the `root` user to stop services on their own machine, wouldn't it?

I'd recommend against blindly stopping services on a system you care about without reading what they're for first.

The only actionable item from the issue is the last part (with `RefuseManualStop=true`) but that one is not actionable from our side, since we don't maintain dbus. For this you'd have to contact the respective upstream for your dbus implementation (dbus or dbus-broker).

**Comment by zsugabubus** [comment] 2020-02-23 13:35
> systemd has no concept of core services, and even if it had, it would be infeasible to maintain it, since the definition of a core service differs from environment to environment

I meant hard dependencies under core services, which if aren’t running system hardly functions (well). There shouldn’t be too much from these and dbus seemed one of these from my scenario. It’s mentioned/maintained among runtime dependencies so it doesn’t seem a so random service(*) to me that systemd doesn’t even care about (and varies between systems): https://github.com/systemd/systemd/blob/master/README#L177.

*: Guess that the service needs to be started otherwise it’s pretty unusable.

> I'd recommend against blindly stopping services on a system you care about without reading what they're for first.

You are absolutely right! From https://www.freedesktop.org/wiki/Software/dbus/:
> D-Bus is a message bus system, a simple way for applications to talk to one another. In addition to interprocess communication, D-Bus helps coordinate process lifecycle; it makes it simple and reliable to code a "single instance" application or daemon, and to launch applications and daemons on demand when their services are needed. 

Without deeper investigations–from this short introduction–I didn’t expected my complete login session to crash and getty services not to start afterwards. If it’s not a hard dependency of systemd I don’t know what is.

> Also, it would be pretty dumb if systemd prevented the root user to stop services on their own machine, wouldn't it?

If it’s a dumb thing then `RefuseManualSt{art,op}` are also make no sense. Why user should be blocked if she explicitly wants to do this. She knows what she does, doesn’t?
Maybe it’s useful because of self-protection?

---

But tell me is it only me who stops dbus and the complete system becomes unusable? Was it just a coincidence that I stopped dbus and something bad happened? Can it be an issue with my system configuration?
