### ISSUE TITLE
It is possible to start the service via masked alias

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#10124] opened 2018-09-19 09:02 UTC
**systemd version the issue has been seen with**
* systemd-239

**Used distribution**
 * Fedora

**Expected behaviour you didn't see**
* It shouldn't be possible to start the service via masked unit file.

**Unexpected behaviour you saw**
* systemd will happily start masked service via alias, i.e. it doesn't check the state of the target unit file. 

**Steps to reproduce the problem**
 ```
$ systemctl cat a.service
# /usr/lib/systemd/system/a.service
[Service]
ExecStart=/bin/true

$ ln -s  /usr/lib/systemd/system/a.service  /usr/lib/systemd/system/b.service
$ systemctl daemon-reload
$ systemctl mask a.service
Created symlink /etc/systemd/system/a.service -> /dev/null
$ systemctl is-enabled b.service
masked
$ systemctl start b.service
$ echo $?
0
```

**Comment by mbiebl** [comment] 2018-09-19 11:13
Looks like a duplicate of #4122

**Comment by keszybz** [comment] 2021-03-03 23:54
This seems to be fixed now:
```console
$ systemctl is-enabled b.service
masked
$ sudo systemctl start b.service
Failed to start b.service: Unit b.service is masked.
```

**Closed as completed by keszybz** 2021-03-03 23:54 UTC
Labels: pid1, install, downstream/rhel
