### ISSUE TITLE
Microsoft Natural Ergonomic Keyboard 4000: Error calling EVIOCSKEYCODE on device node '/dev/input/event0'

### ISSUE THREAD

**Issue by naihil** [systemd/systemd#10746] opened 2018-11-12 19:50 UTC
**systemd version the issue has been seen with**
> 239

**Used distribution**
 > Debian Buster

**Expected behaviour you didn't see**
 > No error at journalctl -b

**Unexpected behaviour you saw**
 > Errors at boot log:
systemd-udevd[354]: Error calling EVIOCSKEYCODE on device node '/dev/input/event0' (scan code 0xc022d, key code 103): Invalid argument
systemd-udevd[354]: Error calling EVIOCSKEYCODE on device node '/dev/input/event0' (scan code 0xc022e, key code 108): Invalid argument

**Steps to reproduce the problem**
Errors logged at boot log.
`# udevadm info /dev/input/event0`
> P: /devices/pci0000:00/0000:00:14.0/usb2/2-9/2-9:1.0/0003:045E:00DB.0001/input/input0/event0
N: input/event0
S: input/by-id/usb-Microsoft_Natural®_Ergonomic_Keyboard_4000-event-kbd
S: input/by-path/pci-0000:00:14.0-usb-0:9:1.0-event-kbd
E: BACKSPACE=guess
E: DEVLINKS=/dev/input/by-path/pci-0000:00:14.0-usb-0:9:1.0-event-kbd /dev/input/by-id/usb-Microsoft_Natural®_Ergonomic_Keyboard_4000-event-kbd
E: DEVNAME=/dev/input/event0
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb2/2-9/2-9:1.0/0003:045E:00DB.0001/input/input0/event0
E: ID_BUS=usb
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_INPUT_KEYBOARD=1
E: ID_MODEL=Natural®_Ergonomic_Keyboard_4000
E: ID_MODEL_ENC=Natural®\x20Ergonomic\x20Keyboard\x204000
E: ID_MODEL_ID=00db
E: ID_PATH=pci-0000:00:14.0-usb-0:9:1.0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_9_1_0
E: ID_REVISION=0173
E: ID_SERIAL=Microsoft_Natural®_Ergonomic_Keyboard_4000
E: ID_TYPE=hid
E: ID_USB_DRIVER=usbhid
E: ID_USB_INTERFACES=:030101:030000:
E: ID_USB_INTERFACE_NUM=00
E: ID_VENDOR=Microsoft
E: ID_VENDOR_ENC=Microsoft
E: ID_VENDOR_ID=045e
E: KEYBOARD_KEY_c022d=up
E: KEYBOARD_KEY_c022e=down
E: LIBINPUT_DEVICE_GROUP=3/45e/db:usb-0000:00:14.0-9
E: MAJOR=13
E: MINOR=64
E: SUBSYSTEM=input
E: TAGS=:power-switch:
E: USEC_INITIALIZED=2642207
E: XKBLAYOUT=us,ru
E: XKBMODEL=pc105
E: XKBOPTIONS=grp:ctrl_shift_toggle,grp_led:scroll
E: XKBVARIANT=,

**Comment by poettering** [comment] 2018-11-16 23:21
Duplicate of #8413

**Closed as completed by poettering** 2018-11-16 23:21 UTC
Labels: udev
