### ISSUE TITLE
Fails to build with gcc9

### ISSUE THREAD

**Issue by rossburton** [systemd/systemd#12454] opened 2019-05-01 11:51 UTC
systemd 242 fails with gcc9 (9.0.1 snapshot 7833ad1 to be precise):

```
In file included from ../git/src/basic/macro.h:549,
                 from ../git/src/basic/alloc-util.h:9,
                 from ../git/src/network/networkd-link.c:9:
In function 'link_enable_ipv6',
    inlined from 'link_set_mtu' at ../git/src/network/networkd-link.c:1483:16:
../git/src/basic/log.h:104:9: error: '%s' directive argument is null [-Werror=format-overflow=]
  104 |         log_internal_realm(LOG_REALM_PLUS_LEVEL(LOG_REALM, (level)), __VA_ARGS__)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../git/src/shared/log-link.h:21:25: note: in expansion of macro 'log_internal'
   21 |                         log_internal(level, error, __FILE__, __LINE__, __func__, ##__VA_ARGS__); \
      |                         ^~~~~~~~~~~~
../git/src/shared/log-link.h:33:50: note: in expansion of macro 'log_link_full'
   33 | #define log_link_warning_errno(link, error, ...) log_link_full(link, LOG_WARNING, error, ##__VA_ARGS__)
      |                                                  ^~~~~~~~~~~~~
../git/src/network/networkd-link.c:324:17: note: in expansion of macro 'log_link_warning_errno'
  324 |                 log_link_warning_errno(link, r, "Cannot %s IPv6 for interface %s: %m",
      |                 ^~~~~~~~~~~~~~~~~~~~~~
../git/src/network/networkd-link.c: In function 'link_set_mtu':
../git/src/network/networkd-link.c:324:79: note: format string is defined here
  324 |                 log_link_warning_errno(link, r, "Cannot %s IPv6 for interface %s: %m",
      |                                                                               ^~
```

**Comment by benjarobin** [comment] 2019-05-01 18:08
Duplicate of #12373 ? 
The only problem is that `gcc 9.0.1 snapshot 7833ad1` is more recent than `gcc-9.0.1-0.10.fc30.x86_64`

**Comment by kraj** [comment] 2019-05-02 02:57
@benjarobin yes the issues are same and is still prevalent with latest gcc from `gcc-9-branch`

**Comment by mrc0mmand** [comment] 2019-05-02 20:20
Tried this with the latest Fedora Rawhide gcc9 build (`gcc (GCC) 9.0.1 20190430 (Red Hat 9.0.1-0.16)`) and the compilation went fine.

**Comment by kraj** [comment] 2019-05-03 17:48
@mrc0mmand I guess there could be difference in commandline arguments, in Yocto/OE we use security related warning flags in addition to defaults. See below, are you compiling with similar options ?

`
x86_64-yoe-linux-gcc -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-
strong -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/m
nt/a/yoe/build/tmp/work/core2-64-yoe-linux/systemd/1_242+AUTOINC+1e5d2d6564-r0/recipe-sysr
oot -Isrc/network/70b1c79@@networkd-core@sta -Isrc/network -I../git/src/network -Isrc/basi
c -I../git/src/basic -Isrc/shared -I../git/src/shared -Isrc/systemd -I../git/src/systemd -
Isrc/journal -I../git/src/journal -Isrc/journal-remote -I../git/src/journal-remote -Isrc/n
spawn -I../git/src/nspawn -Isrc/resolve -I../git/src/resolve -Isrc/timesync -I../git/src/t
imesync -I../git/src/time-wait-sync -Isrc/login -I../git/src/login -Isrc/udev -I../git/src
/udev -Isrc/libudev -I../git/src/libudev -Isrc/core -I../git/src/core -Isrc/shutdown -I../
git/src/shutdown -I../git/src/libsystemd/sd-bus -I../git/src/libsystemd/sd-device -I../git
/src/libsystemd/sd-event -I../git/src/libsystemd/sd-hwdb -I../git/src/libsystemd/sd-id128
-I../git/src/libsystemd/sd-netlink -I../git/src/libsystemd/sd-network -I../git/src/libsyst
emd/sd-resolve -Isrc/libsystemd-network -I../git/src/libsystemd-network -I. -I../git/ -fdi
agnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wextra -Werror=undef -Wlogical-op -Wm
issing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsug
gest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -
Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror
=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=
5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shi
ft-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -Wno-unused-parame
ter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Wno-error=n
onnull -Wno-maybe-uninitialized -ffast-math -fno-common -fdiagnostics-show-option -fno-str
ict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-bu
ffer-size=4 -ffunction-sections -fdata-sections -Werror=shadow -include config.h -m64 -mar
ch=core2 -mtune=core2 -msse3 -mfpmath=sse -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wf
ormat -Wformat-security -Werror=format-security --sysroot=/mnt/a/yoe/build/tmp/work/core2-
64-yoe-linux/systemd/1_242+AUTOINC+1e5d2d6564-r0/recipe-sysroot -O2 -g -feliminate-unused-
debug-types -fmacro-prefix-map=/mnt/a/yoe/build/tmp/work/core2-64-yoe-linux/systemd/1_242+
AUTOINC+1e5d2d6564-r0=/usr/src/debug/systemd/1_242+AUTOINC+1e5d2d6564-r0 -fdebug-prefix-ma
p=/mnt/a/yoe/build/tmp/work/core2-64-yoe-linux/systemd/1_242+AUTOINC+1e5d2d6564-r0=/usr/sr
c/debug/systemd/1_242+AUTOINC+1e5d2d6564-r0 -fdebug-prefix-map=/mnt/a/yoe/build/tmp/work/c
ore2-64-yoe-linux/systemd/1_242+AUTOINC+1e5d2d6564-r0/recipe-sysroot= -fdebug-prefix-map=/
mnt/a/yoe/build/tmp/work/core2-64-yoe-linux/systemd/1_242+AUTOINC+1e5d2d6564-r0/recipe-sys
root-native= -fPIC -MD -MQ 'src/network/70b1c79@@networkd-core@sta/networkd-link.c.o' -MF
'src/network/70b1c79@@networkd-core@sta/networkd-link.c.o.d' -o 'src/network/70b1c79@@netw
orkd-core@sta/networkd-link.c.o' -c ../git/src/network/networkd-link.c
`

**Comment by kraj** [comment] 2019-05-03 17:55
particularly this option ```-Werror=format=2``` is interesting. Can you try adding that option to your build ?

**Comment by mrc0mmand** [comment] 2019-05-03 18:33
Thank you for the hint, @kraj! As I could compile systemd even with `-Werror=format=2`, I started experimenting a bit further with the various compilation options you provided and finally managed to find a reliable reproducer of your issue:

```bash
CFLAGS='-D_FORTIFY_SOURCE=2 -O2' meson build 
ninja -C build
```

This leads to the aforementioned error:
```
In file included from ../src/basic/macro.h:549,
                 from ../src/basic/alloc-util.h:9,
                 from ../src/network/networkd-link.c:8:
In function ‘link_enable_ipv6’,
    inlined from ‘link_set_mtu’ at ../src/network/networkd-link.c:1464:16:
../src/basic/log.h:104:9: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
  104 |         log_internal_realm(LOG_REALM_PLUS_LEVEL(LOG_REALM, (level)), __VA_ARGS__)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/shared/log-link.h:21:25: note: in expansion of macro ‘log_internal’
   21 |                         log_internal(level, error, __FILE__, __LINE__, __func__, ##__VA_ARGS__); \
      |                         ^~~~~~~~~~~~
../src/shared/log-link.h:33:50: note: in expansion of macro ‘log_link_full’
   33 | #define log_link_warning_errno(link, error, ...) log_link_full(link, LOG_WARNING, error, ##__VA_ARGS__)
      |                                                  ^~~~~~~~~~~~~
../src/network/networkd-link.c:323:17: note: in expansion of macro ‘log_link_warning_errno’
  323 |                 log_link_warning_errno(link, r, "Cannot %s IPv6 for interface %s: %m",
      |                 ^~~~~~~~~~~~~~~~~~~~~~
../src/network/networkd-link.c: In function ‘link_set_mtu’:
../src/network/networkd-link.c:323:79: note: format string is defined here
  323 |                 log_link_warning_errno(link, r, "Cannot %s IPv6 for interface %s: %m",
      |          
```

It looks like gcc9 is stricter in terms of passing NULL into printf-like functions.

**Comment by mrc0mmand** [comment] 2019-05-03 18:42
Also, browsing through similar issues with gcc9, it looks like this one is actually a feature:

Quote from https://gcc.gnu.org/gcc-9/changes.html#c-family
> `-Wformat-overflow` and `-Wformat-truncation` have been extended to all formatted input/output functions (where applicable) and enhanced to detect a subset of instances of reading past the end of unterminated constant character arrays in %s directives. 

The error indeed goes away with `CFLAGS='-O2 -Wno-format-overflow'`.

**Comment by kraj** [comment] 2019-05-03 18:44
yes we can suppress it sure, but is that the right approach here ?

**Comment by mrc0mmand** [comment] 2019-05-03 19:27
Well, guarding the problematic argument should be enough in this case, like:

```diff
diff --git a/src/network/networkd-link.c b/src/network/networkd-link.c
index 3e22efb92a..15851f2965 100644
--- a/src/network/networkd-link.c
+++ b/src/network/networkd-link.c
@@ -321,7 +321,8 @@ static int link_enable_ipv6(Link *link) {
         r = sysctl_write_ip_property_boolean(AF_INET6, link->ifname, "disable_ipv6", disabled);
         if (r < 0)
                 log_link_warning_errno(link, r, "Cannot %s IPv6 for interface %s: %m",
-                                       enable_disable(!disabled), link->ifname);
+                                       enable_disable(!disabled),
+                                       (link->ifname) ? link->ifname : "<null>");
         else
                 log_link_info(link, "IPv6 successfully %sd", enable_disable(!disabled));
```

but as I'm not familiar with the networking code, I'd ask @yuwata or @keszybz.

**Comment by mrc0mmand** [comment] 2019-05-03 19:30
Also, the gcc9 introduces several new warnings, which might need some attention:

```
[357/1793] Compiling C object 'src/shared/5afaae1@@systemd-shared-242@sta/utmp-wtmp.c.o'.
../src/shared/utmp-wtmp.c: In function ‘utmp_put_init_process’:
../src/shared/utmp-wtmp.c:211:9: warning: ‘strncpy’ specified bound 4 equals destination size [-Wstringop-truncation]
  211 |         strncpy(store.ut_id, sanitize_id(id), sizeof(store.ut_id));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/shared/utmp-wtmp.c:214:17: warning: ‘strncpy’ specified bound 32 equals destination size [-Wstringop-truncation]
  214 |                 strncpy(store.ut_line, basename(line), sizeof(store.ut_line));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/shared/utmp-wtmp.c: In function ‘utmp_put_dead_process’:
../src/shared/utmp-wtmp.c:248:9: warning: ‘strncpy’ specified bound 4 equals destination size [-Wstringop-truncation]
  248 |         strncpy(lookup.ut_id, sanitize_id(id), sizeof(lookup.ut_id));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[444/1793] Compiling C object 'src/udev/3eb56e7@@scsi_id@exe/scsi_id_scsi_serial.c.o'.
../src/udev/scsi_id/scsi_serial.c: In function ‘prepend_vendor_model’:
../src/udev/scsi_id/scsi_serial.c:406:9: warning: ‘strncpy’ output may be truncated copying 8 bytes from a string of length 8 [-Wstringop-truncation]
  406 |         strncpy(serial, dev_scsi->vendor, VENDOR_LENGTH);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/udev/scsi_id/scsi_serial.c:407:9: warning: ‘strncat’ output may be truncated copying 16 bytes from a string of length 16 [-Wstringop-truncation]
  407 |         strncat(serial, dev_scsi->model, MODEL_LENGTH);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by cmyster** [comment] 2019-05-06 02:57
Tested with gcc 9.1.0, adding the -Wno-format-overflow flag worked around the failure but it doesn't feel right.

**Comment by breisig** [comment] 2019-05-06 19:17
I am getting the same error message even with the latest gcc 9.1 release and the latest gcc 9 snapshot [ gcc version 9.1.1 20190504 ]. This needs to get fixed asap.

**Closed as completed** 2019-05-07 23:39 UTC
Labels: not-our-bug
