### ISSUE TITLE
systemd-logind ignoring LidSwitchIgnoreInhibited=yes

### ISSUE THREAD

**Issue by acidg** [systemd/systemd#7137] opened 2017-10-19 08:51 UTC
### Submission type
 - Bug report

### systemd version the issue has been seen with
235

### Used distribution
Arch Linux:
- Kernel 4.13.7
- Gnome 3.26.1

### Expected behavior you didn't see
Laptop going to sleep when closing the lid

### In case of bug report: Unexpected behaviour you saw
Laptop did not go to sleep

### Steps to reproduce the problem
My /etc/systemd/logind.conf:
```
[Login]
#NAutoVTs=6
#ReserveVT=6
#KillUserProcesses=no
#KillOnlyUsers=
#KillExcludeUsers=root
#InhibitDelayMaxSec=5
HandlePowerKey=ignore
HandleSuspendKey=suspend
HandleHibernateKey=hibernate
HandleLidSwitch=suspend
HandleLidSwitchDocked=suspend
#PowerKeyIgnoreInhibited=no
SuspendKeyIgnoreInhibited=yes
#HibernateKeyIgnoreInhibited=no
LidSwitchIgnoreInhibited=yes
#HoldoffTimeoutSec=30s
#IdleAction=ignore
#IdleActionSec=30min
#RuntimeDirectorySize=10%
#RemoveIPC=yes
#InhibitorsMax=8192
#SessionsMax=8192
#UserTasksMax=33%
```

systemd-inhibit --list:
```
     Who: gdm (UID 120/gdm, PID 647/gsd-power)
    What: sleep
     Why: GNOME needs to lock the screen
    Mode: delay

     Who: bene (UID 1000/bene, PID 1443/gsd-media-keys)
    What: handle-power-key:handle-suspend-key:handle-hibernate-key
     Why: GNOME handling keypresses
    Mode: block

     Who: bene (UID 1000/bene, PID 1393/gsd-power)
    What: handle-lid-switch
     Why: Multiple displays attached
    Mode: block

     Who: NetworkManager (UID 0/root, PID 438/NetworkManager)
    What: sleep
     Why: NetworkManager needs to turn off networks
    Mode: delay

     Who: UPower (UID 0/root, PID 573/upowerd)
    What: sleep
     Why: Pause device polling
    Mode: delay

     Who: gdm (UID 120/gdm, PID 635/gsd-media-keys)
    What: handle-power-key:handle-suspend-key:handle-hibernate-key
     Why: GNOME handling keypresses
    Mode: block

     Who: gdm (UID 120/gdm, PID 647/gsd-power)
    What: handle-lid-switch
     Why: Multiple displays attached
    Mode: block

     Who: bene (UID 1000/bene, PID 1393/gsd-power)
    What: sleep
     Why: GNOME needs to lock the screen
    Mode: delay

     Who: GNOME Shell (UID 1000/bene, PID 1276/gnome-shell)
    What: sleep
     Why: GNOME muss den Bildschirm sperren
    Mode: delay

9 inhibitors listed.
```

Log with ```systemd.log_level=debug``` set in boot parameters:
```
Okt 19 09:40:46 schenker systemd-logind[4906]: Lid closed.
Okt 19 09:40:46 schenker systemd-logind[4906]: device-enumerator: scan all dirs
Okt 19 09:40:46 schenker systemd-logind[4906]:   device-enumerator: scanning /sys/bus
Okt 19 09:40:46 schenker systemd[1]: systemd-logind.service: Got notification message from PID 4906 (WATCHDOG=1)
Okt 19 09:40:46 schenker systemd-logind[4906]:   device-enumerator: scanning /sys/class
Okt 19 09:40:46 schenker systemd-logind[4906]: Refusing operation, handle-lid-switch is inhibited.
Okt 19 09:40:46 schenker systemd-logind[4906]: device-enumerator: scan all dirs
Okt 19 09:40:46 schenker systemd-logind[4906]:   device-enumerator: scanning /sys/bus
Okt 19 09:40:46 schenker systemd-logind[4906]:   device-enumerator: scanning /sys/class
Okt 19 09:40:46 schenker systemd-logind[4906]: Refusing operation, handle-lid-switch is inhibited.
Okt 19 09:40:56 schenker systemd-logind[4906]: Lid opened.
```

**Comment by poettering** [comment] 2017-10-20 10:22
The logs actually give a good indication what is going on: GNOME is blocking the sleep operation:

```
Okt 19 09:40:46 schenker systemd-logind[4906]: Refusing operation, handle-lid-switch is inhibited.
```

And the inhibitor list shows who precisely is responsible:

```
     Who: bene (UID 1000/bene, PID 1393/gsd-power)
    What: handle-lid-switch
     Why: Multiple displays attached
    Mode: block
```

i.e. you have multiple displays attached. At least "gsd-power" thinks so. if you don#t think this is right, please contact the "gsd-power" maintainers, but logind is really just honouring the inhibitor that "gsd-power" installed.

Hence, this is not an issue with logind, it does what it is told. Please contact the "gsd-power" folks for help

**Comment by poettering** [comment] 2017-10-20 10:23
uh, i missed that your bug was that we don't ignore the inhibitor even though LidSwitchIgnoreInhibited is set

**Comment by poettering** [comment] 2017-10-20 10:43
Ah, so this is documented behaviour actually. From logind.conf(5):

> PowerKeyIgnoreInhibited=, SuspendKeyIgnoreInhibited=, HibernateKeyIgnoreInhibited=, LidSwitchIgnoreInhibited=
> Controls whether actions that systemd-logind takes when the power and sleep keys and the lid switch are triggered are subject to high-level inhibitor locks ("shutdown", "sleep", "idle"). Low level           inhibitor locks ("handle-power-key", "handle-suspend-key", "handle-hibernate-key", "handle-lid-switch"), are always honored, irrespective of this setting.

So, gsd-power installed a inhibitor for handle-lid-switch as you see in your systemd-inhibit output. And that we honour unconditionally, regardless of the XyzIgnoreInhibited= setting, as documented.

This is confusing, admittedly, but it does make some sense.

To give a bit of background: logind distinguishes high-level and low-level inhibitor locks. high-level inhibitor locks inhibit an actual sleep/shutdown operation being executed, while low-level inhibitors already inhibit the processing of the key event that ultimately might result in the operation. That means, if you close the lid and a suspend shall happen, in theory two inhibitors are consulted: first the inhibitor of the key handling, and if there was none then the inhibitor of the sleep operation. Why this two-layered approach? First of all we permit reconfiguration of what shall happen on which key to some level: while usually closing the lid means suspending, people could reconfigure it to mean "shutdown". Some apps then might want to block/delay suspend (think: cdrecord wants to make sure the cd burning isn't interrupted), while other apps actually want to block the handling of the key at all (for example, because they want to handle it themselves, so that they can show an interactive dialog or whatnot).

Now, some user actions are "stronger" than others. We currently assume that closing the lid is a very explicit operation that means "suspend this", thus while usually we honour all inhibitors we offer the option to ignore the high-level inhibitors for this operation. However we don't do this for the low-level inhibitors, as we assume that that's a DE or so which wants to handle everything on their own, and since they explicitly asked us to take over lid close handling there's little reason to not honour that, and accept it.

Or in other words: your DE explicitly asked to be responsible for lid switch events. Hence, if anything doesn#t work as intended on that, please talk to the DE people responsible for this.

Hence, closing this again, we actually do what we are supposed to do, and the DE asked us not to do anything, so we do.

**Closed as completed by poettering** 2017-10-20 10:43 UTC
Labels: login, not-our-bug

**Comment by acidg** [comment] 2017-10-21 22:50
Thanks you for clarification! This helps a lot :)

**Comment by Fnordbert** [comment] 2023-08-02 06:07
Sorry to resurrect this old issue, but I am struggling to arrive at a definitive answer.
Does this mean it's now _impossible_ to  configure systemd to suspend on lid close when an external monitor is attached?

It seems to me, that would be a completely legitimate and not uncommon behavior to want.
If `HandleLidSwitchDocked` and `LidSwitchIgnoreInhibited` is not intended to support this, then what _are_ they for?
There are lots of confused discussions on these settings, so it would be good to have a clear answer.

( Some suggest setting `IgnoreLid=true` in UPower.conf to prevent gsd-power from taking the lock, but that does not work for me in Ubuntu 22.04, and [that could be intentional](https://gitlab.freedesktop.org/upower/upower/-/issues/246) it seems. )

**Comment by Fnordbert** [comment] 2023-08-02 08:44
Thanks for the quick clarification & confirmation! 
That means I can now focus fully on figuring out whats going on with upower and `IgnoreLid`.
