### ISSUE TITLE
systemd-cryptsetup: cannot enroll a second FIDO2 slot after password was deleted

### ISSUE THREAD

**Issue by Kranzes** [systemd/systemd#25128] opened 2022-10-25 12:34 UTC
### systemd version the issue has been seen with

251.5

### Used distribution

NixOS

### Linux kernel version used

6.0.3

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

I wanted to configure a `systemd-cryptsetup` config where I would have 2 slots enrolled both of which are FIDO2 keys (I've got 1 daily-use YubiKey and then another one as a backup in a safe). When I started using `systemd-cryptenroll` I added my first FIDO2 key to the second slot (password being the 1st slot). I then decided to delete the 1st slot which has the old traditional password as I no longer needed it can am able to unlock the LUK2 device with just the FIDO2 key. I deleted the password and then wanted to add my second (backup) FIDO2 key via `systemd-cryptenroll` but it seems that `systemd-cryptenroll` always asks for a normal passphrase which I no longer have, so I cannot enroll another slot. Luckily I am not locked out as I can *unlock* the device with just the FIDO2 key but I can't *enroll* new slots with it. It would be great If having a password wouldn't be a requirement to enroll new slots via `systemd-cryptsetup` that way I can add more non password/recovery slots without having the need to have one enrolled. Ideally I would have a setup where I have two FIDO2 keys enrolled without any traditional password.

### Unexpected behaviour you saw

`systemd-cryptenroll` did not prompt me to use my only slot (the FIDO2 one) to enroll a second slot. It only prompted me to unlock with a password which I already deleted.

### Steps to reproduce the problem

1. Run `systemd-cryptenroll` on a device and notice that there is already a password slot enrolled
2. Enrolled one of the FIDO2 keys I have
3. Test that unlocking/mount the device via the newly enrolled FIDO2 keys works
4. Delete the password slot from before as it's no longer needed
5. Try to enroll another slot- it prompts for a password that no longer exists and doesn't try to authenticate via the only existing slot available which isn't a password one

**Comment by poettering** [comment] 2022-10-25 12:52
Also see #23544

Duplicate of #20230

**Closed as completed by poettering** 2022-10-25 12:52 UTC
Labels: bug 🐛, cryptsetup

**Comment by 05storm26** [comment] 2022-11-20 16:15
For those that have a trouble recovering from this situation:

Some guides like this: https://access.redhat.com/solutions/1543373 recommend extracting the master key of the luks encryption of the opened luks device using `sudo dmsetup table <luks-name> --showkeys`, and then using the master-key with `cryptsetup luksAddkey` with the `--master-key-file` option.

Turns out that for luks2 formats the kernel keeps the master key in the keyring so by default you can't see the master key using the `dmsetup table --showkeys`. 

To fix this:

`sudo cryptsetup refresh --disable-keyring  <luks-name>`

After that you can get the master key from the running kernel using the above `dmsetup table` and use it to add a new luks key.

```
$ sudo cryptsetup refresh --disable-keyring  <luks-name>
$ cp <(sudo dmsetup table <luks-name> --showkeys | awk '{print$5}' | xxd -r -p) /tmp/master-key
$ sudo cryptsetup luksAddKey /dev/sdX --master-key-file /tmp/master-key
Enter new passphrase for key slot: 
Verify passphrase:
$
```

**Comment by Kranzes** [comment] 2022-12-20 09:21
`sudo cryptsetup refresh --disable-keyring  <luks-name>` requires entering a passphrase which we can't do as we don't have it enrolled anymore.

**Comment by 05storm26** [comment] 2022-12-20 09:24
@Kranzes It worked for me after removing the password. systemd-cryptsetup would unlock it with using the TPM based on the secure boot status of the machine. 

I think that you just need to have it being unlocked, which in my case was done by systemd using the TPM key.

**Comment by Kranzes** [comment] 2022-12-20 09:26
It is unlocked, I am booted after all haha.

**Comment by 05storm26** [comment] 2022-12-20 09:32
I just tried it again: 

```
$ mount | grep luks
/dev/mapper/luks-<long-hyphenated-uuid> on / type ext4 (rw,relatime)
$ sudo cryptsetup refresh --disable-keyring  luks-<long-hyphenated-uuid>
$
```

Are you sure that the *name* of the luks device is "root"? That seems weird to me. Mostly by default at least the luks name is something like "luks-<uuid-hyphenated>".

i.e.:

```
$ sudo dmsetup table
luks-<uuid>: 0 461117440 crypt aes-xts-plain64 ....
````

**Comment by Kranzes** [comment] 2022-12-20 09:33
it is root, yes.

**Comment by 05storm26** [comment] 2022-12-20 09:36
Is your `FIDO2` plugged in when you try to execute the refresh? Can that device be somehow passed with some arguments to `cryptsetup refresh` maybe?

**Comment by Kranzes** [comment] 2022-12-20 09:41
It is connected. The reason it works for you is that `cryptsetup` (non systemd) no supports TPM but it doesn't support FIDO2 yet.

**Comment by 05storm26** [comment] 2022-12-20 09:47
> It is connected. The reason it works for you is that cryptsetup (non systemd) no supports TPM but it doesn't support FIDO2 yet.

(I assume you meant: "that cryptsetup (non systemd) no***w*** supports TPM". )

Yeah that makes sense, in that case this method doesn't work in general.
