### ISSUE TITLE
systemd merges deps of mount unit files and /proc/self/mountinfo, leading to surprising results: systemd automatically unmounts manually mounted filesystems

### ISSUE THREAD

**Issue by rmetrich** [systemd/systemd#9869] opened 2018-08-14 12:49 UTC
**systemd version the issue has been seen with**
> systemd-219 (RHEL7) and later e.g. systemd-238-9 (Fedora 28)

**Used distribution**
 > RHEL7, Fedora 28

**Expected behaviour you didn't see**
 > When a device for an unmounted mount point disappears, nothing happens.

**Unexpected behaviour you saw**
 > When a device for an unmounted mount point disappears, the mount point which was reused for another mount gets automatically unmounted.

**This is a follow-up of Issue #8596 which has been closed unresolved.**

**Steps to reproduce the problem**
 > This is easily reproducible with various devices, such as loopback, iscsi, LVM, scsi disks.
 > Usually, the mount unit is generated by systemd-fstab-generator, but creating the unit manually also works.
 > Simplest reproducer is with loopback:
 >
 > 1. Create loopback device
~~~
# truncate -s 1G /root/file
# losetup /dev/loop1 /root/file
# mkfs.xfs /dev/loop1
~~~

 > 2. Create `mnt.mount` unit for **non-existent** device `/dev/loop0` and **enable** it, so that `multi-user.target` pulls the unit
~~~
# cat /etc/systemd/system/mnt.mount 
[Mount]
What=/dev/loop0
Where=/mnt
Type=xfs
Options=defaults

[Install]
WantedBy=multi-user.target

# systemctl enable mnt.mount
~~~

> 3. Mount `/dev/loop1` as `/mnt` manually
~~~
# mount /dev/loop1 /mnt
~~~

**RESULT**
- `/mnt` is mounted, then automatically unmounted by systemd
- journal shows `mnt.mount: Unit is bound to inactive unit dev-loop0.device. Stopping, too.`

**Additional information**

This happens because `mnt.mount` exists in the dependency tree at the time of the manual mount, due to having `multi-user.target` pull the unit.
Due to having the unit reused, the `BindsTo` property is not updated from `dev-loop0.device` (unit definition) to `dev-loop1.device` (actual device), causing systemd to stop the unit when analyzing the `BindsTo` property internally.
[Red Hat BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1494014) contains the gory details.

This issue is critical, as the administrator will not notice the automatic unmount being done.

**Comment by jsynacek** [comment] 2018-08-20 10:50
I can confirm that this reproduces on systemd-239 as well.

**Comment by poettering** [comment] 2018-09-12 09:44
systemd honours user configuration, and the unit file says it's backed by /dev/loop0, and that doesn't exist so the mount is removed. There's logic in that, but I can see how this is surprising. Currently, when you have a mount in effect whose configuration differs from the .mount unit you supplied then you get a mixture of deps for both definitions. Now, it's probably a good idea not to mix things like this, as you'll not only confuse systemd with it, but most likely the user too. That said, we can probably optimize this but I am not entirely sure how to do that best. I mean this would mean explicitly ignoring unit file definitions (i.e. user configuation) while a mount is active, and that's a bit strange and something we do in no other case.

**Comment by rmetrich** [comment] 2018-10-09 14:13
A solution I can think about is to have the mount unit name be built based on `mountpoint + device`. This would be more unique (but not unique, in case the mount is overloaded).

**Comment by jnielsendotnet** [comment] 2018-10-10 18:33
The unit file example posted by rmetrich is a good illustration of the issue, but for me the real astonishment comes from the interaction of systemd with /etc/fstab. I'm a longtime sysadmin with experience on many platforms but not a systemd guru. Before I ran in to this bug I had no idea that systemd did anything at all with fstab. Now I'm paranoid about making ANY changes to fstab on a running system without going through a methodical process of manually unmounting, commenting out the line in fstab, running "systemctl daemon-reload", then adding any new mounts. Please see the RH bugzilla report for additional context.

I agree that checking that the currently-mounted filesystem matches the device systemd has on record before doing anything like unmounting it is a minimal starting point. I assume the point of automatically unmounting is supposed to be to avoid (further) damage to the system state if a device backing a filesystem goes away; however unmounting a HEALTHY filesystem on a HEALTHY device because an OLD device goes away is bad bad bad.

**Comment by rodehoed** [comment] 2019-02-06 09:01
We are seeing this exact behaviour also on our RHEL7 servers. But we are having another use case. This problem is triggered when the backup client starts to backup and when the puppet client (and it's restarting services) run on the same time. 

We use R1Soft backup software which make a snapshot on a  special partition (/dev/hcp1) and when the client is done than it unmounts that partition systemd is unmounting the /var partition and renders the server useless.

> Feb  5 13:37:10 xxxxxxxx kernel: hcp: INFO: dec_device_user: 2,9942,cdp-2-6
Feb  5 13:37:10 xxxxxxxx kernel: hcp: INFO: stopping hcp session hcp1.
Feb  5 13:37:10 xxxxxxxx kernel: hcp: INFO: hcp session hcp1 stopped.
Feb  5 13:37:10 xxxxxxxx systemd: Stopping MariaDB database server...
Feb  5 13:37:10 xxxxxxxx systemd: Stopping Avahi mDNS/DNS-SD Stack...
Feb  5 13:37:10 xxxxxxxx systemd: Stopping NTP client/server...
Feb  5 13:37:10 xxxxxxxx systemd: Stopped target Local File Systems.
Feb  5 13:37:10 xxxxxxxx systemd: Stopping Load/Save Random Seed...
Feb  5 13:37:10 xxxxxxxx systemd: Stopped This is the timer to set the schedule for automated renewals.
Feb  5 13:37:10 xxxxxxxx systemd: Stopping The nginx HTTP and reverse proxy server...
Feb  5 13:37:10 xxxxxxxx systemd: Stopping Update UTMP about System Boot/Shutdown...
Feb  5 13:37:10 xxxxxxxx systemd: Stopped Flush Journal to Persistent Storage.
Feb  5 13:37:10 xxxxxxxx chronyd[2938]: chronyd exiting
Feb  5 13:37:10 xxxxxxxx systemd: Stopped Flexible branding.
Feb  5 13:37:10 xxxxxxxx systemd: Stopping The PHP FastCGI Process Manager...
Feb  5 13:37:10 xxxxxxxx systemd: Stopped The nginx HTTP and reverse proxy server.
Feb  5 13:37:10 xxxxxxxx systemd: Stopped Update UTMP about System Boot/Shutdown.
Feb  5 13:37:10 xxxxxxxx systemd: Stopped The PHP FastCGI Process Manager.
Feb  5 13:37:10 xxxxxxxx systemd: Stopped Load/Save Random Seed.
Feb  5 13:37:10 xxxxxxxx avahi-daemon[2887]: Got SIGTERM, quitting.
Feb  5 13:37:10 xxxxxxxx avahi-daemon[2887]: Leaving mDNS multicast group on interface eth0.IPv4 with address ip.ip.ip.ip.
Feb  5 13:37:10 xxxxxxxx avahi-daemon[2887]: avahi-daemon 0.6.31 exiting.
Feb  5 13:37:10 xxxxxxxx systemd: Stopped NTP client/server.
Feb  5 13:37:10 xxxxxxxx systemd: Stopped Avahi mDNS/DNS-SD Stack.
Feb  5 13:37:10 xxxxxxxx systemd: Closed Avahi mDNS/DNS-SD Stack Activation Socket.
Feb  5 13:37:11 xxxxxxxx systemd: Stopped The NGINX part of SMT.
Feb  5 13:37:15 xxxxxxxx systemd: Stopped MariaDB database server.
Feb  5 13:37:15 xxxxxxxx systemd: Unmounting /var...
Feb  5 13:37:15 xxxxxxxx umount: umount: /var: target is busy.
Feb  5 13:37:15 xxxxxxxx umount: (In some cases useful info about processes that use
Feb  5 13:37:15 xxxxxxxx umount: the device is found by lsof(8) or fuser(1))
Feb  5 13:37:15 xxxxxxxx systemd: var.mount mount process exited, code=exited status=32
Feb  5 13:37:15 xxxxxxxx systemd: Failed unmounting /var.
Feb  5 13:37:15 xxxxxxxx systemd: Unit var.mount is bound to inactive unit dev-disk-by\x2duuid-7ec6b55c\x2d5923\x2d4dd2\x2db8aa\x2da821e84f71ee.device. Stopping, too.
Feb  5 13:37:15 xxxxxxxx systemd: Unmounting /var...
Feb  5 13:37:15 xxxxxxxx umount: umount: /var: target is busy.
Feb  5 13:37:15 xxxxxxxx umount: (In some cases useful info about processes that use
Feb  5 13:37:15 xxxxxxxx umount: the device is found by lsof(8) or fuser(1))

**Comment by btibor91** [comment] 2019-04-12 11:56
It looks like we're facing the same issue, too (CentOS 7.6.1810, systemd 219):

```
Apr 10 04:54:47 server01.domain.com kernel: hcp: INFO: dec_device_user: 8,30181,cdp-2-6
Apr 10 04:54:47 server01.domain.com kernel: hcp: INFO: stopping hcp session hcp1.
Apr 10 04:54:48 server01.domain.com systemd[1]: Unmounting /home...
Apr 10 04:54:48 server01.domain.com umount[18911]: umount: /home: target is busy.
Apr 10 04:54:48 server01.domain.com umount[18911]: (In some cases useful info about processes that use
```

Any update on this? Is there any known workaround/temporary fix possible?

**Comment by msg7086** [comment] 2019-04-23 02:59
Hit hard on systemd 232 on Debian 9 when I was re-creating an MD device.

Workaround for me was to `systemctl daemon-reload`.

**Comment by archiecobbs** [comment] 2019-04-30 14:42
This bug is preventing my system from booting up properly with desired filesystems mounted.

openSUSE Leap 15.0 with systemd-234-lp150.19.1. Prior to the most recent upgrade, this had been working fine for years.

In my scenario, I have mount A and mount B. Mount A contains a "disk image" file which is then used as a loopback mount by mount B. Mount A is a FUSE filesystem ([s3backer](https://github.com/archiecobbs/s3backer)).

When my system boots up, mount A succeed but mount B fails.

My `/etc/fstab`:

```
# Mount A
s3backer#mybucket /mnt/s3b fuse [s3backer flags elided]...,timeout=90,_netdev,x-systemd.requires=firewalld.service 0 0

# Mount B
/mnt/s3b/file /mnt/backup ext4 loop,discard,noatime,nodiratime,_netdev,x-systemd.requires=mnt-s3b.mount 0 0

```

Here's `journalctl -xe` output:

```
Apr 30 09:14:35 rebound systemd[1]: Mounting /mnt/s3b...
-- Subject: Unit mnt-s3b.mount has begun start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit mnt-s3b.mount has begun starting up.
Apr 30 09:14:36 rebound s3backer[3412]: established new mount token 0x54982055
Apr 30 09:14:36 rebound s3backer[3412]: s3backer process 3412 for /mnt/s3b started
Apr 30 09:14:37 rebound systemd[1]: Mounted /mnt/s3b.
-- Subject: Unit mnt-s3b.mount has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit mnt-s3b.mount has finished starting up.
-- 
-- The start-up result is done.
Apr 30 09:14:37 rebound s3backer[3421]: mounting /mnt/s3b
Apr 30 09:14:42 rebound systemd[1]: Unnecessary job for /dev/loop0 was removed.
-- Subject: Unit dev-loop0.device has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit dev-loop0.device has failed.
-- 
-- The result is collected.
Apr 30 09:14:42 rebound systemd[1]: mnt-backup.mount: Bound to unit dev-loop0.device, but unit isn't active.
Apr 30 09:14:42 rebound systemd[1]: Dependency failed for /mnt/backup.
-- Subject: Unit mnt-backup.mount has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit mnt-backup.mount has failed.
-- 
-- The result is dependency.
```

FYI [this comment](https://bugzilla.redhat.com/show_bug.cgi?id=1494014#c20) seems to give a consistent description of how this problem occurs, from what I can tell. Why is this taking so long to fix?

Question: is there some way to workaround this problem (other than manual intervention)? E.g., some change to `/etc/fstab` that will avoid it? E.g., somehow hard-coding the loopback device?

**Comment by arvidjaar** [comment] 2019-05-01 06:52
Sounds like another variant of https://github.com/systemd/systemd/issues/1741

**Comment by karelzak** [comment] 2019-06-13 10:56
@rmetrich had a good point.

In mount(8)/libmount when we search in mount table (for example for mount -a) we identify mounts by source+target[+fsroot].

It's not enough to use only source or target because the same device is possible to mount on more places and more filesystems is possible to mount to the same mountpoint. (And in case of bind-mount or btrfs subroot you also need to check fsroot because more directories from the same filesystem is possible to mount on different places). 

Unfortunately, src/core/mount.c in mount_load_proc_self_mountinfo() uses only unit_name_from_path(where, ".mount", &e), and all is based on "where" (mount target). The result is that systemd on the fly makes a new connection between "where.mount" configuration and some completely new situation in the kernel mount table.

It would be probably better in mount code to replace unit_name_from_path() + manager_get_unit() with something more sophisticated and also check for complete "where+what" tuple. It would be also opportunity to support more mount units for the same mount point. The old "where.mount" should be maintained as fallback for backward compatibility only.

@poettering ?

**Comment by holymonson** [comment] 2019-06-19 14:21
Meeting the opposite situation: Consider an entry with `automount` in `fstab`, mounted by systemd. If user umount it and then access the path, systemd will mount it automatically, without notifying user.

The key point is, __systemd should respect user's manual operation__. When user manually and effectively `mount` or `umount` a path, systemd should mask the corresponding `.mount` file in runtime, by linked to `/dev/null` in `/run/systemd` somewhere. And systemd could unmask them when user run `mount -a`.

This may fix both issuses, without the `mountpoint + device` solution.

**Comment by amg1127** [comment] 2019-06-19 16:11
In my humble opinion, if the administrator user specifies the *automount*
option in *fstab*, he/she is explicitly requesting systemd to mount
something automatically. This mimics the behavior of mount points
controlled by an *autofs *daemon, for example, and is in accordance with
the idea conveyed by a word composed of "auto" (automatic) + "mount".

**Comment by holymonson** [comment] 2019-06-19 16:43
> In my humble opinion, if the administrator user specifies the *automount*
> option in *fstab*, he/she is explicitly requesting systemd to mount
> something automatically. This mimics the behavior of mount points
> controlled by an *autofs *daemon, for example, and is in accordance with
> the idea conveyed by a word composed of "auto" (automatic) + "mount".

The way I see it is, `automount` means requesting to be mounted when it needs. But when the user manually `umount`, it has indicated he/she is taking over control, the system should step down, unless the control is manually released. Shouldn't a direct command from user be prior to an entry in config file?

**Comment by archiecobbs** [comment] 2019-06-19 17:26
I agree with @amg1127 (as would most UNIX administrators I think).

When you `umount` the filesystem, you're not changing the fact that the automount is still in effect. Unless and until you edit `fstab`, you're still telling the system "automount this on demand".

In any case this is distracting from much more serious effects of this bug (e.g., in my case, I can no longer perform automatic backups).

**Comment by holymonson** [comment] 2019-06-20 05:32
> When you umount the filesystem, you're not changing the fact that the automount is still in effect. Unless and until you edit fstab, you're still telling the system "automount this on demand".

When you umount the filesystem, the whole entry in `fstab` becomes inaccurate (e.g., device, fs type, options), so why should `automount` only stay in effect? 

The situation @archiecobbs concern is, __the admin him/herself umount a filesystem, but count on systemd could automatically mount it back__. If it does damage, should it blame systemd instead of the admin him/herself?

Manual `mount`/`umount` is a behavior outside `fstab`, but systemd always sticks to `fstab`, there must be some conflicts unavoidable. It can be solved only one of them step down: 
1. Prevent manual operation violating `fstab`, unless `fstab` is modified (and maybe reload into systemd); 
2. Or systemd restrain itself on conflicting entries, and it may block other units depend on them.

**Comment by arvidjaar** [comment] 2019-06-20 17:48
> Consider an entry with `automount` in fstab, mounted by systemd. If user umount it

It is not clear what do you mean. Automount always consists of two halves - top and bottom. Top can be considered as just a handle; access to top triggers mounting of bottom which is actual filesystem with data. After that top is sort of hidden as long as bottom remains mounted.

It is possible that systemd conflates both, I have not looked in the details.

If you unmount top half, then I tend to agree with you (except unmounting top does not automatically implies unmounting bottom). If you unmount bottom then you are mistaken - this is normal part of automount handling. May be your confusion comes from the fact that first umount actually unmounts bottom half.

**Comment by archiecobbs** [comment] 2019-06-20 18:32
Also, automounter functionality has been around for decades, while systemd is new, and was designed to replicate the previous behavior.

If you look that previous behavior, i.e., how systems used to work prior to systemd, then you'll see that it was the exact same behavior: if you unmount an automounted filesystem, and then later come back and touch the automount directory, the automounter would re-mount the filesystem.

Now this behavior may be a problem (in your view), but it's not a systemd problem.

In fact the automounter typically had an idle timeout feature so it would unmount the filesytem itself after a period of inactivity. That would put you into the exact same state as before: filesystem is unmounted, but will mount on demand.

**Comment by poettering** [comment] 2020-01-21 14:40
Current systemd versions are capable of updating deps picked up from udev and /proc/self/mountinfo automatically, and we also don't use BindsTo= between .mount and their backing devices anymore. Thus this should be fixed doubly with current systemd versions. If reproducible still, please open a new bug and provide a new minimal reproducer.

**Comment by msekletar** [comment] 2021-02-11 17:59
This is still reproducible with latest systemd version.

**Closed as completed** 2021-05-25 20:07 UTC
Labels: needs-discussion 🤔, pid1, downstream/rhel
