### ISSUE TITLE
 [RFE] Add support for cgroup templates

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#7651] opened 2017-12-15 09:01 UTC
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with
systemd-219-42.el7_4.4.x86_64
> …

### Used distribution
RHEL-7
> …

It would be nice if we could create cgroup templates for user slices the similar way it's possible in RHEL-6:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/resource_management_guide/sec-moving_a_process_to_a_control_group

I.e. The aim is to set a default limit for every user in terms of memory/cpu it can consume.
This is currently not possible (we can only do it for explicitly specified user slices).

**Comment by poettering** [comment] 2017-12-15 09:33
See #7599.

**Comment by poettering** [comment] 2017-12-15 09:34
Duplicate of #2556

**Closed as completed by poettering** 2017-12-15 09:34 UTC
Labels: RFE 🎁, pid1, duplicate
