### ISSUE TITLE
mount units cannot unmount fuse systems on user bus

### ISSUE THREAD

**Issue by stewbond** [systemd/systemd#19809] opened 2021-06-03 16:39 UTC
**systemd version the issue has been seen with**
```
systemd 247 (247.3-5)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
```
**Used distribution**
> Debian testing

**Linux kernel version used** (`uname -a`)
```
Linux stewbian 5.10.0-6-amd64 #1 SMP Debian 5.10.28-1 (2021-04-09) x86_64 GNU/Linux
```

**CPU architecture issue was seen on**
> x86_64

**Expected behaviour you didn't see**
> `systemctl --user stop *.mount` should `umount` fuse system and the unit should be inactive.

**Unexpected behaviour you saw**
> `systemctl --user stop *.mount` causes unit to remain active instead of unmounting fuse-system

**Steps to reproduce the problem**
With `sshfs` installed and an ssh key accepted on the remote machine:
```bash
stew ~ $ systemctl --user cat home-stew-shared.mount
# /home/stew/.config/systemd/user/home-stew-shared.mount
[Mount]
What=%u@192.168.1.9:
Where=%h/shared
Type=fuse.sshfs

stew ~ $ systemctl --user start home-stew-shared.mount
stew ~ $ mount | grep shared
stew@192.168.1.9: on /home/stew/shared type fuse.sshfs (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
```
At this point, I have a good mount.  But if I try to unmount it:
```bash
stew ~ $ systemctl --user stop home-stew-shared.mount
stew ~ $ systemctl --user status home-stew-shared.mount
● home-stew-shared.mount - /home/stew/shared
     Loaded: loaded (/home/stew/.config/systemd/user/home-stew-shared.mount; static)
     Active: active (mounted) (Result: exit-code) since Thu 2021-06-03 18:27:22 CEST; 11s ago
      Where: /home/stew/shared
       What: stew@192.168.1.9:
      Tasks: 6 (limit: 14237)
     Memory: 3.5M
        CPU: 26ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/home-stew-shared.mount
             ├─87069 ssh -x -a -oClearAllForwardings=yes -2 stew@192.168.1.9 -s sftp
             └─87075 sshfs stew@192.168.1.9: /home/stew/shared -o rw,dev,suid

Jun 03 18:27:03 stewbian systemd[1029]: Mounting /home/stew/shared...
Jun 03 18:27:04 stewbian systemd[1029]: Mounted /home/stew/shared.
Jun 03 18:27:22 stewbian systemd[1029]: Unmounting /home/stew/shared...
Jun 03 18:27:22 stewbian umount[87098]: umount: /home/stew/shared: must be superuser to unmount.
Jun 03 18:27:22 stewbian systemd[1029]: home-stew-shared.mount: Mount process exited, code=exited, status=32/n/a
Jun 03 18:27:22 stewbian systemd[1029]: Failed unmounting /home/stew/shared.
stew ~ $ mount | grep shared
stew@192.168.1.9: on /home/stew/shared type fuse.sshfs (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
```
We can see the unit is still active and the system is still mounted.  I need to unmount manually and fail the unit:
```bash
stew ~ $ umount ~/shared
stew ~ $ mount | grep shared
stew ~ $ systemctl --user status home-stew-shared.mount
● home-stew-shared.mount - /home/stew/shared
     Loaded: loaded (/home/stew/.config/systemd/user/home-stew-shared.mount; static)
     Active: failed (Result: exit-code) since Thu 2021-06-03 18:28:03 CEST; 22s ago
      Where: /home/stew/shared
       What: stew@192.168.1.9:
      Tasks: 0 (limit: 14237)
     Memory: 4.0K
        CPU: 28ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/home-stew-shared.mount

Jun 03 18:27:22 stewbian systemd[1029]: home-stew-shared.mount: Mount process exited, code=exited, status=32/n/a
Jun 03 18:27:22 stewbian systemd[1029]: Failed unmounting /home/stew/shared.
Jun 03 18:28:03 stewbian systemd[1029]: home-stew-shared.mount: Failed with result 'exit-code'.
Jun 03 18:28:03 stewbian systemd[1029]: home-stew-shared.mount: Unit process 87069 (ssh) remains running after unit stopped.
```

----

Expected behaviour can be observed if I manually create `/sbin/umount.fuse.sshfs` with this:

```bash
#!/bin/sh
/bin/fusermount -u "$1"
```
Then I get this expected behaviour
```bash
stew ~ $ systemctl --user cat home-stew-shared.mount
# /home/stew/.config/systemd/user/home-stew-shared.mount
[Mount]
What=%u@192.168.1.9:
Where=%h/shared
Type=fuse.sshfs

stew ~ $ systemctl --user start home-stew-shared.mount
stew ~ $ mount | grep shared
stew@192.168.1.9: on /home/stew/shared type fuse.sshfs (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
stew ~ $ systemctl --user stop home-stew-shared.mount
stew ~ $ mount | grep shared
stew ~ $ systemctl --user status home-stew-shared.mount
● home-stew-shared.mount - /home/stew/shared
     Loaded: loaded (/home/stew/.config/systemd/user/home-stew-shared.mount; static)
     Active: inactive (dead)
      Where: /home/stew/shared
       What: stew@192.168.1.9:

Jun 03 18:21:29 stewbian systemd[1029]: Mounting /home/stew/shared...
Jun 03 18:21:29 stewbian systemd[1029]: Mounted /home/stew/shared.
Jun 03 18:21:56 stewbian systemd[1029]: Unmounting /home/stew/shared...
Jun 03 18:21:56 stewbian systemd[1029]: home-stew-shared.mount: Succeeded.
Jun 03 18:21:56 stewbian systemd[1029]: home-stew-shared.mount: Unit process 86820 (ssh) remains running after unit stopped.
Jun 03 18:21:56 stewbian systemd[1029]: Unmounted /home/stew/shared.
```

I would love to see systemd do what `umount` does when I call it as an unprivileged user when working on the user-bus.

**Comment by poettering** [comment] 2021-06-03 20:11
Duplicate of #17788

**Closed as completed by poettering** 2021-06-03 20:11 UTC
Labels: pid1, duplicate
