### ISSUE TITLE
systemd-resolved "DNSSEC=allow-downgrade" fails

### ISSUE THREAD

**Issue by jonathan-gruber-jg** [systemd/systemd#32561] opened 2024-04-29 14:32 UTC
### systemd version the issue has been seen with

255.5

### Used distribution

Arch Linux

### Linux kernel version used

6.8.7-arch1-2

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

When a server does not support DNSSEC and systemd-resolved is configured with the option "DNSSEC=allow-downgrade" in the "[Resolve]" section, systemd-resolved should fall back to non-DNSSEC mode. In this case, systemd-resolved might log something like "Server \<insert IP\> does not support DNSSEC, downgrading to non-DNSSEC mode."

### Unexpected behaviour you saw

When a server does not support DNSSEC and systemd-resolved is configured with the option "DNSSEC=allow-downgrade" in the "[Resolve]" section, systemd-resolved seemingly does not fall back to non-DNSSEC mode and instead reports "DNSSEC validation failed" and fails to resolve any domain names.

I have attached the output of 'SYSTEMD_LOG_LEVEL=debug journalctl -u systemd-resolved.service --all', for the most recent boot that I had systemd-resolved configured in the way mentioned above, in various output formats for your convenience.

[json.log](https://github.com/systemd/systemd/files/15150574/json.log)
[json-pretty.log](https://github.com/systemd/systemd/files/15150575/json-pretty.log)
[short.log](https://github.com/systemd/systemd/files/15150576/short.log)
[short-full.log](https://github.com/systemd/systemd/files/15150577/short-full.log)
[verbose.log](https://github.com/systemd/systemd/files/15150578/verbose.log)

### Steps to reproduce the problem

I do not know much about networking, so I apologize if I use widely incorrect terminology here or if these steps are wrong.

1) Configure systemd-resolved with "DNSSEC=allow-downgrade" set in the "[Resolve]" section.
2) Connect to a network with a DNS server that does not support DNSSEC.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Relevant log files are attached above.
```

**Comment by LRitzdorf** [comment] 2024-04-29 16:41
Same issue here, also on Arch, which seems to have appeared with the update to systemd 255.5.
Also, cross-reference #32531; this might be a duplicate?

**Comment by rpigott** [comment] 2024-04-29 19:48
Yes, this appears to be a duplicate of #32531. A debug log of sd-resolved could confirm.

**Comment by bluca** [comment] 2024-04-29 21:05
https://github.com/systemd/systemd/issues/32531

**Closed as not planned by bluca** 2024-04-29 21:05 UTC
Labels: bug 🐛, resolve, duplicate
