### ISSUE TITLE
RFE: enqueue stop, restart, reload jobs from timer units, not just start

### ISSUE THREAD

**Issue by johannbg** [systemd/systemd#3866] opened 2016-08-02 16:38 UTC
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)

Looking at thread [1] there is an use case to support to run execution as in starting/stopping/reload/restart of type service units in type timer units. 

If looking at the following answer from Kai Krakow it requires the user to create 4 new type units, two new service types units and two new timer types to be scheduled with each other.
That could be reduced to two timer types unit if Execute= option would be introduced to be used in conjuction with the Unit one.

Two type timer units would then only be required and look something like this
# start-vpn.timer

[Unit]
Description=Start VPN at 07:00 every day

[Timer]
Execute=start
Unit=openvpn.service
OnCalendar=07:00

[Install]
WantedBy=multi-user.target
# stop-vpn.timer

[Unit]
Description=Stop VPN at 17:00 every day

[Timer]
Execute=stop
Unit=openvpn.service
OnCalendar=17:00 

[Install]
WantedBy=multi-user.target

This could also just use the existing naming convention in type service units as in ExecStart,ExecReload, ExecStop which would then translate to this for the above usecase on the list.
# start-vpn.timer

[Unit]
Description=Start VPN at 07:00 every day

[Timer]
ExecStart
Unit=openvpn.service
OnCalendar=07:00

[Install]
WantedBy=multi-user.target
# stop-vpn.timer

[Unit]
Description=Stop VPN at 17:00 every day

[Timer]
ExecStop
Unit=openvpn.service
OnCalendar=17:00 

[Install]
WantedBy=multi-user.target
1. https://lists.freedesktop.org/archives/systemd-devel/2016-August/037270.html

**Comment by poettering** [comment] 2016-08-03 14:38
This has been requested before, but I am not convinced we really should cover both activation an deactivation with timer units. If people want that they may activate a "systemct stop" invocation after all.

**Comment by johannbg** [comment] 2016-08-03 20:30
One approach is to cover activation/restart/reload/deactivation of type service units the other would be to introduce the ability to run an command or script directly from the type timer units since the fundamental problem here is that you cannot execute an command directly from an type timer unit ( unless I did not get the memo ) so user will always require a two type units ( service and a timer ) to trigger a single task to run a script or a an command ( which could be systemctl stop/reload/restart for an service ). 

Basically this 
*/10 \* \* \* \* /usr/bin/echo sample >> /tmp/sample.txt

has effectively become this.. 

# sample.service

[Unit]
Description=Echo's sample into temporary sample file

[Service]
Type=oneshot
ExecStart=/usr/bin/sh -c '/usr/bin/echo sample >> /tmp/sample.txt'

# sample.timer

[Unit]
Description=Echo sample every 15 minutes

[Timer]
Unit=sample.service
OnCalendar=*:0/15

Administrators gained 10 lines by using type service units ( one line in type service unit is equivalent of 10 lines in legacy sysv init script ) however as you can see it's the opposite with type timer units in which a single line in cron amounts to two type unit files ( service and an timer ) and 10 lines in total in those files.

By introducing Execute= in which administrators could run an script or command directly it would reduce the file number of one and the line number in half as in.

[Unit]
Description=Echo sample every 15 minutes

[Timer]
OnCalendar=*:0/15
Execute=/usr/bin/echo sample >> /tmp/sample.txt

There are most certainly legit use cases both in the ability to deactivating type service units ( think maintenance windows with scheduled downtime ) as well as the ability to run an script or an command directly from within the timer unit itself.

What was the reason why we did not want to run command directly from within timer units themselves from the get go? ( I cant recall what it was. )

**Comment by miaofengwei** [comment] 2016-08-06 00:26
add a new unit type autotimer?

**Comment by poettering** [comment] 2017-05-12 13:07
Closing as duplicate of #3642.

**Closed as completed by poettering** 2017-05-12 13:07 UTC
Labels: RFE 🎁, pid1, duplicate

**Comment by uasan** [comment] 2017-12-02 15:09
Is any progress?

Thanks.
