### ISSUE TITLE
systemd-nspawn bind device node

### ISSUE THREAD

**Issue by embetrix** [systemd/systemd#26890] opened 2023-03-19 12:12 UTC
### systemd version the issue has been seen with

250

### Used distribution

Any

### Linux kernel version used

5.10.116

### CPU architectures issue was seen on

arm

### Component

systemd-nspawn

### Expected behaviour you didn't see

bind device nodes with systemd.nspawn config files is not working

### Unexpected behaviour you saw

bind device nodes with systemd.nspawn config files cannot write to

### Steps to reproduce the problem

```
[Exec]
Boot=off
Parameters=/bin/dd if=/dev/random of=/dev/fb0


[Network]
VirtualEthernet=no

[Files]
Bind=/dev/fb0
BindReadOnly=/bin 
BindReadOnly=/usr/bin 
BindReadOnly=/lib 
BindReadOnly=/usr/lib 
```
```
# systemctl start systemd-nspawn@test.service
# systemctl status systemd-nspawn@test.service
x systemd-nspawn@test.service - Container test
     Loaded: loaded (8;;file://stm32mp157c-rufma/lib/systemd/system/systemd-nspawn@.service/lib/systemd/system/systemd-nspawn@.service8;;; disabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Sun 2023-03-19 12:05:39 UTC; 2s ago
       Docs: 8;;man:systemd-nspawn(1)man:systemd-nspawn(1)8;;
    Process: 5489 ExecStart=systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest --network-veth -U --settings=override --machine=test (code=exited, status=1/FAILURE)
   Main PID: 5489 (code=exited, status=1/FAILURE)
     Status: "Terminating..."

Mar 19 12:05:39 stm32mp157c-rufma systemd[1]: Starting Container test...
Mar 19 12:05:39 stm32mp157c-rufma systemd[1]: Started Container test.
Mar 19 12:05:39 stm32mp157c-rufma systemd-nspawn[5489]: dd: can't open '/dev/fb0': Operation not permitted
Mar 19 12:05:39 stm32mp157c-rufma systemd[1]: systemd-nspawn@test.service: Main process exited, code=exited, status=1/FAILURE
Mar 19 12:05:39 stm32mp157c-rufma systemd[1]: systemd-nspawn@test.service: Failed with result 'exit-code'.
```

whereas using --bind option directly with systemd-nspawn is working:

```
# systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest --network-veth -U --settings=override --machine=test --bind=/dev/fb0
dd: error writing '/dev/fb0': No space left on device
301+0 records in
300+0 records out
153600 bytes (150.0KB) copied, 0.012988 seconds, 11.3MB/s
```

**Comment by embetrix** [comment] 2023-03-19 13:01
I solved this by setting property:

```
systemctl set-property systemd-nspawn@test DeviceAllow='/dev/fb0 rwm'
```

**Comment by embetrix** [comment] 2023-03-19 13:02
I would think that Bind setting in _systemd.nspawn_ is equivalent to _--bind_ option of _systemd-nspawn_ command but they are not !

**Comment by embetrix** [comment] 2023-03-20 13:55
it looks like if the kernel config **CONFIG_USER_NS** is set the bind of device node doesn't work in either ways!

**Comment by poettering** [comment] 2024-11-05 12:45
Duplicate of #20271

**Closed as completed by poettering** 2024-11-05 12:45 UTC
Labels: nspawn, documentation, not-a-bug
