### ISSUE TITLE
Suspend-then-hibernate does not work, yet both work fine by themselves

### ISSUE THREAD

**Issue by initzx** [systemd/systemd#25703] opened 2022-12-11 16:19 UTC
### systemd version the issue has been seen with

252.3-1

### Used distribution

Arch Linux 

### Linux kernel version used

6.0.12-arch1-1 but also 5.15.82-1-lts

### CPU architectures issue was seen on

x86_64

### Component

systemd-logind

### Expected behaviour you didn't see

By setting HibernateDelaySec=1 in sleep.conf, the system should suspend first and then hibernate immediately. 

### Unexpected behaviour you saw

When triggering systemctl suspend-then-hibernate or closing lid. The system suspends perfectly but never enters into hibernation after the set amount of time. 

### Steps to reproduce the problem

Run systemctl suspend-then-hibernate

**Comment by kolayne** [comment] 2022-12-11 16:43
Looks like a duplicate of #25269

**Closed as completed** 2022-12-12 06:14 UTC
Labels: bug 🐛, login, duplicate, sleep
