### ISSUE TITLE
freeze after "Starting Flush Journal to Persistent Storage"

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#2994] opened 2016-04-08 17:55 UTC
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> systemd 229

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

> I am expecting that I boot normally.
### In case of bug report: Unexpected behaviour you saw

> The boot sequence freezes.
### In case of bug report: Steps to reproduce the problem

> Just boot
### Further Explaination

I have this freeze only sometimes. The most time it's working fine.
Here is my journalctl log for the last boot with this behaviour:

https://paste.archlinux.de/qfvBTK/

It will everytime freeze at the same point and the fan is getting very noisy..

**Comment by poettering** [comment] 2016-04-15 08:17
Please have a look at:

https://freedesktop.org/wiki/Software/systemd/Debugging/

It has recommendations how to debug boot problems. Among other things, please enable the debug shell, and check with tools like "ps", "top", "systemctl list-jobs" what is hanging there, and what is consuming so much CPU that your fan gets noisy.

**Comment by shibumi** [comment] 2016-04-16 16:45
I have needed 3 boots today to boot up my system. Everytime it has freezed during boot process. I needed to Hard-Reset. I can't even change the TTY or go in to rescue shell or something. At the third boot the system bootet up without problem.

I wanted to check the boots via journalctl but I get the following: `journalctl --list-boots`

```
root@motoko ~ # journalctl --list-boots 
Failed to determine boots: No data available
```

But seems like: `journalctl -b <boot>` is working. Here are my last two boots with freezing:

https://paste.archlinux.de/J39d4T/

https://paste.archlinux.de/s569sL/

EDIT: I will enable the systemd debug shell. I hope that I can jump in the debug shell next time when the boot freezes.. I will also check my RAM next boot.. just for making sure it's not the RAM.

**Comment by poettering** [comment] 2016-04-17 12:37
I'd guess this is some sort of driver bug, as your logs all end when udev tries to trigger the hw so that the various drivers are load. Most likely one of them brings your system to a standstill...

The fact that the journal flushing thing is the last thing you see doesn't mean too much. After all the boot is pretty much fully parallelized now. Driver probing and userspace startup all run in parallel then.

My recommendation would be to check after a successful boot which drivers are loaded (via "lsmod") and then play around and see if you blacklist some of them whether you get to a reliable boot-up. Primary candidates that could be at fault here are i2c and graphics drivers.

**Comment by jimgao1** [comment] 2016-09-26 22:12
Currently experiencing the same problem with a Thinkpad W530 running using dedicated graphics card (NVidia K1000M) running Arch Linux.

**Comment by ekce** [comment] 2016-09-27 00:37
I started getting this today too on a Thinkpad T420 running Arch Linux with a discrete video card (last night I uninstalled bumblebee, installed nvidia's libgl, and disabled the integrated card in the BIOS). The card is identified as: NVIDIA Corporation GF119M [Quadro NVS 4200M].

The freezing has been a little random. This last time it took me at least five attempts to boot.

The last messages to appear in my journal before the crash are always:

```
Sep 26 17:54:54 anu systemd[1]: Starting udev Kernel Device Manager...
Sep 26 17:54:54 anu systemd[1]: Reached target Local File Systems (Pre).
Sep 26 17:54:54 anu systemd-journald[187]: Journal started
Sep 26 17:54:53 anu systemd-modules-load[179]: Inserted module 'vboxdrv'
Sep 26 17:54:53 anu systemd-modules-load[179]: Inserted module 'vboxpci'
Sep 26 17:54:53 anu systemd-modules-load[179]: Inserted module 'vboxnetadp'
Sep 26 17:54:53 anu systemd-modules-load[179]: Inserted module 'vboxnetflt'
Sep 26 17:54:54 anu systemd[1]: Started Journal Service.
Sep 26 17:54:54 anu systemd[1]: Starting Flush Journal to Persistent Storage...
-- Reboot --
```

(The last one shown on screen is the udev kernel device manager message but the last one in the log is always the flush journal to persistent storage message).

Each time it freezes I have no choice but to do a hard reboot as the computer becomes completely unresponsive.

There was one single time when it crashed after booting and I'm not 100% sure it was related.

```
Sep 26 12:32:47 anu kernel: NVRM: GPU at PCI:0000:01:00: GPU-6102695c-6ef4-7a7e-b287-464e2ba9d6b8
Sep 26 12:32:47 anu kernel: NVRM: Xid (PCI:0000:01:00): 8, Channel 00000000
Sep 26 12:32:49 anu kernel: NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
Sep 26 12:32:51 anu kernel: NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
Sep 26 12:33:03 anu kernel: NVRM: Xid (PCI:0000:01:00): 8, Channel 00000001
Sep 26 12:33:03 anu kernel: NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
Sep 26 12:33:08 anu kernel: NVRM: Xid (PCI:0000:01:00): 16, Head 00000000 Count 0000426b
Sep 26 12:33:12 anu kernel: NVRM: Xid (PCI:0000:01:00): 8, Channel 00000001
Sep 26 12:33:13 anu kernel: NVRM: os_schedule: Attempted to yield the CPU while in atomic or interrupt context
Sep 26 12:33:32 anu dhclient[568]: DHCPREQUEST on wlp3s0 to 136.159.253.46 port 67
Sep 26 12:33:32 anu dhclient[568]: DHCPACK from 136.159.253.46
Sep 26 12:33:32 anu NetworkManager[422]: <info>  [1474914812.8886] dhcp4 (wlp3s0):   address 10.13.67.59
Sep 26 12:33:32 anu NetworkManager[422]: <info>  [1474914812.8889] dhcp4 (wlp3s0):   plen 24 (255.255.255.0)
Sep 26 12:33:32 anu NetworkManager[422]: <info>  [1474914812.8889] dhcp4 (wlp3s0):   gateway 10.13.67.1
Sep 26 12:33:32 anu NetworkManager[422]: <info>  [1474914812.8889] dhcp4 (wlp3s0):   server identifier 136.159.253.46
Sep 26 12:33:32 anu NetworkManager[422]: <info>  [1474914812.8889] dhcp4 (wlp3s0):   lease time 600
Sep 26 12:33:32 anu NetworkManager[422]: <info>  [1474914812.8889] dhcp4 (wlp3s0):   nameserver '136.159.1.21'
Sep 26 12:33:32 anu NetworkManager[422]: <info>  [1474914812.8889] dhcp4 (wlp3s0):   nameserver '136.159.34.201'
Sep 26 12:33:32 anu NetworkManager[422]: <info>  [1474914812.8890] dhcp4 (wlp3s0):   domain name 'ucalgary.ca'
Sep 26 12:33:32 anu NetworkManager[422]: <info>  [1474914812.8890] dhcp4 (wlp3s0): state changed bound -> bound
Sep 26 12:33:32 anu dbus[391]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org.freedesktop.nm-dispatcher.service'
Sep 26 12:33:32 anu systemd[1]: Starting Network Manager Script Dispatcher Service...
Sep 26 12:33:32 anu dbus[391]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Sep 26 12:33:32 anu systemd[1]: Started Network Manager Script Dispatcher Service.
Sep 26 12:33:32 anu nm-dispatcher[939]: req:1 'dhcp4-change' [wlp3s0]: new request (0 scripts)
Sep 26 12:33:32 anu nm-dispatcher[939]: req:1 'dhcp4-change' [wlp3s0]: completed: no scripts
Sep 26 12:33:33 anu dhclient[568]: bound to 10.13.67.59 -- renewal in 286 seconds.
Sep 26 12:33:47 anu wpa_supplicant[441]: wlp3s0: CTRL-EVENT-SIGNAL-CHANGE above=1 signal=-34 noise=9999 txrate=300000
Sep 26 12:33:55 anu systemd-logind[389]: Power key pressed.
-- Reboot --
```

**Comment by keszybz** [comment] 2016-10-15 20:23
Since stopping right after "Starting Flush Journal to Persistent Storage" seems to be the common theme, you could disable persistent logs (e.g. temporarily rename /var/log/journal to something else), and see if that changes anything. I doubt that this will change much, because the crash probably happens when the system becomes busy, and the flushing of the journal just happens to be the first thing that does that.

**Comment by poettering** [comment] 2017-05-12 13:54
Closing this bug. Most likely not caused by systemd, and no feedback in a while

**Closed as completed by poettering** 2017-05-12 13:54 UTC
Labels: needs-reporter-feedback ❓

**Comment by nponeccop** [comment] 2017-11-29 00:18
JFYI the problem still happens in Arch, but now it's only in exotic configurations, namely with LTS kernels on i686 under Microsoft Hyper-V. The same Hyper-V and kernels don't hang with Debian, so it could be some difference in kernel config/compiler that makes it hang.

**Comment by atilaneves** [comment] 2019-04-03 16:56
This bug still exists. No exotic configuration, standard Arch installed today. I've had this problem from the get-go on my Dell XPS15 and only around 10% of my boots didn't hang. I tried debugging the issue and added `systemd.log_level=debug`. It still hangs every now and again but I managed to get 4 consecutive boots for the first time ever.

I assume it's a race condition of some sort given that it doesn't happen all of the time.

**Comment by vcaputo** [comment] 2019-04-03 18:56
@atilaneves When the hang occurs, assuming you're seeing something similar to the original reporter with the high CPU usage/fans racing once hung, could you try using magic sysrq to dump things like the stack traces for all active CPUs?  sysrq-l for that one.

sysrq-w and sysrq-t would be nice as well, but may require some serial/netconsole setup to capture its contents, though a camera could probably capture a video of the output scrolling if needed.

Considering how few reports we're getting of this nature, it seems very likely to be a specific kernel/driver/hw issue and not a systemd bug.  I have an Arch system here that reboots daily in a hands-free headless arrangement, and it *never* hangs on boot.

**Comment by atilaneves** [comment] 2019-04-04 09:32
@vcaputo I don't hear the fan. 

I think it's probably a systemd bug. I didn't have this problem yesterday with Artix Linux, and the fact that it's random is probably due to systemd's multithreaded startup. The fact that `systemd.log_level-debug` makes the issue manifest a lot less frequently is another indication that the problem is with systemd.

It's unlikely to be a driver issue because a bare Arch install boots successfully. It's only after I install a package (any package! `sudo` is enough) that the issue *immediately* starts again. The Arch iso also boots successfully and consistently.

I'll try and see if I get anything from sysrq.

**Comment by atilaneves** [comment] 2019-04-04 12:04
I added these kernel parameters:

```
systemd.log_level=debug systemd.log_target=console console=tty1 sysrq_always_enabled=1 systemd.debug-shell=1
```

Lots of output on the screen. But when it hangs, I can't sysrq to do anything. I also can't use the debug shell. I can't do anything except hard reset.

So I tried changing the default target. `local-fs.target` always boots, but as early as `sysinit.target` the system starts hanging again. `local-fs.target` however always ends up waiting for 90s for the SSD.

**Comment by poettering** [comment] 2019-04-04 12:11
if the system hangs and doesn't react to sysrq it appears this is a hard kernel lockup, i.e. systemd might trigger something there, but is not where the bug is...

**Comment by vcaputo** [comment] 2019-04-04 19:07
If you haven't already, it's worth verifying the magic sysrq stuff is functional when the system isn't hung before drawing any conclusions.

Some keyboards, like the ThinkPad ultranavs, can require awkward Fn-key contortions.

**Comment by atilaneves** [comment] 2019-04-05 12:04
I tried sysrq after a normal boot and that worked... so the kernel is definitely being affected by something systemd is doing.

**Comment by vcaputo** [comment] 2019-04-05 20:04
@atilaneves Sounds like a kernel bug.

Userspace shouldn't be able to hang the kernel like that, maybe one of your kernel modules is hanging the machine when the device is probed.

For starters make sure your system isn't booting in `quiet` mode so you can see all the dmesg output on the console as it boots.  You may just have to blacklist a buggy kernel module or something like that.

At this point the focus should shift away from systemd, it's a kernel/boot hang issue to debug accordingly.

FWIW on my primary personal machines I build a monolithic kernel with just the drivers for the devices I need to use with it enabled.  It greatly reduces the surface area for these kinds of issues, and if a hang does occur the bug search space is narrowed down to what I have explicitly turned on in the kernel config.  Some distros get angry without loadable module support though, YMMV.

**Comment by shibumi** [comment] 2019-04-05 20:12
I have no issues since some months on Arch Linux, by the way.  I guess it had something to do with the kernel. So definitely not a systemd bug.

**Comment by Davidrjx** [comment] 2021-01-30 04:10
smilar with case above, most often debian linux system reboots automatically, before and after that reboot, no much valuable info besides snippet looks like 
```
...
Jan 30 10:22:56 ai-2080ti-xx kubelet[1679]: W0130 10:22:56.147751    1679 reflector.go:256] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: w
atch of *v1.Pod ended with: too old resource version: 664783077 (664784732)
Jan 30 10:25:01 ai-2080ti-xx CRON[34038]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Jan 30 10:35:01 ai-2080ti-xx CRON[85659]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Jan 30 10:45:01 ai-2080ti-xx CRON[1424]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Jan 30 10:55:01 ai-2080ti-xx CRON[90919]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Jan 30 11:02:42 ai-2080ti-xx kubelet[1679]: W0130 11:02:42.161649    1679 reflector.go:256] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: w
atch of *v1.Pod ended with: too old resource version: 664817273 (664820735)
Jan 30 11:05:01 ai-2080ti-xx CRON[135595]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Jan 30 11:15:01 ai-2080ti-xx CRON[13752]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Jan 30 11:18:28 ai-2080ti-xx systemd-modules-load[1238]: Inserted module 'psmouse'
Jan 30 11:18:28 ai-2080ti-xx systemd-modules-load[1238]: Inserted module 'ipmi_devintf'
Jan 30 11:18:28 ai-2080ti-xx systemd[1]: Starting Flush Journal to Persistent Storage...
Jan 30 11:18:28 ai-2080ti-xx systemd[1]: Started Load/Save Random Seed.
Jan 30 11:18:28 ai-2080ti-xx systemd[1]: Started LVM2 metadata daemon.
Jan 30 11:18:28 ai-2080ti-xx systemd[1]: Started udev Coldplug all Devices.
Jan 30 11:18:28 ai-2080ti-xx kernel: [    0.000000] Linux version 4.9.0-8-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debia
n 6.3.0-18+deb9u1) ) #1 SMP Debian 4.9.144-3 (2019-02-02)
Jan 30 11:18:28 ai-2080ti-xx systemd[1]: Started Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling.
Jan 30 11:18:28 ai-2080ti-xx kernel: [    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-4.9.0-8-amd64 root=UUID=81dccfc0-2080-48e9-8f9d-1dfa53d3
d341 ro nomodeset cgroup_enable=memory swapaccount=1 quiet
Jan 30 11:18:28 ai-2080ti-xx kernel: [    0.000000] x86/fpu: Supporting XSAVE feature 0x001: 'x87 floating point registers'
Jan 30 11:18:28 ai-2080ti-xx kernel: [    0.000000] x86/fpu: Supporting XSAVE feature 0x002: 'SSE registers'
Jan 30 11:18:28 ai-2080ti-xx kernel: [    0.000000] x86/fpu: Supporting XSAVE feature 0x004: 'AVX registers'
...
```

**Comment by shibumi** [comment] 2021-01-30 15:11
@Davidrjx  this looks more like a kernel issue for me.

**Comment by worksasintended** [comment] 2022-01-12 11:39
Tried to get an old W520 going again, same issue here. I think I remember having this issue only with the nvidia card active (I use the old 390-dkms for it). 
Unfortunately, the integrated intel graphics card cannot use the digital graphic ports....

**Comment by JakeDevs** [comment] 2023-02-23 13:25
Any updates on this? Happens for me as well
