### ISSUE TITLE
Documentation Should Include Version Numbers

### ISSUE THREAD

**Issue by Kurt-von-Laven** [systemd/systemd#1949] opened 2015-11-19 05:42 UTC
It would be ideal if systemd's documentation included annotations specifying what version specific features were added in. For example, http://www.freedesktop.org/software/systemd/man/systemd.service.html#Type= mentions: "Behavior of dbus is similar to simple; however, it is expected that the daemon acquires a name on the D-Bus bus, as configured by BusName=. systemd will proceed with starting follow-up units after the D-Bus bus name has been acquired. Service units with this option configured implicitly gain dependencies on the dbus.socket unit. This type is the default if BusName= is specified." If I understand https://github.com/systemd/systemd/commit/45f06b3450174a9649a51a0b48fdbbbe98f2bb5d correctly, dbus.socket is only added when Type=dbus in systemd version 228 and higher. This request is for some indication of which version of systemd specific parts of the documentation apply to.

**Comment by poettering** [comment] 2015-11-22 21:58
Duplicate of #1712.

**Closed as completed by poettering** 2015-11-22 21:58 UTC
Labels: RFE 🎁, documentation, duplicate
