### ISSUE TITLE
systemd-run does not support SystemCallFilter and SystemCallErrorNumber

### ISSUE THREAD

**Issue by tfheen** [systemd/systemd#7129] opened 2017-10-18 18:15 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 234

### Used distribution

> Debian

### In case of bug report: Expected behaviour you didn't see

> The output of ls in the directory I ran the command in

### In case of bug report: Unexpected behaviour you saw

> Unknown assignment SystemCallFilter=~fsync sync syncfs fdatasync msync sync_file_range.
> Failed to create bus message: Invalid argument

### In case of bug report: Steps to reproduce the problem

> `systemd-run --user --wait --tty -p SystemCallFilter="~fsync sync syncfs fdatasync msync sync_file_range" -p SystemCallErrorNumber=0 -- ls`

**Comment by yuwata** [comment] 2017-10-19 03:19
I think PR #6497 implements what you want to do, and the PR is merged in v235. If possible, please test with v235.

**Comment by tfheen** [comment] 2017-10-19 05:24
Seems to still not work, but the error message is different:
```
$ systemd-run --user --wait --tty -p SystemCallFilter="~fsync sync syncfs fdatasync msync sync_file_range" -p SystemCallErrorNumber=0 -- ls        
Failed to create bus message: Invalid argument
Failed to create bus message: Invalid argument
```

**Comment by yuwata** [comment] 2017-10-19 05:34
Confirmed.

**Comment by yuwata** [comment] 2017-10-19 05:46
At least `SystemCallErrorNumber=0` is not a valid setting. From systemd.exec(5)
> SystemCallErrorNumber=
           Takes an "errno" error number name to return when the system call           filter configured with SystemCallFilter= is triggered, instead of           terminating the process immediately. Takes an error name such as           EPERM, EACCES or EUCLEAN. When this setting is not used, or when the empty string is assigned, the process will be terminated           immediately when the filter is triggered.

So, `$ systemd-run --user --wait --tty -p SystemCallErrorNumber=EPERM -- ls` is meaningless but works fine.

`SystemCallFilter=` setting in `systemd-run` seems to be broken...

**Comment by yuwata** [comment] 2017-10-19 07:11
`RestrictAddressFamilies=` is also broken...

**Comment by yuwata** [comment] 2017-10-19 12:31
I've created PR #7141. If possible, please test it.

**Comment by tfheen** [comment] 2017-10-21 05:08
> At least `SystemCallErrorNumber=0` is not a valid setting.

Huh, indeed, you're right, it gives me a parse error.

It would be quite useful to have the ability to specify 0/"ignore" there too (since there's no `EOK` or similar errno for returning 0).  The use case is to mask out certain system calls such as `fsync` and so more easily implement something along the lines of `eatmydata` without ugly `LD_PRELOAD` hacks.

**Comment by poettering** [comment] 2017-10-23 16:47
please file an RFE for the "ignore" errno thing. Not entirely sure we can actually implement this with libseccomp, but otherwise I figure we can add that

**Comment by tfheen** [comment] 2017-10-23 17:05
Done, https://github.com/systemd/systemd/issues/7129#issuecomment-338722427

**Closed as completed** 2017-10-24 13:25 UTC
Labels: bug 🐛, run
