### ISSUE TITLE
container does not reboot when it is started by machinectl or systemctl

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#9540] opened 2018-07-08 21:23 UTC
**systemd version the issue has been seen with**

239

**Used distribution**

Debian unstable. A bug report was filed at the downstream as
[https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903288](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903288)
Reporting to the upstream was suggested there.

**Expected behaviour you didn't see**

`systemctl reboot` in a container reboots the container.

**Unexpected behaviour you saw**

A systemd-nspawn container does not reboot if it is started by `machinectl` or `systemctl` on the host Linux. The key error messages are as below, in particular `systemd-nspawn[943]: Failed to register machine: Machine 'container-unstable' already exists`

```
Jul 08 21:17:17 unstable systemd[1]: Starting Container container-unstable...
Jul 08 21:17:17 unstable systemd-nspawn[943]: Failed to register machine: Machine 'container-unstable' already exists
Jul 08 21:17:17 unstable systemd[1]: systemd-nspawn@container-unstable.service: Main process exited, code=exited, status=1/FAILURE
Jul 08 21:17:17 unstable systemd[1]: systemd-nspawn@container-unstable.service: Failed with result 'exit-code'.
Jul 08 21:17:17 unstable systemd[1]: Failed to start Container container-unstable.
Jul 08 21:17:17 unstable systemd[1]: systemd-nspawn@container-unstable.service: Consumed 31ms CPU time, received 0B IP traffic, sent 0B IP traffic
```

If I start it as
`systemd-nspawn -b -M container-unstable --network-ipvlan=wls3`
then `systemctl reboot` inside the container works as expected.

**Steps to reproduce the problem**

The below is transcript to reproduce the above:

```
root@unstable:/var/tmp# machinectl start container-unstable
root@unstable:/var/tmp# machinectl list
MACHINE            CLASS     SERVICE        OS VERSION ADDRESSES     
container-desktop  container systemd-nspawn -  -       192.168.1.131
container-unstable container systemd-nspawn -  -       192.168.1.130

2 machines listed.
```

```
root@unstable:/var/tmp# ssh -l root 192.168.1.130
root@192.168.1.130's password: 
Linux container-unstable 4.17.0-1-amd64 #1 SMP Debian 4.17.3-1 (2018-07-02) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sun Jul  8 21:13:16 2018 from 192.168.1.129
```

```
root@container-unstable:~# systemctl reboot
Connection to 192.168.1.130 closed by remote host.
Connection to 192.168.1.130 closed.
root@unstable:/var/tmp# machinectl list
MACHINE           CLASS     SERVICE        OS VERSION ADDRESSES     
container-desktop container systemd-nspawn -  -       192.168.1.131

1 machines listed.
```

```
root@unstable:/var/tmp# journalctl -n 20 -u systemd-nspawn@container-unstable --no-pager
-- Logs begin at Sun 2018-07-08 21:06:44 JST, end at Sun 2018-07-08 21:17:17 JST. --
Jul 08 21:17:15 unstable systemd-nspawn[867]: [FAILED] Failed unmounting /tmp.
Jul 08 21:17:15 unstable systemd-nspawn[867]: [  OK  ] Unmounted /run/systemd/nspawn/incoming.
Jul 08 21:17:15 unstable systemd-nspawn[867]: [  OK  ] Reached target Unmount All Filesystems.
Jul 08 21:17:15 unstable systemd-nspawn[867]: [  OK  ] Stopped target Local File Systems (Pre).
Jul 08 21:17:15 unstable systemd-nspawn[867]: [  OK  ] Stopped Remount Root and Kernel File Systems.
Jul 08 21:17:15 unstable systemd-nspawn[867]: [  OK  ] Stopped target Swap.
Jul 08 21:17:15 unstable systemd-nspawn[867]: [  OK  ] Reached target Shutdown.
Jul 08 21:17:15 unstable systemd-nspawn[867]: [  OK  ] Reached target Final Step.
Jul 08 21:17:15 unstable systemd-nspawn[867]:          Starting Reboot...
Jul 08 21:17:17 unstable systemd[1]: systemd-nspawn@container-unstable.service: Consumed 1.083s CPU time, received 13.1K IP traffic, sent 8.5K IP traffic
Jul 08 21:17:17 unstable systemd[1]: systemd-nspawn@container-unstable.service: Service RestartSec=100ms expired, scheduling restart.
Jul 08 21:17:17 unstable systemd[1]: systemd-nspawn@container-unstable.service: Scheduled restart job, restart counter is at 1.
Jul 08 21:17:17 unstable systemd[1]: Stopped Container container-unstable.
Jul 08 21:17:17 unstable systemd[1]: systemd-nspawn@container-unstable.service: Consumed 1.083s CPU time, received 13.1K IP traffic, sent 8.5K IP traffic
Jul 08 21:17:17 unstable systemd[1]: Starting Container container-unstable...
Jul 08 21:17:17 unstable systemd-nspawn[943]: Failed to register machine: Machine 'container-unstable' already exists
Jul 08 21:17:17 unstable systemd[1]: systemd-nspawn@container-unstable.service: Main process exited, code=exited, status=1/FAILURE
Jul 08 21:17:17 unstable systemd[1]: systemd-nspawn@container-unstable.service: Failed with result 'exit-code'.
Jul 08 21:17:17 unstable systemd[1]: Failed to start Container container-unstable.
Jul 08 21:17:17 unstable systemd[1]: systemd-nspawn@container-unstable.service: Consumed 31ms CPU time, received 0B IP traffic, sent 0B IP traffic
root@unstable:/var/tmp# 
```

**Comment by yuwata** [comment] 2018-07-09 02:30
Seems duplicate of #2809.

**Comment by ryutaroh-matsumoto** [comment] 2018-07-09 02:53
@yuwata I agree. Thank you.

**Closed as completed by ryutaroh-matsumoto** 2018-07-09 02:53 UTC
Labels: nspawn, duplicate
