### ISSUE TITLE
Bug: systemctl restart a.service starts more services than it should

### ISSUE THREAD

**Issue by zmlpjuran** [systemd/systemd#5470] opened 2017-02-27 13:48 UTC
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 219
+ studied news and issues, there is nothing similar.

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> 7.3 RedHat

### In case of bug report: Expected behaviour you didn't see

> only b.service should be restarted

### In case of bug report: Unexpected behaviour you saw

> c.service should not be restarted
> it should not be inconsistent in described configuration modifications

### In case of bug report: Steps to reproduce the problem

> I have 3 services, all are static, described bellow. b part of a, c part of a,  a running, b running, c stopped
Using command
systemctl restart a 
a and b are restarted c is not restarted. That's OK
If I add line
After=c.service
to [Unit] section of b.service, c is restarted too in same scenario. That's not OK.

Same problem will appear if services are bound using Require= directive (b requires a, c requires a)

# a.service
[Unit]
Description=TEST A
[Service]
ExecStart=/usr/bin/run-infinite-loop.sh A
 
# b.service
[Unit]
Description=TEST B
PartOf=a.service
[Service]
ExecStart=/usr/bin/run-infinite-loop.sh B

#c.service
[Unit]
Description=TEST C
PartOf=a.service
[Service]
ExecStart=/usr/bin/run-infinite-loop.sh C

Same problem occurs when services are binded using Requires= directive, b requires a, c requires a

**Comment by zmlpjuran** [comment] 2017-04-19 08:46
Hi, can anybody confirm the issue?

**Comment by arvidjaar** [comment] 2017-05-01 17:10
I cannot reproduce it with systemd 232.

**Comment by poettering** [comment] 2017-05-02 12:05
note that we do not track issues in such old systemd versions here. Please contact your downstream distro for help in that case. We only track issues in the two most recently released systemd versions upstream, and right now thats 233 and 232, which recieved numerous fixes over 219, also in the area you encountered the issue in.

Hence, I will close this, in particular as @arvidjaar was not able to reproduce this on 232. 

Thank you for your understanding, and please make sure to contact your downtsream distro for help.

**Closed as completed by poettering** 2017-05-02 12:05 UTC
Labels: version-too-ancient
