### ISSUE TITLE
journalctl: support negated matching

### ISSUE THREAD

**Issue by lucaswerkmeister** [systemd/systemd#4529] opened 2016-10-31 16:39 UTC
### Submission type

  - [ ] Bug report
  - [x] Request for enhancement (RFE)

I think it would be very useful if `journalctl` supported negative / inverted matches in addition to ordinary ones, for example with the operator `!=` known from most programming languages. (There’s no danger of collision with fields like `FIELD!`, since journal fields can only contain A-Z0-9_ – see `valid_user_field`.)

Example uses:

- Hide “time has been changed” message that frequently seems to annoy users ([example](https://unix.stackexchange.com/questions/166639/how-to-disable-systemds-time-has-been-changed-message-spam-in-systemd-journal), also witnessed on IRC):

        journalctl MESSAGE_ID!=c7a787079b354eaaa9e77b371893cd27

- Hide info messages from some very talkative services:

        journalctl PRIORITY!=info + _SYSTEMD_UNIT!=postfix.service _SYSTEMD_UNIT!=opendkim.service _SYSTEMD_UNIT!=spamassassin.service

A related issue is #4091, but I hope this one is more feasible to implement. I expect `journalctl` would apply all usual matches as before, and then apply the inverted matches to the results. This should require no changes to the journal file format.

**Comment by poettering** [comment] 2016-11-01 13:34
duplicate of #2720

**Closed as completed by poettering** 2016-11-01 13:34 UTC
Labels: RFE 🎁, journal, duplicate

**Comment by lucaswerkmeister** [comment] 2016-11-01 13:44
Sorry, I couldn’t find it with any of the search terms I tried. Thanks for the info.
