### ISSUE TITLE
resolved hangs when resolving resolve local hostname

### ISSUE THREAD

**Issue by Stebalien** [systemd/systemd#7160] opened 2017-10-22 20:40 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

> systemd 235
+PAM -AUDIT -SELINUX -IMA -APPARMOR -SMACK -SYSVINIT -UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid

### Used distribution

> Arch Linux (custom systemd build that removes a few features I don't need)

### In case of bug report: Expected behaviour you didn't see

> Firefox starts

### In case of bug report: Unexpected behaviour you saw

> Firefox hangs on start

### In case of bug report: Steps to reproduce the problem

1. Connect to a crappy public wifi network (bonus points for captive portals and weird MTUs :)).
2. Connect to a VPN with network-manager (openvpn)
3. Starting Firefox and watch it hang (until systemd-resolved is restarted). It appears to be blocking on resolving the local machine's hostname (something that should *always* succeed immediately, without hitting the network).

This should give you some context but, unfortunately, I'm pretty sure it isn't sufficient to reproduce this problem (you probably have to be on *this* wifi and *this* VPN). I've attached what I have so far below, that should be significantly more useful.

---

I debugged this a bit and it appears that Firefox is stuck waiting for systemd-resolved to finish the following dbus call:

```
method call time=1508703825.173362 sender=:1.751 -> destination=org.freedesktop.resolve1 serial=2 path=/org/freedesktop/resolve1; interface=org.freedesktop.resolve1.Manager; member=ResolveHostname
   int32 0
   string "raft"
   int32 2
   uint64 0
```

Where "raft" is my machine's hostname.

The strace from systemd-resolved is:

```
strace: Process 4047 attached
epoll_pwait(4, [{EPOLLIN, {u32=1848319072, u64=9708474408032}}], 16, -1, NULL, 8) = 1
clock_gettime(CLOCK_BOOTTIME, {tv_sec=3400, tv_nsec=337721922}) = 0
recvmsg(11, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\1\2\1 \0\0\0\2\0\0\0\267\0\0\0\1\1o\0\31\0\0\0", iov_len=24}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 24
recvmsg(11, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="/org/freedesktop/resolve1\0\0\0\0\0\0\0"..., iov_len=208}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 208
sendmsg(11, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\1\0\1\226\0\0\0*\4\0\0\177\0\0\0\1\1o\0\25\0\0\0/org/fre"..., iov_len=144}, {iov_base="\221\0\0\0type='signal',sender='org.fr"..., iov_len=150}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 294
recvmsg(11, {msg_namelen=0}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
ppoll([{fd=11, events=POLLIN}], 1, {tv_sec=24, tv_nsec=999977000}, NULL, 8) = 1 ([{fd=11, revents=POLLIN}], left {tv_sec=24, tv_nsec=999897854})
recvmsg(11, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\2\1\1\0\0\0\0005\3\0\0005\0\0\0\6\1s\0\6\0\0\0", iov_len=24}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 24
recvmsg(11, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base=":1.440\0\0\5\1u\0*\4\0\0\7\1s\0\24\0\0\0org.free"..., iov_len=48}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 48
sendmsg(11, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\1\0\1\v\0\0\0+\4\0\0\177\0\0\0\1\1o\0\25\0\0\0/org/fre"..., iov_len=144}, {iov_base="\6\0\0\0:1.715\0", iov_len=11}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 155
recvmsg(11, {msg_namelen=0}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
ppoll([{fd=11, events=POLLIN}], 1, {tv_sec=24, tv_nsec=999977000}, NULL, 8) = 1 ([{fd=11, revents=POLLIN}], left {tv_sec=24, tv_nsec=999913750})
recvmsg(11, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\2\1\1\v\0\0\0006\3\0\0=\0\0\0\6\1s\0\6\0\0\0", iov_len=24}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 24
recvmsg(11, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base=":1.440\0\0\5\1u\0+\4\0\0\10\1g\0\1s\0\0\7\1s\0\24\0\0\0"..., iov_len=67}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 67
stat("/etc/hosts", {st_mode=S_IFREG|0644, st_size=314, ...}) = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=3400, tv_nsec=338383181}) = 0
epoll_pwait(4, [{EPOLLIN, {u32=1848281496, u64=9708474370456}}], 17, -1, NULL, 8) = 1
clock_gettime(CLOCK_BOOTTIME, {tv_sec=3403, tv_nsec=96843126}) = 0
read(13, "\1\0\0\0\0\0\0\0", 8)         = 8
epoll_ctl(4, EPOLL_CTL_DEL, 14, NULL)   = 0
close(14)                               = 0
socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 14
setsockopt(14, SOL_IP, IP_UNICAST_IF, [33554432], 4) = 0
connect(14, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("75.75.75.75")}, 16) = 0
epoll_ctl(4, EPOLL_CTL_ADD, 14, {EPOLLIN, {u32=1848335392, u64=9708474424352}}) = 0
write(14, "[\244\1\0\0\1\0\0\0\0\0\1\4raft\10hanahaus\3com\0\0"..., 46) = 46
timerfd_settime(13, TFD_TIMER_ABSTIME, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=3404, tv_nsec=96325000}}, NULL) = 0
epoll_pwait(4, [{EPOLLIN, {u32=1848335392, u64=9708474424352}}], 17, -1, NULL, 8) = 1
clock_gettime(CLOCK_BOOTTIME, {tv_sec=3403, tv_nsec=117713941}) = 0
recvfrom(14, NULL, 0, MSG_PEEK|MSG_TRUNC, NULL, NULL) = 35
recvmsg(14, {msg_name={sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("75.75.75.75")}, msg_namelen=128->16, msg_iov=[{iov_base="[\244\201\205\0\1\0\0\0\0\0\0\4raft\10hanahaus\3com\0\0"..., iov_len=3928}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 35
epoll_ctl(4, EPOLL_CTL_DEL, 14, NULL)   = 0
close(14)                               = 0
socket(AF_INET, SOCK_DGRAM|SOCK_CLOEXEC|SOCK_NONBLOCK, IPPROTO_IP) = 14
setsockopt(14, SOL_IP, IP_UNICAST_IF, [33554432], 4) = 0
connect(14, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("76.76.76.76")}, 16) = 0
epoll_ctl(4, EPOLL_CTL_ADD, 14, {EPOLLIN, {u32=1848398304, u64=9708474487264}}) = 0
write(14, "[\244\1\0\0\1\0\0\0\0\0\0\4raft\10hanahaus\3com\0\0"..., 35) = 35
timerfd_settime(13, TFD_TIMER_ABSTIME, {it_interval={tv_sec=0, tv_nsec=0}, it_value={tv_sec=3408, tv_nsec=346325000}}, NULL) = 0
epoll_pwait(4, strace: Process 4047 detached
 <detached ...>
```

I'm on a public wifi at a coffee shop/shared workspace called Hanahaus, hence the "hanahaus.com" domain.

The relevant strace from the stuck firefox process is:

```
[pid  4255] connect(7, {sa_family=AF_UNIX, sun_path="/var/run/dbus/system_bus_socket"}, 33 <unfinished ...>
[pid  4255] <... connect resumed> )     = 0
[pid  4255] getsockopt(7, SOL_SOCKET, SO_PEERCRED,  <unfinished ...>
[pid  4255] <... getsockopt resumed> {pid=1, uid=0, gid=0}, [12]) = 0
[pid  4255] fstat(7,  <unfinished ...>
[pid  4255] <... fstat resumed> {st_mode=S_IFSOCK|0777, st_size=0, ...}) = 0
[pid  4255] getsockopt(7, SOL_SOCKET, SO_ACCEPTCONN, [0], [4]) = 0
[pid  4255] getsockname(7, {sa_family=AF_UNIX}, [128->2]) = 0
[pid  4255] geteuid()                   = 1000
[pid  4255] sendmsg(7, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\0AUTH EXTERNAL ", iov_len=15}, {iov_base="31303030", iov_len=8}, {iov_base="\r\nNEGOTIATE_UNIX_FD\r\nBEGIN\r\n", iov_len=28}], msg_iovlen=3, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 51
[pid  4255] gettid()                    = 4255
[pid  4255] getrandom("\xa7\x43\x48\x66\xb2\xde\x82\x87\x54\xb8\xb5\x60\x82\x0f\x46\xb2", 16, GRND_NONBLOCK) = 16
[pid  4255] recvmsg(7, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="OK 9feee33f4c509b9b008a701d59ecf"..., iov_len=256}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 52
[pid  4255] sendmsg(7, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\1\0\1\0\0\0\0\1\0\0\0m\0\0\0\1\1o\0\25\0\0\0/org/fre"..., iov_len=128}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 128
[pid  4255] recvmsg(7, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\2\1\1\v\0\0\0\1\0\0\0=\0\0\0\6\1s\0\6\0\0\0", iov_len=24}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 24
[pid  4255] recvmsg(7, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base=":1.455\0\0\5\1u\0\1\0\0\0\10\1g\0\1s\0\0\7\1s\0\24\0\0\0"..., iov_len=67}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 67
[pid  4255] sendmsg(7, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\1\2\1 \0\0\0\2\0\0\0\242\0\0\0\1\1o\0\31\0\0\0/org/fre"..., iov_len=184}, {iov_base="\0\0\0\0\4\0\0\0raft\0\0\0\0\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=32}], msg_iovlen=2, msg_controllen=0, msg_flags=0}, MSG_DONTWAIT|MSG_NOSIGNAL) = 216
[pid  4255] recvmsg(7, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\4\1\1\v\0\0\0\2\0\0\0\215\0\0\0\1\1o\0\25\0\0\0", iov_len=24}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 24
[pid  4255] recvmsg(7,  <unfinished ...>
[pid  4255] <... recvmsg resumed> {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="/org/freedesktop/DBus\0\0\0\2\1s\0\24\0\0\0"..., iov_len=147}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = 147
[pid  4255] recvmsg(7,  <unfinished ...>
[pid  4255] <... recvmsg resumed> {msg_namelen=0}, MSG_DONTWAIT|MSG_NOSIGNAL|MSG_CMSG_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable)
[pid  4255] ppoll([{fd=7, events=POLLIN}], 1, {tv_sec=44, tv_nsec=999754000}, NULL, 8 <unfinished ...>
```

My nsswitch.conf was (as recommended by the systemd-resolved manual (mostly)):

```
# Begin /etc/nsswitch.conf

passwd: compat mymachines systemd
group: compat mymachines systemd
shadow: compat

publickey: files

hosts: files mymachines resolve [!UNAVAIL=return] myhostname
networks: files

protocols: files
services: files
ethers: files
rpc: files

netgroup: files

# End /etc/nsswitch.conf
```

Moving `myhostname` before `resolve` allowed Firefox to start.

My resolved.conf is:

```
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.
#
# Entries in this file show the compile time defaults.
# You can change settings by editing this file.
# Defaults can be restored by simply deleting this file.
#
# See resolved.conf(5) for details

[Resolve]
#DNS=8.8.8.8 8.8.4.4 2001:4860:4860::8888 2001:4860:4860::8844
FallbackDNS=8.8.8.8 8.8.4.4 2001:4860:4860::8888 2001:4860:4860::8844
Domains=
LLMNR=no
MulticastDNS=no
#DNSSEC=yes
DNSSEC=no
Cache=yes
#DNSStubListener=udp
```

My /etc/hostname is set correctly (to `raft`).

I am getting a fair number of degraded feature set messages but this shouldn't be preventing resolved from resolving my hostname.

```
Oct 22 13:20:46 raft systemd-resolved[4047]: Using degraded feature set (TCP) for DNS server 76.76.76.76.
Oct 22 13:20:54 raft systemd-resolved[4047]: Using degraded feature set (UDP) for DNS server 76.76.76.76.
```

**Comment by poettering** [comment] 2017-10-23 16:59
hmm, something appears to be bad for the DNS server when you resolve the "raft.hanahaus.com" name. Any chance you can generate a pcap file of the DNS traffic that happens when you do this?

Also, could you run systemd-resolved with debug logging on, then reproduce this? i.e. run "systemctl edit systemd-resolved", and type into the vi that is opened:

```
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

then restart resolved with `systemctl restart systemd-resolved`

Then, try to resolve "raft" with `systemd-resolve` and provide the log output systemd-resolved generated for this. It'd be best if nothing else happens on the system in this case, in order to keep the log output minimal, and only carry the information we need here.

**Comment by Stebalien** [comment] 2017-10-23 17:16
> hmm, something appears to be bad for the DNS server when you resolve the "raft.hanahaus.com" name. Any chance you can generate a pcap file of the DNS traffic that happens when you do this?

> Also, could you run systemd-resolved with debug logging on, then reproduce this? i.e. run "systemctl edit systemd-resolved", and type into the vi that is opened:

I will the next time I visit that coffee shop.

However, unless I'm mistaken, systemd-resolved should never be resolving my local hostname over the network. Firefox is asking systemd-resolved to resolve "raft", not "raft.search.domain". systemd-resolved should just notice that "raft" is the local hostname and stop there without ever hitting the network.

**Comment by poettering** [comment] 2017-10-23 17:29
> However, unless I'm mistaken, systemd-resolved should never be resolving my local hostname over the network. Firefox is asking systemd-resolved to resolve "raft", not "raft.search.domain". systemd-resolved should just notice that "raft" is the local hostname and stop there without ever hitting the network.

well, we do synthesize RRs for the local hostname, but only as fallback if DNS can't do it. That's because of compat with server systems which use DNS to pick the "main" IP address of the system, and we can't really break that...

**Comment by poettering** [comment] 2018-05-24 11:44
Ok, let's close this one for now, due to lack of response.

**Closed as completed by poettering** 2018-05-24 11:44 UTC
Labels: resolve, needs-reporter-feedback ❓

**Comment by mattock** [comment] 2022-02-01 12:58
I believe I've hit this same issue with Mozilla Firefox and Thunderbird on Fedora 35. Launching Thunderbird takes about four minutes because it is waiting for systemd-resolve to resolve the local hostname ("carbon") from DNS. The same seems to happen with Firefox : clicking on links that go to the default browser (=Firefox) take ages to actually load.

I can work around this problem by adding an entry for my hostname ("carbon") to /etc/hosts:

```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 carbon
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

Here's a strace of Thunderbird:

```
strace: Process 83757 attached
ppoll([{fd=11, events=POLLIN}], 1, {tv_sec=103, tv_nsec=301473930}, NULL, 8) = 1 ([{fd=11, revents=POLLIN}], left {tv_sec=0, tv_nsec=0})
recvfrom(11, "{\"error\":\"io.systemd.Resolve.Que"..., 131072, MSG_DONTWAIT, NULL, NULL) = 61
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
close(11)                               = 0
getpid()                                = 83757
symlink("127.0.0.1:+83757", "/tmp/thunderbird/lock") = 0
```

Please let me know what additional details you would need to resolve this

**Comment by mattock** [comment] 2022-02-01 14:08
I should add that restarting systemd-resolved while Firefox or Thunderbird is stalling also "fixes" the problem.

**Comment by phiresky** [comment] 2023-12-11 12:42
I have the same problem. Linux 6.6.5-arch1-1. systemd 255-1.
Firefox hangs on start (nothing visible showing). strace looks the same as mattock. Restarting systemd-resolved works around it.

Adding `127.0.0.1 <hostname>` to /etc/hosts fixes it. My /etc/hosts file was empty before without any other problems.
