### ISSUE TITLE
Link to source unit removed when disabling service

### ISSUE THREAD

**Issue by wsw70** [systemd/systemd#3490] opened 2016-06-10 08:31 UTC
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

229
### Used distribution

Ubuntu 16.04, Raspbian
### In case of bug report: Expected behaviour you didn't see

`systemctl disable something.service` leaves the file or link `/etc/systemd/system/something.service` untouched and removes links from the unit configuration directory.
### In case of bug report: Unexpected behaviour you saw

`systemctl disable something.service` removes `/etc/systemd/system/something.service` when it is  a link to a file elsewhere.
### In case of bug report: Steps to reproduce the problem
- create a unit file `/opt/something.service` (the location does not matter)
- `ln -s /opt/something.service /etc/systemd/system`
- `systemctl enable something.service`
- `systemctl disable something.service`

`/etc/systemd/system/something.service` has been deleted.

The [documentation ](https://www.freedesktop.org/software/systemd/man/systemctl.html#) states that (please note the "**to**")

> disable NAME...
> Disables one or more units. This removes all symlinks **to the specified unit files** from the unit configuration directory, and hence undoes the changes made by enable. Note however that this removes **all symlinks to the unit files** (i.e. including manual additions), (...)

which means that only links pointing **TO** the unit will be removed. The unit file (whether this is an actual file or a link) should not be touched (there is no reason it is modified in any way). A different behaviour for a plain file vs. a link should not be there when disabling the service (which is the action to "isolate" the unit file form configuration directories.

**Comment by poettering** [comment] 2016-06-10 11:32
Nope, this is a misunderstanding: as the man page says, this really removes all matching symlinks ot the unit _files_ from /etc. Symlinks in /etc/systemd/system/ is really the stuff that "systemctl enable", "systemctl disable" and "systemctl link" manage. What they create and what they remove. It will not operate on non-symlinks, and it won't operate outside of /etc/systemd/system, but it _really_ removes all symlinks to the actual unit files, regardless whether they are just .wants.d/ links, or aliases.

Or in other words: "systemctl disable" is the antidote to both "systemctl enable" and "systemctl link" (and in fact any manually created symlinks matching the unit name).

So, really, this is by design and on purpose. Closing.

**Closed as completed by poettering** 2016-06-10 11:32 UTC
Labels: systemctl

**Comment by poettering** [comment] 2016-06-10 11:33
(and I think the man page is really clear about that, given that it says: "Note however that this removes all symlinks to the unit files (i.e. including manual additions)". And the link you created is after all just that: a symlink the the unit file.

**Comment by wsw70** [comment] 2016-06-10 11:42
OK thank you for the information. It therefore means that it is better to use true files in `/etc/systemd/system` as they will not be touched by `systemctl disable`. 

A sa side note I find it quite strange that a file is not touched, while a link is removed (the file should be removed as well - to be consistent in the functionality: disable = remove the unit data from `/etc/systemd/system`). 
It also breaks the ability to keep some `.service` files in a repo elsewhere and just have a lin in `/etc/systemd/system` pointing to it.

But anyway - if this is by design then be it.

**Comment by poettering** [comment] 2016-06-10 13:13
well, the way we see this is that "systemctl enable", "systemctl disable" and related calls manage symlinks in /etc. They create them and remove them. And that's really it. If it's not a symlink, or if its not in /etc, then "systemctl enable"/"systemctl disable"/… won't touch it.

And note that "systemctl link" exists explicitly to link foreign files into /etc. And the opposite call, to remove those links again from there is "systemctl disable".

**Comment by Kyslik** [comment] 2017-04-24 15:13
Note that disabling service also removes ***.wants** directory if its empty.
