### ISSUE TITLE
sysctl fails to setup IP forwarding

### ISSUE THREAD

**Issue by kaihendry** [systemd/systemd#468] opened 2015-07-02 04:00 UTC
Using 221-2 on Archlinux.

http://s.natalian.org/2015-07-02/ip_forward_system_conf_bug.mp4

Only once I had `/etc/sysctl.d/40-ip-forward.conf` set!

Ref: https://bbs.archlinux.org/viewtopic.php?pid=1541424#p1541424

**Comment by jernst** [comment] 2015-07-02 04:43
To confirm and to elaborate:
1. `/etc/sysctl.d/ip_forward.conf` contains `net.ipv4.ip_forward = 1`
2. Reboot
3. `cat /proc/sys/net/ipv4/ip_forward` shows 1
4. `systemd-nspawn -n ...` container has local networking, but fails to reach upstream
5. toggle the bit: `echo 0 > /proc/sys/net/ipv4/ip_forward`, followed by `echo 1 > /proc/sys/net/ipv4/ip_forward`
6. container now can reach upstream

**Comment by poettering** [comment] 2015-07-06 18:57
Not sure what this bug is precisely about?

What does the sysctl ip forwarding setting for the individual interface say?

Note that current versions of systemd-networkd will turn off forwarding for each interface it manages, unless it is explicitly enabled in the .network file via either IPForward=yes or IPMasquerade=yes. 80-container-ve.network has that set by default, and hence should get forwarding turned on automatically.

**Comment by kaihendry** [comment] 2015-07-16 13:17
My [/etc/systemd/network/50-containers.network](http://ix.io/jLp) has both IPForward=yes or IPMasquerade=yes and it doesn't work.

Oddly there is no difference in the sysctl reading for my **ve-arch** interface before or after I run `echo 1 > /proc/sys/net/ipv4/ip_forward`.

http://s.natalian.org/2015-07-16/ve-arch.txt

**Please NOTE** the very odd behaviour that I've been able to reproduce that https://github.com/systemd/systemd/issues/468#issuecomment-117904714 states. Even if it says it's forwarding, it's NOT until you toggle it off and on again!

**Comment by jernst** [comment] 2015-07-18 05:32
Wild guess: systemd reads the value before /etc/sysctl.d/\* had a chance to set it?

**Comment by poettering** [comment] 2015-07-23 17:15
Sorry, I still don't get what the bug is about precisely? Do you have the forwarding setting defined in a sysctl file? if so, networkd will override it, though race against it.

@teg, maybe we should order networkd.service after sysctl.service? that way the confusion goes away, and all sysctl changes made on the "default" sysctl for all ifaces will be properly inherited to the network interfaces managed by networkd.

**Comment by teg** [comment] 2015-07-23 18:51
Yeah, that makes sense.

**Comment by poettering** [comment] 2015-07-23 20:47
OK, under the assumption that #691 fixed the issue, I'll close this now.

If this does not fix the issue, please let me know what precisely the issue is supposed to be and open it again.

**Closed as completed by poettering** 2015-07-23 20:47 UTC
Labels: network

**Comment by jernst** [comment] 2015-08-17 20:49
I'm afraid the behavior is unchanged with systemd 224 on the host (221 in the container, but that should not matter I think.) I can confirm that systemd-sysctl runs before systemd-networkd and before the container is started.

See steps to follow above at https://github.com/systemd/systemd/issues/468#issuecomment-117904714
