### ISSUE TITLE
No HDD spindown/parking (which decreases the disc's lifespan)

### ISSUE THREAD

**Issue by heldernovais** [systemd/systemd#13678] opened 2019-09-28 23:48 UTC
> systemd --version
systemd 240
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Lubuntu (Ubuntu flavour)

**Expected behaviour you didn't see**
 > The HDD (both an external and internal sda) should spin down and be parked before the system completely powers off.

**Unexpected behaviour you saw**
 > Systemd shuts the system down without waiting. The logs seem to prove that there are no fatal flaws. The system visually shuts down too fast for what's common.
> Both discs get their power supply cut off, which results in a significantly high-pitched squeaking sound. Possibly related: a new internal hdd with close to 2 months of usage is already showing signs of wear and clicking sounds after these incidents.

**Steps to reproduce the problem**
On Lubuntu, the default shutdown button is pressed, equivalent to pressing the power off button.

**Workarounds*
hdparm can be used to force the disc to spin down and park. Ideally, systemd will check if the disc is still spinning with "hdparm -C", and only shutdown when true. I began using a custom script to force this before shutting down by command.

**Comment by heldernovais** [comment] 2019-09-30 22:40
Anyone? This keeps on happening.

**Comment by heldernovais** [comment] 2019-10-01 18:57
Power Off Retract Count keeps increasing.

**Comment by floppym** [comment] 2019-10-01 21:17
A daily reminder is unnecessary.

I don't think this is a new thing: systemd has been shutting down this way for several years, probably since the very first releases. If you have some evidence of a regression in recent versions, that might warrant a higher priority.

**Comment by poettering** [comment] 2019-10-02 12:56
systemd ultimately just calls the reboot() system call as last step, which then shuts down all drivers and eventually powers off the machine. It's thus really a job for the kernel to power down devices and busses if that's desirable, userspace can't really know what's right to do.

On my machine (at least when in debug mode) I can see that immediately before poweroff such requests are propagated via the ATA connectors, so at least some subsystems get this right.

Hence, can you please report this to the kernel folks instead, they need to fix this in the kernel, if there's really a problem here.

Closing hence. Hope that makes sense.

**Closed as completed by poettering** 2019-10-02 12:56 UTC
Labels: not-our-bug

**Comment by heldernovais** [comment] 2019-10-06 23:00
Alright, thanks for the help. I'm going to report this to the kernel.
