### ISSUE TITLE
pam_systemd doesn't set DBUS_SESSION_BUS_ADDRESS for user manager

### ISSUE THREAD

**Issue by heftig** [systemd/systemd#1600] opened 2015-10-18 05:52 UTC
`pam_systemd` is in both the login PAM stacks and the `systemd-user` stack.

In the kdbus case, pam_systemd sets `DBUS_SESSION_BUS_ADDRESS` correctly.

In the userspace bus case, pam_systemd sets `DBUS_SESSION_BUS_ADDRESS` correctly only for the user session, not the user manager. Hence, services launched by the manager are now missing this critical environment variable.

Downstream bugs:
https://bugs.archlinux.org/task/46721
https://bugzilla.gnome.org/show_bug.cgi?id=756420

Pushing it to the manager after startup is too late, so what to do?

**Comment by heftig** [comment] 2015-10-18 06:00
Obviously, the `access` check is the culprit, which won't work for the user manager.

**Comment by heftig** [comment] 2015-10-18 06:47
I think I have an acceptable workaround... adjusted the `dbus` package with:

##### `dbus.socket`

``` ini
[Unit]
Description=D-Bus User Message Bus Socket
Requires=dbus-setenv.service
After=dbus-setenv.service

[Socket]
ListenStream=%t/bus

[Install]
WantedBy=sockets.target
Also=dbus.service
```

I thought about using a dropin for the added `Requires=` and `After=` here, but that would have affected `systemd-bus-proxyd.socket` as well, I believe. Do dropins work through aliases?

##### `dbus-setenv.service`

``` ini
[Unit]
Description=Set Environment DBUS_SESSION_BUS_ADDRESS
DefaultDependencies=no
Requisite=dbus.socket

[Service]
Type=oneshot
Environment=DBUS_SESSION_BUS_ADDRESS=unix:path=%t/bus
ExecStart=/usr/bin/systemctl --user import-environment DBUS_SESSION_BUS_ADDRESS
```

**Comment by poettering** [comment] 2015-10-19 20:19
Is this really necessary? I mean, why doesn't the default bus path (based on XDG_RUNTIME_DIR) in newer libdbus versions and sd-bus suffice?

**Comment by poettering** [comment] 2015-10-19 20:19
@dvdhrm @kaysievers ?

**Comment by heftig** [comment] 2015-10-19 20:25
Are you considering removing the variable completely? There are many implementations of DBus, most of which need `DBUS_SESSION_BUS_ADDRESS` to be able to connect to a session bus. Also, most distributions are not using the default bus path. These things will take years to change, and legacy code will always be there.

**Comment by heftig** [comment] 2015-10-19 20:29
Then again, I suppose one could try to put `Requires=dbus.socket` and `Environment=DBUS_SESSION_BUS_ADDRESS=unix:path=%t/bus` on the units that need it. Should then be done by `systemd-dbus1-generator`, too.

On second thought, that would override the kdbus `DBUS_SESSION_BUS_ADDRESS`. Ugh.

**Comment by heftig** [comment] 2015-10-19 20:40
Alternatively, you could mandate that using user services means having a bus at the default bus path, and omit the access check in `pam_systemd` for the manager, maybe like this:

``` diff
From 90d7245f792dfb452f753e4a7f162b95d3c73e6c Mon Sep 17 00:00:00 2001
From: "Jan Alexander Steffens (heftig)" <jan.steffens@gmail.com>
Date: Sun, 18 Oct 2015 08:17:49 +0200
Subject: [PATCH] pam_systemd: Avoid D-Bus socket access check for manager

Assume that if we launch services from the manager, they always
use a managed dbus-daemon. Not all that great either, but hopefully
more compatible.
---
 src/login/pam_systemd.c | 20 +++++++++++---------
 1 file changed, 11 insertions(+), 9 deletions(-)

diff --git a/src/login/pam_systemd.c b/src/login/pam_systemd.c
index f66f1ce..966e6c1 100644
--- a/src/login/pam_systemd.c
+++ b/src/login/pam_systemd.c
@@ -176,7 +176,8 @@ static int get_seat_from_display(const char *display, const char **seat, uint32_
 static int export_legacy_dbus_address(
                 pam_handle_t *handle,
                 uid_t uid,
-                const char *runtime) {
+                const char *runtime,
+                bool for_manager) {

         _cleanup_free_ char *s = NULL;
         int r = PAM_BUF_ERR;
@@ -189,14 +190,15 @@ static int export_legacy_dbus_address(
                  * daemons that spawn dbus-daemon, instead of forcing
                  * DBUS_SESSION_BUS_ADDRESS= here. */

-                s = strjoin(runtime, "/bus", NULL);
-                if (!s)
-                        goto error;
+                if (!for_manager) {
+                        _cleanup_free_ char *p = strjoin(runtime, "/bus", NULL);
+                        if (!p)
+                                goto error;

-                if (access(s, F_OK) < 0)
-                        return PAM_SUCCESS;
+                        if (access(p, F_OK) < 0)
+                                return PAM_SUCCESS;
+                }

-                s = mfree(s);
                 if (asprintf(&s, UNIX_USER_BUS_ADDRESS_FMT, runtime) < 0)
                         goto error;
         }
@@ -282,7 +284,7 @@ _public_ PAM_EXTERN int pam_sm_open_session(
                                 return r;
                         }

-                        r = export_legacy_dbus_address(handle, pw->pw_uid, rt);
+                        r = export_legacy_dbus_address(handle, pw->pw_uid, rt, true);
                         if (r != PAM_SUCCESS)
                                 return r;
                 }
@@ -461,7 +463,7 @@ _public_ PAM_EXTERN int pam_sm_open_session(
                         return r;
                 }

-                r = export_legacy_dbus_address(handle, pw->pw_uid, runtime_path);
+                r = export_legacy_dbus_address(handle, pw->pw_uid, runtime_path, false);
                 if (r != PAM_SUCCESS)
                         return r;
         }
-- 
2.6.1
```

Or you could get rid of the `access` check completely, causing an unconditional `DBUS_SESSION_BUS_ADDRESS` even in the user session:

``` diff
From d2e0c8ff25c74a5ea59f09c4cbaa53126d36ae1b Mon Sep 17 00:00:00 2001
From: "Jan Alexander Steffens (heftig)" <jan.steffens@gmail.com>
Date: Sun, 18 Oct 2015 08:01:18 +0200
Subject: [PATCH] HACK: Unconditionally set session bus address

Stopgap measure for https://github.com/systemd/systemd/issues/1600
---
 src/login/pam_systemd.c | 12 ------------
 1 file changed, 12 deletions(-)

diff --git a/src/login/pam_systemd.c b/src/login/pam_systemd.c
index f66f1ce..61915c9 100644
--- a/src/login/pam_systemd.c
+++ b/src/login/pam_systemd.c
@@ -185,18 +185,6 @@ static int export_legacy_dbus_address(
                 if (asprintf(&s, KERNEL_USER_BUS_ADDRESS_FMT ";" UNIX_USER_BUS_ADDRESS_FMT, uid, runtime) < 0)
                         goto error;
         } else {
-                /* FIXME: We *really* should move the access() check into the
-                 * daemons that spawn dbus-daemon, instead of forcing
-                 * DBUS_SESSION_BUS_ADDRESS= here. */
-
-                s = strjoin(runtime, "/bus", NULL);
-                if (!s)
-                        goto error;
-
-                if (access(s, F_OK) < 0)
-                        return PAM_SUCCESS;
-
-                s = mfree(s);
                 if (asprintf(&s, UNIX_USER_BUS_ADDRESS_FMT, runtime) < 0)
                         goto error;
         }
-- 
2.6.1
```

This seems like a bad idea, though, since it breaks compatibility with legacy D-Bus setups.

**Comment by dvdhrm** [comment] 2015-10-20 09:05
Wait, nobody should rely on `DBUS_USER_BUS_ADDRESS` except legacy applications. But anything using libdbus, sd-bus or gdbus should use the user-bus as fallback if nothing else is specified. The only reason we still set the environment variable is to help applications like `gdm` to not spawn their own session bus.

Why exactly is gvfs unable to cope with this?

**Comment by heftig** [comment] 2015-10-20 09:40
Looking in gvfs code, `g_io_module_load` in `client/gdaemonvfs.c` and `g_proxy_volume_monitor_setup_session_bus_connection` in `monitor/proxy/gproxyvolumemonitor.c` both contain this snippet:

``` c
  /* This is so that system daemons can use gio
   * without spawning private dbus instances.
   * See bug 526454.
   */
  if (g_getenv ("DBUS_SESSION_BUS_ADDRESS") == NULL) 
    return;
```

https://bugzilla.gnome.org/show_bug.cgi?id=526454

Seems that GVFS basically completely disables itself (the GIO module isn't loaded) if the variable isn't present.

**Comment by dvdhrm** [comment] 2015-10-21 10:07
Sorry for the delay. Ok, so the issue is, we cannot 'predict' whether `systemd --user` spawns a dbus-daemon or not. Setting `DBUS_SESSION_BUS_ADDRESS` when spawning `systemd --user` is thus not a viable solution. Furthermore, the env-variable should not be set for units that start before the bus does.

The easiest solution would be to add to dbus.socket:

```
ExecStartPost=/usr/bin/systemctl --user set-environment DBUS_SESSION_BUS_ADDRESS=unix:path=%t/bus
```

**Comment by poettering** [comment] 2015-10-21 10:14
@dvdhrm hmm, would it be that bad to set the address unconditionally? i mean, we could just say that dbus-daemon really has to place its socket where we expect it to place it, and everything else is unsupported. That way the only thing that might happen is that clients connect to the socket declared in DBUS_SESSION_BUS_ADDRESS and then get connection refused, but that's not really an issue, is it? Or am I missing something?

**Comment by heftig** [comment] 2015-10-21 10:16
Ah, I didn't notice socket units supported Post/Pre exec.

**Comment by dvdhrm** [comment] 2015-10-21 10:21
No, we cannot set `DBUS_SESSION_BUS_ADDRESS` for things like `gdm` and friends. They will silently fail if they have not been converted to the user-bus.

Sure, you might argue that anything that uses bus-units should never be using the session-bus, but that might not be true right now. Furthermore, by moving it into `dbus.socket`, we put the legacy into dbus instead of systemd. They can drop it once no-one depends on it anymore.

**Comment by heftig** [comment] 2015-10-22 18:51
Created a bug for D-Bus at https://bugs.freedesktop.org/show_bug.cgi?id=92612 and attached a patch with @dvdhrm's suggested fix.

**Comment by dvdhrm** [comment] 2015-10-23 09:10
Thanks a lot, much appreciated. I'm on CC for that bug and will chime in if necessary.

I will close this now. Feel free to re-open if necessary.

**Closed as completed by dvdhrm** 2015-10-23 09:10 UTC
Labels: sd-bus

**Comment by CanadianJeff** [comment] 2016-01-04 23:58
re open this please as this issue was posted in a gvfs bug report

https://bugzilla.gnome.org/show_bug.cgi?id=753561#c21

**Comment by dvdhrm** [comment] 2016-01-08 15:24
@CanadianJeff why? What's wrong with the fix provided in this thread? Please see here:
https://github.com/smcv/dbus-mirror/commit/98e4499240050ea3b41951fda0c06b863b89b152

**Comment by CanadianJeff** [comment] 2016-01-08 22:10
all fixed there was an update to gvfs

```
root@xubuntu:/tmp# dpkg -l gvfs*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                        Version            Architecture       Description
+++-===========================-==================-==================-===========================================================
ii  gvfs:amd64                  1.27.3-1ubuntu1    amd64              userspace virtual filesystem - GIO module
ii  gvfs:i386                   1.27.3-1ubuntu1    i386               userspace virtual filesystem - GIO module
ii  gvfs-backends               1.27.3-1ubuntu1    amd64              userspace virtual filesystem - backends
un  gvfs-backends-goa           <none>             <none>             (no description available)
ii  gvfs-bin                    1.27.3-1ubuntu1    amd64              userspace virtual filesystem - binaries
ii  gvfs-common                 1.27.3-1ubuntu1    all                userspace virtual filesystem - common data files
ii  gvfs-daemons                1.27.3-1ubuntu1    amd64              userspace virtual filesystem - servers
ii  gvfs-fuse                   1.27.3-1ubuntu1    amd64              userspace virtual filesystem - fuse server
ii  gvfs-libs:amd64             1.27.3-1ubuntu1    amd64              userspace virtual filesystem - private libraries
ii  gvfs-libs:i386              1.27.3-1ubuntu1    i386               userspace virtual filesystem - private libraries
```
