### ISSUE TITLE
networkd: tunnel dev never reevaluates Local=slaac

### ISSUE THREAD

**Issue by sevenautumns** [systemd/systemd#30946] opened 2024-01-15 20:32 UTC
### systemd version the issue has been seen with

254.6

### Used distribution

NixOS

### Linux kernel version used

6.1.71

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

When I get a new ipv6 address, the tunnel devices with `Local=slaac` utilizes the new ipv6 address

### Unexpected behaviour you saw

The tunnel device keeps its old slaac configured ipv6 address

The following commands result in a new evaluation of Local=slaac
```
ip -6 tunnel del tun0
systemctl restart systemd-networkd
```

### Steps to reproduce the problem

- create a tunnel device with Local=slaac
- change ipv6 address of tunneled network
- see that tunnel still uses old ipv6

**Comment by yuwata** [comment] 2024-02-02 16:25
duplicate of #24854.

**Closed as completed by yuwata** 2024-02-02 16:25 UTC
Labels: bug 🐛, network, duplicate
