### ISSUE TITLE
systemd-networkd: do not reconfigure when roaming between APs on same SSID

### ISSUE THREAD

**Issue by zeldovich** [systemd/systemd#20887] opened 2021-09-29 23:43 UTC
**Is your feature request related to a problem? Please describe.**
When a wireless interface is associated to a wireless network (SSID) with multiple access points, the client might roam (reassociate) between access points.  When reassociating, carrier is lost and then re-gained on the interface.  This causes systemd-networkd to reconfigure the interface addresses -- first by dropping addresses and routes when carrier is lost, and then re-acquiring the addresses and routes via DHCP/SLAAC.

This reconfiguration of the interface significantly increases the effective latency of roaming from one access point to another, and causes some applications to get errors (e.g., when routes disappear).

The expected behavior is that the address information is retained when re-associating to another access point in the same SSID, but gets reconfigured if the interface associates to a different SSID.  This behavior is implemented by other tools on Linux (like NetworkManager).

**Describe the solution you'd like**
It would be great if systemd-networkd did not trigger reconfiguration of an interface when the wireless interface is re-associated to another access point on the same SSID -- but did reconfigure when the interface connects to a different SSID.

It seems that carrier information alone is not sufficient for systemd-networkd to determine the right course of action; perhaps explicit support for knowing about the associated SSID of a wireless interface is necessary inside systemd-networkd to implement correct behavior.  Alternatively, maybe wpa_supplicant provides some dbus API to determine what's going on (is the interface re-associating)?

**Describe alternatives you've considered**
One workaround I'm currently using is to set `IgnoreCarrierLoss=true` for the wireless interface.  This causes systemd-networkd to keep the address configuration when roaming between APs on the same SSID.  But it causes undesirable behavior when switching SSIDs (e.g., moving a laptop from my home network to my office network): systemd-networkd still keeps the home IP address even when wpa_supplicant has connected to the office SSID, and requires an explicit `systemd reconfigure wlp...` to get the right IP address.

An alternative workaround I considered is to convince wpa_supplicant to create a separate wireless interface for each SSID that it connects to -- e.g., create a `wifi-home` interface when connected to my home SSID, and a `wifi-office` interface when connected to my office SSID, both backed by the same wifi phy interface.  This seems like it would work well with systemd-networkd's view of how interfaces work (perhaps along with the `IgnoreCarrierLoss=true` workaround on those interfaces).  But this seems like a pretty involved change to how wpa_supplicant works.

**The systemd version you checked that didn't have the feature you are asking for**

The latest version of systemd in Arch Linux (249.4) has this problem.

**Comment by yuwata** [comment] 2021-09-29 23:48
Few hours ago, PR #20802 was merged, which changes the logic of SSID handling. Could you test the current git HEAD, and if it still has this issue, then could you provide the debugging log of networkd?

**Comment by zeldovich** [comment] 2021-09-29 23:50
Oh, quite the coincidence.  Will build HEAD and report back.  Thanks.

**Comment by yuwata** [comment] 2021-09-29 23:50
Also, please provide the relevant .network files.

**Comment by zeldovich** [comment] 2021-09-30 00:18
It seems like systemd-networkd built from fab79a85af29ba1c1e237ace6c8078357c04b488 still has the problematic behavior described in this issue.

Here's my network file:

    [Match]
    Name=wlp0s20f3

    [Network]
    DHCP=ipv4
    IPv6AcceptRA=true
    # IgnoreCarrierLoss=true

    [DHCPv4]
    RouteMetric=500

    [IPv6AcceptRA]
    RouteMetric=500

As my test case, I ran `SYSTEMD_LOG_LEVEL=debug ./systemd-networkd` and waited for it to obtain addresses for my wireless interface (which was already connected to my home SSID).  Then I ran `wpa_cli reassociate`, which caused `wpa_supplicant` to re-associate to the same access point as it was already connected to, but in the process it did drop carrier on the wireless interface and then re-acquire carrier.

These test steps caused systemd-networkd to drop the v4 and v6 addresses, and re-acquire them when carrier came back, which is undesirable.

Attached are two debug output logs from systemd-networkd.  The first is the output generated from startup until I run `wpa_cli reassociate`, and the second is the output generated after I run `wpa_cli reassociate` until things quiesce again.

[networkd-startup.log](https://github.com/systemd/systemd/files/7255686/networkd-startup.log)
[networkd-reassociate.log](https://github.com/systemd/systemd/files/7255689/networkd-reassociate.log)

**Comment by yuwata** [comment] 2021-09-30 00:20
Thanks. I will take a look.

**Comment by yuwata** [comment] 2021-09-30 05:50
First, I cannot find anything strange at least from the provided logs. So, I dropped the 'bug' tag.

> It would be great if systemd-networkd did not trigger reconfiguration of an interface when the wireless interface is re-associated to another access point on the same SSID -- but did reconfigure when the interface connects to a different SSID.

Yeah, of course that's better if possible.

> It seems that carrier information alone is not sufficient for systemd-networkd to determine the right course of action; perhaps explicit support for knowing about the associated SSID of a wireless interface is necessary inside systemd-networkd to implement correct behavior.

Currently, networkd receives several wifi interface status through nl80211, as you can already see the logs.
But, I am not sure that it is possible to distinguish that the disconnection is caused by re-association or (pure) de-association.

> Alternatively, maybe wpa_supplicant provides some dbus API to determine what's going on (is the interface re-associating)?

If they provided such information, then it maybe an option.

> One workaround I'm currently using is to set IgnoreCarrierLoss=true for the wireless interface. This causes systemd-networkd to keep the address configuration when roaming between APs on the same SSID.

Yeah, the option should not be used such purpose, and the result you find is expected.

**Comment by yuwata** [comment] 2021-09-30 05:55
> This reconfiguration of the interface significantly increases the effective latency of roaming from one access point to another, and causes some applications to get errors (e.g., when routes disappear).

That's my personal opinion, and off-topic here, but in the current era, in general, applications should not expect stable connection any more, and resume operation nicely when connection is recovered.

**Comment by zeldovich** [comment] 2021-09-30 13:14
> > This reconfiguration of the interface significantly increases the effective latency of roaming from one access point to another, and causes some applications to get errors (e.g., when routes disappear).
> 
> That's my personal opinion, and off-topic here, but in the current era, in general, applications should not expect stable connection any more, and resume operation nicely when connection is recovered.

I agree -- this view seems reasonable enough, and not really the core of the feature request.

**Comment by zeldovich** [comment] 2021-09-30 13:18
> First, I cannot find anything strange at least from the provided logs. So, I dropped the 'bug' tag.

Fair enough; I think of this issue as a feature request for an optimization.

The core issue is reducing the network downtime when switching between access points.  The re-configuration by systemd-networkd is by far the largest component of the reassociation time in my experiments.

By comparison, pretty much every other network management system implements this optimization -- NetworkManager on Linux, and the built-in network managers on Android, iOS, MacOS, and Windows.

> > It seems that carrier information alone is not sufficient for systemd-networkd to determine the right course of action; perhaps explicit support for knowing about the associated SSID of a wireless interface is necessary inside systemd-networkd to implement correct behavior.
> 
> Currently, networkd receives several wifi interface status through nl80211, as you can already see the logs. But, I am not sure that it is possible to distinguish that the disconnection is caused by re-association or (pure) de-association.

I'm really not knowledgeable about what would be the proper place to obtain the right status information for making this optimization, sorry.

> > One workaround I'm currently using is to set IgnoreCarrierLoss=true for the wireless interface. This causes systemd-networkd to keep the address configuration when roaming between APs on the same SSID.
> 
> Yeah, the option should not be used such purpose, and the result you find is expected.

Indeed, no complaints about the behavior I see with the workaround, just wanted to mention it as a way of showing the behavior I'm hoping to achieve.

Thank you for looking at this issue!

**Comment by yuwata** [comment] 2021-11-13 02:18
Fix is waiting in #21344. If possible, please test the PR.

**Comment by zeldovich** [comment] 2021-11-13 11:14
Thank you for PR #21344!  That addresses most of this issue.

There's a minor remaining nit: when the wireless interface associates to a new SSID (within the IgnoreCarrierLoss timeout), systemd-networkd does not re-configure the interface.  The systemd-networkd log output is roughly as follows (attached is the full `SYSTEMD_LOG_LEVEL=debug` log, [ssid-change.log](https://github.com/systemd/systemd/files/7531896/ssid-change.log)):

    wlp0s20f3: Connected WiFi access point: open-wifi (f6:9f:c2:61:d2:37)
    wlp0s20f3: Gained carrier
    wlp0s20f3: Lost carrier
    wlp0s20f3: Connected WiFi access point: Chapeau-claque (f0:9f:c2:61:d2:37)
    wlp0s20f3: Gained carrier

I think the ideal behavior would be for systemd-networkd to remember the currently-connected SSID, and if it connects to a new SSID, the interface should be re-configured regardless whether carrier dropped.

Let me know if you'd prefer me to open a separate issue for this remaining nit (and thank you again for already fixing the bulk of the problem!).

**Comment by yuwata** [comment] 2021-11-14 02:01
I cannot reproduce the issue... Did you tested the branch as is? Or, applied the patches to the systemd package you use?

**Comment by yuwata** [comment] 2021-11-14 02:02
Ah, you use the same .network file for different APs. Thanks. Will fix the issue in the PR.

**Closed as completed** 2021-11-16 01:27 UTC
Labels: RFE 🎁, network
