### ISSUE TITLE
Multiple systemctl suspend regressions

### ISSUE THREAD

**Issue by MatthewOwens** [systemd/systemd#17981] opened 2020-12-14 21:56 UTC
**systemd version the issue has been seen with**
 > 247.1-3

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > Linux gensokyo 5.9.14-arch1-1 #1 SMP PREEMPT Sat, 12 Dec 2020 14:37:12 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Computer Suspends

**Unexpected behaviour you saw**
 > When run with just `systemctl suspend`:
 > Computer initially suspends successfully. However after a period of time all fans spin up to 100%, and front power light turns on.    This issue seems to be inconsistent, and does not occur on every suspend.
 > When `systemctl suspend` is called from a keybind (tested with both sxhkd and i3wm):
 > system suspends, resumes and suspends again. If called with a locker program such as i3-lock or slock, the lock screen is seen after the inital suspend but no input is passed to the lock program after the second suspend.

**Steps to reproduce the problem**
 > Run `systemctl suspend` and wait or run `systemctl suspend` from a keybind with i3 or sxhkd. Issue may persist when run with other keybinding methods, however these are the only two I have tested so far.

**Comment by bluca** [comment] 2020-12-14 23:34
> Computer initially suspends successfully. 

A bit suspicious - you mentioned it is a regression, what was the context exactly? A systemd upgrade? Was anything else updated at the same time?

**Comment by MatthewOwens** [comment] 2020-12-15 10:32
Hey @bluca,
As arch linux doesn't support partial upgrades, quite a bit was updated at the same time. I've included the pacman log snippet for the day [here](https://gist.github.com/MatthewOwens/6af5a71882100a6d58c03b332f4a5575).

Prior to this update suspend was working without issue via a keybind and I had never seen the fans spin up and front light come on while the system was suspended.

If you need any further log files or testing on my part, please let me know. Cheers

**Comment by bluca** [comment] 2020-12-15 10:37
Looks like the kernel was upgraded. Can you try and downgrade components and see if it makes a difference?

**Comment by poettering** [comment] 2020-12-15 17:16
So this has nothing to do with systemd, but smells like a firmware prob/kernel prob, i.e. some IRQ is configured by firmware as wakeup trigger, that shouldn't be a wakeup trigger. you might be able to fix that by tweaking your bios setup or via writes to /proc/acpi/wakeup

But systemd as nothing to do with that, we just ask the kernel to suspend, and it handles the rest in conjunction with the firmware. systemd isn't involved until the system is fully resumed again.

Hence, closing. Your might have success talking to kernel power management people, maybe they know what to do about this in a generic fasion so that you don#t have to muck manually with files in /proc...

**Closed as completed by poettering** 2020-12-15 17:16 UTC
Labels: systemctl, needs-reporter-feedback ❓
