### ISSUE TITLE
`machinectl shell` results in no shell and a coredump

### ISSUE THREAD

**Issue by pieterlexis** [systemd/systemd#22377] opened 2022-02-02 15:15 UTC
**systemd version the issue has been seen with**
 > systemd 250 (250.3-2-arch)
 > +PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

**Used distribution**
 > Arch Linux

**Linux kernel version used** (`uname -a`)
 > `Linux lychee.plexis.eu 5.16.4-arch1-1 #1 SMP PREEMPT Sat, 29 Jan 2022 19:08:13 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > A running shell when using `machinectl shell <name>`

**Unexpected behaviour you saw**
```
▲ ~ date
Wed Feb  2 04:05:15 PM CET 2022
▲ ~ sudo machinectl shell ampache
Connected to machine ampache. Press ^] three times within 1s to exit session.

Connection to machine ampache terminated.
▲ ~ sudo coredumpctl| tail -n 1
Wed 2022-02-02 16:05:28 CET    16966 1033568256 1033568256 SIGABRT none     /usr/lib/systemd/systemd  n/a
```

**Steps to reproduce the problem**
* use `mkosi` to generate a Ubuntu Focal image with this config:
```ini
[Distribution]
Distribution=ubuntu
Release=focal

[Output]
Format=tar
```
* Import it `machinectl import-tar image.tzr.xz ampache`
* Start it `machinectl start amapache`
* Try to open a shell `machinectl shell ampache`

**Additional program output to the terminal or log subsystem illustrating the issue**

Journal for the container
```
-- Boot a9420c66846143c7a943092b8f52000a --
Feb 02 16:02:06 music.plexis.eu systemd-journald[15]: Journal started
Feb 02 16:02:06 music.plexis.eu systemd-journald[15]: Runtime Journal (/run/log/journal/cc35a763777e4a3f9f4774734beab0de) is 8.0M, max 78.4M, 70.4M free.
Feb 02 16:02:06 music.plexis.eu systemd-sysctl[17]: Not setting net/ipv4/conf/all/promote_secondaries (explicit setting exists).
Feb 02 16:02:06 music.plexis.eu systemd-sysctl[17]: Not setting net/ipv4/conf/default/promote_secondaries (explicit setting exists).
Feb 02 16:02:06 music.plexis.eu systemd-sysctl[17]: Couldn't write 'fq_codel' to 'net/core/default_qdisc', ignoring: No such file or directory
Feb 02 16:02:06 music.plexis.eu systemd[1]: Starting Flush Journal to Persistent Storage...
Feb 02 16:02:06 music.plexis.eu systemd-journald[15]: Time spent on flushing to /var/log/journal/cc35a763777e4a3f9f4774734beab0de is 1.707ms for 6 entries.
Feb 02 16:02:06 music.plexis.eu systemd-journald[15]: System Journal (/var/log/journal/cc35a763777e4a3f9f4774734beab0de) is 8.0M, max 4.0G, 3.9G free.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Finished Flush Journal to Persistent Storage.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Starting Create Volatile Files and Directories...
Feb 02 16:02:06 music.plexis.eu systemd[1]: Finished Create Volatile Files and Directories.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Starting Network Name Resolution...
Feb 02 16:02:06 music.plexis.eu systemd[1]: Condition check resulted in Network Time Synchronization being skipped.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Reached target System Time Set.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Reached target System Time Synchronized.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Starting Update UTMP about System Boot/Shutdown...
Feb 02 16:02:06 music.plexis.eu systemd[1]: Finished Update UTMP about System Boot/Shutdown.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Reached target System Initialization.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Started Daily apt download activities.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Started Daily apt upgrade and clean activities.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Started Periodic ext4 Online Metadata Check for All Filesystems.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Condition check resulted in Discard unused blocks once a week being skipped.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Started Message of the Day.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Started Daily Cleanup of Temporary Directories.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Reached target Timers.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Listening on D-Bus System Message Bus Socket.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Reached target Sockets.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Reached target Basic System.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Started D-Bus System Message Bus.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Condition check resulted in Remove Stale Online ext4 Metadata Check Snapshots being skipped.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Condition check resulted in getty on tty2-tty6 if dbus and logind are not available being skipped.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Condition check resulted in Set the CPU Frequency Scaling governor being skipped.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Starting Login Service...
Feb 02 16:02:06 music.plexis.eu systemd[1]: Starting Permit User Sessions...
Feb 02 16:02:06 music.plexis.eu systemd[1]: Finished Permit User Sessions.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Started Console Getty.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Condition check resulted in Getty on tty1 being skipped.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Reached target Login Prompts.
Feb 02 16:02:06 music.plexis.eu systemd-logind[26]: New seat seat0.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Started Login Service.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Reached target Multi-User System.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Reached target Graphical Interface.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Starting Update UTMP about System Runlevel Changes...
Feb 02 16:02:06 music.plexis.eu systemd[1]: systemd-update-utmp-runlevel.service: Succeeded.
Feb 02 16:02:06 music.plexis.eu systemd-resolved[23]: Positive Trust Anchors:
Feb 02 16:02:06 music.plexis.eu systemd[1]: Finished Update UTMP about System Runlevel Changes.
Feb 02 16:02:06 music.plexis.eu systemd-resolved[23]: . IN DS 20326 8 2 e06d44b80b8f1d39a95c0b0d7c65d08458e880409bbc683457104237c7f8ec8d
Feb 02 16:02:06 music.plexis.eu systemd-resolved[23]: Negative trust anchors: 10.in-addr.arpa 16.172.in-addr.arpa 17.172.in-addr.arpa 18.172.in-addr.arpa 19.172.in-addr.arpa 20.172.>
Feb 02 16:02:06 music.plexis.eu systemd-resolved[23]: Using system hostname 'music.plexis.eu'.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Started Network Name Resolution.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Reached target Host and Network Name Lookups.
Feb 02 16:02:06 music.plexis.eu systemd[1]: Startup finished in 610ms.
Feb 02 16:05:28 music.plexis.eu systemd[1]: Created slice system-container\x2dshell.slice.
Feb 02 16:05:28 music.plexis.eu systemd[1]: Started Shell for User root.
Feb 02 16:05:28 music.plexis.eu systemd[33]: Assertion 'a' failed at src/basic/path-util.c:486, function path_compare(). Aborting.
Feb 02 16:05:28 music.plexis.eu systemd[1]: container-shell@1.service: Succeeded.
Feb 02 16:06:26 music.plexis.eu systemd[1]: Started Shell for User root.
Feb 02 16:06:26 music.plexis.eu systemd[37]: Assertion 'a' failed at src/basic/path-util.c:486, function path_compare(). Aborting.
Feb 02 16:06:26 music.plexis.eu systemd[1]: container-shell@1.service: Succeeded.
Feb 02 16:13:04 music.plexis.eu systemd[1]: Started Shell for User root.
Feb 02 16:13:04 music.plexis.eu systemd[42]: Assertion 'a' failed at src/basic/path-util.c:486, function path_compare(). Aborting.
Feb 02 16:13:05 music.plexis.eu systemd[1]: container-shell@1.service: Succeeded.
Feb 02 16:13:09 music.plexis.eu systemd[1]: Started Shell for User root.
Feb 02 16:13:09 music.plexis.eu systemd[46]: Assertion 'a' failed at src/basic/path-util.c:486, function path_compare(). Aborting.
Feb 02 16:13:09 music.plexis.eu systemd[1]: container-shell@1.service: Succeeded.
```

debug log of `machinectl shell`:

```
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.Machine: Sending message: {"method":"io.systemd.UserDatabase.GetGroupRecord","parameters":{"gid":100,"service":"io.systemd.Machine"}}
/run/systemd/userdb/io.systemd.Machine: Changing state idle-client → awaiting-reply
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.DynamicUser: Sending message: {"method":"io.systemd.UserDatabase.GetGroupRecord","parameters":{"gid":100,"service":"io.systemd.DynamicUser"}}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state idle-client → awaiting-reply
/run/systemd/userdb/io.systemd.Machine: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.Machine: Changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.Machine: Changing state processing-reply → idle-client
/run/systemd/userdb/io.systemd.DynamicUser: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.DynamicUser: Changing state processing-reply → idle-client
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.Machine: Sending message: {"method":"io.systemd.UserDatabase.GetMemberships","parameters":{"groupName":"users","service":"io.systemd.Machine"},"more":true}
/run/systemd/userdb/io.systemd.Machine: Changing state idle-client → awaiting-reply-more
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.DynamicUser: Sending message: {"method":"io.systemd.UserDatabase.GetMemberships","parameters":{"groupName":"users","service":"io.systemd.DynamicUser"},"more":true}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state idle-client → awaiting-reply-more
/run/systemd/userdb/io.systemd.Machine: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.Machine: Changing state awaiting-reply-more → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.Machine: Changing state processing-reply → idle-client
/run/systemd/userdb/io.systemd.DynamicUser: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state awaiting-reply-more → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.DynamicUser: Changing state processing-reply → idle-client
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.Machine: Sending message: {"method":"io.systemd.UserDatabase.GetGroupRecord","parameters":{"gid":10,"service":"io.systemd.Machine"}}
/run/systemd/userdb/io.systemd.Machine: Changing state idle-client → awaiting-reply
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.DynamicUser: Sending message: {"method":"io.systemd.UserDatabase.GetGroupRecord","parameters":{"gid":10,"service":"io.systemd.DynamicUser"}}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state idle-client → awaiting-reply
/run/systemd/userdb/io.systemd.Machine: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.Machine: Changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.Machine: Changing state processing-reply → idle-client
/run/systemd/userdb/io.systemd.DynamicUser: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.DynamicUser: Changing state processing-reply → idle-client
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.Machine: Sending message: {"method":"io.systemd.UserDatabase.GetMemberships","parameters":{"groupName":"wheel","service":"io.systemd.Machine"},"more":true}
/run/systemd/userdb/io.systemd.Machine: Changing state idle-client → awaiting-reply-more
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.DynamicUser: Sending message: {"method":"io.systemd.UserDatabase.GetMemberships","parameters":{"groupName":"wheel","service":"io.systemd.DynamicUser"},"more":true}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state idle-client → awaiting-reply-more
/run/systemd/userdb/io.systemd.Machine: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.Machine: Changing state awaiting-reply-more → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.Machine: Changing state processing-reply → idle-client
/run/systemd/userdb/io.systemd.DynamicUser: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state awaiting-reply-more → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.DynamicUser: Changing state processing-reply → idle-client
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.Machine: Sending message: {"method":"io.systemd.UserDatabase.GetGroupRecord","parameters":{"gid":994,"service":"io.systemd.Machine"}}
/run/systemd/userdb/io.systemd.Machine: Changing state idle-client → awaiting-reply
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.DynamicUser: Sending message: {"method":"io.systemd.UserDatabase.GetGroupRecord","parameters":{"gid":994,"service":"io.systemd.DynamicUser"}}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state idle-client → awaiting-reply
/run/systemd/userdb/io.systemd.Machine: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.Machine: Changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.Machine: Changing state processing-reply → idle-client
/run/systemd/userdb/io.systemd.DynamicUser: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.DynamicUser: Changing state processing-reply → idle-client
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.Machine: Sending message: {"method":"io.systemd.UserDatabase.GetMemberships","parameters":{"groupName":"docker","service":"io.systemd.Machine"},"more":true}
/run/systemd/userdb/io.systemd.Machine: Changing state idle-client → awaiting-reply-more
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.DynamicUser: Sending message: {"method":"io.systemd.UserDatabase.GetMemberships","parameters":{"groupName":"docker","service":"io.systemd.DynamicUser"},"more":true}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state idle-client → awaiting-reply-more
/run/systemd/userdb/io.systemd.Machine: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.Machine: Changing state awaiting-reply-more → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.Machine: Changing state processing-reply → idle-client
/run/systemd/userdb/io.systemd.DynamicUser: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state awaiting-reply-more → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.DynamicUser: Changing state processing-reply → idle-client
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.Machine: Sending message: {"method":"io.systemd.UserDatabase.GetGroupRecord","parameters":{"gid":100,"service":"io.systemd.Machine"}}
/run/systemd/userdb/io.systemd.Machine: Changing state idle-client → awaiting-reply
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.DynamicUser: Sending message: {"method":"io.systemd.UserDatabase.GetGroupRecord","parameters":{"gid":100,"service":"io.systemd.DynamicUser"}}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state idle-client → awaiting-reply
/run/systemd/userdb/io.systemd.Machine: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.Machine: Changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.Machine: Changing state processing-reply → idle-client
/run/systemd/userdb/io.systemd.DynamicUser: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.DynamicUser: Changing state processing-reply → idle-client
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.Machine: Sending message: {"method":"io.systemd.UserDatabase.GetMemberships","parameters":{"groupName":"users","service":"io.systemd.Machine"},"more":true}
/run/systemd/userdb/io.systemd.Machine: Changing state idle-client → awaiting-reply-more
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.DynamicUser: Sending message: {"method":"io.systemd.UserDatabase.GetMemberships","parameters":{"groupName":"users","service":"io.systemd.DynamicUser"},"more":true}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state idle-client → awaiting-reply-more
/run/systemd/userdb/io.systemd.Machine: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.Machine: Changing state awaiting-reply-more → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.Machine: Changing state processing-reply → idle-client
/run/systemd/userdb/io.systemd.DynamicUser: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state awaiting-reply-more → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.DynamicUser: Changing state processing-reply → idle-client
Connected to machine ampache. Press ^] three times within 1s to exit session.
Connection to machine ampache terminated.
```

**Comment by medhefgo** [comment] 2022-02-02 16:23
Looks like a duplicate of #22234 to me.

**Closed as completed by medhefgo** 2022-02-02 16:23 UTC

**Comment by pieterlexis** [comment] 2022-02-02 18:45
> Looks like a duplicate of #22234 to me.

looks like it, I guess I used the wrong keywords to search. Thanks!
