### ISSUE TITLE
Ability to start services based on specific network devices

### ISSUE THREAD

**Issue by Sworddragon** [systemd/systemd#4172] opened 2016-09-17 02:06 UTC
### Submission type
- [ x ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 231
### Used distribution

> Ubuntu 16.10 dev

It seems it is not possible to start a service after a specific network device enters some state (for example being setup). For example maybe specific targets could be generated for such devices like network-online-eth0.target or a new unit type like systemd.network could be implemented to provide this ability.

**Comment by keszybz** [comment] 2016-09-18 15:09
This has come up before. In general depending on a specific intrrface is the wrong solution because network configuration is ephemeral and can change back and forth based on external events. Instead, programs should either listen on all interfaces or use IP_FREEBIND or listen on net link if they really must react to network changes. You can add After=some.device if you just want to wait for a specific device, but that has limited usefulness. What exactly are you trying to do?

**Comment by Sworddragon** [comment] 2016-09-18 16:49
> In general depending on a specific intrrface is the wrong solution because network configuration is ephemeral and can change back and forth based on external events.

It looks like systemd.network could be the right place then to react on all these events and services can bind it if this requirement is needed :)

> What exactly are you trying to do?

Performance optimization. Actually I'm porting an upstart script where this was possible as for the job it was just required to have a specific device being setup. In the worst case waiting for the complete network to be setup could lead to a significant delay. Units can react on so many events but not on specific network events - it looks that something useful is missing here.

**Comment by keszybz** [comment] 2016-09-19 01:41
> was just required to have a specific device being setup

This sounds like the wrong approach. When listening on wildcard address or when using IP_FREEBIND you don't have to wait for _any_ device, which is always faster than waiting for one device.

**Comment by poettering** [comment] 2016-10-10 09:31
I am not convinced this is really a good idea, a network interface state is a lot more complex than just "on" and "off", it's multi-dimensional in fact (one example: ipv4 might be up, but ipv6 not yet, or the other way round).

**Comment by poettering** [comment] 2020-08-28 18:00
Duplicate of #7743 in a way (closing this one since the #7743 is more elaborate, even if this one is older)

**Closed as completed by poettering** 2020-08-28 18:00 UTC
Labels: RFE 🎁, network
