### ISSUE TITLE
Unexpected `hostnamectl` behavior with a long transient hostname

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#20417] opened 2021-08-10 14:37 UTC
**systemd version the issue has been seen with**
 > v249~rc2-1.fc35

**Used distribution**
 > Fedora Rawhide

**Linux kernel version used** (`uname -a`)

 > `5.13.0-0.rc7.20210625git44db63d1ad8d.55.fc35.x86_64`

`hostnamectl` can't change the transient hostname back once it has been set to a 64-character long one.

Initial state:
```
# hostnamectl
   Static hostname: n/a                                                      
Transient hostname: fedora
         Icon name: computer-vm
           Chassis: vm
        Machine ID: b294558f15804e699e066463ce33ec8b
           Boot ID: 724c2a5f24c04e28a0297e23b85bfa9f
    Virtualization: kvm
  Operating System: Fedora 35 (Rawhide Prerelease)                           
       CPE OS Name: cpe:/o:fedoraproject:fedora:35
            Kernel: Linux 5.13.0-0.rc7.20210625git44db63d1ad8d.55.fc35.x86_64
      Architecture: x86-64
   Hardware Vendor: Red Hat
    Hardware Model: OpenStack Compute
```

Set a 64-character long hostname:
```
# hostnamectl hostname xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.x
Could not set transient hostname: Failed to set hostname: File name too long
# hostnamectl
 Static hostname: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.x
       Icon name: computer-vm
         Chassis: vm
      Machine ID: b294558f15804e699e066463ce33ec8b
         Boot ID: 724c2a5f24c04e28a0297e23b85bfa9f
  Virtualization: kvm
Operating System: Fedora 35 (Rawhide Prerelease)                                  
     CPE OS Name: cpe:/o:fedoraproject:fedora:35
          Kernel: Linux 5.13.0-0.rc7.20210625git44db63d1ad8d.55.fc35.x86_64
    Architecture: x86-64
 Hardware Vendor: Red Hat
  Hardware Model: OpenStack Compute
```

Try to change it back to something shorter:
```
# hostnamectl hostname localhost
Could not set static hostname: Failed to set hostname: File name too long
# hostnamectl
   Static hostname: localhost
Transient hostname: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.x
         Icon name: computer-vm
           Chassis: vm
        Machine ID: b294558f15804e699e066463ce33ec8b
           Boot ID: 724c2a5f24c04e28a0297e23b85bfa9f
    Virtualization: kvm
  Operating System: Fedora 35 (Rawhide Prerelease)                                  
       CPE OS Name: cpe:/o:fedoraproject:fedora:35
            Kernel: Linux 5.13.0-0.rc7.20210625git44db63d1ad8d.55.fc35.x86_64
      Architecture: x86-64
   Hardware Vendor: Red Hat
    Hardware Model: OpenStack Compute
```

**Comment by poettering** [comment] 2021-08-10 17:32
Duplicate of #20309

**Closed as completed** 2021-08-12 07:34 UTC
Labels: bug 🐛, hostname, duplicate
