### ISSUE TITLE
After 2036/02/07 06:28:15(UTC), it fails to sync time.

### ISSUE THREAD

**Issue by KazuoHagihara** [systemd/systemd#26914] opened 2023-03-21 10:58 UTC
### systemd version the issue has been seen with

241

### Used distribution

Debian buster

### Linux kernel version used

4.14-at50-g33dfadcc7cfb

### CPU architectures issue was seen on

arm

### Component

systemd-timesync

### Unexpected behaviour you saw

After 2036/02/07 06:28:15(UTC), ntpmsg.recv_time.sec and ntpmsg.trans_time.sec overflow. Hence this if statement is always false and it fails to sync time.

https://github.com/systemd/systemd/blob/2415a0c7aa1801c6080ba1b8e8d584d5eb0a8c01/src/timesync/timesyncd-manager.c#L469-L473

How about the following amendment?
```c
#define OFFSET_1900_2036 0x100000000

        uint64_t recv_time_sec64;
        uint64_t trans_time_sec64;
        uint32_t recv_time_sec_swap = be32toh(ntpmsg.recv_time.sec);
        uint32_t trans_time_sec_swap = be32toh(ntpmsg.trans_time.sec);

        if ((recv_time_sec_swap & UINT32_C(0x80000000)) == 0) {
                recv_time_sec64 = (uint64_t)recv_time_sec_swap + OFFSET_1900_2036;
        } else {
                recv_time_sec64 = recv_time_sec_swap;
        }

        if ((ntpmsg.trans_time.sec & UINT32_C(0x80000000)) == 0) {
                trans_time_sec64 = (uint64_t)trans_time_sec_swap + OFFSET_1900_2036;
        } else {
                trans_time_sec64 = trans_time_sec_swap;
        }

        if (recv_time_sec64 < TIME_EPOCH + OFFSET_1900_1970 ||
            trans_time_sec64 < TIME_EPOCH + OFFSET_1900_1970) {
                log_debug("Invalid reply, returned times before epoch. Ignoring.");
                return manager_connect(m);
        }
```

**Comment by Jookia** [comment] 2023-03-28 08:03
I just dove in to this myself. The right way to fix this is to add support for NTP eras.

With NTPv4 this logic should basically be:

1. Note what NTP era we are in (multiple of roughly 126 years since 1900),
2. Check if the date is back in time
3. Increase the era
4. Add the era to the NTP timestamp to get the current date

NTPv5 replies with a packet containing the era which means the logic is:

1. Receive the packet
2. Add roughly 126 years times the era number

32-bit time_t doesn't support adjusting by more that 68 years at a time so that would need to be capped.

**Comment by poettering** [comment] 2023-06-08 09:42
Duplicate of #17461

**Comment by poettering** [comment] 2023-06-08 09:42
(but please submit as PR)

**Closed as completed by poettering** 2023-06-08 09:42 UTC
Labels: bug 🐛, timesync
