### ISSUE TITLE
LVM cache volume marked dirty after shutdown

### ISSUE THREAD

**Issue by matte3560** [systemd/systemd#35243] opened 2024-11-19 21:41 UTC
### systemd version the issue has been seen with

256.8-1

### Used distribution

Arch Linux

### Linux kernel version used

6.11.8-arch1-2 and 6.6.62-1-lts

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

LVM cache volume is marked with 100% dirty blocks after shutdown. There is a printout at the very end of the shutdown procedure that says something along the lines of:
`Could not detach DM /dev/dm-0: Device or resource busy`
This line shows up for several device mapper devices, but does not make it into journalctl output from previous boots so this isn't an exact reproduction.

The volume is not mounted on / or any boot-critical mount point.

Tried 6.11.8-arch1-2 and 6.6.62-1-lts kernel, this made no difference. Downgrading to systemd 256.7-1 fixed the issue. When running 256.7-1, the `Could not detach DM /dev/dm-0: Device or resource busy` output does not appear.

The attached journalctl output is from a shutdown, starting with the "Unmounting ..." entry for the affected LVM cache volume (/vol/data). The first part is systemd 256.8-1, the second is 256.7-1.

### Steps to reproduce the problem

Shut down using "poweroff" command with LVM cache volume mounted from fstab.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
256.8-1:
Nov 16 23:31:30 mathias-desktop systemd[1]: Unmounting /vol/data...
Nov 16 23:31:30 mathias-desktop systemd[1]: proc-sys-fs-binfmt_misc.mount: Deactivated successfully.
Nov 16 23:31:30 mathias-desktop systemd[1]: run-credentials-systemd\x2dnetwork\x2dgenerator.service.mount: Deactivated successfully.
Nov 16 23:31:30 mathias-desktop systemd[1]: run-credentials-systemd\x2dresolved.service.mount: Deactivated successfully.
Nov 16 23:31:30 mathias-desktop systemd[1]: run-credentials-systemd\x2dsysctl.service.mount: Deactivated successfully.
Nov 16 23:31:30 mathias-desktop systemd[1]: run-credentials-systemd\x2dtmpfiles\x2dsetup.service.mount: Deactivated successfully.
Nov 16 23:31:30 mathias-desktop systemd[1]: run-credentials-systemd\x2dnetworkd.service.mount: Deactivated successfully.
Nov 16 23:31:30 mathias-desktop systemd[1]: tmp.mount: Deactivated successfully.
Nov 16 23:31:30 mathias-desktop systemd[1]: Unmounted Temporary Directory /tmp.
Nov 16 23:31:30 mathias-desktop systemd[1]: Stopped target Swaps.
Nov 16 23:31:30 mathias-desktop systemd[1]: boot.mount: Deactivated successfully.
Nov 16 23:31:30 mathias-desktop systemd[1]: Unmounted /boot.
Nov 16 23:31:30 mathias-desktop systemd[1]: systemd-fsck@dev-disk-by\x2duuid-1210\x2d9B72.service: Deactivated successfully.
Nov 16 23:31:30 mathias-desktop systemd[1]: Stopped File System Check on /dev/disk/by-uuid/1210-9B72.
Nov 16 23:31:31 mathias-desktop kernel: XFS (dm-3): Unmounting Filesystem 7d873b0a-34f2-4661-9d88-96f95421faea
Nov 16 23:31:31 mathias-desktop systemd[1]: vol-data.mount: Deactivated successfully.
Nov 16 23:31:31 mathias-desktop systemd[1]: Unmounted /vol/data.
Nov 16 23:31:31 mathias-desktop systemd[1]: Reached target Unmount All Filesystems.
Nov 16 23:31:31 mathias-desktop systemd[1]: systemd-fsck@dev-cache_vg-data_lv.service: Deactivated successfully.
Nov 16 23:31:31 mathias-desktop systemd[1]: Stopped File System Check on /dev/cache_vg/data_lv.
Nov 16 23:31:31 mathias-desktop systemd[1]: Removed slice Slice /system/systemd-fsck.
Nov 16 23:31:31 mathias-desktop systemd[1]: Stopped target Preparation for Local File Systems.
Nov 16 23:31:31 mathias-desktop systemd[1]: Stopping Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
Nov 16 23:31:31 mathias-desktop systemd[1]: systemd-tmpfiles-setup-dev.service: Deactivated successfully.
Nov 16 23:31:31 mathias-desktop systemd[1]: Stopped Create Static Device Nodes in /dev.
Nov 16 23:31:31 mathias-desktop systemd[1]: systemd-sysusers.service: Deactivated successfully.
Nov 16 23:31:31 mathias-desktop systemd[1]: Stopped Create System Users.
Nov 16 23:31:31 mathias-desktop systemd[1]: systemd-tmpfiles-setup-dev-early.service: Deactivated successfully.
Nov 16 23:31:31 mathias-desktop systemd[1]: Stopped Create Static Device Nodes in /dev gracefully.
Nov 16 23:31:31 mathias-desktop systemd[1]: run-credentials-systemd\x2dsysusers.service.mount: Deactivated successfully.
Nov 16 23:31:31 mathias-desktop systemd[1]: run-credentials-systemd\x2dtmpfiles\x2dsetup\x2ddev\x2dearly.service.mount: Deactivated successfully.
Nov 16 23:31:31 mathias-desktop systemd[1]: run-credentials-systemd\x2dtmpfiles\x2dsetup\x2ddev.service.mount: Deactivated successfully.
Nov 16 23:31:31 mathias-desktop lvm[16119]:   4 logical volume(s) in volume group "cache_vg" unmonitored
Nov 16 23:31:31 mathias-desktop systemd[1]: lvm2-monitor.service: Deactivated successfully.
Nov 16 23:31:31 mathias-desktop systemd[1]: Stopped Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling.
Nov 16 23:31:31 mathias-desktop systemd[1]: Reached target System Shutdown.
Nov 16 23:31:31 mathias-desktop systemd[1]: Reached target Late Shutdown Services.
Nov 16 23:31:31 mathias-desktop systemd[1]: systemd-poweroff.service: Deactivated successfully.
Nov 16 23:31:31 mathias-desktop systemd[1]: Finished System Power Off.
Nov 16 23:31:31 mathias-desktop systemd[1]: Reached target System Power Off.
Nov 16 23:31:31 mathias-desktop systemd[1]: Shutting down.
Nov 16 23:31:31 mathias-desktop systemd-shutdown[1]: Syncing filesystems and block devices.
Nov 16 23:31:31 mathias-desktop systemd-shutdown[1]: Sending SIGTERM to remaining processes...
Nov 16 23:31:31 mathias-desktop systemd-journald[495]: Received SIGTERM from PID 1 (systemd-shutdow).
Nov 16 23:31:31 mathias-desktop systemd-journald[495]: Journal stopped


256.7-1:
Nov 18 12:11:22 mathias-desktop systemd[1]: Unmounting /vol/data...
Nov 18 12:11:22 mathias-desktop systemd[1]: proc-sys-fs-binfmt_misc.mount: Deactivated successfully.
Nov 18 12:11:22 mathias-desktop systemd[1]: run-credentials-systemd\x2dresolved.service.mount: Deactivated successfully.
Nov 18 12:11:22 mathias-desktop systemd[1]: run-credentials-systemd\x2dsysctl.service.mount: Deactivated successfully.
Nov 18 12:11:22 mathias-desktop systemd[1]: run-credentials-systemd\x2dtmpfiles\x2dsetup.service.mount: Deactivated successfully.
Nov 18 12:11:22 mathias-desktop systemd[1]: tmp.mount: Deactivated successfully.
Nov 18 12:11:22 mathias-desktop systemd[1]: Unmounted Temporary Directory /tmp.
Nov 18 12:11:22 mathias-desktop kernel: XFS (dm-3): Unmounting Filesystem 7d873b0a-34f2-4661-9d88-96f95421faea
Nov 18 12:11:22 mathias-desktop systemd[1]: boot.mount: Deactivated successfully.
Nov 18 12:11:22 mathias-desktop systemd[1]: Unmounted /boot.
Nov 18 12:11:22 mathias-desktop systemd[1]: Stopped target Swaps.
Nov 18 12:11:22 mathias-desktop systemd[1]: systemd-fsck@dev-disk-by\x2duuid-1210\x2d9B72.service: Deactivated successfully.
Nov 18 12:11:22 mathias-desktop systemd[1]: Stopped File System Check on /dev/disk/by-uuid/1210-9B72.
Nov 18 12:11:22 mathias-desktop systemd[1]: vol-data.mount: Deactivated successfully.
Nov 18 12:11:22 mathias-desktop systemd[1]: Unmounted /vol/data.
Nov 18 12:11:22 mathias-desktop systemd[1]: Reached target Unmount All Filesystems.
Nov 18 12:11:22 mathias-desktop systemd[1]: systemd-fsck@dev-cache_vg-data_lv.service: Deactivated successfully.
Nov 18 12:11:22 mathias-desktop systemd[1]: Stopped File System Check on /dev/cache_vg/data_lv.
Nov 18 12:11:22 mathias-desktop systemd[1]: Removed slice Slice /system/systemd-fsck.
Nov 18 12:11:22 mathias-desktop systemd[1]: Stopped target Preparation for Local File Systems.
Nov 18 12:11:22 mathias-desktop systemd[1]: Stopping Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling...
Nov 18 12:11:22 mathias-desktop systemd[1]: systemd-tmpfiles-setup-dev.service: Deactivated successfully.
Nov 18 12:11:22 mathias-desktop systemd[1]: Stopped Create Static Device Nodes in /dev.
Nov 18 12:11:22 mathias-desktop systemd[1]: systemd-tmpfiles-setup-dev-early.service: Deactivated successfully.
Nov 18 12:11:22 mathias-desktop systemd[1]: Stopped Create Static Device Nodes in /dev gracefully.
Nov 18 12:11:22 mathias-desktop lvm[1399]:   4 logical volume(s) in volume group "cache_vg" unmonitored
Nov 18 12:11:23 mathias-desktop systemd[1]: lvm2-monitor.service: Deactivated successfully.
Nov 18 12:11:23 mathias-desktop systemd[1]: Stopped Monitoring of LVM2 mirrors, snapshots etc. using dmeventd or progress polling.
Nov 18 12:11:23 mathias-desktop systemd[1]: Reached target System Shutdown.
Nov 18 12:11:23 mathias-desktop systemd[1]: Reached target Late Shutdown Services.
Nov 18 12:11:23 mathias-desktop systemd[1]: systemd-poweroff.service: Deactivated successfully.
Nov 18 12:11:23 mathias-desktop systemd[1]: Finished System Power Off.
Nov 18 12:11:23 mathias-desktop systemd[1]: Reached target System Power Off.
Nov 18 12:11:23 mathias-desktop systemd[1]: Shutting down.
Nov 18 12:11:23 mathias-desktop systemd-shutdown[1]: Syncing filesystems and block devices.
Nov 18 12:11:23 mathias-desktop systemd-shutdown[1]: Sending SIGTERM to remaining processes...
Nov 18 12:11:23 mathias-desktop systemd-journald[486]: Received SIGTERM from PID 1 (systemd-shutdow).
Nov 18 12:11:23 mathias-desktop systemd-journald[486]: Journal stopped
```

**Comment by bluca** [comment] 2024-11-20 09:51
I guess this might have been caused by the backport of https://github.com/systemd/systemd/pull/33355 in https://github.com/systemd/systemd/pull/35156 @YHNdnzj any idea?

**Comment by mokkurkalve** [comment] 2024-11-20 10:21
Experiencing the exact same on Arch Linux x86_64 with kernel 6.11.9.zen1-1. LVM on LUKS encrypted volumes. Messages coming too late at shutdown for journald to catch them. Downgrading to systemd 256.7-1 seems to fix the problem. At least the messages are gone.

**Comment by YHNdnzj** [comment] 2024-11-20 12:18
> I guess this might have been caused by the backport of https://github.com/systemd/systemd/pull/33355 in https://github.com/systemd/systemd/pull/35156 @YHNdnzj any idea?

Hmm, I don't see the connection to that PR. Instead I'd highly suspect #34330, considering that we might not be correctly taking sync progress for DM devices into account: https://github.com/systemd/systemd/pull/34289#issuecomment-2341204999

cc @poettering

**Comment by bluca** [comment] 2024-11-20 12:21
Uh yes I clicked on the wrong commit, sorry, meant that one

**Comment by p-kraszewski** [comment] 2024-11-20 17:14
I can confirm that behavior on 2 different Manjaro machines.

* Kern: `Linux 6.12.0-1-MANJARO`
* systemd: `systemd 256 (256.8-1-manjaro)`

**Comment by poettering** [comment] 2024-11-21 13:30
Note that the code in systemd's shutdown logic is fallback stuff only. LVM really shoud dissamble its DM devices on its own, cleanly. Either during regular shutdown or in the "exitrd".

We do the basic minimum only: sync the devices with a timeout, and do one ioctl to delete them, if that works. everything else really has to be done in LVM, with a better understanding of LVM does.

Hence please file an issue against your distro first, so that they fix this in their LVM logic and their exitrd.

**Comment by bluca** [comment] 2024-11-21 13:44
Yes if there's some issue in the exitrd it needs to be fixed there. However, if a regression is triggered by the mentioned commit, we should _also_ back it out of 256, as stable releases should be stable. So, is it possible that this started to happen now due to https://github.com/systemd/systemd/pull/34330 having been backported to 256?

**Comment by yuwata** [comment] 2024-11-21 18:10
@matte3560 @mokkurkalve @p-kraszewski Could you test #35286?

**Comment by poettering** [comment] 2024-11-22 09:24
> Yes if there's some issue in the exitrd it needs to be fixed there. However, if a regression is triggered by the mentioned commit, we should _also_ back it out of 256, as stable releases should be stable. So, is it possible that this started to happen now due to #34330 having been backported to 256?

No, we do not have to make this our problem. Yes, behaviour changed in an emergency/fallback codepath. But it's LVM's bug or the exitrds's bug if they even allow us to enter this codepath on this. This should not be load bearing, but LVM/exitrd make it so, but that's on them, not on us.

The question is whether to put more value into "guarantees to shut down eventually even on the fucktest uptest system" over "let's try to tape over seriously broken software".

I think the former is a lot more important from my pov.

@matte3560 have you contacted your distro about this? please contact your distro's LVM maintainers to fix their services so that such devices are disassembled cleanly on shutdown. Also, ask them to provide an exitrd to clean things up if such DM devices are used as root device.

**Comment by poettering** [comment] 2024-11-22 12:25
That commit was never in any release, we merged that long after v256.

**Comment by mokkurkalve** [comment] 2024-11-22 13:24
@yuwata I applied the patch to the sources but my compile failed early. 
```
Summary of Failures:

1040/1637 systemd:test / test-creds                                         FAIL             0.13s   killed by signal 6 SIGABRT
1249/1637 systemd:fstab / test-fstab-generator                              FAIL             0.03s   exit status 1
1250/1637 systemd:network / test-network-generator-conversion               FAIL             0.03s   exit status 1
1311/1637 systemd:sysusers / test-sysusers                                  FAIL             1.24s   exit status 1
```
I fear it's above my abilities to figure how to solve this. 
Let's hope somebody else can be helpful.

**Comment by matte3560** [comment] 2024-11-22 13:52
> @matte3560 @mokkurkalve @p-kraszewski Could you test #35286?

I need to tinker a bit to figure out how to get a patched systemd built on my machine, it's been a while. Will try to look at it this weekend though.

> @matte3560 have you contacted your distro about this? please contact your distro's LVM maintainers to fix their services so that such devices are disassembled cleanly on shutdown. Also, ask them to provide an exitrd to clean things up if such DM devices are used as root device.

I haven't raised the issue on any other bugtracker yet. I'm guessing the LVM gitlab is the place to report this, since they seem to provide the service files. Again, I'll try to look into it over the weekend.

**Comment by poettering** [comment] 2024-11-22 15:29
> It is in 256.8, as mentioned above, it was included in a backport PR, see: #35156

Sure, whatever. But please understand if you revert that, this will be a regression for other users. You lose some users and you win others. Not sure this is worth the effort, in particular as the original bug is not even ours. But, I personally don't care about the stable branch, apparently the policy on the stable branch is a bit yolo, so go ahead, if you want to revert it.

**Comment by poettering** [comment] 2024-11-22 15:30
> I haven't raised the issue on any other bugtracker yet. I'm guessing the LVM gitlab is the place to report this, since they seem to provide the service files. Again, I'll try to look into it over the weekend.

LVM people do not maintain archlinux' initrd/exitrd. 

Sorry, but your first point of contact should always be your distro if in doubt. Go to upstream only if you really know it's an upstream issue, or if downstreams ask you to.

**Comment by yuwata** [comment] 2024-11-22 16:11
> @yuwata I applied the patch to the sources but my compile failed early.
> 
> ```
> Summary of Failures:
> 
> 1040/1637 systemd:test / test-creds                                         FAIL             0.13s   killed by signal 6 SIGABRT
> 1249/1637 systemd:fstab / test-fstab-generator                              FAIL             0.03s   exit status 1
> 1250/1637 systemd:network / test-network-generator-conversion               FAIL             0.03s   exit status 1
> 1311/1637 systemd:sysusers / test-sysusers                                  FAIL             1.24s   exit status 1
> ```
> 
> I fear it's above my abilities to figure how to solve this. Let's hope somebody else can be helpful.

Not sure how you applied and tested, but I recommend to use a package builder for your distro, like rpmbuild for Fedora/CentOS, though you use Arch and I am not familiar with that.

**Comment by YHNdnzj** [comment] 2024-11-22 16:21
> @yuwata I applied the patch to the sources but my compile failed early. 
> ```
> Summary of Failures:
> 
> 1040/1637 systemd:test / test-creds                                         FAIL             0.13s   killed by signal 6 SIGABRT
> 1249/1637 systemd:fstab / test-fstab-generator                              FAIL             0.03s   exit status 1
> 1250/1637 systemd:network / test-network-generator-conversion               FAIL             0.03s   exit status 1
> 1311/1637 systemd:sysusers / test-sysusers                                  FAIL             1.24s   exit status 1
> ```
> I fear it's above my abilities to figure how to solve this. 
> Let's hope somebody else can be helpful.
> 

Please try building in a clean chroot: https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot

**Comment by mokkurkalve** [comment] 2024-11-22 20:15
> Please try building in a clean chroot: https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot

After fiddeling about I managed to build in a clean chroot, loading the patch from the PKGBUILD. 
However, unfortunately, I get the same messages at shutdown along the line of ```
Could not detach DM /dev/dm-0: Device or resource busy``` as before the patch.

**Comment by yuwata** [comment] 2024-11-22 20:28
@mokkurkalve Do you observe any error message about syncing?

**Comment by mokkurkalve** [comment] 2024-11-22 20:32
> @mokkurkalve Do you observe any error message about syncing?

It is very hard because it's just on the console a second before shutdown. As said before it's to late for logs, journald are already terminated. So I'm not really shure what I'm seeing, it goes to fast....

**Comment by yuwata** [comment] 2024-11-22 20:50
Another attempt -> #35312.
@mokkurkalve Please test the PR. Thank you.

**Comment by mokkurkalve** [comment] 2024-11-22 21:36
> Another attempt -> #35312. @mokkurkalve Please test the PR. Thank you.

This time it seems you succeeded. At least there are no error messages at shutdown now, so I presume so.

**Closed as completed** 2024-11-23 08:31 UTC
Labels: bug 🐛, regression ⚠️, shutdown

**Comment by matte3560** [comment] 2024-11-24 10:11
> Another attempt -> #35312. @mokkurkalve Please test the PR. Thank you.

Just tested on my machine as well. Seems to be working well.

**Comment by yuwata** [comment] 2024-11-24 11:26
@matte3560 Thank you for testing!

**Comment by matte3560** [comment] 2024-11-24 21:25
> @matte3560 Maybe one could get Arch Linux to cherrypick this patch (waiting for the fix to go through the ecosystem) ?

I haven't made an account on the Arch GitLab yet, so I can't create an issue right now unfortunately (account registration seems to be restricted). Sent an email so hopefully the turnaround is quick. If anyone else has access they could do it instead.

I guess they might pick this patch up in the meantime. Sounds like the potential LVM service and exitrd issues should be looked at too, even if the patch covers up an underlying issue.

**Comment by mokkurkalve** [comment] 2024-11-24 21:45
> I haven't made an account on the Arch GitLab yet, so I can't create an issue right now unfortunately (account registration seems to be restricted). Sent an email so hopefully the turnaround is quick. If anyone else has access they could do it instead.

Oh, yeah, there's that... I started a brief attempt once at creating a GitLab account, but, I don't remember... It was complicated and I just gave up and haven't gotten around to it since... Well, we'll see.

**Comment by matte3560** [comment] 2024-11-24 22:25
It was very quick, I created an issue on the Arch tracker as well: https://gitlab.archlinux.org/archlinux/packaging/packages/systemd/-/issues/35
