### ISSUE TITLE
systemd-cryptenroll: ECC is not auto selected as primary algorithm

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#29756] opened 2023-10-28 22:26 UTC
### systemd version the issue has been seen with

254

### Used distribution

Arch Linux

### Linux kernel version used

6.5.9-arch2-1

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

When enrolling my system's TPM2 device, for some reason `systemd-cryptenroll` does not automatically select ECC as the default algorithm. Instead, systemd-cryptenroll chooses to use RSA as the LUKS2 header reports `"tpm2-primary-alg":"rsa"`.

Below I listed the following output of some relevant commands that may or may not help.

tpm2_getcap ecc-curves:
<pre>
TPM2_ECC_NIST_P256: 0x3
TPM2_ECC_NIST_P384: 0x4
TPM2_ECC_BN_P256: 0x10
</pre>

cat /sys/class/tpm/tpm0/tpm_version_major:
<pre>
2
</pre>

tpm2_getcap properties-fixed:
<details>
<pre>
TPM2_PT_FAMILY_INDICATOR:
  raw: 0x322E3000
  value: "2.0"
TPM2_PT_LEVEL:
  raw: 0
TPM2_PT_REVISION:
  raw: 0x8A
  value: 1.38
TPM2_PT_DAY_OF_YEAR:
  raw: 0x3D
TPM2_PT_YEAR:
  raw: 0x7E2
TPM2_PT_MANUFACTURER:
  raw: 0x414D4400
  value: "AMD"
TPM2_PT_VENDOR_STRING_1:
  raw: 0x414D4400
  value: "AMD"
TPM2_PT_VENDOR_STRING_2:
  raw: 0x0
  value: ""
TPM2_PT_VENDOR_STRING_3:
  raw: 0x0
  value: ""
TPM2_PT_VENDOR_STRING_4:
  raw: 0x0
  value: ""
TPM2_PT_VENDOR_TPM_TYPE:
  raw: 0x1
TPM2_PT_FIRMWARE_VERSION_1:
  raw: 0x30039
TPM2_PT_FIRMWARE_VERSION_2:
  raw: 0x5
TPM2_PT_INPUT_BUFFER:
  raw: 0x400
TPM2_PT_HR_TRANSIENT_MIN:
  raw: 0x6
TPM2_PT_HR_PERSISTENT_MIN:
  raw: 0x2
TPM2_PT_HR_LOADED_MIN:
  raw: 0x3
TPM2_PT_ACTIVE_SESSIONS_MAX:
  raw: 0x40
TPM2_PT_PCR_COUNT:
  raw: 0x18
TPM2_PT_PCR_SELECT_MIN:
  raw: 0x3
TPM2_PT_CONTEXT_GAP_MAX:
  raw: 0xFF
TPM2_PT_NV_COUNTERS_MAX:
  raw: 0x0
TPM2_PT_NV_INDEX_MAX:
  raw: 0x800
TPM2_PT_MEMORY:
  raw: 0x6
TPM2_PT_CLOCK_UPDATE:
  raw: 0x1000
TPM2_PT_CONTEXT_HASH:
  raw: 0xB
TPM2_PT_CONTEXT_SYM:
  raw: 0x6
TPM2_PT_CONTEXT_SYM_SIZE:
  raw: 0x100
TPM2_PT_ORDERLY_COUNT:
  raw: 0xFF
TPM2_PT_MAX_COMMAND_SIZE:
  raw: 0x1000
TPM2_PT_MAX_RESPONSE_SIZE:
  raw: 0x1000
TPM2_PT_MAX_DIGEST:
  raw: 0x20
TPM2_PT_MAX_OBJECT_CONTEXT:
  raw: 0x6D0
TPM2_PT_MAX_SESSION_CONTEXT:
  raw: 0xFC
TPM2_PT_PS_FAMILY_INDICATOR:
  raw: 0x322E3000
TPM2_PT_PS_LEVEL:
  raw: 0x0
TPM2_PT_PS_REVISION:
  raw: 0x101
TPM2_PT_PS_DAY_OF_YEAR:
  raw: 0x3D
TPM2_PT_PS_YEAR:
  raw: 0x7E2
TPM2_PT_SPLIT_MAX:
  raw: 0x80
TPM2_PT_TOTAL_COMMANDS:
  raw: 0x6E
TPM2_PT_LIBRARY_COMMANDS:
  raw: 0x6D
TPM2_PT_VENDOR_COMMANDS:
  raw: 0x1
TPM2_PT_NV_BUFFER_MAX:
  raw: 0x400
TPM2_PT_MODES:
  raw: 0x0
</pre>
</details>

tpm2_getcap algorithms:
<details>
<pre>
rsa:
  value:      0x1
  asymmetric: 1
  symmetric:  0
  hash:       0
  object:     1
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     0
sha1:
  value:      0x4
  asymmetric: 0
  symmetric:  0
  hash:       1
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     0
hmac:
  value:      0x5
  asymmetric: 0
  symmetric:  0
  hash:       1
  object:     0
  reserved:   0x0
  signing:    1
  encrypting: 0
  method:     0
aes:
  value:      0x6
  asymmetric: 0
  symmetric:  1
  hash:       0
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     0
mgf1:
  value:      0x7
  asymmetric: 0
  symmetric:  0
  hash:       1
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     1
keyedhash:
  value:      0x8
  asymmetric: 0
  symmetric:  0
  hash:       1
  object:     1
  reserved:   0x0
  signing:    1
  encrypting: 1
  method:     0
xor:
  value:      0xA
  asymmetric: 0
  symmetric:  1
  hash:       1
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     0
sha256:
  value:      0xB
  asymmetric: 0
  symmetric:  0
  hash:       1
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     0
rsassa:
  value:      0x14
  asymmetric: 1
  symmetric:  0
  hash:       0
  object:     0
  reserved:   0x0
  signing:    1
  encrypting: 0
  method:     0
rsaes:
  value:      0x15
  asymmetric: 1
  symmetric:  0
  hash:       0
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 1
  method:     0
rsapss:
  value:      0x16
  asymmetric: 1
  symmetric:  0
  hash:       0
  object:     0
  reserved:   0x0
  signing:    1
  encrypting: 0
  method:     0
oaep:
  value:      0x17
  asymmetric: 1
  symmetric:  0
  hash:       0
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 1
  method:     0
ecdsa:
  value:      0x18
  asymmetric: 1
  symmetric:  0
  hash:       0
  object:     0
  reserved:   0x0
  signing:    1
  encrypting: 0
  method:     1
ecdh:
  value:      0x19
  asymmetric: 1
  symmetric:  0
  hash:       0
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     1
ecdaa:
  value:      0x1A
  asymmetric: 1
  symmetric:  0
  hash:       0
  object:     0
  reserved:   0x0
  signing:    1
  encrypting: 0
  method:     0
ecschnorr:
  value:      0x1C
  asymmetric: 1
  symmetric:  0
  hash:       0
  object:     0
  reserved:   0x0
  signing:    1
  encrypting: 0
  method:     0
kdf1_sp800_56a:
  value:      0x20
  asymmetric: 0
  symmetric:  0
  hash:       1
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     1
kdf1_sp800_108:
  value:      0x22
  asymmetric: 0
  symmetric:  0
  hash:       1
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     1
ecc:
  value:      0x23
  asymmetric: 1
  symmetric:  0
  hash:       0
  object:     1
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     0
symcipher:
  value:      0x25
  asymmetric: 0
  symmetric:  0
  hash:       0
  object:     1
  reserved:   0x0
  signing:    0
  encrypting: 0
  method:     0
ctr:
  value:      0x40
  asymmetric: 0
  symmetric:  1
  hash:       0
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 1
  method:     0
ofb:
  value:      0x41
  asymmetric: 0
  symmetric:  1
  hash:       0
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 1
  method:     0
cbc:
  value:      0x42
  asymmetric: 0
  symmetric:  1
  hash:       0
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 1
  method:     0
cfb:
  value:      0x43
  asymmetric: 0
  symmetric:  1
  hash:       0
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 1
  method:     0
ecb:
  value:      0x44
  asymmetric: 0
  symmetric:  1
  hash:       0
  object:     0
  reserved:   0x0
  signing:    0
  encrypting: 1
  method:     0
</pre>
</details>

### Unexpected behaviour you saw

`"tpm2-primary-alg":"rsa"` is in the LUKS2 header for my device when running the command: `cryptsetup luksDump /dev/nvme0n1p2 --dump-json-metadata`

### Steps to reproduce the problem

On a system with an AMD TPM2 device:

1. systemd-cryptenroll /dev/nvme0n1p2 --tpm2-device=auto
2. cryptsetup luksDump /dev/nvme0n1p2 --dump-json-metadata

As a result, `"tpm2-primary-alg":"rsa"` is chosen.

**Comment by poettering** [comment] 2023-10-30 10:34
We do default to ECC by default actually, and that since a long time. Most likely your TPM already had a stored SRK on it (probably created by Windows), because we'll reuse any stored SRK preferable, and will only generate a new one if none has been stored so far.

Consider deleting your SRK and re-enrolling.

If this doesn't suffice, then please report back, but I am very confident this is not a systemd issue. Closing hence.

(I mean, when I initially hacked this up I was so annoyed about how long TPMs take to generate new RSA keys, which is why from basically day 1 we defaulted to ECC)

**Closed as completed by poettering** 2023-10-30 10:34 UTC
Labels: bug 🐛

**Comment by c3Ls1US** [comment] 2023-10-30 17:11
Thank you! I can confirm that deleting the SRK and re-enrolling solved the issue. As a result, I see the field `"tpm2-primary-alg":"ecc"` in the LUKS2 header
