### ISSUE TITLE
DynamicUser= is missing error-handling for setup_namespace() == EPERM or EACCESS

### ISSUE THREAD

**Issue by sourcejedi** [systemd/systemd#9835] opened 2018-08-08 18:47 UTC
Broadly suggested in an issue on Ubuntu 18.04: https://utcc.utoronto.ca/~cks/space/blog/linux/SystemdTimesyncdFailure

Audited 7e8d494 (v239+) source files [execute.c](https://github.com/systemd/systemd/blob/7e8d494/src/core/execute.c) / [namespace.c](https://github.com/systemd/systemd/blob/7e8d494/src/core/namespace.c) (and checking the general DynamicUser= design from the [systemd blog post](http://0pointer.net/blog/dynamic-users-with-systemd.html)).

Using `DynamicUser=yes` with e.g. `StateDirectory=foobar`, requires a private mount namespace.  setup_namespace() is used to make a sub-directory of /var/lib/private/ accessible.  In the main namespace, /var/lib/private is inaccessible (`chmod a-rwx`) unless you have CAP_DAC_SEARCH.

But apply_mount_namespace() [silently ignores](https://github.com/systemd/systemd/blob/7e8d494/src/core/execute.c#L2389) EPERM or EACCESS errors from setup_namespace().  E.g. if `unshare(CLONE_NEWNS)` fails with EPERM or EACCESS, the error will be ignored.  Then I think the daemon is going to hit EACCESS when it tries to access its subdirectory - and you're in very annoying debugging territory.

In cks' case on Ubuntu 18.04, the namespace failure actually seemed to be triggered by some inconvenient dead FUSE mount.  I don't know whether that full scenario is also reproducible on 7e8d494.

**Expected behaviour you didn't see**

When using `DynamicUser=yes` with `StateDirectory=foobar`, failure of `unshare(CLONE_NEWNS)` failure is treated as fatal and logged, showing the error code even when it is EPERM or EACCESS (and some clue that would let you work out this was related to mount namespaces).

EDIT: And if this hard failure applies *only* to `DynamicUser=yes`, you'd really want the message to give some clue about that.  I guess at minimum, mentioning /var/lib/private would give a clue.

---

**Steps to reproduce the problem**

The steps were tested with systemd v238 on Fedora Linux.

Start the following `test.service`, inside a systemd-nspawn container which was started manually with the option `--drop-capability=CAP_SYS_ADMIN`.  On systemd v238, `test.service` will try to run the `touch` command, and the touch command will fail with "Permission denied".  (It will succeed when run inside a container which is allowed CAP_SYS_ADMIN).

```
[Service]
Type=oneshot
DynamicUser=yes
User=test-service
StateDirectory=test-service
ExecStart=/bin/cat /proc/self/mountinfo
ExecStart=/bin/ls -l /proc/self/ns
ExecStart=/bin/ls -ld /var/lib/test-service
ExecStart=/bin/touch /var/lib/test-service/test
```

**Expected behaviour you didn't see (from reproducer)**

The service failure should have happened *before* running the touch command. (systemd should have logged an error message etc, as above).

**Comment by siebenmann** [comment] 2018-08-08 19:10
Just for the record, strace output for our issue shows that the problem is with something other than `unshare()`; the trace we see is:

````
[....]
26787 openat(AT_FDCWD, "/run/systemd/unit-root/h/281/ckstst", O_RDONLY|O_CLOEXEC|O_PATH|O_DIRECTORY) = 4
26787 name_to_handle_at(4, "thinclient_drives", {handle_bytes=128}, 0x7ffe1eca7454, 0) = -1 EACCES (Permission denied)
26787 openat(4, "thinclient_drives", O_RDONLY|O_CLOEXEC|O_PATH) = -1 EACCES (Permission denied)
26787 newfstatat(4, "thinclient_drives", 0x7ffe1eca7560, AT_SYMLINK_NOFOLLOW) = -1 EACCES (Permission denied)
26787 close(4)                          = 0
26787 close(3)                          = 0
26787 chdir("/")                        = 0
26787 setresgid(62583, 62583, 62583)    = 0
[...]
````

On Ubuntu 18.04's version of systemd (based on version 237), the issue happens any time we have a FUSE mount (active or inactive) in a NFS mounted home directory that is not world-accessible (and thus not accessible to UID 0 on the NFS client). This happens with eg sshfs.

**Comment by sourcejedi** [comment] 2018-08-08 19:48
@siebenmann Sounds like it could be something along the lines of `ProtectHome=read-only` -> bind_remount_recursive_with_mountinfo() -> path_is_mount_point().  Ouch.  Thanks for the specific details of your case.

I haven't worked out exactly what conditions would trigger it, but it seems undesirable.  Like you mentioned on Twitter, it looks like it should be possible to trigger with something like FUSE mount(s) and no_allow_others.

**Comment by yuwata** [comment] 2018-08-09 12:53
@sourcejedi Are you working on this? If not, I may try to tackle this tonight or tomorrow.

@siebenmann If possible, could you provide a minimal reproducer for this?

**Comment by sourcejedi** [comment] 2018-08-09 17:57
@yuwata I am not working on implementing the title issue, which is about providing better troubleshooting when there is a error. But I've edited it to add a demonstration of the title issue, tested on v238. Nice to have some more confirmation, and maybe you'll find it useful.

I'm also hoping to test the theory in my comment about siebenmann's `strace` output, and provide a demonstration *at least* on v238.

@poettering, anyone: a heads up. We noticed DynamicUsers=yes + StateDirectory=foobar (and a service which actually relies on the state directory) will cause failures on unprivileged containers. I don't see this mentioned in the NEWS items, about the systemd services that switched to DynamicUsers=yes. I reported this issue to help users troubleshoot problems like this.  But maybe we need to think about the services we switched and whether this effect is acceptable?

If it is acceptable for some services to fail inside unpriv containers, but not others, I'm feeling it would be best to highlight this issue in `man systemd.exec` which describes `DynamicUsers=yes`.

**Comment by yuwata** [comment] 2018-08-10 05:39
#9848.

**Comment by yuwata** [comment] 2018-08-11 13:16
@siebenmann I hope that #9852 fixes your original issue. I have tested with the PR with the simpler reproducer provided by @sourcejedi in #9844.

If it is possible, please test your case with the recent snapshot. Thank you.

**Comment by siebenmann** [comment] 2018-08-16 16:08
I managed to build the current systemd git tip on a scratch Ubuntu 18.04 machine and install it, and my test case appears to work now; I can start and restart systemd-timesyncd in a sshfs mount situation where it fails on other 18.04 machines with the stock systemd. Inspecting the /proc/<PID>/mounts of the resulting systemd-timesyncd shows that it does have the expected /var/lib/private tmpfs mount.

**Comment by sourcejedi** [comment] 2018-08-16 21:38
@siebenmann excellent. Thanks again for your information, as NFS root_squash is [slightly different](https://unix.stackexchange.com/questions/463076/why-cant-unprivileged-users-nest-fuse-mounts-but-they-can-mount-fuse-inside-nf) from the FUSE `!allow_other` reproducer.

**Comment by yuwata** [comment] 2018-09-03 14:04
#9852 has been merged. Let's close this.

**Closed as completed by yuwata** 2018-09-03 14:04 UTC
Labels: pid1, needs-better-log-message
