### ISSUE TITLE
systemd  Caught <ABRT>   dumped core as pid 1776634  Freezing execution   

### ISSUE THREAD

**Issue by Rockybeerl** [systemd/systemd#22026] opened 2022-01-06 12:24 UTC
**systemd version the issue has been seen with**
     243 
**Used distribution**

**Linux kernel version used (uname -a)**
4.14.90
**CPU architecture issue was seen on**
arm64 
**Expected behaviour you didn't see**
systemd is in a suspended state and cannot use operating system commands, such as reboot failure systemctl status sshd and systemctl status systemd-login exceptions。
**Unexpected behaviour you saw**
systemd is in a suspended state and cannot use operating system commands, such as reboot failure,no response, systemctl status sshd and systemctl status systemd-login exceptions。
Steps to reproduce the problem
It is difficult to reproduce. It is not reproduced at present
**Additional program output to the terminal or log subsystem illustrating the issue**
 When the operating system is running, it is found that systemd is abnormal and the phenomenon of dumped core occurs。
systemd [1] Caught <ABRT>, dumped core as pid 1776634 .
systemd[1]: Freezing execution .
The systemd version used is systemd-243-17,The relevant logs before systemd caught < abrt > are as follows:
......
systemd[417081]: run-user-1281.mount: Succeeded.
systemd[1]: run-user-1281.mount: Succeeded.
systemd[1]: user-runtime-dir@1281.service: Succeeded.
systemd[1]: Stopped User Runtime Directory /run/user/1281.
systemd[1]: Removed slice User Slice of UID 1281.
systemd[1]: Caught <ABRT>, dumped core as pid 1776634.
systemd[1]: Freezing execution.
At the same time, trace the core, and the stack information is as follows:
![image](https://user-images.githubusercontent.com/42106111/148381903-746e5711-ac93-4865-81d4-ad2730a60fa1.png)

You can see the call stack of systemd:
transaction_add_job_and_dependencies()->job_dependency_new()->__libc_calloc(calloc function of C library) ->_int_malloc()-->__malloc_assert(), In the C library, "assert ((unsigned long) (size) > = (unsigned long) (NB));" An exception occurred in the statement, Print relevant variable information at the same time.  
![image](https://user-images.githubusercontent.com/42106111/148382018-b0da2611-7d08-44f8-9f4c-b3379dc44b33.png)

According to the exception information, I check the patch and repair records that have not been handled in the relevant submission records of systemd。Is this a systemd bug? Under what circumstances will this problem be triggered? How to solve this problem?, What are the debugging methods or information you need to get to debug this problem. 

And I read the main version of systemd source code ,  job_dependency_new（）function is the same in src/core/job.c c file

**Comment by yuwata** [comment] 2022-01-06 12:34
Sorry, v243 is too old here, as this is upstream issue tracker. Please contact to your downstream, or try to reproduce the issue with recent releases (v249 or v250) or current git HEAD. Closing.

**Closed as completed by yuwata** 2022-01-06 12:34 UTC
Labels: not-our-bug, version-too-ancient

**Comment by yuwata** [comment] 2022-01-06 12:42
Also, at least current `job_dependency_new()` seems to have no issue. I guess this is an issue in glibc.

**Comment by Rockybeerl** [comment] 2022-01-06 13:15
Yes  at least current job_dependency_new() seems to have no issue ,and  job_dependency_new()  code has not been modified does not mean that there are no bugs。 You guess this is an issue in glibc  ,   I went to the glibc community to confirm that there was an exception in the value passed in by the systemd layer

**Comment by Rockybeerl** [comment] 2022-01-10 03:22
After checking glibc, there are no calloc related fixes and related issues

**Comment by keszybz** [comment] 2022-01-10 08:57
@Rockybeerl 243 was releases more than two years ago and in the meantime there have been countless fixes in our codebase. Allocation bugs like this are quite often triggered by a seemingly unrelated bug in some earlier allocation or freeing. So as @yuwata wrote, it is very hard to provide an answer to your questions. We limit ourselves to fixing only recent versions because we simply don't have enough resources to address issues in old versions, sorry.
