### ISSUE TITLE
systemd-run: add persist option to write the transient unit file to /etc/systemd/system

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#14245] opened 2019-12-04 16:15 UTC
I can copy the unit files manually from /run/systemd/transient but it would be nice to have an option to do this automatically. I'm using systemd-run to start daemons remotely on nspawn machines and need the generated units to restart when the nspawn machine is rebooted which requires persisting the transient unit files somewhere and enabling them.

**Comment by anitazha** [comment] 2019-12-04 20:39
Duplicate of #13485

**Closed as completed by anitazha** 2019-12-04 20:39 UTC
