### ISSUE TITLE
Race condition between systemd-networkd and udev rules

### ISSUE THREAD

**Issue by sknaumov** [systemd/systemd#9682] opened 2018-07-21 07:39 UTC
I'm trying to rename network interfaces and bring them up using systemd 237 from Ubuntu 18.04 (system created using debootstrap + some other basic packages, network manager is not installed, net.ifnames=0, biosdevname=0).

I used the following methods, neither of them work:

1. Use udev rules for renaming and match by new name in /etc/systemd/network files to apply [Network] settings.
2. Use udev rules for renaming and match by driver name in /etc/systemd/network files to apply [Network] settings.
3. Match by driver name to rename with [Link] and to apply [Network] settings.

With (1) interfaces are renamed, but not brought up. Restart of systemd-networkd service helps.
With (2) and (3) interfaces are brought up, but not renamed.

I guess that there could be some delay for interface renaming and therefore some race condition between udev and networkd service. What could be the best workaround, say how to introduce some delay between udev and networkd or how to restart networkd after udev, but before other services like dnsmasq (to make method (1) work)?

**Comment by yuwata** [comment] 2018-07-21 09:30
Could you test (1) with v239. I think this at least the case (1) is already fixed.

**Comment by sknaumov** [comment] 2018-07-21 13:07
@yuwata I will on Monday, but could you also suggest some easy workaround for v237?

**Comment by yuwata** [comment] 2018-07-21 14:33
Hmm, I have no idea except restarting networkd.

I think the case (1) is a duplicate of #8794 and #7920, and is fixed by #8795.

**Comment by sknaumov** [comment] 2018-07-23 14:52
I have managed to fix it for systemd 237 by applying a small delay:

> $ cat /etc/systemd/system/systemd-udevd.service.d/fix-iface-rename.conf
> [Service]
> ExecStartPost=/bin/sleep 1

**Comment by poettering** [comment] 2018-11-30 12:48
Duplicate of #7293

**Closed as completed by poettering** 2018-11-30 12:48 UTC
Labels: udev, network, needs-reporter-feedback ❓, duplicate
