### ISSUE TITLE
systemd-udevd: could not read from '/sys/module/acpi_cpufreq/initstate': No such device

### ISSUE THREAD

**Issue by pheiduck** [systemd/systemd#24152] opened 2022-07-29 17:11 UTC
### systemd version the issue has been seen with

251.3

### Used distribution

Manjaro Linux

### Linux kernel version used

5.18.14

### CPU architectures issue was seen on

x86_64

### Component

systemd-udevd

### Expected behaviour you didn't see

none error if AMD P-State is used.

### Unexpected behaviour you saw

```
$ journalctl -b -p err
could not read from '/sys/module/acpi_cpufreq/initstate': No such device
```

### Steps to reproduce the problem

Is triggerd if you update System > reboot.
Execute `journalctl -b -p err`

**Comment by yuwata** [comment] 2022-07-30 01:33
Duplicate of #20605. Closing.

**Closed as completed by yuwata** 2022-07-30 01:33 UTC
Labels: bug 🐛, udev
