### ISSUE TITLE
Accounting=yes in user.slice or user-.slice.d/foo.conf does not enable the corresponding controller

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#9763] opened 2018-07-31 15:38 UTC
**systemd version the issue has been seen with**
239

**Used distribution**
Debian buster (testing) as of July 2018

**Expected behaviour you didn't see**

If we write the following in `/etc/systemd/system/user-.slice.d/foo.conf`, those accounting are enabled:

```
CPUAccounting=yes
MemoryAccounting=yes
IOAccounting=yes
IPAccounting=yes
TasksAccounting=yes

MemoryHigh=90%
```

**Unexpected behaviour you saw**

`cpu` and ` io` controllers are not enabled while `memory.high` is properly set, as

```
# ls -1 /sys/fs/cgroup/user.slice/user-0.slice
cgroup.controllers
cgroup.events
cgroup.max.depth
cgroup.max.descendants
cgroup.procs
cgroup.stat
cgroup.subtree_control
cgroup.threads
cgroup.type
cpu.stat
memory.current
memory.events
memory.high
memory.low
memory.max
memory.stat
pids.current
pids.events
pids.max
session-1.scope
session-3.scope
user@0.service
# cat /sys/fs/cgroup/user.slice/user-0.slice/memory.high 
3574370304
```

I used Linux 4.17 kernel, which has `cpu.stat` even if the CPU controller is not enabled. As such, `systemctl status` shows the CPU accounting, but it does not show the IO accounting. The current programming logic should also enable the CPU controller.

```
# systemctl status -l user-0.slice 
* user-0.slice - User Slice of UID 0
   Loaded: loaded
  Drop-In: /lib/systemd/system/user-.slice.d
           `-10-defaults.conf
           /etc/systemd/system/user-.slice.d
           `-my.conf
   Active: active since Wed 2018-08-01 00:13:02 JST; 1min 34s ago
       IP: 0B in, 0B out
    Tasks: 7 (limit: 9925)
   Memory: 12.9M (high: 3.3G)
      CPU: 212ms
   CGroup: /user.slice/user-0.slice
           |-session-1.scope
           | |-499 /bin/login -p --
           | `-629 -bash
           |-session-3.scope
           | |-634 sshd: root@pts/0
           | |-640 -bash
           | `-648 systemctl status -l user-0.slice
           `-user@0.service
             `-init.scope
               |-618 /lib/systemd/systemd --user
               `-619 (sd-pam)

Aug 01 00:13:02 buster-wayland systemd[618]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Aug 01 00:13:02 buster-wayland systemd[618]: Reached target Paths.
Aug 01 00:13:02 buster-wayland systemd[618]: Listening on GnuPG cryptographic agent and passphrase cache.
Aug 01 00:13:02 buster-wayland systemd[618]: Starting D-Bus User Message Bus Socket.
Aug 01 00:13:02 buster-wayland systemd[618]: Listening on D-Bus User Message Bus Socket.
Aug 01 00:13:02 buster-wayland systemd[618]: Reached target Sockets.
Aug 01 00:13:02 buster-wayland systemd[618]: Reached target Basic System.
Aug 01 00:13:02 buster-wayland systemd[618]: Reached target Default.
Aug 01 00:13:02 buster-wayland systemd[618]: Startup finished in 319ms.
Aug 01 00:13:02 buster-wayland login[629]: ROOT LOGIN  on '/dev/tty1'
```

`systemd` seems to load the configurations properly, as

```
# systemctl cat user-0.slice
# /lib/systemd/system/user-.slice.d/10-defaults.conf
#  SPDX-License-Identifier: LGPL-2.1+
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=User Slice of UID %j
After=systemd-user-sessions.service

[Slice]
TasksMax=33%

# /etc/systemd/system/user-.slice.d/my.conf
[Slice]
CPUAccounting=yes
MemoryAccounting=yes
IOAccounting=yes
IPAccounting=yes
TasksAccounting=yes

MemoryHigh=90%
# systemctl show user-0.slice | grep Accounting
CPUAccounting=yes
IOAccounting=yes
BlockIOAccounting=no
MemoryAccounting=yes
TasksAccounting=yes
IPAccounting=yes
```

The reason why `memory` and `tasks` controllers are enabled is maybe the following delegation of memory and cpu.

```
# systemctl cat user@0.service
# /lib/systemd/system/user@.service
#  SPDX-License-Identifier: LGPL-2.1+
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=User Manager for UID %i
After=systemd-user-sessions.service
After=user-runtime-dir@%i.service
Requires=user-runtime-dir@%i.service

[Service]
User=%i
PAMName=systemd-user
Type=notify
ExecStart=-/lib/systemd/systemd --user
Slice=user-%i.slice
KillMode=mixed
Delegate=pids memory
TasksMax=infinity
TimeoutStopSec=120s
```

`echo +cpu >/sys/fs/cgroup/cgroup.subtree_control` enables the CPU controller, and the above symptom is independent of [9733](https://github.com/systemd/systemd/issues/9733)

**Steps to reproduce the problem**

Use unified cgroup hierarchy and put the above file into `/etc/systemd/system/user-.slice.d`. This symptom was observed in Debian testing running on a barebone hardware. I also did the same thing in Debian unstable in systemd-nspawn running on Ubuntu 18.04. In Debian unstable in systemd-nspawn, everything worked as expected, i.e., `/sys/fs/cgroup/user.slice/user-0.slice` has CPU and IO files.

**Comment by ryutaroh-matsumoto** [comment] 2018-08-03 16:38
I found that my description of condition of reproducing this is incomplete:

When I login as root I always see this symptom. But after `touch some.service; systemctl daemon-reload`, `cpu` and `io` controllers are enabled at `/sys/fs/cgroup/user.slice/user-0.slice/cgroup.controllers`. I also updated the issue title as the original title is ambiguous.

**Comment by ryutaroh-matsumoto** [comment] 2018-08-04 22:59
Writing the following content into `user.slice` does not enable CPU or IO controllers in the unified cgroup hierarchy. On the other hand, writing it into `system.slice` DOES enable CPU and IO controllers. I updated the issue title.

```
[Slice]
CPUAccounting=yes
MemoryAccounting=yes
IOAccounting=yes
IPAccounting=yes
TasksAccounting=yes
```

**Comment by ryutaroh-matsumoto** [comment] 2018-08-05 03:15
Adding

```
[Install]
WantedBy=multi-user.target
```

and run `systemctl enable user.slice` *fixes* this issue. In other words, the same workaround is valid as the following other issues and I suspect that the root cause is also the same:

* [Incomplete initialization of user-$UID.slice disturbing per-user resource control](https://github.com/systemd/systemd/issues/9578)
* [Incomplete initialization of user-$UID.slice disturbs systemd-run --user -t -p MemoryHigh=1G](https://github.com/systemd/systemd/issues/9512)
* [Memory accounting regression for user units](https://github.com/systemd/systemd/issues/9502)

**Comment by poettering** [comment] 2018-11-23 11:35
This actually appears to be a duplicate of #9512: the same controller realization problems cause both issues, hence let's close this one as a duplicate.

**Closed as completed by poettering** 2018-11-23 11:35 UTC
Labels: bug 🐛, cgroups, pid1, duplicate
