### ISSUE TITLE
 systemd upgrade to 252-2 breaks suspend, suspend-then-hibernate

### ISSUE THREAD

**Issue by testudomarginata** [systemd/systemd#25377] opened 2022-11-14 05:55 UTC
### systemd version the issue has been seen with

252-2, 252.1-1

### Used distribution

Debian

### Linux kernel version used

Linux 6.0.0-4-amd64

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

Sytem ( in this case a Surface Go3 and a Thinkpad X1 Yoga Titanium, running Debian testing/Sid mix with KDE Plasma on wayland as desktop environment) has suspend-then-hibernate enabled. 
Closing the lid causes the system to enter s2idle and then hibernate after HibernateDelaySec.

### Unexpected behaviour you saw

Also reported on the Debian bug tracker:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1023483

Suspend (seemingly random):
When the system is put into s2idle (e.g. after idling a while or by
closing the lid), sometimes (not easily reproducible) the display stays
off and keyboard, touchpad and touchscreen are not repsonsive.
I can connect to the system by ssh, though.

Suspend-then-hibernate (reproducible most of the time):
When the system is put into s2idle and suspend-then-hibernate is
activated, no hibernation occurs even after multiples of HibernateDelaySec.
When the system is woken up before HibernateDelaySec has passed, it
usually wakes up normally but sometimes doesn't (see above).
When the system is woken up after HibernateDelaySec has passed, the
display always remains off and input devices are not responsive. Still,
ssh connection is possible then as well.

### Steps to reproduce the problem

- Boot system
- Login at SDDM
- Close lid
- Wait 3 minutes
- Open lid
- Shutdown either from command line or via ssh login

Please find attached log files from my Thinkpad for both versions 251-6
(everything works well) and 252-2 (suspend-then-hibernate issue as
described above).

Downgrading to version 251.6-1 solves this issue.

[boot-login-suspend-then-hibernate-systemd-251-6.txt](https://github.com/systemd/systemd/files/9999990/boot-login-suspend-then-hibernate-systemd-251-6.txt)
[boot-login-suspend-then-hibernate-systemd-252-2.txt](https://github.com/systemd/systemd/files/9999991/boot-login-suspend-then-hibernate-systemd-252-2.txt)

**Comment by yuwata** [comment] 2022-11-14 06:36
Duplicate of #25356 and #25377.

**Closed as completed by yuwata** 2022-11-14 06:36 UTC
Labels: login, regression ⚠️, duplicate, sleep
