### ISSUE TITLE
SystemD needs the CoC

### ISSUE THREAD

**Issue by ForTheGreaterGood** [systemd/systemd#10198] opened 2018-09-28 16:57 UTC
On the basis of the misogyny and the vitriol by some developers within Systemd senior leadership, it is about time SystemD follows the Linux and adopts  the Code Of Conduct as presented by Ada and the contributor-covenant.org

**Comment by boucman** [comment] 2018-09-28 16:59
duplicate of #10148

**Comment by mbiebl** [comment] 2018-09-28 17:06
It's a clear trolling attempt

**Closed by mbiebl** 2018-09-28 17:06 UTC
