### ISSUE TITLE
Systemd-Cryptenroll not working on system anymore

### ISSUE THREAD

**Issue by MrSandMN** [systemd/systemd#28654] opened 2023-08-03 07:11 UTC
### systemd version the issue has been seen with

254-1-arch

### Used distribution

Arch Linux

### Linux kernel version used

Linux 6.4.7-arch1-2

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Expected behaviour you didn't see

systemd-cryptenroll successfully enrolling keys to tpm2 for luks 2 partition

### Unexpected behaviour you saw

TPM2 device supports both SHA1 and SHA256 PCR banks, but only SHA1 PCRs are valid, falling back to SHA1 bank. This reduces the security level substantially.
WARNING:esys:src/tss2-esys/api/Esys_Create.c:399:Esys_Create_Finish() Received TPM Error
ERROR:esys:src/tss2-esys/api/Esys_Create.c:134:Esys_Create() Esys Finish ErrorCode (0x00000184)
Failed to generate object in TPM: tpm:handle(1):value is out of range or is not correct for the context

### Steps to reproduce the problem

systemd-cryptenroll --tpm2-device=/dev/tpm-device --tpm2-pcrs=0+7 /dev/LUKS2-volume -> running this on the latest updates on system has stopped working.
Rolling back to the snapshot taken before the update works as intended

**Comment by mrc0mmand** [comment] 2023-08-03 08:44
Duplicate of #28655.

**Comment by ddstreet** [comment] 2023-08-03 21:04
> Duplicate of #28655.

I think this is actually a separate issue.

**Comment by medhefgo** [comment] 2023-08-03 21:14
@MrSandMN Does #28663 work for you?

**Comment by MrSandMN** [comment] 2023-08-04 04:01
Hi can some one help me understand what it is I need to do, I'm a bit lost, should i pull the systemd from this repository then patch the tpm2-util.c in src/share with the information from #28663  then build and install it manually? I'm not a developer of any kind and this would be my first time trying to follow these pages, I have tried reading through #28655 but no luck not even sure where to patch a/src/shared/tpm2-util.c b/src/shared/tpm2-util.c from #28655, i thought I could follow along but boy was I wrong.

**Comment by medhefgo** [comment] 2023-08-04 07:24
Since you're on arch: Just use [systemd-git](https://aur.archlinux.org/packages/systemd-git) from the [AUR](https://wiki.archlinux.org/title/Arch_User_Repository) to build and install the PR. Only thing you have to replace is the git url in the PKGBUILD from `git+https://github.com/systemd/systemd` to `git+https://github.com/ddstreet/systemd.git#tpm2_legacy_create_primary`.

**Comment by MrSandMN** [comment] 2023-08-04 08:10
> https://github.com/ddstreet/systemd.git#tpm2_legacy_create_primar

Hi medhefgo, im getting the following error when changing the link as you mentioned
ERROR: Unrecognized reference: tpm2_legacy_create_primary

I also tried using git+https://github.com/ddstreet/systemd/tree/tpm2_legacy_create_primary that didn't even try to download am I missing something?

**Closed as completed** 2023-08-04 09:13 UTC
Labels: bug 🐛, cryptsetup, regression ⚠️, tpm2

**Comment by MrSandMN** [comment] 2023-08-04 11:06
> Since you're on arch: Just use [systemd-git](https://aur.archlinux.org/packages/systemd-git) from the [AUR](https://wiki.archlinux.org/title/Arch_User_Repository) to build and install the PR. Only thing you have to replace is the git url in the PKGBUILD from `git+https://github.com/systemd/systemd` to `git+https://github.com/ddstreet/systemd.git#tpm2_legacy_create_primary`.

Just an update, this resolved my issue with TPM2 and Cryptenroll as well, thank you for helping me with the the aur and the PKGBUILD part @medhefgo.
