### ISSUE TITLE
No "systemctl --user --global daemon-reexec" equivalent for upgrades

### ISSUE THREAD

**Issue by anitazha** [systemd/systemd#13065] opened 2019-07-15 22:14 UTC
_I commented on #12770 but this seemed like this is worth its own issue._

We're upgrading from systemd 241 to 242. On development servers, where we primarily use user services, users are getting access denied messages:
```
Failed to start logged-in.target: Access denied
See user logs and 'systemctl --user status logged-in.target' for details.

devbox:/etc/systemd/user% systemctl --user status logged-in.target
Failed to get properties: Access denied

devbox:/etc/systemd/user% sudo systemctl --user status logged-in.target
Failed to connect to bus: Operation not permitted
```

Running `XDG_RUNTIME_DIR= systemctl --user daemon-reexec` fixes it, which leads me to believe something with the user private bus gets messed up during the upgrade. RPM install runs `systemctl daemon-reexec` as part of the install script so I think there should be an equivalent to also do this for all the user managers on a host.

**Comment by poettering** [comment] 2019-07-16 09:31
Duplicate of #12770

**Closed as completed by poettering** 2019-07-16 09:31 UTC
Labels: RFE 🎁, pid1, duplicate
