### ISSUE TITLE
IPv6 RA flood !

### ISSUE THREAD

**Issue by belahssen** [systemd/systemd#5747] opened 2017-04-17 19:48 UTC
guys i Have BIG problem how can i solve it !!
i run flood_router6 without configure nothing 
+==> Help please and give me what i shoud configure like ipv6 ? DHCP SERVER ??

**Comment by evverx** [comment] 2017-04-17 20:19
I'm not sure I understand what the issue is. Did you mean https://github.com/systemd/systemd/issues/2977?

**Comment by evverx** [comment] 2017-04-17 20:36
I've just seen https://github.com/systemd/systemd/issues/5668. I'm closing this one.

**Closed as completed by evverx** 2017-04-17 20:36 UTC
Labels: misfiled
