### ISSUE TITLE
Dependencies of unit start even if conditions aren't met

### ISSUE THREAD

**Issue by crawford** [systemd/systemd#985] opened 2015-08-18 00:01 UTC
Assume I have a unit, a.target, which depends on another unit, b.service, and has a condition which is false. If I start a.target, b.service is also started, even though the condition hasn't been met. Is this expected/optimal? Is there a way to change this behavior?

```
$ cat a.target
[Unit]
ConditionPathExists=/not/here
Requires=b.service
```

```
$ cat b.service
[Service]
ExecStart=/usr/bin/echo Hello
```

I wouldn't expect b.service to start in this scenario.

**Comment by marineam** [comment] 2015-08-18 00:23
This is the way it works by design. The condition isn't evaluated until it is time to start the service since a dependency such as b.service may be responsible for creating the /not/here path.

Some conditions aren't going to change such as virtualization or cmdline but it'd probably be weird if some conditions were evaluated early while others were late.

**Comment by crawford** [comment] 2015-08-18 00:30
Interesting. I hadn't considered the case like you described (though, I figured it must exist). I guess what I'm looking for is a conditional dependency.

**Comment by arvidjaar** [comment] 2015-08-18 03:28
@marineam What semantic condition on target has? Targets are never "started" - they just trigger other units and wait for them. According to your description condition on target is NOOP and utterly useless. 

> it'd probably be weird if some conditions were evaluated early while others were late

Well, "starting" target means evaluating its dependencies, so it is not really that weird in this case.

**Comment by poettering** [comment] 2015-08-18 08:24
@crawford well, if you had a condition check at the time of queuing (rather than at the time when starting) then things become quite undeterministic in most cases since the point where you do the condition check is not precisely timed. A good chunk of the condition checks verify system state that changes after all, and when one does them too early will fail even though they should not.

Or to say this differenty: if we really had what you are asking for then for the initial condition we'd run a ton of condition checks right at the first moment of userspace, without any ability to order or delay these checks, and I am not really sure that's desirable.

What's your usecase for this? Maybe we can find a different solution.

Generators might be a solution for you. They may be used to convert external configuration and static kernel configuration into unit files and dependencies.

**Comment by vcaputo** [comment] 2015-08-19 05:22
The specific scenario where this was desirable used `ConditionKernelCommandline`, which would have been stable from boot.  Instead we're using a generator which has to parse the cmdline.  It seemed more elegant to do this in systemd when there already exists `ConditionKernelCommandline`, but as we understand now there's no way to apply these conditions to dependencies.

**Comment by poettering** [comment] 2016-04-18 14:33
I think this one is cleared up now, let's close this. (Feel free to reopen if I misunderstood this)

**Closed as completed by poettering** 2016-04-18 14:33 UTC
Labels: needs-reporter-feedback ❓
