### ISSUE TITLE
nspawn: Failed to set up ID mapped mounts: Device or resource busy

### ISSUE THREAD

**Issue by iam-TJ** [systemd/systemd#31825] opened 2024-03-16 18:27 UTC
### systemd version the issue has been seen with

systemd 252 (252.22-1~deb12u1)

### Used distribution

Debian 12

### Linux kernel version used

6.7.2+debian+tj

### CPU architectures issue was seen on

x86_64

### Component

systemd-nspawn

### Expected behaviour you didn't see

Start an unprivileged volatile container.

### Unexpected behaviour you saw

```
systemd-nspawn  --boot --link-journal=try-guest --network-veth --volatile=yes --directory=/ -U
Spawning container sunny on /.
Press ^] three times within 1s to kill container.
Selected user namespace base 351076352 and range 65536.
Failed to set up ID mapped mounts: Device or resource busy
Short read while reading cgroup mode (0 bytes). The child is most likely dead.`
```
Also reported in #29226 but not pursued.

### Steps to reproduce the problem

`systemd-nspawn  --boot --link-journal=try-guest --network-veth --volatile=yes --directory=/ -U`

Looking at the code closely, for `-U` it appears to do the equivalent of this pseudo command sequence:
```
# [strace] 2225119 clone(child_stack=NULL, flags=CLONE_NEWNS|SIGCHLD) = 2225120
# mount commands in NEWNS pid 2225120
mount --make-rslave / 
mount --bind / /run/systemd/nspawn-root
mount -t tmpfs tmpfs /tmp/nspawn-volatile-${unique} -o mode=755,size=25%,nr_inodes=1m,uid=351076352,gid=351076352
mount --rbind /run/systemd/nspawn-root/usr on /tmp/nspawn-volatile-${unique}/usr
mount --move /tmp/nspawn-volatile-${unique} /run/systemd/nspawn-root
# [strace] 2225120 open_tree(-1, "/run/systemd/nspawn-root", OPEN_TREE_CLONE|OPEN_TREE_CLOEXEC) = 6
# [strace] 2225120 clone(child_stack=NULL, flags=CLONE_NEWUSER|SIGCHLD) = 2225121
# [strace] 2225120 openat(AT_FDCWD, "/proc/2225121/ns/user", O_RDONLY|O_NOCTTY|O_CLOEXEC <unfinished ...>
# [strace] 2225120 <... openat resumed>)           = 8
# [strace] 2225120 mount_setattr(6, "", AT_EMPTY_PATH|AT_RECURSIVE, {attr_set=MOUNT_ATTR_IDMAP, attr_clr=0, propagation=0 /* MS_??? */, userns_fd=8}, 32) = 0
umount /run/systemd/nspawn-root
# >> Failed to unmount /run/systemd/nspawn-root: Device or resource busy
```
I may be confused due to the separate mount namespace from fd==6 but at this point there are two mounts on `/run/systemd/nspawn-root/` - the first real root-fs bind and then the moved `/tmp/nspawn-volatile-${unique} ` -- which is intended to be unmounted here?

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# I've run the process with `gdb` and captured what appears to be useful information.

SourceCode/systemd/systemd/src$ cat gdb-trace-child-processes.commands
set follow-fork-mode parent
set detach-on-fork off
set schedule-multiple on

SourceCode/systemd/systemd/src$ sudo SYSTEMD_LOG_LEVEL=debug gdb --quiet --command=./gdb-trace-child-processes.commands --args systemd-nspawn  --bo
ot --link-journal=try-guest --network-veth --volatile=yes --directory=/ -U
Reading symbols from systemd-nspawn...
Reading symbols from /usr/lib/debug/.build-id/91/021fba10de7a97c0da468c155f68b4b387a410.debug...
(gdb) start
Temporary breakpoint 1 at 0xff40: file ../src/nspawn/nspawn.c, line 5913.
Starting program: /usr/bin/systemd-nspawn --boot --link-journal=try-guest --network-veth --volatile=yes --directory=/ -U
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Temporary breakpoint 1, main (argc=7, argv=0x7fffffffe3e8) at ../src/nspawn/nspawn.c:5913
warning: Source file is more recent than executable.
5913    DEFINE_MAIN_FUNCTION_WITH_POSITIVE_FAILURE(run);
(gdb) break outer_child
Breakpoint 2 at 0x55555556ee00: file ../src/nspawn/nspawn.c, line 3638.
(gdb) break remount_idmap
Breakpoint 3 at 0x7ffff7d171b0: file ../src/shared/mount-util.c, line 1101.
(gdb) c
Continuing.
Setting RLIMIT_CPU to infinity.
Setting RLIMIT_FSIZE to infinity.
Setting RLIMIT_DATA to infinity.
Setting RLIMIT_STACK to 8388608:infinity.
Setting RLIMIT_CORE to 0:infinity.
Setting RLIMIT_RSS to infinity.
Setting RLIMIT_NPROC to 127876.
Setting RLIMIT_NOFILE to 1024:524288.
Setting RLIMIT_MEMLOCK to 8388608.
Setting RLIMIT_AS to infinity.
Setting RLIMIT_LOCKS to infinity.
Setting RLIMIT_SIGPENDING to 127876.
Setting RLIMIT_MSGQUEUE to 819200.
Setting RLIMIT_NICE to 0.
Setting RLIMIT_RTPRIO to 0.
Setting RLIMIT_RTTIME to infinity.
Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Spawning container sunny on /.
Press ^] three times within 1s to kill container.
[New inferior 2 (process 2333158)]
Reading symbols from /usr/lib/debug/.build-id/42/45bcbb01fecadd5d26b293eede3dab91ee296f.debug...
Reading symbols from /usr/lib/debug/.build-id/82/ce4e6e4ef08fa58a3535f7437bd3e592db5ac0.debug...
Reading symbols from /usr/lib/debug/.build-id/ea/87e1b3daf095cd53f1f99ab34a88827eccce80.debug...
Reading symbols from /usr/lib/debug/.build-id/38/e7d4a67acf053c794b3b8094e6900b5163f37d.debug...
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Switching to Thread 0x7ffff76835c0 (LWP 2333158)]

Thread 2.1 "systemd-nspawn" hit Breakpoint 2.2, outer_child (barrier=0x7fffffffdad0, directory=0x5555555adc80 "/", dissected_image=0x0, secondary=false, pid_socket=13,
uuid_socket=15, notify_socket=17, kmsg_socket=9, rtnl_socket=11, uid_shift_socket=21, master_pty_socket=19, unified_cgroup_hierarchy_socket=23, fds=0x0, netns_fd=-1)
at ../src/nspawn/nspawn.c:3638
3638                    int netns_fd) {
(gdb) c
Continuing.
Outer child is initializing.
Mounting / (MS_REC|MS_SLAVE "")...
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.DynamicUser: Sending message: {"method":"io.systemd.UserDatabase.GetUserRecord","parameters":{"uid":351076352,"service":"io.systemd.DynamicU
ser"}}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state idle-client → awaiting-reply
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.Machine: Sending message: {"method":"io.systemd.UserDatabase.GetUserRecord","parameters":{"uid":351076352,"service":"io.systemd.Machine"}}
/run/systemd/userdb/io.systemd.Machine: Changing state idle-client → awaiting-reply
/run/systemd/userdb/io.systemd.DynamicUser: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.DynamicUser: Changing state processing-reply → idle-client
/run/systemd/userdb/io.systemd.Machine: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.Machine: Changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.Machine: Changing state processing-reply → idle-client
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.DynamicUser: Sending message: {"method":"io.systemd.UserDatabase.GetUserRecord","parameters":{"uid":351141886,"service":"io.systemd.DynamicU
ser"}}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state idle-client → awaiting-reply
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.Machine: Sending message: {"method":"io.systemd.UserDatabase.GetUserRecord","parameters":{"uid":351141886,"service":"io.systemd.Machine"}}
/run/systemd/userdb/io.systemd.Machine: Changing state idle-client → awaiting-reply
/run/systemd/userdb/io.systemd.DynamicUser: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.DynamicUser: Changing state processing-reply → idle-client
/run/systemd/userdb/io.systemd.Machine: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.Machine: Changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.Machine: Changing state processing-reply → idle-client
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.DynamicUser: Sending message: {"method":"io.systemd.UserDatabase.GetGroupRecord","parameters":{"gid":351076352,"service":"io.systemd.Dynamic
User"}}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state idle-client → awaiting-reply
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.Machine: Sending message: {"method":"io.systemd.UserDatabase.GetGroupRecord","parameters":{"gid":351076352,"service":"io.systemd.Machine"}}
/run/systemd/userdb/io.systemd.Machine: Changing state idle-client → awaiting-reply
/run/systemd/userdb/io.systemd.DynamicUser: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.DynamicUser: Changing state processing-reply → idle-client
/run/systemd/userdb/io.systemd.Machine: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.Machine: Changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.Machine: Changing state processing-reply → idle-client
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.DynamicUser: Sending message: {"method":"io.systemd.UserDatabase.GetGroupRecord","parameters":{"gid":351141886,"service":"io.systemd.Dynamic
User"}}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state idle-client → awaiting-reply
varlink: Setting state idle-client
/run/systemd/userdb/io.systemd.Machine: Sending message: {"method":"io.systemd.UserDatabase.GetGroupRecord","parameters":{"gid":351141886,"service":"io.systemd.Machine"}}
/run/systemd/userdb/io.systemd.Machine: Changing state idle-client → awaiting-reply
/run/systemd/userdb/io.systemd.DynamicUser: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.DynamicUser: Changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.DynamicUser: Changing state processing-reply → idle-client
/run/systemd/userdb/io.systemd.Machine: New incoming message: {"error":"io.systemd.UserDatabase.NoRecordFound","parameters":{}}
/run/systemd/userdb/io.systemd.Machine: Changing state awaiting-reply → processing-reply
Got lookup error: io.systemd.UserDatabase.NoRecordFound
/run/systemd/userdb/io.systemd.Machine: Changing state processing-reply → idle-client
Selected user namespace base 351076352 and range 65536.
Bind-mounting / on /run/systemd/nspawn-root (MS_BIND|MS_REC "")...
Mounting tmpfs (tmpfs) on /tmp/nspawn-volatile-JwW0L8 (MS_STRICTATIME "mode=755,size=25%,nr_inodes=1m,uid=351076352,gid=351076352")...
Bind-mounting /run/systemd/nspawn-root/usr on /tmp/nspawn-volatile-JwW0L8/usr (MS_BIND|MS_REC "")...
Moving mount /tmp/nspawn-volatile-JwW0L8 → /run/systemd/nspawn-root (MS_MOVE "")...

Thread 2.1 "systemd-nspawn" hit Breakpoint 3.1, remount_idmap (p=p@entry=0x555555591a68 "/run/systemd/nspawn-root", uid_shift=uid_shift@entry=351076352, uid_range=65536,
owner=owner@entry=4294967295, idmapping=idmapping@entry=REMOUNT_IDMAPPING_HOST_ROOT) at ../src/shared/mount-util.c:1101
warning: Source file is more recent than executable.
1101                    RemountIdmapping idmapping) {
(gdb) s
1106            assert(p);
(gdb) n
1108            if (!userns_shift_range_valid(uid_shift, uid_range))
(gdb) n
1112            mount_fd = open_tree(-1, p, OPEN_TREE_CLONE | OPEN_TREE_CLOEXEC);
(gdb) n
1113            if (mount_fd < 0)
(gdb) p mount_fd
$1 = 6
(gdb) n
1117            userns_fd = make_userns(uid_shift, uid_range, owner, idmapping);
(gdb) n
[New inferior 3 (process 2333354)]
Reading symbols from /usr/lib/debug/.build-id/91/021fba10de7a97c0da468c155f68b4b387a410.debug...
Reading symbols from /usr/lib/debug/.build-id/42/45bcbb01fecadd5d26b293eede3dab91ee296f.debug...
Reading symbols from /usr/lib/debug/.build-id/82/ce4e6e4ef08fa58a3535f7437bd3e592db5ac0.debug...
Reading symbols from /usr/lib/debug/.build-id/ea/87e1b3daf095cd53f1f99ab34a88827eccce80.debug...
Reading symbols from /usr/lib/debug/.build-id/38/e7d4a67acf053c794b3b8094e6900b5163f37d.debug...
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Successfully forked off '(sd-mkuserns)' as PID 2333354.

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
(gdb) inferior 2
[Switching to inferior 2 [process 2333158] (/usr/bin/systemd-nspawn)]
[Switching to thread 2.1 (Thread 0x7ffff76835c0 (LWP 2333158))]
#0  0x00007ffff7af2bc6 in __waitid (idtype=idtype@entry=P_PID, id=id@entry=2333354, infop=infop@entry=0x7fffffffd590, options=options@entry=4)
at ../sysdeps/unix/sysv/linux/waitid.c:29
29      ../sysdeps/unix/sysv/linux/waitid.c: No such file or directory.
(gdb) n
make_userns (idmapping=REMOUNT_IDMAPPING_HOST_ROOT, owner=4294967295, uid_range=<optimized out>, uid_shift=4294967295) at ../src/shared/mount-util.c:1090
1090            if (userns_fd < 0)
(gdb) p userns_fd
$2 = 8
(gdb) n
1053            _cleanup_free_ char *line = NULL;
(gdb) n
1052            _cleanup_close_ int userns_fd = -1;
(gdb) n
1053            _cleanup_free_ char *line = NULL;
(gdb) n
1052            _cleanup_close_ int userns_fd = -1;
(gdb) n
remount_idmap (p=p@entry=0x555555591a68 "/run/systemd/nspawn-root", uid_shift=uid_shift@entry=351076352, uid_range=<optimized out>, owner=owner@entry=4294967295,
idmapping=idmapping@entry=REMOUNT_IDMAPPING_HOST_ROOT) at ../src/shared/mount-util.c:1118
1118            if (userns_fd < 0)
(gdb) p mount_fd
$4 = 6
(gdb) p userns_fd
$5 = 8
(gdb) n
1122            if (mount_setattr(mount_fd, "", AT_EMPTY_PATH | AT_RECURSIVE,
(gdb) s
__GI_mount_setattr () at ../sysdeps/unix/syscall-template.S:117
117     ../sysdeps/unix/syscall-template.S: No such file or directory.

(gdb) n
remount_idmap (p=p@entry=0x555555591a68 "/run/systemd/nspawn-root", uid_shift=uid_shift@entry=351076352, uid_range=<optimized out>, owner=owner@entry=4294967295,
idmapping=idmapping@entry=REMOUNT_IDMAPPING_HOST_ROOT) at ../src/shared/mount-util.c:1130
1130            r = umount_verbose(LOG_DEBUG, p, UMOUNT_NOFOLLOW);
(gdb) s
umount_verbose (error_log_level=error_log_level@entry=7, what=what@entry=0x555555591a68 "/run/systemd/nspawn-root", flags=flags@entry=8) at ../src/shared/mount-util.c:700
700             assert(what);
(gdb) n
702             log_debug("Umounting %s...", what);
(gdb) n
Umounting /run/systemd/nspawn-root...
704             if (umount2(what, flags) < 0)
(gdb) s
__GI___umount2 (special_file=special_file@entry=0x555555591a68 "/run/systemd/nspawn-root", flags=flags@entry=8) at ../sysdeps/unix/sysv/linux/umount2.c:25
25      ../sysdeps/unix/sysv/linux/umount2.c: No such file or directory.
(gdb) n
umount_verbose (error_log_level=error_log_level@entry=7, what=what@entry=0x555555591a68 "/run/systemd/nspawn-root", flags=flags@entry=8) at ../src/shared/mount-util.c:705
705                     return log_full_errno(error_log_level, errno,
(gdb) n
Failed to unmount /run/systemd/nspawn-root: Device or resource busy
remount_idmap (p=p@entry=0x555555591a68 "/run/systemd/nspawn-root", uid_shift=uid_shift@entry=351076352, uid_range=<optimized out>, owner=owner@entry=4294967295,
idmapping=idmapping@entry=REMOUNT_IDMAPPING_HOST_ROOT) at ../src/shared/mount-util.c:1131
1131            if (r < 0)
```

**Comment by bluca** [comment] 2024-03-17 13:10
duplicate of https://github.com/systemd/systemd/issues/29226

**Closed as not planned by bluca** 2024-03-17 13:10 UTC
Labels: nspawn, duplicate
