### ISSUE TITLE
ProtectSystem, PrivateDevices or ProtectHome makes socket paths mismatch in Apparmor

### ISSUE THREAD

**Issue by HenrikHolst** [systemd/systemd#4774] opened 2016-11-30 15:12 UTC
### Submission type

  - [x ] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

231

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

Ubuntu 16.10

### In case of bug report: Expected behaviour you didn't see

Match of path being /run/mysqld/mysqld.sock

### In case of bug report: Unexpected behaviour you saw

audit: type=1400 audit(1480516514.245:108): apparmor="DENIED" operation="connect" info="Failed name lookup - disconnected path" error=-13 profile="/usr/bin/mda" **name="run/mysqld/mysqld.sock"** pid=15111 comm="mda" requested_mask="wr" denied_mask="wr" fsuid=0 ouid=113

### In case of bug report: Steps to reproduce the problem

Add either one of these in /lib/systemd/system/mariadb.service:

ProtectSystem=full
PrivateDevices=true
ProtectHome=true

Comment all of the three and everything works and the /run/mysqld/mysqld.sock path is correctly parsed by Apparmor but with any single one of the above stanzas the path is changed to run/mysqld/mysqld.sock in Apparmor

**Comment by poettering** [comment] 2016-11-30 16:11
Well, that's caused by path-based MACs I figure. Not sure what we can do about that. I figure this is something aa has to fix, there's nothing much we could do...

Closing this. Please contact the aa folks about this. Sorry!

**Closed as completed by poettering** 2016-11-30 16:11 UTC
Labels: not-our-bug
