### ISSUE TITLE
systemctl status for exited service does not show correct status nor which commands systemd executed

### ISSUE THREAD

**Issue by stapelberg** [systemd/systemd#4815] opened 2016-12-03 21:24 UTC
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> systemd 232
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN

### Used distribution

> Debian testing, but the issue was originally observed on CoreOS

### In case of bug report: Expected behaviour you didn't see

The `systemctl status` output does not contain any information about which commands systemd executed (no ExecStart lines), nor about the status of the unit (I expected it to be in status “exited”).

### In case of bug report: Steps to reproduce the problem

```
# cat >/etc/systemd/system/poc2.service <<'EOT'
[Unit]
Description=Fixes FORWARD firewall chain after docker starts up

[Service]
ExecStart=/bin/bash -c 'echo first | logger'
EOT

# systemctl daemon-reload

# systemctl status poc2    
● poc2.service - Fixes FORWARD firewall chain after docker starts up
   Loaded: loaded (/etc/systemd/system/poc2.service; static; vendor preset: enabled)
   Active: inactive (dead)

# systemctl start poc2 

# systemctl status poc2
● poc2.service - Fixes FORWARD firewall chain after docker starts up
   Loaded: loaded (/etc/systemd/system/poc2.service; static; vendor preset: enabled)
   Active: inactive (dead)

Dec 03 22:18:40 midna systemd[1]: Started Fixes FORWARD firewall chain after docker starts up.
```

**Comment by poettering** [comment] 2016-12-05 23:54
systemd GC's services that exited cleanly and that are not referenced by anything anymore. That's by design. Specifically, it will GC for which all of the following applies

* isn't running
* never ran OR ran but exited cleanly
* does not have any job queued
* is not in a failed state
* is not referenced by any other unit
* is not "perpetual" (these are a very special few units, such as `-.mount`, `init.scope` and a few others. Units that are *always* up, and can never be downed)
* unit is being reffed by bus clients via the Ref()/Unref() calls

There's currently no nice way to temporarily add a reference to a unit to make sure it isn't cleaned up from the shell (though we probably could add "systemctl ref" or so for this...). For `Type=oneshot` there's `RemainAfterExit=yes` however, which permits having services around that have no running processes, but this is in many ways very different from adding a ref.

(In current systemd versions there's "systemctl start --wait …" btw, which permits starting a unit and then waiting until it exits and reporting some exit status information, maybe that's all you need?)

Either way, the behaviour you see is by design, and not a bug. Closing hence. Hope that makes sense!

**Closed as completed by poettering** 2016-12-05 23:54 UTC
Labels: pid1, not-a-bug
