### ISSUE TITLE
242: meson shows wrong DNSSEC and DNS-over-TLS mode after detection

### ISSUE THREAD

**Issue by kloczek** [systemd/systemd#12284] opened 2019-04-11 19:10 UTC
I'm using list on meson options:

<pre>+ /usr/bin/meson --buildtype=plain --prefix=/usr --libdir=/usr/lib64
--libexecdir=/usr/libexec --bindir=/usr/bin --sbindir=/usr/sbin
--includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man
--infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc
--localstatedir=/var --sharedstatedir=/var/lib --wrap-mode=nodownload
--auto-features=enabled .  x86_64-redhat-linux-gnu -D acl=true -D
apparmor=false -D audit=true -D blkid=true -D bzip2=false -D
default-locale=C -D default-kill-user-processes=false -D dev-kvm-mode=0666
-D dns-over-tls=openssl -D efi=true -D elfutils=true -D gcrypt=false -D
gnu-efi=true -D gnutls=false -D gshadow=true -D hwdb=true -D ima=true -D
install-tests=true -D kmod=true -D libcryptsetup=true -D libcurl=true -D
libidn2=true -D libiptc=true -D lz4=true -D microhttpd=false -D
nobody-group=nobody -D nobody-user=nobody -D
&apos;ntp-servers=0.fedora.pool.ntp.org 1.fedora.pool.ntp.org
2.fedora.pool.ntp.org 3.fedora.pool.ntp.org&apos; -D openssl=true -D pam=true -D
polkit=true -D qrencode=true -D rc-local=/etc/rc.d/rc.local -D seccomp=true
-D selinux=true -D smack=false -D split-bin=true -D split-usr=false -D
sysusers=true -D sysvinit-path=/etc/rc.d/init.d -D tests=unsafe -D tpm=true
-D tty-gid=5 -D users-gid=100 -D version-tag=v242-2.fc31 -D xkbcommon=true
-D xz=true -D zlib=false
</pre>
And after detection meson shows:
<pre><b>Message:</b> systemd 242
         split /usr:                        false
         split bin-sbin:                    true
         prefix directory:                  /usr
         rootprefix directory:              /usr
         sysconf directory:                 /etc
         include directory:                 /usr/include
         lib directory:                     /usr/lib64
         rootlib directory:                 /usr/lib64
         SysV init scripts:                 /etc/rc.d/init.d
         SysV rc?.d directories:            /etc/rc.d
         PAM modules directory:             /usr/lib64/security
         PAM configuration directory:       /etc/pam.d
         RPM macros directory:              /usr/lib/rpm/macros.d
         modprobe.d directory:              /usr/lib/modprobe.d
         D-Bus policy directory:            /usr/share/dbus-1/system.d
         D-Bus session directory:           /usr/share/dbus-1/services
         D-Bus system directory:            /usr/share/dbus-1/system-services
         bash completions directory:        /usr/share/bash-completion/completions
         zsh completions directory:         /usr/share/zsh/site-functions
         extra start script:                /etc/rc.d/rc.local
         extra stop script:                 /usr/sbin/halt.local
         debug shell:                       /bin/sh @ /dev/tty9
         TTY GID:                           5
         users GID:                         100
         maximum system UID:                999
         maximum system GID:                999
         minimum dynamic UID:               61184
         maximum dynamic UID:               65519
         minimum container UID base:        524288
         maximum container UID base:        1878982656
         /dev/kvm access mode:              0666
         render group access mode:          0666
         certificate root directory:        /etc/ssl
         support URL:                       https://lists.freedesktop.org/mailman/listinfo/systemd-devel
         nobody user name:                  nobody
         nobody group name:                 nobody
         fallback hostname:                 localhost
         symbolic gateway hostnames:        _gateway
<b>         default DNSSEC mode:               no
         default DNS-over-TLS mode:         no</b>
         default cgroup hierarchy:          hybrid
         default net.naming-scheme setting: latest
         default KillUserProcesses setting: false
         default locale:                    C
         default DNS servers:               1.1.1.1
                                            8.8.8.8
                                            1.0.0.1
                                            8.8.4.4
                                            2606:4700:4700::1111
                                            2001:4860:4860::8888
                                            2606:4700:4700::1001
                                            2001:4860:4860::8844
         default NTP servers:               0.fedora.pool.ntp.org
                                            1.fedora.pool.ntp.org
                                            2.fedora.pool.ntp.org
                                            3.fedora.pool.ntp.org
         time epoch:                        1555000116 (2019-04-11T16:28:36+00:00)
         static libsystemd:                 false
         static libudev:                    false
         efi arch:                          x86_64
         EFI machine type:                  x64
         EFI CC                             gcc
         EFI lib directory:                 /usr/lib64
         EFI lds directory:                 /usr/lib64/gnuefi
         EFI include directory:             /usr/include/efi

         enabled features: libcryptsetup, PAM, AUDIT, IMA, SELinux, SECCOMP,
xz, lz4, ACL, qrencode, openssl, libcurl, idn, libidn2, libiptc, elfutils,
binfmt, vconsole, quotacheck, tmpfiles, environment.d, sysusers, firstboot,
randomseed, backlight, rfkill, logind, machined, portabled, hostnamed,
timedated, timesyncd, localed, networkd, resolve, <b>DNS-over-TLS(openssl),</b>
coredump, polkit, efi, gnu-efi, kmod, xkbcommon, pcre2, blkid, dbus, glib,
nss-myhostname, nss-mymachines, nss-resolve, nss-systemd, hwdb, tpm, man
pages, man page indices, SysV compat, utmp, ldconfig, hibernate, adm group,
wheel group, gshadow, link-udev-shared, link-systemctl-shared

         disabled features: AppArmor, SMACK, zlib, bzip2, gcrypt,
microhttpd, gnutls, libidn, importd, <b>DNS-over-TLS(gnutls)</b>, legacy pkla, html
pages, debug hashmap, debug mmap cache, debug siphash, debug udev, valgrind,
trace logging
       
</pre>

**Comment by yuwata** [comment] 2019-04-12 01:09
- DNSSEC cannot be enabled if gcrypt is disabled.
- The default DNS over TLS mode is 'no', so if you want to change the default setting, please also specify `-D default-dns-over-tls=opportunistic`.

Conclusion: this is not a bug. Let's close this.

**Closed as completed by yuwata** 2019-04-12 01:09 UTC
Labels: not-a-bug, meson
