### ISSUE TITLE
RFE: Add support for systemctl check-config <service>

### ISSUE THREAD

**Issue by damon-atkins** [systemd/systemd#3619] opened 2016-06-28 13:22 UTC
### Submission type
- [ ] Bug report
- [X ] Request for enhancement (RFE)
### systemd version the issue has been seen with

All Please.
    Being able to perform configuration file syntax checks
e.g.
 systemctl check-config dhcpd

Should return true if service does not support running a configuration check and true if the configuration has no errors/issues.
Otherwise false

Some services have ways to check configuration files, some don't but it would be nice if their was a standard way to request a check.

**Comment by poettering** [comment] 2016-06-28 18:12
I am not really convinced this has a place in systemd since that's nothing generic that systemd could make use of for its service lifecycle. We get a lot of requests like this that ask for additional verbs to be added to systemctl for specific services even though systemd couldn't make any use of that verb on its own and it's highly specific to the application in question. In those cases like in this case I am really not too convinced this would be a good idea to add and our usual suggestion is to add a service-specific tool like "apachectl" or so that implements additional service-specific verbs.

**Comment by damon-atkins** [comment] 2016-06-29 13:47
SystemD allows starting and stopping of the service,  many services also allow syntax checking in fact some init scripts have arguments for syntax checking of configuration files.

It might be the case that systemd does not call it, but systemctl calls the command direct.

To place the existing features of init scripts.

This allows a stand for syntax checking of a configuration file across all the platforms systemsd runs on.
Just like it provides the standard for start, restart, stop. In order to start,stop,restart it needs to know were the binary is and the configuration file, if the configuration file is passed as a command line argument.

Hence its not that much of an extention for systemctl /systemd to run a syntax check against a command.

Effectively allowing  
systemctl check-config dhcpd && systemctl restart dhcpd rather than the service starting and complaining about a syntax error and exiting.

Making services a bit more fault tolerant.

**Comment by poettering** [comment] 2016-07-22 21:37
Duplicate of #3656. Closing.

**Closed as completed by poettering** 2016-07-22 21:37 UTC
Labels: RFE 🎁, pid1, duplicate

**Comment by damon-atkins** [comment] 2016-07-24 13:14
Can not see how these are duplicates.    It seems #3656 is asking for a lot more flexibility  which I assume would be a lot more effort.

**Comment by zabarabab** [comment] 2021-07-31 08:46
Currently every admin has to find out how to check the syntax of every single service he wants to run. That's a waste of lifetime. 

If this feature is implemented via #3656, it's important that the name of this action is `check-config` or `syntax-check` for every service. 

> I am not really convinced this has a place in systemd since that's nothing generic that systemd could make use of for its service lifecycle.

In this regard it is similar to `Documentation=` in [systemd.unit(5)](https://github.com/systemd/systemd/blob/e3709627e64ddf5d58aaf7c0bab08fda9fd7eb26/man/systemd.unit.xml#L581)

**Comment by damon-atkins** [comment] 2021-08-06 05:15
@poettering cloud you please re-open this.
