### ISSUE TITLE
Systemd-coredump service file not available

### ISSUE THREAD

**Issue by lorediana** [systemd/systemd#18647] opened 2021-02-17 08:56 UTC
Systemd-coredump does not work even if all the configuration files are installed. Though systemd-coredump@.service is nowhere to be found, only the systemd-coredump@.service.in. What is the meaning of the systemd-coredump@.service.in file? Do you know what else should I check to see why the coredumps are not generated? Thank you!

**Comment by mrc0mmand** [comment] 2021-02-17 09:38
Please fill in the original [issue template](https://github.com/systemd/systemd/blob/main/.github/ISSUE_TEMPLATE/Bug_report.md), since we don't know anything about your setup (OS, systemd version, etc.). Right now, there's nothing actionable for us here.

**Comment by Diana-Lorena** [comment] 2021-02-17 10:55
Sorry, The systemd version is 229-4ubuntu21.29 and the kernel version is 4.15.0-133-generic. The usecase was to kill a process and then check for coredumps, and there is none. Is this enough info?

**Comment by bluca** [comment] 2021-02-17 12:29
> Though systemd-coredump@.service is nowhere to be found, only the systemd-coredump@.service.in. 

This sounds like a (worrying) build problem in the systemd package. Have you reported this to your distribution maintainer?

**Comment by mbiebl** [comment] 2021-02-17 12:32
`apt install systemd-coredump`

**Comment by mbiebl** [comment] 2021-02-17 12:36
https://launchpad.net/ubuntu/+archive/primary/+files/systemd-coredump_229-4ubuntu21.29_amd64.deb looks fine to me. Have you unpacked the src package and tried to manually copy the service file?

**Comment by Diana-Lorena** [comment] 2021-02-17 12:54
@mbiebl Apparently the service file can be found in the release folder, that goes on target after compilation. But not in the source folder (there is only the .in service file). I will try as you said.

**Comment by mbiebl** [comment] 2021-02-18 17:46
Since I'm pretty sure this is neithe an upstream nor downstream issue and the problem is solved by installing the systemd-coredump package, I'm closing this bug report.

**Closed as completed** 2021-02-18 17:46 UTC
Labels: needs-reporter-feedback ❓, not-a-bug
