### ISSUE TITLE
systemd 249.4 don't configure network interface

### ISSUE THREAD

**Issue by dieterferdinand** [systemd/systemd#21022] opened 2021-10-16 12:29 UTC
hello,
i have a big problem with the network-config and systemd-networkd. on my new installed gentoo system, i want to use it for my network-config, but after the system is ready, i have no network.

i make two configs, one for a dummy device with ip-adresses for source-routing and one for the lan-interface. the dummy-device is setup, but the lan-device is down. i can configure it with ifconfig or ip without problems. i can also use dhclient to aktivate this interface. but with networkd nothing will work.
i have the same problem on a bananapi-r2. i try it with networkd, but nothing  happens, all other programs work fine. i don't know the systemd-version of this system (is offline at the moment).

i have a second problem with networkd. if i setup interface that networkd can use it, some settings are not aktivated, because the interface need some time before packages can be sended and received, so routes are not set. i must restart networkd some times.

i think, that this problem not happens on all hardware. i have it tried on an older lenovo-notebook with a realtek gigabit lan-interface.

if i use ifconfig/ip/dhclient to setup the interface, it need more then 2 second to get ready and then some time, before i can setup the gateways. i use it with dhcp.

i like it to use networkd, because it can make all settings i need. but on this system i must write my own script to setup the network-config. i use a complex network-configuration (more then one default gw, source routing, vlan) and it is easy to make this config with networkd, if it works. my new script is easy to use too and i insert some checks (with timeout), to get save, that i can make all settings which need a functional network connection.

last time i use it with systemd 248.3 and a D-Link DGE-528T Gigabit Ethernet Adapter which works fine.

goodby

**Comment by yuwata** [comment] 2021-10-18 05:57
First of all, please follow the template of the issue, at least, fill all information which the template request.
Especially, clarify which interface has problem, and what kind of configs are not set to the interface.

And then, please provide,
- .network, .netdev and .link files relevant to your issue.
- debugging logs of networkd, which can be generated by creating the following drop-in by using `systemctl edit systemd-networkd.service`:
```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

Sorry, but unfortunately, I have nothing to do without such information.

**Comment by dieterferdinand** [comment] 2021-10-30 20:04
hello,
the first boot today with the internal lan-device is ok, the second boot with the usb-device not. the route tables are not set. the config for both is the same, i have only changed the ip-address.

[networkd.log](https://github.com/systemd/systemd/files/7447525/networkd.log)

goodby

**Comment by yuwata** [comment] 2021-11-30 07:04
Still the issue is not clarified... Closing.

Feel free to request to reopen the page, when you provide the information I requested in https://github.com/systemd/systemd/issues/21022#issuecomment-945388327.

**Closed as completed by yuwata** 2021-11-30 07:04 UTC
Labels: network, needs-reporter-feedback ❓
