### ISSUE TITLE
Inconsistent network configuration behaviour compared to systemd units

### ISSUE THREAD

**Issue by lattwood** [systemd/systemd#3964] opened 2016-08-15 14:30 UTC
### Submission type
- [x] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

```
$ systemctl --version
systemd 225
-PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS -ACL +XZ -LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN
```
### Used distribution

```
$ uname -a
Linux ip-10-0-21-52.ec2.internal 4.5.0-coreos-r1 #2 SMP Tue May 24 17:45:36 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux
$ cat /etc/motd
CoreOS beta (1010.4.0)
```
### Expected behaviour you didn't see

I expected the merging behaviour systemd has for drop-in unit augmentations to also apply to network configuration.

I expected to be able to create a file named  `/run/systemd/network/dnsmasq.network` with the following contents, and have it globally augment the DNS configuration of the system.

```
[Network]
DNS=127.0.0.1
Domains=ec2.internal
```
### Unexpected behaviour you saw

It works until your DHCP leases expire, at which point a renewal doesn't occur. I suspect static networking configuration may be affected by this as well.
### Steps to reproduce the problem

```
$ echo "[Network]\nDNS=127.0.0.1\nDomains=ec2.internal" | sudo tee -a /run/systemd/network/dnsmasq.network
$ sudo systemctl restart systemd-networkd
$ $(/bin/sh -c "secs=`ip a ls | grep valid_lft | grep -v forever | awk '{print $2}'`; echo \${secs%sec}")
$ ping -c1 google.com || echo "no more networking!"
```
### Workaround (for CoreOS)

Include the contents of `/lib/systemd/network/zz-default.network` in `dnsmasq.service`, so the drop-in unit now resembles...

```
[Network]
DHCP=yes
DNS=127.0.0.1

[DHCP]
UseMTU=true
UseDomains=true
```

**Comment by evverx** [comment] 2016-08-15 17:09
Duplicate of https://github.com/systemd/systemd/issues/3655

**Closed as completed by evverx** 2016-08-15 17:09 UTC
Labels: network, duplicate
