### ISSUE TITLE
LZ4 "expected to fail" test passes

### ISSUE THREAD

**Issue by cdown** [systemd/systemd#10560] opened 2018-10-29 11:59 UTC
**systemd version the issue has been seen with**
> HEAD

**Used distribution**
 > Arch Linux

This code in test-compress.c consistently fails for me (ie. the return code from `LZ4_decompress_safe_partial` returns something positive).

```
        /* We expect this to fail, because that's how current lz4 works. If this
         * call succeeds, then lz4 has been fixed, and we need to change our code.
         */
        r = LZ4_decompress_safe_partial(buf, huge,
                                        compressed,
                                        12, HUGE_SIZE-1);
        assert_se(r < 0);
```

I won't pretend to understand why this is supposed to fail, but I figured you'd appreciate me reporting it :-)

This is with lz4 1.8.3, specifically lz4 1:1.8.3-1 as packaged by Arch Linux.

**Comment by cdown** [comment] 2018-10-29 12:02
Cc @keszybz who seems to have written this code

**Comment by poettering** [comment] 2018-10-29 12:09
Duplicate of #10259

**Closed as completed by poettering** 2018-10-29 12:09 UTC
Labels: tests, duplicate
