### ISSUE TITLE
resolver: all resources types are masked by /etc/hosts

### ISSUE THREAD

**Issue by samueltardieu** [systemd/systemd#2667] opened 2016-02-19 13:07 UTC
systemd 229 on ArchLinux

In my /etc/hosts, I have

```
10.8.0.1        rfc1149.net
```

because I want my machine to use a tunnel (on 10.8.0.1) when connecting to host rfc1149.net

However, it seems that systemd resolver masks all resource types instead of just masking `A` resources in this case:

``` bash
%  systemd-resolve rfc1149.net -t a
rfc1149.net. IN A     10.8.0.1

-- Information acquired via protocol DNS in 1.1ms.
-- Data is authenticated: yes

% systemd-resolve rfc1149.net -t soa
rfc1149.net: resolve call failed: Name 'rfc1149.net' does not have any RR of the requested type
```

**Comment by poettering** [comment] 2016-02-19 15:27
Yeah, we consider /etc/hosts authoritative, and override the listed domains in full. Can you make a good case why you think that behaviour isn't right?

**Comment by samueltardieu** [comment] 2016-02-19 17:59
I thought this would prevent my SSH client (which runs with option `VerifyHostKeyDNS yes`) from retrieving `SSHFP` records for `rfc1149.net`, but it looks like it can do this just fine (despite my `nsswitch.conf` containing `files resolve myhostname mymachines`).

If this is expected, the issue is moot indeed, I can live with resorting to `dig +dnssec` instead of `systemd-resolve`.

**Comment by poettering** [comment] 2016-02-23 11:55
well, ssh doesn't use resolved's DNS RR resolving APIs, hence it doesn't really care what resolved returns.

But yeah, I'd say it is definitely intended behaviour that /etc/hosts overrides a domain in full, and doesn't result in "merged" domains from different sources.

**Closed as completed by poettering** 2016-02-23 11:55 UTC
Labels: resolve
