### ISSUE TITLE
Specifiers do not expand in systemd-run directives.

### ISSUE THREAD

**Issue by bl33pbl0p** [systemd/systemd#7868] opened 2018-01-12 17:08 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

236

### Used distribution

Exherbo Linux

### In case of bug report: Expected behaviour you didn't see

delta ~ $ systemd-run -p ExecStartPre=/bin/echo\ %n -t /usr/bin/echo
Running as unit: run-u6891.service
Press ^] three times within 1s to disconnect TTY.
run-u6891.service

### In case of bug report: Unexpected behaviour you saw

delta ~ $ systemd-run -p ExecStartPre=/bin/echo\ %n -t /usr/bin/echo
Running as unit: run-u6891.service
Press ^] three times within 1s to disconnect TTY.
%n

### In case of bug report: Steps to reproduce the problem

Use unit specifiers documented in `systemd.unit` with systemd-run as shown above.

**Comment by yuwata** [comment] 2018-01-13 14:50
duplicate of #5699.

**Closed as completed by yuwata** 2018-01-13 14:50 UTC
Labels: run, duplicate
