### ISSUE TITLE
systemd-resolved reply depends on previous queries / does not reply directly to an A query if DNAME is involved

### ISSUE THREAD

**Issue by dtardon** [systemd/systemd#19219] opened 2021-04-06 12:44 UTC
**systemd version the issue has been seen with**
 > 248

**Used distribution**
 > Fedora 28

**Linux kernel version used** (`uname -a`)

 > `Linux localhost.localdomain 5.0.16-100.fc28.x86_64 #1 SMP Tue May 14 18:22:28   UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > `dig hrz.uni-bonn.de @127.0.0.53 A` should always respond with an A record of hrz.uni-bonn.de .

> `;; ANSWER SECTION:`
> `hrz.uni-bonn.de.        86400   IN      A       131.220.14.100`

**Unexpected behaviour you saw**
 > systemd-resolved responds with an A record of rhrz.uni-bonn.de and a DNAME entry instead of an A record for hrz.uni-bonn.de .

> `;; ANSWER SECTION:`
>`hrz.uni-bonn.de.        7167    IN      DNAME   rhrz.uni-bonn.de.`
> `rhrz.uni-bonn.de.       7163    IN      A       131.220.14.100`

**Steps to reproduce the problem**
 > `resolvectl flush-caches`
> `dig rhrz.uni-bonn.de @127.0.0.53 A`
> `dig hrz.uni-bonn.de @127.0.0.53 DNAME`
>`dig hrz.uni-bonn.de @127.0.0.53 A`

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```
**Note**
I'm just a messenger here. This was originally reported with v239 on CentOS 8 as https://bugzilla.redhat.com/show_bug.cgi?id=1823446 .

**Comment by poettering** [comment] 2021-04-07 12:16
hmpf, the server is broken. If you ask for A it returns A. If you ask for DNAME it returns a DNAME. THis is not allowed by RFCs. A DNAME and CNAME applies to domain fully, regarldess of type. They should fix that.

That said, we should handle this better, since the brokeness appears to be common. 

Duplicate of #16913, where this is also requested.

**Closed as completed by poettering** 2021-04-07 12:16 UTC
Labels: resolve, duplicate

**Comment by olifre** [comment] 2021-04-07 12:53
> They should fix that. (i.e. it should have returned DNAME when being asked for A, too)

Can you elaborate which DNS server is broken? I can for sure report this to the admins and determine the implementation they use (and take it upstream there), but I can't reproduce what you describe for the example provided in this issue:
```
# dig +short hrz.uni-bonn.de NS
...
nic.rhrz.uni-bonn.de.
...
# dig nic.hrz.uni-bonn.de A @nic.hrz.uni-bonn.de
...
;; ANSWER SECTION:
hrz.uni-bonn.de.        86400   IN      DNAME   rhrz.uni-bonn.de.
nic.hrz.uni-bonn.de.    86400   IN      CNAME   nic.rhrz.uni-bonn.de.
nic.rhrz.uni-bonn.de.   86400   IN      A       131.220.16.220
...
```
i.e. I get the `DNAME` and `A` record in the answer section as required when asking for any descendant of the `DNAME` node. In case you refer to `hrz.uni-bonn.de` itself, querying for the `A` record of that should not return the `DNAME` according to [rfc6672, table 1](https://tools.ietf.org/html/rfc6672#ref-0), since `DNAME` substitution only applies to descendants and not the node to which the `DNAME` itself is attached.
If there's a newer RFC I have missed replacing this, please point me to it.

**Comment by olifre** [comment] 2021-04-21 15:40
@poettering Sorry for bumping this question, but since I'd love to take the brokenness you mention to the DNS server upstream so they can fix it for the future, it would be helpful to get further input on which brokenness you refer to (I'm probably interpreting the RFCs in a wrong way?). 

Or, rephrased, I don't understand what exactly you mean by:
> (i.e. it should have returned DNAME when being asked for A, too)

The way I interpret  [rfc6672, table 1](https://tools.ietf.org/html/rfc6672#ref-0), this should only be done for descendants (and this is what the server seems to do), but not for the domain itself, which according to the footnote of that table should only respond with the `DNAME` for `QTYPE=DNAME`, but not for other `QTYPE` such as `A`.

**Comment by hexchain** [comment] 2021-07-18 18:05
IMHO this is probably not the same as #16913. `resolved` should not follow DNAME for the owner name, regardless of whether it is returned as an answer. The "unexpected behavior" in the original issue clearly shows a problem.

DNAME isn't exclusive and only affects subdomains. [RFC 6672#2.3](https://datatracker.ietf.org/doc/html/rfc6672#section-2.3) indicates that "the owner name of a DNAME is not redirected itself" and "the domain name that owns a DNAME record is allowed to have other resource record types at that domain name".

Also, according to [RFC 6672#3.4.1](https://datatracker.ietf.org/doc/html/rfc6672#section-3.4.1), 4A, when the response answers the question (in this case there is a type A RR of `hrz.uni-bonn.de` in the reply), it should be returned back to the client, suggesting that DNAME chasing should not happen.

However, the authoritative server at `nic.rhrz.uni-bonn.de` doesn't seem to return DNAME for A queries to `hrz.uni-bonn.de` anymore, so I cannot verify the behavior of the current `resolved`.

**Comment by olifre** [comment] 2021-07-18 18:14
> However, the authoritative server at `nic.rhrz.uni-bonn.de` doesn't seem to return DNAME for A queries to `hrz.uni-bonn.de` anymore, so I cannot verify the behavior of the current `resolved`.

I believe it never did — the problem is that the sequence:
```
resolvectl flush-caches
dig rhrz.uni-bonn.de @127.0.0.53 A
dig hrz.uni-bonn.de @127.0.0.53 DNAME
dig hrz.uni-bonn.de @127.0.0.53 A
```
causes `resolved` to return a `DNAME` when being asked for an A record, forcing the client to folllow the DNAME to understand how the reply answers the actual question:
```
dig hrz.uni-bonn.de @127.0.0.53 A
;; ANSWER SECTION:
hrz.uni-bonn.de.        7106    IN      DNAME   rhrz.uni-bonn.de.
rhrz.uni-bonn.de.       7106    IN      A       131.220.14.100
```
The authoritative server does not respond this way:
```
dig hrz.uni-bonn.de A @nic.hrz.uni-bonn.de
hrz.uni-bonn.de.        86400   IN      A       131.220.14.100
```
`resolved`, however, does not reply this way when the cache is already filled by the sequence of commands mentioned in the original report (and also repeated above).

**Comment by hexchain** [comment] 2021-07-19 03:48
> the problem is that the sequence

Yes, I can reproduce this now. Then I believe the authoritative server is behaving correctly and `resolved` is violating the standard here.

@poettering Can we reopen this?
