### ISSUE TITLE
Fix rotation support for HP EliteBook 820 G1

### ISSUE THREAD

**Issue by jtsagata** [systemd/systemd#13463] opened 2019-09-03 17:54 UTC
**Is your feature request related to a problem? Please describe.**
HP EliteBook 820 G1 sensor give reversed rotations

**Describe the solution you'd like**
A Fix is
```
sensor:modalias:platform:lis3lv02d:dmi:*svn*Hewlett-Packard*:*
  ACCEL_MOUNT_MATRIX=-1, 0, 0; 0, 1, 0; 0, 0, 1
```
 a line like 
```
sensor:modalias:platform:lis3lv02d:dmi:*svnHP:pnHPEliteBook820G1*
```
seems that is not working 

sudo dmidecode| grep HP
Product Name: HP EliteBook 820 G1

**Comment by poettering** [comment] 2019-11-04 10:31
please provide a PR for this.

/cc @hadess

**Comment by hadess** [comment] 2019-11-04 22:41
Duplicate of https://github.com/systemd/systemd/issues/13543, fixed in https://github.com/systemd/systemd/pull/13545

**Closed as completed by hadess** 2019-11-04 22:41 UTC
Labels: hwdb, already-fixed
