### ISSUE TITLE
RFE provide systemd-boot api via d-bus

### ISSUE THREAD

**Issue by soloturn** [systemd/systemd#26397] opened 2023-02-11 06:26 UTC
### Component

systemd-boot

### Is your feature request related to a problem? Please describe

in gnome there was a discussion to offer a GUI to select which operating system to boot next, on selecting reboot:
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6358

systemd-boot would have this feature, but has it not accessible via an API. d-bus was one of the desired options mentioned, but any API which avoids spawning CLI and parsing output would be helpful.

**Comment by medhefgo** [comment] 2023-02-11 09:39
`bootctl list --json=short` will give you what you want until somebody bothers to provide a real API.

**Comment by medhefgo** [comment] 2023-02-11 09:40
Duplicate of #11221

**Closed as not planned by medhefgo** 2023-02-11 09:40 UTC
Labels: RFE 🎁

**Comment by poettering** [comment] 2023-02-11 12:27
Logind has apis for selecting what to boot into next, what else do you need?

**Comment by medhefgo** [comment] 2023-02-11 12:44
> Logind has apis for selecting what to boot into next, what else do you need?

Huh. From a quick look that api fails to provide user-friendly strings for the boot entries.

**Comment by cmurf** [comment] 2023-02-15 15:40
> `bootctl list --json=short` will give you what you want until somebody bothers to provide a real API.

Hmm, this returns nothing on my UEFI system using GRUB. Does bootctl list require sd-boot to report  either the OSLoaders found on the ESP, or the NVRAM boot entries that point to OSLoaders? Since NVRAM boot entries can become stale, it'd be useful to have a way of listing both NVRAM entries and ESP OSLoaders, to check if the NVRAM entry is a dead end or not.

**Comment by poettering** [comment] 2023-02-15 16:27
> Hmm, this returns nothing on my UEFI system using GRUB. Does bootctl list require sd-boot to report either the OSLoaders found on the ESP, or the NVRAM boot entries that point to OSLoaders? Since NVRAM boot entries can become stale, it'd be useful to have a way of listing both NVRAM entries and ESP OSLoaders, to check if the NVRAM entry is a dead end or not.

No, it requires access to the ESP and XBOOTLDR, and look for Type `#1` and Type `#2` entries there.

To my knowledge grub/fedora chooses some private partition setup, not matching the spec, hence even though it might generate supposedly valid type `#1` entries these days (so i hear) there's no way to find them.
