### ISSUE TITLE
Two units with same StateDirectory (and DynamicUser=1) step on each other

### ISSUE THREAD

**Issue by bl33pbl0p** [systemd/systemd#8093] opened 2018-02-04 17:55 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

236

### Used distribution

Exherbo Linux

### In case of bug report: Expected behaviour you didn't see

systemd denies execution of a unit which has the same StateDirectory as to that of a running unit.

### In case of bug report: Unexpected behaviour you saw
```
[root@delta] ~ # systemd-run -p DynamicUser=1 -p StateDirectory=foo sleep 10000
Running as unit: run-rb1cbdb613f204e06af6885fc957669f8.service
[root@delta] ~ # ls -lha /var/lib/private/
total 4.0K
drwx------  4 root                root                  32 Feb  4 12:18 .
drwxr-xr-x 27 root                root                4.0K Feb  4 12:18 ..
drwxr-xr-x  2 _du6ece9305e5e8f130 _du6ece9305e5e8f130    6 Feb  4 12:18 foo
drwxr-xr-x  3 root                root                  22 Jan  8 21:40 systemd
[root@delta] ~ # systemd-run -p DynamicUser=1 -p StateDirectory=foo sleep 10000
Running as unit: run-r84474b0c8b13422eb8e5b4722fee2001.service
[root@delta] ~ # ls -lha /var/lib/private/
total 4.0K
drwx------  4 root                root                  32 Feb  4 12:18 .
drwxr-xr-x 27 root                root                4.0K Feb  4 12:18 ..
drwxr-xr-x  2 _du4987feb90486f6e9 _du4987feb90486f6e9    6 Feb  4 12:18 foo
drwxr-xr-x  3 root                root                  22 Jan  8 21:40 systemd
[root@delta] ~ # 
```

### In case of bug report: Steps to reproduce the problem

As described above, the ownership for the StateDirectory= of a running unit is changed, this might cause problems because the running process may not be able to create or write to files inside the state directory. Instead, it would be much better to not allow the loading of a unit if the StateDirectory= is already owned by a running unit. (should be allowed if no active unit has ownership on it).

Ofcourse, any other units invoked with the same directives would also hold ownership and the running units might be caught into issues. It's not about just two units.

**Comment by yuwata** [comment] 2018-02-05 05:34
Duplicate of #7090. Possibly related to #7253.

**Comment by yuwata** [comment] 2018-02-05 05:35
(If you do not think this is duplicated, then please reopen this. Thank you.)

**Closed as completed by yuwata** 2018-02-05 05:35 UTC
Labels: pid1, duplicate

**Comment by bl33pbl0p** [comment] 2018-02-05 06:20
Indeed.
