### ISSUE TITLE
redis-server fails with systemd emitting 'Too many levels of symbolic links'

### ISSUE THREAD

**Issue by karolyi** [systemd/systemd#6318] opened 2017-07-10 09:26 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

`232-21ubuntu5`

### Used distribution

ubuntu 17.04

### In case of bug report: Expected behaviour you didn't see

redis-server should start with its factory configuration

### In case of bug report: Unexpected behaviour you saw

`journalctl -xe` says:
```
redis-server.service: Failed at step NAMESPACE spawning /bin/run-parts: Too many levels of symbolic links
redis-server.service: Failed at step NAMESPACE spawning /usr/bin/redis-server: Too many levels of symbolic links
```

### In case of bug report: Steps to reproduce the problem

just try to install redis-server on 17.01

**Comment by poettering** [comment] 2017-07-10 09:54
What is the precise contents of your `rdis-service.service` unit file? (i.e. the output of `systemctl cat rdis-service.service`).

Also, do you have any non-standard symlinks in place, for example a symlink from /tmp to /var/tmp or vice versa or so?

**Comment by karolyi** [comment] 2017-07-10 10:07
```ini
[Unit]
Description=Advanced key-value store
After=network.target
Documentation=http://redis.io/documentation, man:redis-server(1)

[Service]
Type=forking
ExecStart=/usr/bin/redis-server /etc/redis/redis.conf
PIDFile=/var/run/redis/redis-server.pid
TimeoutStopSec=0
Restart=always
User=redis
Group=redis

ExecStartPre=-/bin/run-parts --verbose /etc/redis/redis-server.pre-up.d
ExecStartPost=-/bin/run-parts --verbose /etc/redis/redis-server.post-up.d
ExecStop=-/bin/run-parts --verbose /etc/redis/redis-server.pre-down.d
ExecStop=/bin/kill -s TERM $MAINPID
ExecStopPost=-/bin/run-parts --verbose /etc/redis/redis-server.post-down.d

PrivateTmp=yes
LimitNOFILE=65535
PrivateDevices=yes
ProtectHome=yes
ReadOnlyDirectories=/
ReadWriteDirectories=-/var/lib/redis
ReadWriteDirectories=-/var/log/redis
ReadWriteDirectories=-/var/run/redis
CapabilityBoundingSet=~CAP_SYS_PTRACE

# redis-server writes its own config file when in cluster mode so we allow
# writing there (NB. ProtectSystem=true over ProtectSystem=full)
ProtectSystem=true
ReadWriteDirectories=-/etc/redis

[Install]
WantedBy=multi-user.target
Alias=redis.service
```

**Comment by karolyi** [comment] 2017-07-10 11:47
> Also, do you have any non-standard symlinks in place, for example a symlink from /tmp to /var/tmp or vice versa or so?

no such thing:
```
$ ls -ld /tmp /var/tmp /etc/systemd /lib/systemd /lib/systemd/system 
drwxr-xr-x  5 root root  4096 jún   30 12:17 /etc/systemd/
drwxr-xr-x  8 root root  4096 jún   30 12:17 /lib/systemd/
drwxr-xr-x 26 root root 36864 júl   10 12:07 /lib/systemd/system/
drwxrwxrwt  9 root root  4096 júl   10 13:01 /tmp/
drwxrwxrwt  2 root root  4096 júl   10 13:00 /var/tmp/

$ ls -l /etc/systemd/system/redis.service /lib/systemd/system/redis-server.service 
lrwxrwxrwx 1 root root   40 júl   10 11:18 /etc/systemd/system/redis.service -> /lib/systemd/system/redis-server.service
-rw-r--r-- 1 root root 1122 jún   18  2016 /lib/systemd/system/redis-server.service
```

you can easily reproduce the problem by installing a 17.04 and then installing redis-server on it.

**Comment by poettering** [comment] 2017-07-11 08:46
Hmm, are any of /var/lib/redis, /var/log/redis, /var/run/redis, /etc/redis symlinks on your system?

**Comment by poettering** [comment] 2017-07-11 08:47
I am pretty sure this works correctly with 233 btw. my educated guess is that you have some symlink in place for one of the dirs mentioned in the namespacing directives in the unit file, and that 232 doesn't like that. This got fixed in 233 however. Any chance you can check if this issue goes away with 233?

**Comment by poettering** [comment] 2017-07-11 08:49
(i.e. 8fceda937f3a177d9e27b403fb5e1b34138b05f5 most likely fixed this)

**Comment by karolyi** [comment] 2017-07-11 09:19
> Hmm, are any of /var/lib/redis, /var/log/redis, /var/run/redis, /etc/redis symlinks on your system?
Nope:
```
$ ls -ld /var/lib/redis /var/run/redis /etc/redis
drwxr-xr-x 6 root  root  4096 júl   10 11:18 /etc/redis/
drwxr-xr-x 2 redis redis 4096 júl   10 11:18 /var/lib/redis/
drwxrwsr-x 2 redis redis   40 júl    9 14:12 /var/run/redis/
```

> Any chance you can check if this issue goes away with 233?

If there's a PPA source for it, I can try.

**Comment by poettering** [comment] 2017-07-11 09:35
> Any chance you can check if this issue goes away with 233?
> 
> If there's a PPA source for it, I can try.

Please contact the Ubuntu community for that, we don't do downstream packaging, sorry.

**Comment by karolyi** [comment] 2017-07-11 09:41
having googled around, I found this:

https://launchpad.net/~pitti/+archive/ubuntu/systemd

I can try this if you say it seems legit.

**Comment by poettering** [comment] 2017-07-11 09:46
Those appear to be @martinpitt's packages, and yes, @martinpitt is super legit.

**Comment by karolyi** [comment] 2017-07-13 08:23
I just installed a 17.04 on a virtualmachine to see if the factory image manages to install redis-server right. It did. So I'll need to investigate further on why systemd fails to install redis on my server, which is basically the same, although it's a virtual server provided by my hosting provider (hence the reason I don't really want to play around with non-production stuff there)

Is there a way I can get more output from systemd (debug) for why it refuses to start the service?

**Comment by karolyi** [comment] 2017-07-13 09:49
okay, out of desperation I installed @martinpitt's PPA. nothing changed, except now I don't see the 'too many symlinks' error message anymore with `journalctl -xe`

however, now I can see a different status for redis:

```
● redis-server.service - Advanced key-value store
   Loaded: loaded (/lib/systemd/system/redis-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2017-07-13 11:48:14 CEST; 4s ago
     Docs: http://redis.io/documentation,
           man:redis-server(1)
  Process: 1068 ExecStopPost=/bin/run-parts --verbose /etc/redis/redis-server.post-down.d (code=exited, status=237/KEYRING)
  Process: 1066 ExecStart=/usr/bin/redis-server /etc/redis/redis.conf (code=exited, status=237/KEYRING)
  Process: 1063 ExecStartPre=/bin/run-parts --verbose /etc/redis/redis-server.pre-up.d (code=exited, status=237/KEYRING)
```

**Comment by karolyi** [comment] 2017-07-13 10:01
I can get you access to my box, if that helps. You can find me on freenode with the username `karolyi`, and there we can set up an access for you to test it out.

Meanwhile, I had to downgrade systemd, as mysql didn't start with it.

**Comment by karolyi** [comment] 2017-07-20 11:43
bump

**Comment by poettering** [comment] 2017-07-20 12:35
> status=237/KEYRING)

This appears to be a complete different issue: for some reason acess to the kernel keyring is not permitted? Is this is some strange environment, LXC or somehting like that?

**Comment by karolyi** [comment] 2017-07-20 13:36
it's a [hosteurope virtual server](https://www.hosteurope.de/en/Server/Virtual-Server/), they have provided an initial image which I upgraded to 17.04. mind you, that keyring error was with the newer systemd that failed to start mysql.

contact me on IRC and I'll set you up for investigating.

**Comment by poettering** [comment] 2017-07-20 15:03
do they use virtuozzo or something like that? or is that a proper VM? What does "systemd-detect-virt" report?

**Comment by karolyi** [comment] 2017-07-20 16:35
yep, I have a virtuozzo panel. systemd-detect-virt tells openvz.

**Comment by poettering** [comment] 2017-07-20 18:53
OK, that's a duplicate of #6281 then.

**Comment by karolyi** [comment] 2017-07-20 19:48
it works with 16.04 though. I have another box on the same virtualized HW.

**Comment by zacheryph** [comment] 2017-07-31 13:39
In 17.04 `/var/run` is a symlink. as soon as i removed this and copied /run into its place redis started up perfectly fine. This is 232. Yes, i know this isnt the best or even a proper solution ;).  Maybe ubuntu will update to 233 for 17.04.  I imagine this is broke for everyone.

```console
$ ls -ld /var/run
lrwxrwxrwx 1 root root 4 Apr 12  2016 /var/run -> /run         
```

**Comment by poettering** [comment] 2017-07-31 13:56
@zacheryph systemd is simply not supported on systems where /var/run isn't a symlink to /run...

I am pretty sure this all will just work fine on current systemd (modulo the keyring thing on openvz, which however should be easy to fix). 

@karolyi: If what @zacheryph suggests is right, it might be sufficient to change this line to:

```
ReadWriteDirectories=-/var/run/redis
```
to:
```
ReadWriteDirectories=-/run/redis
```

to make things work even on the affected systemd versions. Can you check that? If this makes it work, please contact the redis packagers to change the unit file accordingly, as /var/run is really just an anachronism these days, and a legacy alias for /run only.

**Comment by zacheryph** [comment] 2017-07-31 14:02
OK.  I reset /var/run to point to /run.

I can vouch, changing ReadWriteDirectories (I also changed PIDFile under Service) and daemon-reload, redis came up just fine.

**Comment by karolyi** [comment] 2017-07-31 14:11
sheesh, this `/run` modification just fixed the error by only changing `ReadWriteDirectories=-/run/redis`.

I'll contact the redis packagers, please keep this issue open until they fix their stuff, will link this issue for them.

**Comment by poettering** [comment] 2017-07-31 14:12
ah, very good. Can you ping the redis maintainers to make the same change please?

I'd be thankful if anyone could test this all on current systemd though, it's definitely our intention that specifying /var/run should work too, and if it doesn't we should fix that. However, I think it will already just work on current systemd versions...

**Comment by karolyi** [comment] 2017-07-31 14:19
I just did report it, linking for reference:
https://bugs.launchpad.net/ubuntu/+source/redis/+bug/1707656

**Comment by poettering** [comment] 2017-09-14 19:29
Closing, as the /var/run symlink issue got fixed, and they keyring issue is tracked in #6281.

**Closed as completed by poettering** 2017-09-14 19:29 UTC
Labels: needs-reporter-feedback ❓

**Comment by KellyLSB** [comment] 2018-03-29 02:34
Still true for `redis-server.service` in Ubuntu (xenial) `redis-server=2:3.0.6-1`

**Comment by JoshuaFlood** [comment] 2018-05-22 13:29
Still true for xenial w/ redis version 4.0.9 on a digitalocean droplet. Tried altering /var/run entry but with no luck.

**Comment by darmen** [comment] 2019-02-24 21:21
Same for `redis-server.service` in Debian 9.8 (stretch) `redis-server:3:3.2.6-3+deb9u2`.
