### ISSUE TITLE
Make creation of persistant services in one command line like with systemd-run possible

### ISSUE THREAD

**Issue by Eucyon** [systemd/systemd#14458] opened 2019-12-31 19:43 UTC
**Describe the solution you'd like**
With systemd-run, one can create simple services and their timers in just one command line, which is easier than creating unit files and starting or enabling them, especially for one-timers. But they don't survive the next boot, they are transient.

Please enable this feature for persistant units which do survive the next boot.

Related to #13485, #14245, #14251.

**Comment by doverride** [comment] 2020-01-01 13:40
```
for i in $(systemd-run $@ 2>&1 | awk -F": " '{ print $2 }')
do
   cat /run/systemd/transient/$i > /etc/systemd/system/$i
done
```

**Comment by poettering** [comment] 2020-01-21 12:52
Duplicate of #13485

**Closed as completed by poettering** 2020-01-21 12:52 UTC
Labels: RFE 🎁, pid1, duplicate
