### ISSUE TITLE
Notification-Daemon service started on kdbus system exits after some time

### ISSUE THREAD

**Issue by elkrejzi** [systemd/systemd#313] opened 2015-06-21 11:23 UTC
Using kdbus and MATE Desktop here. When something tries to use desktop notification service, the notification-daemon is spawned by kdbus and the notification is shown properly. But after some inactivity, the notification-daemon is shut down and the following is seen in journal:

Jun 21 13:15:45 krejzi systemd[445]: Starting DBUS1: org.freedesktop.Notifications...
Jun 21 13:15:45 krejzi systemd[445]: Started DBUS1: org.freedesktop.Notifications.
Jun 21 13:16:58 krejzi systemd[445]: dbus-org.freedesktop.Notifications.service: Main process exited, code=exited, status=1/FAILURE
Jun 21 13:16:58 krejzi systemd[445]: dbus-org.freedesktop.Notifications.service: Unit entered failed state.
Jun 21 13:16:58 krejzi systemd[445]: dbus-org.freedesktop.Notifications.service: Failed with result 'exit-code'.

Trying to access the notification service again will result in the same behavior. I've tried to manually run the notification-daemon from the command line and the behavior is same. I've even ran it in gdb, but couldn't get anything useful from it:

[Thread 0x7ffff7f99900 (LWP 1658) exited]
[Inferior 1 (process 1658) exited with code 01](gdb) bt
No stack.

Any hints on how to debug this would be nice.

**Comment by kaysievers** [comment] 2015-06-21 15:27
"the notification-daemon is shut down" vs. "Notifications.service: Main process exited" does sound like the daemon itself exits or fails. Sure, it might be caused by a bug triggered by kdbus, but it does not sound like a kdbus issue, it for sure does not actively stop anything. Can you try to find out more why it exits/fails?

**Comment by elkrejzi** [comment] 2015-06-21 16:17
Well, I don't know where to start. I already said that using gdb doesn't help.

**Comment by elkrejzi** [comment] 2015-06-21 16:24
Here's strace output too. I couldn't figure out anything from it. Maybe one of you guys can:

https://gist.github.com/elkrejzi/1c120668670d9886f441

**Comment by dvdhrm** [comment] 2015-06-24 12:27
It looks like this is the expected behavior. See this:

https://github.com/mate-desktop/mate-notification-daemon/blob/master/src/daemon/daemon.c#L178

The mate-notification-daemon exits if there's no activity for some time. However, it exits with error-code "1" instead of success "0". Maybe you want to file an upstream bug-report? The original gnome source does not show this behavior.

Not sure why you only experience this with kdbus, though. But I really think this line I mentioned above should say `exit(0)`. If I'm wrong, maybe the mate developers can give some insight?

**Comment by elkrejzi** [comment] 2015-06-25 11:48
@dvdhrm Thank you for investigating this. I've filled a bug against mate-notification-daemon.

As for why I only experience it with kdbus:

It might be the same with dbus-daemon, except that it doesn't track exit-status or report failures-on-exit. Amazing how using kdbus reveals some outstanding issues.

**Comment by dvdhrm** [comment] 2015-06-25 11:49
Indeed, that might be the case here. It's now tracked by pid1.
I'll close this bug now. Feel free to re-open if something shows up again (and feel free to keep me on CC for the mate bug).

Thanks for the report!

**Closed as completed** 2015-06-25 11:50 UTC
Labels: not-our-bug, kdbus
