### ISSUE TITLE
systemd 235 - BindsTo device delayed state changes - on restart, service unit instability - regression

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#7162] opened 2017-10-23 03:43 UTC
- Bug report

Arch Linux
systemd 235.8-1

This use to work fine, last time I checked - systemd 234 or maybe 233.

The master@bond0.service file has:
BindsTo= sys-subsystem-net-devices-%i.device

Also, through a series of target unit files, plugging the device also will Require master@bond0.service.

"systemctl start master@bond0.service" works normally, but with a subsequent "systemctl restart master@bond0.service", ultimately, the device unit "mysteriously" disappears and stops the service unit.

Now, suspicion:  Could the initial "sys-subsystem-net-devices-bond0.device: Changed plugged -> dead" have been the delayed consequence of the "stop" portion of the "restart" cycle not being recognized until the subsequent "start" portion of the "restart" cycle has already begun?

If that is the case, then this is an "atomicity" or "asynchronicity" error in the systemd "stop" phase of the "restart" cycle.  The "active" or "inactive" state of a device *must* be "collected" *before* the service unit, which might be creating or destroying that device, can be said to be "done", and therefore, *before* the "start" phase of a "restart" cycle.  Have there been changes to the BindsTo or device ordering mechanisms?

With "systemd-analyze set-log-level debug", the log has - edited:

 systemd[1]: master@bond0.service: Changed exited -> stop-post
 systemd[1]: master@bond0.service: Changed stop-post -> dead
 ruby systemd[1]: master@bond0.service: Job master@bond0.service/restart finished, result=done
[  End of stop phase, beginning of start phase. ]
 systemd[1]: master@bond0.service: Converting job master@bond0.service/restart -> master@bond0.service/start
 systemd[1]: master@bond0.service: Changed dead -> start
 systemd[1]: master@bond0.service: Changed start -> exited
 systemd[1]: master@bond0.service: Job master@bond0.service/start finished, result=done
[ That should have, and would have, been the end of it, after creating bond0. ]
 systemd[1]: master@bond0.service: Failed to send unit change signal for master@bond0.service: Connection reset by peer
[ Then, seemingly out of nowhere: ]
 systemd[1]: sys-subsystem-net-devices-bond0.device: Changed plugged -> dead
 systemd[1]: master@bond0.service: Trying to enqueue job master@bond0.service/stop/replace
 systemd[1]: master@bond0.service: Installed new job master@bond0.service/stop as 9035
 systemd[1]: master@bond0.service: Enqueued job master@bond0.service/stop as 9035
 systemd[1]: sys-devices-virtual-net-bond0.device: Changed plugged -> dead
 systemd[1]: sys-devices-virtual-net-bond0.device: Collecting.
 systemd[1]: sys-devices-virtual-net-bond0.device: Failed to send unit change signal for sys-devices-virtual-net-bond0.device: Transport endpoint is not connected
 systemd[1]: sys-devices-virtual-net-bond0.device: Failed to send unit remove signal for sys-devices-virtual-net-bond0.device: Transport endpoint is not connected
 systemd[1]: sys-subsystem-net-devices-bond0.device: Failed to send unit change signal for sys-subsystem-net-devices-bond0.device: Transport endpoint is not connected
 systemd[1]: Failed to send job change signal for 9035: Transport endpoint is not connected
 ...
 systemd[1]: master@bond0.service: Changed exited -> stop-post
 systemd[1]: master@bond0.service: Changed stop-post -> dead
 systemd[1]: master@bond0.service: Job master@bond0.service/stop finished, result=done
...

The debug log never discloses *why* a service job state is invoked, so we can only guess at how the bond0 device suddenly "disappears", but my suspicion is that this is simply the very same "disappearance" resulting from the clean-up in the "ExecStopPost" of the service unit from the "stop" phase of the "restart", which has:
ExecStopPost= /usr/bin/ip link delete %I

But then, the command to create the bond0 interface has already been run from the service unit, and with the bond0 device creation and subsequent "delayed" re-appearance, systemd again starts master@bond0.service:

 systemd[1]: sys-subsystem-net-devices-bond0.device: Changed dead -> plugged
 systemd[1]: master@bond0.service: Installed new job master@bond0.service/start as 9052
 systemd[1]: sys-devices-virtual-net-bond0.device: Changed dead -> plugged
 systemd[1]: master@bond0.service: Changed dead -> start
 systemd[1]: master@bond0.service: Job master@bond0.service/start finished, result=done

Now, since master@bond0.service was already "stopped" a *second* time, the same "delayed" disappearance occurs, again, and then the device re-appears, again, and the sequence repeats, again:

 systemd[1]: sys-subsystem-net-devices-bond0.device: Changed plugged -> dead
 systemd[1]: master@bond0.service: Trying to enqueue job master@bond0.service/stop/replace
 systemd[1]: master@bond0.service: Installed new job master@bond0.service/stop as 9310
 systemd[1]: sys-devices-virtual-net-bond0.device: Changed plugged -> dead
 systemd[1]: sys-devices-virtual-net-bond0.device: Collecting.
...
 systemd[1]: sys-subsystem-net-devices-bond0.device: Changed dead -> plugged

In the log, this is followed by a lot of entries in the nature of:
 systemd[1]: Requested transaction contradicts existing jobs: Resource deadlock avoided
as other dependent service units are started, and then deleted, and then stopped.  Of course, this is a lot of otherwise pointless "busy work", since the master@bond0.service unit should never have been started, then stopped and then started again, in the "start" phase of the "restart".

Here, despite the bond0 device "re-appearing" again, no start job is queued, and the existing stop job completes:

 systemd[1]: master@bond0.service: Changed exited -> stop-post
 systemd[1]: master@bond0.service: Changed stop-post -> dead
 systemd[1]: master@bond0.service: Job master@bond0.service/stop finished, result=done

Otherwise, this "back and forth" might have gone on indefinitely.  Ultimately, though, the "restart" has failed.  This is a problem that needs to be fixed.

This can get even worse, were the service unit which creates a network device to try to first delete a pre-existing device before creating that device, just to ensure a particular configuration state for that device.  If the pre-existing device deletion is not recognized by systemd until after that device has been re-created by the service unit, then there is going to be even more "instability", as the device "disappears" and "re-appears" and "disappears" and "re-appears", and on and on.

It looks like systemd should have treated the execution phase of a service unit as "atomic" with respect to the activation state of a BindsTo dependency.  In other words, the activation state of a BindsTo dependency would be "locked" whenever a dependent service unit is in an execution phase, and that activation state must be "collected" immediately before and after a dependent service unit execution phase.  Any "delayed" device activation state information is simply *wrong* information.

I also tried adding a gratuitous "sleep 1" to the ExecStopPost, with the idea that the inactive state of the bond0 device would have time to propagate, but this is not enough.  Instead, the delay seemed to also delay the propagation of the subsequent activation state of the bond0 device.  The log gives - edited:

 systemd[1]: master@bond0.service: Unit is bound to inactive unit sys-subsystem-net-devices-bond0.device. Stopping, too.
 systemd[1]: master@bond0.service: Trying to enqueue job master@bond0.service/stop/fail
 systemd[1]: Requested transaction contradicts existing jobs: Transaction is destructive.
 systemd[1]: master@bond0.service: Failed to enqueue stop job, ignoring: Transaction is destructive.
[  But the delay also delays the activation state of the bond0 device. ]
 systemd[1]: enp0s7@bond0.service: Unit is bound to inactive unit sys-subsystem-net-devices-bond0.device. Stopping, too.
 systemd[1]: enp0s7@bond0.service: Trying to enqueue job enp0s7@bond0.service/stop/fail
 systemd[1]: enp0s7@bond0.service: Installed new job enp0s7@bond0.service/stop as 10058
 systemd[1]: enp0s7@bond0.service: Enqueued job enp0s7@bond0.service/stop as 10058
[  Finally, the device activation state changes, but it is too late: ]
 systemd[1]: sys-subsystem-net-devices-bond0.device: Changed dead -> plugged
 systemd[1]: sys-subsystem-net-devices-bond0.device: Changed dead -> plugged
 systemd[1]: enp0s7@bond0.service: enp0s7@bond0.service/start would change existing job.
 systemd[1]: enp0s7@bond0.service: Deleting enp0s7@bond0.service/start to minimize impact
 systemd[1]: enp0s7@bond0.service: enp0s7@bond0.service/start would change existing job.
 systemd[1]: enp0s7@bond0.service: Deleting enp0s7@bond0.service/start to minimize impact.
 systemd[1]: enp0s7@bond0.service: Changed exited -> stop-post
 systemd[1]: enp0s7@bond0.service: Changed stop-post -> dead
 systemd[1]: enp0s7@bond0.service: Job enp0s7@bond0.service/stop finished, result=done

The result is that the bond0 device still exists, but none of the slave devices are still enslaved, and again, the restart has failed.

Additionally adding a gratuitous "sleep 1" delay after the bond0 device is created results in a working restart.  But hey, this is getting ridiculous, with two seconds of gratuitous delay, after the device is destroyed and created.  The device activation state changes are not being properly synchronized by systemd.

**Comment by poettering** [comment] 2019-11-13 12:32
My educated guess is that After=sys-subsystem-net-devices-%i.device is missing in the unit file, and that we nowadays are more insisting about that. 

See documentation about this, where we clarify this explicitly:

https://www.freedesktop.org/software/systemd/man/systemd.unit.html#BindsTo=

Anyway this report lacks the actual unit files, and smells like something better discussed on systemd-devel anyway, since it's likely just caused by incorrect unit files, not actual bugs. Closing hence.

**Closed as completed by poettering** 2019-11-13 12:32 UTC
Labels: pid1
