### ISSUE TITLE
Services with PrivateTmp=true will fail when /tmp is a symlink toward /var/tmp

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#6212] opened 2017-06-27 14:04 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

> v233

### Used distribution

> openSUSE Tumbleweed

### Description

Some people want their /tmp to be a symlinked to /var/tmp. That doesn't seem a good idea but since it used to work...

So the issue is that since commit 8fceda937f3a177d9e27b403fb5e1b34138b05f5, the following errors can be seen when /tmp → /var/tmp:

> systemd[1868]: ntpd.service: Failed at step NAMESPACE spawning /usr/sbin/start-ntpd: No such file or directory

Basically ntpd.service uses `PrivateTmp=true`. In this case PID1 will try to setup a new namespace with /tmp and /var/tmp bound to private host directories. However since /tmp points to /var/tmp both directories will have the same parent dir.

But as soon as /var/tmp will be first mounted, the host directory for /tmp is not visible anymore by the ntpd service.

Before 8fceda937f3a177d9e27b403fb5e1b34138b05f5, this used to work since PID1 noticed /tmp and /var/tmp were the same and therefore /tmp remained as a symlink in the new namespace.

**Comment by mbiebl** [comment] 2017-06-27 20:56
Related downstream bug report:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850855
Units with PrivateTmp fail when /var is a symlink

**Comment by poettering** [comment] 2018-05-03 10:26
I am pretty sure this is fixed now since #8708. Closing.

if you can reproduce this with #8708 pleas reopen.

**Closed as completed by poettering** 2018-05-03 10:26 UTC
Labels: pid1

**Comment by fbuihuu** [comment] 2018-05-24 05:15
Verified.
