### ISSUE TITLE
systemd-tmpfiles --clean gets stuck on trying to open a pipe

### ISSUE THREAD

**Issue by grawity** [systemd/systemd#31503] opened 2024-02-27 06:08 UTC
### systemd version the issue has been seen with

255.3

### Used distribution

Arch Linux

### Linux kernel version used

6.6.2-arch1-1

### CPU architectures issue was seen on

None

### Component

systemd-tmpfiles

### Expected behaviour you didn't see

systemd-tmpfiles should unlink() pipes without trying to open them.

### Unexpected behaviour you saw

systemd-tmpfiles tries to open() the pipe – which blocks and the process gets stuck forever.

### Steps to reproduce the problem

1. `mkdir /tmp/repro`
2. `echo "q /tmp/repro 0777 root root 15s" > /etc/tmpfiles.d/bug.conf`
3. `mkfifo /tmp/repro/fifo`
4. `sleep 30` for the ctime of the fifo to age
5. `systemd-tmpfiles --clean repro.conf`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
# ls -l /tmp/clr*
prwx------ 1 grawity users 0 Dec 21 13:39 /tmp/clr-debug-pipe-1134568-207416317-in|
prwx------ 1 grawity users 0 Dec 21 13:39 /tmp/clr-debug-pipe-1134568-207416317-out|

# strace systemd-tmpfiles --clean
<other output>
statx(3, "clr-debug-pipe-1134568-207416317-in", AT_STATX_SYNC_AS_STAT|AT_SYMLINK_NOFOLLOW|AT_NO_AUTOMOUNT, STATX_TYPE|STATX_MODE|STATX_UID|STATX_ATIME|STATX_MTIME|STATX_CTIME|STATX_BTIME, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFIFO|0700, stx_size=0, ...}) = 0
openat(3, "clr-debug-pipe-1134568-207416317-in", O_RDONLY|O_NOFOLLOW|O_NOATIME|O_CLOEXEC
<hangs forever at this point>
```

**Comment by YHNdnzj** [comment] 2024-02-27 06:19
Duplicate of https://github.com/systemd/systemd/issues/30690 and already fixed by #31116.

**Closed as not planned** 2024-02-27 06:22 UTC
Labels: bug 🐛, tmpfiles, duplicate, already-fixed
