### ISSUE TITLE
if you mask systemd-cryptsetup's unit and have entries in /etc/crypttab, then things start breaking (surprise!)

### ISSUE THREAD

**Issue by oficsu** [systemd/systemd#29488] opened 2023-10-07 00:14 UTC
### systemd version the issue has been seen with

core/systemd 254.5-1

### Used distribution

Manjaro (latest)

### Linux kernel version used

6.5.5-1-MANJARO

### CPU architectures issue was seen on

x86_64

### Component

systemd-cryptsetup

### Steps to reproduce the problem

Prerequisites:
1) I have a custom mkinitcpio hook that decrypts my swap partition to `/dev/mapper/swap`;
2) It behaves like `plymouth-encrypt` + `decrypt_keyctl`, so my `/etc/crypttab` [has a special meaning](https://cryptsetup-team.pages.debian.net/cryptsetup/README.keyctl.html) for the `password`/`keyfile` field. Hooks priorities:
```bash
HOOKS=(plymouth base udev keyboard autodetect keymap block oficsu-decrypt resume filesystems)
```
3) I can assume my hook works because I still can resume my system with `resume=/dev/mapper/swap`;
4) Even though `systemd-cryptsetup@swap.service` works (= does nothing), I had to mask it since this service can't parse my `/etc/crypttab` correctly and produces warnings for my partitions:
```bash
cat /etc/crypttab
# <name>        <device>        <password>                    <options>
root      PARTUUID=<root-uuid>     root    luks=no,discard,header=PARTUUID=<boot-uuid>:/headers/root
swap      PARTUUID=<swap-uuid>     root    luks=no,discard,header=PARTUUID=<boot-uuid>:/headers/swap

```
```
systemd[1]: /run/systemd/generator/systemd-cryptsetup@swap.service:20: RequiresMountsFor= path is not absolute, ignoring: root
```
5) I added my swap device to fstab:
```bash
cat /etc/fstab
...
/dev/mapper/swap none swap defaults 0 2
```

6) Everything worked fine for 2 years (until the last reboot), and I don't have recent changes in my system configuration 

### Expected behaviour you didn't see

My configuration still works and doesn't depend on the masked `systemd-cryptsetup`

### Unexpected behaviour you saw

The swap partition isn't enabled after the last reboot with masked `systemd-cryptsetup` (but it works with unmasked)

The swap mentions in system logs:
````bash
journalctl -b 0  | grep swap
kernel: Command line: ... resume=/dev/mapper/swap ...
kernel: Kernel command line: ... resume=/dev/mapper/swap ...
kernel: zswap: loaded using pool zstd/zsmalloc
<EOF>
````

Try mounting manually (the shown entry is my swap):
```bash
mount -av
...
none  : ignored 
```

Systemctl statuses:
```bash
systemctl status dev-mapper-swap.swap
○ dev-mapper-swap.swap - /dev/mapper/swap
     Loaded: loaded (/etc/fstab; generated)
     Active: inactive (dead)
       What: /dev/mapper/swap
       Docs: man:fstab(5)
             man:systemd-fstab-generator(8)
```
```bash
systemctl status swap.target
○ swap.target - Swaps
     Loaded: loaded (/usr/lib/systemd/system/swap.target; static)
     Active: inactive (dead)
       Docs: man:systemd.special(7)
```
Of course, everything works after a manual `swapon -a`, but I have no clue what happened and how to debug further. But I think the reason is the upgrade from 253.8-1 to 254.3-1

**Comment by oficsu** [comment] 2023-10-07 06:24
Even more interesting. I've tried the following:
```bash
btrfs subvolume create /swap
btrfs filesystem mkswapfile --size 256m --uuid clear /swap/swapfile
echo '/swap/swapfile none swap defaults 0 0' >> /etc/fstab
mkinitcpio -P
reboot
```

Then I booted with different kernels: 6.5.5-1-MANJARO, 6.1.55-1-MANJARO, 6.0.19-4-MANJARO. With the 6.0, swap hasn't been activated. With the first two, it is:
```bash
journalctl -b 0  | grep swap
...
systemd[1]: Activating swap /swap/swapfile...
systemd[1]: Activated swap /swap/swapfile.
kernel: Adding 262140k swap on /swap/swapfile.  Priority:-2 extents:10 across:15242088k FS
...
```
Any ideas?

**Comment by poettering** [comment] 2023-10-10 08:26
Is any of this reproducible if systemd is used in the initrd, and the /etc/crypttab is compatible with systemd?

Generally, please contact your distro for help with this, in particular if they depart from our logic so much, they have to maintain this then. This is not actionable for us, noone of us runs Manjaro or uses their initrd implementation.

**Comment by oficsu** [comment] 2023-10-12 16:38
> Is any of this reproducible if systemd is used in the initrd, and the /etc/crypttab is compatible with systemd?

If systemd is used in the initrd, then... `systemd-cryptsetup` should not be masked? So... Does it make sense? Because the bug somewhere in `fstab-generator` that incorrectly handles masked `systemd-cryptsetup`. Does `fstab-generator` supposed to work with masked `systemd-cryptsetup`?

If so, it doesn't look like a distro-specific bug. I think it was introduced with systemd 254, because it happened to my second laptop after the upgrade. I can test it on a simpler configuration with Debian testing + `plymouth-encrypt` + masked `systemd-cryptsetup`

Should I? Will it be enough to assume the bug is in systemd and not related to Manjaro?

**Comment by poettering** [comment] 2023-10-24 12:32
uh, if you mask that then i guess the logic around blockdev@.target won't work anymore.

So yes, if you mask central pieces of systemd's mount/volume handling then you should not be surprised things don't work anymore...

**Comment by oficsu** [comment] 2023-10-25 16:32
So, @poettering, is there a correct way to disable device decryption, but keep the rest mount/volume handling? Or can I expect it in a future release?

**Comment by poettering** [comment] 2023-10-30 22:00
it's not something anyone here cares about. generally, if you mask systemd's units you void your warranty and we are deeply uninterested in reports that things break then. If you mask systemd's units you need to know what you are doing and how to deal with the fallout. Clean setups do not mask units.

I mean, we provide the concept of masking units to you, but it comes with the implied risk that it will break things.

anyway, i am not sure i grok why you feel the need to mask it though? what's wrong with it?

**Comment by oficsu** [comment] 2023-10-31 09:31
> what's wrong with it?

@poettering, because systemd doesn't recognize my crypttab format correctly:
* it warns [usage of keyfile the way `decrypt_keyctl` expects it to be](https://cryptsetup-team.pages.debian.net/cryptsetup/README.keyctl.html), and I don't want one day it to break completely or cause my system to stop loading because of it;
* it doesn't (or didn't?) recognize [option `header=PARTUUID=<some-part-uuid>:<path-to-header>`](https://www.freedesktop.org/software/systemd/man/latest/crypttab.html#header=), so systemd can't decrypt my partition

Anyway, the partition is already decrypted before systemd starts. So I need a safe way to disable systemd decrypting facilities (but not others)

**Comment by poettering** [comment] 2023-10-31 11:48
> * it doesn't (or didn't?) recognize [option `header=PARTUUID=<some-part-uuid>:<path-to-header>`](https://www.freedesktop.org/software/systemd/man/latest/crypttab.html#header=), so systemd can't decrypt my partition

see docs, it's the other way round, and supported.

> * it warns [usage of keyfile the way `decrypt_keyctl` expects it to be](https://cryptsetup-team.pages.debian.net/cryptsetup/README.keyctl.html), and I don't want it to break completely one day or cause my system to stop loading because of it;

i have no idea what that means and what decrypt_keyctl is. But if this is just about caching passwords, then systemd does that anyway.

But frankly, feel free to use whatever you like, it's entirely up to you of course, but please also understand that randomly some units voids your warranty.

You best bet is probably to mask the systemd-cryptsetup-generator, so that we do not generate any units for your device. But frankly I'd really avoid trying to shoehorn this script mess into systemd.

Anyway, let's close this, as this is not a bug, and I see nothing actionable here from our side.

**Closed as completed by poettering** 2023-10-31 11:48 UTC
Labels: cryptsetup, fstab-generator, not-a-bug
