### ISSUE TITLE
A scope remains active after it's processes have exited

### ISSUE THREAD

**Issue by robryk** [systemd/systemd#1351] opened 2015-09-23 00:59 UTC
When I start a process in a new scope using systemd-run I'd expect the scope to disappear or become inactive once all processes inside have exited. That does not happen: the scope remains `active (running)` despite having no processes. This prevents me from reusing the same scope name without explicitly stopping the scope first.

Repro steps:

```
[robryk@sharya-rana bin]$ systemctl --user daemon-reload
[robryk@sharya-rana bin]$ systemctl --version
systemd 226
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD +IDN
[robryk@sharya-rana bin]$ systemd-run --user --scope --unit=foobar /bin/sleep 5
Running scope as unit foobar.scope.
[robryk@sharya-rana bin]$ systemctl status --user foobar.scope
● foobar.scope - /bin/sleep 5
   Loaded: loaded (/run/user/1000/systemd/user/foobar.scope; static; vendor preset: enabled)
  Drop-In: /run/user/1000/systemd/user/foobar.scope.d
           └─50-Description.conf
   Active: active (running) since Wed 2015-09-23 02:51:56 CEST; 30s ago

Sep 23 02:51:56 sharya-rana systemd[763]: Started /bin/sleep 5.
[robryk@sharya-rana bin]$ systemd-run --user --scope --unit=foobar /bin/sleep 5
Failed to start transient scope unit: Unit foobar.scope already exists.
[robryk@sharya-rana bin]$ 
```

What I would expect:
- I'd expect the `systemctl status` invocation to claim that the scope is inactive.
- I'd expect the second call to systemd-run to succeed.

**Comment by poettering** [comment] 2015-09-23 01:16
Which distro is this? Which version of systemd is this?

**Comment by robryk** [comment] 2015-09-23 06:02
Distro: Arch Linux

Version of systemd:
I've just realized that at that point I has systemd 226 installed and systemd 225 running as the user daemon. Doing `daemon-reexec` (un)fortunately caused the issue to disappear.

**Comment by utezduyar** [comment] 2015-09-23 07:33
Strange because this was fixed long time ago (v220) - https://github.com/systemd/systemd/commit/de158ed22db60e3a6654557fa4aa72f7248550af. Please report back if you can reproduce it.

**Comment by robryk** [comment] 2015-09-23 07:47
Please note that my process was not short-lived: it was "sleep 5". I will report back if it reappears.

**Comment by poettering** [comment] 2015-11-02 19:38
Closing, as the issue apparently disappeared...

**Closed as completed by poettering** 2015-11-02 19:38 UTC
Labels: pid1, needs-reporter-feedback ❓
