### ISSUE TITLE
[resolved] cannot set "Domains" parameter for Global

### ISSUE THREAD

**Issue by bugfood** [systemd/systemd#11318] opened 2019-01-03 02:42 UTC
**systemd version the issue has been seen with**
```
$ systemd --version
systemd 240
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

**Used distribution**
```
$ cat /etc/debian_version 
buster/sid
```

**Expected behaviour you didn't see**
1. Can query the "Global" domains directly via resolvectl.
2. Can set the domains for "Global" via resolvectl or busctl.

**Unexpected behaviour you saw**
1. Cannot query the "Global" domains directly via resolvectl.
2. Cannot set the domains for "Global" via resolvectl or busctl.

**Steps to reproduce the problem**
```
# Initial setup:
$ resolvectl domain 
Global: wework.com
Link 10 (br1):
Link 9 (br0):
Link 5 (docker0):
Link 2 (eth0):
$ busctl get-property org.freedesktop.resolve1 /org/freedesktop/resolve1 org.freedesktop.resolve1.Manager Domains
a(isb) 1 0 "wework.com" false

# Expected behavior for querying a regular interface:
$ resolvectl domain eth0
Link 2 (eth0):
$ resolvectl domain 2
Link 2 (eth0):

# Unexpected behavior for querying "Global":
$ resolvectl domain Global
Unknown interface 'Global': No such device
$ resolvectl domain 0
Unknown interface '0': No such device

# Expected behavior when setting domains via busctl for a regular interface:
$ sudo busctl call org.freedesktop.resolve1 /org/freedesktop/resolve1 org.freedesktop.resolve1.Manager SetLinkDomains 'ia(sb)' 2 1 example.com false
$ resolvectl domain eth0
Link 2 (eth0): example.com

# Unexpected behavior when setting domains via busctl for "Global" (index 0):
$ sudo busctl call org.freedesktop.resolve1 /org/freedesktop/resolve1 org.freedesktop.resolve1.Manager SetLinkDomains 'ia(sb)' 0 1 example.com false
Invalid interface index
```

Thanks,
Corey

**Comment by yuwata** [comment] 2019-01-03 12:11
Duplicate of #8916.

**Closed as completed by yuwata** 2019-01-03 12:11 UTC
Labels: RFE 🎁, resolve, duplicate
