### ISSUE TITLE
Ordering network before cryptsetup

### ISSUE THREAD

**Issue by npmccallum** [systemd/systemd#5169] opened 2017-01-27 15:20 UTC
I'm working on automated decryption. https://github.com/latchset/clevis

We currently have automated root volume decryption in dracut. However, we want to also automate non-root volumes. Unfortunately, it doesn't seem possible to me to get network access started before cryptsetup in the current systemd.

I'm not sure why cryptsetup for ancillary volumes is starting so early. Currently it starts before sysinit.target. But network doesn't come up until afterwards. Is there something I'm missing? Can we move cryptsetup.target after sysinit.target?

**Comment by fsateler** [comment] 2017-01-27 17:17
Duplicate of #4642

**Closed as completed by fsateler** 2017-01-27 17:17 UTC
Labels: RFE 🎁, duplicate
