### ISSUE TITLE
systemctl show changes

### ISSUE THREAD

**Issue by lnykryn** [systemd/systemd#3856] opened 2016-08-02 07:30 UTC
We declare that systemctk show is stable and can be used in scripts, but the recent changes broke my script. https://git.fedorahosted.org/cgit/initscripts.git/commit/?h=rhel7-branch&id=ccaff12b467734624ef41e623aa0f94fa05114af

Because service command in the past did not need any reload action when initscript was added. This changed with introduction of sysv-generator. I have fixed that issue by looking at the unit in service command and when I got not-found I have tried to reload systemd before calling systemctl start. This does not work anymore since show returns that unit was not found.

To be clear, I am fine with the new behavior and the changes in my code are pretty trivial and I am completely fine with wontfix. I just want to bring this up.

**Comment by keszybz** [comment] 2016-08-02 12:15
As a matter of principle you are right… but yeah, I don't think this something we can fix without adding special support for initscripts back to pid1. So I'd be inclined to to close as wontfix.

**Comment by lnykryn** [comment] 2016-08-02 12:46
I am not complaining about initscript but about change of systemctl show for non existing units.

**Comment by lnykryn** [comment] 2016-08-02 12:51
In short:  I have used this for getting the information that unit does not exist and I need to reload systemd: systemctl show -p LoadState "$prog.service" | grep -q 'not-found'

**Comment by fsateler** [comment] 2016-08-02 14:25
I think the problem is the change:

```
# 215
% systemctl show -pLoadState asdf.service
LoadState=not-found
# 231
% systemctl show -pLoadState asdf.service
Unit asdf.service could not be found.
```

**Comment by lnykryn** [comment] 2016-08-02 14:55
Yes

**Comment by MacGyverNL** [comment] 2016-08-02 17:55
The same change seems to affect the systemd bash completion script at https://github.com/systemd/systemd/blob/ed1190498f977f5dd2287b1e4db356147196ced5/shell-completion/bash/systemctl.in#L41 . As far as I've been able to deduce, the function __filter_units_by_property depends on the behaviour that for every unit fed to systemctl show --property, there will be _exactly_ one line of output on stdout. Since this change breaks that assumption, the not-found units are matched with property output for whatever unit was next in the list, resulting in bash completion failing and being interleaved with errors about units not found.

**Comment by fsateler** [comment] 2016-08-02 19:36
I think this was introduced on e33a06a1eb7406ece8e35f6346ba0ea208c11cf1, in particular there is an explicit check https://github.com/systemd/systemd/commit/e33a06a1eb7406ece8e35f6346ba0ea208c11cf1#diff-69ea3a0848eb29638bc663cf16af1b2dR4596:

```
        if (streq_ptr(property_info.load_state, "not-found") && streq_ptr(property_info.active_state, "inactive"))
                 return EXIT_PROGRAM_OR_SERVICES_STATUS_UNKNOWN;
```

**Comment by poettering** [comment] 2016-08-17 18:14
I figure we really should print the "Unit asdf.service could not be found." stuff only on "systemctl status" but not on "systemctl show". The former is user-facing the latter is supposed to be scriptable. Hence the letter should stick to the old behaviour really.

Marked this for v232 now.

**Closed as completed** 2016-09-27 14:25 UTC
Labels: systemctl, regression ⚠️
