### ISSUE TITLE
systemd-analyze is not reporting time spent in firmware when Secure Boot is enabled

### ISSUE THREAD

**Issue by hal3003** [systemd/systemd#14157] opened 2019-11-26 11:50 UTC
I'm unsure as to whether this is a bug or expected behaviour, since I could not find documentation.

**systemd version the issue has been seen with**
> 243.4

**Used distribution**
 > Fedora 31, Debian 10

**Expected behaviour you didn't see**
 > Usually on a system that is booted in UEFI mode, the output of sytemd-analyze looks like this: 
```
Startup finished in 25.530s (firmware) + 1.496s (loader) + 1.060s (kernel) + 2.099s (userspace) = 30.186s
graphical.target reached after 1.386s in userspace

```
**Unexpected behaviour you saw**
 > On my systems that are booted in UEFI mode with secure boot enabled, the output looks like this:
```
Startup finished in 5.419s (kernel) + 13.477s (initrd) + 7.399s (userspace) = 26.297s 
graphical.target reached after 7.382s in userspace
```

**Steps to reproduce the problem**

- boot system with secure boot disabled
- run systemd-analyze
- boot system with secure boot enabled 
- run systemd-analyze

**Comment by paulmenzel** [comment] 2019-11-27 11:49
Is it the same system you test this with, that means en-/disable SecureBoot?

**Comment by hal3003** [comment] 2019-11-27 12:34
> Is it the same system you test this with, that means en-/disable SecureBoot?

Yes.
I tested it on two systems, my desktop and a Thinkpad T495s. Both exhibit the same issue, they only report time spent in firmware if Secure Boot is disabled. Once I disabled Secure Boot, both systems report time spent in firmware.

**Comment by poettering** [comment] 2019-12-13 14:06
is /sys/firmware/acpi/tables/FPDT accessible when this happens? that's where we parse that from...

**Comment by hal3003** [comment] 2019-12-16 08:43
> is /sys/firmware/acpi/tables/FPDT accessible when this happens? that's where we parse that from...

Yes, it is accessible, but with very limited rights. This is on my Thinkpad T495s. I can confirm this on my other system later.
`ls -la /sys/firmware/acpi/tables/FPDT`
`-r--------. 1 root root 52 Dec 15 23:27 /sys/firmware/acpi/tables/FPDT`

**Comment by poettering** [comment] 2020-01-21 08:52
so, if you run the systemd-analyze command as root, does it work then?

**Comment by hal3003** [comment] 2020-01-21 09:07
> so, if you run the systemd-analyze command as root, does it work then?

I'm afraid not. The file you mentioned earlier exists on both my systems. Running systemd-analyze as root does not report time spent in firmware on either systems.

**Comment by openmindead** [comment] 2020-02-14 02:05
Manjaro (default EFI entry, systemd-boot, ssd No.1): output is full (`Startup finished in 14.199s (firmware) + 3.360s (loader) + 1.975s (kernel) + 12.082s (userspace) = 31.617s`)
Ubuntu (another EFI entry, manually selected in UEFI menu, shim / grub, ssd No.2): output contains kernel and userspace only).

**Comment by JeffPeters** [comment] 2021-09-20 23:11
The issue is ```/sys/firmware/acpi/tables/FPDT``` just is a pointer to where to load the data from in ```/dev/mem``` And with secure boot enabled, access to [```/dev/mem```](https://github.com/systemd/systemd/blob/f62c5bd15203aa944d6bce7d03ab5bad6b0958a0/src/shared/acpi-fpdt.c#L108) is limited to signed kernels or signed kernel modules, and as this systemd code is running in userspace it fails to get firmware start time (even with root permissions). 

Might have better luck with Kernel 5.12+ which allow reading this data from the kernel itself, via ```/sys/firmware/acpi/fpdt/firmware_start_ns```
See: 
 - https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-firmware-acpi
 - https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.12-ACPI-FPDT

If that works you could then write your own kernel module (and sign it) to read the value in an older kernel, but I assume updating kernel/system would be easier.

**Comment by poettering** [comment] 2024-04-18 08:58
I guess we can close this since bc09c2d865315e8f0ffdb20b31cd420faec16b5d has long been merged

**Closed as completed by poettering** 2024-04-18 08:58 UTC
Labels: needs-reporter-feedback ❓
