### ISSUE TITLE
$prefix is suddenly ignored in systemd.pc

### ISSUE THREAD

**Issue by benzea** [systemd/systemd#18130] opened 2021-01-04 13:30 UTC
So, with 6e65df89c348242dbd10036abc7dd5e8181cf733 the .pc file is now ignoring the prefix. This is breaking some meson files we have currently that override the `prefix` value in order to install into a development environment (i.e. `jhbuild`).

I don't really like that hack, but it works. We really want to install into a separate prefix, and then make sure this gets picked up when/if we need it.

There are various ways of doing that. Relying on `systemd.pc` and overriding the prefix was one option. Another options would be to just build `systemduserunitdir` directly rather than relying on pkgconfig. But, I fear we want something somewhat automatic/convenient that doesn't result in setting an option for every module in jhbuild (or we need a well-defined option that everyone can use).

Thoughts on reverting the commit (partially)? As I said, fine if you reject the idea, we can find another solution for the problem.

**Comment by keszybz** [comment] 2021-01-04 13:43
> I don't really like that hack, but it works. 

Define "works". As mentioned in the patch:
> FIXME: systemd.pc uses ${prefix}, but CONF_PATHS_NULSTR doesn't.

This means that the configuration would be (partially) loaded from the wrong paths.

**Comment by benzea** [comment] 2021-01-04 13:45
Well, we would still hard-code it in systemd everywhere. This is just about making it easier to override for special cases (i.e. jhbuild).

Looks like the NixOS people suggested https://github.com/systemd/systemd/pull/18118/commits/234655c554cc5f8b85e0fc36b58fcd1439d5c2ba in #18118, so really, this issue is a duplicate of that one.

**Comment by bluca** [comment] 2021-01-04 17:30
Duplicate of https://github.com/systemd/systemd/issues/18082 - closing

**Closed as completed by bluca** 2021-01-04 17:30 UTC
Labels: duplicate
