### ISSUE TITLE
test-suite failure: test-udev-device-thread                 FAIL

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#10431] opened 2018-10-16 22:42 UTC
Trying to build git master in Debian sid buildd chroot I get the following failure:
```
434/494 test-udev-device-thread                 FAIL     0.02 s (killed by signal 6 SIGABRT)

--- command ---
PATH='/build/systemd-239+upstream20181016/build-deb:/usr/sbin:/usr/bin:/sbin:/bin' SYSTEMD_KBD_MODEL_MAP='/build/systemd-239+upstream20181016/src/locale/kbd-model-map' SYSTEMD_LANGUAGE_FALLBACK_MAP='/build/systemd-239+upstream20181016/src/locale/language-fallback-map' /build/systemd-239+upstream20181016/build-deb/test-udev-device-thread
--- stderr ---
Assertion 'loopback = udev_device_new_from_syspath(NULL, "/sys/class/net/lo")' failed at ../src/libsystemd/sd-device/test-udev-device-thread.c:26, function main(). Aborting.
-------
```

**Comment by mbiebl** [comment] 2018-10-17 14:41
Fwiw, test-sd-device-thread has the same problem...

**Comment by mbiebl** [comment] 2018-10-17 14:44
```
# ip -c a                                                  
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 52:54:00:de:a9:aa brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.154/24 brd 192.168.122.255 scope global ens3
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fede:a9aa/64 scope link 
       valid_lft forever preferred_lft forever

# find /sys/class/net/
/sys/class/net/
/sys/class/net/lo
/sys/class/net/ens3
```

**Comment by mbiebl** [comment] 2018-10-17 15:41
hm, this is interesting. If I build systemd in chroot environment which does not use a merged-/usr setup, then the test succeeds. The root cause seems to be the same as in #10430
The test-udev-device-thread binary links against the wrong libudev:
```
        libudev.so.1 => /build/systemd-D0bXUg/systemd-239+upstream20181016/build-deb/./../../../../lib/x86_64-linux-gnu/libudev.so.1 (0x00007f953b2f7000)
```
The difference is that the failure mode is less obvious as in #10431

**Comment by yuwata** [comment] 2018-10-18 19:05
So, this seems a duplicate of #10430. Let's close this.

**Closed as completed by yuwata** 2018-10-18 19:05 UTC
Labels: tests, not-our-bug, duplicate, meson
