### ISSUE TITLE
Since v240, exiting sway (wayland compositor) closes the logind session

### ISSUE THREAD

**Issue by aroig** [systemd/systemd#11269] opened 2018-12-25 11:26 UTC
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > arch linux + [sway](https://github.com/swaywm/sway) from master

**Expected behaviour you didn't see**
 > sway is a lightweight wayland compositor. I start it from a tty. When I exit the compositor I expect it goes back to the tty, without closing my current logind session. That was the behaviour on systemd 239

**Unexpected behaviour you saw**
 > When closing sway, logind decides to close my user session.

**Steps to reproduce the problem**
Start and exit sway (or maybe any other wayland compositor) from a tty.

Here is a piece of logind logs:

> Dec 25 11:50:23 riemann systemd-logind[31666]: Sent message type=method_return sender=n/a destination=:1.284 path=n/a interface=n/a member=n/a cookie=127 reply_cookie=56 signature=n/a error-name=n/a error-message=n/a
Dec 25 11:50:23 riemann systemd-logind[31666]: Got message type=method_call sender=:1.284 destination=org.freedesktop.login1 path=/org/freedesktop/login1/session/_315 interface=org.freedesktop.login1.Session member=ReleaseControl cookie=57 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Dec 25 11:50:23 riemann systemd-logind[31666]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RemoveMatch cookie=128 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Dec 25 11:50:23 riemann systemd-logind[31666]: Successfully forked off '(logind)' as PID 32180.
Dec 25 11:50:23 riemann [32180]: PR_SET_MM_ARG_START failed, attempting PR_SET_MM_ARG_END hack: Operation not permitted
Dec 25 11:50:23 riemann [32180]: PR_SET_MM_ARG_END hack failed, proceeding without: Operation not permitted
Dec 25 11:50:23 riemann systemd-logind[31666]: (logind) succeeded.
Dec 25 11:50:23 riemann systemd-logind[31666]: Sent message type=method_return sender=n/a destination=:1.284 path=n/a interface=n/a member=n/a cookie=129 reply_cookie=57 signature=n/a error-name=n/a error-message=n/a
Dec 25 11:50:23 riemann login[31692]: pam_unix(login:session): session closed for user abdo
Dec 25 11:50:23 riemann systemd-logind[31666]: Got message type=method_call sender=:1.286 destination=org.freedesktop.login1 path=/org/freedesktop/login1 interface=org.freedesktop.login1.Manager member=ReleaseSession cookie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Dec 25 11:50:23 riemann systemd-logind[31666]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetConnectionUnixUser cookie=130 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Dec 25 11:50:23 riemann systemd-logind[31666]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.280 path=n/a interface=n/a member=n/a cookie=15 reply_cookie=130 signature=u error-name=n/a error-message=n/a
Dec 25 11:50:23 riemann systemd-logind[31666]: Sent message type=method_return sender=n/a destination=:1.286 path=n/a interface=n/a member=n/a cookie=131 reply_cookie=2 signature=n/a error-name=n/a error-message=n/a
Dec 25 11:50:23 riemann login[31692]: pam_succeed_if(login:session): requirement "uid = 1000" was met by user "abdo"
Dec 25 11:50:23 riemann systemd-logind[31666]: Sent message type=method_call sender=n/a destination=org.freedesktop.systemd1 path=/org/freedesktop/systemd1/unit/session_2d15_2escope interface=org.freedesktop.systemd1.Scope member=Abandon cookie=132 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Dec 25 11:50:23 riemann systemd[1]: getty@tty2.service: Succeeded.
Dec 25 11:50:23 riemann audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=getty@tty2 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 25 11:50:23 riemann systemd[1]: getty@tty2.service: Consumed 24ms CPU time, no IP traffic.
Dec 25 11:50:23 riemann systemd[1]: session-15.scope: Succeeded.
Dec 25 11:50:23 riemann systemd[1]: session-15.scope: Consumed 2.242s CPU time, no IP traffic.
Dec 25 11:50:23 riemann systemd[1]: getty@tty2.service: Service has no hold-off time (RestartSec=0), scheduling restart.
Dec 25 11:50:23 riemann systemd[1]: getty@tty2.service: Scheduled restart job, restart counter is at 10.
Dec 25 11:50:23 riemann systemd[1]: Stopped Getty on tty2.

The logind forking piece suggests that @fbuihuu commit  ad96887a1205bad9656d280c5681f482e6d04838 might have something to do with it.

**Comment by poettering** [comment] 2018-12-25 15:11
so, what precisely are you doing? you temporarily upgrade a text login to graphical, and expect it to go back afterwards?

**Comment by aroig** [comment] 2018-12-25 15:17
> you temporarily upgrade a text login to graphical, and expect it to go back afterwards?

Yes.

**Comment by aroig** [comment] 2018-12-25 18:01
I confirm that reverting ad96887a1205bad9656d280c5681f482e6d04838 goes back to the desired behaviour. After the wayland compositor shuts down I go back to the text tty, without logind closing my session.

**Comment by aroig** [comment] 2018-12-25 19:54
Ah! looking at the code of ad96887a1205bad9656d280c5681f482e6d04838 it seems that it is actually intended behaviour! By kicking out the terminal controlling process, you actually end the session once the logind-forked process exits, isn't it? Did I understand correctly what is going on?

Can't the terminal hung problem be solved in a less drastic way? This is actually quite unexpected behaviour, as you tie the session lifetime to the process that did TakeControl, isn't it? At the very least it may deserve some documentation.

Also, even on a more traditional setup where a graphical login will spawn a graphical session, and there is no going back to text, wouldn't this new behaviour introduce a race on session closing? Consider the case where the login manager starts a process, say gnome-session, but the one that does TakeControl is a child of it. I'm not sure if gnome-session actually behaves this way, but it is a possible scenario, and I use gnome-session for illustration. Then, when the one that does TakeControl dies, logind may close the session while gnome-session may still be doing clean-up work.

**Comment by doverride** [comment] 2018-12-26 12:17
also applies to awesomewm

**Comment by fbuihuu** [comment] 2019-01-09 16:49
> Ah! looking at the code of [ad96887](https://github.com/systemd/systemd/commit/ad96887a1205bad9656d280c5681f482e6d04838) it seems that it is actually intended behaviour! By kicking out the terminal controlling process, you actually end the session once the logind-forked process exits, isn't it?

It's not really the intended behaviour... I unfortunately overlooked this case: logind isn't closing any session, it becomes the controlling terminal process and steals the terminal to login(1) in your case (since the compositor was started manually from a tty). login(1) probably receives the signal HUP and reacts by exiting hence your session is closed.

**Comment by fbuihuu** [comment] 2019-01-09 16:54
@poettering I'm not sure how this can be fixed properly... OTOH commit adb8688b3ff445d9c48e alone should be enough to fix issue #9754 ?

So maybe simply reverting ad96887a1205bad9656d280c5681f482e6d04838 is the way to go...

WDYT ?

**Comment by mrmazda** [comment] 2019-01-10 00:08
To be clear, this is not wayland only:
https://bugzilla.opensuse.org/show_bug.cgi?id=1120836

Another downstream:
https://bugzilla.redhat.com/show_bug.cgi?id=1663050

**Comment by keszybz** [comment] 2019-01-10 09:50
@fbuihuu Reverting  ad96887 and relying on adb8688 sounds good. Can you post a PR?

**Closed as completed** 2019-01-10 14:59 UTC
Labels: login

**Comment by drankinatty** [comment] 2019-01-10 19:11
I'm glad this is being fixed. I too boot to multi-user.target and then use the traditional `startx` to launch the desired xsession (either i3 or fluxbox). I do not expect to be logged out from my tty on xsession exit. (I've used this approach since at least 2002 on a half-dozen different distros) Thanks for the quick restoration of expected behavior.
