### ISSUE TITLE
DHCPv6 client is not started 

### ISSUE THREAD

**Issue by sunharis** [systemd/systemd#12255] opened 2019-04-09 06:31 UTC
**systemd version the issue has been seen with**
systemctl --version
systemd 241 (241-9-gc1f8ff8+)

My configuration file is as below.

cat /etc/systemd/network/00-eth0.network
[Match]
Name=eth0
[Network]
DHCP=yes >>> I tried with ipv6 also but didn't work.
IPv6AcceptRA=yes  >> it always set the /proc/sys/net/ipv6/conf/eth0/accept_ra to 0
DuplicateAddressDetection=yes
[DHCP]
ClientIdentifier=mac

 systemctl restart systemd-networkd
 cat /proc/sys/net/ipv6/conf/eth0/accept_ra
0

ip addr output

ip addr show
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether 72:e2:84:14:24:1b brd ff:ff:ff:ff:ff:ff
    inet 10.5.5.11/22 brd 10.5.7.255 scope global dynamic eth0
       valid_lft 38128sec preferred_lft 38128sec
    inet6 fe80::70e2:84ff:fe14:241b/64 scope link
       valid_lft forever preferred_lft forever

ip addr show output shows the link local address which suggest that ipv6 is enabled on the interface.

 ls -lrt /proc/net/if_inet6
-r--r--r--    1 root     root             0 Apr  9 06:09 /proc/net/if_inet6

if_inet6 is also present.

In the below traces I could have seen that DHCPv4 started and get the v4 address but v6 client didn't start at all.

###Systemd-networkd debug traces

eth0: Acquiring IPv4 link-local address
IPV4LL: Picked new IP address 169.254.36.40.
eth0: Acquiring DHCPv4 lease
DHCP CLIENT (0xd4f44d73): STARTED on ifindex 2
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=10 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
eth0: Setting addresses
DHCP CLIENT (0xd4f44d73): DISCOVER
lo: Link state is up-to-date
lo: Unmanaged
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_31 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=11 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
eth0: Removing address: 169.254.36.40/16 (valid forever)
eth0: Removing address: 10.5.5.11/22 (valid for 11h 57min 35s)
eth0: Addresses set
eth0: Setting routes
eth0: Routes set
IPV4ACD: Probing 169.254.36.40
DHCP CLIENT (0xd4f44d73): OFFER
DHCP CLIENT (0xd4f44d73): REQUEST (requesting)
DHCP CLIENT (0xd4f44d73): ACK
DHCP CLIENT (0xd4f44d73): lease expires in 11h 59min 58s
DHCP CLIENT (0xd4f44d73): T2 expires in 10h 29min 58s
DHCP CLIENT (0xd4f44d73): T1 expires in 6h
eth0: DHCPv4 address 10.5.5.11/22
eth0: Updating address: 10.5.5.11/22 (valid for 12h)
eth0: DHCP: No routes received from DHCP server: No data available
eth0: DHCP: No gateway received from DHCP server: No data available
IPV4ACD: Probing 169.254.36.40
IPV4ACD: Probing 169.254.36.40
IPV4ACD: ANNOUNCE

**Unexpected behavior you saw**

I was thinking that having the above configuration will start the DHCPv6 Client but I don't see anything in the debug traces.

**Steps to reproduce the problem**

Having the above network configuration file and restart the systemd-networkd

**Comment by ssahani** [comment] 2019-04-09 08:35
```IPv6AcceptRA=yes >> it always set the /proc/sys/net/ipv6/conf/eth0/accept_ra to 0```

networkd does not uses kernel's ndisc. It has it's own.


I cant reproduce this. You can try with my conf.

```
[root@Zeus network]# cat 12-veth.netdev
[NetDev]
Name=veth-test
Kind=veth

[Peer]
Name=veth-peer
[root@Zeus network]

[root@Zeus network]# cat veth0.network
[Match]
Name=veth-test

[Network]
DHCP=yes
DuplicateAddressDetection=yes
[root@Zeus network]# cat veth0-peer.network
[Match]
Name=veth-peer

[Network]
EmitLLDP=yes
IPv6PrefixDelegation=yes

[IPv6Prefix]
Prefix=2002:da8:1:0::/64
PreferredLifetimeSec=1000s
ValidLifetimeSec=2100s
```

log
```
NDISC: Started IPv6 Router Solicitation client
veth-peer: Sending LLDP packet...
NDISC: Sent Router Solicitation, next solicitation in 4s
veth-test: Adding route: dst: fe80::88a6:1cff:fe3f:a61a/128, src: n/a, gw: n/a, prefsrc: n/a
LLDP: Successfully processed LLDP datagram.
DHCP CLIENT (0x40ec5c50): DISCOVER
veth-peer: Adding address: fe80::78cb:afff:fe27:804e/64 (valid forever)
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_321 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=40 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
veth-peer: Gained IPv6LL
veth-peer: Discovering IPv6 routers
NDISC: Started IPv6 Router Solicitation client
veth-peer: Starting IPv6 Router Advertisements
RADV: Started IPv6 Router Advertisement daemon
veth-peer: Requesting DHCPv6 prefixes to be delegated for new link
RADV: Next Router Advertisement in 7s
NDISC: Sent Router Solicitation, next solicitation in 3s
veth-peer: Adding route: dst: fe80::78cb:afff:fe27:804e/128, src: n/a, gw: n/a, prefsrc: n/a
NDISC: Received Router Advertisement: flags none preference medium lifetime 0 sec
NDISC: Invoking callback for 'router' event.
veth-test: Configuring route: dst: 2002:da8:1::/64, src: n/a, gw: n/a, prefsrc: n/a
veth-test: Updating route: dst: 2002:da8:1::/64, src: n/a, gw: n/a, prefsrc: n/a
veth-test: Updating address: 2002:da8:1:0:88a6:1cff:fe3f:a61a/64 (valid for 35min)
veth-peer: Sending LLDP packet...
DHCP CLIENT (0x40ec5c50): DISCOVER
LLDP: Successfully processed LLDP datagram.
veth-peer: Sending LLDP packet...
LLDP: Successfully processed LLDP datagram.
veth-test: Updating address: 2002:da8:1:0:88a6:1cff:fe3f:a61a/64 (valid for 34min 59s)
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_322 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=41 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
veth-test: Adding route: dst: 2002:da8:1:0:88a6:1cff:fe3f:a61a/128, src: n/a, gw: n/a, prefsrc: n/a
veth-peer: Sending LLDP packet...
LLDP: Successfully processed LLDP datagram.


```

**Comment by sunharis** [comment] 2019-04-09 10:19
I don't have netdev. I don't have peer.network file. I only have the network file.

I modified the network file by adding 
DuplicateAddressDetection=yes
EmitLLDP=yes
IPv6PrefixDelegation=yes

Still the same behavior is seen. The logs are below.

eth0: Discovering IPv6 routers
NDISC: Started IPv6 Router Solicitation client
eth0: Starting IPv6 Router Advertisements
RADV: Started IPv6 Router Advertisement daemon
eth0: Requesting DHCPv6 prefixes to be delegated for new link
RADV: Next Router Advertisement in 9s
NDISC: Sent Router Solicitation, next solicitation in 4s
lo: Link state is up-to-date
lo: Unmanaged
eth0: Removing address: 10.5.5.12/22 (valid for 11h 51min 37s)
Could not emit changed OperationalState: Transport endpoint is not connected
NDISC: Sent Router Solicitation, next solicitation in 7s
LLDP: Invoking callback for 'added' event.
LLDP: Successfully processed LLDP datagram.
RADV: Next Router Advertisement in 15s
NDISC: Sent Router Solicitation, next solicitation in 15s
NDISC: No RA received before link confirmation timeout

**Comment by ssahani** [comment] 2019-04-09 11:28
>I don't have netdev. I don't have peer.network file. 

This is a test scenario I gave you.

>I only have the network file. I already have a DHCPv6 server configured

Am I missing something. Should not be a "Router Advertisement Daemon"

http://www.rjsystems.nl/en/2100-dhcpv6-stateful-autocfg.php


From your log you not receiving any RA see.
```
RADV: Next Router Advertisement in 15s
NDISC: Sent Router Solicitation, next solicitation in 15s
NDISC: No RA received before link confirmation timeout
```

**Comment by sunharis** [comment] 2019-04-09 13:21
My system needs a stateful DHCPv6. The DHCP server which i have used for my setup , works good with another server which uses the standalone dhcpv6 client. I am facing issue at the system which uses the systemd-networkd for the network.

**Comment by ratagupt** [comment] 2019-04-09 15:37
@ssahani does that mean that if the auto conf router is not there in the network then DHCPV6 client will not be able to get the DHCPV6 IP address from the DHCPV6 server.

**Comment by ssahani** [comment] 2019-04-10 07:38
>@ssahani does that mean that if the auto conf router is not there in the network then DHCPV6 client will not be able to get the DHCPV6 IP address from the DHCPV6 server

Yes. 
https://community.arubanetworks.com/t5/Controller-Based-WLANs/Explain-the-M-and-O-bit-in-IPv6-DHCP-server-configuration-What/ta-p/177442
https://www.youtube.com/watch?v=6g_DEcwNgp0

>I asked this even in my setup where dhclinet v6 runs, i don't have the auto config router there and it gets the IP from the dhcp server.

Not sure how dhclient works.

**Comment by ssahani** [comment] 2019-04-10 16:47
Can we close this ?

**Comment by sunharis** [comment] 2019-04-11 08:48
Sure Susant. I can now see the SOLICIT packets going out from the networkd. Thanks for your support.

**Comment by sunharis** [comment] 2019-04-15 09:52
Hi Susant,
Even after the Solicit packets going out of the dhcp client, the client is not getting the ipv6 address assigned.  Can you please help here by mentioning what i am missing in the client ? 

Below is the logs from the system-networkd after  a restart. 

DHCPv6 CLIENT: Sent SOLICIT
DHCPv6 CLIENT: Next retransmission in 9s
NDISC: No RA received before link confirmation timeout
NDISC: Invoking callback for 'timeout' event.
NDISC: Received Router Advertisement: flags MANAGED preference medium lifetime 300 sec
NDISC: Invoking callback for 'router' event.
eth0: Acquiring DHCPv6 lease on NDisc request
DHCPv6 CLIENT: Sent SOLICIT
DHCPv6 CLIENT: Next retransmission in 18s
DHCPv6 CLIENT: IA NA T1 60s > T2 30s
DHCPv6 CLIENT: Recv ADVERTISE
LLDP: Invoking callback for 'added' event.
LLDP: Successfully processed LLDP datagram.
NDISC: Received Router Advertisement: flags MANAGED preference medium lifetime 300 sec
NDISC: Invoking callback for 'router' event.
eth0: Acquiring DHCPv6 lease on NDisc request

The DHCP server i am using is working good with another non-systemd dhcp client.

**Comment by sunharis** [comment] 2019-04-16 05:07
The dhcpv6 client is only able to get the auto conf address. 

I have the below configuration at my networkd file:
[Match]
Name=eth0
[Network]
LinkLocalAddressing=yes
DHCP=yes
IPv6AcceptRA=false
[DHCP]
ClientIdentifier=duid
DUIDType=link-layer-time

The radvd file:
{
        AdvSendAdvert on;
        AdvManagedFlag on;
        AdvOtherConfigFlag on;
        MinRtrAdvInterval 30;
        MaxRtrAdvInterval 100;
        prefix 3ffe:501:ffff:101::/64
        {
               AdvOnLink off;
               AdvRouterAddr on;
        };

};

the ip assignment at the client is as below:
eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether 72:e2:84:14:24:1b brd ff:ff:ff:ff:ff:ff
    inet 169.254.36.40/16 brd 169.254.255.255 scope link eth0
       valid_lft forever preferred_lft forever
    inet 10.5.5.15/22 brd 10.5.7.255 scope global dynamic eth0
       valid_lft 43060sec preferred_lft 43060sec
    inet6 3ffe:501:ffff:101:70e2:84ff:fe14:241b/64 scope global dynamic
       valid_lft 86393sec preferred_lft 14393sec
    inet6 fe80::70e2:84ff:fe14:241b/64 scope link
       valid_lft forever preferred_lft forever

**Comment by sunharis** [comment] 2019-04-17 14:33
Any updates?

**Comment by ssahani** [comment] 2019-04-17 14:54
Can you use this test scenario
https://src.fedoraproject.org/rpms/wide-dhcpv6/blob/master/f/tests/dhcp6s and
replace client with networkd. Paste the networkd logs also the wireshark
dump.

**Comment by sunharis** [comment] 2019-04-17 14:57
Thanks Susanth. I will do this and update you with the data.

**Comment by sunharis** [comment] 2019-04-25 05:13
By using the wide-dhcpv6 server , I am still seeing the same behaviour.

I used the below DHCPv6 server:

root       929     1  0 Apr23 ?        00:00:00 dhcp6s -c /etc/wide-dhcpv6-20080615/dhcp6s.conf enp11s0f1

The server side interface was configured like below:

enp11s0f1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether e4:1f:13:63:13:76 brd ff:ff:ff:ff:ff:ff
    inet 10.5.5.1/24 brd 10.5.5.255 scope global enp11s0f1
       valid_lft forever preferred_lft forever
    inet6 3ffe:501:ffff:101::1234/64 scope global
       valid_lft forever preferred_lft forever
    inet6 3ffe:501:ffff:101::132/128 scope global dynamic
       valid_lft 2433263sec preferred_lft 446063sec
    inet6 fe80::62e2:d540:c8c5:d9c6/64 scope link
       valid_lft forever preferred_lft forever

Below is my client network interface config file:

[Match]
Name=eth0
[Network]
LinkLocalAddressing=yes
DHCP=yes
DuplicateAddressDetection=yes
[DHCP]
ClientIdentifier=duid
DUIDType=link-layer

Below is the networkd traces in the client:

Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=13 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
DHCPv6 CLIENT: Sent SOLICIT
DHCPv6 CLIENT: Next retransmission in 2s
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=14 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
eth0: DHCP: No routes received from DHCP server: No data available
eth0: DHCP: No gateway received from DHCP server: No data available
IPV4ACD: Probing 169.254.36.40
DHCPv6 CLIENT: Sent SOLICIT
DHCPv6 CLIENT: Next retransmission in 4s
IPV4ACD: Probing 169.254.36.40
IPV4ACD: ANNOUNCE
eth0: IPv4 link-local claim 169.254.36.40
eth0: Updating address: 169.254.36.40/16 (valid forever)
eth0: Configured
Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=15 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
DHCPv6 CLIENT: Sent SOLICIT
DHCPv6 CLIENT: Next retransmission in 8s
IPV4ACD: ANNOUNCE
NDISC: No RA received before link confirmation timeout
NDISC: Invoking callback for 'timeout' event.
DHCPv6 CLIENT: Sent SOLICIT
DHCPv6 CLIENT: Next retransmission in 17s

**Comment by ssahani** [comment] 2019-04-25 07:06
can't reproduce 
```
NDISC: Received Router Advertisement: flags MANAGED preference medium lifetime 1800 sec
NDISC: Invoking callback for 'router' event.
veth-test: Acquiring DHCPv6 lease on NDisc request
veth-test: Configuring route: dst: n/a, src: n/a, gw: fe80::1:2ff:fe03:409, prefsrc: n/a
veth-test: Configuring route: dst: 2001:888:db8:1::/64, src: n/a, gw: n/a, prefsrc: n/a
NDISC: Received Router Advertisement: flags MANAGED preference medium lifetime 1800 sec
NDISC: Invoking callback for 'router' event.
veth-test: Acquiring DHCPv6 lease on NDisc request
veth-test: Configuring route: dst: n/a, src: n/a, gw: fe80::1:2ff:fe03:409, prefsrc: n/a
veth-test: Configuring route: dst: 2001:888:db8:1::/64, src: n/a, gw: n/a, prefsrc: n/a
DHCPv6 CLIENT: Timeout T1
DHCPv6 CLIENT: Sent RENEW
DHCPv6 CLIENT: Next retransmission in 9s
DHCPv6 CLIENT: T1 expires in 4s
DHCPv6 CLIENT: T2 expires in 8s
veth-test: DHCPv6 address 2001:888:db8:1::1000/128 timeout preferred 10 valid 10
DHCPv6 CLIENT: Recv REPLY
veth-test: Updating address: 2001:888:db8:1::1000/128 (valid for 10s)
DHCPv6 CLIENT: Timeout T1
NDISC: No RA received before link confirmation timeout
NDISC: Invoking callback for 'timeout' event.
DHCPv6 CLIENT: Sent RENEW
DHCPv6 CLIENT: Next retransmission in 10s
DHCPv6 CLIENT: T1 expires in 5s
DHCPv6 CLIENT: T2 expires in 8s
veth-test: DHCPv6 address 2001:888:db8:1::1000/128 timeout preferred 10 valid 10
DHCPv6 CLIENT: Recv REPLY
veth-test: Updating address: 2001:888:db8:1::1000/128 (valid for 10s)
DHCPv6 CLIENT: Timeout T1
DHCPv6 CLIENT: Sent RENEW
DHCPv6 CLIENT: Next retransmission in 9s
DHCPv6 CLIENT: T1 expires in 5s
DHCPv6 CLIENT: T2 expires in 7s
veth-test: DHCPv6 address 2001:888:db8:1::1000/128 timeout preferred 10 valid 10
DHCPv6 CLIENT: Recv REPLY
veth-test: Updating address: 2001:888:db8:1::1000/128 (valid for 10s)
DHCPv6 CLIENT: Timeout T2
DHCPv6 CLIENT: Timeout T1
DHCPv6 CLIENT: Sent RENEW
DHCPv6 CLIENT: Next retransmission in 9s
DHCPv6 CLIENT: T1 expires in 4s
DHCPv6 CLIENT: T2 expires in 7s
veth-test: DHCPv6 address 2001:888:db8:1::1000/128 timeout preferred 10 valid 10
DHCPv6 CLIENT: Recv REPLY
veth-test: Updating address: 2001:888:db8:1::1000/128 (valid for 10s)


```

```
24: veth-test@veth-peer: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 02:01:02:03:04:08 brd ff:ff:ff:ff:ff:ff
    inet6 2001:888:db8:1::1000/128 scope global dynamic noprefixroute 
       valid_lft 1sec preferred_lft 1sec
    inet6 fe80::1:2ff:fe03:408/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by sunharis** [comment] 2019-04-25 08:32
What different configuration you have to get the "Configuring route:" ? I am getting until there , but this is not happening in my networkd client.
I have a stand alone server running the dhcpv6 server. I don't have the server running in the same system

**Comment by sunharis** [comment] 2019-04-25 09:15
I keep getting the below traces.

NDISC: Received Router Advertisement: flags MANAGED preference medium lifetime 1800 sec
NDISC: Invoking callback for 'router' event.
eth0: Acquiring DHCPv6 lease on NDisc request

DHCPv6 CLIENT: Sent SOLICIT
DHCPv6 CLIENT: Next retransmission in 1min 54s
LLDP: Invoking callback for 'refreshed' event.
LLDP: Successfully processed LLDP datagram.
LLDP: Invoking callback for 'refreshed' event.
LLDP: Successfully processed LLDP datagram.
LLDP: Invoking callback for 'refreshed' event.
LLDP: Successfully processed LLDP datagram.

**Comment by ssahani** [comment] 2019-04-25 10:15
seems you dhcpv6 server is not responding and something not right conf.
```
NDISC: Received Router Advertisement: flags MANAGED preference medium lifetime 1800 sec
NDISC: Invoking callback for 'router' event.
eth0: Acquiring DHCPv6 lease on NDisc request

DHCPv6 CLIENT: Sent SOLICIT
DHCPv6 CLIENT: Next retransmission in 1min 54s
LLDP: Invoking callback for 'refreshed' event.
```
Please follow the test I suggested you. This can be done in one machine since a veth interface. Again can't reproduce with current git.

**Comment by sunharis** [comment] 2019-04-26 08:07
I updated the radvd in the server to the latest version , and made some changes in the dhcp server configuration files. I see that intermittently I am getting the IP assigned. But not always after a networkd restart.

**Closed as completed** 2019-05-10 09:27 UTC
Labels: network, dhcp

**Comment by ssahani** [comment] 2019-05-10 09:57
ok thanks .
