### ISSUE TITLE
5da38d0 breaks initialization of systemd in systemd-nspawn containers

### ISSUE THREAD

**Issue by eliasp** [systemd/systemd#4173] opened 2016-09-17 14:17 UTC
### Submission type
- Bug report
### systemd version the issue has been seen with

> git/master 5da38d0 and later
### Used distribution

> Gentoo (Host), Ubuntu 16.04/systemd 229 (Guest)
### In case of bug report: Expected behaviour you didn't see

> Booting a systemd-nspawn container using `-b`/`--boot` won't work anymore.
### In case of bug report: Unexpected behaviour you saw

> Since 5da38d0 booting a systemd-nspawn container (e.g. using Ubuntu 16.04 with systemd 229 in the container) fails:

```
moria ~ # systemd-nspawn -bxD /var/lib/machines/ubuntu-xenial-salt
Spawning container ubuntu-xenial-salt-2bb8317faa949977 on /var/lib/machines/.#machine.ubuntu-xenial-salt45a484ed93981a61.
Press ^] three times within 1s to kill container.
systemd 229 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN)
Detected virtualization systemd-nspawn.
Detected architecture x86-64.  

Welcome to Ubuntu 16.04 LTS!  

Failed to install release agent, ignoring: No such file or directory
Failed to create /init.scope control group: Read-only file system
Failed to allocate manager object: Read-only file system
[!!!!!!] Failed to allocate manager object, freezing.
Freezing execution.
```
### In case of bug report: Steps to reproduce the problem

> Install systemd 5da38d0 or later on the host
> Try to start an Ubuntu 16.04 container (other OS might work as well) using the `--boot`/`-b` param: `systemd-nspawn -bxD /var/lib/machines/ubuntu-xenial-salt`

**Comment by evverx** [comment] 2016-09-17 14:27
Duplicate of https://github.com/systemd/systemd/issues/4008

**Closed as completed by evverx** 2016-09-17 14:27 UTC
Labels: cgroups, pid1, duplicate

**Comment by evverx** [comment] 2016-09-17 15:00
There is a workaround:

``` sh
UNIFIED_CGROUP_HIERARCHY=no systemd-nspawn ...
```

**Comment by wsw70** [comment] 2016-10-06 15:18
@evverx Could you please elaborate on how to use this workaround?

**Comment by wsw70** [comment] 2016-10-06 15:35
@evverx Is there a way to use this workaround in service units? It works from the command line but when I tried to add it in `ExecStart` but I get 

```
root@srv /v/l/machines# systemctl status systemd-nspawn@vpnin -l
● systemd-nspawn@vpnin.service - Container vpnin
   Loaded: error (Reason: Invalid argument)
   Active: failed (Result: timeout) since Thu 2016-10-06 17:31:09 CEST; 3min 28s ago
     Docs: man:systemd-nspawn(1)
 Main PID: 3578 (code=killed, signal=KILL)
   Status: "Container running."

Oct 06 17:29:49 srv systemd[1]: [/lib/systemd/system/systemd-nspawn@.service:17] Executable path is not absolute, ignoring: UNIFIED_CGROUP_HIERARCHY=no /u
Oct 06 17:29:49 srv systemd[1]: systemd-nspawn@vpnin.service: Service lacks both ExecStart= and ExecStop= setting. Refusing.
```

I tried adding

```
[Service]
Environment=UNIFIED_CGROUP_HIERARCHY=no
```

but it was not taken into account

**Comment by evverx** [comment] 2016-10-08 12:53
> it was not taken into account

@wsw70, this looks like #4181 (or, maybe, forgotten `systemctl daemon-reload`)
