### ISSUE TITLE
Default boot entry changed to last entry (ignoring loader.conf) after upgrade to v245

### ISSUE THREAD

**Issue by mmonaco** [systemd/systemd#15068] opened 2020-03-10 17:26 UTC
I set my default entry in `loader.conf`. After updating to `v245` and running `bootctl update` the default entry becomes the last sorted entry in `entries/`. To work around this, I needed to do `bootctl set-default` explicitly. My `loader.conf` setting appears to be ignored.

**Comment by mmonaco** [comment] 2020-03-12 13:07
I found the commit, 6cd12ebcfe459466257ea63022a32515d756e719. I guess this is intentional should have been in NEWS?

**Comment by Scrumplex** [comment] 2020-03-12 13:34
> should have at least been in NEWS?

I agree. The fix is trivial, by just adding .conf at the end

**Comment by mmonaco** [comment] 2020-03-12 22:17
(As an aside, what's the best way to clear what I set with `set-default`? Set it to the empty string, or can the efivar be removed completely?)

**Comment by ahkok** [comment] 2020-03-31 21:40
This is a regression, confirmed in ClearLinux. Adding `.conf` indeed fixes, but this is unfortunate for sure.

**Comment by eoli3n** [comment] 2020-11-17 15:28
Any update on this ?

**Comment by lnicola** [comment] 2020-11-20 08:26
@eoli3n try changing `/boot/loader/loader.conf` to say `default entry.conf`.

**Comment by eoli3n** [comment] 2020-11-20 09:00
Its already like, its precisely what is not working
```
$ cat /efi/loader/loader.conf
default org.zectl-pacmanhook-20200523T162905.conf
timeout 3
password xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
 
$ cat /efi/loader/entries/org.zectl-pacmanhook-20200523T162905.conf
title           Arch Linux ZFS Default
linux           /env/org.zectl-pacmanhook-20200523T162905/vmlinuz-linux-lts
initrd          /env/org.zectl-pacmanhook-20200523T162905/intel-ucode.img
initrd          /env/org.zectl-pacmanhook-20200523T162905/initramfs-linux-lts.img
options         zfs=zroot/ROOT/pacmanhook-20200523T162905 rw 
```

**Comment by lnicola** [comment] 2020-11-20 09:01
Not sure then, it works for me.

**Comment by tz4678** [comment] 2021-04-29 05:15
i have the same problem

**Comment by tz4678** [comment] 2021-04-29 05:18
```bash
~/Downloads via 🐍 v3.9.4 took 2s 
λ ls /boot/loader/entries               
arch.conf  arch-lts.conf

~/Downloads via 🐍 v3.9.4 
λ grep default /boot/loader/loader.conf 
default       arch-lts
```

```bash
~/Downloads via 🐍 v3.9.4 
λ cat /boot/loader/entries/arch-lts.conf 
title    Arch Linux LTS
linux    /vmlinuz-linux-lts
initrd   /amd-ucode.img
initrd   /initramfs-linux-lts.img
initrd   /initramfs-linux-lts-fallback.img
options  root=PARTUUID=c2b3a2f3-cb76-47c1-8d13-51d7966959a5 rootflags=subvol=@ rw
```
not working too:

```
default  Arch Linux LTS
```

```bash
λ bootctl --version
systemd 248 (248-5-arch)
...
```

**Comment by lnicola** [comment] 2021-04-29 06:51
```diff
-default       arch-lts
+default       arch-lts.conf
```

**Comment by medhefgo** [comment] 2021-07-25 11:47
- Make sure sd-boot is up-to-date with `bootctl update`
- Run `bootctl set-default "your-entry-filename.conf"`
- `cp /sys/firmware/efi/efivars/LoaderEntryDefault-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f ~/default-bootctl.txt`
- Reboot into sd-boot, select your desired default entry and press 'd' until is says the default boot entry was set.
- `cp /sys/firmware/efi/efivars/LoaderEntryDefault-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f ~/default-sd-boot.txt`

After this, default selection should work properly. If it isn't, the copied files must differ, please provide a diff in that case.

**Comment by medhefgo** [comment] 2022-01-13 14:34
As already stated, the `default` option needs to match the full filename for the entry to be selected since https://github.com/systemd/systemd/commit/6cd12ebcfe459466257ea63022a32515d756e719. That means it has to end with '.efi' for stub entries or '.conf' otherwise.
It is an unfortunate regression, but was needed. I am not inclined to create a workaround for this either, so I will be closing this for now.

Any here that reported their default from no getting picked up, please make sure you are using systemd-boot v250, run `bootctl set-default ""` to delete the default EFI var or and make sure the default in `loader.conf` is the filename of your desired entry (or a glob like `arch*`).

And before reporting further problems on this, please make sure you are running an up-to-date systemd-boot by pressing `p` in the boot menu. That page will also report the values for config options it picks up as well as the IDs to use for specific boot entries.

**Closed as completed by medhefgo** 2022-01-13 14:34 UTC
Labels: bug 🐛, sd-boot/sd-stub/bootctl
