### ISSUE TITLE
Documentation: networkctl OPERATIONAL state

### ISSUE THREAD

**Issue by neophob** [systemd/systemd#9474] opened 2018-06-29 14:31 UTC
**Is your feature request related to a problem? Please describe.**
networkctl show the OPERATIONAL state of each interface. However I could not find a definition of the states. (check man page and https://wiki.freedesktop.org/www/Software/systemd/)

**Describe the solution you'd like**
Documentation of each state, for example what defines "routable". Does Systemd does a ping to the gateway? Or does it try to connect somehow to the internet (DNS, NTP..)

**Comment by keszybz** [comment] 2018-07-23 12:15
Duplicate of #575.

**Closed as completed by keszybz** 2018-07-23 12:15 UTC
Labels: network, documentation
