### ISSUE TITLE
"BindsTo=" must confirm that a device exists before enqueuing a start job on that device.

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#4413] opened 2016-10-19 20:59 UTC
- [ ] Bug report

> systemd 231-4
> 
> Arch
### In case of bug report: Steps to reproduce the problem

Given a template service unit file with BindsTo and WantedBy dependencies:

[Unit]
BindsTo= sys-subsystem-net-devices-%i.device
[Service]
ExecStart= /usr/bin/wpa_supplicant ...
[Install]
WantedBy= sys-subsystem-net-devices-%i.device

Where there are:
 $ ls -1 sys-subsystem-net-devices-wlp0s3f3u1.device.wants
 supplicant@wlp0s3f3u1.service

and
 $ ls -1 sys-subsystem-net-devices-wlp0s3f3u2.device.wants
 supplicant@wlp0s3f3u2.service

and where the two interface names are the names generated for the same device plugged into either one of two different USB sockets.

Plugging the USB network device into _either_ socket, creating just one of either wlp0s3f3u1 or wlp0s3f3u2, causes the supplicant to be started for _both_ interface names, wlp0s3f3u1 _and_ wlp0s3f3u2.

Ultimately, the error is tolerable because the supplicant will fail for the nonexistent network device interface, and then the corresponding service unit will time-out and fail.

But still, the service unit for the nonexistent device interface should _not_ have been started at all.

It appears that systemd is unable to distinguish USB network device interface names.

**Comment by arvidjaar** [comment] 2016-10-20 16:47
Enable systemd debug log level, plug in USB device and provide logs when it happens.

**Comment by thx1111** [comment] 2016-10-21 17:07
@arvidjaar
Thanks Andrey.
[plugjournaltrunc.txt](https://github.com/systemd/systemd/files/544821/plugjournaltrunc.txt)

I have set "systemd.log_level=debug" on the kernel command line, copied the journal from:
 journalctl -S "2016-10-20 17:22:12" -U "17:23:22" -o short-monotonic --no-hostname
and then truncated the output shortly after the two unit files are starting:
 wlp0s3f3u1@bond0
 wlp0s3f3u2@bond0

wlp0s3f3u2@bond0.service is starting from a failed state, since it was previously started at boot, even though, still, there was no such device installed, for interface wlp0s3f3u2.

The network device was unplugged from the USB port for interface wlp0s3f3u1, and then plugged back in.  The journal log begins right after the USB network device is plugged into 
the first USB Port, "Port 00".  The interface  wlp0s3f3u2 would be on "Port 01".  There is:
 $ usb-devices
 T:  Bus=01 Lev=00 Prnt=00 Port=00 Cnt=00 Dev#=  1 Spd=480 MxCh= 6
 D:  Ver= 2.00 Cls=09(hub  ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
 P:  Vendor=1d6b ProdID=0002 Rev=04.04
 S:  Manufacturer=Linux 4.4.26-1-lts ehci_hcd
 S:  Product=EHCI Host Controller
 S:  SerialNumber=0000:00:03.3
 C:  #Ifs= 1 Cfg#= 1 Atr=e0 MxPwr=0mA
 I:  If#= 0 Alt= 0 #EPs= 1 Cls=09(hub  ) Sub=00 Prot=00 Driver=hub

 T:  Bus=01 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#=  6 Spd=480 MxCh= 0 
 D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs= 1
 P:  Vendor=0846 ProdID=9041 Rev=02.00
 S:  Manufacturer=Realtek
 S:  Product=802.11n WLAN Adapter
 S:  SerialNumber=00e04c000001
 C:  #Ifs= 1 Cfg#= 1 Atr=a0 MxPwr=500mA
 I:  If#= 0 Alt= 0 #EPs= 4 Cls=ff(vend.) Sub=ff Prot=ff Driver=rtl8192cu

These unit files are installed with "WantedBy= sys-subsystem-net-devices-%p.device" and are pulled-in from:
 ls -1 sys-subsystem-net-devices-wlp0s3f3u1.device.wants
 supplicant@wlp0s3f3u1.service
 wlp0s3f3u1@bond0.service
and
 ls -1 sys-subsystem-net-devices-wlp0s3f3u2.device.wants
 supplicant@wlp0s3f3u2.service
 wlp0s3f3u2@bond0.service

Here, the file name is used to pass the physical device interface name.  It is a hard link to a file slave@.service which enslaves the interface to the bonding interface.

If you search the journal log from "less" with "Start|Stop|wlp0s3f3u2", notice the line:
[ 2423.629087] ip[2764]: Cannot find device "wlp0s3f3u2"

This is right after udevd has configured the other interface, wlp0s3f3u1, and before systemd has even begun to enqueue jobs.  I'm wondering if things have already gone wrong here.  While my unit files do use the ip command, none of those unit files have been started yet.

What is looking for this nonexistent device interface, and why?  And from where did it get that interface name, "wlp0s3f3u2"? What started that ip command, process 2764?  Did udevd do that?  Is this correct behavior?  Or is udevd causing the problem?  Let me know if you have some ideas about how to track that down.

The next thing I see is:
 [ 2423.795805] systemd[1]: wlp0s3f3u2@bond0.service: Installed new job wlp0s3f3u2@bond0.service/start as 815

and, of course, there is nothing interesting after that.  The error has already occurred, and systemd is just doing what it is suppose to do now.

**Comment by arvidjaar** [comment] 2016-10-22 07:04
Please provide full output of `systemctl show supplicant@wlp0s3f3u1.service supplicant@wlp0s3f3u2.service wlp0s3f3u1@bond0.service wlp0s3f3u2@bond0.service`

**Comment by thx1111** [comment] 2016-10-22 15:13
[show.txt](https://github.com/systemd/systemd/files/545852/show.txt)

**Comment by arvidjaar** [comment] 2016-10-22 16:46
OK, and please "udevadm info --export-db". So far it is indeed not clear what triggers both supplicant services.

**Comment by thx1111** [comment] 2016-10-22 17:21
[udevinfo.txt](https://github.com/systemd/systemd/files/545904/udevinfo.txt)

Hmm - the file contains no mention of the nonexistent network interface, wlp0s3f3u2.

Is there some way to capture the interaction between udevd and systemd when the device is plugged?

I tried setting udev_log="debug", but that did not seem to add anything useful in the log.

**Comment by arvidjaar** [comment] 2016-10-22 17:42
I was mostly interested in `SYSTEMD_WANTS`, but there are none on network interfaces. Could you provide full `systemctl show`, in case there are some weird dependency chains? Thank you!

**Comment by thx1111** [comment] 2016-10-22 17:53
I'm assuming that you mean `systemctl show '*'`:
[fullshow.txt](https://github.com/systemd/systemd/files/545928/fullshow.txt)

**Comment by arvidjaar** [comment] 2016-10-23 06:01
```
[ 2423.766535] systemd[1]: sys-subsystem-net-devices-wlp0s3f3u1.device: Changed dead -> plugged
[ 2423.796966] systemd[1]: sys-subsystem-net-devices-wlp0s3f3u2.device: Installed new job sys-subsystem-net-devices-wlp0s3f3u2.device/start as 817
```

And `sys-subsystem-net-devices-wlp0s3f3u2.device` has `Wants=supplicant@wlp0s3f3u2.service`.

This is triggered by this dependency chain (extra units trimmed):

```
Id=sys-subsystem-net-devices-wlp0s3f3u1.device
Wants=wlp0s3f3u1@bond0.service

Id=wlp0s3f3u1@bond0.service
Requires=master@bond0.service

Id=master@bond0.service
Wants=wlp0s3f3u2@bond0.service

Id=wlp0s3f3u2@bond0.service
BindsTo=sys-subsystem-net-devices-wlp0s3f3u2.device

Id=sys-subsystem-net-devices-wlp0s3f3u2.device
Wants=supplicant@wlp0s3f3u2.service
```

So pragmatic answer - this works as designed and to break dependency loop you need to use `SYSTEMD_WANTS` in udev rule instead of direct `Wants` on device unit.

Long answer. Devices are sufficiently different from normal units. In particular devices usually cannot be actively started (or stopped) - we can only passively wait for device to appear. So semantic of `BindsTo` being equal to `Requires` by actively attempting to _start_ device and propagating start request down the chain is _usually_ wrong - `Requisite` is much more appropriate here. OTOH there are cases when current semantic is useful (like running cryptsetup for cryptocontainer to appear). So I argue that overloading `BindsTo` with `Requires` semantic is wrong. `BindsTo` should mean what its name suggests and leave decision whether to actively start or passively wait to `Requires` or `Requisite` at discretion of unit author.

**Comment by thx1111** [comment] 2016-10-23 14:12
Thanks Andrey!

Please offer a little more background, for understanding this.  For context, my understanding, from the systemd.unit man page, and from communication from Lennart, is that `BindsTo` is - presently - required when working with "devices", where the man page says "... it also declares that this unit is stopped when any of the units listed suddenly disappears. Units can suddenly, unexpectedly disappear if ... a device is unplugged ... **without involvement of systemd**.", where "disappears" is, effectively, a specific term-of-art here.  Also - and leaving-out a lot of background - my understanding, based upon reading the man page, is that `BindsTo` is one of the dependencies from the group of dependencies I have classified as "Reverse Stop" dependencies, where "Reverse" refers to the idea that the "referred-to" unit is acting, rather than "this unit" is acting, when, in this case, the unit `sys-subsystem-net-devices-wlp0s3f3u2.device` "disappears".

So now, that part about which I am unclear - my understanding has been that `BindsTo` is _not_ one of the "Start" dependencies, and so a `BindsTo` dependency _should not_ mean that this unit will Start the referred-to unit, nor will the referred-to unit Start this unit.

Are you saying that, instead, presently, the `BindsTo` dependency _also_ creates a Start dependency?  That would be a problem.

More precisely, if I understand what you are describing, it seems that `BindsTo` is creating a "Reverse Start" dependency, where the referred-to unit, `sys-subsystem-net-devices-wlp0s3f3u2.device`, is propagating a Start to "this unit", `wlp0s3f3u2@bond0.service` and `supplicant@wlp0s3f3u2.service`, which each have `BindsTo` dependencies on the device `sys-subsystem-net-devices-wlp0s3f3u2.device`.  Is that what is happening here?

And do I understand correctly that you argue that that is the wrong behavior.  I will agree.  systemd imposes some difficulty in not having a _complete_ set of independent "Forward" and "Reverse" Start and Stop dependency control words, specifically missing an independent "Forward Stop" dependency, necessitating a kind of "Reverse Reverse Stop" approach instead, using `RequiredBy`.  Nonetheless, for each unit, systemd requires that there must exist a specific Start and a specific Stop dependency, in order for proper Start and Stop ordering to operate.  In the case of these two unit files, the specific Start dependency is the "Revere Start" `WantedBy` dependency, upon the device `sys-subsystem-net-devices-wlp0s3f3u2.device`.  The theory is that, when the "referred-to" unit, the device, "appears",  then "this unit" will be started.  This is the intended semantics of the `WantedBy` Start dependency and the `BindsTo` Stop dependency, and the reason for their pairing.

I just want to be clear about the connection _between_ the two similar devices, `wlp0s3f3u1` and `wlp0s3f3u2`.  You are showing `master@bond0.service Wants=wlp0s3f3u2@bond0.service`.  That comes from the "Reverse Start" `WantedBy` dependency in `wlp0s3f3u2@bond0.service`, so that starting the bonding master interface will then start the units which enslave the slave interfaces.  Then, the dependency chain has `wlp0s3f3u2@bond0.service BindsTo=sys-subsystem-net-devices-wlp0s3f3u2.device`.  Now, that is not _suppose_ to be a Start dependency.  But then, this is where everything goes wrong, because systemd is - presently - propagating `BindsTo` as a Start dependency.  Yeah, that's messed-up.

And, I should point-out that _neither_ of the two units, not the enslaving service unit `wlp0s3f3u2@bond0.service`, and not the supplicant service unit `supplicant@wlp0s3f3u2.service`, should be started here, when the other device, `wlp0s3f3u1` is plugged.  So this is not just about the supplicant being started when it should not.

I went back and looked at the complete log file again, and I see there is a line:
 `[ 2424.035194] systemd[1]: wlp0s3f3u2@bond0.service: Forked /usr/bin/ip as 2764`
which explains the earlier line:
 `[ 2423.629087] ip[2764]: Cannot find device "wlp0s3f3u2"`
I don't understand why the time stamps are so "inverted".  I guess the journal takes some time to "catch-up" with systemd running with debug logging.  The time reversal in the log was just unexpected, and I do not actually understand the meaning of `journalctl -o short-monotonic`.

Hmm - so now what?  How do we fix this `BindsTo` issue?

**Comment by arvidjaar** [comment] 2016-10-23 16:48
> Are you saying that, instead, presently, the BindsTo dependency also creates a Start dependency?

Yes. I guess everyone fell in this trap once. `BindsTo` is really `Requires` + some sugar on top.

**Comment by thx1111** [comment] 2016-10-23 17:51
Can we fix this?  The essential mechanism here is a dependency word that creates a Reverse Stop dependency on the "disappears" action, as distinct from the "deactivates" action.  `Requires` creates both a Forward Start, when "this unit" is activated, and a Reverse Stop, when the "referred-to" unit is "deactivated".

Hmm - according to the chart I have made, `Requisite` also provides a Reverse Stop dependency function, without any other Forward or Reverse Start or Stop action, but only responds to a "deactivation", and not to a "disappearance".

How about re-basing `BindsTo` on `Requisite`, instead of `Requires`, except with the "disappearance" trigger?

Hmm - would `Requisite` always be doing the "right thing" if it _also_ responded to a "disappearance", as well as to a "deactivation"?  That could be another approach.  And that might be an easier fix.  Then `Requisite=sys-subsystem-net-devices-%i.device` could be used instead of `BindsTo`.

Otherwise, there exists another "missing" systemd dependency function...

Hmm - you say some people are actually using the Forward Start function in `BindsTo` - cryptsetup for cryptocontainer?  So, if `BindsTo` is "fixed", then those people would have to add an explicit `Wants` or `Requires` dependency.  But then, if `Requisite` is "fixed" some people will want to change all instances of `BindsTo` to `Requisite`, to avoid that "parasitic" Forward Start, assuming that there are no problems caused by combining "deactivations" and "disappearances" for the Reverse Stop.  Would that impact a larger number of people?  In that case it might be better to just fix `BindsTo`.

**Comment by thx1111** [comment] 2016-10-23 23:20
It occurred to me to try combining `Requisite` and `BindsTo`, to block the "parasitic" Forward Start dependency, but then, I notice two things:

1) Adding `Requisite=sys-subsystem-net-devices-wlp0s3f3u2.device` to both `wlp0s3f3u2@bond0.service` and `supplicant@wlp0s3f3u2.service` seems to have no effect whatsoever, and

2) where there is `wlp0s3f3u2@bond0.service BindsTo=sys-subsystem-net-devices-wlp0s3f3u2.device` in the dependency chain,  this is _not_ a Forward Start dependency, as implied by comparing `BindsTo` to `Requires`, and which would imply that starting `wlp0s3f3u2@bond0.service` would Start `sys-subsystem-net-devices-wlp0s3f3u2.device`.  Instead, what is seen happening is a Reverse Start dependency, which should have nothing to do with `BindsTo`, regardless of how it is implemented.  The theory from the dependency chain being that `master@bond0.service Wants=wlp0s3f3u2@bond0.service` is interpreted as `master@bond0.service` "starting" `wlp0s3f3u2@bond0.service`.  That is a different thing.

Now, `wlp0s3f3u2@bond0.service` _does_ have a `WantedBy=sys-subsystem-net-devices-wlp0s3f3u2.device`, which will create a `sys-subsystem-net-devices-wlp0s3f3u2.device
Wants=wlp0s3f3u2@bond0.service`, which was not mentioned in the dependency chain shown above.

So then, the "crazy-making" thing in the dependency chain does _not_ actually seem to be in the `BindsTo` dependency, but instead is further up the dependency chain, at `wlp0s3f3u1@bond0.service Requires=master@bond0.service`.  It would seem to me that the problem at that step in the dependency chain is that `master@bond0.service` is _already running_.  And so there is no reason to "start" it.  And so, the dependency chain should have been interrupted and ended right there.

Is there some reason that this dependency chain continues past `wlp0s3f3u1@bond0.service Requires=master@bond0.service`?

And, of course, even if the dependency chain _does_ continue past there, there is still the issue that the device `sys-subsystem-net-devices-wlp0s3f3u2.device` _does not exist_.  And now we are back to the idea that `BindsTo` should have some concept of a nonexistent device.

In which case, the solution would be to add a step in the `BindsTo` logic to check that the `BindsTo` unit actually exists, before continuing.

**Comment by thx1111** [comment] 2016-11-01 16:31
Perhaps another thing to check - if systemd were to mistakenly agglomerate all of the file names hard-linked to slave@.service, the effect would be the same.

In this case, there are three files hard-linked to slave@: enp0s7@.service, wlp0s3f3u1@.service, and wlp0s3f3u1@.service.  enp0s7@.service is already running, so would be ignored.  wlp0s3f3u1@.service would be started, as intended, so looks normal.  And then trying to start wlp0s3f3u2@.service would appear as the only error, even though the actual error would have been in confusing these three service units.

It is hard to tell, since only systemd actions are shown in the debug log. It's like showing a conclusion without showing the minor and major premises in a syllogism.  You know that the conclusion is wrong, but cannot say how the error was made.

**Comment by thx1111** [comment] 2016-11-14 20:09
Here's another way to look at the problem - I thought to add an explicit
 Requisite=sys-subsystem-net-devices-wlp0s3f3u2.device
to the service unit file.  And then, we can view
 systemd-analyze --require dot supplicant@wlp0s3f3u2.service

This now shows:
 "sys-subsystem-net-devices-wlp0s3f3u2.device"->"supplicant@wlp0s3f3u2.service" [color="grey66"];
 "supplicant@wlp0s3f3u2.service"->"sysinit.target" [color="black"];
 "supplicant@wlp0s3f3u2.service"->"system-supplicant.slice" [color="black"];
 "supplicant@wlp0s3f3u2.service"->"sys-subsystem-net-devices-wlp0s3f3u2.device" [color="darkblue"];
 "supplicant@wlp0s3f3u2.service"->"network.target" [color="grey66"];
 "supplicant@wlp0s3f3u2.service"->"shutdown.target" [color="red"];

And,
$ systemctl status sys-subsystem-net-devices-wlp0s3f3u2.device
● sys-subsystem-net-devices-wlp0s3f3u2.device
   Loaded: loaded
   Active: inactive (dead)

So now, if you believe "systemd-analyze" and "systemctl status", there should be no way for the supplicant@wlp0s3f3u2.service to start.

Instead, unplugging and plugging the alternate device, wlp0s3f3u1, still results in systemd trying to start the unit files for wlp0s3f3u2.

So, here is another view of the problem - what does it take to violate the Requisite dependency?

**Comment by thx1111** [comment] 2016-11-18 04:02
It turns out that this is a "show stopper" bug when any kind of target unit is "RequiredBy" these removable devices:

 supplicant@.service
 Wants= network.target
 Before= network.target
 After= something.target
 ...
 RequiredBy=something.target

So then, when systemd tries to erroneously start the unit it should not be starting - supplicant@wlp0s3f3u2.service in this example - first, the entire system start-up hangs, waiting the DefaultTimeoutStartSec for the nonexistent device to start, and then, when that start-up fails, the network fails to start because of the After=something.target dependency, and then the the entire system is hung, where the network.target ordering has the After= dependency:

systemd-user-sessions.service
After=...network.target

A bug that can block systemd-user-sessions.service and makes target units unusable in some circumstances is serious.

**Comment by poettering** [comment] 2017-05-12 13:11
I will close this now, as the requested behaviour contradicts the intended behaviour of BindsTo.

**Closed as completed by poettering** 2017-05-12 13:11 UTC
Labels: pid1
