### ISSUE TITLE
nspawn reboot: machine already exists

### ISSUE THREAD

**Issue by jengelh** [systemd/systemd#7681] opened 2017-12-17 22:36 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 235

### Used distribution

> Debian sid

### In case of bug report: Expected behaviour you didn't see

> successful auto restart of the nspawn container

### In case of bug report: Unexpected behaviour you saw

When nspawn runs as a system service, a restart of the container (issued from inside with `reboot` our outside with `machinectl reboot foo`) leads to machinectl not noticing that the container ended before systemd restarts nspawn.

```
# journalctl -fu systemd-nspawn@foo
# machinectl reboot foo
23:29:25 systemd-nspawn[1630]: foo login: [  OK  ] Stopped target Graphical Interface.
[..]
23:29:25 systemd-nspawn[1630]: [  OK  ] Reached target Unmount All Filesystems.
23:29:25 systemd-nspawn[1630]: [  OK  ] Stopped target Local File Systems (Pre).
23:29:25 systemd-nspawn[1630]: [  OK  ] Stopped Remount Root and Kernel File Systems.
23:29:25 systemd-nspawn[1630]: [  OK  ] Reached target Shutdown.
23:29:25 systemd[1]: systemd-nspawn@foo.service: Service hold-off time over, scheduling restart.
23:29:25 systemd[1]: systemd-nspawn@foo.service: Scheduled restart job, restart counter is at 1.
23:29:25 systemd[1]: Stopped Container foo.
23:29:25 systemd[1]: Starting Container foo...
23:29:26 systemd-nspawn[1860]: Failed to register machine: Machine 'foo' already exists
23:29:26 systemd-nspawn[1860]: Parent died too early
23:29:26 systemd[1]: systemd-nspawn@foo.service: Main process exited, code=exited, status=1/FAILURE
23:29:26 systemd[1]: systemd-nspawn@foo.service: Failed with result 'exit-code'.
23:29:26 systemd[1]: Failed to start Container foo.
```

**Comment by federico-cuello-sociomantic** [comment] 2018-02-06 14:24
Looks like duplicate of https://github.com/systemd/systemd/issues/2809

**Closed as completed** 2018-07-09 01:30 UTC
Labels: nspawn, duplicate
