### ISSUE TITLE
Add logical NOT support to journalctl

### ISSUE THREAD

**Issue by bl33pbl0p** [systemd/systemd#8167] opened 2018-02-13 11:50 UTC
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

236

### Used distribution

Exherbo Linux

### RFE

It seems currently there is no way to express a logic where all entries except the ones from, say, _SYSTEMD_UNIT=session-3.scope are shown. It would be nice if some way to negate fields is supported. Note that this would be even better if it could be applied to combinations of AND and OR, maybe something like ![_PID=1 _SYSTEMD_UNIT=foobar.service] or ![_PID=1 + _SYSTEMD_UNIT=foobar.service] (The syntax is just an example, there might be much better ways to express the same).

**Comment by poettering** [comment] 2018-02-13 12:07
Duplicate of #2720

**Closed as completed by poettering** 2018-02-13 12:07 UTC
Labels: journal, duplicate
