### ISSUE TITLE
systemctl set-property --runtime user-$UID.slice CPUQuota=50% has no effect when the CPU controller is not enabled in that slice (duplicate??)

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#9733] opened 2018-07-26 22:52 UTC
**systemd version the issue has been seen with**

239

**Used distribution**

Debian testing (buster)

**Expected behaviour you didn't see**

Assume the unified cgroup hierarchy.

```
systemctl set-property --runtime user-$UID.slice "CPUQuota=50%" 
```

sets `/sys/fs/cgroup/user.slice/user-$UID.slice/cpu.max` with a reasonable content.

**Unexpected behaviour you saw**

Firstly, the files of `user-1001.slice` are:

```
root@letsnote2:/var/tmp# ls -l /sys/fs/cgroup/user.slice/user-1001.slice
total 0
-r--r--r-- 1 root   root   0 Jul 27 07:38 cgroup.controllers
-r--r--r-- 1 root   root   0 Jul 27 07:38 cgroup.events
-rw-r--r-- 1 root   root   0 Jul 27 07:38 cgroup.max.depth
-rw-r--r-- 1 root   root   0 Jul 27 07:38 cgroup.max.descendants
-rw-r--r-- 1 root   root   0 Jul 27 07:38 cgroup.procs
-r--r--r-- 1 root   root   0 Jul 27 07:38 cgroup.stat
-rw-r--r-- 1 root   root   0 Jul 27 07:37 cgroup.subtree_control
-rw-r--r-- 1 root   root   0 Jul 27 07:38 cgroup.threads
-rw-r--r-- 1 root   root   0 Jul 27 07:38 cgroup.type
-r--r--r-- 1 root   root   0 Jul 27 07:38 cpu.stat
-r--r--r-- 1 root   root   0 Jul 27 07:38 memory.current
-r--r--r-- 1 root   root   0 Jul 27 07:38 memory.events
-rw-r--r-- 1 root   root   0 Jul 27 07:38 memory.high
-rw-r--r-- 1 root   root   0 Jul 27 07:38 memory.low
-rw-r--r-- 1 root   root   0 Jul 27 07:38 memory.max
-r--r--r-- 1 root   root   0 Jul 27 07:38 memory.stat
-r--r--r-- 1 root   root   0 Jul 27 07:38 pids.current
-r--r--r-- 1 root   root   0 Jul 27 07:38 pids.events
-rw-r--r-- 1 root   root   0 Jul 27 07:38 pids.max
drwxr-xr-x 2 root   root   0 Jul 27 07:29 session-4.scope
drwxr-xr-x 4 guest2 guest2 0 Jul 27 07:29 user@1001.service
```

Then run `systemctl set-property --runtime user-1001.slice "CPUQuota=50%"` does not make `cpu.max`. On the other hand, `systemctl set-property --run-time user-1001.slice MemoryHigh=500K` **works as expected.**

**Steps to reproduce the problem**

See above.
I wonder if this issue is a duplicate of [9623](https://github.com/systemd/systemd/issues/9623), but I am not sure. If a maintainer believes that it is a duplicate, then please close this.

If this is an expected behavior, then a documentation of this would help users.

**Comment by ryutaroh-matsumoto** [comment] 2018-07-27 17:49
I found the reason behind this behavior. `echo +cpu /sys/fs/cgroup/cgroup.subtree_control` gives `write error: Invalid argument` even though `/sys/fs/cgroup/cgroup.controllers` has `cpu`. I can consistently reproduce this behavior on Linux 4.17.8 running on a barebone hardware, but Linux 4.17.8 running in qemu/kvm does not show this strange behavior. I doubt this is a bug of systemd. So I close this issue.

**Closed as completed by ryutaroh-matsumoto** 2018-07-27 17:49 UTC

**Comment by ryutaroh-matsumoto** [comment] 2018-07-27 18:10
`write error: Invalid argument`  by `echo +cpu /sys/fs/cgroup/cgroup.subtree_control` happens when `cgroup_no_v1=all` is given to the kernel command line. Now I very strongly believe that this is not a bug of systemd.

**Comment by ryutaroh-matsumoto** [comment] 2018-07-27 18:21
@htejun Sorry for disturbing you. `cgroup_no_v1=all` makes `echo +cpu >/sys/fs/cgroup/cgroup.subtree_control` give `write error: Invalid argument` even though `/sys/fs/cgroup/cgroup.controllers` has `cpu`. This seems to contradict

> To make testing and experimenting easier, the kernel parameter cgroup_no_v1= allows disabling controllers in v1 and make them always available in v2.

in https://www.kernel.org/doc/Documentation/cgroup-v2.txt

The kernel version on which I observed the above is 4.17.8. I would appreciate it if you could comment on this at your convenient time.

**Comment by htejun** [comment] 2018-07-30 19:18
@ryutaroh-matsumoto, `cat /proc/cgroups` shows which controllers are attached to which hierarchies and could be useful in debugging these issues.

**Comment by ryutaroh-matsumoto** [comment] 2018-07-30 21:55
@htejun Thanks for your response. Now I have two laptops with Linux 4.17.8 and one shows this symptom while the other doesn't... The laptop with this symptom has the following `/proc/cgroups`:

```
#subsys_name	hierarchy	num_cgroups	enabled
cpuset	0	103	1
cpu	0	103	1
cpuacct	0	103	1
blkio	0	103	1
memory	0	103	1
devices	0	103	1
freezer	0	103	1
net_cls	0	103	1
perf_event	0	103	1
net_prio	0	103	1
pids	0	103	1
```

The other laptop without this symptom has essentially the same `/proc/cgroups`, where `103` is changed to `56`. Both laptops have the same kernel command line `cgroup_no_v1=all systemd.unified_cgroup_hierarchy=1 i8042.reset=1`. 

The laptop with this problem was booted several days ago, and rebooting it _fixed_ this symptom... And `/proc/cgroups` is the same before and after the reboot.

**Comment by ryutaroh-matsumoto** [comment] 2018-07-31 15:56
@htejun Thanks again for your investigation. The first one is broken one.

```
root@letsnote2:/home/ryutaroh# echo +cpu >/sys/fs/cgroup/cgroup.subtree_control 
bash: echo: write error: Invalid argument
root@letsnote2:/home/ryutaroh# for i in $(find /sys/fs/cgroup -name cgroup.subtree_control); do ENABLED="$(cat $i)"; if [ -n "$ENABLED" ]; then echo "$i: $ENABLED"; fi; done
/sys/fs/cgroup/user.slice/user-0.slice/cgroup.subtree_control: memory pids
/sys/fs/cgroup/user.slice/user-0.slice/user@0.service/cgroup.subtree_control: memory pids
/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/cgroup.subtree_control: memory pids
/sys/fs/cgroup/user.slice/user-1000.slice/cgroup.subtree_control: memory pids
/sys/fs/cgroup/user.slice/cgroup.subtree_control: memory pids
/sys/fs/cgroup/system.slice/system-systemd\x2dfsck.slice/cgroup.subtree_control: memory pids
/sys/fs/cgroup/system.slice/system-systemd\x2dbacklight.slice/cgroup.subtree_control: memory pids
/sys/fs/cgroup/system.slice/system-user\x2druntime\x2ddir.slice/cgroup.subtree_control: memory pids
/sys/fs/cgroup/system.slice/cgroup.subtree_control: memory pids
/sys/fs/cgroup/system.slice/system-getty.slice/cgroup.subtree_control: memory pids
/sys/fs/cgroup/cgroup.subtree_control: memory pids
```

The next one is without this symptom:

```
root@buster-wayland:~# echo +cpu >/sys/fs/cgroup/cgroup.subtree_control 
root@buster-wayland:~# for i in $(find /sys/fs/cgroup -name cgroup.subtree_control); do ENABLED="$(cat $i)"; if [ -n "$ENABLED" ]; then echo "$i: $ENABLED"; fi; done
/sys/fs/cgroup/user.slice/user-0.slice/cgroup.subtree_control: memory pids
/sys/fs/cgroup/user.slice/user-0.slice/user@0.service/cgroup.subtree_control: memory pids
/sys/fs/cgroup/user.slice/cgroup.subtree_control: memory pids
/sys/fs/cgroup/system.slice/system-systemd\x2dbacklight.slice/cgroup.subtree_control: memory pids
/sys/fs/cgroup/system.slice/system-user\x2druntime\x2ddir.slice/cgroup.subtree_control: memory pids
/sys/fs/cgroup/system.slice/cgroup.subtree_control: memory pids
/sys/fs/cgroup/system.slice/system-getty.slice/cgroup.subtree_control: memory pids
/sys/fs/cgroup/cgroup.subtree_control: cpu memory pids
```

I also write the outputs of `systemd-cgls`

```
root@letsnote2:/home/ryutaroh# systemd-cgls --all --full -k
Control group /:
-.slice
|-   2 [kthreadd]
|-   3 [rcu_gp]
|-   5 [kworker/0:0H]
|-   7 [mm_percpu_wq]
|-   8 [ksoftirqd/0]
|-   9 [rcu_sched]
|-  10 [rcu_bh]
|-  11 [migration/0]
|-  12 [watchdog/0]
|-  13 [cpuhp/0]
|-  14 [cpuhp/1]
|-  15 [watchdog/1]
|-  16 [migration/1]
|-  17 [ksoftirqd/1]
|-  19 [kworker/1:0H]
|-  20 [cpuhp/2]
|-  21 [watchdog/2]
|-  22 [migration/2]
|-  23 [ksoftirqd/2]
|-  25 [kworker/2:0H]
|-  26 [cpuhp/3]
|-  27 [watchdog/3]
|-  28 [migration/3]
|-  29 [ksoftirqd/3]
|-  31 [kworker/3:0H]
|-  32 [kdevtmpfs]
|-  33 [netns]
|-  34 [kauditd]
|-  35 [kworker/0:1]
|-  36 [kworker/1:1]
|-  37 [khungtaskd]
|-  38 [oom_reaper]
|-  39 [writeback]
|-  40 [kcompactd0]
|-  41 [ksmd]
|-  42 [khugepaged]
|-  43 [crypto]
|-  44 [kintegrityd]
|-  45 [kblockd]
|-  46 [edac-poller]
|-  47 [devfreq_wq]
|-  48 [watchdogd]
|-  49 [kworker/2:1]
|-  50 [kworker/3:1]
|-  51 [kswapd0]
|-  68 [kthrotld]
|-  69 [ipv6_addrconf]
|- 121 [acpi_thermal_pm]
|- 128 [ata_sff]
|- 130 [irq/19-mmc0]
|- 131 [kworker/1:2]
|- 178 [scsi_eh_0]
|- 179 [scsi_tmf_0]
|- 180 [scsi_eh_1]
|- 181 [scsi_tmf_1]
|- 182 [scsi_eh_2]
|- 183 [scsi_tmf_2]
|- 184 [scsi_eh_3]
|- 185 [scsi_tmf_3]
|- 189 [kworker/2:2]
|- 191 [kworker/1:1H]
|- 211 [kworker/2:1H]
|- 222 [kworker/0:1H]
|- 249 [kworker/3:1H]
|- 251 [jbd2/sda2-8]
|- 252 [ext4-rsv-conver]
|- 293 [kworker/3:2]
|- 330 [irq/46-mei_me]
|- 332 [cfg80211]
|- 338 [kworker/u9:0]
|- 339 [i915/signal:0]
|- 340 [i915/signal:1]
|- 341 [i915/signal:2]
|- 342 [i915/signal:6]
|- 377 [irq/49-iwlwifi]
|- 405 [kworker/u9:2]
|- 520 [btrfs-worker]
|- 521 [btrfs-worker-hi]
|- 522 [btrfs-delalloc]
|- 523 [btrfs-flush_del]
|- 524 [btrfs-cache]
|- 525 [btrfs-submit]
|- 526 [btrfs-fixup]
|- 527 [btrfs-endio]
|- 528 [btrfs-endio-met]
|- 529 [btrfs-endio-met]
|- 530 [btrfs-endio-rai]
|- 531 [btrfs-endio-rep]
|- 532 [btrfs-rmw]
|- 533 [btrfs-endio-wri]
|- 534 [btrfs-freespace]
|- 535 [btrfs-delayed-m]
|- 536 [btrfs-readahead]
|- 537 [btrfs-qgroup-re]
|- 538 [btrfs-extent-re]
|- 540 [btrfs-cleaner]
|- 541 [btrfs-transacti]
|- 544 [jbd2/sda4-8]
|- 545 [ext4-rsv-conver]
|-1609 [kworker/u8:0]
|-1624 [kworker/u8:2]
|-1629 [kworker/0:2]
|-1646 [kworker/u8:1]
|-1730 [kworker/u8:3]
|-1733 [kworker/1:0]
|-1734 [kworker/0:0]
|-user.slice
| |-user-0.slice
| | |-session-4.scope
| | | |- 718 /bin/login -p --
| | | `-1251 -bash
| | `-user@0.service
| |   |-dbus.socket
| |   `-init.scope
| |     |-1207 /lib/systemd/systemd --user --log-level=debug
| |     `-1211 (sd-pam)
| `-user-1000.slice
|   |-user@1000.service
|   | |-gvfs-goa-volume-monitor.service
|   | | `-1287 /usr/lib/gvfs/gvfs-goa-volume-monitor
|   | |-pulseaudio.service
|   | | `-1258 /usr/bin/pulseaudio --daemonize=no
|   | |-gvfs-daemon.service
|   | | |-1051 /usr/lib/gvfs/gvfsd
|   | | `-1378 /usr/lib/gvfs/gvfsd-trash --spawner :1.6 /org/gtk/gvfs/exec_spaw/0
|   | |-dbus.socket
|   | |-gvfs-udisks2-volume-monitor.service
|   | | `-1277 /usr/lib/gvfs/gvfs-udisks2-volume-monitor
|   | |-init.scope
|   | | |-827 /lib/systemd/systemd --user --log-level=debug
|   | | `-828 (sd-pam)
|   | |-gvfs-gphoto2-volume-monitor.service
|   | | `-1302 /usr/lib/gvfs/gvfs-gphoto2-volume-monitor
|   | |-at-spi-dbus-bus.service
|   | | |-1064 /usr/lib/at-spi2-core/at-spi-bus-launcher
|   | | |-1095 /usr/bin/dbus-daemon --config-file=/usr/share/defaults/at-spi2/accessibility.conf --nofork --print-address 3
|   | | `-1097 /usr/lib/at-spi2-core/at-spi2-registryd --use-gnome-session
|   | |-gvfs-metadata.service
|   | | `-1401 /usr/lib/gvfs/gvfsd-metadata
|   | |-dbus.service
|   | | |- 927 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
|   | | |-1106 /usr/lib/dconf/dconf-service
|   | | |-1293 /usr/lib/mate-panel/wnck-applet
|   | | |-1336 /usr/lib/mate-panel/clock-applet
|   | | |-1341 /usr/lib/mate-panel/notification-area-applet
|   | | `-1391 /usr/lib/mozc/mozc_server
|   | |-gvfs-mtp-volume-monitor.service
|   | | `-1294 /usr/lib/gvfs/gvfs-mtp-volume-monitor
|   | `-gvfs-afc-volume-monitor.service
|   |   `-1282 /usr/lib/gvfs/gvfs-afc-volume-monitor
|   `-session-2.scope
|     |- 821 lightdm --session-child 12 21
|     |- 906 /usr/bin/gnome-keyring-daemon --daemonize --login
|     |- 919 mate-session
|     |-1002 /usr/bin/ssh-agent /usr/bin/im-launch mate-session
|     |-1031 /usr/bin/uim-xim
|     |-1032 uim-toolbar
|     |-1035 /usr/lib/uim/uim-helper-server
|     |-1172 /usr/bin/mate-settings-daemon
|     |-1182 marco
|     |-1255 mate-panel
|     |-1278 caja
|     |-1304 mate-screensaver
|     |-1307 nm-applet
|     |-1308 mate-power-manager
|     |-1312 /usr/lib/x86_64-linux-gnu/polkit-mate/polkit-mate-authentication-agent-1
|     |-1321 mate-volume-control-applet
|     |-1413 mate-terminal
|     |-1419 bash
|     |-1422 /usr/bin/emacs25
|     |-1428 /usr/lib/uim/uim-candwin-gtk
|     |-1430 /bin/bash --noediting -i
|     |-1433 ssh -l root 192.168.1.9
|     |-1435 /usr/bin/ssh-agent -D -a /run/user/1000/keyring/.ssh
|     |-1443 /usr/lib/firefox-esr/firefox-esr
|     |-1488 /usr/lib/firefox-esr/plugin-container -greomni /usr/lib/firefox-esr/omni.ja -appomni /usr/lib/firefox-esr/browser/omni.ja -appdir /usr/lib/firefox-esr/browser 1443 true tab
|     |-1622 su
|     |-1623 bash
|     |-1641 /bin/bash --noediting -i
|     |-1644 su
|     |-1645 bash
|     `-1755 systemd-cgls --all --full -k
|-init.scope
| `-1 /sbin/init
`-system.slice
  |-irqbalance.service
  | `-646 /usr/sbin/irqbalance --foreground
  |-system-systemd\x2dfsck.slice
  |-systemd-udevd.service
  | `-311 /lib/systemd/systemd-udevd
  |-cron.service
  | `-638 /usr/sbin/cron -f
  |-polkit.service
  | `-698 /usr/lib/policykit-1/polkitd --no-debug
  |-rtkit-daemon.service
  | `-1274 /usr/lib/rtkit/rtkit-daemon
  |-sys-kernel-debug.mount
  |-bluetooth.service
  | `-634 /usr/lib/bluetooth/bluetoothd
  |-home.mount
  |-accounts-daemon.service
  | `-642 /usr/lib/accountsservice/accounts-daemon
  |-wpa_supplicant.service
  | `-644 /sbin/wpa_supplicant -u -s -O /run/wpa_supplicant
  |-libvirtd.service
  | |- 898 /usr/sbin/libvirtd
  | |-1169 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper
  | `-1170 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper
  |-lightdm.service
  | |-721 /usr/sbin/lightdm
  | `-729 /usr/lib/xorg/Xorg :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
  |-ModemManager.service
  | `-636 /usr/sbin/ModemManager --filter-policy=strict
  |-systemd-journald.service
  | `-282 /lib/systemd/systemd-journald
  |-var-lib-machines.mount
  |-system-systemd\x2dbacklight.slice
  |-ssh.service
  | `-748 /usr/sbin/sshd -D
  |-dev-mqueue.mount
  |-colord.service
  | `-727 /usr/lib/colord/colord
  |-NetworkManager.service
  | |-643 /usr/sbin/NetworkManager --no-daemon
  | `-859 /sbin/dhclient -d -q -sf /usr/lib/NetworkManager/nm-dhcp-helper -pf /run/dhclient-wlp2s0.pid -lf /var/lib/NetworkManager/dhclient-475d2705-471c-4bb8-8d5d-843267f93c16-wlp2s0.lease -cf /var/lib/NetworkManager/dhclient-wlp2s0.conf wlp2s0
  |-rsyslog.service
  | `-640 /usr/sbin/rsyslogd -n -iNONE
  |-blk-availability.service
  |-boot-efi.mount
  |-system-user\x2druntime\x2ddir.slice
  |-cups-browsed.service
  | `-702 /usr/sbin/cups-browsed
  |-dev-disk-by\x2duuid-8d454141\x2d7ccb\x2d4913\x2db46b\x2dd7da5b2fd8b0.swap
  |-lvm2-lvmetad.service
  | `-306 /sbin/lvmetad -f
  |-cups.service
  | `-639 /usr/sbin/cupsd -l
  |-upower.service
  | `-1331 /usr/lib/upower/upowerd
  |-udisks2.service
  | `-641 /usr/lib/udisks2/udisksd
  |-dev-hugepages.mount
  |-dbus.service
  | `-632 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
  |-systemd-timesyncd.service
  | `-594 /lib/systemd/systemd-timesyncd
  |-system-getty.slice
  | `-getty@tty1.service
  |-avahi-daemon.service
  | |-645 avahi-daemon: running [letsnote2.local]
  | `-697 avahi-daemon: chroot helper
  `-systemd-logind.service
    `-633 /lib/systemd/systemd-logind
```

The above is the output from broken one. The next is that from the laptop without symptom:

```
root@buster-wayland:~# systemd-cgls --all --full -k
Control group /:
-.slice
|-  2 [kthreadd]
|-  3 [rcu_gp]
|-  5 [kworker/0:0H]
|-  7 [mm_percpu_wq]
|-  8 [ksoftirqd/0]
|-  9 [rcu_sched]
|- 10 [rcu_bh]
|- 11 [migration/0]
|- 12 [watchdog/0]
|- 13 [cpuhp/0]
|- 14 [cpuhp/1]
|- 15 [watchdog/1]
|- 16 [migration/1]
|- 17 [ksoftirqd/1]
|- 19 [kworker/1:0H]
|- 20 [kdevtmpfs]
|- 21 [netns]
|- 22 [kauditd]
|- 25 [khungtaskd]
|- 26 [oom_reaper]
|- 27 [writeback]
|- 28 [kcompactd0]
|- 29 [ksmd]
|- 30 [khugepaged]
|- 31 [crypto]
|- 32 [kintegrityd]
|- 33 [kblockd]
|- 34 [edac-poller]
|- 35 [devfreq_wq]
|- 36 [watchdogd]
|- 37 [kswapd0]
|- 54 [kthrotld]
|- 56 [kworker/0:2]
|- 57 [ipv6_addrconf]
|-117 [acpi_thermal_pm]
|-118 [irq/23-mmc0]
|-120 [ata_sff]
|-121 [scsi_eh_0]
|-122 [scsi_tmf_0]
|-123 [scsi_eh_1]
|-124 [scsi_tmf_1]
|-125 [scsi_eh_2]
|-126 [scsi_tmf_2]
|-127 [scsi_eh_3]
|-128 [scsi_tmf_3]
|-129 [scsi_eh_4]
|-130 [scsi_tmf_4]
|-131 [scsi_eh_5]
|-132 [scsi_tmf_5]
|-140 [kworker/0:1H]
|-185 [btrfs-worker]
|-186 [kworker/u9:0]
|-188 [btrfs-worker-hi]
|-189 [btrfs-delalloc]
|-190 [btrfs-flush_del]
|-191 [btrfs-cache]
|-192 [btrfs-submit]
|-193 [btrfs-fixup]
|-194 [btrfs-endio]
|-195 [btrfs-endio-met]
|-196 [btrfs-endio-met]
|-197 [btrfs-endio-rai]
|-198 [btrfs-endio-rep]
|-199 [btrfs-rmw]
|-200 [btrfs-endio-wri]
|-201 [btrfs-freespace]
|-202 [btrfs-delayed-m]
|-203 [btrfs-readahead]
|-204 [btrfs-qgroup-re]
|-205 [btrfs-extent-re]
|-206 [btrfs-cleaner]
|-207 [btrfs-transacti]
|-351 [cfg80211]
|-359 [i915/signal:0]
|-361 [i915/signal:2]
|-365 [pccardd]
|-371 [kworker/1:2H]
|-375 [kworker/1:4]
|-376 [irq/30-iwlwifi]
|-508 [kworker/u9:1]
|-664 [kworker/u8:1]
|-676 [kworker/1:1]
|-678 [kworker/0:0]
|-679 [kworker/u8:2]
|-717 [kworker/u8:0]
|-718 [kworker/0:1]
|-719 [kworker/1:0]
|-user.slice
| |-user-0.slice
| | |-session-3.scope
| | | |-634 sshd: root@pts/0
| | | |-640 -bash
| | | `-721 systemd-cgls --all --full -k
| | |-session-1.scope
| | | |-499 /bin/login -p --
| | | `-629 -bash
| | `-user@0.service
| |   |-dbus.socket
| |   `-init.scope
| |     |-618 /lib/systemd/systemd --user
| |     `-619 (sd-pam)
| `-user-nonexistent.slice
|-init.scope
| `-1 /sbin/init
`-system.slice
  |-irqbalance.service
  | `-472 /usr/sbin/irqbalance --foreground
  |-haveged.service
  | `-468 /usr/sbin/haveged --Foreground --verbose=1 -w 1024
  |-systemd-udevd.service
  | `-255 /lib/systemd/systemd-udevd
  |-dev-disk-by\x2duuid-9b672f67\x2d28f5\x2d4765\x2da423\x2dc53f419d25fe.swap
  |-cron.service
  | `-478 /usr/sbin/cron -f
  |-polkit.service
  | `-489 /usr/lib/policykit-1/polkitd --no-debug
  |-sys-kernel-debug.mount
  |-wpa_supplicant.service
  | `-476 /sbin/wpa_supplicant -u -s -O /run/wpa_supplicant
  |-ModemManager.service
  | `-470 /usr/sbin/ModemManager --filter-policy=strict
  |-systemd-journald.service
  | `-239 /lib/systemd/systemd-journald
  |-system-systemd\x2dbacklight.slice
  |-ssh.service
  | `-502 /usr/sbin/sshd -D
  |-dev-mqueue.mount
  |-NetworkManager.service
  | |-475 /usr/sbin/NetworkManager --no-daemon
  | `-533 /sbin/dhclient -d -q -sf /usr/lib/NetworkManager/nm-dhcp-helper -pf /run/dhclient-wls3.pid -lf /var/lib/NetworkManager/dhclient-929d9c46-5952-4646-afde-638d6b98b127-wls3.lease -cf /var/lib/NetworkManager/dhclient-wls3.conf wls3
  |-rsyslog.service
  | `-477 /usr/sbin/rsyslogd -n -iNONE
  |-system-user\x2druntime\x2ddir.slice
  |-systemd-resolved.service
  | `-263 /lib/systemd/systemd-resolved
  |-dev-hugepages.mount
  |-dbus.service
  | `-474 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
  |-systemd-timesyncd.service
  | `-265 /lib/systemd/systemd-timesyncd
  |-system-getty.slice
  | `-getty@tty1.service
  |-avahi-daemon.service
  | |-471 avahi-daemon: running [buster-wayland.local]
  | `-487 avahi-daemon: chroot helper
  `-systemd-logind.service
    `-500 /lib/systemd/systemd-logind
```

Both laptops running the following kernel...

```
root@letsnote2:/home/ryutaroh# uname -a
Linux letsnote2 4.17.0-1-amd64 #1 SMP Debian 4.17.8-1 (2018-07-20) x86_64 GNU/Linux
root@buster-wayland:~# uname -a
Linux buster-wayland 4.17.0-1-amd64 #1 SMP Debian 4.17.8-1 (2018-07-20) x86_64 GNU/Linux
```
