### ISSUE TITLE
initrd: tmpfiles failure parsing systemd.conf ACLs

### ISSUE THREAD

**Issue by kaysievers** [systemd/systemd#162] opened 2015-06-11 09:29 UTC
Jun 11 11:17:24 ank systemd-tmpfiles[132]: Failed to parse ACL "d:group:adm:r-x,d:group:wheel:r-x": Invalid argument. Ignoring

**Comment by martinpitt** [comment] 2015-06-11 09:38
I got that when this feature got introduced because we don't actually have a `wheel` group. Do you?

**Comment by kaysievers** [comment] 2015-06-11 09:41
$ id kay
uid=2702(kay) gid=2702(kay) groups=2702(kay),10(wheel)

**Comment by arvidjaar** [comment] 2015-06-11 10:13
And "adm"? I do not have it e.g. on my SLES server. Sounds more Solaris to me.

**Comment by martinpitt** [comment] 2015-06-11 10:32
`adm` is a standard LSB group, every linux should have it. http://refspecs.linuxbase.org/LSB_5.0.0/LSB-Core-generic/LSB-Core-generic.html#USERNAMES

**Comment by martinpitt** [comment] 2015-06-11 10:33
To avoid doubt: tmpfiles of course needs to get along with it not being there, it's an optional group still. (I was just pointing out that it's not Solaris specific)

**Comment by poettering** [comment] 2015-06-12 11:20
@martinpitt well, there are some groups we _require_ to exist, like video, audio and so on. "adm" is kinda one of them too, see sysusers.d/.

If debian decides not to support adm, then it needs to patch that out, from the tmpfiles snippet as well as the sysusers snippet.

**Comment by poettering** [comment] 2015-06-12 11:21
@kaysievers but i presume you do have both wheel and adm around, right?

either way, if a group is missing on a system then the parsing error of an ACL expression certainly shouldn't be "EINVAL", though.

**Comment by martinpitt** [comment] 2015-06-12 11:30
@poettering oh, Debian/Ubuntu do support `adm`, it's even a static group. I was just guessing that @kaysievers wouldn't have that group, as he does seem to have `wheel`.

**Comment by poettering** [comment] 2015-06-15 10:08
So, do we have any idea why @kaysievers's line actually failed with EINVAL? @kaysievers you have both groups around, don't you? If so, this cannot be related to group resolving...

**Comment by kaysievers** [comment] 2015-06-15 10:11
$ getent group wheel adm
wheel:x:10:kay
adm:x:4:

**Comment by poettering** [comment] 2015-06-17 20:18
Hmm, I have no idea what might have caused that. @kaysievers, can you reproduce this at all?

I have now prepped PR #275 with a couple of fixes, which should hopefully make it easier to debug this (since it won't eat up errors anymore and turn them into EINVAL). 

Kay, was this a boot-up where maybe /etc/nsswitch.conf was missing or so? (i.e. stateless or so?)

**Comment by kaysievers** [comment] 2015-06-17 22:42
The log is from the initrd. Let Harald take a look what's going wrong there. It is not release-critical.

**Comment by poettering** [comment] 2015-06-17 22:42
Kay just indicated that this is an initrd invocation of tmpfiles. Question hence becomes: why does the initrd include tmpfiles? and if it does that for a good reason, then why does it miss the adm/wheel groups?

I figure this should be reassigned to dracut now. @haraldh can you take this over?

**Comment by poettering** [comment] 2015-07-11 20:36
Closing this now, as this is something to deal with in dracut. @haraldh please look into this.

**Closed as completed by poettering** 2015-07-11 20:36 UTC
Labels: not-our-bug, initrd
