### ISSUE TITLE
UTF8 unit files with byte order mark (BOM) not supported

### ISSUE THREAD

**Issue by LuAPi** [systemd/systemd#2874] opened 2016-03-20 16:25 UTC
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

systemd --version
systemd 225
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

Ubuntu 15.10 32bit server (GNU/Linux 4.2.0-16-generic i686)
### In case of bug report: Expected behaviour you didn't see

Expected UTF8 files to work as unit files.
Reality is UTF8 files with byte order mark (BOM) can not be used as unit files.
### In case of bug report: Unexpected behaviour you saw

Attempting to enable a unit with UTF8 byte order mark returns:

> Failed to execute operation: Bad message

`journalctl -xeq` lists the error as
`systemd[1]: [/etc/systemd/system/bomTestA.timer:1] Missing '='.`
This suggests the parser is treating the UTF8 BOM as an option and is expecting an `=` after it when it shouldn't.
### In case of bug report: Steps to reproduce the problem
1. Create a unit file with a UTF8 byte order mark at the start in /etc/systemd/system/
2. Attempt to enable or start the unit file with systemctl
3. Observe failure

I tried to attach a minimal example in a zip file but github is rejecting my file. Here's a dropbox link
https://www.dropbox.com/s/0hya6cvh6fshsek/bom.ZIP?dl=1
It contains 4 files:
bomTestA (.timer and .service) which feature the byte order mark at the start.
bomtestB (.timer and .service) which don't feature the byte order mark.

Usage (output prefixed with `#`):
`sudo unzip -d /etc/systemd/system/ bom.ZIP`
`sudo systemctl enable bomTestA.timer`
`#Failed to execute operation: Bad message`
`sudo systemctl enable bomTestB.timer`
`#Created symlink from /etc/systemd/system/multi-user.target.wants/bomTestB.timer to /etc/systemd/system/bomTestB.timer.`

**Comment by zdzichu** [comment] 2016-03-20 16:54
Duplicate of #2823 ?

**Comment by LuAPi** [comment] 2016-03-20 16:56
Yes. My mistake.
I searched for UTF8 byte order mark and found nothing.
Feel free to merge / mark as duplicate.

**Closed as completed** 2016-03-20 20:23 UTC
