### ISSUE TITLE
systemd-nspawn fails inside systemd-nspawn when DropCapabilities active: Operation not permitted

### ISSUE THREAD

**Issue by thiagomacieira** [systemd/systemd#12798] opened 2019-06-14 17:16 UTC
**systemd version the issue has been seen with**
> 242

**Used distribution**
 > Clear Linux 29920 and openSUSE Tumbleweed

**Expected behaviour you didn't see**
 > Starting a nested container should work

**Unexpected behaviour you saw**
 > systemd-nspawn fails with error message
```
$ sudo systemd-nspawn -D /tmp/clr-barebones
Spawning container clr-barebones on /tmp/clr-barebones.
Press ^] three times within 1s to kill container.
Dropping capabilities failed: Operation not permitted
Child died too early.
```

**Steps to reproduce the problem**
1. Create a config file in /etc/systemd/nspawn for a container and add: `DropCapability=CAP_SYS_BOOT CAP_MKNOD`
1. Start such a container
1. From inside that container, attempt to start another container, one without a config file

Inside the outer container, /proc/self/status for a root process shows:
```
CapInh: 0000000000000000
CapPrm: 00000000f5acbfff
CapEff: 00000000f5acbfff
CapBnd: 00000000f5acbfff
CapAmb: 0000000000000000
```

Up until systemd v241, stracing the inner systemd-nspawn showed:
```
capset(({version=_LINUX_CAPABILITY_VERSION_3, pid=0}, {effective=0xf5acbfff, permitted=0xf5acbfff, inheritable=0}) = 0
```

Using systemd v242, the strace shows:
```
capset(({version=_LINUX_CAPABILITY_VERSION_3, pid=0}, {effective=0xfdecafff, permitted=0xfdecafff, inheritable=0xfdecafff}) = -1 EPERM (Operation not permitted)
```

Note that in v241, the effective and permitted were equal to the ambient capabilities. In v242, it attempts to regain the two dropped capabilities (CAP_SYS_BOOT and CAP_MKNOD), drops CAP_NET_ADMIN and sets the inheritable.

**Comment by poettering** [comment] 2019-06-18 09:21
hmm, let me get this right: you want that nspawn instead of enforcing the precisely configured set of caps would just drop what it is told to drop and if there are caps already dropped on top of that, not complain?

I assumed that the current behaviour (i.e. adjusting the caps to exactly what is configured) is the better approach, since it guarantees reproducible behaviour. But maybe we can find a middle ground, where we warn about caps that we cannot acquire but which are not listed to be dropped, and then proceed anyway. Would that work for you? (if so, patch would be gladly accepted for thta)

**Comment by poettering** [comment] 2019-06-18 12:10
Appears to be a duplicate of #12539. Closing.

**Closed as completed by poettering** 2019-06-18 12:10 UTC
Labels: nspawn

**Comment by thiagomacieira** [comment] 2019-06-18 14:23
I wouldn't mind telling systemd-nspawn that I do indeed want it to drop those capabilities.

But it has no global config file where I could configure that. The systemd-nspawn process I'm having trouble with is launched by mock (https://github.com/rpm-software-management/mock), not machinectl.
