### ISSUE TITLE
uid_is_system / SYSTEM_UID_MAX should not be static

### ISSUE THREAD

**Issue by jwrdegoede** [systemd/systemd#10184] opened 2018-09-27 07:14 UTC
**systemd version the issue has been seen with**
systemd-239-3.fc29.x86_64

**Used distribution**
 Fedora

**Expected behaviour you didn't see**
 A timer with "ConditionUser=!@system" in its  timer file runs for my user login session

**Unexpected behaviour you saw**
The timer did not run

**Steps to reproduce the problem**
1. Edit: /etc/login.defs
2. Change SYS_UID_MAX  to 499, UID_MIN to 500
3. adduser
4. reboot (to give systemd a chance to see the new login.defs
5. login as the new user
6. Units for that user with "ConditionUser=!@system"  do not run

Now one might say don't do step 2. of the reproduction steps, but this is happening on my main workstation, which has been upgraded from one Fedora release to the next to the next, etc. The /etc/login.defs file on this machine is from 2012 and has never been manually edited by me. IMHO systemd should check for  /etc/login.defs' SYS_UID_MAX value and use that if present, using SYSTEM_UID_MAX as a fallback.

The parsing of /etc/login.defs' SYS_UID_MAX can be done once at boot and then cached.

**Comment by yuwata** [comment] 2018-09-27 08:07
It seems a duplicate of #9769, at least deeply related to that.

**Comment by jwrdegoede** [comment] 2018-09-27 09:49
On 27-09-18 10:07, Yu Watanabe wrote:
> It seems a duplicate of #9769 <https://github.com/systemd/systemd/issues/9769>, at least deeply related to that.

You're right, this does seem have the same root cause.

That bug was closed with Lennart writing: "On systemd systems the UID boundaries are not user configuration, and they really should not be. This is documented at various places..."
and: "How to assign UID ranges really has to be a decision for the distro developers, it shouldn't be subject to user configuration ..."

Lennart, I do not disagree with that, but the problem is that at least Fedora at point in time decided to change
the login.defs setting from normal users starting at UID 500 to normal users starting at UID 1000, so on old
Fedora systems which have been upgraded over time the current systemd behavior *simply is broken*. No user
configuration has been done and the upgrade process correctly keeps the old login.defs (as provided by the distro).

Systemd fails to honor the distro settings in this case as it uses the new defaults instead of the login.defs
settings which were actually in place when the users were created (once upon a time).

**Comment by bl33pbl0p** [comment] 2018-09-27 10:08
Agreed, it should try to read login.defs at runtime and use the compiled-in value as a fallback. Every other tool that deals with UID ranges seems to read login.defs at runtime, systemd ones being the exception.

**Comment by jwrdegoede** [comment] 2018-10-13 09:07
I was just bitten by this again. systemd-devs if I write a patch to parse login.defs once at systemd startup, with a fallback to the current behavior if that fails (e.g. running in the initrd) would you be willing to take such a patch ?

**Comment by poettering** [comment] 2018-10-16 11:22
> I was just bitten by this again. systemd-devs if I write a patch to parse login.defs once at systemd startup, with a fallback to the current behavior if that fails (e.g. running in the initrd) would you be willing to take such a patch ?

we expose this all over the place, for example in `pkg-config --variable=systemuidmax systemd`. It's not that easy... And frickin ugly...

**Comment by jwrdegoede** [comment] 2018-10-16 13:29
On 16-10-18 13:22, Lennart Poettering wrote:
>     I was just bitten by this again. systemd-devs if I write a patch to parse login.defs once at systemd startup, with a fallback to the current behavior if that fails (e.g. running in the initrd) would you be willing to take such a patch ?
> 
> we expose this all over the place, for example in |pkg-config --variable=systemuidmax systemd|.

Why would systemd expose this in pkg-config? But yes this shows another
way in how this is broken, if something decides to trust the
systemd pc provided value for this it may be wrong:

[hans@shalem ~]$ pkg-config --variable=systemuidmax systemd
999
[hans@shalem ~]$ grep SYS_UID_MAX /etc/login.defs
SYS_UID_MAX               499

And no systemd is not the canonical source of this value /etc/login.defs
has been been the canonical source of this since before the beginning
of this millennium. systemd itself acknowledges this by extracting it
it from /etc/login.defs at build-time but that is simply wrong as
this value is simply not static as systemd sofar has assumed it is.

As I mentioned before I can live with the argument that end-users
should not change this, but there are scenarios where systemd gets
it wrong where it was not changed by the end user.

Anyways I doubt anything relies on this being in pkg-config, so the
answer here is to simply stop exposing this in pkg-config, especially
since the value in the .pc file is wrong on some systems too.

> It's not that easy... And frickin ugly...

Listen, you can keep repeating how ugly this is, but now matter how you put
it the current behavior is buggy. Currently "ConditionUser=@system"
simply is broken, BROKEN and *BROKEN*.

If you do not want to fix this I suggest just removing @system support
completely, not having it is better then incomplete broken support.

And if you disagree it is broken, do the following:

Install Fedora 14, create 1 or more normal users. Then upgrade it to 15,
16, etc. until you are at 28 or 29.

Now use "ConditionUser=!@system" for a user service (so that it e.g.
does not run under the gdm chooser session) and notice how the service
also does not run for the users you've created.

I do not believe I'm the only person to hit this scenario I'm quite sure
there are quite a few people who have old installs which have been upgraded
over time around and "ConditionUser=@system" simply is BROKEN on such
systems.

Now can we please work towards a fix for this? As mentioned before I'm
willing to spend time on fixing this.

**Comment by poettering** [comment] 2018-10-16 13:48
Dunno, this actually hasn't come up before in this context. Fedora switched 7 years ago from 500 → 1000...

I mean, the limit of 500 is kinda borked anyway (it got bumped because it was too low), I am not sure it's really worth playing whack-a-mole with this, and exchanging one brokeness by another...

Moreover, it's one thing parsing foreign configuration files (login.defs is a private configuration file shadow-utils, and the man page kinda suggests that other tools should be configured elsewhere) in our meson scripts at build time. It's quite another to do this during runtime all the time.

I'd be willing to take a patch that allows overriding the boundary with an env var for specific tools. that way you could for example add a compat kludge to the rpm postinst scriptlets of systemd.rpm that parse around in login.defs and generates drop-ins in /etc/systemd/system/user@.service.d/. Still ugly, but not as ugly, and we wouldn't have to bless the flawed concept of login.defs upstream.

**Comment by poettering** [comment] 2018-11-06 09:40
Duplicate of #9769, #3855, #4850

**Comment by teg** [comment] 2018-11-06 09:51
FYI, dbus-broker currently uses the pkgconfig value from systemd. Though we would be happy to move to some other solution if anything else is less broken.

**Comment by didierm** [comment] 2019-05-21 11:36
> Dunno, this actually hasn't come up before in this context. Fedora switched 7 years ago from 500 → 1000...

Some people are running RHEL.
We started deploying EL3 in the early 2000's with UID_MIN,GID_MIN=500 (/etc/login.defs is currently modified to the former standard values in our kickstart %pre sections).

Migrating our uid/gid's is simply not feasible.

**Comment by poettering** [comment] 2020-11-24 15:25
@keszybz add a horrible hack to address this in aa25270cb22f5f7ca2b18c288d4e15bbc6eb239e. Closing.

**Closed as completed by poettering** 2020-11-24 15:25 UTC
Labels: pid1
