### ISSUE TITLE
VNI of existing VXLAN does not get updated if configuration changes

### ISSUE THREAD

**Issue by mweinelt** [systemd/systemd#17562] opened 2020-11-10 00:07 UTC
**systemd version the issue has been seen with**
 > systemd 246 (246)
> +PAM +AUDIT -SELINUX +IMA +APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS +ACL +XZ +LZ4 -ZSTD +SECCOMP +BLKID -ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > NixOS

**Linux kernel version used** (`uname -a`)
 > 5.4.75

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
After changing the VNI of an existing VXLAN interface and restarting networkd the interface should get recreated with the correct VNI.

**Unexpected behaviour you saw**
After updating the VNI of an existing VXLAN interface and restarting networkd the VXLAN interface was still around with its old VNI.

**Steps to reproduce the problem**
 
1. Create 10-vxlan.conf
```
[NetDev]
Kind=vxlan
Name=vx-test

[VXLAN]
VNI=100
```
2. `systemctl restart systemd-networkd`
3. Observe the VXLAN ID at `ip -d link show dev vx-test`
4. Update the VNI to something else
```
[NetDev]
Kind=vxlan
Name=vx-test

[VXLAN]
VNI=200
```
5. `systemctl restart systemd-networkd`
6. Observe the VXLAN ID at `ip -d link show dev vx-test` again

**Notes**

I saw the same behaviour with the RoutingAlgorithm in #17252. Switch between `BATMAN_IV` and `BATMAN_V` in the config and restart networkd, the interfaces will stay the same no matter what.

**Comment by yuwata** [comment] 2020-11-10 06:23
Duplicate of #9627.

**Closed as completed by yuwata** 2020-11-10 06:23 UTC
Labels: RFE 🎁, network, duplicate
