### ISSUE TITLE
LSB service stopped after, not before partition unmounting

### ISSUE THREAD

**Issue by sknaumov** [systemd/systemd#9765] opened 2018-07-31 16:35 UTC
**systemd version the issue has been seen with**
> 237, 239

**Used distribution**
 > Debootstrapped Ubuntu 18.04-based system

**Expected behaviour you didn't see**
 > LSB service with 'Required-Stop: $local_fs $remote_fs $named $network $syslog $time' stops before partition mounted with fstab tried to get unmounted.

**Unexpected behaviour you saw**
 > LSB service stops after unmounting attempt, which results in failure, as the service still uses this partition.

**Steps to reproduce the problem**
> Create separate partition on some /dev/sd* device, mount it in fstab, create an LSB service that depends on $local_fs and $remote_fs and uses this partition (say, stores database there), and then try to shutdown PC.

**Comment by mbiebl** [comment] 2018-07-31 21:18
You probably want Required-Start: instead of -Stop

**Comment by sknaumov** [comment] 2018-08-01 08:41
I already have it:

```
### BEGIN INIT INFO
# Provides:          sniffer
# Required-Start:    $local_fs $named $network $remote_fs $syslog $time
# Required-Stop:     $local_fs $named $network $remote_fs $syslog $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start sniffer daemon
### END INIT INFO
```

Thats why I expect that everything will be mounted before my service is started (which is true) and that my service will be stopped at shutdown before unmounting (which is false):
```
systemd[1]: Stopping LSB: Start sniffer daemon...
systemd[1]: Unmounting /var/sniffer
umount[522]: umount: /var/sniffer: target is busy
...
systemd[1]: Failed unmounting /var/sniffer.
sniffer[519]: * Stopping sniffer
...
sniffer[519]: ...done.
...
systemd[1]: Stopped LSB: Start sniffer daemon.
```

**Comment by poettering** [comment] 2018-08-01 09:51
What does your fstab entry look like? What does `systemctl show var-sniffer.mount` show?

**Comment by sknaumov** [comment] 2018-08-01 12:43
[fstab.txt](https://github.com/systemd/systemd/files/2249429/fstab.txt)
[var-sniffer.mount.txt](https://github.com/systemd/systemd/files/2249430/var-sniffer.mount.txt)

BTW, I've managed to make a workaround:
```
echo "\
[Unit]
RequiresMountsFor=/var/sniffer
" > /etc/systemd/system/sniffer.service.d
```

**Comment by poettering** [comment] 2018-08-02 18:15
You specified "nofail" for that partition in /etc/fstab. That means that systemd won't wait for the mount to show up at boot, nor for it to go away on shutdown. It also means systemd won't care if mounting it fails.

The ordering logic is a bit underdocumented, I added this now in #9784. 

Basically, if you want the mount to show up realiably either drop "nofail" from the fstab entry, or use After=var-sniffer.mount in your unit file.

Anyway, this is kinda intended behaviour (and with #9784 finally documented), hence closing this. I hope this makes sense.

**Closed as completed by poettering** 2018-08-02 18:15 UTC

**Comment by sknaumov** [comment] 2018-08-03 08:29
But why systemd can't detect on shutdown that it is actually mounted and act accordingly?

**Comment by poettering** [comment] 2018-08-03 10:45
> But why systemd can't detect on shutdown that it is actually mounted and act accordingly?

So, systemd doesn't have a concept for "order only at shutdown but not at startup". The assumption so far is that either some file system is needed for a service or it isn't. Hence there's only one type of ordering, and After= hence means two things: "start B after A when both are starting, but stop A after B when both are stopping". 

It has been requested before that systemd should allow separate ordering for startup and shutdown, i.e. allow that when two units are started they can be ordered in some way, but that when they are stopped they aren't ordered in the opposite order. But so far when this came up each time a better solution was found. 

I am not sure I grok your usecase. It appears your service needs that mount to be around, no? If so RequiresMountsFor= sounds appropriate, no?

**Comment by sknaumov** [comment] 2018-08-03 11:01
1. I just want the service to start and work even if separate storage HDD is not installed, but if it is, then wait for it to be mounted and then stop service before it gets unmounted.

2. I want HDD to be labeled and formatted at boot if it had not been labeled yet. I do it in a separate service that is started before local-fs-pre (actually it has DefaultDependencies=no, Before=systemd-fsck-root.service, Conflicts=shutdown.target). For some reason it affects mount time of /var/sniffer (when it is mounted after formatting) even though the service is started before local-fs-pre, so this mount is shifted towards end of boot sequence, but still happens before start of LSB services. And here I see this strange "RequiresMountsFor" behavior, when /var/sniffer is mounted before the time LSB services are started, but sniffer service is not started by systemd (see https://github.com/systemd/systemd/issues/9765#issuecomment-409880507).

**Comment by poettering** [comment] 2018-08-03 11:15
note that devices can take any time they want to show up at boot with today's hardware. hence a logic of "is the hardware installed then mount it" can never work reliably, since during early boot the device won't have been enumerated, and you never know when it will or whether it will at all...

I am not sure how you format your disk, but have you checked that after formatting is complete the device shows up properly? i.e. "udevadm info" on the device should show the "systemd" tag to be set for it, and SYSTEMD_READY=0 should not be set.

**Comment by fbuihuu** [comment] 2018-08-28 14:06
> It has been requested before that systemd should allow separate ordering for startup and shutdown, i.e. allow that when two units are started they can be ordered in some way, but that when they are stopped they aren't ordered in the opposite order. But so far when this came up each time a better solution was found.

That's not entirely true, https://github.com/systemd/systemd/pull/6102 is still opened...
