### ISSUE TITLE
We basically block login during boot, and yet we tell people that it is possible for privileged users

### ISSUE THREAD

**Issue by XANi** [systemd/systemd#8228] opened 2018-02-20 08:21 UTC
I've noticed it is in the repo and included by default in few distros, however I can't figure out case why someone would want to have it.

Current behaviour (from what I can observe) is basically "forbid any non-root login until system started", which in our case was "just dont allow actual system admins to log in for few minutes(till systemd goes from "starting" to "degraded") to fix/debug the problem" (which i our case was some service timing out on network resource), because as every nice admin we don't use `root` account to manage servers but use sudo instead.

I can see the case when you'd want prevent users to log in before system is booted, but without distinction between sysadmins (users managing actual system) and users (users using services on system or deploying apps on it) that just isn't very useful (and afaik pam_nologin doesn't have option to allow particular group of users to log in).

I mean turning it off is easy enough but seems like a mine waiting for someone to step into it

**Comment by keszybz** [comment] 2018-02-20 09:13
That's how things traditionally worked in UNIX / Linux. Actual behaviour is determined by pam_nologin(8), and only if the pam module is actually configured. So systemd just provides the hook into this logic, but the actual decision whether to make use of this or not is made elsewhere.

If you think the whole nologin logic is obsolete, you need to take it up with whoever maintains the pam config. That's the right place to change this, i.e. change the policy, and not get rid of the mechanism.

So I'll close this, since this is not the place to change this. That said, I agree pam_nologin doesn't work in the modern world where people use sudo for administration, and more generally, it is mostly pointless, since there's nothing wrong with letting users log in during bootup. I'd be great to get rid of nologin from the default pam configurations.

**Comment by XANi** [comment] 2018-02-20 10:24
@keszybz I haven't saw distro pre-systemd that created nologin the same way systemd did - on boot. So it is very much systemd-induced problem.

nologin has its use cases (limited as they are) - say I do something on /home and want to block users from logging for few minutes, systemd just misuses it.

> Actual behaviour is determined by pam_nologin(8), and only if the pam module is actually configured. So systemd just provides the hook into this logic, but the actual decision whether to make use of this or not is made elsewhere.

No. pam_nologin IS a hook, systemd is the trigger because systemd creates the file in the first place. 

"we create some pointless file for no reason, just remove app that uses that file" is not exactly great answer too

**Comment by mbiebl** [comment] 2018-02-20 11:23
I just checked an old Debian jessie installation with sysvinit. Seems the mechanism for creating /run/nologin is there, but it's only activate when ```DELAYLOGIN=yes``` has been set in /etc/default/rcS. The default is ```no```

**Comment by keszybz** [comment] 2018-02-20 11:34
Hmm, so another case where we implemented something that sysv supposedly did. In this case I think it would make sense to stop creating /run/nologin at boot.

**Comment by XANi** [comment] 2018-02-20 11:39
@mbiebl Heh I even forgot that option existed. Out of few dozen desktops and few hundred servers I never had a case for using it.

Alternatively, leave commented-out example on how to do it (as it is kinda nontrivial how does that even happen if you're not deep into systemd architecture) for those who need it.

**Comment by mbiebl** [comment] 2018-02-20 11:49
> Hmm, so another case where we implemented something that sysv supposedly did. In this case I think it would make sense to stop creating /run/nologin at boot.

Do you know how RHEL/Fedora pre-systemd handled this?

**Comment by keszybz** [comment] 2018-02-20 11:51
No idea. But we default to Debian behaviour usually, so what you wrote is good enough for me ;)

**Comment by mbiebl** [comment] 2018-02-20 12:05
Fwiw, the man page https://manpages.debian.org/jessie/initscripts/rcS.5.en.html is not in sync with the actual behaviour:
```
DELAYLOGIN
Normally the system will not let non-root users log in until the boot process is complete and the system has finished switching to the default runlevel (usually level 2). However, in theory it is safe to log in a bit earlier, namely, as soon as inetd has started. Setting the variable to no allows earlier login; setting the variable to yes prevents it.
 
Some details: The DELAYLOGIN variable controls whether or not the file /run/nologin is created during the boot process and deleted at the end of it. The login(1) program refuses to allow non-root logins so long as /run/nologin exists. If you set the variable to no then it is advisable to ensure that /run/nologin does not exist.
```

**Comment by XANi** [comment] 2018-02-20 12:08
@keszybz on Centos 6 there doesn't seem to be any mechanism to create it automatically (and it uses `/etc/nologin`), grepping /etc only showed some selinux rules and pam.d for pam_nologin

**Comment by mbiebl** [comment] 2018-02-20 12:09
Haha, so the initscript /etc/init.d/bootmis.sh has the following:
```
[ "$DELAYLOGIN" ] || DELAYLOGIN=yes
. /lib/init/vars.sh
```
It seems /lib/init/vars.sh overrides DELAYLOGIN and set's it to no, as /etc/default/rcS contains
```
# do not allow users to log in until the boot has completed
#DELAYLOGIN=no
```

**Comment by mbiebl** [comment] 2018-02-20 12:11
So much for consistency...

**Comment by sourcejedi** [comment] 2018-02-20 16:08
Hmm.

I think the main use for nologin was/is supposed to be system shutdown.  If you want to take it out of the boot process since (recent?) Debian wasn't actually using it, I don't object.

However, this makes me think of ordering dependencies on the session scope.  Initially because I had a concern about PID re-use races (#6803).  But ignore that - my main thought here is, if all we did was stop creating the nologin file during boot, I think you would then get stuck waiting for systemd-user-sessions.service.  So I'd be very curious, if you really know what happens when you reproduce your problem after disabling pam_nologin.

```
$ systemctl show session*.scope | grep After
After=systemd-user-sessions.service user-42.slice systemd-logind.service
```

I thought that one function of ordering login services, is that you might want `/home` to be available.  `home.mount` is not ordered relative to `basic.target`.  Instead, services that want all the fs's available are ordered after remote-fs.target.

```
$ systemctl cat systemd-user-sessions.service | grep After=
After=remote-fs.target nss-user-lookup.target network.target
```

I think if you login before then, you get an unfriendly message saying your home directory is not available, and dumping you in `/` without evaluating your user profile?  And the per-user systemd instance, `user@.service`, will not be very happy.

Dunno how much the ordering can or does go away, if you have no remote mounts that get ordered Before=remote-fs.target.

nologin is also touched by systemd-logind, but I think only for the shutdown path.  Which probably does match historic behaviour, of `/sbin/shutdown` preventing new logins in the last five minutes before shutdown.

**Comment by mbiebl** [comment] 2018-02-20 17:39
fwiw, I have no strong opinion on whether to keep /run/nologin during boot or not. I just wanted to provide some (historical) context from the Debian side.

**Comment by mbiebl** [comment] 2018-02-20 17:44
It might just be a bug in the old Debian sysv init scripts which no-one ever noticed so far. Looking at the bootmisc.sh script more closely, it also still uses /var/lib/initscripts/nologin and /etc/nologin was apparently previously a symlink to that location. 
It seems bootmisc.sh was never updated to use the new location /run/nologin. See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=743743

**Comment by XANi** [comment] 2018-02-21 09:59
@sourcejedi As for boot, that is easily fixable by adding simple drop-in with a dep, for those that need it. I so far haven't noticed anything bad happening after removing `systemd-nologin.conf` (and, well, it haven't existed in debian jessie at all with no drawbacks).

Altho I guess real solution would be checking if all paths mounted *at login time* to that particular user homedir are present. Because you can have users that do not have their home dir in /home. 

Network mounts complicate stuff even more. Say if you make an error in firewall setup and on next boot /home fails to mount you do not want to block *all* the users because then sysadmin can't log in to check what is going on. Nologin ain't solving any of those and solution that would would probably be pretty complex as at the very least you'd have to have list of users always allowed to log in.

Shutdown is whole other can of worms. Currently, SSH is generally first thing that gets turned off (because generally no other service depends on it) so you don't *really* need nologin to get same result.

Which is good in principle (altho a bit of an accident) but when something wrong happens, like service doesn't want to shut down, in BEST case you just wait few minutes, in WORST, you end up with server that won't reboot and no way to log in to it.

There are also other "interesting" things like distros in general turning off firewall on shutdown, which has no goddamn sense (why would you remove security rules that block access to services at any point after boot?). I mean cleanly stopping daemon (if a given iptables wrapper works as a demon), sure, but removing rules itself is pointless (altho not that it matters as network itself usually goes down right after)

**Comment by sourcejedi** [comment] 2018-02-21 10:43
Ah sorry, you're disabling `tmpfiles.d/systemd-nologin.conf`.  Same question though.  _Does this actually help you proceed_ in your problem case, _or does the login process instead hang waiting for `systemd-user-sessions.service`?_

>  I guess real solution would be checking if all paths mounted at login time to that particular user homedir are present. Because you can have users that do not have their home dir in /home.

We don't wait on `home.mount` specifically, we wait on `remote-fs.target` i.e. everything.  `httpd.service`, `libvirtd.service` tend to do the same.

> /home fails to mount you do not want to block all the users because then sysadmin can't log in to check what is going on. Nologin ain't solving any of those and solution that would would probably be pretty complex as at the very least you'd have to have list of users always allowed to log in.

The deps I'm referring to are After= and Wants=, not Requires=.  If something _fails_, then we'll still proceed.  But we wait for everything (i.e. all fs listed as auto in fstab, which get generated into mount units with appropriate dependencies) to fail or succeed first.

I'm explaining why I'd be surprised if removing nologin it actually helped this case in systemd.  
I wasn't trying to say nologin really achieves anything at boot time... though thinking about it, isn't it preferable for your case to get a specific error message, rather than a mysterious hang?

**Comment by XANi** [comment] 2018-02-21 11:42
@sourcejedi yes, it did help, now I can log in almost instantly after network is up (else I wouldn't be asking if it is needed ;)  (debian stretch on systemd 232)

"Specific error message" would help. `System is booting up. See pam_nologin(8)` is NOT helping.

My first reaction was, of course, `man pam_nologin`. Which said NOTHING about what created or removed that file on boot. So I went on looking in usual systemd places, `/lib` and `/etc` to find nothing and only after grepping `/` I've found that

Googling it just returns a bunch of confused ubuntu users and someone recommending removing this file. So I overrode it by symlinking `/etc/tmpfiles.d/systemd-nologin.conf` to dev null, rebooted and it worked.

**Comment by sourcejedi** [comment] 2018-02-21 11:54
Consider me surprised.  Can you show the logs?

We're interested in the relative time of `systemd-user-sessions.service`, which should appear in the logs as "Permit User Sessions".  That's the service which deletes nologin.  Your user session unit should show up like "Started Session 2 of user alan."  My hypothesis is that the session start will always be after the systemd-user-sessions start.

What you seem to be saying is that you're able to start a session _before_ systemd-user-sessions, once you have disabled/removed `tmpfiles.d/systemd-nologin.conf` so that pam_nologin doesn't stop you.

**Comment by sourcejedi** [comment] 2018-02-21 11:54
By logs I mean `journalctl -b` or so.

**Comment by XANi** [comment] 2018-02-21 12:09
@sourcejedi I'm not up to anonymizying 9k lines of log, anything in particular I should look for ?

It's a KVM hypervisor and with ISCSI connected device names go all the way up to `/dev/sdmp` so there is plenty to spam at boot.

Or just ` ln -s /dev/null /etc/tmpfiles.d/systemd-nologin.conf` (that's pretty much what I did) and reboot your machine/VM

**Comment by sourcejedi** [comment] 2018-02-21 12:42
Lines (preserving relative order) which match

1. Started Permit User Sessions
2. Started Session ...

and if you can, a few other lines relevant to starting this specific session for context... the "Start_ing_" message as well, ssh/audit/pam login messages.

Again, my hypothesis is they will always be in this order.

What you seem to be saying is that you're able to get "Started Session ..." for your user login, before "Started Permit User Sessions".

Or alternatively that you're able to get a shell prompt as a normal user before the corresponding "Started Session ...".  That would be shown by you being able to log in, run `systemctl status systemd-user-sessions`, and see that it is not yet activated.  (Instead it shows "waiting" or "activat_ing_" or something).

I sometimes use `journalctl -b -u init.scope` to just get the logs from PID 1, which would include both of these.  I think they'd be less sensitive (at least easier to check for that), though it might include some handling of your many device units.

Please note, this tracker is usually for the last two upstream versions of systemd only.  I'm assuming the relevant units on your system are the same (including the session scope created dynamically by systemd-logind); I don't think this stuff has changed very recently though.

**Comment by sourcejedi** [comment] 2018-02-21 12:43
github and my mouse are conspiring against me

**Comment by XANi** [comment] 2018-02-21 13:35
> What you seem to be saying is that you're able to get "Started Session ..." for your user login, before "Started Permit User Sessions".

No. I'm saying "I masked file that creates /run/nologin and I can now log on immediately instead of waiting". Nothing more, nothing less, I don't know systemd internals well enough to tell anything more.

From start of the network: (i've omitted iscsid/multipath spam)
```
Feb 21 12:29:09 hqblade202 systemd[1]: Reached target Network.
Feb 21 12:29:09 hqblade202 systemd[1]: Starting OpenBSD Secure Shell server...
Feb 21 12:29:09 hqblade202 systemd[1]: Starting The Marionette Collective...
Feb 21 12:29:09 hqblade202 systemd[1]: Reached target Network is Online.
Feb 21 12:29:09 hqblade202 systemd[1]: Starting iSCSI initiator daemon (iscsid)...
Feb 21 12:29:09 hqblade202 systemd[1]: Starting Prefetch new Ksplice updates...
Feb 21 12:29:09 hqblade202 systemd[1]: Starting Statistics collection and monitoring daemon...
Feb 21 12:29:09 hqblade202 systemd[1]: Starting Nagios remote plugin execution daemon...
Feb 21 12:29:09 hqblade202 systemd[1]: Starting /etc/rc.local Compatibility...
Feb 21 12:29:09 hqblade202 sshd[1438]: Server listening on 0.0.0.0 port 22.
Feb 21 12:29:09 hqblade202 sshd[1438]: Server listening on :: port 22.
Feb 21 12:29:09 hqblade202 systemd[1]: Started OpenBSD Secure Shell server.
Feb 21 12:29:09 hqblade202 systemd[1]: Started Nagios remote plugin execution daemon.
Feb 21 12:29:09 hqblade202 systemd[1]: Started iSCSI initiator daemon (iscsid).
Feb 21 12:29:09 hqblade202 systemd[1]: Starting Login to default iSCSI targets...
Feb 21 12:29:10 hqblade202 rc.local[1433]: [18B blob data]
Feb 21 12:29:10 hqblade202 systemd[1]: Started /etc/rc.local Compatibility.
Feb 21 12:29:10 hqblade202 sshd[1626]: Accepted publickey for xani from 1.2.3.4 port 57572 ssh2: RSA SHA256:xxx
Feb 21 12:29:10 hqblade202 sshd[1626]: pam_unix(sshd:session): session opened for user xani by (uid=0)
Feb 21 12:29:13 hqblade202 systemd[1]: Started The Marionette Collective.
Feb 21 12:29:14 hqblade202 systemd-logind[854]: New session 1 of user xani.

```
(I had ssh running in a loop, that is why you see login just after network connected)
then a metric shitton of
```
Feb 21 12:29:25 hqblade202 systemd[8172]: Failed to open directory /home/xani/.config/systemd/user/dev-mapper-hqstorwize1\x2dhq\x2dfw\x2dteamcity\x2dsystem.device.wants: Permission denied
Feb 21 12:29:25 hqblade202 systemd[8172]: Failed to open directory /home/xani/.config/systemd/user/dev-mapper-hqstorwize1\x2dhq\x2dfw\x2dteamcity\x2dsystem.device.requires: Permission denied
Feb 21 12:29:25 hqblade202 systemd[8172]: Failed to open directory /home/xani/.local/share/systemd/user/dev-mapper-hqstorwize1\x2dhq\x2dfw\x2dteamcity\x2dsystem.device.wants: Permission denied
Feb 21 12:29:25 hqblade202 systemd[8172]: Failed to open directory /home/xani/.local/share/systemd/user/dev-mapper-hqstorwize1\x2dhq\x2dfw\x2dteamcity\x2dsystem.device.requires: Permission denied
Feb 21 12:29:25 hqblade202 systemd[8172]: Failed to open directory /home/xani/.config/systemd/user/dev-disk-by\x2did-wwn\x2d0x600507630080881e4800000000000069.device.wants: Permission denied
Feb 21 12:29:25 hqblade202 systemd[8172]: Failed to open directory /home/xani/.config/systemd/user/dev-disk-by\x2did-wwn\x2d0x600507630080881e4800000000000069.device.requires: Permission denied
Feb 21 12:29:25 hqblade202 systemd[8172]: Failed to open directory /home/xani/.local/share/systemd/user/dev-disk-by\x2did-wwn\x2d0x600507630080881e4800000000000069.device.wants: Permission denied
Feb 21 12:29:25 hqblade202 systemd[8172]: Failed to open directory /home/xani/.local/share/systemd/user/dev-disk-by\x2did-wwn\x2d0x600507630080881e4800000000000069.device.requires: Permission denied
Feb 21 12:29:25 hqblade202 systemd[8172]: Failed to open directory /home/xani/.config/systemd/user/dev-disk-by\x2did-scsi\x2dhqstorwize1\x2dhq\x2dfw\x2dteamcity\x2dsystem.device.wants: Permission denied
```
which baffles me why it would try each of hundreds of files instead of just listing a fucking directory but whatever. Also it is not a "permission denied" as that dir doesn't even exist

**Comment by sourcejedi** [comment] 2018-02-21 14:31
fwiw i reported a spurious permission denied error for non-existent files on SELinux.  You might be seeing the same error, which we fixed upstream  #6450

**Comment by sourcejedi** [comment] 2018-02-21 16:04
At 12:29:09 you have `network.target` being started, which should precede `systemd-user-sessions.service`.  Then eventually we see `user@.service` starting `systemd --user`.

I see we don't tend to generate the intermediate "Start*ing* Session ...".  Sessions - well, scope units in general - can be a bit weird.

_But_, I don't see `Starting User Manager for UID` - this is the service which is spawning `systemd[8172]`, the `systemd --user` instance.  That should be somewhere before the flood of spurious permission denied messages that the instance generates.

So I'm not clear from this whether or not you have "Started Session"... before "Started Permit User Sessions", which is what I specifically asked about.  It might be easier to check in `journalctl -u init.scope` (or if that doesn't work on your version, `journalctl _PID=1`) around this time period, Feb 21 12:29:08 through 12:29:30.

"systemd-logind[854]: New session 1 of user xani." is still before the wait for `systemd-user-sessions.service`, as far as I can see from the current code.

Thanks for showing and explaining the SSH-specific bits so clearly.

**Comment by XANi** [comment] 2018-02-21 16:16
@sourcejedi SELinux is off on that machine

As for User manager, yes, it is there, just after what I pasted before. With `init.scope` its:

```
Feb 21 14:35:51.737818 hqblade202 systemd[1]: Reached target Remote File Systems (Pre).
Feb 21 14:35:51.768944 hqblade202 systemd[1]: Reached target Remote File Systems.
Feb 21 14:35:51.801908 hqblade202 systemd[1]: Starting Bareos File Daemon service...
Feb 21 14:35:51.835535 hqblade202 systemd[1]: Starting LSB: exim Mail Transport Agent...
Feb 21 14:35:51.868473 hqblade202 systemd[1]: Starting Permit User Sessions...
Feb 21 14:35:51.917695 hqblade202 systemd[1]: Starting Virtualization daemon...
Feb 21 14:35:51.954498 hqblade202 systemd[1]: Started Permit User Sessions.
Feb 21 14:35:51.983916 hqblade202 systemd[1]: bareos-filedaemon.service: PID file /var/lib/bareos/bareos-fd.9102.pid not readable (yet?) after start: No such f
Feb 21 14:35:51.998848 hqblade202 systemd[1]: Started Getty on tty1.
Feb 21 14:35:52.028412 hqblade202 systemd[1]: Reached target Login Prompts.
Feb 21 14:35:52.057652 hqblade202 systemd[1]: Created slice User Slice of xani.
Feb 21 14:35:52.090381 hqblade202 systemd[1]: Started Session 2 of user xani.
Feb 21 14:35:52.120427 hqblade202 systemd[1]: Starting User Manager for UID 20110900...
Feb 21 14:35:52.151049 hqblade202 systemd[1]: Started Session 1 of user xani.
Feb 21 14:35:52.183080 hqblade202 systemd[1]: Started Bareos File Daemon service.
Feb 21 14:35:52.526364 hqblade202 systemd[1]: Started Virtualization daemon.
Feb 21 14:35:52.682054 hqblade202 systemd[1]: Started User Manager for UID 20110900.
Feb 21 14:35:52.711620 hqblade202 systemd[1]: Starting Suspend/Resume Running libvirt Guests...
Feb 21 14:35:52.869717 hqblade202 systemd[1]: Started LSB: exim Mail Transport Agent.
Feb 21 14:35:53.061556 hqblade202 systemd[1]: Started Suspend/Resume Running libvirt Guests.
Feb 21 14:35:53.234675 hqblade202 systemd[1]: Reached target Multi-User System.
```

Also notice that start of session 2 was logged before 1. And "started user manager" message should probably also include session number.

**Comment by sourcejedi** [comment] 2018-02-21 17:05
So if we look at the specific messages I was thinking of.  The program which removes `/run/nologin` runs, and _then_ in the next 0.2s or so, we see starts of the units for both the individual login sessions, and the systemd user manager which is shared between all sessions of the same user.

```
Feb 21 14:35:51.954498 hqblade202 systemd[1]: Started Permit User Sessions.
...
Feb 21 14:35:52.090381 hqblade202 systemd[1]: Started Session 2 of user xani.
...
Feb 21 14:35:52.120427 hqblade202 systemd[1]: Starting User Manager for UID 20110900...
...
Feb 21 14:35:52.151049 hqblade202 systemd[1]: Started Session 1 of user xani.
```

Therefore in this example, reconfiguring systemd to not create /run/nologin in early boot, will not change how early you would be able to create & activate these session units.

It doesn't show how much earlier `sshd` started - but I'm very suspicious that these sessions were created a bit longer than 0.2s ago, and their start was delayed until after "Started Permit User Sessions".

The other half of my hypothesis is that you were not able to interact with the shell before the "Started Session".  It would be equally weird if that was disproved; I really can't imagine that's how this stuff was written to work.

poettering seems to have the same thought I had about home directories, commenting on the PR.  Perhaps unfortunate that the discussion was split. https://github.com/systemd/systemd/pull/8232#issuecomment-367040803

**Comment by XANi** [comment] 2018-02-21 17:41
> Therefore in this example, reconfiguring systemd to not create /run/nologin in early boot, will not change how early you would be able to create & activate these session units.

Seems that is the case. So that would mean that creating it in the first place is pointless? As only difference is that in one case user just waits few seconds (...at worst, most machines boot much faster than this one) and in other they get logged out immediately, have to try again, and the

```
sshd[7704]: fatal: Access denied for user xani by PAM account configuration [preauth]
```
message is left in the logs. Which is another problem as that basically looks like someone tried to do something bad while in reality they just ran ssh command too early...

 
> It doesn't show how much earlier sshd started - but I'm very suspicious that these sessions were created a bit longer than 0.2s ago, and their start was delayed until after "Started Permit User Sessions".

SSH is started just after network target - look at the previous log. But first login indeed waited a bit, just I didn't noticed at first because it was running in `while` loop on other terminal

**Comment by poettering** [comment] 2018-02-21 18:51
BTW, I opened a PAM RFE bug now: https://github.com/linux-pam/linux-pam/issues/42

**Comment by poettering** [comment] 2018-02-21 18:53
I prepped PR #8244 now, which extends the /run/nologin messages a bit, as the messaging apparently has been considered less than ideal.

**Comment by poettering** [comment] 2018-02-21 19:05
> sshd[7704]: fatal: Access denied for user xani by PAM account configuration [preauth]

I figure a fix to pam_nologin should be easy that adds a log message by pam_nologin itself when this happens.

**Comment by sourcejedi** [comment] 2018-02-21 19:06
@poettering I repeat.  Both #8244 and https://github.com/linux-pam/linux-pam/issues/42 seem to claim that it was possible to login during the systemd boot process, if only you were root.  Where is *systemd* letting that happen?  My assumption would be that no-one can because of the ordering dependency of the session unit on systemd-user-sessions.service.  I looked at a `root` login on Fedora 27 and the session unit still showed as having this ordering dependency.

**Comment by sourcejedi** [comment] 2018-02-21 19:12
https://github.com/linux-pam/linux-pam/issues/42 could still be useful for the shutdown side however.  I probably even ranted about it in one of the half-written logind patches I have.

**Comment by poettering** [comment] 2018-02-21 19:55
> Both #8244 and linux-pam/linux-pam#42 seem to claim that it was possible to login during the systemd boot process, if only you were root. Where is systemd letting that happen?

logindis not bus activated, and pam_systemd is at least on fedora (and we suggest everywhere) marked as a PAM module whose failure should be ignored. That means: if you log in before logind is up then pam_systemd will fail but you will still be able to log in, but none of logind's session management then apply to you, you get a much "rawer" session then, akin to an sulogin session.

**Comment by sourcejedi** [comment] 2018-02-21 20:04
Cool!  That sounds like there is a window of weirdness when logind starts, and now `root` cannot log in while the misconfigured iscsi target or whatever is timing out.    Does systemd-logind.service want to gain `After=systemd-user-sessions.service`?

**Comment by sourcejedi** [comment] 2018-02-21 20:06
I guess it would mean the session units would want to switch as well, to being ordered `After=systemd-logind.service`

**Comment by poettering** [comment] 2018-02-21 22:39
> Does systemd-logind.service want to gain After=systemd-user-sessions.service?

The session scopes already are. We should parallelize as much as we can, and hence place only deps we need, and I don't see why logind would benefit from such a dep.

**Comment by sourcejedi** [comment] 2018-02-22 08:48
Then why are you saying that exempting root/wheel from `nologin` is useful during bootup?  They will not be able to login because their session units will be blocked until `nologin` is deleted anyway.  _Unless_ they manage to hit a window between when `sshd` started, and `nss-user-lookup.target` -> `logind` started.

It leaves the behaviour that was reported, and that you're working on enhancing, as a race condition between nss-user-lookup.target and network.target+remote-fs.target.  Surely if we are working on this, we need to find some way to make it deterministic?

**Comment by poettering** [comment] 2018-02-22 09:26
> Then why are you saying that exempting root/wheel from nologin is useful during bootup? They will not be able to login because their session units will be blocked until nologin is deleted anyway.

Their session units are created by logind, triggered by pam_systemd. If logind is not running pam_systemd will fail, and now scope units are created, hence no ordering takes effect.

**Comment by sourcejedi** [comment] 2018-02-22 11:19
> > Then why are you saying that exempting root/wheel from nologin is useful during bootup? They will not be able to login because their session units will be blocked until nologin is deleted anyway.

> Their session units are created by logind, triggered by pam_systemd. If logind is not running pam_systemd will fail, and now scope units are created, hence no ordering takes effect.

@poettering Yes, I understood that.  My point remains.  I highly suggest re-reading the next sentence I had written

> > Then why are you saying that exempting root/wheel from nologin is useful during bootup? They will not be able to login because their session units will be blocked until nologin is deleted anyway.  _Unless_ they manage to hit a window between when `sshd` started, and `nss-user-lookup.target` -> `logind` started.

but I can also try to rephrase it more rigorously if that is not clear.

You seem to be arguing to let privileged users get past the PAM denial - which was including an explanatory message which implicitly invited a retry, and can be googled for - so that we can silently hang the login process for X minutes instead.  But you have not explained why the silent hang is desirable, and whether you consider it sufficient to address this report by @XANi.

IMO ssh users are able to notice the difference between 

1. Instant "Connection refused", 5 second "no route to host" timeout, or even TCP/IP connection timeout with no authentication prompt
2. a silent X minute wait following successful SSH authentication.

IMO, us promoting the latter as a special case to learn about when they are logging in as a privileged user during boot is not a good plan to make them happy.  _Especially_ if we promote it with the justification of making boot slightly faster when everything goes right.

## Sequence of events, as I understand it

logind gets

`After=basic.target nss-user-lookup.target user.slice ...`

Let us ignore `nss-user-lookup.target`.  It's not relevant on a simple default install of Fedora.  On my laptop `systemctl show -p After nss-user-lookup.target` shows nothing.  (I can't find it in the logs, but the time it is marked active is before any of the post-initrd activation logs, including the network).

Then the only significant ordering dependency that logind has is `basic.target`.  Let us consider logind as having started immediately after basic.target is reached.

Similarly assume that network.target came up immediately, allowing sshd.service to start without delay.

Consider the window where it is possible to log in through `sshd` before `logind` has started, and hence avoid being put in a session unit with After=systemd-user-sessions.service.  In this example, that window of time is negligible or empty.

By contrast, systemd-user-sessions.service is ordered `After=remote-fs.target`.  remote-fs.target is not ordered before basic.target.  Therefore let us imagine systemd-user-sessions.service as starting X minutes after basic.target, due to misconfigured-netdev-fs-with-X-minute-timeout.mount.

As I understand it, this is the sequence of events which led to this report by @XANi.  We have a X minute window where logins by all users would be delayed - unless their login is failed by an earlier pam module instead.

**Comment by XANi** [comment] 2018-02-22 12:12
> As I understand it, this is the sequence of events which led to this report by @XANi. We have a X minute window where logins by all users would be delayed - unless their login is failed by an earlier pam module instead.

That seems to be gist of it. I've only noticed it on that particular machine because on others that phase is just too short to matter (and in that case pam_nologin makes even less sense as it would deny users for 1-2 seconds or less, instead of just making them wait a second)

**Comment by sourcejedi** [comment] 2018-02-22 13:34
My feeling is the post-authentication delay would have been harder for XANi to trace to systemd's choices, but not necessarily less annoying.

Sometimes there may be a reason for developers to effectively obfuscate problems and rely on the user to wait/retry/whatever.  But as a developer I would like to be able to follow the reasoning.  In this case I'm struggling to do so and I think the counterargument is more sound.

---

Re-opened as per @keszybz.

> I replaced "Fixes" with "See", because I think #8228 needs a bit more discussion. We can close it later. https://github.com/systemd/systemd/pull/8244#issuecomment-367678737

**Comment by keszybz** [comment] 2018-02-23 11:03
> keszybz closed this in #8244 22 hours ago

Hmm, that's a bug in the github interface, I guess. I don't think it should close an issue if "Closes #..." is not in any of the merged commits.

**Comment by Daniel-Abrecht** [comment] 2018-02-23 12:55
> Hmm, that's a bug in the github interface, I guess. I don't think it should close an issue if "Closes #..." is not in any of the merged commits.

Even though none of the merged commits contained "closes" or "fixes", the first comment aka description of the pull request #8244 contained "Fixes: #8228".

From the github page https://help.github.com/articles/closing-issues-using-keywords/:
>You can include keywords in your pull request titles and descriptions, as well as commit messages, to automatically close issues in GitHub.

The first comment was the description, the description contained "fixes", therefore the issue was closed. I think everything worked exactly as intended.

**Comment by poettering** [comment] 2018-03-21 10:43
So, is there anything left on this issue to discuss? I think making pam_nologin honour group membership in "wheel" (or some other group, don't care) should suffice to solve this properly.

During early-boot (i.e. single user mode) logind is not started and not activatable, hence pam_systemd.so will be skipped and we hence allow root/wheel to log in just fine, and this is the most important case.

In the time-frame after early-boot finished, but logind isn't yet up root/wheel logins will be delayed possibly, but only until the dbus method call times out. if it does, logins will be permitted anyway for root/wheel.

Hence I think we are good, no? What is there left to discuss for systemd?

**Comment by sourcejedi** [comment] 2018-03-21 16:39
(If that's the most important case, it sounds like the more important issue is one not mentioned here, #7115.  It's interesting that you're confident PAM would work appropriately in "single user mode"... I guess it comes up if your muscle memory has you typing `sudo` inside the sulogin shell, but I'm not sure how you'd notice other than that).

So I didn't anticipate the default dbus method timeout (25 seconds). That's what was missing from your explanation for me to understand.

How can I confirm that logind will not be bus-activated though? What's the implication of the Debian patch that says it re-enables bus activation, and that on Fedora I've seen dbus activate the service?  

```
# systemctl isolate multi-user.target
# systemctl stop systemd-logind
# systemctl is-active systemd-logind
active
# journalctl -b | grep -E "Login Service|login1" | tail -n 5
Mar 21 15:54:34 fedora27-vm systemd[1]: Stopped Login Service.
Mar 21 15:54:37 fedora27-vm dbus-daemon[591]: [system] Activating via systemd: service name='org.freedesktop.login1' unit='dbus-org.freedesktop.login1.service' requested by ':1.72' (uid=0 pid=1630 comm="sudo systemctl is-active systemd-logind " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
Mar 21 15:54:37 fedora27-vm systemd[1]: Starting Login Service...
Mar 21 15:54:38 fedora27-vm dbus-daemon[591]: [system] Successfully activated service 'org.freedesktop.login1'
Mar 21 15:54:38 fedora27-vm systemd[1]: Started Login Service.
```

-- v237-git-something, installed on Fedora 27.

**Comment by sourcejedi** [comment] 2018-03-21 16:41
^ edited the above, I suspect the `sudo` invocation that followed `stop systemd-logind` is what re-activated it,

**Comment by poettering** [comment] 2018-11-20 18:34
Hmm, seems we dropped the ball on this one, sorry for this. let's finish the discussion here though.

> How can I confirm that logind will not be bus-activated though? What's the implication of the Debian patch that says it re-enables bus activation, and that on stock Fedora I've seen dbus activate the service?

Oh, it's bus-activatable, but not in early boot. For the simple reason that dbus-daemon doesn't run there, it's socket is established only after sysinit.target is reached.

Hence, I think we are safe on this one. Let's close this hence, hope everything is answered now.

**Closed as completed by poettering** 2018-11-20 18:34 UTC
