### ISSUE TITLE
Could not create runtime directory 'links': No such file or directory 

### ISSUE THREAD

**Issue by MichaelKohler** [systemd/systemd#7863] opened 2018-01-12 14:29 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

>  236.0-2

### Used distribution

> ArchLinux

### Expected behaviour you didn't see

> /run/systemd/netif/ subfolders should be written correctly at start and subsequent writes to it shouldn't fail

### Unexpected behaviour you saw

> Jan 12 13:40:19 SOME_HOSTNAME systemd[1]: Starting Network Service...
Jan 12 13:40:19 SOME_HOSTNAME systemd-networkd[117]: Could not create runtime directory 'links': No such file or directory
Jan 12 13:40:19 SOME_HOSTNAME systemd-networkd[117]: Could not create runtime directory 'leases': No such file or directory
Jan 12 13:40:19 SOME_HOSTNAME systemd-networkd[117]: Could not create runtime directory 'lldp': No such file or directory
Jan 12 13:40:19 SOME_HOSTNAME systemd-networkd[117]: gretap0: Failed to save link data to /run/systemd/netif/links/5: No such file or directory
Jan 12 13:40:19 SOME_HOSTNAME systemd-networkd[117]: tunl0: Failed to save link data to /run/systemd/netif/links/3: No such file or directory
Jan 12 13:40:19 SOME_HOSTNAME systemd-networkd[117]: wlan1: Failed to save link data to /run/systemd/netif/links/9: No such file or directory
Jan 12 13:40:19 SOME_HOSTNAME systemd-networkd[117]: gre0: Failed to save link data to /run/systemd/netif/links/4: No such file or directory
Jan 12 13:40:19 SOME_HOSTNAME systemd-networkd[117]: ip_vti0: Failed to save link data to /run/systemd/netif/links/6: No such file or directory
Jan 12 13:40:19 SOME_HOSTNAME systemd-networkd[117]: eth0: Failed to save link data to /run/systemd/netif/links/2: No such file or directory
Jan 12 13:40:19 SOME_HOSTNAME systemd-networkd[117]: sit0: Failed to save link data to /run/systemd/netif/links/7: No such file or directory
Jan 12 13:40:19 SOME_HOSTNAME systemd-networkd[117]: lo: Failed to save link data to /run/systemd/netif/links/1: No such file or directory
Jan 12 13:40:19 SOME_HOSTNAME systemd-networkd[117]: wlan0: Failed to save link data to /run/systemd/netif/links/8: No such file or directory

### Steps to reproduce the problem

> We have upgraded from 234.11-8, we did not see these fails in that version and links/lldp gets written correctly

```
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
```

```
ls -al | grep netif
drwxr-xr-x  2 systemd-network systemd-network  60 Jan 12 13:41 netif
```

```
ls -al netif
total 4
drwxr-xr-x  2 systemd-network systemd-network  60 Jan 12 13:41 .
drwxr-xr-x 17 root            root            440 Jan 12 13:40 ..
-rw-r--r--  1 systemd-network systemd-network  71 Jan 12 13:41 state
```

**Comment by shawnl** [comment] 2018-01-13 03:07
duplicate of #7761 ?

**Comment by yuwata** [comment] 2018-01-13 13:03
- Please paste the output of `systemctl cat systemd-networkd.service`.
- SELinux is enabled or disabled?
- What happens when `rm -rf  /run/systemd/netif` and then (re)start networkd.service?

**Comment by MichaelKohler** [comment] 2018-01-15 10:37
Output of systemctl cat systemd-networkd.service:

```
# /usr/lib/systemd/system/systemd-networkd.service
#  SPDX-License-Identifier: LGPL-2.1+
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Network Service
Documentation=man:systemd-networkd.service(8)
ConditionCapability=CAP_NET_ADMIN
DefaultDependencies=no
# systemd-udevd.service can be dropped once tuntap is moved to netlink
After=systemd-udevd.service network-pre.target systemd-sysusers.service systemd-sysctl.service
Before=network.target multi-user.target shutdown.target
Conflicts=shutdown.target
Wants=network.target

[Service]
Type=notify
Restart=on-failure
RestartSec=0
ExecStart=!!/usr/lib/systemd/systemd-networkd
WatchdogSec=3min
User=systemd-network
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_BROADCAST CAP_NET_RAW
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_BROADCAST CAP_NET_RAW
ProtectSystem=strict
ProtectHome=yes
ProtectControlGroups=yes
ProtectKernelModules=yes
MemoryDenyWriteExecute=yes
RestrictRealtime=yes
RestrictAddressFamilies=AF_UNIX AF_NETLINK AF_INET AF_INET6 AF_PACKET
SystemCallFilter=~@clock @cpu-emulation @debug @keyring @module @mount @obsolete @raw-io @reboot @swap
SystemCallArchitectures=native
LockPersonality=yes
RuntimeDirectory=systemd/netif
RuntimeDirectoryPreserve=yes

[Install]
WantedBy=multi-user.target
Also=systemd-networkd.socket
Alias=dbus-org.freedesktop.network1.service

# We want to enable systemd-networkd-wait-online.service whenever this service
# is enabled. systemd-networkd-wait-online.service has
# WantedBy=network-online.target, so enabling it only has an effect if
# network-online.target itself is enabled or pulled in by some other unit.
Also=systemd-networkd-wait-online.service
```

SELinux is disabled.

`rm -rf /run/systemd/netif` and then restarting it again leads to the same behaviour:

```
Jan 15 10:36:36 NEEO-50f76c4c systemd[1]: Starting Network Service...
Jan 15 10:36:36 NEEO-50f76c4c systemd-networkd[723]: Could not create runtime directory 'links': No such file or directory
Jan 15 10:36:36 NEEO-50f76c4c systemd-networkd[723]: Could not create runtime directory 'leases': No such file or directory
Jan 15 10:36:36 NEEO-50f76c4c systemd-networkd[723]: Could not create runtime directory 'lldp': No such file or directory
Jan 15 10:36:36 NEEO-50f76c4c systemd-networkd[723]: wlan0: Gained IPv6LL
Jan 15 10:36:36 NEEO-50f76c4c systemd-networkd[723]: eth0: Gained IPv6LL
Jan 15 10:36:36 NEEO-50f76c4c systemd-networkd[723]: wlan1: Failed to save link data to /run/systemd/netif/links/9: No such file or directory
Jan 15 10:36:36 NEEO-50f76c4c systemd-networkd[723]: ip_vti0: Failed to save link data to /run/systemd/netif/links/6: No such file or directory
Jan 15 10:36:36 NEEO-50f76c4c systemd-networkd[723]: sit0: Failed to save link data to /run/systemd/netif/links/7: No such file or directory
Jan 15 10:36:36 NEEO-50f76c4c systemd-networkd[723]: tun0: Failed to save link data to /run/systemd/netif/links/10: No such file or directory
Jan 15 10:36:36 NEEO-50f76c4c systemd-networkd[723]: eth0: Failed to save link data to /run/systemd/netif/links/2: No such file or directory
Jan 15 10:36:36 NEEO-50f76c4c systemd-networkd[723]: lo: Failed to save link data to /run/systemd/netif/links/1: No such file or directory
Jan 15 10:36:36 NEEO-50f76c4c systemd-networkd[723]: gretap0: Failed to save link data to /run/systemd/netif/links/5: No such file or directory
Jan 15 10:36:36 NEEO-50f76c4c systemd-networkd[723]: tunl0: Failed to save link data to /run/systemd/netif/links/3: No such file or directory
Jan 15 10:36:36 NEEO-50f76c4c systemd-networkd[723]: gre0: Failed to save link data to /run/systemd/netif/links/4: No such file or directory
Jan 15 10:36:36 NEEO-50f76c4c systemd-networkd[723]: wlan0: Failed to save link data to /run/systemd/netif/links/8: No such file or directory
Jan 15 10:36:36 NEEO-50f76c4c systemd-networkd[723]: Enumeration completed
Jan 15 10:36:36 NEEO-50f76c4c systemd[1]: Started Network Service.
Jan 15 10:36:36 NEEO-50f76c4c systemd-networkd[723]: lo: Failed to save link data to /run/systemd/netif/links/1: No such file or directory
Jan 15 10:36:36 NEEO-50f76c4c systemd-networkd[723]: wlan0: Failed to save link data to /run/systemd/netif/links/8: No such file or directory
Jan 15 10:36:36 NEEO-50f76c4c systemd-networkd[723]: tun0: Failed to save link data to /run/systemd/netif/links/10: No such file or directory
```

**Comment by yuwata** [comment] 2018-01-15 18:08
Hmm... Do you have any specific configuration for /run?
What happens when the following drop-in config is added:
```
[Service]
ExecStartPre=/usr/bin/mkdir /run/systemd/netif/baz
```
the directory can be created?
(btw, you can use `journalctl --no-hostname`)

**Comment by MichaelKohler** [comment] 2018-01-16 15:50
Thanks for your responses. Adding

```
ExecStartPre=/usr/bin/mkdir /run/systemd/netif/lldp
```

in the `[Service]` part leads to the following error:

```
systemd-networkd.service: Failed to apply ambient capabilities (before UID change): Invalid argument
systemd-networkd.service: Failed at step CAPABILITIES spawning /usr/bin/mkdir: Invalid argument
systemd-networkd.service: Control process exited, code=exited status=218
```

```
systemd-networkd.service: Start request repeated too quickly.
systemd-networkd.service: Failed with result 'exit-code'.
Failed to start Network Service.
systemd-networkd.socket: Failed with result 'service-start-limit-hit'.
```

This works perfectly well when started with ```PermissionsStartOnly=true```, but I don't think that's the correct solution here ;)

To test the write access I've enabled a shell for systemd-network and logged in with it, then I can do a  `/usr/bin/mkdir /run/systemd/netif/baz` without any problem, so it shouldn't be an access problem, correct?

Do you happen to have any other pointer?

**Comment by yuwata** [comment] 2018-01-16 17:30
Thanks. Could you paste that output of `uname -a`?

**Comment by MichaelKohler** [comment] 2018-01-16 17:35
> Thanks. Could you paste that output of uname -a?

Linux SOMEHOSTNAME 4.1.0-00002-gf790e8c #1 SMP Tue Jan 16 13:28:43 UTC 2018 armv7l GNU/Linux

**Comment by yuwata** [comment] 2018-01-16 17:42
How about `systemd-resolved.service`. Does it also fail with similar error message?

**Comment by yuwata** [comment] 2018-01-16 18:03
What happens when `CapabilityBoundingSet=` is commented out?

**Comment by MichaelKohler** [comment] 2018-01-16 18:55
Thanks for the response and your patch!

> How about systemd-resolved.service. Does it also fail with similar error message?

There are no logs indicating that this fails with the same error message without any changes. With adding the `ExecStartPre=/usr/bin/mkdir /run/systemd/netif/lldp` line it fails with the same message:

```
Jan 16 18:26:23  systemd[1]: Starting Network Name Resolution...
Jan 16 18:26:23  server[215]: /bin/java -Dsun.lang.ClassLoader.allowArraySyntax=true -Xmx192M -Xbootclasspath/a:../../../lib/framework/serverjvm15.jar: -cp ../../../lib/framework/fwtime.jar:
Jan 16 18:26:23  systemd[225]: systemd-resolved.service: Failed to apply ambient capabilities (before UID change): Invalid argument
Jan 16 18:26:23  systemd[225]: systemd-resolved.service: Failed at step CAPABILITIES spawning /usr/bin/mkdir: Invalid argument
Jan 16 18:26:23  systemd[1]: systemd-resolved.service: Control process exited, code=exited status=218
Jan 16 18:26:23  systemd[1]: systemd-resolved.service: Failed with result 'exit-code'.
Jan 16 18:26:23  systemd[1]: Failed to start Network Name Resolution.
```

> What happens when CapabilityBoundingSet= is commented out, or add CAP_CHOWN CAP_DAC_OVERRIDE CAP_FOWNER to CapabilityBoundingSet=?
(Please remove the ExecStartPre=... line added before.)

Commenting out CapabilityBoundingSet => directories can get created and I don't see any errors related to those in journalctl

Adding `CAP_CHOWN CAP_DAC_OVERRIDE CAP_FOWNER` to CapabilityBoundingSet works as well.

So it definitely has to do with the permissions and I'm confident your patch will fix it. Honestly, I don't think I have time to set up the whole building system to test this.

**Comment by yuwata** [comment] 2018-01-16 19:30
Hooray! Thank you for testing so many time.

**Comment by MichaelKohler** [comment] 2018-01-16 19:35
Thank you for the fast responses and the right pointers for testing!

**Closed as completed** 2018-01-17 18:18 UTC
Labels: network
