### ISSUE TITLE
autopkgtest failing with "Job for systemd-resolved.service failed"

### ISSUE THREAD

**Issue by filbranden** [systemd/systemd#9621] opened 2018-07-17 13:43 UTC
This is failing in recent PRs that don't touch anything related (e.g. #9612).

autopkgtest for the 3 archs fails with:

```
Job for systemd-resolved.service failed.
See "systemctl status systemd-resolved.service" and "journalctl -xe" for details.
dpkg: error processing package systemd (--configure):
 installed systemd package post-installation script subprocess returned error exit status 1
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Sub-process /usr/bin/dpkg returned an error code (1)
autopkgtest [11:27:06]: ERROR: erroneous package: installation of basic binaries failed, exit code 100
blame: https://git.launchpad.net/~pitti/systemd/+git/debian
badpkg: installation of basic binaries failed, exit code 100
```

I was wondering if this was the same as #9546, but considering we're now creating the dynamic users with tmpfiles again (#9586), I'd think that would take care of that problem... So this might be something else?

cc @martinpitt @mbiebl

**Comment by yuwata** [comment] 2018-07-17 14:41
Ugh, I thought I would mention the possibility of such error before v240 is released.

I do not know well about dpkg, but at least fedora rpm needs to stop relevant service before creating the users...

**Comment by mbiebl** [comment] 2018-07-17 14:43
I've committed this yesterday: 
https://salsa.debian.org/systemd-team/systemd/commit/9c13ce6441e786178fc8633e2ea88bfc5115363

Maybe the CI didn't have this commit?

**Comment by filbranden** [comment] 2018-07-17 15:15
If this is the branch, looks like your commit is present:
https://git.launchpad.net/~pitti/systemd/+git/debian/log/

**Comment by evverx** [comment] 2018-07-18 07:19
The CI uses [`$(cd debian/tmp/upstream; git describe | sed 's/^v//')-0`](https://salsa.debian.org/systemd-team/systemd/blob/master/debian/extra/checkout-upstream#L38) as the package version. It doesn't seem that `dpkg --compare-versions "$2" lt-nl "239-6"` is applicable here.

**Comment by evverx** [comment] 2018-07-18 07:57
Anyway, the script tries to stop `systemd-resolved` and `systemctl stop` appears to fail. I guess the only way to figure out what's going on is to run `journalctl` to see what's happened.

**Comment by mbiebl** [comment] 2018-07-18 08:32
Ah, I think I know what's going on. It's actually the start which fails.
bionic has an older systemd version which can fails to start newer resolved versions (due to the service lockdown that was applied in v239).
I need to add the stop / adduser / start after the daemon-reexec.

**Comment by mbiebl** [comment] 2018-07-18 09:12
Sorry for the breakage, I'll commit a fix later today once I verified that this works. Should be synced to the lp git in a couple of hours then.

**Comment by evverx** [comment] 2018-07-18 09:19
Thank you.

It was either `stop` or `start` that failed and I apparently guessed wrong :-) I'm wondering how you found out that it was actually `start`. It would seem that nothing in
```sh
active
Warning: Stopping systemd-networkd.service, but it can still be activated by:
  systemd-networkd.socket
active
active
Job for systemd-resolved.service failed.
```
could suggest that.

**Comment by mbiebl** [comment] 2018-07-18 09:38
@evverx A similar issue was filed for udev in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=903224 in Debian.

Fwiw, I can confirm that moving the start after daemon-reexec helped. I've committed a fix accordingly and @martinpitt forced an import, so CI should (hopefully) be unbroken again.
I'm thus closing this bug report.

**Closed as completed by mbiebl** 2018-07-18 09:38 UTC
Labels: ci

**Comment by filbranden** [comment] 2018-07-18 15:14
BTW perhaps it would be nice to add more logs to these runs so it's easier to troubleshoot them...

For example:
* Run the shell commands under `set -x`
* If anything goes wrong, run some commands (e.g. `journalctl -e` or `-n 300` etc.) to gather enough data to help tell what happened.

It would also be good to keep a pointer/URL (perhaps include in log output?) of the git repository with the scripts running there, so others could try to reproduce that as well...

Thanks for fixing this, much appreciated!

Cheers!
Filipe
