### ISSUE TITLE
Yellow color in journalctl is hard to read in a light terminal

### ISSUE THREAD

**Issue by ivan** [systemd/systemd#13561] opened 2019-09-14 22:58 UTC
**systemd version the issue has been seen with**
> 243

**Used distribution**
 > NixOS release-19.09 branch (2019-09-14)

**Expected behaviour you didn't see**
 > a readable color for yellow-highlighted messages as in systemd 242

**Unexpected behaviour you saw**
 > hard to read yellow color (see image)

![journalctl Screenshot_20190914_224509](https://user-images.githubusercontent.com/4458/64914500-b66e3500-d742-11e9-87d6-136fe95e1192.png)

**Steps to reproduce the problem**

Run konsole and set a light brown background; run `journalctl -b` and find a message highlighted in `ANSI_HIGHLIGHT_YELLOW`.

I believe this was changed to use the 256-color color `#185` in #12601, which as far as I know cannot be remapped to another color in konsole.

**Comment by cdown** [comment] 2019-09-20 16:14
I'm inclined to agree with you that we should probably stick with ANSI codes which are more trivially remapped by the user for their needs, but tagging @poettering and @keszybz since they were involved on the original discussion in #12601

**Comment by poettering** [comment] 2019-10-08 12:29
Well maybe this may sound dickish but maybe use a different, less problematic background color? Is this color from a standard color palette of some common terminal app?

**Comment by mbiebl** [comment] 2019-10-08 12:40
The other day someone brought up https://no-color.org/ on #nm IRC.
Maybe this could be something systemd supports?

**Comment by keszybz** [comment] 2019-10-08 13:37
> The other day someone brought up https://no-color.org/ on #nm IRC.
> Maybe this could be something systemd supports?

Sounds reasonable. A PR would be welcome ;)

> I believe this was changed to use the 256-color color #185 in #12601, which as far as I know cannot be remapped to another color in konsole.

The problem is that no matter what color is chosen, there will always be somebody for whom the color is not right. ANSI yellow might look better on konsole with your custom background, but it looks bad on other terminals.

**Comment by poettering** [comment] 2019-11-04 09:13
Still wondering if the selected choice of palette is a palette some popular terminal includes in the default set of palettes, or whether this is some locally put together palette?

otherwise, let's maybe close this...

**Comment by ivan** [comment] 2019-11-04 11:01
I don't know why fixing this would depend on finding a color scheme in a popular terminal that resembles the one I use. journalctl is an important program where users might need to read messages regardless of what background color they like, and I think the one I've got is totally reasonable :-)

If the previously-used paletted yellow is too often an unusable color (the only motivation I see is "it looks bad on other terminals" here), maybe another palletted color could be used, or perhaps the paletted yellow could not span the entire message text, or there could be an option to revert back to paletted colors.  I agree with your initial disinclination to use unthemable colors in https://github.com/systemd/systemd/pull/12601#discussion_r285627947

**Comment by poettering** [comment] 2019-11-04 11:09
ok, so I understand this is a manually put together palette? If so, I am much less inclined to do anything about this I must say...

**Comment by poettering** [comment] 2019-11-04 11:18
We have a way btw, do make the output readable on any weird palette, just set SYSTEMD_COLOR=0. I am not sure we need to support arbitrary, strange palettes beyond that..

**Comment by ivan** [comment] 2019-11-04 11:37
Ah, thanks, I see that is `SYSTEMD_COLORS` and not `SYSTEMD_COLOR`, also I did not find it in `man journalctl`.

I don't think this palette is particularly strange, the background is just slightly darker than e.g. Black on Light Yellow in konsole, where the contrast with journalctl's 256-color yellow isn't particularly good either (but doesn't reach unreadability).

I will just keep patching systemd and let someone else advocate for this if they wish.

**Comment by poettering** [comment] 2019-11-15 10:01
ok, let's turn this into a documentation issue, to move SYSTEMD_COLORS documentation into the env block described in the journalctl man page.

**Closed as completed** 2019-11-16 12:48 UTC
Labels: journal, documentation, util-lib

**Comment by rnhmjoj** [comment] 2019-11-17 12:52
I noticed this change and I too don't really like it: it's readable on my (dark) palette but it looks out of place nonetheless. I don't understand why you are not sticking to the 16 colors palette, which is designed to look good on the terminal background.

**Comment by keszybz** [comment] 2019-11-17 18:14
> I don't understand why you are not sticking to the 16 colors palette

Because it doesn't look good and is not legible in the standard color palettes that most people will use, because they never switch away from the default. If you modify your color palette and journalctl does not look OK for you, you can always use the environment variable to switch back to uncolored jouralctl output. We clearly cannot make everyone happy, so the only feasible options are to use no color, or to pick colors that work with the defaults.

**Comment by rnhmjoj** [comment] 2019-11-17 19:09
> We clearly cannot make everyone happy, so the only feasible options are to use no color, or to pick colors that work with the defaults.

Given the mechanism already in place an option could be to implement `SYSTEMD_COLORS=16` to limit the colors used. But I understand I'm a minority here and it's a rather immaterial problem.

Thank you for the reply.

**Comment by keszybz** [comment] 2019-11-18 08:08
> Given the mechanism already in place an option could be to implement SYSTEMD_COLORS=16 to limit the colors used

I would happilly merge a patch that adds support for `SYSTEMD_COLORS=16`...

**Comment by nsklaus** [comment] 2020-07-12 19:10
i have the same problem with journalctl.  (journalctl -b0 -p4)
i'm using a light background (#C2C2C2) and the yellow lines are difficult to read.
my terminal isn't set to use such a color, where does journalctl define the colors it uses ?

**Comment by garberw** [comment] 2020-09-15 15:11
All I want is to have an inverse-video xterm specifically WHITE background and BLACK text.  
It is very useful to see journalctl output in color but you can hardly see the 
(light yellow / slightly orange color) output (warnings?) for "journalctl -b -p 4" in xterm-256color.
Since I can barely even read the output, and I do not want to just output in black and white, 
(I know how to do that) this seems like a very basic requirement and not so trivial.
You must be using only about six colors, so an option (command line / environment variable /
config file) to set each of those six colors would be very nice.
Anyway, love systemd, and keep up the good work :-)

**Comment by keszybz** [comment] 2020-09-15 15:17
@garberw see https://bugzilla.redhat.com/show_bug.cgi?id=1859889.

**Comment by garberw** [comment] 2020-09-15 18:55
that article said it was up to the program designer (you) to choose a color palette which can be viewed on either light or dark background terminals.  in the mean time I have written scripts to change and reset the xterm:

[wg-background.zip](https://github.com/systemd/systemd/files/5227134/wg-background.zip)

**Comment by oliverpool** [comment] 2021-08-09 19:25
Since https://github.com/systemd/systemd/pull/17702 has been merged (released in version 248), you can use set the `SYSTEMD_COLORS` environement variable to `16` to accommodate your palette.

> Various tools now accept SYSTEMD_COLORS=16|256 to configure what colours are used in output.
