### ISSUE TITLE
Build error with 238 release

### ISSUE THREAD

**Issue by rezso** [systemd/systemd#8688] opened 2018-04-09 00:28 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 238

### Used distribution

> UHU-Linux

### In case of bug report: Expected behaviour you didn't see

> successful compilation

### In case of bug report: Unexpected behaviour you saw

`FAILED: src/core/core@sta/dbus-kill.c.o 
ccache cc  -Isrc/core/core@sta -Isrc/core -I../src/core -I. -I../ -Isrc/libsystemd-network -I../src/libsystemd-network -I../src/libsystemd/sd-network -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-device -I../src/libsystemd/sd-bus -Isrc/libudev -I../src/libudev -Isrc/udev -I../src/udev -Isrc/login -I../src/login -Isrc/timesync -I../src/timesync -Isrc/resolve -I../src/resolve -Isrc/journal -I../src/journal -Isrc/systemd -I../src/systemd -Isrc/shared -I../src/shared -Isrc/basic -I../src/basic -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O3 -Wextra -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wdeclaration-after-statement -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Wdate-time -Wnested-externs -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -fPIE -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Wno-error=nonnull -Werror=shadow -ffunction-sections -fdata-sections -include config.h -fPIC -pthread -MD -MQ 'src/core/core@sta/dbus-kill.c.o' -MF 'src/core/core@sta/dbus-kill.c.o.d' -o 'src/core/core@sta/dbus-kill.c.o' -c ../src/core/dbus-kill.c
In file included from ../src/basic/util.h:47:0,
                 from ../src/basic/hashmap.h:30,
                 from ../src/shared/bus-util.h:31,
                 from ../src/core/dbus-kill.c:21:
../src/basic/missing.h:528:17: error: expected identifier before numeric constant
 #define MS_MOVE 8192
`

### In case of bug report: Steps to reproduce the problem

> I tried with gcc 7.2 and 7.3, kernel 4.9.93 and 4.14.32. glibc: 2.26

**Comment by evverx** [comment] 2018-04-09 06:16
The issue seems to be a duplicate of https://github.com/systemd/systemd/issues/8507.

**Closed as completed by evverx** 2018-04-09 06:16 UTC
Labels: build-system, duplicate
