### ISSUE TITLE
pid1 should not output unicode glyphs to /dev/console if there's reason to assume that it can't draw unicode glyphs, in order to avoid � character during the boot process

### ISSUE THREAD

**Issue by mattia-b89** [systemd/systemd#6443] opened 2017-07-24 17:08 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 233.75, probably here before

### Used distribution

> Arch Linux
### In case of bug report: Expected behaviour you didn't see

> print normal characters during the boot

### In case of bug report: Unexpected behaviour you saw

> � character during the boot process

### In case of bug report: Steps to reproduce the problem

> boot with many kernel parameters, in order to have a long options line
> my experience: if I boot with these parameters: "root=PARTUUID=3a0ebdfc-e32f-4a35-a482-35dcfd8ee34a resume=PARTUUID=18f13113-dc7f-4138-8084-4e4a67c581ba elevator=bfq nowatchdog rw"
> the problem appears
> if I trim the options line to: "root=/dev/sda3 resume=/dev/sda2 elevator=bfq nowatchdog rw"
> the boot process is fine
> I use systemd-boot, so I'm talking about options array in the /boot/loader/entries/linux.conf file

**Comment by mattia-b89** [comment] 2017-07-24 17:21
I attach a photo: 
![img_20170724_191640](https://user-images.githubusercontent.com/545463/28535538-091fd42c-70a5-11e7-9e30-55d22db02b2e.jpg)

**Comment by mattia-b89** [comment] 2017-07-24 18:05
you can note the � characters on the top

**Comment by poettering** [comment] 2017-07-31 09:15
Hmm, this is the three-dot ellipsis unicode character ("…"), and your console apparently has no font loaded supporting basica unicode.

I figure we should add some code to ellipsize_mem() to use three traditional ASCII dots as fallback if the console doesn't do unicode, similar to the fallbacks we already have in place for drawing trees and stuff.

**Comment by arvidjaar** [comment] 2017-07-31 17:20
> fallback if the console doesn't do unicode

That's, unfortunately, not enough - it depends on actual font. E.g. relatively popular LatArCyrHeb **Unicode** font does not include ellipsis. Not sure this fallback is possible, unless there is easy way to query font for supported code positions.

**Comment by poettering** [comment] 2017-07-31 17:28
@arvidjaar, well, but isn't that something the maintainer of that font should deal with and fix? I mean, the ellipsis isn't precisely the most exotic unicode character. Moreover, unicode *does* define a way how to handle missing glyphs, precisely by drawing that strange question mark glyph instead, and I am not convinced we should second-guess that... Finally, if the font is undermaintained, maybe the distros should pick a different one?

**Comment by keszybz** [comment] 2017-07-31 17:40
We recommend eurlatgr since 25b47f96d9601ff566257b2a31bfb5f4bd25d661.

**Comment by mattia-b89** [comment] 2017-07-31 19:48
I have added FONT=eurlatgr in my vconsole.conf but I see � characters.

using `showconsolefont` on a VT, it shows no � characters
`vi /usr/share/kbd/consolefonts/README.eurlatgr` shows the ellipsis character … correctly

**Comment by mattia-b89** [comment] 2017-08-06 17:14
this likely because `eurlatgr` is the default console font...

**Comment by myllynen** [comment] 2017-09-06 08:49
Due to the 512-char limitation for console fonts creating a full-blown Unicode console font is not possible however when eurlatgr was created one of the goals when selecting glyphs to be included in the font was full support for systemd and that should still be the case.

I can't reproduce this on Fedora 26, adding a service with a long enough description shows ellipsis correctly. I don't think this is a general eurlatgr/systemd issue.

**Comment by poettering** [comment] 2017-09-15 11:28
So, given that eurlatgr is supposed to have this glyph these days I think we can drop this for v235, even though we should add some logic to PID 1 eventually to use fallback glyphs for its console status messages if it is determined that /dev/console is determined to lack the relevant unicode glyphs.

**Comment by myllynen** [comment] 2017-09-15 13:33
FWIW, the characters supported by eurlatgr are listed in its README file:

http://git.altlinux.org/people/legion/packages/kbd.git?p=kbd.git;a=blob;f=data/consolefonts/README.eurlatgr

**Comment by poettering** [comment] 2018-05-03 11:33
OK, since c30a49b2d019d8657f5a2ca1a3bfdd8bc7ca673c we now have a fallback to ASCII "..." over unicode "…" in place. However, on the console we'll still use the unicode version, under the assumption that this is actually OK with the most common fonts, and @myllynen indicated that this is indeed the case.

I also prepped #8894 which adds a comment to the relevant function clarifying that eurlatgr should be checked when adding a new glyph to systemd's usage, and that that font is the reference.

I think this means we can close this issue now. Yes, if the console font doesn't support "…" properly this set of changes won't change anything, but I think it's safe to assume (and documented) that the console supports that font now. 

Closing.

**Closed as completed by poettering** 2018-05-03 11:33 UTC
Labels: pid1, util-lib

**Comment by devZer0** [comment] 2024-04-16 14:59
> but I think it's safe to assume (and documented) that the console supports that font now.

@poettering , especially when troubleshooting a system , chances are likely that you only have 80x25 bios console, wich does not seem to support "..." unicode character
