### ISSUE TITLE
`SSID=` Does not work with with bonded interface

### ISSUE THREAD

**Issue by LaserEyess** [systemd/systemd#27466] opened 2023-04-30 17:33 UTC
### systemd version the issue has been seen with

253

### Used distribution

Arch

### Linux kernel version used

6.2.13-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

```
[Match]
SSID=MYSSID
```

Should work regardless of what interface type is being used.

My setup is a little strange but I essentially have the following goals:
 - When connected to my home network I want to use a bonded wired-wireless interface with wireless being an active backup for wired. This part *by itself* without any other files and without `SSID=` **works**
 - When connected to my home network I want to use a static IP address and allow for DNS registration on my home router
 - When connected to a public network I do not want to use the bonded interface, I want to use only a wireless interface with enhanced privacy settings. This part *by itself* and without `SSID=` **works**

### Unexpected behaviour you saw

systemd-networkd constantly disconnects and reconnects, making the network unusable. Once I combine the bonding configuration with the public-wireless configuration and differentiate them with `SSID=`, systemd-networkd is unable to create a stable network.

Log Snippet:
```
Apr 30 13:08:40 homura systemd-networkd[718]: wlan0: Configuring with /etc/systemd/network/20-wireless-public.network.
Apr 30 13:08:43 homura systemd-networkd[718]: wlan0: Connected WiFi access point: Basement (02:ec:da:f5:50:5a)
Apr 30 13:08:43 homura systemd-networkd[718]: wlan0: Gained carrier
Apr 30 13:08:43 homura systemd-networkd[718]: wlan0: Reconfiguring with /etc/systemd/network/10-wireless-home.network.
Apr 30 13:08:43 homura systemd-networkd[718]: wlan0: Link DOWN
Apr 30 13:08:43 homura systemd-networkd[718]: wlan0: Lost carrier
Apr 30 13:08:43 homura systemd-networkd[718]: wlan0: Reconfiguring with /etc/systemd/network/20-wireless-public.network.
Apr 30 13:08:43 homura systemd-networkd[718]: wlan0: Link UP
Apr 30 13:08:43 homura systemd-networkd[718]: wlan0: Gained carrier
Apr 30 13:08:44 homura systemd-networkd[718]: wlan0: Lost carrier
Apr 30 13:08:44 homura systemd-networkd[718]: wlan0: DHCPv6 lease lost
Apr 30 13:08:49 homura systemd-networkd[718]: wlan0: Connected WiFi access point: Basement (02:ec:da:f5:50:5a)
Apr 30 13:08:49 homura systemd-networkd[718]: wlan0: Gained carrier
Apr 30 13:08:49 homura systemd-networkd[718]: wlan0: Reconfiguring with /etc/systemd/network/10-wireless-home.network.
Apr 30 13:08:49 homura systemd-networkd[718]: wlan0: DHCPv6 lease lost
Apr 30 13:08:49 homura systemd-networkd[718]: wlan0: Link DOWN
Apr 30 13:08:49 homura systemd-networkd[718]: wlan0: Lost carrier
Apr 30 13:08:49 homura systemd-networkd[718]: wlan0: Link UP
Apr 30 13:08:49 homura systemd-networkd[718]: wlan0: Gained carrier
Apr 30 13:08:49 homura systemd-networkd[718]: wlan0: Reconfiguring with /etc/systemd/network/20-wireless-public.network.
Apr 30 13:08:49 homura systemd-networkd[718]: wlan0: Link DOWN
Apr 30 13:08:49 homura systemd-networkd[718]: wlan0: Lost carrier
Apr 30 13:08:49 homura systemd-networkd[718]: wlan0: Link UP
Apr 30 13:08:49 homura systemd-networkd[718]: wlan0: Gained carrier
Apr 30 13:08:50 homura systemd-networkd[718]: wlan0: Lost carrier
Apr 30 13:08:50 homura systemd-networkd[718]: wlan0: DHCPv6 lease lost
Apr 30 13:08:51 homura systemd-networkd[718]: wlan0: Connected WiFi access point: Basement (02:ec:da:f5:50:5a)
Apr 30 13:08:51 homura systemd-networkd[718]: wlan0: Gained carrier
Apr 30 13:08:51 homura systemd-networkd[718]: wlan0: Reconfiguring with /etc/systemd/network/10-wireless-home.network.
```

Full debug log w/ `SYSTEMD_LOG_LEVEL=debug`: https://0x0.st/HPpg.log

### Steps to reproduce the problem

I used the following configuration

`00-bond.netdev`
```
[NetDev]
Name=bond
Kind=bond

[Bond]
Mode=active-backup
MIIMonitorSec=1s
```

`00-bond.network`
```
[Match]
Name=bond
SSID=Basement

[Link]
RequiredForOnline=degraded-carrier

[Network]
DHCP=yes
IPv6AcceptRA=yes
```

`10-wireless-home.network`
```
[Match]
Type=wlan
SSID=Basement

[Link]
RequiredForOnline=false

[Network]
Bond=bond
PrimarySlave=false
IgnoreCarrierLoss=5s
```

`20-wireless-public`
```
[Match]
Type=wlan
SSID=!Basement

[Network]
DHCP=yes

IPv6AcceptRA=true
IPv6PrivacyExtensions=true

[DHCPv4]
# These settings ensure privacy
Anonymize=true

# Use DNS is needed for captive portal networks
UseDNS=true
UseRoutes=true
UseGateway=true
UseTimezone=true

[IPv6AcceptRA]
# Needed for captive portals
UseDNS=true

[DHCPv6]
UseDNS=true
UseHostname=false
UseDomains=false
```

Adding `SSID=!Basement` to `20-wireless-public.network` does not work.

I am using iwd to manage my wlan device, but the configurations are all default

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
See above for logs
```

**Comment by yuwata** [comment] 2023-05-22 04:23
Duplicate of #23255 and #19832.

Please try to use `SSID=*` instead of `SSID=!Basement`. Closing. If it does not work, feel free to request to reopen this.

**Closed as completed by yuwata** 2023-05-22 04:23 UTC
Labels: bug 🐛, network, duplicate
