### ISSUE TITLE
systemd is too fast for machinectl reboot

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#2813] opened 2016-03-09 01:19 UTC
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> v229
### Used distribution

> Arch Linux
### Bugreport

Rebooting a machine via `machinectl reboot` does not work:

```
root@motoko / # machinectl start work
root@motoko / # machinectl
MACHINE    CLASS     SERVICE       
testserver container systemd-nspawn
work       container systemd-nspawn

2 machines listed.
root@motoko / # machinectl reboot work
root@motoko / # machinectl
MACHINE    CLASS     SERVICE       
testserver container systemd-nspawn

1 machines listed.
root@motoko / # machinectl status work
Could not get path to machine: No machine 'work' known
1 root@motoko / #                                          
```

`journalctl`:

```
Mar 09 02:19:04 motoko systemd-nspawn[25470]: Rebooting.
Mar 09 02:19:04 motoko systemd-networkd[16511]: ve-work: Lost carrier
Mar 09 02:19:04 motoko systemd-timesyncd[368]: Network configuration changed, trying to establish connection.
Mar 09 02:19:04 motoko systemd-timesyncd[368]: Synchronized to time server 37.120.191.49:123 (2.arch.pool.ntp.org).
Mar 09 02:19:04 motoko systemd[1]: systemd-nspawn@work.service: Service hold-off time over, scheduling restart.
Mar 09 02:19:04 motoko systemd[1]: Stopped Container work.
Mar 09 02:19:04 motoko systemd[1]: Starting Container work...
Mar 09 02:19:04 motoko systemd-nspawn[25750]: Failed to register machine: Machine 'work' already exists
Mar 09 02:19:04 motoko systemd[1]: systemd-nspawn@work.service: Main process exited, code=exited, status=1/FAILURE
Mar 09 02:19:04 motoko systemd[1]: Failed to start Container work.
Mar 09 02:19:04 motoko systemd[1]: systemd-nspawn@work.service: Unit entered failed state.
Mar 09 02:19:04 motoko systemd[1]: systemd-nspawn@work.service: Failed with result 'exit-code'.
Mar 09 02:19:04 motoko kernel: IPv6: ADDRCONF(NETDEV_UP): ve-work: link is not ready
Mar 09 02:19:04 motoko systemd-timesyncd[368]: Network configuration changed, trying to establish connection.
Mar 09 02:19:04 motoko systemd[1]: Stopped Container work.
Mar 09 02:19:04 motoko systemd-machined[7665]: Machine work terminated.
Mar 09 02:19:04 motoko systemd-timesyncd[368]: Synchronized to time server 37.120.191.49:123 (2.arch.pool.ntp.org).
Mar 09 02:19:04 motoko systemd-timesyncd[368]: Network configuration changed, trying to establish connection.
Mar 09 02:19:04 motoko systemd-timesyncd[368]: Synchronized to time server 37.120.191.49:123 (2.arch.pool.ntp.org).
Mar 09 02:19:12 motoko systemd[431]: Started DWM statusbar.
```

**Comment by Ram-Z** [comment] 2016-04-14 18:32
Can confirm on Chakra Linux, `systemd 228`.

**Comment by poettering** [comment] 2016-04-15 11:18
Hmm, this is strange. It appears as if the container wasn't properly removed from the list of machines in machined's database.

Any chance you could turn on debug logging in machined and try to reproduce the issue? To turn on debug logging in machined, add in a drop-in for it (via systemctl edit) and set Environment=SYSTEMD_LOG_LEVEL=debug for it.

**Comment by poettering** [comment] 2016-04-15 11:56
So this actually sounds like a duplicate of #2809, i.e. the machine is not removed correctly from machine list machined maintains. Let's continue this in #2809.

**Comment by poettering** [comment] 2017-05-12 13:48
Closing as duplicate

**Closed as completed by poettering** 2017-05-12 13:48 UTC
Labels: bug 🐛, machine, duplicate
