### ISSUE TITLE
sd-bus API documentation is incomplete

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#235] opened 2015-06-16 21:29 UTC
<strike>In v221, the sd-bus API has been made public, but there is no documentation yet.</strike>
- [x] sd-bus (entry point)
- [ ] sd_bus_get_allow_interactive_authorization
- [ ] sd_bus_start
- [ ] sd_bus_close
- [ ] sd_bus_try_close
- [x] sd_bus_ref
- [x] sd_bus_unref
- [ ] sd_bus_is_open
- [ ] sd_bus_get_bus_id
- [ ] sd_bus_get_scope
- [ ] sd_bus_get_tid
- [ ] sd_bus_get_owner_creds
- [ ] sd_bus_send
- [ ] sd_bus_send_to
- [x] sd_bus_call
- [x] sd_bus_call_async
- [x] sd_bus_get_fd
- [ ] sd_bus_get_events
- [ ] sd_bus_get_timeout
- [x] sd_bus_process
- [ ] sd_bus_process_priority
- [ ] sd_bus_wait
- [ ] sd_bus_flush
- [ ] sd_bus_get_current_slot
- [ ] sd_bus_get_current_message
- [ ] sd_bus_get_current_handler
- [ ] sd_bus_get_current_userdata
- [ ] sd_bus_attach_event
- [ ] sd_bus_detach_event
- [ ] sd_bus_get_event
- [ ] sd_bus_add_filter
- [x] sd_bus_add_match
- [ ] sd_bus_add_object
- [ ] sd_bus_add_fallback
- [ ] sd_bus_add_object_vtable
- [ ] sd_bus_add_fallback_vtable
- [ ] sd_bus_add_node_enumerator
- [ ] sd_bus_add_object_manager
- [ ] sd_bus_slot_ref
- [ ] sd_bus_slot_unref
- [ ] sd_bus_slot_get_bus
- [ ] sd_bus_slot_get_userdata
- [ ] sd_bus_slot_set_userdata
- [ ] sd_bus_slot_get_description
- [ ] sd_bus_slot_set_description
- [ ] sd_bus_slot_get_current_message
- [ ] sd_bus_slot_get_current_handler
- [ ] sd_bus_slot_get_current_userdata
- [ ] sd_bus_message_new_signal
- [ ] sd_bus_message_new_method_call
- [ ] sd_bus_message_new_method_return
- [ ] sd_bus_message_new_method_error
- [ ] sd_bus_message_new_method_errorf
- [ ] sd_bus_message_new_method_errno
- [ ] sd_bus_message_new_method_errnof
- [ ] sd_bus_message_ref
- [ ] sd_bus_message_unref
- [ ] sd_bus_message_get_type
- [x] sd_bus_message_get_cookie
- [x] sd_bus_message_get_reply_cookie
- [ ] sd_bus_message_get_priority
- [ ] sd_bus_message_get_expect_reply
- [ ] sd_bus_message_get_auto_start
- [ ] sd_bus_message_get_allow_interactive_authorization
- [ ] sd_bus_message_get_signature
- [ ] sd_bus_message_get_path
- [ ] sd_bus_message_get_interface
- [ ] sd_bus_message_get_member
- [ ] sd_bus_message_get_destination
- [ ] sd_bus_message_get_sender
- [ ] sd_bus_message_get_error
- [ ] sd_bus_message_get_errno
- [x] sd_bus_message_get_monotonic_usec
- [x] sd_bus_message_get_realtime_usec
- [x] sd_bus_message_get_seqnum
- [ ] sd_bus_message_get_bus
- [ ] sd_bus_message_get_creds
- [ ] sd_bus_message_is_signal
- [ ] sd_bus_message_is_method_call
- [ ] sd_bus_message_is_method_error
- [ ] sd_bus_message_is_empty
- [ ] sd_bus_message_has_signature
- [ ] sd_bus_message_set_expect_reply
- [ ] sd_bus_message_set_auto_start
- [ ] sd_bus_message_set_allow_interactive_authorization
- [ ] sd_bus_message_set_destination
- [ ] sd_bus_message_set_priority
- [x] sd_bus_message_append
- [x] sd_bus_message_append_basic
- [x] sd_bus_message_append_array
- [x] sd_bus_message_append_array_space
- [x] sd_bus_message_append_array_iovec
- [x] sd_bus_message_append_array_memfd
- [x] sd_bus_message_append_string_space
- [x] sd_bus_message_append_string_iovec
- [x] sd_bus_message_append_string_memfd
- [x] sd_bus_message_append_strv
- [ ] sd_bus_message_open_container
- [ ] sd_bus_message_close_container
- [ ] sd_bus_message_copy
- [ ] sd_bus_message_read
- [x] sd_bus_message_read_basic
- [ ] sd_bus_message_read_array
- [ ] sd_bus_message_read_strv
- [ ] sd_bus_message_skip
- [ ] sd_bus_message_enter_container
- [ ] sd_bus_message_exit_container
- [ ] sd_bus_message_peek_type
- [ ] sd_bus_message_verify_type
- [ ] sd_bus_message_at_end
- [ ] sd_bus_message_rewind
- [ ] sd_bus_get_unique_name
- [x] sd_bus_request_name
- [x] sd_bus_release_name
- [ ] sd_bus_list_names
- [ ] sd_bus_get_name_creds
- [ ] sd_bus_get_name_machine_id
- [ ] sd_bus_call_method
- [ ] sd_bus_call_method_async
- [ ] sd_bus_get_property
- [ ] sd_bus_get_property_trivial
- [ ] sd_bus_get_property_string
- [ ] sd_bus_get_property_strv
- [ ] sd_bus_set_property
- [ ] sd_bus_reply_method_return
- [ ] sd_bus_reply_method_error
- [ ] sd_bus_reply_method_errorf
- [ ] sd_bus_reply_method_errno
- [ ] sd_bus_reply_method_errnof
- [ ] sd_bus_emit_signal
- [ ] sd_bus_emit_properties_changed_strv
- [ ] sd_bus_emit_properties_changed
- [ ] sd_bus_emit_interfaces_added_strv
- [ ] sd_bus_emit_interfaces_added
- [ ] sd_bus_emit_interfaces_removed_strv
- [ ] sd_bus_emit_interfaces_removed
- [ ] sd_bus_query_sender_creds
- [ ] sd_bus_query_sender_privilege
- [x] sd_bus_creds_new_from_pid
- [x] sd_bus_creds_ref
- [x] sd_bus_creds_unref
- [x] sd_bus_creds_get_mask
- [x] sd_bus_creds_get_augmented_mask
- [x] sd_bus_creds_get_pid
- [x] sd_bus_creds_get_ppid
- [x] sd_bus_creds_get_tid
- [x] sd_bus_creds_get_uid
- [x] sd_bus_creds_get_euid
- [x] sd_bus_creds_get_suid
- [x] sd_bus_creds_get_fsuid
- [x] sd_bus_creds_get_gid
- [x] sd_bus_creds_get_egid
- [x] sd_bus_creds_get_sgid
- [x] sd_bus_creds_get_fsgid
- [x] sd_bus_creds_get_supplementary_gids
- [x] sd_bus_creds_get_comm
- [x] sd_bus_creds_get_tid_comm
- [x] sd_bus_creds_get_exe
- [x] sd_bus_creds_get_cmdline
- [x] sd_bus_creds_get_cgroup
- [x] sd_bus_creds_get_unit
- [x] sd_bus_creds_get_slice
- [x] sd_bus_creds_get_user_unit
- [x] sd_bus_creds_get_user_slice
- [x] sd_bus_creds_get_session
- [x] sd_bus_creds_get_owner_uid
- [x] sd_bus_creds_has_effective_cap
- [x] sd_bus_creds_has_permitted_cap
- [x] sd_bus_creds_has_inheritable_cap
- [x] sd_bus_creds_has_bounding_cap
- [x] sd_bus_creds_get_selinux_context
- [x] sd_bus_creds_get_audit_session_id
- [x] sd_bus_creds_get_audit_login_uid
- [x] sd_bus_creds_get_tty
- [x] sd_bus_creds_get_unique_name
- [x] sd_bus_creds_get_well_known_names
- [x] sd_bus_creds_get_description
- [x] sd_bus_error_free
- [x] sd_bus_error_set
- [x] sd_bus_error_setf
- [x] sd_bus_error_set_const
- [x] sd_bus_error_set_errno
- [x] sd_bus_error_set_errnof
- [x] sd_bus_error_set_errnofv
- [x] sd_bus_error_get_errno
- [x] sd_bus_error_copy
- [x] sd_bus_error_is_set
- [x] sd_bus_error_has_name
- [x] sd_bus_error_add_map
- [x] sd_bus_path_encode
- [x] sd_bus_path_decode
- [x] sd_bus_track_new
- [x] sd_bus_track_ref
- [x] sd_bus_track_unref
- [x] sd_bus_track_unrefp
- [x] sd_bus_track_get_bus
- [x] sd_bus_track_get_userdata
- [x] sd_bus_track_set_userdata
- [x] sd_bus_track_add_sender
- [x] sd_bus_track_remove_sender
- [x] sd_bus_track_add_name
- [x] sd_bus_track_remove_name
- [x] sd_bus_track_count
- [x] sd_bus_track_count_sender
- [x] sd_bus_track_count_name
- [x] sd_bus_track_contains
- [x] sd_bus_track_first
- [x] sd_bus_track_next
- [x] sd_bus_track_get_recursive
- [x] sd_bus_track_set_recursive
- [ ] sd_bus_emit_object_added
- [ ] sd_bus_emit_object_removed
- [ ] sd_bus_flush_close_unref
- [ ] sd_bus_default_flush_close
- [x] sd_bus_path_decode_many
- [x] sd_bus_path_encode_many
- [x] sd_bus_get_exit_on_disconnect
- [x] sd_bus_set_exit_on_disconnect
- [ ] sd_bus_open_with_description
- [ ] sd_bus_open_user_with_description
- [ ] sd_bus_open_system_with_description
- [x] sd_bus_slot_get_floating
- [x] sd_bus_slot_set_floating

**Comment by poettering** [comment] 2015-06-16 22:50
Well, a good chunk of the sd-bus call is actually documented with man pages. But yes, it's not complete.

**Comment by mbiebl** [comment] 2015-06-16 23:04
hm, man sd-bus or sd_bus_TAB didn't turn anything up. Oh right, those man pages are installed conditionally on ENABLE_KDBUS (in Makefile-man.am) and I didn't have --enable-kdbus

**Comment by mbiebl** [comment] 2015-06-16 23:07
Even with --enable-kdbus, a central sd-bus man page is missing as entry point.

**Comment by poettering** [comment] 2015-06-17 10:37
@mbiebl see #245: the patch enables the sd-bus man pages now unconditionally, regardless of ENABLE_KDBUS. Given that we also moved the rest of sd-bus out of ENABLE_KDBUS that's the right thing to do.

**Comment by mbiebl** [comment] 2015-11-11 00:20
@poettering Can this issue be closed now?

**Comment by poettering** [comment] 2015-11-12 12:59
On Tue, 10.11.15 16:20, Michael Biebl (notifications@github.com) wrote:

> @poettering Can this issue be closed now?

Well, we still are missing some docs here...

**Comment by keszybz** [comment] 2016-04-23 01:38
- [ ] sd-bus (entry point)
  - [ ] sd_bus_get_allow_interactive_authorization
  - [ ] sd_bus_start
  - [ ] sd_bus_close
  - [ ] sd_bus_try_close
  - [x] sd_bus_ref
  - [x] sd_bus_unref
  - [ ] sd_bus_is_open
  - [ ] sd_bus_get_bus_id
  - [ ] sd_bus_get_scope
  - [ ] sd_bus_get_tid
  - [ ] sd_bus_get_owner_creds
  - [ ] sd_bus_send
  - [ ] sd_bus_send_to
  - [ ] sd_bus_call
  - [ ] sd_bus_call_async
  - [ ] sd_bus_get_fd
  - [ ] sd_bus_get_events
  - [ ] sd_bus_get_timeout
  - [ ] sd_bus_process
  - [ ] sd_bus_process_priority
  - [ ] sd_bus_wait
  - [ ] sd_bus_flush
  - [ ] sd_bus_get_current_slot
  - [ ] sd_bus_get_current_message
  - [ ] sd_bus_get_current_handler
  - [ ] sd_bus_get_current_userdata
  - [ ] sd_bus_attach_event
  - [ ] sd_bus_detach_event
  - [ ] sd_bus_get_event
  - [ ] sd_bus_add_filter
  - [ ] sd_bus_add_match
  - [ ] sd_bus_add_object
  - [ ] sd_bus_add_fallback
  - [ ] sd_bus_add_object_vtable
  - [ ] sd_bus_add_fallback_vtable
  - [ ] sd_bus_add_node_enumerator
  - [ ] sd_bus_add_object_manager
  - [ ] sd_bus_slot_ref
  - [ ] sd_bus_slot_unref
  - [ ] sd_bus_slot_get_bus
  - [ ] sd_bus_slot_get_userdata
  - [ ] sd_bus_slot_set_userdata
  - [ ] sd_bus_slot_get_description
  - [ ] sd_bus_slot_set_description
  - [ ] sd_bus_slot_get_current_message
  - [ ] sd_bus_slot_get_current_handler
  - [ ] sd_bus_slot_get_current_userdata
  - [ ] sd_bus_message_new_signal
  - [ ] sd_bus_message_new_method_call
  - [ ] sd_bus_message_new_method_return
  - [ ] sd_bus_message_new_method_error
  - [ ] sd_bus_message_new_method_errorf
  - [ ] sd_bus_message_new_method_errno
  - [ ] sd_bus_message_new_method_errnof
  - [ ] sd_bus_message_ref
  - [ ] sd_bus_message_unref
  - [ ] sd_bus_message_get_type
  - [x] sd_bus_message_get_cookie
  - [x] sd_bus_message_get_reply_cookie
  - [ ] sd_bus_message_get_priority
  - [ ] sd_bus_message_get_expect_reply
  - [ ] sd_bus_message_get_auto_start
  - [ ] sd_bus_message_get_allow_interactive_authorization
  - [ ] sd_bus_message_get_signature
  - [ ] sd_bus_message_get_path
  - [ ] sd_bus_message_get_interface
  - [ ] sd_bus_message_get_member
  - [ ] sd_bus_message_get_destination
  - [ ] sd_bus_message_get_sender
  - [ ] sd_bus_message_get_error
  - [ ] sd_bus_message_get_errno
  - [x] sd_bus_message_get_monotonic_usec
  - [x] sd_bus_message_get_realtime_usec
  - [x] sd_bus_message_get_seqnum
  - [ ] sd_bus_message_get_bus
  - [ ] sd_bus_message_get_creds
  - [ ] sd_bus_message_is_signal
  - [ ] sd_bus_message_is_method_call
  - [ ] sd_bus_message_is_method_error
  - [ ] sd_bus_message_is_empty
  - [ ] sd_bus_message_has_signature
  - [ ] sd_bus_message_set_expect_reply
  - [ ] sd_bus_message_set_auto_start
  - [ ] sd_bus_message_set_allow_interactive_authorization
  - [ ] sd_bus_message_set_destination
  - [ ] sd_bus_message_set_priority
  - [x] sd_bus_message_append
  - [x] sd_bus_message_append_basic
  - [x] sd_bus_message_append_array
  - [x] sd_bus_message_append_array_space
  - [x] sd_bus_message_append_array_iovec
  - [x] sd_bus_message_append_array_memfd
  - [x] sd_bus_message_append_string_space
  - [x] sd_bus_message_append_string_iovec
  - [x] sd_bus_message_append_string_memfd
  - [x] sd_bus_message_append_strv
  - [ ] sd_bus_message_open_container
  - [ ] sd_bus_message_close_container
  - [ ] sd_bus_message_copy
  - [ ] sd_bus_message_read
  - [ ] sd_bus_message_read_basic
  - [ ] sd_bus_message_read_array
  - [ ] sd_bus_message_read_strv
  - [ ] sd_bus_message_skip
  - [ ] sd_bus_message_enter_container
  - [ ] sd_bus_message_exit_container
  - [ ] sd_bus_message_peek_type
  - [ ] sd_bus_message_verify_type
  - [ ] sd_bus_message_at_end
  - [ ] sd_bus_message_rewind
  - [ ] sd_bus_get_unique_name
  - [x] sd_bus_request_name
  - [x] sd_bus_release_name
  - [ ] sd_bus_list_names
  - [ ] sd_bus_get_name_creds
  - [ ] sd_bus_get_name_machine_id
  - [ ] sd_bus_call_method
  - [ ] sd_bus_call_method_async
  - [ ] sd_bus_get_property
  - [ ] sd_bus_get_property_trivial
  - [ ] sd_bus_get_property_string
  - [ ] sd_bus_get_property_strv
  - [ ] sd_bus_set_property
  - [ ] sd_bus_reply_method_return
  - [ ] sd_bus_reply_method_error
  - [ ] sd_bus_reply_method_errorf
  - [ ] sd_bus_reply_method_errno
  - [ ] sd_bus_reply_method_errnof
  - [ ] sd_bus_emit_signal
  - [ ] sd_bus_emit_properties_changed_strv
  - [ ] sd_bus_emit_properties_changed
  - [ ] sd_bus_emit_interfaces_added_strv
  - [ ] sd_bus_emit_interfaces_added
  - [ ] sd_bus_emit_interfaces_removed_strv
  - [ ] sd_bus_emit_interfaces_removed
  - [ ] sd_bus_query_sender_creds
  - [ ] sd_bus_query_sender_privilege
  - [x] sd_bus_creds_new_from_pid
  - [x] sd_bus_creds_ref
  - [x] sd_bus_creds_unref
  - [x] sd_bus_creds_get_mask
  - [x] sd_bus_creds_get_augmented_mask
  - [x] sd_bus_creds_get_pid
  - [x] sd_bus_creds_get_ppid
  - [x] sd_bus_creds_get_tid
  - [x] sd_bus_creds_get_uid
  - [x] sd_bus_creds_get_euid
  - [x] sd_bus_creds_get_suid
  - [x] sd_bus_creds_get_fsuid
  - [x] sd_bus_creds_get_gid
  - [x] sd_bus_creds_get_egid
  - [x] sd_bus_creds_get_sgid
  - [x] sd_bus_creds_get_fsgid
  - [x] sd_bus_creds_get_supplementary_gids
  - [x] sd_bus_creds_get_comm
  - [x] sd_bus_creds_get_tid_comm
  - [x] sd_bus_creds_get_exe
  - [x] sd_bus_creds_get_cmdline
  - [x] sd_bus_creds_get_cgroup
  - [x] sd_bus_creds_get_unit
  - [x] sd_bus_creds_get_slice
  - [x] sd_bus_creds_get_user_unit
  - [x] sd_bus_creds_get_user_slice
  - [x] sd_bus_creds_get_session
  - [x] sd_bus_creds_get_owner_uid
  - [x] sd_bus_creds_has_effective_cap
  - [x] sd_bus_creds_has_permitted_cap
  - [x] sd_bus_creds_has_inheritable_cap
  - [x] sd_bus_creds_has_bounding_cap
  - [x] sd_bus_creds_get_selinux_context
  - [x] sd_bus_creds_get_audit_session_id
  - [x] sd_bus_creds_get_audit_login_uid
  - [x] sd_bus_creds_get_tty
  - [x] sd_bus_creds_get_unique_name
  - [x] sd_bus_creds_get_well_known_names
  - [x] sd_bus_creds_get_description
  - [x] sd_bus_error_free
  - [x] sd_bus_error_set
  - [x] sd_bus_error_setf
  - [x] sd_bus_error_set_const
  - [x] sd_bus_error_set_errno
  - [x] sd_bus_error_set_errnof
  - [x] sd_bus_error_set_errnofv
  - [x] sd_bus_error_get_errno
  - [x] sd_bus_error_copy
  - [x] sd_bus_error_is_set
  - [x] sd_bus_error_has_name
  - [x] sd_bus_error_add_map
  - [x] sd_bus_path_encode
  - [x] sd_bus_path_decode
  - [ ] sd_bus_track_new
  - [ ] sd_bus_track_ref
  - [ ] sd_bus_track_unref
  - [ ] sd_bus_track_get_bus
  - [ ] sd_bus_track_get_userdata
  - [ ] sd_bus_track_set_userdata
  - [ ] sd_bus_track_add_sender
  - [ ] sd_bus_track_remove_sender
  - [ ] sd_bus_track_add_name
  - [ ] sd_bus_track_remove_name
  - [ ] sd_bus_track_count
  - [ ] sd_bus_track_contains
  - [ ] sd_bus_track_first
  - [ ] sd_bus_track_next
  - [ ] sd_bus_emit_object_added
  - [ ] sd_bus_emit_object_removed
  - [ ] sd_bus_flush_close_unref
  - [ ] sd_bus_default_flush_close
  - [x] sd_bus_path_decode_many
  - [x] sd_bus_path_encode_many

**Comment by keszybz** [comment] 2016-04-23 01:40
93 out of 210 + 1, about 44% done.

**Comment by poettering** [comment] 2016-06-16 12:05
sd-event is fully documented these days.

**Comment by keszybz** [comment] 2016-09-15 11:12
I moved the list to the first comment now.

**Comment by hemanthgu** [comment] 2017-08-09 13:35
Bump !! looking for API documentation to use sd-bus to interact with systemd.

**Comment by vbextreme** [comment] 2018-05-22 11:25
I try to call sd_bus_list_names, after call sd_buf_default_system, but return -22 and not found documentation for error -22 or how to use sd_bus_list_names.

**Comment by keszybz** [comment] 2018-05-22 12:05
@vbextreme 22=EINVAL. Most likely you passed NULL in the args.

**Comment by vbextreme** [comment] 2018-05-27 14:37
ok, testing with C code without problems.
My problems it's with triple pointers and perl6 native call. Thank's

**Comment by keszybz** [comment] 2019-05-18 08:32
Current status:
libsystemd: 386/540 libudev: 65/90

**Comment by keszybz** [comment] 2020-03-03 17:50
libsystemd: 398/551 libudev: 65/90

**Comment by keszybz** [comment] 2020-03-18 09:48
libsystemd: 403/551 libudev: 65/90

**Comment by keszybz** [comment] 2020-03-18 17:11
After #15153 is merged, we'll be at
libsystemd: 409/550 libudev: 65/90

**Comment by keszybz** [comment] 2020-04-28 17:48
Fixed by @DaanDeMeyer in bac1b83217.

**Closed as completed by keszybz** 2020-04-28 17:48 UTC
Labels: documentation, sd-bus

**Comment by CarloWood** [comment] 2021-02-20 07:00
I started an attempt to use sd-bus a few days ago... by now my verdict is: unusable due to lack of good documentation. Most notably, there isn't a tutorial or even examples on how to use it (the way I need to use it, using sd_bus_set_fd.

**Comment by yuwata** [comment] 2021-02-20 07:40
Why not to use `sd_bus_attach_event()`? The man page of `sd_bus_set_fd()` suggests to use `sd_bus_attach_event()`.

**Comment by CarloWood** [comment] 2021-02-20 12:34
On Fri, 19 Feb 2021 23:41:06 -0800
Yu Watanabe <notifications@github.com> wrote:

> Why not to use `sd_bus_attach_event()`? The man page of
> `sd_bus_set_fd()` suggests to use `sd_bus_attach_event()`.
> 

I am not using sd-event. I have my own socket, epoll and main loop.
Even my own timers. My own threads...

All I need is a library that generates the protocol for me.

**Comment by yuwata** [comment] 2021-02-20 12:58
src/libsystemd/sd-bus/test-bus-server.c or other tests use the function. They may help you. Then, if you succeed to create a good example, please submit as a PR.

**Comment by poettering** [comment] 2021-02-20 12:59
sd_bus_set_fd() is a *very* advanced way to use sd-bus, you should not need that for regular operation. If you use that you are assumed to have an understanding of things that goes beyond what an introduction or tutorial could ever give you.

I think we should certainly provide reference docs eventually for all our APIs, and for sd-event we provide that fully, for sd-bus to some degree. And yes, more examples and tutorials are great, but humm, that'd be the cherry on top really, and given our limited man power unlikely to happen any time soon — we'd of course welcome contributions in this area.

**Comment by CarloWood** [comment] 2021-02-21 15:22
On Sat, 20 Feb 2021 04:58:45 -0800
Yu Watanabe <notifications@github.com> wrote:

> src/libsystemd/sd-bus/test-bus-server.c or other tests use the
> function. They may help you. Then, if you succeed to create a good
> example, please submit as a PR.

How does using these calls guarantee that sd_bus_get_owner_creds
and sd_bus_get_name_creds are never called?

(because they were that would be UB as they access bus->is_local
which is undefined like this)

Carlo

**Comment by CarloWood** [comment] 2021-02-26 08:21
ping

Also, doing what src/libsystemd/sd-bus/test-bus-server.c says, I get the following conversation between client and server:

dbus<-- \x00AUTH ANONYMOUS\r\nDATA 616e6f6e796d6f7573\r\nNEGOTIATE_UNIX_FD\r\nBEGIN\r\n
dbus--> REJECTED EXTERNAL\r\nERROR "Not currently in an auth conversation"\r\nERROR "Need to authenticate first"\r\n

Can anyone explain that error? What is causing it?
If it is caused by the ANONYMOUS then how can that test ever work?

Also, I just need to same as sd_bus_open_user, but then with a call to sd_bus_set_fd, this seems impossible because there is no way to set bus->is_local = true;  -- can `sd_bus_set_is_local()` be added please?

**Comment by keszybz** [comment] 2021-02-26 08:27
@CarloWood an old bug is not the right place to ask about implementation details. Those kinds of questions look more appropriate either for the systemd-devel or dbus lists.
