### ISSUE TITLE
systemd-udev interferes with MAC addresses of interfaces it's not supposed to do

### ISSUE THREAD

**Issue by BarbarossaTM** [systemd/systemd#21185] opened 2021-10-29 17:24 UTC
**systemd version the issue has been seen with**
 >  247 (247.3-6)

**Used distribution**
 > Debian Bullseye

**Linux kernel version used** (`uname -a`)
 > `Linux ash 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > The MAC address of a newly created bridge interface is randomly chosen.

**Unexpected behaviour you saw**
 > The MAC address of a newly created bridge is the same for every bridge interface with the same name even when the interface is created manually with `ip link`. This is an issue because this behavior will break your network when you connect two or more hosts with a bridge with the same name to the same Layer2 segment.

**Steps to reproduce the problem**
 > See below.
> I looks like the problematic code is part of systemd-udevd. If I stop `systemd-udevd`, `systemd-udevd-kernel.socket`, and `systemd-udevd-control.socket` the MAC address is chosen randomly again and not overwritten.

**Additional program output to the terminal or log subsystem illustrating the issue**

**Debian Buster system showing the expected behaviour** 

```
root@sesquialtera:~# for n in 0 1 2 3 4; do ip link add br${n} type bridge; done

br0              DOWN           5e:20:8a:b6:90:a8 <BROADCAST,MULTICAST> 
br1              DOWN           de:ab:c0:aa:a7:be <BROADCAST,MULTICAST> 
br2              DOWN           4a:cc:8b:00:2d:5c <BROADCAST,MULTICAST> 
br3              DOWN           de:c6:ba:2d:9b:37 <BROADCAST,MULTICAST> 
br4              DOWN           b6:cd:53:79:31:fc <BROADCAST,MULTICAST> 
root@sesquialtera:~# for n in 0 1 2 3 4; do ip link del br${n}; done
root@sesquialtera:~# for n in 0 1 2 3 4; do ip link add br${n} type bridge; done
root@sesquialtera:~# ip -br l

br0              DOWN           7a:52:4f:85:fb:e1 <BROADCAST,MULTICAST> 
br1              DOWN           4a:e2:11:f5:19:af <BROADCAST,MULTICAST> 
br2              DOWN           06:a6:23:29:49:7d <BROADCAST,MULTICAST> 
br3              DOWN           de:d6:ac:92:58:cf <BROADCAST,MULTICAST> 
br4              DOWN           d2:0f:6f:96:92:ab <BROADCAST,MULTICAST>
```

**Debian Bullseye system showing the problematic behaviour**
```
ash.in.ffho.net:~# for n in 0 1 2 3; do ip l add br$n type bridge; done
ash.in.ffho.net:~# ip -br l

br0              DOWN           d2:9e:b3:32:53:42 <BROADCAST,MULTICAST> 
br1              DOWN           e2:00:44:2c:5b:70 <BROADCAST,MULTICAST> 
br2              DOWN           0e:99:b7:42:f0:25 <BROADCAST,MULTICAST> 
br3              DOWN           a6:3f:5f:b5:9a:d6 <BROADCAST,MULTICAST> 
ash.in.ffho.net:~# for n in 0 1 2 3; do ip link del br${n}; done
ash.in.ffho.net:~# for n in 0 1 2 3; do ip l add br$n type bridge; done
ash.in.ffho.net:~# ip -br l

br0              DOWN           d2:9e:b3:32:53:42 <BROADCAST,MULTICAST> 
br1              DOWN           e2:00:44:2c:5b:70 <BROADCAST,MULTICAST> 
br2              DOWN           0e:99:b7:42:f0:25 <BROADCAST,MULTICAST> 
br3              DOWN           a6:3f:5f:b5:9a:d6 <BROADCAST,MULTICAST> 
```

**Comment by yuwata** [comment] 2021-10-30 22:09
Please create a .link file, e.g.
```
# /etc/systemd/network/90-bridge.link
[Match]
OriginalName=br*

[Link]
MACAddressPolicy=random
```

**Comment by yuwata** [comment] 2021-10-30 22:11
> This is an issue because this behavior will break your network when you connect two or more hosts with a bridge with the same name to the same Layer2 segment.

This should not happen, unless multiple hosts use the same machine ID.

**Comment by yuwata** [comment] 2021-10-30 22:12
Note, the behavior was introduced by 6d36464065601f79a352367cf099be8907d8f9aa.

Anyway, this is not a bug. But intended behavior. Closing.

**Closed as completed by yuwata** 2021-10-30 22:12 UTC
Labels: udev, network, not-a-bug

**Comment by BarbarossaTM** [comment] 2021-11-01 14:38
Well I guess assumption 3. in the linked commit is false: People are complaining and have complained early on as I can see.

I still feel `systemd-udevd` has no business in changing the MAC addresses of an interface which has been created by some unrelated tool, and even doing so by default (config file). This breaks behavior which has been there for years if not decades and violates the principle of least surprise.

**Comment by j0ju** [comment] 2021-11-01 22:57
The kernel has a default behavior in managing MAC addresses for interfaces. Udevd is overwriting the kernel assigned MACs. 
Even the proposed .link file with 
```
[Link]
MACAddressPolicy=random
```
is overriding this behavior. As a first MAC would be assigned in the ways of the kernel e.g. for bridges at first but a random MAC onto that interface, and after manually adding an interface it would  assign the MAC of the first interface to the bridge if the MAC has not been altered manually in between.

As an user I like to have a switch to disable this.

**Comment by p1lgr1m** [comment] 2023-01-03 22:25
I have a (headless) server with Intel AMT enabled (to have remote console whenever normal networking is unavailable, e.g. during maintenance). The server has 1 Ethernet port - and it's a member of a bridge in Linux. Intel AMT is set up to "share" the connection with the OS.

After upgrading to Bullseye, Intel AMT was no longer reachable. That's not good for something that is supposed to provide emergency access. Culprit was the new, random, MAC address that Bullseye assigns to the bridge. Forcing the MAC address back to the MAC of the NIC fixed the issue (with `bridge_hw eth0` added to the bridge config in `/etc/network/interfaces` ).

Not saying that the new default behavior is wrong - just that it has consequences and it breaks something for me.

**Comment by MarcusWichelmann** [comment] 2026-04-10 16:37
This has bitten me as well and caused outages in a production environment where a few nodes suddenly had a MAC address configured on a veth interface that was different from the one we assigned statically. After hours of debugging, we discovered this bug report.

Our setup included a simple bash script which, among other things, creates a veth-pair and sets it's MAC address. This veth-pair is needed for internal communication. The relevant parts looked like this (names changed):
```bash
ip link add veth0 type veth peer name veth1

# [...] some other things

ip link set dev veth1 address <our MAC>
ip link set dev veth1 up
ip link set dev veth0 up
```

In rare cases, the resulting `veth1` interface did not have the MAC address we assigned to it. Turns out, the `MACAddressPolicy` was the culprit and caused a race condition with our `ip link set dev veth1 address` call. Depending on what happened faster, the MAC address was a different one.

In my opinion it is very suprising that systemd touches interfaces we never configured it to manage. Applications that run perfectly fine on other systems may suddenly break on nodes which use systemd-networkd. And this is very time consuming to trace down, especially when not knowing about this feature.

Limiting this feature to networkd-managed interfaces only would make it way less suprising, as interferences for those managed interfaces are to be expected.

@yuwata May I politely ask to reopen this issue please?
