### ISSUE TITLE
systemctl: allow tailing of logs and state changes when (re)starting

### ISSUE THREAD

**Issue by NotAFile** [systemd/systemd#14912] opened 2020-02-20 16:20 UTC
**Is your feature request related to a problem? Please describe.**
Often, I find myself debugging failing units, especially ones that are one-shot. This usually involves running `systemctl start [unit]`, checking if the unit is actually running and looking at it's stdout using `journalctl`. This quickly gets tedious.

**Describe the solution you'd like**
This common use could be simplified using a convenience function similar to `systemctl [enable|disable] --now`. For example, `systemctl [start|restart|stop] --watch`. This would perform the action, then tail the journal output for the unit, including unit state changes. It would exit when the unit stops (like `--wait`), or `^c` is pressed. It could also exit when the unit signals readiness using `sd_notify` after successful startup.

**Describe alternatives you've considered**
 - The `systemd-run` tool can already perform similar actions. Adding an option to run an existing unit definition with it might be a simpler solution. However, knowledge of `systemd-run` is not widespread, and workflow wise, this is really variant of `systemctl` usage. `systemd-run` would also need to learn some option to easily detach from the unit and let it run.
 - Individual users can define aliases to perform similar actions. However, these would need to be installed on every machine, and would not offer as tight integration.

**Comment by boucman** [comment] 2020-02-20 16:52
can't you simply run "journalctl -f -u <unit>" on another terminal ?

**Comment by NotAFile** [comment] 2020-02-20 20:24
@boucman you could absolutely, yes. I should have mentioned that. However, that's not as easy on a server. It does cover the case where you're debugging something for an extended amount of time and the inconvenience of having to switch to a new tmux or screen session, assuming those are installed, or even a second ssh connection, is worthwhile.

But usually I just want to quickly verify that something started up fine without having to enter 3+ commands (`systemctl start`, `systemctl status`, `journalctl -fu`).

**Comment by poettering** [comment] 2021-05-12 12:46
Pretty much a duplicate of #1287 actually, let's close

**Closed as completed by poettering** 2021-05-12 12:46 UTC
Labels: RFE 🎁, systemctl, duplicate
