### ISSUE TITLE
Improved catalog messages for start jobs

### ISSUE THREAD

**Issue by bjourne** [systemd/systemd#19546] opened 2021-05-08 04:38 UTC
`journalctl -xe` prints the following

```Subject: A start job for unit UNIT has finished successfully
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit UNIT has finished successfully.
░░ 
░░ The job identifier is 160.
```

and

```░░ Subject: A start job for unit UNIT has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit UNIT has begun execution.
░░ 
░░ The job identifier is 143.
```
These messages could be improved by printing the names of the jobs or what executables/services they invoke. The job id isn't enough.

**Comment by poettering** [comment] 2021-05-10 20:55
so my guess this is from a per-user instance of systemd?

the per-user instances set USER_UNIT instead of UNIT but the catalog refers only to the latter. So this works nicely with the systemd instance, but not otherwise.

**Comment by poettering** [comment] 2021-05-10 20:57
Duplicate of #8005

**Closed as completed by poettering** 2021-05-10 20:57 UTC
Labels: journal, duplicate, catalog
