### ISSUE TITLE
systemd-homed: Polkit doesn't recognize wheel group specified in "memberOf" array

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#17755] opened 2020-11-27 18:52 UTC
**systemd version the issue has been seen with**
246.6-1-arch

**Used distribution**
Arch Linux

**Linux kernel version used** (`uname -a`)
Linux 5.9.11-arch1-1 #1 SMP PREEMPT x86_64 GNU/Linux

**CPU architecture issue was seen on**
 x86_64

**Expected behaviour you didn't see**
[I "converted" my user to the homed format though `homectl`, following this guide](https://systemd.io/CONVERTING_TO_HOMED/). 
That means removing references to the user in the passwd, and group files (also in the shadow files). Instead, I specified the user's auxiliary (system) groups with `--member-of`, with the group "wheel", used for administration, among them.

The command `sudo` recognizes the user as a member of the wheel group and accepts his password for authentication.
I expected the `pkexec` dialogs do do the same but they don't. They will only accept the root password, which I'd rather leave empty and locked.

[The workaround is to include the user in the wheel group, the old-fashioned way, as shown here](https://www.reddit.com/r/archlinux/comments/i05el0/policykit_systemdhomed_not_playing_nicely_together/g24lzt0/). It seems Polkit expects to find group information in the old-fashioned Unix files **only**, even though my `/etc/nsswitch.conf` looks like this:

```
# Name Service Switch configuration file.
# See nsswitch.conf(5) for details.

passwd: files systemd
group: files systemd
shadow: files

publickey: files

hosts: files mymachines myhostname mdns4_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns
networks: files

protocols: files
services: files
ethers: files
rpc: files

netgroup: files
```

**Unexpected behaviour you saw**
Polkit authorization dialogs don't accept my password, even though systemd-homed (and for example, the `id` and `groups` commands say I belong in the wheel group)

**Steps to reproduce the problem**
- Create a new user (or convert an existing one, removing references of them in the unix group files), having him be a `--member-of` the `wheel` group.
- Try to `pkexec something` (For example, `linssid-pkexec`, which is a wrapper for the LinSSID WiFi scanning program)
- The dialog doesn't accept your user's password, only `root`'s

EDIT:
- journalctl when using member-of:
```
polkit-agent-helper-1[4029]: pam_unix(polkit-1:auth): authentication failure; logname= uid=1000 euid=0 tty= ruser=root rhost=  user=root
polkitd[1389]: Operator of unix-session:1 FAILED to authenticate to gain authorization for action com.warsev.pkexec.linssid for unix-process:4022:26371 [/bin/sh /usr/bin/linssid-pkexec] (owned by unix-user:leo)
pkexec[4023]: leo: Error executing command as another user: Request dismissed [USER=root] [TTY=/dev/pts/1] [CWD=/home/leo] [COMMAND=/usr/sbin/linssid]
```

- `journalctl` after `gpasswd -a leo wheel`:
```
systemd-homed[552]: leo: changing state active → authenticating-for-acquire
systemd-homework[4589]: Provided password unlocks user record.
systemd-homework[4589]: Discovered used LUKS device /dev/mapper/home-leo, and validated password.
systemd-homework[4589]: Successfully re-activated LUKS device.
systemd-homework[4589]: Provided password unlocks user record.
systemd-homework[4589]: Discovered used loopback device /dev/loop0.
systemd-homework[4589]: Read embedded .identity file.
systemd-homework[4589]: Provided password unlocks user record.
systemd-homework[4589]: Reconciling user identities completed (host and header version were identical).
systemd-homework[4589]: Reconciling embedded user identity completed (host and embedded version systemd-homework[4589]: Everything completed.
systemd-homed[552]: leo: changing state authenticating-for-acquire → active
polkit-agent-helper-1[4582]: pam_systemd_home(polkit-1:auth): Home for user leo successfully acquired.
polkitd[1389]: Operator of unix-session:1 successfully authenticated as unix-user:leo to gain ONE-SHOT authorization for action com.warsev.pkexec.linssid for unix-process:4578:57757 [/bin/sh /usr/bin/linssid-pkexec] (owned by unix-user:leo)
pkexec[4579]: pam_unix(polkit-1:session): session opened for user root(uid=0) by (uid=1000)
pkexec[4579]: leo: Executing command [USER=root] [TTY=/dev/pts/3] [CWD=/home/leo] [COMMAND=/usr/sbin/linssid]
```

**Comment by nl6720** [comment] 2020-11-29 11:44
This is an issue with Arch Linux's `/etc/nsswitch.conf`, see https://bugs.archlinux.org/task/67658 .

The workaround is to [manually edit `/etc/nsswitch.conf`](https://wiki.archlinux.org/index.php/Systemd-homed#polkit_does_not_detect_groups_of_systemd-homed_users).

**Comment by JpegXguy** [comment] 2020-11-29 13:32
Ah, I didn't search well enough. Seems to me like this should be in `nsswitch.conf` by default in the Arch package?
So the need for editing `nsswitch.conf` is intended behaviour? I'll close it if it is.

**Comment by nl6720** [comment] 2020-11-29 13:52
Yes, it's the intended behavior according to [nss-systemd(8)](https://www.freedesktop.org/software/systemd/man/nss-systemd.html#Configuration%20in%20/etc/nsswitch.conf).

**Closed as completed** 2020-11-29 14:15 UTC

**Comment by Thesola10** [comment] 2021-03-11 11:31
Just a heads-up for those who, like me, encountered the issue on a long-time install of Arch

The section of the Arch Wiki mentioned by @nl6720 **no longer exists**, but if your system is up-to-date, the fixed version of `nsswitch.conf` might be found as `nsswitch.conf.pacnew`, so make sure to **replace** your `nsswitch.conf` with the `.pacnew` version (and eventually do the same with `/etc/pam.d` rules

**Comment by JpegXguy** [comment] 2021-03-11 15:03
I think it's semi-obligatory to have the package `pacman-contrib` installed these days, in order to use the `pacdiff` utility. It handles pacsave and pacnew files, which you would otherwise forget

**Comment by eddebc** [comment] 2021-09-27 17:54
> Just a heads-up for those who, like me, encountered the issue on a long-time install of Arch
> 
> The section of the Arch Wiki mentioned by @nl6720 **no longer exists**, but if your system is up-to-date, the fixed version of `nsswitch.conf` should be found as `nsswitch.conf.pacnew`, so make sure to **replace** your `nsswitch.conf` with the `.pacnew` version (and eventually do the same with `/etc/pam.d` rules

In my case, it was a new installation with no `pacnew` files laying around. Took the listed config from [the man pages](freedesktop.org/software/systemd/man/nss-systemd.html) and `sudo` returned.
