### ISSUE TITLE
systemd-poweroff.service ignores ExecCondition

### ISSUE THREAD

**Issue by nils-werner** [systemd/systemd#23603] opened 2022-06-02 17:36 UTC
I have a modified `systemd-poweroff.service` that is set to not shut down the machine when a `btrfs scrub` service is running.

```
[Unit]
Description=System Power Off
Documentation=man:systemd-poweroff.service(8)
DefaultDependencies=no
Requires=shutdown.target umount.target final.target
After=shutdown.target umount.target final.target
SuccessAction=poweroff-force

[Service]
ExecCondition=!systemctl is-active btrfs-scrub@home.service
```

However `ExecCondition` seems to not have any effect, if I run

```
sudo systemctl start btrfs-scrub@home.service
sudo systemctl start systemd-poweroff.service
```

the machine still shuts down, and `journalctl -ru systemd-poweroff.service` tells me

```
Jun 02 19:22:43 nas systemd[1]: Condition check resulted in System Power Off being skipped.
Jun 02 19:22:43 nas systemd[1]: systemd-poweroff.service: Skipped due to 'exec-condition'.
Jun 02 19:22:43 nas systemctl[4026]: failed
Jun 02 19:22:43 nas systemd[1]: Starting System Power Off...
```

So it seems `ExecCondition` is recognized, executed, but ignored.

My intuition tells me that this has to do with the fact that the service doesn't actually execute anything, but only works via its dependencies?

**Comment by nils-werner** [comment] 2022-06-06 07:29
Oh, reading the manual again I realized that `!` means two entirely different things for `ConditionPathExists` (where it negates the outcome) and `ExecStartPre` (where it escalates the permissions of the invoked process). I guess the same is then also true for `ExecCondition`.

Also, I read the log the wrong way round and assumed the last line meant the condition was ignored when in fact it wasn't.

**Comment by yuwata** [comment] 2022-06-27 16:38
Please see the man page systemd-poweroff.service(8).
> Note that systemd-halt.service (and the related units) should never be executed directly. Instead, trigger system shutdown with a command such as "systemctl halt" or suchlike.

How about to use systemd-inhibit for such purpose?

Anyway, this is not a bug, closing.

**Closed as completed by yuwata** 2022-06-27 16:38 UTC
Labels: pid1, not-supported, not-a-bug
