### ISSUE TITLE
systemd services send anonymous logs

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#5284] opened 2017-02-09 11:02 UTC
Hi,

All services provided by systemd use the systemd logging facility.

By default, they all select to log straight to the journal by selecting `LOG_TARGET_AUTO`.

The side effect is that all logs sent by a given (systemd) unit are not belonging to that unit.
IOW `journalctl -u <unit>` won't show the relevant logs.

Wouldn't it be more appropriate to let the units log through stderr in this case ?

**Comment by poettering** [comment] 2017-02-09 11:17
I am sorry, I don't grok what you are saying?

**Comment by fbuihuu** [comment] 2017-02-09 11:25
For example:

 - systemd-remount-fs.service uses /usr/lib/systemd/system/systemd-remount-fs.

 - The binary uses `log_error()` which sends errors to  journald.

 - Those logs can't be seen with "journalctl -u systemd-remount-fs".

**Comment by poettering** [comment] 2017-02-09 11:57
duplicate of #2913

**Comment by poettering** [comment] 2017-02-09 11:58
Also see this item from the TODO file:

 ```
* journald: when we recv a log datagram via the native or syslog transports,
  search for the PID in the active stream connections, and let's make sure to
  always process the datagrams before the streams. Then, cache client metadata
  per stream in the stream object. This way we can somewhat fix the race with
  quickly exiting processes which log as long as they had their own stream
  connection...
```

**Closed as completed by poettering** 2017-02-09 11:57 UTC
Labels: journal, duplicate

**Comment by fbuihuu** [comment] 2017-02-09 12:16
Hmm there's no race nor process exiting involve here.

Using `LOG_TARGET_JOURNAL` in daemons (like it's done currently in all systemd services) implies that all logs wont have the  `_SYSTEMD_UNIT=` metadata set.

That wouldn't be the case if the logs were sent to stderr.

**Comment by poettering** [comment] 2017-02-09 12:30
> Using LOG_TARGET_JOURNAL in daemons (like it's done currently in all systemd services) implies that all logs wont have the _SYSTEMD_UNIT= metadata set.

Hu? No it doesn't.

**Comment by fbuihuu** [comment] 2017-02-09 13:17
Could you then please explain why the following log entry taken from systemd-remount-fs.c:

` log_error(MOUNT_PATH " for %s exited with exit status %i.", s, si.si_status);`

is not shown here when the service **failed**:

>  $ systemctl status systemd-remount-fs.service
>    [...]
>     Process: 407 ExecStart=/usr/lib/systemd/systemd-remount-fs (code=exited, status=1/FAILURE)
>    Main PID: 407 (code=exited, status=1/FAILURE)
> 
>    Feb 09 14:10:23 linux-vl4t systemd-remount-fs[407]: mount: / not mounted or b...
>    Feb 09 14:10:23 linux-vl4t systemd-remount-fs[407]: In some cases useful info...
>    Feb 09 14:10:23 linux-vl4t systemd-remount-fs[407]: dmesg | tail or so.
>    Feb 09 14:10:23 linux-vl4t systemd[1]: systemd-remount-fs.service: Main pro...RE
>    Feb 09 14:10:23 linux-vl4t systemd[1]: Failed to start Remount Root and Ker...s.
>    Feb 09 14:10:23 linux-vl4t systemd[1]: systemd-remount-fs.service: Unit ent...e.
>    Feb 09 14:10:23 linux-vl4t systemd[1]: systemd-remount-fs.service: Failed w...'.
>    Hint: Some lines were ellipsized, use -l to show in full.

However the log entry can be seen with:

>  $ journalctl -b | grep "exited with exit"
>  Feb 09 14:10:23 linux-vl4t systemd-remount-fs[407]: /usr/bin/mount for / exited with exit status 32.

**Comment by poettering** [comment] 2017-02-09 13:53
see the bug I linked: #2913
