### ISSUE TITLE
Tasks limit too low (4915 instead of 15 % of `/proc/sys/kernel/pid_max`)

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#13419] opened 2019-08-28 13:22 UTC
With systemd  242, and `#DefaultTasksMax=15%` in `/etc/systemd/system.conf`, on a systemd with `/proc/sys/kernel/pid_max` 131072, the value is still according to `systemctl status my.service` is still 4915.

    $ systemd --version
    systemd 242 (242)
    +PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
    $ more /proc/sys/kernel/pid_max
    131072
    $ grep DefaultTasksMax /etc/systemd/system.conf
    #DefaultTasksMax=15%
    $ systemctl status my.service
    […]
        Tasks: 36 (limit: 4915)
    […]
    $ more /proc/sys/kernel/threads-max
    1026320

According to the manual, it should be 15 % of that value by default, right?

https://github.com/systemd/systemd/blob/3005b38056676776fe7fb9514b544345a04e92ee/man/systemd-system.conf.xml#L363-L364

One of the corresponding functions is `procfs_tasks_get_limit()`.

**Comment by Werkov** [comment] 2019-09-04 08:33
Hi.

Q1) Do you specify explicit `TasksMax=` for the service or the `system.slice`?
Q2) Is the /proc/sys/kernel/pid_max value your kernel's default or do you set it via `sysctl.d`?
Q3) Is the limit fixed after `systemctl daemon-reload`?

**Comment by paulmenzel** [comment] 2019-09-04 08:47
> Q1) Do you specify explicit `TasksMax=` for the service or the `system.slice`?

No, we do not.

> Q2) Is the `/proc/sys/kernel/pid_max` value your kernel's default or do you set it via `sysctl.d`?

Yes, it is the default. We do *not* set it via `sysctl.d`.

> Q3) Is the limit fixed after `systemctl daemon-reload`?

No, it is still too low.

**Comment by Werkov** [comment] 2019-09-04 09:11
Aha. The value read from kernel is clamped with `TASKS_MAX` depending on sizeof(pid_t) [process-util.h:181](https://github.com/systemd/systemd/blob/v242/src/basic/process-util.h#L181).

It seem you may fall victim to your glibc, not a systemd bug. Can you check what's the `sizeof(pid_t)` in your build environment?

**Comment by paulmenzel** [comment] 2019-09-04 09:25
Thank you for looking into this.

```
$ /usr/lib/libc.so.6
GNU C Library (GNU libc) stable release version 2.27.
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 5.5.0.
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<http://www.gnu.org/software/libc/bugs.html>.
$ more main.c
#include <stdio.h>
#include <stdlib.h>

int main () {
	printf("%i\n", sizeof(pid_t));
	return 0;
}
$ gcc main.c
$ ./a.out 
4
```

**Comment by Werkov** [comment] 2019-09-04 14:04
If the `sizeof(pid_t) == 4` even during compile time, then I don't know where does the value 4915 (15% of 32767) come from.

I reviewed how is the kernel value `pid_max` initialized and the upstream, kernel has no config option for the explicit value (only `CONFIG_BASE_SMALL`). I.e. I assume you must have increased your `pid_max` somewhat (other than `sysctl.d`) during boot.

Then I can reproduce it with v242. When I increase `/proc/sys/kernel/pid_max` manually, mere `systemctl daemon-reload` won't update it. I need `systemctl daemon-reexec`. I believe it is thanks to a9fd4cd1206832a61aaf61fff583bb133e6cb965.

However, that sigle patch wouldn't help during a boot. A naïve attempt is in the branch [fix-pid_max-update](https://github.com/Werkov/systemd/commits/fix-pid_max-update). (It is naïve because it won't be exercised on units that start before `systemd-sysctl.service`.)

**Comment by Werkov** [comment] 2019-09-09 16:30
This fix I posted in fix-pid_max-update is unnecessary. I see that dracut includes systemd-sysctl into the initramfs, i.e. PID 1 will read the new values after switchroot.

@paulmenzel Can you track down how is your `pid_max` value (131072) set?

**Comment by paulmenzel** [comment] 2019-09-09 16:33
@Werkov, sorry I do not understand your question. I am certain, that the Linux kernel sets this value itself.

**Comment by Werkov** [comment] 2019-09-09 16:48
Can you please share `dmesg | grep pid_max` (as root or with `sudo` for dmesg)?

**Comment by paulmenzel** [comment] 2019-09-09 16:59
> Can you please share `dmesg | grep pid_max` (as root or with `sudo` for dmesg)?

Hmm, looks like you are right.

    $ free -h
                  total        used        free      shared  buff/cache   available
    Mem:           125G         60G        734M        2.2M         64G         62G
    Swap:            0B          0B          0B
    $ dmesg | grep pid_max
    [    2.841047] pid_max: default: 32768 minimum: 301

I am going to ask my colleagues if they changed the value while debugging. If that turns out to be true, I am very sorry, for the noise.

PS: On a 1 TB machine, the value is set higher by the Linux kernel.

    $ dmesg | grep pid_max
    [   10.941723] pid_max: default: 131072 minimum: 1024

**Comment by Werkov** [comment] 2019-09-09 17:05
> PS: On a 1 TB machine, the value is set higher by the Linux kernel.

It shouldn't be because of the available memory but CPUs,  `pid_max` default is bumped to `1024 * #CPUS` (if it's more than the default 32Ki).



> I am going to ask my colleagues if they changed the value while debugging.

This is what I meant by tracking down the origin of the value :-)

**Comment by paulmenzel** [comment] 2019-09-10 12:34
Looking at the history, the root user issued the command below.

    $ echo $((32768 * 4 )) > /proc/sys/kernel/pid_max

Should systemd discover that change? If not, can systemd be told to update the limits?

Should I create a separate issue for that?

**Comment by Werkov** [comment] 2019-09-10 13:13
This is how I "reproduced" it in the [comment](https://github.com/systemd/systemd/issues/13419#issuecomment-527915700).
systemd doesn't actively monitor the value (that is sane).
`systemctl daemon-reload` should work though. And it does not in v242. I don't have v243 environment at hand but I assume this is fixed in v243 (referring the commit in my previous comment). If you see the same behavior in v243, then it's worth keeping this opened.

**Comment by Werkov** [comment] 2019-09-26 15:19
Thanks for the observation @paulmenzel, I saw that as well with v243. I believe you that's a v243 bug when the documented default is not honored. As for the original issue, when I do `systemctl daemon-reload` after changing `pid_max`, the new values are propagated to the defaults as expected.

**Closed as completed** 2019-11-18 21:18 UTC
Labels: pid1
