### ISSUE TITLE
systemd-networkd[NNN]: Assertion 'a' failed at src/network/networkd-address.c:1857, function address_is_ready(). Aborting.

### ISSUE THREAD

**Issue by helmutg** [systemd/systemd#20232] opened 2021-07-15 16:38 UTC
**systemd version the issue has been seen with**
 > 247.3-5

**Used distribution**
 > Debian bullseye amd64

**Linux kernel version used** (`uname -a`)
 > `Linux debian 5.10.0-7-amd64 #1 SMP Debian 5.10.40-1 (2021-05-28) x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > networkd should not crash

**Unexpected behaviour you saw**
 > networkd aborted. The message was:
 > `systemd-networkd[NNN]: Assertion 'a' failed at src/network/networkd-address.c:1857, function address_is_ready(). Aborting.`

**Steps to reproduce the problem**
 > Admittedly, the problem halfway is a user error. It is on the border between "don't do that" and "networkd should not crash"
 > 1. Cause a non-bridge interface to occupy a name, say `foo`, using a `systemd.link` file.
 > 2. Rename the interface in the `systemd.link` file to a different name, say `bar`.
 > 3. Create a `systemd.netdev` file that configures a bridge interface named `foo`.
 > 4. Create a `system.network` file that assigns another interface to the bridge named `foo`.
 > 5. `systemctl restart systemd-networkd`
 > `networkd` keeps aborting. You can fix the situation by manually renaming the interface `foo` or by rebooting, in which case it will be renamed due to the changed `systemd.link` file.

**Discussion**
> The scenario certainly is a user error, so the best `networkd` can do is provide a better error message and not crash. If you deem the issue unimportant, I can understand that. Just close it in that case.

**Comment by bluca** [comment] 2021-07-20 08:44
Yeah we shouldn't crash on such an error - any idea if it's reproducible with 249 (you can get it from experimental)? /cc @yuwata

**Comment by yuwata** [comment] 2021-08-04 03:51
> > 1. Cause a non-bridge interface to occupy a name, say `foo`, using a `systemd.link` file.
> > 2. Rename the interface in the `systemd.link` file to a different name, say `bar`.
> > 3. Create a `systemd.netdev` file that configures a bridge interface named `foo`.
> > 4. Create a `system.network` file that assigns another interface to the bridge named `foo`.
> > 5. `systemctl restart systemd-networkd`
> >    `networkd` keeps aborting. You can fix the situation by manually renaming the interface `foo` or by rebooting, in which case 

@helmtg Could you provide these .network, .netdev, and .link files explicitly?

**Comment by waldiTM** [comment] 2021-08-06 08:20
I see the same problem in another setting.
I use Ganeti to manage VM via qemu/kvm.
Now I want to use `systemd-networkd` to do the router advertisements for the completely routed network.

.network-File:
```
[Match]
Name=tap*

[Network]
DHCP=no
IPv6SendRA=yes
KeepConfiguration=static
IPForward=yes

[IPv6SendRA]
EmitDNS=yes
DNS=_link_local
DNSLifetimeSec=30min

[IPv6Prefix]
Prefix=2001:db8::/64
OnLink=no
Assign=yes
```

No special .link or .netdev files exist.

The link seems to be okay:
```
● 3: tap0                                                               
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: /etc/systemd/network/vm.network
                          Type: ether
                         State: routable (initialized)
                        Driver: tun
                    HW Address: 4a:c4:65:06:e5:81
                           MTU: 1500 (min: 68, max: 65521)
                         QDisc: pfifo_fast
  IPv6 Address Generation Mode: eui64
          Queue Length (Tx/Rx): 1/1
              Auto negotiation: no
                         Speed: 10Mbps
                        Duplex: full
                          Port: tp
                       Address: 2001:db8::48c4:65ff:fe06:e581
                                fe80::48c4:65ff:fe06:e581

Aug 06 08:12:54 debian systemd-networkd[244]: tap0: Link UP
Aug 06 08:12:54 debian systemd-networkd[244]: tap0: Gained carrier
Aug 06 08:12:55 debian systemd-networkd[244]: tap0: Gained IPv6LL
Aug 06 08:13:01 debian systemd-networkd[664]: tap0: Gained IPv6LL
Aug 06 08:13:01 debian systemd-networkd[665]: tap0: Gained IPv6LL
```

But every other restart of `systemd-networkd` breaks, sometimes even five time in a row.

```
Aug 06 08:16:16 debian systemd[1]: Stopped Network Service.
Aug 06 08:16:16 debian systemd[1]: Starting Network Service...
Aug 06 08:16:16 debian systemd-networkd[901]: tap1: Gained IPv6LL
Aug 06 08:16:16 debian systemd-networkd[901]: tap0: Gained IPv6LL
Aug 06 08:16:16 debian systemd-networkd[901]: enp0s2: Gained IPv6LL
Aug 06 08:16:16 debian systemd-networkd[901]: Enumeration completed
Aug 06 08:16:16 debian systemd[1]: Started Network Service.
Aug 06 08:16:16 debian systemd-networkd[901]: enp0s2: DHCPv4 address 10.0.2.15/24 via 10.0.2.2
Aug 06 08:16:16 debian systemd-networkd[901]: Assertion 'a' failed at src/network/networkd-address.c:1868, function address_is_ready(). Aborting.
Aug 06 08:16:16 debian systemd[1]: systemd-networkd.service: Main process exited, code=killed, status=6/ABRT
Aug 06 08:16:16 debian systemd[1]: systemd-networkd.service: Failed with result 'signal'.
Aug 06 08:16:16 debian systemd[1]: systemd-networkd.service: Scheduled restart job, restart counter is at 1.
```

It seems to not be reproducible in 249.2.

**Comment by yuwata** [comment] 2022-03-29 14:50
This cannot be reproducible with recent releases. Closing.

**Closed as completed by yuwata** 2022-03-29 14:50 UTC
Labels: bug 🐛, network, needs-reporter-feedback ❓

**Comment by votdev** [comment] 2023-05-31 07:52
Does anyone have any idea which commit is responsible for fixing this issue in 249.2? This would help to fix that issue in [Debian 11](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1036949#10).
