### ISSUE TITLE
systemd-modules-load.service at boot output is unavailable to systemctl status

### ISSUE THREAD

**Issue by zeha** [systemd/systemd#5130] opened 2017-01-22 22:45 UTC
### Submission type

  - [X] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> Debians systemd 232-7
> systemd 232 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)

### Used distribution

> Debian sid

### In case of bug report: Expected behaviour you didn't see

systemctl status should show output of systemd-modules-load.service, which ran just after journald has started.

Expected output:

```
● systemd-modules-load.service - Load Kernel Modules
   Loaded: loaded (/lib/systemd/system/systemd-modules-load.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2017-01-22 23:38:34 CET; 2s ago
     Docs: man:systemd-modules-load.service(8)
           man:modules-load.d(5)
  Process: 998 ExecStart=/lib/systemd/systemd-modules-load (code=exited, status=1/FAILURE)
 Main PID: 998 (code=exited, status=1/FAILURE)

Jan 22 23:38:34 sxl systemd[1]: Starting Load Kernel Modules...
Jan 22 23:38:34 sxl systemd[1]: systemd-modules-load.service: Main process exited, code=exited, status=1/FAILURE
Jan 22 23:38:34 sxl systemd[1]: Failed to start Load Kernel Modules.
Jan 22 23:38:34 sxl systemd[1]: systemd-modules-load.service: Unit entered failed state.
Jan 22 23:38:34 sxl systemd[1]: systemd-modules-load.service: Failed with result 'exit-code'.
```

Even better would be if the actual error would also be captured:
```
Jän 22 23:06:12 sxl systemd-modules-load[300]: Failed to find module 'athingthatdoesnotexist'
```

### In case of bug report: Unexpected behaviour you saw

```
● systemd-modules-load.service - Load Kernel Modules
   Loaded: loaded (/lib/systemd/system/systemd-modules-load.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2017-01-22 23:06:12 CET; 31min ago
     Docs: man:systemd-modules-load.service(8)
           man:modules-load.d(5)
 Main PID: 300 (code=exited, status=1/FAILURE)

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```

journalctl output:

```
Jän 22 23:06:12 sxl systemd[1]: systemd 232 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
Jän 22 23:06:12 sxl systemd[1]: Detected virtualization vmware.
Jän 22 23:06:12 sxl systemd[1]: Detected architecture x86-64.
Jän 22 23:06:12 sxl systemd[1]: Set hostname to <sxl>.
Jän 22 23:06:12 sxl systemd[1]: acpid.socket: Cannot add dependency job, ignoring: Unit acpid.socket is masked.
Jän 22 23:06:12 sxl systemd[1]: acpid.path: Cannot add dependency job, ignoring: Unit acpid.path is masked.
Jän 22 23:06:12 sxl systemd[1]: Started Dispatch Password Requests to Console Directory Watch.
Jän 22 23:06:12 sxl systemd[1]: Created slice User and Session Slice.
Jän 22 23:06:12 sxl systemd[1]: Listening on Journal Audit Socket.
Jän 22 23:06:12 sxl systemd[1]: Listening on /dev/initctl Compatibility Named Pipe.
Jän 22 23:06:12 sxl kernel: EXT4-fs (sda1): re-mounted. Opts: discard,user_xattr,errors=remount-ro
Jän 22 23:06:12 sxl kernel: RPC: Registered named UNIX socket transport module.
Jän 22 23:06:12 sxl kernel: RPC: Registered udp transport module.
Jän 22 23:06:12 sxl kernel: RPC: Registered tcp transport module.
Jän 22 23:06:12 sxl kernel: RPC: Registered tcp NFSv4.1 backchannel transport module.
Jän 22 23:06:12 sxl systemd-journald[299]: Journal started
Jän 22 23:06:12 sxl systemd-journald[299]: Runtime journal (/run/log/journal/48e9d21e953d4a28860cd5e78cddae4c) is 0B, max 0B, 0B free.
Jän 22 23:06:12 sxl systemd-modules-load[300]: Failed to find module 'athingthatdoesnotexist'
Jän 22 23:06:12 sxl systemd[1]: Starting Flush Journal to Persistent Storage...
Jän 22 23:06:12 sxl systemd-journald[299]: Runtime journal (/run/log/journal/48e9d21e953d4a28860cd5e78cddae4c) is 0B, max 0B, 0B free.
Jän 22 23:06:12 sxl systemd[1]: Started Flush Journal to Persistent Storage.
```

### In case of bug report: Steps to reproduce the problem

- install Debian sid test VM
- echo athingthatdoesnotexist >> /etc/modules
- reboot

Note: after `systemctl restart systemd-modules-load.service` after the system has booted, `systemctl status systemd-modules-load.service` shows the expected output.

**Comment by poettering** [comment] 2017-02-01 19:05
Can you provide the "journalctl -o verbose" output for the relevant log line generated by the load-modules service.

Most likely this is just an instance of #2913.

**Comment by zeha** [comment] 2017-02-01 19:24
```
Wed 2017-02-01 20:21:52.131757 CET [s=9706a03411204db8a83342186421518f;i=645;b=e8af52a980da4a3ca8c0fbe5f78ba9e8;m=41131d;t=5477cf5fec488;x=1f677b31c4f50474]
    _BOOT_ID=e8af52a980da4a3ca8c0fbe5f78ba9e8
    _MACHINE_ID=48e9d21e953d4a28860cd5e78cddae4c
    _HOSTNAME=sxl
    PRIORITY=3
    SYSLOG_FACILITY=3
    _UID=0
    _GID=0
    CODE_FILE=../src/modules-load/modules-load.c
    CODE_LINE=86
    CODE_FUNCTION=load_module
    SYSLOG_IDENTIFIER=systemd-modules-load
    MESSAGE=Failed to find module 'athingthatdoesnotexist'
    _TRANSPORT=journal
    _PID=297
    _SOURCE_REALTIME_TIMESTAMP=1485976912131757
```

**Comment by poettering** [comment] 2017-02-01 19:28
Yeah, the message is missing the _UNIT= field, which means the journal couldn't match this up. Closing as duplicate of #2913

**Closed as completed by poettering** 2017-02-01 19:28 UTC
Labels: journal, duplicate
