### ISSUE TITLE
nspawn does not tear down veth interface

### ISSUE THREAD

**Issue by jengelh** [systemd/systemd#2933] opened 2016-04-01 10:09 UTC
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 228
### Used distribution

> openSUSE Leap 42.1
### In case of bug report: Expected behaviour you didn't see

> Remove the veth interface that was implicitly created on nspawn start.
### In case of bug report: Unexpected behaviour you saw

```
Apr 01 11:55:40 niw-hv03 systemd-nspawn[13637]: Container iridium is being rebooted.
Apr 01 11:55:40 niw-hv03 systemd[1]: systemd-nspawn@iridium.service: Service hold-off time over, scheduling restart.
Apr 01 11:55:40 niw-hv03 systemd[1]: Stopped Container iridium.
Apr 01 11:55:40 niw-hv03 systemd[1]: Starting Container iridium...
Apr 01 11:55:40 niw-hv03 systemd-nspawn[14412]: Spawning container iridium on /D/machines/iridium-191.
Apr 01 11:55:40 niw-hv03 systemd-nspawn[14412]: Press ^] three times within 1s to kill container.
Apr 01 11:55:40 niw-hv03 systemd-nspawn[14412]: mount(/D/machines/iridium-191/sys/fs/selinux) failed, ignoring: No such file or directory
Apr 01 11:55:40 niw-hv03 systemd-nspawn[14412]: mount(/D/machines/iridium-191/sys/fs/selinux) failed, ignoring: Invalid argument
Apr 01 11:55:40 niw-hv03 systemd[1]: systemd-nspawn@iridium.service: Main process exited, code=exited, status=1/FAILURE
Apr 01 11:55:40 niw-hv03 systemd[1]: Failed to start Container iridium.
Apr 01 11:55:40 niw-hv03 systemd[1]: systemd-nspawn@iridium.service: Unit entered failed state.
Apr 01 11:55:40 niw-hv03 systemd[1]: systemd-nspawn@iridium.service: Failed with result 'exit-code'.
Apr 01 11:55:40 niw-hv03 systemd[1]: Stopped Container iridium.
Apr 01 11:55:40 niw-hv03 systemd-nspawn[14412]: Failed to add new veth interfaces (ve-iridium:host0): File exists
Apr 01 11:55:40 niw-hv03 systemd-nspawn[14412]: Parent died too early
```
### In case of bug report: Steps to reproduce the problem

> Issue `reboot` from within the container, or `systemctl restart` from outside. The interface also sticks around with `systemctl stop` for at least some time.

**Comment by poettering** [comment] 2016-04-01 14:33
hmm, normally the kernel should kill the veth link automatically when the container namespace goes away... If it stays around there's something else going wrong, which cause the namespace to stick around for longer.

Issues with this have been reported before, hence I figure we should explicitly kill the veth link, just to be safe, and fix the race on reboots.

**Comment by poettering** [comment] 2016-04-18 16:41
Duplicate of #2173.

**Closed as completed by poettering** 2016-04-18 16:41 UTC
Labels: nspawn, duplicate
