### ISSUE TITLE
systemd-rescue mode should be able to trigger reboot via CTRL+DEL

### ISSUE THREAD

**Issue by shibumi** [systemd/systemd#6454] opened 2017-07-25 18:15 UTC
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 233

### Used distribution

> Arch Linux

Following scenario:

I use systemd-boot with systemd kernel hooks. When I don't enter my password for the decryption process of my LUKS devices systemd-boot will jump into rescue mode. In this mode it's not possible to reboot via `systemd reboot` nor via `init 0` or `reboot`. It would be nice if it would be possible to press CTRL+DEL in that mode to trigger a reboot.

**Comment by poettering** [comment] 2017-07-31 09:17
I figure #6482 and #6484 are the reasons for this issue. I'll close this one as duplicate now, as I am quite confident, that fixes those two bugs will fix this one too!

duplicate of #6482 and #6484.

**Closed as completed by poettering** 2017-07-31 09:17 UTC
Labels: pid1, duplicate

**Comment by sourcejedi** [comment] 2017-08-16 16:28
I don't think so.  TL;DR - but it could be #6504 (fixed in master branch), particularly if it affects systems with auditting enabled.

---

It's not the initctl bug, because that affects poweroff only.  And systemctl doesn't fall back to signals.  In fact my failure occurs despite `systemctl` successfully connecting to and sending messages to `/run/systemd/private`.  (courtesy of `strace`).

I reproduced something that looks similar on Fedora 26 (systemd-233-6.fc26.x86_64), when I happened to run `systemctl emergency` and then `systemctl emergency` again.  Neither `systemctl reboot` nor `systemctl poweroff` worked.  Nor did ctrl+alt+del (maybe its a similar reason that didn't work in some of my other bugs?)

After the 2x `systemctl emergency`, I get this:

```
# systemctl list-jobs
 JOB UNIT                          TYPE STATE  
1075 systemd-journald-audit.socket stop waiting
```

and `top` shows systemd using 10-12% cpu.
