### ISSUE TITLE
Compilation is failing under Fedora Rawhide x86_64

### ISSUE THREAD

**Issue by fredericlepied** [systemd/systemd#7575] opened 2017-12-07 14:54 UTC
### Submission type

 - Bug report
 

### systemd version the issue has been seen with

> …
master branch after commit https://github.com/systemd/systemd/commit/c1a3890410f043fe09af8b139eb6bfe2832089be

### Used distribution

> …
Fedora Rawhide x86_64

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

> …
Compilation error:

[292/1866] cc  -o libsystemd.so.0.19.1 'systemd@sha/src_libsystemd_sd-bus_bus-bloom.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-common-errors.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-container.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-control.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-convenience.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-creds.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-dump.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-error.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-gvariant.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-internal.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-introspect.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-kernel.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-match.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-message.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-objects.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-signature.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-slot.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-socket.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-track.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-type.c.o' 'systemd@sha/src_libsystemd_sd-bus_sd-bus.c.o' 'systemd@sha/src_libsystemd_sd-daemon_sd-daemon.c.o' 'systemd@sha/src_libsystemd_sd-device_device-enumerator.c.o' 'systemd@sha/src_libsystemd_sd-device_device-private.c.o' 'systemd@sha/src_libsystemd_sd-device_sd-device.c.o' 'systemd@sha/src_libsystemd_sd-event_sd-event.c.o' 'systemd@sha/src_libsystemd_sd-hwdb_sd-hwdb.c.o' 'systemd@sha/src_libsystemd_sd-id128_id128-util.c.o' 'systemd@sha/src_libsystemd_sd-id128_sd-id128.c.o' 'systemd@sha/src_libsystemd_sd-netlink_local-addresses.c.o' 'systemd@sha/src_libsystemd_sd-netlink_netlink-message.c.o' 'systemd@sha/src_libsystemd_sd-netlink_netlink-socket.c.o' 'systemd@sha/src_libsystemd_sd-netlink_netlink-types.c.o' 'systemd@sha/src_libsystemd_sd-netlink_netlink-util.c.o' 'systemd@sha/src_libsystemd_sd-netlink_rtnl-message.c.o' 'systemd@sha/src_libsystemd_sd-netlink_sd-netlink.c.o' 'systemd@sha/src_libsystemd_sd-network_network-util.c.o' 'systemd@sha/src_libsystemd_sd-network_sd-network.c.o' 'systemd@sha/src_libsystemd_sd-path_sd-path.c.o' 'systemd@sha/src_libsystemd_sd-resolve_sd-resolve.c.o' 'systemd@sha/src_libsystemd_sd-utf8_sd-utf8.c.o' 'systemd@sha/src_libsystemd_sd-login_sd-login.c.o' 'systemd@sha/src_journal_audit-type.c.o' 'systemd@sha/src_journal_catalog.c.o' 'systemd@sha/src_journal_compress.c.o' 'systemd@sha/src_journal_journal-file.c.o' 'systemd@sha/src_journal_journal-send.c.o' 'systemd@sha/src_journal_journal-vacuum.c.o' 'systemd@sha/src_journal_journal-verify.c.o' 'systemd@sha/src_journal_lookup3.c.o' 'systemd@sha/src_journal_mmap-cache.c.o' 'systemd@sha/src_journal_sd-journal.c.o' 'systemd@sha/src_journal_journal-authenticate.c.o' 'systemd@sha/src_journal_fsprg.c.o' 'systemd@sha/src_shared_gcrypt-util.c.o' -flto -Wl,--no-undefined -Wl,--as-needed -shared -fPIC -Wl,--start-group -Wl,-soname,libsystemd.so.0 -Wl,-z,relro -Wl,-z,now -pie -Wl,--gc-sections -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld src/basic/libbasic.a -pthread -shared -Wl,--version-script=/builddir/build/BUILD/systemd-236/src/libsystemd/libsystemd.sym -lgcrypt -lrt -llzma -llz4 -lcap -lblkid -lselinux -Wl,--end-group '-Wl,-rpath,$ORIGIN/' -Wl,-rpath-link,/builddir/build/BUILD/systemd-236/x86_64-redhat-linux-gnu/  
FAILED: libsystemd.so.0.19.1 
cc  -o libsystemd.so.0.19.1 'systemd@sha/src_libsystemd_sd-bus_bus-bloom.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-common-errors.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-container.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-control.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-convenience.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-creds.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-dump.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-error.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-gvariant.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-internal.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-introspect.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-kernel.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-match.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-message.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-objects.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-signature.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-slot.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-socket.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-track.c.o' 'systemd@sha/src_libsystemd_sd-bus_bus-type.c.o' 'systemd@sha/src_libsystemd_sd-bus_sd-bus.c.o' 'systemd@sha/src_libsystemd_sd-daemon_sd-daemon.c.o' 'systemd@sha/src_libsystemd_sd-device_device-enumerator.c.o' 'systemd@sha/src_libsystemd_sd-device_device-private.c.o' 'systemd@sha/src_libsystemd_sd-device_sd-device.c.o' 'systemd@sha/src_libsystemd_sd-event_sd-event.c.o' 'systemd@sha/src_libsystemd_sd-hwdb_sd-hwdb.c.o' 'systemd@sha/src_libsystemd_sd-id128_id128-util.c.o' 'systemd@sha/src_libsystemd_sd-id128_sd-id128.c.o' 'systemd@sha/src_libsystemd_sd-netlink_local-addresses.c.o' 'systemd@sha/src_libsystemd_sd-netlink_netlink-message.c.o' 'systemd@sha/src_libsystemd_sd-netlink_netlink-socket.c.o' 'systemd@sha/src_libsystemd_sd-netlink_netlink-types.c.o' 'systemd@sha/src_libsystemd_sd-netlink_netlink-util.c.o' 'systemd@sha/src_libsystemd_sd-netlink_rtnl-message.c.o' 'systemd@sha/src_libsystemd_sd-netlink_sd-netlink.c.o' 'systemd@sha/src_libsystemd_sd-network_network-util.c.o' 'systemd@sha/src_libsystemd_sd-network_sd-network.c.o' 'systemd@sha/src_libsystemd_sd-path_sd-path.c.o' 'systemd@sha/src_libsystemd_sd-resolve_sd-resolve.c.o' 'systemd@sha/src_libsystemd_sd-utf8_sd-utf8.c.o' 'systemd@sha/src_libsystemd_sd-login_sd-login.c.o' 'systemd@sha/src_journal_audit-type.c.o' 'systemd@sha/src_journal_catalog.c.o' 'systemd@sha/src_journal_compress.c.o' 'systemd@sha/src_journal_journal-file.c.o' 'systemd@sha/src_journal_journal-send.c.o' 'systemd@sha/src_journal_journal-vacuum.c.o' 'systemd@sha/src_journal_journal-verify.c.o' 'systemd@sha/src_journal_lookup3.c.o' 'systemd@sha/src_journal_mmap-cache.c.o' 'systemd@sha/src_journal_sd-journal.c.o' 'systemd@sha/src_journal_journal-authenticate.c.o' 'systemd@sha/src_journal_fsprg.c.o' 'systemd@sha/src_shared_gcrypt-util.c.o' -flto -Wl,--no-undefined -Wl,--as-needed -shared -fPIC -Wl,--start-group -Wl,-soname,libsystemd.so.0 -Wl,-z,relro -Wl,-z,now -pie -Wl,--gc-sections -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld src/basic/libbasic.a -pthread -shared -Wl,--version-script=/builddir/build/BUILD/systemd-236/src/libsystemd/libsystemd.sym -lgcrypt -lrt -llzma -llz4 -lcap -lblkid -lselinux -Wl,--end-group '-Wl,-rpath,$ORIGIN/' -Wl,-rpath-link,/
### In case of bug report: Steps to reproduce the problem

Complete log at http://38.145.33.116/systemd-master/c1/a3/c1a3890410f043fe09af8b139eb6bfe2832089be_57d0af03/build.log.gz

> …

**Comment by poettering** [comment] 2017-12-07 15:10
well, this is broken in gcc somewhere. the relevant bits from the logs are:

```
*** WARNING *** there are active plugins, do not report this as a bug unless you can reproduce it without enabling any plugins.
Event                            | Plugins
PLUGIN_FINISH_UNIT               | Generate final annotations
PLUGIN_START_UNIT                | Generate global annotations
PLUGIN_ALL_PASSES_END            | Generate per-function annotations
lto1: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
lto-wrapper: fatal error: cc returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
```

Seems rawhide hasn't been in order since a week or so, we have been ignoring all rawhide CI results since gcc started to segfault systematically on this.

Most likely this is triggered by our use of LTO, but it's ultimately a bug in gcc/binutils that needs to be fixed, not in our code

**Comment by keszybz** [comment] 2017-12-11 13:19
This seems to be fixed now. Recent Fedora CI builds fail with a different error. I tried to diagnose what exactly changed to fix this, but gcc-7.2.1-3.fc28.x86_64 with binutils-2.29.1-5.fc28  does not crash, even though it did crash in CI. So it seems that something else is responsible, but I don't know what exactly.

Fedora spec file needs to be adjusted for some new files, I'll take care of this.

**Comment by keszybz** [comment] 2017-12-11 23:02
<strike>https://bugzilla.redhat.com/show_bug.cgi?id=1524737</strike>

**Comment by keszybz** [comment] 2017-12-12 12:55
@yuwata and I updated the rawhide spec file, it builds fine now. And the segfault bug was caused by annobin, this should be fixed now too.

**Closed as completed by keszybz** 2017-12-12 12:55 UTC
Labels: not-our-bug, ci
