### ISSUE TITLE
systemd-resolved: RRSIG format error unless EDNS is disabled

### ISSUE THREAD

**Issue by fjros** [systemd/systemd#9241] opened 2018-06-08 17:32 UTC
**systemd version the issue has been seen with**
systemd 237

**Used distribution**
 Ubuntu 18.04

**Expected behaviour you didn't see**

```
root@systemd-00:~# host -t RRSIG keyserver.ubuntu.com
keyserver.ubuntu.com has no RRSIG record
```

**Unexpected behaviour you saw**

Query fails:

```
root@systemd-00:~# host -t RRSIG keyserver.ubuntu.com
Host keyserver.ubuntu.com not found: 1(FORMERR)
```

```
root@systemd-00:~# dig -t RRSIG keyserver.ubuntu.com
; <<>> DiG 9.11.3-1ubuntu1-Ubuntu <<>> -t RRSIG keyserver.ubuntu.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: FORMERR, id: 39656
;; flags: qr rd ra; QUERY: 0, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; WARNING: EDNS query returned status FORMERR - retry with '+noedns'

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Fri Jun 08 17:06:38 UTC 2018
;; MSG SIZE  rcvd: 12
```

But succeeds if edns is disabled:

```
root@systemd-00:~# dig -t RRSIG keyserver.ubuntu.com +noedns

; <<>> DiG 9.11.3-1ubuntu1-Ubuntu <<>> -t RRSIG keyserver.ubuntu.com +noedns
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: FORMERR, id: 44610
;; flags: qr rd ra; QUERY: 0, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; Query time: 1 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Fri Jun 08 17:07:47 UTC 2018
;; MSG SIZE  rcvd: 12
```

**Steps to reproduce the problem**

Using systemd-resolved as DNS stub listener, try to get a RRSIG record:

`host -t RRSIG keyserver.ubuntu.com`

**Comment by poettering** [comment] 2018-06-08 18:43
duplicate of #4621

**Closed as completed** 2018-06-08 18:43 UTC
Labels: resolve, duplicate
