### ISSUE TITLE
nspawn boot fails when private-users defined - Failed to write boot id: Permission denied

### ISSUE THREAD

**Issue by LaKing** [systemd/systemd#6244] opened 2017-06-30 03:33 UTC
- Bug report
Fedora systemd-233-6.fc26.x86_64

### In case of bug report: Expected behaviour you didn't see

The defined nspawn container(s) booting up, using the custom private user id.

### In case of bug report: Unexpected behaviour you saw
```
Jun 30 05:14:30 t2.test.vm systemd[1]: Starting srvctl - container echo-two.ve...
-- Subject: Unit srvctl-nspawn@echo-two.ve.service has begun start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit srvctl-nspawn@echo-two.ve.service has begun starting up.
Jun 30 05:14:30 t2.test.vm systemd-nspawn[29691]: Spawning container echo-two.ve on /srv/echo-two.ve/rootfs.
Jun 30 05:14:30 t2.test.vm systemd-nspawn[29691]: Press ^] three times within 1s to kill container.
Jun 30 05:14:30 t2.test.vm systemd-nspawn[29691]: Selected user namespace base 262144 and range 65536.
Jun 30 05:14:30 t2.test.vm systemd[1]: srvctl-nspawn@echo-two.ve.service: Main process exited, code=exited, status=1/FAILURE
Jun 30 05:14:30 t2.test.vm systemd-nspawn[29691]: Failed to write boot id: Permission denied
Jun 30 05:14:30 t2.test.vm systemd[1]: Failed to start srvctl - container echo-two.ve.
-- Subject: Unit srvctl-nspawn@echo-two.ve.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit srvctl-nspawn@echo-two.ve.service has failed.
-- 
-- The result is failed.
Jun 30 05:14:30 t2.test.vm systemd-nspawn[29691]: Child died too early.
Jun 30 05:14:30 t2.test.vm systemd[1]: srvctl-nspawn@echo-two.ve.service: Unit entered failed state.
Jun 30 05:14:30 t2.test.vm systemd[1]: srvctl-nspawn@echo-two.ve.service: Failed with result 'exit-code'.
```
### In case of bug report: Steps to reproduce the problem

I have created a custom nspawn@.service based on systemd-nspawn@.service.
With the -U option removed from the service file, and PrivateUsers=262144 (for example) and PrivateUsersChown=true defined in the .nspawn file, the container(s) fail to boot.

The custom uid's seem to have been applied on the rootfs. I see the right uid's and gid's.
```
drwxr-xr-x 17 262144 262144 224 Jun 30 04:59 rootfs
```

As far as I can see the main error is: 
```
systemd-nspawn[...]: Failed to write boot id: Permission denied
```

Unless PrivateUsers=0, it fails when using any other valid uid.

A quick search took me to nspawn.c file, line 1430
```
        from = prefix_roota(dest, "/run/proc-sys-kernel-random-boot-id");
        to = prefix_roota(dest, "/proc/sys/kernel/random/boot_id");

        r = sd_id128_randomize(&rnd);
        if (r < 0)
                return log_error_errno(r, "Failed to generate random boot id: %m");

        r = id128_write(from, ID128_UUID, rnd, false);
```

How can I help to fix this issue?

**Comment by LaKing** [comment] 2017-06-30 21:38
Booting the container directly with the nspawn command does not fail completly, but there are many many Permission related errors. 

```
[root@t2 echo-two.ve]# systemd-nspawn -bD /srv/echo-two.ve/rootfs  --private-users=131072 --private-users-chown
Spawning container rootfs on /srv/echo-two.ve/rootfs.
Press ^] three times within 1s to kill container.
Selected user namespace base 131072 and range 65536.
systemd 233 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN default-hierarchy=hybrid)
Detected virtualization systemd-nspawn.
Detected architecture x86-64.

Welcome to Fedora 26 (Twenty Six)!

Failed to create compat systemd cgroup /init.scope: Permission denied
Failed to attach 1 to compat systemd cgroup /init.scope: No such file or directory
Failed to create compat systemd cgroup /user.slice: Permission denied
user.slice: Failed to set invocation ID on control group /user.slice, ignoring: Operation not permitted
[  OK  ] Created slice User and Session Slice.
[  OK  ] Listening on Journal Socket.
[  OK  ] Reached target Swap.
Failed to create compat systemd cgroup /system.slice: Permission denied
system.slice: Failed to set invocation ID on control group /system.slice, ignoring: Operation not permitted
[  OK  ] Created slice System Slice.
Failed to create compat systemd cgroup /system.slice/system-getty.slice: Permission denied
system-getty.slice: Failed to set invocation ID on control group /system.slice/system-getty.slice, ignoring: Operation not permitted
[  OK  ] Created slice system-getty.slice.
[  OK  ] Listening on /dev/initctl Compatibility Named Pipe.
[  OK  ] Listening on Journal Socket (/dev/log).
[  OK  ] Reached target Slices.
[  OK  ] Started Dispatch Password Requests to Console Directory Watch.
Failed to create compat systemd cgroup /system.slice/dev-mqueue.mount: Permission denied
dev-mqueue.mount: Failed to set invocation ID on control group /system.slice/dev-mqueue.mount, ignoring: Operation not permitted
Failed to attach 14 to compat systemd cgroup /system.slice/dev-mqueue.mount: No such file or directory
         Mounting POSIX Message Queue File System...
Failed to create compat systemd cgroup /system.slice/fedora-readonly.service: Permission denied
fedora-readonly.service: Failed to set invocation ID on control group /system.slice/fedora-readonly.service, ignoring: Operation not permitted
Failed to attach 15 to compat systemd cgroup /system.slice/fedora-readonly.service: No such file or directory
         Starting Configure read-only root support...
[  OK  ] Reached target Local File Systems (Pre).
Failed to create compat systemd cgroup /system.slice/system-sshd\x2dkeygen.slice: Permission denied
system-sshd\x2dkeygen.slice: Failed to set invocation ID on control group /system.slice/system-sshd\x2dkeygen.slice, ignoring: Operation not permitted
[  OK  ] Created slice system-sshd\x2dkeygen.slice.
[  OK  ] Started Forward Password Requests to Wall Directory Watch.
[  OK  ] Reached target Encrypted Volumes.
[  OK  ] Reached target Paths.
[  OK  ] Listening on Process Core Dump Socket.
Failed to create compat systemd cgroup /system.slice/systemd-journald.service: Permission denied
systemd-journald.service: Failed to set invocation ID on control group /system.slice/systemd-journald.service, ignoring: Operation not permitted
Failed to attach 16 to compat systemd cgroup /system.slice/systemd-journald.service: No such file or directory
         Starting Journal Service...
Failed to create compat systemd cgroup /system.slice/tmp.mount: Permission denied
Failed to create compat systemd cgroup /system.slice/-.mount: Permission denied
Failed to create compat systemd cgroup /system.slice/proc-sysrq\x2dtrigger.mount: Permission denied
Failed to create compat systemd cgroup /system.slice/run-systemd-nspawn-incoming.mount: Permission denied
Failed to create compat systemd cgroup /system.slice/etc-resolv.conf.mount: Permission denied
Failed to create compat systemd cgroup /system.slice/proc-sys-kernel-random-boot_id.mount: Permission denied
[  OK  ] Mounted POSIX Message Queue File System.
[  OK  ] Started Journal Service.
         Starting Flush Journal to Persistent Storage...
[  OK  ] Started Configure read-only root support.
[  OK  ] Reached target Local File Systems.
         Starting Preprocess NFS configuration...
[  OK  ] Started Preprocess NFS configuration.
[  OK  ] Started Flush Journal to Persistent Storage.
         Starting Create Volatile Files and Directories...
[  OK  ] Started Create Volatile Files and Directories.
         Starting Update UTMP about System Boot/Shutdown...
         Mounting RPC Pipe File System...
[FAILED] Failed to mount RPC Pipe File System.
See 'systemctl status var-lib-nfs-rpc_pipefs.mount' for details.
[DEPEND] Dependency failed for rpc_pipefs.target.
[DEPEND] Dependency failed for RPC security service for NFS client and server.
[  OK  ] Started Update UTMP about System Boot/Shutdown.
[  OK  ] Reached target System Initialization.
[  OK  ] Started Daily Cleanup of Temporary Directories.
[  OK  ] Listening on D-Bus System Message Bus Socket.
[  OK  ] Reached target Sockets.
[  OK  ] Started dnf makecache timer.
[  OK  ] Reached target Timers.
[  OK  ] Reached target Basic System.
[  OK  ] Reached target sshd-keygen.target.
         Starting GSSAPI Proxy Daemon...
[  OK  ] Started D-Bus System Message Bus.
         Starting System Logging Service...
[  OK  ] Reached target Network.
         Starting OpenSSH server daemon...
         Starting Network Name Resolution...
         Starting Login Service...
[  OK  ] Started GSSAPI Proxy Daemon.
[  OK  ] Reached target NFS client services.
[  OK  ] Reached target Remote File Systems (Pre).
[  OK  ] Reached target Remote File Systems.
         Starting Permit User Sessions...
[  OK  ] Started Permit User Sessions.
[  OK  ] Started Console Getty.
[  OK  ] Reached target Login Prompts.
[  OK  ] Started Login Service.
[  OK  ] Started Network Name Resolution.
[  OK  ] Reached target Host and Network Name Lookups.
         Starting The Apache HTTP Server...
[  OK  ] Reached target Network is Online.
         Starting Notify NFS peers of a restart...
[FAILED] Failed to start OpenSSH server daemon.
See 'systemctl status sshd.service' for details.
[  OK  ] Started Notify NFS peers of a restart.
[  OK  ] Started System Logging Service.
[FAILED] Failed to start The Apache HTTP Server.
See 'systemctl status httpd.service' for details.
[  OK  ] Reached target Multi-User System.
[  OK  ] Reached target Graphical Interface.
         Starting Update UTMP about System Runlevel Changes...
[  OK  ] Started Update UTMP about System Runlevel Changes.

Fedora 26 (Twenty Six)
Kernel 4.11.7-300.fc26.x86_64 on an x86_64 (console)

rootfs login: 

```

**Comment by poettering** [comment] 2017-07-03 14:17
hmm, strange, very strange...

**Comment by LaKing** [comment] 2017-07-15 15:35
Since fedora 26 has been released I checked against it, ...

test1.ve.nspawn file
```
[Network]
Bridge=10.69.0.x

[Exec]
PrivateUsers=131072

[Files]
PrivateUsersChown=true
```

And then the command to start
```
[root@t1 test1.ve]# /usr/bin/systemd-nspawn --boot --settings=trusted --machine=test1.ve -D /srv/test1.ve/rootfs
Spawning container test1.ve on /srv/test1.ve/rootfs.
Press ^] three times within 1s to kill container.
Child died too early.
Selected user namespace base 131072 and range 65536.
Failed to write boot id: Permission denied

```

or 

```
[root@t1 test1.ve]# systemd-nspawn -bD /srv/test1.ve/rootfs  --private-users=131072 --private-users-chown
Spawning container rootfs on /srv/test1.ve/rootfs.
Press ^] three times within 1s to kill container.
Selected user namespace base 131072 and range 65536.
systemd 233 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN default-hierarchy=hybrid)
Detected virtualization systemd-nspawn.
Detected architecture x86-64.

Welcome to Fedora 26 (Twenty Six)!

Failed to create compat systemd cgroup /init.scope: Permission denied
Failed to attach 1 to compat systemd cgroup /init.scope: No such file or directory
[  OK  ] Listening on /dev/initctl Compatibility Named Pipe.
[  OK  ] Reached target Swap.
Failed to create compat systemd cgroup /system.slice: Permission denied
system.slice: Failed to set invocation ID on control group /system.slice, ignoring: Operation not permitted
[  OK  ] Created slice System Slice.
Failed to create compat systemd cgroup /system.slice/system-getty.slice: Permission denied
system-getty.slice: Failed to set invocation ID on control group /system.slice/system-getty.slice, ignoring: Operation not permitted
[  OK  ] Created slice system-getty.slice.
[  OK  ] Listening on Journal Socket (/dev/log).
[  OK  ] Reached target Remote File Systems.
[  OK  ] Listening on Process Core Dump Socket.
Failed to create compat systemd cgroup /system.slice/dev-mqueue.mount: Permission denied
dev-mqueue.mount: Failed to set invocation ID on control group /system.slice/dev-mqueue.mount, ignoring: Operation not permitted
Failed to attach 12 to compat systemd cgroup /system.slice/dev-mqueue.mount: No such file or directory
         Mounting POSIX Message Queue File System...
[  OK  ] Started Forward Password Requests to Wall Directory Watch.
[  OK  ] Started Dispatch Password Requests to Console Directory Watch.
[  OK  ] Reached target Paths.
[  OK  ] Reached target Encrypted Volumes.
Failed to create compat systemd cgroup /system.slice/system-sshd\x2dkeygen.slice: Permission denied
system-sshd\x2dkeygen.slice: Failed to set invocation ID on control group /system.slice/system-sshd\x2dkeygen.slice, ignoring: Operation not permitted
[  OK  ] Created slice system-sshd\x2dkeygen.slice.
Failed to create compat systemd cgroup /user.slice: Permission denied
user.slice: Failed to set invocation ID on control group /user.slice, ignoring: Operation not permitted
[  OK  ] Created slice User and Session Slice.
[  OK  ] Reached target Slices.
[  OK  ] Listening on Journal Socket.
[  OK  ] Reached target Local File Systems (Pre).
Failed to create compat systemd cgroup /system.slice/systemd-journald.service: Permission denied
systemd-journald.service: Failed to set invocation ID on control group /system.slice/systemd-journald.service, ignoring: Operation not permitted
Failed to attach 13 to compat systemd cgroup /system.slice/systemd-journald.service: No such file or directory
         Starting Journal Service...
Failed to create compat systemd cgroup /system.slice/fedora-readonly.service: Permission denied
fedora-readonly.service: Failed to set invocation ID on control group /system.slice/fedora-readonly.service, ignoring: Operation not permitted
Failed to attach 14 to compat systemd cgroup /system.slice/fedora-readonly.service: No such file or directory
         Starting Configure read-only root support...
Failed to create compat systemd cgroup /system.slice/systemd-sysusers.service: Permission denied
systemd-sysusers.service: Failed to set invocation ID on control group /system.slice/systemd-sysusers.service, ignoring: Operation not permitted
Failed to attach 15 to compat systemd cgroup /system.slice/systemd-sysusers.service: No such file or directory
         Starting Create System Users...
Failed to create compat systemd cgroup /system.slice/run-systemd-nspawn-incoming.mount: Permission denied
Failed to create compat systemd cgroup /system.slice/proc-sys-kernel-random-boot_id.mount: Permission denied
Failed to create compat systemd cgroup /system.slice/-.mount: Permission denied
Failed to create compat systemd cgroup /system.slice/proc-sysrq\x2dtrigger.mount: Permission denied
Failed to create compat systemd cgroup /system.slice/tmp.mount: Permission denied
Failed to create compat systemd cgroup /system.slice/etc-resolv.conf.mount: Permission denied
[  OK  ] Mounted POSIX Message Queue File System.
[  OK  ] Started Create System Users.
[  OK  ] Started Journal Service.
         Starting Flush Journal to Persistent Storage...
[  OK  ] Started Configure read-only root support.
[  OK  ] Reached target Local File Systems.
         Starting Rebuild Journal Catalog...
         Starting Rebuild Dynamic Linker Cache...
         Starting Mark the need to relabel after reboot...
[  OK  ] Started Mark the need to relabel after reboot.
[  OK  ] Started Rebuild Dynamic Linker Cache.
[  OK  ] Started Rebuild Journal Catalog.
         Starting Update is Completed...
[  OK  ] Started Update is Completed.
[  OK  ] Started Flush Journal to Persistent Storage.
         Starting Create Volatile Files and Directories...
[  OK  ] Started Create Volatile Files and Directories.
         Starting Update UTMP about System Boot/Shutdown...
[  OK  ] Started Update UTMP about System Boot/Shutdown.
[  OK  ] Reached target System Initialization.
[  OK  ] Started Daily Cleanup of Temporary Directories.
[  OK  ] Started dnf makecache timer.
[  OK  ] Reached target Timers.
[  OK  ] Reached target Network.
[  OK  ] Listening on D-Bus System Message Bus Socket.
[  OK  ] Reached target Sockets.
[  OK  ] Reached target Basic System.
         Starting Permit User Sessions...
         Starting Network Name Resolution...
         Starting System Logging Service...
         Starting OpenSSH ed25519 Server Key Generation...
         Starting OpenSSH rsa Server Key Generation...
[  OK  ] Started D-Bus System Message Bus.
         Starting Login Service...
         Starting OpenSSH ecdsa Server Key Generation...
[  OK  ] Started Permit User Sessions.
[  OK  ] Started Console Getty.
[  OK  ] Reached target Login Prompts.
[  OK  ] Started OpenSSH ed25519 Server Key Generation.
[  OK  ] Started Login Service.
[  OK  ] Started OpenSSH ecdsa Server Key Generation.
[  OK  ] Started Network Name Resolution.
[  OK  ] Reached target Host and Network Name Lookups.
         Starting The Apache HTTP Server...
[  OK  ] Started OpenSSH rsa Server Key Generation.
[  OK  ] Reached target sshd-keygen.target.
         Starting OpenSSH server daemon...
[FAILED] Failed to start OpenSSH server daemon.
See 'systemctl status sshd.service' for details.
[  OK  ] Started System Logging Service.
[FAILED] Failed to start The Apache HTTP Server.
See 'systemctl status httpd.service' for details.
[  OK  ] Reached target Multi-User System.
[  OK  ] Reached target Graphical Interface.
         Starting Update UTMP about System Runlevel Changes...
[  OK  ] Started Update UTMP about System Runlevel Changes.

Fedora 26 (Twenty Six)
Kernel 4.11.9-300.fc26.x86_64 on an x86_64 (console)

rootfs login: 

```

So the bug seems to be there.

**Comment by LaKing** [comment] 2017-09-02 22:49
Can I do something to debug this? I have no clue where to start, but willing to help!

**Comment by LaKing** [comment] 2017-11-15 02:05
The problem still persist at the release of fedora 27.  - systemd 234

**Comment by Mic92** [comment] 2018-01-08 17:09
I attached with my [container debugging tool](https://github.com/Mic92/cntr) during the boot process to systemd-nspawn and saw that it did not correctly change the owner of mount points:

```console
$ ls -la /var/lib/cntr
rwxr-xr-x  13 root   root     13 Jan  8 17:47 .
drwxr-xr-x  40 root   root     41 Jan  3 11:20 ..
drwxr-xr-x   5 nobody nogroup 360 Jan  8 18:00 dev
drwxr-xr-x   2 root   root      4 Jan  8 17:47 etc
drwxr-xr-x   4 root   root      4 Jan  8 17:47 nix
dr-xr-xr-x 263 nobody nogroup   0 Jan  8 18:00 proc
drwx------   2 root   root      2 Jan  8 17:47 root
drwxr-xr-x   3 nobody nogroup  60 Jan  8 18:00 run
drwxr-xr-x   2 root   root      3 Jan  8 17:47 sbin
dr-xr-xr-x  13 nobody nogroup   0 Jan  8 17:19 sys
drwxrwxrwt   6 nobody nogroup 120 Jan  8 18:02 tmp
drwxr-xr-x   2 root   root      2 Jan  8 17:47 usr
drwxr-xr-x   4 root   root      4 Jan  8 17:47 var
```

`/tmp` is owned by uid 0 on the host and not by the unprivileged container user.

**Comment by Mic92** [comment] 2018-01-08 17:12
Is there an regression test for unprivileged containers in systemd-nspawn?

**Comment by Mic92** [comment] 2018-01-08 17:29
According to the function name this should actually ensure the directory to be created with correct uid/gid:

https://github.com/systemd/systemd/blob/master/src/nspawn/nspawn-mount.c#L599

**Comment by Mic92** [comment] 2018-01-08 21:12
This mount call causes the directories, that are mountpoints to change their owner back to root:
https://github.com/systemd/systemd/blob/master/src/basic/mount-util.c#L600

**Comment by poettering** [comment] 2018-01-24 13:41
@Mic92 hmm, but that'd be a kernel bug, no? 

> Is there a regression test for unprivileged containers in systemd-nspawn?

there are some nspawn tests (test/TEST-13-NSPAWN-SMOKE), but they do not test the private user feature really. Would be great to add some however ;-)

**Comment by Mic92** [comment] 2018-01-24 16:54
@poettering the problem is that mount() creates a new inode on a different filesystem (see device numbers):

```
[nobody@turingmachine:/var/lib/cntr]$ stat .
  File: .
  Size: 13              Blocks: 3          IO Block: 1024   directory
Device: 18h/24d Inode: 517135      Links: 13
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-01-24 12:07:59.479752962 +0000
Modify: 2018-01-08 21:52:59.430194721 +0000
Change: 2018-01-08 21:52:59.430194721 +0000
 Birth: -
[nobody@turingmachine:/var/lib/cntr]$ stat sys
  File: sys
  Size: 0               Blocks: 0          IO Block: 4096   directory
Device: 15h/21d Inode: 1           Links: 13
Access: (0555/dr-xr-xr-x)  Uid: (65534/  nobody)   Gid: (65534/ nogroup)
Access: 2018-01-22 23:24:14.772993436 +0000
Modify: 2018-01-22 23:24:14.772993436 +0000
Change: 2018-01-22 23:24:14.772993436 +0000
 Birth: -
```

The mountpoints are created before `setup_private_users` is called, 
so they are not created in the context of the container usernamespace.
The solution would be either to call `unshare` earlier or to fix uids/gids for the mountpoints after mount().

**Comment by asbachb** [comment] 2019-01-06 20:04
I wonder if this is still an issue in a recent systemd versions?!

**Comment by vvrein** [comment] 2020-03-30 09:01
@asbachb still sometimes facing this issue.
I was starting container sometimes in privileged mode, sometimes not, e.g. 
```
systemd-nspawn --network-bridge=mbr0 -bUD /var/lib/machines/arch1
....
systemd-nspawn --network-bridge=mbr0 -bD /var/lib/machines/arch1
```
And at some point, container starts to show errors like

```
[FAILED] Failed to start Home Area Manager.
See 'systemctl status systemd-homed.service' for details.
[FAILED] Failed to start Login Service.
See 'systemctl status systemd-logind.service' for details.
[  OK  ] Stopped Login Service.
         Starting Update UTMP about System Boot/Shutdown...
[  OK  ] Finished Permit User Sessions.
[FAILED] Failed to start Update UTMP about System Boot/Shutdown.
See 'systemctl status systemd-update-utmp.service' for details.
[  OK  ] Started Console Getty.
[  OK  ] Reached target Login Prompts.
         Starting Login Service...
[FAILED] Failed to start Login Service.
See 'systemctl status systemd-logind.service' for details.
[  OK  ] Stopped Login Service.
         Starting Update UTMP about System Boot/Shutdown...
[FAILED] Failed to start Update UTMP about System Boot/Shutdown.
See 'systemctl status systemd-update-utmp.service' for details.
         Starting Login Service...
[FAILED] Failed to start Login Service.
See 'systemctl status systemd-logind.service' for details.
[  OK  ] Stopped Login Service.
         Starting Update UTMP about System Boot/Shutdown...
[FAILED] Failed to start Update UTMP about System Boot/Shutdown.
See 'systemctl status systemd-update-utmp.service' for details.
         Starting Login Service...
[FAILED] Failed to start Login Service.
See 'systemctl status systemd-logind.service' for details.
[  OK  ] Stopped Login Service.
         Starting Update UTMP about System Boot/Shutdown...
[FAILED] Failed to start Update UTMP about System Boot/Shutdown.
See 'systemctl status systemd-update-utmp.service' for details.
         Starting Login Service...
[FAILED] Failed to start Login Service.
See 'systemctl status systemd-logind.service' for details.
[  OK  ] Stopped Login Service.
[FAILED] Failed to start Update UTMP about System Boot/Shutdown.
See 'systemctl status systemd-update-utmp.service' for details.
[FAILED] Failed to start Login Service.
See 'systemctl status systemd-logind.service' for details.
```

As fix for this I manually set `--private-users=1354956800:65536 --private-users-chown`, and shift for `+65536` in case of container boot-up fails.

**Comment by greyltc** [comment] 2021-02-13 20:47
I just saw this today on Arch with systemd 247.3
when trying to run `sudo machinectl start newsys`

**Comment by LiangPingPiJiu** [comment] 2023-02-19 18:12
I had the same issue after mixed ownership in the container as mentioned above.

> @vvrein 
> As fix for this I manually set `--private-users=1354956800:65536 --private-users-chown`, and shift for `+65536` in case of container boot-up fails.
> 
> After such shift, I suppose, nspawn is re-chown'ing whole fs tree, and problem goes gone :)

Thank you, this workaround worked as well for me :)
Namespace begin was automatically choosen to 527237120 before, so I just added 65536 and startet with 527302656:
`systemd-nspawn -b --machine XXX --private-users=527302656:65536 --private-users-chown`
After that all ownership was correctly fixed and I could start normally with `systemd-nspawn -bU --machine` XXX or `systemctl` again.

I use systemd 247 (247.3-7+deb11u1) on Debian 11 (Bullseye).

**Comment by poettering** [comment] 2023-04-03 14:08
I am pretty sure this works these days. Let's close. if this is reproducible with a prpoerly chown()ed tree, then feel free to reopen.

**Closed as completed by poettering** 2023-04-03 14:08 UTC
Labels: bug 🐛, nspawn
