### ISSUE TITLE
localectl: hardcoded /usr/lib/locale/locale-archive path

### ISSUE THREAD

**Issue by eimiar** [systemd/systemd#17544] opened 2020-11-07 12:01 UTC
**systemd version the issue has been seen with**
 > systemd 246 (246)
> +PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL -XZ +LZ4 +ZSTD +SECCOMP +BLKID -ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified

**Used distribution**
 > Gentoo.

**Linux kernel version used** (`uname -a`)
 > Linux 5.9.6

**CPU architecture issue was seen on**
 > Both aarch64 and amd64.

**Expected behaviour you didn't see**
 > Output.

**Unexpected behaviour you saw**
 > No output.

**Steps to reproduce the problem**
 > Just execute command `localectl list-locales`.

Running the command `localectl list-locales` won't give any output if locale-archive is located in a path different than `/usr/lib/locale/locale-archive`.
`src/basic/locale-util.c` shows that the path is hardcoded in lines **104** and **166**.
Creating a symbolic link to the correct archive location (in my case is `/usr/lib64/locale/locale-archive`) might be a temporary solution.
A better solution would be either automate the path retrieval from libc or allow a config to set up this path.

**Comment by poettering** [comment] 2020-11-09 15:42
[Canned reply follows] When submitting a GitHub issue, please fill in the submission form you find in the issue creation page, i.e. provide the requested details, such as distribution and systemd versions. We ask you these details to keep frustration at a minimum, both for us, and for you. If you don't provide this information it makes things needlessly difficult to help you.

Also, please keep in mind: this is a bug and feature request tracker only. If you have a support question, i.e. wonder how to use a feature, or can't figure out how to do something best, please use a different forum, such as the systemd mailing list. Also, do not file bug reports unless you can reproduce the issue with one of the two most recently released *upstream* version of systemd. For everything older, please contact your downstream distribution instead.

Thank you for understanding!

**Comment by poettering** [comment] 2020-11-09 15:42
Also, what are locale files doing in lib64? Fix your distro? Locale is not arch-dependent, they should not be in lib64

**Comment by eimiar** [comment] 2020-11-09 16:04
I have edited the main post including the form in the issue creation page.


> 
> 
> Also, what are locale files doing in lib64? Fix your distro? Locale is not arch-dependent, they should not be in lib64

I don't know. I'm just reporting this behaviour. You suggest locale is not arch-dependent, where can I verify that?

**Comment by poettering** [comment] 2020-11-09 16:26
Well, no major distro I know of puts them in lib64, for starters, even though many of them support multilib...

Which distro is this?

**Comment by eimiar** [comment] 2020-11-09 16:28
Gentoo.

**Comment by floppym** [comment] 2020-11-09 16:29
Gentoo installs a symlink from /usr/lib/locale to /usr/lib64/locale.

I do not know why the files are installed in /usr/lib64/locale, but your system appears to be missing a symlink.

**Comment by floppym** [comment] 2020-11-09 16:35
> I do not know why the files are installed in /usr/lib64/locale

It looks like libc looks in libdir (abi-specific) for locale-archive. Not sure if this is Gentoo-specific or not.

```
% file /lib64/libc-2.32.so
/lib64/libc-2.32.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, stripped
% strings /lib64/libc-2.32.so | grep locale-archive
/usr/lib64/locale/locale-archive

% file /lib/libc-2.32.so
/lib/libc-2.32.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 3.2.0, stripped
% strings /lib/libc-2.32.so | grep locale-archive
/usr/lib/locale/locale-archive
```

**Comment by eimiar** [comment] 2020-11-09 16:54
> It looks like libc looks in libdir (abi-specific) for locale-archive. Not sure if this is Gentoo-specific or not.

I confirm. Same output with my system, but I don't have a /lib/libc-x.yy.so
```
# file /lib64/libc-2.31.so
/lib64/libc-2.31.so: ELF 64-bit LSB shared object, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, stripped
# strings /lib64/libc-2.31.so | grep locale-archive
/usr/lib64/locale/locale-archive
# file /lib/libc-2.31.so
/lib/libc-2.31.so: cannot open `/lib/libc-2.31.so' (No such file or directory)
```

**Comment by floppym** [comment] 2020-11-09 16:56
I see; you are running a no-multilib system, which causes the /usr/lib/locale symlink to be missing.

Please file a bug at https://bugs.gentoo.org/.

**Comment by poettering** [comment] 2020-11-09 17:04
On Gentoo locale archives are arch dependent? That#s so weird. Sounds like a bug in gentoo.

Either way, let's close this. Gentoo's setup really makes no sense, and I figure the fact they install a symlink acknowledges they know that.

**Closed as completed by poettering** 2020-11-09 17:04 UTC

**Comment by floppym** [comment] 2020-11-09 17:06
Yes, this is a Gentoo bug.

**Comment by floppym** [comment] 2020-11-09 17:11
For reference: https://bugs.gentoo.org/753740
