### ISSUE TITLE
systemd-networkd ignores .network file for NetDev: Network File: n/a

### ISSUE THREAD

**Issue by beremour** [systemd/systemd#24259] opened 2022-08-09 11:31 UTC
I am trying to move from NetworkManager to systemd-networkd. I can't assign IP address to VLAN interface, because corresponding .network file is ignored.  NetDev device status gives "Network File: n/a"

/etc/systemd/network/07-eth1.link
```
[Match]
MACAddress=00:50:56:29:9c:98
[Link]
Name=eth1
```
/etc/systemd/network/07-eth1.network
```
[Match]
Name=eth1

[Network]
VLAN=1-207
LinkLocalAddressing=no
LLDP=no
EmitLLDP=no
IPv6AcceptRA=no
IPv6SendRA=no
```
/etc/systemd/network/10-eth1.207.netdev
```
[NetDev]
Name=1-207
Kind=vlan

[VLAN]
Protocol=802.1q
Id=207
GVRP=False
MVRP=False
```
/etc/systemd/network/10-eth1.207.network
```
[Match]
Name=1-207

[Network]
LinkLocalAddressing=ipv4
MulticastDNS=true
Address=10.0.1.207/24
```

networkctl status 1-207
```
                     Link File: n/a
                  Network File: n/a
                          Type: vlan
                         State: off (pending)
                  Online state: unknown
              Hardware Address: 00:50:56:29:9c:98 (VMware, Inc.)
                           MTU: 1500 (max: 65535)
                         QDisc: noop
  IPv6 Address Generation Mode: eui64
                       VLan Id: 207
      Number of Queues (Tx/Rx): 1/1
              Auto negotiation: no
                         Speed: 10Gbps
                        Duplex: full
                          Port: tp
             Activation Policy: up
           Required For Online: yes

Aug 09 14:08:17 fenode.local systemd-udevd[1137]: 1-207: Failed to rename network interface 5 from '1-207' to 'eth1': File exists
Aug 09 14:08:17 fenode.local systemd-udevd[1137]: 1-207: Failed to process device, ignoring: File exists
Aug 09 14:08:17 fenode.local systemd-networkd[1794]: 1-207: netdev has index 5
Aug 09 14:08:17 fenode.local systemd-networkd[1794]: 1-207: netdev ready
Aug 09 14:08:17 fenode.local systemd-networkd[1794]: 1-207: Saved new link: ifindex=5, iftype=ETHER(1), kind=vlan
Aug 09 14:08:17 fenode.local systemd-networkd[1794]: 1-207: Saved original MTU 1500 (min: 0, max: 65535)
Aug 09 14:08:17 fenode.local systemd-networkd[1794]: 1-207: Saved hardware address: 00:50:56:29:9c:98
Aug 09 14:08:17 fenode.local systemd-networkd[1794]: 1-207: Failed to manage link by its new hardware address, ignoring: File exists
Aug 09 14:08:17 fenode.local systemd-networkd[1794]: 1-207: Flags change: +MULTICAST +BROADCAST
Aug 09 14:08:17 fenode.local systemd-networkd[1794]: 1-207: Interface is being renamed, pending initialization.
```

**Comment by yuwata** [comment] 2022-08-09 12:33
07-eth1.link file also matches with the clan interface, as it has the same MAC address as one for eth1. Try to add other settings in the [Match] section, e.g. Type=ether.

Also, you should not use ethX (or any other names used by kernel), as it easily causes conflicts.

In short, this is not a bug, but user's misconfiguration. Closing.

**Closed as completed by yuwata** 2022-08-09 12:33 UTC
Labels: network, not-a-bug

**Comment by beremour** [comment] 2022-08-09 16:53
VLAN interface inherits MAC address from it's parent eth1 interface. Is it a problem ? I think it is not.

**Comment by beremour** [comment] 2022-08-09 16:58
Can you explain how 07-eth1.link matches any other interface ?

**Comment by yuwata** [comment] 2022-08-09 17:01
As you said, both physical and vlan interfaces has the same MAC address, and the .link file only contains MACAddress= setting. Thus, the file will be applied to the both interfaces.

**Comment by beremour** [comment] 2022-08-09 17:11
VLAN interface gets MAC address becase it was binded to interface eth1 via /etc/systemd/network/07-eth1.network. Config files 10-eth1.207.netdev and 10-eth1.207.network has only name matching. I stil have no idea why  10-eth1.207.network is ignored.

**Comment by beremour** [comment] 2022-08-09 17:11
Type ether dosen't help

**Comment by yuwata** [comment] 2022-08-09 17:26
Before networkd try to configure an interface, udevd must finish to configure the interface. As you can see, the udevd fail to rename the vlan interface. Hence, networkd cannot start to configure the interface.

**Comment by yuwata** [comment] 2022-08-09 17:29
> Type ether dosen't help

I guess you misunderstand my comment. I mean you need to modify the .link file something like the following.
```
[Match]
MACAddress=00:50:56:29:9c:98
Type=ether
[Link]
Name=eth1
```
Again, please please change `Name=eth1`.

**Comment by beremour** [comment] 2022-08-09 17:46
Ah! Thank you very much "Type=ethe" in .link file helped! Will also follow you advice about changing name ethX.
