### ISSUE TITLE
Cannot apply persistent-net udev rules without a reboot

### ISSUE THREAD

**Issue by BPetitZMP** [systemd/systemd#17594] opened 2020-11-13 06:25 UTC
**systemd version the issue has been seen with**
 > 245.4-4ubuntu3.3

**Used distribution**
 > Ubuntu 20.04.1 LTS

**Linux kernel version used** (`uname -a`)
 > Linux 16-Z0043 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86-64

**Expected behaviour you didn't see**
 > After placing a persistent name rule in /etc/udev/rules.d and running `sudo udevadm control --reload-rules && udevadm trigger`, expected to see the newly named interface with `ifconfig -a` without the need to reboot the system.

**Unexpected behaviour you saw**
 > The previous name was in use until rebooting the PC. Only after reboot the name defined in the .rules file is applied.

**Steps to reproduce the problem**
 > Place a 70-persistent-net.rules file in /etc/udev/rules.d/ to attribute a name to a network interface then run `sudo udevadm control --reload-rules && udevadm trigger` and check if the new interface is in the list given by `ifconfig -a`.

For reference, my file content is:
`SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="78:d0:04:2a:61:c4", KERNEL=="enp*", NAME="mylan0"`

**Comment by yuwata** [comment] 2020-11-13 06:40
Please try `udevadm trigger --action=add`, otherwise the rule is not applied to the interface, as you set `ACTION=="add"`.

**Comment by BPetitZMP** [comment] 2020-11-13 06:53
Thank you for your very fast answer, I tried your suggestion, but it did not seem to solve my issue.
I tried:
`sudo udevadm control --reload-rules && udevadm trigger --action=add`
and
`udevadm trigger --action=add`
as well as
`sudo udevadm trigger --action=add`
and
`sudo udevadm control --reload-rules && sudo udevadm trigger --action=add`
in case there was any permission issues, but the result stay the same on my system.

**Comment by yuwata** [comment] 2020-11-13 07:03
I guess `NamePolicy=` setting contains `keep` in the corresponding .link file (e.g. /usr/lib/systemd/network/99-default.link).
Please try to create e.g., /etc/systemd/network/99-default.link without `keep` in `NamePolicy=` setting.
You can find which .link file is applied to the interface by `udevadm info /sys/class/net/INTERFACE_NAME`. or `networkctl status INTERFACE_NAME`.

**Comment by yuwata** [comment] 2020-11-13 07:04
Please also see https://www.freedesktop.org/software/systemd/man/systemd.link.html#NamePolicy=.

**Comment by BPetitZMP** [comment] 2020-11-13 08:15
Your guess was correct indeed, the command you recommended me gave this result:
```
networkctl status enp0s31f6
WARNING: systemd-networkd is not running, output will be incomplete.

Failed to query link bit rates: Unit dbus-org.freedesktop.network1.service not found.
● 7: enp0s31f6                                                     
             Link File: /etc/systemd/network/99-default.link       
          Network File: n/a                                        
                  Type: ether                                      
                 State: n/a (unmanaged)                            
                  Path: pci-0000:00:1f.6                           
                Driver: e1000e                                     
                Vendor: Intel Corporation                          
                 Model: Ethernet Connection (7) I219-LM            
            HW Address: 78:d0:04:2a:61:c4 (Neousys Technology Inc.)
                   MTU: 1500 (min: 68, max: 9000)                  
  Queue Length (Tx/Rx): 1/1                                        
      Auto negotiation: yes                                        
                 Speed: 1Gbps                                      
                Duplex: full                                       
                  Port: tp                                         
               Address: 192.168.10.27                              
                        fe80::b7ed:bc7a:4b94:41b7                  
               Gateway: 192.168.10.1 (YAMAHA CORPORATION)          
```
With the link file `/etc/systemd/network/99-default.link` containing `keep` in the `NamePolicy=` as follows for reference:
```
#  SPDX-License-Identifier: LGPL-2.1+
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Match]
OriginalName=*

[Link]
NamePolicy=keep kernel database onboard slot path
AlternativeNamesPolicy=database onboard slot path
MACAddressPolicy=persistent
```
I then created a `/etc/systemd/network/99-default.link` file with the same content but omitting the `keep` value as you suggested:
```
#  SPDX-License-Identifier: LGPL-2.1+
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Match]
OriginalName=*

[Link]
NamePolicy=kernel database onboard slot path
AlternativeNamesPolicy=database onboard slot path
MACAddressPolicy=persistent
```
At this point I was not sure how to reload the network link configuration without reboot, so I:
- deleted my .rules file,
- rebooted the PC,
- placed the .rules file again in `/etc/udev/rules.d/`,
- ran `sudo udevadm control --reload-rules && sudo udevadm trigger --action=add`

Unfortunately I still could not see my custom interface name with `ifconfig -a`.

Interestingly though running `networkctl status enp0s31f6` command again after all that I could see an error message:
```
enp0s31f6: Failed to rename network interface 7 from 'enp0s31f6' to 'mylan0': Device or resource busy
```

What would be the next action to try to try to make the renaming active without reboot?
Also, as a side note, how can I make the custom .link configuration active without rebooting the PC?

**Comment by yuwata** [comment] 2020-11-13 08:31
> I was not sure how to reload the network link configuration without reboot

`udevadm control --reload` should also reload .link files.

> enp0s31f6: Failed to rename network interface 7 from 'enp0s31f6' to 'mylan0': Device or resource busy

Seems that the interface is already up. That is, some network management daemon like networkd, NetworkManager or ifupdown already activate the interface.

> SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="78:d0:04:2a:61:c4", KERNEL=="enp*", NAME="mylan0"

I noticed that the rule sounds strange, as it requires once the interface renamed from `ethX` to `enpYYY`, and then after that renamed to `mylan0` when `udevadm trigger` is invoked. How about to create a .link file something like the following instead of the rule?
```
# /etc/systemd/network/10-mylan0.link
[Match]
MACAddress=78:d0:04:2a:61:c4

[Link]
Name=mylan0
AlternativeNamesPolicy=database onboard slot path
MACAddressPolicy=persistent
```

**Comment by BPetitZMP** [comment] 2020-11-13 09:11
It seems that my system uses NetworkManager indeed.
Thank you for your suggestion, it seems cleaner indeed to use a `.link` file to configure the interface name.

After deleting the `.rules` file and creating the `10-mylan0.link` file, I now tried to:
- stop NetworkManager service, 
- run `sudo udevadm control --reload`,
- and start the NetworkManager service

However the result is still the same, my interface is unchanged when I check it.
At this point is it possible it is a problem from NetworkManager?

The steps in my first post used to work for me in Ubuntu 18.04, however I cannot trace back which version of systemd/udev and NetworkManager I was using at the time.

**Comment by yuwata** [comment] 2020-11-13 09:22
.link files are used by udevd. So, you need to trigger the uevent by `udevadm trigger --action=add /sys/class/net/INTERFACE_NAME`, or reboot the system.

**Comment by yuwata** [comment] 2020-11-13 09:23
And, as I said before, before triggering uevent, you need to down the interface `ip link set INTERFACE_NAME down`.

**Comment by yuwata** [comment] 2020-11-13 09:26
(By the way, here is a bug or RFE tracker, and not a support forum. Your issue seems not a bug in systemd. Let's close this at least tentatively. Of course, if you think this is caused by a bug in systemd, then feel free to ask to reopen this page.)

**Closed as completed by yuwata** 2020-11-13 09:26 UTC
Labels: udev, not-a-bug

**Comment by BPetitZMP** [comment] 2020-11-13 09:44
Thank you for the suggestion of using `ip link set` to down the currently used interface, this time it worked on my system.

I am sorry if this felt like a support session on your side, I thought I might have found a bug in udev because as I wrote before the steps detailed in my first post did work in the past on a Ubuntu 18.04 (without needing to down the interface being used) and did not work anymore.

If this is not a bug, then it is ok for me to close the issue.

**Comment by yuwata** [comment] 2020-11-13 09:48
> this time it worked on my system.

Yey! I am happy to hear that.

> I am sorry if this felt like a support session on your side

No problem. Feel free to post anything if you think you find a bug.
