### ISSUE TITLE
Service as User Group no longer has write access to /etc

### ISSUE THREAD

**Issue by severach** [systemd/systemd#7906] opened 2018-01-16 20:22 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

````
# pacman -Q systemd
systemd 236.81-1
````

### Used distribution

Arch

### In case of bug report: Expected behaviour you didn't see

````
[Service]
...
User=nobody
Group=nobody
````

I no longer have read-write access to a folder in /etc when running as user.

### In case of bug report: Unexpected behaviour you saw

Write to /etc is blocked. Read access to /etc is not fully functional.

### In case of bug report: Steps to reproduce the problem

````
su
mkdir /etc/sds-test-folder
echo "Success" > /etc/sds-test-folder/touch
chown -R root:nobody /etc/sds-test-folder
chmod 775 /etc/sds-test-folder
ls -l /etc/sds-test-folder/*
#-rw-r--r-- 1 root nobody 8 Jan 16 15:16 /etc/sds-test-folder/touch
cat > /usr/lib/systemd/system/sds-test-folder.service << EOF
[Unit]
Description=Test access to /etc
After=network-online.target

[Service]
Type=oneshot
# Enable one of the following
ExecStart=/usr/bin/touch /etc/sds-test-folder/config
#ExecStart=/usr/bin/cat /etc/sds-test-folder/touch
User=nobody
Group=nobody
EOF
systemctl daemon-reload && systemctl start sds-test-folder.service; systemctl status sds-test-folder.service
````
Jan 16 14:59:21 gq systemd[1]: Starting Test access to /etc...
Jan 16 14:59:21 gq touch[21206]: /usr/bin/touch: cannot touch '/etc/sds-test-folder/config': Permission denied

Bug 1: With ExecStart=cat, why does "Success" not show in the log until I change the service to run as root after which all the formerly invisible "Success" now show up.

Bug 2: With ExecStart=touch, how do I get write access to the folder in /etc when run as user?

````
# Cleanup
su
rm -rf /etc/sds-test-folder/
rm /usr/lib/systemd/system/sds-test-folder.service
systemctl daemon-reload
````

**Comment by yuwata** [comment] 2018-01-16 20:31
Seems duplicate of #7717.

**Comment by yuwata** [comment] 2018-01-16 20:38
Could you give me several information: 
- passwd and group entries in `/etc/nsswitch.conf`
- `id nobody`
- `cat /usr/lib/sysusers.d/basic.conf | grep Nobody`

**Comment by yuwata** [comment] 2018-01-16 20:50
Yeah, systemd-236.81-1 is not built with correct `-Dnobody-user=foovar -Dnobody-group=foovar` option. See
https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/system
Please report this to the distribution maintainer. @eworm-de ?

**Closed as completed by yuwata** 2018-01-16 20:50 UTC
Labels: duplicate

**Comment by severach** [comment] 2018-01-16 21:00
https://bugs.archlinux.org/task/56828

**Comment by severach** [comment] 2018-01-18 20:35
This is not a satisfactory answer. This only covers one user. There are many users that need write access to etc.

How do I restore write access to /etc for a user, preferably for a single folder?

Moving to /var/lib isn't the answer. Eventually that will be locked.

**Comment by yuwata** [comment] 2018-01-18 23:33
The user nobody on your system is wrongly configured. There are several choises.
1. Rebuild systemd with suitable nobody configuration.
2. Use DynamicUser=yes instead of User= and Group=.
3. Create (if necessary) a user and group, and use it.
