### ISSUE TITLE
journalctl, check for unit arg to exist, before running

### ISSUE THREAD

**Issue by mator** [systemd/systemd#572] opened 2015-07-13 08:25 UTC
journalctl doesn't check for unit if it exists or not, just silently runs. For example, with non existent unit glusterfsx:

[root@node01 ~]# rpm -q systemd
systemd-219-18.fc22.x86_64
[root@node01 ~]# systemctl list-units | grep glusterfsx
[root@node01 ~]# 
[root@node01 ~]# journalctl -u glusterfsx
-- Logs begin at Wed 2013-07-03 13:24:48 MSK, end at Mon 2015-07-13 11:22:00 MSK. --
[root@node01 ~]# echo $?
1

it should return more visible error, that there's no such unit glusterfsx.
Thanks.

**Comment by arvidjaar** [comment] 2015-07-13 11:58
Why it should be an error? Unit may be deleted or journal files could be from completely another system. Having no unit with this name on system _now_ does not mean this unit is not present in journal files we examine.

**Comment by mator** [comment] 2015-07-13 12:16
I don't state that it should be error or not. It is de-facto error right now, just looking at return code. I just say, that it should be more "visible" error (human friendly), besides of setting return code only. Thanks.

**Comment by poettering** [comment] 2015-07-24 01:29
If you apply filters then it might happen that the resulting set of log messages is empty, and that's expected, and not an error. As such, the fact that the journalctl command above returned one is actually a bug, but as it happens it is fixed with #695, which will ensure the call results in a 0 exit code.

As soon as #695 I think this issue may be closed too, as the intended behaviour is then back in place.

**Comment by zonque** [comment] 2015-07-24 10:06
#695 is merged now, closing.

**Closed as completed by zonque** 2015-07-24 10:06 UTC
Labels: journal
