### ISSUE TITLE
systemd 243 causes sddm to trigger a GPU fault on startup and hang

### ISSUE THREAD

**Issue by Plagman** [systemd/systemd#13562] opened 2019-09-15 00:25 UTC
After upgrading an arch system from 242.84 to 243.0, sddm isn't properly starting up anymore.

Instead, the system remains at the text VT, and the following GPU error spew can be found in the kernel log:

```
[    9.707047] [drm] Fence fallback timer expired on ring gfx
[   10.213664] [drm] Fence fallback timer expired on ring comp_1.0.0
[   10.720337] [drm] Fence fallback timer expired on ring comp_1.1.0
[   11.226696] [drm] Fence fallback timer expired on ring comp_1.2.0
[   11.733751] [drm] Fence fallback timer expired on ring comp_1.3.0
```

This is on a Vega 20 board, with otherwise up-to-date amdgpu and Mesa bits.

After the problem occurs, the normal boot/login sequence can be resumed by restarting the sddm unit, at which point no further abnormal behavior is observed (so far - other than all our input udev rules breaking).

It's 100% reproducible by flipping between these two versions.

**Comment by ivanbardov** [comment] 2019-09-15 18:33
I guess, that's about the same issue we experienced here https://github.com/systemd/systemd/issues/13296

**Comment by keszybz** [comment] 2019-09-16 12:44
Duplicate of #13296.

**Closed as completed by keszybz** 2019-09-16 12:44 UTC
