### ISSUE TITLE
systemd-shutdow - Failed to parse /proc/self/mountinfo:1 on armv7hl

### ISSUE THREAD

**Issue by kwizart** [systemd/systemd#7623] opened 2017-12-13 08:02 UTC
### Submission type
 - Bug report

When using shutdown on the device, I saw theses failure on console.

[  466.683866] systemd-shutdown[1]: Sending SIGTERM to remaining processes...
[  466.705067] systemd-journald[400]: Received SIGTERM from PID 1 (systemd-shutdow).
[  467.167407] systemd-shutdown[1]: Sending SIGKILL to remaining processes...
[  467.188249] systemd-shutdown[1]: Unmounting file systems.
[  467.194078] systemd-shutdown[1]: Failed to parse /proc/self/mountinfo:1.
[  467.201007] systemd-shutdown[1]: Failed to parse /proc/self/mountinfo:2.
[  467.207765] systemd-shutdown[1]: Failed to parse /proc/self/mountinfo:3.
[  467.214578] systemd-shutdown[1]: Failed to parse /proc/self/mountinfo:4.
[  467.221333] systemd-shutdown[1]: Failed to parse /proc/self/mountinfo:5.
[  467.228174] systemd-shutdown[1]: Failed to parse /proc/self/mountinfo:6.
[  467.234939] systemd-shutdown[1]: Failed to parse /proc/self/mountinfo:7.
[  467.307504] reboot: Power down

### systemd version the issue has been seen with

systemd-234-9.fc27.armv7hl

### Used distribution

Fedora 27+ armv7hl

### In case of bug report: Expected behaviour you didn't see

Clean shutdown without failure

### In case of bug report: Unexpected behaviour you saw

Failure message are output.

From a running trimslice (tegra20 cortex-a9), using fedora 27 minimal image. Here the output of mountinfo:
cat /proc/self/mountinfo
18 61 0:18 / /sys rw,nosuid,nodev,noexec,relatime shared:2 - sysfs sysfs rw,seclabel
19 61 0:4 / /proc rw,nosuid,nodev,noexec,relatime shared:23 - proc proc rw
20 61 0:6 / /dev rw,nosuid shared:19 - devtmpfs devtmpfs rw,seclabel,size=469792k,nr_inodes=117448,mode=755
21 18 0:7 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime shared:3 - securityfs securityfs rw
22 20 0:19 / /dev/shm rw,nosuid,nodev shared:20 - tmpfs tmpfs rw,seclabel
23 20 0:20 / /dev/pts rw,nosuid,noexec,relatime shared:21 - devpts devpts rw,seclabel,gid=5,mode=620,ptmxmode=000
24 61 0:21 / /run rw,nosuid,nodev shared:22 - tmpfs tmpfs rw,seclabel,mode=755
25 18 0:22 / /sys/fs/cgroup ro,nosuid,nodev,noexec shared:4 - tmpfs tmpfs ro,seclabel,mode=755
26 25 0:23 / /sys/fs/cgroup/unified rw,nosuid,nodev,noexec,relatime shared:5 - cgroup2 cgroup rw,seclabel
27 25 0:24 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:6 - cgroup cgroup rw,seclabel,xattr,name=systemd
28 18 0:25 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime shared:16 - pstore pstore rw,seclabel
29 25 0:26 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:7 - cgroup cgroup rw,seclabel,cpu,cpuacct
30 25 0:27 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime shared:8 - cgroup cgroup rw,seclabel,pids
31 25 0:28 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime shared:9 - cgroup cgroup rw,seclabel,net_cls,net_prio
32 25 0:29 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime shared:10 - cgroup cgroup rw,seclabel,cpuset
33 25 0:30 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime shared:11 - cgroup cgroup rw,seclabel,perf_event
34 25 0:31 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime shared:12 - cgroup cgroup rw,seclabel,memory
35 25 0:32 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime shared:13 - cgroup cgroup rw,seclabel,freezer
36 25 0:33 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime shared:14 - cgroup cgroup rw,seclabel,devices
37 25 0:34 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime shared:15 - cgroup cgroup rw,seclabel,blkio
59 18 0:35 / /sys/kernel/config rw,relatime shared:17 - configfs configfs rw
61 0 8:3 / / rw,noatime shared:1 - ext4 /dev/sda3 rw,seclabel,data=ordered
38 18 0:17 / /sys/fs/selinux rw,relatime shared:18 - selinuxfs selinuxfs rw
39 18 0:8 / /sys/kernel/debug rw,relatime shared:24 - debugfs debugfs rw,seclabel
40 19 0:36 / /proc/sys/fs/binfmt_misc rw,relatime shared:25 - autofs systemd-1 rw,fd=40,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=13502
41 20 0:16 / /dev/mqueue rw,relatime shared:26 - mqueue mqueue rw,seclabel
72 61 8:1 / /boot rw,noatime shared:27 - ext3 /dev/sda1 rw,seclabel,data=ordered
141 24 0:38 / /run/user/0 rw,nosuid,nodev,relatime shared:93 - tmpfs tmpfs rw,seclabel,size=102412k,mode=700

### In case of bug report: Steps to reproduce the problem

Shutdown on armhfp device.

**Comment by yuwata** [comment] 2017-12-13 09:34
I think this is duplicate of #6796 and already fixed by 3d4ec01269244c2d35a781abf748ea9ba57666e2 (#6806).

**Closed as completed** 2017-12-13 09:35 UTC
Labels: duplicate
