### ISSUE TITLE
systemctl list-units --all doesn't show all loaded units

### ISSUE THREAD

**Issue by RomanTi** [systemd/systemd#5063] opened 2017-01-11 15:18 UTC
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 231

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Ubuntu 16.10

### In case of bug report: Expected behaviour you didn't see

> systemctl list-units --all --type service

doesn't show all the loaded units (as per man page). It shows only enabled OR active OR (enabled AND active) units. But if the unit is loaded, but inactive AND disabled then it doesn't show it.

### In case of bug report: Steps to reproduce the problem

example with ssh service:

> sudo apt-get install openssh-server
> sudo systemctl disable ssh
> sudo systemctl stop ssh
> sudo systemctl list-units --type service --all | grep ssh
> sudo systemctl status ssh

**Comment by poettering** [comment] 2017-01-12 09:27
systemd will implicitly load units as necessary. If a unit is not loaded and you issue "systemctl status", "systemctl start", "systemctl restart", … on it, it will be loaded temporarily, and possibly unloaded quickly after the operation is completed if there's no reason to keep it in memory thereafter.

"systemctl status" is hence *not* useful for determining if something is loaded or not, as anything it shows will be loaded simply triggered by the fact of showing it.

"systemclt list-units -all" shows only loaded units, without exceptions.

Closing, as this appears to be an issue based on a misunderstanding about the behaviour of "systemctl status".

**Closed as completed by poettering** 2017-01-12 09:27 UTC
Labels: systemctl, not-a-bug

**Comment by markstos** [comment] 2017-01-12 11:36
@poettering Thank for the prompt feedback.

I should be re-opened as a documentation issue if not a bug issue. I've just recently read the docs for `systemctl status` and it's absolutely *not* documented that it loads units on demand, declares them as "loaded" and then unloads them.    Currently #4950 is actively working on improving the anemic docs on explaining the `systemctl status` output. 

As someone who helps a number of people with `systemd` questions on StackExchange, it's clear that the output of this command which is intended to easy to understand is currently not. The twist that "loaded" doesn't always mean a that unit is normally loaded certainly seems worth mentioning! Or for that matter: it sounds like the "Loaded" status as reported by `systemctl status` is fairly useless if it's always going to report "loaded" and therefore should simply be removed from the output to avoid the appearance of providing useful information. One reasonable assumes that if the "Loaded:" status is reported, that it is reported because it would be both accurate is useful. Always reporting "loaded" doesn't seem useful.

(And frankly, if the status is "loaded-only-to-show-you-the-status", it seems more useful to just say it's unloaded).

**Comment by keszybz** [comment] 2017-01-12 14:49
It *used* to say "Loaded: not-found" before (when the unit could not be found), but this was confusing to users and `systemctl` was changed to just display nothing in the straightforward case of a missing unit.

But it is still possible to encounter different states. If a unit is masked, you'll see "Loaded: masked".
If systemd has state for a unit that was subsequently deleted, you'll also see "Loaded: not-found":
```
# systemctl start foobar
# rm /usr/lib/systemd/system/foobar.service
# systemctl status foobar
● foobar.service
   Loaded: not-found (Reason: No such file or directory)
   ...
```

Improvements to docs are certainly welcome, but please note that current behaviour of `systemctl list-unit --all` is as intended.

**Comment by mbigras** [comment] 2019-08-06 01:10
Is it possible to configure a service unit to stay loaded after it's stopped?

From reading:

https://github.com/coreos/go-systemd/blob/fd7a80b32e1fc73e890fde45604ed5009dc817a3/dbus/methods.go#L297-L302

```
// ListUnits returns an array with all currently loaded units. Note that
// units may be known by multiple names at the same time, and hence there might
// be more unit names loaded than actual units behind them.
// Also note that a unit is only loaded if it is active and/or enabled.
// Units that are both disabled and inactive will thus not be returned.
func (c *Conn) ListUnits() ([]UnitStatus, error) {
	return c.listUnitsInternal(c.sysobj.Call("org.freedesktop.systemd1.Manager.ListUnits", 0).Store)
}

```

I discovered if I enable the unit then the go-systemd ListUnits method will still be able to discover the state of my unit when I stop it with `systemctl stop foo.service`. However, I don't want my unit to be enabled because foo.service has cross-machine dependencies and doesn't benefit from being restarted on machine reboot. I do want the unit to stay loaded so my prometheus node exporter with systemd collector will still discover the foo.service state is "inactive" when I stop it.

So instead of:

```
# /etc/systemd/system/foo.service
[Service]
ExecStart=/usr/bin/python3 -m http.server 3001

[Install]
WantedBy=multi-user.target
```

I'm looking for something like:

```
# /etc/systemd/system/foo.service
[Service]
ExecStart=/usr/bin/python3 -m http.server 3001
RemainLoaded=yes
```

**Comment by keszybz** [comment] 2019-08-06 06:29
A service will stay loaded if it is wanted/required/etc by something, or if it failed, or if it is running, or if it has been started and has RemainAfterExit=true. Otherwise, it'll be garbage collected.

> I do want the unit to stay loaded so my prometheus node exporter with systemd collector will still discover the foo.service state is "inactive" when I stop it.

You'll have to find a solution in the exporter code to properly discover units which are not currently refrenced.

**Comment by poettering** [comment] 2019-08-06 07:52
Use RefUnit() via the bus to continuously reference a unit. In that case it stays loaded until you call UnrefUnit(), or disconnect from the bus, and no other reason is in place to keep it loaded. RefUnit() is available to privileged clients only and since v232 (i.e. ~2016)

That all said, please ask questions like that on the ML, not in this bug tracker. It's not a support forum but a bug tracker. Thank you for understanding.
