### ISSUE TITLE
libsystemd GetUnitByPID, causing the system to crash

### ISSUE THREAD

**Issue by supertomato696** [systemd/systemd#34104] opened 2024-08-23 03:01 UTC
### systemd version the issue has been seen with

systemd-254.7-1.fc39.x86_64

### Used distribution

ubuntu 22.04

### Linux kernel version used

6.5.0-1024-azure

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

```
 ret = sd_bus_call_method(bus,
                                     "org.freedesktop.systemd1",
                                     "/org/freedesktop/systemd1",
                                     "org.freedesktop.systemd1.Manager",
                                     "GetUnitByPID",
                                     &error,
                                     &m,
                                     "u",
                                     (uint32_t)serviceId); 
```

Passing in a non-service process pid should return an error code, not cause a system crash.

### Unexpected behaviour you saw

When a non-service process PID is passed in, the system crashes, ubuntu22.04 in Hyper-V disconnects, and ubuntu22.04 exits.

### Steps to reproduce the problem

```
#include <iostream>
#include <systemd/sd-bus.h>
#include <iostream>
#include <stdexcept>
#include <cstring>

#include <systemd/sd-login.h>
#include <thread>
#include <sys/resource.h>
#include <fstream>

 int manager_service_by_id(int serviceId, const std::string& action) {
        sd_bus *bus = nullptr;
        sd_bus_error error = SD_BUS_ERROR_NULL;
        sd_bus_message *m = nullptr;
        std::string objectPath;
        std::string serviceName;

        int ret = sd_bus_open_system(&bus);
        if (ret >= 0) {
            std::cout << "linux_service_manager connect to dbus!" << std::endl;
            ret = sd_bus_request_name(bus, "com.byd.bos_em_service",0);
            if (ret >= 0) {
                std::cout << "linux_service_manager  require service name " <<  std::endl;
            }
        }

        ret = sd_bus_call_method(bus,
                                     "org.freedesktop.systemd1",
                                     "/org/freedesktop/systemd1",
                                     "org.freedesktop.systemd1.Manager",
                                     "GetUnitByPID",
                                     &error,
                                     &m,
                                     "u",
                                     (uint32_t)serviceId);

        if (ret < 0) {
            std::cerr << "manager_service_by_id " << "Failed to GetUnitByPid pid :" << serviceId << " " << error.message << std::endl;
            sd_bus_error_free(&error);
            sd_bus_message_unref(m);
            sd_bus_unref(bus);
            return -1;
        }

        const char* path = nullptr;
        ret = sd_bus_message_read(m, "o", &path);
        if (ret < 0 ) {
            sd_bus_message_unref(m);
            sd_bus_error_free(&error);
            sd_bus_unref(bus);
            std::cerr << "Failed to read object path: " << serviceId << " " << strerror(-ret) << std::endl;
            return -1;
        }

        if (path == nullptr) {
            std::cerr << "read empty object path" << std::endl;
            sd_bus_message_unref(m);
            sd_bus_error_free(&error);
            sd_bus_unref(bus);
            return -1;
        }

        objectPath = path;
        sd_bus_message_unref(m);
        m = nullptr;

        ret = sd_bus_get_property(bus,
                                  "org.freedesktop.systemd1",
                                  objectPath.c_str(),
                                  "org.freedesktop.systemd1.Unit",
                                  "Id",
                                  &error,
                                  &m,
                                  "s");
        if (ret < 0) {
            std::cerr << "Failed to get Id property: " << error.message << std::endl;
            sd_bus_message_unref(m);
            sd_bus_error_free(&error);
            sd_bus_unref(bus);
            return -1;
        }

        const char* service = nullptr;
        ret = sd_bus_message_read(m, "s", &service);
        if (ret < 0 ) {
            std::cerr << "Failed to read Id property: " << strerror(-ret) << std::endl;
            sd_bus_message_unref(m);
            sd_bus_error_free(&error);
            sd_bus_unref(bus);
            return -1;
        }

        if (service == nullptr) {
            std::cerr << "read empty Id property" << std::endl;
            sd_bus_message_unref(m);
            sd_bus_error_free(&error);
            sd_bus_unref(bus);
            return  -1;
        }

        serviceName = service;
        sd_bus_message_unref(m);
        m = nullptr;

        ret = sd_bus_call_method(bus,
                                 "org.freedesktop.systemd1",
                                 "/org/freedesktop/systemd1",
                                 "org.freedesktop.systemd1.Manager",
                                 action.c_str(),
                                 &error,
                                 &m,
                                 "ss",
                                 serviceName.c_str(),
                                 "replace");

        if (ret < 0) {
            std::cerr << "Failed to " << action <<  " service: " << error.message << std::endl;
            sd_bus_error_free(&error);
            sd_bus_message_unref(m);
            sd_bus_unref(bus);
            return -1; // Indicate error
        }

        sd_bus_message_unref(m);
        sd_bus_error_free(&error);

        sd_bus_unref(bus);
        // Get the main PID of the service
        return 0;
        // return getMainPidByName(serviceName);
    }

int stop_service_by_id(int serviceId) {
   return manager_service_by_id(serviceId, "StopUnit");
}

int main() {
    std::cout << "input servcieId" << std::endl;
    int pid;
    int result;
    while(std::cin >> pid ) {
        std::cout << "stop pid: " << pid << " result: " << stop_service_by_id(pid) << std::endl;
    }

    return 0;
}
```

Write a simple program, eg

```
#include <iostream>
#include <thread>
#include <chrono>
#include <unistd.h>
int main() {
    int pid;
    while(true) {
        pid = getpid();
        std::cout << "app running..." <<  " pid: " << pid << std::endl;
        
        std::this_thread::sleep_for(std::chrono::seconds(5));
    }

    return 0;
}
```

Start the program, and then pass in the PID of the program

**Comment by poettering** [comment] 2024-08-23 08:14
254 is too old to be tracked here. Please contact your downstream distro for help.

and this is not a useful bug report, as you didn't include logs of the generated failure.

**Comment by bluca** [comment] 2024-08-27 14:32
Also please provide the debug logs and ideally the crash dump

**Comment by poettering** [comment] 2024-08-29 08:14
> Actually we still do stable release updates for v254

hmm, can we *please* dial down the noise on this? this bug tracker becomes useless if it starts tracking issues that are not existing in current versions of systemd.

**Comment by bluca** [comment] 2024-08-29 08:33
I think a hard pid1 crash is worth an exception, as far as bugs go out cannot get much worse than that

**Comment by yuwata** [comment] 2024-08-29 09:55
I cannot reproduce the issue. I've tested with #34168.

**Comment by bluca** [comment] 2024-08-29 10:01
I can't reproduce either - the key detail we are missing, as mentioned earlier, is _how_ the program is ran, so that it ends up not being part of a unit. Without that information this is not actionable.

**Comment by yuwata** [comment] 2024-09-02 08:38
Do you really observe crash?
I guess you run the sleep code in system.slice or so, then the 'GetUnitByPID' and 'StopUnit' program terminates system.slice. So, you confused that the system is crashed. Similarly, if you run the sleep code in a user session, then the 'StopUnit' program terminates the user session, and you will be logged out.
If so, there is nothing spurious, and everything expected.

Closing. Feel free to request to reopen if you really observe crash. Then, please provide coredump or so.

**Closed as completed by yuwata** 2024-09-02 08:38 UTC
Labels: bug 🐛, pid1, needs-reporter-feedback ❓, cant-reproduce
