### ISSUE TITLE
Enable dependencies on system units from user scope

### ISSUE THREAD

**Issue by mrmeszaros** [systemd/systemd#26305] opened 2023-02-02 22:20 UTC
### Component

systemctl, systemd

### Is your feature request related to a problem? Please describe

I have a user level timer unit that triggers a service that needs network to be online.
Problem is, the `network-online.target` is a system level unit.

So, now my user scoped units cannot depend on units that are inherently system level.

MOREOVER, when I added `Requires=network-online.target` to the user scoped timer, and did a daemon-reload, I received NO warning whatsoever, and wondered why the timer does not activate.

### Describe the solution you'd like

Enable cross-scope dependencies "downwards": `user -> system`.

OR at least put out a warning, if a loaded unit has missing / unit files  or dependencies.
For example: there is no user level `network-online.target`.

### Describe alternatives you've considered

I have found that I can link the target to the users scope by running `systemctl --user link /lib/systemd/system/network-online.target` which simply creates a symlink inside `.config/systemd/user/`.

### The systemd version you checked that didn't have the feature you are asking for

245

**Comment by dtardon** [comment] 2023-02-03 09:59
A duplicate of #3312.

**Closed as not planned** 2023-02-03 10:00 UTC
Labels: RFE 🎁, pid1, systemctl, duplicate

**Comment by poettering** [comment] 2023-02-03 10:54
Still think it might make sense to provide networkd-wait-online also in the user session
