### ISSUE TITLE
PathExists triggers continously, hogging CPU

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#16669] opened 2020-08-04 21:52 UTC
Version: 246

Originally filed downstream as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=967906

resolvconf ships the following files
```
resolvconf: /lib/systemd/system/resolvconf-pull-resolved.path
resolvconf: /lib/systemd/system/resolvconf-pull-resolved.service
```

Those monitor changes to `/run/systemd/resolve/stub-resolve.conf` to update the resolvconf state accordingly. With 246, systemd enters a busy loop where it continously starts resolvconf-pull-resolved.service

To reproduce the problem, make sure resolved is enabled and active then create those two unit files

```
# cat test.service
[Unit]
Description=test

[Service]
Type=oneshot
ExecStart=sh -c 'date'

# cat test.path
[Path]
PathChanged=/run/systemd/resolve/stub-resolv.conf
PathExists=/run/systemd/resolve/stub-resolv.conf
```
Now start `test.path` and systemd, journald and dbus will hog the CPU trying to contiously start `test.service`

**Comment by mbiebl** [comment] 2020-08-05 21:25
Running git bisect, the first bad commit is 708961c

**Comment by mbiebl** [comment] 2020-08-06 07:04
@OhNoMoreGit ^ can you have a look? Is this really the desired behaviour?

**Comment by OhNoMoreGit** [comment] 2020-08-06 23:52
It is as far as I can tell the behaviour that is documented in `systemd.path(5)`:

    When a service unit triggered by a path unit terminates (regardless
    whether it exited successfully or failed), monitored paths are
    checked immediately again, and the service accordingly restarted
    instantly.

Since `PathExists=` is continually asserted, the service should be continually started.

Now, it may be the case that the _documentation_ is wrong, in which case my fix to make the code match the documentation is wrong. But if that's the case, it's impossible to use path units in a race-free fashion. There will always be some period when the file could be created that would be "lost" by systemd... or even by the service itself, if it does its own inotify-based monitoring of the path.

**Comment by mbiebl** [comment] 2020-08-07 06:42
Does this behaviour make sense? I mean, why should `test.service` immediately be triggered again if there were no changes to `/run/systemd/resolve/stub-resolv.conf`?

**Comment by mbiebl** [comment] 2020-08-07 06:45
What I don't understand quite yet, what does `monitored paths are checked immediately again` mean? As said, in this particular case, the monitored path has not changed since the service was started the last time. Nonetheless, systemd starts it as if there was a change to the monitored path in the mean time.

**Comment by OhNoMoreGit** [comment] 2020-08-07 09:07
Well, to me `PathExists=` means "trigger the unit if the path _exists_", not "trigger the unit if the path _comes into existence_". The manpage does say `If the file specified exists, the configured unit is activated.`.

If you only want to trigger the service when the file changes, why not just use `PathChanged=` alone? What is the intent of the `PathExists=` in that unit?

**Comment by mbiebl** [comment] 2020-08-07 09:56
I'm not the author of those unit files, so take my answer with a grain of salt: I suppose the idea was to get the initial state from resolved when `resolvconf-pull-resolved.path` is started. Say resolved is active and running and you start `resolvconf-pull-resolved.path` during boot, you want to get the current data from resolved and watch for any changes.

**Comment by OhNoMoreGit** [comment] 2020-08-07 10:11
It seems like a better way to do that would be to have an `[Install]` section in `resolvconf-pull-resolved.service` and have it started at boot, like any other service. This will work even if there is a `resolvconf-pull-resolved.path` to trigger it later.

@poettering What are your thoughts on this issue? This is definitely a regression as the behaviour has _changed_ in the last systemd release. But is the old or new behaviour "more correct"?

We might be able to make `PathExists=` only ever trigger the service once for a particular file; i.e. the file would have to be completely unlinked and re-created for it to trigger again. Was this the intended behaviour when path units were added to systemd?

**Comment by mbiebl** [comment] 2020-08-07 10:52
Shouldn't at the very least be some rate limiting applied? DoSing a system this way is not a sensible behaviour imho.

**Comment by OhNoMoreGit** [comment] 2020-08-07 11:08
Yes, if `StartLimitIntervalSec=`/`StartLimitBurst=` isn't being applied, that does sound like something that should be fixed.

**Comment by mbiebl** [comment] 2020-08-07 11:15
I guess with this change, `PathExists=` and `Type=oneshot` (without `RemainAfterExit=true`) is no longer a sensible combination. Maybe the documentation should warn explicitly in that regard.

**Comment by mbiebl** [comment] 2020-08-07 11:21
> If you only want to trigger the service when the file changes, why not just use `PathChanged=` alone? What is the intent of the `PathExists=` in that unit?

I found this
https://salsa.debian.org/debian/resolvconf/-/commit/f55901068d8f971d9514c8d8e3082fa7d56effa3

Bringing @xnox into the loop here (as author of that change) and @andrewshadura as maintainer of resolvconf

**Comment by OhNoMoreGit** [comment] 2020-08-07 11:22
It makes sense if the service were to _remove_ the file. Think, for instance, of a spool directory: you could have `PathExistsGlob=` (or `DirectoryNotEmpty=`) to start the service whenever there are one or more files to be processed, and the service could delete the files as it processes them.

But I agree that some further warnings on the behaviour of these directives might be warranted. That is, if this new behaviour is actually correct.

I hope it is... as I said earlier, it's the behaviour I'd written _my_ tools expecting.

**Comment by xnox** [comment] 2020-08-07 11:59
We have changed how resolvconf/resolved integration many times.

I thought we need path trigger to pull up to date search domains from resolved into resolvconf, if resolvconf manages the system.

At the time it was introduced there were ordering issues, and unit needed to be fired irrespective of resolved or resolvconf (ifupdown) starting first. Thus Exist & Changed triggers needed for things to work on boot & during runtime.

Maybe the triggers got fixed since and Changed is fired on boot too, making Exists redundant?

**Comment by OhNoMoreGit** [comment] 2020-08-07 12:11
`PathChanged=` won't fire on boot. If you want the service to start on boot, you can just use:

    [Install]
    WantedBy=multi-user.target

and enable the service.

**Comment by xnox** [comment] 2020-08-07 12:16
Yeap that make sense. I'll try to check if everything still works correctly with "enabled by default, condition exists, and path changed"

We probably want the service to be WantedBy systemd-resolved.service though.

**Comment by mbiebl** [comment] 2020-08-11 19:45
Hi @poettering : I'd welcome your feedback here. What's your take on this issue?

**Comment by barlik** [comment] 2020-08-14 23:32
Hi, I have stumbled upon the same bug just now after upgrading systemd to version 246.

For year, I've been using `PathExistsGlob=/dev/input/event*` to monitor new input devices and then trigger a `oneshot` unit file (without `RemainAfterExit=true`) to set them up. This setup was working reliably and I've never had issues with it before.

I don't know which behaviour is the correct one, the old or the new one, but silently changing it will make a lot of people unhappy. Likewise, I don't think that adding a documentation warning is enough; if the `Type=oneshot` and `RemainAfterExit=false` combination is no longer desirable, the service should fail straight away and avoid looping indefinitely.

**Comment by arvidjaar** [comment] 2020-08-15 07:33
> For years, I've been using `PathExistsGlob=/dev/input/event*` to monitor new input devices and then trigger a `oneshot` unit file (without `RemainAfterExit=true`) to set them up.

Well, that's different use case and using `RemainAfterExit=true` will defeat the purpose of path unit as it will activate the first time only. I do not think it is possible to implement in current state. It really requires something like `PathAdded=` (and may be `PathRemoved=`), but then it also needs some way to pass file name to started unit.

**Comment by poettering** [comment] 2020-09-11 16:27
The old behaviour of PathExists= was simply broken, and not in line with what the docs said.  708961c7011b7578d3e6e10ca463d15edb62b5c1 fixed the code to match the docs. And I think the new behaviour makes a ton more sense, since it removes the raciness around it. The idea around PathExists= is that some service is supposed to be started whenever a specific file exists, and is restarted as long as it exists. If a service wants to stop that it could remove the file or just keep running. I am sorry that users apparently started to rely on our bug here. :-(

If you want to be started only when a file is changed use PathChanged/Modified= – that's what they are for.

if you want to start some service when some file exists once and then restart it whenever it is changed, then add ConditoinPathExists= to your service and simply invoke the service at boot, along with the .path unit. Note that this is racy however, since if a change is made right after your service did its thing but before it exited, then you'll lose the event. If that's a relevant usecase we should cover we could add a new PathTimestampChanged= or so, which would be exactly like PathModified= but do one more thing: keep track of the mtime/ctime of the file, and if it changed while the service was running, and the service exited, then we'd immediately reexecute it. That way you'd get the guarantee that we'd start your service after each mtime/ctime change, so that your service goes through its startup phase for each change. But that'd be a new feature, consider posting an RFE issue for that.

Now, as I understand the start limit wasn't trggered for this stuff, which would be a real bug to fix. i'll have a look at that.

**Comment by keszybz** [comment] 2020-09-12 07:50
What @OhNoMoreGit writes in https://github.com/systemd/systemd/issues/16669#issuecomment-670486278:
> If you want the service to start on boot, just add an `[Install]` section 

is correct, but not desirable. We should have a way to trigger the path unit if the path *initially exists* when the path unit is started and then whenever it is modified. We shouldn't require a separate enablement step to have this behaviour.

I see three ways:
- add a new directive like PathChangedOrExisted= (no idea about the name)
- tweak PathChanged= to take an additional character like `!`: `PathChanged=!/some/path`
- change the definition of PathChanged= to also include "path exists when the path unit is first started".

I have a preference for the third option, because it is simpler and it removes a race condition: we can never tell if a path was modified before or while the manager is started.

**Closed as completed** 2020-09-14 19:51 UTC
Labels: regression ⚠️
