### ISSUE TITLE
sd-bus: org.freedesktop.DBus.ObjectManager listed in GetManagedObjects results

### ISSUE THREAD

**Issue by bradbishop** [systemd/systemd#8444] opened 2018-03-13 19:53 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

I noticed this when my project moved to 234.  The behavior outlined below appears to have been introduced here: systemd/systemd#5799.

### Used distribution

Yocto 2.4

### In case of bug report: Unexpected behaviour you saw

systemd adds org.freedesktop.DBus.ObjectManager to all objects returned via GetManagedObjects when ObjectManager is not implemented on those objects.

### In case of bug report: Steps to reproduce the problem

Create a dbus service
Create an ObjectManager on "/"
Create an object on "/foo"
busctl call [service] / org.freedesktop.DBus.ObjectManager GetManagedObjects
Observe the org.freedesktop.DBus.ObjectManager interface on /foo in the reply

**Comment by bradbishop** [comment] 2018-03-14 01:36
Possible patch:  systemd/systemd#8448

**Comment by igo95862** [comment] 2022-07-26 18:53
Should be fixed now: 5f4ccb0705a54f18f2010b9481039918c448a524

**Closed as completed** 2022-07-26 19:00 UTC
Labels: sd-bus

**Comment by igo95862** [comment] 2022-07-26 20:20
@yuwata could you also look at #2986 (it was fixed long ago but the issue is still opened)
