### ISSUE TITLE
systemd-user doesn't properly close its PAM session

### ISSUE THREAD

**Issue by ebiggers** [systemd/systemd#8598] opened 2018-03-28 04:09 UTC
The systemd --user instance that is started when a user first logs in (if pam_systemd is enabled) starts a subprocess "(sd-pam)" that opens a PAM session for the user, using the "systemd-user" service name.  See [setup_pam() in src/core/execute.c](https://github.com/systemd/systemd/blob/e64c2d0b5fbd8ab75d8f73f5820696ee15c8c6f0/src/core/execute.c#L1122).

However, this PAM session is not properly closed.  There are two related bugs:

* The sd-pam subprocess drops privileges after pam_open_session(), so pam_close_session() runs as the user rather than as root.  This breaks PAM modules that need to do privileged tasks to clean up the session, such as unmounting the user's home directory.  Note that the [man page for pam_close_session()](http://man7.org/linux/man-pages/man3/pam_close_session.3.html) explicitly says that privileges are needed:

>  It should be noted that the effective uid, geteuid(2). of the application should be of sufficient privilege to perform such tasks as unmounting the user's home directory for example.

* systemd doesn't wait for the sd-pam subprocess to close the PAM session and exit but rather sends it SIGKILL.  It can be killed while in the middle of pam_close_session(), so not all of the PAM hooks are guaranteed to be run.  I verified this using strace; PID 1 was iterating through all processes in the user's cgroup, including sd-pam, and killing them.  This breaks PAM modules such as [pam_mount](http://pam-mount.sourceforge.net/), [pam_ecryptfs](http://manpages.ubuntu.com/manpages/artful/man8/pam_ecryptfs.8.html), and [pam_fscrypt](https://github.com/google/fscrypt#setting-up-the-pam-module).  That is, with pam_mount [the user's filesystems are left mounted](https://wiki.archlinux.org/index.php/Talk:Pam_mount#automatic_unmounting_and_systemd); with pam_ecryptfs [the user's encrypted home directory is left mounted/unlocked](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=765854); and with pam_fscrypt the user's login passphrase-protected directories are left "unlocked". This appears to be a longstanding bug that many users have reported in many Linux distributions over the past few years; the preceding links were just a couple examples.  The Debian bug for ecryptfs was reported for the Jessie release which was the release that Debian switched from sysvinit to systemd.

I observed these bugs on systemd 238 and on Arch Linux, though from what I gather these bugs are already years old at this point, and affect all Linux distributions that use systemd.  To be very clear, these bugs are *not* caused by the user having background processes running; the problem is that systemd is not properly closing a PAM session when the systemd-user instance exits.

Unfortunately I don't have an easy solution in mind, though I haven't had time to look into it in depth yet.  It's possible that having the sd-pam process be a child of systemd-user is just fundamentally wrong, so the order will need to be flipped around to have sd-pam spawn systemd-user, which would make it more similar to how other processes like 'login' or display managers manage PAM sessions.

In the mean time, here are some possible workarounds for people affected by this bug:

* One workaround is to configure /etc/pam.d/systemd-user to exclude the relevant PAM module(s).  This prevents systemd-user from opening a PAM session with the relevant PAM modules, so it doesn't matter that it doesn't get closed.  I'm using this workaround on my Arch Linux system with pam_fscrypt.  However, this has the disadvantage that if systemd-run is used to run a long-lived service like 'screen' that persists past logout, then the home directory is not kept unlocked as might be expected.

* An alternative workaround which [might be implemented for fscrypt](https://github.com/google/fscrypt/issues/95) (though a similar workaround could be used for ecryptfs as well) is to do the directory locking/unlocking in a systemd service instead of a PAM module.  It's an ugly hack though, and the PAM session hook would still be needed for non-broken init systems.

* Or pam_systemd can be disabled, though this breaks other functionality.

**Comment by arvidjaar** [comment] 2018-03-28 06:22
> systemd doesn't wait for the sd-pam subprocess to close the PAM session and exit but rather sends it SIGKILL

Which cgroup version? I believe on v1 systemd still skips waiting for empty cgroup in this case which matches your observation; on v2 it should wait until sd-pam exits (or timeout).

**Comment by ebiggers** [comment] 2018-03-28 06:36
> Which cgroup version? I believe on v1 systemd still skips waiting for empty cgroup in this case which matches your observation; on v2 it should wait until sd-pam exits (or timeout).

It's v2, apparently.   strace output of pid 1 shows:

```
open("/sys/fs/cgroup/unified/user.slice/user-1000.slice/user@1000.service", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 17
fstat(17, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
getdents(17, /* 13 entries */, 32768)   = 464
openat(AT_FDCWD, "/sys/fs/cgroup/unified/user.slice/user-1000.slice/user@1000.service/init.scope/cgroup.procs", O_RDONLY|O_CLOEXEC) = 49
fstat(49, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
read(49, "13386\n", 4096)               = 6
openat(AT_FDCWD, "/proc/13386/comm", O_RDONLY|O_CLOEXEC) = 50
fstat(50, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
read(50, "(sd-pam)\n", 1024)            = 9
close(50)                               = 0
kill(13386, SIGKILL)                    = 0
```

Mountpoint is:

``
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
``

**Comment by poettering** [comment] 2018-03-28 10:44
Part of this is already discussed in #1350.

**Comment by poettering** [comment] 2018-03-28 10:52
So, we got away with all this so far because relying on the PAM end hook for resource deallocation is less than ideal anyway, and most software hence doesn't rely on it and uses some alternative scheme, so that PAM session managers which die abnormally won't leave stuff around.

The reason it's done the way it is is that we rely on PR_DEATHSIG to clean-up the PAM helper process when the service main process goes away, but the kernel will only honour this if privs match between the service process and the PAM session stub process...

Fixing this properly would mean making the PAM stub process something PID 1 cares for explicitly. WHich we should do, but so far didn't bother with...

However, I'd strongly recommend to change the design of your package so that you do not rely on PAM session end hooks anyway. If you do, then things will always remain fragile, maybe one day no longer with the PAMName= concept in systemd, but still with all the other weird PAM users out there. One way to handle this more robustly is to do clean-up of your mounts in some external mini service, and allocate some socket or so to it in the pam start hook, which you close in the end hook. However, if the PAM stub process dies abnormally the kernel will close it automatically too, hence you get the guarantee that your service will be informed about ending PAM sessions.

**Comment by aplsms** [comment] 2018-09-21 03:35
i have the same issue. details: https://github.com/systemd/systemd/issues/10123

**Comment by domdom82** [comment] 2018-10-18 16:21
I think I am getting the same issue on Ubuntu 16.04.
We have many users working on a system with tmux sessions. The users login with ssh and use sudosh as a login shell to be able to capture their sessions for audit logging. Not sure if that is related.

After a couple of days we get hundreds of zombies all looking like this:
```
(...)
14937 ?        Ds     0:00 /lib/systemd/systemd --user
14939 ?        Z      0:00  \_ [(sd-pam)] <defunct>
15058 ?        Zs     0:00  \_ [kill] <defunct>
17414 ?        Ds     0:00 /lib/systemd/systemd --user
17415 ?        Z      0:00  \_ [(sd-pam)] <defunct>
17699 ?        Zs     0:00  \_ [kill] <defunct>
24999 ?        Ds     0:00 /lib/systemd/systemd --user
25005 ?        Z      0:00  \_ [(sd-pam)] <defunct>
25346 ?        Zs     0:00  \_ [kill] <defunct>
 6725 ?        Ds     0:00 /lib/systemd/systemd --user
 6726 ?        Z      0:00  \_ [(sd-pam)] <defunct>
 6889 ?        Zs     0:00  \_ [kill] <defunct>
12206 ?        Ss     0:00 /lib/systemd/systemd --user
12207 ?        S      0:00  \_ (sd-pam)
 9258 ?        Ds     0:00 /lib/systemd/systemd --user
 9262 ?        Z      0:00  \_ [(sd-pam)] <defunct>
29674 ?        Zs     0:00  \_ [kill] <defunct>
 8829 ?        Ds     0:00 /lib/systemd/systemd --user
 8830 ?        Z      0:00  \_ [(sd-pam)] <defunct>
 9117 ?        Zs     0:00  \_ [kill] <defunct>
 7383 ?        Ds     0:00 /lib/systemd/systemd --user
 7384 ?        Z      0:00  \_ [(sd-pam)] <defunct>
 7387 ?        Zs     0:00  \_ [kill] <defunct>
(...)
```

**Comment by Amosss** [comment] 2020-02-12 12:23
I think I'm having the same issue with ubuntu 18.04.4
ssh sessions are not cleared from the list loginctl list-sessions

**Comment by xidiandb** [comment] 2020-04-16 02:42
How to reproduce

**Comment by Mogaba** [comment] 2020-06-09 14:30
I believe I have the same issue in Debian 10 with pam_mount: mounts and ssh processes stay active after logout. Is there a workaround?

**Comment by chriscoxe** [comment] 2021-04-07 17:55
@ebiggers
> However, this has the disadvantage that if systemd-run is used to run a long-lived service like 'screen' that persists past logout, then the home directory is not kept unlocked as might be expected.
I'm wondering how safe this workaround is. Should it be relatively safe on the assumption that systemd-run commands won't be run by a user, and that nothing special has been set up anything relating to /home or the home directory for individual user(s) (e.g. not using systemd-homed or homectl), and not  logging in via SSH? The reason I ask is because I don't know much about systemd & PAM, so I don't know whether/which systemd services access home directories unless special setup has been done, and I wonder whether I should be worried about race conditions, e.g. if some kind of systemd or login manager or other system process might try to access a user's home directory before it has been unlocked, or after it has been locked. Note: if it matters, I'm using LightDM on Arch Linux; it's a home PC that I won't be accessing from remotely. If you can think of anything else (apart from sshd) accesses a home directory that's commonly installed that this workaround might not work for, that might be helpful for other users to be aware of, until this issue or the underlying issue is resolved.

Am I right in thinking that (using the Arch Linux install instructions at the time of writing), setting up an encrypted home directory for individual user(s), that if this workaround is not used, logging out (of e.g. the display manager such as GDM or LightDM) won't typically lock the user's home directory (due to the underlying problem), and (assuming nothing special has been set up relating to home directory for individual user(s)) that a reasonably safe way to lock it instead would be to properly shut down the machine, i.e. would be unlocked on the first attempt by anything to lock it, then there might then be in a period while other stuff that accesses it on shutdown writes to it using the already open file handles (could they corrupt the files if they try to write to them)? Thanks

**Comment by junkeythong** [comment] 2021-05-23 07:47
I also faced the same issue, I use the workaround using setpriv instead of sudo when calling a command with normal user, it will bypass PAM. I still don't know the permanent fix right now.
Thanks

**Comment by IsaacRay** [comment] 2022-05-16 18:57
@00xc to be perfectly honest, I don't know how it was used. All I know is what I could see in the logs, which showed me the command history of the user, and I was able to view the session IP for the user that executed the commands. I will have to dig up the log file, since this was months and months ago.

**Comment by gleventhal** [comment] 2022-11-04 16:25
Is this being worked on?  I believe I am seeing this issue, and suspect that  it's leading to harmful issues with automount

**Comment by ileGITimo** [comment] 2023-05-22 14:40
I have two Fedora 38 systems where cron sessions remain open and eventually each new invocation of cron results in "Failed to create session: Maximum number of sessions (8192) reached".  Cron scripts seem to run but this is a bit annoying.   Could look into converting to systemd timers, but this ought to work.

**Comment by Danbardo** [comment] 2023-07-25 23:25
I just upgraded from CentOS 7 to Almalinux 8.8.0.
CSF is picking up systemd --user and sd-pam running for up to 7 hours after a user logs out.
The processes seem to terminate after that. Is there any way to reduce period of time the program remains running after logout?

**Comment by msekletar** [comment] 2024-01-09 14:06
@poettering What about connecting to PID1 via dbus from `(sd-pam)` and calling `StartAuxiliaryScope()` and create the scope that would have `Before=` and `BindsTo=` on `user@<UID>.service` to ensure proper stop ordering? Scope could be named `user-<UID>-sd-pam.scope` or so.

**Comment by Werkov** [comment] 2024-01-09 14:52
(Oh, the new hammer on an old nail :-)
In this particular case, is cgroup context cloning necessary?
Otherwise, the "old hammer" `StartTransientUnit()` could solve this analogously.

**Comment by msekletar** [comment] 2024-01-09 15:04
But jokes aside I think that cgroup context copying is exactly what you want in this case and potential patch we might end up with would be *much* shorter compared to the patch we would need if we wanted to do this manually.

**Comment by poettering** [comment] 2024-01-09 17:19
@msekletar i am pretty sure the pam process should be kept part of the unit in question. It should just be tracked explicitly by pid1. 

i.e. right now, pid1 tracks two processes per service: main and control. add a third one, the pam process (or call it "session" process, i don't care).

Then, when we go into the killing logic, kill the pam process a bit later than the rest.

generally, I think pam modules which rely on on the session close hook to be called are not a model we should really support, it's simply not robust. pam sessions are a fragile concept and pam modules really should make sure they can recover from such unclean shutdowns.

or in other words: i think these pam modules should not rely on the session close hook to work correctly, but have some ipc socket or so in the background that tracks the session. this is what pam_systemd did since day 1, precisely to ensure the robustness here, and not having to rely on the pam session.

**Closed as completed** 2024-05-21 07:01 UTC
Labels: pid1
