### ISSUE TITLE
systemd v232 on i686 - Cannot recognize partitions on boot and no UUIDs with lsblk -f

### ISSUE THREAD

**Issue by thx1111** [systemd/systemd#4614] opened 2016-11-08 06:02 UTC
- [ ] Bug report
 
> systemd 232-1

> Arch

On a couple of older i686 laptops, circa 2006, with systemd 232-1, there is some problem where systemd will not be able to recognize the HD partitions, right after the kernel sets-up the drive - a 40GiB and 75GiB Hitachi in these cases. This seems to be something that tracks with the systemd package, as downgrading *just* the systemd package, to 231-4, makes the problem go away. I did *not* see the problem on a couple of newer x86-64 laptop and desktop machines.

The most telling thing that I've noticed so far is that, when systemd fails, the "lsblk -f" command only knows the mount points, and *the UUIDs are all blank*. The lsblk man page says "reads the sysfs filesystem and udev db to gather information". So, if systemd tries to do the same thing, and fails to receive the UUIDs, then everything fails from there - no swap, no root, no journald, ... and systemd is stuck, with timeouts. But then, if systemd is downgraded, the lsblk command works normally, and shows the UUIDs.

232-1 definitely has some problem on some hardware. I can boot into systemd emergency mode to twiddle things, and downgrade systemd. There are no other oddities so far, while running with the 232-1 systemd in emergency mode. The partitions can all be mounted and read and written. fsck says the fs is clean. blkid -p returns all the correct UUIDs. There is just that issue with lsblk and systemd boot.

If you have any ideas where to look for the cause of this, please let me know. In particular, how could systemd affect lsblk? Something with the udev db? Or with the udevd 232 specifically? Is systemd-udevd not working on i686?

**Comment by keszybz** [comment] 2016-11-10 13:15
There were a bunch of tree-wide cleanups, and some small feature additions,
but no "real changes". It's possible that it's some memory corruption issue,
either a new one, or even something that was there previously and got
exposed now. I'm afraid i686 gets very little testing.

**Comment by falconindy** [comment] 2016-11-10 21:03
Since this is i686, I'm pretty sure this is a dupe of https://github.com/systemd/systemd/issues/4575.

**Comment by keszybz** [comment] 2016-11-10 21:06
You're right, it almost certainly is. For some reason I though #4575 is already fixed (maybe because it's so egregious ;))

**Comment by poettering** [comment] 2016-12-13 01:35
Closing this as duplicate of #4575.

**Closed as completed by poettering** 2016-12-13 01:35 UTC
Labels: duplicate
