### ISSUE TITLE
systemd-nspawn -u foo fails if foo is not a valid user on the host system

### ISSUE THREAD

**Issue by davide125** [systemd/systemd#8194] opened 2018-02-15 23:34 UTC
`systemd-nspawn -u` is documented as "After transitioning into the container, change to the specified user-defined in the container's user database.". In systemd 234, this works fine even if the user specified doesn't exist on the host system, as long as it's available within the container. This changed in 237, where nspawn started failing explicitly in this case with a `Failed to resolve user` error. We've noticed this when trying to use `mock`, as internally that calls `systemd-nspawn -u mockbuild`, where `mockbuild` doesn't exist on the host (by design), but it defined as `mockbuild:x:0:156::/builddir:/bin/bash` in `/etc/passwd` in the mock chroot. @zfjagann and I did some digging and think this might be related to 7d4904fe7a (which was part of #7767), but we haven't been able to validate that as the commit doesn't revert cleanly in the released 237 tree.

### Submission type

 - Bug report

### systemd version the issue has been seen with

> 237

### Used distribution

> CentOS 7

### In case of bug report: Expected behaviour you didn't see

> nspawn should start the container and run the command as the specified user

### In case of bug report: Unexpected behaviour you saw

> `Failed to resolve user mockbuild.`

### In case of bug report: Steps to reproduce the problem

> Minimal repro: given a mock chroot on `/data/mock/centos-7-x86_64`, run
`systemd-nspawn -q -D /data/mock/centos-7-x86_64 -u mockbuild bash --login -c '/usr/bin/cat /etc/passwd'`
which is a simplified version of what `mock` runs internally. On 234, this produces the contents of `/etc/passwd` in the container as expected. On 237, it results in `Failed to resolve user mockbuild.`.

**Comment by zfjagann** [comment] 2018-02-16 05:00
Also, we tried this both with and without private users and both resulted
in the same behavior.

**Comment by davide125** [comment] 2018-02-22 21:47
This is a bug somewhere in `safe_fork()`, which was introduced in https://github.com/systemd/systemd/commit/4c253ed1cae8b4df72ce1353ee826a4fae399e25 as part of https://github.com/systemd/systemd/pull/7728. I validated that building systemd with the following patch applied solved the issue for us:
```
diff --git a/src/nspawn/nspawn-setuid.c b/src/nspawn/nspawn-setuid.c
index b08bcd9..bbe0d40 100644
--- a/src/nspawn/nspawn-setuid.c
+++ b/src/nspawn/nspawn-setuid.c
@@ -34,7 +34,7 @@
 #include "util.h"
 
 static int spawn_getent(const char *database, const char *key, pid_t *rpid) {
-        int pipe_fds[2], r;
+        int pipe_fds[2];
         pid_t pid;
 
         assert(database);
@@ -44,10 +44,10 @@ static int spawn_getent(const char *database, const char *key, pid_t *rpid) {
         if (pipe2(pipe_fds, O_CLOEXEC) < 0)
                 return log_error_errno(errno, "Failed to allocate pipe: %m");
 
-        r = safe_fork("(getent)", FORK_RESET_SIGNALS|FORK_DEATHSIG|FORK_LOG, &pid);
-        if (r < 0)
-                return r;
-        if (r == 0) {
+        pid = fork();
+        if (pid < 0)
+                return log_error_errno(errno, "Failed to fork getent child: %m");
+        else if (pid == 0) {
                 int nullfd;
                 char *empty_env = NULL;
```
However, this is not a proper fix -- we should find out what's wrong with `safe_fork()` in the first place.

**Comment by poettering** [comment] 2018-02-26 14:20
Hmm, so this works correctly here, though I tested this with a fedora system in a container. No problem at all changing to a user that exists in the container but not on the host here. Could you paste an "strace -f -s500 -o log …" dump of this failing on a minimal command line, please?

**Comment by poettering** [comment] 2018-02-26 14:21
also, please provide the output of the command when SYSTEMD_LOG_LEVEL=debug is set!

**Comment by davide125** [comment] 2018-02-26 17:59
Here's the output with `SYSTEMD_LOG_LEVEL=debug`
```
# SYSTEMD_LOG_LEVEL=debug systemd-nspawn -q -D /data/mock/centos-7-x86_64/root -u mockbuild bash --login -c '/usr/bin/cat /etc/passwd'
Found cgroup on /sys/fs/cgroup/systemd, legacy hierarchy
(sd-namespace) succeeded.
Init process invoked as PID 3742968
Bus n/a: changing state UNSET → OPENING
Bus n/a: changing state OPENING → AUTHENTICATING
Bus n/a: changing state AUTHENTICATING → HELLO
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.32466 path=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 signature=s error-name=n/a error-message=n/a
Bus n/a: changing state HELLO → RUNNING
Sent message type=method_call sender=n/a destination=org.freedesktop.machine1 path=/org/freedesktop/machine1 interface=org.freedesktop.machine1.Manager member=CreateMachineWithNetwork cookie=3 reply_cookie=0 signature=sayssusaia(sv) error-name=n/a error-message=n/a
Got message type=method_return sender=:1.159 destination=:1.32466 path=n/a interface=n/a member=n/a cookie=1292 reply_cookie=3 signature=o error-name=n/a error-message=n/a
Failed to chown "/sys/fs/cgroup/systemd/machine.slice/machine-root.scope/cgroup.controllers", ignoring: No such file or directory
Failed to chown "/sys/fs/cgroup/systemd/machine.slice/machine-root.scope/cgroup.events", ignoring: No such file or directory
Failed to chown "/sys/fs/cgroup/systemd/machine.slice/machine-root.scope/cgroup.stat", ignoring: No such file or directory
Failed to chown "/sys/fs/cgroup/systemd/machine.slice/machine-root.scope/cgroup.subtree_control", ignoring: No such file or directory
Failed to chown "/sys/fs/cgroup/systemd/machine.slice/machine-root.scope/cgroup.threads", ignoring: No such file or directory
Child died too early.
Bus n/a: changing state RUNNING → CLOSED
Mounting / (MS_REC|MS_SLAVE "")...
Using legacy hierarchy for container.
Bind-mounting /data/mock/centos-7-x86_64/root on /data/mock/centos-7-x86_64/root (MS_BIND|MS_REC "")...
Mounting /data/mock/centos-7-x86_64/root (MS_REC|MS_SHARED "")...
Mounting tmpfs on /data/mock/centos-7-x86_64/root/tmp (MS_NOSUID|MS_NODEV|MS_STRICTATIME "mode=1777")...
Mounting sysfs on /data/mock/centos-7-x86_64/root/sys (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC "")...
Mounting tmpfs on /data/mock/centos-7-x86_64/root/dev (MS_NOSUID|MS_STRICTATIME "mode=755")...
Mounting tmpfs on /data/mock/centos-7-x86_64/root/dev/shm (MS_NOSUID|MS_NODEV|MS_STRICTATIME "mode=1777")...
Mounting tmpfs on /data/mock/centos-7-x86_64/root/run (MS_NOSUID|MS_NODEV|MS_STRICTATIME "mode=755")...
Bind-mounting /sys/fs/selinux on /data/mock/centos-7-x86_64/root/sys/fs/selinux (MS_BIND "")...
Remounting /data/mock/centos-7-x86_64/root/sys/fs/selinux (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_REMOUNT|MS_BIND "")...
Mounting devpts on /data/mock/centos-7-x86_64/root/dev/pts (MS_NOSUID|MS_NOEXEC "newinstance,ptmxmode=0666,mode=620,gid=5")...
Bind-mounting /run/systemd/nspawn/propagate/root on /data/mock/centos-7-x86_64/root/run/systemd/nspawn/incoming (MS_BIND "")...
Remounting /data/mock/centos-7-x86_64/root/run/systemd/nspawn/incoming (MS_RDONLY|MS_REMOUNT|MS_BIND "")...
Mounting /data/mock/centos-7-x86_64/root/run/systemd/nspawn/incoming (MS_SLAVE "")...
Bind-mounting /dev/pts/1 on /data/mock/centos-7-x86_64/root/dev/console (MS_BIND "")...
Applying whitelist on architecture: x86
System call preadv2 is not known, ignoring.
System call pwritev2 is not known, ignoring.
Failed to add rule for system call set_tls() / -10183, ignoring: Numerical argument out of domain
Failed to add rule for system call newfstatat() / 262, ignoring: Numerical argument out of domain
System call statx is not known, ignoring.
Failed to add rule for system call epoll_ctl_old() / 214, ignoring: Numerical argument out of domain
Failed to add rule for system call epoll_wait_old() / 215, ignoring: Numerical argument out of domain
Failed to add rule for system call arch_prctl() / 158, ignoring: Numerical argument out of domain
Applying whitelist on architecture: x32
Failed to add rule for system call _llseek() / -10026, ignoring: Numerical argument out of domain
System call preadv2 is not known, ignoring.
System call pwritev2 is not known, ignoring.
Failed to add rule for system call chown32() / -10004, ignoring: Numerical argument out of domain
Failed to add rule for system call fchown32() / -10008, ignoring: Numerical argument out of domain
Failed to add rule for system call lchown32() / -10025, ignoring: Numerical argument out of domain
Failed to add rule for system call get_thread_area() / 211, ignoring: Numerical argument out of domain
Failed to add rule for system call getegid32() / -10015, ignoring: Numerical argument out of domain
Failed to add rule for system call geteuid32() / -10016, ignoring: Numerical argument out of domain
Failed to add rule for system call getgid32() / -10017, ignoring: Numerical argument out of domain
Failed to add rule for system call getgroups32() / -10018, ignoring: Numerical argument out of domain
Failed to add rule for system call getresgid32() / -10019, ignoring: Numerical argument out of domain
Failed to add rule for system call getresuid32() / -10020, ignoring: Numerical argument out of domain
Failed to add rule for system call getuid32() / -10021, ignoring: Numerical argument out of domain
Failed to add rule for system call set_thread_area() / 205, ignoring: Numerical argument out of domain
Failed to add rule for system call set_tls() / -10183, ignoring: Numerical argument out of domain
Failed to add rule for system call sigreturn() / -10058, ignoring: Numerical argument out of domain
Failed to add rule for system call ugetrlimit() / -10068, ignoring: Numerical argument out of domain
Failed to add rule for system call fcntl64() / -10009, ignoring: Numerical argument out of domain
Failed to add rule for system call fstat64() / -10010, ignoring: Numerical argument out of domain
Failed to add rule for system call fstatat64() / -10011, ignoring: Numerical argument out of domain
Failed to add rule for system call fstatfs64() / -10012, ignoring: Numerical argument out of domain
Failed to add rule for system call ftruncate64() / -10014, ignoring: Numerical argument out of domain
Failed to add rule for system call lstat64() / -10028, ignoring: Numerical argument out of domain
Failed to add rule for system call mmap2() / -10029, ignoring: Numerical argument out of domain
Failed to add rule for system call oldfstat() / -10034, ignoring: Numerical argument out of domain
Failed to add rule for system call oldlstat() / -10035, ignoring: Numerical argument out of domain
Failed to add rule for system call oldstat() / -10037, ignoring: Numerical argument out of domain
Failed to add rule for system call stat64() / -10062, ignoring: Numerical argument out of domain
Failed to add rule for system call statfs64() / -10063, ignoring: Numerical argument out of domain
System call statx is not known, ignoring.
Failed to add rule for system call truncate64() / -10066, ignoring: Numerical argument out of domain
Failed to add rule for system call _newselect() / -10032, ignoring: Numerical argument out of domain
Failed to add rule for system call epoll_ctl_old() / 214, ignoring: Numerical argument out of domain
Failed to add rule for system call epoll_wait_old() / 215, ignoring: Numerical argument out of domain
Failed to add rule for system call ipc() / -10024, ignoring: Numerical argument out of domain
Failed to add rule for system call umount() / -10070, ignoring: Numerical argument out of domain
Failed to add rule for system call recv() / -110, ignoring: Numerical argument out of domain
Failed to add rule for system call send() / -109, ignoring: Numerical argument out of domain
Failed to add rule for system call socketcall() / -10060, ignoring: Numerical argument out of domain
Failed to add rule for system call waitpid() / -10073, ignoring: Numerical argument out of domain
Failed to add rule for system call nice() / -10033, ignoring: Numerical argument out of domain
Failed to add rule for system call setgid32() / -10046, ignoring: Numerical argument out of domain
Failed to add rule for system call setgroups32() / -10047, ignoring: Numerical argument out of domain
Failed to add rule for system call setregid32() / -10048, ignoring: Numerical argument out of domain
Failed to add rule for system call setresgid32() / -10049, ignoring: Numerical argument out of domain
Failed to add rule for system call setresuid32() / -10050, ignoring: Numerical argument out of domain
Failed to add rule for system call setreuid32() / -10051, ignoring: Numerical argument out of domain
Failed to add rule for system call setuid32() / -10052, ignoring: Numerical argument out of domain
Failed to add rule for system call sigaction() / -10054, ignoring: Numerical argument out of domain
Failed to add rule for system call signal() / -10055, ignoring: Numerical argument out of domain
Failed to add rule for system call sigpending() / -10056, ignoring: Numerical argument out of domain
Failed to add rule for system call sigprocmask() / -10057, ignoring: Numerical argument out of domain
Failed to add rule for system call sigsuspend() / -10059, ignoring: Numerical argument out of domain
Failed to add rule for system call fadvise64_64() / -10007, ignoring: Numerical argument out of domain
Failed to add rule for system call oldolduname() / -10036, ignoring: Numerical argument out of domain
Failed to add rule for system call olduname() / -10038, ignoring: Numerical argument out of domain
Failed to add rule for system call readdir() / -10041, ignoring: Numerical argument out of domain
Failed to add rule for system call sendfile64() / -10043, ignoring: Numerical argument out of domain
Failed to add rule for system call setfsgid32() / -10044, ignoring: Numerical argument out of domain
Failed to add rule for system call setfsuid32() / -10045, ignoring: Numerical argument out of domain
Applying whitelist on architecture: x86-64
Failed to add rule for system call _llseek() / -10026, ignoring: Numerical argument out of domain
System call preadv2 is not known, ignoring.
System call pwritev2 is not known, ignoring.
Failed to add rule for system call chown32() / -10004, ignoring: Numerical argument out of domain
Failed to add rule for system call fchown32() / -10008, ignoring: Numerical argument out of domain
Failed to add rule for system call lchown32() / -10025, ignoring: Numerical argument out of domain
Failed to add rule for system call getegid32() / -10015, ignoring: Numerical argument out of domain
Failed to add rule for system call geteuid32() / -10016, ignoring: Numerical argument out of domain
Failed to add rule for system call getgid32() / -10017, ignoring: Numerical argument out of domain
Failed to add rule for system call getgroups32() / -10018, ignoring: Numerical argument out of domain
Failed to add rule for system call getresgid32() / -10019, ignoring: Numerical argument out of domain
Failed to add rule for system call getresuid32() / -10020, ignoring: Numerical argument out of domain
Failed to add rule for system call getuid32() / -10021, ignoring: Numerical argument out of domain
Failed to add rule for system call set_tls() / -10183, ignoring: Numerical argument out of domain
Failed to add rule for system call sigreturn() / -10058, ignoring: Numerical argument out of domain
Failed to add rule for system call ugetrlimit() / -10068, ignoring: Numerical argument out of domain
Failed to add rule for system call fcntl64() / -10009, ignoring: Numerical argument out of domain
Failed to add rule for system call fstat64() / -10010, ignoring: Numerical argument out of domain
Failed to add rule for system call fstatat64() / -10011, ignoring: Numerical argument out of domain
Failed to add rule for system call fstatfs64() / -10012, ignoring: Numerical argument out of domain
Failed to add rule for system call ftruncate64() / -10014, ignoring: Numerical argument out of domain
Failed to add rule for system call lstat64() / -10028, ignoring: Numerical argument out of domain
Failed to add rule for system call mmap2() / -10029, ignoring: Numerical argument out of domain
Failed to add rule for system call oldfstat() / -10034, ignoring: Numerical argument out of domain
Failed to add rule for system call oldlstat() / -10035, ignoring: Numerical argument out of domain
Failed to add rule for system call oldstat() / -10037, ignoring: Numerical argument out of domain
Failed to add rule for system call stat64() / -10062, ignoring: Numerical argument out of domain
Failed to add rule for system call statfs64() / -10063, ignoring: Numerical argument out of domain
System call statx is not known, ignoring.
Failed to add rule for system call truncate64() / -10066, ignoring: Numerical argument out of domain
Failed to add rule for system call _newselect() / -10032, ignoring: Numerical argument out of domain
Failed to add rule for system call ipc() / -10024, ignoring: Numerical argument out of domain
Failed to add rule for system call umount() / -10070, ignoring: Numerical argument out of domain
Failed to add rule for system call recv() / -110, ignoring: Numerical argument out of domain
Failed to add rule for system call send() / -109, ignoring: Numerical argument out of domain
Failed to add rule for system call socketcall() / -10060, ignoring: Numerical argument out of domain
Failed to add rule for system call waitpid() / -10073, ignoring: Numerical argument out of domain
Failed to add rule for system call nice() / -10033, ignoring: Numerical argument out of domain
Failed to add rule for system call setgid32() / -10046, ignoring: Numerical argument out of domain
Failed to add rule for system call setgroups32() / -10047, ignoring: Numerical argument out of domain
Failed to add rule for system call setregid32() / -10048, ignoring: Numerical argument out of domain
Failed to add rule for system call setresgid32() / -10049, ignoring: Numerical argument out of domain
Failed to add rule for system call setresuid32() / -10050, ignoring: Numerical argument out of domain
Failed to add rule for system call setreuid32() / -10051, ignoring: Numerical argument out of domain
Failed to add rule for system call setuid32() / -10052, ignoring: Numerical argument out of domain
Failed to add rule for system call sigaction() / -10054, ignoring: Numerical argument out of domain
Failed to add rule for system call signal() / -10055, ignoring: Numerical argument out of domain
Failed to add rule for system call sigpending() / -10056, ignoring: Numerical argument out of domain
Failed to add rule for system call sigprocmask() / -10057, ignoring: Numerical argument out of domain
Failed to add rule for system call sigsuspend() / -10059, ignoring: Numerical argument out of domain
Failed to add rule for system call fadvise64_64() / -10007, ignoring: Numerical argument out of domain
Failed to add rule for system call oldolduname() / -10036, ignoring: Numerical argument out of domain
Failed to add rule for system call olduname() / -10038, ignoring: Numerical argument out of domain
Failed to add rule for system call readdir() / -10041, ignoring: Numerical argument out of domain
Failed to add rule for system call sendfile64() / -10043, ignoring: Numerical argument out of domain
Failed to add rule for system call setfsgid32() / -10044, ignoring: Numerical argument out of domain
Failed to add rule for system call setfsuid32() / -10045, ignoring: Numerical argument out of domain
Applying NETLINK_AUDIT mask on architecture: x86
Failed to add audit seccomp rule, ignoring: Invalid argument
Applying NETLINK_AUDIT mask on architecture: x32
Applying NETLINK_AUDIT mask on architecture: x86-64
Bus n/a: changing state UNSET → OPENING
Bus n/a: changing state OPENING → AUTHENTICATING
Bus n/a: changing state AUTHENTICATING → HELLO
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.32465 path=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 signature=s error-name=n/a error-message=n/a
Bus n/a: changing state HELLO → RUNNING
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/dbus interface=org.freedesktop.DBus member=NameHasOwner cookie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.32465 path=n/a interface=n/a member=n/a cookie=3 reply_cookie=2 signature=b error-name=n/a error-message=n/a
Bus n/a: changing state RUNNING → CLOSED
Mounting proc on /proc (MS_NOSUID|MS_NODEV|MS_NOEXEC "")...
Bind-mounting /proc/sys on /proc/sys (MS_BIND "")...
Remounting /proc/sys (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_REMOUNT|MS_BIND "")...
Bind-mounting /proc/sysrq-trigger on /proc/sysrq-trigger (MS_BIND "")...
Remounting /proc/sysrq-trigger (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_REMOUNT|MS_BIND "")...
Mounting tmpfs on /sys/fs/cgroup (MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_STRICTATIME "mode=755,uid=0,gid=0")...
Mounting cgroup on /sys/fs/cgroup/perf_event (MS_NOSUID|MS_NODEV|MS_NOEXEC "perf_event")...
Remounting /sys/fs/cgroup/perf_event (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_REMOUNT|MS_BIND "")...
Mounting cgroup on /sys/fs/cgroup/freezer (MS_NOSUID|MS_NODEV|MS_NOEXEC "freezer")...
Remounting /sys/fs/cgroup/freezer (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_REMOUNT|MS_BIND "")...
Mounting cgroup on /sys/fs/cgroup/blkio (MS_NOSUID|MS_NODEV|MS_NOEXEC "blkio")...
Remounting /sys/fs/cgroup/blkio (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_REMOUNT|MS_BIND "")...
Mounting cgroup on /sys/fs/cgroup/hugetlb (MS_NOSUID|MS_NODEV|MS_NOEXEC "hugetlb")...
Remounting /sys/fs/cgroup/hugetlb (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_REMOUNT|MS_BIND "")...
Mounting cgroup on /sys/fs/cgroup/cpuset (MS_NOSUID|MS_NODEV|MS_NOEXEC "cpuset")...
Remounting /sys/fs/cgroup/cpuset (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_REMOUNT|MS_BIND "")...
Mounting cgroup on /sys/fs/cgroup/net_cls,net_prio (MS_NOSUID|MS_NODEV|MS_NOEXEC "net_cls,net_prio")...
Remounting /sys/fs/cgroup/net_cls,net_prio (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_REMOUNT|MS_BIND "")...
Mounting cgroup on /sys/fs/cgroup/memory (MS_NOSUID|MS_NODEV|MS_NOEXEC "memory")...
Remounting /sys/fs/cgroup/memory (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_REMOUNT|MS_BIND "")...
Mounting cgroup on /sys/fs/cgroup/devices (MS_NOSUID|MS_NODEV|MS_NOEXEC "devices")...
Remounting /sys/fs/cgroup/devices (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_REMOUNT|MS_BIND "")...
Mounting cgroup on /sys/fs/cgroup/cpu,cpuacct (MS_NOSUID|MS_NODEV|MS_NOEXEC "cpu,cpuacct")...
Remounting /sys/fs/cgroup/cpu,cpuacct (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_REMOUNT|MS_BIND "")...
Mounting cgroup on /sys/fs/cgroup/pids (MS_NOSUID|MS_NODEV|MS_NOEXEC "pids")...
Remounting /sys/fs/cgroup/pids (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_REMOUNT|MS_BIND "")...
Mounting cgroup on /sys/fs/cgroup/systemd (MS_NOSUID|MS_NODEV|MS_NOEXEC "none,name=systemd,xattr")...
Remounting /sys/fs/cgroup (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_NOEXEC|MS_REMOUNT|MS_STRICTATIME "mode=755")...
Bind-mounting /run/proc-sys-kernel-random-boot-id on /proc/sys/kernel/random/boot_id (MS_BIND "")...
Remounting /proc/sys/kernel/random/boot_id (MS_RDONLY|MS_NOSUID|MS_NODEV|MS_REMOUNT|MS_BIND "")...
Bind-mounting /run/kmsg on /proc/kmsg (MS_BIND "")...
Successfully forked off '(getent)' as PID 2.
Failed to rename process, ignoring: Operation not permitted
Parent died early, raising SIGTERM.
Failed to resolve user mockbuild.
# 
```

**Comment by davide125** [comment] 2018-02-26 18:05
And here's the [strace-log.gz](https://github.com/systemd/systemd/files/1759743/strace-log.gz) from
```
# strace -f -s500 -o log /bin/systemd-nspawn -q -D /data/mock/centos-7-x86_64/root -u mockbuild bash --login -c '/usr/bin/cat /etc/passwd'
Child died too early.
Failed to rename process, ignoring: Operation not permitted
Failed to resolve user mockbuild.
#
```

**Comment by poettering** [comment] 2018-02-26 19:28
Hmm, if you backport 799a960d1f80c58fd982b3c248906cd4791a69fa and 7ddc2dc5e67bf0d4ace73161d6a3cde0ea85c62b, does it work then?

I am pretty sure that both together will fix the issue for you.

**Comment by poettering** [comment] 2018-02-26 19:29
ah, wait, you said you already run 237... I take that back then

**Comment by davide125** [comment] 2018-02-26 19:41
Yeah, this is on 237 as packaged [here](https://github.com/facebookincubator/rpm-backports/blob/master/rpms/systemd/specfiles/systemd.spec), which is basically the one shipped in rawhide.

**Comment by davide125** [comment] 2018-02-26 19:42
Well, https://github.com/facebookincubator/rpm-backports/commit/0536473f941e6985dff14d745c85bc9fc6482a31 to be precise, as the version in master has my workaround applied.

**Comment by poettering** [comment] 2018-02-26 19:47
Ah, but I bet backporting 996def17f99bb3f41f82032860dfcb98ff19c3ae will fix it for you.

**Comment by poettering** [comment] 2018-02-26 19:47
Closing as duplicate of #8113.

**Closed as completed by poettering** 2018-02-26 19:47 UTC
Labels: nspawn

**Comment by davide125** [comment] 2018-02-26 21:36
That did the trick, thanks @poettering !
