### ISSUE TITLE
Systemd crashed when type dbus service is enabled without busname

### ISSUE THREAD

**Issue by Taha-Firoz** [systemd/systemd#21681] opened 2021-12-08 12:25 UTC
**systemd version the issue has been seen with**
247.3-3ubuntu3.6

**Used distribution**
 Ubuntu Desktop 21.04

**Linux kernel version used** (`uname -a`)
 `5.11.0-1023-raspi #25-Ubuntu SMP PREEMPT Fri Nov 19 07:45:23 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`

**CPU architecture issue was seen on**
 AArch64

**Expected behaviour you didn't see**
 Systemd to reject invalid service file, with type dbus but busname missing

**Unexpected behaviour you saw**
Systemd crashes irrecoverably, hard restart is required

**Steps to reproduce the problem**
Make a service that has `Type=dbus` but don't add the `BusName=` field

**Additional program output to the terminal or log subsystem illustrating the issue**
```textDec 06 18:48:07 firoz systemd[1]: Freezing execution.
Dec 06 18:48:07 firoz systemd[1]: Caught <ABRT>, dumped core as pid 2135.
Dec 06 18:48:06 firoz systemd[1]: Assertion 'name' failed at src/core/unit.c:3498, function unit_watch_bus_name(). Aborting.
Dec 06 18:48:05 firoz systemd[1]: /lib/systemd/system/plymouth-start.service:17: Unit configured to use KillMode=none. This is unsafe, as it disables systemd's process lifecycle management for the service. Ple>
Dec 06 18:48:05 firoz systemd[1]: Reloading.
Dec 06 18:48:05 firoz python3[2109]: ansible-ansible.builtin.systemd Invoked with name=test.app.service daemon_reload=True enabled=True daemon_reexec=False scope=system no_block=False state=N>
```

**Comment by Taha-Firoz** [comment] 2021-12-08 12:26
I've gone through the systemd source and it seems like theres an assert for a bus name for `unit_watch_bus_name` which fails when no busname is provided however I don't supposed that should happen.

**Comment by bluca** [comment] 2021-12-08 13:32
Cannot reproduce on main:

```
Dec 08 13:30:10 image systemd[1]: test.service: Service is of type D-Bus but no D-Bus service 
name has been specified. Refusing.
```

**Comment by mrc0mmand** [comment] 2021-12-08 13:33
Looks like this was fixed in 0f97b7c338bb7440572c454558efb8fee395896a.

**Comment by bluca** [comment] 2021-12-08 13:33
It was already reported in #19920 and fixed by [0f97b7c338bb7440572c454558efb8fee395896a](https://github.com/systemd/systemd/issues/19920)

**Closed as completed by bluca** 2021-12-08 13:33 UTC
Labels: duplicate, already-fixed

**Comment by Taha-Firoz** [comment] 2021-12-08 13:37
So I should just update my systemd then?

**Comment by bluca** [comment] 2021-12-08 13:39
We don't control what patches distributions choose backport. If you'd like this bug to be fixed in Ubuntu, please use Ubuntu's bug reporting mechanism to request a backport.

**Comment by Taha-Firoz** [comment] 2021-12-08 13:42
Ok thank you!
