### ISSUE TITLE
[networkd] IPv6 prefix delegation doesn't work, networkd always assigns the same EUI-64 address no matter what 

### ISSUE THREAD

**Issue by LunarLambda** [systemd/systemd#34229] opened 2024-09-02 14:22 UTC
### systemd version the issue has been seen with

254, 252

### Used distribution

Debian 12

### Linux kernel version used

6.1.0-23-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

My router receives a `/56` net from the ISP. The router, correctly configured for IPv6 prefix delegation according to the manufacturer's official documentation, gives out a `/62` prefix for delegation.

systemd-networkd should receive that prefix via DHCPv6, and assign subnets of the prefix to the interfaces as exemplified in the `systemd.network` manpage under the `DHCPv6 PD` example.

### Unexpected behaviour you saw

No matter what I set, no matter what combination of settings I try, even having looked through every possible prefix delegation issue relating to networkd I could find, having tried with both version 252 from Debian bookworm and 254 from `bookworm-backports`, the outcome is always the same:

The upstream interface, `wan`, always assigns itself the wrong, EUI-64 generated address, which while externally routable, is /not/ a subnet of the `/62` prefix given by the router (`...:b800::/64` vs `...:b8fc::/62`) . The downstream interface, `lan`, never receives any kind of subnet from networkd.

The `Hint:` message produced by networkd is also unclear, mentioning a `IPv6Token=` setting that doesn't exist (presumably it means `Token=` in one of the IPv6-related sections), and suggests setting `UseAutonomousPrefix=no`. Neither setting seems to accomplish anything, the outcome and warning/hint message always remains the exact same.

If I throw away the addresses/routes made by networkd and assign the subnets and routes manually, it all works great and I can get IPv6 connectivity over the `lan` interface. So there is a known working state, I just cannot get networkd to produce this state.

### Steps to reproduce the problem

`/etc/systemd/network/10-wan.link`
```ini
[Match]
PermanentMACAddress=a8:b8:e0:00:2e:4c

[Link]
Name=wan
```
`/etc/systemd/network/wan.network`
```ini
[Match]
Name=wan

[Network]
Address=192.168.178.100/24
Gateway=192.168.178.1
DHCP=ipv6
DHCPPrefixDelegation=yes
IPv6AcceptRA=yes

[DHCPv6]
PrefixDelegationHint=::/62

[DHCPPrefixDelegation]
UplinkInterface=:self
SubnetId=0x0
Announce=no
```
`/etc/systemd/network/10-lan.link`
```ini
[Match]
PermanentMACAddress=a8:b8:e0:00:2e:4b

[Link]
Name=lan
```
`/etc/systemd/network/lan.network`
```ini
[Match]
Name=lan

[Network]
Address=192.168.0.1/24
IPv6SendRA=yes
IPv6AcceptRA=no
DHCPPrefixDelegation=yes

[DHCPPrefixDelegation]
UplinkInterface=wan
SubnetId=0x1
Announce=yes
```

These configurations (minus the ipv4 address/gateway assignments) match the example in the manpage.

### Additional program output to the terminal or log subsystem illustrating the issue

Log of `systemctl [re]start systemd-networkd` with SYSTEMD_LOG_LEVEL=debug set:
https://gist.github.com/LunarLambda/1a42ddd5c425955768aa3d64b22787b3

**Comment by yuwata** [comment] 2024-09-02 17:27
You can see, the .network files you provided are not used. But, 90-lan.network and 90-wan.network are used. These can be also confirmed by `networkctl status lan` and `networkctl status wan`.

**Comment by yuwata** [comment] 2024-09-02 17:31
Closing, this should be mostly caused by misconfiguration.
Feel free to request to reopen, still delegation does not work even if expected .network files used.

**Closed as completed by yuwata** 2024-09-02 17:31 UTC
Labels: network, needs-reporter-feedback ❓, not-a-bug

**Comment by LunarLambda** [comment] 2024-09-02 17:33
> You can see, the .network files you provided are not used. But, 90-lan.network and 90-wan.network are used. These can be also confirmed by `networkctl status lan` and `networkctl status wan`.
> 
> As suggested [systemd.network(5)](https://www.freedesktop.org/software/systemd/man/latest/systemd.network.html#Description), each .network files should prefixed with a number.

Could you briefly explain why? Does networkd not read files without a numeric prefix at all? Or does it try to read the prefixless ones first?

**Comment by yuwata** [comment] 2024-09-02 18:00
Please read the linked man page.
> The .network files are read from the files located in the system network directories /usr/lib/systemd/network and /usr/local/lib/systemd/network [[1]](https://www.freedesktop.org/software/systemd/man/latest/systemd.network.html#ftn.usr-local-footnote), the volatile runtime network directory /run/systemd/network and the local administration network directory /etc/systemd/network. All configuration files are collectively sorted and processed in alphanumeric order, regardless of the directories in which they live. However, files with identical filenames replace each other. It is recommended that each filename is prefixed with a number smaller than "70" (e.g. 10-eth0.network). Otherwise, the default .network files or those generated by [systemd-network-generator.service(8)](https://www.freedesktop.org/software/systemd/man/latest/systemd-network-generator.service.html#) may take precedence over user configured files. Files in /etc/ have the highest priority, files in /run/ take precedence over files with the same name under /usr/.

**Comment by LunarLambda** [comment] 2024-09-03 06:44
Renaming the `.network` files to have a `90-` prefix did indeed make it work. Thank you for your help
