### ISSUE TITLE
Intermittent failure resolving CNAMEd hosts

### ISSUE THREAD

**Issue by smurfix** [systemd/systemd#9690] opened 2018-07-22 16:54 UTC
**systemd version the issue has been seen with**
235, 239

**Used distribution**
debian

**Expected behaviour you didn't see**
api.tumblr.com is always resolved correctly

**Unexpected behaviour you saw**
```
$ while resolvectl query api.tumblr.com ; do sleep 1 ; done
[ heaps of of successful lookups ]
api.tumblr.com: resolve call failed: Lookup failed due to system error: Invalid argument
```

As the error happens, there are two lookups to api.tumblr.com (A and AAAA). Both succeed, returning the CNAME this record points to plus the associated IP4/IP6 address. I verified this with wireshark.

**Steps to reproduce the problem**
see above.

NB: I could not reproduce this with a non-CNAME RR.

**Comment by smurfix** [comment] 2018-09-13 09:01
*Ping* any ideas / progress / whatever on this?

**Comment by yuwata** [comment] 2018-09-13 09:06
I cannot reproduce this with recent snapshot. I only get the following result.
```
api.tumblr.com: 119.161.4.42
                119.161.4.40
                (edge2.gycs.b.yahoodns.net)

-- Information acquired via protocol DNS in 664.0ms.
-- Data is authenticated: no
```

**Comment by smurfix** [comment] 2018-09-13 09:09
Thanks for the feedback.

I will compile a recent snapshot and try to reproduce.

**Comment by smurfix** [comment] 2018-09-13 11:32
Reproducible with current snapshot, requiring ~150 to 300 passes through this loop:
```
$ while resolvectl query api.tumblr.com ; do sleep 0.1 ; done
api.tumblr.com: 87.248.118.25
                87.248.118.24
                2a00:1288:80:800::8001
                2a00:1288:80:800::8000
                (edge2.gycs.b.yahoodns.net)

-- Information acquired via protocol DNS in 2.7ms.
-- Data is authenticated: no
[the above is repeated … but then:]
api.tumblr.com: resolve call failed: Lookup failed due to system error: Invalid argument
```
My resolv.conf points to a standard (remote) bind9 instance.

**Comment by yuwata** [comment] 2018-09-13 13:18
Hmm, I will try to do again. I've just done only ~30 trials.

Could you paste debugging logs around the failure?

**Comment by smurfix** [comment] 2018-09-13 16:30
I have captured a "good" and a "bad" run with strace.

https://gist.github.com/smurfix/12f7431a107c16943d008561c510ca41

If you need more / anything else, let me know.

**Comment by tmccombs** [comment] 2019-05-07 20:21
I am also encountering this with systemd 242 on archlinux. I usually get it for duckduckgo.com, although I've also seen it happen for google.com, github.com, and stackoverflow.com. 

I've found that when it happens, restarting systemd-resolved usually fixes it. (Although in at least one case it eventually recovered on its own). 

From `systemd-resolve` I got the following error while in this state:

resolve call failed: CNAME loop detected, or CNAME resolving disabled on 'safe.duckduckgo.com'

**Comment by tmccombs** [comment] 2019-05-08 05:23
Since posting that last comment, this has started happening much more frequently.

**Comment by smurfix** [comment] 2019-05-08 05:54
The problem happens at the instant the DNS record times out of the cache, so you can reproduce it easily by hammering `resolved` with requests until that happens. duckduckgo and github, for instance, time out after a minute. api.tumblr.com's CNAME is set to expire after 30 seconds.

**Comment by keszybz** [comment] 2020-04-20 16:04
I can't reproduce this. I've been running `while resolvectl query api.tumblr.com ; do sleep 0.1 ; done` in a loop for a couple of hours with no failure. Removing the sleep or adding `sudo resolvectl flush-caches` in a parallel loop also doesn't make a difference.

**Comment by keszybz** [comment] 2020-04-20 16:07
If someone can reproduce this, a log from systemd-resolved with debug logging turned on would be useful.

**Comment by eduarrrd** [comment] 2020-08-11 14:52
Currently happening to me.

Version:
```
$ /lib/systemd/systemd-resolved --version
systemd 246 (246)
+PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

Invocation (anonymized):
```
$ resolvectl query target.subd.sub.d.tld
target.subd.sub.d.tld: resolve call failed: Lookup failed due to system error: Invalid argument
```

Log:
```
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Got message type=method_call sender=:1.2716 destination=org.freedesktop.resolve1 path=/org/freedesktop/resolve1 interface=org.freedesktop.resolve1.Manager member=ResolveHostname cookie=2 reply_cookie=0 signature=isit error-name=n/a error-message=n/a
Aug 11 16:35:02 myhostname systemd-resolved[117723]: idn2_lookup_u8: target.subd.sub.d.tld → target.subd.sub.d.tld
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Looking up RR for target.subd.sub.d.tld IN A.
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Looking up RR for target.subd.sub.d.tld IN AAAA.
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=203 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=GetNameOwner cookie=204 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.2643 path=n/a interface=n/a member=n/a cookie=105 reply_cookie=204 signature=s error-name=n/a error-message=n/a
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Cache miss for target.subd.sub.d.tld IN A
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Transaction 56429 for <target.subd.sub.d.tld IN A> scope dns on enp0s31f6/*.
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Using feature level UDP+EDNS0 for transaction 56429.
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Using DNS server 192.168.1.1 for transaction 56429.
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Sending query packet with id 56429.
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Cache miss for target.subd.sub.d.tld IN AAAA
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Transaction 51585 for <target.subd.sub.d.tld IN AAAA> scope dns on enp0s31f6/*.
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Using feature level UDP+EDNS0 for transaction 51585.
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Using DNS server 192.168.1.1 for transaction 51585.
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Sending query packet with id 51585.
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.2643 path=n/a interface=n/a member=n/a cookie=104 reply_cookie=203 signature=n/a error-name=n/a error-message=n/a
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Match type='signal',sender='org.freedesktop.DBus',path='/org/freedesktop/DBus',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0=':1.2716' successfully installed.
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Processing incoming packet on transaction 56429 (rcode=SUCCESS).
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Transaction 56429 for <target.subd.sub.d.tld IN A> on scope dns on enp0s31f6/* now complete with <success> from network (unsigned).
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Processing incoming packet on transaction 51585 (rcode=SUCCESS).
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Transaction 51585 for <target.subd.sub.d.tld IN AAAA> on scope dns on enp0s31f6/* now complete with <success> from network (unsigned).
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Freeing transaction 56429.
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Sent message type=error sender=n/a destination=:1.2716 path=n/a interface=n/a member=n/a cookie=205 reply_cookie=2 signature=s error-name=org.freedesktop.DBus.Error.InvalidArgs error-message=Lookup failed due to system error: Invalid argument
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RemoveMatch cookie=206 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Aug 11 16:35:02 myhostname systemd-resolved[117723]: Freeing transaction 51585.
```

For comparison:
```
$ dig @127.0.0.53 target.subd.sub.d.tld

; <<>> DiG 9.16.5 <<>> @127.0.0.53 target.subd.sub.d.tld
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29594
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;target.subd.sub.d.tld. IN      A

;; ANSWER SECTION:
target.subd.sub.d.tld. 0 IN     CNAME   subd.sub.d.tld.
subd.sub.d.tld. 0     IN      A       192.168.xxx.yyy

;; Query time: 4 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Tue Aug 11 16:49:42 CEST 2020
;; MSG SIZE  rcvd: 88
```

**Comment by bellpr** [comment] 2021-04-14 05:33
This is happening to me when trying to resolve `static-exp1.licdn.com` (static content for LinkedIn.com), which completely breaks the site. Example:
```
$ resolvectl query static-exp1.licdn.com
static-exp1.licdn.com: resolve call failed: CNAME loop detected, or CNAME resolving disabled on '<REDACTED>.trafficmanager.net'
```
But there is no loop. Performing the same query with `dig` reveals there's just a long chain of `CNAME` records (nine total) before the `A` records. The `resolvectl` query fails at the eighth `CNAME` record.

**Comment by smurfix** [comment] 2021-04-14 06:03
Eh. They've shortened the chain to six by now.

**Comment by bellpr** [comment] 2021-04-14 06:08
> Eh. They've shortened the chain to six by now.

If you are referring to LinkedIn, that may be true where you are located, but not in my location. CDN edge servers here have a very long chain. Regardless, there is no actual loop, so the lookup should not fail.

**Comment by poettering** [comment] 2021-04-14 08:34
the CNAME redirection limit has recently been bumped in e0ae456a554d0fce250f9a009c561b97f20c41f8.

I am pretty sure this is fixed in 248. If not, please file a new bug, and include the debug log of the offending lookup.

**Closed as completed by poettering** 2021-04-14 08:34 UTC
Labels: resolve

**Comment by paravz** [comment] 2021-04-15 22:58
Likely a reason for Microsoft teams not working when using systemd-resolved on Fedora 33, took a while to figure out

```
$  resolvectl query endpoint1-s03prdwuscompsvc.prd.bmc.cdn.office.net
endpoint1-s03prdwuscompsvc.prd.bmc.cdn.office.net: resolve call failed: CNAME loop detected, or CNAME resolving disabled on 'edge-prod-wstr3.ctrl.t-0001.trafficmanager.net'


$  dig endpoint1-s03prdwuscompsvc.prd.bmc.cdn.office.net @127.0.0.53

; <<>> DiG 9.11.28-RedHat-9.11.28-1.fc33 <<>> endpoint1-s03prdwuscompsvc.prd.bmc.cdn.office.net @127.0.0.53
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 32372
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;endpoint1-s03prdwuscompsvc.prd.bmc.cdn.office.net. IN A

;; Query time: 130 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Thu Apr 15 15:56:18 PDT 2021
;; MSG SIZE  rcvd: 78



$  dig endpoint1-s03prdwuscompsvc.prd.bmc.cdn.office.net @8.8.8.8

; <<>> DiG 9.11.28-RedHat-9.11.28-1.fc33 <<>> endpoint1-s03prdwuscompsvc.prd.bmc.cdn.office.net @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35404
;; flags: qr rd ra; QUERY: 1, ANSWER: 11, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;endpoint1-s03prdwuscompsvc.prd.bmc.cdn.office.net. IN A

;; ANSWER SECTION:
endpoint1-s03prdwuscompsvc.prd.bmc.cdn.office.net. 299 IN CNAME ep1-s03-prd-wus-cdn-office-bmc.trafficmanager.net.
ep1-s03-prd-wus-cdn-office-bmc.trafficmanager.net. 29 IN CNAME endpoint1-s03prdwuscompsvc-nativecdn.azureedge.net.
endpoint1-s03prdwuscompsvc-nativecdn.azureedge.net. 310 IN CNAME endpoint1-s03prdwuscompsvc-nativecdn.afd.azureedge.net.
endpoint1-s03prdwuscompsvc-nativecdn.afd.azureedge.net. 29 IN CNAME star-azureedge-prod.trafficmanager.net.
star-azureedge-prod.trafficmanager.net. 4 IN CNAME dual.t-0009.t-msedge.net.
dual.t-0009.t-msedge.net. 227   IN      CNAME   t-0009.t-msedge.net.
t-0009.t-msedge.net.    59      IN      CNAME   Edge-Prod-WSTr3.ctrl.t-0009.t-msedge.net.
Edge-Prod-WSTr3.ctrl.t-0009.t-msedge.net. 239 IN CNAME edge-prod-wstr3.ctrl.t-0001.trafficmanager.net.
edge-prod-wstr3.ctrl.t-0001.trafficmanager.net. 0 IN CNAME standard.t-0009.t-msedge.net.
standard.t-0009.t-msedge.net. 24 IN     A       13.107.246.19
standard.t-0009.t-msedge.net. 24 IN     A       13.107.213.19

;; Query time: 113 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Apr 15 15:56:24 PDT 2021
;; MSG SIZE  rcvd: 469
```

**Comment by TylerBrock** [comment] 2021-09-22 00:39
I'm experiencing the same issue with api.twilio.com which also has < 1 minute TTL:

```sh
$ while resolvectl query api.twilio.com --cache=false; do sleep 1; done;
-- Information acquired via protocol DNS in 1.1ms.
-- Data is authenticated: no; Data was acquired via local or encrypted transport: no
-- Data from: network
api.twilio.com: 34.227.179.12                  -- link: ens5
                (ien-l4-tcp-rest-api.us-east-1.api-lb.twilio.com)

-- Information acquired via protocol DNS in 1.3ms.
-- Data is authenticated: no; Data was acquired via local or encrypted transport: no
-- Data from: network
api.twilio.com: resolve call failed: Lookup failed due to system error: Invalid argument
```

As far as I can tell there is only three CNAMES in between us and the load balancer for api.twilio.com:

```sh
$ dig api.twilio.com

; <<>> DiG 9.16.21 <<>> api.twilio.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35852
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;api.twilio.com.                        IN      A

;; ANSWER SECTION:
api.twilio.com.         43      IN      CNAME   virginia.us1.api-lb.twilio.com.
virginia.us1.api-lb.twilio.com. 43 IN   CNAME   ien-l4-tcp-rest-api-b.us-east-1.api-lb.twilio.com.
ien-l4-tcp-rest-api-b.us-east-1.api-lb.twilio.com. 43 IN A 52.20.104.111

;; Query time: 0 msec
;; SERVER: 172.31.0.2#53(172.31.0.2)
;; WHEN: Tue Sep 21 20:36:36 EDT 2021
;; MSG SIZE  rcvd: 166
```

I can also attest to it seemingly corresponding to the exact moment when the record times out just like @smurfix has mentioned.

**Comment by TylerBrock** [comment] 2021-09-22 00:41
Would it be possible to reopen this issue @poettering? I do not think it is related to the CNAME redirection limit.

**Comment by net147** [comment] 2021-09-22 07:23
https://github.com/systemd/systemd/issues/20617 seems related
