### ISSUE TITLE
Escaping logic for paths containing hyphens is unaesthetic

### ISSUE THREAD

**Issue by eMPee584** [systemd/systemd#7899] opened 2018-01-16 15:53 UTC
Replacing hyphens with \x2d really messes with readability of unit names, for example mount units for `/dev/disk/by-label` paths.
Is there any practical use for the perfect unescapability? I'd rather have both slash and hyphen mapped to hyphens then scrambled unit names..

**Comment by yuwata** [comment] 2018-01-16 15:57
Seems a duplicate of #7692.

**Comment by poettering** [comment] 2018-01-22 10:08
> Is there any practical use for the perfect unescapability?

Yes, all across the codebase we make use of the fact that path names and unit names can be mapped to each other in a bijective way. For example, for mount units we use that in order to create implicit deps from a mount unit to its parent mount: as we know exactly how paths relate to each other and that maps to how unit names relate to each other we can safely derive the parent's unit name from every mount unif name.

So, yes. this is used all across the board and for good reasons (at least to my opinion good ones).

Sorry, but this nothing we can change at this point, already for compatibility reasons. I mean, I am all for cosmetic changes, but we have to consider the price in each case, and this one comes at a too heavy one for systemd's own logic.

Sorry!

**Closed as completed by poettering** 2018-01-22 10:08 UTC
Labels: escape

**Comment by eMPee584** [comment] 2018-10-09 15:55
thanks for explaining the point by the way.
Nevertheless, it's really unintuitive on first sight, and any more visually pleasing way of escaping slashes would be +awesome : )
