### ISSUE TITLE
cross compile failed:linux/capability.h: No such file or directory

### ISSUE THREAD

**Issue by lujfsd** [systemd/systemd#12717] opened 2019-06-01 07:49 UTC
**systemd version the issue has been seen with**
> V242

**Used distribution**
 > cross compile for imx6

**Expected behaviour you didn't see**
 > …

**Unexpected behaviour you saw**
 > 

1. [2/154] Generating cap-list.txt with a meson_exe.py custom command.
FAILED: src/basic/cap-list.txt 
/home/conn/.local/bin/meson --internal exe /home/conn/build_imx6/sdbus-cpp/build/libsystemd-v242/src/LibsystemdBuildProject-build/meson-private/meson_exe_generate-cap-list.sh_6563987603aacc426944d6703e38207043681c0b.dat
cc1: fatal error: linux/capability.h: No such file or directory

1. [1/154] Generating errno-from-name.h with a meson_exe.py custom command.
FAILED: src/basic/errno-from-name.h 
/home/conn/.local/bin/meson --internal exe /home/conn/build_imx6/sdbus-cpp/build/libsystemd-v242/src/LibsystemdBuildProject-build/meson-private/meson_exe_gperf_4ac85487c0adbfd3c5a5ba2a4b57711d39b496f4.dat
src/basic/errno-from-name.gperf: No keywords in input file!

This is build log file
[LibsystemdBuildProject-build-out.log](https://github.com/systemd/systemd/files/3243540/LibsystemdBuildProject-build-out.log)

**Steps to reproduce the problem**
`1.meson --buildtype=release --cross-file=imx6_cross.txt -Dstatic-libsystemd=pic`
`2.meson version.h`
`3.meson libsystemd.a`

this is cross file:[imx6_cross .txt](https://github.com/systemd/systemd/files/3243541/imx6_cross.txt)

> [binaries]                   
c = '/opt/fsl-framebuffer/2.4.4/sysroots/x86_64-fslsdk-linux/usr/bin/arm-fsl-linux-gnueabi/arm-fsl-linux-gnueabi-gcc'
cpp = '/opt/fsl-framebuffer/2.4.4/sysroots/x86_64-fslsdk-linux/usr/bin/arm-fsl-linux-gnueabi/arm-fsl-linux-gnueabi-g++'                     
ar = '/opt/fsl-framebuffer/2.4.4/sysroots/x86_64-fslsdk-linux/usr/bin/arm-fsl-linux-gnueabi/arm-fsl-linux-gnueabi-ar'                       
strip = '/opt/fsl-framebuffer/2.4.4/sysroots/x86_64-fslsdk-linux/usr/bin/arm-fsl-linux-gnueabi/arm-fsl-linux-gnueabi-strip'                 
pkgconfig = '/opt/fsl-framebuffer/2.4.4/sysroots/x86_64-fslsdk-linux/usr/bin/pkg-config' 
\
[host_machine]               
system = 'linux'             
cpu_family = 'arm'           
cpu = 'cortex-a9'            
endian = 'little'      
  \
[build_machine]              
system = 'linux'             
cpu_family = 'x86_64'        
cpu = 'i686'   
\
[properties]
c_args = ['-march=armv7-a','-marm','-mfpu=neon','-mfloat-abi=hard','-mcpu=cortex-a9','--sysroot=/opt/fsl-framebuffer/2.4.4/sysroots/cortexa9hf-neon-fsl-linux-gnueabi']
c_link_args = ['--sysroot=/opt/fsl-framebuffer/2.4.4/sysroots/cortexa9hf-neon-fsl-linux-gnueabi','-mfloat-abi=hard']
\
[paths]
prefix = '/home/conn/build_imx6/install/'
libdir = 'lib'
bindir = 'bin'

Can someone help me? 
Thanks!

**Comment by lujfsd** [comment] 2019-06-03 06:58
Using the patch below, I got the expected results。close this issue。
``` diff --git a/meson.build b/meson.build
index 79195c9..7fcab71 100644
--- a/meson.build
+++ b/meson.build
@@ -409,7 +409,22 @@ if cc.compiles('''
         add_project_arguments('-Werror=shadow', language : 'c')
 endif
-cpp = ' '.join(cc.cmd_array()) + ' -E'
+cpp = ' '.join(cc.cmd_array()) + ' -E '
+
+if meson.is_cross_build()
+	c_args = [
+		'-march=armv7-a',
+		'-marm',
+		'-mfpu=neon',
+		'-mfloat-abi=hard',
+		'-mcpu=cortex-a9',
+		'--sysroot=/opt/fsl-framebuffer/2.4.4/sysroots/cortexa9hf-neon-fsl-linux-gnueabi',
+		'-I/opt/fsl-framebuffer/2.4.4/sysroots/cortexa9hf-neon-fsl-linux-gnueabi/usr/include/',
+	]
+	cpp += ' '.join(c_args)
+endif
+
+message('Test cpp @0@'.format(cpp))
```

**Comment by yuwata** [comment] 2019-06-03 07:05
Is it not possible to do that in your cross file?

**Comment by lujfsd** [comment] 2019-06-03 07:18
> Is it not possible to do that in your cross file?

Hi,as you see , in my cross file has contain it. But in meson.build file ，i can't get it.

I try [meson.build cpp variable is created without specified cpp_args from properties (cross compiling)issue#10288](https://github.com/systemd/systemd/issues/10288#issue-367171697) , but dons't worked.

**Comment by yuwata** [comment] 2019-06-03 07:23
Ah, I see. Thanks for the reference. This seems to be duplicate of #10288. Let's close this.

If you find general fix for the issue, then please submit as a PR. Thank you.

**Closed as completed by yuwata** 2019-06-03 07:23 UTC
Labels: duplicate, meson

**Comment by lujfsd** [comment] 2019-06-03 07:27
Ok , i will if i find it.
