### ISSUE TITLE
allow user units to depend on system units

### ISSUE THREAD

**Issue by xenoterracide** [systemd/systemd#20249] opened 2021-07-19 15:27 UTC
**Is your feature request related to a problem? Please describe.**

So I'm setting up timers to update some of my user-only installed software. I realized that in order to perform the update, I wanted the network to be available. a little research shows me that I want the `network-online.target`, well fun story, that's a system target and you can't use those in user targets.

```
Starting zinit update...
fatal: unable to access 'https://github.com/zdharma/zinit/': Could not resolve host: github.com
Compiling Zinit (zcompile){…}
^MReloading Zinit for the current session{…}

zinit-update.service: Deactivated successfully.
Finished zinit update.
Starting zinit update...
From https://github.com/zdharma/zinit
 * branch              master     -> FETCH_HEAD
Compiling Zinit (zcompile){…}
^MReloading Zinit for the current session{…}

zinit-update.service: Deactivated successfully.
Finished zinit update.
```

**Describe the solution you'd like**

I feel like this, or something like this should work. maybe `system:network-online.target` as namepsacing...

```ini
[Unit]
Description=zinit update
Documentation=https://github.com/zdharma/zinit
Requires=network-online.target

[Service]
Type=oneshot
ExecStart=zsh --singlecommand -c 'zinit self-update'
```

**Describe alternatives you've considered**

I'm pretty certain I can just copy (or link?) some of the system definitions into my user definitions, still, not ideal IMO.

**note**

to be fair it does look like the network manager implementation is bad at keeping network-online up to date. Not sure who provides that.

**Comment by keszybz** [comment] 2021-07-23 09:47
The problem is that the system manager state is completely independent of the user manager state. So there is no obvious way to share the state of units from one to the other. But I think something like this would be useful in case on network-online.target and time-sync.target. I'm not sure if there are any other similar units.

We would need to some way to have a user unit that would simply mirror the state of the system unit.

**Comment by xenoterracide** [comment] 2021-07-23 14:06
maybe auto-create a copy in the user bus, and propagate via dbus? I don't know, I don't fully understand how it all works ;)

**Comment by dtardon** [comment] 2021-07-26 11:55
This is a duplicate of #3312.

**Comment by poettering** [comment] 2021-07-29 13:18
Closing as duplicate

**Closed as completed by poettering** 2021-07-29 13:18 UTC
Labels: RFE 🎁, pid1, duplicate
