### ISSUE TITLE
systemctl set-property could not include single quotes ' '

### ISSUE THREAD

**Issue by opensourcesharing** [systemd/systemd#35754] opened 2024-12-25 17:40 UTC
### systemd version the issue has been seen with

252.x

### Used distribution

AlmaLinux 9.5

### Linux kernel version used

5.14.0-503.16.1.el9_5.x86_64

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

systemctl set-property name.service ExecStart=-/path/to/command -o '-b -c -- root' 

### Unexpected behaviour you saw

systemctl set-property name.service ExecStart=-/path/to/command -o '-b -c -- root' 
Unknown output '-b -c -- root'

**Comment by YHNdnzj** [comment] 2024-12-25 19:59
Please quote the whole value field (after `=`) so that it's passed as a single argument. Plus, note that ExecStart is not a property that supports runtime modification, and hence cannot be used in `set-property`.

Not a bug, closing.

**Closed as not planned by YHNdnzj** 2024-12-25 19:59 UTC
Labels: systemctl, not-a-bug
