### ISSUE TITLE
`systemctl reboot` doesn’t save the bash history

### ISSUE THREAD

**Issue by fbruetting** [systemd/systemd#9749] opened 2018-07-29 12:45 UTC
**systemd version the issue has been seen with**
> 238

**Used distribution**
 > Fedora 28 SB

**Expected behaviour you didn't see**
 > After `systemctl reboot`, the used commands should be in the bash history.

**Unexpected behaviour you saw**
 > The history doesn’t get saved, at rebooting the system via this method.

**Steps to reproduce the problem**
> Enter a few commands, enter `systemctl reboot`, look if the commands are listed by the bash history.

**Comment by kirbyfan64** [comment] 2018-07-29 19:14
Pretty sure this is a bash issue and has nothing to do with systemd...

**Comment by filbranden** [comment] 2018-07-29 22:02
I noticed that too.

I'm not so sure this is purely a bash issue, since if it was terminated properly and at the right time (before filesystems are made read-only, etc.) it would have had time to flush its history to the `.bash_history` file...

If it's indeed an issue with bash, I think we should at least figure out what it would have to do differently to do this correctly and why.

Do other shells (zsh?) have the same issue? (That might give a hint on whether this is bash or not...)

**Comment by floppym** [comment] 2018-07-30 02:34
bash ignores SIGTERM if there is a child process running in the foreground. Perhaps bash is being sent SIGTERM before systemctl exits and the child process is reaped. It would then be killed via SIGKILL instead, which gives it no opportunity to complete any cleanup tasks like writing to the history file.

**Comment by floppym** [comment] 2018-07-30 02:38
The bash manual actually states that interactive shells always ignore SIGTERM, but this does not seem to be the case in testing on my system.

https://www.gnu.org/software/bash/manual/html_node/Signals.html

**Comment by boucman** [comment] 2018-07-30 08:18
systemd has an option to explicitely send a SIGPIPE with the SIGTERM for shells... maybe it is not set/forwarded properly to your shell ?

**Comment by poettering** [comment] 2018-07-30 10:41
How do you start your shell? is that a console login? ssh login? x11/wayland login?

**Comment by fbruetting** [comment] 2018-07-30 11:10
Just via my dock on Wayland. I’ll check this with `zsh` and `sudo reboot`…

**Comment by poettering** [comment] 2018-07-30 11:16
and how is that "dock on wayland" started? gnome-session?

What most likely happens is that the shell is not terminated correctly through SIGHUP, but through SIGKILL or something like that. Question is why, hence it matters what the execution environment precisely is. Is this run from a systemd --user instance? Or maybe a console login upgraded to graphical? what precisely is the codepath here?

**Comment by fbruetting** [comment] 2018-07-30 11:23
Yes, I think so (that’s the single most useful shell extension). I could also click Gnome Termianl or Tilix via the app launcher – that wouldn’t change anything.

It’s the same with `sudo reboot`, but I can’t try `zsh` right now, is I don’t have my config file which sets up the history and am pretty busy right now, but I can check that next week. Maybe @filbranden is right and it’s due to the Silverblue-ish stuff. Could anyone test on a regular Fedora system?

**Comment by fbruetting** [comment] 2018-08-31 12:41
So I tried this on a regular (non-ostreed) Fedora 28 machine and the problem is the same.

**Comment by mrc0mmand** [comment] 2023-12-13 19:22
Closing since the issue is quite old and doesn't appear to be a systemd issue. If the issue still persists, please feel free to reopen the issue with the necessary information.

**Closed as not planned by mrc0mmand** 2023-12-13 19:22 UTC
Labels: needs-reporter-feedback ❓
