### ISSUE TITLE
please consider adding a possibliity to configure null routes

### ISSUE THREAD

**Issue by Zugschlus** [systemd/systemd#967] opened 2015-08-15 09:26 UTC
Hi,

in networking, it is common to "anchor" a supernetwork in a null route to avoid routing loops. The actually used networks get a more specific route. For example, a common setup would be:

[Route]
Gateway=unreachable
Destination=2001:db8:1:1000::/60

[Route]
Gateway=2001db8:1:1001::1
Destination=2001:db8:1:1002::/64

This is currently not possible because systemd-networkd does not recognize the "unreachable" keyword (and none of the other keywords I tried).

If this is already possible, please document in systemd.network(5) how to do this. If it is not possible, please implement.

Greetings
Marc

[1] "ip route" uses "unreachable" to express a null route, cisco gear usually uses "Null0".

**Comment by poettering** [comment] 2015-08-16 12:30
Makes sense to add I guess.

**Comment by Mic92** [comment] 2015-08-21 09:42
If somebody implements this feature, it might be worth to add "blackhole" routes as well, which just drop the packets instead of sending ICMP unreachable.

**Comment by poettering** [comment] 2016-04-18 12:24
This is actually a duplicate of #797. Closing.

**Closed as completed by poettering** 2016-04-18 12:24 UTC
Labels: RFE 🎁, network, duplicate
