### ISSUE TITLE
VRF devices added, but not brought up

### ISSUE THREAD

**Issue by halvors** [systemd/systemd#4308] opened 2016-10-08 00:05 UTC
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> systemd 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Ubuntu
### In case of bug report: Expected behaviour you didn't see

> …
### In case of bug report: Unexpected behaviour you saw

> vrf1: <NOARP,MASTER> mtu 65536 qdisc noop state DOWN mode DEFAULT group default qlen 1000
### In case of bug report: Steps to reproduce the problem

> Add a VRF device and try to pass traffic thru.

**Comment by poettering** [comment] 2016-11-23 23:48
@andir, any idea?

**Comment by andir** [comment] 2016-11-26 15:11
I can confirm the issue with the interface being down. I believe it was working (as in routing) when I submitted the PR. I've to invest a bit more time to figure out why the link isn't being set up.

**Comment by ssahani** [comment] 2016-12-22 06:56
Please try with  . This should bring up the device.

```
# cat vrf1.network
[Match]
Name=vrf-test
```

```
5: vrf-test: <NOARP,MASTER,UP,LOWER_UP> mtu 65536 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 2a:eb:fa:8f:c4:d4 brd ff:ff:ff:ff:ff:ff
```

**Comment by ssahani** [comment] 2017-07-12 11:44
Since VRF can be up by the prev conf we can close this issue.

**Comment by keszybz** [comment] 2017-07-12 13:14
@ssahani the example you pasted is just the .network stub. Can you paste the whole thing with .netdev and all?

**Comment by ssahani** [comment] 2017-07-12 14:05
@keszybz it's in the examples
~~~
[NetDev]                                                                                                                                                                                       
Name=vrf-test                                                                                                                                                                                  
Kind=vrf                                                                                                                                                                                       
                                                                                                                                                                                               
[VRF]                                                                                                                                                                                          
TableId=42 
```

**Comment by andir** [comment] 2017-08-31 00:31
So, I looked at this again and can confirm that VRFs are `DOWN` per default. The behaviour is actually the same as with bridges and similar devices as far as I can tell.

I guess it would make sense to force the netdev into `UP` state when it's kind is VRF.

The easiest workaround for this would be shipping a `90-vrf.network` default file like this:
```
[Match]
Driver=vrf
```

This will then force all VRFs into `UP` state. 

I've created a PR to address this.

**Comment by afics** [comment] 2018-03-08 13:19
Adding a `.network` file as suggested by @ssahani does bring the interface up but leaves it in `configuring`  in `networkd` state despite it having carrier.

I have confirmed this behaviour on both archlinux and Fedora 27. `systemctl --version` for both of those:
```
systemd 238
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN +PCRE2 default-hierarchy=hybrid

systemd 234
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid
```

Do you want me to open a new bug report?

**Comment by keszybz** [comment] 2018-03-08 13:34
No solution for this was merged, and this bug is still open.

**Comment by poettering** [comment] 2018-05-24 11:14
Let's close this issue here. It is by design that .netdev only creates network devices, and .network should the configure it. If the issue with not progressing beyond "configuring" is still there, please open a new bug for it.

**Closed as completed by poettering** 2018-05-24 11:14 UTC
Labels: network
