### ISSUE TITLE
systemd-networkd static network hangs in routable (pending) state, systemd-resolved never gets DNS

### ISSUE THREAD

**Issue by j0057** [systemd/systemd#34751] opened 2024-10-13 13:58 UTC
### systemd version the issue has been seen with

systemd-256.5-2ubuntu3

### Used distribution

Ubuntu 24.10 (Oracular)

### Linux kernel version used

6.11.0-8-generic

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd, systemd-resolved

### Expected behaviour you didn't see

For this network in a Qemu VM:

        [Match]
        Type=ether
        [Network]
        Address=172.23.49.12/24
        Gateway=172.23.49.254
        DNS=172.23.2.1

The address and gateway get configured properly, but the DNS setting is never picked up and the network status stays 'pending'.
    
Here are debug logs of systemd-networkd and systemd-resolved: https://gist.github.com/j0057/b941302c196c8db8c833fdefde1f5013

### Unexpected behaviour you saw

The `networkctl status enp0s2` never goes beyond 'pending':

    ● 2: enp0s2
                       Link File: n/a
                    Network File: n/a
                           State: routable (pending)
                    Online state: unknown
                            Type: ether
                Hardware Address: 02:00:ac:17:31:0c
                             MTU: 1500 (min: 68, max: 65535)
                           QDisc: pfifo_fast
    IPv6 Address Generation Mode: eui64
        Number of Queues (Tx/Rx): 1/1
                Auto negotiation: no
                         Address: 172.23.49.12
                                  fe80::acff:fe17:310c
                         Gateway: 172.23.49.254
    
And `resolvectl status` never shows it received the configured DNS server:

    Global
             Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
      resolv.conf mode: stub
    
    Link 2 (enp0s2)
        Current Scopes: none
             Protocols: -DefaultRoute -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

**Comment by yuwata** [comment] 2024-10-13 15:22
Hm? That suggests /run/udev/data/n2 does not exist. Please check.

**Comment by j0057** [comment] 2024-10-13 16:36
I checked, udev was not installed, and installing it fixes the problem. I take it the relevant log line was:

    enp0s2: link pending udev initialization...

Should I file a bug with downstream Ubuntu, to ask if udev can be added as a dependency of the systemd-resolved package? I mean, it looks like systemd-resolved can't work well if udev is not available.

**Comment by yuwata** [comment] 2024-10-13 16:59
Not familiar with ubuntu packaging policies, but networkd and resolved can work on container, but udev is not necessary on container. So, packages for networkd and resolved should not depend on udev, in general. Otherwise, container images get unnecessary udev package.

Anyway, this is not a bug, at least in upstream. Closing.

**Closed as not planned by yuwata** 2024-10-13 16:59 UTC
Labels: udev, network, not-a-bug
