### ISSUE TITLE
Allow systemd.timer restart an active unit

### ISSUE THREAD

**Issue by rfrail3** [systemd/systemd#22200] opened 2022-01-21 09:17 UTC
**Is your feature request related to a problem? Please describe.**
If you want to replace a cron task that restarts a running service, you can't replace it with one .timer file. That's because, as the [documentation](https://www.freedesktop.org/software/systemd/man/systemd.timer.html) points "_in case the unit to activate is already active at the time the timer elapses it is not restarted, but simply left running._"

**Describe the solution you'd like**
A new option on the .timer definition, like for example "`AllowRestart=`" to give the chance to the user to restart an already active unit.

**Describe alternatives you've considered**
Now, you need to create a `foo-schedule.timer `to fire up` foo-schedule.service` at specific time and restart `foo.service`.

**The systemd version you checked that didn't have the feature you are asking for**
250.3

**Comment by poettering** [comment] 2022-01-28 13:28
Duplicate of #17705

**Closed as completed by poettering** 2022-01-28 13:28 UTC
Labels: RFE 🎁, pid1, duplicate
