### ISSUE TITLE
[Regression] #10787 prevents system from booting

### ISSUE THREAD

**Issue by Keruspe** [systemd/systemd#10854] opened 2018-11-20 13:58 UTC
**systemd version the issue has been seen with**
> Current git master HEAD

**Used distribution**
 > Exherbo

**Expected behaviour you didn't see**
 > System boots as usual

**Unexpected behaviour you saw**
 > System waits forever for `/dev/mapper/root`

**Steps to reproduce the problem**

My disk is encrypted using cryptsetup. `/dev/mapper/root` contains a btrfs filesystem, which contains the subvolume which is mounted on my / and others.
Within dracut, everything works as expected, but after the switch root, when systemd tries to mount all the things from fstab, it just waits forever for `/dev/mapper/root` to be ready.
Passing `systemd.unit=emergency.target` and then running `systemctl start default.target` from the emergency shell sometimes works around this (`/dev/mapper/root` exists).

Rolling back to the previous merge (278939be7a8eb07c696b3601cb63522d252b7291) fixes the issue, master is broken since 4874191d9d766093f92059cbc0724bf2a25f6460 which is the merge commit of #10787

**Comment by yuwata** [comment] 2018-11-20 14:44
Hmm? Could you show what unit fails?

**Comment by yuwata** [comment] 2018-11-20 14:45
Are there any softwares depends on our not-exported functions?

**Comment by yuwata** [comment] 2018-11-20 14:48
Or, do you have any chance to rebuild your initramfs? That is, could you run `drucut` to rebuild your initramfs?

**Comment by Keruspe** [comment] 2018-11-20 14:51
I should have mentioned it, but I have regenerated the initramfs.
As I said, everything works fine in the initramfs part, it's in really early boot, when mounting the filesystems (all of them are subvolumes of the btrfs filesystem in `/dev/mapper/root`), after the switch root that it gets stuck.

After some more digging, reverting 5ea78a39e5894297d59ea75b30e250d24bbfc6aa (and fixing the trivial conflicts) solves the problem

**Comment by yuwata** [comment] 2018-11-20 14:54
Ah,,, could you provide logs about coredumps or similar?

**Comment by Keruspe** [comment] 2018-11-20 15:02
No sign of coredump (well, at least coredumpctl doesn't list any, and I didn't see any alarming message in this regard).

I might have an idea, testing it now

**Comment by Keruspe** [comment] 2018-11-20 15:05
@yuwata inspired by the former macro (before the faulty patch) ^

This fixes my problem

**Comment by yuwata** [comment] 2018-11-20 15:12
Oh, thanks. I will take a look.

**Comment by yuwata** [comment] 2018-11-20 17:54
I've proposed a cleanup for libudev-list in #10861. I am not sure that fixes this issue. But I hope it does.

**Comment by Keruspe** [comment] 2018-11-20 21:18
@yuwata It does indeed fix my problem

**Comment by yuwata** [comment] 2018-11-21 03:17
BTW, are there any chance to boot the system with `udev.children_max=1` without the above PRs? Now I am thinking about this may be a duplicate of #10754.

**Comment by Keruspe** [comment] 2018-11-21 09:51
@yuwata indeed, seems to work too (actually I applied #10865 to test that, as it seemed to do the same and it's easier for me to just apply patches)

**Comment by yuwata** [comment] 2018-11-21 10:34
Ah, thank you for testing the PR.

**Comment by yuwata** [comment] 2018-11-21 10:46
So, I have labeled this issue 'duplicate'. And let's, at least tentatively, close this. Let's discuss at #10754.

**Closed as completed by yuwata** 2018-11-21 10:46 UTC
Labels: bug 🐛, udev, regression ⚠️, duplicate
