### ISSUE TITLE
initrd-switch-root.service: Current command vanished from the unit file, execution of the command list won't be resumed.

### ISSUE THREAD

**Issue by mabod** [systemd/systemd#15699] opened 2020-05-05 05:37 UTC
**systemd version the issue has been seen with**
systemd 245.5-2

**Used distribution**
Manjaro Testing

**Expected behaviour you didn't see**
I would expect no warning/error message in the log

**Unexpected behaviour you saw**
Warning/error message in the log saying:

```
systemd[1]: initrd-switch-root.service: Current command vanished from the unit file, execution of the command list won't be resumed.
```

```
45# pacman -Qo /usr/lib/systemd/system/initrd-switch-root.service
/usr/lib/systemd/system/initrd-switch-root.service is owned by systemd 245.5-2
```

```
41# systemctl cat initrd-switch-root.service 
# /usr/lib/systemd/system/initrd-switch-root.service
#  SPDX-License-Identifier: LGPL-2.1+
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Switch Root
DefaultDependencies=no
ConditionPathExists=/etc/initrd-release
OnFailure=emergency.target
OnFailureJobMode=replace-irreversibly
AllowIsolate=yes

[Service]
Type=oneshot
ExecStart=systemctl --no-block switch-root /sysroot
```

**Comment by poettering** [comment] 2020-05-05 06:35
Is it possible that manjaro changes/extends that service in its initrd? can you ping the manjaro devs about this?

**Comment by mabod** [comment] 2020-05-05 07:12
I have created a thread in the Manjaro forum about this topic and asked that question to @philmmanjaro 

I need to mention that I also see that error during boot for the plexmediaserver:

`systemd[1]: plexmediaserver.service: Current command vanished from the unit file, execution of the command list won't be resumed.`

When I stop/start plex while the system is up and running I do not not see that error. It is only during boot.

```
65# systemctl cat plexmediaserver.service 
# /usr/lib/systemd/system/plexmediaserver.service
[Unit]
Description=Plex Media Server
After=network.target

[Service]
EnvironmentFile=/etc/conf.d/plexmediaserver
ExecStart=/usr/lib/plexmediaserver/Plex\x20Media\x20Server
Type=simple
User=plex
Group=plex
Restart=on-failure
RestartSec=5
StartLimitInterval=60s
StartLimitBurst=3

[Install]
WantedBy=multi-user.target
```

**Comment by ssahani** [comment] 2020-05-05 08:55
As @poettering  said  including binary and confs should solve 
```
#cat /etc/dracut.conf.d/my.conf
install_items+=" /usr/bin/your-bin" 

#dracut -v -f
```

**Comment by mabod** [comment] 2020-05-05 11:00
Is that a question for me? I do not understand your comment.
And I am not using dracut.

**Comment by mabod** [comment] 2020-05-06 05:25
I tested more and found that it has to do with the initrd hooks I am using.

I am using:
`HOOKS=(base systemd autodetect modconf block keyboard sd-vconsole filesystems fsck)`
and this causes the error message. 

The default Manjaro hooks are:
`HOOKS=(base udev autodetect modconf block filesystems keyboard fsck)`
With that I do not see the error. 

So it is the `systemd` hook which is causing the issue.

**Comment by DaanDeMeyer** [comment] 2020-05-07 16:26
I can confirm I'm seeing the same issue on a base Arch Linux machine. I'm also using the systemd hook instead of base/udev.

**Comment by DaanDeMeyer** [comment] 2020-06-01 19:53
I added some extra logging to `service_deserialize_exec_command`:

```
/* Let's check whether exec command on given offset matches data that we just deserialized */
        for (command = s->exec_command[id], i = 0; command; command = command->command_next, i++) {
                if (i != idx)
                        continue;

                log_warning("%s == %s && %s == %s", strv_join(argv, NULL), strv_join(command->argv, NULL), command->path, path);

                found = strv_equal(argv, command->argv) && streq(command->path, path);
                break;
        }
```

With this addition and after booting with mkosi in qemu, both `path` and `argv` contain the path `/usr/local/bin/systemctl` while `command->path` and `command->argv` contain `/usr/bin/systemctl`. initrd-switch-root contains an `ExecStart` line containing `systemctl` (without a path prefix).

Dissecting the initramfs, `/usr/local/bin` is a symlink to `/usr/bin` so I'm guessing systemd is resolving symlinks for `command->path` but isn't resolving symlinks for `path`.

Now to figure out why /usr/local/bin is symlinked to /usr/bin by mkinitcpio in the first place. This might still be something we should fix on our side though.

**Comment by mabod** [comment] 2020-06-17 11:13
Issue https://github.com/systemd/systemd/issues/16076

Contains the solution for me: Add fullpath to the `systemctl` call in `initrd-switch-root.service`
A new `initramfs` has to be created after that and the message is gone.

**Comment by frostworx** [comment] 2020-06-18 07:45
I can confirm that 
`ExecStart=/usr/bin/systemctl --no-block switch-root /sysroot`
instead of
`ExecStart=systemctl --no-block switch-root /sysroot`
fixes the issue.
interesting though that this only is successful, when you edit the line directly in
`/usr/lib/systemd/system/initrd-switch-root.service`
 a
`/etc/systemd/system/initrd-switch-root.service.d/fix.conf`
with
```
[Service]
ExecStart=
ExecStart=/usr/bin/systemctl --no-block switch-root /sysroot
```
doesn't fix it though

**Comment by poettering** [comment] 2020-08-06 22:27
Duplicate of #16076

**Closed as completed by poettering** 2020-08-06 22:27 UTC
Labels: pid1, duplicate
