### ISSUE TITLE
Add a specifier for FQDN

### ISSUE THREAD

**Issue by Toniob** [systemd/systemd#9953] opened 2018-08-27 15:16 UTC
Hi,

There are already several specifiers for systemd units : https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Specifiers . Will it be possible to add a specifier which would return the Fully Qualified Domain Name (FQDN) of the current machine ? And not just the hostname like %H does.

Thanks

**Comment by lucaswerkmeister** [comment] 2018-09-06 13:46
What do you mean by the Fully Qualified Domain Name? I’m not aware of any stable definition we could use.

- It could be the result of an rDNS lookup on “the” machine’s IP, but doing a DNS request when *parsing* units seems impossible (we have to be able to resolve specifiers during earliest boot, long before any network is up), and a machine may also have more than one non-local IP address, from one or more network interfaces.
- It could be the `domainname` field from the `uname(2)` syscall (or the `getdomainname` wrapper function). But does anybody set that field? On my server, the `domainname` utility prints `(none)`, and `ypdomainname` and `nisdomainname` report “local domain name not set”.

**Comment by Toniob** [comment] 2018-09-07 12:57
I mean having the same result as 
`hostname --fqdn`
Do you think that's possible ?

**Comment by poettering** [comment] 2018-09-10 13:09
Sorry, but I don#t think we can do this. The issue is that "hostname --fqdn" does a reverse DNS lookup. But DNS is only available late at boot, and blocks on external network services (i.e. the DNS server), and we can't really do that. The thing is that parsing unit files happens during early boot, and we need to complete it in order to start booting, and hence can't wait for DNS (i mean, if we could reach the DNS server at all that early, which we can't).

Sorry, but I see no way how we could do this. The key really is that specifier expansion happens during load time, and not during runtime...

I hope this makes some sense. Closing hence. Sorry.

**Closed as completed by poettering** 2018-09-10 13:09 UTC
Labels: RFE 🎁, pid1, cant-fix

**Comment by anarcat** [comment] 2025-07-10 02:08
i just stumbled upon this, and i think the documentation could be improved. here, %H and %l (unexpectedly) return precisely the same thing, the short hostname.

now, we could argue all day about whether or not `hostname` (without --fqdn) should return the FQDN, or the mechanics of this, i think that's besides the point here. the point is more that %H and %l *look* different in the docs, but they aren't in practice, at least in many environments.

so there should be a note in the systemd.unit manual page about this, IMHO.
