### ISSUE TITLE
set-property drop-in created in runtime storage when used without --runtime

### ISSUE THREAD

**Issue by bl33pbl0p** [systemd/systemd#8000] opened 2018-01-25 15:17 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

236

### Used distribution

Exherbo Linux

### In case of bug report: Expected behaviour you didn't see

```
set-property NAME ASSIGNMENT...
           Set the specified unit properties at runtime where this is supported. This allows changing configuration parameter properties such as resource control settings at runtime. Not all properties may be changed at runtime, but many resource control settings (primarily those in systemd.resource-control(5)) may. The changes are applied instantly, and stored on disk for future boots, unless --runtime is passed, in which case the settings only apply until the next reboot. The syntax of the property assignment follows closely the syntax of assignments in unit files.

           Example: systemctl set-property foobar.service CPUShares=777

If the specified unit appears to be inactive, the changes will be only stored on disk as described previously hence they will be effective when the unit will be started.
Note that this command allows changing multiple properties at the same time, which is preferable over setting them individually. Like unit file configuration settings, assigning the empty list to list parameters will reset the list.

```
user-1000.slice is active, and `systemctl set-property user-1000.slice MemoryLimit=7G` should apply it instantly, and store it on disk in /etc for future reboots, at /etc/systemd/system/user-1000.slice.d/50-MemoryLimit.conf.

### In case of bug report: Unexpected behaviour you saw

The drop-in is made under /run/systemd/transient/user-1000.slice.d/ even when --runtime was not passed, and hence it does not stick through reboots.

### In case of bug report: Steps to reproduce the problem

systemctl set-property user-1000.slice _property_ (on an active slice unit, say the slice of the user currently active).

**Comment by yuwata** [comment] 2018-01-25 16:33
duplicate of #7106.

**Closed as completed by yuwata** 2018-01-25 16:33 UTC
Labels: systemctl, duplicate
