### ISSUE TITLE
When the "BUS_AUTHENTICATING" times are long lasting, the accumulated sd_bus_message may be too large, even cause OOM

### ISSUE THREAD

**Issue by taskset** [systemd/systemd#8166] opened 2018-02-13 10:01 UTC
[ensure_running_before_append_msg.txt](https://github.com/systemd/systemd/files/1719492/ensure_running_before_append_msg.txt)

```
[1226067.221310] Out of memory: Kill process 361 (nginx) score 1000 or sacrifice child
[1226067.224298] Killed process 361 (nginx) total-vm:51128kB, anon-rss:26032kB, file-rss:4kB, shmem-rss:0kB
[1226070.043548] nginx invoked oom-killer: gfp_mask=0x280da, order=0, oom_score_adj=1000
[1226070.043553] nginx cpuset=b9974c214c32ee3596355a724c3c18415dd8fb408985bd019d7a32f827f98020 mems_allowed=0
......
```

```
crash> ps
   PID    PPID  CPU       TASK        ST  %MEM     VSZ    RSS  COMM
>     0      0   0  ffffffff819c5460  RU   0.0       0      0  [swapper/0]
      0      0   1  ffff8801749c1f60  RU   0.0       0      0  [swapper/1]
      0      0   2  ffff8801749c2f10  RU   0.0       0      0  [swapper/2]
      0      0   3  ffff8801749c3ec0  RU   0.0       0      0  [swapper/3]
      0      0   4  ffff8801749c4e70  RU   0.0       0      0  [swapper/4]
      0      0   5  ffff8801749c5e20  RU   0.0       0      0  [swapper/5]
>     0      0   6  ffff8801749c6dd0  RU   0.0       0      0  [swapper/6]
      0      0   7  ffff8801749e8000  RU   0.0       0      0  [swapper/7]
      0      0   8  ffff8801749e8fb0  RU   0.0       0      0  [swapper/8]
      0      0   9  ffff8801749e9f60  RU   0.0       0      0  [swapper/9]
      0      0  10  ffff8801749eaf10  RU   0.0       0      0  [swapper/10]
      0      0  11  ffff8801749ebec0  RU   0.0       0      0  [swapper/11]
      0      0  12  ffff8801749ece70  RU   0.0       0      0  [swapper/12]
      0      0  13  ffff8801749ede20  RU   0.0       0      0  [swapper/13]
      0      0  14  ffff8801749eedd0  RU   0.0       0      0  [swapper/14]
      0      0  15  ffff880174a58000  RU   0.0       0      0  [swapper/15]
      1      0   3  ffff8801748f0000  UN  36.3 12875972 12560084  systemd
      2      0  15  ffff8801748f0fb0  IN   0.0       0      0  [kthreadd]
```

systemd uses too much memory.

I have analysis it:

```
(gdb) maintenance info sections
Core file:
......
    0x7f50cdd7f000->0x7f50cdec0000 at 0x002ae000: load5 ALLOC LOAD HAS_CONTENTS
    0x7f50cdec0000->0x7f50ce001000 at 0x003ef000: load6 ALLOC LOAD HAS_CONTENTS
    0x7f50ce001000->0x7f50ce142000 at 0x00530000: load7 ALLOC LOAD HAS_CONTENTS
	......
	0x7f50da00b000->0x7f50da00c000 at 0x05d4e000: load166 ALLOC LOAD HAS_CONTENTS
    0x7f50da7a5000->0x7f53dc1f9000 at 0x05d4f000: load167 ALLOC LOAD HAS_CONTENTS
    0x7ffe54dfa000->0x7ffe54e1b000 at 0x3077a3000: load168 ALLOC LOAD HAS_CONTENTS
    0x7ffe54ed8000->0x7ffe54eda000 at 0x3077c4000: load169 ALLOC LOAD READONLY CODE HAS_CONTENTS
    0xffffffffff600000->0xffffffffff601000 at 0x3077c6000: load170 ALLOC LOAD READONLY CODE HAS_CONTENTS
......
```
    ----》This segtion over 12G:
```
    0x7f50da7a5000->0x7f53dc1f9000 at 0x05d4f000: load167 ALLOC LOAD HAS_CONTENTS  

	dump memory:	
0x7f52da7a60b0: 0x7b61730800670108      0x00000073617d7673
0x7f52da7a60c0: 0x0000000000000000      0x00000000000003a1
0x7f52da7a60d0: 0x0000000000000001      0x00007f50e0c46f10
0x7f52da7a60e0: 0x0000000000000000      0x00007f52da7a6be8
0x7f52da7a60f0: 0x00007f52da7a6c40      0x00007f52da7a6c68
0x7f52da7a6100: 0x0000000000000000      0x0000000000000000
0x7f52da7a6110: 0x0000000000000000      0x0000000000000000
......
0x7f52da7a6c40: 0x656572662e67726f      0x2e706f746b736564
0x7f52da7a6c50: 0x6f72502e73754244      0x0073656974726570
0x7f52da7a6c60: 0x0000001100730103      0x69747265706f7250
0x7f52da7a6c70: 0x65676e6168437365      0x0000000000000064
0x7f52da7a6c80: 0x7b61730800670108      0x00000073617d7673
0x7f52da7a6c90: 0x0000000000000000      0x00000000000003a1
0x7f52da7a6ca0: 0x0000000000000001      0x00007f50f516bb00
0x7f52da7a6cb0: 0x0000000000000000      0x00007f52da7a73a8
0x7f52da7a6cc0: 0x00007f52da7a7400      0x00007f52da7a7428
0x7f52da7a6cd0: 0x0000000000000000      0x0000000000000000
......

0x7f52da7a7400: 0x656572662e67726f      0x2e706f746b736564
0x7f52da7a7410: 0x6f72502e73754244      0x0073656974726570
0x7f52da7a7420: 0x0000001100730103      0x69747265706f7250
0x7f52da7a7430: 0x65676e6168437365      0x0000000000000064
0x7f52da7a7440: 0x7b61730800670108      0x00000073617d7673
0x7f52da7a7450: 0x0000000000000000      0x00000000000003a1
0x7f52da7a7460: 0x0000000000000001      0x00007f50f516bb00
0x7f52da7a7470: 0x0000000000000000      0x00007f52da7a7f78
0x7f52da7a7480: 0x00007f52da7a7fd0      0x00007f52da7a7ff8
0x7f52da7a7490: 0x0000000000000000      0x0000000000000000
```

Dump the string:
```
(gdb) x/20s 0x7f52da7a7400
0x7f52da7a7400: "org.freedesktop.DBus.Properties"
0x7f52da7a7420: "\003\001s"
0x7f52da7a7424: "\021"
0x7f52da7a7426: ""
0x7f52da7a7427: ""
0x7f52da7a7428: "PropertiesChanged"
0x7f52da7a743a: ""
0x7f52da7a743b: ""
0x7f52da7a743c: ""
0x7f52da7a743d: ""
0x7f52da7a743e: ""
0x7f52da7a743f: ""
0x7f52da7a7440: "\b\001g"
0x7f52da7a7444: "\bsa{sv}as"
0x7f52da7a744e: ""
```
--->
It seems like sd_bus_message:
```
        "  <signal name=\"PropertiesChanged\">\n"                       \
        "   <arg type=\"s\" name=\"interface\"/>\n"                     \
        "   <arg type=\"a{sv}\" name=\"changed_properties\"/>\n"        \
        "   <arg type=\"as\" name=\"invalidated_properties\"/>\n"       \
        "  </signal>\n"    
```

```
struct sd_bus_message {
        unsigned n_ref;

        sd_bus *bus;

        uint64_t reply_cookie;

        const char *path;
        const char *interface;
        const char *member;
        const char *destination;
        const char *sender;

        sd_bus_error error;

        sd_bus_creds creds;
		......
}
```

```
(gdb) p *(sd_bus_message *)0x7f52da7a8030
$21 = {n_ref = 1, bus = 0x7f50ed0ce6e0, reply_cookie = 0, path = 0x7f52da7a8738 "/org/freedesktop/systemd1/unit/dev_2dmapper_2dncl_5cx2dpaasdata_2edevice",
  interface = 0x7f52da7a8790 "org.freedesktop.DBus.Properties", member = 0x7f52da7a87b8 "PropertiesChanged", destination = 0x0, sender = 0x0, error = {name = 0x0,
    message = 0x0, _need_free = 0}, creds = {allocated = false, n_ref = 0, mask = 0, uid = 0, euid = 0, suid = 0, fsuid = 0, gid = 0, egid = 0, sgid = 0, fsgid = 0,
    supplementary_gids = 0x0, n_supplementary_gids = 0, pid = 0, tid = 0, comm = 0x0, tid_comm = 0x0, exe = 0x0, cmdline = 0x0, cmdline_size = 0, cmdline_array = 0x0,
    cgroup = 0x0, session = 0x0, unit = 0x0, user_unit = 0x0, slice = 0x0, capability = 0x0, audit_session_id = 0, audit_login_uid = 0, label = 0x0, unique_name = 0x0,
    well_known_names = 0x0, well_known_names_driver = false, well_known_names_local = false, cgroup_root = 0x0, description = 0x0, unescaped_description = 0x0},
  monotonic = 0, realtime = 0, seqnum = 0, priority = 0, verify_destination_id = 0, sealed = true, dont_send = false, allow_fds = true, free_header = true,
  free_kdbus = false, free_fds = false, release_kdbus = false, poisoned = false, header = 0x7f52da7a8720, footer = 0x0, header_accessible = 0, footer_accessible = 0,
  fields_size = 174, body_size = 100, user_body_size = 100, body = {next = 0x0, data = 0x7f52da7a8650, mmap_begin = 0x0, size = 100, mapped = 0, allocated = 192,
    memfd_offset = 0, memfd = -95, free_this = true, munmap_this = false, sealed = false, is_zero = false}, body_end = 0x7f52da7a81d8, n_body_parts = 1, rindex = 0,
  cached_rindex_part = 0x0, cached_rindex_part_begin = 0, n_fds = 0, fds = 0x0, root_container = {enclosing = 0 '\000', need_offsets = false, index = 0, saved_index = 6,
    signature = 0x7f52d9ed5c00 "sa{sv}as", before = 0, begin = 0, end = 100, array_size = 0x0, offsets = 0x0, n_offsets = 0, offsets_allocated = 0, offset_index = 0,
    item_size = 0, peeked_signature = 0x0}, containers = 0x7f52da7a83d0, n_containers = 0, containers_allocated = 6, iovec = 0x0, iovec_fixed = {{iov_base = 0x0,
      iov_len = 0}, {iov_base = 0x0, iov_len = 0}}, n_iovec = 0, kdbus = 0x0, peeked_signature = 0x0, enforced_reply_signature = 0x0, timeout = 0,
  sender_buffer = '\000' <repeats 25 times>, destination_buffer = '\000' <repeats 25 times>, destination_ptr = 0x0, header_offsets = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
  n_header_offsets = 0}
(gdb)

(gdb) p *(sd_bus *)0x7f50ed0ce6e0
$43 = {n_ref = {_value = 81325}, state = BUS_AUTHENTICATING, input_fd = 104, output_fd = 104, message_version = 1, message_endian = 0, is_kernel = false, can_fds = true,
  bus_client = false, ucred_valid = true, is_server = true, anonymous_auth = false, prefer_readv = false, prefer_writev = false, match_callbacks_modified = true,
  filter_callbacks_modified = true, nodes_modified = false, trusted = false, fake_creds_valid = false, fake_pids_valid = false, manual_peer_interface = false,
  is_system = false, is_user = false, use_memfd = 0, rbuffer = 0x7f50ed0cee50, rbuffer_size = 45, rqueue = 0x0, rqueue_size = 0, rqueue_allocated = 0,
  wqueue = 0x7f50d55d2010, wqueue_size = 81324, windex = 0, wqueue_allocated = 81918, cookie = 81324, unique_name = 0x0, unique_id = 0, match_callbacks = {
    type = BUS_MATCH_ROOT, parent = 0x0, next = 0x0, prev = 0x0, child = 0x7f50ed089cd0, {value = {str = 0x0, u8 = 0 '\000'}, leaf = {callback = 0x0}, compare = {
        children = 0x0}}}, reply_callbacks_prioq = 0x0, reply_callbacks = 0x0, filter_callbacks = 0x7f50ed066e58, nodes = 0x7f50da86fa10, vtable_methods = 0x7f50da86f620,
  vtable_properties = 0x7f50da86f6e0, sockaddr = {sa = {sa_family = 0, sa_data = '\000' <repeats 13 times>}, in = {sin_family = 0, sin_port = 0, sin_addr = {s_addr = 0},
      sin_zero = "\000\000\000\000\000\000\000"}, in6 = {sin6_family = 0, sin6_port = 0, sin6_flowinfo = 0, sin6_addr = {__in6_u = {__u6_addr8 = '\000' <repeats 15 times>,
          __u6_addr16 = {0, 0, 0, 0, 0, 0, 0, 0}, __u6_addr32 = {0, 0, 0, 0}}}, sin6_scope_id = 0}, un = {sun_family = 0, sun_path = '\000' <repeats 107 times>}, nl = {
      nl_family = 0, nl_pad = 0, nl_pid = 0, nl_groups = 0}, storage = {ss_family = 0, __ss_align = 0, __ss_padding = '\000' <repeats 111 times>}, ll = {sll_family = 0,
      sll_protocol = 0, sll_ifindex = 0, sll_hatype = 0, sll_pkttype = 0 '\000', sll_halen = 0 '\000', sll_addr = "\000\000\000\000\000\000\000"}}, sockaddr_size = 0,
  kernel = 0x0, machine = 0x0, nspid = 0, server_id = {bytes = "\377EU\327\066\210C\017\240?@,\217Kr", qwords = {1099872503130834431, 8235833763800932256}}, address = 0x0,
  address_index = 0, last_connect_error = 0, auth = BUS_AUTH_EXTERNAL, auth_rbegin = 38, auth_iovec = {{iov_base = 0x7f50ecfe2160, iov_len = 52}, {iov_base = 0x0,
      iov_len = 0}, {iov_base = 0x0, iov_len = 0}}, auth_index = 0, auth_buffer = 0x7f50ecfe2160 "OK ff4555d73688430fa0df85402c8f4b72\r\nAGREE_UNIX_FD\r\n",
  auth_timeout = 1119433216405, ucred = {pid = 3689, uid = 0, gid = 0}, label = 0x0, creds_mask = 805306368, fds = 0x0, n_fds = 0, exec_path = 0x0, exec_argv = 0x0,
  iteration_counter = 0, kdbus_buffer = 0x0, memfd_cache_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __list = {
        __prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, memfd_cache = {{fd = 0, address = 0x0, mapped = 0,
      allocated = 0} <repeats 32 times>}, n_memfd_cache = 0, original_pid = 1, hello_flags = 1, attach_flags = 16, match_cookie = 1, input_io_event_source = 0x7f50ed0cf160,
  output_io_event_source = 0x0, time_event_source = 0x7f50ed0cef60, quit_event_source = 0x7f50ed0cf060, event = 0x7f50da7a5d70, event_priority = 0, current_message = 0x0,
  current_slot = 0x0, current_handler = 0x0, current_userdata = 0x0, default_bus_ptr = 0x0, tid = 0, fake_creds = {uid = 0, euid = 0, suid = 0, fsuid = 0, gid = 0,
    egid = 0, sgid = 0, fsgid = 0}, fake_pids = {pid = 0, tid = 0, ppid = 0}, fake_label = 0x0, cgroup_root = 0x0, description = 0x0, bloom_size = 0, bloom_n_hash = 0,
  track_queue = 0x0, slots = 0x7f50ed0df570}
(gdb)
```

---->
The wqueue is too large:
```
wqueue = 0x7f50d55d2010, wqueue_size = 81324, windex = 0, wqueue_allocated = 81918
```

The state is BUS_AUTHENTICATING:
```
state = BUS_AUTHENTICATING
```

We also analysis other private_bus, and found every one have too large wqueue.

```
(gdb) print sizeof(sd_bus_message)
$40 = 904

(gdb) p* (Manager *)0x7f50da7a7050
$1 = {units = 0x7f50da7a6080, jobs = 0x7f50da7a60b0, units_by_type = {0x7f510ca25b80, 0x7f50da7d0890, 0x0, 0x7f50da9059a0, 0x0, 0x7f53dbe61fd0, 0x7f53d8a286e0,......
api_bus = 0x7f50da93fb40, system_bus = 0x7f50da93fb40, private_buses = 0x7f50da822770, 

(gdb) p *(Set *)0x7f50da822770
$35 = {b = {hash_ops = 0x7f50da002920 <trivial_hash_ops>, 
{indirect = {storage = 0x7f53db7eac00 "", hash_key = "\203v\ay\313\335\311H\345\356|\234Z\\B)", n_entries = 97,n_buckets = 227, idx_lowest_entry = 1, _pad = "\000\000"}, 
direct = {storage = "\000\254~\333S\177\000\000\203v\ay\313\335\311H\345\356|\234Z\\B)a\000\000\000\343\000\000\000\001\000\000\000\000\000"}}, 
type = HASHMAP_TYPE_SET, has_indirect = true, n_direct_entries = 0, from_pool = true}}
```

So, that such accumulated sd_bus_message may be too large, such as:

  97(private_buses) * 81324 (messages per bus,eg)*  904(sizeof(sd_bus_message)) = 7131138912 (over 7G)

We think, this patch may fix it:
 

Thanks.
Regards,

**Comment by evverx** [comment] 2018-02-13 11:19
The issue seems to be a duplicate of https://github.com/systemd/systemd/issues/6668, where the bug reporter was [asked to provide a minimal reproducer](https://github.com/systemd/systemd/issues/6668#issuecomment-325676851) triggering the leak in the last version of `systemd` (which is currently `237`). Is there any chance you could do that?

**Comment by poettering** [comment] 2018-02-13 16:22
So we do enforce a write queue limit of 192K currently, since 5ddda46f18384d51c74df6daca58a8bc87b46ad1. We used to allow 1K only, before that, but this resulted in problems for people with huge amounts of units.

I am not sure what the best approach regarding this is. On one hand people might actually have such large numbers of units for good reasons, and otoh having such huge numbers of messages queued might be a problem if memory is limited...

This specific problem appears to be triggered by clients that create a direct connection and then simply hang, never processing their queues. Direct connections are root-only actually precisely for this reason: we didn't want to replicate the accounting for them that dbus-daemon normally does to ensure untrusted clients can't keep resources pinned for good. But of course, not doing this kind of accounting while restricting unprivileged clients still means that while we might not be open to DoS from untrusted clients we still are open to accidental DoS by privileged clients.

**Comment by poettering** [comment] 2018-02-13 16:25
> We think, this patch may fix it:

Well, we are running in a supposedly async fashion, i.e. we can't sync on one specific client. That way we'd replace one DoS by a different one: a slow client might freeze us altogether

**Comment by poettering** [comment] 2018-02-13 16:32
One more thing: there's a 90s timeout on the AUTHENTICATING phase currently.

hence, there are limits on all resources we use right now, i.e. the number of connections, the number of queued messages as well as the time we permit connections to stay in AUTHENTICATING phase. However, the limits might be too low on your system if they are all hit at the very same time.

**Comment by poettering** [comment] 2018-02-13 17:50
@w-simon so, i thought about the issue a bit, and prepped #8171 which I think should fix the issue for you. Any chance you can test things with that applied?

That PR won't change the current limits, but it will ensure we never actually hit the limits, and throttle notification message generation when the bus wqueue is already quite full.

Would appreciate feedback if this improves things for you!

**Comment by w-simon** [comment] 2018-02-14 00:47
@poettering 
Thanks very much, we will test it soon.
But as you known, we are going to have the Spring Festival holiday, so we will feed back the test results after that. 
Regards,

**Comment by evverx** [comment] 2018-02-14 01:34
@poettering I'm still trying to understand whether this issue is the same as #6668. Am I right in thinking that the leak mentioned in #6668 is not a leak in the most common sense of the word, but just an overloaded queue that happens to hit some limits due to kind of a misuse?

I'm also a bit concerned about the delay being introduced in #8171 which can be triggered by just one buggy client hanging and restarting, but it's probably because I haven't fully figured out its implications.

**Comment by poettering** [comment] 2018-02-14 09:52
> @poettering I'm still trying to understand whether this issue is the same as #6668. Am I right in thinking that the leak mentioned in #6668 is not a leak in the most common sense of the word, but just an overloaded queue that happens to hit some limits due to kind of a misuse?

Well, the thing is that it *doesn't* hit any limits — in our own code at least. Our limits are so high, that you can make things consume considerable amounts of resources, that are beyond what resource-constrained systems can deal with. And the problem is that the limits we compile in are picked so that they can cover big servers fine, even though for smaller systems lower limits might be possibly better...

Because our limits are relatively high the limits of the available hw resources are hit instead, which causes the kernel to enter a OOM situation, which is the symptom seen here...

And yes, there's no actual leak here. All memory is properly tracked, and there are limits on everything. It's just that the limits are very high for a specific set of systems.


> I'm also a bit concerned about the delay being introduced in #8171 which can be triggered by just one buggy client hanging and restarting, but it's probably because I haven't fully figured out its implications.

Yes, with that patch a client which doesn't read its messages is able to slow down signal generation for everyone else too. I am not too concerned about this though given that we only talk to trusted clients, and trading in slow notifications for reducing the chance of triggering OOM sounds OK to me... I mean, notifications are asynchronous anyway, hence nobody knows when they'll arrive anyway...

**Closed as completed** 2018-02-28 17:15 UTC
Labels: sd-bus, needs-reporter-feedback ❓

**Comment by w-simon** [comment] 2018-03-01 05:42
@poettering  Well, the thing is that it doesn't hit any limits — in our own code at least. Our limits are so high, that you can make things consume considerable amounts of resources, that are beyond what resource-constrained systems can deal with. And the problem is that the limits we compile in are picked so that they can cover big servers fine, even though for smaller systems lower limits might be possibly better...

Well, these macros are not configurable:
#define BUS_WQUEUE_MAX (192*1024)
#define BUS_RQUEUE_MAX (192*1024)
and alse
#define MANAGER_BUS_MESSAGE_BUDGET 100U

If we provide some configuration items for that,  it may be better.
Regards,

**Comment by poettering** [comment] 2018-03-01 09:46
> If we provide some configuration items for that, it may be better.
> Regards,

Well, adding configurable knobs should always be the last resort only. I very much prefer if we can make things "just work" for everyone before adding tunables. To me it's a bit of chickening out if add those, as that means we failed at just making things work.
