### ISSUE TITLE
Warning message at boot when asking for LUKS password

### ISSUE THREAD

**Issue by LaserEyess** [systemd/systemd#15489] opened 2020-04-20 01:04 UTC
**systemd version the issue has been seen with**
> systemd 245 (245.5-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > No warnings at boot

**Unexpected behaviour you saw**
 > journalctl -b -u dracut-initqueue.service 
-- Logs begin at Sat 2018-03-17 14:26:34 EDT, end at Sun 2020-04-19 20:53:01 EDT. --
Apr 19 20:37:52 archlinux systemd[1]: Starting dracut initqueue hook...
Apr 19 20:37:53 archlinux dracut-initqueue[498]: Warning: The unit file, source configuration file or drop-ins of systemd-cryptsetup@root.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Apr 19 20:37:59 archlinux systemd[1]: Finished dracut initqueue hook.
Apr 19 20:37:59 archlinux systemd[1]: dracut-initqueue.service: Succeeded.
Apr 19 20:37:59 archlinux systemd[1]: Stopped dracut initqueue hook.

**Steps to reproduce the problem**
install systemd 245 and dracut
make initramfs with `/usr/bin/dracut -f --no-hostonly-cmdline /boot/initramfs-linux.img`
reboot

My kernel cmdline may be of interest
>options		root=/dev/mapper/root rw quiet rd.luks.uuid=$UUID rd.luks.name=$UUID=root rd.luks.allow-discards systemd.unified_cgroup_hierarchy=1

Please let me know what other information is useful. I do have an `/etc/crypttab` and it has a single line for a secondary disk that is mounted on demand using systemd.automount.

I'm in the process of trying to narrow down when exactly this started. I wasn't really paying attention and did not reboot this machine for a while. However based on #13499 I'm guessing it happened after https://github.com/systemd/systemd/commit/5a1c1b534fe13e60ef9bce0dc680ad6f2a0c577f

**Comment by LaserEyess** [comment] 2020-04-20 01:46
Seems to occur all the way down to `systemd 243.0`. I will try some more testing on old versions tomorrow. Right now I'm relying on packages in arch to test, if I switch to git bisect that may take a good deal longer since I'm pretty terrible with git.

**Comment by poettering** [comment] 2020-08-31 20:56
Duplicate of #13634

**Closed as completed by poettering** 2020-08-31 20:56 UTC
Labels: pid1, duplicate
