### ISSUE TITLE
preset-all removes default.target

### ISSUE THREAD

**Issue by jsynacek** [systemd/systemd#9078] opened 2018-05-24 11:54 UTC
**Description**
Calling `systemctl preset-all` removes `default.target`, even if it is specified in a preset file as an enable item.

Reproducible on the current master, commit 6e2d744b2f8ce8dac0bc686db217c4f45d3148d2.

**Steps to reproduce**
1) Make sure that `multi-user.target` is set as the default target.
```
# systemctl set-default multi-user.target
```
2) Check that the distribution default target is `graphical.target`.
```
# ls -la /usr/lib/systemd/system/default.target
lrwxrwxrwx. 1 root root 16 Apr 13 01:52 /usr/lib/systemd/system/default.target -> graphical.target
```
3) Remove all presets.
```
# rm -f /usr/lib/systemd/system-preset/*.preset
```
4) Configure testing presets.
```
# cat /usr/lib/systemd/system-preset/00-test.preset
enable default.target
disable *
```
5) Reload the daemon and use presets.
```
# systemctl daemon-reload && systemctl preset-all
...
Removed symlink /etc/systemd/system/default.target.
```
6) The `default.target` was removed and it no longer points to the `multi-user.target`, as set in step 1. The distribution `default.target` is still there, as in step 2:
```
# systemctl get-default
graphical.target
```

**Expected behaviour**
The `default.target` symlink is special and should not be deleted by the `disable *` glob. Perhaps it should only be deleted when it is *explicitely* specified.

Note that, in step 4, if instead of `enable default.target` the line reads `enable multi-user.target`, the symlink to the `default.target`, as in step 5, is not removed.

**Comment by poettering** [comment] 2018-05-30 09:34
I am not sure I follow. Presets declare whether unit files shall be enabled or not, and you have to specify the name of the actual unit file there, not of any of the symlinks to it, as the symlinks are what is being managed with the enabling/disabling logic.

hence, everything really works as intended. If you don't want the symlink to be removed, place "enable multi-user.target" in the preset file, which as you noticed works correctly. 

Or am I misunderstanding you? 

The general rule is: we should never allow configuration to alter the effect of presets, as presets are supposed to *generate* configuration, and not *consume* it.

**Comment by jsynacek** [comment] 2018-06-11 08:17
Ok, your explanation makes sense. However, there is still one thing that I don't understand. Consider this:
```
# systemctl get-default
multi-user.target

# systemctl preset-all
...
Removed symlink /etc/systemd/system/default.target.

# systemctl get-default ### 1)
graphical.target

# echo "enable multi-user.target" > /etc/systemd/system-preset/01-target.preset
# systemctl daemon-reload
# systemctl preset-all ### 2)

# systemctl get-default
graphical.target
```
In 1), why is the default target "set back" to graphical?

In 2), `multi-user.target` is not reenabled after running the command. Why is that?

**Comment by poettering** [comment] 2018-06-11 10:49
hmm, on current systemd versions multi-user.target and graphical.target don't carry any [Install] info anymore, hence preset should have no effect on them anyway?

**Comment by poettering** [comment] 2018-06-12 17:18
They used to, we dropped them in 02ebe178a2bd6b2448d4fbfa4a1f7fa98e9e82b1. See the commit msg for details.

Anyway, afaics everything works as it should. closing hence. hope that's ok.

**Closed as completed by poettering** 2018-06-12 17:18 UTC
Labels: needs-reporter-feedback ❓, install
