### ISSUE TITLE
systemd hibernate: better error info needed

### ISSUE THREAD

**Issue by 2xUPe** [systemd/systemd#18480] opened 2021-02-05 17:11 UTC
Sytemctl hibernate refused to work: "Failed to hibernate system via logind: Not enough swap space for hibernation"
But I had two swap partitions with each 3 GB and 2 GB.
During boot both were activated:
04.02.21 09:20	systemd[1]	Activating swap /dev/disk/by-uuid/6d86fe0b-3e20-4fc2-9b59-537e8409401d...
04.02.21 09:20	systemd[1]	Activating swap /dev/disk/by-uuid/984f72cf-0334-4075-bf72-6ccf6d7eedbc...
kernel command line has the right entry:
resume=/dev/disk/by-uuid/6d86fe0b-3e20-4fc2-9b59-537e8409401d
So there was enough space
As there was no priority defined, the priority was automatically set:
02.02.21 11:10		Adding 2098172k swap on /dev/sda3. Priority:-2 extents:1 across:2098172k FS
02.02.21 11:10		Adding 2098172k swap on /dev/sda3. Priority:-2 extents:1 across:2098172k FS
02.02.21 11:10		Adding 3148796k swap on /dev/sdb3. Priority:-3 extents:1 across:3148796k FS
02.02.21 11:10		Adding 3148796k swap on /dev/sdb3. Priority:-3 extents:1 across:3148796k FS
Explanation: 
Systemctl hibernate always takes the swap partition with the highest priotrity, but if that does not match with the entry in the kernel command line, the error info is as mentioned above. But this info is misleading and wrong in this case. It was hard and nearly  be impossible to find out, what the real problem was and I ran into solution only by luck. (Changing the priority manually solved the issue at once.)

The best way to solve this issue - as I think - would be: systemctl hibernate could give in a case like this a more specific error info: swap partition not matching the kernel command line. Or something like this.

Another option to solve this, is that systemctl hibernate should always use for hibernation the swap partition mentioned in the kernel command line.

Or to add always the complete list of the swap partitions into the kernel command line, but where could this become published?

**Comment by poettering** [comment] 2021-02-05 23:08
Please provide the data asked from you in the submission form, i.e. systemd versions you have seen this with. that can't be too hard to provide, can it?

**Comment by 2xUPe** [comment] 2021-02-06 08:57
Sorry for forgetting this because I choose the topic "Feature request" and not "Bug report" and there these datas are not required.
systemd Version: 246.9-1.1
Distro:   openSUSE TW, current Version: 20210203-869.1 x86_64
`Linux desktop-gcbpif4 5.10.0-2.g1bdd4f9-default #1 SMP Mon Dec 14 08:15:12 UTC 2020 (1bdd4f9) x86_64 x86_64 x86_64 GNU/Linux`
CPU:     intel xeon L5420 x86_64
Maybe it is correct now?

**Comment by poettering** [comment] 2021-02-08 16:31
Duplicate of #13470

**Closed as completed by poettering** 2021-02-08 16:31 UTC
Labels: RFE 🎁, duplicate, sleep

**Comment by 2xUPe** [comment] 2021-02-09 10:50
I would like to reopen this bug, because I would change the title to:
"Always give kernel resume partition highest priority".
"Better info needed" is a good idea, but avoiding such errors by changing the code, seems better to me.
So, as the new title says, systemd should write the partition priority in /proc/swaps ( if systemd writes out this file, but I don´t know that) in the way that the resume partition in the kernel command line has always the highest priority. In my case, to provide the error as described above, I set manually:
Filename				Type		Size		Used		Priority
/dev/sda3                               partition	2098172		0		10
/dev/sdb3                               partition	3148796		396876		100
Do you agree with this changing ?

**Comment by mbiebl** [comment] 2021-02-09 18:33
I think related here is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902416#65 (and the follow up messages) which deal with the problem of multiple swap partitions.
Also relevant is the feedback from our Debian kernel maintainer at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902416#112

**Comment by poettering** [comment] 2021-02-09 22:59
the logic already uses whatever is specified as resume partition in the kernel, and then falls back to highest prio partition

https://github.com/systemd/systemd/blob/main/src/shared/sleep-config.c#L311

**Comment by mbiebl** [comment] 2021-02-09 23:56
I think the logic is still broken and I don't think #9559 was ever fixed properly.

**Comment by 2xUPe** [comment] 2021-02-10 11:59
Thanks for the links!
part of: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=902416#139 

The logic goes like this:

- if the user has /sys/power/resume && /sys/power/resume_offset, they
have correctly configured a swapfile - use that.

- else if the user has only set /sys/power/resume, they have correctly
configured a partition, use that.

- else if the user has only set /sys/power/resume_offset but not
/sys/power/resume, log a debug message and ignore the offset and
continue to the next condition.

- finally, if the user has requested hibernate and has not correctly
configured /sys/power/resume and /sys/power/resume_offset, try and
determine the correct configuration by inspecting /proc/swaps.


This is the actual code of systemd, but in my case it is not working correctly, because the automatically set priorities in /proc/swaps do not match to the setting in the kernel command line resume=...... .There is no error message, but the the hibernate image is not found by the kernel during resume, a complete new boot is the result. 

The the logic above should become changed in that way that systemd should look into the kernel command line and use the swap partition defined there, as the automatically defined priorities in /proc/swaps are always beginning with the first swap partition in the partition table and do not always match the kernel command line resume partition. 
Another way is to give the partition mentioned in the kernel command line always the highest priority, so that the used partition from /proc/swaps is always the right one. (This is the way, I solve this issue manually.)
