### ISSUE TITLE
ManageForeignRoutes flag not working

### ISSUE THREAD

**Issue by chenglongtang1** [systemd/systemd#29716] opened 2023-10-25 22:40 UTC
### systemd version the issue has been seen with

253

### Used distribution

Ubuntu 23.10

### Linux kernel version used

6.5.0-1007-gcp

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

The official doc shows that:
`ManageForeignRoutes`, if set to true, `systemd-networkd` will remove routes that are not configured in .network files (except for routes with protocol "kernel", "dhcp" when KeepConfiguration= is true or "dhcp", and "static" when KeepConfiguration= is true or "static"). When false, it will not remove any foreign routes, keeping them even if they are not configured in a .network file. Defaults to yes.

When I set `ManageForeignRoutes` to no and then I create a new route and then restart `systemd-networkd`, the newly added route should be there. But I couldn't see it.

### Steps to reproduce the problem

1. I have a config file in `/usr/lib/systemd/networkd.conf.d/10-disable-route-mgmt.conf` that has `ManageForeignRoutes=no` set up like the following.
```
[Network]
ManageForeignRoutes=no
ManageForeignRoutingPolicyRules=no
```

2. Restart the systemd-networkd to make the configure effective.
```
sudo systemctl daemon-reload
sudo systemctl restart systemd-networkd
```

3. Add the route.
```
sudo ip route add local 104.154.96.57 dev ens4 proto 66 scope host
```

I can see that a new route has been added.
```
chenglongtang@test:~$ sudo ip route show table local
local 10.127.0.12 dev ens4 proto kernel scope host src 10.127.0.12 
local 104.154.96.57 dev ens4 proto 66 scope host 
local 127.0.0.0/8 dev lo proto kernel scope host src 127.0.0.1 
local 127.0.0.1 dev lo proto kernel scope host src 127.0.0.1 
broadcast 127.255.255.255 dev lo proto kernel scope link src 127.0.0.1 
```

4. Restart systemd-networkd.
```
sudo systemctl restart systemd-networkd
```

5. Check the route.
```
chenglongtang@test:~$ sudo ip route show table local
local 10.127.0.12 dev ens4 proto kernel scope host src 10.127.0.12 
local 127.0.0.0/8 dev lo proto kernel scope host src 127.0.0.1 
local 127.0.0.1 dev lo proto kernel scope host src 127.0.0.1 
broadcast 127.255.255.255 dev lo proto kernel scope link src 127.0.0.1 
```
We find that the `local 104.154.96.57 dev ens4 proto 66 scope host` has been removed from the list by restart of systemd-networkd.

One interesting thing I found is that if I run `sudo ip route add local 104.154.96.57 dev eth0 proto 66 scope host` with `systemd-networkd` turned off, then the restart of `systemd-networkd` didn't remove the newly added route. But then  I restarted `systemd-networkd` again, the route was removed.

**Comment by yuwata** [comment] 2023-10-30 05:12
Is this really removed by networkd?

Please provide debugging log generated with the following:
```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

I guess the address (_not_ route) `10.127.0.12` is not managed by networkd, that is, you also create the address manually or by another daemon, right? Then, networkd removed the address on restart, and the kernel removes the route when the address is removed.

Please also provide relevant .network files.

**Comment by chenglongtang1** [comment] 2023-11-02 19:52
Hi, yuwata. Thanks for your reply. Here is the log after running:
```
sudo ip route add local 104.154.96.57 dev ens4 proto 66 scope host
sudo systemctl restart systemd-networkd
```
You can see in Nov 02 19:45:07, there is a 
```
ens4: Ignoring received foreign route (configured): dst: 104.154.96.57/32, src: n/a, gw: n/a, prefsrc: n/a, scope: host, table: local(255), proto: 66, type: local, nexthop: 0, priority: 0, flags: n/a
```

```
Nov 02 19:44:45 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413310]: ens4: Configuring NDisc route (requesting,configuring): dst: n/a, src: n/a, gw: fe80::4001:aff:fe7f:1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Nov 02 19:44:45 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413310]: ens4: Configuring NDisc route (requesting,configuring): dst: 2600:1900:4000:cc61::/65, src: n/a, gw: fe80::4001:aff:fe7f:1, prefsrc: n/a, scope: global, table: main(254), proto: ra, type: unicast, nexthop: 0, priority: 100, flags: n/a
Nov 02 19:44:45 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413310]: ens4: ndisc_check_ready(): SLAAC addresses and routes are not set.
Nov 02 19:44:45 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413310]: ens4: SLAAC addresses and routes set.
Nov 02 19:45:07 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413310]: ens4: Ignoring received foreign route (configured): dst: 104.154.96.57/32, src: n/a, gw: n/a, prefsrc: n/a, scope: host, table: local(255), proto: 66, type: local, nexthop: 0, priority: 0, flags: n/a
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413310]: Restart operation initiated.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413310]: Bus bus-api-network: changing state RUNNING → CLOSED
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413310]: ens4: LLDP Rx: Stopping LLDP client
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd[1]: Stopping systemd-networkd.service - Network Configuration...
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413310]: ens4: DHCPv6 client: State changed: bound -> stopping
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413310]: ens4: DHCPv6 client: Sent Release
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413310]: ens4: DHCPv6 lease lost
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413310]: ens4: Removing DHCPv6 address (configured): 2600:1900:4000:cc61:0:a::/128 (valid for 57min 30s, preferred for 57min 30s), flags: n/a, scope: global
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413310]: ens4: DHCPv6 client: State changed: stopping -> stopped
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413310]: ens4: NDISC: Stopping IPv6 Router Solicitation client
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413310]: ens4: DHCPv4 client: FREE
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd[1]: systemd-networkd.service: Deactivated successfully.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd[1]: Stopped systemd-networkd.service - Network Configuration.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd[1]: Starting systemd-networkd.service - Network Configuration...
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: SELinux enabled state cached to: disabled
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Bus bus-api-network: changing state UNSET → OPENING
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: sd-bus: starting bus bus-api-network by connecting to /run/dbus/system_bus_socket...
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Bus bus-api-network: changing state OPENING → AUTHENTICATING
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Registering bus object implementation for path=/org/freedesktop/network1 iface=org.freedesktop.network1.Manager
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Registering bus object implementation for path=/org/freedesktop/network1/link iface=org.freedesktop.network1.DHCPServer
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Registering bus object implementation for path=/org/freedesktop/network1/link iface=org.freedesktop.network1.Link
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Registering bus object implementation for path=/org/freedesktop/network1/network iface=org.freedesktop.network1.Network
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Registering bus object implementation for path=/org/freedesktop/LogControl1 iface=org.freedesktop.LogControl1
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: sd-device-monitor(n/a): Failed to stat PID1's netns, ignoring: No such file or directory
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: No virtualization found in DMI vendor table.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Unable to read /sys/firmware/dmi/entries/0-0/raw, using the virtualization information found in DMI vendor table, ignoring: No such file or directory
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: UML virtualization not found in /proc/cpuinfo.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Virtualization XEN not found, /proc/xen does not exist
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Virtualization found, CPUID=KVMKVMKVM
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Found VM virtualization kvm
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: /usr/lib/systemd/network/80-container-host0.network: Conditions in the file do not match the system environment, skipping.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: lo: Saved new link: ifindex=1, iftype=LOOPBACK(772), kind=n/a
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: lo: Saved original MTU 65536 (min: 0, max: 4294967295)
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: lo: Saved hardware address: 00:00:00:00:00:00
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: lo: Saved IPv6 link-local address generation mode: eui64
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: lo: Flags change: +LOOPBACK +UP +LOWER_UP +RUNNING
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: lo: Link UP
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: lo: Gained carrier
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: lo: udev initialized link
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Saved new link: ifindex=2, iftype=ETHER(1), kind=n/a
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Saved original MTU 1460 (min: 68, max: 65535)
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Saved permanent hardware address: 42:01:0a:7f:00:0c
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Saved hardware address: 42:01:0a:7f:00:0c
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Saved IPv6 link-local address generation mode: eui64
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Flags change: +UP +LOWER_UP +RUNNING +MULTICAST +BROADCAST
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Link UP
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Gained carrier
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: sd-device: Failed to chase symlinks in "/sys/devices/pci0000:00/0000:00:04.0/physfn".
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: udev initialized link
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: lo: Received new foreign QDisc (configured): handle=0:0, parent=ffff:ffff, kind=noqueue
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Received new foreign QDisc (configured): handle=0:0, parent=ffff:ffff, kind=mq
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Received new foreign QDisc (configured): handle=0:0, parent=0:2, kind=pfifo_fast
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Received new foreign QDisc (configured): handle=0:0, parent=0:1, kind=pfifo_fast
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: lo: Received new foreign address (configured): 127.0.0.1/8 (valid forever, preferred forever), flags: permanent, scope: host
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: lo: link_check_ready(): link is in pending state.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Received new foreign address (configured): 10.127.0.12/32 (valid for 57min 29s, preferred for 57min 29s), flags: n/a, scope: global
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: link_check_ready(): link is in pending state.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: lo: Received new foreign address (configured): ::1/128 (valid forever, preferred forever), flags: permanent, scope: host
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: lo: link_check_ready(): link is in pending state.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Received new foreign address (configured): fe80::4001:aff:fe7f:c/64 (valid forever, preferred forever), flags: permanent, scope: link
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Gained IPv6LL
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: link_check_ready(): link is in pending state.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: rtnl: received non-static neighbor, ignoring.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: rtnl: received non-static neighbor, ignoring.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: rtnl: received non-static neighbor, ignoring.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: rtnl: received non-static neighbor, ignoring.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: rtnl: received non-static neighbor, ignoring.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: rtnl: received non-static neighbor, ignoring.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: rtnl: received non-static neighbor, ignoring.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: rtnl: received non-static neighbor, ignoring.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: rtnl: received non-static neighbor, ignoring.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: rtnl: received non-static neighbor, ignoring.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Could not enumerate wireless LAN phy, ignoring: Operation not supported
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Could not enumerate wireless LAN interfaces, ignoring: Operation not supported
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Enumeration completed
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd[1]: Started systemd-networkd.service - Network Configuration.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Bus bus-api-network: changing state AUTHENTICATING → HELLO
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=RequestName cookie=2 reply_cookie=0 signature=su error-name=n/a error-message=n/a
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=3 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Got message type=method_return sender=org.freedesktop.DBus destination=:1.3499 path=n/a interface=n/a member=n/a  cookie=1 reply_cookie=1 signature=s error-name=n/a error-message=n/a
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Bus bus-api-network: changing state HELLO → RUNNING
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Kernel removed unknown foreign address (n/a): 2600:1900:4000:cc61:0:a::/128 (valid forever, preferred forever), flags: n/a, scope: global
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Ignoring received foreign route (n/a): dst: 2600:1900:4000:cc61:0:a::/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local(255), proto: kernel, type: local, nexthop: 0, priority: 0, flags: n/a
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: lo: Failed to get driver, continuing without: Operation not supported
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: lo: Saved permanent hardware address: 00:00:00:00:00:00
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: lo: Link state is up-to-date
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: lo: State changed: pending -> initialized
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_31 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=4 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: lo: Unmanaging interface.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: lo: State changed: initialized -> unmanaged
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_31 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=5 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Found driver: virtio_net
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Link state is up-to-date
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: State changed: pending -> initialized
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=6 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: found matching network '/run/systemd/network/10-netplan-ens4.network'.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Configuring with /run/systemd/network/10-netplan-ens4.network.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=7 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: State changed: initialized -> configuring
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=8 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: link_check_ready(): link is not activated.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: link_check_ready(): link is not activated.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Setting '/proc/sys/net/ipv6/conf/ens4/disable_ipv6' to '0'
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: No change in value '0', suppressing write
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Setting '/proc/sys/net/ipv6/conf/ens4/use_tempaddr' to '0'
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: No change in value '0', suppressing write
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Setting '/proc/sys/net/ipv6/conf/ens4/accept_ra' to '0'
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: No change in value '0', suppressing write
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Setting '/proc/sys/net/ipv6/conf/ens4/proxy_ndp' to '0'
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: No change in value '0', suppressing write
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Setting '/proc/sys/net/ipv4/conf/ens4/promote_secondaries' to '1'
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: No change in value '1', suppressing write
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: link_check_ready(): link is not activated.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Requested to activate link
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Requested configuring of the DHCPv4 client.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Requested configuring of the DHCPv6 client.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Requested configuring of the IPv6 Router Discovery.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Removing foreign address (configured,marked): 10.127.0.12/32 (valid for 57min 29s, preferred for 57min 29s), flags: n/a, scope: global
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1/link/_32 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=9 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: link_check_ready(): link is not activated.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: link_check_ready(): link is not activated.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: link_check_ready(): link is not activated.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: link_check_ready(): link is not activated.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: link_check_ready(): link is not activated.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: link_check_ready(): link is not activated.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: link_check_ready(): link is not activated.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: link_check_ready(): link is not activated.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: link_check_ready(): link is not activated.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: LLDP Rx: Started LLDP client
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Bringing link up
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/network1 interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=10 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Forgetting foreign address (n/a): 10.127.0.12/32 (valid for 57min 29s, preferred for 57min 29s), flags: n/a, scope: global
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: link_check_ready(): link is not activated.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Ignoring received foreign route (n/a): dst: 10.127.0.12/32, src: n/a, gw: n/a, prefsrc: 10.127.0.12, scope: host, table: local(255), proto: kernel, type: local, nexthop: 0, priority: 0, flags: n/a
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: link_check_ready(): DHCPv4, DHCPv6, DHCP-PD or IPv4LL is enabled but no dynamic address is assigned yet.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: DHCPv4 client: STARTED on ifindex 2
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: DHCPv4 client is configured, acquiring DHCPv4 lease.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: DHCPv6 client is configured.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: Discovering IPv6 routers
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: NDISC: Started IPv6 Router Solicitation client
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: IPv6 Router Discovery is configured and started.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: DHCPv4 client: DISCOVER
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Got message type=signal sender=org.freedesktop.DBus.Local destination=n/a path=/org/freedesktop/DBus/Local interface=org.freedesktop.DBus.Local member=Connected  cookie=4294967295 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: DHCPv4 client: Received message from RAW socket, processing.
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: DHCPv4 client: OFFER
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Got message type=signal sender=org.freedesktop.DBus destination=:1.3499 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired  cookie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: DHCPv4 client: REQUEST (requesting)
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: Got message type=signal sender=org.freedesktop.DBus destination=:1.3499 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired  cookie=3 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Nov 02 19:45:12 test-systemd-forwarding-rule-disabled-ubuntu-2 systemd-networkd[413494]: ens4: DHCPv4 client: Received message from RAW socket, processing.

```

**Comment by yuwata** [comment] 2023-11-03 03:43
As you can see,
```
ens4: Forgetting foreign address (n/a): 10.127.0.12/32 (valid for 57min 29s, preferred for 57min 29s), flags: n/a, scope: global
```
The address is configured before networkd is started. How do you configure it? By another daemon? By kernel command line?

**Comment by yuwata** [comment] 2023-11-03 04:00
Anyway, this is not a bug, and expected behavior. Closing.

**Closed as completed by yuwata** 2023-11-03 04:00 UTC
Labels: network, not-a-bug
