### ISSUE TITLE
Systemd-boot Bad *.efi boot files (aarch64)

### ISSUE THREAD

**Issue by iDigitalFlame** [systemd/systemd#27837] opened 2023-05-29 23:13 UTC
### systemd version the issue has been seen with

253.4-1

### Used distribution

ArchLinux

### Linux kernel version used

6.2.10-1-aarch64-ARCH

### CPU architectures issue was seen on

aarch64

### Component

bootctl, systemd-boot

### Expected behaviour you didn't see

System was supposed to boot properly

### Unexpected behaviour you saw

System failed to boot correctly and failed back to the UEFI screen.

### Steps to reproduce the problem

Update systemd to the latest version and use "bootctl update" to update the EFI files.

For example my EFI directory is in "/boot/EFI"
"/boot/EFI/systemd/systemd-bootaa64.efi" sha256:6ca23dbe6272955df425b05c5a99354d50cc8fcbc4bab724491b1ba541788dd3 fails to boot and be detected by the firmware, while the previous version sha256:4b736db0f718da851df64fd3470dd0bf719bb0c1ab8b46aec5ddff9a22bc91b8 will work without issue.

To prove this, replacing "/boot/EFI/systemd/systemd-bootaa64.efi" and "/boot/EFI/BOOT/BOOTAA64.EFI" with the older efi file versions allows the system to boot normally.

**Comment by YHNdnzj** [comment] 2023-05-30 06:56
Might be a duplicate of https://github.com/systemd/systemd/issues/26951. Can you please try the latest main?

**Comment by iDigitalFlame** [comment] 2023-05-31 01:37
Build with latest `main` resulted in `sha256:c000d8d79c37a4d1763be4c0473758c304ca2302c05baf408c0c2f4feabfb90e`
`systemd-bootaa64.efi: PE32+ executable (EFI application) Aarch64 (stripped to external PDB), for MS Windows, 9 sections`
Replaced `/boot/EFI/BOOT/BOOTAA64.EFI` and `/boot/EFI/systemd/systemd-bootaa64.efi` with the new file, same issue (not booting).
Replacing the files with the older `sha256:4b736db0f718da851df64fd3470dd0bf719bb0c1ab8b46aec5ddff9a22bc91b8` version fixes the issue and allows the system to boot normally.

Upon inspection of the different files (ones that work and don't)
Working: `systemd-bootaa64.efi: PE32+ executable (EFI application) Aarch64 (stripped to external PDB), for MS Windows, 2 sections`
Non-working: `PE32+ executable (EFI application) Aarch64 (stripped to external PDB), for MS Windows, 9 sections`

I'm not 100% sure if this is due to a crash as I cannot get the console output during the bootup period, but the device eventually falls to the EFI shell.

**Comment by medhefgo** [comment] 2023-05-31 07:02
Please try latest main with `-Db_sanitize=undefined` passed to meson.

Also, please do a bisection to find the faulty commit.

**Closed as completed** 2023-06-05 14:24 UTC
Labels: bug 🐛, not-our-bug, sd-boot/sd-stub/bootctl

**Comment by alex-startengine** [comment] 2023-06-20 20:22
@iDigitalFlame did you ever figure this out? I am confused because apparently sd-boot doesnt even use gnu-efi, but i still can't get past the firmware screen with systemd-boot.  so are we not supposed to use the systemd-bootaa64.efi file anymore? because that's what my bootctl copies over.

```
[root@eos ~]# bootctl install
Created "/boot/EFI/systemd".
Created "/boot/EFI/BOOT".
Created "/boot/EFI/Linux".
Copied "/usr/lib/systemd/boot/efi/systemd-bootaa64.efi" to "/boot/EFI/systemd/systemd-bootaa64.efi".
Copied "/usr/lib/systemd/boot/efi/systemd-bootaa64.efi" to "/boot/EFI/BOOT/BOOTAA64.EFI".
Random seed file /boot/loader/random-seed successfully written (32 bytes).
Successfully initialized system token in EFI variable with 32 bytes.
Created EFI boot entry "Linux Boot Manager".
```

**Comment by medhefgo** [comment] 2023-06-20 20:54
That's still the stable systemd version using gnu-efi, which cannot work due to the linked bug. You need to build systemd-git from aur or do it manually and replace `systemd-bootaa64.efi` with the build result manually.
