### ISSUE TITLE
homed: allow logins without password if backend is not encrypted, like traditional UNIX accounts allow it

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#20844] opened 2021-09-25 12:39 UTC
Hi 

I cannot achieve automatic login with GDM and systemd-homed. The home directory is a btrfs subvolume, and the whole system uses FDE and is decrypted at boot, thus there is no need for a second redundant password entry upon login (single user machine).

I've tried `homectl update <user> --automatic login yes` which successfully updates the flag, and configured GDM for autologin for the user, but this crashes GDM. With traditional user directories, automatic login works fine.

I've read [this issue](https://github.com/systemd/systemd/issues/16703) but it doesn't seem relevant as it discusses encrypted home directories and not plain / btrfs subvolumes.

Thanks, have a good day !

**Comment by q2dg** [comment] 2021-09-25 17:23
There's an open issue in Gnome's Gitlab related to this: https://gitlab.gnome.org/GNOME/gdm/-/issues/645
I don't know if it helps.

**Comment by clavelc** [comment] 2021-09-26 11:46
Thanks, it doesn't really help though, it's nearly a year old and no solution has been found...

**Comment by poettering** [comment] 2021-09-28 11:27
The autologin flag that homed manages per user is not used by gdm/accountsdaemon so far. It still needs to be hooked up.

if gdm-style autologin doesn't work: so far we insist that some authentication credential is passed in. Even for backends that use no encryption. We can look into losening this up.

**Comment by poettering** [comment] 2021-10-04 21:54
Duplicate of #17300

**Closed as completed by poettering** 2021-10-04 21:54 UTC
Labels: RFE 🎁, homed
