### ISSUE TITLE
pid 1 wakes up from automount-expire timer every second

### ISSUE THREAD

**Issue by martinpitt** [systemd/systemd#571] opened 2015-07-13 06:45 UTC
In https://launchpad.net/bugs/1470845 it was reported that pid 1 wakes up every second on a system without anything happening:

```
# strace -fvvs1024 -p 1
{{EPOLLIN, {u32=3, u64=3}}}, 35, -1) = 1
clock_gettime(0x7 /* CLOCK_??? */, {68, 315999996}) = 0
read(14, "\1\0\0\0\0\0\0\0", 8)         = 8
fcntl(21, F_DUPFD_CLOEXEC, 3)           = 15
ioctl(21, 0xc0189374, 0x7fff374b98f0)   = 0
fcntl(16, F_GETFD)                      = 0x1 (flags FD_CLOEXEC)
clone(child_stack=0x7f738bdbedf0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x7f738bdbf9d0, tls=0x7f738bdbf700, child_tidptr=0x7f738bdbf9d0) = 3242
timerfd_settime(14, TFD_TIMER_ABSTIME, {it_interval={0, 0}, it_value={69, 565780000}}, NULL) = 0
epoll_wait(4, Process 3242 attached
 <unfinished ...>
[pid  3242] set_robust_list(0x7f738bdbf9e0, 24) = 0
[pid  3242] ioctl(15, 0xc018937c, 0x7f738bdbed20) = -1 EAGAIN (Resource temporarily unavailable)
[pid  3242] close(15)                   = 0
[pid  3242] close(16)                   = 0
[pid  3242] madvise(0x7f738b5bf000, 8368128, MADV_DONTNEED) = 0
[pid  3242] _exit(0)                    = ?
[pid  3242] +++ exited with 0 +++
```

FD 14 is just a timerfd:

```
lrwx------ 1 root root 64 Jul 13 08:41 14 -> anon_inode:[timerfd]
```

I. e. this creates a short-lived thread every second on some `SOURCE_TIME_MONOTONIC` sd-event. There are no journal entries for this even in debug mode.

This goes away after `daemon-reload` or `daemon-reexec`, and I can't reproduce it in a VM, but I do see it on my desktop.

Does anyone have any debugging hints? We use monotonic timer sd_events in a dozen places, is there any way to map an `sd_event` object back to the place that instantiated it, like a name or so?

**Comment by martinpitt** [comment] 2015-07-13 06:46
This happens since at least 221, I verified with 222 and current git master.

**Comment by martinpitt** [comment] 2015-07-13 07:08
Ah, I found the sd_event_source's description field. The timer is `automount-expire`. Indeed that seems to set up an 1 s timer:

```
        timeout = now(CLOCK_MONOTONIC) + MAX(a->timeout_idle_usec/10, USEC_PER_SEC);
```

**Comment by martinpitt** [comment] 2015-07-13 07:11
automount related journal entries:

```
Jul 13 09:04:26 donald systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
Jul 13 09:04:27 donald systemd[1]: proc-sys-fs-binfmt_misc.automount: Got automount request for /proc/sys/fs/binfmt_misc, triggered by 708 (update-binfmts)
```

```
$ mount|grep binfmt
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=23,pgrp=1,timeout=0,minproto=5,maxproto=5,direct)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
```

**Comment by poettering** [comment] 2015-07-24 01:11
The kernel autofs iface is stupid, and requires these regular polls. The idle timeout divided by 10 is a bit frequent though, I will upgrade that to /3 now. 

What puzzles me a bit though, @martinpitt: how come this setting is on for you even? It certainly isn't upstream for proc-sys-fs-binfmt_misc.automount. Is this a Debian/Ubuntu modification? Or a local modification?

Either way, there's little we can do about this without fix from the kernel side, to not require these idle polling...

**Comment by poettering** [comment] 2015-07-24 01:12
If debian/ubuntu sets TimeoutIdleUSec= for proc-sys-fs-binfmt_misc.automount: why? And if so, why so low? Basically by setting it so low you request the high polling frequency.

**Comment by poettering** [comment] 2015-07-24 01:17
The PR upping this to 1/3rd of the idle time is now in #696.

**Comment by mbiebl** [comment] 2015-07-24 02:23
@poettering There are no Debian/Ubuntu specific patches I could think of which make a difference in that regard

```
$ systemctl show proc-sys-fs-binfmt_misc.automount -p TimeoutIdleUSec 
TimeoutIdleUSec=0
```

**Comment by mbiebl** [comment] 2015-07-24 15:05
@poettering any idea why TimeoutIdleUSec=0 is set for automount units with v222/git master?

```
$ systemctl cat proc-sys-fs-binfmt_misc.automount
# /lib/systemd/system/proc-sys-fs-binfmt_misc.automount
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Arbitrary Executable File Formats File System Automount Point
Documentation=https://www.kernel.org/doc/Documentation/binfmt_misc.txt
Documentation=http://www.freedesktop.org/wiki/Software/systemd/APIFileSystems
DefaultDependencies=no
Before=sysinit.target
ConditionPathExists=/proc/sys/fs/binfmt_misc/
ConditionPathIsReadWrite=/proc/sys/

[Automount]
Where=/proc/sys/fs/binfmt_misc
```

**Comment by mbiebl** [comment] 2015-07-24 15:06
Fwiw, with a F22 VM and systemd v219, "systemctl show proc-sys-fs-binfmt_misc.automount -p TimeoutIdleUSec" returns nothing. So maybe this is regression.

**Comment by mbiebl** [comment] 2015-07-24 15:16
nvm, found that v219 does not have support for TimeoutIdleSec yet, this was introduced in v220 in commit deb0a77cf0b409141c4b116ae30becb3d878e1ad

**Comment by poettering** [comment] 2015-07-24 15:17
@mbiebl TimeoutIdleSec=0 i s the default, that's why it is set. It means that the idle logic is turned off.

TimeoutIdleSec= is a 220 feature, that's why it won't be visible on 219...

**Comment by poettering** [comment] 2015-07-24 15:20
@martinpitt do you know why the idle logic was turned on for your .automount unit?

**Comment by mbiebl** [comment] 2015-07-24 15:21
@poettering apparently there is something wrong with 0 meaning disabled.
Explicitly setting TimeoutIdleSec=10 means systemd only wakes up every 10 secs.

So I assume that the default 0 == disabled is broken

**Comment by mbiebl** [comment] 2015-07-24 15:31
at a quick glance, https://github.com/systemd/systemd/blob/master/src/core/automount.c#L403 might be fishy.

**Comment by zonque** [comment] 2015-07-24 15:35
@mbiebl why? For usec=0, param.timeout.timeout will also be 0.

**Comment by zonque** [comment] 2015-07-24 15:39
The problem is here:

``` c
timeout = now(CLOCK_MONOTONIC) + MAX(a->timeout_idle_usec/3, USEC_PER_SEC);
```

`automount_start_expire()` should not be called for `a->timeout_idle_usec == 0` at all. I'm preparing a patch for this.

**Comment by mbiebl** [comment] 2015-07-24 15:49
@zonque are you sure? USEC_PER_SEC-1/USEC_PER_SEC looks like it results to 1

**Comment by zonque** [comment] 2015-07-24 15:52
999999 / 1000000 = 0.999999
So in int, that's 0.

**Comment by mbiebl** [comment] 2015-07-24 15:56
ahem, yeah. Sorry for the brain fart.

**Comment by zonque** [comment] 2015-07-24 15:57
:)

**Comment by mbiebl** [comment] 2015-07-24 16:44
Hm, does automount expiry actually work?
For testing, I've set TimeoutIdleSec=10 in proc-sys-fs-binfmt_misc.automount, but proc-sys-fs-binfmt_misc.mount is not unmounted after 10 seconds although lsof doesn't show any open fds.

Also, shouldn't the timer only be activated once the mount unit has been become active and cleared again, once the mount unit becomes inactive?

@michaelolbrich ^

**Comment by mbiebl** [comment] 2015-07-24 17:00
Tried with a real file system as well via /etc/fstab and setting x-systemd.idle-timeout=30.
No file system access to that mount point happened, yet the file system was not unmounted.
I manually unmounte the file system but systemd kept polling (checked via  strace -p1 -tt 2>&1 | grep AUTOFS)

This is with latest git head. I guess I should file a separate issue for that

**Comment by michaelolbrich** [comment] 2015-07-24 20:20
@mbiebl: I'm guessing you don't have a 'noauto' in your fstab? The problem is, that the expire timer is only started when the mount is triggered from the automount. So the timer is never started if the mount unit is explicitly started (e.g. during startup via local-fs.target). I'm working on a patch for this.
I don't see the polling issue any more. This should be fixed with the "timeout_idle_usec == 0" check.

Hmmm, if mounting is triggered from the automount unit, and is then unmounted manually, ugly things happen: The timer is still running, and at some point the kernel will issue a 'umount request' (why?). The mount unit is already dead and no state change happens, so the token is never returned. Any future access to the mount point will block forever :-/. I'm working on a patch for this as well.

**Comment by mbiebl** [comment] 2015-07-24 20:39
@michaelolbrich 
LABEL=Data  /mnt/data   ntfs-3g user,noauto,x-systemd.automount,x-systemd.idle-timeout=30   0   0

On boot, /mnt/data is not mounted but "ls /mnt/data" will mount the file system on-demand and I see in strace, that systemd start polling autofs via ioctls.
But the file system is not umounted after 30 secs without any activity. So the auto-expire feature seems to be broken.

Also, as said, if I manually unmount /mnt/data, i.e. mnt-data.mount is then in state inactive (dead), systemd should stop polling.

**Comment by michaelolbrich** [comment] 2015-07-24 20:51
@mbiebl 
That's a fuse filesystem, right? Can you try with a normal filesystem? It's quite possible that the kernel cannot detect idle for a fuse filesystem. That would explain what you see: The kernel never issues a unmount request and the unit continues to poll. Take a look at the pull-request I just created a few minues ago. With this the polling should stop after the manual umount.

**Comment by mbiebl** [comment] 2015-07-24 21:09
@michaelolbrich odd, after a reboot the auto-expire seems to work and actually unmount the file system
Not sure, maybe systemd got confused while I did my tests and a simple daemon-reexec and restart mnt-data.automount wasn't sufficient.

The continued polling after auto-unmount still remains though

**Comment by mbiebl** [comment] 2015-07-24 21:22
Let me clarify the last statement:

If the unmount is triggered by systemd via auto-expire, the polling stops.
If the umount is triggered externally (e.g. via umount /mnt/data), the polling continues.

**Comment by michaelolbrich** [comment] 2015-07-24 21:24
@mbiebl 
This should be fixed by my pull-request.

**Comment by kaysievers** [comment] 2015-07-30 11:11
@michaelolbrich , any umount from the command line now seems to trigger an immediate remount:
  systemd[1]: boot.automount: Got automount request for /boot, triggered by 11536 (umount)

**Comment by michaelolbrich** [comment] 2015-07-30 11:58
@kaysievers , this does not happen here (with systemd 223). What's your exact fstab entry (or mount/automount unit)? And what exactly is 'immediate', directly after the umount, or after timeout/3?

**Comment by kaysievers** [comment] 2015-07-30 13:36
@michaelolbrich , no fstab, no config, just the auto-generated units for /boot. As the log line says, the process umount triggers the auto-mounting, not timeout.

```console
$ cat /run/systemd/generator.late/boot.mount 

# Automatically generated by systemd-gpt-auto-generator

[Unit]
Description=umask=0077
Documentation=man:systemd-gpt-auto-generator(8)
RequiresOverridable=systemd-fsck@dev-sda1.service
After=systemd-fsck@dev-sda1.service

[Mount]
What=/dev/sda1
Where=/boot
Type=vfat

## Options=noauto,rw

 cat /run/systemd/generator.late/boot.automount 

# Automatically generated by systemd-gpt-auto-generator

[Unit]
Description=umask=0077
Documentation=man:systemd-gpt-auto-generator(8)
[Automount]
Where=/boot

## TimeoutIdleSec=120
```

**Comment by michaelolbrich** [comment] 2015-07-30 18:16
@kaysievers , I tested your unit files in my qemu test setup, with a different device name. No problems here.
This is really confusing. The latest changes only touch the expire code and should not cause anything like this. And I don't see, how a manual umount can cause this to happen but not a 'expire' umount. Unless you're running a different umount program from the command line.
Can you strace the umount? Is it doing anything after the actual umount system call?

**Comment by mbiebl** [comment] 2015-07-30 21:17
@kaysievers is tab completion trying to access the mountpoint thus triggering a mount request?

**Comment by kaysievers** [comment] 2015-07-31 00:52
strace:
...
stat("/sbin/umount.vfat", 0x7ffec4dc35f0) = -1 ENOENT (No such file or directory)
stat("/sbin/fs.d/umount.vfat", 0x7ffec4dc35f0) = -1 ENOENT (No such file or directory)
stat("/sbin/fs/umount.vfat", 0x7ffec4dc35f0) = -1 ENOENT (No such file or directory)
umount2("/boot", 0)                     = 0
close(1)                                = 0
close(2)                                = 0
exit_group(0)                           = ?
+++ exited with 0 +++

Immediately after that:
systemd[1]: boot.automount: Got automount request for /boot, triggered by 3139 (umount)

Hmm, I don't know how tab completion would interfere here. Any specific thing in mind? It is _after_ the umount syscall and seems triggered by the umount binary.

**Comment by michaelolbrich** [comment] 2015-07-31 08:51
I've tried this with a self compiled systemd 223 on qemu x86_64 with v4.0 and v4.2-rc4 kernels and on qemu ARM with a v3.18 kernel. And just now with the latest systemd 223 packages from Debian unstable on real hardware. In the last case the units are from the EFI generator.
No problems at all.
Other than trying to bisect which change triggers the problem. I'm out of ideas.

**Comment by keszybz** [comment] 2017-06-29 02:24
There have been a bunch of fixes to the automount code since v223, so hopefully this is fixed. This bug has gone stale, closing.

**Closed as completed by keszybz** 2017-06-29 02:24 UTC
Labels: pid1
