### ISSUE TITLE
ping output delayed (`error:io.systemd.Resolve.DNSError`)

### ISSUE THREAD

**Issue by paulmenzel** [systemd/systemd#29082] opened 2023-09-05 14:31 UTC
### systemd version the issue has been seen with

254

### Used distribution

Debian sid/unstable

### Linux kernel version used

Linux version 6.4.0-1-amd64 (debian-kernel@lists.debian.org) (gcc-13 (Debian 13. 1.0-9) 13.1.0, GNU ld (GNU Binutils for Debian) 2.40.90.20230720) #1 SMP PREEMPT _DYNAMIC Debian 6.4.4-2 (2023-07-30)

### CPU architectures issue was seen on

x86_64

### Component

systemd-resolved

### Expected behaviour you didn't see

Note, this only happens with www.embl.org.

    $ host www.embl.org
    www.embl.org is an alias for www6.ebi.ac.uk.
    www6.ebi.ac.uk is an alias for www6.g.ebi.ac.uk.
    www6.g.ebi.ac.uk has address 193.62.193.83

`ping -c1 www.embl.org` should show the result immediately.

### Unexpected behaviour you saw

```
$ LANG= time ping -c1 www.embl.org
PING www6.g.ebi.ac.uk (193.62.193.83) 56(84) bytes of data.
[It hangs here for 7 s.]
64 bytes from 193.62.193.83 (193.62.193.83): icmp_seq=1 ttl=49 time=21.1 ms

--- www6.g.ebi.ac.uk ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 21.055/21.055/21.055/0.000 ms
0.00user 0.00system 0:07.65elapsed 0%CPU (0avgtext+0avgdata 2560maxresident)k
0inputs+0outputs (0major+162minor)pagefaults 0swaps
```

With numeric output only, the result is shown immediately:

```
$ LANG= time ping -n -c1 www.embl.org
PING www6.g.ebi.ac.uk (193.62.193.83) 56(84) bytes of data.
64 bytes from 193.62.193.83: icmp_seq=1 ttl=49 time=21.3 ms

--- www6.g.ebi.ac.uk ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 21.256/21.256/21.256/0.000 ms
0.00user 0.00system 0:00.02elapsed 8%CPU (0avgtext+0avgdata 2688maxresident)k
0inputs+0outputs (0major+157minor)pagefaults 0swaps
```

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
strace shows the delay:


$ sudo LANG= strace -ttt -s2048 ping -c1 www.embl.org
[…]
1693924166.409722 read(5, "127.0.0.1\tlocalhost ersatz\n::1\t\tlocalhost ip6-localhost ip6-loopback\nff02::1\t\tip6-allnodes\nff02::2\t\tip6-allrouters\n\n", 4096) = 116
1693924166.409887 read(5, "", 4096)     = 0
1693924166.409961 close(5)              = 0
1693924166.410067 rt_sigprocmask(SIG_BLOCK, [HUP USR1 USR2 PIPE ALRM CHLD TSTP URG VTALRM PROF WINCH IO], [], 8) = 0
1693924166.410323 socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 5
1693924166.410561 connect(5, {sa_family=AF_UNIX, sun_path="/run/systemd/resolve/io.systemd.Resolve"}, 42) = 0
1693924166.410723 sendto(5, "{\"method\":\"io.systemd.Resolve.ResolveAddress\",\"parameters\":{\"address\":[193,62,193,83],\"family\":2,\"flags\":0}}\0", 109, MSG_DONTWAIT|MSG_NOSIGNAL, NULL, 0) = 109
1693924166.410826 brk(0x55dcddb1c000)   = 0x55dcddb1c000
1693924166.410953 recvfrom(5, 0x55dcddadbdf0, 131080, MSG_DONTWAIT, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
1693924166.411081 ppoll([{fd=5, events=POLLIN}], 1, {tv_sec=119, tv_nsec=999743000}, NULL, 8) = 1 ([{fd=5, revents=POLLIN}], left {tv_sec=112, tv_nsec=464046332})
1693924173.947115 recvfrom(5, "{\"error\":\"io.systemd.Resolve.DNSError\",\"parameters\":{\"rcode\":3}}\0", 131080, MSG_DONTWAIT, NULL, NULL) = 65
1693924173.947581 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
1693924173.947765 close(5)              = 0
1693924173.947995 write(1, "64 bytes from 193.62.193.83 (193.62.193.83): icmp_seq=1 ttl=49 time=21.0 ms\n", 7664 bytes from 193.62.193.83 (193.62.193.83): icmp_seq=1 ttl=49 time=21.0 ms
) = 76
```

`resolvectl query` returns the data immediately though:

```
$ resolvectl query www.embl.org
www.embl.org: 193.62.193.83                    -- link: eno1
              (www6.g.ebi.ac.uk)

-- Information acquired via protocol DNS in 1.5ms.
-- Data is authenticated: no; Data was acquired via local or encrypted transport: no
-- Data from: cache
```
```

**Comment by paulmenzel** [comment] 2023-09-05 14:43
Captured traffic:

```
reading from file www.embl.org.pcapng, link-type EN10MB (Ethernet), snapshot length 262144
16:01:57.403042 IP g45.guest.molgen.mpg.de > 193.62.193.83: ICMP echo request, id 59207, seq 1, length 64
	0x0000:  4500 0054 4bbf 4000 4001 031c 8d0e dc2d  E..TK.@.@......-
	0x0010:  c13e c153 0800 2824 e747 0001 d534 f764  .>.S..($.G...4.d
	0x0020:  0000 0000 5726 0600 0000 0000 1011 1213  ....W&..........
	0x0030:  1415 1617 1819 1a1b 1c1d 1e1f 2021 2223  .............!"#
	0x0040:  2425 2627 2829 2a2b 2c2d 2e2f 3031 3233  $%&'()*+,-./0123
	0x0050:  3435 3637                                4567
16:01:57.424186 IP 193.62.193.83 > g45.guest.molgen.mpg.de: ICMP echo reply, id 59207, seq 1, length 64
	0x0000:  4500 0054 9bcd 0000 3101 020e c13e c153  E..T....1....>.S
	0x0010:  8d0e dc2d 0000 3024 e747 0001 d534 f764  ...-..0$.G...4.d
	0x0020:  0000 0000 5726 0600 0000 0000 1011 1213  ....W&..........
	0x0030:  1415 1617 1819 1a1b 1c1d 1e1f 2021 2223  .............!"#
	0x0040:  2425 2627 2829 2a2b 2c2d 2e2f 3031 3233  $%&'()*+,-./0123
	0x0050:  3435 3637                                4567
16:01:57.696523 IP g45.guest.molgen.mpg.de.44446 > 193.62.193.83.5355: Flags [S], seq 3027620985, win 64240, options [mss 1460,sackOK,TS val 3124312199 ecr 0,nop,wscale 7,tfo  cookiereq,nop,nop], length 0
	0x0000:  4500 0040 82eb 4000 0106 0aff 8d0e dc2d  E..@..@........-
	0x0010:  c13e c153 ad9e 14eb b475 d479 0000 0000  .>.S.....u.y....
	0x0020:  b002 faf0 ec00 0000 0204 05b4 0402 080a  ................
	0x0030:  ba39 3887 0000 0000 0103 0307 2202 0101  .98........."...
16:01:57.696905 IP rick.guest.molgen.mpg.de > g45.guest.molgen.mpg.de: ICMP time exceeded in-transit, length 72
	0x0000:  45c0 005c 13f8 0000 4001 937d 8d0e dc21  E..\....@..}...!
	0x0010:  8d0e dc2d 0b00 e100 0000 0000 4500 0040  ...-........E..@
	0x0020:  82eb 4000 0106 0aff 8d0e dc2d c13e c153  ..@........-.>.S
	0x0030:  ad9e 14eb b475 d479 0000 0000 b002 faf0  .....u.y........
	0x0040:  efff 0000 0204 05b4 0402 080a ba39 3887  .............98.
	0x0050:  0000 0000 0103 0307 2202 0101            ........"...
16:02:04.946791 IP g45.guest.molgen.mpg.de > 193.62.193.83: ICMP echo request, id 59207, seq 2, length 64
	0x0000:  4500 0054 4f31 4000 4001 ffa9 8d0e dc2d  E..TO1@.@......-
	0x0010:  c13e c153 0800 20d7 e747 0002 dc34 f764  .>.S.....G...4.d
	0x0020:  0000 0000 4f72 0e00 0000 0000 1011 1213  ....Or..........
	0x0030:  1415 1617 1819 1a1b 1c1d 1e1f 2021 2223  .............!"#
	0x0040:  2425 2627 2829 2a2b 2c2d 2e2f 3031 3233  $%&'()*+,-./0123
	0x0050:  3435 3637                                4567
16:02:04.967997 IP 193.62.193.83 > g45.guest.molgen.mpg.de: ICMP echo reply, id 59207, seq 2, length 64
	0x0000:  4500 0054 9bce 0000 3101 020d c13e c153  E..T....1....>.S
	0x0010:  8d0e dc2d 0000 28d7 e747 0002 dc34 f764  ...-..(..G...4.d
	0x0020:  0000 0000 4f72 0e00 0000 0000 1011 1213  ....Or..........
	0x0030:  1415 1617 1819 1a1b 1c1d 1e1f 2021 2223  .............!"#
	0x0040:  2425 2627 2829 2a2b 2c2d 2e2f 3031 3233  $%&'()*+,-./0123
	0x0050:  3435 3637                                4567
16:02:05.196525 IP g45.guest.molgen.mpg.de.36676 > 193.62.193.83.5355: Flags [S], seq 143590098, win 64240, options [mss 1460,sackOK,TS val 3124319699 ecr 0,nop,wscale 7,tfo  cookiereq,nop,nop], length 0
	0x0000:  4500 0040 bd71 4000 0106 d078 8d0e dc2d  E..@.q@....x...-
	0x0010:  c13e c153 8f44 14eb 088f 02d2 0000 0000  .>.S.D..........
	0x0020:  b002 faf0 ec00 0000 0204 05b4 0402 080a  ................
	0x0030:  ba39 55d3 0000 0000 0103 0307 2202 0101  .9U........."...
16:02:05.196839 IP rick.guest.molgen.mpg.de > g45.guest.molgen.mpg.de: ICMP time exceeded in-transit, length 72
	0x0000:  45c0 005c 1af3 0000 4001 8c82 8d0e dc21  E..\....@......!
	0x0010:  8d0e dc2d 0b00 e100 0000 0000 4500 0040  ...-........E..@
	0x0020:  bd71 4000 0106 d078 8d0e dc2d c13e c153  .q@....x...-.>.S
	0x0030:  8f44 14eb 088f 02d2 0000 0000 b002 faf0  .D..............
	0x0040:  6e9c 0000 0204 05b4 0402 080a ba39 55d3  n............9U.
	0x0050:  0000 0000 0103 0307 2202 0101            ........"...
16:02:12.696779 IP g45.guest.molgen.mpg.de > 193.62.193.83: ICMP echo request, id 59207, seq 3, length 64
	0x0000:  4500 0054 5168 4000 4001 fd72 8d0e dc2d  E..TQh@.@..r...-
	0x0010:  c13e c153 0800 c1a6 e747 0003 e434 f764  .>.S.....G...4.d
	0x0020:  0000 0000 aaa1 0a00 0000 0000 1011 1213  ................
	0x0030:  1415 1617 1819 1a1b 1c1d 1e1f 2021 2223  .............!"#
	0x0040:  2425 2627 2829 2a2b 2c2d 2e2f 3031 3233  $%&'()*+,-./0123
	0x0050:  3435 3637                                4567
16:02:12.717898 IP 193.62.193.83 > g45.guest.molgen.mpg.de: ICMP echo reply, id 59207, seq 3, length 64
	0x0000:  4500 0054 9bcf 0000 3101 020c c13e c153  E..T....1....>.S
	0x0010:  8d0e dc2d 0000 c9a6 e747 0003 e434 f764  ...-.....G...4.d
	0x0020:  0000 0000 aaa1 0a00 0000 0000 1011 1213  ................
	0x0030:  1415 1617 1819 1a1b 1c1d 1e1f 2021 2223  .............!"#
	0x0040:  2425 2627 2829 2a2b 2c2d 2e2f 3031 3233  $%&'()*+,-./0123
	0x0050:  3435 3637                                4567
16:02:12.946386 IP g45.guest.molgen.mpg.de.36686 > 193.62.193.83.5355: Flags [S], seq 275875545, win 64240, options [mss 1460,sackOK,TS val 3124327449 ecr 0,nop,wscale 7,tfo  cookiereq,nop,nop], length 0
	0x0000:  4500 0040 119f 4000 0106 7c4b 8d0e dc2d  E..@..@...|K...-
	0x0010:  c13e c153 8f4e 14eb 1071 86d9 0000 0000  .>.S.N...q......
	0x0020:  b002 faf0 ec00 0000 0204 05b4 0402 080a  ................
	0x0030:  ba39 7419 0000 0000 0103 0307 2202 0101  .9t........."...
16:02:12.946616 IP rick.guest.molgen.mpg.de > g45.guest.molgen.mpg.de: ICMP time exceeded in-transit, length 72
	0x0000:  45c0 005c 21a4 0000 4001 85d1 8d0e dc21  E..\!...@......!
	0x0010:  8d0e dc2d 0b00 e100 0000 0000 4500 0040  ...-........E..@
	0x0020:  119f 4000 0106 7c4b 8d0e dc2d c13e c153  ..@...|K...-.>.S
	0x0030:  8f4e 14eb 1071 86d9 0000 0000 b002 faf0  .N...q..........
	0x0040:  c462 0000 0204 05b4 0402 080a ba39 7419  .b...........9t.
	0x0050:  0000 0000 0103 0307 2202 0101            ........"...
16:02:20.447016 IP g45.guest.molgen.mpg.de > 193.62.193.83: ICMP echo request, id 59207, seq 4, length 64
	0x0000:  4500 0054 5422 4000 4001 fab8 8d0e dc2d  E..TT"@.@......-
	0x0010:  c13e c153 0800 5d75 e747 0004 ec34 f764  .>.S..]u.G...4.d
	0x0020:  0000 0000 0ad2 0600 0000 0000 1011 1213  ................
	0x0030:  1415 1617 1819 1a1b 1c1d 1e1f 2021 2223  .............!"#
	0x0040:  2425 2627 2829 2a2b 2c2d 2e2f 3031 3233  $%&'()*+,-./0123
	0x0050:  3435 3637                                4567
16:02:20.468569 IP 193.62.193.83 > g45.guest.molgen.mpg.de: ICMP echo reply, id 59207, seq 4, length 64
	0x0000:  4500 0054 9bd0 0000 3101 020b c13e c153  E..T....1....>.S
	0x0010:  8d0e dc2d 0000 6575 e747 0004 ec34 f764  ...-..eu.G...4.d
	0x0020:  0000 0000 0ad2 0600 0000 0000 1011 1213  ................
	0x0030:  1415 1617 1819 1a1b 1c1d 1e1f 2021 2223  .............!"#
	0x0040:  2425 2627 2829 2a2b 2c2d 2e2f 3031 3233  $%&'()*+,-./0123
	0x0050:  3435 3637                                4567
16:02:20.696510 IP g45.guest.molgen.mpg.de.48932 > 193.62.193.83.5355: Flags [S], seq 4051671347, win 64240, options [mss 1460,sackOK,TS val 3124335199 ecr 0,nop,wscale 7,tfo  cookiereq,nop,nop], length 0
	0x0000:  4500 0040 c2ae 4000 0106 cb3b 8d0e dc2d  E..@..@....;...-
	0x0010:  c13e c153 bf24 14eb f17f 9933 0000 0000  .>.S.$.....3....
	0x0020:  b002 faf0 ec00 0000 0204 05b4 0402 080a  ................
	0x0030:  ba39 925f 0000 0000 0103 0307 2202 0101  .9._........"...
16:02:20.696753 IP rick.guest.molgen.mpg.de > g45.guest.molgen.mpg.de: ICMP time exceeded in-transit, length 72
	0x0000:  45c0 005c 3480 0000 4001 72f5 8d0e dc21  E..\4...@.r....!
	0x0010:  8d0e dc2d 0b00 e100 0000 0000 4500 0040  ...-........E..@
	0x0020:  c2ae 4000 0106 cb3b 8d0e dc2d c13e c153  ..@....;...-.>.S
	0x0030:  bf24 14eb f17f 9933 0000 0000 b002 faf0  .$.....3........
	0x0040:  82dd 0000 0204 05b4 0402 080a ba39 925f  .............9._
	0x0050:  0000 0000 0103 0307 2202 0101            ........"...
16:02:28.183053 IP g45.guest.molgen.mpg.de > 193.62.193.83: ICMP echo request, id 59207, seq 5, length 64
	0x0000:  4500 0054 5a82 4000 4001 f458 8d0e dc2d  E..TZ.@.@..X...-
	0x0010:  c13e c153 0800 7c7b e747 0005 f434 f764  .>.S..|{.G...4.d
	0x0020:  0000 0000 e7ca 0200 0000 0000 1011 1213  ................
	0x0030:  1415 1617 1819 1a1b 1c1d 1e1f 2021 2223  .............!"#
	0x0040:  2425 2627 2829 2a2b 2c2d 2e2f 3031 3233  $%&'()*+,-./0123
	0x0050:  3435 3637                                4567
16:02:28.204283 IP 193.62.193.83 > g45.guest.molgen.mpg.de: ICMP echo reply, id 59207, seq 5, length 64
	0x0000:  4500 0054 9bd1 0000 3101 020a c13e c153  E..T....1....>.S
	0x0010:  8d0e dc2d 0000 847b e747 0005 f434 f764  ...-...{.G...4.d
	0x0020:  0000 0000 e7ca 0200 0000 0000 1011 1213  ................
	0x0030:  1415 1617 1819 1a1b 1c1d 1e1f 2021 2223  .............!"#
	0x0040:  2425 2627 2829 2a2b 2c2d 2e2f 3031 3233  $%&'()*+,-./0123
	0x0050:  3435 3637                                4567
16:02:28.206297 IP g45.guest.molgen.mpg.de.53596 > 193.62.193.83.5355: Flags [S], seq 1400733975, win 64240, options [mss 1460,sackOK,TS val 3124342709 ecr 0,nop,wscale 7,tfo  cookiereq,nop,nop], length 0
	0x0000:  4500 0040 edf3 4000 0106 9ff6 8d0e dc2d  E..@..@........-
	0x0010:  c13e c153 d15c 14eb 537d 8117 0000 0000  .>.S.\..S}......
	0x0020:  b002 faf0 ec00 0000 0204 05b4 0402 080a  ................
	0x0030:  ba39 afb5 0000 0000 0103 0307 2202 0101  .9.........."...
16:02:28.206522 IP rick.guest.molgen.mpg.de > g45.guest.molgen.mpg.de: ICMP time exceeded in-transit, length 72
	0x0000:  45c0 005c 3dfe 0000 4001 6977 8d0e dc21  E..\=...@.iw...!
	0x0010:  8d0e dc2d 0b00 e100 0000 0000 4500 0040  ...-........E..@
	0x0020:  edf3 4000 0106 9ff6 8d0e dc2d c13e c153  ..@........-.>.S
	0x0030:  d15c 14eb 537d 8117 0000 0000 b002 faf0  .\..S}..........
	0x0040:  096e 0000 0204 05b4 0402 080a ba39 afb5  .n...........9..
	0x0050:  0000 0000 0103 0307 2202 0101            ........"...
16:02:35.447021 IP g45.guest.molgen.mpg.de > 193.62.193.83: ICMP echo request, id 59207, seq 6, length 64
	0x0000:  4500 0054 5bf3 4000 4001 f2e7 8d0e dc2d  E..T[.@.@......-
	0x0010:  c13e c153 0800 5273 e747 0006 fb34 f764  .>.S..Rs.G...4.d
	0x0020:  0000 0000 06d2 0600 0000 0000 1011 1213  ................
	0x0030:  1415 1617 1819 1a1b 1c1d 1e1f 2021 2223  .............!"#
	0x0040:  2425 2627 2829 2a2b 2c2d 2e2f 3031 3233  $%&'()*+,-./0123
	0x0050:  3435 3637                                4567
16:02:35.468554 IP 193.62.193.83 > g45.guest.molgen.mpg.de: ICMP echo reply, id 59207, seq 6, length 64
	0x0000:  4500 0054 9bd2 0000 3101 0209 c13e c153  E..T....1....>.S
	0x0010:  8d0e dc2d 0000 5a73 e747 0006 fb34 f764  ...-..Zs.G...4.d
	0x0020:  0000 0000 06d2 0600 0000 0000 1011 1213  ................
	0x0030:  1415 1617 1819 1a1b 1c1d 1e1f 2021 2223  .............!"#
	0x0040:  2425 2627 2829 2a2b 2c2d 2e2f 3031 3233  $%&'()*+,-./0123
	0x0050:  3435 3637                                4567
16:02:35.696512 IP g45.guest.molgen.mpg.de.44220 > 193.62.193.83.5355: Flags [S], seq 149631243, win 64240, options [mss 1460,sackOK,TS val 3124350199 ecr 0,nop,wscale 7,tfo  cookiereq,nop,nop], length 0
	0x0000:  4500 0040 abf8 4000 0106 e1f1 8d0e dc2d  E..@..@........-
	0x0010:  c13e c153 acbc 14eb 08eb 310b 0000 0000  .>.S......1.....
	0x0020:  b002 faf0 ec00 0000 0204 05b4 0402 080a  ................
	0x0030:  ba39 ccf7 0000 0000 0103 0307 2202 0101  .9.........."...
16:02:35.696797 IP rick.guest.molgen.mpg.de > g45.guest.molgen.mpg.de: ICMP time exceeded in-transit, length 72
	0x0000:  45c0 005c 524e 0000 4001 5527 8d0e dc21  E..\RN..@.U'...!
	0x0010:  8d0e dc2d 0b00 e100 0000 0000 4500 0040  ...-........E..@
	0x0020:  abf8 4000 0106 e1f1 8d0e dc2d c13e c153  ..@........-.>.S
	0x0030:  acbc 14eb 08eb 310b 0000 0000 b002 faf0  ......1.........
	0x0040:  ab6a 0000 0204 05b4 0402 080a ba39 ccf7  .j...........9..
	0x0050:  0000 0000 0103 0307 2202 0101            ........"...
[…]
```

**Comment by rpigott** [comment] 2023-10-16 18:40
This is another duplicate of #28166.

**Comment by poettering** [comment] 2023-11-08 10:43
Closing as duplicate of #28166

**Closed as completed by poettering** 2023-11-08 10:43 UTC
Labels: bug 🐛, resolve, duplicate
