### ISSUE TITLE
systemd-networkd: bond parameter not accepted after loading bonding module

### ISSUE THREAD

**Issue by ingo-h** [systemd/systemd#7025] opened 2017-10-08 11:55 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

234

### Used distribution

Debian GNU/Linux 9.2 (stretch)

### In case of bug report: Expected behaviour you didn't see

Parameter for bond interface set according to values in 08-bond0.netdev first time after bonding module is loaded.

    $ cat /proc/net/bonding/bond0
    Ethernet Channel Bonding Driver: v3.7.1 (April 27, 2011)
    
    Bonding Mode: IEEE 802.3ad Dynamic link aggregation
    Transmit Hash Policy: layer2 (0)
    MII Status: up
    MII Polling Interval (ms): 1000
    Up Delay (ms): 2000
    Down Delay (ms): 8000
    
    802.3ad info
    LACP rate: fast
    Min links: 0
    Aggregator selection policy (ad_select): stable
    --- snip ---

### In case of bug report: Unexpected behaviour you saw

After loading bonding module its parameter are set to kernels default. systemd-networkd notifies `bond0: netdev exists, using existing without changing its parameters`. This is very bad because default is `load balancing (round-robin)` but I need `IEEE 802.3ad Dynamic link aggregation`. After boot the machine has no network connection!

    $ cat /proc/net/bonding/bond0
    Ethernet Channel Bonding Driver: v3.7.1 (April 27, 2011)
    
    Bonding Mode: load balancing (round-robin)
    MII Status: up
    MII Polling Interval (ms): 0
    Up Delay (ms): 0
    Down Delay (ms): 0
    
    Slave Interface: enp66s0
    MII Status: up
    Speed: 1000 Mbps
    Duplex: full
    Link Failure Count: 0
    Permanent HW addr: 00:19:bb:d3:31:0a
    Slave queue ID: 0
    
    Slave Interface: enp4s0
    MII Status: up
    Speed: 1000 Mbps
    Duplex: full
    Link Failure Count: 0
    Permanent HW addr: 00:19:bb:d3:31:08
    Slave queue ID: 0

### In case of bug report: Steps to reproduce the problem

Setup bond interface:

    $ cat /etc/systemd/network/08-bond0.netdev
    [NetDev]
    Name=bond0
    Kind=bond
    [Bond]
    Mode=802.3ad
    LACPTransmitRate=fast
    MIIMonitorSec=1s
    UpDelaySec=2s
    DownDelaySec=8s
    
    $ cat /etc/systemd/network/12-bond0-add-enp4s0.network
    [Match]
    Name=enp4s0
    [Network]
    Bond=bond0
    
    $ cat /etc/systemd/network/16-bond0-add-enp66s0.network
    [Match]
    Name=enp66s0
    [Network]
    Bond=bond0
    
    $ cat /etc/systemd/network/20-bond0-up.network
    [Match]
    Name=bond0
    [Network]
    BindCarrier=enp4s0 enp66s0
Test:

    $ sudo ip link set dev bond0 down && sudo ip link del dev bond0
    $ sudo rmmod bonding
    $ sudo systemctl restart systemd-networkd
Workaround:

Set module parameter to same values as in 08--bond0.netdev

    $ cat /etc/modprobe.d/bonding.conf
    #Mode=802.3ad
    options bonding mode=4
    
    #LACPTransmitRate=fast
    options bonding lacp_rate=1
    
    #MIIMonitorSec=1s
    options bonding miimon=1000
    
    #UpDelaySec=2s
    options bonding updelay=2000
    
    #DownDelaySec=8s
    options bonding downdelay=8000

**Comment by gdamjan** [comment] 2017-10-08 12:04
this is fixed in 235 by 

> CHANGES WITH 235:
> 
>         * A new modprobe.d drop-in is now shipped by default that sets the
>           bonding module option max_bonds=0. This overrides the kernel default,
>           to avoid conflicts and ambiguity as to whether or not bond0 should be
>           managed by systemd-networkd or not. This resolves multiple issues
>           with bond0 properties not being applied, when bond0 is configured
>           with systemd-networkd. Distributors may choose to not package this,
>           however in that case users will be prevented from correctly managing
>           bond0 interface using systemd-networkd.

ps.
also, check older bugs (closed too) before opening new ones

**Comment by gdamjan** [comment] 2017-10-08 12:05
pps.
additional workaround is to not use bond0 either

**Comment by keszybz** [comment] 2017-10-08 12:22
Yes, seems to be a duplicate of #5971.

**Closed as completed by keszybz** 2017-10-08 12:22 UTC

**Comment by ingo-h** [comment] 2017-10-08 12:34
Sorry for inconvenience, I've looked at the news and also checked older bugs but have overseen that ...
