### ISSUE TITLE
systemd-journald.service.xml Access Control docs are wrong

### ISSUE THREAD

**Issue by rkrzr** [systemd/systemd#5200] opened 2017-02-01 17:08 UTC
### Submission type

  - [x] Bug report

### systemd version the issue has been seen with

> 231
> 229

### Used distribution

Ubuntu 16.04 LTS

### In case of bug report: Expected behaviour you didn't see

The docs claim:

>    Journal files are, by default, owned and readable by the
>   systemd-journal system group but are not
>    writable. Adding a user to this group thus enables her/him to read
>    the journal files.

New log files were created with `root:root` owner and group instead of `root:systemd-journal`.
The docs did not mention that the *setgid* bit should be set on `/var/log/journal`.
The bit was also not set by systemd itself, when the directory was created (by changing `Storage=auto` to `Storage=persistent`).

### In case of bug report: Unexpected behaviour you saw

New log files were created with `root:root` owner and group instead of `root:systemd-journal`, which is what the docs claim. Additionally the `setgid` was not set, as mentioned above.

The change log also [states](https://github.com/systemd/systemd/blob/0879a8d316ef4e69c4f925a5384cfa145eaf2b36/NEWS#L3045):

> systemd-journald will no longer adjust the group of journal
files it creates to the "systemd-journal" group. Instead we
rely on the journal directory to be owned by the
"systemd-journal" group, and its setgid bit set, so that the
kernel file system layer will automatically enforce that
journal files inherit this group assignment. ... A tmpfiles.d(5) snippet included in
systemd will make sure the setgid bit and group are
properly set on the journal directory if it exists on every
boot. However, we recommend adjusting it manually after
upgrades too (or from RPM scriptlets), so that the change is
not delayed until next reboot.

Is this information still accurate? If so, the docs should probably be updated to reflect this.

**Comment by poettering** [comment] 2017-02-01 17:10
I presume you created the /var/log/journal directory yourself, without rebooting and letting tmpfiles fix the permissions on the dir, is that correct?

**Comment by rkrzr** [comment] 2017-02-01 17:14
I changed `Storage=auto` to `Storage=persistent` which then created the directory, I believe. I did not reboot the server (why would that be necessary?).

**Comment by poettering** [comment] 2017-02-01 18:01
@rkrzr adjust the permissions of the dir as necessary. note that journald won#t adjust the perms ever, it assumes that they are properly set, and tmpfiles usually does the job. If you create the dir manually, it's your responsibility to fix the perms, and if you don't they will be off...

you can invoke tmpfiles yourself to get the right effect:

```
systemd-tmpfiles --create /usr/lib/tmpfiles.d/systemd.conf
```

We probably should add a command "journalctl --make-persistent" or so, which does all this properly, in a safe way, and suggest people to use that.

The reason journald doesn't fix up the perms on its own is that in order to do that journald would have to resolve the relevant user/group names, which means doing an NSS request. But doing that might result in a log event itself (as NSS might want to talk to a local or service that logs each request..), and hence might end up a deadlock, where the preparation needed for logging itself causes logging...

**Comment by evverx** [comment] 2017-02-01 18:10
Related to https://github.com/systemd/systemd/issues/1397

We have already documented the workaround https://github.com/systemd/systemd/pull/1398/files

**Comment by poettering** [comment] 2017-02-01 19:06
Yeah, let's close this as duplicate of #1397.

**Closed as completed by poettering** 2017-02-01 19:06 UTC
Labels: journal, documentation, duplicate

**Comment by rkrzr** [comment] 2017-02-01 20:17
I see, thanks for the explanation. I think a `journalctl --make-persistent` would be a great idea, since the process is currently not straightforward in my experience.
