### ISSUE TITLE
sys-module-configfs.device races with netconsole-setup

### ISSUE THREAD

**Issue by bdrung** [systemd/systemd#11468] opened 2019-01-17 17:42 UTC
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > Debian testing

**Expected behaviour you didn't see**
 > The netconsole.service from https://github.com/profitbricks/netconsole should start successfully. netconsole-setup executes:
```sh
CONFIGFS_PATH=/sys/kernel/config
NETCONSOLE_PATH=$CONFIGFS_PATH/netconsole

if [ ! -d $CONFIGFS_PATH ]; then
    echo "${0##*/}: Kernel config directory $CONFIGFS_PATH not present." >&2
    echo "${0##*/}: Loading kernel module 'configfs'..." >&2
    modprobe configfs
    if command -v udevadm >/dev/null 2>&1; then
        udevadm settle
    fi
fi

if ! mount | grep -qw "$CONFIGFS_PATH"; then
    echo "${0##*/}: configfs not mounted to '$CONFIGFS_PATH'; mounting configfs..." >&2
    mount -t configfs configfs $CONFIGFS_PATH
fi
```
**Unexpected behaviour you saw**
 > netconsole-setup races with sys-kernel-config.mount to mount `/sys/kernel/config`:
```
$ journalctl -u netconsole.service
systemd[1]: Starting Dynamically configure Linux netconsole...
netconsole-setup[807]: netconsole-setup: Kernel config directory /sys/kernel/config not present.
netconsole-setup[807]: netconsole-setup: Loading kernel module 'configfs'...
netconsole-setup[807]: netconsole-setup: configfs not mounted to '/sys/kernel/config'; mounting configfs...
netconsole-setup[807]: mount: /sys/kernel/config: configfs already mounted on /sys/kernel/config.
systemd[1]: netconsole.service: Main process exited, code=exited, status=32/n/a
systemd[1]: netconsole.service: Failed with result 'exit-code'.
systemd[1]: Failed to start Dynamically configure Linux netconsole.
```

**Steps to reproduce the problem**

Setup a Debian testing virtual machine, install the package `netconsole`, and reboot.

**Analysis**

When `configfs` is not loaded (and not built-in), `netconsole-setup` will call `modprobe configfs`. Then udev will require the `sys-kernel-config.mount` service:
```
SUBSYSTEM=="module", KERNEL=="configfs", TAG+="systemd", ENV{SYSTEMD_WANTS}+="sys-kernel-config.mount"
```

Ordering netconsole.service and sys-kernel-config.mount with After/Before is not possible:
* netconsole.service cannot run before sys-kernel-config.mount, because sys-kernel-config.mount wants to start before sysinit.target, but netconsole.service want to start after network-online.target.
* netconsole.service cannot run after sys-kernel-config.mount, because sys-kernel-config.mount will only be triggered after netconsole started to load the configfs module.

**Possible solutions**

1. Specify `After=sys-kernel-config.mount` and `Wants=sys-kernel-config.mount` in `netconsole.service`. Then netconsole-setup succeeds before sys-kernel-config.mount. Is that a proper solution or does this change is just lucky to not hit the race?

2. Split `netconsole.service` into multiple services. One to load the `configfs` kernel module (should support built-in configfs as well). Then `netconsole.service` can come after `sys-kernel-config.mount`. Is there a recommended naming convention?

3. Let `netconsole-setup` wait for `sys-kernel-config.mount` to finish. How could that be checked?

What is the best solution?

**Comment by poettering** [comment] 2019-01-17 19:13
hmm, isnt the module autoloaded anyway on mount, isn't manual explicit loading entirely redundant? sounds like the netconsole service should simply pull in the mount unit and that's it? i.e. your solution 1?

**Comment by bdrung** [comment] 2019-01-18 09:12
Thanks for the clarification. So specifying `After=sys-kernel-config.mount` and `Wants=sys-kernel-config.mount` in `netconsole.service` should solve the issue for me. Then `netconsole.service` should find a loaded configfs module and a mounted `/sys/kernel/config` when it starts.

The code for explicitly loading configfs and mounting is will be kept in `netconsole-setup` to support non-systemd setups.

Sadly `sys-kernel-config.mount` did not load the configfs kernel module:
```
$ systemctl status sys-kernel-config.mount
● sys-kernel-config.mount - Kernel Configuration File System
   Loaded: loaded (/lib/systemd/system/sys-kernel-config.mount; static; vendor preset: enabled)
   Active: inactive (dead)
Condition: start condition failed at Fri 2019-01-18 09:05:18 UTC; 22s ago
           └─ ConditionPathExists=/sys/kernel/config was not met
    Where: /sys/kernel/config
     What: configfs
     Docs: https://www.kernel.org/doc/Documentation/filesystems/configfs/configfs.txt
           https://www.freedesktop.org/wiki/Software/systemd/APIFileSystems
```

**Comment by bdrung** [comment] 2019-01-21 15:13
That's the output with `udev.log_priority=debug`:
```
$ cat /proc/cmdline
boot=live fetch=http://192.168.1.20:8080/filesystem.squashfs consoleblank=0 crashkernel=512M quiet udev.log_priority=debug console=ttyS0
$ journalctl --no-hostname -u sys-kernel-config.mount
-- Logs begin at Mon 2019-01-21 15:03:00 UTC, end at Mon 2019-01-21 15:06:12 UTC. --
Jan 21 15:03:00 systemd[1]: Condition check resulted in Kernel Configuration File System being skipped.
$ journalctl -b -u systemd-udevd.service --grep configfs --no-hostname
Compiled without pattern matching support
$ journalctl -b -u systemd-udevd.service --no-hostname | grep configfs
$ lsmod | grep configfs
$ ls /sys/kernel/config
ls: cannot access '/sys/kernel/config': No such file or directory
```

But when I load `configfs` manually, it will be correctly mounted:
```
$ sudo modprobe configfs
$ lsmod | grep configfs
configfs               45056  1
$ journalctl --no-hostname -u sys-kernel-config.mount
-- Logs begin at Mon 2019-01-21 15:03:00 UTC, end at Mon 2019-01-21 15:12:52 UTC. --
Jan 21 15:03:00 systemd[1]: Condition check resulted in Kernel Configuration File System being skipped.
Jan 21 15:12:04 systemd[1]: Mounting Kernel Configuration File System...
Jan 21 15:12:04 systemd[1]: Mounted Kernel Configuration File System.
$ ls /sys/kernel/config
```

**Comment by yuwata** [comment] 2019-03-05 09:03
So, I guess, just loading `conigfs` module before using netconsole seems fine. How about using `systemd-modules-load.service`? Or, just running fist half of the script you show in the first comment. As @poettering explained, mounting the directory is redundant for the system with systemd.

Anyway, I think this is not a bug of systemd... Do you think it is ok to close this?

**Comment by poettering** [comment] 2019-11-14 17:11
Let's close.

**Closed as completed by poettering** 2019-11-14 17:11 UTC
Labels: needs-reporter-feedback ❓, not-a-bug
