### ISSUE TITLE
Impossible to suppress start/stop log output for timers?

### ISSUE THREAD

**Issue by pshirshov** [systemd/systemd#9328] opened 2018-06-18 22:11 UTC
I have several timers which trigger every 5-15 seconds.

My system log is flooded by messages like

```
Jun 18 23:06:31 MACHINE systemd[1]: Started SERVICE.
-- Subject: Unit SERVICE.service has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit SERVICE.service has finished starting up.
--
-- The start-up result is RESULT.
```

Seems like it's impossible to remove these messages specifically for my units.

The following block
```
[Service]
LogLevelMax=info
```
works for any timer output except of these start/stop messages

Moreover, seems like any of these options in `journald.conf` doesn't allow me to hide the messages:

```
MaxLevelStore=debug
MaxLevelSyslog=info
MaxLevelKMsg=notice
MaxLevelConsole=info
MaxLevelWall=emerg
```
Systemd version is 238.

**Comment by kirbyfan64** [comment] 2018-06-19 02:47
I'm not a systemd dev, so take this with a grain of salt, but IMO being able to completely get rid of the startup messages would be the perfect trap for debugging hell. OTOH maybe there could be an option with journalctl to hide them, kind of like IRC clients let you hide join and leave messages?

**Comment by pshirshov** [comment] 2018-06-19 09:35
I guess it may be possible to reduce the amount of data at least. RN just one timer execution throws a lot of useless data. Even just "timer xxxx started/finished" would be better than all that blah-blah.

**Comment by poettering** [comment] 2018-07-04 17:15
well, I am pretty sure we should log everything that happens. yes, in some cases this is not interesting, but this is something to deal with when looking at it, not when generating the log data I am sure. Hence, yes, we should trick journalctl some new tricks to suppress specific bits in its output, but i am very sure we should collect everything

**Comment by pshirshov** [comment] 2018-07-04 17:21
But it's not "everything". In this case it's just an overbloated output of systemd itself. Instead of logging all these lines (in worst case) you may log just "Unit SERVICE.service has finished start-up, Defined-By: systemd". Semantically it would be exactly the same thing...

**Comment by poettering** [comment] 2018-07-04 17:22
Oh, if you don't want the catalog stuff, then don't specify "-x" on the command line of journalctl if that's what you are wondering about

**Comment by poettering** [comment] 2018-07-04 17:34
@pshirshov you only get the "catalog" data if you ask for it, i.e. if you specify `-x` to journalctl. If you don't want that, don't specify it, and it's pretty terse then.

**Comment by pshirshov** [comment] 2018-07-04 17:38
Okay, so, I have two issues:

1. Logs are flooded by timer records, so I'm constantly hitting log size limits and missing important things,
2. This output seems to be insanely weird. (I thought it's the same on disk) I understand that I can hide it, but dont' you think that it's better to have one line than ten lines of the same semantic?

**Comment by poettering** [comment] 2018-07-04 17:56
> This output seems to be insanely weird. (I thought it's the same on disk) I understand that I can hide it, but dont' you think that it's better to have just one line than ten lines with the same semantic?

Again, you *explicitly* *requested* this, by passing "-x". If you add "-x" then journalctl will automatically augment log messages with information from the "message catalog", which is supposed to help you understand the message. It's an optional feature, one you have to opt in explicitly every time you call journalctl. I mean, you are complaining that journalctl provides you with stuff you *explicitly* asked for.

**Comment by aldem** [comment] 2019-05-03 18:08
@poettering 
> I am pretty sure we should log everything that happens

Perhaps, it could help if you elaborate why you are so sure?

There are numerous cases when something is just a noise, always ignored (in production at least) and does not deserve to be logged at all, especially in environments where space allocated for logging is at premium (IoT & co) - excessive noise will simply mask important things due to accelerated log rotation, even worse, for flash storage it will significantly increase wear.

If there are many timers, especially with intervals less than one minute, they could produce hundredths of messages per minute but in most cases those messages are useless (we have monitoring to check if something does not work as expected).

I personally believe that philosophy"no news is good news" should be at least considered as an option, because in most cases this is the right thing to do when logging, collecting everything to sort it out later is not always good practice, and enforcing it is even bad practice, especially taking into account that option to filter/supress output is easy to implement, has almost no hit on performance and does not break anything.

**Comment by mitroko** [comment] 2019-07-01 18:27
+1 here, giving my vote for ability to suppress such messages.

**Comment by eMPee584** [comment] 2019-09-23 10:18
Proposition: new unit settings `SilentStartup` and `SilentOnSuccess`.

**Comment by rhendric** [comment] 2019-12-07 20:40
Would appreciate some feedback on #14279 from the participants here!

**Comment by poettering** [comment] 2020-05-19 17:27
Duplicate of #4919

**Closed as completed by poettering** 2020-05-19 17:27 UTC
Labels: RFE 🎁, journal, duplicate

**Comment by socketpair** [comment] 2022-09-13 07:09
Finally:
```
[Service]
LogLevelMax=....
```

**Comment by pshirshov** [comment] 2022-09-13 12:07
Oh, really? Cool.

**Comment by socketpair** [comment] 2022-09-13 14:03
@pshirshov unfortunately it also filters messages going from the service itself.

**Comment by pshirshov** [comment] 2022-09-13 14:13
Well, that's not what I've been looking for but who cares

**Comment by gene1wood** [comment] 2022-12-27 20:11
This feature was added in #19050 and is present in [systemd v249](https://github.com/systemd/systemd/releases/tag/v249) (see [changelog](https://github.com/systemd/systemd/blob/790096852738b4961ffd8b10664a67b3f075d612/NEWS#L2563-L2567)) available in, for example, [Ubuntu Jammy 22.04 LTS](https://packages.ubuntu.com/jammy/systemd)

> The LogLevelMax= setting of unit files now applies not only to log messages generated *by* the service, but also to log messages generated *about* the service by PID 1. To suppress logs concerning a specific service comprehensively, set this option to a high log level.

To use it to, for example, suppress the log lines from a frequently timer like this

> systemd[1]: Starting Clean php session files...
> systemd[1]: phpsessionclean.service: Succeeded.
> systemd[1]: Finished Clean php session files.

create a systemd override file, for example `/etc/systemd/system/phpsessionclean.service.d/override.conf` with contents like

```
[Service]
LogLevelMax=warning
```

**Comment by pshirshov** [comment] 2022-12-28 15:47
Better than nuthing and it was delivered really quick, so thank you so much.

**Comment by sdwru** [comment] 2023-02-17 20:57
> Better than nuthing and it was delivered really quick, in just five years, so thank you so much.

Which will probably never see the light of day on CentOS 7, which I still use for just about everything.
