### ISSUE TITLE
journalctl: option to exclude output messages

### ISSUE THREAD

**Issue by ilf** [systemd/systemd#6630] opened 2017-08-17 10:23 UTC
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

v234

`journalctl` provides lots of options to filter output by whitelist. Sometimes it is also helpful to filter by blacklist, for example: "all messages from this boot, except firewall". Currently, I am filtering the output with `grep -v, --invert-match`. But it sure would be nice to have it "natively".

**Comment by fsateler** [comment] 2017-08-17 20:50
This is duplicate of #2720 , so closing in favor of that one.

**Closed as completed by fsateler** 2017-08-17 20:50 UTC
Labels: journal, duplicate
