### ISSUE TITLE
increase verbosity of the cycle reporter

### ISSUE THREAD

**Issue by adrelanos** [systemd/systemd#3834] opened 2016-07-29 21:39 UTC
### Submission type

Request for enhancement (RFE)
### systemd version the issue has been seen with

231
### Used distribution

Debian jessie
### feature request

I've made [one mistake](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832802) or others and created systemd ordering cycles. These are very difficult to debug. Example output:

```
Jul 29 01:23:59 localhost systemd[1]: Found ordering cycle on basic.target/start
Jul 29 01:23:59 localhost systemd[1]: Found dependency on sysinit.target/start
Jul 29 01:23:59 localhost systemd[1]: Found dependency on networking.service/start
Jul 29 01:23:59 localhost systemd[1]: Found dependency on network-pre.target/start
Jul 29 01:23:59 localhost systemd[1]: Found dependency on my-test.service/start
Jul 29 01:23:59 localhost systemd[1]: Found dependency on basic.target/start
Jul 29 01:23:59 localhost systemd[1]: Breaking ordering cycle by deleting job networking.service/start
Jul 29 01:23:59 localhost systemd[1]: Job networking.service/start deleted to break ordering cycle starting with basic.target/start
```

It would be more helpful to read a message such as this.

> a.service depends on b.service but b.service depends on a.service

Or something like this. You might have a lot better ideas on how to provide useful debug information for such cases.

**Comment by fsateler** [comment] 2016-07-29 22:10
Duplicate of https://github.com/systemd/systemd/issues/3829

**Closed as completed** 2016-07-29 22:41 UTC
