### ISSUE TITLE
AssertPathIsDirectory fails on path w/ non-ascii characters

### ISSUE THREAD

**Issue by funkyfuture** [systemd/systemd#8310] opened 2018-02-28 15:15 UTC
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 237

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> Having a service template that correctly asserts that a directory exists which includes non-ascii characters.

### In case of bug report: Unexpected behaviour you saw

> The assert fails though the directory exists.

###### Adding a service template

```
[Unit]
Description=Docker-Compose project: %i
After=docker.service
BindsTo=docker.service
AssertPathIsDirectory=/home/user/compose_projects/%i

[Service]
Type=simple
Restart=always
WorkingDirectory=/home/user/compose_projects/%i
ExecStart=/usr/bin/docker-compose up
ExecStop=/usr/bin/docker-compose stop
TimeoutStopSec=30
ExecReload=/usr/bin/docker-compose restart
User=user

[Install]
WantedBy=multi-user.target
```

(sure, daemon is reloaded and the service template works w/ ascii-only directory names as expected.)

###### Test that the directory w/ non-ascii characters exists

```
# test -d /home/user/compose_projects/täterätää ; echo $?
0
```

###### Start the service w/ non-ascii characters

```
# systemctl start compose-project@täterätää   
Assertion failed on job for compose-project@t\xc3\xa4ter\xc3\xa4t\xc3\xa4\xc3\xa4.service. 
```

**Comment by poettering** [comment] 2018-02-28 17:10
`compose-project@täterätää` is not a valid unit name, as unit names may not contain umlauts, and have to end in a unit type, such as `.service`. Because systemctl is nice to you it tries some minimal mangling to convert the argument into a valid unit name. It will escape characters outside of the allowed set for you, and it will append the ".service" suffix for you.  However, this kind of mangling will only escape stuff that obviously is not allowed, it will leave stuff that already looks escaped the way it is. It's hence not reversible. If you want to correctly escape arbitrary strings for inclusion in in unit names, use the systemd-escape tool.

`%i` will use the instance name as it is, i.e. the escaped version, i.e. `t\xc3\xa4ter\xc3\xa4t\xc3\xa4\xc3\xa4` in your example above. If you want to use the path in an unescaped version then use `%I` instead.

Also see man:systemd.unit(5) for details about this.

Anyway, closing this, as this works as intended, and by using `%I` you should get what you are looking for.

**Closed as completed by poettering** 2018-02-28 17:10 UTC

**Comment by funkyfuture** [comment] 2018-03-01 12:42
thank ypu very much for your elaboration. the hint on `%I` was essential. i'm still having difficulty to lookup the proper man pages for relevant info.

**Comment by bl33pbl0p** [comment] 2018-03-01 20:25
https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Specifiers
