### ISSUE TITLE
systemd --user sometimes fails with systemd[1]: user@1000.service: Failed with result 'protocol'

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#9656] opened 2018-07-19 19:52 UTC
**systemd version the issue has been seen with**

239

**Used distribution**

Debian testing on qemu/kvm.

**Expected behaviour you didn't see**

Normal startup of systemd --user from user@$UID.service.

**Unexpected behaviour you saw**

I admit the following report needs more information but this is all that I have now. `systemd --user` started in `user@$UID.service` *sometimes* dies during its startup and the login session starts without systemd --user, as if pam_systemd were disabled. [Probably the same issue](https://bbs.archlinux.org/viewtopic.php?id=238673) was mentioned at Arch BBS. When it dies, the log of `user@1000.service` shows the following:

```
-- Logs begin at Thu 2018-07-19 12:16:28 UTC, end at Thu 2018-07-19 12:17:00 UTC. --
Jul 19 12:16:35 debian-testing systemd[1]: Starting User Manager for UID 1000...
Jul 19 12:16:35 debian-testing systemd[393]: pam_unix(systemd-user:session): session opened for user guest2 by (uid=0)
Jul 19 12:16:35 debian-testing systemd[393]: systemd 239 running in user mode for user 1000/guest2. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid)
Jul 19 12:16:35 debian-testing systemd[393]: Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
Jul 19 12:16:35 debian-testing systemd[393]: Unified cgroup hierarchy is located at /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service.
Jul 19 12:16:35 debian-testing systemd[393]: Controller 'cpu' supported: yes
Jul 19 12:16:35 debian-testing systemd[393]: Controller 'cpuacct' supported: no
Jul 19 12:16:35 debian-testing systemd[393]: Controller 'io' supported: yes
Jul 19 12:16:35 debian-testing systemd[393]: Controller 'blkio' supported: no
Jul 19 12:16:35 debian-testing systemd[393]: Controller 'memory' supported: yes
Jul 19 12:16:35 debian-testing systemd[393]: Controller 'devices' supported: no
Jul 19 12:16:35 debian-testing systemd[393]: Controller 'pids' supported: yes
Jul 19 12:16:35 debian-testing systemd[393]: Set up TFD_TIMER_CANCEL_ON_SET timerfd.
Jul 19 12:16:35 debian-testing systemd[393]: Serializing user-environment-generators to memfd.
Jul 19 12:16:35 debian-testing systemd[393]: Successfully forked off '(sd-executor)' as PID 395.
Jul 19 12:16:35 debian-testing systemd[395]: Skipping PR_SET_MM, as we don't have privileges.
Jul 19 12:16:35 debian-testing systemd[395]: Serializing 30-systemd-environment-d-generator to memfd.
Jul 19 12:16:35 debian-testing systemd[395]: Successfully forked off '(direxec)' as PID 396.
Jul 19 12:16:35 debian-testing systemd[396]: Skipping PR_SET_MM, as we don't have privileges.
Jul 19 12:16:35 debian-testing systemd[395]: /usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator succeeded.
Jul 19 12:16:35 debian-testing systemd[393]: (sd-executor) succeeded.
Jul 19 12:16:35 debian-testing systemd[393]: Failed to fully start up daemon: Permission denied
Jul 19 12:16:35 debian-testing systemd[1]: user@1000.service: Failed with result 'protocol'.
Jul 19 12:16:35 debian-testing systemd[1]: Failed to start User Manager for UID 1000.
```

`/usr/lib/systemd/user-environment-generators` has only `30-systemd-environment-d-generator`. Under the normal startup, `Looking for unit files in (higher priority first)` follows the above log.

**Steps to reproduce the problem**

I am not sure how to consistently reproduce this. It is observed on [Debian testing VM disk image](https://github.com/systemd/systemd/issues/9578#issuecomment-405100786) with UID 1000, roughly once in ten times... I have never seen this outside of qemu/kvm, e.g. systemd-nspawn container or barebone Linux. [The reporter on Arch BBS](https://bbs.archlinux.org/viewtopic.php?pid=1797204#p1797204) says

> I have found that issue happens only on linux-zen kernel, when I installed default one (linux) i have no problem.

**Comment by lucab** [comment] 2018-07-26 10:34
I think this the same bug the ContainerLinux CI is hitting, seemingly a regression introduced in v239, which occurs quite friendly on whole distribution test runs.

I still didn't manage to reliably observe this on a local system, but more details and the image artifact are on our bug tracker: https://github.com/coreos/bugs/issues/2478. Please note that we already backported https://github.com/systemd/systemd/pull/9625 previously.

**Comment by Marcool04** [comment] 2018-11-20 22:19
I have done the following:
````
$ grep ExecStart /etc/systemd/system/user@1005.service
#ExecStart=-/usr/lib/systemd/systemd --user
ExecStart=strace -s 500 -D -f -o /tmp/log /usr/lib/systemd/systemd --user
````
Since then the regular ssh logins on by 1005 have been happening with usual regularity but no errors have occurred for me to observe…
I have this in /tmp/log from the strace on a successful connection and git pull: 
https://framabin.org/p/?8331aa9bf4812f72#kKi7kdmyGwUWbGYZZX2onw1TriPvp8wH8Ayz6m9N/Gw=

I have now done this to avoid the strace log being clobbered by a "successful" one on next iteration in case of failure:
````
$ grep OnFailure /etc/systemd/system/user@1005.service
OnFailure=save_strace_on_fail.service

$ systemctl edit --full save_strace_on_fail.service
[Unit]
Description=copy strace log on failure of user@1005.service
[Service]
Type=oneshot
ExecStart=/usr/local/bin/save_strace.sh

$ cat /usr/local/bin/save_strace.sh
#!/bin/bash
now=`date +%s`
cp "/tmp/strace_user_1005_log" "/tmp/strace_user_1005_log-$now"
exit 0
````

Will post back here if I get anything worth reporting…
Regards,
Mark.

**Comment by Marcool04** [comment] 2018-11-24 21:11
(Sorry I still have nothing.
strace is still capturing output from the logins, and there have been:
````
$ journalctl --since "4 days ago" | grep "Started User Manager for UID 1005" | wc -l
923
````
and still no fails to capture…)

**Comment by Marcool04** [comment] 2018-11-28 09:51
OK! Here we go…
The service has failed twice and I have two strace logs for you:
https://framabin.org/p/?8d7eb653fee42162#jnv1pTna3GueC08khsMoxvIYqwZrHr4+M3XK5wDnC6s=
https://framabin.org/p/?15b274078bce6863#Kdjog3P2WSJOdWKo0KK+EnSpn7Ymtjkj8GCnT6d5bPU=
That is a very low proportion of failures:
````
$ journalctl --since "8 days ago" | grep "Started User Manager for UID 1005" | wc -l
1819
journalctl --since "8 days ago" | grep "Failed to start User Manager for UID 1005" | wc -l
2
````
However, looking at the logs, here it seems like there is a "crossover" on login/logout issue, which results in a `bind… already in use` error:
````
Nov 28 07:44:04 [HOST] sshd[26994]: Accepted publickey for git_user from [GIT_HOST_IP] port 38308 ssh2: RSA SHA256:Na3BX3vxpKiK1P7yjIRiPXT4Gihd>
Nov 28 07:44:04 [HOST] sshd[26994]: pam_unix(sshd:session): session opened for user git_user by (uid=0)
Nov 28 07:44:04 [HOST] systemd[1]: Starting User Runtime Directory /run/user/1005...
Nov 28 07:44:04 [HOST] systemd-logind[385]: New session 2186 of user git_user.
Nov 28 07:44:04 [HOST] systemd[1]: Started User Runtime Directory /run/user/1005.
Nov 28 07:44:04 [HOST] systemd[1]: Starting User Manager for UID 1005...
Nov 28 07:44:04 [HOST] systemd[26997]: pam_unix(systemd-user:session): session opened for user git_user by (uid=0)
Nov 28 07:44:06 [HOST] systemd[26997]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Nov 28 07:44:06 [HOST] systemd[26997]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Nov 28 07:44:06 [HOST] systemd[26997]: Listening on GnuPG network certificate management daemon.
Nov 28 07:44:06 [HOST] systemd[26997]: Reached target Paths.
Nov 28 07:44:06 [HOST] systemd[26997]: Listening on p11-kit server.
Nov 28 07:44:06 [HOST] systemd[26997]: Reached target Timers.
Nov 28 07:44:06 [HOST] systemd[26997]: Listening on GnuPG cryptographic agent and passphrase cache.
Nov 28 07:44:06 [HOST] systemd[26997]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Nov 28 07:44:06 [HOST] systemd[26997]: Starting D-Bus User Message Bus Socket.
Nov 28 07:44:06 [HOST] systemd[26997]: Listening on D-Bus User Message Bus Socket.
Nov 28 07:44:06 [HOST] systemd[26997]: Reached target Sockets.
Nov 28 07:44:06 [HOST] systemd[26997]: Reached target Basic System.
Nov 28 07:44:06 [HOST] systemd[1]: Started User Manager for UID 1005.
Nov 28 07:44:06 [HOST] systemd[26997]: Reached target Default.
Nov 28 07:44:06 [HOST] systemd[26997]: Startup finished in 1.814s.
Nov 28 07:44:06 [HOST] systemd[1]: Started Session 2186 of user git_user.
Nov 28 07:44:07 [HOST] sshd[27006]: Received disconnect from [GIT_HOST_IP] port 38308:11: disconnected by user
Nov 28 07:44:07 [HOST] sshd[27006]: Disconnected from user git_user [GIT_HOST_IP] port 38308
Nov 28 07:44:07 [HOST] sshd[26994]: pam_unix(sshd:session): session closed for user git_user
Nov 28 07:44:07 [HOST] systemd[1]: session-2186.scope: Consumed 38ms CPU time, received 0B IP traffic, sent 0B IP traffic
Nov 28 07:44:07 [HOST] systemd-logind[385]: Session 2186 logged out. Waiting for processes to exit.
Nov 28 07:44:07 [HOST] systemd-logind[385]: Removed session 2186.
Nov 28 07:44:17 [HOST] systemd[1]: Stopping User Manager for UID 1005...
Nov 28 07:44:17 [HOST] systemd[26997]: Stopped target Default.
Nov 28 07:44:17 [HOST] systemd[26997]: Stopped target Basic System.
Nov 28 07:44:17 [HOST] systemd[26997]: Stopped target Timers.
Nov 28 07:44:17 [HOST] sshd[27009]: Accepted publickey for git_user from 35.185.77.129 port 60834 ssh2: RSA SHA256:fGjIvU2+0xo7PrAxvCVIm5KJ/dNF>
Nov 28 07:44:17 [HOST] systemd[26997]: Stopped target Paths.
Nov 28 07:44:17 [HOST] sshd[27009]: pam_unix(sshd:session): session opened for user git_user by (uid=0)
Nov 28 07:44:17 [HOST] systemd[26997]: Stopped target Sockets.
Nov 28 07:44:18 [HOST] systemd[26998]: pam_unix(systemd-user:session): session closed for user git_user
Nov 28 07:44:17 [HOST] systemd[26997]: Closed GnuPG cryptographic agent and passphrase cache.
Nov 28 07:44:17 [HOST] systemd[26997]: Closed p11-kit server.
Nov 28 07:44:17 [HOST] systemd[26997]: Closed GnuPG network certificate management daemon.
Nov 28 07:44:17 [HOST] systemd[26997]: Closed GnuPG cryptographic agent and passphrase cache (restricted).
Nov 28 07:44:17 [HOST] systemd[26997]: Closed D-Bus User Message Bus Socket.
Nov 28 07:44:17 [HOST] systemd[26997]: Closed GnuPG cryptographic agent and passphrase cache (access for web browsers).
Nov 28 07:44:17 [HOST] systemd[26997]: Closed GnuPG cryptographic agent (ssh-agent emulation).
Nov 28 07:44:18 [HOST] systemd[27012]: pam_unix(systemd-user:session): session opened for user git_user by (uid=0)
Nov 28 07:44:17 [HOST] systemd[26997]: Reached target Shutdown.
Nov 28 07:44:17 [HOST] systemd[26997]: Starting Exit the Session...
Nov 28 07:44:18 [HOST] systemd-logind[385]: New session 2188 of user git_user.
Nov 28 07:44:18 [HOST] systemd[1]: user@1005.service: Killing process 27001 (strace) with signal SIGKILL.
Nov 28 07:44:18 [HOST] systemd[1]: user@1005.service: Consumed 1.358s CPU time, received 0B IP traffic, sent 0B IP traffic
Nov 28 07:44:18 [HOST] systemd[1]: Starting User Manager for UID 1005...
Nov 28 07:44:19 [HOST] systemd[27012]: bind(/run/user/1005/systemd/notify) failed: Address already in use
Nov 28 07:44:19 [HOST] systemd[27012]: Failed to fully start up daemon: Address already in use
Nov 28 07:44:19 [HOST] systemd[1]: user@1005.service: Main process exited, code=exited, status=1/FAILURE
Nov 28 07:44:19 [HOST] systemd[1]: user@1005.service: Killing process 27016 (strace) with signal SIGKILL.
Nov 28 07:44:19 [HOST] systemd[27013]: pam_unix(systemd-user:session): session closed for user git_user
Nov 28 07:44:19 [HOST] systemd[1]: user@1005.service: Failed with result 'exit-code'.
Nov 28 07:44:19 [HOST] systemd[1]: Failed to start User Manager for UID 1005.
Nov 28 07:44:19 [HOST] systemd[1]: user@1005.service: Triggering OnFailure= dependencies.
Nov 28 07:44:19 [HOST] systemd[1]: user@1005.service: Consumed 844ms CPU time, received 0B IP traffic, sent 0B IP traffic
Nov 28 07:44:19 [HOST] systemd[1]: Starting copy strace log on failure of user@1005.service...
Nov 28 07:44:19 [HOST] systemd[1]: Started Session 2188 of user git_user.
Nov 28 07:44:19 [HOST] systemd[1]: Started copy strace log on failure of user@1005.service.
Nov 28 07:44:19 [HOST] systemd[1]: save_strace_on_fail.service: Consumed 44ms CPU time, received 0B IP traffic, sent 0B IP traffic
Nov 28 07:44:20 [HOST] sshd[27021]: Received disconnect from 35.185.77.129 port 60834:11: disconnected by user
Nov 28 07:44:20 [HOST] sshd[27021]: Disconnected from user git_user 35.185.77.129 port 60834
Nov 28 07:44:20 [HOST] systemd[1]: session-2188.scope: Consumed 35ms CPU time, received 0B IP traffic, sent 0B IP traffic
Nov 28 07:44:20 [HOST] sshd[27009]: pam_unix(sshd:session): session closed for user git_user
Nov 28 07:44:20 [HOST] systemd-logind[385]: Session 2188 logged out. Waiting for processes to exit.
Nov 28 07:44:20 [HOST] systemd[1]: Stopping User Runtime Directory /run/user/1005...
Nov 28 07:44:20 [HOST] systemd-logind[385]: Removed session 2188.
Nov 28 07:44:20 [HOST] systemd[1]: Stopped User Runtime Directory /run/user/1005.
Nov 28 07:44:20 [HOST] systemd[1]: user-runtime-dir@1005.service: Consumed 41ms CPU time, received 0B IP traffic, sent 0B IP traffic
````
So perhaps this is unrelated… sorry for the noise if that is the case :/

**Comment by thx1111** [comment] 2018-12-08 18:54
I also have this "user@1000.service: Failed with result 'protocol'.", where it occurs on login, every time.  I don't know if the cause is the same or not.

I have an old HP NX9420 on which l've just loaded Arch Linux.  I've setup a BTRFS with the filesystem on a subvolume, and using compress=zstd, and where  cmdline includes "systemd.unified_cgroup_hierarchy=1 zswap.enabled=1".  On login, the journal always has:

 systemd[1]: Started Process Core Dump (PID 541/UID 0).
 systemd[537]: pam_unix(systemd-user:session): session closed for user james
 systemd[1]: user@1000.service: Failed with result 'protocol'.
 systemd[1]: Failed to start User Manager for UID 1000.
 systemd[1]: Started Session 1 of user james.

This is the only system where I have ever seen this.  This hardware and BTRFS are new things for me here, which may or may not have anything to do with the cause.  Unfortunately, the consequences of a failed "user@1000.service", are rather extensive, and the cause is not immediately obvious to the user, since login is successful, but no error message is given.  Xorg, though, will fail to start, using "startx".

So, setting
ExecStart=/usr/bin/strace -s 500 -D -f -o /home/james/usertracesystem /usr/lib/systemd/systemd --user

Logging out, and then logging in on VT2, again:

 login[3285]: pam_unix(login:session): session opened for user james by LOGIN(uid=0)
 systemd[1]: Created slice User Slice of UID 1000.
 systemd[1]: Starting User Runtime Directory /run/user/1000...
 systemd-logind[360]: New session 6 of user james.
 systemd[1]: Started User Runtime Directory /run/user/1000.
 systemd[1]: Starting User Manager for UID 1000...
 systemd[3288]: pam_unix(systemd-user:session): session opened for user james by (uid=0)
 strace[3288]: free(): invalid pointer
 systemd[1]: Started Process Core Dump (PID 3297/UID 0).
 systemd[3289]: pam_unix(systemd-user:session): session closed for user james
 systemd[1]: user@1000.service: Main process exited, code=dumped, status=6/ABRT
 systemd[1]: user@1000.service: Killing process 3296 (systemctl) with signal SIGKILL.
 systemd[1]: user@1000.service: Killing process 3292 (strace) with signal SIGKILL.
 systemd[1]: user@1000.service: Failed with result 'core-dump'.
 systemd[1]: Failed to start User Manager for UID 1000.
 systemd[1]: Started Session 6 of user james.
 login[3285]: LOGIN ON tty2 BY james
 systemd-coredump[3298]: Failed to generate stack trace: Unwinding not supported for this architecture
 systemd-coredump[3298]: Failed to log coredump: Permission denied

and, quickly,  grep denied usertracesystemone gives:

3288  openat(AT_FDCWD, "/proc/1/environ", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)
3294  openat(AT_FDCWD, "/proc/1/environ", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)
3288  access("/sys", W_OK)              = -1 EACCES (Permission denied)
3288  openat(AT_FDCWD, "/sys/module/configfs/uevent", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)
3288  openat(AT_FDCWD, "/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/memory.low", O_WRONLY|O_NOCTTY|O_CLOEXEC) = -1 EACCES (Permission denied)
3288  openat(AT_FDCWD, "/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/memory.high", O_WRONLY|O_NOCTTY|O_CLOEXEC) = -1 EACCES (Permission denied)
3288  openat(AT_FDCWD, "/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/memory.max", O_WRONLY|O_NOCTTY|O_CLOEXEC) = -1 EACCES (Permission denied)
3288  openat(AT_FDCWD, "/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/memory.swap.max", O_WRONLY|O_NOCTTY|O_CLOEXEC) = -1 EACCES (Permission denied)
3288  openat(AT_FDCWD, "/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/pids.max", O_WRONLY|O_NOCTTY|O_CLOEXEC) = -1 EACCES (Permission denied)
3296  openat(AT_FDCWD, "/proc/1/environ", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)
3296  newfstatat(AT_FDCWD, "/proc/1/root", 0x7ffe71dc12f0, 0) = -1 EACCES (Permission denied)

while, logging in remotely over ssh, grep denied usertracesystemtwo gives:

3345  openat(AT_FDCWD, "/proc/1/environ", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)
3351  openat(AT_FDCWD, "/proc/1/environ", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)
3345  access("/sys", W_OK)              = -1 EACCES (Permission denied)
3345  openat(AT_FDCWD, "/sys/module/configfs/uevent", O_RDONLY|O_CLOEXEC) = -1 EACCES (Permission denied)

I've attach the complete trace files.  Is there anything that stands out here?

[usertracesystemone.txt](https://github.com/systemd/systemd/files/2659946/usertracesystemone.txt)
[usertracesystemtwo.txt](https://github.com/systemd/systemd/files/2659947/usertracesystemtwo.txt)

**Comment by dm0-** [comment] 2019-01-09 13:54
I'm just noting that I have not encountered this issue yet since upgrading from 239 to 240.

**Comment by thx1111** [comment] 2019-01-11 22:14
I'm also not having this problem since upgrading to 240.

**Comment by Marcool04** [comment] 2019-01-11 22:16
And I don't think I am either any more ! Only been around 24 hours since upgrade so will wait a bit longer before calling this fixed…

**Comment by poettering** [comment] 2019-02-26 16:47
OK, let's assume this is closed in v240, since three folks reported that. Closing hence. Please reopen/report back if this is reproducible in v241

**Closed as completed by poettering** 2019-02-26 16:47 UTC
Labels: pid1, needs-reporter-feedback ❓

**Comment by keyslapper** [comment] 2019-05-24 18:15
I hate to dig up old bugs, but ...
Fedora 30, new VM install.  Connecting to corporate NIS/ypbind config:
"authselect select nis" to set up the NIS profile.
edits to /etc/yp.conf, etc.  Disabled firewalld and set SELinux to permissive.  Exactly the same process and configuration as used on Fedora 29.  This is what I'm getting (My UID is changed here):

> $ systemctl --version
> systemd 241 (v241-8.git9ef65cb.fc30)
> +PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

> $ systemctl list-units --failed
>   UNIT               LOAD   ACTIVE SUB    DESCRIPTION               
> ● user@1000.service loaded failed failed User Manager for UID 1000

> $ systemctl status user@1000.service
> ● user@1000.service - User Manager for UID 1000
>    Loaded: loaded (/usr/lib/systemd/system/user@.service; static; vendor preset: disabled)
>    Active: failed (Result: protocol) since Fri 2019-05-24 13:29:58 EDT; 22min ago
>      Docs: man:user@.service(5)
>   Process: 7080 ExecStart=/usr/lib/systemd/systemd --user (code=exited, status=217/USER)
>  Main PID: 7080 (code=exited, status=217/USER)
> 
> May 24 13:29:58 FC30VBox systemd[1]: Starting User Manager for UID 1000...
> May 24 13:29:58 FC30VBox systemd[7080]: user@1000.service: Failed to determine user credentials: No such process
> May 24 13:29:58 FC30VBox systemd[7080]: user@1000.service: Failed at step USER spawning /usr/lib/systemd/systemd: No such process
> May 24 13:29:58 FC30VBox systemd[1]: user@1000.service: Failed with result 'protocol'.
> May 24 13:29:58 FC30VBox systemd[1]: Failed to start User Manager for UID 1000.

And the journalctl -xe output:

>  A start job for unit user@1000.service has begun execution.
> 
>  The job identifier is 3006.
> May 24 14:05:37 FC30VBox systemd[16465]: user@1000.service: Failed to determine user credentials: No such process
> May 24 14:05:37 FC30VBox systemd[16465]: user@1000.service: Failed at step USER spawning /usr/lib/systemd/systemd: No such process
>  Subject: Process /usr/lib/systemd/systemd could not be executed
>  Defined-By: systemd
>  Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
> 
>  The process /usr/lib/systemd/systemd could not be executed and failed.
> 
>  The error number returned by this process is ERRNO.
> May 24 14:05:37 FC30VBox systemd[1]: user@1000.service: Failed with result 'protocol'.
>  Subject: Unit failed
>  Defined-By: systemd
>  Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
> 
>  The unit user@1000.service has entered the 'failed' state with result 'protocol'.
> May 24 14:05:37 FC30VBox systemd[1]: Failed to start User Manager for UID 1000.
>  Subject: A start job for unit user@1000.service has failed
>  Defined-By: systemd
>  Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
> 
>  A start job for unit user@1000.service has finished with a failure.

Calls to ypwhich, ypcat, domainname, etc. all display the expected NIS domain.  I am able to log in, but constantly have issues with the system freezing for a moment or two.  This user@xxx.service service is the only one that always fails.

If not for the fact I'm using an identical configuration from a Fedora 29 VM that works perfectly, I'd absolutely assume I was doing something wrong.  As it is, either the bug mentioned in this thread (or some variant of it) is back, or I've missed something new in moving to FC30.

Any suggestions would be appreciated.
Cheers!
Lou

**Comment by RobbieTheK** [comment] 2019-06-14 13:39
Yes same here on Fedora 29 and NIS with `4.20.16-200.fc29.x86_64` 
Notice the Duplicate cookie and below is a gdb of a coredump.

```
Jun 14 00:48:55 ourserver systemd[39180]: Received SIGRTMIN+24 from PID 39199 (kill).
Jun 14 00:48:56 ourserver systemd[1]: Stopped User Manager for UID 5472.
Jun 14 00:48:56 ourserver systemd[1]: Stopping User Runtime Directory /run/user/5472...
Jun 14 00:48:56 ourserver systemd[1]: Stopped User Runtime Directory /run/user/5472.
Jun 14 00:48:56 ourserver systemd[1]: Removed slice User Slice of UID 5472.
Jun 14 00:51:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 00:56:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 01:01:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 01:06:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 01:11:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 01:16:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 01:21:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 01:26:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 01:31:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 01:36:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 01:41:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 01:45:26 ourserver systemd[1]: Starting dnf makecache...
Jun 14 01:45:26 ourserver dnf[22146]: Metadata cache refreshed recently.
Jun 14 01:45:26 ourserver systemd[1]: Started dnf makecache.
Jun 14 01:46:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 01:51:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 01:56:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 02:01:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 02:06:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 02:11:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 02:15:01 ourserver systemd[1]: Starting User Manager for UID 0...
Jun 14 02:15:03 ourserver systemd[38437]: bind(/run/user/0/systemd/notify) failed: Address already in use
Jun 14 02:15:03 ourserver systemd[38437]: Failed to fully start up daemon: Address already in use
Jun 14 02:15:03 ourserver systemd[1]: user@0.service: Failed with result 'protocol'.
Jun 14 02:15:03 ourserver systemd[1]: Failed to start User Manager for UID 0.
Jun 14 02:15:03 ourserver systemd[1]: Started Session 19890 of user root.
Jun 14 02:16:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 02:17:46 ourserver systemd[1]: Started /usr/bin/systemctl start man-db-cache-update.
Jun 14 02:17:46 ourserver systemd[1]: Starting man-db-cache-update.service...
Jun 14 02:17:46 ourserver systemd[1]: Started /usr/bin/systemctl start man-db-cache-update.
Jun 14 02:18:09 ourserver systemd[1]: Started man-db-cache-update.service.
Jun 14 02:19:27 ourserver systemd[1]: Starting User Manager for UID 0...
Jun 14 02:19:32 ourserver systemd-logind[43885]: New session 19892 of user root.
Jun 14 02:20:07 ourserver systemd[41574]: bind(/run/user/0/systemd/notify) failed: Address already in use
Jun 14 02:20:07 ourserver systemd[41574]: Failed to fully start up daemon: Address already in use
Jun 14 02:20:07 ourserver systemd[1]: user@0.service: Failed with result 'protocol'.
Jun 14 02:20:07 ourserver systemd[1]: Failed to start User Manager for UID 0.
Jun 14 02:20:07 ourserver systemd[1]: Started Session 19892 of user root.

Jun 14 03:01:04 ourserver systemd[1]: Starting User Manager for UID 0...
Jun 14 03:01:04 ourserver systemd[14158]: bind(/run/user/0/systemd/notify) failed: Address already in use
Jun 14 03:01:04 ourserver systemd[14158]: Failed to fully start up daemon: Address already in use
Jun 14 03:01:04 ourserver systemd[1]: user@0.service: Failed with result 'protocol'.
Jun 14 03:01:04 ourserver systemd[1]: Failed to start User Manager for UID 0.
Jun 14 03:01:04 ourserver systemd[1]: Started Session 19904 of user root.
Jun 14 03:01:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 03:06:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 03:11:37 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 03:16:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 03:21:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 03:25:44 ourserver kernel: FS-Cache: Duplicate cookie detected
Jun 14 03:25:44 ourserver kernel: FS-Cache: O-cookie c=0000000038870852 [p=0000000090eab239 fl=222 nc=0 na=1]
Jun 14 03:25:44 ourserver kernel: FS-Cache: O-cookie d=000000001a86ab95 n=00000000b6293788
Jun 14 03:25:44 ourserver kernel: FS-Cache: O-key=[10] '040002000801966c4034'
Jun 14 03:25:44 ourserver kernel: FS-Cache: N-cookie c=00000000d4cb8e2e [p=0000000090eab239 fl=2 nc=0 na=1]
Jun 14 03:25:44 ourserver kernel: FS-Cache: N-cookie d=000000001a86ab95 n=00000000aaf3d265
Jun 14 03:25:44 ourserver kernel: FS-Cache: N-key=[10] '040002000801966c4034'
Jun 14 03:26:35 ourserver ypbind[20820]: 20822: Ping active servers for all domains.
Jun 14 03:28:29 ourserver systemd-logind[43885]: Session 19904 logged out. Waiting for processes to exit.
Jun 14 03:28:29 ourserver systemd-logind[43885]: Removed session 19904.
Jun 14 03:28:34 ourserver systemd-logind[43885]: New session 19906 of user root.
Jun 14 03:28:34 ourserver systemd[1]: Starting User Manager for UID 0...
Jun 14 03:28:38 ourserver systemd[28928]: bind(/run/user/0/systemd/notify) failed: Address already in use
Jun 14 03:28:38 ourserver systemd[28928]: Failed to fully start up daemon: Address already in use
Jun 14 03:28:38 ourserver systemd[1]: user@0.service: Failed with result 'protocol'.
Jun 14 03:28:38 ourserver systemd[1]: Failed to start User Manager for UID 0.
Jun 14 03:28:38 ourserver systemd[1]: Started Session 19906 of user root.
Jun 14 03:28:50 ourserver systemd-logind[43885]: Session 19906 logged out. Waiting for processes to exit.
Jun 14 03:28:50 ourserver systemd-logind[43885]: Removed session 19906.
Jun 14 03:28:50 ourserver systemd-logind[43885]: New session 19908 of user root.
```

```
systemctl --version
systemd 239
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

```
BFD: warning: /var/lib/systemd/coredump/core.systemd-journal.0.28154ddd19b243eda01287de82559656.31800.1560486433000000 is truncated: expected core file size >= 54960128, found: 4661248
BFD: warning: /var/lib/systemd/coredump/core.systemd-journal.0.28154ddd19b243eda01287de82559656.31800.1560486433000000 is truncated: expected core file size >= 54960128, found: 4661248
[New LWP 31800]

warning: core file may not match specified executable file.
Reading symbols from /usr/lib/systemd/systemd-journald...Reading symbols from /usr/lib/debug/usr/lib/systemd/systemd-journald-239-12.git8bca462.fc29.x86_64.debug...done.
done.
Cannot access memory at address 0x7fefce6f7128
Cannot access memory at address 0x7fefce6f7120
Failed to read a valid object file image from memory.
Core was generated by `/usr/lib/systemd/systemd-journald'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fefce266760 in ?? ()
(gdb) bt full
#0  0x00007fefce266760 in ?? ()
No symbol table info available.
Backtrace stopped: Cannot access memory at address 0x7ffe24f7e2b8
```
[Link to coredump](https://storm.cis.fordham.edu/~rkudyba/var/lib/systemd/coredump/core.systemd-journal.0.28154ddd19b243eda01287de82559656.31800.1560486433000000).

**Comment by 4nanook** [comment] 2019-09-01 09:31
For what it's worth I am running Ubuntu 19.04, it was running systemd version 240.  It had a strange problem where when I logged in there was a 17 second delay.  I built version 243 and replaced the system version with it.  Now the delay is gone, logins are instant, but I am getting this same error, "Protocol".

**Comment by eMPee584** [comment] 2020-04-09 11:29
.. And what does it actually mean, result _protocol_ ?
another error message one has to grep the code to understand xD
