### ISSUE TITLE
New clock skew detection in systemd-229 can't be runtime disabled.

### ISSUE THREAD

**Issue by arachnist** [systemd/systemd#2599] opened 2016-02-12 18:42 UTC
The new clock skew detection can only be disabled by `--with-time-epoch=0`.

There are - not "mainstream" - scenarios where it is desirable to be able to test things with time/date set in the past and recompilation of base system packages is not an option.

**Comment by poettering** [comment] 2016-02-12 19:09
A system is simply not viable anymore with incorrect time, since pretty much all crypto verifies certificate validity by time...

**Comment by arachnist** [comment] 2016-02-12 19:23
Not everything runs on the wild, open internet.

It might be desirable to turn off this feature, for example, when running regression tests against an app that had a time-dependent issue.

**Comment by poettering** [comment] 2016-02-12 19:26
"might be desirable"? So you are not even having this problem, but the issue is purely theoretical so far?

**Comment by arachnist** [comment] 2016-02-12 19:28
In a way, yes - I'm not having this issue as I'm not running systemd on production systems, but I might have to eventually.

**Comment by poettering** [comment] 2016-02-12 19:35
OK, then let's close this. As soon as somebody actually needs this, we can reopen this. Thank you for your understanding.

**Closed as completed by poettering** 2016-02-12 19:35 UTC
