### ISSUE TITLE
Allow timer users to start and stop services in one

### ISSUE THREAD

**Issue by vadi2** [systemd/systemd#28684] opened 2023-08-05 07:25 UTC
### Component

systemd

### Is your feature request related to a problem? Please describe

I'd like to have a service that runs at night only and shuts down in the morning. It turns out that it's [rather cumbersome](https://askubuntu.com/questions/1480975/how-to-start-and-stop-a-systemd-service-on-a-timer) to set this up, requiring 2 service and 2 timer files (4 configuration files in total) - it would be great if the setup was simpler.

### Describe the solution you'd like

A single timer file that can both start and stop the service.

### Describe alternatives you've considered

N/A

### The systemd version you checked that didn't have the feature you are asking for

249

**Comment by dtardon** [comment] 2023-08-08 08:31
This is a duplicate of #17311.

**Closed as not planned by dtardon** 2023-08-08 08:31 UTC
Labels: RFE 🎁, pid1, duplicate
