### ISSUE TITLE
Symlinks in /etc/systemd/logind.conf.d/ are ignored

### ISSUE THREAD

**Issue by jfly** [systemd/systemd#12410] opened 2019-04-26 03:38 UTC
**Note**: I did find a workaround for this, see the bottom for a description.

**systemd version the issue has been seen with**
> I started running into this problem after Arch pacman updated systemd from 241.93-1 -> 242.0-1

**Used distribution**
 > Arch Linux

**Steps to reproduce the problem**

I have two symlinks set up in `/etc/systemd/logind.conf.d/`:

```
➜  ~ ls -alh /etc/systemd/logind.conf.d/
total 16K
drwxr-xr-x 2 root root 4.0K Mar 19 05:36 .
drwxr-xr-x 6 root root 4.0K Apr 24 13:15 ..
lrwxrwxrwx 1 root root   75 Mar 19 05:36 no-suspend-on-lidswitch.conf -> /home/jeremy/.dotfiles/etc/systemd/logind.conf.d/no-suspend-on-lidswitch.conf
lrwxrwxrwx 1 root root   74 Mar 19 05:36 suspend-on-powerbutton.conf -> /home/jeremy/.dotfiles/etc/systemd/logind.conf.d/suspend-on-powerbutton.conf
```

Inside of these files, I have overridden `HandleLidSwitch` and `HandlePowerKey`:

```
➜  ~ cat /home/jeremy/.dotfiles/etc/systemd/logind.conf.d/no-suspend-on-lidswitch.conf 
[Login]
HandleLidSwitch=ignore
➜  ~ cat /home/jeremy/.dotfiles/etc/systemd/logind.conf.d/suspend-on-powerbutton.conf 
[Login]
HandlePowerKey=suspend
```

**Expected behavior you didn't see**
When I close my lid, I want my laptop to stay awake. That is not happening =(

**Unexpected behavior you saw**
When I close my laptop's lid, it goes to sleep.

**Workaround**
If I instead copy these files rather than setting up symlinks, things work as desired.

**Comment by keszybz** [comment] 2019-04-26 07:24
Is /home on a separate partition?

**Comment by FatBoyXPC** [comment] 2019-04-26 07:37
I have the same issue, and for me it's on the same partition.

**Comment by keszybz** [comment] 2019-04-26 07:40
It might be caused by the ownership checks when following symlinks. Nevertheless, I can't reproduce this here.

**Comment by FatBoyXPC** [comment] 2019-04-26 07:44
I can reproduce this the same exact way. Did you try this on 241?

**Comment by poettering** [comment] 2019-04-26 08:03
`systemd-logind.service` has `ProtectHome=yes` set these days, so that it lives in a tight sandbox without access to the users home directories. If you symlink stuff over, then you need to turn that off, of course.

In the general case sandboxing things tightly is a good thing though, and normally there should be no reason why logind should get access to the user's home directory. Hence, closing.

**Comment by keszybz** [comment] 2019-04-26 08:04
Ah, OK. I was lazy and I made a dir underneath /etc for the symlink targets. Stupid.

**Closed as completed by poettering** 2019-04-26 08:03 UTC
Labels: login, not-a-bug

**Comment by FatBoyXPC** [comment] 2019-04-26 13:58
@poettering interesting! The reason we have this setup is to make installing our changes on new machines easier, so we track these logind files in our dotfiles repo and symlink it when necessary. How do you suggest we can still easily do that?

Right now the fix is to copy the files instead of symlink them, but I'm not a big fan of that because if I change the file I might change the file at `/etc/systemd/logind.conf.d/` rather than `~/.dotfiles/etc/systemd/logind.conf.d/`, which means the change doesn't make it into the repo.

**Comment by keszybz** [comment] 2019-04-26 14:23
systemd-logind.service has `ProtectHome=yes, ProtectSystem=strict, ReadWritePaths=/etc /run`. You have two choices: either move those config files somewhere under /etc, /run/, or /usr, or amend the service configuration to allow access to other locations (through a dropin or otherwise).

**Comment by FatBoyXPC** [comment] 2019-04-26 14:57
If I move those files to `/etc`, `/run`, or `/usr` those still can' be symlinks, and it's not like I want my dotfiles hosted in a root directory (as that makes it hard to change).

Will this follow the full symlink trail or only one level? Such as: what if I were to symlink `~/.dotfiles/foo` to `/etc/foo` then symlink that to the appropriate location? I currently expect this to not work.

Is there a way to amend the service that I can track in my home directory?

**Comment by poettering** [comment] 2019-06-20 14:07
You can turn of ProtectHome by adding a unit file drop-in that just sets ProtectHome=no in the [Service] section. Use systemctl edit

**Comment by FatBoyXPC** [comment] 2019-06-26 19:27
Thanks! Now I've only got one file to copy via root rather than a few, and can go back to my nicely managed symlinks!
