### ISSUE TITLE
Introduce something like systemctl --verbose

### ISSUE THREAD

**Issue by lnykryn** [systemd/systemd#2297] opened 2016-01-11 12:04 UTC
It would be nice to have a possibility to show which units were affected by a systemctl command.

For example show stopped units in the case that starting unit has a Conflicts dependencies.

**Comment by karelzak** [comment] 2016-01-12 11:44
How we keep track about such things?  TriggeredBy and ConflictedBy unit properties?

**Comment by johannbg** [comment] 2016-01-12 12:00
Bare in mind that systemctl is not limited to just type service units so if and then when this would be implemented you have to take into account all the different types of units systemctl supports and support that there as well and personally I'm not seeing how you can implement this graceful manner due to the complexity it can involve.

**Comment by lnykryn** [comment] 2016-01-12 14:22
The initial idea here is to somehow print the transaction.

**Comment by poettering** [comment] 2016-01-12 15:45
Has been requested before. Makes sense. Not trivial to do though, as it would require us to beef up the bus calls considerably to return the installed transaction set to the client on each call.

**Comment by poettering** [comment] 2016-01-27 01:13
Duplicate of #1287.

**Comment by poettering** [comment] 2019-02-20 14:31
(dedup'ed, since it's slighty differet from #1287)

**Comment by poettering** [comment] 2019-03-26 17:06
Fix waiting in #12115

**Closed as completed** 2019-03-28 10:04 UTC
Labels: RFE 🎁, pid1, systemctl, downstream/rhel
