### ISSUE TITLE
black screen since systemd update

### ISSUE THREAD

**Issue by edpil02** [systemd/systemd#13296] opened 2019-08-09 18:04 UTC
Fedora rawhide upgrade to systemd-243~rc1, since  got a black screen at login with sddm display manager and nvidia drivers.

That's weird because i have no crash, no error with systemctl, sddm.service is active and i can run startx from another console.
Found a error in xorg.log :
Failed to open authorization file "/var/run/sddm/{2e9cf9dd-f647-4656-b355-a1449cef57e4}": No such file or directory

Downgrade systemd (242) solves th issue.
Sorry for my english

**Comment by poettering** [comment] 2019-08-12 18:46
this is not actionable to us. Please provide a full log excerpt of anything around the issue, otherwise there's little we can do.

**Comment by ivanbardov** [comment] 2019-08-30 04:28
Same here on Gentoo with both 243-rc1 and 243-rc2

Downgrading to v242 (and below) helps. Also I can mitigate the issue by logging as root in tty2 for example and executing `systemctl stop sddm.service` and `systemctl start sddm.service`. After that everything seems to work fine. So the whole issue seems to be about inability of sddm to autostart.

I've posted [a question on Gentoo Forums](https://forums.gentoo.org/viewtopic-t-1101164.html) about this a few days before. For your convenience, I'll copy link to logs below here:

[journalctl -b](https://pastebin.com/aeiSsj2c)
[dmesg](https://pastebin.com/ArK7AmF3)
[systemctl list-dependencies](https://pastebin.com/Uevc4gXn)
[Gentoo make.conf](https://pastebin.com/w59MerAu)
[list of all installed packages using qlist -Iv.txt](https://pastebin.com/1Q4uDQ59)

If any other info is needed, please let me know.

**Comment by edpil02** [comment] 2019-08-30 05:04
I noticed that i have no issue  when i put the nvidia modules in initramfs or try gdm display manager.

Seems to be some delay driver load or service problem  between sddm and  systemd.
I also filed a bug report to sddm upstream , expecting to find what services are required or faulty.

**Comment by ivanbardov** [comment] 2019-09-12 05:30
@poettering 

Upgraded to 243 stable.
sys-apps/systemd-243:0/2::gentoo  USE="acl gcrypt kmod lz4 lzma pam pcre (policykit) resolvconf seccomp (split-usr) sysv-utils -apparmor -audit -build -cgroup-hybrid -cryptsetup -curl -dns-over-tls -elfutils -gnuefi -http -idn -importd -nat -qrcode (-selinux) -test -vanilla -xkb" ABI_X86="32 (64) (-x32)"

So far, nothing has changed, same blackscreen as mentioned in comment above: https://github.com/systemd/systemd/issues/13296#issuecomment-526450906

If there are any other logs required, I'd gladly provide them.

**Comment by kwizart** [comment] 2019-09-16 08:17
@edpil02 @ivanbardov 
It seems like a full log of what's happen is still requested

Link of the sddm report as mentioned (but without logs even).
https://github.com/sddm/sddm/issues/1190

**Comment by keszybz** [comment] 2019-09-16 13:02
We changed the job ordering in v243. Before it was more pseudorandom, now we sort the jobs to make to put various "quick" jobs first. This is an implementation detail, but it might trigger some race.

I don't think we can solve this based on the reports for far. I know nobody in systemd upstream uses sddm, and so far we have no error messages or particular misbehaviour reported.

**Comment by keszybz** [comment] 2019-09-16 13:46
Fedora bug: https://bugzilla.redhat.com/show_bug.cgi?id=1728240.

**Comment by Plagman** [comment] 2019-09-16 16:18
@keszybz I posted errors spewed by the GPU driver in the other bug you closed. https://github.com/systemd/systemd/issues/13562

**Comment by keszybz** [comment] 2019-09-16 18:15
Sure, looks like some kernel driver is unhappy. But the relation to systemd is unclear.

**Comment by ivanbardov** [comment] 2019-09-16 19:29
> @edpil02 @ivanbardov
> It seems like a full log of what's happen is still requested
> 
> Link of the sddm report as mentioned (but without logs even).
> [sddm/sddm#1190](https://github.com/sddm/sddm/issues/1190)

Sorry for being noob here, I thought links I posted above (with journalctl and dmesg etc) could be considered 'full log'. Looks like I was wrong. If there's there any specific guide how to provide more info regarding systemd issues, kindly throw a link at me please.

**Comment by edpil02** [comment] 2019-09-16 19:33
@keszybz 
When my display kernel module (gtx1080)  is in initramfs sddm starts , otherwise, black screen.
So i  think that sddm starts before the driver is loaded with systemd 243.( After the black screen, systemctl start sddm is successful from another console).
Sorry for my english.

**Comment by RPigott** [comment] 2019-09-16 22:21
@ivanbardov sddm and Xorg each have logs that could be useful I think.

**Comment by keszybz** [comment] 2019-09-17 07:08
> So i think that sddm starts before the driver is loaded with systemd 243.

That sounds like a bug in sddm. It must be able to react to hotplug events and spawn a display whenever hardware is detected.

**Comment by edpil02** [comment] 2019-09-17 07:30
-->   That sounds like a bug in sddm.

Yes ! But why downgrade to systemd 242 solves the problem.

**Comment by keszybz** [comment] 2019-09-17 07:53
> But why downgrade to systemd 242 solves the problem.

If it is a race condition, and sddm fails if it is started a bit earlier, and works if it is started a bit later, then it is possible that unrelated changes in systemd cause the problem to be more visible than it was before. But the fix would still need to be in sddm. (Assuming that this is the issue. At this point it's just a hypothesis.)

**Comment by edpil02** [comment] 2019-09-17 10:19
| But the fix would still need to be in sddm.

 I think your are probably  right , because  there is no issue when  sddm is replaced by gdm manager.

**Comment by ivanbardov** [comment] 2019-09-17 12:25
> @ivanbardov sddm and Xorg each have logs that could be useful I think.

Thanks.
Couldn't find logs related to sddm even with 'find' command, so attaching Xorg.0.log only.
Dmesg and journalctl -b are pretty much similar to those posted before (regarding discussed issue), just a tad newer. 

[Xorg.0.log](https://pastebin.com/ESHQKnnu)
[dmesg](https://pastebin.com/80LZuNCe)
[journalctl -b](https://pastebin.com/rw3wA2ug)

**Comment by dashingderpderp** [comment] 2019-10-20 16:43
So, the issue happens when logind starts up before the display driver does. In that case, "CanGraphical" property starts off as false and SDDM observes for PropertyChanged to see if "CanGraphical" eventually changes. However, logind doesn't seem to emit changes to "CanGraphical". I can see changes made to ActiveSession are sent, but nothing else. This doesn't happen in lightdm because lightdm just continuously polls for that property rather than looking for DBus signal for PropertyChanged.

**Comment by keszybz** [comment] 2019-10-21 07:27
Thanks for the investigation. I don't see the signal either. I'll look into it.

**Comment by mozo78** [comment] 2019-10-26 07:36
Same here on Arch. Downgrading to 242 solves the problem.

**Comment by keszybz** [comment] 2019-10-26 09:14
This should be fixed with #13811. Can somebody confirm this?

**Comment by mozo78** [comment] 2019-10-26 09:26
I want to try it but I don't know how. Will wait for feedback too.

**Comment by dashingderpderp** [comment] 2019-10-26 19:17
The problem is fixed with latest systemd now. Tried to manually load my drm driver after blacklisting it and SDDM showed up automagically. Also tried to reproduce the scenario where SDDM loading before drm driver would have caused SDDM to not load, and I confirm that's fixed as well. See [https://pastebin.com/ugr4yRSU](journalctl -b) for the correct behavior after late drm driver loading. SDDM loads before drm and picks up the display once drm is loaded.

Thanks for the fix!

**Comment by keszybz** [comment] 2019-10-27 08:54
Thanks for testing.

**Closed as completed by keszybz** 2019-10-27 08:54 UTC
Labels: login

**Comment by ivanbardov** [comment] 2019-10-28 13:28
Using systemd 243-405-ge9cfc71+ now. The problem is gone, I can use sddm again. Thanks.
