### ISSUE TITLE
Mount efivarfs read-only

### ISSUE THREAD

**Issue by orbea** [systemd/systemd#2502] opened 2016-02-01 17:40 UTC
Its really unfortunate and not cool at all to lock issues when they are still relevant and of such a terrible nature.  So here it is again, don't lock it again Puttering.

"Locking this one. Note sure which peanut gallery site linked this..." - Puttering

"Mounting efivarfs read/write by default can lead to accidental deletion of the EFI variables. It was already reported on Arch Linux forums, that running 'rm -rf' over a directory structure with mounted efivarfs did actually "hard-brick" some MSI notebook."

Can you disable this potentially malicious functionality?  Its not appreciated at all.

Also I understand its possible to accidentally overwrite these vars when making a chroot for another distro.
i.e. "mount /dev dev" "mount /sys sys"

**Comment by poettering** [comment] 2016-02-01 17:46
Duplicate of #2402. Also, insulting. Closing.

Please troll elsewhere, thanks.

**Closed as completed by poettering** 2016-02-01 17:46 UTC
Labels: duplicate, unproductive
