### ISSUE TITLE
Restart= in combination with BindsTo= ineffective on device rediscovery

### ISSUE THREAD

**Issue by eomanis** [systemd/systemd#2824] opened 2016-03-11 00:42 UTC
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229-3
### Used distribution

> Arch Linux ARM on armv7l, Linux 4.4.2-1
### Situation

This is a Cubieboard2 (Allwinner A20) providing a wireless access point using hostapd by means of a wireless network USB dongle.

Hostapd service file shipped by the distribution:
/usr/lib/systemd/system/hostapd.service 

```
[Unit]
Description=Hostapd IEEE 802.11 AP, IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
After=network.target

[Service]
ExecStart=/usr/bin/hostapd /etc/hostapd/hostapd.conf
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target
```

Drop-in snippet to delay the start of hostapd.service until the wireless network USB device is available:
/etc/systemd/system/hostapd.service.d/requiresdevice.conf

```
[Unit]
After=sys-subsystem-net-devices-wlan0.device
BindsTo=sys-subsystem-net-devices-wlan0.device
```

Drop-in snippet for automatic restart:
/etc/systemd/system/hostapd.service.d/restart.conf

```
[Service]
Restart=always
RestartSec=15
```

From time to time the wireless network is gone.
This is apparently due to the wireless network USB device becoming disconnected, and then being reconnected a few seconds later (as shown by `dmesg`).
Because of BindsTo=, systemd then stops hostapd.service (as shown by `systemctl status hostapd.service`).
Despite having configured an automatic restart, hostapd.service is not restarted by systemd after the wireless network device is available again.
In such a state, manually starting hostapd.service using "systemctl start hostapd.service" works flawlessly.

`man systemd.service` says:

> When the death of the process is a result of systemd operation (e.g. service stop or restart), the service will not be restarted.

I assume systemd considers stopping a service due to BindsTo= and device loss as being a systemd operation, and therefore does not make any attempt to start it again.
### In case of bug report: Expected behaviour you didn't see

> hostapd.service being restarted after device rediscovery
### In case of bug report: Unexpected behaviour you saw

> hostapd.service stays in stopped state despite having an automatic restart configured
### In case of bug report: Steps to reproduce the problem

> Probably creating a dummy .service unit with After=, BindsTo= and Restart= that binds to a USB device that can be plugged/unplugged can reproduce this behavior (not tested).

Also see this post in the Arch Linux forums:
[https://bbs.archlinux.org/viewtopic.php?id=209783](https://bbs.archlinux.org/viewtopic.php?id=209783)

Possibly systemd should perceive a BindsTo= service that has been stopped due to device loss as "failed" instead of "stopped by systemd".
The reasoning being that you configure a service with BindsTo= because it should terminate by itself when its device(s) are gone, but fails to do so (hostapd), and you need systemd just to help the service program in doing what it should be doing by itself in the first place, namely failing.
Hence a service stop because of BindsTo= should be considered as the service having failed.

**Comment by arvidjaar** [comment] 2016-03-11 05:15
Try adding `SYSTEMD_WANTS+="hostapd.service"` udev rule to your network device.

**Comment by eomanis** [comment] 2016-03-11 13:06
> Try adding SYSTEMD_WANTS+="hostapd.service" udev rule to your network device.

Writing an udev rule did come to my mind, but it strikes me as unnecessary hardship for users and adminstrators facing a rather mundane use case like this.

Seeing that one of systemd's core competences is the management of services and their dependencies, being able to have this handled by systemd alone would be much appreciated. It's less complex that way for users.

Also, systemd itself obviously has tight integration with udev already - otherwise, how would After=<device> and BindsTo=<device> work at all?
If systemd can start the service on device discovery at system startup, then it can surely easily start it at any time later again.

To clarify, I'll just quote from the Arch Linux forums post:

> Is it possible, with the features systemd brings to the table, to have a service that was terminated due to device loss be restarted automatically once said device becomes available again?

What also should be considered here is that users very possibly want a different behavior when they specify Restart=. The fact that they also want to have a service process killed on device loss with BindsTo= is not an excuse for Restart= not working when that happens.

**Comment by arvidjaar** [comment] 2016-03-11 14:08
@eomanis Well, another option is to make device Want your service by adding corresponding links in .../device.wants. End result is the same - you need to somehow tell systemd to start service when device appears.

**Comment by poettering** [comment] 2016-04-15 09:54
This is really a misunderstanding. Restart= only has an effect if the service exits on its own. By defining BindsTo= from the device unit you explicitly say that the service shell be terminated when the device goes away. That takes precedence over Restart=...

Using BindsTo= from the device to the service and pulling the device is pretty much like invoking "systemctl stop" manually from the command line. In that you wouldn't want the Restart= switch to undo what you just explicitly, manually did, would you?

hope this makes sense.

Closing, since this is intended behaviour.

**Comment by poettering** [comment] 2016-04-15 09:55
adding to this: if you think BindsTo= isn#t right for you service, then please contact the maintainers of that service, as that's under their control really, not systemd upstream.

**Closed as completed by poettering** 2016-04-15 09:54 UTC
Labels: pid1, not-a-bug

**Comment by eomanis** [comment] 2016-04-16 23:05
Well yes, really, you do get what it says on the packaging.

It just seems odd – you have an enabled service for which all requirements are met, and that has Restart=, and yet it does not come up again.
The only situation where you would want this is when you stopped the service manually, and it sort of catches you off guard.

Maybe what would be convenient would be some sort of counterpart to BindsTo= that brings a service up once a device appears, so it spares you from using udev directly – after all, you have such a great abstraction from all the udev intricacies at your disposal, and it is called systemd.

Enough of the whining, a udev rule that works for me:
/etc/udev/rules.d/50-net-wlan0_start-hostapd.rules

```
# Start hostapd.service when wlan0 is discovered
SUBSYSTEM=="net", KERNEL=="wlan0", TAG+="systemd", ENV{SYSTEMD_WANTS}="hostapd.service"
```

Thank you for your time.

**Comment by dimitry-ishenko** [comment] 2016-08-17 19:04
@eomanis if you don't want to mess with udev rules, you could create `.wants` directory for `wlan0` and add a symlink to `hostapd.service` inside to achieve the same result, eg:

```
cd /etc/systemd/system
mkdir sys-subsystem-net-devices-wlan0.device.wants/
cd sys-subsystem-net-devices-wlan0.device.wants
ln -s /usr/lib/systemd/system/hostapd.service
```

Sorry, for beating a dead horse...

**Comment by eomanis** [comment] 2016-08-19 17:29
@dimitry-ishenko Thank you for the suggestion. I'm pretty sure I tried that at some point, but it did not work for me then, and I assumed that this kind of thing wasn't supported for .devices. Maybe I got some detail wrong in my confusion.
Anyway I think I'll try it again if you think it should work, because I would favor it compared to the udev rule.

Edit: I'll be damned, it works. So simple.
dimitry-ishenko, you are the best.

**Comment by dimitry-ishenko** [comment] 2016-08-19 18:56
Thank you, I'll be here all week ;)

**Comment by Grewfisk** [comment] 2017-03-09 07:37
@eomanis @dimitry-ishenko 
I ran into a similar need and discovered that instead of manually creating the symlink you can just add
`WantedBy=multi-user.target sys-subsystem-net-devices-wlan0.device`
to your service file under the [Install] section and systemd will create the symlink for that device when you enable (install) the service.

In my case had a daemon that needed to be killed if a network filesystem became unmounted for any reason.

**Comment by dimitry-ishenko** [comment] 2017-03-10 21:39
@Grewfisk even better. Thank you

**Comment by vadirajjahagirdar** [comment] 2017-05-22 13:51
@Grewfisk : your method din't work on CentOS.
@dimitry-ishenko It works, thanks a million

**Comment by dimitry-ishenko** [comment] 2017-05-22 19:45
@vadirajjahagirdar you are welcome

**Comment by alex-ball** [comment] 2025-01-31 16:02
> [@Grewfisk](https://github.com/Grewfisk) : your method din't work on CentOS.

It's important to know that the `[Install]` section is **only** used by `systemctl enable` and `systemctl disable`.

So if you add new bits to that section, you must run `systemctl enable <your unit>` afterwards in order for the new symlinks to be written.
