### ISSUE TITLE
Error unmounting /var/log partition with journal log files enabled

### ISSUE THREAD

**Issue by fjromerom** [systemd/systemd#6247] opened 2017-06-30 09:39 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

> Systemd version: 229-4ubuntu17

### Used distribution

> Ubuntu 16.04.2 LTS

### In case of bug report: Expected behaviour you didn't see

> Umount correctly /var/log partition

### In case of bug report: Unexpected behaviour you saw

> systemd[1]: Unmounting /var/log...
umount[18542]: umount: /var/log: target is busy
umount[18542]:         (In some cases useful info about processes that
umount[18542]:          use the device is found by lsof(8) or fuser(1).)
systemd[1]: Unmounted /run/user/1000.
systemd[1]: var-log.mount: Mount process exited, code=exited status=32
systemd[1]: Failed unmounting /var/log.

### In case of bug report: Steps to reproduce the problem

> 1. Enable persistent log files in Journal.
> 2. Mount a partition in /var/log
> 3. Reboot the system
> 4. Running "journalctl -r" you will see the previous error

**Comment by evverx** [comment] 2017-06-30 09:57
The same issue seems to be discussed in https://github.com/systemd/systemd/issues/867.

**Comment by poettering** [comment] 2017-07-11 13:56
Let's close this as duplicate of #867

**Closed as completed by poettering** 2017-07-11 13:56 UTC
Labels: journal, pid1, duplicate
