### ISSUE TITLE
Fedora 29 ARMv7HL systemd-journald: Failed to open runtime journal: Cannot allocate memory 

### ISSUE THREAD

**Issue by omerule** [systemd/systemd#11687] opened 2019-02-10 10:19 UTC
Goodmorning,
With version  systemd-239-9.gite339eae.fc29.src.rpm 
The system is killing processen and dmesg ringbuffer is full with this warning:  systemd-journald: Failed to open runtime journal: Cannot allocate memory.
Have been using Linux for some time now.
But i really don't know what todo with this issue.

Why does systemd-journalctl generate these warnings if posible with some context please?

Yours Kindly
Roel

**Comment by poettering** [comment] 2019-02-11 16:57
Can you run "strace" on journald when this happens, to see which syscalls are done internally in the process and might cause the ENOMEM?

Use a cmdline like this: `strace -s 500 -p $(systemctl show --value -p MainPID systemd-journald.service)` and record a few iterations of the error as it happens.

**Comment by ahuillet** [comment] 2019-02-18 09:50
```
mkdir("/var/log/journal/cd3dc0245fe35e710d4f53c74a1bc43a", 0755) = -1 EEXIST (File exists)
openat(AT_FDCWD, "/var/log/journal/cd3dc0245fe35e710d4f53c74a1bc43a/system.journal", O_RDWR|O_CREAT|O_NONBLOCK|O_LARGEFILE|O_CLOEXEC, 0640) = 27
fcntl64(27, F_GETFL)                    = 0x8802 (flags O_RDWR|O_NONBLOCK|O_LARGEFILE)
fcntl64(27, F_SETFL, O_RDWR|O_LARGEFILE) = 0
fstat64(27, {st_mode=S_IFREG|0640, st_size=6553600, ...}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=596303, tv_nsec=161674573}) = 0
mmap2(NULL, 6553600, PROT_READ|PROT_WRITE, MAP_SHARED, 27, 0) = -1 ENOMEM (Cannot allocate memory)
close(27)                               = 0
writev(7, [{iov_base="<44>", iov_len=4}, {iov_base="systemd-journald", iov_len=16}, {iov_base="[223]: ", iov_len=7}, {iov_base="Failed to open system journal: Cannot allocate memory", iov_len=53}, {iov_base="\n", iov_len=1}], 5) = 81
mkdir("/run/log", 0755)                 = -1 EEXIST (File exists)
mkdir("/run/log/journal", 0755)         = -1 EEXIST (File exists)
stat64("/run/log/journal/cd3dc0245fe35e710d4f53c74a1bc43a", {st_mode=S_IFDIR|S_ISGID|0750, st_size=60, ...}) = 0
openat(AT_FDCWD, "/run/log/journal/cd3dc0245fe35e710d4f53c74a1bc43a/system.journal", O_RDWR|O_CREAT|O_NONBLOCK|O_LARGEFILE|O_CLOEXEC, 0640) = 27
fcntl64(27, F_GETFL)                    = 0x8802 (flags O_RDWR|O_NONBLOCK|O_LARGEFILE)
fcntl64(27, F_SETFL, O_RDWR|O_LARGEFILE) = 0
fstat64(27, {st_mode=S_IFREG|0640, st_size=8388608, ...}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=596303, tv_nsec=172834034}) = 0
mmap2(NULL, 8388608, PROT_READ|PROT_WRITE, MAP_SHARED, 27, 0) = -1 ENOMEM (Cannot allocate memory)
close(27)                               = 0
writev(7, [{iov_base="<43>", iov_len=4}, {iov_base="systemd-journald", iov_len=16}, {iov_base="[223]: ", iov_len=7}, {iov_base="Failed to open runtime journal: Cannot allocate memory", iov_len=54}, {iov_base="\n", iov_len=1}], 5) = 82
clock_gettime(CLOCK_REALTIME, {tv_sec=1550483179, tv_nsec=916172594}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1550483179, tv_nsec=917173281}) = 0
epoll_wait(8, [{EPOLLIN, {u32=35679328, u64=35679328}}, {EPOLLIN, {u32=35679776, u64=35679776}}], 29, 0) = 2
clock_gettime(CLOCK_REALTIME, {tv_sec=1550483179, tv_nsec=918685276}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=596303, tv_nsec=186420691}) = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=596303, tv_nsec=191468335}) = 0
read(9, "44,53222,596303144836,-;systemd-journald[223]: Failed to open system journal: Cannot allocate memory\n", 8192) = 101
clock_gettime(CLOCK_REALTIME, {tv_sec=1550483179, tv_nsec=925863221}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1550483179, tv_nsec=926508206}) = 0
epoll_wait(8, [{EPOLLIN, {u32=35679328, u64=35679328}}, {EPOLLIN, {u32=35679776, u64=35679776}}], 29, 0) = 2
clock_gettime(CLOCK_REALTIME, {tv_sec=1550483179, tv_nsec=928002881}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=596303, tv_nsec=195651622}) = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=596303, tv_nsec=196273280}) = 0
read(9, "43,53223,596303161654,-;systemd-journald[223]: Failed to open runtime journal: Cannot allocate memory\n", 8192) = 102
clock_gettime(CLOCK_REALTIME, {tv_sec=1550483179, tv_nsec=930772090}) = 0
clock_gettime(CLOCK_REALTIME, {tv_sec=1550483179, tv_nsec=933662544}) = 0
epoll_wait(8, [{EPOLLIN, {u32=35679328, u64=35679328}}], 29, 0) = 1
clock_gettime(CLOCK_REALTIME, {tv_sec=1550483179, tv_nsec=935235162}) = 0
clock_gettime(CLOCK_MONOTONIC, {tv_sec=596303, tv_nsec=202845282}) = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=596303, tv_nsec=203684984}) = 0
ioctl(3, FIONREAD, [158])               = 0
recvmsg(3, {msg_name=0xbf9df254, msg_namelen=128->0, msg_iov=[{iov_base="<22>Feb 18 10:46:19 dovecot: imap-login: Login: user=<arthur>, method=PLAIN, rip=192.168.0.6, lip=192.168.0.6, mpid=17062, secured, session=<UJIl/yeC2ITAqAAG>", iov_len=24575}], msg_iovlen=1, msg_control=[{cmsg_len=20, cmsg_level=SOL_SOCKET, cmsg_type=SCM_TIMESTAMP, cmsg_data={tv_sec=1550483179, tv_usec=811898}}, {cmsg_len=24, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS, cmsg_data={pid=291, uid=0, gid=0}}], msg_controllen=44, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = 158
clock_gettime(CLOCK_MONOTONIC, {tv_sec=596303, tv_nsec=207251992}) = 0
openat(AT_FDCWD, "/proc/291/comm", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 27
fstat64(27, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
read(27, "log\n", 1024)                 = 4
read(27, "", 1024)                      = 0
close(27)                               = 0
readlinkat(AT_FDCWD, "/proc/291/exe", "/usr/lib/dovecot/log", 4096) = 20
openat(AT_FDCWD, "/proc/291/cmdline", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 27
ugetrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM_INFINITY}) = 0
mmap2(NULL, 2101248, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
brk(0x2c27000)                          = 0x2a06000
mmap2(NULL, 2232320, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
mmap2(NULL, 2097152, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = -1 ENOMEM (Cannot allocate memory)
mmap2(NULL, 1048576, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0xb6075000
munmap(0xb6075000, 1048576)             = 0
mmap2(NULL, 2101248, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1 ENOMEM (Cannot allocate memory)
close(27)                               = 0
openat(AT_FDCWD, "/proc/291/status", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 27
```

The above is my own system with the same error. But, there's plenty of memory free.
```
# free -m         
              total        used        free      shared  buff/cache   available
Mem:           2006         403         343           8        1259        1348
```

**Comment by poettering** [comment] 2019-02-18 11:04
Judging by the strace this appears to be a duplicate of #11502. Closing hence as duplicate. Please upgrade to a version that has the #11502 fix applied.

**Closed as completed by poettering** 2019-02-18 11:04 UTC
Labels: journal, duplicate

**Comment by ahuillet** [comment] 2019-02-18 12:29
Do you know what version number that would be?
Thanks

**Comment by poettering** [comment] 2019-02-18 12:33
depends on your distro, i.e. whether they backported the fix or not. It's included in the upstream version v241.

**Comment by omerule** [comment] 2019-02-21 16:33
Good afternoon,
For more than a few days, the above problem has disappeared from the RaspberryPi3 Fedora29 armv7.
The current installed systemd version is also newer:
systemd-239-11.git4dc7dce.fc29.src.rpm
Although I now get this message in the dmesg ringbuffer at startup:
"
systemd-journald[597]: File /var/log/journal/9f5bb84cccb040b8ba61fabc6208395f/user-1000.journal corrupted or uncleanly shut down, renaming and replacing.
"
And the command: sudo journalctl --verify says "PASS: /var/log/journal"

Is there something I can do about this message, should I make a different call?

Yours kindly
Roel
