### ISSUE TITLE
Coverity (recoverable) build errrors/warnings

### ISSUE THREAD

**Issue by mrc0mmand** [systemd/systemd#18251] opened 2021-01-14 23:02 UTC
I was curious to see what's hiding behind the `Warning:  Recoverable errors were encountered during 3 of these C/C++ compilation units.` message Coverity prints after building systemd and it looks there's a couple of things which Coverity can't handle:

### Warnings

`src/login/logind-button.c`
```
2021-01-14T16:06:32.3190741Z "../src/login/logind-button.c", line 234: warning #32: expression must have
2021-01-14T16:06:32.3191556Z           arithmetic type
2021-01-14T16:06:32.3192275Z                   unsigned long keys[CONST_MAX5(KEY_POWER, KEY_POWER2, KEY_SLEEP, KEY_SUSPEND, KEY_RESTART)/ULONG_BITS+1];
2021-01-14T16:06:32.3193068Z        

2021-01-14T16:06:32.3201804Z "../src/login/logind-button.c", line 263: warning #145: variable "types" may
2021-01-14T16:06:32.3202371Z           not be initialized
2021-01-14T16:06:32.3202837Z                   types[CONST_MAX(EV_KEY, EV_SW)/ULONG_BITS+1] = {},
2021-01-14T16:06:32.3203245Z                   ^

2021-01-14T16:06:32.3208157Z "../src/login/logind-button.c", line 264: warning #32: expression must have
2021-01-14T16:06:32.3208745Z           arithmetic type
2021-01-14T16:06:32.3209397Z                   keys[CONST_MAX5(KEY_POWER, KEY_POWER2, KEY_SLEEP, KEY_SUSPEND, KEY_RESTART)/ULONG_BITS+1] = {},
2021-01-14T16:06:32.3210116Z                        ^

2021-01-14T16:06:32.3211066Z "../src/login/logind-button.c", line 265: warning #145: variable "switches" may
2021-01-14T16:06:32.3211659Z           not be initialized
2021-01-14T16:06:32.3212158Z                   switches[CONST_MAX(SW_LID, SW_DOCK)/ULONG_BITS+1] = {};
2021-01-14T16:06:32.3212789Z                   ^

2021-01-14T16:06:32.3227689Z "../src/login/logind-button.c", line 354: warning #145: variable "switches" may
2021-01-14T16:06:32.3228266Z           not be initialized
2021-01-14T16:06:32.3228789Z           unsigned long switches[CONST_MAX(SW_LID, SW_DOCK)/ULONG_BITS+1] = {};
2021-01-14T16:06:32.3229611Z                         ^

2021-01-14T16:06:32.3230429Z "../src/login/logind-button.c", line 225: warning #1563: function
2021-01-14T16:06:32.3231112Z           "button_suitable" not emitted, consider modeling it or review parse
2021-01-14T16:06:32.3231730Z           diagnostics to improve fidelity
2021-01-14T16:06:32.3232208Z   static int button_suitable(int fd) {
2021-01-14T16:06:32.3232774Z              ^

2021-01-14T16:06:32.3233616Z "../src/login/logind-button.c", line 353: warning #1563: function
2021-01-14T16:06:32.3234326Z           "button_check_switches" not emitted, consider modeling it or review
2021-01-14T16:06:32.3235477Z           parse diagnostics to improve fidelity
2021-01-14T16:06:32.3236122Z   int button_check_switches(Button *b) {
2021-01-14T16:06:32.3236497Z       ^

2021-01-14T16:06:32.3237320Z "../src/login/logind-button.c", line 261: warning #1563: function
2021-01-14T16:06:32.3238003Z           "button_set_mask" not emitted, consider modeling it or review parse
2021-01-14T16:06:32.3239365Z           diagnostics to improve fidelity
2021-01-14T16:06:32.3240051Z   static int button_set_mask(const char *name, int fd) {
```

`src/sysv-generator/sysv-generator.c`
```
2021-01-14T16:06:50.2511545Z "../src/sysv-generator/sysv-generator.c", line 816: warning #145: variable
2021-01-14T16:06:50.2512599Z           "runlevel_services" may not be initialized
2021-01-14T16:06:50.2513188Z           Set *runlevel_services[ELEMENTSOF(rcnd_table)] = {};
2021-01-14T16:06:50.2513635Z                ^

2021-01-14T16:06:50.2559338Z "../src/sysv-generator/sysv-generator.c", line 815: warning #1563: function
2021-01-14T16:06:50.2560665Z           "set_dependencies_from_rcnd" not emitted, consider modeling it or
2021-01-14T16:06:50.2561516Z           review parse diagnostics to improve fidelity
2021-01-14T16:06:50.2562233Z   static int set_dependencies_from_rcnd(const LookupPaths *lp, Hashmap *all_services) {
2021-01-14T16:06:50.2562801Z              ^
```

`../src/test/test-util.c`
```
2021-01-14T16:06:56.3645578Z "../src/test/test-util.c", line 81: warning #1576: static assertion failed with
2021-01-14T16:06:56.3646158Z           "sizeof(val1.b) == sizeof(int) * 100"
2021-01-14T16:06:56.3646616Z           assert_cc(sizeof(val1.b) == sizeof(int) * 100);
2021-01-14T16:06:56.3647517Z           ^

2021-01-14T16:06:56.3648977Z "../src/test/test-util.c", line 86: warning #1576: static assertion failed with
2021-01-14T16:06:56.3649689Z           "__builtin_types_compatible_p(typeof(CONST_MAX(1, 1U)), void)"
2021-01-14T16:06:56.3650528Z           assert_cc(__builtin_types_compatible_p(typeof(CONST_MAX(1, 1U)), void));
2021-01-14T16:06:56.3651201Z           ^

2021-01-14T16:06:56.3652025Z "../src/test/test-util.c", line 64: warning #1563: function "test_max" not
2021-01-14T16:06:56.3652721Z           emitted, consider modeling it or review parse diagnostics to improve
2021-01-14T16:06:56.3653421Z           fidelity
2021-01-14T16:06:56.3653960Z   static void test_max(void) {
```

### Errors
```
2021-01-14T16:06:32.9387408Z "../src/systemd/sd-journal.h", line 75: error #67: expected a "}"
2021-01-14T16:06:32.9388069Z           SD_JOURNAL_SYSTEM_ONLY _sd_deprecated_ = SD_JOURNAL_SYSTEM /* old name */
2021-01-14T16:06:32.9388565Z 
```

Ignore the "function xxx not emitted" warnings - these will go away once the warnings before it get sorted out, they're here just for the sake of completeness. I don't even know if we want to "fix" these - they're definitely false positives. Also, "recoverable error" means a compilation error which Coverity solves by dropping the offending function and attempting to compile & analyze the source without it.

From what I've found out[[0]](https://github.com/bus1/dbus-broker/issues/237), [[1]](https://patchew.org/QEMU/20200629162804.1096180-1-eblake@redhat.com/)), the warnings related to `CONST_MAX()`, `CONST_MAX5()`, and `ELEMENTSOF()` macros are caused by Coverity failing to understand the `__builtin_choose_expr()` bultin. I suspect similar thing will be the cause of the other warnings.

Again, I'm not sure if we want to bother with fixing these, I just wanted to share the results of my *curiosity detour* ;-)

**Comment by poettering** [comment] 2021-02-15 17:01
the `variable "…" may not be initialized` thing is probably because Coverity doesn't know gcc's extensin of allowing array/structure init by `= {}` (ansi c would require at least one field to be specified)

**Comment by poettering** [comment] 2021-02-15 17:04
the test-util ones are all caused by the misunderstanding of the __builtin_… stuff

**Comment by poettering** [comment] 2021-02-15 17:07
and i guess the sd-journal thing is because it doesn't know gcc attributes on enums...

I guess, these are all just cases where coverity is not up to speed with what gcc understands.

the _sd_deprecated_ thing might be easy to circumvent: ifdef the macro to nothing if coverity is detected.

The other ones are harder to remove without ugly patches.

**Comment by mrc0mmand** [comment] 2021-02-15 18:45
Thanks for going through them! Anyway, feel free to close this, since I was just curious if the *hidden* warnings aren't something worth fixing, and apparently they are not :-)

**Comment by poettering** [comment] 2021-02-15 20:11
ok, let's close this then

**Comment by poettering** [comment] 2021-02-15 20:11
(and let's hope coverity cacthes up eventually)

**Closed as completed by poettering** 2021-02-15 20:11 UTC
Labels: coverity
