### ISSUE TITLE
Support for power management inhibiting in pam_systemd

### ISSUE THREAD

**Issue by hdante** [systemd/systemd#30926] opened 2024-01-13 21:06 UTC
### Component

pam_systemd

### Is your feature request related to a problem? Please describe

Hello, is it possible to add inhibit support in pam_systemd ? I need to inhibit suspend to my laptop when I login remotely with ssh.

### Describe the solution you'd like

`optional pam_systemd.so inhibit=sleep inhibit-reason="Interactive remote login"`

Inhibits suspend for the duration of the PAM session.

### Describe alternatives you've considered

- sshd's `ForceCommand`: That's OpenSSH specific, not compatible with any interactive remote session
- systemd's `BindTo`: Auxiliary user service calling systemd-inhibit sleep infinity. That's somewhat fragile and a hack, not really bound to the session.
- sh `.profile`, `.bashrc`: user specific, not generic enough.
- prepend systemd-inhibit in the ssh/PAM shell execution: couldn't find a way to do this.
- Actually track interaction from the remote session: no idea how to do this, sshd might need to support it.

### The systemd version you checked that didn't have the feature you are asking for

255.2-1 Arch Linux

**Comment by poettering** [comment] 2024-04-19 15:51
Duplicate of #20654

**Closed as completed by poettering** 2024-04-19 15:51 UTC
Labels: RFE 🎁, login
