### ISSUE TITLE
Please install dbus interface introspection xml files [RFE]

### ISSUE THREAD

**Issue by garyvdm** [systemd/systemd#21396] opened 2021-11-16 14:28 UTC
It would be nice of the dbus introspection xml files for all systemd dbus services are installed to `/usr/share/dbus-1/interfaces`. I know one can pull it from the dbus server, but I find it more convenient to load it from the disk.

Thanks

**Comment by mrc0mmand** [comment] 2021-11-16 14:48
This seems to be a duplicate of https://github.com/systemd/systemd/issues/20238.

**Closed as completed by mrc0mmand** 2021-11-16 14:48 UTC
Labels: duplicate

**Comment by garyvdm** [comment] 2021-11-16 17:36
Apologies for the duplicate
