### ISSUE TITLE
mymachines fails to resolve usernames 

### ISSUE THREAD

**Issue by yviyvi** [systemd/systemd#9286] opened 2018-06-13 10:55 UTC
Calling `buscl monitor` when running 

`getent --service=mymachines passwd vu-nextcloud-0`

gives a good result:

```
Monitoring bus message stream.
‣ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=1
  Sender=:1.788  Destination=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=Hello
  UniqueName=:1.788
  MESSAGE "" {
  };

‣ Type=method_return  Endian=l  Flags=1  Version=1  Priority=0 Cookie=1  ReplyCookie=1
  Sender=org.freedesktop.DBus  Destination=:1.788
  MESSAGE "s" {
          STRING ":1.788";
  };

‣ Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=5
  Sender=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameOwnerChanged
  MESSAGE "sss" {
          STRING ":1.788";
          STRING "";
          STRING ":1.788";
  };

‣ Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=2
  Sender=org.freedesktop.DBus  Destination=:1.788  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameAcquired
  MESSAGE "s" {
          STRING ":1.788";
  };

‣ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=2
  Sender=:1.788  Destination=org.freedesktop.machine1  Path=/org/freedesktop/machine1  Interface=org.freedesktop.machine1.Manager  Member=MapFromMachineUser
  UniqueName=:1.788
  MESSAGE "su" {
          STRING "nextcloud";
          UINT32 0;
  };

‣ Type=method_return  Endian=l  Flags=1  Version=1  Priority=0 Cookie=868  ReplyCookie=2
  Sender=:1.23  Destination=:1.788
  UniqueName=:1.23
  MESSAGE "u" {
          UINT32 22740992;
  };

‣ Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=6
  Sender=org.freedesktop.DBus  Destination=:1.788  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameLost
  MESSAGE "s" {
          STRING ":1.788";
  };

‣ Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=7
  Sender=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameOwnerChanged
  MESSAGE "sss" {
          STRING ":1.788";
          STRING ":1.788";
          STRING "";
  };


```

The problem is that getent works, but "real" utilities like id/ps/htop etc. fail to resolve usernames of nspawn containers registered with machined.

Here is id:

```
# id -u vu-nextcloud-0                                                                                                                                                                      
id: ‘vu-nextcloud-0’: no such user
```
With busctl I get:

```
Monitoring bus message stream.
‣ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=1
  Sender=:1.794  Destination=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=Hello
  UniqueName=:1.794
  MESSAGE "" {
  };

‣ Type=method_return  Endian=l  Flags=1  Version=1  Priority=0 Cookie=1  ReplyCookie=1
  Sender=org.freedesktop.DBus  Destination=:1.794
  MESSAGE "s" {
          STRING ":1.794";
  };

‣ Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=5
  Sender=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameOwnerChanged
  MESSAGE "sss" {
          STRING ":1.794";
          STRING "";
          STRING ":1.794";
  };

‣ Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=2
  Sender=org.freedesktop.DBus  Destination=:1.794  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameAcquired
  MESSAGE "s" {
          STRING ":1.794";
  };

‣ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=2
  Sender=:1.794  Destination=org.freedesktop.machine1  Path=/org/freedesktop/machine1  Interface=org.freedesktop.machine1.Manager  Member=MapFromMachineUser
  UniqueName=:1.794
  MESSAGE "su" {
          STRING "nextcloud";
          UINT32 0;
  };

‣ Type=method_return  Endian=l  Flags=1  Version=1  Priority=0 Cookie=872  ReplyCookie=2
  Sender=:1.23  Destination=:1.794
  UniqueName=:1.23
  MESSAGE "u" {
          UINT32 22740992;
  };

‣ Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=6
  Sender=org.freedesktop.DBus  Destination=:1.794  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameLost
  MESSAGE "s" {
          STRING ":1.794";
  };

‣ Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=7
  Sender=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameOwnerChanged
  MESSAGE "sss" {
          STRING ":1.794";
          STRING ":1.794";
          STRING "";
  };

‣ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=1
  Sender=:1.795  Destination=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=Hello
  UniqueName=:1.795
  MESSAGE "" {
  };

‣ Type=method_return  Endian=l  Flags=1  Version=1  Priority=0 Cookie=1  ReplyCookie=1
  Sender=org.freedesktop.DBus  Destination=:1.795
  MESSAGE "s" {
          STRING ":1.795";
  };

‣ Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=8
  Sender=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameOwnerChanged
  MESSAGE "sss" {
          STRING ":1.795";
          STRING "";
          STRING ":1.795";
  };

‣ Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=2
  Sender=org.freedesktop.DBus  Destination=:1.795  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameAcquired
  MESSAGE "s" {
          STRING ":1.795";
  };

‣ Type=method_call  Endian=l  Flags=0  Version=1  Priority=0 Cookie=2
  Sender=:1.795  Destination=org.freedesktop.machine1  Path=/org/freedesktop/machine1  Interface=org.freedesktop.machine1.Manager  Member=MapToMachineUser
  UniqueName=:1.795
  MESSAGE "u" {
          UINT32 22740992;
  };

‣ Type=method_return  Endian=l  Flags=1  Version=1  Priority=0 Cookie=873  ReplyCookie=2
  Sender=:1.23  Destination=:1.795
  UniqueName=:1.23
  MESSAGE "sou" {
          STRING "castle";
          OBJECT_PATH "/org/freedesktop/machine1/machine/castle";
          UINT32 22740992;
  };

‣ Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=9
  Sender=org.freedesktop.DBus  Destination=:1.795  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameLost
  MESSAGE "s" {
          STRING ":1.795";
  };

‣ Type=signal  Endian=l  Flags=1  Version=1  Priority=0 Cookie=10
  Sender=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameOwnerChanged
  MESSAGE "sss" {
          STRING ":1.795";
          STRING ":1.795";
          STRING "";
  };

^C
```

Of note here is probably the following

> 
> ‣ Type=method_return  Endian=l  Flags=1  Version=1  Priority=0 Cookie=873  ReplyCookie=2
>   Sender=:1.23  Destination=:1.795
>   UniqueName=:1.23
>   MESSAGE "sou" {
>           **STRING "castle";
>           OBJECT_PATH "/org/freedesktop/machine1/machine/castle";
>           UINT32 22740992;**
>   };

castle is a different nspawn container. I'm assuming this is the problem.

**Comment by yuwata** [comment] 2018-06-13 14:33
Please provide the version of systemd. I cannot reproduce this.
I guess this is already fixed by a79366e22a43ed81017e2d8c2426431d369f3cfa which is included in v225.

**Comment by yviyvi** [comment] 2018-06-13 14:35
arch linux ships 238.133-4 which is what i'm using.

**Comment by yuwata** [comment] 2018-06-13 14:39
Hmm... So, my guess was wrong.

**Comment by yuwata** [comment] 2018-06-13 14:47
The `--private-users=` option of systemd-nspawn for the container 'castle' is disabled?

**Comment by yviyvi** [comment] 2018-06-13 14:49
yes castle has no userns but nextcloud does.

**Comment by yuwata** [comment] 2018-06-13 15:07
If possible, could you try #9288?

**Comment by yviyvi** [comment] 2018-06-13 15:23
ok. seems to work

# id -u vu-nextcloud-0                                                                                                                                                                                        
22740992

**Closed as completed** 2018-06-13 17:05 UTC
Labels: machine
