### ISSUE TITLE
Allow the admin to enable the equivalent of setterm --blank aDelay --powerdown SomeOtherDelay for a VT login prompt

### ISSUE THREAD

**Issue by ZjYwMj** [systemd/systemd#27467] opened 2023-04-30 17:33 UTC
### Component

systemd-logind

### Problem description

A fixed display, that is a fixed text constantly displayed on the screen, is said to eventually harm the monitor. It also draws a small amount of wasted energy, and also a bit distracting. All this happen when a VT has a login prompt, and no one logs in. Circumstances when that can happen is a remotely supervised server with a console in the servers room that is used only for emergencies. A desktop that mainly act as the single printer gateway for a small office. Or for a user that gone away after the desktop was turned on (but before he logged in), because he had some urgent call to attend to. This usually does not happen when there is a graphical login prompt, such as by a display manager, because the graphical environment has a display power management signalling set up.

### Suggested solution

Allow the admin to enable the equivalent of 
    ```setterm --blank a_delay --powerdown some_other_delay```
for a VT login prompt.

### Describe alternatives you've considered

On freebsd, it is integrated with [vidcontrol](https://man.freebsd.org/cgi/man.cgi?vidcontrol(1)). vidcontrol is comparable to [systemd-vconsole-setup.service](https://github.com/systemd/systemd/blob/main/units/systemd-vconsole-setup.service.in).

### The systemd version you checked that didn't have the feature you are asking for

253, and before

**Comment by poettering** [comment] 2023-05-02 09:09
Duplicate of #7396

**Closed as completed by poettering** 2023-05-02 09:09 UTC
Labels: RFE 🎁, login, duplicate
