### ISSUE TITLE
Setting MTUBytes on bridge adapter does not apply value to included NICs which causes failed pings

### ISSUE THREAD

**Issue by cbc02009** [systemd/systemd#24311] opened 2022-08-15 08:44 UTC
### systemd version the issue has been seen with

251

### Used distribution

Arch Linux

### Linux kernel version used

5.19.1-arch2-1

### CPU architectures issue was seen on

x86_64

### Component

Systemd-networkd

### Expected behaviour you didn't see

I expect setting the MTU on a bridge adapter to ensure that all NICs in the bridge use the set MTU value in order for the bridge to function properly.

### Unexpected behaviour you saw

The bridge gets 9000 mtu, but eno1 gets 1500 mtu

### Steps to reproduce the problem

To prove out that MTU works fine on the adapter by itself without a bridge I used the following file:
10-eno1.network
```ini
[Match]
Name=eno1

[Network]
Address=10.0.0.15/16
Gateway=10.0.0.1
IPv6PrivacyExtensions=kernel

[Link]
MTUBytes=9000
```
and was able to ping it from another device using `ping -M do -s 8000 10.0.0.15` successfully

However, using the following setup, the eno1 adapter still uses MTU 1500 and the ping fails:

20-bind.network
```ini
[Match]
Name=eno1

[Network]
Bridge=br0
```

30-br0.netdev
```ini
[NetDev]
Name=br0
Kind=bridge
MACAddress=**:**:**:**
```

40-br0.network
```ini
[Match]
Name=br0

[Network]
Address=10.0.0.15/16
Gateway=10.0.0.1
DNS=10.0.0.17
IPv6PrivacyExtensions=kernel

[Link]
MTUBytes=9000
```

Running `ip a` with the above setup shows: 
```
br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP group default qlen 1000
...
eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br0 state UP group default qlen 1000
```

Manually setting the MTU on eno1 with `sudo ip link set mtu 9000 eno1` causes the ping from the other system to succeed.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
See the above section.
```

**Comment by yuwata** [comment] 2022-08-16 16:56
Why not to also set MTUBytes=9000 in 20-bind.network?

**Comment by yuwata** [comment] 2022-08-16 17:05
I tested MTUBytes= setting both on bridge master and ports, it seems to work fine for me. See #24331.

**Comment by cbc02009** [comment] 2022-08-16 17:16
@yuwata that appears to work, thank you! I swear I read the manual 10 times over and didn't see anything about that. Maybe it can be added to the documentation somewhere? Or maybe it's just obvious to everyone but me.

**Comment by yuwata** [comment] 2022-08-16 17:29
Any suggestions about improving documentation is always welcome. Please open a PR. Thank you.

So, closing this page, as it is not a bug.

**Closed as completed by yuwata** 2022-08-16 17:29 UTC
Labels: network, not-a-bug
