### ISSUE TITLE
Possible journald deadlock

### ISSUE THREAD

**Issue by wjmelements** [systemd/systemd#16244] opened 2020-06-23 00:33 UTC
**245.6-7**

**Arch Linux**

**Symptom**
The deadlock happens about weekly, and seems to have started after a slight increase in logging (perhaps the straw that broke the donkey's back). As far as we can tell all user and system services stop (including ones we did not develop like sshd) though the power is still on. Additionally all logging stops at that time.

**Setup**
We have heavy logging from both user and system services. The relevant `systemctl --user` process runs with UID 992. We log about 1 million lines every four hours from the user process and about 1 million lines each day from the loudest system process. The average line is 80 bytes in length.

Our journalctl.conf:
```
[Journal]
#Storage=auto
#Compress=yes
#Seal=yes
#SplitMode=uid
#SyncIntervalSec=5m
#RateLimitIntervalSec=30s
RateLimitBurst=20000
SystemMaxUse=40G
#SystemKeepFree=
#SystemMaxFileSize=
SystemMaxFiles=200
#RuntimeMaxUse=
#RuntimeKeepFree=
#RuntimeMaxFileSize=
#RuntimeMaxFiles=100
#MaxRetentionSec=
#MaxFileSec=1month
#ForwardToSyslog=no
#ForwardToKMsg=no
#ForwardToConsole=no
#ForwardToWall=yes
#TTYPath=/dev/console
#MaxLevelStore=debug
#MaxLevelSyslog=debug
#MaxLevelKMsg=notice
#MaxLevelConsole=info
#MaxLevelWall=emerg
#LineMax=48K
#ReadKMsg=yes
```

**Hypothesis**
Our hypothesis is that the deadlock happens because of some rare maintenance being triggered by both the user and root systemd processes at the same time. We believe it is from systemd because it stops all other processes (e.g. sshd) and logging system-wide. We believe it is from journald because we log >40GB each day from those separate processes.

**Comment by poettering** [comment] 2020-06-23 07:55
This is way too vague to be useful. Do you have a reproducer? What does strace on journald say? What is a "deadlock" supposed to be? journald hanging? Everything hanging?

**Comment by vcaputo** [comment] 2020-06-23 08:16
It sounds like the host is inaccessible when this occurs, since he mentioned sshd as one of the things appearing stopped.

@wjmelements You may need to keep an interactive ssh login active ahead of time for use when the problem occurs, if something like broken logging is preventing new logins.

journald has a watchdog feature that will restart it should something like a deadlock occur though, it seems unlikely to be the cause.  It wouldn't hurt to verify the watchdog hasn't been disabled in the unit file.

Since we don't have a bunch of similar reports piling up shouting about journald deadlocking my guess is it's somewhere else, maybe a kernel issue.

**Comment by wjmelements** [comment] 2020-06-23 12:32
> You may need to keep an interactive ssh login active ahead of time for use when the problem occurs, if something like broken logging is preventing new logins.

My active ssh quit when it happened the third time.

> It wouldn't hurt to verify the watchdog hasn't been disabled in the unit file.

It doesn't seem to be. I haven't made any modifications. I see:
> WatchdogSec=3min
The state was once stuck for more than 20 minutes, until we restarted. Is there a watchdog for systemd in general?

> What does strace on journald say?
Briefly attempted to set this up. It's more complicated than putting /usr/bin/strace in the ExecStart.

> Since we don't have a bunch of similar reports piling up shouting about journald deadlocking my guess is it's somewhere else, maybe a kernel issue.

It could be. What might be fairly unique in my case is that the `--user` is in the system range (992<1000).

**Comment by poettering** [comment] 2020-06-23 15:00
please answer my earlier questions

**Comment by wjmelements** [comment] 2020-07-06 21:39
I still get the system-wide deadlock about once a week; it has now happened four times. I seek advice on how to run journald as a service with strace.

**Comment by poettering** [comment] 2020-08-06 21:40
`systemctl edit systemd-journald` 

Then override the ExecStart= line:

```
[Service]
ExecStart=
ExecStart=/usr/bin/strace -D -s 500 -yy -o /tmp/journal.log /usr/lib/systemd/systemd-journald
```

Then restart journald. Reproduce the issue, you will find the strace in /tmp/journal.log

Still wondering what a "system-wide deadlock" is supposed to be, would be great if you could answer that? It's the most vague symptom one can come up with, and what makes you think this has anything to do with journald?

**Comment by wjmelements** [comment] 2020-08-07 20:19
> `systemctl edit systemd-journald`
> 
> Then override the ExecStart= line:
> 
> ```
> [Service]
> ExecStart=
> ExecStart=/usr/bin/strace -D -s 500 -yy -o /tmp/journal.log /usr/lib/systemd/systemd-journald
> ```
> 
> Then restart journald. Reproduce the issue, you will find the strace in /tmp/journal.log

Thanks, I was missing some flags. `/tmp/journal.log` is empty so far; is that expected?

> Still wondering what a "system-wide deadlock" is supposed to be, would be great if you could answer that? It's the most vague symptom one can come up with

The machine is still on but the entire system is non-responsive: no ssh, no tty. All logs end system-wide around the same time.

>  what makes you think this has anything to do with journald?

As @vcaputo guessed it could also be a kernel issue, but those are so rare I suspect it is in user-space. Losing sshd suggests it could be systemd, and the main correlating factor before this started happening was vastly increased logging.

I still maintain that it could be because our `--user` service is running with a system UID (<1000), as systemd has several assumptions about user service UIDs being greater than or equal to 1000.

**Comment by poettering** [comment] 2020-08-07 21:52
> Thanks, I was missing some flags. `/tmp/journal.log` is empty so far; is that expected?

No, it should show at least some syscalls, needed during journald startup. Do you see the strace in the ps tree?

> The machine is still on but the entire system is non-responsive: no ssh, no tty. All logs end system-wide around the same time.

Userspace shouldn't be able to freeze a system. If userspace can do this it's typically the kernel's fault. (Except maybe if you totally overload the schedulers and memory management at the same time, Linux hasn't been very good at handling that).

> As @vcaputo guessed it could also be a kernel issue, but those are so rare I suspect it is in user-space. Losing sshd suggests it could be systemd, and the main correlating factor before this started happening was vastly increased logging.

How do you invoke sshd? In the socket activation logic or as standalone daemon?

> I still maintain that it could be because our `--user` service is running with a system UID (<1000), as systemd has several assumptions about user service UIDs being greater than or equal to 1000.

Well, this is a wild guess on top of a wild guess. I see no indication that this has anything to do with the journal and even less that it has anything to do with UID choices.

**Comment by poettering** [comment] 2021-02-12 19:40
Let's close this here. I doubt this is related to journald, and the requested strace was never provided, nor the questions answered.

**Closed as completed by poettering** 2021-02-12 19:40 UTC
Labels: needs-reporter-feedback ❓
