### ISSUE TITLE
Bootctl boot menu resolution and centering

### ISSUE THREAD

**Issue by kittydoor** [systemd/systemd#7230] opened 2017-10-31 00:18 UTC
### Submission type

- Request for enhancement (RFE)

### systemd version the issue has been seen with

> 235

### Used distribution

> Arch Linux

bootctl, or in other words systemd-boot, does not seem to support any kind of way to explicitly set resolution. It's behavior changes from machine to machine, but often the detected resolution and placement leads to a smaller than intended and off center (closer to the left side) menu. A config option for the loader would be very beneficial in fixing this manually.

**Comment by poettering** [comment] 2017-11-21 16:12
Duplicate of #2750.

**Closed as completed by poettering** 2017-11-21 16:12 UTC
Labels: RFE 🎁, sd-boot/sd-stub/bootctl, duplicate
