### ISSUE TITLE
Machinectl start fails with nested Fedora images - machine id clash

### ISSUE THREAD

**Issue by NeilW** [systemd/systemd#2090] opened 2015-12-03 17:25 UTC
I'm running an official Fedora 23 cloud image (from https://download.fedoraproject.org/pub/fedora/linux/releases/23/Cloud/x86_64/Images/Fedora-Cloud-Base-23-20151030.x86_64.raw.xz) on KVM with the `systemd-nspawn@.service` file suitably patched so that 'machinectl start' won't fail with /dev/loop-control permission issues. 

However if I try to run the same Fedora Image as a container with

```
$ sudo machinectl --verify=no pull-raw https://download.fedoraproject.org/pub/fedora/linux/releases/23/Cloud/x86_64/Images/Fedora-Cloud-Base-23-20151030.x86_64.raw.xz fedora23
$ sudo machinectl start fedora23
```

Then the resulting unit file still fails because of a machine id clash.

```
systemctl status -l systemd-nspawn@fedora23.service 
● systemd-nspawn@fedora23.service - Container fedora23
   Loaded: loaded (/usr/lib/systemd/system/systemd-nspawn@.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2015-12-03 15:58:23 UTC; 1h 20min ago
     Docs: man:systemd-nspawn(1)
  Process: 1255 ExecStart=/usr/bin/systemd-nspawn --quiet --keep-unit --boot --link-journal=try-guest --network-veth --machine=%I (code=exited, status=1/FAILURE)
 Main PID: 1255 (code=exited, status=1/FAILURE)
   Status: "Terminating..."

Dec 03 15:58:23 srv-x84n8.gb1s.brightbox.com systemd[1]: Starting Container fedora23...
Dec 03 15:58:23 srv-x84n8.gb1s.brightbox.com systemd-nspawn[1255]: Host and machine ids are equal (c849431f196c4907b7eb56fdff80edff): refusing to link journals
Dec 03 15:58:23 srv-x84n8.gb1s.brightbox.com systemd[1]: systemd-nspawn@fedora23.service: Main process exited, code=exited, status=1/FAILURE
Dec 03 15:58:23 srv-x84n8.gb1s.brightbox.com systemd[1]: Failed to start Container fedora23.
Dec 03 15:58:23 srv-x84n8.gb1s.brightbox.com systemd[1]: systemd-nspawn@fedora23.service: Unit entered failed state.
Dec 03 15:58:23 srv-x84n8.gb1s.brightbox.com systemd[1]: systemd-nspawn@fedora23.service: Failed with result 'exit-code'.
```

**Comment by poettering** [comment] 2016-04-18 16:25
well, it's a safety feature there: you are running two systems together there that have the same machine id. The machine id is supposed to identify the machine in the network, but if they are all the same then they ID is uselles. Consider changing the machine ID on one.

When the system boots up without any machine ID provisioned in /etc/machine-id yet it will be generated dynamically and written there. Hence, instead of changing the machine ID explicitly you can also remove it from the container image so that a new one is randomly assigned at boot.

Closing this now, as this is really intended behaviour.

**Closed as completed by poettering** 2016-04-18 16:25 UTC
Labels: nspawn, not-a-bug
