### ISSUE TITLE
systemd-networkd/resolved is not using the dns server pushed via router advertisement

### ISSUE THREAD

**Issue by kmille** [systemd/systemd#20850] opened 2021-09-27 09:37 UTC
Hey,

I'm not sure if I do something wrong. I'm on Arch. My router announces a DNS server in the Router Advertisement packets:

![2021-09-27-112652_screenshot](https://user-images.githubusercontent.com/6470600/134883281-e1eec96e-9de2-47ab-b5d0-3343ea9acf76.png)

But it is not used/not showing up in the `networkctl` output.

```
kmille@linbox:~ networkctl status wlp3s0   
● 3: wlp3s0                                                                    
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: /etc/systemd/network/wlp3s0.network
                          Type: wlan
                         State: routable (configured)
                  Online state: online                                         
                          Path: pci-0000:03:00.0
                        Driver: iwlwifi
                        Vendor: Intel Corporation
                         Model: Wireless 8260 (Dual Band Wireless-AC 8260)
                    HW Address: redacted
                           MTU: 1500 (min: 256, max: 2304)
                         QDisc: noqueue
  IPv6 Address Generation Mode: eui64
             WiFi access point: redacted
          Queue Length (Tx/Rx): 1/1
                       Address: 192.168.10.xx (DHCP4 via 192.168.10.1)
                                      ipv6: redacted
                       Gateway: 192.168.10.1
                                       ipv6: redacted
                           DNS: 192.168.10.1          <---------------- I miss it here
             Activation Policy: up
           Required For Online: yes
               DHCP4 Client ID: IAID:0xf8038963/DUID
             DHCP6 Client DUID: DUID-EN/Vendor:0000ab118aa23f1d4d7ed7580000

```
I don't see errors in the log. This is my config:

```
kmille@linbox:network cat wlp3s0.network 
[Match]
Name=wlp3s0

[Network]
DHCP=yes
IPv6PrivacyExtensions=yes
IPv6AcceptRA=1

[DHCP]
RouteMetric=20
#UseMTU=true

#[IPv6AcceptRA]
#UseDNS=true
```

**systemd version the issue has been seen with**
```
kmille@linbox:~ systemctl --version                            
systemd 249 (249.4-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

**Linux kernel version used** (`uname -a`)
`Linux box 5.14.7-arch1-1 #1 SMP PREEMPT Wed, 22 Sep 2021 21:35:11 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
x86

**Comment by yuwata** [comment] 2021-09-27 09:48
Hmm, the lifetime of the DNS server is zero. Please check settings of the router.

**Comment by kmille** [comment] 2021-09-27 10:33
You are right. That fixed the problem.
The router also uses `systemd-networkd`. I think the docs could be updated because it was not clear to me, that `DNSLifetimeSec` needs to be set.

This configuration adds a DNS server to the RA, but the lifetime is 0. So it will not be used.
```ini
[IPv6SendRA]
DNS=_link_local
```

This works as expected.
```ini
[IPv6SendRA]
DNS=_link_local
DNSLifetimeSec=86400
```

Thanks for your fast support!

**Comment by yuwata** [comment] 2021-09-27 13:24
Fix is waiting in #20853.

**Comment by kmille** [comment] 2021-09-27 14:51
nice. Can you tell me when it will reach Debian bullseye?

**Comment by yuwata** [comment] 2021-09-27 16:24
@kmille I am not a debian's systemd maintainer, so not sure, but this is not a bug, so I guess the patch will not be backported. Anyway, please contact to your downstream, that is, open an issue page on the debian bug/issue tracker to request backporting the patch.

(BTW, please do not close the issue page until the fix is merged.)

**Closed as completed** 2021-10-12 08:49 UTC
Labels: network, documentation, ndisc/ra
