### ISSUE TITLE
test-execute fails under lxc

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#9700] opened 2018-07-23 15:07 UTC
**systemd version the issue has been seen with**

v239

**Used distribution**
 
Debian sid

AppArmor confinement is enabled for the LXC container, lxc is version 2.0.9

Running test-execute under lxc via autopkgtest, I get:
```
root@autopkgtest-lxc-drpooy:/tmp/autopkgtest-lxc.dbckoweu/downtmp/build.439/src# /usr/lib/systemd/tests/test-execute
Found cgroup on /sys/fs/cgroup/systemd, legacy hierarchy
Found cgroup on /sys/fs/cgroup/systemd, legacy hierarchy
Using cgroup controller name=systemd. File system hierarchy is at /sys/fs/cgroup/systemd/e33f2c8956e4d33c.
Controller 'cpu' supported: yes
Controller 'cpuacct' supported: yes
Controller 'io' supported: no
Controller 'blkio' supported: yes
Controller 'memory' supported: yes
Controller 'devices' supported: yes
Controller 'pids' supported: yes
Looking for unit files in (higher priority first):
	/usr/lib/systemd/tests/testdata/test-execute
Unit type .device is not supported on this system.
Unit type .automount is not supported on this system.
Found container virtualization lxc.
Unit type .swap is not supported on this system.
Unit type .device is not supported on this system.
Unit type .automount is not supported on this system.
Unit type .swap is not supported on this system.
root.mount: Failed to load configuration: No such file or directory
dev.mount: Failed to load configuration: No such file or directory
proc.mount: Failed to load configuration: No such file or directory
tmp.mount: Failed to load configuration: No such file or directory
sys.mount: Failed to load configuration: No such file or directory
sys-fs.mount: Failed to load configuration: No such file or directory
sys-fs-fuse.mount: Failed to load configuration: No such file or directory
sys-devices.mount: Failed to load configuration: No such file or directory
sys-devices-virtual.mount: Failed to load configuration: No such file or directory
proc-sys.mount: Failed to load configuration: No such file or directory
Successfully created private D-Bus server.
Bus bus-system: changing state UNSET → OPENING
Bus bus-system: changing state OPENING → AUTHENTICATING
Successfully connected to system bus.
Invoking unit coldplug() handlers…
dev-hugepages.mount: Changed dead -> mounted
proc-uptime.mount: Changed dead -> mounted
dev-mqueue.mount: Changed dead -> mounted
dev-tty2.mount: Changed dead -> mounted
proc-sysrq\x2dtrigger.mount: Changed dead -> mounted
-.mount: Changed dead -> mounted
dev-tty1.mount: Changed dead -> mounted
init.scope changed dead -> running
proc-meminfo.mount: Changed dead -> mounted
proc-cpuinfo.mount: Changed dead -> mounted
dev-tty4.mount: Changed dead -> mounted
proc-sys-net.mount: Changed dead -> mounted
dev-tty3.mount: Changed dead -> mounted
proc-stat.mount: Changed dead -> mounted
sys-fs-fuse-connections.mount: Changed dead -> mounted
dev-ptmx.mount: Changed dead -> mounted
tmp-autopkgtest\x2dlxc.dbckoweu.mount: Changed dead -> mounted
-.slice changed dead -> active
sys-devices-virtual-net.mount: Changed dead -> mounted
proc-swaps.mount: Changed dead -> mounted
proc-diskstats.mount: Changed dead -> mounted
Invoking unit catchup() handlers…
shutdown.target: Failed to load configuration: No such file or directory
basic.target: Failed to load configuration: No such file or directory
Not running with unified cgroups, BPF firewalling is not supported.
BPF firewalling not supported on this manager, proceeding without.
BPF firewalling not supported on this manager, proceeding without.
exec-basic.service: Passing 0 fds to service
exec-basic.service: About to execute: /usr/bin/touch /tmp/a
exec-basic.service: Forked /usr/bin/touch as 1747
exec-basic.service: Changed dead -> start
exec-basic.service
	UMask: 0022
	WorkingDirectory: /root
	RootDirectory: /
	NonBlocking: no
	PrivateTmp: yes
	PrivateDevices: no
	ProtectKernelTunables: no
	ProtectKernelModules: no
	ProtectControlGroups: no
	PrivateNetwork: no
	PrivateUsers: no
	ProtectHome: no
	ProtectSystem: no
	MountAPIVFS: no
	IgnoreSIGPIPE: yes
	MemoryDenyWriteExecute: no
	RestrictRealtime: no
	KeyringMode: inherit
	RuntimeDirectoryPreserve: no
	RuntimeDirectoryMode: 0755
	StateDirectoryMode: 0755
	CacheDirectoryMode: 0755
	LogsDirectoryMode: 0755
	ConfigurationDirectoryMode: 0755
	StandardInput: null
	StandardOutput: inherit
	StandardError: inherit
	DynamicUser: no
	LockPersonality: no
Bus bus-system: changing state AUTHENTICATING → HELLO
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a
exec-basic.service: Failed to set up namespace, assuming containerized execution, ignoring: Permission denied
Got message type=method_return sender=org.freedesktop.DBus destination=:1.27 path=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 signature=s error-name=n/a error-message=n/a
Bus bus-system: changing state HELLO → RUNNING
exec-basic.service: Executing: /usr/bin/touch /tmp/aGot message type=signal sender=org.freedesktop.DBus destination=:1.27 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired cookie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a

Got message type=method_return sender=org.freedesktop.DBus destination=:1.27 path=n/a interface=n/a member=n/a cookie=3 reply_cookie=2 signature=n/a error-name=n/a error-message=n/a
Match type='signal',path='/org/freedesktop/systemd1/agent',interface='org.freedesktop.systemd1.Agent',member='Released' successfully installed.
Received SIGCHLD from PID 1747 (touch).
Child 1747 (touch) died (code=exited, status=0/SUCCESS)
exec-basic.service: Child 1747 belongs to exec-basic.service.
exec-basic.service: Main process exited, code=exited, status=0/SUCCESS
exec-basic.service: Running next main command for state start.
exec-basic.service: Passing 0 fds to service
exec-basic.service: About to execute: /bin/touch /tmp/b
exec-basic.service: Forked /bin/touch as 1748
exec-basic.service: Failed to set up namespace, assuming containerized execution, ignoring: Permission denied
exec-basic.service: Executing: /bin/touch /tmp/b
Received SIGCHLD from PID 1748 (touch).
Child 1748 (touch) died (code=exited, status=0/SUCCESS)
exec-basic.service: Child 1748 belongs to exec-basic.service.
exec-basic.service: Main process exited, code=exited, status=0/SUCCESS
exec-basic.service: Running next main command for state start.
exec-basic.service: Passing 0 fds to service
exec-basic.service: About to execute: /usr/bin/touch /tmp/c
exec-basic.service: Forked /usr/bin/touch as 1749
exec-basic.service: Failed to set up namespace, assuming containerized execution, ignoring: Permission denied
exec-basic.service: Executing: /usr/bin/touch /tmp/c
Received SIGCHLD from PID 1749 (touch).
Child 1749 (touch) died (code=exited, status=0/SUCCESS)
exec-basic.service: Child 1749 belongs to exec-basic.service.
exec-basic.service: Main process exited, code=exited, status=0/SUCCESS
exec-basic.service: Running next main command for state start.
exec-basic.service: Passing 0 fds to service
exec-basic.service: About to execute: /usr/bin/test -f /tmp/a
exec-basic.service: Forked /usr/bin/test as 1750
exec-basic.service: Failed to set up namespace, assuming containerized execution, ignoring: Permission denied
exec-basic.service: Executing: /usr/bin/test -f /tmp/a
Received SIGCHLD from PID 1750 (test).
Child 1750 (test) died (code=exited, status=0/SUCCESS)
exec-basic.service: Child 1750 belongs to exec-basic.service.
exec-basic.service: Main process exited, code=exited, status=0/SUCCESS
exec-basic.service: Running next main command for state start.
exec-basic.service: Passing 0 fds to service
exec-basic.service: About to execute: /usr/bin/test -f /tmp/b
exec-basic.service: Forked /usr/bin/test as 1751
exec-basic.service: Failed to set up namespace, assuming containerized execution, ignoring: Permission denied
exec-basic.service: Executing: /usr/bin/test -f /tmp/b
Received SIGCHLD from PID 1751 (test).
Child 1751 (test) died (code=exited, status=0/SUCCESS)
exec-basic.service: Child 1751 belongs to exec-basic.service.
exec-basic.service: Main process exited, code=exited, status=0/SUCCESS
exec-basic.service: Running next main command for state start.
exec-basic.service: Passing 0 fds to service
exec-basic.service: About to execute: /usr/bin/test -f /tmp/c
exec-basic.service: Forked /usr/bin/test as 1752
exec-basic.service: Failed to set up namespace, assuming containerized execution, ignoring: Permission denied
exec-basic.service: Executing: /usr/bin/test -f /tmp/c
Received SIGCHLD from PID 1752 (test).
Child 1752 (test) died (code=exited, status=0/SUCCESS)
exec-basic.service: Child 1752 belongs to exec-basic.service.
exec-basic.service: Main process exited, code=exited, status=0/SUCCESS
exec-basic.service: Running next main command for state start.
exec-basic.service: Passing 0 fds to service
exec-basic.service: About to execute: /usr/bin/test -f /tmp/c
exec-basic.service: Forked /usr/bin/test as 1753
exec-basic.service: Failed to set up namespace, assuming containerized execution, ignoring: Permission denied
exec-basic.service: Executing: /usr/bin/test -f /tmp/c
Received SIGCHLD from PID 1753 (test).
Child 1753 (test) died (code=exited, status=0/SUCCESS)
exec-basic.service: Child 1753 belongs to exec-basic.service.
exec-basic.service: Main process exited, code=exited, status=0/SUCCESS
exec-basic.service: About to execute: /usr/bin/rm /tmp/a /tmp/b /tmp/c
exec-basic.service: Forked /usr/bin/rm as 1754
exec-basic.service: Changed start -> start-post
exec-basic.service: Failed to set up namespace, assuming containerized execution, ignoring: Permission denied
exec-basic.service: Executing: /usr/bin/rm /tmp/a /tmp/b /tmp/c
Received SIGCHLD from PID 1754 (rm).
Child 1754 (rm) died (code=exited, status=0/SUCCESS)
exec-basic.service: Child 1754 belongs to exec-basic.service.
exec-basic.service: Control process exited, code=exited status=0
exec-basic.service: Got final SIGCHLD for state start-post.
exec-basic.service: Changed start-post -> dead
Spawning thread to nuke /tmp/systemd-private-b6066afb81864af6824257068880184c-exec-basic.service-dnnXjH
Spawning thread to nuke /var/tmp/systemd-private-b6066afb81864af6824257068880184c-exec-basic.service-vG1Anr
	PID: 1753
	Start Timestamp: Mon 2018-07-23 15:03:43 UTC
	Exit Timestamp: Mon 2018-07-23 15:03:43 UTC
	Exit Code: exited
	Exit Status: 0
BPF firewalling not supported on this manager, proceeding without.
exec-ambientcapabilities.service: Passing 0 fds to service
exec-ambientcapabilities.service: About to execute: /bin/sh -x -c 'c=$$(grep "CapAmb:" /proc/self/status); test "$$c" = "CapAmb:	0000000000002001"'
exec-ambientcapabilities.service: Forked /bin/sh as 1757
exec-ambientcapabilities.service: Changed dead -> start
exec-ambientcapabilities.service
	UMask: 0022
	WorkingDirectory: /root
	RootDirectory: /
	NonBlocking: no
	PrivateTmp: no
	PrivateDevices: no
	ProtectKernelTunables: no
	ProtectKernelModules: no
	ProtectControlGroups: no
	PrivateNetwork: no
	PrivateUsers: no
	ProtectHome: no
	ProtectSystem: no
	MountAPIVFS: no
	IgnoreSIGPIPE: yes
	MemoryDenyWriteExecute: no
	RestrictRealtime: no
	KeyringMode: inherit
	RuntimeDirectoryPreserve: no
	RuntimeDirectoryMode: 0755
	StateDirectoryMode: 0755
	CacheDirectoryMode: 0755
	LogsDirectoryMode: 0755
	ConfigurationDirectoryMode: 0755
	StandardInput: null
	StandardOutput: inherit
	StandardError: inherit
	AmbientCapabilities: cap_chown cap_net_raw
	User: daemon
	DynamicUser: no
	LockPersonality: no
exec-ambientcapabilities.service: User lookup succeeded: uid=1 gid=1
exec-ambientcapabilities.service: Executing: /bin/sh -x -c 'c=$(grep "CapAmb:" /proc/self/status); test "$c" = "CapAmb:	0000000000002001"'
+ grep CapAmb: /proc/self/status
+ c=CapAmb:	0000000000002001
+ test CapAmb:	0000000000002001 = CapAmb:	0000000000002001
Received SIGCHLD from PID 1757 (sh).
Child 1757 (sh) died (code=exited, status=0/SUCCESS)
exec-ambientcapabilities.service: Child 1757 belongs to exec-ambientcapabilities.service.
exec-ambientcapabilities.service: Main process exited, code=exited, status=0/SUCCESS
exec-ambientcapabilities.service: Changed start -> dead
	PID: 1757
	Start Timestamp: Mon 2018-07-23 15:03:43 UTC
	Exit Timestamp: Mon 2018-07-23 15:03:43 UTC
	Exit Code: exited
	Exit Status: 0
BPF firewalling not supported on this manager, proceeding without.
exec-ambientcapabilities-merge.service: Passing 0 fds to service
exec-ambientcapabilities-merge.service: About to execute: /bin/sh -x -c 'c=$$(grep "CapAmb:" /proc/self/status); test "$$c" = "CapAmb:	0000000000002001"'
exec-ambientcapabilities-merge.service: Forked /bin/sh as 1759
exec-ambientcapabilities-merge.service: Changed dead -> start
exec-ambientcapabilities-merge.service
	UMask: 0022
	WorkingDirectory: /root
	RootDirectory: /
	NonBlocking: no
	PrivateTmp: no
	PrivateDevices: no
	ProtectKernelTunables: no
	ProtectKernelModules: no
	ProtectControlGroups: no
	PrivateNetwork: no
	PrivateUsers: no
	ProtectHome: no
	ProtectSystem: no
	MountAPIVFS: no
	IgnoreSIGPIPE: yes
	MemoryDenyWriteExecute: no
	RestrictRealtime: no
	KeyringMode: inherit
	RuntimeDirectoryPreserve: no
	RuntimeDirectoryMode: 0755
	StateDirectoryMode: 0755
	CacheDirectoryMode: 0755
	LogsDirectoryMode: 0755
	ConfigurationDirectoryMode: 0755
	StandardInput: null
	StandardOutput: inherit
	StandardError: inherit
	AmbientCapabilities: cap_chown cap_net_raw
	User: daemon
	DynamicUser: no
	LockPersonality: no
exec-ambientcapabilities-merge.service: User lookup succeeded: uid=1 gid=1
exec-ambientcapabilities-merge.service: Executing: /bin/sh -x -c 'c=$(grep "CapAmb:" /proc/self/status); test "$c" = "CapAmb:	0000000000002001"'
+ grep CapAmb: /proc/self/status
+ c=CapAmb:	0000000000002001
+ test CapAmb:	0000000000002001 = CapAmb:	0000000000002001
Received SIGCHLD from PID 1759 (sh).
Child 1759 (sh) died (code=exited, status=0/SUCCESS)
exec-ambientcapabilities-merge.service: Child 1759 belongs to exec-ambientcapabilities-merge.service.
exec-ambientcapabilities-merge.service: Main process exited, code=exited, status=0/SUCCESS
exec-ambientcapabilities-merge.service: Changed start -> dead
	PID: 1759
	Start Timestamp: Mon 2018-07-23 15:03:43 UTC
	Exit Timestamp: Mon 2018-07-23 15:03:43 UTC
	Exit Code: exited
	Exit Status: 0
BPF firewalling not supported on this manager, proceeding without.
exec-ambientcapabilities-nobody.service: Passing 0 fds to service
exec-ambientcapabilities-nobody.service: About to execute: /bin/sh -x -c 'c=$$(grep "CapAmb:" /proc/self/status); test "$$c" = "CapAmb:	0000000000002001"'
exec-ambientcapabilities-nobody.service: Forked /bin/sh as 1761
exec-ambientcapabilities-nobody.service: Changed dead -> start
exec-ambientcapabilities-nobody.service
	UMask: 0022
	WorkingDirectory: /root
	RootDirectory: /
	NonBlocking: no
	PrivateTmp: no
	PrivateDevices: no
	ProtectKernelTunables: no
	ProtectKernelModules: no
	ProtectControlGroups: no
	PrivateNetwork: no
	PrivateUsers: no
	ProtectHome: no
	ProtectSystem: no
	MountAPIVFS: no
	IgnoreSIGPIPE: yes
	MemoryDenyWriteExecute: no
	RestrictRealtime: no
	KeyringMode: inherit
	RuntimeDirectoryPreserve: no
	RuntimeDirectoryMode: 0755
	StateDirectoryMode: 0755
	CacheDirectoryMode: 0755
	LogsDirectoryMode: 0755
	ConfigurationDirectoryMode: 0755
	StandardInput: null
	StandardOutput: inherit
	StandardError: inherit
	AmbientCapabilities: cap_chown cap_net_raw
	User: nobody
	DynamicUser: no
	LockPersonality: no
exec-ambientcapabilities-nobody.service: User lookup succeeded: uid=65534 gid=65534
exec-ambientcapabilities-nobody.service: Executing: /bin/sh -x -c 'c=$(grep "CapAmb:" /proc/self/status); test "$c" = "CapAmb:	0000000000002001"'
+ grep CapAmb: /proc/self/status
+ c=CapAmb:	0000000000002001
+ test CapAmb:	0000000000002001 = CapAmb:	0000000000002001
Received SIGCHLD from PID 1761 (sh).
Child 1761 (sh) died (code=exited, status=0/SUCCESS)
exec-ambientcapabilities-nobody.service: Child 1761 belongs to exec-ambientcapabilities-nobody.service.
exec-ambientcapabilities-nobody.service: Main process exited, code=exited, status=0/SUCCESS
exec-ambientcapabilities-nobody.service: Changed start -> dead
	PID: 1761
	Start Timestamp: Mon 2018-07-23 15:03:43 UTC
	Exit Timestamp: Mon 2018-07-23 15:03:43 UTC
	Exit Code: exited
	Exit Status: 0
BPF firewalling not supported on this manager, proceeding without.
exec-ambientcapabilities-merge-nobody.service: Passing 0 fds to service
exec-ambientcapabilities-merge-nobody.service: About to execute: /bin/sh -x -c 'c=$$(grep "CapAmb:" /proc/self/status); test "$$c" = "CapAmb:	0000000000002001"'
exec-ambientcapabilities-merge-nobody.service: Forked /bin/sh as 1763
exec-ambientcapabilities-merge-nobody.service: Changed dead -> start
exec-ambientcapabilities-merge-nobody.service
	UMask: 0022
	WorkingDirectory: /root
	RootDirectory: /
	NonBlocking: no
	PrivateTmp: no
	PrivateDevices: no
	ProtectKernelTunables: no
	ProtectKernelModules: no
	ProtectControlGroups: no
	PrivateNetwork: no
	PrivateUsers: no
	ProtectHome: no
	ProtectSystem: no
	MountAPIVFS: no
	IgnoreSIGPIPE: yes
	MemoryDenyWriteExecute: no
	RestrictRealtime: no
	KeyringMode: inherit
	RuntimeDirectoryPreserve: no
	RuntimeDirectoryMode: 0755
	StateDirectoryMode: 0755
	CacheDirectoryMode: 0755
	LogsDirectoryMode: 0755
	ConfigurationDirectoryMode: 0755
	StandardInput: null
	StandardOutput: inherit
	StandardError: inherit
	AmbientCapabilities: cap_chown cap_net_raw
	User: nobody
	DynamicUser: no
	LockPersonality: no
exec-ambientcapabilities-merge-nobody.service: User lookup succeeded: uid=65534 gid=65534
exec-ambientcapabilities-merge-nobody.service: Executing: /bin/sh -x -c 'c=$(grep "CapAmb:" /proc/self/status); test "$c" = "CapAmb:	0000000000002001"'
+ grep CapAmb: /proc/self/status
+ c=CapAmb:	0000000000002001
+ test CapAmb:	0000000000002001 = CapAmb:	0000000000002001
Received SIGCHLD from PID 1763 (sh).
Child 1763 (sh) died (code=exited, status=0/SUCCESS)
exec-ambientcapabilities-merge-nobody.service: Child 1763 belongs to exec-ambientcapabilities-merge-nobody.service.
exec-ambientcapabilities-merge-nobody.service: Main process exited, code=exited, status=0/SUCCESS
exec-ambientcapabilities-merge-nobody.service: Changed start -> dead
	PID: 1763
	Start Timestamp: Mon 2018-07-23 15:03:43 UTC
	Exit Timestamp: Mon 2018-07-23 15:03:43 UTC
	Exit Code: exited
	Exit Status: 0
BPF firewalling not supported on this manager, proceeding without.
exec-bindpaths.service: Passing 0 fds to service
exec-bindpaths.service: About to execute: /usr/bin/touch /tmp/test-exec-bindpaths/thisisasimpletest
exec-bindpaths.service: Forked /usr/bin/touch as 1765
exec-bindpaths.service: Changed dead -> start
exec-bindpaths.service
	UMask: 0022
	WorkingDirectory: /root
	RootDirectory: /
	NonBlocking: no
	PrivateTmp: no
	PrivateDevices: no
	ProtectKernelTunables: no
	ProtectKernelModules: no
	ProtectControlGroups: no
	PrivateNetwork: no
	PrivateUsers: no
	ProtectHome: no
	ProtectSystem: no
	MountAPIVFS: no
	IgnoreSIGPIPE: yes
	MemoryDenyWriteExecute: no
	RestrictRealtime: no
	KeyringMode: inherit
	RuntimeDirectoryPreserve: no
	RuntimeDirectoryMode: 0755
	StateDirectoryMode: 0755
	CacheDirectoryMode: 0755
	LogsDirectoryMode: 0755
	ConfigurationDirectoryMode: 0755
	StandardInput: null
	StandardOutput: inherit
	StandardError: inherit
	DynamicUser: no
	BindPaths: /tmp:/tmp/test-exec-bindpaths:rbind
	BindReadOnlyPaths: /tmp:/tmp/test-exec-bindreadonlypaths:rbind
	LockPersonality: no
exec-bindpaths.service: Failed to set up namespace, assuming containerized execution, ignoring: Permission denied
exec-bindpaths.service: Executing: /usr/bin/touch /tmp/test-exec-bindpaths/thisisasimpletest
Received SIGCHLD from PID 1765 (touch).
Child 1765 (touch) died (code=exited, status=0/SUCCESS)
exec-bindpaths.service: Child 1765 belongs to exec-bindpaths.service.
exec-bindpaths.service: Main process exited, code=exited, status=0/SUCCESS
exec-bindpaths.service: Running next main command for state start.
exec-bindpaths.service: Passing 0 fds to service
exec-bindpaths.service: About to execute: /usr/bin/test -f /tmp/thisisasimpletest
exec-bindpaths.service: Forked /usr/bin/test as 1766
exec-bindpaths.service: Failed to set up namespace, assuming containerized execution, ignoring: Permission denied
exec-bindpaths.service: Executing: /usr/bin/test -f /tmp/thisisasimpletest
Received SIGCHLD from PID 1766 (test).
Child 1766 (test) died (code=exited, status=1/FAILURE)
exec-bindpaths.service: Child 1766 belongs to exec-bindpaths.service.
exec-bindpaths.service: Main process exited, code=exited, status=1/FAILURE
exec-bindpaths.service: Failed with result 'exit-code'.
exec-bindpaths.service: Changed start -> failed
exec-bindpaths.service: Unit entered failed state.
	PID: 1766
	Start Timestamp: Mon 2018-07-23 15:03:43 UTC
	Exit Timestamp: Mon 2018-07-23 15:03:43 UTC
	Exit Code: exited
	Exit Status: 1
Assertion 'service->main_exec_status.status == status_expected' failed at ../src/test/test-execute.c:59, function check(). Aborting.
Aborted
```

**Comment by mbiebl** [comment] 2018-07-23 15:20
It's a privileged container

**Comment by mskarbek** [comment] 2018-07-24 14:51
Same in systemd-nspawn and in qemu VM on Fedora.

**Comment by yuwata** [comment] 2018-09-03 14:16
@mbiebl Could you test this with a recent snapshot? As the error handling about the namespace setup has been updated recently.

**Comment by mbiebl** [comment] 2018-09-04 16:45
@yuwata hm, looks like a lot more, new failures now

**Comment by mbiebl** [comment] 2018-09-04 17:39
With AppArmor confinement disabled: 
[lxc_git-unconfined.txt](https://github.com/systemd/systemd/files/2349607/lxc_git-unconfined.txt)

**Comment by mbiebl** [comment] 2018-09-04 17:39
So it seems, for some reason git master performs particularly worse with AA enabled then 239 did.

**Comment by evverx** [comment] 2018-09-04 17:53
I think that the tests has started to fail when https://github.com/systemd/systemd/commit/1beab8b0d0ff2d7d1436b52d4a0c3d56dc908962 was merged. It's probably worth opening an issue because it's clearly a regression.

**Comment by evverx** [comment] 2018-09-04 18:16
It's unclear why `exec-privatenetwork-yes.service` is failing, though. Could you run something like
```sh
ip link
unshare -n
unshare -n sh -c 'ip link'
```
from inside an unconfined container?

**Comment by evverx** [comment] 2018-09-04 18:18
Whatever it is, it probably should be discussed in another issue as well.

**Comment by evverx** [comment] 2018-09-04 18:44
@yuwata regarding the original issue, no, it hasn't gone away because the test expects the environment where it can fully set up its namespaces and the like. Inside containers, especially inside containers with some kind of security policy applied, that usually doesn't work, so the test fails and will fail until it is fixed somehow :-)

**Comment by mbiebl** [comment] 2018-09-04 23:59
@evverx you were spot on. It's indeed 1beab8b which causes all those failures. Reverting that particular commit I'm back to a single failure, test_execute, i.e. this one.

**Comment by yuwata** [comment] 2018-09-05 02:01
> [lxc_git_b711aee08.txt](https://github.com/systemd/systemd/files/2349564/lxc_git_b711aee08.txt)
```
Failed to remount '/' as SLAVE: Permission denied
exec-basic.service: Failed to set up mount namespacing: Permission denied
exec-basic.service: Failed at step NAMESPACE spawning /usr/bin/touch: Permission denied
```
`mount(NULL, "/", NULL, MS_SLAVE|MS_REC, NULL);` [here](https://github.com/systemd/systemd/blob/b711aee08f9406175ae61244fd186bd5c0969817/src/core/namespace.c#L1328-L1333) is failed.

**Closed as completed** 2018-10-24 20:00 UTC
Labels: tests, lxc/lxd

**Comment by mbiebl** [comment] 2018-10-24 23:20
Unfortunately, the test still fails under AA-confined LXC:
```
====== test-execute =======
Found cgroup on /sys/fs/cgroup/systemd, legacy hierarchy
Found cgroup on /sys/fs/cgroup/systemd, legacy hierarchy
Using cgroup controller name=systemd. File system hierarchy is at /sys/fs/cgroup/systemd/user.slice/user-0.slice/session-3.scope/b8ee1c8e2ef9f755.
Not running with unified cgroups, BPF firewalling is not supported.
Not running with unified cgroups, BPF device control is not supported.
Controller 'cpu' supported: yes
Controller 'cpuacct' supported: yes
Controller 'io' supported: no
Controller 'blkio' supported: yes
Controller 'memory' supported: yes
Controller 'devices' supported: yes
Controller 'pids' supported: yes
Controller 'bpf-firewall' supported: no
Controller 'bpf-devices' supported: no
Looking for unit files in (higher priority first):
	/usr/lib/systemd/tests/testdata/test-execute
Unit type .device is not supported on this system.
Unit type .automount is not supported on this system.
Found container virtualization lxc.
Unit type .swap is not supported on this system.
Unit type .device is not supported on this system.
Unit type .automount is not supported on this system.
Unit type .swap is not supported on this system.
run.mount: Failed to load configuration: No such file or directory
run-user.mount: Failed to load configuration: No such file or directory
root.mount: Failed to load configuration: No such file or directory
dev.mount: Failed to load configuration: No such file or directory
proc.mount: Failed to load configuration: No such file or directory
tmp.mount: Failed to load configuration: No such file or directory
sys.mount: Failed to load configuration: No such file or directory
sys-fs.mount: Failed to load configuration: No such file or directory
sys-fs-fuse.mount: Failed to load configuration: No such file or directory
sys-devices.mount: Failed to load configuration: No such file or directory
sys-devices-virtual.mount: Failed to load configuration: No such file or directory
proc-sys.mount: Failed to load configuration: No such file or directory
Successfully created private D-Bus server.
Bus bus-system: changing state UNSET → OPENING
Bus bus-system: changing state OPENING → AUTHENTICATING
Successfully connected to system bus.
Invoking unit coldplug() handlers…
-.slice changed dead -> active
proc-stat.mount: Changed dead -> mounted
dev-hugepages.mount: Changed dead -> mounted
proc-diskstats.mount: Changed dead -> mounted
proc-meminfo.mount: Changed dead -> mounted
proc-cpuinfo.mount: Changed dead -> mounted
proc-uptime.mount: Changed dead -> mounted
proc-sysrq\x2dtrigger.mount: Changed dead -> mounted
dev-tty3.mount: Changed dead -> mounted
dev-tty4.mount: Changed dead -> mounted
tmp-autopkgtest\x2dlxc.itpgffk8.mount: Changed dead -> mounted
sys-devices-virtual-net.mount: Changed dead -> mounted
dev-tty1.mount: Changed dead -> mounted
run-user-0.mount: Changed dead -> mounted
proc-swaps.mount: Changed dead -> mounted
dev-tty2.mount: Changed dead -> mounted
sys-fs-fuse-connections.mount: Changed dead -> mounted
dev-ptmx.mount: Changed dead -> mounted
dev-mqueue.mount: Changed dead -> mounted
-.mount: Changed dead -> mounted
proc-sys-net.mount: Changed dead -> mounted
init.scope changed dead -> running
Invoking unit catchup() handlers…
shutdown.target: Failed to load configuration: No such file or directory
basic.target: Failed to load configuration: No such file or directory
exec-basic.service: Passing 0 fds to service
exec-basic.service: About to execute: /usr/bin/touch /tmp/a
exec-basic.service: Forked /usr/bin/touch as 1287
exec-basic.service: Changed dead -> start
Bus bus-system: changing state AUTHENTICATING → HELLO
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 signature=n/a error-name=n/a error-message=n/a
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=AddMatch cookie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.10 path=n/a interface=n/a member=n/a cookie=1 reply_cookie=1 signature=s error-name=n/a error-message=n/a
Bus bus-system: changing state HELLO → RUNNING
Got message type=signal sender=org.freedesktop.DBus destination=:1.10 path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=NameAcquired cookie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.10 path=n/a interface=n/a member=n/a cookie=3 reply_cookie=2 signature=n/a error-name=n/a error-message=n/a
Match type='signal',path='/org/freedesktop/systemd1/agent',interface='org.freedesktop.systemd1.Agent',member='Released' successfully installed.
Failed to remount '/' as SLAVE: Permission denied
exec-basic.service: Failed to set up mount namespacing: Permission denied
exec-basic.service: Failed at step NAMESPACE spawning /usr/bin/touch: Permission denied
Received SIGCHLD from PID 1287 ((touch)).
Child 1287 ((touch)) died (code=exited, status=226/NAMESPACE)
exec-basic.service: Child 1287 belongs to exec-basic.service.
exec-basic.service: Main process exited, code=exited, status=226/NAMESPACE
exec-basic.service: Failed with result 'exit-code'.
exec-basic.service: Changed start -> failed
exec-basic.service: Unit entered failed state.
Spawning thread to nuke /tmp/systemd-private-2ddb354e45f248ab8caa3364591ae584-exec-basic.service-e7AeuT
Spawning thread to nuke /var/tmp/systemd-private-2ddb354e45f248ab8caa3364591ae584-exec-basic.service-FiyKIY
Assertion 'service->main_exec_status.status == status_expected' failed at ../src/test/test-execute.c:61, function check(). Aborting.
Aborted
FAIL: test-execute (code: 134)
```
That said, I'm not sure if it's worth re-opening given my comments in #10166
