### ISSUE TITLE
systemd 243 has regression for NFS booting

### ISSUE THREAD

**Issue by ChenQi1989** [systemd/systemd#13628] opened 2019-09-23 12:47 UTC
On current 243, NFS boot does not work. It seems that default.target is not treated as multi-user.target even though the symlink (/etc/systemd/system/default.target -> /lib/systemd/system/multi-user.target) is there.

Here's the FragmentPath value of 'systemctl show default.target' on 243.
FragmentPath=/etc/systemd/system/default.target

Here's the FragmentPath value of 'systemctl show default.target' on 242.
FragmentPath=/lib/systemd/system/multi-user.target

I think this is clearly a regression.

**Comment by ChenQi1989** [comment] 2019-09-24 08:50
I suspect this regression is caused by the following commit.

commit e8630e695232bdfcd16b55f3faafb4329c961104
Author: Zbigniew Jędrzejewski-Szmek <zbyszek@in.waw.pl>
Date:   Thu Jul 18 13:11:28 2019 +0200

    pid1: use a cache for all unit aliases
    
    This reworks how we load units from disk. Instead of chasing symlinks every
    time we are asked to load a unit by name, we slurp all symlinks from disk
    and build two hashmaps:
    1. from unit name to either alias target, or fragment on disk
       (if an alias, we put just the target name in the hashmap, if a fragment
        we put an absolute path, so we can distinguish both).
    2. from a unit name to all aliases
    
    Reading all this data can be pretty costly (40 ms) on my machine, so we keep it
    around for reuse.
    
    The advantage is that we can reliably know what all the aliases of a given unit
    are. This means we can reliably load dropins under all names. This fixes #11972.

**Comment by ChenQi1989** [comment] 2019-09-24 09:40
I've sent out a PR: https://github.com/systemd/systemd/pull/13637

**Comment by michaelolbrich** [comment] 2019-09-25 06:23
This is probably a duplicate of #13609.

**Comment by yuwata** [comment] 2019-09-25 07:27
@michaelolbrich Could you test #13637?

**Comment by michaelolbrich** [comment] 2019-09-26 12:50
@yuwata #13637 fixes my problem in #13609.

**Closed as completed** 2019-09-26 12:53 UTC
Labels: bug 🐛, pid1, duplicate
