### ISSUE TITLE
244-rc1 hangs for ~90sec on shutdown/reboot with "systemd-shutdown[1]: Waiting for process: systemd-udevd"

### ISSUE THREAD

**Issue by mamarley** [systemd/systemd#14140] opened 2019-11-25 02:21 UTC
**systemd version the issue has been seen with**
> 244-rc1

**Used distribution**
 > Ubuntu

**Expected behaviour you didn't see**
 > System should shut down/reboot quickly without hanging

**Unexpected behaviour you saw**
 > System hangs for ~90sec after "Reached target: Reboot" on "systemd-shutdown[1]: Waiting for process: systemd-udevd" before shutting down/rebooting

**Steps to reproduce the problem**
Shut down/reboot a system running 244-rc1.  This has happened to every system on which I have tried it.  I tried setting TimeoutStopSec in systemd-udevd.service and DefaultTimeoutStopSec in /etc/systemd/system.conf and neither has any effect.  I have checked /var/log/syslog and I don't see anything pertaining to the problem there.  I apologize for not providing any more information, but I'm not able to find anything pertaining to debugging this type of problem in the documentation.  However, I am more than willing to provide any information for which you ask.

**Comment by yuwata** [comment] 2019-11-25 02:52
This seems a duplicate of #14128.

**Comment by mamarley** [comment] 2019-11-25 03:14
That's what I thought at first too, but that report is with 243.  I can't reproduce the issue with 243.  Also, that report indicates a different message "A stop job is running…" than mine.

**Comment by ganthore** [comment] 2019-11-25 04:38
I'm experiencing this issue with 243.162

**Comment by poettering** [comment] 2019-11-25 10:31
There's no upstream version 243.162? What is that? Does it include a backport of bfde9421af1458e18999d787b1ab46a6a33e8bb6?

/cc @mwilck

**Comment by mamarley** [comment] 2019-11-25 12:59
I booted with "udev.log_priority=debug" as requested in the other ticket.  The result in /var/log/syslog is at https://paste.ubuntu.com/p/G6zBGkk7wc/.  Nothing additional was printed on the console when the shutdown hung.

**Comment by mwilck** [comment] 2019-11-25 14:52
As in #14128, we've got a number of udev workers that don't finish (I count 18). These are your actual problem, my patch just makes it obvious that they are hanging. Please watch out for hanging processess (e.g. `alt-sysrq-w`). It may be easier to debug this if you just run `systemctl stop systemd-udevd` while the system is up, rather than performing a full shutdown.

If you're just looking for a workaround, see [here](https://github.com/systemd/systemd/issues/14128#issuecomment-558176706).  Wait, you are saying `TimeoutStopSec` doesn't work? That's really weird, what value of `TimeoutStopSec` have you tried?  Note that you have to set  `TimeoutStopSec` to a *lower* value than normal, e.g. 30s or even less. If that still hangs, I'd like to see a log with `systemd.log_level=debug udev.log-priority=debug` showing that that setting is not effective.

Also like in #14128, you're rebooting very quickly, almost immediately after the system is up. The udev worker timeout is 300s by default, so it's not a surprise that hanging workers (from system boot) are now causing trouble during shutdown.

The workers that hang are kind of unusual, it looks like stuff from the kernel memory allocator:

    anon_vma(15:init.scope): Device (SEQNUM=2817, ACTION=add) is queued
    sock_inode_cache(31:dev-hugepages.mount): Device (SEQNUM=2825, ACTION=add) is queued
    PING(31:dev-hugepages.mount): Device (SEQNUM=2826, ACTION=add) is queued
    kmalloc-4k(31:dev-hugepages.mount): Device (SEQNUM=2831, ACTION=add) is queued
    filp(35:dev-mqueue.mount): Device (SEQNUM=2843, ACTION=add) is queued

I'm wondering why udev should bother with these "devices" at all. At least on my system, I can see no udev rules that would apply to them. Of course, that makes it even stranger that workers for these events hang. Normally workers can only hang if they call some external programs or builtins that (attempt to) access resources or do IO.

**Comment by mamarley** [comment] 2019-11-25 16:11
I was rebooting quickly, but that was just for the purposes of reproducing the problem quickly.  I see the same behavior even if I leave the system running for hours before shutting down.  If I do `sudo systemctl stop systemd-udevd`, the process quits (and restarts) before I can do `sudo systemctl status systemd-udevd` to see what is happening.  If I then proceed to reboot the system immediately after that, it still hangs in exactly the same manner.

I have tried setting `TimeoutStopSec` to "5s", but it has absolutely no effect.  Also, unlike the other ticket, I never see `A stop job is running…` at all, it just goes straight to `systemd-shutdown[1]: Waiting for process: systemd-udevd`, so it doesn't even look like it is hitting the normal timeout.  Here is the /var/log/syslog of a reboot with `systemd.log_level=debug udev.log-priority=debug` and `DefaultTimeoutStopSec=5s`: [https://michaelmarley.com/downloads/misc/systemd-debug-output.log](https://michaelmarley.com/downloads/misc/systemd-debug-output.log)

**Comment by yuwata** [comment] 2019-11-25 16:26
Hmm. systemd-udevd.service does not have `Conflicts=shutdown.target`. So, it is killed by `systemd-shutdown`, not `systemd[1]`. @poettering is it intended?

**Comment by yuwata** [comment] 2019-11-25 16:35
I guess, by adding `Conflicts=shutdown.target` to systemd-udevd.service, `TimeoutStopSec=` should works.

**Comment by mwilck** [comment] 2019-11-25 17:08
>  If I do `sudo systemctl stop systemd-udevd`, the process quits (and restarts) before I can do `sudo systemctl status systemd-udevd` to see what is happening. If I then proceed to reboot the system immediately after that, it still hangs in exactly the same manner.

OK, you may need to shutdown the udev sockets first. Anyway, if it's possible to stop and restart udevd, then why is it hanging at shutdown? I could see in your original logs that it was waiting for some workers to finish, and they looked like workers that had been started during boot. Could you boot with `udev.event-timeout=30 udev.log-priority=debug`, wait a minute after the system is up (which should cause all workers to either finished or be killed), stop/restart udevd, shutdown, and provide the logs?

> https://michaelmarley.com/downloads/misc/systemd-debug-output.log

I can see no error or hang in that file, could you help me out?

**Comment by mamarley** [comment] 2019-11-25 17:27
> OK, you may need to shutdown the udev sockets first. Anyway, if it's possible to stop and restart udevd, then why is it hanging at shutdown?

You're asking me?

>I could see in your original logs that it was waiting for some workers to finish, and they looked like workers that had been started during boot. Could you boot with `udev.event-timeout=30 udev.log-priority=debug`, wait a minute after the system is up (which should cause all workers to either finished or be killed), stop/restart udevd, shutdown, and provide the logs?

I tried that, and it curiously still hangs for 90s on the shutdown.  Here is the output: [https://michaelmarley.com/downloads/misc/udevd-event-timeout-30.log](https://michaelmarley.com/downloads/misc/udevd-event-timeout-30.log)

> 
> > https://michaelmarley.com/downloads/misc/systemd-debug-output.log
> 
> I can see no error or hang in that file, could you help me out?

The hang can't be seen in the file as it occurs after logging has stopped and the disks have been dismounted.  Nothing other than the systemd-shutdown message is displayed on the console.

**Comment by mwilck** [comment] 2019-11-25 20:12
> You're asking me?

No, everyone. I don't understand it. It has nothing to do with my patch though. The only effect my patch has is that udev doesn't kill hanging workers 30s after having been asked to quit.

> https://michaelmarley.com/downloads/misc/udevd-event-timeout-30.log

It seems that we're missing messages. Please make sure rate limiting is off in `/etc/systemd/journald.conf`. 

    Nov 25 12:16:18 mamarley-desktop systemd-udevd[361]: filp(31:dev-hugepages.mount): Device (SEQNUM=2823, ACTION=add) is queued
    ...
    Nov 25 12:16:18 mamarley-desktop systemd-udevd[375]: filp(135:console-setup.service): Device (SEQNUM=5005, ACTION=remove) processed

As you can see, worker with PID 375 starts out for SEQNUM 2823, but continues with SEQNUM 5005. This can only be due to lost messages. So, while I still believe some workers must be hanging, the SEQNUM values that I derived from the logs may well be false positives.

In the log you referenced, I cannot see systemd-udevd being stopped and re-started . Messags from the original udevd PID (361) are seen until immediately before the reboot:

    Nov 25 12:18:04 mamarley-desktop systemd-udevd[361]: kmalloc-64(399:pulseaudio.service): Worker [1351] is forked for processing SEQNUM=7465.
    Nov 25 12:18:04 mamarley-desktop systemd-udevd[1351]: kmalloc-64(399:pulseaudio.service): sd-device-monitor: Passed 181 byte to netlink monitor
    Nov 25 12:18:04 mamarley-desktop systemd[1]: Stopped target Multi-User System.

> The hang can't be seen in the file as it occurs after the disks have been unmounted.

That's unfortunate. Please have a look at [diagnosing shutdown problems](https://freedesktop.org/wiki/Software/systemd/Debugging/#index2h1).

**Comment by mwilck** [comment] 2019-11-25 20:18
@yuwata,

> Hmm. systemd-udevd.service does not have `Conflicts=shutdown.target`. So, it is killed by `systemd-shutdown`, not `systemd[1]`. @poettering is it intended?

Indeed. This might also have an effect on *how* systemd-udevd and its children (workers) are killed. The unit file has "`KillMode=mixed`", which is the Right Thing to do to kill udevd. Would systemd-shutdown do the same? I guess not...

@mamarley, could you try adding `Conflicts=shutdown.target`, please?

**Comment by mamarley** [comment] 2019-11-25 22:08
> It seems that we're missing messages. Please make sure rate limiting is off in `/etc/systemd/journald.conf`.
> 
> ```
> Nov 25 12:16:18 mamarley-desktop systemd-udevd[361]: filp(31:dev-hugepages.mount): Device (SEQNUM=2823, ACTION=add) is queued
> ...
> Nov 25 12:16:18 mamarley-desktop systemd-udevd[375]: filp(135:console-setup.service): Device (SEQNUM=5005, ACTION=remove) processed
> ```
> 
> As you can see, worker with PID 375 starts out for SEQNUM 2823, but continues with SEQNUM 5005. This can only be due to lost messages. So, while I still believe some workers must be hanging, the SEQNUM values that I derived from the logs may well be false positives.

I was using the default settings for journald; I didn't modify them at all.  I was also pulling the data from /var/log/syslog, not from journald directly.  I can try doing that though, when I get a chance.

> In the log you referenced, I cannot see systemd-udevd being stopped and re-started . Messags from the original udevd PID (361) are seen until immediately before the reboot:

I didn't stop and restart udev during that session.  When I did, nothing interesting was printed in the logs, and it certainly didn't time out.

> That's unfortunate. Please have a look at [diagnosing shutdown problems](https://freedesktop.org/wiki/Software/systemd/Debugging/#index2h1).

I'm not sure how it could be any different.  If my understanding of systemd-shutdown is correct, it is the very last thing that runs on the system after the system is otherwise ready for shutdown.

> @mamarley, could you try adding `Conflicts=shutdown.target`, please?

When I do that, the timeout works as it should.

**Comment by yuwata** [comment] 2019-11-26 08:32
> > @mamarley, could you try adding `Conflicts=shutdown.target`, please?
> 
> When I do that, the timeout works as it should.

:+1:

**Comment by mwilck** [comment] 2019-11-26 09:43
> I was using the default settings for journald; I didn't modify them at all.

Rate limiting is enabled by default. See `journald.conf(5)`.

> > That's unfortunate. Please have a look at diagnosing shutdown problems.
>
> I'm not sure how it could be any different. If my understanding of systemd-shutdown is correct, it is the very last thing that runs on the system after the system is otherwise ready for shutdown.

In order to make progress on your issue, we need to see meaningful log messages from the situation when the shutdown is hanging. Does that make sense to you?

**Comment by poettering** [comment] 2019-11-26 09:58
Hmm, @mwilck so can you elaborate on the rationale of #13961 a bit more? I am tempted to just revert that. It appears to me that those drivers which are borked if we abort the rules are pretty broken, no? What specifically are those drivers? Why are they affected if we kill the *userspace* worker processes?

I mean, there are always borked kernel drivers, and they should be fixed, but it appears to me that if we can choose between "fail badly at boot" and "fail badly at shutdown" we should opt for the former...

**Comment by mwilck** [comment] 2019-11-26 11:25
> Hmm, @mwilck so can you elaborate on the rationale of #13961 a bit more? I am tempted to just revert that.

I think you understand that this is really just "shooting the messenger". The problem is the hanging workers, and my patch causes a few more of these to get noticed. While this is causing some trouble presently, it may be a good thing in the long run.

The core idea of #13961 was that the timeouts udev uses are inconsistent. The udev event timeout is 180s, the exit timeout was only 30s. DefaultTimeout{Start,Stop}Sec is 90s.  For the "fibre channel probing in initrd" special case, this means e.g.:

 * If the system's root device happens to be found late during probing, the driver will likely finish probing. The worker will be killed after 180s at the earliest, and that timeout is configurable.
 * If the root device is found early, modprobe may be killed after as little as 30s with the "exit timeout" as it used to be before #13961. Thus the probing will be interrupted much earlier, and devices may be missing. Moreover, the exit timeout wasn't configurable.

My first idea had actually been to make the exit timeout configurable, too (#13956). The idea not to use an exit timeout at all was born in a conversation with @fbuihuu, and acked by  @keszybz, so that #13956 was ditched in favor of #13961.

Another aspect of #13961 was that having udev and its workers killed by PID 1 is more transparent and more consistent (and actually, configurable in standard ways) than having that hard-coded 30s exit timeout in udevd itself. I'd expect that this idea would appeal to you.

Now we've encountered a bug (missing `Conflicts=shutdown.target`) which broke the "configurability" part. That's not directly related to my patch, which just made it apparent.

> It appears to me that those drivers which are borked if we abort the rules are pretty broken, no? 

Not sure about that. SCSI device can take a long time, especially on large fabrics. You can speed it up in part by async probing, but that has its limits.

> What specifically are those drivers? 

We've seen it with Fibre Channel, in particular qla2xxx.

> Why are they affected if we kill the _userspace_ worker processes?

It happens if modprobe is killed while the driver is still probing devices.

> I mean, there are always borked kernel drivers, and they should be fixed

It seems to be really hard to fix in general, otherwise it would have been done long ago. Async probing is difficult to get right in the kernel. You need to guard against all sorts of race conditions between device addition, activation, and removal. In a fabric, weird stuff can happen while you're still probing. I guess that's why some drivers try to play it safe during modprobe, which works in general, it just happens to take a long time in certain environments.

> but it appears to me that if we can choose between "fail badly at boot" and "fail badly at shutdown" we should opt for the former...

Is this really "failing badly"? We hang until a timeout is reached. I have seen this many times for various different reasons. If the timeout is eventually reached, and is configurable, it's not that bad IMO. Of course we should find out what hanging processes are causing @mamarley's issue, and I'm trying to (note that @CarbonChauvinist's issue in #14128 is not related to my patch).

By adding  `Conflicts=shutdown.target` to systemd-udevd.service, the situation at shutdown could be improved. We might also add a default `TimeoutStopSec=30` to systemd-udevd.service to make it behave as it used to.  The only difference then would be a different failure mode (udevd exiting by itself with error code because workers can't be killed vs. udevd *and* its workers being killed by PID 1), leading to different log messages during shutdown.

**Comment by mwilck** [comment] 2019-11-26 16:43
@poettering, FTR, commit bfde942 that you intend to revert is **not** applied in the arch package that @mamarley is using (systemd-stable e51d9bf). This regression must have a different cause. Same holds for #14128.

**Comment by mamarley** [comment] 2019-11-26 16:46
I'm not using Arch at all; I'm using Ubuntu with a (self-packaged) 244-rc1.

**Comment by mwilck** [comment] 2019-11-26 16:49
@mamarley, sorry, I got confused with the various users reporting this. Back to start.

**Comment by mwilck** [comment] 2019-11-26 16:52
@mamarley, could you try reverting 5db454b and see if it helps? It's supposed to fix the arch issue.

**Comment by mwilck** [comment] 2019-11-26 16:53
Ah, sorry you're on the master branch, so for you it would be 7b6596d that must be reverted.

**Comment by mamarley** [comment] 2019-11-26 19:30
With that commit reverted, the system shuts down as it should even without the edit to systemd-udevd.service.

**Comment by mwilck** [comment] 2019-11-26 19:43
@mamarley, thanks a lot. Next, could you please keep that commit reverted, and apply 030f457 instead? (would be basically equivalent to testing #14160)?

**Comment by mamarley** [comment] 2019-11-26 20:04
That one works properly too, thanks!

**Comment by mwilck** [comment] 2019-11-26 20:07
Thank you!

**Closed as completed** 2019-11-27 13:11 UTC
Labels: udev, regression ⚠️
