### ISSUE TITLE
session can't be released in systemd-logind

### ISSUE THREAD

**Issue by yangmingtai** [systemd/systemd#27667] opened 2023-05-17 03:25 UTC
### systemd version the issue has been seen with

249

### Linux kernel version used

kernel-5.10

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

when user logout, the session be deleted。

when user logout, systemd sends a UnitRemoved message when releasing a scope unit, and checks whether anyone has subscribed before sending it. Typically, systemd-logind sends a 'Subscribe' message at startup to subscribe, so the message will be sent.
If no one subscribes, the message will not be sent. 
`unit_free->bus_unit_send_removed_signal->bus_foreach_bus`
![image](https://github.com/systemd/systemd/assets/17870505/b754e406-1566-465e-9909-e6dd92a4fcbd)
systemd-logind receive UnitRemoved , delete session.

### Unexpected behaviour you saw

the session no be delated
![image](https://github.com/systemd/systemd/assets/17870505/fa861921-bb55-4516-8bd3-9845922d133f)

The abnormal situation is that systemd sends a dbus message that times out, resulting in an active disconnection and the release of dbus and subscribed. However, systemd-logind does not re-subscribe, so the new connection established between systemd and dbus-daemon is not subscribed and will not send UnitRemoved messages.
![image](https://github.com/systemd/systemd/assets/17870505/ca4a97ac-ff34-4da6-adf9-cb72f16a4423)

The impact is that without UnitRemoved messages, systemd-logind will not delete the session

### Steps to reproduce the problem

Stress Testing ，Timeout between systemd and dbus-daemon

**Comment by dtardon** [comment] 2023-05-17 05:55
This is likely a duplicate of #26744.

**Comment by yangmingtai** [comment] 2023-05-17 07:43
> systemd-logind does not re-subscribe

Yes, that's similar. we identified the reason：dbus timed out, systemd uref "m->subscribed", systemd-logind does not re-subscribe

**Comment by yangmingtai** [comment] 2023-05-17 07:44
> This is likely a duplicate of #26744.

Yes, that's similar. we identified the reason：dbus timed out, systemd uref "m->subscribed", systemd-logind does not re-subscribe

**Comment by poettering** [comment] 2023-06-02 10:34
Let's close this copy, and keep #26744

**Closed as completed by poettering** 2023-06-02 10:34 UTC
Labels: bug 🐛, login, duplicate
