### ISSUE TITLE
Memory accounting regression for user units

### ISSUE THREAD

**Issue by vp1981** [systemd/systemd#9502] opened 2018-07-04 00:46 UTC
**systemd version the issue has been seen with**
> 239

**Used distribution**
 >Arch Linux x86_64

**Expected behaviour you didn't see**
 > systemctl --user status firefox.service
should show the current memory consumption and memory limits as for systemd 238 and --system units.

This is output of the command for systemd 238.133-4 (arch specific numbering):
```
● firefox.service - Firefox: famous Web browser
   Loaded: loaded (/home/vladimir/.config/systemd/user/firefox.service; disabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-07-04 08:08:20 +08; 2min 47s ago
     Docs: http://www.mozilla.org/doc
  Process: 8725 ExecStartPre=/usr/bin/ln -sf /run/user/1000/firefox-cache /home/vladimir/.cache/mozilla (code=exited, status=0/SUCCESS)
  Process: 8722 ExecStartPre=/usr/bin/mkdir /run/user/1000/firefox-cache (code=exited, status=1/FAILURE)
  Process: 8721 ExecStartPre=/usr/bin/rm -rf /home/vladimir/.cache/mozilla (code=exited, status=0/SUCCESS)
 Main PID: 8728 (firefox)
    Tasks: 97 (limit: 4915)
   Memory: 406.0M (high: 1.5G max: 2.0G)
   CGroup: /user.slice/user-1000.slice/user@1000.service/firefox.service
           ├─8728 /usr/lib/firefox/firefox
           ├─9024 /usr/lib/firefox/firefox -contentproc -childID 1 -isForBrowser -prefsLen 41606 -schedulerPrefs 0001,2 -greomni /usr/lib/firefox/omni.ja -appomni /usr/lib/firefox/browser/omni.ja -appdir /usr/lib/firefox/browser 8728 true tab
           └─9682 /usr/lib/firefox/firefox -contentproc -childID 3 -isForBrowser -prefsLen 45548 -schedulerPrefs 0001,2 -greomni /usr/lib/firefox/omni.ja -appomni /usr/lib/firefox/browser/omni.ja -appdir /usr/lib/firefox/browser 8728 true tab

июл 04 08:08:20 smoon4.vl-lomov.ru systemd[970]: Starting Firefox: famous Web browser...
июл 04 08:08:20 smoon4.vl-lomov.ru mkdir[8722]: /usr/bin/mkdir: невозможно создать каталог «/run/user/1000/firefox-cache»: Файл существует
июл 04 08:08:20 smoon4.vl-lomov.ru systemd[970]: Started Firefox: famous Web browser.
```

And this is for systemd 239-2:
```
● firefox.service - Firefox: famous Web browser
   Loaded: loaded (/home/vladimir/.config/systemd/user/firefox.service; disabled; vendor preset: enabled)
   Active: active (running) since Wed 2018-07-04 08:15:37 +08; 19s ago
     Docs: http://www.mozilla.org/doc
  Process: 2411 ExecStartPre=/usr/bin/ln -sf /run/user/1000/firefox-cache /home/vladimir/.cache/mozilla (code=exited, status=0/SUCCESS)
  Process: 2410 ExecStartPre=/usr/bin/mkdir /run/user/1000/firefox-cache (code=exited, status=0/SUCCESS)
  Process: 2409 ExecStartPre=/usr/bin/rm -rf /home/vladimir/.cache/mozilla (code=exited, status=0/SUCCESS)
 Main PID: 2412 (firefox)
   CGroup: /user.slice/user-1000.slice/user@1000.service/firefox.service
           ├─2412 /usr/lib/firefox/firefox
           ├─2489 /usr/lib/firefox/firefox -contentproc -childID 1 -isForBrowser -prefsLen 41606 -schedulerPrefs 0001,2 -greomni /usr/lib/firefox/omni.ja -appomni /usr/lib/firefox/browser/omni.ja -appdir /usr/lib/firefox/browser 2412 true tab
           ├─2681 /usr/lib/firefox/firefox -contentproc -childID 2 -isForBrowser -prefsLen 44973 -schedulerPrefs 0001,2 -greomni /usr/lib/firefox/omni.ja -appomni /usr/lib/firefox/browser/omni.ja -appdir /usr/lib/firefox/browser 2412 true tab
           └─2722 /usr/lib/firefox/firefox -contentproc -childID 3 -isForBrowser -prefsLen 45548 -schedulerPrefs 0001,2 -greomni /usr/lib/firefox/omni.ja -appomni /usr/lib/firefox/browser/omni.ja -appdir /usr/lib/firefox/browser 2412 true tab

июл 04 08:15:37 smoon4.vl-lomov.ru systemd[975]: Starting Firefox: famous Web browser...
июл 04 08:15:37 smoon4.vl-lomov.ru systemd[975]: Started Firefox: famous Web browser.
```

**Unexpected behaviour you saw**
 > there is no memory limits and a process can consume all available memory.

**Steps to reproduce the problem**

Nothing fancy, just standard Arch Linux kernel and systemd 238.133-4 from core repository and systemd 239-2 from testing one.

**Comment by vp1981** [comment] 2018-07-04 12:30
```
$ cat /proc/cmdline
initrd=\intel-ucode.img initrd=\initramfs-linux-ck-sandybridge.img root=PARTUUID=7c905015-d2fc-3343-a207-27cb4855d38d systemd.unified_cgroup_hierarchy=1 scsi_mod.use_blk_mq=1 nopti spectre_v2=off rw
```

(This kernel is not from official Arch Linux repo but I checked both and both show the same behavior).

```
$ mount | column -t
sysfs       on  /sys                                              type  sysfs            (rw,nosuid,nodev,noexec,relatime)
proc        on  /proc                                             type  proc             (rw,nosuid,nodev,noexec,relatime)
devtmpfs    on  /dev                                              type  devtmpfs         (rw,nosuid,size=4024696k,nr_inodes=1006174,mode=755)
securityfs  on  /sys/kernel/security                              type  securityfs       (rw,nosuid,nodev,noexec,relatime)
tmpfs       on  /dev/shm                                          type  tmpfs            (rw,nosuid,nodev)
devpts      on  /dev/pts                                          type  devpts           (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs       on  /run                                              type  tmpfs            (rw,nosuid,nodev,mode=755)
cgroup2     on  /sys/fs/cgroup                                    type  cgroup2          (rw,nosuid,nodev,noexec,relatime,nsdelegate)
pstore      on  /sys/fs/pstore                                    type  pstore           (rw,nosuid,nodev,noexec,relatime)
efivarfs    on  /sys/firmware/efi/efivars                         type  efivarfs         (rw,nosuid,nodev,noexec,relatime)
bpf         on  /sys/fs/bpf                                       type  bpf              (rw,nosuid,nodev,noexec,relatime,mode=700)
/dev/sda3   on  /                                                 type  xfs              (rw,relatime,attr2,inode64,noquota)
systemd-1   on  /proc/sys/fs/binfmt_misc                          type  autofs           (rw,relatime,fd=38,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=12670)
debugfs     on  /sys/kernel/debug                                 type  debugfs          (rw,relatime)
hugetlbfs   on  /dev/hugepages                                    type  hugetlbfs        (rw,relatime,pagesize=2M)
mqueue      on  /dev/mqueue                                       type  mqueue           (rw,relatime)
tmpfs       on  /tmp                                              type  tmpfs            (rw,nosuid,nodev)
configfs    on  /sys/kernel/config                                type  configfs         (rw,relatime)
/dev/sda7   on  /mnt/containers                                   type  xfs              (rw,relatime,attr2,inode64,noquota)
/dev/sda8   on  /mnt/storage                                      type  xfs              (rw,relatime,attr2,inode64,noquota)
/dev/sda6   on  /home                                             type  xfs              (rw,relatime,attr2,inode64,noquota)
/dev/sda1   on  /boot                                             type  vfat             (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro)
/dev/sda5   on  /usr/local                                        type  xfs              (rw,relatime,attr2,inode64,noquota)
/dev/sda4   on  /var                                              type  xfs              (rw,relatime,attr2,inode64,noquota)
/dev/sdb1   on  /media/storage                                    type  xfs              (rw,relatime,attr2,inode64,noquota)
tmpfs       on  /run/user/1000                                    type  tmpfs            (rw,nosuid,nodev,relatime,size=806088k,mode=700,uid=1000,gid=100)
overlaid    on  /run/user/1000/vladimir-chromium                  type  overlay          (rw,nosuid,nodev,relatime,lowerdir=/home/vladimir/.config/chromium-backup,upperdir=/run/user/1000/vladimir-chromium-rw,workdir=/run/user/1000/.vladimir-chromium)
overlaid    on  /run/user/1000/vladimir-firefox-fdukghxl.default  type  overlay          (rw,nosuid,nodev,relatime,lowerdir=/home/vladimir/.mozilla/firefox/fdukghxl.default-backup,upperdir=/run/user/1000/vladimir-firefox-fdukghxl.default-rw,workdir=/run/user/1000/.vladimir-firefox-fdukghxl.default)
overlaid    on  /run/user/1000/vladimir-qutebrowser               type  overlay          (rw,nosuid,nodev,relatime,lowerdir=/home/vladimir/.local/share/qutebrowser-backup,upperdir=/run/user/1000/vladimir-qutebrowser-rw,workdir=/run/user/1000/.vladimir-qutebrowser)
fusectl     on  /sys/fs/fuse/connections                          type  fusectl          (rw,relatime)
gvfsd-fuse  on  /run/user/1000/gvfs                               type  fuse.gvfsd-fuse  (rw,nosuid,nodev,relatime,user_id=1000,group_id=100)
tmpfs       on  /run/user/620                                     type  tmpfs            (rw,nosuid,nodev,relatime,size=806088k,mode=700,uid=620,gid=620)
gvfsd-fuse  on  /run/user/620/gvfs                                type  fuse.gvfsd-fuse  (rw,nosuid,nodev,relatime,user_id=620,group_id=620)
```

**Comment by ryutaroh-matsumoto** [comment] 2018-07-07 22:49
Hi,

In my environment, the memory accounting **both works and fails**, depending  on services. The first and the second examples are failing:

```
ryutaroh@unstable:/var/tmp$ systemctl status user@1000.service
 user@1000.service - User Manager for UID 1000
   Loaded: loaded (/lib/systemd/system/user@.service; static; vendor preset: enabled)
   Active: active (running) since Sun 2018-07-08 07:11:30 JST; 1min 54s ago
 Main PID: 1479 (systemd)
   Status: "Startup finished in 194ms."
       IP: 0B in, 0B out
      CPU: 70ms
   CGroup: /user.slice/user-1000.slice/user@1000.service
           ├─dbus.service
           │ └─1525 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
           └─init.scope
             ├─1479 /lib/systemd/systemd --user
             └─1480 (sd-pam)
```

I see a similar behavior with `systemd-run` as

```
$ systemd-run --user --wait -t -p "MemoryAccounting=yes" /bin/echo "Hello!"
Running as unit: run-u0.service
Press ^] three times within 1s to disconnect TTY.
Hello!
Finished with result: success
Main processes terminated with: code=exited/status=0
Service runtime: 55ms
CPU time consumed: 1ms
```

I see CPU Accounting working. The configuration for the first and the second examples are as follows:

```
$ systemctl show user@1000.service | grep Accounting
CPUAccounting=yes
IOAccounting=yes
BlockIOAccounting=no
MemoryAccounting=yes
TasksAccounting=yes
IPAccounting=yes
$ systemctl show user@1000.service | grep Delegate
Delegate=yes
DelegateControllers=memory pids
```

The third example is working (except IP Accounting) as follows:

```
ryutaroh@unstable:/var/tmp$ systemctl status systemd-nspawn@container-desktop.service | head -15
● systemd-nspawn@container-desktop.service - Container container-desktop
   Loaded: loaded (/etc/systemd/system/systemd-nspawn@.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2018-07-08 07:05:48 JST; 29min ago
     Docs: man:systemd-nspawn(1)
 Main PID: 450 (systemd-nspawn)
   Status: "Container running: Startup finished in 4min 42.119s."
       IP: 33.9M in, 3.2G out
    Tasks: 240 (limit: 16384)
   Memory: 1.2G
      CPU: 3min 20.700s
   CGroup: /machine.slice/systemd-nspawn@container-desktop.service
           ├─payload
           │ ├─init.scope
           │ │ └─453 /usr/lib/systemd/systemd
           │ ├─system.slice
```

(By the way, `in` and `out` in IP accounting seem inverted above... Are they correct?? I doubt them.)

```
ryutaroh@unstable:/var/tmp$ systemctl show systemd-nspawn@container-desktop.service | egrep 'Accounting|Delegate'
Delegate=yes
DelegateControllers=cpu io memory pids
CPUAccounting=yes
IOAccounting=yes
BlockIOAccounting=no
MemoryAccounting=yes
TasksAccounting=yes
IPAccounting=yes
```

My environment is systemd 239 on Debian unstable with `systemd.unified_cgroup_hirarchy=1`

**Comment by ryutaroh-matsumoto** [comment] 2018-07-11 09:35
@vp1981 @poettering I found a way to let systemd 239 operate as expected [here](https://github.com/systemd/systemd/issues/9512#issuecomment-404106710)

**Comment by ryutaroh-matsumoto** [comment] 2018-07-15 15:59
In case of this issue being distro-specific, I created a disk image for qemu/kvm [here](https://drive.google.com/file/d/1rsIu6NFwU9W6JMgA-vKPBi-nNcSQmNqM/view) so that users of other distros can reproduce and investigate this issue. The file is tar+gzipped QCOW2 image file of 600 MB, and it can be used with `Import existing disk image` in `Create a new virtual machine` window of `virt-manager`. In the disk image,

* Architecture is x86-64 and systemd package version is 239-5.
* Debian buster (testing) as of 15 July 2018 with `standard` and `openssh server` are selected in the installation process of [Debian buster alpha 3 installer](https://cdimage.debian.org/cdimage/buster_di_alpha3/amd64/iso-cd/).
* User `root` has password `root` and user `guest2` has password `guest2`.
* Configuration files are untouched except `/etc/default/grub` to enable the unified cgroup hirerarchy.
* Keyboard config is US and it can be changed by `dpkg-reconfigure keyboard-configuration`.
* Ssh login is accepted but root ssh login is not allowed.

If you find this issue being a problem of Debian, please let me know.

**Comment by KenMacD** [comment] 2019-11-03 21:38
Any update on this? It doesn't seem to be working for me either:

```systemd-run --user -t -p "MemoryAccounting=true" -p  "MemoryHigh=1M" memhog 1g```

**Comment by deliciouslytyped** [comment] 2019-11-20 04:04
I have this problem.

**Comment by deliciouslytyped** [comment] 2019-11-20 13:16
Might it be confused by hybrid mode? I'll try to reboot with v2 only later.

**Comment by deliciouslytyped** [comment] 2019-11-20 14:00
I haven't rebooted without hybrid mode yet but I tried manually creating a cgroup directory and moving the set of firefox processes to it to see what happens;

opening `file:///proc/self/cgroup` from firefox shows `9:memory:/user.slice/user-1000.slice/user@1000.service/test-firefox.scope` and I still can't get `systemctl status --user run-firefox.scope` to show anything about memory.
```
● run-firefox.scope - /nix/store/i16mr5kna9v63g1k4klw9kxcfrqrr3ch-firefox-69.0/bin/firefox
   Loaded: loaded (/run/user/1000/systemd/transient/run-firefox.scope; transient)
Transient: yes
   Active: active (running) since Sun 2019-11-10 13:18:08 CET; 1 weeks 3 days ago
   CGroup: /user.slice/user-1000.slice/user@1000.service/run-firefox.scope
```

**Comment by deliciouslytyped** [comment] 2019-12-16 03:55
In my case the issue seems to have been caused by being in hybrid mode. I'm not sure if hybrid mode or cgroupsv1 is the culprit.

**Comment by poettering** [comment] 2020-01-21 14:47
Note that controller delegation is only supported on cgroupv2 anot not on systems where cgroupv1 is used (and that means also not hybrid systems, as on those the controllers are all owned by the cgroupv1 stuff).

Hence, sorry,  @deliciouslytyped what you are doing cannot work, and is not supported.

I tried this today again on a current systemd with cgroupsv2 and all works as it should, for me at least. Is this still broken with current upstream systemd in pure cgroupsv2 for you @vp1981?

**Comment by vp1981** [comment] 2020-01-22 00:50
@poettering , yes, everything works fine when I switched to cgroup2 (I think it is the cgroup2, I set the following in kernel command line: `systemd.unified_cgroup_hierarchy=1`, though I'm not completely sure if this is cgroup2 or not (I wish `systemctl` could report not only default cgroup hierarchy but also current one):
```
$ systemctl --version
systemd 244 (244.1-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
$ mount | grep cgroup
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
```
The output from last command makes me think that I **use** cgroup2 and for my firefox service I have
```
$ systemctl --user status firefox | head -n 13
● firefox.service - Firefox: famous Web browser
     Loaded: loaded (/home/vladimir/.config/systemd/user/firefox.service; disabled; vendor preset: enabled)
     Active: active (running) since Tue 2020-01-21 07:57:19 +08; 24h ago
       Docs: http://www.mozilla.org/doc
    Process: 17365 ExecStartPre=/usr/bin/rm -rf /home/vladimir/.cache/mozilla (code=exited, status=0/SUCCESS)
    Process: 17366 ExecStartPre=/usr/bin/mkdir /run/user/1000/firefox-cache (code=exited, status=0/SUCCESS)
    Process: 17367 ExecStartPre=/usr/bin/ln -sf /run/user/1000/firefox-cache /home/vladimir/.cache/mozilla (code=exited, status=0/SUCCESS)
   Main PID: 17368 (firefox)
      Tasks: 252 (limit: 9421)
     Memory: 1.2G (high: 1.5G max: 2.0G swap max: 1.0G)
        CPU: 0
     CGroup: /user.slice/user-1000.slice/user@1000.service/firefox.service
             ├─17368 /usr/lib/firefox/firefox
```

**Comment by poettering** [comment] 2020-01-22 12:53
@vp1981 ah, thanks for reporting back.

The official way to check if we are in pure cgroupv2 mode is to check if  /sys/fs/cgroup/ is of fs type "cgroup2". Which it is for you apparently.

Thanks for reporting back. I guess we can close the issue now.

**Closed as completed by poettering** 2020-01-22 12:53 UTC
Labels: pid1, needs-reporter-feedback ❓
