### ISSUE TITLE
Assertion 'unit' failed at src/core/manager.c:1191

### ISSUE THREAD

**Issue by Earnestly** [systemd/systemd#1526] opened 2015-10-10 21:18 UTC
- linux-zen 4.2.3 (x86_64)
- kdbus revision 245fe938ca0907dd0db36a123a875320c96ddd35
- systemd 227

I'm not sure how I triggered this, I'm also not sure how to reproduce this so the issue may not be very useful.  Any guidance to narrow this down (if necessary) welcome.

To start off I was using `systemctl --user` to manage pulseaudio and mpd daemons.  A few minutes after login sound cut off, mpd was no longer able to connect: `failed to connect to pulse daemon: Connection refused`.

Immediately I attempt to check on pulseaudio and got this:

```
% systemctl --user status pulseaudio
Failed to connect to bus: Connection refused
```

Running a strace on `systemctl` resulted in the following:

```
open("/sys/fs/kdbus/1000-user/bus", O_RDWR|O_NOCTTY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

Indeed, the only contents of `/sys/fs/kdbus` is `0-system` and `control`.

Looking through the journal I found this:

```
Oct 10 21:36:11 teapot sudo[10655]:  earnest : TTY=pts/4 ; PWD=/home/earnest ; USER=root ; COMMAND=/usr/bin/pacman -U /var/cache/pacman/pkg/xf86-video-intel-1:2.99.917+47
Oct 10 21:36:11 teapot sudo[10655]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 10 21:37:39 teapot sudo[10655]: pam_unix(sudo:session): session closed for user root
Oct 10 21:40:33 teapot systemd[376]: Assertion 'unit' failed at src/core/manager.c:1191, function manager_add_job(). Aborting.
Oct 10 21:40:33 teapot systemd[431]: pam_unix(systemd-user:session): session closed for user earnest
```

_[There is nothing else remarkable about the logs but I can upload a full boot log somewhere if necessary.]_

Other notes:  I do mask `org.a11y.Bus.busname` and `org.gnome.GConf.busname` for my user.

**Comment by dvdhrm** [comment] 2015-10-11 08:15
Duplicate of #498.

Can you see whether `coredumpctl` lists you a coredump? If yes, can you provide a backtrace?

**Comment by Earnestly** [comment] 2015-10-11 11:50
(Un)fortuantely it doesn't appear to have produced any coredumps

**Comment by dvdhrm** [comment] 2015-10-12 10:43
Are you sure? Does `coredumpctl` list something? Same if you run it as root? What does `/etc/systemd/coredump.conf` list as `Storage=`?

Given that you use linux-zen, I assume you're on Arch Linux? I think the default is to store coredumps via systemd there. Hmm, maybe @poettering has an idea why there's no coredump for `systemd --user`.

**Comment by Earnestly** [comment] 2015-10-12 13:06
The same situation is true as root, no coredumps are found.  `coredump.conf` contains: `#Storage=external` and `50-coredump.conf` has `kernel.core_pattern=|/usr/lib/systemd/systemd-coredump %p %u %g %s %t %e`

There's no `50-coredump.conf` override in `/etc/sysctl` and `% sysctl kernel.core_pattern` outputs accordingly: `kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %p %u %g %s %t %e`

That said, I may have done something stupid I simply forgot about as well, I can't guarantee sanity here, but everything _appears_ to check out.

**Comment by poettering** [comment] 2015-10-14 14:05
Hmm, there should be a coredump... do you see the coredump binary in /proc/sys/kernel/core_pattern correctly set?

Do you see any logs about a coredump being collected in the journal? Can you provide a longer excerpt from the journal around the messages you posted above?

The only place where I can see the abort to be trigegred at all is from the busname_enter_running() context. In all other cases we explicitly assert on the passed unit before, or it odesn't apply to the user instance of systemd...

I will add some code now which makes the issue non-fatal, if it really is coming from this place. However, that's purely cosmetical, as I don't see how this could even have been triggered...

**Comment by Earnestly** [comment] 2015-10-14 18:28
_Edit: In your commit comments you mention "unless the daemon is reloaded", which is actually something I did, the logs below show this._

```
% cat /proc/sys/kernel/core_pattern
|/usr/lib/systemd/systemd-coredump %p %u %g %s %t %e
```

At the time I had for some reason forgetten I masked `dbus.socket` for my user (not globally), that was fixed by removing the mask.  I was trying to disable busname activation for services (I prefer explicit service activation).

The mpd service warnings were also fixed later, but shouldn't be an issue here I don't think.

```
Oct 10 20:51:51 teapot login[366]: LOGIN ON tty1 BY earnest
Oct 10 20:52:04 teapot systemd[376]: dbus.socket: Cannot add dependency job, ignoring: Unit dbus.socket is masked.
Oct 10 20:52:04 teapot systemd[376]: Started Legacy D-Bus Protocol Compatibility Daemon.
Oct 10 20:52:19 teapot systemd[376]: dbus.socket: Cannot add dependency job, ignoring: Unit dbus.socket is masked.
Oct 10 20:52:19 teapot systemd[376]: Starting DBUS1: org.a11y.Bus...
Oct 10 20:52:19 teapot systemd[376]: dbus.socket: Cannot add dependency job, ignoring: Unit dbus.socket is masked.
Oct 10 20:52:19 teapot systemd[376]: Starting Music Player Daemon...
Oct 10 20:52:19 teapot systemd[376]: Started DBUS1: org.a11y.Bus.
Oct 10 20:52:24 teapot at-spi-bus-launcher[562]: Activating service name='org.a11y.atspi.Registry'
Oct 10 20:52:24 teapot at-spi-bus-launcher[562]: Successfully activated service 'org.a11y.atspi.Registry'
Oct 10 20:52:24 teapot org.a11y.atspi.Registry[574]: SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
Oct 10 20:52:31 teapot systemd[376]: Started Music Player Daemon.
Oct 10 20:52:54 teapot systemd[376]: dbus.socket: Cannot add dependency job, ignoring: Unit dbus.socket is masked.
Oct 10 20:52:54 teapot systemd[376]: Starting DBUS1: org.gnome.GConf...
Oct 10 20:52:54 teapot systemd[376]: Started DBUS1: org.gnome.GConf.
Oct 10 20:54:56 teapot systemd[376]: Reloading.
Oct 10 20:55:01 teapot systemd[376]: Stopping dbus-org.a11y.Bus.service...
Oct 10 20:55:01 teapot systemd[376]: Stopped dbus-org.a11y.Bus.service.
Oct 10 21:02:47 teapot systemd[1]: Starting Cleanup of Temporary Directories...
Oct 10 21:02:48 teapot systemd[1]: Started Cleanup of Temporary Directories.
Oct 10 21:03:57 teapot systemd[376]: Reloading.
Oct 10 21:08:53 teapot systemd[376]: Closed dbus-org.a11y.Bus.busname.
Oct 10 21:09:07 teapot systemd[1]: [/usr/lib/systemd/system/mpd.service:16] Unknown lvalue 'ControlGroup' in section 'Service'
Oct 10 21:09:07 teapot systemd[1]: [/usr/lib/systemd/system/mpd.service:19] Unknown lvalue 'ControlGroupAttribute' in section 'Service'
Oct 10 21:09:07 teapot systemd[1]: [/usr/lib/systemd/system/mpd.service:16] Unknown lvalue 'ControlGroup' in section 'Service'
Oct 10 21:09:07 teapot systemd[1]: [/usr/lib/systemd/system/mpd.service:19] Unknown lvalue 'ControlGroupAttribute' in section 'Service'
Oct 10 21:09:09 teapot systemd[376]: Stopped dbus-org.a11y.Bus.service.
Oct 10 21:09:31 teapot systemd[1]: [/usr/lib/systemd/system/mpd.service:16] Unknown lvalue 'ControlGroup' in section 'Service'
Oct 10 21:09:31 teapot systemd[1]: [/usr/lib/systemd/system/mpd.service:19] Unknown lvalue 'ControlGroupAttribute' in section 'Service'
Oct 10 21:09:31 teapot systemd[1]: [/usr/lib/systemd/system/mpd.service:16] Unknown lvalue 'ControlGroup' in section 'Service'
Oct 10 21:09:31 teapot systemd[1]: [/usr/lib/systemd/system/mpd.service:19] Unknown lvalue 'ControlGroupAttribute' in section 'Service'
Oct 10 21:09:33 teapot systemd[376]: Stopping DBUS1: org.gnome.GConf...
Oct 10 21:09:33 teapot systemd[376]: dbus-org.gnome.GConf.service: Main process exited, code=exited, status=1/FAILURE
Oct 10 21:09:33 teapot systemd[376]: Stopped DBUS1: org.gnome.GConf.
Oct 10 21:09:33 teapot systemd[376]: dbus-org.gnome.GConf.service: Unit entered failed state.
Oct 10 21:09:33 teapot systemd[376]: dbus-org.gnome.GConf.service: Failed with result 'exit-code'.
Oct 10 21:09:44 teapot systemd[376]: Reloading.
Oct 10 21:11:50 teapot systemd[376]: Reloading.
Oct 10 21:11:59 teapot systemd[376]: Closed DBUS1: org.a11y.Bus.
Oct 10 21:13:10 teapot systemd[376]: Reloading.
Oct 10 21:13:20 teapot systemd[376]: Reloading.
Oct 10 21:36:11 teapot sudo[10655]:  earnest : TTY=pts/4 ; PWD=/home/earnest ; USER=root ; COMMAND=/usr/bin/pacman -U /var/cache/pacman/pkg/xf86-video-intel-1:2.99.917+47
Oct 10 21:36:11 teapot sudo[10655]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 10 21:37:39 teapot sudo[10655]: pam_unix(sudo:session): session closed for user root
Oct 10 21:40:33 teapot systemd[376]: Assertion 'unit' failed at src/core/manager.c:1191, function manager_add_job(). Aborting.
Oct 10 21:40:33 teapot systemd[431]: pam_unix(systemd-user:session): session closed for user earnest
Oct 10 21:47:25 teapot systemd[1]: Starting Authorization Manager...
Oct 10 21:47:25 teapot polkitd[13725]: Started polkitd version 0.113
Oct 10 21:47:25 teapot polkitd[13725]: Loading rules from directory /etc/polkit-1/rules.d
Oct 10 21:47:25 teapot polkitd[13725]: Loading rules from directory /usr/share/polkit-1/rules.d
Oct 10 21:47:25 teapot polkitd[13725]: Finished loading, compiling and executing 1 rules
Oct 10 21:47:25 teapot systemd[1]: Started Authorization Manager.
Oct 10 21:47:25 teapot polkitd[13725]: Acquired the name org.freedesktop.PolicyKit1 on the system bus
Oct 10 21:47:25 teapot polkitd[13725]: Registered Authentication Agent for unix-process:13720:363059 (system bus name :1.201 [/usr/bin/pkttyagent --notify-fd 5 --fallback
Oct 10 21:47:25 teapot login[366]: pam_unix(login:session): session closed for user earnest
```

---

And just to confirm that coredumps do get generated correctly, recently when building glibc from master, a commit caused a regression in reading locale data thus the tools needed to generate locales failed:

```
[...]
Oct 13 15:41:36 teapot systemd-coredump[7366]: Process 7365 (bash) of user 0 dumped core.
Oct 13 15:41:37 teapot systemd-coredump[7374]: Process 7371 (sh) of user 1000 dumped core.
Oct 13 15:41:37 teapot systemd-coredump[7376]: Process 7373 (sh) of user 1000 dumped core.
Oct 13 15:41:37 teapot systemd-coredump[7375]: Process 7372 (sh) of user 1000 dumped core.
Oct 13 15:41:38 teapot systemd-coredump[7368]: Process 7367 (ldconfig) of user 0 dumped core.
[...]
```

These do show up in `coredumpctl list`.

**Comment by poettering** [comment] 2015-10-14 18:33
Ah, if you had masked it, then I am quite confident that #1563 fixes the issue fully. Will close now, hence, please reopen if you can make the issue reappear with that PR applied.

**Closed as completed by poettering** 2015-10-14 18:33 UTC
Labels: bug 🐛, pid1

**Comment by Earnestly** [comment] 2015-10-14 18:49
Okay thanks, will do
