### ISSUE TITLE
systemd-boot doesn't set console mode when menu is not shown

### ISSUE THREAD

**Issue by monstrous-moonshine** [systemd/systemd#24649] opened 2022-09-13 06:56 UTC
### systemd version the issue has been seen with

251

### Used distribution

Arch

### Linux kernel version used

5.19.7-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-boot

### Expected behaviour you didn't see

`console-mode` wasn't set to `max` when `timeout` was left to the default (`0`)

**Comment by medhefgo** [comment] 2022-09-13 07:12
To some degree, this is by design. You ask to skip the menu, why should sd-boot change the console mode when there's nothing to output? It's faster to boot this way.

**Comment by monstrous-moonshine** [comment] 2022-09-13 07:29
It's not just the menu, but also the splash screen and boot messages displayed afterwards which are affected by it. On my firmware, if the boot manager doesn't set the console mode, I found it impossible to increase the framebuffer resolution afterwards, so it also affects any virtual console I might open.

**Comment by medhefgo** [comment] 2022-09-13 10:23
The problem is that it tends to trip up windows if that's the default boot option. The firmware logo will be in the wrong position and I have no idea as to why.

**Comment by monstrous-moonshine** [comment] 2022-09-13 10:49
Thanks for your reply. I built systemd-boot myself from the git repo where I took the console mode setting code out of `menu_run()` and put it before the conditional that checks if the menu is to be shown. The framebuffer resolution is now set correctly for me when I boot Linux as the default option. To confirm your comment, I then booted Windows as default, but couldn't see any problem. Still, if it's a problem that happens in other setups, I understand that you wouldn't want to change the way it is now. :)

**Comment by monstrous-moonshine** [comment] 2022-09-15 17:06
This is indeed very specific to my desktop firmware, and doesn't even happen on my laptop. I could live with setting the timeout to `1`. Thanks for your time. :-)

**Comment by poettering** [comment] 2022-09-16 08:59
OK, thanks. Then let's close this here.

**Closed as completed by poettering** 2022-09-16 08:59 UTC
Labels: needs-discussion 🤔, not-our-bug, sd-boot/sd-stub/bootctl

**Comment by medhefgo** [comment] 2022-10-03 19:25
@monstrous-moonshine Have you tried booting with `video=efifb:mode=N` (you can have the kernel list the supported modes with `video=efifb:list`, but most likely `0` is the native resolution)? It should do the trick.

**Comment by monstrous-moonshine** [comment] 2022-10-04 03:41
@medhefgo Thanks for the tip, this indeed works!
