### ISSUE TITLE
systemd-tImesyncd fails to connect to time server due to failed DNSSEC lookup

### ISSUE THREAD

**Issue by gearhead** [systemd/systemd#15607] opened 2020-04-25 19:03 UTC
**systemd version the issue has been seen with**
> 245

**Used distribution**
 > ArchArm RaspberryPi4 - ArchLinuxARM-rpi-4-latest.tar.gz
Also seen on the regular arch arm RPi1 and RPi2/3 images. The initial install works, but systemd-resolved installs the standard resolved.conf file which enables DNSSEC. If this image is then used on another RPi, it fails to get the time and all DNSSEC requests fail which stops most networking.

**Expected behaviour you didn't see**
 > successful timesyncd on first boot

**Unexpected behaviour you saw**
 > systemd-timesyncd did not run successfully to set the time due to local clock being offset too far from current. All DNSSEC requests then fail. Resolved is set as default to DNSSEC=yes. DNSSEC failures directly relate to no timesync and the local clock being offset from real time.

**Steps to reproduce the problem**
> Create an image and boot it on another RPi. At first boot it cannot resolve any hostnames but can ping/connect to IP addresses just fine.
Resolution (from a booted image that does not have the correct time) is to turn off DNSSEC in /etc/systemd/resolved.conf, restart systemd-resolved, then restart systemd-timesyncd, then reboot. After this you can turn DNSSEC back on and restart systemd-resolved. It seems that as long as you just reboot the RPi, and do not power it off for extended periods, it seems to work fine. 

It seems that this will be a problem for first boot of a system before the RTC is set correctly if the system has an RTC *and* and consistent issues booting of systems without RTCs which a number (most?) SBCs do not have. This has been noted in many places on the web including my comment here:
[https://archlinuxarm.org/forum/viewtopic.php?f=9&t=14443](url)

**Comment by patrolez** [comment] 2020-05-19 01:40
This is somehow related to https://github.com/systemd/systemd/issues/10579 and many another issues already reported :D

**Comment by poettering** [comment] 2020-11-05 10:49
Duplicate of #5873

**Closed as completed by poettering** 2020-11-05 10:49 UTC
Labels: resolve, timesync, duplicate
