### ISSUE TITLE
Configuration of static routes by device

### ISSUE THREAD

**Issue by thehand** [systemd/systemd#3068] opened 2016-04-19 12:11 UTC
### Submission type
- [X] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 225
### Used distribution

> CoreOS alpha (1010.1.0)

Sometimes I need to specify a static route using device and not a simple gateway address.

`route add 123.123.123.123 dev ensX`

To do this, I wrote a script to use in an oneshot service, but it'd be useful to let the admin configure it via standard network unit.

**Comment by einyx** [comment] 2016-04-19 12:18
:+1: on this

**Comment by poettering** [comment] 2016-04-19 15:18
Pretty much a duplicate of #788. Closing this one in favour.

**Closed as completed by poettering** 2016-04-19 15:18 UTC
Labels: RFE 🎁, network, duplicate
