### ISSUE TITLE
unit alive checks

### ISSUE THREAD

**Issue by 13werwolf13** [systemd/systemd#20265] opened 2021-07-21 07:02 UTC
there are many options for a broken service. systemd checks the existence of the process. but there are situations when the process works, but does not provide the necessary functions.
I propose to introduce some kind of AliveChek which, by executing some command, by the result of its execution, will understand whether it is time to restart the service.
P.S.: Yes, the idea was born while reading the documentation for k8s, but it is not useful everywhere.
P.P.S.: sorry for my english

**Comment by 13werwolf13** [comment] 2021-07-21 07:51
probably it is worth clarifying what I know about type=notify
but many proprietary software developers ignore this feature adding their own options.
for example, in my infrastructure there is one service, the operability of which can be found out only by receiving an http response for a certain URL and checking the value inside the json.

**Comment by bluca** [comment] 2021-07-21 11:00
There's already such a feature, WatchdogSec: https://www.freedesktop.org/software/systemd/man/systemd.service.html#WatchdogSec=

**Comment by 13werwolf13** [comment] 2021-07-21 11:15
does it give me the flexibility to choose the way to check the viability of the service. if the program as a whole works but for some reason does not perform the necessary actions.
Above I gave an example in which the check goes on http, even when the program stopped performing a new function, it continued to respond with just another text.
here I mean adding something like this:
```
AliveCheck=curl http://localhost:port/alive | grep state=1
```
or launching another program or utility to check the main one. in proprietary software this occurs.

**Comment by poettering** [comment] 2021-07-29 13:18
Duplicate of #9075

**Closed as completed by poettering** 2021-07-29 13:18 UTC
Labels: pid1, duplicate
