### ISSUE TITLE
Override file on the "Conflict property" created is not applying it correctly.

### ISSUE THREAD

**Issue by Pavithrab7** [systemd/systemd#33437] opened 2024-06-21 09:54 UTC
### systemd version the issue has been seen with

255.4

### CPU architectures issue was seen on

arm

### Expected behaviour you didn't see

I had modified the [unit] Conflicts property in the service overirde file, but the changes where not applied. I had a usecase to remove a conflict present.

### Unexpected behaviour you saw

The conflicts property was not changed based on the override but the override file was picked when I restarted the deamon.

### Steps to reproduce the problem

Write a override file and make changes to Conflicts property in [Unit] section and restart the deamon.
The previous conflicts property had
[Uint]
......
Conflicts=abc.service xyz.service

The override file I wrote

[Uint]
Conflicts=
Conflicts=xyz.service

But the changes were not applied.

**Comment by Pavithrab7** [comment] 2024-06-21 09:54
Is there a different way to override the "Conflict" property?

**Comment by YHNdnzj** [comment] 2024-06-21 09:58
Duplicate of https://github.com/systemd/systemd/issues/18154

**Closed as completed** 2024-06-21 09:58 UTC
Labels: RFE 🎁, pid1, duplicate
