### ISSUE TITLE
systemd-cryptsetup - Failed to deactivate error on shutdown with cryptsetup 2.0

### ISSUE THREAD

**Issue by xabbu** [systemd/systemd#8472] opened 2018-03-16 21:30 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 237.0, 238.0

### Used distribution

> Manjaro  / Arch Linux

### In case of bug report: Expected behaviour you didn't see

clean shutdown of LUKS encrypted devices which are mounted thru `crypttab`. 

### In case of bug report: Unexpected behaviour you saw

When systemd is built with cryptsetup 2.0.2 (also with cryptsetup 2.0 and 2.0.1), on shutdown I see errors like this

```
systemd-cryptsetup[2521]: Failed to deactivate: Device or resource busy
systemd[1]: systemd-cryptsetup@Data.service: Control process exited, code=exited status=1
systemd[1]: systemd-cryptsetup@Data.service: Failed with result 'exit-code'.
systemd[1]: Stopped Cryptography Setup for Data.
```
Usually one for every mounted LUKS device, that I have in my `crypttab`.

The LUKS encrypted device is mounted with an entry in `crypttab`. The Options are "luks,timeout=180". This is not a LUKS2 device. 

When I build systemd with cryptsetup 1.7.5, there are no such errors. 

[A more complete journal excerpt.](https://gist.github.com/xabbu/4b9ab636ed920a4450382f77a3351b94)

### In case of bug report: Steps to reproduce the problem

build systemd with cryptsetup 2.0.2 and use `/etc/crypttab` to mount a luks encrypted device. Shutdown this system and check the journal after the next boot.

**Comment by sierrahotel** [comment] 2018-03-18 09:57
FWIW I'm seeing this issue too with 238.0 and 2.0.2 but haven't tested with previous version combinations (sorry).

**Comment by poettering** [comment] 2018-03-20 08:10
Sounds like an issue with the backend mostly. @mbroz @oniko any idea?

**Comment by oniko** [comment] 2018-03-20 09:28
Off the top of my head, cryptsetup 2.0+ detects if the device is mounted or member of dm device stack. If it's so, it'll fail to deactivate without retrying.

@xabbu what's on top of dm-crypt device that failed to deactivate? If it's a fs, what type? Where is it mounted?

@poettering, @keszybz Any hints on how to debug this in systemd? Because looking at provided log I'm not sure if that's mixed umount and deactivate case...

**Comment by medhefgo** [comment] 2018-03-20 10:18
Looking at the logs, it's clear that the filesystem is only unmounted after cryptsetup service is stopped, not before. Please provide the crypttab lines and the resulting systemd-cryptsetup@ service files.

**Comment by mbroz** [comment] 2018-03-20 14:12
Well, it seems that cryptsetup uncovered dependency problem here by removing old and ugly workaround. 

Libcryptsetup can remove device only when it is not used, IIRC we just removed another retry loop over that inside our library if we detect that device is still mounted.

Systemd should definitely call umount fs first and then LUKS deactivation (it should speed up shutdown as well).

**Comment by medhefgo** [comment] 2018-03-20 15:42
It's the job of fstab generator to create a dependency on the crypto device for the mount unit. Which it afaik always did. Unless something broke that.

**Comment by xabbu** [comment] 2018-03-20 22:47
@oniko, @medhefgo additional files 

/etc/crypttab
```
Multimedia	UUID=4...	/etc/crypt/pass		luks,timeout=180
Data		UUID=5...	/etc/crypt/passdata	luks,timeout=180
```
fstab lines (I don't have a separate home partition.) 
```
/dev/mapper/root / ext4 defaults,discard  0 1
/dev/mapper/Multimedia /home/xabbu/Multimedia ext4 defaults,errors=remount-ro 0 2
/dev/mapper/Data /home/xabbu/Multimedia/Data ext4 defaults,errors=remount-ro 0 2
```
systemd-cryptsetup@ Multimedia.service
```
# /run/systemd/generator/systemd-cryptsetup@Multimedia.service
# Automatically generated by systemd-cryptsetup-generator

[Unit]
Description=Cryptography Setup for %I
Documentation=man:crypttab(5) man:systemd-cryptsetup-generator(8) man:systemd-cryptsetup@.service(8)
SourcePath=/etc/crypttab
DefaultDependencies=no
Conflicts=umount.target
IgnoreOnIsolate=true
After=cryptsetup-pre.target
Before=cryptsetup.target
RequiresMountsFor=/etc/crypt/pass
BindsTo=dev-disk-by\x2duuid-4....device
After=dev-disk-by\x2duuid-4....device
Before=umount.target

[Service]
Type=oneshot
RemainAfterExit=yes
TimeoutSec=0
KeyringMode=shared
ExecStart=/usr/lib/systemd/systemd-cryptsetup attach 'Multimedia' '/dev/disk/by-uuid/4...' '/etc/crypt/pass' 'luks,timeout=180'
ExecStop=/usr/lib/systemd/systemd-cryptsetup detach 'Multimedia'
```
systemd-cryptsetup@ Data.service
```
# /run/systemd/generator/systemd-cryptsetup@Data.service
# Automatically generated by systemd-cryptsetup-generator

[Unit]
Description=Cryptography Setup for %I
Documentation=man:crypttab(5) man:systemd-cryptsetup-generator(8) man:systemd-cryptsetup@.service(8)
SourcePath=/etc/crypttab
DefaultDependencies=no
Conflicts=umount.target
IgnoreOnIsolate=true
After=cryptsetup-pre.target
Before=cryptsetup.target
RequiresMountsFor=/etc/crypt/passdata
BindsTo=dev-disk-by\x2duuid-5....device
After=dev-disk-by\x2duuid-5....device
Before=umount.target

[Service]
Type=oneshot
RemainAfterExit=yes
TimeoutSec=0
KeyringMode=shared
ExecStart=/usr/lib/systemd/systemd-cryptsetup attach 'Data' '/dev/disk/by-uuid/5...' '/etc/crypt/passdata' 'luks,timeout=180'
ExecStop=/usr/lib/systemd/systemd-cryptsetup detach 'Data'
```

home-xabbu-Multimedia.mount 
```
# /run/systemd/generator/home-xabbu-Multimedia.mount
# Automatically generated by systemd-fstab-generator

[Unit]
SourcePath=/etc/fstab
Documentation=man:fstab(5) man:systemd-fstab-generator(8)
Before=local-fs.target
Requires=systemd-fsck@dev-mapper-Multimedia.service
After=systemd-fsck@dev-mapper-Multimedia.service

[Mount]
Where=/home/xabbu/Multimedia
What=/dev/mapper/Multimedia
Type=ext4
Options=defaults,errors=remount-ro
```
home-xabbu-Multimedia-Data.mount
```
# /run/systemd/generator/home-xabbu-Multimedia-Data.mount
# Automatically generated by systemd-fstab-generator

[Unit]
SourcePath=/etc/fstab
Documentation=man:fstab(5) man:systemd-fstab-generator(8)
Before=local-fs.target
Requires=systemd-fsck@dev-mapper-Data.service
After=systemd-fsck@dev-mapper-Data.service

[Mount]
Where=/home/xabbu/Multimedia/Data
What=/dev/mapper/Data
Type=ext4
Options=defaults,errors=remount-ro
```

**Comment by medhefgo** [comment] 2018-03-21 08:51
So the dependencies are: dev-mapper-Data.device < systemd-fsck@Data.service < home-xabbu-Multimedia-Data.mount and a lone systemd-cryptsetup@Data.service, which nothing depends on.

I guess this works for booting because systemd waits for a /dev/mapper/Data to appear. But it doesn't know there's a dependency on the crypto device for the mount unit.

Does adding "x-systemd.requires=systemd-cryptsetup@Data.service" to the fstab options fix this?

**Comment by xabbu** [comment] 2018-03-21 21:39
I changed the `fstab` to this 

```
/dev/mapper/Multimedia /home/xabbu/Multimedia ext4 defaults,errors=remount-ro,x-systemd.requires=systemd-cryptsetup@Multimedia.service 0 2
/dev/mapper/Data /home/xabbu/Multimedia/Data ext4 defaults,errors=remount-ro,x-systemd.requires=systemd-cryptsetup@Data.service 0 2
```

For example the resulting `home-xabbu-Multimedia-Data.mount` looks like this

```
# /run/systemd/generator/home-xabbu-Multimedia-Data.mount
# Automatically generated by systemd-fstab-generator

[Unit]
SourcePath=/etc/fstab
Documentation=man:fstab(5) man:systemd-fstab-generator(8)
Before=local-fs.target
After=systemd-cryptsetup@Data.service
Requires=systemd-cryptsetup@Data.service
Requires=systemd-fsck@dev-mapper-Data.service
After=systemd-fsck@dev-mapper-Data.service

[Mount]
Where=/home/xabbu/Multimedia/Data
What=/dev/mapper/Data
Type=ext4
Options=defaults,errors=remount-ro,x-systemd.requires=systemd-cryptsetup@Data.service
```

After two restarts, the errors are gone. I did it now a couple of times and there isn't a cryptsetup error at  shutdown/reboot. 

So it is possible that systemd adds this requirement to the fs mount automatically?

**Comment by medhefgo** [comment] 2018-03-22 09:36
So, cryptsetup-generator already creates a Requires=systemd-cryptsetup@.service dependency for the /dev/mapper device. But we also need this to be ordered After= so the shutdown case it properly ordered. I tried adding that, but systemd ignores it (.device units cannot be delayed).

Now I am at a loss how to fix this. The ordering *should* be inserted between the systemd-cryptsetup@.service and the /dev/mapper device unit. Adding x-systemd.requires to the fstab is only a band aid. Also, fstab-generator cannot auto-generate that dependency anyway, because /dev/mapper devices could come from other things besides systemd-cryptsetup@.service.

@poeterring Any idea how to fix this ordering?

**Comment by tanskim** [comment] 2018-03-23 11:20
I've also this error on Ubuntu 17.10,  my log : 
```
systemd[1]: Stopped LVM2 metadata daemon.
systemd-cryptsetup[8250]: Failed to deactivate: Device or resource busy
systemd[1]: systemd-cryptsetup@nvme0n1p3_crypt.service: Control process exited, code=exited status=1
systemd[1]: Stopped Cryptography Setup for nvme0n1p3_crypt.
systemd[1]: systemd-cryptsetup@nvme0n1p3_crypt.service: Unit entered failed state.
systemd[1]: systemd-cryptsetup@nvme0n1p3_crypt.service: Failed with result 'exit-code'.
systemd[1]: Reached target Unmount All Filesystems.
systemd[1]: Removed slice system-systemd\x2dcryptsetup.slice.
systemd[1]: Reached target Shutdown.
systemd[1]: Reached target Final Step.
systemd[1]: Starting Reboot...
```
/etc/crypttab:
`nvme0n1p3_crypt UUID=fcc3d85f-187c-4ac0-b054-xxxxxxxxxxxx none luks,discard`

/etc/fstab:
```
/dev/mapper/ubuntu--vg-root /               ext4    errors=remount-ro 0       1
# /boot was on /dev/nvme0n1p2 during installation
UUID=f54abe7b-db17-497b-95fa-xxxxxxxxx /boot           ext4    defaults        0       2
# /boot/efi was on /dev/nvme0n1p1 during installation
UUID=D200-xxxx  /boot/efi       vfat    umask=0077      0       1
/dev/mapper/ubuntu--vg-swap_1 none            swap    sw              0       0

```

**Comment by arvidjaar** [comment] 2018-03-24 19:19
> But we also need this to be ordered `After=` so the shutdown case it properly ordered.

That would be wrong for shutdown; this means stopping of `systemd-cryptsetup@.service` would wait for stopping of corresponding `/dev/mapper` that cannot be stopped.

Actually it would be pretty convincing use case for ordered generators - first run cryptsetup and then fstab generator can decide to put dependency on `systemd-cryptsetup@.service` instead of on device. Or both should be merged together.

May be something like "managed device" could be introduced that would basically forward any job action to corresponding "device handler". Something like `ManagedBy=systemd-cryptsetup@.service` in device unit definition that can be added by generator and effectively makes device unit itself transparent.

P.S. Im pretty sure this problem came up before and more than once.  Cannot find issues now.

**Comment by mesbahamin** [comment] 2018-05-02 05:59
I'm trying to understand how severe this issue is.
Could this cause data corruption on the mounted LUKS devices?

**Comment by medhefgo** [comment] 2018-05-02 08:19
It won't cause corruption. The late shutdown logic takes care of any leftover mounts.

**Comment by joachimneu** [comment] 2018-07-10 11:51
@medhefgo Can you elaborate why this won't cause data corruption/loss? File systems/crypt devices are not shut down/unmounted properly. My default assumption would be that not-sync'ed data is at risk. Isn't this also the (preliminary) bottom line from bug #1620?

**Comment by medhefgo** [comment] 2018-07-10 12:52
This error is in normal shutdown phase. There's a late shutdown phase that takes care of anything left-over. Logs from late shutdown start with a systemd-shutdown prefix.

**Comment by joachimneu** [comment] 2018-07-10 13:13
If I understand correctly, you mean that there should not be a problem, because the late shutdown phase should clean up left-overs of the normal shutdown, right? What about the evidence that file systems are in fact not unmounted properly and thus found dirty at next boot? E.g.,

- https://github.com/systemd/systemd/issues/1620#issuecomment-342311506
- https://github.com/systemd/systemd/issues/1620#issuecomment-342331739

I am trying -- like many others here I suppose -- to get an understanding how severe/risky the problem is and whether I need to deploy a workaround.

**Comment by medhefgo** [comment] 2018-07-10 16:13
It really depends on your setup, I guess. You'll have to check your logs if your fs is dirty or not. You can also just observe the logs with a "systemctl halt" and see if everything is unmounted or not in the end.

**Comment by mbroz** [comment] 2018-11-18 10:47
> Nov 18 00:04:20 holodeck systemd-cryptsetup[25244]: Failed to deactivate: Device or resource busy

Apparently fs (btrfs) is still referencing the device, so libcryptsetup cannot deactivate device that is still in use. Ordering of umount/deactivate  again?

**Comment by tonylambiris** [comment] 2018-11-21 02:21
I don't know if this is related or not, but do you think fstrim may be interfering in some way? I have enabled fstrim.timer but I'm not mounting anything with the discard option.

**Comment by slingamn** [comment] 2019-04-01 13:14
I have this issue on Ubuntu 18.04 (systemd 237), with both my root filesystem (ext4 over LVM over LUKS) and my ZFS pool (ZFS over LUKS). `zpool scrub` hasn't been reporting any errors, but there was one incident where the systemd journal was apparently corrupted.

Could someone clarify the recommended workaround?

**Comment by koroliov** [comment] 2019-07-13 08:05
@medhefgo thank you for suggesting "adding `x-systemd.requires=systemd-cryptsetup@somepart.service`" to the mount options. It did fixed the issue with my home partition. But it did not for the root one. I noticed that for the `systemd-cryptsetup@rootdrive.service` and for `system-systemd\x2dcryptsetup.slice` there is a warning in the `systemctl status *cryptsetup*` output:

   ` WARNING: Locking directory /run/cryptsetup is missing!`

While it's absent for the fixed (home partition) service. And `/run/cryptsetup` was present when I ran `systemctl status`, although empty.

Do you have any idea what the reason of the issue may be, please?

As far as I understand, the home partition is mounted by the `/usr/sbin/cryptsetup` program. But it is on root partition, so it can't be used to mount/umount the root partition itself. So there must be another cryptsetup, which is used by grub2. I tried to `grup2-mkconfig` after setting the `x-systemd.requires` option for the root partition, but that did not help.

**Comment by MaxXor** [comment] 2019-09-10 17:45
Bug still appears with systemd 243 & crytpsetup 2.2.1 and it seems like systemd is trying to close the LUKS device before unmounting the file system. 

```
Sep 10 10:26:43 systemd-cryptsetup[12703]: Device games is still in use.
Sep 10 10:26:43 systemd-cryptsetup[12703]: Failed to deactivate: Device or resource busy
Sep 10 10:26:43 systemd[1]: systemd-cryptsetup@games.service: Control process exited, code=exited, status=1/FAILURE
Sep 10 10:26:43 systemd[1]: systemd-cryptsetup@games.service: Failed with result 'exit-code'.
Sep 10 10:26:43 systemd[1]: Unmounting /mnt/games...
Sep 10 10:26:43 systemd[1]: mnt-games.mount: Succeeded.
Sep 10 10:26:43 systemd[1]: Unmounted /mnt/games.
Sep 10 10:26:43 systemd[1]: systemd-fsck@dev-mapper-games.service: Succeeded.
```

**Comment by fbuihuu** [comment] 2019-12-02 14:32
What about ordering `local-fs-pre.target` after `cryptsetup.target`and `remote-fs-pre.target` after `remote-cryptsetup.target` ?

Does that fix the issue ?

**Closed as completed** 2020-02-04 15:31 UTC
Labels: cryptsetup

**Comment by rebsol** [comment] 2020-09-29 13:44
I have the same issue in Manjaro. Systemd 246 and cryptsetup 2.3.3.

```
systemd-cryptsetup[2428]: Device luks-498829f4-f96d-4bd0-b768-3cfb5b3a8ff6 is still in use.
systemd-cryptsetup[2428]: Failed to deactivate: Device or resource busy
systemd[1]: systemd-cryptsetup@luks\x2d498829f4\x2df96d\x2d4bd0\x2db768\x2d3cfb5b3a8ff6.service: Failed with result 'exit-code'.

```

**Comment by adatum** [comment] 2020-09-29 18:35
I too have had the same issue on every shutdown with Fedora for at least a couple of years. 
Currently on F32, systemd 245.8, cryptsetup 2.3.4.

```
systemd-cryptsetup[2792899]: Device luks-[UUID] is still in use.
systemd-cryptsetup[2792899]: Failed to deactivate: Device or resource busy
systemd[1]: Stopping Security Auditing Service...
systemd[1]: systemd-cryptsetup@luks[...].service: Control process exited, code=exited, status=1/FAILURE
systemd[1]: systemd-cryptsetup@luks[...].service: Failed with result 'exit-code'.
systemd[1]: Stopped Cryptography Setup for luks-[UUID].
```

**Comment by vincentbernat** [comment] 2021-08-01 15:05
I am also still running into this problem. In my case, I have cryptsetup over a partition and puts LVM on top of that. It seems systemd doesn't do the link between the LVM devices and cryptsetup devices. 

```
 17:04 ❱ lsblk
NAME                      MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda                         8:0    0 238.5G  0 disk
├─sda1                      8:1    0   512M  0 part  /boot/efi
├─sda2                      8:2    0   488M  0 part  /boot
└─sda3                      8:3    0 237.5G  0 part
  └─sda3_crypt            254:0    0 237.5G  0 crypt
    ├─chocobo--vg-root    254:1    0  23.3G  0 lvm   /
    ├─chocobo--vg-var     254:2    0   9.3G  0 lvm   /var
    ├─chocobo--vg-swap_1  254:3    0   976M  0 lvm   [SWAP]
    ├─chocobo--vg-tmp     254:4    0   1.9G  0 lvm   /tmp
    ├─chocobo--vg-home    254:5    0  93.1G  0 lvm   /home
    └─chocobo--vg-systems 254:6    0    20G  0 lvm   /var/lib/systems
```

**Comment by Frederick888** [comment] 2022-01-01 18:05
I'm using both LVM on LUKS and ZFS on LUKS so I've got the whole deal (unfortunately), and here are my workarounds.

## LVM on LUKS

I'm using LVM to concatenate 2 old hard drives, `crypthdd2000` and `crypthdd500`, for local caching purposes.

```
$ lsblk -o NAME,FSTYPE,MOUNTPOINT
NAME                                     FSTYPE      MOUNTPOINT
sda                                      crypto_LUKS
└─crypthdd2000                           LVM2_member
  └─VolGroupFoo-temp                 ext4        /mnt/Foo
sdb                                      crypto_LUKS
└─crypthdd500                            LVM2_member
  └─VolGroupFoo-temp                 ext4        /mnt/Foo
```

First of all `/etc/crypttab`, nothing special here except that I've enabled `noauto`

```
crypthdd500     UUID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       /path/to/key       luks,noauto,x-systemd.device-timeout=30s
crypthdd2000    UUID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       /path/to/key       luks,noauto,x-systemd.device-timeout=30s
```

Then create an intermediate service `/etc/systemd/system/lvm-on-luks.service`

```systemd
[Unit]
Description=LVM on LUKS dependency service
Requires=systemd-cryptsetup@crypthdd2000.service
After=systemd-cryptsetup@crypthdd2000.service
Requires=systemd-cryptsetup@crypthdd500.service
After=systemd-cryptsetup@crypthdd500.service

[Service]
Type=oneshot
RemainAfterExit=yes
TimeoutSec=30s
ExecStart=/usr/bin/true
ExecStop=/usr/bin/lvm vgchange -an --nohints VolGroupFoo
```

Note you want only volume groups that are *activated after boot* here. So if you've got more than one VG, add more `ExecStop=`s. Do NOT use `vgchange -an` without VG here.

Finally in `/etc/fstab`

```fstab
# Not all of these are required I guess, but I didn't bother to check
#
# nofail
# noauto
# x-systemd.automount
# x-systemd.device-timeout=2m
# x-systemd.requires=/dev/mapper/crypthdd500
# x-systemd.requires=/dev/mapper/crypthdd2000
# x-systemd.after=/dev/mapper/crypthdd500
# x-systemd.after=/dev/mapper/crypthdd2000
# x-systemd.requires=systemd-cryptsetup@crypthdd500.service
# x-systemd.after=systemd-cryptsetup@crypthdd500.service
# x-systemd.requires=systemd-cryptsetup@crypthdd2000.service
# x-systemd.after=systemd-cryptsetup@crypthdd2000.service
# x-systemd.requires=/dev/mapper/VolGroupFoo-temp
# x-systemd.after=/dev/mapper/VolGroupFoo-temp
# x-systemd.requires=lvm-on-luks.service
# x-systemd.after=lvm-on-luks.service
/dev/VolGroupFoo/temp                       /mnt/Foo            ext4    defaults,noatime,nofail,noauto,x-systemd.automount,x-systemd.device-timeout=2m,x-systemd.requires=/dev/mapper/crypthdd500,x-systemd.requires=/dev/mapper/crypthdd2000,x-systemd.after=/dev/mapper/crypthdd500,x-systemd.after=/dev/mapper/crypthdd2000,x-systemd.requires=systemd-cryptsetup@crypthdd500.service,x-systemd.after=systemd-cryptsetup@crypthdd500.service,x-systemd.requires=systemd-cryptsetup@crypthdd2000.service,x-systemd.after=systemd-cryptsetup@crypthdd2000.service,x-systemd.requires=/dev/mapper/VolGroupFoo-temp,x-systemd.after=/dev/mapper/VolGroupFoo-temp,x-systemd.requires=lvm-on-luks.service,x-systemd.after=lvm-on-luks.service      0 0
```

## ZFS on LUKS

I'm using `zfs-import-cache.service` and `zfs-zed.service` to leverage zfs-mount-generator. IIUC it doesn't support automount so it's somewaht simpler here.

If you use `zfs-import-scan.service` and/or `zfs-mount.service`, the workaround can be a tad different but overall it should be the same idea.

First of all make a copy of `/etc/zfs/zpool.cache`:
```sh
cp /etc/zfs/zpool.cache /etc/zfs/zpool.cache.bak
```

Then run `systemctl edit zfs-import-cache.service`, put the following snippet in it:

```systemd
[Unit]
Requires=systemd-cryptsetup@<disk id>.service
After=systemd-cryptsetup@<disk id>.service
ConditionFileNotEmpty=
ConditionFileNotEmpty=/etc/zfs/zpool.cache.bak

[Service]
TimeoutSec=60s
# to be safe, I've also got zfs in /etc/modules-load.d
ExecStartPre=/usr/bin/modprobe zfs
# `zpool export` clears out /etc/zfs/zpool.cache so we copy our backup back here
ExecStartPre=/usr/bin/cp /etc/zfs/zpool.cache.bak /etc/zfs/zpool.cache
# during shutdown, export the pool
ExecStop=/usr/bin/zpool export tank
```

## If you're using LVM/ZFS on LUKS as root

...then unless you're using systemd hooks then it's probably not systemd's issue, nor can they be solved by workarounds above.

You need to modify your initramfs hooks to solve this, e.g. I had issue with ZFS on LUKS as root in Arch Linux during shutdown, solution was https://bugs.archlinux.org/task/63697#comment195763

**Comment by dhlavac** [comment] 2022-01-18 11:47
Having the same issue on F34, systemd 248 (v248.9-1.fc34),   cryptsetup 2.3.6 with encrypted  BTRFS partition

**Comment by xioren** [comment] 2022-02-01 19:09
Have this issue on a brand new install of Debian Testing.

systemd 250 (250.3-1)
cryptsetup 2:2.4.3-1

log:
```
Feb 01 10:06:14 xioren-pc systemd-cryptsetup[67963]: Device sda3_crypt is still in use.
Feb 01 10:06:14 xioren-pc systemd-cryptsetup[67963]: Failed to deactivate: Device or resource busy
Feb 01 10:06:14 xioren-pc systemd[1]: systemd-cryptsetup@sda3_crypt.service: Control process exited, code=exited, >
Feb 01 10:06:14 xioren-pc systemd[1]: systemd-cryptsetup@sda3_crypt.service: Failed with result 'exit-code'.
```

**Comment by lockie** [comment] 2022-10-24 07:13
Still having this issue in Manjaro 21.3.1 with encrypted ext4 filesystem. @keszybz please reopen, the issue is not resolved.

**Comment by 10101010101010001** [comment] 2023-02-02 21:33
Thanks @Frederick888 

I had to correct two paths for it to work on Ubuntu 22.04, zfs on luks

`[Unit]
Requires=systemd-cryptsetup@<disk id>.service
After=systemd-cryptsetup@<disk id>.service
ConditionFileNotEmpty=
ConditionFileNotEmpty=/etc/zfs/zpool.cache.bak

[Service]
TimeoutSec=60s
# to be safe, I've also got zfs in /etc/modules-load.d
ExecStartPre=/usr/sbin/modprobe zfs
# `zpool export` clears out /etc/zfs/zpool.cache so we copy our backup back here
ExecStartPre=/usr/bin/cp /etc/zfs/zpool.cache.bak /etc/zfs/zpool.cache
# during shutdown, export the pool
ExecStop=/usr/sbin/zpool export dpool`

**Comment by keszybz** [comment] 2023-02-11 13:50
Please open a new issue. This issue is 5 years old and it's unlikely to be the exact same cause.

**Comment by lockie** [comment] 2023-02-11 16:02
@keszybz As you clearly can see above, I did, only to get a snide response from the great mr. Poettering himself.
