### ISSUE TITLE
eno1: Failed to rename network interface 7 from 'eth0' to 'eno1': File exists

### ISSUE THREAD

**Issue by aotto1968** [systemd/systemd#24102] opened 2022-07-25 06:17 UTC
### systemd version the issue has been seen with

251.2

### Used distribution

openSUSE Tumbleweed

### Linux kernel version used

5.18.9-1-default

### CPU architectures issue was seen on

x86_64

### Component

networkctl

### Expected behaviour you didn't see

both network cards should be visible

### Unexpected behaviour you saw

after boot one of my card is missing → ~ 50% chance that current card is missing after boot

### Steps to reproduce the problem

just reboot and see → this issue started probably 3 months ago →it is annoying because after boot I have to switch the physical network cable from one port to the other port to get it working back.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
2022-07-25T07:58:39.621962+02:00 linux02 kernel: [ 1465.121238][ T8589] e1000e: Intel(R) PRO/1000 Network Driver
2022-07-25T07:58:39.621974+02:00 linux02 kernel: [ 1465.121241][ T8589] e1000e: Copyright(c) 1999 - 2015 Intel Corporation.
2022-07-25T07:58:39.621976+02:00 linux02 kernel: [ 1465.121417][ T8589] e1000e 0000:00:19.0: Interrupt Throttling Rate (ints/sec) set to dynamic conservative mode
2022-07-25T07:58:39.729972+02:00 linux02 kernel: [ 1465.229947][ T8589] e1000e 0000:00:19.0 0000:00:19.0 (uninitialized): registered PHC clock
2022-07-25T07:58:39.833999+02:00 linux02 kernel: [ 1465.331573][ T8589] e1000e 0000:00:19.0 eth0: (PCI Express:2.5GT/s:Width x1) 00:1e:67:77:fd:75
2022-07-25T07:58:39.834025+02:00 linux02 kernel: [ 1465.331582][ T8589] e1000e 0000:00:19.0 eth0: Intel(R) PRO/1000 Network Connection
2022-07-25T07:58:39.834028+02:00 linux02 kernel: [ 1465.331698][ T8589] e1000e 0000:00:19.0 eth0: MAC: 10, PHY: 11, PBA No: 0100FF-0FF
2022-07-25T07:58:39.834029+02:00 linux02 kernel: [ 1465.332011][ T8589] e1000e 0000:03:00.0: Interrupt Throttling Rate (ints/sec) set to dynamic conservative mode
2022-07-25T07:58:39.834030+02:00 linux02 kernel: [ 1465.333330][ T8590] e1000e 0000:00:19.0 eno1: renamed from eth0
2022-07-25T07:58:39.885968+02:00 linux02 kernel: [ 1465.385715][ T8589] e1000e 0000:03:00.0 0000:03:00.0 (uninitialized): registered PHC clock
2022-07-25T07:58:39.936654+02:00 linux02 sudo: pam_unix(sudo:session): session closed for user root
2022-07-25T07:58:39.937470+02:00 linux02 systemd-udevd[8590]: eno1: Failed to rename network interface 7 from 'eth0' to 'eno1': File exists
2022-07-25T07:58:39.937648+02:00 linux02 systemd-udevd[8590]: eno1: Failed to process device, ignoring: File exists
2022-07-25T07:58:39.937964+02:00 linux02 kernel: [ 1465.437050][ T8589] e1000e 0000:03:00.0 eth0: (PCI Express:2.5GT/s:Width x1) 00:1e:67:77:fd:74
2022-07-25T07:58:39.937973+02:00 linux02 kernel: [ 1465.437057][ T8589] e1000e 0000:03:00.0 eth0: Intel(R) PRO/1000 Network Connection
2022-07-25T07:58:39.937975+02:00 linux02 kernel: [ 1465.437144][ T8589] e1000e 0000:03:00.0 eth0: MAC: 3, PHY: 8, PBA No: 1000FF-0FF
2022-07-25T07:58:40.813983+02:00 linux02 kernel: [ 1466.311738][ T1165] br0: port 1(eno1) entered blocking state
2022-07-25T07:58:40.814006+02:00 linux02 kernel: [ 1466.311746][ T1165] br0: port 1(eno1) entered disabled state
2022-07-25T07:58:40.814009+02:00 linux02 kernel: [ 1466.311848][ T1165] device eno1 entered promiscuous mode
2022-07-25T07:58:42.378133+02:00 linux02 ModemManager[1101]: <info>  [base-manager] couldn't check support for device '/sys/devices/pci0000:00/0000:00:19.0': not supported by any plugin
2022-07-25T07:58:42.393983+02:00 linux02 kernel: [ 1467.893477][ T8512] e1000e 0000:00:19.0 eno1: NIC Link is Up 100 Mbps Full Duplex, Flow Control: Rx/Tx
2022-07-25T07:58:42.394012+02:00 linux02 kernel: [ 1467.893488][ T8512] e1000e 0000:00:19.0 eno1: 10/100 speed: disabling TSO
2022-07-25T07:58:42.394014+02:00 linux02 kernel: [ 1467.893548][ T8512] br0: port 1(eno1) entered blocking state
2022-07-25T07:58:42.394014+02:00 linux02 kernel: [ 1467.893552][ T8512] br0: port 1(eno1) entered forwarding state
2022-07-25T07:58:42.399332+02:00 linux02 wickedd-dhcp4[1156]: br0: Request to acquire DHCPv4 lease with UUID 5c2bde62-db9f-0c00-8d04-00000e000000
2022-07-25T07:58:42.400101+02:00 linux02 wickedd-dhcp6[1157]: br0: Request to acquire DHCPv6 lease with UUID 5c2bde62-db9f-0c00-8d04-00000f000000 in mode auto
2022-07-25T07:58:42.438055+02:00 linux02 ModemManager[1101]: <info>  [base-manager] couldn't check support for device '/sys/devices/pci0000:00/0000:00:1c.4/0000:03:00.0': not supported by any plugin
2022-07-25T07:58:43.896552+02:00 linux02 sudo:  dev1usr : TTY=pts/1 ; PWD=/home/dev1usr ; USER=root ; COMMAND=/usr/sbin/ifstatus all
2022-07-25T07:58:43.899861+02:00 linux02 sudo: pam_unix(sudo:session): session opened for user root(uid=0) by dev1usr(uid=1000)
2022-07-25T07:58:43.940719+02:00 linux02 sudo: pam_unix(sudo:session): session closed for user root
2022-07-25T07:58:46.906964+02:00 linux02 wickedd-dhcp4[1156]: Discarded suspect dns-domain: 'Speedport_W723_V_Typ_A_1_01_018'
2022-07-25T07:58:46.926102+02:00 linux02 wickedd-dhcp4[1156]: br0: Committed DHCPv4 lease with address 192.168.2.100 (lease time 1814400 sec, renew in 907200 sec, rebind in 1587600 sec)
2022-07-25T07:58:47.042681+02:00 linux02 wickedd[1165]: route ipv4 0.0.0.0/0 via 192.168.2.1 dev br0#5 type unicast table main scope universe protocol dhcp covered by a ipv4:dhcp lease
2022-07-25T08:00:01.439088+02:00 linux02 CRON[9260]: (root) CMD (run-parts /etc/cron.hourly)
2022-07-25T08:00:01.442703+02:00 linux02 CRON[9259]: (root) CMDEND (run-parts /etc/cron.hourly)
2022-07-25T08:00:16.092591+02:00 linux02 sudo:  dev1usr : TTY=pts/1 ; PWD=/home/dev1usr ; USER=root ; COMMAND=/usr/bin/less /var/log/messages
2022-07-25T08:00:16.095875+02:00 linux02 sudo: pam_unix(sudo:session): session opened for user root(uid=0) by dev1usr(uid=1000)
dev1usr@linux02:~> sudo udevadm info /sys/class/net/eth0
P: /devices/pci0000:00/0000:00:1c.4/0000:03:00.0/net/eth0
M: eth0
R: 0
U: net
I: 7
E: DEVPATH=/devices/pci0000:00/0000:00:1c.4/0000:03:00.0/net/eth0
E: SUBSYSTEM=net
E: INTERFACE=eth0
E: IFINDEX=7
E: ID_RENAMING=1

dev1usr@linux02:~> sudo udevadm info /sys/class/net/eno1
P: /devices/pci0000:00/0000:00:19.0/net/eno1
M: eno1
R: 1
U: net
I: 6
E: DEVPATH=/devices/pci0000:00/0000:00:19.0/net/eno1
E: SUBSYSTEM=net
E: INTERFACE=eno1
E: IFINDEX=6
E: USEC_INITIALIZED=1465766944
E: ID_NET_NAMING_SCHEME=v251
E: ID_NET_NAME_MAC=enx001e6777fd75
E: ID_OUI_FROM_DATABASE=Intel Corporate
E: ID_NET_NAME_ONBOARD=eno1
E: ID_NET_LABEL_ONBOARD=Intel 82579LM VPRO
E: ID_NET_NAME_PATH=enp0s25
E: ID_BUS=pci
E: ID_VENDOR_ID=0x8086
E: ID_MODEL_ID=0x1502
E: ID_PCI_CLASS_FROM_DATABASE=Network controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=Ethernet controller
E: ID_VENDOR_FROM_DATABASE=Intel Corporation
E: ID_MODEL_FROM_DATABASE=82579LM Gigabit Network Connection (Lewisville) (Server Board S1200BTLR)
E: ID_MM_CANDIDATE=1
E: ID_PATH=pci-0000:00:19.0
E: ID_PATH_TAG=pci-0000_00_19_0
E: ID_NET_DRIVER=e1000e
E: ID_NET_LINK_FILE=/usr/lib/systemd/network/99-default.link
E: ID_NET_NAME=eno1
E: SYSTEMD_ALIAS=/sys/subsystem/net/devices/eno1
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:
```

**Comment by aotto1968** [comment] 2022-07-25 06:21
additional information: I use a bridge to connect both network devices

```
P: /devices/virtual/net/br0
M: br0
R: 0
U: net
T: bridge
I: 5
E: DEVPATH=/devices/virtual/net/br0
E: SUBSYSTEM=net
E: DEVTYPE=bridge
E: INTERFACE=br0
E: IFINDEX=5
E: USEC_INITIALIZED=503010988
E: ID_NET_NAMING_SCHEME=v251
E: ID_MM_CANDIDATE=1
E: ID_NET_DRIVER=bridge
E: ID_NET_LINK_FILE=/usr/lib/systemd/network/99-default.link
E: ID_NET_NAME=br0
E: SYSTEMD_ALIAS=/sys/subsystem/net/devices/br0
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:
```

```
dev1usr@linux02:~> sudo udevadm info /sys/class/net/lo
P: /devices/virtual/net/lo
M: lo
U: net
I: 1
E: DEVPATH=/devices/virtual/net/lo
E: SUBSYSTEM=net
E: INTERFACE=lo
E: IFINDEX=1
E: USEC_INITIALIZED=4170352
E: ID_MM_CANDIDATE=1
```

**Comment by poettering** [comment] 2022-07-25 08:01
This suggests that your firmware reports the same index for both devices. i.e. the `acpi_index` and `index` sysfs attributes of your device. These are the ACPI _DSM and SMBIOS type 41 objects.

Can you check in sysfs what these sysfs attributes report for you?

**Comment by aotto1968** [comment] 2022-07-26 05:54
can you give me the exact command to extract the output you wanted?

**Comment by yuwata** [comment] 2022-07-26 06:33
>     * today: **eno1** and **eth1**
> 
>     * yesterday:  **eno1** and **eth0**

There is nothing strange in that. There is no persistent ordering about detecting network interfaces. Hence, if you have multiple network interfaces, an interface is sometimes detected as eth0, but sometimes eth1.

Let's go back to the original issue. A workaround for the issue is creating a .link file something like the following:
```
# /etc/systemd/network/90-workaround.link
[Match]
Type=ether

[Link]
NamePolicy=keep kernel database slot path
AlternativeNamesPolicy=database slot path
MACAddressPolicy=persistent
```

**Comment by yuwata** [comment] 2022-07-26 17:20
BTW, this sounds duplicate of #13788.

**Comment by aotto1968** [comment] 2022-07-26 21:58
done
```
> cat /etc/systemd/network/90-workaround.link
[Match]
Type=ether

[Link]
NamePolicy=keep kernel database slot path
AlternativeNamesPolicy=database slot path
MACAddressPolicy=persistent
```

**Comment by aotto1968** [comment] 2022-07-27 06:29
1. Today after boot all network was down.
2. The problem was the *bridge* **br0**, because the *network-device-names* have changed and the *bridge* (at least on opensuse) require a **constant** name !!!
3. after update **br0** and `ifup all` the network was up.

> I hope that the *nework-device-names* are **constant** 
> I really not know what the **renaming** stuff is good for → but the **renaming** add a lot of bugs !!

```
> sudo journalctl -b | grep e1000e
Jul 27 07:50:06 linux02 kernel: e1000e: Intel(R) PRO/1000 Network Driver
Jul 27 07:50:06 linux02 kernel: e1000e: Copyright(c) 1999 - 2015 Intel Corporation.
Jul 27 07:50:06 linux02 kernel: e1000e 0000:00:19.0: Interrupt Throttling Rate (ints/sec) set to dynamic conservative mode
Jul 27 07:50:06 linux02 kernel: e1000e 0000:00:19.0 0000:00:19.0 (uninitialized): registered PHC clock
Jul 27 07:50:06 linux02 kernel: e1000e 0000:00:19.0 eth0: (PCI Express:2.5GT/s:Width x1) 00:1e:67:77:fd:75
Jul 27 07:50:06 linux02 kernel: e1000e 0000:00:19.0 eth0: Intel(R) PRO/1000 Network Connection
Jul 27 07:50:06 linux02 kernel: e1000e 0000:00:19.0 eth0: MAC: 10, PHY: 11, PBA No: 0100FF-0FF
Jul 27 07:50:06 linux02 kernel: e1000e 0000:03:00.0: Interrupt Throttling Rate (ints/sec) set to dynamic conservative mode
Jul 27 07:50:07 linux02 kernel: e1000e 0000:03:00.0 0000:03:00.0 (uninitialized): registered PHC clock
Jul 27 07:50:07 linux02 kernel: e1000e 0000:03:00.0 eth1: (PCI Express:2.5GT/s:Width x1) 00:1e:67:77:fd:74
Jul 27 07:50:07 linux02 kernel: e1000e 0000:03:00.0 eth1: Intel(R) PRO/1000 Network Connection
Jul 27 07:50:07 linux02 kernel: e1000e 0000:03:00.0 eth1: MAC: 3, PHY: 8, PBA No: 1000FF-0FF
Jul 27 07:50:07 linux02 kernel: e1000e 0000:00:19.0 enp0s25: renamed from eth0
Jul 27 07:50:07 linux02 kernel: e1000e 0000:03:00.0 enp3s0: renamed from eth1

> sudo journalctl -b | grep wicked
Jul 27 07:50:06 linux02 udevadm[564]: systemd-udev-settle.service is deprecated. Please fix wickedd.service not to pull it in.
Jul 27 07:50:08 linux02 systemd[1]: Starting wicked AutoIPv4 supplicant service...
Jul 27 07:50:08 linux02 systemd[1]: Starting wicked DHCPv4 supplicant service...
Jul 27 07:50:08 linux02 systemd[1]: Starting wicked DHCPv6 supplicant service...
Jul 27 07:50:08 linux02 systemd[1]: Started wicked DHCPv6 supplicant service.
Jul 27 07:50:08 linux02 systemd[1]: Started wicked DHCPv4 supplicant service.
Jul 27 07:50:08 linux02 systemd[1]: Started wicked AutoIPv4 supplicant service.
Jul 27 07:50:08 linux02 systemd[1]: Starting wicked network management service daemon...
Jul 27 07:50:08 linux02 systemd[1]: Started wicked network management service daemon.
Jul 27 07:50:08 linux02 systemd[1]: Starting wicked network nanny service...
Jul 27 07:50:08 linux02 systemd[1]: Started wicked network nanny service.
Jul 27 07:50:08 linux02 systemd[1]: Starting wicked managed network interfaces...
Jul 27 07:50:39 linux02 wicked[1257]: lo              up
Jul 27 07:50:39 linux02 wicked[1257]: eth0            no-device
Jul 27 07:50:39 linux02 wicked[1257]: eno1            no-device
Jul 27 07:50:39 linux02 wicked[1257]: br0             no-device
Jul 27 07:50:39 linux02 systemd[1]: Finished wicked managed network interfaces.

> sudo ifstatus all
lo              up
      link:     #1, state up
      type:     loopback
      config:   compat:suse:/etc/sysconfig/network/ifcfg-lo
      leases:   ipv4 static granted
      leases:   ipv6 static granted
      addr:     ipv4 127.0.0.1/8 [static]
      addr:     ipv6 ::1/128 [static]

enp0s25         device-unconfigured
      link:     #2, state down, mtu 1500
      type:     ethernet, hwaddr 00:1e:67:77:fd:75

enp3s0          device-unconfigured
      link:     #3, state down, mtu 1500
      type:     ethernet, hwaddr 00:1e:67:77:fd:74

eth0            no-device

eno1            no-device

br0             no-device

> sudo ifstatus all
lo              up
      link:     #1, state up
      type:     loopback
      config:   compat:suse:/etc/sysconfig/network/ifcfg-lo
      leases:   ipv4 static granted
      leases:   ipv6 static granted
      addr:     ipv4 127.0.0.1/8 [static]
      addr:     ipv6 ::1/128 [static]

enp0s25         device-unconfigured
      link:     #2, state down, mtu 1500
      type:     ethernet, hwaddr 00:1e:67:77:fd:75

enp3s0          device-unconfigured
      link:     #3, state down, mtu 1500
      type:     ethernet, hwaddr 00:1e:67:77:fd:74

eth0            no-device

eno1            no-device

br0             no-device

> sudo ifstatus all
lo              up
      link:     #1, state up
      type:     loopback
      config:   compat:suse:/etc/sysconfig/network/ifcfg-lo
      leases:   ipv4 static granted
      leases:   ipv6 static granted
      addr:     ipv4 127.0.0.1/8 [static]
      addr:     ipv6 ::1/128 [static]

enp0s25         enslaved
      link:     #2, state up, mtu 1500, master br0
      type:     ethernet, hwaddr 00:1e:67:77:fd:75
      config:   compat:suse:/etc/sysconfig/network/ifcfg-enp0s25

enp3s0          enslaved
      link:     #3, state device-up, mtu 1500, master br0
      type:     ethernet, hwaddr 00:1e:67:77:fd:74
      config:   compat:suse:/etc/sysconfig/network/ifcfg-enp3s0

br0             device-not-running
      link:     #4, state down, mtu 1500
      type:     bridge, hwaddr f6:65:1a:a6:5b:f4
      config:   compat:suse:/etc/sysconfig/network/ifcfg-br0

> sudo ifup all
lo              up
enp0s25         enslaved
enp3s0          enslaved
br0             up

> sudo ifstatus all
lo              up
      link:     #1, state up
      type:     loopback
      config:   compat:suse:/etc/sysconfig/network/ifcfg-lo
      leases:   ipv4 static granted
      leases:   ipv6 static granted
      addr:     ipv4 127.0.0.1/8 [static]
      addr:     ipv6 ::1/128 [static]

enp0s25         enslaved
      link:     #2, state up, mtu 1500, master br0
      type:     ethernet, hwaddr 00:1e:67:77:fd:75
      config:   compat:suse:/etc/sysconfig/network/ifcfg-enp0s25

enp3s0          enslaved
      link:     #3, state device-up, mtu 1500, master br0
      type:     ethernet, hwaddr 00:1e:67:77:fd:74
      config:   compat:suse:/etc/sysconfig/network/ifcfg-enp3s0

br0             up
      link:     #4, state up, mtu 1500
      type:     bridge, hwaddr f6:65:1a:a6:5b:f4
      config:   compat:suse:/etc/sysconfig/network/ifcfg-br0
      leases:   ipv4 dhcp granted
      leases:   ipv6 dhcp granted, ipv6 auto granted
      addr:     ipv4 xxxxxxxxxxxxxxxx [dhcp]
      addr:     ipv6 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx [auto]
      addr:     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx [auto]
      route:    ipv4 default via xxxxxxxxxxx proto dhcp
      route:    ipv6 default via xxxxxxx metric 1024 proto ra
```

**Comment by yuwata** [comment] 2022-07-30 04:05
When you introduce the .link file as a workaround, then of course you need to change names in the configs wicked or other daemon or tools.

Anyway, there is nothing we can do for the broken firmware. Please also see the discussion in #13788. Closing.

**Closed as completed by yuwata** 2022-07-30 04:05 UTC
Labels: udev, network, needs-reporter-feedback ❓, duplicate, predictable-ifnames
