### ISSUE TITLE
BlockIOWeight / IOWeight have no effect with BFQ

### ISSUE THREAD

**Issue by jwwalton** [systemd/systemd#7057] opened 2017-10-11 01:51 UTC
```
root@foobar / # systemd-run --unit broken345  -p BlockIOWeight=333 sleep 600
Running as unit: broken345.service
root@foobar / # cat /sys/fs/cgroup/blkio/system.slice/broken345.service/blkio.bfq.weight
100
root@foobar / # systemd-run --unit broken567  -p IOWeight=333 sleep 601
Running as unit: broken567.service
root@foobar / # cat /sys/fs/cgroup/blkio/system.slice/broken567.service/blkio.bfq.weight
100
```

```
# find /sys/fs/cgroup/blkio -maxdepth 1
/sys/fs/cgroup/blkio
/sys/fs/cgroup/blkio/blkio.bfq.io_wait_time
/sys/fs/cgroup/blkio/blkio.bfq.empty_time
/sys/fs/cgroup/blkio/machine.slice
/sys/fs/cgroup/blkio/blkio.bfq.time
/sys/fs/cgroup/blkio/blkio.bfq.idle_time
/sys/fs/cgroup/blkio/cgroup.clone_children
/sys/fs/cgroup/blkio/release_agent
/sys/fs/cgroup/blkio/blkio.bfq.io_service_time_recursive
/sys/fs/cgroup/blkio/blkio.bfq.sectors
/sys/fs/cgroup/blkio/blkio.bfq.io_queued
/sys/fs/cgroup/blkio/blkio.bfq.io_service_time
/sys/fs/cgroup/blkio/blkio.bfq.io_merged
/sys/fs/cgroup/blkio/blkio.bfq.io_serviced_recursive
/sys/fs/cgroup/blkio/user.slice
/sys/fs/cgroup/blkio/blkio.bfq.group_wait_time
/sys/fs/cgroup/blkio/blkio.bfq.io_queued_recursive
/sys/fs/cgroup/blkio/blkio.bfq.io_service_bytes_recursive
/sys/fs/cgroup/blkio/blkio.bfq.io_serviced
/sys/fs/cgroup/blkio/tasks
/sys/fs/cgroup/blkio/blkio.bfq.dequeue
/sys/fs/cgroup/blkio/notify_on_release
/sys/fs/cgroup/blkio/init.scope
/sys/fs/cgroup/blkio/blkio.reset_stats
/sys/fs/cgroup/blkio/blkio.bfq.io_merged_recursive
/sys/fs/cgroup/blkio/blkio.bfq.io_service_bytes
/sys/fs/cgroup/blkio/cgroup.procs
/sys/fs/cgroup/blkio/blkio.bfq.time_recursive
/sys/fs/cgroup/blkio/blkio.bfq.avg_queue_size
/sys/fs/cgroup/blkio/blkio.bfq.io_wait_time_recursive
/sys/fs/cgroup/blkio/system.slice
/sys/fs/cgroup/blkio/blkio.bfq.sectors_recursive
/sys/fs/cgroup/blkio/cgroup.sane_behavior

# find /sys/fs/cgroup/blkio/system.slice -maxdepth 1 -type f
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.io_wait_time
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.empty_time
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.time
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.idle_time
/sys/fs/cgroup/blkio/system.slice/cgroup.clone_children
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.io_service_time_recursive
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.sectors
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.io_queued
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.io_service_time
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.io_merged
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.io_serviced_recursive
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.weight
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.group_wait_time
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.io_queued_recursive
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.io_service_bytes_recursive
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.io_serviced
/sys/fs/cgroup/blkio/system.slice/tasks
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.dequeue
/sys/fs/cgroup/blkio/system.slice/notify_on_release
/sys/fs/cgroup/blkio/system.slice/blkio.reset_stats
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.io_merged_recursive
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.io_service_bytes
/sys/fs/cgroup/blkio/system.slice/cgroup.procs
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.time_recursive
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.avg_queue_size
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.io_wait_time_recursive
/sys/fs/cgroup/blkio/system.slice/blkio.bfq.sectors_recursive

```

**Comment by poettering** [comment] 2017-10-11 10:46
bfq doesn't support IO weights IIRC. Hence, what did you expect? we can only expose what the kernel provides, and if it doesn't support this we can't either...

Sorry

**Comment by poettering** [comment] 2017-10-11 13:45
Hmm, so why doesn't bfq use the same weight cgroup attributes?

I have the suspicion this is fixed in cgroupfs2 anyway, so I am not sure we should add new legacy supporting code for this here now.

**Comment by paolo-github** [comment] 2017-10-19 08:48
bfq does use weights; actually, part of the blkio/io infrastructure is code taken from bfq hierarchical support. Simply, I have added an extra .bfq in the middle of the names of bfq cgroups parameters, to distinguish bfq parameters from cfq ones. Full details in bfq documentation:
https://github.com/torvalds/linux/blob/master/Documentation/block/bfq-iosched.txt

Any other sensible solution is ok for me.

**Comment by poettering** [comment] 2017-10-23 18:28
hmm, so what's the long-term strategy here? why can't bfq and cfq and everything else use and expose the same weight context? and if this is all different on cgroupsv1, can't this be streamlined on cgroupsv2 at least?

I'd really prefer not having to teach systemd the differences between the various schedulers.

@htejun any chance you can comment on this?

**Comment by paolo-github** [comment] 2017-10-24 04:04
> Il giorno 23 ott 2017, alle ore 20:28, Lennart Poettering <notifications@github.com> ha scritto:
> 
> hmm, so what's the long-term strategy here? why can't bfq and cfq and everything else use and expose the same weight context? and if this is all different on cgroupsv1, can't this be streamlined on cgroupsv2 at least?
> 
> I'd really prefer not having to teach systemd the differences between the various schedulers.
> 

I do agree that this API difference between cfq and bfq is a mess.
The main reason I resorted to using different cgroups names for bfq is
that, in the current implementation of both cgroups-v1 and cgroups-v2:
- for both cgroups-v1 and cgrups-v2, a scheduler creates its set of
files when it is registered (whether or not the scheduler then happens
to be used)
- so cfq creates files like blkio.weight when it is registered
- then this name is taken (as well as all other names created by cfq),
and cannot be re-used by bfq

And both cfq and bfq may happen to be registered, because in the same
system there may be both devices that still use legacy blk, and thus cfq,
and devices that use blk-mq, and thus bfq.

A structural cgroups change is needed, in the I/O-controller part, to
extend the above scheme so that a same special file may act as an
interface for more than one I/O schedulers.  In particular, that file
should be, at any time, the interface for the I/O scheduler currently
in use for that group at that time.  I guess that an extra difficulty
for implementing such an extension is that a group may contain
processes doing I/O for different devices, and thus scheduled by
different I/O schedulers.  But I guess Tejun (in CC) may clarify this
point better.

In any case, Lennart, if you want, I'm willing to bring this issue to
the attention of the linux-block community, continue the discussion
from there, and contribute to implement possible solutions to this
problems.

Thanks,
Paolo

**Comment by htejun** [comment] 2017-10-24 15:09
@paolo-github, yeah, let's make both use the same file. This is a bit too messy. We can move the the weight settings to blkg, which is partially going back to what we used to have. As long as we make sure that we disallow / clear setting when neither bfq or cfq is attached to the target queue, I think it should be fine semantic-wise.

**Comment by poettering** [comment] 2017-10-25 07:49
Yes, I'd greatly prefer if the differences here are abstracted by the kernel, and userspace doesn't have to know about this. If the kernel would expose the same concepts the same way on all schedulers things would magically start to work even, without any further userspace changes.

**Comment by paolo-github** [comment] 2017-11-04 18:44
@htejun ok, let's do it. If ok for you to provide me with a somewhat detailed scheme of what you have in mind, I'm willing to try to implement it. The more details you can provide me with (pseudocode?, code fragments to complete?, pseudo-diffs?, ...), the happier and more confident I would be.

**Comment by poettering** [comment] 2019-02-26 15:32
So, the kernel folks (hey, @paolo-github) work on this inside the kernel community. I don't think we need to track this here. As soon as the kernel work is done things should magically work with systemd. Let's hence close this here. Hope that makes sense.

**Comment by paolo-github** [comment] 2019-02-26 15:39
For me, yes. The problem is that I'm totally failing to convince relevant people to unify the cgroups interface, so that IOWeight does have an effect with BFQ!

Last, cold thread here:
https://lwn.net/ml/linux-block/20181119103424.3853-1-paolo.valente@linaro.org/

Any intervention from interested people would be welcome, and probably useful.

**Comment by kakra** [comment] 2019-08-16 08:54
Couldn't `IOWeight=` just write to both entries? I cannot currently imagine why I'd ever wanted to have different values in both settings.

**Comment by kakra** [comment] 2019-08-19 20:48
With my patch, BlockIOWeight still won't work with BFQ but that should be fixed by upcoming kernels (it's actually a kernel thing).

**Comment by poettering** [comment] 2021-02-09 21:34
Since 35e7a62ca32a30169a94693b831e53c832251984 systemd will also set bfq weight. Closing.

**Closed as completed by poettering** 2021-02-09 21:34 UTC
Labels: cgroups, pid1, not-our-bug
