### ISSUE TITLE
sd_bus_add_object_manager() exposes no objects when path != "/"

### ISSUE THREAD

**Issue by npmccallum** [systemd/systemd#524] opened 2015-07-08 21:15 UTC
This works:

```
sd_bus_add_object_manager(bus, NULL, "/");
sd_bus_add_object_vtable(bus, NULL, "/foo", "my.Interface", vtable, NULL);
```

In the above scenario, "/foo" is exposed in the ObjectManager on "/".

This doesn't:

```
sd_bus_add_object_manager(bus, NULL, "/foo");
sd_bus_add_object_vtable(bus, NULL, "/foo/bar", "my.Interface", vtable, NULL);
```

In the above scenario, "/foo/bar" is NOT exposed in the ObjectManager on "/foo".

**Comment by dvdhrm** [comment] 2015-07-09 08:59
What do you mean by "does not work"? (or "NOT exposed) What exactly do you call to retrieve the data?

**Comment by npmccallum** [comment] 2015-07-09 14:36
Create two ObjectManagers:

```
/
/foo
```

Create three objects:

```
/
/foo
/foo/bar
```

Now, call GetManagedObjects() on /. After fixing #525, it returns a dictionary with three entries. This is correct. However, if you call GetManagedObjects() on /foo, it returns an empty dictionary. It should return a dictionary with two entries.

**Comment by dvdhrm** [comment] 2015-07-09 14:57
I cannot reproduce this. Can you post a script to test this? Or example code?

**Comment by npmccallum** [comment] 2015-07-09 15:57
Yup:

```
#include <stddef.h>
#include <stdlib.h>

#include <systemd/sd-bus.h>

struct object {
    const char *baz;
};

static const sd_bus_vtable vtable[] = {
    SD_BUS_VTABLE_START(0),
    SD_BUS_PROPERTY("Baz", "s", NULL, offsetof(struct object, baz),
        SD_BUS_VTABLE_PROPERTY_CONST),
    SD_BUS_VTABLE_END
};

int main() {
    struct object obj = { "Hello World" };
    sd_bus *bus = NULL;

    sd_bus_open_system(&bus);
    sd_bus_request_name(bus, "my.name", 0); // Note: requires permission
    sd_bus_add_object_manager(bus, NULL, "/foo");
    sd_bus_add_object_vtable(bus, NULL, "/foo/bar", "my.iface", vtable, &obj);

    while (sd_bus_wait(bus, (uint64_t) -1) >= 0) {
        while (sd_bus_process(bus, NULL) > 0)
            continue;
    }

    return EXIT_SUCCESS;
}
```

The above code appears to work. However, if you call GetManagedObjects() on /foo, it returns an empty dictionary.

**Comment by dvdhrm** [comment] 2015-07-15 12:34
Wow, I wonder how that ever worked...

```
diff --git a/src/libsystemd/sd-bus/bus-objects.c b/src/libsystemd/sd-bus/bus-objects.c
index b3cc28e..cbdf655 100644
--- a/src/libsystemd/sd-bus/bus-objects.c
+++ b/src/libsystemd/sd-bus/bus-objects.c
@@ -1416,7 +1416,7 @@ static struct node *bus_node_allocate(sd_bus *bus, const char *path) {
                 e = strrchr(path, '/');
                 assert(e);

-                p = strndupa(path, MAX(1, path - e));
+                p = strndupa(path, MAX(1, e - path));

                 parent = bus_node_allocate(bus, p);
                 if (!parent)
```

**Comment by dvdhrm** [comment] 2015-07-15 12:46
Fixed in 7d67077f78d4a43f214c240359ad5f7284d086fa. Thanks!

**Closed as completed by dvdhrm** 2015-07-15 12:46 UTC
Labels: bug 🐛, sd-bus

**Comment by heftig** [comment] 2015-07-19 17:19
Doesn't seem to work all that well. `d-feet` reports lots of duplicate objects. It gets worse the deeper the hierarchy is. I think it's getting confused by the fact that the introspections of `/` and `/foo` both contain nodes for `/foo/bar`. It expects that the introspections only show one level (similar to how reading a directory isn't recursive).

**Comment by dvdhrm** [comment] 2015-07-21 09:41
The spec clearly allows recursive introspection data:

```
If a child <node> has any sub-elements, then they must represent
a complete introspection of the child. If a child <node> is empty,
then it may or may not have sub-elements; the child must be introspected
in order to find out. The intent is that if an object knows that its children
are "fast" to introspect it can go ahead and return their information, but
otherwise it can omit it.
```

`d-feet` has several problems regarding recursive introspection and object handling. It is a useful tool to query system information, but I don't think it should be used to debug interface correctness. Until `d-feet` gets fixed, I recommend using `busctl` or `gdbus` to check for interface correctness.

I'd gladly step up and write some `d-feet` patches, but unfortunately it's no C code and I'm getting a little bit rusty in python (or JS or whatever it is written in again)..

**Comment by heftig** [comment] 2015-07-21 13:13
> The spec clearly allows recursive introspection data:

No, I think you're misinterpreting this section and the spec isn't clear at all. It only requires that any child nodes you report must be either empty or complete.

It says nothing about whether having multiple introspection paths to a node (`/ → /foo → /foo/bar` and `/ → /foo/bar`) is allowed.

It says nothing about whether having both `<node name="foo"/>` and `<node name="foo/bar"/>` as siblings is allowed.

It says nothing about whether child nodes with names that contain slashes (i.e., descend more than one level) are allowed. The sample introspection in the spec has no such names.

d-feet seems to expect that you only report `<node name="foo"/>` and a subsequent introspection of `/foo` then contains `<node name="bar"/>`. Both libdbus and gdbus produce such introspection.

There might be other code in the wild that expects this. So, I think jumping levels of the tree might not be a good idea.

**Comment by dvdhrm** [comment] 2015-07-21 13:15
> It says nothing about whether having both <node name="foo"/> and <node name="foo/bar"/> as siblings is allowed.

As siblings? No, it should be recursive. Do we report them as siblings? That sounds wrong indeed.

**Comment by heftig** [comment] 2015-07-21 13:18
``` xml
> dbus-send --system --dest=org.freedesktop.login1 --print-reply / org.freedesktop.DBus.Introspectable.Introspect 
method return sender=:1.4 -> dest=:1.8666 reply_serial=2
   string "<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node>
 <!-- *snip* -->
 <node name="org/freedesktop/login1/user/_120"/>
 <node name="org/freedesktop/login1"/>
 <node name="org/freedesktop/login1/session/self"/>
 <node name="org/freedesktop/login1/user/_1000"/>
 <node name="org/freedesktop/login1/user/self"/>
 <node name="org/freedesktop/login1/seat/seat0"/>
 <node name="org/freedesktop/login1/seat/self"/>
 <node name="org/freedesktop/login1/seat"/>
 <node name="org/freedesktop/login1/user"/>
 <node name="org/freedesktop/login1/session"/>
 <node name="org/freedesktop/login1/session/c2"/>
 <node name="org/freedesktop/login1/session/c1"/>
</node>
"
```

**Comment by poettering** [comment] 2015-07-22 21:01
@heftig Indeed, we should report the subnode tags as children of their respective parent node tags... Could you please file a new github issue about this, as that's a different issue as the original issue discussed here?

**Comment by poettering** [comment] 2015-07-22 21:04
@heftig don't bother, I just filed the issue now myself as #664.
