### ISSUE TITLE
weird square chars in systemd console messages 

### ISSUE THREAD

**Issue by devZer0** [systemd/systemd#32301] opened 2024-04-16 12:09 UTC
### systemd version the issue has been seen with

252

### Used distribution

debian12

### Linux kernel version used

6.1.0-18-amd64

### CPU architectures issue was seen on

x86_64

### Component

other

### Unexpected behaviour you saw

i see these weird square characters in systemd console log/output when on vga 80x25 mode

is this a bug or intentional beviour (abbreviation mechanism) ? if the latter, what's the purpose ?

![grafik](https://github.com/systemd/systemd/assets/3506105/ae42ba9d-e5a2-4880-be47-6baf2b572c20)

### Steps to reproduce the problem

boot a debian 12 VM with "nomodeset" to avoid switching console to higher resolution

**Comment by polarina** [comment] 2024-04-16 12:24
Want to add that we also observe the same behaviour on Ubuntu 23.10 with systemd-255.4-1ubuntu7 (compiled from source). Haven't been a able to figure out the cause either yet.

**Comment by YHNdnzj** [comment] 2024-04-16 12:32
This is intentional, as we ellipsize the status output. It should be UTF-8 ellipsis symbol (`…`).

**Comment by devZer0** [comment] 2024-04-16 12:45
mhh, ok - besides the charcter rendering issue -  do you think it's the best approach to ellipsize in the middle of the systemd service name ?

if it fails you won't even know the exact service name from a console screenshot/picture.

**Comment by yuwata** [comment] 2024-04-16 12:55
Is it also reproducible with a recent release?

**Comment by devZer0** [comment] 2024-04-16 13:11
i can do a test if 255.4-1 from debian sid/unstable is recent anough

**Comment by yuwata** [comment] 2024-04-16 13:38
Yes. v255 is recent enough.

**Comment by devZer0** [comment] 2024-04-16 14:09
mhh, do i really need to ? ( as it has been reported here https://github.com/systemd/systemd/issues/32301#issuecomment-2058966024 to happen with systemd-255.4-1ubuntu7 )

**Comment by yuwata** [comment] 2024-04-16 14:12
Ah, I see. Then, not necessary.

**Comment by YHNdnzj** [comment] 2024-04-16 14:24
Still, this is not a bug. We choose to use the character under the assumption that the recommended console font does render it correctly. This is a duplicate of https://github.com/systemd/systemd/issues/6443. Closing.

**Closed as completed by YHNdnzj** 2024-04-16 14:24 UTC
Labels: pid1, duplicate, not-a-bug

**Comment by poettering** [comment] 2024-04-17 14:10
Just set SYSTEMD_UTF8=0 on the kernel cmdline, that should turn off systemd's unicode output.
