### ISSUE TITLE
network: Bridge parameter set by nspawn cleared by networkd

### ISSUE THREAD

**Issue by miffe** [systemd/systemd#17827] opened 2020-12-02 20:25 UTC
**systemd version the issue has been seen with**
 > 247.1

**Used distribution**
 > arch

**Linux kernel version used** (`uname -a`)
 > Linux node 5.9.11-arch2-1 #1 SMP PREEMPT Sat, 28 Nov 2020 02:07:22 +0000 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64 

In `/etc/systemd/nspawn/ftp.nspawn` i have 
>[Network]
>Bridge=bridge-local

In 246.6 the virtual interface vb-ftp was added to the bridge `bridge-local`
In 247.1 it is not.

A `ip l set vb-ftp master bridge-local` fixes it. But I expected it to be automatic since that was the behavior of the earlier version.

This happens with all of my nspawn containers.

**Comment by poettering** [comment] 2020-12-02 22:10
hmm, we didn't actually change anything in this area.

**Comment by miffe** [comment] 2020-12-02 22:17
A downgrade to systemd 246.6 makes it work again. I though maybe that it had something to do with the python 3.9 transition that arch is going through atm. But just downgrading the systemd packages makes it work again.

**Comment by miffe** [comment] 2020-12-09 18:21
I found the issue. On the host i had an `/etc/systemd/network/vb.network` with the content:

    [Match]
    Name=vb-*
    [Network]
    LinkLocalAddressing=no

To get rid of the IPv6 link local addresses on the nspawn interfaces. Removing that file makes the nspawn containers work.

**Comment by irminsul** [comment] 2020-12-26 01:38
I have just encountered the same issue, and it is unrelated to IPv6LL addressing.

The mere presence of `.network` file that targets `vb-*` devices is enough to break nspawn bridge setups in systemd 247.

**Comment by yuwata** [comment] 2021-01-11 05:19
This is caused by e16e4b3bedc57919b3ecb4096e941709a5d39b8a. Previously, `IFLA_MASTER` is cleared only when link is down. But with the commit, `IFLA_MASTER` is always cleared. So, even if `IFLA_MASTER` is enabled on a link by an external program (in this case, by nspawn), the `IFLA_MASTER` flag is cleared.

cc @ddstreet.

**Comment by Isopod** [comment] 2021-01-13 20:58
I had the same problem. In my case it was caused by a `.network` file that enables IPv6 privacy extensions on all interfaces:

```[Match]
Name=*

[Network]
IPv6PrivacyExtensions=true
```

I worked around it by changing it to this:

```[Match]
Name=br0

[Network]
IPv6PrivacyExtensions=true
```

**Comment by ddstreet** [comment] 2021-01-13 22:15
> This is caused by [e16e4b3](https://github.com/systemd/systemd/commit/e16e4b3bedc57919b3ecb4096e941709a5d39b8a). Previously, `IFLA_MASTER` is cleared only when link is down. But with the commit, `IFLA_MASTER` is always cleared. So, even if `IFLA_MASTER` is enabled on a link by an external program (in this case, by nspawn), the `IFLA_MASTER` flag is cleared.
> 
> cc @ddstreet.

It seems like it was just accidentally working before, no? nspawn shouldn't be manually setting a systemd-networkd managed interface's master, should it?

**Comment by ddstreet** [comment] 2021-01-14 13:53
> I found the issue. On the host i had an `/etc/systemd/network/vb.network` with the content:
> 
> ```
> [Match]
> Name=vb-*
> [Network]
> LinkLocalAddressing=no
> ```
> 

> I had the same problem. In my case it was caused by a `.network` file that enables IPv6 privacy extensions on all interfaces:
> 
> ```
> Name=*
> 
> [Network]
> IPv6PrivacyExtensions=true
> ```
> 

So in both of these cases, you are telling the *host* systemd-networkd that it should manage the host-side veth interfaces that are used by the nspawn containers.

However, the general assumption by systemd-networkd is that when it's told to manage an interface (meaning, when it finds a .network file whose [Match] section matches an interface), it will 100% control that interface. There are a small number of exceptions such as when the KeepConfiguration= param is used, but that's the general rule.

In this case, it's just 'luck' (or really IMHO a bug) that, because the interface happened to be already up, systemd-networkd in the host previously didn't remove the 'master' setting that nspawn added to the host-side veth interface.

> [Match]
> Name=vb-*
> [Network]
> LinkLocalAddressing=no

Why do you care if the host-side veth interface has an ipv6ll address or not?

> Name=*
> 
> [Network]
> IPv6PrivacyExtensions=true

This is a really bad idea, matching on Name=* means systemd-networkd will try to manage *all* system interfaces.

**Comment by Isopod** [comment] 2021-01-14 14:00
> However, the general assumption by systemd-networkd is that when it's told to manage an interface (meaning, when it finds a .network file whose [Match] section matches an interface), it will 100% control that interface.

That is not obvious and counter-intuitive imo. If I don't set a property explicitly, I don't expect systemd-networkd to modify it. For example:

> This is a really bad idea, matching on Name=* means systemd-networkd will try to manage all system interfaces.

I just want systemd-networkd to enable privacy extensions on all interfaces. I didn't specify anything about bridges in here, so I don't expect systemd-networkd to touch this part at all.

**Comment by ddstreet** [comment] 2021-01-14 14:53
> > However, the general assumption by systemd-networkd is that when it's told to manage an interface (meaning, when it finds a .network file whose [Match] section matches an interface), it will 100% control that interface.
> 
> That is not obvious and counter-intuitive imo. If I don't set a property explicitly, I don't expect systemd-networkd to modify it. For example:
> 
> > This is a really bad idea, matching on Name=* means systemd-networkd will try to manage all system interfaces.
> 
> I just want systemd-networkd to enable privacy extensions on all interfaces. I didn't specify anything about bridges in here, so I don't expect systemd-networkd to touch this part at all.

This isn't how systemd-networkd works. It either manages the interface, or it doesn't. If your suggestion was the way systemd-networkd worked, things would be *much* more non-obvious as any random pre-existing interface state would frequently break and/or conflict with the expected configuration.

Specifically for privacy extensions, you shouldn't be using systemd-networkd to change the setting for *all* interfaces on your system, only the ones that you actually want systemd-networkd to control. The *default* configuration for ipv6 privacy extensions can be set via sysctl.conf, and for Ubuntu at least (I'm not sure about other distros) already is set by the /etc/sysctl.d/10-ipv6-privacy.conf configuration:

```
# IPv6 Privacy Extensions (RFC 4941)
# ---
# IPv6 typically uses a device's MAC address when choosing an IPv6 address
# to use in autoconfiguration. Privacy extensions allow using a randomly
# generated IPv6 address, which increases privacy.
#
# Acceptable values:
#    0 - don’t use privacy extensions.
#    1 - generate privacy addresses
#    2 - prefer privacy addresses and use them over the normal addresses.
net.ipv6.conf.all.use_tempaddr = 2
net.ipv6.conf.default.use_tempaddr = 2

```

That (sysctl.d) is the mechanism you should use to *default* to using privacy extensions. If you do, then all your interfaces that *are not* managed by systemd-networkd will default to using privacy extensions, including all the vb-* interfaces created by nspawn.

Note that you can also use sysctl.d configuration to set privacy settings for individual interfaces, e.g.:

```
net.ipv6.conf.all.use_tempaddr = 0
net.ipv6.conf.default.use_tempaddr = 0
net.ipv6.conf.vb-*.use_tempaddr = 2

```

man sysctl.d has more detail.

**Comment by Isopod** [comment] 2021-01-15 00:25
Thanks, I am already doing that. The reason for this `.network` file was precisely to control the setting on interfaces systemd-networkd *does* manage, because the sysctl setting has no effect there. It was never really intended to target `vb-*` interfaces. The file predates my usage of systemd-nspawn by several years. Back then I just wanted a catch-all solution for ethernet, wifi etc., instead of specifying the option manually for every interface. Everything worked until I upgraded to 247. Now that I know what the problem is, it's not a big deal to change it. But I was pulling my hair out until I found this thread.

**Comment by yuwata** [comment] 2021-01-18 06:49
> > This is caused by [e16e4b3](https://github.com/systemd/systemd/commit/e16e4b3bedc57919b3ecb4096e941709a5d39b8a). Previously, `IFLA_MASTER` is cleared only when link is down. But with the commit, `IFLA_MASTER` is always cleared. So, even if `IFLA_MASTER` is enabled on a link by an external program (in this case, by nspawn), the `IFLA_MASTER` flag is cleared.
> > cc @ddstreet.
> 
> It seems like it was just accidentally working before, no? nspawn shouldn't be manually setting a systemd-networkd managed interface's master, should it?

@ddstreet `join_bridge()` in nspawn-network.c makes the interface up and sets `IFLA_MASTER`. So, before the commit you made, networkd did not try to unset `IFLA_MASTER`, as it was done only when the interface is down.

> nspawn shouldn't be manually setting a systemd-networkd managed interface's master, should it?

If nspawn does not specify `IFLA_MASTER`, backward compatibility is broken. If nspawn does not, networkd needs to set it explicitly. But to set the flag correctly, .network file must contain `Bridge=` setting, and nspawn needs to generate .network file with the setting dynamically. Also, some users may not use networkd but use e.g. NetworkManager. So, generating .network file dynamically does not work in that case... So, still nspawn needs to set `IFLA_MASTER`.

My idea to solve this issue is, introducing `ManageMaster=` or `ResetMaster=` boolean setting (defaults to true) in `[Link]` section.
If this is disabled, then networkd does not unset `IFLA_MASTER` flag. The setting will be ignored if `Bridge=` or friends is specified.

**Comment by yuwata** [comment] 2021-01-18 06:55
(BTW, I noticed we have not introduce the default .network file for `vb-*`.)

**Comment by ddstreet** [comment] 2021-01-21 13:07
> > > This is caused by [e16e4b3](https://github.com/systemd/systemd/commit/e16e4b3bedc57919b3ecb4096e941709a5d39b8a). Previously, `IFLA_MASTER` is cleared only when link is down. But with the commit, `IFLA_MASTER` is always cleared. So, even if `IFLA_MASTER` is enabled on a link by an external program (in this case, by nspawn), the `IFLA_MASTER` flag is cleared.
> > > cc @ddstreet.
> > 
> > 
> > It seems like it was just accidentally working before, no? nspawn shouldn't be manually setting a systemd-networkd managed interface's master, should it?
> 
> @ddstreet `join_bridge()` in nspawn-network.c makes the interface up and sets `IFLA_MASTER`. So, before the commit you made, networkd did not try to unset `IFLA_MASTER`, as it was done only when the interface is down.
> 
> > nspawn shouldn't be manually setting a systemd-networkd managed interface's master, should it?
> 
> If nspawn does not specify `IFLA_MASTER`, backward compatibility is broken. If nspawn does not, networkd needs to set it explicitly. But to set the flag correctly, .network file must contain `Bridge=` setting, and nspawn needs to generate .network file with the setting dynamically. Also, some users may not use networkd but use e.g. NetworkManager. So, generating .network file dynamically does not work in that case... So, still nspawn needs to set `IFLA_MASTER`.
> 
> My idea to solve this issue is, introducing `ManageMaster=` or `ResetMaster=` boolean setting (defaults to true) in `[Link]` section.
> If this is disabled, then networkd does not unset `IFLA_MASTER` flag. The setting will be ignored if `Bridge=` or friends is specified.

It seems like that shoudn't be necessary for this case, at least, as by default the host-side systemd-networkd won't have any .network file that should match the interface that systemd-nspawn creates. In the case where the host-side admin has created a .network file that matches the systemd-nspawn-created interface(s), even if a new config param was added, the admin would have to edit their host-side .network file to add the new param anyway, and I think a better approach would be for them is to just not use systemd-networkd to try to manage nspawn-owned interfaces.

However, if there is a case where there is a need to have systemd-networkd not change a managed interface's master setting, maybe it would be better to add a bit to KeepConfiguration= instead of adding a new parameter? If we keep all the systemd-networkd exceptions to interface management in that parameter, it may be easier to deal with, as there may be even more exceptions needed later...

**Comment by yuwata** [comment] 2021-02-18 22:33
Yeah, after re-considering this. User should configure .network with `Bridge=`, and also prepare .netdev for the bridge.

**Comment by yuwata** [comment] 2021-11-30 08:24
57aef9d7373c97d04beb6c5fc268496c3fdcf0a4 introduces `KeepMaster=`. Closing.

**Closed as completed by yuwata** 2021-11-30 08:24 UTC
Labels: network, not-a-bug
