### ISSUE TITLE
systemd-resolved doesn't resolve AAAA records sometimes

### ISSUE THREAD

**Issue by cuihaoleo** [systemd/systemd#5915] opened 2017-05-09 03:57 UTC
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

### systemd version the issue has been seen with

> systemd 232
> +PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +ID

### Used distribution

> Arch Linux with stock 4.10.13-1-ARCH kernel

### In case of bug report: Expected behaviour you didn't see

> User applications (like curl/ping) resolve domain names with AAAA record only successfully without any special options specified.

### In case of bug report: Unexpected behaviour you saw

> Sometimes curl/ping cannot resolve domain names with AAAA record only without `-6` option.

### In case of bug report: Steps to reproduce the problem

Backgroud: I have an ethernet interface ens3 managed by systemd-networkd and a Tinc VPN interface. ens3 has a private IP on it and is routable to IPv4 network. As for Tinc VPN, I assigned an IPv6 unique local address and an IPv4 link-local address on it and is routable to corresponding private network.

```
$ networkctl status
●        State: routable
       Address: 10.0.199.19 on ens3
                169.254.248.36 on cvnet0
                fd38:dd3b:b524:80d5:fc25:70ff:fec9:19f5 on cvnet0
                fe80::f816:3eff:fe73:149a on ens3
                fe80::fc25:70ff:fec9:19f5 on cvnet0
       Gateway: 10.0.199.1 on ens3
           DNS: 114.114.114.114
                202.38.64.7
```

I create AAAA records which resolve IPv6 unique local address for my Tinc network:

```
$ dig +short AAAA loong.tinc.i-yu.me
fd38:dd3b:b524:80d5:fc86:8aff:fe7d:1f2b
```

But sometimes systemd-resolved won't resolve these address unless application ask for IPv6 address explicitly:

```
$ ping lace.tinc.i-yu.me
ping: lace.tinc.i-yu.me: Name or service not known
$ ping -6 -c1 lace.tinc.i-yu.me
PING lace.tinc.i-yu.me(fd38:dd3b:b524:80d5:fcec:efff:fede:c398 (fd38:dd3b:b524:80d5:fcec:efff:fede:c398)) 56 data bytes
......
```

And outputs of `systemd-resolve`:
```
$ systemd-resolve lace.tinc.i-yu.me
lace.tinc.i-yu.me: resolve call failed: 'lace.tinc.i-yu.me' does not have any RR of the requested type
$ systemd-resolve -6 lace.tinc.i-yu.me
lace.tinc.i-yu.me: fd38:dd3b:b524:80d5:fcec:efff:fede:c398

-- Information acquired via protocol DNS in 924us.
-- Data is authenticated: no
```

I say sometimes because sometimes it does work as expected (test at the same time, but another domain name).
```
$ systemd-resolve loong.tinc.i-yu.me
loong.tinc.i-yu.me: fd38:dd3b:b524:80d5:fc86:8aff:fe7d:1f2b

-- Information acquired via protocol DNS in 1.1ms.
-- Data is authenticated: no
```

I've read #5782,  poettering says "if you do not specify the address type you are looking for then we'll suppress answers for protocols we consider "unroutable" on the local system". I'm sure that both IPv6 address is routeable:

```
$ ip r get fd38:dd3b:b524:80d5:fc86:8aff:fe7d:1f2b
fd38:dd3b:b524:80d5:fc86:8aff:fe7d:1f2b from :: dev cvnet0 proto kernel src fd38:dd3b:b524:80d5:fcd3:1aff:fe9d:649 metric 256  pref medium
$ ip r get fd38:dd3b:b524:80d5:fcec:efff:fede:c398
fd38:dd3b:b524:80d5:fcec:efff:fede:c398 from :: dev cvnet0 proto kernel src fd38:dd3b:b524:80d5:fcd3:1aff:fe9d:649 metric 256  pref medium
```

Not sure how to debug it. Any ideas? I'd like to help diagnose the bug.

**Comment by poettering** [comment] 2017-05-09 17:10
REgarding debugging: my comment on #5782 has some hints:

https://github.com/systemd/systemd/issues/5782#issuecomment-298228527

But this requires gdb skills really, not sure what else I can propose...

I figure ultimately this is just a duplicate of #5782...

**Comment by flokli** [comment] 2019-01-03 09:43
@cuihaoleo this really seems to be a duplicate of #5782, my guess is systemd considers resolution works if you have IPv6 adresses on `ens3` (and by doing so, convince resolved to not strip AAAA records)

**Closed as completed** 2020-05-26 17:30 UTC
Labels: bug 🐛, resolve
