### ISSUE TITLE
bind mount by nspawn is available inside systemd-logind.service

### ISSUE THREAD

**Issue by mikhailnov** [systemd/systemd#19192] opened 2021-04-03 10:55 UTC
Hello

I build a squashfs image with a rootfs and then run it an an nspawn container like this:

```bash
mkdir -p /run/coturn-container/certs
mkdir -p /run/coturn-container/live
mkdir -p /run/coturn-container/systemd

systemd-nspawn \
	--image="$(ls -t *.sqfs | head -n1)"  \
	--bind=/run/coturn-container/certs:/var/lib/coturn/certs \
	--bind=/run/coturn-container/live:/etc/letsencrypt/live \
	--bind=/run/coturn-container/systemd:/var/lib/systemd \
	--private-users=1100000 \
	--boot
```

The problem is that `systemd-logind.service` fails to start with error:
systemd-logind.service: Failed to set up special execution directory in /var/lib: Permission denied

I think it is because a separate mount namespace is made inside systemd-logind.service:
```
# systemctl cat systemd-logind | grep -iE 'dir|read|write|protectsystemd' | sort -u
<...>
MemoryDenyWriteExecute=yes
ReadWritePaths=/etc /run
RuntimeDirectory=systemd/sessions systemd/seats systemd/users systemd/inhibit systemd/shutdown
RuntimeDirectoryPreserve=yes
StateDirectory=systemd/linger
```

Q1: is is expected behaviour that such service soes not see bind-mounted `/var/lib/systemd`?
Q2: what is the best practice to run such a container?

systemd v246.9, have not tried the newest version yet.

**Comment by mikhailnov** [comment] 2021-04-03 12:47
Worked around by `--bind=+/run/systemd:/var/lib/systemd`

**Comment by poettering** [comment] 2021-04-06 09:09
You are using userns. Are you sure the mount you add in for /var/lib/systemd is owned by the right UID that'll eventually be mapped to the root UID the container will use?

Maybe the dir you mount in there is simply owned by the wrong UID and thus systemd inside the container can't use it and attempts to create dirs within it will fail with EACCES?

**Comment by mikhailnov** [comment] 2021-04-06 09:45
I think this issue is just a specific case of https://github.com/systemd/systemd/issues/19195 which I reported a bit later. When private users are enabled, directories owned by 0 on the host are mapped to nobody, but it must not prevent root inside the container from writing to them, must it?

**Comment by poettering** [comment] 2021-04-06 09:54
usern is a security mechanism: objects owned by UIDs that cannot be mapped are off limits really and container code that is privileged can't really modify them either.

**Comment by poettering** [comment] 2021-04-06 11:33
Let's close this as duplicate of #19195

**Closed as completed by poettering** 2021-04-06 11:33 UTC
Labels: nspawn, needs-reporter-feedback ❓
