### ISSUE TITLE
systemd-240 doesn't start SDDM on HyperV VM

### ISSUE THREAD

**Issue by FireBurn** [systemd/systemd#11299] opened 2018-12-31 11:26 UTC
**systemd version the issue has been seen with**
> ...
systemd-240

**Used distribution**
 > …
Gentoo
**Expected behaviour you didn't see**
 > …

SDDM doesn't start
**Unexpected behaviour you saw**
 > …

**Steps to reproduce the problem**

Emerge systemd-240 - reboot

To get a working system again emerge systemd-239

[journalctl-239.log](https://github.com/systemd/systemd/files/2718247/journalctl-239.log)
[journalctl-240.log](https://github.com/systemd/systemd/files/2718248/journalctl-240.log)

**Comment by yuwata** [comment] 2019-01-01 19:02
I hope #11244 fixes this issue.

**Comment by yuwata** [comment] 2019-01-03 15:31
#11244 was merged. Let's close this. If the problem still exists, please reopen this.

**Comment by FireBurn** [comment] 2019-01-14 09:20
[journal-240-r3.log](https://github.com/systemd/systemd/files/2754535/journal-240-r3.log)

This is still happening with systemd-240-r3 on Gentoo, that has the above fix I believe

Is there extra debugging I can enable to help pinpoint the issue?

**Comment by yuwata** [comment] 2019-01-14 18:41
This maybe a duplicate of #11293 (and #11413?). The issue was already fixed in the upstream, but it seems that the fix is not included in 240-r3. Please test the latest git snapshot. I am not familiar with gentoo, but maybe systemd-9999?

Then, if the current master does not work, please boot with `systemd.log_level=debug` or `udev.log_priority=debug` to generate debugging logs.

**Comment by FireBurn** [comment] 2019-01-15 00:17
I can confirm this still doesn't work with systemd-9999

Here's the log....

[journalctl-9999.log](https://github.com/systemd/systemd/files/2757571/journalctl-9999.log)

**Comment by yuwata** [comment] 2019-01-15 05:09
So, I cannot find anything suspicious lines about udevd.
Could you test #11378?
Even if #11378 does not fix the issue, then please also provide logs of sddm or X.

**Comment by FireBurn** [comment] 2019-01-15 07:22
What do you mean by test #11378 ?

There are no logs for sddm or X, they don't start

**Comment by FireBurn** [comment] 2019-01-15 09:40
Sorry, didn't realise it was a pull request, I'll test it now

**Comment by FireBurn** [comment] 2019-01-15 12:43
Nope, it still doesn't start with that MR applied

[journalctl-9999-patched.log](https://github.com/systemd/systemd/files/2759668/journalctl-9999-patched.log)

**Comment by keszybz** [comment] 2019-01-15 13:34
Sorry, but I don't think this is going to be diagnosed upstream. This needs to be debugged by somebody who has gentoo and sddm. There are no errors in the logs. For sddm, we only knows that it starts:
> systemd[1]: sddm.service: Succeeded.

It's really hard for us to guess what should be different based on this.

**Comment by FireBurn** [comment] 2019-01-15 17:04
I've downgraded to systemd 239 where it just works

It's really hard for me to guess where it's going wrong too, but based on the fact that it's working fine on my other two systems, one Intel the other AMD I'm guessing it's HyperV related rather than Gentoo or SDDM itself

**Comment by vcaputo** [comment] 2019-01-15 19:53
@FireBurn If you have a situation where the problem is easily reproduced, you may be able to identify the offending commit with a `git bisect`.

**Comment by yuwata** [comment] 2019-01-15 20:00
Maybe #11438 is related.

**Comment by yuwata** [comment] 2019-01-15 22:32
BTW, is it possible to start X manually? What happens when other display manager is used?

**Comment by FireBurn** [comment] 2019-02-15 16:45
Found the commit with bisecting

6260d28b8a002a401eab7511f96fd62f471dccdb is the first bad commit
commit 6260d28b8a002a401eab7511f96fd62f471dccdb
Author: Marco Trevisan (Treviño) <mail@3v1n0.net>
Date:   Thu Nov 1 03:04:50 2018 +0100

    login: Don't mark framebuffer devices as master-of-seat devices

    Currently we consider any framebuffer device as enough to have a
    valid graphical session, but this might lead to many false postives
    like in the case of framebuffer devices that have a linked drm card
    which is still in the process of being added, or for vesa fb, and
    so it doesn't ensure us that we can have a proper graphical session.

    Since these days we normally don't consider anything without a DRM
    card able to provide a full graphical session, let's not set this
    at this level.
    Drivers which can provide a graphical session with the sole fb are
    still free to mark any device as `master-of-seat`

    Fixes #10435

:040000 040000 03a65630453eb01c3feb183e9bbefad83d715440 a519517c5b8da84fcf53c282f2e2c7ce161f67f4 M      src

**Comment by FireBurn** [comment] 2019-02-15 16:57
I can confirm that reverting 6260d28b8a002a401eab7511f96fd62f471dccdb from systemd-241 allows SDDM to start again on HyperV

**Comment by poettering** [comment] 2019-02-15 17:03
hmm, does hyperv not have a drm driver, and only an fb driver?

Is hyperv support still maintained by Microsoft? 

I figure we could readd the master-of-seat tag for hyperv fb devices, if they need it. Preferably that'd be carried by some hyperv-specific package though I must say. Does one such package exist?

**Comment by FireBurn** [comment] 2019-02-15 17:22
Correct it only has FB_HYPERV

I believe it is

No HyperV specific packages on Gentoo

**Comment by poettering** [comment] 2019-02-15 17:38
hmm, can you play around with adding a rule like this one:

```
SUBSYSTEM=="graphics", KERNEL=="fb[0-9]*", DRIVERS="hyperv", TAG+="seat", TAG+="master-of-seat"
```

(not sure how the driver is precisely called, hence please update the rule accordingly, before testing, you get the idea)

if that works, please consider submitting that as PR

**Comment by poettering** [comment] 2019-02-18 17:40
So yeah, it appears #11438 is the same issue as this one, just for different VM hosts. I figure both should be fixed the same way by whitelisting their drivers. (not sure how that scales in the long run, but let's try whitelisting initially)

**Comment by FireBurn** [comment] 2019-02-19 12:06
So adding DRIVERS=="hyperv_fb" makes it work (the double == is required)

Would the final one look like 

SUBSYSTEM=="graphics", KERNEL=="fb[0-9]*", TAG+="seat"
SUBSYSTEM=="graphics", KERNEL=="fb[0-9]*", DRIVERS=="hyperv_fb", TAG+="seat", TAG+="master-of-seat"

Or is there a better way to add this quirk?

**Comment by poettering** [comment] 2019-02-26 17:39
yeah, those lines look good. though you don't need to add the "seat" tag twice...

Can you prep a PR of that? then we can merge the fix.

**Closed as completed** 2019-03-04 11:04 UTC
Labels: udev, login

**Comment by hramrach** [comment] 2021-06-30 10:42
See also #20070
