### ISSUE TITLE
RFE: networkd: possibly down interface when networkd is restarted and .network configures a different MAC address than is previously set, so that the MAC address can actually be changed

### ISSUE THREAD

**Issue by ratagupt** [systemd/systemd#6696] opened 2017-08-30 08:55 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with
232

### In case of bug report: Expected behaviour you didn't see

Here is the configuration of the network file
====================================
cat /etc/systemd/network/00-xyz-eth0.network
[Match]
Name=eth0
[Link]
MACAddress=70:E2:84:14:20:45 
[Network]
Address=10.10.10.4/24
Gateway=10.10.10.1

Configuration of link file
====================
cat /etc/systemd/network/00-xyz-eth0.link
[Match]
MACAddress=60:E2:84:14:20:45

[Link]
MACAddress=70:E2:84:14:20:45

Before systemd-networkd  restart
==========================
ip link show
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether 60:e2:84:14:20:45 brd ff:ff:ff:ff:ff:ff 

After Systemd-networkd restart
systemctl restart systemd-networkd.service

ip link show
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether 60:e2:84:14:20:45 brd ff:ff:ff:ff:ff:ff 

### In case of bug report: Unexpected behaviour you saw

The mac address is not changed,expected output I thought it should be 70:E2:84:14:20:45

### In case of bug report: Steps to reproduce the problem

Given above.

**Comment by poettering** [comment] 2017-08-30 09:06
MAC addresses can only be changed when an interface is down, and yours is not when networkd is restarted. That's a Linux kernel limitation. if you down it first, does it work then?

**Comment by ratagupt** [comment] 2017-08-30 09:20
Yes it worked once I down the interface and restart the networkd.
Shouldn't systemd-networkd take care of this,If in the link file Match section MACAddress is different then Link section MACAddress,It should automatically down the interface,set the mac address and do the interface up..
or if the network file Link section MACAddress is not same as current system MACAddress then do all the operation(interfacedown,set the address,interfaceup).

**Comment by poettering** [comment] 2017-08-30 09:28
i am not sure it really should down interfaces needlessly. But dunno, will leave open as RFE

**Comment by FritzHerbers** [comment] 2019-03-10 17:06
```
The "[Link]" section accepts the following keys:
MACAddress=
    The hardware address to set for the device.
```
Would be nice when something does not work as intended that it is marked as such.

Instead of using systemd-networkd macaddress spoofing, setting a udev rule as:
`ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="XX:XX:XX:XX:XX:XX", RUN+="/sbin/ip link set dev $name address YY:YY:YY:YY:YY:YY"`
networkd is not able to get a DHCP offer (maybe it doesn't even try).
dhclient works immediate.
Is this also a known issue?

Also noted, without the above udev rule and setting link.macaddress (no ip is retrieved), changing it without the link.macaddress and restart systemd-networkd, no ip is retrieved. Is this a known issue?

**Comment by yuwata** [comment] 2019-03-11 01:37
@FritzHerbers Not sure, it seems your issue is not relevant to this issue.

If you use recent systemd, v240 or newer, then please file your issue in a new page. In that case,
- please provide relevant configs: .link, .network, and .rules files.
- please provide relevant debug logs: boot with `udev.log_priority=debug systemd.log_level=debug` and show `journalctl -b --no-hostname -u systemd-networkd.service -u systemd-udevd.service`.

Thank you.

**Comment by FritzHerbers** [comment] 2019-03-11 17:42
@yuwata,  Ubuntu bionic is on v237, cosmic on v239. I will wait till they upgrade and create a new issue should the problem persist.

**Closed as completed** 2021-06-14 20:35 UTC
Labels: RFE 🎁, network
