### ISSUE TITLE
RFE:add a 'lingering' option that can be set per-user service file or 'systemd-run'

### ISSUE THREAD

**Issue by miaofengwei** [systemd/systemd#3382] opened 2016-05-29 08:10 UTC
RFE: add a 'lingering' option that can be set per-user service file or 'systemd-run'

**Comment by mbiebl** [comment] 2016-05-29 08:20
This sounds very useful. Say I wanted to start a screen session which survives a logout, I do not necessarily want all of my desktop processes (tracker, eds, gvfs-\* etc) to keep running as well.

The current all-or-nothing approach is imho not good enough.

**Comment by martinpitt** [comment] 2016-05-29 09:13
We get a lot of complaints in http://bugs.debian.org/825394 about the changed "kill user processes by default on logout" default. Personally I actually _do_ expect my leftover processes to go away on logout, and this downstream bug report is not really representative of normal PC usage by non-technical users, but they do have a point: If someone explicitly opts into using screen/tmux on a local PC, then it is right to assume that these do survive a logout. So if we could change tmux and screen to apply lingering when they start, that'd give the best of both worlds IMHO.

**Comment by 4144** [comment] 2016-05-29 15:06
Better fix systemd.
Because why any program must care about init system used? if program must works in background, then it mean it MUST works. And systemd now broking all this programs.

You simply cant add systemd workaround to all possible software. It can be not only tmux or screen, but any other software.

Even if you add your changes to tmux and screen, how they will works if no systemd in system completly?

**Comment by miaofengwei** [comment] 2016-05-29 15:48
'systemd-run --scope --user --lingering screen' is good enough.

**Comment by poettering** [comment] 2016-05-29 16:55
lingering is relevant to security, it's not the systemd --user instance that decides whether to stay around or not after the user logged out, it's the host systemd instance and logind that decide that, or in other words: it's privileged system code that enforces the lifecycle of the user code, it's not the user code doing this on its own. 

If lingering is enabled, this is a system operation, that is protected via PolicyKit. The default PK policy on this is pretty liberal, but the whole point of the new default behaviour of logind is that use code can't override system policy here, and can't stay around if the host's policy doesn't allow it.

Thus adding an option to systemd --user services (or systemd-run --user) doesn't really make sense: the systemd --user instance can't stay around even if it wants to if the host disallows this.

**Comment by miaofengwei** [comment] 2016-05-29 22:32
@poettering, it's not the systemd-run --user instance that decides whether to stay around or not after the user logged out,it is merely a request, it's the host systemd instance and logind that decide whether to allow the request.

**Comment by miaofengwei** [comment] 2016-05-29 23:08
the request = loginctl enable-linger for #PID temporarily

**Comment by AnchorCat** [comment] 2016-05-30 08:12
How much sense might it be to have `setsid(2)` automatically move the calling process into a new logind session? That seems like a reasonable compromise, but I'm not sure what (if anything) might break with it.

**Comment by miaofengwei** [comment] 2016-05-30 16:09
@poettering, are PAM sessions the correct mechanism to use here?

**Comment by poettering** [comment] 2016-05-30 16:40
@AnchorCat setsid() is a system call used only for doing proper job control on a tty. It has no other uses, and is irelevant for logind-style session management.

@miaofengwei hmm? logind only manages PAM sessions, nothing else.

Anyway, closing this one, as I am very sure we shouldn't mix something that is strictly per-user (lingering) and turn it into something per-service, which it really isn't. Lingering simply controls how long the systemd --user instance sticks around (i.e. the user@.service system unit), and that's a privileged setting, and should not be influenced by unprivileged per-service settings. I hope this is understandable.

**Closed as completed by poettering** 2016-05-30 16:40 UTC
Labels: RFE 🎁

**Comment by miaofengwei** [comment] 2016-06-04 03:48
add a 'LingeringTimeSec' option that can be set per-user service file?
0 means being killed on logout, infinity means no killing.

**Comment by miaofengwei** [comment] 2016-06-04 04:17
Lingering settings need to be two layers, one is declared by the service file, the other is enforced by privileged code and policy.

**Comment by arvidjaar** [comment] 2016-06-04 05:48
@poettering 

> Lingering simply controls how long the systemd --user instance sticks around

The problem is it is too heavy weighted. If it is enabled, user instance is started on system boot which makes it impractical to enable by default for every user.

Currently semantic is
- if linger is disabled, user instance is started with the first session and stopped with the last session
- if linger is enabled, user instance is started when system boots and is stopped when system shuts down

What users apparently want is the third (let's call it on-demand) version with semantic
- if linger is set to on-demand, user instance is started with the first user session and stopped when no more scopes are left for this user

This would enable every user to start long-running processes using `systemd-run --scope` while avoiding huge overhead of enumerating and starting user session for every possible user. At the same time this would automatically cleanup unused user instances when long running processes finish.

IOW - current linger is more focused on making it possible to launch processes on behalf of user without explicit sessions, while "on-demand" is more focused on simply allowing processes that exceed session lifetime.

@miaofengwei Would this answer your demand?

> add a 'LingeringTimeSec' option that can be set per-user service file?

"linger" is really systemd instance property. What you actually want is to explicitly start service in different scope. I am not sure, it may already happen (when using external unit definition); if not, option parallel to `systemd-run --scope` would be needed.

**Comment by bl33pbl0p** [comment] 2019-01-13 20:06
Setting 'UserStopDelaySec=infinity' in logind.conf gives these semantics now, but it is a global option unfortunately.
