### ISSUE TITLE
Invalid serial console blocks system boot

### ISSUE THREAD

**Issue by lyind** [systemd/systemd#15783] opened 2020-05-11 17:28 UTC
**systemd version the issue has been seen with**
> systemd 245 (245.5-2)

**Used distribution**
 > Debian 11 (bullseye)

**Expected behaviour you didn't see**
 > System boots normally and ignores read/write/open errors non-existent/broken serial console, possibly after a timeout.

**Unexpected behaviour you saw**
 > Kernel boots normally, systemd doesn't reach multi-user-target and does not configure the network. The node is unreachable via network and appears to hang.

**Steps to reproduce the problem**
> 1. Check for a non-connected/disabled serial port. On the problematic system running `stty -a -F /dev/ttyS1` yields `stty: /dev/ttyS1: Input/output error`
>    The serial ports are registered by the "serial8250" driver but are probably not wired to anything.
> 1. Boot with a kernel command line that puts serial console on a non-existent/broken serial port via last "console=" argument:
>   `console=tty0 console=ttyS1,115200n8`
> 1. Check if system boots successfully

**Comment by poettering** [comment] 2020-05-11 19:05
Duplicate of #15656

**Closed as completed by poettering** 2020-05-11 19:05 UTC
Labels: duplicate
