### ISSUE TITLE
EFI partition not found when root is an md mirror

### ISSUE THREAD

**Issue by caldwell** [systemd/systemd#32107] opened 2024-04-04 22:14 UTC
### systemd version the issue has been seen with

255.4-1

### Used distribution

Debian (testing)

### Linux kernel version used

6.6.15-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd-gpt-auto-generator

### Expected behaviour you didn't see

systemd-gpt-auto-generator should create `/run/systemd/generator.late/efi.mount` with references to `/dev/...` devices that exist. `/efi` should mount when accessed.

### Unexpected behaviour you saw

systemd-gpt-auto-generator creates this in `/run/systemd/generator.late/efi.mount`:

```
# Automatically generated by systemd-gpt-auto-generator

[Unit]
Description=EFI System Partition Automount
Documentation=man:systemd-gpt-auto-generator(8)
Requires=systemd-fsck@dev-disk-by\x2ddiskseq-18\x2dpart1.service
After=systemd-fsck@dev-disk-by\x2ddiskseq-18\x2dpart1.service
After=blockdev@dev-disk-by\x2ddiskseq-18\x2dpart1.target

[Mount]
What=/dev/disk/by-diskseq/18-part1
Where=/efi
Type=vfat
Options=umask=0077,rw,nodev,nosuid,noexec,nosymfollow
```

Unfortunately `/dev/disk/by-diskseq/18-part1` does not exist in `/dev`:
```
$ ls -l /dev/disk/by-diskseq/18*
ls: cannot access '/dev/disk/by-diskseq/18*': No such file or directory
```

This appears to be due to 9a78ee002f14cf1feeb2d4a13ad9936a2f755e02, which stops creation of `/dev/disk/by-diskseq/*` files for `md` devices.

Ultimately this creates large timeouts when accessing `/efi`:

```
$ time ls -l / > /dev/null
ls: cannot access '/efi': No such device

real    0m52.250s
user    0m0.001s
sys     0m0.002s
```

### Steps to reproduce the problem

1. Create an md device with raid level 1 (mirroring) with 1.0 superblock (1.2 superblock might also work--I've not tried it)
2. Create a gpt partition table on the md device
3. Add an EFI  System Partition (c12a7328-f81f-11d2-ba4b-00a0c93ec93b) with a FAT filesystem
4. Add a Linux partition (0fc63daf-8483-4772-8e79-3d69d8477de4) and install debian testing
5. Boot

**Comment by bluca** [comment] 2024-04-04 22:18
Do firmwares even support ESPs on raid?

**Comment by caldwell** [comment] 2024-04-04 22:27
> Do firmwares even support ESPs on raid?

They don't need to when it's mirrored and the md device uses format 1.0 metadata (which means the md superblock is at the end): block 0-N-1 on any of the raid backing store devices is block 0-N of the md volume, so the block device "shines through" enough for the bios to find and boot grub. This works on all the EFI and old school BIOSes I've used.

**Comment by yuwata** [comment] 2024-04-04 22:30
Should be caused by 8716a76ce2058876abc7c5b1001822ac9e08a617.

**Comment by yuwata** [comment] 2024-04-05 04:57
-> #32111.

**Comment by yuwata** [comment] 2024-04-05 07:50
Is this issue only for ESP? I don't think so. I guess the same issue should be triggered non-ESP partition on MD device.

**Comment by poettering** [comment] 2024-04-05 07:53
@caldwell so your MD devices do they actually have kernel partition scanning enabled? That's not the default for MD, is it?

If you didn't then the right approach is to simply detect in gpt-auto-generator whether part scanning is on. And if it is off, just not do any gpt-auto stuff.

**Comment by caldwell** [comment] 2024-04-05 20:37
> @caldwell so your MD devices do they actually have kernel partition scanning enabled? 

I don't seem to have anything special enabled. I don't see any kernel cmd line params that relate to this. This root device was created in 2019 so I don't really remember the command line I used, though I highly doubt I passed the `--auto` parameter.

> That's not the default for MD, is it?

The mdadm man page says (in the `--auto{=yes,md,mdp,part,p}{NN}` section of "create, build, or grow"):

> "md" causes a non-partitionable array to be used (though since Linux 2.6.28, these array devices are in fact partitionable).

So it sounds like "yes", that's the default? I'm not an expert.

Let me know if there's something specific I should check for.

**Comment by caldwell** [comment] 2024-04-08 19:01
That's fair enough—I appreciate you looking at it regardless. As a workaround, is it enough to just `systemctl mask efi.automount`--will that work for generated units?

**Comment by poettering** [comment] 2024-10-18 12:28
> That's fair enough—I appreciate you looking at it regardless. As a workaround, is it enough to just `systemctl mask efi.automount`--will that work for generated units?

 yes.

Anyway, closing, as there is nothing actionable for us here.

**Closed as completed by poettering** 2024-10-18 12:28 UTC
Labels: bug 🐛, gpt-auto, not-our-bug, regression ⚠️
