### ISSUE TITLE
(second) systemd-resolved does not keep the order of the DNS servers

### ISSUE THREAD

**Issue by rgrasso2** [systemd/systemd#8353] opened 2018-03-05 06:49 UTC
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 234-2ubuntu12.1

### Used distribution

> Ubuntu 17.10

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

> …

### In case of bug report: Steps to reproduce the problem

> …
Hello,

If you allow me, I would like to add my personal comment on previous issue #5755 : I regret that the behavior of the past contributors has muddled the issue, because on my opinion, the issue itself is worth considering. I am in the same situation as were the various requestors of this past issue, and I unfortunately had to disable systemd-resolved.  This is happening on my small home network.
Now I would just like to add that I work in a software company, and we have had this issue repeatedly : the core issue is : there is occasionally a conflict between the developer's vision, and the user's requests. I would like to set apart any argument, whether somebody is right and somebody else is wrong.  If we kept doing things the way we wanted, we would have lots sales, and we did not want that. So we had to comply with the users requests first, which by the way, were not unreasonable. Adding an option to enable the new features we were proud of seemed to be a good solution.

So may I ask that you reconsider this request of ours too ?

Best regards
Robert Grasso

**Comment by poettering** [comment] 2018-03-21 10:30
Duplicate of #5755

**Closed as completed by poettering** 2018-03-21 10:30 UTC
Labels: resolve, duplicate
