### ISSUE TITLE
machined: make btrfs quota use optional

### ISSUE THREAD

**Issue by wlipa** [systemd/systemd#18421] opened 2021-01-31 00:47 UTC
**systemd version the issue has been seen with**
 > systemd 245 (245.4-4ubuntu3.4)

**Used distribution**
 > Ubuntu 20.04 LTS

**Linux kernel version used** (`uname -a`)
 > `Linux host2 5.4.0-1036-gcp #39-Ubuntu SMP Thu Jan 14 18:41:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Running a machinectl import-tar should leave the btrfs quotas on /var/lib/machine alone.

**Unexpected behaviour you saw**
 > Running a machinectl import-tar turns on btrfs quotas that were previously disabled.

**Steps to reproduce the problem**

    $ sudo btrfs qgroup show /var/lib/machines
    ERROR: can't list qgroups: quotas not enabled

    $ machinectl list-images
    NAME              TYPE      RO USAGE CREATED                     MODIFIED
    ubuntu-18.04      subvolume no   n/a Tue 2021-01-26 17:49:30 PST n/a     
    ubuntu-18.04.orig subvolume no   n/a Thu 2021-01-07 08:15:21 PST n/a     

    2 images listed.

    $ sudo machinectl import-tar /tmp/ubuntu-20.04.tar.gz
    Enqueued transfer job 1. Press C-c to continue download in background.
    Importing '/tmp/ubuntu-20.04.tar.gz', saving as 'ubuntu-20.04'.
    Imported 0%.
    Imported 1%.
    ...
    Imported 99%.
    Imported 100%.
    Operation completed successfully.
    Exiting.

    $ sudo btrfs qgroup show /var/lib/machines
    qgroupid          rfer         excl 
    --------          ----         ---- 
    0/5           16.00KiB     16.00KiB 
    0/18652        1.74GiB    175.21MiB 
    0/18653        1.74GiB    178.14MiB 
    0/18768      696.97MiB    696.97MiB 
    254/18768    696.97MiB    696.97MiB 
    255/5        696.99MiB    696.99MiB 

    $ sudo btrfs quota disable /var/lib/machines

    $ sudo btrfs qgroup show /var/lib/machines
    ERROR: can't list qgroups: quotas not enabled

**Comment by poettering** [comment] 2021-02-02 13:51
Well, this is what machined does: it manages container images for you in /var/lib/machiens, and that includes quota.

We might add an option to disable that automatism, but i am still sure we should by default enable quota for this, before dropping images in there, because once the images are created its nasty to get quota set up for them.

**Comment by wlipa** [comment] 2021-02-02 14:29
If that's the intended behavior, a warning that quotas had been turned back on would be helpful.

I had to disable quotas on /var/lib/machines due to bad performance problems when many short duration nspawn containers are run with the --ephemeral option.  It could even lock up in the kernel.

**Comment by wlipa** [comment] 2021-02-02 18:06
Related to https://github.com/systemd/systemd/issues/15903

**Comment by poettering** [comment] 2021-02-03 20:52
Duplicate of #15903

**Closed as completed by poettering** 2021-02-03 20:52 UTC
Labels: RFE 🎁, machine
