### ISSUE TITLE
Mounting non-rootfs /dev/mapper/foo from /etc/fstab fails when luksOpen happens in initramfs

### ISSUE THREAD

**Issue by jcalvinowens** [systemd/systemd#34683] opened 2024-10-08 22:40 UTC
### systemd version the issue has been seen with

255

### Used distribution

Yocto Scarthgap and Gentoo

### Linux kernel version used

6.6-stable, 6.11, and 6.12-rc2

### CPU architectures issue was seen on

aarch64 and x86_64

### Component

systemd

### Expected behaviour you didn't see

The line in /etc/fstab should cause systemd to mount /dev/mapper/vdb_crypt at /mnt if it is opened in the initramfs.

### Unexpected behaviour you saw

The device is not mounted. Systemd times out with "waiting for /dev/mapper/vdb_crypt", even though the device node exists and can be successfully mounted by hand.

### Steps to reproduce the problem

Example /etc/fstab:

```
    /dev/vda / btrfs defaults 0 2
    /dev/mapper/vdb_crypt /mnt btrfs defaults,nofail 0 2
```

Example initramfs (initially empty `/` except /dev/console and busybox+cryptsetup in /sbin):

```
#!/sbin/busybox sh

set -e
set -x
mkdir -p /bin /etc /run /proc /sys /dev /tmp /newroot
/sbin/busybox --install -s /bin

mount -t tmpfs tmpfs /tmp -o mode=01777
mount -t tmpfs tmpfs /run -o mode=0755
mount -t proc proc /proc -o nosuid,nodev,noexec
mount -t sysfs sysfs /sys -o nosuid,nodev,noexec
mount -t devtmpfs devtmpfs /dev -o nosuid
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts -o nosuid,noexec

echo -n "thisisaverysecurelongpassword" | /sbin/cryptsetup luksOpen \
        -d - --allow-discards \
        /dev/vdb vdb_crypt

mount -t btrfs /dev/vda /newroot -o ro

umount /dev/pts /dev /sys /proc /run /tmp
exec switch_root /newroot /sbin/init
```

A little context: I'm working with a usecase where the cryptsetup keyfile needs to be fetched from a hardware security module, both for the rootfs and for the auxiliary partition. It seemed simpler to just luksOpen them all together, and let /etc/fstab mount the auxiliary ones, but this bug prevents me from doing that.

I'm suspicious that https://github.com/systemd/systemd/commit/c072860593 is implicated, but I haven't had the time to do any investigation yet beyond coming up with the isolated reproducer above. I'll add more info when I know more.

**Comment by yuwata** [comment] 2024-10-08 23:23
Duplicate of #33920 and #33948.

This is not a bug in systemd, but a limitation of device-mapper.
Please use systemd in your initrd.

Or, people workarounds similar issues e.g. like https://github.com/anatol/booster/blob/master/init/udev.go#L251C40-L251C67, though we do not support the workaround. Please do so at your own risk.

Closing.

**Closed as not planned by yuwata** 2024-10-08 23:23 UTC
Labels: pid1, not-supported, duplicate

**Comment by mwilck** [comment] 2024-10-09 14:05
Looking at the workaround in @yuwata's comment, this doesn't work because the device-mapper udev rules see no indication that the device has ever been brought up by LVM cleanly. This would normally be reflected by `DM_UDEV_PRIMARY_SOURCE_FLAG=1` in the udev db. But as you bring up the device while udev isn't running, this udev db entry is not created.

So, @yuwata is right, this is not a supported scenario. The LVM udev rules as shipped by distributions depend on DM_UDEV_PRIMARY_SOURCE_FLAG handling. You can either use a workaround like above (faking the DM_UDEV_PRIMARY_SOURCE_FLAG entry).

For some DM targets, you can reload the existing device-mapper table using dmsetup after switching root (the reload operation would generate a "change" uevent with DM_UDEV_PRIMARY_SOURCE_FLAG set). But AFAICS that doesn't work for crypt targets, because you aren't able to grab the key.

**Comment by jcalvinowens** [comment] 2024-10-09 17:47
Thanks both of you for clarifying.

In case anyone else runs across this, I was able to get this to work as roughly described here: https://github.com/systemd/systemd/issues/33948#issuecomment-230793857

An entry for vdb_crypt in fstab works with this minimal initrd:
```
#!/sbin/busybox sh

set -e
mkdir -p /bin /etc /run /proc /sys /dev /tmp /newroot
/sbin/busybox --install -s /bin

mount -t tmpfs tmpfs /tmp -o mode=01777
mount -t tmpfs tmpfs /run -o mode=0755,nodev,nosuid,strictatime
mount -t proc proc /proc -o nosuid,nodev,noexec
mount -t sysfs sysfs /sys -o nosuid,nodev,noexec
mount -t devtmpfs devtmpfs /dev -o nosuid
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts -o nosuid,noexec

/sbin/systemd-udevd --daemon
udevadm control --ping

echo -n "thisisaverysecurelongpassword" | /sbin/cryptsetup luksOpen \
        -d - --allow-discards /dev/vdb vdb_crypt

udevadm wait --settle /dev/mapper/vdb_crypt

mount -t btrfs /dev/vda /newroot -o ro

udevadm control --exit
umount /dev/pts /dev /sys /proc /tmp
mount --move /run /newroot/run
exec switch_root /newroot /sbin/init
```

**Comment by yuwata** [comment] 2024-10-09 17:51
Yeah, hopefully that should work, and definitely better than faking udev database.

**Comment by madsl** [comment] 2025-02-16 09:43
@jcalvinowens sorry for waking up an old issue, but did this initramfs stop working for you with systemd 257? I'm having trouble again after updating...

**Comment by madsl** [comment] 2025-02-16 12:04
Nevermind, there's so many moving parts here that I don't think this has anything to do with an update. I can't get running systemd-udevd in my initramfs to work properly. It never writes anything into any files in /run/udev/data, it just creates lots of empty files. I guess this is because I don't have a full, proper systemd-udevd working inside the initramfs.

Maybe someone has a guide over what files you need to include in the initramfs to make systemd-udevd work in this barebone way?

Resorted to just hack around the issue by marking the dm device as done like so:

```
# cat /etc/udev/rules.d/99-zoverride.rules 
SUBSYSTEM=="block", KERNEL=="dm-0", ENV{SYSTEMD_READY}="1"
```
