### ISSUE TITLE
systemd-networkd dies when starting a container with machinectl

### ISSUE THREAD

**Issue by mrblumi** [systemd/systemd#34074] opened 2024-08-21 20:21 UTC
### systemd version the issue has been seen with

256.5

### Used distribution

Arch Linux ARM

### Linux kernel version used

6.10.6-1-aarch64-ARCH

### CPU architectures issue was seen on

aarch64

### Component

systemd-networkd

### Expected behaviour you didn't see

When starting a container with `machinectl start test` I'd expect the container spun up, the network interface `ve-test` should be created and configured using the default `80-container-ve.network` file and otherwise the host's `systemd-networkd` should be unaffected.
Please find the kernel and systemd-netword logs attached: 
[journalctl-systemd-networkd.log](https://github.com/user-attachments/files/16698247/journalctl-systemd-networkd.log)
[journalctl-dmesg.log](https://github.com/user-attachments/files/16698248/journalctl-dmesg.log)

### Unexpected behaviour you saw

When starting a container with `machinectl start test` the hosts `systemd-networkd` service dies (and refuses to get started again)
Additionally the container is not pingable from within the host and the host is no longer reachable via IPv6.

### Steps to reproduce the problem

- Have a freshly installed Arch Linux ARM system (on a VPS in my case, but any SBC running Arch Linux ARM with above kernel and systemd versions should do as well)
- create a container, i.e.
```
mkdir /var/lib/machines/test
pacstrap /var/lib/machines/test base
```
- start the container
```
machinectl start test
```

**Comment by yuwata** [comment] 2024-08-21 21:57
Duplicate of https://github.com/systemd/systemd/issues/33775, and it is a bug in the kernel.

Workarounds are
- use 6.9.x or older,
- use 6.10.7 or newer (though, not released yet),
- manually apply the two patches listed at https://github.com/systemd/systemd/issues/33775#issuecomment-2299674964,
- build kernel with CONFIG_INIT_STACK_ALL_ZERO.

Closing.

**Closed as completed by yuwata** 2024-08-21 21:57 UTC
Labels: network, duplicate, kernel-bug
