### ISSUE TITLE
Symlinked /root causes failures

### ISSUE THREAD

**Issue by Metabolix** [systemd/systemd#3953] opened 2016-08-13 11:37 UTC
Submission type: Bug report
systemd version: 231
Used distribution: Arch Linux
### Description:

Symlinking /root to another directory breaks several systemd units (at least systemd-networkd). Completely removing /root works. (The services shouldn't access the real home directory, so why not use some dummy directory instead?)
### Expected behaviour:

Everything works with /root symlinked to /home/root.
### Unexpected behaviour:

```
systemd-netword.service: Failed at step NAMESPACE spawning /usr/lib/systemd/systemd-networkd: Too many levels of symbolic links
systemd-timesyncd.service: Failed at step NAMESPACE spawning /usr/lib/systemd/systemd-networkd: Too many levels of symbolic links
mariadb.service: Failed at step NAMESPACE spawning /bin/sh: Too many levels of symbolic links
```
### Steps to reproduce the problem

```
mv /root /home/root
ln -s home/root /root
sed -i s,:/root:,:/home/root:, /etc/passwd
reboot
# ...
systemctl start systemd-networkd.service
systemctl status systemd-networkd.service
```

**Comment by evverx** [comment] 2016-08-13 11:58
Duplicate of https://github.com/systemd/systemd/issues/3867

**Closed as completed by evverx** 2016-08-13 11:58 UTC
Labels: pid1, duplicate
