### ISSUE TITLE
systemd-run resource accounting missing since v256

### ISSUE THREAD

**Issue by rpigott** [systemd/systemd#33348] opened 2024-06-14 20:53 UTC
### systemd version the issue has been seen with

256-1

### Used distribution

Arch Linux

### Linux kernel version used

6.9.4-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-run

### Expected behaviour you didn't see

```
$ pacman -Q systemd
systemd 255.7-1
$ sudo systemd-run --wait -t --property=MemoryAccounting=1 sleep 1
Running as unit: run-u57.service
Press ^] three times within 1s to disconnect TTY.
Finished with result: success
Main processes terminated with: code=exited/status=0
Service runtime: 1.003s
CPU time consumed: 2ms
Memory peak: 808.0K
Memory swap peak: 0B
```

### Unexpected behaviour you saw

```
$ pacman -Q systemd
systemd 256-1
$ sudo systemd-run --wait -t --property=MemoryAccounting=1 sleep 1
Running as unit: run-u788.service
Press ^] three times within 1s to disconnect TTY.

Finished with result: success
Main processes terminated with: code=exited, status=0/SUCCESS
Service runtime: 1.039s
```

### Steps to reproduce the problem

```
$ sudo systemd-run --wait -t --property=MemoryAccounting=1 sleep 1
```

It seems the MemoryAccounting went missing once already in #28542, but now the CPUTime field has vanished too.

**Comment by YHNdnzj** [comment] 2024-06-14 21:04
Duplicate of #33149 (and will be fixed by #33258)

**Closed as not planned** 2024-06-14 21:10 UTC
Labels: bug 🐛, pid1, run, duplicate
