### ISSUE TITLE
machine: pseudo-terminal owner with machinectl shell

### ISSUE THREAD

**Issue by gdzx** [systemd/systemd#4213] opened 2016-09-25 23:35 UTC
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> systemd 231
> +PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN
### Used distribution

> Arch Linux 4.7.4-2-ck #1 SMP PREEMPT Fri Sep 23 05:58:12 EDT 2016 x86_64 GNU/Linux
### Unexpected behavior

> When using `machinectl shell user@machine`, the owner of the pseudo-terminal is the root user regardless of the user specified (created using `terminal-utils.c:open_terminal`). This behavior breaks applications that expect read/write access to the device (`pinentry` for `gpg-agent` for instance).

```
~ machinectl shell user@test /bin/sh
Connected to machine test. Press ^] three times within 1s to exit session.
~ ls -l `tty`
crw--w---- 1 root tty 136, 0 26.09.2016 01:09 /dev/pts/0
```
### Expected behavior

> When using `machinectl login test`, the owner of the pseudo-terminal is the user who logged in (handled inside the container with getty).

```
~ machinectl login test
Connected to machine test. Press ^] three times within 1s to exit session.

Arch Linux 4.7.4-2-ck (pts/0)

test login: user
Password: 
Last login: Mon Sep 26 00:40:36 on pts/0
~ ls -l `tty`
crw------- 1 user tty 136, 0 26.09.2016 01:15 /dev/pts/0
```

> In the case of `machinectl shell user@machine`, changing the owner from root to the specified user solves the issue with applications like `pinentry` and brings consistent behavior between `machinectl login` and `machinectl shell`.

**Comment by poettering** [comment] 2016-10-07 13:36
duplicate of #4260. (or actually that one is a duplicate of this one, but either way we only need to track one)

**Closed as completed** 2016-10-07 13:36 UTC
Labels: nspawn, machine, duplicate
