### ISSUE TITLE
Resume fails with GPT automount, TPM2 encrypted swap device

### ISSUE THREAD

**Issue by cvlc12** [systemd/systemd#35328] opened 2024-11-23 16:11 UTC
### systemd version the issue has been seen with

256.8-1

### Used distribution

Arch

### Linux kernel version used

6.11.9

### CPU architectures issue was seen on

None

### Expected behaviour you didn't see

```
nvme0n1       259:3    0 931,5G  0 disk  
├─nvme0n1p1   259:4    0   300M  0 part  
├─nvme0n1p2   259:5    0    16G  0 part  
│ └─swap      254:2    0    16G  0 crypt [SWAP]
└─nvme0n1p3   259:6    0 915,2G  0 part  
  └─root      254:0    0 915,2G  0 crypt /
```
Both root and swap are LUKS encrypted, bound to (the same) TPM policy. Both are automatically discovered and mouted fine.

When hibernating though, resume times out waiting for the swap device and fails to restore the session:
```
systemd[1]: Timed out waiting for device /dev/disk/by-uuid/15bd4e69-3a13-4b32-b82a-153e5016cf34.
```
Shouldn't the swap space that the system hibernated into also be automatically discovered and mounted when resuming too?

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Arch specific initramfs configuration:

# cat /etc/mkinitcpio.conf.d/00.conf 
MODULES=(btrfs)
HOOKS=(systemd autodetect microcode modconf kms keyboard sd-vconsole sd-encrypt block)
```
```

**Comment by YHNdnzj** [comment] 2024-11-23 16:44
> Shouldn't the swap space that the system hibernated into also be automatically discovered and mounted when resuming too?

We can't assume anything about the backing storage hierarchy of the swap space? Similarly it's impossible to automatically "discover" LUKS devs from fstab. It needs to be explicitly configured to be unlocked in initrd really.

**Comment by YHNdnzj** [comment] 2024-11-25 09:11
> I'm confused, in this setup, without swap encryption the system resumes properly. And with encryption, the swap partition is automatically decrypted and mounted during normal boot.
> 
> What prevents it to be decrypted in initrd before resume uses it?

Ah, I guess you're actually referring to gpt-auto? Then this is a duplicate of #20355, and indeed currently we only detect auxiliary partitions after switching root.

**Comment by YHNdnzj** [comment] 2024-12-06 18:51
> Is there any particular reason for not auto mounting swap partitions in initrd along with / or /usr ? Or is just not implemented yet ?

The options (discard, prio) specified in fstab need to be honored somehow (#6192). For proper mounts `systemd-remount-fs.service` would remount stuff to apply them after switching root, but kernel doesn't have any equivalent for swap spaces.

**Comment by YHNdnzj** [comment] 2024-12-06 22:56
> > The options (discard, prio) specified in fstab need to be honored somehow (#6192). For proper mounts `systemd-remount-fs.service` would remount stuff to apply them after switching root, but kernel doesn't have any equivalent for swap spaces.
> 
> Well in the case of gpt automount, there precisely is no fstab entry anyway 🤷

You wouldn't know if gpt-auto already tries to swapon in initrd...

**Comment by YHNdnzj** [comment] 2024-12-06 22:58
I.e. it's OK to have gpt-auto mount /sysroot/ in initrd, but still having a fstab entry in real root containing different mount options, given systemd-remount-fs.service will take care of that later. But we simply have no mechanism to live refresh swap options

**Comment by YHNdnzj** [comment] 2024-12-08 14:31
See https://github.com/systemd/systemd/issues/27247#issuecomment-2526037748 where a pretty comprehensive explanation of the situation and path forward is described. I'd close this one as duplicate, and focus the discussion there.

**Closed as completed by YHNdnzj** 2024-12-08 14:31 UTC
Labels: RFE 🎁, gpt-auto, duplicate, hibernate-resume
