### ISSUE TITLE
hostnamectl allows hostnames ending with `.local`.

### ISSUE THREAD

**Issue by martins-1992** [systemd/systemd#20678] opened 2021-09-08 21:36 UTC
**systemd version the issue has been seen with**
 > systemd 245 (245.4-4ubuntu3.11)

**Used distribution**
 > Ubuntu 20.04.3 LTS

**Linux kernel version used** (`uname -a`)

 > Linux splitcells-XPS-15-9570 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x64

**Expected behaviour you didn't see**
 >  Changing hostname to something ending with `.local` should result in an error or at least warning,
 > because `local` is a reserved domain name.

**Unexpected behaviour you saw**
 > I killed **all** WLAN connections of my router, by changing the hostname of my laptop to `splitcells-XPS-15-9570.local`.
 > This could only be fixed by removing the `.local` suffix from the laptop's hostname (I am using mDNS).
 > I assume other hardware would have similar issues, so I assume that may be a problem for others as well.

**Steps to reproduce the problem**
 > Change the hostname to something that ends with `.local` like `sudo hostnamectl set-hostname splitcells-XPS-15-9570.local`.

**Additional program output to the terminal or log subsystem illustrating the issue**

I can test it again, if needed, and create some logs.

**Comment by poettering** [comment] 2021-09-13 13:21
Not sure I follow, but I see no reason why setting your domain name to `splitcells-XPS-15-9570.local` woud be problematic? Why precisely should we disallow that?

I mean, i personally think setting the host's domain name to an fqdn is a bad idea, but it's not that this is something we wouldn't support. Hence, I don't follow why you think this should be forbidden?

**Comment by splitcells** [comment] 2021-09-14 07:23
To make it clear: I'm not a network guy and I probably stated the unexpected behaviour with too much authority ^^'
This is no bug in systemd.

> I mean, i personally think setting the host's domain name to an fqdn is a bad idea, but it's not that this is something we wouldn't support. 
I was not talking about fqdn in general, because I thought the `.local` domain was special and will cause further problems down the line,
which are hard to debug.

> Hence, I don't follow why you think this should be forbidden?
I thought that network devices/programs in general may have problems with such hostnames.
Not allowing something like that in general is probably a bad idea,
and breaks the API (also something like a `--force` option could be used).

I just thought, that echoing a warning in such cases (only for .local) may be a nice comfort function.

**Comment by poettering** [comment] 2021-09-29 09:02
So, let's close this. I think using a `.local` fqdn as local hostname is not a great idea, but still something that should work. If you actually run into problems with this, and there's something to fix, please open a bug then. Until then, let's close this.

**Closed as completed by poettering** 2021-09-29 09:02 UTC
Labels: needs-reporter-feedback ❓, hostname
