### ISSUE TITLE
`IOAccounting` in transient unit file not honored

### ISSUE THREAD

**Issue by cdoern** [systemd/systemd#24037] opened 2022-07-15 16:04 UTC
### systemd version the issue has been seen with

systemd 249 (v249.12-5.fc35)

### Used distribution

Fedora 35

### Linux kernel version used

5.18.5-100.fc35.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

```
systemctl show user-libpod_pod_dec3f089af400c6a1f4c52964c42693021055d7e795e4b785bf980e1886313c5 | grep IOAccounting
IOAccounting=**yes**
BlockIOAccounting=no
```

### Unexpected behaviour you saw

unit file: 

```
# This is a transient unit file, created programmatically via the systemd API. Do not edit.
[Unit]
Description=cgroup user-libpod_pod_dec3f089af400c6a1f4c52964c42693021055d7e795e4b785bf980e1886313c5.slice
Wants=user.slice
DefaultDependencies=no

[Slice]
MemoryAccounting=yes
CPUAccounting=yes
IOAccounting=yes
IODeviceWeight=
IODeviceWeight=/dev/block/1:3 123
```
terminal output

```
systemctl show user-libpod_pod_dec3f089af400c6a1f4c52964c42693021055d7e795e4b785bf980e1886313c5 | grep IOAccounting
IOAccounting=no
BlockIOAccounting=no
```

```
systemctl show user-libpod_pod_dec3f089af400c6a1f4c52964c42693021055d7e795e4b785bf980e1886313c5 | grep IOWeight
IOWeight=[not set]
StartupIOWeight=[not set]
BlockIOWeight=[not set]
StartupBlockIOWeight=[not set]
```

### Steps to reproduce the problem

use `StartTransientUnit` and pass it dbus properties, two of which are `IOAccounting=true` and `IODeviceWeight = /dev/block/major:minor`

**Comment by anitazha** [comment] 2022-08-05 00:19
I wasn't able to reproduce and I'm also running v249.12-5.fc35:
```
$ sudo systemd-run -p IOAccounting=yes -p IODeviceWeight="/dev/block/1:3 123" sleep infinity
Running as unit: run-r470c1cb832e04498a1beac808721a345.service
$ systemctl show run-r470c1cb832e04498a1beac808721a345.service -p IOAccounting -p IODeviceWeight
IOAccounting=yes
IODeviceWeight=/dev/block/1:3 123
```

systemd-run uses `StartTransientUnit`. Is there a step I'm missing?

**Comment by poettering** [comment] 2022-08-10 12:41
Dropping from milestone, since it's not clear whether there's actually any bug here.

@cdoern, can you retry with 251?

**Comment by Werkov** [comment] 2023-02-23 10:35
The reported transient unit is a .slice but the checking show command won't specify unit type, i.e. defaults to .service and there's no such service, so show command shows default `IOAccounting=no`.

To falsify the claim above:
```
systemctl show -p LoadState $unit_name
```

I think this is a bogus report, thus I'm closing this (and I can't reproduce neither with systemd-252.5).

**Closed as completed by Werkov** 2023-02-23 10:35 UTC
Labels: bug 🐛, cgroups, pid1, needs-reporter-feedback ❓
