### ISSUE TITLE
meson: should default to LTO again

### ISSUE THREAD

**Issue by eworm-de** [systemd/systemd#6371] opened 2017-07-14 15:46 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

> v234

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> Similar binary sizes compared to auto-tools build.

### In case of bug report: Unexpected behaviour you saw

> Building with meson increases installed package size by about 10MB (+50%). This hits binary sizes for executables and libraries.

### In case of bug report: Steps to reproduce the problem

> Build with meson and auto-tools and compare sizes.

**Comment by eworm-de** [comment] 2017-07-14 15:58
Cc @falconindy

**Comment by mbiebl** [comment] 2017-07-14 16:08
have you enabled lto? Try building with ```-Db_lto=true```

**Comment by mbiebl** [comment] 2017-07-14 16:41
@eworm-de The build sizes are comparable on Debian. But then we do enable lto and use a non-debug build which enables gc-sections: https://github.com/systemd/systemd/blob/master/meson.build#L327

That said, the meson build is indeed a bit larger here as well, but not by 50%, more like 0.5M

**Comment by keszybz** [comment] 2017-07-14 17:13
In Fedora, the meson build comes out larger as well:
```python
import pandas as pd
import subprocess
import io
import sys

def read(fname):
    ls = subprocess.check_output(['rpm', '-qp', '--qf=[%8{filesizes} %{filenames}\n]', '--nodigest', '--nosignature', fname], universal_newlines=True)
    df = pd.read_csv(io.StringIO(ls), index_col=1, sep=r'\s+', names=('size', 'name'), dtype={'size':int})
    return df

df1 = read(sys.argv[1])
df2 = read(sys.argv[2])
diff = df2 - df1
diff.dropna(inplace=True)
diff.sort_values('size', inplace=True)
print(diff)
```
```
                                                        size
name                                                        
/usr/lib/systemd/systemd-shutdown                    -4504.0
/usr/bin/systemd-cgtop                               -4504.0
/usr/lib/systemd/systemd-fsck                        -4432.0
/usr/bin/systemd-path                                -4416.0
/usr/lib/systemd/system-generators/systemd-debu...   -4408.0
/usr/bin/systemd-notify                              -4408.0
/usr/lib/systemd/systemd-journald                     -432.0
/usr/lib/systemd/systemd-sysctl                       -424.0
/usr/bin/systemd-delta                                -424.0
/usr/bin/systemd-tmpfiles                             -424.0
/usr/bin/systemd-sysusers                             -416.0
/usr/bin/busctl                                       -416.0
/usr/lib/systemd/system-generators/systemd-sysv...    -416.0
/usr/lib/systemd/systemd-networkd-wait-online         -408.0
/usr/lib/systemd/systemd-coredump                     -408.0
/usr/bin/localectl                                    -408.0
/usr/bin/journalctl                                   -408.0
/usr/lib/systemd/systemd-remount-fs                   -400.0
/usr/lib/systemd/systemd-timedated                    -392.0
/usr/lib/systemd/system-generators/systemd-fsta...    -392.0
/usr/bin/loginctl                                     -336.0
/usr/lib/systemd/systemd-volatile-root                -336.0
/usr/lib/systemd/user-environment-generators/30...    -328.0
/usr/bin/systemd-cat                                  -328.0
/usr/bin/systemd-cgls                                 -328.0
/usr/bin/systemd-socket-activate                      -328.0
/usr/bin/systemd-escape                               -328.0
/usr/bin/systemd-firstboot                            -328.0
/usr/lib/systemd/system-generators/systemd-syst...    -328.0
/usr/bin/systemd-machine-id-setup                     -328.0
...                                                      ...
/usr/share/man/man5/systemd.mount.5.gz                 182.0
/usr/share/man/man1/systemd-mount.1.gz                 185.0
/usr/lib/systemd/system/getty@.service                 190.0
/usr/lib/systemd/system/console-getty.service          190.0
/usr/lib/systemd/system/container-getty@.service       190.0
/usr/share/man/man8/systemd-fstab-generator.8.gz       194.0
/usr/share/man/man5/systemd.service.5.gz               245.0
/usr/share/polkit-1/actions/org.freedesktop.tim...     263.0
/usr/share/man/man1/networkctl.1.gz                    289.0
/usr/share/locale/sv/LC_MESSAGES/systemd.mo            314.0
/usr/lib/systemd/system/serial-getty@.service          391.0
/usr/lib/systemd/system/systemd-coredump@.service      406.0
/usr/share/polkit-1/actions/org.freedesktop.loc...     438.0
/usr/share/man/man5/systemd.unit.5.gz                  446.0
/usr/share/man/man5/systemd.target.5.gz                471.0
/usr/share/man/man5/systemd.network.5.gz               539.0
/usr/share/man/man5/systemd.exec.5.gz                  547.0
/usr/share/man/man5/systemd.netdev.5.gz                566.0
/usr/share/polkit-1/actions/org.freedesktop.hos...     706.0
/usr/share/doc/systemd/README                         1054.0
/usr/share/polkit-1/actions/org.freedesktop.sys...    1847.0
/usr/lib/systemd/systemd-logind                       3880.0
/usr/share/polkit-1/actions/org.freedesktop.log...    4134.0
/usr/share/locale/pt_BR/LC_MESSAGES/systemd.mo        5944.0
/usr/share/doc/systemd/NEWS                           7334.0
/usr/bin/systemd-mount                                7984.0
/usr/lib/systemd/systemd-resolved                    12240.0
/usr/lib/systemd/systemd-networkd                    53864.0
/usr/bin/systemd-analyze                            382048.0
/usr/lib/systemd/systemd                            485224.0
```
That includes lto and gc-sections. Looks like something to fix.

**Comment by eworm-de** [comment] 2017-07-14 18:01
Looks like link time optimization did the trick! (I thought it was enabled by default...)
Packages built with LTO are even 20KiB smaller.

@keszybz do you want to keep this open?

**Comment by poettering** [comment] 2019-02-26 15:16
Let's convert this into a bug about requesting to default to LTO again, if this is what the issue is.

**Comment by keszybz** [comment] 2019-02-26 17:16
I think there's nothing to fix. We do not specify "release" configuration flags at all. For distro packages, you want stuff like `-O2` or `-O3`, `-Db_lto=true`, `-Wp,-D_FORTIFY_SOURCE=2`, `-fstack-protector-strong`, etc. We could try to specify a "sane default" for release flags, but setting just some subset is not useful imho. I'd be inclined to just close this.

**Comment by poettering** [comment] 2019-02-26 17:24
Well, but the way our package is set up LTO is kinda important, as we link the same stuff into plenty individual binaries all the time, still. 

Maybe at least print a warning if LTO is not on?

**Comment by floppym** [comment] 2019-02-26 17:30
Please don't try to override meson's default values for this stuff. I'm not sure if that's even possible, but it would certainly make things less predictable for people who build lots of different packages.

I would suggest documenting your recommended settings somewhere in the repo (README?), and possibly update the "configure" shell script.

**Closed as completed** 2019-03-05 12:58 UTC
Labels: meson
