### ISSUE TITLE
Systemd fails to mount LVM swap when initrd without systemd

### ISSUE THREAD

**Issue by desultory** [systemd/systemd#33920] opened 2024-08-03 17:29 UTC
### systemd version the issue has been seen with

255

### Used distribution

Fedora, Debian, Ubuntu, Gentoo

### Linux kernel version used

various

### CPU architectures issue was seen on

x86_64

### Component

systemctl, systemd

### Expected behaviour you didn't see

Swap is mounted, the system boots

### Unexpected behaviour you saw

systemd hangs looking for the udev device path for the lvm mount, even though it's mapped, and in the fstab. The swap is not activated

### Steps to reproduce the problem

boot without udev, mount lvm volumes using lvm tools.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
[  OK  ] Found device dev-ttyS0.device - /dev/ttyS0.
[  OK  ] Found device dev-disk-by\x…[0m - /dev/disk/by-uuid/3B58-FB38.
         Starting systemd-fsck@dev-… on /dev/disk/by-uuid/3B58-FB38...
[  OK  ] Found device dev-disk-by\x…1cd04-9665-45c3-806f-4efac215cb86.
[  OK  ] Found device dev-disk-by\x…df152-6dd9-4663-9b55-1d8530278433.
         Starting systemd-cryptsetu…yptography Setup for vda3_crypt...
         Starting systemd-fsck@dev-…152-6dd9-4663-9b55-1d8530278433...
[  OK  ] Started plymouth-start.ser…e - Show Plymouth Boot Screen.
[  OK  ] Started systemd-ask-passwo…uests to Plymouth Directory Watch.
[  OK  ] Finished systemd-cryptsetu…Cryptography Setup for vda3_crypt.
[  OK  ] Reached target blockdev@de…ration for /dev/mapper/vda3_crypt.
[  OK  ] Reached target cryptsetup.…get - Local Encrypted Volumes.
[   10.213056] virtio_net virtio1 enp1s0: renamed from eth0
fsckd-cancel-msg:Press Ctrl+C to cancel all filesystem checks in progress
[  OK  ] Finished systemd-fsck@dev-…ck on /dev/disk/by-uuid/3B58-FB38.
[   10.228012] iTCO_vendor_support: vendor-support=0
[   10.231767] input: PC Speaker as /devices/platform/pcspkr/input/input5
[   10.237732] i801_smbus 0000:00:1f.3: SMBus using PCI interrupt
[   10.239214] i2c i2c-0: 1/1 memory slots populated (from DMI)
[   10.239660] i2c i2c-0: Memory type 0x07 not supported yet, not instantiating SPD
[   10.253595] iTCO_wdt iTCO_wdt.1.auto: Found a ICH9 TCO device (Version=2, TCOBASE=0x0660)
         Starting modprobe@dm_mod.s…[0m - Load Kernel Module dm_mod...
         Starting modprobe@efi_psto…- Load Kernel Module efi_pstore...
         Starting modprobe@loop.ser…e - Load Kernel Module loop...
Checking in pro[   10.295626] iTCO_wdt iTCO_wdt.1.auto: initialized. heartbeat=30 sec (nowayout=0)
[  OK  ] Finished modprobe@dm_mod.s…e - Load Kernel Module dm_mod.
[  OK  ] Finished modprobe@efi_psto…m - Load Kernel Module efi_pstore.
[  OK  ] Finished modprobe@loop.service - Load Kernel Module loop.
Checking in progress on 0 disks (100.0% complete)
[  OK  ] Finished systemd-fsck@dev-…df152-6dd9-4663-9b55-1d8530278433.
         Mounting boot.mount - /boot...
[   10.314259] EXT4-fs (vda2): mounting ext2 file system using the ext4 subsystem
[   10.315694] EXT4-fs (vda2): mounted filesystem without journal. Quota mode: none.
[  OK  ] Mounted boot.mount - /boot.
[   10.387366] SVM: TSC scaling supported
[   10.387732] kvm: Nested Virtualization enabled
[   10.388046] SVM: kvm: Nested Paging enabled
[   10.388338] SVM: Virtual VMLOAD VMSAVE supported
[   10.388661] SVM: Virtual GIF supported
[   10.388922] SVM: LBR virtualization supported
[   10.407857] snd_hda_codec_generic hdaudioC0D0: autoconfig for Generic: line_outs=1 (0x3/0x0/0x0/0x0/0x0) type:line
[   10.408570] snd_hda_codec_generic hdaudioC0D0:    speaker_outs=0 (0x0/0x0/0x0/0x0/0x0)
[   10.409131] snd_hda_codec_generic hdaudioC0D0:    hp_outs=0 (0x0/0x0/0x0/0x0/0x0)
[   10.409645] snd_hda_codec_generic hdaudioC0D0:    mono: mono_out=0x0
[   10.410085] snd_hda_codec_generic hdaudioC0D0:    inputs:
[   10.410457] snd_hda_codec_generic hdaudioC0D0:      Line=0x5
         Starting modprobe@dm_mod.s…[0m - Load Kernel Module dm_mod...
         Starting modprobe@efi_psto…- Load Kernel Module efi_pstore...
         Starting modprobe@loop.ser…e - Load Kernel Module loop...
[  OK  ] Finished modprobe@dm_mod.s…e - Load Kernel Module dm_mod.
[  OK  ] Finished modprobe@loop.service - Load Kernel Module loop.
[  OK  ] Finished modprobe@efi_psto…m - Load Kernel Module efi_pstore.
         Mounting boot-efi.mount - /boot/efi...
[  OK  ] Mounted boot-efi.mount - /boot/efi.
[  OK  ] Reached target local-fs.target - Local File Systems.
         Starting apparmor.service - Load AppArmor profiles...
         Starting console-setup.ser…m - Set console font and keymap...
         Starting plymouth-read-wri…mouth To Write Out Runtime Data...
         Starting systemd-binfmt.se…et Up Additional Binary Formats...
         Starting systemd-tmpfiles-… Volatile Files and Directories...
[  OK  ] Finished console-setup.ser…[0m - Set console font and keymap.
         Mounting proc-sys-fs-binfm…utable File Formats File System...
[  OK  ] Mounted proc-sys-fs-binfmt…ecutable File Formats File System.
[  OK  ] Finished systemd-binfmt.se… Set Up Additional Binary Formats.
[   11.113851] audit: type=1400 audit(1722706086.692:2): apparmor="STATUS" operation="profile_load" profile="unconfined" name="libreoffice-senddoc" pid=993 comm="apparmor_parser"
[   11.115269] audit: type=1400 audit(1722706086.692:3): apparmor="STATUS" operation="profile_load" profile="unconfined" name="libreoffice-oosplash" pid=992 comm="apparmor_parser"
[   11.116503] audit: type=1400 audit(1722706086.692:4): apparmor="STATUS" operation="profile_load" profile="unconfined" name="nvidia_modprobe" pid=988 comm="apparmor_parser"
[   11.116505] audit: type=1400 audit(1722706086.692:5): apparmor="STATUS" operation="profile_load" profile="unconfined" name="nvidia_modprobe//kmod" pid=988 comm="apparmor_parser"
[   11.116507] audit: type=1400 audit(1722706086.692:6): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/bin/man" pid=991 comm="apparmor_parser"
[   11.116509] audit: type=1400 audit(1722706086.692:7): apparmor="STATUS" operation="profile_load" profile="unconfined" name="man_filter" pid=991 comm="apparmor_parser"
[   11.116510] audit: type=1400 audit(1722706086.692:8): apparmor="STATUS" operation="profile_load" profile="unconfined" name="man_groff" pid=991 comm="apparmor_parser"
[   11.116512] audit: type=1400 audit(1722706086.692:9): apparmor="STATUS" operation="profile_load" profile="unconfined" name="lsb_release" pid=987 comm="apparmor_parser"
[   11.116513] audit: type=1400 audit(1722706086.692:10): apparmor="STATUS" operation="profile_load" profile="unconfined" name="libreoffice-xpdfimport" pid=995 comm="apparmor_parser"
[   11.116812] audit: type=1400 audit(1722706086.692:11): apparmor="STATUS" operation="profile_load" profile="unconfined" name="/usr/sbin/cups-browsed" pid=996 comm="apparmor_parser"
[  OK  ] Finished systemd-tmpfiles-…te Volatile Files and Directories.
[  OK  ] Finished plymouth-read-wri…lymouth To Write Out Runtime Data.
         Starting systemd-timesyncd… - Network Time Synchronization...
         Starting systemd-update-ut…rd System Boot/Shutdown in UTMP...
[  OK  ] Finished systemd-update-ut…cord System Boot/Shutdown in UTMP.
[  OK  ] Started systemd-timesyncd.…0m - Network Time Synchronization.
[  OK  ] Reached target time-set.target - System Time Set.
[  OK  ] Finished apparmor.service - Load AppArmor profiles.
         Starting networking.service - Raise network interfaces...
[  OK  ] Finished networking.service - Raise network interfaces.
```

**Comment by yuwata** [comment] 2024-08-04 01:58
> boot without udev

Huh? You disable systemd-udevd?? That's not supported.

**Comment by desultory** [comment] 2024-08-04 04:14
> > boot without udev
> 
> Huh? You disable systemd-udevd?? That's not supported.

I did not disable anything. I simply booted and activated LVM stuff with no udev running. I'm making an initramfs system which does not depend on udev.

**Comment by yuwata** [comment] 2024-08-04 04:27
udevd is necessary in initrd to support such setup.

**Comment by desultory** [comment] 2024-08-04 04:42
> udevd is necessary in initrd to support such setup.

I don't see why? it works fine without it, other than systemd failing to find the /dev/disk uuid.

I'm basing this on the debian/fedora installers which add fstab entries for the swap.

There is no reason for me to include udev in my system as it doesn't need anything dynamic.

Is there some way systemd could see udev was not used pre-boot and accommodate?

**Comment by yuwata** [comment] 2024-08-04 05:35
- Is sysroot also on LVM? Or, only swap is on LVM?
- Is udevd disabled only in initrd phase?
- boot process hang in initrd phase? Or after switching root?

Please provide the fstab file.

**Comment by yuwata** [comment] 2024-08-04 05:43
fstab is converted to systemd .mount and .swap units in both initrd phase and after switching root. And, starting swap unit requires underlying device is processed by udevd.

Maybe, we should add `rd.systemd.swap=BOOL` kernel command line option to allow delaying configuring swap in initrd.

**Comment by desultory** [comment] 2024-08-04 05:56
> * Is sysroot also on LVM? Or, only swap is on LVM?
> 
>     * Is udevd disabled only in initrd phase?
> 
>     * boot process hang in initrd phase? Or after switching root?
> 
> 
> Please provide the fstab file.
![image](https://github.com/user-attachments/assets/c6275f12-dbd1-46c2-b98d-035aef14adaa)

The initrd works fine, the system I made autodetects LUKS/LVM stuff: https://github.com/desultory/ugrd

The issue is that after it does a switch_root and passes things off to systemd, it stalls and I have to manually mount the swap. This issue seems to only occur when LVM swap is used.

I don't typically use systemd, so I'm not sure how those units are created/used, but my intrd system makes a simple bash script to mount things, and it works properly. The "issue" is that it does not use udev, and I think systemd is timing out looking for udev device nodes, when those are not made. I think if something re-triggerd udev shortly after systemd init's, that could fix things. I just don't think it makes sense to add udev to an initramfs, when it's only a systemd requirement, and `swapon -a` works fine without that. It seems like an added check that only causes problems. I can understand preferring udev device ids, but if `swapon -a` works, why do more?

**Comment by YHNdnzj** [comment] 2024-08-04 06:03
> Maybe, we should add rd.systemd.swap=BOOL kernel command line option to allow delaying configuring swap in initrd.

According to the provided info, systemd/fstab-generator doesn't run in initrd at all. And I'm really not convinced by this kind of setup...

**Comment by yuwata** [comment] 2024-08-04 06:03
So, udevd is running after switching root, right?

**Comment by YHNdnzj** [comment] 2024-08-04 06:04
> I can understand preferring udev device ids, but if swapon -a works, why do more?

Sorry, but systemd is not a shell script, and we need to correctly order deps and track/propagate states when they go down. As mentioned, udev-less is not supported.

**Comment by desultory** [comment] 2024-08-04 06:07
> So, udevd is running after switching root, right?

i think so:
![image](https://github.com/user-attachments/assets/8f485776-838f-464a-b1a2-f6d8b1df5330)



> > I can understand preferring udev device ids, but if swapon -a works, why do more?
> 
> Sorry, but systemd is not a shell script, and we need to correctly order deps and track/propagate states when they go down. As mentioned, udev-less is not supported.

udev us not being run in the initrfams, the initramfs does not run system. it runs a simple shell script that gets the root mounted and does switch_root into that rootfs with the init.

At this point in time, ugrd does not handle swap activation. For most of my use cases, i uses zram-init for zram swap, or dmcrypt for encrpyted swap. both are done by the main init system,  not in the initramfs

**Comment by yuwata** [comment] 2024-08-04 06:14
Could you show result of `systemctl cat xxx.swap`, `systemctl status xxx.swap`, and `systemctl show xxx.swap` ? The name of the swap unit should be found in `systemctl list-units`, I hope.

One more thing. The swap is enabled by the initrd script? That is, `swapon` is called in initrd?

**Comment by desultory** [comment] 2024-08-04 06:18
> Could you show result of `systemctl cat xxx.swap`, `systemctl status xxx.swap`, and `systemctl show xxx.swap` ? The name of the swap unit should be found in `systemctl list-units`, I hope.
> 
> One more thing. The swap is enabled by the initrd script? That is, `swapon` is called in initrd?

it is not, the initrd ignores the swap. it exists only to get the rootfs mounted, and switch root. I could make it mount lvm swap stuff, but i think it makes more sense to let the main init system do that, if it can.

I'm trying to adhere strictly to the design philosophy of "the initramfs exists to mount the rootfs", no more, no less. It currently has mechanisms for mounting the swap, but they have to be manually configure by the user. I think the best user experience is one where the initramfs has a simple purpose and there is not confusion about where things are initialized. It should be clear that the main init system sets up most of your fstab stuff, and swap, and that your initramfs does it if you explicitly tell it to. I think it's a bug that systemd has a hard requirement that lvm stuff is setup with udev pre-boot, especially when `swapon -a` works.

**Comment by yuwata** [comment] 2024-08-04 06:31
Hm? Now the swap unit is 'active'. Did you manually start the swap?
Anyway, please provide the result of `systemctl cat`, `status`, and `show` for the swap unit.

**Comment by desultory** [comment] 2024-08-04 06:32
> Hm? Now the swap unit is 'active'. Did you manually start the swap? Anyway, please provide the result of `systemctl cat`, `status`, and `show` for the swap unit.

the swap was started with "swapon -a", I can reboot it and show the output before I run that.

**Comment by yuwata** [comment] 2024-08-04 06:32
> > Hm? Now the swap unit is 'active'. Did you manually start the swap? Anyway, please provide the result of `systemctl cat`, `status`, and `show` for the swap unit.
> 
> the swap was started with "swapon -a", I can reboot it and show the output before I run that.

OK. Then, please reboot and provide the results.

**Comment by desultory** [comment] 2024-08-04 06:33
![image](https://github.com/user-attachments/assets/70ff1e1e-832c-47c2-9de5-84cd68b62c8e)
![image](https://github.com/user-attachments/assets/66dc02d8-f22e-4886-9ce6-b29722ea7233)
pre-reboot

**Comment by yuwata** [comment] 2024-08-04 06:44
Thanks.
Please reboot with `systemd.log_level=debug` kernel command line option, and provide the file generated with `journalctl --no-hostname -b > /tmp/journal.txt`.

**Comment by desultory** [comment] 2024-08-04 06:46
> Thanks. Please reboot with `systemd.log_level=debug` kernel command line option, and provide the file generated with `journalctl --no-hostname -b > /tmp/journal.txt`.

should that kernel command line be passed to the init? or will systemd read /proc/cmdline to get that?

**Comment by desultory** [comment] 2024-08-04 06:59
[Uploading XOdo.txt…]()

**Comment by yuwata** [comment] 2024-08-04 07:01
The link is broken...

**Comment by desultory** [comment] 2024-08-04 07:01
https://0x0.st/XOdo.txt

**Comment by yuwata** [comment] 2024-08-04 07:03
The journal only contains user journal. Please rerun journalctl with `sudo`.

**Comment by desultory** [comment] 2024-08-04 07:04
> The journal only contains user journal. Please rerun `journalctl` with `sudo`.

[XOdP.txt](https://github.com/user-attachments/files/16486574/XOdP.txt)

**Comment by yuwata** [comment] 2024-08-04 07:07
Thanks. I will take a look.

**Comment by desultory** [comment] 2024-08-04 07:07
thank you

**Comment by yuwata** [comment] 2024-08-04 07:36
Hm, for some reasons, udevd does not add symlink `/dev/mapper/$env{DM_NAME}`. Hence, PID1 handles that the block device is not ready, and the swap unit and all units which depend on the swap are stuck.

So, this is not an issue in systemd or udevd, but should be caused by the LVM project, as the udev rules for LVM volume is provided by the LVM project. Please open a new issue at https://github.com/lvmteam/lvm2 with linking with this issue page.

Note, of course, a workaround for the issue is setting `noauto` option to the swap volume in fstab, and calling `swapon` manually.

Closing.

**Closed as not planned by yuwata** 2024-08-04 07:36 UTC
Labels: udev, pid1, not-our-bug

**Comment by yuwata** [comment] 2024-08-04 07:39
Just for record, the following lines in the provided journal suggest that the issue is in udev rules provided by LVM.
```
$ cat XOdP.txt | grep dm-2
Aug 04 01:52:46 systemd-udevd[801]: dm-2: Device is queued (SEQNUM=1479, ACTION=add)
Aug 04 01:52:46 systemd-udevd[801]: dm-2: Device ready for processing (SEQNUM=1479, ACTION=add)
Aug 04 01:52:46 (udev-worker)[807]: dm-2: Processing device (SEQNUM=1479, ACTION=add)
Aug 04 01:52:46 (udev-worker)[807]: dm-2: Removing watch handle -1.
Aug 04 01:52:46 (udev-worker)[807]: dm-2: /usr/lib/udev/rules.d/50-udev-default.rules:85 GROUP 6
Aug 04 01:52:46 systemd-udevd[801]: dm-2: sd-device-monitor(manager): Passed 237 byte to netlink monitor.
Aug 04 01:52:46 (udev-worker)[807]: dm-2: Setting permissions /dev/dm-2, uid=0, gid=6, mode=0660
Aug 04 01:52:46 (udev-worker)[807]: dm-2: Successfully created symlink '/dev/block/254:2' to '/dev/dm-2'
Aug 04 01:52:46 (udev-worker)[807]: dm-2: sd-device: Created db file '/run/udev/data/b254:2' for '/devices/virtual/block/dm-2'
Aug 04 01:52:46 (udev-worker)[807]: dm-2: Device processed (SEQNUM=1479, ACTION=add)
Aug 04 01:52:46 (udev-worker)[807]: dm-2: sd-device-monitor(worker): Passed 399 byte to netlink monitor.
Aug 04 01:52:46 systemd[1]: dm-2: Processing udev action (SEQNUM=1479, ACTION=add)
Aug 04 01:52:46 systemd[1]: dm-2: Device busy: SYSTEMD_READY property from device is false
Aug 04 01:52:46 systemd[1]: dm-2: Device busy: SYSTEMD_READY property from device is false
Aug 04 01:52:46 systemd[1]: dm-2: Device busy: SYSTEMD_READY property from device is false
Aug 04 01:54:16 systemd[1131]: dm-2: Device busy: SYSTEMD_READY property from device is false
Aug 04 01:54:16 systemd[1131]: dm-2: Device busy: SYSTEMD_READY property from device is false
Aug 04 01:54:20 systemd[1597]: dm-2: Device busy: SYSTEMD_READY property from device is false
Aug 04 01:54:20 systemd[1597]: dm-2: Device busy: SYSTEMD_READY property from device is false
```

**Comment by desultory** [comment] 2024-08-04 15:24
> Hm, for some reasons, udevd does not add symlink `/dev/mapper/$env{DM_NAME}`. Hence, PID1 handles that the block device is not ready, and the swap unit and all units which depend on the swap are stuck.
> 
> So, this is not an issue in systemd or udevd, but should be caused by the LVM project, as the udev rules for LVM volume is provided by the LVM project. Please open a new issue at https://github.com/lvmteam/lvm2 with linking with this issue page.
> 
> Note, of course, a workaround for the issue is setting `noauto` option to the swap volume in fstab, and calling `swapon` manually.
> 
> Closing.

I see those entries are created, they just aren't used:
crw-------  1 root root  10, 236 Aug  4 10:21 control
brw-rw----  1 root disk 254,   1 Aug  4 10:21 debian--vg-root
brw-rw----  1 root disk 254,   2 Aug  4 10:21 debian--vg-swap_1
brw-rw----  1 root disk 254,   0 Aug  4 10:21 vda3_crypt

**Comment by yuwata** [comment] 2024-08-05 00:34
I guess, the scenario that causes the issue is something like the following:
1. The lvm volumes are activated without udevd (in initrd, right?), and somehow symlinks /dev/mapper/xxx are created.
2. After switching root, PID1 labels that these block devices are not ready, as udevd not processed them yet.
3. udevd processes the LVM volumes, but for some reasons, the corresponding rules do not request the symlinks.
4. udevd notifies the LVM volumes (dm-x) are ready, but the notifications do not contain about symlinks /dev/mapper/xxx.
5. PID1 still handles /dev/mapper/xxx are not ready yet.

If the above story is correct, the issue should be in the initrd script you use and udev rules provided by LVM.

**Comment by desultory** [comment] 2024-08-05 00:41
> I guess, the scenario that causes the issue is something like the following:
> 
>     1. The lvm volumes are activated without udevd (in initrd, right?), and somehow symlinks /dev/mapper/xxx are created.

I think the symlinks are created because my system runs `vgscan --mknodes`. This was an attempt to try to add the nodes to appease systemd, and this did not work. I left it in because it doesn't seem to harm anything, and I think having the mapped entries makes sense.
> 
>     2. After switching root, PID1 labels that these block devices are not ready, as udevd not processed them yet.
> 
This is my guess as well, it seems it's waiting for udev to add these nodes. It doesn't seem to make the nodes if `vgscan --mknodes` is not used, but still fails. My guess is because it has a hard expectation that udev makes these.
>     3. udevd processes the LVM volumes, but for some reasons, the corresponding rules do not request the symlinks.
> 
FWIW hardlinks are made, or they are converted to hardlinks after switch_root. Not sure how much this matters, but the entries in  /dev/mapper seem totally valid in this form.
>     4. udevd notifies the LVM volumes (dm-x) are ready, but the notifications do not contain about symlinks /dev/mapper/xxx.
> 
>     5. PID1 still handles /dev/mapper/xxx are not ready yet.
> 
Yes, even though the devices are present, some wires are crossed and it's not recognizing them
> 
> If the above story is correct, the issue should be in the initrd script you use and udev rules provided by LVM.

I don't think it makes sense for the initrd to use udev for the sole purpose of making systemd happy _after the initramfs is gone_. The initramfs itself does not need udev, and mounts the root fine without it.

**Comment by yuwata** [comment] 2024-08-05 01:02
> I don't think it makes sense for the initrd to use udev for the sole purpose of making systemd happy after the initramfs is gone. The initramfs itself does not need udev, and mounts the root fine without it.

Yes. You can mount volumes without systemd and udevd in initrd.

**Comment by desultory** [comment] 2024-08-05 01:18
> > I don't think it makes sense for the initrd to use udev for the sole purpose of making systemd happy after the initramfs is gone. The initramfs itself does not need udev, and mounts the root fine without it.
> 
> Yes. You can mount volumes without systemd and udevd in initrd.
Yes, but then systemd seems to fail to recognize them. The only "solution" i know of is to use systemd in the initramfs so it doesn't get confused.

**Comment by yuwata** [comment] 2024-08-05 01:53
> Yes, but then systemd seems to fail to recognize them.

No, the mounted volumes (including manually enabled swap volumes) are correctly recognized. So, systemd itself is OK.
The reason why the swap is not enabled by systemd is that the underlying device is not correctly processed by udevd.
I have no idea what udev rules provided by LVM and device-mapper do. The issue should be solved by the provider of the rules.

**Comment by desultory** [comment] 2024-08-05 15:32
> > Yes, but then systemd seems to fail to recognize them.
> 
> No, the mounted volumes (including manually enabled swap volumes) are correctly recognized. So, systemd itself is OK. The reason why the swap is not enabled by systemd is that the underlying device is not correctly processed by udevd. I have no idea what udev rules provided by LVM and device-mapper do. The issue should be solved by the provider of the rules.

https://github.com/lvmteam/lvm2/issues/153#issuecomment-2268485407

It seems to be a deficiency with udev, or at least a complication from design limits. I'm not sure how I would "record and replay" events but that seems quite complicated, and seems like something udev should be able to do.

**Comment by madsl** [comment] 2024-09-09 10:38
> I think there is a very similar issue occurring when btrfs subvolumes are used. Udev doesn't see the btrfs addition, and then mounts fail, where mount -a works.

I'm hitting this right now, having a btrfs file system on a cryptsetup volum set up manually in a custom initrd. Stopped working after updating systemd today. Do you know what I have to do in this initrd to make systemd not stall waiting for /dev/mapper/root or whatnot?

**Comment by desultory** [comment] 2024-09-09 14:38
> > I think there is a very similar issue occurring when btrfs subvolumes are used. Udev doesn't see the btrfs addition, and then mounts fail, where mount -a works.
> 
> I'm hitting this right now, having a btrfs file system on a cryptsetup volum set up manually in a custom initrd. Stopped working after updating systemd today. Do you know what I have to do in this initrd to make systemd not stall waiting for /dev/mapper/root or whatnot?

`ugrd.fs.fakeudev` as you found out, but for anyone who finds this issue.

In its current state, systemd requires udev is running before any dm mounts are made. If this doesn't happen something must make "fake" (or real) udev entries describing those mounts or systemd won't see them once it starts. If systemd doesn't see these mounts, they may as well not exist.
