### ISSUE TITLE
Ignore session keyring if the kernel does not support chown

### ISSUE THREAD

**Issue by a1any** [systemd/systemd#6281] opened 2017-07-04 10:19 UTC
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 233

### Used distribution

> Arch Linux (on OpenVZ containers)

OpenVZ kernels support keyctl, but fails to implement the chown/chgrp functionality correctly. It returns permission denied when trying to chown/chgrp to anybody other than oneself. For example,

```
# keyctl session
Joined session keyring: 556756508
# keyctl chown 556756508 1000
keyctl_chown: Permission denied
# keyctl chown 556756508 0
# echo $?
0
```

Yes, I know this is a bug on the OpenVZ kernel side, not systemd's (hence this is an RFE rather than a bug report). I think it's a good idea to ignore the keyring issue and continue exec instead of failing in this case. Right now it fails to start all the services that are restricted to users' privilege. Instead of waiting years to fix OpenVZ kernel or switching to other init, it would be lot easier to let systemd handle this.

**ALSO**, there actually is a bug. It appears log_...() functions in setup_keyring() is not enclosed with log_open(). Logs are not showing at all, and that wasted some time for me to investigate this issue.

**Comment by eworm-de** [comment] 2017-07-04 10:24
Is this fixed by #6275?

**Comment by a1any** [comment] 2017-07-04 10:27
@eworm-de 
> Is this fixed by #6275?

No. I tested that patch before submitting this issue.

**Comment by poettering** [comment] 2017-07-10 19:10
I am not sure I like this idea. We generally don't like working around kernel bugs this way, an in particular not kernel bugs in kernels that are so heavily patched.

Can't you work around this locally, i.e. by telling openvz to install some additional seccomp that makes keyctl and friends return ENOSYS or so? systemd will avoid the keyring entirely already if the syscalls return the right error codes, thus indicating that the functionality is not implemented.

**Comment by a1any** [comment] 2017-07-11 06:24
> by telling openvz to install some additional seccomp that makes keyctl and friends return ENOSYS or so

I am afraid in the case of OpenVZ that is not a viable workaround.

> We generally don't like working around kernel bugs this way, an in particular not kernel bugs in kernels that are so heavily patched.

I don't like that either. But how about adding an option to turn this feature off? As much as I like these new "security" features, and systemd's effort to handle old/odd kernels, I think it's always a good idea make all these great great features disabled-by-default. I believe it's a better to, say, add an option like `NewKeyring=` to profile files, and let systemd enforce this rule, failing services even when `keyctl` is ENOSYS, and if that is not set, completely ignore all these and don't touch keyctl. At least, I don't see any drawbacks adding a global (or per-service) option to manually turn it off, IMHO.

**Comment by poettering** [comment] 2017-07-11 07:42
Well, if there's a bug in software A, and software B interfaces with A and triggers it, then the right place to fix it is A, not work-around it in A. This is Open Source after all. The kernel is pretty much as easy or hard to fix as systemd. Hence, what's the benefit of sticking this in systemd?

**Comment by poettering** [comment] 2017-07-11 13:47
Hmm, so here's one idea that might work, that I can live with: we could query the access mode of the key, and if it already matches what we need it to be we can skip the chmod. Would that work for you? If so, please prep a patch.

if not then I am sure this needs to be dealt with in OpenVZ, and I figure we should close the bug here...

**Comment by a1any** [comment] 2017-07-11 15:34
After further research, it turns out that in order to perform chown on keyrings, it requires the CAP_SYS_ADMIN capability. So containers (e.g. LXC) with that capability dropped will suffer from this even with the latest mainline kernel.

So apparently OpenVZ kernel is not to blame here. I was mistaken, sorry.

I am not sure if I understood your new idea @poettering, but I don't think my coding skill is good enough to make a patch here.

IMO the current situation is that the kernel does not give permission of keyring chown'ing to non-sys-admin processes, which is the case for systemd running in restricted containers. I think that is definitely a situation popular enough for systemd to adapt to (or work around).

Alternatively, if you think systemd in CAP_SYS_ADMIN-dropped containers is an non-usecase, please close this bug. Thanks.

**Comment by poettering** [comment] 2017-07-11 16:44
hmm, so we didn#t support CAP_SYS_ADMIN-less boots traditionally, but today this should mostly work, but given that we don't test this regularly it's likely to break sooner or later...

If CAP_SYS_ADMIN is missing, then User= and Group= can't work anyway (as we need the cap for setuid()), and only then we trigger the keyring chown operation, hence I am not sure we can fix anything here really. Or am I missing something?

**Comment by a1any** [comment] 2017-07-11 16:52
Definitely, setuid of course works without that capability. Everything with 'User=' worked fine with 232 and previous versions, or having this keyring setup code commented out.

**Comment by a1any** [comment] 2017-07-11 17:00
I still suggest to have an option to let systemd keep its hands away from the keyring thing entirely. I surely appreciate this feature, but having everything forcefully enabled more than often breaks things here and there. But I sense that you don't enjoy the idea to give user the choice to disable thing they don't need, and in that case, just ignore my humble suggestion.

Anyway, please also fix the bug that keyring logs are not really showing up in the journal.

**Comment by poettering** [comment] 2017-07-11 17:03
hmm, it appears to me the kernel really should be fixed, and permit the chown keyctl if CAP_CHOWN is available... i.e. make the chowning of keys logic identical to the chowning of files logic...

That said, I'd accept a PR that skips the whole keyring setup code if a `have_effective_cap(CAP_SYS_ADMIN)` returns > 0 and `uid_is_valid(uid) || gid_is_valid(gid)` holds true, too.

That'd be a two-liner, and make things work for you:

```c
/* If we are running without CAP_SYS_ADMIN the KEYCTL_CHOWN operation will fail, hence let's skip the setup here, if we need to chown the keys. */
if (have_effective_cap(CAP_SYS_ADMIN) > 0 && (uid_is_valid(uid) || gid_is_valid(gid))
        return 0;
```

somewhere up in setup_keyring()...

**Comment by poettering** [comment] 2017-07-11 17:04
if that makes things work, please submit a PR and we can change this upstream

**Comment by poettering** [comment] 2017-07-11 17:05
> I still suggest to have an option to let systemd keep its hands away from the keyring thing entirely. I surely appreciate this feature, but having everything forcefully enabled more than often breaks things here and there. But I sense that you don't enjoy the idea to give user the choice to disable thing they don't need, and in that case, just ignore my humble suggestion.

This kinda where we'll probably end up, see the discussion at the end of #6286.

**Comment by Temtaime** [comment] 2017-07-23 20:29
Please, fix this. It worked before under lxc.
And now many services refuse to start.

**Comment by karolyi** [comment] 2017-07-30 17:36
+1

**Comment by xnox** [comment] 2017-09-20 12:13
It feels weird to me that user-namespaced process (systemd) cannot keyctl chown things to other uids/gids in the same user-namespace. This feels to me like a kernel limitation / deficiency / bug.

Testing lxd containers is trivial for me, and we do it both automatically and manually, albeit we could do more of it.

**Comment by xnox** [comment] 2017-10-03 03:10
I still believe this is a pure kernel bug, and oversight of something that was not merged in since 2011.

https://lists.linuxfoundation.org/pipermail/containers/2017-October/038250.html

Adding filters in lxd makes no sense at all, as it is not possible to check if one is running on a fixed kernel or not.

Furthermore, I wonder if this is racy, as capability can be revoked between adding a key and performing chown operation. Thus systemd code should be resilient to runtime changes of capabilities. I will propose a patch which will unlink the key, if chown operation has failed.

But ultimately the above kernel patch should be picked up by distributions.

**Comment by evverx** [comment] 2017-10-05 02:48
> But ultimately the above kernel patch should be picked up by distributions.

I'm not sure about that, because, as was pointed out in https://lists.linuxfoundation.org/pipermail/containers/2017-October/038251.html, unsharing a user namespace can be used to change the uid of any key.

In any case, thank you for kicking off the discussion. Hopefully, `keyctl` will be namespaced one day.

**Comment by evverx** [comment] 2017-10-05 02:56
I wonder why there is no "regression" label here. It's a regression, even though it is not going to be fixed.

**Comment by xnox** [comment] 2017-10-05 16:18
@evverx "unsharing a user namespace can be used to change the uid of any key." i don't believe that is true, but i am still crafting a response to that.

**Comment by Temtaime** [comment] 2017-10-12 11:44
It is forcefully a regression maybe made with making some assumptions about the kernel.
Kernel fixes takes years, so it needs to be fixed in the systemd.
Please, fix this one or people will stay with version 229 for years.

**Comment by evverx** [comment] 2017-10-13 18:43
I'm afraid in https://github.com/systemd/systemd/pull/6876 it was made clear that the issue wouldn't be fixed. For now it can be worked around by blocking `keyctl`.

**Comment by evverx** [comment] 2017-10-13 18:50
> ALSO, there actually is a bug. It appears log_...() functions in setup_keyring() is not enclosed with log_open(). Logs are not showing at all, and that wasted some time for me to investigate this issue.

For the record, that issue has been fixed in https://github.com/systemd/systemd/pull/6915.

**Comment by Mic92** [comment] 2017-10-22 09:16
I currently worked around in lxc by appending the following to my seccomp filter:

```
# /etc/lxc/default.seccomp
keyctl_chown errno 38
keyctl errno 38
```

```
lxc.seccomp.profile = /etc/lxc/default.seccomp
```

**Comment by evverx** [comment] 2018-03-27 16:10
The issue seems to have been fixed in https://github.com/systemd/systemd/pull/8447.

**Closed as completed by evverx** 2018-03-27 16:10 UTC
Labels: pid1, regression ⚠️
