### ISSUE TITLE
Enact modified `WatchDogSec=` property without stopping and starting a service

### ISSUE THREAD

**Issue by dilyanpalauzov** [systemd/systemd#30922] opened 2024-01-13 13:10 UTC
### Is your feature request related to a problem? Please describe

Because a system is overloaded, systemd-journald.service or systemd-udevd.service are terimaned by the watchdog mechanism.  I increase `[Service]WatchdogSec=` and do then `systemctl daemon-reload`.  When the processes are terminated again, journald logs that the watchdog timer has expired, but this is the watchdog timer before `systemctl daemon-reload` was executed.  This happens also for subsequent terminations, where I do not modifiy the `WatchdogSec=` value.

So apparently the only way to get new `WatchdogSec=` value enacted, is to stop and start the services, but I do not want to stop and start the services.

### Describe the solution you'd like

`systemctl daemon-reload` should enact modified Watchdog timer in .service files to currently running services, without requiring service stop and start.  At the very least, there should be a way to reread `WatchdogSec=` when a service is stopped and restarted by the watch dog.  My experiment show that `WatchdogSec=` is not reread.

### The systemd version you checked that didn't have the feature you are asking for

253

**Comment by vcaputo** [comment] 2024-01-13 19:56
The `WATCHDOG_USEC` environment variable is set before executing the service's process, and that's the value it will read.

It's not clear to me how the service manager would asynchronously update this environment variable after the fact, it's kind of implicit that the process must exit then the next invocation would see the updated value in `WATCHDOG_USEC`, due to how environment variables work in *NIX.

**Comment by yuwata** [comment] 2024-01-13 20:54
`systemctl daemon-reload` does not take effect to running services. The new setting will be applied after the service restarted.
Some property can changed in runtime by `systemctl set-property`, but currently whatchdog timer is not supported.

**Comment by dilyanpalauzov** [comment] 2024-01-14 08:11
Thanks for your insights.  I restart a system irregularly, e.g. once a year.  Until next restart systemd-journald.service and systemd-udevd.service might be killed by the WatchDog mechanism.  After I increase `WatchdogSec=` I could stop and start both services to get the new value enacted.  But I would prefer if there is a way to apply the new WatchDogSec value without restarting the service. 

```
[Service]
Restart=always
RestartSec=0
WatchdogSec=3min
```

If not possible to change this for the current process, then the latest when the process is terminated and restarted

I am not sure how to understand the initial and corrected reference to `systemctl set-property`.  https://www.freedesktop.org/software/systemd/man/latest/systemctl.html#set-property%20UNIT%20PROPERTY=VALUE… says “Set the specified unit properties at runtime where this is supported. ”.  Are the changes done at runtime, or after restart?

**Comment by dilyanpalauzov** [comment] 2024-01-21 15:37
The systemd-journald and systemd-udevd services can be easily restarted, but I first have to find out what undesired side effects can happen while the services are restarted.  So my assumption is that the effect is unknown.

Concerning modifying the W`atchdogSec` property at runtime, if this is not going to happen, this ticket can be closed.

**Comment by Werkov** [comment] 2024-01-22 09:58
>  So my assumption is that the effect is unknown.

Quote from systemd-journald(8) (section Stream logging):
> If systemd-journald.service is restarted using systemctl restart or equivalent operation instead of a pair of separate systemctl stop and systemctl start commands (or equivalent operations), these stream connections are not terminated and survive the restart. It is thus safe to restart systemd-journald.service, but stopping it is not recommended.

**Comment by poettering** [comment] 2024-01-30 09:19
So we could in theory update the watchdog timeout during runtime, but the problem is that we'd have to notify the service code somehow abou the update timeout and there's no nice way to do this. We set the `$WATCHDOG_USEC` env var for the program after all, and there's no way we can update env vars retroactively for already started services. And even if we could, the program would not take notice and reparse.

Now, we could divise a new protocol for that of course, somehow notify the process, but this would be quite complicated, a lot more complicated at least than just parsing an env var. So even if we'd support it, i doubt many programs would implement it.

I think there's a lot more value in ensuring services can be restarted without losing their state. systemd's own services should be pretty good at that. File bugs if you encounter one that does not handle this way.

Hence closing this. I hope that makes some sense.

**Closed as completed by poettering** 2024-01-30 09:19 UTC
Labels: RFE 🎁, pid1
