### ISSUE TITLE
systemd-journal-upload doesn't start anymore: Error 411: gth required

### ISSUE THREAD

**Issue by heini** [systemd/systemd#11669] opened 2019-02-07 15:51 UTC
**systemd version the issue has been seen with**
> 240

**Used distribution**
 > Debian Buster

**Expected behaviour you didn't see**
 > systemd-journal-upload starts up and pushes journal to remote host

**Unexpected behaviour you saw**
 > systemd-journal-upload[7781]: Upload to http://<remotehost>:19532/upload failed with code 411: gth Required

**Steps to reproduce the problem**
systemctl start systemd-journal-upload

**Comment by yuwata** [comment] 2019-02-07 19:35
Duplicate of #11571.

**Closed as completed by yuwata** 2019-02-07 19:35 UTC
Labels: duplicate, journal-remote
