### ISSUE TITLE
Ubuntu CI unit-tests fail with "ModuleNotFoundError: No module named 'dataclasses'"

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#19640] opened 2021-05-18 05:52 UTC
```
autopkgtest [02:10:49]: test unit-tests: [-----------------------
Traceback (most recent call last):
  File "test/run-unit-tests.py", line 4, in <module>
    import dataclasses
ModuleNotFoundError: No module named 'dataclasses'
```
cc @rbalint.
(Sorry, maybe here is not a good place to report this issue.)

**Comment by keszybz** [comment] 2021-05-18 07:53
@ddstreet please take a look. I think your commit caused this:

    d/t: replace 'root-unittests' shell script with simple call to upstream script
    
    The upstream test runner script is much better, as it only prints failing test
    output, and gives a summary of the test results at the end.

The problem is that bionic has python3.6, and dataclasses module was added in 3.7.

**Comment by ddstreet** [comment] 2021-05-18 12:02
> @ddstreet please take a look. I think your commit caused this:
> 
> ```
> d/t: replace 'root-unittests' shell script with simple call to upstream script
> 
> The upstream test runner script is much better, as it only prints failing test
> output, and gives a summary of the test results at the end.
> ```
> 
> The problem is that bionic has python3.6, and dataclasses module was added in 3.7.

ah crap, sorry.

I just reverted that commit in the upstream-ci branch so tests should work again now.

I'd like to move the Ubuntu CI up to using Focal, instead of Bionic, so we don't need to stay compatible with the super old code in Bionic; I opened https://github.com/systemd/systemd/pull/19647 which I think is the last thing blocking the upgrade of Ubuntu CI to use Focal.

**Comment by keszybz** [comment] 2021-05-18 12:46
Please revert the revert once #19641 is merged

**Comment by ddstreet** [comment] 2021-05-18 13:32
> Please revert the revert once #19641 is merged.

will do

**Comment by keszybz** [comment] 2021-05-18 21:59
> > Please revert the revert once #19641 is merged.
> 
> will do

#19641 has been merged, so this can be done now.

**Closed as completed** 2021-05-18 21:59 UTC
Labels: ci

**Comment by ddstreet** [comment] 2021-05-19 17:32
> > > Please revert the revert once #19641 is merged.
> > 
> > 
> > will do
> 
> #19641 has been merged, so this can be done now.

done
