### ISSUE TITLE
RFE: machinectl shell: spawn shell with service unit environment

### ISSUE THREAD

**Issue by eliasp** [systemd/systemd#8789] opened 2018-04-23 12:00 UTC
### Submission type
 - Request for enhancement (RFE)

### systemd version the issue has been seen with
> 238

### Used distribution
> Gentoo

### RFE
Quite often, I'd love to have a shell available which resembles a service's environment as much as possible to work in an interactive environment, but with the same conditions as the service.

For example, I have the following service unit for [restic](https://github.com/restic/restic):
```INI
[Unit]
Description=Backup %I using 'restic'
ConditionFileNotEmpty=/etc/restic/%i/restic.env
ConditionPathExists=/etc/restic/%i/backup.exclude

[Service]
# /run, /tmp are intentionally not --exclude'd as those are tmpfs anyways and therefore already excluded by --one-file-system
ExecStart=/usr/local/bin/restic backup --cache-dir=/var/cache/restic/%i --one-file-system --exclude-file=/etc/restic/%i/backup.exclude --exclude=/var/cache/* --exclude=/var/tmp/* --exclude=/home/*/.cache/* /
Type=simple
EnvironmentFile=/etc/restic/%i/restic.env
DynamicUser=yes
PrivateTmp=no
PrivateDevices=yes
CacheDirectory=restic/%i
CacheDirectoryMode=0700
ConfigurationDirectory=restic/%i
ConfigurationDirectoryMode=0700
LogsDirectory=restic/%i
SystemCallFilter=@basic-io @default @file-system @io-event @network-io @process @signal getrandom ioctl sched_getaffinity
SystemCallErrorNumber=EPERM
AmbientCapabilities=CAP_DAC_READ_SEARCH
IPAccounting=yes
IOSchedulingClass=idle
CPUSchedulingPolicy=idle
```

Now there are quite a few scenarios which require to have the service's environment available as interactive shell, such as:
- initializing the backup repository
- diff-ing backups
- restoring files
- debugging
- maintenance tasks such as a manual `restic prune` etc.

Now one could use `systemd-run -t -p Foo=bar /bin/bash` to emulate such an environment, but:
- it is quite cumbersome to re-specify all properties of the service unit manually
- `systemd-run` doesn't provide all the features the service unit does, e.g. `DynamicUsers=yes`, instances, …

I'd love to be able to simply type something like this:
```
machinectl shell --unit=restic@moria .host /bin/bash
```
…and end up on a shell which is basically the interactive version of `restic@moria.service` and `/bin/bash` as `ExecStart=`.

**Comment by poettering** [comment] 2018-04-23 15:07
> systemd-run doesn't provide all the features the service unit does, e.g. DynamicUsers=yes, instances, …

DynamicUser=1 works fine with systemd-run, in fact that's I did all my testing of DynamicUser=yes... Just do:

```
systemd-run -p DynamicUser=1 -t /bin/sh
```

which should work fine.

At this point our coverage of properties with systemd-run (or mor generically speaking: transient units) is pretty complete. We track this here:

https://github.com/systemd/systemd/blob/master/doc/TRANSIENT-SETTINGS.md

**Comment by poettering** [comment] 2018-04-23 15:08
In general I do grok your usecase though, and i agree that even though it should be possible to put together the full  unit file env with systemd-run it might be cumbersome to do that...

**Comment by eliasp** [comment] 2018-04-23 15:20
My bad - had a typo in my `systemd-run` tests and used `DynamicUsers=` instead of `DynamicUser=`, sorry.

But the remaining arguments still stand - thanks for validating my usecase.

**Comment by lucaswerkmeister** [comment] 2018-04-26 11:04
:+1: from me, I’ve found myself wishing for something like this before :) but I’m not sure if this makes sense in `machinectl`… if the machine isn’t `.host`, should the unit files be searched in the specified machine or in the host? Personally, I think I would expect this feature in `systemd-run`, perhaps called something like `--inheritProperties`?

I suppose in addition to overriding `ExecStart`, this should set `Restart=no`. `ExecStop` and `ExecStopPost` probably also don’t make sense. What about `ExecStartPre` and `ExecStartPost`? And should `WatchdogSec` be disabled?

**Comment by poettering** [comment] 2018-11-22 18:38
Duplicate of #9907. (yeah that other one is newer, but it has a more concise description i guess, hence let's close this one)

**Closed as completed by poettering** 2018-11-22 18:38 UTC
Labels: RFE 🎁, pid1, run, duplicate
