### ISSUE TITLE
Systemd fails to start a service with ProtectHome=yes and symlinks.

### ISSUE THREAD

**Issue by iazz** [systemd/systemd#4502] opened 2016-10-27 07:56 UTC
### Submission type
- [x] Bug report
- [ ] Request for enhancement (RFE)

_NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!_
### systemd version the issue has been seen with

> 231

_NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!_
### Used distribution

> Ubuntu 16.10
### In case of bug report: Expected behaviour you didn't see

> Services with `ProtectHome=yes` started successfully.
### In case of bug report: Unexpected behaviour you saw

> Services with `ProtectHome=yes` failed to start with the following:
> `Failed at step NAMESPACE spawning /lib/systemd/…: Too many levels of symbolic links`
### In case of bug report: Steps to reproduce the problem

> The problem comes from the fact that my `/home` is a symlink to some other place.  Looking at the source code of `systemd`, it seems that when `ProtectHome=yes`, if any of `/home`, `/run/user` or `/root` is a symlink, the `apply_mount` function in `src/core/namespace.c` fails with `-ELOOP`.
> I understand that when either `/home`, `/run/user` or `/root` is a symlink, systemd can't overmount it with an inaccessible directory.  But why couldn't it overmount the symlink's target with an inaccessible directory instead?  And when the symlink itself is dangling, couldn't systemd simply ignore it?

**Comment by evverx** [comment] 2016-10-28 11:43
Duplicate of https://github.com/systemd/systemd/issues/3867

**Closed as completed by evverx** 2016-10-28 11:43 UTC
Labels: bug 🐛, pid1, duplicate
