### ISSUE TITLE
RFE: systemd-cgls pstree-like mode

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#17375] opened 2020-10-18 09:15 UTC
Right now systemd-cgls shows processes in a single cgroup as a flattened list in random order. It would be great if we could
a) at least sort them so that parents are earlier than children (easy)
b) optionally display a subtree of processes (harder)

This would be useful to understand cases where a larger number of processes are spawned within one cgroup.
For example, I have the following:
```
│   │ │   ├─vte-spawn-ea238e8a-d779-4795-a6ce-e32fa68ccf53.scope 
│   │ │   │ ├─ 97798 zsh
│   │ │   │ ├─ 99705 emacs src/login/logind-inhibit.c
│   │ │   │ ├─268688 podman
│   │ │   │ ├─592693 sudo -b emacs /etc/udev/hwdb.d/60-keyboard.hwdb
│   │ │   │ ├─592695 emacs /etc/udev/hwdb.d/60-keyboard.hwdb
│   │ │   │ ├─592706 dbus-launch --autolaunch 08a5690a2eed47cf92ac0a5d2e3cf6b0 --binary…
│   │ │   │ ├─592707 /usr/bin/dbus-daemon --syslog-only --fork --print-pid 5 --print-add…
│   │ │   │ ├─592709 /usr/libexec/at-spi-bus-launcher
│   │ │   │ ├─592714 /usr/bin/dbus-broker-launch --config-file=/usr/share/defaults/at-sp…
│   │ │   │ ├─592715 dbus-broker --log 4 --controller 9 --machine-id 08a5690a2eed47cf92a…
│   │ │   │ ├─606574 git grep www.freedesktop.org/wiki
│   │ │   │ ├─606579 /bin/sh -c /home/zbyszek/src/diff-so-fancy/diff-so-fancy | less --t…
│   │ │   │ └─606581 less --tabs=4 -RFX
```
This is a cgroup for a single tab of gnome-terminal. Clearly, a lot is happening here. A pstree-like view would help.

**Comment by mehoffer** [comment] 2020-11-06 11:58
Hi, just info regarding

> Right now systemd-cgls shows processes in a single cgroup as a flattened list in **random order**.

From the code it looks like they are sorted (intentionally?) by pids as can be seen [here](https://github.com/systemd/systemd/blob/master/src/shared/cgroup-show.c#L43).

**Comment by poettering** [comment] 2021-02-15 16:06
Duplicate of #8275

**Closed as completed by poettering** 2021-02-15 16:06 UTC
Labels: RFE 🎁, cgls, duplicate
