### ISSUE TITLE
ConditionPathExists= prevents Restart=always from working

### ISSUE THREAD

**Issue by Malvineous** [systemd/systemd#29149] opened 2023-09-10 14:47 UTC
### systemd version the issue has been seen with

254

### Used distribution

Arch Linux

### Linux kernel version used

6.4.11-arch2-1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

I expected a service with `Restart=always` to always restart.

### Unexpected behaviour you saw

The service failed to start the first time due to `ConditionPathExists` failing, but systemd did not try to start the service again later, even though `Restart=always` was set.  So a few seconds later when the file was created and the condition would have passed, no further attempts are made by systemd to start the service.

### Steps to reproduce the problem

1. Create `test.service`
```
[Unit]
Description=Test
Wants=network-online.target
After=network-online.target

StartLimitIntervalSec=0

ConditionPathExists=/dev/ttyUSBmobile4g

[Service]
ExecStart=/usr/bin/bash -c "echo hello"
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
```
2. `systemctl start test`
3. `journalctl -u test -n`
4. Observe service failed to start with the expected error: `systemd[1]: Test was skipped because of an unmet condition check (ConditionPathExists=/dev/ttyUSBmobile4g).`
5. Wait for five seconds and check the journal again, whether you have created the missing file or not.
6. Observe the service never attempts to restart.

In my situation it takes a few moments for the USB device to be reconfigured via a mode switch, where it disconnects and reconnects as the appropriate device.  By this time systemd has already tried to start the service and failed, as the device file does not exist yet.  However it never tries to restart the service again, even after the missing device file appears, despite `Restart=always` being set.

Because I have set `Restart=always` and told it to attempt a restart every five seconds, I expect it would try to restart every five seconds, and continue failing until the `ConditionPathExists` file has been found, at which time it would run `ExecStart` as normal.

**Comment by YHNdnzj** [comment] 2023-09-10 15:36
As documented in [systemd.unit(5)](https://man.archlinux.org/man/systemd.unit.5#Conditions_and_Asserts):

> Before the unit is started, systemd will verify that the specified conditions and asserts are true. If not, the starting of the unit will be (mostly silently) skipped (in case of conditions), or aborted with an error message (in case of asserts).

and [systemd.service(5)](https://man.archlinux.org/man/core/systemd/systemd.service.5.en#OPTIONS):

> Restart=
> Configures whether the service shall be restarted when the service process exits, is killed, or a timeout is reached. 

When `Condition...` is verified to be false, the unit is never started in the first place. Thus, the `Restart=` option that triggers when the service process exits will not apply.

For your specific use case, activating the unit after the device is up should be achievable by using a udev rule with `SYSTEMD_WANTS=` property.

**Comment by poettering** [comment] 2023-09-11 08:02
Yes, Restart= is about *restarting* a service. If it never was started in the first place, the logic has no effect, and that's by documentation.

Closing as this works as intended, and the issue is probably more a usage question, which should be directed to systemd-devel, not file as bug.

**Closed as completed by poettering** 2023-09-11 08:02 UTC
Labels: bug 🐛, pid1, not-a-bug
