### ISSUE TITLE
systemctl status enabled/disabled doesn't take into account /usr/lib/systemd/system symlinks

### ISSUE THREAD

**Issue by WOnder93** [systemd/systemd#29155] opened 2023-09-11 09:14 UTC
### systemd version the issue has been seen with

253.9

### Used distribution

Fedora 38

### Linux kernel version used

6.4.14-200.fc38.x86_64

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

When I add a symlink to a service into `/usr/lib/systemd/system/multi-user.target.wants/` (and run `systemctl daemon-reload`), I expect `systemctl is-enabled`/`systemctl status` to report the service as "enabled" (or similar), same as if I added an equivalent symlink to `/etc/systemd/system/multi-user.target.wants/`.

### Unexpected behaviour you saw

`systemctl is-enabled` and `systemctl status` still report the service as "disabled", even though it is correctly started by systemd at the next boot. Also the `systemctl(1)` manpage doesn't mention `/usr/lib/systemd/system` under `is-enabled`.

### Steps to reproduce the problem

1. Add a symlink to <X>.service into `/usr/lib/systemd/system/multi-user.target.wants/`.
2. Run `systemctl daemon-reload`.
3. Run `systemctl is-enabled <X>.service`.

**Comment by YHNdnzj** [comment] 2023-09-11 09:23
This is expected. When you ship .wants/.requires/.upholds symlinks in /usr/, the service should not carry an [Install] section, instead it is considered "statically enabled" and cannot be disabled using systemctl. If you want to allow the sysadmin to enable/disable the service, please don't ship the symlink, but enable the unit in the post-install script.

See also: https://github.com/systemd/systemd/issues/9569#issuecomment-404869434

Duplicate of #9569, closing.

**Closed as not planned** 2023-09-11 09:23 UTC
Labels: bug 🐛, systemctl, duplicate, not-a-bug
