### ISSUE TITLE
udevd reload not changing permissions until "udevadm test" is ran?!?

### ISSUE THREAD

**Issue by agowa** [systemd/systemd#31970] opened 2024-03-26 15:58 UTC
### systemd version the issue has been seen with

systemd 255 (255.4-2-arch)

### Used distribution

ArchLinux

### Linux kernel version used

6.6.9-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd-udevd, udevadm, udev rule files

### Expected behaviour you didn't see

udevd rule reload/restart changing applying new configs and changing it for already existing devices.
At least `udevadm control --reload-rules && udevadm trigger` should apply the new config e.g. permission changes.

### Unexpected behaviour you saw

Permissions and ownership not changing of device nodes.

### Steps to reproduce the problem

1. `groupadd --system uucpUSB -U user`
2. `ls -la /dev/ttyUSB*` => `crw-rw---- 1 root uucp (...) ttyUSB1` (old config)
3. `echo 'ACTION=="add", SUBSYSTEM=="tty", ENV{ID_BUS}=="usb", GROUP="uucpUSB"' > /etc/udev/rules.d/99-ttyUSB.rules`
4. `udevadm control --reload-rules && udevadm trigger`, or `systemctl restart systemd-udevd.service && udevadm trigger`, or `systemctl daemon-reload && systemctl restart systemd-udevd.service && udevadm control --reload-rules && echo add >> /sys/devices/pci..../uevent`
5. `ls -la /dev/ttyUSB*` => `crw-rw---- 1 root uucp (...) ttyUSB1` (still old config)
6. Wait 30-60s (until `systemctl status systemd-udevd` only shows one running process in its CGroup)
7. `ls -la /dev/ttyUSB*` => `crw-rw---- 1 root uucp (...) ttyUSB1` (still old config)
8. **HOWEVER**
9. `udevadm test sys-devices-pci....-ttyUSB1-tty-tyUSB1.device` => lists the permissions correctly
10. `ls -la /dev/ttyUSB*` => `crw-rw---- 1 root uucpUSB (...) ttyUSB1` (**NEW** config)

Why does it **only** ever reapply the config after a `udevadm test` which is supposed to **not** change state?
(And it is consistent, even just running `udevadm test` like above is enough for the permission change to reapply, even without doing the reload or trigger before)

This could be related to https://github.com/systemd/systemd/issues/3134

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
No issues are logged.
```

**Comment by yuwata** [comment] 2024-03-26 16:29
The rule has `ACTION=="add"`, so you need to use `udevadm trigger --action=add`. Without `--action`, the defaults to `change`, so the new rule will be skipped.

However, the default action for `udevadm test` is `add`, rather than `change`.

See man page for more details.

This is not a bug. Closing.

**Closed as not planned by yuwata** 2024-03-26 16:29 UTC
Labels: udev, not-a-bug

**Comment by agowa** [comment] 2024-03-26 17:52
@yuwata still a bug, `udevadm test` should not change state at least that's what the docs say.

And thanks for the hint about the `--action=add` part. That one worked.
