### ISSUE TITLE
systemd-sysctl fails with "Input/output error"

### ISSUE THREAD

**Issue by neophob** [systemd/systemd#8121] opened 2018-02-07 10:44 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

systemd 236
+PAM -AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN default-hierarchy=hybrid

### Used distribution

Arch Linux ARM

### In case of bug report: Steps to reproduce the problem

```
[root@NEEO-1f136065 ~]# /usr/lib/systemd/systemd-sysctl 
Couldn't write '16' to 'kernel/sysrq': Input/output error
Couldn't write '1' to 'kernel/core_uses_pid': Input/output error
Couldn't write '1' to 'net/ipv4/conf/all/rp_filter': Input/output error
Couldn't write '0' to 'net/ipv4/conf/all/accept_source_route': Input/output error
Couldn't write '1' to 'net/ipv4/conf/all/promote_secondaries': Input/output error
Couldn't write '1' to 'fs/protected_hardlinks': Input/output error
Couldn't write '1' to 'fs/protected_symlinks': Input/output error
```

this worked fine using systemd v234. `proc` fs contains those files, I run `systemd-sysctl` as root user.

strace output:

```
.. <snip>
openat(AT_FDCWD, "/proc/sys/fs/protected_hardlinks", O_WRONLY|O_NOCTTY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_GETFL)                     = 0x20001 (flags O_WRONLY|O_LARGEFILE)
write(3, "1", 1)                        = 1
write(3, "\n", 1)                       = -1 EINVAL (Invalid argument)
close(3)                                = 0
writev(2, [{iov_base="Couldn't write '1' to 'fs/protec"..., iov_len=66}, {iov_base="\n", iov_len=1}], 2Couldn't write '1' to 'fs/protected_hardlinks': Input/output error
) = 67
openat(AT_FDCWD, "/proc/sys/fs/protected_symlinks", O_WRONLY|O_NOCTTY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_GETFL)                     = 0x20001 (flags O_WRONLY|O_LARGEFILE)
write(3, "1", 1)                        = 1
write(3, "\n", 1)                       = -1 EINVAL (Invalid argument)
close(3)                                = 0
writev(2, [{iov_base="Couldn't write '1' to 'fs/protec"..., iov_len=65}, {iov_base="\n", iov_len=1}], 2Couldn't write '1' to 'fs/protected_symlinks': Input/output error
) = 66
```

sysctl is from the arch linux distro (unchanged, equal to the working systemd v234)

```
# cat /usr/lib/sysctl.d/50-default.conf
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

# See sysctl.d(5) and core(5) for documentation.

# To override settings in this file, create a local file in /etc
# (e.g. /etc/sysctl.d/90-override.conf), and put any assignments
# there.

# System Request functionality of the kernel (SYNC)
#
# Use kernel.sysrq = 1 to allow all keys.
# See https://www.kernel.org/doc/html/latest/admin-guide/sysrq.html for a list
# of values and keys.
kernel.sysrq = 16

# Append the PID to the core filename
kernel.core_uses_pid = 1

# Source route verification
net.ipv4.conf.all.rp_filter = 1

# Do not accept source routing
net.ipv4.conf.all.accept_source_route = 0

# Promote secondary addresses when the primary address is removed
net.ipv4.conf.all.promote_secondaries = 1

# Fair Queue CoDel packet scheduler to fight bufferbloat
#net.core.default_qdisc = fq_codel

# Enable hard and soft link protection
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
```

**Comment by neophob** [comment] 2018-02-07 11:08
Update, i checked the strace output between a working and a non working version, here's the difference

Failing:
```
openat(AT_FDCWD, "/proc/sys/net/ipv4/.. whatever", O_WRONLY|O_NOCTTY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_GETFL)                     = 0x20001 (flags O_WRONLY|O_LARGEFILE)
write(3, "1", 1)                        = 1
write(3, "\n", 1)                       = -1 EINVAL (Invalid argument)
close(3)                                = 0
writev(2, [{iov_base="Couldn't write '1' to 'net/ipv4/"..., iov_len=73}, {iov_base="\n", iov_len=1}], 2Couldn't write '1' to 'net/ipv4/conf/eth0/arp_ignore': Input/output error
) = 74
```

Working:
```
openat(AT_FDCWD, "/proc/sys/net/ipv4/.. whatever", O_WRONLY|O_NOCTTY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_GETFL)                     = 0x20001 (flags O_WRONLY|O_LARGEFILE)
fstat64(3, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
write(3, "1\n", 2)                      = 2
close(3)                                = 0
```

**Comment by poettering** [comment] 2018-02-07 11:09
Duplicate of #7744

**Closed as completed by poettering** 2018-02-07 11:09 UTC
Labels: sysctl, duplicate

**Comment by neophob** [comment] 2018-02-07 11:11
Not sure

I checked the strace of a working and a not working version, here's the diff

Not Working:
```
openat(AT_FDCWD, "/proc/sys/net/ipv4/SNIP", O_WRONLY|O_NOCTTY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_GETFL)                     = 0x20001 (flags O_WRONLY|O_LARGEFILE)
write(3, "1", 1)                        = 1
write(3, "\n", 1)                       = -1 EINVAL (Invalid argument)
close(3)                                = 0
writev(2, [{iov_base="Couldn't write '1' to 'net/ipv4/"..., iov_len=73}, {iov_base="\n", iov_len=1}], 2Couldn't write '1' to 'net/ipv4/SNIP': Input/output error
) = 74
```

Working:
```
openat(AT_FDCWD, "/proc/sys/net/ipv4/SNIP", O_WRONLY|O_NOCTTY|O_LARGEFILE|O_CLOEXEC) = 3
fcntl64(3, F_GETFL)                     = 0x20001 (flags O_WRONLY|O_LARGEFILE)
fstat64(3, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
write(3, "1\n", 2)                      = 2
close(3)                                = 0
```

might this be a permission issue?
