### ISSUE TITLE
systemd-timesyncd failing with /usr/lib/systemd/systemd-timesyncd: Not a directory

### ISSUE THREAD

**Issue by Edu4rdSHL** [systemd/systemd#12286] opened 2019-04-12 01:39 UTC
**systemd version the issue has been seen with**
> 242

**Used distribution**
 > ArchLinux

**Expected behaviour you didn't see**
 > systemd-timesyncd.service start normally

**Unexpected behaviour you saw**
 > systemd-timesyncd failing with /usr/lib/systemd/systemd-timesyncd: Not a directory

**Steps to reproduce the problem**

Update to systemd 242 with systemd-timesyncd.service enabled and see the failed service.

journalctl logs:

```
Apr 11 21:03:58 SecHackLabs systemd[1]: Failed to start Network Time Synchronization.
Apr 11 21:03:58 SecHackLabs systemd[1]: systemd-timesyncd.service: Failed with result 'exit-code'.
Apr 11 21:03:58 SecHackLabs systemd[1]: systemd-timesyncd.service: Start request repeated too quickly.
Apr 11 21:03:58 SecHackLabs audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-timesyncd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Apr 11 21:03:58 SecHackLabs audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-timesyncd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Apr 11 21:03:58 SecHackLabs systemd[1]: Stopped Network Time Synchronization.
Apr 11 21:03:58 SecHackLabs systemd[1]: systemd-timesyncd.service: Scheduled restart job, restart counter is at 5.
Apr 11 21:03:58 SecHackLabs systemd[1]: systemd-timesyncd.service: Service has no hold-off time (RestartSec=0), scheduling restart.
Apr 11 21:03:58 SecHackLabs audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-timesyncd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Apr 11 21:03:58 SecHackLabs systemd[1]: Failed to start Network Time Synchronization.
Apr 11 21:03:58 SecHackLabs systemd[1]: systemd-timesyncd.service: Failed with result 'exit-code'.
Apr 11 21:03:58 SecHackLabs systemd[1]: systemd-timesyncd.service: Main process exited, code=exited, status=238/STATE_DIRECTORY
Apr 11 21:03:58 SecHackLabs systemd[1480]: systemd-timesyncd.service: Failed at step STATE_DIRECTORY spawning /usr/lib/systemd/systemd-timesyncd: Not a directory
Apr 11 21:03:58 SecHackLabs systemd[1480]: systemd-timesyncd.service: Failed to set up special execution directory in /var/lib: Not a directory
Apr 11 21:03:58 SecHackLabs kernel: audit: type=1130 audit(1555034638.263:187): pid=1 uid=0 auid=4294967295 ses=4294967295 subj==unconfined msg='unit=systemd-timesyncd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Apr 11 21:03:58 SecHackLabs systemd[1]: Starting Network Time Synchronization...
```

**Comment by yuwata** [comment] 2019-04-12 02:17
Duplicate of #12131.

**Closed as completed by yuwata** 2019-04-12 02:17 UTC
Labels: RFE 🎁, duplicate
