### ISSUE TITLE
Unable to use systemd due to increased resources on a server : traps: systemd-journal[217] general protection fault ip:7f40be5973e3 sp:7ffc1d7b7730 error:0 in libdbus.so

### ISSUE THREAD

**Issue by supr4s** [systemd/systemd#24653] opened 2022-09-13 08:14 UTC
### systemd version the issue has been seen with

247.3

### Used distribution

Debian 11

### Linux kernel version used

5.10.0-18-cloud-amd64

### CPU architectures issue was seen on

x86_64

### Component

other

### Expected behaviour you didn't see

A server that works without any problem with the possibility of managing its services.

### Unexpected behaviour you saw

At boot : 

![systemd-error](https://user-images.githubusercontent.com/34515269/189844681-185da14f-e86a-4346-a3ff-c4d0b72c7e50.PNG)

And impossible to manage server services
e.g : 
```
$ systemctl status mysql
Failed to connect to bus: Connection refused
```

### Steps to reproduce the problem

Hi everyone,

This server is a backup server dedicated to a real time MySQL 5.7 replication.

Via a Cloud provider (OVHCloud) and OpenStack, I increased the server resources from a small instance (7GB RAM, 2vCPu) to a larger one (32vCPu, 120GB RAM).

As soon as the instance started with its new RAM/CPU resources, this problem appeared and since then the server is almost unusable. :( 

I already had a similar problem six months ago (Debian 10 - MySQL 5.7 - did not get the version of systemd), where this server was restarted and MySQL 5.7 was unusable. As soon as I managed the service, the server crashed: 

```
$ systemctl status mysql

Broadcast message from systemd-journald@SRV-EDM-SQL1-2 (Thu 2022-03-10 15:43:22 CET):

systemd[1]: Caught <SEGV>, dumped core as pid 969.

Broadcast message from systemd-journald@SRV-EDM-SQL1-2 (Thu 2022-03-10 15:43:22 CET):

systemd[1]: Freezing execution.

Message from syslogd@SRV-EDM-SQL1-2 at Mar 10 15:43:22 ...
 systemd[1]: Caught <SEGV>, dumped core as pid 969.

Message from syslogd@SRV-EDM-SQL1-2 at Mar 10 15:43:22 ...
 systemd[1]: Freezing execution.
Failed to get properties: Connection timed out
```

I couldn't fix the problem, and ended up installing a new  freshserver.  The only similarities between my server today and the one from six months ago: Debian OS, MySQL 5.7, replication MASTER - SLAVE and MySQL data on an additional disk attached to the instance.

And today a similar problem seems to return, knowing that : 

- An increase of resources/decrease have already been done 2x a few weeks ago without any problem
- The server has rebooted several times without any problem
- I remove the MySQL  launch at the server startup (removal of the files `/lib/systemd/system/mysql.service` and of the symbolic link `/etc/systemd/system/multi-user.target.wants/mysql.service`)
- No more additional disks are attached to the server
- There are almost no services running on the server, nothing out of the ordinary and systemd is still not working

If someone has an idea, I take it !

Thanks.

**Comment by supr4s** [comment] 2022-09-13 08:22
dmesg content attached.
[dmesg.log](https://github.com/systemd/systemd/files/9554914/dmesg.log)

**Comment by mrc0mmand** [comment] 2022-09-13 08:36
Given that everything that touches `libdbus.so` or ` ld-2.31.so` fails and it's not only systemd, I'd say the issue is not in systemd:

```
[   17.858643] audit: type=1400 audit(1663050889.304:10): apparmor="DENIED" operation="open" profile="/usr/sbin/chronyd" name="/usr/local/lib/libdbus.so" pid=432 comm="chronyd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
[   77.159168] traps: systemd-journal[217] general protection fault ip:7f40be5973e3 sp:7ffc1d7b7730 error:0 in libdbus.so[7f40be597000+1000]
[   77.165675] traps: systemd[1] general protection fault ip:7f97771fc3e3 sp:7ffe0eb86a70 error:0 in libdbus.so[7f97771fc000+1000]
[  206.009836] traps: systemd-logind[443] general protection fault ip:7f91741ef3e3 sp:7fff3da51910 error:0 in libdbus.so[7f91741ef000+1000]
[  206.851100] traps: dbus-daemon[438] general protection fault ip:7f83940784ee sp:7fff00e65580 error:0 in libdbus.so[7f8394078000+1000]
[  617.689898] traps: atop[457] general protection fault ip:7f8e2d8a44ee sp:7ffd8f1b8a80 error:0 in libdbus.so[7f8e2d8a4000+1000]
[ 2549.561175] cron[631]: segfault at 46e ip 00007fc0fa0cbe7a sp 00007ffeda938908 error 4 in ld-2.31.so[7fc0fa0c3000+20000]
[ 2549.567406] Code: 0f 84 de fd ff ff 48 8b b3 28 03 00 00 eb 9d 48 c7 83 28 03 00 00 ff ff ff ff e9 c5 fd ff ff 90 41 56 49 89 fa 41 55 49 89 d5 <41> 0f b7 51 06 41 54 55 89 cd 41 0f b6 49 04 53 4c 89 cb 4c 8b 64
[ 6149.587035] cron[835]: segfault at 46e ip 00007fc0fa0cbe7a sp 00007ffeda938908 error 4 in ld-2.31.so[7fc0fa0c3000+20000]
[ 6149.593246] Code: 0f 84 de fd ff ff 48 8b b3 28 03 00 00 eb 9d 48 c7 83 28 03 00 00 ff ff ff ff e9 c5 fd ff ff 90 41 56 49 89 fa 41 55 49 89 d5 <41> 0f b7 51 06 41 54 55 89 cd 41 0f b6 49 04 53 4c 89 cb 4c 8b 64
```

My bet would be filesystem corruption or some apparmor shenanigans (given the first line, I have no experience with apparmor whatsoever).

**Comment by yuwata** [comment] 2022-09-13 08:52
Yeah, this sounds not a bug in systemd.

BTW, this is an upstream issue tracker. v247 is slightly old here, unfortunately. Closing.

Feel free to request to reopen if you still reproduce the issue on another machine with newer systemd (v250 or v251) or the current git HEAD.

**Closed as completed by yuwata** 2022-09-13 08:52 UTC
Labels: not-our-bug, version-too-ancient

**Comment by mbiebl** [comment] 2022-09-13 09:26
> [   17.858643] audit: type=1400 audit(1663050889.304:10): apparmor="DENIED" operation="open" profile="/usr/sbin/chronyd" name="/usr/local/lib/libdbus.so" pid=432 comm="chronyd" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

A locally installed libdbus, apparently. Probably not a good idea to have such a central library built and installed locally.

**Comment by supr4s** [comment] 2022-09-13 11:54
Hi everyone,

Thank you for your feedback. I still don't understand how it could have changed but I will keep looking. Thanks !
