### ISSUE TITLE
[Link] TransmitQueueLength not applied

### ISSUE THREAD

**Issue by onsimon** [systemd/systemd#30947] opened 2024-01-15 22:12 UTC
### systemd version the issue has been seen with

247

### Used distribution

Raspian 11 bullseye

### Linux kernel version used

6.1.21-v8+

### CPU architectures issue was seen on

aarch64

### Component

systemd-udevd

### Expected behaviour you didn't see

Expecting txquelen to be configured when the [Link] TransmitQueueLength parameter is set.

### Unexpected behaviour you saw

`ifconfig can0` shows `txqueuelen` set to `10` when `TransmitQueueLength=1024`

### Steps to reproduce the problem

Trying to set txqueuelen for a CAN networking using a .link file with:
```
[Match]
Name=can*

[Link]
TransmitQueueLength=1024
```

Reboot

`ifconfig can0`

Lots of other cases reported here: https://github.com/linux-can/can-utils/issues/68

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
~ $ ifconfig can0
can0: flags=193<UP,RUNNING,NOARP>  mtu 16
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 10  (UNSPEC)
        RX packets 150911  bytes 1121466 (1.0 MiB)
        RX errors 0  dropped 700  overruns 0  frame 0
        TX packets 8260  bytes 49133 (47.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by YHNdnzj** [comment] 2024-01-16 09:32
Sorry, this is the upstream bug tracker for systemd, and we only support the latest two versions here, namely v254 and v255. Please report to your distro if you're using older versions.

Closing. Feel free to ask for reopen if this can be reproduced on newer versions.

**Closed as completed by YHNdnzj** 2024-01-16 09:32 UTC
Labels: bug 🐛, udev, version-too-ancient

**Comment by yuwata** [comment] 2024-01-16 10:15
Please provide debugging logs of udevd.

Is it possible to change the queue length manually by e.g. `ip` command? If so, please provide the command.

**Comment by hellbe** [comment] 2024-01-16 11:14
@yuwata I can change txquelen with command `ip link set can0 txqueuelen 1024`

Also this udev rule works:
`SUBSYSTEM=="net", ACTION=="add|change", KERNEL=="can*", ATTR{tx_queue_len}="1024"`

Udev debug log: [udev-debug.log.log](https://github.com/systemd/systemd/files/13949095/udev-debug.log.log)

**Comment by hellbe** [comment] 2024-01-16 11:19
Sorry this is not a bug, I am running version 247. A single version short of the parameter being added. Will upgrade my system to the latest distro and it should be fine.

![image](https://github.com/systemd/systemd/assets/4107500/3ed63c04-2bd2-473f-a248-110adfa9eb9b)

**Comment by yuwata** [comment] 2024-01-16 13:01
Happy to hear that. Please let me know still newer version does not work.

**Comment by hellbe** [comment] 2024-01-17 09:34
Tested in Raspian 12 bookworm and it works fine

**Comment by mattie47** [comment] 2024-12-02 02:21
For anyone coming across this post on Google, I had to make my `link` config use `OriginalName` under the match statement, unlike OP with simply "Name":

```
pi@sdm-test:~ $ cat /etc/systemd/network/80-can-txqueue.link
#Config file goes in /etc/systemd/network/80-can-txqueue.link

[Match]
OriginalName=can*

[Link]
TransmitQueueLength=1000
```

And for completeness, this is the CAN config for one of my MCP2518FD interfaces:

```

pi@sdm-test:~ $ cat /etc/systemd/network/80-can0.network
# Config file goes in /etc/systemd/network/80-can0.network
# This replaces the historic /etc/network/interfaces configuration

[Match]
Name=can0

[CAN]
BitRate=250000
RestartSec=100ms
FDMode=no
BusErrorReporting=yes

[Link]
RequiredForOnline=no
```

**Comment by wingunder** [comment] 2024-12-21 10:46
Hi @mattie47
Thanks a lot for your example. It helped me a lot, and works like a charm! :)
With my setup, the following two lines were _not_ required, so I just commented them out:
```text
# FDMode=no
# RequiredForOnline=no
```
However, I simply can't get a change in the `TransmitQueueLength` to get updated, unless I physically reboot.
I've tried running the following in succession, but even that doesn't trigger a reload of the modified `TransmitQueueLength` value:
```sh
# systemctl daemon-reload
# systemctl restart systemd-networkd
```
I've also tried to bring the CAN interface down and back up again, but even that didn't trigger a reload of the modified `TransmitQueueLength` value:
```sh
# ip -d link set down can0
# ip -d link set up can0
```
Does anyone know if there's a way to load the `TransmitQueueLength`, only by using `systemctrl` to restart some service?

**Comment by yuwata** [comment] 2024-12-21 12:59
@wingunder .link file is used by systemd-udevd, rather than systemd-networkd. So, after .link file is modified, you need to do the following to make the new value applied.
```
udevadm control --reload # or systemctl reload systemd-udevd.service
udevadm trigger /sys/class/net/CAN_INTERFACE_NAME
```

**Comment by wingunder** [comment] 2024-12-21 15:43
Hi @yuwata,
Thanks a lot! :)
I tried out your suggestion on 2 of my systems, but it didn't reload the `TransmitQueueLength` value.
I then tried restarting `systemd-udev-trigger.service` and that worked!
So the only thing I need to do is, to run the following command on my systems:
```sh
# vi /etc/systemd/network/80-can-txqueue.link
# systemctl restart systemd-udev-trigger.service
```
Thanks again for your help.
So, `TransmitQueueLength` can be done without rebooting. :)

**Comment by yuwata** [comment] 2024-12-21 19:10
@wingunder Sorry, I forget `--action=add` option for `udevadm trigger`:
```
udevadm control --reload # or systemctl reload systemd-udevd.service
udevadm trigger --action=add /sys/class/net/CAN_INTERFACE_NAME
```
