### ISSUE TITLE
YouCompleteMe configuration relies on the autotools build

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#6071] opened 2017-06-01 19:45 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

> git master

The [ycm configuration](https://github.com/systemd/systemd/blob/d006926/.ycm_extra_conf.py#L6) relies on `make print-CFLAGS` and friends. Thus unless one has an autotools configured tree vim will always complain that make has failed.

**Comment by falconindy** [comment] 2017-06-01 19:53
I looked at this recently. We can rely on the default .ycm_extra_conf.py with 1 exception -- we need to define `compilation_database_folder` to the subdirectory name where meson was configured (e.g. build). We can probably add some autodetection logic to find it based on the existence of `*/build.ninja`.

Would be nice to make this zeroconf and remove the ycm file entirely, but I'm not convinced that's possible...

**Comment by fsateler** [comment] 2017-06-01 20:23
Interesting. It appears this is more zeroconf nowadays: https://github.com/Valloric/YouCompleteMe#c-family-semantic-completion . Maybe it is enough to add a meson target (run by default?) to generate `compile_commands.json`.

**Comment by falconindy** [comment] 2017-06-01 21:13
`compile_commands.json` already gets created by default when you run 'meson $dir'. The problem is getting zeroconf location of it.

**Comment by jhxie** [comment] 2017-11-26 19:03
In case anyone is still actively monitoring this issue, I have written a version of YouCompleteMe configuration file that does not depend on `make print-CFLAGS`; but unfortunately I am unable to make this fully "zero configuration" alike as there is no way to tell where the build tree is unless there is some sort of mechanism implemented in-place in the existing configuration process (for example, exporting an environment variable that points to the `systemd` build tree).

Feel free to have a look at my feature branch [here](https://github.com/jhxie/systemd/tree/ycm-meson-backend).

I could send a pull request should anyone considers this a valuable addition as I personally can not get YouCompleteMe to work properly on the `systemd` source tree without it giving warnings about not able to find header files included in the source files.

**Comment by keszybz** [comment] 2017-12-06 10:14
Fixed in #7476.

(@jhxie in the feature, please include one of the magic github incantations to automatically close the issue. See https://help.github.com/articles/closing-issues-using-keywords/.)

**Closed as completed by keszybz** 2017-12-06 10:14 UTC
Labels: build-system

**Comment by jhxie** [comment] 2017-12-06 14:12
Thanks for letting me know.
