### ISSUE TITLE
pid1: generate better dbus error messages when we refuse access to a unit because we can't read the label off the unit file

### ISSUE THREAD

**Issue by maage** [systemd/systemd#10643] opened 2018-11-05 14:52 UTC
**systemd version the issue has been seen with**
> systemd-239-6.git9f3aed1.fc29.x86_64

**Used distribution**
 > Fedora 29

**Expected behaviour you didn't see**
 > systemd-analyze plot provides me svg output
or better error message for example hint about erroneous file or need to run systemd-daemon-reload.

**Unexpected behaviour you saw**
 > No svg output at all, but message Failed to parse reply: Access denied

**Steps to reproduce the problem**

Install Fedora 29 minimal install
Create a timer and respective unit, enable timer, reboot
run: systemd-analyze plot > boot.svg
remove timer and unit files
run: systemd-analyze plot > boot-rm.svg

foo.service 
```
[Unit]
Description = test
[Service]
Type = oneshot
ExecStart = /usr/bin/true
```

foo.timer 
```
[Unit]
Description=test timer
[Timer]
OnBootSec=30s
[Install]
WantedBy=multi-user.target
```

If I use strace, I can get last message:
```
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="l\3\1\1A\0\0\0\3430\0\0]\0\0\0\5\1u\0;\3\0\0", iov_len=24}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = 24
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\6\1s\0\5\0\0\0:1.55\0\0\0\4\1s\0'\0\0\0org.freedesktop.DBus.Error.AccessDenied\0\10\1g\0\1s\0\0\7\1s\0\4\0\0\0:1.0\0\0\0\0<\0\0\0Failed to get file context on /etc/systemd/system/foo.timer.\0", iov_len=153}], msg_iovlen=1, msg_controllen=0, msg_flags=MSG_CMSG_CLOEXEC}, MSG_DONTWAIT|MSG_CMSG_CLOEXEC) = 153
writev(2, [{iov_base="Failed to parse reply: Access denied", iov_len=36}, {iov_base="\n", iov_len=1}], 2Failed to parse reply: Access denied
) = 37
```

To fix this problem I just need to replace removed files with empty files.

If I run `systemctl daemon-reload` I do get sv plot as expected.

**Comment by poettering** [comment] 2018-11-05 18:48
i am not sure this really constitues a bug... i mean what happens is this: you remove the unit files, then try to access them without reloading PID 1. When you access them and selinux is enabled we'll read the selinux label of the unit files in order to query the selinux policy whether you may actually do that. Now, since they are removed we can't read the label off the unit files, and hence refuse the access.

I mean, what else could we do?

1. We could read the label whenever we load the unit files and cache it. This would mean our selinux checks would follow our own reload cycle instead of the selinux policy reload cycle.
2. We could simply allow the access if we can't determine the label from disk. 

Of course the second issue is very much questionable security-wise, and I am not sure the first issue is in the interest of the selinux folks either...

(Another option would be to turn off selinux btw)

So, neither option appears really desirable to me. Maybe the lesson to learn is: this is not actually a bug, but as long as the state on disk and what you are querying is not in sync (i.e. as long as you have not issued systemctl daemon-reload) then it might be that you don#t get access to stuff, and maybe that's not wrong...

**Comment by maage** [comment] 2018-11-05 19:04
Would it be possible to parse the reply message "Failed to get file context on /etc/systemd/system/foo.timer." from dbus message and then show it like:

Access denied: Failed to get file context on /etc/systemd/system/foo.timer.

Because after this you get the hint that this is because of that file and then you can jump to conclusions like, file I removed the file some days ago and maybe I need to run "systemctl daemon-reload". Information clearly is available but not used.

Is there security implications why dbus messages are not parsed or textual information there not shown?

Currently "Failed to parse reply: Access denied" just does not have enough information to jump to conclusions.

**Comment by poettering** [comment] 2018-11-05 19:41
true, we certainly could pass on more useful errors in this case. the infrastructure certainly exists.

**Comment by poettering** [comment] 2018-11-05 19:42
I relabelled the issue so that i becomes about requesting the better error strings

**Comment by cgzones** [comment] 2020-07-22 13:07
I think this a duplicate of #6450.

On Debian with systemd `245.6-3` I am not able to reproduce the issue (in enforced mode):

```
$ touch /etc/systemd/system/foo.timer
$ systemctl daemon-reload
$ rm -f /etc/systemd/system/foo.timer
$ systemctl status foo.timer
Unit foo.timer could not be found.
```

**Comment by poettering** [comment] 2020-08-28 20:14
Closing as duplicate of #6450

**Closed as completed by poettering** 2020-08-28 20:14 UTC
Labels: pid1, selinux, needs-better-log-message
