### ISSUE TITLE
systemd-journald: dmesg: Failed to write entry (XX items, YY bytes), ignoring: Cannot allocate memory

### ISSUE THREAD

**Issue by alxchk** [systemd/systemd#11537] opened 2019-01-23 07:14 UTC
**systemd version the issue has been seen with**

```
# systemctl --version
systemd 240
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

```
# dpkg -l systemd
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  systemd        240-4        armhf        system and service manager

```

```
# lsb_release -a

No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux buster/sid
Release:        stable-updates
Codename:       sid
```

```
# dmesg | tail -n 20
[388756.293399] systemd-journald[5681]: Failed to write entry (19 items, 605 bytes), ignoring: Cannot allocate memory
[388756.293916] systemd-journald[5681]: Failed to write entry (19 items, 586 bytes), ignoring: Cannot allocate memory
[388756.298738] systemd-journald[5681]: Failed to write entry (19 items, 548 bytes), ignoring: Cannot allocate memory
[388756.299132] systemd-journald[5681]: Failed to write entry (19 items, 551 bytes), ignoring: Cannot allocate memory
[388828.110703] systemd-journald[5681]: Failed to write entry (22 items, 589 bytes), ignoring: Cannot allocate memory
[388828.113676] systemd-journald[5681]: Failed to write entry (22 items, 583 bytes), ignoring: Cannot allocate memory
[388828.115622] systemd-journald[5681]: Failed to write entry (22 items, 587 bytes), ignoring: Cannot allocate memory
[388828.118412] systemd-journald[5681]: Failed to write entry (22 items, 575 bytes), ignoring: Cannot allocate memory
[388828.122789] systemd-journald[5681]: Failed to write entry (22 items, 572 bytes), ignoring: Cannot allocate memory
[388828.125042] systemd-journald[5681]: Failed to write entry (22 items, 583 bytes), ignoring: Cannot allocate memory
[388828.127044] systemd-journald[5681]: Failed to write entry (22 items, 581 bytes), ignoring: Cannot allocate memory
[388828.129446] systemd-journald[5681]: Failed to write entry (22 items, 580 bytes), ignoring: Cannot allocate memory
[388828.133286] systemd-journald[5681]: Failed to write entry (22 items, 584 bytes), ignoring: Cannot allocate memory
[388828.135275] systemd-journald[5681]: Failed to write entry (22 items, 590 bytes), ignoring: Cannot allocate memory
[388841.041268] systemd-journald[5681]: Failed to write entry (19 items, 691 bytes), ignoring: Cannot allocate memory
[388841.043257] systemd-journald[5681]: Failed to write entry (19 items, 706 bytes), ignoring: Cannot allocate memory
[389018.314973] systemd-journald[5681]: Failed to write entry (19 items, 605 bytes), ignoring: Cannot allocate memory
[389018.315161] systemd-journald[5681]: Failed to write entry (19 items, 586 bytes), ignoring: Cannot allocate memory
[389018.315302] systemd-journald[5681]: Failed to write entry (19 items, 548 bytes), ignoring: Cannot allocate memory
[389018.315420] systemd-journald[5681]: Failed to write entry (19 items, 551 bytes), ignoring: Cannot allocate memory
```

```
# dmesg | grep "Failed to write entry" | wc -l
217
```

```
# journalctl -b -u systemd-journald -n 30 -o short-monotonic
-- Logs begin at Mon 2019-01-14 23:54:47 EET, end at Wed 2019-01-23 08:43:37 EET. --
[    6.406681] x systemd-journald[161]: Journal started
[    6.407188] x systemd-journald[161]: Runtime journal (/run/log/journal/879e7f00f4894d5c864c345af25db389) is 3.7M, max 30.0M, 26.2M free.
[    7.538552] x systemd-journald[161]: Time spent on flushing to /var is 796.731ms for 288 entries.
[    7.538552] x systemd-journald[161]: System journal (/var/log/journal/879e7f00f4894d5c864c345af25db389) is 118.6M, max 100.0M, 0B free.
[231573.847900] x systemd-journald[5591]: Journal started
[231573.848640] x systemd-journald[5591]: System journal (/var/log/journal/879e7f00f4894d5c864c345af25db389) is 118.6M, max 100.0M, 0B free.
[231611.741207] x systemd-journald[5591]: Journal stopped
[231612.020909] x systemd-journald[5681]: Journal started
[231612.021785] x systemd-journald[5681]: System journal (/var/log/journal/879e7f00f4894d5c864c345af25db389) is 118.6M, max 256.0M, 137.3M free.
```

```
# journalctl --verify
PASS: /var/log/journal/879e7f00f4894d5c864c345af25db389/system.journal                                                                                             
PASS: /var/log/journal/879e7f00f4894d5c864c345af25db389/user-1000.journal                                                                                          
PASS: /var/log/journal/879e7f00f4894d5c864c345af25db389/system@080dc8395d40437d88e5fe4bca73d7ba-000000000000db06-00057fbf3179527e.journal                          
PASS: /var/log/journal/879e7f00f4894d5c864c345af25db389/system@080dc8395d40437d88e5fe4bca73d7ba-0000000000014a29-00057fd89555a36a.journal                          
c7fe18: Unused data (entry_offset==0)                                                                                                                              
c7fe80: Unused data (entry_offset==0)                                                                                                                              
c7fed0: Unused data (entry_offset==0)                                                                                                                              
PASS: /var/log/journal/879e7f00f4894d5c864c345af25db389/system@080dc8395d40437d88e5fe4bca73d7ba-000000000000e162-00057fbf360e6726.journal                          
PASS: /var/log/journal/879e7f00f4894d5c864c345af25db389/user-1000@099252eb837e4c8184a7fb4bc4d1be3e-00000000000108d3-00057fbf7bf1f3a9.journal                       
PASS: /var/log/journal/879e7f00f4894d5c864c345af25db389/system@080dc8395d40437d88e5fe4bca73d7ba-0000000000011bab-00057fc15d0876cb.journal                          
PASS: /var/log/journal/879e7f00f4894d5c864c345af25db389/user-1000@099252eb837e4c8184a7fb4bc4d1be3e-0000000000011bd4-00057fc16d31fecc.journal                       
7ffdf0: Unused data (entry_offset==0)                                                                                                                              
PASS: /var/log/journal/879e7f00f4894d5c864c345af25db389/system@88476ed100524402a3e10d7720522bbb-0000000000016b83-00057ff3a434c30f.journal                          
PASS: /var/log/journal/879e7f00f4894d5c864c345af25db389/user-1000@fc233f5716454818b93c21ad1055b34b-000000000000917f-00057f7217e1fa28.journal                       
PASS: /var/log/journal/879e7f00f4894d5c864c345af25db389/system@080dc8395d40437d88e5fe4bca73d7ba-000000000000b8c1-00057f98bd767634.journal                          
PASS: /var/log/journal/879e7f00f4894d5c864c345af25db389/user-1000@fc233f5716454818b93c21ad1055b34b-000000000000b8ff-00057f98d4dd414a.journal                       
PASS: /var/log/journal/879e7f00f4894d5c864c345af25db389/user-1000@099252eb837e4c8184a7fb4bc4d1be3e-0000000000014a31-00057fd8961e580c.journal                       
PASS: /var/log/journal/879e7f00f4894d5c864c345af25db389/system@88476ed100524402a3e10d7720522bbb-0000000000018df7-00057ff5e78afdcf.journal                          
PASS: /var/log/journal/879e7f00f4894d5c864c345af25db389/user-1000@4892b31dd3f44fb7b7ae4a23684475fe-0000000000018e59-00057ff5eb0cf2b5.journal  
```

```
# free -h
              total        used        free      shared  buff/cache   available
Mem:           2,0G        691M         63M        876K        1,2G        1,2G
Swap:          1,0G        157M        848M
```

```
# df -h /var/log/journal
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0     60G  3,4G   56G   6% /containers
```

```
# ls -ld /var/log/journal
lrwxrwxrwx 1 root systemd-journal 26 янв  8 10:25 /var/log/journal -> /containers/system/journal
```

```
# journalctl --disk-usage
Archived and active journals take up 166.6M in the file system.     
```

```
# grep -v "^#" /etc/systemd/journald.conf

[Journal]
Storage=persistent
Compress=yes
Seal=no
SystemMaxUse=256M
RuntimeMaxUse=30M

MaxLevelStore=info
MaxLevelSyslog=info
MaxLevelKMsg=debug
MaxLevelConsole=debug
MaxLevelWall=emerg

SyncIntervalSec=10m
```

**Unexpected behaviour you saw**
> systemd-journald push a lot of error (?) messages to dmesg.

**Comment by alxchk** [comment] 2019-01-25 12:33
This happens then journald consume all (?) virtual space:

```
:   /lib/systemd/systemd-journald                                                                                                                                                                     
000ae000   4104K rw---   [ anon ]                            
004b0000     92K r-x-- /lib/systemd/systemd-journald
004d7000      4K r---- /lib/systemd/systemd-journald
004d8000      4K rw--- /lib/systemd/systemd-journald
0068f000  12904K rw---   [ anon ]
01340000 184680K rw---   [ anon ]
0c79a000   8192K rw-s- /containers/system/journal/879e7f00f4894d5c864c345af25db389/system.journal
0cf9a000 1028052K rw---   [ anon ]
4bb8f000      4K -----   [ anon ]
4bb90000   8192K rw---   [ anon ]
4c390000   8192K rw-s- /containers/system/journal/879e7f00f4894d5c864c345af25db389/user-1000.journal
4cb90000   8192K rw-s- /containers/system/journal/879e7f00f4894d5c864c345af25db389/system.journal
4d390000 629964K rw---   [ anon ]
73cc0000 494532K rw---   [ anon ]
92115000 535572K rw---   [ anon ]
b2c1a000      4K -----   [ anon ]
b2c1b000   8192K rw---   [ anon ]
b341b000      4K -----   [ anon ]
b341c000  20504K rw---   [ anon ]
b4822000   8192K rw-s- /containers/system/journal/879e7f00f4894d5c864c345af25db389/user-1000@4892b31dd3f44fb7b7ae4a23684475fe-000000000001e1e2-0005800d37823ee7.journal
b5022000   4104K rw---   [ anon ]
b551d000  19500K rw---   [ anon ]
b6828000     80K r-x-- /lib/arm-linux-gnueabihf/libudev.so.1.6.11
b683c000     60K ----- /lib/arm-linux-gnueabihf/libudev.so.1.6.11
b684b000      4K r---- /lib/arm-linux-gnueabihf/libudev.so.1.6.11
b684c000      4K rw--- /lib/arm-linux-gnueabihf/libudev.so.1.6.11
b684d000     76K r-x-- /lib/arm-linux-gnueabihf/libgpg-error.so.0.25.0
b6860000     60K ----- /lib/arm-linux-gnueabihf/libgpg-error.so.0.25.0
b686f000      4K r---- /lib/arm-linux-gnueabihf/libgpg-error.so.0.25.0
b6870000      4K rw--- /lib/arm-linux-gnueabihf/libgpg-error.so.0.25.0
b6871000     28K r-x-- /lib/arm-linux-gnueabihf/libjson-c.so.3.0.1
b6878000     60K ----- /lib/arm-linux-gnueabihf/libjson-c.so.3.0.1
b6887000      4K r---- /lib/arm-linux-gnueabihf/libjson-c.so.3.0.1
b6888000      4K rw--- /lib/arm-linux-gnueabihf/libjson-c.so.3.0.1
b6889000     28K r-x-- /usr/lib/arm-linux-gnueabihf/libargon2.so.1
b6890000     60K ----- /usr/lib/arm-linux-gnueabihf/libargon2.so.1
b689f000      4K r---- /usr/lib/arm-linux-gnueabihf/libargon2.so.1
b68a0000      4K rw--- /usr/lib/arm-linux-gnueabihf/libargon2.so.1
b68a1000    284K r-x-- /lib/arm-linux-gnueabihf/libdevmapper.so.1.02.1
b68e8000     60K ----- /lib/arm-linux-gnueabihf/libdevmapper.so.1.02.1
b68f7000      4K r---- /lib/arm-linux-gnueabihf/libdevmapper.so.1.02.1
b68f8000     12K rw--- /lib/arm-linux-gnueabihf/libdevmapper.so.1.02.1
b68fb000      4K rw---   [ anon ]
b68fc000     20K r-x-- /lib/arm-linux-gnueabihf/libuuid.so.1.3.0
b6901000     60K ----- /lib/arm-linux-gnueabihf/libuuid.so.1.3.0
b6910000      4K r---- /lib/arm-linux-gnueabihf/libuuid.so.1.3.0
b6911000      4K rw--- /lib/arm-linux-gnueabihf/libuuid.so.1.3.0
b6912000     12K r-x-- /lib/arm-linux-gnueabihf/libattr.so.1.1.0
b6915000     60K ----- /lib/arm-linux-gnueabihf/libattr.so.1.1.0
b6924000      4K r---- /lib/arm-linux-gnueabihf/libattr.so.1.1.0
b6925000      4K rw--- /lib/arm-linux-gnueabihf/libattr.so.1.1.0
b6926000      8K rw---   [ anon ]
b6928000      8K r-x-- /lib/arm-linux-gnueabihf/libdl-2.28.so
b692a000     60K ----- /lib/arm-linux-gnueabihf/libdl-2.28.so
b6939000      4K r---- /lib/arm-linux-gnueabihf/libdl-2.28.so
..
b6b98000      4K rw--- /usr/lib/arm-linux-gnueabihf/libip4tc.so.0.1.0                                                                                                  
b6b99000    628K r-x-- /lib/arm-linux-gnueabihf/libgcrypt.so.20.2.4
b6c36000     64K ----- /lib/arm-linux-gnueabihf/libgcrypt.so.20.2.4
b6c46000      4K r---- /lib/arm-linux-gnueabihf/libgcrypt.so.20.2.4
b6c47000     16K rw--- /lib/arm-linux-gnueabihf/libgcrypt.so.20.2.4
b6c4b000    204K r-x-- /lib/arm-linux-gnueabihf/libcryptsetup.so.12.3.0
b6c7e000     64K ----- /lib/arm-linux-gnueabihf/libcryptsetup.so.12.3.0
b6c8e000      4K r---- /lib/arm-linux-gnueabihf/libcryptsetup.so.12.3.0
b6c8f000      4K rw--- /lib/arm-linux-gnueabihf/libcryptsetup.so.12.3.0
b6c90000     20K r-x-- /lib/arm-linux-gnueabihf/libacl.so.1.1.0        
b6c95000     60K ----- /lib/arm-linux-gnueabihf/libacl.so.1.1.0       
b6ca4000      4K r---- /lib/arm-linux-gnueabihf/libacl.so.1.1.0   
b6ca5000      4K rw--- /lib/arm-linux-gnueabihf/libacl.so.1.1.0   
b6ca6000     12K r-x-- /lib/arm-linux-gnueabihf/libcap.so.2.25    
b6ca9000     60K ----- /lib/arm-linux-gnueabihf/libcap.so.2.25      
b6cb8000      4K r---- /lib/arm-linux-gnueabihf/libcap.so.2.25      
b6cb9000      4K rw--- /lib/arm-linux-gnueabihf/libcap.so.2.25      
b6cba000     20K r-x-- /lib/arm-linux-gnueabihf/librt-2.28.so       
b6cbf000     60K ----- /lib/arm-linux-gnueabihf/librt-2.28.so     
b6cce000      4K r---- /lib/arm-linux-gnueabihf/librt-2.28.so         
b6ccf000      4K rw--- /lib/arm-linux-gnueabihf/librt-2.28.so         
b6cd0000     92K r-x-- /lib/arm-linux-gnueabihf/libselinux.so.1       
b6ce7000     64K ----- /lib/arm-linux-gnueabihf/libselinux.so.1       
b6cf7000      4K r---- /lib/arm-linux-gnueabihf/libselinux.so.1    
b6cf8000      4K rw--- /lib/arm-linux-gnueabihf/libselinux.so.1    
b6cf9000      4K rw---   [ anon ]                                  
b6cfa000   1340K r-x-- /lib/systemd/libsystemd-shared-240.so       
b6e49000     64K ----- /lib/systemd/libsystemd-shared-240.so           
b6e59000    284K r---- /lib/systemd/libsystemd-shared-240.so           
b6ea0000      4K rw--- /lib/systemd/libsystemd-shared-240.so           
b6ea1000      4K rw---   [ anon ]                                      
b6ea2000    912K r-x-- /lib/arm-linux-gnueabihf/libc-2.28.so    
b6f86000     64K ----- /lib/arm-linux-gnueabihf/libc-2.28.so   
b6f96000      8K r---- /lib/arm-linux-gnueabihf/libc-2.28.so   
b6f98000      4K rw--- /lib/arm-linux-gnueabihf/libc-2.28.so   
b6f99000     12K rw---   [ anon ]                             
b6f9c000     72K r-x-- /lib/arm-linux-gnueabihf/libpthread-2.28.so
b6fae000     60K ----- /lib/arm-linux-gnueabihf/libpthread-2.28.so
b6fbd000      4K r---- /lib/arm-linux-gnueabihf/libpthread-2.28.so
b6fbe000      4K rw--- /lib/arm-linux-gnueabihf/libpthread-2.28.so
b6fbf000      8K rw---   [ anon ]                                
b6fc1000     96K r-x-- /lib/arm-linux-gnueabihf/ld-2.28.so   
b6fe4000      4K rw-s- /containers/system/journal/879e7f00f4894d5c864c345af25db389/user-1000.journal
b6fe5000      4K rw-s- /containers/system/journal/879e7f00f4894d5c864c345af25db389/system.journal
b6fe6000      4K rw-s- /run/systemd/journal/kernel-seqnum      
b6fe7000      8K rw---   [ anon ]                                
b6fe9000      4K r---- /lib/arm-linux-gnueabihf/ld-2.28.so       
b6fea000      4K rw--- /lib/arm-linux-gnueabihf/ld-2.28.so       
b6feb000 127224K rw---   [ anon ]                                
bedf2000    132K rw---   [ stack ]                                 
bef6e000      4K r-x--   [ anon ]                                  
bef6f000      4K r----   [ anon ]                                  
bef70000      4K r-x--   [ anon ]                                  
ffff0000      4K r-x--   [ anon ]                               
 total  3118456K                    
```

This observation was done with 11527 patch

**Comment by yuwata** [comment] 2019-01-25 17:09
Maybe, duplicate of #11502.

**Comment by poettering** [comment] 2019-01-26 11:11
@alxchk do the fixes discussed in #11502 fix the issue for you?

**Comment by alxchk** [comment] 2019-01-26 11:21
Actually checking this. I built systemd with that patch. As for now i don't have the issue.

**Comment by yuwata** [comment] 2019-01-28 09:16
OK. Let's close this.

**Closed as completed by yuwata** 2019-01-28 09:16 UTC
Labels: journal, duplicate
