### ISSUE TITLE
Kernel-install (of systemd-boot) issue with $BOOT_DIR_ABS. Fails to build initramfs if more than one loader folder exists.

### ISSUE THREAD

**Issue by spxak1** [systemd/systemd#33151] opened 2024-06-01 14:09 UTC
### systemd version the issue has been seen with

255

### Used distribution

Fedora 40

### Linux kernel version used

6.8.11-300.fc40.x86_64

### CPU architectures issue was seen on

x86_64

### Component

kernel-install

### Expected behaviour you didn't see

kernel-install installs both ```vmlinuz``` and ```intitramfs``` in ```/boot/efi/$MACHINE_ID/$KERNEL_VERSION``` on systems where the bootloader has been changed from grub to systemd-boot, or systems previously using a ```/boot``` partition which has now been merged to the ```/```.

### Unexpected behaviour you saw

kernel-install installs only the kernel ```vmlinuz``` and **no** initramfs, with ```/usr/lib/kernel/install.d/50-dracut.install``` failing and complaining the directory expected is not present.

### Steps to reproduce the problem

* Install Fedora with ```/boot``` partition.
* install systemd-boot (all steps required)
* Upgrade including a new kernel or
* Use ```kernel-install``` to install new kernel.

I have written a couple of notes about the issue here: https://github.com/spxak1/weywot/blob/main/guides/fedora.sdboot.fail.md

Please read for a complete description of the issue and my (poor?) understanding of it.

From ```kernel-install``` source:

~~~
if [[ -d /efi/loader/entries ]] || [[ -d /efi/$MACHINE_ID ]]; then
    BOOT_DIR_ABS="/efi/$MACHINE_ID/$KERNEL_VERSION"
elif [[ -d /boot/loader/entries ]] || [[ -d /boot/$MACHINE_ID ]]; then
    BOOT_DIR_ABS="/boot/$MACHINE_ID/$KERNEL_VERSION"
elif [[ -d /boot/efi/loader/entries ]] || [[ -d /boot/efi/$MACHINE_ID ]]; then
    BOOT_DIR_ABS="/boot/efi/$MACHINE_ID/$KERNEL_VERSION"
elif mountpoint -q /efi; then
    BOOT_DIR_ABS="/efi/$MACHINE_ID/$KERNEL_VERSION"
elif mountpoint -q /boot/efi; then
    BOOT_DIR_ABS="/boot/efi/$MACHINE_ID/$KERNEL_VERSION"
else
    BOOT_DIR_ABS="/boot/$MACHINE_ID/$KERNEL_VERSION"
fi
~~~

BOOT_DIR_ABS is assigned after the **first** find. And since ```/boot``` is checked before ```/boot/efi```. Swapping the order around can  fix this issue, without other effects (probably).

Thank you.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
if [[ -d /efi/loader/entries ]] || [[ -d /efi/$MACHINE_ID ]]; then
    BOOT_DIR_ABS="/efi/$MACHINE_ID/$KERNEL_VERSION"
elif [[ -d /boot/loader/entries ]] || [[ -d /boot/$MACHINE_ID ]]; then
    BOOT_DIR_ABS="/boot/$MACHINE_ID/$KERNEL_VERSION"
elif [[ -d /boot/efi/loader/entries ]] || [[ -d /boot/efi/$MACHINE_ID ]]; then
    BOOT_DIR_ABS="/boot/efi/$MACHINE_ID/$KERNEL_VERSION"
elif mountpoint -q /efi; then
    BOOT_DIR_ABS="/efi/$MACHINE_ID/$KERNEL_VERSION"
elif mountpoint -q /boot/efi; then
    BOOT_DIR_ABS="/boot/efi/$MACHINE_ID/$KERNEL_VERSION"
else
    BOOT_DIR_ABS="/boot/$MACHINE_ID/$KERNEL_VERSION"
fi
```

**Comment by yuwata** [comment] 2024-06-01 23:53
kernel-install is rewritten in C by https://github.com/systemd/systemd/commit/42551ea7e923bac5df12b20e3e735a487d38dcd5 (v254), and the mentioned shell code is not used anymore.
Do you really use v255 ??

**Comment by spxak1** [comment] 2024-06-02 00:32
> kernel-install is rewritten in C by [42551ea](https://github.com/systemd/systemd/commit/42551ea7e923bac5df12b20e3e735a487d38dcd5) (v254), and the mentioned shell code is not used anymore. Do you really use v255 ??

I am indeed on 255. 
~~~
systemctl --version
systemd 255 (255.7-1.fc40)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP -GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
~~~

Admittedly the code I pasted is from the old script, as I don't know C. 

However,  ```50-dracut.install``` reads ```BOOT_DIR_ABS="$3"``` from ```kernel-install```, and evidently if there is a ```loader``` folder in ```/boot``` it assigns ````BOOT_DIR_ABS``` to ````/boot/$MACHINE_ID/$KERNEL_VER```.

Once that folder is removed, and only ```/boot/efi/loaders``` is present, then ```BOOT_DIR_ABS``` is assigned to ```/boot/efi/$MACHINE_ID/$KERNEL_VER```.

So, while ```kernel-install``` is not using that shell code, it evidently follows the same procedure. 

So please ignore the code I used. As I cannot understand C, I cannot tell from the source code if indeed the same procedure is used. I can only deduce it from the outcome of the process. 

Thank you for your attention.

**Comment by yuwata** [comment] 2024-06-02 01:07
I guess you have both XBOOTLDR and ESP partitions, and ESP is mounted under XBOOTLDR, that is not recommended, and you may need some tweaks, like you already tried.

Please see https://uapi-group.org/specifications/specs/boot_loader_specification/#mount-points.
This is not a bug. Closing.

**Closed as completed by yuwata** 2024-06-02 01:07 UTC
Labels: bug 🐛, needs-reporter-feedback ❓, kernel-install

**Comment by spxak1** [comment] 2024-06-02 10:08
> I guess you have both XBOOTLDR and ESP partitions, and ESP is mounted under XBOOTLDR, that is not recommended, and you may need some tweaks, like you already tried.
> 
> Please see https://uapi-group.org/specifications/specs/boot_loader_specification/#mount-points. This is not a bug. Closing.

Thank you for the pointer. Sadly Fedora still uses nested mount points, so this is going to be a problem. Not a significant one, but certainly not solvable without tweaking.

Having said that, may I ask, how come ```kernel-install``` reads ```BOOT_ROOT``` from ```/etc/kernel/install.conf``` as ```/boot/efi``` and uses it to place the kernel correctly, but it fails to place the initramfs in the same directory?

Thanks for your time.

**Comment by yuwata** [comment] 2024-06-02 15:08
50-dracut.install is provided by [dracut](https://github.com/dracutdevs/dracut/blob/master/install.d/50-dracut.install). Please contact the dracut team about the specific plugin issue.

Note, `kernel-install inspect` is a good starting point to investigate issue.

**Comment by spxak1** [comment] 2024-06-02 18:51
> 50-dracut.install is provided by [dracut](https://github.com/dracutdevs/dracut/blob/master/install.d/50-dracut.install). Please contact the dracut team about the specific plugin issue.
> 
> Note, `kernel-install inspect` is a good starting point to investigate issue.

Thank you for taking the time.  I will pursue this further myself. 

Take care.
