### ISSUE TITLE
systemd-journal 100% CPU usage for high frequency logging.

### ISSUE THREAD

**Issue by nrvnrvn** [systemd/systemd#5820] opened 2017-04-26 16:24 UTC
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232/233

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> CoreOS https://coreos.com/releases/#1353.6.0
> Ubuntu Server 17.04
> Archlinux (fresh install as of today)

### In case of bug report: Expected behaviour you didn't see

> Less than 100% CPU usage by systemd-journal

### In case of bug report: Unexpected behaviour you saw

> 100% CPU usage by systemd-journal

### In case of bug report: Steps to reproduce the problem

> `systemd-run sh -c "while :; do echo ok; done"`

**Comment by evverx** [comment] 2017-04-26 16:53
I think this issue is a duplicate of https://github.com/systemd/systemd/issues/5102.

**Comment by mbiebl** [comment] 2017-04-26 19:09
Yeah, closing as duplicate

**Closed as completed by mbiebl** 2017-04-26 19:09 UTC
Labels: journal, duplicate
