### ISSUE TITLE
systemd:amd64 (252-2 -> 252.1-1) brakes suspend/resume

### ISSUE THREAD

**Issue by axet** [systemd/systemd#25356] opened 2022-11-11 18:30 UTC
### systemd version the issue has been seen with

252.1-1

### Used distribution

debian bookworm

### Linux kernel version used

6.0.0-3-amd64

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

suspend resume to work

### Unexpected behaviour you saw

after suspend resume I unable to move any windows. I had to switch to console (alt+f2) and press ctrl+alt+del to reboot

### Steps to reproduce the problem

call 'systemctl suspend' or close notebook lid

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
all hardware logs

* http://linux-hardware.org/?probe=59aa7d31d8
```

Manually rolling back to 252-2 makes system to work again, windows moves.

EDIT: updated logs https://linux-hardware.org/?probe=b5eb364ac6

**Comment by yuwata** [comment] 2022-11-13 05:29
@axet and @Wallaby111 Could you bisect between v252 and v252.1 ? I cannot find suspicious commits...

**Comment by axet** [comment] 2022-11-13 05:43
@yuwata I do not see 252.1 tag, What am I missing?

debian changelog saying it is here:

* https://tracker.debian.org/media/packages/s/systemd/changelog-252.1-1

**Comment by yuwata** [comment] 2022-11-13 05:51
You can find v252.1 tag from https://github.com/systemd/systemd-stable

**Comment by axet** [comment] 2022-11-13 08:38
'make install' breaks keyboard and mouse on my system (no longer pressed, or moved, even alt+f1 no longer works). running 'apt reinstall systemd' makes it unbootable. I'm doing something wrong here. rebuilding systemd more dangerous then rebuilding kernel

**Comment by solsticedhiver** [comment] 2022-11-16 01:29
I am commenting here because other bugs have closed as duplicates.

I was using suspend-then-hibernate on my desktop with 251.7 and this was working as expected. aka suspending to RAM, and then if not waken up, hibernating after HibernateDelaySec time.

I am very disapointed about the behavior change that seems to use a % of battery to activate the hibernate action. As this would mean, this would not work anymore on a desktop?

Or this a bug? exaplaining, why suspend-then-hibernate does not hibernate here, now with 252.1 ?

**Comment by yuwata** [comment] 2022-11-16 04:22
@solsticedhiver That's already reported and discussed at #25269. And I am already working on the issue. See #25374.

**Comment by n-peugnet** [comment] 2022-11-17 15:39
This is strange as I had a similar problem on Debian Bookworm with 252-2 already (didn't test with 252.1-1).
Also with the `linux-image-6.0.0-3-amd64` from Debian (6.0.5-1 really).

And it seems I am not the only one : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1023483.

**Comment by Wallaby111** [comment] 2022-11-18 18:29
Upgrading to the latest Arch kernel seems to have fixed the issue for me as well. Now on 6.0.9-arch1-1 and can both suspend/resume and suspend-then-hibernate/resume with no issues. It did have an issue getting out of [betterlockscreen](https://github.com/betterlockscreen/betterlockscreen) when its auto-lock on suspend service was enabled, but quickly disabling then enabling it fixed that right away.

**Comment by yuwata** [comment] 2022-11-19 06:34
Thank you for the reports. So, let's drop the regression tag.

@n-peugnet Could you also test with newer kernels?

**Comment by testudomarginata** [comment] 2022-11-19 07:22
Hi,
Debian bookworm linux-image-6.0.0-4-amd64 still has the same issue for me, system is not entering hibernate after HibernateDelaySec (although after reading through the other issues linked from here, this might be new and expected behaviour?) and then the screen remains black on wake-up. 
Since downgrading to systemd-251.6-1 fixes this without changing any other package, would this not be considered a systemd regression?
Please let me know if I can supply any more information.
Regards,
Sönke

**Comment by axet** [comment] 2022-11-19 07:35
Ok. Bug not complete went out. Now after suspend / resume. My keyboard has 5-10 seconds delay before typing keys. So weird. Also I got gnome-terminal error in journalctl:

```
ноя 19 10:29:34 axet-laptop gedit[31158]: Unable to connect to ibus: Error receiving data: Connection reset by peer
ноя 19 10:29:34 axet-laptop systemd[1]: system-systemd\x2dcoredump.slice: Consumed 3.764s CPU time.
ноя 19 10:29:34 axet-laptop firefox-esr.desktop[26491]: [Parent 26491, Main Thread] WARNING: Process Key Event failed: The connection is closed.: 'glib warni>
ноя 19 10:29:34 axet-laptop firefox-esr.desktop[26491]: [Parent 26491, Main Thread] WARNING: Process Key Event failed: The connection is closed.: 'glib warni>
ноя 19 10:29:34 axet-laptop firefox-esr.desktop[26491]: [Parent 26491, Main Thread] WARNING: Process Key Event failed: The connection is closed.: 'glib warni>
ноя 19 10:29:34 axet-laptop gnome-terminal-[2106]: Process Key Event failed: The connection is closed.
ноя 19 10:29:34 axet-laptop gnome-terminal-[2106]: Process Key Event failed: The connection is closed.
ноя 19 10:29:34 axet-laptop gnome-terminal-[2106]: Process Key Event failed: The connection is closed.
ноя 19 10:29:34 axet-laptop gnome-terminal-[2106]: Process Key Event failed: The connection is closed.
ноя 19 10:29:34 axet-laptop gnome-terminal-[2106]: Process Key Event failed: The connection is closed.
ноя 19 10:29:34 axet-laptop gnome-terminal-[2106]: Process Key Event failed: The connection is closed.
ноя 19 10:29:34 axet-laptop gnome-terminal-[2106]: Process Key Event failed: The connection is closed.
ноя 19 10:29:34 axet-laptop gnome-terminal-[2106]: Process Key Event failed: The connection is closed.
ноя 19 10:29:34 axet-laptop gnome-terminal-[2106]: Process Key Event failed: The connection is closed.
ноя 19 10:29:34 axet-laptop systemd[1]: Closed Load/Save RF Kill Switch Status /dev/rfkill Watch.
ноя 19 10:29:34 axet-laptop gnome-terminal-[2106]: Process Key Event failed: The connection is closed.
ноя 19 10:29:34 axet-laptop gnome-terminal-[2106]: Process Key Event failed: The connection is closed.
ноя 19 10:29:34 axet-laptop gnome-terminal-[2106]: Process Key Event failed: The connection is closed.
ноя 19 10:29:34 axet-laptop gnome-terminal-[2106]: Process Key Event failed: The connection is closed.
``

**Comment by yuwata** [comment] 2022-11-19 09:11
@testudomarginata Your issue is not relevant, and is #25269. See also https://github.com/systemd/systemd/issues/25356#issuecomment-1316310805.

**Comment by axet** [comment] 2022-11-19 12:43
Bug get back! All keys get frozen again and I unable to move windows. To summarize: 1) random 2) kernel in-depended 3) keys can be delayed 4) keys can be ignored.

hw-probe

* https://linux-hardware.org/?probe=359c282b27

journalctl after resume 15:30:

* https://pastebin.com/PK6Pd9ak

**Comment by Wallaby111** [comment] 2022-11-20 20:01
After reading through the comments on [#25269](https://github.com/systemd/systemd/issues/25269) and seeing @yuwata say that HibernateDelaySeconds= is now hijacked as an interval for measuring discharge rate, I did a little testing. At least on my system, it seems that when going in to suspend-then-hibernate I don't have the resume issues until after that HibernateDelaySeconds= has passed. 

I tested this by making "HibernateDelaySeconds=30" in `/etc/systemd/sleep.conf`, rebooting my laptop, and then entering suspend-then-hibernate and waking it up immediately, then waking it up after a little over 30 seconds. I never had a resume issue after waking it up immediately, but I always did after waiting the 30 seconds. @axet, this could be what makes it appear random to you; repeated testing multiple times in row will work fine, but if you leave it long enough it will have problems resuming. 

If someone else could test this to make sure it's not some issue with my specific setup, that'd be really helpful.

**Comment by fkru** [comment] 2022-11-21 18:37
> After reading through the comments on [#25269](https://github.com/systemd/systemd/issues/25269) and seeing @yuwata say that HibernateDelaySeconds= is now hijacked as an interval for measuring discharge rate, I did a little testing. At least on my system, it seems that when going in to suspend-then-hibernate I don't have the resume issues until after that HibernateDelaySeconds= has passed.
> 
> I tested this by making "HibernateDelaySeconds=30" in `/etc/systemd/sleep.conf`, rebooting my laptop, and then entering suspend-then-hibernate and waking it up immediately, then waking it up after a little over 30 seconds. I never had a resume issue after waking it up immediately, but I always did after waiting the 30 seconds. @axet, this could be what makes it appear random to you; repeated testing multiple times in row will work fine, but if you leave it long enough it will have problems resuming.
> 
> If someone else could test this to make sure it's not some issue with my specific setup, that'd be really helpful.
> 
> Edit: It looks like @yuwata is already working on making some more clear, separate distinctions for HibernateDelaySeconds and the discharge rate measuring interval, so hopefully that will fix the issue, but I'm not sure.

Unfortunately, I cannot confirm your observation, as far as the original bug report is concerned.

**Comment by n-peugnet** [comment] 2022-11-21 21:12
@yuwata:
> Thank you for the reports. So, let's drop the regression tag.
> 
> @n-peugnet Could you also test with newer kernels?

So I tried with systemd `252.1-1`.

1. I did not yet reproduce the issue with `linux-image-6.0.0-4-amd64 (6.0.8-1)`.
2. I tried to test again with `linux-image-6.0.0-2-amd64 (6.0.5-1)` and figured out it happened only when my slock service was enabled.

Here is a setup that almost always triggers it:

```console
$ uname -a
Linux X260-NICOLAS 6.0.0-2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.5-1 (2022-10-28) x86_64 GNU/Linux
$ systemd --version
systemd 252 (252.1-1)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
$ systemctl cat slock@.service
# /etc/systemd/system/slock@.service
[Unit]
Description=Lock X session using slock for user %i
Before=sleep.target

[Service]
User=%i
Environment=DISPLAY=:0
ExecStartPre=/usr/bin/xset dpms force suspend
ExecStart=/usr/local/bin/slock

[Install]
WantedBy=sleep.target
$ cat /etc/systemd/sleep.conf.d/nicolas.conf
[Sleep]
HibernateDelaySec=10
$ systemctl suspend-then-hibernate
```

Then wait for 10+ seconds and power on the computer.

The behaviour varies a little between the different occurences.

Usualy I get a screen completely locked where I can only move the mouse and the keyboard does nothing. I can still change TTY using `ctrl`+`alt`+`f*` binbings.

One time slock was visible when loging back in and I can kind of unlock it by typing my password but then gnome-terminal is completely frozen. I can still launch st via dmenu (didn't find other apps working). in this case I can still run `systemctl status` but `systemctl --user status` waits forever. This time as I had only one session open I tried `loginctl terminate-session 22` to kill it. It allowed me to go back to lightdm login page but didn't correcly lauch my xsession on startup. I had to `loginctl terminate-session` once again.

The `slock@.service` came from [Arch wiki](https://wiki.archlinux.org/title/Slock#Lock_on_suspend) and never failed before.

```
[Sleep]
HibernateDelaySec=10
```

is not necessary but I found the issue to appear more consistently with a smaller value.

I will continue to use systemd `252.1-1` with `linux-image-6.0.0-4-amd64 (6.0.8-1)` and my slock service to see if it appears again.

As I said in https://github.com/systemd/systemd/issues/25269#issuecomment-1310536738 I suspect https://github.com/systemd/systemd/pull/24336 to be related to this issue (based on its name).

**Comment by renzhamin** [comment] 2022-11-28 07:57
> After reading through the comments on [#25269](https://github.com/systemd/systemd/issues/25269) and seeing @yuwata say that HibernateDelaySeconds= is now hijacked as an interval for measuring discharge rate, I did a little testing. At least on my system, it seems that when going in to suspend-then-hibernate I don't have the resume issues until after that HibernateDelaySeconds= has passed.
> 
> I tested this by making "HibernateDelaySeconds=30" in `/etc/systemd/sleep.conf`, rebooting my laptop, and then entering suspend-then-hibernate and waking it up immediately, then waking it up after a little over 30 seconds. I never had a resume issue after waking it up immediately, but I always did after waiting the 30 seconds. @axet, this could be what makes it appear random to you; repeated testing multiple times in row will work fine, but if you leave it long enough it will have problems resuming.
> 
> If someone else could test this to make sure it's not some issue with my specific setup, that'd be really helpful.
> 
> Edit: It looks like @yuwata is already working on making some more clear, separate distinctions for HibernateDelaySeconds and the discharge rate measuring interval, so hopefully that will fix the issue, but I'm not sure.

I have the same problem, resuming before HibernateDelaySec causes no problem but resuming after HibernateDelaySec causes the session to freeze, and I have to kill the session from another tty then log in again or log in with another user
Last tested with kernel 6.0.10

**Comment by renzhamin** [comment] 2022-11-28 07:59
> After reading through the comments on [#25269](https://github.com/systemd/systemd/issues/25269) and seeing @yuwata say that HibernateDelaySeconds= is now hijacked as an interval for measuring discharge rate, I did a little testing. At least on my system, it seems that when going in to suspend-then-hibernate I don't have the resume issues until after that HibernateDelaySeconds= has passed.
> 
> I tested this by making "HibernateDelaySeconds=30" in `/etc/systemd/sleep.conf`, rebooting my laptop, and then entering suspend-then-hibernate and waking it up immediately, then waking it up after a little over 30 seconds. I never had a resume issue after waking it up immediately, but I always did after waiting the 30 seconds. @axet, this could be what makes it appear random to you; repeated testing multiple times in row will work fine, but if you leave it long enough it will have problems resuming.
> 
> If someone else could test this to make sure it's not some issue with my specific setup, that'd be really helpful.
> 
> Edit: It looks like @yuwata is already working on making some more clear, separate distinctions for HibernateDelaySeconds and the discharge rate measuring interval, so hopefully that will fix the issue, but I'm not sure.

I have the same problem, resuming before HibernateDelaySec causes no problem but resuming after HibernateDelaySec causes the session to freeze, and I have to kill the session from another tty then log in again or log in with another user
Last tested with kernel,  linux 6.0.10.arch2-1 and linux-zen 6.0.10.zen2-1

**Comment by jarulsamy** [comment] 2022-12-02 21:33
> I seem to have the same or a similar issue
> 
> if using suspend-then-hibernate, when trying to wake up from suspend, the diplay backlight turns on, but the system remains otherwise frozen/broken. No screen content is shown, caps lock is not flashing, system cannot turn off. I have to hold down power button to force hard shutdown, resulting in loss of all data.
> 
> suspend works fine hibernate on itself also works fine
> 
> systemd 252 (252.2+suse.29.ge7e931b07e) opensuse tumbleweed Linux 6.0.10-1-default
> 
> it was working fine in an older version of systemd

I am having pretty much identical issues. I am running the LTS kernel, so this seems to be specifically a regression in systemd 252. Reverting to v251.7 is a temporary fix.

### System specifications

Distribution: Arch

Version: systemd 252 (252.2-2-arch)

Kernel: Linux 5.15.80-1-lts

---

**Comment by kolayne** [comment] 2022-12-03 09:22
I seem to be having issues similar to what is described above. I have additionally tested suspending/hibernating from tty and got quite surprising results.

<details>
<summary>My setup</summary>

```
nikolay@KoLin:~$ uname -a
Linux KoLin 6.0.10-arch2-1 #1 SMP PREEMPT_DYNAMIC Sat, 26 Nov 2022 16:51:18 +0000 x86_64 GNU/Linux
nikolay@KoLin:~$ systemctl --version
systemd 252 (252.2-2-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
nikolay@KoLin:~$
```

</details>

When doing either `systemctl suspend` or `systemctl hibernate` from either tty or my terminal emulator in X, I have no issues at all. In the graphical environment, when I do either `systemctl hybrid-sleep` or `systemctl suspend-then-hibernate` (no matter if I wake up before or after `HibernateDelaySec` elapse), my graphical environment freezes, not responding to mouse or keyboard, and I cannot switch to a tty. However, when I `systemctl suspend-then-hibernate` from tty and wake up _before_ `HibernateDelaySec` pass, this has no side effects at all, I get back to a functioning tty, but if I wake up _after_ `HibernateDelaySec` passed, the current tty gets completely frozen. This time, I can switch to another tty, though.

Most surprisingly, if I do `systemctl hybrid-sleep` from a tty and then wake up, the current tty works fine, but if I do `systemctl start lightdm.service` after that, which successfully launches lightdm and brings me to a login screen, after I type my password, my window manager (`i3 version 4.21.1 (2022-10-24)`) won't be started (and I didn't find anything useful in the lightdm logs, it seems like it doesn't even attempt to launch it).

**Comment by jojoob** [comment] 2022-12-05 07:37
Under Arch I experience a black screen after resume from suspend-then-hibernate (from suspend state/before HibernateDelaySec). Screen remains black even when trying to switch TTY. Only way out is to power cycling. I did not test just suspend yet. Resume from hibernate works fine. **For me this issue started with systemd 252.2-1.** Downgrade to 252.1-2 solved it for now.

**Comment by fkru** [comment] 2022-12-06 22:05
> > Was it a cold boot after downgrading?
> 
> Yes. I downgraded, restarted and then tested. When I upgrade again no restart is needed to brake resume again. sweat_smile

Let me ask again: When you upgrade to 252.2, then shutdown and boot, does the issue still occur? Thx.

**Comment by jojoob** [comment] 2022-12-07 05:24
Yes, it does.

**Comment by msizanoen1** [comment] 2022-12-07 12:55
Can you check if applying #25662 fixes the problem? (You can find out how to do so by consulting your distribution's packaging documentation)

**Comment by msizanoen1** [comment] 2022-12-07 14:10
Can you execute the following command from SSH when the keys are frozen?
```sh
find /sys/fs/cgroup -name cgroup.freeze -print0 | xargs -0 grep 1
```

**Comment by msizanoen1** [comment] 2022-12-07 14:40
@axet It turns out one of the patches broke cgroup thawing altogether. I just uploaded the fixed patch. Can you retry applying and testing that PR?

**Comment by axet** [comment] 2022-12-07 15:43
It worked. But wait. It happened before. Lets wait for a week and see if it is stable during the night. BTW on my system HibernateDelaySec=16h. Never hits the delay.

**Comment by msizanoen1** [comment] 2022-12-08 04:27
@axet
> It worked. But wait. It happened before. Lets wait for a week and see if it is stable during the night. BTW on my system HibernateDelaySec=16h. Never hits the delay.

If you run any QEMU/KVM processes in the user context please re-patch your packages from the latest commits and reboot - there were some changes made specifically for it.

**Comment by axet** [comment] 2022-12-08 06:43
It looks fine. Stand a night. Few additional suspend / resume. Looks like a fix! Thanks! Congratulations! Tricky one.

**Comment by n-peugnet** [comment] 2022-12-08 08:04
@msizanoen1:
> Can you check if applying #25662 fixes the problem? (You can find out how to do so by consulting your distribution's packaging documentation)

Just built it on Debian bookworm. From the resulted packages I installed `systemd_252.2-1_amd64.deb`, `libsystemd0_252.2-1_amd64.deb` and `libsystemd-shared_252.2-1_amd64.deb` then rebooted. I hope it's enough.

For now the issue didn't show up. I will keep you updated.

I also tested `252.2-1` from Debian's repos just before and I had the issue with the first `suspend-then-hibernate`.

**Closed as completed** 2022-12-08 16:24 UTC
Labels: bug 🐛, login, regression ⚠️, sleep

**Comment by n-peugnet** [comment] 2022-12-09 12:21
Still no sign of the issue, seems like it fixed it for me too.

**Comment by IamNaN** [comment] 2023-07-03 04:25
Sorry to zombie this issue. My AMD Ryzen 7 7700X based motherboard won't resume from suspend. I've been using bookworm, fresh install, not an upgrade, since January. This issue just cropped up since the last update.

Additional note, suspend triggers the AMD RX 7900 XT GPU fans to jump to 100%. This is like the boot phase just before POST.

The situation occurs when timed out or manually suspended.

**Comment by msizanoen1** [comment] 2023-07-03 04:31
> Sorry to zombie this issue. My AMD Ryzen 7 7700X based motherboard won't resume from suspend. I've been using bookworm, fresh install, not an upgrade, since January. This issue just cropped up since the last update.
> 
> Additional note, suspend triggers the AMD RX 7900 XT GPU fans to jump to 100%. This is like the boot phase just before POST.
> 
> The situation occurs when timed out or manually suspended.

@IamNaN Can you run `systemctl log-level debug` prior to invoking `systemctl suspend-then-hibernate`, and then use `journalctl -b > log.txt` to generate a log file and upload it here?

**Comment by IamNaN** [comment] 2023-07-06 00:19
> @IamNaN Can you run `systemctl log-level debug` prior to invoking `systemctl suspend-then-hibernate`, and then use `journalctl -b > log.txt` to generate a log file and upload it here?

Thanks for looking. Sure thing. And another data point for you: this is a dual boot system. I have another drive I select from BIOS (no shared partitions or drives) with Windows 11, and that does recover from suspend. I don't think it's a hardware issue.

[log.txt](https://github.com/systemd/systemd/files/11962931/log.txt)

**Comment by msizanoen1** [comment] 2023-07-06 02:43
@IamNaN The log file doesn't contain the necessary information for troubleshooting. Please provide details on whether you're using `suspend-then-hibernate` or just normal `suspend`, and follow the following steps:

 - Run `sudo systemctl log-level debug`.
 - Run `sudo systemctl suspend-then-hibernate`.
 - If the system fails to resume properly, hard reset the system then create a log file of the previous boot with `sudo journalctl -b -1 > log1.txt`.
