### ISSUE TITLE
autopkgtest failure: boot-and-services: test_gdm3 (__main__.ServicesTest)

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#13272] opened 2019-08-06 09:00 UTC
Testing the v243-rc1 snapshot, I reliably get the following autopkgtest failure for the boot-and-services test:
```
test_gdm3 (__main__.ServicesTest) ... 292 /usr/sbin/gdm3
311 gdm-session-worker [pam/gdm-launch-environment]
328 /usr/lib/gdm3/gdm-wayland-session gnome-session --autostart /usr/share/gdm/greeter/autostart
ERROR
test_logind (__main__.ServicesTest) ... ok
test_network_manager (__main__.ServicesTest) ... ok
test_no_failed (__main__.ServicesTest)
No failed units ... ok
test_rsyslog (__main__.ServicesTest) ... ok
test_tmp_cleanup (__main__.ServicesTest) ... ok
test_tmp_mount (__main__.ServicesTest) ... ok
test_udev (__main__.ServicesTest) ... ok

======================================================================
ERROR: test_gdm3 (__main__.ServicesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest.fsAeDK/build.xZq/src/debian/tests/boot-and-services", line 72, in test_gdm3
    self.active_unit('gdm')
  File "/tmp/autopkgtest.fsAeDK/build.xZq/src/debian/tests/boot-and-services", line 178, in active_unit
    out = subprocess.check_output(['systemctl', 'status', unit])
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['systemctl', 'status', 'gdm']' returned non-zero exit status 3.

----------------------------------------------------------------------
Ran 23 tests in 10.371s

FAILED (errors=1, skipped=2)
autopkgtest [10:49:26]: test boot-and-services: -----------------------]
autopkgtest [10:49:27]: test boot-and-services:  - - - - - - - - - - results - - - - - - - - - -
boot-and-services    FAIL non-zero exit status 1
autopkgtest [10:49:28]: @@@@@@@@@@@@@@@@@@@@ summary
boot-and-services    FAIL non-zero exit status 1
```
The test itself can be found here
https://salsa.debian.org/systemd-team/systemd/blob/master/debian/tests/boot-and-services#L32

git bisect finds the following commit as the first faulty one:
commit e8630e695232bdfcd16b55f3faafb4329c961104
Author: Zbigniew Jędrzejewski-Szmek <zbyszek@in.waw.pl>
Date:   Thu Jul 18 13:11:28 2019 +0200

    pid1: use a cache for all unit aliases

**Comment by mbiebl** [comment] 2019-08-06 20:31
@rbalint mentioned in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=934067 that this issue is possibly triggered because gdm3.service is a symlink to gdm.service (in Debian)

**Comment by rbalint** [comment] 2019-08-07 12:25
Also gdm3.service is not marked as an Alias of the gdm.service.

**Comment by mbiebl** [comment] 2019-08-07 13:12
Curious why  this issue not triggered in the upstream (Ubuntu) CI

**Comment by iainlane** [comment] 2019-08-13 13:53
symlinks are supposed to work, aren't they? I thought `Alias` was just a convenience thing for `systemctl enable` to use to create them for you, so if we don't have one in GDM's Debian packaging that wouldn't be a bug per se.

@xnox Does the CI run this GDM test? IIRC some tests are disabled there.

**Comment by rbalint** [comment] 2019-08-13 14:17
@iainlane I'd like to cahnge my position and I don't believe that this is a GDM bug.

**Comment by rbalint** [comment] 2019-08-13 14:18
@iainlane I also reverted the breaking commit in systemd in eoan and experimental.

**Comment by iainlane** [comment] 2019-08-13 14:29
@rbalint OK then, thanks for following up on this.

**Comment by mbiebl** [comment] 2019-08-19 12:30
@keszybz for historical reasons, Debian ships a gdm3.service symlink (the SysV init script was/is named /etc/init.d/gdm3):
```
/lib/systemd/system/gdm3.service -> gdm.service
```
gdm.service contains:
```
BusName=org.gnome.DisplayManager
```

With your changes in e8630e695232bdfcd16b55f3faafb4329c961104 this now triggers the following failure when trying to start gdm.service:
```
● gdm.service - GNOME Display Manager
   Loaded: error (Reason: Unit gdm.service failed to load properly: File exists.)
   Active: inactive (dead)

Aug 19 12:25:50 autopkgtest-sid systemd[1]: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager, refusing operation.
Aug 19 12:29:32 autopkgtest-sid systemd[1]: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager, refusing operation.
```

Since the "two services" are aliases, systemd should not refuse to start gdm.service.

**Comment by keszybz** [comment] 2019-08-20 22:06
Please check with b208cbe5.

**Comment by mbiebl** [comment] 2019-08-21 07:29
hi @keszybz , I tried with latest master (ba903882212829d32e2c9458633c4427297c8407), but the failure remains:
```
root@autopkgtest-lxc-vbrbhg:/tmp/autopkgtest-lxc.ypvpg8_f/downtmp/build.6KA/src# systemctl status gdm
● gdm.service - GNOME Display Manager
   Loaded: error (Reason: Unit gdm.service failed to load properly: File exists.)
   Active: inactive (dead)

Aug 21 07:23:48 autopkgtest-lxc-vbrbhg systemd[1]: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager, refus
ing operation.
Aug 21 07:26:25 autopkgtest-lxc-vbrbhg systemd[1]: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager, refus
ing operation.
Aug 21 07:27:58 autopkgtest-lxc-vbrbhg systemd[1]: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager, refus
ing operation.
Aug 21 07:27:58 autopkgtest-lxc-vbrbhg systemd[1]: gdm.service: Failed to load configuration: File exists
Aug 21 07:27:58 autopkgtest-lxc-vbrbhg systemd[1]: gdm.service: Trying to enqueue job gdm.service/restart/replace
Aug 21 07:27:58 autopkgtest-lxc-vbrbhg systemd[1]: gdm.service: Collecting.
Aug 21 07:27:58 autopkgtest-lxc-vbrbhg systemd[1]: gdm.service: Failed to send unit remove signal for gdm.service: Connection reset 
by peer
Aug 21 07:28:04 autopkgtest-lxc-vbrbhg systemd[1]: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager, refus
ing operation.
```

**Comment by keszybz** [comment] 2019-08-21 07:49
How can I recreate this locally? I tried various combinations of symlinks, and there is no issue.
```console
$ systemctl show -p Names gdm
Names=gdm3.service gdm.service display-manager.service
$ systemctl show -p BusName gdm
BusName=org.gnome.DisplayManager
```

**Comment by keszybz** [comment] 2019-08-21 09:06
I installed gdm in a debian/unstable container, and I get the same result:
```console
$ systemctl status gdm3
● gdm.service - GNOME Display Manager
   Loaded: loaded (/lib/systemd/system/gdm.service; static; vendor preset: enabled)
   Active: inactive (dead)
$ systemctl show -p Names gdm3
Names=gdm.service display-manager.service gdm3.service
$ systemctl --version
systemd 243 (243-rc1-139-g1a547b5)
```
It would be interesting to see `systemctl dump` output when the problem occurs.

**Comment by mbiebl** [comment] 2019-08-21 11:17
[dump.txt](https://github.com/systemd/systemd/files/3525038/dump.txt)
```
root@autopkgtest-lxc-zmorxn:/tmp/autopkgtest-lxc.vjd49lcx/downtmp/build.bf2/src# systemctl status gdm gdm3 display-manager
● gdm.service - GNOME Display Manager
   Loaded: error (Reason: Unit gdm.service failed to load properly: File exists.)
   Active: inactive (dead)

Aug 21 11:12:34 autopkgtest-lxc-zmorxn systemd[1]: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager, refus
ing operation.
Aug 21 11:14:45 autopkgtest-lxc-zmorxn systemd[1]: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager, refus
ing operation.
Aug 21 11:16:54 autopkgtest-lxc-zmorxn systemd[1]: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager, refus
ing operation.

● gdm.service - GNOME Display Manager
   Loaded: error (Reason: Unit gdm.service failed to load properly: File exists.)
   Active: inactive (dead)

Aug 21 11:12:34 autopkgtest-lxc-zmorxn systemd[1]: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager, refus
ing operation.
Aug 21 11:14:45 autopkgtest-lxc-zmorxn systemd[1]: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager, refus
ing operation.
Aug 21 11:16:54 autopkgtest-lxc-zmorxn systemd[1]: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager, refus
ing operation.
Aug 21 11:16:54 autopkgtest-lxc-zmorxn systemd[1]: gdm.service: Two services allocated for the same bus name org.gnome.DisplayManager, refus
ing operation.

● display-manager.service - GNOME Display Manager
   Loaded: loaded (/usr/lib/systemd/system/gdm3.service; static; vendor preset: enabled)
   Active: active (running) since Wed 2019-08-21 11:12:32 UTC; 4min 21s ago
 Main PID: 120 (gdm3)
      CPU: 47ms
   CGroup: /system.slice/display-manager.service
           └─120 /usr/sbin/gdm3

Aug 21 11:12:32 autopkgtest-lxc-zmorxn systemd[1]: Starting GNOME Display Manager...
Aug 21 11:12:32 autopkgtest-lxc-zmorxn systemd[1]: Started GNOME Display Manager.
```
```
root@autopkgtest-lxc-zmorxn:/tmp/autopkgtest-lxc.vjd49lcx/downtmp/build.bf2/src# ls -al /etc/systemd/system/display-manager.service 
lrwxrwxrwx 1 root root 32 Aug 21 11:12 /etc/systemd/system/display-manager.service -> /lib/systemd/system/gdm3.service
root@autopkgtest-lxc-zmorxn:/tmp/autopkgtest-lxc.vjd49lcx/downtmp/build.bf2/src# ls -al /lib/systemd/system/gdm3.service
lrwxrwxrwx 1 root root 11 Feb  9  2019 /lib/systemd/system/gdm3.service -> gdm.service
```

**Comment by keszybz** [comment] 2019-08-21 11:50
I have the same link setup, but the issue does not occur.
`systemd-analyze unit-files '*gdm*'` please.

**Comment by mbiebl** [comment] 2019-08-21 13:15
```
root@autopkgtest-lxc-mdlelq:/tmp/autopkgtest-lxc.ixkpiiga/downtmp/build.EkC/src# systemd-analyze unit-files '*gdm*'
ids: gdm3.service → gdm.service
ids: gdm.service → /lib/systemd/system/gdm.service
ids: display-manager.service → gdm3.service
aliases: gdm.service ← gdm3.service, gdm.service, display-manager.service
```

**Comment by keszybz** [comment] 2019-08-21 13:25
Hmm. How is the image set up? Is there a daemon-reload from an older systemd version to a newer one?

(How can I recreate this setup locally? Maybe it'd be easier to debug this way.)

**Comment by mbiebl** [comment] 2019-08-21 17:15
I use  `make-dsc` from https://salsa.debian.org/systemd-team/trunk-ci to create a source package which you then can build using your favorite tool (pbuilder, sbuild, etc)

The test environment is create via `autopkgtest-build-lxc debian sid` and the test can the be run via
`autopkgtest -s systemd_*amd64.changes -- lxc -s autopkgtest-sid`

**Comment by mbiebl** [comment] 2019-08-21 18:46
@keszybz this happens on a clean boot with systemd master

**Comment by mbiebl** [comment] 2019-08-21 18:46
i.e. no upgrade / daemon-reload from an older version involved

**Comment by keszybz** [comment] 2019-08-21 20:32
So... I don't have the debian-specific build tools, so I'm not going to rebuild the package.
Dunno, I don't thnk I'm going to solve this. I think you'll need to debug this yourself.
Maybe this is somehow releated to the sysv-compat mode? In my debian/unstable
container, systemd-sysv-generator skips /etc/init.d/gdm3 because the it sees the native unit,
but maybe it can get confused?

**Comment by mbiebl** [comment] 2019-08-21 20:44
Just in case you missed it, the first buggy commit is e8630e6

I don't think it has anything to do with sysv compat mode but rather systemd getting confused when symlinks are involved

**Comment by mbiebl** [comment] 2019-08-21 20:45
I propose reverting e8630e6 until this is fixed

**Comment by mbiebl** [comment] 2019-08-21 20:52
have you tried creating a gdm3.service symlink (pointing at gdm.service) and letting display-manager.service point at gdm3.service?

**Comment by keszybz** [comment] 2019-08-21 21:05
So... in the dump you posted, display-manager.service has FragmentPath=/usr/lib/systemd/system/gdm3.service. But display-manager.service should not be shown at all, because it is an alias from gdm.service. The error seems to be that display-manager.service is treated as a separate unit.

Can you provide the output from something like
```sh
udo find / \( -name display-manager.service -o -name gdm3.service -o -name gdm.service \) -exec ls -ld {} \;
```
?

**Comment by keszybz** [comment] 2019-08-21 21:20
> have you tried creating a gdm3.service symlink (pointing at gdm.service) and letting display-manager.service point at gdm3.service?

Yes, I have the exact same links as you:
```
lrwxrwxrwx. 1 root root   32 Aug 21 11:02 /etc/systemd/system/display-manager.service -> /lib/systemd/system/gdm3.service
-rw-r--r--. 1 root root 1026 Feb  9  2019 /lib/systemd/system/gdm.service
lrwxrwxrwx. 1 root root   11 Feb  9  2019 /lib/systemd/system/gdm3.service -> gdm.service
```

Also, what does `systemd-analyze unit-paths` say?

The problem is somewhat clear at this point: display-manager.service is considered to be unit linked (in the systemctl link sense) to /usr/lib/systemd/system/gdm3.service, instead of an alias from gdm.service. The question is why.

**Comment by mbiebl** [comment] 2019-08-21 21:48
```
root@autopkgtest-sid:/# find / \( -name display-manager.service -o -name gdm3.service -o -name gdm.service \) -exec ls -ld {} \;
find: '/dev/.lxc/sys/kernel': Permission denied
find: '/dev/.lxc/sys/power': Permission denied
find: '/dev/.lxc/sys/class': Permission denied
find: '/dev/.lxc/sys/devices': Permission denied
find: '/dev/.lxc/sys/dev': Permission denied
find: '/dev/.lxc/sys/hypervisor': Permission denied
find: '/dev/.lxc/sys/fs': Permission denied
find: '/dev/.lxc/sys/bus': Permission denied
find: '/dev/.lxc/sys/firmware': Permission denied
find: '/dev/.lxc/sys/block': Permission denied
find: '/dev/.lxc/sys/module': Permission denied
find: '/dev/.lxc/proc/fs': Permission denied
find: '/dev/.lxc/proc/bus': Permission denied
find: '/dev/.lxc/proc/irq': Permission denied
find: '/dev/.lxc/proc/sys': Permission denied
find: '/dev/.lxc/proc/tty': Permission denied
find: '/dev/.lxc/proc/acpi': Permission denied
find: '/dev/.lxc/proc/asound': Permission denied
find: '/dev/.lxc/proc/driver': Permission denied
find: '/dev/.lxc/proc/sysvipc': Permission denied
find: '/dev/.lxc/proc/pressure': Permission denied
find: '/dev/.lxc/proc/1': Permission denied
find: '/dev/.lxc/proc/19': Permission denied
find: '/dev/.lxc/proc/43': Permission denied
find: '/dev/.lxc/proc/51': Permission denied
find: '/dev/.lxc/proc/53': Permission denied
find: '/dev/.lxc/proc/72': Permission denied
find: '/dev/.lxc/proc/73': Permission denied
find: '/dev/.lxc/proc/75': Permission denied
find: '/dev/.lxc/proc/82': Permission denied
lrwxrwxrwx 1 root root 32 Aug 21 21:44 /etc/systemd/system/display-manager.service -> /lib/systemd/system/gdm3.service
find: '/sys/kernel/debug': Permission denied
-rw-r--r-- 1 root root 1026 Feb  9  2019 /usr/lib/systemd/system/gdm.service
lrwxrwxrwx 1 root root 11 Feb  9  2019 /usr/lib/systemd/system/gdm3.service -> gdm.service
```

Removing `/etc/init.d/gdm3` and rebooting doesn't make a difference.

```
root@autopkgtest-sid:/# systemd-analyze unit-paths
/etc/systemd/system.control
/run/systemd/system.control
/run/systemd/transient
/run/systemd/generator.early
/etc/systemd/system
/etc/systemd/system.attached
/run/systemd/system
/run/systemd/system.attached
/run/systemd/generator
/usr/local/lib/systemd/system
/lib/systemd/system
/usr/lib/systemd/system
/run/systemd/generator.late
```

**Comment by mbiebl** [comment] 2019-08-21 21:51
If access to a VM helps, I guess I can set that up.

**Comment by keszybz** [comment] 2019-08-22 07:01
> If access to a VM helps, I guess I can set that up.

That'd be great.

**Comment by mbiebl** [comment] 2019-08-23 11:00
Ok, I guess I can explain why you can't reproduce the problem on fedora:
This only seems to happen, if you run systemd on a usr-merged system, but systemd is compiled with `-Dsplit-usr=true`, which the Debian package is, as `merged-usr` is not mandatory (unfortunately).

**Comment by mbiebl** [comment] 2019-08-23 11:04
Maybe systemd get's confused as gdm.service exists both in /lib/systemd and /usr/lib/systemd and both directories are in the unit-path?

**Comment by mbiebl** [comment] 2019-08-23 11:09
I rebuilt the chroot with `debootstrap --no-merged-usr` and the problem is not triggered.

**Comment by mbiebl** [comment] 2019-08-24 23:10
@keszybz In case you want to reproduce the problem on fedora, you can try the following:
```
# mkdir /usr/local/lib/systemd
# ln -s /usr/lib/systemd/system /usr/local/lib/systemd/system
# cd /usr/lib/systemd/system
# ln -s gdm.service gdm3.service
# ln -sf /usr/lib/systemd/system/gdm3.service /etc/systemd/system/display-manager.service
```

**Comment by keszybz** [comment] 2019-08-26 07:15
@mbiebl thanks! (I won't be needing the VM you made available too.)
Please check if this works for you.

**Comment by mbiebl** [comment] 2019-08-27 10:24
I tested 4573ebb both with a merged and unmerged system (and systemd built with `-Dsplit-usr=true`.
It passed both configurations. So, looks good from my POV.

Thanks a lot @keszybz

**Closed as completed** 2019-08-27 16:12 UTC
Labels: tests, regression ⚠️
