### ISSUE TITLE
systemd restarts services during SysRq's "TERM KILL sync remount"

### ISSUE THREAD

**Issue by RalphCorderoy** [systemd/systemd#3269] opened 2016-05-16 10:49 UTC
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229
### Used distribution

> Arch Linux
### Details

I've an Arch Linux/systemd machine suffering problems.  Magic SysRq is enabled and the only way to recover at these times.  systemd is still working sufficiently to log messages;  I can see them on reboot.  If, after poking around with SysRq, I want to get a smooth reboot then the standard REISUB comes into play.  E sends SIGTERM to all but PID 1, and I sends KILL ditto.  A bit of time is left between each key press because the machine's state makes it slow for processes to quit nicely on the TERM.

Problem is, systemd restarts the processes and they're busy starting up when I remount read-only with U after the sync with S.  systemd has no way of knowing I've asked the kernel to kill everything.

A suggestion is for PID 1 to start a canary process and if it is TERM'd then to take it as a sign that restarts shouldn't occur.

**Comment by grawity** [comment] 2016-05-16 13:11
I'd say this is working as intended (just like with any other init system that supports monitoring – even SysVinit will restart agetty because inittab says so), and in practice often useful for investigating a broken system. I mean, I don't see any point in leaving a system with no userspace processes.

If your filesystems are already read-only, why not just reboot anyway?

If systemd is alive enough to restart services, it will react to Ctrl+Alt+Del as well (at least after a SysRq+R). Pressing that 7 times quickly will tell systemd to immediately jump to the "umount+reboot" part.

**Comment by RalphCorderoy** [comment] 2016-05-16 15:06
The problem is the filesystems become read-only during the start-up of all the services which kind of defeats the purpose of TERMing them all for a nice shutdown.

I see your point about a canary process being hit even though the user does want systemd to restart processes. How about if there was a new SysRq key that told just PID 1 it had been struck, e.g. with a signal, and that could then be configured to have systemd not restart everything?

**Comment by grawity** [comment] 2016-05-16 15:18
Just keep hammering Ctrl+Alt+Del until systemd enters the instant-reboot mode. I think that'll give you the desired result (everything SIGTERM'd & filesystems unmounted) without any SysRq.

Userspace cannot define new SysRq keys, but you could set up Alt+Up (the default Secure Attention Key shortcut, which also sends a signal and starts kbrequest.target in systemd) to do something useful.

**Comment by RalphCorderoy** [comment] 2016-05-16 15:33
These do not work, it needs SysRq so the kernel does the action.  I realise userspace doesn't define SysRq keys.  It would seem a signal-PID-1 key might be generally useful;  could systemd make use of it if it existed?

**Comment by poettering** [comment] 2016-05-17 08:44
Sorry, but I am really against such features of trying to "handle" alt-sysrq. Alt-SysRq is a debug option, and by trying to guess when debug options are used and changing behaviour then you kinda defeat the debug option.

I mean, you could read it the other way: systemd in this case really works as intended: it reacts to the children dying and restarts them, and maybe that's precisely what you wanted when you hit the sysrq key?

We do have the logic of doing a "fast" reboot if you hit ctrl-alt-del often enough. If that doesn#t work for you then ctl-alt-arrowup won't work either, since it uses the same kernel mechanism.

I think the best solution would be to add a new sysrq key that solves this in-kernel: kills all processes and mounts-read-only without giving userspace a way to interfere with that. By fixing this in-kernel everybody benefits, the solution works without breaking anybody else's mode of operation and is actually clean. Hence, please file a feature request against the kernel! 

I hope that makes sense! Closing this bug here.

**Closed as completed by poettering** 2016-05-17 08:44 UTC
Labels: not-our-bug
