### ISSUE TITLE
RFE: journalctl should have option to limit output to logs since last restart or reload

### ISSUE THREAD

**Issue by runejuhl** [systemd/systemd#8724] opened 2018-04-15 12:13 UTC
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 234

### Used distribution

> Debian/Ubuntu

### RFE

When debugging a service it would help to have an option to limit log output to the logs since last restart or reload of a unit. Especially for services with a large amount of logging it's easy to end looking at logs that for some reason no longer have any relevance.

While you could use the `--since` option to pass a timestamp, or the `--cursor` or `--after-cursor` options to give a cursor to journalctl, this still requires you to manually find a timestamp or a cursor ID. Having this as a built-in feature would make this kind of debugging more ergonomic.

**Comment by filbranden** [comment] 2018-04-16 02:27
Recent systemd also has invocation ID, so maybe it's the matter of taking -1, -2, etc. like the `-b` argument takes negative numbers for last boot, previous one, etc.

**Comment by poettering** [comment] 2018-04-17 18:17
Duplicate of #1942

**Closed as completed by poettering** 2018-04-17 18:17 UTC
Labels: RFE 🎁, journal, duplicate
