### ISSUE TITLE
(systemd)[3227624]: pam_systemd(systemd-user:session): Failed to create session: Invalid session class manager-early

### ISSUE THREAD

**Issue by daandemeyer** [systemd/systemd#34569] opened 2024-09-27 12:48 UTC
### systemd version the issue has been seen with

255-256

### Used distribution

CentOS Stream 9

### Linux kernel version used

6.9.0

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

I can upgrade/downgrade system between 255 and 256.

### Unexpected behaviour you saw

The below error happens when downgrading to systemd 255 from systemd 256

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
Sep 27 04:21:34 systemd[1]: Stopped user@0.service - User Manager for UID 0.
Sep 27 05:21:31 systemd[1]: Starting user@0.service - User Manager for UID 0...
Sep 27 05:21:31 (systemd)[3227624]: pam_unix(systemd-user:session): session opened for user root(uid=0) by root(uid=0)
Sep 27 05:21:31 (systemd)[3227624]: pam_systemd(systemd-user:session): Failed to create session: Invalid session class manager-early
Sep 27 05:21:31 systemd[3227624]: Trying to run as user instance, but $XDG_RUNTIME_DIR is not set.
Sep 27 05:21:31 systemd[1]: user@0.service: Main process exited, code=exited, status=1/FAILURE
Sep 27 05:21:31 systemd[1]: user@0.service: Failed with result 'exit-code'.
Sep 27 05:21:31 systemd[1]: Failed to start user@0.service - User Manager for UID 0.
```

**Comment by Hafpaf** [comment] 2024-10-11 07:53
> seems you didnt restart logind?

I had a similar issue and your suggestion solved it with `systemctl restart systemd-logind` 

Thanks!

**Comment by YHNdnzj** [comment] 2024-10-11 20:23
Let's close this one here, as it's also a duplicate of #33403. Safe restart of logind for desktop sessions is an unsorted problem, but would be resolved separately.

**Closed as completed by YHNdnzj** 2024-10-11 20:23 UTC
Labels: bug 🐛
