### ISSUE TITLE
refresh selinux label cache on daemon-reload

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#13363] opened 2019-08-20 07:35 UTC
**systemd version the issue has been seen with**
> ...any

**Used distribution**
 > …Fedora Rawhide

**Expected behaviour you didn't see**
 > …systemcctl daemon-reload does not cause systemd to refresh its label cache

**Unexpected behaviour you saw**
 > …i need to do systemctl daemon-reexec to force systemd to refresh its label cache

**Steps to reproduce the problem**
add a label at runtime that systemd needs to be aware of (for example a label used for RuntimeDirectory=)

**Comment by poettering** [comment] 2019-08-20 11:50
makes sense. But like with most selinux stuff we rely on submitted patches for this! Hence, if you want to see this fixed please submit a PR!

**Comment by doverride** [comment] 2019-08-20 13:17
I tried that before but I can't because your stuff does not compile on SELinux enforced systems. I submitted a PR to address that, and you refused it citing some flawed "standard"

Maybe someone else can pick this up

**Comment by poettering** [comment] 2019-08-20 13:40
> I tried that before but I can't because your stuff does not compile on SELinux enforced systems. I submitted a PR to address that, and you refused it citing some flawed "standard"

Huh? Which PR is that?

> Maybe someone else can pick this up

Noone will, if you close the issue though. I you want someone to look into this then better leave it open otherwise noone will ever see this.

**Comment by doverride** [comment] 2019-08-20 13:43
https://github.com/systemd/systemd/pull/12303

**Comment by doverride** [comment] 2019-08-20 15:08
Anyway I kind of, semi understand the issues and concerns raised in that PR, but:

It doesnt matter what processes in the container think, they are not and should not be allowed to do anything selinux regardless of what they think.

The spec does not work. Try running load_policy in a container that has selinuxfs mounted r/o, It does not care at all weither its ro or rw.

If you just not have selinuxfs in there and you block container access to anything selinux then atleast you can get systemd to build in there.

Regardless though the main issue is in the test that unmounts /sys because if it does that on a host with selinux enabled then its instant death. You can't just unmount selinuxfs.....

**Comment by poettering** [comment] 2019-08-20 16:21
> It doesnt matter what processes in the container think, they are not and should not be allowed to do anything selinux regardless of what they think.

Well, that's a great wish. But containers are not really security technology, in particular not when userns is used.

the r/o mounting of selinux fs is an indication libselinux checks for, it's not something that actually prohibits selinux operations or that one couldn't undo in the container. It's a mechanism we agreed on with the libselinux folks, that's all. Thus it needs a spec, because it's just a friendly agreement how to tell libselinux in the container that selinux exists and might be enabled but please not use that in the container.

**Comment by poettering** [comment] 2019-08-20 16:28
> If you just not have selinuxfs in there and you block container access to anything selinux then atleast you can get systemd to build in there. (is that not what nspawn was initially for?)
> 
> Regardless though the main issue is in the test that unmounts /sys because if it does that on a host with selinux enabled then its instant death. You can't just unmount selinuxfs.....

Not sure I udnerstand why the mere act of building systemd should be affected by selinuxfs being around or not, or being read-only... 

And if the container unmounts selinuxfs what does that matter? it won't be unmounted on the host, so what's the issue?

I totally don#t get the issue you ran into?

**Comment by doverride** [comment] 2019-08-20 18:16
I dont want to get into a debate about containers. But some things:

A "container" without some form of MAC is not a "container".
MAC is a security technology. It is what contains "containers". Aspects like namespaces/cgroups arent  security technologies, i agree.
If you have selinuxfs mounted in the container then that means you have selinux on the host and that then means that you can use selinux on the host to prevent container processes access to selinux. So it is not a "great wish": its reality.

That said, i just tried the whole thing out and seems the scenario might have changed since then. because the results arent the same as before:

1, i was unable to manually umount /sys/fs/selinux from within the container (so thats good)
2. the modprobe hack in systemd-nspawn@.service does not work for "loop" (it takes a second try to start the initial container)
3. systemctl edit systemd-nspawn@.service --full does not work
4. nspawn chowns /sys/fs/selinux (on host /sys/fs/selinux is no longer root.root when you start container) (bad)
5. was unable to build systemd in container (it crapped out somewhere in the tests phase)
6. the good news is that it didnt (try to) unmount selinuxfs in the container (maybe it crapped out before that stage) so i am unable to confirm that part ....

So i was unable to reproduce, but the end result was the same:
unable to successfully build systemd

Therefore. ignore all the noise. but still, i am not going to try and address this issue. Hopefully someone else will pick this up.

I recorded the whole session (mainly for my own reference) but anyone bored and interested can view it here: https://www.youtube.com/watch?v=GCsK0bfQ7Kg (warning: profanity inside)

**Closed as completed** 2019-12-04 09:29 UTC
Labels: RFE 🎁, pid1, selinux

**Comment by bigon** [comment] 2020-01-06 12:16
Hello,

Little remark regarding the patch.

This is probably only working for the PID1 component and not the others that are calling `mac_selinux_init()` (udev, logind,...)

I would personally drop the call to `mac_selinux_reload()` in the daemon-reload case and add a selinux callback (`SELINUX_CB_POLICYLOAD`)

**Comment by bigon** [comment] 2020-01-21 17:39
Shouldn't reopen this? I'm not 100% sure the patch is doing the correct thing

**Comment by poettering** [comment] 2020-01-21 17:43
hmm, how does SELINUX_CB_POLICYLOAD actually work? when is it invoked? in which calling context? docs are terrible for it.

Are oyu sure SELINUX_CB_POLICYLOAD makes reloading on daemon-reload unnecessay?

I mean, by all means prep a patch if it makes sense. (like for everything else selinux related, we need patches, otherwise we are not going to do much). Patches should be constructive though, i.e. replace something with something better, but not just revert stuff that already works OK.

**Comment by bigon** [comment] 2020-01-22 11:16
I ported dbus-daemon to the new API more than a year ago (https://gitlab.freedesktop.org/dbus/dbus/merge_requests/31). IIRC, dbus-daemon is opening the avc_netlink and add a watcher to it. When there is activity on the fd it calls `avc_netlink_check_nb()`

A permission check (`selinux_check_access()`) is also calling `avc_netlink_check_nb()` and then trigger the callback. But if there is no permission check, the callback will not be called. If we can get the callback called, I don't think we need to keep the explicit call to `mac_selinux_reload()` (and that will fix the problem for non PID1 case as well)

Really quickly looking at the code, I would merge the `access_init()` function in `mac_selinux_init()` (any reasons that has been split?) so all the callback are set at the same place. Add a the `SELINUX_CB_POLICYLOAD` callback and then add a way to listen to the avc netlink and call `avc_netlink_check_nb()` when there is activity on the fd (is there an easy way in systemd to do so? Some guidance would be appreciated)

**Comment by poettering** [comment] 2020-01-22 12:49
what I don't like about watching netlink like that is that it is asynchronous. hence when you reload policy and immediately execute some systemd operation it might or might not take the new policy into accoun, and we never know. It's an invitation for races. Same reason why we don't reload PID 1 config automatically via inotify triggers.

what might be acceptable if we check before each and every selinux operation if the policy changed, and then synchronously reload it right away, before executing the operation. That way you get the guarantee that when you reload and  then enqueue an operation it will definitely be done with the new policy.

not sure if there's an api for that that has sensible performance characteristics.

**Comment by bigon** [comment] 2020-01-22 13:38
I think that should work I guess (that's what `selinux_check_access()` is doing in [libselinux](https://github.com/SELinuxProject/selinux/blob/master/libselinux/src/checkAccess.c#L55))

https://github.com/SELinuxProject/selinux/blob/master/libselinux/src/avc_internal.c#L224
