### ISSUE TITLE
systemd-boot-system-token is failing with non-standard EFI partition setup

### ISSUE THREAD

**Issue by andrejpodzimek** [systemd/systemd#17530] opened 2020-11-06 04:46 UTC
**systemd version the issue has been seen with**
 > `246.6`

**Used distribution**
 > ArchLinux

**Linux kernel version used** (`uname -a`)
 > `5.9.6-arch1-1-zen2`

**CPU architecture issue was seen on**
 > Ryzen 3950X

**Expected behaviour you didn't see**
 > No failures.

**Unexpected behaviour you saw**
 > ```
 > Nov 06 05:35:36 aether systemd[1]: Starting Store a System Token in an EFI Variable...
 > Nov 06 05:35:39 aether bootctl[1316]: Failed to probe partition scheme of "/dev/block/9:127": Input/output error
 > Nov 06 05:35:39 aether systemd[1]: systemd-boot-system-token.service: Main process exited, code=exited, status=1/FAILURE
 > Nov 06 05:35:39 aether systemd[1]: systemd-boot-system-token.service: Failed with result 'exit-code'.
 > Nov 06 05:35:39 aether systemd[1]: Failed to start Store a System Token in an EFI Variable.
 > ```

**Steps to reproduce the problem**
 > * Use a replicated `/boot` EFI partition, as described in #17298.
 > * Update to the latest systemd.
 > * Bam. You get a long freeze during boot (1:30 of waiting) and then `degraded` mode all the time.

The bootloader works just fine. Why am I getting such weird errors? Disabling some of the stringent partition layout checks (as described in #17298 (plus also [here](https://github.com/systemd/systemd/issues/12468#issuecomment-698692508))) would help a lot.

**Comment by poettering** [comment] 2020-11-09 15:46
Hmm, it's probably good this fails. if this would work then in your raid setup you#d get a corrupted disk everytime, since the random see logic only is enabled if the system token stuff works, and it would mean sd-boot would write to disk on every boot.

So we probably should make this fail a bit less noisy, but this can never work. EFI in RAID is unuspportable.

**Comment by andrejpodzimek** [comment] 2020-11-12 21:34
The use of RAID is actually unimportant. It doesn't have to be (and can't be) a real atomic RAID with proper checksums (like e.g. Btrfs RAID1 would be), due to the not-so-great filesystem used by UEFI.

So just about _any_ type of replication would be a solution, such as `bootctl --esp-path /boot1 --esp-path /boot2 ...`. That could even keep doing all the stringent backing block device checks.

**Comment by poettering** [comment] 2022-09-02 14:41
Let's close this as duplicate of #3252

**Closed as completed by poettering** 2022-09-02 14:41 UTC
Labels: sd-boot/sd-stub/bootctl
