### ISSUE TITLE
bootctl: Block device node of composite fs partition is invalid

### ISSUE THREAD

**Issue by YorikSar** [systemd/systemd#24616] opened 2022-09-09 14:26 UTC
### systemd version the issue has been seen with

251.4

### Used distribution

NixOS unstable

### Linux kernel version used

5.15.64

### CPU architectures issue was seen on

x86_64

### Component

bootctl

### Expected behaviour you didn't see

`bootctl` should work with `--boot-path` pointing to a ZFS or btrfs partition

### Unexpected behaviour you saw

`bootctl` fails [this check](https://github.com/systemd/systemd-stable/blob/v251.4/src/shared/find-esp.c#L249-L252) and outputs:

```
Block device node of "/boot" is invalid.
```

It seems that this is because ZFS and btrfs filesystems don't reference block device, therefore its major number is 0 and minor refers to the FS in use.

### Steps to reproduce the problem

I'm trying to use recent addition of autoloading EFI drivers and [EfiFs](https://efi.akeo.ie) to load initrd and kernel from XBOOTLDR partition formatted with ZFS or btrfs. I got this error by:

* creating FAT partition and mounting it in `/efi`
* creating ZFS pool with `-o compatibility=grub2` or btrfs partition and mounting it to `/boot`
* running `bootctl --esp-path=/efi --boot-path=/boot install`

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
No filesystem is currently mounted on /sys/fs/cgroup.
Failed to detect cgroup namespace: No medium found
Found container virtualization none.
Using EFI System Partition at /efi.
Block device node of "/boot" is invalid.
```

**Comment by poettering** [comment] 2022-09-15 11:34
Ahumpf, zfs is not really a Linux file system, it's external code. I am not convinced we should add support for something like that that has apparently no avenue in even getting merged upstream.

I'd instead suggest the zfs implement the btrfs ioctls to return the components of a zfs fs? It should pretty much work then.

i.e. if you want compat, then implement the compat in zfs not in systemd.

We probably should add a way to override the checks here, but that's already tracked in #17298.

hence, let's close as duplicate of #17298

**Comment by YorikSar** [comment] 2022-09-15 11:56
@poettering Thanks for your reply. While ZFS is indeed not in mainline kernel, the same would apply to any other composite filesystem, for example, btrfs. It would also return major device number of 0 for `stat()` calls which would break assumptions in the XBOOTLDR partition check.

https://github.com/systemd/systemd/issues/17298 suggests to allow to bypass these checks entirely, but I would suggest adjusting them to not consider `0` as a wrong major device number, but rather attempting to find the actual underlying device and check if it is set up correctly.

I'll rename this issue to show that it's not just about ZFS.

**Comment by YorikSar** [comment] 2022-09-15 12:09
By the way, https://www.kernel.org/doc/Documentation/admin-guide/devices.txt suggests that we should treat major device numbers 144, 145 and 146 in the same way as 0 - they all describe some unnamed devices.

**Comment by poettering** [comment] 2022-09-16 09:55
> @poettering Thanks for your reply. While ZFS is indeed not in mainline kernel, the same would apply to any other composite filesystem, for example, btrfs. 

We support btrfs explicitly, by calling the right ioctls. That's why I was saying zfs should just reimplement the relevant ioctls, and things would mostly just work.

> It would also return major device number of 0 for `stat()` calls which would break assumptions in the XBOOTLDR partition check.

Yeah, we work on anything that returns valid major/minor or on things implementing the btrfs ioctl. (the latter being just btrfs)

> #17298 suggests to allow to bypass these checks entirely, but I would suggest adjusting them to not consider `0` as a wrong major device number, but rather attempting to find the actual underlying device and check if it is set up correctly.

It's not about right or wrong major/minor: we use the backing device major/minor to lookup the device metadata in udev to see if the gpt partition type is in order. If we can't determine the backing device then this check cannot be done.

> I'll rename this issue to show that it's not just about ZFS.

It is just about ZFS, because we support btrfs just fine, due to the explicit ioctl support

**Comment by YorikSar** [comment] 2022-09-16 10:05
I've checked it by replacing zfs pool creation and mount with relevant btrfs ones, and it failed in the same way. Is btrfs on XBOOTLDR supposed to be supported in v251? I don't see anything btrfs specific in `verify_fsroot_dir` function, it throws an error when it sees major device number of 0.

**Comment by YorikSar** [comment] 2022-09-16 10:13
I found btrfs specific ioctl used for some cgroup stuff here: https://github.com/systemd/systemd/blob/main/src/core/cgroup.c#L846-L852, but it's not used in `bootctl`.

**Comment by poettering** [comment] 2022-09-17 16:59
ah, indeed, we don't do in verify_fsroot_dir() what we do in get_block_device_fd()... We probably should. In fact verify_fsroot_dir() should probably just be a wrapper around that helper

**Comment by YorikSar** [comment] 2022-09-17 17:06
I think `verify_fsroot_dir` should do just that - verify that the dir is a root of a filesystem, and we should be able to disable all other checks (including check if major device number is 0) if a weird filesystem is used (like ZFS).

**Closed as completed** 2022-09-20 15:56 UTC
Labels: sd-boot/sd-stub/bootctl
