### ISSUE TITLE
udev severly broken in git master

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd#10864] opened 2018-11-21 02:30 UTC
Seems like udev in current git master is completely broken for me:
Some of the symptoms I noticed
1/ rfkill state is not restored, systemd-rfkill.service is never started
2/ wifi network interface is not renamed. NM for some reason lists the interface as unmanaged, so no network connection
3/ most importantly, as soon as gdm starts, the machine locks up. I can't move the mouse or type anything.
Since I have no network connection, getting SSH access is not possible.

**Comment by mbiebl** [comment] 2018-11-21 02:31
For testing purposed, I only downgraded udev back to v239 and kept the rest of systemd at git master, which gave me back a functioning system

**Comment by yuwata** [comment] 2018-11-21 02:46
Maybe a duplicate of #10754.
Could you try to boot with `udev.children_max=1`?

**Comment by mbiebl** [comment] 2018-11-21 02:59
```udev.children_max=1``` seems to help indeed. It feels like the system took a bit longer to boot and establishing the wifi connection also took a while, but no major failures when using that config option.

**Comment by yuwata** [comment] 2018-11-21 03:02
Thanks.

**Comment by yuwata** [comment] 2018-11-21 03:06
So, at least tentatively, let's close this.

**Closed as completed by yuwata** 2018-11-21 03:06 UTC
Labels: bug 🐛, udev, duplicate
