### ISSUE TITLE
Re-resolve wireguard peer hostname to IP-address

### ISSUE THREAD

**Issue by Tecol87** [systemd/systemd#29557] opened 2023-10-13 00:00 UTC
### Component

systemd-networkd

### Is your feature request related to a problem? Please describe

I have a wireguard peer which has a dynamic IP-address. So connecting to it works fine, but after a while, the connection goes down because his IP-address changes.

### Describe the solution you'd like

systemd-networkd should re-resolve the peer hostname. I see the following options:
- Add a config option to re-resolve it every X seconds regardless.
- Add a config option to re-resolve it, if the last handshake is more than Y handshake-periods behind or X seconds behind.

The first option has the advantage, that it would also work if the peer is kind-of load-balanced via DNS. So the connection will not be down for a small period. I don't know if this is really a use-case in the wild.

### Describe alternatives you've considered

Wireguard-tools has a tool to solve the job:
https://github.com/WireGuard/wireguard-tools/blob/master/contrib/reresolve-dns/reresolve-dns.sh
So creating an additional wireguard-config (which is not active) and adding a systemd-timer for the reresolve-dns script solves the job, but this implies to have duplicate configurations.

### The systemd version you checked that didn't have the feature you are asking for

254.5-1-arch

**Comment by poettering** [comment] 2023-10-13 09:20
Duplicate of #9911

**Closed as completed by poettering** 2023-10-13 09:20 UTC
Labels: RFE 🎁, network, duplicate
