### ISSUE TITLE
Stop job is running.

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#8919] opened 2018-05-07 14:26 UTC
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822996
This bug has been reported back in 2016.

Operating system - Debian 9.4

Shutting down lead to this message stop job is running and takes 1 minute  and 30 seconds to shutdown my system with a 20 GB of RAM and i7 processor. This might be fixed in future systemd release since debian uses a bit old software for stability please check this out.

**Comment by jatin-cbs** [comment] 2018-05-08 10:27
This bug is on most of the linux distros. In some operating systems this happens after x number of shut downs but mostly it do and on most of my system so its NOT a hardware specific problem.

**Comment by poettering** [comment] 2018-05-08 23:18
Which systemd version are you seeing this on? Which service are you seeing this with?

The message simply means that some service is taking very long to shut down. Do you have any indication that systemd is at fault here? Can you reproduce this issue?

**Comment by jatin-cbs** [comment] 2018-05-09 10:01
Yes systemd (232-25+deb9u2)  is the systemd version on debian 9.4 stable. On shut down it shows " A stop job is running for Avahi mDNS/DNS-SD Stack " and  " A stop job is running for gdm GNOME display Manager " and shows the time for example 0 min 40 sec/ 1 min 30 sec. And once it reaches 1 minute 30 seconds it then shut down. 

This bug is not in fedora 28 but its happening with debian and some debian based distros.

**Comment by keszybz** [comment] 2018-05-09 10:16
This message is just means that the stop job for some service is taking a long time to finish (probably it's hanging, and would never finish). The issue is in the service itself, or more likely, in the way that various services are connected together. For example, sometimes a similar issue occurs when a service that requires network to operate is not stopped *before* the service that provides the network, so it cannot shut down successfully. The fix for this is not in systemd itself, but in one or more units, i.e. not something that we have direct influence over. You have to take it up with your distro.

**Closed as completed by keszybz** 2018-05-09 10:16 UTC
Labels: not-our-bug, version-too-ancient
