### ISSUE TITLE
Unable to chown/chmod TemporaryFileSystem directory

### ISSUE THREAD

**Issue by dechamps** [systemd/systemd#19201] opened 2021-04-03 17:51 UTC
**systemd version the issue has been seen with**
247.3-3

**Used distribution**
Debian Unstable

**Linux kernel version used** (`uname -a`)
`5.10.0-4-amd64 #1 SMP Debian 5.10.19-1 (2021-03-02) x86_64 GNU/Linux`

**Steps to reproduce the problem**

```
[Service]
TemporaryFileSystem=/foo

ExecStartPre=/bin/chown nobody:nogroup /foo
ExecStart=/bin/ls -ld /foo
```

The `chown` command appears to run successfully but then the service outputs `root root` instead of the expected `nobody nogroup`. The same problem occurs if one attempts to change the mode using `chmod`.

It works if I mount a tmpfs manually:

```
# mkdir foo
# mount -t tmpfs none foo
# chown nobody:nogroup foo
# ls -ld foo
drwxrwxrwt 2 nobody nogroup 40 Apr  3 18:42 foo
```

Ultimately, all I want to do is change the owner of a `TemporaryFileSystem` directory. I don't want to use `TemporaryFileSystem=/foo:uid=65534` because that forces me to hardcode a UID instead of specifying a username.

**Comment by poettering** [comment] 2021-04-06 08:44
Duplicate of #8695

**Closed as completed by poettering** 2021-04-06 08:44 UTC
Labels: pid1, duplicate
