### ISSUE TITLE
Changing from DHCP to static address with systemd-networkd doesn't work until after reboot

### ISSUE THREAD

**Issue by bswartz** [systemd/systemd#11458] opened 2019-01-17 02:58 UTC
**systemd version the issue has been seen with**
> systemd-networkd 240

**Used distribution**
 > archlinux 2019.01.01

**Expected behaviour you didn't see**
 > Changing an interface from DHCP to static addressing doesn't make the address static until after a reboot.

**Unexpected behaviour you saw**
 > Interface lost address after the DHCP timeout, even after DHCP was disabled

Configure an interface to use DHCP using systemd-networkd. Then statically configure the interface to use that address, and restart systemd-networkd. After this observe that the valid_lft and preferred_lft of the address on the interface is finite, and once these lifetimes expire, the address is lost.

There are 2 workarounds I've found: either reboot the node, or manually set the valid_lft and preferred_lft to forever after bouncing systemd-networkd. IMO, systemd-networkd should be modifying the lifetimes itself.

**Comment by yuwata** [comment] 2019-01-17 03:17
> Configure an interface to use DHCP using systemd-networkd. Then statically configure the interface to use that address, and restart systemd-networkd.

Oh, it seems dangerous...

But, anyway, please provide debugging logs of networkd. Creating the following drop-in config is sufficient to generate that.
```
# /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

**Comment by yuwata** [comment] 2019-01-17 05:19
OK, I confirm that. Fix is waiting in #11460. If possible, please test the PR.

**Comment by ssahani** [comment] 2019-01-17 05:41
>Configure an interface to use DHCP using systemd-networkd. Then statically configure the interface to use that address, and restart systemd-networkd. 
This use case seems strange not invalid though but why would you do that ?

>After this observe that the valid_lft and preferred_lft of the address on the interface is finite, and once these lifetimes expire, the address is lost.

Is't it the right behaviour or I am missing something ?

**Comment by bswartz** [comment] 2019-01-17 14:57
@ssahani It's not the correct behavior for a static IP. Static IPs should have infinite lifetimes.

I agree the use case is not the most common one, so I will explain it. My use case is a cloud use case, where I have a base archlinux image that get cloned each time a new VM is created. Because all VMs start from the same image, it's not possible to statically configure IP addresses in the base image -- I have to use DHCP so each VM can get a different address to start with. However for my use case I reconfigure the VMs to have multiple IPv4 and IPv6 addresses after they boot up, because my application requires this. It's not practical to use DHCP to give multiple IPv4 and IPv6 address to a single host, so static configuration is what I do. This all works fine except that after I configure the addresses to be static, systemd-networkd stops sending DHCP requests and forgets to modify the lifetime of the original address on the interface, so after 1 hour (my DHCP lease time) the address drops off the interface and things start to break. Currently I have modified my automation to simply force the address lifetimes to infinite after modifying the systemd network configuration to be static. I think we can agree that this workaround should not be necessary however. Note that if I reboot or otherwise remove the address from the interface and bounce systemd, it does the right thing and adds the address with infinite lifetime, so the only problem is that it's not checking the lifetime when the address already exists on the interface.

**Comment by ssahani** [comment] 2019-01-17 16:38
>@ssahani It's not the correct behavior for a static IP. Static IPs should have infinite lifetimes.

Can you reproduce this  ? 

>I agree the use case is not the most common one, so I will explain it. My use case is a cloud use case, where I have a base archlinux image that get cloned each time a new VM is created. Because all VMs start from the same image, it's not possible to statically configure IP addresses in the base image -- I have to use DHCP so each VM can get a different address to start with. However for my use case I reconfigure the VMs to have multiple IPv4 and IPv6 addresses after they boot up, because my application requires this. It's not practical to use DHCP to give multiple IPv4 and IPv6 address to a single host, so static configuration is what I do. This all works fine except that after I configure the addresses to >be static, 

This is fundamentally wrong. Breaks the DHCP concept itself.  you trying to configure a DHCP IP which is you took for sometime. After expiration dhcp client should renew the address. You mean it does not renew ? Now you configured this as static, DHCP server can assign this IP to someone else since lease is expired. That will surely make a lot of noise in the network . You should not be adding any address statically from DHCP pool.

>systemd-networkd stops sending DHCP requests and forgets to modify the lifetime of the original address on the interface, so after 1 hour (my DHCP lease time) the address drops off the interface and things start to break.

Use ``` CriticalConnection= ``` . Again this is also a risk .

 >Currently I have modified my automation to simply force the address lifetimes to infinite after modifying the systemd network configuration to be static. I think we can agree that this workaround should not be necessary however. Note that if I reboot or otherwise remove the address from the interface and bounce systemd, it does the right thing and adds the address with infinite lifetime, so the only problem is that it's >not checking the lifetime when the address already exists on the interface.

You can add any other addresses which is but not from DHCP pool as static and do manual inventory and if that expires please file a bug. I am pretty sure this not the right thing to do and networkd should not come around on this.

**Closed as completed** 2019-01-26 14:41 UTC
Labels: bug 🐛, network

**Comment by ddstreet** [comment] 2019-09-30 17:13
@bswartz @yuwata I don't think this is actually fixed yet, is it?

If I start with this:

$ cat 10-eth0-dhcp.network 
[Match]
Name=eth0

[Network]
LinkLocalAddressing=ipv6
DHCP=ipv4

and restart networkd, i have as expected:

$ ip -4 a show eth0
51: eth0@if52: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000 link-netnsid 0
    inet 10.202.51.176/24 brd 10.202.51.255 scope global dynamic eth0
       valid_lft 3561sec preferred_lft 3561sec


but then if i remove that file and create:

$ cat 10-eth0-static.network 
[Match]
Name=eth0

[Network]
LinkLocalAddressing=ipv6
Gateway=10.202.51.1
DNS=8.8.8.8
DNS=8.8.4.4
Domains=test
Address=10.202.51.176/24
DHCP=no


and restart networkd, i get:

$ ip -4 a show eth0
51: eth0@if52: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000 link-netnsid 0
    inet 10.202.51.176/24 brd 10.202.51.255 scope global dynamic eth0
       valid_lft 3452sec preferred_lft 3452sec


it doesn't change the lifetime to forever...

**Comment by ddstreet** [comment] 2019-09-30 17:18
I think this is because when a new static address is setup, it gets its .cinfo.ifa_prefered and .cinfo.ifa_valid set to forever/infinity in address_new(); but when using an existing address, it never adjusts the current ifa_valid/ifa_prefered fields.

**Comment by yuwata** [comment] 2019-09-30 18:07
@ddstreet Could you please open as a new issue?

**Comment by ddstreet** [comment] 2019-10-02 07:13
> @ddstreet Could you please open as a new issue?

yep, I want to re-check my test again to make sure I didn't mess something up, and I'll open a new bug if it really has regressed.

**Comment by ddstreet** [comment] 2019-12-12 19:59
> yep, I want to re-check my test again to make sure I didn't mess something up, and I'll open a new bug if it really has regressed.

just to follow up - my test case was wrong and this bug has not regressed.  sorry for the noise.
