### ISSUE TITLE
cgroup v2 freezer breaks systemd's assumptions about cgroup.events

### ISSUE THREAD

**Issue by msekletar** [systemd/systemd#13620] opened 2019-09-22 12:58 UTC
Current cgroup v2 implementation of freezer breaks systemd assumption about the semantics of `cgroup.events` file. Previously, the contents of the file changed only when cgroup was running empty, and hence systemd received notification and interpreted them as unpopulated notification [1]. However, file now also contains an additional line which contains the status of the freezer cgroup subsystem, and as cgroup gets frozen the kernel generates notification on the file.

In PR #13512 I am trying to account for the new behavior, however, the problem is when we want to freeze the entire container (scope unit) running old systemd version inside of the container. Then systemd in the container will observe "frozen" notifications in its delegated cgroup subtree and will interpret them as "unpopulated" notifications. systemd will log about the fact, but it will recheck the state and it will figure out that service is indeed still alive, i.e. we get incorrect information logged in the journal but services are not stopped.

[1] https://www.kernel.org/doc/html/v5.3-rc8/admin-guide/cgroup-v2.html#un-populated-notification

**Comment by davide125** [comment] 2019-09-22 13:50
cc @rgushchin

**Comment by rgushchin** [comment] 2019-09-23 22:07
I don't think it's a kernel issue, if systemd doesn't check for "unpopulated" values and treats "frozen" notifications as "unpopulated". Also, it's too late to change the freezer interface, it has been merged already. So now there isn't much I can do on the kernel side.
Good news are that there is no regression unless the new freezer is used.

**Comment by msekletar** [comment] 2019-09-24 07:10
Yeah, the current state is probably not the end of the world. In case there isn't anything that can be done on kernel side then I think we should just fix this in systemd and move on.

**Comment by filbranden** [comment] 2019-09-27 17:49
Yeah reading through the snippet you mentioned ("un-populated notification"), it looks like systemd's assumption that notifications on `cgroup.events` would be triggered *only* when populated switched from 1 to 0 was a bit naive. A notification is an indication that the contents of the file should be checked again, we jumped the gun to assume we knew which modification happened (which, at the time, was the only possible one...)

@msekletar If your PR #13512 will have a fix for that assumption, please make sure it's in a separate commit. I'd be happy to later backport that to older versions in systemd-stable, that should help with distros that ship older versions of systemd that might be affected to include that commit, which hopefully means fewer people will end up seeing the "confusing" log message about thinking that the cgroup is empty whenever the systemd <v244 inside container gets freezed...

Cheers!
Filipe

**Comment by msekletar** [comment] 2019-09-29 11:32
@filbranden That is a very good point. I will split out that part to separate commit. Thanks!

**Comment by msekletar** [comment] 2019-09-30 11:36
@filbranden I've updated my freezer PR. PTAL.

**Comment by poettering** [comment] 2019-11-15 12:00
So, not sure I grok what the problem is supposed to be?

When systemd gets an cgroup.events inotify event the `on_cgroup_inotify_even()` handler gets run. if you look closely you'll see that it doesn't do anything particular interesting except calling add_to_cgroup_empty_queue() for the matching units... Now if you look at those functions you see that the first thing they do is check if the cgroup is actually empty, and only then actually adds actually it to the queue.  So, we there might be the chance we get multiple empty events dispatched in some cases when the cgroup is already empty, but that shouldn't matter much. We shouldn't get such events though when the cgroup isn't actually empty. Hence I think we are actually good here? (i mean, this whole stuff is async, but under the assumption that cgroups generally chage from populated to empty only once while we watch them we should be fine).

Or wht am I missing?

**Comment by msekletar** [comment] 2019-11-15 14:38
> We shouldn't get such events though when the cgroup isn't actually empty

However, we get such events even if cgroup isn't empty but it changed its freezer state (e.g. got frozen). We log (on debug level IIRC) that cgorup is empty but then we do look at the actual state and see processes in the cgroup hence we don't consider it empty at last.

**Comment by poettering** [comment] 2019-11-15 14:52
We log? which msg do you mean?

**Comment by poettering** [comment] 2020-01-21 11:25
So I think we can close this now? i.e. we don't actually assume that cgroup.events only wakes us up if the cgroup runs empty, we always check the condition again before acting on it. Thus we are fine being woken up too often, since we always check if anything really changed.

**Closed as completed by poettering** 2020-01-21 11:25 UTC
Labels: needs-discussion 🤔, not-our-bug
