### ISSUE TITLE
systemd 252 breaks i915 kernel parameters

### ISSUE THREAD

**Issue by brb-AT** [systemd/systemd#25539] opened 2022-11-26 14:48 UTC
### systemd version the issue has been seen with

252

### Used distribution

Arch Linux

### Linux kernel version used

6.0.9-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

systemd

### Expected behaviour you didn't see

I am using sbupdate and a unified kernel image with embedded initrd and cmdline. I added the following kernel parameters to the cmdline:
i915.enable_psr=0 i915.fastboot=1
i915 is also loaded as module in mkinitcpio. The hardware is a Tuxedo InfinityBook  with an Intel i7-1165G7.

Everything worked flawlessly in systemd 251. enable_psr=0 is needed on my system to fix an issue with the laptop display not refreshing correctly.

### Unexpected behaviour you saw

Starting with systemd 252, using the kernel parameters causes the i915 kernel module to fail to load:
`[    1.214790] i915: 0^\x13E invalid for parameter enable_psr`

Reverting systemd and systemd-libs back to 251.4 resolves the issue.

### Steps to reproduce the problem

Update systemd to 252 and use probably any i915 kernel parameter that takes a boolean value as 0 or 1.

**Comment by medhefgo** [comment] 2022-11-26 17:20
Should be fixed by https://github.com/systemd/systemd/pull/25222

**Comment by medhefgo** [comment] 2022-11-27 13:09
Also, best way to test if it's caused by the stub is to test with a regular (non-UKI) boot entry. (Or update to v252 and then replace the stub in `/usr/lib/systemd/boot/efi/linuxx64.efi.stub` with the one from v251).

**Closed as completed** 2022-11-28 14:49 UTC
Labels: pid1, regression ⚠️
