### ISSUE TITLE
Scheduled reboot reboots immediately if dbus is not available

### ISSUE THREAD

**Issue by joalif** [systemd/systemd#17575] opened 2020-11-11 18:07 UTC
**systemd version the issue has been seen with**
 > 246.6-1ubuntu1

**Used distribution**
 > Ubuntu Groovy

**Linux kernel version used** (`uname -a`)
 > Linux groovy 5.8.0-28-generic #30-Ubuntu SMP Thu Nov 5 13:24:33 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > When performing a scheduled reboot, it is expected the system to reboot at the specified time.

**Unexpected behaviour you saw**
 > In case dbus is not available the system reboots immediately.

**Steps to reproduce the problem**
 > \# systemctl stop dbus.service
 \# systemctl stop dbus.socket
 \# shutdown +1140 -r "REBOOT!"
Failed to set wall message, ignoring: Failed to activate service 'org.freedesktop.login1': timed out (service_start_timeout=25000ms)
Failed to call ScheduleShutdown in logind, proceeding with immediate shutdown: Connection timed out
Connection to groovy closed by remote host.
Connection to groovy closed.

From the sources it seems that this is intended : 
https://github.com/systemd/systemd/blob/master/src/systemctl/systemctl-logind.c#L318
However, I report this as a bug since this is against the logic of a scheduled reboot; if someone schedules a reboot they want the system to reboot at the specified time not immediately.
Is there anything that could be done to address this ?

**Comment by mbiebl** [comment] 2020-11-11 19:04
I guess logging an error and doing nothing would probably a better alternative.

**Comment by mbiebl** [comment] 2020-11-11 19:11
A somewhat related downstream bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931235

**Comment by mbiebl** [comment] 2020-11-11 19:11
And https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=960042

**Comment by poettering** [comment] 2020-11-13 16:20
I am not convinced not doing anything would be a better idea...

**Comment by poettering** [comment] 2020-11-13 16:22
I mean, the funcitonality is simply not available if you remove logind or dbus. Don't do that. We do the next closest thing, which is reach the ultimate goal, which is rebooting. Of course, we do it earlier than intended, but I think more people would be pissed if we wouldn't reboot at all in this case.

I am inclined to just close this.

I don't even think we should document this. It's very cleary documented that dbus is not an option, and if you disable it YMMV. Hence, what you are doing is your own fault, and you need to know what you do.

**Comment by poettering** [comment] 2020-11-13 16:23
In the log message even says exactly what it is doing, so I don't think there's anything to change here.

**Comment by mbiebl** [comment] 2020-11-13 16:38
> Of course, we do it earlier than intended, but I think more people would be pissed if we wouldn't reboot at all in this case.

It's hard to tell, but given that this issue has been raised several times over the years, it's apparently a behaviour that people didn't expect.Failing safe and doing nothing seems the safer choice to me, then doing only half of the requested action.

**Comment by poettering** [comment] 2020-11-13 16:40
i am pretty sure that there the same amount of people who#d be pissed if we just fail. I don#t think we could win this. And it's pointless, you are using the system outside of the supported usecase anyway.

I am really not convinced the proposed failing behaviour would be better than the current one.

**Comment by mbiebl** [comment] 2020-11-13 16:51
> i am pretty sure that there the same amount of people who#d be pissed if we just fail

We don't have any data which would confirm that. It's pure speculation. So the better question is, what the most sensible behaviour in this case should be. Immediately rebooting isn't, as it catches the admin who scheduled the scheduled shutdown, off guard, possibly in midst of ongoing work.
With an error message that is logged, he can instead choose the proper reaction.

**Comment by poettering** [comment] 2020-11-13 17:38
well, i simply disagree that this isn't the most sensible behaviour. if people ask for a shutdown, we give a shutdown. just not shutting down is a shitty option I believe.

and we do log an error message already, but we also do what the user asked, just a bit earlier.

**Comment by poettering** [comment] 2020-11-13 17:39
if you want the behaviour you are asking for, there's a very easy fix btw, just install fricking dbus. You are shooting yourself in the foot, by saying "i have patched around in my system, now it doesn#t work as intended", to which i can just say "your own damn fault", i am sorry.

If you want delayed shutdown to work, then run dbus, it's documented to not be optional.

**Comment by mcv21** [comment] 2020-12-02 10:52
Perhaps some more context would help here - while stopping dbus provides a straightforward reproducer of the issue, it's not the entire motivating case. "Admin uninstalled dbus" isn't the only reason you'll encounter this problem.

We had some of our systems get into an unhappy state - logind had failed (see log extracts below). The system was still at least somewhat useable, and is one we use for interactive sessions. So we needed to reboot it to return it to normal operation, but to do so with a bit of notice to our users. So we tried to schedule an advanced shutdown, but instead the system shut down immediately:

```
root@farm5-head1:/var/log# shutdown +1140 -r  "Reboot required" 
	Failed to set wall message, ignoring: Connection timed out
Failed to call ScheduleShutdown in logind, proceeding with immediate shutdown: Connection timed out
root@farm5-head1:/var/log# client_loop: send disconnect: Broken pipe
```

I would hope that @poettering would agree that this isn't the correct failure mode - instead giving us the option of immediate shutdown or trying again later would have let us give our users the notice of shutdown that they rightfully expect. 

```
Oct 5 13:33:25 farm5-head1 systemd[1]: systemd-logind.service: Scheduled restart job, restart counter is at 10.
Oct 5 13:33:25 farm5-head1 systemd[1]: Stopped Login Service.
Oct 5 13:33:25 farm5-head1 systemd[1]: Starting Login Service...
Oct 5 13:33:25 farm5-head1 systemd[1]: Started Login Service.
Oct 5 13:36:26 farm5-head1 systemd[1]: systemd-logind.service: Watchdog timeout (limit 3min)!
Oct 5 13:36:26 farm5-head1 systemd[1]: systemd-logind.service: Killing process 29841 (systemd-logind) with signal SIGABRT.
Oct 5 13:37:56 farm5-head1 systemd[1]: systemd-logind.service: State 'stop-sigabrt' timed out. Terminating.
Oct 5 13:39:26 farm5-head1 systemd[1]: systemd-logind.service: State 'stop-sigterm' timed out. Killing.
Oct 5 13:39:26 farm5-head1 systemd[1]: systemd-logind.service: Killing process 29841 (systemd-logind) with signal SIGKILL.
Oct 5 13:39:26 farm5-head1 systemd[1]: systemd-logind.service: Main process exited, code=killed, status=9/KILL
Oct 5 13:39:26 farm5-head1 systemd[1]: systemd-logind.service: Failed with result 'watchdog'.
Oct 5 13:39:26 farm5-head1 ModemManager[5025]: <warn> [sleep-monitor] inhibit failed: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
Oct 5 13:39:26 farm5-head1 systemd[1]: systemd-logind.service: Service has no hold-off time, scheduling restart.
```

**Comment by poettering** [comment] 2021-01-11 16:04
Let's close this, as per discussion in #18010.

**Closed as completed by poettering** 2021-01-11 16:04 UTC
Labels: needs-discussion 🤔, systemctl
