### ISSUE TITLE
resolved: explain differences in search path handling between nss-dns and nss-resolve when both talk to resolved

### ISSUE THREAD

**Issue by remram44** [systemd/systemd#16584] opened 2020-07-25 17:13 UTC
**systemd version the issue has been seen with**
systemd 245 (`245.4-4ubuntu3.2`)

**Used distribution**
Ubuntu 20.04

**Expected behaviour you didn't see**
Resolving `localhost` always works, does not go to the network

**Unexpected behaviour you saw**
Works when disconnected, however when connected to a bad link resolving `localhost` takes a long time, times out, or fails with:

```
$ host localhost
Host localhost.hsd1.ma.comcast.net not found: 2(SERVFAIL)
```

**Steps to reproduce the problem**
* Use systemd-resolved (Ubuntu default configuration)
* Have `localhost` in /etc/hosts (Ubuntu default configuration)
* Be on a bad link (firewall DNS or turn off router or just be in a rural area)
* Can't access `localhost` when the network is acting up, have to manually disconnect for it to resolve again

To reproduce using ufw:
```
$ ufw deny out proto udp to any port 53
$ resolvectl flush-caches
$ host localhost.
localhost has address 127.0.0.1
$ host localhost
... hang ...
```

<details>
<summary><code>resolvctl status</code></summary>

```
Global
       LLMNR setting: no                  
MulticastDNS setting: no                  
  DNSOverTLS setting: no                  
      DNSSEC setting: no                  
    DNSSEC supported: no                  
          DNSSEC NTA: 10.in-addr.arpa     
                      16.172.in-addr.arpa 
                      168.192.in-addr.arpa
                      17.172.in-addr.arpa 
                      18.172.in-addr.arpa 
                      19.172.in-addr.arpa 
                      20.172.in-addr.arpa 
                      21.172.in-addr.arpa 
                      22.172.in-addr.arpa 
                      23.172.in-addr.arpa 
                      24.172.in-addr.arpa 
                      25.172.in-addr.arpa 
                      26.172.in-addr.arpa 
                      27.172.in-addr.arpa 
                      28.172.in-addr.arpa 
                      29.172.in-addr.arpa 
                      30.172.in-addr.arpa 
                      31.172.in-addr.arpa 
                      corp                
                      d.f.ip6.arpa        
                      home                
                      internal            
                      intranet            
                      lan                 
                      local               
                      private             
                      test

Link 3 (wlp4s0)
      Current Scopes: DNS                
DefaultRoute setting: yes                
       LLMNR setting: yes                
MulticastDNS setting: no                 
  DNSOverTLS setting: no                 
      DNSSEC setting: no                 
    DNSSEC supported: no                 
  Current DNS Server: 75.75.75.75        
         DNS Servers: 75.75.75.75        
                      75.75.76.76        
                      2001:558:feed::1   
                      2001:558:feed::2   
          DNS Domain: ~.                 
                      hsd1.ma.comcast.net
```
</details>

<details>
<summary>resolved.conf</summary>

```
[Resolve]
#DNS=
#FallbackDNS=
#Domains=
#LLMNR=no
#MulticastDNS=no
#DNSSEC=no
#DNSOverTLS=no
#Cache=yes
#DNSStubListener=yes
#ReadEtcHosts=yes
```
</details>

<details>
<summary>/etc/hosts</summary>

```
127.0.0.1       localhost
127.0.1.1       axon

127.0.0.1       some-server

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```
</details>

**Comment by TriMoon** [comment] 2020-07-26 06:38
Did you try to resolve `localhost.` instead of `localhost` ?
Because your output is expected behavior AFAIK, your DNS-Search-list(s) will be appended for lookups when providing non-FQDN.

**Comment by keszybz** [comment] 2020-07-26 09:34
`grep hosts /etc/nsswitch.conf` ?

**Comment by remram44** [comment] 2020-07-26 18:19
`localhost.` works, however you understand that using FQDNs in URLs is very unusual and most tools will not generate such URLs. For example, if use Jupyter Notebooks or Webpack's server or anything, my browser will open to the "localhost" domain. If such tools stop working when my link is bad it is a huge hassle.

```
$ grep hosts /etc/nsswitch.conf
hosts:          files mdns4_minimal [NOTFOUND=return] dns myhostname
```

**Comment by keszybz** [comment] 2020-07-26 18:57
Search domain suffixing happens in the nss modules, so when resolved answers queries over dns unicast protocol on port 53, it gets a FQDN and resolves that. This explains why `localhost.` is resolved as you expect it. `localhost` (without the dot) will be resolved correctly by nss-files. So for example, `ping localhost` will work.

There is no bug here, but we should probably explain that better in the man page.

**Comment by remram44** [comment] 2020-07-26 20:42
`systemd-resolved.service(8)` mentions:

```
SYNTHETIC RECORDS
       systemd-resolved synthesizes DNS resource records (RRs) for the
       following cases:
(...)
       •   The hostnames "localhost" and "localhost.localdomain" (as well as
           any hostname ending in ".localhost" or ".localhost.localdomain")
           are resolved to the IP addresses 127.0.0.1 and ::1.
```

and

```
PROTOCOLS AND ROUTING
       Lookup requests are routed to the available DNS servers, LLMNR and
       MulticastDNS interfaces according to the following rules:

       •   Lookups for the special hostname "localhost" are never routed to
           the network. (A few other, special domains are handled the same
           way.)
```

While it is possible to claim that this behavior has simply changed without update to the documentation, it seems more likely to me that this is a genuine block and the doc is correct. The search domain is not supposed to be used for `localhost`.

**Comment by keszybz** [comment] 2020-07-27 08:19
The **label** "localhost" is not reserved. For example, you can define `localhost.example.com`. What is treated specially is `localhost.` and `localhost.localdomain.`. But as mentioned above, this special handling is mostly done in nss modules, and not in the DNS resolver as such. The docs don't make this clear, because they effectively describe what the whole behaviour is without making a distinction between different components and protocols to access systemd-resolved. This something that we should improve.

**Comment by TriMoon** [comment] 2020-07-29 09:05
> `localhost.` works, however you understand that using FQDNs in URLs is very unusual and most tools will not generate such URLs. For example, if use Jupyter Notebooks or Webpack's server or anything, my browser will open to the "localhost" domain. If such tools stop working when my link is bad it is a huge hassle.
> 
> ```
> $ grep hosts /etc/nsswitch.conf
> hosts:          files mdns4_minimal [NOTFOUND=return] dns myhostname
> ```
Check out [nsswitch.conf(5)](https://www.man7.org/linux/man-pages/man5/nsswitch.conf.5.html) :wink:

**Comment by remram44** [comment] 2020-07-29 17:04
@TriMoon I already have `files` first... If there's a trick to prevent the search domain from being appended, I don't see it.

**Comment by poettering** [comment] 2020-08-06 16:52
> @TriMoon I already have `files` first... If there's a trick to prevent the search domain from being appended, I don't see it.

use `host`'s `-N 0` switch, it turns off suffixing.

Turning this into a documentation bug, given @keszybz' suggestions to explain things better.

**Comment by remram44** [comment] 2020-08-06 17:06
Unless there are similar switches for every applications (including my web browser...) this is not a fix for me. I suppose I will have to evaluate other DNS server options, or have to live with this bug.

**Comment by poettering** [comment] 2020-08-06 20:04
@remram44 the search path logic in `host` is done client side, inside of the tool itself. The server cannot do anything about that. It doesn't matter which server you run, because based on your `/etc/resolv.conf` the `host` tool will suffix the host you specify no matter what. Unless of course you turn that off in `host` via `-N 0`.

By the time the first DNS request reaches resolved it is hence already suffixed. To implement what we are asking for, we'd have to filter all requests, if they start with "localhost", but that's a bit too far outside of DNS specs.

**Comment by remram44** [comment] 2020-08-06 20:08
I get what you're saying, it still feels like a bug though. Should this be filed against nss? Or is it something only apps themselves can work around?

**Comment by poettering** [comment] 2020-08-06 20:17
Well, you are using a low-level DNS tool, `host`, you kinda get what you pay for here: it follows DNS logic by the letter...

RFC6761 declares the `localhost.` domain to be special and any names suffixed by it, but it doesn't say that names *prefixed* with it were in any way special.

If you want this fixed, consider filing bugs against affected programs asking them to handle the name `localhost` special and not do search path suffixing on it. But quite frankly, good luck with that... I don't think `host` maintainers would be particularly sympathetic to the idea, as you used a DNS tool to resolve `localhost`, not a glibc NSS tool, and hence you should expect to get DNS behaviour.

**Comment by remram44** [comment] 2020-08-06 20:19
Oh, I'm sorry, `host` was merely the way I reproduced the problem, my annoyance comes from Firefox not loading pages from `localhost` while my WiFi is recovering. Apologies for the confusion.

**Comment by poettering** [comment] 2020-08-06 20:33
well, i think ff sometimes does its own dns these days (if you enable DoH?), where you then are in the same boat as with `host`. But I think you can make it use glibc NSS too. don't know the details. They might be more open to disabling client-side search path logic for `hostname` if they indeed do their own DNS...

How does your nsswitch.conf look like?

**Comment by remram44** [comment] 2020-08-06 21:09
`nsswitch.conf` is [above](#issuecomment-664022923)

<details><summary>Full file (Ubuntu default)</summary>

```
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         compat systemd
group:          compat systemd
shadow:         compat
gshadow:        files

hosts:          files mdns4_minimal [NOTFOUND=return] dns myhostname
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis

```

</details>

**Comment by poettering** [comment] 2020-08-06 21:16
I would expect that firefox would honour /etc/hosts if it indeed does DNS on its own. Given that you list `localhost` there, I am a bit surprised you are saying that it still does search path logic there...

Try to find our if your firefox does DNS on its own, or uses plain glibc NSS for host name resolution

**Comment by remram44** [comment] 2020-08-06 21:43
What happened is that I noticed the issue in Firefox, and when `host` showed the same issue I assumed it was a system-wide or `resolved` problem. However it just happens that both programs are special. Indeed, I have confirmed that `curl` and Chrome can resolve `localhost` URLs while DNS is blocked, it's just Firefox (and `host`) that can't. If I had checked with curl instead of `hosts` I wouldn't have bothered you, sorry about that.

I have tried a few different options in Firefox but to no avail. I guess I will have to use `127.0.0.1` instead of `localhost` until Firefox is fixed.

Thanks again

**Comment by keszybz** [comment] 2020-08-07 07:51
Ubuntu uses resolved in a different way than the usual: it does not use nss-resolve, but sets 127.0.0.1 in /etc/resolv.conf. That's why I added the `downstream/ubuntu` label. Users of other distros will not usually see this.

**Comment by xnox** [comment] 2020-08-07 11:09
> Ubuntu uses resolved in a different way than the usual: it does not use nss-resolve, but sets 127.0.0.1 in /etc/resolv.conf. That's why I added the `downstream/ubuntu` label. Users of other distros will not usually see this.
> 
> edit: you can use `hosts: resolve [!UNAVAIL=return] myhostname files mdns4_minimal [NOTFOUND=return] dns`. This will probably fix this issue, but it's a pretty big departure from Ubuntu defaults.
> 
> /cc @xnox

Please do not recommend hand editting nsswitch.conf on ubuntu. And simply editing to enable resolve module will not work, as in Debian/Ubuntu it is packaged into a separate package which one needs to install.....

.... also I do not believe that the issue the reporter is reporting would be solved by installing and enabling nss-resolve module, would it? because `host` util and `firefox` do not use nsswitch.conf or do they? They only talk to things listed in `/etc/resolv.conf`.

**Comment by xnox** [comment] 2020-08-07 11:16
```
$ dig @127.0.0.53 localhost

; <<>> DiG 9.16.4-Ubuntu <<>> @127.0.0.53 localhost
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37717
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;localhost.			IN	A

;; ANSWER SECTION:
localhost.		0	IN	A	127.0.0.1

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Fri Aug 07 12:16:32 BST 2020
;; MSG SIZE  rcvd: 54
```

Returns very quickly for me though.

**Comment by xnox** [comment] 2020-08-07 11:21
@remram44 

Do you actually use
```
DNS Domain: ~.                 
                      hsd1.ma.comcast.net
```
And where did it come from? If you comment out the search hsd1.ma.comcast.net do things work as expected? Since you do not want things to search for domains in hsd1.ma.comcast.net it should not be configured as such.

I wonder if the solution for you, is then to do:

```
$ sudo ln -sf /lib/systemd/resolv.conf /etc/resolv.conf
```

Such that your local resolution is done without any search domains.

**Comment by remram44** [comment] 2020-08-07 15:17
I did not configure a search domain, I get it from DHCP.

Changing the symlink fixes the issue for `host`, but not Firefox.

**Comment by xnox** [comment] 2020-08-07 18:18
> I did not configure a search domain, I get it from DHCP.
> 
> Changing the symlink fixes the issue for `host`, but not Firefox.

Which firefox version is that? Just whatever Ubuntu ships, right? I'll try to reproduce it, it sounds really weird.

**Comment by remram44** [comment] 2020-08-07 18:28
79.0 (`79.0+build1-0ubuntu0.20.04.1`)

**Comment by TriMoon** [comment] 2020-08-13 13:41
> @remram44 , I did not configure a search domain, I get it from DHCP.

It's been a while since i visited this issue, that said:
Maybe you should reconfigure your network setup to only use the IP from DHCP without the DNS from it?
(I have no idea which system you use to configure your network because there are many ways...)

**Comment by remram44** [comment] 2020-08-13 14:08
NetworkManager has a way to add search domains but not remove them:

![NetworkManager screenshot](https://user-images.githubusercontent.com/426784/90144420-c9bbc300-dd4c-11ea-99e4-88f930e79bec.png)

Changing the `/etc/resolv.conf` link is the only way I know...

**Comment by TriMoon** [comment] 2020-08-13 14:16
There should be an option under "Method" to only use the IP with DHCP....

**Comment by remram44** [comment] 2020-08-13 14:23
I assumed that would also ignore DNS servers.

**Comment by TriMoon** [comment] 2020-08-17 11:30
> I assumed that would also ignore DNS servers.

Wasn't that the point of https://github.com/systemd/systemd/issues/16584#issuecomment-670469000 ?
Because the search domain "hsd1.ma.comcast.net" gets added currently by using plain automatic (full DHCP).
You could then manually add the modem's IP as DNS-server in case you don't run a local DNS-Server, because most modems are used as DNS-replicators.
Maybe there are other ways to ignore the search list provided by DHCP using `*.network` config files, but im unable to provide you such at moment.

**Comment by xnox** [comment] 2020-08-17 13:40
Pure systemd.network has a config option https://www.freedesktop.org/software/systemd/man/systemd.network.html#UseDomains= which dictates whether or not to use DHCP discovered search domains. I am not sure this is available via NetworkManager.

However, this still feels like a bug to me. Because even with (broken) search domains / DNS servers that timeout and never respond, resolving "localhost" should just work instantly via `/etc/hosts` irrespective of anything. Unless I misunderstand something, because I always thought that `/etc/hosts` takes priority for perfect match domains even when queried without the trailing `.` .

Otherwise it would be interesting if one can effectively high jack the traffic by publishing search domain, capturing `localhost.$my-search-domain` traffic, and redirecting it to 127.0.0.1  / `localhost.`. Such that somebody using `localhost` which connected to public WiFi leaks all the traffic that is otherwise assumed to be local.

**Comment by xnox** [comment] 2020-08-17 13:47
Could you please navigate to about:config in Firefox, and search for "localhost" can you paste what values are set of all the options?

**Comment by remram44** [comment] 2020-08-26 03:24
I don't see anything like that:

![screenshot of Firefox config](https://user-images.githubusercontent.com/426784/91251744-111d5880-e72a-11ea-8c2c-9aa57bc023e0.png)

**Closed as completed** 2021-03-01 14:14 UTC
Labels: documentation, downstream/debian
