### ISSUE TITLE
add support for loopback files in /etc/crypttab

### ISSUE THREAD

**Issue by JohannesBuchner** [systemd/systemd#1541] opened 2015-10-12 16:33 UTC
Dear all,

In my system I have a filesystem (/mnt/data) which is mounted fine at boot time. Inside that I have a dm/LUKS filesystem (file /mnt/data/myfs.data) which should be mounted as well. I put that into /etc/crypttab, and that loads. 
However, inside that I have reiserfs filesystems that do not mount on boot. I am dropped in a root shell where I do mount -a and exit and everything is fine.

I think the issue is that the mounting process of systemd, after reading /etc/fstab, does not realise/respect the necessary order, even though I placed 0, 2, 3 in the last column.

How can I set this up so that everything works automatically?
Can I disable parallel mounting somehow, or define what mounting should occur before/after devmapper mounts?

**Comment by JohannesBuchner** [comment] 2015-10-12 16:43
Journal output of mount failure:

```
Oct 11 21:40:26 hostname systemd-cryptsetup[264]: crypt_init() failed: Block device required
Oct 11 21:40:26 hostname systemd[1]: systemd-cryptsetup@data.enc.service: main process exited, code=exited, status=1/FAILURE
Oct 11 21:40:26 hostname systemd[1]: Failed to start Cryptography Setup for data.enc.
Oct 11 21:40:26 hostname systemd[1]: Dependency failed for dev-mapper-data.enc.device.
Oct 11 21:40:26 hostname systemd[1]: Dependency failed for File System Check on /dev/mapper/data.enc.
Oct 11 21:40:26 hostname systemd[1]: Dependency failed for /mnt/data/data.
Oct 11 21:40:26 hostname systemd[1]: Dependency failed for /mnt/data/data/myfs.
Oct 11 21:40:26 hostname systemd[1]: Dependency failed for Local File Systems.
Oct 11 21:40:26 hostname systemd[1]: Job local-fs.target/start failed with result 'dependency'.
Oct 11 21:40:26 hostname systemd[1]: Job mnt-data-data-myfs.mount/start failed with result 'dependency'.
Oct 11 21:40:26 hostname systemd[1]: Dependency failed for /mnt/data/data/myfs2.
Oct 11 21:40:26 hostname systemd[1]: Job mnt-data-data-myfs2.mount/start failed with result 'dependency'.
Oct 11 21:40:26 hostname systemd[1]: Dependency failed for /mnt/data/data/myfs3.
Oct 11 21:40:26 hostname systemd[1]: Job mnt-data-data-myfs3.mount/start failed with result 'dependency'.
Oct 11 21:40:26 hostname systemd[1]: Dependency failed for /mnt/data/data/myfs4.
Oct 11 21:40:26 hostname systemd[1]: Job mnt-data-data-myfs4.mount/start failed with result 'dependency'.
Oct 11 21:40:26 hostname systemd[1]: Job mnt-data-data.mount/start failed with result 'dependency'.
Oct 11 21:40:26 hostname systemd[1]: Job systemd-fsck@dev-mapper-data.enc.service/start failed with result 'dependency'.
Oct 11 21:40:26 hostname systemd[1]: Job dev-mapper-data.enc.device/start failed with result 'dependency'.
Oct 11 21:40:26 hostname systemd[1]: Dependency failed for Encrypted Volumes.
Oct 11 21:40:26 hostname systemd[1]: Job cryptsetup.target/start failed with result 'dependency'.
Oct 11 21:40:26 hostname systemd[1]: Unit systemd-cryptsetup@data.enc.service entered failed state.
Oct 11 21:40:26 hostname systemd[1]: systemd-cryptsetup@data.enc.service failed.
```

Can be manually mounted in root shell with

```
cryptsetup open /mnt/data/data.enc.fs data.enc
mount /dev/mapper/data.enc /mnt/data/data
mount -a
```

**Comment by poettering** [comment] 2015-10-13 16:09
hmm, did i get this right, you have a loopback file you have a LUKS fs inside? we do not support such a thing with systemd's own cryptsetup logic at all, and that's what fails. I figure we could add that though.

**Comment by JohannesBuchner** [comment] 2015-10-13 16:55
Correct.

**Comment by medhefgo** [comment] 2016-04-18 20:38
It should work just fine. The generated unit file for the luks container file should have a proper RequiresMountsFor= directive. Can you give me the crypttab line and fstab line for all the relevant filesystems/devices in question?

**Comment by JohannesBuchner** [comment] 2016-04-18 20:48
Gladly.

/etc/crypttab:
data.enc /mnt/data/data.enc - 

/etc/fstab:
/dev/sda5       /mnt/data   ext4        noatime     0 0
/dev/mapper/data.enc /mnt/data/data/ ext4          auto            0 2
/mnt/data/data/allresults.fs /mnt/data/data/allresults reiserfs loop,nodev,user,users,noatime,notail 0 3

**Comment by medhefgo** [comment] 2016-04-19 08:40
Can you give me the generated unit files for these from /run/systemd/generator ?

**Comment by poettering** [comment] 2016-04-19 09:28
So, as it turns out we actually support this since a while already, see the discussion in #2963. Closing this one.

**Comment by JohannesBuchner** [comment] 2016-04-19 11:05
@poettering : I have 226-r2, which version is supposed to support this?

**Comment by JohannesBuchner** [comment] 2016-04-19 11:09
/run/systemd/generator/cryptsetup.target.requires/systemd-cryptsetup\@data.enc.service
[Unit]
Description=Cryptography Setup for %I
Documentation=man:crypttab(5) man:systemd-cryptsetup-generator(8) man:systemd-cryptsetup@.service(8)
SourcePath=/etc/crypttab
DefaultDependencies=no
Conflicts=umount.target
BindsTo=dev-mapper-%i.device
IgnoreOnIsolate=true
After=cryptsetup-pre.target
Before=cryptsetup.target
RequiresMountsFor=/mnt/data/data.enc

[Service]
Type=oneshot
RemainAfterExit=yes
TimeoutSec=0
ExecStart=/usr/lib/systemd/systemd-cryptsetup attach 'data.enc' '/mnt/data/data.enc' '-' ''
ExecStop=/usr/lib/systemd/systemd-cryptsetup detach 'data.enc'

/run/systemd/generator/dev-mapper-data.enc.device.requires/systemd-cryptsetup\@data.enc.service
[Unit]
Description=Cryptography Setup for %I
Documentation=man:crypttab(5) man:systemd-cryptsetup-generator(8) man:systemd-cryptsetup@.service(8)
SourcePath=/etc/crypttab
DefaultDependencies=no
Conflicts=umount.target
BindsTo=dev-mapper-%i.device
IgnoreOnIsolate=true
After=cryptsetup-pre.target
Before=cryptsetup.target
RequiresMountsFor=/mnt/data/data.enc

[Service]
Type=oneshot
RemainAfterExit=yes
TimeoutSec=0
ExecStart=/usr/lib/systemd/systemd-cryptsetup attach 'data.enc' '/mnt/data/data.enc' '-' ''
ExecStop=/usr/lib/systemd/systemd-cryptsetup detach 'data.enc'

/run/systemd/generator/mnt-data-data.mount
[Unit]
SourcePath=/etc/fstab
Documentation=man:fstab(5) man:systemd-fstab-generator(8)
Before=local-fs.target
RequiresOverridable=systemd-fsck@dev-mapper-data.enc.service
After=systemd-fsck@dev-mapper-data.enc.service

[Mount]
What=/dev/mapper/data.enc
Where=/mnt/data/data
Type=ext4
Options=auto

/run/systemd/generator/mnt-data-data.enc.device.wants/systemd-cryptsetup\@data.enc.service
[Unit]
Description=Cryptography Setup for %I
Documentation=man:crypttab(5) man:systemd-cryptsetup-generator(8) man:systemd-cryptsetup@.service(8)
SourcePath=/etc/crypttab
DefaultDependencies=no
Conflicts=umount.target
BindsTo=dev-mapper-%i.device
IgnoreOnIsolate=true
After=cryptsetup-pre.target
Before=cryptsetup.target
RequiresMountsFor=/mnt/data/data.enc

[Service]
Type=oneshot
RemainAfterExit=yes
TimeoutSec=0
ExecStart=/usr/lib/systemd/systemd-cryptsetup attach 'data.enc' '/mnt/data/data.enc' '-' ''
ExecStop=/usr/lib/systemd/systemd-cryptsetup detach 'data.enc'

[Unit]
SourcePath=/etc/fstab
Documentation=man:fstab(5) man:systemd-fstab-generator(8)
Before=local-fs.target
RequiresOverridable=systemd-fsck@dev-mapper-data.enc.service
After=systemd-fsck@dev-mapper-data.enc.service

[Mount]
What=/dev/mapper/data.enc
Where=/mnt/data/data
Type=ext4
Options=auto

[Unit]
SourcePath=/etc/fstab
Documentation=man:fstab(5) man:systemd-fstab-generator(8)
Before=local-fs.target

[Mount]
What=/mnt/data/data/PostDoc/research/grb/allresults.fs
Where=/mnt/data/data/PostDoc/research/grb/allresults
Type=reiserfs
Options=loop,nodev,user,users,noatime,notail

**Comment by JohannesBuchner** [comment] 2016-04-19 11:59
I think my issue is that the filesystems inside are not mounted after, so it enters root login. But also there, the encrypted fs is not mounted.

**Comment by medhefgo** [comment] 2016-04-19 13:30
Looking at the reiserfs unit file, it is missing the dependency for the underlying mounts. Could you try adding "x-systemd.requires-mounts-for=/mnt/data/data/PostDoc/research/grb/allresults.fs"  to the fstab options (and similar to any other such mount points that depend on container files)? Adjust the file path if needed.

See https://github.com/systemd/systemd/commit/3519d230c8bafe834b2dac26ace49fcfba139823

**Comment by JohannesBuchner** [comment] 2016-05-29 13:56
I did that, but the problem is in crypt_init(), which needs a block device. 

May 29 09:48:19 hostname systemd-cryptsetup[288]: crypt_init() failed: Block device required
May 29 09:48:19 hostname systemd[1]: systemd-cryptsetup@data.enc.service: Main process exited, code=exited, status=1/FAILURE
May 29 09:48:19 hostname systemd[1]: Failed to start Cryptography Setup for data.enc.
May 29 09:48:19 hostname systemd[1]: Dependency failed for dev-mapper-data.enc.device.

This is with 226-r2; would upgrading to 229 or 230 make a difference?

**Comment by JohannesBuchner** [comment] 2016-05-29 15:35
230 yields the same error, therefore please REOPEN this bug.

**Comment by poettering** [comment] 2020-08-28 16:29
I just verified that this works fine with 247. Closing.

(You need a somewhat non-ancient libcryptsetup to do the loopback stuff properly, but then it should just work as expected). 

Closing hence.

Please open a new bug, if this remains reproducible on current userspace.

**Closed as completed by poettering** 2020-08-28 16:29 UTC
Labels: RFE 🎁, cryptsetup
