### ISSUE TITLE
test: boot-and-services fails on bionic-s390x CI

### ISSUE THREAD

**Issue by yuwata** [systemd/systemd#12709] opened 2019-05-31 07:46 UTC
E.g. https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-upstream-systemd-ci-systemd-ci/bionic/s390x/s/systemd-upstream/20190531_055427_1a76b@/log.gz
```
======================================================================
FAIL: test_failing (__main__.SeccompTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest.1Q9k50/build.QeG/systemd/debian/tests/boot-and-services", line 421, in test_failing
    self.assertIn(b'code=killed, signal=SYS', out)
AssertionError: b'code=killed, signal=SYS' not found in b"\xe2\x97\x8f scfail.service - seccomp test\n   Loaded: loaded (/run/systemd/system/scfail.service; static; vendor preset: enabled)\n   Active: failed (Result: core-dump) since Fri 2019-05-31 05:31:48 UTC; 742ms ago\n  Process: 751 ExecStart=/bin/cat /etc/machine-id (code=dumped, signal=SYS)\n Main PID: 751 (code=dumped, signal=SYS)\n      CPU: 3ms\n\nMay 31 05:31:48 autopkgtest systemd[1]: Started seccomp test.\nMay 31 05:31:48 autopkgtest systemd[1]: scfail.service: Main process exited, code=dumped, status=31/SYS\nMay 31 05:31:48 autopkgtest systemd[1]: scfail.service: Failed with result 'core-dump'.\nMay 31 05:31:48 autopkgtest systemd[1]: scfail.service: Consumed 3ms CPU time.\n"

----------------------------------------------------------------------
Ran 23 tests in 10.739s

FAILED (failures=1, skipped=5)
autopkgtest [05:31:49]: test boot-and-services: -----------------------]
autopkgtest [05:31:49]: test boot-and-services:  - - - - - - - - - - results - - - - - - - - - -
boot-and-services    FAIL non-zero exit status 1
```

**Comment by cdown** [comment] 2019-05-31 18:37
Looks like it's because it's `code=dumped`, rather than `code=killed`, which it's looking for.

I'm not sure the exact semantics of dumping or not matter much here, maybe we should just look for signal=SYS?

**Comment by evverx** [comment] 2019-05-31 21:37
Looks like https://github.com/systemd/systemd/pull/12430 coupled with the switch from `libseccomp-2.3.1` to `libsecomp-2.4.1` on Ubuntu Bionic has made test obsolete. I've just reported it in https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1831296. @xnox FYI I'll turn it off in a couple of days if it isn't fixed. No hard feelings.

**Comment by evverx** [comment] 2019-05-31 21:54
On the other hand, it's Friday (or Saturday depending on time zones) so it's unlikely anyone is going to take a look at it until Monday. I'll go ahead and turn it off.

I've subscribed to both https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1829829 and https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1831296 so it wouldn't be hard to turn it on again once the issues are fixed.

**Comment by cdown** [comment] 2019-05-31 21:57
After some digging, looks like it's caused by c3ab2c389ee60d92fb8d7fe779ae9c4e3c092e4c. I guess we had the CI off when this was merged

**Comment by evverx** [comment] 2019-05-31 22:02
Ubuntu CI (at least bionic-s390x) was turned on but it wasn't caught because [according to the logs](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-upstream-systemd-ci-systemd-ci/bionic/s390x/s/systemd-upstream/20190524_094329_c3a75@/log.gz) `libseccomp-2.3.1-2.1ubuntu4.1` was used there. The switch to `libsecomp-2.4.1` broke it completely I think.

**Closed as completed** 2019-06-10 00:10 UTC
Labels: tests, regression ⚠️, not-a-bug, ci
