### ISSUE TITLE
systemd-resolved causes Firefox to take forever to load without work around

### ISSUE THREAD

**Issue by HurricanePootis** [systemd/systemd#32546] opened 2024-04-29 07:17 UTC
### systemd version the issue has been seen with

255.5-2

### Used distribution

Arch Linux

### Linux kernel version used

6.8.7-zen1-2-zen

### CPU architectures issue was seen on

x86_64

### Component

resolvectl

### Expected behaviour you didn't see

That whenever I launch firefox, that the application starts right away. In order to get this behavior, I have to set NetworkManager to use localhost as the DNS with the following (as learned by [here](https://bbs.archlinux.org/viewtopic.php?id=281569)):
```
[global-dns-domain-*]
servers=::1,127.0.0.1
```

### Unexpected behaviour you saw

Firefox takes an extreme amount of time to start, more than a minute.

### Steps to reproduce the problem

NetworkManager set to use systemd-resolved in `/etc/NetworkManager/conf.d/systemdresolved.conf` with the following:
```
[main]
dns=systemd-resolved
```

Systemd-resolved is configured with the following options:
```
[Resolve]
DNS=1.1.1.1 2606:4700:4700::1111
FallbackDNS=1.0.0.1 2606:4700:4700::1001
DNSSEC=allow-downgrade
DNSOverTLS=yes
```

**Comment by HurricanePootis** [comment] 2024-04-29 07:21
[Here](https://gist.github.com/HurricanePootis/490923923fad0235f229267d425eb66e) is a strace of me launching it

**Comment by StenSoft** [comment] 2024-04-29 10:56
Sounds like #32531 but with allow-downgrade

**Comment by eworm-de** [comment] 2024-04-29 19:34
Can anybody tell if #32552 fixes this?

**Comment by rpigott** [comment] 2024-04-29 19:48
I think this is a duplicate of #32531. A debug log of sd-resolved could confirm.

**Comment by eworm-de** [comment] 2024-04-29 19:49
I think the same, but would like to have a confirmation. 😉

**Comment by bluca** [comment] 2024-04-29 21:05
https://github.com/systemd/systemd/issues/32531

**Closed as not planned by bluca** 2024-04-29 21:05 UTC
Labels: bug 🐛, resolve, duplicate
