### ISSUE TITLE
networkd - tap dev failing - TUNSETIFF failed on tun dev: Invalid argument

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#9416] opened 2018-06-25 16:52 UTC
**systemd version the issue has been seen with**
> 238 (in the LXC container)

**Used distribution**
 > host ubuntu 4.15.0-23 (being a VPS on a KVM hypervisor with `virtio` driver)
 > container archlinux
 > lxc 3.0.1

**Expected behaviour you didn't see**
 > `tap` succeeding

**Unexpected behaviour you saw**
 > `tap` failing

**Steps to reproduce the problem**

***tap.netdev***
```
[NetDev]
Name=tap0
Kind=tap
```
***tap.network***
```
[Match]
Name=tap0
[Network]
Bridge=br0
ConfigureWithoutCarrier=yes
```
(re)start `networkd`

---

> systemd-networkd[5061]: tap0: loaded tap
> systemd-networkd[5061]: tap0: TUNSETIFF failed on tun dev: Invalid argument

Adding 
```
[Tap]
OneQueue=yes
```
is producing the same error.

Adding instead
```
[Tap]
MultiQueue=yes
```
and no (such) error

**Comment by yuwata** [comment] 2018-06-25 17:34
Hmm, cannot reproduced. With `OneQueue=yes`,
```
$ cat /sys/class/net/tap0/tun_flags
0x3802
```
The meaning of the flags can be found [here](https://github.com/torvalds/linux/blob/b2fe5fa68642860e7de76167c3111623aa0d5de1/include/uapi/linux/if_tun.h#L63-L78).

**Comment by n8v8R** [comment] 2018-06-25 17:53
With no error that flag reads 

> 0x5902

And the same with the error, perhaps with the error it does not get to write a new flag.

That  `0x5902` flag is not mentioned on the referenced page.

**Comment by yuwata** [comment] 2018-06-25 18:03
> With no error that flag reads

You mean, without `OneQueue=`?

**Comment by n8v8R** [comment] 2018-06-25 18:23
Pardon for not being more clear. What I was trying to say is that the flag remained the same, whether the error was present or not.

What I found out now though is that the flag persistence only happens whith `systemctl restart systemd-networkd`

Now when the box is `shutdown` and booted up again **those errors are absent** and flags reading

no Queue---> `0x1802`
`OneQueue=yes` ---> `0x7802`
`MultiQueue=yes` ---> `0x5902`

Since the errors are gone with the reboot I am closing this.

It would be good though to have the documentation pointing out the need for a reboot as opposed to `systemctl restart systemd-networkd` in order to get the changed settings applied.

**Closed as completed by n8v8R** 2018-06-25 18:23 UTC
