### ISSUE TITLE
systemd-login disturbs all ptys on suspend

### ISSUE THREAD

**Issue by cgzones** [systemd/systemd#23520] opened 2022-05-25 21:53 UTC
**systemd version the issue has been seen with**
 > 251

**Used distribution**
 > Debian sid

**Linux kernel version used** (`uname -a`)
 > `Linux debianHome 5.17.0-2-amd64 #1 SMP PREEMPT Debian 5.17.6-1 (2022-05-14) x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > amd64

**Expected behaviour you didn't see**
 > ptys (e.g. Konsole or tmux) unchanged after suspend

**Unexpected behaviour you saw**
 >
 ```

Broadcast message from christian@debianHome on tty1 (Wed 2022-05-25 23:49:31 CEST):

The system is going down for suspend NOW!
```
> in every terminal

**Steps to reproduce the problem**
 > suspend the system, e.g. on a laptop close and reopen the lid

Please either disable broadcast messages for suspend or add a configuration switch to disable it.

Also reported at https://www.spinics.net/lists/fedora-devel/msg300498.html

Related commit: https://github.com/systemd/systemd/commit/cdf370626f

**Comment by AdrianusWest** [comment] 2022-05-25 22:26
I join in. It's a madhouse with these constant notifications!

**Comment by hl037** [comment] 2022-05-26 08:25
+1 on archlinux

**Comment by VorpalBlade** [comment] 2022-05-26 10:02
If this was only on shutdown I could understand it. However it is nonsensical and annoying to send these messages every time I suspend or hibernate my laptop by closing the lid. If I close the lid I'm *fully aware* that it is going to be suspend. I in fact *expect* it to suspend. But it messes up my terminals when I get back.

**Comment by hl037** [comment] 2022-05-26 12:46
I think it's intended for servers or nfs to advise users of a shared system that it is going down, but they forgot to provide a mean of configuration...

**Comment by arthurflor23** [comment] 2022-05-26 12:57
+1 on arch (so annoying)

**Comment by ffernand** [comment] 2022-05-26 13:08
Also on Arch & some have suggested adding `mesg n` to bash profile.  But it's a no-go for me. Even with `mesg n`, whether on shutdown or sleep, all open terminals are spammed with broadcast messages.

**Comment by ItIsUday** [comment] 2022-05-26 16:38
I believe it's because of this commit https://github.com/systemd/systemd/commit/cdf370626f08ed509a5dde9d5618eed29d625032

**Comment by AdrianusWest** [comment] 2022-05-26 16:52
> I believe it's because of this commit [cdf3706](https://github.com/systemd/systemd/commit/cdf370626f08ed509a5dde9d5618eed29d625032)


I don't think. When disabled, the messages remain.

**Comment by pivonroll** [comment] 2022-05-26 17:48
I can confirm that messages remain even when:
1. I set `FarwardToWall=no` in **journald.conf** at **/etc/systemd**.
    I did reload journald service with `systemctl restart systemd-journald.service`. 
2. Use `mesg n` in terminal
In case 1 I've even rebooted my machine and messages still remain.

**Comment by pieniacy** [comment] 2022-05-26 18:31
+1 on arch

**Comment by mbiebl** [comment] 2022-05-26 19:40
No +1's please. This just creates unnecessary noise for everyone.

@keszybz already acknowledged the issue at https://www.spinics.net/lists/fedora-devel/msg300564.html

What it needs now is a fix/PR, no further me-toos.

**Comment by e7p** [comment] 2022-05-27 10:25
Could one provide a hotfix solution or would it be required to downgrade to v250 in the meantime in case these wall messages are not desired?

**Comment by BSerpent86** [comment] 2022-05-28 08:17
even on shutdown and reboot the message is annoying because it makes the internal speakers beep unnecessarily.

**Comment by keszybz** [comment] 2022-05-28 09:02
What does `utmpdump </var/run/utmp` say? Do you have your local sessions in a terminal emulator listed there?

**Comment by rra** [comment] 2022-05-28 15:51
Yes. For example:
```
Utmp dump of /dev/stdin
[2] [00000] [~~  ] [reboot  ] [~           ] [5.17.0-3-amd64      ] [0.0.0.0        ] [2022-05-28T15:10:02,426829+00:00]
[1] [00053] [~~  ] [runlevel] [~           ] [5.17.0-3-amd64      ] [0.0.0.0        ] [2022-05-28T15:10:11,669420+00:00]
[6] [00756] [tty1] [LOGIN   ] [tty1        ] [                    ] [0.0.0.0        ] [2022-05-28T15:10:16,355700+00:00]
[7] [01088] [:0  ] [eagle   ] [tty7        ] [:0                  ] [0.0.0.0        ] [2022-05-28T15:10:25,342099+00:00]
[7] [01297] [ts/1] [eagle   ] [pts/1       ] [:0                  ] [0.0.0.0        ] [2022-05-28T15:10:26,294377+00:00]
[7] [01296] [ts/0] [eagle   ] [pts/0       ] [:0                  ] [0.0.0.0        ] [2022-05-28T15:10:26,294398+00:00]
[7] [01295] [ts/5] [eagle   ] [pts/5       ] [:0                  ] [0.0.0.0        ] [2022-05-28T15:10:26,342810+00:00]
[7] [01301] [ts/3] [eagle   ] [pts/3       ] [:0                  ] [0.0.0.0        ] [2022-05-28T15:10:26,366797+00:00]
[7] [01300] [ts/2] [eagle   ] [pts/2       ] [:0                  ] [0.0.0.0        ] [2022-05-28T15:10:26,388168+00:00]
[7] [01304] [ts/7] [eagle   ] [pts/7       ] [:0                  ] [0.0.0.0        ] [2022-05-28T15:10:26,395137+00:00]
[7] [01299] [ts/6] [eagle   ] [pts/6       ] [:0                  ] [0.0.0.0        ] [2022-05-28T15:10:26,419345+00:00]
[7] [01305] [ts/8] [eagle   ] [pts/8       ] [:0                  ] [0.0.0.0        ] [2022-05-28T15:10:26,450160+00:00]
[7] [01303] [ts/9] [eagle   ] [pts/9       ] [:0                  ] [0.0.0.0        ] [2022-05-28T15:10:26,452623+00:00]
[7] [01307] [s/10] [eagle   ] [pts/10      ] [:0                  ] [0.0.0.0        ] [2022-05-28T15:10:26,456117+00:00]
[7] [01298] [ts/4] [eagle   ] [pts/4       ] [:0                  ] [0.0.0.0        ] [2022-05-28T15:10:26,460725+00:00]
```

**Comment by rra** [comment] 2022-05-28 15:53
Reading the linked PR, I am suspicious that this may depend on what terminal emulator one uses. I'm quite old-school about terminal emulators and use `xterm` (for a bunch of reasons that I won't get into). Maybe some terminal emulators update `/var/run/utmp` and some do not?

**Comment by cgzones** [comment] 2022-05-28 16:19
Maybe its dependent whether one uses [libutempter](https://github.com/altlinux/libutempter)?

**Comment by VorpalBlade** [comment] 2022-05-28 17:30
> What does utmpdump </var/run/utmp say? Do you have your local sessions in a terminal emulator listed there?

Not in my case, all I see is the X11 logins, ssh logins and reboot records. The kitty terminal emulators do not show up there. Even when I launch other terminal emulators (xterm, konsole) it doesn't happen. Arch Linux with KDE, using zsh for the shell. libutempter is installed by the way. So it is not as easy as just xterm doing this always.

**Comment by mrc0mmand** [comment] 2022-05-28 19:30
> Maybe its dependent whether one uses [libutempter](https://github.com/altlinux/libutempter)?

This looks like the possible root cause. I couldn't reproduce the issue with the default (and latest) Fedora Rawhide, but with `xterm` or `mrxvt` (which use libutempter) I see:

```
[2] [00000] [~~  ] [reboot  ] [~           ] [5.14.0-0.rc2.20210723git8baef6386baa.26.fc35.x86_64] [0.0.0.0        ] [2022-05-28T19:21:52,359918+00:00]
[1] [00053] [~~  ] [runlevel] [~           ] [5.14.0-0.rc2.20210723git8baef6386baa.26.fc35.x86_64] [0.0.0.0        ] [2022-05-28T19:22:00,359805+00:00]
[6] [01228] [tyS0] [LOGIN   ] [ttyS0       ] [                    ] [0.0.0.0        ] [2022-05-28T19:22:00,397598+00:00]
[7] [01289] [    ] [vagrant ] [tty2        ] [tty2                ] [0.0.0.0        ] [2022-05-28T19:22:07,550653+00:00]
[7] [02618] [ts/1] [vagrant ] [pts/1       ] [:0                  ] [0.0.0.0        ] [2022-05-28T19:23:38,764897+00:00]
[7] [02835] [ts/2] [vagrant ] [pts/2       ] [:0                  ] [0.0.0.0        ] [2022-05-28T19:24:05,028316+00:00]
[7] [02878] [ts/3] [vagrant ] [pts/3       ] [:0                  ] [0.0.0.0        ] [2022-05-28T19:24:07,570787+00:00]
[7] [02916] [ts/4] [vagrant ] [pts/4       ] [:0                  ] [0.0.0.0        ] [2022-05-28T19:24:09,287961+00:00]
[7] [02961] [ts/5] [vagrant ] [pts/5       ] [:0                  ] [0.0.0.0        ] [2022-05-28T19:24:10,963773+00:00]
```

**Comment by brunnre8** [comment] 2022-05-30 06:45
tmux seems to register the ptys for each pane on var/run/utmp as well

**Comment by firew4lker** [comment] 2022-05-30 08:15
I don;t know if it is relative. In my system (Archlinux) with 251.1 there is a loud beep each time my system restarts, shuts down or goes to sleep.

**Comment by dvalter** [comment] 2022-05-30 10:35
> > I believe it's because of this commit [cdf3706](https://github.com/systemd/systemd/commit/cdf370626f08ed509a5dde9d5618eed29d625032)
> 
> I don't think. When disabled, the messages remain.

Then I believe 90b1ec0 caused this since reverting both cdf3706 and the following part of 90b1ec0 removes messages at least for suspend.
```diff
diff --git a/src/login/logind-utmp.c b/src/login/logind-utmp.c
index 5533836473..d2b2f8b193 100644
--- a/src/login/logind-utmp.c
+++ b/src/login/logind-utmp.c
@@ -135,11 +135,11 @@ int manager_setup_wall_message_timer(Manager *m) {
                 return 0;
         }
 
-        if (elapse < n)
+        if (elapse > 0 && elapse < n)
                 return 0;
 
         /* Warn immediately if less than 15 minutes are left */
-        if (elapse - n < 15 * USEC_PER_MINUTE) {
+        if (elapse == 0 || elapse - n < 15 * USEC_PER_MINUTE) {
                 r = warn_wall(m, n);
                 if (r == 0)
                         return 0;
```

**Comment by lnussel** [comment] 2022-05-30 15:39
The following should work to disable the messages for tools that just call the dbus methods for suspend/reboot etc without changing the wall message state themselves. It's runtime only until next reboot.

     # busctl set-property org.freedesktop.login1 /org/freedesktop/login1 org.freedesktop.login1.Manager EnableWallMessages b false

**Comment by kparal** [comment] 2022-10-03 07:13
As mentioned in https://bugzilla.redhat.com/show_bug.cgi?id=2129387#c5 , systemd still causes systems to emit a pc speaker beep during reboot/poweroff, but only after a suspend&resume cycle. The fix that applies after a clean boot doesn't persist after suspend&resume and the beeps are unfortunately restored.

**Comment by mbiebl** [comment] 2022-10-05 18:15
fwiw, after I unmuted "Beep" via alsamixer, I now also get the beeps on suspend as well as reboot.

**Comment by d4vid1** [comment] 2022-10-08 20:51
Hi @ all,

Archlinux and other archlinux based distro users can use downgrade tool from AUR ( yay -S downgrade ; sudo downgrade systemd )  to downgrade last version of systemd from 251 to 250, that solution works for me, shutdown or reboot show me 60 Seconds on window again.

**Closed as completed** 2022-10-11 19:43 UTC
Labels: login, sleep
