### ISSUE TITLE
High cardinality with timers for socket-activated units

### ISSUE THREAD

**Issue by amarao** [systemd/systemd#29103] opened 2023-09-06 12:12 UTC
### systemd version the issue has been seen with

252

### Used distribution

Ubuntu 23.04

### Linux kernel version used

6.2.0-26-generic

### CPU architectures issue was seen on

None

### Component

systemd

### Unexpected behaviour you saw

When unit is socket-activated it get timestamp added as a parameter to a template. If this unit is activated often (by timer, or by ingress connections) it creates high cardinality problem.

E.g. https://bugs.launchpad.net/openstack-ansible/+bug/2030748

A healthcheck is run by timer, which in turn connects to a socket, which activates a unit. In a few weeks cardinality of unit name become so high that 

```
time journalctl -F UNIT|wc -l
311751

real 1m6.551s
user 0m11.799s
sys 0m51.035s
```

And it become worse with every week.

Systemd unit example:

```
[Unit]
Description=mariadbcheck socket

[Socket]

ListenStream=10.26.90.68:9200
Accept=yes
FreeBind=true

[Install]
WantedBy=sockets.target
```

And every time healthcheck is run:

```
Sep 06 12:11:13 infra1 systemd[1]: Starting mariadbcheck@ service (10.26.94.140:37276)...
Sep 06 12:11:13 infra1 systemd[1]: mariadbcheck@147486-10.26.90.68:9200-10.26.90.68:51526.service: Succeeded.
```

(there is a new name for the unit)

### Steps to reproduce the problem

1. Create a socket-activated unit
2. Add a timer to activate it every 10s
3. Wait for few days.
4. Run `time journalctl -F UNIT|wc -l` and observe time for execution goes up each day.

**Comment by xiacunshun** [comment] 2023-09-06 17:30
It seems that the template unit spawns all these instances, which is what template units should do. Template unit got different connection IPs and used them to create instance units.
`time journalctl -F UNIT|wc -l` bumps because many connection instance units are created.

**Comment by amarao** [comment] 2023-09-07 09:23
Yes, the main problem is that timestamp is added to the unit name durning templatization. If there was no timestamp, the pool of possible names will be limited and bounded (and reused), but with timestamp in the name cardinality become unbounded with time `cardinality = Ω(t)`.

**Comment by poettering** [comment] 2023-09-07 09:36
Hmm, I am not sure what the problem here is? yeah, we generate a distinct unit name for each connection. Which is intended.

**Comment by amarao** [comment] 2023-09-07 12:16
If there are a lot of connection (e.g. healthcheck run) journald and other logging tools become overloaded with high cardinality of label values. May be it's possible to remove timestamp from the unit name during template instantiation (which will change the way socket units are activated, I understand).

It's really sad to see system tool having performance regression based on system uptime.

**Comment by poettering** [comment] 2023-09-07 12:42
hmm? as a system runs more log messages are generated anyway, why are you concerned about unit names?

i don#t grok what you are trying to say..

**Comment by amarao** [comment] 2023-09-08 09:19
As I said, it's label cardinality, not the amount of logs. It affects journald (journalctl -F UNIT), and it really badly affects any external monitoring system recieving logs.

Prometheus:  metrics are exported by node-exporter, with systemd unit status. Unit name is a label value == high cardinality.

Loki: unit name is a label value for log entry, the same problem: very high cardinality.

Any other structured logging system (journald including!) is affected.

Worse, it's not just high cardinality, it's a cardinality depending on time, that means it become worse and worse with every week. Systems with large retention time are doomed (or require unreasonable amount of resources).

Cardinality is a sum (or product, depending on the used database) of all values of all labels used for indexes.

There are workarounds proposed around this problem:

1. Exclude socket-activated units from scraping (--collector.systemd.unit-exclude). This removes unit metrics entirely.
2. Reduce label to template name during relabeling process

The second option is more reasonable, but what it's doing: removing unique part of the unit name, which systemd creates. May be we can avoid two robots fighting each other (one generate uniqueness, and second removes it) and find a way to avoid unbounded cardinality for socket units?

**Comment by poettering** [comment] 2023-09-08 10:04
i have no idea what "label cardinality" is even supposed to mean.

journalctl -F for any field type is going to be slower if you have more entries, that should be obvious no? journalctl -F MESSAGE grows with each log message, that's expected and not surprising. it's inherent to the fact that we index by every field we pick up.

journal rotation should put a boundary on the amound of logs you record, and that also means the amount of units, messages, dates, invocation ids, and so on, is capped.

**Comment by amarao** [comment] 2023-09-08 14:21
My apology, I thought that journald uses indexes. If it's not, than it just uses a linear scan, and journald is excluded from affected applications.

Label cardinality is a problem, which many logging systems with indexes experience: that a total number of all unique values for indexed fields (like labels, or field names). If this number is too large, logging systems become sluggish and consume lot of memory during mundane requests.

Therefore, large number of unique unit names (unit name is usually a value for label 'service' or 'unit' for logging and metrics) is problematic and I thought to report this problem. A statically configured server is expected to have a bounded number of unique label values, and it suddenly become unbounded, if there is moderately active systemd.socket in the system.

**Comment by poettering** [comment] 2023-09-08 15:04
> My apology, I thought that journald uses indexes. If it's not, than it just uses a linear scan, and journald is excluded from affected applications.

it uses a index. but "journalctl -F" of course dumps you a huge list...

**Comment by amarao** [comment] 2023-09-15 14:03
If it uses index, than it's affected by cardinality problem. For a given system the list of units is expected to be constant (bound by constant in relation with time). socket-activated units breaks that assumption causing unbounded number of unit names in the index.

Excluding timestamp from a unit list when running a socket (with opt-in option, I suppose, to keep it compatible) will allow to reuse unit name and will keep cardinality bounded.

**Comment by poettering** [comment] 2023-10-30 23:08
We index by all fields btw, not just the unit name, i.e. sequence numbers, times, the messag text and stuff. 

Generally, if you dump all possible values of a fields then you get all possible values. No wonder. It's what you asked for. 

An index speeds up lookup if you actually have a key to lookup. And if you don't then you shouldn't be surprised to get a huge list.

Or in other words: if you don't want a huge list of things written to stdout, then don't use journalctl -F on fields that can take myriads of values, such as UNIT? If you do, then it's your own fault.

Anyway, I really don't grok what the problem is here.

**Comment by poettering** [comment] 2023-10-30 23:10
If some software assumes that the set of values UNIT= can take was "small" and "fixed", that software is simply broken and should be fixed. Because it's simply not the case. the name of units is to some level under attacker control even, and that's entirely OK and expected.

Anyway, I think we really should close this, as I see no problem here, the behaviour is expected.

**Comment by mrc0mmand** [comment] 2023-10-31 10:30
To add to this: it's not just socket activated units that increase number of unique UNIT field values - systemd-run generates a (pseudo) random unit name as well, unless `--unit=` is specified, e.g.:

```
$ journalctl -b --grep man-db-cache-update -o short-monotonic --no-hostname
[14924.653545] systemd[1]: Started run-ra322a40c307240b5b8150821ebd6902d.service - /usr/bin/systemctl start man-db-cache-update.
[14924.667344] systemd[1]: Starting man-db-cache-update.service...
...
[182463.555355] systemd[1]: Started run-rd54ec25fd8694357b5863f38dbe8499f.service - /usr/bin/systemctl start man-db-cache-update.
[182463.566681] systemd[1]: Starting man-db-cache-update.service...
```

So the assumption that the unit list is supposed to be constant is simply broken. Also, I wouldn't say that the cardinality is unbounded either, since that is handed by journal rotation, i.e. the cardinality is bounded by storage available for the journal.

**Closed as completed** 2023-11-08 10:42 UTC
Labels: pid1
