### ISSUE TITLE
systemctl start - option to set environment variables for the service

### ISSUE THREAD

**Issue by ibukanov** [systemd/systemd#9370] opened 2018-06-21 07:47 UTC
**Is your feature request related to a problem? Please describe.**

I would like to see an option for `systemctl start` that allows to add/overwrite environment variables that are passed to the Exec* commands of the service that is started. This is very usable when starting the units for debugging or during development. 

**Describe the solution you'd like**

`systemctl start` can be extended with an option like `--env name=value` to set the environment variable that is passed to the service exec commands. For example, to debug an issue with opensshd service, I can start it like:

systemctl start --env OPTIONS='-d -d -d' sshd 

that starts sshd in a verbose debug mode. Another example is debugging/development of an oneshot  service to activate a debug mode for the service with extra logs or checks.

**Describe alternatives you've considered**

Currently to implement this I have a shell script wrapper for `systemctl start`. The wrapper essentially creates if necessary a drop-in for the service at /run/systemd/system with `EnvironmentFile=-/run/start_env.service_name` calling `systemctl daemon-reload` the first time the drop-in is created. Then the wrapper writes passed environment variables into the file, calls `systemctl start` and then removes the file. It would be nice to avoid such complexity just to add a single environment to pass to the commands of the service.

**Comment by poettering** [comment] 2018-06-22 11:36
Well, I am not convinced this is really necessary. I mean, first of all semantically this is problematic as systemd potentially coalesces start requests for specific units coming from multiple sources in a single run queue, and will spawn a service only once for that. If we'd allow start requests to carry additional settings for the service (such as an env assignment) then coalescing becomes complex, as the settings attached to these requests would have to be merged in some way, and as there is no obvious priority concept in place which could say which side wins on conflicting settings.

moreover, this would make things a bit less reproducible, as starting a service wouldn't be same as starting a service at a different time anymore.

I am not sure I grok why you use EnvironmentFile= though. It should be sufficient to just drop-in snippets like this with `systemctl edit --runtime`:

```
[Service]
Environment=FOO=BAR
```

And that's all.

Is there any real reason why `systemctl edit --runtime` isn't enough to solve the issue at hand in a more powerful and generic fashion?

**Comment by ibukanov** [comment] 2018-06-23 21:10
I though this could be implemented in a way that was very similar to EnvironmentFile that was parsed not when the systemd configuration was read but rather each time before systemd executed any of Exec commands. And due to this coalescing of start requests is already indeterministic as each invocation of the service can see different values of the environment.

As for the reason to use EnvironmentFile= in the wrapper script, it is because the environment from it takes precedence over Environment=. For example, in my config `Environment=OPTIONS=-d` in a drop-in for sshd service is no-op as OPTIONS is set in /etc/sysconfig/sshd that sshd.service reads via EnvironmentFile. So my wrapper script creates a drop-in like zzz-temp-env where zzz ensures that the file has the final word in setting the environment. 

Besides, with EnvironmentFile= the drop-in can remove the file with the custom environment without calling daemon-reload via adding `ExecStartPost=/bin/rm -f path_to_environment_file` ensuring the removal of the file whenever the service starts successfully.

**Comment by AlfiCode** [comment] 2019-08-01 05:56
I like your idea, because all that environment stuff is not direct usable in the unit-file, only in the environment of the called ExecStart-function. If you have to work e.g. with absolute paths it's not  nice to retype them.  The "systemctl" is not extracting ${xxx}.
So if I could call systemctl commands and give it my environment staff or at least use flexible variables it would help a lot.
Or did you find already a solution?

**Comment by AlfiCode** [comment] 2019-08-01 06:55
Even "man5/systemd.service.5.html" says:
Basic environment variable substitution is supported.
It's not the full truth.

WORKS:
Environment="ONE=one" 'TWO=two two'
ExecStart=/etc/test/mycmd $ONE $TWO ${TWO}

DOESN'T WORK:
Environment="ONE=one" 'TWO=two two'
Environment="mypath=/etc/test"
ExecStart=${mypath}/mycmd $ONE $TWO ${TWO}

Basic environment variable substitution is supported foor command arguments but not for ExecStart itself (e.g. path to command with ${mypath} fails)!

This should be improved!

**Comment by vigneshraman** [comment] 2019-12-13 12:36
> I am not sure I grok why you use EnvironmentFile= though. It should be sufficient to just drop-in snippets like this with `systemctl edit --runtime`:
> 
> ```
> [Service]
> Environment=FOO=BAR
> ```
> 
> And that's all.

@poettering Do we need to restart the service after we run `systemctl edit --runtime` and update the environment variable? Thanks.

**Comment by poettering** [comment] 2019-12-13 12:43
@vigneshraman this is not a support forum. → mailing list.

**Comment by keszybz** [comment] 2019-12-13 15:45
I have to agree with @poettering: dropins are a sufficient mechanism to achieve the desired result, with clearly defined semantics. They are also more flexible, because they allow not just setting some environment variables, but also overriding the command line or other unit settings. The proposed use case doesn't seem strong enough to add new functionality.

(That said, I think we should provide a way to define runtime dropins more conveniently: something like `systemctl edit foo.service --section=Service Environment=FOO=BAR --section=Unit `Description=override description'`. But that's orthogonal to this issue.)

**Closed as completed by keszybz** 2019-12-13 15:45 UTC
Labels: RFE 🎁, needs-discussion 🤔, pid1
