### ISSUE TITLE
systemd-networkd fails to bring up ethernet interface on boot after update

### ISSUE THREAD

**Issue by Gooberpatrol66** [systemd/systemd#20759] opened 2021-09-15 23:30 UTC
**systemd version the issue has been seen with**
 > 249.2

**Used distribution**
 > Gentoo

**Linux kernel version used** (`uname -a`)

 > `Linux gentoodesktop 5.10.61-gentoo-x86_64 #1 SMP PREEMPT Sat Sep 11 17:22:22 UTC 2021 x86_64 AMD Ryzen 5 3600 6-Core Processor AuthenticAMD GNU/Linux`

**CPU architecture issue was seen on**
 > x86-64

**Expected behaviour you didn't see**
 > enp7s0 is brought up automatically

**Unexpected behaviour you saw**
 > must run "ifconfig enp7s0 up" and "systemctl restart systemd-networkd" to get networking

**Steps to reproduce the problem**
 > reboot the machine

**Additional program output to the terminal or log subsystem illustrating the issue**

```
journalctl -xeu systemd-networkd
-- Boot 12e2dee88f6d48449844dc7c683a5163 --
Sep 15 23:03:59 gentoodesktop systemd-networkd[1526]: lo: Link UP
Sep 15 23:03:59 gentoodesktop systemd-networkd[1526]: lo: Gained carrier
Sep 15 23:03:59 gentoodesktop systemd-networkd[1526]: Enumeration completed
Sep 15 23:03:59 gentoodesktop systemd[1]: Started Network Configuration.
░░ Subject: A start job for unit systemd-networkd.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://gentoo.org/support/
░░ 
░░ A start job for unit systemd-networkd.service has finished successfully.
░░ 
░░ The job identifier is 109.
Sep 15 23:03:59 gentoodesktop systemd-networkd[1526]: eth0: Interface name change detected, renamed to enp7s0.

dmesg | grep eth0
[    1.159881] igb 0000:07:00.0: added PHC on eth0
[    1.159883] igb 0000:07:00.0: eth0: (PCIe:2.5Gb/s:Width x1) 70:85:c2:d7:65:f3
[    1.159884] igb 0000:07:00.0: eth0: PBA No: FFFFFF-0FF
[    2.840546] igb 0000:07:00.0 enp7s0: renamed from eth0

dmesg | grep enp7s0
[    2.840546] igb 0000:07:00.0 enp7s0: renamed from eth0
[  172.445407] igb 0000:07:00.0 enp7s0: igb: enp7s0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
[  172.553098] IPv6: ADDRCONF(NETDEV_CHANGE): enp7s0: link becomes ready

```

**Comment by yuwata** [comment] 2021-09-15 23:38
Duplicate of #20657. Already fixed by 160203e974945ce520fe8f569458634ef898c61c (#20696).

**Closed as completed by yuwata** 2021-09-15 23:38 UTC
Labels: network, already-fixed
