### ISSUE TITLE
bind entries in fstab are made recursive regardless of options

### ISSUE THREAD

**Issue by pgreening** [systemd/systemd#1204] opened 2015-09-08 20:24 UTC
So, to facilitate backups, all of my machines have the root file system mounted as a bind mount at /buroot. This eliminates recursion into other file systems, and prevents backing up things like /dev.  Specifically submounts are not exported. This is confirmed by the mount(8) man page:
              The bind mount call attaches only (part of) a single filesystem, not possible submounts.   The  entire  file  hierarchy  including  submounts  is
              attached a second place by using:

```
                 mount --rbind olddir newdir
```

However the following entry in my fstab:
/                               /buroot         auto    bind            0 4
results in recursive bind mounts being generated:
root@castor:~# mount |grep /buroot
/dev/mapper/castor-root on /buroot type ext4 (rw,relatime,errors=remount-ro,data=ordered)
tmpfs on /buroot/tmp type tmpfs (rw,relatime)
/dev/mapper/castor-var on /buroot/var type ext4 (rw,relatime,data=ordered)
/dev/mapper/castor-vbox--testing on /buroot/export/vbox-testing type ext4 (rw,relatime,data=ordered)
/etc/chmadre.map on /buroot/net type autofs (rw,relatime,fd=6,pgrp=2832,timeout=300,minproto=5,maxproto=5,indirect)
it even reproduces autofs maps!

This is directly contradictory to the documented behavior for bind mounts.  I don't know why this is happening. It may be due to:
- systemd attempting to use parallelism when performing the mounts.
- systemd enabled mount propagation by default for all bind mounts.
- something else, I'm really just guessing here.

Can this somehow please be fixed so that bind mounts do not inherit submounts by default?

**Comment by poettering** [comment] 2015-09-09 06:14
We just invoke util-linux' mount command for bind mounts, as for any other mounts. @karelzak this is for you I think.

Closing this here.

**Closed as completed by poettering** 2015-09-09 06:14 UTC
Labels: not-our-bug

**Comment by pgreening** [comment] 2015-09-09 15:37
No, i don't think that you can really say this is not your bug. I have removed systemd, replacing it with sysV init (removed debian packages systemd-sysv libpam-systemd systemd systemd-ui, installed sysvinit-core, and the problem vanished.  This is clearly a bug in systemd, not the mount command.

**Comment by johannbg** [comment] 2015-09-09 15:45
@pgreening comparing systemd with any other init system and their behaviour out there is like comparing apple and oranges so adjust your expectation in accordance with systemd being entirely "new" not just init but core/base solution. 

That said @karelzak will not hesitate to throw this back here ( or just comment here directly ) if its not relevant to util-linux

**Comment by pgreening** [comment] 2015-09-09 16:02
@johannbg
The expected behavior of bind mounts in /etc/fstab is to not include submounts. This is clearly documented in the mount man page. I've spent days searching the systemd documentation and have found no references to bind mounts being treated in any other way in the official documentation. I have found several posts about the problem, indicating that it may be based on one of several details regarding how systemd is managing the system, however lack of supporting documentation implies that the behavior which systemd itself is expecting is not actually occuring.  I've taken the liberty of comparing this to a traditional system V system because I assume that unless otherwise documented, systemd behavior should mimic system V in regards of things like fstab.  

Unless systemd explicitly documents different handling of bind mounts in fstab, any behavior other than the expected behavior must be considered a bug.  Anything else is just systemd failing to boot the system properly, one of it's fundamental responsibilities.

**Comment by pgreening** [comment] 2015-09-09 16:57
update:
I have compared centos 5 and centos 7. Centos5, using sysV produces the expected non-recursive bind mounts when the bind option is used and recursive bind mounts when rbind is used. Centos 7 mirrors Debian Jessie's behavior of creating recursive bind mounts regardless of whether the bind or rbind mount option is used.

**Comment by karelzak** [comment] 2015-10-02 00:43
I'm not able to reproduce this problem:

 # echo "/ /mnt/test auto bind 0 4" >> /etc/fstab
 # mount /mnt/test

 # findmnt --submounts /mnt/test
 TARGET    SOURCE    FSTYPE OPTIONS
 /mnt/test /dev/sda4 ext4   rw,relatime,data=ordered

 # rpm -q util-linux systemd
 util-linux-2.27-1.fc24.x86_64
 systemd-219-24.fc22.x86_64

Note that if you're not sure then use strace to see mount flags:

 # strace -e mount mount /mnt/test
 mount("/", "/mnt/test", 0x55e4b2090a60, MS_MGC_VAL|MS_BIND, NULL) = 0
 +++ exited with 0 +++

MS_REC (aka recursive) is not use in this case.

**Comment by pgreening** [comment] 2015-10-07 19:03
please try rebooting with the fstab entries in place. I believe this 
only occurs when they're mounted during boot up.

I have eliminated this problem by removing the fstab entries and placing 
the following commands in /etc/rc.local:
mount --make-private /
mount -o bind / /buroot
mount --make-private /buroot

**Comment by eludias** [comment] 2015-11-29 20:45
Finally the answer to my failed backups!

I've upgraded my Debian to a systemd-based version, and from that point on the backups failed, which I traced back to the bind mounts being recursive ('mount --rbind' instead of 'mount --bind'?).

The strange thing is that mounts in /etc/fstab are _only_ mounted recursively during boot up, but not when explicitly mounted with the 'mount' command. 

Workaround (comparable to previous poster): add the 'noauto' to fstab, and mount it explicitly in /etc/rc.local (without any options). This way at least the options can still be kept in /etc/fstab .

**Comment by dfries** [comment] 2016-05-07 19:34
I also do a bind for backup, it is unexpected for this to be recursive.  This is the solution I'm using, add private to the mount flags in /etc/fstab and even on boot it behaves now.

```
# private, don't propagate mounts in or out see mount(8)
/       /var/backups/root none    bind,private    0       0
```

**Comment by hanyong** [comment] 2020-06-07 07:29
I have encountered the strange (bug) behavior of systemd too, spent a few hours to try to workaround. 

Thanks @dfries , add a "private" flag saved me.

**Comment by kilobyte** [comment] 2021-11-06 19:53
The bug is not in any implementation of `mount`, it's in behaviour of systemd afterwards.  If it sees the mount appear, it then adds the children of the original about a second later.

**Comment by kilobyte** [comment] 2021-11-06 20:03
Probably related: if you mount manually with `-o degraded`, systemd will then, about a second later, unmount the filesystem you mounted; this can be prevented by doing `mount …; cd /mountpoint` — if you win the race, you can continue using that filesystem.

I don't know systemd's inner workings, but both behaviours suggest that systemd keeps watching mount points, and has trouble interpreting their state correctly.  In this bug report, it mistakes the `--bind` mount for the original, and in the problem I mentioned in this comment, it believes the degraded mount couldn't possibly happen as not all devices are present (that's why it's degraded...), and tries to amend the situation by unmounting, which is patently wrong.
