### ISSUE TITLE
Feature request: systemctl option to schedule action using transient timer unit

### ISSUE THREAD

**Issue by schuelermine** [systemd/systemd#33268] opened 2024-06-10 21:33 UTC
### Component

systemctl

### Describe the solution you'd like

Add two flags, `--schedule-in-seconds` and `--schedule-on-calendar`, to `systemctl`, that act as follows:
- `systemctl --schedule-in-seconds=… …` acts as `systemd-run --on-active=… systemctl …`
- `systemctl --schedule-on-calendar=… …` acts as `systemd-run --on-calendar=… systemctl …`

For instance, `systemctl stop --schedule-on-calendar=tomorrow stop bluetooth.service` would act like `systemd-run --on-calendar=tomorrow systemctl stop bluetooth.service` and would stop Bluetooth at midnight.

### Describe alternatives you've considered

The `--when` option could be used for this, extending it to cover other actions.

### The systemd version you checked that didn't have the feature you are asking for

255.6

**Comment by dtardon** [comment] 2024-06-11 05:41
A duplicate of #8138.

**Closed as duplicate by dtardon** 2024-06-11 05:41 UTC
Labels: RFE 🎁, systemctl, duplicate
