### ISSUE TITLE
After starting a container running systemd while under X, ^C anywhere terminates the X server.

### ISSUE THREAD

**Issue by 057a3dd61f99517a3afea0051a49cb27994f94d** [systemd/systemd#17227] opened 2020-10-01 16:08 UTC
**systemd version the issue has been seen with**
> systemd 245 (245)
> -PAM -AUDIT -SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS -ACL +XZ -LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN +PCRE2 default-hierarchy=unified

**Used distribution**
Custom.

**Unexpected behaviour you saw**
After starting a container running systemd when you're under X, type `^C` anywhere and the X server is terminated.

**Steps to reproduce the problem**
1. Make sure the kernel is ran without the `console=` option, or `console=tty0` is given, so that `/dev/console` refers to the foreground virtual console.
2. Start the X server, using `ps --format pgid,tpgid,tty -C X` you should see the X server is in the foreground process group of its controlling terminal.
3. Suppose the controlling terminal of X is tty3, `stty --file=/dev/tty3 --all` would output something like:
> speed 38400 baud; rows 24; columns 64; line = 0;
> intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
> eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z;
> rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
> -parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
> ignbrk -brkint ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl -ixon
> -ixoff -iuclc -ixany -imaxbel -iutf8
> -opost -olcuc -ocrnl -onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0
> vt0 ff0
> -isig -icanon -iexten -echo -echoe -echok -echonl -noflsh -xcase -tostop
> -echoprt -echoctl -echoke -flusho -extproc
4. While you're under X, start a container running systemd by unsharing pid and mount namespaces, changing root and then `exec /sbin/init`, there's no mountpoint except `/` at this point, `/dev` starts out empty, a `devtmpfs` is mounted `rw` there by systemd later.
5. Run `stty --file=/dev/tty3 --all` again, you should see something like:
> speed 38400 baud; rows 24; columns 64; line = 0;
> intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;
> eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z;
> rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
> -parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
> -ignbrk -brkint ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl -ixon
> -ixoff -iuclc -ixany imaxbel iutf8
> -opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0
> vt0 ff0
> isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop
> echoprt echoctl echoke -flusho -extproc

The terminal characteristics of `/dev/console` and thus `/dev/tty0` and `/dev/tty3`, the controlling terminal of the X server is changed by systemd so that the `ISIG` flag is turned on.
6. Type `^C` anywhere while under X, a `SIGINT` signal is sent to the X server and it's terminated.

**Comment by poettering** [comment] 2020-10-01 17:42
"start a container"? with nspawn? or what? does that container mgr you are using properly give up the controlling tty and all fds and stuff?

Why is this a systemd bug? sounds like your container manager is hosed?

**Comment by 057a3dd61f99517a3afea0051a49cb27994f94d** [comment] 2020-10-01 20:04
On Thu, Oct 01, 2020 at 10:42:39AM -0700, Lennart Poettering wrote:
> "start a container"? with nspawn? or what? does that container mgr you are using properly give up the controlling tty and all fds and stuff?
> 
> Why is this a systemd bug? sounds like your container manager is hosed?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/systemd/systemd/issues/17227#issuecomment-702293043

I'm not using a container manager, simply starting a container with
unshare/mount these command line tools. The init process inherits
its stdin/stdout/stderr from the pseudoterminal device of a graphical
terminal emulator.

Since the kernel starts the init process with its stdin/stdout/stderr
connected to /dev/console, so that the init process don't have to do
this itself, however, in contrast systemd ignores its stdin/stdout/stderr
and insists on opening /dev/console itself, I find it a bit awkward.

**Comment by poettering** [comment] 2020-10-02 09:10
We close /dev/console because of kernel SAK behaviour: if we'd keep it open continously, and the user hits SAK PID 1 would die, which is typically not desirable, because it makes the system freeze.

That said, if you set the $container env var then we'll keep the fd open, and not reopen /dev/console all the time, as then we know we are in container mode where the SAK concept doesn't exist. See https://systemd.io/CONTAINER_INTERFACE.

Does your pseudo container mgr give up the controlling tty/open a new session/pgroup for your container PID1? if not, it's not surprising that that signals propagate from the container to the whole process group. It's how UNIX works. Not doing so is a bug in your tooling, and has nothing to do with systemd.

Anyway, let's close this, as this really looks like your container manager just doesn't disconnect things properly from the host, and doesn't implement the documented container manager expectations systemd makes. As such it's maybe something to discuss on the systemd ML, but this is not a bug report of feature request, hence shouldn't be tracked here, as we try to keep the noise level down. Hope that makes sense.

(Consider just using systemd-nspawn which implements all this correctly.)

**Closed as completed by poettering** 2020-10-02 09:10 UTC
Labels: needs-reporter-feedback ❓

**Comment by 057a3dd61f99517a3afea0051a49cb27994f94d** [comment] 2020-10-02 18:40
Okay, thanks for the info, I'll look into it later.
