### ISSUE TITLE
TEST-10-ISSUE-2467 fails in ubuntu CI

### ISSUE THREAD

**Issue by xnox** [systemd/systemd#11706] opened 2019-02-13 00:37 UTC
opening an issue that TEST-10-ISSUE-2467 fails on Ubuntu Bionic.

Will blacklist it in tests.

**Comment by evverx** [comment] 2019-02-13 06:23
As I said in https://github.com/systemd/systemd/pull/11591#issuecomment-462836819
> I manually launched an Ubuntu Bionic VM, installed socat there and made sure that the test fails with `TriggerLimitIntervalSec=0` in `test.socket` and passes without it

Could you be more specific about what it is that fails on Ubuntu Bionic?

**Comment by evverx** [comment] 2019-02-13 06:30
It would also be great if you could answer @mrc0mmand's question:
> Is there any update on what's going on with the Ubuntu CI's results, @xnox?

If Ubuntu CI isn't going to be fixed anytime soon, I'd rather turn it off altogether again.

**Comment by xnox** [comment] 2019-02-13 12:03
@evverx please stop turning off _all_ of CI, when it is trivial to blacklist individual failing tests.

**Comment by xnox** [comment] 2019-02-13 12:05
@evverx also, not the CI issue, but the upstream test case is failing.

Somehow it seems to me, that developers are rarely running upstream VM tests before submitting merge proposals. So this is generic degradation. Running unit tests alone, is not enough.

**Comment by evverx** [comment] 2019-02-13 12:16
> Somehow it seems to me, that developers are rarely running upstream VM tests before submitting merge proposals. So this is generic degradation. Running unit tests alone, is not enough.

@xnox I ran TEST-10-ISSUE-2467 on Ubuntu Bionic approximately 100 times before I merged https://github.com/systemd/systemd/pull/11591 so it's very unclear to me what exactly fails there.

> @evverx please stop turning off _all_ of CI, when it is trivial to blacklist individual failing tests.

I'm not talking about TEST-10-ISSUE-2467 or any other test for that matter. What I'm talking about is, as I already wrote in https://github.com/systemd/systemd/pull/11487#issuecomment-462596458,
Ubuntu CI can randomly fail. It can also randomly pass (which is worse, in a way :-). For example, in #11694, if you take a look at the logs, you'll see that "UPSTREAM_PULL_REQUEST=11423" and 11423 isn't exactly 11694. As far as I know @xnox is aware of that and, as I said in [#11686 (comment)](https://github.com/systemd/systemd/pull/11686#issuecomment-462194092), hopefully it will be fixed soon. Until then it's hard to tell what exactly Ubuntu CI tests and whether it passes or not.

**Comment by evverx** [comment] 2019-02-13 12:31
By the way, If you're ready to spend your time visiting every PR to make sure that Ubuntu CI really tests what it is supposed to test and report its status correctly like you did in https://github.com/systemd/systemd/pull/11705, then I of course have no problem with Ubuntu CI.

**Comment by evverx** [comment] 2019-02-13 16:24
Just to be clear, while I think that Ubuntu CI isn't helpful and waiting (unsuccessfully) for two weeks for feedback from it isn't exactly my idea of what CI is, there is nothing to be worry about because I'm not going to turn it off :-) At least currently it runs something and reports something back, which is different from what happened in https://github.com/systemd/systemd/pull/11531.

Regarding the test, could you reproduce the issue locally?

**Comment by evverx** [comment] 2019-03-16 15:13
Looks like https://github.com/systemd/systemd/issues/12010, which was opened yesterday, is a variation of this issue. I'll close this one because it's unlikely anyone is going to receive actionable feedback here.

**Closed as completed by evverx** 2019-03-16 15:13 UTC
Labels: needs-reporter-feedback ❓, ci
