### ISSUE TITLE
Per-Unit Journal Limits

### ISSUE THREAD

**Issue by zealws** [systemd/systemd#3045] opened 2016-04-15 22:43 UTC
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229
### Used distribution

> archlinux

It would be nice if there were a way to specify individual journal limits by service. For example, limiting a noisy or unimportant service's output without affecting other services.

Something like [journald.conf](https://www.freedesktop.org/software/systemd/man/journald.conf.html)'s `SystemMaxUse` but in the unit file for the service would be excellent, but I'm sure there are other ways of doing this.

**Comment by aog2000a** [comment] 2017-09-27 23:43
+1. It would be great to have the possibility to define **log-levels** per Unit, say unit A log up to debug, unit B logs only warnings.
A per unit value MaxLevelStore value so to say. These two settings (maxuse and maxlevel) would perfectly complement each other to control the logging of single units.

**Comment by gleventhal** [comment] 2018-09-04 20:16
This would be great, I would love to skip the journal for transient units, especially because systemd-run is the way to work around certain other limitations (like scope units getting SIGHUP on shutdown), so it would be nice to not pollute the journal with every single systemd-run event.

**Comment by poettering** [comment] 2018-10-02 09:12
Let's close this as duplicate of the more generic #10230, even though the latter is newer. Hope that's OK.

**Closed as completed by poettering** 2018-10-02 09:12 UTC
Labels: RFE 🎁, journal, duplicate
