### ISSUE TITLE
`--user disable` is not properly persisted

### ISSUE THREAD

**Issue by ossilator** [systemd/systemd#27601] opened 2023-05-10 09:44 UTC
### systemd version the issue has been seen with

252.6

### Used distribution

debian sid

### Linux kernel version used

6.4.0-rc1+

### CPU architectures issue was seen on

x86_64

### Component

systemctl

### Expected behaviour you didn't see

`systemctl --user disable <unit>` should disable the unit even if it is enabled by default.

### Unexpected behaviour you saw

the unit remains enabled.

the effect is somewhat unsurprising, given that ~/.config/systemd isn't even created.

i presume it would have to create shadow .wants that symlink to /dev/null.

note that `mask` works just fine.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
> systemctl --user status pipewire
● pipewire.service - PipeWire Multimedia Service
     Loaded: loaded (/usr/lib/systemd/user/pipewire.service; enabled; preset: enabled)
     Active: active (running) since Wed 2023-05-10 11:26:20 CEST; 1min 10s ago
TriggeredBy: ● pipewire.socket
   Main PID: 5558 (pipewire)
      Tasks: 2 (limit: 9505)
     Memory: 5.1M
        CPU: 89ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/pipewire.service
             └─5558 /usr/bin/pipewire
> systemctl --user disable --now pipewire
Warning: Stopping pipewire.service, but it can still be activated by:
  pipewire.socket
> systemctl --user status pipewire
○ pipewire.service - PipeWire Multimedia Service
     Loaded: loaded (/usr/lib/systemd/user/pipewire.service; enabled; preset: enabled)
     Active: inactive (dead) since Wed 2023-05-10 11:27:46 CEST; 2s ago
   Duration: 1min 25.632s
TriggeredBy: ● pipewire.socket
    Process: 5558 ExecStart=/usr/bin/pipewire (code=exited, status=0/SUCCESS)
   Main PID: 5558 (code=exited, status=0/SUCCESS)
        CPU: 98ms
```

**Comment by YHNdnzj** [comment] 2023-05-10 09:50
If the unit is enabled in global scope, there's no way to only disable it in user scope without masking it. A warning for this is added in https://github.com/systemd/systemd/pull/26401.

Duplicate of https://github.com/systemd/systemd/issues/18271.

**Closed as completed** 2023-05-10 09:50 UTC
Labels: bug 🐛, systemctl, user-session

**Comment by ossilator** [comment] 2023-05-10 10:03
> there's no way to only disable it in user scope without masking it

don't you think that this is exactly the bug?
i mean, it's nice that a newer version would have warned me, and that the issue can often be worked around by masking the unit, but what if i actually needed the regular semantics of disable?

**Comment by arvidjaar** [comment] 2023-05-10 10:42
> don't you think that this is exactly the bug?

This is missing feature which is rather hard to implement properly. There was long discussion back on systemd mailing list (years ago) and there could be some open issues on this.
