### ISSUE TITLE
systemd freeze if I disable and enable service MariaDB without service stopping

### ISSUE THREAD

**Issue by bayrepo** [systemd/systemd#5374] opened 2017-02-17 11:41 UTC
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> systemd 219

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> CentOS Linux release 7.3.1611 (Core)

### In case of bug report: Expected behaviour you didn't see

> Correct stopping of service or notification about service should be stopped before disabling, many another service works correctly without stopping after disable and enable, but with MariaDB systemd freezes and the server can't correctly work after freezing, no one new service can be started and stopped. In this situation can't be executed even status check.

### In case of bug report: Unexpected behaviour you saw

> 
```
Broadcast message from systemd-journald@centos7-x64-cltest-com (Fri 2017-02-17 05:56:41 EST):

systemd[1]: Caught <ABRT>, dumped core as pid 19790.


Broadcast message from systemd-journald@centos7-x64-cltest-com (Fri 2017-02-17 05:56:41 EST):

systemd[1]: Freezing execution.


Message from syslogd@centos7-x64-cltest-com at Feb 17 05:56:41 ...
 systemd:Caught <ABRT>, dumped core as pid 19790.

Message from syslogd@centos7-x64-cltest-com at Feb 17 05:56:41 ...
 systemd:Freezing execution.
```

### In case of bug report: Steps to reproduce the problem

> 
The bug can be reproduced with MariaDB 10.1 packages installed from the official site:
[/]# rpm -qa | grep MariaDB
```
MariaDB-common-10.1.21-1.el7.centos.x86_64
MariaDB-server-10.1.21-1.el7.centos.x86_64
MariaDB-client-10.1.21-1.el7.centos.x86_64
MariaDB-shared-10.1.21-1.el7.centos.x86_64
MariaDB-devel-10.1.21-1.el7.centos.x86_64
```

Package has correct mariadb.service file(enabled and loaded) and /etc/init.d/mysql with LSB functions support.

1) check the status of MariaDB service using alias:
```
[/]# systemctl status mysql
● mariadb.service - MariaDB database server
   Loaded: loaded (/usr/lib/systemd/system/mariadb.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/mariadb.service.d
           └─migrated-from-my.cnf-settings.conf
   Active: active (running) since Thu 2017-02-16 16:04:30 EST; 13h ago
  Process: 924 ExecStartPost=/bin/sh -c systemctl unset-environment _WSREP_START_POSITION (code=exited, status=0/SUCCESS)
 Main PID: 569 (mysqld)
   Status: "Taking your SQL requests now..."
   CGroup: /system.slice/mariadb.service
           └─569 /usr/sbin/mysqld

Feb 16 16:04:28 centos7-x64-cltest-com systemd[1]: Starting MariaDB database server...
Feb 16 16:04:29 centos7-x64-cltest-com mysqld[569]: 2017-02-16 16:04:29 140428369041664 [Note] /usr/sbin/mysqld (mysqld 10.1.21-MariaDB) starting as process 569 ...
Feb 16 16:04:30 centos7-x64-cltest-com systemd[1]: Started MariaDB database server.
```
2) disable service: `systemctl disable mysql`
3) check the status of MariaDB service:
```
[/]# systemctl status mariadb.service
● mariadb.service - MariaDB database server
   Loaded: loaded (/usr/lib/systemd/system/mariadb.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/mariadb.service.d
           └─migrated-from-my.cnf-settings.conf
   Active: active (running) since Thu 2017-02-16 16:04:30 EST; 13h ago
 Main PID: 569 (mysqld)
   Status: "Taking your SQL requests now..."
   CGroup: /system.slice/mariadb.service
           └─569 /usr/sbin/mysqld

Feb 16 16:04:28 centos7-x64-cltest-com systemd[1]: Starting MariaDB database server...
Feb 16 16:04:29 centos7-x64-cltest-com mysqld[569]: 2017-02-16 16:04:29 140428369041664 [Note] /usr/sbin/mysqld (mysqld 10.1.21-MariaDB) starting as process 569 ...
Feb 16 16:04:30 centos7-x64-cltest-com systemd[1]: Started MariaDB database server.
```
4) enable again: `systemctl enable mariadb.service`
```
Created symlink from /etc/systemd/system/mysql.service to /usr/lib/systemd/system/mariadb.service.
Created symlink from /etc/systemd/system/mysqld.service to /usr/lib/systemd/system/mariadb.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/mariadb.service to /usr/lib/systemd/system/mariadb.service.
```
5) check status again after enabling: systemctl status mariadb.service
```
[/]# systemctl status mariadb.service
● mariadb.service - MariaDB database server
   Loaded: loaded (/usr/lib/systemd/system/mariadb.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/mariadb.service.d
           └─migrated-from-my.cnf-settings.conf
   Active: inactive (dead)
 Main PID: 569 (mysqld)
   Status: "Taking your SQL requests now..."
   CGroup: /system.slice/mariadb.service
           └─569 /usr/sbin/mysqld

Feb 16 16:04:28 centos7-x64-cltest-com systemd[1]: Starting MariaDB database server...
Feb 16 16:04:29 centos7-x64-cltest-com mysqld[569]: 2017-02-16 16:04:29 140428369041664 [Note] /usr/sbin/mysqld (mysqld 10.1.21-MariaDB) starting as process 569 ...
Feb 16 16:04:30 centos7-x64-cltest-com systemd[1]: Started MariaDB database server.
[/]# systemctl status mysql
● mariadb.service - MariaDB database server
   Loaded: loaded (/usr/lib/systemd/system/mariadb.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/mariadb.service.d
           └─migrated-from-my.cnf-settings.conf
   Active: inactive (dead)
 Main PID: 569 (mysqld)
   Status: "Taking your SQL requests now..."
   CGroup: /system.slice/mariadb.service
           └─569 /usr/sbin/mysqld

Feb 16 16:04:28 centos7-x64-cltest-com systemd[1]: Starting MariaDB database server...
Feb 16 16:04:29 centos7-x64-cltest-com mysqld[569]: 2017-02-16 16:04:29 140428369041664 [Note] /usr/sbin/mysqld (mysqld 10.1.21-MariaDB) starting as process 569 ...
Feb 16 16:04:30 centos7-x64-cltest-com systemd[1]: Started MariaDB database server.
```
6) check that mysqld process exists:
```
[/]# ps aux | grep mysql
mysql      569  0.0  7.7 794960 145128 ?       Ssl  Feb16   0:41 /usr/sbin/mysqld
```
7) kill the process the way it normally stops via SIGTERM (because systemctl can't stop it by command stop)
`kill -SIGTERM 569`
8) I got:
```
Broadcast message from systemd-journald@centos7-x64 (Fri 2017-02-17 05:56:41 EST):

systemd[1]: Caught <ABRT>, dumped core as pid 19790.


Broadcast message from systemd-journald@centos7-x64 (Fri 2017-02-17 05:56:41 EST):

systemd[1]: Freezing execution.


Message from syslogd@centos7-x64 at Feb 17 05:56:41 ...
 systemd:Caught <ABRT>, dumped core as pid 19790.

Message from syslogd@centos7-x64 at Feb 17 05:56:41 ...
 systemd:Freezing execution.
```
9) and here is the coredump:
```
#0  0x00007f12a0ca84a7 in kill () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007f12a260e143 in crash.2993 (sig=6) at src/core/main.c:168
        rl = {rlim_cur = 18446744073709551615, rlim_max = 18446744073709551615}
        sa = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0 <repeats 16 times>}}, sa_flags = 0, sa_restorer = 0x0}
        pid = <optimized out>
        __func__ = "crash"
        __PRETTY_FUNCTION__ = "crash"
        __PRETTY_FUNCTION__ = "crash"
        __func__ = "crash"
#2  <signal handler called>
No symbol table info available.
#3  0x00007f12a0ca81d7 in raise () from /lib64/libc.so.6
No symbol table info available.
#4  0x00007f12a0ca98c8 in abort () from /lib64/libc.so.6
No symbol table info available.
#5  0x00007f12a26295a2 in log_assert_failed_unreachable (text=<optimized out>, file=<optimized out>, line=<optimized out>, func=<optimized out>) at src/shared/log.c:758
No locals.
#6  0x00007f12a2619b2a in service_sigchld_event.9725 (u=0x7f12a34872d0, pid=<optimized out>, code=<optimized out>, status=0) at src/core/service.c:2500
        s = 0x7f12a34872d0
        f = SERVICE_SUCCESS
        __PRETTY_FUNCTION__ = "service_sigchld_event"
        __func__ = "service_sigchld_event"
        __func__ = "service_sigchld_event"
        __PRETTY_FUNCTION__ = "service_sigchld_event"
#7  0x00007f12a25adcc6 in invoke_sigchld_event.3989 (m=<optimized out>, u=0x7f12a34872d0, si=0x7ffcc5b8b3a0) at src/core/manager.c:1779
        iteration = 45967
        __PRETTY_FUNCTION__ = "invoke_sigchld_event"
        __func__ = "invoke_sigchld_event"
        __func__ = "invoke_sigchld_event"
        __PRETTY_FUNCTION__ = "invoke_sigchld_event"
#8  0x00007f12a260fc05 in manager_dispatch_sigchld.3994 (m=0x7f12a3459930) at src/core/manager.c:1831
        name = 0x7f12a34ba020 "mysqld"
        u1 = 0x0
        u2 = 0x7f12a34872d0
        u3 = <optimized out>
        si = {si_signo = 17, si_errno = 0, si_code = 1, _sifields = {_pad = {569, 997, 0 <repeats 26 times>}, _kill = {si_pid = 569, si_uid = 997}, _timer = {si_tid = 569, si_overrun = 997,
              si_sigval = {sival_int = 0, sival_ptr = 0x0}}, _rt = {si_pid = 569, si_uid = 997, si_sigval = {sival_int = 0, sival_ptr = 0x0}}, _sigchld = {si_pid = 569, si_uid = 997,
              si_status = 0, si_utime = 0, si_stime = 0}, _sigfault = {si_addr = 0x3e500000239}, _sigpoll = {si_band = 4282082394681, si_fd = 0}, _sigsys = {_call_addr = 0x3e500000239,
              _syscall = 0, _arch = 0}}}
        __PRETTY_FUNCTION__ = "manager_dispatch_sigchld"
        __func__ = "manager_dispatch_sigchld"
        __func__ = "manager_dispatch_sigchld"
        __PRETTY_FUNCTION__ = "manager_dispatch_sigchld"
#9  0x00007f12a25c76dc in manager_dispatch_signal_fd.3938 (source=<optimized out>, fd=<optimized out>, revents=<optimized out>, userdata=0x7f12a3459930) at src/core/manager.c:2090
        m = 0x7f12a3459930
        n = <optimized out>
        sfsi = {ssi_signo = 17, ssi_errno = 0, ssi_code = 1, ssi_pid = 569, ssi_uid = 997, ssi_fd = 0, ssi_tid = 0, ssi_band = 0, ssi_overrun = 0, ssi_trapno = 0, ssi_status = 0, ssi_int = 0,
          ssi_ptr = 0, ssi_utime = 816, ssi_stime = 1214, ssi_addr = 0, __pad = '\000' <repeats 47 times>}
        sigchld = true
        __PRETTY_FUNCTION__ = "manager_dispatch_signal_fd"
        __func__ = "manager_dispatch_signal_fd"
        code_table = {MANAGER_HALT, MANAGER_POWEROFF, MANAGER_REBOOT, MANAGER_KEXEC}
        target_table = {0x7f12a263758c "default.target", 0x7f12a2638f6e "rescue.target", 0x7f12a2638f53 "emergency.target", 0x7f12a263f64e "halt.target", 0x7f12a263f65a "poweroff.target",
          0x7f12a263f66a "reboot.target", 0x7f12a263f678 "kexec.target"}
        __func__ = "manager_dispatch_signal_fd"
        __PRETTY_FUNCTION__ = "manager_dispatch_signal_fd"
#10 0x00007f12a25a7890 in source_dispatch (s=s@entry=0x7f12a345a0c0) at src/libsystemd/sd-event/sd-event.c:2115
        r = <optimized out>
        __PRETTY_FUNCTION__ = "source_dispatch"
        __func__ = "source_dispatch"
        __func__ = "source_dispatch"
        __PRETTY_FUNCTION__ = "source_dispatch"
#11 0x00007f12a25a9dea in sd_event_dispatch (e=0x7f12a3459db0) at src/libsystemd/sd-event/sd-event.c:2472
        p = <optimized out>
        r = <optimized out>
        __PRETTY_FUNCTION__ = "sd_event_dispatch"
        __PRETTY_FUNCTION__ = "sd_event_dispatch"
#12 0x00007f12a25c346f in sd_event_run (timeout=18446744073709551615, e=0x7f12a3459db0) at src/libsystemd/sd-event/sd-event.c:2501
        r = <optimized out>
        __PRETTY_FUNCTION__ = "sd_event_run"
#13 manager_loop (m=0x7f12a3459930) at src/core/manager.c:2209
        wait_usec = 18446744073709551615
        r = <optimized out>
        rl = {interval = 1000000, begin = 67938068037, burst = 50000, num = 3}
        __PRETTY_FUNCTION__ = "manager_loop"
        __func__ = "manager_loop"
        __func__ = "manager_loop"
        __PRETTY_FUNCTION__ = "manager_loop"
#14 0x00007f12a256cc7e in main (argc=<optimized out>, argv=<optimized out>) at src/core/main.c:1791
        m = 0x7f12a3459930
        r = <optimized out>
        retval = 1
        before_startup = <optimized out>
        after_startup = <optimized out>
        timespan = "\260\267\270\305\374\177\000\000\322\067\063\242\022\177\000\000p\275\212\241\022\177\000\000\322>3\242\022\177\000\000ȔS\242\022\177\000\000\230yT\242\022\177", '\000' <repeats 17 times>
        fds = 0x0
        reexecute = false
        shutdown_verb = 0x0
        initrd_timestamp = <optimized out>
        userspace_timestamp = {realtime = 1487261066909897, monotonic = 4106431}
        kernel_timestamp = {realtime = <optimized out>, monotonic = 0}
        security_start_timestamp = {realtime = 1487261066914799, monotonic = 4111333}
        security_finish_timestamp = {realtime = 1487261066960129, monotonic = 4156663}
        systemd = "systemd"
        skip_setup = <optimized out>
        j = <optimized out>
        loaded_policy = false
        arm_reboot_watchdog = false
        queue_default_job = <optimized out>
        empty_etc = <optimized out>
        switch_root_dir = 0x0
        switch_root_init = 0x0
        saved_rlimit_nofile = {rlim_cur = 1024, rlim_max = 4096}
        error_message = 0x0
        __func__ = "main"
        __PRETTY_FUNCTION__ = "main"
        table = {0x0, 0x0, 0x0, 0x0, 0x7f12a263619c "reboot", 0x7f12a26361c1 "poweroff", 0x7f12a263a16c "halt", 0x7f12a26438c3 "kexec", 0x0}
        __PRETTY_FUNCTION__ = "main"
        systemd = "systemd"
        __func__ = "main"

```

**Comment by bayrepo** [comment] 2017-02-17 11:48
Here is the mariadb.service file:

```
#
# /etc/systemd/system/mariadb.service
#

[Unit]
Description=MariaDB database server
After=network.target
After=syslog.target

[Install]
WantedBy=multi-user.target
Alias=mysql.service
Alias=mysqld.service


[Service]

Type=notify
PrivateNetwork=false
User=mysql
Group=mysql
CapabilityBoundingSet=CAP_IPC_LOCK
ProtectSystem=full
PrivateDevices=true
ProtectHome=true
PermissionsStartOnly=true
ExecStartPre=/bin/sh -c "systemctl unset-environment _WSREP_START_POSITION"
ExecStartPre=/bin/sh -c "[ ! -e /usr/bin/galera_recovery ] && VAR= || \
 VAR=`/usr/bin/galera_recovery`; [ $? -eq 0 ] \
 && systemctl set-environment _WSREP_START_POSITION=$VAR || exit 1"
ExecStart=/usr/sbin/mysqld $MYSQLD_OPTS $_WSREP_NEW_CLUSTER $_WSREP_START_POSITION
ExecStartPost=/bin/sh -c "systemctl unset-environment _WSREP_START_POSITION"

KillMode=process
KillSignal=SIGTERM

SendSIGKILL=no
Restart=on-abort
RestartSec=5s

UMask=007

PrivateTmp=false

LimitNOFILE=16364

```

**Comment by zdzichu** [comment] 2017-02-17 12:35
> systemd 219
> NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream

You missed the note above. The right place to file this bugreport would be Centos bugtracker.

You can also check latest systemd backports to see if the problem is still there:
https://maciej.lasyk.info/2016/Dec/16/systemd-231-latest-in-centos-7-thx-to-facebook/
If it is present in latest systemd version, reopen this issue.

**Comment by poettering** [comment] 2017-02-17 12:50
Closing, this is way too old to be tracked upstream. Please contact your downstream distro for help.

**Closed as completed by poettering** 2017-02-17 12:50 UTC
Labels: version-too-ancient

**Comment by laukstein** [comment] 2018-05-03 14:42
@bayrepo did you reported this issue to MariaDB? I think I had the same issue on latest CendOS with latest MariaDB a few weeks ago. mariadb.service restart solved that error, but still I can't predict if it will not return.

**Comment by bayrepo** [comment] 2018-05-03 15:06
@laukstein, No, I didn't report to MariaDB. Currently I can't reproduce the issue anymore on my test servers.
