### ISSUE TITLE
Provide more details to polkit for org.freedesktop.machine1.host-*

### ISSUE THREAD

**Issue by gdiscry** [systemd/systemd#12448] opened 2019-04-30 22:37 UTC
**Is your feature request related to a problem? Please describe.**

I'm trying to solve the issue of keeping tmux running when `KillUserProcesses=yes` and without enabling the linger state for my user. I have a working solution with a few remaining papercuts and one could be solved in systemd.

My solution consists of
- configuring tmux with `set-option -g default-command="machinectl shell ${USER}@"`
- running tmux with `systemd-run --user --scope tmux`

It works because tmux runs as a transient scope unit in the user manager and is not killed by `KillUserProcess=yes` when the session that launched it is closed. For each new window, tmux runs `machinectl shell` for the current user, which creates a new session and keeps the user manager alive as long as tmux has an active window. Once the last session is closed (whether a standard session or a tmux window), everything is cleaned up and the user manager is stopped.

My main issue is that each new window requires a polkit admin authentication to run a shell as the current user on the current host. The polkit action `org.freedesktop.machine1.host-shell` contains no details regarding the user of the new shell so I cannot simply authorize the action when the subject requesting the action is the same as the user of the new shell.

**Describe the solution you'd like**

I'd like to skip the authentication step for `machinectl shell ${USER}@`.

I have no issues if I have to add a rule to polkit, but I would at least need to know the user of the new shell as a property of the action.

Other properties such as the command and its arguments could also be useful and similar details could also be added to the other actions.

**Describe alternatives you've considered**

I could create a polkit rule to authorize all calls to `org.freedesktop.machine1.host-shell`, but it sounds like a very bad idea.

I could continue to authenticate, but then this solution cannot be used by users without admin access.

**Comment by srd424** [comment] 2019-08-19 14:49
+1 for this - poking through the guts of machined, it seems there are various places details/variables such as machine name, user name, etc. could be passed?

**Comment by poettering** [comment] 2020-01-13 15:35
Duplicate of #6279

**Closed as completed by poettering** 2020-01-13 15:35 UTC
Labels: RFE 🎁, machine
