### ISSUE TITLE
User friendly error messages about unsupported specifiers

### ISSUE THREAD

**Issue by nartamonov** [systemd/systemd#3021] opened 2016-04-12 11:44 UTC
### Submission type
- [ ] Bug report
- [X] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 215
### Used distribution

> Debian Jessie 8.3
### Problem

I'm absolutely new to systemd, so recently I write my first systemd-powered service, which runs simple java application. Most relevant part here:

```
[Service]
ExecStart=/usr/bin/java -Dapp.host=10.200.232.39 -Dapp.port=8090 -Dapp.downloadable-link-template="http://10.200.232.39:8086/%s" -jar /usr/local/stat-counter/stat-counter_2.11-0.3-assembly.jar
```

You can see that application expects formatted-string in place of argument app.downloadable-link-template. What I didn't know as novice is that systemd interprets %X as [specifiers](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Specifiers), in case of %s it is path to user shell which runs systemd instance. When I tried to run service I got unexpected and _absolutely non-informative error message_:

```
Apr 12 14:12:18 videoarch systemd[1]: stat-counter.service failed to run 'start' task: Operation not supported
```

Exactly what operation not supported? So after struggling with it I found some discussion about similar problem but with %i. When I escaped specifier with %%s all worked fine.
### Proposal

Make error messages more user friendly, with details about what operation exactly not supported (in my case it is "specifier %s can not be resolved").

**Comment by keszybz** [comment] 2016-04-25 01:16
Can you paste the whole unit? I cannot reproduce this with current git.

**Comment by nartamonov** [comment] 2016-04-26 17:58
Sorry for delay:

```
[Unit]
Description=Counts archive downloads

[Service]
ExecStart=/usr/bin/java \
    -Dapp.host=10.200.232.39 \
    -Dapp.port=8090 \
    -Dapp.downloadable-link-template="http://10.200.232.39:8086/%s" \
    -jar /usr/local/stat-counter/stat-counter_2.11-0.3-assembly.jar
User=debian
TimeoutStopSec=30s
Restart=always
StartLimitInterval=90s
StartLimitBurst=3
RestartSec=10s

[Install]
WantedBy=multi-user.target
```

**Comment by RadicalPet** [comment] 2017-01-02 11:02
+1 just ran into the same problem and only found the solution via this issue

**Comment by pembo13** [comment] 2018-04-30 09:44
Just for bit by this myself, thankfully Goolge led me here. In my case, i was following the documentation for Celery on creating a systemd service: http://docs.celeryproject.org/en/latest/userguide/daemonizing.html#usage-systemd

**Comment by poettering** [comment] 2019-03-11 12:50
THis is pretty much a duplicate of #1566. Let's close this one

**Closed as completed by poettering** 2019-03-11 12:50 UTC
Labels: pid1, duplicate, needs-better-log-message
