### ISSUE TITLE
systemd-cryptsetup spuriously fail

### ISSUE THREAD

**Issue by yshui** [systemd/systemd#14927] opened 2020-02-23 14:59 UTC
**systemd version the issue has been seen with**
> 244.3 

**Used distribution**
 > Arch Linux

**Unexpected behaviour you saw**
 > systemd-cryptsetup fails with the correct passphrase/keyfile

**Details**
This seems to only happen during early boot. Doesn't seem to be a problem after the system booted.

I kept getting unlock fails for my root device. At first I thought I was just bad at typing passwords. But recently I tried using keyfiles for unlocking. And systemd-cryptsetup _still fails_ non-deterministically. I can simply run

```
systemctl start systemd-cryptsetup@root
```
in the rescue shell to successfully unlock the device, without touching the device or the keyfile.

**Comment by Hello71** [comment] 2020-02-23 19:12
I had this issue before when I used the "Linux root" GPT partition type. Ensure you have set your partitions to "Linux filesystem".

**Comment by yshui** [comment] 2020-02-23 19:31
Happens to an unpartitioned device as well.

**Comment by cmurf** [comment] 2020-02-27 03:08
At least it should work with any of these partition type GUIDs:
CA7D7CCB-63ED-4C53-861C-1742536059CC  LUKS
7FFEC5C9-2D00-49B7-8941-3EA10A5586B7    plain dm-crypt
0FC63DAF-8483-4772-8E79-3D69D8477DE4    Linux filesystem data

I'm not sure what argument there is for ignoring any of the Linux partition type GUIDs unless they're incompatible with the arch. But if I were to LUKS encrypt /home and have that partition set to GUID: 933AC7E1-2EB4-4F13-B844-0E14E2AEF915 I still think the intent is clear. The meaning of seeing this GUID plus a LUKS signature is "this is a LUKS encrypted /home, we need to unlock it and then mount it to /home" rather than fail.

**Comment by yshui** [comment] 2020-03-06 19:16
According to debug logs this is due to a pbkdf2 verification failure, which makes no sense as I am using a keyfile.

**Comment by cmurf** [comment] 2020-03-15 02:41
A keyfile does not obviate KDF. The specific KDF, salt, iterations, are intrinsic to LUKS. I suggest modifying the cryptsetup service unit, adding --verbose or --debug, and then reproduce the problem.

**Comment by yshui** [comment] 2020-03-16 10:13
@cmurf I don't think `systemd-cryptsetup` takes such arguments

**Comment by yshui** [comment] 2020-03-16 10:31
What I meat by verification failure is:

```
Feb 23 15:17:04 archlinux systemd-cryptsetup[671]: Verifying key from keyslot 0, digest 0.
Feb 23 15:17:04 archlinux systemd-cryptsetup[671]: Digest 0 (pbkdf2) verify failed with -1.
```

**Comment by poettering** [comment] 2020-04-01 17:21
hmm, this looks like an issue in libcryptsetup. Maybe the kdf used is argon2 and you don't have enough memory?

Anyway, please ping the libcryptsetup people, the error message you see is from libcryptsetup, not systemd.

**Comment by poettering** [comment] 2020-04-01 17:21
even if you use a keyfile libcryptsetup still uses a kdf iirc

**Comment by yshui** [comment] 2020-04-01 21:00
@poettering 
> Maybe the kdf used is argon2 and you don't have enough memory?

if that's the case, this won't just happen occasionally.

> Anyway, please ping the libcryptsetup people, the error message you see is from libcryptsetup, not systemd.

OK.

**Comment by poettering** [comment] 2020-04-23 12:19
> @poettering
> 
> > Maybe the kdf used is argon2 and you don't have enough memory?
> 
> if that's the case, this won't just happen occasionally.

Well, it might be racy: it might have enough ram as long as nothing else wants the same resources...

> > Anyway, please ping the libcryptsetup people, the error message you see is from libcryptsetup, not systemd.
> 
> OK.

Any results? Can we close this here?

**Comment by yshui** [comment] 2020-04-23 12:31
> Any results? Can we close this here?

I am yet to submit the problem to libcryptsetup, but I guess you can close this one for now.

> don't have enough memory?

I have 32G of memory, kind of weird for that to be used up during boot...

**Closed as completed** 2020-04-23 12:31 UTC
Labels: bug 🐛, needs-reporter-feedback ❓, cryptsetup

**Comment by poettering** [comment] 2020-04-23 13:53
If argon2 is used as kdf it will use half the physical memory by default. so if you have two disks it will already use more memory than available.

**Comment by yshui** [comment] 2020-04-23 21:58
@poettering I don't think what you said is true.

This is what cryptsetup says is the default:

```
Default PBKDF for LUKS2: argon2i
        Iteration time: 2000, Memory required: 1048576kB, Parallel threads: 4
```

Which is confirmed by `luksDump`:

```
        PBKDF:      argon2i
        Time cost:  10
        Memory:     1048576
        Threads:    4
```

**Comment by yshui** [comment] 2020-05-31 03:34
Update: memtest revealed a bit flip in my RAM. I suspect this could be it.

>
