### ISSUE TITLE
systemd-logind does not terminate git+ssh sessions correctly

### ISSUE THREAD

**Issue by SjonHortensius** [systemd/systemd#27210] opened 2023-04-11 09:17 UTC
### systemd version the issue has been seen with

253

### Used distribution

archlinux

### Linux kernel version used

6.2.2-arch1-1

### CPU architectures issue was seen on

x86_64

### Component

loginctl

### Expected behaviour you didn't see

git through ssh sessions should be closed but aren't

### Unexpected behaviour you saw

`loginctl|wc -l` shows `8192` sessions, most of which are owned by the `git` user. Example of a session:

```
229307 - git (998)
           Since: Wed 2023-04-05 03:10:11 CEST; 6 days ago
          Leader: 3114376
          Remote: xxxx
         Service: sshd; type tty; class user
           State: closing
            Unit: session-229307.scope

Apr 05 03:10:11 systemd[1]: Started Session 229307 of User git.
Apr 05 03:10:11 sshd[3114378]: Received disconnect from xxxx port 54156:11: disconnected by user
Apr 05 03:10:11 sshd[3114378]: Disconnected from user git xxxx port 54156
Apr 05 03:10:11 systemd[1]: session-229307.scope: Deactivated successfully.
```

### Steps to reproduce the problem

this will happen after roughly 3 days of normal usage. Fixed by restarting `systemd-logind`

**Comment by YHNdnzj** [comment] 2023-04-11 09:23
Might be a duplicate of #26744?

**Comment by SjonHortensius** [comment] 2023-04-11 12:55
> Might be a duplicate of #26744?

agreed, they look similar and will very likely have the same root-cause. Should I close this one as a dup?

**Comment by YHNdnzj** [comment] 2023-04-11 13:10
Closing this as a duplicate now. Feel free to ask for reopen if things turned out otherwise.

**Closed as not planned by YHNdnzj** 2023-04-11 13:10 UTC
Labels: bug 🐛, login, duplicate
