### ISSUE TITLE
systemd-repart --sector-size=4096 with drives reporting 512b sector size

### ISSUE THREAD

**Issue by cvlc12** [systemd/systemd#35258] opened 2024-11-20 13:49 UTC
### systemd version the issue has been seen with

256

### Used distribution

Arch

### Linux kernel version used

6.11

### CPU architectures issue was seen on

x86_64

### Component

systemd-repart

### Expected behaviour you didn't see

My Samsung SSD only reports support for 512 bytes sector size.

Shouldn't it be possible to pass on a 4K sector size to systemd-repart so that it forces the use of 4K sectors with LUKS/ filesystems ?

### Unexpected behaviour you saw

```
# systemd-repart --sector-size=4096 /dev/nvme1n1
Disk /dev/nvme1n1 has no GPT disk label, not repartitioning.
```

### Steps to reproduce the problem

can also be reproduced in a vm with using
```
 <blockio logical_block_size='512' physical_block_size='4096'/>
```

**Comment by poettering** [comment] 2024-11-21 09:04
> Shouldn't it be possible to pass on a 4K sector size to systemd-repart so that it forces the use of 4K sectors with LUKS/ filesystems ?

The GPT header is different for 512B and 4K sector disks. you thus cannot just copy a 4K image onto a 512B disk, because firmware wouldn#t find the partition table then. It's a pity, but it is how it is.

That said, repart always aligns all offsets to 4K anyway, even on 512B, even if it writes out a 512B GPT.

> # systemd-repart --sector-size=4096 /dev/nvme1n1
> Disk /dev/nvme1n1 has no GPT disk label, not repartitioning.

This actually works as intended: repart by default won't touch disks it cannot recognize a label on. And given you said your disk is actually 512B it won't find one if it looks for a 4K partition table. You can use `--empty=force` to empty the disk entirely and force it to write a new partition table for 4K.

But as mentioned, this won't make you happy, as you can't boot from it anymore, and I am not sure even Linux would recognize your partition table anymore given the wrongly organized GPT label.

Anyway, I am not seeing anything actionable here, closing.

**Closed as completed by poettering** 2024-11-21 09:04 UTC
Labels: bug 🐛, repart
