### ISSUE TITLE
Assertion 'r < 0' failed at ../systemd-239/src/journal/test-compress.c:235, function test_lz4_decompress_partial(). Aborting.

### ISSUE THREAD

**Issue by floppym** [systemd/systemd#10550] opened 2018-10-28 22:42 UTC
**systemd version the issue has been seen with**
systemd-239

**Used distribution**
Gentoo

**Summary**
With lz4-1.8.3, `LZ4_decompress_safe_partial` appears to work.

test_lz4_decompress_partial should be adjusted not to expect failure.

**Comment by yuwata** [comment] 2018-10-28 22:57
Duplicate of #10259.

**Closed as completed** 2018-10-28 22:57 UTC
Labels: journal, duplicate
