### ISSUE TITLE
gpt-auto-generator failing in early boot

### ISSUE THREAD

**Issue by AdrianVovk** [systemd/systemd#19833] opened 2021-06-07 04:57 UTC
**systemd version the issue has been seen with**
 > 248 (commit: a8f76a8db744e706abf3b6e806645f5b92dae698)

**Used distribution**
 > carbonOS

**Linux kernel version used** (`uname -a`)

 > `Linux carbonos 5.12.9 #1 SMP PREEMPT Sat Jun 5 04:28:17 UTC 2021 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > gpt-auto-generator sets up boot.automount and boot.mount for the ESP

**Unexpected behaviour you saw**
 > gpt-auto-generator fails to find ESP with error: `systemd-gpt-auto-generator[497]: Failed to dissect: Connection timed out` and then exits with status 1

**Steps to reproduce the problem**
 > Try to use gpt-auto-generator to mount anything other than rootfs. I'm not certain how to reproduce this because it is happening 100% of the time on my system and so I don't know what exactly is triggering it.

**More info**
> This is seemingly related to #19442, though it didn't fit that issue's scope. Oddly enough, running `systemctl daemon-reload` once I'm booted into the system works perfectly fine, as does the `systemd-dissect` tool and simply running the generator (`doas /usr/lib/.../gpt-auto-generator tmpdir tmpdir tmpdir && ls tmpdir`)

**Comment by poettering** [comment] 2021-06-07 08:33
Duplicate of #19377

**Closed as completed by poettering** 2021-06-07 08:33 UTC
Labels: gpt-auto, duplicate, dissect

**Comment by keszybz** [comment] 2021-06-07 08:35
I think we might have another error lurking here. #19377 was closed 6 days ago, and I saw a very similar error in #19817, which is three days old.

**Comment by AdrianVovk** [comment] 2021-06-07 14:14
Wow I don't know how I missed that other ticket. Sorry about the noise. I'll reopen if that doesn't fix it
