### ISSUE TITLE
user mount units always fail, even on FUSE filesystems

### ISSUE THREAD

**Issue by scruloose** [systemd/systemd#13741] opened 2019-10-07 14:35 UTC
**systemd version the issue has been seen with**

242

**Used distribution**

 Debian Bullseye

**Expected behaviour you didn't see**

 When a user '.mount' unit refers to a FUSE filesystem (eg `Type=fuse.sshfs`), I would expect the user's systemd instance to use the appropriate FUSE command to mount it.

The same regular user mounting the same remote folder to the same local mountpoint by invoking sshfs directly works as expected.

Specifically, I was hoping to set up a mount/automount pair in /etc/systemd/user, using the appropriate specifiers so that any logged-in user could have on-demand access to their remote files via a mountpoint in their local home dir, with correct access controls enforced by using each user's own ssh key (unlocked with ssh-add at login, of course) to connect to their own account on the remote server.

**Unexpected behaviour you saw**

Instead of recognizing that a non-root user can mount a `fuse.sshfs` filesystem only by invoking `sshfs`, the user's systemd instance blindly called `mount` directly, which of course failed due to lack of privilege (similar to [bugzilla bug #73809](https://bugs.freedesktop.org/show_bug.cgi?id=73809)).

Here are relevant lines from journalctl (sanitized, of course):

    Oct 07 10:00:52 hostname mount[7473]: mount: only root can use "--options" option
    Oct 07 10:00:52 hostname systemd[1350]: path-to-mountpoint.mount: Mount process exited, code=exited, status=1/FAILURE
    -- Subject: Unit process exited
    ...
    -- The process' exit code is 'exited' and its exit status is 1.
    Oct 07 10:00:52 hostname systemd[1350]: path-to-mountpoint.mount: Failed with result 'exit-code'.
    -- Subject: Unit failed

**Steps to reproduce the problem**

Create a user unit of type 'mount' to mount a FUSE filesystem. (As far as I can tell, it will fail in the same way no matter what the filesystem is. I have tested with sshfs.)

Command:
`systemctl --user daemon-reload && systemctl --user restart path-to-mountpoint.mount`

Result:
`Job failed. See "journalctl -xe" for details.`

**Comment by poettering** [comment] 2019-10-09 16:56
Nah, there's a protocol built into the /bin/mount command for fuse fs implementations to make themselves available with, thus using plain mount for fuse mounts should generally work too, as long as the fuse tool implements this correctly (many do, some dont). 

The thing though is that /bin/mount refuses to work if you mix unpriv invocation and -o. This is something that util-linux needs to fix for you though.

@karelzak, any idea? Is there any support for allowing invocation of unpriv fuse programs via /bin/mount while specifying -o?

**Comment by karelzak** [comment] 2019-10-10 08:41
Hmm... for non-root users mount(8) assumes that all necessary information and mount options are specified by root user in /etc/fstab, so non-user cannot modify anything from command line and -o is forbidden for non-root users at all. This is important security feature (don't forget mount(8) is suid).

Unfortunately this semantic is generic and applied to all mount(8) execution although the execution is later redirected to some /sbin/mount.<type> helper with non-root rights. This is design disadvantage and fix it in libmount won't be simple, because helper is one of the last thing the library does when mount(8) is executed.

It seems we need to remember that -o is wanted by non-root user and then avoid any conclusion based on mount option in the library and strictly require non-suid execution of  /sbin/mount.<type>. I'll think about it, IMHO it will be possible to fix it.

@scruloose maybe you can report it against util-linux (https://github.com/karelzak/util-linux/issues -- just copy & past this discussion). This is really not systemd issue, it should be possible to reproduce it by mount(8) on command line.

**Comment by poettering** [comment] 2019-10-23 17:46
OK, let's move this to util-linux and close this here. If this is fixed for util-linux this will magically start working in systemd too.

**Closed as completed by poettering** 2019-10-23 17:46 UTC
Labels: RFE 🎁, pid1, not-our-bug

**Comment by karelzak** [comment] 2019-11-19 14:45
@scruloose just to keep you informed, I have a patch and if all will continue as expected than it will be possible with util-linux v2.35 (next month).
https://lore.kernel.org/util-linux/20191119143408.b6pcbhtsiubxdcob@10.255.255.10/T/#u

The idea is to drop suid permissions in mount(8) when you specify on command line something what is allowed only for root user by default. This simple solution allows to use fuse or user namespaces by mount(8) without root perms or user= fstab configuration.

**Comment by scruloose** [comment] 2019-11-19 16:27
@karelzak Nice! I look forward to trying it out.  Thanks for your work on this.
