### ISSUE TITLE
high cpu usage from systemd-udevd

### ISSUE THREAD

**Issue by jonas-w** [systemd/systemd#24160] opened 2022-07-31 20:28 UTC
Sometimes at random systemd-udevd uses 1 cpu core on 100%. I don't know why and want to understand why this happens.

I just ran udevadm monitor while it had 100% cpu usage on one core and this was the output:
```
KERNEL[16384.956041] change   /devices/pci0000:00/0000:00:0d.0/usb2/2-1/2-1.4/2-1.4.4/2-1.4.4:1.0/host0/target0:0:0/0:0:0:0/block/sda (block)
KERNEL[16384.956591] change   /devices/pci0000:00/0000:00:0d.0/usb2/2-1/2-1.4/2-1.4.4/2-1.4.4:1.0/host0/target0:0:0/0:0:0:0/block/sda (block)
UDEV  [16384.958077] change   /devices/pci0000:00/0000:00:0d.0/usb2/2-1/2-1.4/2-1.4.4/2-1.4.4:1.0/host0/target0:0:0/0:0:0:0/block/sda (block)
KERNEL[16384.958792] change   /devices/pci0000:00/0000:00:0d.0/usb2/2-1/2-1.4/2-1.4.4/2-1.4.4:1.0/host0/target0:0:0/0:0:0:0/block/sda (block)
KERNEL[16384.959375] change   /devices/pci0000:00/0000:00:0d.0/usb2/2-1/2-1.4/2-1.4.4/2-1.4.4:1.0/host0/target0:0:0/0:0:0:0/block/sda (block)
KERNEL[16384.961030] change   /devices/pci0000:00/0000:00:0d.0/usb2/2-1/2-1.4/2-1.4.4/2-1.4.4:1.0/host0/target0:0:0/0:0:0:0/block/sda (block)
```
this is only a part of it. This get's printed non stop until the cpu usage goes back. (I have a logfile with over 10000 lines like this)

What does this information tell me and how can i prevent this from happening?

EDIT:
I use Archlinux
My versions:
``` 
➜  ~ systemctl --version
systemd 251 (251.3-1-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
➜  ~ uname -a
Linux orange 5.18.15-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Fri, 29 Jul 2022 22:52:41 +0000 x86_64 GNU/Linux
```

**Comment by yuwata** [comment] 2022-08-01 04:37
Please try to generate debugging logs of systemd-udevd. It seems not necessary to generate whole debugging logs, but it sounds enough for `sda` or other block devices. So, try to create the following file:
```
# /etc/udev/rules.d/00-debug-block.rules
SUBSYSTEM=="block", OPTIONS="log_level=debug"
```
Then, please provide the relevant journal for udevd.

**Comment by yuwata** [comment] 2022-08-01 04:38
BTW, you do not provide several basic information: version of systemd, distro, arch, so on.

**Comment by jonas-w** [comment] 2022-08-01 19:24
@yuwata sorry, added the version information to my post!

Where will this debug log appear? in the journal output of the systemd-udevd unit?

As this error isn't predictable i will send these logs next time it happens.

**Comment by jonas-w** [comment] 2022-09-07 15:21
Okay it seems to have something to do with my docking station. The last few weeks i didn't plug my laptop into my docking station and the high cpu usage through udevd never occured. Today i plugged it in again and after using it for a few hours it happened again. These seem to be the debug logs (These lines repeated themselves over a 1000 times in the timespan of one minute):

```
 sda: '/sbin/multipath -u sda'(out) 'DM_MULTIPATH_DEVICE_PATH="0"'
 sda: Process '/sbin/multipath -u sda' succeeded.
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:63 Importing properties from results of builtin command 'usb_id'
 3-1.4.4:1.0: if_class:8 protocol:6
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:68 LINK 'disk/by-id/usb-Generic_MassStorageClass_000000002958-0:0'
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:90 Importing properties from results of builtin command 'path_id'
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:92 LINK 'disk/by-path/pci-0000:00:14.0-usb-0:1.4.4:1.0-scsi-0:0:0:0'
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:110 Importing properties from results of builtin command 'blkid'
 sda: Failed to open block device /dev/sda, ignoring: No such device or address
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:127 LINK 'disk/by-diskseq/10'
 sda: Handling device node '/dev/sda', devnum=b8:0
 sda: sd-device: Created db file '/run/udev/data/b8:0' for '/devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1.4/3-1.4.4/3-1.4.4:1.0/host0/target0:0:0/0:0:0:0/block/sda'
 sda: Adding watch on '/dev/sda'
 sda: Device processed (SEQNUM=2007902, ACTION=change)
 sda: sd-device-monitor: Passed 1043 byte to netlink monitor
 sda: The log level is changed to 'debug' while processing device (SEQNUM=2007903, ACTION=change)
 sda: /usr/lib/udev/rules.d/56-multipath.rules:34 Importing properties from results of '/sbin/multipath -u sda'
 sda: Starting '/sbin/multipath -u sda'
 Successfully forked off '(spawn)' as PID 409330.
 sda: '/sbin/multipath -u sda'(out) 'DM_MULTIPATH_DEVICE_PATH="0"'
 sda: Process '/sbin/multipath -u sda' succeeded.
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:63 Importing properties from results of builtin command 'usb_id'
 3-1.4.4:1.0: if_class:8 protocol:6
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:68 LINK 'disk/by-id/usb-Generic_MassStorageClass_000000002958-0:0'
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:90 Importing properties from results of builtin command 'path_id'
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:92 LINK 'disk/by-path/pci-0000:00:14.0-usb-0:1.4.4:1.0-scsi-0:0:0:0'
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:110 Importing properties from results of builtin command 'blkid'
 sda: Failed to open block device /dev/sda, ignoring: No such device or address
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:127 LINK 'disk/by-diskseq/10'
 sda: Handling device node '/dev/sda', devnum=b8:0
 sda: sd-device: Created db file '/run/udev/data/b8:0' for '/devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1.4/3-1.4.4/3-1.4.4:1.0/host0/target0:0:0/0:0:0:0/block/sda'
 sda: Adding watch on '/dev/sda'
 sda: Device processed (SEQNUM=2007903, ACTION=change)
 sda: sd-device-monitor: Passed 1043 byte to netlink monitor
 sda: The log level is changed to 'debug' while processing device (SEQNUM=2007904, ACTION=change)
 sda: /usr/lib/udev/rules.d/56-multipath.rules:34 Importing properties from results of '/sbin/multipath -u sda'
 sda: Starting '/sbin/multipath -u sda'
 Successfully forked off '(spawn)' as PID 409331.
 sda: '/sbin/multipath -u sda'(out) 'DM_MULTIPATH_DEVICE_PATH="0"'
 sda: Process '/sbin/multipath -u sda' succeeded.
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:63 Importing properties from results of builtin command 'usb_id'
 3-1.4.4:1.0: if_class:8 protocol:6
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:68 LINK 'disk/by-id/usb-Generic_MassStorageClass_000000002958-0:0'
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:90 Importing properties from results of builtin command 'path_id'
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:92 LINK 'disk/by-path/pci-0000:00:14.0-usb-0:1.4.4:1.0-scsi-0:0:0:0'
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:110 Importing properties from results of builtin command 'blkid'
 sda: Failed to open block device /dev/sda, ignoring: No such device or address
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:127 LINK 'disk/by-diskseq/10'
 sda: Handling device node '/dev/sda', devnum=b8:0
 sda: sd-device: Created db file '/run/udev/data/b8:0' for '/devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1.4/3-1.4.4/3-1.4.4:1.0/host0/target0:0:0/0:0:0:0/block/sda'
 sda: Adding watch on '/dev/sda'
 sda: Device processed (SEQNUM=2007904, ACTION=change)
 sda: sd-device-monitor: Passed 1043 byte to netlink monitor
 sda: The log level is changed to 'debug' while processing device (SEQNUM=2007905, ACTION=change)
 sda: /usr/lib/udev/rules.d/56-multipath.rules:34 Importing properties from results of '/sbin/multipath -u sda'
 sda: Starting '/sbin/multipath -u sda'
 Successfully forked off '(spawn)' as PID 409332.
 sda: '/sbin/multipath -u sda'(out) 'DM_MULTIPATH_DEVICE_PATH="0"'
 sda: Process '/sbin/multipath -u sda' succeeded.
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:63 Importing properties from results of builtin command 'usb_id'
 3-1.4.4:1.0: if_class:8 protocol:6
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:68 LINK 'disk/by-id/usb-Generic_MassStorageClass_000000002958-0:0'
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:90 Importing properties from results of builtin command 'path_id'
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:92 LINK 'disk/by-path/pci-0000:00:14.0-usb-0:1.4.4:1.0-scsi-0:0:0:0'
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:110 Importing properties from results of builtin command 'blkid'
 sda: Failed to open block device /dev/sda, ignoring: No such device or address
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:127 LINK 'disk/by-diskseq/10'
 sda: Handling device node '/dev/sda', devnum=b8:0
 sda: sd-device: Created db file '/run/udev/data/b8:0' for '/devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1.4/3-1.4.4/3-1.4.4:1.0/host0/target0:0:0/0:0:0:0/block/sda'
 sda: Adding watch on '/dev/sda'
 sda: Device processed (SEQNUM=2007905, ACTION=change)
 sda: sd-device-monitor: Passed 1043 byte to netlink monitor
 sda: The log level is changed to 'debug' while processing device (SEQNUM=2007906, ACTION=change)
 sda: /usr/lib/udev/rules.d/56-multipath.rules:34 Importing properties from results of '/sbin/multipath -u sda'
 sda: Starting '/sbin/multipath -u sda'
 Successfully forked off '(spawn)' as PID 409333.
 sda: '/sbin/multipath -u sda'(out) 'DM_MULTIPATH_DEVICE_PATH="0"'
 sda: Process '/sbin/multipath -u sda' succeeded.
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:63 Importing properties from results of builtin command 'usb_id'
 3-1.4.4:1.0: if_class:8 protocol:6
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:68 LINK 'disk/by-id/usb-Generic_MassStorageClass_000000002958-0:0'
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:90 Importing properties from results of builtin command 'path_id'
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:92 LINK 'disk/by-path/pci-0000:00:14.0-usb-0:1.4.4:1.0-scsi-0:0:0:0'
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:110 Importing properties from results of builtin command 'blkid'
 sda: Failed to open block device /dev/sda, ignoring: No such device or address
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:127 LINK 'disk/by-diskseq/10'
 sda: Handling device node '/dev/sda', devnum=b8:0
 sda: sd-device: Created db file '/run/udev/data/b8:0' for '/devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1.4/3-1.4.4/3-1.4.4:1.0/host0/target0:0:0/0:0:0:0/block/sda'
 sda: Adding watch on '/dev/sda'
 sda: Device processed (SEQNUM=2007906, ACTION=change)
 sda: sd-device-monitor: Passed 1043 byte to netlink monitor
 sda: The log level is changed to 'debug' while processing device (SEQNUM=2007907, ACTION=change)
 sda: /usr/lib/udev/rules.d/56-multipath.rules:34 Importing properties from results of '/sbin/multipath -u sda'
 sda: Starting '/sbin/multipath -u sda'
 Successfully forked off '(spawn)' as PID 409334.
 sda: '/sbin/multipath -u sda'(out) 'DM_MULTIPATH_DEVICE_PATH="0"'
 sda: Process '/sbin/multipath -u sda' succeeded.
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:63 Importing properties from results of builtin command 'usb_id'
 3-1.4.4:1.0: if_class:8 protocol:6
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:68 LINK 'disk/by-id/usb-Generic_MassStorageClass_000000002958-0:0'
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:90 Importing properties from results of builtin command 'path_id'
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:92 LINK 'disk/by-path/pci-0000:00:14.0-usb-0:1.4.4:1.0-scsi-0:0:0:0'
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:110 Importing properties from results of builtin command 'blkid'
 sda: Failed to open block device /dev/sda, ignoring: No such device or address
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:127 LINK 'disk/by-diskseq/10'
 sda: Handling device node '/dev/sda', devnum=b8:0
 sda: sd-device: Created db file '/run/udev/data/b8:0' for '/devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1.4/3-1.4.4/3-1.4.4:1.0/host0/target0:0:0/0:0:0:0/block/sda'
 sda: Adding watch on '/dev/sda'
 sda: Device processed (SEQNUM=2007907, ACTION=change)
 sda: sd-device-monitor: Passed 1043 byte to netlink monitor
 sda: The log level is changed to 'debug' while processing device (SEQNUM=2007908, ACTION=change)
 sda: /usr/lib/udev/rules.d/56-multipath.rules:34 Importing properties from results of '/sbin/multipath -u sda'
 sda: Starting '/sbin/multipath -u sda'
 Successfully forked off '(spawn)' as PID 409335.
 sda: '/sbin/multipath -u sda'(out) 'DM_MULTIPATH_DEVICE_PATH="0"'
 sda: Process '/sbin/multipath -u sda' succeeded.
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:63 Importing properties from results of builtin command 'usb_id'
 3-1.4.4:1.0: if_class:8 protocol:6
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:68 LINK 'disk/by-id/usb-Generic_MassStorageClass_000000002958-0:0'
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:90 Importing properties from results of builtin command 'path_id'
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:92 LINK 'disk/by-path/pci-0000:00:14.0-usb-0:1.4.4:1.0-scsi-0:0:0:0'
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:110 Importing properties from results of builtin command 'blkid'
 sda: Failed to open block device /dev/sda, ignoring: No such device or address
 sda: /usr/lib/udev/rules.d/60-persistent-storage.rules:127 LINK 'disk/by-diskseq/10'
 sda: Handling device node '/dev/sda', devnum=b8:0
 sda: sd-device: Created db file '/run/udev/data/b8:0' for '/devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1.4/3-1.4.4/3-1.4.4:1.0/host0/target0:0:0/0:0:0:0/block/sda'
 sda: Adding watch on '/dev/sda'
 sda: Device processed (SEQNUM=2007908, ACTION=change)
 sda: sd-device-monitor: Passed 1043 byte to netlink monitor
```

**Comment by yuwata** [comment] 2022-10-23 06:02
Thank you for the log, and sorry for the late response.

Could you try to comment out the line about DISKSEQ in 60-persistent-storage.rules added by https://github.com/systemd/systemd/commit/0d08db7f89ee665a9dcb6dd66c1f9e203192e8ec ?

**Comment by yuwata** [comment] 2022-10-23 06:02
Also, please show the result of `udevadm info /dev/sda` and `udevadm info --attribute-walk /dev/sda`?

**Comment by yuwata** [comment] 2022-10-25 08:48
From #25021, the issue seems to be caused by continuous media change event from kernel. See https://github.com/systemd/systemd/issues/25021#issuecomment-1290204405.

Could you also provide the result of `udevadm monitor -p` ?

**Comment by yuwata** [comment] 2022-10-26 03:02
This should be a duplicate of #25021, which is already closed. Closing this also.

**Closed as completed by yuwata** 2022-10-26 03:02 UTC
Labels: udev, not-our-bug, needs-reporter-feedback ❓
