### ISSUE TITLE
[238] systemd-logind never unregisters any sessions

### ISSUE THREAD

**Issue by rpodgorny** [systemd/systemd#8453] opened 2018-03-14 13:01 UTC
### Submission type

after upgrading to 238 (on arch linux), the number of sessions only rises even thou users are logged off normally.

### systemd version the issue has been seen with

238

### Used distribution

arch linux

### In case of bug report: Expected behaviour you didn't see

> [radek@pupik ~]$ loginctl|grep radek|wc -l
22
[radek@pupik ~]$ ssh localhost 'uname -a'; ssh localhost 'uname -a'; ssh localhost 'uname -a'
Linux pupik 4.15.7-1-ARCH #1 SMP PREEMPT Wed Feb 28 19:01:57 UTC 2018 x86_64 GNU/Linux
Linux pupik 4.15.7-1-ARCH #1 SMP PREEMPT Wed Feb 28 19:01:57 UTC 2018 x86_64 GNU/Linux
Linux pupik 4.15.7-1-ARCH #1 SMP PREEMPT Wed Feb 28 19:01:57 UTC 2018 x86_64 GNU/Linux
[radek@pupik ~]$ loginctl|grep radek|wc -l
22

### In case of bug report: Unexpected behaviour you saw

> [radek@pupik ~]$ loginctl|grep radek|wc -l
22
[radek@pupik ~]$ ssh localhost 'uname -a'; ssh localhost 'uname -a'; ssh localhost 'uname -a'
Linux pupik 4.15.7-1-ARCH #1 SMP PREEMPT Wed Feb 28 19:01:57 UTC 2018 x86_64 GNU/Linux
Linux pupik 4.15.7-1-ARCH #1 SMP PREEMPT Wed Feb 28 19:01:57 UTC 2018 x86_64 GNU/Linux
Linux pupik 4.15.7-1-ARCH #1 SMP PREEMPT Wed Feb 28 19:01:57 UTC 2018 x86_64 GNU/Linux
[radek@pupik ~]$ loginctl|grep radek|wc -l
25

### In case of bug report: Steps to reproduce the problem

...se above

...maybe this is somehow connected to https://github.com/systemd/systemd/issues/8431

**Comment by poettering** [comment] 2018-03-20 07:32
Do you see the matching slice units around too? i.e. "systemctl --unit=slice", does it show a slice for each session?

**Comment by rpodgorny** [comment] 2018-03-20 09:45
systemctl: unrecognized option '--unit=slice'

...but this may help you:

> sudo systemctl |grep slice |grep incoming
user-1013.slice

so just one slice, then?

> sudo loginctl |grep incoming|wc -l
8190

...but many sessions...

> ps aux|grep incoming|wc -l
6

...but not really that many processes.

(incoming is the user we use for the logins)

**Comment by poettering** [comment] 2018-08-08 14:53
Probably a duplicate of #8015. Let's close this one, and track this in #8015.

**Closed as completed by poettering** 2018-08-08 14:53 UTC
Labels: login, needs-reporter-feedback ❓, duplicate
