### ISSUE TITLE
Allow dropins with precedence lower than the main configuration file

### ISSUE THREAD

**Issue by fsateler** [systemd/systemd#2121] opened 2015-12-08 15:27 UTC
A vendor configuration snippet should be overriden in the main file. For example, a distro might want to default to `Storage=volatile` via a snippet in `/usr/lib/journald.conf.d/`. If the admin decides to change that setting, it should be sufficient to edit `/etc/systemd/journald.conf`. Currently, the vendor snippet is loaded after the main configuration file, thus overriding the admin changes.

Configuration files should have prefix-dependent order: load all by vendor first, then all by admin, to make sure admin changes are respected.

**Comment by poettering** [comment] 2015-12-23 23:53
Drop-ins are for for admins extending vendor configuration. They are not intended for vendors, because vendors can change the main config file in /usr/lib directly. In you specific example the vendor should edit /usr/lib/jounald.conf itself, if he doesn't want to patch the binary anyway.

The main configuration files follow the usual logic, that /etc overrides /run and /usr. And so do the drop-in files, since /etc/systemd/journald.conf.d/foo.conf actually overrides /usr/lib/systemd/journald.conf.d/foo.conf. However, drop-ins always override main configuration, and that's by design and purpose: they are extensions to the main config file. And that's documented that way.

Or in other words: /usr/lib/journald.conf.d/ support only exists for completeness, distros shouldn't really use it, but rather use /usr/lib/journald.conf itself.

**Comment by mbiebl** [comment] 2015-12-24 00:03
Let me quote the man page here (man systemd-system.conf):

"When packages need to customize the configuration, they can install configuration snippets in /lib/systemd/*.conf.d/."

**Comment by fsateler** [comment] 2015-12-24 03:45
> They are not intended for vendors, because vendors can change the main config file in /usr/lib directly

There is no /usr/lib/main.conf, and it would be masked because by default an all-comments /etc/main.conf is shipped.

I understand the logic being used. My claim is that, for key-value configuration files, it is not appropriate. A drop-in overriding a file in the same dir, is totally fine (and I also think it is better than the converse). 

The current options for downstreams or spins to change a default are: patch the source, or be a source of confusion for users.

**Comment by fbuihuu** [comment] 2018-11-09 17:03
Let me re-open this issue as I think there's indeed something missing...

So basically the fact that all dropins (wherever they're located) overrides the values defined by users in the main config file is problematic as it's the only way for downstream or packages to customize the main conf sanely. At least this is clearly stated in the man pages.

One use case previously given is the possibility to have various coredump handlers  shipped via different packages, including systemd-coredump. It's not appropriate to leave DefaultLimitCORE=infinity for some of them or if no handler is installed at all.

IIUC the way to handle this case would be that each package would ship a dropin containing the appropriate value of DefaultLimitCORE= for that specific handler. However it must not overwrite any preference that sysadmin would have set in the main config file (/etc/systemd/system.conf).

This basically means that dropins are mostly useless for packages which sounds like a pity since it seems that they're designed primarily for this purpose.

Perhaps a simple way to address this might be to convert a main config file into a dropin.

In practice that would mean that instead of shipping (for example) system.conf in /etc/systemd, it would be shipped in /etc/systemd/system.conf.d/20-default.conf and PID1 would stop parsing /etc/systemd/system.conf.

 I think that would simplify the logic considerably since we would get rid of the special case of the main conf file and how dropins should overload it.

Now users probably expects to find and use a main config file. But that could be simply addressed by making the main conf file a symlink torwads its dropin replacement, something like:

 ```
ls -l /etc/systemd/system.conf
 /etc/systemd/system.conf -> system.conf.d/20-defaults.conf
```

WDYT ?

**Comment by poettering** [comment] 2018-11-09 17:45
> At least this is clearly stated in the man pages.

It is? Where? it says nothing about downstreams or packages, actually?

**Comment by poettering** [comment] 2018-11-09 17:47
> This basically means that dropins are mostly useless for packages which sounds like a pity since it seems that they're designed primarily for this purpose.

actually no, they weren't. When we added them to unit files we did that so that admins could extend unit files without having to replace them wholesale. That is and was their primary usecase. This is made very visible in "systemctl edit" which by default creates them, and only on "--full" overrides them wholesale

**Comment by poettering** [comment] 2018-11-09 17:48
quite frankly, the config files we ship are examples only and fully redundant. they don't have to exist at all. please just remove them if you don't want them. there's no need to package all the stuff we ship upstream

**Comment by poettering** [comment] 2018-11-09 17:52
quite frankly, i am not sure such corner cases really matter that much. I am not sure yet-another-symlink orgy helps anyone, it just makes things even more complex (and it's complex enough already, we had to add systemctl edit and systemctl cat to keep things managable) and I am not sure changing behaviour in general would be beneficial in this case, it just would break compat once more...

I find the usecase not overly convincing. Downstreams should figure out whether they want coredumping handled by systemd or by something else.

Moreover, I think it's not even wrong of alternative coredump handlers override admin behaviour if they cannot work otherwise. I mean, the admin can still override that too, by dropping a higher numbered drop-in in...

**Comment by boucman** [comment] 2018-11-09 21:00
I can add another usecase, it's when your distro is not provided by a vendor but by vendorS

that's the case for yocto, where a package is built by taking a recipe provided by yocto core (the systemd recipe) and then patching it with various addons (CPU provider, board provider, final customer...)

The normal way to do that (for other recipes than systemd) is to patch or just overwrite the lower layer's config files, but since systemd provides drop-ins, it would be really nice to use that

A bit of a corner-case, but I think it's worth mentionning here..

**Comment by fbuihuu** [comment] 2018-11-12 08:02
> When we added them to unit files we did that so that admins could extend unit files without having to replace them wholesale. That is and was their primary usecase.

I see but generalizing the logic to configuration files doesn't seem to work well as this case is pretty the opposite of the unit file one: in this case the main config file is supposed to be written by the user and should have precedence over any drop-ins that packages could ship.

**Comment by fbuihuu** [comment] 2018-11-12 08:15
> quite frankly, the config files we ship are examples only and fully redundant. they don't have to exist at all. please just remove them if you don't want them. there's no need to package all the stuff we ship upstream

Sure but users are used to put their preferences in main config files, not via a drop-in. And until we consider the main config file  and drop-ins different, it won't be usable by downstream. So it seems that they're pretty useless.

**Comment by fbuihuu** [comment] 2018-11-12 08:21
> quite frankly, i am not sure such corner cases really matter that much. I am not sure yet-another-symlink orgy helps anyone, it just makes things even more complex (and it's complex enough already, we had to add systemctl edit and systemctl cat to keep things managable)

Well supporting conf files via drop-ins only seems a simplification since we don't have to deal with the main conf file anymore and how it can be overridden by downstream packages.

**Comment by fbuihuu** [comment] 2020-05-11 12:24
@keszybz @poettering ping

**Comment by neotinker** [comment] 2020-08-24 16:12
I would agree that /etc/systemd/system.conf is currently rendered somewhat pointless since it only contains comments by default and is overridden by everything (ie. all drop in files in /etc and /usr/lib/systemd)

I don't think that is what most user expect.

I believe most user would expect that files in /etc (system.conf included) would override vendor provided files in /usr/lib/systemd. Drop in files in /etc/systemd/system.conf.d/ would still override /etc/systemd/system.conf since they would both be provided by the local administrator.

The method recommended in the man page of creating a symbolic link to /dev/null in /etc/ with the same name as a vendor provided file in order to disable a vendor provided file seems unnecessarily complicated. Especially in cases where a vendor slips in a new file of which the local administrator may be unaware.

**Comment by keszybz** [comment] 2020-08-24 19:23
If a downstream needs to ship drop-ins in /usr/lib, they can just tell users to use drop-ins with higher numbers for local configuration.
1. in /etc/systemd/foo.conf, say that those are example values, and overrides should be placed in /etc/systemd/foo.conf.d/50-local.conf or higher-numbered file,
2. add /etc/systemd/foo.conf.d/50-local.conf that is commented out and says that this local modifications can go there
3. add /usr/lib/systemd/foo.conf.d/00-49-vendor.conf as needed.

I don't think this is something we need to handle upstream. Different downstreams need different schemes.

**Comment by fbuihuu** [comment] 2020-08-25 07:25
@keszybz let me repeat the issue: most sysadmins are used to putting their settings in main config files. It's been a common and well established practice since... well dunno ;) and currently I don't see any use case that would justify to change this.

Is there any valid use case for letting drop-ins shipped in /usr/lib overrides settings in /etc/systemd/foo.conf ?

And the fact that it's well established is the reason why downstream can't ship any drop-ins in /usr/lib in order to change the defaults otherwise that could override any existing customization already made in /etc/systemd/foo.conf.

Again I don't really see any reason for upstream to choose this behavior.

The same concerns also apply to unit files BTW - sysadmins need to make sure to overwrite the main unit file and all drop-ins that might exist in /usr/lib. And this still has the same drawbacks we saw previously (downstream can't add drop-ins later without risking to break sysadmins redefinitions).

**Comment by keszybz** [comment] 2020-08-25 07:39
Current scheme is that the sorting order of dropins is the same independent of the directory. This makes the whole scheme relatively simple. In hindsight it would probably have been better to let dropins with certain names sort earlier than the main configuration file (e.g. anything starting with `_`). Not sure if we can make something like this in a backwards-compatible way.

**Comment by fbuihuu** [comment] 2020-08-25 07:47
> Current scheme is that the sorting order of dropins is the same independent of the directory. This makes the whole scheme relatively simple.

It seems that you're ignoring the point here... the fact that it's relatively simple isn't relevant here because it breaks users' expectations. We already experimented this and every time a user wants to redefine a setting, he chooses to edit the main config file and then complains it doesn't work because a drop-in is shipped by the distro that redefines the same setting.

Again can you please provide a use case that would justify the current behavior ?

**Comment by keszybz** [comment] 2020-08-25 08:25
Other distro don't seem to have this problem. For example, I have never heard this discussed in Fedora. This is at least in part because most distros don't play so many games with dropins.

Current scheme was designed to allow overrides, and not to build configuration out of tiny bits. If your users are confused by this, then just document what needs to be done (https://github.com/systemd/systemd/issues/2121#issuecomment-679318731).

**Comment by fbuihuu** [comment] 2020-08-25 10:19
It would be interesting to know what other distros think indeed but @fsateler reported the issue initially and this was confirmed by another distro (openSUSE) though. Someone else also provided a use case with Yocto in a previous comment.

Also I'm assuming now that there's no sane use case for letting drop-ins in /usr/lib override settings in main config files so really the current behavior doesn't really make sense to me.

It's not about building configuration out of tiny bits, it's about overriding upstream defaults in a well defined place (without the need to patch and rebuild systemd) so the divergence with upstream can easily be reviewed and even masked to restore the upstream defaults for example.

And to quote systemd-system.conf man page one more time:

>        When packages need to customize the configuration, they can install configuration snippets in
>        /usr/lib/systemd/*.conf.d/ or /usr/local/lib/systemd/*.conf.d/.

So that's definitively a correct approach.

**Comment by keszybz** [comment] 2021-02-17 16:56
Based on the discussion in #18347, the verdict is CANTFIX. Generally the answer is to encourage users to use dropins for their config overrides.

**Comment by fbuihuu** [comment] 2021-02-17 17:51
Then it would make sense to stop shipping main config files and clearly state this in the docs. But it would be still too late anyway, as I said already several times tweaking the main config files (instead of using a drop-ins) was, is and will remain a very common practice.

**Comment by keszybz** [comment] 2021-02-18 11:45
> tweaking the main config files (instead of using a drop-ins) was, is and will remain a very common practice.

Yeah, but it's only a problem when three conditions coincide: the user edits the main file, *and* there are vendor drop-ins, *and* they are in conflict (it's OK if they don't touch the same setting). This can certainly happen, but it's not that likely. And in fact, if you start combining random config changes from admin and vendor config, chances are that something will go wrong anyway. After all, settings are not entirely orthogonal.

**Comment by fbuihuu** [comment] 2021-02-18 14:28
The fact that it's likely or not doesn't matter IMHO. We need a mechanism which works in all cases safely and that's not the case currently so drop-ins for main configuration files are not usable by downstream (or by packages to use the documentation terminology). And that's a pity because it could have been simply addressed.

I don't really see anything wrong if some of the upstream defaults don't fit the vendor use cases. And in their turn, some of the downstream custom settings need to be adapted to cope with some of the user's system specificity.

But anyway anything shipped in /usr that unconditionally override something in /etc is simply wrong.

**Comment by keszybz** [comment] 2023-03-30 08:00
Let's reopen this. Enough use cases have popped up.

**Comment by fbuihuu** [comment] 2023-04-05 13:12
> Let's reopen this. Enough use cases have popped up.

Thanks, see https://github.com/systemd/systemd/pull/27152 for the simple approach consisting in reading main conf files via symlink drop-ins.

**Comment by YHNdnzj** [comment] 2023-09-08 15:21
Implemented in https://github.com/systemd/systemd/pull/29113.

**Closed as completed by YHNdnzj** 2023-09-08 15:21 UTC
Labels: pid1

**Comment by fbuihuu** [comment] 2023-09-11 09:06
> Implemented in #29113.

Could you explain how exactly ?

**Comment by YHNdnzj** [comment] 2023-09-11 09:32
> > Implemented in #29113.
> 
> Could you explain how exactly ?

Hmm, I don't really understand what you mean 🤔. Are you asking me to additionally clarify how this is achieved in this issue, or you think this is not yet addressed?

**Comment by YHNdnzj** [comment] 2023-09-11 09:39
In the latter case (maybe you think I've missed something), feel free to reopen this.

**Comment by fbuihuu** [comment] 2023-09-11 13:05
How does https://github.com/systemd/systemd/pull/29113 ensure that drop-ins shipped by downstream in /usr won't overwrite sysadmin settings written in main config files in /etc/systemd ?

**Comment by YHNdnzj** [comment] 2023-09-11 14:21
> How does #29113 ensure that drop-ins shipped by downstream in /usr won't overwrite sysadmin settings written in main config files in /etc/systemd ?

The original request was not about "ensuring" that though? The PR allows distros to symlink main config into the drop-in dir, so that it will be parsed later, and IIUC that's what you asked?

**Comment by fbuihuu** [comment] 2023-09-11 15:45
> The original request was not about "ensuring" that though?

It was, please see $SUBJECT

**Comment by YHNdnzj** [comment] 2023-09-12 09:11
> > The original request was not about "ensuring" that though?
> 
> It was, please see $SUBJECT

I wouldn't interpret "allow" as "ensure" though? Like I said, distros can now provide symlink to main config file in the drop-in dir. Or do you want that part to be upstreamed too?

**Comment by fbuihuu** [comment] 2023-09-12 12:53
> Like I said, distros can now provide symlink to main config file in the drop-in dir

That was already the case before https://github.com/systemd/systemd/pull/29113. The optimization implemented by this PR is transparent from users POV and the behavior remains unchanged.
