### ISSUE TITLE
ipv6 router advertisement processing logic seems to be broken in v249 - keeps losing ipv6 address

### ISSUE THREAD

**Issue by rpodgorny** [systemd/systemd#20357] opened 2021-07-31 22:23 UTC
**systemd version the issue has been seen with**
 > 249.2

**Used distribution**
 > arch linux

**Linux kernel version used** (`uname -a`)
 > `Linux ruprt 5.12.13-arch1-1-beacon #1 SMP PREEMPT Tue, 13 Jul 2021 07:40:47 +0000 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x64_64

**Expected behaviour you didn't see**
 > stable ipv6 address after slaac configuration

**Unexpected behaviour you saw**
 > dropping ipv6 address on regular basis

after upgrading to systemd 249, i keep getting ipv6 connection problems. after some investigation, i've come to a conclusion there has to be something wrong with how systemd handles ipv6 router advertisements. when router advertisement packet arrives on a newly started interface (managed by systemd-networkd) it gets its ipv6 configured correctly. but as soon as the second ra packet arrives some time later, ipv6 is DEconfigured. the third packet "fixes" ipv6 again, the fourth makes it lose the address again and so on and so on. the tcpdump listing of the packets shows no difference (=they are all identical).

downgrading to systemd v248 fixes the problem (meaning each new ra packet just resets the preffered/valid timers etc. but keeps the address).

for testing purposes, i've set the validity times and retransmissions to shorter values but i see the same behaviour for "standard" intervals.

also, the interface in question is openvpn tap device but that should make no difference.

feel free to ask for more info, i'll try my best to get it...

**Comment by yuwata** [comment] 2021-08-04 03:55
This should be already fixed by 2d302d88e4dfd48b18486c5ce2c7dfeb229a1b0a, and duplicate of #20245. Closing.

**Closed as completed by yuwata** 2021-08-04 03:55 UTC
Labels: network
