### ISSUE TITLE
resolved in split setup fails query for lack of dnssec with dnssec disabled.

### ISSUE THREAD

**Issue by kevincox** [systemd/systemd#19359] opened 2021-04-19 20:20 UTC
**systemd version the issue has been seen with**
systemd 247 (247)

**Used distribution**
NixOS

**Linux kernel version used** (`uname -a`)
`Linux kevinidea 5.10.29 #1-NixOS SMP Sat Apr 10 11:36:11 UTC 2021 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
x86_64

**Expected behaviour you didn't see**
Disabling DNSSec prevented DNSSec failures.

**Unexpected behaviour you saw**
DNSSec failures. It appears that even though DNSSec is disabled for the relevant interface (and it is being used in some way because the response is different than when that VPN is not connected) the query is failing due to a DNSSec error.

**Steps to reproduce the problem**
<pre><b>Global</b>
         Protocols: -LLMNR +mDNS +DNSOverTLS DNSSEC=yes/unsupported                                            
  resolv.conf mode: stub                                                                                       
Current DNS Server: 1.1.1.1#cloudflare-dns.com                                                                 
       DNS Servers: 1.0.0.1#cloudflare-dns.com 1.1.1.1#cloudflare-dns.com 8.8.4.4#dns.google 8.8.8.8#dns.google

<b>Link 2 (enp0s20u1u3)</b>
    Current Scopes: DNS mDNS/IPv4 mDNS/IPv6                                    
         Protocols: +DefaultRoute +LLMNR +mDNS +DNSOverTLS DNSSEC=yes/supported
Current DNS Server: 1.1.1.1                                                    
       DNS Servers: 1.1.1.1 8.8.8.8 2001:4860:4860::8888 2001:4860:4860::8844  

<b>Link 3 (wls1)</b>
    Current Scopes: DNS mDNS/IPv4 mDNS/IPv6                                    
         Protocols: +DefaultRoute +LLMNR +mDNS +DNSOverTLS DNSSEC=yes/supported
Current DNS Server: 1.1.1.1                                                    
       DNS Servers: 1.1.1.1 8.8.8.8 2001:4860:4860::8888 2001:4860:4860::8844  

<b>Link 13 (tun0)</b>
    Current Scopes: DNS                                                         
         Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 10.0.0.1                                                    
       DNS Servers: 10.0.0.1                                                    
        DNS Domain: dev.example.com us-west-2.compute.internal </pre>

<pre><span style="background-color:#2E3436"><font color="#8D9197">%</font></span><span style="background-color:#2E3436"><b> resolvectl query something.dev.example.com</b></span>
<font color="#FF7474"><b>something.dev.example.com: resolve call failed: DNSSEC validation failed: incompatible-server</b></font>
</pre>

**Additional program output to the terminal or log subsystem illustrating the issue**

When not connected to the VPN (records are not available publicly).

<pre><span style="background-color:#2E3436"><font color="#8D9197">%</font></span><span style="background-color:#2E3436"><b> resolvectl                               </b></span>
<b>Global</b>
         Protocols: -LLMNR +mDNS +DNSOverTLS DNSSEC=yes/supported                                              
  resolv.conf mode: stub                                                                                       
Current DNS Server: 1.1.1.1#cloudflare-dns.com                                                                 
       DNS Servers: 1.0.0.1#cloudflare-dns.com 1.1.1.1#cloudflare-dns.com 8.8.4.4#dns.google 8.8.8.8#dns.google

<b>Link 2 (enp0s20u1u3)</b>
    Current Scopes: DNS mDNS/IPv4 mDNS/IPv6                                    
         Protocols: +DefaultRoute +LLMNR +mDNS +DNSOverTLS DNSSEC=yes/supported
Current DNS Server: 1.1.1.1                                                    
       DNS Servers: 1.1.1.1 8.8.8.8 2001:4860:4860::8888 2001:4860:4860::8844  

<b>Link 3 (wls1)</b>
    Current Scopes: DNS mDNS/IPv4 mDNS/IPv6                                    
         Protocols: +DefaultRoute +LLMNR +mDNS +DNSOverTLS DNSSEC=yes/supported
Current DNS Server: 1.1.1.1                                                    
       DNS Servers: 1.1.1.1 8.8.8.8 2001:4860:4860::8888 2001:4860:4860::8844  
</pre>

<pre><span style="background-color:#2E3436"><font color="#8D9197">%</font></span><span style="background-color:#2E3436"><b> resolvectl query something.dev.example.com</b></span>
<font color="#FF7474"><b>something.dev.example.com: resolve call failed: DNSSEC validation failed: no-signature</b></font>
</pre>

**Comment by kevincox** [comment] 2021-04-19 20:25
A workaround is `DNSSEC=allow-downgrade`.

**Comment by poettering** [comment] 2021-04-19 20:26
Please upgrade to v248, and report back if the problem still exists.

**Comment by kevincox** [comment] 2021-04-21 18:45
This is probably a duplicate of https://github.com/systemd/systemd/issues/18821

**Comment by poettering** [comment] 2021-04-27 19:48
Let's close as duplicate of #18821

**Closed as completed by poettering** 2021-04-27 19:48 UTC
Labels: resolve, duplicate
