### ISSUE TITLE
systemd-resolved: allow to enable cache for local resolver address

### ISSUE THREAD

**Issue by mikken** [systemd/systemd#8346] opened 2018-03-03 22:04 UTC
### Submission type

 - Request for enhancement (RFE)

### systemd version the issue has been seen with

> 237

Man entry for `Cache=` in `resolved.conf`:
```
Cache=
Takes a boolean argument. If "yes" (the default), resolving a domain name which already got queried earlier will return
the previous result as long as it is still valid, and thus does not result in a new network request. Be aware that turning
off caching comes at a performance penalty, which is particularly high when DNSSEC is used.

Note that caching is turned off implicitly if the configured DNS server is on a host-local IP address (such as 127.0.0.1
or ::1), in order to avoid duplicate local caching.

```

I'm running `Unbound` locally as it has some features that `systemd-resolved` in missing at the time.
If I have cache disabled in Unbound, there's currently no way to make `systemd-resolved` cache entries.

Please implement something like `Cache=always`.

**Comment by poettering** [comment] 2018-03-08 20:07
Duplicate of #4480

**Closed as completed** 2018-03-08 20:07 UTC
Labels: RFE 🎁, resolve, duplicate
