### ISSUE TITLE
shim, systemd-boot, MOK-signed dkms modules and kernel lockdown mode : Failed to start Load kernel modules

### ISSUE THREAD

**Issue by RushingAlien** [systemd/systemd#29166] opened 2023-09-12 02:45 UTC
### systemd version the issue has been seen with

254.2

### Used distribution

Arch Linux

### Linux kernel version used

6.5.2-arch1-1

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

systemd-boot causes kernel to not be bale preload MOK-signed dkms modules in lockdown mode, not a problem in grub

### Unexpected behaviour you saw

systemd-boot to preload MOK-singed dkms modules successfully, in grub, this is no problem

### Steps to reproduce the problem

1. Use MOK-signed systemd-boot with shim
2. Sign kernel with said MOK
3. put MOK in `/var/lib/dkms/mok.key` so dkms will automatically sign it
4. install a dkms module
5. verify dkms module signature via `modinfo`
6. add `lsm=landlock,lockdown,yama,integrity,apparmor,bpf lockdown=integrity` to kernel cmdline 

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
------------ Tue Sep 12 09:30:52 WIB 2023 ------------
[FAILED] Failed to start Load Kernel Modules.
[FAILED] Failed to start Load Kernel Modules.
[FAILED] Failed to start Load Kernel Modules.
[  OK  ] Finished Tell Plymouth To Write Out Runtime Data.
         Mounting Arbitrary Executable File Formats File System...
[  OK  ] Mounted Arbitrary Executable File Formats File System.
[  OK  ] Finished Update Boot Loader Random Seed.
[  OK  ] Finished Set Up Additional Binary Formats.
[  OK  ] Finished Create Volatile Files and Directories.
         Starting Userspace Out-Of-Memory (OOM) Killer...
         Starting Network Name Resolution...
         Starting Network Time Synchronization...
         Starting Record System Boot/Shutdown in UTMP...
[  OK  ] Finished Record System Boot/Shutdown in UTMP.
[  OK  ] Started Network Time Synchronization.
[  OK  ] Reached target System Time Set.
[  OK  ] Started Userspace Out-Of-Memory (OOM) Killer.
[  OK  ] Started Network Name Resolution.
[  OK  ] Reached target Host and Network Name Lookups.
[  OK  ] Reached target System Initialization.
[  OK  ] Started Refresh existing PGP keys of archlinux-keyring regularly.
[  OK  ] Started Monthly Btrfs scrub on /.
[  OK  ] Started Discard unused filesystem blocks once a week.
[  OK  ] Started Daily man-db regeneration.
[  OK  ] Started Update the plocate database daily.
[  OK  ] Started Refresh Pacman mirrorlist weekly with Reflector..
[  OK  ] Started Daily verification of password and group files.
[  OK  ] Started Daily Cleanup of Temporary Directories.
[  OK  ] Reached target Timer Units.
[  OK  ] Listening on Avahi mDNS/DNS-SD Stack Activation Socket.
[  OK  ] Listening on CUPS Scheduler.
[  OK  ] Listening on D-Bus System Message Bus Socket.
[  OK  ] Listening on Libvirt local socket.
[  OK  ] Listening on Virtual machine log manager socket.
[  OK  ] Reached target Socket Units.
[  OK  ] Reached target Basic System.
         Starting ASUS Notebook Control...
         Starting Avahi mDNS/DNS-SD Stack...
         Starting Bluetooth service...
         Starting Enable Connectivity-checking...
         Starting Apply cpupower-gui config at boot...
         Starting D-Bus System Message Bus...
         Starting User Login Management...
         Starting Waydroid Container...
[  OK  ] Finished Enable Connectivity-checking.
[  OK  ] Started D-Bus System Message Bus.
         Starting firewalld - dynamic firewall daemon...
[  OK  ] Started Avahi mDNS/DNS-SD Stack.
[  OK  ] Started Bluetooth service.
[  OK  ] Reached target Bluetooth Support.
[  OK  ] Started User Login Management.
         Starting Hostname Service...
         Starting cpupower-gui system helper...
[  OK  ] Started Hostname Service.
[  OK  ] Started cpupower-gui system helper.
[  OK  ] Started Waydroid Container.
         Starting Authorization Manager...
[  OK  ] Started firewalld - dynamic firewall daemon.
[  OK  ] Reached target Preparation for Network.
         Starting Network Manager...
[  OK  ] Started Network Manager.
[  OK  ] Reached target Network.
[  OK  ] Started joycond.
[  OK  ] Started OpenSSH Daemon.
         Starting Permit User Sessions...
[  OK  ] Finished Permit User Sessions.
[  OK  ] Started Authorization Manager.
         Starting Network Manager Script Dispatcher Service...
         Starting GNOME Display Manager...
         Starting Hold until boot process finishes up...
[  OK  ] Started Network Manager Script Dispatcher Service.
         Starting Wireless service...
[  OK  ] Started GNOME Display Manager.
```
```

**Comment by medhefgo** [comment] 2023-09-12 05:51
I highly doubt it's caused by us. There is no mention of MOK variables or config table other than "MokSBState" in grub. All MOK related handling and handover are done by shim itself.

**Comment by poettering** [comment] 2023-09-18 19:26
Please contact your distro for help. This doesn't look like it has anything to do with systemd.

**Comment by poettering** [comment] 2023-09-18 19:26
maybe you are not actually using shim? or shim chainloads the wrong boot loader?

**Comment by poettering** [comment] 2023-10-30 22:58
Closing, as this doesn't look like a systemd issue, as per earlier comments.

**Closed as completed by poettering** 2023-10-30 22:58 UTC
Labels: bug 🐛, sd-boot/sd-stub/bootctl
