### ISSUE TITLE
networkd: bond created by networkd has a different "MAC behavior" than those created by kernel/ip

### ISSUE THREAD

**Issue by tomty89** [systemd/systemd#3375] opened 2016-05-28 08:02 UTC
### Submission type
- [X] Bug report
- [ ] Request for enhancement (RFE)
### systemd version the issue has been seen with

230
### Used distribution

Arch Linux
### In case of bug report: Expected behaviour you didn't see

When set the master of a NIC as a (balance-rr) bond created by networkd (.netdev), the MAC address of the master/bond should be changed to that of the slave/NIC, like what would happen if the bond is created by the kernel / with `ip`.
### In case of bug report: Unexpected behaviour you saw

When set the master of a NIC as a (balance-rr) bond created by networkd (.netdev), the MAC address on the slave/NIC is changed to that of the master/bond.

(Note: Maybe the behavior seen with the networkd-created bond is correct? And the behavior seen with the kernel-created bond is incorrect and has something to do with #3374?)
### In case of bug report: Steps to reproduce the problem

Preparation:

```
[tom@localhost ~]$ sudo modprobe bonding

[tom@localhost ~]$ sudo ip l add name bond1 type bond

[tom@localhost ~]$ ls /etc/systemd/network/
bond2.netdev
[tom@localhost ~]$ cat /etc/systemd/network/bond2.netdev 
[NetDev]
Name=bond2
Kind=bond
[tom@localhost ~]$ sudo systemctl start systemd-networkd

[tom@localhost ~]$ ip -d l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 promiscuity 0 addrgenmode eui64 
2: enp3s0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff promiscuity 0 addrgenmode eui64 
3: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 32:88:6b:21:84:b4 brd ff:ff:ff:ff:ff:ff promiscuity 0 
    bond mode balance-rr miimon 0 updelay 0 downdelay 0 use_carrier 1 arp_interval 0 arp_validate none arp_all_targets any primary_reselect always fail_over_mac none xmit_hash_policy layer2 resend_igmp 1 num_grat_arp 1 all_slaves_active 0 min_links 0 lp_interval 1 packets_per_slave 1 lacp_rate slow ad_select stable tlb_dynamic_lb 1 addrgenmode eui64 
4: bond1: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 3e:a5:45:df:1d:49 brd ff:ff:ff:ff:ff:ff promiscuity 0 
    bond mode balance-rr miimon 0 updelay 0 downdelay 0 use_carrier 1 arp_interval 0 arp_validate none arp_all_targets any primary_reselect always fail_over_mac none xmit_hash_policy layer2 resend_igmp 1 num_grat_arp 1 all_slaves_active 0 min_links 0 lp_interval 1 packets_per_slave 1 lacp_rate slow ad_select stable tlb_dynamic_lb 1 addrgenmode eui64 
5: bond2: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 8a:8d:fc:6c:89:28 brd ff:ff:ff:ff:ff:ff promiscuity 0 
    bond mode balance-rr miimon 0 updelay 0 downdelay 0 use_carrier 1 arp_interval 0 arp_validate none arp_all_targets any primary_reselect always fail_over_mac none xmit_hash_policy layer2 resend_igmp 1 num_grat_arp 1 all_slaves_active 0 min_links 0 lp_interval 1 packets_per_slave 1 lacp_rate slow ad_select stable tlb_dynamic_lb 1 addrgenmode eui64 
```

Results:

```
[tom@localhost ~]$ ip l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp3s0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff
3: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 32:88:6b:21:84:b4 brd ff:ff:ff:ff:ff:ff
4: bond1: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 3e:a5:45:df:1d:49 brd ff:ff:ff:ff:ff:ff
5: bond2: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 8a:8d:fc:6c:89:28 brd ff:ff:ff:ff:ff:ff

[tom@localhost ~]$ sudo ip l set enp3s0 master bond0
[tom@localhost ~]$ ip l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp3s0: <NO-CARRIER,BROADCAST,MULTICAST,SLAVE,UP> mtu 1500 qdisc fq_codel master bond0 state DOWN mode DEFAULT group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff
3: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff
4: bond1: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 3e:a5:45:df:1d:49 brd ff:ff:ff:ff:ff:ff
5: bond2: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 8a:8d:fc:6c:89:28 brd ff:ff:ff:ff:ff:ff

[tom@localhost ~]$ sudo ip l set enp3s0 master bond1
[tom@localhost ~]$ ip l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp3s0: <NO-CARRIER,BROADCAST,MULTICAST,SLAVE,UP> mtu 1500 qdisc fq_codel master bond1 state DOWN mode DEFAULT group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff
3: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether be:4a:d1:d4:43:8b brd ff:ff:ff:ff:ff:ff
4: bond1: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether ac:22:0b:29:e6:0c brd ff:ff:ff:ff:ff:ff
5: bond2: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 8a:8d:fc:6c:89:28 brd ff:ff:ff:ff:ff:ff

[tom@localhost ~]$ sudo ip l set enp3s0 master bond2
[tom@localhost ~]$ ip l
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp3s0: <NO-CARRIER,BROADCAST,MULTICAST,SLAVE,UP> mtu 1500 qdisc fq_codel master bond2 state DOWN mode DEFAULT group default qlen 1000
    link/ether 8a:8d:fc:6c:89:28 brd ff:ff:ff:ff:ff:ff
3: bond0: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether be:4a:d1:d4:43:8b brd ff:ff:ff:ff:ff:ff
4: bond1: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 9e:8f:9a:38:c9:0c brd ff:ff:ff:ff:ff:ff
5: bond2: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 8a:8d:fc:6c:89:28 brd ff:ff:ff:ff:ff:ff
```

**Comment by ssahani** [comment] 2017-01-17 07:16
Can't reproduce this .

```
$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:42:66:ed brd ff:ff:ff:ff:ff:ff
    inet 10.65.193.131/23 brd 10.65.193.255 scope global dynamic enp0s3
       valid_lft 86297sec preferred_lft 86297sec
    inet6 fe80::a00:27ff:fe42:66ed/64 scope link 
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc fq_codel master bond1 state UP group default qlen 1000
    link/ether be:5b:b2:6e:1c:79 brd ff:ff:ff:ff:ff:ff <================
5: bond1: <BROADCAST,MULTICAST,MASTER> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether be:5b:b2:6e:1c:79 brd ff:ff:ff:ff:ff:ff <================
```

**Comment by jsoriano** [comment] 2017-08-23 10:59
I'm having this behaviour too, with the same configuration, same hardware and same systemd versions but different kernels:
* With CoreOS 1409.7.0 (systemd 233, linux 4.11.11): master interface uses slave MAC address.
* With CoreOS 1465.6.0 (systemd 233, linux 4.12.7): master interface uses a new MAC address and MAC address in slaves is changed to the master one.

**Comment by bgilbert** [comment] 2017-08-25 08:00
Summarizing https://github.com/coreos/bugs/issues/2120#issuecomment-324849860: on CoreOS Container Linux 1409, `bond0` is automatically created by the bonding driver, so networkd will not attempt to configure its MAC address.  CL 1465 configures the bonding driver not to create `bond0` by default, so networkd will set its MAC.

**Comment by poettering** [comment] 2017-09-14 10:02
OK, closing this, as 582faeb461aa0dd01b55bf6c9b1433532fc927d3 should fix this issue for good

**Closed as completed by poettering** 2017-09-14 10:02 UTC
Labels: network

**Comment by luxifer** [comment] 2019-03-14 13:02
From what I see, the `bond2` is fully managed by `systemd-networkd` but the MAC address selection behaviour is not correct. The `bond2` MUST have taken the MAC address of the first enslaved device (here `enp3s0`), instead it applied its own MAC address on `enp3s0`. According to the kernel doc on bonding this is not the correct behaviour https://www.kernel.org/doc/Documentation/networking/bonding.txt:

> 8.  Where does a bonding device get its MAC address from?
> 
> 	When using slave devices that have fixed MAC addresses, or when
> the fail_over_mac option is enabled, the bonding device's MAC address is
> the MAC address of the active slave.
> 
> 	For other configurations, if not explicitly configured (with
> ifconfig or ip link), the MAC address of the bonding device is taken from
> its first slave device.  This MAC address is then passed to all following
> slaves and remains persistent (even if the first slave is removed) until
> the bonding device is brought down or reconfigured.

**Comment by clonejo** [comment] 2019-09-03 15:09
Additionally, the kernel's default behavior to take over the MAC from a slave is not even configurable in .netdev:

from man [systemd.netdev](https://www.freedesktop.org/software/systemd/man/systemd.netdev.html#%5BNetDev%5D%20Section%20Options):

    [NetDev] Section Options
    MACAddress=

        The MAC address to use for the device. For "tun" or "tap" devices,
        setting MACAddress= in the "[NetDev]" section is not supported. Please
        specify it in "[Link]" section of the corresponding systemd.network(5)
        file. If this option is not set, "vlan" devices inherit the MAC address
        of the physical interface. For other kind of netdevs, if this option is
        not set, then MAC address is generated based on the interface name and
        the machine-id(5). 

Is there some other config option I am missing?
