### ISSUE TITLE
Feature request: EmitDNS and DNS attribute

### ISSUE THREAD

**Issue by yifu** [systemd/systemd#21980] opened 2022-01-03 13:22 UTC
Here is my configuration file:
```
[Match]
Name=eth2
Type=ether

[Network]
DHCPServer=yes

[Address]
Address=0.0.0.0/24

[DHCPServer]
DefaultLeaseTimeSec=24h
UplinkInterface=:none
EmitDNS=yes
DNS=10.23.20.82
```

My DNS server is a dnsmasq instance and I would like it to bind to the
eth2 interface. But it's not possible: since the attribute is
`Address=0.0.0.0/24` I cannot know its IP address. So I bind dnsmasq
to another interface (that is 10.23.20.82) which is a tun interface.

Which is not really pleasant. I would like to be able to express my
configuration that way: `DNS=0.0.0.0` which would make the DHCP server
emit the correct IP address to the DHCP client, that is the IP address
of  eth2 interface. Is this a possible evolution of networkd? Does it
make sense?

I would like to know your point of view on this topic. Am I completely
wrong? Does it make sense? Or is there another way to achieve what I
am trying to do?

Regards
Yves

**Comment by yifu** [comment] 2022-01-03 13:27
Mfff. I've just browsed the list of issues, and this issue might be a duplicate of this one: https://github.com/systemd/systemd/issues/15026 . I am not sure. What do you think?

**Comment by yuwata** [comment] 2022-01-03 19:20
We already support `DNS=_link_local` in [IPv6SendRA] section. So, for DHCP server case, supporting e.g. `DNS=_server_address` sounds natural and good for me.

**Comment by yuwata** [comment] 2022-01-03 19:21
And, yeah. This is a duplicate of #15026. Closing.

**Closed as completed by yuwata** 2022-01-03 19:21 UTC
Labels: RFE 🎁, network, duplicate
