### ISSUE TITLE
systemd-journald: very high memory usage

### ISSUE THREAD

**Issue by ialidzhikov** [systemd/systemd#11900] opened 2019-03-05 17:57 UTC
**systemd version the issue has been seen with**
```bash
$ systemctl --version
systemd 238
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT -GNUTLS -ACL +XZ +LZ4 +SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN +PCRE2 default-hierarchy=legacy
```

**Used distribution**
 ```bash
$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2023.4.0
# ...
```

**Expected behaviour you didn't see**
systemd-journald memory usage to be reasonable low.

**Unexpected behaviour you saw**
systemd-journald memory usage grows without bound until the unit is restarted. At the diagram you see that systemd-journald with CoreOS 2023.4.0 used 5.71GiB memory before restart of the unit.
![CoreOS](https://i.imgur.com/QltVEVg.png)
On the other hand, the same config with CoreOS 1855.4.0 has reasonable memory usage - around ~10MiB.
![CoreOS](https://i.imgur.com/rWX45i7.png)

**Steps to reproduce the problem**
1. Create a CoreOS 2023.4.0 node with docker, kubelet, ...
2. Ensure that systemd-journald has a very high memory usage that breaks another components such as kubelet.

**Comment by keszybz** [comment] 2019-03-05 19:22
Looks like a duplicate of #11502. If you can recreate the issue with the latest release (241) please open a new bug.

**Closed as completed by keszybz** 2019-03-05 19:22 UTC

**Comment by ialidzhikov** [comment] 2019-03-05 21:01
Currently we use the latest stable release of CoreOS (2023.4.0 by the time of writing this) and we experience high memory usage from systemd-journald side. 
1. What is the eta of the fix as a stable CoreOS release?
1. What is you proposal for mitigation/temporary solution until `1.` is done?

**Comment by keszybz** [comment] 2019-03-05 21:26
Please take it up with the support channel of your distribution.
