### ISSUE TITLE
ownership issues after upgrade of host

### ISSUE THREAD

**Issue by wsw70** [systemd/systemd#4743] opened 2016-11-26 09:55 UTC
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> systemd 232
> PPA on ubuntu: 232+upstream20161120-0.master

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Ubuntu 16.10, upgraded from 16.04

### In case of bug report: Expected behaviour you didn't see

> containers running 16.04 on host 16.04 were OK. Host was upgraded to 16.10 + systemd PPA. I expected no changes in their behaviour

### In case of bug report: Unexpected behaviour you saw

>Containers still start but show errors (in their own logging, not the host's) accessing some files and directories. An example is  `/root`:

```
root@delug:/tmp# ls /root
ls: cannot open directory '/root': Permission denied

root@delug:/tmp# ls -l /
total 60
drwxr-xr-x   2 root   root    4096 Nov 22 16:38 bin
drwxr-xr-x   2 root   root    4096 Apr 12  2016 boot
drwxr-xr-x   7 root   root     440 Nov 26 10:23 dev
drwxr-xr-x  82 root   root    4096 Nov 26 10:23 etc
drwxr-xr-x   2 root   root    4096 Apr 12  2016 home
drwxr-xr-x   9 root   root    4096 Jul 23 23:23 lib
drwxr-xr-x   2 root   root    4096 Nov 22 16:38 lib64
drwxr-xr-x   2 root   root    4096 Jul 14 14:34 media
drwxr-xr-x   3 root   root    4096 Jul 27 21:16 mnt
drwxr-xr-x   2 root   root    4096 Oct 13 21:11 opt
dr-xr-xr-x 208 nobody nogroup    0 Nov 26 10:23 proc
drwx------  17 nobody nogroup 4096 Nov 25 20:57 root
drwxr-xr-x  12 root   root     440 Nov 26 10:23 run
drwxr-xr-x   2 root   root    4096 Nov 22 16:38 sbin
drwxr-xr-x   2 root   root    4096 Jul 14 14:34 srv
drwxr-xr-x   9 root   root     180 Nov 26 10:23 sys
drwxr-xr-x   4 nobody nogroup 4096 Nov 20 19:40 temp
drwxrwxrwt   7 root   root     140 Nov 26 10:23 tmp
drwxr-xr-x  10 root   root    4096 Jul 14 14:34 usr
drwxr-xr-x  11 root   root    4096 Jul 14 14:34 var

```

It looks like something happened with the mapping of users and rights.

### In case of bug report: Steps to reproduce the problem

> Upgrade from Ubuntu 16.04 to 16.10

**Comment by poettering** [comment] 2016-11-28 20:37
Hmm, I figure this is caused by the fact that we turned on user namespaces by default. /proc, and /sys are hence owned by "nobody", and that's expected.

But the /root thing is surprising. 

Do you have any particular setup for /root? Did you copy files there directly? Or use --bind= on that dir?

**Comment by wsw70** [comment] 2016-11-28 21:10
@poettering  No,  I did not change anything around /root, I used the generic image from debootstrap. This is the case for existing images as week as a band new created (via debootstrap) on the upgraded system  (both host and guest being ubuntu yakkety)

**Comment by poettering** [comment] 2016-11-29 12:13
If you look from outside the container, what is shown as owner of the root dir and of /root of the container?

**Comment by wsw70** [comment] 2016-11-29 12:21
@poettering 

The root directory for a migrated machine (= one which worked fine before the upgrade):

```
root@srv ~# ls -l /var/lib/machines/dev
total 76
drwxr-xr-x  2 1470693376 1470693376 4096 Oct 10 12:35 bin/
drwxr-xr-x  2 1470693376 1470693376 4096 Apr 12  2016 boot/
drwxr-xr-x  4 1470693376 1470693376 4096 Jul 14 14:35 dev/
drwxr-xr-x 59 1470693376 1470693376 4096 Nov 27 19:56 etc/
drwxr-xr-x  2 1470693376 1470693376 4096 Apr 12  2016 home/
drwxr-xr-x 10 1470693376 1470693376 4096 Oct 10 12:27 lib/
drwxr-xr-x  2 1470693376 1470693376 4096 Jul 14 14:35 lib64/
drwxr-xr-x  2 1470693376 1470693376 4096 Jul 14 14:34 media/
drwxr-xr-x  2 1470693376 1470693376 4096 Jul 14 14:34 mnt/
drwxr-xr-x  2 1470693376 1470693376 4096 Jul 14 14:34 opt/
drwxr-xr-x  2 1470693376 1470693376 4096 Apr 12  2016 proc/
drwx------  6 root       root       4096 Nov 23 11:34 root/
drwxr-xr-x  5 1470693376 1470693376 4096 Oct 10 12:27 run/
drwxr-xr-x  2 1470693376 1470693376 4096 Oct 10 12:35 sbin/
drwxr-xr-x  2 1470693376 1470693376 4096 Jul 14 14:34 srv/
drwxr-xr-x  2 1470693376 1470693376 4096 Feb  5  2016 sys/
drwxrwxrwt  2 1470693376 1470693376 4096 Oct 10 12:35 tmp/
drwxr-xr-x 10 1470693376 1470693376 4096 Jul 14 14:34 usr/
drwxr-xr-x 11 1470693376 1470693376 4096 Jul 14 14:34 var/
```

and home for `root`:

```
root@srv ~# ls -la /var/lib/machines/dev/root
total 44
drwx------  6 root       root       4096 Nov 23 11:34 ./
drwxr-xr-x 21 1470693376 1470693376 4096 Jul 14 14:35 ../
drwxr-xr-x  3 root       root       4096 Nov 23 11:02 .ansible/
-rw-------  1 root       root       1844 Nov 23 16:03 .bash_history
-rw-r--r--  1 root       root       3106 Oct 22  2015 .bashrc
drwx------  3 root       root       4096 Oct 10 12:48 .cache/
drwxr-xr-x  2 root       root       4096 Jul 14 15:08 .nano/
-rw-r--r--  1 root       root        148 Aug 17  2015 .profile
-rw-------  1 root       root        165 Oct 10 11:42 .python_history
drwx------  2 root       root       4096 Nov 23 08:29 .ssh/
-rw-------  1 root       root         49 Nov 23 11:34 .Xauthority
```

**Comment by poettering** [comment] 2016-11-29 14:10
hmm, did you ever access that directory from the outside? This is really strange. Normally the whole tree should be owned by the same high UID...

**Comment by wsw70** [comment] 2016-11-29 14:36
No I did not, and neither changed the default rights. This machine (and others which were active at the time of the upgrade) was functional under 229.  The upgrade was done as part of a xenial -> yakkety upgrade (as 229 was the last version in the PPA for xenial).

**Comment by keszybz** [comment] 2017-06-29 00:24
I'll close this, there have been many changes between v232 and current git master. If anyone encounters this again with v234 or later, please reopen.

**Closed as completed by keszybz** 2017-06-29 00:24 UTC
Labels: nspawn, needs-reporter-feedback ❓
