### ISSUE TITLE
Auto configure delegated IPv6 address on interface

### ISSUE THREAD

**Issue by thequailman** [systemd/systemd#14474] opened 2020-01-03 22:38 UTC
**Is your feature request related to a problem? Please describe.**
After configuring IPv6 prefix delegation successfully, the interfaces that are assigned a prefix do not configure an address for the delegated prefix.  This makes configuring DHCPv6 via dnsmasq or similar challenging, as they need an interface address to construct their ranges from.

**Describe the solution you'd like**
Expose a boolean flag to automatically add an address from the delegated prefix to the interface.  It should respect the IPv6Token parameter.

**Describe alternatives you've considered**
Running a script to set these addresses manually before bringing dnsmasq up.

**Comment by yuwata** [comment] 2020-01-08 09:03
@thequailman Could you elaborate more? An example config and an expected result help me.

**Comment by thequailman** [comment] 2020-01-08 13:42
Sure thing, I have enabled IPv6 prefix delegation using networkd 244:

**WAN**
```
[Match]
Name=enp5s0

[Network]
DHCP=yes
IPForward=yes
IPv6AcceptRA=yes

[DHCPv6]
PrefixDelegationHint=::/56
```

**LAN**
```
[Match]
Name=int

[Network]
Address=192.168.129.1/24
IPv6PrefixDelegation=yes
```

The LAN interface correctly receives a prefix:
```
# ip -6 route | grep int
XXXX:XXXX:XXXX:500::/64 dev int metric 1024 pref medium
```
But the interface itself doesn't assign an IP from this prefix:
```
ip -6 addr show dev int
11: int@bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 fe80::92e2:baff:fe36:b7e4/64 scope link 
       valid_lft forever preferred_lft forever
```

This makes configuring a DHCPv6 service like dnsmasq very difficult, as you can't construct a DHCPv6 range without an IPv6 address being assigned.  Ideally, I would like to have this configuration for LAN:

```
[Match]
Name=int

[Network]
Address=192.168.129.1/24
IPv6PrefixDelegation=yes
IPv6PrefixAssign=yes
IPv6Token=::1
```

Configure the interface using the prefix delegation like this:
```
11: int@bridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000
    inet6 XXXX:XXXX:XXXX:500::1/64 scope global dynamic noprefixroute 
       valid_lft 509261sec preferred_lft 509261sec
    inet6 fe80::92e2:baff:fe36:b7e4/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by yuwata** [comment] 2020-01-10 05:26
@thequailman Thank you for the detailed explanation. One more question, are there any documents (RFC?) for this feature?

**Comment by thequailman** [comment] 2020-01-10 12:53
No, I don't think there is a RFC related to this.

**Comment by yuwata** [comment] 2020-01-11 06:11
@ssahani WDYT?

**Comment by mmonaco** [comment] 2020-01-22 20:04
This, along with #13638 is the functionality I'm looking for to replace my wide-dhcp6c config. I thought I was doing something wrong because I wasn't getting addresses assigned to my lan interfaces. How is this supposed to work without auto-assignment? Even though my ISP claims my IPv6 address/prefix should be static, it does change from time to time.

**Comment by software011** [comment] 2020-02-12 16:50
Si tienes problemas para tratar con tu personalidad o conoces a alguien, te recomiendo este enlace [https://sites.google.com/aprendizajesignificativo.org/personalidad-g/p%C3%A1gina-principal](url) el cual cuenta con una redireccion a un articulo donde se explica que es un test de personalidad y como debes orientarte según tu personalidad para la elección de una carrera universitaria.

**Comment by ssahani** [comment] 2020-02-27 12:37
@thequailman https://github.com/systemd/systemd/pull/14956. I am not too sure about the requirement. But Can you test.

**Comment by thequailman** [comment] 2020-02-28 23:59
:+1: that looks great @ssahani.

**Closed as completed** 2020-03-06 16:13 UTC
Labels: RFE 🎁, network

**Comment by sermolenko** [comment] 2020-03-16 01:12
Is it intended to work for dhcpv6-delegated prefixes as well as static ones? #14956 seems to address the issue for prefixes named in [IPV6Prefix] section, but dhcpv6-delegated prefixes from other interfaces are not named there.

**Comment by mmonaco** [comment] 2020-03-25 19:09
Can we re-open this? Right now, as @sermolenko asks, I think this is limited to statically configured `[IPv6Prefix]`'s. However, if we know the prefix ahead of time, it's easy to manually configured the address on the interface too.

The original request was more useful for DHCPv6 acquired prefixes that we don't know ahead of time. (Also, it would be nice if the assigned address honored the `IPv6Token`).

**Comment by ssahani** [comment] 2020-03-29 16:08
@sermolenko @mmonaco I dont have a test env to test it . It will take some effort to create. In the mean time can you please test with https://github.com/systemd/systemd/pull/15259

**Comment by mmonaco** [comment] 2020-03-29 17:40
Will do!

Not to be confused with the new `DHCPv6.WithoutRA` that I just noticed, I did some searching and couldn't find an FR to also disable RAs from delegated prefixes. That might go well with the original request e.g., if we want to pass on prefix info to another system, we might not need networkd to do the RAs. Is there an FR for this that anyone has noticed?

(Aside: I think the documentation and setting names are a bit confusing, they are conflating 1) PD Requests via DHCPv6, 2) Slicing up a delegated PD, and 3) performing RAs. Agree/disagree?)

**Comment by sermolenko** [comment] 2020-03-29 17:44
> 
> 
> @sermolenko @mmonaco I dont have a test env to test it . It will take some effort to create. In the mean time can you please test with #15259
Will test and report back.

**Comment by mmonaco** [comment] 2020-03-29 20:04
Alright, I didn't do too much digging but #15259 appears to cause some breakage. I only added `AssignAcquiredDelegatedPrefix=yes` to one of my N vlan interfaces. The interface did get an address from the delegated prefix *however* the other interfaces were misconfigured. Looking at `route -6` the other interfaces no longer received a route from a slice of the delegated prefix and the interfaces with `AssignAcquiredDelegatedPrefix=yes` received more than one /64 subnet (although not enough to account for each other interface with `IPv6PrefixDelegation=yes`)!

**Comment by ssahani** [comment] 2020-03-29 20:54
>Looking at route -6 the other interfaces no longer received a route from a slice of the delegated prefix and the interfaces with AssignAcquiredDelegatedPrefix=yes received more than one /64 subnet (although not enough to account for each other interface with IPv6PrefixDelegation=yes)!

Thanks for testing out.   It will just assign what is is being sent .  It's called in `dhcp6_pd_prefix_assign`. If you see it just extracts the prefix and other information, generates `eui64`  suffix and adds the address to the link. May be add more printfs there and run in debug mode to see what is the failure actually.

**Comment by sermolenko** [comment] 2020-03-30 05:33
> @sermolenko @mmonaco I dont have a test env to test it . It will take some effort to create. In the mean time can you please test with #15259

Firstly, many thanks for working on it!

I tested your change in my environment. Unfortunately, hits the assert in link->address_messages and dies (then gets restarted by systemd to die again), here is the log (IPs redacted):

```
Mar 29 22:15:33 edge systemd[1]: Stopped Network Service.
Mar 29 22:15:33 edge systemd[1]: systemd-networkd.service: Scheduled restart job, restart counter is at 10.
Mar 29 22:15:33 edge systemd[1]: systemd-networkd.service: Service has no hold-off time, scheduling restart.
Mar 29 22:15:33 edge systemd[1]: systemd-networkd.service: Failed with result 'signal'.
Mar 29 22:15:33 edge systemd[1]: systemd-networkd.service: Main process exited, code=killed, status=6/ABRT
Mar 29 22:15:32 edge systemd-networkd-new-patched[948]: Assertion 'link->address_messages == 0' failed at src/network/networkd-link.c:1029, function link_request_set_routes(). Abortin
Mar 29 22:15:32 edge systemd-networkd-new-patched[948]: ethext0: DHCPv6 address ZZZZ:ZZZ:ZZZZ:ZZ:ZZZZ:ZZZZ:ZZZZ:ZZZZ/128 timeout preferred 206977 valid 206977
Mar 29 22:15:30 edge systemd-networkd-new-patched[948]: ethext0: DHCPv4 address XX.XXX.XXX.XX/23 via GG.GGG.GGG.G
Mar 29 22:15:30 edge systemd-networkd-new-patched[948]: ethext1: Could not enable IP masquerading, ignoring: Operation not supported
Mar 29 22:15:30 edge systemd-networkd-new-patched[948]: ethext2: Could not enable IP masquerading, ignoring: Operation not supported
Mar 29 22:15:30 edge systemd-networkd-new-patched[948]: ethext0: IPv6 successfully enabled
Mar 29 22:15:30 edge systemd-networkd-new-patched[948]: ethext1: IPv6 successfully enabled
Mar 29 22:15:30 edge systemd-networkd-new-patched[948]: ethext2: IPv6 successfully enabled
Mar 29 22:15:30 edge systemd-networkd-new-patched[948]: ethext3: IPv6 successfully enabled
Mar 29 22:15:30 edge networkd-dispatcher[674]: Interface status change detected: ethext1
Mar 29 22:15:30 edge networkd-dispatcher[674]: Interface status change detected: ethext2
Mar 29 22:15:30 edge networkd-dispatcher[674]: Operational State='routable'
Mar 29 22:15:30 edge networkd-dispatcher[674]: Administrative State='initialized'
Mar 29 22:15:30 edge networkd-dispatcher[674]: WAN interface changed, state='routable', IPv4='XX.XXX.XXX.XX YYY.YYY.YYY.Y', IPv6='ZZZZ:ZZZ:ZZZZ:ZZ:ZZZZ:ZZZZ:ZZZZ:ZZZZ'
Mar 29 22:15:30 edge networkd-dispatcher[674]: Interface status change detected: ethext0
Mar 29 22:15:30 edge systemd-networkd-new-patched[948]: ethint0: IPv6 successfully enabled
Mar 29 22:15:30 edge systemd[1]: Started Network Service.
Mar 29 22:15:30 edge systemd-networkd-new-patched[948]: Enumeration completed
Mar 29 22:15:30 edge systemd-networkd-new-patched[948]: ethext0: Gained IPv6LL
Mar 29 22:15:30 edge systemd-networkd-new-patched[948]: ethext1: Gained IPv6LL
Mar 29 22:15:30 edge systemd-networkd-new-patched[948]: ethext2: Gained IPv6LL
Mar 29 22:15:29 edge systemd[1]: Starting Network Service...


```

**Comment by ssahani** [comment] 2020-03-30 05:57
Thank you for testing . I see the `dhcp6_address_handler`  also processes the routes . We dont need it and it also does not decrement the message count. I replaced with `address_handler`.  Please test.  Sorry for this I don't have this env really.

**Comment by sermolenko** [comment] 2020-03-30 08:53
> Thank you for testing . I see the `dhcp6_address_handler` also processes the routes . We dont need it and it also does not decrement the message count. I replaced with `address_handler`. Please test. Sorry for this I don't have this env really.

Completed the testing. No more crashes as far as I can tell, and the address is now properly assigned to the interface. One small hiccup that I noticed is that there are now two entries in the routing table for the delegated prefix (D is delegated prefix, G is upstream gateway):

```
sergey@edge:~$ ip -6 route show
DDDD:DDD:DDDD:DDDD::/64 dev ethext1 proto kernel metric 256 expires 194885sec pref medium
DDDD:DDD:DDDD:DDDD::/64 dev ethext1 metric 1024 pref medium # <- there used to be only this one
fe80::/64 dev ethext1 proto kernel metric 256 pref medium
fe80::/64 dev ethext2 proto kernel metric 256 pref medium
fe80::/64 dev ethext0 proto kernel metric 256 pref medium
default via GGGG::GGG:GGGG:GGGG:GGGG dev ethext0 proto ra metric 1024 expires 1798sec mtu 1500 pref medium
```
While you're at it, one small suggestion - in the man-file description of 'AssignAcquiredDelegatedPrefix', mention which interface it is supposed to be set on - the one acquiring the prefixes from the upstream DHCPv6, or the one sending router advertisements for a delegated prefix. As currently worded, description is open to wide interpretation. Thank you!

**Comment by ssahani** [comment] 2020-03-30 15:07
Thanks for the confirmation and testing out. I have updated the man . Any suggestion is welcome.

**Comment by mmonaco** [comment] 2020-03-31 18:29
Did I do it wrong? Shouldn't `DHCPv6.AssignAcquiredDelegatedPrefix` be set on the same internal interfaces that `Network.IPv6PrefixDelegation` is set on?

**Comment by ssahani** [comment] 2020-03-31 22:27
> Completed the testing. No more crashes as far as I can tell, and the address is now properly assigned to the interface. One small hiccup that I noticed is that there are now two entries in the routing table for the delegated prefix (D is delegated prefix, G is upstream gateway):
> 
> ```
> sergey@edge:~$ ip -6 route show
> DDDD:DDD:DDDD:DDDD::/64 dev ethext1 proto kernel metric 256 expires 194885sec pref medium

@sermolenko is this prefix route ? Then we can turn off by setting no prefix route while adding the address. The kernel is adding automatically.

**Comment by ssahani** [comment] 2020-03-31 22:29
> Did I do it wrong? Shouldn't `DHCPv6.AssignAcquiredDelegatedPrefix` be set on the same internal interfaces that `Network.IPv6PrefixDelegation` is set on?

Yes I have updated the patch . Please update the patch and retest.

**Comment by mmonaco** [comment] 2020-04-01 00:28
> Yes I have updated the patch . Please update the patch and retest.

You have updated it so the `AssignAcquiredDelegatedPrefix` setting gets applied to the internal lan interface, or are you referring to the documentation change you made? If so the wording could be clearer because it's still not 100% explicit the way it's supposed to work.

(Also, if you wouldn't mind if you are familiar with the code, do you know how to set the preferred/valid lifetimes on the advertise prefixes or is that only possible for statically defined prefixes? #13638 is killing me here, every time I test I have to restart all of my systems. I either need to be able to stabalize the order that /64's are carved off my /56 or set a very low lifetime for SLAAC addresses. Right now it doesn't seem like I can do either).

**Comment by sermolenko** [comment] 2020-04-01 01:22
> @sermolenko is this prefix route ? Then we can turn off by setting no prefix route while adding the address. The kernel is adding automatically.

This is indeed prefix route. I am not sure which route is "more correct" though. Prefix route seems to be assigned with the right metric, in line with other interfaces, and has expiration time in line with the router advertisement lifetime. It seems prefix route as assigned by kernel is just better specified than the one networkd adds manually. If anything, I'd personally prefer that when AssignAcquiredDelegatedPrefix is true, networkd just assigns the address, and skips the manual route creation. Then kernel takes care of getting the route set up.

All of that is relatively minor though - fix is definitely working in my set up as is. Just as @mmonaco, I was a bit confused by the wording, so I added AssignAcquiredDelegatedPrefix to both WAN and LAN interfaces.

**Comment by sermolenko** [comment] 2020-04-19 00:40
@ssahani  I am not entirely familiar with systemd dev process. Is there anything needed from my side to make sure this gets to master?

**Comment by ssahani** [comment] 2020-04-19 03:37
I requested @yuwata to review it. Thanks

**Comment by riobard** [comment] 2021-07-06 19:21
@yuwata Unfortunately this issue isn't completely fixed yet :(

According to @sermolenko 

>  It seems prefix route as assigned by kernel is just better specified than the one networkd adds manually. 

This isn't just better—it's actually required that `networkd` must NOT create the redundant route because that route will be sticking around even after the route created by kernel expires. 

I'm running into the situation that my ISP delegates dynamic short-lived prefixes, and I'm having dozens of dead routes to expired prefixes hanging in my routing table because `networkd` forgot to properly remove the routes it manually created.

Just let kernel handle it.

**Comment by yuwata** [comment] 2021-07-06 23:40
@riobard The issue is filed as #20146. I will work on the issue soon after v249 is released.
