### ISSUE TITLE
Systemd relies on “#include <scsi/sg.h>” which is not installed by the kernel

### ISSUE THREAD

**Issue by dilyanpalauzov** [systemd/systemd#12380] opened 2019-04-24 19:48 UTC
I try to compile systemd 242 on Linux 4.16.13.  Doing in the kernel “make headers_install INSTALL_HDR_PATH=/usr/” creates this structure under `/usr/include/scsi`
```
cxlflash_ioctl.h
scsi_netlink_fc.h
scsi_bsg_fc.h
fc
fc/fc_ns.h
fc/fc_els.h
fc/..install.cmd
fc/fc_fs.h
fc/.install
fc/fc_gs.h
..install.cmd
scsi_netlink.h
.install
```
Calling `ninja` in systemd/build fails with some missing scsc/*.h files:
```
[1/388] Generating version.h with a custom command.
[2/7] Compiling C object 'src/udev/3eb56e7@@ata_id@exe/ata_id_ata_id.c.o'.
FAILED: src/udev/3eb56e7@@ata_id@exe/ata_id_ata_id.c.o 
cc -Isrc/udev/3eb56e7@@ata_id@exe -Isrc/udev -I../src/udev -Isrc/basic -I../src/basic -Isrc/shared -I../src/shared -Isrc/systemd -I../src/systemd -Isrc/journal -I../src/journal -Isrc/journal-remote -I../src/journal-remote -Isrc/nspawn -I../src/nspawn -Isrc/resolve -I../src/resolve -Isrc/timesync -I../src/timesync -I../src/time-wait-sync -Isrc/login -I../src/login -Isrc/libudev -I../src/libudev -Isrc/core -I../src/core -Isrc/shutdown -I../src/shutdown -I../src/libsystemd/sd-bus -I../src/libsystemd/sd-device -I../src/libsystemd/sd-event -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-network -I../src/libsystemd/sd-resolve -Isrc/libsystemd-network -I../src/libsystemd-network -I. -I../ -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -g -Wextra -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Wno-error=nonnull -Wno-maybe-uninitialized -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -Werror=shadow -include config.h -DLOG_REALM=LOG_REALM_UDEV -MD -MQ 'src/udev/3eb56e7@@ata_id@exe/ata_id_ata_id.c.o' -MF 'src/udev/3eb56e7@@ata_id@exe/ata_id_ata_id.c.o.d' -o 'src/udev/3eb56e7@@ata_id@exe/ata_id_ata_id.c.o' -c ../src/udev/ata_id/ata_id.c
../src/udev/ata_id/ata_id.c:14:10: fatal error: scsi/scsi.h: No such file or directory
 #include <scsi/scsi.h>
          ^~~~~~~~~~~~~
compilation terminated.
[3/7] Compiling C object 'src/udev/3eb56e7@@cdrom_id@exe/cdrom_id_cdrom_id.c.o'.
FAILED: src/udev/3eb56e7@@cdrom_id@exe/cdrom_id_cdrom_id.c.o 
cc -Isrc/udev/3eb56e7@@cdrom_id@exe -Isrc/udev -I../src/udev -Isrc/basic -I../src/basic -Isrc/shared -I../src/shared -Isrc/systemd -I../src/systemd -Isrc/journal -I../src/journal -Isrc/journal-remote -I../src/journal-remote -Isrc/nspawn -I../src/nspawn -Isrc/resolve -I../src/resolve -Isrc/timesync -I../src/timesync -I../src/time-wait-sync -Isrc/login -I../src/login -Isrc/libudev -I../src/libudev -Isrc/core -I../src/core -Isrc/shutdown -I../src/shutdown -I../src/libsystemd/sd-bus -I../src/libsystemd/sd-device -I../src/libsystemd/sd-event -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-network -I../src/libsystemd/sd-resolve -Isrc/libsystemd-network -I../src/libsystemd-network -I. -I../ -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -g -Wextra -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Wno-error=nonnull -Wno-maybe-uninitialized -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -Werror=shadow -include config.h -DLOG_REALM=LOG_REALM_UDEV -MD -MQ 'src/udev/3eb56e7@@cdrom_id@exe/cdrom_id_cdrom_id.c.o' -MF 'src/udev/3eb56e7@@cdrom_id@exe/cdrom_id_cdrom_id.c.o.d' -o 'src/udev/3eb56e7@@cdrom_id@exe/cdrom_id_cdrom_id.c.o' -c ../src/udev/cdrom_id/cdrom_id.c
../src/udev/cdrom_id/cdrom_id.c:11:10: fatal error: scsi/sg.h: No such file or directory
 #include <scsi/sg.h>
          ^~~~~~~~~~~
compilation terminated.
[4/7] Compiling C object 'src/udev/3eb56e7@@scsi_id@exe/scsi_id_scsi_serial.c.o'.
FAILED: src/udev/3eb56e7@@scsi_id@exe/scsi_id_scsi_serial.c.o 
cc -Isrc/udev/3eb56e7@@scsi_id@exe -Isrc/udev -I../src/udev -Isrc/basic -I../src/basic -Isrc/shared -I../src/shared -Isrc/systemd -I../src/systemd -Isrc/journal -I../src/journal -Isrc/journal-remote -I../src/journal-remote -Isrc/nspawn -I../src/nspawn -Isrc/resolve -I../src/resolve -Isrc/timesync -I../src/timesync -I../src/time-wait-sync -Isrc/login -I../src/login -Isrc/libudev -I../src/libudev -Isrc/core -I../src/core -Isrc/shutdown -I../src/shutdown -I../src/libsystemd/sd-bus -I../src/libsystemd/sd-device -I../src/libsystemd/sd-event -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-network -I../src/libsystemd/sd-resolve -Isrc/libsystemd-network -I../src/libsystemd-network -I. -I../ -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -g -Wextra -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Wno-error=nonnull -Wno-maybe-uninitialized -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -Werror=shadow -include config.h -DLOG_REALM=LOG_REALM_UDEV -MD -MQ 'src/udev/3eb56e7@@scsi_id@exe/scsi_id_scsi_serial.c.o' -MF 'src/udev/3eb56e7@@scsi_id@exe/scsi_id_scsi_serial.c.o.d' -o 'src/udev/3eb56e7@@scsi_id@exe/scsi_id_scsi_serial.c.o' -c ../src/udev/scsi_id/scsi_serial.c
../src/udev/scsi_id/scsi_serial.c:13:10: fatal error: scsi/scsi.h: No such file or directory
 #include <scsi/scsi.h>
          ^~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: cannot make progress due to previous errors.
```

**Comment by yuwata** [comment] 2019-04-24 20:01
The file seems to be provided by glibc.
```
$ rpm -q --whatprovides /usr/include/scsi/scsi.h
glibc-headers-2.28-27.fc29.x86_64
```

**Comment by yuwata** [comment] 2019-04-24 20:04
So, let's close this. At least, this is not a bug.

**Closed as completed by yuwata** 2019-04-24 20:04 UTC

**Comment by dilyanpalauzov** [comment] 2019-04-24 21:03
Indeed,  `make headers_install INSTALL_HDR_PATH=/usr/` has deleted the content of /usr/include.
