### ISSUE TITLE
UpdateActivationEnvironment fails when an environment variable contains the value \033

### ISSUE THREAD

**Issue by davidedmundson** [systemd/systemd#16704] opened 2020-08-10 13:05 UTC
**systemd version the issue has been seen with**
> 246

**Used distribution**
 > Arch

**Expected behaviour you didn't see**
 > UpdateActivationEnvironment activation succeeds

**Unexpected behaviour you saw**
 > "warning: error sending to systemd: org.freedesktop.DBus.Error.InvalidArgs: Invalid environment assignments"
 > Then all variables sent (including ones without the escape sequence) are ignored.
 > This is especially problematic from my view as a desktop as we sync all the variables at once, and now $DISPLAY and other 
 > vital parts are not set because of this one obscure (but still valid) case.

**Steps to reproduce the problem**

```
#!/bin/sh
export FOO=`echo -e "\033ZTEST"`
echo $FOO
dbus-update-activation-environment --systemd --all
```

It's perfectly legitimate to have a \033 inside an environment variable from a bash POV. If it's legal there it should be legal here.

**Comment by poettering** [comment] 2020-08-10 13:42
Yes, some shells allow this, but it's fishy as it allows playing games with the user (as you can hide the true value of some variables that way), and we currently do not allow that.

**Comment by poettering** [comment] 2020-08-10 13:43
Duplicate of #4446

**Closed as completed by poettering** 2020-08-10 13:43 UTC
Labels: pid1, duplicate
