### ISSUE TITLE
coredumpctl gdb aborts if there is no COREDUMP_EXE

### ISSUE THREAD

**Issue by ghost** [systemd/systemd#422] opened 2015-06-30 11:33 UTC
systemd version: 221-2
OS: Arch Linux x86_64

So, I see that the Compositor process coredumps.
Of course, I try to use coredumpctl gdb to get a backtrace.
Then this happens:

```
mateus ~ $ coredumpctl gdb Compositor
           PID: 1077 (Compositor)
           UID: 1000 (mateus)
           GID: 1000 (mateus)
        Signal: 6 (ABRT)
     Timestamp: Seg 2015-06-29 18:16:44 BRT (14h ago)
       Boot ID: b554956fe0fc4f37935916dc1c5817c2
    Machine ID: 6f73af040ad64d90ae2bddb5baf67eef
      Hostname: mateus-arch
      Coredump: /var/lib/systemd/coredump/core.Compositor.1000.b554956fe0fc4f37935916dc1c5817c2.1077.1435612604000000.lz4
       Message: Process 1077 (Compositor) of user 1000 dumped core.

Failed to retrieve COREDUMP_EXE field: Arquivo ou diretório não encontrado
```

And coredumpctl gdb exits without running gdb.

**Comment by poettering** [comment] 2015-07-23 20:37
Hmm, could you provide the output of "getxattr -d /var/lib/systemd/coredump/core.Compositor.1000.b554956fe0fc4f37935916dc1c5817c2.1077.1435612604000000.lz4" please?

Also, can you run "journalctl -o verbose", find the line in question, and show the full output for the line here?

**Comment by dvdhrm** [comment] 2015-09-05 16:20
I cannot reproduce this, and it looks like a corrupted journal-entry that lacks the coredump-exe  entry. This has been open for 2 months without any reaction, so I'm going to close this now.

**Closed as completed by dvdhrm** 2015-09-05 16:20 UTC
Labels: coredump, needs-reporter-feedback ❓
