### ISSUE TITLE
RFE: extend Password Agents to user instances of systemd

### ISSUE THREAD

**Issue by gdamjan** [systemd/systemd#2217] opened 2015-12-23 01:46 UTC
reference: http://www.freedesktop.org/wiki/Software/systemd/PasswordAgents/

services run by the user instance of systemd should also be able to ask for passwords, especially since one user instance of systemd can support several sessions (tty, X, ssh).

That means the /run/user/1000/systemd/ask-password should be created, and agents bundled with systemd updated. 

No need for pkexec whould be required for those services.

**Comment by Stebalien** [comment] 2015-12-23 04:49
See: #1232

**Comment by poettering** [comment] 2015-12-23 20:01
Duplicate of #1232.

**Closed as completed by poettering** 2015-12-23 20:01 UTC
Labels: ask-password, duplicate
