### ISSUE TITLE
REGRESSION: usb-gadget.target breaks PAPPL

### ISSUE THREAD

**Issue by michaelrsweet** [systemd/systemd#32250] opened 2024-04-12 16:00 UTC
### systemd version the issue has been seen with

247

### Used distribution

RaspbianOS/Debian 11

### Linux kernel version used

6.1.21-v8+

### CPU architectures issue was seen on

aarch64

### Component

systemd

### Expected behaviour you didn't see

UDC remains unbound until configfs data is written.

### Unexpected behaviour you saw

UDC is bound on bootup with no gadgets.

### Steps to reproduce the problem

1. In "/boot/config.txt", comment out the line reading `otg_mode=1` and add a line at the end reading `dtoverlay=dwc2`.
2. In "/boot/cmdline.txt", add `modules-load=dwc2,libcomposite` between the `rootwait` and `quiet` options.

**Comment by michaelrsweet** [comment] 2024-04-12 16:07
This is a regression caused by #11586.

There is no documentation on how to configure gadgets (which should have prevented this new feature from being added), nor is there a way to get the configfs files created prior to systemd "taking over".

For reference, I found this doing testing on a Raspberry Pi for [PAPPL](https://github.com/michaelrsweet/pappl) which is used on embedded Linux systems to implement printer firmware, and part of that includes enabling USB gadgets for printing. At this point I haven't found a way to prevent systemd from f**cking with things, so I really need some guidance on how to work around this issue until you can come up with a fix...

**Comment by yuwata** [comment] 2024-04-12 20:04
I cannot follow the report, but the PR simply pulls `usb-gadget.target`, so the PR itself should not cause any issue.
I guess, there are some services or so that has `WantedBy=usb-gadget.target` or so, and they interfere your project.
You can check that with `systemctl show usb-gadget.target`. There should be some services in WantedBy=, After=, Before=.

**Comment by michaelrsweet** [comment] 2024-04-13 14:15
@yuwata So it seems like systemd triggers this as soon as the dwc2 module is loaded. Disabling/removing the usb-gadget.target seems to be working but I'd rather have a better long-term solution that doesn't depend on hacking systemd...

**Comment by poettering** [comment] 2024-04-13 18:01
@michaelrsweet systemd does not "bind udc". All it does is activating a systemd target unit "usb-gadget.target" if an "udc" device pops up. But that's a systemd thing that has no immediate effect whatsover on the device itself. What it does do however is provide a hook point where other stuff can plug itself into if it wants, and for example configure UDC some way or another.

Hence, my educated guess is that you have some package installed that makes of usb-gadget.target like this, and that package is the culprit here, not systemd.

Consider running "systemctl show -p Wants,Requires usb-gadget.target" or some command like that, it will tell you which services are pulled in like that.

Let me stress this again: we have no code whatsoever in systemd that would be able to configure an UDC devices. Please slow down a bit before blaming systemd.

**Comment by michaelrsweet** [comment] 2024-04-13 19:15
Output from the command says:

```
systemctl show -p Wants,Requires usb-gadget.target
Requires=
Wants=
```

Like I said, nothing was configuring any gadgets but systemd says it has activated the UDC:

```
systemctl | grep udc
  sys-devices-platform-soc-3f980000.usb-udc-3f980000.usb.device                                loaded active plugged   /sys/devices/platform/soc/3f980000.usb/udc>
```

*I* haven't installed or enabled any packages specific to USB gadgets, and nothing shows up (are you see above), but if I disable the usb-gadget.target then I am able to configure the USB gadgets successfully. If it isn't systemd, some guidance on finding the culprit would be greatly appreciated.

**Comment by yuwata** [comment] 2024-04-13 20:39
Not only Wants and Requires, please check all dependencies: After, Before, and so on. Have you checked the result of `systemctl show usb-gadget.target`? Please paste it.

As already said, systemd does not "bind" or "activate" udc. You need to find the one who touches the device.

**Comment by michaelrsweet** [comment] 2024-04-13 20:44
Output of `systemctl show usb-gadget.target`:

```
Id=usb-gadget.target
Names=usb-gadget.target
WantedBy=sys-devices-platform-soc-3f980000.usb-udc-3f980000.usb.device
Conflicts=shutdown.target
Before=shutdown.target
Documentation="man:systemd.special(7)"
Description=Hardware activated USB gadget
LoadState=loaded
ActiveState=active
FreezerState=running
SubState=active
FragmentPath=/lib/systemd/system/usb-gadget.target
UnitFileState=static
UnitFilePreset=enabled
StateChangeTimestamp=Sat 2024-04-13 16:34:46 EDT
StateChangeTimestampMonotonic=10227158
InactiveExitTimestamp=Sat 2024-04-13 16:34:46 EDT
InactiveExitTimestampMonotonic=10227158
ActiveEnterTimestamp=Sat 2024-04-13 16:34:46 EDT
ActiveEnterTimestampMonotonic=10227158
ActiveExitTimestampMonotonic=0
InactiveEnterTimestampMonotonic=0
CanStart=yes
CanStop=yes
CanReload=no
CanIsolate=no
CanFreeze=no
StopWhenUnneeded=no
RefuseManualStart=no
RefuseManualStop=no
AllowIsolate=no
DefaultDependencies=yes
OnFailureJobMode=replace
IgnoreOnIsolate=no
NeedDaemonReload=no
JobTimeoutUSec=infinity
JobRunningTimeoutUSec=infinity
JobTimeoutAction=none
ConditionResult=yes
AssertResult=yes
ConditionTimestamp=Sat 2024-04-13 16:34:46 EDT
ConditionTimestampMonotonic=10227091
AssertTimestamp=Sat 2024-04-13 16:34:46 EDT
AssertTimestampMonotonic=10227107
Transient=no
Perpetual=no
StartLimitIntervalUSec=10s
StartLimitBurst=5
StartLimitAction=none
FailureAction=none
SuccessAction=none
InvocationID=2e7c2527ea1d42f8a3c2e8238e642b83
CollectMode=inactive
```

Output of `systemctl show sys-devices-platform-soc-3f980000.usb-udc-3f980000.usb.device`:

```
SysFSPath=/sys/devices/platform/soc/3f980000.usb/udc/3f980000.usb
Id=sys-devices-platform-soc-3f980000.usb-udc-3f980000.usb.device
Names=sys-devices-platform-soc-3f980000.usb-udc-3f980000.usb.device
Wants=usb-gadget.target
Description=/sys/devices/platform/soc/3f980000.usb/udc/3f980000.usb
LoadState=loaded
ActiveState=active
FreezerState=running
SubState=plugged
StateChangeTimestamp=Sat 2024-04-13 16:34:46 EDT
StateChangeTimestampMonotonic=10217504
InactiveExitTimestamp=Sat 2024-04-13 16:34:46 EDT
InactiveExitTimestampMonotonic=10217504
ActiveEnterTimestamp=Sat 2024-04-13 16:34:46 EDT
ActiveEnterTimestampMonotonic=10217504
ActiveExitTimestampMonotonic=0
InactiveEnterTimestampMonotonic=0
CanStart=no
CanStop=no
CanReload=no
CanIsolate=no
CanFreeze=no
StopWhenUnneeded=no
RefuseManualStart=no
RefuseManualStop=no
AllowIsolate=no
DefaultDependencies=yes
OnFailureJobMode=replace
IgnoreOnIsolate=yes
NeedDaemonReload=no
JobTimeoutUSec=infinity
JobRunningTimeoutUSec=1min 30s
JobTimeoutAction=none
ConditionResult=no
AssertResult=no
ConditionTimestampMonotonic=0
AssertTimestampMonotonic=0
Transient=no
Perpetual=no
StartLimitIntervalUSec=10s
StartLimitBurst=5
StartLimitAction=none
FailureAction=none
SuccessAction=none
InvocationID=d30c6d66299a44a38f5e531a568eec67
CollectMode=inactive
```

**Comment by yuwata** [comment] 2024-04-13 20:54
OK, there is nothing. So, usb-gadget.target should be unrelated to your issue.

**Comment by yuwata** [comment] 2024-04-13 22:51
Closing. The issue is not related to usb-gadget.target.

**Closed as not planned by yuwata** 2024-04-13 22:51 UTC
Labels: pid1, not-our-bug, version-too-ancient
