### ISSUE TITLE
Failed to finalize file systems, ignoring [BUG] but computer won't turn off

### ISSUE THREAD

**Issue by marek-lach** [systemd/systemd#15673] opened 2020-05-02 12:05 UTC
![IMG_2499](https://user-images.githubusercontent.com/45913977/80863531-5e5a5380-8c7d-11ea-9131-0c1985960f10.jpg)

**When does this happen?**
If my laptop battery is too low, maybe 4%, the wifi disconnects as a power saving feature.
Trying to reboot, or power off the laptop after plugging it back into power then results in this error.

Currently only pressing the physical power button for a rather long time eventually turns the computer off.

**What should happen instead?**
After the _Failed to finalize file systems, ignoring_ line the shut-down process just freezes, and stops completely. It doesn't shut down anyway. I think the shutdown should just ignore all background tasks, or processes, and occur regardless.

**Comment by poettering** [comment] 2020-05-03 07:39
So, this is not caused by systemd. You appear to have some kernel problems (i.e. the messages further up point you to that, apparently in the mwifiex driver?), and two processes called "tip" apparently are frozen, most likely due to that. i.e. userspace asks the kernel to reboot, but the kernel just hangs.

If you fix your driver woes I am very sure the rebooting will just work again.

There's nothing we can do from userspace on this, if the kernel is fucked the kernel is fucked, and all bets are off at that point.

Please report this to your downstream or the kernel driver people responsible for your driver, we cannot do anything about this from our side.

Hope that makes sense?

Closing.

**Closed as completed by poettering** 2020-05-03 07:39 UTC
Labels: not-our-bug
