### ISSUE TITLE
rfe: machinectl shell should return exit code from command run in container

### ISSUE THREAD

**Issue by ostcar** [systemd/systemd#3372] opened 2016-05-27 21:18 UTC
### Submission type
- [ ] Bug report
- [x] Request for enhancement (RFE)
### systemd version the issue has been seen with

> 229
### Used distribution

> archlinux
### Description

When machinectl shell calls a command inside the container that fails (returns a exit code other then 0) then machinectl nevertheless returns 0. So when using machinectl shell in scripts, there is no way to know if the command has failed.

Example:

```
$ machinectl shell mymachine -- exit 1
...
$ echo $?
0
```

The problem is, that machinectl shell can also return an error code if there are problems with the connection to the machine, so an non zero exit code would not be distinct. But in this case, there are usual some error messages from machinectl. And it is easier to identify the error if there is an exit code other then zero, then find the error if 0 is returned.

**Comment by poettering** [comment] 2016-10-10 16:12
Duplicate of #4215. Closing this one.

**Closed as completed by poettering** 2016-10-10 16:12 UTC
Labels: RFE 🎁, machine, duplicate
