### ISSUE TITLE
Failed to start Dispatch Password Requests to Console Directory Watch.

### ISSUE THREAD

**Issue by edmundlod** [systemd/systemd#15086] opened 2020-03-11 19:49 UTC
**systemd version the issue has been seen with**
systemd 245-2

**Used distribution**
Arch Linux

**Expected behaviour you didn't see**
No errors during boot.

**Unexpected behaviour you saw**
From `journalctl -xe`

> ...
> Mar 11 19:52:18 birdsong kernel: Run /init as init process
> Mar 11 19:52:18 birdsong systemd[1]: systemd 245-2-arch running in system mode. (+PAM +AUDIT -SELINUX -IMA -APPARMOR>
> Mar 11 19:52:18 birdsong systemd[1]: Detected architecture x86-64.
> Mar 11 19:52:18 birdsong systemd[1]: Running in initial RAM disk.
> Mar 11 19:52:18 birdsong kernel: fbcon: Taking over console
> Mar 11 19:52:18 birdsong systemd[1]: Set hostname to <birdsong>.
> Mar 11 19:52:18 birdsong kernel: Console: switching to colour frame buffer device 128x48
**> Mar 11 19:52:18 birdsong systemd[1]: /usr/lib/systemd/system/systemd-ask-password-console.service:20: Executable "systemd-tty-ask-password-agent" not found in path "/usr/local/bin:/usr/bin"
> Mar 11 19:52:18 birdsong systemd[1]: systemd-ask-password-console.service: Unit configuration has fatal error, unit will not be started.
> Mar 11 19:52:18 birdsong systemd[1]: systemd-ask-password-console.path: Refusing to start, unit systemd-ask-password-console.service to trigger not loaded.
> Mar 11 19:52:18 birdsong systemd[1]: Failed to start Dispatch Password Requests to Console Directory Watch.**
> Mar 11 19:52:18 birdsong systemd[1]: Reached target Local File Systems.
> Mar 11 19:52:18 birdsong systemd[1]: Reached target Paths.
> Mar 11 19:52:18 birdsong systemd[1]: Reached target Slices.
> Mar 11 19:52:18 birdsong systemd[1]: Reached target Swap.
> Mar 11 19:52:18 birdsong systemd[1]: Reached target Timers.
> Mar 11 19:52:18 birdsong systemd[1]: Listening on Journal Audit Socket.
> Mar 11 19:52:18 birdsong systemd[1]: Listening on Journal Socket (/dev/log).
> Mar 11 19:52:18 birdsong systemd[1]: Listening on Journal Socket.
> Mar 11 19:52:18 birdsong systemd[1]: Listening on udev Control Socket.
> Mar 11 19:52:18 birdsong systemd[1]: Listening on udev Kernel Socket.
> ...

Eventually I can enter a password to decrypt a LUKS encrypted disk and the boot process continues normally.

The local file system seems to not yet be up and running when the error occurs.

Kernel used: kernel-hardened from Arch repo

**Steps to reproduce the problem**
Install the newest systemd version and reboot.

**Comment by ratcheer** [comment] 2020-03-14 18:23
I have the same error, but I am on systemd version 245-3, and I run the "standard" Arch Linux kernel.

**Comment by Toolybird** [comment] 2020-03-17 05:42
This is happening during the initramfs stage.

Appears to be harmless. But it sure is annoying seeing these errors in the journal.

Seems to be caused by this commit:

https://github.com/systemd/systemd/pull/14374

(Arch, bog standard, except using dracut instead of mkinitcpio)

**Comment by yuwata** [comment] 2020-03-17 09:09
> Mar 11 19:52:18 birdsong systemd[1]: /usr/lib/systemd/system/systemd-ask-password-console.service:20: Executable "systemd-tty-ask-password-agent" not found in path "/usr/local/bin:/usr/bin"

Where is the binary installed on Arch Linux?

**Comment by lquidfire** [comment] 2020-03-17 09:46
```
$ whereis systemd-tty-ask-password-agent
systemd-tty-ask-password-agent: /usr/bin/systemd-tty-ask-password-agent /usr/share/man/man1/systemd-tty-ask-password-agent.1.gz
```

**Comment by yuwata** [comment] 2020-03-17 10:31
> Mar 11 19:52:18 birdsong systemd[1]: Running in initial RAM disk.

I guess the initrd does not contain `systemd-tty-ask-password-agent`.

**Comment by lquidfire** [comment] 2020-03-17 12:13
I think this is a dracut issue. Compare: https://github.com/dracutdevs/dracut/issues/726 This was fixed here: https://github.com/dracutdevs/dracut/commit/16abea2592d7fee6166660098b647356d5a4cc14

The fix is in dracut 050, but Arch is still on dracut 049-4. I will test at home if an upgrade solves the problem indeed, and then also poke the maintainer of the Arch package.

**Comment by ratcheer** [comment] 2020-03-17 16:50
> > Mar 11 19:52:18 birdsong systemd[1]: /usr/lib/systemd/system/systemd-ask-password-console.service:20: Executable "systemd-tty-ask-password-agent" not found in path "/usr/local/bin:/usr/bin"
> 
> Where is the binary installed on Arch Linux?

On my Arch system, it  is in /usr/bin

**Comment by lquidfire** [comment] 2020-03-17 19:18
I backported the commit that fixes this to a custom dracut-049 and it works. This is not a systemd issue and can be closed. Thanks!

**Closed as completed** 2020-03-17 20:29 UTC
Labels: not-our-bug, ask-password
