### ISSUE TITLE
Offer text based log database format

### ISSUE THREAD

**Issue by plomari** [systemd/systemd#23462] opened 2022-05-21 11:09 UTC
**Is your feature request related to a problem? Please describe.**
It's hard to inspect and process the log files saved by journald, because it's some home-grown binary format not supported by any standard software. The only thing I found was journalctl, which does more than just parsing log files and can't be directed to specific log files (and even if it could, not a satisfying solution anyway). Binary database formats also tend to suffer from internal fragmentation (usually only avoided only at the cost of periodic reorganization or lower performance).

**Describe the solution you'd like**
Simple text output to files. Instead of doing troublesome rotation with file renaming, just start new files with a unique filename (date or counter), and delete the old ones.

**Describe alternatives you've considered**
Reverse-engineering the database format I guess?

**The systemd version you checked that didn't have the feature you are asking for**

 250.4-1

**Comment by poettering** [comment] 2022-05-21 11:52
journalctl --file= reads individual files. And it's very hard to find a distro that doesnt have journalctl. If you found one anyway you actively sabotaged yourself, and you have to deal with the outcome yourself. The format is documented in plenty detail hence not sure why youd reverse engineer anything here:

 http://systemd.io/JOURNAL_FILE_FORMAT

If you want text logs theres plenty sw around which will give you that. Rsyslog and such.

Hence. I see not much here, and this was discussed many times before... Hence closing

**Closed as completed** 2022-05-21 11:52 UTC

**Comment by plomari** [comment] 2022-05-21 11:59
What about the higher size requirements of a binary format? I just checked the same file with `journalctl --file=$FILE | wc -c` and `du $FILE`, the text output was ~3 MB, while the file itself is 32 MB. I've even ran `journalctl --vacuum-time=6d` before that. (Which doesn't fully work, see other bug report.)

**Comment by mrc0mmand** [comment] 2022-05-21 13:04
> What about the higher size requirements of a binary format? I just checked the same file with `journalctl --file=$FILE | wc -c` and `du $FILE`, the text output was ~3 MB, while the file itself is 32 MB.

That's mainly caused by the additional metadata each message carries, so `journalctl --file $FILE -o export` would be more appropriate here. Also, internal fragmentation is not a big issue in journal's case, since we fallocate() the journal files in 8MiB increments, see the discussion in https://github.com/systemd/systemd/issues/22940#issuecomment-1088438650. There's also an ongoing work on the journal's compact mode (https://github.com/systemd/systemd/pull/21183).

**Comment by plomari** [comment] 2022-05-21 13:09
>Also, internal fragmentation is not a big issue in journal's case, since we fallocate() the journal files in 8MiB increments,

The file I checked was fully allocated, on a file system that supports sparse files.
