### ISSUE TITLE
systemd-fstab-generator issues

### ISSUE THREAD

**Issue by jaymzh** [systemd/systemd#8835] opened 2018-04-27 00:16 UTC
### Submission type

Possible bug, definitely RFE on debugging, and possibly some help to debug more :)

### systemd version the issue has been seen with

237

### Used distribution

CentOS

### In case of bug report: Expected behaviour you didn't see

We have some cases where NFS filesystems aren't mounted on boot on some hosts but are on other hosts... and we think it's down to systemd-fstab-generator not generating them right since we don't see the mount units ever show up in the journal.

On two machines that are AFAICT, configured identically where the generator seems to work on one but not the other and I'm out of ideas for debugging. We have something like this in `/etc/fstab`:

```
host:/mount /path1 nfs rw,hard,intr,nfsvers=3,noatime 0 0
host:/mount /path2 nfs rw,hard,intr,nfsvers=3,noatime,lookupcache=positive 0 0
```

Yes, the source is the same in both. This is exactly as it is on the host, except for the nfs server path and the mounted path.

We **have** tried explicitly adding `_netdev` but it didn't help.

On one host this just works, on boot the generated unit is created, it's mounted and the status shows `active (mounted)`. On the other it shows `inactive (dead)`.

We booted with systemd in debug mode, but the mount never shows up in the journal. On the good host you see `Changed dead -> mounted` but it's never mentioned at all on the bad host.

So then we tried replacing `systemd-fstab-generator` with a shellscript that does:

```
SYSTEMD_LOG_LEVEL=debug /systemd-fstab-generator $* >> /run/cake
echo >> /run/cake
```

and then adding `install_items+="/systemd-fstab-generator"` to /etc/dracut.conf, running `dracut --force` and rebooting... but /run/cake has nothing.

At this point I'm out of useful debugging ideas. So:

1. Any other ways to debug what's going on here?
2. If not, can we make this an RFE for debugging in systemd-fstab-generator?
3. If so, I'll go do that
4. Any ideas on what might be wrong?

### In case of bug report: Unexpected behaviour you saw

see above.

### In case of bug report: Steps to reproduce the problem

see above.

**Comment by jaymzh** [comment] 2018-04-27 00:16
CC @davide125

**Comment by yuwata** [comment] 2018-04-27 04:42
Could you show the generated units?

**Comment by keszybz** [comment] 2018-04-27 09:27
I read the bug report... and you don't actually say what the problem is. `systemd-fstab-generator` just writes a bunch of files in `/run/systemd/generator*`, so "it doesn't work" implies that the files are somehow not generated or something. It's unlikely, but also very easy to debug with `ls` and `cat`.

> `SYSTEMD_LOG_LEVEL=debug /systemd-fstab-generator $* >> /run/cake`

systemd-fstab-generator should not write anything to stdout. It's expected that /run/cake is empty.

**Comment by jaymzh** [comment] 2018-04-27 16:19
@keszybz - oops! You're right, I didn't say the actual bug! The actual bug is that the "bad" hosts don't get the mounts mounted on boot, while the "good" hosts do. On the "bad" hosts I can then then `mount /path1` and it works, but they don't mount on boot. On the "good" hosts they're mounted automatically on boot. I'll edit the original post to add that.

@yuwata - yup, I'll get those for you today.

**Comment by jaymzh** [comment] 2018-04-27 18:16
The generated unit appears to be identical on a good and bad host:

bad:
```
# systemctl status path.mount
● path.mount - /path
   Loaded: loaded (/etc/fstab; generated)
   Active: inactive (dead)
    Where: /path
     What: host:/vol
     Docs: man:fstab(5)
           man:systemd-fstab-generator(8)
# systemctl cat path.mount
# /run/systemd/generator/path.mount
# Automatically generated by systemd-fstab-generator

[Unit]
SourcePath=/etc/fstab
Documentation=man:fstab(5) man:systemd-fstab-generator(8)
Before=remote-fs.target

[Mount]
Where=/path
What=host:/vol
Type=nfs
Options=rw,hard,intr,nfsvers=3,noatime
# 
```
Good:

```
# systemctl status path.mount
● path.mount - /path
   Loaded: loaded (/etc/fstab; generated)
   Active: active (mounted) since Mon 2018-04-23 12:40:38 PDT; 3 days ago
    Where: /path
     What: host:/vol
     Docs: man:fstab(5)
           man:systemd-fstab-generator(8)
   CGroup: /system.slice/path.mount

Warning: Journal has been rotated since unit was started. Log output is incomplete or
[root@cfgate003.02.frc2 ~]# systemctl cat path.mount
# /run/systemd/generator/path.mount
# Automatically generated by systemd-fstab-generator

[Unit]
SourcePath=/etc/fstab
Documentation=man:fstab(5) man:systemd-fstab-generator(8)
Before=remote-fs.target

[Mount]
Where=/path
What=host:/vol
Type=nfs
Options=rw,hard,intr,nfsvers=3,noatime
```

On the bad host a manual start works:

```
# systemctl start path.mount
# systemctl status path.mount
● path.mount - /path
   Loaded: loaded (/etc/fstab; generated)
   Active: active (mounted) since Fri 2018-04-27 11:15:31 PDT; 2s ago
    Where: /path
     What: host:/vol
     Docs: man:fstab(5)
           man:systemd-fstab-generator(8)
  Process: 12349 ExecMount=/usr/bin/mount host:/vol /path -t 
   CGroup: /system.slice/path.mount

Apr 27 11:15:31 cfgate001.11.frc3.facebook.com systemd[1]: Mounting /path.
Apr 27 11:15:31 cfgate001.11.frc3.facebook.com systemd[1]: Mounted /path.
```

**Comment by keszybz** [comment] 2018-04-28 08:59
This shows that the content of the unit file itself is OK. The difference is somewhere else.

Please attach the output of `systemctl show /path` and `systemctl show remote-fs.target`.
A full boot log with `systemd.log_level=debug systemd.log_target=kmsg log_buf_len=1M printk.devkmsg=on` would be very useful too.

**Comment by jaymzh** [comment] 2018-04-28 19:51
I did boot with `systemd.log_level=debug systemd.log_target=kmsg log_buf_len=1M printk.devkmsg=on` and `path.mount` and `/path` don't show up in the journal at all on the bad host. On the good host you see it changing state `Changed dead -> mounted` and that's it.

I'll get you the `show`s in a bit.

**Comment by jaymzh** [comment] 2018-04-28 20:36
I often forget the magic of `show`. Thanks. I diff'd all the shows and while there's a bunch of differences between running and non-running mounts and targets, this piece of remote-fs.target was the relevant one:

```
-WantedBy=dracut-pre-pivot.service
+WantedBy=dracut-pre-pivot.service multi-user.target
```

And sure enough remote-fs.target is linked from `/etc/systemd/system/multi-user.target.wants/` on the good host but not the bad.

Adding that fixes the problem. Thank you!

I would know how to debug this in the future, but to make things easier... would it be useful to include somewhere what triggered a target to start? Like "this was started because of socket activation" or "this was started because we hit `multi-user.target` which `Wants` this" or something? Or maybe that's already there somewhere I don't know?

**Comment by keszybz** [comment] 2019-01-24 14:55
> Adding that fixes the problem.

Let's close this then.

>  include somewhere what triggered a target to start? Like "this was started because of socket activation" or "this was started because we hit multi-user.target which Wants this" or something? Or maybe that's already there somewhere I don't know?

I don't think we have anything like this. Please file a new issue to track this.

**Closed as completed by keszybz** 2019-01-24 14:55 UTC
Labels: fstab-generator

**Comment by jaymzh** [comment] 2019-01-25 08:38
@keszybz  - Opened https://github.com/systemd/systemd/issues/11552 for that.
