### ISSUE TITLE
[coredumpctl] make it easy to invoke arbitrary debugger with gdb-like command-line interface

### ISSUE THREAD

**Issue by jnpkrn** [systemd/systemd#9311] opened 2018-06-15 17:02 UTC
**Is your feature request related to a problem? Please describe.**
I prefer `cgdb` for debugging, however I cannot use it easily from `coredumpctl`.
Even when I try a `PATH`/symlink/helper script trick to override `gdb` on `PATH`,
and indeed, I can see it's interface for a bit, it will subsequently terminate.
I have no idea about the reason, may be that `curses`-based environment
relies on some signals (something else?) that are blocked.

I think that enabling to use the same scheme with automatic cleanup and presumably
enforced secure approach in general with arbitrary command with the same interface
would be very convenient.

**Describe the solution you'd like**
Two parts:
- make sure that `cgdb` is fully usable under `coredumpctl`'s wrapping
- allow one to specify alternative gdb command with environment variable,
  e.g. `GDB` (for a start, no need to provide the overriding mechanism
  on the command line)

**Describe alternatives you've considered**
Making the coredump materialized in the filesystem with a separate command
(less convenient, possibly also less secure when the path not selected wisely).

**Comment by poettering** [comment] 2018-06-15 17:15
Already implemented, see #8744. Will be part of the new v239 release which is going to be released next week.

**Closed as completed by poettering** 2018-06-15 17:15 UTC
Labels: coredump, duplicate, already-implemented

**Comment by poettering** [comment] 2018-06-15 17:18
duplicate of #8722

**Comment by jnpkrn** [comment] 2018-06-18 12:41
Confirming `--debugger=cgdb` works well with the pre-release announced in
https://lists.freedesktop.org/archives/systemd-devel/2018-June/040862.html

Thanks and sorry for the dupe, wrong search phrases I guess.
