### ISSUE TITLE
Type=dbus NameOwnerChanged race condition

### ISSUE THREAD

**Issue by mischief** [systemd/systemd#2136] opened 2015-12-10 20:28 UTC
commit bbc2908635ca3ded9162504683fa126809f0ec14 introduces a race condition that occurs during serialization/deserialization of the bus name matchers. an easy way to reproduce is run:

``` sh
while sudo systemctl is-active polkit.service; do sudo systemctl daemon-reload; sleep 0.5; done &
while sudo systemctl is-active polkit.service; do sudo systemctl restart polkit.service; sleep 2; done &
```

and wait for polkit to get stuck in 'activating', since systemd missed the NameOwnerChange signal from polkit. eventually polkit is timed out and killed, even though it is running fine.

i'm not very familiar with dbus api, so i think NameHasOwner needs to be called after matching NameOwnerChange.

friendly ping @zonque :)

**Comment by mischief** [comment] 2015-12-14 20:58
@zonque this was my attempt at solving this, but i could still reproduce the issue afterward. https://gist.github.com/mischief/435b77f48e1e6f5a994f

**Comment by mischief** [comment] 2015-12-14 20:59
https://github.com/coreos/bugs/issues/462 for further examples of this occuring

**Comment by zonque** [comment] 2015-12-15 12:46
Thanks for the report. I see the race, but I fail to reproduce the bug with your two shell loops. Still trying.

**Comment by zonque** [comment] 2015-12-15 14:54
Ok, able to reproduce it now, but it takes a while. I'm puzzled why your patch doesn't do it, it looks correct to me. Will keep digging.

**Comment by zonque** [comment] 2015-12-15 17:21
Ah, ok. If you trigger that NameOwnerChanged signal callback like you did in your gist patch, the service is still 'dead', so that callback function becomes a no-op.

The right approach is probably to check for an existing name from `service_enter_start()`. I'm testing a patch right now, will share later if it works.

**Comment by zonque** [comment] 2015-12-15 18:42
@mischief, care to give this one a spin on your machines?
https://github.com/zonque/systemd/commit/11af6f63

**Comment by mischief** [comment] 2015-12-15 18:56
@zonque i'm testing it now.

**Comment by mischief** [comment] 2015-12-15 19:16
@zonque i can still reproduce the issue with your commit cherry-picked on top of https://github.com/coreos/systemd/tree/v225-coreos. is there perhaps something else between v225..v228 that could affect this?

i can trigger it with this shell script:

``` sh
while sudo systemctl daemon-reload; do sleep 0.01; done &
while sudo systemctl is-active polkit.service; do sudo systemctl restart polkit.service; sleep 1; done &
```

**Comment by mischief** [comment] 2015-12-15 20:17
@zonque i built systemd-228 from your branch at https://github.com/zonque/systemd/tree/nameownerchanged and i can still reproduce. can you?

**Comment by zonque** [comment] 2015-12-15 20:21
Hmm, nope. Running since almost an hour now.

**Comment by mischief** [comment] 2015-12-15 20:33
@zonque curiously, with your branch, polkit has gotten stuck in activating, yet systemd never terminates it due to timeout.

```
$ sudo systemctl status -l polkit
? polkit.service - Authorization Manager
   Loaded: loaded (/usr/lib64/systemd/system/polkit.service; static; vendor preset: disabled)
   Active: activating (start) since Tue 2015-12-15 20:15:42 UTC; 16min ago
     Docs: man:polkit(8)
 Main PID: 1629 (polkitd)
   CGroup: /system.slice/polkit.service
           ??1629 /usr/lib/polkit-1/polkitd --no-debug

Dec 15 20:32:25 coreos_production_qemu-884-0-0-2 polkitd[1629]: Unregistered Authentication Agent for unix-process:25095:105724 (system bus name :1.7863, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Dec 15 20:32:25 coreos_production_qemu-884-0-0-2 polkitd[1629]: Registered Authentication Agent for unix-process:25123:105736 (system bus name :1.7864 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Dec 15 20:32:25 coreos_production_qemu-884-0-0-2 polkitd[1629]: Unregistered Authentication Agent for unix-process:25123:105736 (system bus name :1.7864, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Dec 15 20:32:25 coreos_production_qemu-884-0-0-2 polkitd[1629]: Registered Authentication Agent for unix-process:25150:105749 (system bus name :1.7865 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Dec 15 20:32:26 coreos_production_qemu-884-0-0-2 polkitd[1629]: Unregistered Authentication Agent for unix-process:25150:105749 (system bus name :1.7865, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Dec 15 20:32:26 coreos_production_qemu-884-0-0-2 polkitd[1629]: Registered Authentication Agent for unix-process:25178:105769 (system bus name :1.7866 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Dec 15 20:32:26 coreos_production_qemu-884-0-0-2 polkitd[1629]: Unregistered Authentication Agent for unix-process:25178:105769 (system bus name :1.7866, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Dec 15 20:32:26 coreos_production_qemu-884-0-0-2 polkitd[1629]: Registered Authentication Agent for unix-process:25204:105779 (system bus name :1.7867 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
Dec 15 20:32:26 coreos_production_qemu-884-0-0-2 polkitd[1629]: Unregistered Authentication Agent for unix-process:25204:105779 (system bus name :1.7867, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Dec 15 20:32:26 coreos_production_qemu-884-0-0-2 polkitd[1629]: Registered Authentication Agent for unix-process:25234:105791 (system bus name :1.7868 [/usr/bin/pkttyagent --notify-fd 5 --fallback], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8)
core@coreos_production_qemu-884-0-0-2 ~ $  
```

**Comment by zonque** [comment] 2015-12-15 20:49
How long does it usually take on your machine to reproduce this, with the commands you quoted?
Also, is this really only happening when the daemon is reloaded at the same time? Because the original bug report makes be believe it's not, and it also happens during regular boots.

And also, this seems to be specific to PolKit, right? Or has anyone experienced similar things with other services as well? Thinking about it again, I believe there's something else going on.

**Comment by mischief** [comment] 2015-12-15 20:58
@zonque this occurs during daemon-reload, as far as i can tell.

in CoreOS, we have https://github.com/coreos/coreos-cloudinit which is writing systemd unit files and executing daemon-reload at the end of writing units. this happens every boot in CoreOS. it does not take very long at all to reproduce - with the script in https://github.com/systemd/systemd/issues/2136#issuecomment-164862717 it just took approx 1m30s to trigger and get stuck in activating against your `nameownerchanged` branch.

the test system is a QEMU vm with CoreOS 884.0.0, with the /usr/lib/systemd/systemd binary replaced with one built from your branch.

i'll attempt to reproduce the issue against a different Type=dbus service.

**Comment by mischief** [comment] 2015-12-15 21:03
just reproduced against update_engine, the automatic updating system in CoreOS. the systemd unit is shown here:

```
# /usr/lib64/systemd/system/update-engine.service
[Unit]
Description=Update Engine
ConditionVirtualization=!container
ConditionPathExists=!/usr/.noupdate

[Service]
Type=dbus
BusName=com.coreos.update1
ExecStart=/usr/sbin/update_engine -foreground -logtostderr
BlockIOWeight=100
Restart=always
RestartSec=30

[Install]
WantedBy=default.target
```

and the script (same as above, just different service):

``` sh
while sudo systemctl daemon-reload; do sleep 0.01; done &
while sudo systemctl is-active update-engine.service; do sudo systemctl restart update-engine.service; sleep 1; done &
```

and the status

```
core@coreos_production_qemu-884-0-0-2 ~ $ systemctl status update-engine.service
? update-engine.service - Update Engine
   Loaded: loaded (/usr/lib64/systemd/system/update-engine.service; disabled; vendor preset: disabled)
   Active: activating (start) since Tue 2015-12-15 21:02:46 UTC; 33s ago
 Main PID: 6592 (update_engine)
   Memory: 848.0K
      CPU: 44ms
   CGroup: /system.slice/update-engine.service
           ??6592 /usr/sbin/update_engine -foreground -logtostderr

Dec 15 21:02:46 coreos_production_qemu-884-0-0-2 systemd[1]: Starting Update Engine...
Dec 15 21:02:46 coreos_production_qemu-884-0-0-2 update_engine[6592]: [1215/210246:INFO:main.cc(155)] CoreOS Update Engine starting
Dec 15 21:02:46 coreos_production_qemu-884-0-0-2 update_engine[6592]: [1215/210246:INFO:update_check_scheduler.cc(82)] Next update check in 10m27s
core@coreos_production_qemu-884-0-0-2 ~ $ busctl | grep update
:1.18926                         6592 update_engine   root             :1.18926      update-engine.service     -          -                  
com.coreos.update1               6592 update_engine   root             :1.18926      update-engine.service     -          -                  
core@coreos_production_qemu-884-0-0-2 ~ $ 
```

**Comment by zonque** [comment] 2015-12-16 14:12
Ok, let's step back a little, and see what the life cycle of a service is, assuming, for simplicity, there is _no_ daemon reload in the game: When the unit is loaded by the manager, it calls `service_load()`, which will install the bus match. At this point, the processes of the service are not running, hence the name should be unclaimed. Next, when the service is starting up, `service_start()` is ran, which puts the service in `SERVICE_START` state, waiting for the `NameOwnerChanged` signal to fire. Once that signal is dispatched, the service is marked as fully started. There is no race in this model, unless the process claiming the name on the bus is not actually the one that systemd starts. Then, and only then, can the name we're waiting for pop up prematurely on the bus, causing the described confusion. That, however, is not the case, as the process owning the name is the one that systemd started.

The elephant in the room is of course the daemon reload, in which case we lose the bus connection for a short time, and hence miss the signal delivery. Apparently, CoreOS does a daemon reload also during normal boot, which I didn't know.

I'll provide a different fix later.

**Comment by zonque** [comment] 2015-12-17 19:30
FTR: I figure the fix I wanted to provide is already implemented. When (re-)connecting to the API bus, we already walk the list of active bus names and trigger the `bus_name_owner_change` callback for each waiting unit.

This is probably related to the fact that we don't correctly restore each service's state when doing a daemon reload. We'll think about something.

**Comment by zonque** [comment] 2015-12-18 16:42
Here's another attempt to fix this. @mischief, could you try this one in your setup?

https://github.com/zonque/systemd/commit/aad89bc0

**Comment by zonque** [comment] 2015-12-18 16:50
Ah, wait, take this one instead, please:

https://github.com/zonque/systemd/commit/4bb67803

**Comment by mischief** [comment] 2015-12-20 01:12
@zonque with https://github.com/zonque/systemd/commit/4bb67803 i can no longer reproduce this with polkit, but i can with update_engine.. not clear if the race gap is just smaller, and the timing of polkit vs update_engine differs enough (maybe that slow js engine in polkit :smile:) or if it is some issue with update_engine itself.

**Comment by mischief** [comment] 2015-12-20 01:18
woops, i lied still happens with polkit.service. i didn't let my repro run long enough. have you been able to reproduce this yourself?

**Comment by zonque** [comment] 2015-12-20 11:38
Strange. My patch definitely fixes a bug. Without it, I could mostly reproduce the issue with the polkit service getting stuck in 'deactivating', but now, I don't see that anymore. Fun fact is that the bug itself is unrelated to bbc2908.

Could you post the output of `systemd-analyze dump`, `systemctl status polkit.service`, `ps aufx` and `busctl` from a system where the service is stuck? I wanna make sure the process owning the name systemd is waiting for is in fact the one systemd started itself, etc.

**Comment by zonque** [comment] 2015-12-21 00:14
I ran my test suite for more than 14 hours straight now, without any hick-ups. Whatever it is your system still shows is most certainly a separate issue. I'll file a PR tomorrow.

**Comment by zonque** [comment] 2015-12-21 15:58
Another 5 hours of stress test done, still no fallout. Are you absolutely sure you tested with my test applied, @mischief? You can try current master as well, as #2202 has now been merged.

**Comment by zonque** [comment] 2015-12-21 15:59
(I'm testing with the shell loop commands you provided, btw)

**Comment by mischief** [comment] 2015-12-21 17:46
i'll try master, and give the output of the commands you asked for after the service is stuck in activating.

**Comment by mischief** [comment] 2015-12-21 19:30
@zonque here is the output of `( systemd-analyze dump --no-pager; systemctl status -l --no-pager polkit.service; ps aufx; busctl --no-pager ) > /tmp/debug.txt`: https://gist.github.com/mischief/5a8362b14354fe605663

**Comment by mischief** [comment] 2015-12-21 19:37
this is against a6cff5d3c0e9a5aef3f1440b089fdb9f30bf444f

**Comment by vcaputo** [comment] 2015-12-22 01:56
FTR I was able to reproduce this using upstream systemd master, with mischief's simple two one-liners:

> while sudo systemctl daemon-reload; do sleep 0.01; done &
> while sudo systemctl is-active polkit.service; do sudo systemctl restart polkit.service; sleep 1; done

Within a few minutes of running, restart got stuck waiting indefinitely, but systemd appeared to continue performing daemon-reloads.

**Comment by zonque** [comment] 2015-12-22 09:30
@mischief, @vcaputo could you paste your journal logs somewhere? And did you boot with `debug` on the kernel command line?

**Comment by zonque** [comment] 2015-12-22 10:46
Ok, I think I got it. During `daemon-reload`, we don't give up the DBus connection, hence we don't call into the bus name resync method at all. I confused this with `daemon-reexec`, sorry. Please try this patch: https://github.com/zonque/systemd/commit/65353406

The reason why it didn't show up anymore here is that I booted with `debug`, which apparently affects the timing so much that it suppresses the bug. Oh, well.

**Comment by mischief** [comment] 2015-12-22 19:24
could not reproduce with debug on as well, i just tried. probably journald being a bit latent, which @vcaputo is working on :)

**Comment by mischief** [comment] 2015-12-22 20:03
i believe this has fixed the issue. i can no longer get polkit stuck in activating.

**Comment by zonque** [comment] 2015-12-23 00:18
@mischief ok, thanks a lot for testing!

**Comment by mischief** [comment] 2015-12-23 00:21
thank you for solving the mystery and fixing bugs in the process :-)

**Closed as completed** 2015-12-23 23:46 UTC
Labels: pid1, release-critical, regression ⚠️
