### ISSUE TITLE
systemd-detect-virt does not detect kvm with Hyper-v Enlightenments

### ISSUE THREAD

**Issue by slackbits** [systemd/systemd#17894] opened 2020-12-08 02:17 UTC
Synology's Virtual Machine Manager runs QEMU/KVM with Hyper-v Enlightenments. According to the [QEMU documentation](https://github.com/qemu/qemu/blob/master/docs/hyperv.txt), KVM running with Hyper-V Enlightenments will "When any set of the Hyper-V enlightenments is enabled, QEMU changes hypervisor
identification (CPUID 0x40000000..0x4000000A) to Hyper-V. KVM identification
and features are kept in leaves 0x40000100..0x40000101." This seems similar to another issue, with [Xen](https://github.com/systemd/systemd/issues/7165#issuecomment-338678950), although it did not advertise as Microsoft, just "other".

I am logging this, an possibly can take a look, but my C is rusty, and only good enough to test around. I do not know exactly how to check the "leaves", nor what might be there on an actual hyper-v environment. I also don't know all the places that should be checked either, I am focused on `detect_vm_cpuid` in virt.c. So if anyone has ideas or guidance, that would be great.

**systemd version the issue has been seen with**
 > systemd 246 (246.6-1ubuntu1)

**Used distribution**
 >Ubuntu 20.10

**Linux kernel version used** (`uname -a`)
> Linux test-ubuntu 5.8.0-31-generic #33-Ubuntu SMP Mon Nov 23 18:44:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
```
someone@machine: ~$ systemd-detect-virt
kvm
```

**Unexpected behaviour you saw**
```
someone@machine: ~$ systemd-detect-virt
microsoft
```

**Comment by poettering** [comment] 2020-12-09 11:17
We do not ave access to such machines. If you want to see this fixed, please supply a patch or find someone who has machines like this and cares for it, and ask them to prep a patch. Otherwise this will likely not get fixed anytime soon.

**Comment by poettering** [comment] 2022-04-04 09:33
So this is almost certainly fixed by #22945 (which fixed #22709 which is a duplicate of this issue, but wasn't noticed before). Closing.

**Closed as completed by poettering** 2022-04-04 09:33 UTC
Labels: detect-virt

**Comment by relayman357** [comment] 2023-06-23 22:32
I'm running an Ubuntu MATE 1.26.0 (Release 22.04.2 LTS) guest on a Synology box and 'system-detect-virt' still gives microsoft response.  

systemctl --version  reports systemd 249 (249.11-0ubuntu3.9)

**Comment by keszybz** [comment] 2023-06-24 13:47
v249 is ancient. The patch that was linked above was merged for v251. Please report if it doesn't work with v253.

**Comment by septatrix** [comment] 2023-07-04 17:25
See #28001 for a new report with v253.4, I can also report this on a machine of mine with v252.6
