### ISSUE TITLE
[RFE] Differentiate between first restart delay and subsequent delays

### ISSUE THREAD

**Issue by OlafvdSpek** [systemd/systemd#7138] opened 2017-10-19 09:10 UTC
If a service crashes (for the first time), I'd like it to be restarted as soon as possible, without any delays.
If it crashes / stops again soon after, a delay is probably in order.

However, I don't think there's a way to do this currently. RestartSec controls both delays.

**Comment by poettering** [comment] 2019-02-26 15:51
I'd say this is pretty much the same as #6129, i.e. iterative control over the restart delay. Let's close this one as duplciate hence. hope that makes sense.

Duplicate of #6129

**Closed as completed by poettering** 2019-02-26 15:51 UTC
Labels: RFE 🎁, pid1, duplicate
