### ISSUE TITLE
SD-BUS API sd_bus_send() is leading to memory increase in application on continuous requests

### ISSUE THREAD

**Issue by romio102** [systemd/systemd#17128] opened 2020-09-22 15:59 UTC
Linked SD-BUS as Library to one application which calls sd_bus_send() API to send 6k char buffer per 20 milli sec rate. After 1 min or 2, observing that application sudden spikes in application memory in order of 50-100 MBs.
I also tried using sd_bus_emit_properties_changed() to send the same data at same rate, but that leads to another error "Transport endpoint is not connected".
Are the above APIs shouldnt be used for sending frequent large size data packets?
Is SD-BUS is not recommended for sending the large size of data on higher rate (6k char buffer per 20 millisec)?

For the smaller set of data (2kb char string) at the rate of 20ms works fine with sd_bus_send().

**Comment by poettering** [comment] 2020-09-23 08:10
My educated guess: the socket runs full, hence sd-buffers enqueues in memory, and you are not processing the connection, i.e. sd_bus_process() is not invoked, hence messages are queued locally without bounds.

**Comment by poettering** [comment] 2020-09-23 08:28
See: #17138 

Anyway, let's close this here, since this is amlsot certainly not a bug. If there are any further questions how to use/drive sd-bus, please contact the mailing list, it's the better place to answer questions.

**Closed as completed by poettering** 2020-09-23 08:28 UTC
