### ISSUE TITLE
systemd-networkd: doesn't add route via dhcp-gateway

### ISSUE THREAD

**Issue by TheJJ** [systemd/systemd#2195] opened 2015-12-20 03:47 UTC
Static routes can't automatically be routed via addresses configured by dhcp:

``` cfg
[Match]
name=ext0

[Network]
DHCP=both
IPForward=true

[Route]
Destination=10.10.0.0/16
```

The network gateway is "unknown" and acquired dynamically via `dhcp`.
The given subnet should then be routed via that gateway just configured by `dhcp`.

Instead, the route is just added without a `via` entry to the device.

I couldn't find any information on how to accomplish this setup, the source suggests that it's not supported to re-use dhcp-fetched information.

**Comment by poettering** [comment] 2016-04-18 16:49
Appears to be mostly a duplicate of #1850. Closing this one in favour of that issue.

**Closed as completed by poettering** 2016-04-18 16:49 UTC
Labels: RFE 🎁, network, dhcp, duplicate
