### ISSUE TITLE
systemd keeps remounting unused filesystem

### ISSUE THREAD

**Issue by jayeye** [systemd/systemd#6728] opened 2017-09-02 15:29 UTC
### Submission type

 - Bug report
 

### systemd version the issue has been seen with
 systemd --version
systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

> …

### Used distribution
Ubuntu 16.04.2 LTS
> …

### In case of bug report: Expected behaviour you didn't see

> …

### In case of bug report: Unexpected behaviour you saw

I unmount a filesystem that nothing should be using, and systemd remounts it

> …

### In case of bug report: Steps to reproduce the problem

there is an entry in for a filesystem in /etc/fstab. It gets mounted at boot time, as it should. If at some point I unmount it, systemd remounts it after a few seconds.

> …

**Comment by bl33pbl0p** [comment] 2017-09-02 17:23
Can you paste `systemctl cat <mountpoint>`?

**Comment by jayeye** [comment] 2017-09-03 19:44
```
$ systemctl cat /var/tmp/ingestor
# /run/systemd/generator/var-tmp-ingestor.mount
# Automatically generated by systemd-fstab-generator

[Unit]
SourcePath=/etc/fstab
Documentation=man:fstab(5) man:systemd-fstab-generator(8)
Before=local-fs.target
Requires=systemd-fsck@dev-disk-by\x2dlabel-var\x2dtmp\x2dingestor.service
After=systemd-fsck@dev-disk-by\x2dlabel-var\x2dtmp\x2dingestor.service

[Mount]
What=/dev/disk/by-label/var-tmp-ingestor
Where=/var/tmp/ingestor
Type=ext4
Options=defaults,data=writeback,noatime
```

where `/var/tmp/ingestor` is, of course, where a program called `ingestor` keeps its temporary stuff. 

My point is that mount/umount should never have to know about systemd. If I manually unmount something, systemd should figure out that I unmounted manually and leave it alone.

**Comment by boucman** [comment] 2017-09-03 20:45
that sounds weird, systemd is not supposed to do that... 
you are sure you didn't create an automount ? that no one else is remounting ?

**Comment by poettering** [comment] 2017-09-04 08:29
Please note that we don't track issues with systemd versions older than the two most current upstream systemd versions here. 229 is way older than that. Since 229 there have been a number of updates regarding dependency management for mounts.

Note that the bug submission form, as well as the contribution guidelines highlight expressly that we only track issues in current systemd versions, in order to save you from this kind of frustration. 

Closing this now, since this is too old. Please reopen/file a new issue, if you can reproduce the issue with current systemd. Thank you for understanding.

Also, please always include the relevant bits of configuration when you file a bug. Specifically, in this case, you need to include the actual /etc/fstab line at least.

**Closed as completed by poettering** 2017-09-04 08:29 UTC
Labels: version-too-ancient
