### ISSUE TITLE
tries to rename VLAN interface

### ISSUE THREAD

**Issue by Zugschlus** [systemd/systemd#11992] opened 2019-03-13 18:26 UTC
This is Debian Bug [#920446](http://bugs.debian.org/920446), seen in Debian unstable, with systemd 241, in March 2019. I am the original reporter. The Debian bug report might have additional information that got collected automatically by Debian's bug reporting script.

On my desktop computer, I run some VMs and am using systemd-networkd. The machine has its 'own' network untagged on the ethernet and the VM network tagged.

I have code to rename my ethernet interface to lanc0 to have consistent interface naming across my machines:

/etc/systemd/network/*lanc0*
==> /etc/systemd/network/10-lanc0.link <==
[Match]
MACAddress=54:04:a6:82:21:00
Name=en*

[Link]
Name=lanc0
WakeOnLan=magic

==> /etc/systemd/network/lanc0.network <==
[Match]
Name=lanc0

[Network]
DHCP=yes
IPForward=yes
IPv6AcceptRA=1

[Network]
VLAN=int192

Then I have int192 defined as the VLAN interface for the VMs:
[15/5076]mh@fan:~ $ head -n-0 /etc/systemd/network/*int192*
==> /etc/systemd/network/int192.netdev <==
[NetDev]
Name=int192
Kind=vlan

[VLAN]
Id=192

==> /etc/systemd/network/int192.network <==
[Match]
Name=int192

[Network]
DHCP=no
IPv6AcceptRA=no

This used to work fine until December 29, when systemd 239-15 was replaced with systemd 240-2 on my system during an update.

Since then, it looks like the /etc/systemd/network/10-lanc0.link code also matches the int192 interface, so the code tries to rename it to lanc0 as well, which doesn't succeed because there is already a lanc0,
and the interface ends up as "renameNUM" with some arbitrary number. Adding the Name=en* line to 10-lanc0.link didnt help either. This happens only intermittently, about two out of three boots. I don't  oot the machine too often, so my statistics might be skewed a bit,

What am I supposed to configure if I want the physical ethernet renamed AND a VLAN interface on it?

Greetings
Marc

**Comment by yuwata** [comment] 2019-03-14 04:09
The vlan devices have the same mac address of the stacked interface, in this case, `lanc0`. So, if you use some kind of stacked netdevs, then it is not a good idea to use `MACAddress=` in `[Match]` section. See the recent similar report in #11921.

Also, .link file does not support `Name=` setting in `[Match]` section. Maybe, you mean `OriginalName=`?

Moreover, using `OriginalName=en*` in `[Match]` section is not a good idea. To make the setting works, the interface must be renamed more than once, `ethX` -> `enYYY` -> `lanc0`. So, you need to trigger an extra `add` uevent manually.

I guess, adding `Type=!vlan` in `[Match]` section of the .link file may help you.

I will try to investigate why your settings work with v239.

**Comment by yuwata** [comment] 2019-03-14 04:29
Ah, I guess naming scheme is v240. Relevant PR is #11449.

Before v240, interface is renamed only once. So, even if your vlan interface matches the .link file, re-renaming is not performed.
But, since v240, renaming requested by .link file is always applied. So, your vlan interface matches the .link file, _and_ renamed to the specified value.
Since v241, such a renaming behavior can be controlled via `net.naming-scheme=` kernel command line option. If you want to keep the v239 naming scheme, then please try to set `net.naming-scheme=v239`.

**Comment by poettering** [comment] 2019-03-14 09:25
Hmm, so I figure we can close this? I think the issue is now explained thoroughly, I guess? And there's a local fix available, too, even...

**Comment by yuwata** [comment] 2019-03-14 09:26
Yeah, let's close.

**Closed as completed by yuwata** 2019-03-14 09:26 UTC
Labels: udev, not-a-bug

**Comment by jvsalo** [comment] 2020-01-04 20:14
In case someone is using bridges and VLANs at the same time, both sharing MAC addresses with the underlying interface, the syntax to avoid renaming either is: Type=!vlan bridge
