### ISSUE TITLE
PathExists in path unit when paired with ConditionPathExists in triggered service makes pid1 unresponsive

### ISSUE THREAD

**Issue by joshuamiller01** [systemd/systemd#17433] opened 2020-10-23 17:04 UTC
**systemd version the issue has been seen with**
246

**Used distribution**
CentOS7

**Linux kernel version used** (`uname -a`)
5.2.9

**CPU architecture issue was seen on**
x86_64

**Expected behaviour you didn't see**
path unit fires upon the existence of `PathExists`, corresponding service unit runs once, systemd remains responsive

**Unexpected behaviour you saw**
path unit fired after file was touched, service unit also fired, but pid1 CPU goes to 100%, and calls via `systemctl` (both via sudo and as root) hang.

**Steps to reproduce the problem**
[root@box ~]# cat /etc/systemd/system/test123.path
[Path]
PathExists=/tmp/test123

[Install]
WantedBy=multi-user.target

[root@box ~]# cat /etc/systemd/system/test123.service
[Unit]
Description=Test 123
ConditionPathExists=!/tmp/nopenopenope

[Service]
Type=oneshot
ExecStart=/bin/touch /tmp/nopenopenope

[Install]
WantedBy=multi-user.target

[root@box ~]# systemctl daemon-reload
[root@box ~]# systemctl start test123.path
[root@box ~]# touch /tmp/test123

[root@box ~]# systemctl status test123.service
   ... hangs  

/var/log/messages has many thousands of messages about:
"systemd[1]: Condition check resulted in Test 123 being skipped."

Removing the original trigger file (`rm /tmp/test123`) restores systemd responsiveness

**Comment by mbiebl** [comment] 2020-10-23 17:06
Sounds like a duplicate of #16669

**Comment by joshuamiller01** [comment] 2020-10-23 17:09
Removing the `ConditionPathExists` property changes the behavior - pid1 never goes unresponsive, and the service and path units are marked as failed with "failed (Result: start-limit-hit)" and " failed (Result: unit-start-limit-hit)" respectively.

**Comment by anitazha** [comment] 2020-10-23 18:40
Sounds like the rate limiting was fixed properly for unit start as part of #16669, but not condition checking?

**Comment by keszybz** [comment] 2021-05-15 20:10
https://bugzilla.redhat.com/show_bug.cgi?id=1919538

**Comment by DaanDeMeyer** [comment] 2021-08-20 15:47
So it turns out we check unit conditions before we check start rate limiting so if conditions fail no rate limiting gets applied and we can enter a busy loop. I'm not too familiar with the code, but intuitively it seems like this could be fixed if we just move the start rate limiting checks before the condition checks. 

To achieve this I think we'd need to add some `test_ratelimit` or more generic `verify/validate` method to the unit vtable that is executed earlier in the unit startup process before the condition checks where the ratelimit checks can be done per unit type so that the ratelimit properly applies.

cc @poettering  @keszybz does this seem like a decent solution?

**Closed as completed** 2021-08-25 21:04 UTC
Labels: pid1, downstream/fedora
