### ISSUE TITLE
[Install] in drop-in ignored

### ISSUE THREAD

**Issue by rdaysky** [systemd/systemd#26857] opened 2023-03-17 02:00 UTC
### systemd version the issue has been seen with

252

### Used distribution

Ubuntu 22.10

### Linux kernel version used

5.19.0-35-generic

### CPU architectures issue was seen on

None

### Component

systemctl

### Expected behaviour you didn't see

Ability to systemctl enable the unit

### Unexpected behaviour you saw

Doesn’t enable the unit

### Steps to reproduce the problem

0. Desire to have units parameterized by two parameters
1. Put all the configuration into xyzzy-.socket.d/base.conf, refer to %i and %j there
2. Create empty unit files named xyzzy-a@.socket, xyzzy-b@.socket etc., with the intention of using them as xyzzy-[param1]@[param2].service
3. Run `systemctl cat xyzzy-foo@bar.socket`, observe that it sees, among other things, the [Install] section, taken from the drop-in base.conf file
4. Run `systemctl enable xyzzy-foo@bar.socket`, but it shows the error message below.

### Additional program output to the terminal or log subsystem illustrating the issue

```sh
The unit files have no installation config (WantedBy=, RequiredBy=, Also=,
Alias= settings in the [Install] section, and DefaultInstance= for template
units). This means they are not meant to be enabled using systemctl.
 
Possible reasons for having this kind of units are:
• A unit may be statically enabled by being symlinked from another unit's
  .wants/ or .requires/ directory.
• A unit's purpose may be to act as a helper for some other unit which has
  a requirement dependency on it.
• A unit may be started when needed via activation (socket, path, timer,
  D-Bus, udev, scripted systemctl call, ...).
• In case of template units, the unit is meant to be enabled with some
  instance name specified.
```

**Comment by YHNdnzj** [comment] 2023-03-17 07:26
Seems to be a duplicate of https://github.com/systemd/systemd/issues/22230

**Closed as not planned** 2023-03-17 08:18 UTC
Labels: bug 🐛, systemctl, duplicate

**Comment by deliciouslytyped** [comment] 2023-06-04 20:07
For those like me getting here from a search engine, this *appears* to be resolved on the above linked issue.
