### ISSUE TITLE
systemd does not cache encryption password

### ISSUE THREAD

**Issue by heftig** [systemd/systemd#2378] opened 2016-01-20 01:05 UTC
At boot, systemd asks for the password for both root and swap volumes, in random order. Since the  passwords are identical, I would expect systemd to not ask again once it has a valid password.

The problem seems to be that the started systemd-cryptsetup instances simultaneously try the keyring, fail, then block on the agent.

Fedora apparently includes additional password caching in Plymouth, but Plymouth is not used in Arch.

Log:

```
Jan 20 01:01:04 philomeena kernel: sd 0:0:0:0: [sda] Attached SCSI disk
Jan 20 01:01:04 philomeena systemd[1]: Found device Samsung_SSD_840_PRO_Series strike-root.
Jan 20 01:01:04 philomeena systemd[1]: Starting Cryptography Setup for root...
Jan 20 01:01:04 philomeena systemd[1]: Started Dispatch Password Requests to Console.
Jan 20 01:01:04 philomeena kernel: device-mapper: uevent: version 1.0.3
Jan 20 01:01:04 philomeena kernel: device-mapper: ioctl: 4.34.0-ioctl (2015-10-28) initialised: dm-devel@redhat.com
Jan 20 01:01:04 philomeena systemd[1]: Found device Samsung_SSD_840_PRO_Series strike-swap.
Jan 20 01:01:04 philomeena systemd[1]: Starting Cryptography Setup for swap...
Jan 20 01:01:04 philomeena systemd[1]: Started Dispatch Password Requests to Console.
Jan 20 01:01:04 philomeena kernel: clocksource: Switched to clocksource tsc
Jan 20 01:01:13 philomeena kernel: random: nonblocking pool is initialized
Jan 20 01:01:14 philomeena systemd-cryptsetup[191]: Set cipher aes, mode xts-plain64, key size 256 bits for device /dev/disk/by-uuid/c4678787-8158-4b1d-b351-e41a69d3ea01.
Jan 20 01:01:17 philomeena kernel: NET: Registered protocol family 38
Jan 20 01:01:17 philomeena kernel: raid6: sse2x1   gen()  7938 MB/s
Jan 20 01:01:17 philomeena kernel: raid6: sse2x1   xor()  7433 MB/s
Jan 20 01:01:17 philomeena kernel: raid6: sse2x2   gen() 12917 MB/s
Jan 20 01:01:17 philomeena kernel: raid6: sse2x2   xor()  8593 MB/s
Jan 20 01:01:17 philomeena kernel: raid6: sse2x4   gen() 14787 MB/s
Jan 20 01:01:17 philomeena kernel: raid6: sse2x4   xor() 10419 MB/s
Jan 20 01:01:17 philomeena kernel: raid6: avx2x1   gen() 19818 MB/s
Jan 20 01:01:17 philomeena kernel: raid6: avx2x2   gen() 23063 MB/s
Jan 20 01:01:17 philomeena kernel: raid6: avx2x4   gen() 26373 MB/s
Jan 20 01:01:17 philomeena kernel: raid6: using algorithm avx2x4 gen() 26373 MB/s
Jan 20 01:01:17 philomeena kernel: raid6: using avx2x2 recovery algorithm
Jan 20 01:01:17 philomeena kernel: xor: automatically using best checksumming function:
Jan 20 01:01:17 philomeena kernel:    avx       : 30891.600 MB/sec
Jan 20 01:01:17 philomeena kernel: Btrfs loaded
Jan 20 01:01:17 philomeena kernel: BTRFS: device label strike-root devid 1 transid 437 /dev/dm-0
Jan 20 01:01:17 philomeena systemd[1]: Found device /dev/mapper/root.
Jan 20 01:01:17 philomeena systemd[1]: Started Cryptography Setup for root.
Jan 20 01:01:20 philomeena systemd-tty-ask-password-agent[194]: Invalid password file /run/systemd/ask-password/ask.rPyFrq
Jan 20 01:01:20 philomeena systemd-tty-ask-password-agent[194]: Failed to show password: Bad message
Jan 20 01:01:20 philomeena systemd-tty-ask-password-agent[194]: Invalid password file /run/systemd/ask-password/ask.as3DBt
Jan 20 01:01:20 philomeena systemd-tty-ask-password-agent[194]: Failed to show password: Bad message
Jan 20 01:01:20 philomeena systemd-cryptsetup[196]: Set cipher aes, mode xts-plain64, key size 256 bits for device /dev/disk/by-uuid/2f34d22c-3364-4c34-96c1-742de382de4b.
Jan 20 01:01:22 philomeena systemd[1]: Started Cryptography Setup for swap.
Jan 20 01:01:22 philomeena systemd[1]: Found device /dev/mapper/swap.
```

Also, as seen two tty-ask-password-agents get started. It seems one of them gets blocked, then once the other agent exits, complains that it cannot read the files the other agent consumed.

**Comment by heftig** [comment] 2016-01-20 16:42
I guess the keyname should also be included in the Ask request, so that the agent can do ask_password_keyring?

Could this leak keys across users that it shouldn't?

**Comment by genodeftest** [comment] 2016-01-26 13:07
For security reasons I'd vote against caching this password in user space. Using the same password for two different LUKS containers doesn't sound like a good thing to do either.

On Fedora, Plymouth is an optional component.

**Comment by poettering** [comment] 2016-01-27 15:55
@genodeftest password caching is implemented in systemd already, using the kernel keyring.

**Comment by main--** [comment] 2017-11-08 12:16
My workaround for now is a new unit with `Before=cryptsetup-pre.target` that invokes `/usr/bin/systemd-ask-password --keyname=cryptsetup fucksystemd --no-tty --no-output`.

This mostly does the job, however on my system lvm2-pvscan used to hang (presumably because it already switches root while an inscance of pvscan is still running - it complains about missing files). Now that I added my new SSD it just crashes (something about multiple concurrent invocations of pvscan not being supported?) but still works so whatever.

**Comment by behrmann** [comment] 2018-11-21 18:15
@heftig have you ever solved this problem? I too have been trying to get passphrase caching for an encrypted root and swap to work on a plain Arch (not using Plymouth) and it just does not work for me. 
If this is still a (somewhat) general problem, I'd be glad to help to resolve this.

**Comment by poettering** [comment] 2018-11-21 18:38
Hmm, #10404 probably fixes this. Can you check? I figure we should close this bug

**Comment by behrmann** [comment] 2018-11-21 18:48
@poettering Thanks for the hint, I'll try this out, but I'm away from the machine I'm trying to get this to work on now. I'll get back to you next week.

**Comment by behrmann** [comment] 2018-11-26 16:34
I just built the current systemd v239-stable (63f95c0297aea62ce47d1389e5221c54992f580e) and cherry-picked c7b7d74e81bae65ffef38f46dd6abf0b8a9c3d4f on top. I can confirm, that it solves this issue. Thanks a lot!

**Comment by behrmann** [comment] 2019-01-26 13:53
I can confirm, that on the current systemd-stable in Arch (f02b5472c6f0c41e5dc8dc2c84590866baf937ff with 8ca9e92c742602b8bcd431001e6f5b78c28c184f and ee0b9e721a368742ac6fa9c3d9a33e45dc3203a2 cherrypicked on top) one is asked for both (all?) devices if one initially mistypes a password.

**Comment by yuwata** [comment] 2019-01-26 13:56
So #10404 was already merged. Let's close this.

**Closed as completed by yuwata** 2019-01-26 13:56 UTC
Labels: ask-password
