### ISSUE TITLE
systemd-udevd[492]: eth1: Failed to rename network interface 4 from 'eth2' to 'eth1': File exists

### ISSUE THREAD

**Issue by raJeev-M** [systemd/systemd#29957] opened 2023-11-09 11:40 UTC
Using Ubuntu Jammy.

systemd version: 249

I have three interfaces eth0 / eth1 / eth2.

In bionic, I used udev rules to map the MAC to eth* interfaces and that rule is no longer working in Ubuntu Jammy.

Ex, currently I have:
```
0 -> eth0
2 -> eth1
1 -> eth2
```
what I want to achieve from udev rules is
```
0 -> eth0
1 -> eth1
2 -> eth2
```
But when the rules are executed, I see below errors in syslog (rules are working for many years till now in bionic)
```
 systemd-udevd[492]: eth1: Failed to rename network interface 4 from
 'eth2' to 'eth1': File exists 
 systemd-udevd[492]: eth2: Failed to process device, ignoring: File exists 
 systemd-udevd[501]: eth2: Failed to rename network interface 3 from 'eth1' to 
 'eth2': File exists
 systemd-udevd[501]: eth1: Failed to process device, ignoring: File
 exists
```
The issue seem to be clear tho, Kernel takes the eth* names and assign it to the NICs detected, later on, when the rule tries to re-map... udev reports interface name are already taken (file exists) ... now two things...

1) In what specific commit do we have old behaviour changed? 
2) How to fix it.

**Comment by YHNdnzj** [comment] 2023-11-09 11:43
This is not supported and is a duplicate of #29073. You can find justifications there.

**Closed as not planned by YHNdnzj** 2023-11-09 11:43 UTC
Labels: udev, not-supported, duplicate

**Comment by raJeev-M** [comment] 2023-11-09 12:08
@YHNdnzj, Thanks for your response, Just for clarity, it was working in 18.04 Ubuntu, so, it's like you udev stopped supporting it?

**Comment by YHNdnzj** [comment] 2023-11-09 12:15
> so, it's like udev stopped supporting it?

No, it was and could never be properly supported. These nodes are managed by kernel, and any renaming done by udev is predestined to run into races. Maybe such setup once worked under specific kernel + udev combinations, but there's absolutely no warranty.

**Comment by raJeev-M** [comment] 2023-11-09 12:18
Thanks again, this put a full stop to my endless searches about this topic in the internet, out of curiosity, any alternative that could reliably work? @YHNdnzj

**Comment by YHNdnzj** [comment] 2023-11-09 12:21
> any alternative that could reliably work?

Any other prefixes that aren't `eth` and `wlan` should work, such as `wiredX` and `wirelessX`.
