### ISSUE TITLE
Deletion of static routes on interface configured by DHCP

### ISSUE THREAD

**Issue by aleksander** [systemd/systemd#12951] opened 2019-07-04 06:24 UTC
**systemd version the issue has been seen with**
> 242.32

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > Interface IP addresses configured by DHCP and routes configured statically.

**Unexpected behaviour you saw**
 > Interface IP addresses configured by DHCP and no static routes configured.

**Steps to reproduce the problem**

> I have the following .network config:
```
[Match]
MACAddress=XX:XX:XX:XX:XX:XX

[Network]
DHCP=yes
DNS=172.20.0.3
Domains=XXX.lan.

[Route]
Destination=192.168.202.0/24

[Route]
Destination=172.20.0.0/16

[Route]
Destination=172.22.0.0/16

[Route]
Destination=172.23.0.0/16

[Route]
Destination=172.25.0.0/16

[DHCP]
UseRoutes=no
```
> After systemd-networkd restart I see static routes configured:
```
» ip a s dev XXX
3: XXX: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether XX:XX:XX:XX:XX:XX brd ff:ff:ff:ff:ff:ff
    inet 172.21.0.254/16 brd 172.21.255.255 scope global dynamic XXX
       valid_lft 11138sec preferred_lft 11138sec
    inet6 fe80::96de:80ff:fe76:86af/64 scope link 
       valid_lft forever preferred_lft forever
```
```
» ip r
172.20.0.0/16 dev XXX proto static 
172.21.0.0/16 dev XXX proto kernel scope link src 172.21.0.254 
172.22.0.0/16 dev XXX proto static 
172.23.0.0/16 dev XXX proto static 
172.25.0.0/16 dev XXX proto static 
192.168.202.0/24 dev XXX proto static 
```
> But after some time (it's DHCP lease time I suppose) static routes got deleted:
```
» ip r
172.21.0.0/16 dev XXX proto kernel scope link src 172.21.0.254 
```

**Comment by yuwata** [comment] 2019-07-05 21:42
I cannot reproduce the issue with the current git master. It seems that this is already fixed by b5799eeb0787deacb30d5984f6ac78f88f23b97e.
@ssahani Could you comment on this?

**Comment by ssahani** [comment] 2019-07-05 23:17
That was the precise case we fixed it .  @aleksander Can you reproduce with the current git ?

**Closed as completed** 2019-07-05 23:23 UTC
Labels: bug 🐛, network, already-fixed

**Comment by yuwata** [comment] 2019-07-05 23:24
@ssahani Thanks.
