### ISSUE TITLE
systemd-journal-upload dumps core due to SIGABRT, watchdog timeout

### ISSUE THREAD

**Issue by TKSpyrop** [systemd/systemd#2439] opened 2016-01-26 12:53 UTC
Hello,
I am facing the following issue:

systemd[1]: journal-upload.service: Watchdog timeout (limit 20min)!
systemd[1]: journal-upload.service: Main process exited, code=dumped, status=6/ABRT
systemd[1]: journal-upload.service: Unit entered failed state.
systemd[1]: journal-upload.service: Failed with result 'core-dump'.
systemd-coredump[14276]: Process 10510 (systemd-journal) of user 0 dumped core.
                                                      Stack trace of thread 10510:
                                                      #0  0x00007fce15312bd0 poll (libc.so.6)
                                                      #1  0x00007fce15824f03 n/a (libcurl.so.4)
                                                      #2  0x00007fce15820532 curl_multi_wait (libcurl.so.4)
                                                      #3  0x00007fce1581add7 curl_easy_perform (libcurl.so.4)
                                                      #4  0x00007fce160af3ef n/a (systemd-journal-upload)
                                                      #5  0x00007fce15254770 __libc_start_main (libc.so.6)
                                                      #6  0x00007fce160affa9 n/a (systemd-journal-upload)

where journal-upload.service is a systemd service executing the command
"/usr/lib/systemd/systemd-journal-upload -m --save-state -u http://${JOURNAL_REMOTE_ADDRESS}:${PORT}"
and has a "WatchdogSec=20min" (systemd version used is 225).

coredump backtrace:
(gdb) bt
#0  0x00007fcab07f8bd0 in __poll_nocancel () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007fcab0d0af03 in Curl_poll () from /usr/lib64/libcurl.so.4
#2  0x00007fcab0d06532 in curl_multi_wait () from /usr/lib64/libcurl.so.4
#3  0x00007fcab0d00dd7 in curl_easy_perform () from /usr/lib64/libcurl.so.4
#4  0x00007fcab15953ef in perform_upload (u=0x7fff4784fa70) at src/journal-remote/journal-upload.c:493
#5  main (argc=5, argv=0x7fff4784fd38) at src/journal-remote/journal-upload.c:854

I am aware of this issue https://github.com/systemd/systemd/issues/2010, could it be a similar case? In this one you suggest to increase watchdog timeout, but in my case it is already as long as 20min.
What can have caused this stuck?

Thank you

**Comment by poettering** [comment] 2016-01-26 19:48
Hmm, journal-upload shouldn't block on socket I/O I figure, or not use the watchdog...

@keszybz?

**Comment by poettering** [comment] 2016-01-27 01:11
Duplicate of #2010

**Closed as completed by poettering** 2016-01-27 01:11 UTC
Labels: bug 🐛, duplicate, journal-remote
