### ISSUE TITLE
systemd-networkd: DHCPv6 client has stopped working / receiving replies

### ISSUE THREAD

**Issue by jacob-pro** [systemd/systemd#28065] opened 2023-06-17 13:08 UTC
### systemd version the issue has been seen with

245.4-4ubuntu3.22

### Used distribution

Ubuntu 20.04 (Server)

### Linux kernel version used

5.15.0-1037-oracle

### CPU architectures issue was seen on

x86_64

### Component

systemd-networkd

### Expected behaviour you didn't see

systemd-networkd DHCPv6 client has stopped working. Whilst it still continues to send DHCPv6 solicit messages, it no longer seems to detect the responses or apply the received IPv6 address.

When I run the command `sudo dhclient -6 -d ens3` then it sucessfully aquires an IPv6 address, so the DHCPv6 server is clearly working.

### Steps to reproduce the problem

This is an Ubuntu 20.04 server running on Oracle OCI Compute cloud instance.

When running:

```
$ sudo systemctl restart systemd-networkd
```

I followed the networkd logs, which show a DHCPv6 solicit being sent:

```
$ journalctl --unit=systemd-networkd --follow | grep -E 'ens3|DHCPv6'
Jun 17 12:55:29 calpol systemd-networkd[13420]: DHCPv6 CLIENT: Sent SOLICIT
Jun 17 12:55:29 calpol systemd-networkd[13420]: DHCPv6 CLIENT: Next retransmission in 1min 44s
Jun 17 12:55:32 calpol systemd-networkd[13420]: ens3: Acquiring DHCPv6 lease on NDisc request
Jun 17 12:55:32 calpol systemd-networkd[13420]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::200:17ff:fe3f:5a6, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
Jun 17 12:55:32 calpol systemd-networkd[13420]: ens3: Configuring route: dst: 2603:c020:c004:1f00::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
Jun 17 12:55:47 calpol systemd-networkd[13420]: ens3: Acquiring DHCPv6 lease on NDisc request
Jun 17 12:55:47 calpol systemd-networkd[13420]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::200:17ff:fe3f:5a6, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
Jun 17 12:55:47 calpol systemd-networkd[13420]: ens3: Configuring route: dst: 2603:c020:c004:1f00::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: New device has no master, continuing without
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Flags change: +UP +LOWER_UP +RUNNING +MULTICAST +BROADCAST
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Link 2 added
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: udev initialized link
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Saved original MTU: 9000
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Remembering foreign address: fe80::17ff:fe02:321e/64 (valid forever)
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Gained IPv6LL
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Remembering foreign address: 10.0.0.127/24 (valid forever)
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Remembering route: dst: ff00::/8, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: multicast
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Remembering route: dst: fe80::17ff:fe02:321e/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: local
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Remembering route: dst: fe80::/128, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: local, proto: kernel, type: anycast
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Remembering route: dst: n/a, src: n/a, gw: fe80::200:17ff:fe3f:5a6, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Remembering route: dst: fe80::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Remembering route: dst: 2603:c020:c004:1f00::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: kernel, type: unicast
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Remembering route: dst: 2603:c020:c004:1f00::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Remembering route: dst: 10.0.0.255/32, src: n/a, gw: n/a, prefsrc: 10.0.0.127, scope: link, table: local, proto: kernel, type: broadcast
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Remembering route: dst: 10.0.0.127/32, src: n/a, gw: n/a, prefsrc: 10.0.0.127, scope: host, table: local, proto: kernel, type: local
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Remembering route: dst: 169.254.0.0/16, src: n/a, gw: n/a, prefsrc: 10.0.0.127, scope: link, table: main, proto: dhcp, type: unicast
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Remembering route: dst: 10.0.0.0/24, src: n/a, gw: n/a, prefsrc: 10.0.0.127, scope: link, table: main, proto: kernel, type: unicast
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Remembering route: dst: n/a, src: n/a, gw: 10.0.0.1, prefsrc: 10.0.0.127, scope: global, table: main, proto: dhcp, type: unicast
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Link state is up-to-date
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: found matching network '/run/systemd/network/10-netplan-ens3.network'
Jun 17 12:55:52 calpol systemd-networkd[13468]: Setting '/proc/sys/net/ipv6/conf/ens3/disable_ipv6' to '0'
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: IPv6 successfully enabled
Jun 17 12:55:52 calpol systemd-networkd[13468]: Setting '/proc/sys/net/ipv6/conf/ens3/proxy_ndp' to '0'
Jun 17 12:55:52 calpol systemd-networkd[13468]: Setting '/proc/sys/net/ipv6/conf/ens3/use_tempaddr' to '0'
Jun 17 12:55:52 calpol systemd-networkd[13468]: Setting '/proc/sys/net/ipv6/conf/ens3/accept_ra' to '0'
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Started LLDP.
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Setting address genmode for link
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Setting address genmode done.
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Acquiring DHCPv4 lease
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Discovering IPv6 routers
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: State changed: pending -> configuring
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: DHCPv4 address 10.0.0.127/24 via 10.0.0.1
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Remembering updated address: 10.0.0.127/24 (valid forever)
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Configuring route: dst: n/a, src: n/a, gw: 10.0.0.1, prefsrc: 10.0.0.127, scope: global, table: main, proto: dhcp, type: unicast
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: Configuring route: dst: 169.254.0.0/16, src: n/a, gw: n/a, prefsrc: 10.0.0.127, scope: link, table: main, proto: dhcp, type: unicast
Jun 17 12:55:52 calpol systemd-networkd[13468]: ens3: State changed: configuring -> configured
Jun 17 12:55:53 calpol systemd-networkd[13468]: DHCPv6 CLIENT: Started in Managed mode
Jun 17 12:55:53 calpol systemd-networkd[13468]: ens3: Acquiring DHCPv6 lease on NDisc request
Jun 17 12:55:53 calpol systemd-networkd[13468]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::200:17ff:fe3f:5a6, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
Jun 17 12:55:53 calpol systemd-networkd[13468]: ens3: Configuring route: dst: 2603:c020:c004:1f00::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
Jun 17 12:55:53 calpol systemd-networkd[13468]: DHCPv6 CLIENT: Sent SOLICIT
Jun 17 12:55:53 calpol systemd-networkd[13468]: DHCPv6 CLIENT: Next retransmission in 1s
Jun 17 12:55:54 calpol systemd-networkd[13468]: DHCPv6 CLIENT: Sent SOLICIT
Jun 17 12:55:54 calpol systemd-networkd[13468]: DHCPv6 CLIENT: Next retransmission in 1s
Jun 17 12:55:56 calpol systemd-networkd[13468]: DHCPv6 CLIENT: Sent SOLICIT
Jun 17 12:55:56 calpol systemd-networkd[13468]: DHCPv6 CLIENT: Next retransmission in 3s
Jun 17 12:56:00 calpol systemd-networkd[13468]: DHCPv6 CLIENT: Sent SOLICIT
Jun 17 12:56:00 calpol systemd-networkd[13468]: DHCPv6 CLIENT: Next retransmission in 7s
Jun 17 12:56:02 calpol systemd-networkd[13468]: ens3: Acquiring DHCPv6 lease on NDisc request
Jun 17 12:56:02 calpol systemd-networkd[13468]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::200:17ff:fe3f:5a6, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
Jun 17 12:56:02 calpol systemd-networkd[13468]: ens3: Configuring route: dst: 2603:c020:c004:1f00::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
Jun 17 12:56:07 calpol systemd-networkd[13468]: DHCPv6 CLIENT: Sent SOLICIT
Jun 17 12:56:07 calpol systemd-networkd[13468]: DHCPv6 CLIENT: Next retransmission in 14s
Jun 17 12:56:17 calpol systemd-networkd[13468]: ens3: Acquiring DHCPv6 lease on NDisc request
Jun 17 12:56:17 calpol systemd-networkd[13468]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::200:17ff:fe3f:5a6, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
Jun 17 12:56:17 calpol systemd-networkd[13468]: ens3: Configuring route: dst: 2603:c020:c004:1f00::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
Jun 17 12:56:22 calpol systemd-networkd[13468]: DHCPv6 CLIENT: Sent SOLICIT
Jun 17 12:56:22 calpol systemd-networkd[13468]: DHCPv6 CLIENT: Next retransmission in 28s
Jun 17 12:56:32 calpol systemd-networkd[13468]: ens3: Acquiring DHCPv6 lease on NDisc request
Jun 17 12:56:32 calpol systemd-networkd[13468]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::200:17ff:fe3f:5a6, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
Jun 17 12:56:32 calpol systemd-networkd[13468]: ens3: Configuring route: dst: 2603:c020:c004:1f00::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
Jun 17 12:56:47 calpol systemd-networkd[13468]: ens3: Acquiring DHCPv6 lease on NDisc request
Jun 17 12:56:47 calpol systemd-networkd[13468]: ens3: Configuring route: dst: n/a, src: n/a, gw: fe80::200:17ff:fe3f:5a6, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
Jun 17 12:56:47 calpol systemd-networkd[13468]: ens3: Configuring route: dst: 2603:c020:c004:1f00::/64, src: n/a, gw: n/a, prefsrc: n/a, scope: global, table: main, proto: ra, type: unicast
Jun 17 12:56:51 calpol systemd-networkd[13468]: DHCPv6 CLIENT: Sent SOLICIT
Jun 17 12:56:51 calpol systemd-networkd[13468]: DHCPv6 CLIENT: Next retransmission in 57s
```

However packet capture shows there is clearly a DHCPv6 reply:

```
:~$ sudo tshark -i ens3 -Y "dhcpv6"
Running as user "root" and group "root". This could be dangerous.
Capturing on 'ens3'
    1 0.000000000 fe80::17ff:fe02:321e → ff02::1:2    DHCPv6 136 Solicit XID: 0x787bca CID: 00020000ab11c6e706dbc03d304b
    2 0.000953642 fe80::200:17ff:fe3f:5a6 → fe80::17ff:fe02:321e DHCPv6 178 Reply XID: 0x787bca CID: 00020000ab11c6e706dbc03d304b IAA: 2603:c020:c004:1f00:7316:af31:638b:8149
    6 1.965417949 fe80::17ff:fe02:321e → ff02::1:2    DHCPv6 136 Solicit XID: 0x787bca CID: 00020000ab11c6e706dbc03d304b
    7 1.966094767 fe80::200:17ff:fe3f:5a6 → fe80::17ff:fe02:321e DHCPv6 178 Reply XID: 0x787bca CID: 00020000ab11c6e706dbc03d304b IAA: 2603:c020:c004:1f00:7316:af31:638b:8149
   11 5.852170869 fe80::17ff:fe02:321e → ff02::1:2    DHCPv6 136 Solicit XID: 0x787bca CID: 00020000ab11c6e706dbc03d304b
   12 5.852787685 fe80::200:17ff:fe3f:5a6 → fe80::17ff:fe02:321e DHCPv6 178 Reply XID: 0x787bca CID: 00020000ab11c6e706dbc03d304b IAA: 2603:c020:c004:1f00:7316:af31:638b:8149
   81 13.291287774 fe80::17ff:fe02:321e → ff02::1:2    DHCPv6 136 Solicit XID: 0x787bca CID: 00020000ab11c6e706dbc03d304b
   82 13.291907304 fe80::200:17ff:fe3f:5a6 → fe80::17ff:fe02:321e DHCPv6 178 Reply XID: 0x787bca CID: 00020000ab11c6e706dbc03d304b IAA: 2603:c020:c004:1f00:7316:af31:638b:8149
  151 27.983144464 fe80::17ff:fe02:321e → ff02::1:2    DHCPv6 136 Solicit XID: 0x787bca CID: 00020000ab11c6e706dbc03d304b
  152 27.983817956 fe80::200:17ff:fe3f:5a6 → fe80::17ff:fe02:321e DHCPv6 178 Reply XID: 0x787bca CID: 00020000ab11c6e706dbc03d304b IAA: 2603:c020:c004:1f00:7316:af31:638b:8149
  207 56.769988813 fe80::17ff:fe02:321e → ff02::1:2    DHCPv6 136 Solicit XID: 0x787bca CID: 00020000ab11c6e706dbc03d304b
  208 56.770773606 fe80::200:17ff:fe3f:5a6 → fe80::17ff:fe02:321e DHCPv6 178 Reply XID: 0x787bca CID: 00020000ab11c6e706dbc03d304b IAA: 2603:c020:c004:1f00:7316:af31:638b:8149
```

My config is generated by netplan:

```
$ cat /run/systemd/network/10-netplan-ens3.network
[Match]
MACAddress=02:00:17:02:32:1e
Name=ens3

[Network]
DHCP=yes
LinkLocalAddressing=ipv6
DNS=169.254.169.254
Domains=vcn01052146.oraclevcn.com

[DHCP]
CriticalConnection=true
ClientIdentifier=mac
RouteMetric=100
UseMTU=true
```

networkd config:

```
cat /etc/systemd/system/systemd-networkd.service.d/override.conf
[Service]
Environment=SYSTEMD_LOG_LEVEL=debug
```

**Comment by triatic** [comment] 2023-06-21 21:24
I am observing identical behaviour on my own Oracle Cloud Ubuntu 22.04 instance. Having worked through the issue with Oracle support, they are confident that the issue lies with systemd-networkd, given that `dhclient -6` successfully picks up an IPv6 address.

They are instructing users to statically configure IPv6 addresses within netplan in order to mitigate the issue, but clearly the root cause within systemd-networkd needs to be identified and fixed.

**Comment by yuwata** [comment] 2023-06-25 05:40
Sorry, v245 is too old here. Please contact to your downstream, or reproduce the issue with recent releases or the current git HEAD. Closing.

Feel free to request to reopen the page when you reproduce it with newer release.

**Closed as completed by yuwata** 2023-06-25 05:40 UTC
Labels: bug 🐛, network, version-too-ancient
