### ISSUE TITLE
systemd-networkd: Link defaults to NOARP if [Link] section present but there's no explicit ARP setting

### ISSUE THREAD

**Issue by dardok** [systemd/systemd#4760] opened 2016-11-28 14:12 UTC
### Submission type

  - [ x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Gentoo

### In case of bug report: Expected behaviour you didn't see

> Link should default to *not* setting NOARP on a device if no explicit ARP= setting is present in [Link] section.

### In case of bug report: Unexpected behaviour you saw

> Link is set to NOARP if [Link] section present but there's no explicit ARP setting.

### In case of bug report: Steps to reproduce the problem

> Configure a .network device with a [Link] section but do not include an explicit ARP= setting.  The device will be brought up with NOARP set.  If there's no [Link] section at all, device comes up with ARP enabled (i.e. *not* setting NOARP).  If there's an explicit ARP= setting, NOARP will be set only if ARP=no.

I suspect something is zero-ing out the Link struct before networkd-link.c:link_set_flags is called, instead of leaving the arp struct member at -1 (the default set in networkd-network.c:network_load_one).

**Comment by ssahani** [comment] 2016-11-28 16:33
Please take a look .
https://github.com/systemd/systemd/commit/b8b40317d0355bc70bb23a6240a36f3630c4952b

**Comment by dardok** [comment] 2016-11-28 16:46
Yup, that would do it.  Didn't catch that open issue and fix when searching for "ARP".  Thanks, will test but LGTM.

**Comment by poettering** [comment] 2016-11-28 17:23
Duplicate of #4644

**Closed as completed by poettering** 2016-11-28 17:23 UTC
Labels: network, duplicate
