### ISSUE TITLE
Sometimes dbus-daemon will be zombie after killed if dbus.service has Restart=always and RestartSec=1 

### ISSUE THREAD

**Issue by ExtinctFire** [systemd/systemd#14484] opened 2020-01-06 07:18 UTC
**systemd version the issue has been seen with**
> systemd-239-3.fc29.aarch64

**Used distribution**
 > fedora29
**Expected behaviour you didn't see**
 > kill -9 dbus-daemon, dbus-daemon restart successfully soon.

**Unexpected behaviour you saw**
 >kill -9 dbus-daemon, dbus-daemon will be zombie first. After 90s, dbus-daemon restarts successfully.

**Steps to reproduce the problem**
1、add Restart=always and RestartSec=1 in dbus.service
2、systemctl daemon-reload
3、ps aux | grep dbus-daemon to get the pid of dbus-daemon
4、kill -9 (pid of dbus-daemon)
5、ps aux | grep dbus-daemon
6、try more than once, it will happen.

[root@localhost ~]# systemctl status dbus
● dbus.service - D-Bus System Message Bus
   Loaded: loaded (/usr/lib/systemd/system/dbus.service; static; vendor preset: disabled)
   Active: active (running) since Mon 2020-01-06 14:54:13 CST; 3min 49s ago
     Docs: man:dbus-daemon(1)
 Main PID: 1307 (dbus-daemon)
    Tasks: 2 (limit: 4915)
   Memory: 1.4M
   CGroup: /system.slice/dbus.service
           └─1307 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-act>

Jan 06 14:55:24 localhost.localdomain dbus-daemon[1307]: [system] Activating via systemd: service nam>
Jan 06 14:55:24 localhost.localdomain dbus-daemon[1307]: [system] Successfully activated service 'org>
Jan 06 14:55:24 localhost.localdomain dbus-daemon[1307]: [system] Activating via systemd: service nam>
Jan 06 14:55:24 localhost.localdomain dbus-daemon[1307]: [system] Successfully activated service 'org>
Jan 06 14:56:18 localhost.localdomain dbus-daemon[1307]: [system] Activating via systemd: service nam>
Jan 06 14:56:18 localhost.localdomain dbus-daemon[1307]: [system] Successfully activated service 'org>
Jan 06 14:57:12 localhost.localdomain dbus-daemon[1307]: [system] Activating via systemd: service nam>
Jan 06 14:57:12 localhost.localdomain dbus-daemon[1307]: [system] Successfully activated service 'org>
Jan 06 14:58:00 localhost.localdomain dbus-daemon[1307]: [system] Activating via systemd: service nam>
Jan 06 14:58:00 localhost.localdomain dbus-daemon[1307]: [system] Successfully activated service 'org>
[root@localhost ~]# kill -9 1307; ps aux | grep dbus
dbus      1307  0.0  0.0      0     0 ?        Ds   14:54   0:00 [dbus-daemon]
root      1569  0.0  0.0 212960   824 pts/0    S+   14:58   0:00 grep --color=auto dbus
[root@localhost ~]# ps aux | grep dbus
dbus      1307  0.0  0.0      0     0 ?        Zs   14:54   0:00 [dbus-daemon] <defunct>
root      1571  0.0  0.0 212960   836 pts/0    S+   14:58   0:00 grep --color=auto dbus
[root@localhost ~]# ps aux | grep dbus
dbus      1307  0.0  0.0      0     0 ?        Zs   14:54   0:00 [dbus-daemon] <defunct>
root      1573  0.0  0.0 212960   788 pts/0    S+   14:58   0:00 grep --color=auto dbus

**Comment by poettering** [comment] 2020-01-06 11:03
what is the full service file you are using?

**Comment by poettering** [comment] 2020-01-06 11:04
(Also, we only track issues with the two most current systemd versions here, i.e. v243 and v244 here. For everything else, ping downstream, or reproduce on something newer first)

**Comment by poettering** [comment] 2020-01-06 11:05
Actually we had quite a few changes in SIGCHLD handling since 239, hence closing. Please reopen if reproducible in 244. Thanks.

**Comment by ExtinctFire** [comment] 2020-01-06 12:01
> what is the full service file you are using?
the dbus.service:

[root@localhost ~]# cat /usr/lib/systemd/system/dbus.service
[Unit]
Description=D-Bus System Message Bus
Documentation=man:dbus-daemon(1)
Requires=dbus.socket

[Service]
ExecStart=/usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
ExecReload=/usr/bin/dbus-send --print-reply --system --type=method_call --dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig
OOMScoreAdjust=-900
TimeoutStartSec=30
TimeoutStopSec=30
Restart=always
RestartSec=1

-------
I'll try with systemd-243 now.

**Comment by ExtinctFire** [comment] 2020-01-06 12:07
> Actually we had quite a few changes in SIGCHLD handling since 239, hence closing. Please reopen if reproducible in 244. Thanks.

Now I use systemd-243, still has this problem
[root@localhost ~]# systemctl status dbus
● dbus.service - D-Bus System Message Bus
   Loaded: loaded (/usr/lib/systemd/system/dbus.service; static; vendor preset: di>
   Active: active (running) since Fri 2019-12-27 14:03:40 CST; 1 weeks 3 days ago
     Docs: man:dbus-daemon(1)
 Main PID: 1347 (dbus-daemon)
    Tasks: 2
   Memory: 10.1M
   CGroup: /system.slice/dbus.service
           └─1347 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopi>

[root@localhost ~]# systemctl --version
systemd 243 (v243-6)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=legacy

[root@localhost ~]# systemctl cat dbus
# /usr/lib/systemd/system/dbus.service
[Unit]
Description=D-Bus System Message Bus
Documentation=man:dbus-daemon(1)
Requires=dbus.socket

[Service]
ExecStart=/usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile -->
ExecReload=/usr/bin/dbus-send --print-reply --system --type=method_call --dest=org>
OOMScoreAdjust=-900
Restart=always
RestartSec=1
[root@localhost ~]# ps aux | grep dbus
dbus        1347  0.0  0.1  18560  7936 ?        Ssl   2019   0:09 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only
root       27868  0.0  0.0   7168  1600 pts/0    S+   20:03   0:00 grep --color=auto dbus
[root@localhost ~]# kill -9 1347; ps aux | grep dbus
dbus        1347  0.0  0.0      0     0 ?        Zsl   2019   0:09 [dbus-daemon] <defunct>
root       27882  0.0  0.0   7168  1600 pts/0    S+   20:04   0:00 grep --color=auto dbus
[root@localhost ~]# ps aux | grep dbus
dbus        1347  0.0  0.0      0     0 ?        Zs    2019   0:09 [dbus-daemon] <defunct>
root       27905  0.0  0.0   7168  1600 pts/0    S+   20:04   0:00 grep --color=auto dbus
[root@localhost ~]# ps aux | grep dbus
dbus        1347  0.0  0.0      0     0 ?        Zs    2019   0:09 [dbus-daemon] <defunct>
root       27919  0.0  0.0   7168  1600 pts/0    S+   20:05   0:00 grep --color=auto dbus

**Comment by poettering** [comment] 2020-01-06 12:10
can you enable debug logging in pid1 before you reproduce this (systemd-analyze log-level debug), then provide the logs this generates from PID 1.

**Comment by ExtinctFire** [comment] 2020-01-06 12:42
Jan  6 20:17:16 localhost [/bin/bash]: [date] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.3.22.138)]
Jan  6 20:17:29 localhost [/bin/bash]: [ps aux | grep dbus-daemon] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.3.22.138)]
Jan  6 20:17:59 localhost audit[1670]: ANOM_ABEND auid=4294967295 uid=0 gid=0 ses=4294967295 subj=system_u:system_r:virtd_t:s0-s0:c0.c1023 pid=1670 comm="libvirtd" exe="/usr/sbin/libvirtd" sig=6 res=1
Jan  6 20:17:59 localhost libvirtd[1670]: dbus[1670]: arguments to dbus_connection_ref() were incorrect, assertion "connection->generation == _dbus_current_generation" failed in file dbus-connection.c line 2689.
Jan  6 20:17:59 localhost libvirtd[1670]: This is normally a bug in some application using the D-Bus library.
Jan  6 20:17:59 localhost libvirtd[1670]:  D-Bus not built with -rdynamic so unable to print a backtrace
Jan  6 20:17:59 localhost NetworkManager[1609]: <warn>  [1578313079.7278] ifcfg-rh: dbus: com.redhat.ifcfgrh1 bus closed
Jan  6 20:17:59 localhost avahi-daemon[1348]: Disconnected from D-Bus, exiting.
Jan  6 20:17:59 localhost avahi-daemon[1348]: Got SIGTERM, quitting.
Jan  6 20:17:59 localhost avahi-daemon[1348]: Leaving mDNS multicast group on interface virbr0.IPv4 with address 192.168.122.1.
Jan  6 20:17:59 localhost avahi-daemon[1348]: Leaving mDNS multicast group on interface enp3s0.IPv6 with address fe80::5054:ff:fea1:59d.
Jan  6 20:17:59 localhost avahi-daemon[1348]: Leaving mDNS multicast group on interface enp3s0.IPv4 with address 9.82.244.73.
Jan  6 20:17:59 localhost systemd[1]: tuned.service: Main process exited, code=exited, status=1/FAILURE
Jan  6 20:17:59 localhost systemd[1]: tuned.service: Failed with result 'exit-code'.
Jan  6 20:17:59 localhost audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=tuned comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Jan  6 20:17:59 localhost avahi-daemon[1348]: avahi-daemon 0.7 exiting.
**Jan  6 20:17:59 localhost [/bin/bash]: [kill -9 1350] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.3.22.138)]**
Jan  6 20:17:59 localhost audit[1366]: AVC avc:  denied  { write } for  pid=1366 comm="in:imjournal" name="/" dev="dm-0" ino=2 scontext=system_u:system_r:syslogd_t:s0 tcontext=system_u:object_r:root_t:s0 tclass=dir permissive=1
Jan  6 20:17:59 localhost audit[1366]: AVC avc:  denied  { add_name } for  pid=1366 comm="in:imjournal" name="imjournal.state.tmp" scontext=system_u:system_r:syslogd_t:s0 tcontext=system_u:object_r:root_t:s0 tclass=dir permissive=1
Jan  6 20:17:59 localhost audit[1366]: SYSCALL arch=c00000b7 syscall=56 success=yes exit=13 a0=ffffffffffffff9c a1=fffbf8fad708 a2=241 a3=1b6 items=0 ppid=1 pid=1366 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="in:imjournal" exe="/usr/sbin/rsyslogd" subj=system_u:system_r:syslogd_t:s0 key=(null)
Jan  6 20:17:59 localhost audit: PROCTITLE proctitle=2F7573722F7362696E2F727379736C6F6764002D6E002D694E4F4E45
Jan  6 20:17:59 localhost audit[1366]: AVC avc:  denied  { remove_name } for  pid=1366 comm="in:imjournal" name="imjournal.state.tmp" dev="dm-0" ino=17 scontext=system_u:system_r:syslogd_t:s0 tcontext=system_u:object_r:root_t:s0 tclass=dir permissive=1
Jan  6 20:17:59 localhost audit[1366]: SYSCALL arch=c00000b7 syscall=38 success=yes exit=0 a0=ffffffffffffff9c a1=fffbf8fad708 a2=ffffffffffffff9c a3=fffbec000c50 items=0 ppid=1 pid=1366 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="in:imjournal" exe="/usr/sbin/rsyslogd" subj=system_u:system_r:syslogd_t:s0 key=(null)
Jan  6 20:17:59 localhost audit: PROCTITLE proctitle=2F7573722F7362696E2F727379736C6F6764002D6E002D694E4F4E45
Jan  6 20:18:01 localhost [/bin/bash]: [ps aux | grep dbus-daemon] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.3.22.138)]
Jan  6 20:18:05 localhost [/bin/bash]: [date] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.3.22.138)]
Jan  6 20:18:15 localhost [/bin/bash]: [ps aux | grep dbus-daemon] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.3.22.138)]
Jan  6 20:18:26 localhost [/bin/bash]: [ps aux | grep dbus-daemon] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.3.22.138)]
Jan  6 20:18:40 localhost [/bin/bash]: [ps aux | grep dbus-daemon] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.3.22.138)]
Jan  6 20:19:02 localhost [/bin/bash]: [ps aux | grep dbus-daemon] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.3.22.138)]
Jan  6 20:19:05 localhost [/bin/bash]: [date] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.3.22.138)]
Jan  6 20:19:08 localhost [/bin/bash]: [ps aux | grep dbus-daemon] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.3.22.138)]
Jan  6 20:19:11 localhost [/bin/bash]: [date] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.3.22.138)]
Jan  6 20:19:12 localhost chronyd[1356]: Source 199.182.204.197 replaced with 78.46.102.180
Jan  6 20:19:13 localhost [/bin/bash]: [ps aux | grep dbus-daemon] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.3.22.138)]
Jan  6 20:19:17 localhost [/bin/bash]: [ps aux | grep dbus-daemon] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.3.22.138)]
Jan  6 20:19:20 localhost [/bin/bash]: [ps aux | grep dbus-daemon] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.3.22.138)]
Jan  6 20:19:23 localhost [/bin/bash]: [ps aux | grep dbus-daemon] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.3.22.138)]
Jan  6 20:19:25 localhost [/bin/bash]: [ps aux | grep dbus-daemon] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.3.22.138)]
Jan  6 20:19:26 localhost [/bin/bash]: [ps aux | grep dbus-daemon] return code=[0], execute success by [root(uid=0)] from [pts/0 (9.3.22.138)]
Jan  6 20:19:29 localhost systemd[1]: Failed to get initial list of names: Connection timed out
Jan  6 20:19:29 localhost systemd[1]: avahi-daemon.service: Succeeded.
Jan  6 20:19:29 localhost audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=avahi-daemon comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
**Jan  6 20:19:29 localhost systemd[1]: dbus.service: Main process exited, code=killed, status=9/KILL
Jan  6 20:19:29 localhost systemd[1]: dbus.service: Failed with result 'signal'.**
Jan  6 20:19:29 localhost audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=dbus comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Jan  6 20:19:29 localhost systemd[1]: polkit.service: Succeeded.
Jan  6 20:19:29 localhost audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=polkit comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan  6 20:19:29 localhost systemd[1]: firewalld.service: Main process exited, code=exited, status=1/FAILURE
Jan  6 20:19:29 localhost systemd[1]: firewalld.service: Failed with result 'exit-code'.
Jan  6 20:19:29 localhost audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=firewalld comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Jan  6 20:19:29 localhost systemd[1]: tuned.service: Service RestartSec=100ms expired, scheduling restart.
Jan  6 20:19:29 localhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=tuned comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan  6 20:19:29 localhost audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=tuned comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan  6 20:19:29 localhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@0-2600-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jan  6 20:19:29 localhost systemd[1]: tuned.service: Scheduled restart job, restart counter is at 1.
Jan  6 20:19:29 localhost systemd[1]: Created slice system-systemd\x2dcoredump.slice.
Jan  6 20:19:29 localhost systemd[1]: Starting Authorization Manager...
Jan  6 20:19:29 localhost systemd[1]: Stopped Dynamic System Tuning Daemon.
Jan  6 20:19:29 localhost systemd[1]: Started Process Core Dump (PID 2600/UID 0).
**Jan  6 20:19:31 localhost systemd[1]: dbus.service: Service RestartSec=1s expired, scheduling restart.**
Jan  6 20:19:31 localhost audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=NetworkManager-wait-online comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
**Jan  6 20:19:31 localhost systemd[1]: dbus.service: Scheduled restart job, restart counter is at 1.**
Jan  6 20:19:31 localhost systemd[1]: NetworkManager-wait-online.service: Succeeded.
Jan  6 20:19:31 localhost systemd[1]: Stopped Network Manager Wait Online.
Jan  6 20:19:31 localhost systemd[1]: Stopping Network Manager Wait Online...
Jan  6 20:19:31 localhost systemd[1]: Stopping Network Manager...
Jan  6 20:19:31 localhost NetworkManager[1609]: <info>  [1578313171.1146] caught SIGTERM, shutting down normally.
Jan  6 20:19:31 localhost NetworkManager[1609]: <info>  [1578313171.3130] dhcp4 (enp3s0): canceled DHCP transaction, DHCP client pid 1971
Jan  6 20:19:31 localhost NetworkManager[1609]: <info>  [1578313171.3135] dhcp4 (enp3s0): state changed bound -> done

As you can see, I killed dbus-daemon at 20:17:59 and dbus-daemon was finally exited at 20:19:29, always 90s. Everytime the dbus-daemon was zombie, I found this log "systemd[1]: Failed to get initial list of names: Connection timed out"

**Comment by ExtinctFire** [comment] 2020-01-07 14:02
I found the sd_bus_wait will block in ppoll about 90s but I don't know why, then when go to sd_bus_process again, it will fail in bus_socket_process_authenticating with ETIMEDOUT.

**Comment by poettering** [comment] 2020-01-07 14:09
Ah, so, PID 1 tries hard not to do syncrhonous dbus requests, but you managed to hit the only one still left. So here's what happens:

you kill dbus, systemd notices that, tries to resync the list of names, does so syncrhonously, but for that to complete the bus needs to be restarted (the socket is already established, but due to socket activation talking on it will freeze until the dbus service is started). But we cannot start dbus while we block on the synchronous method call for listing the name. After 90s that method call times out, and all is good.

Coincidentally i fixed the syncrhonous method call in #14424, which should remove this freeze.

**Comment by ExtinctFire** [comment] 2020-01-07 14:27
Thank you! I will try your modification soon.

**Comment by ExtinctFire** [comment] 2020-01-14 02:39
After patching, the problem is fixed, you can close the issue when you merge #14424

**Comment by poettering** [comment] 2020-01-15 10:46
#14424 is merged. Closing.

**Closed as completed by poettering** 2020-01-15 10:46 UTC
Labels: pid1
