### ISSUE TITLE
systemd-resolved won't use dns response for cname when multiple is returned

### ISSUE THREAD

**Issue by jaysonsantos** [systemd/systemd#12659] opened 2019-05-24 09:01 UTC
**systemd version the issue has been seen with**
systemd 242 (242.29-1-arch)
+PAM +AUDIT -SELINUX -IMA -APPARMOR +SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid

**Used distribution**
 arch linux

**Expected behaviour you didn't see**
when resolving an internal cname which goes through a resolver (knot-resolver) running on 127.0.0.1 it should have used the whole response from this resolver giving me an internal IP

**Unexpected behaviour you saw**
It seems that systemd-resolved gets the first cname and tries to follow it instead of using the whole response from the DNS server thus making the resolver to ignore the next requests that use a specific prefix and sending the request to a public DNS

**Steps to reproduce the problem**
`host internal-host.customsufix` should be enough to reproduce

/etc/systemd/resolved.conf
```
[Resolve]
DNS=127.0.0.1
FallbackDNS=1.1.1.1
```

journalctl -u systemd-resolved
```
May 24 08:38:09 arch-vm systemd-resolved[3871]: Got DNS stub UDP query packet for id 64737
May 24 08:38:09 arch-vm systemd-resolved[3871]: Looking up RR for internal-host.production IN A.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Cache miss for internal-host.production IN A
May 24 08:38:09 arch-vm systemd-resolved[3871]: Transaction 49119 for <internal-host.production IN A> scope dns on */*.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Using feature level UDP for transaction 49119.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Using DNS server 127.0.0.1 for transaction 49119.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Sending query packet with id 49119.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Cache miss for internal-host.production IN A
May 24 08:38:09 arch-vm systemd-resolved[3871]: Transaction 18674 for <internal-host.production IN A> scope dns on enp0s3/*.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Detected server responses lack RRSIG records, downgrading feature level...
May 24 08:38:09 arch-vm systemd-resolved[3871]: Using degraded feature set (UDP+EDNS0) for DNS server 192.168.20.1.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Using feature level UDP+EDNS0 for transaction 18674.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Using DNS server 192.168.20.1 for transaction 18674.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Sending query packet with id 18674.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Processing query...
May 24 08:38:09 arch-vm systemd-resolved[3871]: Processing incoming packet on transaction 49119 (rcode=SUCCESS).
May 24 08:38:09 arch-vm systemd-resolved[3871]: Verified we get a response at feature level UDP from DNS server 127.0.0.1.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Not validating response for 49119, used server feature level does not support DNSSEC.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Server 127.0.0.1 does not support DNSSEC, downgrading to non-DNSSEC mode.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Transaction 49119 for <internal-host.production IN A> on scope dns on */* now complete with <success> from network (unsigned).
May 24 08:38:09 arch-vm systemd-resolved[3871]: Freeing transaction 18674.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Following CNAME/DNAME internal-host.production → rds.public.eu-central-1.rds.amazonaws.com.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Cache miss for rds.public.eu-central-1.rds.amazonaws.com IN A
May 24 08:38:09 arch-vm systemd-resolved[3871]: Transaction 37154 for <rds.public.eu-central-1.rds.amazonaws.com IN A> scope dns on */*.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Using feature level UDP for transaction 37154.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Using DNS server 127.0.0.1 for transaction 37154.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Sending query packet with id 37154.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Cache miss for rds.public.eu-central-1.rds.amazonaws.com IN A
May 24 08:38:09 arch-vm systemd-resolved[3871]: Transaction 8503 for <rds.public.eu-central-1.rds.amazonaws.com IN A> scope dns on enp0s3/*.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Using feature level UDP+EDNS0 for transaction 8503.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Using DNS server 192.168.20.1 for transaction 8503.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Sending query packet with id 8503.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Freeing transaction 49119.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Processing incoming packet on transaction 8503 (rcode=SUCCESS).
May 24 08:38:09 arch-vm systemd-resolved[3871]: Not validating response for 8503, used server feature level does not support DNSSEC.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Server 192.168.20.1 does not support DNSSEC, downgrading to non-DNSSEC mode.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Added positive unauthenticated cache entry for rds.public.eu-central-1.rds.amazonaws.com IN CNAME 5s on enp0s3/INET/192.168.20.1
May 24 08:38:09 arch-vm systemd-resolved[3871]: Added positive unauthenticated cache entry for ec2-public-cname.eu-central-1.compute.amazonaws.com IN A 7200s on enp0s3/INET/192.168.20.1
May 24 08:38:09 arch-vm systemd-resolved[3871]: Transaction 8503 for <rds.public.eu-central-1.rds.amazonaws.com IN A> on scope dns on enp0s3/* now complete with <success> from network (unsigned).
May 24 08:38:09 arch-vm systemd-resolved[3871]: Freeing transaction 37154.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Following CNAME/DNAME rds.public.eu-central-1.rds.amazonaws.com → ec2-public-cname.eu-central-1.compute.amazonaws.com.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Cache miss for ec2-public-cname.eu-central-1.compute.amazonaws.com IN A
May 24 08:38:09 arch-vm systemd-resolved[3871]: Transaction 52448 for <ec2-public-cname.eu-central-1.compute.amazonaws.com IN A> scope dns on */*.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Using feature level UDP for transaction 52448.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Using DNS server 127.0.0.1 for transaction 52448.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Sending query packet with id 52448.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Positive cache hit for ec2-public-cname.eu-central-1.compute.amazonaws.com IN A
May 24 08:38:09 arch-vm systemd-resolved[3871]: Transaction 21582 for <ec2-public-cname.eu-central-1.compute.amazonaws.com IN A> on scope dns on enp0s3/* now complete with <success> from cache (unsigned).
May 24 08:38:09 arch-vm systemd-resolved[3871]: Freeing transaction 52448.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Freeing transaction 21582.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Sending response packet with id 64737 on interface 1/AF_INET.
May 24 08:38:09 arch-vm systemd-resolved[3871]: Freeing transaction 8503.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Got DNS stub UDP query packet for id 9317
May 24 08:41:14 arch-vm systemd-resolved[3871]: Looking up RR for internal-host.production IN A.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Cache miss for internal-host.production IN A
May 24 08:41:14 arch-vm systemd-resolved[3871]: Transaction 48235 for <internal-host.production IN A> scope dns on */*.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Using feature level UDP for transaction 48235.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Using DNS server 127.0.0.1 for transaction 48235.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Sending query packet with id 48235.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Removing cache entry for rds.public.eu-central-1.rds.amazonaws.com IN CNAME (expired 180s ago)
May 24 08:41:14 arch-vm systemd-resolved[3871]: Cache miss for internal-host.production IN A
May 24 08:41:14 arch-vm systemd-resolved[3871]: Transaction 1883 for <internal-host.production IN A> scope dns on enp0s3/*.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Using feature level UDP+EDNS0 for transaction 1883.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Using DNS server 192.168.20.1 for transaction 1883.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Sending query packet with id 1883.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Processing query...
May 24 08:41:14 arch-vm systemd-resolved[3871]: Processing incoming packet on transaction 48235 (rcode=SUCCESS).
May 24 08:41:14 arch-vm systemd-resolved[3871]: Not validating response for 48235, used server feature level does not support DNSSEC.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Transaction 48235 for <internal-host.production IN A> on scope dns on */* now complete with <success> from network (unsigned).
May 24 08:41:14 arch-vm systemd-resolved[3871]: Freeing transaction 1883.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Following CNAME/DNAME internal-host.production → rds.public.eu-central-1.rds.amazonaws.com.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Cache miss for rds.public.eu-central-1.rds.amazonaws.com IN A
May 24 08:41:14 arch-vm systemd-resolved[3871]: Transaction 6996 for <rds.public.eu-central-1.rds.amazonaws.com IN A> scope dns on */*.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Using feature level UDP for transaction 6996.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Using DNS server 127.0.0.1 for transaction 6996.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Sending query packet with id 6996.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Cache miss for rds.public.eu-central-1.rds.amazonaws.com IN A
May 24 08:41:14 arch-vm systemd-resolved[3871]: Transaction 58240 for <rds.public.eu-central-1.rds.amazonaws.com IN A> scope dns on enp0s3/*.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Using feature level UDP+EDNS0 for transaction 58240.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Using DNS server 192.168.20.1 for transaction 58240.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Sending query packet with id 58240.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Freeing transaction 48235.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Processing incoming packet on transaction 58240 (rcode=SUCCESS).
May 24 08:41:14 arch-vm systemd-resolved[3871]: Not validating response for 58240, used server feature level does not support DNSSEC.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Added positive unauthenticated cache entry for rds.public.eu-central-1.rds.amazonaws.com IN CNAME 5s on enp0s3/INET/192.168.20.1
May 24 08:41:14 arch-vm systemd-resolved[3871]: Added positive unauthenticated cache entry for ec2-public-cname.eu-central-1.compute.amazonaws.com IN A 7200s on enp0s3/INET/192.168.20.1
May 24 08:41:14 arch-vm systemd-resolved[3871]: Transaction 58240 for <rds.public.eu-central-1.rds.amazonaws.com IN A> on scope dns on enp0s3/* now complete with <success> from network (unsigned).
May 24 08:41:14 arch-vm systemd-resolved[3871]: Freeing transaction 6996.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Following CNAME/DNAME rds.public.eu-central-1.rds.amazonaws.com → ec2-public-cname.eu-central-1.compute.amazonaws.com.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Cache miss for ec2-public-cname.eu-central-1.compute.amazonaws.com IN A
May 24 08:41:14 arch-vm systemd-resolved[3871]: Transaction 8424 for <ec2-public-cname.eu-central-1.compute.amazonaws.com IN A> scope dns on */*.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Using feature level UDP for transaction 8424.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Using DNS server 127.0.0.1 for transaction 8424.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Sending query packet with id 8424.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Positive cache hit for ec2-public-cname.eu-central-1.compute.amazonaws.com IN A
May 24 08:41:14 arch-vm systemd-resolved[3871]: Transaction 2024 for <ec2-public-cname.eu-central-1.compute.amazonaws.com IN A> on scope dns on enp0s3/* now complete with <success> from cache (unsigned).
May 24 08:41:14 arch-vm systemd-resolved[3871]: Freeing transaction 8424.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Freeing transaction 2024.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Sending response packet with id 9317 on interface 1/AF_INET.
May 24 08:41:14 arch-vm systemd-resolved[3871]: Freeing transaction 58240.
```

captured packets that shows that the DNS server actually sent back the whole response
```
    1 0.000000000     10.8.0.6 → 10.8.0.1     DNS 80 Standard query 0x0e61 A internal-host.pROdUCtIon OPT
    2 0.031175980     10.8.0.6 → 10.8.0.1     DNS 80 Standard query 0x0e61 A internal-host.pROdUCtIon OPT
    3 0.045952540     10.8.0.1 → 10.8.0.6     DNS 221 Standard query response 0x0e61 A internal-host.pROdUCtIon CNAME rds.public.eu-central-1.rds.amazonaws.com CNAME ec2-public-cname.eu-central-1.compute.amazonaws.com A 10.0.1.99 OPT
3 packets captured
```

the problem here is that if you resolve a RDS ip from the internet you only get the external IP but i have used knot-resolver to use internal domains to be able to resolve the DNS inside a VPN in order to connect through it using the itnernal IP.

Let me know if any further information is required.

**Comment by poettering** [comment] 2019-06-18 11:52
hmm, not sure i follow? your complaint is that we don't use the additional answer RRs but instead look up the CNAME ourselves again? but how is that a problem? i mean, using that data is surely an optimization, but beyond that?

**Comment by jaysonsantos** [comment] 2019-06-18 12:24
Hi there, In this case when the suffix is used it routes the requests and its chain through an internal DNS server but if systemd goes step by step only the first CNAME goes to the internal DNS server and the remaining will go to the public because they don't match the expected suffix.

To make that work I am using knot resolver to route the queries based on the name with this configuration:
```lua
net = { '127.0.0.1' }

-- VPN specific DNS
local custom_servers = {
        ['10.8.0.1'] = {
                'production.',
        },
        ['10.10.0.1'] = {
                'test.',
        },
    }
for server, domains in pairs(custom_servers) do
    for _, domain in pairs(domains) do
        log('Resolving %s with %s', domain, server)
        policy.add(policy.suffix(policy.STUB(server), {todname(domain)}))
    end
end

-- Fallback to Cloudflare TLS
policy.add(
    policy.all(
        policy.TLS_FORWARD({
            {'1.1.1.1', hostname='1.1.1.1'}
        })
    )
)
```
That config makes sure that every time I try to query for `name.production` it goes through the VPN thus returning an internal IP because the same CNAME on public DNS servers return a public IP but if queried within AWS, it should return its internal IP.
I hope it clarifies the problem.
Thank you for the answer

**Comment by poettering** [comment] 2019-06-18 13:30
So let me get this straight: you have a split horizon setup, where the all queries ending with a specific suffix shall be routed to a DNS server X, while all others shall be routed to a DNS server Y, but as a special addition any host referenced by a CNAME response of X even though it might lie in Y territory should be resolved via X?

How can that possibly work? I mean, resolved caches heavily (it's half what it is about after all). Depending on whether a specific host was first looked up via X through a CNAME or via Y directly a different set of RRs would be in the cache, for the same name + rrtype...

Or am I misunderstanding what you are trying to do?

Note that e actually do try to use the additional response data in a CNAME reply already:

https://github.com/systemd/systemd/blob/master/src/resolve/resolved-dns-query.c#L1020

there might be something wrong there. I figure somebody who can reproduce the issue needs to gdb through that and see why the CNAME reply is not used.

That said I am not sure I grok the probem you have or the usecase...

**Comment by poettering** [comment] 2020-11-18 14:57
Closing, due to lack of reponse.

**Closed as completed by poettering** 2020-11-18 14:57 UTC
Labels: resolve, needs-reporter-feedback ❓

**Comment by quakemmo** [comment] 2023-06-21 11:03
This is still an issue.

On a AWS EC2 Debian instance, when using systemd-resolved, the lookup for an RDS hostname will randomly fail about once every 10 times. This only happens when performing the lookup from inside the instance (multiple DNS entries returned). Never happens when looking up from outside the AWS network (only one DNS entry is returned).

The issue disappears when not using systemd-resolved.

It's a huge PITA and requires juggling things around in order to disable systemd-resolved.
