### ISSUE TITLE
Build fails on sparc64 due to invalid assembler

### ISSUE THREAD

**Issue by glaubitz** [systemd/systemd#9444] opened 2018-06-27 12:30 UTC
The build currently fails on sparc64 due to issues with the inline assembly in raw_clone.h:

```
glaubitz@stadler:/srv/glaubitz/systemd/build$ ninja
[330/1563] Compiling C object 'src/basic/src@basic@@basic@sta/process-util.c.o'.
FAILED: src/basic/src@basic@@basic@sta/process-util.c.o 
cc -Isrc/basic/src@basic@@basic@sta -Isrc/basic -I../src/basic -Isrc/shared -I../src/shared -Isrc/systemd -I../src/systemd -Isrc/journal -I../src/journal -Isrc/journal-remote -I../src/journal-remote -Isrc/nspawn -I../src/nspawn -Isrc/resolve -I../src/resolve -Isrc/timesync -I../src/timesync -I../src/time-wait-sync -Isrc/login -I../src/login -Isrc/udev -I../src/udev -Isrc/libudev -I../src/libudev -Isrc/core -I../src/core -I../src/libsystemd/sd-bus -I../src/libsystemd/sd-device -I../src/libsystemd/sd-hwdb -I../src/libsystemd/sd-id128 -I../src/libsystemd/sd-netlink -I../src/libsystemd/sd-network -Isrc/libsystemd-network -I../src/libsystemd-network -I. -I../ -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/libmount -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=gnu99 -O0 -g -Wextra -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -fPIE -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Wno-error=nonnull -Werror=shadow -include config.h -fPIC -pthread -fvisibility=default  -MD -MQ 'src/basic/src@basic@@basic@sta/process-util.c.o' -MF 'src/basic/src@basic@@basic@sta/process-util.c.o.d' -o 'src/basic/src@basic@@basic@sta/process-util.c.o' -c ../src/basic/process-util.c
In file included from ../src/basic/process-util.c:37:0:
../src/basic/raw-clone.h: In function ‘raw_clone’:
../src/basic/raw-clone.h:50:17: error: unknown register name ‘%g1cc’ in ‘asm’
                 asm volatile("mov %3, %%g1\n\t"
                 ^~~
[363/1563] Compiling C object 'src/journal/src@journal@@journal-client@sta/journal-file.c.o'.
ninja: build stopped: subcommand failed.
glaubitz@stadler:/srv/glaubitz/systemd/build$
```

systemd 238 did not show the problem. I have no bi-sected the problem yet.

CC @jrtc27 @karcherm @trofi @floppym

**Comment by glaubitz** [comment] 2018-06-27 12:42
This was most likely broken by:

```
commit 96f64eb5741b157f26a9089816fdd992e959792e
Author: Mike Gilbert <floppym@gentoo.org>
Date:   Wed May 30 23:06:33 2018 -0400

    basic: set errno in raw_clone() on sparc
    
    sparc sets the carry bit when a syscall fails. Use this information to
    set errno and return -1 as appropriate.
    
    The added test case calls raw_clone() with flags known to be invalid
    according to the clone(2) manpage.
```

@floppym You obviously didn't test your changes :(.

**Comment by floppym** [comment] 2018-06-27 13:56
The changes were definitely tested on a sparc32 userspace. Apologies if it somehow broke on sparc64, but I don't see how it would have.

**Comment by glaubitz** [comment] 2018-06-27 14:05
> Apologies if it somehow broke on sparc64, but I don't see how it would have.

Well, sparc64 has a different ABI so it definitely needs separate testing.

The issue is 100% reproducible, also shows on the buildds: https://buildd.debian.org/status/fetch.php?pkg=systemd&arch=sparc64&ver=239-1&stamp=1529712068&raw=0

**Comment by floppym** [comment] 2018-06-27 14:11
Alright. I'll see if I can reproduce it in QEMU, unless you can provide a fix.

**Comment by glaubitz** [comment] 2018-06-27 14:14
Why not create a 64-bit chroot on your Gentoo system? You're running a 64-bit kernel anyway, aren't you?

```
debootstrap --no-check-gpg --arch=sparc64 --variant=buildd unstable sid-sparc64 http://ftp.ports.debian.org/debian-ports
```

and you have a sparc64 chroot.

**Comment by glaubitz** [comment] 2018-06-27 14:21
According to comments on the #gentoo-sparc IRC channel, the issue shows on sparc32 as well.

**Comment by floppym** [comment] 2018-06-27 14:39
It looks like this broke due to a last minute change I made before the PR was merged; just a typo. I'll submit a PR momentarily.

**Closed as completed** 2018-06-27 16:16 UTC
