### ISSUE TITLE
Bind mounts can create duplicated/mirrored (sub) mount units that confuses PID1

### ISSUE THREAD

**Issue by fbuihuu** [systemd/systemd#10133] opened 2018-09-20 14:57 UTC
If one directory A is bind-mounted onto another one B, then all mounts done under A will be seen by PID1 as different mounts under B.

This can be easily reproduced with:

```
$ mkdir /mnt/{a,b}
$ mkdir /mnt/a/d1
$ mount -o bind /mnt/a /mnt/b
$ mount -t tmpfs none /mnt/a/d1
$ grep /mnt /proc/self/mountinfo 
310 65 254:1 /mnt/a /mnt/b rw,relatime shared:1 - ext4 /dev/vda1 rw
318 65 0:46 / /mnt/a/d1 rw,relatime shared:165 - tmpfs none rw
319 310 0:46 / /mnt/b/d1 rw,relatime shared:165 - tmpfs none rw
$
$ systemctl -t mount list-units   | grep mnt
mnt-a-d1.mount         loaded active mounted /mnt/a/d1                      
mnt-b-d1.mount         loaded active mounted /mnt/b/d1                      
mnt-b.mount            loaded active mounted /mnt/b
```

Since mnt-a-d1.mount mnt-b-d1.mount are seen as 2 different mountpoints, both are likely to be stopped at the same time during shutdown. This will lead inevitably to a failure since the second stopped mount unit will try to unmount the directory which was already unmounted by the first-stopped mount unit:

```
$ systemctl stop mnt-a-d1.mount mnt-b-d1.mount
$ journalctl -b | tail
Sep 20 16:33:25 linux-rpi3 systemd[1]: Unmounting /mnt/a/d1...
Sep 20 16:33:25 linux-rpi3 systemd[1]: Unmounting /mnt/b/d1...
Sep 20 16:33:25 linux-rpi3 umount[1644]: umount: /mnt/b/d1: not mounted.
Sep 20 16:33:25 linux-rpi3 systemd[1]: Unmounted /mnt/a/d1.
Sep 20 16:33:25 linux-rpi3 systemd[1]: mnt-b-d1.mount: Mount process exited, code=exited status=32
Sep 20 16:33:25 linux-rpi3 systemd[1]: mnt-b-d1.mount: Failed with result 'exit-code'.
Sep 20 16:33:25 linux-rpi3 systemd[1]: Unmounted /mnt/b/d1.
```

**Comment by poettering** [comment] 2021-02-09 22:15
Duplicate of #3415

**Closed as completed by poettering** 2021-02-09 22:15 UTC
Labels: bug 🐛, pid1, duplicate
