### ISSUE TITLE
ESP Automount fails since systemd 224

### ISSUE THREAD

**Issue by encbladexp** [systemd/systemd#1167] opened 2015-09-06 05:07 UTC
Since at least systemd 224 my /boot will no longer be mounted by systemd without using an fstab entry. What gdisk knows about my ESP:

```
Partition number (1-3): 1
Partition GUID code: C12A7328-F81F-11D2-BA4B-00A0C93EC93B (EFI System)
Partition unique GUID: A2B94332-DED2-441F-82FF-9D71D083211E
First sector: 2048 (at 1024.0 KiB)
Last sector: 206847 (at 101.0 MiB)
Partition size: 204800 sectors (100.0 MiB)
Attribute flags: 8000000000000000
Partition name: 'EFI system partition'
```

I am using systemd-boot 225 as Bootloader. What further Informations are required to resolve this issue?

**Comment by mus65** [comment] 2015-09-06 09:34
See my comments in #920. This was only partly fixed in 225 and is still broken if the root device is encrypted.

**Comment by poettering** [comment] 2015-09-06 10:40
This should be fixed in v225. Closing as duplicate of #920.

**Closed as completed by poettering** 2015-09-06 10:40 UTC
Labels: gpt-auto

**Comment by encbladexp** [comment] 2015-09-06 11:13
My root device is encrypted too, 225 (i use arch linux) has the same issue. I have this issue on three different systems:
- Desktop with encrypted root inside a LVM, ESP on an different disk
- Homeserver without encrypt, the ESP on an USB Stick and LVM inside a Linux Software RAID
- Notebook with encrypted root inside a LVM, ESP on the same disk

On _all_ systems this worked fine, but for now it is broken since a least 224.

**Comment by poettering** [comment] 2015-09-06 22:15
If you have an encrypted root, then #1178 should help. However, not if LVM is also in the mix. If you use LVM all the automatisms are off really, sorry for that, but we do not support any kind of auto-discovery on LVM.

**Comment by encbladexp** [comment] 2015-09-07 17:43
Is there any reason not just using this EFI var:

```
[root:~] 1 # efivar -p -n 4a67b082-0a4c-41cf-b6c7-440b29bb8c4f-LoaderDevicePartUUID
GUID: 4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
Name: "LoaderDevicePartUUID"
Attributes:
        Boot Service Access
        Runtime Service Access
Value:
00000000  41 00 32 00 42 00 39 00  34 00 33 00 33 00 32 00  |A.2.B.9.4.3.3.2.|
00000010  2d 00 44 00 45 00 44 00  32 00 2d 00 34 00 34 00  |-.D.E.D.2.-.4.4.|
00000020  31 00 46 00 2d 00 38 00  32 00 46 00 46 00 2d 00  |1.F.-.8.2.F.F.-.|
00000030  39 00 44 00 37 00 31 00  44 00 30 00 38 00 33 00  |9.D.7.1.D.0.8.3.|
00000040  32 00 31 00 31 00 45 00  00 00                    |2.1.1.E...      |
```

```
[root:~] # bootctl
System:
     Firmware: UEFI 2.31 (American Megatrends 4.653)
  Secure Boot: disabled
   Setup Mode: setup

Loader:
      Product: systemd-boot 225
    Partition: /dev/disk/by-partuuid/a2b94332-ded2-441f-82ff-9d71d083211e
         File: └─/EFI/SYSTEMD/SYSTEMD-BOOTX64.EFI

Boot Loader Binaries:
          ESP: /dev/disk/by-partuuid/a2b94332-ded2-441f-82ff-9d71d083211e
         File: └─/EFI/systemd/systemd-bootx64.efi (systemd-boot 225)
         File: └─/EFI/Boot/BOOTX64.EFI (systemd-boot 225)

Boot Loader Entries in EFI Variables:
        Title: Linux Boot Manager
           ID: 0x0001
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/a2b94332-ded2-441f-82ff-9d71d083211e
         File: └─/EFI/SYSTEMD/SYSTEMD-BOOTX64.EFI

        Title: Windows Boot Manager
           ID: 0x0000
       Status: active, boot-order
    Partition: /dev/disk/by-partuuid/a2b94332-ded2-441f-82ff-9d71d083211e
         File: └─/EFI/MICROSOFT/BOOT/BOOTMGFW.EFI
```

We know where the ESP is, but we dont use this information for mounting it to /boot? It worked before v224, and i still don't understand why it is broken now :(
