### ISSUE TITLE
Access to automounted dir should not hang when dependent .device start times out

### ISSUE THREAD

**Issue by spaceboy-cz** [systemd/systemd#3000] opened 2016-04-09 22:29 UTC
### Submission type
- [x] Bug report
### systemd version the issue has been seen with

> 229
### Used distribution

> Debian (Raspbian) 8.0
### In case of bug report: Expected behaviour you didn't see

> Access to automounted dir should fail with error when dependent .device start times out
### In case of bug report: Unexpected behaviour you saw

> access hangs indefinitely (or until `daemon-reload`)
### In case of bug report: Steps to reproduce the problem

> 1. Setup automount of LVM volume using fstab options
>    `defaults,noauto,nofail,x-systemd.automount,x-systemd.idle-timeout=300,x-systemd.device-timeout=30`
> 2. unmount the volume
> 3. do `vgchange -an`
> 4. try to access the automount.

IMHO the dependency failure on the .mount job doesn't seem to propagated back to the .automount.
Issue #2873 might be related.

[dmesg.txt](https://github.com/systemd/systemd/files/211499/dmesg.txt)

**Comment by poettering** [comment] 2016-04-18 16:44
Duplicate of #2181. Closing this one.

**Closed as completed by poettering** 2016-04-18 16:44 UTC
Labels: bug 🐛, pid1
