### ISSUE TITLE
 [systemd-networkd] RequiredFamilyForOnline does not appear to be working

### ISSUE THREAD

**Issue by daiaji** [systemd/systemd#22246] opened 2022-01-25 18:34 UTC
**systemd version the issue has been seen with**
 > systemd 250 (250.3-1-manjaro)

**Used distribution**
 > Manjaro

**Linux kernel version used** (`uname -a`)
 > Linux AIO 5.15.16-1-ACS-MANJARO #1 SMP PREEMPT Mon Jan 24 23:05:33 CST 2022 x86_64 GNU/Linux

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > The RequiredFamilyForOnline parameter works

**Unexpected behaviour you saw**
 > RequiredFamilyForOnline does not seem to work.

**Steps to reproduce the problem**
```
cat /etc/systemd/network/10-sr-iov.link
[Match]
OriginalName=enp7s0f2

[SR-IOV]
VirtualFunction=2
```
```
cat /etc/systemd/network/br0_bind.network
[Match]
Name=enp*s0

[Link]
MTUBytes=9000

[Network]
Bridge=br0
```
```
cat /etc/systemd/network/br0.netdev
[NetDev]
Name=br0
Kind=bridge
```
```
cat /etc/systemd/network/br0.network
[Match]
Name=br0

[Network]
DHCP=yes
MulticastDNS=true
IPv6Token=prefixstable
IPv6PrivacyExtensions=prefer-public

[Link]
RequiredForOnline=yes
RequiredFamilyForOnline=ipv4
```
```
cat /usr/lib/systemd/system/test.service 
[Unit]
Description=nettest
Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/bin/sh -c 'networkctl status br0 > /var/log/test.log'
KillMode=process

[Install]
WantedBy=multi-user.target
```
```
cat /var/log/test.log                   
● 3: br0                        
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: /etc/systemd/network/br0.network
                          Type: bridge
                         State: routable (configured)
                  Online state: offline
                        Driver: bridge
              Hardware Address: 12:53:9f:19:83:29
                           MTU: 9000 (min: 68, max: 65535)
                         QDisc: noqueue
  IPv6 Address Generation Mode: eui64
                 Forward Delay: 14.990s
                    Hello Time: 1.990s
                       Max Age: 19.990s
                   Ageing Time: 4min 59.990s
                      Priority: 32768
                           STP: no
        Multicast IGMP Version: 2
                          Cost: 1999
                    Port State: disabled
          Queue Length (Tx/Rx): 1/1
              Auto negotiation: no
                         Speed: 2Gbps
                       Address: fd3c:731a:706b::5c4
                                fd3c:731a:706b:0:3501:5ede:8f26:4c08
                                fd3c:731a:706b:0:bbe6:9919:c88a:287b
                                fe80::1053:9fff:fe19:8329
                           DNS: fd3c:731a:706b::1
             Activation Policy: up
           Required For Online: yes
             DHCP6 Client IAID: 0xe2890d07
             DHCP6 Client DUID: DUID-EN/Vendor:0000ab111b3f9218eb97b87a0000

1月 26 02:25:14 AIO systemd-networkd[424]: br0: netdev ready
1月 26 02:25:14 AIO systemd-networkd[424]: br0: Link UP
1月 26 02:25:15 AIO systemd-networkd[424]: br0: Gained carrier
1月 26 02:25:16 AIO systemd-networkd[424]: br0: Lost carrier
1月 26 02:25:17 AIO systemd-networkd[424]: br0: DHCPv6 lease lost
1月 26 02:25:17 AIO systemd-networkd[424]: br0: Gained IPv6LL
1月 26 02:25:19 AIO systemd-networkd[424]: br0: Gained carrier
1月 26 02:25:45 AIO systemd-networkd[424]: br0: DHCPv6 address fd3c:731a:706b::5c4/128 (valid for 11h 59min 59s, preferred for 11h 59min 59s)
1月 26 02:25:45 AIO systemd-networkd[424]: br0: DHCP: received delegated prefix fd3c:731a:706b:4::/62
```

**Additional program output to the terminal or log subsystem illustrating the issue**

https://gist.github.com/daiaji/faaddfb7bba63a4bc2ed17a3c4d1f7ee

**Comment by yuwata** [comment] 2022-01-25 19:06
Thanks.

- Please disable NetworkManager. The provided log suggests that NetworkManager is running on the system. It sometimes causes conflicts with systemd-networkd.service.
- Please try to edit systemd-networkd-wait-online.service with the following: by calling `systemctl edit systemd-networkd-wait-online.service`
```
[Service]
ExecStart=
ExecStart=/usr/lib/systemd/systemd-networkd-wait-online -i br0
```

**Comment by daiaji** [comment] 2022-01-26 04:38
NetworkManager should have been disabled.
```
sudo systemctl list-unit-files | grep NetworkManager
NetworkManager-dispatcher.service          disabled        disabled
NetworkManager-wait-online.service         disabled        disabled
NetworkManager.service                     disabled        disable

```
```

cat /usr/lib/systemd/system/systemd-networkd-wait-online.service
#  SPDX-License-Identifier: LGPL-2.1-or-later
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Wait for Network to be Configured
Documentation=man:systemd-networkd-wait-online.service(8)
DefaultDependencies=no
Conflicts=shutdown.target
Requires=systemd-networkd.service
After=systemd-networkd.service
Before=network-online.target shutdown.target

[Service]
Type=oneshot
ExecStart=/usr/lib/systemd/systemd-networkd-wait-online
RemainAfterExit=yes
Environment=SYSTEMD_LOG_LEVEL=debug

[Install]
WantedBy=network-online.target
```
https://gist.github.com/daiaji/d116ef3ba0ead77ee5aac93bc53d7adb

**Comment by yuwata** [comment] 2022-01-26 05:17
Hm, it seems the result may be expected. From the man page systemd-networkd-wait-online.service(8),
> By default, it will wait for all links it is aware of and which are managed by systemd-networkd.service(8) to be fully configured or failed, and for at least one link to be online. Here, online means that the link's operational state is equal or higher than "degraded".

And from the log, it seems enp6s0 may be already configured and its operational state is equal or higher than 'degraded'. Because, in the last iteration, there is no line about enp6s0:
```
1月 26 12:36:52 AIO systemd-networkd-wait-online[618]: enp7s0f2v1: Operational state 'off' is not in range ['degraded':'routable']
1月 26 12:36:52 AIO systemd-networkd-wait-online[618]: enp7s0f2v0: Operational state 'off' is not in range ['degraded':'routable']
1月 26 12:36:52 AIO systemd-networkd-wait-online[618]: virbr0: Operational state 'no-carrier' is not in range ['degraded':'routable']
1月 26 12:36:52 AIO systemd-networkd-wait-online[618]: wlp5s0: Operational state 'off' is not in range ['degraded':'routable']
1月 26 12:36:52 AIO systemd-networkd-wait-online[618]: enp7s0f2v2: Operational state 'off' is not in range ['degraded':'routable']
1月 26 12:36:52 AIO systemd-networkd-wait-online[618]: enp7s0f3: Operational state 'off' is not in range ['degraded':'routable']
1月 26 12:36:52 AIO systemd-networkd-wait-online[618]: enp7s0f2: Operational state 'off' is not in range ['degraded':'routable']
1月 26 12:36:52 AIO systemd-networkd-wait-online[618]: lo: link is ignored
1月 26 12:36:52 AIO systemd-networkd-wait-online[618]: br0: No routable or link-local IPv4 address is configured.
1月 26 12:36:52 AIO systemd[1]: Finished Wait for Network to be Configured.
```
that suggests enp6s0 is already configured.

If you need that br0 is configured and it has IPv4 address, then please try to use `-i br0` option for systemd-networkd-wait-online.service.

**Comment by daiaji** [comment] 2022-01-26 06:00
```
cat /usr/lib/systemd/system/systemd-networkd-wait-online.service
#  SPDX-License-Identifier: LGPL-2.1-or-later
#
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.

[Unit]
Description=Wait for Network to be Configured
Documentation=man:systemd-networkd-wait-online.service(8)
DefaultDependencies=no
Conflicts=shutdown.target
Requires=systemd-networkd.service
After=systemd-networkd.service
Before=network-online.target shutdown.target

[Service]
Type=oneshot
ExecStart=/usr/lib/systemd/systemd-networkd-wait-online -i br0
RemainAfterExit=yes
Environment=SYSTEMD_LOG_LEVEL=debug

[Install]
WantedBy=network-online.target
```
```
cat /var/log/test.log                                           
● 4: br0                        
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: /etc/systemd/network/br0.network
                          Type: bridge
                         State: routable (configured)
                  Online state: online
                        Driver: bridge
              Hardware Address: 12:53:9f:19:83:29
                           MTU: 9000 (min: 68, max: 65535)
                         QDisc: noqueue
  IPv6 Address Generation Mode: eui64
                 Forward Delay: 14.990s
                    Hello Time: 1.990s
                       Max Age: 19.990s
                   Ageing Time: 4min 59.990s
                      Priority: 32768
                           STP: no
        Multicast IGMP Version: 2
                          Cost: 1999
                    Port State: disabled
          Queue Length (Tx/Rx): 1/1
              Auto negotiation: no
                         Speed: 2Gbps
                       Address: 10.10.10.10 (DHCP4 via 10.10.10.1)
                                fd3c:731a:706b::5c4
                                fd3c:731a:706b:0:3501:5ede:8f26:4c08
                                fd3c:731a:706b:0:c03d:c7fd:8e19:e412
                                fe80::1053:9fff:fe19:8329
                       Gateway: 10.10.10.1
                           DNS: 10.10.10.1
                                fd3c:731a:706b::1
                                fe80::767d:24ff:febd:fe20
             Activation Policy: up
           Required For Online: yes
               DHCP4 Client ID: IAID:0xe2890d07/DUID
             DHCP6 Client IAID: 0xe2890d07
             DHCP6 Client DUID: DUID-EN/Vendor:0000ab111b3f9218eb97b87a0000

1月 26 13:55:10 AIO systemd-networkd-wait-online[618]: br0: link is being processed by networkd
1月 26 13:55:10 AIO systemd-networkd-wait-online[618]: br0: link is being processed by networkd
1月 26 13:55:19 AIO systemd-networkd-wait-online[618]: br0: link is being processed by networkd
1月 26 13:55:23 AIO systemd-networkd-wait-online[618]: br0: link is being processed by networkd
1月 26 13:55:23 AIO systemd-networkd-wait-online[618]: br0: link is being processed by networkd
1月 26 13:55:23 AIO systemd-networkd[424]: br0: DHCPv6 address fd3c:731a:706b::5c4/128 (valid for 11h 59min 59s, preferred for 11h 59min 59s)
1月 26 13:55:23 AIO systemd-networkd[424]: br0: DHCP: received delegated prefix fd3c:731a:706b:4::/62
1月 26 13:55:25 AIO systemd-networkd-wait-online[618]: br0: link is being processed by networkd
1月 26 13:55:25 AIO systemd-networkd-wait-online[618]: br0: No routable or link-local IPv4 address is configured.
1月 26 13:55:26 AIO systemd-networkd[424]: br0: DHCPv4 address 10.10.10.10/24, gateway 10.10.10.1 acquired from 10.10.10.1
```
seems to be available.
But I configured `RequiredForOnline=no` for all network files except br0, why still can't work.
Can I only configure -i br0 for systemd-networkd-wait-online?

**Comment by yuwata** [comment] 2022-01-26 06:19
> But I configured `RequiredForOnline=no` for all network files except br0, why still can't work.

Doesn't it? I cannot reproduce it.
Could you show provide the result of `networkctl -n 0 status '*'`?

**Comment by daiaji** [comment] 2022-01-26 06:42
```
● 1: lo                         
                     Link File: n/a
                  Network File: n/a
                          Type: loopback
                         State: carrier (unmanaged)
                  Online state: unknown
              Hardware Address: 00:00:00:00:00:00
                           MTU: 65536
                         QDisc: noqueue
  IPv6 Address Generation Mode: eui64
          Queue Length (Tx/Rx): 1/1
                       Address: 127.0.0.1
                                ::1
             Activation Policy: up
           Required For Online: yes

● 2: enp6s0                     
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: /etc/systemd/network/br0_bind.network
                          Type: ether
                         State: enslaved (configured)
                  Online state: unknown
                          Path: pci-0000:06:00.0
                        Driver: r8169
                        Vendor: Realtek Semiconductor Co., Ltd.
                         Model: RTL8125 2.5GbE Controller
              Hardware Address: 12:53:9f:19:83:29
    Permanent Hardware Address: 04:42:1a:a9:5f:81 (ASUSTek COMPUTER INC.)
                           MTU: 9000 (min: 68, max: 9194)
                         QDisc: fq_codel
                        Master: br0
  IPv6 Address Generation Mode: none
          Queue Length (Tx/Rx): 1/1
              Auto negotiation: yes
                         Speed: 2Gbps
                        Duplex: full
                          Port: tp
             Activation Policy: up
           Required For Online: no

● 4: br0                        
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: /etc/systemd/network/br0.network
                          Type: bridge
                         State: routable (configured)
                  Online state: online
                        Driver: bridge
              Hardware Address: 12:53:9f:19:83:29
                           MTU: 9000 (min: 68, max: 65535)
                         QDisc: noqueue
  IPv6 Address Generation Mode: eui64
                 Forward Delay: 14.990s
                    Hello Time: 1.990s
                       Max Age: 19.990s
                   Ageing Time: 4min 59.990s
                      Priority: 32768
                           STP: no
        Multicast IGMP Version: 2
                          Cost: 1999
                    Port State: disabled
          Queue Length (Tx/Rx): 1/1
              Auto negotiation: no
                         Speed: 2Gbps
                       Address: 10.10.10.10 (DHCP4 via 10.10.10.1)
                                240e:381:4555:1600:9621:a98b:c18f:cfa1
                                240e:381:4555:1600:a8fe:c5e9:657e:6dc6
                                fd3c:731a:706b::5c4
                                fd3c:731a:706b:0:3501:5ede:8f26:4c08
                                fd3c:731a:706b:0:8a30:cd28:6be1:240c
                                fe80::1053:9fff:fe19:8329
                       Gateway: 10.10.10.1
                                fe80::5054:ff:fe5c:d6b3
                           DNS: 10.10.10.1
                                fd3c:731a:706b::1
                                fe80::767d:24ff:febd:fe20
             Activation Policy: up
           Required For Online: yes
               DHCP4 Client ID: IAID:0xe2890d07/DUID
             DHCP6 Client IAID: 0xe2890d07
             DHCP6 Client DUID: DUID-EN/Vendor:0000ab111b3f9218eb97b87a0000

● 6: enp7s0f2                   
                     Link File: /etc/systemd/network/10-sr-iov.link
                  Network File: /etc/systemd/network/sr-iov.network
                          Type: ether
                         State: no-carrier (configuring)
                  Online state: unknown
                          Path: pci-0000:07:00.2
                        Driver: igb
                        Vendor: Intel Corporation
                         Model: I350 Gigabit Network Connection (Ethernet Server Adapter I350-T4)
              Hardware Address: a0:36:9f:8c:12:12 (Intel Corporate)
                           MTU: 1500 (min: 68, max: 9216)
                         QDisc: mq
  IPv6 Address Generation Mode: eui64
          Queue Length (Tx/Rx): 8/8
              Auto negotiation: yes
                         Speed: n/a
                          Port: tp
             Activation Policy: always-up
           Required For Online: no
             DHCP6 Client DUID: DUID-EN/Vendor:0000ab111b3f9218eb97b87a0000

● 7: enp7s0f3                   
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: n/a
                          Type: ether
                         State: off (unmanaged)
                  Online state: unknown
                          Path: pci-0000:07:00.3
                        Driver: igb
                        Vendor: Intel Corporation
                         Model: I350 Gigabit Network Connection (Ethernet Server Adapter I350-T4)
              Hardware Address: a0:36:9f:8c:12:13 (Intel Corporate)
                           MTU: 1500 (min: 68, max: 9216)
                         QDisc: noop
  IPv6 Address Generation Mode: eui64
          Queue Length (Tx/Rx): 8/8
              Auto negotiation: yes
                         Speed: n/a
                          Port: tp
             Activation Policy: up
           Required For Online: yes

● 8: wlp5s0                     
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: n/a
                          Type: wlan
                         State: off (unmanaged)
                  Online state: unknown
                          Path: pci-0000:05:00.0
                        Driver: iwlwifi
                        Vendor: Intel Corporation
                         Model: Wi-Fi 6 AX200 (NGW)
              Hardware Address: 20:1e:88:d5:e1:ca (Intel Corporate)
                           MTU: 1500 (min: 256, max: 2304)
                         QDisc: noop
  IPv6 Address Generation Mode: eui64
             WiFi access point: (null) (00:00:00:00:00:00)
          Queue Length (Tx/Rx): 1/1
             Activation Policy: up
           Required For Online: yes

● 9: enp7s0f2v0                 
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: n/a
                          Type: ether
                         State: off (unmanaged)
                  Online state: unknown
                          Path: pci-0000:08:10.2
                        Driver: igbvf
                        Vendor: Intel Corporation
                         Model: I350 Ethernet Controller Virtual Function
              Hardware Address: 7e:8d:da:b4:53:3f
    Permanent Hardware Address: 66:2f:35:4e:48:b3
                           MTU: 1500 (min: 68, max: 9216)
                         QDisc: noop
  IPv6 Address Generation Mode: eui64
          Queue Length (Tx/Rx): 1/1
              Auto negotiation: no
                         Speed: n/a
             Activation Policy: up
           Required For Online: yes

● 10: enp7s0f2v1                
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: n/a
                          Type: ether
                         State: off (unmanaged)
                  Online state: unknown
                          Path: pci-0000:08:10.6
                        Driver: igbvf
                        Vendor: Intel Corporation
                         Model: I350 Ethernet Controller Virtual Function
              Hardware Address: 12:b3:9b:d1:85:4b
    Permanent Hardware Address: 46:81:39:d3:4e:cb
                           MTU: 1500 (min: 68, max: 9216)
                         QDisc: noop
  IPv6 Address Generation Mode: eui64
          Queue Length (Tx/Rx): 1/1
              Auto negotiation: no
                         Speed: n/a
             Activation Policy: up
           Required For Online: yes

● 11: enp7s0f2v2                
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: n/a
                          Type: ether
                         State: off (unmanaged)
                  Online state: unknown
                          Path: pci-0000:08:11.2
                        Driver: igbvf
                        Vendor: Intel Corporation
                         Model: I350 Ethernet Controller Virtual Function
              Hardware Address: fa:ac:ee:7f:a5:65
    Permanent Hardware Address: b2:3d:a8:76:1c:1e
                           MTU: 1500 (min: 68, max: 9216)
                         QDisc: noop
  IPv6 Address Generation Mode: eui64
          Queue Length (Tx/Rx): 1/1
              Auto negotiation: no
                         Speed: n/a
             Activation Policy: up
           Required For Online: yes

● 12: virbr0                    
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: n/a
                          Type: bridge
                         State: no-carrier (unmanaged)
                  Online state: unknown
                        Driver: bridge
              Hardware Address: 52:54:00:e8:a2:1e
                           MTU: 1500 (min: 68, max: 65535)
                         QDisc: noqueue
  IPv6 Address Generation Mode: eui64
                 Forward Delay: 1.990s
                    Hello Time: 1.990s
                       Max Age: 19.990s
                   Ageing Time: 4min 59.990s
                      Priority: 32768
                           STP: yes
        Multicast IGMP Version: 2
                          Cost: 1999
                    Port State: disabled
          Queue Length (Tx/Rx): 1/1
              Auto negotiation: no
                         Speed: n/a
                       Address: 192.168.122.1
             Activation Policy: up
           Required For Online: yes

● 13: vnet0                     
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: n/a
                          Type: ether
                         State: enslaved (unmanaged)
                  Online state: unknown
                        Driver: tun
              Hardware Address: fe:54:00:5c:d6:b3
                           MTU: 9000 (min: 68, max: 65521)
                         QDisc: noqueue
                        Master: br0
  IPv6 Address Generation Mode: eui64
          Queue Length (Tx/Rx): 1/1
              Auto negotiation: no
                         Speed: 10Mbps
                        Duplex: full
                          Port: tp
                       Address: fe80::fc54:ff:fe5c:d6b3
             Activation Policy: up
           Required For Online: yes

```

**Comment by yuwata** [comment] 2022-01-26 07:00
From your console, could you run `SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/systemd-networkd-wait-online`, and provide the result?

**Comment by daiaji** [comment] 2022-01-26 07:04
```
sudo SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/systemd-networkd-wait-online
Found link 13
Found link 12
Found link 11
Found link 10
Found link 9
Found link 8
Found link 7
Found link 6
Found link 3
Found link 2
Found link 1
enp7s0f2v2: Operational state 'off' is not in range ['degraded':'routable']
wlp5s0: Operational state 'off' is not in range ['degraded':'routable']
lo: link is ignored
enp7s0f2v1: Operational state 'off' is not in range ['degraded':'routable']
virbr0: Operational state 'no-carrier' is not in range ['degraded':'routable']
enp6s0: link is ignored
enp7s0f2v0: Operational state 'off' is not in range ['degraded':'routable']
enp7s0f3: Operational state 'off' is not in range ['degraded':'routable']
enp7s0f2: link is ignored
```

**Comment by yuwata** [comment] 2022-01-26 07:05
It finishes almost instantaneously? Or does it timed out?

**Comment by daiaji** [comment] 2022-01-26 07:06
Complete in an instant

**Comment by yuwata** [comment] 2022-01-26 07:15
Ah, maybe I got the root cause. Please try to create the following .network file:
```
# 99-vnet0.network
[Match]
Name=vnet0

[Link]
RequiredForOnline=no
```
If it works for you, then I will post a fix soon.

**Comment by daiaji** [comment] 2022-01-26 07:27
That seems to be a bridge network managed by libvirt, and once I configure it, my PC can't get online.

**Comment by yuwata** [comment] 2022-01-26 07:45
Ah, then, how about the following?
```
# 99-vnet0.network
[Match]
Name=vnet0

[Link]
Unmanaged=yes
```
Then, networkd does not touch anything about the interface, and should not interfere with libvirt.

**Comment by daiaji** [comment] 2022-01-26 08:08
```
cat /etc/systemd/network/99-vnet0.network
[Match]
Name=vnet0

[Link]
RequiredForOnline=no
Unmanaged=yes
```
```
sudo SYSTEMD_LOG_LEVEL=debug /usr/lib/systemd/systemd-networkd-wait-online
Found link 13
Found link 12
Found link 11
Found link 10
Found link 9
Found link 8
Found link 7
Found link 6
Found link 5
Found link 3
Found link 1
wlp5s0: Operational state 'off' is not in range ['degraded':'routable']
enp7s0f2v0: Operational state 'off' is not in range ['degraded':'routable']
virbr0: Operational state 'no-carrier' is not in range ['degraded':'routable']
enp7s0f2v2: Operational state 'off' is not in range ['degraded':'routable']
enp6s0: link is ignored
enp7s0f2v1: Operational state 'off' is not in range ['degraded':'routable']
enp7s0f3: Operational state 'off' is not in range ['degraded':'routable']
enp7s0f2: link is ignored
lo: link is ignored
```
The vnet0 interface doesn't seem to be ignored.

**Comment by yuwata** [comment] 2022-01-26 08:36
Thanks. I hope that PR #22249 fixes the issue.

**Comment by yuwata** [comment] 2022-01-26 08:39
Unfortunately, workaround for this issue is only setting `-i br0`, and `RequiredForOnline=no` does not work, as you already observed.

**Comment by daiaji** [comment] 2022-01-26 10:46
> Unfortunately, workaround for this issue is only setting `-i br0`, and `RequiredForOnline=no` does not work, as you already observed.

It looks like it does, I used your commit, the vnet0 interface is no longer detected, but the detection of the other interfaces (enp6s0 and enp7s0f2) seems to sometimes still affect my test scripts, I now configure for the enp6s0 and enp7s0f2 interfaces With the RequiredForOnline=no parameter, everything seems to work fine.

However, too many places that require additional configuration at this stage may greatly reduce the usability of systemd-networkd-wait-online.

**Comment by yuwata** [comment] 2022-01-26 10:56
Thank you for testing the PR.

> but the detection of the other interfaces (enp6s0 and enp7s0f2) seems to sometimes still affect my test scripts

That's should be expected behavior, as they are managed (a .network file is assigned to the link), and they will be in 'enslaved' state. The 'enslaved' state is higher level than 'degraded', and the default minimum requirement of wait-online is 'degraded' state (degraded < enslaved < routable, as you can see that in the man page networkctl(1)).
So, setting `RequiredForOnline=no` to those irrelevant interfaces is necessary if you do not use `-i br0` option.

> However, too many places that require additional configuration at this stage may greatly reduce the usability of systemd-networkd-wait-online.

That depends on usecases. As you already observed, in your case, setting `RequiredForOnline=no` for non-relevant interfaces is not a good idea and not scalable. So, I recommend to use '-i br0'.

**Comment by daiaji** [comment] 2022-01-26 11:08
> That depends on usecases. As you already observed, in your case, setting `RequiredForOnline=no` for non-relevant interfaces is not a good idea and not scalable. So, I recommend to use '-i br0'.

Perhaps it is.

**Closed as completed** 2022-01-26 16:17 UTC
Labels: bug 🐛, network

**Comment by daiaji** [comment] 2022-01-30 05:23
@yuwata `After=network-online.target ` does not seem to guarantee that the network will be available before the service is started.
```
cat /usr/lib/systemd/system/test.service 
[Unit]
Description=nettest
#Wants=network-online.target
After=network-online.target

[Service]
ExecStart=/bin/sh -c 'networkctl status br0 > /var/log/test.log'
KillMode=process

[Install]
WantedBy=multi-user.target
```
```
cat /var/log/test.log
● 4: br0                        
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: /etc/systemd/network/br0.network
                          Type: bridge
                         State: degraded-carrier (configuring)
                  Online state: offline
                        Driver: bridge
              Hardware Address: d6:af:e0:d2:b2:7c
                           MTU: 9000 (min: 68, max: 65535)
                         QDisc: noqueue
  IPv6 Address Generation Mode: eui64
                 Forward Delay: 14.990s
                    Hello Time: 1.990s
                       Max Age: 19.990s
                   Ageing Time: 4min 59.990s
                      Priority: 32768
                           STP: no
        Multicast IGMP Version: 2
                          Cost: 1999
                    Port State: disabled
          Queue Length (Tx/Rx): 1/1
              Auto negotiation: no
                         Speed: n/a
                       Address: fe80::d4af:e0ff:fed2:b27c
             Activation Policy: up
           Required For Online: yes
             DHCP6 Client DUID: DUID-EN/Vendor:0000ab11ea61f7f08ab001970000

1月 30 13:16:08 RingCity systemd-networkd[480]: br0: netdev ready
1月 30 13:16:09 RingCity systemd-networkd[480]: br0: Link UP
1月 30 13:16:09 RingCity systemd-networkd[480]: br0: Gained carrier
1月 30 13:16:10 RingCity systemd-networkd[480]: br0: Gained IPv6LL
1月 30 13:16:10 RingCity systemd-networkd[480]: br0: Lost carrier
1月 30 13:16:10 RingCity systemd-networkd[480]: br0: DHCPv6 lease lost
```

> After= ensures the opposite, that the listed unit is fully started up before the configured unit is started.

This seems to contradict the description of the document.

**Comment by yuwata** [comment] 2022-01-31 04:18
@daiaji Could you open a new issue page? At that time, please
- enable to generate debugging logs in systemd-networkd-wait-online.service, and provide journal log,
- provide all .network files,
- clarify which version you use (current git HEAD? with or without #22249?).

Thank you!

**Comment by daiaji** [comment] 2022-02-01 18:24
@yuwata Maybe this is a bug again? , I will compile the latest HEAD tomorrow and test it.
