### ISSUE TITLE
System stays frozen after suspend

### ISSUE THREAD

**Issue by abderrahim** [systemd/systemd#33269] opened 2024-06-10 22:11 UTC
### systemd version the issue has been seen with

256~rc4

### Used distribution

Debian sid

### Linux kernel version used

6.8.12-amd64

### CPU architectures issue was seen on

x86_64

### Expected behaviour you didn't see

System resumes from suspend normally

### Unexpected behaviour you saw

System stays frozen after resume. The screen doesn't turn back on, pressing num lock doesn't change the num lock led state.

I'm noting the different things I tried and the results. I noticed that there are some journal entries after the freeze. Nothing that seemed very interesting

It happened again, so:
* I tried to ssh into the machine, and it works.
* Tried to reboot the machine from ssh.
  * The screen turned on.
  * I noticed systemd error messages about "frozen unit cannot be stopped"
  * eventually the machine rebooted

It happened again another time
* ssh into the machine
* ran `sudo systemctl thaw "*"`
* screen turns on, and the system works

### Steps to reproduce the problem

It doesn't happen reliably, but I didn't do anything except letting the system suspend on its own.

I noticed it doesn't happen when I don't have much open, but it might be a coincidence.

### Additional program output to the terminal or log subsystem illustrating the issue

https://gist.github.com/abderrahim/af858e36d587f7a1d3935a023d88719d is an example where I pressed the power button to suspend.

```sh
* 22:55:37 suspend initiated
* 22:58:02 resume initated
* 22:58:47 logged in via ssh
* 22:59:04 tried to thaw units
```

**Comment by YHNdnzj** [comment] 2024-06-11 08:43
Duplicate of #33083, but it seems the fix was incomplete.

**Comment by keszybz** [comment] 2024-06-11 09:58
@abderrahim Please attach boot logs, `journalctl -b` from the affected boot.

**Comment by bluca** [comment] 2024-06-11 10:13
The log is on the gist https://gist.github.com/abderrahim/af858e36d587f7a1d3935a023d88719d

**Comment by keszybz** [comment] 2024-06-11 10:17
``
`Jun 10 22:55:37 lancelot systemd-logind[909]: The system will suspend now!
Jun 10 22:55:37 lancelot ModemManager[996]: <msg> [sleep-monitor-systemd] system is about to suspend
...
Jun 10 22:55:48 lancelot systemd-sleep[422408]: Failed to freeze unit 'user.slice': Connection timed out
Jun 10 22:55:48 lancelot systemd-sleep[422408]: Performing sleep operation 'suspend'...
```

**Comment by YHNdnzj** [comment] 2024-06-11 10:38
> The timeout should make the issue less likely. But the proper fix would be to handle this scenario better and not fail when resuming.

I already have some ideas on making this more robust. Will submit a patch.

**Closed as completed** 2024-06-11 13:56 UTC
Labels: bug 🐛, sleep

**Comment by keszybz** [comment] 2024-06-11 14:03
For anyone reading: the patch that was merged is a straightforward fix that is supposed to suppress the issue for v256. A better fix will hopefully be applied later, but we don't want to do any bigger changes at this point in the release cycle.

**Comment by xuanruiqi** [comment] 2024-06-20 17:44
Apparently, I'm on 256 and still getting this issue. It seems that 60s isn't quite enough:
```
6月 20 20:52:49 xuanrui-desktop systemd-logind[953]: The system will suspend now!
6月 20 20:52:49 xuanrui-desktop NetworkManager[7756]: <info>  [1718884369.2691] manager: sleep: sleep requested (sleeping: no  enabled: yes)
6月 20 20:52:49 xuanrui-desktop NetworkManager[7756]: <info>  [1718884369.2692] manager: NetworkManager state is now ASLEEP
...
6月 20 20:52:50 xuanrui-desktop systemd[1]: Starting System Suspend...
6月 20 20:53:50 xuanrui-desktop systemd-sleep[39463]: Failed to freeze unit 'user.slice': Connection timed out
6月 20 20:53:50 xuanrui-desktop systemd-sleep[39463]: Performing sleep operation 'suspend'...```

Not sure what's wrong on my end. But apparently delaying things don't fix them.

**Comment by YHNdnzj** [comment] 2024-06-21 10:03
@xuanruiqi Could you please try #33092?

**Comment by xuanruiqi** [comment] 2024-06-21 10:45
I still get failed to freeze, but that doesn't block me from suspending and unfreezing my machine anymore. Thanks.

BTW, could anyone provide me some pointers on how to debug this particular error? (`Failed to freeze unit 'user.slice': Connection timed out`)

**Comment by YHNdnzj** [comment] 2024-06-21 14:11
> BTW, could anyone provide me some pointers on how to debug this particular error? (Failed to freeze unit 'user.slice': Connection timed out)

We're waiting for cgroup event from kernel on this one, so maybe something running in your user.slice doesn't play well with cgroup freezer. The kernel people should have better knowledge on this.

**Comment by xuanruiqi** [comment] 2024-06-22 11:57
Yeah, issue is gone after update to 6.9.6. It must have been a regression in 6.9.5.
