### ISSUE TITLE
crash when running systemctl is-enabled '' (empty argument)

### ISSUE THREAD

**Issue by Bluewind** [systemd/systemd#5566] opened 2017-03-10 13:36 UTC
### Submission type

  - [x] Bug report
  - [ ] Request for enhancement (RFE)

*NOTE: Do not submit anything other than bug reports or RFEs via the issue tracker!*

### systemd version the issue has been seen with

> 232-8

*NOTE: Do not submit bug reports about anything but the two most recently released systemd versions upstream!*

### Used distribution

> Arch Linux

### In case of bug report: Expected behaviour you didn't see

> Error message or similar about empty argument

### In case of bug report: Unexpected behaviour you saw

> systemctl is-enabled ''
*** Error in `systemctl': free(): invalid pointer: 0x00007f0bfa37ab38 ***
======= Backtrace: =========
/usr/lib/libc.so.6(+0x70c4b)[0x7f0bfa052c4b]
/usr/lib/libc.so.6(+0x76fe6)[0x7f0bfa058fe6]
/usr/lib/libc.so.6(+0x777de)[0x7f0bfa0597de]
/usr/lib/systemd/libsystemd-shared-232.so(strv_clear+0x29)[0x7f0bfa691d89]
/usr/lib/systemd/libsystemd-shared-232.so(strv_free+0x9)[0x7f0bfa691db9]
systemctl(+0x15a15)[0x5562b7b36a15]
systemctl(+0x19557)[0x5562b7b3a557]
/usr/lib/systemd/libsystemd-shared-232.so(dispatch_verb+0x20d)[0x7f0bfa677c8d]
systemctl(+0x7bbb)[0x5562b7b28bbb]
/usr/lib/libc.so.6(__libc_start_main+0xf1)[0x7f0bfa002291]
systemctl(+0x981a)[0x5562b7b2a81a]
======= Memory map: ========
[snipped]

### In case of bug report: Steps to reproduce the problem

> ``systemctl is-enabled ''``

**Comment by evverx** [comment] 2017-03-10 14:47
Duplicate of #5483

**Closed as completed by evverx** 2017-03-10 14:47 UTC
Labels: systemctl, duplicate
