### ISSUE TITLE
systemd --user instance ability to reference systemd --system services with After= etc.

### ISSUE THREAD

**Issue by adrelanos** [systemd/systemd#5462] opened 2017-02-26 17:36 UTC
### Submission type

  - [x] Request for enhancement (RFE)

### systemd version the issue has been seen with

> 232

### Used distribution

Debian

#### use case

Converting `/etc/xdg/autostart/app.desktop` (graphical autostart applications) to `systemd --user` services. In Qubes, graphical applications must start `After=qubes-gui-agent.service` (a `systemd --system` service). But not necessarily any service to be converted from `/etc/xdg/autostart/app.desktop` to a systemd unit needs that.

#### suggestion

A useful feature would be if systemd unit file running under a `systemd --user` instance could reference `After=some-system.service`.

**Comment by poettering** [comment] 2017-02-26 21:09
Duplicate of #3312

**Closed as completed by poettering** 2017-02-26 21:09 UTC
Labels: RFE 🎁, pid1, duplicate
