### ISSUE TITLE
src/network/networkd-link.c: In function link_sysctl_ipv6_enabled ... error: ‘%s’ directive argument is null [-Werror=format-overflow=]

### ISSUE THREAD

**Issue by floppym** [systemd/systemd#12931] opened 2019-07-02 19:55 UTC
**systemd version the issue has been seen with**
93912e872fb14e9c372e090409e429084a6450f5

**Used distribution**
Gentoo
gcc-9.1.0

```
FAILED: src/network/70b1c79@@networkd-core@sta/networkd-link.c.o
x86_64-pc-linux-gnu-gcc -Isrc/network/70b1c79@@networkd-core@sta -Isrc/network -I../systemd-9999/src/network -Isrc/basic -I../systemd-9999/src/basic -Isrc/shared -I../systemd-9999/src/shared -Isrc/systemd -I../systemd-9999/src/systemd -Isrc/journal -I../systemd-9999/src/journal -Isrc/journal-remote -I../systemd-9999/src/journal-remote -Isrc/nspawn -I../systemd-9999/src/nspawn -Isrc/resolve -I../systemd-9999/src/resolve -Isrc/timesync -I../systemd-9999/src/timesync -I../systemd-9999/src/time-wait-sync -Isrc/login -I../systemd-9999/src/login -Isrc/udev -I../systemd-9999/src/udev -Isrc/libudev -I../systemd-9999/src/libudev -Isrc/core -I../systemd-9999/src/core -Isrc/shutdown -I../systemd-9999/src/shutdown -I../systemd-9999/src/libsystemd/sd-bus -I../systemd-9999/src/libsystemd/sd-device -I../systemd-9999/src/libsystemd/sd-event -I../systemd-9999/src/libsystemd/sd-hwdb -I../systemd-9999/src/libsystemd/sd-id128 -I../systemd-9999/src/libsystemd/sd-netlink -I../systemd-9999/src/libsystemd/sd-network -I../systemd-9999/src/libsystemd/sd-resolve -Isrc/libsystemd-network -I../systemd-9999/src/libsystemd-network -I. -I../systemd-9999/ -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=gnu99 -Wextra -Werror=undef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wfloat-equal -Wsuggest-attribute=noreturn -Werror=missing-prototypes -Werror=implicit-function-declaration -Werror=missing-declarations -Werror=return-type -Werror=incompatible-pointer-types -Werror=format=2 -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wimplicit-fallthrough=5 -Wshadow -Wendif-labels -Wstrict-aliasing=2 -Wwrite-strings -Werror=overflow -Werror=shift-count-overflow -Werror=shift-overflow=2 -Wdate-time -Wnested-externs -Wno-unused-parameter -Wno-missing-field-initializers -Wno-unused-result -Wno-format-signedness -Wno-error=nonnull -Wno-maybe-uninitialized -ffast-math -fno-common -fdiagnostics-show-option -fno-strict-aliasing -fvisibility=hidden -fstack-protector -fstack-protector-strong --param=ssp-buffer-size=4 -ffunction-sections -fdata-sections -Werror=shadow -include config.h -O2 -march=amdfam10 -fPIC -MD -MQ 'src/network/70b1c79@@networkd-core@sta/networkd-link.c.o' -MF 'src/network/70b1c79@@networkd-core@sta/networkd-link.c.o.d' -o 'src/network/70b1c79@@networkd-core@sta/networkd-link.c.o' -c ../systemd-9999/src/network/networkd-link.c
In file included from ../systemd-9999/src/basic/macro.h:558,
                 from ../systemd-9999/src/basic/alloc-util.h:9,
                 from ../systemd-9999/src/network/networkd-link.c:7:
../systemd-9999/src/network/networkd-link.c: In function ‘link_sysctl_ipv6_enabled’:
../systemd-9999/src/basic/log.h:104:9: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
  104 |         log_internal_realm(LOG_REALM_PLUS_LEVEL(LOG_REALM, (level)), __VA_ARGS__)
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../systemd-9999/src/shared/log-link.h:21:25: note: in expansion of macro ‘log_internal’
   21 |                         log_internal(level, error, __FILE__, __LINE__, __func__, ##__VA_ARGS__); \
      |                         ^~~~~~~~~~~~
../systemd-9999/src/shared/log-link.h:33:50: note: in expansion of macro ‘log_link_full’
   33 | #define log_link_warning_errno(link, error, ...) log_link_full(link, LOG_WARNING, error, ##__VA_ARGS__)
      |                                                  ^~~~~~~~~~~~~
../systemd-9999/src/network/networkd-link.c:77:24: note: in expansion of macro ‘log_link_warning_errno’
   77 |                 return log_link_warning_errno(link, r,
      |                        ^~~~~~~~~~~~~~~~~~~~~~
../systemd-9999/src/network/networkd-link.c:78:77: note: format string is defined here
   78 |                                               "Failed to read net.ipv6.conf.%s.disable_ipv6 sysctl property: %m",
      |                                                                             ^~
cc1: some warnings being treated as errors
```

**Comment by ssahani** [comment] 2019-07-03 07:52
cc @keszybz

**Comment by yuwata** [comment] 2019-07-03 08:22
Maybe, duplicate of #12454?

**Comment by floppym** [comment] 2019-07-08 17:20
@yuwata I believe you introduced this failure with bafa9641446852f7fa15ca12d08a223d345c78ea.

**Comment by floppym** [comment] 2019-07-08 17:25
I think adding this to the top of link_sysctl_ipv6_enabled would resolve the issue.
```
assert(link);
assert(link->ifname);
```

**Comment by floppym** [comment] 2019-07-08 17:55
Hmm, I'm a bit confused here.

Adding an assert after the `sysctl_read_ip_property` call eliminates the error.
```
--- a/src/network/networkd-link.c
+++ b/src/network/networkd-link.c
@@ -73,6 +73,7 @@ int link_sysctl_ipv6_enabled(Link *link) {
         int r;

         r = sysctl_read_ip_property(AF_INET6, link->ifname, "disable_ipv6", &value);
+        assert(link && link->ifname);
         if (r < 0)
                 return log_link_warning_errno(link, r,
                                               "Failed to read net.ipv6.conf.%s.disable_ipv6 sysctl property: %m",
```
Adding it before `sysctl_read_ip_property` fails.
```
--- a/src/network/networkd-link.c
+++ b/src/network/networkd-link.c
@@ -72,6 +72,8 @@ int link_sysctl_ipv6_enabled(Link *link) {
         _cleanup_free_ char *value = NULL;
         int r;

+        assert(link && link->ifname);
+
         r = sysctl_read_ip_property(AF_INET6, link->ifname, "disable_ipv6", &value);
         if (r < 0)
                 return log_link_warning_errno(link, r,
```

**Comment by yuwata** [comment] 2019-07-08 17:59
I believe this is a bug of gcc-9.

BTW, the saved value is not used. I've created #12990.

**Comment by floppym** [comment] 2019-07-08 18:08
> I believe this is a bug of gcc-9.

If someone can point me at a GCC bug report or a patch, I can alert Gentoo's toolchain team.

**Comment by yuwata** [comment] 2019-07-09 05:55
gcc-9.1.1-1.fc30.x86_64 can build systemd without this error.

**Comment by keszybz** [comment] 2019-07-09 08:03
Please reopen if it still happens with gcc-9.1.1.

**Comment by floppym** [comment] 2019-07-09 14:59
This appears to be triggered by certain optimization levels. With CFLAGS unset, the build is successful. With `CFLAGS="-O2"`, I get the error. Could you please try to reproduce this with Fedora's compiler?

```
CFLAGS="-O2" meson build
ninja -C build
```

**Comment by yuwata** [comment] 2019-07-09 15:02
Yes, I found that this can be reproduced with -O2, -O3 or -Os

**Comment by yuwata** [comment] 2019-07-10 07:39
See also https://github.com/systemd/systemd-centos-ci/issues/143.

**Comment by mrc0mmand** [comment] 2019-07-10 08:24
It's worth mentioning the reports from systemd/systemd-centos-ci#143 are from Fedora (gcc 9.1.1).

**Closed as completed** 2019-07-10 14:20 UTC
Labels: util-lib, not-our-bug
