### ISSUE TITLE
journal rate limiting is borked for short-living processes

### ISSUE THREAD

**Issue by evverx** [systemd/systemd#1456] opened 2015-10-04 04:13 UTC
`systemd-cat` execs `cat`
`cat` writes to the [`sd_journal_stream_fd`](http://www.freedesktop.org/software/systemd/man/sd_journal_stream_fd.html) and exits.
`journal-server` [tries](https://github.com/systemd/systemd/blob/master/src/journal/journald-server.c#L593) to get info about exited `cat`

``` sh
$ seq 1 1000 | systemd-cat

$ journalct -e
...
Oct 04 13:45:26 jessie-64 cat[1921]: 18
Oct 04 13:45:26 jessie-64 cat[1921]: 19
Oct 04 13:45:26 jessie-64 unknown[1921]: 20
Oct 04 13:45:26 jessie-64 unknown[1921]: 21
...

$ journalctl MESSAGE=1 _PID=1921 -o verbose
-- Logs begin at Mon 2015-09-28 10:32:57 VLAT, end at Sun 2015-10-04 13:47:01 VL
Sun 2015-10-04 13:45:26.009220 VLAT [s=602a2cf9ff774e51929098e5df2b9ac8;i=ce9a9;
    PRIORITY=6
    _UID=1000
    _GID=1000
    _CAP_EFFECTIVE=0
    _SYSTEMD_OWNER_UID=1000
    _SYSTEMD_SLICE=user-1000.slice
    _MACHINE_ID=a0bca4d8e31847608728ea41f8aedc17
    _TRANSPORT=stdout
    MESSAGE=1
    _COMM=cat
    _EXE=/bin/cat
    _CMDLINE=/bin/cat
    _AUDIT_LOGINUID=1000
    _BOOT_ID=1d5bc57f93c9418fbfdb363906321f6b
    _AUDIT_SESSION=3
    _SYSTEMD_CGROUP=/user.slice/user-1000.slice/session-3.scope
    _SYSTEMD_SESSION=3
    _SYSTEMD_UNIT=session-3.scope
    _HOSTNAME=jessie-64
    _PID=1921

$ journalctl MESSAGE=1000 _PID=1921 -o verbose
-- Logs begin at Mon 2015-09-28 10:32:57 VLAT, end at Sun 2015-10-04 13:47:01 VL
Sun 2015-10-04 13:45:26.079659 VLAT [s=602a2cf9ff774e51929098e5df2b9ac8;i=ced90;
    PRIORITY=6
    _UID=1000
    _GID=1000
    _MACHINE_ID=a0bca4d8e31847608728ea41f8aedc17
    _TRANSPORT=stdout
    _BOOT_ID=1d5bc57f93c9418fbfdb363906321f6b
    _HOSTNAME=jessie-64
    MESSAGE=1000
    _PID=1921
```

**Comment by evverx** [comment] 2015-10-04 04:56
Actually, I think `systemd-cat` is deprecated:)
`systemd-run cmd` or `logger --journald` can replace it.

**Comment by poettering** [comment] 2015-10-04 15:12
Nah, it's not deprecated at all... systemd-run does something very different, it runs code in service units and only as side-effect connects their stdout/stderr with the journal. And systemd-cat has the benefit that it doesn't need to stay around to do its job. It can execute binaries with stdout/stderr connected to the journal and doesn't need to remain in memory for that. That's something logger cannot do.

But anyway, you are running into a well-known race: the metadata we get via the PID of peer, but that fails if the process already exited by the time we try to get the metadata. A fix for this requires a kernel change, so that we get the metadata at the same time as the messages.

**Comment by evverx** [comment] 2015-10-06 02:15
> Nah, it's not deprecated at all... systemd-run does something very different

Oh, I see. Thanks for the explanation.

> But anyway, you are running into a well-known race: the metadata we get via the PID of peer, but that fails if the process already exited by the time we try to get the metadata.

I've found the same problem [here](https://github.com/systemd/systemd/blob/master/src/journal/journald-server.c#L888).
So, the rate limiting doesn't work for short-living processes.
Anyone can overwrite the journal with `while :; do seq 1 10000 | systemd-cat; done` :)

**Comment by psz2036** [comment] 2015-10-29 20:34
Would it help to set cgroup.clone_children=1 for the grandparent?

> ... a well-known race ... A fix for this requires a kernel change, so
> that we get the metadata at the same time as the messages.

No: the issue is the delay between the message being sent, and acted
upon. Maybe we could "hold" the process quickly (with SIGSTOP or
ptrace), do our things, then release? Would that be quick enough?
See also
https://bugs.launchpad.net/ubuntu/+source/libcgroup/+bug/827419
about the exact same issue elsewhere.

**Comment by evverx** [comment] 2017-08-01 15:20
The issue seems to have been fixed by https://github.com/systemd/systemd/pull/6392. I'll double-check and close if everything is OK.

**Comment by evverx** [comment] 2017-08-01 15:40
On the other hand, it is still possible to overload `journald` so that it can't handle messages in time, so I'd prefer to keep the issue open.

**Comment by poettering** [comment] 2017-09-20 13:38
This is more less the same as #2913 (which has a slightly broader topic), let's close this one as duplicate

**Closed as completed by poettering** 2017-09-20 13:38 UTC
Labels: bug 🐛, journal, duplicate
