### ISSUE TITLE
Assertion 'fd' failed at ../systemd-237/src/basic/socket-util.c:1011, function getpeergroups(). Aborting.

### ISSUE THREAD

**Issue by uzytkownik** [systemd/systemd#8148] opened 2018-02-09 18:33 UTC
### Submission type

 - Bug report

### systemd version the issue has been seen with

> 237

### Used distribution

> Gentoo

### In case of bug report: Expected behaviour you didn't see

> Domain is resolved

### In case of bug report: Unexpected behaviour you saw

> Resolving address crashes program when using nss

### In case of bug report: Steps to reproduce the problem

> ??? I get consistent crash for one particular program. It does not happen when I switch to dns and doing it over 127.0.0.53 (that is - the server doesn't crash).

```
Assertion 'fd' failed at ../systemd-237/src/basic/socket-util.c:1011, function getpeergroups(). Aborting.
#1  0x00007fa4060d9ebf in __GI_abort () at abort.c:90
#2  0x00007fa404d3e495 in log_assert_failed_realm (realm=realm@entry=LOG_REALM_SYSTEMD, text=text@entry=0x7fa404d4dc02 "fd", file=file@entry=0x7fa404d4f128 "../systemd-237/src/basic/socket-util.c", 
    line=line@entry=1011, func=func@entry=0x7fa404d4f170 <__PRETTY_FUNCTION__.11562> "getpeergroups") at ../systemd-237/src/basic/log.c:820
#3  0x00007fa404d42f21 in getpeergroups (fd=<optimized out>, ret=ret@entry=0x1dd17d8) at ../systemd-237/src/basic/socket-util.c:1011
#4  0x00007fa404d351c6 in bus_get_peercred (b=0x1dd15c0) at ../systemd-237/src/libsystemd/sd-bus/bus-socket.c:623
#5  bus_socket_start_auth (b=b@entry=0x1dd15c0) at ../systemd-237/src/libsystemd/sd-bus/bus-socket.c:674
#6  0x00007fa404d356b4 in bus_socket_connect (b=b@entry=0x1dd15c0) at ../systemd-237/src/libsystemd/sd-bus/bus-socket.c:935
#7  0x00007fa404d23d77 in bus_start_address (b=0x1dd15c0) at ../systemd-237/src/libsystemd/sd-bus/sd-bus.c:1120
#8  0x00007fa404d27006 in sd_bus_start (bus=0x1dd15c0) at ../systemd-237/src/libsystemd/sd-bus/sd-bus.c:1204
#9  0x00007fa404d27306 in sd_bus_open_system (ret=ret@entry=0x7ffec2ba8450) at ../systemd-237/src/libsystemd/sd-bus/sd-bus.c:1305
#10 0x00007fa404d1350c in _nss_resolve_gethostbyname4_r (name=name@entry=0x420007ad20 "XXXXXXXXX", pat=pat@entry=0x7ffec2ba8688, buffer=0x7ffec2ba8900 "", buflen=1024, 
    errnop=errnop@entry=0x7fa41a5866c0, h_errnop=h_errnop@entry=0x7fa41a586724, ttlp=0x0) at ../systemd-237/src/nss-resolve/nss-resolve.c:137
#11 0x00007fa406192165 in gaih_inet (name=name@entry=0x420007ad20 "XXXXXXXXX", service=<optimized out>, req=req@entry=0x420007ada0, pai=pai@entry=0x7ffec2ba8888, naddrs=naddrs@entry=0x7ffec2ba8884, 
    tmpbuf=tmpbuf@entry=0x7ffec2ba88f0) at ../sysdeps/posix/getaddrinfo.c:785
```

I think it might be cause by fd 0 being closed and reused as socket fd. If yes code should use -1 as invalid fd.

**Comment by poettering** [comment] 2018-02-09 18:38
Duplicate of #8075

**Closed as completed by poettering** 2018-02-09 18:38 UTC
Labels: sd-bus, duplicate
