### ISSUE TITLE
Netowrk interface is not configured if LLDP fails

### ISSUE THREAD

**Issue by nolange** [systemd/systemd#16392] opened 2020-07-07 13:12 UTC
Systemd:
> systemd 245 (245)
> -PAM -AUDIT -SELINUX -IMA -APPARMOR -SMACK -SYSVINIT -UTMP -LIBCRYPTSETUP -GCRYPT -GNUTLS -ACL -XZ +LZ4 -SECCOMP +BLKID -ELFUTILS +KMOD -IDN2 -IDN -PCRE2 default-hierarchy=unified

It seems that networkd stops configuring an adapter if enabling LLDP fails (supposedly not enabled in the kernel).

- if LLDP is required for the kernel, please document it
- if not, allow LLDP to fail while still configuring the interface

```
Jul 07 12:55:12 buildroot systemd-networkd[451]: enp3s0: Link UP
Jul 07 12:55:12 buildroot systemd-networkd[451]: enp3s0: Failed to start LLDP: Address family not supported by protocol
Jul 07 12:55:12 buildroot systemd-networkd[451]: Could not process link message, ignoring: Address family not supported by protocol
```

i can work around the issue by adding `LLDP=false` to the config files.

(This is a small "failsafe" kernel, that needs to fit in a couple MB)

**Comment by nolange** [comment] 2020-07-07 13:17
Looking at the source, its probably the raw packets that I am missing.

**Comment by yuwata** [comment] 2020-07-08 01:29
It seems a duplicate of #7145. systemd-networkd requires AF_PACKET.

**Closed as completed** 2020-07-08 01:29 UTC
Labels: network, duplicate
