### ISSUE TITLE
udev: interface name in link file not applied

### ISSUE THREAD

**Issue by daxtens** [systemd/systemd#9006] opened 2018-05-16 01:50 UTC
**systemd version the issue has been seen with**
v237

**Used distribution**
Ubuntu 18.04

**Expected behaviour you didn't see**
I have a link file with the following contents:

```
[Match]
MACAddress=52:54:00:69:1d:5b

[Link]
Name=myif3
WakeOnLan=off
```

I expect to see that when I boot, the interface is renamed to `myif3`.

**Unexpected behaviour you saw**

The interface is not renamed, it stays as `ens3`.

This usually **breaks networking** because other parts of the system assume the interface was renamed.

**Steps to reproduce the problem**

 - Create a virtual machine. (I use `uvtool`, but it doesn't really matter.)
 - If using Ubuntu 18.04, the simplest way to demonstrate this is to change `/etc/netplan/50-cloud-init.yaml` and change the `set-name:` yaml key to `myif3`. Then reboot.
 - If not using Ubuntu 18.04, create a link file that sets the Name of a Link, and reboot.
 - The interface is not renamed (as a result, network connectivity is probably broken.)

**Further Information**

I've done further analysis on this.

The interface will be renamed if the link file is in the initrd, but not if the file is absent from the initrd.

Firstly, systemd-udevd renames the interface when running out of initrd.  If the link file is in the initrd, it will be read and applied at that time. If the link file is *not* in the initrd, systemd-udevd will rename the device anyway according to NamePolicy. This will usually be a PCI slot id - here `ens3`. 

Once we leave initrd and get to the normal root file system, the systemd-udevd daemon will be started. This will also consider the link file, but because the interface has been renamed, the `name_assign_type` will be `NET_NAME_RENAMED` (4), so [`should_rename`](https://github.com/systemd/systemd/blob/v237/src/udev/net/link-config.c#L312) will return false and the device won't be renamed again. This is the cause of the unexpected behaviour.

I think `should_rename` should allow `NET_NAME_RENAMED` to be overridden; at least when there's a specific name given in the link file.

**Comment by daxtens** [comment] 2018-05-16 02:24
Just to expand on this a bit: this behaviour of link files is in contrast to the behaviour of rule files: in udev-event.c, interfaces with a rule that sets their name are renamed unconditionally with [this call to `rename_netif`](https://github.com/systemd/systemd/blob/v237/src/udev/udev-event.c#L888).

**Comment by arvidjaar** [comment] 2018-05-16 03:59
Arguably this is a bug in initramfs generator that should have included corresponding link file. dracut normally adds all `/usr/lib/systemd/network/*.link` and additionally `/etc/systemd/network/*.link` in host-only mode.

**Comment by yuwata** [comment] 2018-05-16 05:53
If your system does not require network stack during initrd, then how about disabling dracut network module or pass `net.ifnames=0` to the kernel command line?

If it requires network stack, then there are at least two choices:
1. add `net.ifnames=0 ifname=_networkname_:_mac_address_ ip=_networkname_:dhcp` or something to the kernel cmdline.
2. rebuild initrd to include the link files.

The first choice is what I use, because I do not want to rebuild initrd so often.

**Comment by daxtens** [comment] 2018-05-16 06:10
`net.ifnames=0` does work as a workaround, but I'm looking for a long term solution based on the behaviour of rules vs link files.

Here's the context: In Ubuntu 16.04, the first-boot network configuration system created a .rule file. Ubuntu 18.04 introduced a new network configuration system that makes .link files instead. We then noticed that interfaces were no longer being renamed. 

I verified that it's not related to any other changes between 16.04 and 18.04: I created a rules file on 18.04, and that caused the interface to be renamed as expected - even if the rules file was not in initrd.

Therefore, I'm trying to figure out if link files should operate the same way as rules files and override previously set names.

(With regards to initramfs, neither the rules nor the link file get built into the initrd until at least the next time update-initramfs is run - normally this doesn't occur until the kernel or other early-boot stuff is upgraded, which often doesn't happen for ephemeral cloud instances. So the question comes down to what the correct behaviour should be after you've pivoted to the real root.)

**Comment by poettering** [comment] 2018-05-17 16:32
Well, .link files are newer, and declarative, while rules files are more imperative. 

Generally we follow the rule to not override user choices again and again, and hence apply naming only one.

To me this appears a shortcoming of the tools in use. .link files should really be included in the initrd i guess... This is necessary in particular as network devices can't be renamed as soon as they are up, and there's a good chance they might be upped in the initrd again.

Hence, I am pretty sure this is something to work on with your distro: they should ensure that if .link files change the initrd is updated too.

**Comment by raharper** [comment] 2018-05-17 16:54
We're generating .link files and network configuration on-the-fly during boot, but outside an initramfs.  We also need this to work when booting without an initramfs.  The generation time happens before networking is configured, so it's perfectly fine to apply different interface names above distro/systemd policy.

If .link files are only useful if they are in place prior to udev starting, that does present a problem for generating .link files dynamically during boot.  That certainly imposes a lot on tools wishing to generating them: run before udev or reboot to apply.

Would it not be possible to preserve the "don't rename after the interface is up" while allowing .link files to apply even if already named once?

Users don't generally write directly to the initramfs so newly generate .link files with properties would end up being present on the rootfs first, needing to be copied into the initramfs and a reboot triggered to update an interface name.   We could avoid the update and reboot if we could apply .link files to downed interfaces.

**Comment by poettering** [comment] 2018-05-17 17:06
Well, you also have the option to simply not apply any renaming at all in the initrd, i.e. remove /usr/lib/systemd/network/99-default.link from the initrd. The issue after all is caused because that file is included in the initrd, but no others are, and hence it takes effect even though others will become available during later boot

**Comment by raharper** [comment] 2018-05-17 18:17
Equally caused by ignoring additional .link files if udev has already processed renames once.

The use-case where a user would like to rename an interface while it is down but without rebooting is not addressed by leaving .link files out of the initramfs.  Surely users can use the ip command to do the rename but then was was the point of having the .link files around if they cannot be used to control things they purport to control?

You mentioned the "not to override user choices again and again"; I think it's quite hard to determine whether the first .link files that udev processes are actually the users choice.  It certainly feels quite hard to enact the users actual choice in these scenarios.  Why is it OK to allow the user to update there .network files with different configuration and restart Networkd to have that apply, but changing the interface name when it is down is "overriding the users choice" ?

**Comment by daxtens** [comment] 2018-05-22 02:01
Would a NamePolicy that allows link files to override previously set names be acceptable?

**Comment by mmjo** [comment] 2018-05-24 11:52
Things seem to work when i change the NamePolicy in the initrd file /lib/systemd/network/99-default.link to
`NamePolicy=kernel`

Leaving out the other NamePolicy-options, prevents renaming in the initrd fase.
Which allows later renames from .link files/netplan.

**Comment by raharper** [comment] 2018-05-24 13:46
We only need to allow interfaces which have requested a rename via .link files to be renamed.  Changing the default policy means all interfaces will have kernel names rather than just affecting the interface that was requested to have a specific name.

**Comment by mmjo** [comment] 2018-05-24 14:08
Yes, but this NamePolicy=kernel setting is only to be changed in the initrd.
Then, in the normal boot fase, interface renames with e.g. netplan's set-name seems to work fine.
The original NamePolicy is still applied.
But not twice, which seems to be a problem.

**Comment by raharper** [comment] 2018-05-24 14:39
IIUC, Ihaving the kernel names in the initramfs means we won't get any renames; then when we mount root, the Namepolicy on disk will apply, but since we've not performed any renames in the initramfs then set-names will work.  That's worth confirming on a system with multiple nics where we set-name only one of the two.

There is still the fundamental question as to why .link renaming is different than any other networkd setting here which can be applied after restarting Networkd.

**Comment by mmjo** [comment] 2018-05-24 15:05
That is also my understanding. 
Although it seems logical, this needs testing indeed.
Unfortunately, i have no systems with two network cards.

I am not sure about the fundamental part. Just that renaming an interface which is already up, is problematic.

**Comment by mmjo** [comment] 2018-05-24 15:13
Possibly useful code snippet, image as on Ubuntu 18.04:
```
## unpack into current directory:
{
	cpio -id
	zcat | cpio -id
} < /boot/initrd.img-4.15.0-22-generic 

## now make mods ... 

## repack:
{
	find kernel | cpio -o -R +0:+0 -H newc
	find . -path ./kernel -prune -o -print | cpio -o -R +0:+0 -H newc | gzip -c
} > /boot/initrd.img
```

**Comment by raharper** [comment] 2018-05-24 15:18
VMs are your friend for multiple nics;  I can confirm the behavior.

Note that we're not looking at renaming any interface that is already up.

**Comment by mmjo** [comment] 2018-05-24 16:21
I see your point. Excluding name changes seems unnecessary policy.
Overriding the user is not so much of a problem: these are likely to be different users.
One is distributor/author of the initrd, the other is the sysadmin writing netplan/.link files.

I am not sure, but the initrd-fase may have an interface up. Could that be problematic?

Though, i think that, even when runtime interface name changes were allowed,
the initrd should have the NamePolicy=kernel fix.

**Comment by xnox** [comment] 2018-05-25 15:55
Imho explicit user configuration of custom interface names should be honoured.
Imho declarative specification of a custom interface name, should trump a non-declarative one.
Thus explicit names specified in the declarative .link files should be always applied.

**Comment by msekletar** [comment] 2018-08-09 13:10
I agree with @xnox. I see absolutely no reason to disregard the explicit user configuration. The current behavior is just confusing since all options from the link file are applied except Name.

Also, I don't understand what problem was this code trying to fix, to begin with.

**Comment by doka-ua** [comment] 2018-08-22 08:04
Dear colleagues,

I'm facing a different behavior with renaming interfaces: with net.ifnames=0 biosdevname=0 in GRUB command-line, changing the /etc/systemd/network's ".link" file (Match MACAddress=, Link Name=wan1) successfully renames interface upon boot (e.g. eth0 -> wan1):
```
2: wan1: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN group default qlen 1000
    link/ether 96:6b:a8:16:20:66 brd ff:ff:ff:ff:ff:ff
```
but it seems that corresponding .network file (Match Name=wan1, Network ...) is ignored since no IP configuration appears on interface. Just manual "systemctl restart systemd-networkd" (no changes to existing config files) solves the issue with IP-configuration. And interesting is that if I match interface (in .network) not by name but by MAC (as in corresponding .link), no renaming happens, so after reboot it appears with IP configuration but as eth0.

No other changes against standard Ubuntu's 18.04 configuration was applied.

This happens on Ubuntu 18.04 w/ Systemd 237-3ubuntu10.3.

**Comment by yuwata** [comment] 2018-08-22 08:16
@doka-ua I think your issue is already fixed by #8795 which is included in v239.

**Closed as completed** 2018-11-12 17:45 UTC
Labels: udev

**Comment by shixudong2020** [comment] 2021-09-11 05:54
A  question about  https://github.com/systemd/systemd/issues/11436 
my english is poor,I am newbie to udev,and I'm studying udev rules and net_setup_link.
on the surface,
before fix to #9006,if name_assign_type is NET_NAME_USER or NET_NAME_RENAMED, in #11436 lan0 cannot renamed to ens3,
after fix to #9006, in #11436 lan0 can renamed to ens3 again,
after fix to #11436 with keep policy,lan0 cannot renamed to ens3.

my question is about 80-net-setup-link.rules
In 80-net-setup-link.rules,one of RENAME's  conditions is NAME= is unset, after 70-persistent-net.rules,the NAME is set to lan0,so 80-net-setup-link.rules cannot rename lan0 to ens3 again even though without keep policy. Now 80-net-setup-link.rules still can rename lan0 to ens3 again,why?

**Comment by yuwata** [comment] 2021-09-11 06:29
Please provide .link files you use, and also provide any relevant configs e.g. kernel command line option if you specify interface name in it. Also, if you invoke some commands to rename the interface, then also provide them.

Without such information, we have no way to solve your issue.

BTW, here is an upstream bug tracker. Do you really have any issues on interface renaming? Or just asking a question about the logic of interface renaming? If you just ask something, then here is not a good place to do that. Please use mailing list or read documents.

**Comment by yuwata** [comment] 2021-09-11 12:03
Hm? `ATTR{address}==""`?? The interface you want to name `lan0` has no MAC address?? Strange.
I guess the line in /etc/udev/rules.d/70-persistent-net.rules is not applied to the interface.

Please try to check attributes with `udevadm info --attribute-walk /sys/class/net/INTERFACE_NAME`.

**Comment by shixudong2020** [comment] 2021-09-11 12:15
sorry, Under #11436 circumstances,after apply /etc/udev/rules.d/70-persistent-net.rules:
SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="<MAC>", NAME="lan0"
I mean that 70-persistent-net.rules can applied to the interface,so the interface name is renamed to lan0.
but because one of  80-net-setup-link.rules RENAME's conditions is NAME= is unset,and now NAME is set to lan0,
so the interface name should not be renamed  from lan0 to ens3 through 99-default.link.

**Comment by yuwata** [comment] 2021-09-11 12:57
Please try to run `udevadm test /sys/class/net/INTERFACE_NAME`. If the output does not include something like the following, then the your custom rule does not applied.
```
INTERFACENAME: /etc/udev/rules.d/70-persistent-net.rules:99 NAME 'lan0'
```

**Comment by shixudong2020** [comment] 2021-09-11 13:53
what’s u udev version?my version is 241-7~deb10u8,and only include link file line,not include rules file line
That's a digression

Under #11436 circumstances,through 70-persistent-net.rules interface can and have renamed to lan0

my question is about the logic of #11436  interface renaming,
one of 80-net-setup-link.rules RENAME's conditions is NAME= is unset,and now NAME is set to lan0,
so the interface name should not be renamed from lan0 to ens3 through 99-default.link.
Under #11436 circumstances,how through /usr/lib/systemd/network/99-default.link rename interface name from lan0 to ens3?

**Comment by yuwata** [comment] 2021-09-11 14:18
> my question is about the logic of #11436 interface renaming

Logic is simple. `systemd-udevd` renames interfaces with the value of `NAME`.
If the interface is renamed to `ens3`, then the final value of `NAME` is `ens3`, and `lan0` is not assigned to `NAME`.
So, I am asking if your custom rule is certainly applied.

> what’s u udev version?my version is 241-7~deb10u8,and only include link file line,not include rules file line

Gah,,, that's too old for here. Please use `SYSTEMD_LOG_LEVEL=debug udevadm test /sys/class/net/ens3`.

**Comment by shixudong2020** [comment] 2021-09-11 15:13
I changed the true MAC of 70-persistent-net.rules,because 80-net-setup-link.rules RENAME's conditions is NAME= is unset,and 70-persistent-net.rules rename NAME to lan0,so the final name is lan0.I use  SYSTEMD_LOG_LEVEL=debug udevadm test /sys/class/net/lan0. output(I specially customize /etc/systemd/network/99-default.link only remove keep from NamePolicy):
Rules contain 393216 bytes tokens (32768 * 12 bytes), 32129 bytes strings
25726 strings (210823 bytes), 22631 de-duplicated (181790 bytes), 3096 trie nodes used
lan0: NAME 'lan0' /etc/udev/rules.d/70-persistent-net.rules:1
lan0: IMPORT builtin 'net_id' /usr/lib/udev/rules.d/75-net-description.rules:6
Using default interface naming scheme 'v240'.
lan0: IMPORT builtin 'hwdb' /usr/lib/udev/rules.d/75-net-description.rules:12
lan0: RUN 'ifupdown-hotplug' /usr/lib/udev/rules.d/80-ifupdown.rules:5
lan0: IMPORT builtin 'path_id' /usr/lib/udev/rules.d/80-net-setup-link.rules:5
lan0: IMPORT builtin 'net_setup_link' /usr/lib/udev/rules.d/80-net-setup-link.rules:9
Config file /etc/systemd/network/99-default.link applies to device lan0
link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
link_config: could not set ethtool features for lan0
Could not set offload features of lan0: Operation not permitted
lan0: Device has name_assign_type=4
lan0: Policy *path* yields "enp0s3".
lan0: RUN '/lib/systemd/systemd-sysctl --prefix=/net/ipv4/conf/$name --prefix=/net/ipv4/neigh/$name --prefix=/net/ipv6/conf/$name --prefix=/net/ipv6/neigh/$name' /usr/lib/udev/rules.d/99-systemd.rules:60
lan0: Failed to update tags under /run/udev/tag/, ignoring: Operation not permitted
lan0: Failed to update database under /run/udev/data/, ignoring: Permission denied
DEVPATH=/devices/pci0000:00/0000:00:03.0/net/lan0
INTERFACE=lan0
IFINDEX=2
ACTION=add
SUBSYSTEM=net
ID_NET_NAMING_SCHEME=v240
ID_NET_NAME_MAC=enx08002703e267
ID_OUI_FROM_DATABASE=PCS Systemtechnik GmbH
ID_NET_NAME_PATH=enp0s3
ID_BUS=pci
ID_VENDOR_ID=0x8086
ID_MODEL_ID=0x100e
ID_PCI_CLASS_FROM_DATABASE=Network controller
ID_PCI_SUBCLASS_FROM_DATABASE=Ethernet controller
ID_VENDOR_FROM_DATABASE=Intel Corporation
ID_MODEL_FROM_DATABASE=82540EM Gigabit Ethernet Controller (PRO/1000 MT Desktop Adapter)
ID_MM_CANDIDATE=1
ID_PATH=pci-0000:00:03.0
ID_PATH_TAG=pci-0000_00_03_0
ID_NET_DRIVER=e1000
ID_NET_LINK_FILE=/etc/systemd/network/99-default.link
ID_NET_NAME=enp0s3
TAGS=:systemd:
SYSTEMD_ALIAS=/sys/subsystem/net/devices/lan0
USEC_INITIALIZED=3706978
run: 'ifupdown-hotplug'
run: '/lib/systemd/systemd-sysctl --prefix=/net/ipv4/conf/lan0 --prefix=/net/ipv4/neigh/lan0 --prefix=/net/ipv6/conf/lan0 --prefix=/net/ipv6/neigh/lan0'
Unload module index
Unloaded link configuration context.

**Comment by yuwata** [comment] 2021-09-12 00:46
Now, I am confused about what you expect. Which name `lan0` or `enp0s3` do you expect??

Again, the logic is simple:
1. udevd just renames interfaces with the value specified in `NAME`.
2. as you already said, 80-net-setup-link.rules does not override `NAME` if it is already set.

If you expect the interface is renamed to `enp0s3`,  just drop your custom rules file `/etc/udev/rules.d/70-persistent-net.rules`.

If you expect `lan0`, then it seems your custom rules file seems to work.

=====
As I already said, here is an UPSTREAM bug tracker. But you use slightly old systemd (v241). Please do not ask any questions like this here any more, but please use our mailing list (though, I do not subscribe the list), or even asking to my personal Twitter account may be also ok. And only when if you find any issues in recent releases (currently v248 and v249), then file that in a new issue page.

This is the final message here I reply to you.
