### ISSUE TITLE
restart=always fails when a dependency breaks

### ISSUE THREAD

**Issue by smurfix** [systemd/systemd#16745] opened 2020-08-16 12:07 UTC
**systemd version the issue has been seen with**
> 246

**Used distribution**
 > Debian testing

**Expected behaviour you didn't see**
 > Service A depends on (and directly uses) Service B and has `Restart=always`. Service B dies, A terminates. A is restarted as soon as B comes back.

**Unexpected behaviour you saw**
 > Service A is not restarted.
 > 
 > I noticed this after a month :-( so unfortunately I don't have detailed logs.

**Steps to reproduce the problem**
> I don't have a "simple" test case but could probably build one; in my case B is a TCP server (not using socket activation) which A connects to.

**Comment by poettering** [comment] 2020-08-28 15:38
Well, this would be a new feature, i.e. Restart=always only is about failures of the unit itself, it has no effect anymore once a service is fully down because its deps are gone. And I am not sure this should really change...

I figure what you are looking for is an "invariant" definition, i.e. where some services are declared to always have to be up, and we'll continiously do whatever is necessary to achieve that, i.e. whenever we can we'd start A in your case.

I think an idea for such invariants makes a lot of sense. This is being tracked in #4263 though as an RFE, I'll thus close this one as duplicate of that.

**Closed as completed by poettering** 2020-08-28 15:38 UTC
Labels: RFE 🎁, pid1
