### ISSUE TITLE
systemd resolve need DNS OVER HTTPS support

### ISSUE THREAD

**Issue by olumolu** [systemd/systemd#32006] opened 2024-03-28 19:38 UTC
### Component

systemd-resolved

### Is your feature request related to a problem? Please describe

Support for dns over https in systemd resolved

### Describe alternatives you've considered

Using doT for dns but this feature is really lacking in linux as a whole i find some workaround doh client but don't know reliable this is.

**Comment by mrc0mmand** [comment] 2024-03-28 19:40
Duplicate of https://github.com/systemd/systemd/issues/8639.

**Closed as not planned by mrc0mmand** 2024-03-28 19:40 UTC
Labels: resolve, duplicate
