### ISSUE TITLE
systemd user process segmentation fault

### ISSUE THREAD

**Issue by viktorjk** [systemd/systemd#17759] opened 2020-11-27 22:56 UTC
Distribution: Arch Linux (with testing repositories enabled)
systemd version: 247-1-arch
kernel: 5.9.11-arch1-1
CPU architecture: x86-64

With version 247 my user session (Gnome Wayland) is sometimes killed because of a segmentation fault in the systemd user process (if I understand correctly what's going on). This seems to happen when I click on an item in the top panel, but I can't reproduce it reliably. However I got several core dumps.

Here is the info for the last core dump with a newly created user account:
PID: 760 (systemd)
UID: 1002 (systemdsegfault)
GID: 1002 (systemdsegfault)
Signal: 11 (SEGV)
Timestamp: Fri 2020-11-27 22:58:34 CET (21min ago)
Command Line: /usr/lib/systemd/systemd --user
Executable: /usr/lib/systemd/systemd
Control Group: /user.slice/user-1002.slice/user@1002.service/init.scope
Unit: user@1002.service
User Unit: init.scope
Slice: user-1002.slice
Owner UID: 1002 (systemdsegfault)
Boot ID: f9324464018e466e9ebffe5d3412e2b2
Machine ID: b8d38fc5d6ee453c982979f8bd144c0c
Hostname: hawking
Storage: /var/lib/systemd/coredump/core.systemd.1002.f9324464018e466e9ebffe5d3412e2b2.760.1606514314000000.zst
Message: Process 760 (systemd) of user 1002 dumped core.
                
Stack trace of thread 760:
#0  0x000000746c756166 n/a (n/a + 0x0)
#1  0xf8badf3cab856818 n/a (n/a + 0x0)

The stack traces of some of the other core dumps have a bit more information, but I am just a user and don't understand them. Attached is the core dump created with the test user account (info above) as it shouldn't contain anything sensitive.

[core.systemd.1002.f9324464018e466e9ebffe5d3412e2b2.760.1606514314000000.gz](https://github.com/systemd/systemd/files/5609775/core.systemd.1002.f9324464018e466e9ebffe5d3412e2b2.760.1606514314000000.gz)

**Comment by keszybz** [comment] 2020-11-28 11:48
Please install debug symbols and provide a traceback with symbols resolved. We're not arch developers and we can't do anything with this information. Nevertheless, it seems that the backtrace is garbled, so more steps except installing debug symbols might be needed.

**Comment by terencode** [comment] 2020-11-28 17:21
Might be related to #17758

**Comment by viktorjk** [comment] 2020-11-29 11:10
Sorry for not giving you the appropriate information earlier. Here is another segfault:
```
           PID: 755 (systemd)
           UID: 1002 (systemdsegfault)
           GID: 1002 (systemdsegfault)
        Signal: 11 (SEGV)
     Timestamp: Sun 2020-11-29 11:19:59 CET (33min ago)
  Command Line: /usr/lib/systemd/systemd --user
    Executable: /usr/lib/systemd/systemd
 Control Group: /user.slice/user-1002.slice/user@1002.service/init.scope
          Unit: user@1002.service
     User Unit: init.scope
         Slice: user-1002.slice
     Owner UID: 1002 (systemdsegfault)
       Boot ID: 6d80620fd6b34e68a17aac5977949412
    Machine ID: b8d38fc5d6ee453c982979f8bd144c0c
      Hostname: hawking
       Storage: /var/lib/systemd/coredump/core.systemd.1002.6d80620fd6b34e68a17aac5977949412.755.1606645199000000.zst
       Message: Process 755 (systemd) of user 1002 dumped core.
                
                Stack trace of thread 755:
                #0  0x000055a037e5a255 manager_invoke_sigchld_event (systemd + 0x72255)
                #1  0x000055a037e5a6b7 manager_dispatch_sigchld (systemd + 0x726b7)
                #2  0x00007f588f29430a source_dispatch (libsystemd-shared-247.so + 0x1b530a)
                #3  0x00007f588f297c7b sd_event_dispatch (libsystemd-shared-247.so + 0x1b8c7b)
                #4  0x00007f588f2988d1 sd_event_run (libsystemd-shared-247.so + 0x1b98d1)
                #5  0x000055a037e5ef33 manager_loop (systemd + 0x76f33)
                #6  0x000055a037e1f208 main (systemd + 0x37208)
                #7  0x00007f588ee38152 __libc_start_main (libc.so.6 + 0x28152)
                #8  0x000055a037e2040e _start (systemd + 0x3840e)
```
Here is its full backtrace:
```
#0  0x000055a037e5a255 in manager_invoke_sigchld_event (m=<optimized out>, u=0x55a039bcdcf0, si=0x7ffe8717f800) at ../systemd-stable/src/core/manager.c:2512
        __PRETTY_FUNCTION__ = "manager_invoke_sigchld_event"
        __func__ = "manager_invoke_sigchld_event"
#1  0x000055a037e5a6b7 in manager_dispatch_sigchld (source=<optimized out>, userdata=0x55a039ae3a80) at ../systemd-stable/src/core/manager.c:2589
        u1 = 0x55a039b5fb80
        array = <optimized out>
        i = <optimized out>
        array_copy = 0x0
        name = 0x55a039bc6530 "caja"
        u2 = 0x55a039bcdcf0
        m = 0x55a039ae3a80
        si = {si_signo = 17, si_errno = 0, si_code = 1, __pad0 = 0, _sifields = {_pad = {1254, 1002, 0 <repeats 26 times>}, _kill = {si_pid = 1254, si_uid = 1002}, _timer = {
              si_tid = 1254, si_overrun = 1002, si_sigval = {sival_int = 0, sival_ptr = 0x0}}, _rt = {si_pid = 1254, si_uid = 1002, si_sigval = {sival_int = 0, sival_ptr = 0x0}}, 
            _sigchld = {si_pid = 1254, si_uid = 1002, si_status = 0, si_utime = 0, si_stime = 0}, _sigfault = {si_addr = 0x3ea000004e6, si_addr_lsb = 0, _bounds = {_addr_bnd = {
                  _lower = 0x0, _upper = 0x0}, _pkey = 0}}, _sigpoll = {si_band = 4303557231846, si_fd = 0}, _sigsys = {_call_addr = 0x3ea000004e6, _syscall = 0, _arch = 0}}}
        r = <optimized out>
        __PRETTY_FUNCTION__ = "manager_dispatch_sigchld"
        __func__ = "manager_dispatch_sigchld"
#2  0x00007f588f29430a in source_dispatch (s=0x55a039ae4cb0) at ../systemd-stable/src/libsystemd/sd-event/sd-event.c:3278
        saved_event = 0x55a039ae2ff0
        saved_type = SOURCE_DEFER
        r = <optimized out>
        __PRETTY_FUNCTION__ = "source_dispatch"
        __func__ = "source_dispatch"
#3  0x00007f588f297c7b in sd_event_dispatch (e=e@entry=0x55a039ae2ff0) at ../systemd-stable/src/libsystemd/sd-event/sd-event.c:3689
        ref = <optimized out>
        p = <optimized out>
        r = <optimized out>
        __PRETTY_FUNCTION__ = "sd_event_dispatch"
#4  0x00007f588f2988d1 in sd_event_run (e=0x55a039ae2ff0, timeout=18446744073709551615) at ../systemd-stable/src/libsystemd/sd-event/sd-event.c:3747
        r = 1
        __PRETTY_FUNCTION__ = "sd_event_run"
#5  0x000055a037e5ef33 in manager_loop (m=0x55a039ae3a80) at ../systemd-stable/src/core/manager.c:2976
        wait_usec = <optimized out>
        watchdog_usec = <optimized out>
        rl = {interval = 1000000, burst = 50000, num = 8, begin = 319764658}
        r = <optimized out>
        __PRETTY_FUNCTION__ = "manager_loop"
        __func__ = "manager_loop"
#6  0x000055a037e1f208 in invoke_main_loop (ret_error_message=<optimized out>, ret_switch_root_init=<optimized out>, ret_switch_root_dir=<optimized out>, ret_fds=<optimized out>, 
    ret_shutdown_verb=<optimized out>, ret_retval=<optimized out>, ret_reexecute=<optimized out>, saved_rlimit_memlock=<optimized out>, saved_rlimit_nofile=<optimized out>, 
    m=<optimized out>) at ../systemd-stable/src/core/main.c:1860
        r = <optimized out>
        r = <optimized out>
        __PRETTY_FUNCTION__ = {<optimized out> <repeats 17 times>}
        __func__ = {<optimized out> <repeats 17 times>}
        _level = <optimized out>
        _e = <optimized out>
        _realm = <optimized out>
        saved_log_target = <optimized out>
        saved_log_level = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _realm = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _realm = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _realm = <optimized out>
        _ptr_ = <optimized out>
        _ptr_ = <optimized out>
        _level = <optimized out>
        _e = <optimized out>
        _realm = <optimized out>
        table = {<optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>, <optimized out>}
        _level = <optimized out>
        _e = <optimized out>
        _realm = <optimized out>
#7  main (argc=<optimized out>, argv=0x7ffe8717fcc8) at ../systemd-stable/src/core/main.c:2861
        initrd_timestamp = {realtime = <optimized out>, monotonic = <optimized out>}
        userspace_timestamp = {realtime = 1606644953990124, monotonic = 74311848}
        kernel_timestamp = {realtime = 0, monotonic = 0}
        security_start_timestamp = {realtime = 0, monotonic = 0}
        security_finish_timestamp = {realtime = 0, monotonic = 0}
        saved_rlimit_nofile = {rlim_cur = 1024, rlim_max = 524288}
        saved_rlimit_memlock = {rlim_cur = 65536, rlim_max = 65536}
        skip_setup = <optimized out>
        loaded_policy = false
        queue_default_job = true
        first_boot = false
        reexecute = false
        switch_root_dir = 0x0
        switch_root_init = 0x0
        before_startup = 74313507
        after_startup = <optimized out>
        timespan = "\240\372\374\216X\177\000\000 \003\375\216X\177\000\000`\370\374\216X\177\000\000\340\367\374\216X\177\000\000\000\000\000\000\000\000\000\000\340\377\374\216X\177\000\000@\000\375\216X\177\000\000\300\000\375\216X\177\000"
        shutdown_verb = 0x0
        error_message = 0x0
        r = <optimized out>
        retval = 1
        m = 0x55a039ae3a80
        fds = 0x0
        finish = <optimized out>
        systemd = "systemd"
        __func__ = "main"
        __PRETTY_FUNCTION__ = "main"
```
"caja" (a fork of Gnome 2 Nautilus from the MATE desktop environment) is mentioned here, I use it as my default file manager. This is the journal entry just before the segfault:
```
Nov 29 11:19:59 hawking systemd[755]: app-gnome-caja\x2dfolder\x2dhandler-1254.scope: Succeeded.
```
Please tell me if you still need more information.

**Comment by viktorjk** [comment] 2020-11-29 12:21
I am now running systemd 247 with commit 428a9f6f1d0396b9eacde2b38d667cbe3f15eb55 reverted because of https://github.com/systemd/systemd/issues/17768#issuecomment-735300622. So far it seems that the issue is gone.

**Comment by mbiebl** [comment] 2020-11-29 17:41
> I am now running systemd 247 with commit [428a9f6](https://github.com/systemd/systemd/commit/428a9f6f1d0396b9eacde2b38d667cbe3f15eb55) reverted because of [#17768 (comment)](https://github.com/systemd/systemd/issues/17768#issuecomment-735300622). So far it seems that the issue is gone.

thanks for confirming

**Comment by keszybz** [comment] 2020-12-01 09:36
Duplicate of #17758.

**Closed as completed by keszybz** 2020-12-01 09:36 UTC
Labels: needs-reporter-feedback ❓, downstream/arch
