### ISSUE TITLE
Drop-in config not recognized when .d directory for a unit is a symlink

### ISSUE THREAD

**Issue by mrvantage** [systemd/systemd#21979] opened 2022-01-03 13:21 UTC
**systemd version the issue has been seen with**
 > systemd 250 (250-5-manjaro)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY +P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified

**Used distribution**
 > Manjaro (stable branch)

**Linux kernel version used** (`uname -a`)

 > `Linux host 5.15.12-1-MANJARO #1 SMP PREEMPT Wed Dec 29 18:08:07 UTC 2021 x86_64 GNU/Linux`

**CPU architecture issue was seen on**
 > x86_64

**Expected behaviour you didn't see**
 > Drop-in config not loaded when the `.d` directory is a symlink in the `--user` context

**Unexpected behaviour you saw**
 > n/a

**Steps to reproduce the problem**
 > 
```
echo '[Unit]
Description=Drop-in test

[Service]
ExecStart=/usr/bin/sleep ${TIME}

[Install]
WantedBy=default.target' > ~/.config/systemd/user/test-drop-in.service

mkdir ~/test-drop-in.service.d

echo '[Service]
Environment=TIME=3600' > ~/test-drop-in.service.d/time.conf

ln -s ~/test-drop-in.service.d ~/.config/systemd/user/test-drop-in.service.d

systemctl --user daemon-reload

systemctl --user status test-drop-in.service
```

No drop-in config is loaded:
```
○ test-drop-in.service - Drop-in test
     Loaded: loaded (/home/user/.config/systemd/user/test-drop-in.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
```

**Additional program output to the terminal or log subsystem illustrating the issue**

```text
…
```

**Comment by mrc0mmand** [comment] 2022-01-03 13:27
Duplicate of #21920 and #21962. Already fixed in #21925.

**Closed as completed by mrc0mmand** 2022-01-03 13:27 UTC
Labels: duplicate
