### ISSUE TITLE
Systemd lost udev "device" units during reload/reexec

### ISSUE THREAD

**Issue by alxchk** [systemd/systemd#16905] opened 2020-08-29 19:58 UTC
**systemd version the issue has been seen with**
> 246

```
tachi ~ # grep 8fd9f80f-4e02-4290-a67c-f5089924b429  /etc/udev/rules.d/99-external-storage.rules
ACTION=="add", ENV{ID_FS_UUID}=="8fd9f80f-4e02-4290-a67c-f5089924b429", SYMLINK+="travel", PROGRAM="/bin/systemd-escape -u $env{ID_FS_UUID}", ENV{SYSTEMD_ALIAS}="/sys/virtual/estorage/%c", ENV{SYSTEMD_WANTS}="external-ssd-storage@$env{ID_FS_UUID}", TAG+="systemd", TAG+="uaccess"
```

```
tachi ~ # systemctl status sys-virtual-estorage-8fd9f80f-4e02-4290-a67c-f5089924b429.device
● sys-virtual-estorage-8fd9f80f-4e02-4290-a67c-f5089924b429.device - PSSD_T7
     Loaded: loaded
     Active: active (plugged) since Sat 2020-08-29 22:38:39 EEST; 16min ago
     Device: /sys/devices/pci0000:00/0000:00:1c.4/0000:02:00.0/0000:03:02.0/0000:3a:00.0/usb4/4-1/4-1.2/4-1.2.3/4-1.2.3:1.0/host1/target1:0:0/1:0:0:0/block/sda
tachi ~ # ls -ld /sys/devices/pci0000:00/0000:00:1c.4/0000:02:00.0/0000:03:02.0/0000:3a:00.0/usb4/4-1/4-1.2/4-1.2.3/4-1.2.3:1.0/host1/target1:0:0/1:0:0:0/block/sda
drwxr-xr-x 8 root root 0 Aug 29 22:38 /sys/devices/pci0000:00/0000:00:1c.4/0000:02:00.0/0000:03:02.0/0000:3a:00.0/usb4/4-1/4-1.2/4-1.2.3/4-1.2.3:1.0/host1/target1:0:0/1:0:0:0/block/sda
tachi ~ # systemctl daemon-reload
tachi ~ # ls -ld /sys/devices/pci0000:00/0000:00:1c.4/0000:02:00.0/0000:03:02.0/0000:3a:00.0/usb4/4-1/4-1.2/4-1.2.3/4-1.2.3:1.0/host1/target1:0:0/1:0:0:0/block/sda
drwxr-xr-x 8 root root 0 Aug 29 22:38 /sys/devices/pci0000:00/0000:00:1c.4/0000:02:00.0/0000:03:02.0/0000:3a:00.0/usb4/4-1/4-1.2/4-1.2.3/4-1.2.3:1.0/host1/target1:0:0/1:0:0:0/block/sda
tachi ~ # systemctl status sys-virtual-estorage-8fd9f80f-4e02-4290-a67c-f5089924b429.device
● sys-virtual-estorage-8fd9f80f-4e02-4290-a67c-f5089924b429.device - /sys/virtual/estorage/8fd9f80f/4e02/4290/a67c/f5089924b429
     Loaded: loaded
     Active: inactive (dead)
tachi ~ 
```

**Comment by fbuihuu** [comment] 2020-08-31 08:02
Well the description of the issue is rather short so I can't tell for sure but it might be a duplicate of issue #12953

**Comment by alxchk** [comment] 2020-08-31 08:22
> is rather short

I believe all is there.
Device units, which are "created" by udev's tag TAG+="systemd" does not survive reload/reexec.

Efficiently this means that unit state becomes "dead" after reload/reexec. looks similar to #12953.

**Comment by poettering** [comment] 2020-08-31 13:57
Your udev rules is borked. Use ACTION!="remove" as condition. If anyone issues "udevadm trigger" your props will otherwise disappear from the device, and systemd will then not see them as soon as you also issue a PID 1 reload.

I figure the "bind"/"unbind" mess  also plays into this, ie. #16853/#7587: your usb device probably sees "bind" quickly after being plugged in, and that is guaranteed to drop the props of your rule again.

**Closed as completed by poettering** 2020-08-31 13:57 UTC
