### ISSUE TITLE
networkd-wait-online errors when booting default mkosi image

### ISSUE THREAD

**Issue by keszybz** [systemd/systemd#27683] opened 2023-05-18 14:44 UTC
### systemd version the issue has been seen with

git

### CPU architectures issue was seen on

None

### Additional program output to the terminal or log subsystem illustrating the issue

```
$ journalctl -b --grep 'networkd'|cat
May 18 16:05:37 fedora systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/systemd-networkd.socket
May 18 16:05:37 fedora systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/systemd-networkd-wait-online@.service
May 18 16:05:37 fedora systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/systemd-networkd-wait-online.service
May 18 16:05:37 fedora systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/systemd-networkd.service
May 18 16:05:37 fedora systemd[1]: Unit systemd-networkd.service has alias dbus-org.freedesktop.network1.service.
May 18 16:05:37 fedora systemd[1]: systemd-networkd.service: Failed to parse system call, ignoring: futex_waitv
May 18 16:05:37 fedora systemd[1]: /usr/lib/systemd/system/systemd-networkd.service:50: Failed to parse system call, ignoring: futex_waitv
May 18 16:05:37 fedora systemd[1]: /usr/lib/systemd/system/systemd-networkd.service:50: Failed to parse system call, ignoring: set_mempolicy_home_node
May 18 16:05:37 fedora systemd[1]: systemd-networkd.socket: Installed new job systemd-networkd.socket/start as 76
May 18 16:05:37 fedora systemd[1]: systemd-networkd.socket: ConditionCapability=CAP_NET_ADMIN succeeded.
May 18 16:05:37 fedora systemd[1]: systemd-networkd.socket: Changed dead -> listening
May 18 16:05:37 fedora systemd[1]: systemd-networkd.socket: Job 76 systemd-networkd.socket/start finished, result=done
May 18 16:05:37 fedora systemd[1]: Listening on systemd-networkd.socket.
May 18 16:05:38 fedora systemd[1]: systemd-networkd.socket: Incoming traffic
May 18 16:05:38 fedora systemd[1]: systemd-networkd.service: Trying to enqueue job systemd-networkd.service/start/replace
May 18 16:05:38 fedora systemd[1]: systemd-networkd.service: Installed new job systemd-networkd.service/start as 106
May 18 16:05:38 fedora systemd[1]: systemd-networkd.service: Enqueued job systemd-networkd.service/start as 106
May 18 16:05:38 fedora systemd[1]: systemd-networkd.socket: Changed listening -> running
May 18 16:05:38 fedora systemd[1]: network.target: starting held back, waiting for: systemd-networkd.service
May 18 16:05:38 fedora systemd[1]: systemd-networkd.service: ConditionCapability=CAP_NET_ADMIN succeeded.
May 18 16:05:38 fedora systemd[1]: systemd-networkd.service: Will spawn child (service_enter_start): /usr/lib/systemd/systemd-networkd
May 18 16:05:38 fedora systemd[1]: systemd-networkd.service: Passing 1 fds to service
May 18 16:05:38 fedora systemd[1]: systemd-networkd.service: About to execute: /usr/lib/systemd/systemd-networkd
May 18 16:05:38 fedora systemd[1]: systemd-networkd.service: Forked /usr/lib/systemd/systemd-networkd as 288
May 18 16:05:38 fedora systemd[1]: systemd-networkd.service: Changed dead -> start
May 18 16:05:38 fedora systemd[1]: Starting systemd-networkd.service...
May 18 16:05:38 fedora systemd[1]: systemd-networkd.service: User lookup succeeded: uid=192 gid=192
May 18 16:05:38 fedora (netw[288]: Followed source symlinks /run/systemd/propagate/systemd-networkd.service → /run/systemd/propagate/systemd-networkd.service.
May 18 16:05:38 fedora (netw[288]: Bind-mounting /run/systemd/propagate/systemd-networkd.service on /run/systemd/mount-rootfs/run/systemd/incoming (MS_BIND "")...
May 18 16:05:38 fedora (netw[288]: Successfully mounted /run/systemd/propagate/systemd-networkd.service to /run/systemd/mount-rootfs/run/systemd/incoming
May 18 16:05:38 fedora (netw[288]: Applying namespace mount on /run/systemd/mount-rootfs/sys/fs/cgroup/system.slice/systemd-networkd.service/memory.pressure
May 18 16:05:38 fedora (netw[288]: Bind-mounting /run/systemd/mount-rootfs/sys/fs/cgroup/system.slice/systemd-networkd.service/memory.pressure on /run/systemd/mount-rootfs/sys/fs/cgroup/system.slice/systemd-networkd.service/memory.pressure (MS_BIND|MS_REC "")...
May 18 16:05:38 fedora (netw[288]: Successfully mounted /run/systemd/mount-rootfs/sys/fs/cgroup/system.slice/systemd-networkd.service/memory.pressure to /run/systemd/mount-rootfs/sys/fs/cgroup/system.slice/systemd-networkd.service/memory.pressure
May 18 16:05:38 fedora (netw[288]: Not remounting /run/systemd/mount-rootfs/sys/fs/cgroup/system.slice/systemd-networkd.service/memory.pressure deny-listed by /run/systemd/mount-rootfs/sys, called for /run/systemd/mount-rootfs/
May 18 16:05:38 fedora (netw[288]: Not remounting /run/systemd/mount-rootfs/sys/fs/cgroup/system.slice/systemd-networkd.service/memory.pressure deny-listed by /run/systemd/mount-rootfs/sys, called for /run/systemd/mount-rootfs/
May 18 16:05:38 fedora (netw[288]: Not remounting /run/systemd/mount-rootfs/sys/fs/cgroup/system.slice/systemd-networkd.service/memory.pressure deny-listed by /run/systemd/mount-rootfs/sys/fs/cgroup/system.slice/systemd-networkd.service/memory.pressure, called for /run/systemd/mount-rootfs/sys/fs/cgroup
May 18 16:05:38 fedora (netw[288]: Not remounting /run/systemd/mount-rootfs/sys/fs/cgroup/system.slice/systemd-networkd.service/memory.pressure deny-listed by /run/systemd/mount-rootfs/sys/fs/cgroup/system.slice/systemd-networkd.service/memory.pressure, called for /run/systemd/mount-rootfs/sys/fs/cgroup
May 18 16:05:38 fedora (netw[288]: Not remounting /run/systemd/mount-rootfs/sys/fs/cgroup/system.slice/systemd-networkd.service/memory.pressure deny-listed by /run/systemd/mount-rootfs/sys/fs/cgroup, called for /run/systemd/mount-rootfs/sys
May 18 16:05:38 fedora (netw[288]: Not remounting /run/systemd/mount-rootfs/sys/fs/cgroup/system.slice/systemd-networkd.service/memory.pressure deny-listed by /run/systemd/mount-rootfs/sys/fs/cgroup, called for /run/systemd/mount-rootfs/sys
May 18 16:05:38 fedora (netw[288]: systemd-networkd.service: Kernel doesn't support PR_SET_MDWE: falling back to seccomp
May 18 16:05:38 fedora (netw[288]: systemd-networkd.service: Executing: /usr/lib/systemd/systemd-networkd
May 18 16:05:38 fedora systemd[1]: systemd-networkd.service: Got notification message from PID 288 (WATCHDOG=1)
May 18 16:05:38 fedora systemd-networkd[288]: Running in initrd, keep DHCPv4 addresses on stopping networkd by default.
May 18 16:05:38 fedora audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=systemd-networkd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
May 18 16:05:38 fedora systemd[1]: systemd-networkd.service: Got notification message from PID 288 (READY=1, STATUS=Processing requests...)
May 18 16:05:38 fedora systemd[1]: systemd-networkd.service: Changed start -> running
May 18 16:05:38 fedora systemd[1]: systemd-networkd.service: Job 106 systemd-networkd.service/start finished, result=done
May 18 16:05:38 fedora systemd[1]: Started systemd-networkd.service.
May 18 16:05:38 fedora systemd[1]: systemd-networkd.service: Watching D-Bus name 'org.freedesktop.network1'.
May 18 16:05:38 fedora systemd[1]: systemd-networkd.service: D-Bus name org.freedesktop.network1 now owned by :1.2
May 18 16:05:38 fedora systemd[1]: systemd-networkd.socket: Installed new job systemd-networkd.socket/stop as 319
May 18 16:05:38 fedora systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2dnetworkd_2esocket interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=58 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 18 16:05:38 fedora systemd[1]: Sent message type=signal sender=org.freedesktop.systemd1 destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2dnetworkd_2esocket interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=59 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 18 16:05:38 fedora systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2dnetworkd_2esocket interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=173 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 18 16:05:38 fedora systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2dnetworkd_2esocket interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=174 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 18 16:05:38 fedora systemd[1]: systemd-networkd.socket: Deactivated successfully.
May 18 16:05:38 fedora systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2dnetworkd_2esocket interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=437 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 18 16:05:38 fedora systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2dnetworkd_2esocket interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=438 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 18 16:05:38 fedora systemd[1]: systemd-networkd.socket: Changed running -> dead
May 18 16:05:38 fedora systemd[1]: systemd-networkd.socket: bpf-lsm: Failed to delete cgroup entry from LSM BPF map: No such file or directory
May 18 16:05:38 fedora systemd[1]: systemd-networkd.socket: Job 319 systemd-networkd.socket/stop finished, result=done
May 18 16:05:38 fedora systemd[1]: Closed systemd-networkd.socket.
May 18 16:05:38 fedora systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2dnetworkd_2esocket interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=439 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 18 16:05:38 fedora systemd[1]: Sent message type=signal sender=n/a destination=n/a path=/org/freedesktop/systemd1/unit/systemd_2dnetworkd_2esocket interface=org.freedesktop.DBus.Properties member=PropertiesChanged cookie=440 reply_cookie=0 signature=sa{sv}as error-name=n/a error-message=n/a
May 18 16:05:38 fedora systemd[1]: Cannot stat /run/credentials/systemd-networkd.socket: No such file or directory
May 18 16:05:39 fedora systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/systemd-networkd-wait-online.service
May 18 16:05:39 fedora systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/systemd-networkd-wait-online@.service
May 18 16:05:39 fedora systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/systemd-networkd.service
May 18 16:05:39 fedora systemd[1]: unit_file_build_name_map: normal unit file: /usr/lib/systemd/system/systemd-networkd.socket
May 18 16:05:39 fedora systemd[1]: Unit systemd-networkd.service has alias dbus-org.freedesktop.network1.service.
May 18 16:05:39 fedora systemd[1]: systemd-networkd.service: Failed to parse system call, ignoring: futex_waitv
May 18 16:05:39 fedora systemd[1]: /usr/lib/systemd/system/systemd-networkd.service:50: Failed to parse system call, ignoring: futex_waitv
May 18 16:05:39 fedora systemd[1]: /usr/lib/systemd/system/systemd-networkd.service:50: Failed to parse system call, ignoring: set_mempolicy_home_node
May 18 16:05:39 fedora systemd[1]: systemd-networkd.service: Changed dead -> running
May 18 16:05:39 fedora systemd[1]: systemd-networkd.service: Child 288 belongs to systemd-networkd.service.
May 18 16:05:39 fedora systemd[1]: systemd-networkd.service: Main process exited, code=exited, status=0/SUCCESS (success)
May 18 16:05:39 fedora systemd[1]: systemd-networkd.service: Deactivated successfully.
May 18 16:05:39 fedora systemd[1]: systemd-networkd.service: Service will not restart (restart setting)
May 18 16:05:39 fedora systemd[1]: systemd-networkd.service: Changed stop-sigterm -> dead
May 18 16:05:39 fedora systemd[1]: systemd-networkd.service: bpf-lsm: Failed to delete cgroup entry from LSM BPF map: No such file or directory
May 18 16:05:39 fedora systemd[1]: systemd-networkd.service: Consumed 21ms CPU time.
May 18 16:05:39 fedora systemd[1]: Cannot stat /run/credentials/systemd-networkd.service: No such file or directory
May 18 16:05:39 fedora systemd[1]: systemd-networkd.service: Releasing resources...
May 18 16:05:39 fedora systemd[1]: systemd-networkd.service: Control group is empty.
May 18 16:05:39 fedora systemd[1]: systemd-networkd.socket: ConditionCapability=CAP_NET_ADMIN succeeded.
May 18 16:05:39 fedora systemd[1]: systemd-networkd.socket: Changed dead -> listening
May 18 16:05:39 fedora systemd[1]: systemd-networkd.socket: Job 472 systemd-networkd.socket/start finished, result=done
May 18 16:05:39 fedora systemd[1]: Listening on systemd-networkd.socket.
May 18 16:05:39 fedora systemd[1]: systemd-networkd-wait-online.service: ConditionCapability=CAP_NET_ADMIN succeeded.
May 18 16:05:39 fedora systemd[1]: systemd-networkd-wait-online.service: Bound to unit systemd-networkd.service, but unit isn't active.
May 18 16:05:39 fedora systemd[1]: systemd-networkd-wait-online.service: Job 506 systemd-networkd-wait-online.service/start finished, result=dependency
May 18 16:05:39 fedora systemd[1]: Dependency failed for systemd-networkd-wait-online.service.
May 18 16:05:39 fedora systemd[1]: systemd-networkd-wait-online.service: Job systemd-networkd-wait-online.service/start failed with result 'dependency'.
May 18 16:05:39 fedora audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=systemd-networkd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
May 18 16:05:39 fedora systemd[1]: systemd-networkd-wait-online.service: Installed new job systemd-networkd-wait-online.service/start as 506
May 18 16:05:39 fedora systemd[1]: systemd-networkd.socket: Installed new job systemd-networkd.socket/start as 472
May 18 16:05:39 fedora systemd[1]: systemd-networkd.service: Got notification message from PID 288 (STOPPING=1, STATUS=Shutting down...)
May 18 16:05:39 fedora systemd[1]: systemd-networkd.service: Changed running -> stop-sigterm
May 18 16:05:39 fedora systemd[1]: systemd-networkd.service: Got notification message from PID 288 (EXIT_STATUS=0)
May 18 16:05:40 fedora systemd[1]: systemd-networkd.socket: Incoming traffic
May 18 16:05:40 fedora systemd[1]: systemd-networkd.service: Trying to enqueue job systemd-networkd.service/start/replace
May 18 16:05:40 fedora systemd[1]: systemd-networkd.service: Installed new job systemd-networkd.service/start as 637
May 18 16:05:40 fedora systemd[1]: systemd-networkd.service: Enqueued job systemd-networkd.service/start as 637
May 18 16:05:40 fedora systemd[1]: systemd-networkd.socket: Changed listening -> running
May 18 16:05:40 fedora systemd[1]: systemd-networkd.service: ConditionCapability=CAP_NET_ADMIN succeeded.
May 18 16:05:40 fedora systemd[1]: systemd-networkd.service: Will spawn child (service_enter_start): /usr/lib/systemd/systemd-networkd
May 18 16:05:40 fedora systemd[1]: systemd-networkd.service: Passing 1 fds to service
May 18 16:05:40 fedora systemd[1]: systemd-networkd.service: About to execute: /usr/lib/systemd/systemd-networkd
May 18 16:05:40 fedora systemd[1]: systemd-networkd.service: Forked /usr/lib/systemd/systemd-networkd as 506
May 18 16:05:40 fedora systemd[1]: systemd-networkd.service: Changed dead -> start
May 18 16:05:40 fedora systemd[1]: Starting systemd-networkd.service...
```

I guess this is somehow related to systemd-networkd being stopped at the wrong time:
f0ad3e6b9652fe785245934ff8604cc897d3b8f4, 4340e5b6df241e4883a1e58dc3446ea489a388a9

**Comment by yuwata** [comment] 2023-05-22 04:18
Duplicate of #27718. Closing.
(#27718 is opened later than this, but it already contains much details.)

**Closed as completed by yuwata** 2023-05-22 04:18 UTC
Labels: bug 🐛, network, duplicate, mkosi
