### ISSUE TITLE
systemd-243 breaks Dual Shock 4 with Steam Input

### ISSUE THREAD

**Issue by Vash63** [systemd/systemd#13553] opened 2019-09-13 22:26 UTC
**systemd version the issue has been seen with**
>243

**Used distribution**
 > Arch

**Expected behaviour you didn't see**
 > DS4 controller works normally in game. Test game is Assassin's Creed Odyssey using Steam Input (which emulates an Xbox 360 controller) with Proton & wine virtual desktop enabled.

**Unexpected behaviour you saw**
 > Controller works when in the Steam interface, but upon loading the game it no longer works.

**Steps to reproduce the problem**
Upgrade to systemd 243. Notice controller doesn't work properly. Downgrade to Arch's 242.84-2 package, re-test and controller functionality is restored.

Note: I originally thought this was related to https://github.com/systemd/systemd/pull/13519 - but after applying this same patch to 243 it did not resolve my issue. Also, `/dev/input/by-id` does not look changed between the 242 and 243 for the Steam Controller ID, in both cases the controller files are:
```
usb-Valve_Software_Steam_Controller-event-mouse
usb-Valve_Software_Steam_Controller-mouse
```

**Comment by Oschowa** [comment] 2019-09-13 23:23
I can confirm, that 243 causes issues with controller input in multiple games.
Rise of the Tomb Raider doesn't recognize any controller input, both with Steam Input enabled and disabled. Some other games, like Dark Souls: Remastered, work with Steam Input disabled, but are broken with Steam Input enabled.
Downgrading to systemd 242.84 fixes this.

I was testing on Arch Linux.

**Comment by yuwata** [comment] 2019-09-14 03:43
Please provide the result of `SYSTEMD_LOG_LEVEL=debug udevadm test /sys/class/input/eventX`. Are there any difference between v242 and v243?

**Comment by Oschowa** [comment] 2019-09-14 08:38
With systemd-242:
[DS4-udev.txt](https://github.com/systemd/systemd/files/3612496/DS4-udev.txt)
[virtual-x360-udev.txt](https://github.com/systemd/systemd/files/3612498/virtual-x360-udev.txt)

With systemd-243:
[DS4-udev-243.txt](https://github.com/systemd/systemd/files/3612500/DS4-udev-243.txt)
The eventX file for the virtual x360-pad created by stream input is missing on 243, might be related to #13519 ? I did not apply this to my systemd build yet, but could if it might be useful.

**Comment by yuwata** [comment] 2019-09-14 17:09
@Oschowa Please apply #13519.

**Comment by Oschowa** [comment] 2019-09-14 18:42
I applied #13518, but there was no change to behviour or the debug output posted above.

**Comment by Vash63** [comment] 2019-09-14 20:52
I can verify that I have also tested 243 with the fix from #13519 and the issue was still present for me. Note that Steam is creating a virtual x360 device, I'm not sure if that matters to udev anywhere but this isn't simply the controller alone not working. The DS4 itself works _in native titles_ that support it, but Valve's emulated X360 pad does not work.

**Comment by Plagman** [comment] 2019-09-15 00:20
Hello,

It seems like our udev rules are being broken by systemd 243 and causing these symptoms. This rule isn't having the desired effect anymore:

```
plagman@redcore:~$ cat /usr/lib/udev/rules.d/70-steam-input.rules | grep uinput
KERNEL=="uinput", SUBSYSTEM=="misc", OPTIONS+="static_node=uinput", TAG+="uaccess", OPTIONS+="static_node=uinput"
```

And presumably the others giving direct access to HID PS4 and Switch Pro controllers are also not working anymore.

**Comment by yuwata** [comment] 2019-09-15 06:30
@Plagman Please apply #13500.

**Comment by Oschowa** [comment] 2019-09-15 09:57
I applied #13500 and #13518 onto v243 and it fixes my controller related issues, thanks.

**Comment by yuwata** [comment] 2019-09-15 10:02
@Vash63 How about your case? Does #13500 help your issue? Anyway, please show the result of `SYSTEMD_LOG_LEVEL=debug udevadm test /sys/class/input/eventX`.

**Comment by Vash63** [comment] 2019-09-15 14:10
With both #13500 and #13518 applied it still doesn't seem to work in my case. `/sys/class/input/eventX` has 4 device added with 242.84, but only 3 with 243. It specifically appears that the one numbered event28 in my tests is missing (which is the virtual controller provided by Steam as it's the only one not registered to a bluetooth address).

[242_event25.txt](https://github.com/systemd/systemd/files/3613826/242_event25.txt)
[242_event26.txt](https://github.com/systemd/systemd/files/3613827/242_event26.txt)
[242_event27.txt](https://github.com/systemd/systemd/files/3613828/242_event27.txt)
[242_event28.txt](https://github.com/systemd/systemd/files/3613829/242_event28.txt)
[patched243_event25.txt](https://github.com/systemd/systemd/files/3613830/patched243_event25.txt)
[patched243_event26.txt](https://github.com/systemd/systemd/files/3613831/patched243_event26.txt)
[patched243_event27.txt](https://github.com/systemd/systemd/files/3613832/patched243_event27.txt)

**Comment by yuwata** [comment] 2019-09-15 18:20
@Vash63 Then, please provide the result of 
`SYSTEMD_LOG_LEVEL=debug udevadm test /devices/virtual/input/input34/event28`
Please do not forget to produce debug logs.

**Comment by Vash63** [comment] 2019-09-16 00:55
[242_input34_event28.txt](https://github.com/systemd/systemd/files/3614488/242_input34_event28.txt)

Here you go. This is once again back to 242.84.

**Comment by Oschowa** [comment] 2019-09-16 01:07
I also just encountered broken controller input in Rise of the Tomb Raider again, while the eventX file for the virtual x360 controller, which should have been created by Steam Input, was missing on v243 + the 2 pr's.
I'm at least 99% sure i properly tested this on this version and found it working correctly, so there seems to be a random element to it? Maybe i just messed up my testing and you can disregard what i said earlier...

**Comment by Vash63** [comment] 2019-09-16 14:26
As an added note for anyone else attempting to help test or duplicate this, make sure you are on Linux 5.2 branch or lower. 5.3 added a regression that completely breaks DS4 controllers via Bluetooth.

**Comment by Vash63** [comment] 2019-09-24 21:28
I noticed this bug is still tagged with 'Needs reporter feedback' - is there something I forgot to provide?

**Comment by Vash63** [comment] 2019-11-30 01:00
As of Arch's 243.162 package I can no longer reproduce this even after many attempts to rule out randomness. @Oschowa Are you still able to duplicate it?

**Comment by yuwata** [comment] 2019-12-03 15:05
Let's close this.

**Closed as completed by yuwata** 2019-12-03 15:05 UTC
Labels: udev, regression ⚠️
