### ISSUE TITLE
41 systemd-udevd processes on startup

### ISSUE THREAD

**Issue by wooque** [systemd/systemd#11405] opened 2019-01-12 19:14 UTC
**systemd version the issue has been seen with**
> 240.0-3

**Used distribution**
 > Arch Linux

**Expected behaviour you didn't see**
 > Only one systemd-udevd process on startup

**Unexpected behaviour you saw**
 > 41 systemd-udevd processes on startup, after ~30s they die to 1

**Steps to reproduce the problem**
Boot latest Arch Linux with 240.0-3 and do `ps aux | grep udevd` as soon as OS starts.

**Additional notes**
Everything is fine in 239.370-1. Issue is still present in 240.34-2 from testing repo.

**Comment by yuwata** [comment] 2019-01-12 23:33
Please try to set `children_max=` in udev.conf.
https://www.freedesktop.org/software/systemd/man/udev.conf.html

Note that `udevd` always has a daemon and multiple 'worker' process. So, at least two process are running during device initialization.

**Comment by yuwata** [comment] 2019-01-12 23:34
Hence, this is the intended behavior, and not a bug. Let's close this.

**Closed as completed by yuwata** 2019-01-12 23:34 UTC
Labels: udev, not-a-bug

**Comment by wooque** [comment] 2019-01-13 01:33
@yuwata Ok, but there is still regression in udev, in 239.370-1, device initialization is finished til I reached GUI and could check running processes and with 16 children workers (logs indicate this), but in 240.0-3 initialization is still not done for 30s after GUI startup even there are 40 workers.

**Comment by yuwata** [comment] 2019-01-13 16:16
So, please provide debug logs of udevd.

**Comment by yuwata** [comment] 2019-01-13 22:47
I do not know what the device 'regulatory.0' is. But, 'change' event for the device is triggered many times at the end of device initialization. This is the common behavior in your two logs. So, if the event itself is ok, then the change in the number of workers is intended behavior. The behavior change is done by eca195ec23fb4ed3ece26b55f85c5eefa662e967.

However, unfortunately, there was a bug #10699, and it is fixed by f007824996baa5efdcbd4efdef1e998da26a19be. So, you see the difference of the number of workers at that commit.

So, still I do not think this is a bug. Do you have any problems caused by the change?

**Comment by yuwata** [comment] 2019-01-13 22:58
Or, do you just want to kill unnecessary workers earlier? If so, it can be implemented by making the timeout 3 seconds configurable, though I am not sure such a option is really necessary.

**Comment by wooque** [comment] 2019-01-13 23:58
@yuwata There were some errors in dmesg connected to regulatory.0, I googled and it's something connected to wireless network handling in kernel, I installed crda package (optional dep for kernel, sets the correct wireless channel) and now workers are much quicker to shutdown, I can barely catch them on startup.
