### ISSUE TITLE
systemd-resolve VPNC with multiple DNS Domains not working correctly

### ISSUE THREAD

**Issue by Techinica** [systemd/systemd#8975] opened 2018-05-11 22:38 UTC
**systemd version the issue has been seen with**
> systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid

**Used distribution**
 > Ubuntu 18.04 LTS

**Expected behaviour you didn't see**
 > Link 24 (tun0)
      Current Scopes: DNS
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
         DNS Servers: 192.168.0.1
                      192.168.0.2
          DNS Domain: a.domain
                      b.domain

**Unexpected behaviour you saw**
 > Link 25 (tun0)
      Current Scopes: DNS
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: no
    DNSSEC supported: no
         DNS Servers: 192.168.0.1
                      192.168.0.2
          DNS Domain: a.domain\044b.domain

**Steps to reproduce the problem**

> Connect to a Cisco VPN with the VPNC client on Ubuntu 18.04 that has multiple DNS search domains?

I've found that for whatever reason the file in /run/systemd/resolve/netif is being created with \044 between the domains instead of a space.

> #This is private data. Do not parse.
LLMNR=yes
MDNS=no
SERVERS=192.168.0.1 192.168.0.2
DOMAINS=a.domain\044b.domain

There is also a 'matching' issue in /var/log/syslog

> systemd-resolved[28968]: Failed to add search domain 'a.domain#036b.domain', ignoring: Invalid argument

Neither the search domains or DNS IP's are defined in my NetworkManager connection file. Changing the file in /run/systemd/resolve/netif by swapping the \044 for a space and restarting systemd-resolved with service systemd-resolved restart works until the connection drops and a new file is created.

(a.domain and b.domain swapped, but they're both domains on standard TLDs)

**Comment by poettering** [comment] 2018-05-17 16:46
hmm, so resolved accepts DNS names clients such as NM or vpnc push into it. It appears that the code pushing this into resolved simply concats all names with a space instead pushing them as individual domains. This is hence a bug in NM/vpnc, i.e. the code that pushes it to resolved.

Maybe @xnox knows more?

Either way, the way this looks there's nothing to fix on the systemd side here, we operate on the data pushed to us.

**Comment by xnox** [comment] 2018-05-24 11:58
Heya. I have been poking network-manager code a bit. @Techinica could you please clarify if you use network-manager-vpnc or network-manager-openconnect? Can you poke NetworkManager using e.g. d-feet to try to figure out if NetworkManager has correct domains set for it, or not?

**Comment by Techinica** [comment] 2018-07-05 20:41
@xnox I'm using network-manager-vpnc
`network-manager-vpnc/bionic,now 1.2.4-6 amd64 [installed]
network-manager-vpnc-gnome/bionic,now 1.2.4-6 amd64 [installed]
`
As for d-feet, I'll try and summarise this (i've reconnected to the VPN a number of times without restarting)

ActiveConnection/1
- Devices/2
- IP4Config/4
ActiveConnection/50
- Devices/2
- IP4Config/55
ActiveConnection/51
- Devices/28
- IP4Config/54

Devices/2
-ActiveConnection/1
-IP4Config/4
Devices/28 (the tun)
-ActiveConnection/51
-IP4Config/54

IP4Config/4 is my local wired.
IP4Config/54 is the VPN, but searches and nameservers are empty. Other address and route data is fine.
IP4Config/55 also contains VPN related IP/routing and contains entries for searches and nameservers.
['a.domain,b.domain'] (a single string value, not two)

If there's something more specific you need, let me know.

**Comment by poettering** [comment] 2018-12-04 16:50
OK, so given the d-feet output this looks like a problem between vpnc and NM. Please report it there.

Let's close this here hence.

**Closed as completed by poettering** 2018-12-04 16:50 UTC
Labels: resolve, not-our-bug

**Comment by stefan-muc** [comment] 2024-09-17 10:18
@Techinica Did you find a solution for this?
Google brought me here. I have quite the same issue here with a bit different setup:

**systemd version the issue has been seen with**
>systemd/noble-updates,now 255.4-1ubuntu8.4 amd64

**Used distribution**
> Ubuntu 24.04 LTS as guest in VirtualBox 7.0.20
> (as far as I remember, I didn't have the problem with `Ubuntu 22.04 LTS`)

**Unexpected behaviour you saw**
```text
$ resolvectl status
Global
         Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
  resolv.conf mode: stub

Link 2 (enp0s3)
    Current Scopes: DNS
         Protocols: +DefaultRoute -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: <vpn 1>
       DNS Servers: <vpn 1> <vpn 2> <home>
        DNS Domain: home\044vpn.domain
```

**Steps to reproduce the problem**
> Connect to Cisco AnyConnect VPN on the Win 11 **host** system (which is used by NAT on the Ubuntu guest)

Regarding `network-manager`:
> $ apt list --installed |grep network-m
> 
> network-manager-config-connectivity-ubuntu/noble,noble,now 1.46.0-1ubuntu2 all [installed]
> network-manager-gnome/noble,now 1.34.0-1ubuntu3 amd64 [installed,automatic]
> network-manager-openvpn-gnome/noble,now 1.10.2-4build2 amd64 [installed]
> network-manager-openvpn/noble,now 1.10.2-4build2 amd64 [installed,automatic]
> network-manager-pptp-gnome/noble,now 1.2.12-3build2 amd64 [installed]
> network-manager-pptp/noble,now 1.2.12-3build2 amd64 [installed,automatic]
> network-manager/noble,now 1.46.0-1ubuntu2 amd64 [installed]

I'm not keen with `d-feet` - installed the apt package with the same name. This gives me a GUI, but filtering for the outputs for `Connection`, `Config`, `IP4` gives me no results.
